### ISSUE TITLE
[Bug] Annotations disappear with time range bigger than 15 minutes

### ISSUE THREAD

**Issue by cvortmann** [grafana/grafana#7837] opened 2017-03-15 11:11 UTC
- What Grafana version are you using?
grafana-4.1.2-1486989747.x86_64

- What datasource are you using?
Graphite 0.9.14

- What OS are you running grafana on?
CentOS Linux release 7.2.1511

- What did you do?
Used a quick time range of _Last 6 hours_.

- What was the expected result?
Annotations lines should still be shown.

- What happened instead?
Annotations lines disappeared.

It seems the `div` gets a negative `left` which make the lines disappear when using Graphite Annotations based on Graphite Events. Using a Graphite Annotation based on metrics still plot the annotation line.

Zoomed into the line and inspected:
![1](https://cloud.githubusercontent.com/assets/189174/23945861/6b72405e-0978-11e7-8cd9-57511afb2032.jpg)

Then started to zoom out by pressing _Zoom Out_ button:
![2](https://cloud.githubusercontent.com/assets/189174/23945864/6b91f9ee-0978-11e7-865f-629c082042c9.jpg)
![3](https://cloud.githubusercontent.com/assets/189174/23945865/6b93136a-0978-11e7-9222-5d2d2888b569.jpg)
![4](https://cloud.githubusercontent.com/assets/189174/23945867/6b955be8-0978-11e7-8d90-e96dedca0d68.jpg)
![5](https://cloud.githubusercontent.com/assets/189174/23945863/6b91296a-0978-11e7-9066-87f58e14f07e.jpg)
![6](https://cloud.githubusercontent.com/assets/189174/23945866/6b93781e-0978-11e7-923d-84606a291b80.jpg)
![7](https://cloud.githubusercontent.com/assets/189174/23945862/6b866b4c-0978-11e7-9691-c90dc8376adb.jpg)

Then selected Quick Range of _Last 6 hours_:
![8](https://cloud.githubusercontent.com/assets/189174/23945868/6b9a9b1c-0978-11e7-8282-5a5c181b9e42.jpg)

**Comment by daveman1010221** [comment] 2017-03-15 13:25
I am having issues with Grafana annotations, as well. I am using the latest testing version, which fixed an issue I was having with missing icons on Ubuntu. I am also performing Lucene queries of elasticsearch. Everything is happy until I attempt to render data from nine cluster nodes. 8 works great. 9 is too much. I'm considering opening a separate issue on this, but it seemed too coincidental that someone else was reporting issues with rendering of annotations, so close in time to what I am seeing with the latest testing build.

**Comment by torkelo** [comment] 2017-03-15 14:43
@cvortmann what is the response from graphite for the 6 hour query?

**Comment by torkelo** [comment] 2017-03-15 14:46
seems to work here with Graphite annotations:
http://play.grafana.org/dashboard/db/annotations-graphite

**Comment by daveman1010221** [comment] 2017-03-15 15:47
Please ignore my previous comment. I tracked down the problem I was having to a data anomaly, Grafana annotations are working fine now.

**Comment by cvortmann** [comment] 2017-03-15 16:02
@torkelo the `graphite` annotation is using _Graphite metrics query_. Those seem to work fine, we had both in our graphs and they continue to show. But the ones that were _Or Graphite events query_ disappeared.

I've manually made a request to graphite server with `{{graphite}}/events/get_data?tags=deploy&from=x&to=y` where x was the unix time of 6h ago and y was the unix time of 1h from now and I got a response with the 3 events I was expecting.

I also tried to record a movie/gif to show it now but it seems the lines are now showing. Is possible that this is related to timezone transformation. The events time are in UTC and Grafana was using, by default, the browser user time which is UTC+1.

**Comment by torkelo** [comment] 2017-03-16 07:46
ok, closing in the meantime. Let me know if still think there might be an issue

**Closed by torkelo** 2017-03-16 07:46 UTC

**Comment by cvortmann** [comment] 2017-03-16 09:02
Yes, is still happening, check the following demonstration:

![kapture 2017-03-16 at 10 01 46](https://cloud.githubusercontent.com/assets/189174/23988690/98daae16-0a2f-11e7-980b-6a02c79c1d63.gif)

**Comment by cvortmann** [comment] 2017-03-16 09:04
The Graphite event has the following info:

```
...
"when": 1489654146,
...
```

**Comment by torkelo** [comment] 2017-03-16 10:17
And the response from Graphite for the annotation query? Open chrome dev tools network tab, and see the response from graphite events

**Comment by cvortmann** [comment] 2017-03-16 11:02
@torkelo it seems to be related to browser used:

Safari:
![safari](https://cloud.githubusercontent.com/assets/189174/23993284/44706fda-0a40-11e7-8574-052f3a325d18.jpg)
Firefox:
![firefox](https://cloud.githubusercontent.com/assets/189174/23993282/43244732-0a40-11e7-90af-e8c80249febe.jpg)
Chrome:
![chrome](https://cloud.githubusercontent.com/assets/189174/23993280/418f0272-0a40-11e7-86dd-7f20ed73a240.jpg)

**Comment by cvortmann** [comment] 2017-03-16 11:10
And when it does, it doesn't transfer any data:

![screen_shot_2017-03-16_at_12_08_53](https://cloud.githubusercontent.com/assets/189174/23993596/7f20f306-0a41-11e7-85d8-5d7df7cebeba.jpg)

**Comment by torkelo** [comment] 2017-03-16 11:21
So when the graph  is empty, no request get_data request is made? or is there a request made but no response?

**Comment by cvortmann** [comment] 2017-03-16 12:29
Both. On previous screenshot there was 3 `render` before the first `get_data`. What I did was change the quick range 3 times. Only in the third time it made the request to `get_data`. But then the request transferred nothing.

The following requests to `render` where requests every 1m given the refresh time.

I've also made the same request using Postman and I get data.

**Comment by cvortmann** [comment] 2017-04-06 17:35
@torkelo did you had the chance to look into it?

**Comment by torkelo** [comment] 2017-04-06 17:38
no :( maybe it's a browser cache issue?

**Comment by cvortmann** [comment] 2017-04-07 11:53
@torkelo it may be the underlaying way that Safari (+ javascript lib used) performs the request and/or cache it. A friend had the same issue when he switched from Chrome to Safari.

**Comment by cvortmann** [comment] 2017-06-01 16:09
@torkelo is seems it's not a Safari only issue. Today I got the same issue in Chrome and Firefox consistently. The browser also showed the request to Graphite for events as cached. So it would should 2 existing lines that were there but not a more recent one that was just emitted.

**Comment by cvortmann** [comment] 2017-06-19 08:03
@daniellee would this be re-opened? Or is being look up elsewhere? 😊

**Comment by torkelo** [comment] 2017-06-19 12:43
No we had trouble replicating it. Can you replicate it with caching disabled? 

Caching should not be an issue as the time range is included in url so the url is different when you change time range.

**Comment by cvortmann** [comment] 2017-06-27 15:20
@torkelo disabling or clearing the cache shows the vertical bar.

**Comment by daniellee** [comment] 2017-06-27 18:06
@cvortmann do you mean that it works when you clear the cache? Or?

**Comment by cvortmann** [comment] 2017-06-28 07:59
@daniellee I'm sorry, yes, it works when one clears the cache.

**Comment by daniellee** [comment] 2017-06-28 09:04
Really strange, cannot reproduce this at all. Are you sure there is no proxy that is caching requests?

Can you follow the steps in this StackOverflow answer to get the cache settings for the ajax requests:

https://stackoverflow.com/a/42450868/22688

As an example from our production Grafana (though most responses have no cache-control header):

![image](https://user-images.githubusercontent.com/434655/27628872-a88a2dba-5bf0-11e7-87ca-260d960ddb79.png)

**Comment by cvortmann** [comment] 2017-06-28 13:11
![response headers - cache control](https://user-images.githubusercontent.com/189174/27638547-edeae6e2-5c13-11e7-8719-1550f5871717.jpg)

![network tab](https://user-images.githubusercontent.com/189174/27638554-f20e0146-5c13-11e7-9749-b96e688513df.jpg)

**Comment by daniellee** [comment] 2017-06-28 13:21
There's your answer. Apache is caching that request for 604800 seconds (or 168 hours). Don't think it is anything to do with Grafana. Do the `render` requests have a similar Cache-Control header?

**Comment by cvortmann** [comment] 2017-06-28 15:41
@daniellee I don't believe the `render` request have such Header. Thanks for the input. I'll look into our cache configuration.

**Comment by cvortmann** [comment] 2017-07-03 15:36
@daniellee @torkelo indeed our cache configuration was caching requests to `get_data` for a week and causing the issue. Thanks for help! We don't see the problem anymore.

**Comment by daniellee** [comment] 2017-07-04 07:07
Great that you finally solved it!
