### ISSUE TITLE
Alert "group" pause / resume

### ISSUE THREAD

**Issue by squalou** [grafana/grafana#32091] opened 2021-03-18 09:32 UTC
**What would you like to be added**:

Being able to pause and resume several alerts at a time.
Ideally defining a group of alerts, then pause / resume this group.
One could even imagine a "planned pause" for some alerts.

**Why is this needed**:

When performing - for instance - maintenance operations on my systems, I pause several grafana alerts.
More and more alerts. .. so I may miss some of them, forget to resume some.

At the moment, having a "pause all" button would be a quick win, but obviously... a more fine-grained mechanism would be better.

The idea behind this is to avoid "false positive alerts" when monitored systems are down on purpose.

For planned maintenance operations, having a kind of scheduled down time with paused alerts would be cherry on the cake.

**Comment by zoltanbedi** [comment] 2021-03-23 16:02
I think this issue is a duplicate of https://github.com/grafana/grafana/issues/6500

**Closed by zoltanbedi** 2021-03-23 16:02 UTC

**Comment by squalou** [comment] 2021-03-23 18:01
indeed ! thanks I'll follow this one
