### ISSUE TITLE
Feature request:  Pin to a specific time zone

### ISSUE THREAD

**Issue by olourkin** [grafana/grafana#2658] opened 2015-09-02 17:01 UTC
We've standardized on Eastern time for all our far-flung server clocks and other technical time references, so it would be a very nice addition to a very nice app if I could pin Grafana to always display using a specific time zone, in the same manner as Graphite.

**Comment by torkelo** [comment] 2015-09-02 17:04
duplicate of https://github.com/grafana/grafana/issues/558

**Closed by torkelo** 2015-09-02 17:04 UTC
