### ISSUE TITLE
Support default data source when defining variables using a query

### ISSUE THREAD

**Issue by rvdheij** [grafana/grafana#27180] opened 2020-08-25 06:43 UTC
**What would you like to be added**:
When defining template variables to be populated by a query, the pull-down menu of data sources does not include the "default" data source. As long as you're careful and use the default, panels will just work when moving to a new data source.
**Why is this needed**:
Copying dashboards to another system using another data source requires that you go into each dashboard and change all the template variables to issue the query against the new data source (forgetting keeps you busy for a while trying to understand why some data is missing from the variable pull-down at runtime).

I can see some issues when the actual data source *type* is not known when defining the variables. I would be happy to already specify the type of data source (like InfluxDB) and allow only the specifics to change (and reject at runtime when the actual data source isn't that type).

**Comment by torkelo** [comment] 2020-08-25 06:46
duplicate of https://github.com/grafana/grafana/issues/24765

**Closed by torkelo** 2020-08-25 06:46 UTC

**Comment by rvdheij** [comment] 2020-08-25 22:31
My apologies. I hadn't found the open issue.

**Comment by Mario-Hofstaetter** [comment] 2021-07-29 13:30
@rvdheij JFYI, since I don't think github notifies in this case.
My #24765 has been closed in the current cleanup process.
