### ISSUE TITLE
Support ad hoc filters with non-string values

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#28338] opened 2020-10-17 00:06 UTC
**What would you like to be added**:
Support for numbers, at least. I can't think of any other types that would need support.

**Why is this needed**:
We're currently forced to convert from number to string and back within a plugin's data source to avoid issues with—at least—[`escapeDelimiter()`](https://github.com/grafana/grafana/blob/master/public/app/features/variables/adhoc/urlParser.ts), which makes for messier source code. [`Datasource::getTagValues()`](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/datasource.ts) current expects a return value of `{ text: string }` when it should probably instead expect `{ key: string, label: string, value: string | number }`.

@scottlepp @dprokop @ryantxu @torkelo

**Comment by torkelo** [comment] 2020-10-17 07:08
sounds like a possibility, not sure templating is already so complicated so dealing with numbers and strings could be messy. 


Duplicate of #12209

**Closed by torkelo** 2020-10-17 07:08 UTC
