### ISSUE TITLE
tooltip values mix current and old/stale values which is very confusing

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#21317] opened 2020-01-02 10:47 UTC
Grafana v6.5.2 (742d165)
why is the popup showing values that don't exist on the chart?

![grafana-popup-huh](https://user-images.githubusercontent.com/20774/71663423-72d12280-2d55-11ea-8483-405549fb825f.png)
i have switched lines to point mode, but i don't see any data corresponding to these low values reported in the popup.

for live dashboard go to metrictank-v0-13-1-weird-bug-temp-dieter in our ops grafana.

**Comment by Dieterbe** [comment] 2020-01-02 10:49
I think i just figured it out thanks to points mode: it's showing the last values of some series that have ended days ago. this is very confusing.

**Comment by torkelo** [comment] 2020-01-02 12:19
dupe of https://github.com/grafana/grafana/issues/6946 

Changing null value mode to null or null as zero should fix it  (connected = throw away null values, so the number of data points in the series no longer match)

**Closed by torkelo** 2020-01-02 12:19 UTC

**Comment by Dieterbe** [comment] 2020-01-02 12:35
null as null shows no numbers at all in the tooltips!
null as zero gives makes things even worse. now i still have the stale stats that i don't want to see, but i can't differentiate stale from current anymore.

**Comment by torkelo** [comment] 2020-01-02 12:39
> null as null shows no numbers at all in the tooltips!

Of course null show no number, what number should we show if the current value you hover over for a series is null?

**Comment by Dieterbe** [comment] 2020-01-02 12:44
well, to clarify. with "null as null" in my example, there's so many nulls, that i don't see any of the actual values that i want to see, because in sort order "increasing" the nulls are assumed to be lower than my actual data. I can work around it by changing order to "decreasing" but that wasn't really what I wanted either.

**Comment by torkelo** [comment] 2020-01-02 15:23
Ah ok, then I understand. Grafana Should filter out and not show null values in tooltip I think (by default m)

**Comment by torkelo** [comment] 2020-01-02 15:24
By should I mean I wish it did :)

**Comment by Dieterbe** [comment] 2020-01-02 15:27
or make it a setting? should we open a new ticket for that?
