### ISSUE TITLE
[Bug] Description tooltip is not fully displayed

### ISSUE THREAD

**Issue by Nailya** [grafana/grafana#7970] opened 2017-03-28 17:33 UTC
- What Grafana version are you using?
4.2.0
- What datasource are you using?
Prometheus
- What OS are you running grafana on?
CentOS Linux release 7.3.1611 (Core)

- What did you do?
I added description to a chart

- What was the expected result?

See screenshot 1:
![1](https://cloud.githubusercontent.com/assets/4751060/24418688/7b646730-13f5-11e7-958a-33d2b84b7e16.png)
- What happened instead?
Description tooltip is cut off
See screenshot 2:
![2](https://cloud.githubusercontent.com/assets/4751060/24418720/8f888c00-13f5-11e7-9e7a-45a8a9de9e8d.png)

With Grafana 4.1.2 everything looks OK

**Comment by daniellee** [comment] 2017-03-29 06:51
Confirmed. Will do a fix for this straight away.

**Comment by torkelo** [comment] 2017-03-29 06:53
might have been caused by this fix
https://github.com/grafana/grafana/pull/7854

**Comment by daniellee** [comment] 2017-03-29 07:12
@torkelo I tested #7854 and it wasn't the cause. git bisect says that it is this commit: https://github.com/grafana/grafana/commit/23eab81cbe3aade48e9ab0eaa2f0584a12706076 and this issue: #7357

Basically when we moved it from right middle to top center.

Going to test a bit more and see if I can keep it top center but move it to the right a bit.

**Comment by daniellee** [comment] 2017-03-29 07:37
The easy fix is to change the position of the popover from `top center` to `top left`:

![image](https://cloud.githubusercontent.com/assets/434655/24443504/32bff8d2-1463-11e7-835e-f1a88a91f210.png)

Reading through issues to see if it breaks anything else...

**Closed** 2017-03-29 09:25 UTC
Labels: comp: panel/common, P1: urgent, type: bug

**Comment by daniellee** [comment] 2017-03-29 09:26
Thanks @Nailya for reporting this. The fix will be included in the next release.

**Comment by tw-bert** [comment] 2017-04-18 06:59
Also encountering this issue after upgrading from 4.1.2 to 4.2.0. 
Any idea of the next release date? We prefer not to downgrade because of the new 'autorefresh via url parameter' functionality (great!) which is used a lot already. 
I'm tempted to use a nightly build for production (backups are verified and in place), but only see 4.3 nightly builds (and confused by older rev numbers in the name than this fix) and a 4.2.0beta. Recommendations?

**Comment by daniellee** [comment] 2017-04-19 08:06
@tw-bert it will be at least a couple of weeks (maybe up to two months) before we release 4.3.0. This is the latest nightly build: https://grafana.com/grafana/download/4.3.0-7571pre1

**Comment by tw-bert** [comment] 2017-04-19 08:10
@daniellee thx for the info. We have worked around it by running an older version (4.1.2) of Grafana on a different port for reading pages with instructions in panel tooltips.
