### ISSUE TITLE
Grafana init failed because connecting to mysql failed

### ISSUE THREAD

**Issue by like-inspur** [grafana/grafana#42495] opened 2021-11-30 06:33 UTC
**What happened**:
I install grafana on kubernetes, config storage mysql,  grafana start need to conect mysql to init  tables, but in this process mysql cluster do active-standby switch, therefore grafana start failed. When pod tries to restart, grafana init still failed. Log like below
![1](https://user-images.githubusercontent.com/18571465/143996912-78e2509f-0916-4603-bc9f-f656c3a2f9f0.png)

**Anything else we need to know?**:
I check mysql migration_log and find rename table not be record into it, so next time grafana still can't start
![2](https://user-images.githubusercontent.com/18571465/143997181-2b7466f4-a9c0-4e76-89a7-02cc2b6347fd.png)

**Environment**:
- Grafana version:  7.1.3

**Comment by ying-jeanne** [comment] 2021-11-30 13:05
Hi @like-inspur could you provide the old version of grafana, and the new version that you plan to update to, so we could be able to reproduce the senario.

Thanks,

**Comment by like-inspur** [comment] 2021-12-07 01:09
Hi @ying-jeanne current version is 7.1.3, plan to update to 7.4.5

**Comment by marefr** [comment] 2021-12-07 17:15
Duplicate of #13497

**Comment by marefr** [comment] 2021-12-07 17:15
Closing this as duplicate

**Closed by marefr** 2021-12-07 17:15 UTC
Labels: area/backend/db/mysql, area/backend/db/migration
