### ISSUE TITLE
Login doesn't work after registering via invite link

### ISSUE THREAD

**Issue by tneumueller** [grafana/grafana#21191] opened 2019-12-19 12:39 UTC
**What happened**:
After a user accepted the invitation sent via email and created his account, he is redirected to the login page from where he cannot sign in. The frontend says "Login successfull" and redirects back to the login page. Our customer had this problem and we are able to reliably reproduce it locally.

**What you expected to happen**:
I would like to be able to login.

**How to reproduce it (as minimally and precisely as possible)**:
Invite a user to an org, user accepts invitation and creates account, tries to login afterwards but can't.

**Anything else we need to know?**:
Tried to delete all cookies and local storage, issue persists. Switching browsers (i.e. accepting the invite with safari and then logging in with chrome or vice versa) made the issue disappear, so did switching the computer.

**Environment**:
- Grafana version: grafana/grafana:latest image from docker hub
- Data source type & version: PostgreSQL version 11.5
- OS Grafana is installed on: grafana/grafana:latest image from docker hub
- User OS & Browser: Brave v1.0.1, Chrome 79.0.3945.88 (64 bit), Safari 13.0.3 (15608.3.10.1.4), Safari 13.0.4 (15608.4.9.1.3), MacOS Catalina 10.15.1 (19B88)
- Grafana plugins: grafana-piechart-panel
- Others: -

**Comment by marefr** [comment] 2019-12-20 09:55
Works as expected to me. When signup is complete you should be logged in and for you seems like not and is redirected to login page, login again successfully, but cookie not accepted in browser so redirected back at login screen again. Seems like you have a problem with setting cookies.

After complete of signup you should get a grafana session cookie as seen here:
![image](https://user-images.githubusercontent.com/1668778/71246338-bc158100-2316-11ea-9bfa-edb68add066f.png)

Would suggest looking into https://grafana.com/docs/grafana/latest/installation/configuration/#cookie-samesite and https://grafana.com/docs/grafana/latest/installation/configuration/#cookie-secure.

**Comment by marefr** [comment] 2019-12-20 09:55
Duplicate of #18690

**Closed by marefr** 2019-12-20 09:55 UTC
Labels: needs investigation

**Comment by tneumueller** [comment] 2019-12-20 10:25
I doubt that this is a duplicate of #18690.
I tried something new, and after logging in (and being redirected at the login page again) I can manually navigate to `/?orgId=1` without problems, so I think setting the session cookie works, because otherwise would I be able to access anything inside the app? Also I think that this is a redirect issue in grafana.

Also I don't see which request you're referring to in your screenshot, I can't find that one in my dev tools:

![Bildschirmfoto 2019-12-20 um 11 23 56](https://user-images.githubusercontent.com/28784529/71248494-41029980-231b-11ea-8e46-486b8dd9c093.png)

**Comment by marefr** [comment] 2020-01-10 10:41
@tneumueller my screenshot is with preserve logs and accepting invite is the request I underlined. Are you by any chance using some custom configuration, please include that. Maybe custom `org_name`? 

Almost sounds like user in question you're testing with don't have a correct org id assigned as the default. If you could check in the user table in the database what is the value of org_id and in org_user table of that user you may find some clues. Grafana server log may be able to give some additional clues.
