### ISSUE TITLE
gauge panel: disable legend 

### ISSUE THREAD

**Issue by tobias-d-oe** [grafana/grafana#27544] opened 2020-09-11 13:06 UTC
**Steps to reproduce**:
Create a gauge panel on dashboard

**Actual Result**:
very big legend is visible and if set legend to blank sign the size from the gauge element not uses all the space possible.
![is](https://user-images.githubusercontent.com/12530915/92929070-44592a80-f440-11ea-99ce-293bd33d70a9.png)

**Expected Result**
can hide legend at all to use all the possible space.
![should-be](https://user-images.githubusercontent.com/12530915/92929075-458a5780-f440-11ea-8484-b6792c65ea4d.png)

**Relevant WCAG Criteria:** 
none

**Environment**:
- Grafana version: 7.5.1
- Data source type & version: prometheus (core)
- User OS & Browser: Linux & FireFox
- Others: -

**Comment by marefr** [comment] 2020-09-11 15:55
Duplicate of #19957

**Closed by marefr** 2020-09-11 15:55 UTC
Labels: area/panel/gauge, type/feature-request

**Comment by torkelo** [comment] 2020-09-11 15:57
this looks like a single panel only, and that is fixed in 7.2-beta1
