### ISSUE TITLE
Raw graphite query editor on Chrome force text cursor to the end of line

### ISSUE THREAD

**Issue by ADovgalyuk** [grafana/grafana#56683] opened 2022-10-11 10:16 UTC
Hi Team,
OS: Linux Ubuntu 22.04
Browser: chrome Version 106.0.5249.103 (Official Build) (64-bit)
Grafana: v9.0.6 and 8.5.11

Using graphite as a source. While editing query in raw mode, cursor force-switch to the end of line after every entered symbol (in any place). Example from "incognito mode" so all browser extensions are disabled. GIF attached.

![Query_graphite](https://user-images.githubusercontent.com/56922689/195062514-5777aed4-33ef-4dd4-98c8-cdf4d7bd59b9.gif)

On the "Firefox 105.0.3 (64-bit)" same OS, it's working fine, can't reproduce.

**Comment by gelicia** [comment] 2022-10-12 02:25
Duplicate of #54535 - please update to 8.5.13 to pick up the update needed for Grafana's query editor to work with Chrome 105.0.5195.52 or later

**Closed by gelicia** 2022-10-12 02:25 UTC
