### ISSUE TITLE
InfluxDB: Alert is not sent when the requirement is meet

### ISSUE THREAD

**Issue by xupy01** [grafana/grafana#34538] opened 2021-05-21 02:06 UTC
**What happened**:
    I have an alarm strategy. In the first picture, 873 has =0% and lasted for 7 minutes, but no alarm occurred. This problem is not always the case. This problem has puzzled me for a long time.
**What you expected to happen**:
    Send an alarm when the alarm threshold is lower than
**How to reproduce it (as minimally and precisely as possible)**:
    Occasionally irregular
**Anything else we need to know?**:

**Environment**:
- Grafana version: 
   grafana-7.3.2-1.x86_64
- Data source type & version:
   influxdb
- OS Grafana is installed on:
   centos 6.5
- User OS & Browser:
   win10  Chrome
- Grafana plugins:
- Others:
![image](https://user-images.githubusercontent.com/46221102/119071303-222a9a00-ba1c-11eb-83e1-1bae548b4162.png)
![image](https://user-images.githubusercontent.com/46221102/119071317-28207b00-ba1c-11eb-922a-9cf584d04d27.png)
![image](https://user-images.githubusercontent.com/46221102/119071329-2e165c00-ba1c-11eb-85b3-1ccc3766c7b8.png)

**Comment by aocenas** [comment] 2021-06-04 09:17
@xupy01 Wouldn't it make more sense to create separate alert for each of the conditions? I think the problem is that you have only single condition for the alert, so you get alert for the first "or" clause that matches and that is it. It does not treat each "or" clause as separate alert. In this case it seems the 855 series was also bellow the threshold and it triggered the alarm so we do not evaluate the other "or" clauses (because the whole condition is true at that moment).

**Comment by aocenas** [comment] 2021-06-16 08:43
Closing this, if there is any new information please reopen

**Closed by aocenas** 2021-06-16 08:43 UTC
Labels: area/alerting, datasource/InfluxDB, needs more info
