### ISSUE TITLE
[Loki] Impossible to create a variable with label_values(log stream selector, label)

### ISSUE THREAD

**Issue by pbrissaud** [grafana/grafana#38619] opened 2021-08-26 21:53 UTC
**What happened**: When I create a variable with **"label_values(log stream selector, label)** , I get these following errors :
*  _Validation_ parse error at line 1, col 14: literal not terminated
* _Templating [severity]_ Error updating options: parse error at line 1, col 14: literal not terminated

**What you expected to happen**: No errors and preview of values updated

**How to reproduce it (as minimally and precisely as possible)**:
  1. Go to Dashbboard -> Create variables
  2. Choose Loki and try a query with log stream selector :
  `label_values({job="syslog"}, severity)`
 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: Loki 2.3.0
- OS Grafana is installed on: Ubuntu 20.04.3
- User OS & Browser: Manjaro 21.1.0 / Firefox 91.0.2
- Grafana plugins: 
- Others:

![Screenshot_20210826_233448](https://user-images.githubusercontent.com/27202456/131040377-12f9aab8-94da-4048-a68f-fa4e733c3467.png)

**Comment by loganmc10** [comment] 2021-08-29 13:31
This kind of thing happens to me sometimes when I'm making Loki dashboards. Sometimes it complains about a syntax error, when everything is correct. If I refresh the dashboard, the error goes away.

It's like it's still caching what I typed in previously or something. I'm guessing that's why it's complaining when you type it out, it's not registering the last thing you typed.

**Comment by pbrissaud** [comment] 2021-08-29 13:35
Yeah, it looks like caching problems or something like that ! It's very frustrating when it happens but that's life !

I don't know if this issue needs to stay open.

**Comment by hugohaggmark** [comment] 2021-09-02 08:03
Moving this to @grafana/observability-squad , feel free to pass it back to UE if this is a general issue unrelated to Loki.

**Comment by Elfo404** [comment] 2021-09-02 14:28
Hi @pbrissaud , this looks very weird

looking at your screenshot it seems the first quote is a single quote, while the second one seems a double quote.

**Comment by pbrissaud** [comment] 2021-09-02 14:44
Hi @Elfo404 , the screenshot is a little blur (sorry for that) but I'm sure there are 2 double quotes 😄

**Comment by ivanahuckova** [comment] 2021-09-06 08:47
@pbrissaud Could you please paste the whole error from the console and also if there are errors in network tab. That would be super helpful! 🙏

**Comment by pbrissaud** [comment] 2021-09-11 19:53
hi @ivanahuckova , I tried to reproduce the bug with the same setup (same pc, same browser, same Grafana version) but I couldn't .
This bug is making me so crazy !

**Comment by hugohaggmark** [comment] 2021-09-13 04:03
Closing this issue because it seems hard to reproduce and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2021-09-13 04:03 UTC
Labels: type/bug, area/dashboard/templating, needs more info, datasource/Loki
