### ISSUE TITLE
Overflow (scrollbar) behavior in Table-Panel (Pagination)

### ISSUE THREAD

**Issue by SensSebastianSchlosser** [grafana/grafana#60963] opened 2023-01-04 13:30 UTC
**What happened**:
There is a weird overflow behavoir on the pagination since v9. Scollbar appears. 

**What you expected to happen**:
There is no overflow (Scollbar)

**How to reproduce it (as minimally and precisely as possible)**:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/117441229/210564681-7a4e74a5-8b13-48ca-96fa-37ae1682a759.png">
Create a table with more than one page (enable pagination). (like in screenshot) Than cause the right flex div "1 - 12 of 2859 rows" to be visible in multiple lines. now a scollbar appears for the whole table. You can achieve that with creating the table with gridpos: w: 12 and h: 14

**Anything else we need to know?**:
-

**Environment**:
- Grafana version: 9.2.7
- Data source type & version: -
- OS Grafana is installed on: Linux
- User OS & Browser: Everywhere
- Grafana plugins: -
- Others: -

**Comment by mellieA** [comment] 2023-01-06 01:26
@SensSebastianSchlosser It looks like the scrollbar was intentionally added in 9.2 here https://github.com/grafana/grafana/pull/53457 

In my tests on 9.3.2 the scrollbar only appears if I hover on a cell in the table and slide left or right (on my mac mouse) to view columns that are outside of the viewable area. I did notice that in one instance while that panel was in focus and I left the browser tab then returned the scrollbar was visible until I clicked on another panel (then I couldn't reproduce it again). Is this what you're seeing?

**Comment by torkelo** [comment] 2023-01-06 06:58
This should be fixed in main, the calculation for rows per page was slightly off so sometimes the scrollbar was shown even when pagination was enabled

**Comment by SensSebastianSchlosser** [comment] 2023-01-09 09:24
I don't know, what "be fixed in main" means, but @torkelo is right. The calculation for row per page was off.
Glad to hear, that there is a fix right now.
You can close this issues, after explaining, on which version it is fixed.

Thank you for your answers!

**Closed** 2023-07-15 00:51 UTC
Labels: needs more info
