### ISSUE TITLE
Elasticsearch 7.x support

### ISSUE THREAD

**Issue by UKSFM99** [grafana/grafana#15622] opened 2019-02-24 15:57 UTC
### What Grafana version are you using?
6.0.0 beta 3
### What datasource are you using?
Elasticsearch 7.0.0 beta 1
### What OS are you running grafana on?
Ubuntu
### What did you do?
After upgrading a Elasticsearch cluster from 6.6 to 7.0 beta 1, I can no longer add new indices as seperate datasources to grafana, due to the following error:
![image](https://user-images.githubusercontent.com/14551965/53301544-1c997600-384c-11e9-9eb6-b484183d70e0.png)

However, current data sources that were created when the cluster was 6.6.0 now no longer work, all charts display the following error:
![image](https://user-images.githubusercontent.com/14551965/53301565-45217000-384c-11e9-9104-bd96d36f738c.png)

Some useful F12 sceenshots to help:
1. Response when using old data sources after upgrading to Elasticsearch 7.0:
![image](https://user-images.githubusercontent.com/14551965/53301581-6aae7980-384c-11e9-8f35-161cd7468830.png)

2. Response when trying to create new data sources that are 7.0:
the _mapping Json is the following:
```
{"logging-2019.02.24":{"mappings":{"properties":{"@timestamp":{"type":"date"},"@version":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-City":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-Country-Code":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-Env":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Host-Type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"HostName":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"Log-Event":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},,"host":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"port":{"type":"long"},"type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}}
```
Which clearly shows the @timestamp field as being of type 'date', even though grafana complains that @timestamp field does not exist

**Comment by marefr** [comment] 2019-03-05 21:20
Regarding max_concurrent_shard_requests the semantics has changed to be the maximum and now defaults to 5 instead of 256: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_semantics_changed_for_literal_max_concurrent_shard_requests_literal

**Comment by Julzorensen** [comment] 2019-04-11 11:46
Hey guys,

Elastic Stack v7 is now GA, some production cluster will be (or are already) upgraded.
Mine is now in full 7.0.0 and I encouter the exact same problem.

Basicly, Grafana seems to not support this new version of ElasticSearch.

Any idea when it'll be fixed?

**Comment by danielfariati** [comment] 2019-04-11 18:08
Same problem here. We upgraded our production cluster and now Grafana stopped working.

Also, when trying to save new Datasources, an error is thrown: `No date field named @timestamp found` (even though the field exists).

**Comment by creaticious** [comment] 2019-04-12 08:05
Same here...upgraded today, can't update datasource because of @timestamp not found...
Maybe this is related to the deprecation of document types in ES 7.0...?

**Comment by c0r3xxx** [comment] 2019-04-12 10:48
we upgraded today too.. same here

**Comment by robertotrgt** [comment] 2019-04-12 15:12
Same over here, upgraded yesterday to ES7, noticed today grafana is not working with that cluster.

**Comment by marefr** [comment] 2019-04-15 07:56
We're planning to fix this for Grafana v6.3 where stable is ~6 weeks forward, but will probably land in master/nightly earlier.

**Comment by hastarin** [comment] 2019-04-17 07:00
As another person who forgot all about Grafana and broke their production dashboard by upgrading things without testing first (and I even have an ELK dev stack in Docker Swarm) I would love some hints on what I might be able to do to assist in testing any early releases of a fix for this?

I've had to embed a Kibana dashboard via an iframe for now.

**Comment by alcidesv** [comment] 2019-04-17 07:21
@hastarin 

Here is a docker image for the PR with this feature: eu.gcr.io/shimmercat-pdi-7108/grafana

**Comment by hastarin** [comment] 2019-04-17 08:20
@alcidesv Wow thanks for the prompt response.  I've now built my own image based on that with extra plugins, etc and it's up and running.

I am pleased to confirm that it has solved my issue for the dashboards I have.  Many thanks for your efforts!

**Comment by danielfariati** [comment] 2019-04-17 17:00
I also tested the docker image.
The dashboards are now working again! Thanks, @alcidesv!

The only thing that appears to not be working is the alerting functionality, always returning: `Query Returned No Series (reduced to null/no value)`.

**Comment by marefr** [comment] 2019-04-19 15:00
@danielfariati Thanks for feedback. Fix for that been pushed to #16646, but currently docker image mentioned above have not been updated as far as I'm concerned.

**Comment by PepeLopez** [comment] 2019-04-19 15:10
I don't get it. This thread is about ES7 compatibility, which is not released yet, but ppl talking about an docker image which is working!? Has the docker image  ES7 compatibility, but not the nightly?
The confusion is real...

**Comment by marefr** [comment] 2019-04-20 08:58
@PepeLopez see https://github.com/grafana/grafana/issues/15622#issuecomment-483968475 above

**Comment by PepeLopez** [comment] 2019-04-20 19:02
> @PepeLopez see [#15622 (comment)](https://github.com/grafana/grafana/issues/15622#issuecomment-483968475) above

I did. It's not answering my question. 
Does that docker image fixed the ES7 compatibility?

**Comment by marefr** [comment] 2019-04-21 00:07
@PepeLopez this issue is open because official Grafana support does not currently exists for elasticsearch v7. The docker image above is a build of the ongoing work for adding support for elasticsearch v7 and haev been built by the author of PR #16646. No alerting support in above image as far as I'm concern, but besides that it sort of works. Please try it out if you want and provide feedback, any. Thanks

**Comment by Aaron3** [comment] 2019-04-22 11:00
Any reason why this isn't being back-ported to a minor release?

**Comment by torkelo** [comment] 2019-04-22 16:45
1) Because the features is not implemented / completed yet
2) we normally don’t backport features and enhancements

**Comment by danielfariati** [comment] 2019-04-23 20:59
> @danielfariati Thanks for feedback. Fix for that been pushed to #16646, but currently docker image mentioned above have not been updated as far as I'm concerned.

@marefr  I tested the code pushed to #16646. Everything (including alerts) seems to be working perfectly, now.
Thanks!

**Comment by sirajshe** [comment] 2019-05-01 06:54
I am using the latest nightly build of grafana to connect to ES 7.0. While saving the datasource, it gives an error

"no handler found for uri [/5/1/2019og0tam06-2019.04.14-000001/_mapping] and method [GET]"

The request in the grafana log is recorded as follows. Looks like a jumbled up index name being used.

INFO[05-01|06:49:03] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/5/1/2019og0tam06-2019.04.14-000001/_mapping status=400 remote_addr=xx.xx.xx.xx time_ms=2 size=119 referer=http://xxxxx:2000/datasources/edit/1/

Following is my data source config.

![image](https://user-images.githubusercontent.com/46110311/57008196-3f753d00-6ba3-11e9-944e-00f7d519b0a3.png)

**Comment by dnewsholme** [comment] 2019-05-01 07:01
The fixed build hasn't been released yet.

**Comment by marefr** [comment] 2019-05-01 07:22
@sirajshe and you have selected Hourly as index pattern which seems wrong in your case since you have inserted the full index name in the index name field.

**Comment by sirajshe** [comment] 2019-05-01 17:40
@dnewsholme - The datasource creation UI only options upto 6.0+. Not sure if the nightly build I used has the changes. (version=6.1.6 commit=cf9cb45 branch=HEAD compiled=2019-04-29T13:29:28+0000)

@marefr - Thanks for the pointer. I removed the pattern and now I am back to the original issue in this thread, ie. "No date field named @timestamp found".

**Comment by sirajshe** [comment] 2019-05-01 17:52
Using a 6.2.0 nightly build now. Will update the thread with the results.

**Comment by sirajshe** [comment] 2019-05-01 18:49
Looks good with the latest build. 7.0 option is available and the data source is functional. Thanks for the help.
version=6.2.0-pre commit=157f330 branch=master compiled=2019-05-01T15:20:01+0000

**Comment by drew-o** [comment] 2019-05-01 22:31
Hello, using Grafana v6.2.0-pre (commit: 9cc67e4) and there's no ES 7.0+ option here. Using nightly build (grafana_6.2.0-91846ebepre_amd64.deb) Maybe I'm missing something? Thanks.

**Comment by sirajshe** [comment] 2019-05-02 06:06
I see the nightly build you are using is about 15 days old and there are ES
7.0 support related commits like the following that happened 8 days back.

https://github.com/grafana/grafana/pull/16646/commits/8816d6d112360057f6c27b86cf2224bd245101ec

I used a most recent nightly build v6.2.0-pre (157f330) and I see the 7.0+
options.

**Comment by tonobo** [comment] 2019-05-02 08:25
I'm following grafana master branch and having a elasticsearch cluster with version 6.7.1 running. The alert rule is pointing to 6.0+ but i'm still getting the error `tsdb.HandleRequest() error json: cannot unmarshal number into Go struct field SearchResponseHits.Total of type map[string]interface {}`. This might be related to the 7.0 changes?

**Comment by drew-o** [comment] 2019-05-02 09:37
Oh yes, thanks for the tip, I realised that just after posting the question. Works like a charm now.

**Comment by marefr** [comment] 2019-05-06 08:00
@tonobo thanks for the feedback. That sounds like a bug and we'll fix that for the 6.2-beta1. Re-opening this issue...

**Closed** 2019-05-06 13:12 UTC
Labels: area/datasource, datasource/Elasticsearch, type/feature-request

**Comment by tonobo** [comment] 2019-05-06 13:52
Awsome!

**Comment by arikfre** [comment] 2019-05-28 11:33
Hi,
Any chance there was a regression?
I'm using Grafana 6.2.1 and Elasticsearch 7.1 and I'm getting the mentioned error:
"no handler found for uri [/pro1559001600000y0q5/28/2019_qu2ry_2ig20t_2019.05/_mapping] and method [GET]"

![image](https://user-images.githubusercontent.com/51040837/58474981-5a60b000-8155-11e9-8b15-a7a50b392be5.png)

**Comment by marefr** [comment] 2019-05-28 11:49
@arikfre please use `[query_digest_]YYYY.MM.DD` as index name.

**Comment by arikfre** [comment] 2019-05-28 11:57
@marefr thank you so much. Works perfectly.

**Comment by Ivan-Strahovsky** [comment] 2019-06-12 17:17
ES version 7.1.1. Grafana: 6.2.2. This is what I see in alert state history:

![image](https://user-images.githubusercontent.com/51758236/59371775-8e1e0700-8d0b-11e9-8be6-465b83c8a579.png)

 what is interesting - when I click test rule it always return me OK state. What can be wrong?

**Comment by marefr** [comment] 2019-06-13 08:15
@Ivan-Strahovsky that's interesting. Can you try and re-save your dashboard with the alert rule? Can you show a screenshot of the datasource configuration?

**Comment by Ivan-Strahovsky** [comment] 2019-06-13 14:47
@marefr 
![image](https://user-images.githubusercontent.com/51758236/59442574-19f16b00-8dc0-11e9-89e0-fbfd354189ca.png)
I tried to recreate alert, dashboard, datasource. Result the same.

**Comment by marefr** [comment] 2019-06-17 10:18
Issue #17558 opened for further discussions around latest comments.

**Comment by hackery** [comment] 2019-07-02 18:35
I encountered this today in Grafana v5.4.2 after upgrading our cluster (QA, thankfully!) to 7.1.1, and found a workaround, for existing datasources at least.

When I removed (blanked out) the value from `Max concurrent Shard Requests` and saved, Grafana gave the complaint about `No date field named ... found` as described by OP, but returning to my dashboards, they now work.

In the Query Inspector, I can see that `max_concurrent_shard_requests` is then not included in the `_msearch` metadata section. Copying the query into Kibana devtools, I can reproduce that it works without, and fails with this metadata field. I presumed first that it's simply no longer supported in Elasticsearch 7.x ... but going back through documentation versions for [_msearch](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-multi-search.html), I can't actually find any evidence that it _ever_ was - it seems to be intended as a _query parameter_, not to go in the metadata. How it worked previously might have been an accident. Or, did it ever work? Pre-7.0, Elasticsearch accepted unrecognised fields in the metadata, ignored them, and only even [logged them](https://github.com/elastic/elasticsearch/blob/6.8/server/src/main/java/org/elasticsearch/action/search/MultiSearchRequest.java#L248) if deprecation logging was enabled. [elasticsearch#35938](https://github.com/elastic/elasticsearch/pull/35938) turned that into the "not supported in the metadata section" error we see here.

> Regarding max_concurrent_shard_requests the semantics has changed to be the maximum and now defaults to 5 instead of 256

This is true, but is it relevant? The value being a couple of orders of magnitude out, in existing queries, might cause performance or stability trouble, but shouldn't fail the query.

I'm surmising that when the `Max concurrent Shard Requests` textfield in the Grafana datasource UI has a value, the query fails but Grafana isn't adequately error checking - the first thing it does is look for the requested timestamp field, and of course doesn't find it in the error response, so it pops its own error message.

**Comment by marefr** [comment] 2019-07-02 19:31
@hackery you'll need at least Grafana v6.2.0 for Elasticsearch 7.x support.

**Comment by quim-clar** [comment] 2024-04-30 17:05
I have grafana 10.4.2  and my elasticsearch 6.6.1. When I try to configure elasticsearch as Grafana's Data Source I get "No date field named @timestamp found. But that date field is declared on the elasticsearch index:
![image](https://github.com/grafana/grafana/assets/123154807/bf927d80-f93f-484c-98c6-27f663dd0043)
Any help please?
