### ISSUE TITLE
Plugin: Bar Chart not show data (one row)

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#45575] opened 2022-02-18 05:00 UTC
**What happened**:
Plugin: Bar chart not show data when we have only one row with data. Sometimes data have many rows and show correctly, but sometimes only one row and Bar Char is empty.
**What you expected to happen**:
Fix it :)
**How to reproduce it (as minimally and precisely as possible)**:
Watch video in .gif
![Animation](https://user-images.githubusercontent.com/73607094/154620541-796e19d6-2689-4560-a41c-efd786f04722.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: MS SQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome
- Grafana plugins: Bar Chart
- Others: n/a

**Comment by leeoniya** [comment] 2022-02-21 15:02
duplicate of https://github.com/grafana/grafana/issues/44484?

**Comment by kirederik** [comment] 2022-03-30 15:44
![image](https://user-images.githubusercontent.com/201163/160875778-f1701f11-25b1-4749-9af0-37e30bb86ef7.png)

Looks like it was indeed https://github.com/grafana/grafana/issues/44484.

**Closed by kirederik** 2022-03-30 15:44 UTC
Labels: type/bug, area/panel/barchart
