### ISSUE TITLE
[Feature request] Graph panel - New Focused Hover tooltip Mode

### ISSUE THREAD

**Issue by daveselan** [grafana/grafana#13134] opened 2018-09-04 11:34 UTC
We have a database that contains thousands of uniquely tagged group values and we want to plot activity grouped by this. These values typically don't continue through the time series. When graphing this data and selecting All series for the tooltip, it's possible to be presented with a huge list of values when hovering over the data. Most the values will be zero as they are null for the majority of the plot. Single mode works, but normally we want to see all the activity just for that period.

Could we have a new option that showed only the data for that time group under the pointer or if that's not easy to do, an option that omits zero or null values from the list?
The other idea I've seen mentioned was a capped list, but then even using the sort option, values could be missed off the list and how long is too long?

**Comment by marefr** [comment] 2018-09-04 11:50
Duplicate of #4623 and #6946

**Closed by marefr** 2018-09-04 11:50 UTC
