### ISSUE TITLE
Error downloading plugin manifest keys

### ISSUE THREAD

**Issue by mkur-ops** [grafana/grafana#83059] opened 2024-02-19 12:39 UTC
### What happened?

Grafana keeps failing with `504 Gateway Timeout`. 
After an error appears grafana has to be restarted.

The only error that can be found in logs around the time of failure is `Error downloading plugin manifest keys`

### What did you expect to happen?

Stop failing the key lookup.
Is there any way to disable it?

### Did this work before?

Not after upgrading from version 8. After upgrading to version 9.* and further issue keeps appearing.

### How do we reproduce it?

1. Version: `10.3.1` running as container in openshift cluster.
2. `check_for_plugin_updates` and `check_for_updates` disabled.
3. Cluster behind corporate firewall, cannot access `grafana.com`

### Environment (with versions)?

Grafana: 10.3.1

### Grafana platform?

Kubernetes

**Comment by tolzhabayev** [comment] 2024-02-28 15:43
Hello @mkur-ops,

you can set the configuration option `public_key_retrieval_disabled ` to `true` in your configuration.

Docs: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#public_key_retrieval_disabled

```
[plugins]
public_key_retrieval_disabled=true
```

**Comment by tolzhabayev** [comment] 2024-02-28 16:37
Closing as there is a config option you can use, feel free to reopen in case it does not work for your case.

**Closed by tolzhabayev** 2024-02-28 16:37 UTC
Labels: area/plugins

**Comment by kumar-pratiyush** [comment] 2024-04-24 10:05
I am facing the same issue. My linux server does not have internet and only has intranet. i have set the following configuration :
check_for_updates = false
check_for_plugin_updates = false
public_key_retrieval_disabled=true
I no longer see the error in the logs but still when I access the port of grafana server it is still not loading. I have also changed the default port from 3000 to 8090.

**Comment by sjager501** [comment] 2024-05-22 17:25
@tolzhabayev I've tried the same steps as above and couldn't manage to resolve the issue. I see this error in the grafana logs:
```
level=error msg="Error downloading plugin manifest keys" error="Get \"https://grafana.com/api/plugins/ci/keys\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

and I get the following when I go to the Grafana UI on port 3000:
![image](https://github.com/grafana/grafana/assets/105253630/6ec4e2f0-c0cb-4a6d-9561-4e0827adfa05)

**Comment by toralf** [comment] 2024-08-06 11:55
I do have this config:
```
mr-fox ~ # grep -B 200 tfoerste /etc/grafana/grafana.ini 
[alerting]
enabled = false
 
[analytics]
enabled = false
check_for_plugin_updates = false
check_for_updates = false
reporting_enabled = false
feedback_links_enabled = false
 
[date_formats]
default_timezone = UTC
 
[grafana_com]
url = https://127.0.0.1
 
[grafana_net]
url = https://127.0.0.1
 
[news]
news_feed_enabled = false
 
[security]
cookie_secure = true
disable_gravatar = true
strict_transport_security = true
 
[server]
protocol = https
http_addr = mr-fox
http_port = 15943
cert_file = /etc/grafana/grafana.crt
cert_key = /etc/grafana/grafana.key
 
#[feature_toggles]
#newVizTooltips = true

[plugins]
public_key_retrieval_disabled=true

```
and get this error:
```
logger=ngalert.state.manager t=2024-08-06T11:53:36.043142148Z level=info msg="Warming state cache for startup"
logger=grafanaStorageLogger t=2024-08-06T11:53:36.0438009Z level=info msg="Storage starting"
logger=ngalert.multiorg.alertmanager t=2024-08-06T11:53:36.043899997Z level=info msg="Starting MultiOrg Alertmanager"
logger=server t=2024-08-06T11:53:36.044327142Z level=error msg="Stopped background service" service=*apiserver.service reason="invalid IP address: mr-fox"
logger=tracing t=2024-08-06T11:53:36.044370464Z level=info msg="Closing tracing"
logger=infra.usagestats t=2024-08-06T11:53:36.045213344Z level=error msg="Failed to get last sent time" error="context canceled"
logger=auth t=2024-08-06T11:53:36.045297272Z level=error msg="Failed to lock and execute cleanup of expired auth token" error="context canceled"
logger=http.server t=2024-08-06T11:53:36.046921185Z level=info msg="HTTP Server TLS settings" scheme=https MinTLSVersion=TLS1.2 configuredciphers=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA
logger=ngalert.state.manager t=2024-08-06T11:53:36.047144826Z level=error msg="Unable to fetch orgIds" error="context canceled"
logger=ngalert.state.manager t=2024-08-06T11:53:36.047171377Z level=info msg="State cache has been initialized" states=0 duration=4.029189ms
logger=ngalert.scheduler t=2024-08-06T11:53:36.047214157Z level=info msg="Starting scheduler" tickInterval=10s maxAttempts=1
logger=ticker t=2024-08-06T11:53:36.047280292Z level=info msg=starting first_tick=2024-08-06T11:53:40Z
logger=http.server t=2024-08-06T11:53:36.048554846Z level=info msg="HTTP Server Listen" address=65.21.94.49:15943 protocol=https subUrl= socket=
logger=serviceaccounts t=2024-08-06T11:53:36.091308484Z level=warn msg="Failed to get usage metrics" error="context canceled"
logger=publicdashboards.metric t=2024-08-06T11:53:36.096307944Z level=error msg="error collecting background metrics" err="context canceled"
logger=provisioning.dashboard t=2024-08-06T11:53:36.096440244Z level=warn msg="Failed to delete orphaned provisioned dashboards" err="context canceled"

```

**Comment by Aminmalek** [comment] 2024-10-30 15:12
I'm facing the same issue here by default grafana setting on docker i didn't have this problem on my test server but in production i face this issue and I can't even debug this

**Comment by toralf** [comment] 2024-10-30 17:34
IMO I solved it by setting 
```
http_addr
```
to an ip address instead of the FQDN.

**Comment by baurmatt** [comment] 2025-03-21 12:37
Debugged in [#102432](https://github.com/grafana/grafana/issues/102432). The problem was the section name. It's called `[plugin]` rather than `[plugins]`.

With the correct section name, I can't reproduce this anymore.
