### ISSUE TITLE
Grafana 6.1.3 can't find field named @timestamp with Elasticsearch 7.0.0

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#16617] opened 2019-04-16 10:13 UTC
**What happened**:
I setup a very basic stack GEF :
- Grafana 6.1.3
- Elasticsearch 7.0.0
- Fluent-Bit 1.0.6

**What you expected to happen**:
I wanted to add a new data sources on Grafana which is present on my Elasticsearch node.
But it keep saying the field @timestamp for the time series search is not present in my indices

**How to reproduce it (as minimally and precisely as possible)**:

1. Install the 3 services mentionned above
2. Setup a basic syslog collector on my fluent-bit then send it to my elasticsearch
3. Setup a day based rotation of my indice with fluent-bit. Elasticsearch add the @timestamp field himself in the incomming messages
4. Went to Grafana to setup a new datasources to retreive the informations that are present in my Elastisearch node
5. Impossible to setup the datasources because Grafana keep saying the field @timestamp doesn't exist.

There is the webpage with the response in the console :
![image](https://user-images.githubusercontent.com/33425208/56201139-8c540200-6040-11e9-9e6b-0343567cf643.png)

As you can see here, the field @timestamp is retreived by Grafana when i pressed the "Test and Save" button, but it seems like he doesn't recognise the field in the response.
And the field @timestamp is used when entries are saved in grafana. If i use Kibana to explore my indice, i can clearly see that all my messages have the @timestamp field. 
The @timestamp field is also inside the mapping of my indice so i don't really see where is the error.

Maybe it's a compatibility issue with Elasticsearch 7.0.0 and Grafana 6.1.3 ? I seen some peoples having the same issue, maybe this post will dig into it and solve this issue ...

**Comment by torkelo** [comment] 2019-04-16 12:57
dupe of https://github.com/grafana/grafana/issues/15622

**Closed by torkelo** 2019-04-16 12:57 UTC
