### ISSUE TITLE
Fails to save case-sensitive and case-insensitive tags in annotations when using MySQL as database

### ISSUE THREAD

**Issue by bogdanov1609** [grafana/grafana#23481] opened 2020-04-09 16:57 UTC
**What happened**:
An annotation is not created if the values in tags differ only in case: 
```
curl -H "Accept: application/json" -H "Content-Type: application/json" -v -H 'Authorization: Bearer XXXXXX' -X POST -d @annotation.json 'https://grafana.vertis.yandex-team.ru/api/annotations'
{"message":"Failed to save annotation"}%
cat annotation.json
{
    "time": 1586419200000,
    "timeEnd": 1586426400000,
    "text": "test",
    "tags": [
        "test",
        "Test"
    ]
}
```
Error in logs: 
```
t=2020-04-09T19:26:34+0300 lvl=eror msg="Failed to save annotation" logger=context userId=0 orgId=1 uname= error="Error 1062: Duplicate entry '793172-2735' for key 'UQE_annotation_tag_annotation_id_tag_id'"
```

**What you expected to happen**:
The annotation was expected to be added with tags as is

**How to reproduce it (as minimally and precisely as possible)**:
Well its, just simple curl.  

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.6.2
- Data source type & version: 
- OS Grafana is installed on: docker container
- User OS & Browser: macos/iterm/curl
- Grafana plugins:
- Others:

**Comment by jongyllen** [comment] 2020-04-13 08:52
Hi, When I try using the same json payload and curl I get
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3000 (#0)
* Server auth using Basic with user 'admin'
> POST /api/annotations HTTP/1.1
> Host: localhost:3000
> Authorization: Basic YWRtaW46Z3JhZmFuYQ==
> User-Agent: curl/7.64.1
> Accept: application/json
> Content-Type: application/json
> Content-Length: 123
>
* upload completely sent off: 123 out of 123 bytes
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Expires: -1
< Pragma: no-cache
< X-Frame-Options: deny
< Date: Mon, 13 Apr 2020 08:50:03 GMT
< Content-Length: 38
<
* Connection #0 to host localhost left intact
{"id":19,"message":"Annotation added"}* Closing connection 0
``` 

Do you get the same result if you upgrade to latest Grafana version?
Or maybe it is something in your database, does it work with a clean installation?

**Comment by bogdanov1609** [comment] 2020-04-20 14:42
> Do you get the same result if you upgrade to latest Grafana version?

Got the same result on 6.6.2. 

> Or maybe it is something in your database, does it work with a clean installation?

The error is repeated only if mysql is used as the annotation storage. Including a clean installation.

**Comment by jongyllen** [comment] 2020-04-20 15:32
> > Do you get the same result if you upgrade to latest Grafana version?
> 
> Got the same result on 6.6.2.
> 
6.7.2 is the latest version

**Comment by bogdanov1609** [comment] 2020-04-21 08:22
Yep, same on 6.7.2
grafana_1  | t=2020-04-21T08:20:19+0000 lvl=info msg="Starting Grafana" logger=server version=6.7.2 commit=423a25fc32 branch=HEAD compiled=2020-04-02T08:02:56+0000
...
grafana_1  | t=2020-04-21T08:20:19+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
grafana_1  | t=2020-04-21T08:20:19+0000 lvl=info msg="Backend rendering via phantomJS" logger=rendering renderer=phantomJS
grafana_1  | t=2020-04-21T08:20:19+0000 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. Read more at https://grafana.com/docs/grafana/latest/administration/image_rendering/" logger=rendering renderer=phantomJS
grafana_1  | t=2020-04-21T08:20:24+0000 lvl=eror msg="Failed to save annotation" logger=context userId=0 orgId=1 uname= error="Error 1062: Duplicate entry '1-1' for key 'UQE_annotation_tag_annotation_id_tag_id'" remote_addr=93.100.213.26
grafana_1  | t=2020-04-21T08:20:24+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/annotations status=500 remote_addr=93.100.213.26 time_ms=53 size=39 referer=

**Comment by jongyllen** [comment] 2020-04-21 09:24
Thanks for checking, it is in the backlog to look at now

**Comment by bogdanov1609** [comment] 2020-06-14 18:46
ping?

**Comment by marefr** [comment] 2021-03-25 14:46
Think this is same problem as described in this issue https://github.com/grafana/grafana/issues/12549#issuecomment-425973742, i.e. unique indices and mysql,

**Comment by jessabe** [comment] 2021-08-16 13:02
Closing this as duplicate of #12549 -- slightly different but the fix should effect both.

**Closed by jessabe** 2021-08-16 13:02 UTC
Labels: type/bug, area/annotations, area/backend/db/mysql
