### ISSUE TITLE
Decimals option is broken

### ISSUE THREAD

**Issue by rooty0** [grafana/grafana#57378] opened 2022-10-20 21:08 UTC
**What happened**:
`Decimals` option does not accept `0` 

**What you expected to happen**:
It should accept `0`

**How to reproduce it (as minimally and precisely as possible)**:
1. Open https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=2
2. Change `Decimals` under `Standart Options` to `whatever > 0`. 
3. Save your panel
4a. Edit the panel and try to change `Decimals` to `0`. **This is broken - you will not be able to do that**.
4b. Try to remove any number from `Decimals` to make it `auto`.  **This is broken - you will not be able to do that**

**Anything else we need to know?**:
The same behavior happens for `Soft min` and `Soft max` under `Axis`.

The current workaround for me - I just modify JSON object of a panel to fix those values.

**Environment**:
- Grafana version: 9.2.1 (the bug was introduced in version 8, please note 7.5.17 is not effected)
- Data source type & version: graphite
- OS Grafana is installed on: docker (image: grafana/grafana:9.2.1), it's reproducible on https://play.grafana.org/
- User OS & Browser: MacOS - Chrome, Safari
- Grafana plugins: None
- Others: N/A

**Comment by leeoniya** [comment] 2022-10-21 02:04
duplicate of https://github.com/grafana/grafana/issues/56923. it's already fixed on `main` and will ship in v9.2.2

**Closed by leeoniya** 2022-10-21 02:04 UTC
