### ISSUE TITLE
Docs feedback: /datasources/prometheus.md error on "access" values 

### ISSUE THREAD

**Issue by yogeek** [grafana/grafana#29597] opened 2020-12-03 23:42 UTC
In the documentation for prometheus datasource, it is indicated that the possible values for `Access` field are `server` (default) or `browser`.

But in the example at the bottom of the page, `access: proxy` is used.
Plus the code indicates that the only accepted values are `direct` or `proxy` (https://github.com/grafana/grafana/pull/26440)

And some tests in my grafana config seemed to show that `proxy` is working but not `server`

Is it possible to update the documentation to reflect the real values please ?

**Comment by ivanahuckova** [comment] 2020-12-06 14:59
Hello @yogeek, in more details, it is explained [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file) 
![image](https://user-images.githubusercontent.com/30407135/101283629-f56f2700-37db-11eb-99f1-0bb3f037a8cb.png)
, but I can see how this can be confusing. Definitely something we could improve!

**Comment by yogeek** [comment] 2020-12-06 15:15
@ivanahuckova thank you for your help.
Ok I see : the values are different in the config file and in the UI... Very confusing indeed 😅

**Comment by ivanahuckova** [comment] 2020-12-06 16:00
I have assigned this issue to me and I'll try to update docs to make it more clear.

**Comment by oddlittlebird** [comment] 2020-12-22 15:31
Let @grafana/docs-squad know if you want help, @ivanahuckova

**Comment by ivanahuckova** [comment] 2021-01-07 09:59
@oddlittlebird I haven't had a chance to look at this (I have it on my to-do list). So if you would like to have a look at it/take it over, that would be awesome! The problem is that our UI and provisioning are using different naming. We are mentioning it in [provisioning docs](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file), but maybe we could add note/info to [prometheus data source settings (Access)](https://grafana.com/docs/grafana/latest/datasources/prometheus/#prometheus-settings) docs as well.

**Closed** 2021-01-08 18:19 UTC
Labels: datasource/Prometheus, priority/important-longterm, type/docs
