### ISSUE TITLE
Explore Tracing: Support trace graph view

### ISSUE THREAD

**Issue by tensorchen** [grafana/grafana#29140] opened 2020-11-16 18:41 UTC
**What would you like to be added**:

Support trace graph view.
Now only support trace timeline view.

**Comment by ivanahuckova** [comment] 2020-11-20 14:54
/duplicate of https://github.com/grafana/grafana/issues/25568

**Comment by davkal** [comment] 2020-12-02 09:57
Which tracing datasource do you use?

**Comment by tensorchen** [comment] 2020-12-05 15:12
@davkal jaeger

**Closed** 2021-03-31 15:56 UTC
Labels: area/tracing, priority/important-longterm, priority/support-subscription, type/feature-request
