### ISSUE TITLE
column from influx missing in table view

### ISSUE THREAD

**Issue by akarl10** [grafana/grafana#64111] opened 2023-03-03 09:21 UTC
**What happened**:
when querying the influxdb for multiple columns a column "msgType" is dropped from the table view results.
Timeseries view has the column, so influx seems to return the column

**What you expected to happen**:
showing the column

**How to reproduce it (as minimally and precisely as possible)**:
show the results as "Table" in the influx query tool and query multiple columns
example:
```influxql
SELECT  "message", "area", "msgType", "state" FROM "logs" WHERE $timeFilter
```
**Anything else we need to know?**:
Until now I was able to reproduce this only with that exact column. The type is string in my case. When switching to timeseries view the column shows up, but in that case I need the table view

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: InfluxDB InfluxQL Server 2.2
- OS Grafana is installed on: ubuntu
- User OS & Browser: firefox ubuntu
- Grafana plugins:
- Others:

**Comment by vincent-olivert-riera** [comment] 2023-03-03 12:09
Duplicate of this one? https://github.com/grafana/grafana/pull/64058

Could you check, please?

**Comment by akarl10** [comment] 2023-03-03 12:15
@vincent-olivert-riera probably. did not discover this issue previosly but seems at least related. I tried to modify the ordering of the columns in the query but the result was always the same (that is always the same column was missing)
What is different to the mentioned issue is that I get every column but msgType, in #64058 no column is returned

**Comment by mellieA** [comment] 2023-03-03 19:33
@akarl10 a workaround for the issue is to create the query with the builder and then switch to the code (raw query). If that also resolves the issue for you, then it is likely the same issue that happens because of how the query model was created when using the code builder only. 

Let us know if you see this resolved by the fix or not

**Comment by akarl10** [comment] 2023-03-04 10:09
@mellieA can confirm that creating the query with the builder (or alternatively manually editing the select property in the panel json so that it contains every column in the same order as the raw query) fixes/workarounds the issue. will check with a upcoming nightly if https://github.com/grafana/grafana/pull/64058 fixes the issue and report back (probably monday)

**Comment by akarl10** [comment] 2023-03-06 07:55
if [grafana_9.5.0~104402pre_amd64.deb](https://dl.grafana.com/oss/main/grafana_9.5.0~104402pre_amd64.deb) should already contain the fix, this does NOT fix the issue

**Closed** 2023-07-14 21:25 UTC
Labels: needs more info
