### ISSUE TITLE
Table ignore \n

### ISSUE THREAD

**Issue by Tepew** [grafana/grafana#26476] opened 2020-07-21 06:33 UTC
In version 6.X type Table use data as is.

![image](https://user-images.githubusercontent.com/42611903/88020723-e5a8bc00-cb34-11ea-84e8-956257ca8786.png)

In version 7.0.3 type Table ignore '\n' and information looked inreadble

![image](https://user-images.githubusercontent.com/42611903/88020936-459f6280-cb35-11ea-95dc-f01fe229879c.png)

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Zabbix 3.12.2
- OS Grafana is installed on: OEL 7
- User OS & Browser: Win 10 Chrome 84.0.4147.89
- Grafana plugins: Zabbix 3.12.2

**Comment by torkelo** [comment] 2020-07-21 07:26
duplicate of https://github.com/grafana/grafana/issues/25623

**Closed by torkelo** 2020-07-21 07:26 UTC
