### ISSUE TITLE
Duplicate time column when joining two table queries

### ISSUE THREAD

**Issue by JacksonPhoong** [grafana/grafana#25797] opened 2020-06-24 08:58 UTC
**What happened**:
I have two Prometheus queries in table format joined by a common label. However, there are now two "Time" columns.
![GrafanaIssue1](https://user-images.githubusercontent.com/51329578/85522752-a4f27b80-b638-11ea-8ffa-61f8b216fc4e.png)
And if I add the "Organize fields" transformation, can see that there is only one "Time" row.
![GrafanaIssue2](https://user-images.githubusercontent.com/51329578/85523099-1d593c80-b639-11ea-97f6-b679e42ea57e.png)
If I click on the "eye" icon to hide the "Time" column, both columns will be hidden.
![GrafanaIssue3](https://user-images.githubusercontent.com/51329578/85523204-3f52bf00-b639-11ea-938e-139e0f81808f.png)

**What you expected to happen**:
I want to have only one of the "Time" column hidden.

**How to reproduce it (as minimally and precisely as possible)**:
Having two Prometheus queries in table format joined by a common label.

**Anything else we need to know?**:
If I try to add another "Outer join" transformation on "Time", all the rows now collapse into one. I'm guessing this is because all the time values are identical. However, there are still two "Time" columns.
![GrafanaIssue4](https://user-images.githubusercontent.com/51329578/85523940-2d255080-b63a-11ea-8607-45ad2c0cf48b.png)

Also, it would be nice if it were possible to drag the transformations around to reorder them just like reordering the fields in "Organize fields" transformation.

**Environment**:
- Grafana version: 7.0.3 (00ee734baf)
- Data source type & version: Prometheus 2.18.1
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome

**Comment by marefr** [comment] 2020-06-24 21:35
Duplicate of #25579

**Comment by marefr** [comment] 2020-06-24 21:36
Closing this as a duplicate. It also feels related to #25594

**Closed by marefr** 2020-06-24 21:36 UTC
