### ISSUE TITLE
Graph tooltip shows data that is not on the moment 

### ISSUE THREAD

**Issue by MaikiGirardi** [grafana/grafana#31114] opened 2021-02-11 00:56 UTC
**What happened**:
I have a graph for CPU usage in a elastic machine pool thats adds and removes machines dynamically. So when i look the graph i want to see the CPU usage on a specific moment, so i move my mouse cursor on the graph and it shows on the tooltip all machines with the last status, instead of showing only the machines that is on that specific moment. This is very annoying and make the usage experience poor. 

**What you expected to happen**:
When we move the mouse cursor on the graph, the tooltip only shows what is show on that specific moment not the resources that are not on that moment. 

The image below shows the problem.

![image](https://user-images.githubusercontent.com/20565056/107591136-c1075500-6be8-11eb-8f2f-085662103f0e.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a graph that has more than one resource.
2. Make one of then stop showing data
3. Put the mouse on the graph on the moment that doesn't have all resources and you will see the problem (the image above has the right example).

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: 7.4.0-1
- Data source type & version: Prometheus 
- OS Grafana is installed on: Red Hat Enterprise Linux release 8.2 
- User OS & Browser: Microsoft Edge Version 88.0.705.63
- Grafana plugins: none
- Others: none

**Comment by torkelo** [comment] 2021-02-11 05:35
duplicate of https://github.com/grafana/grafana/issues/6946 

Two workarounds, use make sure you do not have display option "null value" set to connnected (it removes null values), or try the new time series panel, it has better logic here

**Closed by torkelo** 2021-02-11 05:35 UTC
