### ISSUE TITLE
Currently, the default width/height is hard-coded to 1000x500 here: https://github.com/grafana/grafana/blob/f1c3177e79f21e1292afa02efa393f5e52dc231a/public/app/features/dashboard/components/ShareModal/utils.ts#L106

### ISSUE THREAD

**Issue by ericsirius** [grafana/grafana#79806] opened 2023-12-21 16:50 UTC
Currently, the default width/height is hard-coded to 1000x500 here: https://github.com/grafana/grafana/blob/f1c3177e79f21e1292afa02efa393f5e52dc231a/public/app/features/dashboard/components/ShareModal/utils.ts#L106

The reason i set up the image renderer in the first place was to produce higher quality images than screenshotting would give me. Having to edit the URL by hand for this is really not great.

I propose being able to set a default server-wide for these parameters, and down the line in the future making them easily configurable in the ShareModal. Especially, being able to set the `scale` parameter is essential to take full advantage of the image renderer.

_Originally posted by @laundmo in https://github.com/grafana/grafana/discussions/47211_

**Comment by ericsirius** [comment] 2023-12-21 16:53
I already change this file but the configuration in dashboard on grafana is yet 1000 a 500, my grafana is running in container, I had map the volume, but it does not change anything in 


[Direct link rendered image]

someone can help me?

**Comment by laundmo** [comment] 2023-12-21 17:25
why did you post this again?

**Comment by ericsirius** [comment] 2023-12-21 18:05
> why did you post this again?

Sorry Laundmo, but i need help, can you help in this case?

**Comment by ericsirius** [comment] 2023-12-21 18:06
> why did you post this again?

I did the change that you explain, but in the render bottom in grafana dashboard the url is yet 1000 and 500 width and height

**Comment by laundmo** [comment] 2023-12-21 18:33
i didnt explain a change, i showed where this is hardcoded. i have no idea how to change it. i ended up making a bookmarklet to generate the URL (which i domt have access to right now)

**Comment by tonypowa** [comment] 2024-01-23 11:38
this feature request is a duplicate of https://github.com/grafana/grafana/issues/75963
please ask any questions and keep the discussion in there  🙏 
thank you

**Closed by tonypowa** 2024-01-23 11:38 UTC
