### ISSUE TITLE
Direct link rendered image empty when variable set to auto

### ISSUE THREAD

**Issue by beardhatcode** [grafana/grafana#18529] opened 2019-08-13 08:36 UTC
**What happened**:

Clicking on ":camera: Direct link rendered image" on graph with interval hat is based on variable set to `auto` results in an empty graph.

The title of the image does not contain a filled in template variable. It should be `Submissions aggregated per $smartAggregate` where `$smartAggregate` should have been replaced with `20m` (or any interval).

![bad](https://user-images.githubusercontent.com/662538/62926153-30ae4100-bdb4-11e9-9e1e-f178f62b9939.png)
 
URL of image:
```
https://{host}/render/d-solo/000000002/dodona?tab=visualization&orgId=1&refresh=10s&from=1565640705876&to=1565683905876&panelId=10&var-smartAggregate=$__auto_interval_smartAggregate&width=1000&height=500&tz=Europe%2FBrussels
```

Log:
```
t=2019-08-13T10:16:47+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname= method=POST path=/api/datasources/proxy/1/render status=500 remote_addr=[::1] time_ms=144 size=611 referer="http://localhost:3000/d-solo/000000002/dodona?tab=visualization&orgId=1&refresh=10s&from=1565640705876&to=1565683905876&panelId=10&var-smartAgregate="
```

**What you expected to happen**:

The image should have been requested with `&var-smartAggregate=$__auto_interval_smartAggregate` removed (or filled in)

Which results in the correct image:
![good](https://user-images.githubusercontent.com/662538/62926429-cc3fb180-bdb4-11e9-94cf-ba2554c68798.png)

at URL:

```
https://{host}/render/d-solo/000000002/dodona?tab=visualization&orgId=1&refresh=10s&from=1565640705876&to=1565683905876&panelId=10&width=1000&height=500&tz=Europe%2FBrussels

```

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to / create a panel that includes a `smartSummarize(..., '$yourVariable', 'sum')` where `yourVariable` is an interval that can be set to auto
2. Set `yourVariable` to `auto`
2. Click the arrow in the panel top, choose Share, click :camera: Direct link rendered image
3. See empty graph 

Setting `yourVariable` to `10m` (or any other value) will give a correct image. 
 

**Anything else we need to know?**:

**Environment**:
- Grafana version:  Grafana v6.3.2 (commit: 4832460) 
- Data source type & version: Graphite 
- OS Grafana is installed on: Ubuntu 18.04.3 LTS
- User OS & Browser: 70.0a1 (2019-07-28) (64-bit), Ar
- Grafana plugins:
  - neocat-cal-heatmap-panel @ 0.0.3 
  - vonage-status-panel @ 1.0.7 
- Others: *none*

**Comment by hugohaggmark** [comment] 2019-08-13 11:14
Thanks @beardhatcode for reporting this! We'll take a look at this.

**Comment by Ziars** [comment] 2019-09-22 13:57
Greetings, I'm experiencing the same issue using:

- Ubuntu 16.04
- Grafana v6.3.5
- Prometheus as a data source

Steps I followed to reproduce the problem:

1. Create an empty dashboard
2. Add a variable with Type=Interval, some values and "Auto Option" on
3. Add a graph-panel with any metric to visualize
4. Choose "auto" in the created variable's selector
5. Try to get the rendered image of the panel (Share => Direct link rendered image)

As a result I'm getting 504 timeout from nginx. The request that is being sent:

```
https://mydomain.tld/render/d-solo/vtYxcd34f/rendering-test?orgId=1&refresh=30s&from=1569151937689&to=1569155537689&var-interval=$__auto_interval_interval&panelId=17&width=1000&height=500&tz=Europe%2FMoscow
```

In debug logs of grafana-server the following messages could be seen during request processing:

```
Sep 22 12:32:18 testing grafana-server[2817]: t=2019-09-22T12:32:18+0000 lvl=info msg=Rendering logger=rendering path="d-solo/vtYxcd34f/rendering-test?orgId=1&refresh=30s&from=1569151937689&to=1569155537689&var-interval=$__auto_interval_interval&panelId=17&width=1000&height=500&tz=Europe%2FMoscow"
Sep 22 12:32:18 testing grafana-server[2817]: t=2019-09-22T12:32:18+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/vtYxcd34f/rendering-test?orgId=1&refresh=30s&from=1569151937689&to=1569155537689&var-interval=$__auto_interval_interval&panelId=17&width=1000&height=500&tz=Europe%2FMoscow&render=1 width=1000 height=500 png=/mnt/grafana/data/png/OOcC4JgC7YhAH46hEleK.png domain=localhost timeout=60 renderKey=GrfA32J0pkgcvKbek2521kokr50kn8A9]" timezone=Europe/Moscow
Sep 22 12:33:18 testing grafana-server[2817]: t=2019-09-22T12:33:18+0000 lvl=info msg=Rendering logger=rendering path="d-solo/vtYxcd34f/rendering-test?orgId=1&refresh=30s&from=1569151937689&to=1569155537689&var-interval=$__auto_interval_interval&panelId=17&width=1000&height=500&tz=Europe%2FMoscow"
Sep 22 12:33:18 testing grafana-server[2817]: t=2019-09-22T12:33:18+0000 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/vtYxcd34f/rendering-test?orgId=1&refresh=30s&from=1569151937689&to=1569155537689&var-interval=$__auto_interval_interval&panelId=17&width=1000&height=500&tz=Europe%2FMoscow&render=1 width=1000 height=500 png=/mnt/grafana/data/png/8h0oeLgHFliIh7KutFPR.png domain=localhost timeout=60 renderKey=1nkWfTzIdCyufBuJOZi5Cwb8M5YZZzKq]" timezone=Europe/Moscow
Sep 22 12:33:18 testing grafana-server[2817]: t=2019-09-22T12:33:18+0000 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: http://localhost:3000/d-solo/vtYxcd34f/rendering-test?orgId=1&refresh=30s&from=1569151937689&to=1569155537689&var-interval= status: success 60000\n"
Sep 22 12:33:18 testing grafana-server[2817]: t=2019-09-22T12:33:18+0000 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
Sep 22 12:33:18 testing grafana-server[2817]: t=2019-09-22T12:33:18+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"
Sep 22 12:33:18 testing grafana-server[2817]: t=2019-09-22T12:33:18+0000 lvl=eror msg="Rendering failed." logger=context userId=2 orgId=1 uname=user error="signal: killed"
Sep 22 12:33:18 testing grafana-server[2817]: t=2019-09-22T12:33:18+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=user method=GET path=/render/d-solo/vtYxcd34f/rendering-test status=500 remote_addr=10.116.155.1 time_ms=60017 size=1722 referer="https://mydomain.tld/d/vtYxcd34f/rendering-test?orgId=1&refresh=30s"
```

If the variable is set on any other value than "auto" - no problems with rendering occur. Please, tell if there are any ways to get around the problem.

**Comment by evictorero** [comment] 2024-05-27 21:28
I'm closing this since I couldn't reproduce it in the last version of Grafana. Please reopen it if it is still an issue.

**Closed by evictorero** 2024-05-27 21:28 UTC
Labels: type/bug, area/dashboard/templating, area/image-rendering, version/6, team/grafana-sharing
