### ISSUE TITLE
Grafana 7.0 - Export CSV 

### ISSUE THREAD

**Issue by matteoseppi** [grafana/grafana#24989] opened 2020-05-21 14:54 UTC
We have just updated Grafana from Grafana 6.7 to Grafana 7.0.
We tried to Export a CSV data file from ‘Graph panel’. But it doesn’t work properly because Time column is in Timestamp format and not in Data format (YYYY-MM-DD HH:mm:ss), in CSV file. We need to have Data format in CSV file.
How can we fix it?

**Comment by ryantxu** [comment] 2020-05-21 17:05
Duplicate of #24973

**Closed by ryantxu** 2020-05-21 17:05 UTC
