### ISSUE TITLE
After migrating to 8.1.1 often "relative time range" doesn't responding on click

### ISSUE THREAD

**Issue by mvalletta** [grafana/grafana#38709] opened 2021-08-30 13:10 UTC
**What happened**:
After migrating to 8.1.1 often "relative time range" doesn't responding on click. As you can see in the attached .mov, selection of "Last 2days" needs two clicks and selection of "Last 7 days" needs  4 clicks to be selected

**What you expected to happen**:
Relative time range selected on the first click

**How to reproduce it (as minimally and precisely as possible)**:
Try to change relative time ranges

**Anything else we need to know?**:

**Environment**:
Grafana version: 8.1.1
Data source type & version: PostgreSQL 12
OS Grafana is installed on: Ubuntu 20.04.1
User OS & Browser: MAC OS X + Chrome 92.0
Grafana plugins:
Others:

https://user-images.githubusercontent.com/5305902/131325492-193e6855-bfb3-46c2-8782-0a333f17031e.mov

**Comment by torkelo** [comment] 2021-08-31 11:56
duplicate of https://github.com/grafana/grafana/issues/37727 , fixed in 8.1.2

**Comment by torkelo** [comment] 2021-08-31 11:56
duplicate of https://github.com/grafana/grafana/issues/37727 , fixed in 8.1.2

**Closed by torkelo** 2021-08-31 11:56 UTC
Labels: type/bug, needs investigation, area/frontend, timepicker
