### ISSUE TITLE
Explore: multiline log messages don't display nicely

### ISSUE THREAD

**Issue by rayddteam** [grafana/grafana#17584] opened 2019-06-14 06:36 UTC
**What would you like to be added**:
Explore: put log line inside "pre" or replace newline with "br"
**Why is this needed**:
Needed to show multiline log messages.
Loki accept such messages just fine. IMO :)

**Comment by hugohaggmark** [comment] 2019-06-14 08:18
Thanks for taking time to add this request @rayddteam 

What do you think @davkal

**Comment by steven-sheehy** [comment] 2019-06-15 03:18
Loki doesn't support [multi-line log lines](https://github.com/grafana/loki/issues/74). So not sure doing this adds any value until it does.

**Comment by rayddteam** [comment] 2019-06-15 11:38
> Loki doesn't support [multi-line log lines](https://github.com/grafana/loki/issues/74) as far as I know. For sure the CRI log entry parser doesn't (I wrote it). Multi-line logs will show up as separate lines in Grafana for it.The docker entry parser might, I'm not sure.

Loki works fine with multiline, but promtail don't.
I did test with perl utility wrote on info from python Loki tool.

**Comment by marefr** [comment] 2019-06-24 19:44
Suggested to implement change when creating logs model here: https://github.com/grafana/grafana/blob/2fb45eeec898e0c8fa4ab088a6dc843420af8e2d/public/app/core/logs_model.ts#L357-L399

**Comment by khauser** [comment] 2019-09-17 06:09
Also while having multiline logs we use the logstash json formatted log entries resulting in e.g.:
```
{"@timestamp":"2019-08-13T23:57:20.971+00:00","@version":"1","message":"Error in job timer thread occurred!","logger_name":"somecode.core.internal.job.Timer","thread_name":"JobTimer759282143","level":"ERROR","level_value":40000,"stack_trace":"somecode.core.capi.common.SystemException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat somecode.core.internal.jdbc.JDBCDataSourceMgrImpl.getConnection(JDBCDataSourceMgrImpl.java:783)\n\tat somecode.core.internal.jdbc.JDBCDataSourceMgrImpl.getConnection(JDBCDataSourceMgrImpl.java:796)\n\tat somecode.core.internal.jdbc.JDBCUtilsImpl.getConnection(JDBCUtilsImpl.java:925)\n\tat somecode.core.capi.jdbc.JDBCUtils.getConnection(JDBCUtils.java:560)\n\tat somecode.core.internal.jdbc.DBDate.currentDBDate(DBDate.java:75)\n\tat somecode.core.internal.job.Timer.run(Timer.java:102)\nCaused by: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.ucp.util.UCPErrorHandler.newSQLException(UCPErrorHandler.java:479)\n\tat oracle.ucp.util.UCPErrorHandler.throwSQLException(UCPErrorHandler.java:154)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1127)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1031)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1006)\n\tat somecode.core.internal.jdbc.JDBCDataSource.getConnection(JDBCDataSource.java:101)\n\tat somecode.core.internal.jdbc.JDBCDataSource.getConnection(JDBCDataSource.java:73)\n\tat somecode.core.internal.jdbc.JDBCDataSourceMgrImpl.getConnection(JDBCDataSourceMgrImpl.java:779)\n\t... 5 common frames omitted\nCaused by: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:359)\n\tat oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:58)\n\tat oracle.ucp.jdbc.DataSourceConnectionFactoryAdapter.createConnection(DataSourceConnectionFactoryAdapter.java:102)\n\tat oracle.ucp.jdbc.oracle.OracleDataSourceConnectionFactoryAdapter.createConnection(OracleDataSourceConnectionFactoryAdapter.java:82)\n\tat oracle.ucp.common.Database.createPooledConnection(Database.java:268)\n\tat oracle.ucp.common.Cluster.create(Cluster.java:234)\n\tat oracle.ucp.common.Core.growBorrowed(Core.java:634)\n\tat oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionWithoutCountingRequests(UniversalConnectionPoolImpl.java:230)\n\tat oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:139)\n\tat oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:120)\n\tat oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:170)\n\tat oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.borrowConnection(OracleJDBCConnectionPool.java:849)\n\tat oracle.ucp.jdbc.oracle.OracleConnectionConnectionPool.borrowConnection(OracleConnectionConnectionPool.java:82)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1103)\n\t... 10 common frames omitted\nCaused by: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)\n\tat oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)\n\tat oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)\n\tat oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)\n\tat oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:317)\n\tat oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:241)\n\tat oracle.ucp.jdbc.DataSourceConnectionFactoryAdapter.createConnection(DataSourceConnectionFactoryAdapter.java:96)\n\t... 21 common frames omitted\nCaused by: oracle.net.ns.NetException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:275)\n\tat oracle.net.ns.NSProtocol.connect(NSProtocol.java:264)\n\tat oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)\n\tat oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)\n\t... 27 common frames omitted\n","executionsite":"root"}
```
So fields in this json could contain `\n\t`. In grafana we see them as they are. But as an engineer I would like to see a well formatted stacktrace.

**Comment by vgulinao** [comment] 2019-10-03 13:10
A simple solution could be https://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag/248013#248013.

.logs-row__message {
    white-space: pre-wrap;       /* Since CSS 2.1 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}

**Comment by rrfeng** [comment] 2019-11-13 04:30
I have made a pr #17425 , merged but not working ....

**Comment by ivanahuckova** [comment] 2020-02-18 08:14
This issue was resolved in https://github.com/grafana/grafana/pull/22057 and will be part of 6.7 release. 🙂

**Comment by rayddteam** [comment] 2020-02-18 08:23
> This issue was resolved in #22057 and will be part of 6.7 release. slightly_smiling_face

Great thanks!

**Comment by daviddelannoy** [comment] 2020-03-27 13:26
> Also while having multiline logs we use the logstash json formatted log entries resulting in e.g.:
> 
> ```
> {"@timestamp":"2019-08-13T23:57:20.971+00:00","@version":"1","message":"Error in job timer thread occurred!","logger_name":"somecode.core.internal.job.Timer","thread_name":"JobTimer759282143","level":"ERROR","level_value":40000,"stack_trace":"somecode.core.capi.common.SystemException: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat somecode.core.internal.jdbc.JDBCDataSourceMgrImpl.getConnection(JDBCDataSourceMgrImpl.java:783)\n\tat somecode.core.internal.jdbc.JDBCDataSourceMgrImpl.getConnection(JDBCDataSourceMgrImpl.java:796)\n\tat somecode.core.internal.jdbc.JDBCUtilsImpl.getConnection(JDBCUtilsImpl.java:925)\n\tat somecode.core.capi.jdbc.JDBCUtils.getConnection(JDBCUtils.java:560)\n\tat somecode.core.internal.jdbc.DBDate.currentDBDate(DBDate.java:75)\n\tat somecode.core.internal.job.Timer.run(Timer.java:102)\nCaused by: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.ucp.util.UCPErrorHandler.newSQLException(UCPErrorHandler.java:479)\n\tat oracle.ucp.util.UCPErrorHandler.throwSQLException(UCPErrorHandler.java:154)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1127)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1031)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1006)\n\tat somecode.core.internal.jdbc.JDBCDataSource.getConnection(JDBCDataSource.java:101)\n\tat somecode.core.internal.jdbc.JDBCDataSource.getConnection(JDBCDataSource.java:73)\n\tat somecode.core.internal.jdbc.JDBCDataSourceMgrImpl.getConnection(JDBCDataSourceMgrImpl.java:779)\n\t... 5 common frames omitted\nCaused by: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:359)\n\tat oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:58)\n\tat oracle.ucp.jdbc.DataSourceConnectionFactoryAdapter.createConnection(DataSourceConnectionFactoryAdapter.java:102)\n\tat oracle.ucp.jdbc.oracle.OracleDataSourceConnectionFactoryAdapter.createConnection(OracleDataSourceConnectionFactoryAdapter.java:82)\n\tat oracle.ucp.common.Database.createPooledConnection(Database.java:268)\n\tat oracle.ucp.common.Cluster.create(Cluster.java:234)\n\tat oracle.ucp.common.Core.growBorrowed(Core.java:634)\n\tat oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionWithoutCountingRequests(UniversalConnectionPoolImpl.java:230)\n\tat oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:139)\n\tat oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:120)\n\tat oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:170)\n\tat oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.borrowConnection(OracleJDBCConnectionPool.java:849)\n\tat oracle.ucp.jdbc.oracle.OracleConnectionConnectionPool.borrowConnection(OracleConnectionConnectionPool.java:82)\n\tat oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1103)\n\t... 10 common frames omitted\nCaused by: java.sql.SQLException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)\n\tat oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)\n\tat oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)\n\tat oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)\n\tat oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:317)\n\tat oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:241)\n\tat oracle.ucp.jdbc.DataSourceConnectionFactoryAdapter.createConnection(DataSourceConnectionFactoryAdapter.java:96)\n\t... 21 common frames omitted\nCaused by: oracle.net.ns.NetException: Listener refused the connection with the following error:\nORA-12505, TNS:listener does not currently know of SID given in connect descriptor\n \n\tat oracle.net.ns.NSProtocolStream.negotiateConnection(NSProtocolStream.java:275)\n\tat oracle.net.ns.NSProtocol.connect(NSProtocol.java:264)\n\tat oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1452)\n\tat oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:496)\n\t... 27 common frames omitted\n","executionsite":"root"}
> ```
> 
> So fields in this json could contain `\n\t`. In grafana we see them as they are. But as an engineer I would like to see a well formatted stacktrace.

Hi,

Same error here, still **KO** for us with JSON logs from `LogstashEncoder`, Grafana updated to 6.7.1. Exceptions put by `LogstashEncoder` in `stack_trace` json field are still displayed with \n\t in Loki Explore (both in normal log display and 'Parse fields' section) :

![20200327_03_capture](https://user-images.githubusercontent.com/16318239/77759478-0fdde780-7035-11ea-80e8-63ef5bca18fe.png)

Can we reopen this issue please ?

**Comment by daviddelannoy** [comment] 2020-05-04 07:51
Hi,

Any update on this ? Still KO for us ..

**Comment by hugohaggmark** [comment] 2020-05-04 08:21
ping @grafana/observability-squad

**Comment by davkal** [comment] 2020-05-04 13:52
this likely needs to be solved via a proper JSON formatter

**Comment by ivanahuckova** [comment] 2020-05-04 13:56
@davkal Isn't this same as https://github.com/grafana/grafana/issues/18522

**Comment by ivanahuckova** [comment] 2020-05-11 17:43
Closing the issue, as it is duplicate of #18522.

**Closed by ivanahuckova** 2020-05-11 17:43 UTC
Labels: area/explore, beginner friendly, help wanted, priority/nice-to-have, type/feature-request

**Comment by p12tic** [comment] 2022-03-07 19:57
@ivanahuckova I think this is not duplicate of #18522. Issue still happens as of v8.4.3.

`\n` within JSON values are not replaced with real newlines.

Same output as in https://user-images.githubusercontent.com/16318239/77759478-0fdde780-7035-11ea-80e8-63ef5bca18fe.png.

**Comment by AndresPineros** [comment] 2022-07-30 07:19
Is it possible to re-open this issue? Kibana does present multi-line logs in a decent format. Would be nice to have this in Grafana. Could even be applied optionally with a LogQL parser in case someone needs to see the single-line content.

**Comment by paul-lysak** [comment] 2023-02-07 10:48
I've got newlines displayed nicely in the dashboard "Logs" panel with such query:
```
{someLabel="$someVariable"} |= `$someOtherVariable` |  json | line_format `{{.message}}`
```
Essentially, ` json | line_format ...` extract JSON field and it's displayed as a plain-text now, with all the newlines included.

**Comment by aofodo** [comment] 2024-04-12 07:37
> I've got newlines displayed nicely in the dashboard "Logs" panel with such query:
> 
> ```
> {someLabel="$someVariable"} |= `$someOtherVariable` |  json | line_format `{{.message}}`
> ```
> 
> Essentially, ` json | line_format ...` extract JSON field and it's displayed as a plain-text now, with all the newlines included.

@paul-lysak solution is great. In my case, the main log information is stored in the `body`. Also to avoid duplicating the `body` in the extra one, I cleared it with `label_format body=""`

```
 {someLabel="$someVariable"} |= `$someOtherVariable` |  json  | line_format `[{{.level}}] {{.body}}` | label_format body=""
```
![image](https://github.com/grafana/grafana/assets/165767272/7b3738f2-41ea-48aa-a155-e216a1ecc62c)

**Comment by reynadan** [comment] 2025-03-10 09:19
Enabling "**Wrap lines**" displayed line breaks as wanted

![Image](https://github.com/user-attachments/assets/dd026c5d-dcab-44eb-bb5e-654f86876b53)
