### ISSUE TITLE
Enable explore mode to only authenticated users 

### ISSUE THREAD

**Issue by infa-kparida** [grafana/grafana#34167] opened 2021-05-16 19:47 UTC
**What would you like to be added**:
Enable explore mode to only authenticated users 

**Why is this needed**:
We need to enable explore mode to all our authenticated users and  it looks like the option to do that is to enable below in setting 
`[users]
viewers_can_edit = true`

However we also have anonymous users enabled for one of the ORGANIZATION.Hence this above settings is opening up the explore mode for anonymous users as well which we want to restrict.

**Comment by torkelo** [comment] 2021-05-17 07:31
duplicate of https://github.com/grafana/grafana/issues/29621

**Closed by torkelo** 2021-05-17 07:31 UTC
