### ISSUE TITLE
Show graph problem: undefined if not manually refreshed

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#36196] opened 2021-06-27 15:17 UTC
**What happened**:
Hi, I have a panel showing more series that I can select from a variable. If I add series everything works well, but when I deselect them, than no graph is shown and I need to manually refresh the page. What is strange is that within the edit panel everithing works great, and data are correctly read. I even tried all possible combination between table/series format and table view. But nothing change. 
![Graphana803](https://user-images.githubusercontent.com/51508670/123549971-894e1380-d76b-11eb-9d4b-2df4cd5a845a.gif)

It's much more easier to have a look at the video I attached, then explain it.

**What you expected to happen**:
No need to manually refresh the web page

**Environent**:
- Grafana version: 8.0.3
- Data source type & version: phpMyAdmin 5.1.0
- OS Grafana is installed on: windows 10
- User OS & Browser: windows 10 & Chrome
**Environent**:
- Grafana version: 8.0.3
- Data source type & version: phpMyAdmin 5.1.0
- OS Grafana is installed on: windows 10
- User OS & Browser: windows 10 & Chrome

**Comment by marefr** [comment] 2021-06-29 10:32
Can you please use chrome developer tools or similar and inspect the network tab/request of the query executed when you get the error in the UI? It would also be helpful if you could check the console tab developer tools and copy any errors listed there. Thanks

**Comment by DonatoD** [comment] 2021-06-30 21:37
From the console tab developer tools this is the error I get.
![Immagine 2021-06-30 231151](https://user-images.githubusercontent.com/51508670/124032325-ba8f4380-d9f8-11eb-8779-809a8d72a6d6.jpg)

```
react-dom.production.min.js:216 TypeError: Cannot read property 'type' of undefined
    at Fc (app.90f320b382a70cd0232d.js:4200)
    at na (vendors~app.90f320b382a70cd0232d.js:2)
    at Ba (vendors~app.90f320b382a70cd0232d.js:2)
    at Uu (vendors~app.90f320b382a70cd0232d.js:2)
    at Os (vendors~app.90f320b382a70cd0232d.js:2)
    at _s (vendors~app.90f320b382a70cd0232d.js:2)
    at ws (vendors~app.90f320b382a70cd0232d.js:2)
    at ds (vendors~app.90f320b382a70cd0232d.js:2)
    at vendors~app.90f320b382a70cd0232d.js:2
    at t.unstable_runWithPriority (vendors~app.90f320b382a70cd0232d.js:2)
```

For the network tab/request of the query executed, could you please guide me? I'm not that expert on this. What should I look for?
![Immagine 2021-06-30 232220](https://user-images.githubusercontent.com/51508670/124034872-0ee7f280-d9fc-11eb-88c5-29dd7cf22125.jpg)

**Comment by leeoniya** [comment] 2021-06-30 22:13
looks like a dupe of https://github.com/grafana/grafana/issues/35953 ?

**Comment by marefr** [comment] 2021-07-01 09:01
Duplicate of #35953

**Closed** 2021-07-01 09:02 UTC
Labels: area/frontend, type/duplicate
