### ISSUE TITLE
Removal of Org - User has to manually select new org

### ISSUE THREAD

**Issue by RyanW8** [grafana/grafana#31130] opened 2021-02-11 12:14 UTC
**What happened**:

- User logs into Grafana (OAuth2 authentication) we have `auto_assign_org` set to `false` so each new user is put in their own org until an admin moves them to a correct one.
- Admin assigns the user to a different org
- Admin removes the org which was created by Grafana
- The user (still logged in during this process) cannot see anything, and has to manually select the single org that is assigned to them by hovering over the user icon in the bottom left then going to preferences and clicking 'Select' on the single org that is assigned to them.

Logging out and then back in correctly selects the remaining org for the user

**What you expected to happen**:

When a user has 2 orgs assigned, and the one that is 'Selected' by the user is deleted, Grafana should automatically select the remaining org otherwise nothing is visible.

**How to reproduce it (as minimally and precisely as possible)**:

- Setup generic oAuth authentication with Grafana
- Disable `auto_assign_org`
- Create a `test org`
- Login with a new oAuth user
- Admin assigns `test org` to new oAuth user and deletes the org generated by Grafana.
- *bug* oAuth user has to manually select the only org assigned to them.

**Anything else we need to know?**:

Should be it.

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: N/A
- OS Grafana is installed on: Docker image, tag 7.4.0
- User OS & Browser: Windows 10/Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment] 2021-02-11 14:36
duplicate of https://github.com/grafana/grafana/issues/17464

**Closed by torkelo** 2021-02-11 14:36 UTC

**Comment by RyanW8** [comment] 2021-02-11 14:43
I may be misunderstanding that issue you linked @torkelo but that seems like something else?

**Comment by torkelo** [comment] 2021-02-11 14:46
slightly different, but looks like the same underlying cause
