### ISSUE TITLE
disable unwanted ranges from quick ranges

### ISSUE THREAD

**Issue by inbalzoran** [grafana/grafana#10911] opened 2018-02-14 14:05 UTC
Hey, 
Grafana   4.6.3
prometheus 2.1.0

i don’t want time ranges i don’t support to show in the quick ranges (like years back)
i want it to be editable, even just an option to remove some of your options
can you do that please?
Thanks

**Comment by torkelo** [comment] 2018-02-14 14:06
duplicate of https://github.com/grafana/grafana/issues/9814

**Closed by torkelo** 2018-02-14 14:06 UTC
