### ISSUE TITLE
Playlist cycle stops randomly with error "Possibly unhandled rejection" in console

### ISSUE THREAD

**Issue by tibbing** [grafana/grafana#10518] opened 2018-01-15 11:10 UTC
We're seeing this issue on hosted Grafana (grafana.net) version 4.6.3

After starting a playlist, the cycle stops randomly and goes back to the playlists page (with no playlists listed). Refreshing the page fixes the issue until next time it stops. 

The playlist can run anywhere from an hour to several hours before it happens, still it's an annoying issue since we have to remote in to the machine connected to our TV and refresh. 

The console shows the following errors:
`Possibly unhandled rejection:`
`Server side error :(`

And this one:
`Error: [$http:baddata] Data must be a valid JSON object. Received: "[{"id":4,"name":"Default","interval":"2m"}]<!DOCTYPE html>`

Any ideas?

**Comment by torkelo** [comment] 2018-01-15 11:44
looks like an http error, any nginx or apache proxy infront off grafana?  something is returning in valid json

**Comment by tibbing** [comment] 2018-01-15 12:04
Nope, no proxy it's the cloud-hosted version of Grafana. We are seeing issues sometimes with our data sources returning bad data because of timeouts etc. but I can't see how that should affect the playlist? When that happens we normally just get the error on a specific panel.

**Comment by tibbing** [comment] 2018-01-16 09:51
Attaching screenshots of the errors.

![playlist](https://user-images.githubusercontent.com/4194583/34982522-e7abf786-faaa-11e7-8e9e-cfe29d2a7d06.PNG)
![console1](https://user-images.githubusercontent.com/4194583/34982529-ece6c62c-faaa-11e7-9882-6a421e052336.PNG)
![console2](https://user-images.githubusercontent.com/4194583/34982531-ee701b2e-faaa-11e7-8bec-3c6631add73a.PNG)

**Comment by funrockstefan** [comment] 2018-01-22 09:54
Any update on this issue @torkelo ?

**Comment by tibbing** [comment] 2018-02-13 11:41
Bump
This happens every few hours for us, getting annoying. Any suggestions @torkelo ?

**Comment by torkelo** [comment] 2018-02-13 12:53
Sorry,no updates, have not been able to replicate and no other reports.

**Comment by onorua** [comment] 2018-02-22 22:49
we do have this on 4.6.3 as well, not sure about previous versions. @tibbing did you experience the same on 4.6.0?

**Comment by tibbing** [comment] 2018-02-23 10:36
Sorry haven't tested this on 4.6.0 so I can't say for sure. But it's easily reproduced in the current cloud-hosted environment.

**Comment by onorua** [comment] 2018-02-24 16:41
I can confirm that version 4.6.0 doesn't have this issue.

There is one more thing I noticed with 4.6.3. We have 3 nodes:
2 in AWS in different regions 
1 in DigitalOcean

Both of AWS nodes stuck for about 40 minutes each randomly once in a couple of days on 4.6.3. While DO node never had issues. 
On 4.6.0 - we had not issues for quite some time. 
I believe there is some issue with combination of Grafana 4.6.3 + AWS, and it actually has error 5xx due to backend unavailability due to this. 
I do not know how Grafana cloud is working, but if they have AWS, and bunch of nodes as we are, they may not notice downtime of one node for about 40 minutes, while it stops playlist :(

**Comment by tibbing** [comment] 2018-02-28 13:51
We gave up and switched to the Revolver plugin for chrome instead. For anyone else having this issue I can recommend that as a temporary solution until this is fixed.

https://chrome.google.com/webstore/detail/revolver-tabs/dlknooajieciikpedpldejhhijacnbda?hl=en

**Comment by bergquist** [comment] 2018-04-10 20:51
Can you reproduce this in 5.0.x?

**Comment by tibbing** [comment] 2018-04-13 14:41
I ran the playlist during the night, no errors so far.

**Comment by bergquist** [comment] 2018-04-16 10:51
Still no errors? I'm closing this if thats the case.

**Comment by tibbing** [comment] 2018-04-16 15:24
I think you can close it. Will open a new issue if it happens again.

**Comment by bergquist** [comment] 2018-04-17 06:26
:+1:

**Closed by bergquist** 2018-04-17 06:26 UTC
Labels: comp: playlist, state: needs more detail, type: bug
