### ISSUE TITLE
Cannot create dashboard under reverse proxy with /dashboard as sub-path

### ISSUE THREAD

**Issue by williamsonrichard** [grafana/grafana#12629] opened 2018-07-16 21:53 UTC
With the following nginx config

```        
        location /dashboard/ {
                proxy_pass http://localhost:3000/;
        }
```

and the following line in grafana.ini

```
root_url = %(protocol)s://%(domain)s/dashboard/
```

I get a 'page not found' when trying to create a new dashboard from the Home Dashboard. 

This seems to happen for all pages with /dashboard in the URL, whilst all other pages seem work fine. All works fine if 'dashboard' is replaced by 'grafana', say, in the nginx config and in grafana.ini.

The version of Grafana is 5.2.1 (2040f61). This is on a CentOS server.

**Comment by daniellee** [comment] 2018-07-17 08:13
Duplicate of #11335

It is relatively easy for you to change your nginx config to something else rather than /dashboard so we will not be fixing this. This conflicts with one of Grafana's routes.

**Closed by daniellee** 2018-07-17 08:13 UTC
Labels: type: duplicate

**Comment by williamsonrichard** [comment] 2018-07-17 19:55
No problem, understand not wishing to fix it, but perhaps it would be a good idea to document it somewhere? It seems reasonably likely that people might choose 'dashboard' as root.
