### ISSUE TITLE
own, private signed plugins are not loadable since moving from 7.5.6 to v8.0.0-beta.2

### ISSUE THREAD

**Issue by srw2ho** [grafana/grafana#34718] opened 2021-05-26 09:16 UTC
**What happened**: external builded private signed plugins not loadable

**What you expected to happen**: same behaviour as version  <= 7.5.6

**How to reproduce it (as minimally and precisely as possible)**: grafana toolkit creation with test plugin sample also not loadable
"npx @grafana/toolkit plugin:create mh-parameditor-plugin"
yarn install, yarn dev, sign plugin -> plugin not loadable

**Anything else we need to know?**: 

pictures for showing  can not be uploaded.

**Environment**:
- Grafana version: v8.0.0-beta.2
- Data source type & version: 
- OS Grafana is installed on: inside docker app

- User OS & Browser:
- Grafana plugins: own private signed plugins
- Others:

**Comment by wbrowne** [comment] 2021-05-26 10:42
@srw2ho Is there any information in the logs that you can provide relating to this plugin?

**Comment by srw2ho** [comment] 2021-05-26 13:40
I will send back picture and log Infos.

It seems so, that the img/logo.svn is not loadable for all external builded Plugins. Signing of Plugins is ok.



Freundliche Grüße 

Willi Schneider

**Comment by srw2ho** [comment] 2021-05-27 06:19
pictures and grafana-logs.

[logfile.txt](https://github.com/grafana/grafana/files/6551532/logfile.txt)
<img width="1042" alt="picture_01" src="https://user-images.githubusercontent.com/34190939/119775544-0dd71900-bec4-11eb-80ab-3ae317142c90.png">
<img width="924" alt="picture_02" src="https://user-images.githubusercontent.com/34190939/119775547-0f084600-bec4-11eb-8501-d8b145aabee4.png">
<img width="924" alt="picture_03" src="https://user-images.githubusercontent.com/34190939/119775548-0f084600-bec4-11eb-95b2-3598b2f7236f.png">
<img width="673" alt="picture_04" src="https://user-images.githubusercontent.com/34190939/119775549-0f084600-bec4-11eb-8473-880cebc82959.png">
<img width="1271" alt="picture_05" src="https://user-images.githubusercontent.com/34190939/119775552-0fa0dc80-bec4-11eb-8934-775c94456062.png">
<img width="1104" alt="picture_06" src="https://user-images.githubusercontent.com/34190939/119775554-0fa0dc80-bec4-11eb-8de9-4d33eb736d45.png">

**Comment by srw2ho** [comment] 2021-05-31 07:01
[mh-parameditor-plugin.zip](https://github.com/grafana/grafana/files/6568366/mh-parameditor-plugin.zip)

plugin.json:

  "name": "mh-parameditor-plugin",
  "id": "atmo-9-de-mh-parameditor-plugin",

**Comment by srw2ho** [comment] 2021-05-31 07:06
[mh-parameditor-plugin.zip](https://github.com/grafana/grafana/files/6568392/mh-parameditor-plugin.zip)

plugin.json:

 "name": "mh-parameditor-plugin",
  "id": "atmo-9-de-mh-parameditor-plugin",

**Comment by srw2ho** [comment] 2021-05-31 07:25
I try to build simple panel plugin with command npx @grafana/toolkit plugin:create my-plugin

For building I  used 
 nodejs-Version 14.15.5 under Ubuntu 18 in wsl2-environment 
 nodejs 12-version in a windows cmd.

All that results in the same 404 error.

Within grafana v7.5.6 all plugins runs.

Could it be, that I use a wrong  grafana/toolkit@latest for building or the plugin-ID has not the right format.

**Comment by wbrowne** [comment] 2021-06-01 08:50
I'm starting to think that maybe the problem lies somewhere else in the configuration of your Grafana @srw2ho. Currently I'm trying to reproduce with the following:

```
docker run -d \
-p 3000:3000 \
--name=grafana \
-e "GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana" \
-e "GF_SERVER_SERVE_FROM_SUB_PATH=true" \
-e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=atmo-9-de-mh-parameditor-plugin" \
-v /Users/wbrowne/data:/var/lib/grafana \
grafana/grafana:8.0.0-beta2
```

(Note that the `atmo-9-de-mh-parameditor-plugin`  zip you provided is extracted in my local folder and therefore mounted in `/var/lib/grafana/plugins`)

Can you reproduce if you execute the above?

**Comment by srw2ho** [comment] 2021-06-01 12:43
I was starting docker with the following command under **windows/wsl2**, mounted with my local data paths:

`docker run -d -p 3000:3000  --name=grafana -e "GF_SERVER_ROOT_URL=https://localhost:3000/grafana" -e "GF_SERVER_SERVE_FROM_SUB_PATH=true" -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=atmo-9-de-mh-parameditor-plugin" -v D:\BitBucket\Dashboard\grafana-mh\data:/var/lib/grafana -v D:\BitBucket\Dashboard\grafana-mh\data\plugins:/var/lib/grafana/plugins grafana/grafana:8.0.0-beta2`

I launch grafana frontend under "http://localhost:3000/grafana/" with chrome-browser.

But, I have the same behavior as before ( using grafana inside my docker- composer-file).
As follows a debug message from chrome debugger:
**logo.svg:1 GET http://localhost:3000/grafana/public/plugins/atmo-9-de-mh-parameditor-plugin/img/logo.svg 404 (Not Found)**

grafana logging:

```
t=2021-06-01T12:39:42+0000 lvl=info msg="Starting Grafana" logger=server version=8.0.0-beta2 commit=9d4c719205 branch=HEAD compiled=2021-05-20T09:51:41+0000

t=2021-06-01T12:39:42+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini

t=2021-06-01T12:39:42+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=https://localhost:3000/grafana"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_SERVER_SERVE_FROM_SUB_PATH=true"

t=2021-06-01T12:39:42+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=atmo-9-de-mh-parameditor-plugin"

t=2021-06-01T12:39:42+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana

t=2021-06-01T12:39:42+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana

t=2021-06-01T12:39:42+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana

t=2021-06-01T12:39:42+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins

t=2021-06-01T12:39:42+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning

t=2021-06-01T12:39:42+0000 lvl=info msg="App mode production" logger=settings

t=2021-06-01T12:39:42+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3

t=2021-06-01T12:39:43+0000 lvl=info msg="Starting DB migrations" logger=migrator

t=2021-06-01T12:39:43+0000 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=327 duration=1.2182ms

t=2021-06-01T12:39:43+0000 lvl=info msg="Starting plugin search" logger=plugins

t=2021-06-01T12:39:43+0000 lvl=info msg="Registering plugin" logger=plugins id=input

t=2021-06-01T12:39:43+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-plugin-admin-app

t=2021-06-01T12:39:43+0000 lvl=info msg="Registering plugin" logger=plugins id=atmo-9-de-mh-parameditor-plugin

t=2021-06-01T12:39:43+0000 lvl=info msg="Telemetry Gateway initialization" logger=live.push_http

t=2021-06-01T12:39:43+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl=/grafana socket=

t=2021-06-01T12:39:47+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=172.17.0.1 time_ms=6 size=0 referer=

t=2021-06-01T12:40:10+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=172.17.0.1 time_ms=1109 size=0 referer=

t=2021-06-01T12:40:18+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/plugins/atmo-9-de-mh-parameditor-plugin/img/logo.svg status=404 remote_addr=172.17.0.1 time_ms=298 size=1735 referer="http://localhost:3000/grafana/dashboard/new?orgId=1&editPanel=2"

t=2021-06-01T12:40:21+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/plugins/atmo-9-de-mh-parameditor-plugin/module.js status=404 remote_addr=172.17.0.1 time_ms=16 size=1735 referer="http://localhost:3000/grafana/dashboard/new?orgId=1&editPanel=2"

t=2021-06-01T12:40:21+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/plugins/atmo-9-de-mh-parameditor-plugin/img/logo.svg status=404 remote_addr=172.17.0.1 time_ms=14 size=1735 referer="http://localhost:3000/grafana/dashboard/new?orgId=1&editPanel=2"

```

Normally, i use grafana inside an container app with multiple other instances. I use traefik as reverse proxy for accessing grafana.
But without using traefik i had the same behavior.

Here an extract from my docker composer file:
```
grafana:
    image: grafana/grafana:8.0.0-beta2
    container_name: MHgrafana
    restart: unless-stopped
    # for using without traefik
    # ports:
    #   - "3000:3000"
    env_file:
      - "${CONFIG_PATH}/grafana/env.grafana"
    user: "0"

    volumes:
      # Data persistency
      - ${CONFIG_PATH}/grafana/data:/var/lib/grafana
      - ${CONFIG_PATH}/grafana/data/plugins:/var/lib/grafana/plugins
      # user-configuration for grafana
      - ${CONFIG_PATH}/grafana/grafanaconf:/usr/share/grafana/conf
      - ${CONFIG_PATH}/grafana/grafanaconf/custom.ini:/etc/grafana/grafana.ini

    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web,websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)
      - traefik.http.routers.grafana.middlewares=add-slash@docker
    command: tail -f /dev/null
```

**Comment by wbrowne** [comment] 2021-06-03 13:08
Alright so I did some digging @srw2ho and was able to reproduce with your same environment. The reason why the images are 404ing is that the Grafana server will not server plugin assets if they are UNIX executables. This only happens because of how Docker for Windows does its thing. As per the [official Docker docs](https://docs.docker.com/desktop/faqs/#can-i-change-permissions-on-shared-volumes-for-container-specific-deployment-requirements):
>Docker Desktop does not enable you to control (chmod) the Unix-style permissions on shared volumes for deployed containers, but rather sets permissions to a default value of 0777 (read, write, execute permissions for user and for group) which is not configurable.



Not sure if there's anything we will prioritize for this right now. You can avoid this if you don't mount your plugins and instead install them via [a method such as this](https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-from-other-sources).

**Comment by srw2ho** [comment] 2021-06-07 05:47
Many, many thanks for your support, without it I could not have found the cause.

This means that comfortable development of custom plugins in a (Windows/wsl2/Docker) environment will no longer be possible as before.

Changes to the source code in conjunction with "yarn watch" and then a browser restart will no longer work. When making changes to the source code, the grafana server will then always have to be restarted or the grafana-docker will have to be rebuilt.

Is there a way to install local images using the grafana-cli without https-requests when starting the grafana-server? 

Friendly greetings

Willi Schneider

**Comment by Coding-Mike** [comment] 2021-06-07 13:00
I have the same issue with all my plugins since version 8.0.0-beta2

I use the following Dockerfile to create the docker image with grafana and the preinstalled plugins:

`FROM grafana/grafana:${GRAFANA_VERSION}                                     

USER grafana                
 
# ADD all base plugins from BaseGrafanaPlugins                                     
ADD BaseGrafanaPlugins /var/lib/grafana_plugins `

The folder BaseGrafanaPlugins contains the unzipped plugins from the official plugin page of grafana.

None of the plugins are working. When using the same approach in 7.5.7 it worked.

I use Docker for Windows on a Windows machine to create the docker file and the BaseGrafanaPlugins folder is located on the Harddrive.

I hope this helps to locate the issue.

Kind regards
Michael

**Comment by wbrowne** [comment] 2021-06-09 09:31
@srw2ho @Coding-Mike I just wanted to understand if your situations are the same in order to find the best path forward. Are you both experiencing this whilst in an environment (Windows + Docker) for developing your private plugins? Or is this used beyond that e.g how you're managing your production Grafana

**Comment by Coding-Mike** [comment] 2021-06-09 09:42
@wbrowne I use (Windows + Docker) to create the custom grafana docker image with the Dockerfile as mentioned above. Then the grafana instance runs inside a kubernetes cluster on linux (ubuntu) maschines. The only thing I do is download the plugins from the grafana page and unzip them into the BaseGrafanaPlugins on Windows and then run the docker build command with the Dockerfile.

In version 7.5.7 this approach worked and the plugins worked as expected. Starting with 8.0.0-beta1 this stopped working.

Kind regards
Michael

**Comment by johnatannvmd** [comment] 2021-06-09 10:46
Looks like files with executable attribute not available for downloading via `/public/plugins/`. This has been made in the case of protection from downloading plugins binaries.

If you do not have any plugins with executable backends this should help:
```Dockerfile
FROM grafana/grafana:${GRAFANA_VERSION}

USER grafana

ADD BaseGrafanaPlugins /var/lib/grafana_plugins

RUN chmod -R ogu-x /var/lib/grafana_plugins
```

**Comment by Coding-Mike** [comment] 2021-06-09 11:21
@johnatannvmd I tried this approach but I already get an error when running the docker build command. The last command always claims Operation not permitted and then exits with error code 123.

**Comment by johnatannvmd** [comment] 2021-06-09 11:24
> @johnatannvmd I tried this approach but I already get an error when running the docker build command. The last command always claims Operation not permitted and then exits with error code 123.

Maybe this helps, not tested just first what I'm thought about.

```Dockerfile
FROM grafana/grafana:${GRAFANA_VERSION}

ADD BaseGrafanaPlugins /var/lib/grafana_plugins

RUN find /var/lib/grafana_plugins -type f | xargs chmod ogu-x && \
    chown -R grafana: /var/lib/grafana_plugins

USER grafana
```

**Comment by Coding-Mike** [comment] 2021-06-09 11:37
@johnatannvmd I tried the second approach and got the same error message.

**Comment by Coding-Mike** [comment] 2021-06-09 12:43
I found a fix for this issue.
I use the following Dockerfile to create the new image

```
FROM grafana/grafana:${GRAFANA_VERSION}

USER grafana

ADD BaseGrafanaPlugins /var/lib/grafana_plugins

USER root

RUN find /var/lib/grafana_plugins -type f | xargs chmod ogu-x && \
    chown -R grafana: /var/lib/grafana_plugins

USER grafana

```

**Comment by srw2ho** [comment] 2021-06-09 13:59
We use Grafana on a Windows machine. We use Grafana as a viewer for test bench data **as well as for operating the test bench software**. The test bench software runs exclusively under Windows, therefore a Grafana/Unix environment is not so easy to create.
I know that the Windows Docker story is not optimal, but I don't see a quick way to change this at the moment.

**For the operation of our test benches we use a modified Grafana Client.**

As communication channel for the operating channel the already existing Redux-Store is used in both directions ( from the device to Grafana and from Grafana to the device). 


Therefore the original Grafana will be extended by a paho-MQTT interface, which will write data to the Redux-Store via the MiddleWare sagas.

For our test bench control panels we use the existing UI elements of Grafana. This all works very well.

Updates of custom control panels is easily achieved via the shared/mapped folder in the docker composer file. We simply copy the plugins to the mapped directory.

For building my custom Grafana locally, I use a WSL2/Ubuntu-18.04 environment on Windows. For building the Grafana Docker Image, I use the existing (slightly modified) Docker file located in the root directory of Grafana.  I can modify the Docker File accordingly for the build process. To do this, I would need to know where I would need to make changes so that custom PlugIns would be loadable again.

Kind regards

W. Schneider

**Comment by wbrowne** [comment] 2021-06-09 20:51
Nice one @Coding-Mike - thanks for sharing that. Could you adapt your setup to use this too @srw2ho and see if it works out? I know this is not ideal, but I'd prefer not to revert that security improvement that was recently added.

If that seems to do the job, I'll go ahead and add that to the docs

**Comment by foosel** [comment] 2021-06-13 15:37
> The reason why the images are 404ing is that the Grafana server will not server plugin assets if they are UNIX executables.

Just chiming in here to say that I ran into this as well with an existing instance running in a Docker container on a (Linux based) Synology NAS but wonky permissions set on the volume mount attached to `/var/lib/grafana`. Container against said volume mount up to 7.5.7 worked fine. But after updating to first 8.0.0 and then 8.0.1 images, officially listed & signed (!) plugins would register and load just fine according to the log, but attempting to actually access any of their static files from the frontend would only generate 404s. After some days of trying to debug this and finally a [cry for help on Twitter & some debugging back and forth](https://twitter.com/foosel/status/1403805021574254592) I was pointed here and a simple `chmod -R o-x` on the plugins folder fixed this (why it started out with an executable bit to begin with is something I'm still investigating, it certainly wasn't intentional).

If I may make a suggestion here, it would have been easier to find this if there was some kind of verbose permission check on startup or even just an additional log line in case of a 404 generated due to a set executable bit (possibly only if debug logging is enabled). The way things are just being silently denied I was brought to my wit's end by this (sensible but a tad intransparent) failure mode 😅 In any case, please keep up the great work! 👍

**Comment by wbrowne** [comment] 2021-06-14 08:20
Thanks for sharing @foosel - really appreciate it! I think a log would certainly have been useful, so I'll go ahead and add one.

I'll close this for now, but this can be re-opened if any more improvements should be made. Thanks all!

**Closed by wbrowne** 2021-06-14 08:20 UTC
Labels: area/plugins, needs investigation

**Comment by nhart12** [comment] 2021-06-29 20:49
@wbrowne I'm experiencing this same issue when running out in azure with a mounted file share after updating to v8. I believe the volume get's mounted as root users with full permissions, and it sounds like this is too much permissions and causes the 404s? Any ideas here?

**Comment by nhart12** [comment] 2021-06-29 21:34
For now my workaround is the mount the database only in the fileshare to /var/lib/grafanadata and then changing the GF_PATHS_DATA to /var/lib/grafanadata. This just means the plugins won't be persisted on container reboots, but not the end of the world

**Comment by wbrowne** [comment] 2021-06-30 14:06
See this comment @nhart12 https://github.com/grafana/grafana/issues/34718#issuecomment-857661808

**Comment by MenigaDonatas** [comment] 2021-06-30 20:28
> For now my workaround is the mount the database only in the fileshare to /var/lib/grafanadata and then changing the GF_PATHS_DATA to /var/lib/grafanadata. This just means the plugins won't be persisted on container reboots, but not the end of the world

thanks, had same issue with azure fileshares

**Comment by yggdrasil-tynor** [comment] 2021-07-01 07:43
Would it perhaps make sense to run the grafana process as another user?

**Comment by yggdrasil-tynor** [comment] 2021-07-01 07:44
Good workaround, but would it make sense to make it possible to support running with other permissions to fix this issue?

**Comment by mig4** [comment] 2021-07-01 09:32
Same problem here (files with executable permissions causing 404 errors when loading the plugin files) but we use Grafana on Kubernetes and install the plugins via the `GF_INSTALL_PLUGINS` env var mechanism, so tweaking the Dockerfile is not a viable solution as plugin installation happens at runtime, not at build time.

I'm going to investigate why the plugin I'm trying to install has all files marked executable in the first place, but I agree that a better error message would be quite useful.
