### ISSUE TITLE
[FR] Add optional HTTP headers showing the source of the request when calling datasource

### ISSUE THREAD

**Issue by uepoch** [grafana/grafana#18344] opened 2019-08-02 08:43 UTC
Hello grafana !

On https://github.com/grafana/grafana/pull/17420 it is mentionned that backend_srv could be used to add tracking headers.

**What would you like to be added**:
We would like to generalize the use of X-Grafana-User / X-Grafana-Org-ID / X-Panel-ID / X-Dashboard-Id:
- Add them in all datasources, not just graphite / prometheus
- Send them from the frontend directly, so there's no need to use the datasource proxy (OPT)
- Replace X-Dashboard-ID by either the uid or the slug as it makes little sense to end-users

**Why is this needed**:
For a large company, with thousands of graphs, being able to identify traffic origin is a must-have, and it would really ease detection of unwanted behaviors to have theses informations directly provided by the Grafana calls.

**Comment by marefr** [comment] 2019-08-05 16:04
Duplicate of #17410

**Closed by marefr** 2019-08-05 16:04 UTC
Labels: area/datasource/proxy, type/feature-request
