### ISSUE TITLE
Default Timepicker Settings

### ISSUE THREAD

**Issue by martbhell** [grafana/grafana#2726] opened 2015-09-11 06:48 UTC
Hi, 

is there a way to modify the default timepicker settings for new dashboards?
Like if I hit the equivalent of http://play.grafana.org/dashboard/new in 2.1.3 I would like the new dashboard to have a few options for longer periods such as 4w and 3M.

**Comment by torkelo** [comment] 2015-09-11 07:00
not currently, but would love to this

**Comment by torkelo** [comment] 2015-09-11 07:00
dupe of #1914

**Closed by torkelo** 2015-09-11 07:00 UTC
