### ISSUE TITLE
TV and Sharing Icons missing from dashboard if window is small

### ISSUE THREAD

**Issue by colinl** [grafana/grafana#16382] opened 2019-04-04 13:42 UTC
**What happened**:
Viewing the dashboard (graph panel) in Firefox if the window size is reduced below about 780 px both the TV and Share icons suddenly disappear.  They reappear when the window is enlarged again.
The symptom is also seen on mobile devices running Chrome on Android.  On a Nexus 7 they are visible in landscape mode but not portrait, and on my phone they are never visible.  This means that it is not possible to hide the side menu on smaller mobile devices.

**What you expected to happen**:
The icons should not disappear, the window should have a scroll bar if there is insufficient room.

**How to reproduce it (as minimally and precisely as possible)**:
View the dashboard and reduce the window size.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.0 (from packages.grafana.com repository)
- Data source type & version: Influx but N/R I think.
- OS Grafana is installed on: Ubuntu 18.10
- User OS & Browser: Ubuntu 18.10, Firefix and Android with Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-04-04 16:54
duplicate of https://github.com/grafana/grafana/issues/11523

**Comment by colinl** [comment] 2019-04-04 19:05
I don't believe this is a duplicate of #11523. This relates to the TV icon as well as the Share icon, and I am not running an adblocker or similar.  In particular on the PC the icons disappear as the window is reduced in size so can be nothing to do with an adblocker.  If the duplicity (?) relates to the suggestion that they disappear because there is not room for them then this is not appropriate now that the TV icon is the only way to hide the side menu.  The result is that on a device with a small screen there is now no way of hiding the side menu.

**Comment by daniellee** [comment] 2019-05-02 11:20
As #11523 was closed due to being an adblocker issue, I'm reopening this issue. This is not a bug, more a design issue. The icons are hidden on purpose for smaller screens but as you say it is now difficult to hide the side menu on smaller screens.

**Comment by torkelo** [comment] 2019-05-02 12:29
https://github.com/grafana/grafana/pull/16783 changes the breakpoint when sidemenu is hidden and mobile menu is enabled so v6.2 will see a big improvement for smaller screens (~ipad in portrait).

**Closed** 2019-05-03 17:12 UTC
Labels: area/frontend, type: ux
