### ISSUE TITLE
The plugin page has been stuck on "Loading results," preventing me from enabling Zabbix. Can someone tell me what to do?

### ISSUE THREAD

**Issue by zasufe** [grafana/grafana#78039] opened 2023-11-11 11:53 UTC
The plugin page has been stuck on "Loading results," preventing me from enabling Zabbix. Can someone tell me what to do?

My Grafana server is in an offline, non-networked environment, and I've already installed the plugins offline. However, I'm unable to enable them.
![image](https://github.com/grafana/grafana-zabbix/assets/49631859/a6675522-fab4-4df0-a0cb-46256afa7fe9)

**Comment by zoltanbedi** [comment] 2023-11-13 10:29
I've transfered the issue from zabbix as it is more a question/feature request in grafana.

**Comment by gabor** [comment] 2023-11-13 13:09
@grafana/plugins-platform-frontend , could you take a look please? thanks!

**Comment by mckn** [comment] 2023-11-13 13:17
This should be fixed by the following PR https://github.com/grafana/grafana/pull/77978

**Comment by zoltanbedi** [comment] 2023-11-13 13:33
Awesome! @mckn 🎉

**Comment by zoltanbedi** [comment] 2023-11-13 13:35
We can close this as a duplicate of https://github.com/grafana/grafana/issues/77905

**Closed by zoltanbedi** 2023-11-13 13:35 UTC
