### ISSUE TITLE
[Feature Request]Elasticsearch time offset per metric

### ISSUE THREAD

**Issue by greg-peterson** [grafana/grafana#5804] opened 2016-08-12 18:44 UTC
In elasticsearch query editor allow setting a time shift on each metric so that a single graph could compare multiple time ranges.  Currently can only set time shift for entire panel.  I think it would be similar to the graphite timeshift(7d) function

For instance I would set
- metric A to: Query: *, Metrics: Count, Group by: Date Histogram(@timestamp),
- metric B to: Query: *, Metrics: Count, Group by: Date Histogram(@timestamp), Timeshift(-7d)

Bonus would be for it to accept a template variable for the offset so that the user of the graph could select the offset depending on their interest.

**Comment by wfeng1982** [comment] 2017-02-14 03:07
when would this feature be implemented?

**Comment by bergquist** [comment] 2017-02-14 08:35
@wfeng1982 there is no plans for implementing this atm.

**Comment by ictcorebiz** [comment] 2018-01-09 10:25
This would be a good way to have 2 queries to compare "Today" with "Same day last week" in one graph. Or is there any other way I could accomplish this with ElasticSearch?

**Comment by georgenica** [comment] 2018-06-30 13:05
We are currently using this w/ Timelion in Kibana in order to be able to compare traffic "today" with "traffic 7 days ago" on the same graph, similar to @ictcorebiz suggested. I believe this would be very useful, is there any plan to support this in a future version?

**Comment by davewat** [comment] 2018-06-30 13:45
@georgenica we use needed the same capability, and found the excellent Meta Queries Data Source plugin at https://github.com/GoshPosh/grafana-meta-queries to do just that, comparing multiple time periods using Elasticsearch.

**Comment by Elfo404** [comment] 2020-12-09 13:57
closing this as it seems a duplicate of https://github.com/grafana/grafana/issues/7762 which would solve the problem in a more generic way.

**Closed by Elfo404** 2020-12-09 13:57 UTC
Labels: area/datasource, datasource/Elasticsearch, type/feature-request
