### ISSUE TITLE
x-axis values(datetime) overlaps on Timeseries graph 

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#30959] opened 2021-02-07 04:07 UTC
The new Timeseries graph(Beta) seams to have problems with text size so the date-time text on the x-axis overlaps. Not sure if that can be control manualy

Old table graph
![image](https://user-images.githubusercontent.com/8969659/107136219-9627b300-6901-11eb-8fc1-0e79302a6cc0.png)

Time series graph
![image](https://user-images.githubusercontent.com/8969659/107136321-3aa9f500-6902-11eb-9f5f-b87e217694b7.png)

**Comment by leeoniya** [comment] 2021-02-07 04:09
dupe of https://github.com/grafana/grafana/issues/30906

**Closed by leeoniya** 2021-02-07 04:09 UTC
