### ISSUE TITLE
Annotation query limit can clip one half of a region annotation

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#17645] opened 2019-06-18 17:21 UTC
**What happened**: A region annotation is painted incorrectly, covering the entire graph from the left instead of from the appropriate start time:

![region-annotation-bug](https://user-images.githubusercontent.com/814226/59704814-0896cd00-91cb-11e9-9d1d-72e7ba24ac02.png)

This occurs because the annotations query has a "Max Limit", but a region annotation is represented as two separate annotations. If one half is cut off by the limit then it is painted like this.

We can see in the request response that only one half of this region id is returned, even though both halves are in the database. If we increase the annotation `limit` then the problem goes away (but will reoccur once the new limit is hit).

**What you expected to happen**: The region to be painted in the appropriate time frame, or if it's easier, to simply drop the region annotation if only half of it was returned.

**How to reproduce it (as minimally and precisely as possible)**: Create an annotations query that returns > "Max Limit" annotations. If the MaxLimit+1 annotation is a region, then half of it will not be returned.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.2.2 (07540df)
- Data source type & version: Grafana native annotations
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: macOS Mojave / Safari 12.1.1
- Grafana plugins: n/a
- Others:

**Comment by ryantxu** [comment] 2019-06-18 18:26
I think the best way to fix this would be something like #17647  -- the region structure causes a bunch of weird behaviours like this

**Comment by marefr** [comment] 2019-06-18 20:38
Duplicate of #15764

**Closed** 2019-06-18 20:38 UTC
Labels: area/annotations, type/duplicate
