### ISSUE TITLE
Grafana 7.X Sign In link now points to localhost (was OK in 6.X)

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#26268] opened 2020-07-13 07:03 UTC
**What happened**:

Sign-in button: it shows a link to `localhost` while Grafana runs on `https://projectname.devstats.cncf.io`. All other links from Grafana UI just use `base` URL and correctly navigate to sub-URLs of `https://projname.devstats.cncf.io`. Sign-In is the only exception from this (so I need to manually put `&forceLogin=true` in the URL to be able to Sign in).
I'm using `instance_name = project.devstats.cncf.io` in `grafana.ini` - that was just enough for Grafana 6.X to make all links correct (everything runs behind Kubernetes `nginx` ingress + let's encrypt `https://`).

When I change `grafana.ini` to use `domain = project.cncf.devstats.io` (just like the `instalce_name` variable) Sign-In link is generated without `https://` like this: `projname.devstats.cncf.io-JGJHKLJHgfg-76738/.../rest-of-the-URL` (while other links UI are just fine `https://project.devstats.cncf.io/rest-of-the-URL`) no idea where `-JGJHKLJHgfg-76738/` comes from... in 6.X all works fine and I don't even need to specify `domain = ...` in grafana.ini file at all.

**What you expected to happen**:

Sign In link should be generated the same way as any other UI links (like Home, Settings, data sources etc.)

**How to reproduce it (as minimally and precisely as possible)**:

Install Grafana 7.X behind `nginx` and some https provider, use only `instance_name = your.domain.com` (where that Grafana runs).

**Anything else we need to know?**:

Worked just fine in 4.X, 5.X, 6.X.

**Environment**:
- Grafana version: 7.0.6
- Data source type & version: doesn't matter.
- OS Grafana is installed on: Ubuntu 20.04 LTS
- User OS & Browser: any
- Grafana plugins: nope
- Others: runs behind Kubernetes nginx + Let's encrpyt.

cc @torkelo

**Comment by torkelo** [comment] 2020-07-13 08:33
think it's a duplicate of https://github.com/grafana/grafana/issues/26228 

fix is on it's way https://github.com/grafana/grafana/pull/26239

**Closed** 2020-07-13 08:33 UTC

**Comment by lukaszgryglicki** [comment] 2020-07-13 08:52
Great, thanks, sorry for issues duplicates, but I'm blaming GitHub showing error page so many times and I was unable to check if issue was created or not.
