### ISSUE TITLE
TablePanel/Transforms: Convert Field Type Transform Boolean=>Numeric breaks table panel

### ISSUE THREAD

**Issue by BRM-SMS** [grafana/grafana#60072] opened 2022-12-09 07:30 UTC
**What happened**:

Some (not all) Table Panels appear empty (doesnt show 'No Data')

**What you expected to happen**:

not empty?

**How to reproduce it (as minimally and precisely as possible)**:

Query results

**Anything else we need to know?**:

Worked in 9.2.1 and after upgrading to 9.3.1, some tables are empty. There is data when inspecting the table.

Error in Browser inspection:
![Screenshot 2022-12-09 083013](https://user-images.githubusercontent.com/119508535/206648701-6cb20685-cff1-4e5d-b594-51b995c7647d.png)

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Chrome, Windows 11
- Grafana plugins: Table Panel
- Others:

**Comment by BRM-SMS** [comment] 2022-12-09 07:39
found out it has to do with Convert FIeld Type Transformation, after applying 

boolean > Numeric
string > Time DD.MM.YYYY

the whole table gets empty and browser shows the error above

**Comment by zuchka** [comment] 2022-12-09 19:28
Thanks for creating this issue, @BRM-SMS 

reproduced [here on play.grafana.org](https://play.grafana.org/d/5v20CqK4z/60072?orgId=1):

![CleanShot 2022-12-09 at 09 25 45](https://user-images.githubusercontent.com/37156449/206781938-05d09bcc-5c3f-4c00-908f-fc9fdd22a62f.gif)

**Comment by codeincarnate** [comment] 2022-12-12 16:01
@grafana/observability-metrics this looks like it could be an issue with the transform. Would you mind taking a look?

**Comment by atartareanu** [comment] 2022-12-13 08:31
Hello,
I have the same problem, converting fields to numeric breaks table view.

![image](https://user-images.githubusercontent.com/22320901/207261037-e286de07-d3d3-4b46-8671-d1cfc28b6ba4.png)

![grafana_transform_bug](https://user-images.githubusercontent.com/22320901/207265021-af2e5f15-a39f-4184-be7e-b5c5985c3e42.gif)

Thank you for looking at this bug.
Adrian.

**Comment by bohandley** [comment] 2022-12-13 22:04
Yep! It's a bug I introduced in converting strings to numbers, my apologies. I'll get a fix for this ASAP. Thank you for bringing it to my attention!

**Closed** 2022-12-14 18:00 UTC
Labels: type/bug, area/panel/table, area/transformations
