### ISSUE TITLE
"Annotation Query Failed" immediately after upgrade from 6.1.6 to 6.2.0

### ISSUE THREAD

**Issue by pavel-odintsov** [grafana/grafana#17238] opened 2019-05-22 20:47 UTC
Hello!

**What happened**:

```Annotation Query Failed
Internal Server Error
Annotation Query Failed
Internal Server Error
Annotation Query Failed
Internal Server Error
Annotation Query Failed
Internal Server Error

```

Error
```
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <meta name="viewport" content="width=device-width"> <meta name="theme-color" content="#000"> <title>Grafana - Error</title> <base href="/" /> <link rel="stylesheet" href="public/build/grafana.dark.42c3c32bf36973cb02e0.css"> <link rel="icon" type="image/png" href="public/img/fav32.png"> <link rel="mask-icon" href="public/img/grafana_mask_icon.svg" color="#F05A28"> </head> <body class="theme-dark"> <div class="main-view"> <div class="page-container"> <div class="page-header"> <div class="page-header__inner"> <span class="page-header__logo"> <i class="page-header__icon fa fa-frown-o"></i> </span> <div class="page-header__info-block"> <h1 class="page-header__title"> <a class="text-link" href="login">Grafana</a><span> / Server Error</span><span></span> </h1> <div class="page-header__sub-title">Sadly something went wrong</div> </div> </div> </div> </div> <div class="page-container page-body ng-scope" style="padding: 2rem"> <div class="alert"> <div class="alert-icon"><i class="fa fa-exclamation-triangle"></i></div> <div class="alert-body"> <div class="alert-title">database is locked</div> </div> </div> <br /> <div style="padding: 2rem 0 0"> <p>Check the Grafana server logs for the detailed error message.</p> </div> </div> </div> </body> </html> 
```

Logs:
```
t=2019-05-22T23:40:43+0300 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=1 orgid=1 username=admin datasource=influxdb uri="/api/datasources/proxy/3/query?db=xx&q=SELECT%20mean(%22bits%22)%20FROM%20%22total_traffic%22%20WHERE%20(%22direction%22%20%3D%20%27incoming%27)%20AND%20time%20%3E%3D%20now()%20-%2024h%20GROUP%20BY%20time(2m)%20fill(previous)&epoch=ms" method=GET body=
t=2019-05-22T23:40:43+0300 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/3/query status=500 remote_addr=127.0.0.1 time_ms=209 size=1723 referer="http://xx:81/d/q1DYNVLik/traffic?orgId=1&refresh=5s&from=now-24h&to=now"

```

**Workaround**:

Downgrade to 6.1.6 immediately resolves issue. 

**What you expected to happen**:

Working annotations

**How to reproduce it (as minimally and precisely as possible)**:

We use following configuration for annotations:
```select title, tags, text from events where $timeFilter```

**Anything else we need to know?**:

**Environment**:
- Reverse Proxy: Nginx
- Grafana version: 6.2.0
- Data source type & version: InfluxDB, 1.7.6-1
- OS Grafana is installed on: Ubuntu 14.04
- User OS & Browser: Chrome Linux and Firefox 
- Grafana plugins: Clickhouse, PieChart
- Others:

**Comment by marefr** [comment] 2019-05-23 08:55
@pavel-odintsov  

Given the "Error" you've included seems to me you've done a full page reload and got the Grafana server error screen rendered in browser? What happens if you're starting in the home dashboard and then navigate to your dashboard with annotations, same error screen?

Been trying to reproduce this, but works as expected for me. Working example here with reverse proxy: https://play.grafana.org/d/000000028/influxdb-annotations?orgId=1

Think you can enable data proxy logging and debug logging and include the log output from that when your error happens?

```
[dataproxy]
logging = true

[log]
filters = data-proxy-log:debug
```

Could you include a screenshot of your datasource configuration screen?
Could you check your reverse proxy logs for clues?
Could you check influxdb logs for clues?

Thank you

**Comment by marefr** [comment] 2019-05-23 13:43
Now I just spotted that the error output includes the following

> `<div class="alert-title">database is locked</div>`

Are you using sqlite? See https://github.com/grafana/grafana/issues/16638#issuecomment-494427913

**Comment by marefr** [comment] 2019-05-24 14:25
Short update. Think we identified the problem and a fix should be included in v6.2.1 which we hope to get out beginning next week. 

The fix should already be in master so if you have the chance please try one of the nightly builds/docker master/docker dev and please report back if it works better. Thanks

**Comment by marefr** [comment] 2019-05-24 14:27
I'm closing this in favor of #17247 since it has more comments and user reports.

**Closed by marefr** 2019-05-24 14:27 UTC
Labels: area/annotations, area/datasource/proxy, datasource/InfluxDB, needs investigation

**Comment by gearlbrace** [comment] 2020-02-05 23:51
I ran into this problem when my SSL cert expired. Replaced the cert with the updated one and restarted the grafana-server service and all was right.

Could it be that newer versions fail badly with expired or self-signed certs?
