### ISSUE TITLE
InfluxDB: When editing disabled query in dashboard, it becomes enabled

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#31054] opened 2021-02-09 16:20 UTC
**What happened**:
In dashboard, when query is disabled and you edit it, it becomes enabled. I was able to recreate this only for Influx and Flux and [Prometheus (separate issue).](https://github.com/grafana/grafana/issues/31048) I wasn't able to recreate this bug for Loki, Graphite, Elastic. 

**What you expected to happen**:
If query is disabled and I edit it, I still want it to be disabled.

**How to reproduce it (as minimally and precisely as possible)**:
![Kapture 2021-02-09 at 15 45 49](https://user-images.githubusercontent.com/30407135/107393445-1b29ec80-6afb-11eb-8d16-875c95a7925b.gif)

**Environment**:
- Grafana version: 7.4.0

**Comment by gabor** [comment] 2021-02-18 11:59
in the influxQL editor, it happens in the opposite too. so, you disable the query, apply the changes, edit the panel again, enable the query, edit the query, it automatically becomes disabled. it seems to revert to the "persisted" value.

**Comment by gabor** [comment] 2021-02-18 12:57
and the Flux editor is simply never disabled.

**Comment by gabor** [comment] 2021-02-18 18:50
looking at the influxql-editor, it seems this happens:
- let's assume when the query-editor is created `query.hide===false`, meaning the component is enabled
- the angular-based query-editor is created and is given a couple things here: https://github.com/grafana/grafana/blob/e4672906f0e29e76bd0b6546ccd072722f4d808b/public/app/features/query/components/QueryEditorRow.tsx#L83-L99
  - this is only called once, at the beginning. this means, the "target" here is the query-object from the "beginning". it has `query.hide===false`
- the user clicks on the enable/disable button, and the `QueryEditorRow` component gets new props, where `query.hide===true`
  - the angular component does not know about this at all. it only has access to the above-mentioned data, and that one contains the query from the "start". in that copy of the query, it is still `query.hide===false`.
- the user changes something in the angular component. the angular component mutates the "target" it has.
- the user clicks outside the angular component. the angular component calls `refresh`, which calls `onChange` here https://github.com/grafana/grafana/blob/e4672906f0e29e76bd0b6546ccd072722f4d808b/public/app/features/query/components/QueryEditorRow.tsx#L92
  - this call submits the query-object that was given to the angular-object at the start, where `query.hide=false`, and suddenly the component is not disabled anymore

**Comment by gabor** [comment] 2021-02-18 19:10
based on my previous comment, this should mean the problem is there in every angular-based query-editor. i verified the problem exists in the postgres data-source too.

the good news is we can maybe fix it in all of them at the same time :-)

**Comment by gabor** [comment] 2021-02-19 08:51
the InfluxQL editor is fixed now (together with other angular-based editors hopefully), the Flux-editor fix is in progress.

**Comment by gabor** [comment] 2021-03-03 11:59
the FluxQL editor is fixed now too, this should cover all the cases mentioned in the issue.

**Closed by gabor** 2021-03-03 11:59 UTC
Labels: datasource/InfluxDB, datasource/InfluxDB/flux, priority/important-longterm, type/bug
