### ISSUE TITLE
context deadline exceeded; two different notification channels failed!

### ISSUE THREAD

**Issue by KyleFromOhio** [grafana/grafana#21256] opened 2019-12-25 05:06 UTC
**What happened**: Grafana detected state change and attempted to send an alert to Slack AND to an email webhook. **Neither received/sent**. Errors in log.

**What you expected to happen**: To receive a slack alert and an email alert.

**How to reproduce it (as minimally and precisely as possible)**: Using a slack webhook notification channel to a channel and also a second alert to an email address.

**Anything else we need to know?**:

Errors in log ...
Dec 25 04:26:40 servername grafana-server[881]: t=2019-12-25T04:26:40+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=9 notification=SLACK-alert-critical
Dec 25 04:26:40 servername grafana-server[881]: t=2019-12-25T04:26:40+0000 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook=SLACK-ale
rt-critical
Dec 25 04:26:40 servername grafana-server[881]: t=2019-12-25T04:26:40+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000005 error="context deadline exceeded"
Dec 25 04:26:40 servername grafana-server[881]: t=2019-12-25T04:26:40+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000005 error="context deadline exceeded"
Dec 25 04:26:40 servername grafana-server[881]: t=2019-12-25T04:26:40+0000 lvl=eror msg="Failed to send pushover notification" logger=alerting.notifier.pushover error="context deadline exceeded" webhook=emailmewebhook
Dec 25 04:26:40 servername grafana-server[881]: t=2019-12-25T04:26:40+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000006 error="context deadline exceeded"

**Environment**: Linux Ubuntu 18.04
- Grafana version:  Grafana v6.5.2 (commit: 742d165)
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by KyleFromOhio** [comment] 2019-12-25 05:54
I did the following to try and fix the issue myself. The real issue is I was expecting to be notified of critical alerts and was NOT which was a major concern. 

**FIX?** 
installed grafana image renderer since phantomJS is deprecated. 
Also turned off image rendering on alert notification channels. 
Did a test on critical channel to slack and it worked. It also successfully send alert to my email webhook. 
Also set under alerts in grafana.ini the timeout settings from 30 to 60 seconds.
 $ grafana-cli plugins install grafana-image-renderer
 $ sudo nano /etc/grafana/grafana.ini
[alerting]
concurrent_render_limit = 15
evaluation_timeout_seconds = 60
notification_timeout_seconds = 60
max_attempts = 5
 $ sudo service grafana-server restart

**Comment by hugohaggmark** [comment] 2019-12-27 04:55
@KyleFromOhio do I understand you correctly that you solve this by installing the `grafana-image-renderer` plugin? I haven't seen any other reports about PhantomJs and Slack so it would be good to know If this is really an issue.

All the best

**Comment by marefr** [comment] 2020-01-13 12:48
Duplicate of #2101

**Comment by marefr** [comment] 2020-01-13 12:49
Duplicate of #21018

**Closed by marefr** 2020-01-13 12:48 UTC
Labels: needs more detail
