### ISSUE TITLE
Easier to understand histogram error message for Grafana Cloud Logs customers

### ISSUE THREAD

**Issue by 09jvilla** [grafana/grafana#48988] opened 2022-05-15 14:55 UTC
When the log volume histogram times out, we return an error message that says 'context deadline exceeded', which is a bit hard for a user to understand. 

Can we change this error message, replacing 'context deadline exceeded' with 'Request timed out. Please try again with a shorter time range.' Note: we should still keep the top part of the error which says 'Failed to load log volume for this query.'

<img width="1361" alt="Screen Shot 2022-05-08 at 3 55 15 PM" src="https://user-images.githubusercontent.com/9610816/168479170-e10f32b6-2a87-4daa-b8fc-a95b4ca8b8be.png">

Suggestion from the Loki backend team (cc @kavirajk ) is to improve the error handling on the frontend rather than the backend for this.

**Comment by 09jvilla** [comment] 2022-05-15 14:57
@kavirajk are there any corner cases we need to think about for this? if we just look for 'error=context deadline exceeded' and 'errortype=timeout' is it enough to just transform this on the frontend to 'Request timed out. Please try again with a shorter time range.'? or is there some other time in which you might see 'error=context deadline exceeded' and 'errortype=timeout' that we might need some other, different message?

**Comment by 09jvilla** [comment] 2022-05-15 14:57
cc @gabor for vis

**Comment by joey-grafana** [comment] 2022-05-17 08:31
The `context deadline exceeded` message is coming from `usr/local/go/src/context/context.go`. 
We could check on [this line](https://github.com/grafana/grafana/blob/main/public/app/features/explore/LogsVolumePanel.tsx#L25) if the error & errorType matches and then display a custom error message as suggested i.e. `Request timed out. Please try again with a shorter time range.` The issue here is that if the `context deadline exceeded` error or `errortype=timeout` changes, our transform will no longer work.
We may still need a different message where the above error and errorType mean something else..

**Comment by gabor** [comment] 2022-05-17 10:00
@joey-grafana 
> We could check on [this line](https://github.com/grafana/grafana/blob/main/public/app/features/explore/LogsVolumePanel.tsx#L25)

that would definitively work, the problem is that is a generic place, not loki specific, so for example what if elastic generates that error-message in a different situation? 😿 

i'm afraid we might have to do this somewhere inside the loki-datasource, maybe get the result and modify it at https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/datasource.ts#L157-L161 ? not sure

**Comment by kavirajk** [comment] 2022-05-17 14:58
@gabor can I have some information on how you folks extract error-type?

I'm asking because, this error can either be returned by Loki itself or gateway before Loki (on Grafana cloud). is it taken from the response code?

**Comment by gabor** [comment] 2022-05-17 15:15
@kavirajk we do a best effort approach getting info from the loki error message. this test describes how things will be in grafana9: https://raintank-corp.slack.com/archives/C034P96GCS1/p1652779848359859 

(this one might be slightly different from how it is right now, but should not be too far from it)

**Comment by 09jvilla** [comment] 2022-05-17 18:51
@gabor are you sure that's what you wanted to link to? That's a thread about 'show context' so I couldn't really make the connection to error messages.

**Comment by kavirajk** [comment] 2022-05-18 04:05
@gabor that thread you shared doesn't look like the right one? (I was asking for logic where Grafana get error info from Loki error response).

I did some investigation, looks like we got two cases here.
1. on Grafana cloud where Loki is behind the proxy gateway. In that case, you get a response
```
"errorType": "timeout",
"error": "context deadline exceeded"
```
all the time.

2. If Grafana talks directly to Loki, then in case of query timeout, it just returns following error
``
Request timed out, decrease the duration of the request or add more label matchers (prefer exact match over regex match) to reduce the amount of data processed
``

Only common thing I could find in both cases is the response status code - `StatusGatewayTimeout - 504`.

Curious to know how error handling works in Grafana currently for Loki. Does both of those cases already covered?

**Comment by gabor** [comment] 2022-05-18 06:55
> @gabor are you sure that's what you wanted to link to? That's a thread about 'show context' so I couldn't really make the connection to error messages.

sorry, you are correct, wrong link. i updated it with the correct link.

**Comment by gabor** [comment] 2022-05-18 07:05
@kavirajk i don't think we differentiate by http-status-code currently. i think we just try to extract text from the error-message.

@09jvilla 
we could in theory add an additional check for http-status-code-504, and if it is hit, do the "Request timed out. Please try again with a shorter time range.' " message, but then we loose the helper text that loki already is returning.

couldn't we solve this on Loki's side? :
1. Loki already returns a help-text when the request times out. it could be updated to incorporate the shorter time range suggestion.
2. for log-volume-queries grafana sends a special http-header so that Loki can see that this is a log-volume-query (this is something that loki squad requested). so Loki could make sure to just cancel the request if it is running for too long, so we would never hit the "grafana cloud" timeout. (i don't think we should rely on the grafana-cloud-timeout in application logic. i think we should aim to not hit it.)

what do you think?

**Comment by kavirajk** [comment] 2022-05-18 08:33
>couldn't we solve this on Loki's side? :

The only problem is, in the case of Grafana cloud, this gateway is not just used by Loki, but shared by others as well (mimir and tempo). that's why the error is so generic (`errorType: timeout and error: context deadline exceeded`).

Also we should be careful, when you say "Loki side".
Currently, Loki, doesn't aware of any "special timeout" for Log volume queries. To Loki, log volume query is just a normal metric query with default timeout of 1m.

On the cloud, all the custom timeout is being handled on the "gateway" side, which look for this special header and set timeout to 10s.

Generic solution I could think of is, show this user friendly error when either
1. The response for Log Volume Histogram query returns `StatusGatewayTimeout - 504` (doesn't matter if it's behind proxy or not) or
2. Grafana's internal data proxy times out. (because Loki OSS may have query timeout greater than the grafana proxy timeout)

wdyt?

**Comment by gabor** [comment] 2022-05-18 10:58
@kavirajk thanks for the explanation... an idea:
on the cloud, in the gateway-config, there somewhere is a customization, an "IF" in the config, so that when the special header comes, set timeout to 10s. 
could we just tell the gateway-config, that in this case return this specific error-message?

**Comment by kavirajk** [comment] 2022-05-18 12:22
>could we just tell the gateway-config, that in this case return this specific error-message?

We can. I'm afraid if that's a acceptable special case in the proxy shared by all the backend databases. My other concern is what if someone else from the community have completely different proxy before Loki that returns totally different error string?.

The more I think about it, I believe we should make this decision only based on status code StatusGatewayTimeout. That would be the right assumption rather than depending on "what error string" loki or any proxy returns in the middle.

**Comment by gabor** [comment] 2022-05-18 12:34
hmm. to summarize, your recommendation is that we simply look at the http-status-code of the response of the log-volume-query. if it's http504, we show the special message. is this correct?

**Comment by kavirajk** [comment] 2022-05-18 12:44
> hmm. to summarize, your recommendation is that we simply look at the http-status-code of the response of the log-volume-query. if it's http504, we show the special message. is this correct?

Yes :) This gives us flexibility and independent from what proxy(or without proxy) is being run in front of Loki. Just assuming they return correct status code `StatusGatewayTimeout`

**Comment by 09jvilla** [comment] 2022-06-10 12:50
Hmm... @gabor did this behavior already change in Grafana 9? When the histogram times out in Grafana 9, I see this:

![Screen Shot 2022-06-10 at 7 37 48 AM](https://user-images.githubusercontent.com/9610816/173065709-45dfcec3-d0de-4e7b-ab76-50a325e8bc68.png)

I also note that the histogram doesn't show up as timed out in 10 seconds, but waits to display until the underlying query itself completes (assuming the query takes >10 seconds)

If neither the histogram nor the query itself complete, I now see this:
![Screen Shot 2022-06-10 at 7 40 20 AM](https://user-images.githubusercontent.com/9610816/173066411-d6f1cc7c-2490-4c4f-aabf-698e9362a120.png)

If the query completes before the histogram, I first see the loading page:
![Screen Shot 2022-06-10 at 7 38 16 AM](https://user-images.githubusercontent.com/9610816/173066635-5857ba93-5d3f-4b55-98cb-76933ec87d2b.png)

Then I see 'no log volume data'
![Screen Shot 2022-06-10 at 7 37 48 AM](https://user-images.githubusercontent.com/9610816/173066681-8fdeac21-5e8f-4bb7-915a-f5389b21d5c3.png)

If you can verify that this is the behavior expected in Grafana 9, then I think I need to close this ticket and reopen a new one. 

I think the fact that we now don't show the histogram as failed until the query returns (whether it times out or whether it actually completes) is an improvement. The user now won't think that a failed histogram means a failed query. 

The overall message for a query timeout is still not very clear (we're back to 'context deadline exceeded'), but we can fix that by replaced it with this: 
"Request timed out. Decrease the time span the query covers or add more filtering (prefer an exact match over a regex match) to reduce the quantity of log lines processed."
[I can open this part as a separate ticket].

**Comment by 09jvilla** [comment] 2022-08-25 15:02
Aug 25 discussion: 
@slim-bean mentioned that he thinks Loki should be able to return a cleaner error message for this situation.

**Comment by gabor** [comment] 2023-04-14 10:52
this should be fixed by https://github.com/grafana/grafana/pull/65434 . if it's not correct, feel free to reopen the issue. thanks!

**Closed by gabor** 2023-04-14 10:52 UTC
Labels: datasource/Loki

**Comment by 09jvilla** [comment] 2023-04-14 21:14
Awesome - excited to see this fixed!
