### ISSUE TITLE
UI bug while using Microsoft SQL Server datasource plugin with environment variables (SELECT key __text, value __value FROM [table_name])

### ISSUE THREAD

**Issue by kcshettar** [grafana/grafana#26212] opened 2020-07-09 17:30 UTC
**What happened**: UI bug

_NOTE: images attached below (image1, image2, image3)_

## Issue
- I have two drop down options (Segment, Environment) which are being shown properly (image1). 
- When I choose multiple options (image1), the value of the key is displayed (image2) whereas the actual keys should be shown. 
- As soon as I perform browser refresh (upon selecting multiple keys), the actual keys are being displayed (image3).
- This behavior is not expected.

**What you expected to happen**:
- only the keys should be shown upon selecting multiple values from dropdown (image3)

**How to reproduce it (as minimally and precisely as possible)**:
- **Using the below feature mentioned in Grafana document: 
[Grafana Microsoft SQL datasource plugin](https://grafana.com/docs/grafana/latest/features/datasources/mssql/**)
__Another option is a query that can create a key/value variable. The query should return two columns that are named `__text` and `__value`. The `__text` column value should be unique (if it is not unique then the first value is used). The options in the dropdown will have a text and value that allow you to have a friendly name as text and an id as the value. An example query with hostname as the text and id as the value:_
```
SELECT key __text, value __value FROM [table_name]
```

**Environment**:
- Grafana version: Grafana Enterprise v7.0.3 (00ee734baf)
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows (Windows Server 2016 Datacenter), Standard E4s v3 (4 vcpus, 32 GiB memory)
- User OS & Browser: macOS Mojave 10.14.6, Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Grafana plugins: Microsoft SQL Server

## Reference image
![image1](https://user-images.githubusercontent.com/29801964/87065431-02f99400-c1df-11ea-90d7-0b9776597d55.JPG)
![image2](https://user-images.githubusercontent.com/29801964/87065454-09880b80-c1df-11ea-8ab5-6d5de0bccd1a.JPG)
![image3](https://user-images.githubusercontent.com/29801964/87065469-0d1b9280-c1df-11ea-90b4-f4a17cae1f68.JPG)

**Comment by torkelo** [comment] 2020-08-20 06:43
duplicate of https://github.com/grafana/grafana/issues/25711  fixed in master

**Comment by torkelo** [comment] 2020-08-20 06:43
Fixed by https://github.com/grafana/grafana/pull/27002

**Closed by torkelo** 2020-08-20 06:43 UTC
Labels: area/dashboard/templating, type/bug
