### ISSUE TITLE
[Feature Request] Allow Graphing without Time Series Data

### ISSUE THREAD

**Issue by ssnkhan** [grafana/grafana#10342] opened 2017-12-25 19:21 UTC
I am wanting to use Grafana to plot data directly from Postgres. However, many of my queries do not include time data. In many respects, I am not looking to monitor servers or other time sensitive data, but rather use Grafana to create graphs from pre-existing SQL queries I have written.

I have searched and it would appear that non-time series data in graph panel is not supported right now, however, I really think this is something which would be worthwhile adding:

https://community.grafana.com/t/use-graph-with-mysql-and-non-time-metrics/3004

- What Grafana version are you using?
Grafana 4.6 on OSX, installed via Home-brew

- What datasource are you using?
Postgres

- What OS are you running grafana on?
macOS

- What did you do?
Use Grafana to run an SQL query, and plot it in a graph

- What was the expected result?
Expected a simple bar chart

- What happened instead?
Grafana does not plot non-time series data

Really grateful for you consideration!

**Comment by torkelo** [comment] 2017-12-26 12:33
duplicate of https://github.com/grafana/grafana/issues/7158

**Closed by torkelo** 2017-12-26 12:33 UTC
