### ISSUE TITLE
Dashboards: Dashboard data source not available in mixed data source.

### ISSUE THREAD

**Issue by lumattr** [grafana/grafana#78650] opened 2023-11-24 16:24 UTC
### What happened?

I am unable to select the dashboard from the list of data sources when using a mixed dource type.

### What did you expect to happen?

Shouldn't it be an option?

### Did this work before?

Not sure

### How do we reproduce it?

1. Create a dashboard
2. Add a panel
3. Change query data source to be "Mixed"
4. Select data source for query "A" and search for dashboard

### Environment (with versions)?

Grafana: 10
OS: Windows
Browser: Firefox

### Grafana platform?

Kubernetes

**Comment by lumattr** [comment] 2023-11-24 16:28
For context i am trying to load some shared data that can be used accross multiple panels. In this case a list of account ids and names. At the moment i have 2 queries in a mixed data source, from 2 different databases, one gets the data and another gets the accounts. I'm then using a trasform function to join the data to show the account names against some stats in a table. I have to add the accounts query to each panel at the moment, which is affecting the load times. I would like to be able to define the data query and reuse the results across multiple panels.

**Comment by Sesshoumaru-sama** [comment] 2023-11-25 17:28
I want to do the same, switch to "Mixed" as datasource and then have a query from Influx and a second input which is already provided by a different panel in the dashboard. But I get the impression what "Mixed" really many "Mixed External Source" as in Influx or Postgres -- would be cool if the dashboards would also be available though.

**Comment by vaduga** [comment] 2023-11-28 11:09
https://github.com/grafana/grafana/issues/63866

**Comment by usmangt** [comment] 2023-12-19 10:49
Hi,

Thanks for opening this issue.

Based on your steps of reproduction, I was not able to reproduce it on my test machine using version Grafana v10.3.0-63588 (13d67be0a9)

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by JoaoSilvaGrafana** [comment] 2023-12-20 12:29
As this is the same issue as the one linked (https://github.com/grafana/grafana/issues/63866), I will close it since it is already on the Dashboard's team backlog. I would recommend commenting on that issue or upvoting it to increase its visibility with the team.

**Closed by JoaoSilvaGrafana** 2023-12-20 12:29 UTC
Labels: area/datasource, area/datasource/frontend, triage/needs-confirmation
