### ISSUE TITLE
inspect->data of a table panel shows only one row

### ISSUE THREAD

**Issue by hila3000** [grafana/grafana#27417] opened 2020-09-07 08:58 UTC
**What happened**:
After upgrading to Grafana v7.1.3, when trying to inspect->data of a table panel, it only shows one row.

Screenshot here:
https://ibb.co/cwBNbMr

**What you expected to happen**:
I expect to see all rows existing in the table.

**How to reproduce it (as minimally and precisely as possible)**:
create a table panel and try to inspect->data it.

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: Prometheus 2.12
- OS Grafana is installed on: K8s Cluster, using the image grafana/grafana:7.1.3
- User OS & Browser: MacOS Cataline 10.15.6, Chrome 85.0.4183.83. 
- Grafana plugins: grafana-piechart-panel

Thanks,
Hila

**Comment by torkelo** [comment] 2020-09-07 10:50
duplicate of https://github.com/grafana/grafana/issues/26460 

Please add your query and the raw response and panel json to the issue as we have been unable to replicate the issue

**Closed by torkelo** 2020-09-07 10:50 UTC

**Comment by hila3000** [comment] 2020-09-07 10:54
Will do, thanks
