### ISSUE TITLE
Logs UI: remove "+" button from extracted labels

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#32961] opened 2021-04-13 19:40 UTC
**What happened**:

In Logs view, when using a parser expression, the UI allows you to add an extracted label to the log stream selector... but extracted labels cannot be used in the log stream selector.

**What you expected to happen**:

Extracted labels should not have the "+" button.

**How to reproduce it (as minimally and precisely as possible)**:
1. Make a basic log stream selector: e.g., `{app="grafana",org="ericgce"}`
2. Add the appropriate log parser: e.g., `{app="grafana",org="ericgce"} | logfmt`
3. Open the expended view of one of the log lines (see below screenshot)
4. Pick one of the extracted labels, and click the "+" symbol next to that label (e.g., "Status" label as in below screenshot)
5. See that this label is added to the log stream selector like this: `{app="grafana",org="ericgce",status="Valid"} | logfmt`
6. But no log results are returned, because we can't use an extracted label in the log stream selector

![image](https://user-images.githubusercontent.com/10763196/114609825-3507bd00-9c6d-11eb-8a53-200bf42132d2.png)

**Anything else we need to know?**:

Reported by an on-prem customer, and reproduced in Grafana Cloud

**Screencap (movie)**

![25348-logs-ui-bug](https://user-images.githubusercontent.com/10763196/114610667-2ec61080-9c6e-11eb-9837-cb3bdd479f3a.gif)

**Environment**:
- Grafana version: 7.5.3

**Comment by davkal** [comment] 2021-04-14 08:34
Such a nicely documented issue 🌷 , but I have to mark it as a duplicate of #30856 
that issue also points to a design doc about upcoming work around this: https://docs.google.com/document/d/1DP_piybk4WBs_NWwWuMS4FRQSUK0eeAUY3pT0td7ueQ/edit

**Closed by davkal** 2021-04-14 08:34 UTC
Labels: area/explore, area/frontend, type/bug

**Comment by sergeykranga** [comment] 2021-04-14 09:55
i think in case of json parser, it would be useful instead to leave the "+" button and make it so that the selected label appears as a label filter after the parser. this behavior would allow to filter by extracted labels just by clicking on the "+" button
