### ISSUE TITLE
Grafana Alerting Labels not working for kubernetes ${pod}, allthough ${container} label is working

### ISSUE THREAD

**Issue by DibyoGit** [grafana/grafana#46322] opened 2022-03-08 12:39 UTC
**What happened**:
We are trying to create Alert emails for CPU Usage and Memory usage Grafana dashboards.
We target to print the container name, pod name , node name and the namespace name in our email template.

We have used notification template like this:
**Alert Description: CPU Usage of POD - ${pod} having container ${container} in namespace ${namespace} is greater than the threshold 0.1**

Also the ${container} works only for 1 query(dashboard panel) and not for others. Please clarify how the ${Label} works.
Please note: We have thoroughly gone through the relevant official documentation 

https://grafana.com/docs/grafana/latest/alerting/old-alerting/add-notification-template/

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/64616330/157239769-5d84605f-7ffe-4247-a50e-2cc40b6db210.png)

We want the highlighted values to be populated as well just like the container is getting printed in our alert emails
![Uploading grafana-alert-isse.JPG…]()

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Dev
- Grafana version: 8.4.3 OSS
- Data source type & version: Prometheus (via helm chart) 0.5.1
- OS Grafana is installed on: Kubernetes cluster with RHEL instances
- User OS & Browser: Chrome
- Grafana plugins: None
- Others: N/A

**Comment by ahu0605** [comment] 2022-03-09 10:31
I have the same problem ,are you resolve?

**Comment by alexweav** [comment] 2022-05-06 16:26
Hello! This seems to be related to legacy alerting, which will be deprecated soon. Have you gotten the chance to try unified alerting? Does this issue still reproduce there?

In unified alerting, the template would contain something like `{{ .Labels.pod }}` or `{{ .Labels.namespace }}`.

**Comment by msrpub** [comment] 2022-05-24 18:34
Noticed same behaviour with InfluxDB Datasource alerts when using multiple tags. Only the last tag is replaced.

**Comment by sasi-uvr** [comment] 2022-07-17 21:16
$ is valuating only the last variable. Use [[]] (for e.g., [[tag_pod]] instead $tag_pod) instead of $.

**Comment by armandgrillet** [comment] 2022-08-19 09:33
In previous Grafana versions, we would return the variable names when templating was failing in process. We've changed that in newer versions of Grafana to return `No value` instead. Please try a newer version of Grafana (>= 9.0).

**Comment by grobinson-grafana** [comment] 2022-09-18 14:06
I'm going to close this issue but please feel free to re-open it should the issue still occur on Grafana 9.1.

**Closed by grobinson-grafana** 2022-09-18 14:06 UTC
Labels: type/bug, needs more info, area/alerting
