### ISSUE TITLE
Panel edit: Flux query editor stuck at "Loading..."

### ISSUE THREAD

**Issue by forouher** [grafana/grafana#42803] opened 2021-12-07 05:44 UTC
Hi,

when editing panels on an existing dashboard, sometimes the query editor doesn't load. It is stuck displaying "Loading..." forever:

![Bildschirmfoto vom 2021-12-07 06-22-48](https://user-images.githubusercontent.com/676900/144971741-ec24989b-4db5-4967-a050-0c91ede945a1.png)

The bug comes and goes randomly. On some dashboards, it rarely happens, on others, more than 50% of times I try to edit a panel.

After retrying a couple of times (open the dashboard in new tabs), it works again (for a while):

![Bildschirmfoto vom 2021-12-07 06-30-31](https://user-images.githubusercontent.com/676900/144972133-f7d388a7-ef57-489e-b35f-e0888c936422.png)

I've attached the dashboard as exported json:

[dashboard.zip](https://github.com/grafana/grafana/files/7665783/dashboard.zip)

Grafana version: v8.2.3 (fb85ed6912) on Linux
Data Source: influxdb 2.0 (Flux)
Browser: Chrome 96.0.4664.45 / Ubuntu 20.04
Panel type: "Graph (old)" and Table (probably others too)
Grafana plugins: A handful of custom panels, but none active on the problematic dashboard. No custom data sources.

**Comment by ashharrison90** [comment] 2021-12-07 10:19
hi @forouher 👋 

do you get any errors in the developer console when this happens?

thanks!

**Comment by ashharrison90** [comment] 2021-12-07 10:57
perfect, thanks. i'll route this to the correct team and they'll get back to you if they need any more information. 🙌

**Comment by elandivar** [comment] 2022-03-16 09:22
Same problem here :-( 

Using Grafana version 8.4.3 and Chrome version 98.0.4758.80 (Build oficial) (x86_64)

**Comment by elandivar** [comment] 2022-03-16 09:24
This is my console output:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/4536961/158558323-f0b9ff44-34e2-485e-bd45-4e8fff639f39.png">

**Comment by elandivar** [comment] 2022-03-16 21:57
The problem seems to be fixed in grafana 8.4.4

**Comment by mdnfiras** [comment] 2022-03-31 13:55
I was getting the same error as @elandivar : 
![image](https://user-images.githubusercontent.com/29513074/161071995-8fe5a941-ede9-403c-9d99-b42632188cfc.png)

The query editor was stuck at `loading...` both when creating panels and alerts.
I had to update to 8.4.4 AND clear the browser cache (or try in incognito)

**Comment by MarcoPignati** [comment] 2022-03-31 15:42
I am getting a very similar (if not the same) error as @mdnfiras. Cleaning cache did not help. This is a new dashboard with an empty panel.
![image](https://user-images.githubusercontent.com/35630931/161095220-37671d45-02cd-47af-a01a-e5e1ba1b6c4b.png)

**Comment by weng5e** [comment] 2022-08-06 07:49
I am also seeing the same issue in Prometheus query editor on Grafana 9.0.1.
![image](https://user-images.githubusercontent.com/22308724/183239818-0267919b-ce74-494a-b0f3-5cd3a73e8f03.png)

But the explore UI is more likely to succeed to load the query.
![image](https://user-images.githubusercontent.com/22308724/183239891-ac07fccd-72b6-4140-a535-d113095551de.png)

It might be related to Monaco editor loading? Is it possible that multiple versions of the Monaco editor JS files are being loaded into the page?

**Comment by jalevin** [comment] 2022-08-12 00:30
Would you be able to share your grafana.ini/config.ini?

**Comment by weng5e** [comment] 2022-08-12 00:56
Attached grafana.ini:

https://wuwenggrafanapublic.blob.core.windows.net/public/grafana.ini

**Comment by weng5e** [comment] 2022-08-17 06:05
With help from @itsmylife, the root cause is that there is another plugin loading Monaco editor. Grafana core (Prometheus plugin) is also trying to load the Monaco editor. If those two Monaco editor versions are different, it may run into this loading issue.

When our custom plugin switched to use the [Grafana built in Monaco editor ](https://grafana.com/docs/grafana/latest/packages_api/ui/codeeditor/), then the issue is fixed.

Reference:
https://github.com/grafana/grafana/pull/39570

**Comment by itsmylife** [comment] 2022-08-17 10:04
@elandivar @mdnfiras @MarcoPignati Could you please provide a `.har` file? I want to double-check if the problems you are having are the same.

**Comment by gtk-grafana** [comment] 2023-08-16 12:27
@itsmylife This was on the old board and got lost, can we close this out?

**Comment by itsmylife** [comment] 2023-08-24 14:49
@gtk-grafana I think we can close this out. That should have been resolved already. 
If the same thing happens again we will track it in a new issue.

**Closed by itsmylife** 2023-08-24 14:49 UTC
Labels: datasource/InfluxDB, area/query-editor
