### ISSUE TITLE
Explore: Syntax error when selecting label with mouse

### ISSUE THREAD

**Issue by steven-sheehy** [grafana/grafana#16213] opened 2019-03-25 17:46 UTC
**What happened**:
Testing fix to #16055 and it works well with the keyboard. I uncovered an additional issue when selecting labels/values with the mouse. The popup that appears when you begin typing labels or values does not work when using mouse selection in Firefox. This works correctly in Chrome. The static `Log Labels` dropdown menu also works correctly with the mouse.

**What you expected to happen**:
The label/value should be added to the query.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open Explore -> Loki
2. Type `{ap}`
3. In labels pop up, select label `app` with the mouse

Result: Label not added to query and `syntax error` is displayed

With values:
1. Open Explore -> Loki
2. Type `{app="}`
3. In values pop up, select any value with the mouse

Result: Value not added to query and `syntax error` is displayed

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version: Loki @ master
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS Firefox
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment] 2019-03-26 09:05
Try latest nightly or upcoming v6.1 beta 

Fixed in https://github.com/grafana/grafana/pull/16192

**Comment by steven-sheehy** [comment] 2019-03-26 14:19
@torkelo I am on latest nightly. I opened the previous bug about autocomplete not working in firefox, this is a follow up testing the fix for that. Please reopen.

**Comment by torkelo** [comment] 2019-03-26 14:45
Sorry, missed that part.

**Comment by steven-sheehy** [comment] 2019-03-28 15:14
I noticed this in the console. It looks like grafana is sending the incomplete query to Loki after I click but before the query is updated:

![Screen Shot 2019-03-28 at 10 03 22](https://user-images.githubusercontent.com/17552371/55169094-2ad7fc00-5142-11e9-905d-dd21967b16c8.png)

**Comment by steven-sheehy** [comment] 2019-03-29 04:11
I've also noticed this happen in Chrome too, so removing Firefox from description. And I've seen it work in Firefox. It just seems to work less often in Firefox than Chrome. Probably some race condition with the onblur of the query editor and the popup onclick.

**Comment by hugohaggmark** [comment] 2019-04-04 07:49
Both `handleBlur` https://github.com/grafana/grafana/blob/d35e883eac86f0c4dd26e22d862f89e3cafc16e4/public/app/features/explore/QueryField.tsx#L391 and
`onClickMenu` https://github.com/grafana/grafana/blob/d35e883eac86f0c4dd26e22d862f89e3cafc16e4/public/app/features/explore/QueryField.tsx#L409 fire run queries so there is a race condition.

There's an inconsistency her in the UX. Choosing an item with keyboard does not trigger run queries but clicking with the mouse does. Maybe both should trigger run queries (#14982) or both should just add the chosen suggestion. 

I can make it so clicking in the menu does not run queries and cause this race condition. WDYT?

**Comment by steven-sheehy** [comment] 2019-04-04 14:36
If you're asking me, I think clicking in the menu should behave the same way as the enter key. That is, they both should just add suggestions.

**Comment by davkal** [comment] 2019-04-08 16:32
My UX take: Running queries in Explore is the prime activity and should be deliberate (i.e., via clicking actions). Plus, some queries can be expensive (i.e., take a minute or longer to run). I would not like those being triggered accidentally.

**Comment by hugohaggmark** [comment] 2019-04-12 05:21
I gave this a try, but when I click an item in suggestion list it doesn't add the `=`sign because line below doesn't work the same after menu click compared to after keyboard arrow up/down and enter in suggestion list
https://github.com/grafana/grafana/blob/b9cc476eb7aa57ed6714654e6036c73c9d105919/public/app/features/explore/utils/dom.ts#L32

Someone with better understanding of how slate Editor works would be better fitted to solve this.
Here is how far I came:

I replaced the following:
https://github.com/grafana/grafana/blob/b9cc476eb7aa57ed6714654e6036c73c9d105919/public/app/features/explore/QueryField.tsx#L395-L415

with:
```ts
handleBlur = (event: FocusEvent, change: Change) => {
    // If we dont wait here, menu clicks wont work because the menu
    // will be gone.
    this.resetTimer = setTimeout(this.resetTypeahead, 100);
};

onClickMenu = (item: CompletionItem) => {
    // Manually triggering change
    const change = this.applyTypeahead(this.state.value.change(), item);
    this.onChange(change, false);
};
```

After the change above that gets rid of the race conditions and the refresh on click, the `onWillApplySuggestion`will not add the `=`sign. So then I introduce a new hacky `boolean` to  `onWillApplySuggestion` and ignore the result from getNextCharacter. This works but I found it to be an ugly solution and this could probably be much better solved by someone with Slate skills.
```ts 
onWillApplySuggestion?: (suggestion: string, state: QueryFieldState, isAfterMenuClick?: boolean) => string; 

...

const nextChar = getNextCharacter();
if (!nextChar || nextChar === '}' || nextChar === ',' || isAfterMenuClick) {
  suggestion += '=';
}
```

**Comment by ivanahuckova** [comment] 2019-09-24 09:27
After the slate upgrade, I wasn't able to reproduce this bug, therefore I think that this issue has been fixed. However, I have experienced different bug/unusual behaviour: 
1. Open Explore -> Loki
2. Type {j}
3. `job` label pops up
4. Select label `job` with the mouse
5. Label values (e.g. `varlogs`) aren't displayed until `shift`, `option`, or any key, that doesn't add anything to query is pressed. If `"` or `v` is typed, no label values are displayed.

@kaydelaney Do you have any idea why this could be?

**Comment by kaydelaney** [comment] 2019-09-24 09:30
I can look into it

**Comment by davkal** [comment] 2019-09-24 09:41
You should have to press `=` or a different comparison operator before label results are being suggested.

**Comment by kaydelaney** [comment] 2019-09-24 10:12
Fix: https://github.com/grafana/grafana/pull/19359

**Closed** 2019-10-14 09:05 UTC
Labels: area/explore, type/bug
