### ISSUE TITLE
Changes to panel using MQTT source gives error message

### ISSUE THREAD

**Issue by jon-p-taylor** [grafana/grafana#61120] opened 2023-01-07 19:32 UTC
In line with issue #60570 which was closed without full investigation, if I create a panel using an MQTT data source and then change the panel I get an error message saying "Subscription to the channel 1/ds/LVo8dvh4z/1s/picow/temperature already exists". The MQTT source is a HiveMQ broker which is being connected to using tls. The panel works perfectly until a change is made to it, and then the error message appears.

The message can also be reproduced by deleting the panel and creating a new one with the same source.

**Comment by sbrooke** [comment] 2023-01-07 19:58
Adding my name to the list of people having this problem. I'm using Mosquitto for the broker but get the same kind of error message as soon as I make a change to the panel.

**Comment by sbrooke** [comment] 2023-01-07 20:26
Further testing and this seems to break when I change the viewing period of the panel or add a second sub. However, I'm also having a problem with the data disappearing from the panel after about 10 seconds. I can send further messages and they'll live for about 10 seconds before the panel refreshes to being empty.

**Comment by usmangt** [comment] 2023-01-09 14:49
Hi @jon-p-taylor and @sbrooke ,

First of all thanks for linking the original issue-id reference.

I have reopened it (will close this one) and already moved it to our Engineers team as the issue is related somewhere with the streaming of data.

You will get updates there.

**Closed** 2023-01-10 11:51 UTC
