### ISSUE TITLE
Explore: show context not showing top values

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#21440] opened 2020-01-10 14:24 UTC
**What happened**:

I was trying to find the cause of a panic and when using the `show context` on the line found, it didn't show anything at the top. However it seems that the data is being returned correctly.

![image](https://user-images.githubusercontent.com/1053421/72159655-d1685300-338a-11ea-808b-e01e7ee949c5.png)

**What you expected to happen**:

Show me the top and bottom part of the show context 

**How to reproduce it (as minimally and precisely as possible)**:

Use a filter query, then use show context.

**Environment**:
- Grafana version: Grafana v6.6.0-pre (0bf9e9bc28)
- Data source type & version: Loki
- User OS & Browser: Chrome

/cc @davkal

**Comment by aocenas** [comment] 2020-01-10 15:55
Seems the issue is somewhere around [here](https://github.com/grafana/grafana/blob/9b7748ec133cb2ce4b092e523cb6d70a7b89de83/packages/grafana-ui/src/components/Logs/LogRowContextProvider.tsx#L56). We do some filtering there but that should only filter the row around which we want to see the context, could be something is off and we filter all the rows in some cases.

**Comment by Estrax** [comment] 2020-01-20 01:08
Looks like it works with the current master (d2b08c8368d53b96225749a339f0f04a8d969f49), but I'll take a look at filtering once again to check if it produces valid results.

**Comment by Estrax** [comment] 2020-01-22 14:27
Seems to be working properly with the current master. Closing the issue now. Please reopen if it still doesn't work properly.

**Comment by cyriltovena** [comment] 2020-01-22 14:53
for a0b04559e4 it doesn't work.

**Comment by cyriltovena** [comment] 2020-01-22 14:54
Which seems to be after the commit you're talking about.

**Closed** 2020-01-26 22:13 UTC
Labels: area/explore, datasource/Loki, type/bug
