### ISSUE TITLE
Grafana 3.0.4 fails to display big numbers from InfluxDB

### ISSUE THREAD

**Issue by cristicalin** [grafana/grafana#5550] opened 2016-07-11 06:59 UTC
- **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
  => 3.0.4-1464167696
- What datasource are you using?
  => InfluxDB 0.13.0
- What OS are you running grafana on?
  => Ubuntu 14.04
- What did you do?
  => We monitor a medium size CEPH cluster and we track 3 metrics in InfluxDB: total_avail, total_used and total_space. "total_space" is the total capacity of the cluster in bytes (current value: 145608856633344). Initially we created a single panel with the 3 metrics split in a "group by" and all 3 metrics are displayed correctly.
  We tried to graph this metric on a separate panel by itself.
- What was the expected result?
  => We expected to be able to graph the "total_space" metric similat to the "total_used" and "total_avail" metric.
- What happened instead?
  => Grafana fails to parse the large number by itself and returns only NaN.
  ![grafana-1](https://cloud.githubusercontent.com/assets/6627509/16722045/a4c90282-474c-11e6-8b51-c2367fcaf3b4.png)
  ![grafana-2](https://cloud.githubusercontent.com/assets/6627509/16722131/4e8c0f44-474d-11e6-97fa-4b70f9f9aa44.png)
  ![grafana-3](https://cloud.githubusercontent.com/assets/6627509/16722167/8546bfe8-474d-11e6-88c2-5a74abe5cad2.png)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by cristicalin** [comment] 2016-07-11 07:01
HAR files from chrome.
https://gist.github.com/cristicalin/4c988f6768ef15dd5ea75050130a8cd9

**Comment by torkelo** [comment] 2016-07-11 07:52
dont know what could be the cause, tested with the data in your gist file for the total_space query but it works for me:
![image](https://cloud.githubusercontent.com/assets/10999/16723431/2897c9cc-474d-11e6-8812-65da3f85f23c.png)

So not sure if is something in the influxdb response logic code or what it could be really.

**Comment by cristicalin** [comment] 2016-07-11 09:51
Seems to be limited to the influxdb logic as I have other datasources coming from Elasticsearch and Grafana with larger values than this and those are working properly.

I can try to take a snapshot of my data and share it with you for debugging.

**Comment by torkelo** [comment] 2017-07-25 19:23
closing this as there has been no other reports like this. please let me know if you still have issues like this

**Closed by torkelo** 2017-07-25 19:23 UTC
Labels: datasource: InfluxDB
