### ISSUE TITLE
Prometheus: Still problems editing multi-line queries

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#18607] opened 2019-08-18 09:51 UTC
**What happened**:

Multi-line editing regressed and is still broken after earlier fixes:

![image](https://user-images.githubusercontent.com/345210/63222894-c2032600-c1ad-11e9-9901-280437d80352.png)

At this position I cannot press Enter or Shift-Enter to insert a newline. Instead the completion code keeps inserting weird stuff, like "instance".

**What you expected to happen**:

Enter or Shift-Enter for a newline

PR https://github.com/grafana/grafana/pull/18362 promised to fix this.

**How to reproduce it (as minimally and precisely as possible)**:

```
sum by (container) (
  rate(
    eagle_pod_container_resource_usage_cpu_cores{
      namespace = "$namespace",
      container != "metrics-exporter",instance   
    }[$interval]
  )
  * on (pod) group_left(label_project, label_environment) kube_pod_labels
)
```

**Anything else we need to know?**:

Copying the example on Linux in Chromium with Ctrl-C also loses newlines.

The auto-insertion of closing braces in far away spots is also annoying af.

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: Prometheus 2.11.x 
- User OS & Browser: Chromium 77

**Comment by towolf** [comment] 2019-08-18 10:12
This popup with `instance` and `job` in it pop up in all kinds of really annoying places, preventing cursor movement.

For example, when deleting space manually at the start of the line, the popup prevents cursor movement up and down.

![image](https://user-images.githubusercontent.com/345210/63223144-80747a00-c1b1-11e9-8bc9-418172c1783b.png)

**Comment by towolf** [comment] 2019-08-18 10:13
I think I would have reverted the merging of the Explore editor seeing how many problems there are.

**Comment by kaydelaney** [comment] 2019-08-21 08:54
To clarify, only `shift+enter` is supposed to insert a new line, `enter` on its own either selects a suggestion from the suggestions list if one is visible, or runs the query, but a new line won't be inserted unless shift is held.

**Comment by towolf** [comment] 2019-08-21 09:07
@kaydelaney die you try it? 

Shift-Enter does not work in these locations.

**Comment by towolf** [comment] 2019-08-21 09:08
And Enter "to run the query" does not make sense in the graph editor.

**Comment by kaydelaney** [comment] 2019-08-21 09:10
Yes, I tried it and I was unable to reproduce the issue on v6.3.3, v6.3.x or master

**Comment by towolf** [comment] 2019-08-21 09:20
@kaydelaney can you try adding this variable to make the pop-up more likely?

![image](https://user-images.githubusercontent.com/345210/63419695-882c5c80-c405-11e9-9554-6532b0ef15f5.png)

And then please paste this into a prometheus editor and place your cursor after the comma

```
sum by (container) (
  rate(
    eagle_pod_container_resource_usage_cpu_cores{
      namespace = "$namespace",
      container != "metrics-exporter",🖱️
    }[$interval]
  )
  * on (pod) group_left(label_project, label_environment) kube_pod_labels
)
```

**Comment by towolf** [comment] 2019-08-21 09:21
Maybe you need to press backspace and , or space and backspace to trigger it.

But in my experience this Shift-Enter blocking pop-up is coming up "all the time".

**Comment by kaydelaney** [comment] 2019-08-21 10:07
Tried again on both firefox and chrome. The suggestion box does show up, but for me, it's ignore when i press shift+enter and a new line is inserted as expected

**Comment by torkelo** [comment] 2019-08-21 10:37
What OS are you on @towolf

**Comment by towolf** [comment] 2019-08-21 11:21
#torkelo Ubuntu 19.04, Chromium 77.

**Comment by towolf** [comment] 2019-08-21 11:29
Ok, Shift-Enter works on Windows.

But there are so many more problems.

When the pop-up is shown I cannot do Shift-Arrow anymore to select lines to delete or delete, or whatever.

**Comment by kaydelaney** [comment] 2019-08-21 11:42
@towolf I've just made a PR that addresses some of the usability issues (not all of them unfortunately). https://github.com/grafana/grafana/pull/18661
I'll see about getting Shift+Arrow for selecting implemented as well

**Comment by kaydelaney** [comment] 2019-08-23 14:19
Tested this in a fresh Ubuntu VM (18.04.3) in the latest version of Chromium and Chrome Beta, and still couldn't reproduce the issue

**Comment by aocenas** [comment] 2020-04-23 12:36
Hey @towolf seems like we were not able to reproduce this so going to close this but please reopen if you still have the issue.

**Closed by aocenas** 2020-04-23 12:36 UTC
Labels: datasource/Prometheus, type/bug
