### ISSUE TITLE
Error: [$injector:unpr] Unknown provider

### ISSUE THREAD

**Issue by dkozar** [grafana/grafana#32336] opened 2021-03-25 22:38 UTC
Hi,

I'm running _Grafana 7.4.2_ locally.

I've built a data source plugin using _grafana-starter-datasource_. I pointed Grafana to its `dist` folder.

Grafana's _defaults.ini:_
```
# Directory where grafana will automatically scan and look for plugins
plugins = C:\src\grafana-starter-datasource\dist
```

When I run `yarn watch`, everything works fine.

However, when I run `yarn build` (in order to build a plugin to install to remote Grafana server), my data source stops working:

```
FooBar Datasource plugin failed
Error: [$injector:unpr] Unknown provider: tProvider <- t http://errors.angularjs.org/1.6.9/$injector/unpr?p0=tProvider%20%3C-%20t
```

![image](https://user-images.githubusercontent.com/1078403/108372651-f1f21600-71f6-11eb-80b4-2ef3a1bf94da.png)

This seems to be because of minification.

Unminified (208 KB), result of `yarn watch` - works:

![image](https://user-images.githubusercontent.com/1078403/108373123-6fb62180-71f7-11eb-865c-1822926abd38.png)

Minified (39 KB), result of `yarn build` - doesn't work:

![image](https://user-images.githubusercontent.com/1078403/108373292-a5f3a100-71f7-11eb-8d72-a3946992ad12.png)

I noticed this happening only recently. 

My dependencies (`package.json`):

```
{
  "name": "simple-datasource",
  "version": "1.0.0",
  "description": "Grafana Data Source Plugin Template",
  "scripts": {
    "build": "grafana-toolkit plugin:build",
    "test": "grafana-toolkit plugin:test",
    "dev": "grafana-toolkit plugin:dev",
    "watch": "grafana-toolkit plugin:dev --watch",
    "sign": "grafana-toolkit plugin:sign"
  },
  "author": "Grafana Labs",
  "license": "Apache-2.0",
  "devDependencies": {
    "@grafana/data": "7.4.2",
    "@grafana/runtime": "7.4.2",
    "@grafana/toolkit": "7.4.2",
    "@grafana/ui": "7.4.2",
    "@testing-library/jest-dom": "5.4.0",
    "@testing-library/react": "^10.0.2",
    "@types/lodash": "latest",
  },
  "dependencies": {
    "grafana": "^1.0.1"
  }
  "engines": {
    "node": ">=14"
  }
}
```

Same issue in [grafana-starter-datasource](https://github.com/grafana/grafana-starter-datasource/issues/13).

**Comment by zoltanbedi** [comment] 2021-03-26 09:36
Duplicate of #21390

**Closed by zoltanbedi** 2021-03-26 09:36 UTC

**Comment by dkozar** [comment] 2021-03-26 10:09
Hi, @zoltanbedi!

Is this issue fixed, and with which Grafana version?

The related (duplicate) issue is from the year ago, whereas I'm experiencing it with one of the latest versions of Grafana.

**Comment by zoltanbedi** [comment] 2021-03-26 10:39
Sorry, duplicate was not the proper term. I wanted to point you to the issue that we had and solved this issue. I've tried this and working fine for me. Your package.json looks weird to me as it is different from the one in the starter. Could you try with that?

**Comment by dkozar** [comment] 2021-03-26 13:30
> Your package.json looks weird to me as it is different from the one in the starter. Could you try with that?

In which way weird? It's the one from https://github.com/grafana/grafana-starter-datasource/blob/master/package.json.

**Comment by zoltanbedi** [comment] 2021-03-26 13:34
Specifically the `"grafana": "^1.0.1"` dependency.

**Comment by dkozar** [comment] 2021-04-06 09:33
@zoltanbedi as for the Grafana version, the `1.0.1` seems to be the last one, at least for the package named "grafana":

If I replace it with `7.5.0`, `7.5.0-pre` or similar, I'm getting:

![image](https://user-images.githubusercontent.com/1078403/113690163-0618a680-96c3-11eb-886a-b94105e33a9c.png)

Additionally, I also tried to bump up the dev dependencies to `7.5.0`:

```
  "devDependencies": {
    "@grafana/data": "7.5.0",
    "@grafana/runtime": "7.5.0",
    "@grafana/toolkit": "7.5.0",
    "@grafana/ui": "7.5.0",
```

... however, I'm still getting the same runtime error:

```
My Datasource plugin failed
Error: [$injector:unpr] Unknown provider: tProvider <- t https://errors.angularjs.org/1.8.2/$injector/unpr?p0=tProvider%20%3C-%20t
```

**Comment by ziijiawen** [comment] 2021-09-09 02:29
遇到同样的错误，请问解决了吗 ？？

**Comment by dastein1** [comment] 2022-01-31 13:00
I'm still facing this issue with latest grafana & grafana-toolkit plugin:build. Anyone else?

**Comment by el-yurchito** [comment] 2022-04-10 10:05
I'm still facing this issue too, on grafana 8.3.4

**Comment by fightingMie** [comment] 2022-04-14 03:31
I'm still facing this issue too, on grafana 8.3.4。 +1
