### ISSUE TITLE
ngAlert using Math expression confusing error: frame cannot uniquely be identified by its labels {}

### ISSUE THREAD

**Issue by bobemoe** [grafana/grafana#45721] opened 2022-02-22 11:33 UTC
**What happened**:
Trying to create a multidimentional alert grafana wildcard using `Math` expression, getting error "invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}"

**What you expected to happen**:
Able to preview and complete alert creation, which should generate independent alerts for each of the 4 series

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/2304970/155123217-87ccc485-881d-4d2a-a324-3fa0dc941922.mov

**Anything else we need to know**:
I can't understand the error: "frame cannot uniquely be identified by its labels: has duplicate results with labels {}" is this referring to the labels show in the results test.const, test.sin etc? they are clearly unique. The array of labels it says is the problem {} is blank. Confused as to what I'm doing wrong.

**Environment**:
- Grafana version: docker: graphite/graphite:8.3.6 and 8.4.1
- Data source type & version: docker: graphiteapp/graphite-statsd:1.1.8-8
- OS Grafana is installed on: docker 20.10.10 host os Devuan Linux
- User OS & Browser: Devuan Linux, firefox
- Grafana plugins: default
- Others:

**Comment by kylebrandt** [comment] 2022-02-22 12:55
Too Explain the Error:
The error does mean that there are duplicate labels in the response. `{}` means an empty set of labels, so the error is complaining that although the series have different names, they all have empty labels.

The "classic condition", since it only ever produces one alert instance, regardless of how many series does not have the requirement that each series is uniquely identified by labels.

If you are able to do a label query in Graphite, then this error should go away.

Feature add that may help improve this with Graphite:
We could do some logic like: If graphite query, and no labels, make a "name" label of the metric. Queries your example would work, but if you try to do math with two queries such as `$A + `$B` where B has a different metric name, they won't line up so that wouldn't work -- so it it would be limiting.

**Comment by kylebrandt** [comment] 2022-02-22 13:34
Sorry I didn't want the video close enough.

Seems to be that you are getting an invalid error. The error should be something like "Time series must be reduced to be alerted on". so the error you are getting I think is a bug in that it should be giving a different error.

So you need to add extra step before math (reduce):

![image](https://user-images.githubusercontent.com/1692624/155142623-6959af86-0cad-49ba-be78-3e9aa573f9d9.png)

![image](https://user-images.githubusercontent.com/1692624/155142692-244b54e8-3ed7-46a0-b353-19cfbc2fa2bc.png)

and then hopefully that works for you? (and we need to investigate the error message)

**Comment by bobemoe** [comment] 2022-02-22 14:06
Thanks for investigating.

I've tried adding the Reduce step, that indeed makes sense, however I'm still getting the same error.

I thought it had worked at first, but my "Albert Condition" was still set to B rather than C. When set to B all series alert, when set to C the error occurs.

@kylebrandt I think maybe your screenshot alert condition above may be also set to B as your server001 should not be alerting according to C, yet it is alerting in the preview and says var=B.  Could you confirm this please?

**Comment by bobemoe** [comment] 2022-02-22 14:17
I notice you use `name=server.requests.count` as your graphite query, I'm not familiar with that syntax, any reference I can check out?

Also, graphite does not have `label()` function but does have `alias()` to change the legend with. When using this the name changes on the A panel, but no difference on B or C:
![image](https://user-images.githubusercontent.com/2304970/155150243-53057bfe-f63d-4f1a-8ee5-33111a7d92fc.png)

**Comment by kylebrandt** [comment] 2022-02-22 18:22
> @kylebrandt I think maybe your screenshot alert condition above may be also set to B as your server001 should not be alerting according to C, yet it is alerting in the preview and says var=B. Could you confirm this please?

I am sure if I had it correct. But the issue in my screenshot above is that my math should have been `$B > 10`, like what follows for my example:

![image](https://user-images.githubusercontent.com/1692624/155194590-ee373a16-b3e3-4c0d-b98d-5ba1070eaa01.png)

![image](https://user-images.githubusercontent.com/1692624/155194638-6c089487-3a39-41ca-a228-ebd057f9a830.png)


The "Var B" you see is in the "Info" column, so that is information about other conditions even if they were not selected as the condition to alert on (So that info can be included in notifications and such).

> I notice you use name=server.requests.count as your graphite query, I'm not familiar with that syntax, any reference I can check out?

I don't know Graphite very well. But originally it didn't have "Tags" (For this Tags == Labels, same concept different word). Later versions of Graphite added support for tags: https://graphite.readthedocs.io/en/latest/tags.html . So that example is using a query for Graphite metrics with tags.

**Comment by kylebrandt** [comment] 2022-02-22 18:36
(For Devs) As far the "wrong error message bug" goes, I believe it is a logic error in `evaluateExecutionResult`:

https://github.com/grafana/grafana/blob/ea3e41ea62de4a78c301c129b1863d5d89fc7e38/pkg/services/ngalert/eval/eval.go#L514

While going over the execution Results, we create Eval Results, those Eval Results can be an error result. Then where I linked, we loop over the eval results to look for duplicate labels. And return a single error if there are duplicates by labels. And I think what creates the duplicate labels here is that error results do not have a label (as one would expect), and when we return that dupe error the errors are masked.

**Comment by alaricljs** [comment] 2022-03-08 18:18
I am getting this same error on Grafana 8.4.3 against VictoriaMetrics (a Prometheus compatible TSDB) in spite of having uniquely identifying label sets for each series.  I can reproduce it with or without an Expression using a node_exporter textfile custom label metric:
```
# HELP custom_data This metric’s purpose is to provide labels.
custom_data {hostname="obfusc1",env="sandbox",env_type="nonprod",product="thing",application="subthing"} 1
```

This is on 4 systems and the differentiated labels are `hostname`, `application`,  and the intrinsic `instance`.

With A query being: custom_data{env="sandbox"} and Condition set to A I get the same frame error as above and I find nothing of value in grafana.log (level=debug).

It appears to go beyond just a poor error against errored Eval Results.

**Comment by alaricljs** [comment] 2022-03-08 20:35
Regarding the above I argue that with the current functionality it's a documentation issue.  The documentation does not plainly state that Alerts can only function correctly against non-time series data.  There is no in-built default of Reduce.Last() when using Math.  So instead of `Use Math, Reduce, or Resample expressions to create a multi-dimensional rule.`  I would recommend something along the lines of `Use Reduce or Resample to collapse data to a single point, and optionally Math to apply conditions.`

**Comment by reyjrar** [comment] 2022-08-23 18:01
In 9.1.1, I'm unable to get any Graphite query to generate an alert using the `Reduce` > `Math` step. I always get:

```
invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}
```

And the when I view the `Reduce` query, all the results only have `B` as their identifier. This is very, very, very, very broken for Graphite without Tags.

**Comment by reyjrar** [comment] 2022-08-23 18:15
> In 9.1.1, I'm unable to get any Graphite query to generate an alert using the `Reduce` > `Math` step. I always get:
> 
> ```
> invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}
> ```
> 
> And the when I view the `Reduce` query, all the results only have `B` as their identifier. This is very, very, very, very broken for Graphite without Tags.

It looks like this is a bug in carbonapi, not Grafana. When I switch over to the Graphite Web instance, this now works.

**Comment by bobemoe** [comment] 2022-12-15 17:58
Quick update... Since I originally reported this issue, the "create new alert" process has changed significantly (8.4.1 -> 9.3.1), especially in the UI / workflow area.

It seems the reduce step is now automatically added by default. Its more intuitive and I created a wildcard alert similar to my original attempt, this time with no issues. Still using Graphite WITHOUT tags.

If I delete the reduce step and link the threshold step to the source data in attempt to trigger the confusing error message, the final values says "Time series data" and fires the alert. Seems sensible.

I'd be happy my original issue is solved and to close this now but since other have posted slightly different related comments I'll leave it open in case further investigation is required.

**Comment by yuri-tceretian** [comment] 2023-02-15 21:11
This issue is year old. A lot has changed since then on UI as well as backend side. Let's close the issue. If somebody encounter similar problem where 
```
invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}
``` 
cannot be solved by using Reduce expression, please open a new issue and refer to this one for history.

**Closed by yuri-tceretian** 2023-02-15 21:11 UTC
Labels: type/bug, datasource/Graphite, area/alerting, prio/low, effort/none, area/expressions
