### ISSUE TITLE
Multiple Org Ids for same datasource in datasource.yml file for provisioning

### ISSUE THREAD

**Issue by vijayakumarbathini** [grafana/grafana#20500] opened 2019-11-20 09:13 UTC
**What would you like to be added**:
Support for multiple org Ids for same datasource and dashboards in datasource.yml file and dashboard.yml file
**Why is this needed**:
Currently we are having around 150+ tenants(organizations) which uses same datasources and dashboards as OOB by using provisioning. In order create 1 datasource we have to recreate the same structure in yaml files. If there is a option to provide multiple values for orgId it will be really great. All the duplicate configurations can be removed.

**Comment by marefr** [comment] 2019-11-20 13:56
Duplicate of #12717

**Comment by marefr** [comment] 2019-11-20 13:56
See https://github.com/grafana/grafana/issues/12717#issuecomment-410746748

**Closed by marefr** 2019-11-20 13:56 UTC
Labels: type/duplicate
