### ISSUE TITLE
PromQueryBuilderOptions.tsx:57 -> Unexpected error while editing Prometheus query (on Panel)

### ISSUE THREAD

**Issue by kerk12** [grafana/grafana#53981] opened 2022-08-19 19:24 UTC
**What happened**:
When I go to edit an already existing panel fed through a prometheus query, I get an Unexpected error. The same does not happen when editing InfluxDB queries. They work as expected.

**What you expected to happen**:
To be able to edit the query, as usual.

**How to reproduce it (as minimally and precisely as possible)**:
Go to one of your Dashboards, find a panel that gets fed through a Prometheus query, try to edit it. 

**Anything else we need to know?**:
Error Log:
```
TypeError: l.find(...) is undefined

42120/He<@http://harbor.gk-west.lan:3000/public/build/prometheusPlugin.33be270b46c7028fddb6.js:76:20354
div
A@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:12802
28288/t.EditorRows@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:69342
42120/it<@http://harbor.gk-west.lan:3000/public/build/prometheusPlugin.33be270b46c7028fddb6.js:80:87
dt@http://harbor.gk-west.lan:3000/public/build/prometheusPlugin.33be270b46c7028fddb6.js:80:3456
nu@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:3229:467
au@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:3229:1023
div
div
div
48435/Eo<@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:706213
g@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1100199
So@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:707528
Oo@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:707637
h@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:5731:173
div
F@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:7534:955
div
48435/Ro<@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:709887
g@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1100199
l@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1098242
zr@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:693234
t@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:626665
Hr@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:696777
l@http://harbor.gk-west.lan:3000/public/build/6549.b753dd4af219c39bac3d.js:71:268
div
div
div
div
div
t@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:777624
c@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:83:3007
H@http://harbor.gk-west.lan:3000/public/build/3833.fe8dcff66b78faf8db53.js:5:185
Gr@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:404:229
div
go@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:2653:46
div
16145/Vr<@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:404:1619
div
div
n@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:82:8762
div
n@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:82:10711
div
n@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:82:8762
div
n@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:82:10711
et@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:82:16296
div
div
Xr@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:421:1512
g@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1100199
WithTheme(Connect(Xr))
div
div
div
t@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:777624
c@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:83:3007
div
div
A@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:5654:622
si@http://harbor.gk-west.lan:3000/public/build/DashboardPage.73f5dda94807c3c59e04.js:542:7350
DashboardPage
g@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1100199
n@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1046530
jl@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:8233:11732
t@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1115517
t@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1117538
main
wo@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:8193:22410
t@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1112135
div
Fi@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:2476:1027
19175/t.KBarProvider@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:357775
l@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:5959:28436
nu@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:3229:467
au@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:3229:1023
y@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:2902372
bl@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:8233:10882
l@http://harbor.gk-west.lan:3000/public/build/6354.1768cf67d93e3edb7654.js:2:1098242
Jl@http://harbor.gk-west.lan:3000/public/build/1173.a5030327bdb403b00878.js:8246:115
```

Query:
```
netdata_cpu_cpu_percentage_average{dimension!~"idle"}
```

Devtools console log:
```
TypeError: l.find(...) is undefined
    He PromQueryBuilderOptions.tsx:57
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    loadDatasource QueryEditorRow.tsx:144
react-dom.production.min.js:216:199
```
It points to this line:
```js
const formatOption = FORMAT_OPTIONS.find((option) => option.value === query.format) || FORMAT_OPTIONS[0];
const queryTypeValue = getQueryTypeValue(query);
const queryTypeLabel = queryTypeOptions.find((x) => x.value === queryTypeValue)!.label;
```

**Environment**:
- Grafana version: Docker: grafana-oss (v9.1.0 (82e32447b4))
- Data source type & version: Prometheus, latest.
- OS Grafana is installed on: Ubuntu Server, in a docker container (see above)
- User OS & Browser: Firefox on Windows. Same error on Edge and Chrome as well...
- Grafana plugins: none, just the default ones.
- Others: No reverse proxy used. I access the container directly (currently not in production)

**Comment by evandandrea** [comment] 2022-08-23 15:12
Hello. A few questions to help us understand the issue here:
1. Are you able to reproduce this issue on https://play.grafana.org/ ?
2. Does this error occur for other queries, or only this one?

**Comment by obetomuniz** [comment] 2022-10-24 19:55
@kerk12 Are you still figuring out the problem? I was not able to reproduce the issue reported using other queries on https://play.grafana.org/ and locally. Dashboard that uses a Prom query seems fine while editing. Could you please share additional details that can help us try to reproduce using https://play.grafana.org/ ? 

Closing it for now, but feel free to reopen it if you have more details.

**Closed by obetomuniz** 2022-10-24 19:55 UTC
Labels: datasource/Prometheus, area/frontend
