### ISSUE TITLE
Visual query editor for Flux (InfluxDB 2.0)

### ISSUE THREAD

**Issue by aleheux-tc** [grafana/grafana#33082] opened 2021-04-16 18:12 UTC
There is no visual query editor for Flux, which is the InfluxDB 2.0 query language. There is one for InfluxCL (1.x).

This would greatly help those who are not (yet) very familiar with Grafana/InfluxDB.

**Comment by hugohaggmark** [comment] 2021-04-19 08:59
Duplicate of #27697

**Closed by hugohaggmark** 2021-04-19 08:59 UTC
