### ISSUE TITLE
Azure Monitor Datasource - Bar chart render is spread out for partial sets

### ISSUE THREAD

**Issue by dylan-asos** [grafana/grafana#20513] opened 2019-11-20 12:15 UTC
**What happened**:

When using the Azure Monitor source and writing queries against a Log Analytics workspace,  Bar charts can be rendered inconsistently over the x-axis when there are a limited amount of data points in the time-window.

![time-series-as-bars](https://user-images.githubusercontent.com/16137664/69236710-08d93100-0b8c-11ea-967c-e6cc2ef2a5cb.png)

Viewing the points that made up the set, there were only a few returned for this window

![Time-series-as-points](https://user-images.githubusercontent.com/16137664/69238351-aeda6a80-0b8f-11ea-8025-fd113953cf9a.png)

**What you expected to happen**:

Bar charts are rendered at the points at which they happened and are not 'spread out' over time on the x-axis.

'Null as zero' would be the closest UI option I would expect to set that would fix the behaviour.

**How to reproduce it (as minimally and precisely as possible)**:

* Add a new panel
* Choose a Azure Log Analytics Data Source
* Set the time window to the last 30 minutes
* Add the following query to return a single point (assuming you have Heartbeat)

```
let timeRange = ago(30s);
let TimeTable = Heartbeat
| where TimeGenerated > ago(10m) and TimeGenerated  < ago(9m)
| summarize count() by bin(TimeGenerated, 1m)  
| order by TimeGenerated desc;
TimeTable
| project 
    TimeGenerated,
    TotalCount = 1
| order by TimeGenerated desc
| take 1
```

![example-query-to-reproduce](https://user-images.githubusercontent.com/16137664/69238088-03311a80-0b8f-11ea-9bce-ac7bccbd01d6.png)

**Anything else we need to know?**:

Workaround: 

Using a make-series query on the source query 'fills in the blanks' and creates a complete set of points for the window, resulting in correct rendering of bar graphs.

```
let fromGrafanaTime = (t:long)
{ 
    datetime(1970-01-01) + t * 1ms 
};
SourceTable 
| where $__timeFilter(TimeGenerated) 
| make-series c=count() default=0 on TimeGenerated from fromGrafanaTime($__from) to fromGrafanaTime($__to) step $Interval by SummaryColumn 
| mv-expand TimeGenerated to typeof(datetime), c to typeof(int)
| order by TimeGenerated asc, SummaryColumn asc
```

![make-series-add-zeros](https://user-images.githubusercontent.com/16137664/69237158-f0b5e180-0b8c-11ea-9a39-e7ef1885fcc0.png)

Whilst this works, it does result in overly complex queries for users to work with.

**Environment**:
- Grafana version: Grafana v6.4.3 (3a2bfb7)
- Data source type & version: Azure Monitor

**Comment by hugohaggmark** [comment] 2020-06-11 12:09
Thanks for reporting this @dylan-asos and very sorry for the late feedback. I confirm this is a bug in v6.4.3 of Grafana but I can't reproduce it in v7.0.0 of Grafana so I will close this issue. We can always reopen this issue if extra evidence points are found.

**Closed by hugohaggmark** 2020-06-11 12:09 UTC
Labels: needs investigation
