### ISSUE TITLE
List all core plugin on the Plugins page of grafana.com

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#29778] opened 2020-12-11 16:14 UTC
**What would you like to be added**:
Some of our core plugins are listed on the plugins page but others don’t seem to be:
- MS SQL Server
- Jaeger
- Zipkin
- Tempo
- Google Cloud monitor
- Azure monitor

We should list them.

**Why is this needed**:
Many grafana.com visitors search for core plugins with terms like `MSSQL`, `thanos`, `jaeger` , etc. It's valuable to see plugin details on the website and know that those plugins are available, even if they are built in to Grafana.

**Comment by aocenas** [comment] 2021-01-13 09:37
I am not sure if this is done from grafana repo or somewhere else. @daniellee @briangann do you know how the core datasources get into the plugin page?

**Comment by zoltanbedi** [comment] 2021-02-26 09:59
We probably need to add values here https://github.com/grafana/grafana-com/blob/dd7b653b46e6572fd3d0a79b1a4a9a3ea60d9953/api/routes/plugins.js#L659

**Comment by zoltanbedi** [comment] 2021-02-26 15:36
Duplicate of https://github.com/grafana/grafana-com/issues/1695

**Comment by mjseaman** [comment] 2021-03-23 17:28
Hey @zoltanbedi I think that https://github.com/grafana/grafana-com/issues/1695 is different.

**Comment by zoltanbedi** [comment] 2021-03-23 17:36
Hi @mjseaman,
I've opened a pr to fix this issue https://github.com/grafana/grafana-com/pull/2403 see the comments there. Also I think we can't do anything about this in this repository.

**Closed** 2021-06-17 08:41 UTC
Labels: area/backend/plugins, area/plugins, datasource/Azure, datasource/Jaeger, datasource/MSSQL, datasource/Tempo, datasource/Zipkin
