### ISSUE TITLE
[embedded panel] iframe height makes the vertical scrollbar always show up

### ISSUE THREAD

**Issue by earthnut** [grafana/grafana#3650] opened 2016-01-06 00:56 UTC
Hi ,
   I am trying to put iframe into anther site, however i am facing the problem to disable vertical scrollbar .
   As I looking into the html and found the iframe height seems to be min-height  and the real height is another number . Please check the image below.
   
![a7357847-9edc-4038-9ac4-d17aa8544d01](https://cloud.githubusercontent.com/assets/16567767/12132124/9967141e-b3cd-11e5-8742-73bfcb4c0499.png)

![6709bbfd-b0cb-4ce7-9cab-9ebb8bf00aee](https://cloud.githubusercontent.com/assets/16567767/12132059/0a24528a-b3cd-11e5-9721-33f74c389dee.png)

  is there any work around or way to let me know the real height.

Thanks

**Comment by torkelo** [comment] 2016-01-06 05:06
this is duplicate of https://github.com/grafana/grafana/issues/3607 so I will close it :)

**Closed by torkelo** 2016-01-06 05:06 UTC

**Comment by stahor** [comment] 2017-03-14 12:51
@torkelo this is other issue. Pay attention to difference between actual height and what is calculated. It's much more than border width.
I've faced this problem too and it looks like it was caused by the fact that title of my panel takes more than one line =/.

**Comment by torkelo** [comment] 2017-03-14 13:31
More than one line? Might need to make iframe bigger or reduce the title text

**Comment by stahor** [comment] 2017-03-14 14:29
Nope. It does not help. If you set iframe's height even to 5000px there will be that scrollbar and the difference will be exactly the same as these extra lines take. Looks like height of panel-content is calculated depending on height of iframe  somehow. I haven't yet found this place in code TBH.

**Comment by torkelo** [comment] 2017-03-14 14:42
so you made it bigger so the title is on a single line and still scroll bar?

**Comment by stahor** [comment] 2017-03-14 15:08
No-no the title still takes two lines. But if I change it to take one line scrollbar will disappear. That's why I think that this is the source of issue.

**Comment by torkelo** [comment] 2017-03-14 15:23
Yes, that is the issue, which is why I recommend increasing iframe width or reducing panel title text. Wrapping  panel titles are not supported :(

**Comment by stahor** [comment] 2017-03-14 16:24
Hm ok. I'll probably take a look at this during weekend. Could u tell me where I can find all these calculations for panel height? I mean folder/files/modules. I'm new to grafana and it's a little bit hard to find what I need for now

**Comment by torkelo** [comment] 2017-03-14 16:32
panel_ctrl

**Comment by stahor** [comment] 2017-03-14 16:32
Ta
