### ISSUE TITLE
[Bug] v3.0.0-beta6 gui missing GROUP_BY plus sign

### ISSUE THREAD

**Issue by errnoh** [grafana/grafana#4870] opened 2016-05-01 12:04 UTC
Running v3.0.0-beta6 (2016-04-29), datasource is InfluxDB v0.12.2.

![example](http://i.imgur.com/4FLTCAp.jpg)

Iirc when I was using beta5 previously (download link has been removed since beta6 came out) the plus sign was still there. The drop down menus in the GUI makes it easy to generate graphs without having to remember the whole db schema and would be nice to have this functionality for the GROUP_BY as well.

**Comment by torkelo** [comment] 2016-05-01 12:29
fixed already :)

dupe of https://github.com/grafana/grafana/issues/4862

**Closed by torkelo** 2016-05-01 12:29 UTC
