### ISSUE TITLE
OpenShift oauth login issue

### ISSUE THREAD

**Issue by ndox** [grafana/grafana#9585] opened 2017-10-18 13:34 UTC
Grafana version :  4.5.2
Openshift Version : 3.5

It seems that oauth from OpenShift cannot be used with grafana because email are not present : 
t=2017-10-18T11:38:13+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="Error getting email address: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"users \\\"emails\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"emails\",\"kind\":\"users\"},\"code\":404}\n"
 
Why email is required for grafana to authenticate/sign up ? 
https://github.com/grafana/grafana/blob/88f55b01d81e304c194101ca8e9bfe1ced5d305e/pkg/api/login_oauth.go#L145

Configuration used : 
GF_AUTH_GENERIC_OAUTH_ENABLED=true
GF_AUTH_GENERIC_OAUTH_CLIENT_ID=XXXX
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=XXXX
GF_AUTH_GENERIC_OAUTH_SCOPES=user:full, user:check-access
GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://XXX/oauth/authorize
GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://XXX/oauth/token
GF_AUTH_GENERIC_OAUTH_API_URL=https://XXXX/oapi/v1/users/

I do connect do /users :
lvl=dbug msg="HTTP GET https://XXXX/oapi/v1/users/: 200 OK {\"kind\":\"UserList\",\"apiVersion\":\"v1\",\"metadata\":{\"selfLink\":\"/oapi/v1/users/\",\"resourceVersion\":\"101500705\"},\"items\":[{\"metadata\":{\"name\":\"XXXXXXX\",\"selfLink\":\"/oapi/v1/users/XXXXXXXX\",\"uid\":\"1c358ce0-f298-11e6-b3d4-028d1d8f61bf\",\"resourceVersion\":\"25960476\",\"creationTimestamp\":\"2017-02-14T09:29:40Z\"},\"identities\"

But then got the error because it didn't found email field.

**Comment by DanCech** [comment] 2017-10-18 21:34
Have you tried adding `email` to the scopes you're requesting? The way the account linking works currently it needs to have an email address.

**Comment by ndox** [comment] 2017-10-19 13:23
Hi @DanCech, thanks for the reply. 

On the OpenShift side there is no way to add a user's mail because the field is not present in the object user.

Looking at the oauth RFC I didin't found that it is a mandatory field.

**Comment by DanCech** [comment] 2017-10-19 13:32
The problem is that grafana currently uses the email address as the account identifier for oauth-authenticated users, so regardless of whether it is required by the RFC Grafana does require an email address be returned.  There is some work and discussion in #8689 that would allow using oauth without an email address but I haven't had time to pursue that further.

**Comment by ndox** [comment] 2017-10-20 10:29
Thanks, so I'll follow it since it should fix my issue

**Comment by sengaya** [comment] 2018-06-21 16:33
PR #11354 is merged. Anyone got oauth working with OpenShift?

**Comment by DanCech** [comment] 2018-06-21 20:09
The OAuth connector code still requires an email address

**Closed** 2020-11-10 16:06 UTC
Labels: area/backend/auth, type/duplicate, type/feature-request
