### ISSUE TITLE
Dashboards: Unable to edit Grafana V10.x panels on Safari browser, And Chinese characters cannot be typed in the top input bar.

### ISSUE THREAD

**Issue by YouZhengChuan** [grafana/grafana#74431] opened 2023-09-06 09:02 UTC
### What happened?

1. Unable to edit panels in the new version of Grafana on Safari browser.
2. Chinese characters cannot be typed in the top input bar.

### What did you expect to happen?

1. After upgrading to the `v10.1.1` version, no panels, whether graphics or text tables, can be edited on the Safari browser. Panels can be added, but not edited.
2. The Edit button in the upper right corner of the panel is not visible. The panel can be moved and resized, but the edit button of the panel is not displayed; the `v10.0.3` version can pop up the menu by clicking the left mouse button on the upper right corner. After upgrading to the `v10.1.1` version, clicking the upper right corner of the panel will no longer pop up menu.
3. The top search bar only supports letter input, and Chinese characters cannot be input. In "grafana v9.5", you can enter Chinese characters in the top search bar.

### Did this work before?

1. In the `Grafana v10.1.1` version, it is not possible to edit any panels on the Safari browser. But the older `Grafana v5.x` can work normally on Safari browser.
2. The top search bar of `Grafana v9.5` supports typing in Chinese, which is available on both Safari and Chrom browsers.

### How do we reproduce it?

1. This problem can be reproduced by opening the Grafana dashboard page in Safari and trying to edit it.
2. Add any Chinese input method, switch to the Chinese input method, and enter any character, then press the car, you can find that the English letters are displayed in the input field, but the Chinese characters are lost.

### Is the bug inside a dashboard panel?

dashboard json:

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 550,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "bbc48f27-0b45-40f5-9dec-7272c39cb309"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "bbc48f27-0b45-40f5-9dec-7272c39cb309"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "area::tag"
              ],
              "type": "tag"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "random_data",
          "orderByTime": "ASC",
          "policy": "one_week",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "temp"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "mean"
              }
            ]
          ],
          "tags": []
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "influxdb",
        "uid": "bbc48f27-0b45-40f5-9dec-7272c39cb309"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 1,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "bbc48f27-0b45-40f5-9dec-7272c39cb309"
          },
          "groupBy": [
            {
              "params": [
                "1m"
              ],
              "type": "time"
            },
            {
              "params": [
                "area::tag"
              ],
              "type": "tag"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "measurement": "random_data",
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "temp"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "mean"
              }
            ]
          ],
          "tags": []
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard",
  "uid": "f3779269-1635-4421-b128-10a6921e18ab",
  "version": 2,
  "weekStart": ""
}
```

### Environment (with versions)?

Grafana: 10.1.1
OS: Mac OS 12.1 
Browser: Safari 15.2 (17612.3.6.1.6)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by zuchka** [comment] 2023-09-12 04:44
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by YouZhengChuan** [comment] 2023-09-12 07:38
@zuchka  thank for your reply.

I also encountered the same problem when accessing "play.grafana" on Safari browser:

1. After typing Chinese characters in the top search bar, you will get extra characters.

![image](https://github.com/grafana/grafana/assets/3882312/df6fb98f-65ae-4198-ab17-fb34cf326a78)

Chinese characters can be typed normally elsewhere. For example in the "dashboards" search bar:

![image](https://github.com/grafana/grafana/assets/3882312/540f2fda-8183-4942-88a7-a48889f5ea78)


2. All panels are not editable and can only be resized and repositioned.

![image](https://github.com/grafana/grafana/assets/3882312/061cd9c4-9385-4b62-86e4-594ef1f471ef)

**Comment by ipcpu** [comment] 2023-09-13 07:16
+1 
10.1.1版本搜索框输入中文有问题

**Comment by ahrtolia** [comment] 2023-11-07 02:04
+1
In version 10.1.1, the Chinese search box does not work properly. We have tried it on Safari, Chrome, Firefox and other browsers, and it cannot input Chinese characters through the input method

You can do this by typing in the top search box using the Chinese input method

**Comment by ahrtolia** [comment] 2023-11-07 02:11
We checked that there was an issue with the kbar package imported by grafana, and the issue is as follows
https://github.com/timc1/kbar/issues/327

This problem also exists in https://play.grafana.org

**Comment by gitWyz** [comment] 2023-12-29 10:28
![Uploading D51B4891-4F55-4D43-AAFF-81157228A8D3.png…]()

Look at https://play.grafana.org/ seems to have solved the problem.

**Comment by gitWyz** [comment] 2023-12-29 10:28
<img width="1314" alt="D51B4891-4F55-4D43-AAFF-81157228A8D3" src="https://github.com/grafana/grafana/assets/34329903/ba125134-26bf-4d20-91c0-fbc7b06692c6">

Look at https://play.grafana.org/ seems to have solved the problem.

**Comment by gelicia** [comment] 2024-02-29 15:38
This should be fixed as of https://github.com/grafana/grafana/pull/78373 - closing. Please feel free to reopen if you still encounter this after 10.2.3

**Closed by gelicia** 2024-02-29 15:38 UTC
Labels: needs more info
