### ISSUE TITLE
Variable interpolation does not work on Transformation input fields

### ISSUE THREAD

**Issue by thiagogcm** [grafana/grafana#26872] opened 2020-08-07 21:19 UTC
**What happened**:
I cannot use variables on Transformation inputs
**What you expected to happen**:
To be able use variables everywhere
**How to reproduce it (as minimally and precisely as possible)**:
Just use a variable on Transformation inputs (such as Filter By Name identifier)
**Anything else we need to know?**:
Variable works as expected on panel title, and constant value works on the Transformation input:
![image](https://user-images.githubusercontent.com/1041364/89689050-e8980080-d8d9-11ea-8f81-3af558e664eb.png)
But the variable does not work on the Transformation Input:
![image](https://user-images.githubusercontent.com/1041364/89689269-64924880-d8da-11ea-8abc-28aa6c9b0867.png)

**Environment**:
- Grafana version:  7.1.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2020-08-09 05:58
duplicate of https://github.com/grafana/grafana/issues/25469

**Closed by torkelo** 2020-08-09 05:58 UTC
