### ISSUE TITLE
Explore doesn't work as expected with ElasticSearch

### ISSUE THREAD

**Issue by EugeneKrapivin** [grafana/grafana#19814] opened 2019-10-15 09:14 UTC
**What happened**:
Explore doesn't work with Elasticsearch. when trying you use explore I'm getting
```
Error connecting to datasource: No date field named @timestamp found
```
This issue might be connected to the fact we are using ES with cluster search, hence we do not have mappings.
Another issue that might be related, when creating/saving an ES datasource I would get an error that there is no timestamp field but the source is still working (sans auto-completion on field names)

[probably related issue](https://github.com/grafana/grafana/issues/9906)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: ES 6.7.2 (EDIT: datasource configured to version 6.0+)
- OS Grafana is installed on: centOS
- User OS & Browser: chrome on windows

**Comment by papagian** [comment] 2019-10-15 11:04
There was a similar [issue](https://github.com/grafana/grafana/issues/17011) and it was fixed by selecting the right version in the datasource definition.
Please can you verify that you have selected `6.0+` as Elasticsearch version?

**Comment by EugeneKrapivin** [comment] 2019-10-15 12:45
@papagian yes I can confirm that the ES datasources are configure with version 6.0+
If you'd like i could submit a screenshot of the configuration

**Comment by papagian** [comment] 2019-10-16 07:49
Thank you for your reply!
I'm unable to reproduce it, could you please share the request and response from your browser's Network tab when you try to save the datasource and get the error.

**Comment by EugeneKrapivin** [comment] 2019-10-16 10:48
When reproducing this issue did you use ES in cluster search?
Previously we've been using a tribe, which shared the same mappings with all the other clusters. Since this method is deprecated and now ES uses cluster search, We have a new node that participates in this cluster search but doesn't share the same indexes and mappings as all the other clusters. does that make sense?

These are the requests (for brevity I've omitted the GET request following the save PUT operation)
```
PUT https://<redacted>/api/datasources/39 HTTP/1.1
Host: <redacted>
Connection: keep-alive
Content-Length: 525
Accept: application/json, text/plain, */*
Origin: <redacted>
X-Grafana-Org-Id: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Sec-Fetch-Mode: cors
Content-Type: application/json;charset=UTF-8
Sec-Fetch-Site: same-origin
Referer: https://<redacted>/datasources/edit/39/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,he-IL;q=0.8,he;q=0.7
Cookie:<redacted>
Pragma: no-cache

{"id":39,"orgId":1,"name":"AppLogs","type":"elasticsearch","typeLogoUrl":"","access":"proxy","url":"http://<redacted>:9200","password":"<redacted>","user":"<redacted>","database":"[*:*-app-logs-]YYYY.MM.DD","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":false,"jsonData":{"esVersion":60,"interval":"Daily","keepCookies":[],"logLevelField":"priority","logMessageField":"@message","maxConcurrentShardRequests":"64","timeField":"@timestamp"},"secureJsonFields":{},"version":3,"readOnly":false}
```
this is the response:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json
Date: Wed, 16 Oct 2019 10:38:55 GMT
Pragma: no-cache
Server: nginx/1.12.2
Vary: Accept-Encoding
X-Frame-Options: deny
Content-Length: 525
Connection: close

{"id":39,"orgId":1,"name":"AppLogs","type":"elasticsearch","typeLogoUrl":"","access":"proxy","url":"http://<redacted>:9200","password":"<redacted>","user":"<redacted>","database":"[*:*-app-logs-]YYYY.MM.DD","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":false,"jsonData":{"esVersion":60,"interval":"Daily","keepCookies":[],"logLevelField":"priority","logMessageField":"@message","maxConcurrentShardRequests":"64","timeField":"@timestamp"},"secureJsonFields":{},"version":5,"readOnly":false}
```

This is the request for mappings:
```
GET https://<redacted>/api/datasources/proxy/39/*:*-app-logs-2019.10.16/_mapping HTTP/1.1
Host: <redacted>
Connection: keep-alive
Accept: application/json, text/plain, */*
X-Grafana-Org-Id: 1
X-Grafana-NoCache: true
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Referer: https://eu3-grafana.gigya.net/datasources/edit/39/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,he-IL;q=0.8,he;q=0.7
Cookie: <redacted>
Pragma: no-cache
```

this is the response:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Wed, 16 Oct 2019 09:04:36 GMT
Server: nginx/1.12.2
Warning: 299 Elasticsearch-6.7.2-56c6e48 "[types removal] The parameter include_type_name should be explicitly specified in get mapping requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."
X-Frame-Options: deny
Content-Length: 2
Connection: close
Cache-Control: no-cache

{}
```

**Comment by torkelo** [comment] 2019-12-02 21:26
closing due to lack of updates

**Closed by torkelo** 2019-12-02 21:26 UTC
Labels: area/datasource, area/explore, datasource/Elasticsearch, type/bug

**Comment by EugeneKrapivin** [comment] 2019-12-17 08:31
@torkelo I wasn't aware you are expecting additional info for this case.
If you require additional information - I'll gladly provide it since I believe this issue is influencing more than the explore feature
