### ISSUE TITLE
Cannot use Google Auth + Server side rendering because of root_url

### ISSUE THREAD

**Issue by Esya** [grafana/grafana#6115] opened 2016-09-22 22:45 UTC
* **I'm submitting a ...**
- [x] Bug report

Please include this information:
- What Grafana version are you using? **3.1.1**
- What datasource are you using? Graphite
- What OS are you running grafana on? **Ubuntu 14**

We run multiple grafana servers behind a loadbalancer at **dashboard.ourdomain.com**. Because of that, we set this in our grafana.ini :  

```
root_url = https://dashboard.ourdomain.com
```

But then, when we try to use the direct link rendering system, or our `hubot-grafana` bot, it tries to query : 
```
t=2016-09-22T22:40:59+0000 lvl=info msg="PhantomRenderer::renderToPng url [https://dashboard.ourdomain.com/dashboard-solo/db/rds?from=1474579848054&to=1474583448055&[REDACTED]]"
```

And it gets to another server and **renders the login screen*. It should instead query localhost:3000, and not go through the public URL. 

It works when we set root_url to localhost:3000 but then the Google OAuth callbacks don't work anymore. 

These should probably use two different variables

**Comment by torkelo** [comment] 2016-09-23 10:00
dupe of https://github.com/grafana/grafana/issues/5906

**Closed by torkelo** 2016-09-23 10:00 UTC

**Comment by oryband** [comment] 2016-12-01 16:53
I'm sorry, but this issue still is not resolved for us.
We're using Google auth along with an Nginx reverse proxy that redirects traffic in the following manner:

```
external --(https)--> nginx --(http)--> grafana
```
Unfortunately still getting login page PNGs.

Any advice?

**Comment by oryband** [comment] 2016-12-01 17:06
Please ignore my message above. Version 4.0.0 indeed fix this problem. Thank you.
