### ISSUE TITLE
[Bug] Comments in .md being parsed as text.

### ISSUE THREAD

**Issue by prajwalrao** [grafana/grafana#5350] opened 2016-06-13 17:00 UTC
Comments in the README.md file are being parsed as text. I have the APACHE License as a comment inside my .md file and it's commented out by Github, but shows up on the **/plugins/plugin-name/edit** page as normal text.

Please include this information:
- What Grafana version are you using? - **3.0.4**
- What datasource are you using? - Custom

**Screenshot**
<img width="931" alt="screen shot 2016-06-13 at 9 53 51 am" src="https://cloud.githubusercontent.com/assets/15118150/16016029/822c8baa-314d-11e6-95c0-29bb79fd1fb7.png">

**Comment by DanCech** [comment] 2016-06-13 17:30
This appears to be caused by a bug in the `remarkable` library used to render plugin README files: https://github.com/jonschlinkert/remarkable/issues/209

I would suggest placing the license terms into LICENSE.txt instead of inlining them in README.md.

**Comment by bergquist** [comment] 2016-06-14 05:21
Not sure this issue belongs to this repo. But not sure where to move it either.

**Comment by torkelo** [comment] 2016-06-14 06:16
will close this for now, saying that comments in README are not supported (until fixed in remarkable)

**Closed by torkelo** 2016-06-14 06:16 UTC
