### ISSUE TITLE
Repeated gauge displays wrong value with >1 variable selected

### ISSUE THREAD

**Issue by ryan-maus** [grafana/grafana#15880] opened 2019-03-08 16:41 UTC
**What happened**:
Repeated gauges display the incorrect value when more than one variable option is selected (or the "all" option is selected):
![grafana_bug](https://user-images.githubusercontent.com/302280/54041799-3ad96d00-418e-11e9-9283-60d5b4b4f39b.PNG)

If a single option is selected, it displays the correct value:
![grafana bug 2](https://user-images.githubusercontent.com/302280/54041869-6fe5bf80-418e-11e9-957c-c2adb7b4e649.PNG)

**What you expected to happen**:
The gauges to display the correct values when multiple variables are selected.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Navigate to https://play.grafana.org/d/000000054/repeated-rows?orgId=1
2.  Select a single "server" variable ("backend_01" for example)
3.  In "Row1" configuration, set "Repeat for" to blank
4.  In the "backend_01" graph panel editor, change the visualization type to Gauge
5.  In the "backend_01" graph panel editor, set "Repeat" to "server"
5.  Return to dashboard
6.  Select "all" option for the "server" variable
7.  All four gauges briefly flash a "Query Error" red triangle, then all four gauges incorrectly display the same value.

**Anything else we need to know?**:
Thought this might be related to #15739 , but isn't exactly the same as I'm not using a repeated row.  If this is indeed a duplicate, apologies for that and I will look forward to 6.1.0 release with the fix for #15739.

**Environment**:
(NOTE: Grafana environment is whatever is being used on https://play.grafana.org)
- Grafana version: Grafana v6.0.1 (0c44a04)
- Data source type & version: ?
- OS Grafana is installed on: ?
- User OS & Browser: Windows 10 Pro v1803, Google Chrome v72.0.3626.119
- Grafana plugins: ?
- Others: ?

**Comment by roidelapluie** [comment] 2019-03-09 21:32
https://github.com/grafana/grafana/issues/15739

This will be fixed in 6.1.0

**Comment by roidelapluie** [comment] 2019-03-09 21:33
The issue you mention had nothing to do with rows at the end (just any repetition).

You can try grafana nightly and see if it works for you.

**Comment by saurabhnanda** [comment] 2019-03-20 16:45
I think I'm also hitting the same bug. Is this specific to prometheus data source or any data source?

Is installing master on production recommended? When is 6.1 scheduled to be released?

**Comment by andrewsav-datacom** [comment] 2019-04-11 23:37
@torkelo how is this fixed? If you follow these same steps now it still errors out - every guage except the first one displays the red triangle and a error:

> undefined is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by torkelo** [comment] 2019-04-16 08:35
can you try latest master ? think this will be fixed in v6.1.4 patch release we are doing today

**Comment by andrewsav-datacom** [comment] 2019-04-22 22:44
@torkelo https://play.grafana.org/d/000000054/repeated-rows?orgId=1 is now up to v6.1.4. The same steps still reproduces the issue.

May be it's worth reopening it, since it's seems that fixing this is proving challenging.

**Comment by torkelo** [comment] 2019-04-23 05:54
H

**Comment by torkelo** [comment] 2019-04-23 05:55
Actually this issue is fixed , the one your referencing is another issue

**Closed by torkelo** 2019-04-23 05:54 UTC
Labels: type/bug, type/duplicate

**Comment by AndrewSav** [comment] 2019-04-23 06:11
@torkelo, okay, is this another issue tracked anywhere? Or do you think it's a brand new issue?

**Comment by AndrewSav** [comment] 2019-04-24 21:39
@torkelo, hey, just to touch base, could you please get back to me on the state of the issue I described? I'd like to see it fixed, and if I need to copy and paste the repro from the above into the new issue, let me know and I'll do that. On the other hand, if you already tracking that elsewhere, please let me know where so I could track it too. Thank you in advance.

**Comment by andrewsav-datacom** [comment] 2019-04-28 21:35
It appears that this is now tracked here: https://github.com/grafana/grafana/issues/16762
