### ISSUE TITLE
Dashboards: geomap heatmap "Fit to data" doesn't fit map view to data #84230

### ISSUE THREAD

**Issue by aa-matthias** [grafana/grafana#91693] opened 2024-08-08 14:23 UTC
### What happened?

sorry opening another ticket but no response in the original one / the PR that attempted to fix the issue. https://github.com/grafana/grafana/pull/89248 attempted to fix issue #84230

### What did you expect to happen?

Fully fix the issue

### Did this work before?

yes

### How do we reproduce it?

1. Use Visualization of type Route / Heatmap for GeoMap panel, and fit to data as zoom level
2. GeoMap vis not updating / fully zoomed out
3.

### Environment (with versions)?

Grafana: 11.1.3
OS: Win11
Browser: Firefox 129

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by DEEJCUK** [comment] 2024-08-10 15:03
Same
last working version i can find is 11.0.0

**Comment by swiffer** [comment] 2024-08-29 04:24
Duplicate of #89777

**Closed** 2024-08-29 04:56 UTC
