### ISSUE TITLE
Unexpected UI behavior expanding trace spans in table panel

### ISSUE THREAD

**Issue by dmitri1242** [grafana/grafana#71496] opened 2023-07-12 16:10 UTC
**Describe the bug**
I am noticing unexpected UI behavior with the table panel connected to a Tempo (GCT) datasource to display interactive tables of traces and nested spans. When clicking on the greater than (>) arrow to the left of the trace ID to expand a trace, expanded rows containing spans appear under the wrong traces further down the list. This has happened sporadically in testing, but is reproducible.

**To Reproduce**
1. Created a dashboard and add 3 time series panels pointing to span metrics (GCM), one with exemplars. Add 1 table configured to query span metrics and 1 table pointing to tempo (GCT) traces (5 panels total).
2. Create a service variable for your panels (possible optional)
3. Clicking on the traces to expand will expand the corresponding spans under seemingly random traces further down the list.
4. We have observed this unexpected behavior multiple times over the past week

**Expected behavior**
When expanding traces, corresponding nodes should appear directly under them. This behavior should be consistent when expanding multiple nodes

**Environment:**
Grafana Cloud (GCT) with metrics generator (span metrics, node graphs) and exemplars enabled. We also have ~6 trace tags mapped to span metrics. Traces are being provided via OTel collector.

**Additional Context**
Environment is Grafana Cloud (G10.x). I have non-public materials demonstrating this behavior if necessary for review. This issue is not always immediately visible when creating new dashboards, but over time after revisiting dashboards it is present.

**Comment by joey-grafana** [comment] 2023-08-25 11:59
Duplicate of https://github.com/grafana/grafana/issues/72070

**Closed by joey-grafana** 2023-08-25 11:59 UTC
Labels: area/tracing, datasource/Tempo
