### ISSUE TITLE
Explore / Builder / Aggregation: Error: "Maximum update depth exceeded" when adding Aggregation via Builder

### ISSUE THREAD

**Issue by henry-kuehl** [grafana/grafana#69649] opened 2023-06-06 14:31 UTC
### 
# What went wrong?

**What happened**:
I tried to add an aggregation to a Loki-query via Builder and then select a label to aggregate on and got a Javascript-error. Search was not executed.

**What did you expect to happen**:

Being able to select a label in Builder to aggregate on.

### 
# How do we reproduce it?

  - Use Safari 16.5 on MacOS and open [Grafana Play](https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22ingress-nginx%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) (this worked in Chrome)
  - Switch to Builder-Mode
  - Add an aggregation to the query by selecting it from the list, I used "Aggregations -> Sum"
  - Click on the "+ By Label"-option
  - Observe a javascript-error
```
An unexpected error happened
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Qe@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/5226.8f8087951654808d35d8.js:79:966
gu@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/5226.8f8087951654808d35d8.js:137:14526
div
Nt@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/5226.8f8087951654808d35d8.js:35:274
div
Nt@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/5226.8f8087951654808d35d8.js:35:274
ce@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/6196.63326dc52e52e05fe972.js:1:9801
div
Nt@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/5226.8f8087951654808d35d8.js:35:274
div
M@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/6196.63326dc52e52e05fe972.js:1:12073
div
@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/4712.69b61bf7ee7c213fc37e.js:58:5726
ht@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/4712.69b61bf7ee7c213fc37e.js:58:8016
div
Nt@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/5226.8f8087951654808d35d8.js:35:274
@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/5226.8f8087951654808d35d8.js:35:4972
@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/4712.69b61bf7ee7c213fc37e.js:87:564
$t@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/4712.69b61bf7ee7c213fc37e.js:87:3537
o@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/3175.3c4a84c2da40e268800e.js:1:192
f@https://grafana-assets.grafana.net/grafana/10.0.0-cloud.3.b04cc88b/public/build/3175.3c4a84c2da40e268800e.js:1320:185
d@
div
```

### 
# What Grafana version are you using?

Grafana v10.0.0-cloud.3.b04cc88b (4f5dbbbb36)

### 
### Is the bug inside a Dashboard Panel?

No, Explore-View

### Grafana Platform?

I use Grafana Cloud

### User's OS?

MacOS 13.4

### User's Browser?

Safari 16.5

### Is this a Regression?

Yes

**Comment by tonypowa** [comment] 2023-06-07 12:30
thank you for creating this issue @henry-kuehl 

could you also increase the log's verbosity to [debug](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#level) and note the errors? the issue is being redirected to the appropriate engineering team

More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

thank you

**Comment by gwdawson** [comment] 2023-07-26 13:54
fixed by https://github.com/grafana/grafana/pull/71966

**Closed by gwdawson** 2023-07-26 13:54 UTC
Labels: type/bug, datasource/Loki
