### ISSUE TITLE
[Bug] Brackets in Template Variables are send to Influx escaped 

### ISSUE THREAD

**Issue by JonasGutermuth** [grafana/grafana#8719] opened 2017-06-27 10:57 UTC
The replacement of template variables  is used in the two edit modes different. In the query mode (B) brackets are sendet escaped. The  normal mode (A) is working normal.

![image](https://user-images.githubusercontent.com/19645608/27583841-173407ce-5b36-11e7-847c-7095251aa8df.png)

**The GET-Request sendet to the backend is:**
http://localhost:8200/grafana/api/datasources/proxy/1/query?db=xxx&q=SELECT%20%22value%22%20FROM%20%22v%22%20WHERE%20%22p%22%20%3D~%20%2F%5E
(A) send(with)brackets
(B) send%5C(with%5C)brackets
%24%2F%20AND [...]

Information:
- Grafana version: 4.2 and 4.3.2
- Datasource: Influxdb
- OS: Ubuntu

**Comment by daniellee** [comment] 2017-06-27 18:02
Dupe of #7306 and #8012

**Closed by daniellee** 2017-06-27 18:02 UTC
