### ISSUE TITLE
problems caused by postgres datasource plugin renaming from grafana version 10.2.2 -> 10.2.3

### ISSUE THREAD

**Issue by tsgit** [grafana/grafana#80180] opened 2024-01-09 03:03 UTC
### What happened?

updating grafana from 10.2.2 to 10.2.3 via RPM https://dl.grafana.com/oss/release/grafana-10.2.3-1.x86_64.rpm
```
systemctl stop grafana-server && yum -y install ~thorsten/grafana-10.2.3-1.x86_64.rpm && systemctl start grafana-server
```
broke existing dashboards with the postgres datasource. The dashboards lost their datasource and showed no content.

There are some error messages in the grafana.log 
```
logger=plugins.backend.start t=2024-01-04T09:23:14.206213845-08:00 level=error msg="Could not start plugin" pluginId=postgres error="fork/exec /usr/share/grafana/public/app/plugins/datasource/postgres/_linux_amd64: no such file or directory"
logger=plugins.initialization t=2024-01-04T09:23:14.20629026-08:00 level=error msg="Could not initialize plugin" pluginId=postgres error="fork/exec /usr/share/grafana/public/app/plugins/datasource/postgres/_linux_amd64: no such file or directory"
```

In addition the rpm update left behind the directory
```
/usr/share/grafana/public/app/plugins/datasource/postgres
```
with several empty subdirectories. 

In the user interface for Connections two plugins are shown for postgreSQL. 
![grafana-postgres](https://github.com/grafana/grafana/assets/766159/86be6e05-871f-43de-8a94-fc8813b24158)

### What did you expect to happen?

the renaming of the postgresql datasource plugin should have been seamless.
dashboards should continue to work
the old plugin directory should have been completely removed by rpm upgrade
the connections UI should only show one postgresql plugin

### Did this work before?

yes, things worked nicely in 10.2.2

### How do we reproduce it?

1. install grafana 10.2.2 oss from rpm
2. create a dashboard with postgresql datasource
3. update grafana to 10.2.3 oss via rpm
4. open the dashboard -- it will not show content
5. check leftover empty dir /usr/share/grafana/public/app/plugins/datasource/postgres/

### Environment (with versions)?

Grafana: 10.2.2 -> 10.2.3
OS: Red Hat Enterprise Linux Server 7.9 (Maipo)
Browser: latest Chrome or Firefox

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

postgresql

**Comment by gabor** [comment] 2024-01-10 13:45
thanks for reporting the issue!
it's strange, the `fork/exec /usr/share/grafana/public/app/plugins/datasource/postgres/_linux_amd64` error message makes it look as if grafana wanted to start postgres as an external plugin?

also, the fact that `/usr/share/grafana/public/app/plugins/datasource/postgres` contains empty sub-directories .. grafana does not write there, so i wonder what caused that.

@grafana/plugins-platform-frontend , could you take a look at this please? maybe you have some idea about what could have caused this. thanks!

**Comment by tsgit** [comment] 2024-01-11 01:04
grafana rpm for 10.2.2 has
```
/usr/share/grafana/public/app/plugins/datasource/postgres/CheatSheet.tsx
/usr/share/grafana/public/app/plugins/datasource/postgres/PostgresQueryEditor.tsx
/usr/share/grafana/public/app/plugins/datasource/postgres/PostgresQueryModel.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/README.md
/usr/share/grafana/public/app/plugins/datasource/postgres/configuration/ConfigurationEditor.tsx
/usr/share/grafana/public/app/plugins/datasource/postgres/configuration/useAutoDetectFeatures.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/datasource.test.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/datasource.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/img/postgresql_logo.svg
/usr/share/grafana/public/app/plugins/datasource/postgres/module.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/plugin.json
/usr/share/grafana/public/app/plugins/datasource/postgres/postgresMetaQuery.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/sqlCompletionProvider.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/sqlUtil.ts
/usr/share/grafana/public/app/plugins/datasource/postgres/types.ts
```
grafana rpm for 10.2.3 has
```
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/CheatSheet.tsx
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/PostgresQueryEditor.tsx
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/PostgresQueryModel.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/README.md
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/configuration/ConfigurationEditor.tsx
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/configuration/useAutoDetectFeatures.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/datasource.test.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/datasource.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/img/postgresql_logo.svg
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/module.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/plugin.json
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/postgresMetaQuery.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/sqlCompletionProvider.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/sqlUtil.ts
/usr/share/grafana/public/app/plugins/datasource/grafana-postgresql-datasource/types.ts
```

the datasource was simply renamed/moved. But the old directory was not removed in the rpm update.

This server has been updated for several generations of grafana rpms, and looking at older rpms there are more subdirectories in the /usr/share/grafana/public/app/plugins/datasource/postgres  space, e.g.
```
img/
partials/
specs/
```
I think that's what I saw as leftover empty subdirs after update to 10.2.3

**Comment by andresmgot** [comment] 2024-01-11 11:11
Hello,

I tried to reproduce the issue but I couldn't. This is what I have done:

1. Start a centos container.
2. Download the Grafana RPM for 10.2.2 and install it.
3. Create a postgres data source and a dashboard.
4. Download the Grafana RPM for 10.2.3 and install it.
5. Refresh the browser.

After that, I can still see the data in the dashboard.

It's true that there are some leftovers in `/usr/share/grafana/public/app/plugins/datasource/postgres` but those are empty folders:

```bash
$ find /usr/share/grafana/public/app/plugins/datasource/postgres/
/usr/share/grafana/public/app/plugins/datasource/postgres/
/usr/share/grafana/public/app/plugins/datasource/postgres/img
/usr/share/grafana/public/app/plugins/datasource/postgres/configuration
```

I am not sure why in your environment, it seems to be finding the old plugin `postgres` and trying to load it. Note that for a plugin folder to be loaded, it needs to have a `plugin.json` within it. Do you have more files in `/usr/share/grafana/public/app/plugins/datasource/postgres`? Does it help if you remove that folder and restart the server?

**Comment by tsgit** [comment] 2024-01-11 20:12
if there are no other reports of this problem, it may be due to this instance having been successively updated over the years starting from a fairly old version -- maybe there are some other leftovers. So let's close this issue as not reproducible.

I did remove /usr/share/grafana/public/app/plugins/datasource/postgres and restarted grafana.

The Connection tab still shows 2 postgres plugins.

**Comment by andresmgot** [comment] 2024-01-12 08:52
The Connections view list _datasources_, these are different configurations for connecting to Postgres. If you want to list plugins, you need to go to Home > Administration > Plugins and data > Plugins.

Having said that, after removing the folder, do you still see the problem with the broken dashboards? Do you still see errors in the logs or in the browser?

**Comment by andresmgot** [comment] 2024-01-31 11:22
@krisavi that should not happen, the old type should still work in dashboards as it's marked as an alias.

Can you provide some minimal steps to reproduce the issue? I was not able to reproduce it in the past. Also, does it help if you remove the old directories? (e.g. `/usr/share/grafana/public/app/plugins/datasource/postgres`)

**Comment by krisavi** [comment] 2024-02-19 09:50
Checked again and now they had disappeared. Maybe some odd cache issue. 

Previously I had 2 datasource for postgres when I tried to add new datasource, old broken one didn't have image. Newer one worked fine. 

Similar issue did not appear in our test environment. In production environment it caused issues. Grafana has been gradually upgraded since version 6 or 7, so there might be some permissions issue that is not easily reproducible. Also we use Grafana on 2 nodes in production environment, upgrading one, doing switchover to there and then upgrading other one. 

Dashboards that were using postgres did not work, as they tried to use datasource that was broken. When I tried to reconfigure data source it showed empty configuration for old ones. For me changing it in the config DB helped to solve the issue.

**Comment by andresmgot** [comment] 2024-02-20 08:14
Thanks for the update.

> Also we use Grafana on 2 nodes in production environment, upgrading one, doing switchover to there and then upgrading other one

This sounds like a potential cause, during the upgrade, the inconsistency between versions may have caused two different plugins to be reported (even though I am not sure why the dashboards may fail to load since an existing dashboard should work with both versions).

If it's a temporary problem, let me close this issue. Please reopen it if you find it again or if you find a way to reproduce it.

**Closed by andresmgot** 2024-02-20 08:14 UTC
Labels: needs more info, datasource/Postgres
