### ISSUE TITLE
Hover tooltip - "All series value"

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#24835] opened 2020-05-19 05:04 UTC
**What happened**: We selected the option for the Hover tooltip to show all the series value. Despite the fact that last data point for this series was over a month ago, when hovering on today's data for another series, we see the data point in the hover tooltip, despite the fact that there is no data for today.

**What you expected to happen**: It should only show the relevant series where there is data.

**How to reproduce it (as minimally and precisely as possible)**: Show two data series on the same graph, one with data from last week, one with data for this week, and select in the timepicker one month, and see what the hover shows you.

**Anything else we need to know?**: No

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: SQL Server
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome 8
![AllSeries](https://user-images.githubusercontent.com/1325158/82286838-5dc4fb00-99a7-11ea-9910-45ad21375424.png)

- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2020-05-19 07:56
duplicate of https://github.com/grafana/grafana/issues/6946

**Closed by torkelo** 2020-05-19 07:56 UTC
