### ISSUE TITLE
Wrap SingleStat Panel in Link

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#30563] opened 2021-01-22 19:28 UTC
**What would you like to be added**:

Currently, we can have links in two ways. One is "Link" option displayed on the upper left corner of a panel. The other one is "Data Link" option which is a pretty useful.

I want something simple just for better looking and better user experience. I've want to create a home page using single stat panel with names and "random walk" data and use the panels as buttons to navigate dashboards.

Let's say I have dashboards named, alpha, bravo, charlie, ... Here is my simple home page.

![image](https://user-images.githubusercontent.com/43188411/105536393-52c62580-5d01-11eb-9db2-ce29da0febf5.png)

Can we set the panel a link to go the related page when clicked on it with out data link pop up menu or upper-left corner? Directly on click.

**Why is this needed**:

I think, this link approach will be better than the existing ones for creating dummy panels and use them as buttons.

**Comment by torkelo** [comment] 2021-03-04 08:59
duplicate of https://github.com/grafana/grafana/issues/26805

**Closed by torkelo** 2021-03-04 08:59 UTC
Labels: area/dashboard/data-links, area/panel/stat
