### ISSUE TITLE
New Time Range Selector is Bad UI

### ISSUE THREAD

**Issue by crazyscience** [grafana/grafana#18447] opened 2019-08-08 08:30 UTC
The new design for the time range selector lacks heirarchy or visual queues necessary to quickly navigate changes between time ranges. The previous version of the time range selector was a far, far better alternative and should be reinstated.

**Comment by marefr** [comment] 2019-08-08 08:46
Duplicate of #17802

**Comment by marefr** [comment] 2019-08-08 08:47
Please continue feedback in that issue.

**Closed by marefr** 2019-08-08 08:47 UTC
