### ISSUE TITLE
Elasticsearch provisioning ignores esVersion and pattern/interval.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [grafana/grafana#28063] opened 2020-10-06 15:34 UTC
```
appVersion: 1

datasources:
- id: 3
  orgId: 1
  name: Elasticsearch
  type: elasticsearch
  typeLogoUrl: "public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg"
  access: proxy
  url: "http://elasticsearch:9200"
  password: ""
  user: ""
  database: "[fluentd-]YYYYMMDD"
  basicAuth: false
  isDefault: false
  jsonData: 
    esVersion: "7.0+"
    interval: "Daily"
    logLevelField: ""
    logMessageField: ""
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"
  readOnly: false
```

Both esVersion and interval are ignored.

**Comment by aknuds1** [comment] 2020-10-06 17:39
Is this a duplicate of #28062?

**Closed** 2020-10-07 08:39 UTC
Labels: needs more detail, type/duplicate

**Comment by andrew-pickin-epi** [comment] 2020-10-07 13:10
appVersion: 1

datasources:
- id: 3
  orgId: 1
  name: Elasticsearch
  type: elasticsearch
  typeLogoUrl: "public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg"
  access: proxy
  url: "http://elasticsearch:9200"
  password: ""
  user: ""
  database: "[fluentd-]YYYYMMDD"
  basicAuth: false
  isDefault: false
  jsonData: 
    esVersion: 70
    interval: "Daily"
    logLevelField: ""
    logMessageField: ""
    maxConcurrentShardRequests: 5
    timeField: "@timestamp"
  readOnly: false


Setting as a integer also does not work. Also Interval is ignored.
