### ISSUE TITLE
Support template variables in "Filter data by value" transformation

### ISSUE THREAD

**Issue by jdbaldry** [grafana/grafana#74174] opened 2023-08-31 11:48 UTC
**Why is this needed**:
It allows a user to filter panel data by template variables.

I personally intend to use the feature to filter a Google Sheets data source table using a regular expression value for a template variable.

Specifically, given the custom template variable named `filter` with the value `KEY : REGEXP`, I would like to have the following transformation:

```json
{
  "id": "filterByValue",
  "options": {
    "filters": [
      {
        "config": {
          "id": "regex",
          "options": {
            "value": "${KEY:value}"
          }
        },
        "fieldName": "FIELD NAME"
      }
    ],
    "match": "all",
    "type": "include"
  }
}
```

I would expect the `options.filters.*.config.options.value` field to be subject to template variable interpolation.
The value used in the filter would then be `REGEXP` and not the literal string `${KEY:value}`.

**Comment by oscarkilhed** [comment] 2023-08-31 13:28
Duplicate of #25469

**Closed by oscarkilhed** 2023-08-31 13:28 UTC
Labels: type/feature-request

**Comment by jdbaldry** [comment] 2023-08-31 13:46
Thanks for spotting the duplication, my search through the issues was too specific and I missed the more general issue.
