### ISSUE TITLE
Grafana cannot  build  linux  .tar.gz file  in mac

### ISSUE THREAD

**Issue by xiaoshengMr** [grafana/grafana#27467] opened 2020-09-09 07:15 UTC
**What happened**:
 I develop  the grafana finished and want to build  the binary .tar.gz file which can run in centos and I find cannot build success   why grafana not support  cross compiling which can build in mac os and run in centos
**What you expected to happen**:
success build the binary .tar.gz file run in centos

the error is：
fork/exec /var/folders/8k/27d6_gln6sxd5gb39q3hgtww0000gn/T/go-build219819499/b001/exe/build: exec format error 

**Environment**:
- Grafana version: latest
- User OS & Browser:  mac

**Comment by aknuds1** [comment] 2020-09-09 07:21
Closing this as it's not a bug report, but rather a support request. Please seek support in the community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io).

**Closed by aknuds1** 2020-09-09 07:21 UTC
