### ISSUE TITLE
graph-legend-series increase font size

### ISSUE THREAD

**Issue by vldslvmgy** [grafana/grafana#16209] opened 2019-03-25 17:00 UTC
Greetings, I am facing an issue with a font-size for graph-legend-series. 

I recently upgraded to a version 6.0.2 and need to enlarge the font of those fields. I used the text panel with a type html before. But it seems that the functionality is no longer supported. Thus, I was wondering whether there is a way to enlarge those particular fields.

**Environment**:
- Grafana version: v6.0.2
- Data source type & version: Graphite
- User OS & Browser: Chrome

**Comment by marefr** [comment] 2019-03-25 17:47
Duplicate of #15883

**Comment by marefr** [comment] 2019-03-25 17:47
Please refer to v6 upgrade notes: http://docs.grafana.org/installation/upgrading/#upgrading-to-v6-0

**Closed by marefr** 2019-03-25 17:47 UTC
