### ISSUE TITLE
[Elasticsearch] Cannot perform Bucket Script on mutli queries

### ISSUE THREAD

**Issue by leezhmwty** [grafana/grafana#18313] opened 2019-07-31 08:21 UTC
I want to calculate the percentage by Bucket Script. As follows，just like this Elasticsearch request:
```
{
    "size": 0,
    "aggs": {
        "failed_percent": {
          "date_histogram": {
            "field": "metric_timestamp",
            "interval": "month"
          }, 
            "aggs": {
                "total_discerns": {
                    "filter": {
                        "term": {
                            "type": "all"
                        }
                    }
                },
                "failed_discerns": {
                    "filter": {
                        "term": {
                            "type": "failed"
                        }
                    }
                },
                "failed_percent_script": {
                    "bucket_script": {
                        "buckets_path": {
                            "failedCount": "failed_discerns>_count",
                            "totalCount": "total_discerns>_count"
                        },
                        "script": "params.failedCount / params.totalCount"
                    }
                }
            }
        }
    }
}
```
The "type" is a field and has three values, respectively 'succeed', 'failed', 'all'. The failure rate is obtained by the ES bucket_script. In the other words, i want to get the percentage of (type.failed count / type.all count).
By Grafana, i cannot use Bucket Script to get the results of two queries? As shown below:
![捕获](https://user-images.githubusercontent.com/26474116/62194492-8b0ad300-b3ac-11e9-9d42-507be8db4960.PNG)
Or is there any other ways to achieve my needs?
Thanks !

**Comment by aocenas** [comment] 2019-07-31 13:28
It should work if you add multiple metrics under one query and reference those in the variables:
<img width="1139" alt="Screenshot 2019-07-31 at 15 28 11" src="https://user-images.githubusercontent.com/1014802/62215764-d66eb280-b3a7-11e9-998e-8eeb99d62bfa.png">

**Comment by aocenas** [comment] 2019-07-31 13:32
Closing this is it is a question not a bug or feature request. It is better to ask questions in our [community forum](https://community.grafana.com/) where it is higher chance that someone form outside of grafana can respond. We try to keep only bugs and feature request in Github.

**Comment by aocenas** [comment] 2019-07-31 13:36
Sorry just realised you have different filter query in each, so this won't help with that case.

**Comment by aocenas** [comment] 2019-07-31 14:03
So I do not see any way to reference different query from the script query editor, you can only referenced existing metric in that single query. In that case I would say this should be a feature request to add that.

Though asking on https://community.grafana.com/ can be still valid, maybe somebody know of some workaround to this I do not see right now.

**Comment by leezhmwty** [comment] 2019-08-01 03:19
Maybe I can only change the field of ES document to achieve it. So, if Grafana can reference different queries from the script query editor, it will be easier.
Thank for your reply!

**Comment by leezhmwty** [comment] 2019-08-01 03:26
> So I do not see any way to reference different query from the script query editor, you can only reference existing metrics in that single query. In that case I would say this should be a feature request to add that.
> 
> Though asking on https://community.grafana.com/ can be still valid, maybe somebody knows of some workaround to this I do not see right now.

Maybe I can only change the field of ES document to achieve. So, if it can reference different query from the script query editor, it will be easier.
Thank for your reply!

**Comment by cpmoore** [comment] 2019-08-03 05:50
If the query editor let you use groupings in the bucket script, it would solve your problem, however since it does not I think the only way to do what you want in elasticearch is to add a number metric on the documents in elastic.

For instance if you create a field like `status_code` and set it to `1` for failed and `0` for success then you can add a metric for a `sum` aggregation of `status_code`.  That would give you a total of all the failed documents, then you can divide it by the count metric in the bucket script.

**Comment by leezhmwty** [comment] 2019-08-07 03:22
> If the query editor let you use groupings in the bucket script, it would solve your problem, however since it does not I think the only way to do what you want in elasticearch is to add a number metric on the documents in elastic.

The method you said is the same as I thought, although this method needs to modify the original ES document structure, but it can solve my problem.
Thank for your idea!

**Comment by oangit** [comment] 2020-02-10 12:21
@leezhmwty Have you found a solution to this problem? Can you share?

**Comment by DevMasterSoonToBe** [comment] 2020-07-15 06:00
> If the query editor let you use groupings in the bucket script, it would solve your problem, however since it does not I think the only way to do what you want in elasticearch is to add a number metric on the documents in elastic.
> 
> For instance if you create a field like `status_code` and set it to `1` for failed and `0` for success then you can add a metric for a `sum` aggregation of `status_code`. That would give you a total of all the failed documents, then you can divide it by the count metric in the bucket script.

**Sum** aggregation only adds up values that have _Number_ type in ES, so if you want to have multiple counts on Grafana and then perform bucket script it becomes difficult. Would be nice to have feature where we can perform bucket script with values from seperate queries.

**Comment by vivekgautam91** [comment] 2020-12-23 09:18
@leezhmwty ,Can you please update how this issue got resolved. I am also facing the similar issue, It would be great if you suggest the solution on this.

**Comment by ivanahuckova** [comment] 2021-01-27 10:04
This should be possible to do with transformation feature now https://grafana.com/docs/grafana/latest/panels/transformations/types-options/.

**Closed by ivanahuckova** 2021-01-27 10:04 UTC
Labels: area/datasource/frontend, datasource/Elasticsearch, type/feature-request
