### ISSUE TITLE
Can't edit query for datasource Elasticsearch on latest Google Chrome version

### ISSUE THREAD

**Issue by alessandroniciforo** [grafana/grafana#54980] opened 2022-09-09 13:38 UTC
**What happened**: while using Elasticsearch as a datasource I cannot type anything at the beginning or in the middle of a query in the "Explore" tab of Grafana or while editing a dashboard. Also, the placeholder text is not removed and re-added anytime the field is blank.
![See video attached](https://user-images.githubusercontent.com/6370696/189361168-ee60e913-73cc-421f-957a-a7a38fc91410.gif)

**What you expected to happen**: I can edit the query adding text at the beginning or in the middle of the query

**How to reproduce it (as minimally and precisely as possible)**:
- open Grafana
- configure a valid Elasticsearch datasource
- go to "Explore"
- select the Elasticsearch datasource
- click the Query text field
- start typing: you will notice that the placeholder text is not removed and the typed text is added at the end
- move the cursor at the beginning of the text and type again: you will notice that the first letter typed is added at the beginning and then the focus moves at the end of the string making editing this query impossible

**Anything else we need to know?**: this bug didn't appear until a recent upgrade of Google Chrome. On v8.0.7 this bug affected both Elasticsearch and Prometheus as datasource. As of v8.5.11 this is affecting only Elasticsearch.

**Environment**:
- Grafana version: 8.5.11
- Data source type & version: Elasticsearch 7.6.0
- OS Grafana is installed on: Alpine Linux v3.15.4 (inside a container)
- User OS & Browser: Mac OS / Google Chrome Version 105.0.5195.102 (Official Build) (arm64)
- Grafana plugins:
- Others:

**Comment by scherbakoviv** [comment] 2022-09-09 13:43
Same problem
Duplicate of #54942

**Comment by ivanahuckova** [comment] 2022-09-09 14:55
Fixed in https://github.com/grafana/grafana/pull/54566 which will be part of next (9.1.4) release.

**Closed by ivanahuckova** 2022-09-09 14:55 UTC
