### ISSUE TITLE
Grafana Web-UI not starting after update from 10.0.3 to 10.1.0 on raspberry pi

### ISSUE THREAD

**Issue by helgeschneider** [grafana/grafana#73833] opened 2023-08-25 13:19 UTC
### What happened?

Plugin missing module.js
https://community.grafana.com/t/grafana-not-starting-after-update-to-10-1-0/101993/14

### What did you expect to happen?

solve

### Did this work before?

Yes

### How do we reproduce it?

1. upgrade
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by evan-chaney** [comment] 2023-08-25 13:37
Probably the same issue as #73781

**Comment by helgeschneider** [comment] 2023-08-25 14:32
yes, i didn't find it. thanks.

**Comment by RaithChr** [comment] 2023-08-25 17:21
Same.. Update from 10.0.3 to 10.1.0 no WEB GUI; THX; 
Is there a work arround?

**Comment by BMerz** [comment] 2023-08-25 19:54
Workaround is a roll-back to the old version.
See https://github.com/grafana/grafana/issues/73781#issuecomment-1691980658

**Comment by usmangt** [comment] 2023-08-26 11:20
Seems like a duplicate of https://github.com/grafana/grafana/issues/73781

Therefore closing this one.

**Closed by usmangt** 2023-08-26 11:20 UTC
