### ISSUE TITLE
Panel title bar interferes with other panel menu.

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#32038] opened 2021-03-16 16:55 UTC
<img width="1552" alt="Screenshot 2021-03-16 at 16 52 39" src="https://user-images.githubusercontent.com/444037/111348463-2337f780-8678-11eb-953e-bf62dd829d95.png">

**What happened**:
Clicking panel menu bar (to get to explore, inspect), and the menu bar for a panel below it interferes with the menu.

**What you expected to happen**:

I should be able to select explore, inspect etc

**How to reproduce it (as minimally and precisely as possible)**:

Two panels, one on top of the other, not a lot of height so the menu is taller than the panel.

**Environment**:
- Grafana version: Grafana v7.5.0-14438pre (a1c7e0630d)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux 
- User OS & Browser: Chrome / Mac
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-03-16 19:15
duplicate of https://github.com/grafana/grafana/issues/24986

**Closed by torkelo** 2021-03-16 19:15 UTC
