### ISSUE TITLE
When the set variable has no value, a default value is given

### ISSUE THREAD

**Issue by zio-pzl** [grafana/grafana#27266] opened 2020-08-28 13:37 UTC
hello！
When I set a variable on the dashboard(the data source used is es) and there is no value in this variable, it is shown in the following figure.
![image](https://user-images.githubusercontent.com/49870898/91565925-829d1700-e975-11ea-9816-1b04c4a22e40.png)
The value returned by the last request must be empty
![image](https://user-images.githubusercontent.com/49870898/91566501-5f269c00-e976-11ea-80df-3182b929e01e.png)
So I would like to ask if you can give a default value to a variable when there is no value in the variable, so that I can access it successfully and at least read a little data

**Comment by torkelo** [comment] 2020-08-28 15:13
duplicate of https://github.com/grafana/grafana/issues/5970

**Closed by torkelo** 2020-08-28 15:13 UTC
