### ISSUE TITLE
User Defined Global Templating Variables

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#16797] opened 2019-04-28 00:21 UTC
**What would you like to be added**:

It would be great to be able to have user-set Global Templating variables additionally to built-in ones https://grafana.com/docs/reference/templating/

**Why is this needed**:

It would allow more flexible global configuration for dashboards.  For example in Prometheus you often use topN to limit number of series shown.   This number could be made user settable as some users prefer to see more data others to have cleaner graph.  Same  applies to many rate() intervals - for some users  computing 1min  moving avg rates makes sense for others 5min would work better.

**Comment by marefr** [comment] 2019-04-28 09:57
Duplicate of #1959

**Closed by marefr** 2019-04-28 09:57 UTC
