### ISSUE TITLE
Sort Graph Legend on based hidden columns 

### ISSUE THREAD

**Issue by dguendisch** [grafana/grafana#20165] opened 2019-11-04 19:04 UTC
**What happened**:
Wanted to sort the legend according to `current` values.
Sorting works fine as long as the `current` column is activated and shown, but breaks when the column is not shown.

**What you expected to happen**:
Sorting to work independent of whether the `current` column is shown or not.

**How to reproduce it (as minimally and precisely as possible)**:
I have this graph panel, ordering should be "all landscapes > canary > live >...", but the legend shows "all landscapes > canary > staging > ...":

![image](https://user-images.githubusercontent.com/30311254/68149293-f335fb80-ff3d-11e9-9c3d-1ef8f0110b92.png)

This is how the respective legend part of the panels json looks like:
```
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": true,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": false
      },
```

Now if I flip in the UI the show-current toggle, then sorting is suddenly correct:
![image](https://user-images.githubusercontent.com/30311254/68149424-2c6e6b80-ff3e-11e9-88d2-1e3f16ed0b7a.png)

If I toggle the current toggle again, the sorting is again wrong, exactly as in the first screenshot.

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Elasticsearch 6.8.3
- OS Grafana is installed on: Linux
- User OS & Browser: Mac & Chrome

**Comment by Dominik-K** [comment] 2020-06-25 12:01
Duplicate of https://github.com/grafana/grafana/issues/20165 (that issue is already on the backlog and has more votes).

**Comment by pkolyvas** [comment] 2021-07-26 16:40
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Closed by pkolyvas** 2021-07-26 16:40 UTC
Labels: area/panel/graph, type/feature-request

**Comment by electrofloat** [comment] 2023-08-18 15:52
https://github.com/grafana/grafana/issues/21962 - issues are duplicate of each other... jesus christ! 😠
