### ISSUE TITLE
Panel Editor. Page body resize + dropdown menu = infinite jitter

### ISSUE THREAD

**Issue by mutantcornholio** [grafana/grafana#23397] opened 2020-04-07 13:37 UTC
**What happened**:
In panel editor, if you scroll to the end of page, then use dropdown menu at the very bottom, then scroll down again, then select something from that dropdown to make page a little bigger again, you may experience infinite page up and down resizes.

Here's video with demonstration: https://mcornholio-s3.s3.us-east-2.amazonaws.com/Screen+Shot+2020-04-07+at+15.50.21.mov

**What you expected to happen**:
Dropdown lists should not lead to page resizes. 
If dropdown menu doesn't fit on the screen, it should be moved up, instead of making page bigger and forcing user to scroll page down.

**Environment**:
- Grafana version: Grafana v6.4.4 (092e514)
- Data source type & version: any
- OS Grafana is installed on: hardly relevant
- User OS & Browser: MacOS, Chrome

**Comment by jongyllen** [comment] 2020-04-07 14:23
Hi, thanks for submitting this.
Would you mind trying on latest version of Grafana as well (6.7.2) so we know it is still an issue?

**Comment by mutantcornholio** [comment] 2020-04-09 10:45
It's there on play.grafana.org (6.7.1). Will it do?

**Comment by jongyllen** [comment] 2020-04-09 11:45
Yes, I could reproduce it as well. Thank you for reporting it.

**Comment by dprokop** [comment] 2020-06-09 11:25
@mutantcornholio can you please confirm this issue is still present in 7.0?

**Comment by mutantcornholio** [comment] 2020-06-09 11:28
Yep, still there

**Comment by kaydelaney** [comment] 2021-07-20 14:58
Still present in 8.0.6

**Comment by natellium** [comment] 2021-11-17 17:17
This seems to be fixed in 8.2.4 as the dropdown now opens upwards. Closing this issue.

**Closed by natellium** 2021-11-17 17:17 UTC
Labels: type/bug, area/panel/common
