### ISSUE TITLE
OAuth: 500 / confusing errors when OAuth flows fail

### ISSUE THREAD

**Issue by robx** [grafana/grafana#26824] opened 2020-08-06 08:08 UTC
**What happened**:

Got a scary unhelpful error

> login.OAuthLogin(missing saved state)
> Check the Grafana server logs for the detailed error message.

when an OAuth cookie had expired during the OAuth login flow. (On grafana.com specifically, but it's likely a more general issue.)

Server log extract:

```
t=2020-08-05T12:25:19+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/grafana_com status=500 remote_addr=x.x.x.x time_ms=0 size=1743 referer=https://grafana.com/
```

The same error occurs if I block cookies from the Grafana instance.

**What you expected to happen**:

A friendly error saying that something went wrong, ideally mentioning cookies.

On the backend, no 500 error, this doesn't seem like a 500 error.

**How to reproduce it (as minimally and precisely as possible)**:

To just trigger the error, visit `<instance>/login/<connector>?code=xxx&state=yyy`.

To simulate the actual cookie expiration, try to log in with a non-pre-authorized OAuth provider, then when you've been redirected to the provider and asked to authorize, first delete cookies for the Grafana instance. (Or wait for the cookie to expire.)

**Environment**:
- Grafana version: 7.1.1

**Comment by aknuds1** [comment] 2020-08-06 08:38
Thanks for reporting the issue, we will look into it when time allows.

**Comment by Webbeh** [comment] 2020-12-10 11:33
I have a similar issue.

Grafana 7.3.4, no web proxy, port 3000, under a domain with HTTPS enabled and correct certificates.

We include dashboards in iframes with "&kiosk". The master website has Auth0 authentication live and working properly. Grafana has auth0 authentication with the same tenant/application.

Both the master webpage and the grafana root_url have the same domain (main is "www.xxxx.yyy", grafana is "grafana.xxxx.yyy:3000"), both HTTPS.

When logging with auth0 on the master website, the iframed grafana gives the "missing saved state" 500 error.
If we then open grafana in a new tab, not in an iframe, grafana opens without prompting for an user/password, and takes the correct auth0 token that we just generated from the previous page.

If we then refresh the master page, grafana displays correctly inside iframes as well after showing the window first.

I get an additional error in Firefox's, just after getting the "missing saved state" error message :
![image](https://user-images.githubusercontent.com/1530837/101766660-64ea5c80-3ae3-11eb-8ea6-6c17b0728b4e.png)

If I try to go to the /login/generic_oauth page with the code and state that I see in Firefox network monitor, I get exactly this : 
![image](https://user-images.githubusercontent.com/1530837/101766947-d75b3c80-3ae3-11eb-99be-e26f091c0104.png)


...However, if I remove "code=xxxxx" and only keep the "state" variable, grafana shows correctly and the session cookie is set properly.

This is very strange.

**Comment by Webbeh** [comment] 2020-12-19 10:21
Any hint on the cause of this?

**Comment by Webbeh** [comment] 2021-02-08 14:45
I still have the same problem after trying : 
- using a reverse proxy with Grafana
- http2 enabled or disabled in the grafana server and in the iframing server

**This issue only shows in Firefox (desktop AND mobile/fenix) at the moment. Chrome works fine.**

**Comment by liudhzhyym** [comment] 2021-09-23 08:31
Any news  about this question?

**Comment by kminehart** [comment] 2022-06-02 21:20
@NeckBeardPrince this is almost always an issue with a misconfigured oauth client.

This issue is regarding the poor error message whenever these kinds of issues occur.

**Comment by Jguer** [comment] 2022-10-31 09:01
non-pre-authorized OAuth provider endpoints are not accessible anymore when they are not configured.

We've also done a series of changes improving cookie handling and message display.

Closing this issue. Feel free to submit a new issue on any error messages related to oauth that aren't communicated to the user but should

**Closed by Jguer** 2022-10-31 09:01 UTC
Labels: type/bug, area/auth, prio/low, area/backend
