### ISSUE TITLE
Nested Folders: Cannot move to folders with same name

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#72473] opened 2023-07-27 18:27 UTC
### What happened?

I've enabled the `nestedFolders` feature and created several subfolders (e.g. App1/Prod, App2/Prod, App3/Prod).

When trying to move existing dashboards into these subfolders, the Move page shows many folders with the same name (e.g. Prod), instead of the full path to that folder, which makes it hard to know which subfolder to move the dashboard to.

### What did you expect to happen?

The `Folder name` dropdown would show the full path for subfolders (e.g. `Parent > Subfolder`).

### Did this work before?

N/A

### How do we reproduce it?

1. Create folder A
2. Create subfolder X inside folder A
3. Create folder B
4. Create subfolder X inside folder B
5. Open the dashboard list
6. Select dashboard to move
7. Click Move button
8. See two folders in the list with the name X

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.0.2

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment] 2023-08-23 13:48
Hi @gtirloni,

Sorry for a bit of delay on this one. I just tried to reproduce it but after creating a new Dashboard Folder "A" but I cannot find an option in the UI which allow me to create a subfolder inside A.

Can you please share some more details (or better a small video screencast) as how you are doing this exactly?

**Comment by gtirloni** [comment] 2023-08-26 13:12
You have to enabled the `nestedFolder` [feature toggle](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/#experimental-feature-toggles).

I just noticed there is a new toggle `nestedFolderPicker` that might help with this issue but I haven't tried it yet.

**Comment by usmangt** [comment] 2023-09-12 12:32
So it looks like that this is now fixed as when naming X in folder B , I get this message:

`a folder or dashboard in the general folder with the same name already exists`


Closing this issue now as resolved. Please feel free to re-open it if you see any other changes

**Closed by usmangt** 2023-09-12 12:32 UTC
Labels: needs more info
