### ISSUE TITLE
arm64 docker images since 6.4.0 non-functional

### ISSUE THREAD

**Issue by burberger** [grafana/grafana#19931] opened 2019-10-21 10:24 UTC
**What happened**:
Starting a docker image on an arm64 platform fails with the following:
`/run.sh: line 80: /usr/share/grafana/bin/grafana-server: No such file or directory`

This was from starting `grafana/grafana-arm64v8-linux:6.4.3`.

**What you expected to happen**:
Docker container should start and run contained backend binary.

**How to reproduce it (as minimally and precisely as possible)**:
Run any docker image on docker registry from v6.4.0 onward on an arm64 platform.

**Anything else we need to know?**:
This appears to be related to the switch to an alpine base image.  I've tested a handful of images from v6.3.6 and prior, and they all function.  Best guess, this is related to cgo, as this switches from using glibc to musl in the target image.

**Environment**:
- Grafana version: latest
- Data source type & version: N/A
- OS Grafana is installed on: Docker
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment] 2019-10-21 11:33
Duplicate of #19585

**Closed by marefr** 2019-10-21 11:33 UTC
