### ISSUE TITLE
Make the General folder default permission editable 

### ISSUE THREAD

**Issue by andyallan** [grafana/grafana#12820] opened 2018-08-06 10:18 UTC
Hi folks

The default permissions on the General folder (which cannot be edited) are:

Admin (Role): Admin (locked, cannot be edited)
Editor (Role): Edit
Viewer (Role): View

More than happy for the default shipping permissions to be as above so as not to break anyone's existing set up, but I'd like the ability to change the default permissions on the General folder. 

From a least privileges perspective, I would like *my* default settings to be for the Admin (role) only.

Use case:

We are using Hosted Grafana, and we are looking at allowing some customers access to customer specific folders. So we **can** currently lock down those folders using "default folder permissions and Teams".

However, there are two scenarios that make the default, uneditable permissions of the General folder undesirable. 

1. It's the default folder where dashboards are saved. When you create a dashboard you cannot set permissions on it UNTIL the dashboard has been saved. You can of course save an empty dashboard, and then set permissions, but the whole thing is too prone to human error.

2. Plugins are saved to the General folder by default, and some (all?) complain about being moved to other folders (e.g. worldPing doesn't like this). So we can of course go in and change all the permissions, but again, it's prone to human error.

Both the scenarios above mean there is a potential for unwanted access to dashboards/information.

By allowing the default permissions of the General folder to be changed would prevent this.

Cheers

**Comment by marefr** [comment] 2018-08-06 11:34
Duplicate of #12327

**Closed by marefr** 2018-08-06 11:34 UTC
