### ISSUE TITLE
Panel groups

### ISSUE THREAD

**Issue by gretamosa** [grafana/grafana#22393] opened 2020-02-24 12:27 UTC
**What would you like to be added**:

Panel grouping capabilities

**Why is this needed**:
A picture is worth more than a thousand words: 

<img width="1334" alt="Captura de pantalla 2020-02-24 a las 13 13 55" src="https://user-images.githubusercontent.com/16796053/75151792-d0576f00-5707-11ea-86d1-f5c087f42426.png">

In terms of UX, you're going to think that left-side panel has higher values than the right-side but no so it is a bit confusing for any end-user. 

It's true that it only affects metrics with scalar values (no percentage) and dynamic y-axis calculation but they could be a lot in fact.

By grouping panels, they could share some attributes such as y-axis settings and more. A lot of ideas could be deployed on this way ;)

Related with #10916 but a bit more ambitious.

**Comment by torkelo** [comment] 2020-02-24 12:30
Duplicate of https://github.com/grafana/grafana/issues/4156  and https://github.com/grafana/grafana/issues/10916 , can you add your idea to one of those?

**Closed by torkelo** 2020-02-24 12:30 UTC

**Comment by gretamosa** [comment] 2020-02-24 12:41
Thnaks @torkelo, I didn't see #4156 but with both issues are enough ;)
