### ISSUE TITLE
Azure AD OAuth2 authentication shouldn't default to Viewer and should throw Unauthorized error instead

### ISSUE THREAD

**Issue by motoko89** [grafana/grafana#22741] opened 2020-03-11 21:47 UTC
**What happened**:
Following this https://grafana.com/docs/grafana/latest/auth/azuread/#enable-azure-ad-oauth-in-grafana and according to https://github.com/grafana/grafana/issues/21366#issuecomment-577026143 , if the users aren't assigned any app roles, they shouldn't be allowed to login.

However, in Azure AD, if the user has no app role, `Default Access` role will be assigned to them, and a token will be returned, instead of no token.

And on Grafana side `pkg\login\social\azuread_oauth.go`,  `extractRole()` default to return `Viewer` role.

**What you expected to happen**:
Because, Azure AD token has a group limit of 200, app role is suggested as a consistent way to authorize to certain groups of users. So if users have no assigned app role, `Unauthorized` error should be thrown instead

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v6.7.0-274a4322pre (5ad8a9722e)
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by motoko89** [comment] 2020-03-11 21:48
@twendt could you please take a look?

**Comment by twendt** [comment] 2020-03-12 14:55
You can set the `User assignment required?` to `yes` in the properties of the Enterprise Application in the Azure Portal. Then you won't get assigned to the `Default Access` role anymore and not get a token from the Azure AD.

**Comment by motoko89** [comment] 2020-03-12 17:44
> 
> 
> You can set the `User assignment required?` to `yes` in the properties of the Enterprise Application in the Azure Portal. Then you won't get assigned to the `Default Access` role anymore and not get a token from the Azure AD.

@twendt thanks. I tried that and users with role assigned to them get this error when signing in ` Application needs permission to access resources in your organization that only an admin can grant.`. If I turned the option to `No`, they can login. I already added API permissions `email`, `openid`, `profile`, `User.Read`. Do you know what admin consent API permission that I need for this to work?

**Comment by twendt** [comment] 2020-03-13 12:36
I had the same error right after the chnage as well yesterday. But when I tried a little later then it worked. I think that the change was probably not completely propagated in Azure AD. Can you please set the option again and wait for a few minutes?

**Comment by twendt** [comment] 2020-03-13 14:16
I am running into the same issue now. It seems that the Azure AD does not accept the app roles as user assignment.

**Comment by twendt** [comment] 2020-03-13 14:37
It seems that as soon as the configuration `User assignment required` that all permissions require an admin consent. This is not what we need here. I will see that I create a new PR so that if no role is assigned that the user will be rejected. Maybe I can even make this configurable.

**Comment by marefr** [comment] 2020-10-12 23:02
Duplicate of #23218

**Comment by marefr** [comment] 2020-10-12 23:03
I know this issue was opened before #23218, but that issue has more activity and comments and we would like to group everything related to this there.

**Comment by kyschouv** [comment] 2021-10-08 14:56
This functionality seems to have been missed for AzureAD when implementing for #23218. Could this issue to be re-opened until that's resolved? The properties are even showing up in the admin UI, though they don't appear to exist in the code for AzureAD.

**Comment by kyschouv** [comment] 2022-01-05 19:31
Any ETA on this? The associated PR has been open for over a month now without any movement.

**Closed** 2022-03-18 10:34 UTC
Labels: area/backend, area/backend/auth/oauth
