### ISSUE TITLE
Grafana: From Grafana container image "9.4.13" detected fields are not enabled in explore option

### ISSUE THREAD

**Issue by geevanakash** [grafana/grafana#72426] opened 2023-07-27 06:47 UTC
### What happened?

We recently upgraded to Grafana's recent helm version "6.58.5" with appversion "10.0.2" from our existing appversion "9.3.6".
After moving, we discovered that grafana was unable to display "Detected fileds" when we tried to search for loki logs under the explore option.

We tested a couple of additional versions, "9.4.13" and "9.5.5", and they all have the same problems.

So, within helm version "6.58.5," we utilised grafana appversion "9.3.6," and we can see the "Detected fileds."

Is there anything we need to enable or adjust with versions beginning with "9.4.13," or is this feature gone?

### What did you expect to happen?

We need grafana to have this "Detected fileds" feature with latest appversions.

### Did this work before?

yes, in app version 9.3.6.

### How do we reproduce it?

1. Install latest grafana helm.
2. Install Grafana loki
3. Add loki datasoure in grafana and try using the explore options for logs

### Is the bug inside a dashboard panel?

Not sure

### Environment (with versions)?

Grafana: 10.0.2
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment] 2023-07-31 10:38
Hi @geevanakash,

Thanks for opening this issue.

We will now start investigating this issue and will get back to soon.

**Comment by usmangt** [comment] 2023-08-23 13:43
Got delayed in updating this. I am not able to reproduce it so triaging it.

**Comment by svennergr** [comment] 2023-08-24 13:45
Hey @geevanakash,

this was indeed removed with Grafana 9.4 in https://github.com/grafana/grafana/pull/60448.

We recommend to use a parser like `logfmt` or `json` to get those fields back in the details section.

I'll close the issue, but if you think there's a bug, don't hesitate to comment or open a new issue - thank you!

**Closed by svennergr** 2023-08-24 13:45 UTC
Labels: area/explore, datasource/Loki, triage/needs-confirmation

**Comment by tillmannheigel** [comment] 2023-10-01 21:34
IMO this should actually be documented somewhere more explicitly.
