### ISSUE TITLE
Alerts from Prometheus don't get raised

### ISSUE THREAD

**Issue by claunia** [grafana/grafana#21108] opened 2019-12-15 20:30 UTC
**What happened**: Alerts return error: Error: tsdb.HandleRequest() error bad_data: parse error at char 123: missing unit character in duration

**What you expected to happen**: Alerts go thru configured and tested LINE webhook

**How to reproduce it (as minimally and precisely as possible)**: Create LINE webhook and use this panel:
```
{
  "datasource": "Prometheus",
  "alert": {
    "alertRuleTags": {},
    "conditions": [
      {
        "evaluator": {
          "params": [
            80
          ],
          "type": "gt"
        },
        "operator": {
          "type": "and"
        },
        "query": {
          "params": [
            "B",
            "5m",
            "now"
          ]
        },
        "reducer": {
          "params": [],
          "type": "avg"
        },
        "type": "query"
      }
    ],
    "executionErrorState": "alerting",
    "for": "5m",
    "frequency": "1m",
    "handler": 1,
    "message": "CPU usage too high for monitoring.claunia.com",
    "name": "CPU Used alert",
    "noDataState": "no_data",
    "notifications": [
      {
        "uid": "d7rcigfZz"
      }
    ]
  },
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "decimals": 2,
  "description": "Used CPU from a total available of 100%.\n- CPUThreshold:\n >Critical: > 90% Used CPU\n\nThere are 3 general states your CPU can be in:\n - Idle, which means it has nothing to do.\n - Running a user space program, like a command shell, an email server, or a compiler.\n - Running the kernel, servicing interrupts or managing resources.\n\nThese three meta states can be further subdivided. For example, user space programs can be categorized as those running under their initial priority level or those running with a nice priority. Niceness is a way to tweak the priority level of a process so that it runs less frequently. The niceness level ranges from -20 (most favorable scheduling) to 19 (least favorable). By default processes on Linux are started with a niceness of 0.",
  "editable": true,
  "error": false,
  "fill": 1,
  "fillGradient": 0,
  "grid": {},
  "gridPos": {
    "h": 10,
    "w": 12,
    "x": 0,
    "y": 21
  },
  "height": "260px",
  "hiddenSeries": false,
  "id": 2,
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "hideEmpty": false,
    "max": true,
    "min": true,
    "rightSide": false,
    "show": true,
    "sort": "max",
    "sortDesc": true,
    "total": false,
    "values": true
  },
  "lines": true,
  "linewidth": 1,
  "links": [
    {
      "title": "CPU",
      "url": "https://www.opsdash.com/blog/cpu-usage-linux.html"
    },
    {
      "title": "CPU",
      "url": "http://www.daniloaz.com/en/what-is-the-true-meaning-of-system-average-load-and-cpu-utilization-in-linux/"
    }
  ],
  "nullPointMode": "null as zero",
  "options": {
    "dataLinks": []
  },
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "expr": "100 - (avg by(env, job) (irate(node_cpu_seconds_total{mode=\"idle\",job=\"monitoring.claunia.com\",instance=\"localhost:9100\"}[$__range])) * 100) ",
      "format": "time_series",
      "intervalFactor": 1,
      "legendFormat": "CPU: {{job}}",
      "refId": "B"
    }
  ],
  "thresholds": [
    {
      "value": 80,
      "op": "gt",
      "fill": true,
      "line": true,
      "colorMode": "critical"
    }
  ],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "CPU Used",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "percent",
      "label": "",
      "logBase": 1,
      "max": 100,
      "min": 0,
      "show": true
    },
    {
      "format": "short",
      "logBase": 1,
      "max": null,
      "min": 0,
      "show": false
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Prometheus 2.14.0
- OS Grafana is installed on: Arch Linux
- User OS & Browser: Arch Linux + Chrome
- Grafana plugins: None
- Others: N/A

**Comment by marefr** [comment] 2019-12-16 15:56
$__range is not supported for Prometheus in alerting scenario currently.

**Comment by marefr** [comment] 2019-12-16 15:58
Duplicate of #17058

**Closed by marefr** 2019-12-16 15:58 UTC
Labels: area/alerting, datasource/Prometheus, type/bug
