### ISSUE TITLE
Logs graph in Explorer does not respect selected time range

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#32162] opened 2021-03-19 12:54 UTC
**What happened**:
Graph in Explorer does not correspond to the selected time range
![image](https://user-images.githubusercontent.com/50422107/111783424-45758380-88cb-11eb-8c90-d780fa599571.png)

**What you expected to happen**:
There will be no difference between Grafana 6 and Grafana 7

**Anything else we need to know?**:
Also seen on gif at this page - https://grafana.com/docs/grafana/latest/explore/logs-integration/#labels-and-detected-fields

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: Elasticsearch 7.11.1
- OS Grafana is installed on: docker
- User OS & Browser: Google Chrome on Windows 10

**Comment by M0rdecay** [comment] 2021-03-19 12:59
It looks like it has something to do with the point limit.
If make a small selection (~ 100 messages per period), graph returns to normal

**Comment by Elfo404** [comment] 2021-03-19 13:56
Hi @M0rdecay, thanks for the issue!
We are aware of this and we are doing some research on how to improve the experience. This is actually not related only to Elasticsearch.

closing this as duplicate of https://github.com/grafana/grafana/issues/28844

**Closed by Elfo404** 2021-03-19 13:56 UTC
