### ISSUE TITLE
MySQL data source: Non-standard port is not working

### ISSUE THREAD

**Issue by direk** [grafana/grafana#24587] opened 2020-05-12 15:09 UTC
**What happened**:
MariaDB ("kind of" MySQL on 3307 port) connection not working.

**What you expected to happen**:
Cannot add new MySQL data source that uses non-standard port.

**How to reproduce it (as minimally and precisely as possible)**:
Configure new MySQL data source, use IP:PORT <- this will show error message, as MariaDB by default uses 3307 port and have to be specified manually. While configuring host without :PORT it is parsed correctly.

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 7-beta3
- OS Grafana is installed on: synology / docker

**Comment by ivanahuckova** [comment] 2020-05-13 08:57
@marefr I have tested this out. Even if we use different port, it still results in `dial tcp [::1]:**3306**: connect: connection refused`. 
![image](https://user-images.githubusercontent.com/30407135/81792323-2f0ed680-9508-11ea-82c0-2b27119e1a1a.png)

**Comment by ivanahuckova** [comment] 2020-05-13 09:05
Hello @direk, can you confirm that you are not using provisioned data source? Provisioned data source can not be saved, even though you can change it in UI, but it is not going to be saved. For non-provisioned data source it seems to be working.

**Comment by aknuds1** [comment] 2020-05-13 09:07
Can you please paste the error you're getting?

**Comment by aknuds1** [comment] 2020-05-13 09:13
@direk @ivanahuckova I think this could be a duplicate of #24387.

**Comment by aknuds1** [comment] 2020-05-13 09:33
Closing this as a most likely a dup of #24387. You can try our master branch to verify that the issue is solved for you :)

**Closed by aknuds1** 2020-05-13 09:33 UTC
Labels: area/backend/db/mysql, needs more detail
