### ISSUE TITLE
Restored dashboard moved into the “General” - folder

### ISSUE THREAD

**Issue by gitgia** [grafana/grafana#13169] opened 2018-09-06 05:49 UTC
Hi, I have a following problem when I restore the dashboards:

### What Grafana version are you using?
5.2.0
### What datasource are you using?
InfluxDB 1.5
### What OS are you running grafana on?
Docker
### What did you do?
Restored a backup of a dashboard in a folder.
### What was the expected result?
Earlier version of the dashboard is restored in the same folder.
### What happened instead?
Earlier version of the dashboard is restored in the "General" folder. It has to be moved back to the original folder via "Manange Dashboards".

Thanks!

**Comment by marefr** [comment] 2018-09-06 09:15
Duplicate of #12926

**Closed by marefr** 2018-09-06 09:15 UTC
