### ISSUE TITLE
Transform: negative-Y with the timeseries graph panel

### ISSUE THREAD

**Issue by N3v3R3nD** [grafana/grafana#35461] opened 2021-06-09 19:27 UTC
**What would you like to be added**:
Transform: negative-Y with the timeseries graph panel

**Why is this needed**:
It was a feature of the old graph. but does not work in the new axis display options

**Comment by leeoniya** [comment] 2021-06-09 19:43
Duplicate of https://github.com/grafana/grafana/issues/30365

please upvote that one

**Closed by leeoniya** 2021-06-09 19:43 UTC
