### ISSUE TITLE
Repaint whole log area when scrolling the mouse in explore

### ISSUE THREAD

**Issue by yandingkang** [grafana/grafana#43261] opened 2021-12-17 08:38 UTC
**What happened**:
After logs were displayed in explore window, when I scroll the mouse,almost the whole page will be repainted.If the log number is large,the log area will also be large,causing the UI performance become very slow.
**What you expected to happen**:
Once the result was shown on chrome, the logs area should not be repainted when scrolling the mouse.
**How to reproduce it (as minimally and precisely as possible)**:
1.Open Grafana Explore
2.Select Loki datasource
3.Type a query which will display a large amount of logs e.g 10000lines
4.Open chrome's develop tool
5.Click 'Scrolling performance issues'
6.Find 'repaints on scroll'  area in the web page
7.Click 'Paint flashing' in chrome
8.Find the whole page repainted
**Anything else we need to know?**:
I used this website  'https://play.grafana.org' to test.
**Environment**:
- Grafana version: Grafana v8.3.3 (30bb7a93c)
- Data source type & version: Loki
- OS Grafana is installed on: 
- User OS & Browser:  Win10,Chrome Version96.0.4664.110
- Grafana plugins:
- Others:
![screenshot](https://user-images.githubusercontent.com/76470592/146514716-609e3b0e-0cb8-43fd-bd28-3fc61d1c3212.png)

**Comment by aocenas** [comment] 2022-01-14 11:56
Don't have exactly the same thing but the cause seems to be our custom scroll bars and scroll handling.

With native scrolling, the logs rows aren't really painted during the scroll. So when you scroll fast you just see blank space and only when you slow down a bit do things get painted. Which is much more smooth.

With the custom scrollbars, it seems like the paint is happening during the scroll which then staggers the scroll and that is slower and choppier.

@torkelo as far as I know the custom scrollbars (react-custom-scrollbars-2) are used for styling, is there any other functionality that they provide?

**Comment by torkelo** [comment] 2022-01-14 15:47
The main reason is that they are overlayed. 

Strange that they are causing repaints, they are native scrollbars under the hood , just hidden

**Comment by aocenas** [comment] 2022-01-14 16:20
@torkelo 
> The main reason is that they are overlayed.

Do you mean they are rendered over the content and so obscure it when visible? Is that important for layout (ie they don't change the widths I assume)?

Not sure how native they are. Seems like there still is some code doing some updating in `requestAnimationFrame`. I assume that forces the paint during scroll or something like that. Also question how much is browser dependant (I tried on Linux + Chrome)

**Comment by leeoniya** [comment] 2022-01-15 00:06
`scrollbar-gutter` is supported in Chromium 94+ and soon in Firefox 97 [1], maybe then Safari will finally begin to move on it [2].

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter

[1] https://groups.google.com/a/mozilla.org/g/dev-platform/c/pAh2tDhBFOU/m/wQBctGKCCwAJ?pli=1
[2] https://bugs.webkit.org/show_bug.cgi?id=167335

**Comment by torkelo** [comment] 2022-01-15 00:11
> Do you mean they are rendered over the content and so obscure it when visible? Is that important for layout (ie they don't change the widths I assume)?

I mean does not take up space (like osx native scrollbars), mostly important internal panel scrollbars and other places where the space a full native scrollbar take is very a lot, and when for the centered pages, the native scrollbar (on non osx systems) will cause the page to jump around depending on if there is a scrollbar or not

**Comment by leeoniya** [comment] 2022-01-15 00:42
i have a creative "solution" PoC that might suffice until `scrollbar-gutter` has more general support:

![Peek 2022-01-14 18-41](https://user-images.githubusercontent.com/43234/149601861-0950cc3d-5275-4509-af0f-fe4d7cf04bb9.gif)

https://jsfiddle.net/euLwjq02/1/

```html
<div id="parent" style="height: 350px;">
  <div id="child1">
  Lorem Ipsum is simply dummy text of the printing and typesetting industry. The following example creates a thin (10px wide) scrollbar, which has a grey track/bar color and a dark-grey (#888) handle:
  </div>
  <div id="child2">
    moo cow
  </div>
</div>
```

```css
/* width */
::-webkit-scrollbar {
  width: 16px;
}

/* Track */
::-webkit-scrollbar-track {
  background: rgba(0, 0, 0, 0.3);
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #888;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #555;
}

#parent {
  background: blue;
  width: 300px;
  overflow-y: auto;
  overflow-x: hidden;
}

#child1 {
  background: orange;
}

#child2 {
  background: red;
  width: 100px;
  height: 200px;
}

```

```js
function isScrollbarVisible(el) {
  return el.scrollHeight > el.clientHeight;
}

let p = document.getElementById("parent");
let ps = p.style;

let c1 = document.getElementById("child1");

let height = 350;

let dir = 10;

let it = setInterval(() => {
  if (height == 350 || height == 200)
    dir *= -1
  
  height += dir;
  
  ps.height = height + "px";
  
  if (isScrollbarVisible(p)) {
    c1.style.marginRight = '-16px';
  }
  else {
    c1.style.marginRight = 0;
  }
}, 100);
```

**Comment by leeoniya** [comment] 2022-01-15 00:50
apparently the way to make the scrollbar semi-transparent is to set a png background image (opacity and rgba dont work)

https://stackoverflow.com/a/33686575

**Comment by KingSora** [comment] 2022-11-14 10:24
@torkelo @aocenas 

I've experienced similar issues in my company while using Grafana, and was wondering if you'd be open to switch out the current `react-custom-scrollbars-2` library with `overlayscrollbars`. I'm the author of this package and very confident that it would solve not only this but also many of the other issues reated to `scrollbars`, `scrolling` and `performance`. (`overlayscrollbars` is already used in production by spotify, storybook and many more)

**Comment by svennergr** [comment] 2023-01-19 13:12
fyi @grafana/explore-squad we are going to work on performance issues/repaintings in the logs panel dedicated in https://github.com/grafana/grafana/issues/60687. This issue here might however be something to be solved in Explore.

**Comment by matyax** [comment] 2023-04-12 12:12
From a Logs perspective, I didn't find anything to change or fix. Passing to @grafana/explore-squad

**Comment by ifrost** [comment] 2023-04-13 10:07
> fyi https://github.com/orgs/grafana/teams/explore-squad we are going to work on performance issues/repaintings in the logs panel dedicated in https://github.com/grafana/grafana/issues/60687. This issue here might however be something to be solved in Explore.

> From a Logs perspective, I didn't find anything to change or fix. Passing to https://github.com/orgs/grafana/teams/explore-squad

Logs squad is the owner of this component. Feel free to close the issue if it's resolved / won't be fixed.

**Comment by matyax** [comment] 2023-04-13 11:47
@ifrost Which component? I reassigned this issue because it seems to be related with Explore in general and not specific to any data source. E.g.

![imagen](https://user-images.githubusercontent.com/1069378/231749245-97671f5e-3b43-44fa-9d0e-a42e63f6bfd7.png)

**Closed** 2023-04-14 08:36 UTC
Labels: type/performance, needs investigation, area/explore
