### ISSUE TITLE
Login page does not inherit from AppTitle

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#25235] opened 2020-05-30 14:22 UTC
Hi,

With last Grafana 7.0.1.
Every page uses the `AppTitle` variable to set the page title.
However, the login page does not seem to use it.

Could you fix this bug please so that login page also uses `AppTitle` as its page title ?

Thank you 👍

**Comment by aknuds1** [comment] 2020-05-30 15:23
Why is this a bug exactly?

**Comment by benrubson** [comment] 2020-05-30 15:28
Thank you @aknuds1 for your response :+1:
You're right, I'm not sure the word "bug" is the most appropriate here in this case.
But I think that for consistency the login page title should inherit from `AppTitle`, as it's the case everywhere else ?
Thank you again !

**Comment by aknuds1** [comment] 2020-05-30 15:49
Why does that even matter? Does it have any practical consequence?

**Comment by benrubson** [comment] 2020-05-30 15:54
Yes, when we update the `AppTitle` value in the `.js` file, it get updated everywhere but on the login page :)

**Comment by aknuds1** [comment] 2020-05-30 16:11
Closing as this is not a bug. If you want to change it I suggest to make a PR.

**Closed by aknuds1** 2020-05-30 16:11 UTC
Labels: area/frontend, type/question
