### ISSUE TITLE
[Feature Request] Gauge with more thresholds

### ISSUE THREAD

**Issue by phlupp** [grafana/grafana#6441] opened 2016-11-01 11:56 UTC
* **I'm submitting a ...**

- [x] Feature request

I have an Singlestat with Gauge and thresholds. The value is the voltage of a battery so normally i need more thresholds.

It would be nice if there can be defined upper and lower thresholds. May be with 4 thresholds values like:

8,10,13,15 the result would be: <8 red, 8-10 orange, 10-13 green, 13-15 orange, >15 red

![gauge](https://cloud.githubusercontent.com/assets/6304863/19888861/a609f12c-a031-11e6-848f-fa6914f0ff99.PNG) ![gauge1](https://cloud.githubusercontent.com/assets/6304863/19888978/7f8f613e-a032-11e6-98ea-a013ddcebab1.PNG)

Garafana v3.1.1 a4d2708

**Comment by pfmd86** [comment] 2016-11-01 11:59
Great idea. It would be a nice feature to have more than 2 thresholds!

**Comment by bmagistro** [comment] 2016-11-01 12:02
I'm in favor but this sounds similar to #3608

**Comment by torkelo** [comment] 2016-11-01 12:24
closing due to duplicate of https://github.com/grafana/grafana/issues/3608

**Closed by torkelo** 2016-11-01 12:24 UTC
