### ISSUE TITLE
User not asked to reauthenticate when oauth token has expired

### ISSUE THREAD

**Issue by skadefro** [grafana/grafana#31967] opened 2021-03-14 09:57 UTC
**What happened**:
Once an oauth token expires, the user is not forced to login again, but grafana seem to know the token has expired since it stops sending the authentication header for data sources that has oauthPassThru enabled.
**What you expected to happen**:
The user should be re authenticated, or grafana should at least send the expired token when oauthPassThru is enabled
I would prefer the user was forced to sign in again, but if that is not possible, then at least send the invalid token in the authentication header
**How to reproduce it (as minimally and precisely as possible)**:
Configure grafana for oauth, 
Create a datasource that supports enabling oauthPassThru and then enable it
sign in and validate that grafana is sending the authentication header as expected.
wait for the token to expire.
User can still access grafana and all dashboards, but grafana stops sending the authenication header. 
**Environment**:
- Grafana version: Tested with different version, but currently on v7.5.0-12932
- Data source type & version: I'm testing with my own data souce, but doesnt matter, this is related to grafana
- OS Grafana is installed on: Docker ( using grafana/grafana image )
- User OS & Browser: Windows 10, chrome

**Comment by marefr** [comment] 2021-03-25 11:54
Duplicate of #12131

**Closed** 2021-03-25 11:55 UTC
Labels: needs investigation
