### ISSUE TITLE
An option to switch a panel off (to not to query a data source).

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#28141] opened 2020-10-09 13:22 UTC
**What would you like to be added**:
I have got a bunch of related panels within a dashboard, all displaying data on most occasions.
It would be nice to have an option to switch a (selected) panel off so it does not query a data source.

Without going to "edit panel", hence this option should be a visible "property" of the panel.

Persistence (a cookie?) would be the icing on the cake.

**Why is this needed**:
When I need to track down some exceptional behaviour, one, particular panel of the dashboard is mostly enough (hopefully) when exploring data to solve the problem.

**Comment by aknuds1** [comment] 2020-10-09 13:22
Duplicate of #28140.

**Closed by aknuds1** 2020-10-09 13:22 UTC

**Comment by hawran** [comment] 2020-10-09 13:27
Oops, some glitch with my web browser.
Sorry for that.
