### ISSUE TITLE
Dropdown dashboard list not displaying the dashboard names in the right direction

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#33114] opened 2021-04-19 09:13 UTC
**What happened**:
I've updated from the version 7.4.x to the 7.5.4, and every dashboard link as dropdown are not displaying in the correct way they should be. The names normally display from the right to the left to be able to read the entire dashboard names when the dropdown is expended, but since i've updated, the names are now displayed in the wrong direction.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a dashboard link as a dropdown with multiples entry inside the dropdown
- Open the drop down and you should get the same issue i've got

**Visual reproduction of the issue**
![github_issue_dropdown](https://user-images.githubusercontent.com/33425208/115211742-281d1a80-a100-11eb-8402-24a4a10fd137.gif)

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: Elasticsearch 7.12.0
- OS Grafana is installed on: CentOS 7 1804
- User OS & Browser: Edge 90.0.818.41

**Comment by hugohaggmark** [comment] 2021-04-19 11:42
Reproduced here https://play.grafana.org/d/c_knysXGz/dropdown-dashboard-list-not-displaying-the-dashboard-names-in-the-right-direction-33114?orgId=1

**Comment by jackw** [comment] 2021-05-31 07:09
Duplicate of #30190 and fixed with #34909

**Closed by jackw** 2021-05-31 07:09 UTC
Labels: area/dashboard/links, type/bug
