### ISSUE TITLE
Alerting: sqlstore.transactions complains that database is locked on first start

### ISSUE THREAD

**Issue by antonincms** [grafana/grafana#58545] opened 2022-11-09 19:23 UTC
**What happened**:

When deploying a grafana 9.2.x using the helm chart, with enough dashboards and unified_alerting enabled there are a lot of `Database locked` logs, that can lead to the pod crashing.

```
logger=provisioning.alerting t=2022-11-09T17:47:44.93629362Z level=info msg="starting to provision alerting"
logger=provisioning.alerting t=2022-11-09T17:47:44.93631956Z level=info msg="finished to provision alerting"
logger=grafanaStorageLogger t=2022-11-09T17:47:45.031203864Z level=info msg="storage starting"
logger=ticker t=2022-11-09T17:47:45.031559917Z level=info msg=starting first_tick=2022-11-09T17:47:46Z
logger=http.server t=2022-11-09T17:47:45.131396968Z level=info msg="HTTP Server Listen" address=[::]:3000 protocol=http subUrl= socket=
logger=sqlstore.transactions t=2022-11-09T17:47:45.431106473Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=0
logger=sqlstore.transactions t=2022-11-09T17:47:45.531112667Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=1
logger=sqlstore.transactions t=2022-11-09T17:47:46.13112329Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=2
logger=sqlstore.transactions t=2022-11-09T17:47:46.941872624Z level=info msg="Database locked, sleeping then retrying" error="database is locked" retry=0
... crash of the container 
```

Even if it does not crash, sometimes it prints errors about failing to save a dashboard, which is not good either.

**What you expected to happen**:

Have the same behavior with or without unified_alerting enabled.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce this issue, i made a [values file](https://github.com/grafana/grafana/files/9973960/values.txt), which is not as efficient as our own set of values, since it seems this issues is proportional to the number of dashboars (and we have around 50). 

To reproduce the issue I added a bunch of dashboards and limited the requests and limits, you only need to install grafana with these values : `helm install grafana grafana/grafana -f testvalues.yaml -n monitoring --version v6.43.5`. On my cluster here what's happens (unfortunately the grafana does not crash there, but it happens on our side): 
![demo](https://user-images.githubusercontent.com/9219052/200909886-e3c93a8a-2505-4c5d-a9ff-1994c3dfd620.gif)

**Environment**:
- Grafana version: 9.2.4, but I cannot reproduce with 9.1.8.
- Data source type & version: N/A
- OS Grafana is installed on: N/A (kubernetes) 
- User OS & Browser: N/A
- Grafana plugins: N/A

**Comment by zuchka** [comment] 2022-11-16 02:46
Thanks for creating this issue, @antonincms 

this sounds like a duplicate of [this long-standing issue](https://github.com/grafana/grafana/issues/16638).

I'd check out [this most recent comment](https://github.com/grafana/grafana/issues/16638#issuecomment-1099212368)

**Comment by antonincms** [comment] 2022-11-16 10:06
@zuchka I've seen this issue, but for I am not sure it is related for the following reasons

- This issue relates to grafana 6.1, where we had no issues with grafana up to 9.1, only with 9.2
- For us the issue seems to vanish when enabling the unified alerting
- The tweak proposed in the last comment diminish the number of errors, but there are still some errors logs even with it, so I cannot ship 9.2 knowing that we could have provisioning issues

**Comment by antonincms** [comment] 2022-11-16 10:09
(so @zuchka should I actualize the long-standing issue with all my unique problem, or should not we reopen this issue ?)

**Comment by zuchka** [comment] 2022-11-16 13:23
sure thing @antonincms let's reopen. A few more questions:

> when enabling the unified alerting

Unified Alerting should be default by 9.2. Can you share all your alerting-related configuration changes in grafana.ini?

Were you using legacy alerting previously? Just want to rule out any migration-related issues--apologies if I am not understanding you completely

**Comment by antonincms** [comment] 2022-11-16 14:10
Hello, 

> Unified Alerting should be default by 9.2. Can you share all your alerting-related configuration changes in grafana.ini?

I can confirm we are using the legacy alerting (since some of our teams still rely on on-dashboards alerts), we set the `unified_alerting.enabled` field to false in the grafana.ini part of the helm chart : 
```
grafana.ini:
  unified_alerting:
    enabled: false
```

> Were you using legacy alerting previously? Just want to rule out any migration-related issues--apologies if I am not understanding you completely

We were, but the issue I have also appears on brand-new deployments of the grafana helm chart. 

I have the impression it could be related to the migration making a lot of requests to migrate provisioned dashboards (we have 80 dating from grafana 5.x to 8.x), but what I don't understand is the fact that enabling unified alerting seemed to solve the problem.

**Comment by salavessa** [comment] 2022-11-17 18:29
Hi,

Just to add that I also experienced this issue on all my servers which run with `GF_UNIFIED_ALERTING_ENABLED=false`.

Can also confirm that everything works fine in `9.1.8`, the issue started happening in grafana `9.2.0` versions and is still there as of `9.2.5`.

Providing more info below which hopefully will help to better identify and sort the problem:
- we use the official grafana docker images and everything worked fine in all `9.2.x` versions so far, including alerts being triggered on all of our existing dashboards (all created before `9.2`) UNTIL the moment we had to update a dashboard with (legacy) alerts in it (we didn't try creating new dashboards so can't comment there)
- refreshing the browser page after we get the "save error" (due to `database is locked`) does show the updated dashboard BUT if the changes are related to a panel with alerts, those alerts don't seem to get triggered any longer (although you can still see them correctly configured/updated in the "Alert" section)
_Note_: we managed to get the broken alerts working again by rolling back to `9.1.8` and touching/saving the dashboard
- attaching [grafana-9.2-db-locked-saving-dashboard.log](https://github.com/grafana/grafana/files/10034226/grafana-9.2-db-locked-saving-dashboard.log) which show grafana startup and then `"database locked"` which corresponds to the action of saving a dashboard with panels which contained alerts (it happens every time we try to save the dashboard)

So the impression I get from this behavior is that the dashboard+alerts save process is made in two stages, a first one where the dashboard itself is saved successfully an then, and a second stage which fails creating/updating the alerts apparently due to a database lock.

Besides the above it was also noticed something different in the behavior of making a "read-only" dashboard editable (tested in firefox and chrome), and maybe has nothing to do with this issue (but also started happening in grafana `9.2.0`): when clicking the dashboard settings the layout is missing the left menu (which I guess it's fine if it's intentional) but the page doesn't reload once the button gets clicked, instead one needs to go back to the dashboard (via top-left arrow) and click the dashboard settings again to be able to see the "writable" dashboard sections and configs:
`9.1.x` <img src="https://user-images.githubusercontent.com/15344273/202518562-cb075f61-d53d-41ab-8f68-9ea7c9bdeb48.png" height="120"> vs `9.2.x` <img src="https://user-images.githubusercontent.com/15344273/202518822-2e72704a-70f4-406f-b3cb-ff66bba2c582.png" height="120">.

Thanks!

**Comment by armandgrillet** [comment] 2022-11-18 10:25
Thank you for the detailed information. Which database are you using with Grafana? SQLite?

**Comment by salavessa** [comment] 2022-11-18 10:47
@armandgrillet - yes we are (the default for the official docker image under `/var/lib/grafana/grafana.db`).

**Comment by yangkb09** [comment] 2022-12-02 15:27
Hey! 👋🏼 This looks like an alerting issue. I see it's on the Alerting team's board, so I'm going to remove this from ours 🙂.

**Comment by JohnnyQQQQ** [comment] 2023-01-27 10:41
Legacy Alerting has been deprecated since Grafana 9. Please upgrade to Grafana Alerting, which is not affected by this issue.

**Closed by JohnnyQQQQ** 2023-01-27 10:41 UTC
Labels: type/bug, area/alerting, area/backend/db
