### ISSUE TITLE
Time overlaps with legend

### ISSUE THREAD

**Issue by haizaar** [grafana/grafana#9791] opened 2017-11-06 03:56 UTC
Grafana 4.6.1 running on GKE. Chromium 62.0.3202.75 on Ubuntu 16.04 amd64. The datasource is Prometheus 2.0.0-rc.3.

When displaying graph on 1/3 of 27" screen, date/time values on X axle are displayed in two rows (time below date) and overlap with graph legend. Please see the below screenshots:

![image](https://user-images.githubusercontent.com/58201/32424392-4322893c-c300-11e7-8f91-251c728c0b9f.png)

![image](https://user-images.githubusercontent.com/58201/32424740-7bf94c30-c302-11e7-8012-29925370711b.png)

**Comment by torkelo** [comment] 2017-11-06 09:38
duplicate of https://github.com/grafana/grafana/issues/3155 

Does this happen frequently? Usually only happens extremely rarely for me and I usually need to resize the browser window to trigger it and a time range refresh or dashboard reload will fix it.

**Closed by torkelo** 2017-11-06 09:38 UTC
