### ISSUE TITLE
Enable support for custom s3 like endpoints for external image storage

### ISSUE THREAD

**Issue by gksinghjsr** [grafana/grafana#15445] opened 2019-02-14 15:35 UTC
Grafana supports s3 as a datasource for external image storage. However, it does not support custom S3 like storages, which are AWS S3 compatible.

**Comment by marefr** [comment] 2019-02-15 09:21
> like sotrages

Don't know exactly what you mean. Can you update the description with some more information? Thanks

**Comment by gksinghjsr** [comment] 2019-02-15 10:56
@marefr updated the description.

**Comment by marefr** [comment] 2019-02-15 12:17
Duplicate of #8157

**Closed by marefr** 2019-02-15 12:17 UTC
