### ISSUE TITLE
InternalLinking: Better architecture around linking datasources

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#29417] opened 2020-11-26 16:34 UTC
At this moment there are multiple features that are basically a data link to a query in a specific datasource (usually opened in Explore) like Derived Fields in Loki, Data Links in Elastic, Exemplars in Prometheus or Trace to Logs functionality.

Right now they are implemented by leveraging parts of DataLink which was aimed only at creating url links and so the code is messy because compared the normal Datalink, InternalLink needs:
1. Know the target datasource and how to create query.
2. Know how to actually open the link as if we see the link in Explore we open it as a second Explore split pane while in Dashboards we navigate to Explore. So we need both proper URL (also to open in separate tab) but also an optional function in Explore to run onClick.

Even though both things are implemented there are lots of issue with the current implementation:
1. We hard code lots of the features to target only specific data source types. For example Derived fields in Loki can only target specific tracing datasources which accept single trace ID as a query. The main issue here is that for user to be able to create proper query they basically need a proper queryEditor otherwise they would need to create a proper query as text/json which is not supper great UX. This would be similar to providing editor for template variables or annotation.
2. We need to pass a lot more information to data link related code and create 2 separate code paths for internal links and normal data links. Things like `getDataSourceSettingsByUid` is passed deep into `fieldOverrides` code because it's needed to create proper links. Similar with the onClick. This probably could be avoided with better separation of concerns and properly define links as either external/internal.

**Comment by gelicia** [comment] 2022-11-16 15:39
Duplicate of #55236

**Closed by gelicia** 2022-11-16 15:39 UTC
Labels: type/feature-request, prio/medium, type/refactor, area/explore, area/dashboard/data-links
