### ISSUE TITLE
Missing subpath on 'Sign In' navigation item behind proxy

### ISSUE THREAD

**Issue by Pherekles** [grafana/grafana#63355] opened 2023-02-15 07:06 UTC
**What happened**:

I'am driving several Grafana instances behing an proxy (nginx) which works fine for all versions < v9.3.1 After I tried updating one older instance to v9.3.6 I ran into an issue with the 'Sign In' item in the navigation. A click on it will end up in a 404 HTML error because the path behind the button is not correct - the subpath is missing here.
But I need to highlight that this just happen when Grafana is running on a subpath (e.g.: mydom.org/grafanaup) behind a proxy. If a subdomain (grafana.mydom.org) is configured I dont notice this issue. That means everything after the slash is ignored for the 'Sign In' navigation item.

When configuring the proxy, I have strictly followed the specifications of the Grafana documentation for years. Since it works without any problems for all other older versions, I rule out a misconfiguration here.

The issue:
![1](https://user-images.githubusercontent.com/47866553/218954854-e1f314c2-38cd-4c47-80d4-c499e81b46a6.png)

**What you expected to happen**:

My expectation is that the subpath I configured is used here same as on all other navigation items or links like the pictures below show. In my case 'grafanaup' is my configured subpath on the proxy and grafana.

![2](https://user-images.githubusercontent.com/47866553/218955466-faba63ca-1519-4439-a691-07dfd0b812fa.png)
![3](https://user-images.githubusercontent.com/47866553/218955469-acb13c5c-de07-42e0-88e3-45d0b591cce7.png)

**How to reproduce it (as minimally and precisely as possible)**:

Just setup a new Grafana instance with a version number after v9.3.1 and configure an proxy in front of it. The syntax of the URL to reach Grafana must setup in this way: [domain/hostname]/[subpath].

**Anything else we need to know?**:

This issue was already reported in the [Grafana forum](https://community.grafana.com/t/grafana-sign-in-navigation-item-misses-the-subpath-behind-proxy-but-other-nav-items-do-not/77260/5) but without an reference to an issue here.

**Environment**:

- Grafana version: 9.3.1, 9.3.6
- Data source type & version: indipendent
- OS Grafana is installed on: Windows Server 2019 Datacenter
- User OS & Browser: Windows 10; Microsoft Edge, Chrome, Firefox
- Grafana plugins: indipendent
- Others: -

**Comment by zuchka** [comment] 2023-02-15 22:13
/duplicate of https://github.com/grafana/grafana/issues/59767

looks like we might have to reopen that one. PLease add a comment to that thread

**Closed** 2023-02-15 22:14 UTC
Labels: type/duplicate
