### ISSUE TITLE
Alerting: Dashboard not auto saving when Legacy Alerting is used

### ISSUE THREAD

**Issue by bmnidhin** [grafana/grafana#75599] opened 2023-09-28 04:48 UTC
### What happened?

- Grafana legacy alert is not auto saving if we navigate away from edit panel. It was working earlier in Grafana v7 and other form elements such as panel title and description 
https://github.com/grafana/grafana/assets/11921692/51225363-71cb-4095-9c68-13a9f918aed3

### What did you expect to happen?

- Auto saving form states even if we navigate away from edit panel. 

### Did this work before?

Yes, it was working in v7

### How do we reproduce it?

1. Take a panel with legacy alerting
2.Edit form in `Alert` tab
3. Navigate back to dashboard without hitting `Save` or `apply` button
4. Open `Alert` tab again (its gone)

### Environment (with versions)?

Grafana: v9.5.5 (284c43c23d)
OS: MacOs Ventura 13.5 
Browser: Chrome 116.0.5845.187 (Official Build) (x86_64)

### Grafana platform?

Kubernetes

### Datasource(s)?

Graphite Carbon API

**Comment by balogun14** [comment] 2023-09-28 08:44
can you explain this issue a bit more @bmnidhin

**Comment by bmnidhin** [comment] 2023-09-28 08:58
@balogun14 we have a Grafana 9 dashboard still with legacy alerting. If I change the alert (eg description) and navigate back to dashboard without saving the changes are not cached (auto save)

1. Edited the description

<img width="1000" alt="Screenshot 2023-09-28 at 2 25 41 PM" src="https://github.com/grafana/grafana/assets/11921692/4e33ffd0-6307-4f6f-b933-10617e44a26d">

2. Navigated back without saving
<img width="998" alt="Screenshot 2023-09-28 at 2 25 57 PM" src="https://github.com/grafana/grafana/assets/11921692/2c981be0-6d98-4304-b469-87d976c07de6">

3. Changes gone
<img width="674" alt="Screenshot 2023-09-28 at 2 26 08 PM" src="https://github.com/grafana/grafana/assets/11921692/b1b4f74e-3989-49f3-a364-6cd0d4c93b11">

**Comment by balogun14** [comment] 2023-09-28 09:02
@bmnidhin Thank you for the response i would love to solve this issue so i will familiarize myself with the codebase

**Comment by ignas-sedunovas** [comment] 2023-10-10 18:17
This could be a duplicate of #60839

**Comment by camathieu** [comment] 2023-10-16 19:43
Hello,

We are facing very similar issue with Grafana v10.1.1 Legacy Alerting alerts.
When adding / changing alert tags and hitting Apply the changes are not persisted.

https://github.com/grafana/grafana/assets/6413246/66aa58c5-4e2f-435d-857b-49fe0c74673c

**Comment by armandgrillet** [comment] 2023-10-18 09:13
The causes are the same as the ones described https://github.com/grafana/grafana/issues/60839#issuecomment-1612956609, we have deprecated legacy alerting since Grafana 9 and will thus not fix this issue. The workaround is to save instead, which indeed lacks the preview then, or migrate to Grafana Alerting as legacy alerting will not exist in Grafana 11. Sorry for the inconvenience.

**Closed by armandgrillet** 2023-10-18 09:13 UTC
Labels: area/alerting
