### ISSUE TITLE
Grafana "grafana_datasource_request_duration_seconds" empty query result

### ISSUE THREAD

**Issue by Irrational-NX** [grafana/grafana#54922] opened 2022-09-08 15:05 UTC
**What happened**:
updated grafana from 9.0.3 to 9.1.3, my dashboard monitoring the "grafana_datasource_request_duration_seconds" metric of grafana itself doesn't send anyting now

**What you expected to happen**:
Still have data for this metric

**How to reproduce it (as minimally and precisely as possible)**:
Have a grafana in version 9.1.3, scrapping it with prometheus and look for the "grafana_datasource_request_duration_seconds" metric

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.3
- Data source type & version: prometheus
- OS Grafana is installed on: Docker/Ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mildwonkey** [comment] 2022-09-14 15:28
Hi @Irrational-NX , thanks for reporting this unexpected behavior!

I can reproduce what you're seeing locally. This metric (and a few others) were changed to histograms in Grafana 9.1 (changelog entry [here](https://github.com/grafana/grafana/blob/main/CHANGELOG.md#breaking-changes-1)), so any dashboards using those metrics need to be changed. 

I had some luck getting a similar dashboard panel with the `grafana_datasource_request_duration_seconds_bucket` metric, for example.

I am still looking into why `grafana_datasource_request_duration_seconds` itself appears empty after the upgrade and I'll update this or get another team to help take a look.

**Comment by mildwonkey** [comment] 2022-09-14 17:03
Update! I was close, but not quite right. `grafana_datasource_request_duration_seconds` has been removed and split into 3 metrics relating to `grafana_datasource_request_duration`: 

> Those metric which were updated are now named `grafana_datasource_request_duration_seconds_bucket`, `grafana_datasource_request_duration_seconds_sum` and `grafana_datasource_request_duration_seconds_count` . The old one `grafana_datasource_request_duration_seconds` is removed and no longer updated.

Since there isn't a bug for us to fix, I am going to close this issue. I hope this information helped!

---
Here's some extra documentation on histograms that coworkers sent me, when I asked about these metrics:
* This Grafana blog post on [visualizing histograms](https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/)
* [Prometheus Docs](https://prometheus.io/docs/practices/histograms/#quantiles)

**Closed by mildwonkey** 2022-09-14 17:03 UTC
Labels: area/backend
