### ISSUE TITLE
Stat panel: No variable substitution in value map

### ISSUE THREAD

**Issue by beerygaz** [grafana/grafana#37817] opened 2021-08-12 06:57 UTC
**What happened**: 

Using Grafana 8.1.1 I added a stat panel.  I added a value mapping of 0 : ${myVariable} 
The stat panel does not replace/subsitute the placeholder for the actual variable value but simple displays "${myVariable}" verbatim.

**What you expected to happen**:
I expect the ${myVariable} placeholder to be replaced with the value of the variable as it did in 7.x

**How to reproduce it (as minimally and precisely as possible)**:
Create a variable x with value "Test"
Create a stat panel from a simple source that returns a value of 0
Add a value mapping of 0 : ${x}

**Anything else we need to know?**:

**Environment**: Docker
- Grafana version: 8.1.1
- Data source type & version: Any
- OS Grafana is installed on: Docker (Ubuntu)
- User OS & Browser: Chrome
- Grafana plugins: None

**Comment by torkelo** [comment] 2021-08-12 07:37
duplicate of https://github.com/grafana/grafana/issues/35972

**Closed by torkelo** 2021-08-12 07:37 UTC
