### ISSUE TITLE
PostgreSQL: dataset selection is not available for postgresql datasource

### ISSUE THREAD

**Issue by dgilev** [grafana/grafana#63161] opened 2023-02-09 01:25 UTC
**What happened**:

The dataset dropdown list is not available in PostgreSQL datasource query editor even though it's mentioned in [documentation](https://grafana.com/docs/grafana/latest/datasources/postgres/#dataset-and-table-selection):

> In the dataset dropdown, choose the PostgreSQL database to query. The dropdown is be populated with the databases that the user has access to. When the dataset is selected, the table dropdown is populated with the tables that are available.`

![CleanShot 2023-02-08 at 17 21 16@2x](https://user-images.githubusercontent.com/100722179/217690665-598d4729-bcbb-458b-a53c-7b94a3aaa4b9.png)

I can confirm that the user I'm using in datasource settings has access to multiple databases. 

**What you expected to happen**:

Ideally I should be able to switch between different postgresql databases by selecting different datasets to avoid creating multiple datasources (i.e. one datasource for each database).

**Anything else we need to know?**:

Looks like it might be purposefully hidden in `public/app/plugins/datasource/postgres/QueryEditor.tsx` with no override:

`postgres/QueryEditor.tsx:const queryHeaderProps = { isDatasetSelectorHidden: true };`

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Linux
- User OS & Browser: macOS 13.2 / Safari 16.3
- Grafana plugins:
- Others:

**Comment by usmangt** [comment] 2023-02-09 15:11
Hi @dgilev,

Thanks for opening this issue.

Which Postgres version you are using?

**Comment by dgilev** [comment] 2023-02-09 18:10
@usmangt it's PostgreSQL 14.4

**Comment by usmangt** [comment] 2023-02-21 10:02
Based on your steps of reproduction, I was also able to reproduce it on my test machine.

I used the following:

Grafana OSS ver 9.3.6
Postgresql version 15
OS Linux CentOS 7

Once configured and viewing it in Explore tab, cannot see the list of tables I have created which I can see in Postgres cmd line:


```
postgres=# \dt+
                                     List of relations
 Schema |   Name   | Type  |  Owner   | Persistence | Access method |  Size   | Description 
--------+----------+-------+----------+-------------+---------------+---------+-------------
 public | accounts | table | postgres | permanent   | heap          | 0 bytes | 
 public | hotel    | table | postgres | permanent   | heap          | 0 bytes | 
```

So I am not sure if there is a missing step either on the documentation side or a bug. Therefore will move it to our Engineers to investigate it further.

**Comment by zoltanbedi** [comment] 2023-02-27 08:54
Hi @dgilev,

Sorry this is a problem in our documentation. This is by design as you can't write a SQL query that with the database in it like in MSSQL and MySQL. You need to create separate datasource for separate databases.

TODO:

- [ ] Change query builder image for postgresql datasource
- [ ] Remove the mention of dataset dropdown from docs

**Comment by GrafanaWriter** [comment] 2023-02-28 19:29
To be assigned to new data sources writer.

**Comment by ashutosh887** [comment] 2023-03-13 15:13
@GrafanaWriter @zoltanbedi @dgilev @usmangt I would like to work on this

**Comment by zoltanbedi** [comment] 2023-03-20 12:22
Please do @ashutosh887. Let me know if something is not clear.

**Comment by ashutosh887** [comment] 2023-03-20 13:09
Thanks @zoltanbedi 
Can you please help me how to approach this Issue?
I'm clear with the TODO

> Hi @dgilev,
> 
> Sorry this is a problem in our documentation. This is by design as you can't write a SQL query that with the database in it like in MSSQL and MySQL. You need to create separate datasource for separate databases.
> 
> TODO:
> 
> * [ ]  Change query builder image for postgresql datasource
> * [ ]  Remove the mention of dataset dropdown from docs

**Comment by zoltanbedi** [comment] 2023-03-20 14:27
Please take a look at this guide https://grafana.com/docs/writers-toolkit/writing-guide/contribute-documentation/#edit-a-topic

**Comment by ashutosh887** [comment] 2023-03-20 14:30
Thanks @zoltanbedi 
Let me check

**Comment by ashutosh887** [comment] 2023-04-06 13:03
I wanted to resolve this issue
@baldm0mma Can you help me solve this? 🙂

**Comment by baldm0mma** [comment] 2023-04-06 13:43
Hey @ashutosh887 after checking into our roadmap, this behavioral fix needs to be done pretty quickly, so I'm going to update this documentation myself; there's a lot of other great work to jump into if you're interested [here](https://github.com/grafana/grafana/blob/HEAD/CONTRIBUTING.md)!

**Comment by ashutosh887** [comment] 2023-04-06 13:50
Sure Thanks @baldm0mma 
Please take it forward Sir

**Closed** 2023-06-06 16:28 UTC
Labels: type/docs, help wanted, datasource/Postgres, good first issue
