### ISSUE TITLE
CloudWatch: logAction type query returns inconsistent results

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#26962] opened 2020-08-12 15:38 UTC
**What happened**:
We're getting reports that logAction/GetQueryResults type CloudWatch queries for an absolute time frame return inconsistent results, for example using the following request:

```
{
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1596412800000",
      "to": "1596585599000",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 1,
          "maxDataPoints": 1,
          "datasourceId": 16,
          "type": "logAction",
          "subtype": "GetQueryResults",
          "queryId": "855586b5-3ef0-41c4-9d16-8b7ed95bc157",
          "region": "us-east-1",
          "statsGroups": [
            "Client"
          ]
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "series": null,
        "tables": null,
        "dataframes": [
         ...
        ]
      }
    }
  }
}
```

Supposedly both number of results and order can vary.

We have to figure out why this is, from what we're told the same queries directly to CW are consistent. Could it be another case of results being sorted within Grafana?

**Comment by aknuds1** [comment] 2020-08-18 12:01
I see that results are [ordered by time](https://github.com/grafana/grafana/blob/54ad5b8/pkg/tsdb/cloudwatch/log_query.go#L105-L106), so that could account for why the order might be different versus querying CW directly.

**Comment by aocenas** [comment] 2020-08-26 21:24
@aknuds1 do you have any example of the output? Like how it differs, what lines are missing of how consistent the differences are?

**Comment by aknuds1** [comment] 2020-08-27 07:21
@aocenas I'm on vacation until the 2nd, with limited connectivity, but check the escalation thread in Slack?

**Comment by aocenas** [comment] 2020-08-31 08:45
So only one I found is this:
>Hi, this one is about cloudwatch logs. We have a client using this query on a log group:
```
parse @message '*,*' as @ip,@rest
| stats count(*) as @num by @ip
| sort @num desc
| limit 10
```
> But every time I run it (on the same time range) I get different results (see screenshots), and the results do not watch what they get on cloudwatch.
Do you have any ideas what might be causing this ?

But @kaydelaney already investigated that one and created a PR as it seemed to be a result of query timeout https://github.com/grafana/grafana/pull/26621. So not sure if this is the same issue or not.

**Comment by aknuds1** [comment] 2020-09-08 11:09
@aocenas Should be this message:

> Hello folks! I have a prospect who’s having an issue with CloudWatch metrics. They have a query which they’re sending to CloudWatch in an absolute time frame, but they’re getting different results when they run it. This varies between the number of results coming back and the order in which the results come back (they’re trying to use a bar gauge). If they do this within an AWS CW dashboard, the sort order and results returned are consistent. In Grafana, they aren’t. My assumption is that a CloudWatch query with an absolute time frame should return the same results in the same order, is that correct? Don’t want to spam the main channel, so will add relevant content in thread.

**Comment by aocenas** [comment] 2020-09-09 11:49
Ah so this is cloudWatch metrics issue then? Why did I think this was a logs issue :thinking: ?

**Comment by aocenas** [comment] 2020-09-09 11:50
Oh right there is a `"type": "logAction",` in the query in description.

**Comment by sunker** [comment] 2021-05-05 11:51
@aocenas moving this to the observability project since it's related to CloudWatch logs

**Comment by iwysiu** [comment] 2022-08-10 17:55
Is this still an issue? I managed to create a logs panel for a fixed time frame that had an inconsistent order, but I checked and we got the inconsistently ordered results from the AWS Cloudwatch Logs API.

**Comment by MatiasGaribotti** [comment] 2022-08-23 20:05
@aocenas @iwysiu I am currently having this issue. Every time I run the same query, with the same absolute time range I get different resoults. 

For what I've seen in the query inspector, it is not returning a timeout.

Any updates on this?

Thanks in advance

**Comment by iwysiu** [comment] 2022-09-12 21:20
Hi @MatiasGaribotti I'm taking another look, what grafana version are you on? Is the issue a different order, a different number of results, or both?
Also, if you can tell me, what query are you running?

**Comment by sarahzinger** [comment] 2022-10-11 14:01
Hi Folks, while it's possible there is a bug here, it sounds like we don't have enough information to reproduce it unfortunately. Going to close this issue for now, at least until we can get more reproduction steps. Thanks!

**Closed by sarahzinger** 2022-10-11 14:01 UTC
Labels: area/backend, needs investigation, datasource/CloudWatch Logs
