### ISSUE TITLE
Color table based on text value

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#19366] opened 2019-09-24 13:26 UTC
Using a table visualization with a custom sql query.

**What would you like to be added**:
Feature to be able to colorize table values based on some enum text value.
![Table_colors](https://user-images.githubusercontent.com/22418250/65513104-464e7480-dee3-11e9-879b-5d1c1759b511.png)
For example, a **Text to value** mapping type would allow to map text enum values to numbers, and numbers to be colored by thresholds.

**Why is this needed**:
I need to highlight text enum values in table.

**Comment by marefr** [comment] 2019-09-25 08:49
Duplicate of #11418

**Closed by marefr** 2019-09-25 08:49 UTC
