### ISSUE TITLE
Dashboards save: Interaction with the save drawer closes it

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#81369] opened 2024-01-26 13:31 UTC
### What happened?

When the save dashboard button is not displayed in the tool bar (i.e. you open it via the "show more items" icon) then any interaction with the save drawer closes it.
Impact: You cannot save your dashboard unless you zoom out to show the button or you go through dashboard settings 😢 

Example:

https://github.com/grafana/grafana/assets/42030685/0e88fc7e-3f9d-48cf-80ce-793341c6e47a

### What did you expect to happen?

I'd expect to be able to interact with items inside the save drawer 😉 

### Did this work before?

yes but not sure when it broke

### How do we reproduce it?

1. Open dashboard
2. Zoom in until the save icon no longer appears
3. Click the "show more items" and save dashboard icon
4. Try to interact with drawer

### Environment (with versions)?

Grafana: ops
OS: mac
Browser: chrome

### Grafana platform?

I use Grafana Cloud

**Comment by natellium** [comment] 2024-01-26 13:52
duplicate of https://github.com/grafana/grafana/issues/81009

**Closed** 2024-01-26 13:53 UTC
Labels: type/bug, type/duplicate, area/dashboard, bot/duplicate, team/grafana-dashboards
