### ISSUE TITLE
Regex Value Mappings not working as expected

### ISSUE THREAD

**Issue by Beowolve** [grafana/grafana#41606] opened 2021-11-11 14:04 UTC
Regex value mappings seam to have many bugs in the current Grafana version:

1. Only the first regular expression is used, the second gets ignored
2. If you set a color, the complete row gets colored. Regular value mappings us the color only for the found value/column.
3. $1 seams to be ignored

**What you expected to happen**:
All regular expressions should be executed not just the first one.
Coloring should be consistent with other value mappings. Only the part, that is replaced should be colored.
$1 is mentioned in the documentation but isn't working.

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/32326640/141311023-750c4235-cabb-446f-8fbe-edd8367adbf3.png)

CSV Content:
```
Version, Description
13.0.1745.2, Microsoft SQL Server 2016 (RTM-GDR) (KB4058560)
13.0.1745.2, Microsoft SQL Server 2016 (RTM-GDR) (KB4058560)
13.0.6300.2, Microsoft SQL Server 2016 (SP3) (KB5003279)
13.0.1745.2, Microsoft SQL Server 2016 (RTM-GDR) (KB4058560)
12.0.6433.1, Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB4583462)
13.0.1745.2, Microsoft SQL Server 2016 (RTM-GDR) (KB4058560)
13.0.6300.2, Microsoft SQL Server 2016 (SP3) (KB5003279)
12.0.6433.1, Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB4583462)
```

Demo Dashboard
[regex_valuemappings.zip](https://github.com/grafana/grafana/files/7520885/regex_valuemappings.zip)

**Anything else we need to know?**:
The current documentation has no information about the regex syntax accepted. Also there is no working example?
Whats new in 8.2 lists the feature, but that's it. [Whats new to Grafana 8.2](https://play.grafana.org/d/k5rL1wH7k/0-new-features-in-v8-2?orgId=1)

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: TestData DB / CSV (happens on all datasources for me)
- OS Grafana is installed on: Official Docker Container
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: none used
- Others:

**Comment by ashharrison90** [comment] 2021-11-11 15:10
> 1. Only the first regular expression is used, the second gets ignored
> 1. If you set a color, the complete row gets colored. Regular value mappings us the color only for the found value/column.
> 1. $1 seams to be ignored

attempting to repro each of these 3 locally:
1. can't repro this on main, so potentially fixed already
1. can repro this, but that might be as designed 🤔 
1. can repro this

**Comment by ashharrison90** [comment] 2021-11-12 10:24
hey @Beowolve 👋 

> 1. Only the first regular expression is used, the second gets ignored
> 1. If you set a color, the complete row gets colored. Regular value mappings us the color only for the found value/column.
> 1. $1 seams to be ignored

so i've had a bit more time to look into these now

1. has been fixed by https://github.com/grafana/grafana/pull/41515, which will be included in the upcoming Grafana 8.3.0 release
2. i believe this is working as intended. unless you're saying it will also color values in other columns? but i don't see that behaviour (see screenshot in part 3)
3. in order for $1, $2, etc to work, you need 1 or more capture groups in your regex. if you change your regex to `/(Microsoft SQL Server 2016)/` you should be able to use $1: 
![image](https://user-images.githubusercontent.com/20999846/141451312-94dd456d-efb6-4896-ad15-ea206d5d59c6.png)

i'm gonna close this as i don't believe there's a bug here. if i've missed something, feel free to add a comment and we can discuss and reopen. thanks! 🙌

**Closed by ashharrison90** 2021-11-12 10:24 UTC
Labels: type/bug, area/frontend, area/value-mapping

**Comment by Beowolve** [comment] 2021-11-12 11:18
This is how it looks for me on 8.2.3, but if 8.3 fixes it everything is fine I guess.

![image](https://user-images.githubusercontent.com/32326640/141458742-5f930122-3101-46b4-beed-e49a99f5e64f.png)

**Comment by ashharrison90** [comment] 2021-11-12 11:50
@Beowolve give it a try when 8.3.0 comes out and let us know. i think the beta version is due within the next couple of weeks. 👍
