### ISSUE TITLE
Time series panel: Tooltip always shared

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#37977] opened 2021-08-17 18:13 UTC
**What happened**:
Using several `Time series` panels, and seleting the `All` option for `Tooltip mode` on those will make the tooltip be constantly displayed in _every_ `Time series` panel, whatever setting has been chosen for `Graph tooltip` at the dashboard level (current is `Shared crosshair`, but switching it has no effect in edition mode).

**What you expected to happen**:
`All` option shall not impact the behaviour controlled by the dashboard's `Graph tooltip` option.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create several `Time series` panels with `Single` option selected for the `Tooltip mode` option, in a dashboard with `Shared crosshair` option selected for the `Graph tooltip` option.
2. Edit several panels to switch the `Single` option to `All`
3. Watch Hell unfold

**Anything else we need to know?**:
I did not save the dashboard with those settings, as the edition mode wasn't satisfying.

**Environment**:
- Grafana version: v8.1.0
- Data source type & version: Prometheus v2.28.0
- OS Grafana is installed on: GNU/Linux Debian-like
- User OS & Browser: Firefox v91.0.1
- Grafana plugins: Nothing relevant

**Comment by zuchka** [comment] 2021-08-18 01:18
Hi @Berbe 

I am not sure if this behavior is intended but I confirmed the following [with this dashboard](https://play.grafana.org/d/pPwspqM7z/tooltip-test?orgId=1).

Given a dashboard with multiple time-series panels:

If the dashboard setting's `graph tooltip` is set to `shared crosshair` AND all time series panels have `tooltip mode=single` then: 

expected behavior; a single time series appears on a single panel's tooltip with mouse hover, and the crosshair appears on all panels

But, for any panel with `tooltip mode=all`, then that panel's tooltip will always appear, as a sort of hybrid shared-crosshair-and-tooltip effect

**Comment by zuchka** [comment] 2021-08-18 01:20
Hi @Berbe, this was reported and fixed for 8.1.1.

https://github.com/grafana/grafana/issues/37892

Can you try upgrading? We are still trying to backport the fix

**Comment by zuchka** [comment] 2021-08-18 01:21
duplicate of https://github.com/grafana/grafana/issues/37892

**Closed by zuchka** 2021-08-18 01:21 UTC

**Comment by zuchka** [comment] 2021-08-18 01:25
fwiw I could reproduce this on 8.1.0 but it was fixed on v8.1.1 (90c87a52f7)

**Comment by Berbe** [comment] 2021-08-18 09:50
My bad. Didn't find this issue when searching if that was reported already.

**Comment by Berbe** [comment] 2021-08-18 09:52
Also, @zuchka the changelog of the v8.1.1 seems borked, as I *did* check that and only a single issue is referenced there.
