### ISSUE TITLE
Grafana HTTP API PostgreSQL datasource not updating password field

### ISSUE THREAD

**Issue by tristanbala** [grafana/grafana#20912] opened 2019-12-06 00:44 UTC
I am trying to create a PostgreSQL datasource using the Grafana HTTP API and have Grafana 5.3.1 installed. When I make the POST request I supply a username and password, and set the "password" field in secureJsonFields to True (that's how it appears when I inspect the UI).

The response I get is 200 and the datasource appears on my list of datasources. In the datasource config I see that everything is filled out correctly _except_ for the password field, which is empty. I would normally expect the password section to say "configured".

Is there something I'm doing wrong in my request?

Here is the response I get:
```
{
   "datasource":{
      "id":13,
      "orgId":1,
      "name":<name>,
      "type":"postgres",
      "typeLogoUrl":"",
      "access":"proxy",
      "url":<url>,
      "password":<password>,
      "user":"<user>,
      "database":<db>,
      "basicAuth":false,
      "basicAuthUser":"",
      "basicAuthPassword":"",
      "withCredentials":false,
      "isDefault":false,
      "jsonData":{
         "postgresVersion":1000,
         "sslmode":"disable"
      },
      "secureJsonFields":{

      },
      "version":1,
      "readOnly":false
   },
   "id":13,
   "message":"Datasource added",
   "name":<name>
}

**Comment by papagian** [comment] 2019-12-06 10:11
Following this [comment](https://github.com/grafana/grafana/issues/19764#issuecomment-541559433): you need to set password via the `secureJsonData.basicAuthPassword` property.

Duplicate of #19764

**Closed by papagian** 2019-12-06 10:11 UTC
Labels: type/duplicate

**Comment by tristanbala** [comment] 2019-12-06 19:08
This isn't exactly the same issue as I am not using Basic Auth.

**Comment by tristanbala** [comment] 2019-12-06 19:12
<img width="630" alt="Screen Shot 2019-12-06 at 11 10 17 AM" src="https://user-images.githubusercontent.com/12354072/70349258-358e7900-1819-11ea-881e-b57b6fc1af79.png">

Here is what my config page looks like after the datasource is created. There isn't a Basic Auth box that I have checked.

**Comment by papagian** [comment] 2019-12-08 12:49
My mistake I meant `secureJsonData.password` instead of `secureJsonData.basicAuthPassword`

This is an example JSON for creating a datasource:

```
{
  "access": "proxy",
  "basicAuth": false,
  "basicAuthPassword": "",
  "basicAuthUser": "",
  "database": "grafana",
  "isDefault": false,
  "jsonData": {
      "postgresVersion": 903,
      "sslmode": "disable"
  },
  "name": "PostgreSQL-20912",
  "orgId": 1,
  "password": "",
  "readOnly": false,
  "secureJsonData": {
      "password": "password"
  },
  "type": "postgres",
  "url": "localhost:5432",
  "user": "grafana",
  "version": 3,
  "withCredentials": false
}
```

However, `5.3.1` is a really old grafana version. Do you think it's possible to upgrade to a more recent version?
