### ISSUE TITLE
Database migration fails when going from 8.5.9 to 9.4.2 due to unified alerting

### ISSUE THREAD

**Issue by andnofence** [grafana/grafana#64191] opened 2023-03-05 07:04 UTC
**What happened**:
I tried upgrading our 8.5.9 instance to 9.4.2. On startup the upgraded version crashes due to a migration error. The relevant log lines:

```
logger=migrator t=2023-03-03T21:36:29.383914007Z level=info msg="Starting DB migrations"
--
logger=migrator t=2023-03-03T21:36:29.391522576Z level=info msg="Executing migration" id="clear migration entry \"remove unified alerting data\""
logger=migrator t=2023-03-03T21:36:29.394570709Z level=info msg="Executing migration" id="move dashboard alerts to unified alerting"
logger=migrator t=2023-03-03T21:36:29.397502349Z level=info msg="alerts found to migrate" alerts=13
logger=migrator t=2023-03-03T21:36:29.565372914Z level=error msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="pq: duplicate key value violates unique constraint \"UQE_alert_configuration_org_id\""
logger=migrator t=2023-03-03T21:36:29.56540635Z level=error msg="Exec failed" error="pq: duplicate key value violates unique constraint \"UQE_alert_configuration_org_id\"" sql="code migration"
Error: ✗ migration failed (id = move dashboard alerts to unified alerting): pq: current transaction is aborted, commands ignored until end of transaction block
```

As a workaround I disabled unified alerting and got the upgrade to complete.

**What you expected to happen**:
The database migration should succeed

**How to reproduce it (as minimally and precisely as possible)**:
This one is probably hard to reproduce without having our exact state. But I don't know the Grafana schema so I don't know what queries to run.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.9 upgrading to 9.4.2
- Data source type & version: 
- OS Grafana is installed on: Docker container running on ECS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vsile** [comment] 2023-03-06 08:42
The same issue on 9.3.8
Cannot remove notification policy 
![изображение](https://user-images.githubusercontent.com/9244347/223059613-82829707-07e2-4cac-ba00-eed963667300.png)

**Error: failed to save and apply Alertmanager configuration: pq: duplicate key value violates unique constraint "UQE_alert_configuration_org_id"**

Looks like a bug.

**Comment by tonypowa** [comment] 2023-03-06 09:22
hello @andnofence  @vsile  

this issue seems related to  https://github.com/grafana/grafana/issues/43546#issuecomment-1186924004 (not sure if it's a duplicate), and if it is, it looks like the team is aware of the bug already 

based on that issue and the error message (`UQE_alert_configuration_org_id`) , "it might be that either the alert rules are associated with either a **deleted org** or a deleted dashboard"  (i am tagging the alerting squad for review)

i would suggest to take a look into the issue above and try what's advised 

good luck and please share your findings !

**Comment by tonypowa** [comment] 2023-03-07 08:35
thanks for the research @andnofence  !

in order to answer that question, I have to refer you to the alerting squad

the team will get in touch with you

**Comment by bossjie** [comment] 2023-04-18 06:10
I truncate this table alert_configuration then get go pass.
should be caused by last time we did turn on unified alert then it would insert a record into this table. this time(migration) it tries to do same work so it gets duplicated error

**Comment by grobinson-grafana** [comment] 2023-04-20 10:24
Is there data in the `alert_configuration` table before running the migration?

**Comment by grobinson-grafana** [comment] 2023-04-26 19:06
I'm going to close this as I think the cause is data in the `alert_configuration` before migrations are run. There was a bug in some version of Grafana 8 where data from the `alert_configuration` table wasn't deleted when downgrading from unified alerting to the old dashboard alerts, so I suspect that was the cause here too.

**Closed by grobinson-grafana** 2023-04-26 19:06 UTC
Labels: area/alerting
