### ISSUE TITLE
[Feature request] Alert if NO DATA in one metric from query

### ISSUE THREAD

**Issue by m-messiah** [grafana/grafana#6925] opened 2016-12-12 13:16 UTC
I am using Grafana 4.1.0-1481012464pre1 (Stable 4 + correct webdav) with Graphite on debian jessie.

So, now NO DATA alert works only if whole query does not return any result, but if I want to monitor each metric in query - I need to separate them by separate queries.

For example, I have query A: `system.*.cpu.percent` and alert if `#A` is more than 85 for last 5 minutes, and alert if NO DATA. And I have 3 hosts: host1 host2 and server1.

Expected: If one of hosts down, for example, host1 and host2 is up, but server1 is down - no graph is plotted, and alert NO DATA: server1 raised.

Reality: no plot, but no alert, while at least one of servers is up.

Seems, it is related to allow alerts on query, if one of metric already raised it, and needs to keep series counter, but I think it is very useful in path of alerting system, to handle this situation.

**Comment by torkelo** [comment] 2016-12-12 13:54
duplicate of https://github.com/grafana/grafana/issues/6041

**Closed by torkelo** 2016-12-12 13:54 UTC
