### ISSUE TITLE
export dashboard as PDF (and calc/excel/..) - reports

### ISSUE THREAD

**Issue by DEvil0000** [grafana/grafana#17794] opened 2019-06-27 09:15 UTC
**What we do and need / current situation**:
Creating PDF reports is something a lot of people want. At the moment we use grafana dashboards for graphs and BIRT to create the PDF. It then contains additional tables and the graphs (using render to png link). This approach however is quite ugly and grafana does basically support everything needed beside the PDF export.
We now tried to use table panels and PDF renderer/exporter called [reporter](https://github.com/IzakMarais/reporter) to get rid of BIRT. As discribed in #17792 the rendering of table panels does not work out for most cases - but thats not what this is about.
Just to mention - one can also export CSV of the data in a panel but not for a whole dashboard.

**What would you like to be added**:
I would like grafana to come with a PDF export per dashboard like the one implemented by [reporter](https://github.com/IzakMarais/reporter). Just with better support for (larger) tables - maybe spanning over multiple pages.
I would also like to have a dashboard wide calc/excel/.. export. Basically CSV but one panels data matching one sheet in the resulting document.
The PDF export however is the more important one and should be super easy.

**Why is this needed**:
Our customers want exports of dashboards once a month in PDF format. Basically a report on paper.

**Comment by ryantxu** [comment] 2019-06-27 15:21
> The PDF export however is the more important one and should be super easy

:)  ha

I think when the chromium based image renderer is standard, and we have better hooks for knowing that all panels have rendered this will be possible

**Comment by marefr** [comment] 2020-01-20 09:45
Duplicate of #6843

**Comment by marefr** [comment] 2020-01-20 09:46
Referenced issue is referring to render PDF for panels, but I think it's better to keep everything related to PDF rendering in there (we can change the title) since it has a lot of comments and upvotes.

**Closed by marefr** 2020-01-20 09:46 UTC
Labels: area/image-rendering, type/duplicate
