### ISSUE TITLE
grafana > 7.0.3: graphs are not displayed in firefox

### ISSUE THREAD

**Issue by filipsPL** [grafana/grafana#28712] opened 2020-10-31 08:58 UTC
Hi,

**What happened**:

- grafana > 7.0.3 - graphs are not displayed in *firefox*
- in other browsers it works perfectly
- in grafana 7.0.3 works perfectly
- this happens also in the firefox in the safe mode, with all plugins disabled.

The dashboard - no graphs are shown:

![obraz](https://user-images.githubusercontent.com/11406606/97775091-033ae800-1b5e-11eb-842c-e9f8261a74b7.png)

The error visible in the dashboard:

![obraz](https://user-images.githubusercontent.com/11406606/97775160-d1765100-1b5e-11eb-8815-66fb78060815.png)

In the firefox console:

![obraz](https://user-images.githubusercontent.com/11406606/97775180-f9fe4b00-1b5e-11eb-8852-32a35a32e1e4.png)

In the query inspector:

![obraz](https://user-images.githubusercontent.com/11406606/97775231-66794a00-1b5f-11eb-9678-73725efb20bf.png)

**What you expected to happen**:

- display panels 

**How to reproduce it (as minimally and precisely as possible)**:

- no idea

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5, 7.2.2, 7.3.1
- Data source type & version: linux binaries `....linux-amd64.tar.gz`
- OS Grafana is installed on: 
- User OS & Browser: canonical Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 Linux 5.4.0-37-generic; Firefox 78.0.2 20200708170202
- Grafana plugins: influxdb, updated
- Others:

**Comment by marefr** [comment] 2020-11-02 09:37
Please include the panel JSON of one of the failing panes or the full dashboard JSON.

**Comment by filipsPL** [comment] 2020-11-02 13:32
Hi, thanks for responding.

> Please include the panel JSON of one of the failing panes

Done:  [grafana.json.txt](https://github.com/grafana/grafana/files/5475299/grafana.json.txt)

> Maybe also including your browser time zone/language could be helpful as well based on the error message thrown together with time zone selected in your dashboard.

```js
new Date().toString()
"Mon Nov 02 2020 14:26:15 GMT+0100 (czas środkowoeuropejski standardowy)"
```
(TZ is CEST)

> browser language

Firefox is sending this header: `Accept-Language: en-US,en;q=0.5`

> Btw, I'm not sure what version you have problem with since you're writing that there's problem in 7.0.3 and then

No, I wrote it doesn't work for grafana version > (higher than) 7.0.3, while for grafana version 7.0.3 it works pefrectly. To sum up:
- 7.0.3 it works
- 7.1.5, 7.2.2, 7.3.1 it doesn't work

**Comment by filipsPL** [comment] 2020-11-02 13:39
OK, something is messed with with the Accept-Language header sent by the browser. If I changed it from:

`Accept-Language: en-US,en;q=0.5`

to:

`Accept-Language: pl,en-US;q=0.5` or `Accept-Language: pl,en-US;q=0.7,en-GB;q=0.3`

grafana works fine again!

So it seems that grafana has a problem with this first header.

**Comment by marefr** [comment] 2020-11-02 17:55
Weird. Thanks. Please include your language settings of Firefox, primary and alternatives. Does decide what Accept-Language header browser will send with all requests. Something like this 
![image](https://user-images.githubusercontent.com/1668778/97901702-d0027f80-1d3c-11eb-832a-92cc5d77b9fd.png)

What language do you have on your operating system?

**Comment by filipsPL** [comment] 2020-11-02 20:33
With this settings grafana *works fine*:

![obraz](https://user-images.githubusercontent.com/11406606/97914435-29c07500-1d50-11eb-9f5f-20ccaec9df84.png)
header: `Accept-Language: pl,en-US;q=0.7,en-GB;q=0.3`
![image](https://user-images.githubusercontent.com/11406606/97914844-cedb4d80-1d50-11eb-8698-fab2708089b6.png)
header: `Accept-Language: en-US`

The original settings:
![image](https://user-images.githubusercontent.com/11406606/97915630-12828700-1d52-11eb-94ec-8294dc568d8c.png)
header `Accept-Language: en-US,en;q=0.5`
but with this grafana also works fine! It means that **I can't reproduce this problem anymore!**

> What language do you have on your operating system?

pl_PL.UTF-8


So at this points it seems that I can't reproduce this problem anymore. I guess this has something with language headers but I can't figure out what is going on. Please let me know if I can help.

**Comment by mckn** [comment] 2020-11-03 14:37
I have tried to reproduce this but I can't get it to fail in either Firefox, Chrome or Opera. The part of the code that is referenced in this issue is when the native i10n support tries to use the native locale flags so I must be something with the browser settings.

I will close this due to unable to reproduce. Feel free to re-open or ping me if you can figure out how to reproduce it.

**Closed by mckn** 2020-11-03 14:37 UTC
Labels: area/dashboard, needs investigation
