### ISSUE TITLE
Unable login, unable change admin password

### ISSUE THREAD

**Issue by ghdevops123** [grafana/grafana#23381] opened 2020-04-07 02:55 UTC
I had Grafana up and running for about a week, when I came in Monday morning the page had expired and I needed to log back in. Except it would not accept my password. Selecting “Forgot your password” did no good, so I looked for means to reset the password. I was able to find in Github issues thread how to reset via commandline connecting to the sqllite database. I should mention I also backed up the grafana.db, and tried the method to have a new grafana.db created as if this was a new install. Still can not login.

Now here is the real issue. So right now I have user admin with password admin. I open the webpage, type those in and next get screen prompting me to change the password. Except if I select “skip” it goes back to login, and if I try to enter a new password I get a red error box stating “! Unauthorized”…and nothing helps.

What I get for logging is of not much assistance that I can see -
t=2018-10-23T07:50:12-0500 lvl=info msg=“Request Completed” logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=10...61 time_ms=220 size=42 referer=https://..com:3001/login
t=2018-10-23T07:50:34-0500 lvl=info msg=“Request Completed” logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10...61 time_ms=1 size=61 referer=https://..com:3001/login
t=2018-10-23T07:55:32-0500 lvl=info msg=“Request Completed” logger=context userId=0 orgId=0 uname= method=PUT path=/api/user/password status=401 remote_addr=10...61 time_ms=1 size=26 referer=https://..com:3001/login

It has done this with my original grafana.db and newly created on. It does this in Chrome and Edge. I did bump log level to debug and tried again, only thing I get was this:

t=2018-10-23T08:03:33-0500 lvl=info msg=“Request Completed” logger=context userId=0 orgId=0 uname= method=PUT path=/api/user/password status=401 remote_addr=10...61 time_ms=0 size=26 referer=https://..com:3001/login

**Comment by jongyllen** [comment] 2020-04-07 07:17
Hi, that sound very strange. If you have rested and cannot login it sounds like something else then Grafana. 

There are no active bugs like this regarding logging in and I cannot reproduce this.

Maybe a silly question but have you tried doing this in private mode in your browser, and also clear all cookies? I would also ask in the community forums if anyone has experienced this.
Providing what OS/Browser and Grafana version is essential to get help ([community forums](https://community.grafana.com/)) or submit bugs ([github issue using the template](https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md))

**Comment by s0nders** [comment] 2020-04-22 20:12
same issue here, reset via cli and login is successful but just reloads the page and prompts for creds again.

**Comment by xianweijian** [comment] 2020-04-23 08:24
I had same issue.
I use docker to deploy.But only my pc chrome brower can login and reset password.Other brower or computer brower can not login.
my grafana version:6.7.2(by docker)
chrome version: 71.0.3578.98
docker on linux: red-hat 7.4

**Comment by marefr** [comment] 2020-04-23 09:21
Sounds like auth token cookie not being set. Please open Chrome developer tools or similar. Then in console tab find settings and check Preserve log. Then find network tab and check Preserve log. Then login and reproduce your problem and inspect any information logged to console or the request(response details of the login HTTP POST request. Include information here.

**Comment by thomas536** [comment] 2020-05-14 06:04
Here's my response from /login that's exhibiting this behavior (login "successful", return back to /, which immediately 302s back to /login). Is there some DNS or SameSite shenanigans going on?

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json
Expires: -1
Pragma: no-cache
Set-Cookie: grafana_session=059d1095710bf538ebd78f21fd974a48; Path=/; Max-Age=2595600; HttpOnly; SameSite=Lax
X-Frame-Options: deny
Date: Thu, 14 May 2020 06:00:40 GMT
Content-Length: 23
```

**Comment by gsahbi** [comment] 2020-05-21 11:54
login fails as well for version 7.0 but works for 6.x and only with chrome

**Comment by consideRatio** [comment] 2020-05-28 21:39
I just confirmed that you can, at least in chrome, have two cookies set with the same name as long as their path only differs with a trailing / or not.

So I figure what happens then is that the old auth cookie is being read by the webservers, but the new auth cookie is being written to during logins. Yikes... It really is hard to catch all the consequences of a change.

I think the fix to make, is to try delete any old cookies with a trailing slash when logging in, alongside setting the new without a trailing slash.

**Comment by consideRatio** [comment] 2020-05-28 21:45
Ping @papagian who have worked a lot with cookies and had the foresight to understand it is a very tricky matter to get right.

**Comment by papagian** [comment] 2020-05-29 17:36
thank you @consideRatio for bringing this into my attention.

I think that if the problem is actually that there is a cookie left that it cannot be deleted because of the different cookie path, then this will happen only the first time a user will attempt to login; if the stale cookie is deleted (manually) and the user is successfully logged on, all the following login attempts for the user will be successful. Therefore, I think that it should be enough to add a note for warning the users for the modification and advise them to delete stale cookies or change the cookie name if they experience login issues.

However, it's hard to say if all the above reported cases are cause by the stale cookie. For investigating them further, additional information would be valuable like:
- the server logs (ideally with debug logging enabled)
- the running grafana version and browser
- check whether there are stale cookies left

**Comment by joneskoo** [comment] 2020-06-11 20:31
Please note my comment in https://github.com/grafana/grafana/issues/15316#issuecomment-642906587 ; I had a bit different failure mode than what I can understand from this ticket. In my case Grafana appeared to not be signed in. I logged in (with Google auth) and after successful sign in I return to the same view - I appear to not be logged in to Grafana.

My Grafana is at path /grafana/ . I noted that I had cookie grafana_session for both /grafana and /grafana/ . After I deleted both and signed in I could sign in again.

    lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"

Is it possible to make next release of Grafana clear the grafana_session with trailing slash  in path - if it can't find cookie like ^ above error it should attempt to clear both with and without trailing slash? Hopefully this helps reproduce the problem.

**Comment by joneskoo** [comment] 2020-06-11 20:38
@papagian Any harm to clear session cookie from /grafana/ if we get error "Failed to look up user based on cookie"? The /grafana should be written on successful sign-in.

**Comment by marefr** [comment] 2020-06-11 20:49
This problem are now described in the [upgrade notes](https://grafana.com/docs/grafana/latest/installation/upgrading/#cookie-path).

**Comment by marefr** [comment] 2020-06-11 20:59
We are clearing the auth token cookie when "Failed to look up user based on cookie" error: 
https://github.com/grafana/grafana/blob/4c8ad8d031b51089b12db7ae5d9daf48c867128c/pkg/middleware/middleware.go#L218

We're not planning to add another special case for cleaning the cookie having a path of sub path + trailing slash. But if anyone is interested contributing a fix for this we will consider accepting it.

**Closed by marefr** 2020-06-11 20:59 UTC
Labels: area/backend/auth, needs more detail
