### ISSUE TITLE
6.7.1 crashing on not being able to parse alert notifier yaml

### ISSUE THREAD

**Issue by devdavidkarlsson** [grafana/grafana#23217] opened 2020-03-31 05:56 UTC
**What happened**:
Grafana crashing on boot, 
`t=2020-03-30T17:03:15+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Alert notification provisioning error: Alert validation error: Recipient on invalid format: \"grafana-alerts\""`. This worked before,

**What you expected to happen**:
Successfull startup, even if alert would be non functional

**How to reproduce it (as minimally and precisely as possible)**:
`
cat >>  /etc/grafana/provisioning/notifiers/initial_config.yaml <<-'EOM'
apiVersion: 1
notifiers:
  - name: default-slack
    type: slack
    uid: grafana-slack
    settings:
      recipient: "grafana-alerts"
      icon_emoji: ":rain_cloud:"
      uploadImage: true
      url: https://hooks.slack.com/services/T3WG........HjqNkyh
EOM
`

**Anything else we need to know?**:

**Environment**:
- Grafana version:
 "Starting Grafana" logger=server version=6.7.1 commit=ca6d08d5cb branch=HEAD compiled=2020-03-20T13:13:09+0000
- OS Grafana is installed on:
Amazon linux
- Grafana plugins:
Slack alerts/notifiers configured.

**Comment by devdavidkarlsson** [comment] 2020-03-31 06:15
was missing a # infront of slack channel name. Old config stopped working on updating to 6.7.1

**Comment by jongyllen** [comment] 2020-03-31 08:20
Hi, I guess that means we can close this issue?

**Comment by aknuds1** [comment] 2020-03-31 08:38
You can see the requirements for the recipient configuration parameter in [our docs](https://grafana.com/docs/grafana/latest/alerting/notifications/#slack).

@jongyllen I think we can close the issue, since it's not a bug.

**Closed** 2020-03-31 09:04 UTC
