### ISSUE TITLE
CLI: Service instructions on windows are incorrect

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#20983] opened 2019-12-09 23:40 UTC
**What happened**: I attempted to install the Pie Chart Panel plugin by following the instructions in the [Pie Chart Panel page](https://grafana.com/grafana/plugins/grafana-piechart-panel/installation). I entered `grafana-cli plugins install grafana-piechart-panel` in the command line. 

It gave me this error: Error: ✗ Failed to extract plugin archive: Could not create /var/lib/grafana/plugins/grafana-piechart-panel. Permis
sion denied. Make sure you have write access to plugindir

**What you expected to happen**: I expected it to work the way the instructions said.

**How to reproduce it (as minimally and precisely as possible)**: See above.

**Anything else we need to know?**:
I was able to get it to install by running the Windows PowerShell as an administrator when I put `.\` in front of it. 

However, then the plugin installer tells me in the PowerShell to restart the service with service grafana-server restart, which does not work in either Windows Powershell or the cmd prompt.

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: N/A, none hooked up. 
- OS Grafana is installed on: Windows 10 Professional
- User OS & Browser: Chrome
- Grafana plugins: Pie Chart
- Others:

**Comment by ryantxu** [comment] 2019-12-10 00:23
are you on windows, or wsl?  with wsl, does:
`sudo grafana-cli plugins install grafana-piechart-panel`
change anything?

On windows, I would expect any service related commands to be `sc.exe ...` not `service ...`

If the docs suggest this could/should work we should make sure that windows is not near the descriptions!

**Comment by ryantxu** [comment] 2019-12-10 03:29
IIUC, the issue is that grafana-cli suggest running a command that does not exist in windows.  It should suggest:
```
net stop grafana-server
net start grafana-server
```
or
```
sc.exe stop grafana-server
sc.exe start grafana-server
```

**Comment by oddlittlebird** [comment] 2019-12-10 15:36
Fixing the grafana-cli instructions is the big one. @DanCech and I need to put our heads together and update the plugin installation instructions in the docs and in grafana-net so that Windows users understand that they need to do something different.

**Comment by oddlittlebird** [comment] 2019-12-12 21:47
You guys might want to test if restarting the Grafana service is actually necessary on Windows machines. I am not positive, but I am pretty sure that the Piechart Panel appeared without me restarting.

**Comment by bergquist** [comment] 2020-03-09 08:37
The grafana server only loads plugins on startup so the grafana-server needs to be restarted when new plugins are installed.

**Comment by tushar315** [comment] 2020-05-04 12:10
@oddlittlebird  can exactly tell what command you ran on powershell such that your panel came without restarting the grafana server.

**Comment by oddlittlebird** [comment] 2020-05-04 15:14
I copied and pasted one from the Install tab of the plugins website, and my panel just showed up. Local installation on a Windows 10 Pro machine.

**Comment by marefr** [comment] 2021-03-23 19:52
@oddlittlebird this has been open for over a year now and this issue haven't really had a lot of activity. I'm still not sure if this is something that could be resolved in grafana-cli, docs or if it's a grafana.com issue. I'm eager to close this unless anyone disagree?

**Comment by oddlittlebird** [comment] 2021-03-23 21:00
The main issue is that the instructions given in Grafana CLI do not work for Windows machines.

**Comment by marefr** [comment] 2021-03-24 09:48
@oddlittlebird Depending on how you have installed Grafana and run it you might not have a Grafana service at all. If you have, it could be different ways of doing this on Windows and Linux.

I suggest changing `Restart grafana after installing plugins . <service grafana-server restart>` to `Restart Grafana after installing plugins.` to minimize the risk of shooting our self in the foots. WDYT?

**Comment by oddlittlebird** [comment] 2021-03-24 13:43
Looks good to me. FYI, we actually have a topic in the docs just about [restarting Grafana](https://grafana.com/docs/grafana/latest/installation/restart-grafana/). We should not link from the software, but we add something about referring to the Grafana documentation for instructions.

**Comment by marefr** [comment] 2021-03-24 15:17
What about `Restart Grafana after installing plugins. Please refer to the official documentation of how to restart Grafana`?

**Comment by oddlittlebird** [comment] 2021-03-24 15:58
`Restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.`

Is my suggestion. Sounds good to me!

**Closed** 2021-03-29 08:45 UTC
Labels: area/grafana-cli, type/bug
