### ISSUE TITLE
[Bug] Hide value in Table Panel adds horizontal scrollbar

### ISSUE THREAD

**Issue by jon-rei** [grafana/grafana#12510] opened 2018-07-05 12:01 UTC
Hi,

I am currently facing an cosmetic issue with the table panel inside one of mine Grafana dashboards.
When I'm removing the value of the metric which is shown inside the table. My browser renders a horizontal scrollbar on the bottom of the table.

![grafik](https://user-images.githubusercontent.com/21036205/42322173-be2bb64e-805b-11e8-8bd9-384bc66ab2ac.png)

### What Grafana version are you using?
v5.2.1
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?
Removed value inside the table panel
### What happened?
One horizontal scrollbar is added to the panel

I have tested it on several browsers and getting the same result.

**Comment by marefr** [comment] 2018-07-05 15:51
Unable to reproduce. Could you please share your panel json?

**Comment by jon-rei** [comment] 2018-07-06 05:47
**Panel json**
```
{
  "columns": [],
  "datasource": null,
  "fontSize": "100%",
  "gridPos": {
    "h": 5,
    "w": 3,
    "x": 0,
    "y": 25
  },
  "id": 12,
  "links": [],
  "pageSize": null,
  "scroll": true,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "styles": [
    {
      "alias": "",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "mappingType": 1,
      "pattern": "branch",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    },
    {
      "alias": "",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "mappingType": 1,
      "pattern": "version",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    },
    {
      "alias": "",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "decimals": 2,
      "pattern": "/.*/",
      "thresholds": [],
      "type": "hidden",
      "unit": "short"
    }
  ],
  "targets": [
    {
      "expr": "alertmanager_build_info",
      "format": "table",
      "instant": true,
      "intervalFactor": 1,
      "refId": "A"
    }
  ],
  "title": "Alertmanager version",
  "transform": "table",
  "type": "table"
}
```

**Comment by marefr** [comment] 2018-07-06 08:50
Thanks. Confirmed bug

**Comment by marefr** [comment] 2018-07-06 08:53
But closing this in favor of #9964. Seems like the same problem. Thanks for helping us reproduce this bug!

**Closed by marefr** 2018-07-06 08:53 UTC
Labels: comp: panel/table, type: bug
