### ISSUE TITLE
ngalerts firing with empty labels

### ISSUE THREAD

**Issue by gabrielmcf** [grafana/grafana#35943] opened 2021-06-18 11:57 UTC
**What happened**:

I've created some grafana managed alerts with prometheus as a data source. I'm using the labels to have a multi dimension alert and it works fine most of the time. Some times, although, it fires without any proper application failure, when we look at the alert the templated labels are empty. I've tried to filter out the empty labels using PromQl but it still happens. I've checked the prometheus metrics at the time the alert has fired and it has no empty label metrics.

**What you expected to happen**:

There should not be an alert with empty labels, all alerts should have a proper label and fire only then.

**How to reproduce it (as minimally and precisely as possible)**:

Create an alert like the image:

![Screenshot from 2021-06-17 14-36-45](https://user-images.githubusercontent.com/156070/122557039-a0299300-d012-11eb-9d48-9d269d69cce1.png)
 
After some time it fires like the image below:

![Screenshot from 2021-06-17 14-36-28](https://user-images.githubusercontent.com/156070/122557118-bafc0780-d012-11eb-8191-8b8ad5782614.png)

**Anything else we need to know?**:

I've noticed it happens with other data sources as well, the exact same behaviour. I've also tried to configure the missing data options without any help.

![Screenshot from 2021-06-18 09-30-24](https://user-images.githubusercontent.com/156070/122561302-18468780-d018-11eb-803f-6645503d2fad.png)

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Prometheus 2.19.3 (installed using linkerd-viz), Azure 
- OS Grafana is installed on: running on docker over Linux (centos 8.3.2011)
- User OS & Browser: Fedora 33 & Google Chrome 91

**Comment by gabrielmcf** [comment] 2021-06-18 12:51
I've tried to update do 8.0.3 but the prometheus data source started to return 503 in the alert page.

**Comment by gabrielmcf** [comment] 2021-06-18 13:02
It seems to happen when for some reason the data source return 503. I'm not sure why it is returning this error but am investigating. It happens both with prometheus and azure data source.

**Comment by gabrielmcf** [comment] 2021-06-18 20:10
I've been able to successfully update to 8.0.3 and the problem still exists. I will update the original post.

**Comment by codesome** [comment] 2021-06-21 05:15
@gabrielmcf multidimensional alerts work a little differently in Grafana compared to Prometheus. The multidimensional part would still produce a single alert right now with the multidimentional info is clubbed under a single label `__value__` which is available to template the contact points. Hence `$labels` wont have the labels as you expect in Prometheus. We are working on improving this experience.

**Comment by gabrielmcf** [comment] 2021-06-21 12:13
@codesome, thanks for the clarification! What I have suggested that seems to work like Prometheus (but occurs with others datasources as well) is that is creates an instance for each combination of the label values. Is that correct?

**Comment by kylebrandt** [comment] 2021-06-21 12:20
> @codesome, thanks for the clarification! What I have suggested that seems to work like Prometheus (but occurs with others datasources as well) is that is creates an instance for each combination of the label values. Is that correct?

I think this is just a bit of confusion between features. The labels should not be empty valued there, and there should be multiple alert instances when responses return labels. (What gets combined is the values of expression values, and ends up in `__values__` currently, but this is different thing).

Not sure why this happens or where the error is. Perhaps when a error is returned something strange happens in the state manager/cache - could be elsewhere though (before or after that in the pipeline)

**Comment by gabrielmcf** [comment] 2021-06-21 13:23
Great, so I got it right, I was not saying this is not the expected behaviour, just that it seems to work that way! Thank you for the help!

**Comment by kylebrandt** [comment] 2021-06-21 13:45
At least currently I haven't been able to replicate this (at least on `main`), but not quite sure how to. I tried putting the following in my prom data source code:

```
		if time.Now().Minute()%2 == 0 {
			return result, fmt.Errorf("and error Kyle made")
		}
```

But my screen looks like:

![image](https://user-images.githubusercontent.com/1692624/122770618-a0749900-d273-11eb-9f91-228bf9505c6d.png)

With the one at the bottom only having custom/system labels, but that is expected because only an error is returned (so no labels and one instance). What I don't understand is the label key being there but with an empty value.

**Comment by gabrielmcf** [comment] 2021-06-21 14:12
I do have some alerts with this same behavior (firing with no custom label). The error message is "context deadline exceeded". But it should not happen, since in this case, the data should always have labels (Azure datasource).

**Comment by codesome** [comment] 2021-06-21 14:39
One of the errors that I faced too was when using templates for labels and then they render to be empty strings, which as a result makes 2 different alerts coming from the same query (multidimensional labels from Prometheus) to be converted into a single alert (because the labels that is supposed to be different are now empty), hence the clash errors out. (I can post the error message tomorrow)

This happens when I set alert on Prometheus query directly without any classic condition (or with too, I dont remember).

**Comment by gabrielmcf** [comment] 2021-06-21 14:49
I thought it was something related to prometheus returning series without labels, but then I've filtered the empty values in PromQL and it still happens.

**Comment by davidmparrott** [comment] 2021-06-22 02:57
@gabrielmcf I'm taking a look at this and trying to isolate where I think this might be happening. So far I think the state cache is behaving correctly given the results it is processing but I have some things to continue to poke at. Thanks for bringing this to our attention.

**Comment by davidmparrott** [comment] 2021-06-23 16:14
I am not able to reproduce this which is making it a challenge to try and troubleshoot. @papagian or @gotjosh any thoughts?

**Comment by gabrielmcf** [comment] 2021-07-02 12:06
Is there any further information I can give on the subject? The debug logs are not very helpful.

**Comment by gabrielmcf** [comment] 2021-07-02 21:22
I've found a workaround excluding those alerts from the notification police. I need to use a couple of different policies depending on what labels are coming empty. It does not avoid the alert from being fired but it does reduces the number of messages being sent. The matching expressions looks like the follow image.
![Screenshot from 2021-07-02 18-21-09](https://user-images.githubusercontent.com/156070/124329777-7324c680-db62-11eb-9ba5-22664ee679a4.png)

**Comment by gabrielmcf** [comment] 2021-07-06 12:33
Even with this workaround it stills send some messages with empty labels...

**Comment by Nkmol** [comment] 2021-07-06 15:02
I could reproduce the same issue using InfluxDB=1.8.4 and Grafana=8.0.4. Using the "Preview alert" I could see the `label: { value="value"}` to be filled, but when using this either in the annotations or labels (`$labels.value`) it showed an empty value.

**Comment by gotjosh** [comment] 2021-07-12 12:22
> I could reproduce the same issue using InfluxDB=1.8.4 and Grafana=8.0.4. Using the "Preview alert" I could see the label: { value="value"} to be filled, but when using this either in the annotations or labels ($labels.value) it showed an empty value.

Hi @Nkmol, this is a different issue that's being handled by #36020.

> Even with this workaround it stills send some messages with empty labels...

We're unable to replicate this sadly. As an intermediate step, we're planning to add a log-level output to aid us with debugging.

**Comment by davidmparrott** [comment] 2021-07-12 19:39
@gabrielmcf I believe I have finally gotten to the bottom of what's happening here. The fix for this is to change the behavior of the label and annotation expansion code. Previously, when we were missing a key in the evaluation results, we would insert the key with the zero value for the key type. Because all of our labels are strings, this was always an empty string. 

When your datasource errors, we're processing an evaluation result that has an incomplete/empty label set. When we get to the template expansion step, because of the missing value handling, we were adding these extra labels with empty values. This change will result in the alert instance having a value that is the string representation of the templated label eg `{{$labels.code}}`

![Alerting__Alert_rules_-_Grafana](https://user-images.githubusercontent.com/4461026/125345859-e7532d00-e30d-11eb-8779-b041b3359b92.png)

In the PR, I mention another issue that deals with instances with some missing labels persisting. The fix that I will create for that issue will also address the situation where you wind up with this alert instance that has the value set to be the string of the template. It should also allow you to create a routing rule where you're not notified in the event that you see the template expansion fail.

**Comment by gabrielmcf** [comment] 2021-07-12 19:44
That's really great new @davidmparrott! I'm thrilled to see that the PR is already in 8.0.6 milestone! Thank you very much, I will test it soon!

**Closed** 2021-07-13 13:57 UTC
Labels: area/unified-alerting, type/bug

**Comment by gabrielmcf** [comment] 2021-07-16 13:31
I've been testing the new version for a couple days now and I'm able to avoid the alerts beeing sent using the notification policies. It just doesn't make much sense to me that an data source fetch error should trigger an alert instance. Shouldn't it trigger an alert somewhere else? Or be treated as missing data?

**Comment by davidmparrott** [comment] 2021-07-16 17:14
I was just talking to @kylebrandt about this yesterday, in fact. It's related to what's going on in [this scenario](https://github.com/grafana/grafana/issues/36179#issuecomment-876727998) although there the reason evaluation matches disappeared is that they were being filtered out by the query itself. 

The heart of the problem is one that's common to any alerting system where you're analyzing incoming signals that can have variable numbers of matches. A lack of a response does not exactly map to our definition of NoData. We have two situations are they're not quite the same. In one, we run the query and, for a given label set (match) we get no values (eg the query response indicates the presence of a match but returns no values for the query) or every data point is null. The other scenario is where we do not get any response, or the response does  not contain a match that was previously reporting. The first scenario is what is addressed by the NoData setting. The second has a variety of possible solutions and I'm currently working on how to handle them.

The most obvious solution, setting every alert instance associated with an alerting rule into an error state when the datasource returns an error or could not be reached, would need a mechanism to prevent momentary blips from creating noisy/flapping alerts. Adding a configuration setting that says "alert me if it is in error for N evaluation cycles" would give users the ability to have noisy/fast alerts or quieter/slower alerts, at least.
