### ISSUE TITLE
New/updated provisioned dashboard alerts are not used once migrated to unified alerting

### ISSUE THREAD

**Issue by ahrtolia** [grafana/grafana#52388] opened 2022-07-18 09:51 UTC
**What happened**:
When I create an alert using the Grafana Dashboard API, it returns success, but I can't find the corresponding alert rule。
![image](https://user-images.githubusercontent.com/38370438/179485797-dac192dc-5dd6-414f-a1a6-5a0781b683c6.png)
![image](https://user-images.githubusercontent.com/38370438/179485739-c6f944aa-cc0f-4def-aa06-3db0a95e8d33.png)
![image](https://user-images.githubusercontent.com/38370438/179485924-575cc678-526a-4192-a005-c69b21c23ce3.png)

**What you expected to happen**:
I want to create an alert through DashboardAPI, and the alert will be associated to Dashboard and Panel

**How to reproduce it (as minimally and precisely as possible)**:
Simply call the examples provided in the official documentation to reproduce
**Anything else we need to know?**:
that is all
**Environment**:
- Grafana version:
- 8.3.7 & 9.0.3
- Data source type & version:
- sqlite3
- OS Grafana is installed on:
- macOS，CentOS
- User OS & Browser:
- MacOS & Chrome
- Grafana plugins:
- Others:

**Comment by ashharrison90** [comment] 2022-07-26 13:32
@grafana/alerting-squad is this even possible to do via the dashboard api with unified alerting or is this a case of outdated documentation? (see `Example Request for updating dashboard alert rule` here: https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/#create--update-dashboard)

**Comment by armandgrillet** [comment] 2022-08-12 09:19
The problem is that legacy alerting is disabled thus the provisioned alerts through a dashboard JSON are not loaded and that the migration from legacy alerting to unified alerting has already happened thus the alerts are not migrated.

The solution would be to use the new file-provisioning feature which will be available in Grafana 9.1 (August 16th). However, the lack of error messages to guide the user through this experience is an issue.

**Comment by ShawnPollock** [comment] 2022-09-27 16:25
Is there any way to migrate alerts from dashboard.json files to the new format?

**Comment by alexweav** [comment] 2022-09-28 21:08
@ShawnPollock Not without manual translation at the moment. But, this is something we're working on as part of this ticket.

One option to help out in the short term is to provision things in a Legacy instance, and then upgrade that instance to UA. The migration will translate objects. You can then GET the object in UA, the JSON model is _almost_ identical to the .yaml model you need for the new format, it'll need a few manual touch-ups like wrapping the objects in a list.

We're looking into:
1. Creating a `/export` provisioning route, which does these manual touch-ups automatically. It'll just export the provisioning files that map to your data
2. Extracting the object translation into a command-line utility, that can be used to port old files to new without running a DB migration.

However, these aren't in place quite yet.

**Comment by ShawnPollock** [comment] 2022-09-28 21:17
I see, unfortunately manually updating dozens and dozens of alerts is not something that is practical right now, but I appreciate the quick response and will be patiently awaiting the export feature. Thanks!

**Comment by yuri-tceretian** [comment] 2023-05-05 22:55
I think this is duplicated of https://github.com/grafana/grafana/issues/43546

**Comment by JacobsonMT** [comment] 2024-04-05 17:40
Closing with the removal of legacy alerting in v11.

The new [preview tool method of upgrading](https://grafana.com/docs/grafana/v10.4/alerting/set-up/migrating-alerts/#upgrade-with-preview-recommended) to Grafana Alerting available in v10.3+ gives the opportunity to upgrade your alerts in a safe preview environment before cutting over to Grafana Alerting. During this preview you can export your provisioned alerts in file-provisioning or HCL format so you can migrate your as-code setup at your leisure.

**Closed by JacobsonMT** 2024-04-05 17:40 UTC
Labels: type/bug, prio/high, area/alerting
