### ISSUE TITLE
Tempo Service Graph requests can return error even if graph metric data is present

### ISSUE THREAD

**Issue by hedss** [grafana/grafana#56337] opened 2022-10-04 18:21 UTC
**What happened**:
In a Grafana Cloud stack with:
* Metrics generation enabled
* `traces_service_graph_*` active series present with relevant data
requesting the Service Graph from the Tempo Explorer panel can yield the following error:

```
bad_data: invalid parameter "query": 1:67: parse error: error parsing regexp: invalid nested repetition operator: `**`
```
The service graphs are not rendered. Image showing issue below.

![image](https://user-images.githubusercontent.com/8259026/193894671-435fe497-0638-486d-b04e-99548f501fc6.png)

Full, prettified data frame response from the query is below but from a quick inspection it appears the offender is an incorrect regexp expression in the PromQL query:
```
"histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/**\"}[$__range])) by (le))": {
      "error": "bad_data: invalid parameter \"query\": 1:67: parse error: error parsing regexp: invalid nested repetition operator: `**`"
```

Data frame response:
```
{
  "results": {
    "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/\"}[$__range])) by (le))": {
      "frames": [
        {
          "schema": {
            "name": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/\"}[10800s])) by (le))",
            "refId": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/\"}[$__range])) by (le))",
            "meta": {
              "type": "timeseries-many",
              "custom": {
                "resultType": "vector"
              },
              "executedQueryString": "Expr: histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/\"}[10800s])) by (le))\nStep: 15s"
            },
            "fields": [
              {
                "name": "Time",
                "type": "time",
                "typeInfo": {
                  "frame": "time.Time"
                }
              },
              {
                "name": "Value",
                "type": "number",
                "typeInfo": {
                  "frame": "float64"
                },
                "labels": {},
                "config": {
                  "displayNameFromDS": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/\"}[10800s])) by (le))"
                }
              }
            ]
          },
          "data": {
            "values": [
              [
                1664903449838
              ],
              [
                0.0018000000000000002
              ]
            ]
          }
        }
      ]
    },
    "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/**\"}[$__range])) by (le))": {
      "error": "bad_data: invalid parameter \"query\": 1:67: parse error: error parsing regexp: invalid nested repetition operator: `**`"
    },
    "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/error\"}[$__range])) by (le))": {
      "frames": [
        {
          "schema": {
            "name": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/error\"}[10800s])) by (le))",
            "refId": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/error\"}[$__range])) by (le))",
            "meta": {
              "type": "timeseries-many",
              "custom": {
                "resultType": "vector"
              },
              "executedQueryString": "Expr: histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/error\"}[10800s])) by (le))\nStep: 15s"
            },
            "fields": [
              {
                "name": "Time",
                "type": "time",
                "typeInfo": {
                  "frame": "time.Time"
                }
              },
              {
                "name": "Value",
                "type": "number",
                "typeInfo": {
                  "frame": "float64"
                },
                "labels": {},
                "config": {
                  "displayNameFromDS": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/error\"}[10800s])) by (le))"
                }
              }
            ]
          },
          "data": {
            "values": [
              [
                1664903449838
              ],
              [
                0.0018000000000000002
              ]
            ]
          }
        }
      ]
    },
    "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/welcome\"}[$__range])) by (le))": {
      "frames": [
        {
          "schema": {
            "name": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/welcome\"}[10800s])) by (le))",
            "refId": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/welcome\"}[$__range])) by (le))",
            "meta": {
              "type": "timeseries-many",
              "custom": {
                "resultType": "vector"
              },
              "executedQueryString": "Expr: histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/welcome\"}[10800s])) by (le))\nStep: 15s"
            },
            "fields": [
              {
                "name": "Time",
                "type": "time",
                "typeInfo": {
                  "frame": "time.Time"
                }
              },
              {
                "name": "Value",
                "type": "number",
                "typeInfo": {
                  "frame": "float64"
                },
                "labels": {},
                "config": {
                  "displayNameFromDS": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"/welcome\"}[10800s])) by (le))"
                }
              }
            ]
          },
          "data": {
            "values": [
              [
                1664903449838
              ],
              [
                0.00865929230357198
              ]
            ]
          }
        }
      ]
    },
    "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"HTTP GET\"}[$__range])) by (le))": {
      "frames": [
        {
          "schema": {
            "name": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"HTTP GET\"}[10800s])) by (le))",
            "refId": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"HTTP GET\"}[$__range])) by (le))",
            "meta": {
              "type": "timeseries-many",
              "custom": {
                "resultType": "vector"
              },
              "executedQueryString": "Expr: histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"HTTP GET\"}[10800s])) by (le))\nStep: 15s"
            },
            "fields": [
              {
                "name": "Time",
                "type": "time",
                "typeInfo": {
                  "frame": "time.Time"
                }
              },
              {
                "name": "Value",
                "type": "number",
                "typeInfo": {
                  "frame": "float64"
                },
                "labels": {},
                "config": {
                  "displayNameFromDS": "histogram_quantile(.9, sum(rate(traces_spanmetrics_latency_bucket{span_name=~\"HTTP GET\"}[10800s])) by (le))"
                }
              }
            ]
          },
          "data": {
            "values": [
              [
                1664903449838
              ],
              [
                0.001875063653752962
              ]
            ]
          }
        }
      ]
    },
    "topk(5, sum(rate(traces_spanmetrics_calls_total{status_code=\"STATUS_CODE_ERROR\",span_name=~\"/welcome|/**|HTTP GET|/error|/\"}[$__range])) by (span_name))": {
      "error": "bad_data: invalid parameter \"query\": 1:81: parse error: error parsing regexp: invalid nested repetition operator: `**`"
    }
  }
}
```

**What you expected to happen**:
Relevant `traces_service_graph_` metrics should be queried correctly and data response used to build the service graph for rendering.

**How to reproduce it (as minimally and precisely as possible)**:
This is occurring on a specific stack. Please see @adamquan for details on access to his stack to reproduce.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud v9.1.6-10b38e80 (46a8c21981)
- Data source type & version: Tempo, Grafana Cloud as of 2022/10/04
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by aocenas** [comment] 2023-02-06 15:53
This seems to be a duplicate of this one https://github.com/grafana/grafana/issues/54849. Seems like there is a span name `\**` for some reason and it ends up being interpreted as a regex.

**Closed by aocenas** 2023-02-06 15:53 UTC
Labels: needs investigation, datasource/Tempo

**Comment by chenfango** [comment] 2023-08-25 03:27
> 

hi ,  In which version was this issue fixed
