### ISSUE TITLE
Grafana on TV-Browser

### ISSUE THREAD

**Issue by Becker884** [grafana/grafana#56500] opened 2022-10-06 18:08 UTC
For some time now, Grafana has not been able to be viewed on Smart-TV Browsers:

![1](https://user-images.githubusercontent.com/81651521/194386855-9b3040be-d638-4fb9-91a9-75cb8b665000.jpeg)

Is there a solution for this, e.g. adjusting the configuration ?

I am using Grafana 9.1.7 

Thanks.

**Comment by gelicia** [comment] 2022-10-06 19:05
Duplicate of #56500

Please see this comment specifically https://github.com/grafana/grafana/issues/52486#issuecomment-1194078915

**Closed by gelicia** 2022-10-06 19:05 UTC
