### ISSUE TITLE
{__interval} as integer in seconds

### ISSUE THREAD

**Issue by EmanuelMarioJoos** [grafana/grafana#89449] opened 2024-06-20 06:50 UTC
**Why is this needed**:

I want to sum up multiple signal on the fly. For that i need to first resample them and then sum them up. Depending on the time selection (from, to) i need bigger or smaller resampling frequency.  I have an API that does that. The API accepts as Q-Param *resampling interval* in seconds. The problem is that {__interval} returns 30s, 1m, 5m etc. But i would like to have that in seconds (integer) without units.

something like **{__interval_s}** would be nice. I see that  {__interval_ms} exists but i can not convert that into seconds before the API call. 

Thanks a lot for the help.

**Comment by maurerle** [comment] 2024-06-20 11:56
How are you editing the API?
In many queries you can just send __interval_ms/1000 though I do not know which API you are refering to.

I don't think that it is very useful to add anoter interval variable - instead it would be better to allow calculation on that generally?

**Comment by EmanuelMarioJoos** [comment] 2024-06-21 05:35
Hey thanks a lot for your answer. So the API is a self written one which we also use for other stuff. We use the Infinity plugin to call the API therefore __interval_ms/1000 is not working. It would be nice to allow calculations on that in general. Or do you have any other idea how to get seconds as Int in the API call?

**Comment by maurerle** [comment] 2024-06-21 06:32
As you control the called API yourself, it might be easiest to add an endpoint/param which can handle milliseconds to solve your problem.

If you would like to see a change, you might want to propose something to the Infinity plugin https://github.com/grafana/grafana-infinity-datasource/issues instead of the general Grafana repository.

**Comment by EmanuelMarioJoos** [comment] 2024-06-21 12:41
Thanks for the answer. In principle you are right. But i thought to enable __interval_s which returns second values as integers is maybe something quite general. 

Thanks for the hint about infinity plugin.

**Comment by marefr** [comment] 2024-07-01 11:41
Duplicate of #8751

**Comment by marefr** [comment] 2024-07-01 11:51
Sounds to me like you can either change your API to support milliseconds or either file a request towards https://github.com/grafana/grafana-infinity-datasource so I'll close this. If you still would like this to be opened as a feature request let us know and we'll consider reopen.

**Closed by marefr** 2024-07-01 11:51 UTC
