### ISSUE TITLE
macOS Safari and Grafana v7.1.0 (8101355285): Full page views don't open, some graphs don't show up

### ISSUE THREAD

**Issue by iwittkau** [grafana/grafana#26564] opened 2020-07-23 21:08 UTC
**What happened**: Since updating to Grafana v7.1.0 (8101355285) a graph on one of my dashboards doesn't show up in Safari (works in Chrome) and in general the full page View mode of any visualization shows just a blank page and no visualization.

**What you expected to happen**: Visualizations load normally and the View mode shows a visualization in full page view.

**How to reproduce it (as minimally and precisely as possible)**: Select "view" from a visualization on any dashboard.

**Anything else we need to know?**:

- Everything seems to be working just fine on Google Chrome.
- Multiple machines of macOS Mojave and Safari 13.1.2 show the exact same behavior.

From Safari console when opening a view from a dashboard:

```
flotcharts error
Error: Invalid dimensions for plot, width = 1390, height = 0
(anonyme Funktion) — jquery.flot.js:136
n — jquery.flot.js:114
(anonyme Funktion) — jquery.flot.js:1326
r — jquery.flot.js:714
(anonyme Funktion) — jquery.flot.js:3299
value — graph.ts:527
value — graph.ts:451
value — graph.ts:115
```
**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- Data source type & version: any
- OS Grafana is installed on: linux/Docker
- User OS & Browser: macOS 10.14.6 (18G6020) / Safari 13.1.2 (14609.3.5.1.5)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2020-07-24 05:26
duplicate of https://github.com/grafana/grafana/issues/26442 , fix coming today in 7.1.1

**Closed by torkelo** 2020-07-24 05:26 UTC
