### ISSUE TITLE
Grafana GUI do not work with Chromium browser

### ISSUE THREAD

**Issue by NerijusRazvodovskis** [grafana/grafana#46781] opened 2022-03-21 13:13 UTC
**What happened**:
Grafana GUI stopped to work

**What you expected to happen**:
Grafana GUI working

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/70511397/159267181-6ac3ad61-f60d-4584-817c-9bd92743f7cd.png)
[js.zip](https://github.com/grafana/grafana/files/8315592/js.zip)

**Environment**:
- Grafana version: 8.4.1-1, 
- User OS & Browser: Pop-OS, chromium/focal,now 83.0.4103.116-3pop1 amd64 [installed]

**Comment by leeoniya** [comment] 2022-03-21 13:32
this was fixed in 8.4.4

duplicate of https://github.com/grafana/grafana/issues/46110

**Closed by leeoniya** 2022-03-21 13:32 UTC
