### ISSUE TITLE
Allow LogsPanel to initialize as scrolled to the bottom

### ISSUE THREAD

**Issue by jareware** [grafana/grafana#36629] opened 2021-07-11 12:44 UTC
**What would you like to be added**: I'd like to add a toggle option "Start at bottom" to [`LogsPanel`](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/logs/module.tsx). This would cause the panel to render exactly as before, but as if you'd have immediately scrolled it all the way to the bottom.

**Why is this needed**: If you're one of the folks who enjoy looking at their logs in the Ascending order, there's currently no way to render the panel so that you'd see the most recent log lines first.

---

Looks like this would be quite simple to implement at [`LogRows`](https://github.com/grafana/grafana/blob/c7d2d7079905e8101be4e883bb9890f7f40819ea/packages/grafana-ui/src/components/Logs/LogRows.tsx), by doing a `ref.scrollTop = ref.scrollHeight` after mount if some prop (e.g. `startAtBottom`) is set.

To make this work best, looks like we'd also want to default `renderAll` to `true` in that case.

I'd be happy to take a stab at implementing this, but wanted to check first if the approach would be fine with you (and thus there's a chance the PR would be accepted). 🙂

**Comment by hhromic** [comment] 2021-07-12 00:36
> If you're one of the folks who enjoy looking at their logs in the Ascending order, there's currently no way to render the panel so that you'd see the most recent log lines first.

This is our team! We had to revert all our log panels back to "descending" order when we realised that the log panels always initialise from the top, thus making the "ascending" order a bit useless in panels with more log lines than the size of the panel.

**Comment by zoltanbedi** [comment] 2021-07-14 08:45
This is a duplicate of #33661

**Closed by zoltanbedi** 2021-07-14 08:45 UTC
Labels: area/panel/logs, type/feature-request
