### ISSUE TITLE
Sorry for this, we will investigate. The best short term solution is to use a refresh page browser plugin: https://chrome.google.com/webstore/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc?hl=sv

### ISSUE THREAD

**Issue by zhoumin8023** [grafana/grafana#30052] opened 2021-01-05 04:38 UTC
Sorry for this, we will investigate. The best short term solution is to use a refresh page browser plugin: https://chrome.google.com/webstore/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc?hl=sv

@torkelo  When will this problem be solved?

**Comment by torkelo** [comment] 2021-01-05 06:28
Can you link to the issue? Not sure this this title is very good.

Duplicate of the memory leak issue ?

**Closed by torkelo** 2021-01-05 06:28 UTC
