### ISSUE TITLE
"non-capturing regex" variable interpolation

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#20792] opened 2019-12-02 08:24 UTC
**What would you like to be added**:
a new variable formatting option like "regex_nocapture"

where current "regex" option is:
```
servers = ['test1.', 'test2']
String to interpolate: '${servers:regex}'
Interpolation result: '(test1\.|test2)'
```

the "regex_nocapture" option is:
```
String to interpolate: '${servers:regex_nocapture}'
Interpolation result: '(?:test1\.|test2)'
```

**Why is this needed**:
For chaining of multi-value template variables, if a query regex has an input variable coming *before* the desired capture group, currently you're out of luck because the variable interpolation will hijack the capture.  (Example: `/.*cluster="$cluster".*instance="([^"]+)".*/`, where `cluster` is a multi-value).

the problem is explained in detail here:  https://community.grafana.com/t/use-of-embedded-multi-value-variables-in-regex/13792

**Alternative**:
Allow specifying output format for query variables, so that the desired capture group could be referenced (e.g. `"\2"`).  Having an output format would be useful for a lot of other use cases as well.

**Comment by torkelo** [comment] 2019-12-02 22:15
duplicate of https://github.com/grafana/grafana/issues/4000

**Closed by torkelo** 2019-12-02 22:15 UTC

**Comment by belm0** [comment] 2019-12-02 22:57
@torkelo no-capture seems like a useful primitive that is straightforward to add, and addresses something that is impossible now.  

vs. the proposed exclusion feature request which can be summarized as " regex is hard, please make filtering easier" and has languished for 4 years.

**Comment by torkelo** [comment] 2019-12-02 23:00
the endgoal is the same. You can update that issue with your feature request description if you want

**Comment by fraktury** [comment] 2020-05-12 10:17
Hey, 
I was in the same situation as you and I figured out how to do it: 
(?:${servers:pipe})

The expression "${servers:pipe}" allows you to separate your values by a pipe that you then insert in a non-capturing group 

https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/
