### ISSUE TITLE
IPv6 adress parsing erroneous

### ISSUE THREAD

**Issue by bastischubert** [grafana/grafana#28203] opened 2020-10-12 16:25 UTC
**What happened**:
After turning logging to Debug i noticed that IPv6 is not handled properly:

t=2020-10-12T18:17:38+0200 lvl=dbug msg="Failed to parse client IP address" logger=auth clientAddr=2001:608:0:a00::102d err="failed to split network address \"2001:608:0:a00::102d\" by host and port: net.SplitHostPort failed for '2001:608:0:a00::102d': address 2001:608:0:a00::102d: too many colons in address"

**What you expected to happen**:
Proper handling of IPv6 Adresses

**How to reproduce it (as minimally and precisely as possible)**:
Turn log level to debug, Login to grafana via IPv6 connection

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.2.1 (72a6c64532)
- Data source type & version: does not apply to auth section
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Fedora 32 / Chrome 86.0.4240.75 + Firefox 81.0.1
- Grafana plugins: core + Grafana Image Renderer
- Others:

**Comment by marefr** [comment] 2020-10-13 09:44
Weird. Are you running behind a reverse proxy having header `X-Real-IP` or `X-Forwarded-For` set? If so, what's the value of those? Seems like the IPv6 address is resolved without a port and maybe causing this error?

**Comment by bastischubert** [comment] 2020-10-13 13:37
Yep, it is running behind a reverse Proxy that inserts XFF Header (Just the IP, no Port)
from tcpdump:

`X-Forwarded-For: 2001:608:0:a00::102d`

**Comment by marefr** [comment] 2020-10-20 22:39
I think the problem is here when `defaultPort` is empty:
https://github.com/grafana/grafana/blob/f158e4f526795123a959c77b9e75876cd18a04e2/pkg/util/ip_address.go#L65

**Comment by taciomcosta** [comment] 2020-10-28 00:03
Hello, guys.

I've added a PR that makes IPv6 addresses not surrounded by brackets acceptable.
Let me know for any improvements! :)

**Closed** 2020-11-25 06:55 UTC
Labels: Hacktoberfest, area/backend, help wanted, type/bug
