### ISSUE TITLE
Table rows cannot be set to a specific height.表格不能设定行高 

### ISSUE THREAD

**Issue by tqangxl** [grafana/grafana#93259] opened 2024-09-12 10:20 UTC
### What happened?

The table occupies too much display space.
![image](https://github.com/user-attachments/assets/99234cc6-12d1-4dea-baad-98df2d097c2c)

**What would you like to be added**:
The row height cannot be adjusted. If the table is made more compact, more content can be displayed.

### What did you expect to happen?

It is hoped that the ability to set the font size of text within the table and customize the height of each row in the table will be allowed. This way, the display style can be fully controlled.

24 rows in smaller table
![image](https://github.com/user-attachments/assets/48bf26a9-43ee-4bcc-a240-6e1cdb9669cb)
### Did this work before?

The table occupies too much space, and the content that needs to be displayed cannot all be shown.

### How do we reproduce it?
1.Multiple lines of content are all converted into table display.
2.The converted table content. The table has 50 rows, and some cells contain 200 characters.
3.The table has multiple columns, each with different widths, and the content is fully displayed.
1.多行内容，都转成表格显示，
2.转换后的表格里。含有约50行内容，有的内容有200个字符，
3.表格有多列，每一列的宽度不一样，内容都有完全展示出来

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by malmr** [comment] 2024-11-11 16:27
Duplicate of #65312

**Closed** 2024-11-27 22:04 UTC
Labels: type/feature-request, area/panel/table, automated-triage
