### ISSUE TITLE
7.2 Upgrade Grafana Snapshot: Panels loading with no plot/no data which are using Table, Stat and Bar gauge

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#29005] opened 2020-11-11 04:35 UTC
**What happened**: The panels are loading empty or no data when we generate snapshots on the dashboard where we used plugins like Table with transformations, Gauge, Stat and Bar gauge. Also tried increasing timeout which didn't work.

**What you expected to happen**: Dashboards with any type of plugin should be able to load with data properly in Snapshot.

**How to reproduce it (as minimally and precisely as possible)**: Create a snapshot on a dashboard where we used plugins like Table with transformations, Gauge, Stat and Bar gauge. Please refer Snaphot: https://play.grafana.org/dashboard/snapshot/RrFFR3IWErhDpbXo8mjt2djc5NXs35PI?orgId=1 generated on: https://play.grafana.org/d/0KapoFkMk/1-new-features-in-v7-0?orgId=1&refresh=5s also able to reproduce it locally.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2
- Data source type & version: Any
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: Table with transformations, Gauge, Stat and Bar gauge. 
- Others:

**Comment by papagian** [comment] 2020-11-11 08:27
Thank you for reporting this.

The running grafana version of play.grafana.org is `7.3.1` and when I try to create a snapshot I get an error:
`Error 1406: Data too long for column 'dashboard_encrypted' at row 1`
which is a known issue that it is going to be fixed in the next version by #28831

When you running grafana locally which version do you use?
Can you share your server's logs? Do you see any errors when creating the snapshot?

**Comment by satyatechy** [comment] 2020-11-11 09:33
Hi There,

I am using Grafana v7.2.1 
Attched my log: [grafana.log](https://github.com/grafana/grafana/files/5523093/grafana.log)
I don't see any error while generating.

When we generate snapshot locally, the last panels are loading with no data with an unauthorized error message: ![image](https://user-images.githubusercontent.com/65600879/98793670-39197f80-242e-11eb-8402-6135f35774f9.png)

Whereas published to raintank working fine: https://snapshot.raintank.io/dashboard/snapshot/bmJ8HlEJwM0ncoxYaibOWBVuvSt82gvB

**Comment by papagian** [comment] 2020-11-11 14:20
Which datasource are you using for the panels that have no data or are unable to authorise? How they are configured?

When loading the dashboard all the panels are loading correctly and the problem is occurs only when loading the snapshot?

Also, I see an error in your log about registering stackdriver plugin.
Can you check if under `C:\Program Files\GrafanaLabs\grafana\data\plugins` whether you have both `cloud-monitoring` and `stackdriver` directories? If so, can you delete the `stackdriver` directory, restart grafana and retry to take the snapshot.

**Comment by papagian** [comment] 2020-11-11 14:22
I'm able to reproduce the empty tables in the dashboard by running the latest master 2c724e0aa2 and trying taking a local snapshot of [this](https://github.com/grafana/grafana/blob/master/devenv/dev-dashboards/panel-table/table_tests_new.json) dashboard.

**Closed** 2020-11-17 09:25 UTC
Labels: area/dashboard/snapshot, priority/support-subscription, type/bug
