### ISSUE TITLE
Grafana not using token sent by Keycloak

### ISSUE THREAD

**Issue by MichelS08** [grafana/grafana#34498] opened 2021-05-20 13:15 UTC
**What happened**:
We have Grafana successfully integrated with Keycloak.
during the AuthN process, keycloak do send the "access token,  and refresh token to grafana.

I can see that Grafana successfully receives the tokens and stores them in the "user_auth" DB table.
Also Grafana creates a new token stores the info in user_auth_token Table.

At this point, the session is using the created token by Grafana where it will be rotated/refreshed and expired based on the (login_maximum_inactive_lifetime_duration/token_rotation_interval_minutes parameters) instead of using the Token generated by keycloak and use the refresh/expire settings of that token

Below is the relevant "auth.generic_oauth" configuration 

`name = keycloak
enabled = true
allow_sign_up = false
client_id = grafana-server-stg
client_secret = secret
scopes = openid profile email address
auth_url = https://<keycloak URL>/auth/realms/NuanceCustomers/protocol/openid-connect/auth
token_url = https://<keycloak URL>/auth/realms/NuanceCustomers/protocol/openid-connect/token
api_url = https://<keycloak URL>/auth/realms/NuanceCustomers/protocol/openid-connect/userinfo
signout_redirect_url = https://<keycloak URL>/auth/realms/NuanceCustomers/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fgrafana-sharedservices`

Can You please advise if We're missing something in our config that enforce  Grafana to get a refreshed token from keycloak, or the is an issue?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.6-1
- Data source type & version:
- OS Grafana is installed on: CentOS Linux release 7.9.2009
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by MichelS08** [comment] 2021-05-26 13:54
Hello community, Anyone having the same issue where grafana doesn't use the token sent by keycloak (for refresh/expire/..)

**Comment by dsotirakis** [comment] 2021-05-27 08:07
Duplicate of #12131?

**Comment by MichelS08** [comment] 2021-05-27 13:50
looking at #12131 the root cause might be the same as I'm facing, Grafana is not using the token sent by the Oauth IDP (keycloak)
But the issue seems to fixed by adding  login_maximum_inactive_lifetime_duration/token_rotation_interval_minutes parameters.

In my case, Grafana do refresh and expire the token/session based on what I have configured in login_maximum_inactive_lifetime_duration/token_rotation_interval_minutes parameters instead of using/refreshing/expiring the token sent by keycloak and based on the exp/refresh params of that token.

**Comment by marefr** [comment] 2021-05-31 08:29
Duplicate of #12131

**Comment by marefr** [comment] 2021-05-31 08:30
Grafana doesn't support expiration/refresh of external auth token in relation to Grafana's own auth token rotation. The referenced issue is there to track that specific request.

**Closed by marefr** 2021-05-31 08:30 UTC
Labels: area/backend/auth, type/question
