### ISSUE TITLE
Allow OAuth authentication with minimal userinfo

### ISSUE THREAD

**Issue by acdha** [grafana/grafana#13141] opened 2018-09-04 19:53 UTC
Using v5.1.5 I was trying to setup authentication using a commercial IdP which has a very limited userinfo endpoint which returns only a single value, causing Grafana to fail the login because it can't get an email address:

```json
{
    "aud": null,
    "sub": "…",
    "unique_name": "username@example.org"
}
```

It'd be nice if this was at least minimally usable as would be the case with HTTP Basic authentication.

**Comment by marefr** [comment] 2018-09-05 07:55
Duplicate of #12986

**Closed by marefr** 2018-09-05 07:55 UTC
