### ISSUE TITLE
Table panel hiding the value on the right in FireFox

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#24978] opened 2020-05-21 10:50 UTC
**What happened**:
The new table panel is hiding a part of the value in the last column on the right if the scrollbar is present and the alignment of the column is set to Right.

This is happening in FireFox only (Chrome has a thinner scrollbar and it looks like there is none in Edge). 

No scrollbar:
![Grafana Play Home Grafana no scrollbar](https://user-images.githubusercontent.com/56955081/82551648-dd49fa00-9b60-11ea-994d-b9e117c46b9c.png)

With Scrollbar:
![Grafana Play Home Grafana scrollbar](https://user-images.githubusercontent.com/56955081/82551685-f0f56080-9b60-11ea-87b7-7864e6e1c358.png)

**What you expected to happen**:
The full value of the right column should show when the scrollbar appears in the table.

**How to reproduce it (as minimally and precisely as possible)**:
Go to this panel on play.grafana.org using FireFox:

https://play.grafana.org/d/000000012/grafana-play-home?editPanel=2&orgId=1

Change visualization to Table and the issue will appear.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: N/A
- User OS & Browser: Windows 10, FireFox 76.0.1

**Comment by torkelo** [comment] 2020-05-22 08:36
duplicate of https://github.com/grafana/grafana/issues/24872

**Closed by torkelo** 2020-05-22 08:36 UTC
