### ISSUE TITLE
Specify desired step in Prometheus in dashboard panels

### ISSUE THREAD

**Issue by zemek** [grafana/grafana#9705] opened 2017-10-27 21:30 UTC
Previously we used to be able to specify the step parameter in Prometheus. This was changed in https://github.com/grafana/grafana/pull/8073

It would be nice to be able to get this functionality back to be able to display brief spikes in graphs.

**Comment by atonkyra** [comment] 2017-11-01 21:30
This would be pretty awesome to have back. Right now some fast moving gauges are impossible to render correctly.

The animation at https://gyazo.com/f83dc32078209a7e6a4a87efe5b4e81b illustrates the problem pretty well.

**Comment by MarcMagnin** [comment] 2017-11-09 14:01
This would be quite nice to have it back. Any idea when this could be done if it is planned?

**Comment by MarcMagnin** [comment] 2017-11-14 15:15
For reference there is a discussion on prom github as well: https://github.com/prometheus/prometheus/issues/2364
Basically without an enforced step on a metric which is not a counter (using the rate trick), there is no way to render properly a chart on each refresh when the time range is higher than 1h.

**Comment by SeerUK** [comment] 2017-11-30 15:59
I've also just left a comment on that issue explaining what I've found about the issue. Realistically I think this is something that Prometheus should handle, but it's something that Grafana may be able to deal with on it's own too - I'm still experimenting with it really.

**Comment by thenayr** [comment] 2017-12-04 22:24
With this change in place I can't get metric resolution lower than 15s intervals (we actually use 10s resolution for all metrics).   

I also have all of the issues mentioned above with spiky charts jumping around needlessly.

**Comment by dprittie** [comment] 2017-12-05 15:39
I am also unable to get a metric resolution lower than 15s - we have some prometheus targets that scrape every 500 ms and we unable to properly observe this data which is a serious breaking change for us :(

if anyone has figured out a way to get lower than 15s please share!

**Comment by torkelo** [comment] 2017-12-05 17:14
Have you set the min step/interval option on the datasource options page? You can also override it on per panel or query level

**Comment by atonkyra** [comment] 2017-12-05 17:23
@torkelo the problem is the fact that it is _min_ step. We can define the minimum step but not the maximum step which in turn causes us to end up overstepping high frequency polled data. (see my picture above for example, with that the min step was set to 1s on 10s interval polled data)

**Comment by SeerUK** [comment] 2017-12-05 17:37
One option to help with this issue is to use an `*_over_time` aggregation query, and set the time period to `$__interval`, this will scale to the step size. Unfortunately, it doesn't completely solve the problem.

**Comment by torkelo** [comment] 2017-12-05 20:35
Not sure I understand, you want grafana to query for more data points than there are pixels in the graph? Say you set a max step your query will return too much data.

Prometheus have range selectors and functions that should allow you to get what you want, using the interval variable can help

**Comment by atonkyra** [comment] 2017-12-05 20:56
@torkelo okay let's simplify it

I have data with resolution of 1 value per 10 seconds. Now if I want to show all the data and want to see the spikes, what would be the logical step in a 5 minute graph? I'd say it's 10 seconds.

Okay, now lets set min step to 10s for the fun of it. Graph keeps changing *completely* _every_ reload!? Okay let's examine what we send to Prometheus:

```
GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=...&start=1512506717&end=1512507017&step=15
```

See the step 15? That basically means that we are stepping *over* *existing* values. Let's look at this on a timeline.

```
0s  10s  20s  30s  40s  50s  60s
+----+----+----+----+----+----+---- ...
0    1   100   0    1   100   0
^      ^       ^      ^       ^

+ = value interval
^ = where step happens to land at
```

Now looking at that we see that the spikes of 100 may be jumped over due to the misaligned step. Prometheus might report 1 or 100 on the 15 second marker depending on which side the step happens to land at.

I hope this explains the problem better.

**Comment by atonkyra** [comment] 2017-12-05 21:21
@bmildren okay, I didn't even know there was such setting, setting that to the minimal value of any scrape job you have will fix the problem.

I still think defaulting to anything hard-coded is utterly broken.

**Comment by atonkyra** [comment] 2017-12-05 21:52
If we wanted some automation, one could use /api/v1/status/config API endpoint on Prometheus. The contents are in yaml so that would need parsing. Grafana could then perform a match on the job key and failing that, fallback to global scrape interval on the config.

**Comment by torkelo** [comment] 2017-12-06 08:09
> I still think defaulting to anything hard-coded is utterly broken (on the lower bound). At the very least it should be configurable on the graph.

Grafana defaults to the same default prometheus use. And nothing is hard coded as you can change it. However I can still see a problem here as Grafana should align step in even intervals of the min step / scrape interval option

**Comment by bergquist** [comment] 2017-12-06 10:11
FYI that setting is only available in the night builds.

**Comment by atonkyra** [comment] 2017-12-06 11:00
I'd say we still need a per-graph (or query?) "scrape interval" field and when that is absent default to the global on the datasource. Let's say I have a Prometheus instance with default scrape interval of 10s but I happen to have some data at 1s and some at 60s.

Single global default just doesn't make sense for many Prometheus installations IMHO.

**Comment by bergquist** [comment] 2017-12-06 14:32
It's now possible to set min interval per panel in the nightly build
![image](https://user-images.githubusercontent.com/618863/33666558-aaf2ac98-da9a-11e7-813c-b79249d40757.png)

**Comment by zemek** [comment] 2017-12-08 17:10
FWIW my original issue is actually solved by using `max_over_time(my_metric{}[$__interval])`

**Comment by matejzero** [comment] 2017-12-14 17:40
This is a showstopper for us. We are trying to migrate to Prometheus from Graphite and not having consistent graphs doesn't work for us:)

It's really hard to debug an issue on the system when graphs are constantly changing.

Will follow this thread and provide info if needed.

**Comment by thenayr** [comment] 2017-12-14 19:06
I believe Grafana `4.6.3` release today addresses this https://github.com/grafana/grafana/commit/8a1616305ca3a1958f8c61ec12db3c8f98dc2c23

**Comment by matejzero** [comment] 2017-12-14 20:54
I upgraded to 4.6.3 but it doesn't seem to fix my issue.

I have set scrape interval in data source to 10s and this is what I get:
![output_jhx70k](https://user-images.githubusercontent.com/4689252/34013745-fd1ab234-e118-11e7-86be-ac18e7ef2b5c.gif)

This are 2 graphs with reload time of 1 minute. This is quire irritating when you debug an issue on the system.

**Comment by bmildren** [comment] 2017-12-14 21:13
In this case, isn't that just an artifact of irate?  irate is based on the last two data points in the range vector ( https://prometheus.io/docs/prometheus/latest/querying/functions/#irate() ), here you're looking at the graph 1 minute later so the last two data points in each of the 5m ranges are going to different no matter what you set your scrape interval to.  🤔

**Comment by matejzero** [comment] 2017-12-14 21:43
Could be, now that I think of it (I'm a total Prometheus noob). Should using rate() function solve the problem, because I see the same problem with rate().

**Comment by atonkyra** [comment] 2017-12-14 22:18
Does resolution 1/1 help at all?

I think we still have a problem with this which I believe is that the dashboard refreshes aren't aligned to the step (which I believe @torkelo mentioned earlier), example:

```
scrape interval 10s, min step 15s

S = scraped value
! = step

                   S-----S-----S-----S-----S-----S ...
initial            !        !        !        !    ...
reload after 5s       !        !        !        ! ...
reload after 10s         !        !        !       ...
```

So basically when we have uneven scrape/step intervals we ultimately have situation where step causes us to hit completely different values on each refresh.

**Comment by thenayr** [comment] 2017-12-14 22:37
Setting your resolution to 1/1 on that chart *should* fix it

**Comment by craig-miskell-fluxfederation** [comment] 2017-12-15 03:13
As zemek  mentioned above, when using rate, you can now use $__interval as the range vector range.  Grafana still varies the step based on the graph time range + resolution, but that value ends up as $__interval, and by passing that to Prometheus, you get a rate over the 'step' period, rather than a hard coded one which might be two short for the current step.
Example:
rate(node_disk_bytes_read{instance="$server"}[$__interval])

I'm not sure there's any sensible solution for irate (being a rate over the 'last two samples'), but that's a really hard problem to solve I think.

**Comment by matejzero** [comment] 2017-12-15 07:50
@atonkyra: setting the resolution to 1/1 fixes it for some cases. I can get it to work IF:

- step is set to a multiple of scrape interval (my scrape interval is 10s)
- refresh interval is set to the same value as step (if step is 30, my graphs must reload every 30s

So I can have nice graphs for 3h/10s reload or 12h/30s reload. 6h fails, because step is set to 15.

So 12h graphs looks like so:
```
scrape interval 10s, step 30s

S = scraped value
! = step

                   S---S---S---S---S---S---S---S---S---S---S---S---S---S ...
initial            !           !           !           !           !...
reload after 30s               !           !           !           !...
reload after 60s                           !           !           !...
```

15s step obviously breaks it.

@thenayr what is your scrape rate and the range vector for irate functions? 

@craig-miskell-fluxfederationI'm having some problems with $__interval as well. If I set scrape interval in datasource to 10s, then $__interval sets range vector to 10s on small time ranges which means I get no graph, since range vector is not 2*scrape interval. Is that a bug?

**Comment by craig-miskell-fluxfederation** [comment] 2018-01-02 20:53
@matejzero Not sure about bug, but it doesn't do that for me.  For a data series where the scrape interval was 10s I can zoom in to a 1 minute range and still get a graph; the step grafana is using is 30s.  Closer than that gives a blank graph, but I don't think it's unreasonable for it to fail a rate-based query at some very short requested intervals.  Grafana 4.6.2, FWIW.

**Comment by craig-miskell-fluxfederation** [comment] 2018-01-04 03:51
Can confirm that making from + to an integer multiple of step, and using $__interval in the rate expression, makes things really solid.  Will submit a PR tomorrow.

**Comment by haizaar** [comment] 2018-01-04 08:48
> Edit: After having experimented a little, Grafana could handle this if Prometheus doesn't, by ensuring that steps always contained the same points, i.e. if the step size is 15s, maybe each step should be one of these parts of a minute: 0-15s, 15-30s, 30-45s, or 45-60s. So, if now was 36 seconds into a minute, prometheus would be queried for 45s into that same minute (i.e. into the future). In this case, prometheus does actually seem to return the latest information for the last point which means that the last point will change, but once we get passed it it would always remain the same from then on.

We've took this approach solving similar problem in the other project and it worked wonders in making graphs "stable". We are rounding up the interval to the closest divisor of the minute, hour, etc and then rounding from/to values to the start/end on the interval boundary. Hopefully Grafana can have this behavior as an option one day.

**Comment by free** [comment] 2018-01-30 11:14
FYI I'm trying to convince Prometheus developers that their current implementation of `rate`/`increase`/`delta` is broken because (particularly given the Grafana approach of requesting one data point every `$__interval` and allowing you to use the same `$__interval` as your range argument) it will split the timeseries into non-overlapping ranges and compute the rate/increase only by looking at the points contained in the range and using extrapolation to try and guess the points immediately outside the range. This means that with an underlying resolution of 5 seconds and a range of 10 seconds, Prometheus will only use every second increase (e.g. [0, 5], [10, 15], [20, 25] etc.), throw away the rest of the data and attempt to guesstimate the data it threw away by extrapolating.

This is only one of the causes of jittery graphs. There are other problems too, as pointed out in this thread, but fixing this would be one step forward. Adding Grafana support for optionally aligning the start and end with a multiple of `$__interval` would pretty much solve all others. The Prometheus issue is prometheus/prometheus#3746, you can vote on it (whether up or down).

I also proposed a solution, prometheus/prometheus#3760. It essentially replaces the whole complex logic of when and by how much to extrapolate with a difference between the last value in the range and the last value before the range. There are a couple of benefits to this approach:
1. No data is thrown away. A sum of all increases will actually match the change in the underlying counter.
2. You can now calculate a rate/increase at the resolution of the underlying data. Even higher, if you want to, but you'll still only get one data point for every underlying data point and Grafana will not connect the dots with lines.

Please play with it if you have time and let me know if it does anything for you. Or whether it causes other problems.

**Comment by craig-miskell-fluxfederation** [comment] 2018-01-30 19:05
That is really funny/ironic: I spent half of last weekend discovering exactly the same thing about the extrapolation (because I had some pathological data sets where the value didn't increase over $interval but did immediately before and after, so my graphs would go to 0 when the time periods aligned Just Right.)
Thanks for pointing out the Prometheus issue reports; I'll see what I can add to them.

**Comment by jgracenin** [comment] 2018-03-28 13:12
@free -- thanks for your xrate V2 work. I finally have accurate Prometheus graphs. For my data (e.g. network error counters), rate extrapolation doesn't work well.

I tried posting [this experience report](https://gist.github.com/jgracenin/3d4d5849f34f4cc9c676f2cc5b7faef2) to the prometheus-dev thread (even after becoming a sub), but my reply is always deleted (spam?). I also mentioned it in their IRC yesterday, but I was ignored. I give up :)

FWIW, Borgmon doesn't extrapolate rates. From the [Google SRE book alerting chapter](https://landing.google.com/sre/book/chapters/practical-alerting.html):
> The rate() function takes the enclosed expression and returns the total delta divided by the total time between the earliest and latest values.

It's unclear if both approaches are needed in the future, but xrate is a substantial improvement over rate for my data.

Since they closed your PR, I'm now just going to promote xrate/xincrease in place of the original rate funcitons in my 2.0.0 build. Hopefully, rate will improve someday and I'll just use the official release. I can't afford to wait to see if that ever happens.

**Comment by leoluk** [comment] 2018-03-28 13:45
I'm also running the xrate patch in one production setup in order to deal with a customer's slow moving counter and I can confirm that it works fine. I'd love to see this merged, constantly rebasing it on top of the master gets tiresome.

I understand why it hasn't been merged, but it does solve a real issue that people have.

**Comment by free** [comment] 2018-03-28 15:06
With apologies for hijacking this thread, I am considering maintaining a Prometheus fork with the `xrate`/`xincrease` additions. It's far from an ideal solution, but seeing how the `xrate` proposal is going nowhere (and my posts to the Prometheus dev group also get consistently marked as spam), it's at least something. Would that help anyone?

**Comment by haizaar** [comment] 2018-03-28 15:36
Hi Alin,

I red most of your other threads on the subject and I much admire your
persuasiveness.

While I like p8s/grafana a lot, I find it practically useless for slow
moving counters. The fact that p8s considers range query as (,) intervals
and not as [,) intervals was quite surprising.

Therefore I will be eager to try your xrate function and friends.

If you can maintain a docker image that is similar to upstream releases +
your patches, that would be absolutely awesome.

Thanks again.

**Comment by matejzero** [comment] 2018-04-19 19:31
@free could you update your fork to 2.2.1 version? I tried it myself and I get some conflicts. Are you still planning to maintain the fork?

**Comment by free** [comment] 2018-04-22 17:30
Will do, tomorrow (I think I might already have the code, just not pushed).
Saw your post on Friday but I was too busy at work (and too lazy to
respond).

**Comment by free** [comment] 2018-04-23 08:52
Done, updated fork is at https://github.com/free/prometheus/tree/xrate_v2.2.1

Haven't tested it, as I'm still very busy this week, but my last tested changes were made just days before the 2.2.1 release on then top-of-tree code.

**Comment by matejzero** [comment] 2018-04-24 05:39
Thank you.

I have some weird acting counter graphs and will test it with your patch to see if it improves the output.

**Comment by matejzero** [comment] 2018-04-24 06:42
I'm not sure if I'm doing something wrong or what, but it seems like Prometheus won't accept xrate function.

`xrate(node_cpu{cpu="cpu0",instance="node.domain.tld",job="node",mode="iowait"}[60s])`
`Error executing query: parse error at char 6: unknown function with name "xrate"`

Looking at build information, I'm running the right version:
```
# ./prometheus --version
prometheus, version 2.2.1 (branch: xrate_v2.2.1, revision: f3e781a5af599a76edbf1c2f61a4a57ce48b371d)
```

Am I doing something wrong?

**Comment by free** [comment] 2018-04-24 08:26
Weird. I just built it locally (make build in the root dir) and it seems to
be working just fine. Maybe I need to make an actual release, with a binary
and all.

Also, we should probably move this discussion to an issue in the fork
itself, so we don't spam everyone.

>

**Comment by matejzero** [comment] 2018-04-24 08:48
I'll give it another try:)

I wanted to open the ticket there, but issue tracker is not available in the fork:) Do you have to enable it manually?

**Comment by free** [comment] 2018-04-24 12:04
Weird, again. I did indeed have to explicitly enable the issue tracker in the fork. It's up and running now, let's move this discussion there.

**Comment by geekdave** [comment] 2018-04-24 15:02
Could you please link to the fork here so us lurkers can follow along? :-)

**Comment by free** [comment] 2018-04-24 15:13
Sure, it's http://github.com/free/prometheus

And the 2.2.1 branch is https://github.com/free/prometheus/tree/xrate_v2.2.1

**Comment by free** [comment] 2018-06-08 08:00
FYI, I've just made a Prometheus 2.3.0 + `xrate` release, at https://github.com/free/prometheus/releases/tag/xrate_v2.3.0

Prometheus 2.3.0 has significantly improved the performance of range queries (which is where Grafana and `xrate` come together), so you may want to give it a whirl.

**Comment by matejzero** [comment] 2018-06-08 08:18
Great! I'm already running it on our Prometheus and so far it looks good:)

**Comment by zemek** [comment] 2018-07-05 23:00
is this effectively resolved in grafana 5.2 with https://github.com/grafana/grafana/pull/10434 ?

**Comment by gjcarneiro** [comment] 2020-01-25 11:51
I have similar problems due to step.  My metric is something like:

```
sum(max_over_time(pricefeed_num_clients}[15m]))
```

Now, if tick the Instant checkbox I get a URL that includes time=xxxx, and that's it.

If I untick the Instant checkbox, I get a URL that includes start=xxxx&end=yyy&step=300.  Due to the step=300, I actually get a max_over_time, in a period of a few hours, that can be actually lower than the max_over_time I get with the Instant mode.  Which is mathematically impossible.

I just want to get rid of the `step=300` because it's screwing up with the calculation.  I tried subquery syntax, `sum(max_over_time(pricefeed_num_clients}[15m:1m]))`, but it makes no difference.

**Comment by zekth** [comment] 2020-01-27 16:09
Still no solution for this?

**Comment by davkal** [comment] 2020-05-10 19:59
If you want to set a fixed step, you can do this in Explore. But for dashboard panels we have not settled on a solution yet.

**Comment by sksingh20** [comment] 2021-05-27 13:28
Does this mean Grafana is not right tool for historical data view as this represent data wrongly and will completely mislead analysis and reporting?

Changing step value on fly is changing full data view resulting to wrong reporting... Please confirm so that same will be communicated to CXO forums.

**Comment by leoluk** [comment] 2021-05-27 19:10
> Changing step value on fly is changing full data view resulting to wrong reporting... Please confirm so that same will be communicated to CXO forums.

Prometheus is fine for analytics, but as with any data source, it's important to understand its properties/limitations. For reporting, you'll want to use an aggregation function like sum_over_time.

**Comment by sksingh20** [comment] 2021-05-27 20:12
@leoluk I think you mistaken to read problem condition. This appears to me that query is built at grafana level dynamically and not prometheus level. So 
(1) How this is limitation at data source?
(2) Grafana is adding step value in query to reduce data points, which eventually loosing key data value itself!!
(3) can you help with a sample dashboard to find out all power outage in last 7 days or any longer duration on a dashboard?

**Comment by leoluk** [comment] 2021-05-27 21:03
This sounds like a question for the [community](https://prometheus.io/community) or commercial support through a company like [Robust Perception](https://www.robustperception.io/).

When you query a data source to build a graph, you need either sampling (i.e. only looking at every n-th data point) or aggregation (min/max/quantiles) to reduce the number of data points to something that can be displayed in a graph. Grafana instructs Prometheus to sample data - via the step parameter - depending on the zoom level to render data at an appropriate resolution. If you zoom out, resolution will go down. There's a hardcoded limit on how many data points Prometheus will return in a single query.

This issue is about noisy graphs being unstable as a result, since a different set of data points are sampled each time you request it.

**Comment by sksingh20** [comment] 2021-05-28 05:13
@leoluk This makes limitation on gauge data type on grafana. Gauge is actually to show all data points. I see sole objective of dashboard to show actual guage values.
Even if limitation of grafana technical approach, business case is quite clear. If something can't be done using grafana then its just matter to confirm and communicate. 

Can we summarize that Grafana is having limitation to show gauge value properly for data older than 12 hours? and there is high probability that this will show error.

**Comment by leoluk** [comment] 2021-05-28 13:20
Your monitor wouldn't even have enough pixels to show all data points, depending on the resolution. This is not a Grafana limitation, it's a fundamental property of working with time-series data.

**Comment by aocenas** [comment] 2021-06-16 08:57
I guess we could do something like a dropdown select with (max|exact|min)[step] so that user can decide how the step param should be evaluated.

**Closed** 2021-07-28 06:26 UTC
Labels: area/datasource, datasource/Prometheus, effort/small, onboarding, priority/important-longterm, type/feature-request
