### ISSUE TITLE
Existing board from v9.3.8 fails to initiate in 9.4.x

### ISSUE THREAD

**Issue by Klaboe** [grafana/grafana#65247] opened 2023-03-23 08:30 UTC
**What happened**:
After upgrading from v9.3.8 to 9.4.3 some boards suddenly refused to initiate

**What you expected to happen**:
To actually initiate; and if not, i would like to know why.

**How to reproduce it (as minimally and precisely as possible)**:
* Have a board-model with a schemaVersion lower than 38 and a panel that specifises fieldConfig, but NO overrides
* Observe it working in grafana 9.3.x
* Observe it lead to a 

![image](https://user-images.githubusercontent.com/126390/227141467-82a89477-7e8a-4af7-952b-a511dd94efdc.png)
in 9.4.x

**Anything else we need to know?**:

After poking around it looks to be the fault of an addition in `DashboardMigrator.ts::828.` This nested loop: 

```
for (let i = 0; i < panel.fieldConfig.overrides.length; i++) {
      for (let j = 0; j < panel.fieldConfig.overrides[i].properties.length; j++) {
        (...)
     }
}
```

assumes that the variable `overrides` always will be present, which it obviously is not (and it repeats its mistake and assumes that whatever lies in an override will have `properties`).

Existing boards that uses `fieldConfig` but has no override will thus get an Undefined and not load.

It is also not ideal to be completely blocked out of observing ones JSONmodel and board versions when this happens. As shown in the picture there is no way to get to settings for the board.

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: Prometheus/Thanos
- OS Grafana is installed on: Kubernetes (GKE v.1.24. probably a linux-image)
- User OS & Browser: Windows/macOS/Linux & Chrome/Firefox/Vivaldi
- Grafana plugins: Polystat v.2.0.4
- Others: N/A

**Comment by axelavargas** [comment] 2023-03-27 12:45
Hello @Klaboe 👋🏾 , thank you for bringing this issue to our attention 🎖️.  I tried to reproduce it but was not able to do so 😞. I also checked the insight about the migrator and noticed that the migration is applied for the `Table panel`. (Is your dashboard using that panel?) Additionally, our [PanelModel `overrides` is initialized as an empty arra](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/PanelModel.ts#L130)y, so I don't think this is the root cause of your issue.

To move forward, would it be possible for you to provide the dashboard JSONs generated in both v9.3.8 and v9.4.3?

Thank you 🙏🏾 

_ps, make sure to export the dashboard json for sharing externally_

<details>
<summary>Steps to share Dashboard Json</summary>

Click the Share Dashboard Icon
![image](https://user-images.githubusercontent.com/562238/104685855-4f78db80-56fc-11eb-9cd4-658a850181c1.png)

Click on Export, and Click on Export for sharing externally
![image](https://user-images.githubusercontent.com/562238/121632873-11e96600-ca82-11eb-8884-24e8ec6c6da8.png)

Click View JSON and then Copy it to Clipboard
![image](https://user-images.githubusercontent.com/562238/121632928-2cbbda80-ca82-11eb-832f-c42255a8aa57.png)

</details>

**Comment by axelavargas** [comment] 2023-03-27 12:45
Hello @Klaboe 👋🏾 , thank you for bringing this issue to our attention 🎖️.  I tried to reproduce it but was not able to do so 😞. I also checked the insight about the migrator and noticed that the migration is applied for the `Table panel`. (Is your dashboard using that panel?) Additionally, our [PanelModel `overrides` is initialized as an empty arra](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/PanelModel.ts#L130)y, so I don't think this is the root cause of your issue.

To move forward, would it be possible for you to provide the dashboard JSONs generated in both v9.3.8 and v9.4.3?

Thank you 🙏🏾 

_ps, make sure to export the dashboard json for sharing externally_

<details>
<summary>Steps to share Dashboard Json</summary>

Click the Share Dashboard Icon
![image](https://user-images.githubusercontent.com/562238/104685855-4f78db80-56fc-11eb-9cd4-658a850181c1.png)

Click on Export, and Click on Export for sharing externally
![image](https://user-images.githubusercontent.com/562238/121632873-11e96600-ca82-11eb-8884-24e8ec6c6da8.png)

Click View JSON and then Copy it to Clipboard
![image](https://user-images.githubusercontent.com/562238/121632928-2cbbda80-ca82-11eb-832f-c42255a8aa57.png)

</details>

**Comment by axelavargas** [comment] 2023-03-27 12:52
Hello @Klaboe 👋🏾 , thank you for bringing this issue to our attention 🎖️.  I tried to reproduce it but was not able to do so 😞. I also checked the insight about the migrator and noticed that the migration is applied for the `Table panel`. (Is your dashboard using that panel?) Additionally, our [PanelModel `overrides` is initialized as an empty arra](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/PanelModel.ts#L130)y, so I don't think this is the root cause of your issue.

To move forward, would it be possible for you to provide the dashboard JSONs generated in both v9.3.8 and v9.4.3?

Thank you 🙏🏾 

_ps, make sure to export the dashboard json for sharing externally_

<details>
<summary>Steps to share Dashboard Json</summary>

Click the Share Dashboard Icon
![image](https://user-images.githubusercontent.com/562238/104685855-4f78db80-56fc-11eb-9cd4-658a850181c1.png)

Click on Export, and Click on Export for sharing externally
![image](https://user-images.githubusercontent.com/562238/121632873-11e96600-ca82-11eb-8884-24e8ec6c6da8.png)

Click View JSON and then Copy it to Clipboard
![image](https://user-images.githubusercontent.com/562238/121632928-2cbbda80-ca82-11eb-832f-c42255a8aa57.png)

</details>

**Comment by Klaboe** [comment] 2023-03-28 10:51
> Hello @Klaboe 👋🏾 , thank you for bringing this issue to our attention 🎖️. I tried to reproduce it but was not able to do so 😞. I also checked the insight about the migrator and noticed that the migration is applied for the `Table panel`. (Is your dashboard using that panel?) 

The panel is of type "Table", yes. Do we call segments of a dashboard a dashboard as well? 😅 I am not sure what to call the smaller and smaller parts :D  

>Additionally, our [PanelModel `overrides` is initialized as an empty arra](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/state/PanelModel.ts#L130)y, so I don't think this > is the root cause of your issue.

Not sure how far back that has been the case; our schema-version is at 14. The root problem is probably in that it is very old 😅, but the problem is that there is an assumption that pre-existing uploaded dashboards conforms with later standards/types (or even lack of enforcing of said standards earlier); i.e that this field _must_ exist. Case in point that this was not a problem for earlier versions of grafana.

I would recommend to have some undefined-checks in the code i highlighted to mitigate that specific problem
 
> To move forward, would it be possible for you to provide the dashboard JSONs generated in both v9.3.8 and v9.4.3?

I can not get the dashboard for how it is generated in v9.4.3 as it is impossible to extract. It is not possible to enter into the settings to get to the JSONmodel. And i dont have access to grafana 9.3.8 anymore.

_I can_ show the part of the dashboard that we upload though; i do believe this will still make it fail

```
(...)
{
          "datasource": {
            "type": "prometheus",
            "uid": "000000002"
          },
          "fieldConfig": {
            "defaults": {
              "decimals": 0,
              "unit": "short"
            }
          },
          "id": 19,
          "targets": [
            {
              "expr": "<some expression that will only work with our prometheus data>",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "{{name}} - {{domain}}",
              "refId": "A"
            }
          ],
          "title": "Keys",
          "transformations": [
            {
              "id": "reduce",
              "options": {
                "labelsToFields": true,
                "reducers": [
                  "lastNotNull"
                ]
              }
            },
            {
              "id": "sortBy",
              "options": {
                "sort": [
                  {
                    "desc": true,
                    "field": "Last *"
                  }
                ]
              }
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Field": true
                },
                "indexByName": {
                  "Field": 0,
                  "Last *": 3,
                  "domain": 2,
                  "name": 1
                },
                "renameByName": {
                  "Last *": "count"
                }
              }
            }
          ],
          "type": "table"
}
(...)
```

**Comment by polibb** [comment] 2023-05-18 12:40
Hi @Klaboe 👋,

It looks like this issue has been caught and fixed by @ryantxu here: https://github.com/grafana/grafana/pull/66305. 
When you upgrade to 9.5.0 you should have the fix! 

I will close this issue now, thanks to this development. If there's still a problem when you upgrade, please reopen it.

**Closed by polibb** 2023-05-18 12:40 UTC
Labels: area/dashboard, triage/needs-confirmation
