### ISSUE TITLE
Datasources incorrectly marked as read only in the API

### ISSUE THREAD

**Issue by Sytten** [grafana/grafana#18489] opened 2019-08-09 22:16 UTC
**What happened**:
If you create a datasource in the UI and you then fetch it with the API, the field `readOnly` will always be `true`.

**What you expected to happen**:
It should be correctly set depending on the real status of the datasource.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `Testdata DB` named `Test`
2. Do `GET /api/dashboards/name/Test`
3. Check if the field `readOnly` is true

**Environment**:
- Grafana version: 6.2.5

**Comment by torkelo** [comment] 2019-08-10 08:42
You say to 2 contradicting things 

> the field readOnly will always be true

> 3. Check if the field readOnly is false

I created a couple of data sources using UI and all had readOnly = false, which is what it should be, only provisioned data sources have readOnly = true

**Comment by Sytten** [comment] 2019-08-11 04:35
My bad, I fixed my filling. This is really weird, it was not the case in my production system (grafana deployed with helm on EKS). I can reproduce it consistently, maybe the helm chart introduced a bad default?

**Comment by hugohaggmark** [comment] 2019-08-15 12:09
Hi @Sytten are you still stuck on this or have you been able to move forward?

**Comment by Sytten** [comment] 2019-08-17 01:16
I am on vacation, I will revisit next week and give you an update.

**Comment by papagian** [comment] 2019-09-14 13:47
This is a duplicate of #17347

**Closed by papagian** 2019-09-14 13:47 UTC
Labels: needs more detail
