### ISSUE TITLE
Value mapping with color doesn't match in Pie Chart

### ISSUE THREAD

**Issue by juanitomaille** [grafana/grafana#46416] opened 2022-03-10 15:26 UTC
**What happened**:

When creating a pie chart, I use value mapping to match colors with my data but it doesn't seems to work.
You can see below that the color scheme form doesn't show "from thresholds (by value)" 
![Capture d’écran de 2022-03-10 16-16-55](https://user-images.githubusercontent.com/44920274/157693684-cb3ad430-e28d-4a24-8555-960582ce53c7.png)

**What you expected to happen**:

The same than for State timeline : 

![Capture d’écran de 2022-03-10 16-17-26](https://user-images.githubusercontent.com/44920274/157694327-2089c23b-2a62-4a60-9195-df93342d8d37.png)

**How to reproduce it (as minimally and precisely as possible)**:

Create a pie chart with some data and use "value mapping" with changing colors

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.3
- Data source type & version: influxDB 2.1 with flux
- OS Grafana is installed on: rpi
- User OS & Browser: chrome on ubuntu
- Grafana plugins: no
- Others:

**Comment by ivanahuckova** [comment] 2022-03-14 12:21
I was able to reproduce this as well at https://play.grafana.org/d/ktMs4D6Mk/5-bar-charts-and-pie-charts?orgId=1&editPanel=16. I added value mapping of `Vue -> Mapped Vue` and adding color of orange. The mapped value was shown, but the color was incorrect. 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/30407135/158171061-5a3cd528-b125-46a9-bc5e-e83b950d3676.png">
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/30407135/158171101-56d590c6-146c-4ffa-a25e-484aca68c9b9.png">

**Comment by juanitomaille** [comment] 2022-04-01 15:32
Same on grafana 8.4.4

**Comment by mdvictor** [comment] 2022-04-14 08:32
Hello! 

I'm not sure this is a bug. The label value is being mapped correctly and the numeric data should also receive a value mapping to see the colour applied. Here is an example on the environment Ivana linked above.

https://user-images.githubusercontent.com/36818606/163346319-262fde6a-f4ca-40fd-bb63-ab2f2c277d9c.mov

The numeric value should be raw and not the displayed value with unit (e.g: not `169 K` but `169000`)

**Comment by juanitomaille** [comment] 2022-04-14 09:20
if you change color of vue mapped, it doesn't change, you didn't do that.

**Comment by juanitomaille** [comment] 2022-04-14 09:38
what I didn't say : 

The query  is the same in the 2 screenshots in my first post.

to answer about numeric fields only : since the first post, I changed the way to monitor my machine and I don't use anymore string values, I'am using integer. and it's the same result.

**Comment by mdvictor** [comment] 2022-04-14 16:12
For the Pie Chart panel you are trying to map the label to a colour. You need to map the corresponding value of the label to the desired colour.

The visualisations represent data, so in this specific case, the colour of a slice in the PieChart should be decided by a value and not the label, as shown in my comment above, since the slice represents a value (e.g: `42.4 K` is the value represented on the Pie Chart slice and not `Meteor Mapped`, following your example above).

I will close this issue for now, since it is not a bug but more of an enhancement. If you wish, you can open a Feature Request in our Discussions section. Sadly, we will not be able to focus on this for the time being.

Thank you for opening this issue!

**Closed by mdvictor** 2022-04-14 16:12 UTC
Labels: type/bug, area/value-mapping, area/panel/piechart

**Comment by juanitomaille** [comment] 2022-04-14 19:29
@mdvictor : the very first screenshot : prod, error, nosignal, ... are VALUES.
I think the confusion cames with the test environment and, you're right, I tried to map labels there.
 
I replaced my strings in database  by integer codes 0, 1, 2, 3 , 4
So now, I have numeric values.

I will try again in several days. maybe I have to delete and re-do the pie chart.

**Comment by torkelo** [comment] 2022-04-14 20:01
If you want to customize colors click the color line icon in the legend and use the color picker,

**Comment by torkelo** [comment] 2022-04-14 20:02
the reason the value mapping is not working is that the color is taken from the value field, not the name field. So if you where to assign a value mapping color on the value instead of the name it will work

**Comment by juanitomaille** [comment] 2022-04-14 20:16
@torkelo in the first post, It's value mapping. Values are string.
It works with no problem on 2 other types of graphs

**Comment by torkelo** [comment] 2022-04-15 04:32
Cant be strings, pie chart needs number to calculate sice of slice

**Comment by juanitomaille** [comment] 2022-05-17 08:07
Hi, sorry for late answer, I was on other project.

14th apr I wrote "I replaced my strings in database by integer codes 0, 1, 2, 3 , 4
So now, I have numeric values."

After several weeks, I will try again with fresh vision.
