### ISSUE TITLE
universal (alpabetical + numerical) sorting (improve numerical sorting)

### ISSUE THREAD

**Issue by sjvudp** [grafana/grafana#25840] opened 2020-06-25 13:24 UTC
**What would you like to be added**:

Currently multi-value variables can only be sorted alphabetically or numerically.
If you have e.g. hostnames that contain a number (like a13, b2, b10), alphabetical sort would give a13, b10, b2, while numerical sort would give b2, b10, a13.
A better combined sorting algorithm would split each string into a list of names and numbers, and then compare the corresponding component with a proper compare function. if the components are equal, continue with the next component until there is a difference or the input ends.
So the sort order would be a13, b2, b10.

**Why is this needed**:
I see measurements sorted like "cpu.1, cpu.10, cpu.2, ..."

**Comment by torkelo** [comment] 2020-06-29 05:48
duplicate off https://github.com/grafana/grafana/issues/13179

**Closed by torkelo** 2020-06-29 05:48 UTC
