### ISSUE TITLE
Docker images from 8 hours ago are all labelled as amd64

### ISSUE THREAD

**Issue by stephen-dexda** [grafana/grafana#23167] opened 2020-03-28 20:28 UTC
All `master` and `master-ubuntu` images on Docker hub dated approx. 10 a.m. GMT today (28th March 2020) are marked as amd64:

https://hub.docker.com/r/grafana/grafana/tags

![image](https://user-images.githubusercontent.com/46443882/77833037-40577b80-7132-11ea-820e-3ef7e36dcd01.png)

I've checked the `master` images, and despite their labelling they one each of ARM, ARM64 and AMD64.

This causes image run failures on AMD64 platforms - in my case I saw an ARM image pulled.

**Comment by stephen-dexda** [comment] 2020-03-28 20:52
Possibly related? https://github.com/grafana/grafana/issues/22765

**Comment by torkelo** [comment] 2020-03-29 08:28
thanks for reporting this! 

@aknuds1 probably caused by recent changes I assume?

**Comment by aknuds1** [comment] 2020-03-29 09:01
@torkelo Most likely, I will try to find out what went wrong.

**Comment by aknuds1** [comment] 2020-03-30 10:35
The issue should be fixed, thanks for reporting it! Please let us in case something's still wrong.

**Closed by aknuds1** 2020-03-30 10:35 UTC
Labels: type/bug, type/build-packaging

**Comment by SAS-1** [comment] 2020-04-02 11:56
Hi
I noticed that latest had been updated but still no ARM build.

![image](https://user-images.githubusercontent.com/47122073/78246627-5c1ba280-74e1-11ea-9dff-229b8d831cc7.png)
Thanks

**Comment by aknuds1** [comment] 2020-04-02 12:41
@SAS-1 thanks for notifying us about that! I think there might still be an issue in our release process, where the latest tag doesn't get a multi-arch manifest, just an AMD64 image.

**Comment by aknuds1** [comment] 2020-04-02 13:15
I made an issue for this, #23291.
