### ISSUE TITLE
[Feature request] Elasticsearch Datasource Alerting

### ISSUE THREAD

**Issue by ericuldall** [grafana/grafana#6669] opened 2016-11-22 20:23 UTC
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using? v4
- What datasource are you using? Elasticsearch 2.x
- What OS are you running grafana on? debian:jessie
- What did you do? Tried to set up alerts on ES data
- What was the expected result? An alert would be set up
- What happened instead? I got an error

I'm curious if this is a limitation of Elasticsearch itself or the Datasource in Grafana just needs an update to support alerting.

I got the following error:

```
result
firing false
timeMs 0.476ms
error tsdb.HandleRequest() error Could not find executor for data source type: elasticsearch
```

**Comment by utkarshcmu** [comment] 2016-11-22 20:32
https://github.com/grafana/grafana/issues/5893

**Comment by bergquist** [comment] 2016-11-22 21:20
Closing. dupe of #5893

**Closed by bergquist** 2016-11-22 21:20 UTC

**Comment by ericuldall** [comment] 2016-11-23 18:15
Thanks, I'll track that.
