### ISSUE TITLE
[Enhancement request] Enable search a panel

### ISSUE THREAD

**Issue by baurine** [grafana/grafana#21135] opened 2019-12-17 08:39 UTC
**What would you like to be added**:

Enable search a panel by its name or title.

**Why is this needed**:

Now our grafana has tens of dashboards and hundreds of panels, it is difficult to find out the target panel quickly.

**Comment by dprokop** [comment] 2019-12-18 07:22
Duplicate of #15257

**Closed by dprokop** 2019-12-18 07:22 UTC
