### ISSUE TITLE
Graph key slowly creeps leftwards

### ISSUE THREAD

**Issue by Southclaws** [grafana/grafana#13551] opened 2018-10-07 11:18 UTC
I've had this issue ever since I started using Grafana (almost a year now) I assumed it was just an old version but I upgraded to latest yesterday and it's still here so I figured it's issue worthy.

This is present on Firefox and Chrome, but strangely not Safari.

Please include this information:
### What Grafana version are you using?
 Grafana v5.2.4 (0bbac5c) 
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Docker
### What did you do?
View a graph, a line graph.
### What was the expected result?
Normality
### What happened instead?
[This](https://imgur.com/a/LfSVAMx)

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
I'm not sure which network request is necessary for this one, it seems more like a UI bug anyway.

**Comment by torkelo** [comment] 2018-10-07 13:14
you get this chrome as well? We hava only seen this reported before in firefox. What OS and Chrome version are you using? 

Closing this as it's a dupe of https://github.com/grafana/grafana/issues/12726

**Closed by torkelo** 2018-10-07 13:14 UTC
