### ISSUE TITLE
Add a way to override the home dashboard.

### ISSUE THREAD

**Issue by afics** [grafana/grafana#3283] opened 2015-11-19 09:36 UTC
I don't like modifying `grafana/public/dashboards/home.json` just to replace the home dashboard. I think the right way to go about this, would be to look for a file named `home.json` in the directory specified in `[dashboards.json]/path` and use that instead, if it exists.

**Comment by torkelo** [comment] 2015-11-19 09:56
dupe of https://github.com/grafana/grafana/issues/1678

**Closed by torkelo** 2015-11-19 09:56 UTC
