### ISSUE TITLE
[BUG] Alerts Do not allow query to have template variables

### ISSUE THREAD

**Issue by alexbowers** [grafana/grafana#6753] opened 2016-11-30 10:17 UTC
Please include this information:
- What Grafana version are you using? 4.0
- What datasource are you using? InfluxDB
- What OS are you running grafana on? Ubtuntu 14.04

**Comment by bergquist** [comment] 2016-11-30 15:44
Dupe of https://github.com/grafana/grafana/issues/6557

**Closed by bergquist** 2016-11-30 15:44 UTC
