### ISSUE TITLE
[bug]tsdb.HandleRequest() error type assertion to string failed when alerting

### ISSUE THREAD

**Issue by 597365581** [grafana/grafana#34699] opened 2021-05-26 07:13 UTC
when config alert on datasource Elasticsearch, but alert cause error:tsdb.HandleRequest() error type assertion to string failed when alerting

**Environment**:
- Grafana version: code is 7.3.4 branch，but use ./grafana-server -v is Version 7.4.0 (commit: unknown-dev, branch: master)
- Data source type & version:Elasticsearch 7.10.2
- OS Grafana is installed on:CentOS Linux release 7.3.1611 (Core)
- User OS & Browser:windows10 chrome
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/62982788/119617837-cbb2c680-be34-11eb-86b2-6e33bc999b96.png)

![image](https://user-images.githubusercontent.com/62982788/119617656-a1f99f80-be34-11eb-97a3-28385cef0105.png)

**Comment by 597365581** [comment] 2021-05-26 08:37
strack：t=2021-05-26T16:21:10+0800 lvl=dbug msg="goroutine 183 [running]:\ngithub.com/grafana/grafana/pkg/services/alerting/conditions.toCustomError(0x280fe60, 0xc00081b150, 0xc000bb27e0, 0xc0008bfc40)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/services/alerting/conditions/query.go:377 +0x1f6\ngithub.com/grafana/grafana/pkg/services/alerting/conditions.(*QueryCondition).executeQuery(0xc0004fc070, 0xc0002ae2d0, 0xc0008bfbc0, 0x0, 0x203000, 0x8, 0x203000, 0x0)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/services/alerting/conditions/query.go:166 +0x11c7\ngithub.com/grafana/grafana/pkg/services/alerting/conditions.(*QueryCondition).Eval(0xc0004fc070, 0xc0002ae2d0, 0x7f300d904108, 0xc0002ae2d0, 0x22288a0)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/services/alerting/conditions/query.go:55 +0x13b\ngithub.com/grafana/grafana/pkg/services/alerting.(*DefaultEvalHandler).Eval(0xc000b74be0, 0xc0002ae2d0)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/services/alerting/eval_handler.go:34 +0xbe\ngithub.com/grafana/grafana/pkg/services/alerting.testAlertRule(0xc000c9bc00, 0x2566f01)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/services/alerting/test_rule.go:58 +0x78\ngithub.com/grafana/grafana/pkg/services/alerting.handleAlertTestCommand(0xc000ab0e10, 0x0, 0x0)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/services/alerting/test_rule.go:43 +0xe5\nreflect.Value.call(0x1fb51e0, 0x2566f98, 0x13, 0x248c07f, 0x4, 0xc000d53de0, 0x1, 0x1, 0x1, 0x0, ...)\n\t/opt/gosdk1.15/go/src/reflect/value.go:476 +0x8c7\nreflect.Value.Call(0x1fb51e0, 0x2566f98, 0x13, 0xc000d53de0, 0x1, 0x1, 0x0, 0x1, 0x230b660)\n\t/opt/gosdk1.15/go/src/reflect/value.go:337 +0xb9\ngithub.com/grafana/grafana/pkg/bus.(*InProcBus).Dispatch(0xc000582cc0, 0x1f02460, 0xc000ab0e10, 0x0, 0xc000adc528)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/bus/bus.go:133 +0x35c\ngithub.com/grafana/grafana/pkg/bus.Dispatch(...)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/bus/bus.go:205\ngithub.com/grafana/grafana/pkg/api.AlertTest(0xc000b7ea80, 0xc000d6e550, 0x5886b5519, 0x0, 0x0)\n\t/opt/gosdk1.15/grafana-7.3.4/pkg/api/alerting.go:142 +0x145\nreflect.Value.call(0x2063c60, 0x2566998, 0x13, 0x248c07f, 0x4, 0xc000ab0cf0, 0x2, 0x2, 0xc000" logger=error
t=2021-05-26T16:21:10+0800 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=0 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting

**Comment by Elfo404** [comment] 2021-05-26 09:30
Hi @597365581 , thanks for reporting this.

i tried the same query on grafana 7.3.4, but it's working as expected. looking at your screenshots it seems like you are not using 7.3.4 actually, can you confirm which grafana version you are running?

**Comment by 597365581** [comment] 2021-05-26 09:38
***@***.*** linux-amd64]# ./grafana-server -v

Version 7.4.0 (commit: unknown-dev, branch: master)













--

Smile a little more every day   
Have a nice day......

永清|yongqing
15150576251
QQ:597365581
***@***.***
 




At 2021-05-26 17:30:44, "Giordano Ricci" ***@***.***> wrote:

Hi @597365581 , thanks for reporting this.

i tried the same query on grafana 7.3.4, but it's working as expected. looking at your screenshots it seems like you are not using 7.3.4 actually, can you confirm which grafana version you are running?

**Comment by 597365581** [comment] 2021-05-26 09:52
I use a new dashboard to complate the same operate，this bug can not reproducing

**Comment by Elfo404** [comment] 2021-05-26 11:09
Strange. i'm also not able to reproduce it.

I'm going to close the issue then, if it happens again we can reopen it.

**Closed by Elfo404** 2021-05-26 11:09 UTC
Labels: area/alerting, datasource/Elasticsearch, needs investigation
