### ISSUE TITLE
Bad request sent to Azure Monitor after upgrade to v9.0.0

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#51454] opened 2022-06-27 16:25 UTC
**What happened**:

Requests to evaluate alert rules using Azure Monitor as the data source resulted in `400` from the api due to `500` errors from Azure Monitor. The queries work fine in the Explore tab.

```
2022-06-15 15:28:41 logger=context traceID=13e152f22b75f596 userId=1 orgId=1 uname=uname t=2022-06-15T15:28:41.632562394Z level=error msg="Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: request failed, status: 500 Internal Server Error" error="Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: request failed, status: 500 Internal Server Error" traceID=13e152f22b75f596
```

I created an identical alert rule and compared the payload sent to the api from the old and new versions of the alert. The new one works, the old one causes a `500`.

There's some extra data we're sending in the request to evaluate the old alert as part of the alert rule. That data comes from `GET /api/ruler/grafana/api/v1/rules?subtype=cortex`. Excerpt from the response body:

```json
...
"azureLogAnalytics": {
    "query": "//change this example to create your own time series query\n<table name //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
    "resultFormat": "time_series",
    "workspace": "9789c492-0468-4060-8669-0ab7e1c38675"
}
...
```

It looks like the call to the api returns the alert rule + the config options for the Azure Monitor data source. It looks like at some point we saved that data as part of the actual alert rule. This data is sent back to evaluate the rule, and that's when we get the `400` from the api.

**What you expected to happen**:

- No extra data saved with the alert rule.
- The JSON sent to the `/eval` endpoint has only the needed the data.
- The alert rule gets evaluated correctly.

**How to reproduce it (as minimally and precisely as possible)**:

No idea, that's the hard part. It's related to a [customer escalation](https://github.com/grafana/support-escalations/issues/2921).

**Anything else we need to know?**:

We need help from several teams (support, HG, data sources, alerting) to have an answer to these questions:
- [ ] Why did that data got saved with the alert rule?
- [ ] Did we introduce a change that caused this bug? If that's so, when?
- [ ] Is this only affecting Azure Monitor?
- [ ] Are there other customers experiencing this same issue?
- [ ] How do we fix it and prevent it from happening again?

**Environment**:
- Grafana version: v9.0.0
- Data source type & version: Azure Monitor
- OS Grafana is installed on: it's a Grafana Cloud instance

**Comment by andresmgot** [comment] 2022-07-04 09:54
hi @santihernandezc, is it possible to get the original query JSON that was failing so we try to reproduce the issue? If not it's impossible for us to investigate the issue. From the description of the issue, it seems that there is some migration code in the frontend that is not in the backend, that would explain why the query works in explore mode but not as an alert.

I see that the query is setting `    "workspace": "9789c492-0468-4060-8669-0ab7e1c38675"` which means that it was created before 8.0 so I'd assume something went wrong with the migration (and that's why it works if the same query is created in 9.0) but I wouldn't now what change caused the issue.

**Comment by yaelleC** [comment] 2022-07-22 09:52
Hi @santihernandezc & @andresmgot , Although I can still see the logs for the traceId `13e152f22b75f596 `, it seems there are no more traces available.

Chatted with @chaudyg about getting the request body however it’s not something we have access to, we could not get the query JSON either since the alert does not exist anymore (and backups are really not easy to get to). . 

My suggestion would be to close this as `can't repro` and re-open in case a similar issue surfaces?


![Image](https://user-images.githubusercontent.com/42030685/180413143-2c3e882d-f3ad-4ba4-93e5-76b23e1e270f.png)

**Comment by andresmgot** [comment] 2022-07-22 09:57
> My suggestion would be to close this as `can't repro` and re-open in case a similar issue surfaces?

sounds good to me

**Closed** 2022-07-22 10:35 UTC
Labels: area/alerting, needs investigation, datasource/Azure, area/datasource
