### ISSUE TITLE
Send alerts to different places based on template variable?

### ISSUE THREAD

**Issue by eddieparker** [grafana/grafana#25644] opened 2020-06-17 02:09 UTC
I'd like to be able to send the alert e-mail to different locations based on a template variable.

The reason for this is that I have a graph that covers many different products, each of which have a different e-mail alias.  The 'alert' query I already respects template variables, and depending on which one is alerting, I'd like it to send an e-mail to the appropriate list.

If this is already possible I apologize, I just couldn't figure out how to set it up.

**Comment by marefr** [comment] 2020-06-24 21:43
Duplicate of #6557

**Closed by marefr** 2020-06-24 21:43 UTC
Labels: area/alerting, area/alerting/notifications, priority/awaiting-more-evidence, type/feature-request
