### ISSUE TITLE
Singlestat decimal places incorrect

### ISSUE THREAD

**Issue by dswarbrick** [grafana/grafana#16440] opened 2019-04-08 08:54 UTC
**What happened**:
Singlestat panel displays more decimal places than it should.

**What you expected to happen**:
Panel value should be rounded according to specified number of decimal places.

**How to reproduce it (as minimally and precisely as possible)**:
Create singlestat panel, set datasource type to Prometheus (other datasources probably also work). Enter `10000000 / 3` in query field. Set panel decimals width to any non-empty value.

Set unit to "short" or some other unit that performs suffix calculation. Panel will display e.g. "3.333333 Mil" even when decimals is set to any non-empty value.

**Anything else we need to know?**:
The bug only seems to occur on large magnitude values, i.e. `1000 / 3` does not trigger the bug.

Leaving the decimals field empty (i.e. "auto") performs sane rounding with any size panel value.

**Environment**:
- Grafana version: 6.1.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian stretch
- User OS & Browser: Kubuntu 19.04, Firefox 66
- Grafana plugins: n/a
- Others: n/a

**Comment by torkelo** [comment] 2019-04-08 08:56
dupe of https://github.com/grafana/grafana/issues/16373 

fixed in master (nightly build) and will be fixed in upcoming 6.1.2 patch release

**Closed by torkelo** 2019-04-08 08:56 UTC
