### ISSUE TITLE
[Bug] Can't change the 'Date Histogram' field.

### ISSUE THREAD

**Issue by MadeInChina** [grafana/grafana#7582] opened 2017-02-16 04:19 UTC
Please include this information:
- What Grafana version are you using?
   Docker latest
- What datasource are you using?
   Elasticsearch
- What OS are you running grafana on?
   Ubuntu docker
- What did you do?
   Change the 'Date Histogram' to 'ok_time' field.
- What was the expected result?
   Return correct query with 'ok_time'
- What happened instead?
   Using the default date 'create_time' still

<img width="1280" alt="screen shot 2017-02-16 at 11 41 10 am" src="https://cloud.githubusercontent.com/assets/1201118/23007219/0fd3eec8-f442-11e6-9a69-8023b0ea0151.png">
<img width="1280" alt="screen shot 2017-02-16 at 11 40 42 am" src="https://cloud.githubusercontent.com/assets/1201118/23007220/0fd47b90-f442-11e6-9de6-5852ae8fe66d.png">

**Comment by torkelo** [comment] 2017-02-17 07:14
You can change it on the data source option page, having different time fields for the same data source is currently not supported.

**Comment by MadeInChina** [comment] 2017-02-17 14:52
Thanks for response.but hope that could be achieve.because it's a common case

**Comment by HeWhoWas** [comment] 2018-05-29 04:59
Is this by design? We have a pipeline where each step injects the time the record entered into that phase, and sometimes we would like to query a data source with a different field as the time.

For example, each record might get: ingestTime, processTime, etcTime. Ingest is when it's received by our system and placed in the queue, processTime was when it was retrieved from the queue, etc

**Comment by hackery** [comment] 2018-07-06 15:52
Could someone fix the title typo? I searched issues before entering #12519 but didn't find this one based on a query including "field" :(

**Comment by marefr** [comment] 2019-01-10 08:10
@cosmos78 please reload browser to make sure you're using the updated datasource configuration.

**Comment by marefr** [comment] 2019-03-05 22:09
Duplicate of #8260

**Comment by marefr** [comment] 2019-03-05 22:09
Please continue any discussions in #8260

**Closed by marefr** 2019-03-05 22:09 UTC
Labels: datasource: Elasticsearch, help wanted, type: bug
