### ISSUE TITLE
Link y-axis threshold value of a graph to the value of a Grafana variable

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#20059] opened 2019-10-28 12:12 UTC
**What would you like to be added**: The range of values of a particular parameter being plotted against time varies according to another parameter that happens to be configured via a Grafana variable through a drop-down menu. In this case, the y-axis threshold of the graph would also change since the range of values of the plotted parameter changes. Therefore, the thresholds must be designed to be linked with the Grafana variable in order to be reconfigurable when the graph changes.

**Why is this needed**: The lack of having a variable-linked threshold restricts the functionality of the graph panel.

**Comment by torkelo** [comment] 2019-10-28 19:28
duplicate of https://github.com/grafana/grafana/issues/922

**Closed by torkelo** 2019-10-28 19:28 UTC
