### ISSUE TITLE
InfluxDB Flux Multi-Value Variable, choose a good default-format

### ISSUE THREAD

**Issue by mishak87** [grafana/grafana#32871] opened 2021-04-10 22:24 UTC
Please don't make me do this every time I need multi-value variable in flux query
```javascript
import "strings"
import "regexp"

x = regexp.replaceAllString(r: /[{}]/, v: "${multivar}", t: "/")
multivar= regexp.compile(v: "^(" +strings.replaceAll(v: x, t: ",", u: "|") + ")$")

from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["multifield"] =~ multivar)

// ...
```

Expected

```javascript
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["multifield"] =~ ${multivar})
// ... 
```

**Environment**:
- Grafana version: Grafana v7.5.3 (3e3cf4dc60)

**Comment by hugohaggmark** [comment] 2021-04-12 04:47
Adding this to your backlog @grafana/observability-squad, please pass it back if it's generic.

**Comment by gabor** [comment] 2021-06-04 07:51
@mishak87 we're looking into making this easier to use, but for now, you can simply choose the `regex` format, like this:
```javascript
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["multifield"] =~ /^${multivar:regex}$/)
// ... 
```

this should work.

**Comment by gabor** [comment] 2021-06-04 10:10
there are many variable formats ( https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/ ) , we should decide what should be used when a format is not explicitly chosen via `:` . the problem is, Flux is a very rich language, values can be used in different contexts (regular-expression, list-of-quoted-strings, etc.), so it's not straightforward what is the best default-format.

**Comment by mishak87** [comment] 2021-06-10 14:04
Or you could require variable format to be set for flux queries.

**Comment by gabor** [comment] 2021-06-10 15:01
> Or you could require variable format to be set for flux queries.

@mishak87 sorry, i'm not sure if i understand the idea.. you mean that we adjust the flux editor so that if you use a variable without the `:something` part, then it will not be accepted?

**Comment by mishak87** [comment] 2021-06-10 19:49
Yes do not allow user to use variable without explicit format. This way user gets error and learns immediately there is format option for variables. Also she will see it used for time range variables when editing any example query.

**Comment by bohandley** [comment] 2022-10-03 14:33
Due to this being over a year old and a suggestion was given, we are closing this issue. Please reopen if this is still an issue with current version of Grafana.

**Closed by bohandley** 2022-10-03 14:33 UTC
Labels: type/feature-request, datasource/InfluxDB, area/dashboard/templating, prio/medium
