### ISSUE TITLE
Grafana Table Sort not working with multiple prometheus queries

### ISSUE THREAD

**Issue by nizamsp** [grafana/grafana#12311] opened 2018-06-17 11:28 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
Grafana v5.1.3 (commit: 087143285)
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Linux, Debian Stretch
### What did you do?
Merged two prometheus queries in the same table (added in the recent versions)
### What was the expected result?
Everything worked fine except the sorting function. When there are missing values in one of the columns, sorting goes for a toss.
### What happened instead?
sort order was completely random
### If related to metric query / data viz:
Please note the QPS sorting in the below image.
![jumping](https://user-images.githubusercontent.com/1537832/41507434-00895c22-7250-11e8-84a0-f7e2bd8f83dd.png)
If I click the "eye" icon above and hide the first prometheus query (which is Jumping Kms), then the sorting of QPS works fine. Issue happens when both the queries are given and there are missing values when joining both the queries.

**Comment by ivanahuckova** [comment] 2020-07-06 13:17
Hello @nizamsp, I have looked at this issues and I couldn't reproduce it in Grafana 7.0 on [grafana.play](https://play.grafana.org/). In 7.0 we have introduced a new table panel and transformations which probably fixed this problem. I am going to close this issue for now, but if feel free to reopen it if you experience this bug again.

**Closed by ivanahuckova** 2020-07-06 13:17 UTC
Labels: area/datasource, datasource/Prometheus, type/bug
