### ISSUE TITLE
Regression: Shared crosshair works only for panels of the same type

### ISSUE THREAD

**Issue by trollvottel** [grafana/grafana#35908] opened 2021-06-17 19:58 UTC
**What happened**:
Shared crosshair support partially broke somewhere between v7.0.6 (working) and >= v7.5.6 (broken). Cannot tell exactly which version broke it, but now it's only synced between **panels of the same type**, while other types don't show the line anymore.

**What you expected to happen**:
In v7.0.6, shared crosshair worked across panels of all types, e.g. 'graph' & 'discrete' next to each-other.

**How to reproduce it (as minimally and precisely as possible)**:
Enable shaired crosshair and have at least two panels of different types, e.g. 'graph' & 'discrete'.

**Anything else we need to know?**:
Broken in v8.0.2, too, same applies to the new/beta panel types.

**Environment**:
- Grafana version: v7.5.6, v8.0.2
- Data source type & version: Doesn't matter
- OS Grafana is installed on: Linux/Docker
- User OS & Browser: Windows 10 Firefox 89
- Grafana plugins: 'discrete' panel

**Comment by leeoniya** [comment] 2021-06-17 20:12
this is a partial duplicate of https://github.com/grafana/grafana/issues/35683

the Graph panel is unlikely to get any additional attention in the future (it's replaced by new Time series panel). and Discrete panel is mostly replaced by the new State timeline core panel. there is still work to do to get some features rewritten for the new panels, and shared tooltip between Time series and State timeline makes sense to fix.

**Comment by trollvottel** [comment] 2021-06-17 20:40
@leeoniya I don't think that this is an issue of the panels itself but something "middlewarish" in-between. Because the panels themselves, especially the 'discrete' panel haven't changed at all.

**Comment by trollvottel** [comment] 2021-06-17 20:41
Maybe has sth. todo with the "eventbus" changes.

**Comment by leeoniya** [comment] 2021-06-17 20:42
> Maybe has sth. todo with the "eventbus" changes.

yep, i'm sure. lots of stuff was poked there.

**Comment by trollvottel** [comment] 2021-06-17 20:46
And I disagree with your argument about the state-timeline panel replacing the discrete panel because it's still in beta and essential stuff isn't working, yet. Like in-panel scrolling for example (I've created another issue for that). For me, state-timeline looks really promising but regressions still should be fixed ASAP instead of pointing to new stuff sth. that may work in the future.

**Comment by pgassmann** [comment] 2021-06-28 12:02
In 8.0.3, with `shared_crosshair` setting, the timeseries panel acts like `shared_tooltips`, showing tooltips on all panels.

Adding this here instead of creating a separate issue.

**Comment by hhromic** [comment] 2021-07-07 11:53
> In 8.0.3, with `shared_crosshair` setting, the timeseries panel acts like `shared_tooltips`, showing tooltips on all panels.
> 
> Adding this here instead of creating a separate issue.

Just hit this same very issue as well :(
I hope the Grafana developers get some attention to this issue as this is very annoying when you have many time series panels in the same dashboard. All of them start to pollute the screen with tooltips everywhere.

**Comment by xkilian** [comment] 2021-09-03 19:57
Shared crosshair is a key analytics component of grafana for different panel types. Very problmatic when working with paths on maps and different size timelines. I hope this issue will not be forgotten for 8.2.

**Closed** 2021-11-05 17:52 UTC
Labels: type/feature-request, area/frontend, area/panel/timeseries, area/panel/state-timeline
