### ISSUE TITLE
Graph displays with 0 height in Firefox

### ISSUE THREAD

**Issue by UglyHobbitFeet** [grafana/grafana#17474] opened 2019-06-06 19:06 UTC
**What happened**:
Graphs display with a height of zero.

**What you expected to happen**:
I expect to see the graph in it's correct height as the author intended

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to https://play.grafana.org
2. Under the 'Feature showcases' section, click on 'Alerting'
3. Under 'Alerting' click on the word 'Metric Reqs Peaking' and select 'View' from the dropdown
4. The graph does not show correctly in ANY ESR version of Firefox. The graph does not show correctly in any non-ESR version of Firefox before version 67.0

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: N/A since https://play.grafana.org
- Data source type & version: N/A since https://play.grafana.org
- OS Grafana is installed on: N/A since https://play.grafana.org
- User OS & Browser: CentOS 7 / Firefox ESR
- Grafana plugins: N/A since https://play.grafana.org
- Others: N/A since https://play.grafana.org

**Comment by marefr** [comment] 2019-06-07 09:09
Duplicate of #15524

**Closed** 2019-06-07 09:09 UTC
Labels: type/duplicate
