### ISSUE TITLE
Explore show context cropped

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#36945] opened 2021-07-20 10:17 UTC
**What happened**:

When using explore with few log line and trying to use the show context options. The upper part is cropped making the whole thing totally impossible to use.

**What you expected to happen**:

I would expect the show context frame to show entirely.

**How to reproduce it (as minimally and precisely as possible)**:

Query for logs with few result, click on show context on the first few line.

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/1053421/126307454-3b8bbcdc-43cf-424e-a1c7-c6cfc1388f4b.png)

**Environment**:
- Grafana version: Grafana v8.1.0-28776pre (dd11e232d0)
- Data source type & version: Loki
- User OS & Browser: Chrome

**Comment by ivanahuckova** [comment] 2021-07-20 10:22
/duplicate of https://github.com/grafana/grafana/issues/27262

**Closed** 2021-07-20 10:23 UTC
Labels: area/explore, type/duplicate
