### ISSUE TITLE
Alerting: Preview recording rules in the rule editor

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#35699] opened 2021-06-15 08:19 UTC
**What would you like to be added**:

When editing a cortex or loki recording rule in the rule editor, it should be possible to click "preview data" and see the rule evaluation result.

**Comment by gotjosh** [comment] 2021-08-16 14:26
Scope of this for 8.2 can be that we just disable the button with a toolip.

**Comment by gillesdemey** [comment] 2022-06-22 13:15
Closing this as a duplicate of https://github.com/grafana/grafana/issues/35699 and will follow-up there

**Comment by mellieA** [comment] 2022-12-12 18:39
This looks like it was closed as a duplicate of itself. There are newer reports of this issue from internal/external users:

https://github.com/grafana/grafana/issues/60144
https://github.com/grafana/grafana/issues/59301 

Will close the other two issues in favor of this one

**Comment by samjewell** [comment] 2022-12-13 15:02
# Additionally to the original report here:

The same, but for Mimir / Loki RECORDING rules

**What would you like to be added:**

When editing a cortex or loki RECORDING rule in the rule editor, it should be possible to click "preview RULE" and see the rule evaluation result.

**Why is this needed:**

Grafana managed alerts have this feature, but it is currently missing for cortex/loki RECORDING RULES.


**further**

The UI needs a complete update for recording-rules. The button text would say "preview rule", and the alerting chain should probably be removed, as it's not relevant for recording rules.

**Comment by gillesdemey** [comment] 2022-12-14 15:29
Previewing Mimir / Cortex / Loki alerts has been implemented in https://github.com/grafana/grafana/pull/54950 previously

**Comment by armandgrillet** [comment] 2023-02-06 11:47
From @VikaCep : we're explicitly excluding `cloud-recording` queries from preview as they don't seem to be supported. https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rule-editor/PreviewRule.tsx#L99
What is not clear to me if this is not supported because it's not implemented on the backend side (as we call the `/api/v1/eval` API to do it) or if it is purely frontend work that's missing. Do you know? FYI @gillesdemey 

From @gillesdemey : Some initial work is being done in the `alerting/preview-recording-rule` branch; what we're hoping to be able to do is:

1. Render the correct editor for any of the supported datasources
2. Render a visualization for the time series that are being recorded in the rule by pressing the "preview" button.

We don't need expressions (since those aren't supported) and none of the usual config params are supported (no time range, no max data points, etc)

**Comment by gillesdemey** [comment] 2023-02-06 17:46
Just not supported in the Front-end, no back-end changes need to be implemented 👍

**Closed** 2023-03-22 12:21 UTC
Labels: area/alerting, area/frontend, 🍐-programming
