### ISSUE TITLE
Grafana v8.5.0 - not possible to filter tables by values (setting 'getRowProps')

### ISSUE THREAD

**Issue by dhbwka-kn** [grafana/grafana#48278] opened 2022-04-26 14:10 UTC
I can't filter my tables by values anymore. After selecting an existing value from the filter menu, the requested table view briefly appears and then disappears with the error **"Cannot set properties of undefined (setting 'getRowProps')"** showing up in the upper left corner. This issues applies to all my dashboards. I already performed a downgrade to 8.4.7 and didn't have any issues!

**Environment**:
- Grafana version: v8.5.0 (6134e3cf35)
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: Oracle Linux 8.5
- User OS & Browser: Many
- Grafana plugins: None, core only
- Others:

**Comment by mellieA** [comment] 2022-04-26 23:55
@dhbwka-kn this looks like a duplicate of https://github.com/grafana/grafana/issues/48246. The good news is that there is a PR to resolve it https://github.com/grafana/grafana/pull/48258

**Closed by mellieA** 2022-04-26 23:55 UTC
Labels: type/duplicate
