### ISSUE TITLE
Consider using ListMetrics API to query for AWS metrics

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#28382] opened 2020-10-19 19:52 UTC
Amazon (from meeting with Marc) would like us to query AWS SDK, via [ListMetrics API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/viewing_metrics_with_cloudwatch.html), to get all custom namespaces. We should consider if listing metrics dynamically should be better than having static lists of all possible metrics.

**Comment by mtanda** [comment] 2020-10-20 00:18
I think you know, but I should notice about the limitation.
Some of metrics are not listed by ListMetrics API.
For example, `HTTPCode_Target_5XX_Count` in `AWS/ApplicationELB` namespace is not listed until CloudWatch record the not-zero value.

**Comment by mtanda** [comment] 2020-10-20 00:22
I propose you to use both method, use ListMetrics API for getting current recorded metrics list, and use static file to complement missing metrics.

**Comment by aknuds1** [comment] 2020-10-20 06:32
@mtanda Thanks, yeah I'm aware that ListMetrics only lists metrics available to the user.

**Comment by vickyyyyyyy** [comment] 2021-07-09 13:51
Duplicate of https://github.com/grafana/grafana/issues/30977

**Closed by vickyyyyyyy** 2021-07-09 13:51 UTC
Labels: area/backend, datasource/CloudWatch
