### ISSUE TITLE
Docker permission issues

### ISSUE THREAD

**Issue by modem7** [grafana/grafana#24595] opened 2020-05-12 21:04 UTC
**What happened**:
Fresh build of Grafana docker, permission issues with persistent volume

**What you expected to happen**:
No permission issues

**How to reproduce it (as minimally and precisely as possible)**:
```
  grafana:
    hostname: Grafana
    container_name: Grafana
    image: grafana/grafana
    networks:
      pihole:
        ipv4_address: '172.22.0.111'
    ports:
      - "3001:3000"
    volumes: 
      - Grafana:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    depends_on:
      - varkendb
      - varken
      - telegraf
    restart: unless-stopped
```

**Anything else we need to know?**:
```
GF_PATHS_DATA='/config/data' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: can't create directory '/config/plugins': Permission denied
```
I understand that I can do a directory permissions change following the instructions at https://grafana.com/docs/grafana/latest/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later - but why isn't this working as standard in a persistent volume as per your recommendations in https://grafana.com/docs/grafana/latest/installation/configure-docker/

Forgive me if I'm being a muppet here!

**Environment**:
- Grafana version: Docker latest
- Data source type & version: InfluxDB latest
- OS Grafana is installed on: Fedora/Docker
- User OS & Browser: Waterfox latest
- Grafana plugins: grafana-piechart-panel,grafana-worldmap-panel
- Others:

**Comment by ivanahuckova** [comment] 2020-05-13 09:35
Hello @modem7, could you please share with us your compose file or the volumes configuration?

**Comment by modem7** [comment] 2020-05-13 09:38
@ivanahuckova heya, the compose part for grafana plus the named volume is in the notes.

Do you need further information regarding it? If so, anything in particular?

**Comment by ivanahuckova** [comment] 2020-05-18 08:16
If you can, could you please send us the complete file (please make sure there are no credentials)? Otherwise, if you have anything under [volumes configuration](https://docs.docker.com/compose/compose-file/#volume-configuration-reference), could you share that?

**Comment by modem7** [comment] 2020-05-18 17:03
> 
> 
> If you can, could you please send us the complete file (please make sure there are no credentials)? Otherwise, if you have anything under [volumes configuration](https://docs.docker.com/compose/compose-file/#volume-configuration-reference), could you share that?

Hello, 

https://pastebin.com/hi2hfJAZ Here is my full docker-compose file.

Nothing fancy with the volumes, just a named volume and a reference to it.

**Comment by ivanahuckova** [comment] 2020-05-19 14:28
@xlson is [migration from a previous version of the docker container to 5.1 or later ](https://grafana.com/docs/grafana/latest/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later ) something that needs to be done even though you are setting up fresh grafana? It doesn't seems very clear from the documentation.

**Comment by aknuds1** [comment] 2020-05-19 15:25
Can you please be more specific in the issue description about how to reproduce this, and the exact error you're seeing? I can only _guess_ that this is a Docker Compose file. At this stage, I don't know what the problem is.

**Comment by aknuds1** [comment] 2020-05-19 15:27
To me this actually looks like a problem with Docker Compose, where the container volume /config/data is read-only. That isn't a bug in Grafana.

**Comment by modem7** [comment] 2020-05-19 15:35
Of course!

So once I bring the docker compose file up, I get the following in the logs:

```
GF_PATHS_DATA='/config/data' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/config/plugins': Permission denied,
GF_PATHS_DATA='/config/data' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/config/plugins': Permission denied,
GF_PATHS_DATA='/config/data' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/config/plugins': Permission denied,
GF_PATHS_DATA='/config/data' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/config/plugins': Permission denied,
GF_PATHS_DATA='/config/data' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/config/plugins': Permission denied,
GF_PATHS_DATA='/config/data' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/config/plugins': Permission denied,
GF_PATHS_DATA='/config/data' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: can't create directory '/config/plugins': Permission denied,
```

The only way to get round that is by applying the migration fix:

> chown -R 472:472 /config

The volume itself is RW but seems to be owned by root instead of by Grafana user. 

![image](https://user-images.githubusercontent.com/4349962/82346665-ab188b00-99ee-11ea-801f-403473d9d92f.png)

I hope this explains things a bit better?

> 
> 
> Can you please be more specific in the issue description about how to reproduce this, and the exact error you're seeing? I can only _guess_ that this is a Docker Compose file. At this stage, I don't know what the problem is.

**Comment by aknuds1** [comment] 2020-05-19 15:40
I haven't had this problem myself, but it looks as if the solution is to run Grafana as a user (e.g. your own) with the right permissions to the directory you're bind mounting: https://grafana.com/docs/grafana/latest/installation/configure-docker/#run-grafana-container-using-bind-mounts. Hope this helps.

This isn't a bug in Grafana though, so I will close this issue. I would recommend you use the [community forums](https://community.grafana.com/) or [Slack](http://slack.raintank.io/) for support.

**Closed by aknuds1** 2020-05-19 15:40 UTC
Labels: needs investigation
