### ISSUE TITLE
Feature request: Hidden template variables

### ISSUE THREAD

**Issue by tokudan** [grafana/grafana#4146] opened 2016-02-24 19:05 UTC
I would like to hide some template variables from my users, since they are automatically set depending on other variables.

I'm using InfluxDB as a backend.

The background is that I need to change some part of my queries depending on the user selection, for example:
`SELECT non_negative_derivative(mean("value"))/$minterval*8 FROM $retention.traffic_fastd_rx_bytes WHERE ... AND $timeFilter GROUP BY time($minterval) fill(null)`

$minterval is a fixed value but depends on $retention, for my retention policy "l1" $minterval needs to be 60, for "l2" it needs to be 300, etc.

My current solution is that I populate the value of $minterval through the query
`SHOW TAG VALUES FROM retentionlevels WITH KEY = "time" WHERE "level" =~ /^$retention/`

The downside is that this appears as a variable at the top of the dashboard, but there will never be more than one value that the user could select, so the best option would be to hide it from the user.

**Comment by torkelo** [comment] 2016-02-25 09:23
good suggestion, dupe of https://github.com/grafana/grafana/issues/4146 , but will close that one as your issue has better description :)

**Comment by nik-petrov** [comment] 2016-02-25 10:01
Could be that the suggested change by @jbergler in #2665 still works?
https://github.com/jbergler/grafana/commit/d4337d6b8f92113ad986a0c7fc59d63921a4a7a6

**Comment by mtanda** [comment] 2016-02-25 15:48
https://github.com/jbergler/grafana/commit/d4337d6b8f92113ad986a0c7fc59d63921a4a7a6 conflict current master.
Just port it, and open PR https://github.com/grafana/grafana/issues/4154 .

**Comment by sslupsky** [comment] 2016-02-25 22:43
Yes, I agree, the option to hide a variable would be very helpful.

+1

**Comment by bergquist** [comment] 2016-02-29 09:50
fixed by 4299feee3799402119972083696194f7ab6984cc

**Closed by bergquist** 2016-02-29 09:50 UTC
Labels: comp: dashboard/templating, P4: nice to have, state: help wanted (PR), type: feature request
