### ISSUE TITLE
Repeat panel render problem

### ISSUE THREAD

**Issue by baur** [grafana/grafana#40211] opened 2021-10-08 12:09 UTC
**What happened**:

Repeat panel render problem, fixes only with resizing the browser

![repeat](https://user-images.githubusercontent.com/2898361/136553691-0a0d2847-84aa-47b9-9b74-45c895f22d80.gif)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.2.0 (d7f71e9eae)
- Data source type & version: MSSQL
- OS Grafana is installed on: Window10
- User OS & Browser: Chrome
- Grafana plugins: [Timepicker Buttons Panel for Grafana](https://github.com/WilliamVenner/grafana-timepicker-buttons) (the only one not core plugin installed on production, please make core too)
- Others:

**Comment by baur** [comment] 2021-10-08 12:11
the top panels also repeated but works fine

**Comment by torkelo** [comment] 2021-10-10 05:55
Fixed by https://github.com/grafana/grafana/pull/39991 

dupe of #38805

**Closed by torkelo** 2021-10-10 05:55 UTC
