### ISSUE TITLE
[Bug]: In a table/graph it's not possible to have the same metric with different tags/alias

### ISSUE THREAD

**Issue by adamantio87** [grafana/grafana#8070] opened 2017-04-07 15:18 UTC
I'm using grafana 4.1 running on Linux and OpenTSDB as a datasource.

My OpenTSDB entries have the following structure:
...metric=net.usage.server1, tag1=eth0...
...metric=net.usage.server1, tag2=eth1..
...metric=net.usage.server1, tag1=eth2..
...metric=net.usage.server1, tag2=eth3..

And I want to display netusage statistics related to this four ethernet port. I want to display them on a table and on a graph.

I've added two different metrics on the metric tab
-Metric: net.usage.server1; Alias:server1 $tag_int => internal 
int = literal_or(eth0|eth1) , groupBy = true

-Metric: net.usage.server1; Alias:server1 $tag_int =>external 
int = literal_or(eth2|eth3) , groupBy = true

My expectation is to have
server1 eth0 => internal 
server1 eth1 => internal

for ther first metric and

server1 eth2 => external 
server1 eth3 => external

for ther second metric.

Instead I have
server1 eth0 => internal 
server1 eth1 => internal
for ther first metric and

server1 eth2 => internal 
server1 eth3 =>internal
for ther second metric.

It seems it does not properly shows the string in the "Alias" field even if it properly shows the two different tags.

**Comment by smalik03** [comment] 2017-04-07 16:53
@adamantio87 can you specify what version of OpenTSDB you are using? This is an issue that was fixed with OpenTSDB 2.3 where the response returns a query index which is used to map an alias to a response.

#1876

**Comment by torkelo** [comment] 2017-04-07 20:05
Please search before :) `OpenTSDB alias` would have yielded a bunch of closed issues :) 

They all relate to a problem in OpenTSDB that makes it impossible for Grafana to know which series came from which query. 

Dupe of 
https://github.com/grafana/grafana/issues/2687
https://github.com/grafana/grafana/issues/3108
https://github.com/grafana/grafana/issues/1915
https://github.com/grafana/grafana/issues/1876

Fixed in OpenTSDB 2.3 and Grafana 3.1 (master)

**Closed by torkelo** 2017-04-07 20:05 UTC
Labels: datasource: OpenTSDB, state: needs more detail

**Comment by adamantio87** [comment] 2017-04-13 15:15
Thanks. I'll try to ugrade Open TSDB
