### ISSUE TITLE
place to create a common links tempate and can be inserted into all dashboards for navigation

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#19916] opened 2019-10-19 02:35 UTC
**What would you like to be added**:
place to create a common links tempate and can be inserted into all dashboards for navigation
**Why is this needed**:
When located in a specific dashboards many users don't know where and how to switch to another dashboards. Search button not shown clearly as it's on the upper-left corner and it's current dashboard name, anyway the breadcrumb is great. If a common links template there it will be much more easier for admin to globally set up and update menu or catalogs as navigation on his demand,  instead of change each dashboard very time when there is a update.

**Comment by torkelo** [comment] 2019-10-19 07:31
duplicate of https://github.com/grafana/grafana/issues/1959

**Closed by torkelo** 2019-10-19 07:31 UTC
