### ISSUE TITLE
XYChart: Turns into abstract art when panel get's wider 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#45810] opened 2022-02-23 20:52 UTC
On this dashboard: http://localhost:3000/grafana/d/TX2VU59MZ/panel-tests-shared-tooltips?orgId=1  (shared tooltip test

There is a XY chart:
![Screenshot from 2022-02-23 21-49-47](https://user-images.githubusercontent.com/10999/155406145-2ff43bef-6075-4624-8512-a9ebb3d4f80a.png)

It turns into this if I make the panel wider & hit refresh:
![Screenshot from 2022-02-23 21-50-02](https://user-images.githubusercontent.com/10999/155406186-d7b09b90-a648-48aa-8f64-b2c1dd4fcee8.png)

You can also increase the max data points option (Under query options) to trigger the same behavior

**Comment by torkelo** [comment] 2022-02-23 20:53
any ideas @leeoniya ?  (I know there are many other bugs now, this I think is low prio)

**Comment by leeoniya** [comment] 2022-02-24 00:00
> Turns into abstract art

with this and new heatmap we'll be ready to start minting GrafaNFTs :)

cannot reproduce it in the dashboard:

https://user-images.githubusercontent.com/43234/155430545-f36da1f8-ed0f-4e60-b063-d8e08ad3eef1.mp4

it does seem to reproduce in edit mode, though:

https://user-images.githubusercontent.com/43234/155430978-a6b8f5c4-71f1-4ee5-bfe6-73e1d9f42e93.mp4

maybe somewhere something is getting confused about the `Lines` setting:

https://user-images.githubusercontent.com/43234/155431054-fc27ca15-4442-4a97-8bef-651266738d88.mp4

**Comment by nmarrs** [comment] 2023-08-21 17:10
This is not able to replicate this locally and it seems like the underlying issue has been fixed so closing this out.

https://github.com/grafana/grafana/assets/22381771/3095ac7d-46d1-4d7f-b3b6-48fb5cc006da

**Closed by nmarrs** 2023-08-21 17:10 UTC
Labels: type/bug, area/panel/xychart
