### ISSUE TITLE
Question How Can I Hide a Column From Table Panel?

### ISSUE THREAD

**Issue by DanielFRocha** [grafana/grafana#6029] opened 2016-09-13 11:29 UTC
* **I'm submitting a ...**
- [ ] Bug report
- [ ] Feature request
- [X] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1
- What datasource are you using? Zabbix 2.4.5
- What OS are you running grafana on? CentOS 7

Hi, I just wanna know how to hide a column from a table, I really need to this column to be hide how can I do it?

![image](https://cloud.githubusercontent.com/assets/6033757/18472134/fa95de62-798b-11e6-8deb-c8734343c65d.png)

The Time Column must be hidden.

Thanks in Advance.

**Comment by bergquist** [comment] 2016-09-13 11:32
That's not supported within Grafana yet.

Duplicate of https://github.com/grafana/grafana/issues/3551

**Closed by bergquist** 2016-09-13 11:32 UTC

**Comment by DanielFRocha** [comment] 2016-09-13 11:39
Hi bergquist, 
Thanks for your answer, but what about this pull?
https://github.com/grafana/grafana/pull/5677

**Comment by bergquist** [comment] 2016-09-13 11:40
@DanielFRocha something like that will most likley go into 4.0. We also have https://github.com/grafana/grafana/pull/4935

**Comment by DanielFRocha** [comment] 2016-09-13 11:42
@bergquist is there any beta Table Plugin?

**Comment by bergquist** [comment] 2016-09-13 11:52
@DanielFRocha nope. not since its bundled with core Grafana. I try to merge this as soon as possible but its gonna take some time before I get to it :/

**Comment by DanielFRocha** [comment] 2016-09-13 12:16
@bergquist Thanks very much my friend.

Can I Ask One more question?

I Use Sanitize HTML to pull from more than 6 shell scripts.
How can I draw a Line after each line I use <br> to make the enter but use <hr> didn't draw a line.

Thanks in advance.

**Comment by phemmer** [comment] 2017-02-02 05:29
From what I can see, this is not a duplicate of #3551. #3551 is about hiding the column **headers**. This ticket is about hiding the entire column.

**Comment by DanielFRocha** [comment] 2017-03-16 15:20
Yes, Thanks very much for you help!!!

**Comment by costimuraru** [comment] 2018-11-21 12:08
For reference, you can hide a column by using `Column Styles` in Grafana, and seeting the `Column Type` to `Hidden`.
<img width="982" alt="screen shot 2018-11-21 at 14 07 33" src="https://user-images.githubusercontent.com/952836/48840268-d210e500-ed96-11e8-8066-5e6ffea22ba8.png">

**Comment by fetidbell** [comment] 2019-03-29 14:56
> For reference, you can hide a column by using `Column Styles` in Grafana, and seeting the `Column Type` to `Hidden`.
> <img alt="screen shot 2018-11-21 at 14 07 33" width="982" src="https://user-images.githubusercontent.com/952836/48840268-d210e500-ed96-11e8-8066-5e6ffea22ba8.png">

Hi! Don't you know, Is there any way to hide multiple columns in one rule? For example, using this kind of regexp: (column1 | column2) ? Thanks! :)

**Comment by marefr** [comment] 2019-03-29 15:33
@fetidbell just just Apply to columns named=/^(column1|column2)$/

**Comment by fetidbell** [comment] 2019-04-01 13:32
> @fetidbell just just Apply to columns named=/^(column1|column2)$/

Thanks, mate, it's worked for me!

**Comment by ramesh569** [comment] 2020-04-08 08:35
![image](https://user-images.githubusercontent.com/29400228/78762690-cd57cb80-79a1-11ea-9300-b0ea73c1c077.png)

Hi I want remove the coloumn highlighted in red.. donot find any column style options to hide.. could please suggest .

**Comment by lhejazi** [comment] 2020-06-23 20:32
Is Column Styles --> Type --> Hidden available in the new Grafana UI? I can't seem to find it via the Overrides

**Comment by marefr** [comment] 2020-06-24 15:58
@lhejazi since Grafana 7 and using the new table panel you have to use [transformation](https://grafana.com/docs/grafana/latest/panels/transformations/#organize-fields) to hide columns. Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by a-gavin** [comment] 2022-07-14 18:46
Just putting this here for anyone else who stumbles across this post, information on hiding columns are located in the panel transformation docs [here](https://grafana.com/docs/grafana/v8.5/panels/transform-data/transformation-functions/) (more direct link than the one above) and in a community forums post [here](https://community.grafana.com/t/hide-column-in-table-in-v8-0/49040)
