### ISSUE TITLE
'Save as' button in the template dashboard error modal not working

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#52839] opened 2022-07-26 19:38 UTC
**What happened**:
I loaded in an datasource dashboard, and clicked save to bring up the error modal to save a copy. When the `save as` button was clicked, it did not save and the console logged a warning about an unmounted component

https://user-images.githubusercontent.com/5421859/181095559-f6e63515-f13f-4f05-a996-0035cf653524.mov

**What you expected to happen**:
I expected a copy of the dashboard to be saved.

**How to reproduce it (as minimally and precisely as possible)**:
As seen in the video, go to a configured datasource plugin and import one of its dashboards. Click the save icon, and when the modal pops up, click the `save as` button.

**Comment by RubensRafael** [comment] 2022-09-30 12:00
https://www.loom.com/share/b36f1167e3454795bae2505749a24fd2
This issue is no longer reproducible, because changes to the main branch code solved the problem

**Comment by iwysiu** [comment] 2022-10-03 15:34
Hi @RubensRafael , I tried it on main and it's still broken. I'm not talking about the `import` button, which is what your video shows, but the `Save as` button in the modal (about 10 seconds into my screen recording)

**Comment by iwysiu** [comment] 2022-10-03 20:10
Ah, I pulled again, and I do see what you mean. As a note, the error that pops up is a little misleading, but it does work now!
![Screen Shot 2022-10-03 at 4 08 54 PM](https://user-images.githubusercontent.com/5421859/193669667-93600cd6-246e-4531-bece-e70ab2296d2f.png)

**Comment by zuchka** [comment] 2022-11-13 14:56
closing as fixed, although the error message could be more helpful

**Closed by zuchka** 2022-11-13 14:56 UTC
Labels: type/bug, area/frontend
