### ISSUE TITLE
`Updated by` in `Versions` tab shows user id rather than email

### ISSUE THREAD

**Issue by vg-vaibhav** [grafana/grafana#66563] opened 2023-04-14 10:42 UTC
**What happened**:
`Updated by` in `Versions` tab shows user id rather than email. It used to show username/email in 9.0. 

**What you expected to happen**:
It should show username/email

**How to reproduce it (as minimally and precisely as possible)**:
Got to any dashboards setting. Then go to version tab. 
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/24417756/232023120-ef4acbea-3dc4-4c0d-90d5-d1fd69349116.png">

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: any
- OS Grafana is installed on: 
- User OS & Browser: Chrome, Firefox, Safari. iOS
- Grafana plugins:
- Others:

**Comment by tonypowa** [comment] 2023-04-14 10:49
hi @vg-vaibhav 

this is a known issue which has a fix  https://github.com/grafana/grafana/pull/65351

/duplicate of #64584

**Closed by tonypowa** 2023-04-14 10:49 UTC
