### ISSUE TITLE
[Feature request] Select node in graphite template variable

### ISSUE THREAD

**Issue by tfylling** [grafana/grafana#6988] opened 2016-12-16 08:53 UTC
An option to select which node to use as template variable from a graphite statement would mean that you could do eg host = icinga.\*.services.postgres* and specify node(1) to get only hosts that have any postgres data of some kind.

**Comment by torkelo** [comment] 2016-12-16 08:57
duplicate of https://github.com/grafana/grafana/issues/2343

**Closed by torkelo** 2016-12-16 08:57 UTC
