### ISSUE TITLE
Tooltip/Hint (left upper corner of graph) visible in kiosk or kiosk=tv mode

### ISSUE THREAD

**Issue by raphaelgeng** [grafana/grafana#29702] opened 2020-12-09 07:44 UTC
**What would you like to be added**:
It would be very good to see the graph description/hint/tooltip also in the kiosk or kisok=tv mode. 

**Why is this needed**:
This is in my opinion the viewer mode and gives the graph designer/creator the possibility to provide a explination for the graph/view.

Thank you very much!

Best Ragard
Raphael

**Comment by torkelo** [comment] 2020-12-09 09:35
duplicate of #27099

**Closed by torkelo** 2020-12-09 09:35 UTC
