### ISSUE TITLE
Grafana offline mode. 

### ISSUE THREAD

**Issue by suikast42** [grafana/grafana#11737] opened 2018-04-26 14:03 UTC
Hi guys,
i am running the offical docker image from grafana 5.0.4.

As I can see there is an issue with the plugin handling. Grafana tries on every reboot of the grafana container to donwload the plugins. 

After a deep dive I see that zthe runskript of grafana do the folowing:
`if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then
  OLDIFS=$IFS
  IFS=','
  for plugin in ${GF_INSTALL_PLUGINS}; do
    IFS=$OLDIFS
    grafana-cli --pluginsDir "${GF_PATHS_PLUGINS}" plugins install ${plugin}
  done
fi`

But that's annoying in two situaions:
1. We have no internet connection in production
2. The reboot time depends on the spped of your internet connection

Download manually the plugins and copy it per docker to plugins dir is an option but not convienient. 

Is that not possible to install thze plugin if it is not present ?

**Comment by DanCech** [comment] 2018-04-26 14:06
https://github.com/grafana/grafana-docker#building-a-custom-grafana-image-with-pre-installed-plugins

**Comment by daniellee** [comment] 2018-04-30 07:41
The link above has now been moved to the Grafana docs: http://docs.grafana.org/installation/docker/#building-a-custom-grafana-image-with-pre-installed-plugins

@suikast42 if the official image is not exactly what you need then you should build your own. There are lots of examples out there. If you do want to use the Grafana image then is the link above what you were looking for?

Closing this as this is not a bug and I think the question has been answered.

**Closed by daniellee** 2018-04-30 07:41 UTC
Labels: type: question
