### ISSUE TITLE
[Bug] Alias on multiple metrics only uses first metric alias

### ISSUE THREAD

**Issue by bpiraeus** [grafana/grafana#7589] opened 2017-02-16 16:47 UTC
Version: 3.1 and 4.1
Datasource: OpenTSDB
OS: Ubuntu/FreeBSD

2 metrics in same panel - Alias for 1st metric is 'All', Alias for 2nd metric is 'Customer'
In the legend, both metrics are listed as 'All'
Expected 2nd metric legend to display as 'Customer'

This is a minor display issue and mostly an annoyance but it implies a singular override per panel instead of a per metric override for aliases.

**Comment by bpiraeus** [comment] 2017-02-16 16:51
![grafana_bug](https://cloud.githubusercontent.com/assets/2131748/23031238/8236dfa8-f42d-11e6-9021-d320ea0082cb.jpg)

**Comment by torkelo** [comment] 2017-02-16 17:40
There are about 10 other issues reported with the same problem, the root cause is OpenTSDB is missing a feature that made it possible to know which series in response came from which query, this should be fixed in OpenTSDB 2.3 (you also need to set OpenTSDB version in Grafana datasource options)

**Closed by torkelo** 2017-02-16 17:40 UTC

**Comment by bpiraeus** [comment] 2017-02-16 17:49
I didn't see the other issues when I looked, however I have OpenTSDB 2.3 and the version is set correctly, I just verified.

**Comment by torkelo** [comment] 2017-02-16 19:49
Then I don't know, maybe that OpenTSDB feature (show query) was not merged into 2.3
