### ISSUE TITLE
[mysql ]Problem with timefilter macro

### ISSUE THREAD

**Issue by drix1994** [grafana/grafana#13866] opened 2018-10-29 08:20 UTC
Read before posting: 

Please include this information:
### What Grafana version are you using?
Now 5.2.1 because I must do downgrade from 5.3.2
### What datasource are you using?
MySQL
### What OS are you running grafana on?
RedHat 7
### What did you do?
I used $__timeFilter(dateColumn) in mysql querry.
### What happened instead?
In your docs I found info: 
> $__timeFilter(dateColumn) | Will be replaced by a time range filter using the specified column name. For example, dateColumn BETWEEN ‘2017-04-21T05:01:17Z’ AND ‘2017-04-21T05:06:17Z’

In my opinion, your date format is incorrect. When I updated Grafana, then Grafana killed my database, because I created index on datetime column named "load_date" and when the alert module started, then a lot of querries with timefilter locked table because "2017-04-21T05:01:17Z" was not recognized as datetime and mysql was not able to use index...
Is it possibility to edit mysql macro myself?

My EXAMPLE:

> Before update:
![image](https://user-images.githubusercontent.com/30824428/47637244-6357b780-db5b-11e8-854c-1f765899daa0.png)

> After update:
![image](https://user-images.githubusercontent.com/30824428/47637263-6eaae300-db5b-11e8-971f-6d65617fb50f.png)

**Comment by marefr** [comment] 2018-10-29 12:34
Duplicate of #13769

**Comment by marefr** [comment] 2018-10-29 12:34
#13769is fixed and will be included in upcoming v5.3.3 release.

**Closed by marefr** 2018-10-29 12:34 UTC
