### ISSUE TITLE
9.4.1 - Export alerts not working when grafana is served from subpath

### ISSUE THREAD

**Issue by noaml-rb** [grafana/grafana#64230] opened 2023-03-06 14:04 UTC
**What happened**:
Grafana is running in kubernetes and served using ingres-nginx under a sub path. Relevant config from grafana.ini file:
[server]
domain = mydomain.example.com
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true

Connect to grafana using https://mydomain.example.com/grafana, login using the admin user
Go to Alerts → Alerts rules
Click on Export

a new page opens with the following url:
https://mydomain.example.com/api/v1/provisioning/alert-rules/export?download=true&format=yaml
the page displays the grafana 404 page

**What you expected to happen**:
I expect the export button will open 
https://mydomain.example.com/grafana/api/v1/provisioning/alert-rules/export?download=true&format=yaml
a file with the alerts is downloaded

**How to reproduce it (as minimally and precisely as possible)**:
Configure Grafana to work under a subpath using the following settings in grafana.ini file:
[server]
domain = <yourdomin>
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true

Login to Grafana using admin user,
Go to Alerts → Alerts rules
Click on Export

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.1
- Data source type & version:
- OS Grafana is installed on: Kubernetes 1.24
- User OS & Browser: macOS 13.2.1 , Chrome 110.0.5481.177
- Grafana plugins: None
- Others:

**Comment by MiggL** [comment] 2023-06-14 08:38
This was fixed in 9.4.4, see [#64136](https://github.com/grafana/grafana/pull/64136)
Also this issue is a duplicate of #64106

**Closed** 2023-07-07 09:18 UTC
Labels: area/data/export, triage/needs-confirmation
