### ISSUE TITLE
Alert show more will return page not found

### ISSUE THREAD

**Issue by valdemarpavesi** [grafana/grafana#87995] opened 2024-05-16 15:53 UTC
### What happened?

/grafana/alerting/list?search=fan

![image](https://github.com/grafana/grafana/assets/10376101/63c06543-2c18-4667-93e2-a80e08353b72)
![image](https://github.com/grafana/grafana/assets/10376101/0e705128-fdf1-403a-8a2e-a3b014b93a4d)

To reproduce the problem just need two pages with Alerts, and try to show more, in order to to see all alerts, and it will return page not found.

if have only 10 alerts, it will not be a problem.

Need more pages, like:
Showing 15 out of 4961 instances

### What did you expect to happen?

to sow all alerts

### Did this work before?

never

### How do we reproduce it?

n/a

### Environment (with versions)?

Grafana:  10/11
OS: Linux
Browser: any

### Grafana platform?

Kubernetes

**Comment by chenjie4255** [comment] 2024-05-17 06:47
same here.

I think the problem is due to a wrong redirect when using the subpath to serve grafana.

in my case:

```
root_url: https://xxxx.io/g2/
```

when I click the "show all alerts" button below

<img width="305" alt="image" src="https://github.com/grafana/grafana/assets/5313665/bd68e8f1-051d-4fa8-8a6f-97792d584969">

the page's URL becomes https://xxxx.io/g2/g2/xxxxxx......

manual removing the duplicated "g2" path above is a workable workaround.

**Comment by tonypowa** [comment] 2024-06-03 14:06
Thanks for reporting this issue and for sharing the solution @valdemarpavesi .
Closing the issue .

**Closed by tonypowa** 2024-06-03 14:06 UTC
