### ISSUE TITLE
graph stacking should exclude zero/null values

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#20786] opened 2019-12-01 22:02 UTC
Depending on your perspective, this might be a bug...

**What would you like to be added**:
Add an option to stacking to either sort the values presented in the graph (ascending/descending) or just exclude null/0 values from stacked values

**Why is this needed**:
When using "stacking" for the graph visualisation, it is possible to end up with values that are "0" being on the top of the graph. These obscure actual non-zero values. While the tooltip can be sorted, there is no way to sort the actual graph data.

See the attached screen shot as an example. The stacked graph shows the series with a value of "0" on top. That is not in any way intuitive to understand when looking at it. The two lines that I expect to see above the 0 baseline are hidden by values that are zero.

Why use "stacked"? Because disk throughput is being measured and in this case both series are so close together that they cannot be visually separated without stacking (which then tells you the wrong series is active.)

![Screen Shot 2019-12-02 at 8 58 01 am](https://user-images.githubusercontent.com/24280758/69920972-0d81db80-14e2-11ea-9175-7489951f9540.png)

**Comment by torkelo** [comment] 2019-12-02 22:21
duplicate of https://github.com/grafana/grafana/issues/15690

**Closed by torkelo** 2019-12-02 22:21 UTC
