### ISSUE TITLE
[Bug] Cannot get rid of "Empty Space"

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8120] opened 2017-04-13 16:32 UTC
Please include this information:
- What Grafana version are you using? 4.2.0
- What did you do? Expanded the size of a panel to 6 to make Empty Space go away
- What was the expected result? No more Empty Space
- What happened instead? Empty Space appeared in the next row

How to reproduce:
- Create a Row with a Graph that has a Span of 6
- Added a SingleStat to the Row and set its Span to 2
Realise that "OMG, what is this 'Empty Space' thing on the right?!?!?"
- Reisze SingleStat and set its Span to 6
(6 +6 = 12!)
Realise that "OMG, Grafana has moved 'Empty Space' to the row below?"

Solution:
Downgrade to 3.1.1 - No more "Empty Space" problems.

**Comment by torkelo** [comment] 2017-04-13 16:44
Strange, only one other report with similar experience, and multiple attempts to replicate with no success. So this must be a very rare case (as hundreds of thousands use 4.x without any issue like this). So very interested to know you do this :) 

Followed your instructions on http://play.grafana.org , no empty space
<img width="1278" alt="screen shot 2017-04-13 at 18 42 24" src="https://cloud.githubusercontent.com/assets/10999/25014666/fa17ca56-2078-11e7-8bc2-3f5f49526d0a.png">

What browser & OS are you using?

**Comment by torkelo** [comment] 2017-04-13 16:45
closing as it's a duplicate of https://github.com/grafana/grafana/issues/7068

**Comment by eighteen14k** [comment] 2017-04-13 17:01
Well you've closed #7068 too ... if you want more detail, don't close the bug.

Closing the bug means you don't want to work on it any more.

**Comment by eighteen14k** [comment] 2017-04-13 17:12
Browser version is Chrome 57.0.2987.133
OS is Windows 7

The txt file attachment is the JSON for the panel.

Curiously, after I saved the panel to JSON, the screen was then re-rendered and is now correct.

[Disk Space-1492103349167.txt](https://github.com/grafana/grafana/files/920344/Disk.Space-1492103349167.txt)

**Comment by eighteen14k** [comment] 2017-04-13 17:14
And once fixed, it stays fixed. But all I needed to do to reproduce it was reload the webpage from the browser, go back to "Span of 2", change the Span to 6 and voila, "Empty Space" is back.

**Comment by eighteen14k** [comment] 2017-04-13 18:18
The same behaviour is seen with the same version of Chrome on Mac OS.

The same behaviour is also seen with Firefox 45.8.0.

**Comment by eighteen14k** [comment] 2017-04-13 18:22
Are there any more details required?

**Comment by torkelo** [comment] 2017-04-13 20:26
that helped, managed to replicate it on mac if I did something I never do (and seems like most users almost never do it either as it's only 2 people who have reported this out of many thousand). It' funny the span option in the General tab is a relic from how you set spans in an old version of Grafana. Now close to all users use the drag handle in the lower right corner of panels (or the plus or minus icons in the panel menu). 

But your right, if you use the span dropdown in the general tab to specify panel width the empty space calculation is not re-triggered. Thanks for reporting this! will try to fix this soon.

**Comment by eighteen14k** [comment] 2017-04-14 01:42
I find that Span pull down very handy because:
1) it tells you that the total span space is 12
2) if you want to divide the space into 1, 2, 3, 4, 6 or 12 columns then there is a very precise way of doing this rather than doing custom resizes.

**Comment by torkelo** [comment] 2017-04-14 05:10
The resize handle snaps to the same grid, as does the plus and minus icons in the panel menu, but I understand it as some utility still :)

**Comment by agaon** [comment] 2017-05-25 15:15
Encountered the same bug. Workaround seems to work but it would be great if this could be fixed.

**Comment by MisterMartin** [comment] 2017-08-16 13:03
I've also encountered the same bug. I agree that the span pull down is useful.

**Comment by torkelo** [comment] 2017-12-18 14:46
fixed in latest master with new grid engine, https://www.youtube.com/watch?v=BC_YRNpqj5k&t=16s

**Closed by torkelo** 2017-12-18 14:46 UTC
Labels: comp: panel/common, type: bug

**Comment by robrwo** [comment] 2018-07-25 08:08
I've run across this too. But saving the panel and then reloading it seems to fix the issue.
