### ISSUE TITLE
Sort doesnt work in the new timeseries visualization on Grafana 8

### ISSUE THREAD

**Issue by vsenapathy** [grafana/grafana#37278] opened 2021-07-27 19:14 UTC
**What happened**: Sorting of table in timeseries visualization is not working

**What you expected to happen**: Sorting should work on the visualization (This worked in graph visualization)

**How to reproduce it (as minimally and precisely as possible)**: Create a dashboard with timeseries visualization and add data as a table to the right with current and max(This can be anything). Click on the current or max column and it should sort but it doesnt. Now change the visualization to graph and click on the columns and it should work

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Influx/1.7.8
- OS Grafana is installed on: Ubuntu 18.04.4 LTS
- User OS & Browser: Mac and Chrome
- Grafana plugins: boomtable, annunciator,blendstatmclock
- Others:

Thanks,

Vignesh

**Comment by zuchka** [comment] 2021-07-27 23:47
Hi @vsenapathy 

Thanks for creating this issue. Sorting legend items is under development. It currently has the 8.2.0 milestone. In other words, there should be a fix coming soon 👍 :

https://github.com/grafana/grafana/issues/30564

**Comment by afletch** [comment] 2021-09-24 12:39
#30564 is now also on the basis that issues are being tracked separately (i.e. here), yet this is also closed, therefore it seems there is no tracking of this issue which is open?

**Comment by zuchka** [comment] 2021-10-01 23:20
@afletch @vsenapathy to clairfy:

are we discussing legend sorting or sorting a field/column in a table when viewing `time-series` using the `Table view` toggle in the query editor?

**Comment by afletch** [comment] 2021-10-04 08:36
> @afletch @vsenapathy to clairfy:
> 
> are we discussing legend sorting or sorting a field/column in a table when viewing `time-series` using the `Table view` toggle in the query editor?

Legend sorting on time series chart - there's no ability to click the last/min/max/cur headers to sort the data.

**Comment by zoltanbedi** [comment] 2021-10-04 09:27
duplicate of #35429

**Closed by zoltanbedi** 2021-10-04 09:27 UTC
Labels: needs more info

**Comment by vsenapathy** [comment] 2021-10-04 14:35
@afletch :So legend sorting was available pre Grafana 8, as I added this ticket for that request only. Seems like there is already another bug to track this.

Thanks,

Vignesh
