### ISSUE TITLE
Successively trigger alert when Errors happened but no recovered.

### ISSUE THREAD

**Issue by MarcelLeon** [grafana/grafana#20494] opened 2019-11-20 04:07 UTC
I hope get more notifications after an error encounter but no recovered.

We adopt a way to notify Job status when our job consuming lag above threshold then trigger ALERT to Dingding chat group. But we found just one time alert message during the "error time" continue on. If we ignore this alert when the number of alert concurrency is large,and it will cause a big artificial mistake.
So, i can resolve problem via scan the grafana database's alert table in period,finding alert status is "Alerting" then trigger alert, but i don't think it is a sensible choice.
Do we have any plans for this problem? thx.

**Comment by MarcelLeon** [comment] 2019-11-20 04:08
![image](https://user-images.githubusercontent.com/17470121/69208397-63738c80-0b8e-11ea-8ee6-12367c09a5a8.png)

**Comment by marefr** [comment] 2019-11-20 13:49
Duplicate of #6041

**Comment by marefr** [comment] 2019-11-20 13:49
Have a look at [notifcation reminders](https://grafana.com/docs/alerting/notifications/#send-reminders) for a workaround.

**Closed by marefr** 2019-11-20 13:49 UTC
Labels: type/duplicate
