### ISSUE TITLE
Multiple edits of Folder/Dashboard Permissions can result in inconsistent database state and permission leak

### ISSUE THREAD

**Issue by btmc** [grafana/grafana#28615] opened 2020-10-28 18:52 UTC
**What happened**:

Making certain sequence of actions on Folder or Dashboard Permissions tab result in ability of users, whose permissions are based only on organization role (tested for viewer) gain access to dashboards with permissions those of configured for teams or users, not for organization roles.

For example, if Folder/Dashboard Permissions include a team with Edit permission, every user who falls under organization role Viewer also can edit dashboards inside folder/that dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

In this example "Folder 1" has corresponding object with dashboard.id=1 in sqlite3 database, "Team 1" also has corresponding object with team.id = 1.

- Go to "Dashboards -> Manage", select Folder 1 (for example), go to Permissions tab.
- There are only two default editable permissions for organization roles Editor and Viewer.

At this moment the following query to sqlite3 database should return no records:
```
sqlite> select * from dashboard_acl where dashboard_id = 1;
```
- Remove Viewer role by hitting red button in corresponding row.
- Click "Add permission", "Add permission for" window appears.
- Select "Everyone With Viewer Role" and "View" and hit "Save", corresponding row is added to permissions table.
- Select "Team", "Team 1" (in this example) and "Edit" and hit "Save", corresponding row is added to permissions table.

At this moment the following query should return 3 records:
```
sqlite> select * from dashboard_acl where dashboard_id = 1;

          id = 1
      org_id = 1
dashboard_id = 1
     user_id =
     team_id =
  permission = 2
        role = Editor
     created = 2020-10-28 18:30:18
     updated = 2020-10-28 18:30:18

          id = 2
      org_id = 1
dashboard_id = 1
     user_id =
     team_id =
  permission = 1
        role = Viewer
     created = 2020-10-28 18:30:18
     updated = 2020-10-28 18:30:18

          id = 3
      org_id = 1
dashboard_id = 1
     user_id =
     team_id = 1
  permission = 2
        role = Viewer
     created = 2020-10-28 18:30:18
     updated = 2020-10-28 18:30:18
```
Notice that record 3 has both team_id and role filled in, and permission = 2 (edit).

- Add some dashboard "Dashboard 1" to this folder (with default permissions).
- Login as user "User Viewer" not in "Team 1" with Viewer role in organization.
- Ensure that this user "User Viewer" can edit "Dashboard 1".
- Remove permission for "Team 1" from "Folder 1".
- Ensure that "User Viewer" can not edit "Dashboard 1" anymore.

**Anything else we need to know?**:

List of permissions in Folder/Dashboard Permissions tab after such edit looks normal, as there is a permission for role Viewer (View) and a permission for team "Team 1" (Edit), but the database state is different.

**Environment**:
```
- Grafana version:
Grafana v7.2.0 (efe4941ee3)

- OS Grafana is installed on:
CentOS 7
Docker image: grafana/grafana:7.2.0

- User OS & Browser:
Google Chrome: 86.0.4240.111 (Official Build) (x86_64)
OS:            macOS Version 10.14.4 (Build 18E226)
```

**Comment by btmc** [comment] 2020-10-29 08:44
Visualization of the chain of actions in Permissions tab.

![Kapture 2020-10-29 at 11 36 22](https://user-images.githubusercontent.com/22390036/97545181-a8798300-19db-11eb-92a0-ed7095653024.gif)

**Comment by wbrowne** [comment] 2020-10-29 17:20
Thanks for reporting this @btmc and for the clear steps for reproducing 😄  I was indeed able to reproduce what you saw. I'll dig a bit deeper to understand what's going on

**Comment by marefr** [comment] 2020-11-05 21:46
Sounds like some kind of state bug and should maybe escalate/ask frontend platform team for help so we can get out a fix in upcoming patch release.

**Comment by wbrowne** [comment] 2020-11-11 17:14
@btmc Can you confirm if the `dashboard_acl` row inserted from adding the Team edit permission has value `Viewer` for the `role` column (as specified in your comment above)?

**Comment by btmc** [comment] 2020-11-11 17:51
@wbrowne Yes, I can confirm that.
Reproduced it now in a fresh container with version 7.3.2:

```
select * from dashboard_acl where dashboard_id = 3;
```

Nothing initially.

After removing Viewer role:

```
          id = 9
      org_id = 1
dashboard_id = 3
     user_id =
     team_id =
  permission = 2
        role = Editor
     created = 2020-11-11 17:39:04
     updated = 2020-11-11 17:39:04
```

After re-adding Viewer role:

```
          id = 10
      org_id = 1
dashboard_id = 3
     user_id =
     team_id =
  permission = 2
        role = Editor
     created = 2020-11-11 17:39:27
     updated = 2020-11-11 17:39:27

          id = 11
      org_id = 1
dashboard_id = 3
     user_id =
     team_id =
  permission = 1
        role = Viewer
     created = 2020-11-11 17:39:27
     updated = 2020-11-11 17:39:27
```

After adding a team with Edit permission:

```
          id = 12
      org_id = 1
dashboard_id = 3
     user_id =
     team_id =
  permission = 2
        role = Editor
     created = 2020-11-11 17:40:02
     updated = 2020-11-11 17:40:02

          id = 13
      org_id = 1
dashboard_id = 3
     user_id =
     team_id =
  permission = 1
        role = Viewer
     created = 2020-11-11 17:40:02
     updated = 2020-11-11 17:40:02

          id = 14
      org_id = 1
dashboard_id = 3
     user_id =
     team_id = 1
  permission = 2
        role = Viewer
     created = 2020-11-11 17:40:02
     updated = 2020-11-11 17:40:02
```

**Comment by wbrowne** [comment] 2020-11-12 11:29
Interesting - Thank you for clarifying @btmc. I think I may have narrowed down where the problem is occurring. Would you be able to provide the request payload for the POST `api/folders/<uid>/permissions` call when you add the team edit permission?

Apologies for the back and forth! I seem to be having trouble being able to reproduce this again myself strangely

**Comment by btmc** [comment] 2020-11-12 12:45
The POST request payload is:
```
{"items":[{"userId":0,"teamId":0,"role":"Editor","permission":2},{"userId":0,"teamId":0,"role":"Viewer","permission":1},{"userId":0,"teamId":1,"role":"Viewer","permission":2}]}
```

**Comment by wbrowne** [comment] 2020-11-12 15:28
@btmc Thanks for finding this bug! I believe I've found the root of the problem and have created a separate issue to track its fix, so will close this one

**Closed by wbrowne** 2020-11-12 15:28 UTC
Labels: area/backend, area/permissions, needs investigation
