### ISSUE TITLE
Generic Oauth role mapping always refers to OrgId 1

### ISSUE THREAD

**Issue by Darkeye9** [grafana/grafana#22277] opened 2020-02-18 17:24 UTC
**What happened**: Tried to enable Oauth with Role mapping on a already used database and the message "Login Failed: user does not belong to org"

**What you expected to happen**: The user could login correctly from Oauth

**How to reproduce it (as minimally and precisely as possible)**:
Setup a clean grafana setup, create a new Org, and delete the default one. Now configure Oauth and try to login.

The code at https://github.com/grafana/grafana/blob/master/pkg/api/login_oauth.go#L189 sets the roles always referenced to OrgId 1, which does not exists now. The error raises as soon as the ORM tries to add the user to the org.

**Anything else we need to know?**:
I know this is a newly developed feature, and in the happy path, it worked. But I dont think is feasible that everyone is restricted to use the default Org to interface with Oauth. What's more, for people like me, who deleted the original Org, it is nearly impossible to return to an usable state, due to the id being an AUTOINCREMENT.

What I think should be done is to add another generic field to the Oauth implementation enabling the IDM/IdP to specify the Org Name, and match by that.

**Environment**:
- Grafana version: 6.6.0-beta.1.0 (The bug is present in master branch also)
- Data source type & version: N/A
- OS Grafana is installed on: Docker
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

Although I am a newbie to Go, I can try to implement a PR if someones review my proposed solution.

**Comment by aknuds1** [comment] 2020-02-18 17:36
This should be a duplicate of #22188. I'm working on a PR for this bug, initial testing is promising.

**Closed by aknuds1** 2020-02-18 17:36 UTC
