### ISSUE TITLE
[Bug] Dashboard drops out of kiosk mode when using playlist

### ISSUE THREAD

**Issue by hreidar** [grafana/grafana#6864] opened 2016-12-07 10:07 UTC
Version: Grafana 4.0.1
DS: Prometheus
OS: Docker container running on Alpine Linux

What I did:
Created couple of dashboards, saved them in kiosk mode (using short-cut keys), added them to a playlist.

What I wanted:
Playlist running dashboards in kiosk mode

What I got:
Playlist running normal dashboards

Hi, I filed this as a bug but maybe it should be a feature request. Anyhow, the new kiosk mode is awesome and it would be a shame if it can't be used in playlists.

**Comment by bergquist** [comment] 2016-12-07 10:45
Dupe of https://github.com/grafana/grafana/issues/6727
Fixed and will be available in 4.1.0 and 4.0.2 or nightly builds att grafana.org/builds

**Closed** 2016-12-07 10:50 UTC
