### ISSUE TITLE
Bar gauge doesn't fill up whole space up to Max

### ISSUE THREAD

**Issue by jtommi** [grafana/grafana#26175] opened 2020-07-08 17:43 UTC
**What happened**:
I have a bar gauge showing percentages (0-1) and I have a gap after the 100%.
Depending on the size of the panel the size of the gap also varies.
As you can see, I set Max to 1. Setting it to auto does exactly the same.
![image](https://user-images.githubusercontent.com/33985391/86951936-8325e800-c152-11ea-9750-b360d067468b.png)

From playground : https://play.grafana.org/d/vmie2cmWz/bar-gauge?editPanel=4&orgId=1&refresh=10s
![image](https://user-images.githubusercontent.com/33985391/86951995-99cc3f00-c152-11ea-9a02-7b56dc9bf324.png)

It looks like the size of the gap depends on the thickness of the bar:
- thick bar : small gap
- thin bar : big gap

![image](https://user-images.githubusercontent.com/33985391/86952317-16f7b400-c153-11ea-8a11-82cb99ec83bd.png)
![image](https://user-images.githubusercontent.com/33985391/86952321-19f2a480-c153-11ea-9776-25b36b66c1f8.png)

**What you expected to happen**:
There shouldn't be any space left once the value reaches the maximum

**How to reproduce it (as minimally and precisely as possible)**:
Use data that goes up to the max defined in the panel.
It can be seen in the playground: https://play.grafana.org/d/vmie2cmWz/bar-gauge?editPanel=4&orgId=1&refresh=10s

**Anything else we need to know?**:
I asked first on the forum: https://community.grafana.com/t/bar-gauge-max-not-working-as-expected/33324

**Environment**:
- Grafana version: 7
- Data source type & version: MySQL
- OS Grafana is installed on: don't know
- User OS & Browser: Win 10 & Firefox
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment] 2020-07-08 18:41
dupe of https://github.com/grafana/grafana/issues/24954

**Closed by torkelo** 2020-07-08 18:41 UTC
