### ISSUE TITLE
[Feature request] Allow formatting in notification of alert

### ISSUE THREAD

**Issue by ictcorebiz** [grafana/grafana#7094] opened 2016-12-29 14:02 UTC
Please include this information:
- What Grafana version are you using?
**4.0.2**
- What datasource are you using?
**Prometheus**
- What OS are you running grafana on?
**Linux / Docker**
- What did you do?
**Create a notification message for an alert, with formatting using &lt;br/&gt; and &lt;hr/&gt; codes**
- What was the expected result?
**The e-mail would contain a formatted message**
- What happened instead?
**The &lt;br/&gt; were not interpreted as html, but shown as text, hence formatting was not done**

I created a simple message:

````
The health of this system is not GREEN, or has recently changed back to GREEN.

Value - description
4 - GREEN
2 - YELLOW
0 - RED
````

But in mail, all enters were gone, and all text was concattenated.

````
The health of this system is not GREEN, or has recently changed back to GREEN. Value - description 4 - GREEN 2 - YELLOW 0 - RED
````
Adding html &lt;br/&gt; and &lt;hr/&gt; for formatting didn't work because the string was literally shown.
````
The health of this system is not GREEN, or has recently changed back to GREEN. <br/> Value - description<br/> 4 - GREEN<br/> 2 - YELLOW<br/> 0 - RED<br/> <hr/>
````

I would like to have some way to do basic formatting for the mails.

**Comment by bergquist** [comment] 2017-01-02 09:21
Good input but it feels like a dupe of https://github.com/grafana/grafana/issues/5848

**Closed by bergquist** 2017-01-02 09:21 UTC
Labels: comp: alerting, comp: alerting/notifications, type: feature request
