### ISSUE TITLE
Delayed datasource connection error still shows after switching

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#17405] opened 2019-06-03 07:10 UTC
**What happened**:

In Explore, a connection error for a long running ds connection test still shows up after already having switched to another datasource:

<img width="365" alt="Screenshot 2019-06-03 at 09 08 11" src="https://user-images.githubusercontent.com/859729/58782513-26ffa480-85df-11e9-9c78-53c2b7ccf61f.png">

**What you expected to happen**:

The error should not be shown.

**How to reproduce it (as minimally and precisely as possible)**:

Needs a ds that takes long to load labels.

**Comment by ivanahuckova** [comment] 2019-09-17 14:58
@davkal  I think that this issue has been fixed. I have tested it (see below), and issue is not there anymore. 
@kaydelaney is it possible that this bug was fixed after the Slate update?
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/30407135/65053504-565ad700-d96c-11e9-9ca8-eb75b8182889.gif)

**Comment by ivanahuckova** [comment] 2019-09-24 08:48
@davkal I have tested this issue and I couldn't reproduce the bug - see the gif. I think that it has been fixed before. Is it okay to close the issue?

**Comment by ivanahuckova** [comment] 2020-01-20 11:47
I have tried to unsuccessfully reproduce this again. Everything works as expected, therefore I am closing this issue.

**Closed by ivanahuckova** 2020-01-20 11:47 UTC
Labels: area/explore, onboarding, type/bug
