### ISSUE TITLE
theme does not load after changing it from the configuration file

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#55805] opened 2022-09-27 10:47 UTC
**What happened**:

While working on an issue at https://community.grafana.com/t/it-all-turned-white-but-im-in-dark-mode/72598 I run into sort of similar (but not 100% exact) problem.

As per the user. he probably pressed a special shortcut key which changed the Default Theme colour from Dark to White and then when trying to change it back into the option via UI settings, cannot set it back to Dark mode

**What you expected to happen**:

The theme gets changed back to Default (dark) mode

**How to reproduce it (as minimally and precisely as possible)**:

I was partially (not as exact as the user because I do not know the secret shortcut key which changes the theme) able to reproduce it like this.

1- Login to Grafana via admin account and change the theme from dark to white (works as expected)
2- Logout from the UI
3- Change the configuration (/etc/grafana/grafana.ini) parameter from;

`default_theme = dark
`
4- Restart the grafana service
5- login back from the admin account
6- The theme is still white (which I changed in step 1)

The expected result should be that the configuration should take effect and the theme changes back to the dark mode

**Anything else we need to know?**:

**Environment**: locally installed
- Grafana version:  v9.1.6 (92461d8d1e)
- OS Grafana is installed on: CentOS
- User OS & Browser: reproducible on all Chrome, Firefox and even in their incognito mode (after clearing cache n cookies)

**Comment by usmangt** [comment] 2022-09-27 11:26
I think its a bug so adding the label and moving to the User Essentials. Incase I am wrong then please let me know

**Comment by ashharrison90** [comment] 2022-09-27 13:52
@usmangt i _think_ this is working as designed 

first off, the magic key combinations are here (`t t` and `t r`): https://github.com/grafana/grafana/blob/main/public/app/core/services/keybindingSrv.ts#L48

i think these should probably be dev-only key combinations. can't really think of a major use case for having a key combination to switch theme other than it being quicker when developing. if anything, it's just likely to cause confusion for users who accidentally hit it. any thoughts on this @grafana/user-essentials ?

as you mentioned there are two ways to set the theme, either via the config or via the preferences UI. when both are set, UI preferences take precedence. and using the special key combinations sets a UI preference (you can see this if you look in the network tab when pressing the key combinations, it dispatches a request to the `/preferences` api). so setting it via the config won't override this. the only way to change it back is to do it via the preferences UI. 

also worth mentioning if you're an organization admin, there are 2 places where you can set the preferences (org preferences or user preferences). lowest level preferences always take precedence (https://grafana.com/docs/grafana/latest/administration/organization-preferences/#organization-preferences), so a **user** preference set via the UI should always work. 

so with that in mind, setting the user preference here:
![image](https://user-images.githubusercontent.com/20999846/192544888-326d87b2-568c-4faf-81ef-92ede4fed25d.png) should fix things. 

let me know if that makes sense/helps and i can close the issue. 😄

**Comment by andreapx** [comment] 2022-09-27 14:24
Ah, the `tt` shortcut did it!!!
And probably the shortcut works on the user preference since I was checking in the general preferences and at was already in dark mode.
THANKS!

**Closed** 2022-09-27 14:30 UTC
Labels: type/bug, area/ui/theme

**Comment by tomerr90** [comment] 2023-08-21 10:46
In the version Im using the shortcut is "ct" but its still not working, it changing it to dark mode and says "Preferences Updated" but when I refresh its back to light

**Comment by ashharrison90** [comment] 2023-08-21 10:54
@tomerr90 ...and that version is? 😅

the behaviour was particularly buggy early on so it being lost on refresh isn't super surprising, especially if you're on a version pre-10.0.0. if you're on a version >10.0.0 and it's not working for you, can i suggest you raise a new issue following the issue template so we can investigate. thanks! 🙏

**Comment by tomerr90** [comment] 2023-08-21 11:04
Right, sorry, Im on 9.5.1

**Comment by tomerr90** [comment] 2023-08-21 11:22
So my only option here is to upgrade version?

**Comment by tomerr90** [comment] 2023-08-21 12:00
I cant upgrade, and I already tried the profile and it does nothing

**Comment by ashharrison90** [comment] 2023-08-21 12:05
@tomerr90 then i suggest you raise a new issue detailing the problem with setting the theme via the profile page. that should absolutely work in 9.5.1 👍
