### ISSUE TITLE
Influx: No template variables used, but "template variables are not supported in alert queries" received

### ISSUE THREAD

**Issue by flynn1973** [grafana/grafana#26326] opened 2020-07-14 12:02 UTC
**What happened**:
 "Template variables are not supported in alert queries" message when trying to add alerts to a dashboard which
explicitly contain NO templating variable.

**What you expected to happen**:
as the mentioned dashboard has no templating variables i expect no annoying error messages

**How to reproduce it (as minimally and precisely as possible)**:
try to add alerts to a dashboard without templating variables i guess?
**Anything else we need to know?**:
the questioned dashboard configuration
![query](https://user-images.githubusercontent.com/14803546/87423430-94e80f00-c5da-11ea-90ce-d2c1144fe908.PNG)

**Environment**:
- Grafana version: v7.2.0-pre (74b2c2a)
- Data source type & version: influxdb
- OS Grafana is installed on: linux
- User OS & Browser: Windows/Firefox
- Grafana plugins: nne
- Others:

**Comment by ivanahuckova** [comment] 2020-07-15 17:07
I was able to replicate the issue on current master (on [grafana.play](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) it is still correctly working). So the issue was probably introduced between https://github.com/grafana/grafana/commit/74b2c2acdcece0a3a9b6a4ad849f9c294d115090 and (9f4a172a76). To recreate the issue, just open panel with influx data source and open alerting tab. You will see "Template variables are not supported in alert queries" .

**Comment by ryantxu** [comment] 2020-07-15 17:52
Template variables are not supported in alerting for any datasource.  Long list of reasons for this... and will likely be solved by moving alert queries to their own concept:

Duplicate of: https://github.com/grafana/grafana/issues/6557

**Comment by ivanahuckova** [comment] 2020-07-15 18:00
@ryantxu I should have updated the title. Problem is that on master, when you create influxdb query without template variables, you still receive this message.

**Comment by torkelo** [comment] 2020-07-16 05:38
I think this could be related to Hugo's PR that made __dashboard and __org __user  system variables, and if returned via getVariables could mess with this warning

**Comment by ivanahuckova** [comment] 2020-07-16 15:21
@torkelo thanks! I have added it to Platform Backlog. @hugohaggmark fyi.

**Comment by torkelo** [comment] 2020-07-16 17:02
Unable to replicate in 7.1, so maybe only a master thing, strange, wonder what could be the cause then

**Comment by superbool** [comment] 2020-07-17 02:57
Problem may be here:

[v7.1.0](https://github.com/grafana/grafana/blob/v7.1.0/public/app/features/templating/template_srv.ts#L270)
```
variableExists(expression: string) {
    const name = this.getVariableName(expression);
    return name && this.getVariableAtIndex(name) !== void 0;
  }
```

[master](https://github.com/grafana/grafana/blob/master/public/app/features/templating/template_srv.ts#L270)
```
variableExists(expression: string): boolean {
    const name = this.getVariableName(expression);
    return (name && this.getVariableAtIndex(name)) !== undefined;
  }
```

When [`const name = this.getVariableName(expression);` ](https://github.com/grafana/grafana/blob/master/public/app/features/templating/template_srv.ts#L262)
retrun `null`, the [v7.1.0](https://github.com/grafana/grafana/blob/v7.1.0/public/app/features/templating/template_srv.ts#L270) will return `null`, but [master](https://github.com/grafana/grafana/blob/master/public/app/features/templating/template_srv.ts#L270)  will return `true`;

**Comment by ivanahuckova** [comment] 2020-07-17 06:50
Thanks @superbool for looking into this! Yeah, it is due to typescript strict null errors fix that wasn't part of 7.1.

**Comment by flynn1973** [comment] 2020-08-12 14:48
any idea when this will get fixed?

**Comment by ivanahuckova** [comment] 2020-08-12 15:09
@flynn1973 It was already fixed in https://github.com/grafana/grafana/pull/26453 and was part of 7.1.2 release.

**Closed by ivanahuckova** 2020-08-12 15:09 UTC
Labels: area/alerting, area/dashboard/templating, datasource/InfluxDB, priority/important-soon, type/bug
