### ISSUE TITLE
Variables: Wrong selected state is persisted when Save current... checkbox is skipped

### ISSUE THREAD

**Issue by dessen-xu** [grafana/grafana#32883] opened 2021-04-12 08:23 UTC
**What happened**:

When change variable options, then save dashboard that do not select "Save current variable values as dashboard default". Then we get a bug that current value is value that before change, but selected value is value that after change.

example:

![image](https://user-images.githubusercontent.com/41524013/114360932-2c00e800-9ba8-11eb-890e-3bbaee883026.png)
Initial value is "aaa".

![image](https://user-images.githubusercontent.com/41524013/114361085-5b175980-9ba8-11eb-95a7-f5a2a3012057.png)
Then I select other value "*",  save dashboard that do not select "Save current variable values as dashboard default".

![image](https://user-images.githubusercontent.com/41524013/114361513-c82aef00-9ba8-11eb-9f29-09ca32de577a.png)
Open the dashboard again, we can see the current value is "aaa".

![image](https://user-images.githubusercontent.com/41524013/114361898-4edfcc00-9ba9-11eb-9a65-d55517bab48f.png)
But the selected value is "*".

The JSON is incorrect：
![image](https://user-images.githubusercontent.com/41524013/114363068-9fa3f480-9baa-11eb-9aba-5af081fbe69f.png)

**What you expected to happen**:

If I save dashboard that do not select "Save current variable values as dashboard default", the variable do not shoule be changed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.1
- Data source type & version:
- OS Grafana is installed on: mac OS
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment] 2021-04-12 11:02
Hi @dessen-xu and thank you for reporting this. We're thinking about removing selected in the future so this property is to be considered as an internal implementation detail and this is working as intended for now at least. I'm going to close this for now, but we'll reopen this if more feedback or evidence is collected.

**Comment by dessen-xu** [comment] 2021-04-13 03:34
I made a video for this problem, please look at it.


https://user-images.githubusercontent.com/41524013/114492267-d4678880-9c4a-11eb-8595-cd180ecc4c9d.mov

When I open the dashboard after save it, current is " * " but selected value is "aaa", This led to I can not select " aaa ", or not trigger query when select " * ". I must reset the variable. So please review it, the problem had affected us.

**Comment by hugohaggmark** [comment] 2021-04-13 04:30
I see the issue, when you select the saved `current` variable there is a slight issue when you have refresh set to `Never`. The work around is to set refresh to 'On Dashboard Load'. 
![image](https://user-images.githubusercontent.com/562238/114496975-5fcc2400-9c21-11eb-84aa-f94fae5af828.png)

I'll reopen this and see if we can do a proper fix for this. I created a dashboard here: https://play.grafana.org/d/rZFEoIuGk/variable-bug-32883?editview=templating&orgId=1

**Comment by dessen-xu** [comment] 2021-04-13 06:14
No matter what type of variable variable, the problem exists.

**Comment by hugohaggmark** [comment] 2021-04-13 06:24
> No matter what type of variabl, the problem exists.

If you change your refresh to `On Dashboard Load` the problem shouldn't exist.

**Comment by msober** [comment] 2021-04-13 07:11
let me describe the problem again. first, you add a custom type variable, has three options, like option1, option2, option3. and the option1 is defalult selected by grafana.  its image:
![image](https://user-images.githubusercontent.com/1792217/114506767-d4748200-9c64-11eb-9ce0-ff33ecdb2d63.png)
corresponding json:
```json
{
        "allValue": null,
        "current": {
          "selected": false,
          "text": "option1",
          "value": "option1"
        },
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "datasource",
        "options": [
          {
            "selected": true,
            "text": "option1",
            "value": "option1"
          },
          {
            "selected": false,
            "text": "option2",
            "value": "option2"
          },
          {
            "selected": false,
            "text": "option3",
            "value": "option3"
          }
        ],
```
then, I change the value of datasource select to option2, then save the dashborad without select `Save current variable values as dashboard default` checkbox, the dashboard json becomes that **current select datasource is still option1 in `current json object`, but option2 becomes selected in `options json array`**, like:

```json
{
        "current": {
          "selected": false,
          "text": "option1",
          "value": "option1"
        },
       
        "options": [
          {
            "selected": false,
            "text": "option1",
            "value": "option1"
          },
          {
            "selected": true,
            "text": "option2",
            "value": "option2"
          },
          {
            "selected": false,
            "text": "option3",
            "value": "option3"
          }]
}

```
shows like:
![image](https://user-images.githubusercontent.com/1792217/114509096-b4928d80-9c67-11eb-9af6-2f7c9191c512.png)

At this time the hidden problem appeared, when you click datasource input, the option2 is default selected[with Highlight],  like:
![image](https://user-images.githubusercontent.com/1792217/114509552-38e51080-9c68-11eb-86d1-c2c0da741c63.png)

But user still think option1 is the current selected value,  then they want change to option2, when click option2, the value of datasource' select will not change, it will still option1, **their operation not work, noting change**, so this causes the bug that the current select variable option1 in `current json object` **is conflicted with** selected option2 in `options json array` @hugohaggmark hugohaggmark

**Comment by DmitrySidorow** [comment] 2021-04-13 07:26
I also described this problem recently
https://github.com/grafana/grafana/issues/32670

**Comment by dessen-xu** [comment] 2021-04-14 07:59
@torkelo please review it.

**Closed** 2021-05-18 04:10 UTC
Labels: area/dashboard/templating, priority/nice-to-have, type/bug
