### ISSUE TITLE
Go to a future time range with the arrow shortcut next to the zoom out 

### ISSUE THREAD

**Issue by gwuillou** [grafana/grafana#12847] opened 2018-08-08 15:47 UTC
### What Grafana version are you using?
5.1.3
### What datasource are you using?
influxdb
### What OS are you running grafana on?
linux
### What did you do?
![](https://cloud.githubusercontent.com/assets/10656485/21223864/59e82298-c2c1-11e6-82a3-b9fb756b71cc.png)
use the right arrow to go in the future
### What was the expected result?
the time range goes to the future (next day)
### What happened instead?
nothing happends

Perhaps it is related to:
https://github.com/grafana/grafana/issues/6976

**Comment by daniellee** [comment] 2018-08-09 10:12
This seems to work for me. Test it here: https://play.grafana.org/d/000000002/influxdb-templated-queries?orgId=1

The time range is last 1 hour. After clicking on the right arrow at 12:09, the selected time interval jumps 30 minutes forward into the future:

![image](https://user-images.githubusercontent.com/434655/43892795-3aaf2f8e-9bcd-11e8-8085-8b8f56019170.png)

Need more detail about why it does not work for you.

**Comment by gwuillou** [comment] 2018-08-09 10:41
Ok. I found. You have to go to the past and then to the future. It can not go into the future. On your example also.

**Comment by daniellee** [comment] 2018-08-09 12:59
You'll have to explain that a bit more. In my example, the time range changed by 30 minutes as far as I can see.

**Comment by gwuillou** [comment] 2018-08-10 09:42
I know it is a little bit strange for a bug. I explain again:

Try to go into the past with the left arrow in order to have the right time range limit in the past. Then go into the future with the right arrow. You will go until the present and then the right time range limit will move by 1 second for each click on the right arrow.

**Comment by daniellee** [comment] 2018-08-10 15:53
Thanks for the more detailed explanation.

**Comment by gwuillou** [comment] 2018-09-27 12:05
Any news about this issue?

**Comment by torkelo** [comment] 2018-12-17 10:23
closing this, I think it works as intended.

**Closed by torkelo** 2018-12-17 10:23 UTC
Labels: needs investigation

**Comment by gwuillou** [comment] 2018-12-17 10:48
Hello,

Sorry but I am not sure it works as attended. If yes it is not very user friendly... In my case, I goes often from the past to the future, therefore, it is not useful.
I did an example of the problem on the follow link:
[ https://play.grafana.org/d/000000002/influxdb-templated-queries?orgId=1](url)

![grafana_bug](https://user-images.githubusercontent.com/20662503/50082530-831d6a80-01f1-11e9-86af-d6d8dbde63b5.gif)

Sorry for the image quality.

**Comment by torkelo** [comment] 2018-12-17 11:11
What does to the future? When? When you zoom out it will zoom out in both directions, is that what you object to?

**Comment by gwuillou** [comment] 2018-12-17 11:59
It is not a problem with the zoom out I think but with the right arrow to go in the future as explain in my previous message. https://github.com/grafana/grafana/issues/12847#issuecomment-412033495.
The problem of @flopp999  is not the same I think.

**Comment by torkelo** [comment] 2018-12-17 17:07
you cannot use the arrows to go into the future?

**Comment by gwuillou** [comment] 2018-12-17 17:09
If you are before the present and you want to go in the future with the right arrow you cannot. It go just one second after one second.

**Comment by gwuillou** [comment] 2018-12-19 08:07
Here a gif more clear!

![grafana_bug2](https://user-images.githubusercontent.com/20662503/50206986-74f45900-036d-11e9-9538-23fc63efc341.gif)

**Comment by gwuillou** [comment] 2018-12-19 14:53
I think the problem is: there is a check that does not allow to go in the future and it is why it move second by the second with the current time. What is the reason for that?

**Comment by gwuillou** [comment] 2019-11-29 12:36
Answers?
