### ISSUE TITLE
Editing graphs doesn't work properly on 5.0

### ISSUE THREAD

**Issue by gontikas** [grafana/grafana#11321] opened 2018-03-20 20:08 UTC
Hello, 

I recently installed Grafana 5.0 and I am having issues editing a graph, once it is created. 
These graphs were created in 4.1.2 and were imported to 5.0.

First I select edit graph
![image](https://user-images.githubusercontent.com/26825136/37679706-be7310b2-2c4f-11e8-9bd6-95695f3d467b.png)

When I go to edit, the graph title is not the one I selected and I do not see any editing options. 
![image](https://user-images.githubusercontent.com/26825136/37679753-e29fbe04-2c4f-11e8-817e-05359d7074d8.png)

I found a way to get the correct graph and edit it. I have to change the variable to another one. For example from DNSGPLR01 to DNSGTTN01
![image](https://user-images.githubusercontent.com/26825136/37679799-0704b1fa-2c50-11e8-9607-b24b466e3f06.png)

**Comment by torkelo** [comment] 2018-03-20 23:55
Strange, are you using repeating panels? If you open chrome dev tools console any error there?

**Comment by daniellee** [comment] 2018-03-21 10:11
Also, what browser are you using? Those screenshots look strange - are you using IE11?

**Comment by gontikas** [comment] 2018-03-21 14:34
Hello. I cannot reproduce it anymore  :(
I am using Chrome and I do duplicate panels.

**Comment by marefr** [comment] 2018-04-12 13:10
Closing this since you cannot reproduce it.

**Closed by marefr** 2018-04-12 13:10 UTC
Labels: comp: dashboard, state: needs more detail
