### ISSUE TITLE
Why does Grafana send NULL Request Object to datasource Backend

### ISSUE THREAD

**Issue by dk25094** [grafana/grafana#8082] opened 2017-04-10 17:36 UTC
Hi Grafana Experts,

I am working on a BigQuery Datasource plugin.
In my backend implementation of the /query interface, I noticed initially I was getting a good Request Object with the correct panelID, target etc. But after some time, it sends a NULL Request object. In glancing through the backend_srv code, I noticed there is a cancellation logic and sqlite3 db.

My last fix was to reinstall everthing and it worked again.

Can someone explain what is causing Grafana to send an OPTIONs null request object when POSTing to /query and how I can  reset ( Suspect  the sqlite?)  or other mechanism to reset this ?

thanks
deepak

**Comment by torkelo** [comment] 2017-04-10 18:26
dupe of https://community.grafana.com/t/backend-datasource-request-object-null/422/2

**Closed by torkelo** 2017-04-10 18:26 UTC
