### ISSUE TITLE
V7.1 beta2 Influxb v1.8 Flux Support - Datasource Setup issues

### ISSUE THREAD

**Issue by FortDigital** [grafana/grafana#26051] opened 2020-07-03 11:50 UTC
**What happened**: Whilst setting up the Flux Plugin for Influxdb 1.8 i get This error when using a config that should work:

![image](https://user-images.githubusercontent.com/62287745/86465933-8cfeb400-bd2a-11ea-9bcd-7401ae8d48f2.png)

In the Logs i get:

`{"@level":"info","@message":"buckets() =\u003e {telegraf/autogen telegraf/autogen DummyOrg}","@timestamp":"2020-07-03T10:57:00.817062Z"},
t=2020-07-03T10:57:00+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=172.28.0.1 time_ms=33 size=963 referer=http://localhost:8080/datasources/edit/8/,
{"@level":"info","@message":"buckets() =\u003e {  dummyorg}","@timestamp":"2020-07-03T11:05:11.614024Z"},
t=2020-07-03T11:05:11+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=172.28.0.1 time_ms=36 size=963 referer=http://localhost:8080/datasources/edit/8/,
t=2020-07-03T11:41:14+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="missing organization in datasource configuration" remote_addr=172.28.0.1,
t=2020-07-03T11:41:14+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_addr=172.28.0.1 time_ms=4 size=34 referer=http://localhost:8080/datasources/edit/8/`

However in Influxdb1.8 there is no concept of Organizations so this field should not be required, I can bypass this by adding a dummy org code but i get a further error:

![image](https://user-images.githubusercontent.com/62287745/86466053-d64f0380-bd2a-11ea-816d-7260d13b322a.png)

{"@level":"info","@message":"buckets() =\u003e {  DummyOrg}","@timestamp":"2020-07-03T11:43:33.946197Z"},
t=2020-07-03T11:43:33+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=172.28.0.1 time_ms=35 size=963 referer=http://localhost:8080/datasources/edit/8/

If i ignore this and go on to use the plugin it works, it looks like the flux code buckets() is being used to test the datasource is working however buckets() does not seem to work on 1.8 and returns an error in chronograf also , ive tried this against a few different 1.8 instances so if its a config issue its one ive made a few times!:

![image](https://user-images.githubusercontent.com/62287745/86466155-0b5b5600-bd2b-11ea-8326-4146513323a8.png)

**Environment**:
- Grafana version: 7.1 beta 2
- Data source type & version: Influxd/Flux Builtin
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows 10/Chrome
- Grafana plugins: N/a
- Others:

**Comment by FortDigital** [comment] 2020-07-03 11:57
Screenshot of explore query still working despite errors setting up datasource:
![image](https://user-images.githubusercontent.com/62287745/86466807-3abe9280-bd2c-11ea-8fae-4f1b5ebaef7e.png)

Worth noting also that in 1.8 the v. Macro's don't exist in Chronograf so its not quiet as easy and copy and pasting your query

**Comment by cdfuller** [comment] 2020-07-17 19:07
This was fixed in InfluxDB released on July 14th.
https://docs.influxdata.com/influxdb/v1.8/about_the_project/releasenotes-changelog/#v1-8-1-2020-07-14

**Comment by ryantxu** [comment] 2020-07-28 00:02
I think this is a duplicate of #26397 -- at least it will be improved with that

**Closed by ryantxu** 2020-07-28 00:02 UTC
Labels: datasource/InfluxDB, type/feature-request
