### ISSUE TITLE
Add tag values to the opentsdb response for alert messages.

### ISSUE THREAD

**Issue by xy-man** [grafana/grafana#47092] opened 2022-03-31 05:38 UTC
**What happened**:

I usually construct a panel in a way that separates each metric into several tags using one metric_name.
For example, Such like bellow.
![image](https://user-images.githubusercontent.com/36870081/160982866-5006b45e-2554-41fd-ae51-35e5cb1b618c.png)

With this, I created alert(on ngalert) and test it.
And I found that tag values are not included into alert messages.
So I had to see the panel to check which metric had a problem.

alert messages 
```
title: [FIRING:1]
message: **Firing**

Value: [ metric='xxx.for-oncall' labels={} value=46 ]
```

---

**What you expected to happen**:

I thought, if tag values are included in alert message.
I fixed codes ( only 8 lines over 3 files with test case ), and I could get expected result. 😄 

Changed codes are bellow, 
![image](https://user-images.githubusercontent.com/36870081/160982902-d2290570-5dfd-4bc2-88c3-467b5e0b039b.png)

And bellow is alert message i received after change codes.
```
title: [FIRING:1]
message: **Firing**

Value: [ metric='xxx.for-oncall' labels={host=host1, location=loc1, Type=type1, streamId=sid1, svc_type=real}} value=46 ]
```
I think this is not a bug. 
I don't know if it was intentional, but is there a problem if I change it like this? 😅 

---

**How to reproduce it (as minimally and precisely as possible)**:

Any alerts that included a metric with multiple tags.

**Anything else we need to know?**:

nothing..

----

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: opentsdb
- OS Grafana is installed on: Centos7
- User OS & Browser: windows10
- Grafana plugins: none
- Others: none

**Comment by xy-man** [comment] 2022-04-01 03:07
add code changes (patch)
[add-tag-values-into-opentsdb-response-patch.zip](https://github.com/grafana/grafana/files/8394388/add-tag-values-into-opentsdb-response-patch.zip)

**Comment by xy-man** [comment] 2022-04-01 04:15
> additional informations

I tested this changes with grafana-7.5.6 also. 
And this change didn't cause any other errors with previous alerter (not ngalert).
The error didn't occur even if the reference of tag does not exist in another alerter ( eg. email, webook, and so on).

**Comment by aocenas** [comment] 2022-04-04 08:16
@peterholmberg have you seen a similar issue for some other data source?

**Comment by Jack1007** [comment] 2022-04-19 04:29
I meet this problem too. Hope to be fixed as soon as possible.

**Comment by xy-man** [comment] 2022-04-27 02:19
@aocenas 
Hi. 
Is there any discussion with this issue?

**Comment by aocenas** [comment] 2022-04-28 15:48
Seems like more of an alerting issue not specific to OpenTSDB, moving to @grafana/alerting-squad if that is wrong let me know.

**Comment by joeblubaugh** [comment] 2022-05-04 05:14
@aocenas I don't think this is a general alerting issue. Adding tags to the dataframe is the expected behavior for all data sources. This proposed change doesn't touch any of the alerting code because there missing information here comes from the datasource and not from anything about the alerting code.

As an example, the influxdb and graphite tsdbs do the same thing:
https://github.com/grafana/grafana/blob/66d7105b34e9f3c7d4cf5e432e51d58561252996/pkg/tsdb/influxdb/response_parser.go#L119
https://github.com/grafana/grafana/blob/66d7105b34e9f3c7d4cf5e432e51d58561252996/pkg/tsdb/graphite/graphite.go#L245

@xy-man please create a PR, and we'll make sure to get it reviewed.

**Comment by joeblubaugh** [comment] 2022-05-04 05:18
I should add: the reason this issue with the datasource became apparent is that unified alerting will generate an alert message per unique tag combination in the alerting query. Legacy alerting doesn't understand tags in the same way.

**Comment by xy-man** [comment] 2022-05-04 05:34
@joeblubaugh 

Thank you for your review. I checked your comments.
I will create a PR soon.

**Closed** 2022-06-20 02:12 UTC
Labels: datasource/OpenTSDB, area/backend/config, area/backend, needs investigation, area/datasource/backend
