### ISSUE TITLE
`see source` button returns 404 when using Mimir as Datasource

### ISSUE THREAD

**Issue by gespi1** [grafana/grafana#82117] opened 2024-02-07 18:45 UTC
### What happened?

When going to grafana ui > alerting > groups > * select a group * > click `see source` it returns a 404. 

This is because Mimir does not have a `/graph` endpoint. 
![Screenshot 2024-02-07 at 10 36 48 AM](https://github.com/grafana/grafana/assets/21318637/91c5b137-7640-430e-a529-018047c55dab)
![Screenshot 2024-02-07 at 1 39 54 PM](https://github.com/grafana/grafana/assets/21318637/0de0ba71-6583-4f7c-a2f9-598165bc2e59)

### What did you expect to happen?

I expect it to redirect to an explorer to view the respective query results of the selected group chosen. 

### Did this work before?

only if you have an actual prometheus instances as a datasource. Prometheus has a `/graph` endpoint

### How do we reproduce it?

1. Create a Prometheus Datasource thats url is configured to point to Mimir
2. Have an Alert thats attached to a Group trigger
3. Go to  grafana ui > alerting > groups > * select a group * >  and click `see source`
4. and 404

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: Grafana v10.1.1 (0cfa76b22d)
OS: Mac OS 14.1.1
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus Datasources pointing at Mimir

**Comment by gillesdemey** [comment] 2024-03-21 19:52
I can't seem to reproduce this one using the latest version of Mimir and Grafana 10.1.1 – can you try to reproduce on your end? What version of Mimir are you using?

**Comment by gespi1** [comment] 2024-03-25 15:09
Still seeing the error on

- Grafana v10.1.1 (0cfa76b22d)
- Mimir 2.11.0  
![graf-404](https://github.com/grafana/grafana/assets/21318637/e2133d5d-fd1e-4750-966e-be39ab6d3828)

**Comment by gillesdemey** [comment] 2024-03-26 17:12
This is probably https://github.com/grafana/mimir/issues/5006 which happens if Mimir is also pointing to an external Alertmanager.

**Comment by gillesdemey** [comment] 2024-03-27 15:39
I'm going to close this one on the Grafana side and defer this to the Mimir team – the "see source" button for Mimir / Prometheus alerts is just navigating to the `generatorURL` of the alert (which is configured outside of Grafana) so it's working as intended in the UI part of the equation.

**Closed by gillesdemey** 2024-03-27 15:39 UTC
Labels: area/alerting, area/frontend

**Comment by gespi1** [comment] 2024-04-11 16:59
How are you deferring this to the Mimir team, with another github issue? If so do you mind linking it here as well

**Comment by gillesdemey** [comment] 2024-04-11 18:23
That would be https://github.com/grafana/mimir/issues/5006 linked above :)
