### ISSUE TITLE
InfluxDBv1 Datasource Provisioning via File does not set the database value for v9.4.x

### ISSUE THREAD

**Issue by shantanoo-desai** [grafana/grafana#66316] opened 2023-04-11 18:45 UTC
**What happened**:
When trying to provision datasources especially `InfluxDBv1` with a predefined `datasources.yml` file and mounting it via Docker into a Grafana OSS 9.4.7 container the `database` parameter is not set.

[Kooha-2023-04-11-20-36-20.webm](https://user-images.githubusercontent.com/12070966/231259336-56238a61-65dc-4d40-ba5b-7d5bee956d7a.webm)

### Files
`datasources.yml`

```yaml
apiVersion: 1

datasources:
  - name: Komponist-InfluxDBv1
    type: influxdb
    access: proxy
    database: komponistdb
    user: rw_user
    url: http://komponist_influxdbv1:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: test
    editable: true

  - name: Komponist-InfluxDBv2
    type: influxdb
    access: proxy
    url: http://komponist_influxdbv2:8087
    jsonData:
      version: Flux
      organization: komponistorg
      defaultBucket: komponistdb
      tlsSkipVerify: true
    secureJsonData:
      token: testToken
    editable: true

````

**What you expected to happen**:

The Database value should be set for the `InfluxDBv1`

**How to reproduce it (as minimally and precisely as possible)**:

This [Repository](https://github.com/shantanoo-desai/grafana-datasources-bug) provides a basic reproducible example of how to reproduce this bug.

Requirements: Docker v23.0.1 and Docker Compose Version: 2.17.2

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Data source type & version: InfluxDBv1
- OS Grafana is installed on: Linux
- User OS & Browser: Mozilla Firefox
- Grafana plugins: N/A
- Others:

**Comment by shantanoo-desai** [comment] 2023-04-12 08:11
Upon further investigation this problem exists only for `9.4.x`

**Comment by tonypowa** [comment] 2023-04-13 10:37
hi @shantanoo-desai 
first, thank you so much for providing such a great step-by-step troubleshooting guide. Kudos for creating a repo for that too!

I followed it and reproduced as expected in 9.4.7

While this is investigated by our engineers, as a workaround, (in case you can't update the database:  via the UI), I'd suggest to use the [API](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#update-an-existing-data-source) to update the datasource details
It has worked for me:

```
curl --location --request PUT 'localhost:3000/api/datasources/uid/{UID}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxxxxx' \
--data ' {
    "id": 1,
    "uid": "P3CF01143EA0AB962",
    "orgId": 1,
    "name": "Komponist-InfluxDBv1",
    "type": "influxdb",
    "typeName": "InfluxDB",
    "typeLogoUrl": "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg",
    "access": "proxy",
    "url": "http://komponist_influxdbv1:8086",
    "user": "rw_user",
    "database": "aManHasNameNow",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {
      "httpMode": "GET"
    },
    "readOnly": false
  }'
```

![image](https://user-images.githubusercontent.com/45235678/231732949-237f95eb-6145-47a8-9425-3b109f64578f.png)

**Comment by shantanoo-desai** [comment] 2023-04-13 10:41
@tonypowa thank you for the reply. This is just me power-using Grafana OSS and finding out certain problems. I can confirm that this error persists for most of `9.4.x` but didn't persist in `v9.3.x`

**Comment by tonypowa** [comment] 2023-04-13 10:42
note for the metrics squad: related issue here:  https://github.com/grafana/grafana/issues/64273 (currently with DataViz squad)
i don't think this concerns to just one squad @grafana/dataviz-squad   @grafana/observability-metrics  but it's a general database provisioning issue

**Comment by zoltanbedi** [comment] 2023-04-14 11:25
Duplicate of https://github.com/grafana/grafana/issues/64795

**Closed by zoltanbedi** 2023-04-14 11:25 UTC
Labels: type/bug, datasource/InfluxDB
