### ISSUE TITLE
Question: Will the ARM package of Grafana be available in the apt repository?

### ISSUE THREAD

**Issue by SeppPenner** [grafana/grafana#13788] opened 2018-10-22 16:23 UTC
Is it planned to add the ARM image of Grafana to the repository under https://packagecloud.io/grafana/stable?

**Comment by marefr** [comment] 2018-10-22 16:27
Duplicate of #12761

**Closed by marefr** 2018-10-22 16:27 UTC

**Comment by SeppPenner** [comment] 2018-10-22 17:01
Hi @marefr. Sorry, I didn't see that one.
