### ISSUE TITLE
Plugins: Older version of plugin installed due to order of GF_INSTALL_PLUGINS

### ISSUE THREAD

**Issue by townsendduong** [grafana/grafana#78713] opened 2023-11-28 02:49 UTC
### What happened?

An older version of the `redis-datasource` plugin was installed when a newer version was available and compatible with the Grafana verson and other installed plugins. This resulted in `redis-app` plugin version `2.2.1` and `redis-datasource` plugin version `2.1.1` being installed, and a message in the Grafana UI saying an update was available for the `redis-datasource` plugin.

In the logs, I saw these messages:

```
✔ Downloaded and extracted redis-datasource v2.2.0 zip successfully to /var/lib/grafana/plugins/redis-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded and extracted redis-app v2.2.1 zip successfully to /var/lib/grafana/plugins/redis-app

Fetching redis-datasource dependency...

✔ Downloaded and extracted redis-datasource v2.1.1 zip successfully to /var/lib/grafana/plugins/redis-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
```

From those logs, it seems that the current version of `redis-datasource` was first downloaded and installed, and then the minimum compatible version was downloaded and installed over that when the dependencies of `redis-app` were processed.

I'm using the kube-prometheus-stack Helm chart, which has the Grafana Helm chart as a dependency. The `GF_INSTALL_PLUGINS` environment variable is being populated by the list under the `plugins` value passed to the Helm chart. I had the `redis-datasource` before `redis-app`. The `redis-app` plugin version `2.2.1` lists a dependency on the `redis-datasource` plugin `^2.1.1`:

```
    "plugins": [
      {
        "id": "redis-datasource",
        "name": "Redis Data Source",
        "type": "datasource",
        "version": "^2.1.1"
      }
    ]
```

After seeing the log messages, I changed the order of the plugins, which resulted in the latest version of the `redis-datasource` plugin being installed. These are the log messages after this change:

```
✔ Downloaded and extracted redis-app v2.2.1 zip successfully to /var/lib/grafana/plugins/redis-app

Fetching redis-datasource dependency...

✔ Downloaded and extracted redis-datasource v2.1.1 zip successfully to /var/lib/grafana/plugins/redis-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded and extracted redis-datasource v2.2.0 zip successfully to /var/lib/grafana/plugins/redis-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
```

The dependency solver only installed the minimum version of `redis-datasource` to satisfy the dependency, but then the current version was downloaded and installed over that.

### What did you expect to happen?

The `redis-app` plugin version `2.2.1` and the `redis-datasource` plugin version `2.2.0` should both have been installed. Since `redis-datasource` version `2.2.0` is compatible with `redis-app` version `2.2.1`, I would expect the order of the plugins not to matter. If a compatible version of the dependency is already installed, I would not expect an older version to be installed over it.

I would not expect this behavior to be limited to these specific plugins.

### Did this work before?

Don't know. I didn't examine this before.

### How do we reproduce it?

1. Run Grafana with the environment variable `GF_INSTALL_PLUGINS` set to `redis-datasource,redis-app`
2. Check the server logs and the Plugins administration in the Grafana UI
3. Repeat the above steps with the environment variable `GF_INSTALL_PLUGINS` set to `redis-app,redis-datasource`

### Environment (with versions)?

Grafana: 10.1.5 (grafana/grafana-enterprise image)
OS:
Browser:

### Grafana platform?

Kubernetes

**Comment by townsendduong** [comment] 2023-11-28 03:15
Edited the description to add that I'm running the grafana/grafana-enterprise container image. I don't know if that makes a difference because I did not test with the normal image.

**Comment by usmangt** [comment] 2023-12-12 10:36
Hi @townsendduong,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by marefr** [comment] 2023-12-14 14:45
This seems to happen because grafana-redis-app are using a plugin dependency version of `^2.1.1` and Grafana doesn't support semver expressions/constraint for plugin dependencies and treats that as just `2.1.1`:
https://github.com/grafana/grafana/blob/d4ee8c7a3247a28deeda748dea97fe7d9949ea12/pkg/plugins/repo/version.go#L100-L102

Going to ask my colleagues for some additional input on this. Sounds like the solution to your problem might be opening a new issue in https://github.com/RedisGrafana/grafana-redis-app and ask them to remove the version constraint which should mean "I'm dependent on the latest version (whatever that is) of said plugin.

**Comment by marefr** [comment] 2023-12-14 14:58
@townsendduong Just got confirmed that we don't support semver expressions/constraint in plugin dependencies. So it could either be empty or a specific version, i.e. `2.1.1`. Please open an issue in https://github.com/RedisGrafana/grafana-redis-app.

@mikhail-vl FYI if you're not aware of this.

Closing this since we're not planning to support semver expressions/constraint in plugin dependencies.

**Closed by marefr** 2023-12-14 14:58 UTC
Labels: area/plugins, triage/needs-confirmation

**Comment by mikhail-vl** [comment] 2023-12-14 15:34
@marefr Redis team took over Reds plugins, I am not involved anymore.

@townsendduong As recommended, please open an issue for the Redis team to follow-up.

**Comment by townsendduong** [comment] 2023-12-14 15:45
@marefr Thanks, I was not aware that Grafana doesn't support semver expressions. This still leaves the problem that the version installed depends on the order of the plugins. If redis-app had a dependency on specific version `2.1.1` of redis-datasource instead of `^2.1.1`, then later installing a different version would result in a conflict. If I had specified a conflicting version like redis-datasource `2.2.0`, then I think there should be an error message. But if I don't constrain the version of `redis-datasource`, I would expect Grafana to use the version that satisfies the dependencies. This may not require solving a graph since the conflict could be detected when installing a plugin that was already loaded.

**Comment by townsendduong** [comment] 2023-12-14 15:53
It seems a similar issue was opened in grafana-redis-app shortly after I reported this issue here.

**Comment by marefr** [comment] 2023-12-18 13:18
@mikhail-vl I'm very sorry had completely forgot about that. Thanks

**Comment by townsendduong** [comment] 2023-12-18 18:06
Thanks, I understand this plugin dependency management may not be a priority.
