### ISSUE TITLE
AzureAD authentication source removes users from organizations

### ISSUE THREAD

**Issue by Centzilius** [grafana/grafana#23317] opened 2020-04-03 10:47 UTC
**What happened**:
After setting up Grafana with Azure AD as authentication method and configuring app roles I added someone to another organization. After logging out and logging in again that user was no longer in that organization.

**What you expected to happen**:
User to stay in that organization.

**How to reproduce it (as minimally and precisely as possible)**:
* Set Up AzureAD as documented [here](https://grafana.com/docs/grafana/latest/auth/azuread/)
* Create organization
* Let second user log in
* Add yourself and the second user (that is not a grafana admin) to the new organization
* Second user logs out
* Second user logs in
* Notice that he is no longer part of the new organization

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: N/A
- OS Grafana is installed on: Linux (K8S + Docker)
- User OS & Browser: Linux + Firefox
- Grafana plugins: [scalyr](https://github.com/scalyr/scalyr-grafana-datasource-plugin)
- Others:

**Comment by jongyllen** [comment] 2020-04-06 11:28
Hi, thanks for reporting this. It is by design, you can read more in this issue #23204
I am closing this issue as we have a similar one that is older. Will cross reference them as well.

**Closed by jongyllen** 2020-04-06 11:28 UTC
Labels: area/backend/auth/oauth, needs investigation

**Comment by alexanderzobnin** [comment] 2020-04-08 14:10
Ref #22605
