### ISSUE TITLE
[Feature request] Support multiple queries for alerts

### ISSUE THREAD

**Issue by vasil-moneybird** [grafana/grafana#8579] opened 2017-06-09 12:52 UTC
I have been searching in the Grafana community, documentation and the GitHub issues however I wasn't able to find any existing answer to my question, maybe I have overlooked it somewhere, but I am still going to post it as a future request here.

I think it would be really useful if we could use multiple queries for alerts.

Currently the alert conditions panel looks like this:
<img width="622" alt="screen shot 2017-06-09 at 14 50 19" src="https://user-images.githubusercontent.com/22887801/26976179-fbeb9782-4d22-11e7-9a35-5eb2788d3788.png">

It would be really useful if we could use such a query:
`WHEN avg() of query(A, 5m, now) IS ABOVE query(B, 5m now)` or something similar.

My apologies if this already exists but I have not been able to find it.

**Comment by torkelo** [comment] 2017-06-09 13:00
duplicate of https://github.com/grafana/grafana/issues/6593

**Closed by torkelo** 2017-06-09 13:00 UTC
