### ISSUE TITLE
Explore: Infinity datasource not populating URL from Query history

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#89647] opened 2024-06-24 21:38 UTC
When clicking "Run query" in query history, the query editor should populate all fields that were saved. This isn't happening for the Infinity datasource. Since all datasources should work the same way, this could be a more widespread bug - investigate why in this instance the URL field is not being populated.

Note: This might be an issue with the query editor. If so, this issue can be sent to the team responsible for maintaining the Infinity datsource (as of now, this is OSS Big Tent)

Replication Steps:
1. Be sure the infinity datasource is installed
2. Run the default GET JSON 
3. Replace JSON URL with `https://github.com/grafana/grafana/blob/main/latest.json`
4. Run this
5. Pull up query history
6. Find entry with default JSON url from step 2
7. Click run query
8. The results will change, but the URL field will not

**Comment by harisrozajac** [comment] 2024-07-12 17:18
@gelicia I'm not able to reproduce this. In my case the URL field gets populated:


https://github.com/user-attachments/assets/f968e0c0-ab10-4a13-b761-2f96291f92aa

**Comment by harisrozajac** [comment] 2024-07-12 17:21
Maybe try reproducing this on the most recent main. I wonder if this issue was fixed with https://github.com/grafana/grafana/pull/90214

**Comment by harisrozajac** [comment] 2024-07-12 18:51
Closing this as it's not reproducible and it's working as expected

**Closed by harisrozajac** 2024-07-12 18:51 UTC
Labels: type/bug, prio/low, area/explore
