### ISSUE TITLE
I would like to be able to POST a new dashboard while providing the folderUid (seems only the folderId is present in the API)

### ISSUE THREAD

**Issue by JnMik** [grafana/grafana#26678] opened 2020-07-29 17:01 UTC
Hello everyone !

**What would you like to be added**:
Possibility to POST a new dashboard on the API using folderUid.
Seems like only folderId is available right now.

**Why is this needed**:
In infrastructure as code, I keep trace of all my dashboards as json inside the project. I want to hardcode the folderUid name in the json, but I don't know for sure what will be the folders ID. Calling the GET method on folders to get their ID before posting, and replace the folderId in the JSON file at runtime is just painful.

Thanks ! 
If there is already a way to make this happen, i'm all ears !

**Comment by zserge** [comment] 2021-05-17 11:06
Possible duplicate of #12491 and related to PR https://github.com/grafana/grafana/pull/33991

**Closed** 2021-05-26 14:20 UTC
Labels: area/backend/api, area/dashboard, type/feature-request

**Comment by jonathansm1th** [comment] 2021-05-26 20:28
Thanks for creating this issue @JnMik 

Without the dashboard api exposing the folder uid in the response, there also isn't a way to export and migrate both dashboards and their referenced folders to a new Grafana instance via the api.
