### ISSUE TITLE
[Bug] Query builder(UI) generates incorrect WHERE clause for InluxDB integer fields

### ISSUE THREAD

**Issue by the20login** [grafana/grafana#8501] opened 2017-05-31 09:59 UTC
Grafana v4.3.1 (commit: befc15c), InluxDB 1.2.4, both lastest official docker images on linux

When building query with UI
![grafana](https://cloud.githubusercontent.com/assets/3233390/26626380/7f323854-4610-11e7-8545-b1af53f07724.png)
where 'object_id' is integer field, grafana generates this query 
```
SELECT "value" FROM "metric_1" WHERE "object_id" = '1' AND $timeFilter
```
which is incorrect, because InfluxDB process single apostrophe escaping as string values (see https://docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#the-where-clause )

Correct query should be
```
SELECT "value" FROM "metric_1" WHERE "object_id" = 1 AND $timeFilter
```
Query builder should use schema information to correctly determine field types.

**Comment by torkelo** [comment] 2017-05-31 11:42
duplicate of https://github.com/grafana/grafana/issues/5489

**Closed by torkelo** 2017-05-31 11:42 UTC
