### ISSUE TITLE
Azure Monitor Logs: multi resource queries not working as expected

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#69821] opened 2023-06-08 22:16 UTC
### 
# What went wrong?

**What happened**:

  -  When trying to run a query with more than one resource of the same type (Application insights in this case) selected I get the error: 

```
request failed, status: 400 Bad Request, body: {"error":{"message":"The request had some invalid properties","code":"BadArgumentError","correlationId":"8a696e4e-baa6-4f85-b89f-5f581fe823ff","innererror":{"code":"QueryValidationError","message":"The given resource id for microsoft.insights/components is not for a Log Analytics resource"}}}
```
![image](https://github.com/grafana/grafana/assets/20448042/b91dee1b-a37c-4bf8-a141-5018fb1a8f60)

The above error does not get thrown if I query for each resource individually:

![image](https://github.com/grafana/grafana/assets/20448042/5b4591f3-6fcc-4a8f-8627-841b605910a5)

Or when running a query and selecting multiple Log Analytics Workspaces

**What did you expect to happen**:

  - For the query to work for multiple resources the same way it works for a single resource selected. Azure Portal allows querying Logs data for multiple Application Insights resources.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a panel with Azure Monitor data source

**Step 2**:

- Select Logs for the service

**Step 3**:

- Select more than one resource from the resource picker and try to run a query

### 
# What Grafana version are you using?

9.4.12

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

Windows

### User's Browser?

Edge

### Is this a Regression?

None

### Are Datasources involved?

Azure Monitor datasource

**Comment by tonypowa** [comment] 2023-06-09 08:51
hi @jcolladokuri 

thank you for creating this issue

This has been reported already. Please watch this issue instead: 
https://github.com/grafana/grafana/issues/68603

Thank you

/duplicate of #68603

**Comment by jcolladokuri** [comment] 2023-06-09 21:15
Hi @tonypowa, thanks for replying! I believe the issue you shared may not be related, seems like #68603 is related to Azure Monitor Metrics and the issue I found is with Azure Monitor Logs. Could you help verify this please?

**Comment by jcolladokuri** [comment] 2023-06-12 23:00
Hi @aangelisc! Can you please help take a look here? Thanks!

**Comment by avidhanju** [comment] 2023-06-13 17:47
@aangelisc does this information help with cross-resource query for App Insights resources?
https://learn.microsoft.com/en-us/azure/azure-monitor/logs/unify-app-resource-data

**Comment by aangelisc** [comment] 2023-06-19 16:36
Hi @avidhanju, that's similar to what we've implemented already for the traces query editor. 

@jcolladokuri, @avidhanju - the issue here is that the Log Analytics query endpoint does not correctly recognise app insights components for multi-resource queries. 

I've linked a PR that should fix this behaviour in Grafana by using the correct endpoint.

**Closed** 2023-07-04 09:45 UTC
Labels: effort/small, datasource/Azure
