### ISSUE TITLE
Send Alert to Telegram

### ISSUE THREAD

**Issue by omilun** [grafana/grafana#11011] opened 2018-02-24 15:02 UTC
I am using Grafana 5.0.0-beta4 .
I want to send my alerts to Telegram but Grafana can not send any text and photos  when triggers or errors have on my system but only it send a "OK" alert with my text and a image .
I have migrated to v5 to have image on alerts but i think v5 has .
this is my rules:
![](https://preview.ibb.co/mwDnCc/Screenshot_20180224_181143.png)
![](https://image.ibb.co/mCpxdH/Screenshot_20180224_183530.png)
i have no problem on v4 but i want to have image on alert.

**Comment by ryanoolala** [comment] 2018-03-02 07:49
I managed to get he alert with image working when i changed the external_image_storage provider to S3. Probably any external storage will work so you might want to look into using that alternative for now

**Comment by torkelo** [comment] 2018-03-03 11:21
can you check logs?

**Comment by omilun** [comment] 2018-03-04 10:03
Actually I found the problem it happens because Telegram has a tight character limitation on photo messages and the grafana message is too long so it returns an error and the message is discarded.
There is a little [hack](https://www.reddit.com/r/Telegram/comments/4q7zcr/qa_how_can_i_post_longcaptioned_photos_to_my/) to bypass this limitation.

**Comment by xlson** [comment] 2018-03-05 12:38
Duplicate of #10975

**Closed by xlson** 2018-03-05 12:38 UTC

**Comment by omilun** [comment] 2018-03-05 16:18
we can send alert without dashboard links into alert message to solve this problem . 
i can send alert without any junk message like url and alert message .
