### ISSUE TITLE
Unable to get resolved alerts with metrics value?

### ISSUE THREAD

**Issue by AashishChughHome** [grafana/grafana#16191] opened 2019-03-25 06:10 UTC
Hi Team,

I am getting cpu alerts when cpu usage is greater then 80% with mertrics name,instance_name value, but once it resolved i am getting only ok mail in my mailbox, it is not indicating which instance comes into normal state.

it is getting worst when in 1 hour my 5 instance is in alert state and after that i am getting only ok mail, i am totally confused to relate that mails.

I want then when cpu comes to normal state their should be metric name and value also.

Please find attachment regarding the same.
Their is two attachment in which cpu is high and another in which cpu is normal.

![Capture](https://user-images.githubusercontent.com/29576872/54898478-84e28280-4ef2-11e9-98d6-f5334e8478f3.PNG)

![Capture1](https://user-images.githubusercontent.com/29576872/54898480-857b1900-4ef2-11e9-96d0-9d167d254078.PNG)

**Comment by marefr** [comment] 2019-03-25 08:31
Duplicate of #7980

**Closed by marefr** 2019-03-25 08:31 UTC
