### ISSUE TITLE
Elasticsearch: Index name is lost after upgrading from 7.3.5 to 9.4.1

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#64120] opened 2023-03-03 10:09 UTC
A user upgraded from Grafana 7 to 9.4, and after the upgrade, the index name field on all their Elastic search data sources disappeared. 

We reproduced the issue upgrading from 7.3.5 to 9.4.1. 

Datasource v7.3.5;
`{"id":1,"orgId":1,"name":"Elasticsearch","type":"elasticsearch","typeLogoUrl":"","access":"proxy","url":"http://my-fake-elastic-search:9200","password":"","user":"","database":"[custom-logstash-]YYYY.MM","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":true,"jsonData":{"esVersion":70,"interval":"Monthly","logLevelField":"my_fields_name","logMessageField":"_my_message","maxConcurrentShardRequests":5,"timeField":"@timestamp_log"},"secureJsonFields":{},"version":2,"readOnly":false}` 
![image](https://user-images.githubusercontent.com/49911675/222131894-0e87493d-e305-48c3-931a-c975fbe7ca35.png)

Datasource v9.4.1;
`{"id":1,"uid":"TyGLGJx4z","orgId":1,"name":"Elasticsearch","type":"elasticsearch","typeLogoUrl":"","access":"proxy","url":"http://my-fake-elastic-search:9200","user":"","database":"","basicAuth":false,"basicAuthUser":"","withCredentials":false,"isDefault":true,"jsonData":{"esVersion":70,"interval":"Monthly","logLevelField":"my_field_name","logMessageField":"_my_message","maxConcurrentShardRequests":5,"timeField":"@timestamp_log"},"secureJsonFields":{},"version":1,"readOnly":false,"accessControl":{"alert.instances.external:read":true,"alert.instances.external:write":true,"alert.notifications.external:read":true,"alert.notifications.external:write":true,"alert.rules.external:read":true,"alert.rules.external:write":true,"datasources.caching:read":true,"datasources.caching:write":true,"datasources.id:read":true,"datasources.permissions:read":true,"datasources.permissions:write":true,"datasources:delete":true,"datasources:query":true,"datasources:read":true,"datasources:write":true}}` 
![image](https://user-images.githubusercontent.com/49911675/222131927-9b0a1892-5ee1-434c-b034-69fb8856d779.png)

**The index field isn't dropped when upgrading first to 9.3.2, and then to 9.4.1.** 
I'm guessing there is a migration step that isn't done after 9.4, would it be possible to add it again? 
Or is there a query the client can run on their database to restore the index names in the data sources?

**Comment by gabor** [comment] 2023-03-14 15:36
i was able to reproduce it with grafana docker images (need to make sure the `grafana.db` is kept between the various docker versions):
- start with `7.3.1`, create an elastic datasource, write something in the the `index` field.
- turn it off, start grafana `9.4.1`, the datasource's `index` value is empty

next test:
- start with `7.3.1`, create an elastic datasource, write something in the the `index` field.
- turn it off, start grafana `9.3.2`,the datasource's `index` value is correct 
- turn it off, start grafana `9.4.1`, the datasource's `index` value is correct

it seems if i go from `7.3.1` directly to main-branch-grafana, then it works ok:
- start with `7.3.1`, create an elastic datasource, write something in the the `index` field.
- turn it off, start grafana `main`, the datasource's `index` value is correct

@zoltanbedi sorry, this is a wild guess, might this be caused by the same problem you fixed in https://github.com/grafana/grafana/pull/62790 ?

**Comment by zoltanbedi** [comment] 2023-03-20 11:49
Yes, sorry about that. I've backported the fix to 9.4.x so it will be available in the next public release.

**Closed** 2023-03-20 13:15 UTC
Labels: type/bug, datasource/Elasticsearch

**Comment by mieliespoor** [comment] 2023-03-26 17:39
We upgraded today to the latest version of 9.4.x. With issue closed, it gives the impression that we shouldn't have seen this issue anymore, but we did and had to roll back our deployment of Grafana. Any update on when it will be made available?

**Comment by gabor** [comment] 2023-04-26 12:58
hi @mieliespoor, the releases `9.4.9` and `9.5.1` should contain the fix.
