### ISSUE TITLE
[feature request] "single" hover tooltip should show all items under mouse

### ISSUE THREAD

**Issue by danielmotaleite** [grafana/grafana#12670] opened 2018-07-20 13:43 UTC
I have a graph with many series with requests by "url types" (related to to the backend) and their limits.
Using hover tooltip with all series is mostly useless as they are too many, so i switched to single to do the mouse over and read the value for what i need. It mostly works, except now when multiple series have the same value, it will only show the last one draw, all other behind are unknown to me.

So "single" hover tooltip should not only show the last draw series value, but also all the series that are also on the same place, that have the same value

**Comment by marefr** [comment] 2018-07-23 12:22
Duplicate of #6946

**Closed by marefr** 2018-07-23 12:22 UTC
