### ISSUE TITLE
Dashboard Graph & TimeSeries Null value config is broken

### ISSUE THREAD

**Issue by Jojoooo1** [grafana/grafana#56567] opened 2022-10-07 15:23 UTC
**What happened**: Null value config is not being properly applied.

**What you expected to happen**: Null values should be null

**How to reproduce it (as minimally and precisely as possible)**:
Grafana 9.0.7 Null value = null
![Screenshot from 2022-10-07 12-20-00](https://user-images.githubusercontent.com/17641873/194589724-2be01e35-c8f9-457b-8051-6ee8552bca60.png)

Grafana 9.1.7 Null value = null
![Screenshot from 2022-10-07 12-21-23](https://user-images.githubusercontent.com/17641873/194590032-fd44b295-e079-4e16-87d9-b0f05745bfeb.png)

Which basically false the whole mean/average values. Can be reproduced in Graph and TimeSeries dashboards.

**Comment by gelicia** [comment] 2022-10-07 15:43
Closed as duplicate of #54230

**Closed by gelicia** 2022-10-07 15:43 UTC
