### ISSUE TITLE
Grafana Alerts Erroring out while using Thanos API as the Data Source

### ISSUE THREAD

**Issue by Ganga-Ops** [grafana/grafana#33499] opened 2021-04-28 18:53 UTC
**What happened**:
Trying to setup alerts for Dashboards created with Prometheus - Thanos API as the Datasource ( used Custom Hearders in API) 
Getting the below error while testing the alerts 

{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "1.227ms",
  "error": "readObjectStart: expect { or n, but found B, error found in #1 byte of ...|Bad Request|..., bigger context ...|Bad Request. The request or configuration is malfor|...: ",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1619635462311,
        "queries": [
          {
            "refId": "A",
            "model": {
              "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^rt.*\"}[2m]))",
              "hide": false,
              "interval": "",
              "legendFormat": "",
              "refId": "B"
            },
            "datasource": {
              "id": 13,
              "name": "OCClusterPrometheus-Thanos"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1619635762311
      }
    }
  ]
}

**What you expected to happen**:

Alerts should trigger properly 

**How to reproduce it (as minimally and precisely as possible)**:

Configure Thanos API as datasource

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.4.2.
- Data source type & version: Thanos API

**Comment by Ganga-Ops** [comment] 2021-04-29 20:02
Accidently Closed it. Reopening

**Comment by Ganga-Ops** [comment] 2021-05-03 13:21
Any updates on this issue ?

**Comment by ctrought** [comment] 2021-05-14 21:29
We're experiencing the same issue with grafana alerts and thanos as a datasource with custom headers and query parameters. Link for reference on setup.

https://www.openshift.com/blog/thanos-querier-versus-thanos-querier

**Comment by ctrought** [comment] 2021-05-20 19:09
> @ctrought we are experiencing issues getting 8.0 working in OpenShift. Have you been able to test that 8.0 actually resolves the issue?

Not for alerting unfortunately. Although we can get thanos connected as a datasource and all dashboards working properly, the alerting functionality is not working. The update with #32440 appeared to get us past the initial error related to the custom parameters not being included, but now we've got a mysterious 502 bad gateway for our alerts.

**Comment by Ganga-Ops** [comment] 2021-05-20 19:16
We are getting this error in Alerts while using Thanos datasource in 8.0

t=2021-05-20T00:09:49+0000 lvl=dbug msg="Sending query" logger=tsdb.prometheus start=2021-05-20T00:04:49+0000 end=2021-05-20T00:09:49+0000 step=10s query=sum(pod:container_cpu_usage:sum)
t=2021-05-20T00:09:49+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=0 name="Pods CPU usage for alert" error="server error: 502: " changing state to=alerting

**Comment by douglasawh** [comment] 2021-05-24 13:35
@mckn this was marked as "needs investigation". Is there any additional data we could provide?

**Comment by douglasawh** [comment] 2021-05-26 19:24
@Ganga-Ops I see @ctrought mentions this was in OpenShift. Is this the same for you? I have been able to confirm that Grafana 8 does resolve the issue. The 502 is either:
A) A thanos-specific bug
B) A networking issue.

The original issue is NOT thanos-specific, as can be seen at https://github.com/grafana/grafana/issues/29468. Thanos introduces additional complexity when compared to the prom-label-proxy, but ultimately, that's the piece of thanos that causes the "The request or configuration is malfor" error.

I'm not sure if there's anything more for the Grafana community to do, but I do know that one of the Thanos maintainers is involved in the Grafana issues, so perhaps he will see this and be able to point you in the right direction.

**Comment by Ganga-Ops** [comment] 2021-05-26 19:29
@douglasawh . Yes . I am also facing the issue in Openshift  only when we configure Thanos as the datasource

**Comment by ctrought** [comment] 2021-05-26 23:53
> @Ganga-Ops I see @ctrought mentions this was in OpenShift. Is this the same for you? I have been able to confirm that Grafana 8 does resolve the issue. The 502 is either:
> A) A thanos-specific bug
> B) A networking issue.
> 
> The original issue is NOT thanos-specific, as can be seen at #29468. Thanos introduces additional complexity when compared to the prom-label-proxy, but ultimately, that's the piece of thanos that causes the "The request or configuration is malfor" error.
> 
> I'm not sure if there's anything more for the Grafana community to do, but I do know that one of the Thanos maintainers is involved in the Grafana issues, so perhaps he will see this and be able to point you in the right direction.

In our case, thanos as a datasource works fine in OCP for all dashboards. All metrics are loaded and displayed correctly. This would lead me to believe the issue is in with grafana (alerting) as all metrics are being pulled in and displayed. However I don't know much about the inner workings of the grafana alerting and how that differs from the way grafana pull the metrics in for the dashboards.

**Comment by douglasawh** [comment] 2021-06-11 18:23
@Ganga-Ops it looks like you might need to create a new one of these. It looks like it got moved to done: https://github.com/grafana/grafana/projects/15#card-60085620 -- As far as I can tell, Grafana has no automated way to get these back on their board once it is closed. 18 days ago I asked @mckn if there was any additional info they needed and I haven't heard back, presumably because they work from the board. Have you attempted to contact the team via IRC or any other method?

**Comment by mckn** [comment] 2021-06-14 12:18
Ah, thanks for pinging me @douglasawh. Looks like this got automatically moved to done because @Ganga-Ops closed it. I will move it to the inbox again so the backend squad can have a look at it.

**Comment by marefr** [comment] 2021-06-14 21:52
So sounds like there might not be anything more we can do from Grafana perspective?

Please include details of the errors you get on Grafana v8 and indicate exakt version you're using. Can you include details/screenshot (with sensitive information replaced) of your configured prometheus/thanos data source in Grafana?

**Comment by douglasawh** [comment] 2021-06-15 14:11
@jeffbmartinez I think the question is whether https://github.com/grafana/grafana/pull/32440 is properly implemented and then there's the separate question as to whether custom query params are properly implemented in Thanos (and more specifically, OpenShift's implementation of Thanos).

Perhaps @povilasv could provide some insight on what might be going on here.

I will work on getting the requested data.

**Comment by ctrought** [comment] 2021-06-15 15:15
Thanks for reopening! I'm taking a complete guess, but in OpenShift their thanos request flow looks like this

1. Thanos Tenancy (RBAC on custom query namespace param)
2. Prom Label Proxy ([Forked](https://github.com/openshift/prom-label-proxy))
3. Thanos Querier

The prom label proxy is a forked version and runs behind community. From what I could see it does not yet include support for POST requests like the community version which was added somewhat recently. Does the Grafana alerting issue requests differently than the Datasource (ie. is it hard coded to do POSTs) or does it respect the Datasource settings? Tried to turn on debug but not much info was given other than the general error. The error seen when testing alerts is 502 bad gateway which at first sounds like network, but Datasource is working when using HTTP method GET, however if the Datasource is flipped to POST then it too will throw a 502. 

So I know originally Grafana did not use all of the configured Datasource settings for the alerting, which is why the fix for custom query params was added. Based on this I am wondering if it really uses all of the configured Datasource settings or some are still being ignored (like HTTP method)?

**Comment by marefr** [comment] 2021-06-15 16:25
> The error seen when testing alerts is 502 bad gateway which at first sounds like network, but Datasource is working when using HTTP method GET, however if the Datasource is flipped to POST then it too will throw a 502.

Grafana Prometheus backend data source uses github.com/prometheus/client_golang@v1.10.0 and calls `client.QueryRange`: 
https://github.com/grafana/grafana/blob/f7ed35336d13f4b0484e092451672ce54e693a89/pkg/tsdb/prometheus/prometheus.go#L89

[github.com/prometheus/client_golang/api/prometheus/v1/api.go](https://github.com/prometheus/client_golang/blob/v1.10.0/api/prometheus/v1/api.go) holds the ` QueryRange` implementation and calls [DoGetFallback](https://github.com/prometheus/client_golang/blob/efe7aa73021f40ba96d167c144941fa5fb7f43e2/api/prometheus/v1/api.go#L1045) method. The comment for this method clearly states 

> DoGetFallback will attempt to do the request as-is, and on a 405 or 501 it will fallback to a GET request.

So maybe the Prom Label Proxy returns the wrong status code?

**Comment by ctml91** [comment] 2021-06-16 04:39
> Grafana Prometheus backend data source uses github.com/prometheus/client_golang@v1.10.0 and calls `client.QueryRange`:

It's an interesting theory and would make sense. The data source is working outside of alerting for all dashboards, do these implement the same methods?

**Comment by ctrought** [comment] 2021-06-16 04:41
> Grafana Prometheus backend data source uses github.com/prometheus/client_golang@v1.10.0 and calls `client.QueryRange`:

It's an interesting theory and would make sense. The data source is working outside of alerting for all dashboards though, do these implement the same methods?

**Comment by marefr** [comment] 2021-06-16 10:01
Outside alerting the requests goes through the Grafana data source proxy and the client-side/UI would make either a GET or POST request to the Grafana data source proxy depending on the setting configured for the Prometheus data source.

**Comment by marefr** [comment] 2021-06-16 11:14
I'm closing this since it seems Grafana cannot do any more in this regard.

**Closed by marefr** 2021-06-16 11:14 UTC
Labels: area/alerting, area/backend, needs investigation

**Comment by m-yosefpor** [comment] 2022-02-26 15:36
We also have the same issue. Has anyone figured out a workaround?
