### ISSUE TITLE
Annotations : allow regions events from external datasource

### ISSUE THREAD

**Issue by finkr** [grafana/grafana#13759] opened 2018-10-19 13:24 UTC
This is a feature request for the annotations.

It would be nice to be able to query no just events (annotation) from external datasource*, but also _regions events..._ something similar to the one in Native annotations : ([regions-events](http://docs.grafana.org/reference/annotations/#adding-regions-events))

*) like postgreSQL, MySQL/MariaDB, and others

**Comment by marefr** [comment] 2018-10-19 13:50
Duplicate of #10589

**Closed** 2018-10-19 13:50 UTC
