### ISSUE TITLE
Allow changing threshold base color when using Config from Query Results

### ISSUE THREAD

**Issue by chazapp** [grafana/grafana#91243] opened 2024-07-31 08:59 UTC
**Why is this needed**:  
  
I am building a Service Level Objective visualization using standardized metrics via recording rules.
I would like to display using thresholds the points where the Service Level Indicator is above the Service Level Objective, both values provided via Prometheus metrics.  

In Grafana 11  a feature allowing changing the color of a threshold configured via `Config from Query Results` was added. Unfortunately, we cannot update the base color which is set to green. [Citing the docs](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-thresholds/#threshold-value):  

> The Base value represents minus infinity. By default, it’s set to the color green, which is generally the “good” color.

**What would you like to be added**:  

In my case, a value under the SLO is a bad event. I'd like to be able to set the base color to red, when using `Config from Query Results`. Example screenshot:

![image](https://github.com/user-attachments/assets/f476b48c-c248-49ea-96a4-bd5851a27057)
  
In this example, the SLO is set to 99.9%. I would like to be able to set the green area of the panel to red. I tried changing the base value using a field override, but it also overrides the threshold i'm trying to set from query result.

**Who is this feature for?**

Anyone building Grafana panels who needs flexibility when using threshold values.

**Comment by gelicia** [comment] 2024-11-19 19:43
Duplicate of https://github.com/grafana/grafana/issues/90201

**Closed by gelicia** 2024-11-19 19:43 UTC
Labels: type/feature-request
