### ISSUE TITLE
InfluxDB Data source: 0 measurements found in new buckets

### ISSUE THREAD

**Issue by schollsi** [grafana/grafana#68290] opened 2023-05-11 09:28 UTC
### 
# What went wrong?

**What happened**:

  I am trying to create a new InfluxDB-Datasource in Grafana in the same way I created other InfluxDB-Datasources in the past. It seems like Grafana is able to connect to the bucket but doesn't find any measurements:

![image](https://github.com/grafana/grafana/assets/92976715/f92d312d-39ba-4b65-bbeb-b86630b0ad92)

However in the bucket there is 1 measurement with values as i can see in the InfluxDB Data Explorer-Interface:

![image](https://github.com/grafana/grafana/assets/92976715/222c1fea-92ee-4ad1-8ba8-9a9f3b6bcdae)

This only happens when trying to connect to newly created buckets in InfluxDB. I can add new Datasources which have older buckets as database and everything works as expected (all measurements are found)

I have allready tried to create a new API Token in InfluxDB with read/write-Permission to the bucket but it still doesn't work.

**What did you expect to happen**:

 Grafana is able to connect to the datasource and is finding all measurements

### 
# How do we reproduce it?

**Step 1**:

- Create a new bucket in InfluxDB

**Step 2**:

- Write Data into the new bucket

**Step 3**:

- Add a new InfluxDB-Datascource in Grafana which has the newly created bucket as database

**Step 4**:

- When clicking "Save & test" I get the message "datasource is working. 0 measurements found" allthough there are measurements in the bucket

### 
# What Grafana version are you using?

v9.5.1

### User's Browser?

Google Chrome Version 112.0.5615.140

### Are Datasources involved?

InfluxDB OSS 2.1.0

**Comment by usmangt** [comment] 2023-05-15 10:41
Hi @schollsi,

Thanks for opening this issue.

I will try to reproduce it by creating a test machine and will get back to you with more information.

**Comment by jishajnutanix** [comment] 2023-05-22 07:42
I'm facing the same issue. The configuration seems to be correct; but the data is not shown in grafana
"InfluxDB Data source: 0 measurements found in new buckets"
Any workaround ?

**Comment by PitbullSwe** [comment] 2023-05-22 09:26
Hi
I have the same problem, the database don´t generate any measurements 
![image](https://github.com/grafana/grafana/assets/105519597/3862b3a1-f398-4168-9dec-cad9e915e8a7)

**Comment by chriwo1983** [comment] 2023-05-29 10:55
same issue as described above here.

**Comment by NiFu90** [comment] 2023-06-05 07:39
same problem here. Any news on this already? Does someone have a solution for it?

**Comment by usmangt** [comment] 2023-06-05 08:24
Hi all,

This issue is now assigned to the team that means its now in the queue for investigation.

**Comment by tonreproc** [comment] 2023-06-07 08:48
Hi all,

Some time ago I updated from version 1.8 to 2.0. My 'old' buckets (made in the v1.8 release) work fine with the InfluxQL query language. These where converted in the update process from v1.8 to v2.0.

Now I have the same issue here with a new bucket. This gives the same error as reported here. When I change the Query Language to Flux then it works fine. The new Grafana 2.0 release does obviously not accept the InfluxQL query language.

So it is strange is that my 'old' buckets (made in the v1.8 release) work fine with the InfluxQL query language.

**Comment by K0nne** [comment] 2023-06-15 09:21
We are facing the same issue. With InfluxDB OSS 2.1.1 and a working datasource.

If we upgrade InfluxDB OSS 2.1.1 to any newer release, Grafana (9.5.x) does not find any measurements after this when using InfluxQL. With Flux measurements are found.

**Comment by itsmylife** [comment] 2023-06-17 12:00
Thanks for waiting for me to come up with some answers. I did check how we do health checks. So far we didn't change the logic. And I cannot reproduce the issue. 

So I will try to reproduce it once more. 
- I will pull InfluxDB OSS 2.1.1
- I will create a user in it. I think @KOnne is right
- Will create two measurements. One has a field. Other has nothing.
- I will connect it with grafana and check. 

In the meantime, I have a couple of questions:
- Is it working with an earlier version of Grafana (let's say v9.4.x)
- After configuring and getting `0 measurements found` could you please run this query `SHOW measurements`? And please share what you get as a result.
- Could you please check if the user has read permission in InfluxDB?

**Comment by K0nne** [comment] 2023-06-17 20:30
They added this security enhancement with influxdb 2.2:

> Add read permissions check for querying data. This prevents authenticated requests using a write-only token from reading data via the InfluxQL /query compatibility API.

If you come from influxdb <2.2, Update to the latest Release and only have write permissions - because it worked before - you cant read anymore. 

What a beautiful breaking change within a minor version 😅

**Comment by tonreproc** [comment] 2023-06-18 21:32
I am out of office for several weeks so I can't really test as asked.

But what is strange to me is the fact that I can read the database if I use Flux to query the database. No permissions changed.

**Comment by schollsi** [comment] 2023-06-19 11:14
> Thanks for waiting for me to come up with some answers. I did check how we do health checks. So far we didn't change the logic. And I cannot reproduce the issue.
> 
> So I will try to reproduce it once more.
> 
> * I will pull InfluxDB OSS 2.1.1
> * I will create a user in it. I think @konne is right
> * Will create two measurements. One has a field. Other has nothing.
> * I will connect it with grafana and check.
> 
> In the meantime, I have a couple of questions:
> 
> * Is it working with an earlier version of Grafana (let's say v9.4.x)
> * After configuring and getting `0 measurements found` could you please run this query `SHOW measurements`? And please share what you get as a result.
> * Could you please check if the user has read permission in InfluxDB?

**Comment by itsmylife** [comment] 2023-06-19 12:38
@schollsi Could you please try with "Format as Table"?

**Comment by schollsi** [comment] 2023-06-19 12:47
@itsmylife Looks the same with "Format as Table":

![image](https://github.com/grafana/grafana/assets/92976715/f8f5ac1e-faaf-4654-8adf-648f24ba28cf)

**Comment by itsmylife** [comment] 2023-06-19 12:50
@schollsi Could you please share your setup configuration of InfluxDB? (docker-compose.yml file if you used docker) and Grafana configuration of Influxdb datasource?
Also if your influxdb datasource is online somewhere is it possible if I can reach it and run some tests? (I'll debug it on my machine)

**Comment by itsmylife** [comment] 2023-06-20 16:07
@schollsi I did my test an here are my results.

Reproduce Steps:

- I installed influxdb 2.1.0 via docker. 
- Have `config` and `data` folders where you run this command.
```
docker rm --force influx210 && docker run -p 3333:8086 \
      --name "influx210" \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -e DOCKER_INFLUXDB_INIT_MODE=setup \
      -e DOCKER_INFLUXDB_INIT_USERNAME=admin \
      -e DOCKER_INFLUXDB_INIT_PASSWORD=admin12345 \
      -e DOCKER_INFLUXDB_INIT_ORG=myorg \
      -e DOCKER_INFLUXDB_INIT_BUCKET=mybucket \
      -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken \
      influxdb:2.1.0-alpine
```
- I logged in with my credentials `admin`/`admin12345` to influxdb UI. 
- I write data via "Left Navigation"->"Buckets"->"mybucket"->"+ Add data"->"Line Protocol"->"Enter Manually"
- Paste `myMeasurement,tag1=value1,tag2=value2 fieldKey="fieldValue" 1687273621000000000` and click "Wirte Data"
- Check the data is there via Data Explorer
- Back to grafana. Configure datasource as usual.
- See you got no measurements back even though you have one.


Fix:
- I installed influxdb 2.1.0 via docker. 
- Have `config` and `data` and **`scripts`** folders where you run this command.
- Have an _**executable**_ `.sh` file under `scripts` folder with content:
```
#!/bin/sh

influx v1 dbrp create --bucket-id "${DOCKER_INFLUXDB_INIT_BUCKET_ID}" --org myorg --db mybucket --rp default --default
```
- More details: https://hub.docker.com/_/influxdb/ -> Custom Initialization Scripts
- Then run following command
```
docker rm --force influx210 && docker run -p 3333:8086 \
      --name "influx210" \
      -v $PWD/data:/var/lib/influxdb2 \
      -v $PWD/config:/etc/influxdb2 \
      -v $PWD/scripts:/docker-entrypoint-initdb.d \
      -e DOCKER_INFLUXDB_INIT_MODE=setup \
      -e DOCKER_INFLUXDB_INIT_USERNAME=admin \
      -e DOCKER_INFLUXDB_INIT_PASSWORD=admin12345 \
      -e DOCKER_INFLUXDB_INIT_ORG=myorg \
      -e DOCKER_INFLUXDB_INIT_BUCKET=mybucket \
      -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken \
      influxdb:2.1.0-alpine
```
- Do the rest as explained in reproduce steps (logging in, writing data, configuring data source)
- Observe you now have the measurements data


I'll be out for 2 weeks. But I think this should help. I'll check this when I'll be back. Hope this will solve your issue.

**Comment by schollsi** [comment] 2023-06-21 06:58
@itsmylife The influx v1 dprp create command solved the issue. Every Bucket I use this command on can now be accessed from Grafana and I see all the measurements.

Thank you for your effort

**Comment by itsmylife** [comment] 2023-06-22 20:33
@schollsi I am happy that the problem is resolved. Feel free to open new issues if you will experience other problems. I am closing this issue. Happy coding!

**Closed by itsmylife** 2023-06-22 20:33 UTC
Labels: datasource/InfluxDB, prio/high, triage/needs-confirmation, effort/medium

**Comment by aay404** [comment] 2023-06-27 06:59
@itsmylife Hi! How do I configure this when I'm using InfluxDB cloud and Grafana cloud as well?

**Comment by itsmylife** [comment] 2023-07-06 18:20
@aay404 with influx cli tool you can use this command. It is going to happen on influxdb cloud. Nothing needs to be done on Grafana side after this.
```
influx v1 dbrp create --db <your-rp-name> --rp 30d --bucket-id <test bucket ID> --host https://<your public endpoint> --token '<your token>'
```

Documentation https://docs.influxdata.com/influxdb/v2.0/query-data/influxql/#map-unmapped-buckets

**Comment by divStar** [comment] 2024-02-17 00:06
`influx v1 dbrp create --bucket-id "${DOCKER_INFLUXDB_INIT_BUCKET_ID}" --org myorg --db mybucket --rp default --default` actually worked for "InfluxDB v2.7.5" (seems to be the latest as of now, 17th of February, 2024).

However: what if one day we cannot use this command anymore? Glad it solved the issue though :).

**Comment by clane2812** [comment] 2024-05-03 12:56
I use the Influx 2.7.5 running in docker and used the above mentioned influx v1 dbrp command till now. When testing around with automatic creation of orgs + buckets via the influx.client-package i discovered that this command is obviously not needed anymore? 

I can setup a new influx-db and query all data from grafana without running the cli-command. Visualization of buckets, created in other organizations works fine too, but you have to create fresh API-tokens for every organization. The initial admin-token only works for the initial organization and it´s buckets. 

see #83030
