### ISSUE TITLE
query editor missing

### ISSUE THREAD

**Issue by Becker884** [grafana/grafana#62414] opened 2023-01-28 11:35 UTC
Yesterday I updated to 9.3.6 and now the query editor is missing:

![grafik](https://user-images.githubusercontent.com/81651521/215264283-9c4013a0-87d6-4e50-aa89-0d4c8a3650a0.png)

any idea how to get it back ?

**Comment by zuchka** [comment] 2023-01-28 19:52
what happens if you expand queries A, B, or C? same thing?

**Comment by caunus** [comment] 2023-01-29 10:51
Same here. As well latest version, on a self hostet Ubuntu instance . Not possible to edit exiting queries, but possible to create new on. No difference if pane is close or open. Grafana is connect to an local InfluxDB server.

**Comment by tonypowa** [comment] 2023-01-30 09:23
marking it as a bug and forwarding it to the dashboard squad since more users have reported this issue

**Comment by axelavargas** [comment] 2023-01-30 10:05
Hey @Becker884  👋🏾 , thanks a lot for reporting this issue, I am closing this as a duplicate of https://github.com/grafana/grafana/issues/61710 , the fix is already in place 🥳 PR: https://github.com/grafana/grafana/pull/61927

**Closed** 2023-01-30 10:05 UTC
Labels: type/bug, datasource/InfluxDB, area/query-editor

**Comment by Becker884** [comment] 2023-02-28 21:40
Today I got 9.4.1 and there is nox fix
