### ISSUE TITLE
Wrong graph data displayed when sum function used within metrics query

### ISSUE THREAD

**Issue by evgenyf** [grafana/grafana#12022] opened 2018-05-21 15:39 UTC
I've tried to use following grafana versions: 2.6, 3.0.4, 3.1.1, 5.1.1, 5.1.2
OS: Ubuntu
Datasource: InfluxDb

I imported attached json file that contains dashboard with one graph.
Data that displayed on this single graph displayed in wrong way: sum is not calculated (displayed as mean) and second WHERE statement is not taking into account.

[dashboard_one_element.zip](https://github.com/grafana/grafana/files/2023156/dashboard_one_element.zip)

**Comment by torkelo** [comment] 2018-05-21 16:52
dupe of the same issue you created here https://github.com/grafana/grafana/issues/11895 

the same answer still applies :) 

You cannot modify the query in the json unless you already switched to text edit mode.

**Closed by torkelo** 2018-05-21 16:52 UTC
