### ISSUE TITLE
MySQL: migration to 9.2.0 and later causes panels to be broken - due to messed up rawSQL in json.

### ISSUE THREAD

**Issue by laundmo** [grafana/grafana#59976] opened 2022-12-07 17:46 UTC
**What happened**:

When upgrading Grafana (running in docker) from 8.5.2 to 9, MySQL panel queries appear to only contain a default query string.
The same panels worked fine before on 8.5.2
It seems to me, that somewhere in migrating from the old Graph panel, `rawSQL` in the panel JSON was falsely set to the default SQL. This was not an issue in any versions up to including 9.1.8, since that's the last version with the old query builder which seemed to ignore the `rawSQL`. 

**What you expected to happen**:

The new query builder to use the "select" array as a source for its migration - not the rawSQL.

**How to reproduce it (as minimally and precisely as possible)**:

I don't have a full reproduction, as we're unable to reproduce the original Graph -> Timeseries migration issue.
Attached is the unedited panel JSON of one such panel, where rawSQL is set to the default query.

<details>
<summary>Panel JSON</summary>

```json
{
  "id": 8,
  "gridPos": {
    "h": 8,
    "w": 12,
    "x": 0,
    "y": 8
  },
  "type": "timeseries",
  "title": "BB4 Übersicht",
  "datasource": {
    "type": "mysql",
    "uid": "000000002"
  },
  "pluginVersion": "8.4.4",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": true,
        "showPoints": "always",
        "pointSize": 3,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "Abstich (m)",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "area"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "rgba(255, 255, 255, 0.2)",
            "value": null
          },
          {
            "color": "#5ed851",
            "value": -132
          },
          {
            "color": "transparent",
            "value": -126
          }
        ]
      },
      "decimals": 1,
      "links": [],
      "max": -110,
      "min": -134,
      "unit": "lengthm"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "BB4_Hz"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-green",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "BB4_Hz"
        },
        "properties": [
          {
            "id": "unit",
            "value": "hertz"
          },
          {
            "id": "min",
            "value": 0
          },
          {
            "id": "max",
            "value": 60
          },
          {
            "id": "custom.axisLabel",
            "value": "Frequenz (Hz)"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "BB4_Abst"
        },
        "properties": [
          {
            "id": "custom.transform",
            "value": "negative-Y"
          },
          {
            "id": "decimals",
            "value": 2
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": [
        "last"
      ]
    }
  },
  "targets": [
    {
      "format": "time_series",
      "group": [
        {
          "params": [
            "$__interval",
            "none"
          ],
          "type": "time"
        }
      ],
      "metricColumn": "none",
      "rawQuery": false,
      "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
      "refId": "A",
      "select": [
        [
          {
            "params": [
              "BB4_AbstichGOK"
            ],
            "type": "column"
          },
          {
            "params": [
              "avg"
            ],
            "type": "aggregate"
          },
          {
            "params": [
              "BB4_Abst"
            ],
            "type": "alias"
          }
        ],
        [
          {
            "params": [
              "BB4_Hz"
            ],
            "type": "column"
          },
          {
            "params": [
              "avg"
            ],
            "type": "aggregate"
          },
          {
            "params": [
              "BB4_Hz"
            ],
            "type": "alias"
          }
        ]
      ],
      "table": "qryICAlleWerte",
      "timeColumn": "reading_time",
      "timeColumnType": "datetime",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    }
  ]
}
```

</details>

To reproduce the issue using this panel json:
- install/setup grafana 9.1.8
- adding a dummy mysql datasource might be required to allow to panel to be saved
- add a panel, paste this panel json and save dashboard. errors can be ignored as this issue does not require data.
- migrate to grafana 9.2.0
- observe how the panel defaults to the raw sql string editor and shows the default string, losing the previously working query builder config completely.

**Anything else we need to know?**:

The faulty rawSQL string did not seem to cause any issues in the versions before 9.1.9. All panels worked and showed up without issue.
We have many panels and dashboards where this is the case. Any assistance in migrating them without having to recreate them will be greatly appreciated.

**Environment**:
- Grafana version: 8.5.2, 9.1.8, 9.2.0
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu 21.10 using Docker
- User OS & Browser: Windows 10 + Firefox
- Grafana plugins: None

**Comment by joshhunt** [comment] 2022-12-12 12:01
This shouldn't have anything to do with Graph/Time Series visualisation - Graph to Time Series _should_ be migrated independently of any changes to data sources. I'll try and reproduce and see what's going on :)

**Comment by laundmo** [comment] 2022-12-12 12:30
okay, it was the only plausible explanation i have.

the core issue us twofold:
- somehow the rawSQL got messed up and contains a default sql
- the migration to the new query builder uses rawSQL instead of the json data

is there a way i could bulk update the rawSQL to match the actual query?

**Comment by laundmo** [comment] 2022-12-12 15:24
i also haven't managed to repero the rawSQL becoming default with any combination of grafana 7, 8 and 9 and graph panel migrations which i tried, and although the instance has bee around for longer, the pabels where the rawSQL is default were mostly originally created in grafana 7

**Comment by zoltanbedi** [comment] 2022-12-13 11:27
Hey @laundmo,

Thanks for creating this issue. I can reproduce the problem you are facing with the panel you attached. The thing is that we migrated the sql datasources in 9.1 from angular to react. With this migration we only migrated the rawSQL field as the querybuilders are not compatible with each other. The problem you are facing should not happen though because when you change the query in the visual query builder the rawSQL field should also update. I suggest you try and change something in your old visual query builder so it will update the rawSQL field properly. With that said I'm going to close this issue as it looks like a problem with your panel for some reason. I'll reopen it if more people are going to face this issue.

**Closed by zoltanbedi** 2022-12-13 11:27 UTC
Labels: area/panel/graph, area/backend/db/migration, triage/needs-confirmation

**Comment by laundmo** [comment] 2022-12-13 18:58
> With that said I'm going to close this issue as it looks like a problem with your panel for some reason. I'll reopen it if more people are going to face this issue.

The confusing part is that this is a issue with the majority of our panels, and sometimes whole dashboards.

**Comment by swebs** [comment] 2023-01-21 00:36
I think we have this same issue (we are using postgres). We have just been copying in the same json over the past several years when we deploy new machines (often with newer grafana versions). It has always worked until now, but it seems to be hung up on this rawSql line with the latest grafana version:
`"rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"`
I've never paid any attention to this line until now. The rest of the json seems to correctly define the query we need. In my mind I was thinking that maybe the variables in the rawSql were supposed to be substituted with the correct strings, but am now realizing that perhaps this is just a bad default string that got there somehow and has previously been ignored.
