### ISSUE TITLE
grafana will login out when refresh the grafana gui which have 15 panels every 10s

### ISSUE THREAD

**Issue by AryTing** [grafana/grafana#17586] opened 2019-06-14 09:33 UTC
Installed the grafana on k8s env. 
I do the PT for the grafana v6.2.2. when open one dashboard which have 15 panels, and each panel has one query.  and set refresh every 10s. After about 30min, it will login out. and 
 logs of grafana pod are as follows :

<img width="440" alt="image" src="https://user-images.githubusercontent.com/51818464/59498578-44c6e680-8ec8-11e9-9cc0-950f2953b8cc.png">

but in the before version 5.2.4, it will work well setting the refresh time to 1s. 

**What you expected to happen**:  I think It should work as well as before version. 

**How to reproduce it (as minimally and precisely as possible)**:  open a dashboard, and it has 15 panels, and set the refresh time to 1s. 

**Anything else we need to know?**:  

**Environment**:
- Grafana version:  v6.2.2
- Data source type & version:  10.3.15-MariaDB MariaDB Server
- OS Grafana is installed on:  k8s
- User OS & Browser:   windows 10, IE edge, chrome
- Grafana plugins: none
- Others:

**Comment by hugohaggmark** [comment] 2019-06-14 12:33
Hi @AryTing and thanks for taking the time to report this. 

Could you supply more information of what kind of database you're using for Grafana. Is it sqlite3 or MySql or Postgres? If it is sqllite have you tried with MySql or Postgres?

**Comment by AryTing** [comment] 2019-06-14 12:39
hi,I used the mysql  database.

**Comment by AryTing** [comment] 2019-06-17 09:57
Hi, if using sqlite3 data source, it doesn't have this issue. It works well.

**Comment by hugohaggmark** [comment] 2019-06-17 10:11
Hi again @AryTing , did I understand you correctly that this is not an issue any longer?

**Comment by AryTing** [comment] 2019-06-19 07:28
we want to use MariaDB database instead of sqlite3.  it works well on sqlite3 but not on MariaDB. 
This issue occurs on MariaDB database.

**Comment by hugohaggmark** [comment] 2019-06-19 07:59
Hi again,

have you tried to configuring these: 

- [conn-max-lifetime](https://grafana.com/docs/installation/configuration/#conn-max-lifetime) 
- [max_idle_conn](https://grafana.com/docs/installation/configuration/#max-idle-conn) 
- [max-open-conn](https://grafana.com/docs/installation/configuration/#max-open-conn)

**Comment by AryTing** [comment] 2019-06-19 08:45
no, I didn't configure these parameters. So they should use the default values.

**Comment by AryTing** [comment] 2019-06-19 09:15
in the running time, the MariaDB database shows:
`
![image](https://user-images.githubusercontent.com/51818464/59752981-cc8c6680-92b5-11e9-98e9-475e723b557f.png)
`

**Comment by AryTing** [comment] 2019-06-19 09:18
in the running time, some of parameters of the mariadb database are as follows ：
![image](https://user-images.githubusercontent.com/51818464/59753079-fba2d800-92b5-11e9-81cd-07cbded1b415.png)

**Comment by marefr** [comment] 2019-06-19 13:44
@AryTing are you using a clustered setup of MariaDB like multi-master, master/slave or replication?

This issue may be related? https://github.com/grafana/grafana/issues/13497

If you're not running a clustered or replication setup and you haven't configured above mentioned parameters that may be something to investigate to tweak the performance.

**Comment by AryTing** [comment] 2019-06-20 06:54
Thanks . I tried again with simplex MariaDB , it works well. So the grafana doesn't support multi-master. 
Is there plan for enhancement it to support multi-master or replication MariaDB?

**Comment by marefr** [comment] 2019-06-20 16:21
Duplicate of #13497

**Comment by marefr** [comment] 2019-06-20 16:24
Please continue discussion around support for multi-master in #13497. Agree it would be nice to fix, but maintainers of Grafana project would need help to investigate why it isn't working and how to fix it.

**Closed by marefr** 2019-06-20 16:24 UTC
Labels: area/backend/db/mysql, type/duplicate
