### ISSUE TITLE
Column sorting in table doesn't make sense

### ISSUE THREAD

**Issue by garbled1** [grafana/grafana#24873] opened 2020-05-19 14:50 UTC
**What happened**:
Sort a column of 0-1.0 values, get crazy results.

**What you expected to happen**:

Values should sort in ascending or descending order

**How to reproduce it (as minimally and precisely as possible)**:
Generated column from 2 numeric values, X / Y = column.  Generates a value of 0-1.0.  Doesn't matter what type of display I pick for the column, it seems to sort alphabetically instead of numerically?

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: postgresql
- OS Grafana is installed on: Debian 10
- User OS & Browser: Debian 10, firefox 68.7.0
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/6556271/82341541-6caaae00-99a5-11ea-9180-8879ecdf0573.png)

**Comment by torkelo** [comment] 2020-05-20 07:11
duplicate of https://github.com/grafana/grafana/issues/24557 

Can you add the raw response from your query to that issue? I am unable to replicate this.

**Closed by torkelo** 2020-05-20 07:11 UTC

**Comment by ivanahuckova** [comment] 2020-06-03 16:44
@torkelo I was able to replicate this on play.
![Kapture 2020-06-03 at 18 36 47](https://user-images.githubusercontent.com/30407135/83664346-2a4eb700-a5ca-11ea-92ad-99802ad60a72.gif)
