### ISSUE TITLE
Grafana alerts to be scheduled only on weekdays

### ISSUE THREAD

**Issue by deepaakella** [grafana/grafana#15238] opened 2019-02-04 20:42 UTC
Hi Grafana support Team,

 I am trying to set up alerts for dashboards that I had created to monitor the application parameters only on weekdays from 9-9 and skip the monitoring / alerting on weekends. Can you let me know the process for the same.

Below are the details of the Grafana tool that my application is using :

**Comment by bergquist** [comment] 2019-02-05 09:44
dupe of https://github.com/grafana/grafana/issues/6592

**Closed by bergquist** 2019-02-05 09:44 UTC
