### ISSUE TITLE
[ packaging ] RPM verification failure on RHEL 8 in FIPS mode

### ISSUE THREAD

**Issue by mpostument** [grafana/grafana#41036] opened 2021-10-28 11:38 UTC
**What happened**: Installation of grafana 8.2.2 on Red Hat 8 with enabled FIPS is failing with error
```shell
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Transaction test error:
  package grafana-8.2.2-1.x86_64 does not verify: no digest

$rpm --checksig grafana-8.2.2-1.x86_64.rpm 
grafana-8.2.2-1.x86_64.rpm: DIGESTS signatures NOT OK

$rpm --checksig -v grafana-8.2.2-1.x86_64.rpm 
grafana-8.2.2-1.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID 24098cb6: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    V4 RSA/SHA256 Signature, key ID 24098cb6: OK
    MD5 digest: NOTFOUND
```

**What you expected to happen**: Package is installed

**How to reproduce it (as minimally and precisely as possible)**: Try to install on RedHat 8 with FIPS enabled

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: - 
- OS Grafana is installed on: RedHat 8 with FIPS
- User OS & Browser: - 
- Grafana plugins: - 
- Others:

**Comment by ngharo** [comment] 2022-01-19 23:18
This is a real issue. Red Hat 8.5 w/ FIPS

```
# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.5 (Ootpa)

# grep fips=1 /proc/cmdline 
BOOT_IMAGE=(hd0,msdos2)/vmlinuz-4.18.0-348.7.1.el8_5.x86_64 root=/dev/mapper/rhel-root ro nofb splash=quiet crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet rd.shell=0 fips=1 boot=UUID=061a03d1-5b66-4bc0-9811-2f3fec95bd37 page_poison=1 vsyscall=none slub_debug=P audit=1 audit_backlog_limit=8192 pti=on

# curl -O https://dl.grafana.com/oss/release/grafana-8.3.4-1.x86_64.rpm
# rpm --checksig -v grafana-8.3.4-1.x86_64.rpm 
grafana-8.3.4-1.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID 24098cb6: NOKEY
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    V4 RSA/SHA256 Signature, key ID 24098cb6: NOKEY
    MD5 digest: NOTFOUND
```

Attempting install via dnf/yum/rpm
```
Error: Transaction test error:
  package grafana-8.3.4-1.x86_64 does not verify: no digest
```

Here's the grafana package in Red Hat repositories

```
# dnf download grafana
... 
grafana-7.5.9-5.el8_5.x86_64.rpm

# rpm --checksig -v grafana-7.5.9-5.el8_5.x86_64.rpm 
grafana-7.5.9-5.el8_5.x86_64.rpm:
    Header V3 RSA/SHA256 Signature, key ID fd431d51: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, key ID fd431d51: OK
```

Notice how all checks report OK.

If someone can point me towards more information how packages are built, I may be able to help contribute a fix.

**Comment by ngharo** [comment] 2022-01-19 23:25
@kminehart Can we reopen this please? I'm happy to contribute any information needed to track this down.

This has been a pretty common issue on RHEL 8. Red Hat introduced stricter package verification (sha256 file digests and signature requirements) without communicating it very well.

Here's a related issue for Telegraf that was resolved by changing one line in their build process
https://github.com/influxdata/telegraf/issues/10270 and PR https://github.com/influxdata/telegraf/pull/10272/files

**Comment by ngharo** [comment] 2022-02-14 15:13
@kminehart can you help?

**Comment by hrw** [comment] 2022-04-07 17:05
CentOS Stream 9 does not handle SHA1 keys at all.

```
[root@8d1db04e7f70 ~]# wget -q https://packages.grafana.com/gpg.key
[root@8d1db04e7f70 ~]# rpm --import gpg.key
error: gpg.key: key 1 import failed.
[root@8d1db04e7f70 ~]# 
```

**Comment by hrw** [comment] 2022-04-19 10:57
Any update?

**Comment by hrw** [comment] 2022-05-17 07:37
ping

**Comment by willscavforlabkeys** [comment] 2022-09-09 22:47
```
# rpm --checksig -v /var/cache/dnf/grafana-ee12c6ab2813e349/packages/grafana-enterprise-9.1.4-1.x86_64.rpm
/var/cache/dnf/grafana-ee12c6ab2813e349/packages/grafana-enterprise-9.1.4-1.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID 24098cb6: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    V4 RSA/SHA256 Signature, key ID 24098cb6: OK
    MD5 digest: NOTFOUND

# sha256sum /var/cache/dnf/grafana-ee12c6ab2813e349/packages/grafana-enterprise-9.1.4-1.x86_64.rpm
0654b9958fdf9585b214f9b5484c364169305dc5bed4ffc2ffd64455a61898b6  /var/cache/dnf/grafana-ee12c6ab2813e349/packages/grafana-enterprise-9.1.4-1.x86_64.rpm
```

🤦 

@ngharo Thoughts? This isn't fixed.

**Comment by nmaludy** [comment] 2022-11-10 18:23
Same issue on my end.

**Comment by kminehart** [comment] 2022-11-15 18:41
@nmaludy @willscavforlabkeys @hrw @ngharo I would love to help but I need more information from you all on how to reproduce the issue.

Whenever I do anything with docker using RedHat's Universal Base Image or CentOS, it works fine. What am I missing?

**Comment by nmaludy** [comment] 2022-11-15 19:11
@kminehart you need to enable FIPS mode: https://access.redhat.com/solutions/137833

For RHEL/CentOS/Rocky 8 it's simply:

```
fips-mode-setup --enable
update-crypto-policies --set FIPS:OSPP
reboot
```
This turns off things like SHA1 and MD5.


Then, if you try to install the grafana package it will fail the transaction with an error
```
Error unpacking rpm package
error: unpacking of archive failed on file /etc/init.d/grafana-server;636d3ee6: cpio: Digest mismatch
```

I believe the issue is that somehow the grafana package is built with either SHA1 or MD5 hashes. When Yum tries to verify the hashes it fails because those algorithms are not allowed in FIPS mode.

**Comment by hrw** [comment] 2022-11-15 19:14
Fresh `quay.io/centos/centos:stream9` container:

```
bash-5.1# cat /etc/yum.repos.d/grafana.repo
[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
bash-5.1# dnf install -y grafana
CentOS Stream 9 - BaseOS                                                                                              6.1 MB/s | 6.0 MB     00:00
CentOS Stream 9 - AppStream                                                                                            17 MB/s |  15 MB     00:00
CentOS Stream 9 - Extras packages                                                                                      21 kB/s | 8.8 kB     00:00
grafana                                                                                                               993  B/s | 454  B     00:00
grafana                                                                                                               9.6 kB/s | 1.7 kB     00:00
Importing GPG key 0x24098CB6:
 Userid     : "Grafana <info@grafana.com>"
 Fingerprint: 4E40 DDF6 D76E 284A 4A67 80E4 8C8C 34C5 2409 8CB6
 From       : https://packages.grafana.com/gpg.key
grafana                                                                                                                15 MB/s |  24 MB     00:01
Dependencies resolved.
======================================================================================================================================================
 Package                                                Architecture             Version                            Repository                   Size
======================================================================================================================================================
Installing:
 grafana                                                x86_64                   9.2.4-1                            grafana                      91 M
Installing dependencies:
 acl                                                    x86_64                   2.3.1-3.el9                        baseos                       73 k
 chkconfig                                              x86_64                   1.20-2.el9                         baseos                      180 k
 cracklib                                               x86_64                   2.9.6-27.el9                       baseos                       94 k
 cracklib-dicts                                         x86_64                   2.9.6-27.el9                       baseos                      3.6 M
 cryptsetup-libs                                        x86_64                   2.4.3-5.el9                        baseos                      437 k
 dbus                                                   x86_64                   1:1.12.20-6.el9                    baseos                      3.8 k
 dbus-broker                                            x86_64                   28-7.el9                           baseos                      172 k
 dbus-common                                            noarch                   1:1.12.20-6.el9                    baseos                       15 k
 device-mapper                                          x86_64                   9:1.02.185-3.el9                   baseos                      141 k
 device-mapper-libs                                     x86_64                   9:1.02.185-3.el9                   baseos                      178 k
 fontconfig                                             x86_64                   2.14.0-1.el9                       appstream                   297 k
 freetype                                               x86_64                   2.10.4-9.el9                       baseos                      388 k
 graphite2                                              x86_64                   1.3.14-9.el9                       baseos                       95 k
 harfbuzz                                               x86_64                   2.7.4-8.el9                        baseos                      625 k
 initscripts-service                                    noarch                   10.11.5-1.el9                      baseos                       14 k
 kmod-libs                                              x86_64                   28-7.el9                           baseos                       64 k
 libbrotli                                              x86_64                   1.0.9-6.el9                        baseos                      314 k
 libdb                                                  x86_64                   5.3.28-53.el9                      baseos                      738 k
 libeconf                                               x86_64                   0.4.1-2.el9                        baseos                       28 k
 libfdisk                                               x86_64                   2.37.4-9.el9                       baseos                      155 k
 libpng                                                 x86_64                   2:1.6.37-12.el9                    baseos                      117 k
 libpwquality                                           x86_64                   1.4.4-8.el9                        baseos                      119 k
 libseccomp                                             x86_64                   2.5.2-2.el9                        baseos                       72 k
 libutempter                                            x86_64                   1.2.1-6.el9                        baseos                       27 k
 openssl                                                x86_64                   1:3.0.1-43.el9                     baseos                      1.2 M
 pam                                                    x86_64                   1.5.1-13.el9                       baseos                      622 k
 systemd                                                x86_64                   250-11.el9                         baseos                      4.2 M
 systemd-libs                                           x86_64                   250-11.el9                         baseos                      633 k
 systemd-pam                                            x86_64                   250-11.el9                         baseos                      258 k
 systemd-rpm-macros                                     noarch                   250-11.el9                         baseos                       43 k
 urw-base35-bookman-fonts                               noarch                   20200910-6.el9                     appstream                   847 k
 urw-base35-c059-fonts                                  noarch                   20200910-6.el9                     appstream                   875 k
 urw-base35-d050000l-fonts                              noarch                   20200910-6.el9                     appstream                    77 k
 urw-base35-fonts                                       noarch                   20200910-6.el9                     appstream                    11 k
 urw-base35-fonts-common                                noarch                   20200910-6.el9                     appstream                    22 k
 urw-base35-gothic-fonts                                noarch                   20200910-6.el9                     appstream                   643 k
 urw-base35-nimbus-mono-ps-fonts                        noarch                   20200910-6.el9                     appstream                   796 k
 urw-base35-nimbus-roman-fonts                          noarch                   20200910-6.el9                     appstream                   856 k
 urw-base35-nimbus-sans-fonts                           noarch                   20200910-6.el9                     appstream                   1.3 M
 urw-base35-p052-fonts                                  noarch                   20200910-6.el9                     appstream                   974 k
 urw-base35-standard-symbols-ps-fonts                   noarch                   20200910-6.el9                     appstream                    42 k
 urw-base35-z003-fonts                                  noarch                   20200910-6.el9                     appstream                   276 k
 util-linux                                             x86_64                   2.37.4-9.el9                       baseos                      2.3 M
 util-linux-core                                        x86_64                   2.37.4-9.el9                       baseos                      461 k
 xml-common                                             noarch                   0.6.3-58.el9                       appstream                    32 k

Transaction Summary
======================================================================================================================================================
Install  46 Packages

Total download size: 115 M
Installed size: 370 M
Downloading Packages:
(1/46): cracklib-2.9.6-27.el9.x86_64.rpm                                                                              230 kB/s |  94 kB     00:00
(2/46): acl-2.3.1-3.el9.x86_64.rpm                                                                                    170 kB/s |  73 kB     00:00
(3/46): chkconfig-1.20-2.el9.x86_64.rpm                                                                               355 kB/s | 180 kB     00:00
(4/46): dbus-1.12.20-6.el9.x86_64.rpm                                                                                  25 kB/s | 3.8 kB     00:00
(5/46): cryptsetup-libs-2.4.3-5.el9.x86_64.rpm                                                                        1.4 MB/s | 437 kB     00:00
(6/46): dbus-broker-28-7.el9.x86_64.rpm                                                                               766 kB/s | 172 kB     00:00
(7/46): dbus-common-1.12.20-6.el9.noarch.rpm                                                                           91 kB/s |  15 kB     00:00
(8/46): device-mapper-1.02.185-3.el9.x86_64.rpm                                                                       762 kB/s | 141 kB     00:00
(9/46): freetype-2.10.4-9.el9.x86_64.rpm                                                                              1.5 MB/s | 388 kB     00:00
(10/46): graphite2-1.3.14-9.el9.x86_64.rpm                                                                            642 kB/s |  95 kB     00:00
(11/46): device-mapper-libs-1.02.185-3.el9.x86_64.rpm                                                                 225 kB/s | 178 kB     00:00
(12/46): initscripts-service-10.11.5-1.el9.noarch.rpm                                                                 156 kB/s |  14 kB     00:00
(13/46): cracklib-dicts-2.9.6-27.el9.x86_64.rpm                                                                       2.4 MB/s | 3.6 MB     00:01
(14/46): kmod-libs-28-7.el9.x86_64.rpm                                                                                441 kB/s |  64 kB     00:00
(15/46): harfbuzz-2.7.4-8.el9.x86_64.rpm                                                                              365 kB/s | 625 kB     00:01
(16/46): libbrotli-1.0.9-6.el9.x86_64.rpm                                                                             235 kB/s | 314 kB     00:01
(17/46): libeconf-0.4.1-2.el9.x86_64.rpm                                                                              174 kB/s |  28 kB     00:00
(18/46): libfdisk-2.37.4-9.el9.x86_64.rpm                                                                             246 kB/s | 155 kB     00:00
(19/46): libpng-1.6.37-12.el9.x86_64.rpm                                                                              216 kB/s | 117 kB     00:00
(20/46): libdb-5.3.28-53.el9.x86_64.rpm                                                                               351 kB/s | 738 kB     00:02
(21/46): libseccomp-2.5.2-2.el9.x86_64.rpm                                                                            354 kB/s |  72 kB     00:00
(22/46): libpwquality-1.4.4-8.el9.x86_64.rpm                                                                          413 kB/s | 119 kB     00:00
(23/46): libutempter-1.2.1-6.el9.x86_64.rpm                                                                           115 kB/s |  27 kB     00:00
(24/46): pam-1.5.1-13.el9.x86_64.rpm                                                                                  652 kB/s | 622 kB     00:00
(25/46): openssl-3.0.1-43.el9.x86_64.rpm                                                                              958 kB/s | 1.2 MB     00:01
(26/46): systemd-pam-250-11.el9.x86_64.rpm                                                                            1.2 MB/s | 258 kB     00:00
(27/46): systemd-rpm-macros-250-11.el9.noarch.rpm                                                                     274 kB/s |  43 kB     00:00
(28/46): systemd-250-11.el9.x86_64.rpm                                                                                2.5 MB/s | 4.2 MB     00:01
(29/46): systemd-libs-250-11.el9.x86_64.rpm                                                                           440 kB/s | 633 kB     00:01
(30/46): fontconfig-2.14.0-1.el9.x86_64.rpm                                                                           961 kB/s | 297 kB     00:00
(31/46): util-linux-2.37.4-9.el9.x86_64.rpm                                                                           1.9 MB/s | 2.3 MB     00:01
(32/46): urw-base35-bookman-fonts-20200910-6.el9.noarch.rpm                                                           5.5 MB/s | 847 kB     00:00
(33/46): util-linux-core-2.37.4-9.el9.x86_64.rpm                                                                      421 kB/s | 461 kB     00:01
(34/46): urw-base35-d050000l-fonts-20200910-6.el9.noarch.rpm                                                          1.3 MB/s |  77 kB     00:00
(35/46): urw-base35-fonts-common-20200910-6.el9.noarch.rpm                                                            364 kB/s |  22 kB     00:00
(36/46): urw-base35-fonts-20200910-6.el9.noarch.rpm                                                                   113 kB/s |  11 kB     00:00
(37/46): urw-base35-c059-fonts-20200910-6.el9.noarch.rpm                                                              2.9 MB/s | 875 kB     00:00
(38/46): urw-base35-gothic-fonts-20200910-6.el9.noarch.rpm                                                            7.5 MB/s | 643 kB     00:00
(39/46): urw-base35-nimbus-roman-fonts-20200910-6.el9.noarch.rpm                                                       11 MB/s | 856 kB     00:00
(40/46): urw-base35-nimbus-sans-fonts-20200910-6.el9.noarch.rpm                                                        13 MB/s | 1.3 MB     00:00
(41/46): urw-base35-p052-fonts-20200910-6.el9.noarch.rpm                                                               15 MB/s | 974 kB     00:00
(42/46): urw-base35-standard-symbols-ps-fonts-20200910-6.el9.noarch.rpm                                               875 kB/s |  42 kB     00:00
(43/46): urw-base35-z003-fonts-20200910-6.el9.noarch.rpm                                                              4.1 MB/s | 276 kB     00:00
(44/46): xml-common-0.6.3-58.el9.noarch.rpm                                                                           484 kB/s |  32 kB     00:00
(45/46): urw-base35-nimbus-mono-ps-fonts-20200910-6.el9.noarch.rpm                                                    1.9 MB/s | 796 kB     00:00
(46/46): grafana-9.2.4-1.x86_64.rpm                                                                                    50 MB/s |  91 MB     00:01
------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                  12 MB/s | 115 MB     00:09
CentOS Stream 9 - BaseOS                                                                                              1.6 MB/s | 1.6 kB     00:00
Importing GPG key 0x8483C65D:
 Userid     : "CentOS (CentOS Official Signing Key) <security@centos.org>"
 Fingerprint: 99DB 70FA E1D7 CE22 7FB6 4882 05B5 55B3 8483 C65D
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
Key imported successfully
grafana                                                                                                               9.6 kB/s | 1.7 kB     00:00
Importing GPG key 0x24098CB6:
 Userid     : "Grafana <info@grafana.com>"
 Fingerprint: 4E40 DDF6 D76E 284A 4A67 80E4 8C8C 34C5 2409 8CB6
 From       : https://packages.grafana.com/gpg.key
warning: Signature not supported. Hash algorithm SHA1 not available.
Key import failed (code 2). Failing package is: grafana-9.2.4-1.x86_64
 GPG Keys are configured as: https://packages.grafana.com/gpg.key
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
bash-5.1#```

**Comment by hrw** [comment] 2022-11-15 19:15
Run key linter (from sequoia-keyring-linter-0.5.0-9.fc37.x86_64 package) on Fedora 37:

```
20:14 marcin@puchatek:del$ wget https://packages.grafana.com/gpg.key
--2022-11-15 20:14:27--  https://packages.grafana.com/gpg.key
Translacja packages.grafana.com (packages.grafana.com)... 151.101.2.217, 151.101.66.217, 151.101.130.217, ...
Łączenie się z packages.grafana.com (packages.grafana.com)|151.101.2.217|:443... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 1694 (1,7K) [text/plain]
Zapis do: `gpg.key'

gpg.key                               100%[=======================================================================>]   1,65K  --.-KB/s     w 0s

2022-11-15 20:14:27 (35,9 MB/s) - zapisano `gpg.key' [1694/1694]

20:14 marcin@puchatek:del$ sq-keyring-linter gpg.key
Certificate 8C8C34C524098CB6 is not valid under the standard policy: No binding signature at time 2022-11-15T19:14:32Z
Certificate 8C8C34C524098CB6 contains a User ID ("Grafana <info@grafana.com>") protected by SHA-1
Certificate 8C8C34C524098CB6, key CA6D481DBD044C76 uses a SHA-1-protected binding signature.
Examined 1 certificate.
  0 certificates are invalid and were not linted. (GOOD)
  1 certificate was linted.
  1 of the 1 certificates (100%) has at least one issue. (BAD)
0 of the linted certificates were revoked.
  0 of the 0 certificates has revocation certificates that are weaker than the certificate and should be recreated. (GOOD)
0 of the linted certificates were expired.
1 of the non-revoked linted certificate has at least one non-revoked User ID:
  1 has at least one User ID protected by SHA-1. (BAD)
  1 has all User IDs protected by SHA-1. (BAD)
1 of the non-revoked linted certificates has at least one non-revoked, live subkey:
  1 has at least one non-revoked, live subkey with a binding signature that uses SHA-1. (BAD)
0 of the non-revoked linted certificates have at least one non-revoked, live, signing-capable subkey:
  0 certificates have at least one non-revoked, live, signing-capable subkey with a strong binding signature, but a backsig that uses SHA-1. (GOOD)```

**Comment by kminehart** [comment] 2022-11-15 19:54
Gotya. We'll lok into it, I appreciate the responses.

**Comment by hrw** [comment] 2022-11-22 17:28
@kminehart any update?

**Comment by kminehart** [comment] 2022-11-29 17:22
Looking into it now.

**Comment by kminehart** [comment] 2022-11-29 18:04
Opened a PR to set the `--rpm-digest sha256` argument when we create the packages with `fpm`. This seems pretty benign so we're going to continue with that, and if that doesn't work, we'll continue to investigate.

**Comment by kminehart** [comment] 2022-11-30 16:08
I did say,

> This seems pretty benign so we're going to continue with that, and if that doesn't work, we'll continue to investigate

Why don't we wait to see how this affects your installation first and if that doesn't work then we can re-open the issue and look into the more difficult task of improving our GPG key?

This pull request was not merged for the 9.3.0 package but that argument will be used in 9.3.1 and 9.4.0 when those are released.

**Comment by hrw** [comment] 2022-12-13 20:20
9.3.1 got released:

```
INFO:kolla.common.utils.grafana:(22/22): grafana-9.3.1-1.x86_64.rpm              22 MB/s |  84 MB     00:03
INFO:kolla.common.utils.grafana:--------------------------------------------------------------------------------
INFO:kolla.common.utils.grafana:Total                                            15 MB/s |  93 MB     00:06
INFO:kolla.common.utils.grafana:grafana                                         9.2 kB/s | 1.7 kB     00:00
INFO:kolla.common.utils.grafana:Importing GPG key 0x24098CB6:
INFO:kolla.common.utils.grafana: Userid     : "Grafana <info@grafana.com>"
INFO:kolla.common.utils.grafana: Fingerprint: 4E40 DDF6 D76E 284A 4A67 80E4 8C8C 34C5 2409 8CB6
INFO:kolla.common.utils.grafana: From       : https://packages.grafana.com/gpg.key
INFO:kolla.common.utils.grafana:
INFO:kolla.common.utils.grafana:warning: Signature not supported. Hash algorithm SHA1 not available.
INFO:kolla.common.utils.grafana:
INFO:kolla.common.utils.grafana:Key import failed (code 2). Failing package is: grafana-9.3.1-1.x86_64
INFO:kolla.common.utils.grafana: GPG Keys are configured as: https://packages.grafana.com/gpg.key
INFO:kolla.common.utils.grafana:
INFO:kolla.common.utils.grafana:The downloaded packages were saved in cache until the next successful transaction.
INFO:kolla.common.utils.grafana:You can remove cached packages by executing 'dnf clean packages'.
INFO:kolla.common.utils.grafana:Error: GPG check FAILED
INFO:kolla.common.utils.grafana:
```

Let me repeat: GPG key is wrong.

**Comment by kminehart** [comment] 2022-12-14 20:00
@hrw no need to be adversarial, it's perfectly sufficient to say that it's still not working as expected. I'm trying to help.

**Comment by mnasiadka** [comment] 2023-01-02 11:41
You can just use sequoia-keyring-linter (https://crates.io/crates/sequoia-keyring-linter) for linting the gpg keyring file:
 
 curl https://rpm.grafana.com/gpg.key | sq-keyring-linter
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1694  100  1694    0     0   5902      0 --:--:-- --:--:-- --:--:--  5902
Certificate 8C8C34C524098CB6 is not valid under the standard policy: No binding signature at time 2023-01-02T11:40:05Z
Certificate 8C8C34C524098CB6 contains a User ID ("Grafana <info@grafana.com>") protected by SHA-1
Certificate 8C8C34C524098CB6, key CA6D481DBD044C76 uses a SHA-1-protected binding signature.
Examined 1 certificate.
  0 certificates are invalid and were not linted. (GOOD)
  1 certificate was linted.
  1 of the 1 certificates (100%) has at least one issue. (BAD)
0 of the linted certificates were revoked.
  0 of the 0 certificates has revocation certificates that are weaker than the certificate and should be recreated. (GOOD)
0 of the linted certificates were expired.
1 of the non-revoked linted certificate has at least one non-revoked User ID:
  1 has at least one User ID protected by SHA-1. (BAD)
  1 has all User IDs protected by SHA-1. (BAD)
1 of the non-revoked linted certificates has at least one non-revoked, live subkey:
  1 has at least one non-revoked, live subkey with a binding signature that uses SHA-1. (BAD)
0 of the non-revoked linted certificates have at least one non-revoked, live, signing-capable subkey:
  0 certificates have at least one non-revoked, live, signing-capable subkey with a strong binding signature, but a backsig that uses SHA-1. (GOOD)

**Comment by hrw** [comment] 2023-01-18 06:37
Looks like problem got fixed:

```
07:36 marcin@puchatek:del$ wget https://packages.grafana.com/gpg.key
--2023-01-18 07:36:35--  https://packages.grafana.com/gpg.key
Translacja packages.grafana.com (packages.grafana.com)... 151.101.130.217, 151.101.66.217, 151.101.2.217, ...
Łączenie się z packages.grafana.com (packages.grafana.com)|151.101.130.217|:443... połączono.
Żądanie HTTP wysłano, oczekiwanie na odpowiedź... 200 OK
Długość: 2460 (2,4K) [text/plain]
Zapis do: `gpg.key'

gpg.key                                         100%[====================================================================================================>]   2,40K  --.-KB/s     w 0,001s

2023-01-18 07:36:35 (2,69 MB/s) - zapisano `gpg.key' [2460/2460]

07:36 marcin@puchatek:del$ sq-keyring-linter gpg.key
Examined 1 certificate.
No issues found (see `sq-keyring-linter --help` for a list of issues that are checked for).
07:36 marcin@puchatek:del$
```

**Closed** 2023-01-18 15:28 UTC
Labels: type/build-packaging, needs investigation
