### ISSUE TITLE
404 on styleguide.json

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#9959] opened 2017-11-21 14:59 UTC
In master, when looking at:
http://localhost:3000/styleguide/colors

No colors are shown, and there is a 404 in the logs:

> http://localhost:3000/public/build/styleguide.json 404 (Not Found)

The other tabs seem to be OK.

**Comment by torkelo** [comment] 2017-11-21 15:05
duplicate of https://github.com/grafana/grafana/issues/9944

**Closed by torkelo** 2017-11-21 15:05 UTC
