### ISSUE TITLE
Using Overrides to change the Display Name affects the ability to hide/show different series

### ISSUE THREAD

**Issue by Ctrl-LeftAlt-Delete** [grafana/grafana#35770] opened 2021-06-15 16:12 UTC
**What happened**:
When showing multiple queries on the same Time Series panel and using Overrides to change the Display Name affects the ability to select the series name to hide the series.
When the Display Name override is applied and the user clicks the new series name in the panel to toggle show/hide, the effect is applied to all the series, not just the series that is clicked.
**What you expected to happen**:
I would expect the ability to show/hide the series to continue working for the individual series regardless of applying overrides.
**How to reproduce it (as minimally and precisely as possible)**:
Create a Time Series panel with 2 queries.
Click the series names individually and see how they individually appear and disappear.
Now create an override (Fields with name) to change the Standard Options > Display Name for one or both series.
Go back and click the series names individually and see how they no longer appear and disappear individually. Each time you click any of the series, both series will appear and dissapear.
**Environment**:
- Grafana version: Grafana v8.0.1 (8849243d27)
- Data source type & version: InfluxDB 2.0.7
- OS Grafana is installed on: Synology NAS Docker
- User OS & Browser: Windows 10 + Chrome
- Grafana plugins:
- Others:

**Anything else we need to know?**:
See Panel JSON below:

```json
{
  "id": 23763571993,
  "gridPos": {
    "h": 8,
    "w": 12,
    "x": 12,
    "y": 16
  },
  "type": "timeseries",
  "title": "Tank Flow (MP40 Power)",
  "pluginVersion": "8.0.1",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [],
      "unit": "watt"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "watt {device_id=\"2_1\", hardware=\"1.0\", host=\"telegraf1\", name=\"MP40_LPwr\", output_id=\"8\", output_type=\"outlet\", software=\"5.05_1A20\", source=\"Peninsula230\", type=\"output\"}"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "MP40 Left Power"
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "single"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": [
        "min",
        "mean",
        "max",
        "range"
      ]
    }
  },
  "targets": [
    {
      "query": "from(bucket: \"TelegrafBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"neptune_apex\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"MP40_LPwr\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"watt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
      "refId": "MP40 Left Power"
    },
    {
      "hide": false,
      "query": "from(bucket: \"TelegrafBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"neptune_apex\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"MP40_RPwr\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"watt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
      "refId": "MP40 Right Power"
    }
  ],
  "datasource": null
}
```

**Comment by marefr** [comment] 2021-06-15 16:52
Reproduced bug. Tested changing display name for Simple Graph and backend_01 in this dashboard: https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1

**Comment by torkelo** [comment] 2021-06-15 19:30
duplicate of https://github.com/grafana/grafana/issues/31364

**Closed by torkelo** 2021-06-15 19:30 UTC
Labels: area/field/overrides, area/panel/timeseries, type/bug
