### ISSUE TITLE
TimeSeries Panel Legend as Table scroll left/right

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#35568] opened 2021-06-11 13:53 UTC
In the "TimeSeries" panel, the "Legend" table in table mode incorrectly has a margin-left of 8px. This leads to the table scrolling to the right and left, even though it is supposed to have a size (width) of 100%.

I correct that with the CSS:
`.css-1e78qpm
  { margin-left: -1px !important; }`

This can be reproduced in play.grafana.com. 
<img width="1290" alt="grafik" src="https://user-images.githubusercontent.com/79257887/121697128-0a9b7a00-cacd-11eb-8deb-145bdbb17e39.png">

**Comment by torkelo** [comment] 2021-06-11 13:56
dupe of https://github.com/grafana/grafana/issues/32676

**Comment by torkelo** [comment] 2021-06-11 13:57
fix coming https://github.com/grafana/grafana/pull/35563

**Closed by torkelo** 2021-06-11 13:56 UTC
