### ISSUE TITLE
[Bug] Templating variables is missing parenthesis around expression.

### ISSUE THREAD

**Issue by mrosterm** [grafana/grafana#7372] opened 2017-01-26 14:27 UTC
- What Grafana version are you using?

3.1.1 and 4.1.1 (installed from RPM's)

- What datasource are you using?

InfluxDB + Elasticsearch

- What OS are you running grafana on?

CentOS 7

- What did you do?

Upgraded from 3.1.1 to 4.1.1.

- What was the expected result?

Templating variables would work as previous. Using e.g. `$Host` would expand to `(hostname1|hostname2)` if both hostname1 and hostname2 are selected.

- What happened instead?

Grafana version 3.1.1 query against an InfluxDB data source with hostname1 and hostname2 selected:
`SELECT MEAN("value") FROM /(hostname1|hostname2)\.iostat\.(sda|sdb|md0)\.r_per_s$/ WHERE time > now() - 2m GROUP BY time(100ms) fill(null)`

Grafana version 4.1.1 query against an InfluxDB data source with hostname1 and hostname2 selected:
`SELECT MEAN("value") FROM /hostname1|hostname2\.iostat\.(sda|sdb|md0)\.r_per_s$/ WHERE time > now() - 2m GROUP BY time(100ms) fill(null)`

Don't currently have any similar queries performed against our Elasticsearch clusters as I was forced to roll back the upgrade before I managed to fetch it.

**Comment by torkelo** [comment] 2017-01-26 14:31
dupe of https://github.com/grafana/grafana/issues/7306 

You can change to use the query editor mode it has the correct interpolation

**Closed by torkelo** 2017-01-26 14:31 UTC
