### ISSUE TITLE
Graph Panel: add a ceiling value to y axis 

### ISSUE THREAD

**Issue by lanzafame** [grafana/grafana#22819] opened 2020-03-17 01:53 UTC
**What would you like to be added**:
Currently, if you add a max to the y-axis, the y-axis doesn't dynamically resize to anything less than that value. What I would like is the ability to set a ceiling value for the y-axis that allows the axis to resize as if both min/max are set to auto but won't go beyond the ceiling value.

**Why is this needed**:
Certain graphs will never have values above a certain amount but setting max to that value results in a graph that isn't always as readable as it could be.

The following shows a graph with y-axis max set to auto, resulting in 125%, which for this particular graph is impossible:
<img width="268" alt="Screen Shot 2020-03-17 at 09 53 33" src="https://user-images.githubusercontent.com/5924712/76812738-97f80c00-6841-11ea-9a02-95c80e336583.png">

So during times when there are no peaks, the axis re-scales to an appropriate height but this function is lost when the max is set. If there was a way to set the ceiling value so that scaling would happen up to the ceiling value, this would be ideal.

**Comment by slar** [comment] 2020-07-09 08:37
Found this issue while searching for if this feature existed. I would find this feature very useful too.

**Comment by torkelo** [comment] 2020-07-09 10:07
duplicate of https://github.com/grafana/grafana/issues/979

**Closed by torkelo** 2020-07-09 10:07 UTC
Labels: area/frontend, area/ux, priority/awaiting-more-evidence, type/feature-request
