### ISSUE TITLE
One of the users gets login.OAuthLogin(get info from azuread) but the rest is fine

### ISSUE THREAD

**Issue by nimdil** [grafana/grafana#36215] opened 2021-06-28 11:42 UTC
**What happened**:
We have setup Grafana in our AKS cluster. It works fine with "Sign in with Microsoft" for everyone (few people) except me.

**What you expected to happen**:
Logging in.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure.

**Anything else we need to know?**:
[auth.azuread]
name = Azure AD
enabled = true
allow_sign_up = true
client_id = <id>
client_secret = ${AZURE_AD_SECRET}
scopes = openid email profile
auth_url = <correct url>
token_url = <correct url>
allowed_domains = <our domain>
allowed_groups = <groups IDs of several groups>

I can check in Azure Portal that I'm member of some of the groups listed and so I should get through. My colleagues are getting through without any issues. I however can't - regardless of browser and incognito mode.

When I try to log in I get following log entry:
t=2021-06-28T09:48:06+0000 lvl=eror msg="login.OAuthLogin(get info from azuread)" logger=context userId=0 orgId=0 uname= error="user not a member of one of the required groups"

which is contradictory to information in Portal Azure. The only difference between my account in AAD and the other users' accounts is that my account is member of a lot more AAD groups (>100) than the rest.

**Environment**:
- Grafana version: v7.5.4 (615c153b3a)
- OS Grafana is installed on: FROM grafana/grafana:latest-ubuntu
- User OS & Browser: Windows 10 & Opera/Firefox/Edge/Chrome

**Comment by wbrowne** [comment] 2021-07-05 10:08
@nimdil Looks like this is potentially a duplicate of this issue https://github.com/grafana/grafana/issues/28457. Can you check it out and confirm?

**Comment by nimdil** [comment] 2021-08-12 13:33
> @nimdil Looks like this is potentially a duplicate of this issue #28457. Can you check it out and confirm?

I'll investigate further. It shouldn't necessarily be the reason as I'm member of under 140 groups so they all should fit into token. But maybe I'm missing something and as result only overall claim is provided.

**Comment by Jguer** [comment] 2022-06-03 08:42
This should be now be fixed in the latest version of 8.4, 8.5 and 9.0.

https://github.com/grafana/grafana/pull/43470
https://github.com/grafana/grafana/pull/49506

**Closed by Jguer** 2022-06-03 08:42 UTC
Labels: area/backend, area/auth/oauth

**Comment by mvadu** [comment] 2022-08-22 04:06
@Jguer  we had few users who were not hitting 200 limit, but exhibiting the behavior described in this issue. But the endpoint used to [extract roles](https://github.com/grafana/grafana/blob/6afad517618f01433e29d0ea4336fa47d2ab8859/pkg/login/social/azuread_oauth.go#L196) was erroring out with `read: connection reset by peer`. The way we solved the issue was to restrict the Azure token to include only Grafana app specific groups as per https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims#add-group-claims-to-tokens-for-saml-applications-using-sso-configuration 
![image](https://user-images.githubusercontent.com/8618235/185837528-a8a0bcd8-4573-4d95-8af8-a29157e12d01.png)
