### ISSUE TITLE
Singlestat: No background color when value is not numeric

### ISSUE THREAD

**Issue by Pedrat** [grafana/grafana#19867] opened 2019-10-16 16:20 UTC
**What happened**:
When grafana was updated from 6.3.5 to 6.4.X (tested with 6.4.0, 6.4.2 and 6.4.3) singlestat
panels no longer have background colors when any non-numeric value is present
**What you expected to happen**:

![image](https://user-images.githubusercontent.com/36329075/66937884-21f43c80-f038-11e9-9880-eb1cce683097.png)

But on version 6.4.3 it's not green (see image below, same panel but on 6.4.3)
![image](https://user-images.githubusercontent.com/36329075/66938001-4fd98100-f038-11e9-8343-b1cd35136751.png)

**How to reproduce it (as minimally and precisely as possible)**:
* Have a grafana instance running 6.4.X
* Add a singlestat panel with any dummy MySql database and with background color
* Test with following query: `SELECT 1` and should work
* Test with following query: `SELECT "1"` and should work
* Test with following query: `SELECT "1/1"` and it will not work

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: MySql
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-10-17 07:11
duplicate of https://github.com/grafana/grafana/issues/19548

**Closed by torkelo** 2019-10-17 07:11 UTC
