### ISSUE TITLE
[FeatureRequest] MySQL should accept DSN parameters

### ISSUE THREAD

**Issue by nicolaerosia** [grafana/grafana#33209] opened 2021-04-21 11:40 UTC
The current MySQL plugin does not provide a way to pass parameters to DSN [0]

I'm trying to use this plugin with MongoSQLd [1] which is MySQL 5 compliant however the go sql driver complains with the following error and I have no way of adding that parameter.
```
this user requires clear text authentication. If you still want to use it, please add 'allowCleartextPasswords=1' to your DSN
```

In my opinion, there should be a way to add additional parameters AND have an option to override default parameters which currently are being enforced:
```
cnnstr := fmt.Sprintf("%s:%s@%s(%s)/%s?collation=utf8mb4_unicode_ci&parseTime=true&loc=UTC&allowNativePasswords=true",
```

[0] https://github.com/grafana/grafana/blob/master/pkg/tsdb/mysql/mysql.go#L35
[1] https://docs.mongodb.com/bi-connector/current/reference/mongosqld/

**Comment by hugohaggmark** [comment] 2021-04-22 04:54
Passing this over to @grafana/backend-platform

**Comment by marefr** [comment] 2021-04-22 08:40
Duplicate of #16539

**Closed** 2021-04-22 08:40 UTC
Labels: area/backend/db/mysql, datasource/MySQL, type/feature-request

**Comment by marefr** [comment] 2022-04-27 15:46
Please use the discussion https://github.com/grafana/grafana/discussions/37010 linked from https://github.com/grafana/grafana/issues/16539 to discuss this further.
