### ISSUE TITLE
Alert Parsing Failed - unexpected character $

### ISSUE THREAD

**Issue by dnivra26** [grafana/grafana#32773] opened 2021-04-08 06:19 UTC
**Created an alert config for a Graph panel. Configuration looks fine. It is showing the red alert bar properly on the panel. However when i try to test the alert, getting a parse error

"error": "tsdb.HandleRequest() error bad_data: 1:131: parse error: unexpected character: '$'",

metric: metric_name{filter1="value", filter2="value"} - (metric_name{filter1="value", filter2="value"} offset $__interval > 0)**:

**Test rule to have worked fine**:

**Have alert configured for a offset metric with $__interval variable**:

**Environment**:
- Grafana version: Grafana v7.2.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: mac, Chrome

**Comment by zoltanbedi** [comment] 2021-04-08 08:40
Duplicate of #6557

**Closed by zoltanbedi** 2021-04-08 08:40 UTC
