### ISSUE TITLE
per-panel variables

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#20946] opened 2019-12-07 08:49 UTC
**What would you like to be added**:

I'd like per-panel template variables.  They should be accessible directly from the panel window.

**Why is this needed**:

For example, a variable to chose the displayed quantile, or N of a topk query, or a filter applied to the metric's labels.

Dashboard variables aren't useful for this, because you'd like to set each panel independently, and it would result in an unmanageable and confusing number of similarly-named variables.

**Comment by papagian** [comment] 2019-12-07 15:50
Duplicate of #8408

**Closed by papagian** 2019-12-07 15:50 UTC
Labels: type/duplicate
