### ISSUE TITLE
Postgres session database leaking connections

### ISSUE THREAD

**Issue by JorritSalverda** [grafana/grafana#9827] opened 2017-11-08 20:23 UTC
The postgres session database connection seems to have problems to keep the number of connections to the database under control.

- What Grafana version are you using?
**4.6.1**

- What datasource are you using?
**Postgres**

- What OS are you running grafana on?
**docker container grafana/grafana**

- What did you do?

My dashboards kept showing errors in the graphs. Looking at the error logs it turned out the Google Cloud SQL postgres ran out of connections. I then set up a cockroachdb cluster for the sessions database. 

- What was the expected result?

 The number of database connections to stay at a reasonable level. Connection pooling should probably keep it at 10 connections per grafana instance?

- What happened instead?

After running this configuration for half an hour the connection count has gone up to 800 connections, which seems a bit overzealous for a 3 pod grafana setup.

![grafana-sessions-db-connections](https://user-images.githubusercontent.com/136472/32572324-7a25a100-c4ca-11e7-947a-fafcdc922af6.png)

**Comment by JorritSalverda** [comment] 2017-11-08 20:36
It only gets worse, grafana is now failing to render any graphs. The connection count has surpassed 1500! The page itself can be refreshed, so it seems the database connection for the regular database works fine (I still point that one to the Cloud SQL postgres instance).

![1500plus](https://user-images.githubusercontent.com/136472/32572918-825d96aa-c4cc-11e7-80f3-44f8de1a80c2.png)

**Comment by JorritSalverda** [comment] 2017-11-09 08:43
Could it be that the init code for sessions using postgres at https://github.com/grafana/grafana/blob/v4.6.1/vendor/github.com/go-macaron/session/postgres/postgres.go#L108-L116 is getting called for each macaron session?

**Comment by daniellee** [comment] 2017-11-10 10:45
Wonder if this is related to: https://github.com/grafana/grafana/issues/9784

We are all out of office this week (at a conference). Will investigate on Monday.

**Comment by JorritSalverda** [comment] 2017-12-14 12:45
Did you find anything regarding a possible connection leak? This is still an issue every now and then. We currently use Google Cloud SQL postgres, which has a 100 connection limit which it frequently runs out of.

**Comment by remeika** [comment] 2017-12-19 00:46
Have you set `[database] max_idle_conn` / `[database] max_open_conn`? If so, what are the values?

**Comment by JorritSalverda** [comment] 2017-12-19 07:56
Ah, I didn't test those. Setting them to `max_idle_conn = 2` and `max_open_conn = 10` to verify whether that solves the issue. If this resolves the issue perhaps the default value for `max_open_conn` is better set to something else than unlimited :)

**Comment by JorritSalverda** [comment] 2017-12-19 07:58
Do these settings actually apply to the session database connection?

**Comment by JorritSalverda** [comment] 2017-12-19 08:47
Unfortunately the settings don't seem to apply to the session database connection created by macaron. I still get these kind of errors:

```
t=2017-12-19T08:41:59+0000 
lvl=eror 
msg="Request error" 
error="session/postgres: error checking existence: pq: remaining connection slots are reserved for non-replication superuser connections"
stack="
/usr/local/go/src/runtime/panic.go:491 (0x431e62)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/postgres/postgres.go:148 (0xb495c4)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/session.go:257 (0x832d21)\n
/go/src/github.com/grafana/grafana/pkg/middleware/session.go:117 (0xb9490f)\n
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:99 (0xb8fd6d)\n
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:57 (0xb969d6)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x7f19c0)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7d4863)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7d459a)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)\n
/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb979e0)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x7f19c0)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7d4863)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7d459a)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x7f1b15)\n
/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xb95571)\n
/usr/local/go/src/runtime/asm_amd64.s:509 (0x46107a)\n
/usr/local/go/src/reflect/value.go:434 (0x4bf934)\n
/usr/local/go/src/reflect/value.go:302 (0x4bef13)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7d4ba8)\n
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7d44a9)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x7f1bdd)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x803412)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:296 (0x7fd98b)\n
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x7f6387)\n
/usr/local/go/src/net/http/server.go:2619 (0x692de3)\n
/usr/local/go/src/net/http/server.go:1801 (0x68f09c)\n
/usr/local/go/src/runtime/asm_amd64.s:2337 (0x4638c0)\n
"
```

Like the `lvl` by the way ;)

**Comment by daniellee** [comment] 2017-12-19 18:11
@JorritSalverda Maybe you could do a temporay fix and try set it via the connection string:

http://www.npgsql.org/doc/connection-string-parameters.html

or changing the [max_connections setting](https://www.postgresql.org/docs/current/static/runtime-config-connection.html#GUC-MAX-CONNECTIONS) in the postgres config file might be another option. 

To properly solve this, it looks like we need to create a PR for Macaron so that we can send in the max open and max idle connections as session options.

**Comment by remeika** [comment] 2018-02-12 23:57
`max_connections` attempts to change the value on your postgres *server*, not in the Macaron client. Adding it causes grafana to panic:

`panic: pq: parameter "max_connections" cannot be changed without restarting the server
`

It will be worth submitting a PR to Macaron, and also checking Grafana to see if it is leaking sessions.

**Comment by lastblindpilot** [comment] 2018-07-04 15:11
Is this still an open issue? We have Grafana v5.1.3 and a lot of panels with postgres datasource.
![grafana_postgres_issue](https://user-images.githubusercontent.com/1263084/42284482-4eea1bdc-7fb5-11e8-9e7c-2f9ab9297a53.png)

**Comment by torkelo** [comment] 2018-07-04 17:48
Have you set [database] max_idle_conn / [database] max_open_conn , what to?

**Comment by lastblindpilot** [comment] 2018-07-18 10:18
The issue reappeared. 
max_idle_conn = 2, max_open_conn = 300, Grafana v5.1.3, Postgres max_connections = 1000
![image](https://user-images.githubusercontent.com/1263084/42875514-a1422550-8a8c-11e8-9101-a794815339ea.png)

**Comment by torkelo** [comment] 2018-07-18 10:43
@lastblindpilot are you using the postgres data source or just as Grafana main db?

**Comment by lastblindpilot** [comment] 2018-07-18 10:46
@torkelo, postgres as data source

**Comment by torkelo** [comment] 2018-07-18 14:22
dupe of (and fixed today) https://github.com/grafana/grafana/issues/12636

**Closed by torkelo** 2018-07-18 14:22 UTC
Labels: datasource: Postgres, type: bug
