### ISSUE TITLE
Starting to type the Prometheus query label value glitches the UI and removes the incompletely added label

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana#22242] opened 2020-02-17 06:20 UTC
**What happened**:

1. Start typing a Prometheus query.
1. Try to add a label filter e.g. `instance = "foo"`)
1. Observe as typing the opening quote before `foo` causes some UI glitch that removes the label, pops the cursor to the start of the textbox and executes the query.

Does not reproduce 100% of the times but fairly common.

Video evidence: https://imgur.com/AJ38jWK

**What you expected to happen**:

Typing the opening quote should just put the quote in the textbox.

**How to reproduce it (as minimally and precisely as possible)**:

Seems to happen about 10-50% of the time when I try to type the value for a label. It does not have to be the first label - adding more labels also triggers it. The label I try to add is removed when the glitch happens.

This is not always the quote character that triggers it - sometimes I get a few more characters in before it deletes it - this happens when I am typing faster. Autocomplete shenanigans?

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux (container)
- User OS & Browser: Firefox 73 on Windows 10
- Grafana plugins: Zabbix
- Others:

**Comment by sandersaares** [comment] 2020-02-17 06:50
Just now this happened again (happens a lot today - query specific?). The keyboard shortcuts help text popped up somehow. In the background, I noticed my key presses still went to the start of the textbox I was editing (though the contents had been mangled, removing the label I was adding).

Video of the resulting situation: https://imgur.com/U0abllG

**Comment by papagian** [comment] 2020-02-17 15:13
@sandersaares 
thank you for reporting this.
Can you check the Web Console under Web Developer menu for any errors/warnings?

**Comment by sandersaares** [comment] 2020-02-19 08:50
This appears to correlate with the glitches:

```
TypeError: this.props.panelData is undefined PromLink.tsx:21:27
```

When I break on exceptions, I see this:

![image](https://user-images.githubusercontent.com/9914262/74817438-918b7880-5305-11ea-92d4-cae81c7a3ced.png)

But one time I saw something else!

![image](https://user-images.githubusercontent.com/9914262/74817088-04482400-5305-11ea-865b-9d1396bcdb3a.png)

DeleteDashboard?! Hold up, on Monday a dashboard mysteriously vanished for me without me ever knowingly deleting it... could this be related? Some UI glitch makes me hit the delete button and invisibly confirm while typing a query?! Just a theory but a scary theory!

**Comment by Estrax** [comment] 2020-05-03 21:09
I wasn't able to reproduce it with the same setup - the problem is most likely with one of your browser plugins (like adblock).

Closing this issue.

**Closed by Estrax** 2020-05-03 21:09 UTC
Labels: area/frontend, datasource/Prometheus
