### ISSUE TITLE
Value Color in Singlestat panel of Grafana v6.5.0

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#20689] opened 2019-11-27 07:50 UTC
**What happened**: I have migrated from Grafana v6.3.5 to v6.5.0, and I have subsequently noticed that in the singlestat panel, the value colour is not being applied to non-integer datatypes while it had been applied in v6.3.5.

**What you expected to happen**: As in v6.3.5, the value colouring applies universally upon enabling the toggle switch.

**How to reproduce it (as minimally and precisely as possible)**: Create a singlestat panel retrieving data from a PostgreSQL datasource and a query returning a non-integer value; set value colouring on regardless of the other colouring options.

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: v6.5.0 (commit: 24a5d2f)
- Data source type & version: PostgreSQL v11
- OS Grafana is installed on: Ubuntu 19.10
- User OS & Browser: Ubuntu 19.10 & Mozilla Firefox 70.0.1 (64-bit)
- Grafana plugins: nil
- Others: nil

**Comment by marefr** [comment] 2019-11-27 12:21
Can you please include screenshot showing how you've configured it and the visual problem?

**Comment by torkelo** [comment] 2019-11-27 23:29
duplicate off https://github.com/grafana/grafana/issues/19548

**Closed by torkelo** 2019-11-27 23:29 UTC
Labels: needs more detail
