### ISSUE TITLE
Grafana settings for custom Azure clouds configuration

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#61126] opened 2023-01-09 06:14 UTC
Depends on:
- https://github.com/grafana/grafana-azure-sdk-go/issues/25

Design discussion:
- #61016

**Comment by kostrse** [comment] 2024-01-18 21:00
bump

**Comment by aangelisc** [comment] 2024-03-21 09:16
Closing as duplicate of #82915

**Closed by aangelisc** 2024-03-21 09:16 UTC
Labels: type/feature-request, datasource/Azure
