### ISSUE TITLE
Legend texts are not selectable anymore

### ISSUE THREAD

**Issue by jdesgats** [grafana/grafana#64493] opened 2023-03-09 09:58 UTC
**What happened**:
When a graph is having a legend, the text of the different entries is not selectable, we're only able to click it.

**What you expected to happen**:
We used to be able to select the text in legend entries, so it can be copy/pasted elsewhere.

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph with a legend, try to hover over text, it can't be selected.

**Anything else we need to know?**:
I think this was caused by #56690 that turned anchors `<a>` into buttons that behave differently when trying to select text.

**Environment**:
- Grafana version: 9.4.1
- Data source type & version: any
- OS Grafana is installed on: Linux
- User OS & Browser: Linux/Firefox 110
- Grafana plugins:
- Others:

**Comment by jdesgats** [comment] 2023-03-09 10:33
Some additional details: it seems to only happening when the legend is displayed as a table and doesn't happen when editing the graph. It seems that the `user-select: text;` CSS rule is not applied consistently in all cases.

**Comment by tonypowa** [comment] 2023-03-13 09:44
hi @jdesgats 

thank you for creating this issue

however, I could not reproduce it from my end locally  (v9.3.8), neither on https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

could you[ record a gif](https://community.grafana.com/t/proptip-record-gif-and-attach-to-bug-report-to-showcase-issue/31320) and provide any error logs (if there are any) ?

**Comment by volter** [comment] 2023-05-03 07:11
The problem appears to be limited to Firefox! Chrome works.

**Comment by tonypowa** [comment] 2023-05-03 07:55
I still cannot reproduce this in 9.4.7

![legend](https://user-images.githubusercontent.com/45235678/235860279-e100e208-c544-4b12-8fd5-b946636e7c16.gif)

![image](https://user-images.githubusercontent.com/45235678/235859884-20276a0a-2ffb-4284-b42f-abf5979f800c.png)

> The problem appears to be limited to Firefox! Chrome works.

what version of Grafana, Firefox are you running? And what OS?

**Comment by volter** [comment] 2023-05-03 07:57
Oh, this is about selecting text in a way you could copy it to the clipboard! That's at least how I read it and the problem I met.

**Comment by tonypowa** [comment] 2023-05-03 08:08
you are correct @volter  

I tested again and I can't select the text either 

Moreover, I just realised another user reported this problem already, and it has already been marked as a bug and assigned to an engineering team.   

https://github.com/grafana/grafana/issues/64084

Marking this issue as a /duplicate of #64084
You can follow up on the progress of the issue from there

thank you

**Closed** 2023-05-03 08:09 UTC
Labels: type/duplicate, needs more info
