### ISSUE TITLE
Docs: "Edit this page" leads to GitHub 404

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/grafana#54411] opened 2022-08-29 20:17 UTC
**What happened**:

I found a small format issue on the "Sharing" topic of the main Grafana docs ([related PR](https://github.com/grafana/grafana/pull/54408)).

But, when I selected **Edit this page**, the anchor went to a GitHub 404. I had to search for the text to find where the file actually ws.
All child topics in "Sharing" also have a broken edit link.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce:
1. Go to https://grafana.com/docs/grafana/latest/sharing/
2. Select **Edit this page**.
   - Where it goes: https://github.com/grafana/grafana/edit/main/docs/sources/sharing/_index.md
   - Where it should go: https://github.com/grafana/grafana/blob/main/docs/sources/share-dashboards-panels/index.md

**Comment by osg-grafana** [comment] 2022-08-30 10:51
Closing, due to duplicate of https://github.com/grafana/technical-documentation/issues/349.

**Comment by osg-grafana** [comment] 2022-08-30 11:22
Reopening so that there is more visibility to the public about this issue; the `technical-documentation` repo is private, and some of the details about the root cause of this and fix might otherwise be hidden from the public.

**Comment by MattDodsonEnglish** [comment] 2022-09-08 11:38
I'm closing this, because, at least in the particular instance described in this issue, the behavior is fixed with https://github.com/grafana/grafana/pull/54408.

**Closed** 2022-10-04 16:14 UTC
Labels: type/docs
