### ISSUE TITLE
Vertical scroll is hidden when horizontal scroll is visible in table panel

### ISSUE THREAD

**Issue by GrzegorzLyp** [grafana/grafana#26380] opened 2020-07-16 16:06 UTC
**What happened**: The table panel does not show vertical scroll when data is wide and horizontal scroll appears.

**What you expected to happen**: Vertical scroll should be always visible as the number of records exceeds height of panel.

**How to reproduce it (as minimally and precisely as possible)**: Create table panel with columns that are wide enough so the horizontal scroll appears. I use overrides for column 2 and 3 to create data link.

![image](https://user-images.githubusercontent.com/29247982/87694894-0bc60900-c78f-11ea-853a-579b25c15238.png)

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: MS SQL Server 2017
- OS Grafana is installed on: Windows 2016 Server
- User OS & Browser: Windows 10 2004, Google Chrome 84

**Comment by ivanahuckova** [comment] 2020-07-17 06:54
Thanks @ GrzegorzLyp for creating the issue. Yes, I was able to replicate this on [grafana.play](https://play.grafana.org/) as well.

**Comment by torkelo** [comment] 2020-07-17 18:45
duplicate of https://github.com/grafana/grafana/issues/25293

**Closed by torkelo** 2020-07-17 18:45 UTC
Labels: area/grafana/ui, area/panel/table
