### ISSUE TITLE
enable/disable annotations per panel

### ISSUE THREAD

**Issue by 3IMOH** [grafana/grafana#5490] opened 2016-07-01 16:30 UTC
- [x] Feature request

It would be nice to be able to specify an annotation as visible per panel. I have a dashboard with multiple charts and I want to show an annotation on one chart.

I could also see a use case where someone had multiple annotations defined and wanted to "target" different annotations on individual panels.

**Comment by torkelo** [comment] 2016-07-02 15:21
Duplicate of https://github.com/grafana/grafana/issues/717

**Closed by torkelo** 2016-07-02 15:21 UTC
