### ISSUE TITLE
Alerts on working hours

### ISSUE THREAD

**Issue by erikoffereins** [grafana/grafana#16611] opened 2019-04-16 07:23 UTC
**What would you like to be added**:
A possibility for grafana. So grafana only send alerts on working hours
**Why is this needed**:
We only need alerts on working hours but not in the evening or weekend

**Comment by torkelo** [comment] 2019-04-16 07:26
dupe of https://github.com/grafana/grafana/issues/6592

**Closed by torkelo** 2019-04-16 07:26 UTC
