### ISSUE TITLE
Too tedious to change copies of a panel

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20014] opened 2019-10-25 11:25 UTC
**What would you like to be added**:
Copies should be linked to a reference panel that when edited also update the copies

**Why is this needed**:
Scenario:
1. You realize you cannot use variables from playlists, and you cannot template screens.
2. So you make eight copies of your screen, one for each variable configuration.
3. And you edit each copy of your screen to set the variables and save it.
4. And then you realize that there was a typo in one panel.
5. So you go in and edit in eight different screens to fix that typo.
6. Then you realize that it doesn't look good on the TN panel, so you need to change a few colours to get better contrast.
7. So you do that on eight different copies, by the means of clicking in every pane, navigating through the point-n-click and then pressing.

Original discussion with context: https://news.ycombinator.com/item?id=21344459

**Comment by torkelo** [comment] 2019-10-25 11:27
duplicate of https://github.com/grafana/grafana/issues/1803

**Closed by torkelo** 2019-10-25 11:27 UTC
