### ISSUE TITLE
Error on Azure Container Instances: Migration failed err: database is locked

### ISSUE THREAD

**Issue by tgranqvist** [grafana/grafana#20549] opened 2019-11-21 09:45 UTC
**What happened**:
After creating and starting a container group with one container, grafana/grafana:6.4.4, the container shuts down and goes into a reboot loop. I mounted one volume via Azure File Share to /var/lib/grafana

The log gives me the following error:
t=2019-11-21T09:13:42+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: database is locked" 
More log output: [ACI.log](https://github.com/grafana/grafana/files/3873875/ACI.log)

Just to test write access to the volume, I installed some plugins via the environment variables. This works: I see the plugin directories and the log says OK. I also see the database and journal files on the volume, but they are bith 0 kb in size and the log errors out on the database.
 
**What you expected to happen**:
I expected the container to start and stay running, with the database created to the mounted volume.

**How to reproduce it (as minimally and precisely as possible)**:
Use the guide from here to create the instance: [Mount an Azure file share in Azure Container Instances], using the following Yaml file: [deploy-gvt.yaml.txt](https://github.com/grafana/grafana/files/3873936/deploy-gvt.yaml.txt)

**Anything else we need to know?**:
This has been on the forum: [Grafan with Azure File Share], no resolution so far. Supposedly this works with Azure Kubernetes Service, when [mounting the share] with following mount options:
```
   mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
```

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: not configured
- OS Grafana is installed on: Docker, grafana/grafana:6.4.4
- Grafana plugins: grafana-clock-panel, grafana-simple-json-datasource
- Others: I can provide access to my Azure instance for debugging if needed

[Mount an Azure file share in Azure Container Instances]: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files
[Grafan with Azure File Share]: https://community.grafana.com/t/grafan-with-azure-file-share/10949
[mounting the share]: https://docs.microsoft.com/bs-cyrl-ba/azure/aks/azure-files-dynamic-pv

**Comment by marefr** [comment] 2019-11-21 10:39
Duplicate of #16638

**Comment by marefr** [comment] 2019-11-21 10:40
Please try to switch to WAL mode in SQLite, see https://github.com/grafana/grafana/issues/16638#issuecomment-498811755, or switch to MySQL or Postgres.

**Closed by marefr** 2019-11-21 10:40 UTC

**Comment by tgranqvist** [comment] 2019-11-21 13:04
Thank you @marefr. Should I be able to override this using GV_ environment variables? At least this doesn't seem to work (in the YAML file):
```
environmentVariables:
  - name: GF_DATABASE_URL
    value: 'sqlite3://data/mygrafana.db?cache=private&mode=rwc&_journal_mode=WAL'
```
I see that the environment variable is used to override the setting, 
`t=2019-11-21T12:54:30+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_URL=sqlite3://data/grafana.db?cache=private&mode=rwc&_journal_mode=WAL"`

The database file is still the default name (grafana.db), and the same error shows up:

`t=2019-11-21T12:54:35+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: database is locked"`

**Comment by marefr** [comment] 2019-11-21 14:27
@tgranqvist should probably be:

```
GF_DATABASE_TYPE=sqlite3
GF_DATABASE_CONNECTION_STRING=file:data/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
```

**Comment by faarbaek** [comment] 2020-01-31 10:47
You cannot set the connection string using GF_DATABASE_CONNECTION_STRING. Just tried it, but the logs does not mention that the setting is replaced.

@tgranqvist did you evet get Grafana to work in ACI with Azure File Share? I had the same issue, but switched to App Services which supported blob storage - but unfortunately this support ends in 2 days (after which it becomes read-only). So I really need Grafana to work with Azure File Share.

**Comment by yaroshevichd** [comment] 2020-01-31 13:57
@faarbaek the following worked for me:
1. enable WAL (as described here https://github.com/grafana/grafana/issues/16638#issuecomment-498811755)
2. specify GF_DATABASE_URL in the form of 'sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL' (where '/var/lib/grafana/grafana.db' is path in my environment, so may be something other for you). I believe that in reality only last part is acually essential '_journal_mode=WAL', but URL have to be fully qualified

**Comment by faarbaek** [comment] 2020-02-02 19:06
> @faarbaek the following worked for me:
> 
> 1. enable WAL (as described here [#16638 (comment)](https://github.com/grafana/grafana/issues/16638#issuecomment-498811755))
> 2. specify GF_DATABASE_URL in the form of 'sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL' (where '/var/lib/grafana/grafana.db' is path in my environment, so may be something other for you). I believe that in reality only last part is acually essential '_journal_mode=WAL', but URL have to be fully qualified

Thanks - Works like a charm. This really saved my day 😊

**Comment by stmax82** [comment] 2020-02-07 15:27
I can't seem to get grafana running in an Azure Container Instance with persistent storage, no matter what I try it results in "database is locked".

I'm starting the container like that (in PowerShell mit Azure CLI):

```
az container create -g $resourceGroup -n $grafanaContainerGroupName `
                    -e 'GF_DATABASE_URL="sqlite3:///var/lib/grafana/grafana42.db?cache=private&mode=rwc&_journal_mode=WAL"' `
                    --image grafana/grafana:latest `
                    --cpu 1 --memory 2 `
                    --location $location `
                    --os-type Linux `
                    --ip-address Public `
                    --restart-policy Never `
                    --azure-file-volume-account-name $storageAccountName `
                    --azure-file-volume-account-key $storageKey `
                    --azure-file-volume-share-name $grafanaDataShareName `
                    --azure-file-volume-mount-path "/var/lib/grafana" `
                    --ports 3000
```

Checking the logs with:

```
az container logs -g $resourceGroup -n $grafanaContainerGroupName
```
shows:
```
msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_URL=sqlite3:///var/lib/grafana/grafana42.db?cache=private&mode=rwc&_journal_mode=WAL"
```
... so it seems to have accepted my environment variable.

But then at the bottom:
```
msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: database is locked"
```

Any ideas what I'm doing wrong? Thanks.

**Comment by faarbaek** [comment] 2020-02-07 22:00
> I can't seem to get grafana running in an Azure Container Instance with persistent storage, no matter what I try it results in "database is locked".
> 
> I'm starting the container like that (in PowerShell mit Azure CLI):
> 
> ```
> az container create -g $resourceGroup -n $grafanaContainerGroupName `
>                     -e 'GF_DATABASE_URL="sqlite3:///var/lib/grafana/grafana42.db?cache=private&mode=rwc&_journal_mode=WAL"' `
>                     --image grafana/grafana:latest `
>                     --cpu 1 --memory 2 `
>                     --location $location `
>                     --os-type Linux `
>                     --ip-address Public `
>                     --restart-policy Never `
>                     --azure-file-volume-account-name $storageAccountName `
>                     --azure-file-volume-account-key $storageKey `
>                     --azure-file-volume-share-name $grafanaDataShareName `
>                     --azure-file-volume-mount-path "/var/lib/grafana" `
>                     --ports 3000
> ```
> 
> Checking the logs with:
> 
> ```
> az container logs -g $resourceGroup -n $grafanaContainerGroupName
> ```
> 
> shows:
> 
> ```
> msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_URL=sqlite3:///var/lib/grafana/grafana42.db?cache=private&mode=rwc&_journal_mode=WAL"
> ```
> 
> ... so it seems to have accepted my environment variable.
> 
> But then at the bottom:
> 
> ```
> msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: database is locked"
> ```
> 
> Any ideas what I'm doing wrong? Thanks.

Did you change journal mode in the SQLite DB as mentioned in this comment: https://github.com/grafana/grafana/issues/16638#issuecomment-498811755

**Comment by dylandragon93** [comment] 2020-02-11 15:49
@faarbaek it sounds like you got this working on a container in Azure App Service, yes? I have the same problem as @stmax82, and it's because I haven't done step 1 in @yaroshevichd's solution. How did you run the pragma statement `PRAGMA journal_mode=wal;` within the AAS container? You running it as a startup file within the app service?

**Comment by stmax82** [comment] 2020-02-11 15:55
@faarbaek @dylandragon93 I got it to work by now.. it's ugly but works. I manually created an empty sqlite db and ran PRAGMA journal_mode=wal; on it once. Now I always automatically copy that file to the azure file share (using az storage copy) before I start grafana for the first time.

Couldn't grafana enable WAL journaling mode so it would work out of the box again with file shares? Would that cause any other problems?

**Comment by dylandragon93** [comment] 2020-02-11 21:18
@stmax82 thanks for following up, that did the trick. My use case was pretty specific, as we couldn't use an IaaS VM, MySQL, nor AKS. So the only options were to use ACI or a single container/Docker Compose on Azure App Service. For anyone trying to do something similar, here's a breakdown of what worked for me:

Deploy a single container (the newest Alpine Linux version from Docker Hub) Grafana instance to Azure App Service with persistent storage via Azure File Service:

* Create a storage account (I used general purpose v2) and ensure the `Firewalls and virtual networks` settings allow your app to connect. For example, if deploying within an App Service Environment, there will be additional security settings for the ASE.
* As blob storage is read-only now, you must create a file share in the service account.
* Install SQLite locally and upload an empty DB with a WAL journal mode (PowerShell):
  ```PowerShell
  choco install sqlite
  sqlite3 grafana.db 'pragma journal__mode=wal;'
  az storage copy -s .\grafana.db -d https://<storage_account>.file.core.windows.net/<file_share> --subscription <subscription_name>
  ```
* Create an Azure App Service that deploys a container on Linux and uses Docker Hub as the image source.
* Add key/value pair to the application settings: `GF_DATABASE_URL` = `sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL` (might not need the `cache=private&` portion because the cache is private by [default](https://grafana.com/docs/grafana/latest/installation/configuration/#cache-mode)).
* Add a path mapping with a mount path of `/var/lib/grafana` to the app.
  * In Azure Portal this is `App Services` > `<app_name>` > `Settings` > `Configuration` > `Path mappings` > `New Azure Storage Mount`.

At this point the app should start without database locking. Here are some good sources you can use for clarification on any of the above steps and how to hook up the app to Azure Active Directory:

* https://www.phillipsj.net/posts/an-easy-grafana-setup-using-azure-app-service-for-linux/
* https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-serve-content-from-azure-storage
* https://grafana.com/docs/grafana/latest/auth/generic-oauth/#set-up-oauth2-with-azure-active-directory
* https://chocolatey.org/install (for the `choco install sqlite` command)

If you want to back up more than `/var/lib/grafana`, you could also configure multiple mount points (currently up to 5 per app service) for the different [default paths](https://grafana.com/docs/grafana/latest/installation/configure-docker/#default-paths) that Grafana uses.

@stmax82 this is less of a Grafana problem and more of an Azure one. AFAIK there's nothing wrong with the default journal mode they've chosen to use (which seems to be a divisive topic on its own), rather it's Azure's problem for making blob container storage mounts read-only before offering more robust support for file share mounts (e.g. mount options like in AKS). Given our particular requirements, I think what we've done is a good solution until Microsoft can make the storage mounts better.

**Comment by HueGeneSymphony** [comment] 2020-03-24 22:00
@dylandragon93 
To expand on your post. I'm running a prometheus-operator grafana image in kubernetes that also uses Azure File Share, and I'm on MacOS using terminal instead of PowerShell. The steps I used are similar but a few changes are necessary.

Prometheus Operator Configuration
```
grafana:
  'grafana.ini':
    database:
      url: sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
  persistence:
    enabled: true
    existingClaim: # your volume claim
```

Generate grafana database somewhere on your local filesystem.
The file should be about 4K after generation.
** note capital PRAGMA and 1 underscore instead of 2, this is different from @dylandragon93 
```
sqlite3 grafana.db 'PRAGMA journal_mode=wal;'
```

I then manually uploaded this file to the file share through the Azure Portal, but the command he used is probably fine. Deploy prometheus operator and your good.

**Comment by muzammil360** [comment] 2020-05-17 11:41
I also ran into the exact same issue. @yaroshevichd, @faarbaek, @stmax82, @dylandragon93 and @HueGeneSymphony saved the day in a combined effort. 

Make sure you do make `grafana.db` locally and upload it at the mounted path. For making the file locally, use the following command shared by @HueGeneSymphony which is 
```
sqlite3 grafana.db 'PRAGMA journal_mode=wal;'
```

This is different from the one shared by @dylandragon93 as that command produces an empty file of 0 bytes.

Anyways, thanks a lot to all the guys above for saving the day.

**Comment by HueGeneSymphony** [comment] 2020-05-18 14:02
@muzammil360 are you using this for prometheus?

I hate to be the bearer of bad news, but we had to change our DB setup after about a week due to a non-recoverable corruption issue. If you are using prometheus with azure file share, you will most likely run into this same issue. I don't know if this affects grafana.

Azure File Share is not POSIX compliant, an issue discussed further in this thread:
https://groups.google.com/d/msg/prometheus-users/_RoZXYcSwpM/N_23OFkJCQAJ

We moved to using Persistent Azure Disks and also backup to a Container on an Azure Storage Account using Thanos. This combination has been working well for us and we were able to up the number of prometheus replicas and reduce retention time of prometheus instances while leaving the Thanos backup for permanent LT storage.

If you are using Azure File Share for your DB I highly recommend you go ahead and jump to Azure Disks now.

**Comment by muzammil360** [comment] 2020-05-18 16:48
@HueGeneSymphony, yes I am using azure file share with prometheus as well. Thanks a lot for sharing this information. Will look more into it.

**Comment by kaisert** [comment] 2020-07-07 14:03
@muzammil360 's solution did not work for me (although it improved the frequency a bit)

Grafana randomly logs out and only shows its error page. In the logs it says

2020-07-07T02:04:03.442792383Z t=2020-07-07T02:04:03+0000 lvl=info msg="Database locked, sleeping then retrying" logger=sqlstore error="database is locked" retry=8166

Restarting the container brings back Grafana for a while.
Using Grafana 7.0.5 docker image deployed as an app service on azure. /var/lib/grafana is connected to a file share.
GF_DATABASE_URL is set to sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL

**Comment by phillipsj** [comment] 2020-10-02 00:41
Yeah none of these really work. Even trying the persistent storage option, which must be backed by Azure Files, doesn't work either. I have updated my post about it and I am going to provide an alternative way to create backups which offer an alternative. https://www.phillipsj.net/posts/update-easy-grafana-on-azure/

**Comment by davidxcheng** [comment] 2021-01-29 13:33
If anyone else ends up switching form Azure File to Azure Disk after reading @HueGeneSymphony s comment and is getting an error saying that the path to your mount "is not writable", try adding this to your deployment yaml:

```yml
securityContext:
  runAsUser: 472
  fsGroup: 472
```

For reasons explained [here](https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later)

**Comment by navpreet-securitas** [comment] 2022-02-21 17:29
I encountered same problem while running in AKS with azure files : 
` Migration failed err: database is locked"`

but then using custom NFS based storageClass : 

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
```
this got fixed.

addin to @HueGeneSymphony :  azure docs says nfs is POSIX compliant.  (https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#nfs-file-shares)

**Comment by dvidben** [comment] 2022-02-24 18:24
> @muzammil360 are you using this for prometheus?
> 
> I hate to be the bearer of bad news, but we had to change our DB setup after about a week due to a non-recoverable corruption issue. If you are using prometheus with azure file share, you will most likely run into this same issue. I don't know if this affects grafana.
> 
> Azure File Share is not POSIX compliant, an issue discussed further in this thread: https://groups.google.com/d/msg/prometheus-users/_RoZXYcSwpM/N_23OFkJCQAJ
> 
> We moved to using Persistent Azure Disks and also backup to a Container on an Azure Storage Account using Thanos. This combination has been working well for us and we were able to up the number of prometheus replicas and reduce retention time of prometheus instances while leaving the Thanos backup for permanent LT storage.
> 
> If you are using Azure File Share for your DB I highly recommend you go ahead and jump to Azure Disks now.

I definitely agree with @HueGeneSymphony. 
According to Microsoft, AzureFiles should only be used for shared configuration. We have also seen the "database is locked" for installs using AzureFiles

**Comment by easonboy** [comment] 2022-07-26 03:53
It's ok  thaks!

**Comment by easonboy** [comment] 2022-07-26 03:54
> 我在使用 azure 文件的 AKS 中运行时遇到了同样的问题： ` Migration failed err: database is locked"`
> 
> 使用基于 NFS 的但自定义存储类：
> 
> ```
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   name: azurefile-csi-nfs
> provisioner: file.csi.azure.com
> parameters:
>   protocol: nfs
> ```
> 
> 这得到了修复。
> 
> 添加到@HueGeneSymphony: azure 说 nfs 是 POSIX 三年级的。（[https://docs.microsoft.com/en-docs/azure/aks/azure-files-csi#nfs-file-shares](https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#nfs-file-shares)）
it's ok ,thanks~~
