### ISSUE TITLE
kWh units change to fWh when value is 0 in 9.0.0

### ISSUE THREAD

**Issue by NosIreland** [grafana/grafana#50846] opened 2022-06-15 08:29 UTC
**What happened**:
After upgrading to 9.0.0 the kWh units changed to fWh when value is 0. This is seen on Gauge and Stat panels
![image](https://user-images.githubusercontent.com/19308746/173779869-4fdc8a50-654b-4c76-ab2f-3464e46f4d85.png)
![image](https://user-images.githubusercontent.com/19308746/173780213-afbe71c7-15a2-4182-b44f-4148a7c51ba7.png)

**What you expected to happen**:
The unit should not change and stay as kWh

**How to reproduce it (as minimally and precisely as possible)**:
Use version 9.0.0 with stat or gauge panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Running as conteiner
- User OS & Browser: Win10 Firefox/Edge/Chrome
- Grafana plugins: na
- Others:

**Comment by sakjur** [comment] 2022-06-15 09:41
It sounds like an unintended side-effect of #50117 (cc @kaydelaney), the SI-prefixed units automatically scale depending on their values, so that 0.001kWh could be the slightly more useful 1Wh, but it looks like 0.0 is converted to the smallest supported unit (femto, i.e. _f_), which seems wrong.

The zero value would likely best be presented in either its SI base unit (which if parsed strictly ends up being somewhat complicated since kilogram is the base unit for mass rather than grams, so `0.00 kg` would be more correct than `0.00 g`) or, as you're suggesting, in the unit that 1.0 would be represented as (i.e. what's selected in the unit dropdown).

I guess it's a matter of adding a special case doing something like setting the `siIndex` to `0` for literal zero values to the `scaledUnits` function and a test case for a scaled zero value in _valueFormats.test.ts_.

https://github.com/grafana/grafana/blob/a9a276a9dae50e04b8b823fff43ca998b8e3110a/packages/grafana-data/src/valueFormats/valueFormats.ts#L136-L154

https://github.com/grafana/grafana/blob/a9a276a9dae50e04b8b823fff43ca998b8e3110a/packages/grafana-data/src/valueFormats/symbolFormatters.ts#L37-L40

**Comment by daniellee** [comment] 2022-06-15 09:49
Looks like a duplicate of https://github.com/grafana/grafana/issues/50672 

There is already a fix that will be included in 9.0.1: https://github.com/grafana/grafana/pull/50719

Closing as duplicate and thanks for the quick report!

**Closed by daniellee** 2022-06-15 09:49 UTC
Labels: type/bug, type/duplicate, effort/small, help wanted, beginner friendly, area/units

**Comment by sakjur** [comment] 2022-06-17 06:24
@torkelo This problem statement specifically states “when value is 0”. That’s an edge case and it makes sense that it specifically is treated to no conversion of units, since 0 is the same regardless of prefix. 

I think you’re considering the wider picture for values such as 0.75, and I think the problem there is that there are multiple correct answers: some will want that as kWh regardless. Others think 750Wh is a better response. Someone might want Joule or calories back (let’s hope not) 🙃

While I’m not sure I prefer the new Grafana 9 rounding to the old Grafana 8 rounding, I think the fundamental problem lies in the units being represented only as “in” and never as “out”. If I would’ve had the TS skills to do it, I’d like to build a system where when you pick kWh as your unit, you also get to pick how you want it displayed, maybe a radio option between “always use kWh | scale with SI prefix“.

We could later expand on that and allow more complex scaling options (0.15kWh is reasonably equivalent to 150Wh in legibility, but between 0.00001kWh and 10mWh the latter is likely preferable) and common-but-icky conversions for some units (hello °F and °C)— but just allowing “static out” and “SI prefix’d out” will resolve the problem for a bunch of people who now have to resort to custom units. WDYT?
