### ISSUE TITLE
when  I am trying to import grafana dashboard on my web site in Iframe if is not showing right side date filter.it shows before the whole page loaded but when page is loaded is it disappear.

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#27207] opened 2020-08-26 05:33 UTC
**What happened**:Date filter is not showing on my web site in Iframe.

**What you expected to happen**:Date filter should be show

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:laptop
- Grafana version:6.2..O(beta version)
- Data source type & version:sql server 2017
- OS Grafana is installed on:Windows
- User OS & Browser:Chrome
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment] 2020-08-31 09:05
@karamjeetkaurpreeti would be great if you could provide better reproducible steps with images or animation. Thank you!

**Comment by hugohaggmark** [comment] 2020-08-31 13:41
@karamjeetkaurpreeti have you looked at these Grafana ini values?
allow_embedding: true
cookie_samesite: none

**Comment by hugohaggmark** [comment] 2020-09-04 06:00
I'm going to close this issue for now because we've not received any feedback to our initial questions. If reporter supplies more proof in this issue, we'll of course reopen it.

All the best

**Closed by hugohaggmark** 2020-09-04 06:00 UTC
Labels: needs more detail
