### ISSUE TITLE
Bring back "Transform: negative-Y" to new "Time Series panel"

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#35628] opened 2021-06-14 10:51 UTC
**What would you like to be added**:

see for yourself - which one looks better and easier to look at.
![image](https://user-images.githubusercontent.com/5955795/121881139-82f57b80-cd17-11eb-8be1-bfec3f4297c9.png)

**Why is this needed**:

It makes more sense to display network activity using "Transform: negative-Y" approach as this is de facto standard way to visualize network throughput.

**Comment by torkelo** [comment] 2021-06-14 11:14
duplicate of https://github.com/grafana/grafana/issues/30365

**Closed by torkelo** 2021-06-14 11:14 UTC
