### ISSUE TITLE
Expose Grafana internal metrics on a different port

### ISSUE THREAD

**Issue by MatonAnthony** [grafana/grafana#31356] opened 2021-02-19 15:48 UTC
I would like to be able to expose the Grafana internal metrics (see: [Internal Grafana metrics](https://grafana.com/docs/grafana/latest/administration/view-server/internal-metrics/#internal-grafana-metrics)) on a port different that the one exposes to the rest of the world.

We have a standardized metrics pipeline that requires us to use a separated port for technical metrics than the port exposed the outside world.

This does not appear to be possible with Grafana.

Would you accept a contribution to add this possibility? 

I would add an option in `grafana.ini` with the port.

```ini
# Metrics available at HTTP API Url /metrics
[metrics]
# Disable / Enable internal metrics
enabled           = true

# Disable total stats (stat_totals_*) metrics to be generated
disable_total_stats = false

## New addition
# Choose the port on which the metrics are published
port = 3000
```

**Comment by ivanahuckova** [comment] 2021-02-24 12:59
@grafana/backend-platform Would we accept contribution to add option to config file to choose the port on which the metrics are published?

**Comment by ivanahuckova** [comment] 2021-02-24 13:03
Also this seems to be related/same as this closed issue https://github.com/grafana/grafana/issues/17987

**Comment by marefr** [comment] 2021-03-08 09:41
Duplicate of #17987

**Comment by marefr** [comment] 2021-03-08 09:42
In addition to comment in #17987 you can also enable basic authentication for the metrics endpoint

**Closed by marefr** 2021-03-08 09:42 UTC
Labels: area/backend, area/configuration, type/feature-request

**Comment by MatonAnthony** [comment] 2021-03-08 10:17
I do not believe using Nginx as a generic solution or any other reverse proxy for that matter is the best way to resolve my issue.

But thank you for the clear stance on this enhancement request.
I will look towards other solutions, that do not involve making any change to the Grafana codebase.

**Comment by cannonpalms** [comment] 2024-04-24 18:34
Sorry for grave-digging a 3-year-old thread, but considering that the disagreement at hand is over whether or not this issue was closed prematurely, I'm going to stick to this issue rather than creating Yet Another Issue.

---------------

I wholeheartedly agree with @MatonAnthony . It is almost table-stakes at this point to be able to configure the bind address/port of metrics. Suggesting that users deploy a full-featured reverse proxy is a very silly workaround. 

Is there a reason that it would be prohibitively difficult to support such config files/args/vars? Can an internal contributor please lay out a plan of attack so that someone in the community (I volunteer!) can implement what, on the surface, looks extremely simple?

**Comment by hanumanhuda** [comment] 2024-09-17 08:54
Is there solution to this problem? because this is critical problem as metrics endpoint could have internal information, which are revealed publicly. Also for nginx case, not every deployment has nginx fronting the Grafana, Can we quick configuration to have separate port?
