### ISSUE TITLE
Email alerting failure

### ISSUE THREAD

**Issue by tatric** [grafana/grafana#15756] opened 2019-03-04 12:23 UTC
Version 6.0.0 (commit: 34a9a62, branch: HEAD)
Postgres and Mssql
Ubuntu 18.04 
Setup email alerting; notification Channel
send test email 
### What happened instead?
WUI said email sent (twice while pressed test email once) green box top right, but email never recived. Checked logs shows error:
> "t=2019-03-04T11:57:21+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[our.email.address@mail.net]
 t=2019-03-04T11:57:26+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF
 t=2019-03-04T11:57:26+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid= error=EOF”
Alerts have been set up, No mails have ever been received. We are using our own mail server that is we are au fait with adding software to email via.
We are using smtp without authentication 

[smtp]
enabled = true
host = 192.168.81.74:25
user = our.email.address @mail.net
from_address = our.email.address @mail.net
skip_verifiy = true

**Comment by marefr** [comment] 2019-03-04 12:36
Duplicate of #7116

**Comment by marefr** [comment] 2019-03-04 12:36
Duplicate of #13041

**Closed** 2019-03-04 12:36 UTC

**Comment by tatric** [comment] 2019-03-04 14:18
Why does it say its sent an email Successfully in the GUI but failed in the logs? Should it not say in the GUI when pressing the test button that the email has failed!  So I believe there to be an issue with the test button.
I know the email server is working.

I don't know what the error message means, EOF I assume End OF File, but shouldn't this be set to a valid test email to send?

I have looked at the other two tickets; I don't know how they apply to me and what the fix was.

**Comment by marefr** [comment] 2019-03-08 12:38
@tatric Emails are sent asynchronously so that's why you're not receiving an error in the UI. EOF usually means that the server is closing the connection or you cannot connect to your email server.

This https://github.com/grafana/grafana/issues/7116#issuecomment-403163594 for example is worth a try. Here's another one https://github.com/grafana/grafana/issues/13041#issuecomment-416557021
