### ISSUE TITLE
Grafana 8: Change the Prometheus data source to POST by default

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#34535] opened 2021-05-20 21:36 UTC
**What would you like to be added**:

I would like the default HTTP method for the Prometheus data source to be changed from GET to POST.

**Why is this needed**:

The POST API's of Prometheus are there since January 2018 (Prometheus 2.1.0). They have less limitations than the GET API's (e.g. when dealing with high cardinality labels, GET hits the URL size limit).

This seems the right time to do this as we are bumping grafana to a new major release number.

**Comment by SeanTse** [comment] 2021-05-24 02:47
Are you looking for this? [issue-504736828](https://github.com/grafana/grafana/issues/19731#issue-504736828)

**Comment by marefr** [comment] 2021-05-24 07:51
Duplicate of #30837

**Comment by marefr** [comment] 2021-05-24 07:51
Available since v7.5.

**Comment by ivanahuckova** [comment] 2021-05-24 07:58
In https://github.com/grafana/grafana/pull/31292 for newly set up data source instances we've defaultly set their method to POST. But 8.0.0 is probably a good time to switch default (non-selected) option to POST.

**Closed** 2021-05-25 16:56 UTC
Labels: datasource/Prometheus, type/feature-request
