### ISSUE TITLE
More alert rules condition

### ISSUE THREAD

**Issue by Kevinsss** [grafana/grafana#13332] opened 2018-09-19 04:19 UTC
Hi.
Now the alert rules will be executed at all times. It would be great to add a time range condition , while only the current time is in the time range, the alert rules can be executed. For example, I want to alerts send  notification from 8:00 am to 8:00 pm, if current time is not at this range,  do not send notification.

what's more,  this is useful if grafana add some query conditions to compare with different series, like  `A-B > 100`, `A / B <= 10%` ........

Thank you.

**Comment by torkelo** [comment] 2018-09-19 07:48
closing this, duplicate of https://github.com/grafana/grafana/issues/6592

**Closed by torkelo** 2018-09-19 07:48 UTC
