### ISSUE TITLE
[Bug] Description tooltip

### ISSUE THREAD

**Issue by stychu** [grafana/grafana#8478] opened 2017-05-26 11:09 UTC
Those panels that are to the right of the edge are getting cut.
Also icon for displaying the description tooltip is very hard to see I'd suggest some changes to positioning and colours  and directions for tooltip.

![image](https://cloud.githubusercontent.com/assets/9383657/26492368/fe2e60c0-4213-11e7-8139-9245bd8f95e5.png)

**Comment by daniellee** [comment] 2017-05-26 12:22
What version of Grafana are you using? This looks like a duplicate of #7970

**Comment by torkelo** [comment] 2017-05-26 12:26
please upgrade to Grafana 4.3.1

**Closed by torkelo** 2017-05-26 12:26 UTC
Labels: state: needs more detail
