### ISSUE TITLE
 Building on macOS Big Sur

### ISSUE THREAD

**Issue by krvajal** [grafana/grafana#29121] opened 2020-11-14 21:13 UTC
I just installed macOS Big Sur and I can not build grafana anymore. 
When running `make run` I get the following error
```
[Bra] 11-14 22:12:49 [FATAL] Fail to watch directory($WORKDIR/pkg/tsdb): bad file descriptor
make: *** [run] Error 1
Version: 7.4.0-pre, Linux Version: 7.4.0, Package Iteration: 1605388370pre
go build -ldflags -w -X main.version=7.4.0-pre -X main.commit=e503188b6f -X main.buildstamp=1605270103 -X main.buildBranch=master -o ./bin/grafana-cli ./pkg/cmd/grafana-cli
```

Any ideas how to fix this?

**Comment by aknuds1** [comment] 2020-11-15 09:58
I'm on Big Sur, and I can build Grafana without any issues. I just tried `make run` and Grafana gets launched as per usual.

I've got Go version 1.15.5:

```
$ go version
go version go1.15.5 darwin/amd64
```

**Comment by aknuds1** [comment] 2020-11-15 10:07
From your error message it looks as if you have an error in the [bra](https://github.com/unknwon/bra) tool.

You can try upgrading it to see if it helps:

```
pushd scripts/go
go get -u github.com/unknwon/bra
popd
rm scripts/go/bin/bra
make run
```

If you still have problems after upgrading bra, I suggest you file an issue with that project.

Closing the issue for now, since I can't reproduce and it's not a Grafana bug. If you need further support, I suggest using our community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io).

**Closed by aknuds1** 2020-11-15 10:07 UTC

**Comment by oshopgiri** [comment] 2020-11-17 15:51
Running `ulimit -S -n 2048` fixed this error for me. I'm on macOS Big Sur with Go version 1.15.5.

**Comment by krvajal** [comment] 2020-11-17 16:11
I can't believe it. Thanks, man, it works

**Comment by MatinWood** [comment] 2020-12-26 06:21
> Running `ulimit -S -n 2048` fixed this error for me. I'm on macOS Big Sur with Go version 1.15.5.

Thanks man, it works

**Comment by DavidMarom** [comment] 2022-02-16 17:06
Same problem, the above does not work for me

**Comment by DavidMarom** [comment] 2022-02-16 20:36
This worked for me:
`source ~/.zshrc`

**Comment by bitzhuxb** [comment] 2022-08-09 07:41
ulimit S -n  4096 fixed this error. 
goversion 1.7 
macos11.4 
grafana :v8.5.9
