### ISSUE TITLE
Dashboard import do not work if the dashboard uses datasource template parameters

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#6385] opened 2016-10-26 10:13 UTC
- [ x] Bug report for Grafana 3.1

We use a datasource template variable on almost all our dashboards. To copy an existing dashboard we currently export it to a file and then import it again and change the title. 

Since Grafana 3.1 (introducing the dashboard export to Grafana net feature) a wizard pops up when importing a dashboard. You MUST supply on existing dashboard, otherwise the dashboard cannot be saved. The chosen datasource however overwrites the datasource template parameter on all our panels and they have to be corrected again by hand. I would expect the import wizard does not overwrite template parameters in the datasource selector of the panels.

If you import a dashboard with --Mixed-- datasources it is not even possible to import a dashboard.
The JSON load function is also not working (if you dump an exported json file content in it)

An "fallback" import function (of Grafana <3.1) would be appreciated.

**Comment by torkelo** [comment] 2016-10-26 11:53
dupe of https://github.com/grafana/grafana/issues/6189

**Closed by torkelo** 2016-10-26 11:53 UTC
