### ISSUE TITLE
[Bug] WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by warmfusion** [grafana/grafana#6850] opened 2016-12-06 14:20 UTC
Please include this information:
- What Grafana version are you using?
    - 4.0.1
- What datasource are you using?
    - N/A - Happens on homepage - [Graphite, Elasticsearch]
- What OS are you running grafana on?
    - Debian Wheezy
- What did you do?
    - Open any pages on site
- What was the expected result?
    - Page displayed without errors or code chunks
- What happened instead?
    - Page displays large amounts of configuration text
    - Console reports a javascript warning:
       `boot.fdf40765.js:41 WARNING: Tried to load angular more than once.`

The screenshot below shows the graphical errors  - Note that I have scrolled down past alot of the output from the window to show the top of the dashboard is being displayed once you get past the text output.

![screen shot 2016-12-06 at 2 19 19 pm](https://cloud.githubusercontent.com/assets/2294568/20928724/0b675a16-bbbf-11e6-9a3f-7ae93a04c418.png)

**Comment by torkelo** [comment] 2016-12-06 14:28
do you have any plugins installed?

**Comment by warmfusion** [comment] 2016-12-06 15:01
Ah yes; sorry.

here are the plugins;

```
$ grafana-cli plugins ls
installed plugins:
grafana-piechart-panel @ 1.1.4
grafana-worldmap-panel @ 0.0.16
jdbranham-diagram-panel @ 1.3.0
```

**Comment by torkelo** [comment] 2016-12-06 15:24
cant replicate with those plugins. Do you have any proxy infront of grafana?

**Comment by warmfusion** [comment] 2016-12-06 15:31
Yes, we run a HAProxy balancer with configuration as follows;

```
global
        nbproc 1
        log 127.0.0.1   local0
        log 127.0.0.1   local1 notice
        maxconn 4096
        user haproxy
        group haproxy
        #daemon
        debug
        #quiet
        tune.ssl.default-dh-param 2048

defaults
        log     global
        mode    http
        option  tcplog
        option  dontlognull
        option redispatch
        retries 3
        maxconn 2000
        timeout connect      5000
        timeout client      50000
        timeout server      50000

frontend http-in

            bind 0.0.0.0:80

            mode http

            option httplog
            option forwardfor
            option dontlognull
            option logasap

            acl grafana hdr_reg(host) -i ^grafana.priv.example.org
            capture request header origin len 128
            http-response add-header Access-Control-Allow-Origin %[capture.req.hdr(0)] if { capture.req.hdr(0) -m found }
            rspadd Access-Control-Allow-Headers:\ Origin,\ X-Requested-With,\ Content-Type,\ Accept  if { capture.req.hdr(0) -m found }
            use_backend grafana if grafana

    backend grafana
            balance roundrobin
            option httpchk GET /
                    server localhost :::3000 check inter 30000 rise 2 fall 3 maxconn 4096
```

**Comment by torkelo** [comment] 2016-12-06 22:16
Try going directly to grafana, and bypass haproxy.  Must  be something wrong with the proxy

**Comment by warmfusion** [comment] 2016-12-07 10:24
Nope.

Note; It doesn't seem to happen everytime, and it does appear to be slightly harder to reproduce when going direct. Refreshing often fixes the issue, but them sometimes it just sticks around.

The following shows my connecting directly to our grafana server on port 3000, bypassing the haproxy and going directly to the source.

![grafana_-_cdn_monitoring](https://cloud.githubusercontent.com/assets/2294568/20963881/2cd2caa2-bc67-11e6-8685-920a64c4b96f.png)

**Comment by warmfusion** [comment] 2016-12-07 11:39
@torkelo  - Please reopen this issue; Heres any other information i can think of;

* Upgraded from a 3.x release
* Local SQLIte.db for its storage

Grafana configuration as shown;

```
/etc/grafana# cat grafana.ini
### MANAGED BY PUPPET ###
[server]
domain = grafana.priv.example.org
root_url = %(protocol)s://%(domain)s/
enable_gzip = true
[analytics]
reporting_enabled = false
[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_role = editor
[auth.anonymous]
enabled = true
org_role = Viewer
org_name = Example org
[auth.google]
enabled = true
client_id = REDACTED.apps.googleusercontent.com
client_secret = REDACTED
allow_sign_up = true
```

**Comment by torkelo** [comment] 2016-12-07 13:08
could you disable gzip and see if that makes a difference?

**Comment by torkelo** [comment] 2016-12-07 13:09
your browser has warning icon in the address field. 

Also can you disable all extensions (try incognito mode)

**Comment by warmfusion** [comment] 2016-12-08 14:45
howdy, I've got a screenshot from a Firefox browser session with the same outcome, and I've included (although its small) the full chunk of text output as shown in the element inspector.

The Warning is due to my activating the 'warn if not https'  on chrome.
I have no plugins or extensions on firefox.
The same occurs when using Privacy Mode.

![screenshot_12_8_16__2_37_pm](https://cloud.githubusercontent.com/assets/2294568/21014083/7598e508-bd54-11e6-8904-74b75de00976.png)

**Comment by torkelo** [comment] 2016-12-08 15:02
Strange, no idea what's going on. Something is making the response corrupt :( 

No one else has reported anything similar so have very little to go in terms of helping you solve this :+1: (

Maybe if you did a curl of the root grafana address and save the html and pasted that in a gist?

**Comment by warmfusion** [comment] 2016-12-08 15:05
Like so;
https://gist.github.com/warmfusion/41db471fe09d273c367b38718b483497

**Comment by torkelo** [comment] 2016-12-12 14:30
No idea what's going on, something is making the response corrupt, must be some proxy or something between your browser and grafana. Grafana's response is clean but the one you see in your browser looks broken up :(

**Comment by warmfusion** [comment] 2016-12-12 15:01
Thanks for looking. Its not a proxy - as outlined by the screenshot above with :3000 
Its affecting multiple users, multiple browsers (including mobile) and so I guess I'll have to debug it myself.

⚠️  This is not a resolved issue. :-1:

**Comment by torkelo** [comment] 2016-12-12 15:05
Sorry, I can open it again, but since your the one one having a corrupt response I suspect it's a network / http proxy issue I am not sure how I can help you troubleshoot it more :(

**Comment by torkelo** [comment] 2016-12-12 15:06
How many elasticsearch data sources have you added?

**Comment by torkelo** [comment] 2016-12-20 10:28
closing this, please let me know if you find anything that you feel is a bug in Grafana

**Closed by torkelo** 2016-12-20 10:28 UTC
Labels: state: needs more detail, type: bug

**Comment by macb** [comment] 2017-06-09 21:51
fwiw we're also running into this issue on 4.x (I think 4.1). the initial response seems to include the bottom portion of a (previous?) request. While we do use a proxy in front of grafana I'm pretty hesitant to point the finger at nginx as its just forwarding the http body from the grafana instance.

middle portion of the partial script truncated for sanity, but here is the top part of the http response on initial request. after the `<html lang="en">` below the response body seems reasonably formatted.
```
:null,"logos":..........
		};
	</script>

	<script src="/public/app/boot.5ee7468a.js"></script>

	

	</body>
</html>
<!DOCTYPE html>
<html lang="en">
......
```

**Comment by torkelo** [comment] 2017-06-10 06:31
Looks like an issue with a reverse proxy or http proxy between grafana and your browser

**Comment by macb** [comment] 2017-06-11 06:24
@torkelo no, i don't believe that's the case. the proxy between grafana and the browser serves dozens of other services handling hundreds of requests per second as well without similar issues. if it were causing issue why would the concatenated data look similar to grafana itself and not be from other service requests as well?

**Comment by torkelo** [comment] 2017-06-11 07:33
Not sure, something is mangling the response. We have a similar report a year ago, also caused  the proxy

**Comment by macb** [comment] 2017-06-12 01:07
@torkelo as far as I can tell that was not resolved, in fact the user eliminated the proxy and was still able to reproduce.

https://github.com/grafana/grafana/issues/6850#issuecomment-266452793

**Comment by torkelo** [comment] 2017-06-12 04:46
Just because he ran port 3000 does not mean there is no proxy. 

What are you grafana.ini settings? Especially the Server section? Got gzip enabled?

**Comment by macb** [comment] 2017-06-12 15:54
I can reliably reproduce within our environment when `curl`-ing the grafana instance directly with no proxy in front of it. You can see one response where it returns a valid `<!DOCTYPE html>` and one where there is instead a partial JSON blob at the top of the response (I truncated it for brevity).

```
kubelet-bfbabce:~$ curl http://1.0.0.1:3000 2>/dev/null | head -1
<!DOCTYPE html>
kubelet-bfbabce:~$ curl http://1.0.0.1:3000 2>/dev/null | head -1
[]},"includes":[{"name":"Prometheus Stats","path":"dashboards/prometheus_stats.json",.....
```

As far as I can tell we use a default `grafana.ini` as packaged with the 4.2 debian package. There is no `gzip` enabled at least according to the lack of a `Content-Encoding` header. It is using chunked transfer encoding:
`Transfer-Encoding: chunked`

Most of our configuration is instead which database to talk to and how to handle sessions.

We do run it within docker and use a container similar to the official but it packages plugins as opposed to fetching them at run time.

**Comment by torkelo** [comment] 2017-06-12 16:19
No kubernetes ingest controller proxy ? It's strange that there this has only happened to two people. Not sure what it can be beside a proxy issue.

**Comment by torkelo** [comment] 2017-06-12 16:20
What plugins do you have installed? Maybe a plugin is causing it?

**Comment by macb** [comment] 2017-06-12 18:07
https://github.com/grafana/grafana/issues/6850#issuecomment-307840163 I circumvented our ingress in this case and `curl`-ed the pod directly from the kubelet it was being hosted on. So the only thing inbetween is the veth.

Only plugin I see being installed during docker container build is:
`grafana-cli plugins install raintank-worldping-app`

Only 2 people are reporting it. There could be more experiencing it but willing to just hit refresh instead of opening a GH issue. :)

**Comment by warmfusion** [comment] 2017-06-12 20:16
So i get the exact same behaviour as @macb ... heres the example output from my server;

```
# netstat -tulpn | grep grafa
tcp6       0      0 :::3000                 :::*                    LISTEN      32684/grafana-serve
# curl localhost:3000 2>/dev/null | head -1
","url":"https://www.elastic.co/products/elasticsearch"}],"logos" ... 
# This line goes on for A LONG time

# curl localhost:3000 2>/dev/null | head -1
<!DOCTYPE html>


# grafana-cli plugins ls
installed plugins:
grafana-clock-panel @ 0.0.8
grafana-piechart-panel @ 1.1.4
grafana-worldmap-panel @ 0.0.16
jdbranham-diagram-panel @ 1.4.0

# grafana-server -v
Version 4.0.1 (commit: v4.0.1)
```

**Comment by warmfusion** [comment] 2017-06-12 20:19
Just disabled gzip, and after a number of requests was able to reproduce the corrupt html response

**Comment by warmfusion** [comment] 2017-06-12 20:24
Just seen the same behaviour indicated with the end of one request being bolted to the start of the next.

**Comment by torkelo** [comment] 2017-06-14 10:04
And if you try it withiut plugins, or with Grafana  4.3

Do you get the same error?

**Comment by warmfusion** [comment] 2017-06-14 10:46
I can't use Grafana 4.3 as we're got a legacy ElasticSearch 1.6 installation that needs upgrading.

The plugins seem unlikly as a cause as @macb and myself dont' appear to have any common plugins, however I'll try and look out of hours as the worldmap plugin is used on our monitoring screens around the office.

Ref; https://github.com/grafana/grafana/issues/6850#issuecomment-307870909
