### ISSUE TITLE
Grafana 7 integrate with Okta will resets user's Org ID for each login.

### ISSUE THREAD

**Issue by frankietseng** [grafana/grafana#27001] opened 2020-08-14 07:55 UTC
I have integrated the Okta with my Grafana 7.1.3. I need to set multiple organizations ID for each users. But when user's web session timeout or Grafana service restart, user need to login through the Okta again. After that, user's org ID will be resets to only have default org ID. 

Someone has the same issue:
https://community.grafana.com/t/grafana7s-okta-integration-resets-org-permissions-upon-each-login/32873

**My wokrflow**:
At first, I have add the org ID for my user.
![Screen Shot 2020-08-14 at 3 32 58 PM](https://user-images.githubusercontent.com/63087605/90225663-51d0c400-de44-11ea-9db6-73f60b99617d.png)
Then logout from Grafana.
![Screen Shot 2020-08-14 at 3 34 11 PM](https://user-images.githubusercontent.com/63087605/90225705-5eedb300-de44-11ea-9aac-47433aee2473.png)
And login
![Screen Shot 2020-08-14 at 3 35 03 PM](https://user-images.githubusercontent.com/63087605/90226374-7c6f4c80-de45-11ea-9d5a-0d3fc6684d13.png)

There are only one org ID left.
![Screen Shot 2020-08-14 at 3 35 45 PM](https://user-images.githubusercontent.com/63087605/90226400-85601e00-de45-11ea-9774-92f27040aa5b.png)

I also check my database.
Before login:
![Screen Shot 2020-08-14 at 3 48 13 PM](https://user-images.githubusercontent.com/63087605/90226596-cce6aa00-de45-11ea-8d80-d08da97b2137.png)
After login again:
![Screen Shot 2020-08-14 at 3 48 39 PM](https://user-images.githubusercontent.com/63087605/90226627-d839d580-de45-11ea-8803-8973b15779ff.png)

**What would you like to be added**:

- Is it possible to set multiple default org ID  with `auto_assign_org_id` in grafana.ini ?

- or don't make the org ID overwrites when new session created through Okta.

**Why is this needed**: to give different permissions for different organization user.

**Comment by aknuds1** [comment] 2020-08-14 07:59
I think this is a duplicate of #22605.

**Closed by aknuds1** 2020-08-14 07:59 UTC

**Comment by frankietseng** [comment] 2020-08-14 08:22
> I think this is a duplicate of #22605.

Got it. Hope to hear good news as soon as possible. Thank you!

**Comment by aknuds1** [comment] 2020-08-14 08:27
There are a couple of PRs under way, but the functionality needs to be discussed and agreed on.
