### ISSUE TITLE
Dashboard hangs with message "Services"

### ISSUE THREAD

**Issue by cypres-it** [grafana/grafana#17299] opened 2019-05-27 10:10 UTC
**What happened**:

  When I open the affected dashboard I only see the Grafana toolbar on the left and a white screen with a "Services" message and a spinning wheel.

**What you expected to happen**:

  I expect to see the dashboard or some kind of error message that tells me what is going on.

**How to reproduce it (as minimally and precisely as possible)**:

  I would post the Dashboard json. But I don't know how to get to it because of this issue.

**Anything else we need to know?**:

  I tried multiple times, reloading everything, restarting grafana, but the dashboard won't load.

**Environment**:
- Grafana version:     Grafana v6.2.0 (5d16da7)
- Data source type & version: PostgreSQL
- OS Grafana is installed on: CentOS Linux release 7.6.1810 (Core)
- User OS & Browser:
  Windows 10
  Chrome Version 74.0.3729.169 (Offizieller Build) (64-Bit)
  Firefox 67 (64-Bit)
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment] 2019-05-27 12:06
Looks like your dashboard loading is hanging. 

Can you open chrome dev tools and check for errors in the console? Also check the network tab in dev tools and find the api request that loads the dashboard json and paste that here.

**Comment by cypres-it** [comment] 2019-05-27 12:18
In the console there is only a warning that "window.controllers/Controllers" shoudn't be used anymore.

If I check in the network tab and hit ctrl-f5 all the requests have status 200 OK:

```
GET http://radon:3000/d/XG3vljmWz/ak-test-1?orgId=1
[HTTP/1.1 200 OK 125ms]

GET http://radon:3000/public/build/grafana.light.42c3c32bf36973cb02e0.css
[HTTP/1.1 200 OK 298ms]

GET http://radon:3000/public/build/vendor.42c3c32bf36973cb02e0.js
[HTTP/1.1 200 OK 2512ms]

GET http://radon:3000/public/build/app.42c3c32bf36973cb02e0.js
[HTTP/1.1 200 OK 1567ms]

GET http://radon:3000/public/img/grafana_icon.svg
[HTTP/1.1 200 OK 38ms]

GET http://radon:3000/avatar/46d229b033af06a191ff2267bca9ae56
[HTTP/1.1 200 OK 36ms]

GET http://radon:3000/public/img/icn-dashboard-tiny.svg
[HTTP/1.1 200 OK 33ms]

window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. index.js:1362
GET http://radon:3000/public/fonts/fontawesome-webfont.woff2?v=4.7.0
[HTTP/1.1 200 OK 88ms]

GET http://radon:3000/public/img/apple-touch-icon.png
[HTTP/1.1 200 OK 38ms]

GET http://radon:3000/public/img/fav32.png
[HTTP/1.1 200 OK 37ms]

```

**Comment by torkelo** [comment] 2019-05-28 11:17
And the dashboard json (check via chrome dev tools network tab). 

Maybe a recursive variable dependency?

**Comment by cypres-it** [comment] 2019-05-28 11:50
That could be. I added `where` conditions to the variable queries so that the value list is reduced based on the other variable selections. That seemed to work though, at least somewhat. When and how are those queries evaluated? If they are evaluated together at the same time then that might be the issue. I was hoping that they are evaluated individually when you click on a variables drop down menu. Then these mutual references shouldn't be an issue.

Here is the dashboard's json:
```
{"meta":
 {"type":"db",
  "canSave":true,
  "canEdit":true,
  "canAdmin":true,
  "canStar":true,
  "slug":"x-test-1",
  "url":"/d/XG3vljmWz/x-test-1",
  "expires":"0001-01-01T00:00:00Z",
  "created":"2019-05-24T10:53:11+02:00",
  "updated":"2019-05-28T09:02:31+02:00",
  "updatedBy":"admin",
  "createdBy":"admin",
  "version":9,
  "hasAcl":false,
  "isFolder":false,
  "folderId":9,
  "folderTitle":"not working",
  "folderUrl":"/dashboards/f/x1zS5zGWz/not-working",
  "provisioned":false,
  "provisionedExternalId":""},
 "dashboard":
 {"annotations":
  {"list":[
      {"builtIn":1,
       "datasource":"-- Grafana --",
       "enable":true,
       "hide":true,
       "iconColor":"rgba(0,211,255,1)",
       "name":"Annotations \u0026 Alerts",
       "type":"dashboard"}]},
  "editable":true,
  "gnetId":null,
  "graphTooltip":0,
  "id":2,
  "links":[],
  "panels":[
      {"aliasColors":
       {},
       "bars":false,
       "dashLength":10,
       "dashes":false,
       "datasource":"PostgreSQL",
       "fill":1,
       "gridPos": {"h":12, "w":24, "x":0, "y":0},
       "hideTimeOverride":false,
       "id":2,
       "interval":"1d",
       "legend":
       {"alignAsTable":false,
	"avg":false,
	"current":false,
	"max":false,
	"min":false,
	"rightSide":false,
	"show":true,
	"total":false,
	"values":false},
       "lines":true,
       "linewidth":1,
       "links":[],
       "nullPointMode":"null",
       "percentage":false,
       "pointradius":2,
       "points":true,
       "renderer":"flot",
       "seriesOverrides":[],
       "spaceLength":10,
       "stack":false,
       "steppedLine":false,
       "targets":[
	   {"format":"time_series",
	    "group":[],
	    "metricColumn":"servername ||'.'|| dbname ||'.'|| key",
	    "rawQuery":true,
	    "rawSql":"SELECT\n  dt AS \"time\",\n  descr ||' ('|| dbname ||'@'|| servername ||')' AS metric,\n  value\nFROM v_sla_log\nWHERE\n  $__timeFilter(dt) AND\n  netname IN ($netname) AND\n  db_type IN ($db_type) AND\n  database IN ($database) AND\n  descr IN ($metric)\nORDER BY 1,2",
	    "refId":"A",
	    "select":[[{"params":["value"], "type":"column"}]],
	    "table":"v_sla_log",
	    "timeColumn":"dt",
	    "timeColumnType":"timestamp",
	    "where":[
		{"name":"$__timeFilter",
		 "params":[],
		 "type":"macro"},

		{"datatype":"text",
		 "name":"",
		 "params":["servername", "IN", "($server)"],
		 "type":"expression"},

		{"datatype":"text",
		 "name":"",
		 "params":["dbname", "IN", "($database)"],
		 "type":"expression"},

		{"datatype":"text",
		 "name":"",
		 "params":["key", "IN", "($metric)"],
		 "type":"expression"}]}],
       "thresholds":[],
       "timeFrom":"7d",
       "timeRegions":[],
       "timeShift":null,
       "title":"$metric",
       "tooltip":
       {"shared":false,
	"sort":0,
	"value_type":"individual"},
       "type":"graph",
       "xaxis":
       {"buckets":null,
	"mode":"time",
	"name":null,
	"show":true,
	"values":[]},
       "yaxes":[
	   {"format":"short",
	    "label":null,
	    "logBase":1,
	    "max":null,
	    "min":null,
	    "show":true},
	   {"format":"short",
	    "label":null,
	    "logBase":1,
	    "max":null,
	    "min":null,
	    "show":true}],
       "yaxis":
       {"align":false,
	"alignLevel":null}}],
  "refresh":false,
  "schemaVersion":18,
  "style":"dark",
  "tags":["test", "x"],
  "templating":
  {"list":[
      {"allValue":null,
       "current":
       {"tags":[],
	"text":"X",
	"value":["X"]},
       "datasource":"PostgreSQL",
       "definition":"select distinct netname from v_sla_log where db_type in ($db_type) and database in ($database) and key in ($metric)",
       "hide":0,
       "includeAll":true,
       "label":"Net Name",
       "multi":true,
       "name":"netname",
       "options":[],
       "query":"select distinct netname from v_sla_log where db_type in ($db_type) and database in ($database) and key in ($metric)",
       "refresh":1,
       "regex":"",
       "skipUrlSync":false,
       "sort":1,
       "tagValuesQuery":"",
       "tags":[],
       "tagsQuery":"",
       "type":"query",
       "useTags":false},

      {"allValue":null,
       "current":
       {"selected":false,
	"tags":[],
	"text":"X",
	"value":["X"]},
       "datasource":"PostgreSQL",
       "definition":"select distinct db_type from v_sla_log where netname in ($netname) and database in ($database) and key in ($metric)",
       "hide":0,
       "includeAll":true,
       "label":"",
       "multi":true,
       "name":"db_type",
       "options":[],
       "query":"select distinct db_type from v_sla_log where netname in ($netname) and database in ($database) and key in ($metric)",
       "refresh":1,
       "regex":"",
       "skipUrlSync":false,
       "sort":1,
       "tagValuesQuery":"",
       "tags":[],
       "tagsQuery":"",
       "type":"query",
       "useTags":false},

      {"allValue":null,
       "current":
       {"tags":[],
	"text":"a + b + c + d + e + f",
	"value":["a", "b", "c", "d", "e", "f"]},
       "datasource":"PostgreSQL",
       "definition":"select distinct database from v_sla_log where netname in ($netname) and db_type in ($db_type) and key in ($metric)",
       "hide":0,
       "includeAll":true,
       "label":"Database",
       "multi":true,
       "name":"database",
       "options":[],
       "query":"select distinct database from v_sla_log where netname in ($netname) and db_type in ($db_type) and key in ($metric)",
       "refresh":1,
       "regex":"",
       "skipUrlSync":false,
       "sort":1,
       "tagValuesQuery":"",
       "tags":[],
       "tagsQuery":"",
       "type":"query",
       "useTags":false},

      {"allValue":null,
       "current":
       {"selected":false,
	"text":"All",
	"value":"$__all"},
       "datasource":"PostgreSQL",
       "definition":"select distinct descr from v_sla_log where netname in ($netname) and db_type in ($db_type) and database in ($database)",
       "hide":0,
       "includeAll":true,
       "label":"Metric",
       "multi":true,
       "name":"metric",
       "options":[],
       "query":"select distinct descr from v_sla_log where netname in ($netname) and db_type in ($db_type) and database in ($database)",
       "refresh":1,
       "regex":"",
       "skipUrlSync":false,
       "sort":1,
       "tagValuesQuery":"",
       "tags":[],
       "tagsQuery":"",
       "type":"query",
       "useTags":false}]},
  "time": {"from":"now-7d", "to":"now"}, "timepicker":
  {"refresh_intervals":["5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"],
   "time_options":["5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"]},
  "timezone":"",
  "title":"x test 1",
  "uid":"XG3vljmWz",
  "version":9}}
```

**Comment by AlKult** [comment] 2019-07-03 13:58
Hi,

I'm getting the same issue. And it most likely is to do with variable dependency.
Data Source is Elasticsearch.

When I have just these variables, everything works fine:
```
$Name	{"find": "terms", "field": "Name.keyword"}
$ID	{"find": "terms", "field": "ID.keyword", "query": "Name.keyword:$Name"}
```

But when I modify the first variable to query for the second one, I get that "Services" message that never transitions into anything.
```
$Name	{"find": "terms", "field": "Name.keyword", "query": "ID.keyword:$ID"}
$ID	{"find": "terms", "field": "ID.keyword", "query": "Name.keyword:$Name"}
```

I'd expect Grafana to generate an error if that logic is not supported. But on the other hand, I'd expect that logic to be supported as it's not uncommon to have fields of data that are mutually-dependable and can filter out each other in either direction.

Thanks!

Best regards,
Albert.

**Comment by torkelo** [comment] 2019-07-03 15:13
circular dependencies are not supported (cause infinite loop)

**Comment by AlKult** [comment] 2019-07-03 15:22
Is there any other means to make two filters filter each other out in Grafana?

**Comment by AlKult** [comment] 2019-07-23 11:36
> Is there any other means to make two filters filter each other out in Grafana?

Hi,

Can someone help me with this, please?

Best regards,
Albert.

**Comment by Tomy8s** [comment] 2019-07-25 12:21
Would it be possible to show an error in this case, and not have Grafana just hang?

**Comment by marefr** [comment] 2019-08-07 13:26
Duplicate of #8583

**Closed** 2019-08-07 13:26 UTC
Labels: needs more detail

**Comment by atxparis** [comment] 2019-08-21 15:59
My Dashboard also crashed the same way. Is there a way to this dashboard back so I can troubleshoot the issue? If only I could get access to its JSON file, it would be enough...

**Comment by AlKult** [comment] 2019-08-21 16:13
> My Dashboard also crashed the same way. Is there a way to get this dashboard back so I can troubleshoot the issue? If only I could get access to its JSON file, it would be enough...

This issue is closed as a duplicate. Use #8583

**Comment by shobhit921** [comment] 2020-05-05 10:53
Was this issue solved? I have the same issue with mostly the same responses as mentioned by cypres-it. Same 200 responses and json from dev tools

**Comment by Thys3Potgieter** [comment] 2020-06-01 22:37
I managed to access my dashboard that was doing this by disabling all data sources referenced by the dashboard.

**Comment by meernasserali-cts** [comment] 2020-06-02 16:30
> I managed to access my dashboard that was doing this by disabling all data sources referenced by the dashboard.

@Thys3Potgieter Did you delete the data sources referenced in order to recover the dashboard?

**Comment by Thys3Potgieter** [comment] 2020-06-02 16:32
Hi Meer, I changed the host IP in the datasource configuration so that the dashboard could not access the datasources, allowing it to load.
