### ISSUE TITLE
Alerting: Preview routing is using cached notification policies

### ISSUE THREAD

**Issue by jan2893** [grafana/grafana#86756] opened 2024-04-23 10:24 UTC
### What happened?

- I clicked `Preview routing`
- The routing was wrong because my notification policy was broken
- I fixed the notification policy in new tab
- I clicked `Preview routing`
- It showed old and broken routing
- I refreshed the alert review tab (which cleared all my changes that I was testing)
- I reapplied all my changes
- I clicked `Preview rounting`
- It showed correct routing that I wanted to see

### What did you expect to happen?

That I do not need to refresh the whole tab to get new notification policies in the alert edit view.

### Did this work before?

No

### How do we reproduce it?

- I clicked `Preview routing`
- The routing was wrong because my notification policy was broken
- I fixed the notification policy in new tab
- I clicked `Preview routing`
- It showed old and broken routing

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.4.1
OS: Ubuntu 22.04.4 LTS
Browser: Chrome Version 123.0.6312.122 (Official Build) (64-bit)

### Grafana platform?

Kubernetes

**Comment by jan2893** [comment] 2024-04-23 10:25
It's interesting that showing the routing is not instant, it takes a few seconds so I'd expect it to fetch the new notification policies.

**Comment by tonypowa** [comment] 2024-05-21 13:09
Hi @jan2893 
Thank you for creating this issue

Is the issue consistently reproducible following the steps you mentioned, or does it occur intermittently?
And do you also experience the same in browsers other than Chrome?

**Comment by jan2893** [comment] 2024-06-20 08:20
It's consistent. I can reproduce it every time.
I can also reproduce it in Firefox.

**Comment by tonypowa** [comment] 2024-06-20 09:09
What version of Grafana are you using? Can you try to reproduce it in incognito?

I can't reproduce the scenario that you describe
Here is a screen recording where I "fix" the policy while editing the alert rule in a separate tab. There's no need to refresh for Grafana to pick up the changes.
![86756](https://github.com/grafana/grafana/assets/45235678/7d86e7a7-399a-4d8d-8265-bb3da495a446)

tested in Grafana v11.2.0-72125 (b9812a0784)
Firefox 126.0.1

**Comment by tonypowa** [comment] 2024-08-19 09:35
Closing since it's probably fixed. Please feel free to reopen if the problem persists.!

**Closed by tonypowa** 2024-08-19 09:35 UTC
Labels: needs more info
