### ISSUE TITLE
Numeric columns are sorted alphabetically in grafana 8.1.2

### ISSUE THREAD

**Issue by aricamf** [grafana/grafana#41545] opened 2021-11-10 13:41 UTC
**What happened**: Numeric columns are sorted alphabetically

**What you expected to happen**: sort the table numerically

**How to reproduce it (as minimally and precisely as possible)**: 
1. query data collected by loki ad visualize with the table
2. numeric columns are sorted alphabetically

![image](https://user-images.githubusercontent.com/36829174/141123555-608f9bdf-1e00-4b04-b590-c74e1757a290.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version:  loki 2.2
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser:  chrome + windows 10
- Grafana plugins: n/a
- Others: n/a

**Comment by ashharrison90** [comment] 2021-11-10 14:24
hi @aricamf 👋 

thanks for raising this. i'm unable to reproduce on the latest version of grafana:
![image](https://user-images.githubusercontent.com/20999846/141129138-27b8b21c-6bed-4f89-b212-2a71bd171192.png)

is it possible for you to upgrade and check to see if that fixes your problem? the other reason upgrading would be nice is that we've introduced some type indicators for table columns with https://github.com/grafana/grafana/pull/38855. my suspicion is those are actually string fields, so this is expected behaviour.

hope that helps!

**Comment by aricamf** [comment] 2021-11-10 14:34
Hi @ashharrison90  
Thanks for the prompt reply so much! Sure I will upgrade the grafana to the latest version and have a try. One more thing I would like to highlight is, actually the meta data is indeed number but...it's a json format and I did a "Labels to field" transformation so that it can be visualized as a table.

Will that transform the number to "string"?

Thanks

**Comment by aricamf** [comment] 2021-11-10 14:49
I've upgraded to the 8.2.3 and the issue is still there. Let me try to clarify a bit more.

By explore, I saw the data as number
![image](https://user-images.githubusercontent.com/36829174/141134837-d34d3ebc-2749-488a-bf3c-11ee0602da56.png)

however "Labels to Field" and visualize as table ... it's indeed a string...

![image](https://user-images.githubusercontent.com/36829174/141134973-0c4e669f-f9e1-42ab-a5c2-af8046c2cec1.png)

...any hints...how I can show/sort this field numerically?

**Comment by ashharrison90** [comment] 2021-11-10 16:05
hi again @aricamf 👋 

looking at the [code](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/transformations/transformers/labelsToFields.ts#L83) for the labels to fields transformer, yes i believe that will convert everything to strings.

without knowing the details of your use case, i wonder if using something like the [loki example dashboard](https://play.grafana.org/d/T512JVH7z/loki-nginx-service-mesh?orgId=1) on grafana play to refer to will help? specifically something like the [http status codes panel](https://play.grafana.org/d/T512JVH7z/loki-nginx-service-mesh?orgId=1&editPanel=2).

if that doesn't help with your use case, the best place to ask for support would be either on the [community forums](https://community.grafana.com/) or in the [grafana public slack](http://grafana.slack.com)

given that i don't think there's a bug here i'm going to close this. hope that makes sense! 👍

**Closed by ashharrison90** 2021-11-10 16:05 UTC
Labels: needs more info
