### ISSUE TITLE
Windows services can't start Grafana after upgrading to version 7.4.0

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#31061] opened 2021-02-09 20:04 UTC
After unpacking Grafana binary version 7.4.0 on top of version 7.3.4 the windows services can't start Grafana and Windows warn that the services was't started and without any error message.

I used NSSM to start grafana as services

I have had no problems at former upgrades for version 7.x.x to version 7.x.y.

**Environment**:
- Grafana version: 7.4.0
- OS Grafana is installed on: Windows Azure
- Grafana plugins: Plugins also from version before version 7

**Comment by torkelo** [comment] 2021-02-10 08:07
Any error message in the grafan server log? in the windows event log?

**Comment by HenrikRolandHansen** [comment] 2021-02-10 08:37
Hi Torkelo

Attached the grafana log file.
[grafana.log](https://github.com/grafana/grafana/files/5956773/grafana.log)

The windows log does not provide much information 

Service grafana ran for less than 1500 milliseconds. Restart will be delayed by 128000 milliseconds.

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="nssm" /> 
  <EventID Qualifiers="32768">1034</EventID> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-02-10T08:31:19.606959900Z" /> 
  <EventRecordID>68686749</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>A0505P01.energinet.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>grafana</Data> 
  <Data>1500</Data> 
  <Data>128000</Data> 
  </EventData>
  </Event>

**Comment by aknuds1** [comment] 2021-02-10 08:43
Can't see anything wrong in the Grafana log. Can you manually run Grafana in the same way as NSSM runs it @HenrikRolandHansen, in order to try to reproduce the failure?

**Comment by HenrikRolandHansen** [comment] 2021-02-10 09:06
1. I first run the grafana-server manualy for the version 7.4.0 it works fine. 
2. Then I unpack the Binary over the old version and start the grafana-server manualy and get this log from the CMD . The server does not start:


E:\Temp\Grafana v7 test\bin>grafana-server
[32mINFO[0m[02-10|10:03:47] Starting Grafana                         [32mlogger[0m=server [32mversion[0m=7.4.0 [32mcommit[0m=c2203b9859 [32mbranch[0m=HEAD [32mcompiled[0m=2021-02-04T12:11:00+0100
[32mINFO[0m[02-10|10:03:47] Config loaded from                       [32mlogger[0m=settings [32mfile[0m="E:\\Temp\\Grafana v7 test/conf/defaults.ini"
[32mINFO[0m[02-10|10:03:47] Config loaded from                       [32mlogger[0m=settings [32mfile[0m="E:\\Temp\\Grafana v7 test\\conf\\custom.ini"
[32mINFO[0m[02-10|10:03:47] Config overridden from Environment variable [32mlogger[0m=settings [32mvar[0m="GF_PANELS_DISABLE_SANITIZE_HTML=true"
[32mINFO[0m[02-10|10:03:47] Path Home                                [32mlogger[0m=settings [32mpath[0m="E:\\Temp\\Grafana v7 test"
[32mINFO[0m[02-10|10:03:47] Path Data                                [32mlogger[0m=settings [32mpath[0m="E:\\Temp\\Grafana v7 test\\data"
[32mINFO[0m[02-10|10:03:47] Path Logs                                [32mlogger[0m=settings [32mpath[0m="E:\\Temp\\Grafana v7 test\\data\\log"
[32mINFO[0m[02-10|10:03:47] Path Plugins                             [32mlogger[0m=settings [32mpath[0m="E:\\Temp\\Grafana v7 test\\data\\plugins"
[32mINFO[0m[02-10|10:03:47] Path Provisioning                        [32mlogger[0m=settings [32mpath[0m="E:\\Temp\\Grafana v7 test\\conf\\provisioning"
[32mINFO[0m[02-10|10:03:47] App mode production                      [32mlogger[0m=settings
[32mINFO[0m[02-10|10:03:47] Connecting to DB                         [32mlogger[0m=sqlstore [32mdbtype[0m=sqlite3
[33mWARN[0m[02-10|10:03:47] SQLite database file has broader permissions than it should [33mlogger[0m=sqlstore [33mpath[0m="E:\\Temp\\Grafana v7 test\\data\\grafana.db" [33mmode[0m=-rw-rw-rw- [33mexpected[0m=-rw-r-----
[32mINFO[0m[02-10|10:03:47] Starting DB migrations                   [32mlogger[0m=migrator
[32mINFO[0m[02-10|10:03:47] Starting plugin search                   [32mlogger[0m=plugins
[33mWARN[0m[02-10|10:03:47] Plugin is duplicate                      [33mlogger[0m=plugins [33merror[0m="Failed to register plugin: plugin with ID \"stackdriver\" already loaded from \"E:\\\\Temp\\\\Grafana v7 test\\\\public\\\\app\\\\plugins\\\\datasource\\\\stackdriver\""
[33mWARN[0m[02-10|10:03:47] Some plugins failed to load              [33mlogger[0m=plugins [33merrors[0m="[Failed to register plugin: plugin with ID \"stackdriver\" already loaded from \"E:\\\\Temp\\\\Grafana v7 test\\\\public\\\\app\\\\plugins\\\\datasource\\\\stackdriver\"]"
[33mWARN[0m[02-10|10:03:47] The following files were not included in the signature [33mlogger[0m=plugins [33mplugin[0m=gel [33mfiles[0m=[img\\pipeline.svg]
[33mWARN[0m[02-10|10:03:47] The following files were not included in the signature [33mlogger[0m=plugins [33mplugin[0m=input [33mfiles[0m=[img\\input.svg]
service init failed: failed to scan bundled plugins directory 'E:\Temp\Grafana v7 test\plugins-bundled': unknown plugin type "transform"

E:\Temp\Grafana v7 test\bin>

**Comment by aknuds1** [comment] 2021-02-10 09:16
Ah, I recognize the problem. It's an issue with upgrading from 7.3 to 7.4, where a bundled plugin (GEL) is left behind, that is now in the core. Try removing plugins-bundled\gel-0.6.0.

**Comment by aknuds1** [comment] 2021-02-10 09:38
Closing the issue for the time being, since I think my suggestion above should solve the problem.

**Comment by HenrikRolandHansen** [comment] 2021-02-10 09:39
It works now!  thanks. 

I deleted the gel-0.6.0 folder as you surgested and Services starts again.

Cheers

Henrik

**Closed by aknuds1** 2021-02-10 09:38 UTC
Labels: needs more info, os/windows

**Comment by nabelekt** [comment] 2021-02-10 19:57
It would probably be helpful to many if this was documented more broadly, or fixed in the installer. I had the same issue.
Windows 10
grafana-enterprise-7.4.0.windows-amd64.msi
upgrading 7.3.X to 7.4.0

Resolved after deleting the gel-0.6.0 folder. Do I need to to anything to restore that directory, or is it no longer needed?

**Comment by aknuds1** [comment] 2021-02-10 20:36
@nabelekt I'm actually not sure if this is fixed in the Windows installer, which I know there was some work on. The directory is no longer needed.

**Comment by nabelekt** [comment] 2021-02-10 21:00
Should this issue be reopened then as a bug for the installer? The grafana-enterprise-7.4.0.windows-amd64.msi file I downloaded was downloaded just a couple of hours ago.

**Comment by aknuds1** [comment] 2021-02-11 03:51
@nabelekt It's better to create a new issue.

**Comment by aliche123** [comment] 2021-07-31 08:26
any help please , can not start the grafana???? these is error??
eth2test@Eth:~$ sudo systemctl status grafana-server
● grafana-server.service - Grafana instance
     Loaded: loaded (/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2021-07-31 03:18:40 CDT; 6s ago
       Docs: http://docs.grafana.org
    Process: 23920 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.>
   Main PID: 23920 (code=exited, status=1/FAILURE)

Jul 31 03:18:40 Eth systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Jul 31 03:18:40 Eth systemd[1]: Stopped Grafana instance.
Jul 31 03:18:40 Eth systemd[1]: grafana-server.service: Start request repeated too quickly.
Jul 31 03:18:40 Eth systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jul 31 03:18:40 Eth systemd[1]: Failed to start Grafana instance.

**Comment by gautham2914** [comment] 2025-05-20 12:59
If you are running in Windows machine , Please try to repair the Grafana.exe .After re installing ,please restart the machine . Grafana services will get automatically starts.

If you made any changes in config file, please made changes again for required outups.
