### ISSUE TITLE
No longer able to bind anonymously for auth LDAP search v6.0.0

### ISSUE THREAD

**Issue by gribnut** [grafana/grafana#15643] opened 2019-02-25 17:35 UTC
### What Grafana version are you using?
6.0.0
### What OS are you running grafana on?
RHEL 7.7
### What did you do?
Upgraded Grafana from v5.4.3 to v6.0.0
### What was the expected result?
Maintain previous auth behavior with anonymous bind for LDAP searches by setting bind_dn and bind_password directives to empty string.
### What happened instead?
After upgrading Grafana to v6.0.0, previous LDAP auth behavior of performing anonymous bind for LDAP search when setting bind_dn and bind_password to empty string no longer occurs.  Grafana LDAP client in v6.0.0 now appears to attempt to bind with an empty password instead of binding anonymously. 
Also tried with bind_dn and bind_password not set in config (toml file) with same result - Grafana LDAP client does not perform anonymous bind for LDAP search.

**Comment by xlson** [comment] 2019-02-26 09:52
This seems to have been an unintentional behavior that was removed when upgrading go-ldap. If you are able to configure a bind_dn that works for all users, more about that [here](http://docs.grafana.org/auth/ldap/#bind) the user's password will be used for the initial bind.

Duplicate of #15245

**Comment by gribnut** [comment] 2019-02-26 12:55
Unfortunately in my environment, I don't control the structure/DIT of the LDAP Directory.  Users are not  all under the same branch so a search is required and the Grafana option of single bind_dn pattern doesn't work.  Additionally, the only option we have for searching for users is via anonymous bind as well.
Seems like the best option is to have the Grafana LDAP client bind anonymously for the initial search if the bind_dn config item is empty (or not set).
I didn't realize there was a previous open issue on this topic (I missed in search before opening this one).   I'll post thoughts on #15245 as well.

**Comment by xlson** [comment] 2019-02-26 13:00
@gribnut Let's stay on this issue for now. Any chance you could get the administrator of your ldap system to setup a user for read-only search so that you can use that for the inital bind?

**Comment by gribnut** [comment] 2019-02-26 13:12
Thanks @xlson  
I've gone that route as a temp workaround after upgrading to Grafana v6.0.  However, our company also has policy that requires periodic password resets so I'll eventually fall into needing to update the grafana config to match which turns into a bit of a kludge over time.

When initially setting up Grafana for LDAP auth few years ago, I came across previous issue/discussion around anonymous binds by setting bind_dn and bind_password to empty values.  While it may not be a large number of users, there seems to be other environments also needing anonymous binds for the user searches.

Would following logic meet current designed behavior + allow for environments that require anonymous searches?
* If bind_dn is empty value (or not set), perform anonymous LDAP search for user
* If bind_dn is set but bind_password is empty, use single bind method
* If bind_dn and and bind_password are both set, bind with configured credentials for user search

**Comment by xlson** [comment] 2019-02-26 15:56
@torkelo @marefr I noticed that you discussed this recently. Could you take a look at this issue when you get back?

**Comment by JimboJoe** [comment] 2019-03-04 18:17
Hello, we are in the same case as @gribnut for the [Grafana YunoHost package](https://github.com/YunoHost-Apps/grafana_ynh): we need to perform an anonymous LDAP search (which is handled by many other supported upstream apps).
The proposal to have an anonymous bind when bind_dn/bind_password are empty seems suitable (this was actually the working configuration until 6.0 upgrade).
Thanks!

**Comment by dileks** [comment] 2019-03-05 07:13
Just as feedback:
After upgrading to `grafana v6.0.0` (Debian/stable) we could fix the LDAP login by using "Single Bind" method.
```
[ /etc/grafana/ldap.toml ]

 # Search user bind dn
-bind_dn = "cn=admin,dc=grafana,dc=org"
+#bind_dn = "cn=admin,dc=grafana,dc=org"
 # Search user bind password
-bind_password = 'grafana'
+#bind_password = 'grafana'
+# Use Single Bind, details see <http://docs.grafana.org/auth/ldap/#bind>
+bind_dn = "uid=%s,ou=People,dc=<COUNTRY_SHORT>,dc=<COMPANY_NAME>,dc=org"
```
Feel free to adapt the `bind_dn` line to your needs.

**Comment by sergiik** [comment] 2019-03-05 14:59
Single Bind will work only for simple setup where one can provide a single bind expression that matches all possible users.

**Comment by gribnut** [comment] 2019-03-06 18:08
I have updated to v6.0.1 and verified anonymous LDAP binds now working if bind_dn is not set or empty.  Thanks @marefr and @torkelo.   Appreciate the fix.

**Comment by JimboJoe** [comment] 2019-03-06 19:31
I have updated to 6.0.1 as well and the fix works for direct login/password :+1: . Our existing login via auth proxy still doesn't work (complaining about empty ldap password)... is there a chance to still have a specific issue?

**Comment by marefr** [comment] 2019-03-08 11:01
@JimboJoe Thanks for testing. This was basically the thing I was unsure about, see [PR comment](https://github.com/grafana/grafana/pull/15803#issue-258410192). Reopening this and try to fix for v6.0.2.

**Closed** 2019-03-08 13:25 UTC
Labels: comp: backend/auth/ldap, type: bug

**Comment by JimboJoe** [comment] 2019-03-29 06:27
Hello,
I forgot to report back: auth proxy is now also working fine. Thanks a lot for your communication and quick fix on this! :+1:

**Comment by marefr** [comment] 2019-03-29 06:35
@JimboJoe Thanks! :+1:
