### ISSUE TITLE
No query panel for Microsoft SQL Server datasource

### ISSUE THREAD

**Issue by gsaiz** [grafana/grafana#37049] opened 2021-07-21 09:38 UTC
**What happened**:

I added a Microsoft SQL Server datasource and couldn't see the query panel appear in the Explore tab.

Here is the recording:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/25729908/126466836-9d601b5f-4f47-4584-927a-ab9ffa95dfc4.gif)

**What you expected to happen**:

The query editor should have appeared so that I could write the SQL query.

As shown in [this page from the docs](https://grafana.com/docs/grafana/latest/datasources/mssql/), this is what I was expecting to appead:

![MSSQL Query Editor](https://grafana.com/static/img/docs/v51/mssql_query_editor.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a Microsoft SQL Server datasource.
2. Try to query any data in the Explore panel.

**Anything else we need to know?**:

I'm also experiencing this issue with Grafana 7.5.9.

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Microsoft SQL Server  (from Grafana labs)
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 10 21H1, Firefox 89.0.2 x64, Chrome 91.0.4472.164 (Official Build) (64-bit), Edge 91.0.864.71 (Official build) (64-bit).

- Grafana plugins: Microsoft SQL Server

**Comment by ivanahuckova** [comment] 2021-07-21 11:05
Hello @gsaiz, I tested this on grafana.play that is currently on 8.0.6 and couldn't reproduce the issue. You can check out this https://play.grafana.org/goto/1dIkGIWnz?orgId=1

![image](https://user-images.githubusercontent.com/30407135/126478876-fa715fa2-8fc8-4f3d-af6b-e145ba47d816.png)

Can you please open the console to see if there are any errors?

**Comment by gsaiz** [comment] 2021-07-21 12:44
Hi @ivanahuckova , I have tested the grafana.play instance and I can't reproduce the issue either, it works fine there.

However, I can see the following uncaught exceptions on my instance from the console, which seem to be the issue:

`
Uncaught (in promise) TypeError: u.acequire is not a function
    N code_editor.ts:149
    N code_editor.ts:94
    Angular 24
    r helpers.js:72
    setTimeout handler*3CEA/Q</e.prototype._wrapTimeFunction/< trycatch.js:86
    Angular 13
    d plugin_component.ts:223
    d plugin_component.ts:258
    link plugin_component.ts:266
    promise callback*link plugin_component.ts:265
    Angular 6
    componentDidMount QueryEditor.tsx:65
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    r helpers.js:72
code_editor.ts:149:8

`

I am using the same browser for both pages.

**Comment by gsaiz** [comment] 2021-07-21 12:48
Okay, after refreshing the page a few times on my Grafana Cloud instance, the exception is gone and I can now see the query editor. This was on Firefox.

I have done the same with Chrome and Edge, and refreshing the _Explore_ tab also fixed it in both cases.

**Comment by wbrowne** [comment] 2021-07-28 09:33
I will close this issue - but please reach out if the problem persists and we can re-open and investigate further

**Comment by gsaiz** [comment] 2021-08-02 17:10
Hi @wbrowne , this issue is definitely still there, I experience it every day. Simply refreshing the edit panel fixes it for my browser, until I close it and open it again.

I can provide information if you need it.

**Comment by raakasf** [comment] 2022-05-04 15:50
I can confirm that I see the same issue with an custom plugin for druid sql:
![Screen Shot 2022-05-04 at 11 04 14 AM](https://user-images.githubusercontent.com/4614260/166720313-f103a096-842b-4450-82be-caefa1b96c26.png)

**Comment by wbrowne** [comment] 2022-05-04 16:01
Looping in @grafana/grafana-bi-squad in case this is still relevant. Could be related to efforts around Angular deprecation

**Comment by zoltanbedi** [comment] 2022-05-30 08:13
I was not able to reproduce this in 9. We are also working on migrating the sql datasources (MSSQL,MYSQL,POSTGRES) to React.

**Closed by zoltanbedi** 2022-05-30 08:13 UTC
Labels: datasource/MSSQL, needs investigation, area/query-editor
