### ISSUE TITLE
Multi-value templating on metric names doesn't work for OpenTSDB

### ISSUE THREAD

**Issue by HugoMFernandes** [grafana/grafana#12625] opened 2018-07-16 16:53 UTC
Unlike other datasources, OpenTSDB doesn't allow for any wildcarding on the metric name. However, the current code uses `pipe` (as it does for tags, filters, etc) which actually produces broken metric names.

e.g.: `a.$var.b` (given `var=[1,2]`) currently resolves to `a.1|2.b` (which is not TSDB-valid).

In order to support templating, template variables within a single target need to explode into multiple (virtual) targets.

I'll submit a PR with a fix in a sec.

**Comment by torkelo** [comment] 2018-07-17 17:51
duplicate of https://github.com/grafana/grafana/issues/7754

**Closed by torkelo** 2018-07-17 17:51 UTC
