### ISSUE TITLE
session_life_time not working

### ISSUE THREAD

**Issue by ciprianpascu** [grafana/grafana#6635] opened 2016-11-18 08:21 UTC
- What Grafana version are you using? 3.1.1
- What OS are you running grafana on? Red Hat Enterprise Linux Server 7.2 (Maipo)

- What did you do?session_life_time

We have Nerve polling Grafana every 2s on port 3000, uri '/login', in order to maintain some records in Zookeeper. I can see the file amout in /var/lib/grafana/sessions increasing constantly because of this. I changed the value of session_life_time in the grafana.ini file to 10 (s) in order to see if the sessions will be deleted;  they are not.

- What was the expected result?
I would have expected that old sessions are deleted when session_life_time expires.

- What happened instead?
The sessions were not deleted, their number continued increasing.

**Comment by bergquist** [comment] 2016-11-18 15:30
I assume you want to health check grafana? 
Then its a dupe of this issue https://github.com/grafana/grafana/issues/3302

**Closed by bergquist** 2016-11-18 15:30 UTC
