### ISSUE TITLE
Grafana Alert using OpenSearch data source: Query type breaks alerts and data sources in org

### ISSUE THREAD

**Issue by wkneewalden** [grafana/grafana#77902] opened 2023-11-08 22:32 UTC
### What happened?

Alert was created that queries the OpenSearch data source. The query was missing double quotes around the string to match the lucene format, and the 'Group by' was selected to 'Filters'. Attempts to preview query gave the error in pop-up message, and also showed in alerts page under Health as shown in attached image:

[ss.dataQueryError] failed to execute query [A]:
[plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = Unknown desc = invalid character 'U' looking for beginning of value

![image](https://github.com/grafana/grafana/assets/67339085/5d8cd216-64e1-470c-8288-7188c6fb7f5b)

Attempts to create new alerts in same org that are known to work that query the OpenSearch data source give same error. By removing OpenSearch data source and all data sources in org, removing all alerts in org, and then recreating data sources and alerts allows creating new alerts that are known to work that then actually work. Seems to indicates that the alert system breaks due to a specific type of alert query using the OpenSearch data source causing all alert queries to produce this error.

### What did you expect to happen?

New alerts created afterward with correct queries or using Data Histogram would work without same error.

### Did this work before?

No, observed similar behavior in the past with Grafana v8 and v9, and now with v10.

### How do we reproduce it?

1. Create an alert that queries OpenSearch data source.
2. Set query to string without surrounding double quotes.
3. Set 'Group by' to 'Filters'
4. Preview query to generate error message, or save alert and wait for no data to then hover over Health error message in alerts page to show same error message
5. Attempt to create new alerts you know work with correct query string and 'Group by' set to 'Data histogram' but get same message.
6. Remove OpenSearch and any other data sources in org.
7. Remove all alerts in org.
8. Add back data sources and alerts in org.
9. Create new alerts you know work that query the OpenSearch data source and they now work.

### Is the bug inside a dashboard panel?

No, it is specific to alerts.

### Environment (with versions)?

Grafana: OSS v10.1.1
OS: Amazon Linux 2
Browser:  Chrome

### Grafana platform?

Other

### Datasource(s)?

OpenSearch v2.2.0

**Comment by giuliomagnifico** [comment] 2023-11-09 13:43
I have the same issue without using OpenSearch

`[sse.dataQueryError] failed to execute query [A]:`

and I have connected Grafana to pushover and it spams to me tons of notifications with those errors:

![Screenshot 2023-11-09 at 14 41 19](https://github.com/grafana/grafana/assets/1975176/4b5ad948-57ff-42ed-afa9-5b3e79ed7979)

**Comment by armandgrillet** [comment] 2023-11-22 10:36
@wkneewalden Can you send us logs showing that the evaluation for other alert rules is also failing? Are all your alert rules on the same OpenSearch datasource?

**Comment by wkneewalden** [comment] 2023-11-29 19:22
Yes, they are on the same data source. Here are some logs indicating different alerts having same issue.

```
logger=ngalert.scheduler rule_uid=b1ad5c0a-a9f9-41ee-904b-0c70c98ebc50 org_id=157 version=4 fingerprint=b3c5095f14f94719 attempt=0 now=2023-11-29T19:00:00Z rule_uid=b1ad5c0a-a9f9-41ee-904b-0c70c98ebc50 org_id=157 t=2023-11-29T19:00:09.875428534Z level=error msg="Failed to evaluate rule" error="[sse.dataQueryError] failed to execute query [A]: [plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = Unknown desc = invalid character 'U' looking for beginning of value"

logger=ngalert.scheduler rule_uid=b240b658-2c21-4e24-9c26-5a15018db84c org_id=157 version=9 fingerprint=f5a4ce75799eea18 attempt=0 now=2023-11-29T19:00:00Z rule_uid=b240b658-2c21-4e24-9c26-5a15018db84c org_id=157 t=2023-11-29T19:00:09.268170602Z level=error msg="Failed to evaluate rule" error="[sse.dataQueryError] failed to execute query [A]: [plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = Unknown desc = invalid character 'U' looking for beginning of value" duration=22.264076ms

logger=ngalert.scheduler rule_uid=f4b7f392-f58d-4226-9eb9-da477ad3d16c org_id=157 version=19 fingerprint=6c22fbec44bed940 attempt=0 now=2023-11-29T19:00:00Z rule_uid=f4b7f392-f58d-4226-9eb9-da477ad3d16c org_id=157 t=2023-11-29T19:00:08.505582031Z level=error msg="Failed to evaluate rule" error="[sse.dataQueryError] failed to execute query [A]: [plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = Unknown desc = invalid character 'U' looking for beginning of value" duration=17.870723ms
```

**Comment by armandgrillet** [comment] 2023-12-14 16:37
From the logs it is not related to alerting despite this is happening in alerting, passing this to the datasource team.

**Comment by fridgepoet** [comment] 2024-01-01 07:17
Hi @wkneewalden, what are your settings on the config page for this OpenSearch data source, for example what is under "Auth"? 

Also are you able to reproduce this error on a later version of the plugin? 

Note: Similar error to this issue https://github.com/grafana/opensearch-datasource/issues/111

**Comment by wkneewalden** [comment] 2024-01-04 16:53
I believe the same issue has been observed with v2.13.1 but will keep posted. In contrast to the other link, Basic Auth with user/password was used in configuration.

![opensearch_datasource_config](https://github.com/grafana/grafana/assets/67339085/e711667b-7b4c-4c62-94bf-a6ee46403af8)

**Comment by idastambuk** [comment] 2024-01-08 09:11
Hi @wkneewalden can you confirm that the latest version of the plugin still produces the same error? If so, does the same query produce an error in Explore?
Also, I'm unable to reproduce it with either 2.2.0 or 2.14.1, can you give an example of a query that would fail, just in case? 
Thanks!

**Comment by wkneewalden** [comment] 2024-01-22 22:41
Fortunately there hasn't been any issues reported since last version upgrade of plugin over a month ago. That may have solved it. Next time it happens will list the specific query that triggers it.

**Comment by idastambuk** [comment] 2024-01-24 11:19
Hi @wkneewalden, thanks for letting us know, glad that it's working now. Closing this

**Closed by idastambuk** 2024-01-24 11:19 UTC
Labels: area/alerting, triage/needs-confirmation, datasource/OpenSearch
