### ISSUE TITLE
Selected Log Groups for CloudWatch disappear (don't stick)

### ISSUE THREAD

**Issue by datanisse** [grafana/grafana#25470] opened 2020-06-09 07:24 UTC
**What happened**:
Configured Cloudwatch Log Groups disappear / don't stay after saving a dashboard

**What you expected to happen**:
That the configured Log Groups stay

**How to reproduce it (as minimally and precisely as possible)**:
- Create a new panel - Graph
- Cloudwatch as the data source
- Cloudwatch Logs as Query Mode
- Select a Log Group
- Enter an Insight query
- Save the dashboard
- Exit from the panel back to the dashboard
- Edit the panel again and the Log Groups field is empty and you get an error 'Log group is required'

**Anything else we need to know?**:
We have a large number of log groups and only a few are in the drop down list, so you have to copy and paste (or type the log group) and press enter to save

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Cloudwatch
- OS Grafana is installed on: 
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

**Comment by kalzoo** [comment] 2020-06-11 20:45
Also in 7.0.3

**Comment by aocenas** [comment] 2020-06-15 14:51
Seems like duplicate of https://github.com/grafana/grafana/issues/25185

**Closed by aocenas** 2020-06-15 14:51 UTC
Labels: datasource/CloudWatch, datasource/CloudWatch Logs, needs investigation
