### ISSUE TITLE
Failed to start grafana. error: section "tracing.opentelemetry.jaeger" does not exist

### ISSUE THREAD

**Issue by froehl** [grafana/grafana#48177] opened 2022-04-25 11:19 UTC
**What happened**:
Apr 25 13:10:21 server01 grafana-server[9584]: Failed to start grafana. error: section "tracing.opentelemetry.jaeger" does not exist
Apr 25 13:10:21 server01 grafana-server[9584]: section "tracing.opentelemetry.jaeger" does not exist

**How to reproduce it (as minimally and precisely as possible)**:
_grafana.ini:_
..
`
#################################### Distributed tracing ############
[tracing.jaeger]
;address = localhost:6831
;always_included_tag = tag1:value1
;sampler_type = const
;sampler_param = 1
;sampling_server_url =
;zipkin_propagation = false
;disable_shared_zipkin_spans = false

[tracing.opentelemetry.jaeger]
; address = http://localhost:14268/api/traces
`
..

If i set address = http://localhost:14268/api/traces Grafana starts but i have many logs 
'Post "http://localhost:14268/api/traces": dial tcp [::1]:14268: connect: connection refused' 
because I don't have jaeger, of course.

**Environment**:
- Grafana version: 8.5.0
- OS Grafana is installed on: Ubuntu 18.04 (no Docker!)
- User OS & Browser: Firefox 99.0.1 (64-Bit)

**Comment by mellieA** [comment] 2022-04-28 19:59
@froehl I wasn't able to reproduce this on Ubuntu 22.04 and Grafana 8.5.0, can you check if this still exists with 8.5.1 released today?

**Comment by froehl** [comment] 2022-04-29 17:41
Hi @mildwonkey & @mellieA,

I have found the mistake.
In my defaults.ini file the sections [tracing.jaeger] and [tracing.opentelemetry.jaeger] were missing.
But they were set in my grafana.ini. 

I thought the settings would be overwritten by the grafana.ini.

My config files now look like this:
# defaults.ini:

[tracing.jaeger]
address =
always_included_tag =
sampler_type = const
sampler_param = 1
sampling_server_url =
zipkin_propagation = false
disable_shared_zipkin_spans = false

[tracing.opentelemetry.jaeger]
address =

# grafana.ini:

[tracing.jaeger]
;address = localhost:6831
;always_included_tag = tag1:value1
;sampler_type = const
;sampler_param = 1
;sampling_server_url =
;zipkin_propagation = false
;disable_shared_zipkin_spans = false

[tracing.opentelemetry.jaeger]
;address = http://localhost:14268/api/traces

**Comment by papagian** [comment] 2022-05-02 10:52
@froehl thank you for your reply. I will close this since it's actual a configuration issue that is resolved.

Regarding your question:
> I thought the settings would be overwritten by the grafana.ini. In my tests I also uncommented all attributes of the two categories in grafana.ini. But unfortunately that did not work.

As explained in [#45605](https://github.com/grafana/grafana/issues/45605#issuecomment-1056577756) [one should never modify the `defaults.ini`](https://github.com/grafana/grafana/blob/69ee917c8924915cc394ee64705185367079f9f0/conf/defaults.ini#L3https://github.com/grafana/grafana/blob/69ee917c8924915cc394ee64705185367079f9f0/conf/defaults.ini#L3); the default configuration is actually overridden by the `grafana.ini` but if the `defaults.ini` is outdated and there are missing sections from what the server expects then the server will fail to start.

**Closed by papagian** 2022-05-02 10:52 UTC
Labels: needs more info, area/backend/config, needs investigation
