### ISSUE TITLE
bug : metrics query editor - interactive - cannot use the scroll bar

### ISSUE THREAD

**Issue by Daryes** [grafana/grafana#13860] opened 2018-10-27 21:19 UTC
grafana v5.3.2

Firefox v62 (win64)
Datasource : influxdb
Required : more than 11 measurements and/or tags on a metric available in the datasource db.

Reproduce steps : edit or add a new graph panel, select the metrics tab, edit or add a new query.
When clicking on any element that will show either the measurements or the tags list, it will appear with a scroll bar on the right if there are 12 or more items.
Clicking on the scroll bar will close the list, preventing to select any item.
Using the keyboard or the mouse wheel works.

Might be because this scroll bar has the default browser UI, instead of using the Grafana theme like the other scroll bars.

**Comment by torkelo** [comment] 2018-10-28 12:28
duplicate of https://github.com/grafana/grafana/issues/11744

**Closed by torkelo** 2018-10-28 12:28 UTC
