### ISSUE TITLE
Template Variables: Grafana fails to update custom variables on a dashboard load, resulting in incorrect and empty panels

### ISSUE THREAD

**Issue by anubhavcodes** [grafana/grafana#28897] opened 2020-11-06 11:21 UTC
**What happened**:

This is an issue when opening a dashboard with multiple variables using an URL.

We recently upgraded our grafana instances to v7.3.1 from v7.1.5 and looks like the custom variables are no longer resolved on page load and the dashboards are empty.

**What you expected to happen**:

The dashboards should not have shown incorrect components in services resulting in incorrect panels which are empty. The components should have been correctly shown by resolving the custom variables correctly, showing up the correct panels with data from the data source. 

**How to reproduce it (as minimally and precisely as possible)**:

When we open a dashboard with the service and component set via the custom variables we get the following results in the component dropdown, which are incorrect, and it results to the empty panels.  

![index](https://user-images.githubusercontent.com/1628340/98347254-77223800-2017-11eb-924f-4cba5e5ec022.png)

![index](https://user-images.githubusercontent.com/1628340/98347678-062f5000-2018-11eb-8f16-feba56d0fe50.png)

As soon as we change the name of the service and then again select the above services, the correct components are displayed again. 

![image](https://user-images.githubusercontent.com/1628340/98347818-3bd43900-2018-11eb-830e-513e2ee7428f.png)

![image](https://user-images.githubusercontent.com/1628340/98347858-4989be80-2018-11eb-992c-438fb6b80405.png)

These variables are set in the settings of the dashboard, and work well for previous versions <=7.1.5 but not on 7.3.1. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.1
- OS Grafana is installed on: debian-stretch
- User OS & Browser: MacOS Chrome/Firefox/Safari
- Grafana plugins: - No Plugins.

**Comment by papagian** [comment] 2020-11-06 12:37
Thank you for reporting this.
I'm trying to reproduce it; can you provide the following information: what is the type and the refresh settings for those variables?

**Comment by anubhavcodes** [comment] 2020-11-07 15:02
>  what is the type and the refresh settings for those variables?

@papagian Thank you for responding back. The type is **query** and the refresh settings for those variables are `on dashboard load`. 

Let me know if you need any more information.

**Comment by papagian** [comment] 2020-11-09 18:51
I'm unable to reproduce it. However [the dashboard](https://gist.github.com/papagian/c9db332a53f29b31b0d39dc30875ecea) I've tried with may be not the optimal.

**Comment by anubhavcodes** [comment] 2020-11-10 16:03
Thanks, I will try to reproduce the bug myself and share it here, otherwise we will close this issue.

**Comment by anubhavcodes** [comment] 2020-11-17 14:41
@papagian @ivanahuckova @peterholmberg 

I was able to recreate the bug locally. Here is what I did. 

I wrote my own exporter using the python client library as follows: 

```
from prometheus_client import start_http_server, Gauge
import random
import time

COMPONENTS = [
    ['common', 'service1', 'service2'],   #component0
    ['common', 'service3'],               #component1
    ['service4', 'service5', 'service6'], #component2
]


def process_gauge(g: Gauge, c: int):
    component_name = f"component{c}"
    service_name = COMPONENTS[c][random.randint(0, len(COMPONENTS[c]) - 1)]
    if random.randint(3, 4) % 2 == 0:
        g.labels(component_name, service_name).inc(random.randint(1, 100))
    else:
        g.labels(component_name, service_name).dec(random.randint(1, 100))
    time.sleep(random.randint(0,5))


if __name__ == '__main__':
    start_http_server(9000)
    gauge = Gauge('test_gauge', 'A guage to reproduce bug', ['component', 'service'])
    gauge.labels('component1', 'common').set(100)
    while True:
        c = random.randint(0, 2)
        process_gauge(gauge, c)
```

Basically when you run this code, you get metrics exposed as follows: 

![Screenshot 2020-11-17 at 15 32 39](https://user-images.githubusercontent.com/1628340/99402903-28fc1700-28ea-11eb-932e-b26d0b70ff33.png)

I setup a local prometheus server and used docker to quickly spin up a docker container for grafana as follows: 

```
docker container run --rm --publish 3000:3000 grafana/grafana:7.3.1
```

Now I exposed and populated the metrics, and setup m grafana dashboard. There are the custom variables that I set in my grafana dashboard: 

![image](https://user-images.githubusercontent.com/1628340/99403303-99a33380-28ea-11eb-9f99-4aa1f3210b35.png)

![image](https://user-images.githubusercontent.com/1628340/99403340-a3c53200-28ea-11eb-9cb9-9b039261b153.png)

Now, when I click on this link: 

http://localhost:3000/d/WTewptTGk/test-dashboard?orgId=1&from=now-5m&to=now&**var-component=component2&var-service=All**

I should see a dashboard with `component2` and in the dropdown of `service` I should see `service4, service5, service6`. However this is what I see: 

![Screenshot 2020-11-17 at 15 29 22](https://user-images.githubusercontent.com/1628340/99403524-d96a1b00-28ea-11eb-8560-23314873cb84.png)

When you go back to the home screen and then come back to the dashboard, you see the right options in the `service` dropdown

![Screenshot 2020-11-17 at 15 30 51](https://user-images.githubusercontent.com/1628340/99403624-f3a3f900-28ea-11eb-8af5-ceed5ad3fb41.png)

[Here](https://gist.github.com/anubhavcodes/8abf16770eda07916f4c802cb7b80205) is the gist for my config. 

Let me know if there is something I can do to help. I can create a docker image / docker-compose config that makes it easier to test this out. I am very happy to help out further.

**Comment by hugohaggmark** [comment] 2021-03-11 11:10
Hi @anubhavcodes and so sorry for the very late reply. I've created a similar dashboard here https://play.grafana.org/d/S17wM-UGz/template-variables-grafana-fails-to-update-custom-variables-on-a-dashboard-load-resulting-in-incorrect-and-empty-panels-28897?orgId=1&var-instance=demo.robustperception.io:9090&var-job=All and I can't recreate the issue you're describing.

I can see one issue with the information you've added and that is you're using `Never` on the `Variable Refresh` setting. Try changing that to `On Dashboard Load` instead and I think it will work.
![image](https://user-images.githubusercontent.com/562238/110778371-8f72bf80-8262-11eb-920b-75d51a3e6491.png)

I'm closing this issue now, but we can always reopen it if more evidence is provided that this is an issue.

**Closed by hugohaggmark** 2021-03-11 11:10 UTC
Labels: area/dashboard/templating, needs investigation

**Comment by anubhavcodes** [comment] 2021-03-12 13:09
@hugohaggmark , thanks for the conclusion. I guess this issue was fixed in one of the future updates, as you already mentioned in one of the [other issues](url)
