### ISSUE TITLE
new feature? Display time difference when selecting a range on the graph

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#14968] opened 2019-01-21 11:45 UTC
Would be nice to see in some case the length of a period when selecting it in the graph, so you do not need to calculate/estimate it yourself.

![add-time-difference](https://user-images.githubusercontent.com/13450219/51472595-3ee63280-1d7a-11e9-9f9a-23cfbdd81588.png)

Then maybe also allow esc to cancel the selection, now it automatically zooms in.

**Comment by torkelo** [comment] 2019-01-21 11:49
would be nice, duplicate of https://github.com/grafana/grafana/issues/13453

**Closed by torkelo** 2019-01-21 11:49 UTC
