### ISSUE TITLE
[Feature Request] Composite Panels

### ISSUE THREAD

**Issue by rfriedma** [grafana/grafana#22662] opened 2020-03-09 21:57 UTC
**What would you like to be added**:
I would like a way to make a composite panel that can be repeated by variable. My mental model is basically what a "Row" lets you do today but doesn't span the entire width of the screen. A panel that you could compose with other panel types and repeat as a group.

**Why is this needed**:
I want more complex status panels (Single stat + small table/text + small graph) without writing it in code. I just want to compose smaller panels together and have them repeat. One example is a "Server status" grouping that combines a health status/gauge, connected users (or CPU) over time and descriptive text/table about the server. I want better utilization of the space so that users don't have to scroll vertically down a page and could instead see them wrap more compactly like any other repeated panel.

**Comment by torkelo** [comment] 2020-03-10 10:12
duplicate of https://github.com/grafana/grafana/issues/10916

**Closed by torkelo** 2020-03-10 10:12 UTC
