### ISSUE TITLE
Slack notifications do not work

### ISSUE THREAD

**Issue by 4szt4l** [grafana/grafana#10912] opened 2018-02-14 15:35 UTC
Hi all,

I have problems with Slack webhooks. When I use 'Send Test', it works without any problems, but not from the Alerts having from v4.6.3. The evaluation is good, I can see the green/red hearts and the Test Rule gives correct output as well

Please include this information:
- What Grafana version are you using?
v5.0.0beta
- What datasource are you using?
InfluxDB 1.3.5
- What OS are you running grafana on?
Ubuntu 14.04
- What did you do?
nothing, but upgraded from 4.6.3
- What was the expected result?
everything is working fine
- What happened instead?
slack notifications are not sent:
t=2018-02-14T13:54:01+0100 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2018-02-14T13:54:01+0100 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=74 notification=Slack
t=2018-02-14T13:54:01+0100 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook=Slack
t=2018-02-14T13:54:01+0100 lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"

E-mail notifications are working fine.  Thanks for any feedback.

**Comment by bergquist** [comment] 2018-02-15 08:01
Does the graph panel have a table legend to the right by any chance?
Sounds like it can be related to https://github.com/grafana/grafana/issues/10526

**Comment by 4szt4l** [comment] 2018-02-15 08:11
Yes it's on the right!

**Comment by bergquist** [comment] 2018-02-15 08:28
Ok. Then I'm closing this since its a dupe of #10526

**Closed by bergquist** 2018-02-15 08:28 UTC
Labels: state: needs more detail
