### ISSUE TITLE
[Feature request] Visualise values from legend

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#11295] opened 2018-03-19 11:51 UTC
When having for example _max_ and _avg_ values displayed in the legend I'd like to be able to display each value in graph as a horizontal line like in screenshot below:

![image](https://user-images.githubusercontent.com/327717/37593976-39458cb6-2b74-11e8-8ff7-e0ba03512241.png)

This is how it would look like when _avg_ is marked to be displayed in graph. Line at 242 mbps and 565 kbps is drawn.

**Comment by bergquist** [comment] 2018-03-20 08:00
Dupe of https://github.com/grafana/grafana/issues/159 or https://github.com/grafana/grafana/issues/922

**Closed by bergquist** 2018-03-20 08:00 UTC
