### ISSUE TITLE
[Feature request] links to Graph, copy graph to another dashboard

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2593] opened 2015-08-24 21:59 UTC
It will be good if graph can be an entity that can be linked to, copied from one dashboard to another dashboard.

**Comment by torkelo** [comment] 2015-08-25 06:45
yes, would be great :) 

dupe of https://github.com/grafana/grafana/issues/1803

**Closed by torkelo** 2015-08-25 06:45 UTC
