### ISSUE TITLE
Alerting: Grafana 10.1 no longer shows existing labels as options when creating a new alert

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#75046] opened 2023-09-18 21:21 UTC
### What happened?

We recently upgraded from 10.0.x to 10.1.1 and one change I noticed in the UI is that when creating new alerts, existing labels are no longer being shown as options.  Not sure why this would have been removed but I feel like it's helpful to see what labels already exist and to have the choice to pick from them.  This is under section 5 when creating an alert.

### What did you expect to happen?

Existing tags to be shown, as it was in 10.0.x

### Did this work before?

Yes

### How do we reproduce it?

1.  Create an alert and at the bottom on step 5 go to add labels and you do not get prompted with choices for existing ones.
2.
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: grafana/grafana:10.1.1
OS: Mac OS Monterey
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by danfinn** [comment] 2023-09-21 19:21
I just noticed that if I create an alert and then come back to it, these existing labels do then get shown as options so it seems like it's just when you initially create the alert for whatever reason.

**Comment by usmangt** [comment] 2023-09-21 21:04
:Hi @danfinn,

Thanks for opening this issue.

Can you please share a screenshot or a small screencast/gif file so that we can see how you are able to notice the issue.

Thanks

**Comment by usmangt** [comment] 2023-09-27 17:09
Based on your steps of reproduction, I was also able to reproduce it on my test machine.

I will forward this issue to our Engineers so that they can have a look and analyse it.

Please provide the previous Grafana version in which this feature used to work as it will be a valuable information for analysis

**Comment by danfinn** [comment] 2023-09-27 17:19
Previously we were on 10.0.2

**Comment by armandgrillet** [comment] 2023-10-04 09:26
Can you confirm that you have existing alert rules with labels and give us more reproduction steps? We checked on Grafana 10.1.1 and were unable to reproduce, we see existing labels as options: 

![image](https://github.com/grafana/grafana/assets/2117580/d70300f2-2416-491f-8c77-3d83929e2b6b)
![image](https://github.com/grafana/grafana/assets/2117580/7572e8d7-8982-49bb-8aaa-3fd005c3e180)

**Comment by danfinn** [comment] 2023-10-04 17:11
@armandgrillet are those provisioned labels or ones you added manually?  Maybe there is something "special' about lables that were provisioned.

I will try to get a screen capture today.

**Comment by danfinn** [comment] 2023-10-04 18:10
![grafana_bug](https://github.com/grafana/grafana/assets/5891946/34ba7f4e-af17-449c-9751-d1161f0e72b1)

**Comment by danfinn** [comment] 2023-10-04 18:13
![grafana_bug](https://github.com/grafana/grafana/assets/5891946/795b15c6-e37c-4858-b6f9-7a656c56f0d0)

**Comment by soniaAguilarPeiron** [comment] 2023-11-08 11:51
I could reproduce the issue in the v10.1.1 release. And I can confirm this issue has been fixed in the latest version.

**Closed by soniaAguilarPeiron** 2023-11-08 11:51 UTC
Labels: type/bug, area/alerting, area/frontend
