### ISSUE TITLE
React datasources lack access to the templateSrv

### ISSUE THREAD

**Issue by seanlaff** [grafana/grafana#20807] opened 2019-12-02 15:43 UTC
I want to support report variables in my react datasource but the types/getters are not exposed. 

Maybe we can expose it the same grafana/runtime exposes types and getters for the backendSrv (although Im not sure if there are greater plans for refactoring templating), i.e..
```ts
import { BackendSrv, getBackendSrv } from '@grafana/runtime';
```

As a work-around I tried extending my constructor to pick it up as it would in angular, ie
```ts
constructor(instanceSettings: DataSourceInstanceSettings<MyOptions>, backendSrv: BackendSrv, templateSrv: any) {
```
However having these extra args causes the plugin to get rendered in angular mode (which breaks) via
https://github.com/grafana/grafana/blob/a7a9bcbcbb6ce9e9bf986f4691ee047b22f736fe/public/app/features/plugins/datasource_srv.ts#L83

**Comment by torkelo** [comment] 2019-12-02 22:20
dupe of https://github.com/grafana/grafana/issues/19058

**Closed by torkelo** 2019-12-02 22:20 UTC
