### ISSUE TITLE
Documentation: can't build docs

### ISSUE THREAD

**Issue by aerickson** [grafana/grafana#18399] opened 2019-08-06 07:17 UTC
**What happened**:

I'm working on a fix for https://github.com/grafana/grafana/issues/18274 and wanted to build the docs to see my change. I tried to follow docs/README.md, but encountered issues.

**What you expected to happen**:

I expected to be able to build and view docs locally.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the included steps in the README.md. 

The first command results in an error:

```
git clone https://github.com/grafana/website
```

That repo doesn't exist. I've gotten further, but have encountered more errors.

**Anything else we need to know?**:

No.

**Environment**:
grafana git master at 541981c3411201c75abee6f806a2cd79c0517f15
Docker Engine: 18.09.2
OS X 10.14.6 (18G87)

**Comment by marefr** [comment] 2019-08-06 09:14
Duplicate of #18076

**Closed by marefr** 2019-08-06 09:14 UTC
