### ISSUE TITLE
Explore throws 404 error on /api/v1/rules with Mimir as Source

### ISSUE THREAD

**Issue by m-wack** [grafana/grafana#53451] opened 2022-08-09 10:43 UTC
I have setup Mimir in Kubernetes using the following config:

alertmanager:
enable_api: false
ruler:
enable_api: false

I am using Mimir 2.2.0 and Grafana 9.0.1.

I am using Mimir as a Prometheus Datasource in Grafana with
manageAlerts: false

However, when going into Explore in Grafana and selecting the Mimir source, Grafana does a Request to:
/api/datasources/4/resources/api/v1/rules

This results in a 404 Not Found Banner shown in Grafana. Everything is working though, I can do queries, I see stuff. It's just that this error pops up everytime. 

I am also using Loki as a Datasource, also with the Ruler disabled and manageAlerts set to false in Grafana, and it does not throw this error. 
The Mimir Team told me this seems to be a Grafana Issue.

Any idea why this happens?

Regards

**Comment by mellieA** [comment] 2022-08-15 19:24
@m-wack was there a previous issue/discussion with the mimir team you can reference here for context? 

To help me route this to the right squad, are you only seeing the error in explore or is it showing up in other places when you reference your mimir datasource?

I tried this using the docker tutorial environment at https://grafana.com/tutorials/play-with-grafana-mimir/ and edited the mimir configuration to set `enable_api: false` for alertmanager and ruler settings: 

```
alertmanager:
    data_dir: /data/alertmanager
    enable_api: false
    external_url: http://localhost:9009/alertmanager
. . . 
ruler:
    alertmanager_url: http://127.0.0.1:8080/alertmanager
    enable_api: false
```

I added a new mimir datasource and disabled managing alerts: 

![Screen Shot 2022-08-15 at 1 22 41 PM](https://user-images.githubusercontent.com/18175287/184702789-38ce65e6-687a-4da2-b877-1dd571717712.png)

The tutorial is using mimir 2.2.0 and Grafana 9.0.7

**Comment by m-wack** [comment] 2022-08-19 07:28
@mellieA sorry for the late reply, I was on vacation.
The discussion with the Mimir Team is rather short. It's here:

https://github.com/grafana/mimir/discussions/2668

Regarding the disabled Ruler and Alertmanager API, I also tried enabling it for testing and the 404 stayed the same. 

Your configuration above looks like what I'm trying to use.

It's not quite clear for me, if the request that's issuing the 404, is going to Mimir itself or Grafana queries its own API there.
The URL is https://grafana.example.com/api/datasources/4/resources/api/v1/rules

Is that trying to query Mimir or Grafana's API there?

**Comment by mellieA** [comment] 2022-08-19 16:58
Ok, I'll see if the squad that knows the prometheus datasource can help figure out if this is coming from the datasource or the explore code

**Comment by evandandrea** [comment] 2022-08-23 15:06
We think this may be fixed. @gtk-grafana is going to check Mimir against the 9.x versions to confirm the version it's fixed in.

**Comment by m-wack** [comment] 2022-08-24 07:45
Sounds good, thank you for the feedback. 
Let me know if you have a specific version of Grafana I should try out.

**Comment by gtk-grafana** [comment] 2022-08-24 14:20
@m-wack  I was able to reproduce this on 9.0.2, but not 9.0.5 or 9.1.0, looks like we had forgotten to silence the UI error when we're checking for rules support (that API endpoint is expected to fail on some versions of prometheus/mimir), so this shouldn't impact any functionality, but if you get annoyed by the error message showing up every time you're in explore, you should be able to upgrade and this should go away.

Make sure to let us know if you're still having any trouble!

**Closed by gtk-grafana** 2022-08-24 14:20 UTC
Labels: prio/low, datasource/Prometheus, triage/needs-confirmation
