### ISSUE TITLE
[ngalert/cloudwatch] Grafana8 unified alerting  behaviour with Cloudwatch metrics + template variables  

### ISSUE THREAD

**Issue by awsiv** [grafana/grafana#37850] opened 2021-08-12 16:03 UTC
**What happened**:
Trying to create an alert from a cloudwatch metrics panel with template variables, I get `Failed to evaluate queries and expressions: failed to execute conditions: failed to query data: MissingEndpoint: 'Endpoint' configuration is required for this service` 

![image](https://user-images.githubusercontent.com/1265825/129228837-fb5eb1c3-c3fd-449f-9ffd-99d0358865e8.png)

The alert itself seems to be working if I save it (meaning it will fire and resolve correctly), but it still complains with the following:
![image](https://user-images.githubusercontent.com/1265825/129228863-faad87e8-7ae4-490b-973a-3a09a54c88e7.png)

Which makes me wonder which value is being used for the template variables `$region` and `$ecsCluster` 

**What you expected to happen**:
It would be good to allow users to select the template variables for testing when alerts are being created, similar to how we can select them in the `Explore` page.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard panel with cloudwatch datasource and use region as template variable.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.1 (90c87a52f7)
- Data source type & version: Cloudwatch metrics
- OS Grafana is installed on: Docker/fargate
- User OS & Browser: Chromium
- Grafana plugins: cloudwatch
- Others:

**Comment by kylebrandt** [comment] 2021-08-16 12:57
This should work in 8.2, as I believe this is a duplicate of https://github.com/grafana/grafana/issues/37061 , which has a merged PR slated for 8.2 release.

**Closed by kylebrandt** 2021-08-16 12:57 UTC
Labels: datasource/CloudWatch, area/unified-alerting
