### ISSUE TITLE
Support Log -> Tracing linking in "log" panel type

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#28724] opened 2020-11-01 21:41 UTC
**What would you like to be added**:
Currently, I am able to setup log -> tracing linked like in this post https://grafana.com/blog/2020/10/27/announcing-grafana-tempo-a-massively-scalable-distributed-tracing-system/. However, this is not possible on the logs panel as far as I can tell. 

Note: its possible I cannot due this due to https://github.com/grafana/grafana/issues/28723. Not sure if the logs are supposed to be expandable in the log panel view like explore or not.

If this is added, it may also make sense to allow derived fields to be configured per panel as well. It seems odd to be at the data source level because we may have many panels which want different links, many different formats of logs, and may even format the same log two different ways in two different panels with `log_format`. I can break this into its own issue if desired.

**Why is this needed**:
Would like a single pane of glass with metrics+logs for my service with links to traces.

**Comment by aocenas** [comment] 2020-11-02 12:59
@howardjohn Thanks for the input. Yeah this is an issue of not actually having the log row detail component inside the logs panel in dashboards. There are some UX issues with that in addition with the config that you already mention, we hope to figure this out but right now isn't highly prioritized so don't have any timelines for this.

**Comment by ivanahuckova** [comment] 2021-05-05 09:00
Duplicate of https://github.com/grafana/grafana/issues/22271. When Log Details is implemented in logs panel, log -> tracing will be part of it.

**Closed by ivanahuckova** 2021-05-05 09:00 UTC
Labels: area/panel/logs, type/feature-request
