### ISSUE TITLE
Alerting: Notifications are sent to the wrong contact point with nested policies

### ISSUE THREAD

**Issue by DohanKim** [grafana/grafana#80265] opened 2024-01-10 05:49 UTC
### What happened?

<img width="1930" alt="Screenshot 2024-01-09 at 6 35 51 PM" src="https://github.com/grafana/grafana/assets/6930365/f0eb8857-53bd-49bf-a64b-ad70dcd094a3">
<img width="788" alt="Screenshot 2024-01-10 at 12 41 44 AM" src="https://github.com/grafana/grafana/assets/6930365/1be5d4bd-561c-45b0-a018-6b81efd769c2">

### What did you expect to happen?

Even though an alert is recognized as "message =~ .:closed." and shows "1 instances" on the policy,
notification is being sent to "slack-alerts" (see the first screenshot) instead of "slack-warnings" which is the contact point of the parent's policy, not the children's.

### Did this work before?

No

### How do we reproduce it?

1. Configure a receiver R1 in the default notification policy
2. Create a child policy A that matches foo = bar label and do not define a receiver
3. Create a child policy X under A that matches x = y label and defines a receiver R2
4. Create an alert with labels foo = bar and x = y
5. Confirm in Preview Routing that policy X is used.
6. Cause the alert to trigger and send a notification
7. Confirm if the notification was sent to receiver R1 or R2

### Environment (with versions)?

Grafana: 
Grafana v10.3.0-64399 
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment] 2024-02-07 09:37
/duplicate of #75307

please wait for the team to answer on the existing issue
we appreciate your patience
thank you

**Closed** 2024-02-07 09:37 UTC
Labels: type/duplicate
