### ISSUE TITLE
Legends with option "As Table and To The Right" out of rows and borders on iOS Safari

### ISSUE THREAD

**Issue by fanvinga** [grafana/grafana#27834] opened 2020-09-26 04:03 UTC
**What happened**:
![IMG_2422](https://user-images.githubusercontent.com/26292849/94329606-169ee480-ffef-11ea-824d-0a389c96adcc.jpg)
![IMG_2423](https://user-images.githubusercontent.com/26292849/94329607-1868a800-ffef-11ea-9fc6-7b2c128dc0c5.jpg)

**What you expected to happen**:
* Displays correctly within the boundary like the To The Right option is turned off
![image](https://user-images.githubusercontent.com/26292849/94329659-9f1d8500-ffef-11ea-8df5-f7eb46462a90.png)

**How to reproduce it (as minimally and precisely as possible)**:
* Use Safari to view some legend table with To The Right option turned on

**Anything else we need to know?**:
* If you try to set the screen to iPhone X in chrome developer tools everything works fine, but it's actually misaligned in safari!

**Environment**:
- Grafana version:Grafana v7.2.0 (efe4941ee3)
- Data source type & version:Prometheus v2.21.0
- OS Grafana is installed on:Grafana Docker Image on Debian Linux
- User OS & Browser:iOS 14.0 & Safari 14
- Grafana plugins:none
- Others:

**Comment by torkelo** [comment] 2020-09-28 10:39
duplicate of https://github.com/grafana/grafana/issues/27676

**Closed by torkelo** 2020-09-28 10:39 UTC
