### ISSUE TITLE
Explore: "Add data source" should use root_url

### ISSUE THREAD

**Issue by stalks** [grafana/grafana#22027] opened 2020-02-08 13:12 UTC
**What happened**:
Setup grafana in docker behind nginx reverse proxy.
Click Explore >> Add data source redirects me to /datasources/new, resulting in 404

**What you expected to happen**:
Should redirect to /grafana/datasources/new

**Environment**:
- Grafana version: 6.6.1 (docker/alpine)
- Data source type & version: mysql, mariadb 10.4
- OS Grafana is installed on: alpine docker in a debian10 docker host
- User OS & Browser: Win10 Chrome
- Grafana plugins: alexanderzobnin-zabbix-app
- Configs

*nginx.conf:*
```
location /grafana/ {
        proxy_pass  http://grafana:3000/;
    }
```
*grafana.ini:*
```
root_url = %(protocol)s://%(domain)s/grafana/
```
*docker-compose.yml:*
```yaml
version: '3.1'

services:
    grafana:
        image: grafana/grafana:6.6.1
        container_name: grafana
        volumes:
            - etc:/etc/grafana
        environment:
            - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
        networks:
            - net
            - proxy
    sql:
        image: mariadb:10.4
        container_name: grafana-sql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root-dbpasswd
            - MYSQL_DATABASE=grafana
            - MYSQL_USER=grafana
            - MYSQL_PASSWORD_FILE=/run/secrets/grafana-dbpasswd
        volumes:
            - sql:/var/lib/mysql
        networks:
            - net
            - pma
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-u", "healthcheck"]
            timeout: 20s
            retries: 10
        secrets:
            - root-dbpasswd
            - grafana-dbpasswd

secrets:
    root-dbpasswd:
        file: ./secrets/root-dbpasswd.secret
    grafana-dbpasswd:
        file: ./secrets/grafana-dbpasswd.secret


volumes:
    etc:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /data/docker/volumes/grafana-etc
    sql:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /data/docker/volumes/grafana-sql

networks:
    net:
        driver: bridge
    proxy:
        external:
            name: shared-proxy
    pma:
        external:
            name: shared-pma
```

**Comment by clsack** [comment] 2020-02-26 17:43
Hi, I'm having the same issue but with another endpoint.
Grafana version:
```
{
  "commit": "3fa63cfc34",
  "database": "ok",
  "version": "6.6.2"
}
```

Using centos 7, no grafana plugins, no docker.

nginx conf:
```
location /grafana/ {
        proxy_pass  http://127.0.0.1:3000/;
    }
```

grafana root_url
`root_url = %(protocol)s://%(domain)s/grafana/`


Steps:
1. Dashboards > Grafana metrics
2. Select 'Explore' in some component

It redirects to ip:port/explore... instead of ip:port/grafana/explore...
So far, other links are working as expected.

**Comment by luizribeiro** [comment] 2020-03-01 16:17
@clsack, I'm also having this issue. I believe it was caused by PR #22202 while trying to fix issue #22201.

**Comment by dprokop** [comment] 2020-04-03 09:16
@stalks are you still experiencing this issue? It should be fixed now.

**Comment by dprokop** [comment] 2020-04-07 19:25
@luizribeiro what Grafana version are you using?

**Comment by luizribeiro** [comment] 2020-04-08 01:39
Not sure which version I was using back then, but I'm on 6.7.2 and I can't reproduce this bug anymore.

**Comment by dprokop** [comment] 2020-04-08 06:19
Thanks @luizribeiro! I'm closing this issue then.

**Closed by dprokop** 2020-04-08 06:19 UTC
Labels: area/explore, area/frontend, needs more detail, type/bug
