### ISSUE TITLE
[MySQL-Feature request] Control quoting in SQL-queries when using template variables

### ISSUE THREAD

**Issue by breadcrump** [grafana/grafana#9030] opened 2017-08-13 11:48 UTC
Hi guys,

im working with grafana to display data from a mysql-db.
Now i wanted to use the templating-feature. So i just created a variable of custom type and inserted the table names which i wanted to access.
If i call the variable with "$table" (table is the name of the variable i created), it sends the statement with doubled quotes to the database. 
Example of the db-request:

SELECT * FROM "table" WHERE id = 1;

The database then tells me, that something in the statement is wrong (of course, because theres no table with the name "table", rather it´s name is table). It would be nice, if there would be a feature to disable the double-quotes.
Let me know, if someone needs further information.

**Comment by daniellee** [comment] 2017-08-13 12:21
@torkelo I'm thinking it might be better to remove the double quote interpolation. It's kind of unnatural/confusing for MySQL.

**Comment by torkelo** [comment] 2017-08-13 18:58
Though it only did that for multi value, which it needs to do it, is doing it for single value as well, then I agree it should not

**Comment by breadcrump** [comment] 2017-08-13 21:23
I think it does quoted interpolation for multi value as well as single value. I'll test it tomorrow and give you some reply.

**Comment by breadcrump** [comment] 2017-08-14 11:27
Hi all together,

today I tested the string-interpolation behavior for single value variable.
It also quotes the chosen value before the statment is sent to the database.
So I also get the response from the MySQL-DB, that there is a syntax failure.

**Comment by svenklemm** [comment] 2017-10-17 21:09
Since grafana already has 2 ways to pull in variable values it would be nice to have 1 be quoted and the other raw.

- $var could return values quoted
- [[var]] could return values unquoted

Having a way to get unquoted variables would be really useful for the postgres datasource aswell.

**Comment by svenklemm** [comment] 2017-10-18 17:39
@torkelo @daniellee do you think it would be a good idea to separate $var and [[var]] that way for mysql and postgres?

**Comment by torkelo** [comment] 2017-10-19 05:36
No, those two have a separate purpose, the first one can only be used when not surrounded by word chars, the alt syntax is there to accommodate those scenarios

**Comment by svenklemm** [comment] 2017-10-19 06:21
I know those differences but since variables are quoted in both cases you cant really use them surrounded by word chars. Because of the quoting the following example would never work: 
```sql
WHERE field = 'prefix[[var]]suffix'
```
Influxdb doesnt quote variables for example so you can use them inside of expressions. In sql there is no need for matching inside word boundaries cause the quotes separate the value.

**Comment by daniellee** [comment] 2017-10-24 12:08
Fixed by #9611

**Closed by daniellee** 2017-10-24 12:08 UTC
Labels: datasource: MySQL

**Comment by towolf** [comment] 2017-10-29 13:44
@svenklemm @torkelo with this change my queries broke, which I cobbled together to support multiple dropdowns as filters in templating.

Since I wanted to support single selection, multi selection and an 'all' value as `*` I devised this clause:
![image](https://user-images.githubusercontent.com/345210/32144325-774c59da-bcb7-11e7-8009-818c91ab8875.png)

1. If 'all' value is select, it short-circuits.
2. If multi-selection it inserts a quoted array ('choice1', 'choice2')
3. If single item is selected in dropdown it inserts (choice1), and that fails

This worked before, how do I handle that now?

**Comment by svenklemm** [comment] 2017-10-29 15:20
@towolf, you are right with the current approach you can't do template variables with multi-value and select only a single item. For that to work you need the variables always returned quoted. 
I suggested always returning quoted entries when using $var and unquoted when using [[var]] which would allow both use cases.

**Comment by towolf** [comment] 2017-10-29 15:22
Yes, I would love to be able to select either one of these.

 I agree that unquoted style is useful in other scenarios. We would need both.

**Comment by svenklemm** [comment] 2017-10-29 15:38
After checking the source code we wouldnt need to differentiate between $var and [[var]] but could instead always return quoted values when the variable allows multi selection.

**Comment by md100play** [comment] 2017-10-29 15:41
What about adding a macro function that would take a multi-selection variable and output the way it currently works? Without using the macro it will use the unquoted version as in the accepted pull request.

**Comment by torkelo** [comment] 2017-10-29 15:55
Yes, that is how it should work and is implemented for other datasources, when multi or all value enabled values are always quoted

**Comment by joriws** [comment] 2017-10-30 18:31
For me the use case is also templating table name (show tables) which
currently does not work and sql returns error

select id,name from $Table

29.10.2017 17.56 "Torkel Ödegaard" <notifications@github.com> kirjoitti:

Yes, that is how it should work and is implemented for other datasources,
when multi or all value enabled values are always quoted

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/grafana/grafana/issues/9030#issuecomment-340272474>,
or mute
the thread

**Comment by svenklemm** [comment] 2017-10-30 19:46
@joriws your use case already works in master branch since #9611 got merged into master branch, but it didnt make it into 4.6.0

**Comment by joriws** [comment] 2017-11-30 11:53
@svenklemm Thanks - would it also work with SELECT WHERE something LIKE '%$Templated%' -type of query because with current it does not. 

I also tried LIKE '%' || $Templated || '%' but that returns too much..

The issue is that under Templated I've a substring from middle of SQL column and I need to return all.

**Comment by joriws** [comment] 2017-11-30 12:01
Ok I see that I can LIKE concat('%',$Template,'%') to have the effect..

**Comment by svenklemm** [comment] 2017-11-30 14:41
In the next major version ```LIKE '%$Templated%'``` will work in 4.6.x you need the concat workaround

**Comment by joriws** [comment] 2017-12-01 08:30
I'd really love removing all quoting engine by MySQL datasource. We can do manually quoting where needed. Bonus is that datasource is much more simplified because it does not need to know MySQL syntax?

As my next scenario is to have Templated variable with custom setting integer values like "90, 95, 99" which then are used in SELECT to count user selectable percentiles like

"$Percentile / 100 * COUNT(*)"

ref. https://stackoverflow.com/questions/19770026/calculate-percentile-value-using-mysql

**Comment by easyterra** [comment] 2017-12-14 19:00
I have setup a template that returns mysql table names. I was planning on using these values to dynamically switch between tables, but the single quotes are still in use? Could it be that the Grafana Cloud is not updated yet?

Resulting SQL:

```
SELECT
  timestamp as time_sec,
  SUM(bookings) as value,
  site_domain AS metric

FROM 'ri_ymd'
WHERE timestamp > 1505498394
```

**Comment by ThuyLeVn** [comment] 2018-01-25 08:32
$value     SELECT COLUMN [[column]] FROM [[table]]; 
==> it is not run. which template variable????

**Comment by vipin-pink** [comment] 2018-02-26 15:05
@ThuyLeVn 

I have opened a pull request for postgres which resolved the problem of quotes for me : 
- https://github.com/grafana/grafana/pull/11021 

If you need something similar on mysql i can have that integrated as well. Do let me know or you can adapt similarly if you have time to include MYSQL code.

Cheers!
