### ISSUE TITLE
Table panel: fixed header does not scroll horizontally

### ISSUE THREAD

**Issue by thallesferraz** [grafana/grafana#17784] opened 2019-06-26 17:14 UTC
Hi , i'm with another problem in dashboard with table dynamic the first line is fixed moving the scroll.

![issue](https://user-images.githubusercontent.com/52176159/60200474-905c8700-981c-11e9-8261-412806cc6b3d.gif)

**Comment by dprokop** [comment] 2019-06-27 08:18
@thallesferraz thanks for reporting. The fixed header is a feature, but the fact that it doesn't scroll in horizontal direction seems to be a bug.

**Comment by ryantxu** [comment] 2019-06-27 21:45
There are a bunch of open issues for this same problem... see #4157

These are all fixed in the react table... but that does not yet support the other features...

**Comment by torkelo** [comment] 2019-07-01 08:34
related to this , https://github.com/grafana/grafana/issues/4157

**Comment by wernerdaehn** [comment] 2019-08-29 12:22
@torkelo The request to show correct data is a feature request???

Interesting values for dates and currencies are shown here. (I scrolled to the right and since the header does not move, the header does not match the columns.)

![image](https://user-images.githubusercontent.com/13607767/63939696-29e82500-ca68-11e9-9e2f-562abd3b07dc.png)

**Comment by BrandonQDixon** [comment] 2019-08-29 14:40
This is definitely a bug, and calling it a 'feature request' and not a bug is dishonest in my opinion.

**Comment by torkelo** [comment] 2019-10-11 07:36
duplicate of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2019-10-11 07:36 UTC
Labels: area/frontend, area/panel/table, type/feature-request
