### ISSUE TITLE
2.6.0b1 - Query builder with Graphite doesn't select item with mouse consistently

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#3428] opened 2015-12-04 19:30 UTC
Steps to reproduce:
1. edit a graph (play.grafana.org, logins graph for example)
2. click 'select metric' and then find a metric in the list and use your mouse click to select it
3. observe that the 'select metric' text is still displayed
4. click 'select metric' again and use your keyboard to highlight a choice and enter to select it
5. observe that the choice is displayed properly and you can navigate deeper into the tree

A few times my mouse has worked to select an item, but usually it doesn't.  Selecting with enter works every time.

**Comment by torkelo** [comment] 2015-12-04 20:20
I think it is a timing issue, I can only replicate it when I click and hold an item. If I click normally I never get the scenario you describe. 

Anyway should be fixed. Will check if the same issue is present in older versions.

**Comment by torkelo** [comment] 2015-12-04 20:22
the same problem is present in older versions as well, can you replicate this when clicking normally?

**Comment by maddenca** [comment] 2015-12-04 21:00
Now that you mention, in older versions I also noticed it a little here and there but just thought it was my poor clicking accuracy.  But now on 2.6 it is much more apparent.  Like it often takes 4-6 clicks before I can get it to accept it which is pretty unworkable.  The speed of scrolling in the list doesn't matter, it just seems random.  Fortunately the keyboard enter key works to select every time :-)

I run win 8.1 and have the same behavior in chrome and firefox.

**Comment by torkelo** [comment] 2015-12-06 09:14
found the cause and fixed it!

**Closed** 2015-12-06 09:14 UTC

**Comment by maddenca** [comment] 2015-12-10 07:51
verified fix in 2.6b2; thanks for the efforts!
