### ISSUE TITLE
[Bug] Grafana 4.3.1 - graph on the logarithmic scale is distorted

### ISSUE THREAD

**Issue by alxrem** [grafana/grafana#8475] opened 2017-05-26 08:23 UTC
Reproducible with grafana from docker image grafana/grafana:4.3.1 and browsers Firefox 52.1.1 and Chromium 58.0.3029.96

On some graph select on Axes tab `Scale log (Base 10)` and `Y-Min 0`.

![dash-log](https://cloud.githubusercontent.com/assets/123157/26486741/1f5bafaa-4205-11e7-9314-0edbbf443535.png)

**Comment by daniellee** [comment] 2017-05-26 08:57
Dupe of #8244. It is fixed in master and will be released in a patch version (v3.4.2) very soon.

**Closed by daniellee** 2017-05-26 08:57 UTC
