### ISSUE TITLE
Add functions to format variable values

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#15007] opened 2019-01-23 13:00 UTC
It can happen that formating is needed to be applied to some variables.

With prometheus when using histograms you have the name of the histogram bucket in a label called `le` (for lesser equal). It represent a numerical value that is the upper limit of a bucket and prometheus use exponential notation when the value becomes big.

![screenshot_35](https://user-images.githubusercontent.com/153052/51608084-c4064e80-1f16-11e9-8eac-73175a7e1bb1.png)

It would be nice if grafana would allow the use of formatting functions on variables like in go templates, e.g. : `{{ le | exp2dec | bytes }}`

**Comment by torkelo** [comment] 2019-01-23 17:10
duplicate of https://github.com/grafana/grafana/pull/6627

**Closed by torkelo** 2019-01-23 17:10 UTC
