### ISSUE TITLE
[Windows] [Generic OAuth]: Remote endpoint parsing from the config results in broken redirects.

### ISSUE THREAD

**Issue by OrionDevelopment** [grafana/grafana#28803] opened 2020-11-04 09:00 UTC
**What happened**:
Generic Oauth configuration seems to parse the wrong URLs when it runs under windows.
This causes redirects to happen relative instead of absolute making the generic oauth system not work on windows, due to the fact that grafana does not run the OAuth2 endpoint but still redirects the calls to itself, instead of to the remote system.

**What you expected to happen**:
Grafana should parse the urls as specified in the custom.ini file and use them as absolute urls when redirecting on login.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a windows grafana setup with an external OAuth2 provider (Eg. IdentityServer4 or KeyCloak) under a different domain.
2. Configure the OAuth2 provider with a client for Grafana.
3. Configure the generic Oauth2 section in Grafana and target the three required URLS to the reference the external OAuth2 provider on a different domain.
4. Try to login via the remote OAuth2, provider. Notice that the login fails and grafana redirects to itself. When opening the browser devtools and reading the network details, notice that all redirects (even for the ones that should target the remote provider), have the grafana domain, but the right url structure behind the domain as configured in the custom.ini file.

**Anything else we need to know?**:
The same configuration works on linux machines (At least under a container infrastructure)
Reproduced on different machines, with different domains.
Logins via the buildin authentication handler still work.

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Not related. But MSSQL Server 2017
- OS Grafana is installed on: Windows Server 2019 Datacenter AZURE VM.
- User OS & Browser: Windows 10 Pro 2004, happens in Chrome, Edge, and Firefox
- Grafana plugins: Clock panel, video panel, piechar panel, vonage status panel
- Others: Running behind a dual reverse proxy: NGinx reverse proxy, to split tenant related logic to the right machine, then IIS reverse proxy using URL Rewrite module, to handle the internal running of grafana next to IIS.

**Sample configs**
- Windows Grafana: https://gist.github.com/OrionDevelopment/20247ae59f7575bcf806660f36a2107d
- OBS.Identity (Custon IdentityServer 4, relevant information only): https://gist.github.com/OrionDevelopment/36f7a852269170ebb715d34ae34aa062
- Linux container config (docker compose, internal system only): https://gist.github.com/OrionDevelopment/070df639b18b2c9acc13d228ef509763 

**Screen recordings**
- Gif:
![grafana issue](https://user-images.githubusercontent.com/5585406/98090478-58d80300-1e84-11eb-8a00-277832707e32.gif)

**Access to test system is possible**
We were even able reproduce this on our public demonstration system which we use for client demonstrations, if needed a project member could contact me to see the problem in action on that demonstration system.

**Comment by aknuds1** [comment] 2020-11-04 14:56
Closing since I couldn't reproduce (on Windows) on the latest version, v7.3.1, using GitLab as a generic OAuth provider. Please try upgrading and if the issue still occurs, let us know.

**Closed by aknuds1** 2020-11-04 14:56 UTC
Labels: area/backend, area/backend/auth/oauth, needs investigation

**Comment by OrionDevelopment** [comment] 2020-11-05 12:07
@aknuds1 I am able to reproduce this on 7.3.1
I can get you access to the test system that we use to reproduce this problem.

**Comment by OrionDevelopment** [comment] 2020-11-05 12:17
Please reopen the issue, or at least validate that my custom.ini config file is correctly setup for OAuth usage.

**Comment by OrionDevelopment** [comment] 2020-11-05 12:38
Nevermind I am able to verify that the update solved the issue.
Just a caching issue.
