### ISSUE TITLE
Legend rows cannot be sorted following migration to Time Series from Graph (Old) Panels

### ISSUE THREAD

**Issue by n1nj4888** [grafana/grafana#35690] opened 2021-06-15 03:54 UTC
Running Grafana Docker 8.0.1.

Following migrating Graph (Old) panels to Time Series panels, the Panel Legend can no longer be sorted in ascending/decending numerical order simply by clicking on the required Legend Column.

Graph (Old) Legend - Clicking on any of the legend column headers sorts the rows numerically (and reverse numerically) according to the column.
![image](https://user-images.githubusercontent.com/29934446/121990222-fe1a6880-cdcf-11eb-9d14-8bc1d073a5a3.png)

Time Series Legend - Clicking on any of the legend column headers does not have any affect to the row ordering.
![image](https://user-images.githubusercontent.com/29934446/121990159-e642e480-cdcf-11eb-9b09-8fd1d1ccae2c.png)

**Comment by torkelo** [comment] 2021-06-15 07:33
duplicate of https://github.com/grafana/grafana/issues/35429

**Closed by torkelo** 2021-06-15 07:33 UTC
