### ISSUE TITLE
[Tempo plugin] Tags box is broken in the latest version of Chrome and Edge browser

### ISSUE THREAD

**Issue by faustodavid** [grafana/grafana#54643] opened 2022-09-02 13:19 UTC
**What happened**:
When trying to type a tag in the search tags box in the Tempo Datasource, it autocompletes whatever I try to write with a static value.

**What you expected to happen**:
When I start typing something in the search tags box, it should provide suggestions related to what I am typing but not override what I typed.

**How to reproduce it (as minimally and precisely as possible)**:
Open Grafana, go to explorer view, select a Tempo datasource, and try to type anything in the tags box.

![tempo-plugin-error](https://user-images.githubusercontent.com/2423149/188154146-1b0ff566-f247-4eee-844d-78e9f3953f22.gif)

**Anything else we need to know?**:
The issue only happens in the latest Microsoft Edge (version 105.0.1343.25) or Google Chrome (version 105.0.5195.52).

**Environment**:
- Grafana version: v9.1.2 and v9.0.5
- Data source type & version: Tempo
- OS Grafana is installed on:
- User OS & Browser: Microsoft Edge (version 105.0.1343.25) or Google Chrome (version 105.0.5195.52)
- Grafana plugins:
- Others:

**Comment by svennergr** [comment] 2022-09-02 14:09
Hi @faustodavid,
thanks for creating the issue. This is a duplicate of https://github.com/grafana/grafana/issues/54535, thus I am closing this issue here.

**Closed by svennergr** 2022-09-02 14:09 UTC
