### ISSUE TITLE
[Bug] Metric data not drawn on panel  

### ISSUE THREAD

**Issue by farzadpanahi** [grafana/grafana#4438] opened 2016-03-21 22:32 UTC
os: linux
datasource: kairosdb
grafana ver: 2.6.0
browser: chrome (Version 49.0.2623.87 (64-bit)) on mac (10.10.5 (14F1605))

when i leave grafana dashboard page in auto-refresh mode, after a while i notice that some of the graphs are empty. meaning that the legends and the axis are there, even the hover on works and displays data points but the metric is not drawn. basically no lines. empty graph. 
i checked the xhr queries and i can see that the data points are returned in response but for some reason they are not drawn. the in-app refresh does not fix it but the browser refresh fixes it. but after a while again some of the graphs are empty again.

looks like a client side issue. any idea?

**Comment by Jhors2** [comment] 2016-03-21 23:14
+1, I have the same issue

**Comment by utkarshcmu** [comment] 2016-03-22 01:24
Its happening in Chrome Version 49.0.2623.87 / Grafana 2.6.0.

**Comment by farzadpanahi** [comment] 2016-03-22 01:52
is this a known issue?

**Comment by utkarshcmu** [comment] 2016-03-22 04:56
No, this started happening on Chrome recently. Idk why. Whenever I switch my tab to any other page and come back to any Grafana dashboard after it has been refreshed at least once between this time of moving between tabs, this happens with me.

**Comment by bergquist** [comment] 2016-03-22 07:32
Do we have a rough estimate about how long it takes before going blank? I might be willing to add a full page reload to get rid of this behavior. I expect this to happen to a lot of people who are running Grafana on TV etc.

**Comment by torkelo** [comment] 2016-03-22 08:35
duplicate of https://github.com/grafana/grafana/issues/4378 

I looked at this 2 days ago, could replicate it on mac and Chrome 49, looks like a bug in Chrome that effects canvas, when you get back to the tab anything drawn on the canvas is not rendered to the page (the canvas is just blank)

**Closed by torkelo** 2016-03-22 08:35 UTC
