### ISSUE TITLE
[Feature request] Add alerts on a singlestat panel

### ISSUE THREAD

**Issue by JeromeVi** [grafana/grafana#7525] opened 2017-02-10 13:20 UTC
Please include this information:
- What Grafana version are you using? v4.1.1
- What datasource are you using? Prometheus
- What OS are you running grafana on? MacOS Sierra
- What did you do? Setting some alerts
- What was the expected result? Be able to set an alert on a singlestat panel
- What happened instead? no possibility to do it

### Request
Hi, today I was trying to add some alerts to test this feature and I wanted to put an alert on a singlestat panel who display the CPU usage in %, but there isn't the field to add the alert.

**So the request is adding the alert field on singlestat**

### Why 
For me it sounds natural to put an alert on a singlestat, for example in my case "if usage is bigger than 80% then alert me"

**Comment by bergquist** [comment] 2017-02-10 13:27
Dupe of https://github.com/grafana/grafana/issues/6983

**Closed by bergquist** 2017-02-10 13:27 UTC
