### ISSUE TITLE
MySQL Collation errors after upgrade (8.2.3 → 8.3.1) 

### ISSUE THREAD

**Issue by costela** [grafana/grafana#42874] opened 2021-12-08 10:44 UTC
**What happened**:

After an upgrade from 8.2.3 to 8.3.1 we receive the following errors:
![image](https://user-images.githubusercontent.com/94699/145180128-b52ce054-9e04-4277-8ea6-d6b8038a087a.png)

```
failure getting rule groups: Error 1267: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='
```

**What you expected to happen**:

No errors.

**How to reproduce it (as minimally and precisely as possible)**:

Install 8.2.3 with a mysql backend, upgrade to 8.3.1.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: AWS Aurora (MySQL 5.7) 2.04.5 
- OS Grafana is installed on: k8s
- User OS & Browser: linux/mac + chrome/firefox
- Grafana plugins:
- Others:

**Comment by ying-jeanne** [comment] 2021-12-28 09:55
it seems when we query the DB, we have always used collate utf8mb4_unicode_ci, it is a bit weird since I didn't see any collation utf8mb4_general_ci defined in the code base.

**Comment by ying-jeanne** [comment] 2021-12-28 10:59
Hey @costela, thanks you for reporting the issue. could you inspect the mysql DB to see what is the data types of table alert_rule? it would help us to reproduce the issue.

Thanks,

**Comment by FlorianLoch** [comment] 2022-01-04 11:01
Hello @ying-jeanne,
Let me provide you with these details on behalf of @costela.

`alert_rule` looks fine:
![image](https://user-images.githubusercontent.com/5587805/148048488-65b6598d-3edb-432e-a0f9-1f534b3c6058.png)

So I looked at other tables and `alert_notification` contains both collations:

![image](https://user-images.githubusercontent.com/5587805/148049042-5416b00c-763c-46dd-91a5-ed66bbb3302c.png)

`annotation`, `api_key`, `cache_data`, `dashboard`, `dashboard_acl`, `dashboard_provisioning` and probably others (that is just were I stopped investigating) contain columns set to `utf8mb4_general_ci`.

Hope this helps.

Would simply adjusting the collations fix our issue or would you advise against this?

**Comment by marefr** [comment] 2022-01-18 10:57
> Would simply adjusting the collations fix our issue or would you advise against this?

@FlorianLoch changing to `utf8mb4_general_ci` should do it. Seems like we have a glitch in the migrations when adding columns to a table there's no collation specified so it picks the default one. I'll try to open a fix for this.

**Comment by marefr** [comment] 2022-01-18 11:16
@FlorianLoch I've tested this and cannot reproduce the problem. Can you please provide your schema and server collation based on below examples for us to further be able to investigate this? Thanks 

Schema collation:
```
mysql> SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'grafana';
+----------------------------+------------------------+
| DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME |
+----------------------------+------------------------+
| utf8mb4                    | utf8mb4_unicode_ci     |
+----------------------------+------------------------+
1 row in set (0.00 sec)
```

Server collation:
```
mysql> SHOW VARIABLES LIKE 'collation%';
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | latin1_swedish_ci  |
| collation_database   | utf8mb4_unicode_ci |
| collation_server     | utf8mb4_unicode_ci |
+----------------------+--------------------+
3 rows in set (0.00 sec)
```

Collation of all tables:
```
mysql> SELECT CCSA.* FROM information_schema.`TABLES` T,        information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation   AND T.table_schema = "grafana";                                          
+--------------------+--------------------+
| COLLATION_NAME     | CHARACTER_SET_NAME |
+--------------------+--------------------+
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
| utf8mb4_unicode_ci | utf8mb4            |
+--------------------+--------------------+
52 rows in set (0.01 sec)
```

Collation of alert_notification columns:
```
mysql> SELECT column_name, character_set_name, collation_name FROM information_schema.`COLUMNS`  WHERE table_schema = "grafana"   AND table_name = "alert_notification";                                                                                       
+-------------------------+--------------------+--------------------+                                                                                                                                                                                          
| column_name             | character_set_name | collation_name     |                                                                                                                                                                                          
+-------------------------+--------------------+--------------------+                                                                                                                                                                                          
| id                      | NULL               | NULL               |                                                                                                                                                                                          
| org_id                  | NULL               | NULL               |                                                                                                                                                                                          
| name                    | utf8mb4            | utf8mb4_unicode_ci |                                                                                                                                                                                          
| type                    | utf8mb4            | utf8mb4_unicode_ci |                                                                                                                                                                                          
| settings                | utf8mb4            | utf8mb4_unicode_ci |                                                                                                                                                                                          
| created                 | NULL               | NULL               |                                                                                                                                                                                          
| updated                 | NULL               | NULL               |                                                                                                                                                                                          
| is_default              | NULL               | NULL               |                                                                                                                                                                                          
| frequency               | NULL               | NULL               |                                                          
| send_reminder           | NULL               | NULL               |                                                          
| disable_resolve_message | NULL               | NULL               |                                                          
| uid                     | utf8mb4            | utf8mb4_unicode_ci |                                                          
| secure_settings         | utf8mb4            | utf8mb4_unicode_ci |                                                          
+-------------------------+--------------------+--------------------+                                                          
13 rows in set (0.00 sec)                                      
```

**Comment by FlorianLoch** [comment] 2022-01-19 09:57
@marefr I am happy to provide this information to you, hoping it helps to find the underlying issue.

We have two setups, one for testing and one for production. As the following is the same for both of them I am quite sure nobody tampered with the DB causing the current state.

```
mysql> SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'grafana_prod';
+----------------------------+------------------------+
| DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME |
+----------------------------+------------------------+
| utf8                       | utf8_general_ci        |
+----------------------------+------------------------+
```

```
mysql> SHOW VARIABLES LIKE 'collation%';
+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_general_ci |
| collation_database   | latin1_swedish_ci  |
| collation_server     | latin1_swedish_ci  |
+----------------------+--------------------+
```

```
mysql> SELECT CCSA.*,T.table_name FROM information_schema.`TABLES` T,        information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation   AND T.table_schema = "grafana_prod";
+--------------------+--------------------+----------------------------+
| COLLATION_NAME     | CHARACTER_SET_NAME | table_name                 |
+--------------------+--------------------+----------------------------+
| utf8_general_ci    | utf8               | migration_log              |
| utf8_general_ci    | utf8               | session                    |
| utf8_general_ci    | utf8               | star                       |
| utf8mb4_unicode_ci | utf8mb4            | alert                      |
| utf8mb4_unicode_ci | utf8mb4            | alert_configuration        |
| utf8mb4_unicode_ci | utf8mb4            | alert_instance             |
| utf8mb4_unicode_ci | utf8mb4            | alert_notification         |
| utf8mb4_unicode_ci | utf8mb4            | alert_notification_state   |
| utf8mb4_unicode_ci | utf8mb4            | alert_rule                 |
| utf8mb4_unicode_ci | utf8mb4            | alert_rule_tag             |
| utf8mb4_unicode_ci | utf8mb4            | alert_rule_version         |
| utf8mb4_unicode_ci | utf8mb4            | annotation                 |
| utf8mb4_unicode_ci | utf8mb4            | annotation_tag             |
| utf8mb4_unicode_ci | utf8mb4            | api_key                    |
| utf8mb4_unicode_ci | utf8mb4            | builtin_role               |
| utf8mb4_unicode_ci | utf8mb4            | cache_data                 |
| utf8mb4_unicode_ci | utf8mb4            | dashboard                  |
| utf8mb4_unicode_ci | utf8mb4            | dashboard_acl              |
| utf8mb4_unicode_ci | utf8mb4            | dashboard_provisioning     |
| utf8mb4_unicode_ci | utf8mb4            | dashboard_snapshot         |
| utf8mb4_unicode_ci | utf8mb4            | dashboard_tag              |
| utf8mb4_unicode_ci | utf8mb4            | dashboard_version          |
| utf8mb4_unicode_ci | utf8mb4            | data_keys                  |
| utf8mb4_unicode_ci | utf8mb4            | data_source                |
| utf8mb4_unicode_ci | utf8mb4            | kv_store                   |
| utf8mb4_unicode_ci | utf8mb4            | library_element            |
| utf8mb4_unicode_ci | utf8mb4            | library_element_connection |
| utf8mb4_unicode_ci | utf8mb4            | login_attempt              |
| utf8mb4_unicode_ci | utf8mb4            | ngalert_configuration      |
| utf8mb4_unicode_ci | utf8mb4            | org                        |
| utf8mb4_unicode_ci | utf8mb4            | org_user                   |
| utf8mb4_unicode_ci | utf8mb4            | permission                 |
| utf8mb4_unicode_ci | utf8mb4            | playlist                   |
| utf8mb4_unicode_ci | utf8mb4            | playlist_item              |
| utf8mb4_unicode_ci | utf8mb4            | plugin_setting             |
| utf8mb4_unicode_ci | utf8mb4            | preferences                |
| utf8mb4_unicode_ci | utf8mb4            | quota                      |
| utf8mb4_unicode_ci | utf8mb4            | role                       |
| utf8mb4_unicode_ci | utf8mb4            | seed_assignment            |
| utf8mb4_unicode_ci | utf8mb4            | server_lock                |
| utf8mb4_unicode_ci | utf8mb4            | short_url                  |
| utf8mb4_unicode_ci | utf8mb4            | tag                        |
| utf8mb4_unicode_ci | utf8mb4            | team                       |
| utf8mb4_unicode_ci | utf8mb4            | team_member                |
| utf8mb4_unicode_ci | utf8mb4            | team_role                  |
| utf8mb4_unicode_ci | utf8mb4            | temp_user                  |
| utf8mb4_unicode_ci | utf8mb4            | test_data                  |
| utf8mb4_unicode_ci | utf8mb4            | user                       |
| utf8mb4_unicode_ci | utf8mb4            | user_auth                  |
| utf8mb4_unicode_ci | utf8mb4            | user_auth_token            |
| utf8mb4_unicode_ci | utf8mb4            | user_role                  |
+--------------------+--------------------+----------------------------+
51 rows in set (0.02 sec)
```

```
mysql> SELECT column_name, character_set_name, collation_name FROM information_schema.`COLUMNS`  WHERE table_schema = "grafana_prod"   AND table_name = "alert_notification";
+-------------------------+--------------------+--------------------+
| column_name             | character_set_name | collation_name     |
+-------------------------+--------------------+--------------------+
| id                      | NULL               | NULL               |
| org_id                  | NULL               | NULL               |
| name                    | utf8mb4            | utf8mb4_general_ci |
| type                    | utf8mb4            | utf8mb4_general_ci |
| settings                | utf8mb4            | utf8mb4_general_ci |
| created                 | NULL               | NULL               |
| updated                 | NULL               | NULL               |
| is_default              | NULL               | NULL               |
| frequency               | NULL               | NULL               |
| send_reminder           | NULL               | NULL               |
| disable_resolve_message | NULL               | NULL               |
| uid                     | utf8mb4            | utf8mb4_unicode_ci |
| secure_settings         | utf8mb4            | utf8mb4_unicode_ci |
+-------------------------+--------------------+--------------------+
```

So our MySQL instances' defaults differ - but AFAIU that should not really be an issue as long as Grafana sets the collation and charset explicitly for its tables? 
You stated that there is no explicit collation defined in the migration scripts - that would (at least) explain the default collation showing up with the three tables `migration_log`, `session` and `star`.
But I am not sure it explains why there are multiple collations in some tables (e.g. in `alert_notifications`), as the second collation in there is not equal to the default collation. It is the same as the default `connection_collation` with our setup, but not with yours. 🤔

**Comment by FlorianLoch** [comment] 2022-01-19 10:43
For the sake of completeness and in case anyone runs into the same issue: I used the following SQL queries to have our DB setup match yours by adjusting charsets and collations.

After applying these we have been able to upgrade to `8.3.4` without any further issues. 🎉 

```sql
-- Fix/set default charset and collation for schema
ALTER DATABASE grafana_prod CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Generate queries to alter the tables, these will then also adjust the columns contained in them
SELECT CONCAT('ALTER TABLE ', tbl.TABLE_SCHEMA, '.', tbl.TABLE_NAME, ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;') FROM information_schema.TABLES tbl WHERE tbl.TABLE_SCHEMA = 'grafana_prod';

-- Generated queries; run these to actually update the tables and columns
ALTER TABLE grafana_prod.alert CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.alert_configuration CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.alert_instance CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.alert_notification CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.alert_notification_state CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.alert_rule CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.alert_rule_tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.alert_rule_version CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.annotation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.annotation_tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.api_key CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.builtin_role CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.cache_data CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.dashboard CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.dashboard_acl CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.dashboard_provisioning CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.dashboard_snapshot CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.dashboard_tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.dashboard_version CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.data_keys CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.data_source CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.kv_store CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.library_element CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.library_element_connection CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.login_attempt CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.migration_log CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.ngalert_configuration CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.org CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.org_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.permission CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.playlist CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.playlist_item CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.plugin_setting CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.preferences CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.quota CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.role CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.seed_assignment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.server_lock CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.session CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.short_url CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.star CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.tag CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.team CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.team_member CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.team_role CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.temp_user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.test_data CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.user_auth CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.user_auth_token CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE grafana_prod.user_role CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by marefr** [comment] 2022-01-19 20:04
@FlorianLoch thanks a lot for that extensive update. I don't understand why this has happened. Maybe something related to you're using AWS Aurora, but not sure. 

I'm going to close this now since we cannot reproduce it and you've provided a workaround, but if more reports/activity regarding this comes up we'll consider reopening this one.

**Closed by marefr** 2022-01-19 20:04 UTC
Labels: needs more info, area/backend/db/mysql, area/backend/db/migration
