### ISSUE TITLE
Incorrect alias names when hiding series

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#2697] opened 2015-09-08 12:49 UTC
Grafana 2.1.3 with InfluxDB 0.9.3:
1. Create graph with two series
2. Give both an alias which displays in the legend (e.g. "foo" and "bar")
3. Click the eye icon of the first series to hide
4. Only second series is shown in graph *but* the legend shows "foo" instead of "bar".
Not only is the name in the legend wrong, but this also stops series specific overrides from working (e.g. if second series should show on Y-axis 2, it will show on Y-axis 1 when he first series is hidden)

**Comment by torkelo** [comment] 2015-09-08 13:12
Good news for you :) 

fixed in https://github.com/grafana/grafana/commit/745a7b44617014cc4c7c6aa50e54e46a413ebe33 
dupe of https://github.com/grafana/grafana/issues/2651

**Closed by torkelo** 2015-09-08 13:12 UTC

**Comment by jessetan** [comment] 2015-09-09 10:11
👍
