### ISSUE TITLE
[Feat] Disable save dashboard modal if history disabled

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [grafana/grafana#9604] opened 2017-10-20 14:13 UTC
After update to latest version started to popup annoying messages after every even small change in dashboard. And not exist option to disable this annoying "feature".

**Comment by jpVm5jYYRE1VIKL** [comment] 2017-10-23 10:33
Why you think that this is feature request. It is real bug.

**Comment by torkelo** [comment] 2017-10-23 13:47
dupe of https://github.com/grafana/grafana/issues/8887

**Comment by andig** [comment] 2018-08-04 08:03
This is not a dupe. This issue is about the annoying popup (same issue here), the other one is about number of history entries. I‘d appreciate being able to disable the history comments popup.

**Comment by marefr** [comment] 2018-08-06 08:50
Recently we did a couple of changes to the save dashboard modal so you'll get checkboxes if you want to save changed time range and/or variables. 

So I guess we'll need to introduce a setting to disable dashboard history. If not dashboard history is enabled and not time range or variables have been changed then the modal can be disabled.

**Comment by hugohaggmark** [comment] 2020-11-11 05:53
Closing this as I can't repro this on Grafana v7.4.0-pre (db637a3630) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2020-11-11 05:53 UTC
Labels: area/dashboard/history, type/feature-request
