### ISSUE TITLE
$__range not supported with Loki + label_values()

### ISSUE THREAD

**Issue by loganmc10** [grafana/grafana#37804] opened 2021-08-11 16:12 UTC
**What happened**:
I am trying to create a dashboard variable like this:
```
label_values(topk(20,sum by (SrcAddr,DstAddr,SamplerAddress, DstPort, Proto) (sum_over_time({job="netflow"} | json | unwrap Bytes[$__range]))), SrcAddr) 
```
In order to get the top 20 SrcAddr label values, This query works in the Explore interface.

Grafana says:
> parse error at line 0, col 117: not a valid duration string: "$__range"

**What you expected to happen**:
I thought the $__range variable was supported with Loki starting in 8.1, but it doesn't seem to work here. https://github.com/grafana/grafana/pull/36175

**How to reproduce it (as minimally and precisely as possible)**:
I suspect any Loki query using $__range will fail when making a dashboard variable

**Anything else we need to know?**:
I am using Grafana Cloud, just got updated to 8.1.1

Other examples use query_result and then a regex selector to grab the label values, but Loki doesn't seem to support query_result()

**Environment**:
- Grafana version: Cloud, 8.1.1
- Data source type & version: Loki (Grafana Cloud)
- OS Grafana is installed on: Cloud
- User OS & Browser: Windows 10 and Chrome
- Grafana plugins: N/A
- Others:

**Comment by loganmc10** [comment] 2021-08-11 16:24
I guess even when I change the range to a value like 1h I get this:
> only label matchers is supported

So it doesn't seem to work anyway. I am trying to do this: https://www.robustperception.io/graph-top-n-time-series-in-grafana using Loki. This example uses the query_result() function, but that isn't available with Loki. I opened a feature request for supporting query_result() with Loki here: https://github.com/grafana/grafana/discussions/37805. I guess this can be closed if someone at Grafana feels that this sort of thing shouldn't be supported using label_values()

**Comment by ivanahuckova** [comment] 2021-08-12 07:25
@loganmc10 thanks for creating feature request #37805! 🚀 I'll close this issue as the problem is not `$__range` variable.

**Closed by ivanahuckova** 2021-08-12 07:25 UTC
Labels: datasource/Loki
