### ISSUE TITLE
Explore: Log panel forgets column settings between query runs

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#15605] opened 2019-02-22 11:51 UTC
0. Loki in Explore
1. Select a label and run query that has non-common labels in the result (label column is shown with labels)
2. Toggle off the label column (label column is gone)
3. Run query again

Result: Label column shows up again

Expected: disabled columns should stay hidden between run (same for time columns)

**Comment by steven-sheehy** [comment] 2019-03-16 06:22
This is extremely annoying. I had a crack at it but couldn't figure it out. My best guess was some capability issue between the angular and react components. Any ideas on where to look @davkal ?

**Comment by davkal** [comment] 2019-03-25 14:26
I was wondering if #16043 could address this as well, but I did not want to broaden the scope of that PR.

**Comment by steven-sheehy** [comment] 2019-03-30 01:36
I've confirmed that the Logs component is getting unmounted frequently when it shouldn't, causing it to discard its state. But I can't figure out why.

**Comment by davkal** [comment] 2019-04-04 13:41
I can still repro this. To get non-common labels I append the same unique string to two tailed logs and then query with `{job="varlogs"} ragnarok`. On the first run, no labels are shown, then I switch labels on and see the labels, then I run the query again and when the results come back, the labels are no longer shown.

**Comment by steven-sheehy** [comment] 2019-05-10 15:33
This might be fixed now on master. Possibly by accident via #16955.

@davkal @marefr Can someone confirm?

**Comment by marefr** [comment] 2019-05-10 16:16
@steven-sheehy changes in that PR shouldn't have done anything related to Loki since it's angular query editor related and Loki query editor is React.

**Comment by steven-sheehy** [comment] 2019-05-10 16:18
It might not be that PR. 😄  But point is it might be fixed if someone can test. I tested it and it looks fixed.

**Comment by marefr** [comment] 2019-05-10 16:32
Nice :smile: Will give it a try beginning next week.

**Comment by marefr** [comment] 2019-05-20 15:19
Seems to be fixed so closing this. Thanks @steven-sheehy for the heads up.

**Closed by marefr** 2019-05-20 15:19 UTC
Labels: area/explore
