### ISSUE TITLE
non-deterministic column order since grafana 6.4.x

### ISSUE THREAD

**Issue by Stono** [grafana/grafana#19647] opened 2019-10-06 14:21 UTC
**What happened**:
Many people are crying out for column ordering (see https://github.com/grafana/grafana/issues/5082), however in 6.4.x it's actually worse.  Not only can we not reorder columns, between dashboard refreshes, they change!  Here is the same panel between three clicks of the refresh.

<img width="824" alt="Screenshot 2019-10-06 at 15 19 31" src="https://user-images.githubusercontent.com/1486729/66270543-ec3ba080-e84c-11e9-9996-941afa141f2b.png">
<img width="836" alt="Screenshot 2019-10-06 at 15 19 36" src="https://user-images.githubusercontent.com/1486729/66270544-ec3ba080-e84c-11e9-9a3c-604f2b90297e.png">
<img width="812" alt="Screenshot 2019-10-06 at 15 19 43" src="https://user-images.githubusercontent.com/1486729/66270545-ec3ba080-e84c-11e9-9823-f06c7f4d97e1.png">

**What you expected to happen**:
I mean ideally, controlled ordering, but at least the 6.3.x behaviour which was consistently uncontrollable (seemingly alphabetical)

**How to reproduce it (as minimally and precisely as possible)**:
Use 6.4.x and refresh

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-10-07 08:14
Are you using prometheus? If so it's a dupe of https://github.com/grafana/grafana/issues/19529 

fixed in master and soon to be released 6.4.2

**Closed by torkelo** 2019-10-07 08:14 UTC

**Comment by Stono** [comment] 2019-10-07 12:48
Indeed I am, and thank you for linking the issues
