### ISSUE TITLE
Row breaks when adding new panel

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#16292] opened 2019-03-29 10:33 UTC
**What happened**:
I have dashboard with one row. When I add new panel, some widgets falls out from the raw. 
As you can see, Uptime and CPU singlestat widgets (in right-top corner) falls out:
![report](https://user-images.githubusercontent.com/1700286/55226581-5df3bb80-5226-11e9-81c2-bb5bea46f91c.gif)

**How to reproduce it (as minimally and precisely as possible)**:
Create new row and fill it with some widgets **for all width.**
Minimize the row.
Press "Add panel"

**Environment**:
- Grafana version: Grafana v6.0.2 (commit: 3f4c2e7)
- Data source type & version: Zabbix Source
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome latest
- Grafana plugins: Zabbix Source plugin

**Comment by torkelo** [comment] 2019-03-29 11:04
duplicate of https://github.com/grafana/grafana/issues/15224

**Closed by torkelo** 2019-03-29 11:04 UTC
