### ISSUE TITLE
Support for multiple datasources in a single chart

### ISSUE THREAD

**Issue by amuraru** [grafana/grafana#1326] opened 2015-01-10 22:54 UTC
Right now only one datasource can be used in a chart - it would be useful to have the datasource selectable for each metric so multiple metrics from multiple datasources can be mixed in a chart

**Comment by torkelo** [comment] 2015-01-11 10:02
This would be nice, just a little tricky to implement without changing to much and adding too much complexity.

Dupe of #436

**Closed by torkelo** 2015-01-11 10:02 UTC
