### ISSUE TITLE
[UX/UI] Global defaults for graph look & feel

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#11872] opened 2018-05-08 08:03 UTC
@davkal as per our chat at KubeCon.

Related to https://github.com/grafana/grafana/issues/11871
Being able to define global defaults / overrides would be useful. Let's say I always need my left axis to have line fill 2 and line width 4, it would be nice to be able to set this from a central place.

This would have obvious implications on "Export as JSON" etc as users may want to export those defaults along with the actual dashboard/graph.

**Comment by bergquist** [comment] 2018-05-08 08:17
Dupe of https://github.com/grafana/grafana/issues/11864 unless you think I missed something?

**Closed by bergquist** 2018-05-08 08:17 UTC
