### ISSUE TITLE
Nested jsonData cause datasource provisioning error

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#11841] opened 2018-05-07 03:59 UTC
### What Grafana version are you using?
5.1.0
### What datasource are you using?
camptocamp-prometheus-alertmanager-datasource
### What OS are you running grafana on?
MacOS
### What did you do?
Add datasource provisioning setting file for camptocamp-prometheus-alertmanager-datasource.

```
  jsonData:
    severity:
      info: info
      warning: warning
      critical: critical
      high: high
```

https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource
### What was the expected result?
Grafana provision datasource.
### What happened instead?
Cause error, Grafana suddenly exit.
```
t=2018-05-07T12:50:26+0900 lvl=eror msg="Startup failed" error="Failed to provision Grafana from config. error: json: unsupported type: map[interface {}]interface {}"
```

**Comment by torkelo** [comment] 2018-05-07 06:10
duplicate of https://github.com/grafana/grafana/issues/11537

**Closed by torkelo** 2018-05-07 06:10 UTC
