### ISSUE TITLE
alert provisioning api: alert-rules/export api returns ambiguous message about missing traceID when there are no alerts

### ISSUE THREAD

**Issue by SkouRene** [grafana/grafana#68761] opened 2023-05-22 08:14 UTC
### 
# What went wrong?

**What happened**:
- using grafana 9.5.1 oss

  - when calling api  endpoint "api/v1/provisioning/alert-rules/export?download=true&format=yaml" i get error message: "failed to get alert rules: command missing required fields" traceID empty

**What did you expect to happen**:

  - Last i call this endpoint I got the file with all the alerts in yaml format.

### 
# How do we reproduce it?

**Step 1**:

- Open postman

**Step 2**:

- call endpoint "api/v1/provisioning/alert-rules/export?download=true&format=yaml" with your admin user in basic auth

**Step 3**:

- Wait for the error message

### 
# What Grafana version are you using?

v9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Ubuntu 22.04

### Is this a Regression?

None

**Comment by mellieA** [comment] 2023-05-23 23:34
@SkouRene I tested this using postman and was able to download the file: 

<img width="910" alt="Screenshot 2023-05-23 at 5 32 08 PM" src="https://github.com/grafana/grafana/assets/18175287/11c690a3-76ac-4ff0-9d9a-1ff636015273">

**Comment by mellieA** [comment] 2023-05-23 23:40
I reproduced the error once in the beginning of testing on a fresh instance when there were no rules present. I just deleted the rule and it reproduced the problem in postman as well.  

curl admin:admin@localhost:3000/api/v1/provisioning/alert-rules/export

{"message":"failed to get alert rules: command missing required fields","traceID":""}%

**Comment by JohnnyQQQQ** [comment] 2023-05-23 23:57
Duplicate of #68929

**Closed by JohnnyQQQQ** 2023-05-23 23:57 UTC
Labels: area/alerting, area/backend/api, area/provisioning

**Comment by SkouRene** [comment] 2023-06-14 11:01
Thank for answer
