### ISSUE TITLE
Alert is not rendered according to the scale of the axis of the query

### ISSUE THREAD

**Issue by trensetim** [grafana/grafana#35021] opened 2021-06-01 08:05 UTC
**What happened**:
While using a graph chart with prometheus data, I noticed that when assigning one query to the right axis and creating an alert rule for that query, the alert-indicator-line does not adhere to the right axis scale but instead to the left axis scale.

**What you expected to happen**:
Alert indicators for queries which are assigned to the right axis, should be rendered according to the right axis scale.

**How to reproduce it (as minimally and precisely as possible)**:
1 Create a query for a prometheus metric upon postgres_exporter for rate(pg_stat_database_tup_fetched{datname="My Database"}[30s])    Not sure if that works regardless of the queries metric...?
2 Assign the query to the right axis
3 Scale right axis different from left axis
4 Create an alert upon the query

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana/grafana:7.3.6
- Data source type & version: prom/prometheus:latest
- OS Grafana is installed on: docker @ WSL2
- User OS & Browser: Windows 10 Pro & Mozilla Firefox Stable 88.0.1 64bit
- Grafana plugins: none
- Others:

**Comment by trensetim** [comment] 2021-06-01 08:05
![grafik](https://user-images.githubusercontent.com/74014803/120288835-f1225300-c2c0-11eb-9b70-0ecd41b65b52.png)

**Comment by trensetim** [comment] 2021-06-01 08:07
On the screenshot you can see, my alert is set to "above 3" but the right axis (which query A "Fetch" is assigned to) scales from 0 to 500k so the red alert indicating threshold line should be effectively at the bottom of the graph (such that the entire graph would be colored red)

**Comment by torkelo** [comment] 2021-06-01 08:20
duplicate of #12705

**Comment by trensetim** [comment] 2021-06-01 09:15
Agreed. It is a duplicate. Nonetheless what are your plans to tackle this? The other ticket shows rather sparse responses...

**Closed** 2021-06-01 14:14 UTC

**Comment by torkelo** [comment] 2021-06-01 14:16
no plans, the new alerting system in v8 will have a separate alert rule UI (ie not in dashboard panel graph). 

And the new time series panel (new default Graph) does support thresholds to be linked to a specific axis using the field override system
