### ISSUE TITLE
Missing Gopkg.toml on Docker build

### ISSUE THREAD

**Issue by rshejnberg** [grafana/grafana#16814] opened 2019-04-29 20:50 UTC
**What happened**:

I'm trying to bring upstream changes into a forked instance of Grafana to bring it up to v6 and am encountering issues when running docker build. Because the file Gopkg.toml has been removed I receive:
```
Building grafana
Step 1/43 : FROM golang:1.12.4
 ---> b860ab44e93e
Step 2/43 : WORKDIR $GOPATH/src/github.com/grafana/grafana
 ---> Using cache
 ---> 4bf89ce2a4f9
Step 3/43 : COPY Gopkg.toml Gopkg.lock ./
ERROR: Service 'grafana' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder170327836/Gopkg.toml: no such file or directory
```

**What you expected to happen**:

I expected ``docker build`` to execute without issue

**How to reproduce it (as minimally and precisely as possible)**:

Run ``docker build`` when there is no Gopkg.toml in your root project directory.

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: N/A
- OS Grafana is installed on: Mac
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A/

**Other info**

Looks like the files referenced in the line raising the error were removed in [this](https://github.com/grafana/grafana/commit/b9e148f3abdb7b44db2533c9b072d517a37db821) commit. Shouldn't another change be made removing this step from the dockerfile?

**Comment by steven-sheehy** [comment] 2019-04-29 21:51
Duplicate of https://github.com/grafana/grafana/issues/16789

**Comment by bergquist** [comment] 2019-04-30 05:49
Closing since its a dupe

**Closed by bergquist** 2019-04-30 05:49 UTC
