### ISSUE TITLE
Table - Max: calculate based on all values - not works

### ISSUE THREAD

**Issue by baur** [grafana/grafana#32092] opened 2021-03-18 10:10 UTC
**What happened**:

Max: calculate based on all values is not works if more than 3 columns

3 column

![image](https://user-images.githubusercontent.com/2898361/111609888-f402c100-8804-11eb-9d3b-8ff73971fa69.png)

4 column

![image](https://user-images.githubusercontent.com/2898361/111609994-11378f80-8805-11eb-82a8-bb0064644a72.png)

**How to reproduce it (as minimally and precisely as possible)**:
Any query with more than 3 columns (RDBMS)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5 beta1
- Data source type & version: PostgreSQL v 12
- OS Grafana is installed on: Windows Server
- User OS & Browser: Chrome
- Grafana plugins: none
- Others: -

**Comment by torkelo** [comment] 2021-03-18 11:35
duplicate of https://github.com/grafana/grafana/issues/26383

**Closed by torkelo** 2021-03-18 11:35 UTC
