### ISSUE TITLE
Bug - Graph Panel - ElasticSeach - in v6.0.0-pre1 (3ad48ff)

### ISSUE THREAD

**Issue by ldktta** [grafana/grafana#15175] opened 2019-01-31 19:20 UTC
Please include this information:
### What Grafana version are you using?
Grafana v6.0.0-pre1 (3ad48ff)
### What datasource are you using?
ElastiSeach 6.0+
### What OS are you running grafana on?
Linux RedHat 7
### What did you do?
Update Grafana v5.5.0-pre1 (d907b1e) to Grafana v6.0.0-pre1 (3ad48ff)
### What happened instead?
Error in Graph Panel

![image](https://user-images.githubusercontent.com/14881332/52078984-5770fc80-2573-11e9-9af2-b5deb5d23fc0.png)

![image](https://user-images.githubusercontent.com/14881332/52079002-635cbe80-2573-11e9-83a6-a883d7318aac.png)

**Comment by dprokop** [comment] 2019-01-31 19:33
Thanks for reporting this issue. Can you provide me with panel's JSON?

Might be related to https://github.com/grafana/grafana/issues/15156 fixed in https://github.com/grafana/grafana/pull/15160

**Comment by ldktta** [comment] 2019-01-31 19:41
{
  "aliasColors": {
    "IN  /Common/Pool_CALDEN": "#E0F9D7",
    "IN  /Common/Pool_CALDEN_EXT": "#890F02",
    "IN  /Common/Pool_ClickSchedule": "#6D1F62",
    "IN  /Common/Pool_OPENREPORTS": "#E0F9D7",
    "IN  /Common/Pool_Pac": "#DEDAF7",
    "IN  /Common/Pool_Sinapse": "#7EB26D",
    "IN  /Common/Pool_TarifaSocial_Prod": "#705DA0",
    "IN  /Common/Pool_VGAS_PROD": "#EAB839",
    "IN  /Common/Pool_ws-xlocate": "#967302",
    "IN /Common/Pool_Sinapse": "#7EB26D",
    "IN /Common/Pool_TarifaSocial_Prod": "#7EB26D",
    "In-TOTAL": "#BF1B00",
    "OUT /Common/Pool_CALDEN": "#E0F9D7",
    "OUT /Common/Pool_CALDEN_EXT": "#890F02",
    "OUT /Common/Pool_CLICKMOBILE_PROD": "#C15C17",
    "OUT /Common/Pool_ClickSchedule": "#6D1F62",
    "OUT /Common/Pool_GIS_MOBILE": "#0A437C",
    "OUT /Common/Pool_IDM": "#6ED0E0",
    "OUT /Common/Pool_METROGAS": "#E5AC0E",
    "OUT /Common/Pool_Pac": "#F2C96D",
    "OUT /Common/Pool_ScadaWeb": "#E5A8E2",
    "OUT /Common/Pool_Sinapse": "#7EB26D",
    "OUT /Common/Pool_TarifaSocial_Prod": "#705DA0",
    "OUT /Common/Pool_VGAS_PROD": "#EAB839",
    "OUT /Common/Pool_ws-xlocate": "#967302",
    "Out-/Common/Pool_Sinapse": "#7EB26D",
    "Out-TOTAL": "#DEDAF7",
    "TOTAL-in": "#E24D42",
    "TOTAL-out": "#DEDAF7",
    "▲ OUT /Common/Pool_BUHO": "#99440A",
    "▲ OUT /Common/Pool_CALDEN": "#5195CE",
    "▲ OUT /Common/Pool_CALDEN_EXT": "#890F02",
    "▲ OUT /Common/Pool_DOCUWARE_C": "#F29191",
    "▲ OUT /Common/Pool_GIS_MOBILE": "#052B51",
    "▲ OUT /Common/Pool_IDM": "#6ED0E0",
    "▲ OUT /Common/Pool_METROGAS": "#3F6833",
    "▲ OUT /Common/Pool_OPENREPORTS": "#2F575E",
    "▲ OUT /Common/Pool_OpenReports": "#EF843C",
    "▲ OUT /Common/Pool_Pac": "#F9E2D2",
    "▲ OUT /Common/Pool_PulseNet": "#3F6833",
    "▲ OUT /Common/Pool_ScadaWeb": "#F2C96D",
    "▲ OUT /Common/Pool_Sinapse": "#7EB26D",
    "▲ OUT /Common/Pool_TarifaSocial_Prod": "#705DA0",
    "▲ OUT /Common/Pool_Turnos_Prod": "#E5A8E2",
    "▲ OUT /Common/Pool_VGAS_PROD": "#EAB839",
    "▼ IN /Common/Pool_BUHO": "#99440A",
    "▼ IN /Common/Pool_CALDEN": "#82B5D8",
    "▼ IN /Common/Pool_CALDEN_EXT": "#890F02",
    "▼ IN /Common/Pool_DOCUWARE_C": "#F29191",
    "▼ IN /Common/Pool_IDM": "#967302",
    "▼ IN /Common/Pool_OPENREPORTS": "#2F575E",
    "▼ IN /Common/Pool_OpenReports": "#EF843C",
    "▼ IN /Common/Pool_Pac": "#FCEACA",
    "▼ IN /Common/Pool_PulseNet": "#3F6833",
    "▼ IN /Common/Pool_Sinapse": "#7EB26D",
    "▼ IN /Common/Pool_TarifaSocial_Prod": "#705DA0"
  },
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "ElasticSearchF5",
  "decimals": 1,
  "description": "",
  "editable": true,
  "error": false,
  "fill": 1,
  "gridPos": {
    "h": 10,
    "w": 24,
    "x": 0,
    "y": 1
  },
  "hideTimeOverride": false,
  "id": 1,
  "interval": "$Interval",
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": false,
    "hideEmpty": true,
    "hideZero": true,
    "max": true,
    "min": false,
    "rightSide": true,
    "show": true,
    "sideWidth": 500,
    "sort": "avg",
    "sortDesc": true,
    "total": true,
    "values": true
  },
  "lines": true,
  "linewidth": 2,
  "links": [],
  "nullPointMode": "connected",
  "paceLength": 10,
  "percentage": false,
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "repeat": null,
  "seriesOverrides": [
    {
      "alias": "▲ OUT TOTAL",
      "color": "#E0F9D7",
      "dashLength": 3,
      "dashes": true,
      "fill": 2,
      "spaceLength": 3,
      "zindex": -3
    },
    {
      "alias": "▼ IN TOTAL",
      "color": "#BF1B00",
      "dashLength": 3,
      "dashes": true,
      "fill": 2,
      "spaceLength": 3,
      "transform": "negative-Y",
      "zindex": -3
    },
    {
      "alias": "/.*OUT \\/Common/",
      "bars": true,
      "lines": false,
      "stack": "B"
    },
    {
      "alias": "/.*IN \\/Common.*/",
      "bars": true,
      "lines": false,
      "stack": "A",
      "transform": "negative-Y"
    }
  ],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "alias": "▲ OUT TOTAL",
      "bucketAggs": [
        {
          "fake": true,
          "field": "@timestamp",
          "id": "3",
          "settings": {
            "interval": "auto",
            "min_doc_count": 0,
            "trimEdges": 0
          },
          "type": "date_histogram"
        }
      ],
      "dsType": "elasticsearch",
      "metrics": [
        {
          "field": "bytes_out",
          "id": "1",
          "meta": {},
          "settings": {},
          "type": "sum"
        }
      ],
      "query": "Pool.keyword:/Common/$Pool AND http_status.keyword:$StatusCode  AND node.keyword:$Node AND node_port.keyword:$Port AND subnet.keyword:$SubNet AND server.keyword:$Server AND src_ip:$Src_ip AND http_metod.keyword:$Metod",
      "refId": "A",
      "timeField": "@timestamp"
    },
    {
      "alias": "▼ IN TOTAL",
      "bucketAggs": [
        {
          "fake": true,
          "field": "@timestamp",
          "id": "3",
          "settings": {
            "interval": "auto",
            "min_doc_count": 0,
            "trimEdges": 0
          },
          "type": "date_histogram"
        }
      ],
      "dsType": "elasticsearch",
      "metrics": [
        {
          "field": "bytes_in",
          "id": "1",
          "meta": {},
          "settings": {},
          "type": "sum"
        }
      ],
      "query": "Pool.keyword:/Common/$Pool AND http_status.keyword:$StatusCode  AND node.keyword:$Node AND node_port.keyword:$Port AND subnet.keyword:$SubNet AND server.keyword:$Server AND src_ip:$Src_ip AND http_metod.keyword:$Metod",
      "refId": "D",
      "timeField": "@timestamp"
    },
    {
      "alias": "▼ IN {{term Pool.keyword}}",
      "bucketAggs": [
        {
          "fake": true,
          "field": "Pool.keyword",
          "id": "3",
          "settings": {
            "min_doc_count": 1,
            "order": "asc",
            "orderBy": "_term",
            "size": "0"
          },
          "type": "terms"
        },
        {
          "field": "@timestamp",
          "id": "2",
          "settings": {
            "interval": "auto",
            "min_doc_count": 0,
            "trimEdges": 0
          },
          "type": "date_histogram"
        }
      ],
      "dsType": "elasticsearch",
      "metrics": [
        {
          "field": "bytes_in",
          "id": "1",
          "meta": {},
          "settings": {},
          "type": "sum"
        }
      ],
      "query": "Pool.keyword:/Common/$Pool AND http_status.keyword:$StatusCode  AND node.keyword:$Node AND node_port.keyword:$Port AND subnet.keyword:$SubNet AND server.keyword:$Server AND src_ip:$Src_ip AND http_metod.keyword:$Metod",
      "refId": "B",
      "timeField": "@timestamp"
    },
    {
      "alias": "▲ OUT {{term Pool.keyword}}",
      "bucketAggs": [
        {
          "fake": true,
          "field": "Pool.keyword",
          "id": "3",
          "settings": {
            "min_doc_count": 1,
            "order": "asc",
            "orderBy": "_term",
            "size": "0"
          },
          "type": "terms"
        },
        {
          "field": "@timestamp",
          "id": "2",
          "settings": {
            "interval": "auto",
            "min_doc_count": 0,
            "trimEdges": 0
          },
          "type": "date_histogram"
        }
      ],
      "dsType": "elasticsearch",
      "hide": false,
      "metrics": [
        {
          "field": "bytes_out",
          "id": "1",
          "meta": {},
          "settings": {},
          "type": "sum"
        }
      ],
      "query": "Pool.keyword:/Common/$Pool AND http_status.keyword:$StatusCode  AND node.keyword:$Node AND node_port.keyword:$Port AND subnet.keyword:$SubNet AND server.keyword:$Server AND src_ip:$Src_ip AND http_metod.keyword:$Metod",
      "refId": "C",
      "timeField": "@timestamp"
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeRegions": [
    {
      "colorMode": "blue",
      "fill": true,
      "from": "3",
      "fromDayOfWeek": 6,
      "line": false,
      "op": "time",
      "to": "3",
      "toDayOfWeek": 1
    },
    {
      "colorMode": "custom",
      "fill": true,
      "fillColor": "rgba(92, 92, 92, 0.3)",
      "from": "12",
      "line": false,
      "op": "time",
      "to": "21"
    }
  ],
  "timeShift": null,
  "title": "",
  "tooltip": {
    "msResolution": false,
    "shared": true,
    "sort": 2,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "histogramValue": "percent",
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "decbytes",
      "label": "Transferencia",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": false
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}

**Comment by marefr** [comment] 2019-01-31 21:34
Is this a duplicate of #15156?

**Comment by torkelo** [comment] 2019-02-01 05:08
yes, it's a dupe and already fixed in nightly build!

**Closed by torkelo** 2019-02-01 05:08 UTC
Labels: comp: frontend, type: bug
