### ISSUE TITLE
Problem with GiB und GB in newest grafana version

### ISSUE THREAD

**Issue by RedJohn14** [grafana/grafana#16423] opened 2019-04-06 12:50 UTC
Hello,

I have a problem with GiB und GB in newest grafana version. I used "Singlestat" or "Gauge" for Visualization. And have problems if I would like to see used GB or GiB. (see attached screenshots)

With Graph Visualization is no problem.

**Comment by RedJohn14** [comment] 2019-04-06 12:51
![Bildschirmfoto 2019-04-06 um 14 51 23](https://user-images.githubusercontent.com/47501883/55669749-7b0a3900-587b-11e9-953f-4c30771ae601.png)
![Bildschirmfoto 2019-04-06 um 14 51 03](https://user-images.githubusercontent.com/47501883/55669751-7cd3fc80-587b-11e9-91c3-26387ba9e5ad.png)

**Comment by RedJohn14** [comment] 2019-04-06 12:52
On Screenshots you can see my issue, 2 GB or 2 GiB not 2.000 GiB

**Comment by torkelo** [comment] 2019-04-07 12:39
dupe of https://github.com/grafana/grafana/issues/16373

**Comment by torkelo** [comment] 2019-04-07 12:39
Fix coming, PR is already open

**Closed by torkelo** 2019-04-07 12:39 UTC
