### ISSUE TITLE
grafana 7 : transformation parameters doesnt show ...TypeError: n.state is null

### ISSUE THREAD

**Issue by ouinouin** [grafana/grafana#25228] opened 2020-05-30 02:52 UTC
**What happened**:
while selecting a transformation, (click select), the selected transformation parameters doesnt appear, in some transofrmations you can see a result on the table. sometimes while zooming in and out with the date picker , the transformation parameters fiinish by appearing, but any time i quit the query editor and come back to try to reedit the transformatio, i get this on a single black page : 

An unexpected error happened
TypeError: n.state is null

    in t
    in div
    in Ma
    in div
    in an
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

**What you expected to happen**:
expect to see the transformation parameters anytime i click on the select button of a transformation.

**How to reproduce it (as minimally and precisely as possible)**:
use an influxdb database, and create a graph or table panel , go to the transform tab, and select the operations transform for example, the view showing wich calculation (total difference etc etc etc.) wont apperar.
save the panel, go back to somewhere else in grafana, go back again to the transformation editor  of the panel you just created, and you ll ge tthis page : 
**Anything else we need to know?**:

**Environment**:
![Capture d’écran du 2020-05-30 04-36-02](https://user-images.githubusercontent.com/6713759/83317864-6d0e3900-a230-11ea-9852-a825c719d221.png)

- Grafana version: tested on 7.0 beta3 7.0.1 on docker environment and also on native debian installation.
- Data source type & version: influxdb 1.7
- OS Grafana is installed on: tested on debian and docker
- User OS & Browser: tested on chromium and firefox
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment] 2020-05-30 06:16
Could you try to copy the error from the browser JavaScript console when the error happens? Then you would probably get a non-truncated stacktrace.

**Comment by aknuds1** [comment] 2020-05-30 06:18
I think this might be a duplicate of #25194. Can you try downloading the [nightly](https://grafana.com/grafana/download/7.1.0-1d66e55cpre) and see if it solves the issue?

**Comment by ouinouin** [comment] 2020-06-02 05:53
Hi, tried to download the nigthlies in deb format or in docker, y got error 404 for the deb package and same kind of error for the docker container, i tried with many different tags : 

wget https://dl.grafana.com/oss/master/grafana_7.1.0-4a981fcdpre_amd64.deb
--2020-06-02 07:51:56--  https://dl.grafana.com/oss/master/grafana_7.1.0-4a981fcdpre_amd64.deb
Résolution de dl.grafana.com (dl.grafana.com)… 151.101.122.217, 2a04:4e42:1d::729
Connexion à dl.grafana.com (dl.grafana.com)|151.101.122.217|:443… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2020-06-02 07:51:57 erreur 404 : Not Found.

**Comment by aknuds1** [comment] 2020-06-02 05:56
@ouinouin Hi sorry, apparently nightly Debian and RPM packages haven't been uploaded since about 10 days. I'm looking into it right now. See #25236. Sorry!

**Comment by ouinouin** [comment] 2020-06-02 05:58
got it, bu seems the docker nightly  is also affected by this, i cant manage to dl any image 7.1.0-xxxxxxxx also in docker.

**Comment by aknuds1** [comment] 2020-06-02 06:13
@ouinouin I've found that there's a bug in our publishing, it should be https://dl.grafana.com/oss/master/grafana_7.1.0~4a981fcdpre_amd64.deb.

**Comment by ouinouin** [comment] 2020-06-02 06:15
yep, dl is working. any hint fot the docker image link ?

**Comment by aknuds1** [comment] 2020-06-02 06:15
Don't know yet. Working to solve the RPM/Debian publishing issue.

**Comment by ouinouin** [comment] 2020-06-02 06:23
ok, 
at least I confirm the bug is solved in the version above mentionned.
the "binary operation" in the calculation transformation is a bit misleading, but the results are OK, just have to set "fill" to "previous" to got  a correct graph.

**Comment by aknuds1** [comment] 2020-06-02 06:31
In that case I guess we can close the issue, thanks for testing the nightly.

**Closed by aknuds1** 2020-06-02 06:31 UTC
Labels: area/frontend, needs investigation, type/bug
