### ISSUE TITLE
Google OAuth2 and support roles mapping

### ISSUE THREAD

**Issue by inkdude** [grafana/grafana#32457] opened 2021-03-29 20:09 UTC
**What would you like to be added**:

Hi! We go to google auth in auth grafana - that's really cool, but we need role mapping. We use roles mapping with ldap groups when use openldap, but now we go to the google and i don't find this features

**Why is this needed**:
Grafana have setting for default role for all users from google auth, but this is wrong. Admin - only one user or some group of users, all other people shoul be viewers or editors, but not admins.

**Comment by Elfo404** [comment] 2021-04-01 10:31
hi @inkdude 

Have you checked https://grafana.com/docs/grafana/latest/auth/generic-oauth/#role-mapping?

closing this as it's not a bug nor a feauter request, if you need support or have generic questions please post them in our [Community forum](https://community.grafana.com/)

**Closed by Elfo404** 2021-04-01 10:31 UTC
