### ISSUE TITLE
X-Axis display broken on Brave Browser

### ISSUE THREAD

**Issue by jeanlucmongrain** [grafana/grafana#46424] opened 2022-03-10 16:54 UTC
Grafana version: 8.4.3

Even if brave is Chromium + specifics, I didn't expected Brave to behave differently.
the X axis don't seem to adapt to the size. The legend always step on each others.
Change zoom level, sometimes somewhat work around that issue. but not all the time.

![Comparison](https://user-images.githubusercontent.com/474302/157713803-2722bfd4-1b5c-4ae9-a5d4-a6c23a83d17f.png)

![Larger](https://user-images.githubusercontent.com/474302/157714245-8616461b-d07f-4efa-a3a0-a6d8642602be.png)

**Comment by Elfo404** [comment] 2022-03-11 10:23
Hi @jeanlucmongrain thanks for reporting this.

It is very weird, i'm not able to reproduce this, it works just fine for me. 
I'm assuming that is the timeseries panel (looks like it is), would you be able to share your dashborad json? and which exact version of Brave are you running?

Thank you

**Comment by jeanlucmongrain** [comment] 2022-03-11 17:33
@Elfo404 

> It is very weird, i'm not able to reproduce this, it works just fine for me.

I'm running latest stable release (V1.36.112)

On Linux, more precisely PopOS (Ubuntu 21.10 variant) 

> I'm assuming that is the timeseries panel (looks like it is), would you be able to share your dashborad json?

I can reproduce this on EVERY timeseries

**Comment by leeoniya** [comment] 2022-03-15 23:32
i tried in Manjaro (Arch Linux) and also cannot reproduce this in Version 1.36.111 Chromium: 99.0.4844.51 (Official Build) unknown (64-bit).

this looks like a duplicate of https://github.com/grafana/grafana/issues/37957

**Comment by zoltanbedi** [comment] 2022-06-03 08:19
I'm going to close this now. Let us know if there is still an issue.

**Closed by zoltanbedi** 2022-06-03 08:19 UTC
Labels: needs more info, area/panel/timeseries

**Comment by wbwue** [comment] 2022-07-25 07:53
I'm having similar issue since many Brave versions, the dashboard works just fine in Firefox. For me it is mainly on single stat and gauge panels.
![image](https://user-images.githubusercontent.com/7753305/180726099-1bc8c2e2-6356-4748-bf0f-c4f6f32f198d.png)
![image](https://user-images.githubusercontent.com/7753305/180726256-658b36ce-71f7-4548-81be-5af01fcaa1dd.png)
