### ISSUE TITLE
Render problems on grafana 2.5.0 and empty share link/render on latest build

### ISSUE THREAD

**Issue by szibis** [grafana/grafana#2791] opened 2015-09-21 19:29 UTC
Hi,

I have build Version: 2.5.0-pre1, Commit: v2.1.2+356-g1f95927, Build date: 2015-09-16 14:28:41 +0000 UTC

System Ubuntu 14.04 Server

Unfortunately latest build from today 21.09.2015 have empty share link and render url only goes to after sharing some graphs

On working release i have some trouble with rendering. Sometimes renders ok, sometimes with 

![not_found](https://cloud.githubusercontent.com/assets/329831/10001775/c03333de-60a3-11e5-889b-0a719b6d1f5a.png)

Sometimes with:

![cutted images and no auth no vars](https://cloud.githubusercontent.com/assets/329831/10001782/c66d8830-60a3-11e5-9b0a-afcda351703a.png)

How is this possible to render without auth from web browser that work with UI with no problems and renders all image, view, edit ?. Tokens are forwarder in this case as we have image render behind warning and error message.

This is not stable right now. Same results from curl some graphs renders ok, some after second time refresh, sometimes not found back after next refresh/curl get. Render times when ok 2-3 seconds, when not ok 10-14 seconds.

After 5 parallel gets on web browser now i have only not fround renders all dead. 

From logs with Trace level:

```bash
2015/09/21 18:57:22 [I] Completed /api/login/ping 401 Unauthorized in 2.013791ms
2015/09/21 18:57:27 [I] Completed /api/datasources/proxy/2/metrics/find/ 401 Unauthorized in 146.696µs
2015/09/21 18:57:27 [I] Completed /api/datasources/proxy/2/metrics/find/ 401 Unauthorized in 149.117µs
2015/09/21 18:57:27 [I] Completed /api/login/ping 401 Unauthorized in 5.276091ms
2015/09/21 18:57:32 [I] Completed /dashboard-solo/db/graphite_internals 404 Not Found in 787.175µs
2015/09/21 18:57:32 [I] Completed /api/dashboards/db/graphite_internals_v2 401 Unauthorized in 2.353063ms
2015/09/21 18:57:32 [I] Completed /api/login/ping 401 Unauthorized in 377.218µs
2015/09/21 18:57:43 [I] Completed /dashboard-solo/db/graphite_internals 404 Not Found in 776.36µs
2015/09/21 18:57:43 [I] Completed /api/dashboards/db/graphite_internals 401 Unauthorized in 2.22214ms
2015/09/21 18:57:43 [I] Completed /api/login/ping 401 Unauthorized in 332.589µs
2015/09/21 19:10:42 [I] Completed /dashboard-solo/db/graphite_internals 404 Not Found in 2.877049ms
2015/09/21 19:10:42 [I] Completed /api/dashboards/db/graphite_internals 401 Unauthorized in 2.278485ms
2015/09/21 19:10:42 [I] Completed /api/login/ping 401 Unauthorized in 450.892µs
2015/09/21 19:11:14 [I] PhantomRenderer::renderToPng url https://grafana.example.com/dashboard-solo/db/graphite_internals?panelId=19&fullscreen&from=1441355263555&to=1441362463557&var-env=production&var-region=xxxxx&var-clustername=xxxx&width=1000&height=500
```

Each of this requests from working authorized web browser with google oauth setup which work good and dashboard UI work with no problems as share function but render as described before. 

From curl same problems as decsribed

When i log in as admin without google:

```
2015/09/21 19:20:10 [I] PhantomRenderer::renderToPng url https://grafana.example.com/dashboard-solo/db/es-utilization?panelId=1&fullscreen&from=1442859594441&to=1442863194445&width=1000&height=500
2015/09/21 19:20:11 [I] Completed /dashboard-solo/db/es-utilization 404 Not Found in 27.734024ms
2015/09/21 19:20:22 [I] PhantomRenderer::renderToPng url https://grafana.example.com/dashboard-solo/db/es-utilization?panelId=1&fullscreen&from=1442859594441&to=1442863194445&width=1000&height=500
2015/09/21 19:20:33 [I] PhantomRenderer::renderToPng url https://grafana.example.com/dashboard-solo/db/es-utilization?panelId=1&fullscreen&from=1442859594441&to=1442863194445&width=1000&height=500
2015/09/21 19:20:34 [I] Completed /dashboard-solo/db/es-utilization 404 Not Found in 5.872003ms
2015/09/21 19:20:37 [I] PhantomRenderer::renderToPng url https://grafana.example.com/dashboard-solo/db/es-utilization?panelId=1&fullscreen&from=1442859594441&to=1442863194445&width=1000&height=500
2015/09/21 19:20:50 [I] PhantomRenderer::renderToPng url https://grafana.example.com/dashboard-solo/db/es-utilization?panelId=1&fullscreen&from=1442859594441&to=1442863194445&width=1000&height=500
2015/09/21 19:20:51 [I] Completed /dashboard-solo/db/es-utilization 404 Not Found in 4.348046ms
2015/09/21 19:20:51 [I] Completed /api/login/ping 401 Unauthorized in 1.843355ms
```

First request:

![error_render](https://cloud.githubusercontent.com/assets/329831/10002377/04558938-60a7-11e5-9643-600141871ba4.png)

Second request for render same url:

![good_render](https://cloud.githubusercontent.com/assets/329831/10002383/0d48046c-60a7-11e5-98ee-3364d43179de.png)

Third request with same url:

![not_found_render](https://cloud.githubusercontent.com/assets/329831/10002389/14123ede-60a7-11e5-9d67-afcefe85b46f.png)

No graphite problems on backend side. Old grafana 1.9 and graphite-web performing with no problems.

Any ideas why this work in such way ?

**Comment by torkelo** [comment] 2015-09-22 05:33
Strange, Have not noticed anthing like this. What do you use for session storage? Looks like the sessions are timing out or getting lost. 

Try cleaning up grafana data/sessions folder (think it should be in /var/lib/grafana/data). This should be done automatically by Grafana but maybe something is wrong in the cleanup process. 

I did discover a bug in the share modal, fixed in latest master build (not directly related to the issues you are seeing)

**Comment by szibis** [comment] 2015-09-22 07:59
I use MySQL for sessions, but same problem with one host and in memory sessions. I now move data dir to tmpfs if works then it is quicker but still same issues as described before. All PNG files exists after rendering in png dir and there is tmpfs space for more in my case.

It would be grate to have memcache with hashing for sessions store. This will be good because  memcache is used for cache in graphite-web, then grafana would use this next to graphite API on same machine, less moving parts and fast store.

**Comment by torkelo** [comment] 2015-09-22 08:19
Are you using a proxy in front of grafana? any logs that can help troubleshoot this. Never seen an issue similar to this

**Comment by szibis** [comment] 2015-09-22 08:25
I think problem is session uniqueness ? When i use one instance of grafana all is working good. When i reset sessions, move to file all working, but when i add second instance behind loadbalancer and switch to mysql as session i have not found problems.

**Comment by szibis** [comment] 2015-09-22 08:46
What kind of logs do you need. I have Trace logging in grafana backend but there is nothing more then info or i just wrongly set this.

**Comment by torkelo** [comment] 2015-09-22 09:30
Are you sure that your mysql session store config is working and active? are you getting sessions in the session table? This could explain it, you need mysql session store if you have multiple grafana servers and a load balancer

**Comment by szibis** [comment] 2015-09-22 10:27
Yes i have session table in grafana DB:

```
mysql> use grafana;
Database changed
mysql> select * from session;
Empty set (0.00 sec)

mysql> select * from session;
Empty set (0.00 sec)

mysql> desc session;
+--------+------------------+------+-----+---------+-------+
| Field  | Type             | Null | Key | Default | Extra |
+--------+------------------+------+-----+---------+-------+
| key    | char(16)         | NO   | PRI | NULL    |       |
| data   | blob             | YES  |     | NULL    |       |
| expiry | int(11) unsigned | NO   |     | NULL    |       |
+--------+------------------+------+-----+---------+-------+
3 rows in set (0.00 sec)
```

I do have proper configuration in all two grafana instrances like:

```
provider = grafana:xxxxxx@tcp(10.1.1.2:3306)/grafana
```
All grants for grafana DB fro grafana user and this should works with no problems, but it's not.

Many lines with 401 unauthorized explains sessions problem, but after total reinstall grafana with grafana with all grafana db drop with sessions table recreated and all sources/configs not helped.

**Comment by torkelo** [comment] 2015-09-22 10:41
you dont appear to have nay rows in the session table, `Empty set (0.00 sec)`

**Comment by szibis** [comment] 2015-09-22 10:43
Yes nothing but for now i don't know why.

**Comment by torkelo** [comment] 2015-09-22 10:47
@szibis have you restarted grafana after config change? Can you check grafana admin view and make sure that you session config change is active?

**Comment by szibis** [comment] 2015-09-22 11:24
Yes i restarted grafana after recreate and many time before. Yes on admin in system info i have all my changes loaded.

**Comment by torkelo** [comment] 2015-09-22 11:56
not sure what the problem is in your install :( everything works here. 

![image](https://cloud.githubusercontent.com/assets/10999/10017781/93c72902-6131-11e5-86c0-7f4f3fbf32e2.png)

![image](https://cloud.githubusercontent.com/assets/10999/10017790/a48c2b5c-6131-11e5-9e32-fe07682961dd.png)

**Comment by torkelo** [comment] 2015-09-22 11:57
Another this that could be causing issues if root_url in grafana.ini make sure it is set to the the the root url you see in your browser (the domain / url of the loadbalancer), the root url is used when setting session cookies.

**Closed by torkelo** 2015-09-22 11:57 UTC

**Comment by szibis** [comment] 2015-09-22 13:10
root url is set to domain loadbalanced that points in browser. Any difference i have is that i have no session_id_hashfunc set and there is nothing in doc about that. 

Still nothing i will look at this after break maybe this will help me to look at problem from bigger perspective

**Comment by szibis** [comment] 2015-09-22 13:13
Thanks for help

**Comment by torkelo** [comment] 2015-09-22 13:18
You not using any auth proxy or somthing similar? check traffic between load balancer and grafana, maybe it is caching requests or doing something with the requests. Clear cookies etc
