### ISSUE TITLE
explore log tab panel time column format error

### ISSUE THREAD

**Issue by denissduan** [grafana/grafana#20140] opened 2019-11-01 03:33 UTC
**What happened**:
when i search logs at explore log panel, the first time column display error
![image](https://user-images.githubusercontent.com/8587100/68000524-6d932100-fc9b-11e9-8ead-297a1d2267d5.png)

**What you expected to happen**:
display correct time and can format localize like "2019-11-1 11:32:00"
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment] 2019-11-01 14:24
Duplicate of https://github.com/grafana/grafana/issues/19909. Already in our ToDo.

**Closed by aocenas** 2019-11-01 14:24 UTC
Labels: type/duplicate
