### ISSUE TITLE
Safari problem with Edit panel

### ISSUE THREAD

**Issue by UAnton** [grafana/grafana#31308] opened 2021-02-18 07:54 UTC
**What happened**:
After click Edit - blank screen. No any errors in browser console.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Use last Safari Technology Preview

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.4.2
- Data source type & version: Prometheus 2.24.1
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: MacOS 11.2 & Safari
- Grafana plugins:
- Others:

**Comment by dprokop** [comment] 2021-02-18 12:13
Confirmed bug, panel edit is not shown unless you resize the window

**Comment by dprokop** [comment] 2021-02-24 08:11
@UAnton this seems to be fixed now on master and will be released in next Grafana version.

**Closed by dprokop** 2021-02-24 08:11 UTC
Labels: type/bug

**Comment by ardu1** [comment] 2021-05-26 11:22
Hello, is there any date, when the next Grafana version with the solved problem is comming?

**Comment by jrs65** [comment] 2021-06-07 20:44
@ardu1 we just upgraded and this bug seemed to be fixed in 7.5.7

**Comment by ardu1** [comment] 2021-06-09 06:22
Hello, thanks for the information. I tried to update my Grafana VM with v7.3.7 (1e261642f4), but when I use in terminal this command apt-get update and the upgrade I only get the information, that all is up to date?

> ***@***.***:~# apt-get update
> OK:1 https://repos.influxdata.com/debian buster InRelease
> OK:2 http://security.debian.org/debian-security buster/updates InRelease
> OK:3 http://deb.debian.org/debian buster InRelease
> OK:4 http://deb.debian.org/debian buster-updates InRelease
> Paketlisten werden gelesen... Fertig
> ***@***.***:~# apt-get upgrade
> Paketlisten werden gelesen... Fertig
> Abhängigkeitsbaum wird aufgebaut.       
> Statusinformationen werden eingelesen.... Fertig
> Paketaktualisierung (Upgrade) wird berechnet... Fertig
> 0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
> ***@***.***:~# 


Do you have an idea to install how to the new version or better to install the version 8, which is ready since 2 days?

Thanks and best regards

**Comment by ardu1** [comment] 2021-06-10 05:50
I could it install and it works.

Thanks!
