### ISSUE TITLE
Customize body of webhook contact point in alerting

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82696] opened 2024-02-15 18:01 UTC
### Discussed in https://github.com/grafana/grafana/discussions/68158

<div type='discussions-op-text'>

<sup>Originally posted by **Helloworld-can** May  9, 2023</sup>
Hello,

Was hoping if there's  way we can achieve this use case within Grafana.

Idea is to trigger Webhook(with Body) event whenever a panel goes in Alerting state.

Was hoping if anyone has been able to achieve this?

Type: Grafana On-Prem
version: 9.2.1
Alerting Type: Unified Alerting
Alert Manager: Grafana</div>

**Comment by armandgrillet** [comment] 2024-03-13 10:18
Dupe of https://github.com/grafana/grafana/issues/6956

**Closed by armandgrillet** 2024-03-13 10:18 UTC
Labels: type/feature-request, area/alerting, migrated-discussions
