### ISSUE TITLE
Expansion of list variables in CloudWatch queries with multiple dimensions only works if variable is specified as first dimension

### ISSUE THREAD

**Issue by ab791520b4** [grafana/grafana#12181] opened 2018-06-06 12:24 UTC
I am using Grafana 5.1.0 with the CloudWatch data source.

When I add a graph with a metric query for AWS/ElasticBeanstalk:LoadAverage1min I need to specify multiple dimensions (EnvironmentName and InstanceId). For each EnvironmentName I have a variable `$instances` containing a list with all instance IDs. When I set everything up things work like a charm:

![grafik](https://user-images.githubusercontent.com/32538765/41037267-1a063ed8-6993-11e8-82b9-5004b619d221.png)

But as soon as I save the dashboard and reload the dashboard then it no longer works. It seems that the order of the dimensions changed from InstanceId first to InstanceId second:

![grafik](https://user-images.githubusercontent.com/32538765/41037433-a176c072-6993-11e8-8868-2563d0bcb163.png)

The chart then displays "No data points" and instead of listing multiple graphs in the legend (one for each entry in $instances) exactly one entry is shown in the legend where {{InstanceId}} is a complete list of all entries in $instances (e.g. "{i-abcdef, i-012345}").

I would expect that it does not matter whether InstanceId is specified first or second. In both cases I would expect the list to be correctly expanded into multiple queries.

The broken request:
<pre><code>{"from":"1528236000000","to":"1528287468219","queries":[{"refId":"metricFindQuery","intervalMs":1,"maxDataPoints":1,"datasourceId":256,"type":"metricFindQuery","subtype":"dimension_values","region":"eu-central-1","namespace":"AWS/ElasticBeanstalk","metricName":"LoadAverage1min","dimensionKey":"InstanceId","dimensions":{"EnvironmentName":"foo","InstanceId":"{i-012345,i-abcdef}"}}]}</code></pre>

The response to the broken request:
<pre><code>{"results":{"metricFindQuery":{"refId":"metricFindQuery","meta":{"rowCount":0},"series":null,"tables":[{"columns":[{"text":"text"},{"text":"value"}],"rows":[]}]}}}</code></pre>

**Comment by torkelo** [comment] 2018-06-06 20:02
duplicate of https://github.com/grafana/grafana/issues/11062

**Closed by torkelo** 2018-06-06 20:02 UTC
