### ISSUE TITLE
Improve experience when using devices with small screens

### ISSUE THREAD

**Issue by yvonne-tydwr** [grafana/grafana#16402] opened 2019-04-05 07:55 UTC
**What happened**:
Running a dashboard (graph panel) on a small mobile device it seems not possible to hide the side menu.  The TV icon is not visible for some reason.

**What you expected to happen**:
It should be possible to hide the side menu

**How to reproduce it (as minimally and precisely as possible)**:
View on a small mobile device, there is no TV icon to click.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.1.0
- Data source type & version:
Influx
- OS Grafana is installed on:
Ubuntu
- User OS & Browser:
Chrome on android
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2019-04-05 08:02
But the side menu is not visible on small devices? 

![image](https://user-images.githubusercontent.com/1668778/55612995-dd830c80-5789-11e9-855d-3cd2148f7c48.png)

**Comment by yvonne-tydwr** [comment] 2019-04-05 08:16
That's interesting.  A little more research seems to show that this is only a problem with certain sizes of device.  With a larger device the TV icon is present so there is no problem:
![image](https://user-images.githubusercontent.com/49303561/55613551-d99fbc00-5782-11e9-93b2-1247515721a9.png)

With a small device it is as you have shown, the side menu does not show, so again no problem, but in between there is a range of sizes where there is no TV icon, but there is a side menu:
![image](https://user-images.githubusercontent.com/49303561/55613743-4dda5f80-5783-11e9-855c-386fe7adbeb8.png)
This can be seen by using a browser on a PC and reducing the window size.

**Comment by marefr** [comment] 2019-04-05 08:36
Duplicate of #16382

**Comment by colinl** [comment] 2019-04-05 08:42
#16382 is marked as a dup of #11523 which is titled 'Share icon missing -mobile devices', which does not sound like a particularly serious issue.  However the fact that on certain devices it is not possible to hide the side menu makes it much more serious, at least to us, as the devices we use as panels have the problem so we lose a significant amount of screen real estate.

**Comment by torkelo** [comment] 2019-04-05 09:33
Maybe we need to tweak the responsive rule for when sidemenu is hidden and replaced with the mobile menu? 

The TV button is not really designed for use with mobile/small screens but for large screens when wanting to go into "non interactive" mode and hide sidemenu or dashboard toolbar

**Comment by yvonne-tydwr** [comment] 2019-04-05 09:49
If it dropped into mobile menu mode at the size where currently the top icons disappear that, I think, would solve the problem for me.

**Closed** 2019-04-26 17:16 UTC
Labels: area/dashboard, type/feature-request
