### ISSUE TITLE
Support user defined timezone in defaults

### ISSUE THREAD

**Issue by pseudocoder** [grafana/grafana#18449] opened 2019-08-08 08:43 UTC
Please support a user-defined timezone (i.e. free format string) in the defaults for system, user and dashboard.

Two benefits:

- allows a workaround for cases where the browser timezone isn't recognised by the server/database
- allows users to specify a specific timezone globally, independent of their own location

**Comment by marefr** [comment] 2019-08-08 08:49
Duplicate of #558

**Comment by marefr** [comment] 2019-08-08 08:49
Please search for existing issues before opening new ones. Thanks

**Closed by marefr** 2019-08-08 08:49 UTC
Labels: type/duplicate

**Comment by pseudocoder** [comment] 2019-08-08 09:15
Thanks - I did search, the other one is a mess of suggestions and seems to be referring to a fixed offset.

I added a comment regarding this proposal at the end.
