### ISSUE TITLE
Ad hoc filters can not be attached into bashboard links unless refresh the whole page.

### ISSUE THREAD

**Issue by liukch** [grafana/grafana#26776] opened 2020-08-04 07:00 UTC
#### What happened:

In Dashboard Links, the type is "dashboards" with tags, check the "Variable values".
Then add a filter, click dashboard link, the filter can not be carried by the dashboard link.
If I add a filter, then press 'F5' to refresh the whole page, then the dashboard link will carry the filter.

#### What you expected to happen:

I think "refresh page" is unreasonable, when I add a filter, do not need refresh page, the "Variable values" will work.

#### How to reproduce it (as minimally and precisely as possible):

- Create two dashboards, data source is Elacticsarch
- In "Dashboard settings" -> "Links", create dashboard links, type is "dashboards", with tags, check the "Variable values"
- In "Dashboard settings" -> "Variables", add filters, type is "Ad hoc filters", name is "Filters"
- Add a filter then click dashboard link, the link not carry the filter
- Add a filter then refresh the whole page, click the dashboard link, the link will carry the filter

##### Environment:

Grafana version: Grafana v7.1.1 (3039f9c)
Data source type & version: Elasticserch 1.6.0
OS Grafana is installed on: Official docker
User OS & Browser: Microsoft Windows 10 Education 19041 & Firefox 78.0.1
Grafana plugins: None
Others:

**Comment by aknuds1** [comment] 2020-08-04 07:01
Please rewrite the issue description using our standard issue template.

**Comment by liukch** [comment] 2020-08-04 07:21
> Please rewrite the issue description using our standard issue template.

OK

**Comment by torkelo** [comment] 2020-08-04 15:35
ad hoc filters are not really a normal variable and is not supported in dashboard links, duplicate of https://github.com/grafana/grafana/issues/12394

**Closed by torkelo** 2020-08-04 15:35 UTC
