### ISSUE TITLE
Telegram alerts is not working.

### ISSUE THREAD

**Issue by emilianito** [grafana/grafana#17856] opened 2019-07-01 17:05 UTC
Telegram alerts is not working.

I have configured Telegram Alerts with KEY API and GROUP ID correctly since I click on "send test" button and I get the test alert in telegram group inmediatly.
I have setted up a metric with the Telegram alert I have setted before.
When the metrics is over the threshold (and the graphic shows a red label with the text "ALERTING"), the alert is never sent. (I excpect an alert in the telegram group)

Update: I have found some log:

t=2019-06-29T00:38:31+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-06-29T00:38:31+0000 lvl=eror msg="Could not close Telegram inline image." logger=alerting.notifier.telegram err="invalid argument"
t=2019-06-29T00:38:31+0000 lvl=eror msg="Could not generate Telegram message with inline image." logger=alerting.notifier.telegram err="open : no such file or directory"

- Grafana version: Grafana v6.2.5 (6082d19) - Docker image
- Data source type & version: Prometheus  Version | 2.10.0 d20e84d0fb64aff2f62a977adc8cfb656da4e286
- OS Grafana is installed on: official Docker Image grafana/grafana
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: none
- Others: none

**Comment by marefr** [comment] 2019-07-02 07:52
The problem is with rendering of image "Failed to upload alert panel image". For the panel where alert rule is defined, if you open panel menu and select Share and click on Direct link rendered image. What happens then?

Could be that you have too little memory assigned to your docker container. PhantomJS which is used for render the panel image needs quite a lot of memory.

**Comment by emilianito** [comment] 2019-07-03 16:05
When I click on that link, after several seconds (about one minute), I got this message:

Grafana / Server Error
Sadly something went wrong
Timeout error. You can set timeout in seconds with &timeout url parameter

Check the Grafana server logs for the detailed error message.

And the log says:

t=2019-07-03T15:56:49+0000 lvl=info msg=Rendering logger=rendering path="dashboard-solo/new?tab=queries&panelId=2&orgId=1&from=1562147759388&to=1562169359388&width=1000&height=500&tz=UTC"
t=2019-07-03T15:56:50+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname= method=GET path=/dashboard-solo/new status=404 remote_addr=127.0.0.1 time_ms=136 size=26371 referer=
t=2019-07-03T15:57:52+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-07-03T15:57:52+0000 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"

**Comment by marefr** [comment] 2019-07-03 19:28
Seems like you tried direct rendered image of a panel in a new dashboard (not saved) based on the path `dashboard-solo/new?tab=queries`. I asked you to do direct rendered image of the panel where your alert rule is defined (same alert that you showed Grafana server log messages from in issue description).

**Comment by marefr** [comment] 2019-08-07 13:43
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Closed by marefr** 2019-08-07 13:43 UTC
Labels: area/alerting/notifications, area/image-rendering, needs more detail

**Comment by debugloop** [comment] 2020-01-28 13:59
Hi @marefr, I'm hitting this exact issue, see logs below. Clicking on `Direct link rendered image` as you've asked yields a 504 Gateway Time-out from nginx, which is my reverse proxy, creating the following log entries.

Alert logs:
```
t=2020-01-28T14:41:01+0100 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=2 newState=pending prev state=ok
t=2020-01-28T14:43:01+0100 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=2 newState=alerting prev state=pending
t=2020-01-28T14:43:01+0100 lvl=info msg=Rendering logger=rendering path="d-solo/P1PPwUCiz/cluster-health?orgId=1&panelId=42"
t=2020-01-28T14:43:31+0100 lvl=info msg="Rendering timed out" logger=rendering
t=2020-01-28T14:43:31+0100 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2020-01-28T14:43:31+0100 lvl=eror msg="Could not generate Telegram message with inline image." logger=alerting.notifier.telegram err="open : no such file or directory"
t=2020-01-28T14:43:31+0100 lvl=info msg="Sending telegram notification" logger=alerting.notifier.telegram chat_id=mychatid12345 bot_token=mytokenishereXYZ123 apiAction=sendMessage
t=2020-01-28T14:43:31+0100 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="context deadline exceeded" webhook="Daniel Telegram"
t=2020-01-28T14:43:31+0100 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000001 error="context deadline exceeded"
t=2020-01-28T14:43:31+0100 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000001 error="context deadline exceeded"
t=2020-01-28T14:51:01+0100 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=2 newState=ok prev state=alerting

```

Manual image render:
```
t=2020-01-28T14:54:44+0100 lvl=info msg=Rendering logger=rendering path="d-solo/P1PPwUCiz/cluster-health?orgId=1&from=1580217867993&to=1580219667994&var-nodes=All&var-requesttype=Fetch&panelId=42&width=1000&height=500&tz=Europe%2FBerlin"
t=2020-01-28T14:55:44+0100 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="signal: killed"
t=2020-01-28T14:55:44+0100 lvl=eror msg="Rendering failed." logger=context userId=0 orgId=1 uname= error="signal: killed"
t=2020-01-28T14:55:44+0100 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/P1PPwUCiz/cluster-health status=500 remote_addr=129.143.0.165 time_ms=60074 size=1722 referer="http://myfqdn/d/P1PPwUCiz/cluster-health?orgId=1&from=now-30m&to=now"
```

**Comment by marefr** [comment] 2020-01-28 14:37
@debugloop please use Grafana 6.6.0 which include this fix https://github.com/grafana/grafana/pull/21536. PhantomJS being killed usually could mean you don't have enough memory available for it. You could also try the [grafana image renderer plugin](https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin).

**Comment by debugloop** [comment] 2020-01-28 15:08
@marefr Thanks for the heads-up, updates were borked on this node because of a faulty repo... Alerts seem to be working fine again, thanks :+1:

The direct image rendering is still not working though, and the node in question has more than 3GB of memory available. I only need the feature for fancy alerts, but I'll dig into that tomorrow and create/locate an issue if needed. Thanks again :+1:

**Comment by debugloop** [comment] 2020-01-28 15:24
Okay, so instead of calling it a day I attempted to debug this right quick. Just manually running yields the follwing:

```
# /usr/share/grafana/tools/phantomjs/phantomjs --ignore-ssl-errors=true --web-security=true --local-url-access=false --debug=false /usr/share/grafana/tools/phantomjs/render.js url="http://localhost:3000/d-solo/P1PPwUCiz/cluster-health?orgId=1&from=1580221896552&to=1580223696552&var-nodes=All&var-requesttype=Fetch&panelId=42&width=1000&height=500&tz=Europe%2FBerlin&render=1" width=1000 height=500 png=/var/lib/grafana/png/PqmKJ0hsASu23rMG9lk4.png domain=localhost timeout=60 renderKey=xQZdgOC16QV37CgBMo3IWCPKr6PTtkaZ
Loading a web page: http://localhost:3000/d-solo/P1PPwUCiz/cluster-health?orgId=1&from=1580221896552&to=1580223696552&var-nodes=All&var-requesttype=Fetch&panelId=42&width=1000&height=500&tz=Europe%2FBerlin&render=1 status: success 60000
ERROR: TypeError: undefined is not an object (evaluating 'container[0].getBoundingClientRect')
TRACE:
 -> undefined: 6
 -> : 7

  phantomjs://code/render.js:48 in onError
TypeError: null is not an object (evaluating 'bb.width')

  phantomjs://code/render.js:68 in checkIsReady
```

Which is idling indefinitely if left alone and is probably only getting killed when Grafana terminates the request context (or something) when my nginx times out. However, I also saw that there's an effort of deprecating phantomjs, so I won't create an issue unless you tell me otherwise.

**Comment by marefr** [comment] 2020-01-28 15:30
@debugloop thanks. Yeah please use the [grafana image renderer plugin](https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin) instead since PhantomJS is marked as deprecated and others have reported problems with it on latest versions.

**Comment by 1014670860** [comment] 2022-05-26 04:55
I think I solved it. It should be caused by carrying too much data, so you need to set the corresponding relationship in [Notification policies](https://logging.gojapp.com/alerting/routes), so that only separate alarm messages will be sent.
