### ISSUE TITLE
gauge shows alias / names

### ISSUE THREAD

**Issue by Links2004** [grafana/grafana#27189] opened 2020-08-25 09:53 UTC
**What happened**:

Update from 7.0.3 to 7.1.4, single stat gauge shows alias / names.
this effects a lot of my boards and looks very ugly.
I where not able to find a way to hide it again, and on top editing 80+ dashboards is time consuming.

example:

![image](https://user-images.githubusercontent.com/974709/91159089-de427880-e6c7-11ea-9518-ca771b08dd67.png)

**What you expected to happen**:

no names / alias shown for single stat gauge by default.

**How to reproduce it (as minimally and precisely as possible)**:

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {},
          "decimals": 0,
          "mappings": [],
          "max": "3.5",
          "min": "-0.5",
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "#1F60C4",
                "value": null
              },
              {
                "color": "#37872D",
                "value": 0.5
              },
              {
                "color": "#73BF69",
                "value": 1.5
              },
              {
                "color": "#E24D42",
                "value": 2.5
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 4,
        "w": 4,
        "x": 0,
        "y": 0
      },
      "hideTimeOverride": true,
      "id": 2,
      "links": [],
      "options": {
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "last"
          ],
          "fields": "",
          "values": false
        },
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },
      "pluginVersion": "7.1.4",
      "targets": [
        {
          "refId": "A",
          "target": "keepLastValue(stats.gauges.zehnder.kwl.setting.speed, 30s)",
          "textEditor": false
        }
      ],
      "timeFrom": "1m",
      "timeShift": null,
      "title": "Speed",
      "type": "gauge"
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "New dashboard",
  "uid": null,
  "version": 0
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.4
- Data source type & version: graphite 1.10.7
- OS Grafana is installed on: Debian 9
- User OS & Browser: Chrome
- Grafana plugins: 
```
bessler-pictureit-panel @ 1.0.0
digrich-bubblechart-panel @ 1.2.0
fatcloud-windrose-panel @ 0.7.0
fetzerch-sunandmoon-datasource @ 0.1.6
grafana-clock-panel @ 1.1.1
grafana-image-renderer @ 2.0.0
grafana-piechart-panel @ 1.6.0
grafana-polystat-panel @ 1.2.0
michaeldmoore-annunciator-panel @ 1.0.5
michaeldmoore-multistat-panel @ 1.4.1
mtanda-heatmap-epoch-panel @ 0.1.7
natel-discrete-panel @ 0.1.0
natel-plotly-panel @ 0.0.6
petrslavotinek-carpetplot-panel @ 0.1.1
ryantxu-ajax-panel @ 0.0.7-dev
snuids-radar-panel @ 1.4.4
vonage-status-panel @ 1.0.9
yesoreyeram-boomtable-panel @ 1.4.0
```
- Others:

**Comment by torkelo** [comment] 2020-08-25 11:33
duplicate of https://github.com/grafana/grafana/issues/25212 fix in progress https://github.com/grafana/grafana/pull/27186

**Closed by torkelo** 2020-08-25 11:33 UTC
