### ISSUE TITLE
Autorefresh causes a full reload on Panels and loses the selected filters

### ISSUE THREAD

**Issue by mihail-sky** [grafana/grafana#44605] opened 2022-01-28 16:55 UTC
**What happened**:
We have a dashboard configured with auto-refresh every 30 seconds. When we select filtering on a panel and the auto-refresh is triggered, the filters are reset and panels are completely reloaded. You can see in the video at 21 seconds how the filters are reset.

https://user-images.githubusercontent.com/43004087/151588459-f383dda2-92f1-45db-bc0e-e41f7759fe4b.mov

**What you expected to happen**:
On an auto-refresh filters are still in place.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This started occuring after upgrading from 8.3.1 to 8.3.3. We downgraded to 8.3.1 and confirmed that it works as expected using the older version.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Prometheus 2.28.1
- OS Grafana is installed on: Kubernetes 1.20
- User OS & Browser: Firefox 96.0.2

**Comment by chron0** [comment] 2022-01-30 09:13
I am seeing a similar regression after an update from 8.2.x to 8.3.4 where prometheus panels are really slow and flicker during updates instead of just rendering the new data (both with old graph and new timeseries panels). At the same time the prometheus queries are somehow no longer working:

![Screenshot_2022-01-30_09-11-05](https://user-images.githubusercontent.com/3270028/151693744-5878eab1-e5e1-463f-a1f8-6f0638ec1434.png)

this showed up in console (unclear if related - just in case):

![Screenshot_2022-01-30_09-12-05](https://user-images.githubusercontent.com/3270028/151693762-e6ee6122-7910-4c89-8e61-176163539097.png)

**Comment by axsuul** [comment] 2022-01-30 16:09
Also seeing this on **8.3.4** with autorefresh on, where only the panels that vary by variable will flicker and disappear. Downgrading to **8.3.1** fixes it.


https://user-images.githubusercontent.com/187961/151707435-ae63d27c-9b2c-465c-a716-95d31554c2ef.mp4

**Comment by zuchka** [comment] 2022-02-01 19:19
@mihail-sky @axsuul @chron0 

I did some research and there are several recent issues and PRs related to variables, refreshes, and "flickering". 

1. Can you all confirm that the panels in question include template variables?

2. Can someone provide some solid reproduction steps? That would make things much easier for the squads 👍 

possibly related:
https://github.com/grafana/grafana/issues/42761
https://github.com/grafana/grafana/pull/42828
https://github.com/grafana/grafana/pull/43447
https://github.com/grafana/grafana/issues/43843

**Comment by chron0** [comment] 2022-02-01 20:08
@zuchka template variables: confirmed

**Comment by axsuul** [comment] 2022-02-01 20:09
@zuchka template variables: confirmed

**Comment by mihail-sky** [comment] 2022-02-02 10:06
@zuchka template variables: confirmed

**Comment by kaydelaney** [comment] 2022-02-10 20:07
Not having any luck reproducing this issue unfortunately.
If someone who's experienced this issue could share their dashboard I think it would help a lot with figuring out what exactly is happening here

**Comment by torkelo** [comment] 2022-02-10 20:26
@kaydelaney did you use a repeated panel? 

Think it's due to repeated panels get new key property which makes them unmount and remount. No super easy fix here other than rewriting the repeat process code in DashboardModel so that we preserve/remember the key, since we start by removing all repeated panels and then re-add them this is a pretty big / complex change

**Comment by richardsimko** [comment] 2022-06-21 08:17
I have the same issue with a repeated templated dashboard. I can share the dashboard JSON if that helps.

**Comment by chirag-prajapati-einfochips** [comment] 2022-07-21 16:08
We are observing same behaviour with version Grafana v8.3.3 . It is really required for users who work on data analysis after applying filters.

**Comment by ashharrison90** [comment] 2022-08-02 10:26
have tested and i believe this was fixed in 8.3.4

**Closed by ashharrison90** 2022-08-02 10:26 UTC
Labels: type/bug, area/dashboard/templating, area/templating/repeating
