### ISSUE TITLE
MySQL connection failing with @ in the password

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#20392] opened 2019-11-14 16:03 UTC
**What happened**:
Grafana failed to connect to the MySQL database if the password contains the @ character.
**What you expected to happen**:
Grafana should connect to the MySQL database if the password is correct.
**How to reproduce it (as minimally and precisely as possible)**
Set up a MySQL user with a password containing the @ character and rant permissions to the database. Add a data source in Grafana and provide the MySQL server information, database name, username, and a password. The connection will fail and the Grafana log will show the "Access denied for user" error.
Changing the password to the one not containing @ and updating it in the data source will result in a successful connection.

**Environment**:
- Grafana version: 6.4.4 - 
- Data source type & version: MySQL

**Comment by marefr** [comment] 2019-11-14 16:16
Duplicate of #20228

**Closed** 2019-11-14 16:16 UTC
Labels: type/duplicate
