### ISSUE TITLE
Table panel (gauge) doesn't work as expected on some data(source)

### ISSUE THREAD

**Issue by trivita** [grafana/grafana#38474] opened 2021-08-24 03:19 UTC
**What happened**:

Gauge doesn't work properly on auto Max auto Min

**What you expected to happen**:

Max = full length

**How to reproduce it (as minimally and precisely as possible)**:

please refer to my screenshots

**Anything else we need to know?**:

if I put a value in Max, everything works fine.

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: Clickhouse
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:
![image](https://user-images.githubusercontent.com/1425147/130550369-4fa28d8c-1328-4793-94f3-d6ca5f97f2a0.png)
![image](https://user-images.githubusercontent.com/1425147/130550419-e6fdd8d7-8cd2-40cd-aa48-936e884b60c5.png)

**Comment by hugohaggmark** [comment] 2021-08-24 05:33
Duplicate of #37635

**Closed by hugohaggmark** 2021-08-24 05:33 UTC

**Comment by trivita** [comment] 2021-08-24 06:20
not exactly the same, i found out that this might be related to the **json data format** returned from the data source.

in my case, the json data returned from clickhouse is actually a **string array** which in fact should be **an integer array** from SQL perspective. (very oddly, **the unit function works** on string array, for example turning '1000' to '1k') this might lead to the failure of soft max and soft min functioning properly. whileas i have another table panel, where the json data is an integer array, functions correctly.

**Comment by trivita** [comment] 2021-08-25 02:34
after further investigation into the source code
![image](https://user-images.githubusercontent.com/1425147/130716823-5a439cf3-e703-4208-9489-a10b3a8f1578.png)
this line of code should be the problem
as my data source Clickhouse, returned the int array in the string array format

1. this function won't handle integer in string format， hence the automatic min/max won't work
2. table gauge will handle integer in string format and renders correctly

**Comment by trivita** [comment] 2021-08-25 02:45
i found a workaround 
just add a binary calculation on this problematic field
now everything works properly
![image](https://user-images.githubusercontent.com/1425147/130717931-c9417c05-2fb4-4d3a-b440-f570e41397c3.png)
