### ISSUE TITLE
[Feature] Stacked X-Axis in Series Mode

### ISSUE THREAD

**Issue by tcloaa** [grafana/grafana#8787] opened 2017-07-05 08:28 UTC
Hi, may I ask that,

![screenshot from 2017-07-05 16 24 42](https://user-images.githubusercontent.com/8750937/27855877-b82b444e-619e-11e7-871b-7d7056e5c5f1.png)

Is it possible to make this bar stack together (in x-axis = series mode graph, since I am interested in values, not time)? Coz I would like to see the time used in each phase and then put them together to see the total time.

If not, how shall I modify the js source code in Graph Panel Plugin to achieve this goal myself?

Thanks!

**Comment by daniellee** [comment] 2017-07-06 09:39
Not sure I understand. The x axis does not represent time in this view. So stacking does not work here if it did then you would always get one column which seems strange?

An alternative would be to add another query for the total. E.g. query A shows columns for a, b, c, d, e and query B shows one column for the total.

**Comment by ChamMach** [comment] 2017-07-06 15:55
Hi, 
I think he want something like this : 
https://github.com/grafana/grafana/issues/7949

**Comment by daniellee** [comment] 2017-07-06 18:13
@ChamMach thanks! Closing this as a dupe of #7949

**Closed by daniellee** 2017-07-06 18:13 UTC
Labels: comp: panel/graph, type: question
