### ISSUE TITLE
[Feature Request] Playlist - template variable population

### ISSUE THREAD

**Issue by KelvinPriceDSL** [grafana/grafana#10725] opened 2018-02-02 00:17 UTC
Having built a dashboard with templated variables, it would be useful to set up a playlist that uses that dashboard for each "slide" in the slideshow, but with different values for one of the templated variables.

The sequence could just be one "slide" for each possibility in the drop-down list for a specific variable, but I can see that people might want to specify a subset of those maybe using the equivalent of the multi-select.

For instance, at the moment, for say 5 servers, server1, server2, etc you would have to have 5 individual dashboards, one for each of the 5 servers and set your playlist to iterate through those 5 individual dashboards.  It would be preferable to point to one dashboard that has a template variable for server name and have the playlist run that dashboard 5 times, each time with a different server name for the value of the variable.

**Comment by bergquist** [comment] 2018-03-14 17:40
Dupe of https://github.com/grafana/grafana/issues/773

**Closed by bergquist** 2018-03-14 17:40 UTC
Labels: comp: playlist, type: feature request
