### ISSUE TITLE
Scroll can't start in graphs on Chrome mobile

### ISSUE THREAD

**Issue by Josh-G** [grafana/grafana#11710] opened 2018-04-24 09:45 UTC
### What Grafana version are you using? 
5.1.0-beta1
### What datasource are you using? 
N/A
### What OS are you running grafana on? 
Ubuntu
### What did you do? 
Ref #11456: Opened dashboard on mobile, try to scroll page where the first touch starts within the boundary of a graph - either on the graph area or on labels etc. Tested on a Samsung Galaxy S7 Edge, Chrome 66
### What was the expected result?
The page scrolls as I drag.
### What happened instead?
The page does not scroll. This differs to previous behaviour and can make navigating dashboards with large graphs difficult.
The page also overflows on the x-axis causing a horizontal scrollbar, however this scrollbar is on a different container than the vertical scroll, so it is only possible to scroll left and right in this overflowed space.
![scrolling](https://user-images.githubusercontent.com/487384/39179553-822dd0b0-47ac-11e8-8486-6df06dc7ca77.gif)

**Comment by bergquist** [comment] 2018-04-24 17:54
@daniellee you be the judge if this should be fixed in 5.1

**Comment by daniellee** [comment] 2018-04-30 13:50
@bergquist this is not a new problem - there are lots of pages in Grafana that do work for certain widths. But I think this is a simple fix - the problem is the time picker that is overflowing instead of wrapping underneath the title.

**Comment by daniellee** [comment] 2018-05-02 08:50
Can confirm that the scrolling after clicking directly on a graph panel should work (it does on an iPhone) so we will try and fix that as well.

**Closed** 2018-05-03 13:18 UTC
Labels: comp: mobile support, type: bug, type: ux
