### ISSUE TITLE
[Feature request] trigger the alerts separately in the same graph but different group by tags

### ISSUE THREAD

**Issue by pdu** [grafana/grafana#9348] opened 2017-09-25 14:44 UTC
Hi,

My use case is: I have to setup the CPU monitoring for the k8s cluster which contains more than 20 nodes. Then I config the graph to include all the CPU usage data of all the nodes and assign a threshold for alerting.

node one breaks the threshold, an alert was triggered
While the alert was not recovered, node two also breaks the threshold

The current behavior is to not trigger the alert again
The wanted behavior is to trigger the alert again that node two breaks the threshold

Questions:
1, do you already have the plan to support this use case?
2, if you accept this use case and don't have the development plan, may I help to implement this and contribute back?

Thanks,
Peng

**Comment by bergquist** [comment] 2017-09-27 15:14
This is a dupe of https://github.com/grafana/grafana/issues/6041

**Closed by bergquist** 2017-09-27 15:14 UTC
