### ISSUE TITLE
After update to 8.0.0-1 one Dashboard reports "Dashboard init failed" (other dashboards works OK)

### ISSUE THREAD

**Issue by dan-m-joh** [grafana/grafana#35405] opened 2021-06-09 09:13 UTC
After updating to 8.0.0-1 this morning we get "Dashboard init failed" for one of our dashboards.

![image](https://user-images.githubusercontent.com/26163222/121325768-2d356380-c912-11eb-9d75-464642d56611.png)

Before the update (v 7.5.7) the dashboard worked flawlessly.

**Environment**:
- Grafana version: 8.0.0-1
- Data source type & version: InfluxDB v1.8.6-1
- OS Grafana is installed on: CentOS Linux 8
- User OS & Browser: Linux/Windows Firefox/Chrome/Edge

Any suggestion on how to debug this?

**Comment by zoltanbedi** [comment] 2021-06-09 09:33
duplicate of https://github.com/grafana/grafana/issues/34788

**Closed by zoltanbedi** 2021-06-09 09:33 UTC
