### ISSUE TITLE
Drag-and-drop causes existing panels to jump between rows

### ISSUE THREAD

**Issue by bmerry** [grafana/grafana#11015] opened 2018-02-26 06:41 UTC
- What Grafana version are you using?
5.0.0-beta4 (from Dockerhub)
- What datasource are you using?
Prometheus (but can be seen without a datasource)
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Added a new panel to a dashboard which uses rows and dragged it to where I wanted it. Afterwards, some of the existing panels had moved to different rows.
- What was the expected result?
The existing panels should stay in the row they were placed (and ideally with the layout they were placed with).
- What happened instead?
Existing panels moved between rows.
 
I can reproduce it fairly reliably from a brand-new dashboard (no data source needed) - I didn't resize any of the panels, just picked an arbitrary panel type.
1. Add two rows.
2. Add two panels to the bottom row, side-by-side.
3. Add one panel to the top row, on the left.
4. Add a new panel and drag it downwards. The right-hand panel from the second row jumps up to the top row.

In general I've found the behaviour of panels trying to move to accommodate the dragged panel to be a frustrating experience, frequently destroying my layout. I would prefer to lock down the existing layout and only be able to drag a new panel to a hole.

It may also help to add new panels to the bottom instead of the top, since I go about constructing a dashboard from the top down and thus every new panel has to be dragged through the already-placed ones to get to the bottom.

**Comment by torkelo** [comment] 2018-02-26 08:55
thanks for reporting this, will close as it has already been reported. 

duplicate of https://github.com/grafana/grafana/issues/10831 

We have a fix but waiting for grid framework project to merge our fix.

**Closed by torkelo** 2018-02-26 08:55 UTC
