### ISSUE TITLE
Alerts cannot connect to database since 8.1.0

### ISSUE THREAD

**Issue by jnguiot** [grafana/grafana#37626] opened 2021-08-06 08:02 UTC
## Environment:
* Grafana 8.1.0
* Influxdb 1.8.9-1
* Debian 9

## Initial Condition:
* Influxdb and Grafana are installed on the same server. 
* Influxdb has an authentication with a login and a password

## How to reproduce:
* Create a dashboard
* Create a graph panel.
* Input any query related to your data into the query panel (eg `SELECT mean("percent_packet_loss") FROM "ping" WHERE ("url" = 'xxxxx') AND $timeFilter GROUP BY time($__interval) fill(null)`
* In Alerting tab of the graph, input a threshold, 
* Save dashboard
* Click on test rule in alert tab

## Observed behavior:
* when testing rule, we have this response:
```
firing:true
state:"alerting"
conditionEvals:" = true"
timeMs:"168.163ms"
error:"request handler error: failed to query data: InfluxDB returned error status: 401 Unauthorized"
logs:Array[1]
0:Object
message:"Condition[0]: Query"
data:Object
from:1628236340096
queries:Array[1]
0:Object
to:1628236640096
```
## Expected behavior:
* no error should be displayed when testing. Alert should be fired if data requires it.

## Misc
Please note:
* all our alerts have suffered this issue when updating from 8.0.6 to 8.1.0
* no configuration has changed on influxdb, especially authentication
* grafana still display data. Only alerting seems broken.
* reverting back to 8.0.6 fixes our issue

Thank you for Grafana which is an incredible piece of software. I will do my best to help you on this matter.

**Comment by yakob-aleksandrovich** [comment] 2021-08-06 10:25
+1, the same issue happened with us as well. Only difference: Graphite instead of InfluxDB

**Comment by cykl** [comment] 2021-08-06 10:33
Same issue with Grafana 8.0 and InfluxDB 1.8. InfluxDB Data source works fine in explore mode, but all alerts fail on "401 Unauthorized"

**Comment by Ejant** [comment] 2021-08-09 00:29
+1 Same here, Using Influx 1.8 and Grafana 8.1. Downgrading solves the issue.

**Comment by gabor** [comment] 2021-08-09 10:07
hi @jnguiot , @cykl , @Ejant thanks for reporting the issue. we are looking into it, unfortunately for now i'm unable to reproduce it. i tried with influxdb-1.8.6 and also with influxdb2 (in influxql mode).
could i ask you for more info, or perhaps to doublecheck some things?:
- is this happening with "old alerting" or the new unified alerting? (the new one has to be enabled by the feature-toggle `ngalert` ( https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/ ))
- can this be reproduced by using a simple query, without any template variables, then switching to the alert-tab and only specifying the threshold value and nothing else? (i'm trying to make sure the problem is not caused by maybe dashboard-variables or something else)
- exact influxdb version
- if you can test this: is this happening with influxdb2 in influxql-language-mode too?
- if you can test this: is this happening with influxdb2 in flux-language-mode too?


thanks!

**Comment by gabor** [comment] 2021-08-09 10:08
@yakob-aleksandrovich thanks for the report. could you please create a separate issue for your problem, as it deals with `graphite` not `influxdb`? i understand they might be related, but this way the info might get lost. thanks!

**Comment by gabor** [comment] 2021-08-09 10:11
@jnguiot @cykl @Ejant one more question:
- are you running grafan + influxdb using docker? or natively installed?

**Comment by cykl** [comment] 2021-08-09 10:18
> is this happening with "old alerting" or the new unified alerting?

alertng

> can this be reproduced by using a simple query, without any template variables, then switching to the alert-tab and only specifying the threshold value and nothing else?

Yes.

Simple query:

![image](https://user-images.githubusercontent.com/1764725/128691203-00bb8310-8617-4c34-a231-8e858292ac66.png)

Create new alert:

![image](https://user-images.githubusercontent.com/1764725/128691308-818f879a-f33e-4e34-9271-3d273cbfae0b.png)

> exact influxdb version

1.8.2-alpine using InfluxQL (:scream_cat: )

> are you running grafana + influxdb using docker? or natively installed?

I'm using helm chart version 6.14.2 with image.tag set to 8.1.0

> if you can test this: is this happening with influxdb2 in influxql-language-mode too?
> if you can test this: is this happening with influxdb2 in flux-language-mode too?

I don't use influxdb2. But could define a Flux datasource if that really help.

My data source is provisioned as follow:

```
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: influxdb
      type: 'influxdb'
      is_default: true
      access: proxy
      database: micrometer
      user: [readacted]
      password: [redacted]
      url: 'https://[redacted]/'
      jsonData:
        httpMode: GET
```

**Comment by jnguiot** [comment] 2021-08-09 10:19
Thank @gabor for your time on this. 

> is this happening with "old alerting" or the new unified alerting? (the new one has to be enabled by the feature-toggle ngalert ( https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/ ))

I would assume it is the "old alerting". Our Grafana is an old Grafana instance with apt auto update. We did no manual actions when updating to 8.0.

>  can this be reproduced by using a simple query, without any template variables, then switching to the alert-tab and only specifying the threshold value and nothing else? (i'm trying to make sure the problem is not caused by maybe dashboard-variables or something else)

Please check my report. Yes, I was able to reproduce it with a very simple query with no template variable ($timeFilter and $__interval are Grafana required variables to draw the graph)

> exact influxdb version

```
root@supervision:~# influx --version
InfluxDB shell version: 1.8.9 
```

> if you can test this: is this happening with influxdb2 in influxql-language-mode too?
> if you can test this: is this happening with influxdb2 in flux-language-mode too?

Unfortunately, I don't know influxdb2. I might have a look on it later

> are you running grafana + influxdb using docker? or natively installed?

It is natively installed on a Debian 9

> when configuring the influxdb data source, to reproduce the problem is it enough to set the URL , the DATABASE, the USERNAME and the PASSWORD? or are you using some special setting there?

I actually did not change my datasource configuration, just using the one that was working since I believe it would make no difference. I will try to reproduce this bug today with a datasource creation.

**Comment by gabor** [comment] 2021-08-09 13:33
@cykl i might have found the issue, not 100% sure yet:

when i looked at your provisioning example, you are provisioning it like:
```
user: something
password: something
```

there is a newer way to do:
```
user: something
secureJsonData:
    password: something
```

this workaround should fix your problem, could you try it?
(more info with example data source provisioning here https://grafana.com/docs/grafana/latest/administration/provisioning/)

alternatively, if you have the datasource created manually, re-entering the password in the password-field and saving it should achieve the same.

@yakob-aleksandrovich @jnguiot @Ejant could you try this too?

**Comment by Ejant** [comment] 2021-08-09 13:46
> hi @jnguiot , @cykl , @Ejant thanks for reporting the issue. we are looking into it, unfortunately for now i'm unable to reproduce it. i tried with influxdb-1.8.6 and also with influxdb2 (in influxql mode).
> could i ask you for more info, or perhaps to doublecheck some things?:
> 
> * is this happening with "old alerting" or the new unified alerting? (the new one has to be enabled by the feature-toggle `ngalert` ( https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/ ))

We have the issue with only old alerting.

> * can this be reproduced by using a simple query, without any template variables, then switching to the alert-tab and only specifying the threshold value and nothing else? (i'm trying to make sure the problem is not caused by maybe dashboard-variables or something else)
> * exact influxdb version

Version 1.8.0
> * are you running grafana + influxdb using docker? or natively installed?

Natively. Running on Debian 8.11

> * when configuring the influxdb data source, to reproduce the problem is it enough to set the URL , the DATABASE, the USERNAME and the PASSWORD? or are you using some special setting there?

Only URL, user and password, no special settings.

> * if you can test this: is this happening with influxdb2 in influxql-language-mode too?

no, we don't have Influx 2.x

> * if you can test this: is this happening with influxdb2 in flux-language-mode too?
> 
> thanks!
> 
> [EDIT: added more questions]

**Comment by Ejant** [comment] 2021-08-09 13:47
> @cykl i might have found the issue, not 100% sure yet:
> 
> when i looked at your provisioning example, you are provisioning it like:
> 
> ```
> user: something
> password: something
> ```
> 
> there is a newer way to do:
> 
> ```
> user: something
> secureJsonData:
>     password: something
> ```
> 
> this workaround should fix your problem, could you try it?
> (more info with example data source provisioning here https://grafana.com/docs/grafana/latest/administration/provisioning/)
> 
> alternatively, if you have the datasource created manually, re-entering the password in the password-field and saving it should achieve the same.
> 
> @yakob-aleksandrovich @jnguiot @Ejant could you try this too?

I will try as soon as I can. I've rolled back new install because It's a Prod env.

Kr

**Comment by cykl** [comment] 2021-08-09 15:05
> @cykl i might have found the issue, not 100% sure yet:
> ```
> user: something
> secureJsonData:
>     password: something
> ```
> this workaround should fix your problem, could you try it?

Just tried it; I confirm that it does fix the issue. Thanks for the prompt investigation :+1: 

> (more info with example data source provisioning here https://grafana.com/docs/grafana/latest/administration/provisioning/)

It seems that InfluxDB datasource documentation hasn't been updated and still documents the old way: https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/ 

Might be worth reviewing the data sources documentation and/or ensuring coherent behavior between query and alerting.

**Comment by germm** [comment] 2021-08-09 15:09
Thank you @gabor for the suggested workaround. Re-entering the password in the datasource configuration fixed the issue for my manually created datasource.

**Comment by gabor** [comment] 2021-08-09 15:14
@cykl wrote:

> It seems that InfluxDB datasource documentation hasn't been updated and still documents the old way: https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/
> 
> Might be worth reviewing the data sources documentation and/or ensuring coherent behavior between query and alerting.

yes, i'll look into improving it.

**Comment by jnguiot** [comment] 2021-08-09 15:15
Should we update our datasources or new Grafana version will take care of it?

**Comment by gabor** [comment] 2021-08-09 15:16
@grafana/backend-platform the problem seems to be somewhere in https://github.com/grafana/grafana-plugin-sdk-go , could you look at it please? 

(i can create a separate github-issue in that repo and close this one if you prefer to do it that way)

**Comment by Ejant** [comment] 2021-08-10 02:41
> Thank you @gabor for the suggested workaround. Re-entering the password in the datasource configuration fixed the issue for my manually created datasource.

I confirm that this fixes the issue.

**Comment by gabor** [comment] 2021-08-11 07:44
@jnguiot 

> Should we update our datasources or next new Grafana version will take care of it?

i do recommend to update the datasources. the "old way" has been deprecated, so updating is the safest approach forward.

**Comment by gabor** [comment] 2021-08-11 07:51
to summarize: with grafana 8.1, there was a change to how alerts get executed, and the new code path does not support the "old password approach".

considering this has been marked as deprecated for some time, we decided that compatibility with the old approach will not be restored, and we will update our documentation to explain that this does not work anymore.
i'm sorry for the confusion and problems this caused, the workaround (update the provisioning-template, or just re-enter the password) should fix this.

**Comment by steverweber** [comment] 2021-08-11 13:29
> Thank you @gabor for the suggested workaround. Re-entering the password in the datasource configuration fixed the issue for my manually created datasource.

I currently have 14 influxdb datasources. Some I might not even remember the password to. Please automate the "workaround" on install of the new version it should be possible to update the datasources to whatever this new format it.

**Comment by kartoffelheinz** [comment] 2021-08-12 08:48
Been bitten by this from today's upgrade to 8.1.1- All our 1.000s alerts fired immediately since the default for "error" is "alert"...

We were never notified that all configured data sources apparently use "old" and deprecated ways of password storage. In what way shoudl I have been notified by Grafana? 

Making such a breaking change in a minor update version, without automatic migration, without a BIG FAT WARNINGS just asks for huge trouble.

**Comment by steverweber** [comment] 2021-08-12 12:47
To add to kartoffelheinz experience. It was a frighting moment when my phone started buzzing with alerts. Had to fanatically stop the grafana service. Lucky many of the high severity alerts were set with a 15min delay or it would have hit mailing lists saying there's issues with server rooms AC, UPS, storage systems and other scary things that keep us up at night. Basically this could have generated a bunch of unwanted email traffic in a large organization and yes all fingers would come back pointing at me.  Next grafana upgrade I'll be doing on a staging server.

**Comment by marefr** [comment] 2021-08-16 12:09
@gabor what's left here? Adding a new section for Grafana 8.1 [here](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v80) and close it? Anything else?

**Comment by steverweber** [comment] 2021-08-16 13:18
I implore Grafana developers to consider making this task an auto handled database migration.

**Comment by marefr** [comment] 2021-08-17 08:21
When deprecating this in Grafana v6.2 we decided not to run this as an automatic database migration. See [upgrade notes](https://grafana.com/docs/grafana/latest/installation/upgrading/#ensure-encryption-of-data-source-secrets).

There exists a command using the grafana cli that allows you to migrate data sources using unencrypted passwords, see https://grafana.com/docs/grafana/latest/administration/cli/#migrate-data-and-encrypt-passwords

**Closed** 2021-08-19 14:36 UTC
Labels: datasource/InfluxDB, area/backend, area/unified-alerting

**Comment by marefr** [comment] 2021-08-23 12:40
I'll open a PR to address the upgrade notes for v8.1...
