### ISSUE TITLE
Dashboards: upgrade from version 10.1.5 to version 10.2.0, influxql template variables get double escaped and break

### ISSUE THREAD

**Issue by rschultz7** [grafana/grafana#77465] opened 2023-10-31 17:32 UTC
### What happened?

After my upgrade from version 10.1.5 to version 10.2.0 template variables that contain IP address's are double escaped, as it they appear as 10\\.1\\.1\\.1 instead of 10\.1\.1\.1 I git bisected it down to this commit https://github.com/grafana/grafana/pull/75653

### What did you expect to happen?

That it works like in version 10.1.5 and variables not get double escaped. 

### Did this work before?

Yes version 10.1.5

### How do we reproduce it?

1. Create variable that pulls information from InfluxDB via InfluxQL and the result is an IP address
select DISTINCT("vcenter") from (select "usage_average","vcenter" from "vsphere_host_cpu" WHERE $timeFilter)
2. Create second variable referencing the first 
select DISTINCT("clustername") from (select "usage_average","clustername" from "vsphere_host_cpu" WHERE $timeFilter AND "vcenter" =~ /$vcenter/)
3. Won't probably pull the values as the $vcenter variable gets double escaped. 

`http://someurl/query?db=somedatabase&q=select DISTINCT("clustername") from (select "usage_average","clustername" from "vsphere_host_cpu" WHERE time >= 1698751354270ms and time <= 1698772954270ms AND "vcenter" =~ /10\\.1\\.1\\.1/)&epoch=ms`

### Environment (with versions)?

Grafana: 10.2.0
OS: Arch Linux
Browser: Firefox 119

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by gpinkos** [comment] 2023-11-01 09:27
I do not have a system running 10.1.5 that I can roll back to and play with, but using v10.2.0 and a simple template variable containing an IP address, it appears to work correctly...

InfluxQL query:
`SELECT mean("value") FROM "measurement" WHERE "vcenter" =~ /$vcenter/ AND $timeFilter GROUP BY time($__interval) fill(null)`

with a variable selected, from Inspect Query:
`query:"SELECT mean(\"value\") FROM \"measurement\" WHERE \"vcenter\" =~ /192.168.44.98/ AND $timeFilter GROUP BY time($__interval) fill(null)"`

![image](https://github.com/grafana/grafana/assets/97072938/881d9dc5-a37b-4548-bbe9-0e67dc8c385d)

**Comment by rschultz7** [comment] 2023-11-01 16:42
Here are some pictures to show difference between 10.1.5 and 10.2.0

10.1.5 - Dashboard showing correct data
![Screenshot from 2023-11-01 09-11-02](https://github.com/grafana/grafana/assets/146036904/551a51e4-2f8b-448b-a4ef-5cb5596a73d5)

Template variable pulling the tags. 
![Screenshot from 2023-11-01 09-11-43](https://github.com/grafana/grafana/assets/146036904/d97410c1-c8a9-4914-b18e-8a535b958585)

Proper escaped query in browser developer tools. 
![Screenshot from 2023-11-01 09-15-14](https://github.com/grafana/grafana/assets/146036904/5e53f5bf-be3f-4c26-a0c4-81cc6bb0d052)


10.2.0
Dashboard Broken
![10 2 0 dashboard not working](https://github.com/grafana/grafana/assets/146036904/b1d90b74-e87b-4d7a-a0f6-ef1b303028d9)

Template Query not pulling values. 
![10 2 0 datastore settings](https://github.com/grafana/grafana/assets/146036904/14a4ca4b-f103-43f3-86cb-7fa969b7cd1c)

Network request has double escaped IP address. 
![10 2 0 web request double escaped](https://github.com/grafana/grafana/assets/146036904/23b33221-0ced-45e6-bd6a-6a06cccec09d)


All variables 
![10 2 0 variables](https://github.com/grafana/grafana/assets/146036904/18d8e45b-9b7d-4f8a-9221-bc5970558c3a)


I am using Telegraf vsphere input plugin to InfluxDB 2.  I am using the dashboard located at https://grafana.com/grafana/dashboards/8159-vmware-vsphere-overview/?tab=revisions revision 38 as it was the last one to utilize InfluxQL.

**Comment by keeks5** [comment] 2023-11-01 18:21
Same problem after upgrade to 10.2. 
The problem seems to be variables specific. They are broken.
On panels it works.

But this is a bad one, most of the dashboards affected.

**Comment by rschultz7** [comment] 2023-11-01 20:47
> Same problem after upgrade to 10.2. The problem seems to be variables specific. They are broken. And it seems to happen if there is some sign(like . or ) etc. ) in the variable value that is used in the query. On panels it works.
> 
> EDIT: Found workaround, at least for my dashboards. https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#advanced-variable-format-options
> 
> @rschultz7 Changed my filters like this: "server" = '${servers:raw}' - if variable has one value "server"=~ /${servers:regex}/ - if variable has multiple values

Thanks, workaround also worked for my dashboards. Hopefully the underlying issue can be found.

**Comment by rschultz7** [comment] 2023-11-01 20:58
> I do not have a system running 10.1.5 that I can roll back to and play with, but using v10.2.0 and a simple template variable containing an IP address, it appears to work correctly...
> 
> InfluxQL query: `SELECT mean("value") FROM "measurement" WHERE "vcenter" =~ /$vcenter/ AND $timeFilter GROUP BY time($__interval) fill(null)`
> 
> with a variable selected, from Inspect Query: `query:"SELECT mean(\"value\") FROM \"measurement\" WHERE \"vcenter\" =~ /192.168.44.98/ AND $timeFilter GROUP BY time($__interval) fill(null)"`
> 
> ![image](https://user-images.githubusercontent.com/97072938/279631633-881d9dc5-a37b-4548-bbe9-0e67dc8c385d.png)

@gpinkos The dashboard queries that use vcenter variable work fine. Its the additional variables that reference the first variable (vcenter) that are broken.

**Comment by natellium** [comment] 2023-11-20 18:13
Hey @grafana/observability-metrics , I'm removing Dashboards because it seems the issue is influxDB only. If there's anything we can do to help do let us know :)

**Comment by itsmylife** [comment] 2023-11-20 19:00
@natellium Thanks for pinging us. It is a data source issue indeed. 

The problem should have been resolved by this PR https://github.com/grafana/grafana/pull/78068
And it is backported to `v10.2.x` https://github.com/grafana/grafana/pull/78068
`v10.2.2` will have the fix.

**Comment by mbentley** [comment] 2024-01-04 15:55
I am not sure if this is exactly related but I also have noticed that I have variables which are no longer working as expected when I upgrade to Grafana 10.2.x and it also seems to be related to improperly escaped characters.  I am on 10.2.3 right now and I have a variables where there are characters that need to be escaped but they are not.  If I roll back to 10.1.6, they function as expected.  I can see in the InfluxDB logs what Grafana is querying:


10.1.6 properly escaped:
```
ts=2024-01-04T15:43:34.381012Z lvl=info msg="executing new query" log_id=0mJG1EDW000 query="SELECT last(\"total\") FROM \"trivy\" WHERE (\"image\" =~ /^mbentley\\/acme\\.sh:latest-amd64$/ AND \"image\" =~ /^mbentley\\/.*/) AND time >= now() - 7d and time <= now() GROUP BY time(2h), \"image\" fill(none)"
```

10.2.3, improperly escaped:
```
ts=2024-01-04T15:47:35.364305Z lvl=info msg="executing new query" log_id=0mJG1EDW000 query="SELECT last(\"total\") FROM \"trivy\" WHERE (\"image\" =~ /^mbentley/acme.sh:latest-amd64$/ AND \"image\" =~ /^mbentley\\/.*/) AND time >= 1703778455227ms and time <= 1704383255227ms GROUP BY time(2h), \"image\" fill(none) ORDER BY time ASC"
```

An example of an item that is failing as a variable is `mbentley/acme.sh:latest-amd64`

Here is my query:
```
SELECT last("total") FROM "trivy" WHERE ("image" =~ /^$IMAGE$/ AND "image" =~ /^mbentley\/.*/) AND $timeFilter GROUP BY time($__interval), "image" fill(none)
```
![screenshot 2024-01-04 at 10 53 41 AM](https://github.com/grafana/grafana/assets/414445/6c7ac0b6-0830-4698-b623-81b6ba016905)

**Closed** 2024-01-31 23:30 UTC
Labels: datasource/InfluxDB, area/dashboard/templating, triage/needs-confirmation
