### ISSUE TITLE
Alignment of the time axis between different graph panels

### ISSUE THREAD

**Issue by hsmptg** [grafana/grafana#14742] opened 2019-01-05 22:29 UTC
It is possible to force the alignment of the time axes between different graph panels within the same dashboard?
Note that the end of the time axes (right side of it) are align but if we have different widths in the y-axis labels then a slight misalignment between graphs occur that do not allow an easy comparison of events present in different graphs.
Regards

**Comment by torkelo** [comment] 2019-01-07 07:05
duplicate of https://github.com/grafana/grafana/issues/4469

**Closed by torkelo** 2019-01-07 07:05 UTC
