### ISSUE TITLE
Logs in explore missing timestamp with elasticsearch

### ISSUE THREAD

**Issue by chelomontilla** [grafana/grafana#20152] opened 2019-11-04 08:50 UTC
**What happened**:
In version 6.4.3 the logs are missing the timestamp, and is always displaying 2019-01-01 00:00:00
In the explore section.
**What you expected to happen**:
With previous version 6.3.5 the same data displays correctly the timestamp.
**How to reproduce it (as minimally and precisely as possible)**:
Configure a elasticsearch datasource with log data and configure the time field.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Elasticsearch 7.1
- OS Grafana is installed on: docker official image
- User OS & Browser:chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-11-04 11:50
dupe of https://github.com/grafana/grafana/issues/19909

**Closed by torkelo** 2019-11-04 11:50 UTC
