### ISSUE TITLE
Nested template query uses Grafana variable name instead of OpenTSDB tag name

### ISSUE THREAD

**Issue by benelgiac** [grafana/grafana#22674] opened 2020-03-10 10:44 UTC
**What happened**:
I have an OpenTSDB time-series with 4 tags. Those are "revision", "host", "webserver", "testname". 
I have created four variables in Grafana to be able to select values for each of these tags. Those are:
 * SvnRevision = tag_name(metric, revision)
 * Host             = tag_name(metric, host)
 * WebServer  = tag_name(metric, webserver)
 * TestName    = tag_name(metric, testname)

They are all "multiple choices" variables with the "All" selection enabled. So far so good. 

I have tried to modified "TestName" to be nested and only pick test name for a particular revision number, so I modified the definition to

 * TestName    = tag_name(metric, testname, revision=$SvnRevision)

This worked fine except if "All" is selected for the variable "SvnRevision". Troubleshooting the query performed by Grafana, this is what I saw

![Varname instead of tag name](https://user-images.githubusercontent.com/6727932/76303502-27417480-62c2-11ea-966d-32f2f1f7a5e1.png)

It seems like the query uses the correct tag name "revision" just when querying for the first value, then it switches to a tag name "SvnRevision". Of course there is no tag with that name in OpenTSDB and the result set is empty.

**What you expected to happen**:

I'd expect that the query is the same despite Grafana variable name, and that the tag name is always used.

If I rename the variable "SvnRevision" to match the tag name "revision" everything works fine

![renamed Variable](https://user-images.githubusercontent.com/6727932/76303667-61ab1180-62c2-11ea-8a6e-5f1d4cb2c93a.png)

**How to reproduce it (as minimally and precisely as possible)**:
 * Load a metric with at least two tags (t1, t2) in OpenTSDB. Make sure each tag has at least a few different values.
 * Create two Grafana template variables for each of the tags values, "multiple choice" and "All" enabled. 
 * Give the variables names that are different from the tag name themselves (MyT1, MyT2)
 * Make the second variable a nested one (i.e. MyT2 = tag_values(metric, t2, t1=$MyT1).
 * From the dashboard, select "All" for MyT1. The LOOKUP query generated by Grafana to get values for MyT2 uses "MyT1" as a tag name instead of "t1".
 * Rename the variable "MyT1" to "t1" and perform the same test from the dashboard. It should now work.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6
- Data source type & version: OpenTSDB 2.3.1
- OS Grafana is installed on: Ubuntu 18.04.3 LTS
- User OS & Browser: Ubuntu 19.10 & Chrome 80.0.3987.122 (Official Build) (64-bit)
- Grafana plugins:
- Others:

**Comment by benelgiac** [comment] 2020-03-10 10:49
By the way, I'd expect that when I select "All" for a variable name, the query would use a "*" wildcard in the query instead of explicitly passing the entire list of values.

**Comment by torkelo** [comment] 2020-03-10 14:40
for that you need to specify a wildcard All value in the template variable options

**Comment by benelgiac** [comment] 2020-03-10 14:49
Oh yeah that would be the "Custom all value" setting! Did not notice it, thank you!

**Comment by aocenas** [comment] 2020-11-18 09:49
Needs to be checked whether this is something to fix on TSDB plugin side or it is something in the template variables interpolation logic.

**Comment by zoltanbedi** [comment] 2021-02-26 14:23
I couldn't reproduce this issue in 7.4 so I'm closing this now. If you think this is still an issue we can reopen this.

**Closed by zoltanbedi** 2021-02-26 14:23 UTC
Labels: area/dashboard/templating, datasource/OpenTSDB, effort/small, help wanted, needs investigation, type/bug
