### ISSUE TITLE
Add datasource template variables

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#3110] opened 2015-10-31 02:40 UTC
I have different datasources for the same dashboard. Currently I had to copy the dashboard to another, and change the datasource of graphs one by one.  It's more convenient with datasource template variables

**Comment by torkelo** [comment] 2015-10-31 10:34
dupe of https://github.com/grafana/grafana/issues/816

**Closed by torkelo** 2015-10-31 10:34 UTC
