### ISSUE TITLE
Using wildcard Span names causes Tempo to be unable to display Service Graph

### ISSUE THREAD

**Issue by lusson-luo** [grafana/grafana#65447] opened 2023-03-28 08:33 UTC
**Describe the bug**

I am writing to report an issue that I have encountered with Tempo. I have noticed that when I use a Span name with a wildcard, such as `"/actuator/health/**"`, it causes Tempo to be unable to display the Service Graph. As a result, I would like to know how to handle this issue.

Could you please provide some guidance on how to use wildcard Span names with Tempo, while still being able to display the Service Graph? Also, it would be helpful if you could provide some background on why wildcards cause issues with the Service Graph, and any best practices or recommendations for using Span names with wildcards.

Thank you for your attention to this matter. I appreciate any help or advice you can provide.

**To Reproduce**
use grafana choose Service Graph, click query, then notify failed.
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/19859400/228177014-4801278f-846b-4062-a5e0-d74fad062ddd.png">
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/19859400/228177509-eb8b321a-ea88-4303-ba2d-611a8e24ccb1.png">

**Expected behavior**
Display normal Service Graph

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
**Additional Context**

**Comment by aocenas** [comment] 2023-04-04 08:26
This is a duplicate of https://github.com/grafana/grafana/issues/65447

**Comment by joey-grafana** [comment] 2023-05-15 13:18
Fixed in https://github.com/grafana/grafana/pull/66301

**Closed by joey-grafana** 2023-05-15 13:18 UTC
Labels: type/bug, prio/medium, area/tracing, datasource/Tempo
