### ISSUE TITLE
Grafana 7.1 + azure monitor: Axes Left Y change of units not respected

### ISSUE THREAD

**Issue by olsonnn** [grafana/grafana#26497] opened 2020-07-21 19:44 UTC
Grafana 7.1 + azure monitor: Axis Left Y change of unit not respected

Default for example = Seconds for unit.
Cannot change it to something else for example milliseconds. Value not saved/ shown

Graphs also show "count" and cannot set to none
![image](https://user-images.githubusercontent.com/36011279/88105042-98affe80-cba3-11ea-8b55-53bb9098988d.png)

**Comment by ivanahuckova** [comment] 2020-07-22 07:37
@olsonnnj thanks for creating the issue. The [PR fixing](https://github.com/grafana/grafana/pull/26429) this was already merged and will be part of 7.1.1 release.

**Comment by kylebrandt** [comment] 2020-07-22 12:41
@ivanahuckova are we sure this is totally fixed? From the description it sounds like part of the problem is not being able to change/override the unit that is returned by the data source.

**Comment by kylebrandt** [comment] 2020-07-22 14:06
It does seem that Grafana will not let me set the Axis label if a unit is returned with the data, so reopening.

![Azure Monitor Virtual Machines - Grafana](https://user-images.githubusercontent.com/1692624/88186267-f7589500-cc02-11ea-9ded-068b0d518ce2.gif)

**Comment by kylebrandt** [comment] 2020-07-22 14:14
@ryantxu Can you explain how this is supposed to work? In other words, if the data returns a Unit, and the users wants to specify a different unit than what is returned, how is that supposed to be done?

**Comment by ryantxu** [comment] 2020-07-22 15:51
sorry, can not explain it... needed some code to make it semi-reasonable.  See #26529

**Closed** 2020-07-23 18:00 UTC
Labels: area/dataframe, area/field/overrides, datasource/Azure, datasource/Azure/Monitor
