### ISSUE TITLE
Change Default Org

### ISSUE THREAD

**Issue by dahendel** [grafana/grafana#1823] opened 2015-04-20 18:45 UTC
Is it possible to change the default org users are assigned to when they create accounts? I am sure it is trivial and I may have overlooked it in docs, but I could not find a way to do it.

**Comment by torkelo** [comment] 2015-04-20 18:56
No, right now that is always the organization with orgId = 1.

**Comment by torkelo** [comment] 2015-04-20 18:56
Is there are reason for wanting to change it?

**Comment by whisk3y** [comment] 2015-04-20 19:28
I made an Org and some dashboards and realized that for every user I had signup I would have to go in and manually assign them to that Org. It isn't a huge deal I can just import my dashboards into the default one and problem solved. Again just curious.

**Comment by agilgur5** [comment] 2015-06-09 21:52
+1, especially since the organization with orgId = 1 is created by default by Grafana ("Main Org."). Also #2068 is a duplicate of this

**Comment by jcmartins** [comment] 2015-08-25 19:32
+1, I have this problem with Google Authentication. Maybe you can incluse a Organization in the google auth link anonymous

**Comment by pokemane** [comment] 2016-10-26 17:45
+1.  Annoying when making use of several orgs with even low rates of member turnover

**Comment by dekhtyarev** [comment] 2016-12-15 06:02
+1

**Comment by olivermc1** [comment] 2017-04-03 11:44
+1

**Comment by daveselan** [comment] 2017-04-28 16:57
We could do with the ability to change the default Org to another orgid other than 1 for new users. Over time, we have several older orgids, but now our "main" orgid for new users is 6 (in our case). We use ldap and have many new users logging in and orgid 1 is only used by a handful of original developers.
This would be a great if simple feature to have!

**Comment by jcmcken** [comment] 2017-06-07 16:36
Similar use case here. We originally created an 'admin' dashboard at orgId = 1. Now we want new OAuth users to sign in and be sent to a generic, high-level dashboard (not the admin dashboard). There doesn't seem to be a simple way of accomplishing this.

**Comment by erniek** [comment] 2017-08-21 14:45
+1

**Comment by dleutnant** [comment] 2017-11-14 15:15
+1

**Comment by jcmcken** [comment] 2017-11-14 21:08
@dleutnant I don't think it's a duplicate. The referenced issue seems to be about autogenerating an organization on Grafana setup without having to configure one yourself. This issue is about setting the auto-assign org to a specific org that already exists (instead of just setting it to orgId = 1)

**Comment by dleutnant** [comment] 2017-11-15 07:56
@jcmcken Agreed. Eventually _related_ is more precise (instead of _duplicated_).

**Comment by carlislk** [comment] 2018-02-23 19:48
Any updates on this issue? I have a similar use case as mentioned above and this feature would make managing users much easier.

**Comment by marefr** [comment] 2018-07-30 15:05
Fixed by #12401

**Closed by marefr** 2018-07-30 15:05 UTC
Labels: comp: backend/user, type: feature request
