### ISSUE TITLE
Table url not redirecting to self with variable

### ISSUE THREAD

**Issue by mindfuucker** [grafana/grafana#17547] opened 2019-06-12 13:38 UTC
**What happened**:
I made a dashboard with variables called cell-overview. 
The variable is called pusher
All columns have the same url:
`/d/kyTfdH7Zz/cell-overview?var-pusher=${__cell_0}-${__cell_1}`

Clicking the table-row does nothing

**What you expected to happen**:
If you click the row, it should redirect you to the same dashboard with a variable selected. 

ctrl+click will open the correct link in a new tab. As I'm planning this in a kiosk iframe this is not what I need. 
**How to reproduce it (as minimally and precisely as possible)**:

1. create dashboard with variable query
2. create table with the same query
3. Visualisation -> Column Styles -> Url to <dashboard_url>?var-<varname>=${__cell_0}
4. Click on the table

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: PostgreSQL 11.2
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu 18.04, Firefox AND Opera
- Grafana plugins: non-used
- Others: Screenshot below
![Screenshot from 2019-06-12 15-17-14](https://user-images.githubusercontent.com/5075692/59355865-190cfa80-8d28-11e9-9699-d9e1a4d8dc90.png)

**Comment by hugohaggmark** [comment] 2019-06-12 14:34
Duplicate of #13433. See [comment](https://github.com/grafana/grafana/issues/13433#issuecomment-425146681) for a potential workaround.

**Closed** 2019-06-12 14:36 UTC
Labels: type/duplicate
