### ISSUE TITLE
OOB dashboard ARG query picker not working as expected

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#59761] opened 2022-12-03 00:26 UTC
**What happened**: a previously working OOB dashboard, see: https://grafana.com/grafana/dashboards/15128-azure-alert-consumption/ shows weird behavior on ARG queries. 

When I select the right combination of variables to return data, it works as expected:

![image](https://user-images.githubusercontent.com/20448042/205411440-6be9d154-215d-437e-a5a4-611a13056a6a.png)

This, however, is not true all the time. If I select a sub from the dropdown that is _not_ my default sub in the datasource, the panel only loads _as long as I do not go into edit mode_. I think that this is due to the fact that the sub picker for the ARG query is not using the right value. Here is what my JSON looks like: 

![image](https://user-images.githubusercontent.com/20448042/205411725-96d41268-235b-4b62-956c-575ba93a61ff.png)

and here is what the ARG query looks like:

![image](https://user-images.githubusercontent.com/20448042/205411763-39b3fa97-76a3-4fdd-aaf9-0ade0ce14e3a.png)

Note how the sub picker has the actual subscription rather than the variable `$sub` selected.

**What you expected to happen**:
For all my panels to work as expected regardless of sub selected

**How to reproduce it (as minimally and precisely as possible)**:
1. Download JSON for dashboard linked above
2. _Without_ editing and panels, select a sub from the variable picker that is NOT your default sub on the data source (note how data loads)
3. Edit any of the panels, note how data no longer loads (and how the sub picker shows the default description rather than $sub)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.7.1
- Data source type & version: Azure Monitor 1.0.0
- OS Grafana is installed on:
- User OS & Browser: Windows & Edge
- Grafana plugins: NA 
- Others: NA

**Comment by zuchka** [comment] 2022-12-05 23:53
Thanks for creating this issue, @jcolladokuri 

This repo doesn't have any control over that published dashboard, which was created by a third party. They list this email for feedback:
[azmongrafana@microsoft.com](mailto:azmongrafana@microsoft.com)

PS--it's not uncommon for published dashboards to grow stale, especially when it comes to template variables. https://community.grafana.com is another place that might be able to provide help 👍

**Comment by jcolladokuri** [comment] 2022-12-30 21:02
Hi @zuchka, sorry for the delay in replying, this is not something that just happens in the dashboard (sorry if that was not clear), it happens for any ARG query that I make, if I try to use a variable for the subscription:

![subPickerNotWorkingWithVariables](https://user-images.githubusercontent.com/20448042/210111385-2aa852df-25a7-401f-892d-17f0262ccda3.gif)

**Comment by zuchka** [comment] 2022-12-31 03:15
roger that--pushing this to the azure folks 👍

**Comment by jcolladokuri** [comment] 2023-01-04 00:07
Thank you! @zuchka

**Comment by andresmgot** [comment] 2023-01-10 11:34
I am able to reproduce it, this is a bug introduced here: https://github.com/grafana/grafana/pull/56284

When fetching subscriptions for populating the selector, we are sanitizing the current query subscriptions and if the subscriptions are not valid, those are cleaned up. The problem is that we are not considering template variables as valid options:

https://github.com/grafana/grafana/blob/7bb76e0975b5553f3e727c19f3015a138b226f41/public/app/plugins/datasource/grafana-azure-monitor-datasource/components/ArgQueryEditor/ArgQueryEditor.tsx#L62:L69

There, apart than `fetchedSubscriptions` we should also use `variableOptionGroup.options`.

**Comment by adamyeats** [comment] 2023-07-25 13:56
Fixed in https://github.com/grafana/grafana/pull/63731. 🎉

**Closed by adamyeats** 2023-07-25 13:56 UTC
Labels: type/bug, datasource/Azure, good first issue
