### ISSUE TITLE
Cannot set two different unit overrides for different time-series

### ISSUE THREAD

**Issue by atifali** [grafana/grafana#39263] opened 2021-09-16 00:15 UTC
**What happened**:
I have two different time-series in a panel, and trying to set field overrides with units gives the following errors:

![Screen Shot 2021-09-15 at 5 12 17 PM](https://user-images.githubusercontent.com/12394084/133529095-118d6c27-1597-4d45-836e-1b923733e1f8.png)

![Screen Shot 2021-09-15 at 5 12 56 PM](https://user-images.githubusercontent.com/12394084/133529142-a869e3c0-7fcd-4b27-a642-3b62a2e3dee0.png)

Here are the overrides and the datasource query configurations:

![Screen Shot 2021-09-15 at 5 13 41 PM](https://user-images.githubusercontent.com/12394084/133529219-31990952-be83-42a2-b6ea-14f63b39cc98.png)

![Screen Shot 2021-09-15 at 5 13 27 PM](https://user-images.githubusercontent.com/12394084/133529184-99280652-c789-40ef-9865-bd69c2740e3f.png)

**What you expected to happen**:

I would expect two different y-axis units to show up on either sides for the respective series.

**How to reproduce it (as minimally and precisely as possible)**:

Here is the panel JSON:

```
{
  "id": 23763571993,
  "gridPos": {
    "h": 10,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "timeseries",
  "title": "Test Panel",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": []
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "A-series"
        },
        "properties": [
          {
            "id": "unit",
            "value": "accMS2"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "A-series1"
        },
        "properties": [
          {
            "id": "unit",
            "value": "areaF2"
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "single"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "scenarioId": "random_walk",
      "refId": "A",
      "seriesCount": 2
    }
  ],
  "datasource": null
}
```

**Environment**:
- Grafana version: main (dev run)
- Data source type & version: gdev-testdata
- OS Grafana is installed on: macOS
- User OS & Browser: macOS, Chrome

**Comment by torkelo** [comment] 2021-09-16 16:21
duplicate of https://github.com/grafana/grafana/issues/38810

**Closed by torkelo** 2021-09-16 16:21 UTC
Labels: type/bug, area/frontend
