### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#17837] opened 2019-06-30 14:20 UTC
**What would you like to be added**:

- Ability to attach a variable to a specific panel instead of it being dashboard-specific
- Ability to move the location of the variable's value selector around the dashboard.
- Ability to specify a default value any time when multiple values are available - e.g., when the variable is set by a query.

**Why is this needed**:

I was recently trying to make an indicator more configurable by the viewer without having the modify the dashboard each time and thought that variables are the perfect way to do this. Sadly, after experimenting a bit, I had to give up on the idea. There were basically two problems I couldn't figure out how to solve.

1) The panel containing the indicator in question is far away from the top of the dashboard, while the selector for the variable's value is always at the top. This makes is a bit hard for the user to realize that by using this selector s/he can change the looks of a particular panel way down. Would have been nice if the variable was panel-specific, or at least the selector could be moved to where the panel is.

2) I can easily fill the values for the selector with a database query, but most of the time a particular value is used. Sadly, it's neither the first, nor the last value of the alphabetically sorted query results, so I cannot get it selected by default. When the variable is of type _text box_, you can specify a default value that is pre-filled - but it would be nice if you could specify the default value for other types of variables too. like _query_, _custom_, etc. If the query does not return the default value among the results, the selector could react as if no default value is set.

**Comment by torkelo** [comment] 2019-07-01 07:57
Hi, 

Thanks for reporting this feedback & feature ideas! 

dupe of https://github.com/grafana/grafana/issues/5329 

the other ideas also have similar issues but cannot find them right now.

**Closed** 2019-07-01 07:57 UTC
