### ISSUE TITLE
Parsing url in MSSQL Data Source not working correctly

### ISSUE THREAD

**Issue by gunnarthors** [grafana/grafana#31625] opened 2021-03-02 23:15 UTC
When connecting to named instance using MS SQL Data Source it seems like the instance name is ignored. 

Using docker images from docker hub.

With version 6.7.2 it works! 

Version 6.7.2 -- docker : grafana/grafana:6.7.2
Host: sqlServer.domain.local\instanceName 
Result: Connection Established. Works perfectly.

Version 7.4.3 -- grafana/grafana:7.4.3 or current grafana/grafana:latest
Host: sqlServer.domain.local\instanceName 
Result: Connection fail. Error: HostIP:1433 Connection refused

Too my understanding it seems like it solves the dns name for the sqlserver but does not add the instance name to the connection string. Otherwise the error would probably say HostIP:1433/instanceName Connection refused.  

There has been similar issues in the past which are closed issues: [25067](https://github.com/grafana/grafana/issues/25067)

Running containers from Docker hub Grafana public repository on Docker Desktop on MacOS

**Comment by marefr** [comment] 2021-03-10 11:08
Duplicate of #27224

**Closed** 2021-03-10 11:08 UTC
Labels: datasource/MSSQL, needs investigation, type/bug
