### ISSUE TITLE
Logs: Adjust documentation for unified labels/detected-fields

### ISSUE THREAD

**Issue by svennergr** [grafana/grafana#61026] opened 2023-01-05 10:25 UTC
We need to change [documentation](https://grafana.com/docs/grafana/latest/explore/logs-integration/) after https://github.com/grafana/grafana/issues/30221 is finished.

**Comment by gabor** [comment] 2023-01-13 10:11
is https://github.com/grafana/grafana/issues/61215 a duplicate of this?

**Comment by svennergr** [comment] 2023-01-13 10:15
> is https://github.com/grafana/grafana/issues/61215 a duplicate of this?

at least https://grafana.com/docs/grafana/latest/explore/logs-integration/#toggle-detected-fields is solved by this. live tailing isn't. I will adjust #61215

**Closed** 2023-01-20 09:16 UTC
Labels: type/docs, area/logs
