### ISSUE TITLE
CloudWatch dimension_values doesn't support tag filtering

### ISSUE THREAD

**Issue by bendem** [grafana/grafana#13643] opened 2018-10-12 09:02 UTC
### What Grafana version are you using?
5.3.0

### What datasource are you using?
CloudWatch

### What OS are you running grafana on?
docker

### What did you do?
Tried creating a query variable for a dashboard to get a scaling group name from an elastic beanstalk env

### What was the expected result?
Get the autoscaling group name

### What happened instead?
If the query syntax is invalid:
> Templating
> Template variables could not be initialized: Cannot read property 'inputEdges' of undefined

If the query is valid:
> Templating
> Template variables could not be initialized: e.replace is not a function

The filtering works fine with `ec2_instance_attribute`, not with `dimension_values`.
```js
// that works
ec2_instance_attribute(eu-west-1,
    InstanceId,
    { "tag:elasticbeanstalk:environment-name": [ "$env" ] })
```

### If related to metric query / data viz:
```js
dimension_values(eu-west-1, 
    AWS/EC2, 
    CPUUtilization, 
    AutoScalingGroupName, 
    { "tag:elasticbeanstalk:environment-name": [ "$env" ] })
```

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 No outbound request, not console error. The error is catched and displayed, but I can't find the source of the popup.

**Comment by peterj16** [comment] 2018-10-12 10:01
This is a paricularly big problem for me as well:
The query language can only filter based on dimensions. These are instance-id...
Therefore we define variables like $mainapplication which selects all instance-ids filtered based on tags for all ec2 instances running mainapplication.
This works perfectly fine in dashboards, but I cannot define alerts, since alerts do not allow variables.
We would therefore need to be able to filter based on tags in the queries themselves.

**Comment by marefr** [comment] 2018-10-12 10:54
> Templating
> Template variables could not be initialized: Cannot read property 'inputEdges' of undefined

This is duplicate of reported problem in #13628

**Comment by bendem** [comment] 2018-10-12 11:28
It is related but it isn't the same problem. The inputEdges problem happens in many cases but it isn't generally blocking. The query is still executed correctly. The e.replace problem is blocking because the filtering doesn't work at all.

**Comment by mtanda** [comment] 2018-10-25 03:58
It is not easy.
`dimension_values` return `AutoScalingGroupName` dimension value by calling `cloudwatch:ListMetrics`.
And to get AutoScalingGroup tags, Grafana need to call `autoscaling:DescribeTags`. It is new API, Grafana didn't use.

I think supporting tag filtering is quite complicated, and not maintainable.

I suggest to create API Gateway which returns filtered result for simple-json-datasource.

API Gateway support private API, it is only callable from VPC, it is safe.
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html

simple-json-datasource support templating.
https://github.com/grafana/simple-json-datasource

**Comment by mtanda** [comment] 2018-10-25 04:01
@marefr I never try to support this type feature, because such requirement is exists in many resource type like RDS, Elasticache, DynamoDB, ...

And there is workaround, user can create what they need by using API Gateway.

**Comment by bendem** [comment] 2018-10-25 11:58
Note that it the error happens **before** the request is sent to AWS. It's a bug in the query parsing code I'm guessing. And that probably ought to be fixed whether the actual filtering on tags is implemented or not.

**Comment by marefr** [comment] 2018-10-29 12:05
@mtanda okay thanks for the clarification. Please let me know if we should close this issue since there are no easy solution and you've provided good workarounds.

**Comment by mtanda** [comment] 2018-10-29 14:17
No need to close feature request. Just remove `help wanted` is enough because it is difficult to implement.

**Comment by mtanda** [comment] 2019-02-07 02:56
https://github.com/grafana/grafana/pull/14803 will solve this issue.
If `Resource Groups Tagging API` support autoscaling group, user can filter autoscaling group name by tag.
https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html

**Comment by marefr** [comment] 2019-02-07 08:46
@mtanda so we can close this now?

**Comment by mtanda** [comment] 2019-02-07 16:27
@marefr The original issue is, getting the autoscaling group name by tag filtering.
It is not solved yet, but if AWS enhance `Resource Group Tagging API`, it will be solved.
So, I think we can close this issue.

**Comment by marefr** [comment] 2019-02-07 17:03
@mtanda sounds good. Thanks!

**Closed by marefr** 2019-02-07 17:03 UTC
Labels: datasource: CloudWatch, type: feature request
