### ISSUE TITLE
Building 3.0 on Raspberry Pi armv6

### ISSUE THREAD

**Issue by Vebryn** [grafana/grafana#3994] opened 2016-02-10 23:03 UTC
Hi,

I try to build grafana frontend, I got these warning message on grunt execution :

> public/app/app.ts(76,5): error TS2304: Cannot find name 'Promise'.
> public/app/core/directives/plugin_component.ts(66,28): error TS2304: Cannot find name 'Promise'.
> public/app/core/utils/css_loader.ts(29,14): error TS2304: Cannot find name 'Promise'.
> public/app/features/panel/panel_editor_tab.ts(20,14): error TS2304: Cannot find name 'Promise'.
> public/app/headers/common.d.ts(1,1): error TS6053: File 'public/vendor/npm/angular2/typings/tsd.d.ts' not found.
> public/app/headers/common.d.ts(2,1): error TS6053: File 'public/vendor/npm/angular2/manual_typings/globals.d.ts' not found.
> Warning: Task "typescript:build" failed. Use --force to continue.
> Aborted due to warnings.

I can force execution but Firefox Console reports error related to promise absence.

Any idea ? Backend and other steps are successful.

PS :
* phantomjs 1.9.8
* node 0.12.6
* npm 2.11.2
* go 1.5

Best regards,

**Comment by utkarshcmu** [comment] 2016-02-10 23:28
Looks like angularJS errors....Check angularJS dependency :)

**Comment by torkelo** [comment] 2016-02-12 09:00
this has been fixed in https://github.com/grafana/grafana/commit/f797b19825bdb99570e6b2a98d48ff439bf8731a  (caused by a npm postinstall script that for some failed due to permission issue)

**Closed by torkelo** 2016-02-12 09:00 UTC

**Comment by Vebryn** [comment] 2016-02-12 18:01
I temporarily use --unperm npm parameter, thank you!
