### ISSUE TITLE
State timeline displays persistent state when a series returns one data value

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#46762] opened 2022-03-19 19:33 UTC
**What happened**:

I use the State Timeline panel to display Prometheus `ALERTS` metrics. Since around Grafana v8.3 (not certain of the exact version), series that have only one value are shown as a state that is persisted until the end of the graph.

![Screenshot 2022-03-19 15-21-11 alerts noise](https://user-images.githubusercontent.com/3270755/159135618-c0195055-976f-4ec2-bab6-77fa43a87f4d.png)

**What you expected to happen**:

Series that return only one point should be displayed for the duration of one interval, and disappear the next interval.

**How to reproduce it (as minimally and precisely as possible)**:

You can use this dashboard:
[2022-03-19 State timeline bug report-1647717597106.zip](https://github.com/grafana/grafana/files/8309964/2022-03-19.State.timeline.bug.report-1647717597106.zip)

It has one panel, uses the TestData DB data source with a Raw Frame like this:

```
[
  {
    "schema": {
      "name": "CanaryAlert",
      "refId": "A",
      "meta": {
        "custom": {
          "resultType": "matrix"
        }
      },
      "fields": [
        {
          "name": "Time",
          "type": "time",
          "typeInfo": {
            "frame": "time.Time"
          },
          "config": {
            "interval": 15000
          }
        },
        {
          "name": "Value",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          },
          "labels": {
            "alertname": "CanaryAlert",
            "owner": "all"
          },
          "config": {
            "displayNameFromDS": "CanaryAlert"
          }
        }
      ]
    },
    "data": {
      "values": [
        [
          1647703185000
        ],
        [
          2
        ]
      ]
    }
  }
]
```

![Screenshot 2022-03-19 15-29-36 state timeline bug report](https://user-images.githubusercontent.com/3270755/159135663-faf8e9ed-fce3-4461-bd49-6a66954f6cf3.png)

**Anything else we need to know?**:

I tried the "Outer Join"  transformation and it didn't help.

**Environment**:
- Grafana version: v8.4.4
- Data source type & version: Prometheus v2.33.4
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu 20.04, Firefox 98.0.1
- Grafana plugins:
- Others:

**Comment by muffl0n** [comment] 2022-04-06 09:35
I have the same problem, though my datasource returns more than one value:

https://user-images.githubusercontent.com/927904/161945330-45c9b9f7-e2b8-417f-a9d2-7a691cd05a75.mov

I just upgraded from 8.3.4 to 8.4.2 and I'm absolutely sure that it worked before.

**Comment by muffl0n** [comment] 2022-04-06 09:45
I verified: It's broken since 8.4.0.

**Comment by leeoniya** [comment] 2022-04-06 10:23
i think the one-value thing is a duplicate of an issue i fixed two days ago: #46805.

closing this as fixed, thanks!

**Closed by leeoniya** 2022-04-06 10:23 UTC
Labels: type/bug, area/panel/state-timeline

**Comment by curusarn** [comment] 2022-08-12 09:22
I still experience this issue in v8.5.9

**Comment by ChrisKoh83** [comment] 2023-11-23 07:51
I also have the issue on Grafana v9.5.13 (802385ecac)
