### ISSUE TITLE
Use @prometheus-io/lezer-promql instead of lezer-promql since it is deprecated

### ISSUE THREAD

**Issue by itsmylife** [grafana/grafana#53290] opened 2022-08-04 10:54 UTC
We should update [lezer-promql](https://github.com/prometheus/lezer-promql) package since it is deprecated:
See: https://github.com/prometheus/lezer-promql/blob/main/README.md#status

There is an effort about making this happen:
https://github.com/grafana/grafana/pull/50866

But this PR is very old and has many conflicts. Also contains some issues related to types and unit tests.
We can use the code introduced in https://github.com/grafana/grafana/pull/50866 and update it.

**Comment by evandandrea** [comment] 2022-08-08 13:26
- Updated the types which will make this upgrade easier.
- If anyone wants to take this, please ignore that Ismail has this assigned. Ismail is focused on release management this week.
- Galen is picking this up. He's already been in this code.

**Comment by gtk-grafana** [comment] 2022-08-09 19:19
Duplicate of #50866 ?

**Closed** 2022-08-09 19:19 UTC
Labels: datasource/Prometheus
