### ISSUE TITLE
Grafana reads a float Value as int

### ISSUE THREAD

**Issue by bpetrickX** [grafana/grafana#46793] opened 2022-03-21 15:25 UTC
**What happened**:
A bug that occurred a couple of months ago, returned in between to normal and is now back: Float ('java.lang.Float' or 'java.lang.Double') values of an Elasticsearch database are interpreted as integer values.
e.g. a 16.936 is displayed as 16
reading the Value from the Database gets the desired float value. 

The only link I was able to find is from reading the query inspector*. The following two values follow another. All previous values are interpreted falsely as integer, all following correctly as float: 
key_as_string:"epoch_millis1646092785000"
key:1646092785000
value = 16

key_as_string:"1646092815000"
key:1646092815000
value:16.412999749999997

![grafik](https://user-images.githubusercontent.com/68113853/159299654-cb9893e3-c663-40fb-9934-7b5a755ff78b.png)

why is there the "epoch_millis" in the key_as_string? why should that have anything to do with the value?

*path in inspector:
responses:Array[1]
0:Object
aggregations:Object
2:Object
buckets:Array[296]

**How to reproduce it (as minimally and precisely as possible)**:
Haven't been able to reproduce. Apart from the "epoch_millis" in "key_as_string:"

**Anything else we need to know?**:

**Environment**:
- Grafana version: doesn't matter I tried 6.2 with Elasticsearch 5.6, Updated to Grafana 8.4.4, and additional the latest Grafana Version with Elasticsearch 7.12
- Data source type & version:
- OS Grafana is installed on: Docker grafana/grafana:latest 
- User OS & Browser: Firefox 98.0.1
- Grafana plugins: none

**Comment by zuchka** [comment] 2022-03-23 21:00
Thanks for creating this issue, @bpetrickX 

can you think of any way for the teams to reliably reproduce this issue?

**Comment by zuchka** [comment] 2022-03-28 18:43
please do let us know, @bpetrickX. And thank you again for working with us on this.

in the meantime, I think I will close this issue since, for now, Grafana appears to be working as intended 👍

**Closed by zuchka** 2022-03-28 18:43 UTC
Labels: needs more info
