### ISSUE TITLE
Cloudwatch: Add back support for importing dashboards across aws accounts

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#79318] opened 2023-12-11 14:15 UTC
When we added our new cross-account observability feature we accidentally caused a breaking change for customers who had this use case:
- have multiple aws accounts that all have the same cloudwatch logs group names
- create one dashboard that can be imported and used across different grafana cloudwatch datasource plugin instances. 

This previously worked so long as the log group names were the same across different accounts.

This then broke when we added a feature to access different aws accounts from the same grafana instance with aws's cross-account observability feature because we now access cloudwatch log groups by ARN not by log group names. Because we were unaware of this poorly documented feature, this caused an unintended breaking change for some customers. 

There are a few possible approaches we could take to support this and it needs further research, but we should not deprecate the `cloudWatchCrossAccountQuerying` until we have figured out a way to support this.

**Comment by katebrenner** [comment] 2024-02-28 15:32
closing as duplicate of https://github.com/grafana/grafana/issues/74627

**Closed by katebrenner** 2024-02-28 15:32 UTC
Labels: internal
