### ISSUE TITLE
MariaDB $__timeGroup problem with Epoch format

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#13381] opened 2018-09-21 09:45 UTC
### What Grafana version are you using?
v5.2.4 (commit: 0bbac5c)

### What datasource are you using?
MariaDB 10.1.8

The `$__timeGroup` macro doesn't work with Epoch time format.

The database sample:

~~~
start		sec
1537479569	66
1537479756	47
1537479936	58
~~~

The query:

~~~
SELECT
  $__timeGroup(start, '1m', 0) AS time_sec,
  'sec' AS metric,
  sec AS value
FROM publish
WHERE $__unixEpochFilter(start)
AND type = '3MIN'
GROUP BY time_sec
ORDER BY time_sec ASC
~~~

The error message:

~~~
Invalid type for column time/time_sec, must be of type timestamp or unix timestamp, got: <nil> <nil>
~~~

example with filter:
![20180921110913](https://user-images.githubusercontent.com/2911588/45873896-cbb0bd80-bd93-11e8-9a2f-f56527b73c68.png)

example without filter:
![20180921110953](https://user-images.githubusercontent.com/2911588/45873897-cbb0bd80-bd93-11e8-83d9-b1e707a93db9.png)

**Comment by marefr** [comment] 2018-09-21 11:11
Duplicate of #12892

**Comment by marefr** [comment] 2018-09-21 11:11
Feature will be included in Grafana v5.3 stable

**Closed by marefr** 2018-09-21 11:11 UTC

**Comment by sanchomuzax** [comment] 2018-10-11 12:48
I installed v5.3.0 stable version, but this error persists. 😞

**Comment by marefr** [comment] 2018-10-11 13:00
@sanchomuzax please try the new macro called `$__unixEpochGroup`, see [documentation](http://docs.grafana.org/features/datasources/mysql/#macros).

**Comment by sanchomuzax** [comment] 2018-10-17 05:05
Working, thank you!
