### ISSUE TITLE
alerting queries the wrong datasource

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#7683] opened 2017-02-28 08:36 UTC
Some history:
- we used to have a raintankPOC datasource
- it was renamed to raintankPOC-old, and a new raintankPOC datasource was created.
- (probably on an older version of grafana, but 4-ish)
- we have alerting rules pointed to raintankPOC

what we found out now, using Grafana v4.1.1 (commit: v4.1.1) at raintank, is that changing raintankPOC-old broke a bunch of alerts that are set to query raintankPOC as datasource.
So it looks like these alerts still query raintankPOC-old instead of raintankPOC.

**Comment by torkelo** [comment] 2017-02-28 09:05
yes, alerts are targeting data source by ids, so if you just changed name the alert rules will still use the same data source. 

Data source renaming is a big problem in grafana as panels refer to them by id (which is a legacy from pre Grafana 2.x where data sources where specified in config.js).

Very time consuming to solve this properly as it requires long running jobs update references in dashboard json models and in tern in alert models.

**Comment by bergquist** [comment] 2017-02-28 14:18
I think this is just something we have to fix in the grafana dashboards. referring to datasources in different was is very annoying and confusing for the user. 

This requires to much internal knowledge about grafana to figure this out.

**Comment by torkelo** [comment] 2017-02-28 14:44
yea, agree. Wonder how fix it though.

**Comment by torkelo** [comment] 2020-11-10 15:04
duplicate of https://github.com/grafana/grafana/issues/1664

**Closed by torkelo** 2020-11-10 15:04 UTC
Labels: area/alerting, priority/important-longterm, type/bug
