### ISSUE TITLE
Add up/down arrows on Transforms in Panel Editor

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#26971] opened 2020-08-12 19:46 UTC
**What would you like to be added**:
In Transform tab in Panel editor: add up/down buttons to allow re-ordering of transforms.

**Why this might be difficult/unworkable?**
There may be technical or logical issue with this idea: i.e., when you create a transform, it needs to check what series are available, including series created by previous transforms. If you change the order of the transforms, it may make some transforms invalid because they refer to series that are not created yet (i.e., created by a transform that now falls below it in the sequence of transforms). Thus any solution for this request would have to check transforms for such logic issues before allowing a transform to be moved up (or down?) in the sequence of transforms.

**Why is this needed**:
Per customer:

> I had created two transforms, organized them to hide the source data, then realized I wanted to create 2 more transforms. I created the two transforms, but when I went back to the Organize fields tool to hide my source data, my two transforms weren't present. I had to delete out the organize tools and add it to the bottom of my transforms.
> Is there any way we could get the up and down arrows to move the order of transforms the way you can move the order of queries? If the transforms are dependent on each other in a specific order, flexibility to customize this order would be appreciated.

**Comment by torkelo** [comment] 2020-08-13 06:14
duplicate of https://github.com/grafana/grafana/issues/25482

**Closed by torkelo** 2020-08-13 06:14 UTC
