### ISSUE TITLE
After last update,  datepicker doesn't run and there are lots of angular errors on console

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#3589] opened 2015-12-23 10:46 UTC
When trying to test the last master version 

when trying to open datepicker , the button does'nt work

![image](https://cloud.githubusercontent.com/assets/5883405/11975093/72f6ffd2-a96a-11e5-83ca-112cded19dd9.png)

we can see also  lots of console errors.

![image](https://cloud.githubusercontent.com/assets/5883405/11975076/4791bc2e-a96a-11e5-8c3a-7980298db25b.png)

How can I fix that?

**Comment by utkarshcmu** [comment] 2015-12-23 10:52
Works for me here.... Have u tried running the following commands and then restarting Grafana server using "$GRAFANA_HOME/bin/grafana-server

1. "grunt test"
2. "go run build.go build"

**Comment by toni-moreno** [comment] 2015-12-23 11:09
I'm working with bra , I did.
```
# grunt
# $GOPATH/bin/godep restore
# bra run
```
But after doing as you said , 

```` 
[root@grafanalab01 grafana]# go run build.go build
Version: 3.0.0-pre1, Linux Version: 3.0.0, Package Iteration: pre1
rm -r bin
rm -r Godeps/_workspace/pkg
rm -r Godeps/_workspace/bin
rm -r dist
rm -r tmp
rm -r /root/grafana-lab/pkg/linux_amd64/github.com/grafana
rm -r ./bin/grafana-server
rm -r ./bin/grafana-server.md5
GOPATH=/root/grafana-lab/src/github.com/grafana/grafana/Godeps/_workspace:/root/grafana-lab
go version
go version go1.5.1 linux/amd64
go build -ldflags -w -X main.version=3.0.0-pre1 -X main.commit=v2.6.0+173-gf074c1e -X main.buildstamp=1450789151 -o ./bin/grafana-server .
[root@grafanalab01 grafana]# bin
bin/  bind
[root@grafanalab01 grafana]# bin/grafana-server
2015/12/23 11:58:39 [I] Starting Grafana
2015/12/23 11:58:39 [I] Version: 3.0.0-pre1, Commit: v2.6.0+173-gf074c1e, Build date: 2015-12-22 13:59:11 +0100 CET
2015/12/23 11:58:39 [I] Configuration Info
Config files:
  [0]: /root/grafana-lab/src/github.com/grafana/grafana/conf/defaults.ini
Paths:
  home: /root/grafana-lab/src/github.com/grafana/grafana
  data: /root/grafana-lab/src/github.com/grafana/grafana/data
  logs: /root/grafana-lab/src/github.com/grafana/grafana/data/log
  plugins: data/plugins

2015/12/23 11:58:39 [I] Database: sqlite3
2015/12/23 11:58:39 [I] Migrator: Starting DB migration
2015/12/23 11:58:39 [I] Listen: http://0.0.0.0:3000
```
Errors persist for me, even when rendering seems to be working

![image](https://cloud.githubusercontent.com/assets/5883405/11975423/ef256f5a-a96d-11e5-9792-be70adfd9694.png)


![image](https://cloud.githubusercontent.com/assets/5883405/11975379/83955566-a96d-11e5-8d4c-ef3237712d59.png)

**Comment by toni-moreno** [comment] 2015-12-23 11:48
hi @utkarshcmu can you see in your browser debugger the path where grafana are loading static files please? Should be loaded static files from /public/ or /public_gen/ when working with bra?

**Comment by toni-moreno** [comment] 2015-12-23 13:01
Hi @torkelo , @bergquist , @utkarshcmu 
 I've downgraded my local master branch  to a previous commit (e29e3416dbeb9fdcb6ec433ef5982cee107d4fb4) ( from Thu Dec 17 14:28:11 2015 +0100)
```
# git checkout e29e3416dbeb9fdcb6ec433ef5982cee107d4fb4
```

With this version all is working fine to me , datepicker working ok

![image](https://cloud.githubusercontent.com/assets/5883405/11976868/c56c68d0-a97c-11e5-8fdb-31209f465d21.png)

And there aren't  errors on the browser console.

What am I doing wrong?

**Comment by utkarshcmu** [comment] 2015-12-23 14:19
I am not able to reproduce these console errors. Try clearing your browser cache may be.

**Comment by toni-moreno** [comment] 2015-12-23 14:36
I've loaded grafana with Firefox ( for the first time in this computer), and here we can see even more errors ,  datepicker doesn't work.

![image](https://cloud.githubusercontent.com/assets/5883405/11978248/44f86d3a-a98a-11e5-9536-9dd96c4ca97a.png)

And a lot of "ReferenceError"

![image](https://cloud.githubusercontent.com/assets/5883405/11978257/551a68ee-a98a-11e5-85c2-0ff0aff7b8ec.png)

**Comment by torkelo** [comment] 2015-12-23 16:25
Could  be due switch from requirejs to systemjs, I am on holiday for 2 weeks to might be some time until I can investigate this :(

**Comment by toni-moreno** [comment] 2015-12-23 21:20
no problem @torkelo enjoy your holidays we will fix this and a lot of other things next year !!

Merry Christmas and a happy New Year! !

**Comment by torkelo** [comment] 2015-12-24 07:36
Thanks :)

Merry Christmas!

**Comment by torkelo** [comment] 2016-01-07 19:53
fixed in https://github.com/grafana/grafana/commit/52644bb28a59974b4f71ba4502be0ff3fadebf4a

**Closed by torkelo** 2016-01-07 19:53 UTC
