### ISSUE TITLE
Prompt: "Open xdg-open?" for pinned tabs in Google Chrome 

### ISSUE THREAD

**Issue by dmke** [grafana/grafana#12226] opened 2018-06-11 08:51 UTC
*Note: This is not a blocker, but increasingly annoying.*

### What Grafana version are you using?

Grafana v5.1.3 (087143285)

As far as I can remember, this issue wasn't present in 4.x. I don't know when exactly this started, though.

### What datasource are you using?

InfluxDB, but I don't believe this is relevant.

### What OS are you running grafana on?

Ubuntu 16.04.4 LTS (same here, I don't think this is relevant).

The client OS is a Debian 9.4 (Stretch, stable), with Google Chrome 68.0.3440.17 (official beta, but it happens with v67 stable as well).

### What did you do?

I have two pinned tabs in Google Chrome (latest version), for two dashboards (of different organizations). When I start the browser, and switch to the pinned tabs, *sometimes* I get directly greeted with an "Open xdg-open?" prompt. Some other times, the page is empty, showing only the Grafana-gray background and the dashboard's header bar; only after hitting F5 (or Ctrl+F5), the prompt appears. Most of the time (I'd say 75%), I don't get a prompt at all.

![image](https://user-images.githubusercontent.com/327411/41221416-60166f04-6d64-11e8-9920-b5ac28c3fb83.png)

### What was the expected result?

Not show the prompt.

### What happened instead?

Clicking on "Open xdg-open" does not do anything. Neither does the dashboard (re)load, nor is any process executed (as far as I can tell). Only the prompt disappears, I still need to hit refresh to load the dashboard.

**Comment by daniellee** [comment] 2018-06-11 09:03
I tested a few times with one pinned tab and didn't get this problem. Could it be something to do with have pinned tabs for two organizations. If you test with with just one pinned tab, do you still get the xdg-open popup?

**Comment by dmke** [comment] 2018-06-11 09:30
It only happens with two (or possibly more) tabs for different organizations.

The seemingly random behaviour also suggest something session/cookie-related.

**Comment by marefr** [comment] 2018-06-12 08:14
xdg-open seems to be linux specific, https://linux.die.net/man/1/xdg-open. Closing this as it seems to be related to something running on your computer. Will consider reopen if you think this still is a Grafana issue.

**Closed by marefr** 2018-06-12 08:14 UTC
Labels: state: needs more detail

**Comment by marefr** [comment] 2018-06-12 08:40
So what happens when you click *Open xdg-open*? Feels like you have some strange file association/app settings on your computer?

**Comment by dmke** [comment] 2018-06-12 08:52
Nothing obvious happens (but let me hook up `strace` in a moment).

I am also not aware of strange MIME associations on this machine (it is however a devops machine, so who knows which tool might have injected an unwanted association).

**Comment by dmke** [comment] 2018-06-12 09:17
The `--verbose` log of Chrome shows this line after clicking on *Open xdg-open* (I've replaced the hostname of our Grafana instance with [REDACTED]):

```
gvfs-open: sockets://[REDACTED]/d/000000003/traffic-clients?orgId=2&refresh=5m: error opening location: The specified location is not supported
```

In the trace log, this is the corresponding line:

```
[pid 10814] execve("/home/dm/code/admin/ansible-src/bin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/home/dm/code/admin/ansible-src/test/runner/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/home/dm/.rbenv/shims/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/home/dm/code/go/bin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/home/dm/.local/go/bin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/home/dm/.rbenv/bin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/sbin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/usr/sbin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/home/dm/bin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/usr/local/bin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = -1 ENOENT (No such file or directory)
[pid 10814] execve("/usr/bin/xdg-open", ["xdg-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = 0
[...]
[pid 10818] execve("/usr/bin/gvfs-open", ["gvfs-open", "sockets://[REDACTED]/d/0"...], [/* 68 vars */]) = 0
```

`/usr/bin/xdg-open` is a shell script ([gist](https://gist.github.com/dmke/022476afa90b0b8349f2922fb26ea959)), which delegates to the Desktop Environment's XDG implementation (`/usr/bin/gvfs-open` for Gnome 3 in my case).

Any idea, where the `sockets://` URI is cobbled together?

**Comment by relishcolouredhat** [comment] 2018-06-13 02:03
I get 'xdg-open' popups on my xfce ubuntu machine any time I'm directed towards a URI that is not handled by anything else. (including 'sockets://') 

I haven't run into this yet (only using one org), but just intended to add a vote that while being related to odd MIME extensions, I have always seen the error in the context of the opposite - trying to follow hooks for an oddball extension. (we inherited some interesting links like sw:// and script:// in my environment...)

**Comment by ajaykpaul** [comment] 2019-10-16 11:17
It is a valid issue. Even I am able to reproduce it in my Fedora 30
