### ISSUE TITLE
Failed to look up user based on cookie

### ISSUE THREAD

**Issue by icepopfh** [grafana/grafana#32964] opened 2021-04-14 02:46 UTC
**What happened**:
My Grafana panel will exit automatically if opened for a long time. When I check the log, I find that the user token is not found, please help to check it.
![image](https://user-images.githubusercontent.com/53719692/114643799-ee67a080-9d08-11eb-8d9a-2c680ee9e661.png)

**What you expected to happen**:
I wish I could always keep my monitor panel, for example:
![image](https://user-images.githubusercontent.com/53719692/114644000-49999300-9d09-11eb-8f7a-dd4c0cf2debf.png)

**How to reproduce it (as minimally and precisely as possible)**:
You can reproduce it by holding a panel open for about three days.

**Anything else we need to know?**:
I deployed through Docker and the deployment command is "docker run -e "GF_SECURITY_ADMIN_PASSWORD=******" -itd -p 3000:3000 --name grafana -v /etc/localtime:/etc/localtime:ro -v /data/monitor/grafana/data:/var/lib/grafana -v /data/monitor/grafana/conf:/usr/share/grafana/conf --privileged=true --restart=always grafana:7.0.4".

Defaults.ini file contents:
app_mode = production
instance_name = ${HOSTNAME}
[paths]
data = data
temp_data_lifetime = 24h
logs = data/log
plugins = data/plugins
provisioning = conf/provisioning
[server]
protocol = http
http_port = 3000
domain = localhost
enforce_domain = false
root_url = %(protocol)s://%(domain)s:%(http_port)s/
serve_from_sub_path = false
router_logging = false
static_root_path = public
enable_gzip = false
socket = /tmp/grafana.sock
[database]
type = sqlite3
host = 127.0.0.1:3306
name = grafana
user = root
max_idle_conn = 2
conn_max_lifetime = 14400
ssl_mode = disable
path = grafana.db
cache_mode = private
[remote_cache]
type = database
[dataproxy]
logging = false
timeout = 30
send_user_header = false
[analytics]
reporting_enabled = true
check_for_updates = true
[security]
disable_initial_admin_creation = false
admin_user = admin
admin_password = admin
secret_key = SW2YcwTIb9zpOOhoPsMm
disable_gravatar = false
disable_brute_force_login_protection = false
cookie_secure = false
cookie_samesite = lax
allow_embedding = true
strict_transport_security = false
strict_transport_security_max_age_seconds = 86400
strict_transport_security_preload = false
strict_transport_security_subdomains = false
x_content_type_options = false
x_xss_protection = false
[snapshots]
external_enabled = true
external_snapshot_url = https://snapshots-origin.raintank.io
external_snapshot_name = Publish to snapshot.raintank.io
public_mode = false
snapshot_remove_expired = true
[dashboards]
versions_to_keep = 20
min_refresh_interval = 5s
[users]
allow_sign_up = true
allow_org_create = false
auto_assign_org = true
auto_assign_org_id = 1
auto_assign_org_role = Viewer
verify_email_enabled = false
login_hint = email or username
password_hint = password
default_theme = dark
viewers_can_edit = false
editors_can_admin = false
[auth]
login_cookie_name = grafana_session
login_maximum_inactive_lifetime_days = 7
login_maximum_lifetime_days = 999
token_rotation_interval_minutes = 262800
disable_login_form = false
disable_signout_menu = false
oauth_auto_login = false
oauth_state_cookie_max_age = 60
api_key_max_seconds_to_live = -1
[auth.anonymous]
enabled = false
org_name = Main Org.
org_role = Viewer
[auth.github]
enabled = false
allow_sign_up = true
client_id = some_id
client_secret = some_secret
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
[auth.gitlab]
enabled = false
allow_sign_up = true
client_id = some_id
client_secret = some_secret
scopes = api
auth_url = https://gitlab.com/oauth/authorize
token_url = https://gitlab.com/oauth/token
api_url = https://gitlab.com/api/v4
[auth.google]
enabled = false
allow_sign_up = true
client_id = some_client_id
client_secret = some_client_secret
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
api_url = https://www.googleapis.com/oauth2/v1/userinfo
[auth.grafananet]
enabled = false
allow_sign_up = true
client_id = some_id
client_secret = some_secret
scopes = user:email
[auth.grafana_com]
enabled = false
allow_sign_up = true
client_id = some_id
client_secret = some_secret
scopes = user:email
[auth.azuread]
name = Azure AD
enabled = false
allow_sign_up = true
client_id = some_client_id
client_secret = some_client_secret
scopes = openid email profile
auth_url = https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token
[auth.okta]
name = Okta
enabled = false
allow_sign_up = true
client_id = some_id
client_secret = some_secret
scopes = openid profile email groups
auth_url = https://<tenant-id>.okta.com/oauth2/v1/authorize
token_url = https://<tenant-id>.okta.com/oauth2/v1/token
api_url = https://<tenant-id>.okta.com/oauth2/v1/userinfo
[auth.generic_oauth]
name = OAuth
enabled = false
allow_sign_up = true
client_id = some_id
client_secret = some_secret
scopes = user:email
email_attribute_name = email:primary
tls_skip_verify_insecure = false
[auth.basic]
enabled = true
[auth.proxy]
enabled = false
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
ldap_sync_ttl = 60
sync_ttl = 60
enable_login_token = false
[auth.ldap]
enabled = false
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
sync_cron = "0 0 1 * * *"
active_sync_enabled = true
[smtp]
enabled = false
host = localhost:25
skip_verify = false
from_address = admin@grafana.localhost
from_name = Grafana
[emails]
welcome_email_on_sign_up = false
templates_pattern = emails/*.html
[log]
mode = console file
level = debug
filters = auth:debug
[log.console]
format = console
[log.file]
format = text
log_rotate = true
max_lines = 1000000
max_size_shift = 28
daily_rotate = true
max_days = 7
[log.syslog]
format = text
[quota]
enabled = false
org_user = 10
org_dashboard = 100
org_data_source = 10
org_api_key = 10
user_org = 10
global_user = -1
global_org = -1
global_dashboard = -1
global_api_key = -1
global_session = -1
[alerting]
enabled = true
execute_alerts = true
error_or_timeout = alerting
nodata_or_nullvalues = no_data
concurrent_render_limit = 5
evaluation_timeout_seconds = 30
notification_timeout_seconds = 30
max_attempts = 3
min_interval_seconds = 1
[explore]
enabled = true
[metrics]
enabled              = true
interval_seconds     = 10
disable_total_stats = false
[metrics.graphite]
prefix = prod.grafana.%(instance_name)s.
[grafana_net]
url = https://grafana.com
[grafana_com]
url = https://grafana.com
[tracing.jaeger]
sampler_type = const
sampler_param = 1
zipkin_propagation = false
disable_shared_zipkin_spans = false
[rendering]
concurrent_render_request_limit = 30
[panels]
enable_alpha = false
disable_sanitize_html = false
[plugins]
enable_alpha = false
app_tls_skip_verify_insecure = false

**Environment**:
- Grafana version:7.0.4
- Data source type & version: prometheus:2.19.1
- OS Grafana is installed on: CentOS 7.7.1908(docker)
![image](https://user-images.githubusercontent.com/53719692/114646009-0a6d4100-9d0d-11eb-92a6-79ff350308bf.png)
- User OS & Browser: Windows 10 Home Edition is 64-bit & Google Chrome 89.0
- Grafana plugins: Polystat V1.2.0 & Pie Chart V1.6.0 & FlowCharting V0.9.0 & briangann-datatable V1.0.3 & yesoreyeram-boomtable V1.4.0 & fifemon-graphql-datasource V1.3.0 & gapit-htmlgraphics V1.2.0
- Others: None

**Comment by marefr** [comment] 2021-04-14 08:01
Duplicate of #15316

**Closed** 2021-04-14 08:01 UTC
Labels: area/backend, area/backend/auth, type/bug
