### ISSUE TITLE
Issue: Table Panel-Raw data - integer 0 is displayed as 00

### ISSUE THREAD

**Issue by pfischer64** [grafana/grafana#29410] opened 2020-11-26 10:18 UTC
When I create a table panel using "Raw data" the integer values of 0 (Data-source is Elasticsearch) are shown as "00" inside the table panel. Values different from 0 or integers as a string (something like"19") are  displayed correct.

![Grafana-7 32_display_issue](https://user-images.githubusercontent.com/43639627/100338145-82460380-2fd8-11eb-937b-7efcc171d770.png)

**Comment by pfischer64** [comment] 2020-11-26 11:07
Seems similar or duplicate to #29394

https://github.com/grafana/grafana/issues/29394

**Comment by torkelo** [comment] 2020-11-26 16:35
duplicate of https://github.com/grafana/grafana/issues/29410

**Closed by torkelo** 2020-11-26 16:35 UTC
