### ISSUE TITLE
 Threshold colors not loading properly

### ISSUE THREAD

**Issue by Amreeshbaskar** [grafana/grafana#47297] opened 2022-04-05 06:31 UTC
**What happened**:
The Bargraph is set up for mysql Table, Threshold color is setup. The color are working properly at the time of dashboard loading and once any  variable changes at dashboard top and bar graph values are changed the threshold colors are not working properly.
The dashboard is setup to reload every 5s. also tried with overide property, same issue exist.

The threshold color setup like this base red,>70 yellow,>90 Green
Graph at time of loading of dashboard
![s1](https://user-images.githubusercontent.com/42416179/161692552-18fb63ab-5568-427d-b656-a34c4a53d427.PNG)

Graph showing incorrect threshold colors when variables and values are changed
![s2](https://user-images.githubusercontent.com/42416179/161692623-08aa2108-4b10-414e-8f6c-10cc54d80dc9.PNG)

**What you expected to happen**:
The threshold color needs to be changed when the values of the graph changes in the dynamic dashboards

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: MySQL 8.0.28
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: Mysql

**Comment by mellieA** [comment] 2022-04-05 20:33
@amreeeshbaskar can you also share the dashboard json so we can see what options are selected for coloring the bars and the graph itself?

I see a similar issue here https://github.com/grafana/grafana/issues/39614 but more information will help us to look further into it.

**Comment by Amreeshbaskar** [comment] 2022-04-06 04:43
{
  "id": 9,
  "gridPos": {
    "h": 12,
    "w": 24,
    "x": 0,
    "y": 13
  },
  "type": "barchart",
  "title": "$Releases",
  "transformations": [
    {
      "id": "organize",
      "options": {
        "excludeByName": {},
        "indexByName": {},
        "renameByName": {
          "pip_url": "Link",
          "pipeline_name": "Pipeline Name",
          "qscore": "Q Score",
          "rcc_id": "RCC",
          "rra_id": "RRA",
          "srs_id": "SRS"
        }
      }
    }
  ],
  "datasource": {
    "type": "mysql",
    "uid": "Mby0QyB7k"
  },
  "pluginVersion": "8.4.1",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 1,
        "fillOpacity": 80,
        "gradientMode": "none",
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisSoftMin": 0,
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        }
      },
      "color": {
        "mode": "thresholds",
        "fixedColor": "orange"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "semi-dark-red",
            "value": null
          },
          {
            "color": "semi-dark-yellow",
            "value": 70
          },
          {
            "color": "semi-dark-green",
            "value": 90
          }
        ]
      },
      "links": [
        {
          "targetBlank": true,
          "title": "",
          "url": "${__data.fields.Link}"
        }
      ],
      "unit": "short"
    },
    "overrides": []
  },
  "options": {
    "orientation": "auto",
    "xTickLabelRotation": 0,
    "xTickLabelSpacing": 0,
    "showValue": "always",
    "stacking": "none",
    "groupWidth": 0.7,
    "barWidth": 0.97,
    "barRadius": 0,
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "displayMode": "hidden",
      "placement": "right",
      "calcs": []
    },
    "colorByField": "qscore",
    "text": {
      "valueSize": 14
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "mysql",
        "uid": "Mby0QyB7k"
      },
      "format": "table",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "select pipeline_name,srs_id,rra_id,rcc_id,qscore,pip_url from jd \nwhere  sno in \n(select max(sno) from jd where srs_tag='$Releases' and hardware like (case when 'All'=$Hardware then '%' else $Hardware end) group by pipeline_name)\norder by pipeline_name;",
      "refId": "A",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "column"
          }
        ]
      ],
      "timeColumn": "time",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    }
  ]
}

**Comment by Amreeshbaskar** [comment] 2022-04-07 11:22
{
  "__inputs": [
    {
      "name": "DS_MYSQL-2",
      "label": "MySQL-2",
      "description": "",
      "type": "datasource",
      "pluginId": "mysql",
      "pluginName": "MySQL"
    }
  ],
  "__elements": [],
  "__requires": [
    {
      "type": "panel",
      "id": "barchart",
      "name": "Bar chart",
      "version": ""
    },
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.4.5"
    },
    {
      "type": "datasource",
      "id": "mysql",
      "name": "MySQL",
      "version": "1.0.0"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1649330492339,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "mysql",
        "uid": "${DS_MYSQL-2}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "axisSoftMin": 0,
            "fillOpacity": 80,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "semi-dark-red",
                "value": null
              },
              {
                "color": "semi-dark-yellow",
                "value": 70
              },
              {
                "color": "semi-dark-green",
                "value": 90
              }
            ]
          },
          "unit": "short"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "colorByField": "value",
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "hidden",
          "placement": "right"
        },
        "orientation": "auto",
        "showValue": "always",
        "stacking": "none",
        "text": {
          "valueSize": 14
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "pluginVersion": "8.4.5",
      "targets": [
        {
          "datasource": {
            "type": "mysql",
            "uid": "${DS_MYSQL-2}"
          },
          "format": "table",
          "group": [],
          "metricColumn": "none",
          "rawQuery": true,
          "rawSql": "select * from sample where f1='$f1';",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "column"
              }
            ]
          ],
          "timeColumn": "time",
          "where": [
            {
              "name": "$__timeFilter",
              "params": [],
              "type": "macro"
            }
          ]
        }
      ],
      "title": "Panel Title",
      "type": "barchart"
    }
  ],
  "schemaVersion": 35,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {},
        "datasource": {
          "type": "mysql",
          "uid": "${DS_MYSQL-2}"
        },
        "definition": "select f1 from sample;",
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "f1",
        "options": [],
        "query": "select f1 from sample;",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "sample2",
  "uid": "D574fMU7k",
  "version": 4,
  "weekStart": ""
}

**Comment by Amreeshbaskar** [comment] 2022-04-07 11:26
![s1](https://user-images.githubusercontent.com/42416179/162188067-168b3079-d23d-4a54-ba60-17ce5d615505.PNG)

At the time of loading color coding is working fine


![s2](https://user-images.githubusercontent.com/42416179/162188151-475b755e-79f8-4502-8941-57a421e08b1c.PNG)
When the variable changes and graph value changes, the threshold is not working properly

**Comment by Amreeshbaskar** [comment] 2022-04-15 10:49
This issue is with barchart only, other things like bar gauge is working fine

**Comment by ErikLambrechts** [comment] 2022-06-15 13:24
I experience the same problem. How could this be solved?

**Comment by AG-AALVES** [comment] 2022-06-17 13:08
Same problem with bargraph on version 8.5.6 and 9.0.0. The color are not updated based on new values, only on dashboard load.

If time range is changed and new values are received, the colors are not updated at all. They are only updated if you enter edit mode and go back for every time you have new values or if use F5 to refresh the entire page.

**Comment by clompsy** [comment] 2022-07-07 12:15
Same here with v8.5.2.
It basically makes the Bar Chart unusable for us since the color misrepresents the value.
Sometimes even small changes are relevant if they move to another treshold, but with an auto-refreshing dashboard the color will be misleading and it's not immediately clear that a treshold is reached.

**Comment by oscarkilhed** [comment] 2022-08-18 06:59
I've looked at this since the merged fix caused a regression.
The issue seems to be that `colorByField` has `values` assigned when the panel loads. Those values are then used in [`getColor`](https://github.com/grafana/grafana/blob/83f8da2e022e4371ac2426326095eb0f36b1ab3c/public/app/plugins/panel/barchart/BarChartPanel.tsx#L229). When the data updates we're still using the values that were assigned when the panel loads.

**Comment by melquelima** [comment] 2022-10-27 21:23
Same here, i have tryed to change the BarChartPanel.tsx file as meioned but no success yet

**Comment by leeoniya** [comment] 2022-11-05 01:47
like https://github.com/grafana/grafana/issues/39614, i cannot reproduce this anymore.

@melquelima if you're still having issues in v9.2.3 (latest release), please open a new issue with your panel config and data, or ideally a debug snapshot:  https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/#panel-help-menu

**Closed by leeoniya** 2022-11-05 01:47 UTC
Labels: needs more info, area/panel/barchart

**Comment by amaresh0612** [comment] 2023-02-06 05:21
This issue is still not resolved and Grafana admins are avoiding the question and closing topics.

**Comment by opensourcefan** [comment] 2023-05-28 22:55
New fresh install, had the same happen but on a line graph.

**Comment by leeoniya** [comment] 2023-05-30 15:14
as i said in the comment above, if this is still an issue, you'll need to give us panel config + data and maybe a screen rec so we can reproduce the issue.

can you reproduce it here?

https://play.grafana.org/d/barchart-thresholds-mappings/barchart-thresholds-and-mappings?orgId=1

**Comment by sxm51** [comment] 2023-06-08 00:15
Here's an example using timeseries panel.

* Edit the following dashboard, panel: https://play.grafana.org/d/timeseries-stacking2/timeseries-and-barchart-stacking?orgId=1&editPanel=7
* Add following thresholds: Green: Base, Red: 15.
* Set `Color scheme` as `From thresholds (by value)`.
<img width="386" alt="Screenshot 2023-06-08 at 10 11 14 am" src="https://github.com/grafana/grafana/assets/106202371/60429fa9-ee93-45cf-aabc-6e2e6d130576">


Result:

Tooltip has the right color but not the timeseries?
<img width="1467" alt="Screenshot 2023-06-08 at 10 11 24 am" src="https://github.com/grafana/grafana/assets/106202371/aa45ecdf-f5ba-41ab-b680-504bd24c93bf">

**Comment by leeoniya** [comment] 2023-06-08 00:20
are you expecting the entire area fill and stroke to turn red or just the hovered point?

**Comment by sxm51** [comment] 2023-06-08 22:36
I was thinking the area above the threshold to turn red in this case.
Having the point alone turn red would be confusing?

**Comment by leeoniya** [comment] 2023-06-08 23:02
that's possible, you just have to set the correct options. try importing this dashboard: https://github.com/grafana/grafana/blob/main/devenv/dev-dashboards/panel-timeseries/timeseries-by-value-color-schemes.json

![image](https://github.com/grafana/grafana/assets/43234/08f33711-e307-47a4-8372-2620cf21aef9)
![image](https://github.com/grafana/grafana/assets/43234/e7711f49-76c7-47bf-a0db-30f239200f70)

**Comment by sxm51** [comment] 2023-06-09 00:35
That works, Thanks for your help.

Just realised its in the docs, but missed it - https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/time-series/#by-value-color-schemes
