### ISSUE TITLE
Navigation: Grafana logo in navbar leads to login when anonymous allowed

### ISSUE THREAD

**Issue by tab0r** [grafana/grafana#59969] opened 2022-12-07 16:27 UTC
**What happened**:
I have local Grafana instances running to allow anonymous admin access for development (with disabled login screen).
When clicking the Grafana log at the top of the navbar, it leads to localhost:3000/login.
This doesn't seem to happen at [wikimedia's public instance](https://grafana.wikimedia.org/d/000000479/cdn-frontend-traffic?orgId=1).

**What you expected to happen**:
Clicking the grafana logo should lead to the home dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Clone Grafana.
Set the following env vars:

```
ENV GF_AUTH_ANONYMOUS_ORG_ROLE "Admin"
ENV GF_AUTH_ANONYMOUS_ENABLED "true"
ENV GF_AUTH_BASIC_ENABLED "false"
ENV GF_AUTH_DISABLE_LOGIN_FORM=true
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version: n/a
- OS Grafana is installed on: Linux/Ubuntu 20.04 LTS
- User OS & Browser: Same, Firefox
- Grafana plugins: n/a
- Others: same results when I run latest docker images as a locally compiled version from code

**Comment by zuchka** [comment] 2022-12-09 18:57
I can confirm that this has changed between 8.5.14 and 9.3.1, but I cannot confirm if it is a bug or is intentional.
https://user-images.githubusercontent.com/37156449/206771572-6bea36e7-6d9f-47fa-a17e-67a0c6337785.mp4

```
  docker run --rm \
    -e GF_LOG_LEVEL=debug \
    -e GF_LOG.CONSOLE_LEVEL=debug \
    -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin \
    -e GF_AUTH_ANONYMOUS_ENABLED=true \
    -e GF_AUTH_BASIC_ENABLED=false \
    -e GF_AUTH_DISABLE_LOGIN_FORM=true \
    -p 3000:3000 \
    grafana/grafana:9.3.1
```

**Comment by ashharrison90** [comment] 2022-12-12 09:53
dupe of https://github.com/grafana/grafana/issues/57048

**Closed by ashharrison90** 2022-12-12 09:53 UTC
Labels: area/navigation, triage/needs-confirmation

**Comment by tab0r** [comment] 2022-12-15 20:37
Awesome thank you! I promised I searched for existing issues- we just used different language.
