### ISSUE TITLE
Overlapping tooltips

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20000] opened 2019-10-24 16:16 UTC
**What happened**:
1. Tooltips are overlapping.
2. Tooltips are positioned on the screen in the way that I cannot see the full list of series.

<img width="1437" alt="tooltip" src="https://user-images.githubusercontent.com/15225624/67504523-d3731d80-f689-11e9-8e14-a98ba67fea91.png">

**What you expected to happen**:
1. To see just one tooltip.
2. If possible tooltips should be fully visible on the screen, if not possible then I should always see the top of the tooltip, not the bottom.

**Comment by Dieterbe** [comment] 2019-11-18 11:13
bump. to be clear, not just the overlapping, actually the inability to see the data at the top is the most frustrating part of this. i run into this frequently and would like to see this fixed.

**Comment by torkelo** [comment] 2019-11-18 11:27
duplicate of https://github.com/grafana/grafana/issues/16157

**Closed by torkelo** 2019-11-18 11:27 UTC
Labels: area/ux, type/ux

**Comment by Dieterbe** [comment] 2019-11-18 11:48
I think in this case it was actually multiple tooltips coming from the same panel (not a shared tooltip scenario I believe which is what the other ticket is about). but most importantly, the inability to see the top of the tooltip data

**Comment by torkelo** [comment] 2019-11-18 12:24
> multiple tooltips coming from the same panel

What do you mean multiple tooltips from same panel?

**Comment by Dieterbe** [comment] 2019-11-18 13:19
looking back at the video i've shared internally (that this screenshot came from), i'm now 100% sure i did not have the multi-tooltip thing activated, for some reason one panel seem to have triggered multiple tooltips in some sort of rapid fire.
