### ISSUE TITLE
Viewer user with admin permissions on folder can't create dashboard from main(left) menu

### ISSUE THREAD

**Issue by AnSmol** [grafana/grafana#13114] opened 2018-09-02 14:07 UTC
### What Grafana version are you using?
Grafana v5.2.3 (cf4c090)

### What datasource are you using?
Elasticsearch 5.6.10(b727a60, lucene_version:6.6.1)

### What OS are you running grafana on?
Debian GNU/Linux 9 (stretch)

### What did you do?
Tried to create dashboard with user with viewer org role and admin/editor permission on folder in general way,  by the left-hand menu.

### What was the expected result?
Successful save dashboard in folder, wich user have admin/editor permissions

### What happened instead?
Access denied error.
But if i create dashboard with folders big green "Create dashboard" button, saving is going succesful

Screencast - http://recordit.co/uMIorB0ra2

**Comment by marefr** [comment] 2018-09-03 09:56
Duplicate of #12543

Fix will be released in v5.3.

**Closed by marefr** 2018-09-03 09:56 UTC
Labels: comp: dashboard/folders, type: bug

**Comment by flopp999** [comment] 2018-10-15 17:54
This issue is closed, but you removed it from Milestone 5.3.
Does this mean that this is still a bug in 5.3?

A workaround is to create the dashboard by click on Home-gear wheel in private folder, then +Dashboard, then it works. But you cannot go back to older versions, I have not reported the version-error as new issue, I want to see if the solution for this error also will fix the version-error.

**Comment by marefr** [comment] 2018-10-15 22:52
@flopp999 I removed it from the milestone because it was a duplicate of already fixed issue #12543 in 5.3. This is fixed in v5.3. I've added it back to 5.3 milestone to minimize confusion. Thanks for pointing this out.

**Comment by gauravk48** [comment] 2018-12-07 17:52
We are facing the same issue. It would be good to have the bug fixed.

**Comment by torkelo** [comment] 2018-12-07 17:57
What version are you using?
