### ISSUE TITLE
Unable to build Grafana Image using Docker Desktop on Windows

### ISSUE THREAD

**Issue by J93d** [grafana/grafana#29254] opened 2020-11-20 02:25 UTC
**What happened**:

Failed to build grafana image with added plugin (redis-datasource) using the method provided in 

*https://grafana.com/docs/grafana/latest/installation/docker/#build-and-run-a-docker-image-with-pre-installed-plugins*

Build was exited with below error:

*COPY failed: stat /var/lib/docker/tmp/docker-builder886986622/grafana-latest.linux-x64.tar.gz: no such file or directory*

![image](https://user-images.githubusercontent.com/46070517/99748747-1c9ed680-2b03-11eb-9615-4e8a7bc39b1d.png)

**What you expected to happen**:

Build success with grafana/grafana image having redis-datasource plugin

**How to reproduce it (as minimally and precisely as possible)**:

Run the below command in Docker desktop:

*docker build --build-arg "GRAFANA_VERSION=latest" --build-arg "GF_INSTALL_PLUGINS=redis-datasource" -t grafana/grafana -f Dockerfile .*

With Dockerfile as ubuntu.Dockerfile  

**Anything else we need to know?**:

**Environment**:
- Grafana version: NA
- Data source type & version: redis-datasource
- OS Grafana is installed on: NA
- User OS & Browser: Windows 10.0.19041 N/A Build 19041
- Grafana plugins:
- Others: Docker desktop details:
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by aknuds1** [comment] 2020-11-20 07:52
I just tested following the [procedure](https://grafana.com/docs/grafana/latest/installation/docker/#build-and-run-a-docker-image-with-pre-installed-plugins) you listed, and it does work. Which directory are you in when you perform the following command: `docker build --build-arg "GRAFANA_VERSION=latest" --build-arg "GF_INSTALL_PLUGINS=redis-datasource" -t grafana/grafana -f Dockerfile`?

**Comment by dprokop** [comment] 2020-11-20 07:54
@aknuds1 I can confirm the same issue, just following the procedure and I encounter the same problem with both Dockerfile and ubuntu.Dockerfile.

**Comment by aknuds1** [comment] 2020-11-20 07:58
I see now that the user is on Windows, if it does fail I suspect it's due to Docker on Windows intricacies.

**Comment by J93d** [comment] 2020-11-20 09:16
> I just tested following the [procedure](https://grafana.com/docs/grafana/latest/installation/docker/#build-and-run-a-docker-image-with-pre-installed-plugins) you listed, and it does work. Which directory are you in when you perform the following command: `docker build --build-arg "GRAFANA_VERSION=latest" --build-arg "GF_INSTALL_PLUGINS=redis-datasource" -t grafana/grafana -f Dockerfile .`?

I am in an empty folder with only docker file. I followed the procedure to my best understanding. If there are any changes, please do mention.

**Comment by aknuds1** [comment] 2020-11-20 09:29
You shouldn't be in an empty directory @J93d , you should be in the directory [packaging/docker/custom](https://github.com/grafana/grafana/tree/master/packaging/docker/custom) in the Grafana repository.

Closing this as it most likely stems from a user mistake.

**Closed by aknuds1** 2020-11-20 09:29 UTC
Labels: needs more info, type/build-packaging
