### ISSUE TITLE
Bug: Folder API error

### ISSUE THREAD

**Issue by zhangzx1996** [grafana/grafana#83474] opened 2024-02-27 08:54 UTC
### What happened?

There is the message "Folder API error" when I change the folder name

### What did you expect to happen?

no

### Did this work before?

yes

### How do we reproduce it?

1.
2.
3.

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: 10.2.3
OS: 
Browser: google chrome  121.0.6167.184

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment] 2024-03-26 17:02
hi @zhangzx1996 

can you elaborate on the repro steps please?
thank you!

**Comment by SteenSchutt** [comment] 2024-05-10 09:47
I am seeing this as well. It appears to happen in lots of different situations where a proper error message would have been helpful. In my case the error is caused by trying to rename a folder to have the same name as a dashboard in the same folder. (I have the nested folders flag enabled, in case that's relevant for anyone)

```
logger=folder-service t=2024-05-10T11:44:34.049108766+02:00 level=error msg="folder update failed" folderUID=e1bcc2d9-121d-4b52-beb6-9e264a58ab00 error="UNIQUE constraint failed: dashboard.org_id, dashboard.folder_uid, dashboard.title"

```

@zhangzx1996 I'd recommend checking Grafana's log for more information.

**Comment by SteenSchutt** [comment] 2024-05-10 13:34
@tonypowa What I'm describing is a known limitation: https://github.com/grafana/grafana/issues/15642
I am just suggesting a way for the asker to find more information on the issue, as I found this one while trying to resolve a different problem.

**Comment by tonypowa** [comment] 2024-05-20 08:18
thank you @SteenSchutt  !
@zhangzx1996 closing the issue. Feel free to request to reopen once you have gathered more information on how you persinally reproduce the issue, so we can move the issue to an engineering team

**Closed by tonypowa** 2024-05-20 08:18 UTC
Labels: needs more info
