### ISSUE TITLE
Regression from 9.3.2: Dashboard-variable not used in Influx-query in 9.5.1

### ISSUE THREAD

**Issue by konfusator** [grafana/grafana#67602] opened 2023-05-01 20:08 UTC
## What happened:

In my setup there are three different retention policies in influx DB, holding the data for thirty days, one year or ten years respectively. I'm switching manually between the policies using a template variable $influx_retention, which is a custom variable containing the names of the policies. Queries are done in the form

```
SELECT mean("value") FROM "$influx_retention"."ping4" WHERE ("metric" = 'pl' AND "hostname" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval) fill(null)
```

This might not be the most elegant way but it worked up to Grafana 9.3.2 but fails with 9.5.1

## What you expected to happen:
If the variable $influx_retention is changed in the pulldown menu a new query in the new retention policy should be made and the data of that retention policy should be shown. This does not happen any more.

## How to reproduce it (as minimally and precisely as possible):
Create a simple dashboard with a custom variable  $influx_retention and a query like the one above. Using the browsers developemnt console you will see that on selecting a new value in the Pulldown menu the query will still use the old name.

## Environment:
- Grafana version: 9.5.1
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: Debian 10
- User OS & Browser: Debian bullseye; browser Firefox 102  and Chromium 112

**Comment by cholyoak** [comment] 2023-05-03 22:10
I can second this regression. It is most likely related to #66466 somehow, though I can't speak to the internals.

**Comment by maxwellvarner** [comment] 2023-05-08 20:51
I third this issue. I found that switching my query type to raw mode allows for the retention variable I've created to be used, but using the editor mode seems to ignore that variable. Interestingly, I also have a interval variable used in my timestamp groupby clause that works no matter what mode is used to build the query.

It would seem that some change is finding the default retention variable from my influxdb datasource and using that value instead of the value I'm passing in. Which sounds very much like the PR mentioned above by @cholyoak

**Comment by itsmylife** [comment] 2023-05-16 16:26
@maxwellvarner With [this PR](https://github.com/grafana/grafana/pull/63820) we start to use retention policies in queries as it should have been. So when you select retention policy in the dropdown it will be in the query. But, correct me if I am wrong, I think you are trying to have a template variable in the retention policies dropdown. And since we are not interpolating the retention policy in there we are always using the default policy instead of the variable value. If my understanding is correct, we need to handle interpolation for retention policies as well. If I understand your case I will start investigating this.

**Comment by maxwellvarner** [comment] 2023-05-16 16:45
@itsmylife you are understanding my use case correctly. I have created a template variable where I run a query against my influxdb datasource, SHOW RETENTION POLICIES, which populates the variable dropdown and then I utilize that template variable in the panel query.

This appears to be respected when the query is written or converted to raw mode, but leaving the query of the panel in editor mode (which is preferred as it's easier to read and modify; plus we have 100s of panels who's queries are saved in editor mode and we'd have to convert them all to raw mode to work around the issue) results in the default being passed in the generated request to influxDB.

As mentioned above, this never seemed to be an issue on previous versions of Grafana (raw vs editor mode with template variables for the retention policy). During my upgrades this worked all the way up to 9.4.7. It wasn't until 9.5.1 that the issue presented itself. 

![Screenshot 2023-05-16 at 12 36 10 PM](https://github.com/grafana/grafana/assets/93388319/99dd0e73-45a4-4ad2-a355-d93b92631782)

**Comment by maxwellvarner** [comment] 2023-05-16 16:58
The purpose of this approach is to allow users who only have viewing access to these panels the ability to adjust the retention policy of the panel queries and reduce the number of panels and dashboards we'd have to create for each specific retention policy.

However, I have read a bit about the autogen retention policy, though if enabled that seems to just grab the default retention policy for the database. If there was an option that automatically picked the retention policy based on the time range chosen that would be useful, but I suspect would only work if naming standards for retention polices were utilized (ie. two_hours, two_days, one_week, one_month, etc.) If they were named anything else then you'd have to somehow get the duration value associated with the retention polices of the database and base the choice on that value.

**Comment by itsmylife** [comment] 2023-05-18 09:06
@maxwellvarner Thanks for the clarification. I will start working on this.

**Comment by therokh** [comment] 2023-05-25 07:28
Hi, we have the same issue. We have upgraded from 9.2.3 to 9.5.2 and our retention policy variable no longer works in the panel, which seem to fall back to our default retention policy in Influx. We've worked around it for now by changing our default retention policies on the Influx instances as we are explicitly setting the policy in Telegraf

**Closed** 2023-05-31 10:04 UTC
Labels: datasource/InfluxDB, triage/needs-confirmation

**Comment by maxwellvarner** [comment] 2023-06-13 16:47
@itsmylife - how does the back patching process of this fix work? If I pull a new image of 9.5.1 would I expect the fix to be in that version or do I need to upgrade to 9.5.3 to get these changes? It was unclear to me based on the CHANGELOG if this was part of the 9.5.3 build.

**Comment by Rayn0r** [comment] 2023-06-14 06:30
@itsmylife I am on Grafana 10.0.0 now and this still does not seem work. I'm using a Time Series to plot some graphs, but the retention selected is still not honored in the query.
See pictures below:
![image](https://github.com/grafana/grafana/assets/4147858/f348d94e-ea35-45cb-9357-d6b9e96795f5)

![Grafana_query-variable_not_working](https://github.com/grafana/grafana/assets/4147858/8b3448ea-58ba-46af-9eeb-9b9b3a85146c)

**Comment by itsmylife** [comment] 2023-06-14 07:28
@maxwellvarner Basically it is just cherry-picking a commit to another branch. In your case v9.5.x branches we have won't receive any new commits. So the fix won't be there. It would be best if you upgraded the v10.0.x version as it is the latest supported version. 

@Rayn0r I might have messed with the backporting. I will check that immediately. I am sorry for the inconvenience.

**Comment by itsmylife** [comment] 2023-06-14 09:09
@Rayn0r The changes will be in the release on the 20th of June.
