### ISSUE TITLE
[Bug] InfluxDB Query with multiple $__interval causes error in alerting

### ISSUE THREAD

**Issue by mgaffigan** [grafana/grafana#8247] opened 2017-04-28 20:44 UTC
- What Grafana version are you using?
Grafana v4.2.0 (commit: 349f3eb)

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Centos 7

- What did you do?
Create a graph with query `SELECT derivative(sum("value"), $__interval) FROM "mssql.deadlocks" WHERE "host" = 'v-dbserver1' AND "instance" = 'prod' AND $timeFilter GROUP BY time($__interval) fill(previous)`, add an alert `when max() of query(A, 5m, now) is above 10`.

- What was the expected result?
The alert triggers when the maximum value returned exceeds 10 in the preceding five minutes. 

- What happened instead?

    Error: tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request

Query submitted to InfluxDB: 

    SELECT derivative(sum("value"), 1ms) FROM "mssql.deadlocks" WHERE "host" = 'v-dbserver1' AND "instance" = 'prod' AND time > now() - 5m GROUP BY time($__interval) fill(previous)

Note that `$__interval` was left un-replaced in the query submitted to Influx.  The graph query gets correctly substituted:

    SELECT derivative(sum("value"), 2s) FROM "mssql.deadlocks" WHERE "host" = 'v-dbserver1' AND "instance" = 'prod' AND time > now() - 30m GROUP BY time(2s) fill(previous)

**Comment by jgoldschrafe** [comment] 2017-04-29 19:47
This isn't related to the issue you're seeing at all, but I wanted to point out that your `GROUP BY` should be `GROUP BY time($__interval, now())`. With the bucketing you have now, a mismatch between the query timeboxes and the `WHERE` filter's time range will cause you to have incorrect first and last values.

**Comment by mgaffigan** [comment] 2017-04-30 00:22
@jgoldschrafe, it is funny you should mention that, since I was scratching my head as to why my numbers were unevenly bucketed on a different query.  Thanks.

**Comment by torkelo** [comment] 2017-05-01 17:21
duplicate of https://github.com/grafana/grafana/issues/7969  (fixed in master)

**Closed by torkelo** 2017-05-01 17:21 UTC
