### ISSUE TITLE
Auto-save option

### ISSUE THREAD

**Issue by ankitmalhotra** [grafana/grafana#26387] opened 2020-07-16 22:56 UTC
**What would you like to be added**:
Please provide am Auto-save feature or some feature to cognitively alert users that they need to save their work

**Why is this needed**:
Hours of manual work, created dashboards and panels could get lost in a fraction of a second without any backup or recovery possibility

**Comment by ryantxu** [comment] 2020-07-17 00:18
Something different than this:
![image](https://user-images.githubusercontent.com/705951/87734722-4aa49080-c788-11ea-85a6-aa515773e4cf.png)

**Comment by torkelo** [comment] 2020-07-17 05:15
Dupe of #174

**Closed by torkelo** 2020-07-17 05:15 UTC

**Comment by ankitmalhotra** [comment] 2020-07-17 17:23
> Something different than this?
> ![image](https://user-images.githubusercontent.com/705951/87734722-4aa49080-c788-11ea-85a6-aa515773e4cf.png)

@ryantxu If this dialog appears automatically without me hitting the "save" button then yes, it still will be helpful.
