### ISSUE TITLE
[Feature Request] - Template using Name and Value

### ISSUE THREAD

**Issue by nmat** [grafana/grafana#8702] opened 2017-06-26 05:50 UTC
In templating today you can add custom templates using comma seperated values, however lets say you want a value with a different name.
 
{
"Name" : "Value",
"Datacenter Europe" : "dc-01",
"Datacenter US" : "dc-02",
}

Mostly to make the templating more readable if the viewer is a non tech person.

**Comment by torkelo** [comment] 2017-06-26 07:24
duplicate of https://github.com/grafana/grafana/issues/1988

**Closed by torkelo** 2017-06-26 07:24 UTC
