### ISSUE TITLE
Dashboards: influxdbBackendMigration FF enabled - Breaks Template Variables with special characters

### ISSUE THREAD

**Issue by lonionss** [grafana/grafana#79368] opened 2023-12-12 03:37 UTC
### What happened?

Recently updated from v10.0.2 to v10.2.2. In doing so we discovered that public dashboards were broken. The fix was outlined to be enabling the FF 'influxdbBackendMigration' as per: https://github.com/grafana/grafana/issues/77648

Enabling the FF caused queries with template variables to no longer escape special characters, specifically ')'.

$device_name = /Test|Test (1)/
The Query attempting to be executed:
`SELECT (mean("field") FROM "measurement" WHERE ("device" =~ /^$device_name$/)`

In Query inspector, the executedQueryString is:
`SELECT mean(\"field\") FROM \"measurement\" WHERE \"device\" =~ /^Test|Test (1)$/`

The above query returned no data.

### What did you expect to happen?

The executedQueryString would be expected to look like: 
`SELECT mean(\"field\") FROM \"measurement\" WHERE \"device\" =~ /^(Test|Test \\(1\\))$/)`

### Did this work before?

The query works in the current version (v10.2.2) without 'influxdbBackendMigration' FF enabled.
The executedQueryString with FF disabled is:
`SELECT mean(\"field\") FROM \"measurement\" WHERE \"device\" =~ /^(Test|Test \\(1\\))$/)`

### How do we reproduce it?

1. 'influxdbBackendMigration' FF disabled
2. Create a dashboard with a template variable that contains 2 or more values, at least one of them with a special character such as '('
3. Create a panel that queries the template variable and confirm this is working
4. enable FF 'influxdbBackendMigration'
5. Query should stop returning data for the value with a special character and executedQueryString will be formatted different to the original query

### Environment (with versions)?

Grafana: 10.2.2
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

influxDB v1.8

**Comment by gtk-grafana** [comment] 2024-01-05 14:40
Duplicate of https://github.com/grafana/grafana/issues/80003

**Comment by gtk-grafana** [comment] 2024-01-09 20:30
Duplicate of #80003

**Closed by gtk-grafana** 2024-01-09 20:30 UTC
Labels: datasource/InfluxDB, triage/needs-confirmation
