### ISSUE TITLE
Resize Adjacent Panels

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#20395] opened 2019-11-14 17:45 UTC
**What would you like to be added**:

When changing the width of a panel (say making it bigger), I would like the adjacent panel to change size.

Essentially the behavior show in:

![image](https://cloud.githubusercontent.com/assets/10999/9408647/e9a367f4-4814-11e5-9f43-e124b4014c85.gif)

from https://github.com/grafana/grafana/issues/2577

Or something like when resizing columns in google sheets:

![image](https://user-images.githubusercontent.com/1692624/68882267-da1b1080-06dc-11ea-8ce8-86243d931986.png)

**Why is this needed**:

Currently when trying to adjust the width of panel:

![image](https://user-images.githubusercontent.com/1692624/68881324-ed2ce100-06da-11ea-80f3-eec1e0b8fef9.png)

The adjacent panel gets pushed down out the row:

![image](https://user-images.githubusercontent.com/1692624/68881366-00d84780-06db-11ea-9fd3-a5910673ff98.png)

The is a jarring experience because things are jumping around:

![chrome-capture](https://user-images.githubusercontent.com/1692624/68882023-4fd2ac80-06dc-11ea-967a-f463de8e6012.gif)

**Comment by torkelo** [comment] 2019-11-17 09:34
This is a pretty universal behavior for all grid layouts that allow for rich layouts (kibana, datadog, chronograf, splunk). And is built-in behavior in the grid framework. 

Modifying other panels width just because your modifying one is very hard for Grafana to decide is the right thing to do.  it worked before as rows was a strict concept and panels could not have different heights within a row. There is no similar row concept in Grafana after v5. 

But I think we can make some improvements to resizing: 
I think we could have some hidden power shortcuts to auto align widths, and also to show width in grid units as you resize to make it easier to get the same width.

**Comment by ryantxu** [comment] 2019-11-18 00:38
The behavior in grafana is based on: https://github.com/STRML/react-grid-layout

It might be interesting to have a drag handle between two panels -- but I think it is worth adding at the RGL level, not grafana proper

**Comment by torkelo** [comment] 2019-11-18 07:42
The problem is that this has to be some resize mode you can toggle in / out of. As it would be super bad if you just want to make a panel full size and then want the other panels to be pushed down and not squashed to oblivion.

**Comment by pkolyvas** [comment] 2021-07-26 16:40
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Closed by pkolyvas** 2021-07-26 16:40 UTC
Labels: area/frontend, area/panel/common, type/feature-request
