### ISSUE TITLE
Cloud Monitoring/Stackdriver project selector constantly resets itself

### ISSUE THREAD

**Issue by bjakubski** [grafana/grafana#27863] opened 2020-09-28 15:59 UTC
**What happened**:

I'm running grafana in GKE (GCE for the purpose of this error).
I'm running grafana with its specific Service Account, using `authenticationType: gce`.
This Service Account has monitoring.viewer role in **multiple** projects.

If I open a panel editor (or "explore") and select my Cloud Monitoring/Stackdriver data source I'm able to see the projects I have access to in the dropdown in the "Project" field.

If I select any project other than happens to be there pre-selected (which is also the project grafana instance is running on, in other words it is the one which metadata calls will return) **dropdown menu will disappear, but still the first project will be shown as seleceted**. In other words: No matter which project I choose I'm left with the first one.
**But** this is superficial. The other project **gets** selected.
If I do a query first (any query) and group by project_id (to see where I get data from) I can see that If I change "Project" from "1" to "4" then project "4" is queried and data from it is shown.

Still the wrong project is shown and If I do any change in the query (changing metric to something else) query is again sent against the default project ("1" in example above), so project selector is fully reset....

**What you expected to happen**:

After selecting project it is shown as selected.
Changing query parameters should not reset the project selection.

**How to reproduce it (as minimally and precisely as possible)**:

Pretty much as I described it in "What happened".

**Anything else we need to know?**:

As the project that is selected by default and select resets to is the project grafana is running in I suspect it is related to handling the GCE-fetched metadata.

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Google Cloud Monitoring Data Source 1.0.0
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome 85 /Linux
- Grafana plugins: -
- Others: -

**Comment by zoltanbedi** [comment] 2020-09-28 16:11
I think this is a duplicate of #27855

**Closed by zoltanbedi** 2020-09-28 16:11 UTC
