### ISSUE TITLE
HA servers with identical provisioned dashboards leads to infinite growth of dashboard_version table

### ISSUE THREAD

**Issue by vitroth** [grafana/grafana#13043] opened 2018-08-27 16:00 UTC
When deploying multiple grafana servers, if identical dashboard files exist on disk on each server, the servers will continuously insert "updates" into the dashboard_version table and eventually exhaust the database capacity.

For example:
 - Grafana deployed in AWS using an AMI that contains grafana and a pre-populated set of dashboards, using RDS for the backend database
 - Grafana running in an AutoScalingGroup with multiple instances
 - If the ASG deploys two instances, they will continuously update the database, despite the contents of the database being identical to the dashboard they are inserting.

This was observed with Grafana 5.1.3, but is likely related to #12864 which was observed on 5.2.2

### What Grafana version are you using?
5.1.3
### What datasource are you using?
prometheus
### What OS are you running grafana on?
Ubuntu 14
### What did you do?
Deployed multiple grafana hosts for HA access, with identical dashboard configurations on disk
### What was the expected result?
Dashboard loads once, service operates normally
### What happened instead?
The dashboard_version table ended up with thousands of copies of the dashboards, differing only in the insert timestamp and row id, until the database went offline due to disk usage.

**Comment by torkelo** [comment] 2018-08-27 16:40
duplicate of https://github.com/grafana/grafana/issues/12864

**Closed by torkelo** 2018-08-27 16:40 UTC

**Comment by vitroth** [comment] 2018-08-27 19:55
Sorry, I didn't think this was strictly a duplicate of #12864.  In that ticket, two misconfigured dashboard files (having the same id field) on a single system cause the system to misbehave, where in this ticket two separate systems, each with identical dashboard files, causes a similar failure in the backend database processing.  To me it was similar symptoms, different scenarios.

**Comment by marefr** [comment] 2018-08-28 09:09
Same symptoms. Fixing #12864 should fix this problem as well.

**Comment by aiman-alsari** [comment] 2018-12-05 13:13
We're seeing this same scenario, we don't have any duplicate IDs, ours is replicating every dashboard in the versions table due to HA.
