### ISSUE TITLE
Release: Latest release to previous version

### ISSUE THREAD

**Issue by bLd75** [grafana/grafana#49298] opened 2022-05-20 06:49 UTC
**What happened**:

In the last release, version with tag `latest` points to grafana v7.5.16, while the latest version is v8.5.3.
Our integration pipeline (and I guess many other users one) scrapes the latest version of grafana to upgrade. As a result, we downgraded to an older version which broke all our dashboards.

**What you expected to happen**:

Release with tag `latest` to be always the latest version.

**How to reproduce it (as minimally and precisely as possible)**:

`wget $(curl -s https://api.github.com/repos/grafana/grafana/releases/latest |grep "tag_name"  | awk '{print "https://dl.grafana.com/oss/release/grafana_" substr($2, 3, length($2)-4) "_amd64.deb"}') `

**Comment by zuchka** [comment] 2022-05-20 19:52
The community forum has reported this as well:

https://community.grafana.com/t/grafana-latest-ubuntu-docker-container-downgraded-to-7-5-14/59987/4

but also for more general confusion, and a desire for a `stable` tag:

https://community.grafana.com/t/suggestion-stable-tag-for-docker/60242

https://community.grafana.com/t/docker-main-vs-latest/60183

**Comment by bLd75** [comment] 2022-05-20 23:00
Thank you, in general stable has a higher standard of testing than latest version.

The tags included into a GH release can simply follow some simple path to make it clear for everyone (from newest to oldest):
- testing
- latest
- stable
- legacy

**Comment by AndrewSav** [comment] 2022-05-23 01:00
It would be good if `https://api.github.com/repos/grafana/grafana/releases/latest` returned lasted non-testing release.

**Comment by chennin** [comment] 2022-06-13 17:04
Yes, I think the `latest` tag flip flopping between a stable version and a beta version and then a very old stable version is clearly a bug. Please either fix `latest` or define a `stable` tag that points to the most recent `stable` version. Alternately or in addition, please define tags like `8` and `8.5` that always point to the most recent version matching them.  Please also be sure to document the policy for what points to what.

More references:

https://github.com/grafana/grafana/discussions/47177
https://github.com/grafana/grafana/discussions/45342
https://github.com/grafana/grafana/discussions/42796
https://github.com/grafana/grafana/discussions/42879

> It would be good if `https://api.github.com/repos/grafana/grafana/releases/latest` returned lasted non-testing release. We too are using this Url to check if we might need updates.

@AndrewSav  For this you can  use `https://grafana.com/api/grafana/versions/stable`

**Comment by AndrewSav** [comment] 2022-06-14 22:41
> For this you can use https://grafana.com/api/grafana/versions/stable

@chennin  Not really, I need the latest version, not all of them, and as far as I'm aware the order is not guaranteed either. Thank you for the suggestion!

**Comment by zuchka** [comment] 2022-07-28 07:14
going to close this for now pending new info. If the problem still exists, we can re-open :)

**Closed** 2022-07-28 07:14 UTC
Labels: type/build-packaging, area/docker

**Comment by chennin** [comment] 2022-08-05 16:41
@zuchka  This has happened again.  "Latest" amd64 is currently 845cdcb541eb aka 9.1.0-beta1 amd64.  **PLEASE** fix the processes that continue to mis-tag "latest", or introduce a "stable" tag that always points to the latest stable release and document it.  *Something* to prevent this from happening again.

**Comment by AndrewSav** [comment] 2022-08-06 03:01
@chennin unless it was just fixed, you might have a different issue than OP, if so it may be better opening a separate issue describing it. Currently if you follow the steps to reproduce in OP you will get 9.0.6 which is what I'd expect.

**Comment by malcolmholmes** [comment] 2022-08-06 07:25
@AndrewSav the symptoms were the same, even if the cause was different (yet to be investigated).

I am grateful to @chennin for pointing this out. Once noticed, it was easy to fix, which I did soon after he pointed it out.
