### ISSUE TITLE
[Feature request] MS SQL Server as DB (not datasource)

### ISSUE THREAD

**Issue by PhilSmithABB** [grafana/grafana#8674] opened 2017-06-21 08:47 UTC
We're using Grafana 4.3.2 with our own custom datasource on Windows 2012. 

Currently we're using MySQL or SQLLite as the Grafana database (not as a datasource) but because we're predominately the windows stack we'd like to be able to use MS SQL Server instead of MySQL for high availability configurations. 

I'd imagine [SQL Server Express](https://www.microsoft.com/en-us/sql-server/sql-server-editions-express) would be good enough as this allows for a 10GB database and it's available for free.

**Comment by torkelo** [comment] 2017-06-21 12:18
duplicate of https://github.com/grafana/grafana/issues/1692

**Comment by daniellee** [comment] 2017-06-21 15:03
Noticed that this was not a duplicate and it is a feature that we would like to implement in the future.

**Comment by MarcoJ-CID** [comment] 2018-04-13 12:59
Hi. Any updates to this topic?

**Comment by captncraig** [comment] 2018-05-30 21:53
FYI I started working on this, and am already up and running. Will make formal pr as soon as I more thoroughly test different config scenarios and make sure everything seems stable.

https://github.com/grafana/grafana/compare/master...captncraig:mssql?expand=1

**Comment by srivb** [comment] 2021-05-24 10:20
Any documents to follow? How to add my MSSQL DB as  the database for high availablity

**Comment by bergquist** [comment] 2023-01-31 17:24
This issue has been open for many years now. While we appreciate the pull requests adding support for MSSQL we cannot take on the maintenance burden given the low demand. 

MySQL, MariaDB, Postgres, and sqlite run fine on Windows. If those are not an option due to the company's commitment to Microsoft you can use [Grafana Cloud](https://grafana.com/get/?pg=oss-graf&plcmt=hero-btn-1) or [Azure’s managed Grafana service](https://azure.microsoft.com/en-us/products/managed-grafana/#overview).

**Closed by bergquist** 2023-01-31 17:24 UTC
Labels: type/feature-request, area/backend/db
