### ISSUE TITLE
Jump to explore broken in latest master

### ISSUE THREAD

**Issue by gouthamve** [grafana/grafana#22201] opened 2020-02-14 09:52 UTC
We are running commit 961cb6b284 with the web-prefix of `/grafana`. When I try to jump to explore from a dashboard panel, it tries to open the url: `/grafana/grafana/explore?.....`, adding an extra `/grafana` thereby 404-ing.

**Comment by luizribeiro** [comment] 2020-03-01 16:14
Did this really fix the issue?

I'm currently running v6.6.2 and when I click on Explore I don't get any sub URL prefix. All other links from the graph panel work though.

**Comment by chadlwilson** [comment] 2020-03-10 04:06
This (or related) fixes seemed to make Explore work again for Gauge panels we have (which was broken in 6.6.1), but break it for all our single stat panels. Very confusing.

**Comment by tskarhed** [comment] 2020-03-10 10:22
@chadlwilson Can you provide some steps to reproduce this? Quickly tried from master and I couldn't reproduce it.

**Comment by dprokop** [comment] 2020-03-10 10:23
@tskarhed have you tried with Grafana served from subpath?

**Comment by tskarhed** [comment] 2020-03-10 10:24
> @tskarhed have you tried with Grafana served from subpath?

Yes,
```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

**Comment by dprokop** [comment] 2020-03-10 12:11
Confirmed bug in 6.6.2. Works in single stat, gauge, doesn't work in single stat.

**Comment by dprokop** [comment] 2020-03-10 12:26
This is now fixed in master with @torkelo's PR merged (https://github.com/grafana/grafana/pull/21265). Angular and React panels use the same PanelHeader now and the menu component is reused. We must have missed the links fix for Angular panels, sorry about that.

New version (6.7.0-beta1) is about to be released tomorrow.

**Closed by dprokop** 2020-03-10 12:26 UTC
Labels: area/frontend, type/bug

**Comment by chadlwilson** [comment] 2020-03-11 01:00
Thanks a lot @dprokop and @tskarhed . I trust you don't need re-prod steps now, but our use case is pretty standard:

- Grafana installed via stable Helm chart
- K8S ingress configured for `/grafana/?(.*)` route
- `root_url = /grafana` (we don't seem to have the domain there, that seems to work?)
- `serve_from_sub_path` is default (false)

I tried switching `serve_from_sub_path` to `true` when doing trial-and-error to address this in case it was due to our use case, however it didn't seem to have any effect.

Any chance of a `6.6.3` backport to address this? We rolled back to `6.6.1` (because in our case the blast radius is lower for broken Gauge explores to SingleStat explores) but it'd be nice to have this resolved sooner rather than later.
