### ISSUE TITLE
Input Focus Issue when typing Korean Characters in Elastic search Query Editor

### ISSUE THREAD

**Issue by zestairlove** [grafana/grafana#54818] opened 2022-09-07 04:40 UTC
**What happened**:
- When typing Korean Characters in Elastic search Query Editor, the editor's input loses focus, and in Grafana, the Shortcut is executed and the search UI is executed.

![2022-09-07 13-26-19 2022-09-07 13_28_01](https://user-images.githubusercontent.com/24940457/188789605-7acefa75-87f9-4ddf-9fa1-fa242091b2af.gif)

**Environment**:
- Grafana version: 8.5.5, 9.1.3
- Data source type & version: Elastic Search
- OS Grafana is installed on:
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment] 2022-09-07 11:49
This is a duplicate of https://github.com/grafana/grafana/issues/54535. Follow that issue for updates on when it is fixed.

**Closed by ivanahuckova** 2022-09-07 11:50 UTC
