### ISSUE TITLE
Alert using slack with dashboard image fails with error message: file already closed

### ISSUE THREAD

**Issue by bmy4415** [grafana/grafana#32048] opened 2021-03-17 05:30 UTC
**What happened**:
Slack alert with attaching dashboard image fails.
Below is log from grafana
```
t=2021-03-17T05:17:03+0000 lvl=warn msg="Failed to close file" logger=rendering renderer=http path=/var/lib/grafana/png/llXM6yPDHzvh9os49r63.png err="close /var/lib/grafana/png/llXM6yPDHzvh9os49r63.png: file already closed"
t=2021-03-17T05:17:04+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification=slack
t=2021-03-17T05:17:04+0000 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack
```

I found this [code line](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/slack.go#L375).

I also found that image file itself is stored inside grafana container.
```
bash-5.0$ ls -al /var/lib/grafana/png
total 64
drwx------    2 grafana  root            38 Mar 17 05:17 .
drwxrwxrwx    1 grafana  root            35 Mar 17 05:22 ..
-rw-r--r--    1 grafana  root         63281 Mar 17 05:17 llXM6yPDHzvh9os49r63.png
```

Also, I uses s3 as external storage and found that this dashboard image is successfully uploaded to s3.
But strangely, this is not attached to slack notification.

Can anybody take a look into this issue?

**What you expected to happen**:
Dashboard image is successfully sent to slack.

**How to reproduce it (as minimally and precisely as possible)**:
When creating notification channel with slack type, enable `Include image` tap from `Notification settings`

![Screen Shot 2021-03-17 at 14 22 41](https://user-images.githubusercontent.com/29326383/111419179-550a9600-872c-11eb-89df-ad8b9ae0a010.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:
```
t=2021-03-17T05:12:50+0000 lvl=info msg="Starting Grafana" logger=server version=7.4.3 commit=010f20c1c8 branch=HEAD compiled=2021-02-24T10:29:10+0000
```
- Data source type & version:
```
/bin $ ./prometheus --version
prometheus, version 2.25.1 (branch: HEAD, revision: 34ca0bb20a1b2257950bba94df9391cc62ff3a91)
  build user:       root@3e6c98526c22
  build date:       20210314-12:27:48
  go version:       go1.15.10
  platform:         linux/amd64
```
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment] 2021-03-17 11:36
Thanks for reporting this. 
Can you please fill in the OS Grafana is running on? that might help to reproduce the issue.

Thanks a lot.

**Comment by leahoswald** [comment] 2021-04-27 14:56
Is the image not displayed at all or just not loaded? In the second case you get some grey replacement in slack

**Comment by marcogreiveldinger3798** [comment] 2021-05-03 08:49
Hi there,
I am getting the same error message but with a MS-Teams connector. Maybe this might help:

```

t=2021-05-03T08:35:50+0000 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/IfY-O7OZz/infra?orgId=1&panelId=8"
--

t=2021-05-03T08:35:50+0000 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=4LHHr3nXv9719AEluLfwD3Auc80TxZuc&timeout=15&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2FIfY-O7OZz%2Finfra%3ForgId%3D1%26panelId%3D8%26render%3D1&width=1000"
--

t=2021-05-03T08:35:54+0000 lvl=warn msg="Failed to close file" logger=rendering renderer=http path=/var/lib/grafana/png/VpPPVtt3U69SMdoN5wNq.png err="close /var/lib/grafana/png/VpPPVtt3U69SMdoN5wNq.png: file already closed"
--

t=2021-05-03T08:35:54+0000 lvl=info msg="Executing teams notification" logger=alerting.notifier.teams ruleId=16 notification="test teams"
```

The strange thing is that I can view rendered screenshot when I take them manually via 'share panel' -> 'Direct link rendered image' ... Even though the same error occurs  but the screenshot is visible via the link. I can also confirm that they are created and are accessible in the docker container.

I am using a custom build grafana docker image (based on grafana/grafana:7.5.4 with some extra plugins and custom datasources) and the standard image-renderer docker

```docker-compose.yml
version: '3.1'
services:
  grafana:
    image: 'myOwnECR/grafana:latest'
    ports:
      - "3000:3000"
    environment:
      ...
      GF_PATHS_PLUGINS: /home/grafana/plugins
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    logging:
      driver: awslogs
      options:
        awslogs-group: grafana
    networks:
      - grafananet
  renderer:
    image: grafana/grafana-image-renderer:2.0.1
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
    networks:
      - grafananet
  nginx:
    image: 'myOwnECR/nginx-grafana:latest'
    ports:
      - '443:443'
    networks:
      - grafananet

networks:
  grafananet:
    driver: bridge
```

**Comment by leahoswald** [comment] 2021-05-03 08:53
At our installation I could fix a similar error by renabling TLS1.2 in the niginx reverse proxy. So maybe there is a strict proxy in your setup too.

**Comment by marcogreiveldinger3798** [comment] 2021-05-03 13:48
This shouldn't be a problem as we are quite default here 
```
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers         HIGH:!aNULL:!MD5;
```
And this should also not be a problem as the setup is communicating directly through docker hostnames with no nginx in between
```
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
```

**Comment by BitProcessor** [comment] 2021-05-27 07:56
I'm experiencing something similar with Slack notifications:
```
t=2021-05-27T07:39:12+0000 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/gwvUbfqGz/kubernetes?orgId=1&panelId=2"
t=2021-05-27T07:39:18+0000 lvl=warn msg="Failed to close file" logger=rendering renderer=http path=/var/lib/grafana/png/kAMpHdGwyvzDBHGWIa0u.png err="close /var/lib/grafana/png/kAMpHdGwyvzDBHGWIa0u.png: file already closed"
t=2021-05-27T07:39:18+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification="Slack - #monitoring_grafana"
```

The "Include image" is enabled in the notification channel config, but nothing is present:

![Screenshot 2021-05-27 at 09 46 46](https://user-images.githubusercontent.com/50638541/119786462-804df600-bed0-11eb-9add-26347e9bd83f.png)

I'm running this on Kubernetes, with the Grafana Helm chart:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: prod-grafana
spec:
  releaseName: grafana
  chart:
    repository: https://grafana.github.io/helm-charts
    name: grafana
    version: 6.9.1
  values:
    image:
      tag: 7.5.7
    replicas: 1
    envFromSecret: sealed-secret
    admin:
      existingSecret: sealed-secret
      userKey: GF_SECURITY_ADMIN_USER
      passwordKey: GF_SECURITY_ADMIN_PASSWORD
    testFramework:
      enabled: false
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/metrics'
      prometheus.io/port: '3000'
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
      path: /
      hosts:
        - <DELETED>
      tls:
        - hosts:
          - <DELETED>
          secretName: le-prod-grafana
    serviceAccount:
      create: true
      name: grafana
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::<DELETED>:role/EKS-prod-grafana-ServiceAccount-Role
    imageRenderer:
      enabled: true
      replicas: 1
         
    grafana.ini:
      database:
        type: postgres
        host: pro-services.cluster-<DELETED>.eu-west-1.rds.amazonaws.com
        name: pro_grafana
        user: pro_grafana_mainuser
      server:
        domain: <DELETED>
        root_url: <DELETED>
        serve_from_sub_path: true
      auth:
        oauth_auto_login: true
        disable_login_form: true
        sigv4_auth_enabled: true
      auth.basic:
        enabled: false
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        allowed_domains: <DELETED>
        # team_ids: 
        # allowed_organizations:
        name: Auth0
        client_id: <DELETED>
        scopes: openid profile email
        auth_url: https://slickss.eu.auth0.com/authorize
        token_url: https://slickss.eu.auth0.com/oauth/token
        api_url: https://slickss.eu.auth0.com/userinfo
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/<DELETED>
          access: proxy
          isDefault: true
          jsonData:
            sigV4Auth: true
            sigV4AuthType: default
            sigV4AssumeRoleArn: arn:aws:iam::<DELETED>:role/Grafana-AMP-Query-Central-Role
            sigV4Region: eu-west-1

```

**Comment by Legion2** [comment] 2021-05-31 12:28
We also have the `Failed to close file` log message and we use telegram notification channel. Grafana and image renderer are deployed using the official helm chart `6.9.1`.

**Comment by dsotirakis** [comment] 2021-06-02 10:07
Hello all, thanks for reporting this!

Unfortunately, I can get the `Failed to close file` warning, but I can see my image being sent correctly, so not able to reproduce that really 😕 

Furthermore, from version `8.0.0-beta1` and after, we refactored things a bit (check this PR https://github.com/grafana/grafana/pull/32511), so when trying to reproduce there, the error seems to be gone. Will continue investigating in case I missed something.

**Comment by dsotirakis** [comment] 2021-08-17 08:00
Closing this, since we have no updates for the last two months and also not able to reproduce. Feel free to open another issue if the error still insists. Thanks for raising the issue!

**Closed by dsotirakis** 2021-08-17 08:00 UTC
Labels: area/alerting/notifications, area/imagestore, needs investigation
