### ISSUE TITLE
nestedFolders: Dashboard Permissions by Team not works

### ISSUE THREAD

**Issue by baur** [grafana/grafana#74302] opened 2023-09-04 03:26 UTC
### What happened?

Dashboard Permissions by Team not works if enable nested folders

### What did you expect to happen?

Member of team must have view access to dashboar if team was added on Permissions 

### Did this work before?

no, as nested folders are a new feature

### How do we reproduce it?

1. set
[feature_toggles]
nestedFolders = true
2. Create team team1
3. Add user1 to team1
4. Create dashboard1
5. Add team1 to dashboard1 Permissions  as viewver 
6. Login as user1

### Environment (with versions)?

Grafana: 10.1.1
OS: Windows10
Browser: Chrome

### Grafana platform?

None

### Datasource(s)?

mssql

**Comment by papagian** [comment] 2023-09-18 07:59
thank you for reporting this: but I'm afraid I'm unable to reproduce it
![Screenshot 2023-09-18 at 10 35 17 AM](https://github.com/grafana/grafana/assets/1632407/710f58ce-cbf9-4e62-85ef-00603786ea82)
![Screenshot 2023-09-18 at 10 35 50 AM](https://github.com/grafana/grafana/assets/1632407/d8b8cee8-862c-4001-ba02-d04904d2d422)
I wonder if your issue is a duplicate of #71425 (the dashboard does not appear in the browser view rather than being unable to access the dashboard).
Could you provide more specific details of how to reproduce it? also note that the subfolders is a preview feature (not generally available yet)

**Comment by mildwonkey** [comment] 2023-11-16 14:38
I am going to close this issue, since we do have some recent fixes, but if anyone is still seeing an issue with Dashboard permissions, please open a new issue with a detailed reproduction case. Thanks!

**Closed by mildwonkey** 2023-11-16 14:38 UTC
Labels: needs more info, area/dashboard/folders
