### ISSUE TITLE
Using Alerts on Loki data source seems to be ignoring "Skip TLS Verify" set on the data source.

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#32856] opened 2021-04-09 18:38 UTC
**What happened**: setting alert on loki data source and testing it shows "x509: certificate is not valid for any names, but wanted to match log" ... However the query the alert is being set on runs fine.

**How to reproduce it (as minimally and precisely as possible)**: Create a alert on loki data source that has an invalid ssl cert while using option (Skip TLS Verify)

**Environment**:
- Grafana version: 7.5.1, 7.5.3
- Data source type & version: loki
- OS Grafana is installed on: ubuntu 20.04

**Comment by steverweber** [comment] 2021-04-09 18:48
The alert query returns error like: 
```
Error: tsdb.HandleRequest() error Get "https://log-p02.../loki/api/v1/query_range?direction=BACKWARD&end=1617993605091838222&interval=1&limit=1000&query=rate.....5B%24__interval%5D%29&start=1617990005091838222&step=2": x509: certificate is not valid for any names, but wanted to match log-p02.math.private.uwaterloo.ca
```

**Comment by hugohaggmark** [comment] 2021-04-12 04:27
Passing over this to @grafana/observability-squad for investigation

**Comment by ivanahuckova** [comment] 2021-04-12 08:11
/duplicate of https://github.com/grafana/grafana/issues/32533

**Closed** 2021-04-12 16:11 UTC
Labels: area/alerting, datasource/Loki, needs investigation, type/duplicate
