### ISSUE TITLE
Templating in 2.5+ with Prometheus DS

### ISSUE THREAD

**Issue by A-Kasper** [grafana/grafana#3166] opened 2015-11-08 19:15 UTC
I can't use templates. When adding a template (query) Grafana throws an error, that the variable couldn't be set. (undefined). In 2.1.3 everything works fine with same setup (prometheus plugin)

**Comment by mtanda** [comment] 2015-11-09 01:09
What version of Prometheus are you using?
I'm tested templating on Grafana 2.5, and Prometheus 0.16.1, I can't replicate.
Prometheus API is changed since 0.15.0, current datasource plugin doesn't support old API.

**Comment by A-Kasper** [comment] 2015-11-09 01:27
Am 09.11.2015 um 02:09 schrieb Mitsuhiro Tanda:
> What version of Prometheus are you using?
> I'm tested templating on Grafana 2.5, and Prometheus 0.16.1, I can't
> replicate.
> Prometheus API is changed since 0.15.0, current datasource plugin
> doesn't support old API.


Hi

I'm using 16.1

do the following:
1. add data source http://map.freifunk-bochum.de:9090 (direct) Prometheus
2. Goto Dashboard
3. Add new Template

Variable: nodes, query, prometheus

Query: ffnode_*_clients

Update...

**Comment by mtanda** [comment] 2015-11-09 02:49
Okay, same version I use.

Not sure why it doesn't work.
In my environment, specify by regex, not wildcard is work.
Please try "ffnode_.*_clients" query.

**Comment by A-Kasper** [comment] 2015-11-09 04:22
​



2015-11-09 3:50 GMT+01:00 Mitsuhiro Tanda <notifications@github.com>:

**Comment by A-Kasper** [comment] 2015-11-09 04:24
​with these Infos you should be able to reconstruct the issue



2015-11-09 5:21 GMT+01:00 Andre Kasper <ein.kasper@gmx.de>:

**Comment by A-Kasper** [comment] 2015-11-09 04:30
I tried to copy the old datasource folder to the new grafana instance: Same
error

2015-11-09 5:24 GMT+01:00 Andre Kasper <ein.kasper@gmx.de>:

**Comment by mtanda** [comment] 2015-11-09 08:23
hmm, sorry, I have no idea.
Would you capture the error message?

**Comment by A-Kasper** [comment] 2015-11-09 10:03
I would, if someone could tell me how
Am 09.11.2015 09:23 schrieb "Mitsuhiro Tanda" <notifications@github.com>:

**Comment by mtanda** [comment] 2015-11-10 01:23
Do you use Google Chrome?
If you use it, follow this document.
http://docs.grafana.org/installation/troubleshooting/

You can't see graphs too?
All templating expression, metrics(go_) or something, doesn't work?

**Comment by mtanda** [comment] 2015-11-10 02:18
I understand your situation, the error dialog is useless...
![template_error](https://cloud.githubusercontent.com/assets/224552/11052482/ad8a1fee-879b-11e5-9b87-0936c4a089cb.png)

**Comment by mtanda** [comment] 2015-11-10 02:20
@torkelo the error dialog doesn't handle error message correctly.
We need improve it.

![templating_error_report](https://cloud.githubusercontent.com/assets/224552/11052606/e1e03138-879c-11e5-95db-fe9232da60b7.png)

**Comment by mtanda** [comment] 2015-11-10 10:29
I fix the error dialog. It is already merged to master.
https://github.com/grafana/grafana/pull/3188

**Comment by mtanda** [comment] 2015-11-10 16:02
@torkelo sorry, I little confuse you.
Original issue what A-Kasper has isn't solved yet.
Please reopen this issue.

**Comment by valcryst** [comment] 2016-01-19 13:19
@mtanda yes there is still an issue, i just wanted to switch from 2.1.3 to 2.6 and templating is not useable anymore with prometheus using wildcards.

![error](https://cloud.githubusercontent.com/assets/12711020/12419624/9e2ef404-beb7-11e5-810e-34b75a8b4872.png)

**Comment by valcryst** [comment] 2016-01-19 13:41
The query is also different as before.. if i look into it with F12


![image](https://cloud.githubusercontent.com/assets/12711020/12420102/b516b3c0-beba-11e5-81f1-fce2fbc43096.png)

**Comment by mtanda** [comment] 2016-01-19 14:55
The metric query spec seems to be changed by this commit, https://github.com/grafana/grafana/commit/daee7970f33ad9548f73a3465f10dc9e853fe45e .

Please try "metrics(ffnode_*_clients)" .

**Comment by valcryst** [comment] 2016-01-19 15:40
Unfortunately that does not work, only difference is i dont get any Errors
but still not showing anything.

**Comment by mtanda** [comment] 2016-01-19 15:53
Ah, it is not wildcard, should specify regex.
"metrics(ffnode_.*_clients)"

**Comment by valcryst** [comment] 2016-01-19 16:01
@mtanda YOU ARE MY HERO! :)

works like a charm, thanks for help!
I think it would be nice to write this into the documentation for people who upgrade like me.

**Comment by mtanda** [comment] 2016-01-20 09:34
I create a PR to add explanation for user who upgrade Grafana.

**Comment by mtanda** [comment] 2016-01-21 16:09
PR is merged.

**Comment by mtanda** [comment] 2016-01-21 16:11
@torkelo This issue is solved.
Original issue is caused by incompatibility of datasource plugin.

**Closed** 2016-01-21 17:05 UTC
Labels: state: needs more detail
