### ISSUE TITLE
Value and gauge color mismatch in singlestat panel

### ISSUE THREAD

**Issue by marcmaz** [grafana/grafana#5759] opened 2016-08-09 12:02 UTC
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1
- What datasource are you using?
ZABBIX
- What OS are you running grafana on?
RHEL6
- What did you do?
I've created single stat panel with gauge and value. Defined thresholds are 26 and 30. Current value is 25.8.
- What was the expected result?
Because 25.8 is less than 26, both value and gauge should be GREEN.
- What happened instead?
Gauge is GREEN and value is YELLOW.

![image](https://cloud.githubusercontent.com/assets/20926405/17515184/2e3411fa-5e37-11e6-95e5-a05d7f8c5dd5.png)

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment] 2016-08-10 04:54
dupe of https://github.com/grafana/grafana/issues/5515

**Closed by torkelo** 2016-08-10 04:54 UTC
