### ISSUE TITLE
Short links: Add option to not clean up

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73514] opened 2023-08-18 18:00 UTC
**Why is this needed**:

We somewhat often run into users who are confused why their short links no longer work. I feel like a common use case is to create a link and embed it in a run book or other document that is not accessed within the 7 day time limit. The short link is removed, and link is not available when it is needed. The feature then seems broken at a critical time, which results in less trust of the product.

**What would you like to be added**:

There's a few options here that vary on how large of a feature we'd want to build for this.

1. An admin page of short links where those about to be deleted show yellow, and someone can "star" them or something to prevent them from being deleted (we have this same paradigm in explore's query history)
2. When you visit a page, if a short link exists with the same URL as what is visited, it bumps up the visited date even if it wasn't accessed via the short link
3. When you visit a page, if a short link exists with the same URL as what is visited, the short link button is yellow or something, indicating they should click to re-up the short link time
4. Warn the person creating the short link that unvisited links are deleted after a week (we already have an alert here, so we'd just need to add some text). They would probably paste it into a new tab to visit it to prevent the deletion from happening
5. Let the person creating the short link star it to prevent it from being deleted

**Who is this feature for?**

Anyone using short links that are not used within 7 days.

**Comment by ethirolle** [comment] 2023-08-18 18:38
Love these ideas❤

Mt two cents...

My gut is that it should not be too horribly taxing on the Grafana DB if this approach leads to more short-links being retained in that table (especially compared to some tables that can be truly huge and problematic, like annotations).

I especially like this idea (and I think we could combine it with one or more of the other ideas):
> Let the person creating the short link star it to prevent it from being deleted
I think it makes sense to provide an option at time of short-link creation, which educates the user, and gives a chance to make it a persistent link that never dies, if that is what they want.

Also, FYI: the same short link API is used for the new "Copy link to log line" feature (https://grafana.com/docs/grafana/next/explore/logs-integration/#copy-link-to-log-line)

**Comment by Elfo404** [comment] 2024-02-28 10:00
Related to #83009

**Comment by Elfo404** [comment] 2024-02-28 14:39
Closing this a duplicate of https://github.com/grafana/grafana/issues/83009

**Closed by Elfo404** 2024-02-28 14:39 UTC
Labels: type/feature-request, area/short-url, team/grafana-dashboards, crossroads-call
