### ISSUE TITLE
Data missing when querying longer periods from InfluxDB

### ISSUE THREAD

**Issue by d-beam** [grafana/grafana#30667] opened 2021-01-27 10:27 UTC
When I try to increase the querying period to more than two days, data goes lost as seen in the image. Whole series gets dropped, but also the data for last two days (in this example) disappear completely

![grafanaMissingData](https://user-images.githubusercontent.com/48758792/105977329-24da3b80-6089-11eb-8452-b709ca9866ee.jpg)

**Environment**:
- Grafana version: Grafana v7.3.5 (11f305f88a)
- Data source type & version: InfluxDB Version 2.0.0 (50964d7)
- OS Grafana is installed on: Some kind of public cloud host
- User OS & Browser: Win10, Google Chrome

**Comment by ivanahuckova** [comment] 2021-01-27 11:31
/duplicate of https://github.com/grafana/grafana/issues/30607

**Closed by ivanahuckova** 2021-01-27 11:31 UTC
