### ISSUE TITLE
bug: tooltip does not respect graph tooltip setting

### ISSUE THREAD

**Issue by uhthomas** [grafana/grafana#35572] opened 2021-06-11 14:40 UTC
**What happened**:

Despite having the "graph tooltip" setting set to "shared crosshair", the tooltip appears on all graphs.

**What you expected to happen**:

There should only be a shared crosshair, no tooltip.

**How to reproduce it (as minimally and precisely as possible)**:

Create a dashboard with some (new) time series and set the "graph tooltip" setting to "shared crosshair".

![image](https://user-images.githubusercontent.com/9749173/121703828-1ab25a00-cacb-11eb-9bed-d5ab0910adf6.png) 

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: v8.0.0
- Data source type & version: Time Series (new)
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Windows 10 (Chrome)
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment] 2021-06-11 21:56
looks like a duplicate of https://github.com/grafana/grafana/issues/35552

@uhthomas lets track that thread instead 👍

**Closed by zuchka** 2021-06-11 21:56 UTC
