### ISSUE TITLE
Grafana Timezone/Timeshift Bug when grouping by time(1d)

### ISSUE THREAD

**Issue by ninjarocketman** [grafana/grafana#11585] opened 2018-04-13 14:02 UTC
### What Grafana version are you using?
Version 4.6.3 (commit: 7a06a47)

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
16.04.1-Ubuntu

### What did you do?
Created a dashboard that accesses data stored in an influxdb database, UTC time format.
Set the dashboard time to local browser time. Local system time is currently CEST.

### What was the expected result?
The dashboard displays the results for UTC+2 because that is the time zone I am currently in.

### What happened instead?
**Actually two issues:**
1. The dashboard displays the results for UTC+1 (CET)

2. When aggregated and grouped by time(1d), the result is from 1am - 1am, so it delivers the time grouped by UTC midnight to midnight, but should do it either from _CEST midnight to midnight_ or _UTC 10pm -1 day till 10pm_.

For clarification some outputs:

database output for UTC:
```
> select sum(value) from "autogen"."testtrack" where testtag = 'abc' and time >= '2018-02-04T23:00:00Z' and time <= '2018-02-07T01:00:00Z' group by time(1d)
name: testtrack
time                 sum
----                 ---
...
2018-02-05T00:00:00Z 960918
2018-02-06T00:00:00Z 926282
...
```

database output for UTC+1 (so the timeshift is actually -1h):
```
> select sum(value) from "autogen"."testtrack" where testtag = 'abc' and time >= '2018-02-04T23:00:00Z' and time <= '2018-02-07T01:00:00Z' group by time(1d, -1h)
name: testtrack
time                 sum
----                 ---
...
2018-02-05T23:00:00Z 933437
2018-02-06T23:00:00Z 934796
…
```

Grafana output for Dashboard >Settings > Timezone > UTC:
```
Time | sum
2018-02-04 00:00:00 | 89.54 K
2018-02-05 00:00:00 | 960.92 K
2018-02-06 00:00:00 | 926.28 K
2018-02-07 00:00:00 | 487.00
```

and > Local browser time:
```
Time | sum
2018-02-04 01:00:00 | 89.54 K
2018-02-05 01:00:00 | 960.92 K
2018-02-06 01:00:00 | 926.28 K
2018-02-07 01:00:00 | 487.00
```

I can see in the network request, that the request in both cases is sent without a timeshift, therefore the result is “right” in terms of answering the sent request. But shouldn’t the “local browser time” - setting translate the request to the local browser time in reference to UTC?

The manual fix for this is to send a timeshift with every request, but I am building dashboards for various parameters with various panels and for staff working in different time zones.

Any ideas how I can fix this? Or is it a bug?
Maybe I am entirely misunderstanding the local browser time option - help is highly appreciated for both of the issues.

**Comment by rmiggily** [comment] 2018-08-27 07:54
This is not a bug. It actually is an[ expected behavior](https://docs.influxdata.com/influxdb/v1.6/query_language/data_exploration/#common-issues-with-basic-syntax) of InfluxDB. Could be resolved by #12245.

**Comment by ninjarocketman** [comment] 2018-09-22 20:27
Thank you @rmiggily for your reply. I know it's an expected behaviour of InfluxDB and a long needed feature.
My question, or issue, is with the Grafana time shift option: If I set the Grafana dashboard to local browser time I'd expect Grafana to manage the appropriate time shifts of the request for InfluxDB in relation to UTC, but it's not translated right. How can I fix this for different time zones via Grafana without having to manually calculate the difference between local browser time and UTC?

**Comment by rmiggily** [comment] 2018-09-24 12:49
@ninjarocketman Personally I add a hidden template variable with my preferred time zone shift and add them to my group by time clause as a time shift. However Daylight Savings is a head ache and I have to change this hidden template variable every 6 month. Influx DB has added a time [zone clause](https://docs.influxdata.com/influxdb/v1.6/query_language/data_exploration/#the-time-zone-clause) to resolve this issue. There is a pull request for adding this feature to Grafana but for some reasons has been blocked. You could +1 this [pull request](https://github.com/grafana/grafana/pull/12245#issuecomment-422810674) to speed up the process.

**Comment by michaelpiron** [comment] 2021-04-22 13:22
You can solve this by adding a timezone clause in your query in Grafana:
![image](https://user-images.githubusercontent.com/4469877/115721584-78a1ab80-a37e-11eb-8f4a-b18192cde252.png)

**Comment by ninjarocketman** [comment] 2021-05-12 08:30
@michaelpiron, how did you add the tz field to the UI? Could you show us how the query looks like in the query editor? Thank you.

**Comment by michaelpiron** [comment] 2021-05-12 09:32
This is how it looks in query editor:
`SELECT sum("Wh") FROM "forever"."energy" WHERE ("sensor" = 'import' OR "sensor" = 'local_used_solar' OR "sensor" = 'export') AND "client" = '$client' AND $timeFilter GROUP BY time(1d), "sensor" fill(null) tz('CET')`

I didn't explicitly add the timezone tz field in the UI, as far as I remember. I think it's linked to the version I'm using: I'm using Grafana v7.4.3 (010f20c1c8).

**Comment by PoloKltz** [comment] 2021-05-12 09:44
> @michaelpiron, how did you add the tz field to the UI? Could you show us how the query looks like in the query editor? Thank you.

@ninjarocketman 

Timezone can also be selected in the GROUP BY block (since v7.5 I think)

![image](https://user-images.githubusercontent.com/27371716/117954299-790fdf80-b349-11eb-8f17-d0579f65363d.png)

**Comment by gabor** [comment] 2021-05-20 13:23
@ninjarocketman is your issue solved by using the timezone-clause? if not, could you describe what is missing? thanks!

**Comment by ninjarocketman** [comment] 2021-05-26 10:49
Thank you very much for all your suggestions. The tz support of influxDB brings us closer to the truth, although we still experience discrepancies when it comes to grouping values by day. But I think that's more of an influx issue ... @gabor: in Grafana, if I set the dashboard time to the local browser time (currently UTC+2), Grafana's requests are still not enriched with a timeshift. However, this is the behaviour I expect from this feature. Maybe you can explain to me how the feature works or what it is supposed to do if not this?

**Comment by gabor** [comment] 2021-05-28 14:59
@ninjarocketman i'm not sure i understand the question, sorry.
could you describe a specific situation where things do not work the way you think they should?

i double checked what happens when i adjust the time-zone in the time-range selector, and it simply displays the result using that timezone.
for example:
- if your timezone is set to CEST, and you query for data for the last 3 hours, then (roughly based on when i am writing this), you get a time-series visualization that starts at 14:00 and ends at 17:00
- if you change the timezone setting to UTC, you get a visualization that starts at 12:00 and ends at 15:00

(in both cases the same data is drawn, because it is the same time range).
if i specify absolute-time-ranges, those seem to work ok too, in both CEST and in UTC.

**Comment by aocenas** [comment] 2021-06-16 08:46
Closing this as there is no new information, if there is any please comment and reopen

**Closed by aocenas** 2021-06-16 08:46 UTC
Labels: area/dashboard/timezone, area/datasource, datasource/InfluxDB, needs more info
