### ISSUE TITLE
Table filter funnels not clickable when panel title is empty

### ISSUE THREAD

**Issue by shauljacobspl** [grafana/grafana#64021] opened 2023-03-02 12:28 UTC
**What happened**:
I enabled column filtering from the table panel settings, left the panel title empty as not needed for GUI design. The filter funnel icons show but cannot be clicked.

**What you expected to happen**:
I should be presented with a drop-down menu to filter the chosen table column.

**How to reproduce it (as minimally and precisely as possible)**:
Enable column filtering on the table panel and then try click on the funnel icon at the top row of a column, Nothing happens.

**Anything else we need to know?**:
When I populate the panel title, the column filtering works. Seems it has be filled out otherwise the the panel title HTML element sits over the top row so you cannot sort or filter columns. Same outcome with using Edge web browser.

**Environment**:
- Grafana version: v9.3.4
- Data source type & version: MySQL (Bundled with Grafana)
- OS Grafana is installed on:
- User OS & Browser: Windows 10 and Google Chrome version 110.0.5481.177
- Grafana plugins: MySQL

**Comment by usmangt** [comment] 2023-03-03 08:50
Hi @shauljacobspl,

Thanks for opening this issue.

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by usmangt** [comment] 2023-03-14 12:06
Thanks @shauljacobspl 

Based on your steps of reproduction, I was also able to reproduce it on my test machine.

The behaviour I see is that;

-  if there is a Panel title => works fine as expected
- if there is NO Panel title => it will appear but when hovering the mouse to select the filter/funnel it hides and is not selectable.

Looks like a bug, will forward it to our Engineers

**Comment by shauljacobspl** [comment] 2023-03-14 12:10
> Thanks @shauljacobspl
> 
> Based on your steps of reproduction, I was also able to reproduce it on my test machine.
> 
> The behaviour I see is that;
> 
> * if there is a Panel title => works fine as expected
> * if there is NO Panel title => it will appear but when hovering the mouse to select the filter/funnel it hides and is not selectable.
> 
> Looks like a bug, therefore will forward it to our Engineers

Thanks for your help!

Kind Regards,
Shaul

**Comment by baldm0mma** [comment] 2023-03-21 21:11
Thanks @shauljacobspl and @usmangt for bringing this to our attention. I'm looking into it. :)

**Comment by usmangt** [comment] 2023-03-22 09:03
> this issue here is that the filter icons/buttons are mostly unclickable when the panel has no title? Am I correct in assuming this video sums up the issue?

Yes that is correct

**Comment by baldm0mma** [comment] 2023-03-28 13:59
Hey everyone; this issue has been addressed and will be fixed in v9.5; I'm going to close this issue. You can see a tad more about it from the founder themselves about it ->

https://github.com/grafana/grafana/pull/65396#pullrequestreview-1361114705

**Closed by baldm0mma** 2023-03-28 13:59 UTC
Labels: type/bug, area/panel/table
