### ISSUE TITLE
Text duplicates when adding annotations after changing datasource

### ISSUE THREAD

**Issue by ajnurjukan** [grafana/grafana#19852] opened 2019-10-16 09:45 UTC
*What happened**:
When I change datasource from grafana to simple json datasource text query appears two times.
![Screenshot from 2019-10-16 08-40-32](https://user-images.githubusercontent.com/37128135/66907867-581ac780-f00a-11e9-8722-4f3b830a470a.png)

**What you expected to happen**:
It should show text query only one time.

Grafana version: 6.4.2
Data source type & version: Simple JSON datasource
OS Grafana is installed on: Ubuntu 18.04
User OS & Browser:

**Comment by marefr** [comment] 2019-10-16 11:39
Duplicate of https://github.com/grafana/simple-json-datasource/issues/139

**Closed by marefr** 2019-10-16 11:40 UTC
