### ISSUE TITLE
[Feature Request] Support using math in beginning of SELECT in the Influx Query Editor

### ISSUE THREAD

**Issue by unixninja92** [grafana/grafana#6407] opened 2016-10-27 19:06 UTC
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1.1

- What datasource are you using?
Influxdb

- What OS are you running grafana on?
Official docker image

- What did you do?
I want to graph cpu % used by looking at the opposite of idle cpu %. Currently the influx query editor only lets you use math at the end of a select, but I need to use math at the beginning.
Example Query: 
`SELECT 100 - mean("usage_idle") FROM "cpu" WHERE "service" = 'this-service' AND "environment" = 'this-env' AND $timeFilter GROUP BY time($Aggregation) fill(null)`

**Comment by torkelo** [comment] 2016-10-27 20:03
dupe of https://github.com/grafana/grafana/issues/6299 

as temp workaround you can use `* -1 + 100`

**Closed by torkelo** 2016-10-27 20:03 UTC
