### ISSUE TITLE
Table Panel with Merge transform only allows first data type

### ISSUE THREAD

**Issue by calebedwards21** [grafana/grafana#37417] opened 2021-07-30 16:01 UTC
**What happened**:

I have a query for Splunk datasource:  `| makeresults count=10 | streamstats count | eval _time=_time-60*count ,field=if(count=5, "string", count)`

I change the 5th number to a string. There is two fields, count and field. Field is just a copy of count but has "string" in the spot where the number 5 is on the count column.

<table>
<tr><th>Table 1 Field 1</th><th>Table 1 Field 2</th></tr>
<tr><td>

| time | count |
|--|--|
| _time | 1 |
| _time | 2 |
| _time | 3 |
| _time | 4 |
| _time | 5 |
| _time | 6 |
| _time | 7 |
| _time | 8 |
| _time | 9 |
| _time | 10 |

</td><td>

|time|field| 
|--|--|
| _time | 1 |
| _time | 2 |
| _time | 3 |
| _time | 4 |
| _time | "string"|
| _time | 6 |
| _time | 7 |
| _time | 8 |
| _time | 9 |
| _time | 10 |

</td></tr> </table>

As soon as a merge transform is used, it combines the two columns along with time, but the "string" value in field is changed to NaN.

| time | count | fields|
| --- | --- | --- |
| _time | 1 | 1|
| _time | 2 | 2|
| _time | 3 | 3|
| _time | 4 | 4|
| _time | 5 | NaN|
| _time | 6 | 6|
| _time | 7 | 7|
| _time | 8 | 8|
| _time | 9 | 9|
| _time | 10 | 10|

**What you expected to happen**:

I expected for the merge to take place and the "string" value to remain as is. The columns should allow more than one data type after the merge takes place.

| time | count | fields|
| --- | --- | --- |
| _time | 1 | 1|
| _time | 2 | 2|
| _time | 3 | 3|
| _time | 4 | 4|
| _time | 5 | "string"|
| _time | 6 | 6|
| _time | 7 | 7|
| _time | 8 | 8|
| _time | 9 | 9|
| _time | 10 | 10|

**How to reproduce it (as minimally and precisely as possible)**:

1.  Create a table panel
2. Run a query that returns a column that has different data types
3. Perform a merge transform

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.5 and 8.0.6
- Data source type & version:
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows and Chrome
- Grafana plugins: Custom Splunk Plugin
- Others:

**Comment by tskarhed** [comment] 2021-08-03 12:32
I tried a quick replication using CSV and the testdata source. I think they all might be treated as strings, so it didn't work properly. Good job with the example data though! 

https://play.grafana.org/d/_-yrsNGnk/table-panel-with-merge-transform-only-allows-first-data-type-37417?orgId=1&from=1627972321216&to=1627993921216

**Comment by calebedwards21** [comment] 2021-08-13 16:53
@ashharrison90 - This is for a custom data source. Not the Grafana Splunk data source. The data source is setting the field type to "other" when I have more than one data type in a column (int and string in this case). When the field type is other, the merge just seems to be taking the first value type and casting the rest of the values to that type, which ends up in a string being converted to NaN.

**Comment by calebedwards21** [comment] 2021-08-13 16:58
![spl_nan](https://user-images.githubusercontent.com/31447494/129393888-eb148de7-a958-45fa-a9f2-ad6a94839649.PNG)

Here is the screenshot of the query with the merge transform selected.

**Comment by dprokop** [comment] 2021-10-07 07:59
@calebedwards21 could you please provide us the data of your panel from [Panel Inspect](https://grafana.com/docs/grafana/latest/panels/inspect-panel/#download-raw-query-results-as-csv)? Please make sure the data has no transformations and field config applied- you can set it in the Data options in the Panel Inspect.

I the meantime - since we couldn't reproduce this issue- I'm gonna close it. Feel free to reopen when you send us the data.

**Closed by dprokop** 2021-10-07 07:59 UTC
Labels: area/panel/table, needs investigation, area/transformations
