### ISSUE TITLE
Units: Can't choose 'd' as a custom unit

### ISSUE THREAD

**Issue by der-eismann** [grafana/grafana#25703] opened 2020-06-18 16:46 UTC
**What happened**: I tried to convert some old single stat panels that are showing uptimes in days to the new stat panel and discovered that I am unable to use `d` as a custom unit suffix.
This is quite unfortunate because you still can't prevent the regular `days` unit to change to weeks and using `days` as a custom unit is just wasting space.
The old system with prefix and suffix was so much easier to use... I was also not able to find a help button or a link to a documentation showing how to use prefixes, I only found this in the [release notes](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-6/#custom-data-units).

**What you expected to happen**: To be able to append a simple `d` as a custom unit.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a stat panel which has a value of 25 for example
- Try to use `d` as a custom suffix
- You will always get the regular `days` unit and it will round the value to weeks

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Prometheus 2.19.0
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Fedora 32 & Chrome 83

**Comment by torkelo** [comment] 2020-06-19 07:08
duplicate of https://github.com/grafana/grafana/issues/8781

**Closed by torkelo** 2020-06-19 07:08 UTC
