### ISSUE TITLE
Let graph legend lables be links that can be opened in new window via right click

### ISSUE THREAD

**Issue by mkaluza** [grafana/grafana#13863] opened 2018-10-28 22:50 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.3.1
### What datasource are you using?
Graphite
### What OS are you running grafana on?
Fedora 28

It would be nice if it was possible to make legend labels openable links that point to some url and can include fragments of metric name similar to aliasByNode. It would be useful for linking directly to monitored app's item's control panel.

Example:
metric: stats.*.input.*.speed (like stats.server1.input.123.speed where server1 and 123 are some IDs)
legend url pattern: http://our.control.interface/inputs/$1/$3 ($1/3 for the second/fourth node name)
result: label saying "speed.123" should have a link of http://our.control.interface/inputs/server1/123

To make it backwards compatible, the link should not be opened by left click (cancel event default action in onClick handler). The link should only work with right click -> open in new window/tab/etc.

**Comment by torkelo** [comment] 2018-10-29 15:47
duplicate of https://github.com/grafana/grafana/issues/1232

**Closed by torkelo** 2018-10-29 15:47 UTC
