### ISSUE TITLE
Clean way to remove "Forgot your password?" link on start page

### ISSUE THREAD

**Issue by mboehm21** [grafana/grafana#17443] opened 2019-06-05 06:12 UTC
**What would you like to be added**:

A config option to remove the "Forgot your password?" on Grafana's login page. If there is already one, please show me. The only way we found was to comment the block out in html which is not really clean.

**Why is this needed**:

In environment with LDAP-backend and an existing selfservice for password recovery it makes no sense to have this functionality in Grafana.

**Comment by marefr** [comment] 2019-06-05 14:20
Duplicate of #14246

**Comment by marefr** [comment] 2019-06-05 14:21
Fixed by #14232 and included in Grafana v6.

**Closed by marefr** 2019-06-05 14:21 UTC
Labels: area/backend, area/backend/auth, priority/nice-to-have, type/feature-request
