### ISSUE TITLE
[Feature Request] Allow to per-panel annotations

### ISSUE THREAD

**Issue by dluc** [grafana/grafana#6914] opened 2016-12-12 02:45 UTC
Currently annotations are configured in the dashboard settings, and apply to all the panels in the dashboard.

It would be useful to configure annotations on a graph panel (or any panel) instead. For instance let's assume I have a dashboard showing the temperature and humidity values in a building, I would like to see humidity warnings (=annotations) in the humidity graph, and temperature warnings in the temperature graph.

Some ways this feature could be achieved are described below.

**Option 1 - Enable annotations per panel**

Keep the current configuration, i.e. one configure the annotations in the dashboard configuration. However, on each panel one can choose which annotations to enable. For instance one configure "temperature" and "humidity" annotations in the dashboard, then enable temperature annotations in the temperature graph, and humidity annotations in the humidity graph.

**Option 2 - Override**

Keep the current behavior, plus extend the graph panel to override the dashboard annotations settings:
* Don't show annotations in this panel
* Use a different set of annotations in this panel (and enter settings)

**Option 3 - Configure annotations per panel**

Move the current annotations configuration to the panels where one wants to see them. Annotations are not configured on the dashboard anymore, but instead on each panel where required.

**Comment by bergquist** [comment] 2016-12-12 07:54
Closing since its a dupe of https://github.com/grafana/grafana/issues/717

**Closed by bergquist** 2016-12-12 07:54 UTC
