### ISSUE TITLE
LibraryPanel: stats panel with variables related to a library used in a loop row has default value different entering into page

### ISSUE THREAD

**Issue by acappelletti** [grafana/grafana#61999] opened 2023-01-24 14:36 UTC
I'm on Grafana 9.3.1 and I got strange behavior between variables and "stats panels" linked to libraries inside a loop in a ROW panel.  Seems that anything is related a library has a default value entering into page... before a force change using a combo menù on top.

**How to reproduce it (as minimally and precisely as possible)**:
Create a ROW panel and loop over a hidden variable.
In this row introducing a panel with a simle prometheus query from panel linked to a library.
This panel must have a query using the variable of loop.

Exemple:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/43847440/214322074-667e48e8-ca1f-466b-a276-961b19e6e84b.png">

the query...
topk (1,ag_details{ag_name="$agname", replica_server_name="$dbinstance", primary_replica="$dbinstance", job="$job"})

$agname is the loop variable used for ROW panel

<img width="577" alt="image" src="https://user-images.githubusercontent.com/43847440/214323575-ded5354d-95eb-42dc-8af2-30292eaecbc8.png">

after change from TOP menù... all is ok

<img width="222" alt="image" src="https://user-images.githubusercontent.com/43847440/214322461-315dd76d-7f00-4c31-b964-d3d120a1c622.png">

only entering into page I got stat panel with same values not like the ones that I put on hi-light above in this thread.

Alen

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: RHES
- User OS & Browser: Chrome

**Comment by dengaleev** [comment] 2023-03-09 19:40
We have the same bug, it is really hurts.

**Comment by dglushenok** [comment] 2024-01-23 07:53
FYI - the problem can be reproduced in v9.4.3, but not appear in v10.2.3 (have not checked intermediate versions).

**Comment by tonypowa** [comment] 2024-08-19 09:28
Closing this issue due to inactivity. Please feel free to reopen if the problem persists.

**Closed by tonypowa** 2024-08-19 09:28 UTC
Labels: needs more info, area/frontend/library-panels, area/dashboard/rows
