### ISSUE TITLE
Invalid Username Or Password: LDAP login issue

### ISSUE THREAD

**Issue by Siddhu1096** [grafana/grafana#14199] opened 2018-11-27 11:27 UTC
Read before posting: 
I am getting invalid username or password. It's working through "softerra ldap browser" software.
Followed the steps as described in grafana community..
Error:
 t=2018-11-27T05:19:47-0600 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"
t=2018-11-27T05:19:47-0600 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=10.96.19.162 time_ms=201 size=42 referer=http://10.96.26.54:3000/login

This is my ldap.toml file

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host =  "myldaphost"
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if ldap server supports TLS
use_ssl = false
# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify =false
# set to the path to your root CA certificate or leave unset to use system defaults
#root_ca_cert = ""
# Authentication against LDAP servers requiring client certificates
#client_cert = ""
#client_key = ""

# Search user bind dn
bind_dn = "CN=svc_wikijs_reader,OU=service accounts,DC=myhost,DC=local"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = 'mypassword'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter ="(sAMAccountName=%s)"

# An array of base dns to search through
search_base_dns = ["CN=Energy-APP-access,OU=EmailGroups,DC=myhost,DC=local"]

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by marefr** [comment] 2018-11-27 13:41
Duplicate of #14173

**Closed by marefr** 2018-11-27 13:42 UTC
