### ISSUE TITLE
Can't import GPG key with gpg/rpm --import without an error

### ISSUE THREAD

**Issue by djuarezg** [grafana/grafana#61491] opened 2023-01-13 13:32 UTC
`gpg --import https://rpm.grafana.com/gpg.key` reports the following on a Rocky 8 machine:

```
[root@test_machine djuarezg]# gpg --import gpg.key 
gpg: key 8C8C34C524098CB6: no public key - can't apply revocation certificate
gpg: key 9E439B102CF3C0C6: public key "Grafana Labs <engineering@grafana.com>" imported
gpg: Total number processed: 2
gpg:               imported: 1
```

PS:

```
[root@test_machine djuarezg]# rpm --import ./gpg.key  -vv
ufdio:       1 reads,    17154 total bytes in 0.000005 secs
ufdio:       1 reads,     3009 total bytes in 0.000003 secs
D: loading keyring from pubkeys in /var/lib/rpm/pubkeys/*.key
D: couldn't find any keys in /var/lib/rpm/pubkeys/*.key
D: loading keyring from rpmdb
D: opening  db environment /var/lib/rpm cdb:0x401
D: opening  db index       /var/lib/rpm/Packages 0x400 mode=0x0
D: locked   db index       /var/lib/rpm/Packages
D: opening  db index       /var/lib/rpm/Name 0x400 mode=0x0
D:  read h#     415 
Header SHA1 digest: OK
D: added key gpg-pubkey-6d745a60-60287f36 to keyring
D:  read h#     419 
Header SHA1 digest: OK
D: added key gpg-pubkey-2f86d6a1-5cf7cefb to keyring
D:  read h#     435 
Header SHA1 digest: OK
D: added key gpg-pubkey-c9d8b80b-54c2e310 to keyring
D: added subkey 0 of main key gpg-pubkey-c9d8b80b-54c2e310 to keyring
D:  read h#     438 
Header SHA1 digest: OK
D: added key gpg-pubkey-7457ccd1-58071431 to keyring
D: added subkey 0 of main key gpg-pubkey-7457ccd1-58071431 to keyring
D:  read h#     439 
Header SHA1 digest: OK
D: added key gpg-pubkey-168a1ea1-58138084 to keyring
D: added subkey 0 of main key gpg-pubkey-168a1ea1-58138084 to keyring
D:  read h#     467 
Header SHA1 digest: OK
D: added key gpg-pubkey-29111145-591cd381 to keyring
D: added subkey 0 of main key gpg-pubkey-29111145-591cd381 to keyring
D:  read h#     469 
Header SHA1 digest: OK
D: added key gpg-pubkey-d88e42b4-52371eca to keyring
D: added subkey 0 of main key gpg-pubkey-d88e42b4-52371eca to keyring
D:  read h#     630 
Header SHA1 digest: OK
D: added key gpg-pubkey-621e9f35-58adea78 to keyring
D:  read h#     745 
Header SHA1 digest: OK
D: added key gpg-pubkey-24098cb6-58875d52 to keyring
D: added subkey 0 of main key gpg-pubkey-24098cb6-58875d52 to keyring
D:  read h#     799 
Header SHA1 digest: OK
D: added key gpg-pubkey-2cf3c0c6-63b86a25 to keyring
D: added subkey 0 of main key gpg-pubkey-2cf3c0c6-63b86a25 to keyring
D: Using legacy gpg-pubkey(s) from rpmdb
error: ./gpg.key: key 2 import failed.
D: closed   db index       /var/lib/rpm/Packages
D: closed   db index       /var/lib/rpm/Name
D: closed   db environment /var/lib/rpm

```

**Comment by Kalarumeth** [comment] 2023-01-13 14:33
I have some issue, when try to check updating showing error of repository and gpg key,
I fix it changing repository and retrive new gpg key

Get new Grafana key
`sudo wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key`

Add new repo:
`echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list`

**Comment by jeremyspencer39171** [comment] 2023-01-13 14:35
I see the same thing in CentOS 7:
```
[root@host ~]# gpg --import gpg.key
gpg: key 24098CB6: no public key - can't apply revocation certificate
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 2CF3C0C6: public key "Grafana Labs <engineering@grafana.com>" imported
gpg: Total number processed: 2
gpg:               imported: 1  (RSA: 1)
```
I was using the repo (the old one at packages.grafana.com, I hadn't noticed the updated url) yesterday without issues, so presumably it's a recent change.

**Comment by kminehart** [comment] 2023-01-13 15:28
Hi, thanks for the feedback.

When we tested this we didn't run into any issues however some reports have been coming in about the revocation certificate on rpm distributions.

If this is blocking you, here's a link to the public key without the revocation certificate. https://rpm.grafana.com/gpg-2023-01-12.key

In the meantime, we'll continue to investigate our options. For more information on why we rotated this GPG key, visit our blog post: https://grafana.com/blog/2023/01/12/grafana-labs-update-regarding-circleci-security-updates/

**Comment by ashleykleynhans** [comment] 2023-01-13 15:46
The revocation certificate in the pubic key file is also not recognised by the Ansible `apt_key` module with Ubuntu 22.04 LTS.

```
fatal: [172.30.4.219]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "data": null,
            "file": null,
            "id": null,
            "key": null,
            "keyring": "/usr/share/keyrings/grafana.gpg",
            "keyserver": null,
            "state": "present",
            "url": "https://packages.grafana.com/gpg.key",
            "validate_certs": true
        }
    },
    "msg": "Unable to extract key from 'inline data'",
    "stderr": "gpg: WARNING: no command supplied.  Trying to guess what you mean ...\ngpg: standalone signature of class 0x20\ngpg: Signature made Tue Jan 10 18:15:35 2023 UTC\ngpg:                using RSA key 4E40DDF6D76E284A4A6780E48C8C34C524098CB6\ngpg: standalone revocation - use \"gpg --import\" to apply\n",
    "stderr_lines": [
        "gpg: WARNING: no command supplied.  Trying to guess what you mean ...",
        "gpg: standalone signature of class 0x20",
        "gpg: Signature made Tue Jan 10 18:15:35 2023 UTC",
        "gpg:                using RSA key 4E40DDF6D76E284A4A6780E48C8C34C524098CB6",
        "gpg: standalone revocation - use \"gpg --import\" to apply"
    ],
    "stdout": "pub:-:3072:1:9E439B102CF3C0C6:1673030181:1736102181::-:\nuid:::::::::Grafana Labs <engineering@grafana.com>:\nsub:-:3072:1:20106AEF79E58171:1673030181:1736102181:::\n",
    "stdout_lines": [
        "pub:-:3072:1:9E439B102CF3C0C6:1673030181:1736102181::-:",
        "uid:::::::::Grafana Labs <engineering@grafana.com>:",
        "sub:-:3072:1:20106AEF79E58171:1673030181:1736102181:::"
    ]
}
```

**Comment by mdebord-dlr** [comment] 2023-01-13 20:23
Confirming that this is change broke builds that use Ansible's [apt_key](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html) module. Using the workaround key (https://rpm.grafana.com/gpg-2023-01-12.key) for now, thanks to Grafana team for providing it.

**Comment by skibbipl** [comment] 2023-01-13 21:46
I'm getting similar errors with debian key.

**Comment by szykin** [comment] 2023-01-14 08:44
Either of urls
https://rpm.grafana.com/gpg-2023-01-12.key
https://apt.grafana.com/gpg.key
https://rpm.grafana.com/gpg.key
are unavailable, when trying these in the browser the only thing I get is 403 response with ```Sorry, the provided token is not valid``` message

**Comment by ashleykleynhans** [comment] 2023-01-14 08:54
@szykin All of those URLs work for me.

**Comment by szykin** [comment] 2023-01-14 09:18
@kminehart can you confirm that this behavior is explicitly set for russian ip adresses?

**Comment by solmoller** [comment] 2023-01-14 21:02
Raspberry Pi 4 here:
`$ sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://phoscon.de/apt/deconz buster InRelease                            
Hit:3 http://archive.raspberrypi.org/debian buster InRelease                   
Get:4 https://download.docker.com/linux/raspbian buster InRelease [33.6 kB]    
Get:5 https://packages.grafana.com/enterprise/deb stable InRelease [5,984 B]   
Err:5 https://packages.grafana.com/enterprise/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
Fetched 33.6 kB in 2s (22.3 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.grafana.com/enterprise/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
W: Failed to fetch https://packages.grafana.com/enterprise/deb/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
W: Some index files failed to download. They have been ignored, or old ones used instead.
`
Probably same issue
`wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key`
Seems to fix it

**Comment by ashleykleynhans** [comment] 2023-01-15 09:44
@solmoller its related but your error is actually expected when the public key is revoked, and you just need to install the new one to replace the old one.

We had a different issue where the revocation certificate that was included within the same file for the new public key was not being recognised, but the revocation certificate now seems to have been removed from the file containing the new public key and the issue is resolved.

**Comment by pulse-mind** [comment] 2023-01-15 09:55
Hi,

So you can do something like this (depending on your paths...) :
Have a look to your file path, in my example : 
```
less /etc/apt/sources.list.d/packages_grafana_com_oss_deb.list
```
Give me 
```
deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/grafana.gpg] https://packages.grafana.com/oss/deb stable main
```
So you can see the path to the gpg file and set it in the following curl command

```
curl https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/trusted.gpg.d/grafana.gpg
```
And then try again
```
sudo apt update
```

**Comment by Starfoxfs** [comment] 2023-01-16 08:36
That´s fine, but please change this in Tutorial to install Grafana on Raspberry.

[https://grafana.com/tutorials/install-grafana-on-raspberry-pi/](url)

Now i have this line working fine on my Raspberry:

`curl https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/trusted.gpg.d/grafana.gpg`

`echo "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list`

**Comment by tonypowa** [comment] 2023-01-16 09:38
> Hi, thanks for the feedback.
> 
> When we tested this we didn't run into any issues however some reports have been coming in about the revocation certificate on rpm distributions.
> 
> If this is blocking you, here's a link to the public key without the revocation certificate. https://rpm.grafana.com/gpg-2023-01-12.key
> 
> In the meantime, we'll continue to investigate our options. For more information on why we rotated this GPG key, visit our blog post: https://grafana.com/blog/2023/01/12/grafana-labs-update-regarding-circleci-security-updates/

@djuarezg Hi Daniel 👋 

please let us know if following the above blog post from Grafana solved the issue. If so, feel free to mark it as the answer. Otherwise, we are here for you 👍

**Comment by tomjensendk** [comment] 2023-01-16 10:13
Hi @tonypowa 

There are still issues with the writeup about Debian/Ubuntu where I'm getting the errors described in #61524

**Comment by djuarezg** [comment] 2023-01-16 10:29
@tonypowa It works again, thank you very much for your brief response!

**Comment by tonypowa** [comment] 2023-01-16 11:39
> Hi @tonypowa
> 
> There are still issues with the writeup about Debian/Ubuntu where I'm getting the errors described in #61524

closing this issue since it has been solved for the reporting user
we will address the writeup in your linked issue @tomjensendk  👍

**Closed by tonypowa** 2023-01-16 11:39 UTC
Labels: type/build-packaging

**Comment by tonypowa** [comment] 2023-01-16 13:52
> That´s fine, but please change this in Tutorial to install Grafana on Raspberry.
> 
> https://grafana.com/tutorials/install-grafana-on-raspberry-pi
> 
> Now i have this line working fine on my Raspberry:
> 
> `curl https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/trusted.gpg.d/grafana.gpg`
> 
> `echo "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list`

hi @Starfoxfs 
the debian  instructions should work (e.g. for raspbian users) but that depends on the distribution you have installed in your raspberry pi.

If this is not your case, or need more help, create a separate issue to give better visibility to the community 👍 

pro tip: refrain from using `apt-key add`. It has been [deprecated ](https://itsfoss.com/apt-key-deprecated/)for security reasons.

**Comment by Starfoxfs** [comment] 2023-01-17 09:36
Good morning,

thanks for the Info @tonypowa , the .KEY File is secure enough ? all other Files in `/usr/share/keyrings` are in GPG Format and not readable with normal Editor like Nano. The Grafana.key is readable.

**Comment by gabrielwpulido** [comment] 2023-02-01 00:45
Hello everyone, The only solution after struggling all this week was replacing the stable repo with beta repo. After that, it worked.

Cheers

**Comment by smarakdas314** [comment] 2024-03-28 12:06
Maybe unrelated but -alternative- for Debian12 is new DEB822 format

```
- name: Download and import grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/trusted.gpg.d/grafana.key
    checksum: sha256:58052c148058ace26dbd01ce057afa5709fb9d39c8a8ab16800be3f42fc02ab2

- name: Add repo using key from URL
  deb822_repository:
    name: grafana
    types: deb
    uris: https://apt.grafana.com/
    suites: stable
    components: main
    architectures: amd64
    signed_by: /etc/apt/trusted.gpg.d/grafana.key
    state: present
    enabled: true
```
