### ISSUE TITLE
Need SigV4 auth in 10.3.x version to use Elasticsearch and Opensearch datasource.

### ISSUE THREAD

**Issue by SricharanSundar** [grafana/grafana#83291] opened 2024-02-23 09:45 UTC
**Why is this needed**:
   While SigV4 authentication was previously available in Grafana versions up to 10.1.x for OpenSearch and Elasticsearch connections, it has been removed in subsequent versions starting from 10.3.x.
   But that is the recommended authentication from your side to use of AWS OpenSearch logs.

**What would you like to be added**:
   Add the SigV4 authentication again in grafana oss and cloud version to use. Please provide the feature back in the next release in either 10.3.x or 10.4.x.
   This auth mechanism enabling button also not available.

**Who is this feature for?**
   For all the Grafana Users and Developers who are using this feature currently and for some of the users who are all getting 401 unauthorized after the upgrade 10.3.1 for elasticsearch datasource and opensearch datasource plugin.

Please fix this soon provide those feature back in next releases.

**Comment by nightswimmings** [comment] 2024-02-23 10:35
It's already fixed and merged in trunk, we need to wait a couple of weeks for the release
https://github.com/grafana/grafana/issues/81294#issuecomment-1956211799

I am in the same situation, waiting for it, as 10.3 breaks our AWS logs datasource, but we need it in order to being able to migrate the new alert system as provisioning

**Comment by SricharanSundar** [comment] 2024-02-28 07:06
> It's already fixed and merged in trunk, we need to wait a couple of weeks for the release [#81294 (comment)](https://github.com/grafana/grafana/issues/81294#issuecomment-1956211799)
> 
> I am in the same situation, waiting for it, as 10.3 breaks our AWS logs datasource, but we need it in order to being able to migrate the new alert system as provisioning

So which authentication mechanism can replace the SIGV4 to use the AWS logs again from opensearch

**Comment by tolzhabayev** [comment] 2024-02-28 15:27
Closing as duplicate of https://github.com/grafana/grafana/issues/81294

**Closed by tolzhabayev** 2024-02-28 15:27 UTC
Labels: datasource/Elasticsearch
