### ISSUE TITLE
Floating sections in bar chart

### ISSUE THREAD

**Issue by perrydyball** [grafana/grafana#26930] opened 2020-08-11 15:20 UTC
Floating sections in bar chart

![image](https://user-images.githubusercontent.com/31008857/89896095-c43b6d00-dbd4-11ea-9b13-b31a0d7c594c.png)

When the individual series are displayed everything looks good - only when a series is shown in combination with the series with missing values do the others 'float'

I've tried the stacking null value and null value as zero options but made no difference.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: https://github.com/yesoreyeram/grafana-azure-datasource
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 - 2004 / Chrome latest
- Grafana plugins: None

**Comment by sakjur** [comment] 2020-08-11 16:37
Would it be possible for you to share the graph's configuration? Press the **panel top menu > inspect** and then select the JSON tab and share the content of **Panel JSON** and **Panel Data**. That would give us a sense of how to reproduce this. You can mask potentially sensitive information.

**Comment by Ultraseamus** [comment] 2020-08-11 16:40
This has been an issue for a couple years now, it is something I somewhat fixed in a private fork.

The bug happens when one of the series is there in one bucket, missing in the next, and eventually shows up again later (in this case it looks to be the series "VM"). It should be pretty easy to repro. Something you can do to avoid is to switch to displaying "Percentages".

My "fix" was adding a flag for ES's "Date Histogram" where part of the series creation would inject null values for those buckets (so it would line the series up, and add those null buckets in if the other series had them present). It's a workaround, not a true fix. When I looked into it, a true fix appeared complex. I have been hoping the React version of this panel would be new enough to not have this issue.

**Comment by perrydyball** [comment] 2020-08-12 08:00
@sakjur - here it is - nothing strange going on here - @Ultraseamus is right, it happens when a time series goes from values, to no values, and back to values again

`{
  "aliasColors": {},
  "bars": true,
  "dashLength": 10,
  "dashes": false,
  "datasource": "Azure Costs",
  "decimals": 2,
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "fill": 1,
  "fillGradient": 0,
  "gridPos": {
    "h": 9,
    "w": 8,
    "x": 16,
    "y": 24
  },
  "hiddenSeries": false,
  "id": 31,
  "legend": {
    "alignAsTable": true,
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "rightSide": true,
    "show": true,
    "total": true,
    "values": true
  },
  "lines": false,
  "linewidth": 1,
  "nullPointMode": "null",
  "options": {
    "dataLinks": []
  },
  "percentage": false,
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": true,
  "steppedLine": false,
  "targets": [
    {
      "azureAppInsights": {
        "appInsightsAppId": "",
        "query": "",
        "workspace": ""
      },
      "azureCostAnalysis": {
        "alias": "VM",
        "filters": [
          {
            "FilterType": "Dimensions",
            "Name": "ResourceGroupName",
            "Operator": "In",
            "Values": [
              "MY-VM-RG"
            ]
          },
          {
            "FilterType": "Dimensions",
            "Name": "MeterSubCategory",
            "Operator": "In",
            "Values": [
              "Virtual Machines BS Series Windows"
            ]
          }
        ],
        "granularity": "Daily",
        "grouping": [
          {
            "name": "MeterSubCategory",
            "type": "None"
          }
        ],
        "managementGroupId": "",
        "resourceGroupName": "",
        "scope": "Subscription",
        "subscriptionId": "3616xxxx-xxxxx-xxxxx-xxxx-xxxxxxxcaaa7",
        "subscriptionName": "My Subscription"
      },
      "azureLogAnalytics": {
        "query": "",
        "workspace": ""
      },
      "azureResourceGraph": {
        "query": "",
        "skip": 0,
        "top": 1000
      },
      "azureServiceHealth": {
        "subscriptionId": ""
      },
      "queryType": "Azure Cost Analysis",
      "refId": "A"
    },
    {
      "azureAppInsights": {
        "appInsightsAppId": "",
        "query": "",
        "workspace": ""
      },
      "azureCostAnalysis": {
        "alias": "SSD",
        "filters": [
          {
            "FilterType": "Dimensions",
            "Name": "ResourceGroupName",
            "Operator": "In",
            "Values": [
              "MY-VM-RG"
            ]
          },
          {
            "FilterType": "Dimensions",
            "Name": "MeterSubCategory",
            "Operator": "In",
            "Values": [
              "Premium SSD Managed Disks"
            ]
          }
        ],
        "granularity": "Daily",
        "grouping": [
          {
            "name": "MeterSubCategory",
            "type": "None"
          }
        ],
        "managementGroupId": "",
        "resourceGroupName": "",
        "scope": "Subscription",
        "subscriptionId": "3616xxxx-xxxxx-xxxxx-xxxx-xxxxxxxcaaa7",
        "subscriptionName": "My Subscription"
      },
      "azureLogAnalytics": {
        "query": "",
        "workspace": ""
      },
      "azureResourceGraph": {
        "query": "",
        "skip": 0,
        "top": 1000
      },
      "azureServiceHealth": {
        "subscriptionId": ""
      },
      "queryType": "Azure Cost Analysis",
      "refId": "B"
    },
    {
      "azureAppInsights": {
        "appInsightsAppId": "",
        "query": "",
        "workspace": ""
      },
      "azureCostAnalysis": {
        "alias": "Burst License",
        "filters": [
          {
            "FilterType": "Dimensions",
            "Name": "ResourceGroupName",
            "Operator": "In",
            "Values": [
              "MY-VM-RG"
            ]
          },
          {
            "FilterType": "Dimensions",
            "Name": "MeterSubCategory",
            "Operator": "In",
            "Values": [
              "windows server burst"
            ]
          }
        ],
        "granularity": "Daily",
        "grouping": [
          {
            "name": "MeterSubCategory",
            "type": "None"
          }
        ],
        "managementGroupId": "",
        "resourceGroupName": "",
        "scope": "Subscription",
        "subscriptionId": "3616xxxx-xxxxx-xxxxx-xxxx-xxxxxxxcaaa7",
        "subscriptionName": "My Subscription"
      },
      "azureLogAnalytics": {
        "query": "",
        "workspace": ""
      },
      "azureResourceGraph": {
        "query": "",
        "skip": 0,
        "top": 1000
      },
      "azureServiceHealth": {
        "subscriptionId": ""
      },
      "queryType": "Azure Cost Analysis",
      "refId": "C"
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "VM Scaling",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "transformations": [],
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "$$hashKey": "object:632",
      "decimals": 2,
      "format": "currencyGBP",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "$$hashKey": "object:633",
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}`

**Comment by perrydyball** [comment] 2020-08-12 11:58
I realize I had not shared the data - here it is...
[GrafanaData.zip](https://github.com/grafana/grafana/files/5062481/GrafanaData.zip)

**Comment by torkelo** [comment] 2020-08-12 12:38
If your stacking data make sure that every series has the same number of data points and that they align, and if you have no data point make it a 0 value

**Comment by sakjur** [comment] 2020-08-12 12:59
@torkelo Isn't that what "null value as zero" is supposed to do when you can't do that for your data sources? 🤔

**Comment by tofu-rocketry** [comment] 2020-09-14 12:32
@torkelo I've seen this issue reported a number of times. As @sakjur says, the "null value as zero" setting should be the thing to sort this. Could you just please fix it and make the panel behave as everyone seems to expect it to?

**Comment by torkelo** [comment] 2021-05-02 07:43
this should be fixed in later versions as the stack interpolation has been removed

**Closed by torkelo** 2021-05-02 07:43 UTC
Labels: needs investigation

**Comment by tofu-rocketry** [comment] 2021-05-04 08:05
> this should be fixed in later versions as the stack interpolation has been removed

@torkelo What version is that in as I can't see anything in the changelog?

**Comment by torkelo** [comment] 2021-05-04 14:14
@tofu-rocketry 

this is in the changelog for 7.4.0-beta1 
Graph: Fixes stacking issues like floating bars when data is not aligned. #29051, @torkelo

**Comment by tofu-rocketry** [comment] 2021-05-04 15:55
Thanks! That's good to see. I was only looking for "interpolation". :)

**Comment by mfrater** [comment] 2021-05-21 00:34
The stacking changes made in 7.4.0 broke my stacking graphs due to my data having missing values in different series. This is what my stacked graph looks like now.
![Annotation 2021-05-21 122859](https://user-images.githubusercontent.com/5498669/119064763-34163800-ba30-11eb-82c9-e9027fce7fb8.png). 
As mentioned above by @sakjur, its probably more a "null value as zero" issue, as changing null value setting to connected, null or null as zero makes no difference. Is anyone looking at fixing this? Is it scheduled in a release?
