### ISSUE TITLE
Grafana Playlist next/previous/hold via hotkey and scheduling

### ISSUE THREAD

**Issue by thestraycat** [grafana/grafana#18421] opened 2019-08-06 18:05 UTC
We have a use case to be able to skip through the playlist dashboards using arrow keys and there isn't any current functionality to allow this via hotkeys.

**Left Arrow** = Previous Dashboard in the rotation
**Right Arrow** = Next Dashboard in the rotation
**Up Arrow** = Toggle hold/resume on current dashboard
**Down Arrow** = Resume on current dashboard from Hold state if toggle wasn't an option?

I personally use HDMI CEC to control our instance, so arrowkeys are automatically mapped and available and would be good candidates to control the instance when in the playlist mode. 

(Also without looking through documentation new users would likely first attempt to use the arrow keys to control the playlist functionality without having to search for the hotkeys)

**Comment by torkelo** [comment] 2019-08-06 18:11
duplicate of https://github.com/grafana/grafana/issues/7724

**Closed by torkelo** 2019-08-06 18:11 UTC
Labels: area/playlist, type/feature-request

**Comment by thestraycat** [comment] 2019-08-06 18:13
Hi Torkelo, Is there anyway of mentioning the use of the arrowkeys, there quite specific to this particular request?

**Comment by torkelo** [comment] 2019-08-06 18:15
How we implement the keybindings (arrow keys or something else) is an implementation detail. 

But you can add that as a wish to that existing feature request
