### ISSUE TITLE
MSSql: Adds support for region annotations

### ISSUE THREAD

**Issue by Jens-H-Eriksen** [grafana/grafana#20918] opened 2019-12-06 07:47 UTC
As discussed in other issues like #10589 it would be a really nice enhancement if it is possible to create **_region annotations_** by datasources. As we uses MS SQL as our primary data source it is a highly wanted feature. The feature has already been added for Elasticsearch as a datasource #17602 and the way it is implemented with an optionally _Enddate_ would be much prefered.

**Comment by papagian** [comment] 2019-12-06 09:07
Duplicate of #10589

**Closed** 2019-12-13 16:25 UTC
Labels: area/backend, datasource/MSSQL, type/feature-request

**Comment by HenrikRolandHansen** [comment] 2020-12-09 20:54
is region annotation still not supported for Influxdb?
