### ISSUE TITLE
Feature Request: User custom notes/comments

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [grafana/grafana#3641] opened 2016-01-05 11:14 UTC
It shall be great if Grafana allow users to write notes/comments on certain plot or time series data whatever he/she observed, user written notes can be saved back to database, again brought back to dashboard/plots. 

these notes not necessary to be attached to each series of data, instead, it can be based on timeline. This helps users to remember to recollect/remember what they analyzed in past.    

![untitled](https://cloud.githubusercontent.com/assets/354710/12113821/5af68c16-b3cb-11e5-9791-037a9f05c4f0.png)

**Comment by volter** [comment] 2016-01-06 12:05
Possible duplicate of #1286

**Closed** 2016-01-07 16:23 UTC
