### ISSUE TITLE
Grafana directory listing ignores maxDataPoints

### ISSUE THREAD

**Issue by ivanpondal** [grafana/grafana#60645] opened 2022-12-21 18:14 UTC
**What happened**:

When consuming `-- Grafana --` datasource with `List public files` query, results are always limited to 100.

I tried putting a higher and lower `maxDataPoints` limit, both gets ignored and 100 is used in place.

**What you expected to happen**:

`maxDataPoints` should be value should be respected.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new dashboard.
2. Choose `-- Grafana --` datasource.
3. For query type choose `List public files`.
4. As `Path` put `img/icons/unicons`.

**Anything else we need to know?**:

Just for context, my plan was to use Grafana's icons for a custom plugin I'm currently developing (just the way GeoMap does for markers). That's how I noticed I was only getting the first 100 icons.

This issue impacts all plugins currently relying on Grafana's directory listing.

**Environment**:
- Grafana version: 9.2.5
- Data source type & version: Grafana
- OS Grafana is installed on: Using docker official image
- User OS & Browser: Mac OS, chrome

**Comment by usmangt** [comment] 2022-12-22 21:18
Hi @ivanpondal 

Thanks for opening this issue.

Did you select pagination as it seems to be disabled?

![image](https://user-images.githubusercontent.com/69509548/209227457-82e0bfa3-c860-40cb-811e-ffdfb407f627.png)

If incase this is not the case you are referring to (because I did not understand it correctly). Then please provide some screenshots or better a small screencast for more visibility.

Thanks.

**Comment by ivanpondal** [comment] 2022-12-23 12:54
Hey @usmangt ! Enabling pagination does not solve the issue since this is a backend issue.

Even with pagination enabled, it caps at 100 results:
<img width="1010" alt="Screenshot 2022-12-23 at 09 52 24" src="https://user-images.githubusercontent.com/1630370/209339312-1ddd9044-25d4-4d91-b482-16af92ec578e.png">

When setting `maxDataPoints` to a higher value:
<img width="371" alt="Screenshot 2022-12-23 at 09 53 28" src="https://user-images.githubusercontent.com/1630370/209339482-45016784-628b-4a5e-af54-f42845213f6e.png">

I still receive a total of 100 items.
<img width="533" alt="Screenshot 2022-12-23 at 09 54 42" src="https://user-images.githubusercontent.com/1630370/209339563-fd216ed2-30bd-4c81-8d38-1f4c807d5df4.png">

**Comment by usmangt** [comment] 2023-01-03 14:48
Hi @ivanpondal ,

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

I have tried it on my machine (by following your initial steps but seems there is something I am missing)

Thanks

**Comment by ivanpondal** [comment] 2023-01-09 16:00
Hey @usmangt 

Here is a video on how to reproduce the issue. I couldn't share the dashboard due to missing permissions to save.

https://user-images.githubusercontent.com/1630370/211351707-e7f677f4-d55b-4e74-a257-4c22b7a7ed64.mp4

**Comment by usmangt** [comment] 2023-01-16 22:58
Thanks for the screencast.

I will forward this issue to our Engineers as they might be able to tell in more detail.

**Comment by gelicia** [comment] 2024-02-29 13:42
This looks to have been fixed by #76414 https://github.com/grafana/grafana/pull/76414/files#diff-f1386ecf8e451a84d16e901593385dbecf86e95242c70084a41c1c43f37830a9L173

Closing.

**Closed by gelicia** 2024-02-29 13:42 UTC
Labels: area/dashboard, triage/needs-confirmation, datasource/Grafana
