### ISSUE TITLE
[Bug] Table panel header overflow in mobile view

### ISSUE THREAD

**Issue by j-white** [grafana/grafana#9322] opened 2017-09-21 11:11 UTC
This was discovered and is reproducible on Grafana v4.5.1.

To reproduce:
* Using the built-in table panel render a table with many columns and enable scrolling in the paging options.
* Render the dashboard on a mobile device or using a smaller resolution

Expected results:
* Use the vertical and horizontal scroll to see the complete table contents

Actual results:
* The table header overflows into the right of the panel and is no longer aligned with the columns

![image](https://user-images.githubusercontent.com/1379749/30692897-58261260-9e9b-11e7-8ff7-8fa179ea006a.png)

**Comment by j-white** [comment] 2017-09-21 11:11
Disabling the 'position: absolute' style in the 'table-panel-table-header-inner' class fixes the problem, but I'm not sure if there are any other consequences: https://github.com/grafana/grafana/blob/f1036a93828e497f0f469a830aa1b46146851621/public/sass/components/_panel_table.scss#L126

**Comment by torkelo** [comment] 2017-09-21 11:53
it will make fixed header stop working for table panel. dupe of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2017-09-21 11:53 UTC
