### ISSUE TITLE
[Bug] - After upgrading to Grafana 4.6.0 status panel can't load and I receive 401 unauthorized error

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#9730] opened 2017-10-30 16:08 UTC
Please include this information:
- What Grafana version are you using?
4.6.0
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Amazon Linux AMI
- What did you do?
After upgrading to Grafana 4.6.0 I tried to load a dashboard which includes status panel and I received the following error: 
"Plugin Error
Fetch error: 401 Unauthorized Instantiating https://xxxx:4000/public/plugins/vonage-status-panel/module.js Loading plugins/vonage-status-panel/module"

**Comment by daniellee** [comment] 2017-10-30 17:39
Dupe of this #9692 ? Are you using AuthProxy?

**Comment by dudusakharovich** [comment] 2017-10-30 17:43
@daniellee  - No, I'm using Basic auth.
Can you please help me resolve this issue ? I have important dashboards which are using status panel that are currently not working due to this issue.

**Comment by daniellee** [comment] 2017-10-30 18:41
Of course. This is due to a breaking change in Grafana 4.6 for two published plugins and this plugin is one of them. Looks it might be fixed soon in the plugin, see:

https://github.com/Vonage/Grafana_Status_panel/issues/81

**Closed by daniellee** 2017-10-30 18:41 UTC
Labels: comp: plugins

**Comment by dudusakharovich** [comment] 2017-10-30 19:02
@daniellee - What did you mean by your comment "The quickest way to fix this is to copy and paste these files into the plugin and adapt them for the Status Panel plugin" ?

What should I do exactly ?

**Comment by daniellee** [comment] 2017-10-30 19:43
That comment was for the plugin maintainers. The link is to the GitHub repo for the plugin. It is not a Grafana issue.

**Comment by dudusakharovich** [comment] 2017-10-30 20:04
@daniellee  - So basically I don't really have what to do to fix it , maybe just perform a downgrade ?

**Comment by daniellee** [comment] 2017-10-30 20:28
@dudusakharovich your options are:
- downgrade Grafana
-wait a few days and hope a new version of the plugin comes out (it looks like it will be soon)
-uninstall the plugin and git clone the PR into your data/plugins directory and see if it works

**Comment by dudusakharovich** [comment] 2017-10-30 22:22
10x @daniellee.

What is the best method to downgrade Grafana without loosing my data (Data sources, dashboards and etc.) ?
Is there a ready written process for it ?
Or if I yum remove it and reinstall it the data will be kept ?

**Comment by daniellee** [comment] 2017-10-31 11:17
Downgrading is a bit tricky if you did not do a backup of your database before upgrading. When you start the Grafana server after an upgrade, it runs a database migration and adds new tables/columns etc. 

But I see in the other thread that the database seemed to be ok after a downgrade. I think you will have an extra table for the new annotations feature but I don't think we removed anything between 4.5.2 and 4.6.0.
