### ISSUE TITLE
Grafana Cloudwatch datasources not not being loaded/updated 

### ISSUE THREAD

**Issue by dbarranco** [grafana/grafana#19932] opened 2019-10-21 10:45 UTC
**What happened**:
Currently have several Grafana Cloudwatch datasources added via ConfigMaps into a grafana StatefulSet in Kubernetes.
When starting Grafana setting the log level to `debug`, I can see it is loading all the provisioning files:

```
t=2019-10-21T10:21:21+0000 lvl=dbug msg="updating datasource from configuration" logger=provisioning.datasources name=cloudwatch-aws-studio
```

The `cloudwatch-bitnami-studio` is a Cloudwatch datasource that was recently updated (name change and new AWS API keys set via env var in Grafana).

What I would expect is that Grafana has correctly updated that datasource in the UI with a kick of the pod, however, I still see the old datasource:

![Screen Shot 2019-10-21 at 12 37 14 PM](https://user-images.githubusercontent.com/9199512/67198563-854ae980-f3ff-11e9-91c3-479975fcea1f.png)

And if I try to test the datasource to check if it works or not, I don't get any test result.
Doing a quick inspect with the Google Chrome tools I can see that:

![Screen_Shot_2019-10-21_at_12_37_59_PM](https://user-images.githubusercontent.com/9199512/67198675-c2af7700-f3ff-11e9-96db-70e405dbd554.png)

****
Some interesting details:

This Grafana instance has a sqlite local database to change the dashboards that have not been migrated to the provisioning method yet.
If I get the sqlite file and I check it on my workstation I still see the old datasource there. Removing this old datasource in the database and replacing the database file in the Grafana pod and restarting it won't change anything :/ 

**What you expected to happen**:
I would expect Grafana to correctly update the Cloudwatch datasource, or create a newer one (as the name changed).

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a Grafana pod, provision a datasource for Cloudwatch setting the AWS API keys via env vars and then update that datasource.

**Anything else we need to know?**:
The Cloudwatch datasource I'm setting:

```
# config file version
apiVersion: 1

datasources:
  - name: cloudwatch-aws-studio
    type: cloudwatch
    jsonData:
      authType: credentials
      defaultRegion: us-east-1
```

**Environment**:
- Grafana version: `6.1.6`
- Data source type & version:
- OS Grafana is installed on: Debian
- User OS & Browser: no user (`1001`)
- Grafana plugins: default ones
- Others: I'm using the bitnami/grafana container.

**Comment by marefr** [comment] 2019-10-21 11:50
Duplicate of #17804

**Comment by marefr** [comment] 2019-10-21 11:50
You have to either restart Grafana for datasource provisioning to reload or either use the HTTP api to reload the config, see https://grafana.com/docs/http_api/admin/#reload-provisioning-configurations.

**Closed by marefr** 2019-10-21 11:50 UTC
