### ISSUE TITLE
Bar Gauge Panel - Increasing/decreasing sort order

### ISSUE THREAD

**Issue by kolminux** [grafana/grafana#27230] opened 2020-08-26 16:27 UTC
Add a “Sort order: Increasing/Decreasing” in the Panel->Display section of the Bar Gauge Panel plugin.

This feature is useful when monitoring parameters which deserve attention prioritizing the max or min, such as temperature or pressure.
When sorted randomly, it's difficult to see which are the highest or lowest.

![image](https://user-images.githubusercontent.com/70282028/91330369-b32b5800-e79f-11ea-8e92-592cff928f69.png)

**Comment by torkelo** [comment] 2020-08-26 17:18
duplicate of https://github.com/grafana/grafana/issues/17245

**Closed by torkelo** 2020-08-26 17:18 UTC
