### ISSUE TITLE
[Bug] Repeating panels shows empty panels when value is zero or null and you try to hide them

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#8712] opened 2017-06-26 21:50 UTC
Please include this information:
- What Grafana version are you using? 4.3.2
- What datasource are you using? Graphite
- What OS are you running grafana on? CentOS 7
- What did you do? Setup a repeating panel and selected hide null and zero values
- What was the expected result? Panels to not show if their value was null or zero
- What happened instead? Empty panels with no metric name even in the legend showed up

**Comment by daniellee** [comment] 2017-06-27 10:34
dupe of #4470

A PR was submitted for this but did not get merged due to lack of updates: #7529

**Closed by daniellee** 2017-06-27 10:34 UTC
