### ISSUE TITLE
Explore / Logs: scroll to top breaking top button area position

### ISSUE THREAD

**Issue by xpader** [grafana/grafana#79196] opened 2023-12-07 02:36 UTC
### What happened?

When toggle top search bar, and click log area "Scroll to top" button, query button area will move up a little position, and toggle top search bar will won't come back.

### What did you expect to happen?

Click "Scroll to top" not effect any component position, just scroll to top.

### Did this work before?

No

### How do we reproduce it?

1. In Explore page, click "Toggle top search bar" at right top corner.
2. Query logs, and click "Scroll to top" at right bottom corner.
3. Run query bottom bar will move up little position.

### Environment (with versions)?

Grafana: 10.2.2
OS: MacOS Ventura 13.6.1
Browser: Edge, Firefox

### Grafana platform?

Docker

### Datasource(s)?

Loki 2.9.2

**Comment by tonypowa** [comment] 2024-01-03 14:21
hi @xpader 

thanks for reporting this bug

i have reproduced it and recorded it for clarity 

![lokito2](https://github.com/grafana/grafana/assets/45235678/be5951aa-1d90-4784-b62d-e38bc2cd7353)

**Comment by xpader** [comment] 2024-01-08 06:50
@gelicia Still exists on play.grafana.org, but better.

**Comment by gelicia** [comment] 2024-01-08 16:32
@xpader do you have any other replication steps you can share?

Here's what I'm doing, please let me know what you're seeing thats different. Tried in FF and Chrome.
1. Go to [this logs link](https://play.grafana.org/explore?schemaVersion=1&panes=%7B%22yZT%22%3A%7B%22datasource%22%3A%22grafanacloud-alert-state-history%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%7Binstance_id%3D%5C%2235611%5C%22%7D+%7C%3D+%60%60%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22grafanacloud-alert-state-history%22%7D%2C%22editorMode%22%3A%22builder%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-6h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1)
2. Click "Toggle top search bar" to hide it
3. Scroll down about a third of the page to see the "Scroll to top" button
4. Click it
5. Run query button is not cut off, toggling the top search bar does not cut it off.

**Comment by xpader** [comment] 2024-01-09 03:09
@gelicia Yes, this is the steps to replication.
The buttons cut off in firefox, move a little position in chrome, edge.

**Comment by gelicia** [comment] 2024-01-09 15:53
@xpader @tonypowa My apologies, I'm still not understanding. Here's a video of it on FF 121.0 on OSX. Does it look like what you're seeing? If so, can you let me know with a timecode or something what I'm supposed to be seeing? 

https://github.com/grafana/grafana/assets/1533128/58252510-f13d-4e08-bb52-cd4f0cad2e94

**Comment by xpader** [comment] 2024-01-10 03:21
@gelicia Look at my video, you'll see what's going on.

https://github.com/grafana/grafana/assets/8629617/ccfd7e89-aa65-4579-a701-9184f5e43a1c

**Comment by xpader** [comment] 2024-01-10 03:22
Even if you refresh the entire page, it will not recover.

**Comment by gelicia** [comment] 2024-01-10 14:36
Thanks to @Elfo404 for the tip - this is reproducible in OSX only if you select the "Show Scroll bars > Always" option in system settings.

**Comment by gelicia** [comment] 2024-01-10 17:52
Logs folks, it looks like there's a problem with the container height on this button - the scroll to top button does not show when the top search bar is showing. This is happening when the `exploreScrollableLogsContainer` feature flag is off. ([src](https://github.com/grafana/grafana/blob/main/public/app/features/explore/Logs/Logs.tsx#L532C32-L532C46))

Something with the alignment is cutting off the top of the run queries button. It seems to happen with the scrollbar showing, so for OSX, you will need to turn that setting on. 

![Screenshot 2024-01-10 at 11 03 33 AM](https://github.com/grafana/grafana/assets/1533128/d29e641d-fa9b-4acc-93ab-970d8e77f665)

**Comment by ifrost** [comment] 2024-02-22 09:11
Logs Container scrolls to the [top of the logs container](https://github.com/grafana/grafana/blob/ff5b0f7bd8605f8e0f347c64c96e7953842cea8e/public/app/features/explore/Logs/Logs.tsx#L774) with the scrolling defined [here](https://github.com/grafana/grafana/blob/ff5b0f7bd8605f8e0f347c64c96e7953842cea8e/public/app/features/explore/Logs/Logs.tsx#L550). It seems the logic is nothing funky and in theory it should not be affecting the Explore's bar so might be worth checking on our end. Also it works fine with Content Outline so maybe we could provide a consistent way of scrolling to the top of the component. 

BTW. @grafana/observability-logs do we still need this button since we have Content Outline? It was removed from Trace View (https://github.com/grafana/grafana/pull/77158)

**Comment by gelicia** [comment] 2024-12-12 14:05
This looks to have been fixed. Closing.

**Closed by gelicia** 2024-12-12 14:05 UTC
Labels: type/bug, prio/low, area/explore
