### ISSUE TITLE
[Feature Request] Add support for performing math across multiple fields to InfluxDB query builder

### ISSUE THREAD

**Issue by pprkut** [grafana/grafana#4710] opened 2016-04-14 14:55 UTC
Currently, Grafana (2.6) supports math functionality with the field on the left side within the InfluxDB query builder. I.e. it can build queries like

```
SELECT mean("field") / 100 AS "field" FROM "measurement" WHERE "tag" = 'value' AND $timeFilter GROUP BY time($interval) fill(null)
```

It would be nice to also have support for math with fields on both sides, for example something like

```
SELECT mean("field1") + mean("field2") + mean("field3") AS "field" FROM "measurement" WHERE "tag" = 'value' AND $timeFilter GROUP BY time($interval) fill(null)
```

**Comment by deric** [comment] 2016-04-17 12:02
:+1:

**Comment by roycepope** [comment] 2017-04-22 01:29
This would be amazing!

**Comment by dugwood** [comment] 2018-04-23 02:58
Isn't it a duplicate of #3552?

**Comment by torkelo** [comment] 2020-11-12 12:05
you can do this in the raw query build mode, with the editor it becomes hard to do

**Closed by torkelo** 2020-11-12 12:05 UTC
Labels: area/datasource, datasource/InfluxDB, help wanted, priority/nice-to-have, type/feature-request
