### ISSUE TITLE
Docker Grafana latest tag comes as 8.1.6

### ISSUE THREAD

**Issue by fate8383** [grafana/grafana#62589] opened 2023-01-31 13:57 UTC
Docker Grafana latest tag comes as 8.1.6 version....I use main tag but it also comes with 9.4.0 which honestly all I want is latest stable 9.3.6. I can use the version tag but update notifications are important for me so using versions won't do for me.

**Comment by nappy** [comment] 2023-01-31 14:50
In an effort in switching to main, I noticed main being on [v9.4.0-100060pre (c3b476e1dc)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md)

This does not look right either, does it?

**Comment by dsotirakis** [comment] 2023-01-31 14:52
Oh wow, don't have the slightest clue as of what happened, I checked the docker manifests and they were all correct 😬 
I'll will fix now, and let you know all about the progress.

**Comment by nappy** [comment] 2023-01-31 14:58
Just to give you a potential hint on finding the cause, the version which was latest before might have already been a downgrade too, because I started having issues with the variables using a flux2 query on the dashboard. With 8.1.6 everything was broken and therefore I noticed...

**Comment by dsotirakis** [comment] 2023-01-31 15:05
@nappy thanks, the initial issue was that accidentally the `9.4.0-beta1` release we created today was marked as latest for a little while and that's why we needed to re-push latest and we kinda broke it 😓 
But it's interesting, what you found - if/when you have some time we'd appreciate you creating an issue explaining what was broken for you in the `9.4.0-beta1` release so we can make sure it won't come together with `9.4.0` 🙏 

Meanwhile, fix incoming!

**Comment by fate8383** [comment] 2023-01-31 15:08
Main comes as 9.4 works fine for all my dashboards (influx v1, v2 and Prometheus sourced many dashboards). I will still go back to latest once fixed. I need stable version in production. Thanks

**Comment by dsotirakis** [comment] 2023-01-31 15:19
All, @fate8383, @nappy, @HitkoDev the issue should be fixed by now - latest should point to `9.3.6`.
Please have a look and let me know if things still seem weird on your end. If everything is okay, feel free to close the issue.
Thanks for escalating quickly and sorry for the fuss 🙏

**Comment by chvvkumar** [comment] 2023-01-31 15:23
> All, @fate8383, @nappy, @HitkoDev the issue should be fixed by now - latest should point to `9.3.6`. Please have a look and let me know if things still seem weird on your end. If everything is okay, feel free to close the issue. Thanks for escalating quickly and sorry for the fuss 🙏

I just pulled latest and got v.9.3.6. Thanks for fixing this quickly!

**Comment by fate8383** [comment] 2023-01-31 15:24
Fixed, thanks

**Closed** 2023-01-31 15:38 UTC
Labels: type/bug, prio/high, area/docker
