### ISSUE TITLE
Gauge Plugin: HTML div element with the value is duplicated at each dashboard refresh

### ISSUE THREAD

**Issue by mihailescu2m** [grafana/grafana#21156] opened 2019-12-18 03:46 UTC
**What happened**:
At a dashboard refresh, there is a new HTML div created for the value, and the old one is not removed. Divs are stacked on top of each other and the value becomes blurry.

**What you expected to happen**:
Only one div to display the gauge value

**How to reproduce it (as minimally and precisely as possible)**:
* create a gauge panel
* refresh dashboard

**Environment**:
- Grafana version: grafana:6.5.1-ubuntu (docker)
- Data source type & version: InfluxDB 1.7 (docker)
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: grafana-piechart-panel, natel-plotly-panel, blackmirror1-singlestat-math-panel, btplc-trend-box-panel, marcuscalidus-svg-panel, michaeldmoore-multistat-panel, yesoreyeram-boomtable-panel, ryantxu-ajax-panel, grafana-influxdb-flux-datasource, fetzerch-sunandmoon-datasource, andig-darksky-datasource, simpod-json-datasource

![Capture](https://user-images.githubusercontent.com/4421731/71054192-fb21c600-21a0-11ea-8844-8f277978edb2.JPG)

**Comment by dprokop** [comment] 2019-12-19 07:39
@mihailescu2m thanks fo reporting this. Is this sth that you can reproduce consistently? I've tried reproducing this issue but couldn't see this happening.

**Comment by mihailescu2m** [comment] 2019-12-21 07:26
Yes I can reproduce consistently.
Started a new dashboard, and the issue started to appear after adding a panel using Singlestat Math plugin which was set to show as gauge. So the issue seem to be because of Singlestat Math gauge, but it affects only the official gauge plugin - i.e. the singlestat math is ok.

**Comment by ryantxu** [comment] 2019-12-23 21:57
Interesting!  We have various reports of this behavior, but have been unable to reproduce.  I bet `Singlestat Math` (or some other plugin) imports something that affects how this works.

@mihailescu2m -- what other plugins do you have installed?

**Comment by torkelo** [comment] 2020-05-28 07:31
duplicate of https://github.com/grafana/grafana/issues/17939

**Closed by torkelo** 2020-05-28 07:31 UTC
Labels: area/frontend, needs more detail
