### ISSUE TITLE
Explore UI input lag

### ISSUE THREAD

**Issue by bjor-joh** [grafana/grafana#59044] opened 2022-11-21 13:31 UTC
**What happened**:
When using the explore UI to explore metrics in prometheus I'm getting input lag. 
I start typing and at first it's snappy. But once I've queried a couple of metrics things start to become slow. 
I start typing and it can take several seconds before the letter appear in the text input field. It's not autocomplete that is slow, it feels like it's the UI itself, the characters don't appear as I type. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Search for and visualize a couple of metrics in the explore UI.
2. Try searching for another metrics
3. Things start to slow down

**Anything else we need to know?**:

I tried on different computers and multiple browsers. I also tried incognito mode to ensure it was not a chrome plugin causing the issue. 

When the slowness happens I notice a spike in `Google Chrome Helper (Renderer)` process when I look in the mac Activity Monitor.
I see no errors in the grafana logs and the grafana CPU and memory usage is very low. 

When I refresh the browser things appear snappy again, until after a couple of queries and then the pattern repeats. 

**Environment**:
- Grafana version: 9.2.5
- Data source type & version: prometheus: 2.37.1
- OS Grafana is installed on: kubernetes (GKE) 1.23
- User OS & Browser: MacOS 13.0(Ventura)
- Grafana plugins: grafana-github-datasource, grafana-bigquery-datasource, savantly-heatmap-panel, yesoreyeram-infinity-datasource
- Others:

**Comment by itsmylife** [comment] 2022-11-29 10:00
Hi @bjor-joh, Thanks for taking the time and creating the issue. 
Could you please share some more information? 

- The browser version you are using
- Did you experience the same thing with the different browsers?
- Do you have any other plugins/datasources installed on grafana?
- What metrics are you typing? Anything specific or any metric causes this?
- If possible, could you please provide a .har file so we will be able to observe closely?

Thanks for the details in advance and sorry for the long list of requests.

**Comment by bjor-joh** [comment] 2022-11-30 07:57
Hi @itsmylife, thanks for getting back. 
Please find additional info below

* Browser version: chrome(107.0.5304.110 (Official Build) (x86_64)) and firefox(107.0.1 (64-bit))
* Yes, tried both firefox and chrome
* We have theses plugins/datsources installed/configured:
  *  https://grafana.com/grafana/plugins/grafana-github-datasource/
  * https://grafana.com/grafana/plugins/grafana-bigquery-datasource/
  * https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/
  * https://grafana.com/grafana/plugins/savantly-heatmap-panel/
  * Tempo (core)
  * Jaeger (core)
  
Besides that it's only `core` plugins, guessing these are shipped by default with grafana.

It feels like it's happening for all metrics, but it seems to be more severe with queries resulting in a lot of returned time series. Here's a concrete example. 
We are using elasticsearch and fetching metrics via this exporter https://github.com/prometheus-community/elasticsearch_exporter.  

This metric `elasticsearch_breakers_estimated_size_bytes` returns 1302 rows for the last 1 hour. After fetching we experience input lag. However this query `sum(elasticsearch_breakers_estimated_size_bytes)` reduces the returned rows to 62 and we experience no input lag. So there seems to be a correlation between returned rows and the issue we are experiencing. 

I can't share the HAR file unfortunately since it contains sensitive data. 
I've attached a screeenshot of what the developer console looks like. I went through the same scenario as describe above

1. query `elasticsearch_breakers_estimated_size_bytes`
2. experiencing lag
3. sum(elasticsearch_breakers_estimated_size_bytes)
4. no lag

From what I can see things are snappy on the network. 

<img width="1678" alt="grafana_screenshot" src="https://user-images.githubusercontent.com/53463827/204739138-6ceaa3ef-47ef-4c97-85c0-518cbddd0760.png">

**Comment by gtk-grafana** [comment] 2022-11-30 13:18
@bjor-joh We're having a hard time reproducing this issue, and it looks like the API calls to get the data are coming back quickly. Can you attach a video of the lag you are seeing in the UI, and a CPU profile while you're experiencing the input lag? 

Also if you run this query directly in the native prometheus UI do you see any lag?

**Comment by bjor-joh** [comment] 2022-12-01 12:53
@gtk-grafana 
Please find requested videos and profile attached. 
No I'm not experiencing the same issue in the prometheus UI. I attached a video of that as well to showcase the difference. 

I did an additional thing while recording the video to try and rule out as much as possible. I started with a clean grafana image running on docker locally on my machine. I then port-forwarded to the prometheus data source running in kubernetes. 
I also did this while using chrome incognito mode to rule out any browser plugin causing issues. 

[Archive.zip](https://github.com/grafana/grafana/files/10132490/Archive.zip)

**Comment by gtk-grafana** [comment] 2022-12-01 13:46
@bjor-joh thanks for the videos/profile, I'm taking a look and see if we can reproduce this locally. Quick question: do you see the UI locking up like this when you're using the query builder, instead of the code editor?

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/109082771/205068190-2484a587-7878-45e1-989c-afeb4fdda90e.png">

We're still using the /series endpoint call in the code editor, which can use a lot more memory than the new API calls. I'm working on a fix for this that should be out in the next minor release or so, but I have a feeling that's not related to the issue you're seeing. We'll keep investigating and we'll keep this thread updated as we learn more.

**Comment by bjor-joh** [comment] 2022-12-01 14:28
No actually that one seems to perform ok. 
Also If I create a dashboard and edit a panel in the dashboard I don't experience the same issue either, regardless if using code editor or query builder. So seems to be isolated to the explore-ui. 

It really feel like there is something client side and not a network error, but that is more of a gut feel. 

Thanks for looking in to this and let me know if there is anything else you need.

**Comment by gtk-grafana** [comment] 2022-12-01 16:08
@bjor-joh One more idea for you to try: what if you set the "query type" to series, instead of both, and try to reproduce the issue again?
<img width="857" alt="image" src="https://user-images.githubusercontent.com/109082771/205101805-e468c10f-f711-4dd9-907b-874912178d77.png">

There are some known performance issues with the table that gets rendered in the explore UI for instant queries, especially for series with many labels, which could potentially be locking the main thread while rendering, which could result in behavior similar to what you're seeing here.

**Comment by bjor-joh** [comment] 2022-12-02 11:25
Still experienced some lag, but it got a lot better.

**Comment by gtk-grafana** [comment] 2022-12-09 14:00
@bjor-joh Sorry for not getting back to you sooner, while I'm still not able to exactly reproduce this issue, I'm going to hope that the optimizations in https://github.com/grafana/grafana/issues/58187 will help. I should have some time to wrap that up in the coming weeks, but I think we've got a code-freeze until after the holidays (Jan 10), so it might take a bit longer before we can release any potential fix for this. 
Thank you for your patience, I'll try to find some time to dig into this further.

**Comment by bjor-joh** [comment] 2022-12-09 15:02
@gtk-grafana Thanks for getting back. Sounds good

**Comment by bjor-joh** [comment] 2022-12-12 08:20
@gtk-grafana hi again. 

I managed to find some time to reproduce this and I think I found a way. 
I have created a repository with instructions here: https://github.com/bjor-joh/grafana-issue-59044

Figured this might help us see if the changes you mentioned will indeed solve it. This will hopefully shorten the feedback loop a bit so that we don't have to wait for the next release to see if there is any improvement. 

Let me know if you have any issues running the example in the repository I linked.

**Comment by gtk-grafana** [comment] 2022-12-12 18:29
@bjor-joh I just want to start by saying thank you so much for going through all of this effort to provide us such a great example to reproduce this issue, this is really cool and I've never seen that `expose_many_metrics` script before, super useful!

Anyway, I was able to reproduce this issue with your example, and while my feature branch doesn't seem to have much impact, I was able to track down what appears to be the problem here!

This is actually a bug I seem to have released in https://github.com/grafana/grafana/pull/55513, sorry about that! The fix simply involved debouncing a function which is setting the current editor value, which should prevent that function (which was taking 400+ms in your provided example after each keystroke) from blocking the main thread until the user stops typing for a bit, and it will dramatically reduce the number of times we call that function, so performance improvements all around!

I've got a draft PR that fixes this, but we're starting a code freeze on Wednesday for the winter holidays, so I probably won't be able to release the fix for this until January at the earliest. 

Thank you again @bjor-joh, I really appreciate the work you did to get us this awesome demo! 🎉🎉 🎉

**Comment by bjor-joh** [comment] 2022-12-12 19:06
@gtk-grafana Awesome, that is great news. 

No worries about not getting this in before the code freeze, that is totally fine. 

Grafana is such a nice product, I use it both personally and professionally. Nice to find a way to be able to give back. 🙂

**Closed** 2022-12-15 20:15 UTC

**Comment by gtk-grafana** [comment] 2023-03-20 15:40
https://github.com/grafana/grafana/issues/60420 will add additional configuration allowing users to configure a longer debounce interval to further reduce the amount of resources
