### ISSUE TITLE
[Feature Request] Multiple thresholds for alert notifications

### ISSUE THREAD

**Issue by ivanmp91** [grafana/grafana#14470] opened 2018-12-12 18:08 UTC
**Use case**
As grafana user, I would like to define alert notifications with different thresholds and associate a different status based on each threshold, something like 'OK', 'WARNING', 'CRITICAL', 'NOTICE'... Also it would be nice to associate each threshold to a different notification channel. In the end should be something similar like having multiple alert conditions for a single dashboard.

Current workaround is duplicate dashboards and associate different alert conditions for each of them.

**Comment by torkelo** [comment] 2018-12-12 20:43
duplicate of https://github.com/grafana/grafana/issues/6553 and https://github.com/grafana/grafana/issues/7832

**Closed by torkelo** 2018-12-12 20:43 UTC
