### ISSUE TITLE
[Feature request] Allow merging of graphs into a scratch pad

### ISSUE THREAD

**Issue by swaranga** [grafana/grafana#13436] opened 2018-09-27 06:24 UTC
Feature request to allow selection of several graphs on a dashboard and create a new merged graph. The reason this is useful is because when we are exploring a cause of an issue, we might be looking at multiple graphs across our dashboard. Allowing merging of the graph helps us determine root causes easily.

I characterize the following for it to be a useful feature:
* User should be able to select multiple graphs and add them to a "cart"
* Once the cart has the required graphs, they should be able to click on a "merge" button which would render a graph with all the graphs in the art plotted in the same panel. Clearing a cart of any existing graphs should be supported of course.
* The merged graph tab does not need to provide the templating functionality from the original graphs - it should just take the graphs as rendered on the original (with the template variables populated) and plot them in the merged graph. But it should support selecting different time-ranges once the merged graph is rendered just like other normal graphs.
* The merged graph should be opened in a new tab
* The merge functionality should not make an changes in the original graphs
* User should be able to add graphs to the cart from different browser tabs. If not the functionality would be rather limited. In most cases, when I am debugging an issue, I am looking at different dashboards in multiple browser tabs.
* The new merged graphs should not be persisted in the Grafana backend database. It should be a temporary graph rendered on a browser tab. This is because this feature, if available, will be used frequently for debugging issues and persisting them in the backend would pollute the whole Grafana installation.
* A readonly user should be able to create these merged graphs and should not need editor or admin permissions.

**Comment by swaranga** [comment] 2018-09-28 00:46
My responses:

> the scratch area is always available in the bottom and can be pulled up at will
> when pulled up, it covers most of the dashboard like a modal, but you can change its size

Will a user be able to change the time-range of the graph in the modal without changing the time range of the entire dashboard thus causing all the graphs in the dashboard to reload?

> if you change dashboards, the scratch area stays unaffected, you can add more panels to it

It should really work across browser tabs though. making a user switch a dashboard will limit the usefulness of the feature.

> a scratch area should either be shareable via link (which means its complex state needs to be kept somewhere, likely the backend).

I like the shareability of ephemeral graphs but may be you don't need to persist it in the backend. If you implement it such that the merged graph is re-creatable from the source graphs you could encode the information of the source graphs in the url for a merged graphs and recreate it when necessary to render. There are some other caveats though for this approach though - like what happens if the source graph is deleted or changed etc. 

> or be subscribe-able like vs code live share

This seems too complex to implement and may be not very useful as well. Since if it is subscribable, then it means there is just one url for a scratch-pad for a given Grafana server. Then multiple users will not be able to create there own scratch pad. We have one Grafana server for multiple teams with their own dashboards and having just one scratch pad would be very limiting for each team to work concurrently.

**Comment by davkal** [comment] 2018-10-02 07:52
Thank you for the feedback. 

> Will a user be able to change the time-range of the graph in the modal without changing the time range of the entire dashboard thus causing all the graphs in the dashboard to reload?

It'd be great if you can state your use case or desired flow. It's harder to decode this from a question 😉 

What would also help:

-  concrete numbers: how many dashboards/panels/datasources you normally traverse before finding a root cause?
- why do you keep multiple tabs open in the first place?
- do the tabs need to stay open after sending graphs to scratch?

**Comment by diafour** [comment] 2018-11-20 06:06
Scratch area is a super cool feature! Totally want it :)

My thoughts on this topic:

Variables.
What to do with them? Allow to change variables inside scratch area or add graphs with hardcoded variables values?

"Instantiate a scratch"
Allow to transform scratch area into a real dashboard.

**Comment by swaranga** [comment] 2019-09-11 03:19
>It'd be great if you can state your use case or desired flow. It's harder to decode this from a question 

Here is my use-case, our platform is comprised of multiple applications/services working together. Each of the services have other dependencies as well. We create detailed Grafana dashboards for each service. When a problem occurs, like a latency increase, we need to dig into what might have caused it. In such cases, we load multiple dashboards in multiple tabs and inspect the spikes. If we suspect a spike in the latency of one service might be causing the spike in the other, it would be easy if we can quickly merge them to a separate graph and examine if the spikes are at the same time.

**Comment by hugohaggmark** [comment] 2020-11-13 06:52
Moving this to @grafana/observability-squad.

**Comment by gabor** [comment] 2022-10-19 14:27
sounds like a dashboard-feature, @grafana/dashboards-squad , could you take a look?

**Comment by dprokop** [comment] 2024-03-25 10:49
@swaranga thanks for opening the issue. However we see a very litte interest in this feature request. I'll close it for now, but if you still find this request relevant we are more than happy to review and consider a PR with the contribution.

**Closed by dprokop** 2024-03-25 10:49 UTC
Labels: type/feature-request, area/dashboard, team/grafana-dashboards, prio/future
