### ISSUE TITLE
Annotations HTTP API does not return the annotation id on creation.

### ISSUE THREAD

**Issue by rrey** [grafana/grafana#10391] opened 2018-01-01 17:54 UTC
Version:  Grafana v4.6.3 (commit: 7a06a47)

Using the docker container, when I'm sending an annotation through the http api, the server answer does not contain the annotation id in the json.

The documentation (http://docs.grafana.org/http_api/annotations/) states that we should have the id:
```
When creating a region annotation the response will include both id and endId, if not only id.
```

See the following trace of the curl command used:
```
$ curl -H "Content-Type: application/json" -XPOST 127.0.0.1:3000/api/annotations -d @test.json --basic --user "admin:admin"
{"message":"Annotation added"}
```

test.json content:

```
{
  "time": 1514828605000,
  "tags":["test"],
  "text":"Annotation Description"
}
```

**Comment by torkelo** [comment] 2018-01-02 09:28
fixed in master/nightly builds, dupe of https://github.com/grafana/grafana/issues/9798

**Closed by torkelo** 2018-01-02 09:28 UTC

**Comment by rrey** [comment] 2018-01-02 10:10
Great, thx @torkelo
