### ISSUE TITLE
Bug in legend

### ISSUE THREAD

**Issue by Gatses** [grafana/grafana#14057] opened 2018-11-13 21:26 UTC
### What Grafana version are you using?
v5.3.4
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Ubuntu 16
### Browser
Google Chrome (70.0.3538.77), Firefox (63.0.1 )
### What did you do?
If you hover the mouse on the "Legend", the information is shifted to the right.
![bug](https://user-images.githubusercontent.com/21112682/48443543-8496e580-e7a2-11e8-93ee-38bee2c0bab0.gif)

If set "Width" - everything is ok.

**Comment by daniellee** [comment] 2018-11-13 23:16
I couldn't recreate this (just did a quick try). Could you attach the dashboard json so we can see which settings you are using. This is the type of bug we would like to fix quickly. Thanks!

**Comment by Gatses** [comment] 2018-11-13 23:39
Yes of course. :)
[Bug.zip](https://github.com/grafana/grafana/files/2578552/Bug.zip)

**Comment by ialoh** [comment] 2018-11-13 23:58
ср, 14 нояб. 2018 г. в 01:40, Gatses <notifications@github.com>:

**Comment by torkelo** [comment] 2018-11-14 05:09
This is likely caused by the baron scroll comp, fixed in nightly and upcoming 3.4

**Closed by torkelo** 2018-11-14 05:09 UTC
Labels: comp: panel/graph, state: needs more detail, type: bug
