### ISSUE TITLE
Cloudwatch: Issue using ANOMALY_DETECTION_BAND

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#90625] opened 2024-07-18 18:12 UTC
A customer has pointed out to us that when using ANOMALLY_DETECTION_BAND as a metric math query, they don't get any data back. I was able to reproduce as well:

<img width="959" alt="Screenshot 2024-07-18 at 1 12 54 PM" src="https://github.com/user-attachments/assets/29decc31-a2d1-4db7-8793-56080148e64b">

I also noticed I was able to sometimes get this error `Unsupported operand type(s) for ANOMALY_DETECTION_BAND: '[Array[TimeSeries], Scalar]` on a monitoring account when I messed around with reordering/renaming the queries 
<img width="1144" alt="Screenshot 2024-07-18 at 1 13 19 PM" src="https://github.com/user-attachments/assets/465d2219-f984-4b0f-922b-e35e65018f23">

I'm not sure if that's related or not. 

I also added these feature toggles: 
```
cloudwatchBatchQueries = true
sseGroupByDatasource = true
```

But the issue persisted. 

Grafana > 11.1.0

**Comment by xpuska513** [comment] 2024-08-23 10:13
I have similar issue running on Grafana v11.1.3. When running same query via CloudWatch in AWS console it returns expected results, but same query in grafana evaluates in NoData

**Comment by iwysiu** [comment] 2024-08-28 15:57
Hi @xpuska513 , can you give me more details about the query you're trying to run, like the json for the dashboard (click the share button at the top of the dashboard and export the json)? I'm investigating this and I wasn't able to reproduce it. If you're trying to run the query in an alert, do you have the `sseGroupByDatasource` and `cloudwatchBatchQueries` feature toggles set?

**Comment by iwysiu** [comment] 2024-08-28 19:21
@xpuska513 I should have mentioned this in my first message, but you have to [explicitly create an anomaly detection alarm](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Create_Anomaly_Detection_Alarm.html) on the metric in order to be able to query it ([docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html). Have you done that, and are you still seeing the issue?

**Comment by xpuska513** [comment] 2024-09-06 07:42
Hi @iwysiu, I've tried the solution you described, but I'm still facing the same issue. I want to create and alert for our ALB request count to notify us when we have higher traffic than usual. I've created an alert in CloudWatch, but still don't see any data, but will give it a time to collect some data first and then will get back to you with updates.

**Comment by xpuska513** [comment] 2024-09-06 07:45
@iwysiu, the solution seems to be working fine, thanks for help!

**Comment by iwysiu** [comment] 2024-09-06 13:23
@xpuska513 I'm glad it worked for you 😄 In that case, I'm going to close this issue

**Closed by iwysiu** 2024-09-06 13:23 UTC
Labels: type/bug, datasource/CloudWatch, internal
