### ISSUE TITLE
Grafana 5.0 - invisible sign out menu 

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#10439] opened 2018-01-05 10:18 UTC
Hello,

Please add some default background on the sign out menu icon as right now without mouseover it's invisible :)

![obraz](https://user-images.githubusercontent.com/12551929/34604951-efe9362e-f209-11e7-8bd9-9e90cebeb072.png)

- What Grafana version are you using? 5.0 alpha

Regards
PaVliK

**Comment by torkelo** [comment] 2018-01-08 08:50
dupe of https://github.com/grafana/grafana/issues/10426

**Closed by torkelo** 2018-01-08 08:50 UTC
