### ISSUE TITLE
"All" templating variable shortcut for better performance

### ISSUE THREAD

**Issue by vonox7** [grafana/grafana#11158] opened 2018-03-08 09:31 UTC
When creating a template variable and including the `All` option, a query like `SELECT mean(userCount) FROM influxDb WHERE ("coutry" =~ /^(ac|ad|ae|af|ag|ai|al|am|an|...|za|zm|zw)$/) AND time >= now() - 2d GROUP BY time(1h) fill(null)"` will be very slow. In fact, when having more than about 50 tags, my 2GB-RAM database won't even process the query:
```
Annotation Query Failed
{"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/annotations","params":{"from":1520328096346,"to":1520500896346,"dashboardId":22},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"abort"}
```

Having this tag filter is often important, e.g. when quickly looking into only one country. By selecting the `All` option, i want to see all countries, but in this case the dashboard won't load any data.

As workaround, I created two identical dashboards: One with the country templating variable but without the `All` option. And one without the country templating variable and also without the specifying WHERE-clause.

Proposal: **Can Grafana remove the WHERE-clause when selecting `All`**?
When selecting `All`, the query should like  `SELECT mean(userCount) FROM influxDb WHERE time >= now() - 2d GROUP BY time(1h) fill(null)"`

I'm running Grafana 5.0.0 with InfluxDB on linux.

**Comment by JamesGalt** [comment] 2018-03-08 19:03
Hi
the problem is if your variable is filtered by a regex, removing the where clause will cause some data to be shown whereas they shouldn't.

**Comment by vonox7** [comment] 2018-03-08 19:21
I understand you. In fact, that depends on the definition of "All". Until this further investigation I personally had no clue, that `All` excluded some values, as the words sounds pretty inclusive.

**Comment by bergquist** [comment] 2018-04-11 11:33
Removing the Where clause would be tricky to do in a simple manner and hard to get right for all datasources.  Having two dashboards and link between those seems like a simpler solution. 

Closing this as it's too much of an edge case.

**Closed by bergquist** 2018-04-11 11:33 UTC
