### ISSUE TITLE
Do not fallback to "All" for dashboard variables

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#17096] opened 2019-05-15 14:33 UTC
When you have a dashboard variable which has `All` option and for some reason the current selected value(s) is/are not available on a new time range the var will fallback to `All` choice.

This is quite dangerous if you have a lot of items in the list and you are iterating rows over that variable.

More than once I killed my monitoring stack because of the DOS grafana generates when it queries the TSDB for all the items of the list.

**Comment by xlson** [comment] 2019-05-16 08:40
I have a few questions:

1. Why is the All option enabled if it can't be used?
2. What would be the best behavior in your use case?

**Comment by sylr** [comment] 2019-05-16 08:49
1. It can be use when number of items in list is not too important (say 10~15) but sometimes the list can contain 50, even 100 items.
2. The way I see it falling back to an empty var would be the  best solution.

**Comment by sylr** [comment] 2019-05-16 08:50
Or maybe being able to define the default/fallback value would be even better.

**Comment by torkelo** [comment] 2019-05-16 19:07
dupe of https://github.com/grafana/grafana/issues/6995

**Closed by torkelo** 2019-05-16 19:07 UTC
