### ISSUE TITLE
Inconsistent Display of labels for CloudWatch

### ISSUE THREAD

**Issue by viper25** [grafana/grafana#26794] opened 2020-08-05 09:05 UTC
**What happened**:
For a CloudWatch Metrics data source, the DynamoDB Table Name doesn't appear for certain metrics, specifically *WriteThrottleEvents*.

**What you expected to happen**:
Display the table label for which the active metrics. The table label is displayed for the ReadThrottleEvents metric but not the WriteThrottleEvents 

**How to reproduce it (as minimally and precisely as possible)**:
Create A Graph chart with a AWS CloudWatch Metrics data source. Select a DynamoDB with a WriteThrottleEvents metric. For this you must somehow generate values for this metric. Select * as the TableName dimension. The setting is shown here:
![image](https://user-images.githubusercontent.com/327990/89392818-9b325c80-d73c-11ea-9b92-68bc360f4405.png)

The bug is shown here:
![](https://i.imgur.com/xL8rPOl.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.1 (3039f9c3bd)
- Data source type & version: AWS CloudWatch Metrics
- OS Grafana is installed on:
- User OS & Browser: AWS Linux
- Grafana plugins: 
- Others:

**Comment by mchene** [comment] 2020-08-10 16:04
Is the WriteThrottleEvents for any global secondary indexes, https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/metrics-dimensions.html?  If so, you'll need to specify the "GlobalSecondaryIndex" as a Dimension.  The alternative is to use the Search metric math expression, https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html.

**Comment by viper25** [comment] 2020-08-12 01:27
No there's no secondary indices on this table. It's on the main primary keys. For some reason this metric doesn't display the terms labels correctly. I've seen this in other places on Grafana as well (will post here if I remember).

**Comment by wbrowne** [comment] 2020-08-25 13:39
@viper25 Thanks for creating this issue!

If possible, could you share the full output from the Query inspector - that will help in investigating further

**Comment by oleksii-iaroshchuk** [comment] 2020-09-23 11:40
This issue is very similar to the one I am currently observing on some our dashboards.
When trying to build [dynamic queries using dimension wildcards](https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#dynamic-queries-using-dimension-wildcards), if there is only one dimension value available, metric name is used instead of dimension name in the graph legend.
I see the same on the gif above - when there are metrics for 2 Dynamo tables, table names are displayed correctly in the legend. But when there is only one table, we see a metric name.

I digged through the issues and PRs, and I think these might be related to the issue:
- https://github.com/grafana/grafana/pull/21541
  - https://github.com/grafana/grafana/issues/20927
  - https://github.com/grafana/grafana/issues/20729
- https://github.com/grafana/grafana/issues/21625
  - https://github.com/grafana/grafana/pull/21626

**Additional notes:**
- I see this issue in Grafana v7.1.3 (5723d951af)
- This issue is not consistent across all dashboards - some dashboards display metric with a single dimension properly, and some have this strange behavior.

I also found a **hacky workaround** (probably it will help to find a root cause): 
- Add a second similar query to the chart
- Set dimension value to some STUB value
- Set Alias to some not disturbing value like "-"
- Set Match Exact for this stub query to True
- Now the main query displays dimension name correctly in the chart legend (in addition to stub dimension legend "-")

I decided not to create a separate issue for now, because I believe we are seeing the same problem.

**Comment by bitbier** [comment] 2020-10-27 15:44
Any word on this? We are running into this issue as well. We only use the CloudWatch metrics and this happens when a query a metric and only one unique dimension combination is returned. As soon as we have more than one, the labels are displayed correctly. It makes it hard for our users to understand their metrics as that one label doesn't describe the specific dimension that contains 100% of the data.

**Comment by wbrowne** [comment] 2020-10-27 16:53
Apologies for the delay on this. I have some time now and I'll try reproduce to understand the problem better on the Grafana side. Thanks @bitbier @oleksii-iaroshchuk for the extra context

**Comment by sunker** [comment] 2020-12-03 07:54
This is how the GetMetricData api works. If dimensions are not defined specifically (i.e a wildcard is used), the returned time series label will be equal to the dimension name **if more than one time series is being returned**. If only one time series is being returned, the label name will be the same as the metric. You'll see the exact same behavior in the CloudWatch Console. 

I totally agree this behavior is inconsistent. Unfortunately there's nothing we can do to work around this on the Grafana side, so I'll close this issue.

**Closed by sunker** 2020-12-03 07:54 UTC
Labels: datasource/CloudWatch, needs investigation

**Comment by oleksii-iaroshchuk** [comment] 2020-12-03 16:08
@sunker , thanks for the clarification. Does this mean we should create a ticket for Amazon on this? Do you know what is the best place for this?

**Comment by jpmatusik** [comment] 2021-12-21 06:54
Just ran into this issue as well. I see the note above saying that there is no work around that can be done on the grafana side, but I'm looking at the API for GetMetricData and I see that dynamic labels can be added to a query.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/graph-dynamic-labels.html

Of specific interest is ${PROP('Dim.dimension_name')}.

In boto3, using it looks like this with product_id as a wildcard.

```
import boto3
from datetime import datetime

client = boto3.client("cloudwatch", region_name='us-east-2')

response = client.get_metric_data(
    MetricDataQueries=[
        {
            'Id': 'a',
            'Expression': '''REMOVE_EMPTY(SEARCH('{"namespace","app","env","product_id","user_id"} MetricName="name" "app"="api" "env"="test" "user_id"="the-user-id"', 'Average', 60))''',
            'Label': "product_id=${PROP('Dim.product_id')}\nuser_id=${PROP('Dim.user_id')}\nenv=${PROP('Dim.env')}",
        },
    ],

    StartTime=datetime(2021, 12, 21, 0),
    EndTime=datetime(2021, 12, 22),
)

print(len(response['MetricDataResults']))
print(response['MetricDataResults'][0]['Label'])
```
where in this case the printed output look like this 
```
# from the len
1 
# from the label
product_id=the-product-id
user_id=the-user-id
env=test
```

Seems to me that manually constructing the label and using a safe delimiter could be useful here.

**Comment by skylarmb** [comment] 2022-06-25 02:41
I am able to work around this by using the "Labels to fields" transform.

Without transform, legend / labels are useless:
![image](https://user-images.githubusercontent.com/7543705/175755127-5a8e16a2-85af-404c-87f2-093f77a407fd.png)

With "Labels to fields" transform, labels are now the same as the original dimension value in the query:
![Untitled](https://user-images.githubusercontent.com/7543705/175755188-7d62051e-2eca-4570-92de-3e3741644706.png)
