### ISSUE TITLE
CloudWatch id field breaks alert addressing

### ISSUE THREAD

**Issue by erothmayer** [grafana/grafana#13940] opened 2018-11-02 00:31 UTC
Please include this information:
### What Grafana version are you using?
5.3.1 (assume it also repros in 5.3.2 but can't confirm due to https://github.com/grafana/grafana/issues/13939 blocking the use case before I can check)

### What datasource are you using?
CloudWatch Metrics

### What OS are you running grafana on?
Docker distro

### What did you do?
1. Add a metric WITHOUT an 'id'
2. Add an alert on it and test
3. See that it fires 'true' and returns a sensible value
4. Add a value in 'id' for the metric
5. Test the alert again

### What was the expected result?
It should still evaluate the same as it did without the id

### What happened instead?
It evaluates false with the message `Condition: Eval: false, Query Returned No Series (reduced to null/no value)`

My strong suspicion is that this is related to the id / refId mixup that is also behind #13939 , and the id of the Series in the result set is being altered so that the Alert sub-system can no longer find the data.

I tried addressing it both as "A" and as "aaa" (the ID I had entered) in the alert definition, and it could not find the data by either identifier.

**Comment by torkelo** [comment] 2018-11-05 09:41
> Add a metric WITHOUT an 'id' 

what do you mean without an id? What id are you referring to?

**Comment by erothmayer** [comment] 2018-11-05 15:38
@torkelo 

![image](https://user-images.githubusercontent.com/26010650/48008059-cbfbe280-e0cd-11e8-96e5-8a602e17c647.png)

I believe it's a specialized metric field for the CloudWatch datasource.

**Comment by torkelo** [comment] 2018-11-05 17:03
Not sure what that id field is and how it affects alerting

**Comment by marefr** [comment] 2018-11-05 17:30
Think this is the same problem as #13749

**Comment by asphodei** [comment] 2018-12-12 00:54
Reproduced in 5.4.1. 

**Steps to reproduce:**

1) take any CloudWatch metric
![screen shot 2018-12-11 at 7 45 07 pm](https://user-images.githubusercontent.com/44406294/49839683-2566c980-fd7e-11e8-8873-bc3cb2f898ef.png)

2) test an alert with it 
![screen shot 2018-12-11 at 7 45 22 pm](https://user-images.githubusercontent.com/44406294/49839693-30215e80-fd7e-11e8-8693-979085b918f8.png)

As you can see, it works as expected.

3) add an ID to the metric
![screen shot 2018-12-11 at 7 50 49 pm](https://user-images.githubusercontent.com/44406294/49839705-3b748a00-fd7e-11e8-9172-bb3f43ae4690.png)

4) test the same alert 
![screen shot 2018-12-11 at 7 50 56 pm](https://user-images.githubusercontent.com/44406294/49839712-42030180-fd7e-11e8-80b2-b5cfbab81296.png)

**Comment by marefr** [comment] 2018-12-12 09:34
@asphodei #13749 is still open and haven't been fixed that's probably why

**Comment by marefr** [comment] 2018-12-12 09:35
Duplicate of #13749

**Closed by marefr** 2018-12-12 09:35 UTC
Labels: state: needs more detail
