### ISSUE TITLE
Mathematical operations on multiple queries from different data sources

### ISSUE THREAD

**Issue by stvnwrgs** [grafana/grafana#3973] opened 2016-02-09 17:26 UTC
I was searching for a way to divide a value of metric A through a value of metric B with InfluxDB as data source.

I found ticket #1295, that says this is only working with Graphite because the operation is handled directly in the data source. Such a feature should definitely be added to InfluxDB, but I think it would also be useful to be able to use this feature from multiple data sources. That would also allow to use this feature independently from the data source.

I also found #3762 and some other tickets where people asked for the same.

After thinking about this, I found a second thing that could be improved and would be needed for this:

**Multiple data sources for graph queries**
One graph is only capable of getting multiple queries from the same data source. Ticket: #3972

**Arithmetic operations for queries**

Add basic math operations that can be used on queries. 

1. Get data for each query.
2. Create var to store data
3. Group data to the same interval

- This on is a little bit tricky. Not sure how to get the same the same loopable interval for both queries. Maybe a sum / mean, etc for the one with less data points.

4. Loop over interval and execute math operation on data points 
for query A and B
5. save to var
6. Show graph

This is how it might look like:
![image](https://cloud.githubusercontent.com/assets/1257443/12889839/1c6e82c0-ce81-11e5-8196-b49531468b83.png)

I absolutely don't know if such a feature would kill Grafana because of resource lacks. Maybe someone is able to rate this? Is grafana hypothetical able to calculate something like this?

**Comment by torkelo** [comment] 2016-02-09 17:27
this is an awesome feature that we want to implement int the future. 

Will close as this is duplicate of https://github.com/grafana/grafana/issues/3677

**Closed by torkelo** 2016-02-09 17:27 UTC

**Comment by LiXi-storage** [comment] 2017-02-14 15:48
May I ask how this project is going on? I am considering a similar feature, but it turns out it is not going to be easy....

**Comment by arifA9** [comment] 2017-12-14 09:56
Hi, Is this issue resolved in Grafana. I am facing the similar issue and looking for solution

**Comment by huwenbiao** [comment] 2018-04-03 09:35
+1

**Comment by jdde** [comment] 2018-05-17 12:46
+1

**Comment by xJoshx** [comment] 2018-05-24 09:00
+1

**Comment by addictedanshul** [comment] 2018-07-27 06:11
+1

**Comment by aramhakobyan** [comment] 2018-08-28 23:00
+1

**Comment by pbosgraaf** [comment] 2018-09-23 16:30
+1

**Comment by lmssdd** [comment] 2019-03-29 08:57
+1

**Comment by cyrilbkr** [comment] 2019-04-10 15:38
+1

**Comment by bpetit** [comment] 2019-04-10 15:42
It would be an awesome feature. Computing ES and TSDB metrics for example would be a game changer.

**Comment by StephaneDci** [comment] 2019-07-11 16:01
+1

**Comment by yasegev** [comment] 2019-07-18 13:21
+1

**Comment by AlexandreGuidin** [comment] 2020-04-17 12:40
Maybe this should help you

https://grafana.com/grafana/plugins/goshposh-metaqueries-datasource
