### ISSUE TITLE
Roadmap: Grafana plugins platform

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#36228] opened 2021-06-28 15:38 UTC
We would like to make the experience of **_extending Grafana when building a plugin_** as smooth as butter. Hopefully you have a bunch of ideas that we can improve.

> Note: this issue is targeting the APIs being used to build plugins/apps to extend Grafana.

### What to do:

- Add a comment explaining the feature you want to be added to the plugins APIs.
- Add a comment including a link to an existing issue, open or closed.
- Thumbs up comments 👍 and we will try to use this as an indicator of demand (prefer adding a 👍 to an existing comment rather than adding a new comment).
- It can be difficult to prioritize work for a project like Grafana which can be used in many different ways, it's hard to tell how common some might be or how popular a feature request is, your feedback would be greatly appreciated!

One request, we can keep the thread easier to read if we don't have too many discussions, prefer creating a separate issue or use the existing issue to have specific conversations.

### Things we already have planned:

> Note: this is a living document and is prone to change.

**Grafana 8.3:**
- Automatically suggest compatible plugin version that will work with your current Grafana version when managing plugins. 
- Display a warning in plugins catalog if you are trying to uninstall a plugin that is being used and configured as a datasource.
- Make is possible to easily publish/subscribe to appEvents in a plugin.

**Grafana 8.4:**
- Support running plugins remotely so you can run one instance of a plugin and use it for multiple Grafana instances.

**Later version of Grafana:**
- Better manage changes between Grafana version so that we always strive for backward compatibility.
- Enhance plugin developer tooling so it is easier to use and debug across all major OS.
- Improve the CI pipeline support for helping internal and external plugin developers building awesome plugins.
- Add APIs to make it easy to support internalization in plugins.
- Introduce a developer portal with documentation, migration guides etc. to make it easier for developers to understand how to extend Grafana.

**Comment by joshhunt** [comment] 2021-06-28 16:38
One thing that could be interesting to look is whether eslint could statically identify anti-patterns and provide warnings in your editor. Grafana could develop a custom eslint plugin (see https://github.com/vercel/next.js/blob/canary/packages/eslint-plugin-next/lib/index.js) and have it a part of the default template.

**Comment by srclosson** [comment] 2021-07-09 12:58
Setting expectations with developers that "Your plugin must at least support the last 1 year of grafana releases" (or something to that effect) and then providing tools to ensure developers can easily tests their plugins for compatibility would be stellar.

**Comment by joshhunt** [comment] 2021-07-12 16:59
I would also love to see a clean up of the `DataSourceApi` / `DataSourceWithBackend` typescript interfaces with some stricter types for the methods, and simplifying the obligations of developers in terms of  methods to implement, or the shape of the data to return

e.g. `applyTemplateVariables` is basically typed to return `any`, but it apparently looks like it needs to return properties like `refId: target.refId` or ,  I'm unsure why. IMHO Grafana should just handle that for me, and I shouldn't have the opportunity to screw that up by omitting the field Having better types for these functions.

https://github.com/grafana/grafana/blob/83b6df7/public/app/plugins/datasource/cloud-monitoring/datasource.ts#L106-L116

**Comment by joshhunt** [comment] 2021-07-13 10:34
It could be interesting to look into adding "Auth Providers" as a core (plugin?) concept to Grafana. This would be a way to centralise authentication implementations in the code, and help users manage data source credentials in Grafana.

Hypothetically the user can go to a "Credentials" settings page in Grafana and configure some Azure (for example) credentials. Then when I'm setting up Azure Monitor, ADX, and any other data sources rather than entering in credentials specific to that data source, I could select from the available credentials I have set up.  UX wise, you should have the ability to create new credentials inline, if you don't have any yet.

Data sources could express (through plugin ids??) which auth types they're compatible with (or require), and the grafana http stack could transparently apply those auth middleware to requests made with it

I imagine this would be an extension of the current core auth options available through DataSourceHTTPSettings, and could solve some UX problems that's starting to show as it supports more auth types optionally for some data sources. 

A major consideration that could prevent this from being a good idea is that (by design!!!) currently you cannot reuse secrets between multiple data sources. Once you've entered a secret into a data source, you cannot reuse that secret to use elsewhere. I'm unsure whether its safe or not to "trust" admins to be able to reuse secrets like this.

**Comment by richardqlam** [comment] 2021-07-13 14:09
For Grafana Cloud, we often have overlapping concepts that exist both within Grafana Core and within the Cloud Portal. For example, API keys exist both at the Grafana level and at the Portal level. As we bring more of these concepts out of the Portal directly into Grafana, we want to be able to consolidate these concepts -- users shouldn't have to distinguish the difference between two menu options that say the same thing.

It would be great, then, if there was:
- The ability to hide specific Core sidenav buttons or sub-menu options, altogether
- The ability to add new sub-menu options to existing Core sidenav buttons
- The ability to modify existing Core pages so that new tabs and pages cab be added AND existing ones can be removed. For example, add a new page called "cloud integrations" to the existing Core Configuration page, or prevent the existing "Teams" pages from appearing/being accessed.

**Comment by wz2b** [comment] 2021-07-27 11:21
I would like to request the ability to have 3rd parties sign plug-ins in two ways:

 * by signing them with a CA issued code signing certificate (Comodo, Sectigo, etc.) or
 * by allowing grafana administrators to install their own CA somewhere on the system
What I don't love is the [hard coded method of validating the plug-in certificate](https://github.com/grafana/grafana/blob/0c804df763d4026440ddd97f3b707ea7593013a2/pkg/plugins/manager/manifest.go#L29) being used currently.

I attempted to raise this issue in #26287 and want to try again.

The certificate keystore doesn't have to be fancy.  I would make a search path or list that you can specify in grafana.ini, for example:

```
[plugins]
plugin_signing_certificates=/etc/ssl/certs/*.pem;some_self_signing_ca.pem;something_else.pem
```
then, in addition to checking the hard-coded internal grafana certificate the user could specify others.  I would default to checking the system keystore (usually /etc/ssl/certs if you're on something linux-y).  Note I also added the ability to include specific additional certificates.

How this would work is:

* If someone has a real code-signing certificate, then it would just work with one caveat: I would like grafana having a warning at the time of installation that says something like "Warning, you are installing a plugin not developed by Grafana Labs"
* If someone doesn't have one, then they generate their own "root" CA and install that as above
* I would require the code-signing usage (in the x.509 certificate extensions) for any of this to work

I think what this does is allows you to have 3rd party plugins where at a minimum you can identify the source of the plugin - you know where it came from and you know nobody else modified it, because it was signed by me, and Sectigo (or whomever) verifies that I'm really me.

The instructions to create a self-signed root and certificate are easy openssl commands, or it could easily be added to the mage system - if we can get consensus on this, I will volunteer to do that.

**Comment by unknowndevQwQ** [comment] 2021-08-10 10:07
> Setting expectations with developers that "Your plugin must at least support the last 1 year of grafana releases" (or something to that effect) and then providing tools to ensure developers can easily tests their plugins for compatibility would be stellar.

I think it's more intuitive to follow the [semantic version](https://semver.org) to ensure reliability than to follow the time

**Comment by torkelo** [comment] 2021-08-10 10:13
@richardqlam why hide Teams? it's a pretty core feature for organizing dashboards & folder

**Comment by torkelo** [comment] 2021-08-10 10:19
> The ability to hide specific Core sidenav buttons or sub-menu options, altogether
The ability to add new sub-menu options to existing Core sidenav buttons
The ability to modify existing Core pages so that new tabs and pages can be added AND existing ones can be removed. For example, add a new page called "cloud integrations" to the existing Core Configuration page, or prevent the existing "Teams" pages from appearing/being accessed.

The easiest way to accomplish this might be through a custom cloud build of enterprise, enterprise can modify the nav tree and add core pages. Having a plugin be able to do that could be tricky. Another option would be a very complex configuration scheme where the nav tree is defined in a config file but that has a lot of challenges as well.

**Comment by richardqlam** [comment] 2021-08-10 12:20
> @richardqlam why hide Teams? it's a pretty core feature for organizing dashboards & folder

This was just a random example, and a bad one. A more appropriate one may be "Users" since it is managed separately in the Cloud Portal. But either way, was just listing an example not an actual request.

**Comment by Willena** [comment] 2021-08-11 19:05
Since the introduction of transformations, I've seen that the team keeps adding more transforms to Grafana (it is great !).
I would love to see a new plugin API dedicated to transformations. So that transformations that are not considered important for Grafana Core could still be added using a plugin.

Any thoughts on that ?

**Comment by yosiasz** [comment] 2021-08-13 15:32
Make the following a bit more smart so that it lists out all teams and buckets (like variables work for devs 😉 )
Sometimes you forget team names and bucket names and have to leave this config to hunt down exact spelling of names.
Thanks!
![image](https://user-images.githubusercontent.com/900951/129383068-dd17ae08-1389-4085-958d-e34562735ef9.png)

**Comment by bobfrankly** [comment] 2021-08-17 19:22
It's almost humorous that I spot this after opening this:https://github.com/grafana/grafana/discussions/37978 . **I'd really like to see a way to add our own valueFormatters via plugins** so we don't have to bug the core devs over stuff like https://github.com/grafana/grafana/issues/37838 . We'd just be able to write a new currency formatter that doesn't compress the values by omitting the trailing zeros.

**Comment by mckn** [comment] 2021-08-25 09:47
> Make the following a bit more smart so that it lists out all teams and buckets (like variables work for devs 😉 )
> Sometimes you forget team names and bucket names and have to leave this config to hunt down exact spelling of names.
> Thanks!
> ![image](https://user-images.githubusercontent.com/900951/129383068-dd17ae08-1389-4085-958d-e34562735ef9.png)

This I great and I have forwarded it to the people working with the influx datasource plugin.

**Comment by tolzhabayev** [comment] 2022-02-28 12:10
We are closing this issue as we are switching to a new format of transparency around plugin platform development.

You can always submit a feature request as well as upvote existing ones here: https://github.com/grafana/grafana/discussions/categories/plugins
And see our public roadmap here: https://github.com/orgs/grafana/projects/76/views/9

**Closed by tolzhabayev** 2022-02-28 12:10 UTC
Labels: area/plugins, area/backend, area/frontend
