### ISSUE TITLE
Alert notification only send Alerting status,not include OK status 

### ISSUE THREAD

**Issue by unknown0x11** [grafana/grafana#9860] opened 2017-11-12 08:18 UTC
- What Grafana version are you using? 4.6.1
- What datasource are you using? influxdb
- What OS are you running grafana on? ubuntu 17.10
- What did you do? Test alert notification.
- What was the expected result? Only send alerting status,not include ok status.
- What happened instead? Send Alerting status and OK status both.

Hi, when I use grafana's alert function, I just want to send Alerting status, but now I received both Alerting status and OK status. Is there any way or any new feature can support this,just send Alerting status , not include OK status? Thanks!

**Comment by torkelo** [comment] 2017-11-13 09:37
duplicate of https://github.com/grafana/grafana/issues/6696

**Closed by torkelo** 2017-11-13 09:37 UTC
