### ISSUE TITLE
Organization Role: None

### ISSUE THREAD

**Issue by Freyert** [grafana/grafana#21040] opened 2019-12-11 16:16 UTC
**What would you like to be added**:
Would like to be able to give users in an organization access to nothing. 

**Why is this needed**:
That way with `auto_assign_org_role` we can have a holding tank for new users and administrators can assign them an appropriate role. This is mostly to secure Grafana through authorization in case someone figures out how to game authentication.

Draft PR: https://github.com/grafana/grafana/pull/21038

**Comment by marefr** [comment] 2019-12-11 17:49
Duplicate of #13474

**Closed by marefr** 2019-12-11 17:49 UTC
