### ISSUE TITLE
Alert emitted from non-existing rules

### ISSUE THREAD

**Issue by MatonAnthony** [grafana/grafana#51534] opened 2022-06-29 05:40 UTC
**What happened**: Following the update to Grafana 9 a bunch of legacy alerts are not migrated properly and are triggered but are no longer manageable

**What you expected to happen**: All alerting rules should be manageable (delete, silence, view, ...)

**How to reproduce it (as minimally and precisely as possible)**: 

I am not a 100% sure but:

- Create an alert on a panel in Grafana 8.5
- Migrate the instance to Grafana 9

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 9.0.1
- Data source type & version: Prometheus (various versions)
- OS Grafana is installed on: Grafana provided Docker Image
- User OS & Browser: Windows - Chrome
- Grafana plugins: N/A
- Others: On-premise installation

**Comment by MatonAnthony** [comment] 2022-07-04 11:43
After further investigations on our side, we believe it's triggered by alert that when the migration started were in the "Alerting" state.

**Comment by alexweav** [comment] 2022-07-29 16:40
To me, this sounds like it may have emitted a "Firing" notification in Grafana 8, then after the restart never sent a "Resolved" notification because the state was lost. This much is expected behavior.

@MatonAnthony Could you confirm if this is true? Or, is there actually a broken/unmanageable alert in the grafana UI? Could you provide some screenshots/more detail on how the alert rule appears broken? We mention that it cannot be managed - are there any error messages when we try to do so?

**Comment by armandgrillet** [comment] 2022-11-04 10:32
Closing this as no reply since more than 14 days.

**Closed by armandgrillet** 2022-11-04 10:32 UTC
Labels: needs more info, area/alerting, area/backend
