### ISSUE TITLE
Request to provide 'Query Options' per query in panel edit mode 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#25882] opened 2020-06-28 21:56 UTC
**What would you like to be added**:

In edit mode ‘Query options’ apply to all queries. A,B,C etc. 

![image](https://user-images.githubusercontent.com/54800912/85959069-588d9f80-b99a-11ea-9c93-cf4d94c89548.png)
  
It would be good if each query could have separate query options.
 
For example for Query A shows ‘today, last 1 hours data’ and query B shows ‘yesterday, last 1 hours data’ 
 
Then we can create a panel to compare the last hour for today, yesterday, 7days ago etc, and visualise in the same graph.  

![image](https://user-images.githubusercontent.com/54800912/85959091-722ee700-b99a-11ea-8d67-ac74f1703aff.png)
  
So in future edit mode with multiple queries could appear like the below image.  This would be for single datasource and for mixed mode.  

![image](https://user-images.githubusercontent.com/54800912/85959093-7b1fb880-b99a-11ea-9036-ae700ced77ac.png)

**Why is this needed**: 

To compare metrics across dates in the same panel.

**Comment by marefr** [comment] 2020-06-29 07:54
In this example, since you'e looking at 1 hour data in both queries the interval should be the same so make sure to use the data source query specific grouping by interval.

**Comment by torkelo** [comment] 2020-06-29 07:59
This will likely never be possible as these are panel level options that cannot be defined on query level

**Comment by marefr** [comment] 2020-06-29 08:01
I'm actually think the request is regarding overriding time per query which is a duplicate. So will close this as a duplicate of #7762. Let me know if I misunderstood something.

**Comment by marefr** [comment] 2020-06-29 08:01
Duplicate of #7762

**Closed by marefr** 2020-06-29 08:01 UTC
Labels: area/datasource, priority/awaiting-more-evidence, type/feature-request
