### ISSUE TITLE
Grafana not reapeating rows/panels for multivalue variables with 'All' value.

### ISSUE THREAD

**Issue by wiku-PSNC** [grafana/grafana#27163] opened 2020-08-24 12:27 UTC
Hi,

I've noticed after last upgrade (to 7.1.4) that value 'All' in multivalue variables is treated as one value causing the row/panel is not repeated for each value. I've many saved dasboards which worked fine before upgrade.

Kind regards,
Wiktor

**Comment by torkelo** [comment] 2020-08-24 12:36
duplicate of #27119

fix coming in 7.1.5 (scheduled for release tomorrow)

**Closed by torkelo** 2020-08-24 12:36 UTC
