### ISSUE TITLE
 Influx queries using a variable for the retention policy no longer work

### ISSUE THREAD

**Issue by passing** [grafana/grafana#70254] opened 2023-06-16 14:55 UTC
### 
# What went wrong?

**What happened**:

  - our dashboards with InfluxDB datasource using a variable for the retention policies stopped working

I could reproduce that the issue has not been there until version 9.3.15. It occurs with version 9.4.12 and any later version up to 10.0.0-preview

### 
# How do we reproduce it?

**Step 1**:

- Create an InfluxDB datasource

**Step 2**:

- Create a variable "retention" which uses the query `show retention policies`
![image](https://github.com/grafana/grafana/assets/8142186/724c8f5e-1194-4992-869a-be6381dbc170)

**Step 3**:

- Create a dashboard with a panel where you use the `$retention` variable as the retention policy

On Grafana 9.3.15 it works and the variable allows for choosing different retentions:
![image](https://github.com/grafana/grafana/assets/8142186/2f1b0cf6-9c96-4833-8105-9818eaee662a)

the query inspector shows the following query
```
SELECT mean("dashboards") FROM "RetPolicy_D365R2"."grafana_stats" WHERE time >= now() - 2d and time <= now() GROUP BY time(2m) fill(null)
```

On Grafana 9.4.12 and later versions it no longer works and the panel is empty. No error is shown

the query inspector shows the following query
```
"SELECT mean(\"dashboards\") FROM \"RetPolicy_D30R2\".\"grafana_stats\" WHERE time >= now() - 2d and time <= now() GROUP BY time(2m) fill(null)"
```

if you omit the variable and set the retention directly in the panel, the panel shows the correct result again and the query inspector shows the query like before
```
SELECT mean("dashboards") FROM "RetPolicy_D365R2"."grafana_stats" WHERE time >= now() - 2d and time <= now() GROUP BY time(2m) fill(null)
```

### 
# What Grafana version are you using?

 v9.5.3

### 
### Grafana Platform?

Docker

### User's OS?

Amazon Linux

### User's Browser?

Firefox 113.0.1 (64-bit)

### Is this a Regression?

Yes

### Are Datasources involved?

InfluxDB 5.0.0

**Comment by itsmylife** [comment] 2023-06-17 13:14
This will fix the issue https://github.com/grafana/grafana/pull/69202
The latest version which will be released next week will have this fix.

**Comment by passing** [comment] 2023-06-19 07:32
@itsmylife thank you for the quick feedback and pointing me to the related issue that's already in progress

I have now also tried the latest nightly build (docker image grafana/grafana-oss-dev:10.1.0-121880pre) with my local test setup and the test dashboard no longer shows the issue there

> Additional question: Do you use influxdbBackendMigration feature toggle?

we don't have that feature toggle enabled. Also tried enabling it on my local test setup with versions 9.4.12 and 9.5.3 but it doesn't seem to have an effect on the issue

**Comment by itsmylife** [comment] 2023-06-19 11:08
@passing Thanks for checking.

Some extra information: 
> In version `9.4.x` we removed the feature toggle and backend mode was the default mode. See https://github.com/grafana/grafana/pull/61308
> But after having problems with the backend mode we revert that change https://github.com/grafana/grafana/pull/64829
> That explains the problem you had. The latest version still has a feature flag but it was disabled by default. So it means you will have all the functionality as usual. 
See the ongoing progress of backend mode migration https://github.com/grafana/grafana/issues/65045
> We will slowly migrate everything to backend mode. And in theory, end users will notice nothing. 

Since the issue is gone for you I will close this. Feel free to ask questions if you have any.

**Closed by itsmylife** 2023-06-19 11:08 UTC
Labels: datasource/InfluxDB, area/dashboard/templating, type/regression

**Comment by parekcze** [comment] 2023-06-28 12:52
Hi @itsmylife ,

could you backported this fix in to 9.4 version, please? We can't upgrade now, because "Breaking changes with default retention policy" since version 9.5.

**Comment by itsmylife** [comment] 2023-07-06 18:13
@parekcze I will ask the release team if that's possible.

**Comment by itsmylife** [comment] 2023-07-07 21:08
@parekcze Unfortunately it is not possible :/ 
I backported the PR to `v9.4.x` See https://github.com/grafana/grafana/pull/71202
But we cannot create a release for this one.

**Comment by parekcze** [comment] 2023-07-11 10:22
@itsmylife Thanks for try. It's problem for us. We cann't downgrade, because created alerts and other things and cannot upgrade, because "breaking changes" around influxdb in version 9.5.

I tried change both files in `/usr/share/grafana/public` in Debian, but nothing change. Retention policy variable still doesn't working.

**Comment by QustodioPablo** [comment] 2023-07-11 11:21
Upgraded to 9.5.6 just to get this fix, but the issue is still present.

**Comment by QustodioPablo** [comment] 2023-07-11 11:53
> @QustodioPablo We cannot upgrade to version 9.5.x, because our default retention policy in influxdb is `default` and this isn't supported in new version. We cannot rename it now and we have to stay on version 9.4.x.

I was just reporting that this issue is still present in version 9.5.6, which supposedly fixes it.
Was not commenting on your specific issue, sorry for the confusion.

**Comment by itsmylife** [comment] 2023-07-17 08:28
@QustodioPablo It is indeed not working in `v9.5.6`. I checked and can confirm the fix is not in the release `v9.5.6`. I think there was a miscommunication with the release team. I am following up with them and keep you posted. Apologies about that.

**Comment by itsmylife** [comment] 2023-07-20 15:37
@QustodioPablo I confirmed that the fix will be in the next release of v9.5.x which will be done in one week. We are sorry about the delay.

**Comment by itsmylife** [comment] 2023-07-26 18:06
@QustodioPablo `v9.5.7` has the fix https://grafana.com/grafana/download/9.5.7

**Comment by parekcze** [comment] 2023-09-05 17:50
Since today update to 9.4.14 changing retention policy in dashboard working!!! Thank you very much for backport to 9.4.
