### ISSUE TITLE
https proxy for slack

### ISSUE THREAD

**Issue by sonchu** [grafana/grafana#13639] opened 2018-10-12 06:37 UTC
Please include this information:
### What Grafana version are you using?
5.3.0
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Centos 7
### What did you do?
Configure https proxy for slack alert
### What was the expected result?
Able to send successfully
### What happened instead?
Got error: "x509: certificate signed by unknown authority"
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

Please advise? I have configured the https_proxy under /etc/grafana/grafana-server.in but no luck.

Thanks a lot in advance.

Regards,
Son

**Comment by marefr** [comment] 2018-10-12 11:02
@sonchu Please see comment [here](https://github.com/grafana/grafana/issues/11962#issuecomment-421025199).

Duplicate of #11962

**Closed by marefr** 2018-10-12 11:02 UTC

**Comment by gjemp** [comment] 2019-09-05 11:46
/etc/sysconfig/grafana-server service env conf is the right place to where the http_proxy env key must be added for systemd services . Hope it helps others who had similar issue.

PS! i use Grafana 6.3.5 on RH 7.6

Br,
G
