### ISSUE TITLE
Grafana plugins directory in /home doesn't work, and Grafana crashes and restarts.

### ISSUE THREAD

**Issue by SimHacker** [grafana/grafana#44621] opened 2022-01-29 14:28 UTC
I love Grafana and appreciate your great work developing it, and am learning how to develop my own plugins, but I've encountered a problem.

Symlinking to a plugin dir in a repo for development is a very common and convenient use case. And so is putting the repo under a directory in /home. Both of which I wanted to do, but was unsuccessful.

I configured grafana to put the plugins in /home/grafana/dashboard/grafana/plugins (or /home/ubuntu, or any other directory under /home), which is a directory in my git repo, so I could check them into source code control and develop my own plugin. 

When I start grafana with that plugins directory, it is unable to load any plugins, and restarts. 

The log ends and repeats after the message "No enterprise license found in path (starting without enterprise features)". 

But there is no error or warning message about why Grafana crashed or what it was doing when it crashed. 

I can put the directory anywhere else in the file system except /home and it works fine. 

If the plugins directory does not exist, I get the log message "External plugins directory created", but I have searched the grafana source code for this message and can't find it. 

To reproduce, create a /home/grafana directory (or any other directory under /home) and set the permissions so you are sure grafana has complete access (to eliminate permissions as a problem. it also crashes without an error message with tighter permissions and different ownership, i.e. on /home/ubuntu):

mkdir -p /home/grafana/dashboard/grafana/plugins
chown -R grafana.grafana /home/grafana
chmod a+rwx /home/grafana

Edit the plugins directory definition in /etc/grafana.ini to:

plugins = /home/grafana/dashboard/grafana/plugins

rm /var/log/grafana/grafana.log

Restart grafana, and look at the log. It will complain about no enterprise license, then repeat again from the first log message when grafana crashes and restarts. 

The first message in my log is: "falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled."

What I really want to do is to simply work on developing a grafana plugin while it's off in its own directory under /home/ubuntu or whatever user directory I'm putting the repo in. I don't actually want to check ALL of the grafana plugins into the repo, only the examples (so I can play with them) and the ones I'm developing. Is there a better way to do that? Can Grafana support multiple plugin directories, some of which might be in /home? Can I use symbolic links? My experiments symlinking from /var/lib/grafana/plugins/myplugin to /home/... were just as unsuccessful. 

msg="Couldn't scan directory due to lack of permissions" logger=plugin.finder pluginDir=/var/lib/grafana/plugins err="stat /var/lib/grafana/plugins/myplugin: permission denied"

root@staging-dashboard:/var/lib/grafana/plugins# ls -l /var/lib/grafana/plugins
total 8
drwxr-x--- 4 grafana grafana 4096 Jan  8 03:40 doitintl-bigquery-datasource
lrwxrwxrwx 1 grafana grafana   58 Jan 29 14:47 myplugin -> /home/ubuntu/dashboard/grafana/plugins/myplugin
drwxr-x--- 3 grafana grafana 4096 Jan 11 08:18 yesoreyeram-infinity-datasource

root@staging-dashboard:/var/lib/grafana/plugins# ls -ld /home/ubuntu/dashboard/grafana/plugins/myplugin
drwxrwxrwx 7 grafana grafana 4096 Jan 29 13:36 /home/ubuntu/dashboard/grafana/plugins/myplugin

root@staging-dashboard:/var/lib/grafana/plugins# ls -ld /home/ubuntu/dashboard/grafana/plugins
drwxrwxrwx 7 grafana grafana 4096 Jan 29 13:35 /home/ubuntu/dashboard/grafana/plugins

root@staging-dashboard:/var/lib/grafana/plugins# ls -ld /home/ubuntu/dashboard/grafana
drwxrwxrwx 4 grafana grafana 4096 Jan 29 13:36 /home/ubuntu/dashboard/grafana

root@staging-dashboard:/var/lib/grafana/plugins# ls -ld /home/ubuntu/dashboard
drwxrwxrwx 5 grafana grafana 4096 Jan 29 13:36 /home/ubuntu/dashboard

root@staging-dashboard:/var/lib/grafana/plugins# ls -ld /home/ubuntu
drwxr-xr-x 8 ubuntu ubuntu 4096 Jan 29 14:38 /home/ubuntu

root@staging-dashboard:/var/lib/grafana/plugins# ls -ld /home
drwxr-xr-x 6 root root 4096 Jan 29 14:10 /home

But here is an interesting data point: If I copy /home/ubuntu/dashboard/grafana/plugins/myplugin into /myplugin and symlink to that, it works fine. So it definitely has something to do with /home. I also tried /home2/myplugin and that worked fine too. And I tried /home/myplugin and that did NOT work. And the permissions on the /home directory are just the same, and they are both on the same (root) device.  So somewhere in the code it's definitely checking for the "/home/" directory being in the path, not just a substring "home" in the path. 

root@staging-dashboard:/var/lib/grafana/plugins# ls -ld /home*
drwxr-xr-x 7 root root 4096 Jan 29 14:58 /home
drwxr-xr-x 2 root root 4096 Jan 29 14:58 /home2

This seems to be a related issue:

SymLink in default plugins folder causes server to not load any plugins #43012
https://github.com/grafana/grafana/issues/43012

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: postgresql
- OS Grafana is installed on: Ubuntu 20.04.3
- User OS & Browser: macOS Chrome
- Grafana plugins: yesoreyeram-infinity-datasource doitintl-bigquery-datasource grafana-plugin-examples and my own
- Others:

**Comment by marefr** [comment] 2022-01-31 11:01
Duplicate of #43012

**Comment by marefr** [comment] 2022-01-31 11:04
Trying to keep the number of open issues as low as possible. Thanks for this detailed report. Lets continue the discussions in #43012. This definitely looks like a permission problem, you need to make sure that the user account/group Grafana is running under has access to your home directory. Not sure either how you've installed Grafana, via debian/RPM repository?

**Closed by marefr** 2022-01-31 11:04 UTC
