### ISSUE TITLE
Time regions based on day/night time

### ISSUE THREAD

**Issue by blazewicz** [grafana/grafana#26603] opened 2020-07-26 07:29 UTC
**What would you like to be added**:

Option to set automatic time region adjustment based on calculated sunrise / sunset hours.

This could be implemented by adding a tick box enabling this feature which would disable default time selectors and enable an input field for location information.

Location information input may be shared with possible solution for #4123 and maybe #14400. 

Solution may for example use: https://github.com/mourner/suncalc

**Why is this needed**:

I see it in home automation and solar power generation. It would be useful to see daylight time regions which directly correlates with temperature and sunlight availability.

**Comment by torkelo** [comment] 2020-07-26 14:35
Dupe of https://github.com/grafana/grafana/issues/14400

**Closed by torkelo** 2020-07-26 14:36 UTC

**Comment by blazewicz** [comment] 2020-07-26 16:05
@torkelo #14400 is linked to #4123 because both are about hours displayed on time axis. What has to be done to resolve both these issues is to add option to override timezone for each graph and change time region selectors to match timezone which is displayed under the graph.

What I'm proposing here is to allow automatic adjustment of time region boundaries based on sunset/sunrise hours at given geographical location - it doesn't even depend on the timezone displayed under the graph. My proposition is different than both aforementioned and could be implemented independently.

I don't agree this a duplicate of issue you are pointing to, maybe you had different one on mind?

**Comment by torkelo** [comment] 2020-07-27 04:18
> What I'm proposing here is to allow automatic adjustment of time region boundaries based on sunset/sunrise hours at given geographical location 

Why this complicated solution instead of just timezone selection?

**Comment by blazewicz** [comment] 2020-07-27 08:30
> Why this complicated solution instead of just timezone selection?

Because timezones and duration of daytime are **not** same thing. Timezones only affect the offset of what my clock is showing relative to UTC.

Daytime is when sun is above the horizon - so when sunlight is shining in a given geographical location.

See examples for two different European cities that are in same timezone:

| city |date | sunrise (CET) | sunrise (UTC) | sunset (CET) | sunset (UTC) | day length
|-----|-----|---------------|---------------|--------------|---------------|-----------
Warsaw, Poland | December, 21st 2019 | 07:43 | 06:43 | 15:25 | 14:25 | 07:42
Madrid, Spain | December, 21st 2019 | 08:34 | 08:35 | 17:51 | 16:51 | 09:17
Warsaw, Poland | June, 21st 2020 | 04:14 | 03:14 | 21:01 | 20:01 | 16:46
Madrid, Spain | June, 21st 2020 | 06:44 | 05:44 | 21:48 | 20:48 | 15:03

So now when I want to see how temperature readings or power generation statistics are related to day/night time I would have to adjust time region boundaries every few weeks.

ref: https://www.timeanddate.com/sun

**Comment by javierin** [comment] 2020-11-24 17:44
I also agree that this would be very useful for graphing anything solar-energy related, for instance

**Comment by torkelo** [comment] 2020-11-25 06:09
This should be easily solved by using the sun and moon data source, https://grafana.com/grafana/plugins/fetzerch-sunandmoon-datasource 

either in mixed data source mode (mixing queries from different data sources), or as an annotation source

**Comment by dergreg** [comment] 2021-04-15 21:19
Has anyone found a solution already? I also could use this for displaying solar generation data
