### ISSUE TITLE
Unique Panel ID's that allow updates to be reflected across dashboards

### ISSUE THREAD

**Issue by tsully193** [grafana/grafana#18748] opened 2019-08-27 16:42 UTC
**What would you like to be added**:
Have panels have unique ID's across all dashboards allowing panels to be placed on multiple dashboards. This way any updates to a panel on one dashboard would be reflected on the other.

**Why is this needed**:
Currently if you copy a panel from one dashboard to another, you need to make any changes to the panel on both dashboards.

**Comment by dprokop** [comment] 2019-08-28 06:36
Duplicate of https://github.com/grafana/grafana/issues/1803

**Closed by dprokop** 2019-08-28 06:36 UTC
