### ISSUE TITLE
Add payload transformation for Webhook notification channel

### ISSUE THREAD

**Issue by fredwangwang** [grafana/grafana#26683] opened 2020-07-29 18:56 UTC
**What would you like to be added**:
Allow manipulating the structure of the json payload before sending it to the target.

**Why is this needed**:

Considering webhook channel is mostly used to integrating with 3rd party toolings that support webhook endpoints but does not have native integration with Grafana,
the json format generated by Grafana is almost definitely not directly consumable by the 3rd party toolings.

So right now the practice (at least I use) is to create an agent sits in between which simply transform and pass the payload to the consuming parts. This works but introduces an awkward and unnecessary piece in the mix.

So I propose to add the capability to manipulate and transform the payload in Grafana directly.

**How**
*This is just the current idea in my head but by no means have to be the way actually get implemented*

Add a transform field to the webhook settings. 
The transform will takes a javascript function which takes the payload as the argument, and return the transformed as result.
The javascript should run in a sandboxed setting with a timeout.

**Comment by torkelo** [comment] 2020-08-09 06:05
duplicate of https://github.com/grafana/grafana/issues/6956

**Closed by torkelo** 2020-08-09 06:05 UTC

**Comment by fredwangwang** [comment] 2020-08-09 06:09
Ah, thanks for linking to the original issue! Didn't realize there's one already.
