### ISSUE TITLE
Time Series inconsistent display between "last 12 hours" and "last 24 hours"

### ISSUE THREAD

**Issue by kdrapel** [grafana/grafana#61654] opened 2023-01-18 08:12 UTC
**What happened**:
A timeserie chart does not display the expected content when switching from "Last 12 hours" to "Last 24 hours". Part of the serie is not displayed. "Last 21 hours" is ok but "Last 22 hours" fails, see screenshots below.

**What you expected to happen**:
I would expect the content of the "Last 12 hours" to be visible in the "Last 24 hours", scaled down by 2. Nothing in the query is filtering out part of the data.

**How to reproduce it (as minimally and precisely as possible)**:

Last 12h:
![image](https://user-images.githubusercontent.com/12449790/213117032-c945ed1a-2b84-437c-abe4-748ef9c53078.png)

Last 20h:
![image](https://user-images.githubusercontent.com/12449790/213117893-e249e77c-17b6-4618-9a38-67c1a28b414c.png)

Last 21h:
![image](https://user-images.githubusercontent.com/12449790/213118062-e5477521-97cc-457b-b216-c73c2e452ed4.png)

Last 22h:
![image](https://user-images.githubusercontent.com/12449790/213118029-1dbfcd10-6092-4051-818b-c00091bc9eb9.png)

Last 24h:
![image](https://user-images.githubusercontent.com/12449790/213117235-e7cb99e7-01e8-47f0-95d7-2ec802584fbd.png)

Data for "last 24 h" (is suspicious, missing samples from morning 18th, **could the issue be linked to InfluxDB plugin**?)
![image](https://user-images.githubusercontent.com/12449790/213117758-31ffb07c-7b69-48c3-b0b2-c9e6e3fde091.png)

Data for last 12h (here I see the samples from morning 18th):
![image](https://user-images.githubusercontent.com/12449790/213118350-bdc6309f-9627-4b14-a992-b19d9ded76d3.png)

Query:
from(bucket: "${CONST_BUCKET}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "XXXXXXX")
  |> filter(fn: (r) => r["_field"] == "value")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "A")

`{
  "id": 706,
  "gridPos": {
    "h": 4,
    "w": 12,
    "x": 12,
    "y": 11
  },
  "type": "timeseries",
  "title": "XXXXXXXXXXXXX",
  "transformations": [
    {
      "id": "concatenate",
      "options": {
        "frameNameLabel": "{E6516E3A-0F55-4A00-A938-C5B54ADB8F27}",
        "frameNameMode": "label"
      }
    }
  ],
  "datasource": {
    "type": "influxdb",
    "uid": "${CONST_DATASOURCE}"
  },
  "pluginVersion": "9.1.4",
  "description": "XXXXXXXXXXXXX",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "smooth",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 30,
        "gradientMode": "scheme",
        "spanNulls": true,
        "showPoints": "never",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "lineStyle": {
          "fill": "solid"
        }
      },
      "color": {
        "mode": "thresholds"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 600
          },
          {
            "color": "red",
            "value": 800
          }
        ]
      },
      "unit": "none"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byType",
          "options": "number"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "${RES_QueueSize}"
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "showLegend": false,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "${CONST_DATASOURCE}"
      },
      "hide": false,
      "query": "from(bucket: \"${CONST_BUCKET}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"YYYYYYYYYYYYYYY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> yield(name: \"A\")",
      "queryType": "randomWalk",
      "refId": "A"
    }
  ]
}`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.2
- Data source type & version: InfluxDB v2.5.1
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: None

**Comment by tonypowa** [comment] 2023-01-23 13:02
👋  @kdrapel  and thank you for creating this issue

i am forwarding your question  to the observability metrics squad for further review

in the meantime, what is the value of [max data points](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/#query-options) in your query? I am asking about this detail since there were similar issues in the past (but with error message) [Reference](https://github.com/grafana/grafana/issues/26484#issuecomment-789662617).

**Comment by kdrapel** [comment] 2023-01-23 15:46
Dear @tonypowa, 
This is how the options are defined on that graph. I did not tweak the max data points, I usually leave the "aggregateWindow" do the work for me.
![image](https://user-images.githubusercontent.com/12449790/214082056-7487a758-939a-4db3-858b-074ca8bbed8e.png)

**Comment by itsmylife** [comment] 2023-02-07 13:54
@kdrapel Could you please provide a `.har` file for me with all the requests you made to reproduce the issue? 
12h, 20h, and 24h would be enough.

**Comment by kdrapel** [comment] 2023-02-07 15:20
Sorry but I tried to go back in time to try to reproduce the issue but I can't manage to have the same effect as what happened one month ago. 

![image](https://user-images.githubusercontent.com/12449790/217285921-89e05364-058c-4a3b-971f-4d1a72badcea.png)

Produce the wanted chart on 24h:
![image](https://user-images.githubusercontent.com/12449790/217285744-509d1bc1-c21a-4704-b02f-88e4a2718b5d.png)

**Comment by itsmylife** [comment] 2023-02-08 13:09
@kdrapel In that case, I suspect that the data was corrupted somehow and you got badly shaped data so it cannot be visualized. Since we cannot reproduce the issue can we close this one? Feel free to open a new one if you experience the same problem again. Adding a `.har` file would be quite useful for debugging the next time.

**Comment by kdrapel** [comment] 2023-02-08 13:39
Ok close it.

**Closed** 2023-03-28 15:10 UTC
Labels: datasource/InfluxDB, area/panel/timeseries
