### ISSUE TITLE
[Feature request] Customize X- axis with week dates, Months and years

### ISSUE THREAD

**Issue by yuva-phani** [grafana/grafana#8166] opened 2017-04-19 10:09 UTC
Hi, 
It would be great if X-axis can be customized.
For example i am having lot of data and i want to see data weekly,monthly and yearly. Right now it is difficult to understand the data by grafana graph because it is having x- axis as fixed.I am using grafana version 4.1.1 and data sources i am using are elastic search and influxdb.

Thanks,
Yuva Phani

**Comment by torkelo** [comment] 2017-04-19 13:17
duplicate of https://github.com/grafana/grafana/issues/3591

**Closed by torkelo** 2017-04-19 13:17 UTC
