### ISSUE TITLE
Time window for notification channels

### ISSUE THREAD

**Issue by jmalter** [grafana/grafana#33087] opened 2021-04-17 04:56 UTC
**What would you like to be added**:
The time window of the notification channels should be individually configurable

**Why is this needed**:
We have different support times. For example from Monday to Friday from 07:15 a.m. to 11:00 p.m. and on weekends from 08:00 a.m. to 09:00 p.m. It should be possible to configure this independently for each channel, as certain emergency alarms go via a different channel and sent to the service manager at any time.

As an example:
Alert CPUUtilization occurs on monday at 05:00. Alert should send via mail which has no timeframe config. The channel Google Chat should not be used, because alert is out of configurable timeframe. If alert still persists at 07:15 a.m., the alert should also sent via Google Chat.

This should configurable on the notification channel, not on the checks or on the receiving devices

**Comment by hugohaggmark** [comment] 2021-04-19 09:03
Duplicate of #6592

**Closed by hugohaggmark** 2021-04-19 09:03 UTC
Labels: bot/duplicate

**Comment by jmalter** [comment] 2021-04-19 09:48
This is not a duplicate, because we requested the configuration on notification channel

**Comment by hugohaggmark** [comment] 2021-04-19 12:11
> Time of day restrictions.
> 
> See two ways this could be implemented.
> 
> 1. As an alert condition
> 2. As a filter on notifications

I thought `2. As a filter on notifications` would cover your case @jmalter

**Comment by jmalter** [comment] 2021-05-22 05:57
Ok unsderstand that this is a duplicate, but for me it looks that no one is working on that PR to integrate it. Many requesting such a feature since a long time, than there is someone who provide a solution. And what happens? Sorry, for my direct words
