### ISSUE TITLE
Grafana 8.4 - server messages are all logged as "emerg" priority

### ISSUE THREAD

**Issue by kbbl1977** [grafana/grafana#45837] opened 2022-02-24 13:26 UTC
**What happened**:
When logging is configured to _syslog_, ale messages are logged with _emerg_ priority, regardless of what type of message is logged.

After update to 8.4.0 messgaes from grafana server started to appear on system console.
These were sent to Wall by systemd journal.
Grafana is configured to log via syslog:
`mode = syslog`
Journald is configured to forward _emerg_ level messages to **Wall**, thus these messages appear on system console to all users.

Problem is in grafana logger, as it emit all messages with **emerg** priority, reagardless what level is mentioned withing the message itself.

Here is a piece of grafana log:
```
2022-02-24T12:37:33.149+01:00 lbxovaa2 emerg grafana[46603]: logger=settings t=2022-02-24T12:37:33.14+0100 lvl=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
2022-02-24T12:37:33.151+01:00 lbxovaa2 emerg grafana[46603]: logger=settings t=2022-02-24T12:37:33.14+0100 lvl=info msg="Config loaded from" file=/etc/grafana/grafana.ini
```

The _emerg_ is message priority as reported by journal/syslog, however message itself states level as _lvl=info_.
The logger obviously send all messages to syslog port with _emerg_ priority/level.

**What you expected to happen**:
Messages should be sent to syslog port with correct priority/level - according to the message.

After grafana downgrade to 8.3.6 messages are correctly logged:
```
2022-02-24T14:10:06.124+01:00 lbxovaa2 info grafana[1223]: t=2022-02-24T14:10:06+0100 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=1223
2022-02-24T14:10:06.125+01:00 lbxovaa2 err grafana[1223]: t=2022-02-24T14:10:06+0100 lvl=eror msg="can't read datasource provisioning files from directory" logger=provisioning.datasources path=/etc/grafana/provisioning/datasources error="open /etc/grafana
/provisioning/datasources: no such file or directory"
```
As You can see, priority/level reported by syslog is the same as reported in the message itself.

**How to reproduce it (as minimally and precisely as possible)**:
This started happening after update to 8.4.0, still happen in 8.4.1.

**Anything else we need to know?**:
Downgrade to 8.3.6 fixes the problem.

This is relevant part of grafana config
```
[log]
mode = syslog
[log.syslog]
level = info
;format = text
;network =
;address =
facility = local4
tag = grafana
```

We update grafana packages from official repo:
```
[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
```

**Environment**:
- Grafana version: 8.4
- Data source type & version: n/a
- OS Grafana is installed on: Linux CentOS 7
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

Many thanks for help.

Best regards,
Tomas

**Comment by zuchka** [comment] 2022-02-24 19:25
Thanks for creating this issue, @kbbl1977 

really appreciate your thorough notes here. This looks like a duplicate of https://github.com/grafana/grafana/issues/45752, which was reported two days ago. I think I will close this issue as now, but make a note on that issue to look here for extra logging details 👍

**Closed by zuchka** 2022-02-24 19:25 UTC
