### ISSUE TITLE
Graphite Datasource with other panel request gets cancelled

### ISSUE THREAD

**Issue by ShilpaSivanesan** [grafana/grafana#11461] opened 2018-04-03 04:35 UTC
<img width="1323" alt="screen shot 2018-04-02 at 9 30 51 pm" src="https://user-images.githubusercontent.com/34906268/38229461-b73d93e4-36bd-11e8-9486-15f28ada4ee6.png">

**Comment by daniellee** [comment] 2018-04-03 07:41
Does this happen all the time? How big is the dashboard and how many requests are being sent to Graphite?

**Comment by ShilpaSivanesan** [comment] 2018-04-03 08:14
It happens when I do timeshift or moving average on graphite data. This is a test dashboard doesn't have much data. One of the promise gets cancelled on making request

**Comment by ShilpaSivanesan** [comment] 2018-04-03 08:26
Referred similar issue in Prometheus  https://github.com/grafana/grafana/issues/5459

**Comment by ShilpaSivanesan** [comment] 2018-04-03 13:08
I have reproduced the same issue 
set datasource as mixed
Add Query A -> graphite
Add Query B -> Druid

Query B gets cancelled
 the query after the graphite datasource query gets cancelled

<img width="1598" alt="screen shot 2018-04-03 at 6 05 19 am" src="https://user-images.githubusercontent.com/34906268/38251057-3aacf02a-3705-11e8-811a-4f7b3a5a4859.png">

**Comment by torkelo** [comment] 2018-06-29 10:47
dupe of https://github.com/grafana/grafana/issues/4453

**Comment by aocenas** [comment] 2020-09-16 08:47
@dprokop Hey this seems like a generic issue with mixed datasource, though I would assume it may be fixed. Can sombody from platform take a look?

**Comment by Gauravshah** [comment] 2020-09-16 11:07
@aocenas this is to do with how requestid is generated with graphite data-source plugin. rest of the data-source plugin seem to generate unique ids

**Comment by torkelo** [comment] 2020-09-16 11:53
Once https://github.com/grafana/grafana/pull/26151 is completed we can remove the requestId all together as we do ńot need it for cancellation when using the new Observable api

**Comment by ifrost** [comment] 2021-03-29 20:16
A lot has changed since the issue was reported. All Graphite requests are now going through the proxy and multiple queries for the same data sources are grouped in a single request so it should no longer be a problem.

**Closed by ifrost** 2021-03-29 20:16 UTC
Labels: area/datasource, datasource/Graphite, priority/important-longterm, type/bug
