### ISSUE TITLE
Can't edit panel in Chrome in Grafana 7.2.1

### ISSUE THREAD

**Issue by veer123prathap** [grafana/grafana#32626] opened 2021-04-02 05:12 UTC
What happened:
Clicking on the panel doesn't open an edit menu in Chrome.

What you expected to happen:
That it opens a menu, in safari.
**Environment**:
- Grafana version: 7.2.1
- Data source type & version: Prometheus, elastic search
- OS Grafana is installed on: linux
- User OS & Browser: chrome 89.0.4389.90 (Official Build) (32-bit)
- Grafana plugins: all
- Others:
we try on incognito mode also panel doesn't open an edit menu.

![grafana](https://user-images.githubusercontent.com/62214817/113383180-f575d280-9348-11eb-8435-31c4e16b2a0a.PNG)

**Comment by superbool** [comment] 2021-04-02 08:28
#31374

**Comment by ravi7248** [comment] 2021-04-03 07:43
I am using Grafana 7.4 and I use only chrome for editing the panels, running queries, and for everything and it works like a charm.
Try to delete cookies in your browser may be that will help

**Comment by zoltanbedi** [comment] 2021-04-03 08:52
Duplicate of #31374, thanks @superbool.

**Closed by zoltanbedi** 2021-04-03 08:52 UTC
