### ISSUE TITLE
Cannot remove provisioned permissions

### ISSUE THREAD

**Issue by exander77** [grafana/grafana#53937] opened 2022-08-19 11:02 UTC
After upgrade to version 9, there is no possibility of removing provisioned permissions.
Another user described it well in the discussion: https://github.com/grafana/grafana/discussions/52903

Here We have removed permissions in the previous version:
![image](https://user-images.githubusercontent.com/2256039/185604816-54001880-edb8-4333-a7bb-ce4d091f19f1.png)
This is the new version and there is no possibility to remove them:
![image](https://user-images.githubusercontent.com/2256039/185604992-78b8314a-2469-44bb-b71b-23792e94dfd9.png)

**Comment by zuchka** [comment] 2022-08-19 20:41
duplicate of #52903 

we can convert the discussion back to an issue as needed

**Closed by zuchka** 2022-08-19 20:41 UTC

**Comment by exander77** [comment] 2022-08-19 20:43
@zuchka I suggest turning it into issue as I have no idea how to remove those provisioned permissions.
