### ISSUE TITLE
Status History: missing date / timestamp on mouse over

### ISSUE THREAD

**Issue by r2ixuz** [grafana/grafana#54112] opened 2022-08-23 17:46 UTC
**What happened**:
When hovering over there is no more a date / timestamp visibile:

<img width="810" alt="Bildschirmfoto 2022-08-23 um 19 41 40" src="https://user-images.githubusercontent.com/15087554/186228037-4df30b71-a5aa-4c90-8b02-18a739990495.png">

**What you expected to happen**:

Mouse over  a value should show also the timestamp as it was befor v9.1.

**How to reproduce it (as minimally and precisely as possible)**:

Use Status History diagram. Point your cursor over an entry.

**Anything else we need to know?**:

I believe this started with version 9.1.

**Environment**:
- Grafana version: 9.1.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: Docker
- User OS & Browser: MacOS , Chrome
- Grafana plugins:
- Others:

**Comment by gelicia** [comment] 2022-08-23 17:53
Duplicate of #54034

**Closed by gelicia** 2022-08-23 17:53 UTC
