### ISSUE TITLE
Concurrent requests causing 401 Unauthorized and logging users out

### ISSUE THREAD

**Issue by davidbhoward** [grafana/grafana#31360] opened 2021-02-19 20:43 UTC
**What happened**:
The `grafana_session` cookie is being refreshed on one request, such as `/api/datasources/proxy/1/api/v1/query_range?`, with a `Set-Cookie: grafana_session=xxx`, but another concurrent request, such as a `/api/datasources/proxy/1/api/v1/label/__name__/values?start=yyy&end=zzz` has already been sent using the old cookie, causing a 401 Unauthorized, thus destroying the session on `grafana_session` cookie which logs the user out.  

**What you expected to happen**:
Not to be logged out when editing a dashboard when I just logged in minutes earlier.  

**How to reproduce it (as minimally and precisely as possible)**:
I was able to reproduce this by going to a dashboard with variables and several panels.  Edit a single panel and set the refresh interval to be 1 min.  Open the network tab, and watch the calls.  I would see one call to `/api/datasources/proxy/1/api/v1/query_range?` that has a `Set-Cookie: grafana_session=xyz` header.  At the time of that request, I have 4 other calls to `/api/datasources/proxy/1/api/v1/label/__name__/values`.  Two calls are using the old cookie values and 2 calls are using the new cookie values.  One of the old cookie values causes a 401 Unauthorized, which then destroys the existing `grafana_session` cookie with `Set-Cookie: grafana_session=`.

**Anything else we need to know?**:
We have looked at all of our settings now and we don't see one that is documented that could help us.  We suspect this is a bug in how things behave.  

**Environment**:
- Grafana version: v7.3.4 (14c494085e)
- Data source type & version: Thanos v0.17.2
- OS Grafana is installed on: Centos 7
- User OS & Browser: macOS Catalina v10.15.7 and Google Chrome v88.0.4324.182
- Grafana plugins: Prometheus (default), Alert list, Azure Monitor, Bar gauge, CloudWatch, Dashboard list, Elasticsearch, Gauge, Gettings Started, Google Cloud Monitoring, Grafana Image Renderer, Graph, Graphite, Heatmap, Home links, Influx Admin, InfluxdDB, Jaeger, Logs, Loki, Microsoft SQL Server, MySQL, News, OpenTSDB, Pagerduty, Pie Chart, Plugin list, Polystat, PostgreSQL, Prometheus AlertManager, Singlestat, Stat, Table, Table (old), Tempo, TestData DB, Text, Welcome, Zipkin
- Others: Grafana server is running in docker within K8s environment.  Netscaler sits in front of the Grafana server for load balancing.

**Comment by davidbhoward** [comment] 2021-03-16 17:49
I dug into this a bit more and this is also happening on my home network as well.  I have more information about the probable cause here.  

The configuration is out of box configuration, so nothing special is needed.  Once you create a dashboard and then go back in to edit a panel from that dashboard, with refresh on say 1m, this is when you hit this bug. 

From what I can tell a token rotation happens in the middle of a "refresh dashboard" request sequence.  Because there are multiple calls, it looks to be successful on the first request but the second request the token has rotated, but you have sent in the previous token, then Grafana sees that the current token isn't valid and then removes the cookie altogether, causing you to now be unauthorized.

Let me know if you need any more information here @peterholmberg.

**Comment by marefr** [comment] 2021-04-20 11:49
Duplicate of #15316

**Comment by marefr** [comment] 2021-04-20 11:49
See update in latest comment in that issue.

**Closed by marefr** 2021-04-20 11:49 UTC
Labels: area/frontend/login, priority/awaiting-more-evidence, type/bug
