### ISSUE TITLE
Support cross tabulation barplot visualization with 2 categorical axes

### ISSUE THREAD

**Issue by holgerbrandl** [grafana/grafana#19994] opened 2019-10-24 13:40 UTC
**What would you like to be added**:
Consider the following table
```
CREATE TABLE Sales (Store varchar, Product varchar, num_sold int);

INSERT INTO Sales VALUES ('B','Table',46);
INSERT INTO Sales VALUES ('B','Hat',3);
INSERT INTO Sales VALUES ('B','Chair',7);
INSERT INTO Sales VALUES ('C','Trousers',9);
INSERT INTO Sales VALUES ('C','Table',10);
INSERT INTO Sales VALUES ('C','Hat',3);

Select * from Sales;
```
![image](https://user-images.githubusercontent.com/200952/67479175-cb9d8400-f65d-11e9-8982-220c6051f6bd.png)

Currently there is no way to visualize these data as bar plot as in
![image](https://user-images.githubusercontent.com/200952/67496021-11694500-f67c-11e9-93a3-714d9ceead51.png)

The current support for stacked bar charts, always seems to require a time axis to work.

**Why is this needed**:
* Cross-tabulation is one of the most central pieces of BI. 
* Most other BI tools can visual this type of data as stacked barchart.

**Comment by oholimoli** [comment] 2019-11-01 14:49
Yes please support bar charts :+1:

**Comment by marefr** [comment] 2019-11-04 12:52
Duplicate of #7798

**Closed by marefr** 2019-11-04 12:52 UTC

**Comment by dzhydyk** [comment] 2021-05-20 06:50
Is there a chance that this will be implemented?
