### ISSUE TITLE
new version 6.6.0 stat box color null values

### ISSUE THREAD

**Issue by pperezm77** [grafana/grafana#21862] opened 2020-01-31 07:53 UTC
**Whathappened:** 
 I have a problem with set color of new stat box in a new version 6.6.0 of Grafana, Concretly it doesn't allow to change the color for null values, only the box turns green and doesn't do anything.

**What you expected to happen:** 
The box allows establish color for null values and title.

**How to reproduce it (as minimally and precisely as possible):** 
if you create a stat box with no data associate you can see this.

**Anything else we need to know?:** 
N/A

**Environment:** 

Grafana version: 6.6.0
Data source type & version: ElasticSearch Index
OS Grafana is installed on: centos 7
User OS & Browser: Ubuntu 18.4, Google Chrome
Grafana plugins: Stat

**Comment by marefr** [comment] 2020-01-31 10:44
Duplicate of #21810

**Closed by marefr** 2020-01-31 10:45 UTC
