### ISSUE TITLE
Renderer crops images if more then 1 row/panel exists in dashboard

### ISSUE THREAD

**Issue by Mikesch-mp** [grafana/grafana#11213] opened 2018-03-12 21:22 UTC
If you use dashboards with some panels in it the renderer will crop the images. If you add rows, rendered image will look ok again.

Please see [issue #127](https://github.com/Mikesch-mp/icingaweb2-module-grafana/issues/127) in my repository for images.

**Comment by bergquist** [comment] 2018-04-11 12:39
@daniellee is this related to the current work on phantomjs?

**Comment by Mikesch-mp** [comment] 2018-05-29 05:04
Any news on this issue?

**Comment by torkelo** [comment] 2018-05-29 06:53
This has nothing to do with rows but a legend that does not fit the request backend image rendering (hard to have a scrollbar in a PNG).  This has always been a problem in Grafana. It's a bit tricky as the rendering API takes a width and height of the final image, to show the complete legend Grafana would have to violate those dimensions.

**Comment by Mikesch-mp** [comment] 2018-05-29 09:27
Sorry title is misleading. Images get cropped when using renderer and you have multiple rows in your dashboards with Grafana 5+.

**Comment by marefr** [comment] 2018-05-29 10:27
If it's only the legend that gets cropped due to scrolling then it's as it always have been like Torkel commented. If there's other things being cropped this might be a bug, but I haven't been able to reproduce any using a dashboard multiple rows and trying a lot of different renderings of different panels in that dashboard.

You're trying to render a png of one panel only right?

**Comment by Mikesch-mp** [comment] 2018-05-29 12:14
The image itself is cropped, see pictures in the issue i mentioned. the left y-axis is cropped in this pic for example
![image](https://user-images.githubusercontent.com/6574967/40658124-7a114baa-634a-11e8-94af-9eb27d77be46.png)

**Comment by marefr** [comment] 2018-05-29 12:32
Have you tried using Grafana v5.1.3? If so, could you please export your dashboard and include it here. Thanks

**Comment by torkelo** [comment] 2018-05-29 14:06
unable to replicate this, the legend gets cropped if it cannot fit in the requested height. Closing as this as you changed it back to strange title :)

**Closed by torkelo** 2018-05-29 14:06 UTC
Labels: type: feature request
