### ISSUE TITLE
Unable to provision multiple Notification policies using file provisioning

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#66324] opened 2023-04-11 21:08 UTC
Grafana 9.4.7

**What happened**:
I'm attempting to provision all of my unified alerting configuration via yaml files.  I've been able to get contact points and alert rules provisioned however I'm having some strange issues with Notification policies.  I can get it to provision a single policy but I can't figure out how to provision more than 1.

If I use something like this:
```
apiVersion: 1
policies:
  - orgId: 1
    receiver: Teams
    routes:
      - receiver: Teams
        object_matchers:
          - [ 'Teams', '=', 'True' ]
  - orgId: 1
    receiver: GoAlert
    routes:
      - receiver: GoAlert
        object_matchers:
          - [ 'GoAlert', '=', 'True' ]
```

Then I only end up with the GoAlert Notification policy.  I don't see anything mentioned in the logs about why one is getting ignored or any errors or anything like that.  I've also tried breaking each of these out into multiple files and I still only end up with 1 getting created.  I also am seeing that using this configuration grafana is saying that my root notification policy has been configured via provisioning and cannot be edited but I don't think I've done anything here that should or would be touching the root notification policy?
![Notification_policies_-_Alerting_-_Grafana](https://user-images.githubusercontent.com/5891946/231287679-adf074c2-ce16-4734-9c35-b68a27d33d16.jpg)

It would be nice if the examples that you gave showed had to add multiples of things.  For example, with contact points I was not able to determine how to provision multiple contact points in a single file so I've had to break each one out into it's own file but I'm suspecting there's a better way to do this but I don't see it mentioned in any docs anywhere.

**What you expected to happen**:

To be able to create multiple notification policies and to have documentation that is useful.

**How to reproduce it (as minimally and precisely as possible)**:

Use example yaml above and put that in your provisioning folder

**Comment by danfinn** [comment] 2023-04-11 21:25
Made some progress through trial and error, this seems to work:
```
apiVersion: 1
policies:
  - orgId: 1
    receiver: BMAP_MSTeams
    routes:
      - receiver: BMAP_MSTeams
        object_matchers:
          - [ 'Teams', '=', 'True' ]
      - receiver: BMAP_GoAlert
        object_matchers:
          - [ 'GoAlert', '=', 'True' ]
```

However I still end up with grafana saying that my root notification policy has been configured and can't be altered when I don't think I've done anything to configure that.

There is still the issue with the API request not working and it would also be nice to see some examples like this in the documentation.

**Comment by tonypowa** [comment] 2023-04-14 09:42
hello @danfinn 

thanks for creating this issue

this is the first time I ever provisioned a notification policy, so apologies if the bellow does not help you.

for me, provisioning works as long as the  `receiver` (line 4 in your yaml) makes reference to the root policy

you could check your notification policy tree via  [this api](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idroute-get-policy-treespan-get-the-notification-policy-tree-_routegetpolicytree_) `/api/v1/provisioning/policies ` and follow the json structure for your provisioning file .
Here is how my notification policy looks like, and how it matches my policy provisioning file.

api response in JSON:

``` json
{
    "receiver": "paco-test",
    "routes": [
        {
            "receiver": "paco-test",
            "object_matchers": [
                [
                    "Teams",
                    "=",
                    "True"
                ]
            ]
        },
        {
            "receiver": "go-alert",
            "object_matchers": [
                [
                    "GoAlert",
                    "=",
                    "True"
                ]
            ]
        }
    ],
    "provenance": "file"
}
```
yaml file:

``` yaml

apiVersion: 1
policies:
  - orgId: 1
    receiver: paco-test
    routes:
      - receiver: paco-test
        object_matchers:
            - [ 'Teams', '=', 'True' ]
      - receiver: go-alert
        object_matchers:
            - [ 'GoAlert', '=', 'True' ]

``` 

view of provisioned policies in the ui:

![image](https://user-images.githubusercontent.com/45235678/232008039-6aecccc2-f75f-4523-9c4b-1da87ccdb825.png)

**Comment by tonypowa** [comment] 2023-04-14 09:58
> Have some issues too where Grafana crashes as it says either mute timings or contactPoints do not exists eventhough they are defined in the same file and first.
@jcdauchy-moodys 
i believe the contact points need to already be there before you can provision the policy(ies)

i'd try that and if you still get an error, please find it in the logs and copy paste it here

More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by alexweav** [comment] 2023-04-14 16:24
Right now we only support provisioning of the notification policy tree, of which there is only 1. You'll need to add your individual policies as entries under `routes` in the policy object - but the entire tree will still provisioned together.

This is an unfortunate consequence of how prometheus-style trees work. Policy entries can override other policy entries if they both match labels on the same alert - this means that if we allowed policies to be provisioned separately, the order of the individual policies becomes undefined and the behavior would be not deterministic in the event that multiple policies match the same rule. In this case, you could provide the same file to multiple installations, and they would have different behavior, which is something we didn't like.

**Comment by ryan-grafana** [comment] 2023-04-14 16:26
closing this as it's not a bug. we will consider file based policy provisioning without requiring the full tree in future feature builds.

**Closed by ryan-grafana** 2023-04-14 16:26 UTC
Labels: needs more info, area/alerting
