### ISSUE TITLE
Does grafana 5.0 work only with "real Amazon s3"?

### ISSUE THREAD

**Issue by Zlogene** [grafana/grafana#11240] opened 2018-03-14 12:09 UTC
Hello!

 We are using grafana 5.0 and try to set up picture sending along with the alerts. We are using Digital Ocean endpoint for this purpose, but `grafana.log` says that it was not able to find bucket settings for `image.uploader.s3`.

Does `s3` service restricted to only amazon, or maybe there is something we have done wrong?

**Comment by bergquist** [comment] 2018-03-14 16:31
The image uploaders we support are AWS/GCP/Azure and webdav. I'm not sure how Digital Ocean works so its hard us to answer. I'm closing this issue since its a question and not a bug/feature request.

**Closed by bergquist** 2018-03-14 16:31 UTC
