### ISSUE TITLE
FR: export datasources as json

### ISSUE THREAD

**Issue by cdanis** [grafana/grafana#14600] opened 2018-12-19 15:20 UTC
I help run a Grafana instance for a medium-sized organization.  We're interested in migrating to 'provisioning' datasources as JSON files that would live in our Puppet repo, but we have about 20 datasources.

It'd be awesome if there was some way to export the current datasources as JSON.  Would hate for a typo in one of the files I'll have to write by hand to break a bunch of our dashboards.

**Comment by torkelo** [comment] 2018-12-19 15:36
duplicate of https://github.com/grafana/grafana/issues/11495

**Closed by torkelo** 2018-12-19 15:36 UTC
