### ISSUE TITLE
Add variable type : time range

### ISSUE THREAD

**Issue by andrew2015** [grafana/grafana#11234] opened 2018-03-14 06:09 UTC
In my case, I want to add one panel with time range 3month at top, and the detail panels for one specific day in following, this need change the time range be panel related and not global.

**Comment by marefr** [comment] 2018-03-14 08:30
Duplicate of #8267 so will close this. However in your case you can use the override relative time feature per panel to solve your problem.

**Closed by marefr** 2018-03-14 08:30 UTC

**Comment by andrew2015** [comment] 2018-03-15 01:44
Thanks @marefr . The feature #8267 is what I need, is there a schedule for that feature delivery ?
