### ISSUE TITLE
Hide zero/null values in time series panel

### ISSUE THREAD

**Issue by jesjimher** [grafana/grafana#35598] opened 2021-06-13 10:26 UTC
**What would you like to be added**:
Time series panel is looking great and almost there to be able to completely replace old graph panel, but I still miss the option for hiding null/zero values in legend, when there's no data in the current view.

**Why is this needed**:
That's a very useful feature that allows having a clean legend when there's a lot of queries in a panel, but not all of them have data all the time (for example, a plot of power consumption of a home, separated by appliance).

It would also give time series panel feature parity with graph panel, which would make transition easier.

Thanks and congratulations for such a great piece of software!

**Comment by torkelo** [comment] 2021-06-13 16:02
duplicate of #35592

**Closed by torkelo** 2021-06-13 16:02 UTC
