### ISSUE TITLE
Notification Slack  (RocketChat) Failed : Include image

### ISSUE THREAD

**Issue by osauzet** [grafana/grafana#22506] opened 2020-03-02 08:05 UTC
**What happened**:
When I configure notification for RocketChat channel, I use the Slack templage. I dont want to use "Include Image", but when i look to the rocketchat log, i can see field : -> image_url: ''   empty !
With this empty value, the notification doesn't work :-(

**What you expected to happen**:
I think that if I do not choose to include an image, this field should not be sent at all ... (because sending it empty, it generates an error)

**How to reproduce it (as minimally and precisely as possible)**:
When i use CURL, i can confirm empty image_url break the notification : 

Work ->
curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://commons.wikimedia.org/wiki/File:Grafana_screenshot.png","color":"#764FA5"}]}' https://rocketchat.iut-larochelle.fr/hooks/ABCDXxxx

Work ->
 curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","color":"#764FA5"}]}' https://rocketchat.iut-larochelle.fr/hooks/ABCDXxxx

don't work :  
curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"","color":"#764FA5"}]}' https://rocketchat.iut-larochelle.fr/hooks/ABCDXxxx

**Anything else we need to know?**:
I tested the proposed script here without success :  https://github.com/RocketChat/Rocket.Chat/issues/11506#issuecomment-407445878

**RocketChat log:**

 I20200302-09:03:00.364(1) server.js:204 API ➔ debug POST: /hooks/ABCDXxxx 
I20200302-09:03:00.366(1) server.js:204 Integrations ➔ Incoming WebHook.info Post integration: Grafana 
I20200302-09:03:00.369(1) server.js:204 Integrations ➔ Incoming WebHook.debug @urlParams: {   integrationId: 'bJRNxDonNBctWZ958',   token: 'ABCDXxxx' } 
I20200302-09:03:00.370(1) server.js:204 Integrations ➔ Incoming WebHook.debug @bodyParams: {   attachments: [     {       color: '#D63232',       fallback: '[Alerting] Test notification',       fields: [Array],       footer: 'Grafana v6.6.2',       footer_icon: 'https://grafana.com/assets/img/fav32.png',       image_url: '',       text: ' Someone is testing the alert notification within grafana.',       title: '[Alerting] Test notification',       title_link: 'http://localhost:3000/grafana/',       ts: 1583136180     }   ],   channel: '#sige-alert',   parse: 'full',   username: 'rocket.cat' } 
I20200302-09:03:00.373(1) server.js:204 API ➔ debug Failure {   statusCode: 400,   body: {     success: false,     error: 'Invalid href value provided',     stack: undefined   } }  

**Environment**:
- Grafana version: v6.6.2 (3fa63cfc34)
- RocketChat : 3.0.0
- OS Grafana is installed on: Debian 9.12
- User OS & Browser: FreeBSD , FireFox and Chrome

**Comment by aocenas** [comment] 2020-03-02 21:01
@marefr do you know who would be best to check this?

**Comment by marefr** [comment] 2020-03-03 08:34
@aocenas hmm think @aknuds1 merged a fix for this a while ago so please check with him.

**Comment by aknuds1** [comment] 2020-03-04 09:04
@aocenas @marefr Yeah I did merge a PR that should fix this issue: #22372.

@osauzet A fix for this is part of our master branch and will be released with 6.7.0.

**Closed** 2020-03-04 09:05 UTC

**Comment by aknuds1** [comment] 2020-03-04 09:06
Duplicate of #21709.

**Comment by osauzet** [comment] 2020-03-04 09:45
@aocenas @aknuds1 thank-you for your prompt response and the modification for 6.7 :-) !

**Comment by aknuds1** [comment] 2020-03-04 09:50
You're welcome!
