### ISSUE TITLE
Bug: direct link rendered images truncate legend 

### ISSUE THREAD

**Issue by PRI-mcallen** [grafana/grafana#1791] opened 2015-04-15 22:09 UTC
When sharing images that are linked to a direct rendered image that has many time series, the legend is truncated and will only show a subset of the series names/colors.  This is an issue if the legend wraps to multiple lines.

**Comment by torkelo** [comment] 2015-04-16 05:17
Fixed yesterday, https://github.com/grafana/grafana/issues/1786
dupe of https://github.com/grafana/grafana/issues/1749

However your case, having multiple series that wrap to a second line is not fixed. You will have to increase the width of the image to make the legend fit on one row or change it into a table legend. 

It is pretty tricky to calculate the height of the legend before rending (something that is done), it can be done for single line legends (that do no wrap) and for table legends. If a single line legend wrap however it becomes tricky. You would have to calculate before the legend html elements are drawn that they would wrap and cause two lines.

**Closed by torkelo** 2015-04-16 05:17 UTC
