### ISSUE TITLE
Unable to split Time Series Aggregation queries across multiple columns of table panel

### ISSUE THREAD

**Issue by LF-Tech** [grafana/grafana#10202] opened 2017-12-14 00:00 UTC
Please include this information:
- What Grafana version are you using?
	Grafana v4.6.2 (commit: 8db5f08) 
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
unRAID Docker

I have a table panel set up to display Free Space for each of my disks. See images for Table Panel and Query settings. 
 
![image](https://user-images.githubusercontent.com/26773970/33968714-084a3fde-e02f-11e7-9dd0-e54999dcafc6.png)

![image](https://user-images.githubusercontent.com/26773970/33968772-5fa86530-e02f-11e7-9e0d-875562ddae05.png)

I would like to set up additional queries in this table for Used Space and Total Space to be displayed across additional columns. When adding the queries they add additional rows and there appears to be no capability to split queries across columns.

**Comment by bergquist** [comment] 2017-12-14 09:07
Table panel does not support merging multiple queries right now. 

Dupe of https://github.com/grafana/grafana/issues/9170

Will be fixed by https://github.com/grafana/grafana/pull/10050 soonish

**Closed by bergquist** 2017-12-14 09:07 UTC
