### ISSUE TITLE
Grafana does not show prometheus anotations involving min

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#32133] opened 2021-03-18 17:57 UTC
**What happened**:
I have an annotation that is not shown, I couldn't find a tool to debug it more like I can do with queries.
the following graph uses the same annotations logic:
`min(scylla_node_ops_finished_percentage) by(instance, ops)<1.0`
As can be seen the graph is there but the annotation is not.
![image](https://user-images.githubusercontent.com/2118079/111673400-9b8eec00-8823-11eb-8d51-7ee083e499d8.png)
**What you expected to happen**:
to show an anotation:
**How to reproduce it (as minimally and precisely as possible)**:
This is the dashboard I'm using:
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      },
      {
        "datasource": "prometheus",
        "enable": true,
        "expr": "min(scylla_node_ops_finished_percentage) by (instance,ops,dc)<1.0",
        "hide": false,
        "iconColor": "rgba(255, 96, 96, 1)",
        "name": "ops",
        "showIn": 0,
        "tagKeys": "instance,ops,dc",
        "target": {},
        "titleFormat": "ops"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 9,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "prometheus",
      "fieldConfig": {
        "defaults": {},
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "7.5.0-beta1",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "min(scylla_node_ops_finished_percentage) by (instance,ops,dc)<1.0",
          "interval": "",
          "legendFormat": "",
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard Copy",
  "uid": "Wmzo6nQGz",
  "version": 1
}
```
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3 (I tried 7.5.beta but it didn't work)
- Data source type & version: prometheus
- OS Grafana is installed on: docker
- User OS & Browser: chrome
- Grafana plugins: N/A
- Others:

**Comment by ivanahuckova** [comment] 2021-03-23 13:48
Hello @amnonh, could you please share the response from network tab when you turn on the annotation. Cause on grafana.play.org I was able to create annotations using prometheus query with min. 
![image](https://user-images.githubusercontent.com/30407135/112156439-8a106000-8be6-11eb-87c3-691bc8b41ad9.png)

Just wondering if your query is returning data - because in here - I have query that doesn't return any data and therefore annotation is not rendered. 
![image](https://user-images.githubusercontent.com/30407135/112156704-c93eb100-8be6-11eb-8605-aab2ca8b9734.png)

**Comment by amnonh** [comment] 2021-03-23 16:28
Thanks @ivanahuckova  for trying to solve the issue, this is how it looks like:
![Screenshot from 2021-03-23 18-24-20](https://user-images.githubusercontent.com/2118079/112181761-601a6600-8c05-11eb-90d9-7bbbac47dfa0.png)
As you can see I do get results, previously what i did was to put the same anotation query on a panel and see it as well, I remove that for the screenshot just to make it cleaner.

**Comment by ivanahuckova** [comment] 2021-03-26 12:44
Let's try to pass it to @grafana/grafana-frontend-platform as from what I can see, we receive correct data from Prometheus, but they are not displayed in the graph panel as Annotations. I tried to reproduce this couple times, but wasn't able to. So not sure what could be the cause, because everything looks correct.

**Comment by jackw** [comment] 2021-03-30 13:20
@amnonh we spent a bit of time trying to investigate this further and from looking at the screenshots you've uploaded we're wondering what is the dashboard time range and if the timestamps in the annotations response fit into it? (For example the graph shows a time range of 18:08 - 18:22 but the annotations have timestamps for 16:00 - 16:15.)

**Comment by amnonh** [comment] 2021-03-31 06:37
@jackw The time looks confusing because I used utc for that dashboard, but as I mentioned, to verify that the annotation should work, I used a panel with the anotation metric (see the first image in this issue).
I also tested it with browswer time and got the same results.

I did test it with Prometheus 2.25.2 not sure if it maters.

**Comment by oscarkilhed** [comment] 2021-04-06 08:11
As we can't reproduce this, we're going to close it. If there is additional reports of this issue we can always open it up again.

**Closed by oscarkilhed** 2021-04-06 08:11 UTC
Labels: area/annotations, area/dashboard, area/panel/graph, needs investigation
