### ISSUE TITLE
Graph panel legend expands on mouseover

### ISSUE THREAD

**Issue by cartw** [grafana/grafana#12726] opened 2018-07-26 09:44 UTC
As per comments in #11830 opening a new issue as I still see this behaviour. 
Please include this information:
### What Grafana version are you using?
5.2.2, also observed in 5.2.1.
### What datasource are you using?
Graphite / Elasticsearch

### What OS are you running grafana on?
Various Ubuntu, and reproduced locally on MacOS 

### What did you do?
Using Firefox - 61.0.1 - I created a graph panel with multiple metrics and set the legend to a table on the right.   
e.g.
<img width="420" alt="screen shot 2018-07-26 at 10 17 00" src="https://user-images.githubusercontent.com/41674477/43254082-75d0382a-90be-11e8-8fa9-a6d94e49a6eb.png">
<img width="524" alt="screen shot 2018-07-26 at 10 16 50" src="https://user-images.githubusercontent.com/41674477/43254090-7baf9812-90be-11e8-9a3c-662894204bfb.png">

### What was the expected result?
Legend table would remain static on the right side of the panel.  

### What happened instead?
When the legend contained enough entries to require a scroll bar in the given panel size, each mouse over / away from the legend causes the metric names to shift left by 15 pixels, gradually moving over the graph itself. 
<img width="814" alt="screen shot 2018-07-26 at 10 16 31" src="https://user-images.githubusercontent.com/41674477/43254256-e9f7e2de-90be-11e8-8c51-54468a9ced6e.png">

Eventually it will move further and further left until it the legend is the full width of the panel
This seems related to the scroll bar, since this is only drawn when the mouse is over the legend, so each mouse event causes the scrollbar to either be drawn or removed and at  the same time the metric names move left. 

Using the FF inspector you can see the various width attributes of the legend div increasing by 15 pixels with each switch on/off of panel-hover-highlight on the panel-container div.
![screen shot 2018-07-26 at 10 38 02](https://user-images.githubusercontent.com/41674477/43254948-703b82dc-90c0-11e8-8cb6-e5ec3801a5fe.png)
![screen shot 2018-07-26 at 10 38 12](https://user-images.githubusercontent.com/41674477/43254949-70569126-90c0-11e8-8b27-786c17c19e24.png)
![screen shot 2018-07-26 at 10 39 07](https://user-images.githubusercontent.com/41674477/43254951-706f536e-90c0-11e8-8508-88e243ec0ee7.png)

If the Legend is given a fixed width in the Panel options the behaviour is different - the metric names stay on the left but the scroll bar moves to the right on mouse events until is reaches the max width of the panel. This is less noticeable or annoying, but probably related.

I can't reproduce on Chrome so this seems to be a Firefox issue.

**Comment by davkal** [comment] 2018-07-26 12:18
Can repro on FF mac v61, but not on chrome. Investigating...

**Comment by davkal** [comment] 2018-07-26 13:08
I think we're hitting a FFMAC special case in baron, our scroll handler. It adds padding (15px) on each scroll element update: 
https://github.com/Diokuz/baron/blob/master/src/core.js#L596

The update here is triggered on an animation or transition event on hover:
https://github.com/Diokuz/baron/blob/master/src/core.js#L209

To verify, you can change your user agent to not match the regexp in https://github.com/Diokuz/baron/blob/master/src/core.js#L46 and the issue disappears.

My guess is that baron no longer needs this special treatment in FF61 /cc @Diokuz

**Comment by marefr** [comment] 2018-07-26 13:36
Not really sure what to do with this since I don't think we can change the behavior of baron, our third party scroll library. The only thing we can do is to file a bug report for baron and hope for the best.

**Comment by davkal** [comment] 2018-07-26 13:47
Could fork baron, make a PR, and use that fork's branch build in Grafana until this is fixed upstream. I'll create an issue there first. Let's see what happens.

**Comment by marefr** [comment] 2018-07-26 13:55
I would rather not maintain a fork of baron so lets see if there are any response to the issue.

**Comment by marefr** [comment] 2018-07-26 13:57
Guess we could submit a PR for it without incorporating it in Grafana

**Comment by marefr** [comment] 2018-07-26 19:41
@torkelo do you have any input regarding this?

**Comment by ViViDboarder** [comment] 2018-10-29 15:59
Any more thoughts on this? Looks like there is no input from the maintainer of baron yet.

I could submit a PR removing that if block, but I don't really have hopes that it will be merged.

**Comment by davkal** [comment] 2018-10-29 16:17
@ViViDboarder It's worth a try.

**Comment by torkelo** [comment] 2018-10-29 17:44
We have a new react legend PR that we will merge soon that will fix this.

**Comment by ViViDboarder** [comment] 2018-10-29 17:55
Thanks @torkelo! In that case I'll abandon my patch to baron as I'm not able to reproduce there anyway.

**Comment by davkal** [comment] 2018-10-30 09:54
Yes you're right, I should have realised this too. @ViViDboarder apologies for the goose chase.

**Comment by marefr** [comment] 2018-11-16 08:37
Fixed by #13740

**Closed by marefr** 2018-11-16 08:37 UTC
Labels: needs investigation, type: bug
