### ISSUE TITLE
SingleStat null values

### ISSUE THREAD

**Issue by r02b** [grafana/grafana#13168] opened 2018-09-05 23:46 UTC
Grafana version: 1.1.4 (though problem appeared also in 1.0.2)
Datasource: Graphite 1.2.0-dev
OS: Linux
Problem description: I'm using the filterSeries Graphite function in a SingleStat panel. The problem is, sometime the condition does not hold for any of the input series, and so I get a sort of null. I'm saying "sort of", because when I try using the transformNull function to get an actual value instead it does not work.
I know that in past versions of Grafana, I could map null to a textual **value, not text**. I do currently use the existing value mapping, which is better than displaying "no value", but this way I don't get to enjoy all the great visualizations benefits, for example, color the value according to my predefined thresholds.

Is there a workaround I'm not aware of to handle these sorts of things? I wasn't able to find any that worked. Or, can you bring back that old feature?

Thanks!

**Comment by marefr** [comment] 2018-09-06 08:57
Duplicate of #8404

See https://github.com/grafana/grafana/issues/8404#issuecomment-380794878

**Closed by marefr** 2018-09-06 08:57 UTC
