### ISSUE TITLE
Double-byte variable value was lost after jumped to new dashboard via data link

### ISSUE THREAD

**Issue by GitHubWade** [grafana/grafana#22528] opened 2020-03-03 08:50 UTC
**What happened**:
I have two dashboards.
Dashboard  A: include a Graph panel, time as X axis , double-byte chars as serie name,with a data link to Dashboard B via variable var-type=${__series.name}
Dashboard B: display data according to the variable type from A

When clicking the Graph panel data bars  in dashboard A, the data link title(double-byte chars: SO创建) appears.
Then clicking the data link title(SO创建),it has unexpected results.
The variable var-type in dashboard B url  becomes SO, without double bytes "创建" 

**What you expected to happen**:
The double-byte variable value shouble the same as before after jumped to new dashboard via data link(var-type=SO创建)

**How to reproduce it (as minimally and precisely as possible)**:
Create two dashboards A and B.
A: include a Graph panel, time as X axis , double-byte chars as serie name("SO创建" eg.).
    create a data link in the panel, ${__series.name} as title, link to B with var-type=${__series.name}
B:show data via variable type

Click data bars in Graph pane in A, then the data link title shows
Click data link title,then move to dashboard B
Confirm the variable type url in browser

**Anything else we need to know?**:
No

**Environment**:
Grafana version: 6.6.2
Data source type & version: PostgreSQL 9.4
OS Grafana is installed on: CentOS
User OS & Browser: Mac Chrome
Grafana plugins: Graph panel
Others:

**Comment by GitHubWade** [comment] 2020-03-03 11:38
@torkelo any plans?

**Comment by torkelo** [comment] 2020-03-03 11:40
plans?

**Comment by aocenas** [comment] 2020-03-04 10:20
@dprokop can you check this out?

**Comment by daliang1215** [comment] 2020-04-30 04:19
I don’t think it ’s possible to transfer Chinese, I also need this function。
I have two Variables, year and sales_name , I found some error when I post the url using data link . 
year is number , and sales_name is chinese like"销售". 
my data link : 
[http://192.168.2.112:3000/d/ZbyRlm6Wk/he-nan-cun-chu-li-nian-xiao-shou-e?tab=visualization&panelId=10&orgId=1&var-sales_name=${sales_name}&var-year=${year}](http://192.168.2.112:3000/d/ZbyRlm6Wk/he-nan-cun-chu-li-nian-xiao-shou-e?tab=visualization&panelId=10&orgId=1&var-sales_name=${sales_name}&var-year=${year})
but when i click this link , I found it in browser  ：
[http://192.168.2.112:3000/d/ZbyRlm6Wk/he-nan-cun-chu-li-nian-xiao-shou-e?tab=visualization&panelId=10&orgId=1&var-sales_name=${sales_name}&var-year=19](http://192.168.2.112:3000/d/ZbyRlm6Wk/he-nan-cun-chu-li-nian-xiao-shou-e?tab=visualization&panelId=10&orgId=1&var-sales_name=&var-year=19)

Variable {sales_name} can't be transfered  but  Variable  ｛year｝ can be transfered( integer) .  

so i think chinese need to be support or use other method.

**Comment by hugohaggmark** [comment] 2020-11-13 08:34
I think this is a duplicate of #22125 or that would probably solve this issue too, so I'm closing this issue now. This doesn't mean we will reopen this issue if you think my assumption of the duplication of #22125 is wrong.

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2020-11-13 08:34 UTC
Labels: area/dashboard/data-links
