### ISSUE TITLE
Executable Notification channel

### ISSUE THREAD

**Issue by TheSilverHawkx** [grafana/grafana#26666] opened 2020-07-29 07:12 UTC
**What would you like to be added**:
An executable notification channel.
An option to use a script or executable located on the Grafana server in order to send notifications to 3rd party tools that doesn't support web hooks or REST API.

**Why is this needed**:
1. In the company I work for there is a central sms and mailing system which is a bit old and doesn't support REST API.
As of now I don't have any easy solution to pass notifications from Grafana to it and therefore I use a 3rd party tool to query my different data sources and try to replicate Grafana's behavior to send notifications (not ideal). 
With an executable channel I can easily set up a script that send messages without the use of a 3rd party tool.

2. Another old tool which was built inside the company is in change of knowledge base for infrastructure servers (aggregating data from configuration managers, alerting systems and more).
I'd like to enrich my current alerts with notifications from Grafana.

3. Let's say I want to perform a task on a remote server (auditing / backing up / restarting etc.) only when a certain threshold of my application is crossed, with an executable notification channel It could be done easily. 

Adding an executable channel opens up a world for many possibilities:
- It can cover any blank spots in the current notification system, which will make it more popular among users that doesn't have a popular tools (for any reason) and might attract new users to it for automation purposes.
- It could be used for automating tasks as a response to graph thresholds, you could potentially help reduce debugging time troubleshooting by performing automated actions that usually would've left "running"  24/7 in case there would be an error, e.g tracing tools, logs backup etc.

**Structure**:
As a user those are the main features I'd like in such channel:
1. Path to executable (on grafana server).
2. Arguments sections separately.
3. placeholders for the text, like $value, $metric,$message, $host.
4. Trigger  action and Resolved action (the first for when the problem occurs and the second for when it is resolved).
5. Once the channel is triggered, log the output to the grafana.log for easy troubleshooting in case the scripts don't work.

**Comment by torkelo** [comment] 2020-07-29 07:51
duplicate of https://github.com/grafana/grafana/issues/6721

**Closed by torkelo** 2020-07-29 07:51 UTC
Labels: area/alerting/notifications, type/feature-request
