### ISSUE TITLE
Local admin password cannot be changed

### ISSUE THREAD

**Issue by langebe** [grafana/grafana#17175] opened 2019-05-20 13:54 UTC
Logging in with the grafana default admin account does not allow to change the password.
The following error is displayed: You cannot change password when ldap or auth proxy authentication is enabled.

There is also an LDAP user account with the same name (not sure if related).

The error is shown when logging in with either password (local or LDAP one).
It should be possible to change the password when using the local password for logging in.

**Comment by marefr** [comment] 2019-05-20 15:10
Duplicate of #12238

**Closed by marefr** 2019-05-20 15:10 UTC
