### ISSUE TITLE
Auto fit dashboard panels to optimize space used for current TV / Monitor 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#12768] opened 2018-07-30 18:26 UTC
## Scenarios 
* Your designing a dashboard on one monitor that is to be shown on another TV and it's hard to fine-tune panel height so they look good on the TV. 
* One dashboard might be used for by different sized monitors / TVs would be good if Grafana could auto adjust panel height to optimize space used. 

## Auto adjusting panel heights
Before a dashboard is fully loaded, if a setting named `autofitpanels` (tenative name) is turned on then adust panel heights to optimize space used. 

## Challenages. 
- Where should option live? (user, dashboard, playlist or just url)
- How do you toggle it? 
- Should it be a transient option? (like kiosk mode that is only triggered by url)

Start implementing the feature using an url param, we can make it into a peristed property on user or playlist later. 

General idea would be to adjust all the panels height (except row panels) to optimize space. This could be done sometime during dashboard ini (after panel repeats). First measure the viewport height then use that to change the panels grid height (using a relative increase/decrease). 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashboard_ctrl.ts#L64

Related to old closed feature request: https://github.com/grafana/grafana/issues/1141

**Comment by torkelo** [comment] 2018-07-30 19:17
@dehrax if you could take a look at this (with help from @marefr when needed) that would be great.

**Comment by dehrax** [comment] 2018-07-31 07:31
This feels like playlist thing. Would it be a reasonable thing to have this be the standard option when running a playlist? Or is that assuming too much? We could definitely do an URL option.

**Comment by marefr** [comment] 2018-07-31 09:01
Some random thoughts.

Not everyone use the playlist feature for display dashboard on big TV screens, they render single dashboards as well.

Would using responsive design be an alternative? Basically above a certain resolution make everything bigger (fonts, elements, graph line thickness etc) - which should in theory automatically re-scale the panels to fit better on a large screen? Just adjusting height of panels would make it scale nicely, but resolution of content would not be great experience and hard to see. This will in theory solve the problem of building a dashboard to be displayed on a bigger screen since what you see on your screen will be automatically be re-scaled on bigger screens.

If responsible is not possible to solve for all possible screens then a setting of some kind would probably be ideal. If I build a dashboard for a big TV screen I expect to be able to see/preview how it will look on other screens why maybe a setting on dashboard which will freeze the height of the dashboard to viewport height may be convenient. When displayed on larger screen it would be possible to calculate original relative height and use that to increase relative height. Alternatively a kiosk mode may be handy (which you also can trigger by keyboard). Responsive design If not having a fixed height how should we know which panels to display in viewport and which not (if having lots of panels not fitting in)?

**Comment by allamiro** [comment] 2018-08-01 13:53
i like this feature I think its important feature to display grafana dashboards on any screen

**Comment by dehrax** [comment] 2018-08-02 11:56
![img_20180802_134450](https://user-images.githubusercontent.com/1438972/43582133-97d1ef0c-965b-11e8-9f33-791f5175abc3.jpg)
The automatic resize works decently, just need to work out a few caveats and add somewhere to enable/disable.

**Comment by marefr** [comment] 2018-08-07 13:59
First take on this have been merged to master thru #12796 and we hope to gather some valuable feedback.

Enable this in a dashboard by shortcut d+a or append &autofitpanels in dashboard url.

**Comment by marefr** [comment] 2018-08-07 15:36
Feedback that I came to think about after reviewing the PR: 
* We maybe should merge kiosk and autofit panels together to one?
* For me it would make sense to hide the variables on top, but maybe not for others (who needs to know what variable values have been selected)?

**Comment by torkelo** [comment] 2018-08-08 05:40
In kiosk mode you don’t see time range which I feel is most of the time important, but maybe not. Hiding variables is tricky, maybe they give important context to what your seeing but then again the panel legends and titles should already that, so maybe your right

**Comment by dehrax** [comment] 2018-08-08 08:31
What are the different use cases for kiosk mode and autofit panels? When are they the same and when are they not the same?

**Closed** 2018-08-14 10:26 UTC
Labels: P1: urgent, support subscription priority

**Comment by torkelo** [comment] 2018-08-14 10:34
After testing this more, I am a bit unsure about adding a UI option for it (on user or dashboard). Will need more feedback if this feature is good enough to warrant that. It only works ok on some dashboards and unsure how useful this feature will be to a wider user base. 

So until we get some more feedback that this is actually working & useful enough I think having it as an url option & keyboard shortcut will be good enough. 

Keyboard shortcut is `d a`, this keyboard shortcut will reload dashboard with the `&autofitpanels" url parameter added.

**Comment by sebwills** [comment] 2019-08-08 08:30
By way of feedback - I wanted this feature, searched for it in the UI, didn't find it, googled and found this issue, turned it on with the shortcut and it did exactly what I wanted (simple dashboard with three graphs) - thanks!. Also tried in combination with kiosk mode but didn't like the fact that kiosk mode hides the dashboard title.

**Comment by dreallday** [comment] 2020-03-03 15:30
I love this feature. Thanks all!

**Comment by Pla5ma** [comment] 2020-12-07 16:50
This option is exactly what I need! Great. But often the legend is broken with this setting:

![image](https://user-images.githubusercontent.com/57805183/101379432-8ca7ad80-38b4-11eb-8e9a-ef73b2573f00.png)

Maybe the space between the text elements should be dynamical too?!

**Comment by svet-b** [comment] 2021-04-13 13:44
I'd love to have this exposed in the UI, in a way that enables it by default for certain dashboards. We've encountered the need for it with increasing frequency, due to the following use case: **large horizontally scrolling table panels**.

The new table panel is so great, that we have a few dashboards which simply contain a single large table with metrics. These tables will often involve both horizontal and vertical scrolling. By default, it's not possible to size the table's height to the user's window - so for some users the table will not fill their screen, while for others the table will extend past the bottom of the screen. The latter is particularly problematic, since it means that in order for the user to reach the table's horizontal scroll bar, they need to scroll _all the way down_.

The screen capture below hopefully illustrates this well. To be clear, I don't necessarily think that there's a problem with the table panel itself. I think the issue is with the difficulty of fitting it to the user's window. And that would be addressed by a full implementation of this feature.


https://user-images.githubusercontent.com/12831860/114562711-6be2d080-9c77-11eb-8af2-1c1d2a31adb4.mov

**Comment by SMillerDev** [comment] 2021-07-09 14:34
After finding this thread I gave it a try on a 4K screen compared to my laptop and it works pretty well. The only issue I found is that if your dashboard has variables it doesn't take that padding into account and you suddenly have 2 scroll bars.

**Comment by ahti** [comment] 2022-12-15 10:19
We have a dashboard that is basically just a log viewer with some small graphs on the side to make it look nice.

For that dashboard, the auto-fit option is very useful. Without, users on smaller screens will have nested scroll areas, while on larger screens there will be wasted space.

Thus, I would very much welcome if there was a way to enable it by default for a dashboard.

Regarding the current implementation, I will mirror what was said about the variables bar not being taken into account. Additionally, the automatic height adjustments should happen when resizing the window, instead of just on reloading the page. And lastly, the height adjustments currently show up as modifications in the save dialog, and I think they have triggered the "save before leaving?"-alert for me as well (although I can't reproduce that right now).

**Comment by ethaniel** [comment] 2023-02-04 16:08
It's not working right in my case. Here is how the dashboard looks normally: 
![image](https://user-images.githubusercontent.com/941973/216777570-a75af78c-516f-4d2c-9a10-236bc04b229b.png)

And here it with &kiosk=1&autofitpanels=1
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/941973/216777592-17be47e1-7c9a-4df4-bc89-ca49ed8a38bc.png">

Am I doing something wrong?

**Comment by jisotalo** [comment] 2023-05-24 05:11
This is a good feature! Just wondering if there is any hack how to enable this automatically at home dashboard?

Now I can add it to links to other dashboards, but if user opens grafana, the home dashboard will not have it. And that's the one where I would need this.
