### ISSUE TITLE
Feature Request: Specify Labels for Custom Variable Values

### ISSUE THREAD

**Issue by m4dc4p** [grafana/grafana#3402] opened 2015-12-03 00:43 UTC
When using custom variables, each value is displayed directly in the UI. Those values can look really ugly if they need to be used in a query. I would like to be able to specify a display label for each value.

**Comment by m4dc4p** [comment] 2015-12-03 00:48
Example: I want to parameterize on hostname, but my hosts are FQDNs. So my custom variable value list is "host1.mycompany.com, host2.mycompany.com, ...". That can take up a lot of space at the top of the dashboard, especially when using multi-select lists.

Of course, the obvious follow on feature is that I would like to write javascript code to transform those values into labels. The exact same feature could be awesome for metric aliases, too.

**Comment by torkelo** [comment] 2015-12-03 09:03
duplicate of https://github.com/grafana/grafana/issues/1032

**Closed by torkelo** 2015-12-03 09:03 UTC

**Comment by GianniMorini** [comment] 2019-01-17 14:16
+1

very nice to have, strange it's still missing
