### ISSUE TITLE
Templating: switching between the same data source type shouldn't clear query

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#27206] opened 2020-08-26 02:08 UTC
**What happened**:
In the template variable editor for a query variable, if the referenced datasource doesn't exist, then the query and regex fields are cleared.

This is troublesome in several scenarios, for example user makes a new datasource and deletes the old one before migrating all templates.  When he tries to update the template variable, the original query is lost.

**What you expected to happen**:
Query and regex fields should not be deleted unless the variable type is changed.

**Environment**:
- Grafana version: 7.1.4

**Comment by hugohaggmark** [comment] 2020-08-31 09:02
Thanks for adding this issue @belm0 , I took the liberty to change this to a feature request that states that switching data source for a Query Variable shouldn't clear the query field if the data source type is the same. Couldn't reproduce the same behavior with Regex.

WDYT?

**Comment by belm0** [comment] 2020-08-31 10:13
It's a bug in my opinion-- user's configuration is deleted unexpectedly.

**Comment by hugohaggmark** [comment] 2020-08-31 10:52
Ok, I understand, and I changed it back to a bug. But I think it's been like this since Grafana 6 at least. I can see a couple of solutions:

1. Prevent/warn a user from/when deleting a data source used by template variables.
2. When switching between data sources of the same type, keep the query.

**Comment by belm0** [comment] 2020-08-31 11:19
From my observations, the fields aren't actually deleted until you open the template variable for edit.

So I think the solution would be local to the template editor, and hopefully straightforward.

**Comment by Eraac** [comment] 2020-09-01 08:58
Probably a bug, because this was declare fixed https://github.com/grafana/grafana/issues/20942

**Comment by BrunaDaniel** [comment] 2020-09-22 09:11
> Probably a bug, because this was declare fixed #20942

Actually, I tried this with Grafana 7.1.5 and my Grafana broke. We need a new solution.

**Comment by hugohaggmark** [comment] 2020-10-15 05:03
These lines need to add some logic that makes sure we don't clear the query prop if the datasource type changing to is the same as the previous selected datasource type.
https://github.com/grafana/grafana/blob/master/public/app/features/variables/query/QueryVariableEditor.tsx#L71-L72

**Comment by torkelo** [comment] 2021-03-28 08:02
This seems to be fixed in 7.5

**Closed by torkelo** 2021-03-28 08:02 UTC
Labels: area/dashboard/templating, type/bug
