### ISSUE TITLE
Allow triggering external webhooks on events

### ISSUE THREAD

**Issue by gw0** [grafana/grafana#28772] opened 2020-11-03 09:38 UTC
**What would you like to be added**:
Support for triggering external webhooks on specific events (e.g. when saving a dashboard). Probably for events that the backend already broadcasts for other purposes, e.g.:

https://github.com/grafana/grafana/blob/5fcff1a4c74f80fe5c29cc259d43418b35088467/pkg/api/dashboard.go#L266

**Why is this needed**:
In order to automate provisioning of dashboards it would be beneficial if Grafana could trigger an external webhook each time a dashboard is saved through the Web UI. This would enable an external service to know that a dashboard changed. The service could then use the Grafana API to retrieve the dashboard and open a PR to automate GitOps. For example, to automate authors workflow in https://github.com/grafana/grafana/issues/11778 even further.

Currently, something similar could be implemented with an external service with a pull strategy that is checking for changes in dashboards using the Grafana API. Constant checking introduces a lot of overhead, therefore implementing a push strategy with a webhook makes more sense.

**Comment by yesoreyeram** [comment] 2021-02-12 11:37
Probably duplicate of #9066

**Comment by pkolyvas** [comment] 2021-08-20 15:48
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!

**Closed** 2021-08-20 15:54 UTC
Labels: gh-discussions
