### ISSUE TITLE
Span are indented incorrectly in Tempo search split pane

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#41573] opened 2021-11-10 21:29 UTC
**What happened**:
When using the Tempo search split pane and selecting different traces the indention and colors of the spans of the trace are sometimes rendered incorrectly. 

Things I've noticed about this behavior:
- The colors/indentation seems to be based on swapping between other traces in the same search results. It's as if some kind of state is not being completely cleared out between selections.
- If a trace is rendered incorrectly in the split pane closing the search pane so only the trace is visible always corrects the issue. I have not seen this issue in a full trace window.
- The example below shares details about how the first trace has issues, but I have seen this issue on different positions in the list.
- The example below shares details about how a single span indentation can occur but I have seen much more severely impacted traces as well as span color swapping.

This is the first trace in the search results (74b7a9794feaf48d) rendered correctly:

![image](https://user-images.githubusercontent.com/2272392/141195628-75c5928d-1376-463b-9f5d-aa8e9ccc2c86.png)

If I click the next 3 results in order and then come back it looks like this:

![image](https://user-images.githubusercontent.com/2272392/141195929-91f18b66-ab74-4d57-a2e3-cfe7bd2a972b.png)

Note the incorrect indentation of the final span. If I then click the second trace in the search results and come back to the first in then it goes back to being rendered correctly. The full order of steps is:

1) Click first result (rendered correctly)
2) Click 2 -> 4 in order.
3) Click first result again (rendered incorrectly)
4) Click 2
5) Click first result again (rendered correctly)

**What you expected to happen**:
The colors and indention of the spans to be rendered consistently and correctly in the split pane view with Tempo search.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.2.3-40566 (3b8be57b4f)
- Data source type & version: Tempo
- OS Grafana is installed on: Hosted Grafana
- User OS & Browser: Ubuntu 18.04/Chrome
- Grafana plugins: 
- Others:

**Comment by andersosthus** [comment] 2021-11-13 19:28
I've seen this as well, and it doesn't only happen in split view.

Steps to reproduce:
- Do an action that generates a trace
- Find and open the trace in Tempo viewer before all the spans have been sent to the backend
- After a few seconds, refresh (not the page, but with the Grafana refresh button), and spans can now end up showing wrong indentation.
- A page reload renders everything correctly

I've attached two screenshots, the first showing the state after I've done a "Grafana refresh", and the second after a page refresh.

![image](https://user-images.githubusercontent.com/184104/141656627-07a703e2-91a5-4c77-a785-e88530999487.png)

![image](https://user-images.githubusercontent.com/184104/141656655-e11e84f8-72eb-49a2-9884-284d32fd3a47.png)

**Comment by ivanahuckova** [comment] 2021-11-16 12:43
Based on my investigation:

>The colors/indentation seems to be based on swapping between other traces in the same search results. It's as if some kind of state is not being completely cleared out between selections.

The different trace colors is not connected issue (and not issue at all). It is related to what traces have we been running before, because we are caching key and assigning it a color. This seems more like a useful feature, rather than bug - the same keys have always same color in all traces that we run.

It seems that the issue is mainly (maybe only?) happening for the first trace. I wasn't able to reproduce this wit our data. @joe-elliott can you please provide me/us with access to data where we are able to reproduce it.

**Comment by andersosthus** [comment] 2021-11-17 11:20
@ivanahuckova In my experience, I'm only able to reproduce this when viewing a trace that has not recieved all spans. If the trace has all spans, the issue won't show up, only if you are watching an incomplete trace and do a refresh in Grafana (so that it can fetch all spans) do I see this issue.

For me the issue is also more likely to appear if the trace contains a lot of spans, or more accurately, having passed through multiple services that might report the spans with different intervals.

**Closed** 2021-11-22 12:18 UTC
Labels: type/bug, priority/important-soon, area/tracing, datasource/Tempo
