### ISSUE TITLE
Folder Creation does not check for Dashboard name conflict

### ISSUE THREAD

**Issue by BenB196** [grafana/grafana#22966] opened 2020-03-23 12:53 UTC
**What happened**:
I created a folder with the same name as an existing dashboard. Then went to edit the dashboard. When I tried to save the dashboard I got an error message that a dashboard cannot be the same name as a folder.

**What you expected to happen**:
I would expected that if this were the case. Then I shouldn't have been allowed to create the folder, as there was an existing dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Dashboard with a given name
2. Create a folder with the same name
3. Attempt to edit and save existing dashboard
4. Get error regarding folder/dashboard name conflict

**Anything else we need to know?**:
This error occurs on 6.6.2. However, when I upgraded to 6.7.1 I no longer get an error, but the dashboard still does not save correctly.

**Environment**:
- Grafana version: 6.6.2/6.7.1
- Data source type & version: N/A
- OS Grafana is installed on: Alpine 3.11.3 (running in a Docker Container though)
- User OS & Browser: Windows 10 + Firefox 75.0b7
- Grafana plugins: grafana-worldmap-panel, grafana-clock-panel, grafana-piechart-panel, ryantxu-ajax-panel, farski-blendstat-panel, agenty-flowcharting-panel, jdbranham-diagram-panel, michaeldmoore-multistat-panel, natel-plotly-panel, grafana-polystat-panel, snuids-radar-panel, pr0ps-trac
- Others:

**Comment by dprokop** [comment] 2020-04-03 10:02
Duplicate of #23103

**Closed** 2020-04-14 08:55 UTC
Labels: area/dashboard/folders, needs investigation, type/duplicate
