### ISSUE TITLE
[Bug] grafana-server crashes when [log.console] is missing from config

### ISSUE THREAD

**Issue by rzetterberg** [grafana/grafana#6667] opened 2016-11-22 19:26 UTC
# Problem description

- **Grafana version** - 3.1.0
- **Platform** - Linux (NixOS)

When I run `grafana-server` with a config missing the `[log.console]` header it crashes with:

```
grafana-server
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x64c7d5]

goroutine 1 [running]:
panic(0xee3fe0, 0xc82000a140)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.6.2/share/go/src/runtime/panic.go:481 +0x3e6
gopkg.in/ini%2ev1.(*Section).GetKey(0x0, 0x1064f80, 0x7, 0x0, 0x0, 0x0)
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/Godeps/_workspace/src/gopkg.in/ini.v1/ini.go:484 +0x45
gopkg.in/ini%2ev1.(*Section).Key(0x0, 0x1064f80, 0x7, 0x4)
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/Godeps/_workspace/src/gopkg.in/ini.v1/ini.go:502 +0x39
github.com/grafana/grafana/pkg/log.ReadLoggingConfig(0xc820183010, 0x1, 0x1, 0xc820183060, 0xd, 0xc82007cf00)
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/pkg/log/log.go:157 +0x4f6
github.com/grafana/grafana/pkg/setting.initLogging()
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/pkg/setting/setting.go:561 +0x2cb
github.com/grafana/grafana/pkg/setting.loadConfiguration(0xc820137e30)
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/pkg/setting/setting.go:343 +0x3ba
github.com/grafana/grafana/pkg/setting.NewConfigContext(0xc820137e30, 0x0, 0x0)
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/pkg/setting/setting.go:428 +0x56
main.initRuntime()
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:80 +0xf2
main.main()
        /tmp/nix-build-go1.6-grafana-v3.1.0.drv-0/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:62 +0x2d7
```

Here are direct Github links (using tag v3.1.0) to the 4 latest entries in the stack trace:

- [pkg/log/log.go:157](https://github.com/grafana/grafana/blob/v3.1.0/pkg/log/log.go#L157)
- [pkg/setting/setting.go:561](https://github.com/grafana/grafana/blob/v3.1.0/pkg/setting/setting.go#L561)
- [pkg/setting/setting.go:343](https://github.com/grafana/grafana/blob/v3.1.0/pkg/setting/setting.go#L343)
- [pkg/setting/setting.go:428](https://github.com/grafana/grafana/blob/v3.1.0/pkg/setting/setting.go#L428)

# Steps to reproduce

Create a temporary dir with a minimal config file and run `grafana-server` in the dir:

```bash
TEST_DIR=$(mktemp -d)

cd $TEST_DIR

mkdir conf

cat << \EOF > conf/defaults.ini
instance_name = ${HOSTNAME}
EOF

grafana-server
```

Directly when running `grafana-server` you will get the error above.

If you add the `[log.console]` header to the config file and run `grafana-server` again you get basic logging to `stdout` as expected:

```bash
cat << \EOF > conf/defaults.ini
instance_name = ${HOSTNAME}
[log.console]
EOF

grafana-server
```

With the output:

```
t=2016-11-22T20:18:58+0100 lvl=crit msg="Failed to detect generated css or javascript files in static root (/tmp/tmp.FUyQUEVbRI), have you executed default grunt task?%!(EXTRA []interface {}=[])"
```

# Expected behavior

The program should not crash with a segmentation fault when there are parts missing in the config. 

The program should output an error message that there are parts missing in the config, or that it is invalid.

**Comment by bergquist** [comment] 2016-11-23 05:40
Thank you for reporting this.

Im closing this since I cannot reproduce this in in grafana 4 beta2.

**Closed by bergquist** 2016-11-23 05:40 UTC
