### ISSUE TITLE
Provisioned Dashboard not updating if json contains uid

### ISSUE THREAD

**Issue by gargath** [grafana/grafana#12411] opened 2018-06-26 12:41 UTC
### What Grafana version are you using?
 Official 5.2.0-beta1 container

### What datasource are you using?
  Prometheus
### What OS are you running grafana on?
  Official container deployed to Kubernetes

### What did you do?
  Made changes to a provisioned dashboard
  Clicked "save"
  Copy-pasted the JSON provided
  Updated file mounted into Grafana provisioning folder with that JSON

### What was the expected result?
  Grafana should have updated the existing provisioned dashboard with the new JSON now found in the pre-existing provisioning file

### What happened instead?
  Grafana failed to update the dashboard.
  The error logged was:
  `lvl=eror msg="failed to save dashboard" logger=provisioning.dashboard type=file name=default error="A dashboard with the same uid already exists"`

From what I understand, the correct way to update provisioned dashboards is to copy/paste the JSON provided when you click "save" and update the provisioning file with that.
This does not seem to work in this case.

**Comment by torkelo** [comment] 2018-06-26 13:07
Maybe you have two provisioned dashboards with same uid?

**Comment by gargath** [comment] 2018-06-26 13:16
Actually, yes. Some further investigation revealed that the export was done in one instance, and the import done in another where a different board with that uid already existed.

This could be easily avoided if dashboard uids were UUIDs rather than steadily increasing integers.
Would that be feasible to do?

**Comment by bergquist** [comment] 2018-06-26 13:42
@gargath UID is only an integer if the dashboard was created pre 5.0. New dashboard gets a UUID like string ex `66CTjRDik`

Im closing this issue since the problem is solved.

**Closed by bergquist** 2018-06-26 13:42 UTC
