### ISSUE TITLE
Improve status code when adding datasources

### ISSUE THREAD

**Issue by mengjie-ms** [grafana/grafana#89025] opened 2024-06-11 09:40 UTC
### What happened?

This is the follow-up for https://grafana.com/orgs/azuregrafanasupport/tickets/131853.
Grafana returns 500 when "Failed to add datasource" with "pq: duplicate key value violates unique constraint 'UQE_role_org_id_name' ". 
![90456f1a-ce4d-4845-83f8-7170984eaedb](https://github.com/grafana/grafana/assets/106638080/ad44bb45-a403-499c-8b90-a785ba3fa67b)
Grafana has handled the 500 status for "UQE_data_source_org_id_name" [link](https://github.com/grafana/grafana/issues/65509), but not cover the "UQE_role_org_id_name".

### What did you expect to happen?

proper status code and error message

### Did this work before?

no

### How do we reproduce it?

Not very confirmed what the role is.

### Environment (with versions)?

Grafana: 10.3.4
OS:
Browser:

### Grafana platform?

None

**Comment by mengjie-ms** [comment] 2024-06-17 06:30
This issue was discovered by our scheduled health report, was not reported by our customer, so we didn't know their produce steps. While we tried to add datasources and managed roles, but didn't reproduce the same error. Besides, this error is rare for only once in last 30 days. We're not sure it's user error or temporary internal server error, do you have any ideas?

**Comment by marefr** [comment] 2024-06-26 13:30
Probably originates from https://github.com/grafana/grafana/blob/ba4f2713c532735adcfab38b84c362c63ffba354/pkg/services/datasources/service/datasource.go#L295 which is datasource permissions.

**Comment by jinghzhu-msft** [comment] 2024-07-22 06:10
Hi @marefr , is there any update for it? Do we have timeline to fix it?

**Comment by aarongodin** [comment] 2024-07-29 16:04
There's a set of managed roles that are created as part of the datasource creation. Referring to the line that @marefr linked, these would be one for each of the builtin Viewer and Editor roles, and the currently logged in user or service account.

This func would be run for each of those assignments to first check if there's an existing managed role for each of those three assignments:

https://github.com/grafana/grafana/blob/ba4f2713c532735adcfab38b84c362c63ffba354/pkg/services/accesscontrol/resourcepermissions/store.go#L583

Based on the checks for an existing managed role, there might be an issue if a managed role was created without an `org_id`. This is not expected behavior since all datasources must have an associated `org_id`.

I don't see any recent changes that would cause this either. I think unless we have specific steps to reproduce it seems more likely that this was due to inconsistent state on the side of the DB.

**Comment by aarongodin** [comment] 2024-07-29 16:07
We could add a specific check around the error returned from setting the managed permissions, but keeping this as a 500-level error makes sense to me. Ideally we would not leak the reason for the error however, so I can fix the error handling logic to prevent that.

**Comment by mengjie-ms** [comment] 2024-09-10 07:25
Hi @aarongodin, Is there any pull request for the issue? Or is there any update about the fix?

**Comment by aarongodin** [comment] 2024-09-11 14:12
There is not a fix yet for this. I have some bandwidth to take a look later today and will push a fix through.

**Comment by mengjie-ms** [comment] 2024-09-29 07:39
Hi @aarongodin, I see you removed the assignments yesterday, is there any updates?

**Comment by aarongodin** [comment] 2024-10-01 20:08
Hey @mengjie-ms I took a second look at this. Since there were not any steps to reproduce I've done my best to ensure that errors from managed permissions on DS creation are surfaced correctly. I confirmed this with a corresponding test case:

https://github.com/grafana/grafana/issues/89025

Additionally, we want to ensure that if an error was surfaced, the 500-level error message would not be surfaced through the API (no users should see an error coming from the DB).

I confirmed this through these steps:

1. Modify the area of the code to always return an error when creating managed permissions.
2. Make a cURL like:

```
curl --location --request POST 'http://localhost:3000/api/datasources' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: localhost:3000' \
--header 'Connection: keep-alive' \
--data-raw '{"type":"prometheus","access":"proxy"}'
```

3. Note that the request body does not contain any sensitive error:

```
{
    "message": "Failed to add datasource",
    "traceID": ""
}
```

4. Check the logs to ensure the real reason for the error was noted:

```
ERROR[10-01|14:53:38] Failed to add datasource                 logger=context userId=1 orgId=2 uname=admin error="failed to set datasource resource permissions" remote_addr=[::1] traceID=
ERROR[10-01|14:53:38] Request Completed                        logger=context userId=1 orgId=2 uname=admin method=POST path=/api/datasources status=500 remote_addr=[::1] time_ms=42 duration=42.659458ms size=51 referer= handler=/api/datasources/ status_source=server
```

This is because the error handling logic uses a different public message for unknown errors:

https://github.com/grafana/grafana/blob/main/pkg/api/datasources.go#L461-L471

Hoping that this suffices to show that this error doesn't seem possible from an API perspective. There are other paths through the code that can create datasources, so if we are provided other steps that assume the API is not being used, I'll check into those as well.

**Comment by aarongodin** [comment] 2024-10-02 14:31
I found that through file provisioning, it's possible to surface an error from setting managed permissions, but based on my testing, if an error occurs during file provisioning of datasources, the instance will not start. I believe this is the only other way that datasources may be added, and it seems unlikely that this is the step the customer was taking as it would have halted their instance from starting, creating a much larger issue than is being reported.

**Comment by aarongodin** [comment] 2024-10-17 15:04
@mengjie-ms are you comfortable closing this issue considering https://github.com/grafana/grafana/pull/94113 is closed?

If there are additional occurrences that have come up since this issue was opened, that would be helpful. Otherwise, I'd like to resolve this as not reproducable.

**Closed** 2024-10-21 16:45 UTC
Labels: area/datasource, area/auth/rbac
