### ISSUE TITLE
[Feature Request] German "Milliarden"

### ISSUE THREAD

**Issue by macmeaker** [grafana/grafana#8672] opened 2017-06-21 06:30 UTC
Hello,
in Germany we say to "billion" "Milliarden" and "Billion" in Germany means 1.000.000.000.000.
So my question or feature request is that for american "billion" it would be nice if exists the short name "Milrd" or something in this way. 
So:
1.000.000 --> Million --> Mil
1.000.000.000 --> Milliarden --> Milrd
1.000.000.000.000 --> Billion --> Bil
1.000.000.000.000.000 --> Billiarden --> Bilrd
 
Maybe it is possible to handle this problem.
I didn't find something on https://community.grafana.com

Thanks

**Comment by demonkoryu** [comment] 2017-06-21 12:14
Correct german abbreviations are as follows (including the dot):
- [million] Million: Mio.
- [billion] Milliarde: Mrd.
- [trillion] Billion: Bio.
- [quadrillion] Billiarde: Brd.

The prefixes in square brackets are the english equivalents.

**Comment by torkelo** [comment] 2017-06-21 12:19
duplicate of (or similar to), https://github.com/grafana/grafana/issues/448

**Closed by torkelo** 2017-06-21 12:19 UTC
