### ISSUE TITLE
Tooltip rendering of heatmap cells in Firefox

### ISSUE THREAD

**Issue by UlrichEckhardt** [grafana/grafana#13277] opened 2018-09-14 07:31 UTC
The tooltips when hovering over a heatmap are not displayed correctly. This happens in the below Firefox version and also happened in an earlier one. On Chromium at the below version, this doesn't happen. I haven't checked any other version of that browser.

When hovering over a cell, the cell is highlighted with a bright border, but no tooltip is displayed. The red, vertical line, which usually follows your mouse movements, is positioned at the very left of the heatmap then. If you move the mouse pointer to the gap between two cells, you get a tooltip and the red line also jumps there.

System info:
- Grafana 5.2.2
- Datasource: Prometheus
- OS: Debian 9.5
- non-working Firefox: 60.2.0esr
- working Chromium: 69.0.3497.81

**Comment by marefr** [comment] 2018-09-14 08:41
Duplicate of #12486

**Comment by marefr** [comment] 2018-09-14 08:41
Fix will be included in v5.3 stable

**Closed by marefr** 2018-09-14 08:41 UTC
Labels: type: duplicate
