### ISSUE TITLE
MySQL Time Series Query Chart Zoom Problem

### ISSUE THREAD

**Issue by PimpJuiceIT** [grafana/grafana#13694] opened 2018-10-16 18:29 UTC
I'm running **Grafana version 5.2.3 (cf4c090**) on **CentOS 7.5** and I do not have any trouble with zooming in on data from a **MySQL** data source in a **Graph** chart (see examples below of this working) where when I zoom in on the data, I can see if just fine.

### When it does work
![image](https://user-images.githubusercontent.com/44209265/47037997-6495e700-d14e-11e8-88d2-4d8b01243d77.png)

![image](https://user-images.githubusercontent.com/44209265/47038042-8000f200-d14e-11e8-8310-8263afc3c95b.png)

The datasource is a **MySQL** 5.7 instance and the SQL Query I'm using looks like this using **Time Series**

```
SELECT  $__time(TimeStr)
		    , ROUND(value * 0.03527396195, 2) value
		    , 'Can Weight' as metric
FROM RTCanWeights
WHERE $__timeFilter(TimeStr) AND Value > 0
```

### What I did

I upgraded the Grafana instance to the latest version `5.3.1`, after making full backups of the system and local Grafana DB, etc. and doing a server reboot, this functionality seems to not work properly because now when you go to zoom in on the **Graph** of the same data on the same object and query, the data either does not display and disappears like there is no data available during the zoomed in time frame.

Please note that if you do not zoom in and look at the data just to today or yesterday, etc. then it will display, but if you try to drag to a smaller time period in the graph with the mouse, this is when it zooms but does not display the data.

I looked over the Help and some of the new macros and I believe I'm still using the two I need here but wondering if this is a bug or some oversight per a release note that I missed.

I've since restored this system back to the pre upgrade version but I can get a test system setup and do something further if needed.

### Specs Recap
- CentOS Linux release 7.5.1804 (Core)
   - Kernel 4.18.5-1.el7.elrepo.x86_64
- Grafana v5.3.1 [issue]
- Grafana v5.2.3 (cf4c090) [works]
- MySQL 5.7 datasource
- Graph chart
  - see MySQL query above (time series)
- Zooming in on data from line chart does not display data when zoomed in

**Comment by torkelo** [comment] 2018-10-16 19:30
Whats you raw query and the generated sql and what does that query return ? You can view generated sql in query editor ui and use query inspector in metrics tab to inspect response, also try executing query manually in sql tool

**Comment by PimpJuiceIT** [comment] 2018-10-16 20:43
@torkelo The Generated SQL looks fine and correct, and running the same SQL query from the back end via MySQL Workbench brings back the data correctly too. 

This is all from the `5.2.3` version and I assume you want to know what this is from the `5.3.1` version, correct? 

If so, I'll get a new VM created tomorrow for testing and restore an image to it and then run through the yum update process and report back those results. 

Literally though other than that, changing to the version `5.3.1` from `5.2.3` is all that I did when I noticed but I reverted it back before getting more detail after basic testing.

I'll get a test system up and running and report back those results from the `5.3.1` version sometime tomorrow so I can give you accurate feedback on the system with this issue. I was hoping this would be something already posted as a duplicate that I could not find—I couldn't get that lucky though.

**Comment by wiyotndn** [comment] 2018-10-16 23:58
I am seeing similar issues after an update to 5.3.1  It seems that auto generated time stamps with __timefilter are in the future nor do queries seems to be effected by the hour over ride or time zone when using a mysql data source.

Grafana Query
SELECT
  UNIX_TIMESTAMP(action_time) as time_sec,
  count(action_time)
  action_time
FROM actions
WHERE $__timeFilter(action_time)

Generated Query
SELECT
  UNIX_TIMESTAMP(action_time) as time_sec,
  count(action_time)
  action_time
FROM actions
WHERE action_time BETWEEN '2018-10-16T22:35:54Z' AND '2018-10-16T23:35:54Z

Edited query that returns results with corrected time 
SELECT
  UNIX_TIMESTAMP(action_time) as time_sec,
  count(action_time)
  action_time
FROM actions
WHERE action_time BETWEEN '2018-10-16 15:35:54' AND '2018-10-16 16:35:54'

**Comment by PimpJuiceIT** [comment] 2018-10-17 00:03
> I am seeing similar issues after an update to 5.3.1 It seems that auto generated time stamps with __timefilter are in the future nor do queries seems to be effected by the hour over ride or time zone when using a mysql data source.
> 
> Grafana Query
> SELECT
> UNIX_TIMESTAMP(action_time) as time_sec,
> count(action_time)
> action_time
> FROM actions
> WHERE $__timeFilter(action_time)
> 
> Generated Query
> SELECT
> UNIX_TIMESTAMP(action_time) as time_sec,
> count(action_time)
> action_time
> FROM actions
> WHERE action_time BETWEEN '2018-10-16T22:35:54Z' AND '2018-10-16T23:35:54Z
> 
> Edited query that returns results with corrected time
> SELECT
> UNIX_TIMESTAMP(action_time) as time_sec,
> count(action_time)
> action_time
> FROM actions
> WHERE action_time BETWEEN '2018-10-16 15:35:54' AND '2018-10-16 16:35:54'

@torkelo Does this help much with another person with more clear examples of the issue? I am still happy to setup a test system tomorrow and provide further detail, but not if you say it's not needed any further based on this other report of this same issue I reported with more examples of the raw queries.

**Comment by marefr** [comment] 2018-10-17 07:35
@wiyotndn what timezone on your server where Grafana runs? What timezone of your MySQL server/instance?

**Comment by PimpJuiceIT** [comment] 2018-10-17 16:52
@torkelo Please see the below results from the "working" and "not working" and the working and not work gives the exact same result if I run the `sql:` query manually from the UI of the Graph of this dashboard or whatever.

It seems there was a change and not the not working query is using `BETWEEN` and not with the UTC time even though that column in the `rawSql:` is using the `$__timeFilter()` macro. 

@marefr In this case the CentOS server is on the EDT time, the MySQL instance is on the EDT time zone, and the `TimeStr` date field for this example is also per the EDT time zone. Please note that there are other Graph charts that exhibit this same issue where the `TimeStr` column values from those tables are in other non-EDT time zones. We use the `TimeStr` in particular per these particular dashboards to monitor IoT processes around the world where those columns values (`TimeStr`) are always set to the time zone from the IoT device where those reside. The `TimeStr` value from the tables will always be accurate for the timestamp per the timezone where that data is collected. 

We have the dashboards in this case for all **Time Options** set to default but I also changed to local browser and the same thing occurs. I think it's related to the `$__timeFilter()` not getting the UTC time now and using `BETWEEN` clause rather than `<= AND >=` but It's interesting again that the time is rendered in `YYYY-MM-DDThh:mm:ssZ` format rather than UTC or `UNIX_TIMESTAMP()`.


### Version 5.3.1 (Not Working Zoomed)

**Query Inspector Response**

```
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1539778332824"
to:"1539783242747"
queries:Array[1]
0:Object
refId:"A"
intervalMs:5000
maxDataPoints:1280
datasourceId:14
rawSql:"SELECT $__time(TimeStr) , ROUND(value * 0.03527396195, 2) value , 'Can Weight' as metric FROM RTCanWeights WHERE $__timeFilter(TimeStr) AND Value > 0 "
format:"time_series"
response:Object
results:Object
A:Object
refId:"A"
meta:Object
rowCount:0
sql:"SELECT UNIX_TIMESTAMP(TimeStr) as time_sec , ROUND(value * 0.03527396195, 2) value , 'Can Weight' as metric FROM RTCanWeights WHERE TimeStr BETWEEN '2018-10-17T12:12:12Z' AND '2018-10-17T13:34:02Z' AND Value > 0 "
series:Array[1]
0:Object
name:"Can Weight"
points:Array[2123]
tables:null
```

### Version 5.2.3 (Working Zoomed)

**Query Inspector Response**

```
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1539778332824"
to:"1539783242747"
queries:Array[1]
0:Object
refId:"A"
intervalMs:5000
maxDataPoints:1280
datasourceId:14
rawSql:"SELECT $__time(TimeStr) , ROUND(value * 0.03527396195, 2) value , 'Can Weight' as metric FROM RTCanWeights WHERE $__timeFilter(TimeStr) AND Value > 0 "
format:"time_series"
response:Object
results:Object
A:Object
refId:"A"
meta:Object
rowCount:7337
sql:"SELECT UNIX_TIMESTAMP(TimeStr) as time_sec , ROUND(value * 0.03527396195, 2) value , 'Can Weight' as metric FROM RTCanWeights WHERE TimeStr >= FROM_UNIXTIME(1539778332) AND TimeStr <= FROM_UNIXTIME(1539783242) AND Value > 0 "
series:Array[1]
0:Object
name:"Can Weight"
points:Array[7337]
tables:null
```

**Comment by torkelo** [comment] 2018-10-17 17:05
Grafana only sends UTC time range filters and only supports UTC date time fields (the ui can show them in local or UTC). So make sure the data is stored in UTC. 

This might have worked before by accident, which is unfortunate that this is not working anymore. We will have to keep track of this and see if more are impacted

**Comment by marefr** [comment] 2018-10-17 17:28
Duplicate of #13621

**Comment by marefr** [comment] 2018-10-17 17:28
For possible workaround see https://github.com/grafana/grafana/issues/13621#issuecomment-429137697

**Comment by wiyotndn** [comment] 2018-10-17 19:07
I have all servers in Central time and writing dates in mysql format in central time as well.  I have time zone set to browser time in grafana settings.

No changes have been made besides the upgrade.  I assuming this was working by  accident in the past

**Comment by PimpJuiceIT** [comment] 2018-10-17 19:31
@wiyotndn 

That appears to be the case per https://community.grafana.com/t/preset-time-frames-broken-shows-no-data-points-date-is-5-hours-ahead/10683/7

> Our intention have never been to support anything else than UTC on Grafana and UTC in database/storing timestamps in actual UTC time in database. Unfortunately this have worked for you unintentionally before. Hopefully we can find a way to manage multiple timezones in dashboard/datasource in the future.

I do have UTC time values in these tables but the time zone adjustments still need to be made. The time zone thing and the offsetting per daylight saving time may be the two hurdles here for me at least—this is why I test though.

Look into a solution such as the one mentioned here using variables https://github.com/grafana/grafana/issues/13621#issuecomment-429137697. If I get a clear solution that works for me, I will share with detail with you and others.

**Comment by wiyotndn** [comment] 2018-10-17 20:40
Changing from __timefilter() to
WHERE UNIX_TIMESTAMP(action_time) between $__unixEpochFrom() and  $__unixEpochTo()
gives me the expected results with no additional changes

It appears the unixEpochFrom is using browser time and __timeFilter is not

with  unixEpochFrom and  unixEpochTo
SELECT
  UNIX_TIMESTAMP(action_time) as time_sec,
  count(action_time)
  action_time
FROM fail2ban
WHERE UNIX_TIMESTAMP(action_time) between 1539797597 and  1539808397
1539797597  = 2018-10-17 12:33:17

Using Time filter
SELECT
  UNIX_TIMESTAMP(action_time) as time_sec,
  count(action_time)
  action_time
FROM fail2ban
WHERE action_time BETWEEN '2018-10-17T17:34:13Z' AND '2018-10-17T20:34:13Z'

**Comment by PimpJuiceIT** [comment] 2018-10-17 21:21
Big thanks to @wiyotndn 

> Changing from `__timefilter()` to
>     WHERE UNIX_TIMESTAMP(action_time) between $__unixEpochFrom() and $__unixEpochTo()
> gives me the expected results with no additional changes. 
> It appears the `unixEpochFrom() `is using browser time and `__timeFilter()` is not
> with `unixEpochFrom()` and `unixEpochTo()`

### My Solution

Use . . . 

    WHERE UNIX_TIMESTAMP(TimeStr) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()

@torkelo @marefr Any change of getting some sort of macro for this in a future enhancement? If the workaround is as simple as that, then I suppose being a dynamic macro would not be too difficult.

**Comment by torkelo** [comment] 2018-10-18 15:46
Both are using UTC time, the reason why the second alternative works for you is that you use UNIX_TIMESTAMP(action_time)  which will translate your non UTC stored date to a UTC time

**Comment by PimpJuiceIT** [comment] 2018-10-18 16:28
@torkelo 

Yes, I realize that but in the past you could simply use `$__timeFilter(action_time)` to pass in the non-UTC value and it would take care of the rest. Not you have to use `UNIX_TIMESTAMP(action_time) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()` to get the same result on the `WHERE` clause. 

I guess I was wondering if it'd be difficult to build a separate macro that takes the non-UTC and translates it for you automatically. It seems the `$__time(column) -> UNIX_TIMESTAMP(column) as time_sec` does this for you and accepts the non-UTC value and does the conversion behind the scenes dynamically I suppose using `UNIX_TIMESTAMP(column)` per it's method. 

The reason I ask and mention this as the response quoted above states _"Our intention have never been to support anything else than UTC"_; however, it seems like the `$__time(column)` actually is there for that specific reason and `$__timeFilter(column)` used to do that to ensure the whatever filter you have set on the "time range" settings ensures the chart scales the time accordingly when the column values were non-UTC. 

I am totally fine with the workaround but the hope would be that the `$__time(column)` functionality will never change to not support the non UTC values like as occurred with the ``$__timeFilter(column)` functionality. 

In my case I do have a table that contains UTC from each device and/or correlated table, but the device's non-UTC time values adjusts for daylight saving time and offsets for the timezone the device is in. Using pure UTC for the data and the web browser settings, etc. in Grafana doesn't list data offsetting time zone or accounting for Daylight Saving Time whereas the data in the DB table already does this so the data for this is already there. 

I just wanted to mention this to you specifically as I'm sure others could have some great helpfulness with this sort of functionality that is more clear how to use is as such with the great Grafana product you have. 

I appreciate you and your team and all your efforts and the Grafana system.

**Comment by PimpJuiceIT** [comment] 2018-10-18 18:10
@torkelo @marefr 

Lastly, something else I wanted to mention in **addition to my above feedback** that I just noticed to mention since I test between the `5.2.3` and `5.3.1` against the same DB tables and servers, it seems the old method using `WHERE $__timeFilter(column)` responds much much quicker than the new `UNIX_TIMESTAMP(action_time) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()` method but I'll break down the SQL and run both queries against the instance and look it over with `EXPLAIN` or whatever to see the differences. The `$__timeFilter(column)` seems to perform the SQL more efficiently though than the new syntax getting the exact same data from the exact same server on the exact same Hyper-V hardware where both CentOS machines are setup and running from.

**Comment by PimpJuiceIT** [comment] 2018-10-18 22:16
@torkelo @marefr 

Okay, disregard that last comment, I did a compare with `EXPLAIN` and it seems we have an index on the `TimeStr` (non-UTC) column and not the `TimeInt` (UTC) column. Sorry about that—total oversight; d'oh!!

Thanks for listening guys, keep up the great work!!

**Comment by PimpJuiceIT** [comment] 2018-10-18 22:33
@torkelo @marefr 

I was wrong again.... It seems that in MySQL the execution plan cannot use an index when you use the `UNIX_TIMESTAMP()` function. 

The old method method used `$__timeFilter()` and generated SQL something like.... 

`WHERE TimeStr >= FROM_UNIXTIME(1539835200) AND TimeStr <= FROM_UNIXTIME(1539898805) AND Value > 0`

Explain shows (returns in less than 1 second)...

![image](https://user-images.githubusercontent.com/44209265/47187909-dcf1d900-d303-11e8-9f55-3dff4277f510.png)

The new method now gives SQL something like.... 

`WHERE UNIX_TIMESTAMP(TimeStr) BETWEEN 1539835200 AND 1539900108 AND Value > 0`

Explain shows (returns after 17 seconds)... 

![image](https://user-images.githubusercontent.com/44209265/47187941-fbf06b00-d303-11e8-9fae-fe196fc2a04b.png)


As you can see, using the ` UNIX_TIMESTAMP()` method to specify the non-UTC means MySQL cannot use any index. I'll play with it more later and see if I can find a better solution.


Related post... https://dba.stackexchange.com/questions/28310/is-a-query-with-unix-timestamp-using-indexes-in-mysql

**Comment by torkelo** [comment] 2018-10-19 04:36
Which explains why we changed it

**Comment by marefr** [comment] 2018-10-22 07:29
Closing this since it's a duplicate of #13621

**Closed** 2018-10-22 07:29 UTC
Labels: datasource: MySQL, state: needs more detail

**Comment by RafaellaN** [comment] 2018-12-04 15:53
Hello, I am looking something like this, I want to be able to do average of values between specific time each day. Anyone know how it done?
SELECT
UNIX_TIMESTAMP(DateTime) as time_sec,
  avg(MyValue) as value,
  'MyValue' as metric
  
FROM MyTABLE
WHERE SN='$VARIABLE' and BETWEEN 'Today 15:00:00' AND 'Today 16:35:54'

**Comment by PimpJuiceIT** [comment] 2018-12-04 16:16
> Hello, I am looking something like this, I want to be able to do average of values between specific time each day(different day). Anyone know how its done? The below doesn't work and it seems that i can't find something similar..
> SELECT
> UNIX_TIMESTAMP(DateTime) as time_sec,
> avg(MyValue) as value,
> 'MyValue' as metric
> 
> FROM MyTABLE
> WHERE SN='$VARIABLE' and BETWEEN 'Today 15:00:00' AND 'Today 16:35:54'

Consider opening a separate post asking the question with all the other usual detail opening a question provides you to fill in. Be thorough with your detail and just put a link to this post and state that you're looking for something such as "X" query posted here. Why not just let the time filter up top dictate the time range based on what it selected there to show though and take out the `BETWEEN` statement entirely?

**Comment by PimpJuiceIT** [comment] 2018-12-04 16:21
@RafaellaN 

> Hello, I am looking something like this, I want to be able to do average of values between specific time each day(different day). Anyone know how its done? The below doesn't work and it seems that i can't find something similar..
> SELECT
> UNIX_TIMESTAMP(DateTime) as time_sec,
> avg(MyValue) as value,
> 'MyValue' as metric
> 
> FROM MyTABLE
> WHERE SN='$VARIABLE' and BETWEEN 'Today 15:00:00' AND 'Today 16:35:54'

Try something like....

```
SELECT $__time(DateTime)
	, avg(MyValue) as value
	, 'MyValue' as metric
FROM MyTABLE
WHERE SN='$VARIABLE' and BETWEEN $__timeEpoch(DateTime)
```
