### ISSUE TITLE
Grafana 5.1.5 Table panel column names doesnt wrap 

### ISSUE THREAD

**Issue by ShilpaSivanesan** [grafana/grafana#13050] opened 2018-08-28 06:44 UTC
The table panel column names are overlapped when then no of columns are high
<img width="1582" alt="screen shot 2018-08-27 at 11 56 58 pm" src="https://user-images.githubusercontent.com/34906268/44705960-f5a4e780-aa54-11e8-857d-f8bf540f6d9e.png">

**Comment by torkelo** [comment] 2018-08-28 07:31
duplicate of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2018-08-28 07:31 UTC
