### ISSUE TITLE
Datasources: multiple default datasources

### ISSUE THREAD

**Issue by mhulscher** [grafana/grafana#80785] opened 2024-01-18 09:48 UTC
### What happened?

Since we upgraded to Grafana 10.2.3 (introduced in helm release 7.0.22) we are frequently seeing Grafana ignoring the  `is_default: false` attribute when creating new datasources. We even see multiple datasources being marked as default, which should not be possible.

This also leads to idempotency issues when using terraform:

* a datasource is created with `is_default: false`
* the next run of `terraform plan` reads the datasource and sees that attribute `is_default` is `true`
* terraform reports that it wants to make a change

```
  # grafana_data_source.additional["foo"] will be updated in-place
  ~ resource "grafana_data_source" "additional" {
        id                       = "1:8"
      ~ is_default               = true -> false
        name                     = "Foo"
        # (9 unchanged attributes hidden)
    }

  # grafana_data_source.additional["bar"] will be updated in-place
  ~ resource "grafana_data_source" "additional" {
        id                       = "1:15"
      ~ is_default               = true -> false
        name                     = "Bar"
        # (9 unchanged attributes hidden)
    }

  # grafana_data_source.additional["baz"] will be updated in-place
  ~ resource "grafana_data_source" "additional" {
        id                       = "1:7"
      ~ is_default               = true -> false
        name                     = "Baz"
        # (8 unchanged attributes hidden)
    }

  # grafana_data_source.additional["qux"] will be updated in-place
  ~ resource "grafana_data_source" "additional" {
        id                       = "1:6"
      ~ is_default               = true -> false
        name                     = "Qux"
        # (8 unchanged attributes hidden)
    }
```

### What did you expect to happen?

Datasources should not be marked as default.

### Did this work before?

Yes

### How do we reproduce it?

We create tens of datasources with terraform with a parallelism of 25, so high concurrency. All have the `is_default` value set to false.

### Environment (with versions)?

Grafana **Enterprise**: 10.2.3

### Grafana platform?

Self-hosted

### Datasource(s)?

All of them

**Comment by pathcl** [comment] 2024-01-31 22:14
@mhulscher which terraform provider are you using? and which terraform? seems an interesting issue to fix

**Comment by tonypowa** [comment] 2024-02-14 15:56
Hi @mhulscher 

thank you for reporting this issue

In order to route the issue to the appropriate team, could you please check if you can provision the data source(s) via the [Grafana API ](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/)(without terraform, create datasources with POST requests) ? 
If it's reproducible I will know which team to route this to

Thanks in advance

**Comment by mhulscher** [comment] 2024-03-08 09:41
Hi @tonypowa I am going to have to take a look. However, the problem started appearing after upgrading Grafana, while keeping the version of the TF provider the same. We are using the latest version of the TF provider. Which is 2.13.0 at the moment.

**Comment by tonypowa** [comment] 2024-05-20 07:47
closing this since there hasn't been any updates for a while
feel free to add more info and request to reopen if the issue persists

**Closed by tonypowa** 2024-05-20 07:47 UTC
Labels: needs more info, area/provisioning
