### ISSUE TITLE
Live measurements stopped working for Grafana 8.0.4 and above on Linux

### ISSUE THREAD

**Issue by rokitski** [grafana/grafana#38414] opened 2021-08-21 19:15 UTC
**What happened**:
Live measurements stopped working in time series, stat panels after Grafana is updated to version 8.0.4 and above

**What you expected to happen**:
Live measurements operational, as in Grafana 7.4 -> 8.0.3

**How to reproduce it (as minimally and precisely as possible)**:
Install Grafana 8.0.3 or below on Linux. Create test dashboard with a time series panel, connected to Grafana internal data source, choose live measurements under query type. Choose one of the test data streams: 2s or 20Hz. Confirm that the panel displays live data.
Upgrade Grafana to any version above 8.0.3 and check the panel. Confirm that the streams are still available in panel configuration. Live measurements don't work and the wheel in the upper right corner of the panel continuously spins

**Anything else we need to know?**:
I've tested versions 8.0.0, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.1.1, 8.1.2 on Raspberry Pi. Live measurements work as expected up to version 8.0.3 and don't work on any version above 8.0.4
On Red Hat linux I've tested versions 8.0.3 and 8.1.1. In 8.0.3 live streaming works and on 8.1.1 it doesn't.

**Environment**:
- Grafana version: 8.0.4 and above
- Data source type & version: built-in plugin/testdata/random-20Hz-stream
- OS Grafana is installed on: Raspbian, Red Hat Linux
- User OS & Browser: Any - Mobile phone, tablet, laptop
- Grafana plugins: Standar plugins (no custom plugins installed)
- Others:

**Comment by hugohaggmark** [comment] 2021-08-23 05:07
Hi @rokitski and thank you for reporting this, this feature is under heavy development so expect the interfaces and structures to change as this becomes more production ready. I can reproduce this for Grafana 8.1.2.

**Comment by hugohaggmark** [comment] 2021-08-23 05:09
@ryantxu @FZambia is this something you are aware of?

**Comment by FZambia** [comment] 2021-08-23 06:35
Most probably the duplicate of #36929 

@rokitski hello, could you check out the linked issue? You can start with looking at browser Javascript console (Chrome devtools) – most probably you'll see 403 error returned when connecting to WebSocket endpoint. Or look at Grafana server logs – there should be a warning with a message `Request Origin is not authorized`. In this case fixing `[server] root_url` or setting `[live] allowed_origins` should help.

**Comment by rokitski** [comment] 2021-08-25 04:10
It appears that the issue is related based on the logs in [#36929](https://github.com/grafana/grafana/issues/36929) .

Here are logs from Grafana, when live measurements demo worked fine with Grafana 8.0.3 until Grafana 8.1.2 was installed at t=2021-08-24T20:57:08-0700. With Grafana 8.1.2 error messages show up in the log. I've attached dashboard setup showing internal Grafana source. Live measurements don't work with version > 8.0.3 using external data uploads using curl as well.

[Grafana_live_measurements_errors.log](https://github.com/grafana/grafana/files/7043573/Grafana_live_measurements_errors.log)
<img width="1129" alt="Grafana_803_works" src="https://user-images.githubusercontent.com/85377025/130725033-74dbd7fe-6c75-461f-9151-def927a7623c.png">

**Closed** 2021-08-25 07:01 UTC
Labels: type/bug, area/live

**Comment by FZambia** [comment] 2021-08-25 09:28
@rokitski thanks, opened a pull request to discuss whether we should support behavior of Grafana v8.0.0-v8.0.3 in #38538 – to avoid such problems you experienced.
