### ISSUE TITLE
loki tag filtering does not take effect in the data source

### ISSUE THREAD

**Issue by zhaomingcheng01** [grafana/grafana#91820] opened 2024-08-13 01:45 UTC
### What happened?

![image](https://github.com/user-attachments/assets/9f2592db-7a20-49de-be60-39ba4d39991a)

### What did you expect to happen?

Tags can be used to filter values

### Did this work before?

Have not tried

### How do we reproduce it?

1. Install the latest version of grafana
2. Install the latest version of Google
3. Use the following dashboard

### Is the bug inside a dashboard panel?

{
  "annotations": {
    "list": [
      {
        "$$hashKey": "object:75",
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "description": "Loki logs panel with prometheus variables ",
  "editable": true,
  "fiscalYearStartMonth": 0,
  "gnetId": 15324,
  "graphTooltip": 0,
  "id": 3,
  "links": [
    {
      "asDropdown": false,
      "icon": "bolt",
      "includeVars": true,
      "keepTime": true,
      "tags": [],
      "targetBlank": true,
      "title": "View In Explore",
      "tooltip": "",
      "type": "link",
      "url": "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{namespace=\\\"$namespace\\\",pod=~\\\"$pod\\\"}|=\\\"$search\\\"\"},{\"ui\":[true,true,true,\"none\"]}]"
    }
  ],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "loki",
        "uid": "cdu6q8s9kcv0ge"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "hidden",
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 100,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "links": [],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "short"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 3,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 6,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": false
        },
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        }
      },
      "pluginVersion": "10.4.0",
      "targets": [
        {
          "datasource": {
            "type": "loki",
            "uid": "cdu6q8s9kcv0ge"
          },
          "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"[$__interval]))",
          "refId": "A"
        }
      ],
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "loki",
        "uid": "cdu6q8s9kcv0ge"
      },
      "gridPos": {
        "h": 25,
        "w": 24,
        "x": 0,
        "y": 3
      },
      "id": 2,
      "maxDataPoints": "",
      "options": {
        "dedupStrategy": "exact",
        "enableLogDetails": true,
        "prettifyLogMessage": false,
        "showCommonLabels": false,
        "showLabels": false,
        "showTime": false,
        "sortOrder": "Ascending",
        "wrapLogMessage": false
      },
      "targets": [
        {
          "datasource": {
            "type": "loki",
            "uid": "cdu6q8s9kcv0ge"
          },
          "expr": "{namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"",
          "refId": "A"
        }
      ],
      "title": "Logs Panel",
      "type": "logs"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "j-SADWmVk"
      },
      "gridPos": {
        "h": 3,
        "w": 24,
        "x": 0,
        "y": 28
      },
      "id": 4,
      "options": {
        "content": "<div style=\"text-align:center\"> For Grafana Loki blog example </div>\n\n\n",
        "mode": "html"
      },
      "pluginVersion": "9.0.5",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "j-SADWmVk"
          },
          "refId": "A"
        }
      ],
      "transparent": true,
      "type": "text"
    }
  ],
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "kube-system",
          "value": "kube-system"
        },
        "datasource": {
          "type": "loki",
          "uid": "cdu6q8s9kcv0ge"
        },
        "definition": "",
        "hide": 0,
        "includeAll": false,
        "label": "namespace",
        "multi": false,
        "name": "namespace",
        "options": [],
        "query": {
          "label": "namespace",
          "refId": "LokiVariableQueryEditor-VariableQuery",
          "stream": "",
          "type": 1
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      },
      {
        "current": {
          "selected": false,
          "text": "ack-node-cleaner-1723510800-7x9dc",
          "value": "ack-node-cleaner-1723510800-7x9dc"
        },
        "datasource": {
          "type": "loki",
          "uid": "cdu6q8s9kcv0ge"
        },
        "definition": "",
        "hide": 0,
        "includeAll": false,
        "label": "pod",
        "multi": false,
        "name": "pod",
        "options": [],
        "query": {
          "label": "pod",
          "refId": "LokiVariableQueryEditor-VariableQuery",
          "stream": "{namespace=\"$namespace\"}",
          "type": 1
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      },
      {
        "current": {
          "selected": false,
          "text": "level=warn",
          "value": "level=warn"
        },
        "hide": 0,
        "label": "Search",
        "name": "search",
        "options": [
          {
            "selected": true,
            "text": "level=warn",
            "value": "level=warn"
          }
        ],
        "query": "level=warn",
        "skipUrlSync": false,
        "type": "textbox"
      }
    ]
  },
  "time": {
    "from": "now-30m",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "Loki Logs Dashboard",
  "uid": "liz0yRCZz",
  "version": 10,
  "weekStart": ""
}

### Environment (with versions)?

Grafana: 11.1.3
OS: 
Browser: Google Latest edition

### Grafana platform?

Kubernetes

### Datasource(s)?

mysql8.0

**Comment by KaloyanHr** [comment] 2024-08-13 07:00
Hello,

I have a similar problem.

Loki v2.8.2 in k8s
Grafana OSS v11.1.3 on a Linux VM

After the upgrade from v10.4.1 to v11.1.3, there is a problem with the labels from our Loki data sources. When you choose a specific system with a hostname label and then try to filter for example the jobs for the system or the log file that’s scraped it’s showing all possible options (for all systems from that data source) instead of filtering the jobs/log files/etc. for the specific system. After testing by adding my Loki data sources on a separate Grafana isntance, this seems to start breaking from v11.1.X, on 11.0.X it is still working correctly. The interesting thing is that the Label Browser is filtering correctly, however the Explore field is not. The problem is that this is breaking my filters in my logs dashboards by showing all values for all systems from the Loki data source even though I select a specific system on which I want to filter. I couldn’t find any workaround and also couldn’t find any information in the changelog, breaking changes, etc. that explain why this would break in 11.1.X. Can you please advise if there’s some kind of fix for this planned and why it’s working in 11.0.X but not in 11.1X ?

**Comment by lux4rd0** [comment] 2024-08-14 12:32
Broken for awhile unfortunately...

https://github.com/grafana/loki/issues/12983

**Comment by jd-hatzenbuhler** [comment] 2024-09-02 14:28
same issue here in 11.2.0 version

**Comment by matyax** [comment] 2024-11-25 11:22
Hi everyone! I just verified that the stream selector is sent and interpolated before fetching label values.

![Image](https://github.com/user-attachments/assets/10a8e96a-2e52-4268-854e-a34db0d8bb92)

Please make sure both Grafana and Loki are on the most recent versions. Thank you for reporting this.

**Closed by matyax** 2024-11-25 11:22 UTC
Labels: datasource/Loki
