### ISSUE TITLE
Grafana: Webhook Failed Validation - upon sending message to Teams

### ISSUE THREAD

**Issue by Wireheadbe** [grafana/grafana#89617] opened 2024-06-24 12:03 UTC
### What happened?

When sending a mail to a Teams Chat, we get the message "Failed to send alert.: send notification to Teams: webhook failed validation:

![image](https://github.com/grafana/grafana/assets/4497972/2ea5f422-5018-46d3-bec7-d66ce0a0da1b)

The message is delivered fine in the Teams chat, however, Grafana insists that the message was not delivered due to this. In turn, it will try to resend the message at regular intervals

### What did you expect to happen?

Seeing the message was delivered correctly, there is probably an issue in the way the response codes are handled.

### Did this work before?

I hadn't tested this before, but it seems people have had this before:
https://github.com/grafana/grafana/issues/60924

### How do we reproduce it?

1. Create a new webhook for a teams chat
2. Create a new contact
3. Send a test alert and observe

### Environment (with versions)?

Grafana: 11.0.0, also happens on 11.1.0-180959
OS: n/a -> docker image 
Browser: Any

### Grafana platform?

Docker

**Comment by grigassukys** [comment] 2024-07-18 07:07
Exactly the same issue on our side also.
We are using new Teams Workflows from Microsoft PowerAutomate. 
Using old Webhooks (which are being deprecated) everything works as intended.

**Comment by tonypowa** [comment] 2024-07-19 09:03
Hello @Wireheadbe 

Thank you for creating this issue

If possible, could you check and share any related logs from Grafana's server side? In addition do you see any relevant details in  browser inspector tool (network tab)?

**Comment by ceesios** [comment] 2024-07-19 09:12
We are also having this issue. I assume it has something to do with the http return code being 202 now and 200 in the old "webhook.office.com" situation. Also the return headers differ.

**Comment by ceesios** [comment] 2024-07-19 13:41
Duplicate of #90139

**Closed** 2024-07-19 15:28 UTC
Labels: needs more info, area/alerting
