### ISSUE TITLE
Generic mark & copy selection from dashboard to clipboard

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#3348] opened 2015-11-26 11:00 UTC
As ive started to play around with the new table panel i notice you cannot select any data and copy it to clipboard unless you do edit of a panel/dashboard , then it works. 
Have tried with different browsers and its the same.

**Comment by eostermueller** [comment] 2015-12-06 02:31
+1, this would be great to have...

If enhanced a bit, this feature could kill a few birds with one stone.
I'm still trying to find a way to cross reference a short metric name in grafana
to a very long name -- as long as 8k of text, the text of a SQL statement.

This post provides a little more detail:
https://groups.io/g/grafana/messages?expanded=1&d=&msgnum=710

The new grafana table panel works like a GROUP BY, right?
How tough would it be for grafana to make a webservice call to for each row in the group by (grouped by short metric name), asking for the long name for each short metric.

Grafana would then include the "long name" in the copy clipboard...but would never have to tackle the sticky issue of displaying the 8k of text.

I just made the first release this morning of my app that writes JDBC SQL perf metrics to influx/grafana.
Check out http://wuqiSpank.org

**Comment by torkelo** [comment] 2016-01-20 14:55
duplicate of https://github.com/grafana/grafana/issues/2083

**Closed by torkelo** 2016-01-20 14:55 UTC
Labels: comp: panel/table
