### ISSUE TITLE
New Value: A dynamic max value for the y-axis for graphs

### ISSUE THREAD

**Issue by Trysupe** [grafana/grafana#25873] opened 2020-06-27 09:09 UTC
**What would you like to be added**:

A dynamic max value for the y-axis for graphs

**Why is this needed**:

Currently there are the min value and the max value available for the y-axis
![image](https://user-images.githubusercontent.com/45742226/85918658-faab6b80-b864-11ea-8cbc-e4156cae88cc.png)

If left empty they scale of the y-axis will be set automatically which is pretty nice since it shows the maximum amount of detail.

The problem:
I got a graph which shows pings times of my network devices over time. Sometimes one of these devices is not responding and the ping jumps up to about 3000ms. If I put no max value for the y-axis a see all these huge spikes and all the detail for the low numbers gets lost:
![image](https://user-images.githubusercontent.com/45742226/85918730-a0f77100-b865-11ea-83ef-f426220439d6.png)

As a consequence I put in the y-max value of 1500ms which has the benefit that the spikes are partly visible and most of the low ping information is visible as well:
![image](https://user-images.githubusercontent.com/45742226/85918765-d4d29680-b865-11ea-8d2f-5f01cf5202fb.png)
However when there are no spikes I loose a huge amount of details as seen here:
![image](https://user-images.githubusercontent.com/45742226/85918775-f03da180-b865-11ea-92e6-6db6c8da3458.png)

So this is where the dynamic max value for the y-axis comes in: It should be like "auto" on the current "y-max" value however should have a limit on the top end.
In this example: when there are no spikes the "y-max" value should be empty so as much of the low ping information is visible. When there are spikes going up the y-axis should be bottled at a certain point (like 1500ms) so I only loose some bit of information of the low pings.

Any questions, opinions or suggestions?

**Comment by torkelo** [comment] 2020-06-28 06:19
duplicate of https://github.com/grafana/grafana/issues/979

**Closed by torkelo** 2020-06-28 06:19 UTC
