### ISSUE TITLE
tsdb.HandleRequest() response error &{pq: relation "metric_table" does not exist A ...

### ISSUE THREAD

**Issue by huynhsamha** [grafana/grafana#19301] opened 2019-09-23 08:30 UTC
**What happened**:
Alerting with PostgreSQL and TimescaleDB got an error on Test Rule
> tsdb.HandleRequest() response error &{pq: relation "metric_table" does not exist A 0xc000ba6900 [] []}

**What you expected to happen**:
I'd like it works.

**How to reproduce it (as minimally and precisely as possible)**:
Connect Grafana with PostgreSQL (with TimescaleDB).
Create an Alert and run Test Rule.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5
- Data source type & version:PostgreSQL 9.3
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 16.04 and Chrome
- Grafana plugins: Grafana Image Render
- Others:

Some images

![img1](https://user-images.githubusercontent.com/24195776/65411359-dd012f80-de16-11e9-9936-19cca4fefb9b.png)

![img2](https://user-images.githubusercontent.com/24195776/65411364-df638980-de16-11e9-92e9-0bd2bb13c318.png)

Full errors on Test Rule:

```json
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "16.299ms",
  "error": "tsdb.HandleRequest() response error &{pq: relation \"metric_table\" does not exist  A 0xc0011aa8b0 [] []}",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1569227207690,
        "queries": [
          {
            "refId": "A",
            "model": {
              "format": "time_series",
              "group": [
                {
                  "params": [
                    "$__interval",
                    "none"
                  ],
                  "type": "time"
                }
              ],
              "interval": "",
              "metricColumn": "none",
              "rawQuery": false,
              "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
              "refId": "A",
              "select": [
                [
                  {
                    "params": [
                      "nice"
                    ],
                    "type": "column"
                  },
                  {
                    "params": [
                      "avg"
                    ],
                    "type": "aggregate"
                  },
                  {
                    "params": [
                      "nice"
                    ],
                    "type": "alias"
                  }
                ]
              ],
              "table": "cpu_metric",
              "timeColumn": "\"timestamp\"",
              "timeColumnType": "timestamp",
              "where": [
                {
                  "name": "$__timeFilter",
                  "params": [],
                  "type": "macro"
                }
              ]
            },
            "datasource": {
              "id": 1,
              "name": "PostgreSQL"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1569227267690
      }
    }
  ]
}
```

**Comment by marefr** [comment] 2019-09-23 09:46
Duplicate of #19063

**Closed** 2019-09-23 09:46 UTC

**Comment by huynhsamha** [comment] 2019-09-26 07:35
Hi @marefr, can you show me how to make alert work with the form UI instead of the raw sql? I've changed to raw SQL, and it worked both using test rule and trigger the real alert. But I want to use alert with query builder in the form UI.

**Comment by marefr** [comment] 2019-09-26 08:05
@huynhsamha a fix is included in Grafana v6.4-beta2.

**Comment by huynhsamha** [comment] 2019-09-26 08:44
@marefr, which commits I can follow to update my source? Because I've customized something from source which I cloned before. I think i cloned from v6.4.0-beta1.

**Comment by marefr** [comment] 2019-09-26 13:17
Given you've customized and commit those changes to a working branch, named X here for brevity. Branch off from latest Grafana v6.4.x branch into branch Y and cherry-pick your customized commits using `git cherry-pick <commit sha>` where `<commit sha>` you should find by doing a `git log` when in branch X.

Alternatively, branch off from latest Grafana v6.4.x branch into new branch and manually apply your customization you earlier done.

The commit in master is https://github.com/grafana/grafana/commit/7c499ffdd87af54d3d7ea2dfcc5095eb6d52573a

One other alternative would be to cherry pick that into your current branch `git fetch origin/master` where origin is grafana/grafana followed by `git cherry-pick 7c499ffdd87af54d3d7ea2dfcc5095eb6d52573a`

Let me know if you don't understand..

**Comment by huynhsamha** [comment] 2019-09-27 02:14
Sorry, I didn't checkout a new branch from Grafana source. Because Grafana source is too large, I'd removed too many files and folders I don't need (examples as `docs` and other markdown files). Therefore I can't fetch from origin Grafana.

However, I updates source with your reference commit [7c499ff](https://github.com/grafana/grafana/commit/7c499ffdd87af54d3d7ea2dfcc5095eb6d52573a) manually, and it works :laughing: 

Thanks so much!!
