### ISSUE TITLE
Idea: Punch-Card graph type

### ISSUE THREAD

**Issue by Luzifer** [grafana/grafana#2333] opened 2015-07-11 15:13 UTC
As I'm graphing chat engagement in one of my Grafana dashboards I came across the idea of a Punch-Chard graph type similar to the [GitHub commit Punch-Card](https://github.com/grafana/grafana/graphs/punch-card). Don't really know whether this is possible but maybe this might be a good use for people wanting to display for example (my usecase) when more ops in the chat are required because of large amount of chatters online.

**Comment by mattttt** [comment] 2015-07-12 00:38
Slack has a very similar viz in the weekly email to admins:

![image](https://cloud.githubusercontent.com/assets/2886187/8635876/cc4bb2ce-280c-11e5-831d-b8c51db46b8d.jpg)

**Comment by deebs031** [comment] 2015-07-24 20:57
+1

**Comment by bodsch** [comment] 2015-11-06 09:47
+1

**Comment by vkroz** [comment] 2018-03-19 19:00
+1

**Comment by torkelo** [comment] 2018-04-21 12:12
This would be a cool panel but does not need to be in the core but can be an external plugin (to begin with).

We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

**Closed by torkelo** 2018-04-21 12:12 UTC
Labels: type: feature request

**Comment by nirname** [comment] 2023-10-16 20:37
+1. I see the issue is closed and there are like 3.7k opened issues currently. But I'd like revive this one. Our team has exactly this case, where we have information which is represented in punch-card.
