### ISSUE TITLE
Template-able alerts

### ISSUE THREAD

**Issue by tomsucho** [grafana/grafana#24370] opened 2020-05-07 06:20 UTC
**What would you like to be added**:
some basic templating for alerts so that the user can customize the alert messages

**Why is this needed**:
Currently all is static and you can actually only customize the alert name and alert message. You can also add tags aka labels but they are static text as well. If I wanted to add a tag to show up as a label in alertmanager say "instance_name"=$metric with the value of the metric name set dynamically it is not possible. This is needed as alerting can go to various notification channels 
 through alertmanger, each of which may expect a certain alert message format and labels. So being able to customize the alert message via templating is critical for such integrations.
Something like Prometheus does would be awesome to have.

**Comment by torkelo** [comment] 2020-05-07 08:53
duplicate of https://github.com/grafana/grafana/issues/7121 and other issues

**Closed by torkelo** 2020-05-07 08:53 UTC
