### ISSUE TITLE
Empty snapshots

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#5737] opened 2016-08-05 14:34 UTC
Grafana 3.1.1 from the official Docker image, OpenTSDB datasource. When I create a snapshot for a long period of time that is not so fast to fetch, snapshot is saved with no data.

Snapshot is saved, but queries are still in progress:

![image](https://cloud.githubusercontent.com/assets/89186/17439834/bc7f678e-5b21-11e6-9142-f1d3c54e0ec3.png)

And queries return much later:

![image](https://cloud.githubusercontent.com/assets/89186/17439868/da19dd6a-5b21-11e6-92c0-56b1b1d53785.png)

**Comment by torkelo** [comment] 2016-08-05 15:48
dupe of 
https://github.com/grafana/grafana/issues/2537

**Closed by torkelo** 2016-08-05 15:48 UTC
