### ISSUE TITLE
sticky option for variable option section

### ISSUE THREAD

**Issue by hertz1987** [grafana/grafana#14644] opened 2018-12-23 03:51 UTC
Grafana version: 5.4.2
Datasource version: Elasticsearch 6.4.2

OS version: Ubuntu 16.04

Did what:  Scrolling down the dashboard

Expected result: variables option should be sticky along with dashboard option buttons,so I don't have to scroll up the page when trying to change the variable options. besides, after change of variable options and page refresh, the page should stay where i last visited it, for example,if I scrolled down about 50% of the page height, and changed some variable option that caused a page refresh, the refreshed page should stay at 50% of the page height.

**Comment by torkelo** [comment] 2018-12-23 06:40
duplicate of https://github.com/grafana/grafana/issues/11166

**Closed by torkelo** 2018-12-23 06:40 UTC
