### ISSUE TITLE
Custom time range window cannot be scrolled down on IOS safari/chrome

### ISSUE THREAD

**Issue by wayn0728** [grafana/grafana#13331] opened 2018-09-19 02:58 UTC
I upgraded my grafana to V5.2.4. When I use it on ios, I want to select time range as "last 12 hours", but the time selection window height is not enough and cannot be scrolled down. "last 12 hours" is on the very bottom of the window so that I cannot choose it.
![gnf](https://user-images.githubusercontent.com/2744466/45728703-c4ef4280-bbfb-11e8-9161-7a11c8a47234.jpg)

**Comment by torkelo** [comment] 2018-09-19 07:47
duplicate of https://github.com/grafana/grafana/issues/11845

**Closed by torkelo** 2018-09-19 07:47 UTC
