### ISSUE TITLE
Alerting: Alert List Panel: setting the `Alert state filter` option to `Normal` doesn't return any results when using Prometheus data source

### ISSUE THREAD

**Issue by avanish-vaghela** [grafana/grafana#76820] opened 2023-10-19 14:19 UTC
### What happened?

Alerting: Alert List Panel: setting the `Alert state filter` option to `Normal` doesn't return results when using Prometheus data source

Panel: https://play.grafana.org/d/Kb2RgVQnk/alert-panel?orgId=1&refresh=5s&editPanel=2

<img width="1453" alt="Screenshot 2023-10-19 at 3 10 59 pm" src="https://github.com/grafana/grafana/assets/25927235/9b723c21-0002-4eeb-ae2a-646299c7d99b">

<img width="1714" alt="Screenshot 2023-10-19 at 3 02 00 pm" src="https://github.com/grafana/grafana/assets/25927235/29376828-15b6-4c83-bc06-c2ba2c07f891">

### What did you expect to happen?

The alert panel should display alerts in the `normal` (inactive) state i.e. non-firing or non-pending when the `Normal` option is enabled

### Did this work before?

Not sure

### How do we reproduce it?

1. Go to https://play.grafana.org/d/000000074/alerting?orgId=1&viewPanel=3&editPanel=3
2. Change the data source to `grafanacloud-play-prom` or any other Prometheus data source where there are alerts
3. In the Alert List Panel's setting change `Alert state filter` to `Normal` 

### Environment (with versions)?

**Grafana:** Grafana v10.1.1 (0cfa76b22d)
**OS**: MacOS Ventura 13.6
**Browser:** Chrome 118.0.5993.70 

### Grafana platform?

Kubernetes

### Datasource(s)?

Mimir/Prometheus

**Comment by tonypowa** [comment] 2023-11-02 21:42
hi @avanish-vaghela 

thanks for reporting this bug

I am adding the issue to the alerting team's board for review

**Comment by avanish-vaghela** [comment] 2023-11-09 12:14
Hi, Thanks for the explanation and reply. As you said the current behaviour is subpar and can be improved. I am happy to contribute toward making it less confusing if you point me in the right direction. Can we please reopen this issue and I can work on a PR to make it a better experience?

**Comment by armandgrillet** [comment] 2023-11-10 19:46
This is not a beginner-friendly issue, reopening as this might be a regression for legacy alerting users (we haven't confirmed that yet though).

**Comment by floka94** [comment] 2024-02-07 09:06
Still have the same problem!

**Comment by gillesdemey** [comment] 2024-06-11 13:35
Closing this one – Prometheus-based data sources (including Mimir and Cortex) do not generate "normal" instances (unlike the built-in Grafana ruler).

**Closed by gillesdemey** 2024-06-11 13:35 UTC
Labels: type/bug, area/panel/alertlist

**Comment by jmichalek132** [comment] 2024-06-26 09:21
> Closing this one – Prometheus-based data sources (including Mimir and Cortex) do not generate "normal" instances (unlike the built-in Grafana ruler).

That is true, but the point of the issues is, that due to how the filtering is currently setup there is no way to use the panel to show alerts from prometheus datasource which are not firing.
Also the same language (normal) is used in the Alert rules page despite as you said prometheus doesn't generate normal instances.

Imho  this both of these issues are bad for user experience.

**Comment by skywalkr** [comment] 2024-08-05 21:05
I agree with @jmichalek132 and would add that the norma\healthy state of Prometheus-based alerts is shown on the alert rules page. Would this get more traction if we put in a feature request?

**Comment by michelle-douglas** [comment] 2024-08-08 20:55
Hi Team, Submitting a feature request on behalf of my customer for this. Hoping to get it reviewed soon. Stay tuned.
