### ISSUE TITLE
Datasource variable using stale value

### ISSUE THREAD

**Issue by ajay-sainy** [grafana/grafana#51355] opened 2022-06-23 22:11 UTC
**What happened**: 
Dashboard using stale value of datasource type variable.

**What you expected to happen**:
Dashboard/panels to use the value displayed on the dropdown.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create 2 data sources of Prometheus type
2. Create new dashboard with 1 variable of datasource type and a panel that use the datasource variable.
3. Save the dashboard. Close it and reopen. It will use the previously selected datasource variable value for showing the chart in the panel.
4. Edit the panel and you will notice that the data source value in the query editor section is different that the one displayed in the variable dropdown. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser: Windows, Chrome
- Grafana plugins:
![Untitled](https://user-images.githubusercontent.com/12763412/175423746-a75c9d7a-8b41-4884-9180-94735e6f0b56.jpg)

- Others:

**Comment by autoric** [comment] 2022-06-24 19:31
I am also encountering this issue in grafana v9.

## Describe the problem

- I have a dashboard that is configured to use a datasource variable.
![Screen Shot 2022-06-03 at 11 29 17 AM](https://user-images.githubusercontent.com/918178/171902789-0f0239df-e02c-46a2-9e64-991e6f0d9e59.png)

- I add a new panel, I select `${datasource}` from the datasource dropdown.
- The panel is now configured to query the datasource _for the the current value of the  `datasource` variable_. 
![Screen Shot 2022-06-03 at 11 29 53 AM](https://user-images.githubusercontent.com/918178/171902819-0fe2ee81-4235-407e-89e0-2d6d8d8cc843.png)

- If I change the datasource variable, the query is still being executed against the original value of the datasource variable, not the new value. In this screenshot, the query is being evaluated against "Prometheus Global with LTS", not "Prometheus APAC", even though I changed the global datasource. 
![Screen Shot 2022-06-03 at 12 03 01 PM](https://user-images.githubusercontent.com/918178/171902924-a91b302b-48d8-45e9-bc30-1ac42020a3d5.png)


## Workaround

I can workaround this issue by:
- Configure the datasource, then deleting + adding a new query. It will now be correctly bound the `${datasource}` variable, rather than the current value of the variable.
- Repeat the above for each graph, or create each new panel by duplicating an existing one.
- See this video to understand the workaround

https://user-images.githubusercontent.com/918178/171915964-f63b3680-44f7-4f4f-8590-b7a42c454740.mov

**Comment by torkelo** [comment] 2022-06-27 09:46
Can you try selecting a datasource (of the same type) that is not a variable in the datasources drop down, then select the variable again in the variable dropdown.

The fix/bug was in what happens when you select the variable in the datasources drop down.

**Comment by taleena** [comment] 2022-07-12 17:44
@natellium this is coming up frequently on customer's end - have we recreated using the suggestion above?

**Comment by axelavargas** [comment] 2022-07-14 09:14
Hi all 👋🏾 , I did some research on this topic using Prometheus and Loki and noticed a couple of things:

- Since Grafana v9.0.2, the DataSource variable in the query editor is correctly bound to the {$datasource} variable set from the variable dropdown selector. Before it was bound to the value of the variable. I tested it and confirmed **that now the query is performed with the last value of the Datasource variable**.

Before 8.4.5 and Grafana v9.0.0  :
![IssueGrafana9 0 0](https://user-images.githubusercontent.com/239999/178939856-1d794b87-d3f2-4e5e-8dbc-40af36ec0306.png)

Since Grafana v9.0.2

https://user-images.githubusercontent.com/239999/178944913-6ac088a5-5df0-4de9-ba6d-739b57e7d812.mp4


### But...
I have found something that seems like a bug, the Query editor props are not being refreshed when I change the prop (in the case of Prometheus it did not refresh the metrics), see below 

https://user-images.githubusercontent.com/239999/178938974-1c9782a8-2f67-401e-ac8d-43c2b9d336ea.mp4

### In Resume
I believe the issue reported here is being fixed in Grafana v9.0.2

For the second issue, I am not sure if is already reported because I was testing 8.1.2 and the same behavior was present there. Maybe @grafana/observability-experience-squad knows something about this? 

Thank you 🤗

**Comment by Elfo404** [comment] 2022-07-14 09:29
@grafana/observability-metrics owns the Prometheus datasource (looping in also @grafana/observability-logs-and-traces as i can see the same behavior with Loki)

**Comment by axelavargas** [comment] 2022-07-19 06:48
Thanks, @gabor and @Elfo404 🙌🏾 for taking a look, I'm closing this issue as the issue is fixed in Grafana 9.0.2 and we have new issues for loki and prometheus.

**Closed by axelavargas** 2022-07-19 06:48 UTC
Labels: type/bug, area/dashboard/templating

**Comment by gabor** [comment] 2022-07-27 11:36
update: i did some work on the Loki side, and found that the info is already stale at some higher level "above" the Loki react component, so i created a new issue at https://github.com/grafana/grafana/issues/52737 , which will need to be handled first.
