### ISSUE TITLE
Keep the variables at the top when scrolling down

### ISSUE THREAD

**Issue by Daniel-Mompean** [grafana/grafana#27009] opened 2020-08-14 12:52 UTC
**What would you like to be added**: Keep the variables at the top when scrolling down

**Why is this needed**: this option would give a visibility of the filters, currently we have to move the scroll bar up and down to change the filter, or confirm what is in the filter

**Comment by sakjur** [comment] 2020-08-14 13:42
Duplicate of #12790

(or possibly #11042)

**Closed by sakjur** 2020-08-14 13:42 UTC
