### ISSUE TITLE
Wrong ordering a number field in json table panel 

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#6507] opened 2016-11-08 11:13 UTC
* **I'm submitting a ...**
- [* ] **Bug report**

Please include this information:
- What Grafana version are you using? **v3.1.1**
- What datasource are you using? **Elasticsearch 2**
- What OS are you running grafana on? **Centos 7**
- What did you do? **Created a table panel with "To Table Transform" as JSON data and selected "wQueryTime" as  a number field and attempted to order this descending. Set thresholds as 2,5,10 (See full config below)**
- What was the expected result? **Expected the data below to be ordered correctly and thresholds coloured**
- What happened instead? **Wrong order and no colours :(**

Here is the config and example:
![grafanaordering](https://cloud.githubusercontent.com/assets/12910496/20096979/2334f8e6-a5a4-11e6-9eb0-a591c6487ffd.PNG)

**Comment by torkelo** [comment] 2016-11-08 11:19
duplicate of https://github.com/grafana/grafana/issues/6262

**Comment by waqark3389** [comment] 2016-11-08 11:20
@torkelo Sorry, I did search but didn't find that. Should have seen it, apologies.

**Closed by torkelo** 2016-11-08 11:19 UTC
