### ISSUE TITLE
Query on threshold.

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#22689] opened 2020-03-10 15:22 UTC
**What would you like to be added**:
To be able to use the query result as a threshold of coloring
**Why is this needed**:
To dynamically set the thresholding.

**Comment by torkelo** [comment] 2020-03-10 15:29
duplicate of https://github.com/grafana/grafana/issues/159

**Closed by torkelo** 2020-03-10 15:29 UTC

**Comment by radimkohout** [comment] 2020-03-10 15:39
When it'll be done?
