### ISSUE TITLE
[Feature Request] Restore left/right time shift  arrows for relative time spans

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#13967] opened 2018-11-05 15:09 UTC
Grafava v.5.3.2 has lost the left / right arrows for shifting the time window in case a relative time span is selected. After installing the update to 5.3.2 I received a feedback from multiple end-users that they miss this functionality. Would you consider restoring these buttons in the next release?

**Comment by marefr** [comment] 2018-11-05 15:41
Duplicate of #13687

**Comment by marefr** [comment] 2018-11-05 15:41
See https://github.com/grafana/grafana/issues/13687#issuecomment-430150283

**Closed by marefr** 2018-11-05 15:41 UTC

**Comment by coussej** [comment] 2018-11-05 15:45
@marefr the issue that you mention is closed, however torkelo said that if more users want them back you would add them back. To support this, wouldn't it therefore not be logical to have a feature request issue that is not closed?

**Comment by marefr** [comment] 2018-11-05 15:49
@coussej That a feature request is closed per default doesn't mean we never reopen it. In this case I'll reopen it to for a while to let people upvote it. Thanks

**Comment by coussej** [comment] 2018-11-05 17:12
Ok, thanks!
