### ISSUE TITLE
Querying data: Allow per-query time overrides

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#18936] opened 2019-09-06 07:51 UTC
As discussed during front-end sync on Sep 5th, @kylebrandt suggested to add possibility to specify time overrides per query.

This feature needs to be detailed, but creating this issue to start the discussion.

cc @ryantxu @aocenas

**Comment by torkelo** [comment] 2019-09-06 08:09
duplicate of https://github.com/grafana/grafana/issues/7762

**Closed by torkelo** 2019-09-06 08:09 UTC
Labels: area/frontend, area/panel/data, priority/unscheduled, type/feature-request
