### ISSUE TITLE
Coudn't set the graph's title

### ISSUE THREAD

**Issue by nidzelska** [grafana/grafana#12565] opened 2018-07-10 19:02 UTC
What Grafana version are you using?
v5.1.3

What datasource are you using?
InfluxDB

What did you do?
I added 2 graphs in 1 Dashboard for channel monitoring. From DB it came with tags - name and group.
In title for every graphs in dashboard I used $name ( so every graph automatically got different names)
When I set up variable "group" (SHOW TAG VALUES WITH KEY = "group" WHERE "name" =~ /^$name$/) it showed me the right result(in Preview of values) , but after using it in the graph's title like: $name - $group - all of graphs got the same group's tag, but different names.

What was the expected result?
In graph's title channel with different names get different groups

What happened instead?
All of graphs got the same group's tag, but different names.
![screenshot from 2018-07-10 21-32-08](https://user-images.githubusercontent.com/39418013/42531524-dcb94fd8-848c-11e8-8531-24a818d005bf.png)
![screenshot from 2018-07-10 21-31-08](https://user-images.githubusercontent.com/39418013/42531525-dced1728-848c-11e8-9c3c-bd8e0e94cb10.png)
![screenshot from 2018-07-10 21-27-29](https://user-images.githubusercontent.com/39418013/42531526-dd0ad600-848c-11e8-91e8-2f5cb903fda2.png)

So, as you see at the picture - there are different names of channels, but the same values of group.
How can I make it work?
[test.txt](https://github.com/grafana/grafana/files/2181789/test.txt)

**Comment by DanCech** [comment] 2018-07-10 19:17
Duplicate of #12559, please don't open multiple issues for the same thing.

**Closed by DanCech** 2018-07-10 19:17 UTC
