### ISSUE TITLE
changing display interval disables auto-refresh

### ISSUE THREAD

**Issue by HerrBerg** [grafana/grafana#2042] opened 2015-05-22 09:45 UTC
changing the time interval displayed, disables a auto-refresh interval which was set before
steps to reproduce:
- select auto-refresh interval
- change time interval
now the auto-refresh is disabled

this behavior started with version 2.1

**Comment by torkelo** [comment] 2015-05-25 08:14
Cannot replicate in latest master. What commit is your version of 2.1-pre1 ?

**Comment by torkelo** [comment] 2015-05-25 08:16
Tested in Chrome and Firefox (linux)

**Comment by HerrBerg** [comment] 2015-05-26 14:10
Ok, I tested again and it seems I missed one precondition:
In the settings of the dashboard the timepicker "until now-" option needs to be configured to eg. "10s"
After that setting I can see this behavior with chromium and firefox (linux)

I'm using the debian package (grafana_2.1.0-pre1_amd64.deb) build on 5/21/2015, 9:25:22 AM
from http://grafana.org/download/builds

**Comment by torkelo** [comment] 2015-05-26 14:49
@HerrBerg thanks for spotting the fact that you had now delay configured, that was the cause! Fixed in master now!

**Closed** 2015-05-26 14:48 UTC
Labels: bug
