### ISSUE TITLE
Loki logs not loading past ~5 minutes

### ISSUE THREAD

**Issue by christopher-wong** [grafana/grafana#21706] opened 2020-01-24 06:03 UTC
**What happened**:
When using Explore to query Loki, the chart doesn't render logs that are older than ~5 minutes. 

As you can see from the logs bar chart in the screenshot, only 5 minutes of logs appear. If I spam the refresh button, or enable auto-refresh, I can watch as the logs from 5 minutes ago disappear as new logs come in. The first green bar gets smaller, the last green bar grows.

This application has been running for hours and has thousands of log lines. When I use `logcli` I can dump all the logs successfully from Loki. 

**What you expected to happen**:
I should be able to see all the logs for a given timeframe.

**How to reproduce it (as minimally and precisely as possible)**:
Query for logs for an application

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version: Loki v1.3.0
- OS Grafana is installed on: AWS EKS
- User OS & Browser: macOS 10.15.2 / Safari 13.0.4
- Grafana plugins: n/a
- Others: Loki and Prometheus both have persistence enabled.

<img width="1792" alt="Screen Shot 2020-01-23 at 9 44 11 PM" src="https://user-images.githubusercontent.com/10580086/73047872-1f219880-3e2c-11ea-9e0b-1dc60d07998c.png">

**Comment by negbie** [comment] 2020-01-24 10:28
This is because you've reached your row limit of 1000.

**Comment by aocenas** [comment] 2020-01-24 10:50
This is duplicate of this other issue https://github.com/grafana/grafana/issues/21576. This is known and we have it in our roadmap.

**Closed by aocenas** 2020-01-24 10:50 UTC
Labels: area/explore, datasource/Loki, type/bug

**Comment by HristoA** [comment] 2020-12-09 08:48
https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/pull/805#issuecomment-741626700

**Comment by HristoA** [comment] 2020-12-09 08:59
Hi. 
You can go to `Data source->Loki` and  set `Maximum lines` to 5000 lines (this can't be overwrites from Grafana Explorer `Line limit` field). Keep in mind that if you set to high or unlimited value this can lead Loki to crash if you have too much logs in selected time frame.
