### ISSUE TITLE
Grafana panel description going out of screen

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#68564] opened 2023-05-16 15:24 UTC
### 
# What went wrong?

the panel description/popover text is going out of the screen sometimes.

For the first time after the dashboard is loaded the description is coming below the info icon and everything is visible as shown below.

![https://global.discourse-cdn.com/grafana/optimized/3X/0/1/0145a1694df1b7c374e4d5cfe82548a2120c36b8_2_690x325.png](https://global.discourse-cdn.com/grafana/optimized/3X/0/1/0145a1694df1b7c374e4d5cfe82548a2120c36b8_2_690x325.png)

But after that if we hover over the info icon, the text is coming above the icon and some part of it is going out of the screen as given below.

![https://global.discourse-cdn.com/grafana/optimized/3X/5/b/5b47fc5862159516b81a83b92bd3844cfa87fc79_2_690x332.png](https://global.discourse-cdn.com/grafana/optimized/3X/5/b/5b47fc5862159516b81a83b92bd3844cfa87fc79_2_690x332.png)

### 
# How do we reproduce it?

Steps to reproduce:

1. Edit the “What’s New” panel to add a description.
2. Use the following for the description:

This is a description to test that description go off the page after the first time that you click on them. This description is long enough that it needs several lines of text. The quick brown fox jumped over the lazy dog.

3. Save the panel edits
4. Hover over the “i” on the What’s New panel and see that the description is visible
5. Move mouse away to another panel, for example, hover over and inspect data on the Server Requests panel.

Hover over the “i” of the What’s New panel and see that the description box is now to the right of the screen and portions of it are not visible.

### 
# What Grafana version are you using?

v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's Browser?

Any - But mostly use Chrome

### Is this a Regression?

None

### Are Datasources involved?

No

### Anything else to add?

Originially reported on the community forum ([link](https://community.grafana.com/t/grafana-panel-description-going-out-of-screen/81882))

**Comment by axelavargas** [comment] 2023-05-17 07:48
Hey @usmangt 😄, this is a duplicate of https://github.com/grafana/grafana/issues/63372

**Closed by axelavargas** 2023-05-17 07:48 UTC
Labels: type/bug, area/panel/edit

**Comment by YellowDog3629** [comment] 2023-05-17 12:03
#63372 is Closed -- wouldn't that indicate that the issue is fixed ? (which it is not fixed and occurs in 9.5.2)
