### ISSUE TITLE
Alert-List: Link to dashboard/panel doesnt work with different root_:

### ISSUE THREAD

**Issue by tobiasmohr** [grafana/grafana#85238] opened 2024-03-27 10:15 UTC
### What happened?

![image](https://github.com/grafana/grafana/assets/130752200/7b97719d-847e-4aa0-99ab-dd02e3213075)
Here you can see the alarm with the associated dashboard. My base path is /graphs, but the link goes to http://ip/d/a00468c2-91e9-47a4-98de-969235a68196

### What did you expect to happen?

Link is navigating to http://ip/graphs/d/a00468c2-91e9-47a4-98de-969235a6819)

### Did this work before?

I only tested this with a very old version (7.x.x)

### How do we reproduce it?

1. Setup grafana with a different root_url and serve from sub path
2. Create a alert with a dashboard link
3. Click on the alert link

### Environment (with versions)?

Grafana: 10.3.3
OS: debian arm64
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by gillesdemey** [comment] 2024-03-27 13:30
Hi! This seems to be fixed in the latest 10.4.x release where I can no longer reproduce this – whereas I was able to reproduce on 10.3.3.

**Comment by JohnnyQQQQ** [comment] 2024-05-22 09:28
This seems to be fixed, feel free to re-open if not.

**Closed by JohnnyQQQQ** 2024-05-22 09:28 UTC
Labels: type/bug, area/alerting, needs investigation, triage/needs-confirmation
