### ISSUE TITLE
[Feature request] Alert list panel more filter options

### ISSUE THREAD

**Issue by amuranka** [grafana/grafana#7764] opened 2017-03-08 10:56 UTC
Using latest stable grafana (4.1.2) it would be very nice to have more filter options for the alert list panel. For example using tags for alert panels and filter for them in the alert list panel.
At least it should be possible to filter by notifications (the recipients).

TY

**Comment by daniellee** [comment] 2017-03-08 11:32
Dupe of #6552

**Closed by daniellee** 2017-03-08 11:32 UTC
Labels: comp: panel/alertlist, type: duplicate

**Comment by amuranka** [comment] 2017-03-08 12:35
my bad! thx
