### ISSUE TITLE
Tag Search doesn't cover all dashboards

### ISSUE THREAD

**Issue by Chirico** [grafana/grafana#4661] opened 2016-04-12 08:57 UTC
When I click on the search bar without entering a query, the result list doesn't show all dashboards but only the first few hundred which is ok so far. But when I now select a tag to filter results without entering a query, the tag filtering is done only on the dashboards that were displayed before. I would expect that selecting a tag leads to a search over all dashboards when no search query is entered.

**Comment by jamesuber** [comment] 2016-04-18 20:10
+1

**Comment by samhatchett** [comment] 2016-04-18 20:19
+1 -- the `/api/search` endpoint is probably to blame? this does not give the complete list.

**Comment by samhatchett** [comment] 2016-05-23 14:27
to clarify the repercussions of this issue: currently the API is not able to reliably get the full list of dashboards, if the number of dashboards is large. So doing something like deleting all dashboards via the API and re-building them requires iteratively checking the `search` endpoint and removing the dashboards returned, until that call returns an empty list.

**Comment by kicmuc** [comment] 2016-06-03 16:15
+1

I have tagged tashboards which are definitely not showing up when looking for the tags and also not when printing out the complete list via API. They are opening fine in the GUI though. We have more than 1000 boards.

**Comment by idanz** [comment] 2016-12-19 06:25
+1

I know why this is happening though, there is a hardcoded limit of 1000 in sqlstore/dashboard.go that is applied before filtering on the tag (which is done in application).
so if you have more than 1000 dashboard/tag combinations in your organization you will have missing results before you even get to apply the tag filter.

The proper solution would be to propagate the tag filter into the sql query itself.

A "fast" solution is to change the limit 1000 to something much bigger and recompile..

**Comment by llelle** [comment] 2017-01-19 14:46
+1

**Comment by luke-powers** [comment] 2017-01-24 01:05
+1 Same issue @samhatchett found in that api/search doesn't return all results for >1000 dashboards. This is for 3.1.1. Personally haven't been able to test on 4.0 yet

**Comment by iksaif** [comment] 2017-02-14 11:01
This seems to be a duplicate of https://github.com/grafana/grafana/issues/3623

**Comment by shalstea** [comment] 2017-11-27 14:58
+1

**Comment by shalstea** [comment] 2017-12-14 15:48
Can this be merged into 4.6.4 and 5.0 alpha ?

**Comment by torkelo** [comment] 2018-07-03 18:38
this should not be an issue any more (after v5)

**Closed by torkelo** 2018-07-03 18:38 UTC
Labels: P3: important, comp: search, help wanted
