### ISSUE TITLE
Loki: Sorting logs based on "Oldest first" only works on 1000 entries shown in the window

### ISSUE THREAD

**Issue by hsiehp** [grafana/grafana#80318] opened 2024-01-10 19:39 UTC
### What happened?

After ingesting the logs into Loki successfully, there is a limit of 1000 lines when trying to look at those logs in Explore page on Grafana GUI. The default display option is "Newest first" so only first 1000 lines from latest line are shown.

When sorting those logs using "Oldest first" option, it only sorts the those 1000 entries.

### What did you expect to happen?

When "Oldest first" option is chose, it should start from the beginning of the time period specified, and show the oldest logs from the duration first, before hitting the 1000 lines limit.

### Did this work before?

No

### How do we reproduce it?

1. Ingest more than 1000 lines of code into Loki
2. Open up the logs in Explore page on Grafana GUI for the time when logs are ingested
3. Click on the "Oldest first" option next to "Display results"

### Environment (with versions)?

Grafana: v10.1.5
OS: Linux
Browser: Safari

### Grafana platform?

None

### Datasource(s)?

Loki

**Comment by svennergr** [comment] 2024-01-17 16:08
Closing this as a duplicate of https://github.com/grafana/grafana/issues/78588

**Closed by svennergr** 2024-01-17 16:08 UTC
