### ISSUE TITLE
Relative time field doesn't honor dashboard timezone

### ISSUE THREAD

**Issue by infertux** [grafana/grafana#61901] opened 2023-01-23 01:40 UTC
**What happened**:

The *Relative time* field in a panel's *Query options* does not use the timezone set for the dashboard.

**What you expected to happen**:

Use the dashboard timezone.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set a dashboard timezone to UTC+2
2. Set computer timezone to UTC+0
3. Set panel *Relative time* field to `now/d` i.e. "Today so far"
4. Open *Query inspector* - the panel will use UTC+0 instead of UTC+2 in the `from` parameter

**Environment**:
- Grafana version: Latest
- Data source type & version: Prometheus
- OS Grafana is installed on: Cloud instance

**Comment by torkelo** [comment] 2023-01-23 07:30
duplicate of https://github.com/grafana/grafana/issues/59665

**Closed by torkelo** 2023-01-23 07:30 UTC
