### ISSUE TITLE
Unable to provision folders with default permissions in 10.2

### ISSUE THREAD

**Issue by piotrborowka-dnv** [grafana/grafana#78060] opened 2023-11-13 15:04 UTC
### What happened?

 In 10.2 it's impossible to provision folders with default permissions for Admin, Editor and Viewer. All folders got default permissions only for Admin.

It is also connected with #77334 and #77688 .

### What did you expect to happen?

Folders are created with permissions for Admin, Editor and Viewer.

### Did this work before?

Yes, before the root folder update, everything was working properly.

### How do we reproduce it?

1. Use 10.2 Grafana docker image.
2. Provision example dashboard to the root folder or folder newly created from the files structure.
3. Check dashboards/folders default permissions.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.2.0 (895fbafb7a)
OS: Docker Engine v24.0.7

### Grafana platform?

Docker

**Comment by hoelzro** [comment] 2023-11-14 16:42
And here's my script and supporting files: https://gist.github.com/hoelzro/bdff74120c43828a21645267d3577ebe

**Comment by mildwonkey** [comment] 2023-11-15 14:23
Hi @hoelzro , thanks for reporting this and sorry for the bad behavior. And thanks for the supporting info, I appreciate it! 

I need a bit more to reproduce the issue you are seeing, however. Can you provide your configuration (removing any sensitive data first) and any other information we might need to reproduce it? 

I'm also going to tag the @grafana/identity-access-team, as they are the experts in our RBAC permissions.

**Comment by kalleep** [comment] 2023-11-15 15:01
Hey, we are aware of the issue and a fix has already been merged and backported and is included in  10.2.1 https://github.com/grafana/grafana/pull/77155

**Comment by mildwonkey** [comment] 2023-11-15 15:49
thanks @kalleep ! I'll close this issue, since there's a confirmed fix. @hoelzro , this will be fixed once you are able to upgrade to the 10.2.1 release. Thanks, and sorry again for the bad behavior!

**Closed by mildwonkey** 2023-11-15 15:49 UTC
Labels: area/backend, area/provisioning, triage/needs-confirmation
