### ISSUE TITLE
Support configuring separate read/write endpoints for database

### ISSUE THREAD

**Issue by stuartnelson3** [grafana/grafana#16517] opened 2019-04-11 12:40 UTC
**What would you like to be added**: Support for setting `read_url` and `write_url` in the database config section, instead of a single `url` (https://grafana.com/docs/installation/configuration/#url)

**Why is this needed**: We would like to make our grafana service available across multiple datacenters, with grafana instances reading from a database replica in their local datacenter, but writing to a centralized point (which then replicates the data out). In the event of an incident that brings down the primary datacenter, we want to be able to use a grafana instance in a separate dc in a read-only mode, without having to reconfigure the running instance.

**Comment by daniellee** [comment] 2019-04-11 13:28
Ref #13399
Ref #3676

Is this a dupe of the above issue? It sounds like something a proxy should handle.

**Comment by bergquist** [comment] 2019-04-11 13:37
closing this since its a dupe.

**Closed by bergquist** 2019-04-11 13:37 UTC
Labels: area/backend/db, type/feature-request
