### ISSUE TITLE
Streaming channel error: Subscription to the channel already exists

### ISSUE THREAD

**Issue by limecat-ss** [grafana/grafana#60570] opened 2022-12-20 13:07 UTC
**What happened**:

When I use Stream metrics from Telegraf to Grafana I get the error: 'Streaming channel error: Subscription to the channel already exists'. And this usually happens when I use the playlist in kiosk mode

**How to reproduce it (as minimally and precisely as possible)**:

Following this tutorial: https://grafana.com/tutorials/stream-metrics-from-telegraf-to-grafana/

**Anything else we need to know?**:

When I refresh the page the error disappears, but when I use playlist the error happens again

- Grafana version: 9.3.2
- Telegraf Version : 1.25

Error image:

![grafana_error](https://user-images.githubusercontent.com/103083073/208676209-d4a7c19c-0c8c-4cc6-9403-99d5d1f25f24.png)

**Comment by usmangt** [comment] 2022-12-23 16:56
Hi @limecat-ss,

Thanks for opening this issue.

I have tried to reproduce it and yes this error also occurred for me as well. But in my case, I was getting 2 listings of 
`stream/custom_stream_id/cpu`

When I tried the very 1st time and it seems to be working fine for both till I save the Dashboard with the 2nd one. Then went back want to save the 1st one too and then get the same error.

I then restarted the Telegraf service and then in the UI I only see a single listing of `stream/custom_stream_id/cpu` when selecting from the Live measurement channel. (this can be considered as a **workaround**)

So, this seems to be not a Grafana issue but a Telegraf glitch (or a bug) and better to ask in their [community](https://community.influxdata.com/c/ts-collect/6).

I will now close this issue.

**Comment by limecat-ss** [comment] 2022-12-29 12:29
Hi,

I am getting the same type of error using the mqtt plugin. Doesn't this suggest that the problem is with Grafana?

**Comment by fredlcore** [comment] 2023-01-01 00:51
Same here with the MQTT plugin of Grafana. Sometimes I manage to get data plotted, but as soon as I make some changes in the panel and hit "apply", the error comes up even though I haven't changed anything regarding the topic.

**Comment by tankienleong** [comment] 2023-01-04 01:47
I also faced the same error with the MQTT plugin of Grafana

**Comment by powersj** [comment] 2023-01-04 23:36
Hi @usmangt, 

Telegraf maintainer here

Based on that error message from the Grafana UI, how does that indicate an issue with telegraf? Are you aware of something telegraf should be doing differently?

Not sure where to go with this one :)

**Comment by jim0020** [comment] 2023-01-07 04:22
Same issue here with grafana/mqtt-datasource

**Comment by jon-p-taylor** [comment] 2023-01-07 19:26
I am having the same issue without Telegraf being involved at all. Just a simple MQTT connection from Grafana to a HiveMQ broker. This looks a lot more like a Grafana issue than anything else. This has been closed prematurely by the looks of it.

**Comment by sbrooke** [comment] 2023-01-07 19:56
Adding to the chorus. I'm using MQTTBox to send a simple publish message into Mosquitto running in a Docker on Unraid. The Grafana MQTT plugin works fine the first time you add the "topic" to the dashboard in the edit screen. I can publish messages multiple times without issue, and the graph is updated. Once I make any change, such as Apply/Save it breaks it and I have no visualized data. After some time I also get the error message about already being subscribed to the channel. This is almost certainly a problem with the Grafana MQTT plugin.

**Comment by usmangt** [comment] 2023-01-09 12:54
Hi @powersj and others

Thanks for commenting here :slightly_smiling_face:  I did not find any error in the logs and then this issue did not occur again on my test machine so my best guess was that it could be a glitch on the telegraf side.

But as many other users are reporting it (for other datasources) so I will try to get our team to get it investigated.

**Comment by usmangt** [comment] 2023-01-09 12:58
Although the issues seem to be related with the Streaming data so added the "Multitenancy" project but there might be a chance of it related to the Dashboard so added it as well.

**Comment by jon-p-taylor** [comment] 2023-01-09 14:34
> Hi @powersj and others
> 
> Thanks for commenting here 🙂 I did not find any error in the logs and then this issue did not occur again on my test machine so my best guess was that it could be a glitch on the telegraf side.
> 
> But as many other users are reporting it (for other datasources) so I will try to get our team to get it investigated.

I still don;t understand why you are linking this to telegraf. There is no telegraf instance associated with the issue I have reported.

**Comment by usmangt** [comment] 2023-01-09 14:39
@jon-p-taylor 

No, I am not linking to telegraf or even with MQTT. It is now clear that it has something to do with the streaming and therefore asked the team to have a look.

I hope this remove any confusion :)

**Comment by limecat-ss** [comment] 2023-01-09 16:26
> I still don;t understand why you are linking this to telegraf. There is no telegraf instance associated with the issue I have reported.

I noticed this problem initially using realtime streaming with Telegraf. Then I saw that the same thing happened with grafana's mqtt datasource.

**Comment by OlivierGre** [comment] 2023-01-12 09:04
I'm also facing the same "MQTT Streaming channel error: Subscription to the channel already exists". Yesterday I have opened a ticket on grafana/mqtt-datasource: https://github.com/grafana/mqtt-datasource/issues/64

I have used an MQTT Client on an Android phone and I don't have such problem. It does received the MQTT notifications.

**Closed** 2023-01-12 17:55 UTC
Labels: needs investigation, area/panel/data, area/streaming

**Comment by ArturWierzbicki** [comment] 2023-01-12 20:44
Hey everyone - thanks for reporting this issue. [The fix](https://github.com/grafana/grafana/pull/61406) will land in the next minor version of Grafana (9.3.4/9.2.10); the release is currently scheduled for 24th of Jan

**Comment by OlivierGre** [comment] 2023-01-23 09:34
> Hey everyone - thanks for reporting this issue. [The fix](https://github.com/grafana/grafana/pull/61406) will land in the next minor version of Grafana (9.3.4/9.2.10); the release is currently scheduled for 24th of Jan

Hello Artur,
Is the release containing the fix still planned for the 24th of January?
Thanks for this info.

**Comment by EricZeiberg** [comment] 2023-01-24 18:40
^ Seconding this question. Is the release with the bug fix still planned for the 24th?

**Comment by OlivierGre** [comment] 2023-01-25 08:59
Any chance to see the release today?

**Comment by OlivierGre** [comment] 2023-01-26 13:08
I can see that the version 9.3.5 of Grafana is available on Grafana Cloud. I don't see anymore the error 'Streaming channel error: Subscription to the channel already exists' but for the moment I don't succeed to get MQTT data.

**Comment by bmedici** [comment] 2023-01-29 18:02
Same error, trying to upgrade to 9.3.4, thanks !
