### ISSUE TITLE
Alert name and tags have limit but give 500 error

### ISSUE THREAD

**Issue by ppeter10** [grafana/grafana#34541] opened 2021-05-21 07:59 UTC
**What happened**:
Trying to create/update dashboard through terraform and got 500 error. 
```
module.test.grafana_dashboard.alert: Modifying... [id=alert-for-all-apps-overview]
╷
│ Error: status: 500, body: {"message":"Failed to save dashboard"}
│ 
│   on pagerduty/modules/grafana_dashboard/dashboard.tf line 174, in resource "grafana_dashboard" "alert":
│  174: resource "grafana_dashboard" "alert" {
│ 
╵
```
The dashboard was updated but alerts were not working.
Resaving in dashboard gives "Failed to save dashbord" in a red box on the top right.

**What you expected to happen**:
To save the dashboard properly with working alerts.

**How to reproduce it (as minimally and precisely as possible)**:
had a notification tag that had a value of 658 chars 
and/or
have an alert name with 658+ chars.

When the var was limited to 100 chars it worked

**Anything else we need to know?**:

500 is not a good error message and I couldn't find any reference to a limit for the name or tags.
Please allow unlimited or put proper errors both for API and web interface.

**Environment**:
- Grafana version: Grafana v7.5.5 (b5190ee547)
- OS Grafana is installed on: Linux (docker)

**Comment by Elfo404** [comment] 2021-05-28 15:11
Looping in @grafana/backend-platform

**Comment by marefr** [comment] 2021-05-31 08:53
Duplicate of #22853

**Closed by marefr** 2021-05-31 08:53 UTC
Labels: area/alerting, area/provisioning
