### ISSUE TITLE
how can i customize theme(UI components) in latest verssion of grafana   

### ISSUE THREAD

**Issue by jawadbiag8** [grafana/grafana#36425] opened 2021-07-05 08:29 UTC
**What would you like to be added**:
I want to customize the front end of grafana by using my custom style(css) and I don't want to use boom theme plugin because it shows a panel on dashboard which I don't want to see so if there is any way possible to add my own style sheet code in grafana code base  or is there any plugin available to customize  GUI of grafana 
**Why is this needed**:
to make my dashboard according to my web applications

**Comment by Elfo404** [comment] 2021-07-05 12:13
Hi @jawadbiag8 custom themes are not supported.

Closing this also as duplicate of https://github.com/grafana/grafana/issues/19106

**Closed by Elfo404** 2021-07-05 12:13 UTC
