### ISSUE TITLE
Alerting: Notifications are sent to the wrong contact point with nested policies

### ISSUE THREAD

**Issue by gtirloni** [grafana/grafana#75307] opened 2023-09-22 16:06 UTC
### What happened?

A child policy `A` from the default notification policy does not define a contact point and thus inherits it from the default notification policy:

![image](https://github.com/grafana/grafana/assets/5902830/813a984b-7dcd-4c18-96a8-5cbb70716891)

![image](https://github.com/grafana/grafana/assets/5902830/c9ab4fa0-0b2f-4e57-8f83-4ef1331bd282)

The children of policy `A` do define selectors and contact points accordingly:

![image](https://github.com/grafana/grafana/assets/5902830/8b4631f5-41f3-4b25-8467-8376a99d5d93)

An alert that match of of the children correctly shows the expected policy in `Preview routing`:

![image](https://github.com/grafana/grafana/assets/5902830/23cede75-172b-43f5-abfc-2927b6d81cfd)

However, notifications are still sent to the contact point default in the default notification policy.

The same contact point is used in other notification policies and delivers messages to the right place so we assume it's properly configured (it's not easy/possible to access a secured field).

### What did you expect to happen?

Because the contact point (receiver) defined by a notification policy that matched the alert (a child of `A`), we expected that the receiver from the default notification policy would be overridden and the only from the child policy uses.

### Did this work before?

We did not have this nested notification policies before.

### How do we reproduce it?

1. Configure a receiver `R1` in the default notification policy
2. Create a child policy `A` that matches `foo = bar` label and do not define a receiver
3. Create a child policy `X` under `A` that matches `x = y` label and defines a receiver `R2`
4. Create an alert with labels `foo = bar` and `x = y`
5. Confirm in `Preview Routing` that policy `X` is used.
6. Cause the alert to trigger and send a notification
7. Confirm if the notification was sent to receiver `R1` or `R2`

### Environment (with versions)?

Grafana: 10.1.0

### Grafana platform?

None

**Comment by tonypowa** [comment] 2023-09-26 13:00
hi @gtirloni 
thanks for the issue

is this option enabled in your child policy A?

![image](https://github.com/grafana/grafana/assets/45235678/481a7477-00e6-436f-a788-80b03b13cdbf)

If the Continue matching subsequent sibling nodes option is enabled for a nested policy, then evaluation continues even after one or more matches. A parent policy’s configuration settings and contact point information govern the behavior of an alert that does not match any of the nested policies. A default policy governs any alert that does not match a nested policy.

https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-notification-policy/#configure-notification-policies

**Comment by gtirloni** [comment] 2023-10-25 10:51
> is this option enabled in your child policy A?

No. It's disabled because once policy A matches, we do not want it to check sibling nodes, only to descend into that branch of the tree.

The issue is that preview routing shows the expected contact point and we are happy with that, but the actual routing is different.

**Comment by tonypowa** [comment] 2023-10-25 14:22
many thanks for the info @gtirloni 
I have added the issue to the alerting team's board for review

**Comment by armandgrillet** [comment] 2023-11-02 16:11
Was it an Error or No Data alert? Keep in mind that Error and No Data alerts have different labels and could thus be routed differently. A screenshot of the alert rule would be useful to debug as well.

**Comment by DohanKim** [comment] 2024-01-09 09:15
![Uploading Screenshot 2024-01-09 at 5.36.35 PM.png…]()

I have a similar issue.
Even though an alert is recognized as "message =~ .*:closed.*" and shows "1 instances" on the policy,
notification is being sent to "slack-alerts" instead of "slack-warnings" which is the parent's policy, not the children's.

**Comment by tonypowa** [comment] 2024-01-09 09:59
@DohanKim 

it looks like the alert rule label `log-error` is matching the label of your parent policy, which routes to 'slack-alerts'. Since this is a match, the routing stops here and does not look into the nested policies (your 'slack-warnings' policies)

Could you check your alert rule labels, and confirm with the routing preview tool located at the bottom of the alert rule editor ?

**Comment by DohanKim** [comment] 2024-01-09 15:34
@tonypowa 
Grafana document 
https://grafana.com/docs/grafana/latest/alerting/fundamentals/notification-policies/notifications/#routing
says that 

> If a notification policy has label matchers that match the labels of the alert instance, it will descend into its child policies and, if there are any, will continue to look for any child policies that might have label matchers that further narrow down the set of labels, and so forth until no more child policies have been found.
![image](https://github.com/grafana/grafana/assets/6930365/3b745f0f-d295-496b-9ab0-5b09e25b1652)


It is why we have a "tree structure" anyway. If a match stops routing to the children, having a tree structure is meaningless.

and you can see in the screenshot I uploaded that parent (name=logs-error) shows "0 instances" matching,
though the child (message=.*:closed.*) shows "1 instances" matching.
According to the document, it's supposed to notify slack-warnings.

**Comment by tonypowa** [comment] 2024-01-10 13:18
apologies @DohanKim , you are right. The tree structure logic should route your notifications to slack-warnings.

could you provide the following please ?:

>Was it an Error or No Data alert? Keep in mind that Error and No Data alerts have different labels and could thus be routed differently. A screenshot of the alert rule would be useful to debug as well.

**Comment by DohanKim** [comment] 2024-01-11 11:12
@tonypowa 
it's alerting (error), not No Data

![Uploading Screenshot 2024-01-11 at 8.11.20 PM.png…]()

**Comment by armandgrillet** [comment] 2024-01-11 16:34
Could you please export a minimal example of the routing tree and alert rule showing this issue and share it here? This could be a visualization problem and they are hard to debug.

**Comment by DohanKim** [comment] 2024-01-12 05:54
@armandgrillet 

```
{
  "template_files": {},
  "template_file_provenances": {},
  "alertmanager_config": {
    "route": {
      "receiver": "grafana-default-email",
      "group_by": [
        "grafana_folder",
      ],
      "routes": [
        {
          "receiver": "slack-alerts",
          "object_matchers": [
            [
              "name",
              "=",
              "error"
            ]
          ],
          "routes": [
            {
              "receiver": "slack-warnings",
              "object_matchers": [
                [
                  "message",
                  "=~",
                  ".*:closed.*"
                ]
              ]
            },
            {
              "receiver": "slack-warnings",
              "object_matchers": [
                [
                  "message",
                  "=~",
                  ".*:timeout.*"
                ]
              ]
            }
          ]
        }
      ],
      "group_interval": "5m"
    },
    "templates": null,
    "receivers": [
      {
        "name": "grafana-default-email",
        "grafana_managed_receiver_configs": [
          {
            "uid": "aa5effe5-19c5-448b-9ef3-2a91bd909669",
            "name": "email receiver",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "<example@email.com>"
            },
            "secureFields": {}
          }
        ]
      },
      {
        "name": "slack-alerts",
        "grafana_managed_receiver_configs": [
          {
            "uid": "fc005190-9b50-4b83-ab45-2023d8274adb",
            "name": "slack-alerts",
            "type": "slack",
            "disableResolveMessage": false,
            "settings": {},
            "secureFields": {
              "url": true
            }
          }
        ]
      },
      {
        "name": "slack-warnings",
        "grafana_managed_receiver_configs": [
          {
            "uid": "eb811ba5-c9cd-477e-88c3-bb955195fbb6",
            "name": "slack-warnings",
            "type": "slack",
            "disableResolveMessage": false,
            "settings": {},
            "secureFields": {
              "url": true
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by lafrech** [comment] 2024-01-16 11:37
Hi. I'm facing a similar issue with a nested policy not being applied. The routing preview in the route does indicate that (thanks to the labels) the alert matches the nested policy, but the notification goes to the default policy's contact point anyway.

I don't think this is a visualization issue, as the rule routing preview is in line with our expectations. What is wrong is the outcome : the notification being sent to the contact point associated with the default policy.

Grafana v10.2.3

**Comment by armandgrillet** [comment] 2024-01-17 10:59
We are unable to reproduce it in main with this config:

```
{
  "template_files": {},
  "template_file_provenances": {},
  "alertmanager_config": {
    "route": {
      "receiver": "grafana-default-email",
      "group_by": [
        "grafana_folder",
        "alertname"
      ],
      "routes": [
        {
          "receiver": "email2",
          "object_matchers": [
            [
              "name",
              "=",
              "logs-error"
            ]
          ],
          "routes": [
            {
              "receiver": "email3",
              "object_matchers": [
                [
                  "message",
                  "=~",
                  ".*:closed.*"
                ]
              ]
            }
          ]
        }
      ]
    },
    "templates": [],
    "receivers": [
      {
        "name": "grafana-default-email",
        "grafana_managed_receiver_configs": [
          {
            "uid": "b4817d01-57ee-42fa-a2f8-d4f6518bd689",
            "name": "grafana-default-email",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "test@example.com",
              "singleEmail": false
            },
            "secureFields": {}
          }
        ]
      },
      {
        "name": "email2",
        "grafana_managed_receiver_configs": [
          {
            "uid": "d0557a17-7cfc-4ad7-a13a-c93d5b642715",
            "name": "email2",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "test2@grafana.com",
              "singleEmail": false
            },
            "secureFields": {}
          }
        ]
      },
      {
        "name": "email3",
        "grafana_managed_receiver_configs": [
          {
            "uid": "a88c4cc4-1e5e-4602-af87-462f39ee38ae",
            "name": "email3",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "test3@grafana.com",
              "singleEmail": false
            },
            "secureFields": {}
          }
        ]
      }
    ]
  }
}
```

And this alert rule (we faked the message for easier testing):

```
{
    "apiVersion": 1,
    "groups": [
        {
            "orgId": 1,
            "name": "Test Group",
            "folder": "Test Folder",
            "interval": "1m",
            "rules": [
                {
                    "uid": "bdc6546f-8241-4015-8230-9b5c3e591335",
                    "title": "Test",
                    "condition": "B",
                    "data": [
                        {
                            "refId": "A",
                            "relativeTimeRange": {
                                "from": 600,
                                "to": 0
                            },
                            "datasourceUid": "grafanacloud-prom",
                            "model": {
                                "editorMode": "code",
                                "expr": "1",
                                "instant": true,
                                "intervalMs": 1000,
                                "legendFormat": "__auto",
                                "maxDataPoints": 43200,
                                "range": false,
                                "refId": "A"
                            }
                        },
                        {
                            "refId": "B",
                            "relativeTimeRange": {
                                "from": 600,
                                "to": 0
                            },
                            "datasourceUid": "__expr__",
                            "model": {
                                "conditions": [
                                    {
                                        "evaluator": {
                                            "params": [],
                                            "type": "gt"
                                        },
                                        "operator": {
                                            "type": "and"
                                        },
                                        "query": {
                                            "params": [
                                                "B"
                                            ]
                                        },
                                        "reducer": {
                                            "params": [],
                                            "type": "last"
                                        },
                                        "type": "query"
                                    }
                                ],
                                "datasource": {
                                    "type": "__expr__",
                                    "uid": "__expr__"
                                },
                                "expression": "A",
                                "intervalMs": 1000,
                                "maxDataPoints": 43200,
                                "reducer": "last",
                                "refId": "B",
                                "type": "reduce"
                            }
                        }
                    ],
                    "noDataState": "NoData",
                    "execErrState": "Error",
                    "for": "0s",
                    "annotations": {},
                    "labels": {
                        "message": "{% error: %HTTP.Error{reason: :closed, id:nil}}",
                        "name": "logs-error"
                    },
                    "isPaused": false
                }
            ]
        }
    ]
}
```

**Comment by lafrech** [comment] 2024-01-17 14:50
Here's my config, trimmed down to what should be relevant. I assume other parallel notification policies, rules and stuff in other organizations don't interfere.

```json
{
    "template_files": {},
    "alertmanager_config": {
        "route": {
            "receiver": "grafana-default-email",
            "routes": [
                {
                    "receiver": "User",
                    "object_matchers": [
                        [
                            "alertname",
                            "=~",
                            "Test"
                        ]
                    ]
                }
            ],
            "group_interval": "5s",
            "repeat_interval": "5s"
        },
        "templates": null,
        "receivers": [
            {
                "name": "grafana-default-email",
                "grafana_managed_receiver_configs": [
                    {
                        "uid": "TcaRRL0nz",
                        "name": "grafana-default-email",
                        "type": "email",
                        "disableResolveMessage": false,
                        "settings": {
                            "addresses": "default@test.com",
                            "singleEmail": false
                        },
                        "secureFields": {}
                    }
                ]
            },
            {
                "name": "User",
                "grafana_managed_receiver_configs": [
                    {
                        "uid": "T5aggY07kz",
                        "name": "User",
                        "type": "email",
                        "disableResolveMessage": false,
                        "settings": {
                            "addresses": "user@test.com",
                            "singleEmail": false
                        },
                        "secureFields": {}
                    }
                ]
            }
        ]
    }
}
```


```json
{
    "Test": [
        {
            "name": "Test",
            "interval": "1d",
            "rules": [
                {
                    "expr": "",
                    "for": "0s",
                    "grafana_alert": {
                        "id": 932,
                        "orgId": 1,
                        "title": "Test Temperature",
                        "condition": "C",
                        "data": [
                            {
                                "refId": "A",
                                "queryType": "",
                                "relativeTimeRange": {
                                    "from": 86400,
                                    "to": 0
                                },
                                "datasourceUid": "c7756945-a3f8-4a6d-9d7f-274f18501c92",
                                "model": {
                                    "datasource": {
                                        "type": "influxdb",
                                        "uid": "c7756945-a3f8-4a6d-9d7f-274f18501c92"
                                    },
                                    "groupBy": [
                                        {
                                            "params": [
                                                "$__interval"
                                            ],
                                            "type": "time"
                                        },
                                        {
                                            "params": [
                                                "device_name::tag"
                                            ],
                                            "type": "tag"
                                        },
                                        {
                                            "params": [
                                                "null"
                                            ],
                                            "type": "fill"
                                        }
                                    ],
                                    "intervalMs": 1000,
                                    "maxDataPoints": 43200,
                                    "measurement": "device_frmpayload_data_TempC_SHT",
                                    "orderByTime": "ASC",
                                    "policy": "default",
                                    "refId": "A",
                                    "resultFormat": "time_series",
                                    "select": [
                                        [
                                            {
                                                "params": [
                                                    "value"
                                                ],
                                                "type": "field"
                                            },
                                            {
                                                "params": [],
                                                "type": "mean"
                                            }
                                        ]
                                    ],
                                    "tags": []
                                }
                            },
                            {
                                "refId": "B",
                                "queryType": "",
                                "relativeTimeRange": {
                                    "from": 86400,
                                    "to": 0
                                },
                                "datasourceUid": "__expr__",
                                "model": {
                                    "conditions": [
                                        {
                                            "evaluator": {
                                                "params": [],
                                                "type": "gt"
                                            },
                                            "operator": {
                                                "type": "and"
                                            },
                                            "query": {
                                                "params": [
                                                    "B"
                                                ]
                                            },
                                            "reducer": {
                                                "params": [],
                                                "type": "last"
                                            },
                                            "type": "query"
                                        }
                                    ],
                                    "datasource": {
                                        "type": "__expr__",
                                        "uid": "__expr__"
                                    },
                                    "expression": "A",
                                    "intervalMs": 1000,
                                    "maxDataPoints": 43200,
                                    "reducer": "max",
                                    "refId": "B",
                                    "settings": {
                                        "mode": "dropNN"
                                    },
                                    "type": "reduce"
                                }
                            },
                            {
                                "refId": "C",
                                "queryType": "",
                                "relativeTimeRange": {
                                    "from": 86400,
                                    "to": 0
                                },
                                "datasourceUid": "__expr__",
                                "model": {
                                    "conditions": [
                                        {
                                            "evaluator": {
                                                "params": [
                                                    100
                                                ],
                                                "type": "gt"
                                            },
                                            "operator": {
                                                "type": "and"
                                            },
                                            "query": {
                                                "params": [
                                                    "C"
                                                ]
                                            },
                                            "reducer": {
                                                "params": [],
                                                "type": "last"
                                            },
                                            "type": "query"
                                        }
                                    ],
                                    "datasource": {
                                        "type": "__expr__",
                                        "uid": "__expr__"
                                    },
                                    "expression": "B",
                                    "intervalMs": 1000,
                                    "maxDataPoints": 43200,
                                    "refId": "C",
                                    "type": "threshold"
                                }
                            }
                        ],
                        "updated": "2024-01-17T14:20:10Z",
                        "intervalSeconds": 86400,
                        "version": 14,
                        "uid": "e395b2fb-74dd-4bad-b1a3-43e5c560472b",
                        "namespace_uid": "c7e163e0-b720-4152-8940-2c3cafb56aa2",
                        "namespace_id": 107,
                        "rule_group": "Test",
                        "no_data_state": "Alerting",
                        "exec_err_state": "Error",
                        "is_paused": false
                    }
                }
            ]
        }
    ]
}
```

When a rule fires, the Notification Policies UI reads

```
alertname =~ Test
3 instances @ Delivered to User
```

However, the email is sent to the default contact point.

**Comment by DohanKim** [comment] 2024-01-26 16:57
@armandgrillet any update on this? it keeps happening.

**Comment by aswindevs** [comment] 2024-05-17 07:52
Any update on this? Facing the same issue

**Comment by KaplanSarah** [comment] 2024-05-30 16:03
We believe this was fixed (https://github.com/grafana/grafana/pull/88413).  This will be fixed in Grafana 11.1.  Once it is released, if you are still experiencing the issue please re-open the ticket.

**Closed by KaplanSarah** 2024-05-30 16:03 UTC
Labels: area/alerting, triage/needs-confirmation

**Comment by lafrech** [comment] 2024-05-31 12:54
Thanks for the feedback. I've been doing a few tests this morning. The PR you link to fixes the alert preview so it won't impact what actually happens. However it will greatly help figure out what happens, having the preview actually work.

I guess my issue was a regex related issue. I won't try to figure it out until 11.1, but trying with an equality test on a label (label project = "my project") does work so from my perspective, the resolution is a mix of "can't reproduce", "user should learn regex" and "please wait until 11.1 and open a specific issue if regex matching doesn't behave as expected".

Thanks for the great work on Grafana, specifically the alert / notifications module. It is a bit of a gas factory and I'm still struggling to achieve what I assume are simple things but there are so many use cases to manage that it is hard to do both simple and full-featured.

**Comment by DohanKim** [comment] 2024-06-02 08:16
Thanks for the update.
But I'm still experiencing the issue on Grafana 11.1
