### ISSUE TITLE
Redirect after login doesn't work for Explore

### ISSUE THREAD

**Issue by mure** [grafana/grafana#56827] opened 2022-10-12 20:22 UTC
**What happened**:

![Kapture 2022-10-12 at 15 12 53](https://user-images.githubusercontent.com/9257800/195439503-c084a8f1-89c4-47e9-a5ec-7e74d8bf618f.gif)

Navigating to the Explore view after a login takes you to the homepage.

**What you expected to happen**:

After logging in, you should be redirected to the correct path.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Explore view and build any query.
2. Copy the URL.
3. Log out of Grafana.
4. Navigate to the copied URL

**Anything else we need to know?**: n/a

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: n/a
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS & Safari/Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by zuchka** [comment] 2022-10-15 08:01
Thanks for creating this issue, @mure 

reproduced this on main. you can get a redirect to many different areas of Grafana but not explore

**Comment by gelicia** [comment] 2022-10-19 20:46
During grooming today we discovered that this is a duplicate of #51097 so we will close this one and put that one as in progress.

**Comment by gelicia** [comment] 2022-10-19 20:47
This is somewhat related to #51097 which is more about parts of the URL not working correctly, I will test those items as well for this fix.

**Comment by mure** [comment] 2023-03-07 23:18
@gelicia 
I think this needs to be reopened. I'm still running into the same behavior when using the `serve_from_sub_path` config. 

My `grafana.ini` is simply:

```ini
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

And redirects after login don't work for the Explore mode. This is a pretty important part of our workflow, unfortunately.

**Comment by ifrost** [comment] 2024-02-22 08:39
> I think this needs to be reopened. I'm still running into the same behavior when using the serve_from_sub_path config.

I was not able to reproduce it in the latest version (with or without sub path). Could you please check again with Grafana 10.3.0? Also - could you check if it still affects only Explore or other redirects as well?

**Comment by Elfo404** [comment] 2024-03-11 14:23
Closing this as Grafana 9.1 is EOL and we can't reproduce on main/10.4. Please feel free to comment if we missed something and we can reopen this.

**Closed by Elfo404** 2024-03-11 14:23 UTC
Labels: type/bug, area/explore, area/frontend/login
