### ISSUE TITLE
Granular Docker Tags

### ISSUE THREAD

**Issue by dansiviter** [grafana/grafana#25284] opened 2020-06-02 09:47 UTC
**What would you like to be added**:
For each release add `<major>.<minor>` and `<minor>` tags to Docker images.

e.g. `7.0.1` would also have:
* `7.0`
* `7`

Also, `7.0.1-ubuntu` would have:
* `7.0-ubuntu`
* `7-ubuntu`

**Why is this needed**:
For Instances where we need to auto upgrade to pick up latest patches (bug fix, security) but do not want to break the semvar contract. This will help reduce toil and help address issues automatically.

**Comment by tobijdc** [comment] 2021-04-09 07:51
Looks like this issue is a duplicate of this one
https://github.com/grafana/grafana/issues/16193

**Comment by aknuds1** [comment] 2021-04-09 08:11
Duplicate of #16913.

**Closed by aknuds1** 2021-04-09 08:11 UTC
Labels: area/backend, area/docker, type/build-packaging, type/feature-request
