### ISSUE TITLE
Different behaviour between "previous month" selection and "now-1M/M) for SingleStat

### ISSUE THREAD

**Issue by nwagenmakers** [grafana/grafana#22541] opened 2020-03-03 15:13 UTC
**What happened**:

I want to make a SingleStat showing the summed values for previous month. I want this SingleStat to be 'fixed' to the previous month regardless of the time selection. Therefore I used the "now-1M/M" statement in the relative time field. 

**What you expected to happen**:

I expected the values between the fixed setup (now-1M/M) and the time selection (using the dropdown "previous month") to be the same. However this differs (see screenshots). The difference is caused by the relative (fixed) time setup also including the values for this month).

**How to reproduce it (as minimally and precisely as possible)**:
have a set of simple values for each day for one month (and some additional days in a new month). Create a singlestat and have select the sum of the value for a timefilter. Set the timefilter to "previous month" and note the sum. Then use the relative time (now-1M/M) and check if there is a difference.

![timeselection](https://user-images.githubusercontent.com/61746683/75788780-fc5a9c00-5d68-11ea-93be-46d028f9de61.JPG)
![relativetime](https://user-images.githubusercontent.com/61746683/75788789-febcf600-5d68-11ea-8c62-63795a3d28df.JPG)

**Anything else we need to know?**:

This is done in the month February (and this year is a leapyear). Not sure if this is related?

**Environment**:
- Grafana version: Grafana v6.4.4 (092e514)
- Data source type & version: Influxdb version 1.7.9
- OS Grafana is installed on: Raspian Buster
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: Traffic Lights v1.4.5 and Sun and Moon v0.1.5

**Comment by torkelo** [comment] 2020-03-04 20:48
Relative time only supports relative to now, and does not support this "previous month" format as it requires a from & to . 

so a bit like a dupe of https://github.com/grafana/grafana/issues/22163

**Closed by torkelo** 2020-03-04 20:48 UTC
