### ISSUE TITLE
Dashboard Scenes: Unexpected width for panels set to repeat

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#87229] opened 2024-05-02 12:15 UTC
### What happened?

The width of a panel repeating is too small - on edit mode, but fine on refresh

https://github.com/grafana/grafana/assets/42030685/24081e0b-0a1a-4a7b-9528-2bc7fbe2f777

### What did you expect to happen?

Either the width of the repeated panels should be the same as the width of the initially created panel? Or panels are spread through the full horizontal space.

### Did this work before?

I think so 😉 

### How do we reproduce it?

1. Create a panel + set it to repeat by a template variable
2. Select all values from variable
3. The initial height of the panel is kept for each new one, but the width of the initial panel is now divided by the number of panels in that row 
4. But if you save the dashboard and refresh then panels now use all the horizontal space

### Environment (with versions)?

Grafana: v11.1.0-70005 (6dbc44920c)
OS: mac
Browser: chrome

### Grafana platform?

None

**Comment by torkelo** [comment] 2024-05-06 06:56
dupe of https://github.com/grafana/grafana/issues/84847

**Closed by torkelo** 2024-05-06 06:56 UTC
Labels: type/bug, area/scenes, internal, team/grafana-dashboards
