### ISSUE TITLE
DNS resolve issues in Alpine docker image

### ISSUE THREAD

**Issue by ikkerens** [grafana/grafana#20153] opened 2019-11-04 09:03 UTC
**What happened**:
Since v6.4.0-beta1 Grafana uses alpine linux as base image, despite there being some known issues with using alpine.
In this particular issue I'd like to address the bugged DNS resolving in alpine linux, described here: https://github.com/kubernetes/kubernetes/issues/30215
I tried describing this problem in https://github.com/grafana/grafana/issues/10727 as it seemed related, but since that issue is closed it doesn't seem to get attention anymore.

This affects my Grafana installation as it randomly decides it cannot resolve the hostname of my postgresql server, causing me to be unauthorized and forced to log out.

As shown in the log:
```
t=2019-11-01T15:18:33+0000 lvl=info msg="Successful Login" logger=http.server User=--snip--
t=2019-11-01T15:19:09+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="dial tcp: lookup postgres.databases.svc.cluster.local: no such host"
t=2019-11-01T15:19:09+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/query status=401 remote_addr=--snip-- time_ms=11 size=26 referer="https://--snip--/d/TuobtjoZz/--snip--?orgId=1&refresh=5s&from=now-12h&to=now"
```
After downgrading to 6.3.6 this issue has disappeared entirely.

**What you expected to happen**:
No DNS resolve issues

**How to reproduce it (as minimally and precisely as possible)**:
Run grafana in kubernetes, connect it to a database using a kubernetes hostname, observe the dashboard on a low refresh time (the more requests - the sooner it'll happen)

**Anything else we need to know?**:
A lot of Docker images offer both Alpine and non-Alpine images, please adopt this method as well so that people who run into issues with using Alpine can continue using later versions of Grafana.

**Environment**:
- Grafana version: v6.4.0-beta1 and later
- Data source type & version: Postgres 12
- OS Grafana is installed on: Docker (Alpine), no issue on Docker (Ubuntu)
- User OS & Browser: Windows / Chrome, though can reproduce on any browser
- Grafana plugins: Default distribution
- Others: Running inside Kubernetes

**Comment by aknuds1** [comment] 2019-11-04 10:28
Are you sure this is the same issue as what is discussed in https://github.com/kubernetes/kubernetes/issues/30215?

I think the issue you're seeing is that DNS addresses with the .local suffix can't be resolved, which I have in the past found to be caused by the Go DNS resolver. I fixed that myself by forcing Go to use the system DNS resolver instead (also on Alpine), which handles .local addresses correctly (whereas the Go built-in resolver seems to think .local addresses are mDNS IIRC).

**Comment by aknuds1** [comment] 2019-11-04 10:30
Can you please try resolving this by forcing the system DNS resolver as described [here](https://golang.org/pkg/net/#hdr-Name_Resolution)? I.e., set `GODEBUG=netdns=cgo` in the environment of the grafana container.

**Comment by ikkerens** [comment] 2019-11-04 11:31
Using docker tag 6.4.3 and setting the `GODEBUG` env var to `netdns=cgo` reintroduced the issue where the host could not be resolved. (Same errors, so I won't bother recopying)
However, as curiosity got the better of me, I also tried setting it to `netdns=go`, which resolved the issue again.

So to me, this strengthens the alpine-is-the-problem argument.

**Comment by aknuds1** [comment] 2019-11-05 15:02
@ikkerens I'm surprised that forcing the Go DNS resolver would resolve the issue vs cgo, as I've experienced the opposite in the past. I'd be interested in understanding why the Go DNS resolver works here, and also why it isn't already enabled since it's the default?

Can you confirm that a valid workaround for you is to set `GODEBUG=netdns=cgo` in your container environment?

**Comment by marefr** [comment] 2019-11-05 15:25
Thanks for the feedback. We've decided to build and publish an additional Ubuntu-based image for those having problems with using Alpine, see #20178.

**Comment by ikkerens** [comment] 2019-11-05 21:54
> Can you confirm that a valid workaround for you is to set `GODEBUG=netdns=go` in your container environment?

For me it is, I'm currently running the latest version with that env var set. But ideally this gets resolved (like with the issue that marefr posted) or added to the docs on what *might* help.

**Comment by aknuds1** [comment] 2019-11-06 08:19
Thanks for confirming @ikkerens, I'm surprised that would help, but making a note of it.

**Comment by ikkerens** [comment] 2019-11-06 09:17
Based on my understanding of this situation;
`netdns=go` Uses a pure go DNS resolver that simply reads resolv.conf, which is managed by my cluster DNS, so I think I can safely assume this one is correct.
`netdns=cgo` Uses the systems DNS resolver using nslookup. If what they are saying in the comments of the k8s issue is correct, nslookup is bugged in alpine.

While I don't disbelieve you on the fact that the Go version is imperfect, it seems to work better inside my k8s environment than alpine nslookup does.

Thanks anyway!

**Comment by aknuds1** [comment] 2019-11-06 10:18
@ikkerens I have to test for myself to see what's going on. I can only base myself on the fix I made for another project many months ago, and the Go runtime may have changed since then. From what I recall, `nslookup` worked within the container, while our app didn't until I forced the cgo DNS resolver.

**Comment by aknuds1** [comment] 2019-11-06 10:20
AFAICT from the Kubernetes thread you linked to, they're talking about an `nslookup` bug in Alpine that's fixed since years (if [this](https://github.com/kubernetes/kubernetes/issues/30215#issuecomment-306612110) comment is to be believed).

**Comment by aknuds1** [comment] 2019-11-19 15:19
@ikkerens I tried `nslookup` within a grafana/grafana:6.5.0-beta1 container in a Minikube cluster, looking up a service called "aerospike" in the "databases" namespace. It works, as it did last time I was troubleshooting this type of issue:

```
bash-5.0$ nslookup aerospike.databases.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      aerospike.databases.svc.cluster.local
Address 1: 172.17.0.6 aerospike-1.aerospike.databases.svc.cluster.local
Address 2: 172.17.0.7 aerospike-2.aerospike.databases.svc.cluster.local
Address 3: 172.17.0.5 aerospike-0.aerospike.databases.svc.cluster.local
```

From what I read [here](https://github.com/gliderlabs/docker-alpine/issues/476#issuecomment-457124840) you can ignore the first error output by nslookup. What matters is that it's able to resolve the requested DNS address.

I haven't tested DNS resolution from a Go program yet, that'll have to be the next step.

**Comment by aknuds1** [comment] 2019-11-19 15:42
I tested with a Go program now that looks up a hostname, and that works for both Go and CGo DNS resolvers:

```
bash-5.0$ GODEBUG=netdns=cgo+1 /tmp/test-dns aerospike.databases.svc.cluster.local
go package net: using cgo DNS resolver
DNS lookup of "aerospike.databases.svc.cluster.local" succeeded: [172.17.0.5 172.17.0.7 172.17.0.6]
bash-5.0$ GODEBUG=netdns=go+1 /tmp/test-dns aerospike.databases.svc.cluster.local
go package net: GODEBUG setting forcing use of Go's resolver
DNS lookup of "aerospike.databases.svc.cluster.local" succeeded: [172.17.0.6 172.17.0.7 172.17.0.5]
```

**Comment by aknuds1** [comment] 2019-11-19 16:03
Can you try the 6.5.0-beta1 image @ikkerens, and see if there's any difference?

**Comment by ikkerens** [comment] 2019-11-19 21:44
Just deployed 6.5.0-beta1 on my cluster, removed the GODEBUG envvar and could not reproduce the issue so far, I'll keep it running for a bit to see how this develops.

**Comment by aknuds1** [comment] 2019-11-20 07:57
Great!

**Comment by aknuds1** [comment] 2019-11-21 08:29
Closing this for now, please let us know if you run into problems again.

**Closed by aknuds1** 2019-11-21 08:29 UTC
Labels: area/docker

**Comment by ikkerens** [comment] 2019-11-28 07:58
@aknuds1 Sadly the issue is still present over long-term testing. While it happens significantly less, it's still present. I'm going to install `6.5.0-ubuntu` now and observe that.

**Comment by aknuds1** [comment] 2019-11-28 08:16
@ikkerens Wow, I'm sorry to hear that :/ I wonder what causes it.

**Comment by ikkerens** [comment] 2019-12-08 23:06
Long term testing on the 6.5.0-ubuntu image once again eliminates the issue entire.
I'll just use the ubuntu variants from here on, seems to work well enough for me.

**Comment by aknuds1** [comment] 2019-12-09 08:23
Thanks for reporting that @ikkerens - good to know that Ubuntu based images work better in this regard at the very least.

**Comment by readmodifywrite** [comment] 2024-04-22 16:55
This bug has resurfaced in the intervening years.  mDNS is failing on version 10+.  See #77335
