### ISSUE TITLE
Cloudwatch panels all erroring with "Cannot read from private field"

### ISSUE THREAD

**Issue by pvincentgf** [grafana/grafana#90821] opened 2024-07-23 10:50 UTC
### What happened?

Starting today, all panels loading data from CloudWatch data source are failing with the error "Cannot read from private field"

<img width="289" alt="Screenshot 2024-07-23 at 11 48 17" src="https://github.com/user-attachments/assets/f429de46-00d9-4b18-9f73-83332d599dd1">

### What did you expect to happen?

Widgets should be loading correctly

### Did this work before?

No, only started today - possibly with latest release v11.2.0

### How do we reproduce it?

1. Create a panel that uses Cloudwatch as datasource
2. Attempt loading data
3. Widget is not loading, with red warning "Cannot read from private field"

### Environment (with versions)?

Grafana: Grafana Cloud - version Grafana v11.2.0-73451 (a0268a9ad2)
OS: MacOS
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

CloudWatch

**Comment by pvincentgf** [comment] 2024-07-23 11:24
Actually, isn't it strange that our Grafana Cloud instance is running v11.2.0 while the [milestone](https://github.com/grafana/grafana/milestone/529?closed=1) isn't completed yet?

**Comment by KhazMcdust** [comment] 2024-07-23 15:57
I have this same error all of a sudden with my dashboard used with Athena data source. 
![Screenshot 2024-07-23 115318](https://github.com/user-attachments/assets/36a4e6ed-2b9b-4f97-84e1-b35437509bbc)
The dashboard worked just fine minutes ago and now none of it seems to be working anymore.

What did you expect to happen?
Widgets should be loading correctly

Did this work before?
Yes about 15 minutes ago.

How do we reproduce it?
Create a panel that uses Amazon Athena datasource.
Attempt loading data
All widgets not loading, with red warning "Cannot read from private field"
Is the bug inside a dashboard panel?
No response

Environment (with versions)?
Grafana: Grafana Cloud - version Grafana v11.2.0-73451 
OS: Windows 11
Browser: Edge

Grafana platform?
I use Grafana Cloud

Datasource(s)?
Amazon Athena

**Comment by aa-yledesma** [comment] 2024-07-23 16:42
We're having the same problem at my job with Grafana Cloud. We can access AWS metrics from the Explorer tab, but we can't access those same metrics in a dashboard.

**What did you expect to happen?**
We're expecting our alert groups to display metrics, like they do in Explore mode.

Explore view:
![image](https://github.com/user-attachments/assets/e1515891-b2f3-43a1-becb-d16173752df2)

Dashboard view: 
![image](https://github.com/user-attachments/assets/bb0e46d0-0728-4d7c-9aef-e601f79486be)


**Did this work before?**
Yes. Last time we checked, it was working around 10 hours ago. But it hasn't been working since this morning.

**How do we reproduce it?**
Create a panel that uses Amazon CloudWatch a the data source.
The alert rule should show as empty, with a warning block displaying: "Cannot read from private field"

**Is the bug inside a dashboard panel?**
Yes. It only happens with panels sourcing from CloudWatch. I doesn't happen with panels sourcing metrics straight from other AWS services, like RDS volume endpoints.

**Environment (with versions)?**
Grafana: Grafana Cloud - version Grafana v11.2.0-73451 (a0268a9ad2)
OS: Pop!_OS 22.04 LTS
Browser: Firefox 128.0 (64-bit)

**Grafana platform?**
Grafana Cloud

**Datasource(s)?**
Amazon CloudWatch

**Comment by gvwirth** [comment] 2024-07-23 17:46
We are experiencing the same issue.

**Comment by v4de** [comment] 2024-07-23 18:52
Same issue here, cloudwatch datasource is able to be queried using metrics explorer. However all panels using a cloudwatch datasource have the same error with "Cannot read from private field".

**What did you expect to happen?**
Panels to display previously used fields from cloudwatch data source

**Did this work before?**
This was working yesterday morning

**How do we reproduce it?**
    Create a panel that uses Cloudwatch as datasource
    Select AWS/ECS and CPUUtilization maximum
    Add dimension selecting a service, and deselect "match exactly"
    run query and see red warning icon with text: "Cannot read from private field"

**Is the bug inside a dashboard panel?**
yes

**Environment (with versions)?**
Grafana: Grafana Cloud - Grafana v11.2.0-73451 (a0268a9ad2)
OS: Windows
Browser: Firefox Developer Edition

**Grafana platform?**
I use Grafana Cloud

**Datasource(s)?**
CloudWatch

**Comment by wwilson-andesite** [comment] 2024-07-23 19:16
I'm seeing the same issue with Athena panels

**Comment by sajidkhan8530** [comment] 2024-07-23 19:31
> ### What happened?
> Starting today, all panels loading data from CloudWatch data source are failing with the error "Cannot read from private field"
> 
> <img alt="Screenshot 2024-07-23 at 11 48 17" width="289" src="https://private-user-images.githubusercontent.com/61195971/351295357-f429de46-00d9-4b18-9f73-83332d599dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjMzMjEsIm5iZiI6MTcyMTc2MzAyMSwicGF0aCI6Ii82MTE5NTk3MS8zNTEyOTUzNTctZjQyOWRlNDYtMDBkOS00YjE4LTlmNzMtODMzMzJkNTk5ZGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE5MzAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMTkxMjdhYjZkMmViMTFmZjMwNDcxOThkNWUwMjc0OTA3MGExMWRjODlkZDY4YzIzNDAwZDQ2YTZiZGU2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.scdyiASnB2u4Y8szRYmc-6QnXsYdpIevTHFUFmcX5Vg">
> ### What did you expect to happen?
> Widgets should be loading correctly
> 
> ### Did this work before?
> No, only started today - possibly with latest release v11.2.0
> 
> ### How do we reproduce it?
> 1. Create a panel that uses Cloudwatch as datasource
> 2. Attempt loading data
> 3. Widget is not loading, with red warning "Cannot read from private field"
> 
> ### Is the bug inside a dashboard panel?
> _No response_
> 
> ### Environment (with versions)?
> Grafana: Grafana Cloud - version Grafana v11.2.0-73451 ([a0268a9](https://github.com/grafana/grafana/commit/a0268a9ad258efe408a4325e33b513c16ce4182c)) OS: MacOS Browser: Chrome
> 
> ### Grafana platform?
> I use Grafana Cloud
> 
> ### Datasource(s)?
> CloudWatch

facing same issue

**Comment by mariomerco** [comment] 2024-07-23 19:36
Same over here. 
Alerts are working and I can see the actual data being graphed on the _Explore_ view. So seems to be related to only dashboards, as one of our colleagues here mentioned.
**Grafana v11.2.0-73451 (a0268a9ad2)**

**Comment by sajidkhan8530** [comment] 2024-07-23 19:37
I am also getting same error in my Grafana dashboard which is integrated witho cloudwatch.
![Screenshot (454)](https://github.com/user-attachments/assets/2fb50aa6-ae33-4db7-97a0-d4f4f4933a89)

**Comment by mariomerco** [comment] 2024-07-23 20:34
BTW, I submitted a ticket with Grafana Cloud support and they told us they are working on it. In the meantime, the applied some changes in the _feature toggles_ and it brought back the dashboards

**Comment by pmacca** [comment] 2024-07-23 23:25
> BTW, I submitted a ticket with Grafana Cloud support and they told us they are working on it. In the meantime, the applied some changes in the _feature toggles_ and it brought back the dashboards

Any idea what the change was? 😓
We've lost monitoring visibility.

**Comment by MylesBR** [comment] 2024-07-24 00:15
adding link from customer experiencing issue https://grafana.zendesk.com/agent/tickets/147005

**Comment by Harryols** [comment] 2024-07-24 05:35
I have the same issue with grafana as a service and Azure.

**Comment by Harryols** [comment] 2024-07-24 06:54
It works for me now

**Comment by magweter** [comment] 2024-07-24 08:21
Same, very annoying

**Comment by mbitstefanzeilinger** [comment] 2024-07-24 08:21
Works for us now, had the error until a couple of minutes ago.

**Comment by KANOMNUT** [comment] 2024-07-24 08:31
Same on Azure Monitor data source

**Comment by mehdibo** [comment] 2024-07-24 10:42
@KANOMNUT did it work for you? I can't seem to find the `dashboardScene` option in **Administration >> General >> Feature Toggles**

**Comment by KANOMNUT** [comment] 2024-07-24 11:55
@mehdibo Yes, it works for me after the Grafana support team add ```dashboardScene``` to my Grafana Cloud tenant. If you're using Grafana Cloud, you must open a support case. They'll help you to add it to your tenant.

**Comment by mehdibo** [comment] 2024-07-24 12:42
> @mehdibo Yes, it works for me after the Grafana support team add ```dashboardScene``` to my Grafana Cloud tenant. If you're using Grafana Cloud, you must open a support case. They'll help you to add it to your tenant.

I see, thanks a lot for the reply

Apparently they rolled back, now im getting an older UI and it's working fine

**Comment by iwysiu** [comment] 2024-08-21 17:56
I'm closing this issue because the bug was rolled back, feel free to open a new issue if the problem reoccurs!

**Closed by iwysiu** 2024-08-21 17:56 UTC
Labels: datasource/CloudWatch
