### ISSUE TITLE
Explore unwrapped long line break the "show context" features

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#22126] opened 2020-02-12 16:52 UTC
**What happened**:

If you have a very long line and choose the not wrap it the show context button is not working anymore.
see
![image](https://user-images.githubusercontent.com/1053421/74357370-d2c3db80-4d8d-11ea-8b5a-d9ed7cab29a4.png)

If I select wrap lines, it works.

![image](https://user-images.githubusercontent.com/1053421/74357422-e53e1500-4d8d-11ea-8c5a-2d8fccf8bdcd.png)

**What you expected to happen**:

Show context should work in both case.

**How to reproduce it (as minimally and precisely as possible)**:

Have a long line and unselect the wrap line option.

![image](https://user-images.githubusercontent.com/1053421/74357498-030b7a00-4d8e-11ea-916e-a7ac1546524c.png)

**Environment**:
- Grafana version: Grafana v6.7.0-daa487a4pre (1448767c08)
- Data source type & version: Loki explore

**Comment by aocenas** [comment] 2020-06-17 08:50
The issue is nesting of scrolable containers so not easy to fix, the context feature is being redesigned so it is easier to solve this.

**Comment by aocenas** [comment] 2021-03-29 11:36
Closing as duplicate of https://github.com/grafana/grafana/issues/27262

**Closed by aocenas** 2021-03-29 11:36 UTC
Labels: area/explore, area/panel/logs, datasource/Loki, type/bug
