### ISSUE TITLE
Incorrect y Axis scaling in multi-value Stats panel

### ISSUE THREAD

**Issue by ecraven** [grafana/grafana#36314] opened 2021-06-30 19:21 UTC
I just upgraded to Grafana 8. I have many Stats panels showing multiple values (see Screenshot), before the upgrade they all were scaled to the same Y axis, now they each seem to be scaled separately.
46.9 is definitely less than 50, so in order to actually compare the values, is there any way to get the old behaviour back? I haven't found any setting for this :-/
Thanks for any help!
![maim](https://user-images.githubusercontent.com/215510/124019258-2073cf00-d9e9-11eb-85a1-e01587ad8b2b.png)

**Comment by leeoniya** [comment] 2021-06-30 19:37
Duplicate of https://github.com/grafana/grafana/issues/32765

(please pvote that one)

**Closed by leeoniya** 2021-06-30 19:37 UTC
