### ISSUE TITLE
log scale axis: does not respect Y-min set to 0, wrongly displays value 0 as 1

### ISSUE THREAD

**Issue by jgehrcke** [grafana/grafana#24086] opened 2020-04-30 10:19 UTC
Consider these axis settings, with log scale and `y-min` set to `0`:
![Screenshot from 2020-04-30 11-51-02](https://user-images.githubusercontent.com/265630/80697460-421db180-8ad9-11ea-8b62-82f2105ca0dc.png)

This is how a series with constant value 0 renders:
![Screenshot from 2020-04-30 11-51-54](https://user-images.githubusercontent.com/265630/80697499-52359100-8ad9-11ea-9312-46b809074e3b.png)

Two issues:
1. The `Y-min` is explicitly set to `0` and there is no error shown in the UI, yet the actual `Y-min` in the plot is `1`.
2. The data value 0 is shown by the line plot as if it is 1 (the labels show `current: 0`, but the colored lines imply: `1`.

**What you expected to happen**:
With those axis settings and the example data I expect Grafana to apply a strategy commonly called "symlog" (changing the scale around 0) to actually show the y tick `0`, and to draw the line plot **at 0** in the graph.

**Anything else we need to know?**:
- I have used many plotting tools throughout my scientific career. This problem here is a weak spot in various younger tools (see for example https://github.com/bokeh/bokeh/issues/6517). I think we should appreciate that while it may be considered an edge case, more often than not you _have to_ make sure that very small values, even 0, are displayed in a log-scale plot.

- Matplotlib has "symlog" as a pragmatic solution where between (and including) 0 and 1 a linear scale is applied. This is really a pretty satisfying solution! See https://matplotlib.org/3.1.0/gallery/scales/symlog_demo.html. This approach could be adapted in Grafana, too, and is hopefully quite low-effort. This comment contains an inspiration for various specific scaling/smoothing implementations: https://github.com/matplotlib/matplotlib/issues/7008#issuecomment-595607778

- The main motivation for displaying small values (including 0) may be that I want to know when my assumption is wrong ("the value 0 is never going to happen"). In that case I care  about small values, including 0, being displayed in the graph.

- https://github.com/grafana/grafana/issues/2829 discussed this problem space before. However, I think the problem wasn't described as crisp, and also the symlog solution wasn't discussed.

- I have done the screenshots above with Grafana version: 7.0.0-beta1, but this problem also exists in 6.7.x and probably before that.

**Comment by papagian** [comment] 2020-05-03 12:07
Duplicate of #23674

**Closed by papagian** 2020-05-03 12:07 UTC
Labels: type/duplicate
