### ISSUE TITLE
Span tooltips, tooltips for tables and general unified tooltip architecture

### ISSUE THREAD

**Issue by memetb** [grafana/grafana#24900] opened 2020-05-20 04:46 UTC
I've seen multiple issues vaguely related to this tooltip question but not exactly this. Also, there's multiple features but all relate to the tooltips architecture, so I will just list them and maybe we edit this request:

1. for plugins like Table and Logs, it would be nice to be able to highlight the closest rows that correspond to a shared tooltip, and conversely share the tooltip location of a currently hovered over row. The use case is straightforward: if I mouse over a log entry, it would make sense to see where in the trendlines this corresponds to.

2. it would also be useful to have a feature that allows spans instead of points to be shared in throughout the grafana tooltip API. This would allow, for instance, highlighting of a section of the graph panel when a segment is hovered over in a plugin like the grafana-discrete-natel plugin.

I'm currently in the process of writing a plugin that would definitely make use of this latter feature and I'm wondering if there's a roadmap for the idea at all.

Feature 1. is also a feature that should be fairly straightforward to implement, however it would involve patching existing code and I'm not about to fork a plugin just to add that feature. Any advice on how to approach this, including development contribution, is appreciated. Do you want me to work on a solution or would you like to keep it inhouse?

Thank you.

**Comment by torkelo** [comment] 2020-05-20 06:43
thanks for the description, we have this on the roadmap as an unfinished architectural piece for the new panel architecture. 

duplicate of https://github.com/grafana/grafana/issues/22672 

Work was started trying to find ways to address this https://github.com/grafana/grafana/pull/21010  but not yet completed

**Closed by torkelo** 2020-05-20 06:43 UTC
Labels: type/feature-request

**Comment by memetb** [comment] 2020-05-20 06:51
Thanks for the reply.

**Comment by memetb** [comment] 2020-05-20 06:56
Btw, with regards to point 1, does the grafana team encourage enhancements to core plugins (specifically Logs and Table) or do you prefer we implement this as a third party plugin?
