### ISSUE TITLE
[Feature request] Table panel with 2D time series aggregations

### ISSUE THREAD

**Issue by cubranic** [grafana/grafana#8933] opened 2017-07-26 13:33 UTC
Given a metric with two dimensions, I'd like to use the table panel to show a table where columns are created from the values of one dimension, rows from the values the other, and the value of each cell is the current value (or aggregation) of the metric with that cell's coordinates.

As a real-world example, let's say I have a Prometheus data source. It provides the "up" metric, with labels "job" and "instance". I'd like to arrange the values of "up" into a grid for each job/instance combination, with jobs as columns and instances as rows. Right now, the closest I can get is to have the aggregation(s) as columns, and job/instance combinations as rows.

System information:
- Grafana version: 4.4
- Datasource: Prometheus
- OS: Linux

**Comment by torkelo** [comment] 2017-07-26 19:59
duplicate of https://github.com/grafana/grafana/issues/7169

**Closed by torkelo** 2017-07-26 19:59 UTC
