### ISSUE TITLE
Azure Monitor Datasource struggles with resource-groups having large number of resources

### ISSUE THREAD

**Issue by vipinvkmenon** [grafana/grafana#28016] opened 2020-10-03 07:36 UTC
**What happened**:

When selecting a ResourceGroup with a large number of resources, Grafana is unable to parse/handle it
**What you expected to happen**:

The resources are listed as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Based on the documentation following variables were created

```
Name: Subscriptions
Type: DataSource
Data Source: Azure Monitor
```
```
Name: ResourceGroup
Type: Query
Data Source: $Subscriptions
Query: ResourceGroups()
```
```
Name: VMS
Type: Query
Data Source: Azure Monitor
Query: ResourceNames($ResourceGroup,Microsoft.Compute/virtualMachines)
```

Use the dashboard with the above variables and Select a ResourceGroup with a large number of resources (1000+ in our case).

**Anything else we need to know?**:

Did a comparison of API calls and observed the following:

on calling the API: `/api/datasources/proxy/11/azuremonitor/subscriptions/<******>/resourceGroups/<rg-name>/resources?api-version=2018-01-01`

All the resources get listed as expected

On resource groups, it comes with a response JSON as:
```
{"value":[
{"id":"/subscriptions/<***>/resourceGroups/<rg-name>/providers/Microsoft.Compute/disks/pantestvm_OsDisk_1_1ce0636cb80945b9a6b0a8e041e97daa",
"name":"<rg-vm>_OsDisk_1_1ce0636cb80945b9a6b0a8e041e97daa",
"type":"Microsoft.Compute/disks",
"sku":{"name":"Premium_LRS","tier":"Premium"},
"managedBy":"/subscriptions/<***>/resourceGroups/<rg-name>/providers/Microsoft.Compute/virtualMachines/pantestvm",
"location":"westeurope"},

{"id":"/subscriptions<***>/resourceGroups/<rg-name>/providers/Microsoft.Compute/virtualMachines/na",
"name":"some-vm",
"type":"Microsoft.Compute/virtualMachines",
"location":"westeurope"}
]}

```
The variable 'VMS`  is able to list the resources (VMS) and when one of the VMS is selected from the drop-down,

The API call: `/api/ds/query` creates a payload as follows:

```
{"queries":[{"refId":"A","subscription":"*******",
"queryType":"Azure Monitor",
"azureMonitor":
      {
           "resourceGroup":"<rg-name>",
            "resourceName":"<vm-name>",
            "metricDefinition":"Microsoft.Compute/virtualMachines",
            "timeGrain":"auto",
            "metricName":"Network Out",
            "metricNamespace":"Microsoft.Compute/virtualMachines",
            "aggregation":"Total","dimensionsFilters":[],
            "top":"10"},
"datasourceId":11,
"intervalMs":120000,
"maxDataPoints":100,
"orgId":1}],
"range":{"from":"2020-10-03T04:02:53.333Z","to":"2020-10-03T07:02:53.333Z","raw":{"from":"now-3h","to":"now"}},
"from":"1601697773333",
"to":"1601708573333"}
```
Everything is fine and the respective graphs are populated with data.

And. on a resource group with a large number of resources, a  large list, like the example below is obtained in the response.

```
{"value":[
{"id":"/subscriptions/<***>/resourceGroups/<rg-name>/providers/Microsoft.Compute/disks/pantestvm_OsDisk_1_1ce0636cb80945b9a6b0a8e041e97daa",
"name":"<rg-vm>_OsDisk_1_1ce0636cb80945b9a6b0a8e041e97daa",
"type":"Microsoft.Compute/disks",
"sku":{"name":"Premium_LRS","tier":"Premium"},
"managedBy":"/subscriptions/<***>/resourceGroups/<rg-name>/providers/Microsoft.Compute/virtualMachines/pantestvm",
"location":"westeurope"},

{"id":"/subscriptions<***>/resourceGroups/<rg-name>/providers/Microsoft.Compute/virtualMachines/na",
"name":"some-vm",
"type":"Microsoft.Compute/virtualMachines",
"location":"westeurope"}
]
.
.
.
.
.
(about 999 resources) ],
"nextLink":"https://management.azure.com/subscriptions/<***>/........."
}
```
A new property `nextLink` to the next page becomes available. (Is this handled btw? )

The large result of resources, clearly indicates that it's not a permissions issue and also that the particular API call works as expected.

As a result, the variable 'VMS`  is not able to list the resources (VMS) and the drop-down shows None.

The API call: `/api/ds/query` creates a payload in which becomes the resourceName property stays empty as follows: `"resourceName":""`, thus resulting in 404 error. Thus graphs have `no-data` & `404` error.

Again, This is not a permission issue as when the ResourceGroup and ResourceName (VM Name) is hardcoded in the Dashboard it is able to show the data on the graph.

Backend grafana server clearly is able to handle it and is sending data to the dashboard.

It seems though this large list of resource for some reason is not getting assigned/stored parsed somewhere, due to the size in the client-side.

Feels more like front-end parsing issue/storage issue rather than backend. 

Is this known, is there a defined limit on the number of resources that can be handled/stored?

**Environment**:
- Grafana Version: 7.1.0(8101355285)
- Data source type & version: Azure Monitor
- Data Source Version: [0.3.0](https://github.com/grafana/grafana/blob/8a5fc00330fadb0fa2cba9e21e4ca1367963418c/public/app/plugins/datasource/grafana-azure-monitor-datasource/plugin.json)
- OS Grafana is installed on: ubuntu
- User OS & Browser: mac-os, chrome & safari

**Comment by kylebrandt** [comment] 2020-10-19 12:42
@kaydelaney I think this may be on the front end side based on the description. That being said I'm not sure of a good path to reproduce this...

**Comment by kylebrandt** [comment] 2020-10-20 14:35
I've asked MS if they can:
 - Give us (Grafana) access to a subscription with a lot of resources, or
 - Give us a script to create a bunch of resources that would be in the response ( that won't cost $$ :-) )

This will hopefully allow us to reproduce this an localize the issue.

**Comment by marefr** [comment] 2020-11-13 01:15
@vipinvkmenon if you use Chrome developer tools or similar do you see any errors logged in the console? Have you tried a later version of Grafana just to confirm if it has been fixed in a later version? Thanks

**Comment by vipinvkmenon** [comment] 2020-12-21 04:57
As of creating the bug, we are on 7.3.4

Apart from the JSON, nothing in the console,

There are no console errors that Grafana throws.
All the calls seem to be coming back with proper responses as can be seen in the json-response above (Obtained from google developer console). 

When the JSON Array has a large number of elements, it's just not able to parse/list them on the client-side.

**Comment by sarahzinger** [comment] 2021-11-09 14:21
Hi @vipinvkmenon sorry for the delay, just checking in if you're still seeing this problem and if you're seeing this on Grafana 8.0.x?

**Comment by sunker** [comment] 2021-12-27 09:13
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!

**Closed by sunker** 2021-12-27 09:13 UTC
Labels: needs investigation, datasource/Azure, bot/no new info
