### ISSUE TITLE
table header is moving when scroll

### ISSUE THREAD

**Issue by shkim-sandbox** [grafana/grafana#54734] opened 2022-09-05 20:44 UTC
![CleanShot 2022-09-06 at 05 40 42](https://user-images.githubusercontent.com/26107429/188510987-78df7dd6-fa3e-4493-973a-a1c98201f865.gif)

**What happened**: table header is moving

**What you expected to happen**: The table header should be fixed

**How to reproduce it (as minimally and precisely as possible)**: All situations using the table

**Anything else we need to know?**: As far as I know, it needs to be fixed.

**Environment**:
- Grafana version: 9.1.2
- Data source type & version: mysql 8
- OS Grafana is installed on: lunux
- User OS & Browser: mac / chrome
- Grafana plugins: table
- Others:
-

**Comment by ivanahuckova** [comment] 2022-09-06 12:18
duplicate of https://github.com/grafana/grafana/issues/54516

**Closed by ivanahuckova** 2022-09-06 12:18 UTC
