### ISSUE TITLE
Table: Inconsistent names for queried values

### ISSUE THREAD

**Issue by jiping-s** [grafana/grafana#52026] opened 2022-07-11 08:29 UTC
**What happened**:

When there are multiple Prometheus queries but only one of them contains data and "Merge" transformation cannot be applied, the value column is named as `Value` (no matter which query the value comes from)

**What you expected to happen**:

Value should be named like `Value #A`, `Value #B`, etc regardless whether merge is applied, otherwise cell overriding and other transformations depending on the names simply can't work because there is no way to tell which query "Value" comes from.

**How to reproduce it (as minimally and precisely as possible)**:

Create a table of:
- query A: clamp_max(absent(notExists{label="a"}),10)
- query B: clamp_max(absent(notExists{label="b"}),2)

which displays `Value #A = 1` and `Value #B = 2`

Now change query B to `notExists{label="b"}` - instead of displaying "Value #A = 1" it shows "Value = 1"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.4

**Comment by zoltanbedi** [comment] 2022-07-18 16:15
Hi @jiping-s,
I was not able to reproduce the issue you were seeing. Can you please help me with more details?

**Comment by jiping-s** [comment] 2022-08-12 13:12
@zoltanbedi My example was wrong.

Here is a correct one:

1. Create a panel, table type
2. Query any Prometheus source
3. Add first query `absent(notExists{common="me",a="a"}) * 2`
4. Add second query `absent(notExists{common="me",b="b"}) * 3`
5. Add transform "Merge"

Now on the table you can see it joins data from both queries, with label "a", label "b", Value #A and Value #B. Which works

What breaks is that if you change the second query to `notExists{common="me",b="b"} * 3` (thus not existent), the "Value #A" on the table becomes "Value" and Merge transform shows a red hint *Merge has no effect when applied on a single frame.*, which is highly undesirable, as the column name can be changed depending on whether data is available at runtime and makes it impossible to override with styles.

**Comment by Daryes** [comment] 2022-09-18 14:36
When migrating to the 9.x version, I've experienced something similar with the table panel
Might happen with other panels, btw

On a table panel, add 2 queries
* query named A : `count by (instance) ( node_cpu_seconds_total{mode="idle"} )`
* query named B : `sum by (instance) ( node_filesystem_size_bytes{} )`

Instant type, as timeseries for both

Both of them will end being named `Value`, without much possibility to distinguish them.  
You can change the query name, or set a label, internally they are stuck to the name `Value` and will appear as so in all transformations you can add on the queries.

I think Jiping-s problem and mine are both related to the fact that prometheus has a different behavior depending of the query type:
* simple query : ` node_filesystem_size_bytes{}`   
=> the result has the label `__name__` set to `node_cpu_seconds_total`
* complex query : `sum( node_filesystem_size_bytes{} )`   
=> the label `__name__` is dropped by Prometheus and a tag ` Value` is inserted instead

This behavior is visible directly on Prometheus, in the query/graph page : check the name of the result column.

With the table panel on Grafana v9, it seems internally, `__name__` is always expected from Prometheus, and Grafana does not force an extra label to distinguish between the queries if it doesn't have to.

That would explain why I'm unable to separate both queries by any custom query name or label set in Grafana, and Jiping-s  is seeing a query renamed from `Value #A` to `Value` when the second query has no results.  

If I'm not mistaken, having Grafana always forcing the query name onto the result, without trying to adapt to the situation would resolve this.
Something like `__grafana_label__="query name"`, which would always be present on any prometheus query, allowing to use it in the transformations if required.

The alternative would be to have Prometheus itself giving either the possibility to set an alias name on a query to rename `Value`, or inject part or the whole query into the `Value` name

**Comment by tarko** [comment] 2022-10-27 13:34
I'm also falling for this when migrating from old to new table panel.

Multiple queries with merge transformation, sometimes second query correctly doesn't return any data, merge fails with "Merge has no effect when applied on a single frame" and `Value #A` is suddenly named just `Value`.

As added bonus this value field doesn't also pass "filter by name" and "organize fields" transformations and is just hidden.

**Comment by nemobis** [comment] 2023-10-02 15:26
This would ideally be considered as part of the epic for deprecation of the old Table panel: https://github.com/grafana/grafana/issues/70095

**Comment by Daryes** [comment] 2023-10-14 08:27
Take note this seems to be much broader than only the table panel.
I've gave an example in my [precedent message](https://github.com/grafana/grafana/issues/52026#issuecomment-1250322125), but it looks more about the way prometheus has a change of behavior with complex queries (dropping the label `__name__` ) and the fact that Grafana always expect this label to differentiate between queries.

**Comment by nemobis** [comment] 2023-10-14 09:13
> prometheus has a change of behavior with complex queries (dropping the label `__name__` ) and the fact that Grafana always expect this label to differentiate between queries.

I'm not sure what Grafana's assumptions are, but indeed there is some variability in Prometheus datasources: some drop the `__name__` after aggregations and some don't. A few examples are in https://github.com/jacksontj/promxy/issues/596

**Comment by mdvictor** [comment] 2023-11-06 13:03
> @zoltanbedi My example was wrong.
> 
> Here is a correct one:
> 
> 1. Create a panel, table type
> 2. Query any Prometheus source
> 3. Add first query `absent(notExists{common="me",a="a"}) * 2`
> 4. Add second query `absent(notExists{common="me",b="b"}) * 3`
> 5. Add transform "Merge"
> 
> Now on the table you can see it joins data from both queries, with label "a", label "b", Value #A and Value #B. Which works
> 
> What breaks is that if you change the second query to `notExists{common="me",b="b"} * 3` (thus not existent), the "Value #A" on the table becomes "Value" and Merge transform shows a red hint _Merge has no effect when applied on a single frame._, which is highly undesirable, as the column name can be changed depending on whether data is available at runtime and makes it impossible to override with styles.

This seems to not be the case in v10. I tested with the instructions above and the table does show both value #A and #B in the table after modifying the second query. Closing this issue, but do let me know if there is anything else.

**Closed by mdvictor** 2023-11-06 13:03 UTC
Labels: area/panel/table, needs investigation
