### ISSUE TITLE
Unexpected cursor snapping to the previous text box (Firefox only)

### ISSUE THREAD

**Issue by leijurv** [grafana/grafana#26760] opened 2020-08-03 03:33 UTC
**What happened**:

When clicking from one text box to another, the cursor unexpectedly jumps to the beginning of the first text box.
![grafana](https://user-images.githubusercontent.com/3837873/89143550-d136cd00-d4ff-11ea-9e7a-28067a0c2e13.gif)

**What you expected to happen**:

Clicking the second text box would move the cursor to the second text box.

**How to reproduce it (as minimally and precisely as possible)**:

Make two queries (nonempty). Edit text in the first one. Click the second one. The cursor will jump to the beginning of the first one, instead of jumping to where you click.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.1 (3039f9c3bd)
- Data source type & version: Prometheus, official docker, 2.19.3
- OS Grafana is installed on: Official docker
- User OS & Browser: Mac OSX 10.15.5, Firefox 79.0
- Grafana plugins: None
- Others:

**Comment by aknuds1** [comment] 2020-08-03 07:32
I'm seeing if I can repro this.

**Comment by aknuds1** [comment] 2020-08-03 07:39
I can reproduce the issue. I wonder if it's due to the typeahead dropdown. It doesn't happen all the time, i.e. it must be dependent on some state.

**Comment by aknuds1** [comment] 2020-08-04 08:53
I can reproduce the issue on Firefox, but not on Chromium. _However_, on Chromium I can see that when the typeahead dropdown is visible, I sometimes have to click twice to switch focus to the other query. I.e., the first click only hides the dropdown. I wonder if this is why the cursor snaps on Firefox, so the underlying issue is the same (at least my theory): That a first click is needed to hide the dropdown.

**Comment by davkal** [comment] 2020-11-04 09:33
@grafana/grafana-frontend-platform we'll take this.

**Comment by amckinley** [comment] 2020-12-17 19:39
We're seeing similar behavior with the cursor snapping around, but for us it's on Chrome Version 87.0.4280.88 (Official Build) (x86_64), and we're seeing the cursor move within the same textbox. This seems to have started recently when we upgraded to a 7.x.x release (we're currently running 7.3.3).

User video of the bug in action: https://github.com/amckinley/cortex-heap/blob/main/Screen%20Recording%202020-12-17%20at%2010.39.27%20AM.mov?raw=true

**Comment by RichiH** [comment] 2021-03-15 13:16
Datapoint: On v7.3.7 I saw the second behavior, but not the first. That box should be always up to date; I will fix that and update with info for 7.4.3.

**Comment by lindhe** [comment] 2021-05-11 09:11
I have a similar upsettingly annoying bug where I am not allowed to type in a regex filter for my query. I'm wondering if it might be the same issue as this one or another.

## Example

I have the query

```
sum(kube_node_status_capacity_cpu_cores) by (node)
```

and I want to add `{node=~"$Node"}` to match a regex from the variable `$Node`. I can type this far:

```
sum(kube_node_status_capacity_cpu_cores{node=~}) by (node)
```

But when adding `"` with the cursor placed exactly after `~`, everything becomes insanity:
```
sum(kube_node_status_capacity_cpu_cores{node=~}") by (node)
```

**Comment by ivanahuckova** [comment] 2021-11-19 17:40
@gabor can we close this as it should be resolved with https://github.com/grafana/grafana/pull/41357?

**Comment by gabor** [comment] 2021-11-22 06:55
@ivanahuckova yes, i think we can close this for now. if the new editor does not fix the problem we can reopen it. (the new editor should be availabel in grafana 8.3.0)

**Closed by gabor** 2021-11-22 06:55 UTC
Labels: type/bug, priority/important-soon, datasource/Prometheus, area/frontend, area/panel/data
