### ISSUE TITLE
Time Regions don't respect Dashboard's Timezone

### ISSUE THREAD

**Issue by hahnjo** [grafana/grafana#20544] opened 2019-11-21 08:51 UTC
**What happened**:
I tried to add a daily Time Region at 8:00 and the line appears at 9am.

**What you expected to happen**:
I'd expect the line at 8 am.

**How to reproduce it (as minimally and precisely as possible)**:
Use a non-UTC timezone (CET for me which explains difference of 1h)

**Environment**:
- latest Grafana v6.4.4 on CentOS 7
- querying InfluxDB 1.x, but probably not related to the Time Regions
- tested from Firefox on Linux

**Comment by hugohaggmark** [comment] 2019-11-21 12:40
Duplicate of #14400

**Closed by hugohaggmark** 2019-11-21 12:40 UTC
Labels: type/duplicate
