### ISSUE TITLE
Playlist prompting for Save the changes

### ISSUE THREAD

**Issue by shabbi-Allianz** [grafana/grafana#51506] opened 2022-06-28 14:46 UTC
![image](https://user-images.githubusercontent.com/108351798/176209022-17b2d9b1-8110-4125-8e2f-0e84e8897374.png)

**What happened**: Created the playlist, on each change its prompting to save the changes.

**What you expected to happen**: Next dashboard should be visible without prompting as its a playlist.

**How to reproduce it (as minimally and precisely as possible)**: create a playlist with multiple dashboards and run it as TV

**Anything else we need to know?**:

**Environment**:
- Grafana version: Enterprose
- Data source type & version: SQL Server
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: charts and state
- Others:

**Comment by ivanahuckova** [comment] 2022-06-29 09:09
Unfortunately, I wasn't able to reproduce this. Would you mind sharing which version of Grafana are you using and maybe add more details on when does the prompting to save the changes happen. Does it happen always? Or when you interact with the dashboard?

**Comment by JoaoSilvaGrafana** [comment] 2022-06-30 16:11
I believe this is fixed by this https://github.com/grafana/grafana/pull/51315 which was released in 9.0.2. Could you check if you are running that version? You can see it if you hover over the help icon on the nav bar:
<img width="304" alt="Screenshot 2022-06-30 at 17 10 31" src="https://user-images.githubusercontent.com/100691367/176726291-1227182b-9653-46ed-8c41-d6223b58dde7.png">

**Comment by JoaoSilvaGrafana** [comment] 2022-07-18 12:48
This seems to be fixed to me, @shabbi-Allianz  if you still see the issue let us know and we will reopen it

**Closed by JoaoSilvaGrafana** 2022-07-18 12:48 UTC
Labels: type/bug, prio/high, area/playlist
