### ISSUE TITLE
Transform: An unexpected error occurred

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#25231] opened 2020-05-30 06:15 UTC
**What happened**:
Switching from Table to Stat panel while adding the transform, results in 'unexpected error'

![image](https://user-images.githubusercontent.com/14235758/83321094-f0209680-a212-11ea-8547-861f05a2050e.png)

**What you expected to happen**:
No error is expected

**How to reproduce it (as minimally and precisely as possible)**:
1. Goto https://play.grafana.org/d/000000012/grafana-play-home?editPanel=2&orgId=1
2. Click on Transform->Reduce
3. Switch to Table view by following instruction on the chart.
4. Click on 'Add Transformation' -> Filter by Name
![image](https://user-images.githubusercontent.com/14235758/83321042-a0da6600-a212-11ea-88f8-ab7748d31758.png)
5. Switch to 'Stat' panel
![image](https://user-images.githubusercontent.com/14235758/83321053-bbacda80-a212-11ea-8a81-264c0765c145.png)
6. Go back to Query Tab and click on 'Transform' Tab again

**Anything else we need to know?**:
https://play.grafana.org/d/000000012/grafana-play-home?tab=transform&editPanel=2&orgId=1
It looks like, Transform is broken in latest release.

**Environment**:
- Grafana version: 7.0.2
- Data source type & version: NA
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins: Stat/Table/Transform
- Others:

**Comment by aknuds1** [comment] 2020-05-30 06:28
Is this a duplicate of #25227?

**Comment by MacNale** [comment] 2020-05-30 06:29
> Is this a duplicate of #25227?

perhaps - https://github.com/grafana/grafana/pull/25152#issue-423906423

**Comment by dprokop** [comment] 2020-06-01 12:56
Duplicate: https://github.com/grafana/grafana/issues/25122

**Closed by dprokop** 2020-06-01 12:56 UTC
Labels: area/frontend, area/transformations, needs investigation, type/bug
