### ISSUE TITLE
[Feature Request] Changing the horizontal axis time labels

### ISSUE THREAD

**Issue by mcoimbra** [grafana/grafana#12677] opened 2018-07-20 17:33 UTC
At the moment, as far as I am aware, for any given time series, the horizontal time axis labels only change with the Grafana user interface zoom-in or zoom-out actions.
If we are looking at the period of one month, it may show the days of the month, but if we are looking at one year, it will probably show the months.

Is there any way where I can specifically force Grafana to show for example week numbers?

I don't want to change the granularity of the data - I can already use a custom variable to group my series by hour, week, month, whatever I want.

What I would like is to change the horizontal axis labels to show for example weeks:

Jun Week 4
Jun Week 5
Jul Week 1
Jul Week 2
Jul Week 3

Instead of:

6/16
6/23
7/1
7/8
7/16
7/24

This is how it looks currently:

![grafana_feature](https://user-images.githubusercontent.com/2273294/43016621-5422d7cc-8c4b-11e8-9483-c20aee23ac0a.PNG)

I originally made this question here:

[https://community.grafana.com/t/time-series-dashboard-from-mysql-setting-the-granularity-of-the-xx-axis/8792/3](https://community.grafana.com/t/time-series-dashboard-from-mysql-setting-the-granularity-of-the-xx-axis/8792/3)

Thank you very much.

**Comment by daniellee** [comment] 2018-07-23 09:13
Not currently possible.

**Comment by torkelo** [comment] 2018-07-23 10:21
Think there already is a feature request for custom time axis formats

**Comment by marefr** [comment] 2018-07-23 11:06
Duplicate of #3591

**Closed by marefr** 2018-07-23 11:06 UTC
Labels: comp: panel/graph, type: feature request, type: ux
