### ISSUE TITLE
Cant install Grafana following instructions

### ISSUE THREAD

**Issue by marekbeckmann** [grafana/grafana#28103] opened 2020-10-08 07:29 UTC
**What happened**: I tried to install Grafana following the official instructions (OSS release) for Debian (https://grafana.com/docs/grafana/latest/installation/debian/)

**How to reproduce it (as minimally and precisely as possible)**: Simply follow the installation instructions (see link above). When it comes to the step `sudo apt-get update` the error will occur (see image below)

![error-installation](https://user-images.githubusercontent.com/56757636/95427861-80e94a80-0948-11eb-8479-fb70bdd6b38c.png)

**Environment**:
- OS Grafana is installed on: Debian 10 Buster

**Comment by aknuds1** [comment] 2020-10-08 07:33
Yeah sorry, it's a problem we're in the middle of fixing. Duplicate of #28099.

**Closed by aknuds1** 2020-10-08 07:33 UTC
