### ISSUE TITLE
Service accounts: Chore: Move roles to main package

### ISSUE THREAD

**Issue by donomii** [grafana/grafana#43209] opened 2021-12-16 13:30 UTC
Consider moving roles into main package in pkg/services/serviceaccounts/manager/roles.go

from https://github.com/grafana/grafana/pull/42659/files/4cac308ad9e16f266fc58d00adb6059ccdd6d505#r769459699

**Comment by Jguer** [comment] 2022-03-04 15:44
API keys roles have been moved in https://github.com/grafana/grafana/pull/46255.

This becomes a duplicate of https://github.com/grafana/grafana-enterprise/issues/2979

**Closed by Jguer** 2022-03-04 15:44 UTC
Labels: type/refactor
