### ISSUE TITLE
Unable to use spaces when searching for values in the template variable search box.

### ISSUE THREAD

**Issue by Grrrolf** [grafana/grafana#30275] opened 2021-01-14 09:48 UTC
**What happened**:
I cannot enter a space in the search field for the template variables. Instead, when pressing space, it selects the top result in the list of values.

**What you expected to happen**:
That I can enter a space to finish searching for the correct variable in a long list of variables/values which contain spaces.

**How to reproduce it (as minimally and precisely as possible)**:
![no_spaces_in_filter](https://user-images.githubusercontent.com/10052794/104574043-e2126f80-5655-11eb-9479-842e47052284.gif)

**Anything else we need to know?**:
This issue was fixed in this ticket: https://github.com/grafana/grafana/issues/23825 for Grafana 7.0.  However, it is back in grafana 7.3.6. I have not tested any Grafana version > 7.0 and < 7.3.6. 

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: None
- OS Grafana is installed on: msft windows os 10
- User OS & Browser: msft windows 10 & google chrome and firefox
- Grafana plugins: default plugins
- Others:

**Comment by torkelo** [comment] 2021-01-14 12:32
duplicate of https://github.com/grafana/grafana/issues/28848

**Closed by torkelo** 2021-01-14 12:32 UTC
