### ISSUE TITLE
Graph: Improve IEC bytes grid ticks / intervals 

### ISSUE THREAD

**Issue by nixikanius** [grafana/grafana#19971] opened 2019-10-23 13:53 UTC
**What would you like to be added**:

I would like to propose to make grid intervals of graphs more human-readable that it could be now (Grafana 6.4.3):

![Screenshot 2019-10-23 16 13 32](https://user-images.githubusercontent.com/142733/67397053-4ceb0d00-f5b1-11e9-8ed5-d8be1c561ad9.png)
![Screenshot 2019-10-23 16 12 35](https://user-images.githubusercontent.com/142733/67397068-51172a80-f5b1-11e9-9c7f-b2e597235105.png)

You could see, that the grid of the graphs is divided into intervals of 93 GiB and 9 GiB respectively. To improve the analysis of graphs it would be much better to divide the grid only into round intervals of values (e.g., 1, 2, 5, etc.).

**Why is this needed**:

If the grid of a graph is divided into round intervals, a graph could be analyzed much easier than a graph with the grid divided into intervals of random values. By easying the analysis I mean an easying determination of a half or a quarter of a grid interval.

For example, it's much easy to divide 1, 2 or 5 by two or four than to divide 93 or 9 from my examples. And even if you could divide 93 or 9, it's not easy to add the half or the quarter of interval to the second or the third grid line value.

**Comment by torkelo** [comment] 2019-10-24 05:58
There already is this logic in place, but it does not work when the unit is not metric (base 10) value. So if you switch to metric bytes unit it will be even nice intervals between grid units.

**Comment by nixikanius** [comment] 2019-10-24 06:07
The unit settings for both graphs in my examples are the same and they are already switched to bytes:

![image](https://user-images.githubusercontent.com/142733/67457941-a6991900-f63d-11e9-91e3-d78339013072.png)

**Comment by Berbe** [comment] 2020-11-05 09:16
Duplicate of #8957?

**Comment by pkolyvas** [comment] 2021-07-26 16:40
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Closed by pkolyvas** 2021-07-26 16:40 UTC
Labels: area/panel/graph, type/feature-request
