### ISSUE TITLE
Wrong policy deleted when deleting a notification policy after activation of unified alerting 

### ISSUE THREAD

**Issue by magleg-trustly** [grafana/grafana#49391] opened 2022-05-23 10:30 UTC
**What happened**:
After activating Unified alerting, modifying Notification policies in the GUI does not work as expected.
In https://grafana-server/alerting/routes there's a list of migrated policies. Deleting any of these 
(or any newly created ones) always results in the last one in the list being deleted.

**What you expected to happen**:
The policy you wish to delete gets deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://grafana-server/alerting/routes
Create New policy
Set matcher test = test1
Set a contact point and save.

Create New policy
Set matcher test = test2
Set a contact point and save.

The last two policies in the list are now
test = test1
test = test2

Now delete the policy test = test1. 
Expected behaviour is that the policy is deleted.
Actual behaviour: The last policy in the list is deleted (in this case, test=test2)

**Anything else we need to know?**:
Tested with both 8.5.0 and 8.5.3, same result.
Also, I deleted all alerts and notification policies before activating Unified alerting, same result.

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: Prometheus 2.31.1
- OS Grafana is installed on: Ubuntu 18.04.6 LTS
- User OS & Browser: Macos Monterey, Safari, Chrome
- Grafana plugins:
- Others:

**Comment by townsendduong** [comment] 2022-05-24 00:18
Duplicate of #48472. A fix has already been created, but it may not have made it into the 8.5.3 release. I see that the 8.5.3 milestone has been renamed to 8.5.4.

**Closed** 2022-05-31 21:05 UTC
