### ISSUE TITLE
`range` attribute not set on table panel

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#48695] opened 2022-05-04 11:52 UTC
**What happened**:

Table panels show an error: `Query data error`

**What you expected to happen**:

I didn't expect an error.

**How to reproduce it (as minimally and precisely as possible)**:

These dashboards are read from disk and not created through the UI, therefor they get a dashboard JSON that is not created with this instance.

The Prometheus queries in these dashboard panels have `format: table` and `instant: true` set, the value for attribute `range` is unset.

After toggling back and forth the 'Type' from `range` to `instant` in the GUI, the panel renders, the dashboard JSON now also shows that `range` is set to the opposite value of  `instant`.

![2022-05-04-115228_1110x396_scrot](https://user-images.githubusercontent.com/3349855/166675498-daaa8994-d6e6-4006-8a5d-946b4f332356.png)

**Anything else we need to know?**:

Preliminary conclusion: the `range` attribute is required on the table panel in some cases but not set when loading a dashboard from disk.

**Environment**:
- Grafana version: Grafana v8.5.0 (6134e3cf35)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Linux / Chrome-derivate
- Grafana plugins: n/a
- Others: n/a

**Comment by Duologic** [comment] 2022-05-04 13:13
Did a bit more digging, turns out Grafana doesn't like that the value of `instant` is a string, not a boolean. This worked before, not sure if this should be a considered a regression?

**Comment by zoltanbedi** [comment] 2023-03-10 14:19
I'm going to remove the table panel label as this seems like a Prometheus issue.

**Comment by itsmylife** [comment] 2024-01-21 15:14
I am guessing this was happening when prometheus was a frontend data source. As a backend data source it was expecting those values would be boolean. So this is happening. I can easily reproduce this by setting a instant or range value as a string `"true"`. UI will keep working because `"true"` a non-empty string is a true boolean. But golang doesn't like that :) 
Having string values for `instant` and `range` would have been a mistake, maybe. So I am closing this. The solution would be setting those values as boolean manually.

**Closed by itsmylife** 2024-01-21 15:14 UTC
Labels: datasource/Prometheus, needs investigation
