### ISSUE TITLE
How can i get the time range in templating 

### ISSUE THREAD

**Issue by xnchen1995** [grafana/grafana#9786] opened 2017-11-04 04:17 UTC
i'm using grafana plugin(simpleJson) to make my api  access grafana .but now i don't know how to get the time range in templating module ,because My templating variables are related to time (such as using variable $time or $timeFilter...),please tell me how to do

**Comment by torkelo** [comment] 2017-11-04 07:04
$timeFilter is not available for simple json data source, its specific to some data source implementations. 

closing as dupe of
https://github.com/grafana/grafana/issues/1909

**Closed by torkelo** 2017-11-04 07:04 UTC
