### ISSUE TITLE
Unable to filter metric values in prometheus query explorer

### ISSUE THREAD

**Issue by aesher9o1** [grafana/grafana#69876] opened 2023-06-10 04:32 UTC
### 
# What went wrong?

**What happened**:
Not able to filter metrics by name

**What did you expect to happen**:
Below GIF contains screen recording of grafana 8 (left) vs 9.5.3 (right). On grafana 8 i am able to filter metric as i type locally, while grafana 9.5.3 makes an API call to fetch metrics corresponding to the given filter.

![bug](https://github.com/grafana/grafana/assets/29084675/1046a6c6-f77e-4f3b-af4d-bbe4ebcba186)

### 
# How do we reproduce it?

- Open metric Explore
- Filter for metrics

### 
# What Grafana version are you using?

v9.5.3

### 
### Grafana Platform?

Kubernetes

### User's OS?

macOS 13.4

### User's Browser?

Chrome

### Is this a Regression?

Yes

### Are Datasources involved?

Victoria Metrics

**Comment by gtk-grafana** [comment] 2023-06-12 18:08
@aesher9o1 Thanks for submitting this!
VictoriaMetrics is not officially supported by the Prometheus data source, you might get better behavior with the [VictoriaMetrics plugin](https://github.com/VictoriaMetrics/grafana-datasource).

Additional context that might not be relevant to you: this was a change of behavior starting in Grafana 9.2.5, which was introduced because some users had hundreds of thousands to millions of labels/metrics, and this was causing components to be unresponsive and crash. Our initial solution was to limit the number of results that can be rendered, and to query the backend on auto-complete, which is what is happening in the video on the right hand side, which I expect to be breaking because of the differences between the Prometheus and VictoriaMetrics API.

In Grafana 10 we're releasing new UI to select metrics that allows the user to choose if they want to query everything in the browser and then search on the browser, or to query the backend directly with user provided regex/string.
This functionality can be previewed in g10 with the `prometheusMetricEncyclopedia` feature flag. Feedback is welcome!

Closing, but please re-open if you can reproduce with a Prometheus compatible API.

**Closed by gtk-grafana** 2023-06-12 18:08 UTC
Labels: datasource/Prometheus
