### ISSUE TITLE
Add support for Alerts on Gauge panel

### ISSUE THREAD

**Issue by Trebla7th** [grafana/grafana#17744] opened 2019-06-24 20:51 UTC
**What would you like to be added**:
Add support to send alerts for a gauge panel based on thresholds.  When visualization of a gauge panel is changed to graph, the alert tab appears, when visualized as a gauge, the alert tab disappears.  Given that it's the same backing data, seems like alert support could be easily added here.  

I apologize if this is already possible, the documentation doesn't describe any alerting differences based on visualization and I couldn't find any information on it.

**Why is this needed**:
Currently we use gauge panels as a quick look to monitor many stats across our applications, would be nice to be able to set up alerts on these panels.  Would be nice to set alerts based on the thresholds defined in the gauge, or just based on the underlying data.

**Comment by marefr** [comment] 2019-06-25 05:45
Duplicate of #6983

**Closed by marefr** 2019-06-25 05:45 UTC
