### ISSUE TITLE
Refactor DB backend to make individual panels distinct objects

### ISSUE THREAD

**Issue by davidheitman** [grafana/grafana#19141] opened 2019-09-16 17:15 UTC
I would like to see a refactoring of the backend DB schema to allow individual panels to exist as objects independent from dashboards, and to be referenced individually.

Currently, a dashboard is a single json blob of all panels within that dashboard.  I would like to see this refactored to have a "panel" table with a FK that can be referenced by the "dashboard" table, so a dashboard ceases to be a single large json blob, and becomes a series of references to panel definitions.

This has numerous advantages.  For one, a single panel definition can be referenced in multiple dashboards.  Take, for example, the case of using Grafana to monitor multiple internal systems.  One might desire to have a dashboard that displays vital stats for a stream processing database, and a separate dashboard that displays vital stats for a database to which the processed results are committed.  For either dashboard, a panel describing the lag between produced and consumed data points is a relevant graph.  The current monolithic dashboard definitions, however, require defining, and therefore maintaining, this same panel in two places.  If the panel was an independent object, then the same panel could be referenced in both graphs, and simply maintained in a single location.

In addition to the possible functional and administrative benefits, this would create a clear and simple logical separation which I think would aid in understanding the basic data structures that drive Grafana.  Panels display data points, dashboards display panels, so it makes sense for panels to be their own independent objects, referenced by dashboards.

**Comment by torkelo** [comment] 2019-09-16 18:41
duplicate of https://github.com/grafana/grafana/issues/1803

**Closed by torkelo** 2019-09-16 18:41 UTC
