### ISSUE TITLE
New table panel cannot override timestamp format used as terms

### ISSUE THREAD

**Issue by gadol** [grafana/grafana#26540] opened 2020-07-23 07:23 UTC
After converting few of my tables to the new table panel I found out that then the query groups by timestamp from elastic there is no way to change its date/time format.

Using the old table panel you could set the unit to custom date time and set your own format, with the new one when using override over the column, setting the unit the *Date & Time* (no matter which format) it doesn't do anything.

When changing the group by clause from `terms` to `date histogram` the Unit works, but in my specific case I need to use it as a term.

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: Elastic 6.6.0
- OS Grafana is installed on: Linux (docker image)
- User OS & Browser: Windows 10 and Firefox (but doesn't matter for the issue)
- Grafana plugins: Table Plugin (new)

**Comment by torkelo** [comment] 2020-07-24 05:39
duplicate of https://github.com/grafana/grafana/issues/25884

**Closed by torkelo** 2020-07-24 05:39 UTC
