### ISSUE TITLE
[Feature Request] switch to hide the grafana control bar from scripted dashboards

### ISSUE THREAD

**Issue by dominicnicholas** [grafana/grafana#4830] opened 2016-04-27 12:47 UTC
Hi,

Can the top Grafana control bar (below) be hidden when using a scripted dashboard ? 

![image](https://cloud.githubusercontent.com/assets/515282/14852439/444c0aae-0c54-11e6-9a30-dc651bc044aa.png)

If not, please can this be a feature request ? For example, have a dashboard property like hideGrafanaControlBar : true/false.

Grafana 3 beta 5 / OpenTSDB 2.2 / CentOS 6.7

Thanks!

**Comment by torkelo** [comment] 2016-04-27 12:54
dupe of https://github.com/grafana/grafana/issues/3350

**Closed by torkelo** 2016-04-27 12:54 UTC
