### ISSUE TITLE
[Dashboard - Settings ] Dashboards: Cannot change folder and save. No changes detected.

### ISSUE THREAD

**Issue by droberin** [grafana/grafana#59293] opened 2022-11-24 12:43 UTC
**What happened**:
Edited an existing dashboard in no folder (General) and set it to an existing folder, saving is not possible as UI detects no changes.

**What you expected to happen**:
Saving dashboard into desired folder

**How to reproduce it (as minimally and precisely as possible)**:
- Open existing dashboard which is in no folder (General)
- Set an existing folder through Dashboard Settings -> General -> Folder
- Click in "Save dashboard" button or go back to dashboard main view and use icon (same effect)
- Find saving is unavailable (msg: No changes to save).

**Environment**:
- Grafana version: Grafana 9.2.1-cab7049
- User OS & Browser: macOS, Google Chrome

**Comment by droberin** [comment] 2022-11-24 14:25
adding any other change, such as dashboard visualisation (new row), would lead into the proper mapping of the dashboard in the desired folder

**Comment by usmangt** [comment] 2022-11-24 15:17
Hi @droberin,

Thanks for opening this issue.

I am trying to reproduce this by following your steps but I cannot understand step#2.

Can you please share some screenshots or a small screencast so that we can also see it visually and then try to reproduce it?


Thanks

**Comment by droberin** [comment] 2022-11-24 16:15
Hi, @usmangt ,

I'll try clarifying step#2: click on gear icon (Dashboard Settings), and now in section General (default when opening settings) look for Field "Folder", which should be blank because it was never set when previously saved the dashboard :)
Now set a folder for this dashboard and then try saving the dashboard :)

**Comment by usmangt** [comment] 2022-12-22 22:16
Hi @droberin 

Thanks for the details. Based on your steps of reproduction, I was also able to reproduce it on my test machine.

The Blue button on the top right "Save Dashboard" does not work regardless if I tye a comment/message as it never appears.

Instead the "Save As" button works which is a **workaround** once I change the Folder from General to something else.

Also, in my test case, the default selection of the Folder is set of General instead of null/empty but still able to reproduce it.

I will ask our team to have a look into this case so that they can provide more information.

**Comment by axelavargas** [comment] 2022-12-23 12:38
Hey @droberin 👋🏾 ,

Thanks for reporting this issue. I am also able to reproduce it (🐛.)  In addition to @usmangt workaround, you can also manage dashboards using the "Dashboards --> Browse" and perform actions such as moving the dashboard to another folder there. 


https://user-images.githubusercontent.com/239999/209336845-ad5da233-142c-4629-b473-a6030120dd99.mp4

In the meantime, I will move this issue for further prioritization.

Thank you 🙏🏾

**Comment by joshhunt** [comment] 2023-06-16 11:03
@axelavargas For further clarification, this issue happens regardless of whether the folder is or was in the General folder. You're unable to save the dashboard if the only change you've made to the dashboard model is changing the folder (I _suspect_ if the only changes you've made are to `dashboard.meta` then the save drawer won't let you save).

1. Create a new dashboard and save it into "Folder A"
2. Refresh the page
3. Go to Dashboard Settings and change the folder to "Folder B"
4. Click "Save dashboard"
5. Observe that the Save button is greyed out.

**Comment by natellium** [comment] 2024-02-21 10:17
Hey there, this fix will be included in the next Grafana major (v11), since it will need the new system of dashboards based on Scenes to work. Related PR https://github.com/grafana/grafana/pull/81958

**Closed** 2024-04-15 09:11 UTC
Labels: type/bug, area/dashboard, team/grafana-dashboards, prio/future
