### ISSUE TITLE
Legends repeat as many times as number of active queries

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#28606] opened 2020-10-28 16:07 UTC
**What happened**: Each legend entry gets repeated as many times as number of active queries.

**What you expected to happen**: Legend to be unique.

**How to reproduce it (as minimally and precisely as possible)**: This has been observed using CloudWatch datasource when using expressions:
![grafana-7.3.0-repeated-legend GIF](https://user-images.githubusercontent.com/15344273/97462324-7c57f680-1936-11eb-8c67-18ca9c8265ca.gif)

**Anything else we need to know?**: Works as expected in Grafana 7.2.2

**Environment**:
- Grafana version: 7.3.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: linux (docker)
- User OS & Browser: windows 10 / chrome 86
- Grafana plugins: n/a
- Others: using official grafana docker image

**Comment by hugohaggmark** [comment] 2020-10-29 05:59
Related to #28301

**Comment by wbrowne** [comment] 2020-10-29 10:02
Thanks for creating this issue @salavessa. It seems to be a /duplicate of #28301 which is where we're tracking updates so will close this.

**Closed** 2020-10-29 10:03 UTC
Labels: datasource/CloudWatch, needs investigation, type/duplicate
