### ISSUE TITLE
Loki Datasource: Dashboard variable of type: Query has no Query-type: Query Result

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82693] opened 2024-02-15 17:55 UTC
### Discussed in https://github.com/grafana/grafana/discussions/68516

<div type='discussions-op-text'>

<sup>Originally posted by **samjewell** May 16, 2023</sup>
**What happened**:

I'm building a dashboard where I need to use the results of a Logs query as the input to a Metrics query.

Specifically there are Log-lines which identify which users are hitting a sad-path in the application. I need to join these results together with a dataset present in a metrics datasource. Unfortunately the metrics datasource is so large that I can only get results back by passing the user-ids as part of the query itself. Hence I need to know the user-ids before trying to render the panel, so I need to gather those IDs in a dashboard-variable (because these are evaluated first)

Prometheus datasource offers this option:

![image](https://github.com/grafana/grafana/assets/2903904/4721f7af-63c0-4450-84e9-1efdee838544)

But Loki datasource doesn't:

![image](https://github.com/grafana/grafana/assets/2903904/9d397d61-28ea-4aea-af37-24cdf62e7676)

And the data that I need isn't present in either "label names" or "label values"

**What did you expect to happen**:

Query-type: Query-result to be present in the dashboard-variables config for Loki
</div>

**Comment by svennergr** [comment] 2024-02-20 22:12
Duplicate of https://github.com/grafana/grafana/issues/76612

**Closed** 2024-02-20 22:12 UTC
Labels: type/feature-request, datasource/Loki, migrated-discussions
