### ISSUE TITLE
Logs get deduped when None dedupe strategy is chosen

### ISSUE THREAD

**Issue by alanhe** [grafana/grafana#29255] opened 2020-11-20 05:17 UTC
**What happened**:
In the Explore view, for the Loki datasource, dedup is run even when **None** dedup strategy is set explicitly.

**What you expected to happen**:
I want to see the many duplicated lines as they are in None dedup mode.

**How to reproduce it (as minimally and precisely as possible)**:
Mock two log lines with the same ts & line values as the response of a Loki's `/loki/api/v1/query_range` query, only one line is shown in the logs panel.

**Anything else we need to know?**:
Please check that the `deduplicatedLogRows()` method is called disregard the chosen dedupe strategy:

https://github.com/grafana/grafana/blob/c94e8e61a945364f31aff6f56a9201bc1937e0a7/public/app/core/logs_model.ts#L396

In the Loki plugin, the identical lines are hashed to the same uid, and thus get deduped:

https://github.com/grafana/grafana/blob/c94e8e61a945364f31aff6f56a9201bc1937e0a7/public/app/plugins/datasource/loki/result_transformer.ts#L149-L151

**Environment**:
- Grafana version: Grafana v7.3.3 (2489dc4d3a)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment] 2020-11-20 21:46
/duplicate of https://github.com/grafana/grafana/issues/29255

**Closed** 2020-11-21 09:13 UTC
Labels: area/explore, datasource/Loki, needs investigation, type/duplicate

**Comment by alanhe** [comment] 2020-11-21 12:48
@ivanahuckova   Could you please share the link of the duplicated issue?

**Comment by ivanahuckova** [comment] 2020-11-21 14:58
Yes! I see that I added this issue instead of https://github.com/grafana/grafana/issues/26714 as a the original one. 🙈

**Comment by alanhe** [comment] 2020-11-22 05:43
thx~
