### ISSUE TITLE
Grafana Login with Azure Managed Identity or Federate Credentials 

### ISSUE THREAD

**Issue by jasidhu** [grafana/grafana#91606] opened 2024-08-06 20:55 UTC
**Why is this needed**:

The Grafana login still requires a ClientID & Secret. Requesting a feature to add support for Azure Managed Identity or Federate Credentials. It would help in avoiding the manual effort needed for secret rotation after expiry or credential leak.

**What would you like to be added**:

Option to authenticate using Azure Managed Identity or Federate Credentials.

**Who is this feature for?**

Grafana dashboard users who utilize Azure AD for authentication.

**Comment by aangelisc** [comment] 2024-09-06 15:47
Hi @jasidhu,

I'm unsure what you mean, we already support both [managed identity](https://grafana.com/docs/grafana/latest/datasources/azure-monitor/#configure-managed-identity) and [workload identity](https://grafana.com/docs/grafana/latest/datasources/azure-monitor/#configure-workload-identity) credentials in the Azure Monitor data source.

Let us know if this isn't what you're looking for 😊

**Comment by jasidhu** [comment] 2024-09-11 20:55
> Hi [@jasidhu](https://github.com/jasidhu),
> 
> I'm unsure what you mean, we already support both [managed identity](https://grafana.com/docs/grafana/latest/datasources/azure-monitor/#configure-managed-identity) and [workload identity](https://grafana.com/docs/grafana/latest/datasources/azure-monitor/#configure-workload-identity) credentials in the Azure Monitor data source.
> 
> Let us know if this isn't what you're looking for 😊

Hi, I created this feature request for main Grafana user login process from the browser. It still requires a ClientId & Secret for the setup.

Step #8 from this [document](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/#create-the-microsoft-entra-id-application).

**Comment by aangelisc** [comment] 2024-09-13 12:48
Hi @jasidhu, thank you for clarifying. Redirecting to the relevant team.

**Comment by taleena** [comment] 2024-09-23 15:31
Transferring some information and closing this as a duplicate of https://github.com/grafana/grafana/issues/78249. Please follow that one and add more context there as needed.

**Closed by taleena** 2024-09-23 15:31 UTC
Labels: type/feature-request, team/identity-access
