### ISSUE TITLE
Feature: clamp y-axis min and max

### ISSUE THREAD

**Issue by abursavich** [grafana/grafana#26597] opened 2020-07-24 23:34 UTC
**What would you like to be added**:

I would like an option to clamp the max and/or min y-axis value without specifying a fixed min or max value, which would allow the max and min to be automatically adjusted within that range (of the min-min and max-max).

Call it whatever you want: clamp max, max max, soft max, hard max, something completely different...

It can be a different field or a checkbox next to each current min and max.

**Why is this needed**:

Frequently, especially when dealing with percentages, I don't want to set the min and max (e.g. 0% and 100%), because I want the y-axis to be zoomed in when the elements are all clustered together (e.g. between 20% and 30%). However, I don't want the y-axis to extend beyond the valid values (e.g. 0% and 100%) when the elements are not clustered together (e.g. between 5% and 95%).

NO:
![Screen Shot 2020-07-24 at 4 22 33 PM](https://user-images.githubusercontent.com/1512418/88442618-0f2e4580-cdca-11ea-8471-c609dddc9053.png)

YES:
![Screen Shot 2020-07-24 at 4 25 33 PM](https://user-images.githubusercontent.com/1512418/88442705-5ae0ef00-cdca-11ea-8e6c-4429e3a4dfe7.png)

NO:
![Screen Shot 2020-07-24 at 4 28 04 PM](https://user-images.githubusercontent.com/1512418/88442808-bc08c280-cdca-11ea-8cb1-3f6c49380149.png)

YES:
![Screen Shot 2020-07-24 at 4 28 22 PM](https://user-images.githubusercontent.com/1512418/88442820-c460fd80-cdca-11ea-8142-789a1900c116.png)

**Comment by torkelo** [comment] 2020-07-25 17:42
duplicate of https://github.com/grafana/grafana/issues/979

**Closed by torkelo** 2020-07-25 17:42 UTC
