### ISSUE TITLE
Time Regions in Local Timezone or with Variable support

### ISSUE THREAD

**Issue by danieldonoghue** [grafana/grafana#26448] opened 2020-07-20 07:20 UTC
**What would you like to be added**:

Time regions should be assumed to be in the dashboard configured timezone and not in UTC.

-- or --

Time regions should be able to use a start and end time variable so that I can set them in one place for the entire dashboard.

**Why is this needed**:

If time regions are in UTC, I have to change hundreds on panels twice a year. it also doesn't make sense for this field to be in UTC when everything else is in the configured time zone. If they must be in UTC, let me set them using a constant variable so I only have one place to change twice a year.

**Comment by torkelo** [comment] 2020-07-20 08:24
duplicate of https://github.com/grafana/grafana/issues/14400

**Closed by torkelo** 2020-07-20 08:24 UTC
Labels: type/feature-request
