### ISSUE TITLE
Docs: Fix documentation regarding datasource SSL/TLS certificates support

### ISSUE THREAD

**Issue by edwinsc** [grafana/grafana#19574] opened 2019-10-02 12:51 UTC
**What happened**: Configured Postgres datasource, as documented in https://grafana.com/docs/administration/provisioning/#datasources, using certificates and key to authenticate instead of user and password reports error: "pq: connection requires a valid client certificate". The connection from the machine running Grafana to the Postgres datasource db works fine using command line

**What you expected to happen**: To have Postgres working as a datasource, but using certificates and key to authenticate instead of user and password

**How to reproduce it (as minimally and precisely as possible)**: Have a Postgres datasource configured to be accessible by key and certificates. A working command line to access Postgres would be similar to:
$ psql 'host=db.url dbname=db user=db-user sslcert=user-cert.cer sslkey=user.key sslrootcert=cert-chain.pem sslmode=verify-full'

The Grafana configuration (/etc/grafana/provisioning/datasources/db.yaml) for the datasource would be:
```apiVersion: 1
datasources:
  - name: db
    type: postgres
    url: db.url:5432
    database: db
    user: db-user
    secureJsonData:
      tlsCACert: |
        -----BEGIN CERTIFICATE-----
        cert1 that is part of cert-chain.pem
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        validation chain 1
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        validation chain 2
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        validation chain 3
        -----END CERTIFICATE-----
      tlsClientCert: |
        -----BEGIN CERTIFICATE-----
        contents of user-cert.cer
        -----END CERTIFICATE-----
      tlsClientKey: |
        -----BEGIN PRIVATE KEY-----
        contents of user.key
        -----END PRIVATE KEY-----
    jsonData:
      sslmode: "verify-full" # disable/require/verify-ca/verify-full
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
      postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
```

**Anything else we need to know?**: Configuring Grafana to work in debug mode I see the following log line:
Oct 02 12:29:47 server grafana-server[26126]: t=2019-10-02T12:29:47+0000 lvl=dbug msg=getEngine logger=tsdb.postgres connection="postgres://user:@db.url:5432/db?sslmode=verify-full"
I would expect something like:
Oct 02 12:29:47 server grafana-server[26126]: t=2019-10-02T12:29:47+0000 lvl=dbug msg=getEngine logger=tsdb.postgres connection="postgres://user:@db.url:5432?sslmode=verify-full&sslcert=tlsClientCert&sslkey=tlsClientKey&sslrootcert=tlsCACert"

**Environment**:
- Grafana version: Grafana v5.4.3 (6539180)
- Data source type & version: Postgres 10.7
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Doesn't make any difference
- Grafana plugins: Table panel used for testing access to db with a simple "select 1"

**Comment by hugohaggmark** [comment] 2019-10-03 07:29
Hi @edwinsc have you looked at this https://community.grafana.com/t/what-format-should-tls-certs-be-stored-in-our-yaml-for-datasource-provisioning/7779/3? Hope that can help you.

**Comment by edwinsc** [comment] 2019-10-03 10:50
I read the mentioned doc and I used a YAML parser to make sure the file was correct. When the file is not correctly parsed Grafana fails to start. 
So this is not a problem in the configuration file. It seems that Grafana is not sending the certificate a d key to the Postgres datasource. 
Because of this, I created this bug report.

**Comment by edwinsc** [comment] 2019-10-09 11:43
It seems this was fixed in newer versions of Grafana.
https://github.com/grafana/grafana/pull/14456/commits/33c176e56cc9e69f49664993b7f8f62d77a412c5
I will try to upgrade to the latest version.

**Comment by edwinsc** [comment] 2019-10-10 13:21
I installed Grafana v6.4.2 (443a0ba), but the problem persists, the datasource file is parsed correctly, but I still get the error message "pq: connection requires a valid client certificate"

I also tried to provide paths for the certificates using :
```
...
    jsonData:
      sslmode: "verify-full" # disable/require/verify-ca/verify-full
      sslrootcert: "/path/to/file/cert-chain.pem"
      sslcert: "/path/to/file/user-cert.cer"
      sslkey: "/path/to/file/user.key"
...
```

or using the field names for used by Grafana database:
```
...
    jsonData:
      sslmode: "verify-full" # disable/require/verify-ca/verify-full
      ca_cert_path: "/path/to/file/cert-chain.pem"
      client_cert_path: "/path/to/file/user-cert.cer"
      client_key_path: "/path/to/file/user.key"
...
```

But for all configs, the log line remains similar (I had to change Grafana mode to development to get this line log on 6.4.2):
```
t=2019-10-10T13:06:38+0000 lvl=dbug msg=getEngine logger=tsdb.postgres connection="postgres://user:@db.url:5432/db?sslmode=verify-full"
```

How do I enable additional debugging messages to understand why Grafana is not trying to use certs?

**Comment by marefr** [comment] 2019-10-10 14:08
Duplicate of #14455

**Comment by edwinsc** [comment] 2019-10-10 14:11
@marefr Thanks for the clarification. 

So if I understand correctly this is not possible to do at the moment, not even in version 6.4.2, right?

**Comment by marefr** [comment] 2019-10-10 14:12
Seems like our documentation regarding TLS/SSL is lacking for both  https://grafana.com/docs/features/datasources/postgres/ which is not supported and https://grafana.com/docs/features/datasources/mysql/ which have the support. Also wrong provisioning documentation here https://grafana.com/docs/administration/provisioning/#datasources which implies that all datasources supports `tlsAuth` settings which is not true.

**Comment by edwinsc** [comment] 2019-10-10 15:06
https://github.com/grafana/grafana/pull/14456/commits/33c176e56cc9e69f49664993b7f8f62d77a412c5 seems to add the support for adding key/value entries for psql client string certificate values to the connection string of a postgres datasource. Was this code abandoned?

**Comment by marefr** [comment] 2019-10-10 15:28
Not sure where you found that commit. It's not in master where it looks like this: https://github.com/grafana/grafana/blob/master/pkg/tsdb/postgres/postgres.go#L51

**Comment by edwinsc** [comment] 2019-10-10 15:53
I found it by trying to find a way to solve my issue. :-) 
It seems a simple fix, but I don't know if would create a cascade of changes.

**Comment by marefr** [comment] 2019-10-14 17:05
@edwinsc those changes doesn't seem to be support by the pq library, see https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters. It supports to configure path on disk where certificates are stored.

**Comment by edwinsc** [comment] 2019-10-15 08:32
As seen in my previous comment https://github.com/grafana/grafana/issues/19574#issuecomment-540577474, I tried to use the parameters as supported by pq library. They are also the same ones supported by psql, as I suggested in my initial comment.

The YAML for a postgres datasource would include:
```
...
    jsonData:
      sslmode: "verify-full" # disable/require/verify-ca/verify-full
      sslrootcert: "/path/to/file/cert-chain.pem"
      sslcert: "/path/to/file/user-cert.cer"
      sslkey: "/path/to/file/user.key"
...
```

psql command:
```
$ psql 'host=db.url dbname=db user=db-user sslcert=user-cert.cer sslkey=user.key sslrootcert=cert-chain.pem sslmode=verify-full'
```

It seems to be necessary to edit the YAML parser to get these additional configs and if the config is not 'sslmode: "disable"', add the other fields to the connection string, right?

**Comment by marefr** [comment] 2019-10-15 09:23
For us to approve a PR solving #14455 we expect to be able to configure this in UI and in provisioning. 
![image](https://user-images.githubusercontent.com/1668778/66817992-eaed3080-ef3c-11e9-94eb-ec2dba384cd1.png)

Backend wise the following code needs to be changed:
https://github.com/grafana/grafana/blob/b848276fb828f650b11d2a554ead23b5292c9fa7/pkg/tsdb/postgres/postgres.go#L45-L55

Frontend wise you'll need to make changes here:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/partials/config.html

Naming of `jsonData` properties should end with `File` or `Path` to denote they're referring to file paths and not the actual cert contents.

**Comment by edwinsc** [comment] 2019-10-17 10:16
@marefr I forked the code based on master and, to the best of my knowledge, I did the changes to the two files you pointed to support sslmode "verify-full":
https://github.com/edwinsc/grafana/tree/%2314455

Unfortunately I don't have the resources to test the changes and debug problems. I hope that these small changes can be useful somehow.

If you want me to merge the changes despite the lack of testing, just let me know.

**Comment by oddlittlebird** [comment] 2019-12-23 17:27
What changes need to be made to the documentation to address this?

**Comment by edwinsc** [comment] 2020-01-04 14:59
The change needed to the docs is that different SQL datasources have different configuration options.
For example, Postgres datasource has no support for connections with certificates, MySQL has.
https://github.com/grafana/grafana/pull/21341 will add certificate support to Postgres datasource, but in a different way then supported by MySQL.

**Comment by ryankurte** [comment] 2020-01-06 01:48
In working on this I did wonder whether it would be sensible to raise the three _standard_ tls files (root cert, client cert, client key) to be part of the common configuration (rather than datasource-specific json data). 

The requirement for those files (or the data from them, which is easy to read out in datastore driver) is the same for pretty much any TLS connection, and loading them from files is much more convenient for configuration management than needing to inject them into json files.

**Comment by marefr** [comment] 2020-01-10 09:48
@ryankurte HTTP datasources use a common HTTP configuration which include ssl/tls. Different data source types have different needs and I think it's hard to make this part of common configuration.

**Comment by marefr** [comment] 2021-11-02 09:16
Tricky to document #40163, but we're working on it.

For now opened #41182 for adding proper documentation of SSL/TLS options for MySQL.

**Closed** 2021-11-08 17:59 UTC
Labels: type/docs, datasource/MySQL, datasource/Postgres, area/provisioning, datasource/MSSQL
