### ISSUE TITLE
Update v7 to 8 - websocket error

### ISSUE THREAD

**Issue by bailsaway** [grafana/grafana#36614] opened 2021-07-09 15:04 UTC
**What happened**:
- Upgraded to v8.0.5 by Debian package successfully for some of the new features in v8
- Previously running v7 fine with all AWS IAM permissions etc. 
- On login, no queries complete, even on Query Inspector: writing CloudWatch Insight queries, where I know there's data to be pulled (and it worked prior to upgrade) no logs are loaded at all
- Permissions denied in Ubuntu Terminal access log directory...
![Lambdas returning fine](https://user-images.githubusercontent.com/87194229/125098084-a3261980-e0ce-11eb-9887-6cc425f6617d.png)

Developer tools (Chrome & Safari) console repeats from successful login: 
[Error] WebSocket connection to 'ws://grafana._mydomain_.io:3000/api/live/ws' failed: Unexpected response code: 403

![infinite spin](https://user-images.githubusercontent.com/87194229/125098789-424b1100-e0cf-11eb-8d07-d86757b36be5.png)

**What you expected to happen**:
Logs to be pulled back and loaded as per dashboard preferences, or to error ;) 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
- Cleared cookies
- Rebooted instance
- Confirmed my Grafana IAM policy has all correct permissions
- Datasource access fine - lambda/log streams are being returned fine 

**Environment**: 
- Grafana version: 8.0.5
- Data source type & version: AWS Cloudwatch Logs 
- OS Grafana is installed on: AWS EC2 t2.Large Ubuntu
- User OS & Browser: MacOS Big Sur, Safari & Chrome
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment] 2021-07-09 15:49
Any proxy infront of Grafana that could block websocket requests?

**Comment by bailsaway** [comment] 2021-07-09 17:31
Hey. No proxies set. However, incase I've followed the update instructions wrong:
![Screenshot 2021-07-09 at 18 27 50](https://user-images.githubusercontent.com/87194229/125115827-c8715280-e0e3-11eb-8a1a-8349d3f5256d.png)

**Comment by FZambia** [comment] 2021-07-09 17:52
@bailsaway hello, try to set, replacing `mydomain` to your actual domain:

```
[server]
root_url = "ws://grafana.mydomain.io:3000/"
```

**Comment by bailsaway** [comment] 2021-07-09 17:58
Hey
I just wrote _mydomain_ for privacy purposes. As per screenshots, I've also blanked out the domain name, but rest assured I've got my actual domain name in there :) I'm really cross with myself as 7.3.7 was working perfectly and I updated as per good practice & for the new notification features...and have royally screwed it up!

**Comment by FZambia** [comment] 2021-07-09 18:02
> I just wrote mydomain for privacy purposes

I understand this, but you need to set `root_url` option to your public Grafana URL to make WebSocket connection work. Could you try setting root_url to your public URL? Or do you already have a proper public url set in `root_url` server option?

**Comment by bailsaway** [comment] 2021-07-09 18:37
@FZambia I think I see what you mean :) 
[server]
root_url =  "%(protocol)s://%(domain)s:%(http_port)s/

grafana.ini currently giving me permissions issues...
Will let you know when I've managed to change it :) Thanks :)

**Comment by bailsaway** [comment] 2021-07-13 21:40
Hi guys!
have uninstalled and reinstalled
didnt purge so maintained ini & db
have updated root_url as suggested:
 [server]
root_url = "%(protocol)s://%(domain)s:%(http_port)s/grafana
grafana-server starts fine; datasource access still fine

Logs immediately after successful login (actual domain replaced with "myDomain") and my IP replaced with "RedactedMyIP"
t=2021-07-13T21:28:09+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2021-07-13T21:28:10+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:10+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:11+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:11+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:14+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:14+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:16+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:16+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:18+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:18+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:20+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:20+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:25+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:25+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:37+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:37+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=
t=2021-07-13T21:28:53+0000 lvl=warn msg="Request Origin is not authorized" logger=live origin=http://grafana.mydomain.io:3000 appUrl=http://localhost:3000/ allowedOrigins=
t=2021-07-13T21:28:53+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=403 remote_addr=RedactedMyIP time_ms=0 size=10 referer=


Same Websocket error in Chrome (again, browsing history/cookies cleared):
WebSocket connection to 'ws://grafana.convenet.io:3000/api/live/ws' failed: 
value @ centrifuge.js:544
value @ centrifuge.js:986
(anonymous) @ centrifuge.js:702
centrifuge.js:544 WebSocket connection to 'ws://grafana.convenet.io:3000/api/live/ws' failed: 
value @ centrifuge.js:544
value @ centrifuge.js:986
(anonymous) @ centrifuge.js:702

Thanks again for your help!

**Comment by zoltanbedi** [comment] 2021-07-14 07:31
This is a duplicate of https://github.com/grafana/grafana/issues/35448
Please take a look at https://github.com/grafana/grafana/issues/35448#issuecomment-872224175 for possible solutions.

**Closed by zoltanbedi** 2021-07-14 07:31 UTC
Labels: area/live

**Comment by bailsaway** [comment] 2021-07-14 09:48
Can confirm issue is fixed this morning following the comment you linked to :)
Thanks all!!
