### ISSUE TITLE
Alert state is not changing, after shooting 1 alert.

### ISSUE THREAD

**Issue by Shipankar-Sarkar-Shipu** [grafana/grafana#38990] opened 2021-09-08 13:20 UTC
**What happened**: After updating Grafana 7 to 8, when I create a new alert, after a certain time the state is not changing. 
It is showing the error:"request handler failed to convert dataframe "" to plugins.DataTimeSeriesSlice: input frame is not recognized as a time series" and keep running alering phase. `As` a result I am not getting any more alert from that dashboard.

**What you expected to happen**: It should change to the "OK" state after a certain time referred to in my query.

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:  I am working with MYSQL DB. It was working fine before the update.
![Screenshot from 2021-09-08 19-12-13](https://user-images.githubusercontent.com/83423834/132516156-a5adef66-aa5f-46ee-9995-eeeff6e04d56.png)
![Screenshot from 2021-09-08 19-13-04](https://user-images.githubusercontent.com/83423834/132516181-12cc5927-412e-4ea6-8874-1e6844370a1a.png)

**Environment**: Running Grafana in Docker, DB is MySQL.
- Grafana version: 8.1
- Data source type & version: MySQL - 5.7
- OS Grafana is installed on: Docker
- User OS & Browser: Ubuntu, Chrome+Firefox
- Grafana plugins:
- Others: Posted in the community before: https://community.grafana.com/t/error-request-handler-failed-to-convert-dataframe-results-to-plugins-datatimeseriesslice-input-frame-is-not-recognized-as-a-time-series/50530?u=shipankar
My query:

`SELECT 
  $__timeGroupAlias(created_at,$__interval) ,p_id, count(*) as "log_count"
FROM Table
WHERE
  $__timeFilter(created_at,$__interval)  
  and Conditions
GROUP BY log
having aggregates
ORDER BY  $__timeGroup(created_at,$__interval) `

My Schema:
'id', 'bigint(20) unsigned', 'NO', 'PRI', NULL, 'auto_increment'
'p_id', 'int(10) unsigned', 'NO', 'MUL', NULL, ''
'log', 'varchar(255)', 'YES', '', NULL, ''
'created_at', 'timestamp', 'YES', '', NULL, ''

**Comment by marefr** [comment] 2021-09-09 10:17
Duplicate of #37528

**Comment by marefr** [comment] 2021-09-09 10:18
Fixed in v8.1.3

**Closed by marefr** 2021-09-09 10:18 UTC
Labels: type/bug, area/alerting, datasource/MySQL, area/alerting/legacy
