### ISSUE TITLE
Provisioned dashboards can never be deleted from GUI

### ISSUE THREAD

**Issue by yeplaa** [grafana/grafana#45003] opened 2022-02-07 15:52 UTC
**What happened**:

As indicated on https://github.com/grafana/grafana/issues/41085 , it's not possible to delete from GUI the provisioned dashboards. 
I must delete the dashboard from the container on removing directly the file into the /var/lib/grafana/dashboards/ path.

**What you expected to happen**:

i wish i could delete from the gui the dashboards added. 

Is there another solution or is there an evolution planned?

**Environment**:
Grafana version: 8.3.4
Data source type & version: none
OS Grafana is installed on: K8s . The https://github.com/grafana/helm-charts/tree/main/charts/grafana chart is used to deploy
Grafana plugins: none
Others: none

**Comment by zuchka** [comment] 2022-02-07 20:10
duplicate of https://github.com/grafana/grafana/issues/44900

@yeplaa, if you wish to file a feature request, the proper place to do so is in GitHub Discussions:

https://github.com/grafana/grafana/discussions

**Closed by zuchka** 2022-02-07 20:10 UTC
Labels: type/duplicate
