### ISSUE TITLE
ValueFormats: strings like "07E386" are formatted as numbers

### ISSUE THREAD

**Issue by rvdheij** [grafana/grafana#25520] opened 2020-06-10 19:37 UTC
**What happened**:
A table panel showing the result of an InfluxDB query is missing one of the series names. Other panels with the same query do show the series name.
![cpucount](https://user-images.githubusercontent.com/11174694/84309685-c47da480-ab60-11ea-9ca6-3881b5ad8a37.png)
The table display is missing the 3rd series name.
![query_inspector](https://user-images.githubusercontent.com/11174694/84309768-dcedbf00-ab60-11ea-8d10-391f5feefdcb.png)
I tried to pull open the query results to show the tag for the 3rd series.

**What you expected to happen**:
When I remove the alias $tag_seqnr the full series name shows in the table panel as well. Only when I use the $tag_seqnr alias, one of the entries disappears. I would be less surprised if the series name was missing for the series that was only available during part of the day.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Earlier today with just 3 series, this same entry was missing. I am suspicious that something believes this string with '07E386' may look like a huge floating point number... 

**Environment**:
- Grafana version: 6.4.2 (and reproduced with 7.0.0 as well)
- Data source type & version: InfluxDB 1.8.0
- OS Grafana is installed on: Linux on s390x
- User OS & Browser: RH Linux and Chrome 81.0.4044.138 (also FF 68.8.0esr) and Chrome 84.0.4103.61 on Win10
- Grafana plugins: no extra plugins beyond the standard set
- Others:

**Comment by hugohaggmark** [comment] 2020-10-28 11:06
Sorry for the super late response to this.

I've confirmed this on latest master cb965ce17740b567e1f7ea946778348cc77bfeff and @rvdheij is correct __`07E386`__ is transformed to __Infinity__ and depending on which table you use React or old Angular table this value will be displayed differently.

For the old Angular Panel this is where we end up:
https://github.com/grafana/grafana/blob/cb965ce17740b567e1f7ea946778348cc77bfeff/packages/grafana-data/src/valueFormats/valueFormats.ts#L125

And for the new React Panel this is where we end up:
https://github.com/grafana/grafana/blob/cb965ce17740b567e1f7ea946778348cc77bfeff/packages/grafana-data/src/valueFormats/valueFormats.ts#L49

This is kind of tricky to fix as __`isNaN("07E386")`__ returns __`false`__ , __`Number("07E386")`__ returns Infinity so I'm not sure how we could fix this.

To solve your specific issue @rvdheij you could make sure that the Metrics column style is string then this issue dissapears:
![image](https://user-images.githubusercontent.com/562238/97428096-caa8cd80-1915-11eb-8e61-9c1ba64be6ea.png)

**Comment by hugohaggmark** [comment] 2020-10-28 11:19
To replicate this issue:
1. Install the Grafana Static Plugin
2. Import [this dashboard](https://gist.github.com/hugohaggmark/bd348cb52e1463f15b7faaed60d1cbbe)
3. Notice how "07E386" is formatted in table
![image](https://user-images.githubusercontent.com/562238/97429453-bbc31a80-1917-11eb-90c4-53368cce3da3.png)

**Comment by rvdheij** [comment] 2020-10-28 19:09
Thank you for looking into this. I don't see how your bypass or circumvention would work as there are no options in the table display. The data I have is dynamic and comes out of InfluxDB. The tag values are strings by definition. This seems to be biting me in a few different places where tag values are handled as numbers.
Trying to recreate that table, I now don't seem able to exclude the time column and show just one row with the maximum per series...

**Comment by hugohaggmark** [comment] 2020-10-29 05:40
> Thank you for looking into this. I don't see how your bypass or circumvention would work as there are no options in the table display. The data I have is dynamic and comes out of InfluxDB. The tag values are strings by definition. This seems to be biting me in a few different places where tag values are handled as numbers.

This is where it can get a bit tricky and confusing because we upgraded the Table for 7.0 in Grafana so It kind of depends on which Table you have. If you can share the Panel JSON for your Table I can help out. If your JSON includes __`"type": "table-old"`__ then you're using the Old Table Panel otherwise your using the New Table Panel.

But basically both Tables assume numeric values by default so you need to tell Grafana that your tags should be treated as strings. Screenshots below are from latest master 5cded1d2cd:

__Old Table Panel__
1. Edit Panel
![image](https://user-images.githubusercontent.com/562238/97529276-d779ff80-19af-11eb-95d8-0d4816583f46.png)

2. Add column style
![image](https://user-images.githubusercontent.com/562238/97529363-0c865200-19b0-11eb-9c9c-2f309f6c8175.png)

3. Change name to Metric and choose String as type
![image](https://user-images.githubusercontent.com/562238/97529453-33448880-19b0-11eb-92fa-349f5cd1d59b.png)

__New Table Panel__

1. Edit panel
![image](https://user-images.githubusercontent.com/562238/97529632-9df5c400-19b0-11eb-851c-f917610540a9.png)

2. Add Field override
![image](https://user-images.githubusercontent.com/562238/97529748-d8f7f780-19b0-11eb-95cc-f0434ed6db29.png)

3. To hide the Time column add the Filter by Name Transformation
![image](https://user-images.githubusercontent.com/562238/97529826-093f9600-19b1-11eb-88a5-5de4c4ffc16d.png)


> Trying to recreate that table, I now don't seem able to exclude the time column and show just one row with the maximum per series...

The repro steps are for anyone internally that is assigned to fix this, so the data format is a Table so you can't perform any Table aggregations in the Old Table Panel. But if you're using InfluxDB then it should be possible to do Table aggregations in the Old Table Panel. For intstructions on how to hide column in the New Table Panel follow the steps above.

Hope this helps you

**Comment by hugohaggmark** [comment] 2021-03-11 12:48
I'm going to close this issue as there is a valid workaround and there hasn't been any excessive feedback from the community about this.

**Closed by hugohaggmark** 2021-03-11 12:48 UTC
Labels: area/grafana/data, datasource/InfluxDB, type/bug
