### ISSUE TITLE
[Feature Request] Duplicate Datasource

### ISSUE THREAD

**Issue by notes-jj** [grafana/grafana#4871] opened 2016-05-01 12:20 UTC
Please implement a "Duplicate"-Button to a data source.
For configuring multiple data series, that only differ in database is is cumbersome to create the data source always from scratch.

I'm using docker container grafana:grafana
Grafana version: 3.0.0-beta7, commit: v3.0.0-beta6+8-gf6d538b, build date: 2016-04-30 16:41:24

**Comment by torkelo** [comment] 2016-05-01 12:28
dupe of https://github.com/grafana/grafana/issues/4639

**Closed by torkelo** 2016-05-01 12:28 UTC
