### ISSUE TITLE
Explore: "Expand results" toggle gets applied to the wrong pane when in split view

### ISSUE THREAD

**Issue by andrejpk** [grafana/grafana#80833] opened 2024-01-18 17:30 UTC
### What happened?

When I split an Explore view, if I click the "Expand results" toggle on the right pane, it takes action on the left pane only. Clicking on the left one works on the left one. So I don't see a way to toggle "Expand results" except on the first pane. 

### What did you expect to happen?

When I split an Explore view I expect it to toggle the one I clickedd

### Did this work before?

First time I tried

### How do we reproduce it?

1. Go to Explore view
2. Write a query with results in the first pane
3. Spit panes and write another query
4. Click toggle results on the right pane

### Is the bug inside a dashboard panel?

In the Explore view, not really in a panel

### Environment (with versions)?

Grafana: Grafana v9.5.13 (802385ecac) on Azure Managed Grafana
OS: MacOs
Browser: Edge Version 122.0.2325.0 (Official build) Dev (x86_64)

### Grafana platform?

Other

### Datasource(s)?

Prometheus

----

Initial state:
![image](https://github.com/grafana/grafana/assets/1774478/bc93fe1b-79a5-4b6b-9e85-fcde5f6cf9f9)
click on **right** Expand toggle
<img width="1262" alt="image" src="https://github.com/grafana/grafana/assets/1774478/d370a52e-54b0-41f9-9d8c-a74bb00d8007">

**Comment by tonypowa** [comment] 2024-02-15 09:56
hi @andrejpk 
thank you for reporting this issue

Are there any errors showing up in the browser console when you attempt to click the 'Expand results' toggle in the second pane? If yes, could you please copy and paste them or include a screenshot of the console?

extra helpful request 🙏  could you provide a screen recording of the issue occurring?

**Comment by Elfo404** [comment] 2024-02-15 13:22
Closing this as it duplicate of #73863, and already fixed by https://github.com/grafana/grafana/pull/73864, released in `10.2.0`

**Closed** 2024-02-15 13:22 UTC
Labels: area/explore, triage/needs-confirmation
