### ISSUE TITLE
Fix fastpass issues on Cloudwatch plugin

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#40915] opened 2021-10-26 08:43 UTC
Download the chrome extension for testing pages here: https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en

Fix any problems! 😄

**Comment by vickyyyyyyy** [comment] 2022-01-11 15:32
dupe of https://github.com/grafana/grafana/issues/42705 and https://github.com/grafana/grafana/issues/42706

**Closed by vickyyyyyyy** 2022-01-11 15:32 UTC
Labels: datasource/CloudWatch, type/accessibility
