### ISSUE TITLE
Legend is not updating in its location under the graph

### ISSUE THREAD

**Issue by simonszu** [grafana/grafana#18657] opened 2019-08-21 10:48 UTC
**What happened**:
I have created a graph from a victoriametrics. The default legend is the long string with the several labels i get from the data source. I wanted to give a simple legend (a fixed string). After editing the textbox for it, the legend itself isn't updating, however the fixed string seems to be saved. 

**What you expected to happen**:
The legend below the graph is updated. 
**How to reproduce it (as minimally and precisely as possible)**:
1. Add a new graph panel
2. Enter the metrics query
3. Klick in the legend textbox
4. Set the Legend value to a fixed string
5. Click outside the textbox
6. The legend isn't updating

Additional info: Maybe it is because i set the graph color between step 4 and 5. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3 (as of Docker Image Tag "latest")
- Data source type & version: Victoriametrics, so a Prometheus Data Source. Version: 1.25.2
- OS Grafana is installed on: Debian Buster
- User OS & Browser: Arch Linux with installed daily updates, Google Chrome
- Grafana plugins: None
- Others: -

**Comment by torkelo** [comment] 2019-08-21 11:15
dupe of https://github.com/grafana/grafana/issues/18567 (fixed in master / nightly builds).

**Closed by torkelo** 2019-08-21 11:15 UTC
