### ISSUE TITLE
Feature Req: Descending order in Point Popup

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#3406] opened 2015-12-03 08:38 UTC
I have a graph with 30+ series (grafana 2.5 + Influxdb 0.9). When I want to understand a specific spike to understand which series has that spike, looking into the Point Poup is a neat feature.

However sometimes its not possible, as the screen realstate will be smaller than the space required to show the point popup, and it gets clipped. The series may be buried down. Can we have an option to decide the order in which popup lists series (ascending or descending)?

![image](https://cloud.githubusercontent.com/assets/8618235/11555573/4f2736ec-99c7-11e5-92e2-1bedc52b95e7.png)

**Comment by torkelo** [comment] 2015-12-03 09:01
duplicate of https://github.com/grafana/grafana/issues/1189

**Closed by torkelo** 2015-12-03 09:01 UTC

**Comment by mvadu** [comment] 2015-12-03 09:05
@torkelo sorry for creating a duplicate

**Comment by torkelo** [comment] 2015-12-03 09:07
np :)
