### ISSUE TITLE
$__unixEpochGroup() function doesn't handle values >1d

### ISSUE THREAD

**Issue by mxk1235** [grafana/grafana#16794] opened 2019-04-26 23:21 UTC
**What happened**: 

Using an interval variables together with a large time window can set interval to be '1d', which is then not mapped correctly into seconds.  

**What you expected to happen**: '1d' interval should work as well as '24h'

**How to reproduce it (as minimally and precisely as possible)**:
try using the built-in with a mysql datasource and any regular query.
select something like 1 year time window, and interval variable that will resolve to >1d.  E.g. 
``` $__unixEpochGroup(time_sec, $interval) as tg```

![Screen Shot 2019-04-26](https://user-images.githubusercontent.com/354518/56840832-a363d280-683e-11e9-831c-2a9be4c6d076.jpg)

also happens in SQL editor view

<img width="926" alt="Screen Shot 2019-04-26 at 4 19 34 PM" src="https://user-images.githubusercontent.com/354518/56840903-24bb6500-683f-11e9-90af-5aa3ceb57309.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.4
- Data source type & version: mysql
- OS Grafana is installed on: CentOS
- User OS & Browser: MacOS/Chrome
- Grafana plugins: none
- Others:

**Comment by marefr** [comment] 2019-04-28 09:51
Duplicate of #11431

**Closed by marefr** 2019-04-28 09:51 UTC
