### ISSUE TITLE
Graphite function parameter is always quoted when using template variables

### ISSUE THREAD

**Issue by phrend** [grafana/grafana#2078] opened 2015-05-29 17:43 UTC
I'm just starting out with templates in grafana 2.0.2, and am excited about the possibilities, but think that I ran in to a bug. I created a custom variable named `movingAvg` containing the numbers `1` `2` `3` `4` `5` `6` `7` `8` `9`, and intended to use it with the movingAverage() function. After adding my variable to the function, I get the little red "!" corner on the upper-left of the graph and it says

> Timeseries data request error

It looks like it's failing because Grafana it's wrapping the variable with single quotes. (I can see them when I click on the little pencil to modify the query directly.) If I remove the single quotes, it works as expected.

**Comment by torkelo** [comment] 2015-05-30 07:38
that is strange, it works fine on this dashboard, http://play.grafana.org/dashboard/db/new-features-in-v18?panelId=11&fullscreen&edit&editview=templating

**Comment by torkelo** [comment] 2015-05-30 07:41
hm.. but then again when I updated the query the bug got introduced, so it seems like a new bug (that it worked on previous releases but not know). 

You should be able to use minutes bases moving averages, like '1m', '2m', '10m',  because they should be enclosed in quotes

**Comment by Krinkle** [comment] 2015-09-18 00:44
I'm experiencing the same. Using a variable holding numbers in a function like `movingAverage()` it breaks the query because it wraps the number in single quotes which graphite rejects.

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
> https://grafana.wikimedia.org/#/dashboard/db/resourceloader?panelId=12&fullscreen&edit
>
> x | x
> -- | --
> A | ResourceLoader | reqs | sum | movingAverage($movingAverage) | alias(total)
>
> Template:
> * $movingAverage: 100
>
> Request: `//graphite.wikimedia.org/render?target=alias(movingAverage(ResourceLoader.reqs.all.sum,'100') ..`

> Response:
> ```
> Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
>  response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File "/usr/lib/python2.7/dist-packages/graphite/render/views.py", line 122, in renderView
>  seriesList = evaluateTarget(requestContext, target)
> File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 10, in evaluateTarget
>  result = evaluateTokens(requestContext, tokens)
> File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
>  return evaluateTokens(requestContext, tokens.expression)
> File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
>  args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
> File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
>  return evaluateTokens(requestContext, tokens.expression)
> File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 29, in evaluateTokens
>  return func(requestContext, *args)
> File "/usr/lib/python2.7/dist-packages/graphite/render/functions.py", line 706, in movingAverage
>  delta = parseTimeOffset(windowSize)
> File "/usr/lib/python2.7/dist-packages/graphite/render/attime.py", line 148, in parseTimeOffset
>  unitString = getUnitString(unit)
> File "/usr/lib/python2.7/dist-packages/graphite/render/attime.py", line 168, in getUnitString
>  raise Exception, "Invalid offset unit '%s'" % s Exception: Invalid offset unit '' 
> ```

**Comment by Krinkle** [comment] 2015-09-23 00:27
It looks like issue #1207 (acd944a6496) solved a similar problem.

**Comment by torkelo** [comment] 2015-09-23 09:52
This is not so easy to solve. movingAverage accepts both string and int params, and a template variable name is a string (which will be replaced with variable value at query time). 

And you could have interval variable (with 10m, or 1m value), then the quotes are required.

**Comment by Krinkle** [comment] 2015-09-23 14:13
Is the template substituted before or after expanding individual functions? If it is resolved before, then it can enjoy the same logic as for non-template input (which is also string essentially). acd944a already does this by using `$.isNumeric(value)` to decide whether to quote the value.

**Comment by torkelo** [comment] 2015-09-23 16:08
@Krinkle thats the tricky party, the string interpolation  (evaluation) happens just before the issue is sent to Graphite. 

This happens function rendering (model -> string) happens every time you update/add a function (which causes the underlying graphite text query to be updated)
https://github.com/grafana/grafana/blob/acd944a64968fb8ca832885f3489d22ff49a891a/src/app/services/graphite/gfunc.js#L599

**Comment by sknolin** [comment] 2015-10-29 18:19
I just noticed this bug, and the manual query editor workaround. 

I think it might be common for people to see it because I think one of the first introductions to templating used $smoothing in moving averages. It's not apparent because only when entering new graphs on the same page even does it appear.

Scott

**Comment by SteveNewhouse** [comment] 2016-01-06 14:49
Ran into this just now as well w/movingAverage().

**Comment by lilydjwg** [comment] 2016-04-29 03:57
I ran into this just now. Version is 3.0.0-beta51460725904

**Comment by shalstea** [comment] 2018-10-12 19:14
Problem for me to.

**Comment by torkelo** [comment] 2019-03-22 12:40
Fixed and will be in 6.1

**Closed** 2019-03-22 12:39 UTC
Labels: area/dashboard/templating, datasource/Graphite, type/bug
