### ISSUE TITLE
[Feature request] Add option for navbar positioning to be fixed.

### ISSUE THREAD

**Issue by Niosop** [grafana/grafana#6763] opened 2016-11-30 19:03 UTC
In order to refresh the data manually or change the time range, you have to scroll to the top of the page to see the nav bar.  On dashboards with a lot of graphs, scrolling up, clicking, then scrolling back down to the section you're interested in takes a bit of time.  If there was an option to make navbar positioning fixed so it was always at the top of the page regardless of how much you have scrolled down, it would solve a minor pain point for me.

**Comment by bergquist** [comment] 2016-12-01 16:33
Dupe of https://github.com/grafana/grafana/issues/4670

**Closed by bergquist** 2016-12-01 16:33 UTC
