### ISSUE TITLE
Returned error in Grafana is not expected error

### ISSUE THREAD

**Issue by Techmaster21** [grafana/grafana#30193] opened 2021-01-11 15:17 UTC
**What happened**:
Got error `invalid character '\x1f' looking for beginning of value` when attempting to access nonexistent influxdb bucket.

**What you expected to happen**:
Expect error that relates to the issue, like the InfluxDB web UI gives, `failed to initialize execute state: could not find bucket "nonexistent-bucket"`.

**How to reproduce it (as minimally and precisely as possible)**: 
Install fresh Grafana, add an influx data source using flux (influx 2.x), create a new dashboard and a new panel with a flux query. Attempt to use a bucket that doesn't exist. For instance, 
```
from(bucket: "nonexistent-bucket")
|> range(start: -1w)
```
Observe the error is `invalid character '\x1f' looking for beginning of value`.

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: built in InfluxDB data source using Flux
- OS Grafana is installed on: Kubernetes version 1.17.4 using Docker image
- User OS & Browser: Windows 10, Chrome 87
- Grafana plugins: 
- Others: InfluxDB server version is 2.0.2

**Comment by torkelo** [comment] 2021-01-12 11:37
Can you turn on debug logging and show any server-side errors you see related to this request (grafana server log)

**Comment by Techmaster21** [comment] 2021-01-12 15:45
The only relevant logs I can see are
```
t=2021-01-12T15:07:32+0000 lvl=dbug msg="Processing metrics query" logger=http.server query="&{data:map[datasource:InfluxDB datasourceId:1 groupBy:[map[params:[$__interval] type:time] map[params:[null] type:fill]] intervalMs:15000 maxDataPoints:1262 orderByTime:ASC orgId:1 policy:default query:from(bucket: \"non-existent\")\r\n|> range(start: -1w) refId:A resultFormat:time_series select:[[map[params:[value] type:field] map[params:[] type:mean]]] tags:[]]}"
t=2021-01-12T15:07:32+0000 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=1 orgId=1
t=2021-01-12T15:07:32+0000 lvl=dbug msg="Received a query request" logger=tsdb.influxdb numQueries=1
t=2021-01-12T15:07:32+0000 lvl=dbug msg="Received a query" logger=tsdb.influx_flux query="{TimeRange:0xc00125ed80 Queries:[0xc00125ee80] Headers:map[] Debug:false User:0xc001a209a0}"
t=2021-01-12T15:07:32+0000 lvl=dbug msg="Executing Flux query" logger=tsdb.influx_flux flux="from(bucket: \"non-existent\")\r\n|> range(start: -1w)"
t=2021-01-12T15:07:32+0000 lvl=warn msg="Flux query failed" logger=tsdb.influx_flux err="invalid character '\\x1f' looking for beginning of value" query="from(bucket: \"non-existent\")\r\n|> range(start: -1w)"
t=2021-01-12T15:07:32+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=100.64.10.1 time_ms=54 size=973 referer="https://debug-grafana-devops-onstar.k8s-test-edco.opr.test.statefarm.org/dashboard/new?editPanel=2&orgId=1"
```
I also confirmed that the expected error (bucket not found) is returned by the InfluxDB server when a POST request with the following body is sent to the /api/v2/query endpoint

```json
{
    "query": "from(bucket: \"non-existent\")\r\n|> range(start: -1w)",
    "extern": {
        "type": "File",
        "package": null,
        "imports": null,
        "body": [
            {
                "type": "OptionStatement",
                "assignment": {
                    "type": "VariableAssignment",
                    "id": {
                        "type": "Identifier",
                        "name": "v"
                    },
                    "init": {
                        "type": "ObjectExpression",
                        "properties": [
                            {
                                "type": "Property",
                                "key": {
                                    "type": "Identifier",
                                    "name": "timeRangeStart"
                                },
                                "value": {
                                    "type": "DateTimeLiteral",
                                    "value": "2020-01-09T17:17:49.043Z"
                                }
                            },
                            {
                                "type": "Property",
                                "key": {
                                    "type": "Identifier",
                                    "name": "timeRangeStop"
                                },
                                "value": {
                                    "type": "DateTimeLiteral",
                                    "value": "2021-01-08T17:17:49.029Z"
                                }
                            },
                            {
                                "type": "Property",
                                "key": {
                                    "type": "Identifier",
                                    "name": "windowPeriod"
                                },
                                "value": {
                                    "type": "DurationLiteral",
                                    "values": [
                                        {
                                            "magnitude": 1800000,
                                            "unit": "ms"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            }
        ]
    },
    "dialect": {
        "annotations": [
            "group",
            "datatype",
            "default"
        ]
    }
}
```

**Comment by gabor** [comment] 2021-02-26 13:28
i'm unable to reproduce this unfortunately, tried both grafana-7.3.5 and current-version-in-git. i always get the expected "correct" error message.

@Techmaster21 maybe try a newer version of grafana, it might help. closing the issue. if any new information becomes available just reopen the issue with the new info.

**Closed by gabor** 2021-02-26 13:28 UTC
Labels: datasource/InfluxDB/flux

**Comment by Techmaster21** [comment] 2021-03-08 21:51
Tested again with Grafana version 7.4.3 docker image running locally, InfluxDB version 2.0.4 running on remote Kubernetes cluster. No other changes, same error. Attaching image for reference.

![image](https://user-images.githubusercontent.com/1794313/110386566-0d965280-8026-11eb-9a4d-50356468bc5f.png)

**Comment by YakupBaltas** [comment] 2021-03-30 08:48
I created a new token for the bucket on the InfluxDB side and rearranged it on the Grafana side. My fault was that I used the old bucket token. For me the problem is solved.

**Comment by YakupBaltas** [comment] 2021-03-30 08:51
I created a new token for the bucket on the InfluxDB side and rearranged it on the graphene side. My fault was that I used the old bucket token. For me the problem is solved.

**Comment by alexkar598** [comment] 2023-07-13 01:54
Fixed the issue by setting "Accept-Encoding: Identity" in the header config. \x1f is the first byte of the gzip magic (1f 8b).
