### ISSUE TITLE
Statetimeline share Graph Tooltip with the rest of the grafs (time series etc)

### ISSUE THREAD

**Issue by houmoller** [grafana/grafana#36280] opened 2021-06-29 19:44 UTC
**Why is this component needed**:
To easy tract individual happenings with specific machine states
___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
For monitoring everything that includes different states
___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by leeoniya** [comment] 2021-06-29 19:58
Duplicate of https://github.com/grafana/grafana/issues/35683

related: https://github.com/grafana/grafana/issues/35908

**Closed by leeoniya** 2021-06-29 19:58 UTC
Labels: area/grafana/ui
