### ISSUE TITLE
Text Queries with Zabbix Data Source fail to return content

### ISSUE THREAD

**Issue by ajaxous** [grafana/grafana#28042] opened 2020-10-05 20:07 UTC
**Overview**:

Several, what appear to be related issues happen when working with Zabbix data content (Log, Text and Character) that is considered Text in Grafana.

If I am leveraging a table from Grafana 6.7.X where the query returned textual data (Query Mode: "Text", Format as "Time Series") (when I have a wild card or variable for several different Items), if I go to the transform and select "Series to Rows".  All of my textual data changes to "NaN".  This is keeping the old style table.  If I convert to the new table, the same thing happens.  Previously without the transform and the old table, the different rows of textual data were interleaved as I would expect.

If I start from scratch and create a new dashboard in Grafana 7.2 or the 7.3 pre releases and make exactly the same query as the first variant, I don't get any values returned at all -- the Item is still a wild card.  If I then go and enable the "Series to Rows" Transform, even though there was no data, the value column now contains only "NaN"

As a variant of this experiment, I queried by "Item ID" for fields that are Textual and both 6.7.4 and 7.2 and 7.3 pre all do not return the textual data, they return 0.

It seems like a data-typing issue where in the first two cases, the fields are assumed to be numeric when executing the "Series to Rows" transform and thus the text or empty strings resulted in a NaN.  For the query by Item ID, I do not usually use that, but it did not seem to work as expected for the 6.7 series either -- I'm not sure how the data type is discovered if just specifying the Item ID, but maybe this is related.

I don't know if the Zabbix Data source is typing the data such that it triggers this behavior, but it seems like that may be the case as I haven't seen other reports of this happening.  I see a few days ago someone posted a similar issue with the Stat panel and Text queries -- and I have observed the new Stat Panel acts like the new Table panel, so I suspect there is a connection.

**What happened**: 

Query of Text data returns no data for new 7.X tables.  For working 6.7.X tables, the query works.  For either, if executing the "Series to Rows" Transform, the result is NaN for the value rather than the interleaved text content from the queries.

**What you expected to happen**: 

Have the value of the Text query return and interleaved as per the functionality of the "Series to Rows" transform

**How to reproduce it (as minimally and precisely as possible)**:

- Using a Zabbix data source -- either the direct Zabbix API connection or the Zabbix API + Direct SQL DB method -- both act the same way.
- Create a new dashboard with a table visualization
- Create a new query: "Query Mode: Text", "Format As: Time Series", Group=specific host, Application=specific application, Item=/.*/ or another wild card for multiple text items

With any 7.X, this returns an empty set, but if the previous had been done in 6.7.X and then copied over to 7.X, the query appears to return values.  After either one of those, chose the "Series to Rows" transform and the result will be NaN for all the values.

**Anything else we need to know?**:

The Merge transform will also return Nan even though "Series to Rows" is the actual desired operation.

**Environment**:

- Grafana version: All versions of 7.X, but the "Series to Rows" didn't get introduced until 7.2 I believe.
- Data source type & version: Zabbix Data Source.  Version 4.0.1 and also with the 3.X data sources.
- OS Grafana is installed on: Running in a Docker Container, images: grafana:master and grafana:latest
- User OS & Browser: Windows 10, Chrome or Firefox
- Grafana plugins: Zabbix-Grafana
- Others:

**Comment by aknuds1** [comment] 2020-10-06 06:03
@alexanderzobnin Can you tell if this is a bug in the Zabbix plugin?

**Comment by aknuds1** [comment] 2020-10-06 06:05
@ajaxous Have you considered opening an issue in the [Zabbix](https://github.com/alexanderzobnin/grafana-zabbix) repo instead, since it's a plugin?

**Comment by alexanderzobnin** [comment] 2020-10-06 09:13
@ajaxous Hi! Could you provide zabbix API request results? Series to Rows transformation doesn't work with text data - it expects numeric values. Also, I can't replicate this - all works as expected. If you need actual text values from multiple series, try to use Reduce transformation with `last` or `last (not null)` param.

**Comment by ajaxous** [comment] 2020-10-07 20:43
Hi.

I wasn't initially sure if the issue was with the plugin or Grafana so I thought I'd put here to see if others may have encountered the same phenomena.  Lookin at issue #27971 it seemed like there may be something similar happening.

If the Series to Rows transform doesn't work with text data I can see that triggering what I'm seeing (The NaN message was a bit confusing).  Are there plans to change that in the future?

With Grafana 6.7.4, I'd been using the "Time Series to Rows" Table transform for a "Query Mode: Text" with "Format As: Time Series" and this was working as I expected.

In one case, I'm using the zabbix agent to split a log file into individual sections, each with it's own item.  In the 6.7.4 table, I can use the "Time Series to Rows" to re-assemble all of the different rows of data for each of the items into what looks like the original log file or I can (via variables) pick just specific sections (items) of the log file I want to view.  I'm just attempting to create the same thing with the new 7.X tables.  This is just one example of what I've been using the Time Series to Rows in 6.7.4 for, but there are others that aren't specific to log files.

@alexanderzobnin, How can I get the API result to share with you if what will help?  If I use the Reduce Transform, I believe I'll only get the last row of data from the item, not the entire series.  I previously put together a video (~10 minutes) showing what was happening and can share that with you directly if you wanted to see what was happening.  

I think the issue may be that the way I'm trying to use my textual data;  I need to interleave textual data based on the time-stamp and was hoping the "Time Series to Rows" would work with the textual data. 

Thanks for more of your thoughts on this.

**Comment by alexanderzobnin** [comment] 2020-10-15 12:48
@ajaxous you can use Grafana query inspector to get data source response:

![Screenshot from 2020-10-15 15-47-21](https://user-images.githubusercontent.com/4932851/96128263-cd5ef800-0efd-11eb-8c1f-b1e75410add6.png)

**Comment by asm19** [comment] 2020-10-15 20:13
@alexanderzobnin I don't have any data in v7.2, check: https://github.com/grafana/grafana/issues/27971

Work well in v7.1.5

**Comment by alexanderzobnin** [comment] 2020-10-20 08:05
Ok, I'll try to reproduce this issue.

**Comment by alexanderzobnin** [comment] 2020-10-20 08:14
Confirmed. Text data is not working with Stat and Table panels. It looks like panels expect to get only numeric data, even if Last value selected.

**Comment by hyrava** [comment] 2020-10-20 17:52
Same problem with Discrete panel plugin and Zabbix datasource.

**Comment by cuspat96** [comment] 2020-10-30 06:04
Problem persists in Grafana 7.3.0

**Comment by gustavoghpf** [comment] 2020-10-30 18:56
@aknuds1 @dprokop @torkelo seems like a bug in grafana 7.2+

**Comment by cawhite6** [comment] 2020-11-03 18:45
Any update on possible fix, think it shows a bug in grafana???

**Comment by sirbavo** [comment] 2020-11-04 13:55
> @aknuds1 @dprokop @torkelo seems like a bug in grafana 7.2+

I can also confirm this, 7.1.5 is the last working version. Query inspector is also stucked during the loading process (however based on the network traffic the API is responding with the proper values).

_Zabbix is an enterprise-class monitoring solution with LTS versions also (5 year support), used by many people out there. **The proper working of this data source plugin really needs more attention**, because updating Zabbix, Grafana and the Datasource plugin is generally a nightmare, needs a lot of testing over and over. There are no version without blocker issues. I am in to continue testing and reporting bugs to help reach the stable version state._

**Comment by ajaxous** [comment] 2020-11-23 19:25
What it seems to narrow down to is that with Grafana 6.X, the table had a Table Transform called "Time series to rows" that worked on textual or numeric data.  I used it a lot for textual data (not just the latest values, but a sequence of textual values from several parallel queries that I wanted to organized in chronological sequence).  It (Time series to rows) worked perfect and the table (along with some custom variable menus) gave a lot of flexibility in viewing the data.

Grafana 7 didn't initially have the same functionality in it's transforms but eventually the "Series to rows" was added.  Unfortunately that transform seems to only work with numeric data.   Even with today's docker container snapshot (Grafana v7.4.0-6963pre) with Zabbix 5.0.5 and the Zabbix-Grafana Plugin 4.0.2, I get NaN for all my textual data when I change from the old table to the new table and then add the transform.   If I don't convert the table, I get the expected results with the 4.0.2 version of the plugin, so it is returning the correct data to Grafana: I don't know if there's a type, text vs numeric, associated with the values the Zabbix-Grafana plugin returns, but maybe that could be triggering the behavior if textual data was labeled numeric -- or maybe the value isn't typed and the transform is doing something assuming a numeric value.  Then it might be possible to manually specify text or numeric as an option to the "Series to rows" transform if it can't automatically determine the value type.

Hopefully this isn't a difficult change -- I have enough textual dashboards that use tables with the "Time series to rows" functionality that I'm still holding off on migrating to 7.X due to this issue.

**Comment by alexanderzobnin** [comment] 2020-11-25 12:15
Closing this since issue has been fixed in grafana-zabbix 4.0.2.

**Closed by alexanderzobnin** 2020-11-25 12:15 UTC
Labels: area/transformations, needs investigation

**Comment by alexanderzobnin** [comment] 2020-11-25 12:21
@ajaxous With the latest fix (4.0.2) Series to rows transformation works well:

![Screenshot from 2020-11-25 15-20-47](https://user-images.githubusercontent.com/4932851/100227234-e5308f80-2f31-11eb-88f9-af63165c6f02.png)

**Comment by ghost235** [comment] 2021-01-24 13:33
is the issue back ?

Plugin 4.1.1
Grafana 7.3.7
Zabbix 5.0.1

**Comment by JedTheHead** [comment] 2021-02-17 20:13
It appears to be back for me too. 

Plugin 4.1.2
Grafana 7.4.1
Zabbix 5.0.1

Thanks!

**Comment by cawhite6** [comment] 2021-02-17 20:31
Text still returning, no issue yet but not on latest code
Plugin: 4.0.2
Grafana: 7.3.7
Zabbix: 5.2.4

**Comment by ghost235** [comment] 2021-02-18 18:09
@JedTheHead  have a look to "Display -> Fields" when "Numeric Fields" is selected it will not work (as in pre 7.2).
My workaround select "All Fields" and under "Transform" add "Filter by Name"  than for example deselect "Time" or RegEx to your field or RegEx exclude Time " (?!Time).* ".
Works for me.

**Comment by primary1** [comment] 2021-03-19 08:43
Same issue for me with latest plugin version.

Plugin 4.1.4
Grafana 7.4.2
Zabbix 4.0.10

Works fine with plugin 4.0.2.
