### ISSUE TITLE
Explore errored when label contains unescaped "\"

### ISSUE THREAD

**Issue by wapmorgan** [grafana/grafana#20869] opened 2019-12-04 14:43 UTC
**What happened**:
Grafana explorer page fails and shows error 
```
An unexpected error happened
SyntaxError: Invalid regular expression: /app\exceptions\/: \ at end of pattern
```
when label used in query contains unescaped backslash "\\"

**What you expected to happen**:
List of records.

**How to reproduce it (as minimally and precisely as possible)**:
Search with query like `{label="test\abc"}`.

**Anything else we need to know?**:
Also, sometimes it leads to error `parse error at line 1, col 15: invalid char escape` under the search field.

**Environment**:
- Grafana version: v6.5.0-pre (19dbd27)
- Data source type & version: loki
- OS Grafana is installed on: docker
- User OS & Browser: Ubuntu, Chrome
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment] 2019-12-04 15:00
Can you try latest master? might have been fixed

**Comment by wapmorgan** [comment] 2019-12-06 12:24
Checked on v6.6.0-pre (047abc87c2) - nothing changed.

**Comment by aknuds1** [comment] 2019-12-10 07:48
I will try to reproduce.

**Comment by aknuds1** [comment] 2019-12-10 08:22
@wapmorgan With latest Grafana master (revision 1a2dad9d0c52e7298511656eb95ebad50b04a725), I made the following query to Loki from the Explore page (logs mode): `{filename="test\abc"}`. It doesn't produce any errors. Can you please try latest master and see if you still experience this bug?

**Comment by aknuds1** [comment] 2019-12-10 08:52
We're investigating why backslashes in labels cause parse errors, thanks for bringing this to our attention.

**Comment by aocenas** [comment] 2020-01-21 11:01
Hey @aknuds1, I see you added this to in progress observability, is there something on our side to work on or is this an issue in loki?

**Comment by aknuds1** [comment] 2020-01-21 15:33
@wapmorgan Do you actually mean that the label name contains a backslash? Your example shows the label value having a backslash, but that doesn't fail for me, only when it's in the label name.

**Comment by aknuds1** [comment] 2020-01-23 13:13
When it comes to backslashes in label names, that's actually forbidden. Loki has the same rules for label names as [Prometheus does](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels).

**Comment by kogent** [comment] 2020-02-12 21:15
we also notice problems of backslashes in label values populated by variable queries, especially if the matcher is a regex.

**Comment by aknuds1** [comment] 2020-02-13 08:35
@kogent Can you provide us with a reproducible example of what you're experiencing?

**Comment by kogent** [comment] 2020-02-14 21:49
1. single value bare variable in dashboards:
  * have a variable query that has label values with backslash `\` as a substring. 
  * use the variable in a query:  `metric{label=~"$var"}` 
  * if variable value is `string1\string2` you get an error: `parse error at char 111: unknown escape sequence U+004A's'` 
1. single value regex variable in dashboards
  * have a variable query that has label values with backslash `\` as a substring. 
  * use the variable in a query:  `metric{label=~"${var:regex}"}` 
  *  if variable value is `string1\string2` you get an error: `parse error at char 111: unknown escape sequence \\s` 
1. explore tool
  * any query with a backslash in a label value requires 4 backslashes to work: to match a label value of `string1\string2` you need to do `metric{label=~"string1\\\\string2"}`

the scenarios that seem to work are:
* when you use an explicit equality: `metric{label="string1\string2"}`
* when you use a bare multi value variable: `metric{label=~"$var"}`

**Comment by Mario-Hofstaetter** [comment] 2020-03-21 20:47
The same issue arises automatically when using promtail running on Windows, since windows uses blackslash path seperator.

Even when setting the filepath using forward slashes
```
__path__: C:/aX5/topic154/Log/AX.Server.Service.exe.Performance.log
```
in promtail `static_configs`, the `filename` label will still use backslash, causing trouble:
![grafana-explore-loki-backslash](https://user-images.githubusercontent.com/33002073/77235958-818fde80-6bba-11ea-9916-750ceb04b445.png)

Escaping this with `\\` works, also Dashboard Variables containing the blackslash filepath work without issue thankfully.

Running:
- loki and promtail `v1.3.0`
- grafana `v6.7.1`
all locally on Windows 10 1909

**Comment by newbie689** [comment] 2020-04-03 11:48
How does you Escaping this \\ ? I find that show context also not working
![image](https://user-images.githubusercontent.com/52246790/78357455-185d9180-75e4-11ea-9910-b675fabf38d2.png)

**Comment by aocenas** [comment] 2020-05-29 11:50
@aknuds1 @torkelo was there any updates from our side on this? I see this was moved around a bit in backend backlog so wonder if any investigation was done or not.

**Comment by aocenas** [comment] 2020-05-29 11:51
There also may be some additional info in this issue https://github.com/grafana/grafana/issues/24478

**Comment by aknuds1** [comment] 2020-05-29 12:05
@aocenas I'm not aware of any movement on this. I've been too backed up to look into this any more.

**Comment by candlerb** [comment] 2020-06-15 11:08
As another example:

```
{ip=~"10\.12\.255\.[12]"}
```

This query looks reasonable at first glance, but explore gives "parse error at line 1, col 6: invalid char escape", and a dashboard panel is empty.

The corrected version is:

```
{ip=~"10\\.12\\.255\\.[12]"}
```

There's a level of JSON-like escaping going on, so for example `\n` is a newline, and a backslash in a regex needs to be `\\`.  If you wanted to *match* a literal backslash in a regexp you would need `\\\\` :-(

The behaviour is as-designed, although the error message could be more helpful.

I see [grafana's loki datasource documentation](https://grafana.com/docs/grafana/latest/features/datasources/loki/) does link to [LogQL documentation](https://github.com/grafana/loki/blob/master/docs/logql.md).  In the latter it says:

> To avoid escaping special characters you can use the `` ` ``(back-tick) instead of `"` when quoting strings.
For example `` `\w+` `` is the same as `"\\w+"`, this is specially useful when writing regular expression which can contains many backslash that require escaping.

This doesn't work with loki 1.4.1, but it *does* work with loki 1.5.0.

@mario: if you are on loki 1.5.0 then can you try backticks around your label value?

```
{filename=`C:\aX5\topic154\...`}
```

**Comment by ivanahuckova** [comment] 2020-07-07 19:17
@newbie689 Context query escaping was fixed in https://github.com/grafana/grafana/pull/26116 and will be part of the next release.
@candlerb Thank you so much for your addition to this discussion  🙏. As you are correctly saying, the behaviour is as-designed, but we could improve error messaging and documentation. I have created a [PR for this](https://github.com/grafana/grafana/pull/26136). Once again, thanks! 🙂

**Closed** 2020-07-09 08:13 UTC
Labels: area/explore, datasource/Loki, priority/important-soon, type/bug
