### ISSUE TITLE
‘No Value - What to show when there is no value' does not work in Table Panel 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#28458] opened 2020-10-22 09:23 UTC
**What happened**: ‘No Value - What to show when there is no value’ does not work in Table Panel 

**What you expected to happen**: 
'no value' to be replaced with value specified in 'edit' mode under ‘Field’ > ‘Standard Options’ > ‘No Value - What to show when there is no value’…  

If I set a value in here, it is displayed in certain viz, e.g. Gauge…. However it does not apply for Table Panel…  

**How to reproduce it (as minimally and precisely as possible)**: 

Create a table panel and query a datasource that produces data and then no data (e.g. a prom datasource with promql 'up' on an ephemeral node).  In 'edit' mode under ‘Field’ > ‘Standard Options’ > ‘No Value - What to show when there is no value’…  set this to a text value e.g. 'no data from source' and apply/save your change.  The series should appear with the text label in the visualisation, but it does not.  

This can be verified by following the same steps above, but using Gauge panel.  You will see that the series appears with the text value when there is no data.  

**Anything else we need to know?**:

**Environment**:  Grafana Cloud 
- Grafana version:  Latest 
- Data source type & version:  Latest 
- OS Grafana is installed on:  Grafana Cloud 
- User OS & Browser:  Grafana Cloud 
- Grafana plugins:  n/a 
- Others: n/a

**Comment by ivanahuckova** [comment] 2020-10-22 10:18
@aengusrooneygrafana I am going to mark this as feature request, because currently we don't have this functionality in table panel and `No Value - What to show when there is no value` is a setting for no value in each field (we should maybe improve wording here, so it is clear).

**Comment by dprokop** [comment] 2020-11-02 13:22
@aengusrooneygrafana the Field settings apply to values, not the entire data set. Closing this as this is am intended behaviour.

For empty responses there is a `No data` indication in the table panel which, well, could be improved:

![image](https://user-images.githubusercontent.com/2376619/97872758-dda50e80-1d16-11eb-8bfc-e5779a5117ca.png)

**Closed by dprokop** 2020-11-02 13:22 UTC
Labels: area/panel/table, type/feature-request
