### ISSUE TITLE
SHA256 Sum mismatch for 10.0 & 10.1 OSS/Enterprise - Standalone Linux Binaries(64 Bit)

### ISSUE THREAD

**Issue by 99rgosse** [grafana/grafana#74430] opened 2023-09-06 08:59 UTC
### What happened?

From the grafana download page, when we download the grafana tar file and compare SHA 256 sum against the one on the site, they are different.

Tested on 3 Different computers with linux distributions - Ubuntu/Fedora with different network DSL

Happens on 10.0 and 10.1, both OSS and Enterprise version

### What did you expect to happen?

SHA256 in the download page vs locally generated are the same.

### Did this work before?

Yes around 9.5 

### How do we reproduce it?

Download the tar file for 10.0.5
OSS GRAFANA_VERSION=10.0.5

```
GRAFANA_DOWNLOAD_SHA256=1b40c4540170787168455df99076fd966f2a38391d777e0d6f4652952b93f356
wget https://dl.grafana.com/oss/release/grafana-10.0.5.linux-amd64.tar.gz && echo 
"$GRAFANA_DOWNLOAD_SHA256 grafana-10.0.5.linux-amd64.tar.gz" | sha256sum -c - 
```
grafana-10.0.5.linux-amd64.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

Same with 
Enterprise GRAFANA_VERSION=10.1.1
```
GRAFANA_DOWNLOAD_SHA256=02e093e33ef1643067756074a6f0136c829cbb76b462509c4d1253e018ac960d

wget https://dl.grafana.com/enterprise/release/grafana-enterprise-10.1.1.linux-amd64.tar.gz   && echo "$GRAFANA_DOWNLOAD_SHA256 grafana-enterprise-10.1.1.linux-amd64.tar.gz" | sha256sum -c -      
```
grafana-enterprise-10.1.1.linux-amd64.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by kminehart** [comment] 2023-09-13 20:08
Thanks for letting us know. I'm going to close this as a duplicate of https://github.com/grafana/grafana/issues/74514.

**Closed by kminehart** 2023-09-13 20:08 UTC
Labels: area/backend

**Comment by 99rgosse** [comment] 2023-09-14 05:46
Thank you for your kind reply, and good job for finding the culprit !
