### ISSUE TITLE
mysql panic occurring occasionally upon Grafana dashboard access

### ISSUE THREAD

**Issue by servak** [grafana/grafana#11155] opened 2018-03-08 02:04 UTC
The following error page is being presented occasionally when Grafana is accessed.
The issue began to appear only after Grafana was upgraded to v5.0.0 from v4.6.3, 
and seems to arise irrespective of the dashboard being viewed.
The backend database used is MySQL, which is the same as was in use in v4.6.3.

![image](https://user-images.githubusercontent.com/1210536/37128864-63559ae0-22bf-11e8-9dfb-a62b6ddfc010.png)

![image](https://user-images.githubusercontent.com/1210536/37128879-7cc2131e-22bf-11e8-8497-555cb32982eb.png)

```
2018-03-07T00:42:11.78+0900 [APP/PROC/WEB/2] ERR [mysql] 2018/03/07 00:42:11 packets.go:36: unexpected EOF
2018-03-07T00:42:11.78+0900 [APP/PROC/WEB/2] OUT t=2018-03-07T00:42:11+0900 lvl=eror msg="Request error" error="session/mysql: error checking existence: invalid connection" stack="/usr/local/go/src/runtime/panic.go:491 (0x432ad2)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/mysql/mysql.go:147 (0xbc3a34)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/session.go:257 (0x8415c1)
/go/src/github.com/grafana/grafana/pkg/middleware/session.go:117 (0xc2edaf)
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:99 (0xc2a21d)
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:57 (0xc313c6)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x800040)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7e2ee3)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7e2c1a)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x80025d)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x800195)
/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:145 (0xc328e0)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x800040)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7e2ee3)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7e2c1a)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x80025d)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x800195)
/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xc2ff61)
/usr/local/go/src/runtime/asm_amd64.s:509 (0x461d8a)
/usr/local/go/src/reflect/value.go:434 (0x4c0744)
/usr/local/go/src/reflect/value.go:302 (0x4bfd23)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7e3228)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7e2b29)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x80025d)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x811cb2)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x80c13b)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x804a77)
/usr/local/go/src/net/http/server.go:2619 (0x694ae3)
/usr/local/go/src/net/http/server.go:1801 (0x690d9c)
/usr/local/go/src/runtime/asm_amd64.s:2337 (0x4645d0)
```

Please include this information:
- What Grafana version are you using?
v5.0.0
- What datasource are you using?
Prometheus, InfluxDB
- What OS are you running grafana on?
Ubuntu (buildpack on Pivotal Cloud Foundry)
https://github.com/cloudfoundry/binary-buildpack/releases/tag/v1.0.16
- What did you do?
Access Grafana dashboards.
- What was the expected result?
The dashboard to appear without any errors.
- What happened instead?
Occasionally, instead of the dashboard, a page containing what appears to be mysql panic errors is shown.
Not confined to a particular page, this abnormality persists across all the dashboards.

**Comment by daniellee** [comment] 2018-03-08 08:46
The panic is caused by this function in the session middleware for the go-macaron web framework that Grafana uses: https://github.com/go-macaron/session/blob/master/mysql/mysql.go#L147

```go
// Exist returns true if session with given ID exists.
func (p *MysqlProvider) Exist(sid string) bool {
	var data []byte
	err := p.c.QueryRow("SELECT data FROM session WHERE `key`=?", sid).Scan(&data)
	if err != nil && err != sql.ErrNoRows {
		panic("session/mysql: error checking existence: " + err.Error())
	}
	return err != sql.ErrNoRows
}
```

This code has not changed for a long time so the question is why you are suddenly getting an `invalid connection` error. We upgraded the gp-mysql driver in 5.0 so it could be something to with that.

**Comment by daniellee** [comment] 2018-03-08 08:56
@servak can you turn on debugging in your ini file and hopefully we can get a bit more information about the error.

```ini
[log]
level = debug
```

**Comment by daniellee** [comment] 2018-03-08 08:57
Could be this issue:

https://github.com/go-sql-driver/mysql/issues/674

**Comment by servak** [comment] 2018-03-08 11:43
@daniellee Thank you for your reply.

I turned debugging mode in my Grafana.
Please check below.
```
2018-03-08T20:13:33.58+0900 [APP/PROC/WEB/0] OUT t=2018-03-08T20:13:33+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:13:38.07+0900 [APP/PROC/WEB/2] ERR [mysql] 2018/03/08 20:13:38 packets.go:36: unexpected EOF
2018-03-08T20:13:38.07+0900 [APP/PROC/WEB/2] ERR 2018/03/08 20:13:38 session/mysql: error garbage collecting: invalid connection
2018-03-08T20:13:38.07+0900 [APP/PROC/WEB/2] OUT t=2018-03-08T20:13:38+0900 lvl=dbug msg="Session GC" logger=session
2018-03-08T20:13:38.17+0900 [APP/PROC/WEB/1] ERR [mysql] 2018/03/08 20:13:38 connection.go:311: invalid connection
2018-03-08T20:13:38.18+0900 [APP/PROC/WEB/1] OUT t=2018-03-08T20:13:38+0900 lvl=dbug msg="Session GC" logger=session
2018-03-08T20:13:38.58+0900 [APP/PROC/WEB/0] ERR [mysql] 2018/03/08 20:13:38 packets.go:36: unexpected EOF
2018-03-08T20:13:38.58+0900 [APP/PROC/WEB/0] ERR 2018/03/08 20:13:38 session/mysql: error garbage collecting: invalid connection
2018-03-08T20:13:38.58+0900 [APP/PROC/WEB/0] OUT t=2018-03-08T20:13:38+0900 lvl=dbug msg="Session GC" logger=session
2018-03-08T20:13:43.06+0900 [APP/PROC/WEB/2] OUT t=2018-03-08T20:13:43+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:13:43.16+0900 [APP/PROC/WEB/1] OUT t=2018-03-08T20:13:43+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:13:43.58+0900 [APP/PROC/WEB/0] OUT t=2018-03-08T20:13:43+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:13:53.06+0900 [APP/PROC/WEB/2] OUT t=2018-03-08T20:13:53+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:13:53.16+0900 [APP/PROC/WEB/1] OUT t=2018-03-08T20:13:53+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:13:53.57+0900 [APP/PROC/WEB/0] OUT t=2018-03-08T20:13:53+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:14:03.06+0900 [APP/PROC/WEB/2] OUT t=2018-03-08T20:14:03+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:14:03.16+0900 [APP/PROC/WEB/1] OUT t=2018-03-08T20:14:03+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:14:03.57+0900 [APP/PROC/WEB/0] OUT t=2018-03-08T20:14:03+0900 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
2018-03-08T20:14:12.51+0900 [RTR/22] OUT XXXXXXXXXXXXXXXXXXXXXXX - [2018-03-08T11:14:12.492+0000] "GET / HTTP/1.1" 200 0 4845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "XXX.XXX.XXX.XXX:27203" "XXX.XXX.XXX.XXX:62339" x_forwarded_for:"XXX.XX.X.XXX" x_forwarded_proto:"http" vcap_request_id:"70a7615e-0e02-4298-7f30-22b55d85d97e" response_time:0.01961504 app_id:"d080ad49-f0b9-48d6-9e30-a8c54ee2f81a" app_index:"1" x_b3_traceid:"c5886b64ea7dffde" x_b3_spanid:"c5886b64ea7dffde" x_b3_parentspanid:"-"
2018-03-08T20:15:38.67+0900 [RTR/27] OUT
2018-03-08T20:15:38.74+0900 [APP/PROC/WEB/0] ERR [mysql] 2018/03/08 20:15:38 connection.go:372: invalid connection
2018-03-08T20:15:38.75+0900 [RTR/7] OUT XXXXXXXXXXXXXXXXXXXXXXX - [2018-03-08T11:15:38.749+0000] "GET /api/search?limit=5&starred=true HTTP/1.1" 500 0 692 "http://XXXXXXXXXXXXXXXXXXXXXXX/d/000000044/home?orgId=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "XXX.XXX.XXX.XXX:40990" "XXX.XXX.XXX.XXX:62339" x_forwarded_for:"XXX.XX.X.XXX" x_forwarded_proto:"http" vcap_request_id:"88be15ce-971a-461d-4ecd-e4d3e4ba3535" response_time:0.003975669 app_id:"d080ad49-f0b9-48d6-9e30-a8c54ee2f81a" app_index:"1" x_b3_traceid:"7140c7eba5a24e1d" x_b3_spanid:"7140c7eba5a24e1d" x_b3_parentspanid:"-"
2018-03-08T20:15:38.75+0900 [RTR/7] OUT
2018-03-08T20:15:38.75+0900 [APP/PROC/WEB/1] ERR [mysql] 2018/03/08 20:15:38 packets.go:36: unexpected EOF
2018-03-08T20:15:38.75+0900 [APP/PROC/WEB/1] OUT t=2018-03-08T20:15:38+0900 lvl=eror msg="Request error" error="session/mysql: error checking existence: invalid connection" stack="/usr/local/go/src/runtime/panic.go:491 (0x432ad2)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/mysql/mysql.go:147 (0xbc3a34)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/session/session.go:257 (0x8415c1)
/go/src/github.com/grafana/grafana/pkg/middleware/session.go:117 (0xc2edaf)
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:99 (0xc2a21d)
/go/src/github.com/grafana/grafana/pkg/middleware/middleware.go:57 (0xc313c6)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x800040)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7e2ee3)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7e2c1a)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x80025d)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x800195)
/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:145 (0xc328e0)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x800040)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7e2ee3)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7e2c1a)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x80025d)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x800195)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/gzip/gzip.go:96 (0xc27cb1)
/usr/local/go/src/runtime/asm_amd64.s:509 (0x461d8a)
/usr/local/go/src/reflect/value.go:434 (0x4c0744)
/usr/local/go/src/reflect/value.go:302 (0x4bfd23)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7e3228)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7e2b29)
/go/src/github.com/grafana/grafana/pkg/middleware/util.go:28 (0xc33550)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x800040)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x7e2ee3)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x7e2c1a)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x80025d)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x800195)
/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 (0xc2ff61)
/usr/local/go/src/runtime/asm_amd64.s:509 (0x461d8a)
/usr/local/go/src/reflect/value.go:434 (0x4c0744)
/usr/local/go/src/reflect/value.go:302 (0x4bfd23)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x7e3228)
/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x7e2b29)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x80025d)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x811cb2)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x80c13b)
/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x804a77)
/usr/local/go/src/net/http/server.go:2619 (0x694ae3)
/usr/local/go/src/net/http/server.go:1801 (0x690d9c)
/usr/local/go/src/runtime/asm_amd64.s:2337 (0x4645d0)
"
2018-03-08T20:15:38.76+0900 [RTR/22] OUT XXXXXXXXXXXXXXXXXXXXXXX - [2018-03-08T11:15:38.746+0000] "GET /api/search?dashboardIds=44&dashboardIds=68&dashboardIds=156&dashboardIds=50&dashboardIds=155 HTTP/1.1" 200 0 436 "http://XXXXXXXXXXXXXXXXXXXXXXX/d/000000044/home?orgId=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36" "XXX.XXX.XXX.XXX:38854" "XXX.XXX.XXX.XXX:62605" x_forwarded_for:"XXX.XX.X.XXX" x_forwarded_proto:"http" vcap_request_id:"c625acaf-3b53-4d73-6f13-f45921db4480" response_time:0.018683769 app_id:"d080ad49-f0b9-48d6-9e30-a8c54ee2f81a" app_index:"0" x_b3_traceid:"3e9d3988496bbd84" x_b3_spanid:"3e9d3988496bbd84" x_b3_parentspanid:"-"
```

**Comment by daniellee** [comment] 2018-03-13 17:27
Thanks @servak - working on reproducing this locally and will get a fix out for 5.0.2.

**Comment by daniellee** [comment] 2018-03-13 21:50
## Cause

We updated the MySQL Go Driver for 5.0. It introduced new behavior when the MySQL session times out - which is controlled by the [`wait_timeout` setting](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout). The previous version of the driver retried when the session timed out but with the new version it returns an error. 

This causes the code in Macaron to panic (as mentioned above) and this can be seen both in the logs and in error messages in the UI. The recovery middleware recovers from the Macaron panic and returns a 500 error to the UI. It also causes errors in any background queries like alerting or when old sessions are cleaned up.

Related: https://github.com/go-sql-driver/mysql/issues/657 and https://github.com/go-sql-driver/mysql/pull/302

There are two connections to mysql that can be affected, the connection in SqlStore and the connection to the session table via Macaron (our web framework). (Not sure if this affects the connections to Sql data sources).

This has a serious impact on any Grafana using MySQL for the backend - especially if they have have set a short `wait_timeout`.

## Reproducing the error

This is easy to reproduce - just set `wait_timeout` to a small value. 

## Possible Solutions

1. Revert the mysql driver to an earlier version - has a knock on effect on the mysql data source where changes will have to be reverted. Another disadvantage is that it looks like this change is permanent so Grafana should handle it.

2. Try and use the new (ish) [SetConnMaxLifetime](https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime) for controlling the connection lifetime in the connection pool.

### Current Status

I decided to go with option 2 to start with and have made a first attempt at a patch - will continue with it tomorrow and hopefully get it into 5.0.2. 

I updated xorm (the ORM Grafana uses) to be able to use [SetConnMaxLifetime](https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime) and that seems to fix the first connection. As the second connection is opened inside Macaron, we do not have access to it - a recover func and a retry would be one way to get solve it.

**Comment by bergquist** [comment] 2018-03-20 11:48
@daniellee please close this ticket once we merged this to master. I'm closing the 5.0.3 milestone

**Closed** 2018-03-20 19:16 UTC
Labels: P0: critical, comp: backend/db, type: bug

**Comment by daniellee** [comment] 2018-03-20 19:20
We had this issue in GrafanaCloud and can confirm that this fix worked. 

For `wait-timeout` we have 10 minutes and we set `conn-max-lifetime` to 30 seconds. (The important part is that `conn-max-lifetime` is shorter than `wait-timeout`.
