### ISSUE TITLE
World Map + MySQL = Data Error on Grafana 8

### ISSUE THREAD

**Issue by ajimix** [grafana/grafana#35917] opened 2021-06-18 02:35 UTC
**What happened**:

After upgrade to Grafana 8, the World Map stopped working with MySQL queries.

Error in Safari 14.1.1

<img width="646" alt="2021-06-18 at 10 20 37@2x" src="https://user-images.githubusercontent.com/30565/122496751-d836d300-d01e-11eb-8d84-ed385b82e367.png">

Error in Chrome 91.0.44

<img width="511" alt="2021-06-18 at 10 33 58@2x" src="https://user-images.githubusercontent.com/30565/122497891-b6d6e680-d020-11eb-84a8-2320382e24f6.png">

**What you expected to happen**:

World Map should keep working with queries that were working on Grafana < 8

**How to reproduce it (as minimally and precisely as possible)**:

Add World Map plugin, create a MySQL query similar to this:

```sql
SELECT DATE(created_at) AS "time", country_code AS "metric", count(distinct ip) AS "count" FROM clients
GROUP BY country_code
ORDER BY created_at
```

Which produces the following SQL result

<img width="267" alt="2021-06-18 at 10 29 42@2x" src="https://user-images.githubusercontent.com/30565/122497588-28fafb80-d020-11eb-9c99-695ddd86d130.png">

And use the following World Map options

<img width="360" alt="2021-06-18 at 10 39 01@2x" src="https://user-images.githubusercontent.com/30565/122498297-73c94300-d021-11eb-8592-7c7ee1ee3aea.png">

In Grafana < 8 all the World Map + MySQL graphs were working. After upgrade to Grafana 8 (now in 8.0.2) all of them stopped working with the same error.

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: MySQL latest
- OS Grafana is installed on: Ubuntu 18
- User OS & Browser: tested in MacOS 11.4 with Safari 14.1.1 and Chrome 91.0.44
- Grafana plugins: WorldMap

**Comment by leeoniya** [comment] 2021-06-18 02:44
think this is duplicate of #35599 (will be fixed by https://github.com/grafana/grafana/pull/35839)

**Comment by torkelo** [comment] 2021-06-18 06:06
duplicate of https://github.com/grafana/grafana/issues/35599

We are working on fixing this

**Closed by torkelo** 2021-06-18 06:06 UTC
