### ISSUE TITLE
Can't edit/delete alert rules when data source deleted

### ISSUE THREAD

**Issue by MattKobayashi** [grafana/grafana#53357] opened 2022-08-07 13:13 UTC
**What happened**:
I removed a data source (InfluxDB 2) from Grafana then tried to edit/delete some alert rules with queries that used this data source. I found that the alert rules could not be edited or deleted, instead an error message appears: `Error: invalid rule specification at index [0]: failed to validate condition of alert rule System Load: invalid query C: data source not found: 000000001`. Query C does not exist in the GUI.

**What you expected to happen**:
I expected the alert rules to be able to be deleted regardless of data source availability.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a couple of alert rules with queries that use a specific data source.
2. Remove the data source from Grafana.
3. Try to edit or delete one of the alert rules. It will fail with the above error message.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: 9.0.6
- Data source type & version: InfluxDB 2 and Prometheus
- OS Grafana is installed on: Alpine Linux 3.16
- User OS & Browser: macOS Monterey 12.5
- Grafana plugins: Renderer
- Others: Grafana running in a Docker container on Docker Engine 20.10.16

**Comment by usmangt** [comment] 2022-08-11 14:02
Hi @MattKobayashi ,

Thanks for opening this case.

Did you upgrade your grafana server version and while doing that, were those alert rules were there before moving to ver. 9.0.6 ?

**Comment by MattKobayashi** [comment] 2022-08-11 14:15
Hi @usmangt,

Yes, this Grafana instance has been upgraded, and yes, these rules were migrated as part of those upgrades. It sounds like this may be a known issue?

**Comment by anthosz** [comment] 2022-08-17 07:50
Hi,

I just upgraded to Grafana v9.1.0 and now, all stuff related to Alerts (Alerts Rules/Contact points/Notif) are in read only mode

**Comment by zuchka** [comment] 2022-08-17 14:43
@anthosz that sounds like a different issue that this.

@MattKobayashi I was not able to replicate this. I added a working prometheus datasource and then created an alert based on a query from that datasource. I deleted the datasource and then I was able to delete the associated alert rule.

can you provide more detailed reproduction steps?

**Comment by MattKobayashi** [comment] 2022-08-19 02:32
@zuchka The issue may be specific to InfluxDB v2 data sources using FluxQL queries, that was the datasource I used to create the alert rules originally. I deleted the InfluxDB v2 data source and created new rules based on a Prometheus data source, but wasn't able to delete the original alert rules due to the above mentioned error.

**Comment by gillesdemey** [comment] 2022-08-22 09:49
I've also failed to repro this one, when a data source no longer exists we give the user the option to update the data source configuration for that alert rule definition.

![image](https://user-images.githubusercontent.com/868844/185892876-875e6081-7ef6-4c35-b70a-d7e520e2208d.png)

**Comment by MattKobayashi** [comment] 2022-08-22 11:52
@gillesdemey This option did appear for me, however clicking on "remove query" returned the same error as above.

**Comment by jensenity** [comment] 2022-09-20 04:53
same with here

**Comment by armandgrillet** [comment] 2022-09-23 09:31
We need to reproduce this with the InfluxDB datasource.

**Comment by armandgrillet** [comment] 2022-09-23 16:44
Investigated further: this happens if multiple alert rules in a same group refer to the same deleted datasource and one of them is being deleted. A workaround is to delete all the rules referencing the deleted datasource in a group by using the API. The reason why a solution is not obvious is the fact that we want to be compliant with the Prometheus Alertmanager regarding how we handle groups.

UX wise, we could have a new button allowing the deletion of all alert rules in a group so that the UI has more than the only current option of deleting only one alert rule at once.

**Comment by yuri-tceretian** [comment] 2022-09-23 20:53
I was able to reproduce the problem. It is pretty simple:
1. Create a data source
2. Create two alert rules. **Important:** both alert rules should belong to the same folder and group.
3. Delete the data source
4. In UI, try to delete one of the rules. 🎉 

The reason for that happening is the validation of the group update endpoint `POST /api/ruler/grafana/api/v1/rules/:FOLDER_NAME`. When user clicks on `Delete` button, UI pulls the entire group rule belongs to, modifies the group, and then submits it back. If group is empty after modification, it uses `DELETE  /api/ruler/grafana/api/v1/rules/:FOLDER_NAME/:GROUP_NAME` that deletes the entire group. Otherwise, it sends POST request (above). The input model validation validates that all rules that are specified and fails because the UID of data source points to nothing. 

Therefore, I can see two possible workarounds:
1. Use `DELETE  /api/ruler/grafana/api/v1/rules/:FOLDER_NAME/:GROUP_NAME` to delete entire group. 
2. If the group contains rules that point to another data source and those need to be kept, then use `POST /api/ruler/grafana/api/v1/rules/:FOLDER_NAME` but remove all rules that use deleted data source. The simplest way to do so is to try delete, copy the failed request sent by browser, modify it and re-send.


As far as possible solutions are concerned, I can see two possible ways that are local to the alerting API:
1. Do not perform data source validation early in API model but do that later when we have information about the current rule. This will be hard to implement because we validate query and server-side expression by the `expr` package (shared code), and also do some authorization that checks that the user has access to all datasources before accessing the database and reading the existing rules in the group. Therefore, even if we remove it from model validation 
2. Is little bit simpler but not Prometheus-ish way: create a `DELETE  /api/ruler/grafana/api/v1/rules/:FOLDER_NAME/:GROUP_NAME/:UID` (the exact path is TBD) to delete one specific rule. This will let us to move the logic on UI that modifies the group to the backend and then properly delete the rule. Although it is kinda opposite to the conception of the groups we are moving towards, this will help facilitate what UI actually advertises (handling rules as individual entities) until we figure out the proper layout for groups.

**Comment by grobinson-grafana** [comment] 2022-09-27 12:44
Thanks Yuri for writing such a great explanation of the issue!

I think the issue here is that the Ruler API expects that a datasource cannot be deleted while it is still referenced in an alert rule. If we fix that issue then we also fix this issue.

The first question that we should consider is can we just prevent deletion of datasources that are referenced in alert rules? Then the user would have to delete each of the alert rules first before deleting the datasource.

If we don't want to do that, can we instead make it such that the deletion of a datasource cascades the delete to all alert rules that reference it? The UI should show a message to confirm deletion if there are alert rules that would be deleted by this operation.

**Comment by yuri-tceretian** [comment] 2022-09-27 16:32
After discussing this during our weekly we decided to move forward with the following steps:
- Update datasource API to not let users delete data sources that have alert rules pointing to them. Then UI can follow-up with the different strategies like asking user to re-assign all affected rules to another datasource or delete them together with the datasource. 
- Add `DELETE rule_uid` endpoint and then update UI to use it instead of the rule group update API.

**Comment by scholdan** [comment] 2022-11-03 10:42
I got the same issue with Loki datasource i've deleted.

![image](https://user-images.githubusercontent.com/23090427/199700898-6ea63263-9fe6-4fd7-8de8-d8bc5f4286da.png)

**Comment by suryasubit** [comment] 2022-11-15 07:20
yes you can delete this using a tricks, 

1. try to change the group name
2. delete all the labels and summary and description as well in the very end of this page.
3. delete the query
4. now save the dashboard
5. Now try to delete the alert rule. It will delete successfully.

thanks me later

**Comment by kwenzh** [comment] 2022-12-05 01:36
the same promblem

**Comment by RomanTG** [comment] 2022-12-06 06:08
> yes you can delete this using a tricks,
> 
>     1. try to change the group name with different name
> 
>     2. delete the query ( remove query )
> 
>     3. now save the dashboard
> 
>     4. Now try to delete the alert rule. It will delete successfully.
> 
> 
> thanks me later

Didn't help for me

**Comment by ddervenkov** [comment] 2022-12-11 21:08
1. After "update datasource"  edit  alert rules  to different folder and group (example: Temp Temp  ). 
2. Then can move it back to folder and group.

**Comment by jmuleiro** [comment] 2023-05-16 19:26
In my case @suryasubit 's commend almost worked, but Grafana wouldn't let me save an alert with no query, so I added a PromQL query with a fixed value of 0, saved the alerts, and then deleted them.

**Closed** 2023-06-15 17:33 UTC
Labels: type/bug, area/alerting, prio/medium, effort/medium
