### ISSUE TITLE
session shutdown - Failed to look up user based on cookie

### ISSUE THREAD

**Issue by guitoulefoux** [grafana/grafana#56878] opened 2022-10-13 14:04 UTC
**What happened**:
Since v9.2.0 my session is shutdown

**What you expected to happen**:
nothing

**How to reproduce it (as minimally and precisely as possible)**:
i updated grafana from v9.1.6 (92461d8d1e) to v9.2.0 (c7eea48209)

**Anything else we need to know?**:
On the log i have logger=context t=2022-10-13T15:48:37.394066999+02:00 level=warn msg="Failed to look up user based on cookie" error="database is locked"

**Environment**:
- Grafana version:9.2.0
- Data source type & version: sqlite3
- OS Grafana is installed on: VM azure
- User OS & Browser: Ubuntu 20 - Chrome
- Grafana plugins:
- Others:

**Comment by Jguer** [comment] 2022-10-14 08:40
Hi, I think we need some more details to be able to help

- Did all migrations run correctly? 
- Can you share a bit more about your setup? 
- Database type? 
- Any authentication integration?

**Comment by guitoulefoux** [comment] 2022-10-14 09:25
Hello,

Thank you for your reply.

_Did all migrations run correctly?_
Yes

_Can you share a bit more about your setup?_
Sure what do you want to know?

_Database type?_
sqlite3

_Any authentication integration?_
no

After analysis on my side and after looking at different issues tickets, the problem seems to come from `sqlite error="database is locked"`.

This is what happens just before the session is disconnected:
```
logger=context t=2022-10-13T15:48:37.394066999+02:00 level=warn msg="Failed to look up user based on cookie" error="database is locked"
logger=context t=2022-10-13T15:48:37.480122533+02:00 level=warn msg="Failed to look up user based on cookie" error="database is locked"
logger=context t=2022-10-13T15:48:37.564731564+02:00 level=warn msg="Failed to look up user based on cookie" error="database is locked"
logger=context userId=0 orgId=0 uname= t=2022-10-13T15:48:41.099389012+02:00 level=info msg="Request Completed" method=POST path=/api/ds/query status=401 remote_addr =10.2.1.4 time_ms=8542 duration=8.542016188s size=27 referer="..." handler=/api/ds/query

```

I applied the following update:
```
sudo sqlite3 /var/lib/grafana/grafana.db
sqlite> pragma journal_mode=wal;
```

This modification seems to remove the "database is locked" and the session cut-off problem.

**Comment by Jguer** [comment] 2022-11-16 12:36
Good to know a workaround is working, unfortunately I can't seem to reproduce it and there seems to be no out of the usual scenario. We are starting a rework on user sessions that will hopefully make this issue obsolete.

Closing it for now. If there's any more details on this or other occurrences we can reopen this issue

**Closed by Jguer** 2022-11-16 12:36 UTC
Labels: area/auth
