### ISSUE TITLE
Grafana Query Builder hangs loading K6 metrics from Prometheus

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana#52171] opened 2022-07-13 16:15 UTC
**What happened**:
I set up a Grafana Cloud stack. As part of this stack there were a Prometheus instance and and a Grafana instance.
I followed[ K6's guide](https://k6.io/docs/results-visualization/grafana-cloud/#set-up-grafana-cloud-prometheus) for setting up Grafana Cloud's Prometheus for receiving metrics from `k6`.  Please notice this is not about using [k6 Cloud App](https://grafana.com/grafana/plugins/grafana-k6-app/)  but about sending `k6` metrics to prometheus.

I then used Grafana explorer using the Prometheus instance as a data source but the query builder hung when retrieving the metrics:
![Screenshot from 2022-07-11 16-29-22](https://user-images.githubusercontent.com/720259/178777373-27f74b33-448e-44a1-8aab-4f2c07d7d3d8.png)

However, when I then checked in the Cardinality Management it showed the metrics from k6:

![Screenshot from 2022-07-07 12-51-56](https://user-images.githubusercontent.com/720259/178779262-d209cd77-b34c-4259-8ee0-d6a1612e35a9.png)

Interestingly, the Metrics explorer did work and could successfully retrieve the metrics, as shown bellow. 
![Screenshot from 2022-07-11 15-26-32](https://user-images.githubusercontent.com/720259/178777761-7cd19d7f-45c8-4f49-8a61-e383adc063b9.png)

Therefore, it seams the setup for `k6` is correct and it is working, the problem seam related only with the query builder.

**What you expected to happen**:
I expected the explored to allow me to create a query from te

**How to reproduce it (as minimally and precisely as possible)**:

Following the [Set up Grafana Cloud Prometheus ](https://k6.io/docs/results-visualization/grafana-cloud/#set-up-grafana-cloud-prometheus )guide (you will need a `k6` test script. This bellow  should work:
```
#test.js

import http from "k6/http";
import { sleep } from 'k6';

export default function() {
  const res = http.get('https://test-api.k6.io/public/crocodiles/');
  sleep(1)
};

export let options = {
  stages: [
    { duration: '10m', target: 10 }
  ],
  thresholds: {
    "http_req_duration": ["p(95)<200"],
    "http_req_failed": ["rate<0.01"],
  }
};
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud
- Data source type & version: Prometheus from the Grafana Cloud
- OS Grafana is installed on: N/A
- User OS & Browser: Ubuntu 22.04 / Chrome Version 103.0.5060.53 (Official Build) (64-bit)
- Grafana plugins: N/A
- Others:

**Comment by MattDodsonEnglish** [comment] 2022-07-13 19:21
I came upon this error independently. Exactly the same: k6 metrics show in **Cardinality Management**, but when I tried to add a metric with **Explore Builder** toggled, the wheel just spins and spins―I left the tab open and did something else, and the wheel was still spinning 30 minutes later.

On the k6 side, we've added a little set of instructions to help users get around this. When this gets fixed, it'd be nice to remove that to keep instructions streamlined.

https://k6.io/docs/cloud/integrations/cloud-apm/grafana-cloud/#run-the-cloud-test

**Comment by zoltanbedi** [comment] 2022-07-18 08:21
I was able to reproduce this. Thanks for letting us know.

**Comment by aocenas** [comment] 2022-07-21 13:37
Could be we have some perf optimizations in the metric browser that we should also apply in the builder.

**Comment by aocenas** [comment] 2022-07-28 12:51
So we use a virtualized list in the metrics browser: https://github.com/grafana/grafana/blob/3c6e0e8ef85048af952367751e478c08342e17b4/public/app/plugins/datasource/prometheus/components/PrometheusMetricsBrowser.tsx#L497.

Select that we use in builder does not have any optimization like that. In the meantime as a quick fix we could just limit the number of items (users can still type out the value manually, not great but could be more usable).

Long term would it make sense to add virtualization option to select? Or do we need some new component for that? cc @grafana/user-essentials.
Other option that could make more sense is that we are thinking about somehow merging the metric select into builder as that UX is still better for selecting labels and metrics and that could also solve this issue. @diegoadams @itsmylife

**Comment by aocenas** [comment] 2022-07-29 16:18
Seems like external user actually found some other issue with how we handle metrics https://github.com/grafana/grafana/pull/52148. @itsmylife we should check if that PR helps also in this case.

**Comment by itsmylife** [comment] 2022-08-11 13:48
@aocenas I have checked and merged the PR.

**Comment by gtk-grafana** [comment] 2022-09-22 15:11
@itsmylife do we just need to verify that this issue was fixed by https://github.com/grafana/grafana/pull/52148 before closing this?

**Comment by gtk-grafana** [comment] 2022-09-22 15:54
Ok, so it appears that https://github.com/grafana/grafana/pull/52148 will help with performance, but there's an escalation (https://github.com/grafana/support-escalations/issues/4008) reporting a similar issue with the metric dropdown that appears to be caused by not virtualizing the options within that dropdown.

**Comment by gtk-grafana** [comment] 2022-09-22 16:29
@obetomuniz is handling the PR on this right now but we're temporarily blocked by https://github.com/grafana/grafana/pull/55629. We think the solution for this issue should be to simply replace the current component with the new virtualized one, so I expect a quick followup.

**Closed** 2022-10-05 15:19 UTC
Labels: type/bug, prio/high, datasource/Prometheus
