### ISSUE TITLE
Docs feedback: /panels/thresholds.md

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#25682] opened 2020-06-17 22:25 UTC
>Absolute thresholds are defined based on a number. For example, 80 on a scale of 1 to 150.

Needs better examples (i would provide some but i cant figure out how these work if you want red yellow green on Free disk space) -  ie there is no place to set the "scale"  but "scale" is used in the docs (i know there is no scale to be set)

Also what units is it based off of (if in the absolute mode)?
and what defines Max/Min if in percent mode? (is it the max/min for a query from the current time interval or all time?)
tks

**Comment by sakjur** [comment] 2020-06-18 08:24
@marcusolsson Maybe you could clarify how thresholds works in the docs? 🙂 (cc @oddlittlebird)

**Comment by oddlittlebird** [comment] 2020-07-07 20:20
I will look into this. @sakjur, which team would you recommend I speak with?

**Comment by oddlittlebird** [comment] 2020-12-22 16:16
@dprokop, is there anyone we could work with on this?

**Comment by dprokop** [comment] 2020-12-22 16:18
@oddlittlebird I think I can help to answer any questions you might have @oddlittlebird  :)

**Comment by achatterjee-grafana** [comment] 2021-04-02 15:16
Chatted with @oddlittlebird. She will work with @dprokop to update this topic.

**Comment by GrafanaWriter** [comment] 2022-06-17 20:52
This issue hasn't had activity in more than six months. In another week, I will close it.

If you comment or otherwise update it, we'll reset the clock.

**Comment by GrafanaWriter** [comment] 2024-01-18 16:49
Given the age of this issue, and the lack of activity, I will close. Please reopen if the issue is still valid.

**Closed by GrafanaWriter** 2024-01-18 16:49 UTC
Labels: type/docs, area/panel/common, migrate/status-icebox
