### ISSUE TITLE
Add filter by folder to Dashboard links. 

### ISSUE THREAD

**Issue by cronosnull** [grafana/grafana#26491] opened 2020-07-21 15:59 UTC
**What would you like to be added**:

An option to filter also by folder (as the one already existing in the dashboard list plugin) in the dashboard link by tags. 

![image](https://user-images.githubusercontent.com/4405564/88077537-abaed880-cb7b-11ea-9750-ddd6598e3bf2.png)

**Why is this needed**:
Currently, we can create dashboard links based on tags. This works great and gives us flexibility, but there is no option to filter also by folder. 
We have, among others, a production and a playground folder. When a user copies a production dashboard into the playground folder, the copy will inherit the tags and therefore will appear in the dashboards that have dashboard links to them. With a filter by folder, we can prevent this to happen.

**Comment by torkelo** [comment] 2020-07-21 19:40
duplicate of https://github.com/grafana/grafana/issues/12338

**Closed by torkelo** 2020-07-21 19:40 UTC
