### ISSUE TITLE
Alerting: Error on loading rules from Loki

### ISSUE THREAD

**Issue by pschulten** [grafana/grafana#48627] opened 2022-05-03 10:50 UTC
**What happened**:
Navigating to alert rules throw the error:
```
Errors loading rules
Failed to load the data source configuration for [Loki](https://grafana.signintra.com/datasources/edit/P8E80F9AEF21F6940): Cannot destructure property 'features' of 'l.data.data' as it is undefined.
```

**How to reproduce it (as minimally and precisely as possible)**:
add a Loki datasource with an active ruler and configure alerting

**Anything else we need to know?**:
It works fine for Mimir because the `features` property is exposed: https://github.com/grafana/mimir/blob/90aeee02de04199e0f0e4d981ce2460478f76392/pkg/util/version/info_handler.go#L22

In Loki it's not: https://github.com/grafana/loki/blob/8b15632dd8e584c04facd48a1cbe26aa807516e3/pkg/loki/version_handler.go#L14

It also works with the same setup for Loki, if I downgrade Grafana to 8.3.5 or 8.4.6, but fails with for 8.5.0

Loki DS definition:
```json
{
  name: 'Loki',
  type: 'loki',
  access: 'proxy',
  // BEGIN TODO: OPSORG
  orgId: std.parseInt(opsid),
  // END TODO: OPSORG
  url: 'https://' + $.config.lokiHost,
  version: 1,
  editable: false,
  jsonData: {
    serverName: $.config.lokiHost,
    tlsAuth: true,
    tlsAuthWithCACert: true,
  },
  secureJsonData:
    {
      tlsCACert: loki.issuing_ca,
      tlsClientCert: loki.certificate,
      tlsClientKey: loki.private_key,
    },
},
```

**Environment**:
- Grafana version: 3.5.1
- Data source type & version: Loki 2.5.0

**Comment by pschulten** [comment] 2022-05-04 08:35
I created a workaround by mocking the expected response in my Nginx reverse proxy in front of Loki like this:
```nginx
location ~ /api/v1/status/buildinfo {
#     fake it until resolved
  return 200 '{"status":"success","data":{"application":"Grafana Mocki","version":"2.5.0","revision":"2d9d0ee23","branch":"HEAD","goVersion":"go1.17.8","features":{"ruler_config_api":"true","alertmanager_config_api":"true","query_sharding":"false","federated_rules":"false"}}}';
}
``` 
now Grafana alerting works as expected 🦖

**Comment by gabor** [comment] 2022-05-06 12:22
@grafana/alerting-squad could you take a look at this one? it does not seem to relate to the loki-datasource itself, considering it can be fixed by mocking the `/status/buildinfo` endpoint, the loki-datasource does not connect to that one. but maybe i'm wrong, in which case feel free to send it back to @grafana/observability-logs-and-traces 😄

**Comment by joeblubaugh** [comment] 2022-05-10 02:19
There's an alerting-side change we can make to support a Loki DS with no `features` property, since we didn't always require it. Is there a reason that Loki shouldn't expose the `features` property @pschulten @gabor ? The members of that object make it clear what configuration is available on the data source.

The root of this change is one that let us distinguish between Prom, Cortex and Mimir data sources, and Loki's similarity to these is probably why it got swept up in this. [Here's the PR, #46771.](https://github.com/grafana/grafana/pull/46771)

To avoid this sort of regression, we probably need integration tests that actually communicate with a Loki process so we can track real API changes and differences from expectations.

**Comment by gabor** [comment] 2022-05-10 08:58
> There's an alerting-side change we can make to support a Loki DS with no `features` property, since we didn't always require it. Is there a reason that Loki shouldn't expose the `features` property @pschulten @gabor ? The members of that object make it clear what configuration is available on the data source.

hmm.. if this is a question about a Loki api endpoint, pinging @grafana/loki-squad

**Comment by jeremybanzhaf** [comment] 2022-05-10 15:38
got the same error after upgrading grafana from 8.4.1 to 8.5.2 with loki 2.4.1

**Comment by joeblubaugh** [comment] 2022-05-12 03:23
I'm going to work on an exception for Loki here, since any change that exposes `features` will be in a future release anyway.

**Comment by joeblubaugh** [comment] 2022-05-12 06:09
So this error:
> Errors loading rules
> Failed to load the data source configuration for [Loki](https://grafana.signintra.com/datasourcese/edit/P8E80F9AEF21F6940): Cannot destructure property 'features' of 'l.data.data' as it is undefined.

Traces to this line in the code: https://github.com/grafana/grafana/blob/a1217ef8dada46ceaa7266f5991b470ce38be96a/public/app/features/alerting/unified/api/buildInfo.ts#L61

Where "data.data" is undefined, rather than simply not having a "features" key.

When I reproed this locally, I had *three* problems: 
1. The loki API handler prefixes all of its API paths with loki: `❯ http GET localhost:3100/loki/api/v1/status/buildinfo`. This can be worked around in the data source config value.
2. The response format for Loki looks like:
    ```json
    "data": {
      "revision": ...
    }
    ```
    whereas the Mimir one is:
    ```json
    "data": {
      "data": {
        "revision": ...
      }
    }
    ```
    see the extra `data` wrapper ... this can be worked around with conditional code that checks both `response.data.data` and falls back to `response.data`.
3. Loki doesn't include the features field. We can fake this one in the Grafana backend for the time being.

But we should have a conversation with @grafana/loki-squad and @grafana/mimir-maintainers about the difference in API responses.

**Comment by joeblubaugh** [comment] 2022-05-12 06:35
There's another wrinkle here: Loki can be configured with the ruler API enabled, or disabled, and the value of the buildInfo response is supposed to tell us that. So if faking a static response, you can have a Loki instance that doesn't have the ruler API enabled, and you'll encounter a further error after reading the buildInfo response.

**Comment by joeblubaugh** [comment] 2022-05-12 07:06
I've just pushed up a workaround PR, but for it to work seamlessly, your Loki datasource must have the ruler API enabled via configuration.

**Comment by joeblubaugh** [comment] 2022-05-12 13:57
Raised some related issues on Loki:
https://github.com/grafana/loki/issues/6154
https://github.com/grafana/loki/issues/6155

Alerting will need to handle both the existing API and future fixes for at least a couple of releases, but we can switch on version number.

**Comment by konrad147** [comment] 2022-05-17 11:11
@pschulten Could you provide more details about your configuration? 
Loki, by default hides the `api/v1/status/buildinfo` endpoint behind the `/loki` prefix. So, the final path looks like `/loki/api/v1/status/buildinfo`. 
In the alerting, we call `/api/v1/status/buildinfo` which should cause a 404 error for Loki (and it usually does). 
For some reason, however, your configuration must be slightly different and it returns the `buidinfo` for calls without the `/loki` prefix.

**Closed** 2022-05-18 08:45 UTC
Labels: type/bug, area/frontend, area/alerting/unified
