### ISSUE TITLE
Data source plugin errors

### ISSUE THREAD

**Issue by Hammie217** [grafana/grafana#61526] opened 2023-01-15 11:32 UTC
**What happened**:
When following the tutorial for a data source plugin at: https://grafana.com/tutorials/build-a-data-source-plugin/ a few errors are generated due to some disparities in the text and what grafana requires.

Issues found:
1. DefaultQuery is expected to be "defaultQuery" in dataframes section 2 but is actually DEFAULT_QUERY in types.ts file.
2. defaults is not imported by default so an additional line of "import { defaults } from 'lodash';" is required in datasource.ts
3. When binding the model to a form "query;" is expected but "this.props.query;" is required.

**Environment**:
- Grafana version: v9.3.2

**Comment by tonypowa** [comment] 2023-01-23 09:30
:wave: Thanks for creating this issue, @Hammie217 

Did you manage to build the data source plugin or are you stuck? This is just to know if you managed and so we need to update the docs, or if you need some help.

If you need help, it would be helpful to know more about the errors you had (if possible). Could you look if any errors got logged in the log file ? 

Try increasing [the verbosity of the Grafana server logs](https://grafana.com/docs/grafana/latest/administration/configuration/#level) to debug and note any errors. For printing to console, [set the console logs to ](https://grafana.com/docs/grafana/latest/administration/configuration/#level-1)debug as well. More info on troubleshooting Grafana issues here https://grafana.com/docs/grafana/v9.0/troubleshooting/

**Comment by Hammie217** [comment] 2023-02-03 13:35
@tonypowa Thanks for this. I have managed to get the project working as per the tutorial but I believe the documentation needs an update as described.

I do however have issues when going beyond the tutorial trying to use external libraries that aren't covered in the documentation yet. It seems like adding external libraries are generating a large log of errors due to webpack, am I missing something I need to do to add an external package?

Thanks,
```
ERROR in ../node_modules/httpreq/lib/httpreq.js 27:11-27
Module not found: Error: Can't resolve 'http' in 'D:\Applications\grafana\plugins\hammie217-aspenconnector2-datasource\node_modules\httpreq\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
 @ ../node_modules/httpntlm/httpntlm.js 12:14-32
 @ ./datasource.ts 31:15-34
 @ ./module.ts 2:0-42 5:43-53

ERROR in ../node_modules/httpreq/lib/httpreq.js 29:9-23
Module not found: Error: Can't resolve 'fs' in 'D:\Applications\grafana\plugins\hammie217-aspenconnector2-datasource\node_modules\httpreq\lib'
 @ ../node_modules/httpntlm/httpntlm.js 12:14-32
 @ ./datasource.ts 31:15-34
 @ ./module.ts 2:0-42 5:43-53

```

**Comment by tonypowa** [comment] 2023-02-04 10:45
thanks for providing the error log @Hammie217  👍 

in order to address the doc update and the error when adding the external lib, I am forwarding this issue to the plugins platform squad.

**Comment by andresmgot** [comment] 2023-02-22 14:13
Let me close this issue since it seems it's not reproducible. If you can still reproduce it please reopen it with instructions of how to do it. Thanks!

**Closed by andresmgot** 2023-02-22 14:13 UTC
Labels: type/docs, area/plugins, onboarding
