### ISSUE TITLE
Maintaining Variables Hyper-link Issue

### ISSUE THREAD

**Issue by wood2944** [grafana/grafana#52000] opened 2022-07-08 19:58 UTC
**What happened**:  When clicking on a link taking you to another page it shows the default page.

**What you expected to happen**: When clicking on a link to take you to another page, keep the page variables from the current page.

**How to reproduce it (as minimally and precisely as possible)**: Create a link from one dashboard to another that has {__all_variables} in the dashboard, in the goal of keeping the selected variables. Through the text dashboard panel, using markdown.

**Anything else we need to know?**:

**Environment**: Grafana OSS
- Grafana version: 9.0.0
- Data source type & version: InfluxDB Version 2.0.9, this specific issue doesn't necessarily deal with the data. 
- OS Grafana is installed on: Linux Ubuntu 20.04
- User OS & Browser: Linux Ubuntu 20.04
- Grafana plugins: None
- Others:

**Comment by podolsky** [comment] 2022-07-19 07:19
I see this with 8.4.7 as well, and with links to the same dashboard that are meant to update just one variable's value (to update part of the dashboard using it) and keep all the other variables in their current values. For example a data link in a Time Series graph like this:

`/d/${__dashboard.uid}/${__dashboard.url}?${__all_variables:queryparam}&var-hudtime=${__value.time}
`
Will just nuke all drop-down changeable variables and reset them to their dashboard-saved values.

**Comment by ashharrison90** [comment] 2022-07-26 12:37
@wood2944 @podolsky 

can you try something like `/d/${__dashboard.uid}?${__all_variables})`? that seems to work for me. i don't think you need to `queryparam` formatting for `__all_variables`

**Comment by wood2944** [comment] 2022-07-28 18:02
This may be a little more difficult than originally thought, the suggestion provided did not work, thank you however. I think the problem is as it is a text panel, there is no query associated, so it does not know which Variables it should be pulling through, where as when a data link is connected to a panel with a query, the variables from the query stick with the url. Im not sure if there is a easy solution for this. I do not know if this is actually the reason for this issue however.


![grafana5](https://user-images.githubusercontent.com/82121905/181606282-d2c71876-1005-4fc9-8ca2-d93cdacaab47.png)

**Comment by wood2944** [comment] 2022-08-05 14:30
Is there any more info on this issue?

**Comment by evictorero** [comment] 2023-03-22 20:25
Hi @wood2944 I tested it with the solution @ashharrison90 suggested and it is working as the first comment said it should: `When clicking on a link to take you to another page, keep the page variables from the current page.`
Maybe it was fixed on a new version or if you still have issues can you help me understand what the problem is?

**Comment by natellium** [comment] 2023-05-10 15:06
@wood2944 friendly ping re. the above :)

**Comment by axelavargas** [comment] 2023-05-16 14:01
Hello, @wood2944 👋🏾, looks like this issue was resolved in the latest updates, so I'm going to close it. However, if you find this is not the case, please do not hesitate to inform us and we will promptly re-open the issue 😄.  Really appreciate your patience and your help in spotting this issue. 

Thank you 🙏🏾

**Closed by axelavargas** 2023-05-16 14:01 UTC
Labels: area/dashboard/templating, area/dashboard, needs more info, needs investigation
