### ISSUE TITLE
Execute query from Grafana on demand

### ISSUE THREAD

**Issue by sofixa** [grafana/grafana#4048] opened 2016-02-16 11:00 UTC
Hello. I did a quick Google search, but had no results, so I am asking here - is there a way to execute an INSERT/UPDATE query to an InfluxDB from Grafana ?
I am aware this is slightly out of scope, but i'd like to be able to mark events(annotations) and add tags to certain datapoints, from Grafana(since that's where i'll be looking at the data). 

If there is no easy way of doing that, I was thinking about forking Grafana and just adding an "Add" button that show a field where one could enter a query. Do you think that would be.. appropriate ? Doable? Practical?

Thanks in advance

**Comment by bergquist** [comment] 2016-02-16 13:54
Thats not possible right now. 

But its been a requested feature for quite some time. Closing this since I think its a dupe of https://github.com/grafana/grafana/issues/1286

Feel free to reopen if you do not agree

**Closed by bergquist** 2016-02-16 13:54 UTC
