### ISSUE TITLE
Anonymous users in grafana make a request to /api/user/preferences that http 401's

### ISSUE THREAD

**Issue by Starttoaster** [grafana/grafana#93455] opened 2024-09-18 20:52 UTC
### What happened?

I own a public grafana server that enables anonymous users to view certain dashboards on the server. Every time someone opens it up in their browser, they get a warning that says "Unauthorized"
![Image](https://github.com/user-attachments/assets/b3a6fa4a-ba5d-4183-92b9-20ffd84d42bd)

I looked in the logs, and I see these:

```
level=info msg="Request Completed" method=GET path=/api/user/preferences status=401 remote_addr=redacted time_ms=1 duration=1.181348ms size=27 referer="https://redacted/?orgId=1" handler=/api/user/preferences status_source=server
```

So anonymous users are making requests to user preferences and when it http 401's the page displays this Unauthorized banner. There's seemingly no reason for this, as nothing about the grafana home page that is meant to be viewable is not, it's just kind of a confusing banner to have show up, and I then need to explain to people in the public that they can simply ignore it.

### What did you expect to happen?

@neehhaa06 wrote a better expectation summary:

"To resolve the 401 Unauthorized error for anonymous users in Grafana, ensure that the anonymous user configuration is correct, allowing the Viewer role to access the necessary dashboards. Additionally, modify the frontend to gracefully handle the 401 status by avoiding requests to/api/user/preferencesor not displaying preference-related features for anonymous users."

### Did this work before?

This seems new, but I can't say.

### How do we reproduce it?

1. Stand up a server for anonymous users
2. ???
3. Profit

My configuration file looks like this:

```ini
[paths]
provisioning = /etc/grafana/provisioning
[dashboards]
default_home_dashboard_path = /var/lib/grafana/dashboards/home.json
[security]
disable_initial_admin_creation = true
[auth]
disable_login_form = true
[users]
allow_sign_up = false
allow_org_create = false
viewers_can_edit = false
[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Viewer
hide_version = true

[auth.basic]
enabled = false

[unified_alerting]
enabled = false
```

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.1
OS: official grafana container image
Browser: Chromium

### Grafana platform?

Kubernetes

**Comment by neehhaa06** [comment] 2024-09-19 05:53
Hello @Starttoaster :)

fix: #93455

`
To resolve the 401 Unauthorized error for anonymous users in Grafana, ensure that the anonymous user configuration is correct, allowing the Viewer role to access the necessary dashboards. Additionally, modify the frontend to gracefully handle the 401 status by avoiding requests to `/api/user/preferences` or not displaying preference-related features for anonymous users.
`

**Comment by Starttoaster** [comment] 2024-09-19 16:16
Hello @neehhaa06 :) I appreciate the comment, you accurately summarized what I would like to see changed!

**Comment by burdiyan** [comment] 2024-09-19 16:56
I'm facing the same issue. Suddenly after updating Grafana I start seeing this issue. I'm running Grafana on my local machine to monitoring some of the locally-running programs, and I'm using the anonymous setup for convenience.

**Comment by Berbe** [comment] 2024-09-28 11:10
This indeed seems to be part of anonymous access regressions between `11.1` & `11.2`

**Comment by Starttoaster** [comment] 2024-10-22 21:38
We updated Grafana and noticed this Unauthorized banner went away. I suspect it maybe coincided with this change? https://github.com/grafana/grafana/issues/93518 But I'm not sure.

**Comment by kalleep** [comment] 2024-11-06 14:44
This issue was fixed in https://github.com/grafana/grafana/pull/93840

**Closed by kalleep** 2024-11-06 14:44 UTC
Labels: type/bug, area/auth, area/backend/api, automated-triage
