### ISSUE TITLE
Dashboard list panel unable to use variable

### ISSUE THREAD

**Issue by ninkaninus** [grafana/grafana#36488] opened 2021-07-06 19:13 UTC
**What happened**:
Dashboard list panel did not update with dashboards after added text to variable used in the query

**What you expected to happen**:
Dashboard list panel should update the list of searched dashboards when the user enters a search word in the variable text box

**How to reproduce it (as minimally and precisely as possible)**:
Here is the simplest dashboard i could make with it.
https://gist.github.com/ninkaninus/a4e80c61a5c83261d55f238b0f6fc6b0

You will need some dashboards to list in the panel to validate that it works.

**Anything else we need to know?**:
As i read the documentation it should be possible to use variables in the search query fields.

**Environment**:
- Grafana version: 7.5.9
- Data source type & version: none
- OS Grafana is installed on: Bitnami grafana container
- User OS & Browser: win10 & Chrome
- Grafana plugins: dashboard list v7.5.9
- Others:

**Comment by torkelo** [comment] 2021-07-06 19:35
duplicate of https://github.com/grafana/grafana/issues/18113

**Closed by torkelo** 2021-07-06 19:35 UTC
Labels: area/panel/dashboard-list, type/feature-request
