### ISSUE TITLE
Add "Replace" option to series override?

### ISSUE THREAD

**Issue by TryTryAgain** [grafana/grafana#20603] opened 2019-11-22 17:19 UTC
**What would you like to be added**:
An option in "series override" that would allow replacing the value with a custom value.

**Why is this needed**:
Trying to look at possible solutions to my problem https://github.com/grafana/grafana/issues/9054 where the CloudWatch API doesn't expose the Account Name for AWS/Billing LinkedAccounts. It would be nice if I could use a series override to replace the LinkedAccount ID with the Account Name manually.

I can imagine this would be useful for any time the metric name or alias provided doesn't/can't contain the information you'd like to have displayed.

Any chance this would be considered?

**Comment by torkelo** [comment] 2019-11-25 00:49
duplicate of https://github.com/grafana/grafana/issues/6966

**Closed by torkelo** 2019-11-25 00:49 UTC
