### ISSUE TITLE
Incorrect display of numeric values on the Y axis for Graphite data

### ISSUE THREAD

**Issue by terra-nova** [grafana/grafana#6050] opened 2016-09-15 18:38 UTC
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
grafana-3.1.1-1470047149 from Grafana RHEL/CentOS Yum repository

- What datasource are you using?
Graphite

- What OS are you running grafana on?
CentOS 7.2

- What did you do?
Graph output of check_snmp_storage.pl Nagios plugin.

- What was the expected result?
Correct display of numeric values on the Y axis

- What happened instead?
Incorrect display of numeric values on the Y axis

![snip1](https://cloud.githubusercontent.com/assets/16338849/18561966/3a4a7f48-7b82-11e6-8877-71d2fd0cf80e.PNG)

If I'm not mistaken, 40*10^24 MiB exceeds the capacity of our disk array by a tiny bit. For reference, the legend and mouse-over display show correct numbers for the same data:

![snip2](https://cloud.githubusercontent.com/assets/16338849/18562037/783f469e-7b82-11e6-8c4b-ac18241ce880.PNG)

The "decimal precision for legend and tooltips" has been set to 2 for this particular example. Without specifying a fixed decimal precision, the values displayed in the legend and for mouse-over are also incorrect (40*10^24 MiBs).

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query
![snip3](https://cloud.githubusercontent.com/assets/16338849/18562197/09c705de-7b83-11e6-8c51-ef603b7c2c77.PNG)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

I have no idea what you're talking about. I'm a C++ and SQL guy.

**Comment by torkelo** [comment] 2016-09-16 08:47
could you show the raw response from the metric query? (chrome dev tools network tab)

**Comment by terra-nova** [comment] 2016-09-16 18:17
I am sorry but it is not clear to me what information you are looking for?

Are you looking for the response to the "metrics/find" query (http://grafana-host/api/datasources/proxy/1/metrics/find/?query=icinga2.somehostname.services.check_snmp_storage__boot.check_snmp_storage.perfdata._boot.value)?

The response to that request is this:

`[{"leaf": 1, "context": {}, "text": "value", "expandable": 0, "id": "icinga2.somehostname.services.check_snmp_storage__boot.check_snmp_storage.perfdata._boot.value", "allowChildren": 0}]
`

Or are you looking for the response to the "render" request (http://grafana-host/api/datasources/proxy/1/render)?

It looks like this:

`[{"target": "/boot", "datapoints": [[42414060.339200005, 1471460400], [42414060.339200005, 1471464000], [42414060.339200005, 1471467600], [42414060.339200005, 1471471200], [42414060.339200005, 1471474800], [42414060.339200005, 1471478400], [42414060.339200005, 1471482000], [42414060.339200005, 1471485600], [42414060.339200005, 1471489200], [42414060.339200005, 1471492800], [42414060.339200005, 1471496400], [42414060.339200005, 1471500000], [42414060.339200005, 1471503600], [42414060.339200005, 1471507200], [42414060.339200005, 1471510800], [42414060.339200005, 1471514400], [42414060.339200005, 1471518000], [42414060.339200005, 1471521600], [42414060.339200005, 1471525200], [42414060.339200005, 1471528800], [42414060.339200005, 1471532400], [42414060.339200005, 1471536000], [42414060.339200005, 1471539600], [42414060.339200005, 1471543200], [42414060.339200005, 1471546800], [42414060.339200005, 1471550400], [42414060.339200005, 1471554000], [42414060.339200005, 1471557600], [42414060.339200005, 1471561200], [42414060.339200005, 1471564800], [42414060.339200005, 1471568400], [42414060.339200005, 1471572000], [42414060.339200005, 1471575600], [42414060.339200005, 1471579200], [42414060.339200005, 1471582800], [42414060.339200005, 1471586400], [42414060.339200005, 1471590000], [42414060.339200005, 1471593600], [42414060.339200005, 1471597200], [42414060.339200005, 1471600800], [42414060.339200005, 1471604400], [42414060.339200005, 1471608000], [42414060.339200005, 1471611600], [42414060.339200005, 1471615200], [42414060.339200005, 1471618800], [42414060.339200005, 1471622400], [42414060.339200005, 1471626000], [42414060.339200005, 1471629600], [42414060.339200005, 1471633200], [42414060.339200005, 1471636800], [42414060.339200005, 1471640400], [42414060.339200005, 1471644000], [42414060.339200005, 1471647600], [42414060.339200005, 1471651200], [42414060.339200005, 1471654800], [42414060.339200005, 1471658400], [42414060.339200005, 1471662000], [42414060.339200005, 1471665600], [42414060.339200005, 1471669200], [42414060.339200005, 1471672800], [42414060.339200005, 1471676400], [42414060.339200005, 1471680000], [42414060.339200005, 1471683600], [42414060.339200005, 1471687200], [42414060.339200005, 1471690800], [42414060.339200005, 1471694400], [42414060.339200005, 1471698000], [42414060.339200005, 1471701600], [42414060.339200005, 1471705200], [42414060.339200005, 1471708800], [42414060.339200005, 1471712400], [42414060.339200005, 1471716000], [42414060.339200005, 1471719600], [42414060.339200005, 1471723200], [42414060.339200005, 1471726800], [42414060.339200005, 1471730400], [42414060.339200005, 1471734000], [42414060.339200005, 1471737600], [42414060.339200005, 1471741200], [42414060.339200005, 1471744800], [42414060.339200005, 1471748400], [42414060.339200005, 1471752000], [42414060.339200005, 1471755600], [42414060.339200005, 1471759200], [42414060.339200005, 1471762800], [42414060.339200005, 1471766400], [42414060.339200005, 1471770000], [42414060.339200005, 1471773600], [42414060.339200005, 1471777200], [42414060.339200005, 1471780800], [42414060.339200005, 1471784400], [42414060.339200005, 1471788000], [42414060.339200005, 1471791600], [42414060.339200005, 1471795200], [42414060.339200005, 1471798800], [42414060.339200005, 1471802400], [42414060.339200005, 1471806000], [42414060.339200005, 1471809600], [42414060.339200005, 1471813200], [42414060.339200005, 1471816800], [42414060.339200005, 1471820400], [42414060.339200005, 1471824000], [42414060.339200005, 1471827600], [42414060.339200005, 1471831200], [42414060.339200005, 1471834800], [42414060.339200005, 1471838400], [42414060.339200005, 1471842000], [42414060.339200005, 1471845600], [42414060.339200005, 1471849200], [42414060.339200005, 1471852800], [42414060.339200005, 1471856400], [42414060.339200005, 1471860000], [42414060.339200005, 1471863600], [42414060.339200005, 1471867200], [42414060.339200005, 1471870800], [42414060.3392, 1471874400], [null, 1471878000], [null, 1471881600], [null, 1471885200], [null, 1471888800], [null, 1471892400], [null, 1471896000], [null, 1471899600], [null, 1471903200], [null, 1471906800], [null, 1471910400], [null, 1471914000], [null, 1471917600], [null, 1471921200], [null, 1471924800], [null, 1471928400], [null, 1471932000], [42414060.3392, 1471935600], [42414060.339200005, 1471939200], [42414060.339200005, 1471942800], [42414060.339200005, 1471946400], [42414060.339200005, 1471950000], [42414060.339200005, 1471953600], [42414060.339200005, 1471957200], [42414060.339200005, 1471960800], [42414060.339200005, 1471964400], [42414060.339200005, 1471968000], [42414060.339200005, 1471971600], [42414060.339200005, 1471975200], [42414060.339200005, 1471978800], [42414060.339200005, 1471982400], [42414060.339200005, 1471986000], [42414060.339200005, 1471989600], [42414060.339200005, 1471993200], [42414060.339200005, 1471996800], [42414060.339200005, 1472000400], [42414060.339200005, 1472004000], [42414060.339200005, 1472007600], [42414060.339200005, 1472011200], [42414060.339200005, 1472014800], [42414060.339200005, 1472018400], [42414060.339200005, 1472022000], [42414060.339200005, 1472025600], [42414060.339200005, 1472029200], [42414060.339200005, 1472032800], [42414060.339200005, 1472036400], [42414060.339200005, 1472040000], [42414060.339200005, 1472043600], [42414060.339200005, 1472047200], [42414060.339200005, 1472050800], [42414060.339200005, 1472054400], [42414060.339200005, 1472058000], [42414060.339200005, 1472061600], [42414060.339200005, 1472065200], [42414060.339200005, 1472068800], [42414060.339200005, 1472072400], [42414060.339200005, 1472076000], [42414060.339200005, 1472079600], [42414060.339200005, 1472083200], [42414060.339200005, 1472086800], [42414060.339200005, 1472090400], [42414060.339200005, 1472094000], [42414060.339200005, 1472097600], [42414060.339200005, 1472101200], [42414060.339200005, 1472104800], [42414060.339200005, 1472108400], [42414060.339200005, 1472112000], [42414060.339200005, 1472115600], [42414060.339200005, 1472119200], [42414060.339200005, 1472122800], [42414060.339200005, 1472126400], [42414060.339200005, 1472130000], [42414060.339200005, 1472133600], [42414060.339200005, 1472137200], [42414060.339200005, 1472140800], [42414060.339200005, 1472144400], [42414060.339200005, 1472148000], [42414060.339200005, 1472151600], [42414060.339200005, 1472155200], [42414060.339200005, 1472158800], [42414060.339200005, 1472162400], [42414060.339200005, 1472166000], [42414060.339200005, 1472169600], [42414060.339200005, 1472173200], [42414060.339200005, 1472176800], [42414060.339200005, 1472180400], [42414060.339200005, 1472184000], [42414060.339200005, 1472187600], [42414060.339200005, 1472191200], [42414060.339200005, 1472194800], [42414060.339200005, 1472198400], [42414060.339200005, 1472202000], [42414060.339200005, 1472205600], [42414060.339200005, 1472209200], [42414060.339200005, 1472212800], [42414060.339200005, 1472216400], [42414060.339200005, 1472220000], [42414060.339200005, 1472223600], [42414060.339200005, 1472227200], [42414060.339200005, 1472230800], [42414060.339200005, 1472234400], [42414060.339200005, 1472238000], [42414060.339200005, 1472241600], [42414060.339200005, 1472245200], [42414060.339200005, 1472248800], [42414060.339200005, 1472252400], [42414060.339200005, 1472256000], [42414060.339200005, 1472259600], [42414060.339200005, 1472263200], [42414060.339200005, 1472266800], [42414060.339200005, 1472270400], [42414060.339200005, 1472274000], [42414060.339200005, 1472277600], [42414060.339200005, 1472281200], [42414060.339200005, 1472284800], [42414060.339200005, 1472288400], [42414060.339200005, 1472292000], [42414060.339200005, 1472295600], [42414060.339200005, 1472299200], [42414060.339200005, 1472302800], [42414060.339200005, 1472306400], [42414060.339200005, 1472310000], [42414060.339200005, 1472313600], [42414060.339200005, 1472317200], [42414060.339200005, 1472320800], [42414060.339200005, 1472324400], [42414060.339200005, 1472328000], [42414060.339200005, 1472331600], [42414060.339200005, 1472335200], [42414060.339200005, 1472338800], [42414060.339200005, 1472342400], [42414060.339200005, 1472346000], [42414060.339200005, 1472349600], [42414060.339200005, 1472353200], [42414060.339200005, 1472356800], [42414060.339200005, 1472360400], [42414060.339200005, 1472364000], [42414060.339200005, 1472367600], [42414060.339200005, 1472371200], [42414060.339200005, 1472374800], [42414060.339200005, 1472378400], [42414060.339200005, 1472382000], [42414060.339200005, 1472385600], [42414060.339200005, 1472389200], [42414060.339200005, 1472392800], [42414060.339200005, 1472396400], [42414060.339200005, 1472400000], [42414060.339200005, 1472403600], [42414060.339200005, 1472407200], [42414060.339200005, 1472410800], [42414060.339200005, 1472414400], [42414060.339200005, 1472418000], [42414060.339200005, 1472421600], [42414060.339200005, 1472425200], [42414060.339200005, 1472428800], [42414060.339200005, 1472432400], [42414060.339200005, 1472436000], [42414060.339200005, 1472439600], [42414060.339200005, 1472443200], [42414060.339200005, 1472446800], [42414060.339200005, 1472450400], [42414060.339200005, 1472454000], [42414060.339200005, 1472457600], [42414060.339200005, 1472461200], [42414060.339200005, 1472464800], [42414060.339200005, 1472468400], [42414060.339200005, 1472472000], [42414060.339200005, 1472475600], [42414060.339200005, 1472479200], [42414060.339200005, 1472482800], [42414060.339200005, 1472486400], [42414060.339200005, 1472490000], [42414060.339200005, 1472493600], [42414060.339200005, 1472497200], [42414060.339200005, 1472500800], [42414060.339200005, 1472504400], [42414060.339200005, 1472508000], [42414060.339200005, 1472511600], [42414060.339200005, 1472515200], [42414060.339200005, 1472518800], [42414060.339200005, 1472522400], [42414060.339200005, 1472526000], [42414060.339200005, 1472529600], [42414060.339200005, 1472533200], [42414060.339200005, 1472536800], [42414060.339200005, 1472540400], [42414060.339200005, 1472544000], [42414060.339200005, 1472547600], [42414060.339200005, 1472551200], [42414060.339200005, 1472554800], [42414060.339200005, 1472558400], [42414060.339200005, 1472562000], [42414060.339200005, 1472565600], [42414060.339200005, 1472569200], [42414060.339200005, 1472572800], [42414060.339200005, 1472576400], [42414060.339200005, 1472580000], [42414060.339200005, 1472583600], [42414060.339200005, 1472587200], [42414060.339200005, 1472590800], [42414060.339200005, 1472594400], [42414060.339200005, 1472598000], [42414060.339200005, 1472601600], [42414060.339200005, 1472605200], [42414060.339200005, 1472608800], [42414060.339200005, 1472612400], [42414060.339200005, 1472616000], [42414060.339200005, 1472619600], [42414060.339200005, 1472623200], [42414060.339200005, 1472626800], [42414060.339200005, 1472630400], [42414060.339200005, 1472634000], [42414060.339200005, 1472637600], [42414060.339200005, 1472641200], [42414060.339200005, 1472644800], [42414060.339200005, 1472648400], [42414060.339200005, 1472652000], [42414060.339200005, 1472655600], [42414060.339200005, 1472659200], [42414060.339200005, 1472662800], [42414060.339200005, 1472666400], [42414060.339200005, 1472670000], [42414060.339200005, 1472673600], [42414060.339200005, 1472677200], [42414060.339200005, 1472680800], [42414060.339200005, 1472684400], [42414060.339200005, 1472688000], [42414060.339200005, 1472691600], [42414060.339200005, 1472695200], [42414060.339200005, 1472698800], [42414060.339200005, 1472702400], [42414060.339200005, 1472706000], [42414060.339200005, 1472709600], [42414060.339200005, 1472713200], [42414060.339200005, 1472716800], [42414060.339200005, 1472720400], [42414060.339200005, 1472724000], [42414060.339200005, 1472727600], [42414060.339200005, 1472731200], [42414060.339200005, 1472734800], [42414060.339200005, 1472738400], [42414060.339200005, 1472742000], [42414060.339200005, 1472745600], [42414060.339200005, 1472749200], [42414060.339200005, 1472752800], [42414060.339200005, 1472756400], [42414060.339200005, 1472760000], [42414060.339200005, 1472763600], [42414060.339200005, 1472767200], [42414060.339200005, 1472770800], [42414060.339200005, 1472774400], [42414060.339200005, 1472778000], [42414060.339200005, 1472781600], [42414060.339200005, 1472785200], [42414060.339200005, 1472788800], [42414060.339200005, 1472792400], [42414060.339200005, 1472796000], [42414060.339200005, 1472799600], [42414060.339200005, 1472803200], [42414060.339200005, 1472806800], [42414060.339200005, 1472810400], [42414060.339200005, 1472814000], [42414060.339200005, 1472817600], [42414060.339200005, 1472821200], [42414060.339200005, 1472824800], [42414060.339200005, 1472828400], [42414060.339200005, 1472832000], [42414060.339200005, 1472835600], [42414060.339200005, 1472839200], [42414060.339200005, 1472842800], [42414060.339200005, 1472846400], [42414060.339200005, 1472850000], [42414060.339200005, 1472853600], [42414060.339200005, 1472857200], [42414060.339200005, 1472860800], [42414060.339200005, 1472864400], [42414060.339200005, 1472868000], [42414060.339200005, 1472871600], [42414060.339200005, 1472875200], [42414060.339200005, 1472878800], [42414060.339200005, 1472882400], [42414060.339200005, 1472886000], [42414060.339200005, 1472889600], [42414060.339200005, 1472893200], [42414060.339200005, 1472896800], [42414060.339200005, 1472900400], [42414060.339200005, 1472904000], [42414060.339200005, 1472907600], [42414060.339200005, 1472911200], [42414060.339200005, 1472914800], [42414060.339200005, 1472918400], [42414060.339200005, 1472922000], [42414060.339200005, 1472925600], [42414060.339200005, 1472929200], [42414060.339200005, 1472932800], [42414060.339200005, 1472936400], [42414060.339200005, 1472940000], [42414060.339200005, 1472943600], [42414060.339200005, 1472947200], [42414060.339200005, 1472950800], [42414060.339200005, 1472954400], [42414060.339200005, 1472958000], [42414060.339200005, 1472961600], [42414060.339200005, 1472965200], [42414060.339200005, 1472968800], [42414060.339200005, 1472972400], [42414060.339200005, 1472976000], [42414060.339200005, 1472979600], [42414060.339200005, 1472983200], [42414060.339200005, 1472986800], [42414060.339200005, 1472990400], [42414060.339200005, 1472994000], [42414060.339200005, 1472997600], [42414060.339200005, 1473001200], [42414060.339200005, 1473004800], [42414060.339200005, 1473008400], [42414060.339200005, 1473012000], [42414060.339200005, 1473015600], [42414060.339200005, 1473019200], [42414060.339200005, 1473022800], [42414060.339200005, 1473026400], [42414060.339200005, 1473030000], [42414060.339200005, 1473033600], [42414060.339200005, 1473037200], [42414060.339200005, 1473040800], [42414060.339200005, 1473044400], [42414060.339200005, 1473048000], [42414060.339200005, 1473051600], [42414060.339200005, 1473055200], [42414060.339200005, 1473058800], [42414060.339200005, 1473062400], [42414060.339200005, 1473066000], [42414060.339200005, 1473069600], [42414060.339200005, 1473073200], [42414060.339200005, 1473076800], [42414060.339200005, 1473080400], [42414060.339200005, 1473084000], [42414060.339200005, 1473087600], [42414060.339200005, 1473091200], [42414060.339200005, 1473094800], [42414060.339200005, 1473098400], [42414060.339200005, 1473102000], [42414060.339200005, 1473105600], [42414060.339200005, 1473109200], [42414060.339200005, 1473112800], [42414060.339200005, 1473116400], [42414060.339200005, 1473120000], [42414060.339200005, 1473123600], [42414060.339200005, 1473127200], [42414060.339200005, 1473130800], [42414060.339200005, 1473134400], [42414060.339200005, 1473138000], [42414060.339200005, 1473141600], [42414060.339200005, 1473145200], [42414060.339200005, 1473148800], [42414060.339200005, 1473152400], [42414060.339200005, 1473156000], [42414060.339200005, 1473159600], [42414060.339200005, 1473163200], [42414060.339200005, 1473166800], [42414060.339200005, 1473170400], [42414060.339200005, 1473174000], [42414060.339200005, 1473177600], [42414060.339200005, 1473181200], [42414060.339200005, 1473184800], [42414060.339200005, 1473188400], [42414060.339200005, 1473192000], [42414060.339200005, 1473195600], [42414060.339200005, 1473199200], [42414060.339200005, 1473202800], [42414060.339200005, 1473206400], [42414060.339200005, 1473210000], [42414060.339200005, 1473213600], [42414060.339200005, 1473217200], [42414060.339200005, 1473220800], [42414060.339200005, 1473224400], [42414060.339200005, 1473228000], [42414060.339200005, 1473231600], [42414060.339200005, 1473235200], [42414060.339200005, 1473238800], [42414060.339200005, 1473242400], [42414060.339200005, 1473246000], [42414060.339200005, 1473249600], [42414060.339200005, 1473253200], [42414060.339200005, 1473256800], [42414060.339200005, 1473260400], [42414060.339200005, 1473264000], [42414060.339200005, 1473267600], [42414060.339200005, 1473271200], [42414060.339200005, 1473274800], [42414060.339200005, 1473278400], [42414060.339200005, 1473282000], [42414060.339200005, 1473285600], [42414060.339200005, 1473289200], [42414060.339200005, 1473292800], [42414060.339200005, 1473296400], [42414060.339200005, 1473300000], [42414060.339200005, 1473303600], [42414060.339200005, 1473307200], [42414060.339200005, 1473310800], [42414060.339200005, 1473314400], [42414060.339200005, 1473318000], [42414060.339200005, 1473321600], [42414060.339200005, 1473325200], [42414060.339200005, 1473328800], [42414060.339200005, 1473332400], [42414060.339200005, 1473336000], [42414060.339200005, 1473339600], [42414060.339200005, 1473343200], [42414060.339200005, 1473346800], [42414060.339200005, 1473350400], [42414060.339200005, 1473354000], [42414060.339200005, 1473357600], [42414060.339200005, 1473361200], [42414060.339200005, 1473364800], [42414060.339200005, 1473368400], [42414060.339200005, 1473372000], [42414060.339200005, 1473375600], [42414060.339200005, 1473379200], [42414060.339200005, 1473382800], [42414060.339200005, 1473386400], [42414060.339200005, 1473390000], [42414060.339200005, 1473393600], [42414060.339200005, 1473397200], [42414060.339200005, 1473400800], [42414060.339200005, 1473404400], [42414060.339200005, 1473408000], [42414060.339200005, 1473411600], [42414060.339200005, 1473415200], [42414060.339200005, 1473418800], [42414060.339200005, 1473422400], [42414060.339200005, 1473426000], [42414060.339200005, 1473429600], [42414060.339200005, 1473433200], [42414060.339200005, 1473436800], [42414060.339200005, 1473440400], [42414060.339200005, 1473444000], [42414060.339200005, 1473447600], [42414060.339200005, 1473451200], [42414060.339200005, 1473454800], [42414060.339200005, 1473458400], [42414060.339200005, 1473462000], [42414060.339200005, 1473465600], [42414060.339200005, 1473469200], [42414060.339200005, 1473472800], [42414060.339200005, 1473476400], [42414060.339200005, 1473480000], [42414060.339200005, 1473483600], [42414060.339200005, 1473487200], [42414060.339200005, 1473490800], [42414060.339200005, 1473494400], [42414060.339200005, 1473498000], [42414060.339200005, 1473501600], [42414060.339200005, 1473505200], [42414060.339200005, 1473508800], [42414060.339200005, 1473512400], [42414060.339200005, 1473516000], [42414060.339200005, 1473519600], [42414060.339200005, 1473523200], [42414060.339200005, 1473526800], [42414060.339200005, 1473530400], [42414060.339200005, 1473534000], [42414060.339200005, 1473537600], [42414060.339200005, 1473541200], [42414060.339200005, 1473544800], [42414060.339200005, 1473548400], [42414060.339200005, 1473552000], [42414060.339200005, 1473555600], [42414060.339200005, 1473559200], [42414060.339200005, 1473562800], [42414060.339200005, 1473566400], [42414060.339200005, 1473570000], [42414060.339200005, 1473573600], [42414060.339200005, 1473577200], [42414060.339200005, 1473580800], [42414060.339200005, 1473584400], [42414060.339200005, 1473588000], [42414060.339200005, 1473591600], [42414060.339200005, 1473595200], [42414060.339200005, 1473598800], [42414060.339200005, 1473602400], [42414060.339200005, 1473606000], [42414060.339200005, 1473609600], [42414060.339200005, 1473613200], [42414060.339200005, 1473616800], [42414060.339200005, 1473620400], [42414060.339200005, 1473624000], [42414060.339200005, 1473627600], [42414060.339200005, 1473631200], [42414060.339200005, 1473634800], [42414060.339200005, 1473638400], [42414060.339200005, 1473642000], [42414060.339200005, 1473645600], [42414060.339200005, 1473649200], [42414060.339200005, 1473652800], [42414060.339200005, 1473656400], [42414060.339200005, 1473660000], [42414060.339200005, 1473663600], [42414060.339200005, 1473667200], [42414060.339200005, 1473670800], [42414060.339200005, 1473674400], [42414060.3392, 1473678000], [42414060.339200005, 1473681600], [42414060.339200005, 1473685200], [42414060.339200005, 1473688800], [42414060.339200005, 1473692400], [42414060.339200005, 1473696000], [42414060.339200005, 1473699600], [42414060.339200005, 1473703200], [42414060.339200005, 1473706800], [42414060.339200005, 1473710400], [42414060.339200005, 1473714000], [42414060.339200005, 1473717600], [42414060.339200005, 1473721200], [42414060.339200005, 1473724800], [42414060.339200005, 1473728400], [42414060.339200005, 1473732000], [42414060.339200005, 1473735600], [42414060.339200005, 1473739200], [42414060.339200005, 1473742800], [42414060.339200005, 1473746400], [42414060.339200005, 1473750000], [42414060.339200005, 1473753600], [42414060.339200005, 1473757200], [42414060.339200005, 1473760800], [42414060.339200005, 1473764400], [42414060.339200005, 1473768000], [42414060.339200005, 1473771600], [42414060.339200005, 1473775200], [42414060.339200005, 1473778800], [42414060.339200005, 1473782400], [42414060.339200005, 1473786000], [42414060.339200005, 1473789600], [42414060.339200005, 1473793200], [42414060.339200005, 1473796800], [42414060.339200005, 1473800400], [42414060.339200005, 1473804000], [42414060.339200005, 1473807600], [42414060.339200005, 1473811200], [42414060.339200005, 1473814800], [42414060.339200005, 1473818400], [42414060.339200005, 1473822000], [42414060.339200005, 1473825600], [42414060.339200005, 1473829200], [42414060.339200005, 1473832800], [42414060.339200005, 1473836400], [42414060.339200005, 1473840000], [42414060.339200005, 1473843600], [42414060.339200005, 1473847200], [42414060.339200005, 1473850800], [42414060.339200005, 1473854400], [42414060.339200005, 1473858000], [42414060.339200005, 1473861600], [42414060.339200005, 1473865200], [42414060.339200005, 1473868800], [42414060.339200005, 1473872400], [42414060.339200005, 1473876000], [42414060.339200005, 1473879600], [42414060.339200005, 1473883200], [42414060.339200005, 1473886800], [42414060.339200005, 1473890400], [42414060.339200005, 1473894000], [42414060.339200005, 1473897600], [42414060.339200005, 1473901200], [42414060.339200005, 1473904800], [42414060.339200005, 1473908400], [42414060.339200005, 1473912000], [42414060.339200005, 1473915600], [42414060.339200005, 1473919200], [42414060.339200005, 1473922800], [42414060.339200005, 1473926400], [42414060.339200005, 1473930000], [42414060.339200005, 1473933600], [42414060.339200005, 1473937200], [42414060.339200005, 1473940800], [42414060.339200005, 1473944400], [42414060.339200005, 1473948000], [42414060.339200005, 1473951600], [42414060.339200005, 1473955200], [42414060.339200005, 1473958800], [42414060.339200005, 1473962400], [42414060.339200005, 1473966000], [42414060.339200005, 1473969600], [42414060.339200005, 1473973200], [42414060.339200005, 1473976800], [42414060.339200005, 1473980400], [42414060.339200005, 1473984000], [42414060.339200005, 1473987600], [42414060.339200005, 1473991200], [42414060.339200005, 1473994800], [42414060.339200005, 1473998400], [42414060.339200005, 1474002000], [42414060.339200005, 1474005600], [42414060.339200005, 1474009200], [42414060.339200005, 1474012800], [42414060.339200005, 1474016400], [42414060.339200005, 1474020000], [42414060.339200005, 1474023600], [42414060.339200005, 1474027200], [42414060.339200005, 1474030800], [42414060.339200005, 1474034400], [42414060.339200005, 1474038000], [42414060.339200005, 1474041600], [42414060.339200005, 1474045200], [null, 1474048800]]}]`

Kind regards

**Comment by torkelo** [comment] 2016-09-19 07:02
Think this is caused by same root issue as https://github.com/grafana/grafana/issues/6070

the code here must be updated to better handle very flow diff (or no diff) between min/max
https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js#L1744

**Comment by alexanderzobnin** [comment] 2016-09-19 11:49
@terra-nova what type of unit are you using (on the _Axes_ tab)?

**Comment by terra-nova** [comment] 2016-09-19 17:43
@alexanderzobnin The unit is "bytes" from the "data" category.

**Comment by alexanderzobnin** [comment] 2016-09-19 20:24
@terra-nova Hm... Sorry, I can't replicate issue even using the same data: 

<img width="1280" alt="screen shot 2016-09-19 at 23 22 22" src="https://cloud.githubusercontent.com/assets/4932851/18647727/1057ce98-7ec0-11e6-8479-1af861b97ec1.png">

But anyway, this issue will be fixed with #6070.

**Comment by torkelo** [comment] 2016-09-20 09:38
fixed by https://github.com/grafana/grafana/pull/6082

**Closed by torkelo** 2016-09-20 09:38 UTC
Labels: type: bug
