### ISSUE TITLE
Browser crashes when opening my dashboard after updating to 7.3.2 

### ISSUE THREAD

**Issue by yurividal** [grafana/grafana#29139] opened 2020-11-16 18:36 UTC
I have grafana running on docker. My dashboard has tables, gauges, graphs and singlestat.
After upgrading to 7.3.2 my browser crashes immediately after opening the dashboard. Happens to chrome, firefox and mobile too.
Downgrading to 7.3.0 solves the issue, for now.

**Comment by booleanbetrayal** [comment] 2020-11-16 19:45
We are seeing this as well, upgrading from `7.3.1` to `7.3.2`. The failure seems to be happening with dashboard panels for **Pod Failed** in [this dashboard](https://grafana.com/grafana/dashboards/11663). JS locks up the browser and the tab must be killed (Firefox, Chrome). 

In `7.3.1` the **Pod Failed** panel reflects `0`. Perhaps this is related to the fix what went in via  #28982 ? 

Perhaps this has already been fixed via #29077 ...

I didn't see anything else potentially relevant in the release notes ...

**Comment by zoltanbedi** [comment] 2020-11-16 21:07
Yes sorry about that. 7.3.3 will be released on Monday or Tuesday with the fix for that.
/duplicate of #29073

**Closed by zoltanbedi** 2020-11-16 21:07 UTC
