### ISSUE TITLE
Bug: Grafana Unified Alerts - Time Range Picker - Value not in relative time format

### ISSUE THREAD

**Issue by ThePieMonster** [grafana/grafana#43605] opened 2021-12-31 22:21 UTC
**What happened**:
When entering in a relative time range per the [time range controls document](https://grafana.com/docs/grafana/latest/dashboards/time-range-controls/) 
![image](https://user-images.githubusercontent.com/11359134/147840112-605bd52b-c568-4c7c-92f5-b7a0b0a3b990.png)
a error is received saying that the time range in not a relative time range.
![image](https://user-images.githubusercontent.com/11359134/147840017-7d6e4c5a-c664-4458-a362-33daa3839457.png)

**What you expected to happen**:
No error is received and time range looks at the beginning of the current month to now.

**How to reproduce it (as minimally and precisely as possible)**:
Enable Unified Alerting, attempt to create a alert as shown in the above image. 

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Windows Server

**Comment by ivanahuckova** [comment] 2022-01-03 11:44
I was able to reproduce this in unified alerting's time picker. In dashboard's/explore's time picker this works as expected.

**Comment by ivanahuckova** [comment] 2022-01-04 13:00
Duplicate of https://github.com/grafana/grafana/issues/36154

**Closed by ivanahuckova** 2022-01-04 13:00 UTC
Labels: type/bug, area/alerting/unified
