### ISSUE TITLE
Grafana 8.1.3 plugin: Clock (colorizing doesn't work)

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#39163] opened 2021-09-14 06:45 UTC
**What happened**:
1. Background color doesn't work.
2. Transparent background doesn't work
3. Please add text color
![image](https://user-images.githubusercontent.com/73607094/133208539-58119290-3f07-4238-be47-80439bde7d84.png)

**What you expected to happen**:
Fix this
**How to reproduce it (as minimally and precisely as possible)**:
Add plugin to dashboard

**Environment**:
- Grafana version: 8.1.3
- Data source type & version: MS SQL
- OS Grafana is installed on: CentOs
- User OS & Browser: Chrome
- Grafana plugins: Clock
- Others: n/a

**Comment by torkelo** [comment] 2021-09-14 08:10
@deejayluk what version of the clock panel are you using?

**Comment by deejayluk** [comment] 2021-09-14 08:15
1.1.1 I will update to 1.1.3 and I check this issue

**Comment by deejayluk** [comment] 2021-09-14 08:20
1.13 it's ok but I have request to add change color text from black to white

**Comment by Elfo404** [comment] 2021-09-14 11:25
closing this as duplicate of (in clock-panel repo) https://github.com/grafana/clock-panel/issues/41

**Closed by Elfo404** 2021-09-14 11:25 UTC
