### ISSUE TITLE
Tooltip All shows on Shared Crosshair

### ISSUE THREAD

**Issue by gabrieljones** [grafana/grafana#37892] opened 2021-08-13 15:50 UTC
**What happened**:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18059585/129384670-b38e9395-4ee6-4143-bbc8-24294157aa02.png">

**What you expected to happen**:
Only the shared crosshair should appear

**How to reproduce it (as minimally and precisely as possible)**:
Turn on `Tooltip mode All` for all charts
Set Panel Options > Graph tooltip > Shared crosshair

**Environment**:
- Grafana version: v8.1.0 (62e720c06b)
- Data source type & version: https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1
- OS Grafana is installed on: https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1
- User OS: MacOS 10.15.7
- Browser:
  - Firefox 90.0.2
  - Firefox 91.0

**Comment by oscarkilhed** [comment] 2021-08-16 06:53
Reproducible on play but not locally on main. Need to figure out what commit fixed it and backport.

**Comment by oscarkilhed** [comment] 2021-08-16 07:09
Issue seems to be fixed on 8.1.x. Closing this.

**Closed by oscarkilhed** 2021-08-16 07:09 UTC
Labels: area/frontend
