### ISSUE TITLE
Failed to start renderer plugin: Unrecognized remote plugin message

### ISSUE THREAD

**Issue by nsteinmetz** [grafana/grafana#40188] opened 2021-10-08 07:01 UTC
**What happened**:

* Instance upgraded from 8.1.7 to 8.2.0
* grafana-render-image plugin upgraded to 3.2.1
* Grafana.ini file synced with defaults one in case options are missing
* Fix missing lib `libxshmfence1`
* Once plugin is installed and grafana restarted, grafana keeps up failing to start and loops on this:

```
Oct 08 08:54:53 crnt-d10-monitoring-gra grafana-server[16803]: t=2021-10-08T08:54:53+0200 lvl=eror msg="Stopped background service *rendering.RenderingService" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
Oct 08 08:54:53 crnt-d10-monitoring-gra grafana-server[16803]: t=2021-10-08T08:54:53+0200 lvl=warn msg="plugin failed to exit gracefully" logger=plugins.backend pluginId=grafana-image-renderer
Oct 08 08:54:54 crnt-d10-monitoring-gra grafana-server[16803]: t=2021-10-08T08:54:54+0200 lvl=eror msg="Server shutdown" logger=server error="*rendering.RenderingService run error: Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
Oct 08 08:54:54 crnt-d10-monitoring-gra grafana-server[16803]: *rendering.RenderingService run error: Failed to start renderer plugin: Unrecognized remote plugin message:
Oct 08 08:54:54 crnt-d10-monitoring-gra grafana-server[16803]: This usually means that the plugin is either invalid or simply
Oct 08 08:54:54 crnt-d10-monitoring-gra grafana-server[16803]: needs to be recompiled to support the latest protocol.
Oct 08 08:54:54 crnt-d10-monitoring-gra systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Oct 08 08:54:54 crnt-d10-monitoring-gra systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Oct 08 08:54:54 crnt-d10-monitoring-gra systemd[1]: grafana-server.service: Service RestartSec=100ms expired, scheduling restart.
Oct 08 08:54:54 crnt-d10-monitoring-gra systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 3.
Oct 08 08:54:54 crnt-d10-monitoring-gra systemd[1]: Stopped Grafana instance.
```

**What you expected to happen**:

GRafana starting as expected and grafana-render-image plugin working as expected :)

**How to reproduce it (as minimally and precisely as possible)**:

* Instance upgraded from 8.1.7 to 8.2.0
* grafana-render-image plugin upgraded to 3.2.1
* Grafana.ini file synced with defaults one in case options are missing
* Installing plugin
* Restarting grafana-server

**Anything else we need to know?**:

**Environment**:
- Grafana version:8.2.0
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 10.x - up to date
- User OS & Browser: Manjaro / Firefox
- Grafana plugins:
```
installed plugins:
grafana-piechart-panel @ 1.6.2
ovh-warp10-datasource @ 2.2.1
```
- Others:

**Comment by rtt-mmk** [comment] 2021-10-08 09:15
same on OS: Ubuntu 18.04.6 LTS

**Comment by rtt-mmk** [comment] 2021-10-08 10:11
on CentOS release 7.9.2009 there is no issue with the update to grafana-server 8.2 with grafana-image-renderer 2.0.1. Perhaps this littel info helps.

**Comment by peterdk** [comment] 2021-10-08 10:45
On 3 servers Grafana fails to start with this message after the upgrade. All Ubuntu 20.04

**Comment by ivanahuckova** [comment] 2021-10-08 11:00
I will close this issue for now as it seems like a duplicate of #40187.

**Closed by ivanahuckova** 2021-10-08 11:00 UTC
Labels: type/bug, area/backend/plugins, area/image-rendering
