### ISSUE TITLE
Incorrect generation of graphite queries (GET vs POST)

### ISSUE THREAD

**Issue by SUL-junger** [grafana/grafana#20851] opened 2019-12-03 22:08 UTC
**What happened**:
I want to build a new query in Grafana for a datasource that is accessed through graphite queries.
When I click in "Series > select metric" no dropdown with the available metric IDs appears. This is because of a 400 in the Graphite HTTP API Request:
![grafik](https://user-images.githubusercontent.com/25434102/70089934-6f912c80-1619-11ea-928d-2258e3630864.png)

**What you expected to happen**:
A deeper inspection shows:
Request URL: http://url.tld:3000/api/datasources/proxy/1/metrics/find?from=1575385513&until=1575407115

![grafik](https://user-images.githubusercontent.com/25434102/70090174-f0502880-1619-11ea-87de-081eac19131e.png)

So the parameter that fetches all metric IDs (query = *) is submitted as a form data in the POST Request.
According to [the official documentation](https://graphite.readthedocs.io/en/latest/feeding-carbon.html#) the api query should be build like this:

`GET /metrics/find?query=collectd.*`

If I use a GET Request like described my datasource responds correctly:

`curl "http://ip:port/api/v1/graphite/metrics/find?query=*&from=1575385513&until=1575407115"`

REST [specifies ](https://www.w3.org/2001/sw/wiki/REST) that _GET_ is used for receiving information while _POST_ is not specified.
Please correct me if my understanding is incorrect but Grafana should provide the option for users that only _GET_ Requests are used for any reading of data as this would be Graphite API compliant and REST compliant.

**How to reproduce it (as minimally and precisely as possible)**:
Add a Datasource to Grafana which uses the Graphite Query Language to receive data but is not a Graphite instance itself.

**Anything else we need to know?**:
In case you are wondering why my datasource can't handle the _POST_ request: It is a datasource (M3DB) which can be polled through the graphite API Query Language but it is not a graphite instance itself. This is why the graphite HTTP API specification is important here.

**Environment**:
- Grafana version: v6.5.1
- Data source type & version: M3DB v0.14.2
- OS Grafana is installed on: Debian 10
- User OS & Browser: Linux/Windows - Firefox

**Comment by papagian** [comment] 2019-12-04 11:34
@DanCech could you have a look at this? Should we permit GET requests?

**Comment by torkelo** [comment] 2019-12-04 11:38
What version of Graphite are you using?

**Comment by torkelo** [comment] 2019-12-04 11:40
This was done in order to support long queries. 
https://github.com/grafana/grafana/pull/17814

Graphite does support this. 
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/metrics/views.py#L56

**Comment by SUL-junger** [comment] 2019-12-04 11:54
> What version of Graphite are you using?

As stated in my report it is an M3DB which is accessed through the the Graphite Query language.

I understand the necessity of #17814 and I see how graphite-web uses _POST_ itself. However the Graphite API Documentation (which is reference for the Query language) does not mention this.

Would it be possible to add a Setting "Perform only _GET_ Requests" in the Webinterface which is disabled by default? With this feature grafana would be Graphite API compatible and not just compatible with Graphite Instances. Also this would enable M3DB integration in Grafana.

Proof that GET Requests are a fix for this Issue can be found [here](https://github.com/m3db/m3/issues/2000#issuecomment-561568823). If you use a HAProxy to modify the _POST_ Requests of Grafana everything works fine.

**Comment by DanCech** [comment] 2019-12-04 16:41
This seems like something that should be brought up with M3DB, not supporting POST is a bug in their implementation of the graphite query API.  It is definitely possible to construct valid queries that cannot be submitted via GET because they are too long.

**Comment by papagian** [comment] 2019-12-04 17:23
Following @DanCech's reply, I'm closing this.

**Closed by papagian** 2019-12-04 17:23 UTC

**Comment by SUL-junger** [comment] 2019-12-05 09:01
First of all thanks for your replies. I get your point.
Altough I cannot found _POST_ Requests in the [Graphite HTTP API](https://graphite-api.readthedocs.io/en/latest/api.html). This API is the reference for the M3DB Developers if they implement an Graphite API in their database. Is there any documentation available that describes the _POST_ Requests?

Thanks for your effort!

**Comment by papagian** [comment] 2019-12-05 09:15
@SUL-junger 
I had also difficulty finding it in the docs but if you check the [source code](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/metrics/views.py#L56) it supports POST.

**Comment by SUL-sj** [comment] 2019-12-05 14:32
[I asked the guys over @ graphite-web](https://github.com/graphite-project/graphite-web/issues/2519) about this code change with the _POST_ request. They confirmed that _GET_ is the only API compliant Request methode:

> Yes, it is. All alternative Graphite API implementations use GET IIRC. 

The _POST_ handling does only work for graphite as it has this implement additionally to the API Standard which uses _GET_.

With this information I would kindly like to ask if it this shouldn't be reconsidered to be an Issue because Grafana is not Graphite HTTP API compliant with this _POST_-only implementation.

**Comment by DanCech** [comment] 2019-12-05 15:03
I commented on your issue over there also, Denis was mistaken and graphite-web has accepted POST data since 2009 when support was explicitly added by Chris Davis, the original author of the project, see https://github.com/graphite-project/graphite-web/commit/6fe49b8c0e092466581ad2eafd57608612429b12 .  As noted in the referenced issue, the documentation should be updated to reflect that, and I would be happy to accept a PR to update the docs.

Implementations that do not support POST are not correctly implementing the API, and cannot accept queries that are too large to fit into GET requests.  If you need to support these implementations I would suggest bringing it up with their authors, and until they add support the approach you described above with a reverse proxy is a possible workaround.

**Comment by SUL-sj** [comment] 2019-12-05 15:56
Thank you for the clarification - too bad that the documentation of graphite hasn't been updated but at least I understand the situation now.
