### ISSUE TITLE
Template Var e.metricsFindQuery is Not a Function

### ISSUE THREAD

**Issue by BrandonQDixon** [grafana/grafana#20901] opened 2019-12-05 15:02 UTC
**What happened**: When I imported a dashboard, the template var gives e.metricsFindQuery is not a function. The data is not loaded, and the request to the server is never actually sent. Note, this is not a problem in the dashboard I originally imported from.

**What you expected to happen**: Query would load as normal

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: Create a basic dashboard with JSON datasource. Then, create new installation of Grafana elsewhere, copy Grafana database, and load dashboard.

**Environment**:
- Grafana version: 6.2.5
- Data source type & version:  JSON Datasource – a generic backend datasource 0.1.5
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows, Chrome
- Grafana plugins: JSON Datasource – a generic backend datasource
- Others: Note that this does work on original dashboard (before importing)

EDIT: I should also mention, this seems to only affect dashboard parameters, not the panels themselves.

*Notes:* 

- There is a datasource with the name of the datasource I am trying to use
- The query is valid
- Everything works on the original Grafana instance
- In the inspector, the request is never made to the backend.
- This post was originally made [here](https://github.com/grafana/grafana/issues/20636), but it was closed without the issue actually being addressed, so I've re-opened here.

**Comment by marefr** [comment] 2019-12-05 17:36
Duplicate of #20636

**Closed by marefr** 2019-12-05 17:36 UTC
