### ISSUE TITLE
Binary operation with variable

### ISSUE THREAD

**Issue by MonSansFil** [grafana/grafana#29587] opened 2020-12-03 18:19 UTC
**What happened**:
When I put a variable in a binary operation, calculatation isn't working.

`    {
      "id": "calculateField",
      "options": {
        "binary": {
          "left": "changePercent / 100 + 1",
          "operator": "*",
          "reducer": "sum",
          "right": "$cost"
        },
        "mode": "binary",
        "reduce": {
          "reducer": "sum"
        },
        "replaceFields": true
      }
    }`

The variable is 1000 and set via a textbox.

**What you expected to happen**:
Binary operation to to *1000 instead of nothing

**Environment**:
- Grafana version: 7.3.3
- Data source type & version: influxdb 1.8
- OS Grafana is installed on: linux/docker
- User OS & Browser: windows10 / chrome

Regards,

**Comment by ivanahuckova** [comment] 2020-12-06 13:07
@ryantxu Not sure if this is considered bug or feature request.

**Comment by aocenas** [comment] 2021-04-09 09:43
Seems like this is a duplicate of https://github.com/grafana/grafana/issues/25469

**Closed by aocenas** 2021-04-09 09:43 UTC
Labels: area/dashboard/templating, datasource/InfluxDB, needs investigation, type/feature-request
