### ISSUE TITLE
[Bug] Heatmap tooltip broken when data format is "Time series buckets"

### ISSUE THREAD

**Issue by anttirt** [grafana/grafana#9795] opened 2017-11-06 09:55 UTC
- What Grafana version are you using?
4.6.0

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Linux

- What did you do?
View heatmap panel with prebucketed data (Data format = "Time series buckets")

- What was the expected result?
I see a tooltip with data about a heatmap cell when mouse-hovering over the cell

- What happened instead?
The tooltip is blank and I get an uncaught TypeError in the console

Stack trace (printed every time the mouse moves on top of a cell):
```
heatmap_tooltip.ts:175 Uncaught TypeError: Cannot read property 'bottom' of undefined
    at heatmap_tooltip.ts:175
    at n (lodash.js:5096)
    at M (lodash.js:823)
    at ds (lodash.js:7275)
    at Function.find (lodash.js:5098)
    at t.show (heatmap_tooltip.ts:174)
    at HTMLDivElement.et (rendering.ts:709)
    at HTMLDivElement.dispatch (jquery.js:5206)
    at HTMLDivElement.g.handle (jquery.js:5014)
```

`bucket.bounds` seems to be `undefined` when the format is "Time series buckets"

[Panel JSON and InfluxDB response body](https://github.com/grafana/grafana/files/1445722/data.tar.gz)

**Comment by torkelo** [comment] 2017-11-06 12:01
duplicate of https://github.com/grafana/grafana/issues/9332

**Closed by torkelo** 2017-11-06 12:01 UTC
