### ISSUE TITLE
Provisioning API: Support deleting a rule group

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#81860] opened 2024-02-05 08:11 UTC
**Why is this needed**:

The Provisioning API can be used to create or update rule groups using a PUT request. However, rule groups cannot be DELETEd in a single call. To remove a rule group, it seems one must either DELETE each individual rule one-by-one, at which point the group is also deleted.

**What would you like to be added**:

Support calling DELETE on the `/api/v1/provisioning/{FOLDERUID}/rule-groups/{GROUPNAME}` endpoint. This should delete both the group and all of its component rules.

This is considerably more intuitive than having the rule group disappear after the rules are deleted one-by-one.

**Who is this feature for?**

All users of the provisioning API who deal with alert groups.

**Comment by armandgrillet** [comment] 2024-02-08 16:47
This is a duplicate of https://github.com/grafana/grafana/issues/53136.

**Comment by joeblubaugh** [comment] 2024-02-27 01:15
@armandgrillet I'm happy to take this on - it will be useful for some other work I'm doing.

**Closed** 2024-02-28 15:19 UTC
Labels: type/feature-request, area/alerting, good first issue
