### ISSUE TITLE
$__interval doesn't scale with Loki query resolution value

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#52290] opened 2022-07-14 20:05 UTC
**What happened**:

I tried scaling the interval resolution of a Loki metrics query by changing the resolution from `1/1` to `1/10` and I discovered that the `step` parameter was adjusted, but not the `$__interval` variable.

**What you expected to happen**:

The `$__interval` variable should be scaled the same way as the `step` parameter.

**How to reproduce it (as minimally and precisely as possible)**:

Write a LogQL metrics query which uses `$__interval`. For example:

    sum(count_over_time({nodename="wf-test-01"}[$__interval])) by (syslog_identifier)

Unlike the Prometheus query inspector, the Loki query inspector does not show the interpolated `$__interval` value.

![Screenshot 2022-07-14 15-58-44 query inspector](https://user-images.githubusercontent.com/3270755/179073246-e3dcf081-67c9-4607-a5de-f3a762edb426.png)

In my Loki logs, I was able to capture the actual query (newlines added for readability):

```
level=info
ts=2022-07-14T19:56:33.176209103Z
caller=metrics.go:92
org_id=fake
latency=fast
query="sum(count_over_time({nodename=\"wf-test-01\"}[10ms])) by (syslog_identifier)"
query_type=metric
range_type=range
length=23.557s
step=100ms
duration=30.844561ms
status=200
limit=1000
returned_lines=0
throughput=2.0MB
total_bytes=63kB
```

As you can see, the `step` was scaled from `10ms` to `100ms`, but the `$__interval` value stayed at `10ms`.

**Anything else we need to know?**:

In Prometheus, I can set the "Min interval" and it works as expected. The query inspector also makes it easier to see what's going on.

![Screenshot 2022-07-14 16-03-02 prometheus](https://user-images.githubusercontent.com/3270755/179073286-0ee1528b-7fce-4d41-b5e0-1953783fe339.png)

**Environment**:
- Grafana version: v9.0.2
- Data source type & version: Loki
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by gabor** [comment] 2022-07-18 09:24
hi @adeverteuil thanks for the detailed issue description!

there are multiple topics there, i'll try to go through them one by one:
- the behavior os `resolution` not modifying `$__interval` is not "incorrect" as such.
    - if you check our documentation at https://grafana.com/docs/grafana/latest/datasources/loki/ , `resolution` is described to deal with `step`, which it does. one may argue, that scaling `$__interval` too is "better", but it's hard to say. i do understand that this whole `interval`/`step`/`min_interval`/`resolution` combination is confusing, i created a new github issue at https://github.com/grafana/grafana/issues/52387 to try to improve the situation somehow. i do not know yet what's the best way to move forward.
    - also, this worked like this in the past too, so if we change it, it's a breaking change. 
    - (additionally, please note, even in the Prometheus datasource we are going slowly away from `resolution`, if you create a new dashboard-panel, `resolution` is not there anymore.)
- the `Min interval` dashboard setting affects both `step` and `$__interval` based on my testing in Grafana9.0.2. i cannot reproduce any problem there. if you think something is wrong there, could you please send a more detailed description of what is wrong?
- i can see the interpolated interval-value on the dashboard query inspector in Grafana9.0.2, like this, what do you think is missing?: <img width="771" alt="interval" src="https://user-images.githubusercontent.com/51989/179482234-05081373-b2a7-4ce0-a6f9-57f255c12c48.png">
 
thanks!

**Comment by adeverteuil** [comment] 2022-07-21 17:23
Hi @gabor, thank you for looking into this.

> if you check our documentation at https://grafana.com/docs/grafana/latest/datasources/loki/ , resolution is described to deal with step, which it does.

Yes, but the documentation at https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__interval says that the `$__interval` variable is synced to the interval calculated by Grafana, so that query functions can summarize the data between time intervals.

The interval can be changed using the "Min interval" and "Max data points" [query options](https://grafana.com/docs/grafana/latest/panels/query-options/), or the "Min interval" and "Resolution" parameters in the data source's query editor. In all cases, the query interval (aka "step" in Prometheus vocabulary) is updated, and the `$__interval` variable should be updated as well.

> the "Min interval" dashboard setting affects both step and `$__interval` based on my testing in Grafana9.0.2. i cannot reproduce any problem there.

That's correct, the "Min interval" query parameter correctly adjusts both the query `step` parameter and the `$__interval` variable. The problem only appears with the Resolution parameter.

As you can see in the Explore and the dashboard screenshots, by reducing the Resolution to `1/5`, the step is increased by a factor of 5, but the `$__interval` didn't change. This is a problem because now the `count_over_time()` function is "blind" to 4/5 of the query range, and many log lines are not counted.

![Screenshot 2022-07-21 08-16-52 dashboard](https://user-images.githubusercontent.com/3270755/180211935-5a94b5da-2894-44fc-8780-d289eb44a022.png)
![Screenshot 2022-07-21 08-15-47 explore](https://user-images.githubusercontent.com/3270755/180211936-7a21b207-9934-40a8-a315-a3bf64243e88.png)

Furthermore, the Prometheus data source, before the Resolution parameter was removed, correctly adjusted the `step` query parameter **and** the `$__interval` variable. Tested on Grafana v8.0.5.

![Screenshot 2022-07-21 08-30-18 prom on v8 0 5](https://user-images.githubusercontent.com/3270755/180213871-aca55f1f-567a-494d-a0df-676455ee206d.png)

I understand your two counter points:
* This worked like this in the past too, so if we change it, it's a breaking change.
* We are going slowly away from resolution.

This might mean there is no point investing effort in fixing this issue. I did like the Resolution parameter though. I might put a feature request to have it added to the Query options.

> i created a new github issue at https://github.com/grafana/grafana/issues/52387 to try to improve the situation somehow. i do not know yet what's the best way to move forward.

I added comments with a few pointers in the issue you created.

**Comment by gabor** [comment] 2022-07-22 05:43
hi @adeverteuil thanks for the detailed feedback. it's a good point about `count_over_time` not "covering" a scaled step, i'll copy that over to the newly created issue too. i'll close this one for now.

**Closed by gabor** 2022-07-22 05:43 UTC
Labels: needs more info, datasource/Loki

**Comment by gabor** [comment] 2022-07-22 05:45
@adeverteuil  wrote:
> I did like the Resolution parameter though. I might put a feature request to have it added to the Query options.

that's a great idea!

my general problem with all the "prometheus specific" extra functionality (min_step, resolution etc.) is that they kind of duplicate what grafana does already, but if we could get something "resolution-ish" into the query-options, that would work transparently, and in every datasource, automatically.

**Comment by adeverteuil** [comment] 2022-07-25 17:23
I followed-up with a feature request here: https://github.com/grafana/grafana/discussions/52752
