### ISSUE TITLE
SMTP alert notification is not working

### ISSUE THREAD

**Issue by aksh1** [grafana/grafana#8069] opened 2017-04-07 14:06 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using?
4.2
- What datasource are you using? influxDB
- What OS are you running grafana on?
Ubunyu 14.04

I am trying to send email via SMTP, though the "Test Notification is Sent " is visible on clicking SEND TEST button, but not receiving any mails

In Grafana Log this msg is keep coming
![screenshot from 2017-04-07 19 33 20](https://cloud.githubusercontent.com/assets/8931402/24803605/58ecb8ca-1bc9-11e7-9908-472665ca7c89.png)

And I am not getting any mail

**Comment by daniellee** [comment] 2017-04-07 15:10
Wondering if this might be related to #7189 but I do not see any TLS handshake errors in the output there. Any other information you can give us to help with the troubleshooting?

**Comment by aksh1** [comment] 2017-04-10 06:07
Hi Daniel,

Yeah I checked this issue #7189 but not able to solve my problem.
I am getting test notification on Slack here is the screenshot
![screenshot from 2017-04-10 11 28 24](https://cloud.githubusercontent.com/assets/8931402/24847877/8ac791ca-1de1-11e7-93af-9e921fc8c418.png)

But when I am using mail I dont get any emails though the notification "Test email sent " is shown on the right. Here is grafana SMTP config 
![screenshot from 2017-04-10 11 29 25](https://cloud.githubusercontent.com/assets/8931402/24847940/e8129bcc-1de1-11e7-8044-942919c4d301.png)
Please help I need Email feature of grafana alert.
Thanks for helping

**Comment by daniellee** [comment] 2017-04-10 08:58
As you are not getting any errors (which you usually do when SMTP does not work), can you double check that the SMTP server is working. Are you sure it is configured correctly? Do invites work for example?

![image](https://cloud.githubusercontent.com/assets/434655/24853747/6248fffe-1ddc-11e7-8b40-493b1cd602f8.png)

**Comment by aksh1** [comment] 2017-04-10 09:41
No, I am not getting errors, If I am then it would be in logs. Yes, the SMTP server and the configuration is correct as defined in docs. 
![screenshot from 2017-04-10 15 02 34](https://cloud.githubusercontent.com/assets/8931402/24855589/abdb40a0-1dff-11e7-98a3-60e38857b42e.png)
I am able to get this notification on the right which also means that everything is configured corrrect, otherwise it through error here also.

**Comment by daniellee** [comment] 2017-04-10 16:28
Can you confirm that the SMTP server sends emails. The best test would be to test sending an email outside of Grafana with the same settings if possible otherwise try sending an invitation to confirm that an actual email is sent to your inbox. If there are no errors in Grafana, then I suspect that the problem is not to do with Grafana.

**Comment by aksh1** [comment] 2017-04-11 06:52
Hi Daniel, 
Yes, I tried it also but only getting notification not actual email on my account.
![screenshot from 2017-04-11 12 18 22](https://cloud.githubusercontent.com/assets/8931402/24896169/48e11f76-1eb1-11e7-805d-b035fb30a2c7.png)

Please help

**Comment by daniellee** [comment] 2017-04-11 16:05
So the problem is that your email server does not work? Can I close this issue then?

**Comment by externl** [comment] 2017-04-12 12:56
@daniellee I think he means that Grafana gives a visual notification the the email was sent but the email is never sent.

I'm also experiencing this. SMTP is configured (and works with other clients), Grafana gives visual 
notification saying email was sent, however my smtp server never receives anything. This used to work and I have not change my configuration.

**Comment by externl** [comment] 2017-04-12 13:35
After digging into this a little more it appears that for some reason I was on v4.0.2, not v4.2.0. My SMTP api key was also expired so was no longer working. I think this old version of Grafana just did not report an error correctly, v4.2.0 did.

@aksh1, are you sure you're on v4.2.0 and not v4.0.2?

**Comment by daniellee** [comment] 2017-04-29 20:06
Closing this issue. I can reopen if you have a found a bug or cannot get it to work.

**Closed by daniellee** 2017-04-29 20:06 UTC
Labels: state: needs more detail

**Comment by ZoeThivet** [comment] 2017-05-22 04:10
This one may help someone: try sending the test e-mail to different types of e-mail addresses.

I realized my **Gmail** address would receive the e-mail (but put it in the spam folder) whereas my **Outlook** e-mail address didn't receive the e-mail at all.

So I guess, sometimes the problem has nothing to do with Grafana itself.

**Comment by Zero3** [comment] 2017-06-15 15:22
Mails sent from GrafanaCloud is going straigh to my spam folder in my Office365 mail account too. The relevant headers explain why:

> X-Forefront-Antispam-Report: CIP:104.130.122.5;IPV:NLI;CTRY:;EFV:NLI;**SFV:SPM**;SFS:(8196002)(31640200002)(2980300002)(438002)(286005)(359002)(199003)(349900001)(189002)(349012);DIR:INB;SFP:;**SCL:9**;SRVR:VI1PR0602MB2991;H:mail5.static.mailgun.info;FPR:;SPF:Pass;MLV:ovrnspm;A:1;MX:1;PTR:mail5.static.mailgun.info;CAT:HSPM;LANG:en;

From https://technet.microsoft.com/en-us/library/dn205071.aspx: "The message was marked as spam by the content filter."

From https://technet.microsoft.com/en-us/library/jj200686.aspx: "High confidence spam" + "Deliver the message to the recipients’ Junk Email folder."

I'm not sure what will solve this besides people marking the mails as non-spam. Perhaps changing the generic test notification to include personalized information (User name, organization name, randomized values/graph) and removing stuff like remote images will make the mails more spam filter friendly.

>X-Microsoft-Antispam: UriScan:;**BCL:8**;PCL:0;RULEID:(23075)(22001)(8251501002)(3001016)(71702078);SRVR:VI1PR0602MB2991;

From https://technet.microsoft.com/en-us/library/dn759623(v=exchg.150).aspx: "The message is from a bulk sender that generates a high number of complaints"

As I read this, it means that the server you send mails from at Mailgun sends too many mails that people mark as spam, so Microsoft is blocking it.

**Comment by externl** [comment] 2017-06-15 15:33
@Zero3 I think you should probably open a separate issue for this.

**Comment by Zero3** [comment] 2017-06-15 15:38
@externl You are probaby right. Done!
