### ISSUE TITLE
Resolution dropdown disappears when choosing "1/1"

### ISSUE THREAD

**Issue by larshove** [grafana/grafana#50393] opened 2022-06-08 09:52 UTC
**What happened**:
Editing a graph panel (with Prometheus as a data source) and changing "Resolution" to "1/1" makes the whole dropdown disappear.

**What you expected to happen**:
That the dropdown does not disappear.

**How to reproduce it (as minimally and precisely as possible)**:
Editing a graph panel (with Prometheus as a data source) and changing "Resolution" to "1/1" makes the whole dropdown disappear.

**Anything else we need to know?**:
It worked in 8.4.7 but in all newer versions (including 9.0.0) it does not work.

**Environment**:
- Grafana version: 8.5.5.
- Data source type & version: Prometheus 2.36.0
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Chrome
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment] 2022-06-08 12:27
duplicate of https://github.com/grafana/grafana/issues/48081

**Closed by torkelo** 2022-06-08 12:27 UTC
