### ISSUE TITLE
Layout pops up offscreen: "More ..." popup partially clipped off right-edge of dashboard

### ISSUE THREAD

**Issue by nrichards** [grafana/grafana#15736] opened 2019-03-01 20:18 UTC
The popup for charts is incompletely drawn within the browser window, when popping up near the right-edge of the browser. 

See attachment for "Step 1, 2, 3" style illustration of issue. 

![image](https://user-images.githubusercontent.com/704698/53663905-dd886d80-3c1b-11e9-97fe-e23b3a2536fd.png)

Might be related to #13101. Workaround is to move the chart further to the left, or to resize the chart's width wider.

### What Grafana version are you using?
Grafana v5.4.2 (d812109)
### What datasource are you using?
Prometheus
### What did you do?
*Reproduce*

1. Create a small chart, small width-wise
1. Place the chart on the right edge of the dashboard
1. Click the titlebar. A menu should appear, with a drop-shadow.
1. Click the "More ..." menu. 

### What was the expected result?
*Expectation* 

That the "More ..." menu contents will be laid out on screen, when the popup's x+width or y+height exceeds the bounding view's dimensions.

### What happened instead?
You will see the drop-shadow partially eclipsed. You will NOT see the contents of the "More ..." menu

**Comment by torkelo** [comment] 2019-03-04 09:25
duplicate of https://github.com/grafana/grafana/issues/15692

**Closed by torkelo** 2019-03-04 09:25 UTC
