### ISSUE TITLE
Panel Link-Field is redrawn during streaming

### ISSUE THREAD

**Issue by MrLight** [grafana/grafana#39786] opened 2021-09-29 14:14 UTC
**What happened**:
The Link-Field in a Panel like a timeseries graph is redrawn during live-streaming which makes it impossible to click.
 
**What you expected to happen**:
The link shouldn't be redrawn when the graph is refreshed.
Could be possible linked to #39485 

**How to reproduce it (as minimally and precisely as possible)**:
Create a link in a panel and activate (fast) streaming.
![linkrefresh](https://user-images.githubusercontent.com/566059/135286365-125c70d6-6bc5-43bf-9adb-09cbb205a2ba.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: custom
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment] 2021-10-04 12:49
Think this ain't a time series issue but a general issue with the panel being redrawn when a new data arrives.

**Comment by ashharrison90** [comment] 2021-10-05 10:12
hi @MrLight 👋  
thanks for raising this.

i think this is currently working as designed. since panel links can depend on variables from the data, they have to be recalculated when the data changes.

there is a `stop streaming` button in the upper right hand corner of any streaming panel:

![image](https://user-images.githubusercontent.com/20999846/136001331-329a331c-9fbe-4ac6-8648-3343432d5504.png)

pressing that will stop rerendering the panel temporarily and will allow you to click your panel link. 

appreciate that's not a completely optimal experience, but it would be a disproportionate amount of work to extract out panel links, calculate whether they're actually depending on a variable in the data and only then rerender them. i think we'd be extremely unlikely to ever prioritise that work over other higher impact features, so i'm going to close this as working as designed.

hope that makes sense!

**Closed by ashharrison90** 2021-10-05 10:12 UTC
Labels: type/bug, type/works-as-intended, area/streaming
