### ISSUE TITLE
There is no pod/container name in grafana dashboard. However it is displaying the graph.

### ISSUE THREAD

**Issue by nitinkansal1984** [grafana/grafana#26249] opened 2020-07-10 20:21 UTC
**What happened**:
![New Bitmap Image](https://user-images.githubusercontent.com/31030410/87198812-e0dc4080-c2c8-11ea-8ae2-ac647955ae0b.jpg)

**What you expected to happen**:

There is no pod/container name in grafana dashboard. However it is displaying the graph.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.0.6
- Data source type & version: Prometheus v2.1.0
- OS Grafana is installed on: Kubernetes - EKS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment] 2020-07-13 12:01
Can you please add steps to reproduce this?

**Comment by torkelo** [comment] 2020-08-09 06:42
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.

**Closed by torkelo** 2020-08-09 06:42 UTC
Labels: needs more detail
