### ISSUE TITLE
alerting and nested queries in graphite datasource

### ISSUE THREAD

**Issue by errx** [grafana/grafana#9995] opened 2017-11-27 10:47 UTC
Please include this information:
- What Grafana version are you using?  latest master
- What datasource are you using? graphite
- What OS are you running grafana on? linux
- What did you do?
step1: create new dashboard, add first query (for example it will be #A and just one simple metric)
step2: add second query with query #A  (for example aliasByMetric(#A))
step3: add third function that uses #A and #B (for example divideSeries(#B, #A))
step3: setup alerting
step4: press test
- What was the expected result?
test response should contain something like that:
message:"Condition[0]: Eval: false, Metric: divideSeries(metric1, metric1), Value: 1.000"

- What happened instead?
message:"Condition: Eval: false, Query Returned No Series (reduced to null/no value)"

And here is the alert saved in the database:
"target":"divideSeries(#B, #A)","targetFull":"divideSeries(aliasByMetric(#A), constantLine(4))"

**Comment by errx** [comment] 2017-11-27 13:30
probably already fixed in current master

**Comment by errx** [comment] 2017-11-28 10:59
probably because of this https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/graphite_query.ts#L196

**Comment by Krinkle** [comment] 2017-12-02 00:51
Looks like a duplicate of https://github.com/grafana/grafana/issues/9917

**Comment by torkelo** [comment] 2018-01-10 08:57
dupe of https://github.com/grafana/grafana/issues/9917

**Closed by torkelo** 2018-01-10 08:57 UTC
