### ISSUE TITLE
Log panel: Display also common labels

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20449] opened 2019-11-18 15:57 UTC
**What would you like to be added**:

I would love to see labels in the logs panel, as shown on explore, as well as common labels.

**Comment by hugohaggmark** [comment] 2019-11-19 06:34
Thanks @roidelapluie for adding this feature request. Could to see that there is interest in developing the LogsPanel further!

**Comment by aocenas** [comment] 2020-02-05 13:18
Hey @roidelapluie, I think this should be already implemented you just need to toggle it in the panel settings. Going to close this now but please reopen if it isn't what you meant.
<img width="606" alt="Screenshot 2020-02-05 at 14 18 05" src="https://user-images.githubusercontent.com/1014802/73845180-5a579a80-4822-11ea-880c-680f57012ac8.png">

**Comment by corford** [comment] 2020-02-18 14:50
@aocenas For Loki based Log panels, the option in the panel settings is called "Unique labels". The problem is that if you enable this, the Log panel **does not** show common labels at the top (like in Explore).
![image](https://user-images.githubusercontent.com/1439558/74746446-5df51380-525d-11ea-8dcc-8da75c0a9873.png)
![image](https://user-images.githubusercontent.com/1439558/74746840-f095b280-525d-11ea-936b-b4551f35de0c.png)

**Comment by aocenas** [comment] 2020-02-18 16:37
Ah you are right did not realise that.

**Closed** 2021-07-01 12:06 UTC
Labels: area/panel/logs, type/feature-request
