### ISSUE TITLE
Backspace in query textbox navigates back instead of deleting text

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana#22243] opened 2020-02-17 06:24 UTC
**What happened**:

Quite often I press backspace in a Prometheus query edit textbox and find the page navigating back.

**What you expected to happen**:

I expected the backspace to delete the last character before the cursor in the textbox.

**How to reproduce it (as minimally and precisely as possible)**:

Unknown. It seems to be an issue of the textbox looking like it has focus (blinking cursor) but not actually having focus. I have a feeling that this happens when I click on a textbox. see it has a cursor now, and then try to start deleting - but despite having the blinking cursor, the backspace does not go to the textbox.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux (container)
- User OS & Browser: Firefox 73 on Windows 10
- Grafana plugins: Zabbix
- Others:

**Comment by Estrax** [comment] 2020-04-28 22:25
@sandersaares which edition and version of Windows 10 do you use? I'll try to reproduce it on exactly the same environment, because I was unable to do it on a default installation of Windows 10 Pro r1909. As for Firefox, what's the value you have in `browser.backspace_action` in `about:config`?
My assumption is that either you click outside of the input field somehow or you have backspace action mapped in Firefox settings.

**Comment by Estrax** [comment] 2020-05-03 20:53
Doubly checked and it looks like it works properly. The only case when it can go back in firefox is either when you have an overwritten `backspace action` in Firefox config or when you click outside of the input field. Closing this issue.

**Closed by Estrax** 2020-05-03 20:53 UTC
Labels: area/frontend, datasource/Prometheus
