### ISSUE TITLE
Loki log dashboard still not working since 8.3.2

### ISSUE THREAD

**Issue by smijolovic** [grafana/grafana#44403] opened 2022-01-24 22:34 UTC
Previous issue with 8.3.3 was closed by bot, and still persists with 8.3.4

The issue is NOT Loki or promtail. It is the presentation of the Loki logs on the dashboard not updating as they used to prior to 8.3.3.  Building 8.3.2 from source works as expected on the same setup and configuration of loki, promtail, and grafana...so it definitely is something with grafana.

When I run explore with live tailing, the logs show up instantly:

<img width="1300" alt="Screen Shot 2022-01-24 at 5 28 02 PM" src="https://user-images.githubusercontent.com/56645123/150875654-bfbd974b-9948-46e9-84e6-dd9977edf026.png">

But does not show up on the grafana dashboard:

<img width="1295" alt="Screen Shot 2022-01-24 at 5 29 48 PM" src="https://user-images.githubusercontent.com/56645123/150875827-1b8f24da-ef9f-4202-b07d-af2e00b6cdcd.png">

When I refresh the page (browser refresh) they show up:

<img width="1264" alt="Screen Shot 2022-01-24 at 5 30 58 PM" src="https://user-images.githubusercontent.com/56645123/150876026-67169d60-03d7-42e9-b62b-bc8e35d4ba1b.png">

Was something changed in 8.3.3 source wrt defaults on data injestion rate or size? It's as if there is some rate limiting going on specifically on the dashboard.  The dashboard json for logs:

 {
      "datasource": "Loki",
      "gridPos": {
        "h": 13,
        "w": 24,
        "x": 0,
        "y": 60
      },
      "id": 188,
      "options": {
        "showTime": true,
        "sortOrder": "Descending"
      },
      "repeat": null,
      "repeatDirection": "h",
      "targets": [
        {
          "expr": "{job=\"chaasm-logs\"}",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "CHAaSM Logs",
      "transparent": true,
      "type": "logs"
    }

**Comment by gabor** [comment] 2022-02-18 14:36
hi @smijolovic , when comparing explore-results to dashboard-results, are you running the dashboard with an auto-refresh?

in other words, is the problem that when the dashboard auto-refreshes, new log lines do not become visible, and you have to do a full browser refresh? or is the problem something else?

(i did a quick test with grafana, and have a loki panel in a dashboard with auto-referesh=5s, and it keeps refreshing).

- could you try with grafana-8.4.1?
- also, if it still does not work, which browser do you use?

**Comment by gabor** [comment] 2022-02-21 11:45
@smijolovic i'm glad it worked.

the problem is, i am unable to reproduce this in grafana 8.3.3 (using the grafana docker image). i created a new dashboard with a logs-panel and loki-datasource, i added a query, saved the panel. in the dashboard i choose 5seconds auto-refresh and the content of the logs panel kept changing every 5 seconds.

if you're still interesting in this: could you try to use a grafana 8.3.3 instance, and create a completely new dashboard, with a new panel, add the query, no customization, save, back to dashboard, set refrest to 5seconds, and see if it ever changes?

also, which browser do you use? (i tested on chrome&firefox&safari, and it worked)

**Comment by smijolovic** [comment] 2022-02-21 19:40
It's strange that the docker images are not seeing the same issue. 

The entire supply chain is compiled from source to threat profile all code for security reasons, including all compilers. I have to assume that this wasn't the issue, because the behavior is now working with the 8.4.1 builds in this same fashion. Our datasource is rsyslog output to a facility that is then pulled via promtail into Loki. I have to also assume that the dashboard was not the issue - or it still would not be functioning.

The browser we use for testing is firefox (Mac).

I'm really wondering if the issue is related to a defaults.ini configuration that changed in the 8.3.3 release. I synched up the 8.4.1 defaults.ini to my ini file. There were only a small amount of variations between 8.3.2 through 8.4.1. A diff between those two releases might just determine the culprit. I remember that a number of default configs changed around that time, thus leading me to believe that some line size/cache/buffer threshold somewhere was being tripped.

**Comment by gabor** [comment] 2022-02-23 13:11
hi, it's an interesting idea with the `defaults.ini` changes. unfortunately, as we cannot reproduce it, there's nothing we can do. my only idea is that if you want to spend the time, it should be possible to `git bisect` between 8.3.2 and 8.3.3 (should be around 10 steps), and that should find the commit that broke this. with that information we could try to find out why it is not working for you in 8.3.3 & 8.3.4. for now i'll close the issue (as it is working in 8.4.1), if you find more information just reply back and we can continue. thanks!

**Closed by gabor** 2022-02-23 13:11 UTC
Labels: needs more info, datasource/Loki
