### ISSUE TITLE
[Cloudwatch] - Using Template Variables in Query Dimensions Breaks Query After 9.0

### ISSUE THREAD

**Issue by disfluxly** [grafana/grafana#54338] opened 2022-08-26 16:17 UTC
**What happened**:
After upgrading from Grafana 8 to Grafana 9.0.5, any existing dashboard panels that are using a Template Variable in the Dimensions field no longer work.

**What you expected to happen**:
I expect that existing panels that use Template Variables continue to work as they did before the upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new dashboard in Grafana 8. In a dashboard variable, add in a value. (For example, an S3 Bucket Name). In your Cloudwatch Query, using the drop-down, add in the Template Variable as the value in the Dimension (For example, the `BucketName` dimension in an AWS/S3 query). Finish the rest of the query. Then upgrade to Grafana 9.

At this point, the panel doesn't show any data. Editing the panel and deleting the dimensions, then adding them in the same order as you did the first time around, you will not be able to add in any dimensions after adding the one that includes the Template Variables. This causes the query to be incomplete and doesn't work.

![image](https://user-images.githubusercontent.com/31159882/186948462-7201b470-3421-40ac-b101-df62a4a59290.png)

In the above image, the next Dimension Drop-down should be for `StorageType`, as shown in the image below when specifying `*` or any value directly from the drop-down, but as you can see above, the dimension drop-down is empty.

![image](https://user-images.githubusercontent.com/31159882/186948716-482c3e64-1df4-47d1-8be1-85419de07f35.png)

**Anything else we need to know?**:
I've tested this using both `Custom` type Template Variables, and also `Query` type Template Variables.

This is happening for any Cloudwatch namespace queries, but I've only shown examples above for `AWS/S3`.

This only happens for dashboards that existed before the upgrade.

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Centos
- User OS & Browser: MacOS / Chrome (Tried Firefox as well)
- Grafana plugins:
- Others:

**Comment by disfluxly** [comment] 2022-08-26 17:12
I did some more testing, and discovered that this seems to _only_ impact Panels that existed prior to upgrading.

I'll update the description with that information, as "New" dashboards/panels do seem to work

**Comment by fridgepoet** [comment] 2022-08-29 10:37
Hi @disfluxly 

I went from a panel in Grafana v8.4.7 to v9.0.5 and wasn't able to "lose" the dimension key as you showed.
What specific version of Grafana 8 did you upgrade from?

**Comment by disfluxly** [comment] 2022-08-30 15:35
Hey @fridgepoet  - We were on 8.5.10.

I've also since done some more testing, and I discovered the JSON changes that seem to break it. However, I can't seem to always recreate this, as it appears some Cloudwatch Panels that have gone through the upgrade came out just fine, while others have issues. I'm not entirely sure why, but I'm wondering if it's perhaps a bug from a much previous version that just now has started causing issues.

I discovered that the issue seems to have happened more frequently to panels where the datasource came from a template variable as well (although I did have 1 case where it was a specifically selected Cloudwatch datasource that had this problem). To note, I have over 100 cloudwatch datasources.

It appears that as part of the migration, the `targets` section of the JSON failed to carry over, but the overarching `datasource` section continued to be the cloudwatch type. I think this basically told the GUI to use the Cloudwatch panel editor, but under the hood, it was actually attempting to query Grafana's built in `Random Walk` dataset. This is shown below.

Here's the section of the JSON with just the datasource and targets sections for a panel that broke post-upgrade:

```
{
    "datasource":
    {
        "type": "cloudwatch",
        "uid": "${cw_ds}"
    },
    ....
    ....
    "targets":
    [
        {
            "alias": "",
            "dimensions":
            {
                "BucketName": "$s3_bucket",
                "StorageType": "StandardStorage"
            },
            "expression": "",
            "id": "",
            "matchExact": true,
            "metricEditorMode": 0,
            "metricName": "BucketSizeBytes",
            "metricQueryType": 0,
            "namespace": "AWS/S3",
            "period": "",
            "queryType": "randomWalk",
            "refId": "A",
            "region": "$region",
            "statistic": "Average"
        }
    ]
}
```

Here's the JSON of creating a new panel with the same selections as the above:

```
{
    "datasource":
    {
        "type": "cloudwatch",
        "uid": "${cw_ds}"
    },
    ...
    ...
    "targets":
    [
        {
            "datasource":
            {
                "type": "cloudwatch",
                "uid": "${cw_ds}"
            },
            "dimensions":
            {
                "BucketName": "$s3_bucket",
                "StorageType": "StandardStorage"
            },
            "expression": "",
            "id": "",
            "label": "",
            "matchExact": true,
            "metricEditorMode": 0,
            "metricName": "BucketSizeBytes",
            "metricQueryType": 0,
            "namespace": "AWS/S3",
            "period": "",
            "queryMode": "Metrics",
            "refId": "A",
            "region": "$region",
            "sqlExpression": "",
            "statistic": "Average"
        }
    ]
}
```

Notice the lack of the `datasource` key embedded within `targets`, and the inclusion of `"queryType": "randomWalk",` in the existing panel that broke post-upgrade.

**Comment by disfluxly** [comment] 2022-08-30 17:08
To help our users, I put together a very quick (and dirty, don't judge me) script that they can run against their dashboard json to fix this problem. I'll leave the script here in the event it helps anybody else:

```
# run as python update_json.py dashboard, where dashboard is the name of the .json file you're fixing, omitting the .json
import json
import sys

original_json_file_arg = sys.argv[1]

original_json_file = open(original_json_file_arg +".json")

json_data = json.load(original_json_file)

print("Fixing Dashboard")
for panel in json_data['panels']:
	if panel['datasource']['type'] == 'cloudwatch':
		panel_id = panel['id']
		print(f"Fixing Panel {panel_id}")
		datasource_type = panel['datasource']['type']
		datasource_uid = panel['datasource']['uid']

		targets = panel['targets']

		for target in targets:
			try:
				if 'expression' in target and target['expression'] != "":
					continue

				if 'datasource' not in target:
					target['datasource'] = {
						"type": datasource_type,
						"uid": datasource_uid
					}

				if 'queryType' in target and target['queryType'] == 'randomWalk':
					del target['queryType']

				if 'queryMode' not in target:
					target['queryMode'] = 'Metrics'

				if 'sqlExpression' not in target:
					target['sqlExpression'] = ""

				if 'label' not in target:
					target['label'] = ""

			except KeyError as e:
				print(e)
				print(target)
				sys.exit(1)

print("Finished fixing dashboard")

original_json_file.close()

fixed_json_file = original_json_file_arg + "-fixed.json"

with open(fixed_json_file, 'w') as output:
	json.dump(json_data, output)
```

**Comment by fridgepoet** [comment] 2022-08-31 08:47
@disfluxly Thanks for that, so thorough!

At least for the `queryType` `randomWalk` this seems to have been resolved in v9.0.6 by this fix https://github.com/grafana/grafana/pull/52759

**Comment by jangaraj** [comment] 2022-09-06 14:01
Is it a really bug? I can open template variables:
![image](https://user-images.githubusercontent.com/1182932/188654760-ab802407-5462-4299-8551-211526f9f23d.png)
->
![image](https://user-images.githubusercontent.com/1182932/188654903-121de287-72ca-42e0-842f-2786d09351a6.png)

**Comment by sarahzinger** [comment] 2022-10-11 15:45
Seems like there hasn't been any new information on this in the past few weeks so I'm going to close this, since we weren't able to reproduce. But let us know if we missed anything and we can reopen.

**Closed by sarahzinger** 2022-10-11 15:45 UTC
Labels: area/dashboard/templating, datasource/CloudWatch
