### ISSUE TITLE
Value mappings (more options)

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#35038] opened 2021-06-01 11:50 UTC
**What would you like to be added**:
Please add possibility use variables or values from others column in query.
Please adding posibility using 'like', I mean if value contains some text then display text, now is only equal values or number range.

![image](https://user-images.githubusercontent.com/73607094/120314733-d6a9a300-c2db-11eb-8ce9-1cb34959ef41.png)

**Why is this needed**:
This is very important options to many plugins where will be better possibility filter data and replace to text or value.

**Comment by torkelo** [comment] 2021-06-01 14:13
duplicate of https://github.com/grafana/grafana/issues/34878

**Closed by torkelo** 2021-06-01 14:13 UTC
Labels: area/value-mapping, type/feature-request
