### ISSUE TITLE
[Graph] Bar graph displays two values on one bar

### ISSUE THREAD

**Issue by SergeC** [grafana/grafana#26859] opened 2020-08-07 11:07 UTC
**What happened**:
On a bar chart with time interval 1 day I have two days displayed on one bar

**What you expected to happen**:
In my case, I need one day displayed per bar

**How to reproduce it (as minimally and precisely as possible)**:

![Kapture 2020-08-07 at 14 02 26](https://user-images.githubusercontent.com/1062847/89639922-25063500-d8b7-11ea-9b9a-63e19eeaa545.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.1.2
- Data source type & version: Postgres
- OS Grafana is installed on: MacOS 10.13.6
- User OS & Browser:MacOS 10.13.6 Chrome 84
- Grafana plugins: standard
- Others:

**Comment by torkelo** [comment] 2020-08-07 11:18
duplicate of https://github.com/grafana/grafana/issues/22611 

A temp workaround is to change tooltip to single

**Closed by torkelo** 2020-08-07 11:18 UTC
