### ISSUE TITLE
Detailed error returned to user

### ISSUE THREAD

**Issue by bgardner-noggin** [grafana/grafana#34689] opened 2021-05-25 23:58 UTC
**What happened**:
I am using the cloudwatch plugin. In Grafana 7.5.1 if I wrote a bad query / log insights query, I would get back detailed information in the top left by hovering over the red error.

In  7.5.6 I just get a generic "Metric request error" message and the detailed message has to be retrieved from the server side log

**What you expected to happen**:
Detailed error message should be returned to the user

**How to reproduce it (as minimally and precisely as possible)**:
Create a cloudwatch panel and write a bad logs insights query or metrics expression

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.6
- Data source type & version: cloudwatch
- OS Grafana is installed on: docker container (alpine)
- User OS & Browser: Fedora 33 Chrome
- Grafana plugins: Cloudwatch
- Others:

**Comment by zuchka** [comment] 2021-06-24 19:18
duplicate of https://github.com/grafana/grafana/issues/36097

issue made by same user but new issue has better documentation

**Closed by zuchka** 2021-06-24 19:18 UTC
Labels: datasource/CloudWatch Logs
