### ISSUE TITLE
Grafana 8.4.1 doesn't build on big endian architectures (s390x)

### ISSUE THREAD

**Issue by sergiodj** [grafana/grafana#46492] opened 2022-03-12 01:49 UTC
**What happened**:

I'm building a snap of grafana for multiple architectures (amd64, arm64, ppc64el and s390x), and grafana 8.4.1 doesn't build on s390x anymore:

```
+ make deps-js
install frontend dependencies
YARN_ENABLE_PROGRESS_BARS=false yarn install --immutable
Internal Error: Execution failed with a non-error rejection (rejected value: "Runtime error: expected the system to be little-endian!")
    at oo.error (/build/grafana/parts/grafana-ui/build/.yarn/releases/yarn-3.1.1.cjs:377:305)
    at r (/build/grafana/parts/grafana-ui/build/.yarn/releases/yarn-3.1.1.cjs:448:10660)
make: *** [Makefile:31: node_modules] Error 1
```

**What you expected to happen**:

Our previous release of grafana was for v8.1.1, which built fine on all architectures mentioned above.

**How to reproduce it (as minimally and precisely as possible)**:

Just try to build grafana on a big endian machine.  I understand that it may be hard to obtain one; I can try to help if needed.

**Anything else we need to know?**:

This may be related to https://github.com/emscripten-core/emscripten/issues/12387.

**Environment**:
- Grafana version: 8.4.1

**Comment by ivanahuckova** [comment] 2022-03-14 09:59
fyi @grafana/grafana-release-eng

**Comment by jackw** [comment] 2022-03-15 13:41
Looks like a duplicate of: #46269

**Closed** 2022-03-15 14:00 UTC
Labels: type/build-packaging, needs investigation
