### ISSUE TITLE
Text panel ignors iframe html tag

### ISSUE THREAD

**Issue by OddmarDam** [grafana/grafana#16740] opened 2019-04-24 09:28 UTC
**What happened**: Text panel in html mode wont render iframe tag anymore

**How to reproduce it (as minimally and precisely as possible)**: Add a text panel, set to html mode, create an iframe tag. Result is just plain text of the iframe tag

**Anything else we need to know?**: no

**Environment**: 
- Grafana version: 6.1.4
- OS Grafana is installed on: Linux, Centos 7
- User OS & Browser: Firefox

**Comment by marefr** [comment] 2019-04-24 11:23
Duplicate of #15883

**Comment by marefr** [comment] 2019-04-24 11:24
Please read [upgrade notes](https://grafana.com/docs/installation/upgrading/#upgrading-to-v6-0).

**Closed by marefr** 2019-04-24 11:24 UTC
