### ISSUE TITLE
Filter for value does not work for ES and types other than String

### ISSUE THREAD

**Issue by bla-bu** [grafana/grafana#17272] opened 2019-05-24 14:41 UTC
**What happened**:

I have Traefik logs in Elastic. I’ve created a simple dashboard with only a table to display the following columns: @timestamp, json.RequestMethod, json.RequestPath, json.OriginStatus, json.Duration, json.RequestHost. @timestamp is mapped to type "Date", other to type String. I have a Ad-hoc query variable called "Filters". Now, whenever I click zoom icon (Filter for value) on a value that has different type then String, the following error is thrown:
```
TypeError: e.replace is not a function
    at e.escapeDelimiter (plugin_edit_ctrl.ts:77)
    at plugin_edit_ctrl.ts:76
    at Array.map (<anonymous>)
    at plugin_edit_ctrl.ts:76
    at Array.map (<anonymous>)
    at e.getValueForUrl (plugin_edit_ctrl.ts:76)
    at actions.ts:28
    at qt (lodash.js:516)
    at Function.Ua (lodash.js:9343)
    at e.fillVariableValuesForUrl (template_srv.ts:320) "Possibly unhandled rejection: {}"
```

 
and Ad-hoc filtering stops working completely. As far as I can see, the problem is with type handling when "Filter for value" is clicked. For instance, when I click OriginStatus value 200, Query Inspector shows the following query:
`data:"{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"docker-loadbalancer-*"} {"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1558686669047","lte":"1558708269047","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}],"must":[{"match_phrase":{"json.OriginStatus":{"query":200}}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"docvalue_fields":["@timestamp"]}"`

The same done directly on a dashboard (using Ad-hoc query variable), end up with query:
`data:"{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"docker-loadbalancer-*"} {"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1558686787747","lte":"1558708387747","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}],"must":[{"match_phrase":{"json.OriginStatus":{"query":"200"}}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"docvalue_fields":["@timestamp"]}"`
that correctly filters the results.

**What you expected to happen**:
"Filter for value" should work for any type.

**How to reproduce it (as minimally and precisely as possible)**:
Create simple index in ES with several data types, try use "Filter for value".

**Anything else we need to know?**:
I believe this was mentioned here also: https://github.com/grafana/grafana/issues/16367#issuecomment-479774836

**Environment**:
- Grafana version: 6.1.3
- Data source type & version: Elasticsearch 6.4.2
- OS Grafana is installed on: docker
- User OS & Browser: Chrome, Win 10
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-05-24 15:13
duplicate of https://github.com/grafana/grafana/issues/12209

**Closed by torkelo** 2019-05-24 15:13 UTC
