### ISSUE TITLE
Dashboards with many graphs render at a significant delay

### ISSUE THREAD

**Issue by jsferrei** [grafana/grafana#13354] opened 2018-09-19 19:13 UTC
### What Grafana version are you using?
5.2.4
### What datasource are you using?
N/A
### What OS are you running grafana on?
OSX, Ubuntu
### What did you do?
Load a dashboard where the number of graphs is > the maximum number of connections your browser can serve (for Chrome, 6).
### What was the expected result?
Graphs should render shortly after their queries finish
### What happened instead?
Rendering is significantly delayed, depending on the number of graphs you have. After investigating, I found that the cause of this is that by the time the [requests](https://github.com/grafana/grafana/blob/master/public/app/features/annotations/annotations_srv.ts#L105) to get annotation data sources complete, all graphs have submitted their queries, and all connections are consumed. As a result, the [requests](https://github.com/grafana/grafana/blob/master/public/app/features/annotations/annotations_srv.ts#L108) to get annotation data are blocked until all graph requests to the TSDB resolve. Because graphs [wait](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/module.ts#L210) until annotation queries resolve to render, no graph will render until the last TSDB query resolves.

**Comment by marefr** [comment] 2018-09-20 09:21
Duplicate of #11806. Please refer to that issue in your PR instead.

**Closed** 2018-09-20 09:21 UTC
