### ISSUE TITLE
Unable to set up alerting from Prometheus server

### ISSUE THREAD

**Issue by Mahmo0odsalah** [grafana/grafana#45789] opened 2022-02-23 15:06 UTC
**What happened**:
Alerts don't show when there's an active alert, an error is shown: `Failed to load rules state from Prometheus: json: cannot unmarshal number into Go struct field Alert.data.groups.rules.alerts.value of type string`
**What you expected to happen**:
Alerts show normally in Grafana's UI.
**How to reproduce it (as minimally and precisely as possible)**:
Add a Prometheus data source and go to the alerting page.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: Prometheus: v2.15.2
- OS Grafana is installed on: Linux
- User OS & Browser: Linux & Google Chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment] 2022-02-24 16:53
@Mahmo0odsalah this looks like a duplicate of https://github.com/grafana/grafana/issues/40866

The resolution is to document which versions of prometheus are tested and expected to work - we support the last two minor versions. For example, 2.15.2 was released Jan 2020. The latest version is 2.33, so support is for 2.31+ - [Limitations](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/#limitations)

**Closed by mellieA** 2022-02-24 16:53 UTC
Labels: area/alerting/unified
