### ISSUE TITLE
Azure Metrics can't be fetched at Azure China

### ISSUE THREAD

**Issue by uebenes** [grafana/grafana#23183] opened 2020-03-30 06:28 UTC
**What happened**:
- an Azure Monitor Source has been added (**Azure China**) and the connection to this data source was successful
- an Graph has been added, all Ressource Groups and devices have been fould automatically - so far everything ok
- BUT: if I finished the query and try to fetch, I got following answer:

**{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}**

I am using the same tenent id and client id with the native azure python lib, it there it works fine.

**What you expected to happen**:
- I expected to see the graph, but got a error message

**How to reproduce it (as minimally and precisely as possible)**:
- try to configure an Azure monitor with Azure China - maybe its a problem only in the China API of Azure Monitor together with Grafana 

**Anything else we need to know?**:
- there is a already a topic in: https://community.grafana.com/t/latest-grafana-version-doesnt-work-with-azure-monitor-plugin/20739
- there is no know solution so far

**Environment**:
- Grafana version: 6.7.1
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Linux / Docker
- User OS & Browser: Window 10
- Grafana plugins: Azure Monitor
- Others:

**Comment by daniellee** [comment] 2020-03-30 08:22
Duplicate of #22191

**Closed** 2020-03-30 08:23 UTC
Labels: datasource/Azure Monitor, type/bug, type/duplicate
