### ISSUE TITLE
Can't change orgId of datasource by API

### ISSUE THREAD

**Issue by grifferz** [grafana/grafana#19278] opened 2019-09-22 18:30 UTC
**What happened**:

Tried to use the HTTP API to change the orgId of an existing datasource. The orgId was not changed, even though the update completed without error. As per #5991 it's not currently possible to create a datasource with the correct orgId either.

**What you expected to happen**:

Expected the orgId to change.

**How to reproduce it (as minimally and precisely as possible)**:

Given an existing datasource called "dstest" with id 2:
```
$ curl -X PUT -H 'Content-Type: application/json' -d '{"id":2,"orgId":5,"name":"dstest","type":"prometheus","access":"proxy"}' 'http://user:pass@localhost:3000/api/datasources/2'
{"datasource":{"id":2,"orgId":1,"name":"dstest","type":"prometheus","typeLogoUrl":"","access":"proxy","url":"http://localhost:9090","password":"","user":"","
database":"","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":false,"jsonData":{},"secureJsonFields":{},"version":1,"readOnly":false},"id":2,"message":"Datasource updated","name":"dstest"}

```
The response indicates an update, but the orgId was not updated from 1 to 5.

Messing with the database directly to change the org_id field does produce the desired result.

(As a side note, for a change you have to minimally supply **name**, **type** and **access**, just as for a create. I don't think you should have to if the datasource already exists. id and/or name and then whatever you want to change should be enough.)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.3.5
- Data source type & version: The included prometheus ds
- OS Grafana is installed on: Debian buster, from package
- Grafana plugins: None

**Comment by torkelo** [comment] 2019-09-23 19:17
This is not allowed by design, data sources are an org local thing and moving this between orgs is not a support use case

**Closed by torkelo** 2019-09-23 19:17 UTC
Labels: area/backend, area/backend/api

**Comment by grifferz** [comment] 2019-09-23 19:51
I see. So is the current correct way for the grafana admin to add a datasource to an org as per the comment in #5991:

> you should be able to provide the custom http header X-Grafana-Org-Id to select which organization to use for the api call.

?

Is any of this worth mentioning in the docs for the org section of the API? This design decision wasn't at all obvious to me.
