### ISSUE TITLE
Graph: MinMax window for Y-axis

### ISSUE THREAD

**Issue by whitebearded** [grafana/grafana#21994] opened 2020-02-07 09:15 UTC
Hi everyone!

**Situation**:
We have several graphs showing numbers of the same unit. We therefore usually set y-axis min and max values so that the MinMax-Difference everywhere is the same (e.g. 100k). The absolut numbers in the graph can be very different but this allows better comparison among different graphs.

Example:
![image](https://user-images.githubusercontent.com/6061915/74015618-454d4980-4991-11ea-94d1-61446818f4a9.png)

**Complication**:
If one graph now spikes or goes low, we need to manually adjust min + max values to maintain the 100k window on a higher or lower scale.

**What would you like to be added**:
In our opinion it would be a great addition if you would be able to define a window size (Max - Min), while the graph 
- will be automatically centered around the median value _or_ 
- based on the max value (it should always be in the viewport in our case).

**Relations**:
If found these to issues to be related but from my understanding they wouldn't fix our usecase:
- https://github.com/grafana/grafana/issues/4156
- https://github.com/grafana/grafana/issues/979

I'm looking forward to feedback. Let me know if there are questions! Many thanks!

**Comment by torkelo** [comment] 2020-02-07 14:01
dupe of https://github.com/grafana/grafana/issues/979

**Closed by torkelo** 2020-02-07 14:01 UTC
