### ISSUE TITLE
Clicking on panel title to bring up menu is not reliable

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#40650] opened 2021-10-19 17:17 UTC
**What happened**:

When I click on a panel's title to bring up the menu and select "Edit", 9 times out of 10 the panel just flashes blue and no menu appears. Compare this with grafana 6.5.* where it is a very reliable operation. Is the callback happening too quickly?

A better description might be that I click on the panel's title bar, the panel flashes grey and no menu appears. Might not be 9 times out of 10 but the menu fails with great regularity., maybe 4 out of 5 panel title clicks fail to bring up the menu.

**What you expected to happen**:

For the panel menu to behave like it does with grafana 6.5

**How to reproduce it (as minimally and precisely as possible)**:

Edit any panel served by grafana 8.2.1

**Anything else we need to know?**:

You tell me :)

**Environment**:
- Grafana version: 8.2.1
- User OS & Browser: MacOS X, Chrome 93.0.4577

**Comment by torkelo** [comment] 2021-10-20 07:21
duplicate of https://github.com/grafana/grafana/issues/31374

**Closed by torkelo** 2021-10-20 07:21 UTC
