### ISSUE TITLE
Datasource Plugins: improve error handling for bundled dashboards

### ISSUE THREAD

**Issue by avidhanju** [grafana/grafana#45556] opened 2022-02-17 17:51 UTC
**What happened**: Unhelpful error notification shows up when users try to import a dashboard from data source that has already been provisioned.

**What you expected to happen**: Ideally, dashboards that are provisioned should not be _importable_ from data source. The import button should be disabled for these dashboards with some visual indication to show that the dashboard has already been provisioned. At the very least, the error message that shows up should be a lot more useful about why the import failed.
![image](https://user-images.githubusercontent.com/10158691/154540523-4c55d60e-1272-4d60-910c-31d7c8790729.png)

**How to reproduce it (as minimally and precisely as possible)**: Provision dashboards that are already part of a data source.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.7.1
- Data source type & version: Any data source but we found this through Azure Monitor data source
- OS Grafana is installed on: Linux
- User OS & Browser: Windows + Chrome
- Grafana plugins: Azure Monitor, Prometheus
- Others:

**Comment by leandro-deveikis** [comment] 2022-03-17 16:04
Hi! I have been doing some research on this issue, and I found 2 things on why this is happening:

First, the dashboard at the json file that is provisioned has a `version` attribute, but that `version` is not being set when the dashboard is stored in the database for the first time. Instead, is being defaulted to 1. So when the json file has version=1, there is no problem and the correct message error is shown ("Provisioned dashboard cannot be deleted"). Instead, when the version is not 1, the error on this issue is shown, as the dashboard that is being saved has a different version than the one in the database. This is a validation done to avoid concurrent modifications on dashboards by different users. Not sure yet if this is by design or an actual bug.

The other issue I found is that even if you use the provisioned dashboards from the plugin or datasource folder, there is no actual link between those two on the database. There is a field that is set to know that link if you create the dashboard from the dashboard config UI, but when is being provisioned, is treated as any other dashboard. That is why we will not be able to change the button label to indicate that the dashboard is provisioned.

Given these two issues, the error message that is shown is wrong (as is pointed out in the issue description) but the behavior is the same, a provisioned dashboard can not be deleted from the UI. 

As for both issues, I'm investigating what would be the implications of doing some changes on that behavior, and checking if there is a simple solution that would show the correct error message without doing some major refactor or creating another bug.

**Comment by malcolmholmes** [comment] 2022-04-19 05:56
How does this compare to the same json pushed to the api?

**Comment by leandro-deveikis** [comment] 2022-04-19 14:10
Hi @malcolmholmes I did some more testing (using a local instance) and I think we are having the same issue here.
As a reference, I used postman to create a new dashboard using the same json as the "Azure Storage Insights" (copied from the json file in the plugin).  

![image](https://user-images.githubusercontent.com/34773040/164017294-a0801975-4ddb-4d12-98a0-06eae8876ba1.png)

As is shown, the version returned in the http response is 1 when the version on the json is 28.
However, thanks to this I could do some more digging and I found that we are setting the version to 1 intentionally at this line, as is taking it as a new dashboard

https://github.com/grafana/grafana/blob/69eb6efd6ef4ae46399faf83aafbe1145fc1301c/pkg/services/dashboards/database/database.go#L442

I'm almost sure that when provisioning from a file, the same code is being reused as the provisioning module is the same.

As I said before, there is no easy way to link a provisioned dashboard (either from a file or a API) with the ones listed at the datasource configuration.

**Comment by leandro-deveikis** [comment] 2022-05-23 14:37
I have been speaking with several teams, looking for a possible solution to this issue, but it seems that there is no. Every approach we think of requires a major refactor and does not seems to be worth it at the moment, especially since this is only a misplaced error message, but it behaves as expected in the end. I'm sorry about this, but we won't be fixing this issue at the moment.

**Comment by leandro-deveikis** [comment] 2022-05-23 14:37
I have been speaking with several teams, looking for a possible solution to this issue, but it seems that there is no. Every approach we think of requires a major refactor and does not seems to be worth it at the moment, especially since this is only a misplaced error message, but it behaves as expected in the end. I'm sorry about this, but we won't be fixing this issue at the moment.

**Closed by leandro-deveikis** 2022-05-23 14:37 UTC
Labels: area/dashboard, area/backend/plugins, needs investigation
