### ISSUE TITLE
User with admin rights on a dashboard cannot add a template variable if he doesn't have edit permissions in the folder.

### ISSUE THREAD

**Issue by cronosnull** [grafana/grafana#27269] opened 2020-08-28 15:51 UTC
**What happened**:
A user with admin rights on a dashboard tried to create a new template variable and he got a 403 error when saving the dashboard. The user is able to edit the dashboard adding or removing panels without problems. 
The dashboard is in a folder where the user has only viewer permissions. 

**What you expected to happen**:
The user can save the changes in the dashboard after adding the template variable. 
**How to reproduce it (as minimally and precisely as possible)**:
As admin:
1. Create a user with the viewer role. 
1. Create a folder with the default permissions.
1. Create a new dashboard in that folder.
1. Add the user as admin of the dashboard. 
As the user:
1. Log in with the user. 
1. Add a panel to the dashboard and save. (This works)
1. Create a new template variable (i.e. an interval variable), and save the dashboard. (this fails)

**Anything else we need to know?**:
We have tested with different browsers (Firefox, Safari, and Chrome)
The user can create variables if he has edit permissions in the folder. 
The error message in Grafana 7.1.3 is different from the one in 7.1.5, but the problem is the same in both versions. 
The message error in Grafana 7.1.3 is `You don't have permission to access /api/dashboards/db`, in Grafana 7.1.5 it is `Access denied to save dashboard`.

**Environment**:
- Grafana version: 7.1.3 and 7.1.5
- Data source type & version: ANY
- OS Grafana is installed on: Linux and Windows.
- User OS & Browser: Tested on Windows, Mac and Linux with Chrome, Firefox, and Safari(only mac).
- Grafana plugins: N/A.
- Others: After experimented the error on production I've installed the latest version and was able to reproduce the problem on it.

**Comment by torkelo** [comment] 2020-08-28 17:50
Strange the same api is used, no difference when saving a dashboard with new panel vs changing with a new variable

**Comment by torkelo** [comment] 2020-08-28 17:54
as I thought, was unable to replicate this.

**Comment by torkelo** [comment] 2020-08-28 17:56
Are you using some custom auth? OAuth, Auth proxy? Can you show the network request? Any info from grafana server log? 

As I said this does not make sense, there no code that cares what you changed in the dashboard, the api and security checks are the same when you save a dashboard with a new panel or new variable

**Comment by cronosnull** [comment] 2020-08-28 19:27
Hi @torkelo, 

In the production environment, we use the organization SSO, but I was able to replicate this in a clean install of grafana.
It is indeed a very strange problem, as the same API is used. 

Creating the test user:
![image](https://user-images.githubusercontent.com/4405564/91606155-de65a100-e971-11ea-962f-69abe900ea8f.png)
A folder with default permissions: 
![image](https://user-images.githubusercontent.com/4405564/91606248-06550480-e972-11ea-883b-b423cf47ef3b.png)

A new dashboard in that folder, giving admin permissions to the test user:

![image](https://user-images.githubusercontent.com/4405564/91606364-38fefd00-e972-11ea-84fc-7fee5fdc40b0.png)

Logging in as the test-user, as expected, I can edit the dashboard (adding, editing or removing panels) without problems:
![image](https://user-images.githubusercontent.com/4405564/91606699-d3f7d700-e972-11ea-8f7d-c5308fa94f2f.png)


Then, I add a template variable
![image](https://user-images.githubusercontent.com/4405564/91606784-06a1cf80-e973-11ea-9150-93b670d6043c.png)
And, when saving the dashboard I get:
![image](https://user-images.githubusercontent.com/4405564/91606971-6c8e5700-e973-11ea-8f5f-664e6e874c01.png)

The payload of the request is:

```
{"dashboard":{"annotations":{"list":[{"builtIn":1,"datasource":"-- Grafana --","enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations & Alerts","type":"dashboard"}]},"editable":true,"gnetId":null,"graphTooltip":0,"id":2,"links":[],"panels":[{"aliasColors":{},"bars":false,"dashLength":10,"dashes":false,"datasource":null,"fieldConfig":{"defaults":{"custom":{}},"overrides":[]},"fill":1,"fillGradient":0,"gridPos":{"h":8,"w":12,"x":0,"y":0},"hiddenSeries":false,"id":2,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":true,"total":false,"values":false},"lines":true,"linewidth":1,"nullPointMode":"null","percentage":false,"pluginVersion":"7.1.5","pointradius":2,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"thresholds":[],"timeFrom":null,"timeRegions":[],"timeShift":null,"title":"Panel Title","tooltip":{"shared":true,"sort":0,"value_type":"individual"},"transparent":true,"type":"graph","xaxis":{"buckets":null,"mode":"time","name":null,"show":true,"values":[]},"yaxes":[{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true},{"format":"short","label":null,"logBase":1,"max":null,"min":null,"show":true}],"yaxis":{"align":false,"alignLevel":null}}],"schemaVersion":26,"style":"dark","tags":[],"templating":{"list":[{"allValue":null,"current":{"selected":false,"text":"1","value":"1"},"hide":0,"includeAll":false,"label":null,"multi":false,"name":"testVar","options":[{"selected":true,"text":"1","value":"1"},{"selected":false,"text":"2","value":"2"},{"selected":false,"text":"3","value":"3"},{"selected":false,"text":"4","value":"4"}],"query":"1,2,3,4","skipUrlSync":false,"type":"custom"}]},"time":{"from":"now-6h","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"]},"timezone":"","title":"test_with_user","uid":"9WMn1jNMk","version":7},"overwrite":false,"message":""}
```
Request Headers:
```
accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: es-CO,es-419;q=0.9,es;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 1951
content-type: application/json
Cookie: grafana_session=750bbb38eb84d26a1f837216f1264f6b
Host: localhost:3000
Origin: http://localhost:3000
Referer: http://localhost:3000/d/9WMn1jNMk/test_with_user?orgId=1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
x-grafana-org-id: 1
```
I just compared the payload with the successful request (when no variable is added) and in the failed one there is no folderId.

**Comment by torkelo** [comment] 2020-08-31 11:03
ah, I did only set permissions on the folder level. I recommend only setting permissions on the folder instead of individual dashboards 

This is a duplicate of this bug, https://github.com/grafana/grafana/issues/25771

**Closed by torkelo** 2020-08-31 11:03 UTC
Labels: needs more detail
