### ISSUE TITLE
Explore Logs: Download to data CSV 

### ISSUE THREAD

**Issue by soum1234** [grafana/grafana#15887] opened 2019-03-08 08:50 UTC
can u add a download button to download the data fetched from the search string.
Also an option to increase the no of records matching the search string..currrently only 1000 records are available,
An option to get the count of the no of records that matched the given string would be very useful

thanks

**Comment by Elfo404** [comment] 2021-02-10 09:22
Closing this as duplicate of https://github.com/grafana/grafana/issues/28752

**Closed by Elfo404** 2021-02-10 09:22 UTC
Labels: area/explore, area/panel/logs, type/feature-request
