### ISSUE TITLE
Share variables between dashboards using same datasource

### ISSUE THREAD

**Issue by cedrico2016** [grafana/grafana#13877] opened 2018-10-29 13:07 UTC
### What Grafana version are you using?
Grafana v5.2.1 (2040f61)
### What datasource are you using?
IbnfluxDB
### What OS are you running Grafana on?
Ubuntu
### What did you do?
While creating dashboards i would like to know if there is a possibility in Grafana that should allow to use variables across dashboards using the same datasource. 

Such a feature may allow more flexibility while working with different dashboards using the same datasource for example, as a variable is also linked to the datasource.

**Comment by torkelo** [comment] 2018-10-29 13:19
duplicate of https://github.com/grafana/grafana/issues/1959

**Closed by torkelo** 2018-10-29 13:19 UTC
