### ISSUE TITLE
Prometheus Native Histogram are not display in Heatmap panel

### ISSUE THREAD

**Issue by laupse** [grafana/grafana#58577] opened 2022-11-10 13:17 UTC
**What happened**: 
No heatmap is shown in the panel when queying new native histograms from prometheus, the query inspector show empty result 

**What you expected to happen**:
Heatmap from the native histogram show

**How to reproduce it (as minimally and precisely as possible)**:
Use this repo https://github.com/laupse/prometheus-native-histograms
and then `docker compose up`

**Anything else we need to know?**: 

| Key | Value |
|--|--|
| Panel | heatmap @ 9.2.4 |
| Grafana | 9.2.4 (64017e8ca6) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "type": "heatmap",
      "title": "Reproduced with embedded data",
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "pluginVersion": "9.2.4",
      "interval": "30s",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "scaleDistribution": {
              "type": "linear"
            },
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            }
          }
        },
        "overrides": []
      },
      "options": {
        "calculate": false,
        "yAxis": {
          "axisPlacement": "left",
          "reverse": false
        },
        "rowsFrame": {
          "layout": "auto"
        },
        "color": {
          "mode": "scheme",
          "fill": "dark-orange",
          "scale": "exponential",
          "exponent": 0.5,
          "scheme": "Oranges",
          "steps": 64,
          "reverse": false
        },
        "cellGap": 1,
        "filterValues": {
          "le": 1e-9
        },
        "tooltip": {
          "show": true,
          "yHistogram": false
        },
        "legend": {
          "show": true
        },
        "exemplars": {
          "color": "rgba(255,0,255,0.7)"
        }
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "heatmap-rows",
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: rpc_durations_native_histogram_seconds\nStep: 30s"
                },
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 30000
                    }
                  },
                  {
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "__name__": "rpc_durations_native_histogram_seconds",
                      "instance": "nativehisto:8080",
                      "job": "prometheus"
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [],
                  []
                ]
              }
            }
          ]
        }
      ]
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >heatmap @ 9.2.4</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[prometheus]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 2 fields, 0 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.2.4 (64017e8ca6) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 5,\n  \"gridPos\": {\n    \"h\": 12,\n    \"w\": 14,\n    \"x\": 0,\n    \"y\": 12\n  },\n  \"type\": \"heatmap\",\n  \"title\": \"Heatmap Old histograms\",\n  \"datasource\": {\n    \"uid\": \"prometheus\",\n    \"type\": \"prometheus\"\n  },\n  \"pluginVersion\": \"9.2.4\",\n  \"interval\": \"30s\",\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        }\n      }\n    },\n    \"overrides\": []\n  },\n  \"options\": {\n    \"calculate\": false,\n    \"yAxis\": {\n      \"axisPlacement\": \"left\",\n      \"reverse\": false\n    },\n    \"rowsFrame\": {\n      \"layout\": \"auto\"\n    },\n    \"color\": {\n      \"mode\": \"scheme\",\n      \"fill\": \"dark-orange\",\n      \"scale\": \"exponential\",\n      \"exponent\": 0.5,\n      \"scheme\": \"Oranges\",\n      \"steps\": 64,\n      \"reverse\": false\n    },\n    \"cellGap\": 1,\n    \"filterValues\": {\n      \"le\": 1e-9\n    },\n    \"tooltip\": {\n      \"show\": true,\n      \"yHistogram\": false\n    },\n    \"legend\": {\n      \"show\": true\n    },\n    \"exemplars\": {\n      \"color\": \"rgba(255,0,255,0.7)\"\n    }\n  },\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"prometheus\"\n      },\n      \"editorMode\": \"code\",\n      \"exemplar\": false,\n      \"expr\": \"rpc_durations_native_histogram_seconds\",\n      \"format\": \"heatmap\",\n      \"instant\": false,\n      \"interval\": \"\",\n      \"legendFormat\": \"__auto\",\n      \"range\": true,\n      \"refId\": \"A\"\n    }\n  ]\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Heatmap Old histograms // 2022-11-10 13:50:05",
  "tags": [
    "debug",
    "debug-heatmap"
  ],
  "time": {
    "from": "2022-11-10T12:35:05.288Z",
    "to": "2022-11-10T12:50:05.289Z"
  }
}
```
</details>

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: prometheus 2.40
- OS Grafana is installed on: Docker image on wsl 
- User OS & Browser:Windows Chrome
- Grafana plugins: 
- Others:

**Comment by zuchka** [comment] 2022-11-15 20:42
Thanks for creating this issue, @laupse and thanks doubly for the excellent docker compose setup.

I don't know if this is a bug or feature request but I can confirm that using your setup, the following query works inside the prometheus UI but returns nothing inside the Grafana UI: `rate(rpc_durations_native_histogram_seconds[30s])`

note: creds for grafana are `admin:password`

**Comment by ahurtaud** [comment] 2022-11-24 15:23
I managed to make it work.
The key was that it requires the new heatmap panel which is available only on the grafana main branch and not on any release.
the docker image grafana/grafana:main docker tag fixed it for me ;)

**Comment by laupse** [comment] 2022-11-25 08:58
Works like a charm indeed, Thanks ! 
Since when it is available on the main branch ? i think i did tried it 3 weeks ago and it was not available 

And i guess it will be availbable on 9.4 ? 
![image](https://user-images.githubusercontent.com/98523125/203940959-d6a0f3c8-739b-4de9-852d-0aca0219661d.png)

**Comment by zuchka** [comment] 2022-11-27 02:28
might be this PR:

https://github.com/grafana/grafana/pull/59249

**Comment by zuchka** [comment] 2022-11-27 02:33
closing for now since y'all seem unblocked by this

**Closed by zuchka** 2022-11-27 02:33 UTC
Labels: type/bug, datasource/Prometheus
