### ISSUE TITLE
Alerting: UA Upgrade failure for instances who previously upgraded prior to 8.2, rolled back, and then upgrade again after 9.4

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#65839] opened 2023-04-03 14:05 UTC
**What happened**:

Upgrading to UA prior to 8.2, rolling back, and then upgrading again after 9.4 causes the second upgrade to fail.

This is because the 8.2 migration leaves invalid records in the alert_configuration table. There is some special code in the migration to handle this that is rarely called and not tested, but it's currently broken due to that table changing schema. This needs to be fixed.

https://github.com/grafana/grafana/blob/008bf143accf2eb2e3e529c66168e70dc0fd6d6e/pkg/services/sqlstore/migrations/ualert/ualert.go#L643

Easy workaround is to simply clear the `alert_configuration` table and then upgrade again. I'm a bit surprised the migration does not do this already?

**What you expected to happen**:

Upgrade to pass.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade to UA in some version to 8.2, roll back, and then upgrade again after 9.4.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by yuri-tceretian** [comment] 2023-05-04 19:46
Dupe of https://github.com/grafana/grafana/issues/64191 but I will keep this open as that one was closed.

**Closed** 2023-05-05 16:03 UTC
Labels: type/bug, area/alerting, area/backend
