### ISSUE TITLE
Underlying controls overlap with popup

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#26690] opened 2020-07-30 06:27 UTC
**What happened**:
![sample](https://user-images.githubusercontent.com/1107939/88887676-268f8780-d23d-11ea-88ed-a08e78c93be6.gif)
![sample2](https://user-images.githubusercontent.com/1107939/88888238-3eb3d680-d23e-11ea-9ad9-053748e10336.gif)

**What you expected to happen**:
The popup has to be the very-top control 

**Anything else we need to know?**:
This bug is incredibly annoying as i'm editing various dashboards and this scenario is happening **really often**. I'm using hotkeys for now. This is only a workaround and not working for everything as you may noticed that _"Copy"_ does not have a hotkey.

**Environment**:
- Grafana version: v7.1.0 (8101355285)
- Browser: Chrome Version 84.0.4147.105

**Comment by torkelo** [comment] 2020-07-30 09:55
Duplicate of #25930 

Z-index stacking makes this tricky to solve

**Closed by torkelo** 2020-07-30 09:55 UTC
