### ISSUE TITLE
PageToolbar: Parent text not showing

### ISSUE THREAD

**Issue by Mendes11** [grafana/grafana#39097] opened 2021-09-10 15:04 UTC
**What happened**:
Parent text from PageToolbar is not showing.

Even at the UI examples page you can see it: 
https://developers.grafana.com/ui/latest/index.html?path=/docs/layout-pagetoolbar--examples

![grafana_bug_toolbar_1](https://user-images.githubusercontent.com/7904704/132874944-f17d5fdd-b5e2-4e3f-9807-69e5a7b9ba2e.png)
![grafana_bug_page_toolbar](https://user-images.githubusercontent.com/7904704/132874970-41789a55-dfe3-490d-93cc-5dcabd707af6.png)

**What you expected to happen**:
To show the parent text

**How to reproduce it (as minimally and precisely as possible)**:
Update to the latest version

**Comment by ashharrison90** [comment] 2021-09-16 14:38
hey @Mendes11 👋 

looking at the code, i think this is intended: https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/PageLayout/PageToolbar.tsx#L67

you can see the parent text is only displayed if you also provide a `parentHref`, because it's a clickable link that should take you to the parent. as such i'm going to close this as working as intended.

hope that makes sense, and thanks for raising this! 🙌

**Closed by ashharrison90** 2021-09-16 14:38 UTC
Labels: type/bug, area/frontend, area/grafana/ui
