### ISSUE TITLE
Graph disappears when switching tabs on chrome

### ISSUE THREAD

**Issue by alokpr** [grafana/grafana#11152] opened 2018-03-07 21:18 UTC
- What Grafana version are you using? 4.6.3 (commit: 7a06a47)
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? CentOS
- What did you do? Load dashboard; switch tabs; go back to grafana tab
- What was the expected result? graph should stay visible
- What happened instead? graph disappears

The graph only reappears after refreshing or resizing the window. After some troubleshooting, I disabled "accelerated 2D canvas" in chrome://flags, which fixed the issue but made the interaction really slow. This issue can be seen on Chrome running on Ubuntu 14.04 with Nvidia GPU:

Relevant client information:
Chrome/64.0.3282.167
Linux 4.4.0-116-generic
GL_VENDOR | NVIDIA Corporation
GL_RENDERER | GeForce GTX 1060 6GB/PCIe/SSE2
GL_VERSION | 4.6.0 NVIDIA 390.25

Works fine on Firefox on the same machine.

**Comment by max3163** [comment] 2018-03-09 20:20
Same problem for me

**Comment by marefr** [comment] 2018-03-12 08:23
Can't reproduce this. I would suggest you to try the latest version. Closing this for now. Will consider opening it if more people report it and/or if you have the same problem in the latest version.

**Closed by marefr** 2018-03-12 08:23 UTC

**Comment by derkgort** [comment] 2018-03-30 11:48
Same problem here.

**Comment by edubart** [comment] 2018-04-08 14:27
Same here, Grafana 5.0.4, Chrome 65, Arch Linux, Nvidia 390.48, Awesome WM.

Tuning off hardware acceleration in chrome settings the issue disappears.

**Comment by anibali** [comment] 2018-05-15 05:29
I'm having the same problem. Grafana v5.0.4 (commit: 7dc36ae), Ubuntu 16.04, Chrome 61.0.3163.91, Nvidia drivers 390.30. Firefox seems to work just fine.

**Comment by derkgort** [comment] 2018-05-15 08:35
My solution did not work.
What I did and what worked was disable GPU acceleration in chrome...
