### ISSUE TITLE
Bar width is infinite if one point 

### ISSUE THREAD

**Issue by Ivan-Vinogradov** [grafana/grafana#12125] opened 2018-06-01 06:50 UTC
### What Grafana version are you using?
4.6.1
### What datasource are you using?
PostgreSQL
### What OS are you running grafana on?
Windows Server 2012 R2
### What did you do?
Create graph time series. Add next query:
```
SELECT
  $__timeGroup(CreatedDateTime,'10m') as time,
  Count("Id") as "Some Bar"
FROM
  "SomeTable"
WHERE
  $__timeFilter("CreatedDateTime")
GROUP BY "time"
ORDER BY "time"
```

Generated query:
```
SELECT
  (extract(epoch from "CreatedDateTime")/extract(epoch from '10m'::interval))::int*extract(epoch from '10m'::interval) as time,
  Count("Id") as "Some Bar"
FROM
  "SomeTable"
WHERE
  extract(epoch from "CreatedDateTime") BETWEEN 1527230455 AND 1527835255
GROUP BY "time"
ORDER BY "time"
```

### What was the expected result?
The width of the bar is limited by the special interval
![image](https://user-images.githubusercontent.com/30046957/40825713-27124808-6581-11e8-98e4-91d3f19cbc97.png)

### What happened instead?
If the query returned one result - **bar width is infinite** and not limited to a specified interval
If the query returns more than one result -  the width each bar is limited to the specified interval

![image](https://user-images.githubusercontent.com/30046957/40825130-5c3e5dac-657f-11e8-8b3a-d4041a9b4edb.png)

**Comment by marefr** [comment] 2018-06-01 08:30
Duplicate of #11964. Please refer to [comment](https://github.com/grafana/grafana/issues/11964#issuecomment-389857929) in that issue.

**Closed by marefr** 2018-06-01 08:30 UTC
