### ISSUE TITLE
[Feat Req] Free-form text field in templates

### ISSUE THREAD

**Issue by johnhtodd** [grafana/grafana#9591] opened 2017-10-19 05:56 UTC
We have datasets with many tag values and reasonably high cardinality (TSDB doesn’t matter - it’s the same problem in InfluxDB as Prometheus, for instance.) It is not reasonable to display picklists of all the possible tag values, as they scroll off the screen and that method is somewhat cumbersome with more than a dozen or so options.

**It would be extremely useful to be able to enter free-form text into a template field which could then be substituted in a Metric query.**

This does not sound as complex as most of the other template value options, so I am hoping it would be an easy addition. In an ideal world, the string would be the same format as that which is found in the metric query - that is to say, expansion would be done with comma-separated multi-values, or wildcards. However, even an exact non-interpreted version would work for 90% of our cases where we’re just putting in a specific number, three digit POP string, or IP address in CIDR notation (for example.) It would save lots of time by avoiding “Edit” one-time lookup aborts just to get the data for a single tag value.

We’d be happy to put a few hundred dollars towards this if the payment method was fairly frictionless (PayPal or credit card.) I don’t think we could sponsor the whole feature as a formal contracted development workset, but certainly a significant part could be sponsored if others were also interested or there was some other matching money towards the feature.

**Comment by bergquist** [comment] 2017-10-19 07:39
This has come up in discussions a few times. Dupe of https://github.com/grafana/grafana/issues/3173

**Closed by bergquist** 2017-10-19 07:39 UTC

**Comment by johnhtodd** [comment] 2017-10-19 14:39
Thanks for pointing this to the right ticket. That is indeed the appropriate pre-existing FR description (or close enough.)
