### ISSUE TITLE
UI: Table Transform: dropdown menu cannot scroll up 

### ISSUE THREAD

**Issue by baur** [grafana/grafana#24234] opened 2020-05-04 13:47 UTC
**What happened**:

cannot scroll up

![image](https://user-images.githubusercontent.com/2898361/80972205-a923c900-8e3f-11ea-853a-6907832e86b8.png)

**What you expected to happen**:

scrollup

**Environment**:
- Grafana version: 7.0 beta
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome

**Comment by torkelo** [comment] 2020-05-04 13:57
duplicate of https://github.com/grafana/grafana/issues/24107

**Closed by torkelo** 2020-05-04 13:57 UTC
