### ISSUE TITLE
Add AWS Access Key authentication, that exists on cloudwatch datasource, to elasticsearch datasource

### ISSUE THREAD

**Issue by bpair** [grafana/grafana#11241] opened 2018-03-14 12:32 UTC
I know there have been other requests to add IAM authentication to the elasticsearch datsource and the response has been to use aws-es-proxy instead. This is fine if running Grafana locally but I think a more flexible solution would be to add the AWS Access key authentication to the datasource.

The AWS Access Key authentication is already part of the Cloudwatch datasource and it is the easiest authentication to implement for API Gateway. This would make it possible to use your hosted grafana service hitting an API Gateway proxy that hits elasticsearch via lambda. No servers to maintain.

This architecture works today if no authentication is used but that is a dangerous scenario. This would restrict access. Also in the lambda function it is possible to restrict calls to only GET and POST(with _msearch) to further protect the elasticsearch data. 

Also Amazon just launched their serverless application template repository so I could see a template for creating the API Gateway and Lambda portion which makes this setup easy. https://aws.amazon.com/serverless/serverlessrepo

I am not sure how much work is involved in adding that feature to the elasticsearch datasource but I think a lot of people would benefit, especially those using hosted grafana.

Thanks for all your work, Grafana is amazing and so much better than kibana.

**Comment by bergquist** [comment] 2018-04-11 11:45
dupe of https://github.com/grafana/grafana/issues/10971

**Closed by bergquist** 2018-04-11 11:45 UTC
