### ISSUE TITLE
Threshold from query, *or* "line fill above"

### ISSUE THREAD

**Issue by nikclayton-dfinity** [grafana/grafana#25963] opened 2020-07-01 07:57 UTC
**What would you like to be added**:

I would like either (a) the value for a chart threshold to be specifiable from a query, or (b) the ability to specify that a line fill should go from the line to the top of the chart (currently it only goes to the bottom).

**Why is this needed**:

I have a value that represents a limit for a metric.

For example, a latency threshold of 500ms.

This is stored as a recorded rule in Prometheus, so it's easily under source control, I have a historical record of the limit if it changes, it's easy to use in alerting rules, etc.

I can also display this metric on a Grafana chart, where it generally appears as a flat line (unless I change the limit of course).

I would like to shade the area above the line to clearly indicate that if the other metrics go above the metric there is a problem.

I can create a threshold in the chart, but I must enter a static value rather than a metric. So if I change the threshold in Prometheus I have to remember to change it in Grafana (and if I go and look at historical charts it will display the current threshold value, not the value it was at the time).

So I'd like to be able to either:

1. Enter the threshold value using a query (it would be OK if instead of entering a new query I could select an existing query from the chart), or

2. Be able to fill *above* a line so that that the area above the metric is shaded appropriately.

**Comment by torkelo** [comment] 2020-07-02 07:43
duplicate of https://github.com/grafana/grafana/issues/159

**Closed by torkelo** 2020-07-02 07:43 UTC
Labels: area/frontend, priority/awaiting-more-evidence, type/feature-request
