### ISSUE TITLE
grafana-toolkit: Prettier erases file content

### ISSUE THREAD

**Issue by TheRoSS** [grafana/grafana#19100] opened 2019-09-13 15:36 UTC
**What happened**:
I have the following MonthPickerPanel.tsx file with an import error (line 3):
```typescript
import React, { PureComponent } from 'react';
import { PanelProps, PanelPlugin } from '@grafana/ui';
import { getTimeSrv, TimeSrv } from 'grafana/app/features/dashboard/services/TimeSrv';

export class MonthPickerPanel extends PureComponent<PanelProps> {
  timeSrv: TimeSrv = getTimeSrv();

  constructor(props: PanelProps) {
    super(props);
  }

  render() {
    return (
      <div className="monthpicker">
      </div>
    );
  }
}

export const plugin = new PanelPlugin(MonthPickerPanel);
``` 

When I ran `yarn build`, got following output 
```
> yarn build
yarn run v1.17.3
$ grafana-toolkit plugin:build
Running Build plugin task
✔ Cleaning
✔ Preparing
⠙ Prettier check  
  Fix Prettier issues in following files:
  /home/alex/workspace/gamebeat/grafana-monthpicker/src/MonthPickerPanel.tsx
  
  Run toolkit:dev to fix errors
✖ Prettier failed
error Command failed with exit code 1.
```
When I ran `yarn dev`, Prettier succeeded but MonthPickerPanel.tsx had size of 0

my package.json (only essential fields):
```
  ...
  "main": "dist/module.js",
  "scripts": {
    "build": "grafana-toolkit plugin:build",
    "test": "grafana-toolkit plugin:test",
    "dev": "grafana-toolkit plugin:dev",
    "watch": "grafana-toolkit plugin:dev --watch"
  },
  "devDependencies": {
    "@grafana/data": "latest",
    "@grafana/toolkit": "next",
    "@grafana/ui": "latest",
    "@types/grafana": "https://git@github.com/CorpGlory/types-grafana.git",
    "react": "16.8.6",
    "react-calendar": "^2.18.1",
    "react-dom": "16.8.6"
  }
  ...
```

**What you expected to happen**:
Just an error upon compilation stage

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new panel plugin with data from my package.json
2. Create `src/module.ts` with code: 
```typescript
import { PanelPlugin } from '@grafana/ui';
import { MonthPickerPanel } from './MonthPickerPanel';
export const plugin = new PanelPlugin(MonthPickerPanel)
```
3. Create `src/MonthPickerPanel.tsx` with code from my report (see above)
4. yarn install
5. yarn dev
6. Check the content of `src/MonthPickerPanel.tsx`. It will be empty

**Anything else we need to know?**:
It would be great if `yarn build` prettier displayed what didn't like and where he had found his errors

**Environment**:
- Grafana version:
```
├─ @grafana/data@6.3.2
├─ @grafana/toolkit@6.4.0-alpha.44-7ca77b8a9
├─ @grafana/ui@6.3.2
├─ @types/grafana@4.6.3
```
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment] 2019-09-24 07:12
@TheRoSS Thanks for reporting that and sorry for late response. I've tried to reproduce the issue with latest version of grafana-toolkit, but with no success. Can you please update your grafana-toolkit to `next`(https://www.npmjs.com/package/@grafana/toolkit/v/6.4.0-beta.1) version and try again?

**Comment by torkelo** [comment] 2019-10-14 12:44
closing due to lack of updates

**Closed by torkelo** 2019-10-14 12:44 UTC
Labels: area/grafana/toolkit, needs more detail, type/bug
