### ISSUE TITLE
only 1 backend plugin instance should issue alert queries in cluster env

### ISSUE THREAD

**Issue by knoguchi** [grafana/grafana#26608] opened 2020-07-26 20:52 UTC
I posted the same question to the Community. So far I haven't heard any.  I'd like to hear from the Grafana developers.
https://community.grafana.com/t/how-to-run-only-1-backend-plugin-in-a-cluster-environment/33826

- I have a cluster of Grafana servers behind the load balancer for the performance and the high availability.
- The Grafana instances share the same Postgres database. 
- One of the data sources is enabled for alerts (backend plugin).

**What happened**:
All of the backend plugin instances issued queries for the same alert.   I monitored the logs of each instance, and observed the same alert ID at the same timing.

**What you expected to happen**:
Only 1 backend plugin instance should issue the query.   I wonder if this problem is common for all the datasources with backend plugins or specific to my datasource plugin.  If the problem is common, I think it can be easily fixed by putting mutex in the database.

**Environment**:
- Grafana version: 7.0.6
- Data source type & version:  proprietary datasource with proprietary backend plugin.

**Comment by torkelo** [comment] 2020-07-27 06:38
Alerting rules will be executed from all your grafana servers

You can disable alert rule execution on one server with this setting: https://grafana.com/docs/grafana/latest/administration/configuration/#execute_alerts 

dupe of https://github.com/grafana/grafana/issues/6957

**Closed by torkelo** 2020-07-27 06:38 UTC
