### ISSUE TITLE
Loki: Show context in Explore doesn't work

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#17862] opened 2019-07-02 09:41 UTC
**What happened**:
Selected `Show context` for a Loki log message and error message is displayed: "Error during context query. Please check JS console log".

**What you expected to happen**:
Surrounding/contextual log messages are loaded and displayed.

**How to reproduce it (as minimally and precisely as possible)**:
Using Loki in Explore and filtering a stream `{job="grafana"} eror`, then select `Show context`.

**Anything else we need to know?**:
Seems to be related to wrong date/time format being sent in parameter to loki, but not sure.

![image](https://user-images.githubusercontent.com/1668778/60502455-292c5000-9cbe-11e9-849a-7b6acf1e2275.png)

![image](https://user-images.githubusercontent.com/1668778/60502461-2b8eaa00-9cbe-11e9-9672-840d3788fb2e.png)

**Environment**:
- Grafana version: master (364f1f2)
- Data source type & version: Loki
- User OS & Browser: Chrome

**Comment by kaydelaney** [comment] 2019-07-02 12:45
@marefr I think the problem is most likely that the query you've entered is invalid - should be `{job="grafana"} |="eror"` instead of `{job="grafana"} eror`.
Should be fixed by https://github.com/grafana/grafana/pull/17852

**Comment by marefr** [comment] 2019-07-02 12:54
No, `{job="grafana"} eror` is a valid query. That format was supported at first and then the Loki query language added support for formats like `{job="grafana"} |="eror"`

**Comment by kaydelaney** [comment] 2019-07-02 12:56
Oh! That's interesting, didn't know that. Still not able to reproduce, but I'll do a bit more digging.

**Comment by marefr** [comment] 2019-07-02 12:57
You're using latest master? Maybe one of the recently merged PR's fixed this?

**Comment by marefr** [comment] 2019-07-02 12:59
Still able to reproduce it on 364f1f2

**Comment by kaydelaney** [comment] 2019-07-02 13:20
What version of Loki are you using?

**Comment by marefr** [comment] 2019-07-02 13:30
Quite old:
grafana/loki          master               cd2db53d0097        6 weeks ago         34.9MB

Going to try with latest.

**Comment by marefr** [comment] 2019-07-02 14:23
It works with latest loki master. However, I still find it weird that there are different format in use for `start` and `end` parameters.

**Comment by kaydelaney** [comment] 2019-07-02 14:24
Agreed. I'll write a fix

**Comment by dprokop** [comment] 2019-07-03 07:57
@marefr please see https://github.com/grafana/loki/issues/597 for motivation around different formats for start/end. Problem is we don't support ns precision math, hence the formats are different to be able to fetch correct rows.

**Comment by kaydelaney** [comment] 2019-07-03 12:53
Working as intended, so closing.

**Closed by kaydelaney** 2019-07-03 12:53 UTC
Labels: area/explore, priority/important-soon, type/bug
