### ISSUE TITLE
Variables: Grafana still shows old value in panel after update of a variable (type: constant).

### ISSUE THREAD

**Issue by meberli** [grafana/grafana#27158] opened 2020-08-24 09:08 UTC
**What happened**:
Grafana still shows old variable value in panel after update of a variable (type: constant).

**What you expected to happen**:
- value should be the newly assigned one, not the previous one

**How to reproduce it (as minimally and precisely as possible)**:
- create new dasboard
- add a variable with name 'test' of type constant with value 'hello'
- add a panel with title ${test} 
- save dashboard
- save a dashboard with 'Save As..' under a different name.
- update variable test with new value 'bye'
- save dashboard
--- now the panels title is 'bye'
- reload dashboard
--- now the panels title is hello again

**Environment**:
- Grafana version: v7.0.6 (9f4a172a76
- Data source type & version: none
- OS Grafana is installed on: Linux
- User OS & Browser: Windows/Chrome
- Grafana plugins: none
- Others:

**Comment by sakjur** [comment] 2020-08-24 09:36
Are you checking the `Save current variable values as dashboard default` checkbox when saving the dashboard?

**Comment by meberli** [comment] 2020-08-24 10:08
I only have a 'copy tags' checkbox which I do not activate.

**Comment by meberli** [comment] 2020-08-24 10:15
I just realized the same situation exists always when updating a variable of type constant, You don't even have to copy the dashboard.
A workaround is to first delete the variable, then save the dashboard and re-create the variable with the new value

**Comment by Eraac** [comment] 2020-08-24 12:12
I've open an issue like this https://github.com/grafana/grafana/issues/21870, I think the issue is more UX than a real bug

**Comment by meberli** [comment] 2020-08-28 12:03
No it's not UX. Variable has wrong value after update. It's simple to reproduce:
- create new dasboard
- add a variable with name 'test' of type constant with value 'hello'
- add a panel with title ${test}
- save dashboard
- update variable test with new value 'bye'
- save dashboard and display it
--- now the panels title is 'bye'
- reload browser
--- now the panels title is hello again

**Comment by hugohaggmark** [comment] 2020-10-20 08:17
Hi @meberli as both @sakjur and @Eraac mentioned this is not an issue but bad UX. You're forgetting to check `Save current variable values as dashboard default` checkbox when you save your dashboard.

![image](https://user-images.githubusercontent.com/562238/96559227-09f37080-12bd-11eb-9d9c-a6db0e1ced42.png)

I also followed your repro steps in this movie but I check the `Save current variable values as dashboard default` checkbox and there is no issue.
![bad-save-variables-ux](https://user-images.githubusercontent.com/562238/96559313-298a9900-12bd-11eb-880e-202bbea9a44d.gif)


I'm going to close this issue for now, but we can always reopen it if there is more proof that this is an issue.

All the best

**Closed by hugohaggmark** 2020-10-20 08:17 UTC
Labels: area/dashboard/templating, type/bug

**Comment by ameflorenti** [comment] 2023-09-29 10:58
Hi, I just landed here because I was having that issue, I get that you need to save the values as default. And that fixes the issue. But lets say you forget to save the values as default, grafana then somehow saves those values on the variable (in Settings)  but not on the dashboard, the only way to see that you are getting old values is with the query inspector. Even after dashboard reload. So... I would expect that if you do not save the values, the values are not saved in Variable settings anyway.
