### ISSUE TITLE
Use template variables in Y axis labels

### ISSUE THREAD

**Issue by trenb** [grafana/grafana#9708] opened 2017-10-28 16:35 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- What Grafana version are you using? 4.5.2
- What datasource are you using? Not relevant
- What OS are you running grafana on? CentOS 7
- What did you do? Attempt to use a template variable in the Y axis
- What was the expected result? The value of the template variable would be used in the Y axis label
- What happened instead? Literal printing of the variable name
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
I've looked for this, but wasn't able to see any requests for using Template Variables in Y-Axis labels. I have some dashboards where you can toggle between IOPS view and MB/s. I would like the Y-Axis label to use the value of the template variable.

Thanks!

**Comment by torkelo** [comment] 2017-10-28 19:28
duplicate of https://github.com/grafana/grafana/issues/5983

**Closed by torkelo** 2017-10-28 19:28 UTC
