### ISSUE TITLE
Query Influx $tag_metric not displaying graph

### ISSUE THREAD

**Issue by pdenning** [grafana/grafana#18527] opened 2019-08-13 05:02 UTC
**What happened**:
No graph is shown when using a influx query alias of $tag_metric and there is only a single metric in the group by

![query_with_alias_6 3 2](https://user-images.githubusercontent.com/32345323/62916162-97465580-bdda-11e9-98dc-12d6435761e0.jpeg)
Version 6.3.2 

**What you expected to happen**:
The graph to be displayed
![query_with_alias_6 2 5](https://user-images.githubusercontent.com/32345323/62916188-b349f700-bdda-11e9-86d7-223e008efc66.jpeg)
Version 6.2.5

**How to reproduce it (as minimally and precisely as possible)**:

- Have data in an influx database with only one metric for your search 
- Query the data with a group by metric.
- Have an alias of $tag_metric

**Anything else we need to know?**:
Graph displays when you remove the alias
![query_with_noalias_6 3 2](https://user-images.githubusercontent.com/32345323/62916220-d4124c80-bdda-11e9-811d-afbcd0a82940.jpeg)

Works when there are multiple metrics to group by. 
![query_with_alias_6 3 2_multi_metrics_working](https://user-images.githubusercontent.com/32345323/62916201-c2c94000-bdda-11e9-87e8-2b7f332faad8.jpeg)
Version 6.3.2 with multiple metric tags to group by.

Graph works with version 6.2.5, Doesnt work for any 6.3+ 

 
**Environment**:
- Grafana version: 6.2.5 6.3.0, 6.3.1
- Data source type & version: InfluxDB 1.7.7
- OS Grafana is installed on: Offical Docker container 6.2.5, 6.3.0 and 6.3.2

- User OS & Browser: Default standard docker install
- Grafana plugins: Only default plugins
- Others:

**Comment by torkelo** [comment] 2019-08-13 06:45
dupe of https://github.com/grafana/grafana/issues/18479

**Comment by hugohaggmark** [comment] 2019-08-13 07:30
Duplicate of #18479

**Closed by hugohaggmark** 2019-08-13 07:30 UTC
