### ISSUE TITLE
Stat panel does not permit change base threshold color when the value is text

### ISSUE THREAD

**Issue by celsolom** [grafana/grafana#25867] opened 2020-06-26 14:57 UTC
Hi,

Stat panel does not permit change base threshold color when the value is text.
Im retrieving data from Zabbix via MySQL plugin, query format is Table, Panel value reducer is set to Last, fields select set to All Fields.
Im running two queries, one to retrieve hostname and another to retrieve the number of triggers alarmed for the host.
The numeric(triggers count) is fine but the hostname field dont change the threshold base color even using overrides.

![print](https://user-images.githubusercontent.com/20339961/85870894-0be07380-b7a4-11ea-9184-cd26626dd5b6.png)

**Queries**:
 _Hostname:_
 ```sql
SELECT SUBSTRING_INDEX((SELECT name FROM zabbix.hosts WHERE name = $Nome), '.', 1) AS name
```
_Triggers:_
```sql
SELECT * from triggers
WHERE triggerid IN (
	SELECT t.triggerid FROM hosts h, functions f, items i, problem p, triggers t
	WHERE h.name = $Nome
	AND t.value <> 0
	AND t.status = 0
	AND f.triggerid = t.triggerid 
	AND p.objectid = f.triggerid 
	AND f.itemid = i.itemid
	AND i.hostid = h.hostid 
	)
```

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: MySQL
- OS Grafana is installed on: CentOS 7
- User OS & Browser: LinuxMint 19.3 - Firefox 77.0.1 - Chrome 83.0.4103.106
- Grafana plugins: Stat, MySQL

**Comment by torkelo** [comment] 2020-06-28 06:26
Thresholds only operate on numeric values. 

We are working on a new color option to handle non threshold based color options:
https://github.com/grafana/grafana/pull/24763

**Comment by torkelo** [comment] 2020-06-28 06:27
duplicate of https://github.com/grafana/grafana/issues/25341

**Closed by torkelo** 2020-06-28 06:26 UTC
