### ISSUE TITLE
CloudWatch Logs: Make alertMaxAttempts configurable

### ISSUE THREAD

**Issue by ChenTsungYu** [grafana/grafana#63305] opened 2023-02-13 07:10 UTC
**What happened**:
Hi,
We have the Grafana alert based on AWS Cloudwatch Logs query. 
Sometimes the alert fails with the errors, and the error messages are below:
`logger=ngalert.scheduler rule_uid=oEDtfR2Vk org_id=1 version=13 attempt=0 now=2023-02-13T02:09:00Z t=2023-02-13T02:09:12.596886776Z level=error msg="Failed to evaluate rule" error="[plugin.downstreamError] failed to query data: fetching of query results exceeded the max number of attempts" duration=0s`

As per alert state histories, Sometimes all are good and data is returned and the alert works fine.
![Screenshot 2023-02-13 at 3 02 57 PM](https://user-images.githubusercontent.com/46296838/218392690-d82fb736-10f4-43e9-9a6a-da078a1525aa.png)

Does anybody have an idea?

**What you expected to happen**:
Alert shouldn't happen freqently.

**How to reproduce it (as minimally and precisely as possible)**:
Use the query from AWS CloudWatch log.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: CloudWatch
- OS Grafana is installed on: Amazon Linux
- User OS & Browser:
- Grafana plugins: CloudWatch
- Others:

**Comment by ChenTsungYu** [comment] 2023-02-17 09:47
hi,

Not sure if the request for fetching data from CloudWatch logs hit the limitation of the service quota since we can just identify problems from known log messages.

Maybe the service can provide errors in detail so we can identify the root cause.

Besides, we're trying to change the frequency of log queries from every 10s to 1min to fire Grafana alerts and keep observing their status.
If any feedback, I'll update it here.

Ref:
- [CloudWatch Logs quotas](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html)

Thanks!

**Comment by grobinson-grafana** [comment] 2023-02-24 10:35
Hi! Did you have any success changing the query from every 10 seconds to every 1 minute? We think this might be an issue with the Cloudwatch Logs Datasource (plugin).

**Comment by ChenTsungYu** [comment] 2023-03-09 14:49
Hi,

Yes. It still happened from time to time even I changed the query from every 10 seconds to every 1 minute.

**Comment by sarahzinger** [comment] 2023-03-15 19:28
Hi @ChenTsungYu I think the original theory here that this is related to hitting a limitation with [Cloudwatch Logs quotas](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html) seems the most likely. I agree though, Grafana could improve error handling here to at least make more clear where this error comes from and possible workarounds.

Some things that jump to mind:

> A maximum of 30 concurrent CloudWatch Logs Insights queries, including queries that have been added to dashboards. This quota can't be changed.

Do you have any log queries that are particularly slow? How many log queries are you making at once? Is it possible you've hit 30 at once sometimes?

>30 requests per second in Europe (Paris).
25 requests per second in the following Regions:
US East (N. Virginia)
US East (Ohio)
US West (N. California)
Africa (Cape Town)
Asia Pacific (Hong Kong)
Asia Pacific (Mumbai)
Asia Pacific (Seoul)
Asia Pacific (Singapore)
Asia Pacific (Tokyo)
Asia Pacific (Sydney)
Canada (Central)
Europe (London)
Europe (Milan)
Europe (Stockholm)
Middle East (Bahrain)
South America (São Paulo)
AWS GovCloud (US-East)
AWS GovCloud (US-West)
10 requests per second in all other Regions.
This quota can't be changed.

The fact that you still see the error when you call once every minute is interesting and makes me think it's not related to this, but I suppose if you had say several developers all looking at a grafana dashboard during an incident it seems plausible to me that you could have several folks refreshing their screens making the same query in the same second right as the alert fires off?

Out of curiosity, do you know how many cloudwatch logs are you making at a time? Do you know roughly how long those queries run for?

**Comment by ChenTsungYu** [comment] 2023-03-27 01:38
Hi @sarahzinger,

I think your assumption is correct. 

As per discussion with AWS support, the concurrent CloudWatch Logs Insights queries have already exceeded the limitation.

**Comment by sarahzinger** [comment] 2023-04-07 14:15
@ChenTsungYu I think the next step then is for us to improve our own error handling so that it is clear to users that the issue here is with running into Cloudwatch Quota Limits and not within the plugin. I created this ticket: https://github.com/grafana/grafana/issues/66171 I don't have a specific timeframe on this but we really appreciate you bringing this to our attention! I will close this ticket, but let me know if we've missed anything and I can reopen!

@Fantaztig I believe if you're getting the exact same error message of "fetching of query results exceeded the max number of attempts" then I don't believe the issue is with timeouts, but is with hitting a quota limit with AWS, so I don't think adjusting any configurations in Grafana Cloud would be helpful. However if you believe I'm mistaken and want to adjust a configuration setting, the configuration settings in that would be in a .ini file for OSS are adjustable in Cloud, just send over an email to customer support and they can try to help!

**Comment by sarahzinger** [comment] 2023-05-18 18:46
Hey sorry, revisiting this and seeing I missed something the first time I took a look at this. The error message of "fetching of query results exceeded max number of attempts" might be coming from Grafana:
https://github.com/grafana/grafana/blob/49467b3e5a9610ccb6c15aa75fe1fc4e91d936ee/pkg/tsdb/cloudwatch/log_sync_query.go#L111

I think the part here that threw me is that the error message you pasted:
```fetching of query results exceeded the max number of attempts```
is ever so slightly different from the actual error message without `the`:
```fetching of query results exceeded max number of attempts```

Can you confirm the existence of the word `the` in your error mesage?

It looks like we have a hard coded limit here of 8 requests which seems a bit arbitrary to me:
https://github.com/grafana/grafana/blob/49467b3e5a9610ccb6c15aa75fe1fc4e91d936ee/pkg/tsdb/cloudwatch/log_sync_query.go#L18

Recommend we reopen and see if we might be able to make that a configurable setting

**Comment by ChenTsungYu** [comment] 2023-05-19 01:19
Hi @sarahzinger,

Thanks for your confirmation!

As per checking on my end, the error message I saw : `fetching of query results exceeded the max number of attempts`.
No existence of the word the in my error message. :)

Besides, I saw the error messages like `Error = [plugin.downstreamError] failed to query data: fetching of query results exceeded max number of attempts` via webhook of Microsoft Teams after I upgrade Grafana from v9.3.1 to v9.5.1
![Screenshot 2023-05-19 at 9 17 27 AM](https://github.com/grafana/grafana/assets/46296838/9c0366a5-ca6e-4f19-96c0-38aed35930a7)

**Comment by iwysiu** [comment] 2023-05-23 14:30
Thanks for the feedback! I've renamed it to describe what we want to do better and I've moved it to our backlog.

**Closed** 2023-08-03 17:35 UTC
Labels: datasource/CloudWatch Logs

**Comment by idastambuk** [comment] 2023-08-03 17:56
Hi @ChenTsungYu regarding the ```Error = [plugin.downstreamError] failed to query data: fetching of query results exceeded max number of attempts``` (without "the" 🙂 )

We just merged https://github.com/grafana/grafana/pull/72611 to main, pending release of 10.2.0.
This increases the timeout by default, no change needed.
This should give the alerting queries more time to get the results. The next timeout these queries might hit is the timeout for general alerting which is by default 30 seconds. The error then will contain something like "context cancelled".

Let us know if this resolves the issue!
