### ISSUE TITLE
Alerting: Evict alert history over time

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#73856] opened 2023-08-25 16:30 UTC
### What happened?

The `alert_configuration` table has a system to evict history as it gets very old - but the `alert_rule_version` table does not.

This can result in the rule history table growing unboundedly, one user reported a 13gb table over a very long period of use.

We should use a similar eviction system for that table.

### What did you expect to happen?

I expected the rule version history table to be bounded like the config history one is.

### Did this work before?

No

### How do we reproduce it?

1. Use sqlite to make things easy
2. Update a rule repeatedly - hundreds of times
3. Watch the database size grow forever

### Environment (with versions)?

Grafana: main
OS:
Browser:

### Grafana platform?

None

**Comment by armandgrillet** [comment] 2023-08-29 16:21
We should do something like https://github.com/grafana/grafana/pull/51497

**Comment by bbung** [comment] 2023-09-21 07:57
Hey,

we are using Grafana 10.1.1 and the k8s-sidecar 1.24.6.
   
We are facing the same issue. The entries in the table alert_rule_version just gets bigger and bigger. It was at some point at 75GiB. 

We are using Grafana with the sidecars to deploy about 90 alerts from config maps. 
The http://localhost:3000/api/admin/provisioning/alerting/reload endpoint is reporting a 200 so no errors in our alert configs.

as soon as we activate the calling of the reload url from the side car
(eg.
+        - name: REQ_URL
+          value: http://localhost:3000/api/admin/provisioning/alerting/reload
+        - name: REQ_METHOD
+          value: POST
)
the numbers are starting to increase every couple of seconds.

Alerts however are provisioned but the database is spammed. So the provisioning is not usable at the moment. Any suggestions on how to mitigate this issue?

Thanks

**Comment by PyAgni** [comment] 2023-10-05 20:48
I've raised a fix for this issue. This is my first contribution here, let me know if the PR looks good! 

cc: @alexweav @armandgrillet

**Comment by lakrass** [comment] 2023-11-24 10:57
Got the same problem here with Grafana v10.2.1. I'm using the [Grafana Helm-Chart](https://artifacthub.io/packages/helm/grafana/grafana) with alert rule sidecar for provisioning and our database (the table alert_rule_version) is growing rapidly on just about 100 alert rules.

I've just tested to delete the configmaps within Kubernetes as a workaround for the db being spammed. This seems to work: 
`SELECT COUNT(*) from alert_rule_version;` returns the same amount of rows after a while of deleting the configmaps.

So if you want to use the provisioning mechanism with the sidecar container from the mentioned Helm-Chart, you need to delete the configmaps after them being applied to Grafana. The alerts will remain in Grafana, as you need to delete them as mentioned in the [docs](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#create-and-manage-alerting-resources-using-file-provisioning).

**TL;DL:**
Workaround if you use the [Grafana Helm-Chart](https://artifacthub.io/packages/helm/grafana/grafana) with alert rule sidecar:

1. Apply alert-rule configmaps to Kubernetes
2. Wait for alert-rules being created (mostly immediately after applying configmaps, as sidecar calls refresh API endpoint)
3. Delete alert-rule configmap and the alert_rule_version table should stop being spammed

**Comment by bbung** [comment] 2023-11-24 11:09
Hey @lakrass,

thank you for sharing. As we currently provision the config maps through argocd a deletion is not an option. We currently created an EVENT in the database which truncates the table every day. But how you describe the issue, this could also be the cause of the high load on the database we are experiencing. 

I cannot imaging that there are just a couple of people using this sidecar and getting this error. One could come to the conclusion that either that feature is not used or that maybe thousands of users just keep increasing their database servers. 

This should be a higher priority issue!

@PyAgni your PR looks so close to getting through the process, any chance you can address the open checkpoints.

I would really appreciate it.

**Comment by DrDJIng** [comment] 2023-11-24 12:42
> I've raised a fix for this issue. This is my first contribution here, let me know if the PR looks good!
> 
> cc: @alexweav @armandgrillet

I think this is a good change to have, but doesn't fix the underlying problem.

Versioning alerts should only happen when a change in a rule is detected.

I think it might be [this function here](https://github.com/grafana/grafana/blob/7a46d6a1b391febc4057897ef4e7f75daf6afdce/pkg/services/ngalert/provisioning/alert_rules.go#L341), as I don't see a check for whether an incoming rule is identical to the stored rule.

I think if this check is added, then the InTransaction for the store won't trigger, and so won't create a version in the database.

**Comment by lakrass** [comment] 2023-11-24 20:34
> @bbung: "As we currently provision the config maps through argocd a deletion is not an option."
This is indeed is a big problem for IaC with argocd. I agree!

> @bbung: "We currently created an EVENT in the database which truncates the table every day."
Yes, this is like my solution yet another workaround. Would be a good thing to catch up on the root of the problem.
 
> @bbung: "I cannot imaging that there are just a couple of people using this sidecar and getting this error. One could come to the conclusion that either that feature is not used or that maybe thousands of users just keep increasing their database servers."
Yep.. Actually I'm not sure if the sidecar is the cause of this issue. I haven't tested if it's triggering the reload API call in a loop or something. But as I've understood the param REQ_URL in [the sidecars readme](https://github.com/kiwigrid/k8s-sidecar) it shouldn't be doing that. Instead it only should fire in case the configmap reloads. 
Also I excluded this as a possible behavior, as I should have had issues whith that in another situation. 

Anyway, I totally agree to @DrDJIng:
> @DrDJIng: "Versioning alerts should only happen when a change in a rule is detected."
That behavior would fix the root of this issue and also protect the database against anyone who spams the reload for any reason. 

> @bbung: "This should be a higher priority issue!"
I also agree.

**Comment by lakrass** [comment] 2023-11-24 21:08
Actually, do we even need versioning on provisioned rules? Or at all? Can someone explain what's the use case of the versioning?

**Comment by alexweav** [comment] 2023-11-24 21:28
The versioning is not used at all right now, by anything. It's a mechanism that's been around in the system for a few years now and hasn't been really leveraged or touched. We've seen a handful of cases where operators/administrators were able to use the versioning table to restore accidentally modified rules, so it's had some rare uses over time, but there is no way to interact with it directly over the API.

> Versioning alerts should only happen when a change in a rule is detected.

Roughly a year ago, the rule version got promoted from a rule-level field to a group-level field. That is to say, one rule changing means that the entire group is considered to have changed. A side effect of this is, you get lots of row-spam in this table with seemingly no actual changes at the rule level. If you have 10 rules in a group and one changes, you get 10 version updates. This is one vector for the unreasonable growth, and I agree is something we should fix independently.

> As we currently provision the config maps through argocd a deletion is not an option.

The version entries are separate from rules, and cannot be directly created or deleted via API or by file provisioning at all. Deletion of the record is completely transparent to API users, it won't affect this use case. This table acts more like an audit log, the rows aren't really managed objects in the system.

IMO there should not be an infinitely growing audit log of changes without any eviction mechanism, or you get these unusual, infinitely growing tables. I agree more could (and probably should) be done around this table, but I also think eviction should happen on top of that as a guardrail, or else this table will always infinitely grow as time passes and resources change. Even if the rate of change is reduced, it'll still grow without any cap and will be problematic again sometime in the future.

I'm not totally against the idea of just deleting the table entirely, as it's literally unused right now, but the rare admin use-case has proven useful in the past. It also might be interesting to add a UI that lets you restore soft-deleted rules or something, this table could be used to support that?

**Comment by lakrass** [comment] 2023-11-24 21:51
@alexweav thank you for your explanations! 

I do get why the versioning mechanism has been implemented. There a hand full of valid use cases that can be built on that if requested. 

In my opinion a quick and clean solution would be the deletion of the table and removing the row creation in the source code. At the point someone is requesting a useful feature where the versioning is needed the code can be restored from git. 

I personally prefer to let versioning happen through IaS + provisioning and would recommend that to others too. But I also understand why someone would like to do something like that with the UI. 

But as long as nothing is implemented based on that table, why not get rid of it? Nothing is lost, the code could be restored if needed

**Comment by lakrass** [comment] 2023-11-24 21:59
@alexweav thank you for your explanations!

I do get why the versioning mechanism has been implemented. There are a hand full of valid use cases that can be built on that.

In my opinion a quick and clean solution would be the deletion of the table and removing the row creation from the source. At the point someone is requesting a useful feature, where the versioning is needed, the code can be restored from git (and a check like mentioned by @DrDJIng could be added).

I personally prefer to let versioning happen through IaC + provisioning and would recommend that to others too. But I also understand why someone would like to do something like that with the UI as IaC is not always is the holy grail.

But as long as nothing is implemented based on that table, why not get rid of it? Nothing is lost, the code could be restored if needed.

**Comment by DrDJIng** [comment] 2023-12-08 09:18
@alexweav We think this is actually causing issues with file provisioning in our Grafana instance. The database is used so much due to this versioning that we often get timeout errors when trying to write dashboards, alerts, etc.

If you have a preferred solution to this, I wouldn't mind making a PR with that. Otherwise I can add in a check for writing, and try and track down why it checks the versions so often. 

This is a high priority for us right now, as we have a lot of provisioned files that are modified often, especially dashboards, so we think it's worth the effort to help to correct this.

**Comment by DrDJIng** [comment] 2024-03-13 13:34
This issue is starting to become a real problem for us. Grafana is so busy creating versions in the database it's starting to throw errors because of database locking problems, and it can take a long, long time for changes in provision configmaps to be reflected in Grafana itself.

**Comment by ammarmahmood1999** [comment] 2024-05-08 09:52
As a temporary solution, I've adjusted the configuration, but it's clear that this isn't a long-term fix. It's crucial for Grafana to prioritize addressing this bug.
```
sidecar:
  alerts:
    skipReload: true
    initAlerts: true
```

**Comment by Loucool111** [comment] 2024-06-10 07:54
Any updates on this? I'm currently running into the same issue on multiple Grafana instances.

Looks like #76084 has never been merged

**Comment by DrDJIng** [comment] 2024-06-26 09:32
That PR would help, but I think it would be better if we could just turn off the alert versioning entirely. When it's versioning each of our 500 provisioned alerts multiple times per second, this is a huge drain on our database resources.

**Comment by igloo12** [comment] 2024-06-26 23:11
@DrDJIng looking at the code it resaves all the alerts in the same group.

```
// UpdateCalculatedRuleFields refreshes the calculated fields in a set of alert rule changes.
// This may generate new changes to keep a group consistent, such as versions or rule indexes.
```

Have you tried dividing the alerts into smaller groups to reduce redundant saves?

**Comment by DrDJIng** [comment] 2024-06-28 05:49
They're are grouped in a lot of different groups already. The issue we're having is just a constant creation of alert history, despite the fact that there are no changes in the alerts. Some of our alerts are up to over version 1, 000, 000! 

I haven't had a chance to deeply inspect the code yet, but my instinct tells me it's to do with the provisioning system and the configmaps. Perhaps something like every time a configmap is read that asks grafana to add an alert, even if that alert is already there, grafana versions the alert history?

Though now that I'm typing this out, I think this is likely a separate issue.

**Comment by igloo12** [comment] 2024-06-28 15:54
@DrDJIng I agree sounds like it might be a separate issues. Do you have steps to reproduce?  When you are experiencing the versioning updates? Is it only occurring when you are updating another rule?

**Comment by redisded** [comment] 2024-09-19 09:29
Hello everybody, we just have the same problem of excessive entries in the table alert_rule_version, using argocd and grafana-operator to deploy alert_rules.

When I compare two entries for the same alert rule, the only changes I get are on the fields **id**, **parent_version**, **version**, and **created**.
This last field is a bit confusing because it sometimes differs of only one second between two version, and is at the time of the insertion of the new version, so it seems to been the date/time of the creation of the version, not the rule. Not sure this is really relevant, but I thought it was worth mentioning.

Anyway, I agree with the fact that it should be a high priority, and I'm also convinced that a lot of people are actually facing a big growth of their database, without knowing it (we have dev instance with a low disk space pv wich hit the roof, so we "accidentally" acknowledged the problem).
More worrying than that, we have to face a non negligible number of "database locked" errors in grafana logs because of these massive and unnecessary database updates.

I also think that offering the possibility to deactivate versioning for alert rules would be a more acceptable solution than just cleaning this table on a regular basis, as we have a versioning mecanism with IAC (and as the cleaning solution does not resolve the database locks problems).

I unfortunately cannot help on the code, but willling to make some further test or provide more details on our installation if it can help  to move forward on this topic.

**Comment by igloo12** [comment] 2024-09-19 10:40
@redisded The PR is in the final stages. I just need a member of Grafana to allow the unit tests to run

**Comment by redisded** [comment] 2024-09-19 11:39
@igloo12 We're talking about this one : https://github.com/grafana/grafana/pull/89754 ?
It's only addressing the limit of database growing as I understand it. Am I correct ?
Nothing in view for the initial problem, which is the process that keep writing new versions to this table dispite the fact that the alert rules are not modified ?

**Comment by igloo12** [comment] 2024-09-20 15:18
@redisded Yes, changing the saving how the saving works would require a significant code change or calculating of diffs, which can be tricky, something the Grafana team would need to bless first. If you haven't done so, only things in the same group will be updated on save, so if you can divide your alerts into smaller groups, that might help.

**Closed** 2024-10-04 21:31 UTC
Labels: type/bug, area/alerting, prio/low, area/backend, good first issue, internal
