### ISSUE TITLE
[Bug] - Alerts from hidden panels are not working when using webhook notification channel

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#11414] opened 2018-03-28 11:57 UTC
What Grafana version are you using?
Version 5.0.2

What datasource are you using?
influxdb

What OS are you running grafana on?
Amazon Linux AMI

Hi,
I've configured alert notification channel to send alerts to Opsgenie via webhook.
I'm using two notification channels in my alert configuration: Email & Opsgenie
When I collapse a row with alerting graph and save the dashboard an email regarding the alert is being sent to the designated email address but the Opsgenie integration via webhook is not working and the alert is not being opened in OpgGenie.

If I extend a row with alerting graph and save the dashboard, both email & OpsGenie notification channels are working fine.

**Comment by bergquist** [comment] 2018-03-28 12:12
Dupe of https://github.com/grafana/grafana/issues/11296

We will release 5.0.4 during the day with that fix.

**Closed by bergquist** 2018-03-28 12:12 UTC
