### ISSUE TITLE
Explore: expand results for "raw" format with split pane does only expand (left) side

### ISSUE THREAD

**Issue by mike2194** [grafana/grafana#76561] opened 2023-10-13 15:02 UTC
### What happened?

Within Explore, when viewing prometheus query results in "raw" form on a split pane user is given the option to _expand results_ but only the "left" split-pane does expand.
when user clicks the _expand results_ switch on either "left" or "right" split-pane, only the "left" side does expand.

### What did you expect to happen?

I expected results to expand in the same split-pane for the specific pane where i clicked _expand results_.

### Did this work before?

unknown, prior to v10.1.4

### How do we reproduce it?

1. go to explore
2. make query with prometheus datasource and choose "raw" results format
3. split the panes and refresh results
5. doesn't matter if you expand before splitting
6. doesn't matter if you have different queries
7. click _expand results_ in "left" or "right" pane
9. you can only expand/collapse results on the "right" pane if it's the only pane / close the "left" pane

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: v10.1.4
OS: docker.io/grafana/grafana:10.1.4
via Helm chart: 6.60.4
Browser: Chrome (117.0.5938.149 (Official Build) (x86_64))

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by Elfo404** [comment] 2023-10-27 09:00
closing this as duplicate of https://github.com/grafana/grafana/pull/73864, the issue was fixed in 10.2.0

**Closed by Elfo404** 2023-10-27 09:00 UTC
Labels: triage/needs-confirmation
