### ISSUE TITLE
[Feature request] Custom numeric format for axes unit

### ISSUE THREAD

**Issue by fmcmarques** [grafana/grafana#8640] opened 2017-06-16 15:02 UTC
Grafana version: 4.3.2
Datasource: MySQL
OS: Windows 2008 R2

Doesn't exist a custom numeric format for axes unit that allows for example specifying decimal places and 1000 separator. 

Thanks

**Comment by torkelo** [comment] 2017-06-16 15:46
duplicate of https://github.com/grafana/grafana/issues/2968

**Closed by torkelo** 2017-06-16 15:46 UTC
