### ISSUE TITLE
RFE - Row Template Var 

### ISSUE THREAD

**Issue by stefws** [grafana/grafana#5546] opened 2016-07-10 00:03 UTC
- [x ] Feature request

Please include this information:
- What Grafana version are you using? 3.04
- What datasource are you using? ES 2.3
- What OS are you running grafana on? CentOS 6.8

Think it would be nice if one could define template variables per Rows as well as per Dashboard, eg. I like to define more Rows in my Dashboard and use template variables, only some are on valid on specific Rows, hence confusing that they all appear on top of dashboard. would be nice to be able to scope some variables to specific Rows only.

**Comment by torkelo** [comment] 2016-07-11 05:55
dupe of https://github.com/grafana/grafana/issues/5329

**Closed by torkelo** 2016-07-11 05:55 UTC
