### ISSUE TITLE
[Bug] Variable Interpolation CloudWatch Dimension Queries

### ISSUE THREAD

**Issue by dylanlive** [grafana/grafana#19021] opened 2019-09-11 18:53 UTC
**What happened**:
Variable Interpolation is no longer occurring in CloudWatch Dimension queries. This broke somewhere between v5.3.2 and v6.3.3

A query like `LoadBalancerName:"prod-elb"` now looks like `LoadBalancerName:"$environment-elb"`

Given Variables:
- environment: `prod`
- LoadBalancer: `$environment-elb`

And query:
- Metric: `AWS/ELB` `HTTPCode_Backend_2XX`
- Dimensions: LoadBalancerName: `$LoadBalancer`

Upon viewing query inspector:
Grafana v6.3.3 Request:
```
dimensions:Object
LoadBalancerName:"$environment-elb"
```

**What you expected to happen**:

Grafana v5.3.2 Request:
```
dimensions:Object
LoadBalancerName:"prod-elb"
```

**How to reproduce it (as minimally and precisely as possible)**:
Import this panel:
https://gist.github.com/dylanlive/876397d9cac2577d1f6c50bb57a00c76

Or, to set up manually:
1) Add two "Custom Type" variables:
- environment: `prod`
- LoadBalancer: `$environment-elb`

2) Add a graph, with metric:
 `us-west-2` / `AWS/ELB` / `HTTPCodeBackend_2XX` Stats: `Sum`
Dimensions: `LoadBalancerName = $LoadBalancer`

3) Open Query Inspector, view:
request -> data -> queries -> 0 -> dimensions

Expected: `LoadBalancerName:"prod-elb"`
Actual: `LoadBalancerName:"$environment-elb"`

**Anything else we need to know?**:
Query inspector output:
https://gist.github.com/dylanlive/6a632d78225df2685fb16eafbd340305

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: AWS CloudWatch, included version
- OS Grafana is installed on: Unsure
- User OS & Browser: macOS, Chrome
- Grafana plugins:
- Others:

**Comment by lfroment0** [comment] 2019-10-04 08:38
Running this in Grafana 3.6.5, I couldn't replicate this issue it seems to work fine
```
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1570012570026",
      "to": "1570034170027",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 467,
          "datasourceId": 7,
          "type": "timeSeriesQuery",
          "namespace": "AWS/ApiGateway",
          "metricName": "CacheHitCount",
          "statistics": [
            "Average"
          ],
          "dimensions": {
            "LoadBalancerName": "prod-elb"
          },
          "period": "60",
          "region": "eu-central-1",
          "id": "",
          "expression": "",
          "returnData": true,
          "highResolution": false,
          "datasource": "CloudWatch"
        }
      ]
    }
  },
```

**Comment by sunker** [comment] 2019-11-21 12:36
I cannot reproduce this either @dylanlive. Can you please re-test this in 6.5-beta1 and verify you still have the same problem?

**Comment by dylanlive** [comment] 2019-11-22 19:57
Hmm I still seem to be reproducing on
Grafana v6.5.0-beta1 (ab9c0da)

Steps I took:
1) Create -> Import
2) Pasted code from https://gist.github.com/dylanlive/876397d9cac2577d1f6c50bb57a00c76
3) Chose my Cloudwatch Data source
4) Clicked on Panel -> Edit -> Query Inspector
5) Expanded Request -> Data -> Queries -> 0 -> dimensions -> LoadBalancerName

![Screen Shot 2019-11-22 at 11 56 02 AM](https://user-images.githubusercontent.com/4992944/69456309-2ee30a80-0d1f-11ea-87ba-193f6bf05391.png)

Expected "prod-elb"

**Comment by eholzbach** [comment] 2019-11-25 17:38
This works in 6.1.6. It's broken in 6.2 through 6.5.

**Comment by hugohaggmark** [comment] 2020-11-12 09:34
I think the root issue here is that Custom Variables can't interpolate other variables so the string __`$environment-elb`__ will not be interpolated as __`prod-elb`__ in the Custom Variable. 
I've tried the repro steps for v5.3.2 and v6.1.6 but neither work as explained in the repro steps, so I'm going to close this issue. 

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2020-11-12 09:34 UTC
Labels: area/datasource, datasource/CloudWatch, type/bug, version/6
