### ISSUE TITLE
Seeing warning message in Grafana Log histogram from v10.3+

### ISSUE THREAD

**Issue by gs-mteki** [grafana/grafana#85135] opened 2024-03-26 06:48 UTC
### What happened?

After upgrading to v10.3. We are seeing below error in histogram place.
<img width="1715" alt="image" src="https://github.com/grafana/grafana/assets/76043674/c7601dc7-50f3-41d4-9450-9b80657f6282">

I seen few issues in internet, in all scenarios, issue is with the loki query but in my case logs are coming without any issues but the graph panel in grafana explore is not loading.

In few forum they mentioned sometimes this issue comes due to browser extension but I try to access the same URL in Chrome, Safari, Edge and Firefox in all the browsers I am seeing same issue.

While debugging I inspected the page and see the console for any error than I found two errors.

 - POST API call to` /api/ds/query?ds_type=loki&requestId=explore_m1n_logs_volume_0_1` endpoint is failing with 400 error.
  Same API endpoint is getting success for 10.2.2 version.
- The second one is I am seeing below message as Uncaught exception

```
message : "parse error at line 1, col 90: syntax error: unexpected IDENTIFIER" 
refId : "log-volume-A" 
status : 500
```
Is there any configuration changes I missed. Could someone help us on this ?

### What did you expect to happen?

In grafana explore, when we explore the logs. We see the histogram where we see the logs occurrences over time.
<img width="1710" alt="image" src="https://github.com/grafana/grafana/assets/76043674/25117b2e-66bc-4fc7-9523-2f294d281183">

### Did this work before?

Yes, Grafana version is 10.2.2

### How do we reproduce it?

1. Upgrade to latest version
2. Go to Grafana explore page
3. Search for any logs

### Is the bug inside a dashboard panel?

NO

### Environment (with versions)?

Grafana: Open Source v10.3+
OS: Amazon Linux 2
Browser: Chrome, Safari, Firefox, Edge

### Grafana platform?

A downloaded binary

### Datasource(s)?

Loki

**Comment by StefanLobbenmeierObjego** [comment] 2024-04-03 16:15
Duplicate of #84144

**Comment by tonypowa** [comment] 2024-04-23 13:41
Thank you for reporting this issue @gs-mteki 
However, I am closing it in favour of https://github.com/grafana/grafana/issues/84144
Please monitor the related issue for updates

**Closed by tonypowa** 2024-04-23 13:41 UTC
