### ISSUE TITLE
Tooltips for Time Series displays at bottom of page or off page

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#34777] opened 2021-05-26 23:33 UTC
**What happened**: Tooltips are located at bottom of page or very far below Time Series chart

**What you expected to happen**: Tooltips should show on the chart as you scroll

**How to reproduce it (as minimally and precisely as possible)**: I am using Rows, which may be attributing to the issue. Create two rows, with Time Series charts on each.  Enable to show All tooltips, apply.  scroll along chart to view values

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.0-beta2 (9d4c719205)
- Data source type & version: influx, 1.8.6-1 armhf
- OS Grafana is installed on: Linux raspberrypi 5.10.17-v7l+
- User OS & Browser: Windows 10, Chrome, Brave, Windows Edge
- Grafana plugins: Time Series
- Others:
![Time_Series_ToolTips](https://user-images.githubusercontent.com/510960/119744034-c19ec100-be50-11eb-95db-910bb4089ee1.png)

**Comment by leeoniya** [comment] 2021-05-27 01:05
yep, we're already on it: https://github.com/grafana/grafana/pull/34584

**Comment by leeoniya** [comment] 2021-05-27 01:06
duplicate of #34347

**Closed by leeoniya** 2021-05-27 01:06 UTC
