### ISSUE TITLE
Grafana has failed to load its application files after upgrading to 8.0.2

### ISSUE THREAD

**Issue by balintjuhasz** [grafana/grafana#35927] opened 2021-06-18 08:26 UTC
**What happened**:
After upgrading from 7.5.6 to 8.0.2 all seemed to be running great, except our video wall was unable to load anything from Grafana: "If you're seeing this Grafana has failed to load its application files" followed by 5 steps and none of them worked.

**What you expected to happen**:
Dashboard should be present on screen.

**How to reproduce it (as minimally and precisely as possible)**:
1. Download package from https://dl.grafana.com/oss/release/grafana_8.0.2_amd64.deb
2. dpkg -i grafana_8.0.2_amd64.deb
3. Restart Signage box to empty cache and reload 

**Anything else we need to know?**:
We are using 5 Samsung Signage devices on 8 screens running with Tizen OS 4.0. These devices also access Grafana with auth.proxy and it seems to be working:
```
   window.grafanaBootData = {
          user: {"isSignedIn":true,"id":2,"login":"<actual_username>","email":"<users_email>","name":"<actual_username>","lightTheme":false,"orgCount":1,"orgId":1,"orgName":"<actual_ord>","orgRole":"Viewer","isGrafanaAdmin":false,"gravatarUrl":"/avatar/3adada482768183ebb28d85e79ec0b91","timezone":"browser","locale":"en-US","helpFlags1":0,"hasEditPermissionInFolders":false}
```

Checking it from my machine, using the devices User-Agent and using the header for auth proxy, it loads successfully.

Grafana worked from Windows, Linux and OS X, it looks like the issue is present only when opening from the devices.

**Environment**:
- Grafana version: _8.0.2_
- Data source type & version: _-_ 
- OS Grafana is installed on: _Debian 10 (buster)_
- User OS & Browser: _Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36_
- Grafana plugins: _-_ 
- Others: _nginx, auth proxy_

Let me know if you need anything else, any help would be appreciated!

Thanks!

**Comment by wbrowne** [comment] 2021-06-21 13:03
Hi @balintjuhasz. Would you be able to provide the server logs? There may be something in there that highlights some other useful information

**Comment by balintjuhasz** [comment] 2021-06-22 09:05
Hi @wbrowne,
Sure, we have a cloned environment set up for debugging.
I increased log verbosity to see more:

```
[log]
level = debug
```

```
t=2021-06-22T10:59:17+0200 lvl=dbug msg="Trying to log user in" logger=auth.proxy username=<username> ignoreCache=false
t=2021-06-22T10:59:17+0200 lvl=dbug msg="Getting user ID via auth cache" logger=auth.proxy cacheKey=auth-proxy-sync-ttl:6181d9351a05cd6b6a14a78bc2cc5fd0
t=2021-06-22T10:59:17+0200 lvl=dbug msg="Successfully got user ID via auth cache" logger=auth.proxy id=2
t=2021-06-22T10:59:17+0200 lvl=dbug msg="Got user ID, getting full user info" logger=auth.proxy userID=2
t=2021-06-22T10:59:17+0200 lvl=dbug msg="Successfully got user info" logger=auth.proxy userID=2 username=<username>
t=2021-06-22T10:59:17+0200 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=<username> user_id=2
t=2021-06-22T10:59:17+0200 lvl=info msg="Request Completed" logger=context userId=2 orgId=1 uname=<username> method=GET path=/d/W4I3XITiz/monitoring-dashboard status=200 remote_addr=<IP> time_ms=19 size=46573 referer=
```

Let me know if you need anything else.

**Comment by TrickUK** [comment] 2021-06-23 07:45
We also have the same problem with our Samsung dashboards with Tizen 5.0, with no authentication.  Was working just fine under version 7, but the upgrade to 8.0.3 has produced this behaviour.  Will see if I can remote debug the web application and see if there's anything logged to the console.

**Comment by TrickUK** [comment] 2021-06-23 08:27
Okay so I have finally managed to get a remote debug session working (thanks to portableapps.com for an old enough version of Chrome to load inspector!).

I receive:
`Uncaught SyntaxError: Unexpected token {`
on line 3118 of app*.js:
![image](https://user-images.githubusercontent.com/1598146/123063053-f7f63e80-d404-11eb-9cd8-87d618dabb93.png)

Any help?

**Comment by wbrowne** [comment] 2021-06-23 08:35
@TrickUK @balintjuhasz Are there any errors from the JS console? Also can you see any failed requests from your browser network tab?

**Comment by balintjuhasz** [comment] 2021-06-23 08:37
I'm not sure how can I look at the Signage box's JS console, I'll take a look if I can.

**Comment by TrickUK** [comment] 2021-06-23 08:53
> @TrickUK @balintjuhasz Are there any errors from the JS console? Also can you see any failed requests from your browser network tab?

That is the JS console:
![image](https://user-images.githubusercontent.com/1598146/123066208-c0d55c80-d407-11eb-8f2c-f02835e51388.png)

All resources load successfully:
![image](https://user-images.githubusercontent.com/1598146/123067283-c1babe00-d408-11eb-92bf-07263845eb9e.png)

**Comment by wbrowne** [comment] 2021-06-23 11:30
@TrickUK Are you also running Grafana with a reverse proxy?

**Comment by TrickUK** [comment] 2021-06-23 11:46
Yes indeed, behind Apache:
```
<VirtualHost *:80>
        ServerName grafana.domainname.co.uk
        ServerAdmin webmaster@localhost

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Location "/">
          ProxyPass http://localhost:3000/
        </Location>
        ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

No sub path.  This all worked perfectly before and it looks like the grafana config remains as it was for version 7:
```
#################################### Server ####################################
[server]
# Protocol (http, https, h2, socket)
;protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = 127.0.0.1

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = grafana.domainname.co.uk

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
;root_url = http://grafana.domainname.co.uk/

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
;serve_from_sub_path = false

# Log web requests
;router_logging = false

# the path relative working path
;static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

# Unix socket path
;socket =
```

**Comment by balintjuhasz** [comment] 2021-06-29 07:40
I wasn't able to pull JS console from the boxes and we have no info from the supplier yet.

**Comment by balintjuhasz** [comment] 2021-06-30 10:15
An extra thing I found out is that the browser is identified as Samsung Browser 2.1

**Comment by torkelo** [comment] 2021-06-30 14:19
Samsung Browser 2.1 is very very old, based on a Chrome version 34 (from what I can tell) that Grafana no longer supports this old browser. 

Grafana 8 requires:
* Samsung internet browser v5+ 
* Chrome 49+ 
* Firefox 45+
* Edge 13+
* Safari 9+

**Comment by balintjuhasz** [comment] 2021-07-01 08:35
@TrickUK Can you share what type of devices you have along with firmware version? – we're in contact with Samsung
Here is ours:
```
Type: SBB-SS08NL1
Firmware: TB-KTM2SPMDWWC-1030.5;TB-KTM2SPMDWWS-1015
```

@torkelo That is bad news. :( Is there anything we can do to override or disable this check, perhaps a local patch? It seems like Samsung won't be able to upgrade the browser anytime soon.

I understand the reasons behind this change but we'd like to go ahead with Grafana 8 if it works with the browser despite he fact that it's been deprecated.

**Comment by TrickUK** [comment] 2021-07-06 07:34
Model: UE43RU7020KXXU
Software Version: T-MSLDEUC-1381.2

Ours is just a consumer TV hung on the wall.

**Comment by TrickUK** [comment] 2021-07-06 08:55
FYI, just upgrade to 8.0.4 and have the same behaviour.

**Comment by TrickUK** [comment] 2021-07-08 15:07
FYI, just upgrade to 8.0.5 and have the same behaviour.

**Comment by TrickUK** [comment] 2021-07-16 07:37
FYI, just upgrade to 8.0.6 and have the same behaviour.

**Comment by TrickUK** [comment] 2021-07-23 07:50
FYI, have now downgraded back to 7.5.10 (which worked particularly well) and I now have my dashboards working on the TV's again.

**Comment by Dominion0815** [comment] 2021-07-29 10:56
Same problem with Grafana 8.0.6 and Reverse Proxy Apache/2.4.38 (Debian).

Apache settings:
```
ProxyPreserveHost On
ProxyRequests Off

RequestHeader set X-Forwarded-Proto https

ProxyPass / http://127.0.0.1:3000/
ProxyPassReverse / http://127.0.0.1:3000/
```

**Comment by mckn** [comment] 2021-08-30 12:10
hmm, @marefr sounds like the application loading behind a reverse proxy is busted. Not sure this has to do with the browser version running on a TV since it sounds like @Dominion0815 has the same issue.

**Comment by mckn** [comment] 2021-08-30 12:11
I will see if I can reproduce it locally, will get back with more information.

**Comment by mckn** [comment] 2021-08-31 12:36
Not been able to reproduce it locally. @Dominion0815 @balintjuhasz @TrickUK is this still an issue for you guys?

**Comment by balintjuhasz** [comment] 2021-08-31 13:09
@mckn: v8.0.5 was the last version I tried with, I haven't tried 8.1 as I don't believe anything has changed regarding this.
I don't think reverse proxy is the issue because every device was able to load the new version, only the TVs showed the error page.

It's a shame though because we have no option to upgrade. :(

**Comment by mckn** [comment] 2021-08-31 13:25
Ok ok, then I'm agreeing with @marefr that we can close this one since we will not support `Samsung internet browser < v5`.

**Closed by mckn** 2021-08-31 13:25 UTC
Labels: needs investigation, type/browser-compatability
