### ISSUE TITLE
[bug] plugins in data/plugins directory get 401 unauthorized instantiation

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#9692] opened 2017-10-26 18:54 UTC
Please include this information: 
- What Grafana version are you using? 
4.6.0

- What datasource are you using?
Graphite, and influxdb

- What OS are you running grafana on?
Linux

- What did you do?
Attempted to add a panel which is installed locally in the data/plugins directory

- What was the expected result?
Panel was added

- What happened instead?
Received an error like this:
```
Plugin Error
Fetch error: 401 Unauthorized Instantiating https:/xxxx.com/public/plugins/natel-discrete-panel/module.js Loading plugins/natel-discrete-panel/module
```

And the panel can't be added.

- More information below:
Server is behind ldap authentication reverse proxy.  If I turn OFF the requirement for ldap auth, it adds the panel fine.

Note that I'm running version 4.4.1 in production right now, with this same exact config, and there are no problems.

Did some behavior for loading plugin panels change dfrom 4.4.1 to 4.6.0 ?

**Comment by daniellee** [comment] 2017-10-26 19:01
Sounds like this: https://github.com/grafana/grafana/issues/9509

**Comment by blysik** [comment] 2017-10-26 20:25
As a workaround, I can switch to having grafana natively handle auth via ldap.

**Comment by qrtalaci** [comment] 2017-10-26 20:33
I'm in the same stuatuion after upgraded from v4.5.1 to v4.6.0. Wordmap and Hetmap plugins do not work now. Can we fix the issue with some config modification?

**Comment by torkelo** [comment] 2017-10-27 05:11
If you have auth proxy in front of grafana you need to exclude grafana  static assets path /public

**Comment by aenima-x** [comment] 2017-10-27 16:50
Does anyone know how to exclude the public url? 
I can't make it to work

**Comment by miton18** [comment] 2017-10-30 08:49
I cannot exclude this path, is there any way to set the Auth when loading plugins module.js ?

**Comment by aenima-x** [comment] 2017-10-30 12:16
Since the content in /public is static my solution was to create an alias in apache without Auth and server it from there

**Comment by dudusakharovich** [comment] 2017-10-30 14:13
@torkelo - Hey, Do you intend to fix this issue on the current/latest version ?

**Comment by dudusakharovich** [comment] 2017-10-30 14:23
Does anyone know how to exclude the /public path from auth ??

**Comment by torkelo** [comment] 2017-11-01 09:34
dupe of https://github.com/grafana/grafana/issues/9509

**Closed by torkelo** 2017-11-01 09:34 UTC
Labels: comp: backend/auth
