### ISSUE TITLE
Flux datasource leaking TCP connections

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#26912] opened 2020-08-11 07:20 UTC
**What happened**:
When running a flux query, 2 tcp connection to influxdb are opened and not closed. Over time, this results in grafana not accepting tcp connections with the following error: 
`http: Accept error: accept tcp [::]:3000: accept4: too many open files; retrying in 1s`

I the following GIF, I refresh a single flux query a few times, resulting in 2 extra open connections to influx each time (command:    `netstat -atn | grep ":8086" | wc -l`

![Aug-11-2020 09-07-20](https://user-images.githubusercontent.com/9944663/89868257-cb518380-dbb2-11ea-912d-343fc2c566d6.gif)

**What you expected to happen**:
Grafana not to crash every other day :-) 

**How to reproduce it (as minimally and precisely as possible)**:
Set up a panel with flux query and monitor TCP connections on port 8086.

**Anything else we need to know?**:
This was already mentioned in #26731, and a fix was released in 7.1.3, but the issue persists.
 
**Environment**:
- Grafana version: 7.1.3
- Data source type & version: InfluxDB 1.8.1 with flux.
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Any
- Grafana plugins: /
- Others:

**Comment by aknuds1** [comment] 2020-08-11 07:22
You mean Grafana version 7.1.3?

**Comment by coussej** [comment] 2020-08-11 07:26
@aknuds1 yes of course 🤦🏻‍♂️ Updated.

**Comment by aknuds1** [comment] 2020-08-11 09:44
I've made a PR that will hopefully help, by closing idle HTTP connections: https://github.com/grafana/grafana/pull/26917.

**Comment by aknuds1** [comment] 2020-08-11 11:05
In the interest of reproducing, can you specify more clearly how you configure your query?

**Comment by coussej** [comment] 2020-08-11 12:07
So, query is run agains the influx 1.8.1 flux compatibility endpoint. Just replace the series below with anything valid for your system. Run the query a few times while running `watch 'netstat -atn | grep ":8086" | wc -l'` on your grafana host.

```
f1 = from(bucket: "simulation_tanksystem")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "WP1_fill_level")
  |> aggregateWindow(every: 30s, timeSrc: "_start", fn: mean, createEmpty:false)

f2 = from(bucket: "simulation_tanksystem")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "WP2_fill_level")
  |> aggregateWindow(every: 30s, timeSrc: "_start", fn: mean, createEmpty:false)

join(tables: {a:f1, b:f2}, on: ["_time"])
  |> map(fn: (r) => ({
    _time: r._time,
    _field: "fill_level_total",
    _value: r._value_a + r._value_b
  }))
```

**Comment by aknuds1** [comment] 2020-08-11 12:19
I'm new to the InfluxDB data source; can you tell me how I should configure my data source, to reproduce? I've chosen InfluxDB and query language "Flux", but I'm not sure about the other fields. I'm using the development data source (`make devenv sources=influxdb`), and I think URL should be http://localhost:8086, and I put "grafana" for organization, but I'm not sure about the token (I put "grafana", which is the basic auth password) and the default bucket (no idea here).

**Comment by coussej** [comment] 2020-08-11 12:56
In case of influxDB 1.8.1, you should use.
```
url: http://localhost:8086/api/v2
token: username:password
```

**Comment by aknuds1** [comment] 2020-08-11 12:57
What can I put for default bucket? Do I need to put anything there?

**Comment by aknuds1** [comment] 2020-08-11 13:05
I get this error in the InfluxDB logs when I try to create the data source:

```
[httpd] 172.19.0.1 - - [11/Aug/2020:13:04:27 +0000] "POST /api/v2/query?org=grafana HTTP/1.1" 500 77 "-" "influxdb-client-go/1.3.0  (linux; amd64)" 2ffb116a-dbd3-11ea-814a-0242ac130002 8325
ts=2020-08-11T13:04:27.787040Z lvl=error msg="[500] - \"failed to initialize execute state: createBucketsSource: no user\"" log_id=0OZPe820000 service=httpd
```

**Comment by coussej** [comment] 2020-08-11 13:23
default bucket = your database name, but I don't think it's required. Is the datasource influx 2 or 1.8?

**Comment by aknuds1** [comment] 2020-08-11 14:26
I'm using 1.8.1. Is the user perhaps unrecognized?

**Comment by coussej** [comment] 2020-08-11 15:33
That's possible, I'm not familliar with the grafana dev sources

If you want, you can use the datasource from out demo influxdb, above query will work out of the box then:

use `temp_aknuds1:aknuds1` as a token. 

<img width="596" alt="image" src="https://user-images.githubusercontent.com/9944663/89916817-5acd5580-dbf8-11ea-9fe5-1b067a51129d.png">

**Comment by aknuds1** [comment] 2020-08-11 15:44
Thanks! Will see if I can give it a try.

**Comment by aknuds1** [comment] 2020-08-13 14:19
I could connect to your server, thanks. Seeing if I can reproduce.

**Comment by aknuds1** [comment] 2020-08-13 14:33
I configured Grafana to refresh every 5 seconds, and now it's hovering between 195 and 215 connections. Since the number has stagnated, maybe it's not a problem on my branch?

**Comment by coussej** [comment] 2020-08-13 14:55
Hi, if you refresh more often or add more queries, does it remain stable? We have for example dashboards running > 15 flux queries, refreshing quite often, with also alerts configured on them.

**Comment by aknuds1** [comment] 2020-08-13 15:01
When I refresh more often, it does increase, I can see that.

**Comment by aknuds1** [comment] 2020-08-13 15:03
Is it possible that the InfluxDB SDK doesn't close responses? AFAICT, the requests to Influx, when you use the Flux language, are completely handled by the InfluxDB SDK.

**Comment by aknuds1** [comment] 2020-08-13 15:05
Hm... reading the InfluxDB SDK code, it does provide a function to the caller for closing the response body, and I make sure to call that.

**Comment by aknuds1** [comment] 2020-08-13 15:10
The fix might actually be to close the query results returned by the Flux SDK, which I do in my branch. I'll prepare my PR.

**Comment by coussej** [comment] 2020-08-13 15:16
Probably is related to that. By comparison, when you configure the influx datasource to use influxQL instead of flux, number of connections immediately drops to < 20

**Comment by aknuds1** [comment] 2020-08-13 15:17
Even if I have implemented this fix, my number of connections is high. I couldn't see that creating all these connections happen in our code though, although maybe I'm missing something?

**Comment by aknuds1** [comment] 2020-08-13 15:26
@coussej Here's my fix https://github.com/grafana/grafana/pull/26917/files#diff-dd7a45a33cd3bc886a5a651b8eef8d24R36.

**Comment by aknuds1** [comment] 2020-08-13 15:44
Are you able to build Grafana from source, to try my fix?

**Comment by aknuds1** [comment] 2020-08-13 16:44
Actually, you don't need to build from source, you can try [this](https://grafana.com/grafana/download/7.2.0-39caf71dpre) snapshot build.

**Comment by coussej** [comment] 2020-08-14 10:56
@aknuds1 still there. But I traced it back to the influx go client. Connections are not closed after calling client.Close()... will create an issue with a reproduction on their repo.

**Comment by coussej** [comment] 2020-08-14 11:00
https://github.com/influxdata/influxdb-client-go/issues/183

**Comment by aknuds1** [comment] 2020-08-14 11:05
> @aknuds1 still there. But I traced it back to the influx go client. Connections are not closed after calling client.Close()... will create an issue with a reproduction on their repo.

Thanks for finding the issue @coussej, I was also suspecting the InfluxDB Go client code by now.

**Comment by aknuds1** [comment] 2020-08-14 12:30
I guess this might require some deeper debugging, to figure out what causes eventual leaking of connections.

**Comment by aknuds1** [comment] 2020-08-14 16:07
I have a [fix](https://github.com/grafana/grafana/pull/27012) now, that AFAICT stops the connection leakage. At least with this fix, I don't see any more increase in the number of connections, two at the most.

**Closed** 2020-08-14 16:40 UTC
Labels: area/backend, datasource/InfluxDB, needs investigation

**Comment by aknuds1** [comment] 2020-08-14 17:24
@coussej Please try [this snapshot](https://grafana.com/grafana/download/7.2.0-fa766158pre) build. I think it should resolve your issue.

**Comment by coussej** [comment] 2020-08-15 20:04
That seems to work! Great! Thanks @aknuds1 .

Correct me if I'm wrong, but unrelated to grafana, the issue I created in the flux repo is still relevant right?

**Comment by aknuds1** [comment] 2020-08-16 09:16
I already answered in your InfluxDB Go client issue, that I don't think it's a bug there after all. My fix for this issue seems to have resolved it, so unless I'm mistaken it was just about re-using HTTP connections.
