### ISSUE TITLE
Alerting : Attach images to emails when not using webdav/s3

### ISSUE THREAD

**Issue by Fox32** [grafana/grafana#6183] opened 2016-10-04 13:03 UTC
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Grafana v4.0.0-pre1 (commit: d726f49)
- What datasource are you using? Graphite
- What OS are you running grafana on? Docker
- What did you do? Alert is triggered
- What was the expected result? EMail is send, either with graph image embedded (e.g. data: url), linked to the grafana instance, or no image.
- What happened instead? No email is send

Log Message:
```
grafana_1          | t=2016-10-04T12:56:00+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=1 newState=ok oldState=alerting
grafana_1          | t=2016-10-04T12:56:00+0000 lvl=info msg="Sending notifications for" logger=alerting.notifier ruleId=1
grafana_1          | t=2016-10-04T12:56:00+0000 lvl=eror msg="Failed to upload alert panel image" logger=alerting.notifier error="could not find specified provider"
```

I specified the ```provider = internal``` provider that is mentioned in the config file but not[ implemented yet](https://github.com/grafana/grafana/blob/0d083bad14382064ecdde7a78eeb8d84c6a523df/pkg/components/imguploader/imguploader.go).

**Comment by torkelo** [comment] 2016-10-04 13:32
1) think better handling for default case (no image store provider)
2) investigate attaching the image in the email

**Comment by djordjeandrejevic** [comment] 2016-10-04 15:14
Yeah, I had that error too, ended up using S3.

**Comment by bergquist** [comment] 2016-10-05 05:42
That commit improves the error message. I will look into attaching emails later.

**Comment by Fox32** [comment] 2016-10-05 12:13
The nop uploader is perfect for now, thanks!

**Comment by bergquist** [comment] 2016-10-05 18:15
Moving this from 4.0 beta to 4.0 since the error have been remove.

**Comment by discoduck2x** [comment] 2016-10-17 21:09
@bergquist but is it solved in current nightly? (seems not)

**Comment by torkelo** [comment] 2016-10-18 04:30
The issue is still open, he was referring to the error you got when not having an image store provider

**Closed** 2016-10-21 07:10 UTC
Labels: comp: alerting

**Comment by IamAliBaba** [comment] 2018-02-20 06:15
hi,
Any updates?
