### ISSUE TITLE
Tooltip bug: value transition inside bar

### ISSUE THREAD

**Issue by svenito92** [grafana/grafana#22611] opened 2020-03-06 06:37 UTC
**What happened**:
When using bars, tooltip displays value of previous data point when hovering over left half of a bar and displays correct value, when hovering over right half of bar.

**What you expected to happen**:
Tooltip shows value of current data point regardless where I hover over the bar. Transitions of value ("previous <-> current" and "current <-> next") should happen between bars.

**How to reproduce it (as minimally and precisely as possible)**:
- Create new Graph panel (we can use the default random generated data)
- Change draw mode to bar only
- Zoom in (several times) until you can comfortable move your cursor left and right inside a bar
- Move cursor slowly from left border of the bar to the right. Ovserve the tooltip value change when crossing the mid of the bar

**Anything else we need to know?**:
This also happens, when plotting wider bars (e.g. group by 1 day) so I don't think it has anything to to with the zoom level of above example...

**Environment**:
- Grafana version: Grafana v6.6.2 (3fa63cfc34)
- Data source type & version: Default random data (also tried on MS-SQL data)
- OS Grafana is installed on: Official grafana container on ubuntu (inside VM)
- User OS & Browser: Windows 10 & Firefox 72.0.2 (64-bit)
- Grafana plugins: Graph

- Others:

![image](https://user-images.githubusercontent.com/61381861/76058242-1e783800-5f7c-11ea-909b-39736443981d.png)

![image](https://user-images.githubusercontent.com/61381861/76058269-351e8f00-5f7c-11ea-8f5a-2462d94388a4.png)

**Comment by torkelo** [comment] 2020-03-09 09:26
Unable to replicate this, can you enable points (a the same time as bars) so I can see where the points are.

**Comment by Eraac** [comment] 2020-03-09 10:45
I've the same issue, if you look the first screenshot, value is `~6.2` and the second one (the mouse is on the **same** bar) value is `~5.9`

Because in the first one, tooltip use the previous bar, that a non sense

**Comment by svenito92** [comment] 2020-03-10 08:53
Hi @torkelo 
I did as you asked. I could reproduce the issue as i described above by creating a random graph panel and zooming.

As you can see, the point is in the middle of the bar. The value and the timestamp of the tooltip varies between the left and the right half.

![Capture1](https://user-images.githubusercontent.com/61381861/76295120-551fbc80-62b4-11ea-8b7f-42ade7c761c7.PNG)

![Capture123](https://user-images.githubusercontent.com/61381861/76295133-59e47080-62b4-11ea-8e2a-0fa308980cb2.PNG)

**Comment by torkelo** [comment] 2020-06-11 06:54
Think this is bug in the "all series" mode of the graph tooltip, not sure how easy it would be to fix, but worth a try

**Comment by gengel** [comment] 2020-07-23 05:06
This would be great to get fixed.

**Comment by jrgilman** [comment] 2020-07-23 17:59
@gengel I was really hoping this would get fixed in 7.1 but it looks like it was pushed off to 7.2... It's hard to explain this bug to less tech inclined people using the dashboard.

**Closed** 2020-08-10 08:59 UTC
Labels: area/panel/graph, effort/medium, type/bug

**Comment by jrgilman** [comment] 2020-08-20 20:27
@torkelo just updated to Grafana 7.1.4 and the issue is still happening?

![Peek 2020-08-20 15-26](https://user-images.githubusercontent.com/6265723/90822167-a61eec80-e2f9-11ea-8c2f-58735046c247.gif)

**Comment by torkelo** [comment] 2020-08-21 04:31
Show points i graph settings , maybe data points are not aligned ?

**Comment by jrgilman** [comment] 2020-08-21 07:25
![Screenshot from 2020-08-21 02-23-26](https://user-images.githubusercontent.com/6265723/90863946-7271b000-e355-11ea-92d2-873673097370.png)

`{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1595402617218",
      "to": "1597994617219",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 1800000,
          "maxDataPoints": 1322,
          "datasourceId": 1,
          "rawSql": "WITH ALL_DEPARTMENTS_ALL_DATES AS (\n    SELECT *\n    FROM departments d\n    CROSS JOIN calendar c\n    WHERE d.name != 'Not Used'\n      AND d.id IN ('8','14','12','13','4','6','7','10','9','3','15','1','11','5','2')\n      AND d.unit_of_measure = 'KG'\n      AND c.date <= NOW()\n),\n\nPROCESS_ORDERS_DURING_PERIOD AS (\n    SELECT *\n    FROM sap_process_orders\n    WHERE deleted_at IS NULL\n),\n\nPROCESS_ORDERS_ADDED_TO_DEPARTMENTS AS (\n    SELECT d.date as date,\n           d.id AS department_id,\n           d.name AS department_name,\n           IFNULL(SUM(requested_quantity) - SUM(expected_deficit), 0) AS total_expected\n    FROM ALL_DEPARTMENTS_ALL_DATES d\n    LEFT JOIN PROCESS_ORDERS_DURING_PERIOD po on po.department_id = d.id\n                                             and po.sap_date_created = d.date\n    GROUP BY d.id,\n             d.date\n),\n\nCUMULATIVE_EXPECTED AS (\n    SELECT *,\n           SUM(total_expected) OVER (PARTITION BY department_id ORDER BY date) AS cumulative_expected\n    FROM PROCESS_ORDERS_ADDED_TO_DEPARTMENTS\n),\n\nPRODUCED_ON_DATE AS (\n    SELECT d.date,\n           d.id AS department_id,\n           IFNULL(SUM(spd.amount_produced), 0) AS total_produced\n    FROM sap_production_data spd\n    INNER JOIN PROCESS_ORDERS_DURING_PERIOD spo ON spd.process_order_id = spo.id\n    RIGHT JOIN ALL_DEPARTMENTS_ALL_DATES d ON spd.confirmation_entry_date = d.date\n                                          AND spo.department_id = d.id\n    GROUP BY d.id,\n             d.date\n),\n\nCUMULATIVE_PRODUCED AS (\n    SELECT p.date,\n           p.department_id,\n           p.total_produced,\n           SUM(total_produced) OVER (PARTITION BY department_id ORDER BY date) AS cumulative_produced\n    FROM PRODUCED_ON_DATE p\n)\n\nSELECT ce.date as time,\n       ce.department_name as metric,\n       -1 * (ce.cumulative_expected - cp.cumulative_produced) as value\nFROM CUMULATIVE_EXPECTED ce\nLEFT JOIN CUMULATIVE_PRODUCED cp ON ce.date = cp.date\n                                AND ce.department_id = cp.department_id\nWHERE $__timeFilter(ce.date);",
          "format": "time_series"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "executedQueryString": "WITH ALL_DEPARTMENTS_ALL_DATES AS (\n    SELECT *\n    FROM departments d\n    CROSS JOIN calendar c\n    WHERE d.name != 'Not Used'\n      AND d.id IN ('8','14','12','13','4','6','7','10','9','3','15','1','11','5','2')\n      AND d.unit_of_measure = 'KG'\n      AND c.date <= NOW()\n),\n\nPROCESS_ORDERS_DURING_PERIOD AS (\n    SELECT *\n    FROM sap_process_orders\n    WHERE deleted_at IS NULL\n),\n\nPROCESS_ORDERS_ADDED_TO_DEPARTMENTS AS (\n    SELECT d.date as date,\n           d.id AS department_id,\n           d.name AS department_name,\n           IFNULL(SUM(requested_quantity) - SUM(expected_deficit), 0) AS total_expected\n    FROM ALL_DEPARTMENTS_ALL_DATES d\n    LEFT JOIN PROCESS_ORDERS_DURING_PERIOD po on po.department_id = d.id\n                                             and po.sap_date_created = d.date\n    GROUP BY d.id,\n             d.date\n),\n\nCUMULATIVE_EXPECTED AS (\n    SELECT *,\n           SUM(total_expected) OVER (PARTITION BY department_id ORDER BY date) AS cumulative_expected\n    FROM PROCESS_ORDERS_ADDED_TO_DEPARTMENTS\n),\n\nPRODUCED_ON_DATE AS (\n    SELECT d.date,\n           d.id AS department_id,\n           IFNULL(SUM(spd.amount_produced), 0) AS total_produced\n    FROM sap_production_data spd\n    INNER JOIN PROCESS_ORDERS_DURING_PERIOD spo ON spd.process_order_id = spo.id\n    RIGHT JOIN ALL_DEPARTMENTS_ALL_DATES d ON spd.confirmation_entry_date = d.date\n                                          AND spo.department_id = d.id\n    GROUP BY d.id,\n             d.date\n),\n\nCUMULATIVE_PRODUCED AS (\n    SELECT p.date,\n           p.department_id,\n           p.total_produced,\n           SUM(total_produced) OVER (PARTITION BY department_id ORDER BY date) AS cumulative_produced\n    FROM PRODUCED_ON_DATE p\n)\n\nSELECT ce.date as time,\n       ce.department_name as metric,\n       -1 * (ce.cumulative_expected - cp.cumulative_produced) as value\nFROM CUMULATIVE_EXPECTED ce\nLEFT JOIN CUMULATIVE_PRODUCED cp ON ce.date = cp.date\n                                AND ce.department_id = cp.department_id\nWHERE ce.date BETWEEN FROM_UNIXTIME(1595402617) AND FROM_UNIXTIME(1597994617);",
          "rowCount": 0
        },
        "series": [
          {
            "name": "Make",
            "points": [
              [
                -49463.1,
                1595462400000
              ],
              [
                -50114.1,
                1595548800000
              ],
              [
                -50114.1,
                1595635200000
              ],
              [
                -50114.1,
                1595721600000
              ],
              [
                -51038.6,
                1595808000000
              ],
              [
                -61011.1,
                1595894400000
              ],
              [
                -61249.05,
                1595980800000
              ],
              [
                -68632.05,
                1596067200000
              ],
              [
                -64404.05,
                1596153600000
              ],
              [
                -64404.05,
                1596240000000
              ],
              [
                -64404.05,
                1596326400000
              ],
              [
                -59389.55,
                1596412800000
              ],
              [
                -75344.05,
                1596499200000
              ],
              [
                -72407.05,
                1596585600000
              ],
              [
                -72201,
                1596672000000
              ],
              [
                -72201,
                1596758400000
              ],
              [
                -72201,
                1596844800000
              ],
              [
                -72201,
                1596931200000
              ],
              [
                -73986.5,
                1597017600000
              ],
              [
                -69266,
                1597104000000
              ],
              [
                -61181,
                1597190400000
              ],
              [
                -66941,
                1597276800000
              ],
              [
                -70941,
                1597363200000
              ],
              [
                -70941,
                1597449600000
              ],
              [
                -70941,
                1597536000000
              ],
              [
                -70646.5,
                1597622400000
              ],
              [
                -66080.5,
                1597708800000
              ],
              [
                -64570,
                1597795200000
              ],
              [
                -62438,
                1597881600000
              ],
              [
                -62438,
                1597968000000
              ]
            ]
          },
          {
            "name": "Grind",
            "points": [
              [
                -3617.537,
                1595462400000
              ],
              [
                -3617.537,
                1595548800000
              ],
              [
                -3617.537,
                1595635200000
              ],
              [
                -3617.537,
                1595721600000
              ],
              [
                -2189.037,
                1595808000000
              ],
              [
                -8558.537,
                1595894400000
              ],
              [
                -22650.537,
                1595980800000
              ],
              [
                -16595.537,
                1596067200000
              ],
              [
                -16595.537,
                1596153600000
              ],
              [
                -16595.537,
                1596240000000
              ],
              [
                -16595.537,
                1596326400000
              ],
              [
                -13498.537,
                1596412800000
              ],
              [
                -11744.537,
                1596499200000
              ],
              [
                -24274.537,
                1596585600000
              ],
              [
                -14989.537,
                1596672000000
              ],
              [
                -12024.537,
                1596758400000
              ],
              [
                -12024.537,
                1596844800000
              ],
              [
                -12024.537,
                1596931200000
              ],
              [
                -12095.037,
                1597017600000
              ],
              [
                -7422.037,
                1597104000000
              ],
              [
                -12509.037,
                1597190400000
              ],
              [
                -7530.537,
                1597276800000
              ],
              [
                -7530.537,
                1597363200000
              ],
              [
                -7530.537,
                1597449600000
              ],
              [
                -7530.537,
                1597536000000
              ],
              [
                -12925.537,
                1597622400000
              ],
              [
                -11521.537,
                1597708800000
              ],
              [
                -12759.537,
                1597795200000
              ],
              [
                -9202.537,
                1597881600000
              ],
              [
                -9202.537,
                1597968000000
              ]
            ]
          },
          {
            "name": "Pre-Weigh",
            "points": [
              [
                -3970.996,
                1595462400000
              ],
              [
                -3970.996,
                1595548800000
              ],
              [
                -3970.996,
                1595635200000
              ],
              [
                -3970.996,
                1595721600000
              ],
              [
                -4267.452,
                1595808000000
              ],
              [
                -8049.69,
                1595894400000
              ],
              [
                -6950.126,
                1595980800000
              ],
              [
                -4391.758,
                1596067200000
              ],
              [
                -5915.758,
                1596153600000
              ],
              [
                -5915.758,
                1596240000000
              ],
              [
                -5915.758,
                1596326400000
              ],
              [
                -5027.34,
                1596412800000
              ],
              [
                -6344.134,
                1596499200000
              ],
              [
                -8734.646,
                1596585600000
              ],
              [
                -6808.134,
                1596672000000
              ],
              [
                -6808.134,
                1596758400000
              ],
              [
                -6808.134,
                1596844800000
              ],
              [
                -6808.134,
                1596931200000
              ],
              [
                -9602.54,
                1597017600000
              ],
              [
                -7771.742,
                1597104000000
              ],
              [
                -8652.336,
                1597190400000
              ],
              [
                -6429.244,
                1597276800000
              ],
              [
                -6429.244,
                1597363200000
              ],
              [
                -6429.244,
                1597449600000
              ],
              [
                -6429.244,
                1597536000000
              ],
              [
                -4658.577,
                1597622400000
              ],
              [
                -3886.522,
                1597708800000
              ],
              [
                -2885.712,
                1597795200000
              ],
              [
                -2458.555,
                1597881600000
              ],
              [
                -2458.555,
                1597968000000
              ]
            ]
          },
          {
            "name": "Liquid Bulk",
            "points": [
              [
                -31811.5,
                1595462400000
              ],
              [
                -29811.5,
                1595548800000
              ],
              [
                -29811.5,
                1595635200000
              ],
              [
                -29811.5,
                1595721600000
              ],
              [
                -30811.5,
                1595808000000
              ],
              [
                -26855,
                1595894400000
              ],
              [
                -25630,
                1595980800000
              ],
              [
                -27830,
                1596067200000
              ],
              [
                -27830,
                1596153600000
              ],
              [
                -27830,
                1596240000000
              ],
              [
                -27830,
                1596326400000
              ],
              [
                -27630,
                1596412800000
              ],
              [
                -39330,
                1596499200000
              ],
              [
                -43330,
                1596585600000
              ],
              [
                -44330,
                1596672000000
              ],
              [
                -44330,
                1596758400000
              ],
              [
                -44330,
                1596844800000
              ],
              [
                -44330,
                1596931200000
              ],
              [
                -44270,
                1597017600000
              ],
              [
                -42176,
                1597104000000
              ],
              [
                -41776,
                1597190400000
              ],
              [
                -40776,
                1597276800000
              ],
              [
                -40776,
                1597363200000
              ],
              [
                -40776,
                1597449600000
              ],
              [
                -40776,
                1597536000000
              ],
              [
                -41242,
                1597622400000
              ],
              [
                -41605.5,
                1597708800000
              ],
              [
                -40425.5,
                1597795200000
              ],
              [
                -47629,
                1597881600000
              ],
              [
                -47629,
                1597968000000
              ]
            ]
          },
          {
            "name": "Magic Shave Make",
            "points": [
              [
                -12564,
                1595462400000
              ],
              [
                -15830,
                1595548800000
              ],
              [
                -15830,
                1595635200000
              ],
              [
                -15830,
                1595721600000
              ],
              [
                -10931,
                1595808000000
              ],
              [
                -6032,
                1595894400000
              ],
              [
                -6032,
                1595980800000
              ],
              [
                -6032,
                1596067200000
              ],
              [
                -6032,
                1596153600000
              ],
              [
                -6032,
                1596240000000
              ],
              [
                -6032,
                1596326400000
              ],
              [
                -6032,
                1596412800000
              ],
              [
                -6032,
                1596499200000
              ],
              [
                -6032,
                1596585600000
              ],
              [
                -3323,
                1596672000000
              ],
              [
                -3323,
                1596758400000
              ],
              [
                -3323,
                1596844800000
              ],
              [
                -3323,
                1596931200000
              ],
              [
                -29638,
                1597017600000
              ],
              [
                -31271,
                1597104000000
              ],
              [
                -31271,
                1597190400000
              ],
              [
                -26334,
                1597276800000
              ],
              [
                -26334,
                1597363200000
              ],
              [
                -26334,
                1597449600000
              ],
              [
                -26334,
                1597536000000
              ],
              [
                -20304,
                1597622400000
              ],
              [
                -15369,
                1597708800000
              ],
              [
                -8784,
                1597795200000
              ],
              [
                -26723,
                1597881600000
              ],
              [
                -26723,
                1597968000000
              ]
            ]
          }
        ],
        "tables": null,
        "dataframes": null
      }
    }
  }
}`

**Comment by torkelo** [comment] 2020-08-24 11:32
was not cherry picked for 7.1.4, adding to 7.1.5
