### ISSUE TITLE
When the prometheus label is variable expanded in Data links, the double-byte character It's not expanding.

### ISSUE THREAD

**Issue by buchixx** [grafana/grafana#25999] opened 2020-07-02 01:54 UTC
**What happened**:
 When using Data links in the Stat panel, the double-byte characterLabels are not expanded to URLs.

**How to reproduce it (as minimally and precisely as possible)**:
 Create a double-byte label in prometheus and use it in __field.labels Do.

Prometheus Labels
carrier=“ntt”
code=“999”
grp=“グループ1”
instance=“192.168.1.1”
job=“pinger”
name=“あああああ”

Grafana Stat Panel
My Prometheus label field
﻿${__field.labels.carrier}  <- ok
${__field.labels.code}     <- ok
﻿${__field.labels.grp}      <- not expanded
﻿${__field.labels.instance} <- ok
${__field.labels.job}      <- ok
﻿${__field.labels.name}     <- not expanded

**Environment**:
- Grafana version: 7.0 - 7.0.4
- Data source type & version: prometheus 2.19.1
- OS Grafana is installed on: CentOS 8
- User OS & Browser: Windows & Firefox & Chrome
- Grafana plugins: Stats
- Others:

**Comment by ivanahuckova** [comment] 2020-07-02 14:47
@aocenas fyi

**Comment by aocenas** [comment] 2020-07-02 14:49
@dprokop I think we have more issues like this with double byte chars, did anybody looked into it yet?

**Comment by ivanahuckova** [comment] 2021-11-25 09:20
I am wondering if this is duplicate of https://github.com/grafana/grafana/issues/22125. Could you please try this `${__field.labels.name:percentencode}`?

**Comment by Elfo404** [comment] 2021-12-16 12:48
Closing this as no new information was provided in order to address the issue. Please feel free to comment with the requested info and we can reopen it :)

**Closed by Elfo404** 2021-12-16 12:48 UTC
Labels: needs more info, datasource/Prometheus
