### ISSUE TITLE
Refresh Picker in Explore

### ISSUE THREAD

**Issue by jschill** [grafana/grafana#16247] opened 2019-03-27 10:02 UTC
**What would you like to be added**:
Refresh picker in Explore

**Why is this needed**:
It should be possible to create queries in Explore and have custom refresh intervals on those.

I'm breaking this issue out of #15343

**Comment by davkal** [comment] 2019-04-01 09:36
Duplicate of #15192

**Closed by davkal** 2019-04-01 09:36 UTC
Labels: area/explore, area/frontend, type/feature-request
