### ISSUE TITLE
yarn start:hot error

### ISSUE THREAD

**Issue by Hsinin** [grafana/grafana#49051] opened 2022-05-17 05:45 UTC
**What happened**:
"yarn start" is normal
"yarn start:hot" trigger an error:
`SASS variable files generated
Compiling message catalogs…
Done!
<w> [ReactRefreshPlugin] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.
......
webpack 5.70.0 compiled successfully in 28302 ms
......
runtime modules 20.2 KiB 27 modules
orphan modules 580 KiB [orphan] 10 modules
modules by path ./.yarn/unplugged/core-js-pure-npm-3.19.0-b23c7269f4/node_modules/core-js-pure/ 114 KiB 106 modules
modules by path ./.yarn/__virtual__/ 43.2 KiB (javascript) 17.4 KiB (css/mini-extract)
  javascript modules 43.2 KiB 22 modules
  css modules 17.4 KiB 5 modules
modules by path ./.yarn/cache/ 121 KiB (javascript) 2.09 KiB (css/mini-extract)
  modules by path ./.yarn/cache/html-entities-npm-2.3.2-366c4c257a-522d8d202d.zip/node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
  modules by path ./.yarn/cache/react-refresh-npm-0.11.0-c0a4e59e76-112178a05b.zip/node_modules/react-refresh/ 21.8 KiB 2 modules
  + 4 modules
modules by path ./public/ 139 bytes (javascript) 509 KiB (css/mini-extract)
  javascript modules 139 bytes 3 modules
  css modules 509 KiB 2 modules
.......
ERROR in ./public/app/index.ts
Module build failed (from ./.yarn/__virtual__/babel-loader-virtual-d962a1946f/0/cache/babel-loader-npm-8.2.4-e2dfcd123f-4968251fc4.zip/node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/xxx/gitlab/grafana/public/app/index.ts: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "hot". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "/Users/xxx/gitlab/grafana/.yarn/cache/react-refresh-npm-0.11.0-c0a4e59e76-112178a05b.zip/node_modules/react-refresh/babel.js")
    at ReactFreshBabelPlugin (/Users/xxx/gitlab/grafana/.yarn/cache/react-refresh-npm-0.11.0-c0a4e59e76-112178a05b.zip/node_modules/react-refresh/cjs/react-refresh-babel.development.js:24:13)
    at async (/Users/xxx/gitlab/grafana/.yarn/cache/@babel-core-npm-7.17.8-dc1954857c-0e686b1be4.zip/node_modules/@babel/core/lib/gensync-utils/async.js:44:33)
    at async (/Users/xxx/gitlab/grafana/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:186:15)
    at /Users/xxx/gitlab/grafana/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:216:13
    at Generator.next (<anonymous>)
    at /Users/xxx/gitlab/grafana/.yarn/cache/@babel-core-npm-7.17.8-dc1954857c-0e686b1be4.zip/node_modules/@babel/core/lib/config/full.js:229:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/xxx/gitlab/grafana/.yarn/cache/@babel-core-npm-7.17.8-dc1954857c-0e686b1be4.zip/node_modules/@babel/core/lib/gensync-utils/async.js:25:3)
    at Generator.next (<anonymous>)
    at step (/Users/xxx/gitlab/grafana/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:269:25)`

**Environment**:
- Grafana version: 8.5.2
- node v16.15.0
- yarn 3.2.0
- custom.ini
`app_mode = development
[database]
type = mysql
host = 127.0.0.1:3306
name = grafana
user = root
password = root
url =mysql://root:root@localhost:3306/grafana`

**Comment by Hsinin** [comment] 2022-05-17 06:01
I am confused, what's the problem?

**Comment by zuchka** [comment] 2022-05-17 22:01
sounds like a duplicate of this https://github.com/grafana/grafana/issues/18025

**Comment by zuchka** [comment] 2022-05-17 22:01
I'd hop on that thread instead

**Closed by zuchka** 2022-05-17 22:01 UTC

**Comment by 100apps** [comment] 2022-09-18 14:34
I have the same issue：
```

ERROR in ./public/app/index.ts
Module build failed (from ./.yarn/__virtual__/babel-loader-virtual-6cb66b614a/0/cache/babel-loader-npm-8.2.5-e749e26bb5-a660555788.zip/node_modules/babel-loader/lib/index.js):
Error: [BABEL] /System/Volumes/Data/data/github/grafana/public/app/index.ts: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "hot". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "/System/Volumes/Data/data/github/grafana/.yarn/cache/react-refresh-npm-0.14.0-78ef5eeb73-dc69fa8c99.zip/node_modules/react-refresh/babel.js")
    at ReactFreshBabelPlugin (/System/Volumes/Data/data/github/grafana/.yarn/cache/react-refresh-npm-0.14.0-78ef5eeb73-dc69fa8c99.zip/node_modules/react-refresh/cjs/react-refresh-babel.development.js:25:13)
    at async (/System/Volumes/Data/data/github/grafana/.yarn/cache/@babel-core-npm-7.19.0-50eaedd5da-0d5b52b552.zip/node_modules/@babel/core/lib/gensync-utils/async.js:46:33)
    at async (/System/Volumes/Data/data/github/grafana/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:186:15)
    at /System/Volumes/Data/data/github/grafana/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:216:13
    at Generator.next (<anonymous>)
    at /System/Volumes/Data/data/github/grafana/.yarn/cache/@babel-core-npm-7.19.0-50eaedd5da-0d5b52b552.zip/node_modules/@babel/core/lib/config/full.js:231:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/System/Volumes/Data/data/github/grafana/.yarn/cache/@babel-core-npm-7.19.0-50eaedd5da-0d5b52b552.zip/node_modules/@babel/core/lib/gensync-utils/async.js:27:3)
    at Generator.next (<anonymous>)
    at step (/System/Volumes/Data/data/github/grafana/.yarn/cache/gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip/node_modules/gensync/index.js:269:25)
```
