### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#18487] opened 2019-08-09 13:38 UTC
Grafana v6.4.0-pre (445f1da)

Loaded explore, got this:

<img width="1388" alt="Screenshot 2019-08-09 at 14 37 39" src="https://user-images.githubusercontent.com/444037/62783002-5c2ee400-bab3-11e9-88dd-ff2c1f9f69a0.png">

**Comment by marefr** [comment] 2019-08-12 09:17
Duplicate of #18436

**Comment by tomwilkie** [comment] 2019-08-19 12:09
Mistakenly deduped.

I'm still seeing this in 6.3.3 quite often, although getting a solid reproduction is tricky.

**Comment by davkal** [comment] 2019-08-19 12:22
Spoken to @kaydelaney about making QueryField more robust wrt inputs.
That component should not take down the whole UI.

**Comment by kaydelaney** [comment] 2019-08-20 09:09
@tomwilkie Trying to look into this but still no luck reproducing the issue. Does it tend to occur when loading explore from a new tab, or when navigating to explore from an already loaded Grafana, or something else? Just trying to narrow things down a bit

**Comment by torkelo** [comment] 2019-08-29 11:14
fixed by https://github.com/grafana/grafana/issues/18487

**Closed by torkelo** 2019-08-29 11:14 UTC
Labels: area/explore, type/bug
