### ISSUE TITLE
Cannot build 8.4.0

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#45600] opened 2022-02-18 12:01 UTC
**What happened**: 
Got error on `yarn start` during the build `release-8.4.0`
![err](https://user-images.githubusercontent.com/43705385/154679202-6f486d32-2d8a-43e3-949f-df0e64855eaf.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.4.0
- OS Grafana is installed on: Ubuntu 20.04.03 LTS

**Comment by DmitrySidorow** [comment] 2022-02-18 17:30
8.4.1 same problem. But 8.3.3 is okay

**Comment by jackw** [comment] 2022-02-21 14:10
Can reproduce on Mac OSX. Looks to be an issue with `fork-ts-checker-webpack-plugin@6.5.0`. Downgrading to `fork-ts-checker-webpack-plugin@6.4.0` solves it. I cannot reproduce on main most likely as it's using `fork-ts-checker-webpack-plugin@7.2.0`.

@DmitrySidorow I'm likely missing something here but could you explain your use case for running `yarn start` where it looks like a release is happening? (I'm assuming so anyway given the mention of `release-8.4.0`.) For a release we run `yarn build` with a production Webpack config which doesn't include `fork-ts-checker`.

**Comment by DmitrySidorow** [comment] 2022-02-21 17:12
> Can reproduce on Mac OSX. Looks to be an issue with `fork-ts-checker-webpack-plugin@6.5.0`. Downgrading to `fork-ts-checker-webpack-plugin@6.4.0` solves it. I cannot reproduce on main most likely as it's using `fork-ts-checker-webpack-plugin@7.2.0`.
> 
> @DmitrySidorow I'm likely missing something here but could you explain your use case for running `yarn start` where it looks like a release is happening? (I'm assuming so anyway given the mention of `release-8.4.0`.) For a release we run `yarn build` with a production Webpack config which doesn't include `fork-ts-checker`.

`yarn build`- works. But in the developer guide it is proposed to use `yarn start`

**Comment by twei55** [comment] 2022-02-22 20:14
@DmitrySidorow You can also bypass the TS check with `yarn start --env noTsCheck=1`.

**Comment by jackw** [comment] 2022-03-24 08:27
Now #46836 is merged into the version branch I believe we can close this issue.

**Closed by jackw** 2022-03-24 08:27 UTC
Labels: type/build-packaging, area/frontend
