### ISSUE TITLE
High latency from datasource requests when using PostgreSQL (DBaaS), Oauth and “Forward OAuth Identity"

### ISSUE THREAD

**Issue by hgranlund** [grafana/grafana#20079] opened 2019-10-29 14:15 UTC
**What happened**:
We experience a latency from 300ms to 1,5s when doing multiple datasource requests. 

One requests usually goes through quickly, but when we do multiple requests the latency increases. From two requests and upwards the latency is between 450ms to over a second. 

**What you expected to happen**:

Latency should not be this high. I would expect a latency < 150 ms. 

**How to reproduce it (as minimally and precisely as possible)**:

Set up Grafana with:
- Server protocol = h2
- A postgres DBaaS instance, or any PostgreSQL database with some network latency. Ours has ~5ms. 
- A generic oauth provider
- A datasource with “Forward OAuth Identity” enabled.

Create a dashboard that do multiple requests to the datasource, and you will see that the latency increases with number of requests. 

**Anything else we need to know**:

Screenshot from chrome:

![image](https://user-images.githubusercontent.com/1315128/67774605-f58be780-fa5d-11e9-8c09-59b2f15a1da6.png)

Grafana logs:

[grafana.log](https://github.com/grafana/grafana/files/3783928/grafana.log)

**Environment**:
Grafana version: 6.4.2  (docker-image: grafana/grafana:6.4.2)
PostgreSQL version 11. (a free [DBaaS](https://www.elephantsql.com/) alternative)

**Comment by marefr** [comment] 2019-11-11 08:21
Please enable [router_logging](https://grafana.com/docs/installation/configuration/#router-logging) and provide a new Grafana server log so that each request including timing information is included.

1. How many rows do you have in `user_auth` table in database?
1. Have you tried using HTTP instead of HTTP2? Can you do that?

**Comment by hgranlund** [comment] 2019-11-12 14:36
Is not router_logging already enabled inn the log i provided? Anyways, i am providing new logs with [dataproxy_logging](https://grafana.com/docs/installation/configuration/#logging) and [router_logging](https://grafana.com/docs/installation/configuration/#router-logging) enabled.

1. How many rows do you have in user_auth table in database?
There is 88 rows in the user_auth table.

2. Have you tried using HTTP instead of HTTP2? Can you do that?

I ran the same senario with http and http2.

Results with http: 
![grafanTimings_HTTP](https://user-images.githubusercontent.com/1315128/68680328-c4cda700-0561-11ea-96bd-1aa47aaf5923.PNG)
[grafana_log_http.log](https://github.com/grafana/grafana/files/3836601/grafana_log_http.log)

Results with http2:
![grafanTimings_H2](https://user-images.githubusercontent.com/1315128/68680347-d020d280-0561-11ea-8829-504da9d783b7.PNG)
[grafana_log_h2.log](https://github.com/grafana/grafana/files/3836602/grafana_log_h2.log)

**Comment by torkelo** [comment] 2019-12-02 22:08
how long does the requests take to the datasource? (the query?) any oauth requests?

**Comment by hgranlund** [comment] 2019-12-03 09:03
In this case the datasource query goes directly to a cached value, so we normally see requests with network latency between 5 to 10ms. 

We use “Forward OAuth Identity”, so the token-refresh-request should only happend every 10 minutes (token_rotation_interval_minutes = 10).
The timings are consistent on every page refresh, so the oauth requests should not have a huge impact.

**Comment by marefr** [comment] 2019-12-03 10:37
Maybe related to #20579. Can you please try Grafana 6.4.5 and tell us if the problem remains.

Possibly related to #20515.

**Comment by hgranlund** [comment] 2019-12-04 12:30
I tried out Grafana 6.4.5, but did not see a huge difference in performance. 

My theory is that the latency is caused by all the queries to the PostgreSQL database. Especially the update query, which causes the PostgreSQL processes to wait for locks. In other words, if #20515 moved the update query to a background process, then we could see a huge improvement in performance

**Comment by marefr** [comment] 2019-12-05 12:40
Duplicate of #20515

**Comment by marefr** [comment] 2019-12-05 12:41
Closing this in favor of #20515. Please continue the discussion, if any there.

**Closed by marefr** 2019-12-05 12:41 UTC
Labels: needs more detail
