### ISSUE TITLE
Playlist Remove Button Not Exist

### ISSUE THREAD

**Issue by dr-abadis** [grafana/grafana#39511] opened 2021-09-22 10:25 UTC
Playlist Remove Button Not Exist in version 8.1.2 while I logged in as admin.
![Capture](https://user-images.githubusercontent.com/4403666/134327577-9d7712e5-b5a6-4b5e-9ffa-3b9e5e00d2a9.PNG)

![Capture](https://user-images.githubusercontent.com/4403666/134327339-860c3239-0b62-474b-9335-84b7283f70ed.PNG)
![Capture](https://user-images.githubusercontent.com/4403666/134327700-1643f14b-b16a-4585-8b8b-88216a85a2cd.PNG)

**Comment by zuchka** [comment] 2021-09-22 20:44
Hi @dr-abadis thank you form asking this issue. This bug was reported and already fixed. Please try upgrading and report back if the issue continues. thanks!

duplicate of https://github.com/grafana/grafana/issues/37284

**Closed by zuchka** 2021-09-22 20:44 UTC
