### ISSUE TITLE
Renderer image but not add to Slack

### ISSUE THREAD

**Issue by nscpro** [grafana/grafana#21275] opened 2019-12-28 17:43 UTC
[https://www.icloud.com/sharedalbum/#B0xGtnIORyGPdw](https://www.icloud.com/sharedalbum/#B0xGtnIORyGPdw)

Log file show everything is okay, but if alert coming and send notification to slack, not show image

**Comment by hugohaggmark** [comment] 2019-12-30 05:22
Hi @nscpro  in order for us to investigate this further it would be great if you could supply the following:
**Environment:**

Grafana version:
Data source type & version: 
OS Grafana is installed on: 
User OS & Browser: 
Grafana plugins:
Others:

**Comment by marefr** [comment] 2020-01-13 12:49
Duplicate of #21018

**Closed by marefr** 2020-01-13 12:49 UTC
Labels: needs more detail
