### ISSUE TITLE
Add possibility to acknowledge alert

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#24762] opened 2020-05-16 07:54 UTC
**What would you like to be added**:
When a panel goes into the alerting state, one should be able to acknowlegde the alert, meaning that repeat notifications for that alert as disabled until the next state change, or for a certain period of time (ie. acknowledge for 6 hours, then send notification again.)

**Why is this needed**:
Sometime, an alert is triggered, and after investigation the cause is identified but it can't be fixed immediately. If notification repeats are configured, this causes many 'useless' notifications between cause identification and fix, causing notification fatigue :-)

**Comment by torkelo** [comment] 2020-05-18 07:46
duplicate of https://github.com/grafana/grafana/issues/18193

**Closed by torkelo** 2020-05-18 07:46 UTC
