### ISSUE TITLE
Alerts created via import API not working properly

### ISSUE THREAD

**Issue by Svonn** [grafana/grafana#19159] opened 2019-09-17 08:49 UTC
**What happened**:
I'm creating dashboards via the dashboard import API  (Endpoint /api/dashboards/import). The dashboards show up, show the data, show the thresholds - however, the alerts show a white heart. When querying on /api/alerts/, the alert does not show up at all.
If I make the dashboard editable, click on edit and testfire the alert, the alert will turn green shortly after and also show up when querying on /api/alerts.
The same thing happens when im manually importing the dashboard object via the UI.

**Why import API**
I'm getting 422 Unprocessable Entity errors when using the /api/dashboards/db endpoint with queries that seem valid for the /import endpoint. Also, as said above, the dashboard object works in the UI. Might be related to the issue!

**What you expected to happen**:
After creating the dashboard, the alert should immidiatly show up in the alert list. Having to manually testfire each alert defeats the point of having an automated monitoring of X jobs without the risk of missing one.

**Environment**:
- Grafana version: Grafana v6.3.0-pre (bdaf0aa)
- Data source type & version: Prometheus 2.5.0 (5fef62b83aec95dc2f82b3d77927f8534eb3e46e)
- OS Grafana is installed on: Docker in OpenShift using the image docker.io/grafana/grafana:master

----------------------------------
Here's the JSON part for the alert:

```json
"alert": {
    "conditions": [{
        "evaluator": {
            "params": [
                0.9,
                1.1
            ],
            "type": "within_range"
        },
        "operator": {
            "type": "and"
        },
        "query": {
            "params": [
                "A",
                "2h",
                "now"
            ]
        },
        "reducer": {
            "params": [],
            "type": "avg"
        },
        "type": "query"
    }],
    "executionErrorState": "alerting",
    "for": "0m",
    "frequency": "60s",
    "handler": 1,
    "message": "Job status critical",
    "name": "JOB STATUS ALERT",
    "noDataState": "no_data",
    "notifications": []
}
```

**Comment by torkelo** [comment] 2019-09-17 16:22
duplicate of https://github.com/grafana/grafana/issues/11419

**Comment by torkelo** [comment] 2019-09-17 16:23
temp workaround, load & save dashboard after import

**Closed by torkelo** 2019-09-17 16:22 UTC

**Comment by Svonn** [comment] 2019-09-30 10:59
> 
> 
> temp workaround, load & save dashboard after import

Unfortunatly defeats the point of having automatization for that. Having a large number of jobs we need to use drilldowns / aggregations of alerts that show us if any job in that aggregation is failing. We were hoping by having jobs creating their own dashboards and thus registering in the alert overview we can ensure that there is no job missing.
