### ISSUE TITLE
Enable Warning thresholds for Grafana Alerts

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82928] opened 2024-02-16 17:40 UTC
### Discussed in https://github.com/grafana/grafana/discussions/62634

<div type='discussions-op-text'>

<sup>Originally posted by **AlexeiZenin** January 31, 2023</sup>
With Datadog for the same monitor query we can specify the following thresholds in our Cloudformation. 

With moving to Grafana Alerts we found we need to duplicate our CF resource; 1 for the alert and 1 for a warning. The only differences between the 2 are the thresholds and channels.

Example Datadog monitor config:
```yml
Thresholds:
          Critical: 25.0
          Warning: 100.0
```

This helps improve maintainability, reduce boilerplate, number of "alerts" in the system and reduce load on our respective backends running the alert queries.</div>

**Comment by armandgrillet** [comment] 2024-02-28 10:30
Duplicate of https://github.com/grafana/grafana/issues/6553

**Closed by armandgrillet** 2024-02-28 10:30 UTC
Labels: type/feature-request, area/alerting, migrated-discussions
