### ISSUE TITLE
LDAP auth broke on grafana-6.0.0-beta1?

### ISSUE THREAD

**Issue by sachinrase** [grafana/grafana#15245] opened 2019-02-05 08:24 UTC
hello there , apologies if this is repeat  : is ldap auth broke on  grafana-6.0.0-beta1.x86_64.rpm ( i’m upgrading from  grafana-5.2.4-1 )

Please include this information:
### What Grafana version are you using?
grafana-6.0.0-beta1.x86_64.rpm
### What datasource are you using?
NA
### What OS are you running grafana on?
Centos 7
### What did you do?
upgrading from  grafana-5.2.4-1
### What was the expected result?
LDAP auth continue to work 
### What happened instead?
t=2019-02-04T19:46:19-0800 lvl=info msg="Initial bind failed" logger=ldap error="LDAP Result Code 206 \"Empty password not allowed by the client\": ldap: empty password not allowed by the client"
t=2019-02-04T19:46:19-0800 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 206 \"Empty password not allowed by the client\": ldap: empty password not allowed by the client"
t=2019-02-04T19:46:19-0800 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=xxxx time_ms=23 size=53 referer=https://gui.xxx.com:5000/login
t=2019-02-04T19:46:23-0800 lvl=info msg="Initial bind failed" logger=ldap error="LDAP Result Code 206 \"Empty password not allowed by the client\": ldap: empty password not allowed by the client"
t=2019-02-04T19:46:23-0800 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="LDAP Result Code 206 \"Empty password not allowed by the client\": ldap: empty password not allowed by the client"
t=2019-02-04T19:46:23-0800 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=xxxxx time_ms=23 size=53 referer=https://gui.xxxx.com:5000/login
### If related to metric query / data viz:
no
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 NA

**Comment by sachinrase** [comment] 2019-02-05 08:39
Here is ldap.toml and and I'm testing with LDAP  using openldap-2.4.40-16 
`
$cat /etc/grafana/ldap.toml |grep '[a-zA-Z]' |grep -v '#'
verbose_logging = true 
[[servers]]
host = "xxx.xxx.xxx.xxx"
port = xxxx
use_ssl = false
ssl_skip_verify = false
search_filter = "(xxxxxx=%s)"
search_base_dns = ["dc=xx,dc=xxx,dc=com","ou=groups,dc=xx,dc=xxx,dc=com"]
[servers.attributes]
name = "xxxxxxxxxx"
surname = "xxxxxx"]
username = "xxx"
email =  "xxxxxx"
member_of = "xxxxxxxx" 
[[servers.group_mappings]]
group_dn = "cn=xxx-admin,ou=groups,dc=xx,dc=xxxxx,dc=com"
org_role = "Admin"
[[servers.group_mappings]]
group_dn = "cn=users"
org_role = "Editor"
[[servers.group_mappings]]
group_dn = "*"
org_role = "Editor"`

**Comment by marefr** [comment] 2019-02-05 08:58
Seems like #14511 introduced a regression regarding not allowing empty passwords for bind requests. There's a new [setting in the ldap library](https://github.com/go-ldap/ldap/blob/master/bind.go#L20)  Grafana uses which would allow to reset behavior of allowing empty passwords, but needs to be added  in Grafana, probably as a new configuration parameter?

@torkelo any input on this?

**Comment by torkelo** [comment] 2019-02-05 11:37
hm.. empty password, should we support that?

**Comment by marefr** [comment] 2019-02-05 11:41
Looks like we have supported it, [code](https://github.com/grafana/grafana/blob/ce50e9331ab50d2a1946e3f4a95287c7a1989621/pkg/login/ldap.go#L252) 

Could have been unintentionally supported?

**Comment by torkelo** [comment] 2019-02-05 11:42
no, if no bind password configured we use the password specified by user (direct bind)

**Comment by torkelo** [comment] 2019-02-05 11:45
https://github.com/grafana/grafana/blob/ce50e9331ab50d2a1946e3f4a95287c7a1989621/pkg/login/ldap.go#L262 

always sends in a password, either user password or configured bind password (if a bind password is configured we perform a second bind to validate user password)

**Comment by marefr** [comment] 2019-02-05 17:22
To me it seems like we set the userPassword to empty string on line 252 since `a.server.BindDN` is not configured and marks that we need a second bind. That's fine. But th we do the first bind and it will use an empty password which ldap-go no longer supports without overriding a [setting](https://github.com/go-ldap/ldap/blob/master/bind.go#L20).

**Comment by sachinrase** [comment] 2019-02-05 17:58
@marefr  how can I set `AllowEmptyPassword` in setting ?

**Comment by torkelo** [comment] 2019-02-05 18:03
I don’t see how empty password is possible , either user password is used or bind password

**Comment by marefr** [comment] 2019-02-05 19:04
As I wrote above: 

> To me it seems like we set the userPassword to empty string on line 252 since `a.server.BindDN` is not configured. 

The empty string comes from a bind password not being configured, i.e. value is empty string. 

https://github.com/grafana/grafana/blob/ce50e9331ab50d2a1946e3f4a95287c7a1989621/pkg/login/ldap.go#L253

**Comment by sachinrase** [comment] 2019-02-05 19:21
I'm typing user name and  password in the "Log in" screen , but some how its not carried .There is no bindPassword existing

**Comment by marefr** [comment] 2019-02-05 19:32
@sachinrase multiple threads going on in here. For you to solve this on current 6.0.0-beta1 I think you need to configure [Single Bind](http://docs.grafana.org/auth/ldap/#bind) and set the `bind_dn`. 

Me and Torkel still discusses whether this is a bug or an unintentional feature supported before 6.0.0-beta1.

**Comment by sachinrase** [comment] 2019-02-05 19:51
@marefr  yep it worked like charm ! thanks 👍

**Comment by marefr** [comment] 2019-02-06 11:59
@torkelo given that using single bind and it's required to define `bind_dn` I think we can close this. Do you agree?

**Comment by torkelo** [comment] 2019-02-12 06:45
yes, in a single bind setup bind_dn needs to be defined and include %s for the username: 

example:

```
bind_dn = "cn=%s,o=users,dc=grafana,dc=org"
```

**Closed by torkelo** 2019-02-12 06:45 UTC
Labels: comp: backend/auth/ldap, type: bug

**Comment by costimuraru** [comment] 2019-02-21 14:45
Damn, it's annoying when things break on upgrades :-)
In our case the `bind_dn` line was commented altogether. Was getting the same error when upgraded to Grafana 6. After adding the `bind_dn` [1] line, it started working. Thanks @torkelo @marefr 

`bind_dn = "cn={0},ou=users,o=mycompany"`

**Comment by gribnut** [comment] 2019-02-26 13:04
I also had issue with LDAP authentication after upgrading from Grafana 5.4.2 to 6.0.0.  Previous behavior of Grafana LDAP client was to bind anonymously if bind_dn was an empty string.

Unfortunately in my environment, I don't control the structure/DIT of the LDAP Directory.  Users are not  all under the same branch so a search is required and the Grafana option of single bind_dn pattern doesn't work.  Additionally, the only option we have for searching for users is via anonymous bind as well.

Most of the discussion seems to be around using an empty password.  Seems like the best option is to have the Grafana LDAP client bind anonymously for the initial search if the bind_dn config item is empty (or not set).  
I may be missing something, but would following logic meet current behavior + allow for environments that require anonymous searches?
-  If bind_dn is empty value (or not set), perform anonymous LDAP search for user
- If bind_dn is set but bind_password is empty, use single bind method as described in docs
- If bind_dn and and bind_password are both set, bind with configured credentials for user search

**Comment by JimboJoe** [comment] 2019-03-04 16:32
Hello, we are in the same  case as @gribnut for the [Grafana YunoHost package](https://github.com/YunoHost-Apps/grafana_ynh): we need to perform an anonymous LDAP search (which is handled by many other supported upstream apps).
The proposal to have an anonymous bind when bind_dn/bind_password are empty seems suitable (this was actually the working configuration until 6.0 upgrade).
Thanks!

**Comment by marefr** [comment] 2019-03-04 17:32
@JimboJoe please continue discussions in the current open issue #15643 thanks
