### ISSUE TITLE
Importing Dashboard through Grafana API does not import panels

### ISSUE THREAD

**Issue by efekete** [grafana/grafana#44003] opened 2022-01-13 13:27 UTC
**What happened**:
Using gdg (https://github.com/netsage-project/gdg) for trying to import Dashboard to Grafana result with Error connecting Panels
![Screenshot 2022-01-10 at 21 14 51](https://user-images.githubusercontent.com/31982508/149338640-c432b530-25f0-4628-b308-b6785400f34f.png)

**What you expected to happen**:
Panel in Dashboard to be imported and linked properly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Export any Dashboard with panels
2. Try to POST that Dashboard to Grafana that does not yet have it.

**Anything else we need to know?**:

It works if Imported through Grafana UI
PR with fix: https://github.com/grafana/grafana/pull/43525

**Environment**:
- Grafana version: 8.3.3 and main branch
- Data source type & version: 
- OS Grafana is installed on: Alpine
- User OS & Browser: MacOS BigSur
- Grafana plugins: NA
- Others: NA

**Comment by zuchka** [comment] 2022-01-13 20:03
Thanks for creating this issue, @efekete 

I have never used that third-party tool, and I'm not sure how much help the squads will be in debugging it. Might be better to make an issue in their repo? Sorry if I'm misunderstanding: can you reproduce this without using that tool netsage?

I would also suggest checking out these other third-party tools for dashboard exporting and syncing. There are a handful that are popular:

https://github.com/zuchka/grafana-awesome#dashboard-exporting--syncing

**Comment by efekete** [comment] 2022-01-13 20:14
Yes, it is not tool dependent. It is the way post request works. I was hoping someone could check the PR as it fixes the issue

**Comment by zuchka** [comment] 2022-01-13 23:33
ahh, you wrote that PR! Sorry, I missed that. Looks like the squads are very involved in that thread 👍

**Comment by hugohaggmark** [comment] 2022-01-18 12:31
We don't support importing using the dashboard post api so we'll close this issue and PR. We can always revisit this if more feedback is received from the community. Thank you 🙏

**Closed by hugohaggmark** 2022-01-18 12:31 UTC
Labels: area/backend/api, area/dashboard/import, needs investigation, area/frontend/library-panels
