### ISSUE TITLE
grafana.db should not be mode 755

### ISSUE THREAD

**Issue by wz2b** [grafana/grafana#26313] opened 2020-07-13 23:04 UTC
https://github.com/grafana/grafana/blob/747bdaf2e78d74e2d596f24fe049abe0747f0f57/packaging/deb/control/postinst#L26
```
# Set user permissions on /var/log/grafana, /var/lib/grafana
mkdir -p /var/log/grafana /var/lib/grafana
chown -R $GRAFANA_USER:$GRAFANA_GROUP /var/log/grafana /var/lib/grafana
chmod 755 /var/log/grafana /var/lib/grafana
```
This debian installlation script sets mode 0755 on /var/lib/grafana, but that somehow leaves grafana.db world-readble (0664).  That's a problem, because this database might contain unencrypted passwords used by older datasources.  Even when a datasource gets upgraded (e.g. zabbix grafana datasource) it still seems to leave the old unencrypted 'pasword' field there.  What this means is that an unprivileged user can just run sqlite3 and retrieve these passwords.

I'm not sure where grafana.db gets created.  This can be fixed here in this installation script, but that might not work if grafana creates the database on first run.

Either way ... this file should be protected against local unprivileged user access.

**Comment by aknuds1** [comment] 2020-07-14 06:18
Closing as a duplicate of #8283. I'm assigned to that issue, and plan to work on it soon.

**Closed by aknuds1** 2020-07-14 06:18 UTC

**Comment by wz2b** [comment] 2020-07-14 11:25
Sorry for the duplicate, my bad for not finding the previous ticket.
