### ISSUE TITLE
signatures couldn't be verified

### ISSUE THREAD

**Issue by marekbeckmann** [grafana/grafana#28122] opened 2020-10-08 14:50 UTC
**What happened**: I tried to install Grafana following the official instructions (OSS release) for Debian (https://grafana.com/docs/grafana/latest/installation/debian/)

**How to reproduce it (as minimally and precisely as possible)**: Simply follow the installation instructions (see link above). When it comes to the step `sudo apt-get update` the error will occur (see image below)
![error-installation](https://user-images.githubusercontent.com/56757636/95475320-62a23f80-0986-11eb-9f7c-e6d184243861.png)

**Environment**:
- OS Grafana is installed on: Debian 10 Buster

**Comment by aknuds1** [comment] 2020-10-08 17:10
I think this is a duplicate of #28099. The issue should be rectified, I'll make sure to verify myself though.

**Comment by marekbeckmann** [comment] 2020-10-09 05:37
Just to clarify, I tried installing after you wrote

>  The RPM repos (OSS/enterprise) should be back to normal.

in Issue #28099

**Comment by aknuds1** [comment] 2020-10-09 06:18
I'm trying now to reproduce.

**Comment by aknuds1** [comment] 2020-10-09 06:20
I installed Grafana OSS stable as per the [instructions](https://grafana.com/docs/grafana/latest/installation/debian/), and I get 7.2.1 as expected. Can you please try again and see if the issue is resolved for you? I suspect you might have hit a cached repo.

**Comment by marekbeckmann** [comment] 2020-10-09 06:39
clearing the APT Cache helped and it works now. Thank you very mouch!

**Comment by aknuds1** [comment] 2020-10-09 06:40
Great! Sorry about the hassle!

**Closed by aknuds1** 2020-10-09 06:40 UTC
Labels: needs more detail, type/build-packaging
