### ISSUE TITLE
Ability to alter Home Dashboard

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4147] opened 2016-02-24 20:28 UTC
I am able to edit home dashboard but cannot save it. I can save as a new dashboard but i want to modify home dashboard itself.

Is it allowed or can it be taken as feature request.

**Comment by bergquist** [comment] 2016-02-25 08:36
its not possible right now. dupe of https://github.com/grafana/grafana/issues/1678

feel free to reopen if you disagree.

**Closed by bergquist** 2016-02-25 08:36 UTC
