### ISSUE TITLE
Only got one query while using the inspect to check the "data"

### ISSUE THREAD

**Issue by WakeupTsai** [grafana/grafana#26761] opened 2020-08-03 03:39 UTC
**What happened**:
Only got one query while using the inspect to check the "data"
![image](https://user-images.githubusercontent.com/9034508/89165200-ca18c900-d5aa-11ea-9709-3bd61020c429.png)

**What you expected to happen**:
Should return all the data that show in the table

**How to reproduce it (as minimally and precisely as possible)**:
https://play.grafana.org/d/000000065/prometheus-console-tables?viewPanel=1&orgId=1
-> turn on the "Instant"
-> choose `Table` as the format
-> inspect -> data

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: prometheus
- OS Grafana is installed on: playground
- User OS & Browser: Google Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2020-08-03 06:41
It looks like it shows all the data? What are you missing?

**Comment by WakeupTsai** [comment] 2020-08-03 09:03
@torkelo sorry, I uploaded the wrong image. Already fixed it, please check.

**Comment by WakeupTsai** [comment] 2020-08-24 04:18
@aknuds1 Hi, I updated the detail and image, please help to remove the "needs more detail" label, thanks!

**Comment by peterholmberg** [comment] 2020-10-15 12:23
@WakeupTsai just tried the steps you described and it's showing all data for me. Is this still an issue?

**Comment by roidelapluie** [comment] 2020-10-17 10:44
Yes it is still an issue, tested with 7.3.0-beta1. One table with 7 queries, which make a 8 rows table, only valueA is inspected and exported.
![columns](https://user-images.githubusercontent.com/291750/96335144-8ba58d00-1076-11eb-9a2c-8c89cc402579.png)

**Comment by roidelapluie** [comment] 2020-10-17 10:50
Not that this is a migrated panel form previous versio of grafana that merged values as columns, which I can't do anymore in granafa 7?

**Comment by hugohaggmark** [comment] 2020-10-20 09:38
Related to using Panel Inspect in Angular Panels #27899

**Comment by jjmckain** [comment] 2020-11-10 19:08
We've experienced this same problem.  To the best of my troubleshooting the issue appears to correlate to the timestamp value in the data.  The offending code (in CSV generator) seems to rely on the timestamp values in the data.  Under conditions like above (turning on 'instant'), that timestamp value is the same for all rows, so they overwrite in the table/csv.
In our use-case we're exporting a Table - the columns do not include/group-by time.  In Grafana the rendering looks fine, but when we try to export there's only one row in the table.
![image](https://user-images.githubusercontent.com/1494042/98719665-0a33d880-235e-11eb-8733-f0e43c6b0808.png)


### With Instant=on - timestamps are all the same
![image](https://user-images.githubusercontent.com/1494042/98719072-43b81400-235d-11eb-861b-d7416b9178f4.png)

### With Instant=off - timestamps are unique
![image](https://user-images.githubusercontent.com/1494042/98719190-719d5880-235d-11eb-862c-fde5c1aa9ca3.png)

**Comment by ashharrison90** [comment] 2021-08-09 14:03
hi @WakeupTsai 👋 

i believe the issue has now been fixed as when trying to reproduce in your grafana play link, all the data is now visible:

![image](https://user-images.githubusercontent.com/20999846/128718794-a1a0b595-5eb3-4435-a121-76b79c9d6070.png)

as such, i'm inclined to close this. if i've made a mistake or missed something feel free to add a comment and we can reevaluate. thanks for raising this! 😄

**Closed by ashharrison90** 2021-08-09 14:03 UTC
Labels: needs investigation, area/frontend, panel/inspect
