### ISSUE TITLE
Bar chart does not update value of bar when refreshing dashboard

### ISSUE THREAD

**Issue by Grrrolf** [grafana/grafana#39008] opened 2021-09-08 19:57 UTC
**What happened**:
Data in the database had been updated with new rows. However, when I click 'refresh dashboard', the bar chart increases but the value is not updated.

**What you expected to happen**:
That the value is also updated after clicking 'refresh dashboard'.

**How to reproduce it (as minimally and precisely as possible)**:
* create a table in postgresql
* insert rows
* create dashboard with a bar chart panel in grafana
* use a simple select count() by datetime and group them into quarters of a year query (grouping by day likely suffices)
* now save the dashboard en reload the web page.
* add more rows to the table in postgresql 
* now click 'refresh dashboard' next to the time picker.

For visuals see this video and keep your eye on the right green bar (Q2021-03). The at the start is 3,165, after clicking 'refresh dashboard' you will see the green bar grow, but the value stays the same. Next you'll see a reload of the web page (using the browser reload) and the correct value is shown (3,119):

https://user-images.githubusercontent.com/10052794/132575877-7564cf86-0af0-4bed-b4b0-3ac1a795a9e8.mp4

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2 (OSS)
- Data source type & version: postgresql latest
- OS Grafana is installed on: Ubuntu 21.04
- User OS & Browser: macOS & windows OS + Google chrome - latest
- Grafana plugins: only default plugins + postgresql datasource plugin
- Others: ...

**Comment by leeoniya** [comment] 2021-09-08 22:14
Duplicate of https://github.com/grafana/grafana/issues/38410.

Hoping to get this resolved in the next couple weeks, maybe not by 8.2.0, but 8.2.x.

**Closed by leeoniya** 2021-09-08 22:14 UTC

**Comment by Grrrolf** [comment] 2021-09-09 21:47
@leeoniya, quick question so I won't first create another issue which might possibly be another duplicate.

Will  #38410 also solve the issue of the tooltip not showing values when the bar chart has more than one value per category when tooltip is set to 'all' when they values are grouped? Or when the values are stacked, it won't show the values not when tooltip is set to 'single' or when it is set to 'all'? If not, I can file an issue for this issue.

Have a look at the video:

https://user-images.githubusercontent.com/10052794/132766649-e3f18530-ab01-476b-bdc4-eaa1ab745d94.mp4

**Comment by leeoniya** [comment] 2021-09-10 02:53
> Will #38410 also solve the issue of the tooltip not showing values when the bar chart has more than one value per category when tooltip is set to 'all' when they values are grouped? 

nope, please open a new issue with above details, titled something like **BarChart: missing tooltip values**

we're currently re-structuring some of the internal data structures that can be shared between legend, tooltip and visualizations. this bug exists in part because the intermediate stacked sums are only exposed in some of those contexts.

**Comment by Grrrolf** [comment] 2021-11-23 16:10
@leeoniya:
> [..] please open a new issue with above details, titled something like **BarChart: missing tooltip values**

I have finally opened a new issue for this (#42130).
