### ISSUE TITLE
Downloading Grafana Image Renderer shows BadRequest

### ISSUE THREAD

**Issue by ladeak** [grafana/grafana#22248] opened 2020-02-17 13:00 UTC
I would like to download and install Grafana Image Renderer from Grafana plugins site.
**What happened**:
{
  "code": "BadRequest",
  "message": "Version 1.0.9 is not available for undefined-undefined"
}
**What you expected to happen**: I download a zip file
**How to reproduce it (as minimally and precisely as possible)**:
Click the link at the bottom of page: https://grafana.com/grafana/plugins/grafana-image-renderer/installation

"Alternatively, you can manually download the .zip file and unpack it into your grafana plugins directory."

**Anything else we need to know?**: It seems be the case for all version (including 1.0.9), but just this plugin. Other plugins seems to download fine.

Download link reproduces the issues as well: https://grafana.com/api/plugins/grafana-image-renderer/versions/1.0.9/download

**Comment by aknuds1** [comment] 2020-02-17 13:29
Thanks, I could reproduce this. Looking into how to solve it.

**Comment by aknuds1** [comment] 2020-02-17 14:31
Turns out this is a duplicate of https://github.com/grafana/grafana-image-renderer/issues/47. From what I hear, this is an issue that occurs when a plugin has more than one architecture available, so it isn't an easy fix. The ETA for a fix is Q1 this year. We also recommend installing the plugin via grafana-cli, which should be painless.

**Closed by aknuds1** 2020-02-17 14:31 UTC
Labels: type/bug
