### ISSUE TITLE
Grafana loses query when forwarding to Explore view

### ISSUE THREAD

**Issue by cf-sewe** [grafana/grafana#28729] opened 2020-11-02 07:53 UTC
**What happened**:
When using a specific Loki query, Grafana will no longer be able to forward the original query to the explore view.

**What you expected to happen**:
The original queries should be forwarded to Explore view

**How to reproduce it (as minimally and precisely as possible)**:
This seems to be caused by `%` being present in the query (valid query for loki v2):
```
{namespace="$namespace"} | line_format "{{ printf \"%s\" .pod}}"
```

The URL will update to:
```
https://grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%7D%5D
```

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.3.1
- Data source type & version: Loki 2.0.0
- OS Grafana is installed on: AWS EKS
- User OS & Browser: Windows/Google Chrome
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment] 2020-11-02 08:37
Thanks for raising this @cf-sewe. I'm closing this as this is a duplicate of https://github.com/grafana/grafana/issues/28568

**Closed by zoltanbedi** 2020-11-02 08:37 UTC
