### ISSUE TITLE
Config from Query only allows one threshold, no modification

### ISSUE THREAD

**Issue by lordratner** [grafana/grafana#78013] opened 2023-11-10 17:57 UTC
### What happened?

The previous bug related to this was solved here: #68277

However now there is only the ability to add one threshold from a Config from Query transform. When you hit the "Use as" dropdown there is an option for "Threshold1" which implies the ability to set multiple thresholds, however additional transformations only have the option for "Threshold1."

Additionally, none of these thresholds can be adjusted to set the color. 

There is another strange behavior. When you add Threshold1 using the Config from Query, there is a representation of the added threshold above the Thresholds dialog:

![transforms](https://github.com/grafana/grafana/assets/49489398/9b80abf7-2ea9-4384-8a6f-f9dcc7d048b9)

But it will only show one dot, even if you have multiple transforms creating thresholds. 

However, if you then add an override threshold (which you wouldn't do if using Config from Query thresholds, but I tried anyways), then two Config from Query thresholds appear in the settings dialog, even though they don't work:

![override](https://github.com/grafana/grafana/assets/49489398/1161be49-b043-44b6-821a-6861dfa31264)

### What did you expect to happen?

1. The dropdown should allow for setting multiple Thresholds (not just Threshold1)
2. There should be a way to set the color for each Config from Query threshold, either in the Config from Query box or the Thresholds section of the settings. 

### Did this work before?

No

### How do we reproduce it?

1. Create a Query 
2. Create two expressions from that query (or use two different queries, or anything)
![queries](https://github.com/grafana/grafana/assets/49489398/decca912-9b76-4dd0-8ce5-a3dcbb922ed1)

3. Use the expressions from step two in Transform Data to create two Config from Query Results where they are applied to the Query in step 1 as Thresholds
4. Try to get two thresholds to work, and try to set the color for the thresholds.

### Environment (with versions)?

Grafana: 10.3
OS: Debian
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by leeoniya** [comment] 2023-11-10 20:20
duplicate of #45803 

tracked in https://github.com/grafana/grafana/issues/77491

**Closed by leeoniya** 2023-11-10 20:20 UTC
