### ISSUE TITLE
Global and Folder Variables

### ISSUE THREAD

**Issue by leo-galaxy** [grafana/grafana#90640] opened 2024-07-19 08:39 UTC
**Why is this needed**:

Global and folder variables that can be added on global level and folder level 
and can be inherited instead of creating a variable on each dashboard and duplicating all the time.

Would be nice to have the option to create 
1. Global variables that are inherited to all the folders sub folders and dashboards.
2. Folder variables that are inherited for subfolders and dashboards

<img width="1167" alt="Screenshot 2024-07-19 at 10 31 39 AM" src="https://github.com/user-attachments/assets/d40ad883-6026-41a9-91c5-6c5209524209">
<img width="1148" alt="Screenshot 2024-07-19 at 10 28 56 AM" src="https://github.com/user-attachments/assets/9d5e16f6-f893-4d1f-9a00-8fc573674f8d">

**What would you like to be added**:

Global variable inherited by all folders and dashboards 
Folder variables inherited by its subfolders and dashboards

**Who is this feature for?**

Everyone using dashboards

**Comment by gelicia** [comment] 2024-07-19 14:28
Duplicate of #1959

**Closed by gelicia** 2024-07-19 14:28 UTC
