### ISSUE TITLE
Improve the error messages for "log volume" histogram timeouts

### ISSUE THREAD

**Issue by simonswine** [grafana/grafana#49333] opened 2022-05-20 13:56 UTC
**What happened**:

When waiting for the result of a quite heavy Loki query in the Explore view. There are different timeouts:
- The "Log volume" histogram times out after 10s
- The actual query times out after 2 Minutes

If the "log volume" query times out after 10s the error is displayed like this:

![scrn-2022-05-20-14-53-33](https://user-images.githubusercontent.com/223048/169542893-39daf240-2fe0-452e-a4bd-7cd5b98ecdfa.png)

The actual log results are still processing, but many users think that there is no more results to expect.

**What you expected to happen**:

Making it clearer, by maybe a more subtle message that only the log volume is not able to be processed in time and that there still results to be expected.

**How to reproduce it (as minimally and precisely as possible)**:

Go to a Loki Explore view and query something over a very long time period, so that it is likely to cause a timeout.

**Anything else we need to know?**:

**Environment**: Grafana Cloud and likely on prem Grafana + Loki
- Grafana version: v8.5.2
- Data source type & version: Logs/Loki

cc @09jvilla

**Comment by joey-grafana** [comment] 2022-05-20 14:25
Thank you for creating a PR for this. I think it's a duplicate of [Easier to understand error message for Grafana Cloud Logs customers](https://github.com/grafana/grafana/issues/48988) so closing this in favor of that. Please feel free to reopen if not.

**Comment by simonswine** [comment] 2022-05-20 15:36
I don't think it is a duplicate, they are closely related. But even if the error would clearer around the timeout, it would not be clear that an error is just for the log volume panel rather than the actual query.

**Comment by 09jvilla** [comment] 2022-05-20 17:39
@simonswine So what you're saying is that want a way so that the users knows more clearly they should wait around for the actual log lines to be returning even if the histogram doesn't load.

**Comment by 09jvilla** [comment] 2022-05-20 17:44
<img width="1268" alt="Screen Shot 2022-05-20 at 1 40 56 PM" src="https://user-images.githubusercontent.com/9610816/169583441-d0015525-c872-41e1-a9f4-1cb191791588.png">
Did the customer not see this blue bar that's horizontally moving across the screen as their query continues to load?

**Comment by 09jvilla** [comment] 2022-05-20 17:46
You can actually also see the bar in @simonswine 's original screenshot:
![barthat moves](https://user-images.githubusercontent.com/9610816/169583695-2b74c056-ee7c-417b-adc4-87ec6257c039.jpg)


I'm fine with making the error message more verbose - I guess this current indicator we have is not sufficient, which isn't what I would first expect.

**Comment by ethirolle** [comment] 2022-05-20 17:50
@09jvilla, correct! (I was on the same customer call with Christian.)

No, the customer did not notice that blue bar (nor have I noticed that before, tbh... too subtle for some of us, lol?)

---

Relatedly (but maybe a separate PR or issue?): it would be cool if we could also look into "streaming" the log query results to the UI, as Christian mentioned briefly in https://github.com/grafana/support-escalations/issues/2614. I.e., rather than populate query results into the UI after all the query results have returned, start populating query results in the UI asap, while the rest of the query continues to run. This would replicate the expected behavior for customers used to querying logs in Stackdriver UI. However, I understand it could be technically tricky due to query sharding, etc.

**Comment by 09jvilla** [comment] 2022-05-20 17:54
@ethirolle I will create a separate issue for the streaming results. It is definitely something that makes sense to do and that I've heard come up in other conversations, but its not a quick change so it likely won't get picked up until next quarter at the earliest.

**Comment by 09jvilla** [comment] 2022-05-20 17:55
> No, the customer did not notice that blue bar (nor have I noticed that before, tbh... too subtle for some of us, lol?)

I'll talk with the UX team about trying to make it more clear :) Words are good but a picture is worth 1000 words so would be great if we can indicate this more visually.

**Comment by gabor** [comment] 2022-05-23 06:57
@simonswine 
> **Environment**: Grafana Cloud and likely on prem Grafana + Loki

thanks for reporting the problem. just a small clarification: the thing where the log-volume-query timeouts sooner than the "normal" query is grafana-cloud specific.
when it is on-prem, the user could set their grafana&loki so that this happens too, but it does not happen by default.

**Comment by gabor** [comment] 2022-05-23 06:59
@09jvilla regarding the streaming-displaying the results, can Loki do this? i mean, if i send a let's say range-http-query https://grafana.com/docs/loki/latest/api/#get-lokiapiv1query_range , will Loki stream the http-results back to grafana, or will it first build the whole http-response "in loki" and then return it?

**Comment by 09jvilla** [comment] 2022-05-24 12:28
We cannot do this today @gabor -- I would like for us to make that possible though :) 

following up on https://github.com/grafana/loki-private/issues/292

**Comment by gabor** [comment] 2022-06-10 11:24
hi, from what i can see here, half of the problems will be handled by https://github.com/grafana/grafana/issues/48988 , and the other half is a feature-request to have a better is-loading visual indicator. feature requests go to github-discussions, so i created one here: https://github.com/grafana/grafana/discussions/50598

with this i think we have everything covered, so i'm closing the issue. if i missed something, please tell me and we can cover those topics too.

thanks for all your feedback!

**Closed by gabor** 2022-06-10 11:24 UTC
Labels: datasource/Loki
