### ISSUE TITLE
Grafana 9.3 and 9.4 "Copy" disabled for legend text

### ISSUE THREAD

**Issue by reyjrar** [grafana/grafana#64084] opened 2023-03-02 22:34 UTC
**What happened**:

In earlier versions of Grafana, you could copy the text from the legend in the Legacy Graph and Time Series panels.

This appears to have gone away in 9.3 and 9.4 and is breaking some workflows.

**What you expected to happen**:

Highlight text in the legend, copy, and then paste into either the dashboard as a filter or else where for analysis.

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to highlight text in legend on the Time Series or Legacy Graph panels.

**Anything else we need to know?**:

If you want to do a solid, add a "copy to pasteboard" shortcut option to legend labels. It's often critical to workflows to take data from the legends to use as a filter or jumping off point for an investigation. 

There may be some "UX Guideline" somewhere that suggests removing the highlight here is better, but without a "copy to pasteboard" option, it completely breaks all of our workflows.

We have "overview" dashboards that display a number of graphs bubbling "top N"s up to view. We typically pivot by trying to click on those and add them as filters.  This has never been an option with Time Series or Legacy Graphs (but is in the Table View). It would be *really* useful to have that as well.

**Environment**:
- Grafana version: 9.3.1 and 9.4.3
- Data source type & version: Any
- OS Grafana is installed on: CentOS 7
- User OS & Browser: MacOS Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by mellieA** [comment] 2023-03-04 00:51
@reyjrar I tried this with grafana 9.4.3 and the timeseries panel using the chrome browser and I was able to click to select and then right-click to copy the text in the legend. 

Is that the same workflow you're trying in firefox? A screen recording would be really helpful to see what you're experiencing

**Comment by reyjrar** [comment] 2023-03-07 20:03
Attached is a screen recording showing the issue:

https://user-images.githubusercontent.com/99365/223539344-0eb550be-9c0f-4ad9-a93d-cb57bab65641.mov

**Comment by reyjrar** [comment] 2023-03-15 17:19
@mellieA Any chance you were able to verify this? It's really interrupting our workflows and I'm in a position where I might have to start downloading older releases until I find out where it was working.

**Comment by reyjrar** [comment] 2023-04-11 17:37
PInging Again @mellieA and @tonypowa

**Comment by mellieA** [comment] 2023-04-18 15:01
@reyjrar it works for me on 9.4.3 and 9.4.7 with Chrome. I was able to reproduce this with firefox and 9.4.7 and @tonypowa saw it on 9.4.3 with firefox too

**Comment by zurikus** [comment] 2023-04-20 07:56
Does not work for us either, Grafana 9.4.7. with Chrome. 
Unable to copy from table style "Legend" on Time Series graph. 
It's only possible if we are entering in graph "Edit" mode.

**Comment by clickfreak** [comment] 2023-09-05 13:15
problem still there, Grafana 10.1

But nuance: problem exists if legend shows as "table", if you set legend to "list" then you can select items as text, but its unusable in case if you need any sorting in legend (by min/max/last/total). tbh, i have a lot of dashboards and none of them use "list" in legend. Context: operations of thousands physical servers, terabits of traffic.

It will be good to remove Grafana version mention in title, its really confusing, especially managers in Grafana Labs  ("why we need to take this task with problems in old versions? users just need to update grafana version" 😂)
Maybe add "since 9.3". Or create a new dedicated issue about problem in table legend.

// its really annoyed "bug",  i start to compare Grafana with Nero Burning ROM (it was program to burn CD/DVD, but they start to implement a lot of strange things and finally forget about burning CD/DVD 😂). Why? Because another interesting thing is using canvas to show legend in another Grafana components ("State timeline", for example) which even doesn't allow search by text on the page using basic browser feature.

**Comment by Cougar** [comment] 2023-10-16 11:02
I got hint here: https://github.com/grafana/grafana/pull/56690/files#r993297256
Fix is described here https://stackoverflow.com/a/56039655
I tried it directly in developer tools and adding `user-select: text` to my `.css-7q41tt-LegendLabel` style fixed this issue. Just have to find out now from where is this style coming.

**Comment by TimSimmons** [comment] 2024-02-22 00:42
this still pains me on a daily basis 😭

**Comment by baldm0mma** [comment] 2024-02-26 17:34
This should be fixed by the above PR. And as a note, our current procedural framework does not accommodate back porting any change that **_isn't_** a critical bug-fix, so please consider upgrading to G11 when it releases. Thanks!

**Closed** 2024-02-27 00:35 UTC
Labels: type/bug, area/panel/timeseries, triage/needs-confirmation, area/legend
