### ISSUE TITLE
Unable to build image using source code v9.3.1

### ISSUE THREAD

**Issue by anushanagireddy0430** [grafana/grafana#61021] opened 2023-01-05 08:03 UTC
Unable to build docker image using the source code for grafana version 9.3.1

I have cloned grafana code and checkout to tag v9.3.1. I should be able to build docker image
Getting below error when docker build command is run. Though all the required .cue files are present.

(re)installing /go/bin/wire-v0.5.0
go: downloading github.com/google/subcommands v1.0.1
go: downloading golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b
generate code from .cue files
go generate ./pkg/plugins/plugindef
go: downloading github.com/deepmap/oapi-codegen v1.10.1
go: downloading github.com/grafana/codejen v0.0.2
go: downloading github.com/grafana/cuetsy v0.1.1
go: downloading golang.org/x/mod v0.7.0
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading github.com/labstack/echo/v4 v4.9.0
go: downloading github.com/labstack/gommon v0.3.1
go: downloading github.com/valyala/fasttemplate v1.2.1
/grafana/embed.go:9:31: pattern kinds/*/*.cue: no matching files found
pkg/plugins/plugindef/plugindef.go:11: running "go": exit status 1
make: *** [Makefile:69: gen-cue] Error 1
The command '/bin/sh -c make build-go' returned a non-zero code: 2

**Comment by mellieA** [comment] 2023-01-06 23:09
@anushanagireddy0430 this looks like a duplicate of https://github.com/grafana/grafana/issues/58921 

The [comments](https://github.com/grafana/grafana/issues/58921#issuecomment-1319826837) note that pulling in the PR there, the image builds as expected

**Closed by mellieA** 2023-01-06 23:09 UTC
Labels: type/duplicate

**Comment by zsdyx** [comment] 2023-01-09 01:30
I use version 9.3.2, Also encountered the problem of building failure.The errors are as follows
`#29 278.7 (re)installing /go/bin/wire-v0.5.0
#29 278.8 go: downloading github.com/google/subcommands v1.0.1
#29 278.8 go: downloading golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b
#29 285.6 generate code from .cue files
#29 285.6 go generate ./pkg/plugins/plugindef
#29 285.8 go: downloading github.com/grafana/codejen v0.0.2
#29 285.8 go: downloading github.com/deepmap/oapi-codegen v1.10.1
#29 285.8 go: downloading github.com/grafana/cuetsy v0.1.1
#29 285.8 go: downloading golang.org/x/mod v0.7.0
#29 288.5 go: downloading github.com/xlab/treeprint v1.1.0
#29 288.7 go: downloading github.com/labstack/echo/v4 v4.9.0
#29 289.5 go: downloading github.com/labstack/gommon v0.3.1
#29 289.9 go: downloading github.com/valyala/fasttemplate v1.2.1
#29 292.9 /grafana/embed.go:9:31: pattern kinds/*/*.cue: no matching files found
#29 292.9 pkg/plugins/plugindef/plugindef.go:11: running "go": exit status 1
#29 292.9 make: *** [Makefile:69: gen-cue] Error 1`

**Comment by FengKaiYan** [comment] 2023-01-13 03:11
me too

/grafana/embed.go:9:31: pattern kinds/*/*.cue: no matching files found
pkg/plugins/plugindef/plugindef.go:11: running "go": exit status 1
make: *** [Makefile:69: gen-cue] Error 1
The command '/bin/sh -c make build-go' returned a non-zero code: 2
ERROR: Job failed: exit code 1



please tell me how to do
