### ISSUE TITLE
Sorting is done on the basis of only alphabetical order it should also sort on the basis of data format like date and number

### ISSUE THREAD

**Issue by patidarvivek** [grafana/grafana#23493] opened 2020-04-10 06:54 UTC
The number format is not sorted correctly in table panel it is sorting according to the alphabet, it should also sort on the basis of column format type i.e number, date etc. This issue/bug occur in table format

**What happened**: when sorting the number format order is like
94, 86, 79, 72, 64 ,63, 6, 53, 310 

**What you expected to happen**:
The order should be like
310, 94, 79, 72, 64, 63, 53, 6

**How to reproduce it (as minimally and precisely as possible)**:
sort it on the basis of number format, apply to sort on the basis of data format 

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 6.7.1
- Data source type & version: influxDB 1.7.10
- OS Grafana is installed on: ubuntu 18.04LTS
- User OS & Browser: Chrome and firefox
- Grafana plugins: nil
- Others:

**Comment by jongyllen** [comment] 2020-04-11 15:33
Hi, thanks for submitting. This looks like a duplicate of #22887 so I will close this one to keep it in one issue.

**Closed by jongyllen** 2020-04-11 15:33 UTC
Labels: type/duplicate
