### ISSUE TITLE
Lazy loading CodeEditor component can generate ChunkLoadError (webpack)

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#35199] opened 2021-06-03 14:56 UTC
**What happened**:

Got a javascript error when trying to load json response in explore.

**What you expected to happen**:

No error

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/1053421/120665863-6ee68a00-c48c-11eb-9f98-37d184745a7a.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.0-24922pre (aa4c5bbfe4)
- Data source type & version: Loki

full error stack:

```
ChunkLoadError: Loading chunk 62 failed.
(error: https://admin-ops-us-east-0.grafana.net/grafana/public/build/code-editor.921a2e95768c8455b3aa.js)
ChunkLoadError: Loading chunk 62 failed.
(error: https://admin-ops-us-east-0.grafana.net/grafana/public/build/code-editor.921a2e95768c8455b3aa.js)
    at Function.o.e (https://admin-ops-us-east-0.grafana.net/grafana/public/build/runtime.921a2e95768c8455b3aa.js:1:2692)
    at He (https://admin-ops-us-east-0.grafana.net/grafana/public/build/app.921a2e95768c8455b3aa.js:3326:3402)
    at na (https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:2547235)
    at Uu (https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:2599671)
    at Os (https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:2586683)
    at _s (https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:2586611)
    at ws (https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:2586474)
    at ds (https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:2583461)
    at https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:2533130
    at t.unstable_runWithPriority (https://admin-ops-us-east-0.grafana.net/grafana/public/build/vendors~app.921a2e95768c8455b3aa.js:2:64144)
```

**Comment by axelavargas** [comment] 2021-06-16 15:10
@cyriltovena thank you for reporting this issue 🙌🏾, I did some investigation about it, so here my findings 😄:

* When we are loading Inspector -> JSON, we are lazy loading the `Code Editor` component
* This component is being loaded on demand by using a chunk name generated by Webpack
* If the user is on the explore page, and there is a new build, the chunk name changes
* But because the browser only has the old build reference, when it's trying to load the editor, it can't find it.

* Refreshing the page, is the easiest(_ofc not ideal_) solution if a user is facing this situation.

But I just want to confirm if my findings are correct, can you refresh the page and try again to reproduce this issue? (_I was only able to do it locally by forcing a build and not refreshing the page_)

Thank you!

ps:
There are some alternatives that can potentially solve this issue (using a service worker or telling the user that the page needs to be refreshed), but this requires more planning time, I would check internally how likely this will go into the roadmap in the future.

**Comment by cyriltovena** [comment] 2021-07-01 12:58
Correct refreshing the page,  re-run the query and it was fine.

**Comment by axelavargas** [comment] 2021-07-12 09:56
@cyriltovena Thank you for the confirmation 🙌🏾, we did a small research on possible alternatives, in the future we want to show the users a message to hint they need to refresh the page when this situation happens, for now, I will close this issue, we will revisit the topic in the coming quarters after finalizing other initiatives.

**Closed by axelavargas** 2021-07-12 09:56 UTC
Labels: area/frontend/code-editor, panel/inspect, type/bug
