### ISSUE TITLE
runtime error when creating new dashboard via the API

### ISSUE THREAD

**Issue by nicklan** [grafana/grafana#17510] opened 2019-06-10 22:46 UTC
**What happened**:
I tried to create a dashboard via the `api/dashboard/db` endpoint, and grafana returns an error and logs `runtime error: invalid memory address or nil pointer dereference`.  The dashboard is still created as expected however.

**What you expected to happen**:
The api call to return 200 Success.

**How to reproduce it (as minimally and precisely as possible)**:
Creating a json file at /tmp/dash.json with:
```json
{
   "dashboard": {
      "id": null,
      "schemaVersion": 16,
      "tags": [
         "templated"
      ],
      "timezone": "browser",
      "title": "foo",
      "uid": null,
      "version": 0
   },
   "folderId": 0,
   "overwrite": false
}
```

Do:
`curl -v -H "Authorization: Bearer $TOKEN" -H "Accept: application/json" -H "Content-Type:application/json" -X POST -d@/tmp/dash.json "https://$GRAFANA_URL/api/dashboards/db"`

**Anything else we need to know?**:

The dashboard does get created, but errors are also reported.

Here's the full (redacted) output of the curl command:
```
*   Trying [IP]:443...
* TCP_NODELAY set
* Connected to [URL] ([IP]) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
[snip]
*  SSL certificate verify ok.
> POST /api/dashboards/db HTTP/1.1
> Host: [HOST]
> User-Agent: curl/7.65.0
> Authorization: Bearer [Token]
> Accept: application/json
> Content-Type:application/json
> Content-Length: 233
> 
* upload completely sent off: 233 out of 233 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.17.0
< Date: Mon, 10 Jun 2019 22:39:21 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 122
< Connection: keep-alive
< 
* Connection #0 to host [HOST] left intact
{"error":"Server Error","message":"Internal Server Error - Check the Grafana server logs for the detailed error message."}
```

The server logs say:
```
t=2019-06-10T22:38:41+0000 lvl=eror msg="Request error" logger=context userId=0 orgId=1 uname= error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:513 (0x435098)\n/usr/local/go/src/runtime/panic.go:82 (0x4341ed)\n/usr/local/go/src/runtime/signal_unix.go:390 (0x44b011)\n/go/src/github.com/grafana/grafana/pkg/api/dashboard.go:284 (0x1000076)\n/go/src/github.com/grafana/grafana/pkg/api/api.go:294 (0x103d235)\n/usr/local/go/src/runtime/asm_amd64.s:525 (0x463a24)\n/usr/local/go/src/reflect/value.go:447 (0x4c1223)\n/usr/local/go/src/reflect/value.go:308 (0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x771243)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x770ba9)\n/go/src/github.com/grafana/grafana/pkg/api/common.go:37 (0x103bf4d)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46385a)\n/usr/local/go/src/reflect/value.go:447 (0x4c1223)\n/usr/local/go/src/reflect/value.go:308 (0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x771243)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x770ba9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79f130)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79f04e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xa65e7c)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46385a)\n/usr/local/go/src/reflect/value.go:447 (0x4c1223)\n/usr/local/go/src/reflect/value.go:308 (0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x771243)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x770ba9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79f130)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79f04e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xa65797)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46385a)\n/usr/local/go/src/reflect/value.go:447 (0x4c1223)\n/usr/local/go/src/reflect/value.go:308 (0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x771243)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x770ba9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79f130)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79f04e)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:147 (0xa656b0)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x79efd0)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x770f30)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x770c9b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79f130)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x79f04e)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xa62efd)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46385a)\n/usr/local/go/src/reflect/value.go:447 (0x4c1223)\n/usr/local/go/src/reflect/value.go:308 (0x4c0cb3)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x771243)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x770ba9)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x79f130)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x7af927)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:294 (0x7aa146)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x7a35f1)\n/usr/local/go/src/net/http/server.go:2741 (0x6b379a)\n/usr/local/go/src/net/http/server.go:1847 (0x6afb35)\n/usr/local/go/src/runtime/asm_amd64.s:1333 (0x465570)\n"
t=2019-06-10T22:38:41+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/dashboards/db status=500 remote_addr=10.2.134.0 time_ms=50 size=122 referer=
```

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: Prometheus 5.2
- OS Grafana is installed on: Linux 4.14.78
- User OS & Browser: N/A
- Grafana plugins: None
- Others:

**Comment by nicklan** [comment] 2019-06-11 18:59
Happy to help with any investigation here.  LMK what would be useful.

**Comment by marefr** [comment] 2019-07-03 20:55
Based on stacktrace seems like something is nil when trying to log error here (note 6.1.6 tag) https://github.com/grafana/grafana/blob/cf9cb45fe84cfab8d2580d163c1f653c5d5a96b5/pkg/api/dashboard.go#L284

To investigate: My guess would be cmd.Result is nil or c.SignedInUser is nil. I would suggest trying calling this api using a generated api key. Then I think you should be able to reproduce.

**Comment by papagian** [comment] 2019-07-08 10:08
> To investigate: My guess would be cmd.Result is nil or c.SignedInUser is nil. I would suggest trying calling this api using a generated api key. Then I think you should be able to reproduce.

Indeed, `cmd.Result` is nil since it is assigned to `dashboard` variable
https://github.com/grafana/grafana/blob/master/pkg/api/dashboard.go#L232
https://github.com/grafana/grafana/blob/master/pkg/services/dashboards/dashboard_service.go#L256

**Closed** 2019-07-11 06:45 UTC
Labels: area/backend/api, type/bug
