### ISSUE TITLE
[Feature request] Increase the limit of lookup values

### ISSUE THREAD

**Issue by tomaszpapirzwierz** [grafana/grafana#13652] opened 2018-10-12 12:24 UTC
### What Grafana version are you using?
5.1.2

### What datasource are you using?
TSDB

### What OS are you running grafana on?
Red Hat Enterprise Linux Server release 6.7 (Santiago) 2.6.32-573.18.1.el6.x86_64

In my company we write loads of metrics to OpenTSDB which is then our main source of data for Grafana. Recently we were hit by an autofill limit which limits the number of records in the variable lookup field to 3000. Here is an example: say we have a variable $host defined in a dashboard.  If a metric used in that dashboard has in its history more than 3000 different values for $host, those values won't be available in the host drop-down menu. We have actually found where that limit comes from and it is /usr/share/grafana/public/build/0*.js file having this setting:

`return this._get("/api/search/lookup",{m:i,limit:3e3})`

After manually changing this to

`return this._get("/api/search/lookup",{m:i,limit:3e5})`

we get to see more (all) values for $host variable. The problem we have is that whenever we upgrade Grafana, this property gets overwritten. My feature request is to increase this property to 3e5 in the Grafana source code.

**Comment by torkelo** [comment] 2018-10-12 13:17
duplicate of https://github.com/grafana/grafana/issues/8155

**Closed by torkelo** 2018-10-12 13:17 UTC

**Comment by tomaszpapirzwierz** [comment] 2018-10-12 18:35
Apologies @torkelo, I put some effort before raising this issue to find if it has been raised by anyone. Looks like I was using wrong key words.
