### ISSUE TITLE
Notification channel not working after upgrade from 5.3.2 to 6.1.6

### ISSUE THREAD

**Issue by nicholasgibson2** [grafana/grafana#17260] opened 2019-05-23 23:29 UTC
**What happened**: one of our email notification channels stopped sending emails after upgrading from 5.3.2->6.1.6 This channel was created before the upgrade and was working. Emails still do not send even when changing destination email address. The test notification email sends successfully but no emails send to this channel from alerts. 

**What you expected to happen**: the notification channel to send emails

**How to reproduce it (as minimally and precisely as possible)**: select this notification channel for an alert and set the threshold to fire.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: all data source types
- OS Grafana is installed on: CentOS 7.2.1511
- User OS & Browser: all browsers
- Grafana plugins: N/A
- Others: N/A

**Comment by rossf88** [comment] 2019-05-24 14:31
I have the same issue. The colour of the heart representing the alert state is always white/grey also, even when using a tautology as a query. Test works fine, however the state does not change and as such the alert does not trigger to slack.

**Comment by torkelo** [comment] 2019-05-27 06:12
Any errors or relevant log messages (in Grafana log). 

Does the notification have the "Default (send on all alerts)" checkbox checked? or is it manually added to your alert rules? Can you open the alert rule and verify that it is added? Try removing and readding it t o the alert rule and save dashboard again. Does this affect anything? Just trying to narrow down what could be wrong.

**Comment by rossf88** [comment] 2019-05-27 09:01
I have tried both with and without default. There is also another default channel, so is it potentially the case that there is a problem with multiple channels? 

I do think though the issue is not with the actual alert/channel but rather the state change. The test for each channel works fine, it is more the fact that the actual state itself does not change when it should. IE the state history is empty, and status is currently unknown. Even though my rule for no data / null values is to change the state to "Ok" , that does not happen. Is just always unknown.

**Comment by nicholasgibson2** [comment] 2019-05-28 20:03
@torkelo The notification was not set to default, it was manually added to the alert rule. After setting it as a default alerts send successfully. Removing it as default and manually adding it to an alert rule makes the email not send. Removing the channel and readding to the same alert does not fix it. Removing the alert and creating a new alert does not fix it. When I configure alerts to send to 2 channels I do not see an info log for the broken channel, but I do see one for the working channel. I do not see any error logs around the same time, or any error logs that look like they could be related.

**Comment by torkelo** [comment] 2019-09-04 18:45
Strange, still seeing this?

**Comment by nicholasgibson2** [comment] 2019-09-05 16:43
Still seeing this issue but only with that one channel. Haven't seen it with any other channel.

**Comment by hugohaggmark** [comment] 2019-09-30 09:50
Hi @nicholasgibson2 are you still having issues with this?

**Comment by torkelo** [comment] 2019-10-19 07:57
closing this due to lack of update, 

think this could have been caused by this:
https://github.com/grafana/grafana/issues/19771

**Closed by torkelo** 2019-10-19 07:57 UTC
Labels: needs more detail
