### ISSUE TITLE
Explore: wrong datasource shown in explore coming from a panel 

### ISSUE THREAD

**Issue by oanamangiurea** [grafana/grafana#32221] opened 2021-03-22 15:12 UTC
I am playing in play.grafana.com with one of the dashboards we have as example for prometheus datasource. No matter what panel I inspect via explore I get a graphite datasource selected with an empty query, but if I hit browser back I see the correct query with prometheus datasource selected. I am using this dashboard. See recording for the issue

https://user-images.githubusercontent.com/5183519/112012075-8cfd4900-8b31-11eb-83ac-91e11895c045.mov

**Comment by dprokop** [comment] 2021-03-26 14:46
@aocenas can O11y squad take a look at this? This ain't react-router related, play ain't on muster but 7.5. I also couldn't reproduce this locally agains latest master, maybe there is something in Explore that I'm not aware of.

**Comment by aocenas** [comment] 2021-03-29 13:59
This is supper weird. So far seems like the behavior is sort of random. I tried it on play and it was consistent few times but since then I cannot reproduce it there. Locally on the same commit, I got that once in like 20 tries clicking around.

Interesting thing is that right now on play even though the transition works. When I go to Explore and then back (via browser button) I get url like this: `https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1&left=%5B%22now-1h%22,%22now%22,%22graphite%22,%7B%7D%5D`. The query params `left=...` is something from Explore which should not be there when going back to Dashboard. So there is definitely something going on with the navigation, problem is locally right now I don't get this at all so no idea what is wrong. Could be some cache/local storage thing that could be refreshed?

@dprokop The router change is going to be in v8 right? Also do you get this right now in play or @oanamangiurea? Not sure if to treat this as something transient that wan't happen after v8 anyway. Or am I just (un)lucky that I don't see it now?

**Comment by eamonryan** [comment] 2021-03-30 20:50
@aocenas I am seeing this too in another internal environment (at GL) - the behaviour seems to be that when it occurs, the datasource selected is whatever the "default" datasource is (in my case, Prometheus rather than Graphite).

It seems to not occur on the same panel again after the first time, until you go and try some other panels - I went in a loop of about 6 panels and it kept occurring very frequently.

**Comment by aocenas** [comment] 2021-03-30 21:43
Checked with @eamonryan on a call and so far this is weird, the same dashboard for me, it happened once while clicking on it for 5min. For @eamonryan it seemed like maybe every second click. Tried firefox (which @eamonryan is using) still the same for me. I would guess it is some race condition, probably as a result of one of these refactors https://github.com/grafana/grafana/issues/28535.

**Comment by aocenas** [comment] 2021-04-01 11:12
hmm not sure why gh does not close this automatically.

**Closed by aocenas** 2021-04-01 11:12 UTC
Labels: area/explore, type/bug
