### ISSUE TITLE
Value mapping on datetime fail

### ISSUE THREAD

**Issue by byte-opps** [grafana/grafana#38583] opened 2021-08-26 10:58 UTC
i have a SQL DB source with a datetime column. I use grafana to show the latest datetime and and the standard options to unit "from now" this gives some thing like '10 Hours ago' Great. Now i want the colour to change if more the 5 hours and lesst then 12 and if more then  12 another colour etc. using the value mapping i set these ranges. But the text never changes colour(or the text replacement). appears that the value is not matching but there is no way to know what its trying to do.

Also i note that the date time with out the units changed to "from now" so displaying the date and time value doesn't change with the value mappings or the threashold colours or the preset scales. i can get the colours to change by adding thresholds to 987656787654567 massive values but i don't see how these relate to the date and time (epocs or seconds) seeams to be a string to value or length of string ? I don't know that i am comparing it to. not easy to use.

**Comment by byte-opps** [comment] 2021-08-31 08:06
Thanks for your reply, 

I have attached the pannel JSON which draws data from MSsql server, column type datetime. The pannel is a stat pannel. it shows at the moment 16 hours ago which is great, the difference in time from "now" to the "data". So now I would like to make the colours change depending on this calucated age. I have tried all settings, and thresholds. 

```
select dt_start
from [datafeed].[pull].[audit_data] 
where dt_start BETWEEN '2021-07-28T16:25:53Z' AND '2021-08-27T16:25:53Z'  
```
```

```

```  
{
  "id": 8,
  "gridPos": {
    "h": 2,
    "w": 8,
    "x": 0,
    "y": 0
  },
  "type": "stat",
  "title": "Last run time",
  "datasource": "squirrel",
  "pluginVersion": "8.1.1",
  "fieldConfig": {
    "defaults": {
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "mappings": [
        {
          "options": {
            "from": 0,
            "result": {
              "color": "green",
              "index": 0,
              "text": "recent"
            },
            "to": 5
          },
          "type": "range"
        },
        {
          "options": {
            "from": 9,
            "result": {
              "color": "yellow",
              "index": 1
            },
            "to": 24
          },
          "type": "range"
        },
        {
          "options": {
            "from": 24,
            "result": {
              "color": "red",
              "index": 2
            },
            "to": 1000
          },
          "type": "range"
        }
      ],
      "color": {
        "fixedColor": "#FF9830",
        "mode": "continuous-GrYlRd"
      },
      "decimals": 1,
      "displayName": "time since last load",
      "unit": "dateTimeFromNow"
    },
    "overrides": []
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "last"
      ],
      "fields": "/.*/"
    },
    "orientation": "auto",
    "text": {},
    "textMode": "value",
    "colorMode": "value",
    "graphMode": "area",
    "justifyMode": "center"
  },
  "targets": [
    {
      "alias": "",
      "format": "table",
      "queryType": "randomWalk",
      "rawSql": "select dt_start\nfrom [datafeed].[pull].[audit_data] \nwhere $__timeFilter(dt_start)",
      "refId": "A"
    }
  ]
}
```

**Comment by mckn** [comment] 2021-09-06 08:34
@byte-opps thanks for appending the panel.json. However I can't really see where the issue is and you have not provided any reproduction steps.

When I have a look at this it looks like the `dt_start` is a `DateTime` value and what you really want to query for is the differens between that value and `now`, right? The standard options that you are using will only present the value and no used by the value mappings or threshold. So that is probably why you are not getting the expected behavior.

```sql
SELECT 
      TIMESTAMPDIFF(HOUR, dt_start, GETUTCDATE()) AS hours_since_last_run
FROM
      [datafeed].[pull].[audit_data]
WHERE
      $__timeFilter(dt_start)
```

In the future: it sounds to me like this is something you should post on the community or in our public slack channel.

https://community.grafana.com/
https://slack.grafana.com/

I will close this issue due to not being an issue with the application but more a question on how to use it.

**Closed by mckn** 2021-09-06 08:34 UTC
Labels: needs more info

**Comment by byte-opps** [comment] 2022-05-09 14:05
Seems like you don't understand me, your own product has a calculate different from now (which works fine) but the tresholds are crazy numbers to change the colour of the text. 
![image](https://user-images.githubusercontent.com/61595443/167427622-81d4504d-8607-4af5-84e0-52588e8cb35f.png)
