### ISSUE TITLE
Alerting: Cannot Select Any "Alert Instance" When Creating a Notification Template

### ISSUE THREAD

**Issue by jadeblock** [grafana/grafana#75391] opened 2023-09-25 19:11 UTC
### What happened?

I recently tried creating a custom notification template to send to my team based on newly created alerting rules I have set up. 

I have two rules created: 
![image](https://github.com/grafana/grafana/assets/109608134/ae0775a8-b4b4-48da-98dd-7f18860d1eda)

When trying to create a notification template, under the "Payload Data" window there is a "Select alert instances" button. When I select this button, a window displays with a search box to "Select an alert rule to get a list of available instances." However, nothing ever populates in the drop down. 
![image](https://github.com/grafana/grafana/assets/109608134/0eb06a7f-0654-48d7-a92b-1d7a1406e213)

### What did you expect to happen?

Based on the text of the [Create notification Templates > Preview notification templates section](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/create-notification-templates/#preview-notification-templates) documentation page, I was expecting a drop down of alert rules that matched my search query, and that I could then add the alert instance to the payload data. 

### Did this work before?

N/A

### How do we reproduce it?

1. Click "add template" under the Contact Points page
2. Click "select alert instances" 
3. Search for any alert instance

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: "10.1.1"
OS: Windows 10 Pro
Browser: Chrome

### Grafana platform?

None

**Comment by craig-boman** [comment] 2023-09-25 19:17
Confirmed this is also an issue for me.

**Comment by craig-boman** [comment] 2023-09-25 19:20
Duplicates https://github.com/grafana/grafana/issues/74923

**Comment by tonypowa** [comment] 2023-09-27 10:17
hi @jadeblock 
thanks for reporting this issue

as @craig-boman  pointed out, this is a known issue 
you can subscribe to the other issue to get updates
marking as /duplicate of #74923

**Closed** 2023-09-27 10:19 UTC
Labels: bot/duplicate
