### ISSUE TITLE
Postgres $__timeGroup macro returns "pq: column "METRIC" does not exist"

### ISSUE THREAD

**Issue by anriqing** [grafana/grafana#12230] opened 2018-06-11 14:09 UTC
Please include this information:
### What Grafana version are you using?
5.2.0-pre1
### What datasource are you using?
postgresql
### What OS are you running grafana on?
centos 7.0
### What did you do?
My query with $__timeGroup macro is:
```sql
SELECT
  $__timeGroup("GMT_CREATED",'24h', 0),
  COUNT(ID) as "value",
  REGION_NAME as "metric"
FROM 
  sub_change_order_do
WHERE
  $__timeFilter("GMT_CREATED") AND
  REGION_NAME IN ($region)
GROUP BY time, metric
ORDER BY time
```

Which generates the following sql:
```sql
SELECT
  (extract(epoch from "GMT_CREATED")/86400)::bigint*86400 AS time,
  COUNT(ID) as "value",
  REGION_NAME as "metric"
FROM 
  sub_change_order_do
WHERE
  "GMT_CREATED" BETWEEN '2018-06-01T06:59:49Z' AND '2018-06-08T06:59:49Z' AND
  REGION_NAME IN ('OpsTools_Delta')
GROUP BY time, metric
ORDER BY time
```

However, both grafana and my database returns "pq: column "METRIC" does not exist". Where am I wrong?

**Comment by marefr** [comment] 2018-06-12 08:31
Duplicate of #12197

**Closed by marefr** 2018-06-12 08:31 UTC
