### ISSUE TITLE
Text box template variable doesn't work properly without a default value

### ISSUE THREAD

**Issue by davewat** [grafana/grafana#13666] opened 2018-10-14 14:46 UTC
Please include this information:
### What happened instead? The text of $variablename was passed instead

New Textbox variable is promising, but unable to get it to work - the variable name is passed in the metric query, as opposed to the value that is entered.  Screenshots showing contant passed correctly, but textbox variable not passed:

![grafana53_contant_works](https://user-images.githubusercontent.com/35579731/46918252-0a562400-cf9e-11e8-95f6-1437332499fc.PNG)
![grafana53_contant_works2](https://user-images.githubusercontent.com/35579731/46918254-0e824180-cf9e-11e8-9d2c-deea70c12945.PNG)
![grafana53_textbox_fails](https://user-images.githubusercontent.com/35579731/46918257-12ae5f00-cf9e-11e8-8d6f-3e8cf4a1ea1c.PNG)
![grafana53_textbox_fails2](https://user-images.githubusercontent.com/35579731/46918258-15a94f80-cf9e-11e8-82c0-370537a75927.PNG)

**Comment by torkelo** [comment] 2018-10-15 05:29
That is very strange, unable to replicate on v5.3

![image](https://user-images.githubusercontent.com/10999/46931555-fa951900-d04b-11e8-8ab8-6ff4a7f29368.png)


Are you sure you are running v5.3 and not v5.2 ?

**Comment by bolek2000** [comment] 2018-10-17 08:01
I have the same problem. Browser cache clear doesn't help here. I had the case where in one Dash the variable was detected as a variabel an in another dash not (in the same browser). After updating to 5.3.1 the problem is in both dashboards, also in the one that worked before with 5.3

**Comment by bolek2000** [comment] 2018-10-18 03:02
I found out, that this problem is present, if I have the default value of the text box empty (what we need) and then add the variable to the where clause of a metric. In the first place I get "No data" and the Query Inspector shows pathlevel1" =~ /$freetext/. Then when I type in the first text in the box and hit reload of the webpage then the filter is noticed as a variable and I get the data I expected.
From then on it seems to work, even though the variable doesn't turn blue in the metrics edit tab. But in another Dash it does turn blue. So there seems to be something weird with noticing the variable as a variable. Note that we need to use /$freetext/ not /^$freetext$/ , because we want to have an empty default that matches '.*' in regexp. /^$freetext$/ actually does turn blue in the metrics edit tab.

**Comment by bolek2000** [comment] 2018-10-18 03:15
Later on I saved the dashboard again and now the variable also turned blue, where it wasn't before ??

**Comment by marefr** [comment] 2018-10-18 11:54
@bolek2000 confirmed that text box template variable doesn't work properly when a default value is not provided. Thank you!

**Comment by davewat** [comment] 2018-10-22 16:08
This PR will resolve the on empty value issue (on empty is not the same as default): #13752

**Comment by marefr** [comment] 2018-10-23 11:40
@davewat thanks. However we'll need to include a fix for this bug in patch release so we're going to merge #13791 first and your PR would continue to target a different issue.

**Comment by davewat** [comment] 2018-10-23 12:04
Thanks @marefr - makes sense to fix the bugs first!  I'll resync with master after.

**Closed** 2018-10-23 12:05 UTC
Labels: comp: dashboard/templating, type: bug

**Comment by avlitman** [comment] 2020-12-10 11:21
Hi I hit the same issue, was the fix implemented in one of the versions?
