### ISSUE TITLE
Alerting : Customized notifications

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#5993] opened 2016-09-08 15:30 UTC
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Alerting is cool but adding customized notifications would be a nice to have:

- Customized subject (including keyword for template variables)
- Customized body (including keyword for template variables)
- Customized headers in order to add header to store an API key (for example) : OVH is having an API that needs this key (see https://community.runabove.com/kb/en/queue/dbaas-queue-https.html)
- Customized slack body

**Comment by torkelo** [comment] 2016-09-10 10:24
what do you mean by `including keyword for template variables` and can you please describe `Customized slack body`

**Comment by sbouchex** [comment] 2016-09-10 10:42
About "including keyword for template variables": Since the alert is emitted from a Dashboard, why not giving the possibility to customize the notification message with data coming from the dashboard (like Template variables) and from the graph (graph title...)

About "slack body": Slask offers the ability to full customize the message (see https://api.slack.com/incoming-webhooks), so default message should be the current one and the user may customize it to specify the channel, icon, users...). Passing a json structure should be fine. Of course, with keywords (see above)

**Comment by torkelo** [comment] 2016-09-10 12:17
You can customize the slack message in the notifications tab.  You can specify a message (below send to).  As for channel and icon that is something you specify when you create the webhook url. 

Template variables are not supported in alerting queries. But Graph title could be available as a variable I guess.

**Comment by sbouchex** [comment] 2016-09-12 15:04
About slack, creating several integration url gives you this ability but you have to create one url per message type (one per channel for example) where it would be possible to specify in the JSON part with a line like : "channel": "#{VAR}" where {VAR} would be derived from the dashboard emitting the alert.

**Comment by bergquist** [comment] 2016-10-19 08:26
Kinda dupe of https://github.com/grafana/grafana/issues/5848 Closing this one to reduce the amount of open issues.

**Closed by bergquist** 2016-10-19 08:26 UTC
Labels: comp: alerting, comp: alerting/notifications

**Comment by helletheone** [comment] 2017-05-23 13:12
Sorry but is this now possible a Customized subject for E-Mail? or only for slack?

**Comment by torkelo** [comment] 2017-05-23 13:56
https://github.com/grafana/grafana/issues/5848 is still open

so no change to email notifications

**Comment by robertchen** [comment] 2017-12-15 20:50
for a basic alerting system, alert message should says it is from which host/IP. But strangely, I find grafana alert could not do this?

See we have 30 SIT machines, each runs a stack with a grafana. Each collect metrics with same telegraf.

The alert message should says: Alert is from sit1.domain.com  ...

**Comment by wschenbuer** [comment] 2018-06-15 10:47
@torkelo Hello I am a beginner user of Grafana, but i am wondering if it is possible to add variables(such as panel title, current date time, or other Datas about panel) into notification messages so when the notification message is sent to my email i could see those data directly in my E-mail.

**Comment by NETESairam** [comment] 2018-11-29 20:07
trying to send a slack custom message like a button, it displays as a plain JSON message on slack. Any help?

**Comment by robtcallahan1** [comment] 2019-03-29 19:25
Any progress on this? I'm using Grafana v6.5 and I see now way to customize the message body using data from chart and I'm not finding anything on the web about it. Please help.

**Comment by James00001** [comment] 2019-04-04 19:23
I would love to be able to insert the current threshold of the alert into the text of the message.

I have to write my alert messages in vague terms like "The metric exceeded the allowed threshold" instead of being able to write "The metric exceeded [[threshold]]"

Especially since it is so easy to change that threshold just by dragging the alert line in the graph. What if you change the threshold, but don't realize that the alert text mentioned the old original value?

**Comment by yellochicken** [comment] 2019-04-08 09:00
I´m looking for ways to automate messages with information used to Create the graphs. Are yet to find any information on this on the web. Anyone?

**Comment by crysalis** [comment] 2019-04-17 10:58
Any news about how to customize slack message body?

**Comment by MaliNatan** [comment] 2019-10-30 12:47
Hi,
Is there a way to add details from the log to the notification (that sent to the email), using any code?

**Comment by mikailyetkin** [comment] 2020-01-21 16:14
> Hi,
> Is there a way to add details from the log to the notification (that sent to the email), using any code?

I assume it is still not possible, i am also looking for the same thing. Anyone knows a solution ?

**Comment by waqark3389** [comment] 2020-07-23 17:40
Why was this closed. It is very specific to customising the message

**Comment by wileyj** [comment] 2020-08-25 23:50
> Why was this closed. It is very specific to customising the message

https://github.com/grafana/grafana/issues/5848
https://github.com/grafana/grafana/pull/6436
