### ISSUE TITLE
Feature request: Template variables in thresholds

### ISSUE THREAD

**Issue by KristianLyng** [grafana/grafana#21961] opened 2020-02-06 09:08 UTC
**What would you like to be added**:

Dynamic thresholds in graph panels, based on template variables.

**Why is this needed**:

Example: Network interfaces can have varying speeds, and policy might dictate different thresholds for what is acceptable fill grade. E.g.: If traffic regularly exceeds 50% of capacity, an upgrade is planned.

**Comment by liamdiprose** [comment] 2020-02-11 00:50
Possible duplicate with #4929?

**Comment by marefr** [comment] 2020-02-11 11:09
Duplicate of #922

**Closed by marefr** 2020-02-11 11:09 UTC
Labels: area/dashboard/templating, type/feature-request
