### ISSUE TITLE
Unable to access trace from the Loki traceID button

### ISSUE THREAD

**Issue by berabulut** [grafana/grafana#41451] opened 2021-11-09 06:58 UTC
**What happened**:
When trying to access a trace from a log using TraceID, Grafana doesn't query Tempo automatically.

**What you expected to happen**:
Grafana uses TraceID provided in the log after clicking the blue button to query Tempo automatically. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Send your trace to Tempo.
2. Log your trace's TraceID to Loki.
3. Query Loki to find your logs.
4. Click blue button which appears below TraceID field of log.

**Anything else we need to know?**:
I am using Grafana Cloud, so I don't think my own configuration broke Grafana. Tested the bug in two different browsers.

![Grafana-bug](https://user-images.githubusercontent.com/45367283/140876386-22c4b4f8-1879-41e9-8e1f-95462a08e2db.gif)

**Comment by ashharrison90** [comment] 2021-11-09 16:14
hi @berabulut 👋 

just to clarify, is the issue here that you're expecting the trace id to be prepopulated with the correct value and immediately query when you click the blue button?

@grafana/observability-squad if that's the case, not sure if this is a bug or feature request. defer to your superior wisdom 🧙‍♂️ 🧙‍♀️

**Comment by berabulut** [comment] 2021-11-09 16:37
@ashharrison90 

> just to clarify, is the issue here that you're expecting the trace id to be prepopulated with the correct value and immediately query when you click the blue button?

Yes, it was working as expected until couple of days ago.

**Comment by ashharrison90** [comment] 2021-11-09 16:45
@berabulut ah perfect, thanks for the speedy response 👍 

bug then 🐛

**Comment by ivanahuckova** [comment] 2021-11-11 09:35
I have tried to reproduce this on main branch, but it works as expected. @berabulut Could you please share what version of Grafana are you using and if there are any errors in the console?

**Comment by berabulut** [comment] 2021-11-11 12:42
> I have tried to reproduce this on main branch, but it works as expected. @berabulut Could you please share what version of Grafana are you using and if there are any errors in the console?

Grafana version: v8.2.3-40566 (3b8be57b4f)

Can't see any errors in the console related to this. Nothing is happening when clicking the button.
![Grafana-bug2](https://user-images.githubusercontent.com/45367283/141299926-0f3024f1-100b-448a-a090-e0804213e5b3.gif)

**Comment by ivanahuckova** [comment] 2021-11-11 12:59
Thank you for the information. I'll be looking into this.

**Comment by connorlindsey** [comment] 2021-11-16 15:22
@berabulut Could you share your derived fields configuration for the Loki datasource you're using?

**Comment by berabulut** [comment] 2021-11-16 15:38
> @berabulut Could you share your derived fields configuration for the Loki datasource you're using?

![image](https://user-images.githubusercontent.com/45367283/142016433-377e80f1-91ac-4fd1-8ecd-24fcdccc85b5.png)

**Comment by berabulut** [comment] 2021-11-16 15:44
With our current version it's working again. 
Grafana version: v8.2.4 (d409b0ca16)

**Comment by connorlindsey** [comment] 2021-11-16 15:59
Thanks for sharing your config. Given that it's now working for you and we were unable to reproduce this reliably, I'm going to close this issue. If you run into it again, please re-open or file another issue. Thanks!

**Closed by connorlindsey** 2021-11-16 15:59 UTC
Labels: type/bug, priority/important-soon, needs more info, datasource/Loki, datasource/Tempo
