### ISSUE TITLE
Feature Request: Export all Dashboards in one go!

### ISSUE THREAD

**Issue by bryanchapman9999** [grafana/grafana#1382] opened 2015-01-23 16:41 UTC
After just exporting all our 50ish dashboards one by one, please can we have a 1 click method to backup dashboards.

Many thanks

**Comment by torkelo** [comment] 2015-01-23 17:25
Yes this will be an easier thing to implement in Grafana 2.0 (that comes with a backend part), until then there is this utility you can use: https://github.com/grafana/grafana-tools/blob/master/grafana-dashboards-backup

**Comment by r3cgm** [comment] 2015-06-11 21:15
+1.  I was able to use the grafana-dashboards-backup tool but it would be great to integrate this directly within Grafana.

**Comment by rmoff** [comment] 2015-08-25 17:27
@torkelo is this implemented in v2.0 yet? I can't find it on the interface. Thanks!

**Comment by torkelo** [comment] 2015-08-25 18:34
The issue is open still, meaning it has not been implemented :)

**Comment by r3cgm** [comment] 2015-08-25 21:23
For what it's worth the grafana-dashboards-backup tool is no longer viable as a workaround.  It was coded to extract dashboards from an Elasticsearch backend but now we have switched to InfluxDB.

**Comment by druchoo** [comment] 2015-10-13 17:14
Is there any way to do this in 2.0/1? I need to import dashboards from our prod 2.0 instance and test them in QA 2.1. There is no direct connectivity between servers.

**Comment by torkelo** [comment] 2015-10-14 22:15
checkout the http api , and there is a grafcli tool that does export / import I think

**Comment by druchoo** [comment] 2015-10-15 20:50
grafcli looks interesting. Too bad it's Python3. I'll have a look at the HTTP API. Another semi related question. Using MySQL database - are there differences between v2.0 and 2.1?

**Comment by torkelo** [comment] 2015-11-06 12:20
dupe of https://github.com/grafana/grafana/issues/936#issuecomment-154372243

**Closed by torkelo** 2015-11-06 12:20 UTC
Labels: type: feature request
