### ISSUE TITLE
Grafana keeps returning 401 if the first query to a datasource fails due to context cancelled

### ISSUE THREAD

**Issue by filewalkwithme** [grafana/grafana#52418] opened 2022-07-18 18:04 UTC
**What happened**:
The first request to `/api/ds/query` (Prometheus data source) failed due to context cancelled, and then Grafana started to returning status `401` to following requests 

**What you expected to happen**:
Grafana should recover after a failed request (context cancelled).

**How to reproduce it (as minimally and precisely as possible)**:
- Start a Grafana server (9.0.3) configured with a Prometheus datasource using BasicAuth
- Using the Explore page, run an arbitrary query agains the Prometheus datasource (for example `up{}`)
- Grafana works normally.
- Restart Grafana server
- Now, It's necessary that the first request to `/api/ds/query` gets context canceled. (more details on how to simulate this at the bottom)
- Grafana will return 401 for all following requests to `/api/ds/query` 

**Anything else we need to know?**:
- This issue seems to happen when:
  - the user sends a request to `/api/ds/query`
  - and the first request fails due to context cancelation
  - I am suspicious that a blank credential is being cached in somewhere, [probably here](https://github.com/grafana/grafana/blob/v9.0.3/pkg/services/pluginsettings/service/service.go#L124).
    - I think this is because [decryption does not seems to be returning an error, even if it fails](https://github.com/grafana/grafana/blob/v9.0.3/pkg/services/pluginsettings/service/service.go#L130)
  - we are seeing the following pattern at logs. 
```
ERROR[07-18|14:37:46] Failed to decrypt secure json data       logger=query_data error="context canceled"
ERROR[07-18|14:37:46] Range query failed                       logger=tsdb.prometheus query=up err="Post \"http://localhost:9090/api/v1/query_range\": context canceled"
INFO [07-18|14:37:46] Request Completed                        logger=context traceID=467f17755cf3bacd userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=127.0.0.1 time_ms=12 duration=12.371748ms size=98 referer="http://127.0.0.1:3000/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-maiconcostay-prom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22up%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D" traceID=467f17755cf3bacd  
```

In order to reproduce this, I have modified [handleQueryData](https://github.com/grafana/grafana/blob/v9.0.3/pkg/services/query/query.go#L117) to force context cancellation for the first 3 requests, this way:
```
var count = 0

func (s *Service) handleQueryData(ctx context.Context, user *models.SignedInUser, parsedReq *parsedRequest) (*backend.QueryDataResponse, error) {
	ds := parsedReq.parsedQueries[0].datasource
	if err := s.pluginRequestValidator.Validate(ds.Url, nil); err != nil {
		return nil, models.ErrDataSourceAccessDenied
	}

	// first 3 requests fail due to request cancellation
	if count < 4 {
		c, cancel := context.WithCancel(ctx)
		ctx = c
		cancel()
	}
	count++
	
	....
```

**Environment**:
- Grafana version: 9.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu / Chrome
- Grafana plugins: N/A
- Others: N/A

**Video**:
https://user-images.githubusercontent.com/1558179/179572509-5708de01-baad-45b0-bcce-87936faa7684.mp4

**Comment by filewalkwithme** [comment] 2022-07-18 23:34
More info:
When the issue happens, the map [s.DecryptedSecureJSONData is nil](https://github.com/grafana/grafana-plugin-sdk-go/blob/47e69cf5883bf01e035729b9b63188630f608fec/backend/common.go#L103)

```
httpSettings.BasicAuthPassword = s.DecryptedSecureJSONData["basicAuthPassword"]
```

**Comment by aocenas** [comment] 2022-07-19 13:30
Although not 100% seems like if that error originated there, it should have been wrapped in https://github.com/grafana/grafana/blob/973b3112d76c9a9286a3694909375cc4b56925da/pkg/services/secrets/database/database.go#L42 which does not seem to be the case.

@filewalkwithme 
If you have access to the logs do you have more context. If I am correct in this originating from that DB call there should probably be this one error message somewhere https://github.com/grafana/grafana/blob/7b40322bbed8677187d5e9b97cba159bb476b2c5/pkg/services/secrets/manager/manager.go#L379

**Comment by guicaulada** [comment] 2022-07-19 16:41
Going to the datasources page and clicking on Save & Test for the Prometheus datasource seems to fix the issue.

**Comment by inf0rmer** [comment] 2022-07-19 17:28
> Going to the datasources page and clicking on Save & Test for the Prometheus datasource seems to fix the issue.

Yes, we think this is the case because Save & Test busts the in-memory cache; unfortunately for a lot of cases in Cloud this mitigation is not possible since the datasource will be provisioned. in these cases only a restart does it, which means the customer can't "self-service" the mitigation.

**Comment by guicaulada** [comment] 2022-07-19 17:48
Oh, I didn't mean it as a form of mitigation, it was mostly extra information to help find the root cause of the issue. :)

**Comment by filewalkwithme** [comment] 2022-07-20 03:40
Hi, more info on this;

Using `git bisect`, I tracked down the issue to [this commit](https://github.com/grafana/grafana/commit/a367ad730c409efa8ac583e3ebcaffbbf54cc7ae)

```
a367ad730c409efa8ac583e3ebcaffbbf54cc7ae is the first bad commit
```

Full `git bisect` log:
```
$ git bisect log
git bisect start
# bad: [14e988bd224ff136988dab62d87f1ca8156e1963] "Release: Updated versions in package to 9.0.1" (#381)
git bisect bad 14e988bd224ff136988dab62d87f1ca8156e1963
# good: [4cafe613e1b33dbf24851f4eb46ef2c5ea246052] Merge pull request #289 from grafana/bump-version-8.4.5
git bisect good 4cafe613e1b33dbf24851f4eb46ef2c5ea246052
# good: [0ab7097abc3ee8de68c6bbaf9e9ccc16180f8658] Chore: Update what's new link (#44782)
git bisect good 0ab7097abc3ee8de68c6bbaf9e9ccc16180f8658
# good: [712b239d5ae685db7e8f9d01d5c8aecca611f0b3] Storage: remove pointer on write path (#47580)
git bisect good 712b239d5ae685db7e8f9d01d5c8aecca611f0b3
# good: [712b239d5ae685db7e8f9d01d5c8aecca611f0b3] Storage: remove pointer on write path (#47580)
git bisect good 712b239d5ae685db7e8f9d01d5c8aecca611f0b3
# bad: [acd31ae9f0f9627ccd2d928ea893ca211aeba4d4] Search: simulate folder mange pages within the playground page (#49041)
git bisect bad acd31ae9f0f9627ccd2d928ea893ca211aeba4d4
# bad: [9e21e4d1c1fdc609ea57a589945af6ec43f4c9e4] Alerting: indicate whether an alertrule is provisioned (#48458)
git bisect bad 9e21e4d1c1fdc609ea57a589945af6ec43f4c9e4
# bad: [9e21e4d1c1fdc609ea57a589945af6ec43f4c9e4] Alerting: indicate whether an alertrule is provisioned (#48458)
git bisect bad 9e21e4d1c1fdc609ea57a589945af6ec43f4c9e4
# good: [dbcaedac6cd02632f37f4494ce2687aef8c01ab2] Implement preference service (#47870)
git bisect good dbcaedac6cd02632f37f4494ce2687aef8c01ab2
# good: [dbcaedac6cd02632f37f4494ce2687aef8c01ab2] Implement preference service (#47870)
git bisect good dbcaedac6cd02632f37f4494ce2687aef8c01ab2
# bad: [53fcb7e1716fca89edef798b817b22e6f9f40cf5] Transformations: Allow more complex regex expressions in `Rename by regex` (#48179)
git bisect bad 53fcb7e1716fca89edef798b817b22e6f9f40cf5
# good: [277a83215c1e20ff8c93768f93edf92d60deee5f] Use jest.fakeTimers instead of mocking Date.now (#48121)
git bisect good 277a83215c1e20ff8c93768f93edf92d60deee5f
# good: [b30d9f2732e3c93ee8f1c83ab66e71bcdb7d285d] Explore: Fix height on horizontal drawer and query inspector (#47832)
git bisect good b30d9f2732e3c93ee8f1c83ab66e71bcdb7d285d
# bad: [53e9bf47db21bace6783f2d0eb777209bcc725c6] Secrets: Implement tests and debug log improvements on unified secrets (#48213)
git bisect bad 53e9bf47db21bace6783f2d0eb777209bcc725c6
# good: [ebe34ddcbaa2f43b112b9f7dfe41c233810ad637] Navigation: Remove the 'active' indicator from the Home icon when collapsed (#48192)
git bisect good ebe34ddcbaa2f43b112b9f7dfe41c233810ad637
# bad: [a367ad730c409efa8ac583e3ebcaffbbf54cc7ae] Secrets: Implement basic unified secret store service (#45804)
git bisect bad a367ad730c409efa8ac583e3ebcaffbbf54cc7ae
# good: [0ca32f0c61473ab4ea25d1c991eeef7befc62a3d] TimeSeries: use positive stacks for 0-valued series (#48197)
git bisect good 0ca32f0c61473ab4ea25d1c991eeef7befc62a3d
# first bad commit: [a367ad730c409efa8ac583e3ebcaffbbf54cc7ae] Secrets: Implement basic unified secret store service (#45804)
```

**Comment by guicaulada** [comment] 2022-07-20 18:34
I will try to backport that commit to 9.0.x to see if the issue is fixed.

**Comment by joanlopez** [comment] 2022-07-21 07:04
> I noticed the problem is already fixed on main and decided to use `git bisect` in reverse to find the first good commit ([9aa6ce2](https://github.com/grafana/grafana/commit/9aa6ce2a506643816c92a5ec690c9b988af0919f)).

Yeah, that's exactly what I mentioned [here](https://github.com/grafana/support-escalations/issues/3240#issuecomment-1184490751). I guess that message got lost due to the multiple places we were tracking this issue at.

Thanks a lot for taking care of it! 🙏🏻

**Comment by hairyhenderson** [comment] 2022-07-25 14:56
@guicaulada given #52557 is merged, can this issue be closed?

**Comment by guicaulada** [comment] 2022-07-25 15:39
> @guicaulada given #52557 is merged, can this issue be closed?

Done! 👍

**Closed** 2022-07-25 15:39 UTC
Labels: area/backend
