### ISSUE TITLE
Grafana should distribute evaluations across IntervalSeconds instead of the tick duration

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#56386] opened 2022-10-05 12:04 UTC
**What happened**:

In Grafana the evaluation of alert rules are distributed over a 10 second period (the tick interval). This distributes the volume of queries a datasource might have to respond to, and also subsequent writes to the database.

However, some users have 1000s, or even 10,000s of alert rules with the same `IntervalSeconds`. If we use 5000 alert rules set to evaluate once per 5 minutes as an example. Grafana will wait 5 minutes and then attempt to evaluate all 5000 alert rules within a 10 second period.

**What you expected to happen**:

Grafana should distribute the evaluation over `IntervalSeconds`, such that in the example above all 5000 alert rules are evaluated over a 5 minute period.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by yuri-tceretian** [comment] 2022-10-07 16:43
I think this is a duplicate of this issue https://github.com/grafana/grafana/issues/53744

**Closed** 2022-10-09 22:32 UTC
Labels: type/feature-request, prio/high, area/alerting, effort/large
