### ISSUE TITLE
Add support for hidden table column

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#32590] opened 2021-04-01 10:30 UTC
**What would you like to be added**:
With tables, you can use one cell value in another cell links, but it only works if that cell is used.
Need a way to use that cell value, but without showing that column.
As a work around, having a column with width 0 

**Why is this needed**:
My use case is alerts. There are multiple labels on the alert, I use two of them for a cell link,
one with a code to the page, another one with a full description of the alert (that is bigger than what we have in the table)
This is an example of how the table should look:
![image](https://user-images.githubusercontent.com/2118079/113281274-fe858600-92ed-11eb-8846-1f4a567cab37.png)
In fact it looks like this:
![image](https://user-images.githubusercontent.com/2118079/113281381-22e16280-92ee-11eb-9097-556789fd9eef.png)

**Comment by Elfo404** [comment] 2021-04-01 10:33
Duplicate of #24092

**Closed by Elfo404** 2021-04-01 10:33 UTC
