### ISSUE TITLE
Annotations are broken

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#50849] opened 2022-06-15 08:46 UTC
**What happened**:
Over the past few releases the annotations state keep deteriorate (see also #49515)

Annotations are an important tool, that used to (mostly) work. Since the move to 8.x and the move to the time-series panels they are broken.
**What you expected to happen**:
To make it clear I showed on the graph the Prometheus function of the annotations.
What should have happend that for each point in the graph there would be an annotation.

**How to reproduce it (as minimally and precisely as possible)**:
Here are two examples, same graph, both does not work as they should but in a different way:

version 8.5.2
![image](https://user-images.githubusercontent.com/2118079/173780344-8d9dfdcf-8551-420c-892e-7ebe2301cc1e.png)

Version 9.0.0
![image](https://user-images.githubusercontent.com/2118079/173779120-62eecd55-fc21-418c-8642-09cbe07e7d88.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.x and up
- Data source type & version: prometheus
- OS Grafana is installed on: docker
- User OS & Browser: chrome
- Grafana plugins: NA
- Others:

**Comment by gelicia** [comment] 2022-06-15 12:13
@amnonh Just trying to understand your two tickets - Looking at the other ticket, the annotations that should have been a range were instead one on each point. And here, they are a range and should be individual. Is that correct?

I may mark this ticket as a duplicate of the other one and try to combine them before assigning them to a team to look at, but I want to be sure we have all the information we need to replicate the issue you're seeing.

**Comment by amnonh** [comment] 2022-06-15 12:31
@gelicia no, two different issues, in the previous ticket, annotations should have been a range but were marked as individual.
In this case annotations are missing, as you can see the graph in the panel is the annotation function, so for each point there should have been an annotation, but instead, only some of the points has annotations.

**Comment by gelicia** [comment] 2022-06-15 14:59
@amnonh Can you please provide the annotation query for the example in this ticket?

**Comment by Arturski** [comment] 2022-10-11 14:45
I have the same problem with elastic search queries the annotation query goes through ok but the dashboard only renders half or less of the panel

**Comment by amnonh** [comment] 2022-11-03 19:23
Server/proxy

**Comment by gtk-grafana** [comment] 2022-12-13 18:31
@amnonh Are you still having this issue with 9.3? I don't think I fully understand the issue you are having, and what is the desired functionality in this situation?

For this query: `changes(counters_requests{server="backend-01"}[$__rate_interval]) > 0`, with this annotation query: `changes(counters_requests{server="backend-01"}[$__rate_interval]) > 0` with a step size of 1s. I see the following

<img width="834" alt="image" src="https://user-images.githubusercontent.com/109082771/207412691-f14cc746-f516-4ebe-be24-e686a24f5232.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/109082771/207412827-dca7d180-4717-4774-bc35-f600e2a461ae.png">

And I see an annotation for each min-step of the times-series. If I tweak the min-step of the annotation query 

If I change the step-size to auto, I see that the annotation ranges display until I zoom out a bunch
<img width="842" alt="image" src="https://user-images.githubusercontent.com/109082771/207415520-71433d48-a7a7-451c-aeb9-797b46d18e1e.png">.

What are your values of the min-step for the annotation query, and what happens if you use the `$__rate_interval` variable instead of hardcoding the interval to 30s in your annotation query?
<img width="777" alt="image" src="https://user-images.githubusercontent.com/109082771/207416004-d96c0366-1542-4f44-959e-f6bbf8828252.png">

Thanks for taking the time to submit this issue, and sorry for not getting back to you sooner!

**Comment by gtk-grafana** [comment] 2022-12-13 20:48
A working example would be super helpful in reproducing/tracking this down, If you can reproduce this locally on Grafana 9.3.2, go ahead and pull a debug snapshot of that panel by clicking on the panel title, selecting **More** > **Get help**
<img width="430" alt="image" src="https://user-images.githubusercontent.com/109082771/207420128-fd4502ab-7b8b-49dc-9262-e014deca2805.png"> Then click the Dashboard button.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/109082771/207420685-5fc00894-3d39-48aa-9006-5a40c5b89f5c.png">
This will provide a complete snapshot of that current panel, including annotations.

**Comment by alin-at-dfinity** [comment] 2023-03-10 08:54
To provide some more context, I also noticed this issue with Grafana 8.5.11. I have a dashboard with 4 annotations that used to work fine with older versions of Grafana. With Grafana 8.5.11, however, it looks as if the query resolution is quite a bit lower than it's supposed to.

E.g. in the chart below, there should be a sequence of red, green, yellow and blue annotations for every spike in the chart. This is obviously not the case.

![Screenshot from 2023-03-10 09-33-10](https://user-images.githubusercontent.com/58422065/224265685-534ada6b-e01a-48f1-be42-1ad5ddc0491c.png)

If I inspect the network traffic, the Grafana frontend appears to trigger the right queries -- e.g. `{"from":"1678417586000","to":"1678421186000","queries":[{"expr":"1000 * xyz","range":true,"instant":false,"exemplar":false,"interval":"10s","queryType":"timeSeriesQuery","refId":"X","datasource":{"type":"prometheus","uid":"000000001"},"legendFormat":""}]}`, note the `"interval": "10s"` -- but it is quite clear that the results are not the same as the equivalent Prometheus query.

Loading the query in Prometheus -- same time range, 10 second step i.e. `http://prometheus/graph?g0.expr=1000%20*%20xyz&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h&g0.end_input=2023-03-10%2006%3A06%3A26&g0.moment_input=2023-03-10%2006%3A06%3A26&g0.step_input=10` -- yields all the expected samples.

It seems very much as if Grafana enforces a lower bound on the `step` argument that it passes to Prometheus. The data source I'm using is configured with a 10 second resolution, but using any step below `40s` for my annotations appears to yield the exact same (partial) results. If I go over `40s`, more/other samples get dropped.

**Comment by gtk-grafana** [comment] 2023-06-09 15:29
@HenrikLindholm86 can you provide a debug snapshot of your panel that is exhibiting this error? Can you reproduce this issue on a newer version of Grafana, or play.grafana.org?
Also what is the value of your min step in the annotation query?

<img width="126" alt="image" src="https://github.com/grafana/grafana/assets/109082771/4c3c6595-b2d1-4880-8466-9e288735cef4">

**Comment by alin-at-dfinity** [comment] 2023-06-13 09:38
[Here](https://snapshots.raintank.io/dashboard/snapshot/fklEgczb2McpVBlPMQjGylDoroH78b37)'s a sample snapshot, obtained with the latest version of Grafana. The min step in this case is `10s`. And the panels are wide enough for the graphs to be displayed with 10 second resolution.

Here is the output of the exact query for one of the annotations (the green _Compute manifest end_) run directly against Prometheus' `/api/v1/query_range` endpoint:
```json
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "ic": "mercury",
          "ic_node": "3jfof-q5mok-apuqv-du4j7-jqe6i-iga26-zim7o-fcmxg-la35o-5hnqj-tqe",
          "ic_subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
          "instance": "[2001:438:fffd:4a:6801:36ff:fee1:dd18]:9090",
          "job": "replica",
          "op": "compute_manifest"
        },
        "values": [
          [
            1686641680,
            "1686641680000"
          ],
          [
            1686642150,
            "1686642150000"
          ],
          [
            1686642610,
            "1686642610000"
          ],
          [
            1686643080,
            "1686643080000"
          ],
          [
            1686643550,
            "1686643550000"
          ],
          [
            1686644020,
            "1686644020000"
          ],
          [
            1686644480,
            "1686644480000"
          ],
          [
            1686644950,
            "1686644950000"
          ]
        ]
      },
      {
        "metric": {
          "ic": "mercury",
          "ic_node": "72zkj-5lvrn-h34e6-glnwu-zzxom-p4gp4-5g7xi-jrh3y-2lpa7-gdrai-aqe",
          "ic_subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
          "instance": "[2001:920:401a:1706:6801:57ff:fe10:6658]:9090",
          "job": "replica",
          "op": "compute_manifest"
        },
        "values": [
          [
            1686641670,
            "1686641670000"
          ],
          [
            1686642140,
            "1686642140000"
          ],
          [
            1686642600,
            "1686642600000"
          ],
          [
            1686643070,
            "1686643070000"
          ],
          [
            1686643540,
            "1686643540000"
          ],
          [
            1686644010,
            "1686644010000"
          ],
          [
            1686644470,
            "1686644470000"
          ],
          [
            1686644940,
            "1686644940000"
          ]
        ]
      }
    ]
  }
}
```

As you can see, there are exactly 8 results for each instance (as opposed to 2 + 4 returned by Grafana).

If I round the time range ends to 30 seconds and reduce the step to 30 seconds, I get the exact same 2 + 4 samples from Prometheus:

```json
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "ic": "mercury",
          "ic_node": "3jfof-q5mok-apuqv-du4j7-jqe6i-iga26-zim7o-fcmxg-la35o-5hnqj-tqe",
          "ic_subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
          "instance": "[2001:438:fffd:4a:6801:36ff:fee1:dd18]:9090",
          "job": "replica",
          "op": "compute_manifest"
        },
        "values": [
          [
            1686642150,
            "1686642150000"
          ],
          [
            1686643080,
            "1686643080000"
          ]
        ]
      },
      {
        "metric": {
          "ic": "mercury",
          "ic_node": "72zkj-5lvrn-h34e6-glnwu-zzxom-p4gp4-5g7xi-jrh3y-2lpa7-gdrai-aqe",
          "ic_subnet": "jtdsg-3h6gi-hs7o5-z2soi-43w3z-soyl3-ajnp3-ekni5-sw553-5kw67-nqe",
          "instance": "[2001:920:401a:1706:6801:57ff:fe10:6658]:9090",
          "job": "replica",
          "op": "compute_manifest"
        },
        "values": [
          [
            1686641670,
            "1686641670000"
          ],
          [
            1686642600,
            "1686642600000"
          ],
          [
            1686644010,
            "1686644010000"
          ],
          [
            1686644940,
            "1686644940000"
          ]
        ]
      }
    ]
  }
}
```

Which suggests that Grafana is internally limiting the min step for annotations to 30 seconds.,

**Comment by paulwe** [comment] 2023-07-19 20:49
<img width="834" alt="207412691-f14cc746-f516-4ebe-be24-e686a24f5232" src="https://github.com/grafana/grafana/assets/125901/5aac0079-fe60-4076-9437-f5b91606e721">

Is it possible to render region annotations as a solid shaded area at higher time scales? The repeated vertical lines make graphs unreadable.

**Comment by leeoniya** [comment] 2023-07-19 20:59
this has been requested before.

we would have to provide a pixels threshold setting that controls this clustering behavior.

**Comment by bohandley** [comment] 2024-06-11 14:34
Hi all. Thank you for your input on this behavior in Prometheus annotations. This is a known issue and is being tracked here
https://github.com/grafana/grafana/issues/63687

I am closing this as a duplicate. Please follow the above issue. Thank you!

**Closed by bohandley** 2024-06-11 14:34 UTC
Labels: area/annotations, prio/medium, datasource/Prometheus
