### ISSUE TITLE
Flexible alerting condition base on different time

### ISSUE THREAD

**Issue by amirarsalan** [grafana/grafana#29862] opened 2020-12-15 22:47 UTC
**What would you like to be added**:
I need a new condition type that I could set alert for a range of time.

**Why is this needed**:
For example:
I have a panel and set an alerting for that:

> when: max() **of** query(A, 1m, now) **IS ABOVE**  100

 But this alert must notify me for 8 PM to 12 AM.

after the time I need to notify me by another condition like (12 AM to 8 PM ):

> when: max() **of** query(A, 1m, now) **IS ABOVE**  50

It's just a simple example, but I think this feature can be necessary.

**Comment by hugohaggmark** [comment] 2020-12-16 07:22
Duplicate of #6592

**Closed by hugohaggmark** 2020-12-16 07:22 UTC
