### ISSUE TITLE
Alert not working when sql statement has template variable

### ISSUE THREAD

**Issue by vpanchal72** [grafana/grafana#17844] opened 2019-07-01 11:20 UTC
Case 1:Not Working when  farm = '${Farm:raw}' in SQL Statement >> Test rules shows message:"Condition: Eval: false, Query Returned No Series (reduced to null/no value)"
Case 2: Not Working (same as Case1)  farm = '$Farm' in SQL Statement >> Test rules shows message:"Condition: Eval: false, Query Returned No Series (reduced to null/no value)"
Case 3: Working when farm = 'Boston' in SQL Statement >> Test rules shows message:"Condition[0]: Eval: false, Metric: Attempted Build, Value: 1.000"

SQL Statement 
SELECT
  date_trunc('m', created_at_utc  at time zone 'UTC') AS time, 
  attemptBuild as "Attempted Build" 
FROM rtc_history_log_table
WHERE
  $__timeFilter(created_at_utc) AND farm = '${Farm:raw}'  
GROUP BY 1, 2   
ORDER BY 1,2

Alert Tab
![image](https://user-images.githubusercontent.com/52157263/60432549-32ff7600-9c20-11e9-8352-64b5bc72530f.png)

Variable Settings
![image](https://user-images.githubusercontent.com/52157263/60432589-43afec00-9c20-11e9-88cc-943d56df6059.png)

![image](https://user-images.githubusercontent.com/52157263/60432602-490d3680-9c20-11e9-8f99-003b14b713f8.png)

![image](https://user-images.githubusercontent.com/52157263/60432614-50344480-9c20-11e9-8b8b-a6544172e23e.png)

**Comment by marefr** [comment] 2019-07-01 11:30
Duplicate of #6230

**Closed by marefr** 2019-07-01 11:30 UTC
