### ISSUE TITLE
[Feat] View Loki log entries as Annotations

### ISSUE THREAD

**Issue by lorenwest** [grafana/grafana#18579] opened 2019-08-15 20:16 UTC
**What would you like to be added**:
I'd like to view tagged Loki log entries as dashboard annotations

**Why is this needed**:
Loki stores valuable event information, and I'd like to associate it with my panels as annotations

**Comment by lorenwest** [comment] 2019-08-15 20:17
This may be a dup of #17762 - not enough information in that thread to know if it's a dup or if this is a different request.

**Comment by lorenwest** [comment] 2019-08-15 20:18
Related to #18578

**Comment by hugohaggmark** [comment] 2019-08-16 05:05
Duplicate of #17762

**Closed by hugohaggmark** 2019-08-16 05:06 UTC
Labels: type/duplicate
