### ISSUE TITLE
[Feature request] Scheduled alerts

### ISSUE THREAD

**Issue by pineur** [grafana/grafana#7188] opened 2017-01-09 12:05 UTC
During weekends and holidays it's sometimes ok that some of the Grafana metrics are lower than usual.

It would be great if one could schedule specific alert not to be active during weekends and holidays.

**Comment by torkelo** [comment] 2017-01-09 13:16
duplicate of https://github.com/grafana/grafana/issues/6592

**Closed by torkelo** 2017-01-09 13:16 UTC
