### ISSUE TITLE
Error changing alert rule folder

### ISSUE THREAD

**Issue by bobemoe** [grafana/grafana#59658] opened 2022-12-01 14:41 UTC
**What happened**:

Trying to move some alert rules to a different folder before deleting old folder. Got error.

**What you expected to happen**:

Rules moved to the specified folder.

**How to reproduce it (as minimally and precisely as possible)**:

* Dashboards -> Add new folder: create 2 folders "Foo" and "Bar"
* Alerts -> Alerting: Create new "Rule1" in folder "Foo"
* Alerts -> Alerting: Create new "Rule2" in folder "Foo"
* Alerts -> Alerting: Click edit rule group icon for "Foo > Rule1",  Change folder name to "Bar", click save. Works OK!
* Alerts -> Alerting: Click edit rule group icon for "Foo > Rule2",  Change folder name to "Bar", click save. Fails with error:
`Failed to update namespace / group: Namespace "Bar" already exists.` 
or `Failed to update namespace / group: folder not found` if not pre-created folder.

**Anything else we need to know?**:

Just found a workaround, well, better way of doing it, is to edit the actual rule and change the folder in the dropdown, rather than edit the rule group.

**Environment**:
- Grafana version: 9.3.0 and 9.4-pre
- Data source type & version: Graphite
- OS Grafana is installed on: Docker
- User OS & Browser: Linux, FF
- Grafana plugins: Default
- Others:

**Comment by soniaAguilarPeiron** [comment] 2023-01-23 09:28
I'm not able to reproduce it.
Actually, edit group button let you update the group for all the alerts belonging to this group, not for one rule in particular.

https://user-images.githubusercontent.com/33540275/214004594-a3e92146-08d8-44ab-907e-ebeb845b1584.mp4

**Comment by soniaAguilarPeiron** [comment] 2023-01-23 09:34
Some clarifications that maybe could help:

- in the group edit modal , user can update the 'name' of the folder. So you are updating the name for this folder for all the rules that belong to this group. (This name should not contain any other rule).
- in the alert form you can change the folder for this rule (in this case you are moving this particular rule to another folder that should already exist, and for that you also have to select the group )

**Closed** 2023-02-20 07:47 UTC
Labels: type/bug, area/alerting, needs investigation, area/frontend
