### ISSUE TITLE
[Bug] Template var groups/tags not working

### ISSUE THREAD

**Issue by linar-jether** [grafana/grafana#6752] opened 2016-11-30 08:37 UTC
Seems to be broken in latest stable version V4.0.0.

No matter what (clicking on update/change the refresh method/recreate the template), grafana doesn't execute the group/tags queries (Tested using the chrome developers console)

**Comment by lymichaels** [comment] 2016-11-30 15:50
I'm seeing the same issue and I upgraded from 3.1.1

**Comment by lymichaels** [comment] 2016-12-08 16:12
Anyone find a workaround or fix for this? It's still broken in 4.0.2

**Comment by linar-jether** [comment] 2016-12-08 16:23
I think this is an important feature of grafana, as without it selecting multiple template variables from large lists is almost impossible

**Comment by tfylling** [comment] 2016-12-09 08:50
useTags seems to not be stored in the json structure at all, probably meaning it will always evaluate as false.

**Comment by RomainBelorgey** [comment] 2016-12-09 10:49
Got the same issue since upgrading on 4.0.1. 

Possible to force the useTags value ?

**Comment by directionless** [comment] 2016-12-12 18:21
As I mentioned over in https://github.com/grafana/grafana/issues/6906
It's broken on the example http://play.grafana.org/dashboard/db/templating-value-groups It looks okay, but if you click anything the tags are gone.

**Comment by stevenh** [comment] 2016-12-14 23:07
Confirmed this was broken here when we updated to 4 as well.
When entering the template editor most the time (not all) the experimental feature has been disabled

**Comment by miketwenty1** [comment] 2016-12-15 19:20
+1

**Comment by trondvh** [comment] 2016-12-16 13:25
+1

**Comment by Farfaday** [comment] 2016-12-18 23:07
+1

**Comment by novegit** [comment] 2016-12-20 09:17
+1

**Comment by VinceTT** [comment] 2016-12-22 13:35
+1

**Comment by paloaltorickyrem** [comment] 2016-12-22 23:49
+1

**Closed** 2017-01-02 12:32 UTC
Labels: comp: dashboard/templating, P3: important

**Comment by Keleir** [comment] 2017-07-21 08:35
+1

**Comment by wyzssw** [comment] 2018-01-24 12:41
+1 broken in 4.6.3
