### ISSUE TITLE
Alerting: ANOMALY_DETECTION_BAND() not working for cloudwatch datasource

### ISSUE THREAD

**Issue by nambsp** [grafana/grafana#69873] opened 2023-06-09 22:22 UTC
### 
# What went wrong?

**What happened**:

  - I tried creating a grafana managed alert using ANOMALY_DETECTION_BAND() function of cloudwatch data source 

**What did you expect to happen**:

  - Nodata is seen in alerting section even though same metric can be graphed in grafana dashboard. 

### 
# How do we reproduce it?

**Step 1**:

- Enable anomaly detection for a cloudwatch metric in AWS. eg: ALB\Requestcount

**Step 2**:

- In Grafana, configure for cloudwatch datasource and go to alert rule and create one. Select grafana managed alerting and use the same cloudwatch metric for which model created in query A with m1 as ID. In query B, enter ANOMALY_DETECTION_BNAND(m1,2)  after selecting "code"  

**Step 3**:

- Run queries and will see NO data for query B though data available for query A

### 
# What Grafana version are you using?

v9.5.0

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Other

### User's OS?

Amazon linux

### Is this a Regression?

No

### Are Datasources involved?

cloudwatch

**Comment by idastambuk** [comment] 2023-06-12 20:03
Hi @nambsp, thanks for reporting this, I've managed to reproduce it and will add it to our board. 

Info from initial debugging, for whoever picks this up:
I've managed to get values in AWS Cloudwatch console for ANOMALY_DETECTION_BAND. 
However, when we send what looks like an identical query from grafana Cloudwatch BE to aws/aws-sdk-go [here](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/get_metric_data_executor.go#L21), it doesn't return any values (though it does return correct fields, `EBSWriteBytes` Low and `EBSWriteBytes High`. Not sure why there's a difference in responses.

**Comment by kevinwcyu** [comment] 2023-08-14 18:40
Moved to waiting as it may be fixed in https://github.com/grafana/grafana/pull/72935

**Comment by idastambuk** [comment] 2023-09-08 08:57
Hi again @nambsp, the [fix](https://github.com/grafana/grafana/pull/74551) for this was just merged and will be released in Grafana 10.2.0. Keep in mind that you will have to enable the 'sseGroupByDatasource' feature toggle for the time being, in order to use metric math in Alerts. 

Let us know if that worked for you so we can close the ticket!

**Comment by sarahzinger** [comment] 2023-12-01 14:23
Closing due to inactivity

**Closed by sarahzinger** 2023-12-01 14:23 UTC
Labels: type/bug, datasource/CloudWatch
