### ISSUE TITLE
Add option to synchronize y-axes across repeated panels

### ISSUE THREAD

**Issue by hahnjo** [grafana/grafana#11783] opened 2018-04-30 10:33 UTC
### What Grafana version are you using?
v5.1.0

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
CentOS 7

### What did you do?
Created a dashboard with a repeated panel.

To ease comparing the values in the panels, it would help to "synchronize" the y-axes, ie. have each axis' minimum be the global minimum (fixed to 0 in this case) and each axis' maximum be the global maximum across all panels.

![panels](https://user-images.githubusercontent.com/1613332/39423463-5b6a4768-4c72-11e8-971d-c65579b404eb.png)

**Comment by hahnjo** [comment] 2018-04-30 10:33
I tried to "fake" this using a template variable, but InfluxDB queries always have "time" as their first value which does not help much...

**Comment by torkelo** [comment] 2018-04-30 10:40
duplicate of https://github.com/grafana/grafana/issues/4156

**Closed by torkelo** 2018-04-30 10:40 UTC
