### ISSUE TITLE
Fill below not working with staircase in graph visualization

### ISSUE THREAD

**Issue by oholimoli** [grafana/grafana#20226] opened 2019-11-07 07:21 UTC
When you select "Fill below to: " and have a staircase graph, the filling is drawn for lines without staircase: 
![Staircase bug](https://user-images.githubusercontent.com/47213738/68368084-85552400-0137-11ea-95e0-05137625e22e.PNG)

**Comment by torkelo** [comment] 2019-11-08 13:47
dupe of https://github.com/grafana/grafana/issues/4612

**Closed by torkelo** 2019-11-08 13:47 UTC
