### ISSUE TITLE
Horizontal scrolling in table panel doesn't move table header (in Grafana 5.0.4)

### ISSUE THREAD

**Issue by yuyutime** [grafana/grafana#11468] opened 2018-04-03 14:00 UTC
### What Grafana version are you using?
Grafana 5.0.4
### What datasource are you using?
Postgres
### What OS are you running grafana on?
CentOS 7.3 for grafana-server
### What did you do?
Add table-panel with table content being wide enough to require horizontal scrolling.
### What was the expected result?
Horizontal scrolling should scroll table content **and** table header.
### What happened instead?
Data in columns scroll as expected while table header doesn't move.

**Comment by IntegersOfK** [comment] 2018-04-23 18:05
This bug essential makes it so you can't have more than 5-8 columns in a table on a dashboard, because the table headers/field names don't line up or scroll with the content.

**Comment by torkelo** [comment] 2018-05-18 11:25
duplicate of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2018-05-18 11:25 UTC
Labels: P4: nice to have, comp: panel/table, type: bug
