### ISSUE TITLE
Variables: Filter is not applied to other panels if the variable value is changed while one panel is open in edit/view mode

### ISSUE THREAD

**Issue by cronosnull** [grafana/grafana#17537] opened 2019-06-12 08:28 UTC
**What happened**:
I have two similar tables, they use the same template variables, and the filters work as expected if the panels are closed. If I open one of the tables in edit/view mode, change the value of the filter, and go back to the dashboard, the filter is only applied to the table that was in open mode (until I manually refresh the dashboard).

**What you expected to happen**:
All the panels are refreshed when a filter is changed (regardless of the currently open panel). 

**How to reproduce it (as minimally and precisely as possible)**:
- Create a new dashboard
- Create a template variable
- Add two panels, that use the template variable,  to the dashboard 
- Open one of the panels in edit mode
- Change the filter value
- Go back to the panel

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: ES 5.6
- OS Grafana is installed on: Centos 7
- User OS & Browser: Centos 7, Firefox 60.6.1esr (64-bit)

**Comment by hugohaggmark** [comment] 2019-06-12 13:59
Hi @cronosnull and thanks for reporting this, I can't repro this using docker image for 6.2.0 on MacOs and FireFox so anymore detailed information about datasource used, template variables used, dashboard and panels used would greatly help us in the search for a repro and solution.

**Comment by cronosnull** [comment] 2019-06-12 19:49
I tested the bug in Chrome (Windows) and Firefox on Linux. The grafana version is  v6.2.0 (commit: 10c6285). It was an upgrade from grafana 5 (5.2). 
There is a minimal POC of the problem: https://youtu.be/1a8CwcWNy7A

I've seen the problem with table and plot panels, and query and custom variables.

**Comment by hugohaggmark** [comment] 2019-06-13 05:55
Thanks for that excellent video @cronosnull! I was now able to repro the issue.

**Comment by hugohaggmark** [comment] 2020-11-11 12:04
I can confirm this is still in Grafana v7.3.1 (6668161a88).

**Comment by hugohaggmark** [comment] 2021-03-18 07:40
I guess this is because of https://github.com/grafana/grafana/blob/8fafe95728c0a2bcf0cdabfc857c049cfc80bd81/public/app/features/dashboard/state/DashboardModel.ts#L275-L278. Tricky to solve this without adding complexity and/or removing other use cases where we don't want to update panels, like when they're not yet visible on the screen for instance.

Any suggestions @torkelo or should we close this issue because there doesn't seem to be much upvotes?

**Closed** 2021-05-14 08:42 UTC
Labels: area/dashboard/templating, priority/nice-to-have, type/bug
