### ISSUE TITLE
Timestamp Unit does not respect UTC dashboard timezone setting

### ISSUE THREAD

**Issue by bscherlein** [grafana/grafana#12871] opened 2018-08-10 11:47 UTC
### What Grafana version are you using? 
Grafana v5.2.2 (aeaf7b2)

### What datasource are you using?
Prometheus

### What did you do?
Set the singlestat panel to display the timestamp of the current value of a query in a dashboard where the timezone is set to UTC, using one of the three provided datetime formats under 'Unit'. (The metric is an epoch timestamp.)
![image](https://user-images.githubusercontent.com/28387556/43956091-18ac20fa-9ca3-11e8-9b88-d7e66553cca9.png)
![image](https://user-images.githubusercontent.com/28387556/43956105-223577fc-9ca3-11e8-8a63-ffe5e3b6d0ba.png)

### What was the expected result?
To see the time in UTC

### What happened instead?
Saw the time in local time

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
Request URL:

```
http://grafana.int.s-cloud.net/api/datasources/proxy/43/api/v1/query_range?query=trackusermappings_current_timeslot%7Benvironment%3D%27production%27%7D%20*%201000&start=1533873000&end=1533894900&step=300
```

Request Method: GET
Response: Status Code: 200 OK,

```json
{
"status": "success",
"data": {
"resultType": "matrix",
"result": [
{
"metric": {
"environment": "production",
"job": "users_mapper"
},
"values": [
[
1533873000,
"1533852000000"
],
...,
[
1533894900,
"1533877200000"
]
]
}
]
}
}
```

The `1533877200000` is Friday, 10 August 2018 05:00:00 in UTC, what I expect to see, but instead I get 07:00:00.

This bug seems to be a regression - it was [reported before](https://github.com/grafana/grafana/issues/10338) and supposed to be fixed in [v5.2.2 (`Singlestat: Fix “time of last point” shows local time when dashboard timezone set to UTC #10338`)](https://community.grafana.com/t/release-notes-v5-2-x/7894)

**Comment by torkelo** [comment] 2018-08-11 14:00
thanks for reporting this, but unable to replicate this in master or v5.2.1  (have not tested v5.2.2 yet). 

This was fixed in v5.2 beta release, can you double check what version your using?

**Comment by bscherlein** [comment] 2018-08-13 11:58
Thanks for responding, @torkelo.

I have double-checked, the version I am using is 5.2.2, see my screenshot:

<img width="161" alt="grafanaversion" src="https://user-images.githubusercontent.com/28387556/44030227-76955826-9f00-11e8-976e-7b2474cf8f51.png">

I have now double-checked and realized that the situation is a bit different from https://github.com/grafana/grafana/issues/10338:

My case is that I want to display the _value_ of the metric as a date & time (the raw value would be `1533877200000` and I expect to see `2018-08-10 05:00:00` but I see `2018-08-10 07:00:00` which is local time). (Use case for having a timestamp as a value is a batch job for which I want to display the timeslot for which it was scheduled, not the actual time when it was run.) I want to display `current`, as can be seen in this picture:

<img width="465" alt="singlestat" src="https://user-images.githubusercontent.com/28387556/44030245-8616cd8e-9f00-11e8-8357-52bd36393f44.png">

not `Time of last point` as in https://github.com/grafana/grafana/issues/10338. I have tried the use case in the other issue and indeed it is fixed. So this is a new bug, not a regression - sorry for the confusion, it seemed the same to me at first. 

@grobie could also reproduce the bug, tagging you in case you are interested.

**Comment by torkelo** [comment] 2018-08-13 13:50
can verify this is a bug, timezone is only sent to format func when last_time stat is selected. 

I think the format function signatures for time & date formats needs to follow the other format funcs, that is value, decimals, as first params. 
https://github.com/grafana/grafana/blob/master/public/app/core/utils/kbn.ts#L826 

Then there is no need to have a special condition for this.

**Comment by torkelo** [comment] 2018-10-04 09:05
The issue is that the singlestat is has special logic for last_time which makes this timestamp unit not work with other stat types. So if your value is a timestamp it won't pass that utc flag. 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/singlestat/module.ts#L307

I think the format function signatures for time & date formats needs to follow the other format funcs, that is value, decimals, as first params.
https://github.com/grafana/grafana/blob/master/public/app/core/utils/kbn.ts#L826

here are the format func tests:
https://github.com/grafana/grafana/blob/master/public/app/core/specs/kbn.test.ts#L108

here are the other func signatures:
https://github.com/grafana/grafana/blob/master/public/app/core/specs/kbn.test.ts#L198

**Closed** 2019-01-14 13:50 UTC
Labels: beginner friendly, comp: panel/singlestat, effort1: small, hacktoberfest, help wanted, type: bug
