### ISSUE TITLE
Grafana panel image not rendering

### ISSUE THREAD

**Issue by usmanC9** [grafana/grafana#11223] opened 2018-03-13 12:14 UTC
### What Grafana version are you using? 
v5
### What datasource are you using? 
graphite
### What OS are you running grafana on?
ubuntu
### What did you do?
Render image of boomtable panel (https://github.com/yesoreyeram/yesoreyeram-boomtable-panel)
### What was the expected result?
PNG Image rendered
### What happened instead?
server timeout 
![screencapture-192-168-100-18-3000-render-d-solo-x56lgxrik-customer-summary-report-2018-03-13-16_13_06](https://user-images.githubusercontent.com/17683147/37341035-84337700-26d9-11e8-83ab-77b3aee06fbc.png)

**Comment by usmanC9** [comment] 2018-03-13 13:30
I am also not able to render image of table panel. Grafana server is giving the same error as above.

**Comment by bergquist** [comment] 2018-03-13 20:39
dupe of https://github.com/grafana/grafana/issues/11180

**Closed by bergquist** 2018-03-13 20:39 UTC
