### ISSUE TITLE
Bug - Alerting with Elasticsearch datasource ignores min interval

### ISSUE THREAD

**Issue by shachakz** [grafana/grafana#26076] opened 2020-07-06 07:15 UTC
![Grafana_Elastic_Interval_Bug](https://user-images.githubusercontent.com/11520905/86565758-228b8500-bf71-11ea-9c6b-d4bb1a6752ac.gif)

**What happened**:  When changing the date histogram interval to "auto" after defining a minimum interval alert returns with "no_data" due to:
![image](https://user-images.githubusercontent.com/11520905/86565863-4ea70600-bf71-11ea-8ece-964547a4ecdf.png)

**What you expected to happen**: Both behaviours (defining min interval as 1m and setting date histogram interval to auto / 1m) will result a valid alert without Elasticsearch error 

**How to reproduce it (as minimally and precisely as possible)**: Create an index with many documents over many buckets, a visualization over this index and add Grafana alert

**Anything else we need to know?**: No :)

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Elasticsearch 7.7.0
- OS Grafana is installed on: Docker
- User OS & Browser: Mac OS & Chrome
- Grafana plugins: None
- Others:

**Comment by dprokop** [comment] 2020-07-07 09:11
Thanks @shachakz for reporting. This sounds like a duplicate of https://github.com/grafana/grafana/issues/17327

**Closed by dprokop** 2020-07-07 09:11 UTC
