### ISSUE TITLE
Facing install issue on ppc64le architecture

### ISSUE THREAD

**Issue by vinodk99** [grafana/grafana#90211] opened 2024-07-09 06:04 UTC
### What happened?

while executing yarn install facing issues:

[root@4c00074dba08 grafana]# yarn install
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 542ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ @grafana/data is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/experimental (p09961) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @grafana/data is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/experimental (p9c164) and other dependencies request (^10.0.0).
➤ YN0060: │ @grafana/e2e-selectors is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/experimental (p69e2d) and other dependencies request (^10.0.0).
➤ YN0060: │ @grafana/runtime is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/experimental (p19c88) requests (^10.0.0).
➤ YN0060: │ @grafana/runtime is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/experimental (p68c57) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @grafana/schema is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/scenes (pb8930) requests (^10.4.1).
➤ YN0060: │ @grafana/ui is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/experimental (p3b8f5) and other dependencies request (^10.0.0).
➤ YN0060: │ @grafana/ui is listed by your project with version 11.2.0-pre, which doesn't satisfy what @grafana/experimental (pd722e) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @testing-library/dom is listed by your project with version 10.0.0, which doesn't satisfy what testing-library-selector (p708b4) requests (^9.3.3).
➤ YN0060: │ @types/react is listed by your project with version 18.3.3, which doesn't satisfy what @testing-library/react-hooks (p07e68) and other dependencies request (^16.9.0 || ^17.0.0).
➤ YN0060: │ esbuild is listed by your project with version 0.20.2, which doesn't satisfy what esbuild-plugin-browserslist (p19231) requests (~0.21.4).
➤ YN0060: │ marked is listed by your project with version 12.0.2, which doesn't satisfy what @glideapps/glide-data-grid (pceac5) requests (^4.0.10).
➤ YN0060: │ monaco-editor is listed by your project with version 0.34.1, which doesn't satisfy what @grafana/monaco-logql (p03d88) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react is listed by your project with version 18.2.0, which doesn't satisfy what react-beautiful-dnd (p1eae0) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-dom is listed by your project with version 18.2.0, which doesn't satisfy what @grafana/experimental (p5dcbe) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-test-renderer is listed by your project with version 18.2.0, which doesn't satisfy what @testing-library/react-hooks (pdf88f) requests (^16.9.0 || ^17.0.0).
➤ YN0060: │ rollup is listed by your project with version 2.79.1, which doesn't satisfy what rollup-plugin-dts (p94e70) and other dependencies request (^3.29.4).
➤ YN0060: │ rxjs is listed by your project with version 7.8.1, which doesn't satisfy what @grafana/experimental (p41c44) and other dependencies request (7.8.0).
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide @testing-library/dom (p012e7), requested by @testing-library/user-event.
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide react-dom (p7074a), requested by @testing-library/react.
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide react-dom (pc01b9), requested by @grafana/experimental.
➤ YN0002: │ @grafana-plugins/grafana-postgresql-datasource@workspace:public/app/plugins/datasource/grafana-postgresql-datasource doesn't provide react-select (p515de), requested by @grafana/experimental.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide @testing-library/dom (pc1d93), requested by @testing-library/user-event.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide react-dom (p1c427), requested by @testing-library/react.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide react-dom (p9c227), requested by @grafana/experimental.
➤ YN0002: │ @grafana-plugins/mysql@workspace:public/app/plugins/datasource/mysql doesn't provide react-select (pd59ab), requested by @grafana/experimental.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 87 packages were added to the project, and 57 were removed (+ 2.05 MiB).
➤ YN0000: └ Completed in 2s 969ms
➤ YN0000: ┌ Link step
➤ YN0008: │ cypress@npm:13.10.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ @swc/core@npm:1.4.2 [492e0] must be rebuilt because its dependency tree changed
➤ YN0008: │ msw@npm:2.3.1 [655a6] must be rebuilt because its dependency tree changed
➤ YN0007: │ nx@npm:19.2.0 [231b4] must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.5.5 [7d94a] must be built because it never has been before or the last one failed
➤ YN0009: │ nx@npm:19.2.0 [231b4] couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-2cccf77a/build.log)
➤ YN0000: └ Completed in 5s 311ms
➤ YN0000: · Failed with errors in 10s 491ms
[root@4c00074dba08 grafana]# vi /tmp/xfs-2cccf77a/build.log
[root@4c00074dba08 grafana]# cat /tmp/xfs-2cccf77a/build.log
# This file contains the result of Yarn building a package (nx@virtual:231b41c796fb4c3a1878ccc2b284d7acc71e342654f1dcf3bec9e756c379469380938482d22d651d850cf92850f594f3b751114f8c7660ab24c8aee2d7081537#npm:19.2.0)
# Script name: postinstall

/grafana/node_modules/nx/src/native/native-bindings.js:235
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
        ^

Error: Unsupported architecture on Linux: ppc64
    at Object.<anonymous> (/grafana/node_modules/nx/src/native/native-bindings.js:235:15)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module._load (/grafana/node_modules/nx/src/native/index.js:69:25)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/grafana/node_modules/nx/src/native/index.js:75:21)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)

Node.js v20.15.1
[root@4c00074dba08 grafana]#

### What did you expect to happen?

Install needs to be passed

### Did this work before?

No

### How do we reproduce it?

1.Install node
2.yarn install

### Environment (with versions)?

Grafana:v11.1.0
OS:rhel9.3

### Grafana platform?

None

**Comment by marefr** [comment] 2024-07-11 09:00
Duplicate of #89055

**Comment by marefr** [comment] 2024-07-11 09:01
I'm pretty sure this is similar problem as #89055 and there's a workaround in there so will close this. If that's incorrect, please let us know and we'll reopen.

**Closed by marefr** 2024-07-11 09:01 UTC
