### ISSUE TITLE
Panel visualization Internet Explorer 11

### ISSUE THREAD

**Issue by dcl000** [grafana/grafana#17604] opened 2019-06-17 07:46 UTC
When try to edit any panel the content of the page turns black. Only the left menu is rendered.

How to reproduce it (as minimally and precisely as possible): Grafana 6.2.2 and Internet Explorer 11

Environment:
- Grafana version: 6.2.2
- Data source type & version: Prometheus 2.5.0.linux-amd64
- OS Grafana is installed on: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)
- User OS & Browser: Internet Explorer 11
- Grafana plugins: Only plugins by default
- Others: The page renders properly in Firefox, Chrome and Edge.

![image001](https://user-images.githubusercontent.com/5735697/59586766-ef672100-90e3-11e9-9314-61495d7f89ca.png)

**Comment by aocenas** [comment] 2019-06-17 15:41
Duplicate of https://github.com/grafana/grafana/issues/15754 as right now Grafana 6 does not support ie11 very well.

**Comment by aocenas** [comment] 2019-06-17 15:42
Duplicate of https://github.com/grafana/grafana/issues/15754 as right now Grafana 6 does not support ie11 very well.

**Closed by aocenas** 2019-06-17 15:42 UTC

**Comment by aocenas** [comment] 2019-06-17 16:26
As right now Grafana 6 does not support ie11 very well so we have a single issue for that.
