### ISSUE TITLE
[Feature Request]:singlestat plugin should support multiple thresholds

### ISSUE THREAD

**Issue by rydeng** [grafana/grafana#5242] opened 2016-06-01 13:43 UTC
Feature: The Singlestat plugin should support more thresholds, but now it only can set two thresholds.

Why: The Singlestat now only support two thresholds, it is limited when we need more various thresholds range.

It is not so hard to do it.But it is neccessary.

**Comment by torkelo** [comment] 2016-06-01 13:59
Can you describe the use case? No one else has requested more than the 3 we have now.

**Comment by bergquist** [comment] 2016-06-03 12:10
Closing this since its a duplicate of https://github.com/grafana/grafana/issues/3608

@rydeng Please describe how you would use this feature. Helps us prioritize.

**Closed by bergquist** 2016-06-03 12:10 UTC
Labels: comp: panel/singlestat, type: feature request
