### ISSUE TITLE
[Feature Request] Alerting: Send alert to external script

### ISSUE THREAD

**Issue by matthenning** [grafana/grafana#9312] opened 2017-09-20 13:02 UTC
To attach external alerting components it would be useful to trigger external scripts with an alert.

An additional channel could be added to the alerting channels which allows you to configure the path to a custom script or command line. 
Grafana can then call this script and use parameters to add details about the alert.

Icinga 2 does this in a similar manner.

**Comment by torkelo** [comment] 2017-09-20 13:28
duplicate of https://github.com/grafana/grafana/issues/6721

**Closed by torkelo** 2017-09-20 13:28 UTC
