### ISSUE TITLE
[Feature Request] Support both row and panel replication

### ISSUE THREAD

**Issue by eighteen14k** [grafana/grafana#8119] opened 2017-04-13 16:23 UTC
It would be useful if Grafana could support layouts that allowed:
(a) a row to replicate (vertically) if multiple selections are made on variable "A"
(b) a panel to replicate (horizontally) if multiple selections are made on another variable "B"

The goal is to support a layout like the image attached...
![desired](https://cloud.githubusercontent.com/assets/6872041/25014010/5a52f13a-20b9-11e7-92ad-7aea57840dce.png)

**Comment by torkelo** [comment] 2017-04-13 16:47
duplicate of https://github.com/grafana/grafana/issues/5715

**Closed by torkelo** 2017-04-13 16:47 UTC
