### ISSUE TITLE
Time between alert evaluations is not always honoured

### ISSUE THREAD

**Issue by karimelc** [grafana/grafana#22375] opened 2020-02-21 15:02 UTC
**What happened**:
The execution of alerts (evaluation of query) does not always honour the set evaluation period. I see a discrepancy of several minutes compared to the set evaluation period.

**What you expected to happen**:
When I set the evaluation period in the Alert Rule dialogue to e.g. 10 m I expect the alert scheduler to run every 10 minute or close to every 10 minute.

**How to reproduce it (as minimally and precisely as possible)**:
Set up a few Alerts with the same evaluation period (Evaluate every 10m For 0m). In my tests I seem to need 4 alert rules before I start seeing the problem. Turn on logging according to https://grafana.com/docs/grafana/latest/alerting/rules/#troubleshooting

In the Grafana server log you will now see when the alert rules are run like (filtered for one alert):

t=2020-02-21T**14:00:01**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=16.823 alertId=1 name="authentication failure" firing=false attemptID=1
t=2020-02-21T**14:10:01**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=18.676 alertId=1 name="authentication failure" firing=false attemptID=1
t=2020-02-21T**14:20:01**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=16.236 alertId=1 name="authentication failure" firing=false attemptID=1
t=2020-02-21T**14:30:01**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=17.637 alertId=1 name="authentication failure" firing=false attemptID=1
t=2020-02-21T**14:40:01**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=6.723 alertId=1 name="authentication failure" firing=false attemptID=1 

In the case above for alertId=1 we see that it runs on the second every 10th minute. But for another alertId=5 configured exactly the same way, the time between evaluations is quite off:

t=2020-02-21T**13:53:20**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=12.810 alertId=5 name=sbin_susp firing=false attemptID=1
t=2020-02-21T**14:06:40**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=8.943 alertId=5 name=sbin_susp firing=false attemptID=1
t=2020-02-21T**14:13:20**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.576 alertId=5 name=sbin_susp firing=false attemptID=1
t=2020-02-21T**14:26:40**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.890 alertId=5 name=sbin_susp firing=false attemptID=1
t=2020-02-21T**14:33:20**+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=16.210 alertId=5 name=sbin_susp firing=false attemptID=1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Elasticsearch 7.3.2
- OS Grafana is installed on: docker version on CentOS 7
- User OS & Browser: macOS & Safari
- Grafana plugins: only built-in
- Others:

**Comment by karimelc** [comment] 2020-03-11 12:13
The issue is with grafana/pkg/services/alerting/scheduler.go and this code:

offset := ((rule.Frequency * 1000) / int64(len(rules))) * int64(i)
job.Offset = int64(math.Floor(float64(offset) / 1000))

I changed this to

job.Offset = int64(i)

and then the alerts are evaluated with the set intervals.

**Comment by marefr** [comment] 2020-06-12 12:09
Tested this on latest Grafana version and can't reproduce your problem. Looking at the scheduler.go it haven't really been changed in 4 years and we haven't received any similar report as yours so will close this.

```
t=2020-06-12T00:07:06+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=12.118 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
t=2020-06-12T00:15:59+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.977 alertId=1851 name="Panel Title alert 1 10m" firing=false attemptID=1
t=2020-06-12T01:54:22+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=30.365 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
t=2020-06-12T02:03:08+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.476 alertId=1851 name="Panel Title alert 1 10m" firing=false attemptID=1
t=2020-06-12T02:11:54+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=2.821 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
t=2020-06-12T02:20:33+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.080 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
t=2020-06-12T02:38:06+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.611 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
t=2020-06-12T02:46:52+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.383 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
t=2020-06-12T02:55:38+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=5.075 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
t=2020-06-12T03:04:24+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.755 alertId=1851 name="Panel Title alert 1 10m" firing=true attemptID=1
```

```
t=2020-06-12T00:04:18+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=5.204 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T00:13:19+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.514 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T00:22:20+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=11.963 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T02:00:58+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=5.240 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T02:09:59+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.777 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T02:28:02+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.254 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T02:37:03+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.129 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T02:46:04+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=20.009 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T02:55:05+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.029 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
t=2020-06-12T03:04:06+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.638 alertId=1852 name="Panel Title alert 2 10m" firing=true attemptID=1
```

```
t=2020-06-12T00:05:15+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.442 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T00:15:00+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.779 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T01:54:22+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=1.506 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T02:04:07+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=23.104 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T02:13:59+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.185 alertId=1855 name="Panel Title alert 5 10m" firing=false attemptID=1
t=2020-06-12T02:23:44+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.806 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T02:33:23+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=1.407 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T02:43:08+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=2.732 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T02:52:53+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=4.223 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
t=2020-06-12T03:02:38+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=3.633 alertId=1855 name="Panel Title alert 5 10m" firing=true attemptID=1
```

**Closed by marefr** 2020-06-12 12:09 UTC
Labels: area/alerting/evaluation, area/backend, needs investigation
