### ISSUE TITLE
Time Series not displaying none in 8.5.2 (from 8.3.4)

### ISSUE THREAD

**Issue by JordanZimmitti** [grafana/grafana#48880] opened 2022-05-10 15:30 UTC
**What happened**:
Hi,
We recently upgraded Grafana from 8.3.4 to 8.5.2. After this upgrade when using the time-series graph for graphing loki log data it no longer gets the time when no values are returned. 

The output used to look like this which is correct:
<img width="1335" alt="The good" src="https://user-images.githubusercontent.com/11902836/167664764-ea0844d3-ca37-44ee-956c-ffa88e9e53ff.png">
<img width="1373" alt="Screen Shot 2022-05-10 at 11 24 00 AM" src="https://user-images.githubusercontent.com/11902836/167664784-44031ea3-8158-4c5d-9e09-f1941644d2e4.png">

Now it shows up like this which is incorrect:
<img width="1335" alt="Big Bad" src="https://user-images.githubusercontent.com/11902836/167664877-beddc5ec-37e3-47ca-bdec-af0e67dbe0f5.png">
<img width="1382" alt="the bad 2" src="https://user-images.githubusercontent.com/11902836/167664887-52916ace-9b2d-43b1-a671-d307a0a9c5bc.png">

In the new version of Grafana, it omits the empty time segments instead of showing them as 0 on the graph. If this is not a bug are there any config values that we are missing to reenable this functionality?

**What you expected to happen**:
I would like to get the time-series graph to look like it did before when the time segments with no data were accounted for

**How to reproduce it (as minimally and precisely as possible)**:
Create a time-series graph with Loki data where there may be no data for a time segment

**Anything else we need to know?**:

Thank you!

**Environment**:
- Grafana version: 8.5.2
- Data source type & version: Loki: 2.5.0

**Comment by mellieA** [comment] 2022-05-17 00:05
@JordanZimmitti are you able to share a few sanitized log lines and the query that you're using when you're seeing this issue? 

I wonder if it could be related to the change here: https://github.com/grafana/grafana/pull/45389

**Comment by gabor** [comment] 2022-05-17 14:32
@JordanZimmitti this was changed in grafana8.4.0.

in the old version, if Loki did not return data for a given time-segment, we artificially inserted null-values at those points. this caused problems and bugs in certain situations, because we had to "guess" where the timestamps-with-no-data are.

since grafana8.4.0 we are not doing this null-insertion, and the graph-visualization was adjusted to be able to handle such situations.

do i understand correctly, that the problem for you is the table-visualization?
if it is so, could you describe your workflow? why do you need empty table-rows?

**Comment by JordanZimmitti** [comment] 2022-05-17 14:56
@gabor Hi thank you for the reply!

Yes, the problem is with the table visualization. 

In the first graph picture when logs are not coming into our server it is clearly represented as a 0. In the second graph picture when logs are not coming into our server it keeps the last non-zero number until logs start coming in. This is confusing to look at because it makes it seem like logs are constantly coming in when in actuality they are not.

I would love for there to be a way to treat no logs as zeros in the graph again

Thanks!

**Comment by JordanZimmitti** [comment] 2022-05-17 15:10
This issue: https://github.com/grafana/grafana/issues/49030

That was just released also seems to be like the same issue I am having

**Comment by JordanZimmitti** [comment] 2022-05-17 16:12
> @JordanZimmitti are you able to share a few sanitized log lines and the query that you're using when you're seeing this issue?
> 
> I wonder if it could be related to the change here: #45389

@mellieA Thank you for your replay!

It might be I'm not sure the newer issue I linked to above seems to be the same issue I am having if that helps at all

**Comment by gabor** [comment] 2022-05-18 07:52
@JordanZimmitti i did a quick check and the graph-line did not connect for me when there was no data. could you try these please?:

1. in the dashboard, in the time-series panel options, there is a section called "Connect null values". can you verify that it is set to "Never"?
2. if you have a graph that is wrong, could you:
      - pick a time-range as small as possible that still reproduces the problem
      - upload a picture of the incorrect graph-line
      - click on query-inspector, Data tab, Download_csv button, and upload the csv-file? (make sure no private/secret data is in it)

**Comment by gabor** [comment] 2022-05-19 07:04
@JordanZimmitti thanks for the detailed info... i'm afraid we are missing some detail here, because i'm not able to reproduce this:


1. are you using the "Time series" visualization in grafana8.3.4? (not the "Graph (old)" visualization)
2. are you using any non-default setting in the "Tiime series" visualization in Grafana 8.3.4 (except the connect-null-values)?
3. you see i tried a quick setup in grafana 8.3.4 with some test data, and it looks like this: <img width="931" alt="null" src="https://user-images.githubusercontent.com/51989/169230424-af4dea3e-9957-4377-b43b-ed4bde9cb91e.png">

as you can see, the graph contains 5 values: `1,null,null,null,1`, and i use the connect-null-values option. but the line is drawn at the value `1`, it does not go down to zero where there are `null`s... so i don't know how you achieve that in grafana 8.3.4.

**Comment by JordanZimmitti** [comment] 2022-05-19 12:27
@gabor Hi,

After looking through my time-series graph options I forgot that I had `stack series` set to `normal`. This is what produces the desired graph effect I'm looking for. Try enabling that and see if drops to zero.

**Comment by gabor** [comment] 2022-05-19 13:00
@JordanZimmitti thanks, the `stack-series-normal` was the key 😄 . it seems the problem is not even Loki-related.

in Grafana8.4.0 we adjusted the code how these stacked-graphs work to fix a bug ( https://github.com/grafana/grafana/pull/44359 ).

since then enabled `stack-series-normal` will not pull the value down to zero like before.

so, even if we would insert the nulls in Loki like we did before, it would not help, sorry.

the solution is probably somehow implementing the `set null to zero` feature from `Graph (old)`, like you mentioned too.

pinging @grafana/grafana-bi-squad & @leeoniya , what do you think?

**Comment by JordanZimmitti** [comment] 2022-05-19 13:07
@gabor Awesome! 

I'm glad we narrowed down where it was coming from, thanks for all your help so far! 

I think having an option of `set null to zero` will be incredibly helpful because there are definitely times when having the drop off is important, especially when looking at API requests/responses

**Comment by leeoniya** [comment] 2022-05-19 13:09
@gabor 

we're currently working through how to implement `null-as-zero`. it's a bit trickier that it seems, since it needs to also affect calculations in fieldReducers (done pre-panel) and not just the rendering in the panels.

> so, even if we would insert the nulls in Loki like we did before, it would not help, sorry.

yeah, we do this nulls-at-missing-intervals insertion in the panels now, but moving this up out of the panels into the transformers could result in `null` log lines. this means we'd have to filter them out in other places, i think.

feel free to ping me on slack if you have some ideas :)

**Comment by JordanZimmitti** [comment] 2022-05-19 13:15
@leeoniya 

Is there a way to reimplement the way `stack-series-normal` works in `grafana 8.3.4` but just as another option to choose from?

**Comment by JordanZimmitti** [comment] 2022-05-19 13:41
@gabor @leeoniya

I scanned through the two PoCs mentioned and It looks like you guys already have some ideas on how to approach this!

Thanks for the time put in so far, I really appreciate it and I look forward to hearing updates as this progresses.

Is there a loose ETA or is this topic still in the exploration stage?

**Comment by gabor** [comment] 2022-05-23 07:17
@leeoniya @JordanZimmitti considering this issue is basically about having null-as-zero in time-series-panel, to make it easier to follow, i created a new issue for that here: https://github.com/grafana/grafana/issues/49380 , and i will close this one.

if you disagree just comment and we can discuss, thanks.

**Closed by gabor** 2022-05-23 07:17 UTC
Labels: datasource/Loki
