### ISSUE TITLE
Feature request: configurable HTTP timeouts and retry count

### ISSUE THREAD

**Issue by mgtriffid** [grafana/grafana#10544] opened 2018-01-17 12:10 UTC
Hi!

This was originally posted as [question|https://community.grafana.com/t/how-to-configure-http-timeouts-and-retry-number/4861/2], and Marcus advised to file a feature request.

Sometimes some data sources can be slow, or particular queries can be slow, also something can go wrong accidentally. It would be nice to make HTTP connection timeout and socket timeout configurable. Ideally - for both direct and proxied datasources, but maybe this is not even possible, I'm not sure.

Also would be nice to have configurable number of retries for errored requests. From what I see in code I conclude that there actually is a single retry. Am I right?

Thanks!

**Comment by torkelo** [comment] 2018-01-17 12:37
there is no retry for timeouts or query errors. but you have a dashboard with refresh it will retry on the next refresh interval.

**Comment by torkelo** [comment] 2018-01-17 12:38
duplicate of https://github.com/grafana/grafana/issues/5699

**Closed by torkelo** 2018-01-17 12:38 UTC

**Comment by mgtriffid** [comment] 2018-01-17 12:45
Thanks for quick reply, @torkelo ! I apologize for not finding these FRs by myself.
