### ISSUE TITLE
Dynamic Date Range for Dashboard

### ISSUE THREAD

**Issue by kirano99** [grafana/grafana#18846] opened 2019-09-03 08:45 UTC
Ability to dynamically change the date range of the dashboard based on a grafana variable or date values pulled from an SQL database

Would be useful when pulling multiple sets of data from different days to be able to have grafana automatically set the date range to the appropriate area, where the graph can be seen, rather than having to re-enter the values manually.

Could look something like this... (Where both are defined as variables that pull data from a database)

![Example](https://user-images.githubusercontent.com/34285686/64157891-74ceb780-ce2f-11e9-8a66-b7bed153f934.PNG)

**Comment by torkelo** [comment] 2019-09-03 16:26
dupe of https://github.com/grafana/grafana/issues/16081

**Closed by torkelo** 2019-09-03 16:26 UTC
