### ISSUE TITLE
My SMTP server (gmail) is already sending mails, even testing with invitation, but the alerts aren't sent by mail

### ISSUE THREAD

**Issue by KaiNene** [grafana/grafana#33760] opened 2021-05-05 17:14 UTC
Can you confirm that the SMTP server sends emails. The best test would be to test sending an email outside of Grafana with the same settings if possible otherwise try sending an invitation to confirm that an actual email is sent to your inbox. If there are no errors in Grafana, then I suspect that the problem is not to do with Grafana.

_Originally posted by @daniellee in https://github.com/grafana/grafana/issues/8069#issuecomment-293003715_

**Comment by n0nvme** [comment] 2021-05-06 09:02
duplicate of https://github.com/grafana/grafana/issues/33668

**Comment by marefr** [comment] 2021-05-10 08:06
Duplicate of #33668

**Closed by marefr** 2021-05-10 08:06 UTC
