### ISSUE TITLE
add expressions inside $__timeGroup/$__timeFilter

### ISSUE THREAD

**Issue by mikk150** [grafana/grafana#13017] opened 2018-08-23 14:30 UTC
Please include this information:
### What Grafana version are you using?
v5.2.2
### What datasource are you using?
Mysql
### What OS are you running grafana on?
Debian
### What did you do?
add mysql expressions inside $__timeGroup/$__timeFilter
### What was the expected result?
I get query with time shift
### What happened instead?
error parsing interval INTERVAL 4 WEEK
### If related to metric query / data viz:
```
SELECT
  $__timeGroup(DATE_ADD(created_at, INTERVAL 4 WEEK),'15m') as time_sec,
  count(id) as value,
  "4 weeks earlier" as metric
FROM table
WHERE $__timeFilter(DATE_SUB(created_at, INTERVAL 4 WEEK))
GROUP BY $__timeGroup(created_at,'15m')
ORDER BY created_at
```

**Comment by marefr** [comment] 2018-08-23 15:05
Duplicate of #8411

**Closed by marefr** 2018-08-23 15:05 UTC
