### ISSUE TITLE
Table asc/desc order with minus values is uncorrect

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#25453] opened 2020-06-08 13:27 UTC
**What happened**:
Table is not correctly sorted in asc/desc order when table has minus values.

**What you expected to happen**:
Table sorded in correct order, lowest value up to highest value. First row on picture below should be value -92, followed by -88 and so on.

**How to reproduce it (as minimally and precisely as possible)**:
Clicking on column header to sort table where table has minus values should reproduce uncorrect order.

**Anything else we need to know?**:
For test I also tried using unit temperature, order was still uncorrect.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: OpenTSDB 2.2.1
- OS Grafana is installed on: Debian 4.9
- User OS & Browser:  Win 10, Chrome 83.0.4103.61
- Grafana plugins: Table
- Others: /

![table order](https://user-images.githubusercontent.com/66313770/84034659-ec231000-a99a-11ea-9c8e-c58c3d1d0a42.PNG)

**Comment by torkelo** [comment] 2020-06-08 13:46
fixed by https://github.com/grafana/grafana/pull/25421  (and duplicate of https://github.com/grafana/grafana/issues/14781 )

**Closed by torkelo** 2020-06-08 13:46 UTC
