### ISSUE TITLE
unable to add a user to a team

### ISSUE THREAD

**Issue by vpapas** [grafana/grafana#13986] opened 2018-11-07 12:41 UTC
Hello,

After updating to grafana-5.3.2-1 we are not able to add users to a team.
We are running Grafana on Centos 7.
The datasources are influxdb, graphite & zabbix.

We can only add users that can be found with drop down menu, but if i search for a user and then select the user it does not work.

**Comment by torkelo** [comment] 2018-11-07 14:11
do you have more than 50 teams?

**Comment by torkelo** [comment] 2018-11-07 14:11
think this is fixed in master via the upgrade of react-select

**Comment by marefr** [comment] 2018-11-07 14:18
Yes working as expected in master and is planned to be released in v5.4 stable. @vpapas would recommend you use a nightly build until this if possible.

**Comment by vpapas** [comment] 2018-11-07 14:48
Thank you for your immediate response.

No, we have 6 teams. 
Do you have an estimation for the new release?
Where i can find a nightly build?

**Comment by marefr** [comment] 2018-11-07 14:53
> Do you have an estimation for the new release?

I would guess in a month or more

> Where i can find a nightly build?

Upper right drop down on download page: https://grafana.com/grafana/download/5.4.0-d03eb3e8pre1. For docker please refer to tag `master` or https://hub.docker.com/r/grafana/grafana-dev/ for nightlies.

**Comment by marefr** [comment] 2018-11-07 14:54
Duplicate of #13425

**Closed** 2018-11-07 14:55 UTC
Labels: type: duplicate

**Comment by vpapas** [comment] 2018-11-07 15:05
Great. thanks.
