### ISSUE TITLE
Loki: printf function to format logs not working while "wrap lines" is disabled

### ISSUE THREAD

**Issue by yunusemrecatalcam** [grafana/grafana#35298] opened 2021-06-05 12:54 UTC
**What happened**:
I'm using a formatting like this 
`line_format "{{ printf \"%-20.20s\" .resource_labels_cluster_name}}\t{{printf \"%-5.5s\" .labels_authorization_k8s_io_decision}}\t{{.protoPayload_resourceName}}"`
to align my log fields vertically. The problem is, this formatting only works when "wrap lines" func enabled. 

We've made a conversation about that at grafana forum, I'm opening this issue regarding to it
https://community.grafana.com/t/aligning-log-columns-vertically/47839/4

Thanks!

**Comment by ivanahuckova** [comment] 2021-06-08 14:06
This is the duplicate of https://github.com/grafana/grafana/issues/32943. Unfortunately, css property `white-space` doesn't have a value, that would ignore newlines and keep spaces and tabs. Maybe we should rename Wrap lines to make it more clear that when it is off, all newlines, spaces, tabs are removed and the other way around. Or see how could we improve experience here.

**Comment by yunusemrecatalcam** [comment] 2021-06-11 10:13
I'm not that a frontend developer but as far as I see on the mozilla css doc, there's no `white-space` value to not to delete multiple spaces but still wrap it up, right?

**Comment by ivanahuckova** [comment] 2021-06-11 13:45
Not sure if I understand your comment, but basically we have 2 options:
- Use `white-space: nowrap;` that will never break text, even if the text has newlines and we will always get 1 log message on 1 line. This has disadvantage that it also ignores spaces and tabs and therefore if your expected output is:
```
| 192.168.224.124 |
| 192.1.1.1               |
```
it will be: 
```
```
| 192.168.224.124 |
| 192.1.1.1 |
```
```
- Use `white-space: pre;` that will not break text, will keep multiple spaces after one another as multiple spaces. But it will break text if explicitly written to break(newline). That way we might have 1 log message at multiple lines. But something like this will work:
```
| 192.168.224.124 |
| 192.1.1.1               |
``` 

@grafana/observability-squad what do you think?

**Comment by olbo98** [comment] 2021-06-14 09:47
@ivanahuckova I think using `white-space: pre;` could be a good solution? That way you could align the logs as you want and if you want them to break they can just explicitly write a newline when they want to. Or have i misunderstood the problem?

**Comment by ivanahuckova** [comment] 2021-06-14 09:55
@olbo98 Yes, that is my opinion as well. Just wanted to hear others.

**Comment by ivanahuckova** [comment] 2021-06-15 14:52
So I think there is a general consensus that we want to use `white-space: pre;`. I am removing `needs-investigation` label.

**Comment by ivanahuckova** [comment] 2021-07-09 11:02
Btw @olbo98 if you are going to work on it - the fix we have mentioned here is also going to fix https://github.com/grafana/grafana/issues/32870

**Comment by olbo98** [comment] 2021-07-09 11:04
@ivanahuckova Oh okay cool, i'll get on it! 👍

**Closed** 2021-07-16 13:08 UTC
Labels: area/explore, area/logs, datasource/Loki, help wanted, onboarding, priority/important-soon, type/bug
