### ISSUE TITLE
Column Style Link includes host URL

### ISSUE THREAD

**Issue by kiplandiles** [grafana/grafana#13045] opened 2018-08-27 19:09 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
* What Grafana version are you using? Grafana v5.2.1 (2040f61)
* What datasource are you using? InfluxDB
* What OS are you running grafana on? CentOS Linux release 7.2.1511 (Core)
* What did you do? Updated to latest version which caused issues with Column Style rendered as Link
* What was the expected result? Open new window to Link
* What happened instead? Page Not Found: 404 Error
`    {
      "alias": "URL",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "link": true,
      "linkTargetBlank": true,
      "linkTooltip": "Click to open a new tab to this site.",
      "linkUrl": "$__cell",
      "pattern": "server",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    }`

$__cell above should just be a URL but instead it contains the server URL as well. For example ...
https://grafana.tdstickets.com/https%3A%2F%2Fbustickets.com

It should have only been https%3A%2F%2Fbustickets.com and was before the upgrade. The variable $__cell only contains the URL so Grafana must be pre-pending the server URL. Perhaps we need an "External Link" option now.

**Comment by kiplandiles** [comment] 2018-08-27 21:32
I found from a Community Post that if I use `${__cell:raw}` it works like before.

**Comment by marefr** [comment] 2018-08-28 09:17
Duplicate of #12560

See [comment](https://github.com/grafana/grafana/issues/12560#issuecomment-404100374) in that issue for same solution as @kiplandiles suggested.

**Closed by marefr** 2018-08-28 09:17 UTC

**Comment by torkelo** [comment] 2018-08-28 12:39
will update tooltip to inform of the ${__cell:raw} syntax when we fix this, https://github.com/grafana/grafana/issues/12945
