### ISSUE TITLE
Problem with displaying dashboards from different org at the same time

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#5270] opened 2016-06-03 10:10 UTC
If I try to open a dashboard from org 1 in one browser tab and another dashboard from org 2 in a new browser tab everything works fine.
But when grafana refreshes it looses track of which dashboard belongs to which org.

Im using a single user with auth to both orgs.

Running 3.0.4

**Comment by bergquist** [comment] 2016-06-03 10:14
Thank you for reporting this! But I'm closing this since its a dupe of https://github.com/grafana/grafana/issues/1613

**Closed by bergquist** 2016-06-03 10:14 UTC
