### ISSUE TITLE
[Bug] CSV Export broken in 4.6.0-Beta1

### ISSUE THREAD

**Issue by Scarzer** [grafana/grafana#9545] opened 2017-10-16 15:50 UTC
Please include this information:
- What Grafana version are you using?
4.6.0-Beta1
- What datasource are you using?
Prometheus 
- What OS are you running grafana on?
Ubuntu 17.04
- What did you do?
I am trying to export some data to a CSV. I have a regular old line graph of some data over a couple of days. Using 4.5.2 I was able to export the data without an issue. When I switched to 4.6.0, the same panel failed to give me the data. Attached is the Chrome console error I have when I attempt to export the data

![errorfromcsvexport](https://user-images.githubusercontent.com/1868926/31621540-f3b0666a-b267-11e7-9e7b-1d828800d387.png)

**Comment by daniellee** [comment] 2017-10-16 19:32
Duplicate of #9525 - already fixed and will be included in beta2.

**Closed by daniellee** 2017-10-16 19:32 UTC
Labels: type: duplicate
