### ISSUE TITLE
Playlists have no variables support

### ISSUE THREAD

**Issue by sarlinska** [grafana/grafana#20013] opened 2019-10-25 11:21 UTC
**What happened**:
You cannot use variables from playlists, and you cannot template screens. You have to make copies of your screen, one for each variable configuration. And you edit each copy of your screen to set the variables and save it.

**What you expected to happen**:
Automate variables selection on the same screen, so it becomes multiple screens.

**Anything else we need to know?**:
Original discussion: https://news.ycombinator.com/item?id=21344459

**Comment by torkelo** [comment] 2019-10-25 11:23
duplicate of https://github.com/grafana/grafana/issues/773

**Closed by torkelo** 2019-10-25 11:23 UTC
