### ISSUE TITLE
Including variables in Notification Message(E-mail)

### ISSUE THREAD

**Issue by wschenbuer** [grafana/grafana#12298] opened 2018-06-15 11:38 UTC
Hello I am wondering if there is a way to put variables in Notification message(E-mail), for example i have variable with value 123; how can i display content of this variable in the message?

**Comment by bergquist** [comment] 2018-06-18 07:29
dupe of https://github.com/grafana/grafana/issues/5848

**Closed by bergquist** 2018-06-18 07:29 UTC
