### ISSUE TITLE
Query regex not working properly with version>=10.2.3

### ISSUE THREAD

**Issue by naoziwatele** [grafana/grafana#81127] opened 2024-01-24 03:24 UTC
### What happened?

When query with field value contains a variable, it retrieved wrong field values to display. For example:
field =~ /$variable-xxxxxx/

### What did you expect to happen?

Hope to fix this issue in next release

### Did this work before?

Version <= 10.2.2 does not have this problem

### How do we reproduce it?

1. create a influxDB measurement with different field values, for example "a_output_values", "b_output_values", "c_output_values", "a_log_values", "b_log_values", "c_log_values", 
2. create a variable called 'prefix' with values of "a", "b", "c"
3. when query fieldName =~ /^$prefix_output/, it displays all 6 fields rather than 3

### Environment (with versions)?

Grafana: 10.2.3, 10.3.1
OS: MacOS 14.2.1
Browser: Chrome 120.0.6099.234 (Official Build) (arm64)

### Grafana platform?

Docker

**Comment by manny4566** [comment] 2024-01-24 14:02
Hi,
same Problem. 
Query (icinga2 dashboard) don't work anymore agains an influxdbv2 source:

SELECT (mean("warn")/mean("max")*100) FROM "disk" WHERE ("metric" =~ /^$disk$/ AND "hostname" =~ /^$hostname$/) AND $timeFilter GROUP BY time(5m) fill(null)

**Comment by sekomarek** [comment] 2024-02-28 14:57
Hi, probably same problem here. I can only make variables work if I escape them using /^${servers**:regex**}$/ Othervise, if variable contains text where there are special characters like "/", InfluxDB returns error 500.

**Comment by itsmylife** [comment] 2024-02-29 15:19
@naoziwatele I cannot reproduce the issue. Could you please create a dashboard and share `dashboard.json` with me? That'll be quite helpful. 
@manny4566 and @sekomarek I think the following PRs will solve your cases
- https://github.com/grafana/grafana/pull/83400
- https://github.com/grafana/grafana/pull/83577

**Comment by manny4566** [comment] 2024-02-29 16:16
> @naoziwatele I cannot reproduce the issue. Could you please create a dashboard and share `dashboard.json` with me? That'll be quite helpful. @manny4566 and @sekomarek I think the following PRs will solve your cases
> 
>     * [InfluxDB: Fix escaping template variable when it was used in parentheses #83400](https://github.com/grafana/grafana/pull/83400)
> 
>     * [InfluxDB: Fix interpolation of multi value template variables by adding parenthesis around them #83577](https://github.com/grafana/grafana/pull/83577)

Hi,

yes i think so. Thank you
But my last information was that the fix is planed for 10.4.x. Will it be released now in 11.0.x ?

**Comment by itsmylife** [comment] 2024-02-29 16:21
@manny4566 This is not clear yet. They will be in `v11.0.x` for sure. I am checking if we could make it in `v10.4.x` too. The fixes are a bit behind the release schedule. That's why there is an uncertainty.

**Comment by naoziwatele** [comment] 2024-03-01 03:50
> @naoziwatele I cannot reproduce the issue. Could you please create a dashboard and share `dashboard.json` with me? That'll be quite helpful. @manny4566 and @sekomarek I think the following PRs will solve your cases
> 
> * [InfluxDB: Fix escaping template variable when it was used in parentheses #83400](https://github.com/grafana/grafana/pull/83400)
> * [InfluxDB: Fix interpolation of multi value template variables by adding parenthesis around them #83577](https://github.com/grafana/grafana/pull/83577)

<img width="1030" alt="Screenshot 2024-03-01 at 11 44 28" src="https://github.com/grafana/grafana/assets/7352540/6e1c0721-5e2f-4480-b952-6fb56403c2b2">

Let me know if the above image can explain the problem, if not I will provide an additional json file. Thank you for the help @itsmylife

**Comment by manny4566** [comment] 2024-03-01 08:25
From my site qe have the 

> @naoziwatele I cannot reproduce the issue. Could you please create a dashboard and share `dashboard.json` with me? That'll be quite helpful. @manny4566 and @sekomarek I think the following PRs will solve your cases
> 
>     * [InfluxDB: Fix escaping template variable when it was used in parentheses #83400](https://github.com/grafana/grafana/pull/83400)
> 
>     * [InfluxDB: Fix interpolation of multi value template variables by adding parenthesis around them #83577](https://github.com/grafana/grafana/pull/83577)

Maybe it will help.
From my site we use:
https://grafana.com/grafana/dashboards/381-icinga2-with-influxdb/

My problem is the variable "disk". After the upgrade to >=10.2.3 the variable don't work anymore. I hope the fix will be the solution.

![grafik](https://github.com/grafana/grafana/assets/23473485/fab66bee-cec5-407c-af77-1098f95e6753)

**Comment by itsmylife** [comment] 2024-03-01 10:54
@manny4566 thanks for the details. I checked the dashboard.json and yes your case will be fixed. 
@naoziwatele I think I understand the situation. These two PRs will resolve your issue too. 
- https://github.com/grafana/grafana/pull/83400
- https://github.com/grafana/grafana/pull/83577

**Closed** 2024-03-01 15:31 UTC
Labels: datasource/InfluxDB, area/dashboard/templating, triage/needs-confirmation
