### ISSUE TITLE
[Change Req]: Change what happens when duplicating a graph (so it does not modify width of existing panels in row)

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#7456] opened 2017-02-04 16:39 UTC
@bergquist

**Comment by torkelo** [comment] 2017-02-04 17:03
Yes, this is by design,  Grafana tries to make room for the new panel on the same row,  honestly I find this behavior irritating as well, it is away to get away from rows that wrap (panels with span more than 12), rows that wrap are something we want to discourage.  

Maybe a better way is to create a new row below and add the duplicated panel to that row

**Comment by torkelo** [comment] 2017-02-06 12:10
Do you have a suggestion for what behavior would be best?

**Comment by bergquist** [comment] 2017-02-07 12:57
@torkelo duplicate the panel with the same span width. Causing the row height to expand rather then the duplicated panels width.

**Comment by torkelo** [comment] 2017-02-07 13:36
What? That makes no sense,  expanding row height does not imake it fit more panels :)

**Comment by RichiH** [comment] 2017-02-07 19:10
> Do you have a suggestion for what behavior would be best?

Create the exact same panel to the right of the duplicated one, maintaining all other settings including panel width.

Everything else violates the principle of least surprise.

**Comment by RichiH** [comment] 2017-02-07 19:44
PS: If you need to wrap a row due to that, then so be it.

NB: Without guidance in UI/UX, there is no way to even know you want to discourage this behaviour.

**Comment by torkelo** [comment] 2017-02-08 19:20
Yea, I know we need a way do inform uses having rows that wrap is not a good idea (row height becomes unusable as it will govern panel height for two rows, problems with creating free space to drop a panel on etc) I know this is due to a very frustrating and limiting layout engine, something we want to improve. 

Think the best is to duplicate panel and add it to the right with same span, if there is no room left push other panels to a new row inserted below.  Not ideal maybe

**Comment by RichiH** [comment] 2017-02-13 14:35
Left push? From how I understand things, you mean right push?

**Comment by torkelo** [comment] 2017-12-18 14:45
fixed in master with new grid https://www.youtube.com/watch?v=BC_YRNpqj5k&t=16s

**Closed by torkelo** 2017-12-18 14:45 UTC
Labels: comp: dashboard, type: feature request

**Comment by RichiH** [comment] 2017-12-21 13:16
Thanks!
