### ISSUE TITLE
Single point data display error in bar graph

### ISSUE THREAD

**Issue by yangliuyu** [grafana/grafana#11964] opened 2018-05-17 09:36 UTC
I have installed grafana v5.0.4 commit: 7dc36ae on a CentOS 7 server, using a MySql 7 database as datasource

When display a data series with only one point of data which means only got one row from mysql datasource, the bar display with will cross whole screen, is this a bug? Two rows data from mysql works fine.

![screen shot 2018-05-17 at 5 33 37 pm](https://user-images.githubusercontent.com/1361821/40169398-811614cc-59f8-11e8-8647-aac2ec274baa.png)
![screen shot 2018-05-17 at 5 33 25 pm](https://user-images.githubusercontent.com/1361821/40169405-84cd6020-59f8-11e8-8454-2f7ba03adcd5.png)

**Comment by torkelo** [comment] 2018-05-17 12:05
you need to group by some time interval and insert a null value for missing intervals, without those null values Grafana will not know when there is missing data or how wide the distance between data points should be. 

Grouping by time and inserting null for intervals with no data is supported by most TSBSs, think doing this in SQL is very tricky though. 

duplicate of https://github.com/grafana/grafana/issues/9487

**Closed by torkelo** 2018-05-17 12:05 UTC

**Comment by marefr** [comment] 2018-05-17 13:00
If you upgrade to Grafana v5.1 or newer you can use an updated version of the $__timeGroup macro which allows you to provide a third optional argument which will be used to insert "missing" values, see [documentation](http://docs.grafana.org/features/datasources/mysql/#macros).

**Comment by yangliuyu** [comment] 2018-05-18 05:25
thanks @torkelo @marefr 
I have upgraded to 5.1.3 but got some issue https://github.com/grafana/grafana/issues/11986
and $__timeEpochGroup will save me :) https://github.com/grafana/grafana/issues/11987
