### ISSUE TITLE
Unable to hide Redis query data

### ISSUE THREAD

**Issue by discreetmayor** [grafana/grafana#65004] opened 2023-03-19 16:31 UTC
**What happened**: Unable to hide Redis query result from panel.

**What you expected to happen**: Toggling hide/unhide should affect visibility of query in panel

**How to reproduce it (as minimally and precisely as possible)**:
Add any Redis query that produces data, toggle hide/unhide. See that values are always shown regardless of setting.

**Environment**:
- Grafana version: 9.2.3
- Data source type & version: Redis 2.1.1
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: MacOS 11.7.3, Chrome 110

<img width="1590" alt="Screen Shot 2023-03-19 at 12 08 05 PM" src="https://user-images.githubusercontent.com/3473637/226190196-3e7d0cc1-1174-4bdf-8bc9-f248ab7d0b03.png">
<img width="330" alt="Screen Shot 2023-03-19 at 12 18 36 PM" src="https://user-images.githubusercontent.com/3473637/226190207-cede35ad-2edf-403f-8596-41f2283ca401.png">

**Comment by discreetmayor** [comment] 2023-03-20 11:07
Hello @usmangt - It is "Redis", the one on the left.

**Comment by usmangt** [comment] 2023-04-03 12:14
Moving it to @grafana/dashboards-squad as not 100% sure because the issue is related in the query editor but the plugin i.e. Redis is a commercial one.

Please let me know if incase its the wrong project.

**Comment by evictorero** [comment] 2023-04-25 13:27
I was able to reproduce it as well but I tested the functionality with the same panel and other data sources and they are all working as expected.
This seems to be an issue with the data source, we should open a ticket in [their project](https://github.com/RedisGrafana/grafana-redis-datasource)

**Comment by natellium** [comment] 2023-04-26 07:42
Closing this issue as it doesn't seem to be Grafana related. Ping us if we should reopen :)

**Closed by natellium** 2023-04-26 07:42 UTC
Labels: area/query-editor, triage/needs-confirmation
