### ISSUE TITLE
​Feature Request: [influxDB] Ability to select the Retention Policy

### ISSUE THREAD

**Issue by syepes** [grafana/grafana#3605] opened 2015-12-24 15:01 UTC
Hello,

It would be nice to have the possibility of selecting the Retention Policy when queries the measurements.

Something like this:
![rp](https://cloud.githubusercontent.com/assets/333081/11995793/76ad68da-aa57-11e5-9430-b62c99a2430d.png)

###### Default query by Grafana (That uses the default DB Retention Policy, in this case raw)
```
[query] 2015/12/24 15:46:29 SELECT mean(value) FROM ESXi.raw."cpu_coreUtilization_average-percent" WHERE time > now() - 1h GROUP BY time(1s)
```
###### Desired query by Grafana
```
[query] 2015/12/24 15:45:58 SELECT mean(value) FROM ESXi.hist_5m."cpu_coreUtilization_average-percent" WHERE time > now() - 1h GROUP BY time(1s)
```
```
> SHOW RETENTION POLICIES ON ESXi
name    duration        replicaN        default
default 0               1               false
raw     168h0m0s        1               true
hist_5m 17808h0m0s      1               false
hist_1h 17808h0m0s      1               false
```

**Comment by zbindenren** [comment] 2015-12-29 12:05
+1

We are collecting metrics for our servers every 30 seconds into the default retention policy. We also have a continuous query that performs a downsampling of 10 minutes into the downsampling_10m retention policy. Currenty I cannot display metrics in the downsampling_10m retention policy. Would be a great additon.

**Comment by mjseid** [comment] 2016-01-04 15:32
+1

Same use case here.  Downsampling into separate retention policies is becoming very common for influx and I'm sure this would be useful for many users.

**Comment by torkelo** [comment] 2016-01-07 18:46
dupe of https://github.com/grafana/grafana/issues/2018

would love PR help on this issue,

**Closed by torkelo** 2016-01-07 18:46 UTC

**Comment by syepes** [comment] 2016-01-20 13:47
@torkelo Thanks, this is just perfect as always!
