### ISSUE TITLE
Map String Input to Values for Graph Panel?

### ISSUE THREAD

**Issue by n1nj4888** [grafana/grafana#14222] opened 2018-11-29 01:44 UTC
Is it possible to map string values coming from InfluxDB to values so that they can be graphed with grafana Graph Panel?

I have a measurement in InfluxDB which captures the state of a UPS as follows along with the timestamp:

"OL" = "On AC Power"
"OL-CHRG" = "On AC Power, Battery Charging"
"OB-DISCHRG" = "On Battery, Discharging"

Is it possible in Graph panel to map say the above strings to the following so that they can be graphed on a time-based graph enabling me to see the history of the status of the UPS?

"OL" = "On AC Power" = 1
"OL-CHRG" = "On Battery, Charging" = 0.5
"OB-DISCHRG" = "On Battery, Discharging" = 0

If this is not possible currently, how do I raise a feature request?

Thanks!

### What Grafana version are you using?
Grafana v5.3.4 (commit: 69630b9)

### What datasource are you using?
InfluxDB

### What OS are you running grafana on?
Grafana Docker

### What did you do?
Trying to map string inputs to values for Graph Panel

### What was the expected result?
Can map string input values from InfluxDB (such as "ON", "OFF") to values i.e. "ON"=1, "OFF"=0 and graph on Graph Panel

### What happened instead?
Cant see any option to map string inputs to specific values to graph?

**Comment by xlson** [comment] 2018-11-29 15:15
Duplicate of #11418

**Closed by xlson** 2018-11-29 15:15 UTC

**Comment by dicer** [comment] 2021-04-05 23:39
@xlson I don't think this should have been closed as a duplicate. Issue #11418 is about formatting. This issue here is about transformation of the data itself in a graph panel, so string values can be graphed. For some datasources this can be fixed in the query (https://community.openhab.org/t/grafana-how-to-display-on-off-values-from-mysql-db/38116), but I think a general transform rule for string values would be great!

**Comment by flg** [comment] 2022-02-22 16:42
This should not have been closed. This request is still valid with Grafana 8.
The value mapping seems like a good place where this should be available (along with a type conversion).

**Comment by itsSaad** [comment] 2023-01-04 18:29
5 Years later... Still waiting.

**Comment by leeoniya** [comment] 2023-01-04 18:43
we're working on it:

https://github.com/grafana/grafana/pull/60068
https://github.com/grafana/grafana/pull/60491
