### ISSUE TITLE
Mobile device "Permission to edit panel denied" alerts blocking the screen

### ISSUE THREAD

**Issue by gknox2017** [grafana/grafana#27302] opened 2020-08-31 16:07 UTC
- from my mobile device, logged in as a 'non-editor' user.
- homepage dashboard contains Alerts panel with links to 'details dashboard' with multiple panels displaying bar graphs. 
- 'details dashboard' is covered by "Permission to edit panel denied" alerts - I can close them, but as soon as I scroll through the window, the screen is covered with more alerts.

**What you expected to happen**:
see the graphs without alert popups & not be warned that I do not have access to edit the panels

**Environment**:
- Grafana version: Grafana v7.1.5
- Data source type & version: irrelevant
- OS Grafana is installed on: ubuntu
- User OS & Browser: mobile device, iPhone with Chrome
- Grafana plugins: irrelevant
- Others: irrelevant
![Grafana Access Denied](https://user-images.githubusercontent.com/26876432/91740815-d0866a80-eb81-11ea-92f1-2ac51dddefda.PNG)

**Comment by hugohaggmark** [comment] 2020-09-01 05:02
Thank you for reporting this @gknox2017, when you click on an item in the alert list you're supposed to go straight into editing that alert in the panel and that's why you get this message if you're a viewer. 

So this is unfortunate by design, but we could make the alert list smarter and navigate to the dashboard instead. But as you can set individual permissions on a dashboard, this new smart logic would need to query our api to resolve the permissions before navigating, and then it gets more complicated. 

Another option would be to make the routing of panel requests smarter, but that could also get complicated fast.

I'll change this to a feature request instead and see if we can come up with something. WDYT?

**Comment by gknox2017** [comment] 2020-09-01 13:21
@hugohaggmark Yes, converting to a feature request would be fantastic. 
The dashboard page I'm looking at, has quite a few panels, so as I scroll through the panels, the alert keeps popping up. If you could set some sort of page variable that it has been displayed, then no need to display it again as long as I'm browsing that page. This would prevent the graphs that are scrolling into view to be blocked as well.

**Comment by AndiKu** [comment] 2020-10-16 07:51
I'm preparing the upgrade from version 6.6.0 to latest (7.2.1) and see same issue in the new version. If I click on a alert inside a alert panel it tries to jump to the edit mode of the panel but as viewer it is not possible and I get this error message. But in the old version 6.6.0 it was working. For a viewer it was jumping to the view mode of the panel. For me this looks like a bug in the new versions 7.x and actuall this is hindering us to upgrade because most of my users are viewer and we use the ````viewers_can_edit=false```` setting.

**Comment by massimilianocasini** [comment] 2020-10-16 11:34
Same issue (bug or unfortunate by design) on 7.1.1 and 7.2.1. However, a solution should be found.

**Comment by dwjbosman** [comment] 2020-12-17 23:35
You can add a text panel, and add some html/javascript to disable click events:

```
<script type="text/javascript">
  $(document).ready(function() {

        $('html > head').append($('<style>.alert-rule-item { pointer-events: none; border:3px solid red; }</style>'));

  });
</script>
```

**Comment by PhantomPhreak** [comment] 2020-12-29 05:31
I have the same problem with grafana v7.3
On the Alerts panel, there are following link under the alert: https://host/d/id/name?editPanel=<no>&tab=alert
When there are anonymous user or user, having Viewer permissions only, i'm getting a lot of ugly pop-up messages, as shown above.

Now, let's try to apply some logic here.
Grafana users are not always Admins or Editors. Users may want to **view** a panel, with configured alert, by clicking on the alert, so see why it's triggered (there may be several metrics on it). Not all the users want to **edit** the panel and change the alerting settings. Thus, common behavior is  **view** the panel with alert, not **edit* it.

It would be nice if the link under the alert was changed to `?viewPanel`

**Comment by HB9VQQ** [comment] 2021-01-11 18:31
I second that, why not make the default "view" instead of "edit" ?

**Comment by jakubvojacek** [comment] 2021-01-11 19:54
most definitely agree

was this acknowledged by grafana yet? I belive its quite valid to view the alert dashboards by viewers role only

**Comment by duhang** [comment] 2021-06-28 18:38
We are hitting this exact same issue when upgrading from Grafana 6.x to Grafana 7.3.

Wondering if Grafana development team could take another look at this issue?

Thanks!

**Comment by peterholmberg** [comment] 2021-11-05 10:41
I believe this is fixed via https://github.com/grafana/grafana/pull/31872

https://github.com/grafana/grafana/blob/eec7b9d325f836a16a7c159130522848fe8e75da/public/app/plugins/panel/alertlist/AlertList.tsx#L149

**Closed by peterholmberg** 2021-11-05 10:41 UTC
Labels: type/bug, type/feature-request, area/alerting, area/panel/alertlist
