### ISSUE TITLE
Data Sources - MySQL add connection params

### ISSUE THREAD

**Issue by cloverzrg** [grafana/grafana#32374] opened 2021-03-26 16:39 UTC
**What would you like to be added**:
When add a MySQL source, add a input for the connection params, like `charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai`
**Why is this needed**:
The time in the datetime field of my database is in +8 time zone, but grafana is regarded as UTC time zone

**Comment by zoltanbedi** [comment] 2021-03-26 16:58
Duplicate of https://github.com/grafana/grafana/issues/16539

**Closed by zoltanbedi** 2021-03-26 16:58 UTC

**Comment by nicolaerosia** [comment] 2022-05-20 12:27
this was not fixed
