### ISSUE TITLE
User agent parser crashes server or causes error in profile / user admin view 

### ISSUE THREAD

**Issue by Sincasios** [grafana/grafana#18524] opened 2019-08-12 22:20 UTC
**What happened**:
I'm using Grafana on Docker in my Raspberry Pi 2 (ARM). In the curren version, when I enter on Profile -> Preferences Grafana crash.

docker logs shows this log:
```
grafana_1     | t=2019-08-12T22:17:39+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
grafana_1     | panic: runtime error: invalid memory address or nil pointer dereference
grafana_1     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x16248]
grafana_1     |
grafana_1     | goroutine 196 [running]:
grafana_1     | github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).ParseOs(0x3154000, 0x315ef80, 0x73, 0x7315c)
grafana_1     |         /go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:284 +0xb8
grafana_1     | github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse.func2(0x3218890, 0x3154000, 0x315ef80, 0x73, 0x3052860)
grafana_1     |         /go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:233 +0x68
grafana_1     | created by github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser.(*Parser).Parse
grafana_1     |         /go/src/github.com/grafana/grafana/vendor/github.com/ua-parser/uap-go/uaparser/parser.go:230 +0x13c
grafana_1     | t=2019-08-12T22:18:22+0000 lvl=info msg="Starting Grafana" logger=server version=6.3.2 commit=4832460 branch=HEAD compiled=2019-08-07T09:49:41+0000

```

This is with a new install (deleting the volume that contains persistence).

**What you expected to happen**:
Not crash

**How to reproduce it (as minimally and precisely as possible)**:
Runing grafana docker (grafana/grafana) on ARM: Click on my profile photo -> Preferences (url /profile)

**Environment**:
- Grafana version:
grafana_1     | t=2019-08-12T21:51:30+0000 lvl=info msg="Starting Grafana" logger=server version=6.3.2 commit=4832460 branch=HEAD compiled=2019-08-07T09:49:41+0000
- OS Grafana is installed on: Is the official docker container
- User OS & Browser: Chrome Windows 10
- Grafana plugins: Default plugins
- Others:

**Comment by hugohaggmark** [comment] 2019-08-13 05:40
Thanks for reporting this @Sincasios! Unfortunately I can't reproduce this using the official docker image so I need your help to narrow this down. Did you do an upgrade and can you post the JS error from Chrome console?

**Comment by torkelo** [comment] 2019-08-13 06:30
The crash is user agent parser, so maybe a strange value entry there. Can you check what values you have in the user agent column in the auth token table ?

**Comment by Sincasios** [comment] 2019-08-13 08:07
I tested now on a x86_64 and it works OK, this happens on the ARM image, at least:

Here you have step by step, rembember that all is a fresh install (I'm not mounting any volume in this example):

Enter in my Raspberry Pi 2 runing OSMC.

`docker run -p 3000:3000 grafana/grafana`

Enter in myPi:3000 from Ubuntu x64 (yesterday I was on windows) and open Chrome in incognito mode.

Login with admin/admin and click "skip" on change password. Cilick on the profile image -> preferences.
![image](https://user-images.githubusercontent.com/50843918/62924858-4837fa80-bdb1-11e9-984e-2ce77c6c8da2.png)

This is the full log: https://pastebin.com/NvsHWYcF

And this is what you have in Chrome dev console:
![image](https://user-images.githubusercontent.com/50843918/62924996-a238c000-bdb1-11e9-873a-24e86a4d3f64.png)

```
Failed to load resource: net::ERR_EMPTY_RESPONSE
vendor.e55e38b08497a8e3f639.js:147 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/user/auth-tokens","retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"}},"statusText":"","xhrStatus":"error"}
(anonymous) @ vendor.e55e38b08497a8e3f639.js:147
vendor.e55e38b08497a8e3f639.js:147 Object
(anonymous) @ vendor.e55e38b08497a8e3f639.js:147
vendor.e55e38b08497a8e3f639.js:147 Possibly unhandled rejection: {"message":"Unexpected error"}
(anonymous) @ vendor.e55e38b08497a8e3f639.js:147
```

How can I check: 

> what values you have in the user agent column in the auth token table

**Comment by hugohaggmark** [comment] 2019-08-13 08:57
I'm not able to repro this by downloading `https://dl.grafana.com/oss/release/grafana_6.3.2_arm64.deb` which image are you using @Sincasios?

**Comment by Sincasios** [comment] 2019-08-13 14:50
My Raspberry is a model 2, so it will be armv7, not arm64. On Docker is the ARM image: 
grafana/grafana      latest              95a520e6f931        6 days ago          157MB

It may be a docker image problem, and not a full graphana build.

The problem is not critical, because docker restart grafana and you can save the changes in "profile".

**Comment by hugohaggmark** [comment] 2019-08-14 06:07
Thanks for your quick response, I'm now able to repro this issue!

**Comment by hugohaggmark** [comment] 2019-08-14 06:44
Somewhere in https://github.com/grafana/grafana/blob/0ba07720df9ee053c850dbb708af3a9f019d106d/pkg/api/user_token.go#L44:27 we crash the whole Grafana instance

**Comment by torkelo** [comment] 2019-08-14 07:31
Not sure how that can crash the server, the http server handler has a panic recovery middleware. Very strange.

**Comment by hugohaggmark** [comment] 2019-08-14 07:42
`api/user/auth-tokens` is the request that crashes the instance

**Comment by marefr** [comment] 2019-08-14 08:06
@Sincasios are you sure that Grafana crashes, i.e. that you cannot browse Grafana until you've restarted the container/Grafana?

**Comment by marefr** [comment] 2019-08-14 08:12
This is probably the issue, i.e. package not working on 32 bit systems: https://github.com/ua-parser/uap-go/issues/38

**Comment by hugohaggmark** [comment] 2019-08-14 08:14
As soon as that happens the server crashes and you can't use Grafana @marefr

**Comment by Sincasios** [comment] 2019-08-14 08:41
@marefr Yep. As I said, if you use Docker with -d you can have autorestart, so it is not critical: Container restart, docker restart the container and you can save profile page modifications (and outside Docker I supose that other systems will be used: systemd, monit or something similar) But if you launch this without autorestart it crashes and server is gone.

I see that @hugohaggmark can reproduce it 👍 and that you already have some clues with UAP not suporting 32 bits systems :'(

**Comment by marefr** [comment] 2019-08-19 19:05
One alternative would be to switch to https://github.com/avct/uasurfer. Still needs to test/evaluate this.

**Comment by realPy** [comment] 2019-08-22 07:11
Have the same bug. You are right @marefr it's an alignment problem.
Like said here https://github.com/golang/go/issues/9959 

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned

I successfull patch the parser.go with 4byte padding in some struct in uaparser and the crash has disappear

**Comment by marefr** [comment] 2019-08-23 11:00
Thanks @realPy appreciate it. Let's hope it get merged soon.

**Comment by Cossey** [comment] 2019-08-26 21:44
I just started using this software a couple of days ago and wanted to also confirm that I also get this error on a Raspberry Pi 3 running in Docker. 

Glad to hear the @realPy has found the cause. 

Do you have an ETA on when this fix will make it to release?

Thanks!

**Comment by realPy** [comment] 2019-08-26 21:59
@cossey Good News my PR just merge 
This bug will be close quickly ;)

**Comment by Cossey** [comment] 2019-08-26 22:05
Awesome stuff. Ill keep an eye out for 6.3.4! Good work guys.

**Comment by marcusolsson** [comment] 2019-08-27 08:21
I'll start looking at updating the dependencies. If someone's already working on this, let me know.

**Closed** 2019-09-02 09:02 UTC
Labels: area/backend/auth, type/bug
