### ISSUE TITLE
Grafana AWS Cloudwatch dimension quotes issue

### ISSUE THREAD

**Issue by deduhov** [grafana/grafana#27517] opened 2020-09-10 19:32 UTC
The task is to pull data by Grafana from AWS Cloudwatch. The datasource configured well and part of the data is displayed well in Grafana. 
The issue is that many AWS Lambda durations have to be displayed at the same graph, but Grafana doesn't do this. When lambda names configured as Grafana multivalue variable with regex Grafana pulls lambda names in preview that is good. But when Grafana dashboard configured to show all the lambdas (about 35)  at 1 graph the error 400 received from AWS with description that dimension have to be less than 1024 (lambdas have too long names and unfortunately it's not possible to change it). Error also shows the query sent by Grafana with dimension like 

FuncitonName='lambdaNameHere1' OR 'lambdaNameHere2' OR 'lambdaNameHere3' ... OR 'lambdaNameHere35'
 
When 'Match Exact' turned off and the dimesion is changed to lambdaNameHere the following query at preview is shown:

REMOVE_EMPTY(SEARCH('Namespace="AWS/Lambda" MetricName="Duration" "FunctionName"="lambdaNameHere"', 'p95', 3600))

The lambdas' names begin from lambdaNameHere and have different ends (lambdaNameHere1, lambdaNameHere2, lambdaNameHere3, etc). Grafana doesn't show any graphics, because lambdaNameHere is quoted in the query (quotes added to the query by Grafana) and when this query used in AWS Cloudwatch it also doesn't show anything.

When the query changed to:

REMOVE_EMPTY(SEARCH('Namespace="AWS/Lambda" MetricName="Duration" "FunctionName"=lambdaNameHere', 'p95', 3600)) 

Removed "" around lambdaNameHere, the Cloudwatch service shows all 35 graphics as expected. 
Is there any way to change Grafana behavior and remove this quotes from the query Grafana generates?

Here  https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-syntax.html described that when AWS cloudwatch dimension is quoted then the only fully matched parameter will be shown, but when the dimension is not quoted then the dimension value will be as a pattern and parameter that has this patter in its name will be displayed at the graph.  

Grafana version v7.1.5 (9893b8c53d)
Started in docker container
Browser Google Chrome, Win10 
Datasource AWS CloudWatch

**Comment by marefr** [comment] 2020-09-11 15:34
Duplicate of #21496

**Closed by marefr** 2020-09-11 15:34 UTC

**Comment by Hellseher** [comment] 2023-06-29 00:18
Why is it linked to not related issues and closed?
