### ISSUE TITLE
OpenTSDB: Metric autocompletion is not more working with 9.3.1

### ISSUE THREAD

**Issue by Helene** [grafana/grafana#60350] opened 2022-12-14 16:43 UTC
**What happened**:  
Installed Grafana server 9.3.1 and checked the DataSource connection established successfully.

![check_datasource_connection_9 3 1](https://user-images.githubusercontent.com/22845495/207654247-e81dc378-5ebd-412d-bdb7-a66a9693490b.png)
Started creating new dashboard panel and experienced that the autocompletion for metric name does not work.

![query_editor_9 3 1](https://user-images.githubusercontent.com/22845495/207655219-a98675ac-df9a-4426-9773-fde49275204a.png)

The same procedure for the same datasource works fine with Grafana server 9.0.0

![check_datasource_connection_9 0 0](https://user-images.githubusercontent.com/22845495/207654720-76f871b0-787a-4f09-bde8-53e8bd4c3a7d.png)
![query_editor_9 0 0](https://user-images.githubusercontent.com/22845495/207655263-5db87753-60d5-4786-9724-f11d9a486c6e.png)

**What you expected to happen**:
It should work as it has in 9.0.0.

**How to reproduce it (as minimally and precisely as possible)**:

Connect Grafana server with OpenTSDB source
Add new dashboard panel 
Type metric name. You should get a list of suggested metric names

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Data source type & version: OpenTSDB 2.3
- OS Grafana is installed on: Windows 11
- User OS & Browser: Mozilla FireFox
- Grafana plugins:
- Others:

**Comment by mellieA** [comment] 2022-12-14 23:14
@Helene can you check that suggest API is enabled as mentioned in the docs here: 

https://grafana.com/docs/grafana/latest/datasources/opentsdb/#auto-complete-suggestions 

Please re-open if you find that it is still not working if the setting is enabled.

**Comment by Helene** [comment] 2022-12-15 18:28
> @Helene can you check that suggest API is enabled as mentioned in the docs here:
> 
> https://grafana.com/docs/grafana/latest/datasources/opentsdb/#auto-complete-suggestions
> 
> Please re-open if you find that it is still not working if the setting is enabled.

Again, for the **same OpenTSDB** the metric auto completion in Grafana 9.0.0 working correctly (please review screen shots above). And yes, suggest API is enabled.

**Comment by Helene** [comment] 2022-12-15 18:33
@mellieA I don't see re-open button. Please reopen this issue.

**Comment by mellieA** [comment] 2022-12-16 23:05
@Helene thanks for confirming that it is still enabled, I wanted to be sure the setting hadn't changed on your datasource. 

Can you open developer tools while

**Comment by mellieA** [comment] 2022-12-19 21:15
@Helene, thank you! Those requests are so helpful to see what's different

**Comment by bohandley** [comment] 2023-01-03 17:55
Hi @Helene and @mellieA! Thank you so much for bringing this to my attention. I migrated the query editor from angular to react and there were design changes. The old autocomplete was a text box that queried metricFindQuery(the function which is used for query variables) for the argument 'metrics(<input>)' on every keystroke and then showed autocomplete options to select. We don't a react component for a text box that autocompletes so I repurposed the select component.

This select component queries metricFindQuery for all available metrics once on opening the select the first time and then filters based on typing. Are you clicking the select to open it or are you tabbing into the new autocomplete input(the select)?

There are two ways to test this. What are the results of that query in the network panel that only queries once? If that query is empty I will have to investigate further. Also, could you try creating a new query variable with the argument 'metrics()' and see if there are results? If there are results, then I need to fix whatever is happening that those results are not populating the metric select dropdown in the query editor.

Thank you again for the feedback!

**Comment by yosiasz** [comment] 2023-01-05 15:32
Hello

When querying an opentsdb metric in grafana it shows 2 data points

![image](https://user-images.githubusercontent.com/900951/210816441-95a2165a-f01c-4bd4-b1e2-287741c871ca.png)


But query inspector shows the real data we want to plot namely under tags
![image](https://user-images.githubusercontent.com/900951/210816584-db044265-b527-4065-8abd-277d3429ad74.png)

The rest api call shows that same data
http://localhost:4242/api/query?start=1672706441&m=sum:1h-avg:car_number.opentsdb{country=US}

```
[{"metric":"car_number.opentsdb","tags":{"host":"web01","country":"US","lon":"-122.37866","lat":"47.239788"},"aggregateTags":[],"dps":{}}]
```

What could be the issue?

Grafana 9.1.5

Windows machine

opentsdb running in podman container.

Thanks

**Comment by the-cloud-source** [comment] 2023-01-10 11:52
Hi,
Just my two cents, the influxdb datasource updates the dropdown(s) on typing, it uses the Segment react component instead of the Select react component.

**Comment by Helene** [comment] 2023-01-11 10:06
> Hi @Helene and @mellieA! Thank you so much for bringing this to my attention. I migrated the query editor from angular to react and there were design changes. The old autocomplete was a text box that queried metricFindQuery(the function which is used for query variables) for the argument 'metrics()' on every keystroke and then showed autocomplete options to select. Grafana doesn't currently have a react component for a text box that autocompletes so I repurposed the select component.
> 
> This select component queries metricFindQuery for all available metrics once on opening the select the first time and then filters based on typing.
> 
> Are you clicking the select to open it or are you tabbing into the new autocomplete input(the select)? What are the results of that query in the network panel that only queries once? If that query is empty I will have to investigate further. Also, could you try creating a new query variable with the argument 'metrics()' and see if there are results? If there are results, then I need to fix whatever is happening that those results are not populating the metric select dropdown in the query editor.
> 
> Thank you again for the feedback!

hi @bohandley ,
usually I do not use tabs in the query editor. I click in the 'metrics' text field and start to type letters.

**In the Grafana 9.0.0:**
As soon as I did type letter "g" the query "suggest?type=metrics&**_q=g_**&max=1000" is sent to the datasource with request to return all metric names starting with "g" (q=g).
As soon as I did type next letter, for example "p", the query "suggest?type=metrics&**_q=gp_**&max=1000" is sent to the datasource with request to return all metric names starting with "gp" (q=gp).
As soon as I did type next letter, for example "f", the query "suggest?type=metrics&**_q=gpf_**&max=1000" is sent to the datasource with request to return all metric names starting with "gpf" (q=gpf). And so on.
The list of the results in the dropdown menu will be updated automatically with each new letter I'm adding to the text field.

**In the Grafana 9.3.0:**
As soon as I did type letter "g" the query "suggest?type=metrics&**_q=**&max=1000" is sent to the datasource with request to return all metric names starting with "nothing" (q=).
As soon as I did type next letter, for example "p", the query "suggest?type=metrics&**_q=_**&max=1000" is sent to the datasource with request to return all metric names starting with "nothing" (q=).
As soon as I did type next letter, for example "f", the query "suggest?type=metrics&**_q=_**&max=1000" is sent to the datasource with request to return all metric names starting with "nothing" (q=). And so on.
I think the main issue there is that the value from the input (typed letters) are not passed to the "q"
The list of the results in the dropdown menu shows exactly the same what I did type in the text field. ( In last example it shows "gpf")

**Comment by bohandley** [comment] 2023-01-19 03:08
> @mellieA thanks for reopening the ticket. If you look at the suggest query sent to the datasource, the **q=** parameter remains **always empty**, equal what I do put in the metric field. ![debug_grafana_9 3 1](https://user-images.githubusercontent.com/22845495/208522832-9cb39cc9-3dba-4626-8bdd-65410ad8c07f.png)

Hi Helene, thank you for your patience.

The parameter always remains empty because we
1. call the suggest endpoint once without a query parameter(the equivalent of creating a metric query variable with the string "metrics()")
<img width="884" alt="Screen Shot 2023-01-18 at 9 56 56 PM" src="https://user-images.githubusercontent.com/25674746/213345303-1ea05bcb-ed3a-454c-831b-c41b77c1da6e.png">

2. We use all the results from the suggest endpoint and filter them based on typing input in the metric React component
<img width="534" alt="Screen Shot 2023-01-18 at 9 58 58 PM" src="https://user-images.githubusercontent.com/25674746/213345339-9aaf492b-46d1-46d5-9ad5-ce8094d163f7.png">

With this new behavior, we only call the endpoint once. If the endpoint is working, the response should contain metrics.

**Can you please check the response of the query to the suggest metrics endpoint?**

If the response is empty, we then need to confirm the suggest metrics endpoint is working for you.

To confirm the suggest endpoint is working, you need to create an opentsdb query variable with your datasource selected. The following image shows how this is done.
<img width="669" alt="Screen Shot 2023-01-18 at 10 02 20 PM" src="https://user-images.githubusercontent.com/25674746/213346099-ae03eecf-0f2e-4f09-bd46-3af4466e7946.png">

**Comment by neilfordyce** [comment] 2023-01-24 21:18
The new behaviour is described in this comment pretty succinctly https://github.com/grafana/grafana/blob/82d80154694c73cab1004fdbf688ba85979b3bda/public/app/plugins/datasource/opentsdb/components/OpenTsdbQueryEditor.tsx#L77

It populates the metric name drop down with the first 1,000 metric names then filters client side.  That's fine for a tiny tiny OpenTSDB cluster with less than 1,000 metric names, but the problem is it's pretty common to have millions of metric names in a single OpenTSDB cluster.  This means there's no way to select those metrics any more unless you know exactly what you're looking for.

**Comment by bohandley** [comment] 2023-01-24 22:21
This makes sense, thank you @neilfordyce! The current implementation cannot handle millions of metrics then. I can rewrite the autocomplete to search as it did before. I assume that with @Helene 's  case, there are no metrics returned because there are too many for the client to handle. It would be nice to confirm this, but I can get started working on this. Thank you!

**Comment by Helene** [comment] 2023-01-26 21:55
@bohandley sorry for the delay in the response, very busy at this time. I think @neilfordyce has exactly described the issue. Our typical production environments have more than 50 000 metrics definitions. 
The OpenTSDB offers some autocompletion by itself http://opentsdb.net/docs/build/html/api_http/suggest.html?highlight=suggest. Why not use it? It will reduce data transferred between DB and Grafana. 

And I'm pretty sure the OpenTSDB autocompletion was used in older releases
https://github.com/grafana/grafana/blob/21ba1469b57e2146e0a42507ac08d2ca25b8b98e/public/app/plugins/datasource/opentsdb/datasource.ts#L226

**Comment by bohandley** [comment] 2023-01-31 20:03
Thank you @Helene, I appreciate the response! I have a PR I am working on that uses the suggest api for the issue. There are just a few tests I am working out but it should be ready soon.

**Comment by bohandley** [comment] 2023-02-02 22:48
@Helene and @neilfordyce The work has been merged and should be released in the next few weeks in v9.4. Thank you for your patience!

**Comment by neilfordyce** [comment] 2023-02-02 23:58
Amazing!  Thanks for making the fix @bohandley 🏅

**Comment by Helene** [comment] 2023-02-03 06:45
Great News ! Thank you @bohandley !

**Comment by vieirajlt** [comment] 2023-03-07 14:52
Hey, I have applied similar changes on the PR to Tag values. Can I open a PR? Here is the [commit](https://github.com/vieirajlt/grafana/commit/51b0b880abef3106c6739fe71df4f45d1196b3ec)

**Comment by bohandley** [comment] 2023-03-07 23:05
I'll add this to my list of things to keep an eye on, sorry for the delay and thank you for the patience!

@vieirajlt I will take a look at your commit and see if we can add that to the next 9.4 release. Thanks!

**Comment by bohandley** [comment] 2023-03-08 20:52
Hi @vieirajlt, looks good! Open a PR and I'll get it rolling along.

<img width="649" alt="Screenshot 2023-03-08 at 3 51 39 PM" src="https://user-images.githubusercontent.com/25674746/223847096-d8ebe1a3-1dd6-4e97-9963-b3dce9f6a933.png">

**Comment by vieirajlt** [comment] 2023-03-09 00:13
Hey @bohandley! It's done; thanks for your help!

**Closed** 2023-03-09 12:45 UTC
Labels: datasource/OpenTSDB, prio/low, needs investigation, triage/needs-confirmation
