### ISSUE TITLE
[Feature request] Grant permissions to a single user to add annotations to a dashboard

### ISSUE THREAD

**Issue by ldktta** [grafana/grafana#11178] opened 2018-03-09 14:39 UTC
It would be nice to be able to grant permissions to certain users only to add annotations in certain dashboards without granting them editing permissions.

**Comment by marefr** [comment] 2018-03-09 15:49
Dupe of #9991. Please comment/upvote that issue by adding a :+1: reaction if you really want this.

**Closed by marefr** 2018-03-09 15:49 UTC
