### ISSUE TITLE
MySQL: query returns wrong value for bigint(20) column

### ISSUE THREAD

**Issue by reagankan** [grafana/grafana#72140] opened 2023-07-21 17:29 UTC
### What happened?

Querying mysql database shows incorrect data for columns of type bigint(20).

Response
```json
{
  "results": {
    "A": {
      "frames": [
        {
          "schema": {
            "refId": "A",
            "meta": {
              "executedQueryString": "select * from servers;"
            },
            "fields": [
              {
                "name": "id",
                "type": "number",
                "typeInfo": {
                  "frame": "int64",
                  "nullable": true
                }
              },
              {
                "name": "name",
                "type": "string",
                "typeInfo": {
                  "frame": "string",
                  "nullable": true
                }
              }
            ]
          },
          "data": {
            "values": [
              [
                1111111111111111200,
                2222222222222222300
              ],
              [
                "server-1",
                "server-2"
              ]
            ]
          }
        }
      ]
    }
  }
}
```
<img width="691" alt="select-all" src="https://github.com/grafana/grafana/assets/22034545/4302f3e9-07be-41ef-b458-04c06bbc0bf2">

### What did you expect to happen?

Grafana displays the correct values.

### Did this work before?

unknown

### How do we reproduce it?

1. create mysql database

```
MySQL [(none)]> CREATE DATABASE db_P93691953_github_issue;
Query OK, 1 row affected (0.008 sec)

MySQL [(none)]> USE db_P93691953_github_issue;
Database changed
MySQL [db_github_issue]> create table servers ( id BIGINT(20) NOT NULL, name VARCHAR(30) NOT NULL );
Query OK, 0 rows affected, 1 warning (0.041 sec)

MySQL [db_github_issue]> insert into servers (id, name) values ('1111111111111111111', 'server-1');
Query OK, 1 row affected (0.010 sec)

MySQL [db_github_issue]> insert into servers (id, name) values ('2222222222222222222', 'server-2');
Query OK, 1 row affected (0.006 sec)

MySQL [db_github_issue]> select * from servers;
+---------------------+----------+
| id                  | name     |
+---------------------+----------+
| 1111111111111111111 | server-1 |
| 2222222222222222222 | server-2 |
+---------------------+----------+
2 rows in set (0.001 sec)

MySQL [db_github_issue]>
```
2. query from grafana dashboard or explore page<img width="691" alt="select-all" src="https://github.com/grafana/grafana/assets/22034545/4302f3e9-07be-41ef-b458-04c06bbc0bf2">
<img width="691" alt="select-by-id" src="https://github.com/grafana/grafana/assets/22034545/3e7176fc-954b-4a67-b701-1312e827b73f">
<img width="694" alt="select-by-name" src="https://github.com/grafana/grafana/assets/22034545/d740901b-7fe0-4f93-b895-5c13f6497ea8">

### Is the bug inside a dashboard panel?

Yes, also occurs in the explore page

### Environment (with versions)?

Grafana: 8.4.7
Browser: Firefox 102.12.0esr 

### Grafana platform?

Other

**Comment by usmangt** [comment] 2023-07-25 08:43
Hi @reagankan,

Thanks for opening this issue. It seems more of a question as how to use the Grafana query editor.
.
Please create a new post at our community forums under the [MySQL](https://community.grafana.com/c/support/mysql/54) dedicated category by providing the same details (in case if you missed any) so that our community members can help you out.

If there is no response then let us know and we will try to help you out.

**Comment by derekperkins** [comment] 2023-07-27 01:53
The issue isn't grafana, it's that javascript can't handle integers larger than 2^53. Just cast your ints to strings for display
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by usmangt** [comment] 2023-08-03 08:54
Thanks @derekperkins for providing the answer.

I will now close this issue.

**Closed by usmangt** 2023-08-03 08:54 UTC
