### ISSUE TITLE
msg="Failed to look up user based on cookie" logger=context error="Error 1040: Too many connections"

### ISSUE THREAD

**Issue by izzie88** [grafana/grafana#27340] opened 2020-09-02 17:18 UTC
**What happened**: grafana was integrated with google Oauth. After sometime Unauthorized pop up keeps appearing on the Web UI when tables are auto-refreshing then I get logged out. in the logs i find this: "msg="Failed to look up user based on cookie" logger=context error="Error 1040: Too many connections""

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**: grafana on kubernetes + authentication using google Oauth + MySQL datasource

**Anything else we need to know?**: when I access a dashboard that does not use auto-refresh, i do not get logged out and the unauthorized popup does not show

**Environment**: Kubernetes/Docker
- Grafana version: latest
- Data source type & version: MySQL
- OS Grafana is installed on: Kubernetes
- User OS & Browser: MacOS and Chrome
- Grafana plugins: grafana-kubernetes-app,grafana-piechart-panel,simpod-json-datasource
- Others:

**Comment by hugohaggmark** [comment] 2020-09-03 08:30
@izzie88 does the dashboard queries take longer than your auto refresh setting? Also does `Grafana version: latest` mean `master` or `7.1.5`.

**Comment by marefr** [comment] 2020-09-04 09:06
Duplicate of #15316

**Comment by marefr** [comment] 2020-09-04 09:11
Your underlying problem is `Error 1040: Too many connections`, Please consider configuration of connection settings for MySQL.  [max_idle_conn](https://grafana.com/docs/grafana/latest/administration/configuration/#max_idle_conn), [max_open_conn](https://grafana.com/docs/grafana/latest/administration/configuration/#max_open_conn) and [conn_max_lifetime](https://grafana.com/docs/grafana/latest/administration/configuration/#conn_max_lifetime). If this is not a problem with too many connections to Grafana configuration database and instead MySQL data source queried in dashboards/panels you find similar settings in the [data source configuration](https://grafana.com/docs/grafana/latest/features/datasources/mysql/#data-source-options).

**Closed by marefr** 2020-09-04 09:11 UTC
Labels: type/duplicate
