### ISSUE TITLE
[Feature Request] Convert seconds to human readable time value

### ISSUE THREAD

**Issue by bogdanveres** [grafana/grafana#5271] opened 2016-06-03 14:32 UTC
Can you add for single stat panel a feature to convert seconds to a value that is easy to read? 
For example if I have 1432587 seconds and I want to convert this value to HH:MM:SS. This will result in something like: 16 days 13:56:27. Is it possible? [Here](https://www.tools4noobs.com/online_tools/seconds_to_hh_mm_ss/) is an example.

**Comment by torkelo** [comment] 2016-06-03 16:40
duplicate of https://github.com/grafana/grafana/issues/4747

**Closed by torkelo** 2016-06-03 16:40 UTC
