### ISSUE TITLE
[Feature Request] Alert list filter by notification channel

### ISSUE THREAD

**Issue by fredsmithjr** [grafana/grafana#9175] opened 2017-09-06 00:01 UTC
Please include this information:
- What Grafana version are you using? Master
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubuntu 16.04
 
In alerting list allow selecting a notification channel as a filter so you can add an extra notification channel to each.
Example: The team has a critical alert chat room BUT they should also alert the 24/7 monitoring team. This requires 2 notification channels on the same set of alerts. It would be easier to filter by them.

**Comment by torkelo** [comment] 2017-09-06 12:16
dupe of https://github.com/grafana/grafana/issues/9174

**Closed by torkelo** 2017-09-06 12:16 UTC
