### ISSUE TITLE
Global Variables

### ISSUE THREAD

**Issue by aflorezparra** [grafana/grafana#12095] opened 2018-05-29 09:47 UTC
Hi, I would like to know if you have any plan on when are you going to include global variables.
In addition, I would like to know if there is any possible workaround with the current Grafana 5.x.

Thanks in advance.

**Comment by marefr** [comment] 2018-05-29 10:10
Duplicate of #1959

**Closed by marefr** 2018-05-29 10:10 UTC
Labels: type: duplicate

**Comment by aflorezparra** [comment] 2018-05-29 10:27
Hi @marefr, sorry if u misunderstood me, I will give you a better explanation of what I wanted to achieve.
For each Graph you can define a customized link (Drilldown / detail link) . I want to define a global variable that could be reused in the URL of this links of all the visualizations in Grafana, it is across dashboards.

I followed the thread of #1959 but it does not get me to any solution of how to define a Global Variable.

I have been for some time struggling with this issue, I would be glad to get some hints on how to solve it. Thanks again!

**Comment by marefr** [comment] 2018-05-29 10:28
The referenced issue is a feature request which means that this is a feature we don't currently support.

**Comment by aflorezparra** [comment] 2018-05-29 10:38
Alright, I see it is mentioned , like around one year ago: "updated our roadmap: https://github.com/grafana/grafana/blob/master/ROADMAP.md it is very broad and not very detailed yet."

But couldnt find any description about this in the roadmap. Do you have an estimation of when this is planned for?

Thanks @marefr

**Comment by marefr** [comment] 2018-05-29 11:51
No, sorry cannot give you any estimation, but since it not on or current roadmap there's nothing we'll probably look into short term, more distant future far far away.

**Comment by aflorezparra** [comment] 2018-05-29 13:12
Thanks for your answers
