### ISSUE TITLE
Slow 'select measurement' rendering for InfluxDB

### ISSUE THREAD

**Issue by JozoVilcek** [grafana/grafana#2524] opened 2015-08-15 07:14 UTC
I am experimenting with grafana 2.1.1. When tying to populate graph from influxdb data source, I experience long lags on measurement selection. When I simply click in the box, grafana sends SHOW MEASUREMENTS query to influxdb. Response is returned in about 150ms. But for the drop down list to show up, I have to wait another 20s. Number of returned measurement is about 7k.

Is it supposed to be that slow?
If yes, is it possible to somehow set a LIMIT on select measurements queries?

**Comment by torkelo** [comment] 2015-08-15 16:01
This is bad, sorry for this. I will take a look at fixing this.  

The main issue is that if I use LIMIT on this query people will not able to use the the auto complete search to find the measurement they want. The fix for that would be to have a low limit, like 50 and issue repeated requests for each key entered, but do not think the InfluxDB 
SHOW MEASUREMENTS query supports regex match / filtering, or does it? ping @pauldix

One temporary work around is to pick tags before you pick measurement, this will limit the measurements to what exists for the tag filters selected.

**Comment by bubenkoff** [comment] 2015-08-16 17:46
+1 for solving this.
Show measurements does support where clause so with combination of limit it should suceed.

**Comment by torkelo** [comment] 2015-08-16 19:05
@bubenkoff do you have a syntax for that? I know it supports where clause for tags, but for the measurement name? haven't seen any example for such a query

**Comment by bubenkoff** [comment] 2015-08-17 07:19
you're right, existing where syntax doesn't help at all, if you only have measurements and no tags, which is my case
Looks like we have to request a change for it in influxdb

**Comment by bubenkoff** [comment] 2015-08-18 22:33
https://github.com/influxdb/influxdb/issues/3523

**Comment by torkelo** [comment] 2015-08-31 10:57
Its not much I can do here before InfluxDB implements the filtering.

**Comment by JozoVilcek** [comment] 2015-10-02 20:01
I have played with kairsdb backend, and grafana UI is much more responsive for roughly same number of metric names than with influxdb backend.

**Comment by pauldix** [comment] 2015-10-04 23:02
How many measurements do you have? If you're using InfluxDB, you really should be using tags. The whole reason we introduced tags was that searches in a flat measurement namespace didn't scale well if you had a large number of unique series.

We may introduce a feature to filter the measurement names, but I fear it will only be delaying the problem.

**Comment by JozoVilcek** [comment] 2015-10-05 07:34
It is about 7k measurements. It will grow and yes, long term solution is to for tags. 
Just wanted to point finger on different behavior in grafana when using influxdb a kairosdb backends.

**Comment by pauldix** [comment] 2015-10-07 06:06
enough people have said this is creating problems for them. So while we want to push people to use tags as a way to reduce the number of measurements they have, we'll add this feature to help ease the transition from the older 0.8 style to 0.9.

Issue added to InfluxDB: https://github.com/influxdb/influxdb/issues/4351

**Comment by torkelo** [comment] 2015-10-07 06:18
@pauldix thats great!

**Comment by XANi** [comment] 2016-02-11 15:30
Even with tags that can sometimes be a problem (for example imagine putting data from IDS or netflow collector with thousands of IPs in "src_ip" tag)

One way to make it a bit better is to not start searching while user is still typing in the field and maybe add optional "do not search if there is X or less characters in field". As it is now, firefox freezes and then times out JS every time I type just few characters in search...

**Comment by danielsand** [comment] 2016-03-07 16:52
hey,

since 0.10 they implemented reg exp matching for SHOW MEASUREMENTS with should tackle this problem.

SHOW MEASUREMENTS WITH MEASUREMENT =~ /searchterm.*/

if the input waits for the first for letters or an enter before shooting the query to influx db to display the search result it should work quiet well.

but still there is no initial list with all the entries - but i think this would be overkill :)

**Comment by XANi** [comment] 2016-03-07 18:01
>  but still there is no initial list with all the entries - but i think this would be overkill :)

I'd say the query for "empty" and first few characters (say 3-4) should be done with `limit 1000` to not overwhelm client. Maybe as a configurable option because some people might have a lot of metrics that start with common part

Currently typing just one letter is great way to freeze whole firefox for good few seconds

**Comment by danielsand** [comment] 2016-03-10 09:05
@XANi  https://github.com/influxdata/influxdb/issues/5635

**Comment by XANi** [comment] 2016-03-11 01:59
@danielsand 10k also doesn't exactly work smoothly

**Comment by danielsand** [comment] 2016-03-18 12:59
@XANi exactly

**Comment by hmcgonig** [comment] 2016-04-06 17:57
I can confirm this bug. My team was upgrading from influx .8 to .10 and after the upgrade grafana was painful to use. We ended up rolling back to influx .8 as a lot of our metrics had names that started with the same prefix (collectd, etc) so attempting to filter by "collectd" would fully freeze the browser.

**Comment by torkelo** [comment] 2016-04-06 18:02
Should that not be in tags? Sounds like a problem influxdb and also with metric layout , think influxdb 0.9 was designed to have very few measurements and the rest of series metadata in tags

**Comment by hmcgonig** [comment] 2016-04-06 18:06
Part of the issue could be that the typeahead seems to highlight all list items with the query string. I'd imagine doing a regex on potentially 10K+ things wouldn't be the best for browser performance. Could the max number of items in this suggestion dropdown simply be limited to 500? I think that would be a quick performance boost for those of us with tons of metrics.

**Comment by torkelo** [comment] 2016-04-06 18:14
for InfluxDB 0.11 the solunion is to use the regex filter for the show measurements query that was added in that version and limit to 100 or so results , a PR for that would be great

**Comment by XANi** [comment] 2016-04-06 19:28
@torkelo Or how about fixing it so it actually works on every data source instead of relying on each DB feature to limit responses ?

I mean sure it *should* send limit statement if DB can support it just for efficiency sake but until you limit it in grafana you will always get those edge issues

**Comment by torkelo** [comment] 2016-04-06 19:30
@XANi I had limits before but then people complained that they could not get auto complete for all their series names etc. And there there is centralised way to do this, all data sources have their own query editor and ways of fetching series names etc.

**Comment by XANi** [comment] 2016-04-06 19:48
@torkelo I'm not familiar with HTML5 but isn't there a way to page it inside scroll ? I think the problem here is not amount of data received but browser getting laggy when it have to display 1000 or 10k entries long pulldown menu

**Comment by hmcgonig** [comment] 2016-04-06 19:52
@XANi correct. The influx request itself is completing in around 1 second.

**Comment by torkelo** [comment] 2016-04-06 20:06
@XANi the  InfluxDB request to get series names used to take many many seconds when you had many series, not sure how it is for InfluxDB 0.9+ ,  

as I said the best thing to do here is to issue queries to InfluxDB as you type and limit to only top 100 so, PR from InfluxDB team or anyone would be very helpful.

**Comment by torkelo** [comment] 2016-04-06 20:10
here is the relevant code, https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/query_ctrl.ts#L162

In the beginning InfluxDB SHOW MEASUREMENT query did not support filtering, to get this performance the filtering has to be done on the InfluxDB side , much faster than doing regex matching in the Grafana web ui

**Comment by pauldix** [comment] 2016-04-06 20:15
I can see if someone from our end can take a look. Although I will say it's an anti-pattern in InfluxDB if a user has more than around 10k measurements (at least for the current version). Series metadata should be encoded in tags. The combination of measurement names and tags should keep things snappy.

**Comment by torkelo** [comment] 2016-04-06 20:19
@pauldix thanks for chiming in

Yes having more than 10K sounds like an anti pattern, still having around 5k might reasonably and should be fast in Grafana. And now there you can use regex filtering in `SHOW MEASUREMENTS` query I think grafana should use it, should make measurement exploration faster I hope.

**Comment by pauldix** [comment] 2016-04-06 20:20
agree, we'll take a look at the regex thing. Definitely want people to have
a good Grafana + InfluxDB experience

**Comment by XANi** [comment] 2016-04-07 07:24
@torkelo well even 1k makes firefox occasionally just completely freeze and it is still slow on chrome.

Regex + limit would be best for influx but still there should be at least a safeguard to not have 10k long pulldown in case of mistyping (or just someone testing DB config) because it is pretty hard to fix it if your browser is frozen. Even just "load first 1k records to pulldown" would at least stop it from freezing

**Comment by torkelo** [comment] 2016-04-07 11:08
Yes, as I said the limit should be top 100 or so

**Comment by flyersa** [comment] 2016-09-15 09:46
that is stil not addressed in the latest grafana version. It makes grafana almost useless for us with tens of thousand of series with inputs where we CANNOT use tags.

**Comment by torkelo** [comment] 2016-09-15 09:58
If you can't use tags, why use a tag based TSDB? 

Honestly it would be great to solve this, but no PR yet :(

**Closed** 2017-04-24 09:44 UTC
Labels: datasource: InfluxDB, P0: critical, state: help wanted (PR)
