### ISSUE TITLE
Custom refresh intervals resets on _JSON Model_ view

### ISSUE THREAD

**Issue by zaufi** [grafana/grafana#26722] opened 2020-07-31 09:18 UTC
**What happened**:
I have a dashboard w/ added `5s` refresh interval in addition to the standard set.
The dashboard is saved and when I visit _JSON Model_ the stored setting resets to defaults.

**What you expected to happen**:
My added `5s` interval doesn't disappear.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add `5s` as the very first item of refresh intervals.
2. Save the dashboard.
3. Go to _JSON Model_.
4. Return to the dashboard view (by `Esc` key or clicking the back arrow button)
5. Go to _General_ dashboard settings again.
6. See your `5s` added interval has disappeared.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.1
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Firefox 79
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment] 2020-08-09 06:06
duplicate of https://github.com/grafana/grafana/issues/26581

Fixed in 7.1.2

**Closed by torkelo** 2020-08-09 06:06 UTC
