### ISSUE TITLE
Show context broken if expanded at the top

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#23716] opened 2020-04-20 18:12 UTC
**What happened**:

When you use `show context` close to the top of the page.

You get part of the show context panel cropped see below:
![image](https://user-images.githubusercontent.com/1053421/79784856-e4d37480-8310-11ea-952c-cc0d2c46567c.png)

**What you expected to happen**:

The panel should take over the histogram.

**How to reproduce it (as minimally and precisely as possible)**:

Show context at the top.

**Environment**:
- Grafana version: Grafana v6.7.0 (c4656a885d)
- Data source type & version: Loki

**Comment by Estrax** [comment] 2020-05-15 06:56
Already described in #20624

**Comment by ivanahuckova** [comment] 2020-07-06 13:44
Closing issue as it is duplicate of https://github.com/grafana/grafana/issues/22126.

**Closed by ivanahuckova** 2020-07-06 13:44 UTC
Labels: area/explore, datasource/Loki
