### ISSUE TITLE
Alerts based on multiple queries

### ISSUE THREAD

**Issue by mnuic** [grafana/grafana#24096] opened 2020-04-30 12:13 UTC
**What would you like to be added**:
Condition for alerting that can be set based on a multiple queries, eg. 
```
WHEN avg() OF query (A,2 min, now) IS ABOVE 95% of query (B, 2 min, now)
```

**Why is this needed**:
We use grafana for alerting with Nomad metrics, specifically for tracking cpu and memory of Nomad deployed jobs. Jobs are defined with resources that Nomad allocate from OS to use (cpu, memory, ...).

For example, when jobs memory hit the defined resources target or above it gets OOM killed. To prevent that we define alert when memory is 95% of defined memory resource. It's OK to define alert manually when you have a few services, but with 1000 of them it gets a bit harder. So we would like to use nomad metrics for `stats.gauges.nomad.client.allocs.memory.usage` and `stats.gauges.nomad.client.allocs.memory.allocated` as mentiond:

`A=stats.gauges.nomad.client.allocs.memory.usage`
`B=stats.gauges.nomad.client.allocs.memory.allocated`
and define alert as:
`WHEN avg() OF query (A,2 min, now) IS ABOVE 95% of query (B, 2 min, now)`

**Comment by torkelo** [comment] 2020-04-30 14:06
duplicate of https://github.com/grafana/grafana/issues/6593

**Closed by torkelo** 2020-04-30 14:06 UTC
