### ISSUE TITLE
Heatmap legend not scaling down correctly

### ISSUE THREAD

**Issue by der-eismann** [grafana/grafana#20730] opened 2019-11-28 09:40 UTC
**What happened**: We use a heatmap with buckets from 0 - 1 in 0.02 steps and the legend is not readable when scaling down the panel since too many numbers are shown:
![screenshot](https://user-images.githubusercontent.com/10406217/69794761-254c1d80-11cb-11ea-97cb-0ffcd65c2803.png)

**What you expected to happen**: Only show 10-20 numbers instead of 40 when scaling down the panel.

**How to reproduce it (as minimally and precisely as possible)**: See above

**Anything else we need to know?**: n/a

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: official Docker container on CoreOS
- User OS & Browser: Fedora 31 & Chrome 78
- Grafana plugins: all that are included in official Docker container

**Comment by torkelo** [comment] 2019-12-02 21:24
duplicate of https://github.com/grafana/grafana/issues/11342

**Closed by torkelo** 2019-12-02 21:24 UTC
