### ISSUE TITLE
Using Variables/queries in thresholds

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#25127] opened 2020-05-26 19:05 UTC
**What would you like to be added**:
That I can use query/variable in thresholds
**Why is this needed**:
For dynamical thresholds.

**Comment by torkelo** [comment] 2020-05-27 07:46
duplicate of https://github.com/grafana/grafana/issues/159

**Closed by torkelo** 2020-05-27 07:46 UTC

**Comment by radimkohout** [comment] 2020-05-27 14:39
Will It ever be done? The issue that you are mentioning is 6 years old

**Comment by torkelo** [comment] 2020-05-27 16:57
hope so

**Comment by radimkohout** [comment] 2020-05-28 11:15
Is there any expectation when?

**Comment by Freeze777** [comment] 2020-06-04 13:45
Any updates?

**Comment by radimkohout** [comment] 2020-06-06 18:56
Nope
