### ISSUE TITLE
v7: new table panel - hiding values now means those variables unusable?

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#25289] opened 2020-06-02 10:41 UTC
**What happened**:
In the old table panel you could hide columns but still reference them in variables. In the new v7 table panel this no longer seems possible. Hiding a column means the variable can no no longer be referenced for example, within data links on other columns.

**What you expected to happen**:
Same behaviour as the previous table panel, for example, I want to select a column `src` from my data source which is a source link to an image. I don't want to show `src` within my table so I hide it. However, I want to use `src` within another fields data link so I can have a link that opens the image.

**How to reproduce it (as minimally and precisely as possible)**:
- Add a table panel with a query that shows some column values.
- Add a column override `Data link` property to column (a) which references a variable value of column (b) for example a `Title` and `URL` of: `${__data.fields[src]}` where `src` is the name of column (b).
- Confirm that the `Title` and `URL` of the data link shows the correct value (the value of column (b) `src`).
- Edit the query and add a `Transform` type `Organize fields` and hide column (b).
- Now see that the `Title` and `URL` of the data link shows the literal `${__data.fields[src]}` and no longer the correct value.

**Anything else we need to know?**:
Hidden values **ARE** still available within Grafana, say for example if you have a stat panel showing results from a table panel dashboard it does still show hidden values.

**Environment**:
- Grafana version: Nightly grafana_7.1.0~d3472779pre_amd64
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu v19.10
- User OS & Browser: Ubuntu v20.04 Firefox v76.0.1
- Grafana plugins:
- Others:

**Comment by seanlaff** [comment] 2020-06-18 19:09
In v6 tables we often have a `Name` column with a hidden `OID` column next to it. We make urls on the `Name` column by referencing that row's hidden `OID` column.

In the new dataframe model, my row has fields for both, however the `OID` vanishes when I hide the column.

I'd like to access the hidden `oid` field like so 🙂  

<img width="306" alt="Screen Shot 2020-06-18 at 2 51 54 PM" src="https://user-images.githubusercontent.com/3194832/85060745-bd175600-b173-11ea-9e80-f81b87e27615.png">

**Comment by dprokop** [comment] 2020-06-26 07:47
@therealcodlord @seanlaff indeed this is a current constraint with the transformed data basically removing the hidden fields in the result data frame. We need to adjust the model slightly to allow this behavior, will probably work on this after 7.1

**Comment by giampierod** [comment] 2020-07-01 17:39
How is it possible that you removed a capability and then call it a feature? In the old table there was an actual setting to make a column hidden in the visualization that didn't transform the data. Can you bring that back at least? This is a regression of capabilities plain and simple.

**Comment by torkelo** [comment] 2020-07-01 18:00
yes, sorry about that. It's not easy to move the platform forward and always have 100% backward compatibility, we are working on restoring this, will likely come in v7.2

**Comment by torkelo** [comment] 2020-07-01 18:01
duplicate of https://github.com/grafana/grafana/issues/24092

**Closed by torkelo** 2020-07-01 18:01 UTC
Labels: area/dashboard/data-links, type/feature-request
