### ISSUE TITLE
Failed to lookup user cookie

### ISSUE THREAD

**Issue by adrianromanko** [grafana/grafana#19958] opened 2019-10-22 20:23 UTC
**What happened**:
Too many redirects error OR `lvl=eror msg="failed to look up user based on cookie”`

**What you expected to happen**:
Authenticate user without using sticky sessions.

**How to reproduce it (as minimally and precisely as possible)**:
Run grafana on 2+ instances in HA

**Anything else we need to know?**:
- Grafana 6.3.5
- Generic oauth setup
- Running 3 instances of grafana
- Database is mariadb - single master, 2 replicated slaves setup on the connection
- Related issues:
  - #15316
  - #13497

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: mariadb
- OS Grafana is installed on: centos
- User OS & Browser: chrome v59+
- Grafana plugins: default
- Others: n/a

Authentication with instance 0 is OK
Open another browser window and hit instance 1/2/3, i'll get the following log messages.

lvl=eror msg="failed to look up user based on cookie"

Running a single instance of Grafana works great.

**Comment by dprokop** [comment] 2019-10-24 06:41
@marefr can you pls take a look at this one?

**Comment by amitkumarcn** [comment] 2019-11-04 08:43
@adrianromanko : Can you check if global auto-commit is enabled in your database.? If not , please try to enable it in all the nodes. I got this issue fixed by doing it.

**Comment by marefr** [comment] 2019-11-12 15:51
Duplicate of #15316

**Closed** 2019-11-12 15:51 UTC
Labels: type/duplicate
