### ISSUE TITLE
FR: To place "Update available!"-marked plugins on the top of the list 

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#17486] opened 2019-06-07 15:28 UTC
**What would you like to be added**:
To place "Update available!"-marked plugins on the top of the list.
Alternative way is to make separate category for plugins with any notices: 

![image](https://user-images.githubusercontent.com/1700286/59115296-a8de2d80-8951-11e9-9512-5dd4ae5f562a.png)

**Why is this needed**:
Plugins locates in alphabetical order now. 
So some of those having **Update Available!** notice (or any other notice) must be more visible.

**Comment by hugohaggmark** [comment] 2019-06-10 12:53
Duplicate of #15657

**Closed** 2019-06-10 12:53 UTC
Labels: type/duplicate
