### ISSUE TITLE
[Feature request] Extend user roles to dashboards or dashboard groups

### ISSUE THREAD

**Issue by cosmos1978** [grafana/grafana#7620] opened 2017-02-20 13:10 UTC
It would be really nice to have access rights on dashboards or groups of dashboards.
Our setup has almost 50 users and growing and many of these users want to create or at least manage their own dashboards. I prefer not to give them all editor roles as they could easily mess up dashboards of other users.

Right now I am the only one with full editor rights and I have to give other users read only editor roles so they can design dashboards and the email me the json so I can add it.
This however is growing out of proportions due the popularity of grafana in my company.

So For large userbases with multiple contributors it really is a must to have roles targeted to specific dashboard groups.
To work around this issue I even created multiple organizations so some users can have editor rights and at least save their work since the json export method only works if you do not close your browser.

Thanks,

**Comment by torkelo** [comment] 2017-02-20 13:15
duplicate of https://github.com/grafana/grafana/issues/1128

**Comment by torkelo** [comment] 2017-02-20 13:15
see also https://github.com/grafana/grafana/issues/1611

**Closed by torkelo** 2017-02-20 13:15 UTC
