### ISSUE TITLE
Download logs from a dashboard does not work

### ISSUE THREAD

**Issue by SSvilen** [grafana/grafana#53479] opened 2022-08-09 13:41 UTC
**Describe the bug**
I have a dashboard with a logs panel, where logs are being displayed. If there are multiple data frames and I go to Inspect - Data  and click Download logs, only the last data frame is being downloaded, regardless which data frame I select.
Download CSV seems to work normally.

**To Reproduce**
1. Create dashboard with log panel
2. Build a loki query, that contains data with different unique labels
3. Try to download the data

**Expected behavior**
Download logs should work exaclty like Download CSV.

**Comment by dannykopping** [comment] 2022-08-09 15:54
@SSvilen just be aware I have transferred this issue to [grafana/grafana](https://github.com/grafana/grafana), since Loki is just the database and not the Grafana plugin.

**Comment by SSvilen** [comment] 2022-08-09 20:15
@dannykopping yeah, I thought that may be it belongs to grafana repo, but was not sure where the plugin is being developed.

**Comment by usmangt** [comment] 2022-08-12 08:44
Hi @SSvilen,

Thanks for opening this case.

I tried to reproduce it but seems to be working fine. Can you please try to reproduce this same case on https://play.grafana.org/ ?

**Comment by gabor** [comment] 2022-08-15 15:08
hi @SSvilen, currently the two buttons works slightly differently, download-csv downloads the selected dataframe, and download-logs downloads all the data (all the dataframes).

i agree this is confusing, i created an issue specially for this problem at https://github.com/grafana/grafana/issues/53742

for now, as a workaround, if you upgrade to grafana9, loki logs will always be in a single dataframe, so both the download-csv and the download-logs buttons will work the same way in that case. i hope that helps.

**Closed by gabor** 2022-08-15 15:08 UTC
Labels: needs more info, datasource/Loki

**Comment by SSvilen** [comment] 2022-08-17 09:52
@gabor great, thanks. 
If Grafana 9 uses single dataframe, that would do.
