### ISSUE TITLE
[5.0.0] Sidemenu not present in anonymous mode

### ISSUE THREAD

**Issue by ptitou** [grafana/grafana#11136] opened 2018-03-07 09:53 UTC
- What Grafana version are you using : **Grafana v5.0.0 (commit: af6e283)**

- What datasource are you using : **influxdb**

- What OS are you running grafana on : **CentOS Linux release 7.2.1511 (Core)**

- What did you do : **access homepage in anonymous context**

- What was the expected result : 
**Sidemenu will appear to allow connection or dashboard browsing**

- What happened instead?

Sidemenu is hidden, even the grafana logo. If we look in html source, we can see this : 

`<body class="theme-light sidemenu-hidden page-dashboard sidemenu-open">`

after a refresh, the panel come back and class sidemenu-hidden disappear.

`<body class="theme-light sidemenu-open page-dashboard">`

Tested with Chrome v64.0.3282.186, Opera v51.0.2830.40, IE 11.0.9600.18893 on windows 7 x64

**Comment by bergquist** [comment] 2018-03-07 11:16
Cant reproduce this... Do you see any errors in the browser developer console?

**Comment by ptitou** [comment] 2018-03-07 12:23
Nothing on the console :(

but if I play with keyboard shorcut (g h), I've got the same effect (only in anonymous mode)

**Comment by DankMinhKhoa** [comment] 2018-03-09 20:10
same. Grafana running on debian stretch Linux 4.9.0-6-amd64 through nginx. f5 and the sidebar appears again.

**Comment by pronichev** [comment] 2018-03-19 11:55
I have the same behaviour. 
In anonymous session click on dashboards button on sidebar. Grafana logo will disappear.

**Comment by torkelo** [comment] 2018-07-01 14:41
Closing this, very strange, no other similar reports and unable to replicate. Try latest Grafana v5.2. 

If you have any more info on how to replicate we will reopen right way.

**Closed by torkelo** 2018-07-01 14:41 UTC
Labels: state: needs more detail

**Comment by mattrussi** [comment] 2018-08-22 18:36
@torkelo We've experienced this as well on Grafana v5.2.2 (commit: aeaf7b2). For our situation, I think I've narrowed it down to having a "Home Dashboard" set to something other than "Default" for an organization. No errors are in the browser's console when we see this happen. We've been able to replicate this on Chrome 68 and FireFox 61.0.2.

There are no specific team permissions set for the dashboard which is defined as "Home Dashboard".

I uploaded a quick video of what it looks like. Apologies for the low quality. In the video, I'm an un-authenticated user on the "Home Dashboard" page of "Prometheus Stats". I reload the page and the sidemenu comes back. I click on the menu icon and the sidemenu disappears. I then choose the "Ceph - Cluster" dashboard, and the sidemenu is still gone. I reload that page and the sidemenu reappears until I click on the menu button which takes me back to the "Home Dashboard" with the sidemenu hidden.

https://youtu.be/iCING5pMwTA

**Enabled Auth Types**

auth.anonymous |  
-- | --
enable | true
org_name | default
org_role | Viewer

auth.ldap |  
-- | --
allow_sign_up | true
config_file | config/ldap.toml
enabled | true

**Comment by torkelo** [comment] 2018-08-24 09:06
strange, unable to replicate this either. 

If you go to this dashboard: https://play.grafana.org/d/000000003/big-dashboard?orgId=1 

then navigate to home dashboard using sidemenu, does sidemenu disappear for you?

**Comment by mattrussi** [comment] 2018-08-24 13:34
Unfortunately, I haven't been able to replicate it on play.grafana.org. 😕

Is there anything in particular that we should try for debugging on our side since you can't replicate it?

**Comment by daldoyle** [comment] 2018-09-05 19:44
Not the OP but we see this too. It never seems to happens if you link directly to it, but does when there's the quick redirect upon visiting just the base URL, https://<host>/grafana/, or when clicking the "Home" button via the left sidebar. There is a very brief flicker of the 404 page that shows when you have a bad URL and then it loads up the home page but without the side bar visible. A reload of the now full URL results in the sidebar being shown. 


On the play.grafana.org server I cannot seem to get it to happen, which is bizarre. We are running the same version of Grafana as is current, 5.2.3. The only thing maybe relevant here is we are proxy passing grafana through Apache, but it's pretty much a straight translation of the /grafana/ location. Maybe issue is related to when it isn't located at / location?

Here's the network call stack I see in Chrome's debugger, I don't know if that's enough to provide any hints or guidance. There are no JS errors that I can see in console.

1. https://<host>/grafana/api/dashboards/home => {"redirectUri":"/grafana/d/000000002/home-dashboard"}
2. https://<host>/grafana/public/img/graph404.svg
3. https://<host>/grafana/api/dashboards/uid/000000002 => <huge json blob describing dashboard>

Then dashboard loads and all of the following requests are regular ones I would expect retrieving template vars and graphs and such.

**Comment by daldoyle** [comment] 2018-09-05 21:09
Doing a bit of testing, this does seem to be the case when having a non / root URL, such as "/grafana" and with anonymous views. If I change it so that just the hostname is the root URL in grafana.ini (effectively making it /) then I never see this behavior. If I change to to <host>/grafana as the root URL I can reproduce it reliably.

If I am logged in I do not see this behavior.

**Comment by marefr** [comment] 2018-09-06 08:27
@daldoyle thanks for the additional details. We'll investigate this and will reopen if we can reproduce

**Comment by marefr** [comment] 2018-09-07 13:39
Was able to reproduce using 5.2.3, anonymous auth, custom home dashboard and reverse proxy with sub path.

Good news! Thing is that the "Page not found/404 flicker" was fixed in #12429 and that actually fixes this problem. #12429 fix is included in v5.3.0-beta1 released yesterday and will be included in upcoming v5.3.0 stable release. You can always use nightly build or build from source as well to get the fix.

**Comment by daldoyle** [comment] 2018-09-07 13:49
Great news Marcus, thanks! Looking forward to 5.3.0 for a variety of other reasons, just another on the pile. :)
