### ISSUE TITLE
A common panel can be selected and inserted into current dashboard

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#19917] opened 2019-10-19 02:50 UTC
**What would you like to be added**:
A common panel can be selected and inserted in current dashboard
**Why is this needed**:
Sometimes when created series of relative dashboards there is always some same panels in every dashboard. Update one means update it in each of them. So I'm thinking a common one that one place change updates all.

**Comment by torkelo** [comment] 2019-10-19 07:24
duplicate of https://github.com/grafana/grafana/issues/1803

**Closed by torkelo** 2019-10-19 07:24 UTC
