### ISSUE TITLE
Grafana oauth session is not expired when directly invalidate user session from Keycloak

### ISSUE THREAD

**Issue by zhanglijingisme** [grafana/grafana#13974] opened 2018-11-06 09:28 UTC
**What Grafana version are you using?**

v5.2.4

**What datasource are you using?**

Prometheus

**What OS are you running grafana on?**

CentOS 7.5

**What did you do?**

Do Generic OAuth with Keycloak. On Keycloak UI, directly invalidate user session from "Users" -> "Sessions"

**What was the expected result?**

Grafana session is invalidated, user logout

**What happened instead?**

Grafana session remains active as long as browser is not closed or "Signout" button from Grafana is explicitly pushed.

Even when there is defined tight "session_life_time" (e.g. 1 minute) for Grafana and autorefresh is set off, still session is valid in Grafana after some minutes inactivity.

So, seems that Grafana is not checking the CKEY token existence at all after login. 

This happens not only from Keycloak, but also from other client using SSO with CKEY. It must be implemented in Grafana to provide secure and coherent session handling.

**Comment by marefr** [comment] 2018-11-06 09:36
Duplicate of #12131

**Closed by marefr** 2018-11-06 09:36 UTC
