### ISSUE TITLE
Using Prometheus as source, sort only works in instant query

### ISSUE THREAD

**Issue by lfasci** [grafana/grafana#20853] opened 2019-12-04 06:43 UTC
Using Bar Guage to display a query, result are sorted only if you select instant query.

I use the following query on a temperatures Prometheus DB

topk(7, temperatura), 

If I select instant, results are sorted, otherwise they are not. I also tried to use the functions sort() and sort_asc() but nothing changes
![bug](https://user-images.githubusercontent.com/16296629/70119064-c0307600-1669-11ea-82cd-e75a4047346d.png)

Environment:
- Grafana version: 6.4.3
- Data source type & version: Prometheu
- OS Grafana is installed on: Dietpi
- User OS & Browser: Windows 10, Firefox latest
- Grafana plugins: Bar Gauge beta

**Comment by torkelo** [comment] 2019-12-04 08:22
dupe of https://github.com/grafana/grafana/issues/17245

**Closed by torkelo** 2019-12-04 08:22 UTC
