### ISSUE TITLE
Alerting doesn't work for library panels

### ISSUE THREAD

**Issue by amwolff** [grafana/grafana#37455] opened 2021-08-02 15:01 UTC
**What happened**:

I created multiple dashboards, and there are library panels shared between them. I set up alerts for these library panels, but they never fire, even though they evaluate as `firing`.

![1](https://user-images.githubusercontent.com/30234756/127880117-d51873ca-e78c-4ce5-a991-8151c19ce004.png)

![2](https://user-images.githubusercontent.com/30234756/127880132-77a1281b-e7bd-43a4-b09d-3e8d211390d1.png)

```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": "true = true",
  "timeMs": "5.135ms",
  "matches": [
    {
      "metric": "redacted",
      "value": 100
    }
  ],

[...]

}
```

![4](https://user-images.githubusercontent.com/30234756/127880180-2bb4f869-a0fa-4884-a236-cc76b3d419a0.png)

There's nothing on Alerting/Alert rules page. It's like I didn't create anything.

**What you expected to happen**:

I expected alerts to work as intended. I couldn't find anything in docs that alerts won't work with library panels.

**How to reproduce it (as minimally and precisely as possible)**:

Create:
1. two dashboards;
2. a library panel shared between them;
3. alert on the library panel.

**Anything else we need to know?**:

1. I couldn't find anything significant in Grafana's logs;
2. The source of dashboards I had problems with is publicly available [here](https://github.com/storj/gateway-mt/tree/main/grafana).

**Environment**:
- Grafana version: 8.0.6
- Data source type & version:
  - Prometheus, `version=2.28.0, branch=HEAD, revision=ff58416a0b0224bab1f38f949f7d7c2a0f658940`
- OS Grafana is installed on:
  - Debian
  - Grafana runs in Docker container from an official Grafana's Docker image
- User OS & Browser: n/a
- Grafana plugins: none
- Others: n/a

**Comment by tskarhed** [comment] 2021-08-03 14:53
The exact same alert setup on the same panel that isn't a library panel has the expected behaviour. Couldn't find anything under alerts.

**Comment by hugohaggmark** [comment] 2021-09-09 08:11
@torkelo thinking about this issue, for the old alerting system, this would mean an alert rule would be created for each instance of a library panel with the alert rule. Is this something we want to enable?

**Comment by torkelo** [comment] 2021-09-11 04:48
No its not. And defining alert rules as part of panels is going away anyway as part of next gen alerting

**Comment by hugohaggmark** [comment] 2021-09-13 04:00
Closing this because it's working as intended, you can always open a discussion on Github discussions if this is a feature that you want to see in future versions of Grafana. Thank you for taking the time to create the issue.

All the best!

**Closed by hugohaggmark** 2021-09-13 04:00 UTC
Labels: type/bug, area/alerting, area/frontend/library-panels
