### ISSUE TITLE
Time series panel: axis override ignored when units match

### ISSUE THREAD

**Issue by bmerry** [grafana/grafana#37489] opened 2021-08-03 13:59 UTC
**What happened**: I'm testing out the new Time Series panel to see if it can replace our old graph panels. We have a graph with multiple series, which are split across Y two axes. The units are the same (Hz), but usually the scales are very different, which is why we don't want them all on the same Y axis (the time series for rare events would be squashed onto the axis by the axis scaling for the series for common events).

I've tried to replicate that with the new Time Series panel by setting a series override to specify the axis to use, but it is ignored unless I also override the units to a *different* unit.

**What you expected to happen**: I expect that when all the time series share the same unit, but some are overridden to use a Y axis on the right, it will do so.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a new dashboard
- Add a new panel, with the default random walk query.
- Add a transformation of type "Add field from calculation", mode "Binary operation", computing "A series" * 2.
- Add a field override for the field with name "A-series * 2", with override Axis > Placement set to Right.

![image](https://user-images.githubusercontent.com/1963944/128028455-f00a89df-4888-4988-9e04-519b06d79d6c.png)

This has no effect. Next, add another override for the field, setting Standard options > Unit to Short. Now the right Y axis appears, and the graphs appear more-or-less overlaid as the axis scaling is independent (this is the desired outcome). If the overall unit for the panel is set to Short as well, then it goes back to ignoring the axis override.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Prometheus (but as shown above, it's not source-dependent)
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04, Firefox 90.0
- Grafana plugins: out-of-the-box defaults
- Others:

**Comment by torkelo** [comment] 2021-08-05 16:38
duplicate of https://github.com/grafana/grafana/issues/32165

**Closed by torkelo** 2021-08-05 16:38 UTC
