### ISSUE TITLE
Stat Panel: Duration(s) unit not working

### ISSUE THREAD

**Issue by twbecker** [grafana/grafana#30940] opened 2021-02-05 15:20 UTC
![DurationUnitBroken](https://user-images.githubusercontent.com/1576404/107052592-dc630200-679b-11eb-8871-e535c109ee3e.png)

**What happened**:
Immediately upon upgrade from 7.3.7 -> 7.4.0 a stat panel broke, showing the "No Value" value instead of the duration as it's configured to.

**What you expected to happen**:
The duration value should be displayed (e.g. 4 hours).

**How to reproduce it (as minimally and precisely as possible)**:
Choose duration (s) as the unit for a integral field.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Prometheus 
- OS Grafana is installed on: Centos 7
- User OS & Browser: Firefox

**Comment by dswarbrick** [comment] 2021-02-05 17:16
Confirmed, happening for me too.

**Comment by peterholmberg** [comment] 2021-02-08 09:47
Possible dupe of https://github.com/grafana/grafana/issues/30938

**Closed** 2021-02-08 12:02 UTC
Labels: type/bug
