### ISSUE TITLE
"Line limit" field in Loki query in Grafana explorer does not work

### ISSUE THREAD

**Issue by swisspol** [grafana/grafana#26687] opened 2020-07-30 05:30 UTC
**What happened**:
"Line limit" field in Loki query in Grafana explorer does not work: whatever you enter in the field, the Loki API query argument still use the default limit for the data source (2500 in our case, coming from JSON provisioning), even though the UI says it uses the new limit.

![image](https://user-images.githubusercontent.com/627915/88883148-6d9f5d80-d1e8-11ea-9d30-ed41db3bc0ea.png)

**What you expected to happen**:
Setting a custom "Line limit" in the query actually works.

**How to reproduce it (as minimally and precisely as possible)**:
- Set line limit to a custom value
- Notice the UI shows the new value
- Open Chrome inspector and look at XHR API call to Loki
- Notice passed limit is not the value from the text field

**Anything else we need to know?**:
n/a

**Environment**:
- Grafana version: Grafana 7.1.1
- Data source type & version: Loki 1.5.0
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Chrome

**Comment by aocenas** [comment] 2020-09-30 08:59
This seems like a duplicate of https://github.com/grafana/grafana/issues/26688 so closing this.

**Closed by aocenas** 2020-09-30 08:59 UTC
Labels: area/explore, datasource/Loki, needs investigation
