### ISSUE TITLE
Axis autoscaling does not take into account thresholds

### ISSUE THREAD

**Issue by dzbarsky** [grafana/grafana#14372] opened 2018-12-07 03:20 UTC
### What Grafana version are you using?
5.2.2

### What datasource are you using?
Custom one we wrote, don't think it's relevant here.

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do? 
Set threshold on a graph that did not have y-min/y-max (i.e. defaulted to auto), plotted a series

### What was the expected result?
y-axis would scale to include series and all thresholds in view

### What happened instead?
y-axis only scales to include the series. theresholds may be out of view if series is far from them

### If related to metric query / data viz:
not relevant?

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
not relevant?

**Comment by torkelo** [comment] 2018-12-07 07:45
dupe of https://github.com/grafana/grafana/issues/5984

**Closed by torkelo** 2018-12-07 07:45 UTC
