### ISSUE TITLE
CloudWatch graphs with multiple multi-value dimension variables don't work

### ISSUE THREAD

**Issue by joedj** [grafana/grafana#17949] opened 2019-07-05 02:30 UTC
**What happened**:
CloudWatch graphs with multiple, multi-value variable dimensions do not show any data.
This appears to be because the second multi-value variable is sent as a list, surrounded by `{}`.

For example, a graph with two variable dimensions, both multi-value:
`ClusterName=$Cluster`
`ServiceName=$Service`

If I replace either (or both) of those dimensions with a literal value, the query works.  However, using variables for both dimensions does not work, even if only a single value is selected in the multi-value dropdown.

Somewhat-related issues:
https://github.com/grafana/grafana/issues/14451
https://github.com/grafana/grafana/issues/8939
https://github.com/grafana/grafana/issues/9903#issuecomment-391315894

<img src="https://joedj.net/cloudwatch.png" />

**What you expected to happen**:
Data is shown.

**Environment**:
- Grafana version: Grafana v6.2.1 (9e40b07)
- Data source type & version: CloudWatch
- OS Grafana is installed on: Linux
- User OS & Browser: Mac, Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-07-05 05:08
This use of variables is not currently supported by the CloudWatch data source (mostly because the cloudwatch api makes this hard)

**Comment by torkelo** [comment] 2019-07-05 05:46
looks like a dupe of https://github.com/grafana/grafana/issues/14451

**Comment by joedj** [comment] 2019-07-05 05:49
I don't think this is exactly a dupe of #14451, at least the way #14451 has been interpreted - #14451 seems to be about supporting multi-value variables for `MetricName`, where this issue is about better support for multi-value varialbes for `Dimension` (where they are already, at least partially, supported).

**Comment by torkelo** [comment] 2019-07-05 05:56
ok, sorry reopening

**Comment by kanbara** [comment] 2019-08-05 15:38
I'm also seeing this exact issue, and a lot of our metrics have two variables that we formerly were using  prometheus to scrape and doing something like `query_expr by (service, cluster)`. It would be perfect for us if this were better supported.

**Comment by sunker** [comment] 2019-10-01 09:02
I agree it's a bug that not more than one multiselect variable is supported, bu I also think it's wrong that Grafana is creating new queries based on the multiselect values. This should be done in the cloudwatch API and if it's not supported there we should not provide workarounds for that. 

@mtanda, doesn't the API support chained dimensions so that instead of firing off many queries, we just append the dimensions. Like this `Dimensions = InstanceId: 1, InstanceId: 2`

**Comment by mtanda** [comment] 2019-10-02 15:35
I didn't try yet, but Search expresssion could handle such query, but it's very hacky way.
I don't recommend to use it.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/search-expression-examples.html

I don't expect to use the feature for multiple variables.
Expanding query for all possible combination will make many invalid dimensions.

I think one possible solution is expanding query editor to support JSON string dimension.

Template variable `$dimensions` holds following values.
- { "ClusterName": "c1", "ServiceName": "s1" }
- { "ClusterName": "c1", "ServiceName": "s2" }
- { "ClusterName": "c1", "ServiceName": "s3" }
- { "ClusterName": "c2", "ServiceName": "s1" }
- { "ClusterName": "c2", "ServiceName": "s2" }

And specifying `$dimensions` in CloudWatch query editor.

**Closed** 2019-11-14 09:59 UTC
Labels: datasource/CloudWatch, type/feature-request
