### ISSUE TITLE
Force refId to be unique

### ISSUE THREAD

**Issue by dupondje** [grafana/grafana#28104] opened 2020-10-08 07:33 UTC
**What happened**:

When upgrading Grafana from 7.1.5 to 7.2.0, it adds refId's to the queries that don't have one:

```
    {
      "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
      "format": "time_series",
      "intervalFactor": 1,
      "legendFormat": " Delete Multi"
    },
```

Becomes

```   
        {
          "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
          "format": "time_series",
          "intervalFactor": 1,
          "legendFormat": " Delete Multi",
          "refId": "NA"
        },
```

**What you expected to happen**:
All queries outside the A-Z range now have NA as refId. Which causes other issues:
https://github.com/grafana/grafana/issues/27957

First of all Grafana should handle it correctly when upgrading, so it assigns a unique refId to the queries.
Next to that a constraint should be added that the refId is always unique.

**Comment by hugohaggmark** [comment] 2020-10-08 10:46
Officially we still don't support more than [26 queries per panel](https://github.com/grafana/grafana/issues/4978) but to repro this issue you can try to import a dashboard like the one below and you will see that after the `"refId" : "Z"` the refIds will be assigned `"refId" : "NA"` for every target following `"refId" : "Z"`

```json
{
  "__inputs": [
    {
      "name": "DS_GDEV-PROMETHEUS",
      "label": "gdev-prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.3.0-pre"
    },
    {
      "type": "panel",
      "id": "graph",
      "name": "Graph",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "prometheus",
      "name": "Prometheus",
      "version": "1.0.0"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "${DS_GDEV-PROMETHEUS}",
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "7.3.0-pre",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "mysql_com_admin_commands",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_db",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_db_upgrade",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_event",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_function",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_procedure",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_server",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_table",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_tablespace",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_alter_user",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_analyze",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_assign_to_keycache",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_begin",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_binlog",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_call_procedure",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_change_db",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_change_master",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_check",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_checksum",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_commit",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_db",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_event",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_function",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_index",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_procedure",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_server",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_table",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_trigger",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_udf",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_user",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_create_view",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_dealloc_sql",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_delete",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_delete_multi",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_do",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_db",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_event",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_function",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_index",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_procedure",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_server",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_table",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_trigger",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_user",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_drop_view",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_empty_query",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_execute_sql",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_flush",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_get_diagnostics",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_grant",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_ha_close",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_ha_open",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_ha_read",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_help",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_insert",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_insert_select",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_install_plugin",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_kill",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_load",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_lock_tables",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_optimize",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_preload_keys",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_prepare_sql",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_purge",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_purge_before_date",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_release_savepoint",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_rename_table",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_rename_user",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_repair",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_replace",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_replace_select",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_reset",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_resignal",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_revoke",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_revoke_all",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_rollback",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_rollback_to_savepoint",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_savepoint",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_select",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_set_option",
          "interval": "",
          "legendFormat": ""
        },
        {
          "expr": "mysql_com_show_binlog_events",
          "interval": "",
          "legendFormat": ""
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-5m",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Prometheus MySql 158",
  "uid": "LUP5GV5Gz",
  "version": 1
}

```

**Comment by PaulYuanJ** [comment] 2020-10-13 01:06
I have found the workaround:
`{
    "datasource": "Prod_Prometheus_Thanos",
    "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"10.67.231.60:9100\",mode=\"idle\"}[5m])) * 100)",
    "interval": "",
    "legendFormat": "10.67.231.60 CPU",
    "refId": "717"
}`

As you see, we have 717 query requests, the refId could be any char, so we can use int data to avoid the bug.

**Comment by kaydelaney** [comment] 2020-10-14 08:25
Duplicate of #4978

**Closed by kaydelaney** 2020-10-14 08:25 UTC
Labels: area/dashboard/import, priority/nice-to-have, type/bug
