### ISSUE TITLE
Rename Field causes filter issues

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#35597] opened 2021-06-13 06:36 UTC
Using Grafana 7.5.1

Let's say I have a graph with 2 items (ex. Servers). By default the graph shows both and I can click on each one individually (or use CTL + click to select a few) to filter the display.

When I renamed all of the items in the display using overrides, I can no longer filter by selecting an item, but rather I get an "all or nothing" situation, when I can show or hide all, but not do an individual select/filter. 

I tried in the same issue, to rename 6 out of 8 items. When clicking on the 6 which were renamed, the problem exists. But when I click on the 2 which we not renamed, everything works as expected where I get an individual filter.

**Comment by torkelo** [comment] 2021-06-13 16:04
duplicate of #31364 

Try using organized fields transform and rename fields/series that way as a temporary override

**Closed by torkelo** 2021-06-13 16:04 UTC
