### ISSUE TITLE
Azure Monitor: queries returns "Client.Timeout exceeded while awaiting headers"

### ISSUE THREAD

**Issue by LavederMark-Ylann** [grafana/grafana#80536] opened 2024-01-15 10:47 UTC
### What happened?

We have a TV showing a dashboard that contains 10 panels, for a total of 15 queries.
Sometimes, queries from Azure Monitor returns status code 504, Client.Timeout exceeded while awaiting headers.
During these occurrences, we are not able to use Grafana to monitor our applications and infrastructure for anywhere between 5 to 10 minutes.
The problem concerns every other dashboard that uses the Azure Monitor datasource.

We tried to increase the timeout settings to 60s, without any success.

It is possible to recreate the anomaly by clicking multiple time on refresh button of the dashboard

Grafana is running on an AppService on Azure, running the DockerHub container.

### What did you expect to happen?

Data should be available without any downtime

### Did this work before?

Worked when we started using Grafana, version 8.3.7. The problem is gradually increasing since then.

### How do we reproduce it?

1. Create a dashboard that contains multiple panels with the Azure Monitor datasource
2. Repeatedly click on the refresh button of the dashboard
3. Panels should load until getting error 504 Client.Timeout exceeded while awaiting headers

### Environment (with versions)?

Grafana: 10.2.2
OS: Windows / Linux
Browser: Opera, Chrome

### Grafana platform?

Docker

### Datasource(s)?

Azure Monitor

**Comment by tonypowa** [comment] 2024-02-09 13:10
hi  @LavederMark-Ylann 
thank you for providing details about the timeout issues

Can you provide a sample of the query or queries being run when the 504 error occurs? Please make sure to redact any sensitive information.

Are there any relevant logs from Grafana around the time the timeouts occur?

**Comment by LavederMark-Ylann** [comment] 2024-02-09 14:43
Hi @tonypowa and thank you for looking into this.

As requested, here are some additional information concerning this problem.

Query inspector when the oddity occur :

```json
{
  "request": {
    "url": "api/ds/query?ds_type=grafana-azure-monitor-datasource&requestId=Q426-A",
    "method": "POST",
    "data": {
      "queries": [
        {
          "datasource": {
            "type": "grafana-azure-monitor-datasource",
            "uid": "wETZgg2nz"
          },
          "appInsights": {
            "groupBy": "none",
            "metricName": "select",
            "rawQuery": false,
            "rawQueryString": "",
            "spliton": "",
            "timeGrainType": "auto",
            "xaxis": "timestamp",
            "yaxis": ""
          },
          "azureLogAnalytics": {
            "resultFormat": "table",
            "query": "AppRequests\r\n| where TimeGenerated > ago(10m)\r\n| distinct UserAuthenticatedId \r\n| count",
            "resources": [
              "/subscriptions/{sub_id}/resourceGroups/{resourceGroup_id}/providers/Microsoft.OperationalInsights/workspaces/{workspace}"
            ],
            "workspace": "{workspace_uuid}",
            "dashboardTime": false,
            "timeColumn": ""
          },
          "azureMonitor": {
            "dimensionFilter": "*",
            "metricDefinition": "select",
            "metricName": "select",
            "metricNamespace": "select",
            "timeGrain": "auto",
            "resources": [
              {
                "resourceGroup": "select",
                "resourceName": "select"
              }
            ]
          },
          "exemplar": true,
          "expr": "sum(sqlserver_server_properties_db_offline) by (sql_instance) != 0",
          "interval": "",
          "legendFormat": "",
          "queryType": "Azure Log Analytics",
          "refId": "A",
          "datasourceId": 14,
          "intervalMs": 120000,
          "maxDataPoints": 100
        }
      ],
      "from": "1707475671209",
      "to": "1707486471209"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "Post \"https://api.loganalytics.io/v1/subscriptions/{sub_uuid}/resourceGroups/{resourceGroup_id}/providers/Microsoft.OperationalInsights/workspaces/{workspace}/query\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
        "errorSource": "",
        "status": 504,
        "refId": "A"
      }
    }
  }
}
```

Some of the queries from the dashboard :

```
Perf
| where TimeGenerated > ago(10min) and Computer startswith $serverPattern and CounterName == "% Processor Time" and InstanceName == "_Total" and ObjectName == "Processor"
| order by TimeGenerated desc
| summarize arg_max(TimeGenerated, CounterValue) by Computer
| order by Computer asc
```

```
Perf
| where TimeGenerated > ago(10m) and Computer startswith $serverPattern and ObjectName == "Memory" and CounterName == "% Committed Bytes In Use"
| summarize arg_max(TimeGenerated, CounterValue) by Computer
| order by Computer asc, TimeGenerated desc
```

```
Heartbeat
| where TimeGenerated > ago(5d)
| summarize max(TimeGenerated) by Computer
| where max_TimeGenerated < ago(5min)
| extend downtime = datetime_diff("minute", now(), max_TimeGenerated)
| summarize count()
```

```
AppRequests
| where $__timeFilter()
| extend Computer = replace_regex(replace_regex(AppRoleInstance, @"\..*", ""), "$serverPattern", "")
| summarize ["Total requests"] = sum(ItemCount) by Computer, Time = bin(TimeGenerated, 10min)
| order by Time asc, Computer asc
```

```
AppAvailabilityResults
| where $__timeFilter()
| extend percentage = todouble(Success) * 100, Name = replace_regex(Name, @"^$serverPattern", "Web")
| summarize avg(percentage) by bin(TimeGenerated, 5m),  Name
| order by TimeGenerated asc, Name asc
```

Logs from Grafana (as the IPs are not forwarded, 169.254.130.1 is the internal IP of the AppService) :

```
2024-02-09T13:49:23.877498505Z logger=context userId=53 orgId=1 uname={TV} t=2024-02-09T13:49:23.857401524Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=169.254.130.1 time_ms=29633 duration=29.633556436s size=270 referer="https://{URL}/d/pNqmmgh7z/main?kiosk=&orgId=1&refresh=30s" handler=/api/ds/query
2024-02-09T13:49:23.899958032Z logger=context userId=53 orgId=1 uname={TV} t=2024-02-09T13:49:23.894745333Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=169.254.130.1 time_ms=29680 duration=29.680476543s size=270 referer="https://{URL}/d/pNqmmgh7z/main?kiosk=&orgId=1&refresh=30s" handler=/api/ds/query
2024-02-09T13:49:23.923599082Z logger=context userId=53 orgId=1 uname={TV} t=2024-02-09T13:49:23.920051314Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=169.254.130.1 time_ms=29703 duration=29.703418175s size=270 referer="https://{URL}/d/pNqmmgh7z/main?kiosk=&orgId=1&refresh=30s" handler=/api/ds/query
2024-02-09T13:49:23.926759742Z logger=context userId=53 orgId=1 uname={TV} t=2024-02-09T13:49:23.926429435Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=169.254.130.1 time_ms=29706 duration=29.706172421s size=270 referer="https://{URL}/d/pNqmmgh7z/main?kiosk=&orgId=1&refresh=30s" handler=/api/ds/query
2024-02-09T13:49:23.932288747Z logger=context userId=53 orgId=1 uname={TV} t=2024-02-09T13:49:23.932020042Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=169.254.130.1 time_ms=29709 duration=29.709222075s size=270 referer="https://{URL}/d/pNqmmgh7z/main?kiosk=&orgId=1&refresh=30s" handler=/api/ds/query
2024-02-09T13:49:23.939821590Z logger=context userId=53 orgId=1 uname={TV} t=2024-02-09T13:49:23.939739888Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=169.254.130.1 time_ms=452 duration=452.602201ms size=545 referer="https://{URL}/d/pNqmmgh7z/main?kiosk=&orgId=1&refresh=30s" handler=/api/ds/query

2024-02-09T13:50:21.069617158Z logger=context userId=0 orgId=0 uname= t=2024-02-09T13:50:21.069410154Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=169.254.130.1 time_ms=0 duration=81.602Âµs size=29 referer= handler=/

2024-02-09T13:52:48.486772548Z logger=context userId=38 orgId=1 uname={someUser} t=2024-02-09T13:52:48.485968733Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=169.254.130.1 time_ms=2 duration=2.153538ms size=0 referer= handler=/api/live/ws

2024-02-09T13:53:01.488948446Z logger=context userId=64 orgId=1 uname={anotherUser} t=2024-02-09T13:53:01.487934431Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=169.254.130.1 time_ms=2 duration=2.198633ms size=0 referer= handler=/api/live/ws

2024-02-09T13:53:08.273441288Z logger=grafana.update.checker t=2024-02-09T13:53:08.273255785Z level=info msg="Update check succeeded" duration=35.127814ms
2024-02-09T13:53:08.277483259Z logger=cleanup t=2024-02-09T13:53:08.277384857Z level=info msg="Completed cleanup jobs" duration=57.513105ms
2024-02-09T13:53:08.319802398Z logger=plugins.update.checker t=2024-02-09T13:53:08.319688596Z level=info msg="Update check succeeded" duration=52.68322ms

2024-02-09T13:54:07.472729260Z logger=infra.usagestats t=2024-02-09T13:54:07.472208651Z level=info msg="Usage stats are ready to report"

2024-02-09T13:55:21.813307835Z logger=context userId=0 orgId=0 uname= t=2024-02-09T13:55:21.81303533Z level=info msg="Request Completed" method=GET path=/ status=302 remote_addr=169.254.130.1 time_ms=0 duration=77.001Âµs size=29 referer= handler=/

2024-02-09T13:55:50.820189982Z logger=context userId=38 orgId=1 uname=someUser t=2024-02-09T13:55:50.81875336Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=169.254.130.1 time_ms=2 duration=2.273136ms size=0 referer= handler=/api/live/ws
```

Thank you very much once again.

**Comment by tonypowa** [comment] 2024-02-12 08:17
Many thanks for the detailed report  @LavederMark-Ylann 
The issue is already added to the team's board. An engineer will reach out to you as soon as business allows

**Comment by aangelisc** [comment] 2024-03-04 18:44
Hi @LavederMark-Ylann,

This issue seems to be a throttling issue on the Log Analytics side rather than in Grafana. We have seen this before. 

Are all of your queries executed using the same data source? 
Is the data source configured with App Registration credentials or a Managed Identity?

**Comment by LavederMark-Ylann** [comment] 2024-03-04 19:05
Hello @aangelisc 

You are correct, the queries are executed using the same data source.
We also use App Registration creds. Would migrating to Managed Identity fix the issue ?

**Comment by aangelisc** [comment] 2024-03-19 19:12
Hi @LavederMark-Ylann,

Apologies for the delayed response. Unfortunately making use of Managed Identity wouldn't fix this issue as it would have similar limits to the App Registration credentials. For now the best workaround is to create multiple data sources and split the panels in the dashboard across the data sources to reduce the impact of the throttling on the Azure API>

**Comment by aangelisc** [comment] 2024-03-28 16:37
Closing this issue as it's an Azure limitation rather than a Grafana one. Please re-open if you feel this is not the case or have anything else to add!

**Closed by aangelisc** 2024-03-28 16:37 UTC
Labels: datasource/Azure, triage/needs-confirmation
