### ISSUE TITLE
Stat Panel - Unit: "FROM NOW"- Threshold uses EPOCH-Timestamp instead of duration

### ISSUE THREAD

**Issue by ballardr** [grafana/grafana#39345] opened 2021-09-17 11:45 UTC
![Threshold using epoch](https://user-images.githubusercontent.com/73680473/133775516-ff156934-2440-4072-8011-88169c9236fa.PNG)

**What happened**:
I wanted to display the time since the last event of something, adding a threshold if the duration is over 1d for orange, 3d for red.

I'm mostly copying this from https://github.com/grafana/grafana/issues/24618, but updated for Stat Panel.

**What you expected to happen**:
I could add a time in seconds/ms/ns, at which it should change the color.
I expected the threshhold would be a duration from now, not a fixed date on the unit "FROM NOW".
I expected the units "FROM NOW" would use different units in threshholds then the other two date formats in "Date & Time".

**How to reproduce it (as minimally and precisely as possible)**:
Create a stat panel, query anything which yields a result.
Select unit "Date & Time" -> "From Now"
For testing I recommend one of the other two timestamp types within the same category. (same result)

By selecting a threshold you will get:
If the Base is set to Green and a second orange threshold is set to an epoch just below the last data point, the data will be yellow. That is the threshold may be something like 1631878817. This threshold would thus need to be dynamic to be useful.

Example given at top.

**Anything else we need to know?**:
 - This relates to https://github.com/grafana/grafana/issues/8679
 - This is the issue for the previous version of the panel https://github.com/grafana/grafana/issues/24618
 - Here is a community post about the issue https://community.grafana.com/t/coloration-based-on-date-with-thresholds-overrides/37634
      - I couldn't work out how to implement this. I assumed it used an "expression" after the query, but I could not get to work
- This is another forum post about the issue, pointing to the above https://community.grafana.com/t/coloring-time-from-now-in-single-stat-panel/20025

**Environment**:
- Grafana version: 8.1.2 (103f8fa094)
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows 10 and Chrome
- Grafana plugins: html plugin
- Others:

**Comment by hugohaggmark** [comment] 2021-09-21 11:28
For this to be a reasonable feature, it would have to be something like the feature already proposed in #8679. So I'm going to mark this as a duplicate.

**Comment by hugohaggmark** [comment] 2021-09-21 11:29
Duplicate of #8679

**Closed by hugohaggmark** 2021-09-21 11:29 UTC
Labels: type/duplicate, type/feature-request, area/panel/stat

**Comment by someone701515** [comment] 2025-01-06 08:02
Anyone got a solution for this?
It is very often I need to show how long time ago some vent happened, and then I would like to use threshold colors, e.g. so it is red if more than 3 days ago.
