### ISSUE TITLE
Metrics with same TSDB source cannot have different Alias values

### ISSUE THREAD

**Issue by sferrett** [grafana/grafana#1915] opened 2015-04-30 00:47 UTC
I have a couple of graph panels where I have a tsdb metric that I want to chart both the average and max values for it on the same graph.  Generally I do this by making two metrics with the same metric source but different aggregator.   Since they have the same metric name, I use an alias to label one "Average" and the other "Maximum"

I am looking at Grafana 2.0.2 and I am finding that if I have multiple metrics on a graph that have the same tsdb metric name, the Alias value applied to the first one is applied to all of them and any other alias values for them are ignored.

**Comment by torkelo** [comment] 2015-04-30 04:57
This can be fixed with OpenTSDB 2.2 (not released yet). OpenTSDB has recently added a required feature that makes it possible for grafana to correlate query with returned series. 
https://github.com/OpenTSDB/opentsdb/issues/438

**Comment by torkelo** [comment] 2015-04-30 04:58
duplicate of #1876

**Comment by torkelo** [comment] 2015-04-30 04:58
https://github.com/grafana/grafana/issues/1876

**Closed** 2015-04-30 05:04 UTC
Labels: duplicate
