### ISSUE TITLE
Text falling behind (i) in url field in Table panel 

### ISSUE THREAD

**Issue by JosephFY** [grafana/grafana#13697] opened 2018-10-17 02:30 UTC
I know it's a small bug but I think it worth fixing

### What Grafana version are you using?
5.2.3
### What datasource are you using?
graphite
### What OS are you running grafana on?
redhat linux
### What did you do?
placing a URL in the table panel > Column Style > Link > url
### What was the expected result?
The information circle (i) icon should not overlap with the url text
### What happened instead?
The information circle (i) icon is overlapping with the last 1-2 characters. Screenshot attached
### If related to metric query / data viz:
N/A
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
N/A
 
Using Chrome Version 69.0.3497.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/28739923/47058391-7b5a2f00-d18a-11e8-8337-8f4e5ec410fe.png)

**Comment by marefr** [comment] 2018-10-17 07:44
Duplicate of #12945

**Comment by marefr** [comment] 2018-10-17 07:44
Fix included in v5.3.0 and newer versions.

**Closed by marefr** 2018-10-17 07:44 UTC
