### ISSUE TITLE
Undocumented dashboards/import API Call

### ISSUE THREAD

**Issue by safaci2000** [grafana/grafana#44383] opened 2022-01-24 14:48 UTC
I'm not sure if this qualifies as a bug or feature request but...

The API used by the frontend to import a dashboard is /api/dashboards/import which seems to be the only one that supports importing library panels.  The documented API for doing so /api/dashboard/db/ does not support library panels. 

It would be nice if we could get either the dashboard/db to support the library panels OR document /import as a valid endpoint to use.

Either approach is fine as long as it's documented accordingly.

**Comment by papagian** [comment] 2022-01-26 09:30
Hi, regarding the missing documentation we plan to change the way we document the API. Therefore it's hard to prioritise it unless we get some help.
In case somebody would like to pick it up, I enclose an example request.
<details>
<summary>example request for importing dashboard with library panels</summary>

```
curl 'http://localhost:3000/api/dashboards/import' \
  -H 'content-type: application/json' \
  -H 'Cookie: grafana_session=<cookie>' \
  --data-raw '{
	"dashboard": {
		"annotations": {
			"list": [
				{
					"builtIn": 1,
					"datasource": "-- Grafana --",
					"enable": true,
					"hide": true,
					"iconColor": "rgba(0, 211, 255, 1)",
					"name": "Annotations & Alerts",
					"target": {
						"limit": 100,
						"matchAny": false,
						"tags": [],
						"type": "dashboard"
					},
					"type": "dashboard"
				}
			]
		},
		"editable": true,
		"fiscalYearStartMonth": 0,
		"graphTooltip": 0,
		"id": null,
		"links": [],
		"liveNow": false,
		"panels": [
			{
				"aliasColors": {},
				"bars": false,
				"dashLength": 10,
				"dashes": false,
				"datasource": {},
				"description": "",
				"fill": 1,
				"fillGradient": 0,
				"gridPos": {
					"h": 9,
					"w": 12,
					"x": 0,
					"y": 0
				},
				"hiddenSeries": false,
				"id": 2,
				"legend": {
					"avg": false,
					"current": false,
					"max": false,
					"min": false,
					"show": true,
					"total": false,
					"values": false
				},
				"libraryPanel": {
					"description": "",
					"meta": {
						"connectedDashboards": 1,
						"created": "2021-12-21T10:59:45+02:00",
						"createdBy": {
							"avatarUrl": "/avatar/21232f297a57a5a743894a0e4a801fc3",
							"id": 1,
							"name": "admin"
						},
						"folderName": "General",
						"folderUid": "",
						"updated": "2022-01-26T11:08:59+02:00",
						"updatedBy": {
							"avatarUrl": "/avatar/21232f297a57a5a743894a0e4a801fc3",
							"id": 1,
							"name": "admin"
						}
					},
					"name": "#28301",
					"type": "graph",
					"uid": "Dpjyu0o7k",
					"version": 2
				},
				"lines": true,
				"linewidth": 1,
				"nullPointMode": "null",
				"options": {
					"alertThreshold": true
				},
				"percentage": false,
				"pluginVersion": "8.4.0-pre",
				"pointradius": 2,
				"points": false,
				"renderer": "flot",
				"seriesOverrides": [],
				"spaceLength": 10,
				"stack": false,
				"steppedLine": false,
				"targets": [
					{
						"alias": "",
						"refId": "A",
						"scenarioId": "csv_metric_values",
						"stringInput": "1,20,90,30,5,0"
					}
				],
				"thresholds": [],
				"timeRegions": [],
				"title": "#28301",
				"tooltip": {
					"shared": true,
					"sort": 0,
					"value_type": "individual"
				},
				"type": "graph",
				"xaxis": {
					"mode": "time",
					"show": true,
					"values": []
				},
				"yaxes": [
					{
						"format": "short",
						"logBase": 1,
						"show": true
					},
					{
						"format": "short",
						"logBase": 1,
						"show": true
					}
				],
				"yaxis": {
					"align": false
				}
			}
		],
		"schemaVersion": 34,
		"style": "dark",
		"tags": [],
		"templating": {
			"list": []
		},
		"time": {
			"from": "now-6h",
			"to": "now"
		},
		"timepicker": {},
		"timezone": "",
		"title": "#44383 clone",
		"uid": "7-u-btxnb",
		"version": 1,
		"weekStart": ""
	},
	"overwrite": true,
	"inputs": [],
	"folderId": 0
}'
```
</details>

**Comment by safaci2000** [comment] 2022-01-26 14:07
If Grafana is re-working how the imports are being done that's fine.  I understand that this isn't a big priority though I did want to point out the discrepancy. 

I am trying to understand the recommended REST API to use though.  Is it fair to say that /api/dashboards/import is likely the recommended end approach to use to import dashboards over /api/dashboard/db/ ?

I'd like to at least confirm I'm going down the right path as the documentation on said endpoint is missing.

**Comment by papagian** [comment] 2022-02-07 10:02
> If Grafana is re-working how the imports are being done that's fine. I understand that this isn't a big priority though I did want to point out the discrepancy.
> 

sorry, I think my comment got misinterpreted. I was replying to `OR document /import as a valid endpoint to use` part that we work on formally specifying the HTTP API therefore updating [these docs](https://grafana.com/docs/grafana/latest/http_api/dashboard/) is not our priority.
I'm not aware of any planned changes to the imports.

Also what issues do you have with the `/api/dashboard/db` endpoint with the library panels? the following request seems to work for me:

<details>
<summary>Post dashboard with library panels example request
</summary>

```
curl http://localhost:3000/api/dashboards/db/ \
-H 'Cookie: grafana_session=c15b304f14823291f1b54b8a7ab48822' \
-d '
{
	"dashboard": {
		"annotations": {
			"list": [
				{
					"builtIn": 1,
					"datasource": "-- Grafana --",
					"enable": true,
					"hide": true,
					"iconColor": "rgba(0, 211, 255, 1)",
					"name": "Annotations & Alerts",
					"target": {
						"limit": 100,
						"matchAny": false,
						"tags": [],
						"type": "dashboard"
					},
					"type": "dashboard"
				}
			]
		},
		"editable": true,
		"fiscalYearStartMonth": 0,
		"graphTooltip": 0,
		"links": [],
		"liveNow": false,
		"panels": [
			{
				"aliasColors": {},
				"bars": false,
				"dashLength": 10,
				"dashes": false,
				"datasource": {},
				"description": "",
				"fill": 1,
				"fillGradient": 0,
				"gridPos": {
					"h": 9,
					"w": 12,
					"x": 0,
					"y": 0
				},
				"hiddenSeries": false,
				"id": 2,
				"legend": {
					"avg": false,
					"current": false,
					"max": false,
					"min": false,
					"show": true,
					"total": false,
					"values": false
				},
				"libraryPanel": {
					"meta": {
						"connectedDashboards": 2,
						"created": "2021-12-21T10:59:45+02:00",
						"createdBy": {
							"avatarUrl": "/avatar/21232f297a57a5a743894a0e4a801fc3",
							"id": 1,
							"name": "admin"
						},
						"folderName": "General",
						"folderUid": "",
						"updated": "2022-01-26T11:08:59+02:00",
						"updatedBy": {
							"avatarUrl": "/avatar/21232f297a57a5a743894a0e4a801fc3",
							"id": 1,
							"name": "admin"
						}
					},
					"name": "#28301",
					"uid": "Dpjyu0o7k",
					"version": 2
				},
				"lines": true,
				"linewidth": 1,
				"nullPointMode": "null",
				"options": {
					"alertThreshold": true
				},
				"percentage": false,
				"pluginVersion": "8.5.0-pre",
				"pointradius": 2,
				"points": false,
				"renderer": "flot",
				"seriesOverrides": [],
				"spaceLength": 10,
				"stack": false,
				"steppedLine": false,
				"targets": [
					{
						"alias": "",
						"refId": "A",
						"scenarioId": "csv_metric_values",
						"stringInput": "1,20,90,30,5,0"
					}
				],
				"thresholds": [],
				"timeRegions": [],
				"title": "#28301",
				"tooltip": {
					"shared": true,
					"sort": 0,
					"value_type": "individual"
				},
				"type": "graph",
				"xaxis": {
					"mode": "time",
					"show": true,
					"values": []
				},
				"yaxes": [
					{
						"format": "short",
						"logBase": 1,
						"show": true
					},
					{
						"format": "short",
						"logBase": 1,
						"show": true
					}
				],
				"yaxis": {
					"align": false
				}
			}
		],
		"schemaVersion": 35,
		"style": "dark",
		"tags": [],
		"templating": {
			"list": []
		},
		"time": {
			"from": "now-6h",
			"to": "now"
		},
		"timepicker": {},
		"timezone": "",
		"title": "#44383 post dashboard",
		"version": 0,
		"weekStart": "",
		"id": null,
		"uid": "",
		"hideControls": false
	},
	"message": "",
	"overwrite": false,
	"folderId": 0
}'
{"id":1575,"slug":"44383-post-dashboard","status":"success","uid":"-YGI1ca7z","url":"/d/-YGI1ca7z/44383-post-dashboard","version":1}
```

</details>

> I am trying to understand the recommended REST API to use though. Is it fair to say that /api/dashboards/import is likely the recommended end approach to use to import dashboards over /api/dashboard/db/ ?
> 
> I'd like to at least confirm I'm going down the right path as the documentation on said endpoint is missing.

I don't think that there is a recommended endpoint to use. The `import` one was designed to work together with the [export](https://grafana.com/docs/grafana/latest/dashboards/export-import/#exporting-a-dashboard) one and supports also importing dashboards from other grafana instances by permitting to the user to select among the compatible datasources existing in the destination instance. Other than that the two endpoints should not differ a lot so it's up to the caller to pick the one that best suit to their needs.

**Comment by safaci2000** [comment] 2022-02-07 14:42
@papagian I believe this ticket has more context: https://github.com/grafana/grafana/issues/44003.  It's my understanding that the dashboard/db does not support importing third party panels.  Last comment was:

```
We don't support importing using the dashboard post api so we'll close this issue and PR. We can always revisit this if more feedback is received from the community. Thank you 🙏
```

This was initialed from a user opening up a ticket in the dashboard management tool I wrote for grafana.  My understanding from the user feedback is that:

1.  UI supports importing 3rd party panels.
2. The /import endpoint does as well.
3. the /dashboard/db does not.

My concern was using the /import over /dashboard/db was related to the fact that it seems like an undocumented API.

My request / questions:

A. Can you confirm that the 3 assertions above are correct? 
B. If yes, I was looking for guidance for the how to support 3rd party panels? aka. suggestion to use /import, or wait for release X.X that will support it, etc.

**Comment by papagian** [comment] 2022-02-11 15:12
If you want to share dashboards among different grafana instances then the endpoint to use is the `/import` one. This endpoint tries [to create all the library panels that do not already exist in the new instance](https://github.com/grafana/grafana/pull/39214/files#diff-2800bdf355459d293ccc0508973203bb42adefff53bbbca8d87190fc4807a9e9R285). If a library panel with the same UID already exists in the new instance then it will ignore it. This was implemented as part of [this](https://github.com/grafana/grafana/pull/39214) work. For more details please check the implementation there.

**Comment by efekete** [comment] 2022-02-12 17:23
Exactly, and that is how we came to this issue and request to document that `/import` API.

**Comment by chri2547** [comment] 2023-10-11 16:07
Closing this issue because it's over a year old, in an unresourced area, and not likely to be worked on in the next year.

**Closed by chri2547** 2023-10-11 16:07 UTC
Labels: type/docs, help wanted, area/backend/api, migrate/status-icebox
