### ISSUE TITLE
Add the ability to set a timeout for the Render Plugin request. Unified alerting.

### ISSUE THREAD

**Issue by remackad** [grafana/grafana#59527] opened 2022-11-30 08:22 UTC
**What happened**:

Our alerts are getting sent without screenshots because rendering takes to long.

Log from Grafana
logger=rendering renderer=http t=2022-11-30T14:58:10.118602652+07:00 level=error msg="Failed to send request to remote rendering service" error="Get \"http://grafana_render:8081/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=ITdJiq7M7czZ3y15rFUib32T4KBTOauV&timeout=10&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F0K3ZBAv4z%2Flink-down-alerts%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000\": context deadline exceeded"

Log from Render Plugin
{"level":"error","message":"Request failed","stack":"Error: Request aborted\n    at onaborted (/usr/src/app/node_modules/express/lib/response.js:1052:15)\n    at Immediate._onImmediate (/usr/src/app/node_modules/express/lib/response.js:1094:9)\n    at processImmediate (node:internal/timers:466:21)","url":"/render?deviceScaleFactor=1.000000&domain=grafana&encoding=&height=500&renderKey=HSF5bCeuXGLe7Nm7fso0XBvLuslj0K5H&timeout=10&timezone=&url=http%3A%2F%2Fgrafana%3A3000%2Fd-solo%2F0K3ZBAv4z%2Flink-down-alerts%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000"}

**What you expected to happen**:

A way to configure the rendering timeout. Currently it seems to be hardcoded to 10 seconds:
https://github.com/grafana/grafana/blob/2b5d12310a4eb0f0230f64ed98b1faa138d99b7e/pkg/services/ngalert/image/service.go#L21

We are working on getting the results faster, but I wonder if it were possible to make that configurable.

**How to reproduce it (as minimally and precisely as possible)**:

Create an alert that links a dashboard & panel so the alert message includes an image. The panel in question needs to have a long loading time.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.2.0 (latest docker image from a day ago)
- Data source type & version: MySQL
- OS Grafana is installed on: Centos7 with docker
- User OS & Browser: Fedora 36 with Firefox 
- Grafana plugins:
- Others:

_Originally posted by @apollo13 in https://github.com/grafana/grafana/discussions/53755_

**Comment by apollo13** [comment] 2022-11-30 08:28
FWIW we are still having this issue and I do not understand why the grafana-image-renderer takes that long. What I can imagine is that since it uses a private browser window and has to redownload all assets it takes that long to build up the page.

**Comment by mellieA** [comment] 2022-11-30 19:02
Duplicate of https://github.com/grafana/grafana/issues/58687 feel free to contribute to the conversation there 😄

**Comment by apollo13** [comment] 2022-11-30 19:08
I honestly do not think this is a duplicate. There is a difference between the built-in screenshot timeout vs the whole notification timeout as far as I can tell.

**Comment by vogusyan** [comment] 2022-12-19 10:08
Hello,
Looks like problem [#58687](https://github.com/grafana/grafana/issues/58687) is not about this specific issue. It's about 30 seconds notification timeout, but this topic is about 10 seconds render timeout. Also, issue [#58687](https://github.com/grafana/grafana/issues/58687) with notification timeout concern seems to be closed without any solution. I think it also will be a problem after solving this 10 seconds timeout problem, because my renderer is a bit slow and can render images for about 40-60 seconds.
Maybe we can resurrect this issue?

**Comment by apollo13** [comment] 2022-12-19 12:55
@mellieA Any chance to look into the evidence provided here about this not being a duplicate?

**Comment by mellieA** [comment] 2022-12-20 00:58
It looks like comment from @grobinson-grafana at https://github.com/grafana/grafana/issues/58687#issuecomment-1319803804 says that this setting isn't currently configurable, but then the conversation went in another direction (that user is capturing their own independent screenshots outside of the built-in feature). 

I can re-open this as a feature request

**Comment by grobinson-grafana** [comment] 2022-12-20 11:20
Thank you for opening this issue! I think this is reasonable, and something we had planned to do, but just hadn't prioritized. I think we should support a configurable timeout up to some hardcoded maximum, perhaps 30 seconds.

A concern I have about increasing the timeout is because screenshots are taken synchronously, long timeouts can cause alert rules to miss successive evaluations. We chose a timeout of 10 seconds to reduce the chance of this happening as the minimum tick interval for alert rule evaluation is 10 seconds.

Perhaps we should think about making screenshots asynchronous, and add configurable timeouts at the same time.

**Closed** 2023-01-05 16:07 UTC
Labels: type/feature-request, area/alerting/screenshots
