### ISSUE TITLE
Support send WeCom alert message

### ISSUE THREAD

**Issue by okhowang** [grafana/grafana#21211] opened 2019-12-20 09:27 UTC
**What would you like to be added**:
[WeChat Work](https://work.weixin.qq.com/) is a popular IM in china for working.
We can add an message webhook for it.
**Why is this needed**:
make more friendly to WeChat Work user

**Comment by marefr** [comment] 2019-12-20 10:09
Duplicate of #12333

**Comment by zengxs** [comment] 2020-01-08 06:01
I think this is not duplicate, **Wechat Work** and **Wechat** are two different apps.

**Comment by okhowang** [comment] 2020-09-06 06:36
WeChat Work has been renamed to WeCom

**Comment by davywangsz** [comment] 2020-12-04 09:30
Yeah， now wechat-work renamed to WeCom, its very very polular in China.
i hope grafana could support it.

**Closed** 2021-12-15 16:42 UTC
Labels: type/feature-request, area/alerting/notifications
