### ISSUE TITLE
Explore: Mixed, different datasources, shows one result twice, and one result zero times

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#81461] opened 2024-01-29 10:45 UTC
See **[this Explore URL](https://play.grafana.org/explore?schemaVersion=1&panes=%7B%227hu%22:%7B%22datasource%22:%22--%20Mixed%20--%22,%22queries%22:%5B%7B%22scenarioId%22:%22csv_metric_values%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22grafana-testdata-datasource%22,%22uid%22:%229cY0WtPMz%22%7D,%22stringInput%22:%221,20,90,30,5,0%22,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22expr%22:%22count%28container_fs_reads_total%7B%7D%29%22,%22range%22:false,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22grafanacloud-prom%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22format%22:%22table%22,%22exemplar%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)**

![image](https://github.com/grafana/grafana/assets/2903904/15d368b7-195f-443c-b4a9-e511b7b24e99)

This has two problems:
1. The Tables rendered are duplicates - both show the result from Query B
2. The result from query A is not shown anywhere.

I've persisted the example to **[this dashboard](https://play.grafana.org/d/cd048585-6c2b-49e8-9a69-4dae74d668d1/ad77d391-b306-5f56-818d-ccf38aa92950?orgId=1)** on play.grafana.com 
The issues aren't visible on that persisted dashboard, but can be found by **Explore**-ing that panel

**Comment by gelicia** [comment] 2024-01-29 19:22
I believe this is a duplicate of https://github.com/grafana/grafana/issues/75036 which is a known bug that may or may not be something they will work on. I will ask them to confirm and will open this ticket if they are different.

**Closed by gelicia** 2024-01-29 19:22 UTC
Labels: area/explore, internal
