### ISSUE TITLE
Bar chart does not plot when single group of values is returned (grafana/stable 8.4.1 amd64)

### ISSUE THREAD

**Issue by joaolrc** [grafana/grafana#45826] opened 2022-02-24 10:39 UTC
Hello

I recently upgraded from grafana 8.3.3 from 8.4.1 and found an issue with bar charts.

## Issue

When a single group of values is returned, on version 8.3.3 the chart gets plotted. On 8.4.1 it does not.
Considering this table view (same for both versions as query is exactly the same):
![image](https://user-images.githubusercontent.com/38216435/155503462-09b104a2-0dca-4296-9996-59f1a3c4c1fc.png)

This is the result on V8.3.3:
![image](https://user-images.githubusercontent.com/38216435/155504552-ddcd4b1a-78e9-49d4-af9f-d90e95b27272.png)

On the same machine, i upgrade to V8.4.1 and the result is the following:
![image](https://user-images.githubusercontent.com/38216435/155504862-e9f8f801-3b4c-4511-80aa-7cdcf8e6202f.png)

If more than one group of values is returned, the bars appear on both versions (table view below):
![image](https://user-images.githubusercontent.com/38216435/155506613-3d9149c2-a2de-46a5-a068-99e8076c5653.png)

## Server 

I am using ubuntu server 20.04 and grafana installed as apt package with little or no customizations that differ from default behaviour.
I am using MySQL as data source. Output of mysql --version:
```
mysql  Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
```
All services are runing in the same VM under Windows Server host using Hyper-V as virtualization software.

## Client
I tested on PoP-OS and windows 11 clients both on Firefox and google chrome.

## Panel JSON

For version 8.3.3
```json
{
  "id": 19,
  "gridPos": {
    "h": 11,
    "w": 24,
    "x": 0,
    "y": 11
  },
  "type": "barchart",
  "title": "Units Tested per model",
  "transformations": [
    {
      "id": "seriesToColumns",
      "options": {
        "byField": "modelo"
      }
    }
  ],
  "pluginVersion": "8.3.3",
  "description": "Total, OK and NOK units per PSU model",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 4,
        "fillOpacity": 68,
        "gradientMode": "none",
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisSoftMin": 0,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        }
      },
      "color": {
        "mode": "thresholds"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "mappings": [],
      "unit": "none"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byRegexp",
          "options": "NOK"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-red",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byRegexp",
          "options": "OK"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "semi-dark-green",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Total"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "blue",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "options": {
    "orientation": "auto",
    "xTickLabelRotation": 0,
    "showValue": "never",
    "stacking": "none",
    "groupWidth": 0.7,
    "barWidth": 0.97,
    "tooltip": {
      "mode": "single"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "mysql",
        "uid": "ROrDCP6Mz"
      },
      "format": "table",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT  modelo, COUNT(global_result) as Total FROM GLOBAL_TABLE \nWHERE \nusername in ($worker_var)\nAND\nmodelo in ($model_var) AND $__timeFilter(username_date_hour)  \nAND (global_result>=2 OR global_result<0)\nAND (error_code in ($ecode_var) or (ISNULL(error_code) AND global_result>=2 ))\nGROUP BY modelo\n",
      "refId": "A",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "HUB3V3_global",
      "timeColumn": "username_date_hour",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    },
    {
      "datasource": {
        "type": "mysql",
        "uid": "ROrDCP6Mz"
      },
      "format": "table",
      "group": [],
      "hide": false,
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": " \nSELECT  modelo, COUNT(global_result) as OK FROM GLOBAL_TABLE WHERE\nusername in ($worker_var)\nAND\nmodelo in ($model_var)\nAND $__timeFilter(username_date_hour) AND global_result>=2 GROUP BY modelo \n",
      "refId": "C",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "HUB3V3_global",
      "timeColumn": "username_date_hour",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    },
    {
      "datasource": {
        "type": "mysql",
        "uid": "ROrDCP6Mz"
      },
      "format": "table",
      "group": [],
      "hide": false,
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": " \nSELECT  modelo, COUNT(global_result) as NOK FROM GLOBAL_TABLE WHERE \nusername in ($worker_var)\nAND\nmodelo in ($model_var) \nAND error_code in ($ecode_var)\nAND $__timeFilter(username_date_hour) AND global_result<0 GROUP BY modelo \n",
      "refId": "B",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "HUB3V3_global",
      "timeColumn": "username_date_hour",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    }
  ],
  "datasource": null
}
```

For version 8.4.1
```json
{
  "id": 19,
  "gridPos": {
    "h": 11,
    "w": 24,
    "x": 0,
    "y": 11
  },
  "type": "barchart",
  "title": "Units Tested per model",
  "transformations": [
    {
      "id": "seriesToColumns",
      "options": {
        "byField": "modelo"
      }
    }
  ],
  "pluginVersion": "8.3.3",
  "description": "Total, OK and NOK units per PSU model",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 4,
        "fillOpacity": 68,
        "gradientMode": "none",
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisSoftMin": 0,
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        }
      },
      "color": {
        "mode": "thresholds"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "unit": "none"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byRegexp",
          "options": "NOK"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-red",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byRegexp",
          "options": "OK"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "semi-dark-green",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Total"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "blue",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "options": {
    "orientation": "auto",
    "xTickLabelRotation": 0,
    "xTickLabelSpacing": 0,
    "showValue": "never",
    "stacking": "none",
    "groupWidth": 0.7,
    "barWidth": 0.97,
    "barRadius": 0,
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "mysql",
        "uid": "ROrDCP6Mz"
      },
      "format": "table",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT  modelo, COUNT(global_result) as Total FROM GLOBAL_TABLE \nWHERE \nusername in ($worker_var)\nAND\nmodelo in ($model_var) AND $__timeFilter(username_date_hour)  \nAND (global_result>=2 OR global_result<0)\nAND (error_code in ($ecode_var) or (ISNULL(error_code) AND global_result>=2 ))\nGROUP BY modelo\n",
      "refId": "A",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "HUB3V3_global",
      "timeColumn": "username_date_hour",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    },
    {
      "datasource": {
        "type": "mysql",
        "uid": "ROrDCP6Mz"
      },
      "format": "table",
      "group": [],
      "hide": false,
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": " \nSELECT  modelo, COUNT(global_result) as OK FROM GLOBAL_TABLE WHERE\nusername in ($worker_var)\nAND\nmodelo in ($model_var)\nAND $__timeFilter(username_date_hour) AND global_result>=2 GROUP BY modelo \n",
      "refId": "C",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "HUB3V3_global",
      "timeColumn": "username_date_hour",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    },
    {
      "datasource": {
        "type": "mysql",
        "uid": "ROrDCP6Mz"
      },
      "format": "table",
      "group": [],
      "hide": false,
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": " \nSELECT  modelo, COUNT(global_result) as NOK FROM GLOBAL_TABLE WHERE \nusername in ($worker_var)\nAND\nmodelo in ($model_var) \nAND error_code in ($ecode_var)\nAND $__timeFilter(username_date_hour) AND global_result<0 GROUP BY modelo \n",
      "refId": "B",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "HUB3V3_global",
      "timeColumn": "username_date_hour",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    }
  ],
  "datasource": null
}
```

Thanks in advance!

**Comment by leeoniya** [comment] 2022-02-24 12:54
duplicate of https://github.com/grafana/grafana/issues/44484

**Closed by leeoniya** 2022-02-24 12:54 UTC
