### ISSUE TITLE
[Feat] Option to hide datasource credentials from organization admins

### ISSUE THREAD

**Issue by Photon89** [grafana/grafana#13000] opened 2018-08-22 13:36 UTC
Please consider the following user case:

I (Grafana server admin, in short, admin) would like to set up Grafana with Elasticsearch as datasource and give access to it to several organizations org1 and org2.

Elasticsearch has indices specific to those organizations, org1_index1, org1_index2, ... and org2_index1, org2_index2, ...

Each organization should only have access to its own indices, so I create datasources datasource1 and datasource2 in Grafana with the index names org1* and org2* respectively. 

Now, datasource1 is created by admin in org1 and datasource2 in org2, so each organization admin admin_org1 and admin_org2 can use only the datasource of his organization.

However, admin_org1 and admin_org2 should not be able to access Elasticsearch's database beyond their respective datasource. Therefore they should not be able to read out the Elasticsearch credentials.

Currently, however, it is possible for admin_org1 and admin_org2 to read out these credentials using the datasource API. This gives them the ability to access the whole data stored in Elasticsearch.

Just to be clear, we do not want to have the user management on the Elasticsearch side.

It would therefore be great to have an option when configuring a data source to hide the credentials to all users without server admin privileges or even to all users at all.

**Comment by marefr** [comment] 2018-08-22 16:47
Most other datasource options are encrypted (certs & client secrets) but basic auth fields was added in the beginning when we did not have a good solution for encrypting data source settings, see #10827.

Duplicate of #2132

**Closed by marefr** 2018-08-22 16:47 UTC

**Comment by Photon89** [comment] 2018-08-27 08:34
Thanks for the reply! I realize, my scenario won't work not just because the credentials are visible, but also because the organization admins can edit the index name and, for example, put a * in this field thus gaining access to the complete ES database...

**Comment by marefr** [comment] 2018-08-27 09:01
Just out of curiosity - How do you solve access to certain indices in Kibana today?

**Comment by Photon89** [comment] 2018-08-27 09:56
I am new to the whole ES stuff so I can only write up what my research resulted in so far: The "official" way is to buy X-Pack which is quite expensive. A free option is SearchGuard (its Community edition, to be more precise), which, however, does not support multitenancy. If it is combined with https://github.com/wtakase/kibana-own-home this should also work though.

Since I need to research possibilities to run the whole thing on a managed AWS which does not allow installation of plugins like kibana-own-home, I am now reading into https://github.com/starrlingo/aws-mt-es-kibana-proxy

As you see, in Kibana, there are also no easy (and free) solutions. :)

**Comment by marefr** [comment] 2018-08-27 10:51
Yeah that's what I thought. When we've implemented #12757 it will be more secure from an index isolation perspective to use the Elasticsearch datasource in Grafana - no way for a user to change javascript code to change index. However this will still not help you - if you can't trust your admins of Grafana you'll have to put the authorization logic in ES or in between Grafana and ES.

**Comment by Photon89** [comment] 2018-08-27 11:56
But if the organization admins have no access to the ES credentials (as in here, #13000) and no possibility to change the ES datasource index (as in #12757), how could they gain access to ES outside the index which is specified in the datasource? Sorry, in case the question is naive, as I stated in my previous comment, I'm a newbie in ES and also in security questions in general.

**Comment by marefr** [comment] 2018-08-27 12:50
Thing is someone must have access to configure the datasource otherwise you won't be able to setup and use Elasticsearch datasources in Grafana at all, right? What other user will this be if not admin? 

Since Grafana is a single page application and the current elasticsearch datasource is executing queries against configured Elasticsearch instance in the browser. Therefore it's possible for any user that has access to the Grafana datasource to change the index (using for example Chrome dev tools) since all code is available in the browser as JavaScript. #12757 removes the actual execution of queries against configured Elasticsearch instance from the browser to the Grafana backend, making it impossible for a user to change the index to something else than configured in Grafana for ES datasource.

**Comment by Photon89** [comment] 2018-08-27 12:59
> Thing is someone must have access to configure the datasource otherwise you won't be able to setup and use Elasticsearch datasources in Grafana at all, right? What other user will this be if not admin?

The use case is that the server admin has access to ES itself and can create datasources for it, while the organization admins have no access to ES itself. They can only manage users in their respective organizations and, possibly, add further datasources but not change the ES datasource which has been created by the server admin.

**Comment by marefr** [comment] 2018-08-27 13:43
> torkelo changed the title from User permissions per dashboard to [Feat Req]: Data source permissions on Oct 25, 2017

Scope/title of feature changed so now it's solely about permissions for datasources.

**Comment by Photon89** [comment] 2018-08-27 13:44
Ah, I see! Thanks for the clarification, I will keep an eye at #2132 and #12757 then!
