### ISSUE TITLE
Add 'Hover tooltip' switch to series overrides in Chart Panel

### ISSUE THREAD

**Issue by bedrin** [grafana/grafana#9954] opened 2017-11-21 12:09 UTC
I am using Chart Panel with 'Hover tooltip: All series' draw option
I would like to be able to exclude some series from the hover tooltip

**Comment by torkelo** [comment] 2017-11-23 08:14
duplicate of https://github.com/grafana/grafana/issues/3341

**Closed by torkelo** 2017-11-23 08:14 UTC
