### ISSUE TITLE
[Enhancement] Dashboard: Copy Paste rows between dashboards

### ISSUE THREAD

**Issue by nmcc1212** [grafana/grafana#25955] opened 2020-06-30 23:12 UTC
**What would you like to be added**:

A copy and paste feature for rows similar to the existing one for panels

**Why is this needed**:

To allow many panels to quickly be transferred between dashboards

**Comment by papagian** [comment] 2020-07-01 06:20
Duplicate of #12372

**Closed by papagian** 2020-07-01 06:20 UTC
Labels: type/duplicate
