### ISSUE TITLE
Time series panel - graph colour scheme rendering in Firefox

### ISSUE THREAD

**Issue by trueuto** [grafana/grafana#37629] opened 2021-08-06 10:25 UTC
**What happened**: A new colour scheme for time series graphs based on thresholds render wrongly in Firefox (messed up colours of the graph). Better in Chromium based browsers, but still graph colour is shifted away from the threshold.

**What you expected to happen**: Graphs rendered properly with colours reflecting defined thresholds.

**How to reproduce it (as minimally and precisely as possible)**:
* Edit/create a panel with a Time Series type of graph
* Configure minimum required options:
  - Gradient mode: Scheme
  - Color scheme: From thresholds (by value)
  - Thresholds: choose any that is in the middle of presented data (e.g. 0*C for temperature chart)
  - Show thresholds: As lines

**Anything else we need to know?**: Works much better in Chrome(ium) based browsers but still not very accurate.

**Environment**:
- Grafana version: 8.1.0 (both installed and clean Docker container)
- Data source type & version: n/a (can be observed with "Random Walk" too)
- OS Grafana is installed on: Debian/Ubuntu (Docker)
- User OS & Browser: Windows/Linux, Firefox ESR/Latest.
- Grafana plugins: n/a
- Others: n/a

Chromium based browser:
![image](https://user-images.githubusercontent.com/49986151/128496706-579403c6-1754-4437-8c98-5f9fc6879cbb.png)

Firefox:
![image](https://user-images.githubusercontent.com/49986151/128496792-a0155166-6164-4b8c-b37b-2969f329d453.png)

**Comment by torkelo** [comment] 2021-08-09 09:01
duplicate of https://github.com/grafana/grafana/issues/37658

**Comment by torkelo** [comment] 2021-08-09 12:54
updated https://github.com/grafana/grafana/pull/37670 so that it fixes this issue as well https://github.com/grafana/grafana/pull/37670

**Closed** 2021-08-13 14:38 UTC
Labels: type/bug, area/panel/timeseries
