### ISSUE TITLE
Specific period for Panel

### ISSUE THREAD

**Issue by kyrianae** [grafana/grafana#17437] opened 2019-06-04 20:10 UTC
**What would you like to be added**:
override the refresh time period of the dashboard for a panel
it should be with time window override 

**Why is this needed**:
depending on dashboard you do, you could have  different lifecycle of data, and heavy query for only one part of the dashboard

> i have a bottelneck with iframe but it could be included directly in the request definition

**Comment by torkelo** [comment] 2019-06-05 05:48
duplicate of https://github.com/grafana/grafana/issues/3514

**Closed by torkelo** 2019-06-05 05:48 UTC
