### ISSUE TITLE
Panel view url doesn't redirect to panel; instead rendering entire dashboard

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#11181] opened 2018-03-09 17:13 UTC
### What Grafana version are you using?
5.0.1

### What did you do?
Naviate the panel view URL 
example : http://grafana/d/000000024/manda?panelId=30&fullscreen&orgId=2
In the dashboard, I have many rows and everything in collapsed hidden state.

### What was the expected result?
Instead of rendering the particular panel, grafana still rendering entire dashboard. 

### What happened instead?
Instead of rendering the particular panel, grafana still rendering entire dashboard. 

![panel](https://user-images.githubusercontent.com/153843/37219921-e1c47e3e-23bc-11e8-8693-726c0c5c9dca.png)

**Comment by bergquist** [comment] 2018-03-12 07:53
dupe of https://github.com/grafana/grafana/issues/11086

**Closed by bergquist** 2018-03-12 07:53 UTC
