### ISSUE TITLE
I added dashboards to playlist  and i want to save the playlist to display it for future purpose

### ISSUE THREAD

**Issue by venkatdba64** [grafana/grafana#3470] opened 2015-12-08 21:53 UTC
I added dashboards to playlist  and i want to save the playlist to display it for future purpose.i unable to see my playlist for next login also.

**Comment by torkelo** [comment] 2015-12-09 09:22
duplicate of https://github.com/grafana/grafana/issues/1137

**Closed by torkelo** 2015-12-09 09:22 UTC
