### ISSUE TITLE
Grafana Service exit on Beagle Bone Black , Ubuntu 20

### ISSUE THREAD

**Issue by binueda** [grafana/grafana#25238] opened 2020-05-30 17:39 UTC
**What happened**:
Grafana service does not start after installation, when manually started exit with below error code
/lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/grafana-server)

**What you expected to happen**:
Grafana services expected to run 

**How to reproduce it (as minimally and precisely as possible)**:
sudo apt-get install -y adduser libfontconfig1
wget https://dl.grafana.com/oss/release/grafana_7.0.1_armhf.deb
sudo dpkg -i grafana_7.0.1_armhf.deb

Start the service 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version:
- OS Grafana is installed on: 
 Linux beaglebone 4.19.94-ti-r36 #1bionic SMP PREEMPT Mon Mar 2 15:55:39 UTC 2020 armv7l armv7l armv7l GNU/Linux , Ubuntu 20
- User OS & Browser: Windows & Firefox 
- Grafana plugins: NA
- Others:

**Comment by aknuds1** [comment] 2020-05-30 21:41
Closing as duplicate of #24844. This issue should be fixed with the next official release, as we've switched to building on Debian Stretch, to ensure compatibility with older versions of glibc.

**Closed by aknuds1** 2020-05-30 21:41 UTC
