### ISSUE TITLE
Dashboard view different than the Explore view when using "Add to Dashboard" option with Loki Datasource

### ISSUE THREAD

**Issue by piettes** [grafana/grafana#63929] opened 2023-03-01 12:02 UTC
**What happened**:

I am trying to set up some dashboard for my log monitoring.
When I go to “Explore”, I can really easily do exactly what I want:

![de1bcef781200a98aaa7cc914023a5caeda34cc4_2_1380x712](https://user-images.githubusercontent.com/5419714/222132091-b28926b8-73b5-400a-ab27-280614dadb3b.png)

So basically a nice bar graph with the log level with different color.
There are also the list of logs in the bottom.

However, when I save this view with “Add to Dashboard”, the same panel in the dashboard view looks different:

![f937f53a662aa600266df05d8115763433ecd3dd_2_1380x380](https://user-images.githubusercontent.com/5419714/222132271-8a5036a4-8aef-4eda-b5e4-176eed0b65f8.png)

Now I only have the list of logs, no graph. The graph should also be there.

**What you expected to happen**:

When we save a panel from the the Explore feature, the dashboard should have the same view (with the graph)

**How to reproduce it (as minimally and precisely as possible)**:

Explore > Data Source: Loki > extract some logs (example {name="backend"} |= `` | json | __error__=``) > add to dashboard

**Anything else we need to know?**:
Here is the original question on the community forum:
https://community.grafana.com/t/panel-view-with-explore-not-the-same-when-added-to-dashboard/82864

**Environment**:
- Grafana version: 9.2.5
- Data source type & version: Loki
- OS Grafana is installed on: 
- User OS & Browser: Macos, Firefox
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment] 2023-03-01 14:20
Dashboards and explore are different by definition. The "Add to Dashboard" button does not copy the whole Explore state to a dashboard, but rather the queries you explicitly have set in Explore (and more precisely, only non-hidden ones) into a single panel inside a dashboard and picks a default visualization based on the current result set. In this case, it uses the logs panel.

The logs volume histogram is additional information we display in Explore (it doesn't use the same query, and datasources have to implement different APIs for it to be supported in Explore in the first place) because of the use case it serves.

Exactly te same happens when adding some prometheus query: in Explore we show both a timeseries graph and a table with the results, but we only add a timeseries panel to the dashboard.

Given this is working as intended, i'm going to close this issue, but those are all valid (and appreciated) suggestions. may i ask you to start a discussion in https://github.com/grafana/grafana/discussions/categories/explore ? we are also considering some other improvements for the future to the whole Explore to Dashboard experience, and any idea would be extremely valuable.

**Closed by Elfo404** 2023-03-01 14:20 UTC
Labels: area/dashboard, area/explore, datasource/Loki, triage/needs-confirmation
