### ISSUE TITLE
setting alerts on dashboard with datasource in variable won't works 

### ISSUE THREAD

**Issue by Nacer-BKRM** [grafana/grafana#11857] opened 2018-05-07 15:46 UTC
Hi there, 

I'm facing an error while trying to set alerts on my dashboard, i'm getting this error when : 

-> Trying to clic on Test Rule  
**Error :** 

t=2018-05-07T17:41:34+0200 lvl=eror msg="Failed to test rule" logger=context userId=1 orgId=1 uname=admin error="Data source not found"
t=2018-05-07T17:41:34+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alerts/test status=500 remote_addr=10.xxx.xxx.255 time_ms=31 size=33 referer="http://grafana.MyServerUrl.org/d/L8KI6yMik/elbs-errors?panelId=6&fullscreen&edit&orgId=1&tab=alert"

-> Trying to save Dashboard after alert creation 
**Error :** 
t=2018-05-07T16:25:57+0200 lvl=eror msg="Invalid alert data. Cannot save dashboard" logger=context userId=1 orgId=1 uname=admin error="Invalid alert data. Cannot save dashboard"
t=2018-05-07T16:25:57+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/db/ status=500 remote_addr=10.xxx.xxx.255 time_ms=1 size
=55 referer="http://grafana.MyServerUrl.org/d/1i1oA8Mmz/test-j?panelId=2&fullscreen&edit&orgId=1&var-datasource=Europe&tab=alert"

-------

If i set a datasource directly and not using variable, it works like a charm :) 

Thank you in advance for your help. 

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by marefr** [comment] 2018-05-07 17:50
Duplicate of #6557

**Closed by marefr** 2018-05-07 17:50 UTC
