### ISSUE TITLE
【Alert】 Grafana sends false alarm and the metric value are health

### ISSUE THREAD

**Issue by SperChung-11** [grafana/grafana#37574] opened 2021-08-05 02:44 UTC
What happened: We have used grafana to monitor the  of the occurrence times of the keyword  and found that grafana sends false alarm and the metric value are health actually

What you expected to happen: grafana doesn't send alarm while the metric value are health

How to reproduce it (as minimally and precisely as possible): may be it can reproduce by follower settings:
![20210805-104322(WeLinkPC)](https://user-images.githubusercontent.com/74529952/128283662-c65a0c75-2d09-4871-a1cb-41ba5612eed6.png)
![20210805-104322(WeLinkPC)](https://user-images.githubusercontent.com/74529952/128283749-57f6fcda-1cfb-417a-ab0e-628df78105b1.png)

Anything else we need to know?: There are two grafana instances which are using the same database instance (mysql 5.7.31)

Environment:
Grafana version: 7.0.3

Data source type & version: Mysql 5.7.31
OS Grafana is installed on: docker
User OS & Browser: Euler OS 2.7
Grafana plugins: elasticsearch
Others:

**Comment by SperChung-11** [comment] 2021-08-20 08:48
hi, @dsotirakis is this a bug

**Comment by dsotirakis** [comment] 2021-08-20 13:08
Looping in @grafana/alerting-squad!

**Comment by SperChung-11** [comment] 2021-08-28 07:16
Ah, i have set the state to "Keep Last State" if no data or values are null or error and so on. Is it possible that the date are delayed and the 'Count' function will count 0 and send alarm ?

**Comment by yuri-tceretian** [comment] 2021-10-13 16:01
Unfortunately, I cannot say anything specific based on screenshots that were taken several minutes after the alert fired. The logs would be very helpful. The queries conditions seem to be straightforward, and if the data looked at 16:35 exactly the same way it is in the screenshot, then I would say that there is (or was because 7.0.3 was release 1.5 yr ago) a bug in Grafana 7.0.3. 
However, the visualization is just a retrospective snapshot of the data at a specific point in time, i.e. there is no guarantee that the data looked the same at 16:35 when the alert fired as it looks in the screenshot.

@SperChung-11 does this still happen in your environment? Can you provide some logs from the last occurrence?

**Comment by santihernandezc** [comment] 2021-11-02 17:33
We're closing this since there's no way to reproduce it. Feel free to re-open it if it happens again.

**Closed by santihernandezc** 2021-11-02 17:33 UTC
Labels: needs more info, area/alerting/legacy
