### ISSUE TITLE
Grafana return 404 not found when a user logged in attempt to view a AnonymousEnabled organization 

### ISSUE THREAD

**Issue by chengyumeng** [grafana/grafana#12190] opened 2018-06-07 02:27 UTC
Consider a scenario where when we configure an organization to log in using an anonymous identity, the expected result is that regardless of whether the user is logged in, they can have specific permissions for that organization.

This question is a real case that appeared in my work. When we build private cloud monitoring reports, the kubernetes organization provides users with full view permissions, but other organizations (such as kafka, mysql, etc.) need to be logged in and authorized to access them.

Therefore, when a user is logged in, there is no way to jump to a group that can be accessed anonymously (404 NOT Found).

**Comment by torkelo** [comment] 2018-06-07 10:12
duplicate of https://github.com/grafana/grafana/issues/10057

**Closed by torkelo** 2018-06-07 10:12 UTC
Labels: comp: backend/auth
