### ISSUE TITLE
Scrolling is broken by recent update.

### ISSUE THREAD

**Issue by fake-name** [grafana/grafana#11267] opened 2018-03-15 19:51 UTC
Read before posting: 
Please include this information:
### What Grafana version are you using?
 5.0.2
### What datasource are you using?
 Irrelevant, but graphite
### What OS are you running grafana on?
 Ubuntu 16.04 LTS
### What did you do?
Let apt-get update, open web UI, scrolled window with mouse.
### What was the expected result?
I expect to get the normal browser scrolling behaviour, which in chromium is a smooth animated scroll.
### What happened instead?
Each mouse scrollwheel detent step produces a hard jump that moves approximately 2X as far as it should.

Please [stop scrolljacking](https://envato.com/blog/scroll-hijacking/). It's anti-user. You're breaking my browser, and making grafana actively worse.

How do I turn this off?

**Comment by daniellee** [comment] 2018-03-16 08:16
Duplicate of #11053. 

We are aware that the scrollbar component we are currently using is not working well and will be replacing it in 5.1 - hopefully with a component that does not do scrolljacking. The reasons for having this component in the first place is to provide consistency in styling in all browsers. For example, Firefox had a bunch of bugs related to the native scrollbars messing up height and width calculations for panels.

**Closed by daniellee** 2018-03-16 08:16 UTC
Labels: type: ux

**Comment by fake-name** [comment] 2018-03-16 08:24
Ugly scroll bars are just ugly.

Right now it's not ugly, it's broken. I'd much rather have unstyled scrollbars then the current state.

Maybe roll back the current override until a replacement that's not broken can be implemented?
