### ISSUE TITLE
Wrong URL for login with auth.anonymous + auth.basic if run with sub path with Grafana >= 9.3+ (ok with <= 9.2)

### ISSUE THREAD

**Issue by sc-amaus** [grafana/grafana#63699] opened 2023-02-24 08:18 UTC
**What happened**:
We are running Grafana mixing auth.anonymous (for dashboard access for users without authentication) and auth.basic (for administrators/dashboard editors).

The instance is served under the sub path `/grafana` with Apache as reverse proxy.

Starting with Grafana 9.3 The "Sign in" link is missing the sub path. It's `https://server.fqdn/?orgId=1&forceLogin=true` instead of
`https://server.fqdn/grafana/?orgId=1&forceLogin=true`.

All other links and menus are ok, manual navigation to the correct link works.

I've tried several versions of Grafana. Up to 9.2.10 the link was correct, all versions of 9.3 and the current 9.4.0-beta1 show the wrong link.

**What you expected to happen**:
"Sign in" will link to the correct URL containing the sub path.

**How to reproduce it (as minimally and precisely as possible)**:
Use grafana.ini provided below and use 9.3 or newer.

**Anything else we need to know?**:
grafana.ini:

```
[paths]
data = /vol_1/data/grafana
temp_data_lifetime = 24h
logs = /var/log/grafana
plugins = /vol_1/data/grafana/plugins

[server]
protocol = http
http_addr = 127.0.0.1
http_port = 3000
domain = server.fqdn
;enforce_domain = false
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
read_timeout = 0

[database]
type = sqlite3
path = grafana.db
max_idle_conn = 2
cache_mode = private

[datasources]

[remote_cache]
type = database

[dataproxy]

[analytics]
reporting_enabled = false
check_for_updates = false
check_for_plugin_updates = false
feedback_links_enabled = false

[security]
disable_initial_admin_creation = false
admin_user = admin
admin_password = ***redacted***
secret_key = ***redacted***
disable_gravatar = true
disable_brute_force_login_protection = false
;cookie_secure = false
;cookie_samesite = strict
;allow_embedding = false
;strict_transport_security = false
;strict_transport_security_max_age_seconds = 86400
;strict_transport_security_preload = false
;strict_transport_security_subdomains = false
;x_content_type_options = true
;x_xss_protection = true
;content_security_policy = false
; content_security_policy_template = """script-src 'self' 'unsafe-eval' 'unsafe-inline' 'strict-dynamic' $NONCE;object-src 'none';font-src 'self';style-src 'self' 'unsafe-inline' blob:;img-src * data:;base-uri 'self';connect-src 'self' grafana.com ws://$ROOT_PATH wss://$ROOT_PATH;manifest-src 'self';media-src 'none';form-action 'self';"""

[security.encryption]

[snapshots]
external_enabled = false
snapshot_remove_expired = true

[dashboards]
versions_to_keep = 20
min_refresh_interval = 5s

[users]
allow_sign_up = false
allow_org_create = false
auto_assign_org = true
auto_assign_org_id = 1
auto_assign_org_role = Viewer
verify_email_enabled = false
default_theme = light
default_locale = en-US
viewers_can_edit = false
editors_can_admin = false

[auth]
login_cookie_name = grafana_session
login_maximum_inactive_lifetime_duration = 7d
login_maximum_lifetime_duration = 30d
disable_login_form = false
disable_signout_menu = false
oauth_auto_login = false

[auth.anonymous]
enabled = true
org_name = EARC Pune
org_role = Viewer
hide_version = true

[auth.github]
enabled = false

[auth.gitlab]
enabled = false

[auth.google]
enabled = false

[auth.grafana_com]
enabled = false

[auth.azuread]
enabled = false

[auth.okta]
enabled = false

[auth.generic_oauth]
enabled = false

[auth.basic]
enabled = true

[auth.proxy]
enabled = false

[auth.jwt]
enabled = false

[auth.ldap]
enabled = false

[aws]

[azure]

[rbac]
permission_cache = true

[smtp]
enabled = false

[emails]
welcome_email_on_sign_up = false

[log]
mode = console file
level = info

[log.console]
level =

[log.file]
level =

[log.syslog]
level =

[log.frontend]
enabled = false

[quota]
enabled = false

[unified_alerting]
enabled = false

[unified_alerting.reserved_labels]

[alerting]
enabled = false

[annotations]

[annotations.dashboard]

[annotations.api]

[explore]
enabled = true

[help]
enabled = true

[profile]
enabled = false

[query_history]
enabled = true

[metrics]
enabled = true

[metrics.environment_info]

[metrics.graphite]

[grafana_com]

[tracing.jaeger]

[tracing.opentelemetry]

[tracing.opentelemetry.jaeger]

[tracing.opentelemetry.otlp]

[external_image_storage]

[external_image_storage.s3]

[external_image_storage.webdav]

[external_image_storage.gcs]

[external_image_storage.azure_blob]

[external_image_storage.local]

[rendering]

[panels]
disable_sanitize_html = false

[plugins]
enable_alpha = false

[live]

[plugin.grafana-image-renderer]

[enterprise]

[feature_toggles]

[date_formats]
full_date = YYYY-MM-DD HH:mm:ss
default_timezone = browser

[expressions]
enabled = true

[geomap]
```

Reverse proxy confguration in Apache:

```
...
        # Grafana
        ProxyRequests   Off
        ProxyPreserveHost On
        ProxyPass /grafana http://127.0.0.1:3000/grafana
        ProxyPassReverse /grafana http://127.0.0.1:3000/grafana

...
```

**Environment**:
- Grafana version: 9.3-9.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Redhat Enterprise Linux 8.7 x86_64
- User OS & Browser: Redhat Enterprise Linux 8.7 x86_64 with Firefox from the OS (102.7.0esr (64-bit))
- Grafana plugins: no additional plugins
- Others: -

**Comment by eleijonmarck** [comment] 2023-02-27 10:54
if anyone picks this up, please assign yourself to the issue

**Comment by Bobobo-bo-Bo-bobo** [comment] 2023-02-28 10:48
Isn't this a duplicate of https://github.com/grafana/grafana/issues/59767 ?

**Comment by hazem-bouaziz** [comment] 2023-03-01 16:16
> Isn't this a duplicate of #59767 ?

it is 
and we're waiting the v9.5.0 to be solved

**Comment by parthvnp** [comment] 2023-04-25 04:40
Hey @eleijonmarck if the issue is still open, I would be willing to work on it!

**Comment by sc-amaus** [comment] 2023-04-26 09:51
Got notification and Immediately updated to 9.5.1 ;)
9.5.1 solved this issue

**Closed** 2023-04-26 09:52 UTC
Labels: type/bug, area/auth, help wanted, beginner friendly, team/grafana-authnz
