### ISSUE TITLE
When creating new Annotation using Azure Data Explorer as datasource, automatically loads all records from the first table causing out of memory failures

### ISSUE THREAD

**Issue by MSDkuznetsov** [grafana/grafana#82876] opened 2024-02-16 08:14 UTC
### What happened?

When I create new annotation, and select Azure Data Explorer (Kusto) as data source, the query preview window automatically loads the first database and first table and runs a query on it. This means it **loads all the records** without any limitations exceeding maximum memory allowed if table is large enough.

### What did you expect to happen?

When creating new annotations, by default the first load shouldn't be automatic, the user has to click "Test" to trigger it, this is how it works on regular panels right now. 

Also it probably makes sense to always have a "| limit XXX" set on all these queries by default to prevent this from causing so much damage.

### Did this work before?

don't know, haven't used this before.

### How do we reproduce it?

1. Go to any dashboard
2. Open Annotations settings
3. Click "New Query"
4. Select "Azure Data Explorer" datasource from data source selector
5. Wait a minute
6. An exception will appear:

`Query execution has exceeded the allowed limits (80DA0001): 'sort' operator has exceeded the memory budget (5368709120) during evaluation. Results may be incorrect or incomplete (E_RUNAWAY_QUERY; see https://aka.ms/kustoquerylimits).. [0]Kusto.Data.Exceptions.KustoServicePartialQueryFailureLimitsExceededException: Query execution has exceeded the allowed limits (80DA0001): 'sort' operator has exceeded the memory budget (5368709120) during evaluation. Results may be incorrect or incomplete (E_RUNAWAY_QUERY; see https://aka.ms/kustoquerylimits)`

![image](https://github.com/grafana/grafana/assets/136453859/d0e61b62-d855-49a6-97fa-a7cb59f99431)

### Environment (with versions)?

Grafana: 9.5.15
OS: Azure Managed Grafana
Browser: Edge

### Grafana platform?

Other

### Datasource(s)?

Azure Data Explorer

**Comment by aangelisc** [comment] 2024-03-05 11:21
Closing as duplicate of grafana/azure-data-explorer-datasource#796

**Closed by aangelisc** 2024-03-05 11:21 UTC
Labels: area/annotations, needs investigation, datasource/Azure
