### ISSUE TITLE
Can I use variables in  "graph->display->Series specific overrides"

### ISSUE THREAD

**Issue by crazy-canux** [grafana/grafana#11836] opened 2018-05-05 08:12 UTC
### What Grafana version are you using?
5.1.0

### What datasource are you using?
influxdb

### What OS are you running grafana on?
ubuntu14.04

### What did you do?
I want to show read/write data in +y and -y in the same time.
After I import my json file to another grafana, the graph changed.
The all in +y.

### What happened instead?
After check, the "alias or regex" not variable.
Can I use variable in this?

**Comment by marefr** [comment] 2018-05-06 07:33
If this is a bug report please include more information:
* Screenshots before/after
* json that you import

**Comment by crazy-canux** [comment] 2018-05-07 02:52
![wanted](https://user-images.githubusercontent.com/14313415/39682837-ca137bc2-51e4-11e8-90d1-d9c2a7dd9850.PNG)
![acture](https://user-images.githubusercontent.com/14313415/39682842-cbead0ee-51e4-11e8-82c0-32080a989d6d.PNG)

**Comment by torkelo** [comment] 2018-05-07 06:13
duplicate of https://github.com/grafana/grafana/issues/5398

**Closed by torkelo** 2018-05-07 06:13 UTC
Labels: state: needs more detail
