### ISSUE TITLE
Disabled series still visible when using Grafana expressions

### ISSUE THREAD

**Issue by zviadm** [grafana/grafana#50781] opened 2022-06-14 12:31 UTC
**What happened**:

Created a graph with Math expressions and few hidden series. Hidden series still show up in the graph in addition to the expression series.

**What you expected to happen**:
Hidden/disabled series to not show up.

**How to reproduce it (as minimally and precisely as possible)**:

Create a graph with __expr__ series and disable series that are participating in the __expr__. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: stackdriver & __expr__
- OS Grafana is installed on: Running in Grafana cloud
- User OS & Browser: MacOsx + Chrome
- Grafana plugins:
- Others:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/517937/173577654-74746993-4936-4541-969c-40c4d772b04f.png">

**Comment by JoaoSilvaGrafana** [comment] 2022-06-20 10:14
Hey @zviadm sorry for the delay, we are having another issue with the expressions that is preventing me from testing it properly, hopefully this week I can test this and get back to you 😃

**Comment by JoaoSilvaGrafana** [comment] 2022-07-08 08:58
Hey @zviadm, I'm having some trouble setting up the Google Cloud Monitoring datasource locally to test it properly, do you have other datasources that you can try to see if it happens on all of them?
Because I can't reproduce on other datasources, I've created a panel with the test data source and that seems to be working as expected (https://play.grafana.org/d/NABb2j3nk/50781-disabled-series-still-visible-when-using-grafana-expressions?orgId=1). Just trying to figure out if it is specific to that datasource or if it is something else that is happening.

**Comment by JoaoSilvaGrafana** [comment] 2022-07-27 13:30
I have managed to reproduce this on a Google Cloud Monitoring datasource, so I believe this is very specific to that datasource. Could someone from @grafana/cloud-provider-plugins help with this issue?

**Comment by asimpson** [comment] 2022-07-27 14:09
:hand: I can look into this

**Comment by asimpson** [comment] 2022-07-27 18:19
I can reproduce this issue as well. For comparison I cannot reproduce this in azure monitor, so it does seem tied to something in cloud-monitor. 

Here's how I reproduce this:
1. Head over to a dashboard of some kind, I used a VM Instance Monitoring dashboard
2. Select a panel to Edit
3. Hide a Query by clicking the :eye: icon, note that the query disappears correctly
4. Add a Math Expression, e.g. `round($A)`
5. Scroll back up and click the :eye: icon again, note that nothing happens

**Comment by asimpson** [comment] 2022-07-27 20:50
Turns out we already had this as an issue, #50449. 

I'm going to close this in favor of that one for now.

**Closed by asimpson** 2022-07-27 20:50 UTC
Labels: needs investigation, area/frontend
