### ISSUE TITLE
Grafana docker container restart loop

### ISSUE THREAD

**Issue by skaugify** [grafana/grafana#20356] opened 2019-11-13 12:16 UTC
**What happened**:
Grafana image is pulled and container is installed. After install, container has status "Up" for a few seconds, then restarts for 1-2 minuts with error code 127. It then starts up again, only to continue in the same loop. If the container is stopped (or not run with --restart always) it will not run afterwards. The status was "up" a couple of times, but the UI was impossible to reach on port 3000.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Not sure about the OS or docker enviroment. We used:
docker pull grafana/grafana:latest
docker pull grafana/gravana:6.4.0-pre1
Both of these failed.

**Anything else we need to know?**:
This is run on a Wago PFC200 PLC. The controller uses ptxdist.

**Environment**:
- Grafana version: v6.4.0-pre1 / latest
- Data source type & version: 
- OS Grafana is installed on: docker 18.09.0 on linux arm.
- User OS & Browser: Docker installed on Linux 4.9.146-rt125 (ptxdist)
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2019-11-13 12:25
Duplicate of #19585

**Comment by marefr** [comment] 2019-11-13 12:26
Fix will be included in Grafana v6.5. Read comments in referenced issue for further information.

**Closed by marefr** 2019-11-13 12:26 UTC
