### ISSUE TITLE
Grafana aarch64 package is not installable on Ubuntu 18.04

### ISSUE THREAD

**Issue by hrw** [grafana/grafana#25024] opened 2020-05-22 15:31 UTC
**What happened**:

```
INFO:kolla.common.utils.grafana:Step 9/11 : RUN grafana-cli plugins install gnocchixyz-gnocchi-datasource     && grafana-cli plugins install grafana-influxdb-08-datasource
INFO:kolla.common.utils.grafana:[91m/usr/share/grafana/bin/grafana-cli: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/share/grafana/bin/grafana-cli)
```

**What you expected to happen**:

"grafana-cli" command works

**How to reproduce it (as minimally and precisely as possible)**:

Install Grafana 7.0.0 arm64 package and run "grafana-cli" command.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: https://packages.grafana.com/oss/deb stable/main repo
- OS Grafana is installed on: Ubuntu 18.04
- Grafana plugins: none
- Others:

Looks like you moved with building to 20.04 or Debian 'buster' making Ubuntu 18.04 not supported on aarch64.

**Comment by zoltanbedi** [comment] 2020-05-22 15:37
Hi @hrw thanks for reporting. This is a duplicate of https://github.com/grafana/grafana/issues/24844 so I'm going to close this. You can track that issue to see progress.

**Closed by zoltanbedi** 2020-05-22 15:37 UTC
