### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by laurian-lamba** [grafana/grafana#7783] opened 2017-03-09 09:11 UTC
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
 Grafana v4.1.2
- What datasource are you using?
Graphite, AWS Cloudwatch, ElasticSearch
- What OS are you running grafana on?
RedHat 6.5
- What did you do?
Add more than 26 queries into a single panel, I ran out of alphabet letters.
- What was the expected result?
No,
- What happened instead?
After the 27th query, no refId is assigned in the GUI, but the JSON shows that in randomly assigns alphabet letters so you will have two queries with the same refId.
In this case you end up with doubled metrics on the graph and in the legend.

Why not use numbers for the refId field ?

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

**Comment by torkelo** [comment] 2017-03-09 09:27
duplicate of https://github.com/grafana/grafana/issues/4978

**Closed by torkelo** 2017-03-09 09:27 UTC
