### ISSUE TITLE
Adhoc filters with ElasticSearch - Error when Time field name is selected

### ISSUE THREAD

**Issue by gigi1981** [grafana/grafana#14174] opened 2018-11-23 13:29 UTC
Please include this information:
### What Grafana version are you using?

5.3.4
### What datasource are you using?
Elasticsearch 5.6+

### What OS are you running grafana on?
Ubuntu 18.04

### What did you do?
I tried to filter a table containing formatted json data coming from elastic. If I click on the magnifier of the "Time field name" an error is received. Using any other field of the table it works fine

### What was the expected result?
A table with filter data using the Time field name value.

### What happened instead?
error, and an empty table is showed

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

[Error-1542978367774.log](https://github.com/grafana/grafana/files/2610843/Error-1542978367774.log)

**Comment by marefr** [comment] 2018-11-23 13:34
Duplicate of #10710

**Closed by marefr** 2018-11-23 13:34 UTC
