### ISSUE TITLE
Alerts - "Plain Text" (i.e., non-html) Email Option?

### ISSUE THREAD

**Issue by davelindquist-egistix** [grafana/grafana#11436] opened 2018-03-29 18:00 UTC
### What Grafana version are you using?
Grafana v5.0.4 (commit: 7dc36ae)
### What OS are you running grafana on?
Docker CE (18.02.0-ce, build fc4de44) on Debian Linux (Stretch/9)
 
### Feature Request
Alerts within Grafana work great, and I have no problem with email alerts.

However, when use email alerts to send via my cell provider's email to MMS gateway (which works REALLY well), Grafana still tries to send an HTML email (understandable).

Can we get an option for alerts that is (for example) "Plain Text Email" (as opposed to the existing "Email" option, which is really "Rich Email")?  This would allow much better quality alerts to go through, and would avoid me receiving a message that includes a dump of raw html (which is what the gateway does to the Grafana HTML message).

Thanks!

**Comment by bbodenmiller** [comment] 2018-10-04 01:43
Also interested in this. Need the ability to get easy to understand text message alerts.

**Comment by bmcgough** [comment] 2019-10-28 16:56
We also have an established notification system that involves an email to text gateway. Right now each Grafana alert generates 10 text messages due to the html formatting and none of them are clear enough for someone not familiar with Grafana and html to decipher.

We can't use Grafana Alert Notifications in our environment until this feature is implemented.

**Comment by luke-guyton** [comment] 2020-01-12 21:42
My company also needs this feature because the email content gets copied to a third party app that only allows text.
I really need a date/time in the message content to aide in identifying the relevance of the alert.

**Comment by nobbich** [comment] 2020-05-20 15:02
same here. would be great to have the existing email channel with html and an additional channel "Email - text only".
should not be a big deal to reduce the existing Email-channel to text-only, i guess.

**Comment by sparklabroom** [comment] 2020-08-06 21:51
Same here. text-only notification is necessary to avoid security and traffic issues.

**Comment by mepster** [comment] 2020-10-08 18:39
Yes please - an email sent though a text gateway like mms.att.net is hard to access... you have to download and open a .html attachment.

It would be great to have the info that is already the html (i.e., the 'Notification Message' text, and the links) in plain text format instead of html. (Note that in the image below, "Air Quality alert" and "Temperature alert" are the 'Rule Name', not the 'Notification Message' - would be good to have both.)

Thanks!

![IMG_122106F720E7-1](https://user-images.githubusercontent.com/154626/95499359-06c1c180-095a-11eb-9092-63f9e0a7d165.jpeg)

**Comment by mepster** [comment] 2020-10-08 19:59
BTW if anyone is up for it, the relevant functions in the repository are:

The data is set up in func (en *EmailNotifier) Notify()
[grafana/pkg/services/alerting/notifiers/email.go](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/email.go)

and then it goes though func (ns *NotificationService) sendEmailCommandHandler()
[grafana/pkg/services/notifications/notifications.go](https://github.com/grafana/grafana/blob/master/pkg/services/notifications/notifications.go)

and then func (ns *NotificationService) buildEmailMessage() is set up to compose a text/html email only,
and then only an html version is sent in  func (ns *NotificationService) dialAndSend()
[grafana/pkg/services/notifications/mailer.go](https://github.com/grafana/grafana/blob/master/pkg/services/notifications/mailer.go)

... but that's as far as I got.

**Comment by djairho** [comment] 2021-03-26 09:40
I would like to give this a try.

After doing some research in the codebase, my idea was to do the following:
* set up a .txt template for all emails currently in the `emails` folder in the root of the repo
* add a `PlainTextTemplate` attribute to the `SendEmailCommand` and the `SendEmailCommandSync`
* make sure the `PlainTextTemplate` attribute is provided in every place where the `SendEmailCommand` is created
* run `mailTemplates.ExecuteTemplate` also on the `PlainTextTemplate` resulting in a HTML buffer and a plain-text buffer
* pass on the rendered plain-text template to a new attribute `PlainTextBody` attribute on the `Message` struct
* in the `dialAndSend` function change `m.SetBody("text/html", msg.Body)` to m.SetBody("text/plain", msg.PlainTextBody)`, followed by `m.SetAlternative("text/html", msg.Body)`

What do you guys think? I'll probably give it a try in the next few days.

**Comment by luke-guyton** [comment] 2021-03-26 09:50
I'll admit I have no idea - are you going to do that on a feature branch and test locally?

Regards,
-Luke Guyton
www.kingdomcity.com


-------- Original message --------
From: djairho ***@***.***>
Date: Fri, 26 Mar 2021, 22:41
To: grafana/grafana ***@***.***>
Cc: Luke Guyton ***@***.***>, Comment ***@***.***>
Subject: Re: [grafana/grafana] Alerts - "Plain Text" (i.e., non-html) Email Option? (#11436)

I would like to give this a try.

After doing some research in the codebase, my idea was to do the following:

  *   set up a .txt template for all emails currently in the emails folder in the root of the repo
  *   add a PlainTextTemplate attribute to the SendEmailCommand and the SendEmailCommandSync
  *   make sure the PlainTextTemplate attribute is provided in every place where the SendEmailCommand is created
  *   run mailTemplates.ExecuteTemplate also on the PlainTextTemplate resulting in a HTML buffer and a plain-text buffer
  *   pass on the rendered plain-text template to a new attribute PlainTextBody attribute on the Message struct
  *   in the dialAndSend function change m.SetBody("text/html", msg.Body) to m.SetBody("text/plain", msg.PlainTextBody), followed by m.SetAlternative("text/html", msg.Body)

What do you guys think? I'll probably give it a try in the next few days.

**Comment by zoltanbedi** [comment] 2021-03-26 10:16
@grafana/backend-platform can you help @djairho?

**Comment by justinmchase** [comment] 2021-03-26 14:51
I am trying to send notifications to a Microsoft Teams channel and it has a similar problem. There it won't render messages over 24k and needs text. I would imagine slack would have a similar issue.

**Comment by marefr** [comment] 2021-03-26 15:37
@djairho could work. But running templates for both HTML and plain text feels not optimal. I would rather introduce a ContentType field on `SendEmailCommand` that per default would continue to be HTML and allow for one SendEmailCommand being migrated to support both HTML and plain text one at a time. Then you could focus opening a PR for solving this issue which is supporting plain text emails for email alerts. WDYT?

Perhaps using a field of `EmailContentType` on the `SendEmailCommand` could be useful:

```go
type EmailContentType int

const (
	EMAIL_CONTENT_TYPE_DEFAULT EmailContentType =  iota
	EMAIL_CONTENT_TYPE_HTML
	EMAIL_CONTENT_TYPE_PLAIN
)

func (ect EmailContentType) String() string {
	names := map[int]string{
		int(EMAIL_CONTENT_TYPE_HTML):  "text/html",
		int(EMAIL_CONTENT_TYPE_HTML):  "text/html",
		int(EMAIL_CONTENT_TYPE_PLAIN):  "text/plain",
	}
	return names[int(ect)]
}
```

**Comment by djairho** [comment] 2021-03-26 16:44
@marefr I understand what you are suggesting. However, the use case I have requires one single email containing both content types as alternatives (meaning: a mail client that supports HTML will show the HTML part, a mail client that doesn't will show the plain-text part). That would not be possible if you always have to specify one content type when using the SendEmailCommand.

Another possibility would be to use a bit mask on the SendEmailCommand for the content types you want.

```
type EmailContentType uint8

const (
	EMAIL_CONTENT_TYPE_HTML EmailContentType =  1 << iota
	EMAIL_CONTENT_TYPE_PLAIN
)

func (ect EmailContentType) String() string {
	names := map[int]string{
		int(EMAIL_CONTENT_TYPE_HTML):  "text/html",
		int(EMAIL_CONTENT_TYPE_PLAIN):  "text/plain",
	}
	return names[int(ect)]
}
```

and then a field `ContentTypeFlags` on the `SendEmailCommand` can be set to either `EMAIL_CONTENT_TYPE_HTML` or `EMAIL_CONTENT_TYPE_PLAIN` or `EMAIL_CONTENT_TYPE_HTML | EMAIL_CONTENT_TYPE_PLAIN`. The `dialAndSend` can then set the body and alternatives (in order, because they must be in order of preference) according to the flags that are set by checking for which `ect EmailContentType` the following condition is true: `m.ContentTypeFlags & ect != 0`.

This seems like a more flexible approach to me.

**Comment by marefr** [comment] 2021-03-26 17:10
> However, the use case I have requires one single email containing both content types as alternatives (meaning: a mail client that supports HTML will show the HTML part, a mail client that doesn't will show the plain-text part). That would not be possible if you always have to specify one content type when using the SendEmailCommand.

That sounds complicated and not really in line what this feature request is asking for - support for sending non-HTML email. I would expect users to create one email notifier for plain text and one notifier for html content type and then assign both to alert rules in case you want both plain text and HTML to be delivered. Might be hard for us to accept what you suggests and would suggest you opening a specific feature request for your use case. 

Normally with these advanced use cases we would suggest integrating with a custom service and webhooks and do whatever you want to do.

**Comment by djairho** [comment] 2021-03-26 17:47
> That sounds complicated and not really in line what this feature request is asking for - support for sending non-HTML email

I don't agree. It's a standard way of sending emails that can be shown across different devices and email clients (they select the content type themselves based on their capabilities). This would most definitely support what the feature request is asking for as well because this allows the user to choose one or multiple content types for the email.

> I would expect users to create one email notifier for plain text and one notifier for html content type and then assign both to alert rules in case you want both plain text and HTML to be delivered.

This would result in sending multiple emails instead of one email than be viewed across different devices and clients. Not desired I would think.

> would suggest you opening a specific feature request for your use case

That is actually what I did in the beginning, see #32345 but it got marked as a duplicate of this issue, which brought me here.

**Comment by djairhogeuens** [comment] 2021-03-26 19:10
> > That sounds complicated and not really in line what this feature request is asking for - support for sending non-HTML email
> 
> I don't agree. It's a standard way of sending emails that can be shown across different devices and email clients (they select the content type themselves based on their capabilities). This would most definitely support what the feature request is asking for as well because this allows the user to choose one or multiple content types for the email.
> 
> > I would expect users to create one email notifier for plain text and one notifier for html content type and then assign both to alert rules in case you want both plain text and HTML to be delivered.
> 
> This would result in sending multiple emails instead of one email than be viewed across different devices and clients. Not desired I would think.
> 
> > would suggest you opening a specific feature request for your use case
> 
> That is actually what I did in the beginning, see #32345 but it got marked as a duplicate of this issue, which brought me here.

FYI: Apparently, I was using an old GitHub account. For future tags, please use @djairhogeuens instead of @djairho as I have deleted that account.

**Comment by justinmchase** [comment] 2021-04-02 23:02
I agree with @djairhogeuens, the bit flag or an array of content types which all get sent in a single email makes sense.

**Comment by djairhogeuens** [comment] 2021-04-03 08:53
I implemented the proposed solution approach. However I did it using a new config setting that contains the list of content types you want in the email (html only by default). I'll try to wrap it up and create a pull request for review later today.

**Closed** 2021-07-19 10:31 UTC
Labels: area/alerting/notifications, type/feature-request
