### ISSUE TITLE
Cannot invite users to an org with login form disabled

### ISSUE THREAD

**Issue by 548017** [grafana/grafana#19001] opened 2019-09-11 08:51 UTC
Grafana setup with oauth authentication, login form disabled.
_auth.disable_login_form: true
auth.generic_oauth.enabled: true_

**What happened**: As an Org admin I want to invite an existing grafana user into my organization, can't find Invite user button.

**What you expected to happen**: I want to be able to invite an existing grafana user into my organization.

**How to reproduce it (as minimally and precisely as possible)**: Disable login form, access an org user administration page, can't find Invite user button.

**Anything else we need to know?**:
Probably affected by https://github.com/grafana/grafana/blob/75fa1f0207f539c34e2e674ac04bd2c01db278c1/pkg/api/org_invite.go#L30 being first check guard.

**Environment**:
- Grafana version: v6.3.5 (67bad72)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by papagian** [comment] 2019-09-11 10:19
duplicate of #17824

**Closed by papagian** 2019-09-11 10:19 UTC
