### ISSUE TITLE
SQLServer queries fail when upgrading to Grafana 9.2

### ISSUE THREAD

**Issue by MikelValencia** [grafana/grafana#57147] opened 2022-10-18 07:09 UTC
**What happened**: When upgrading from Grafana 9.0.2 to Grafana 9.2 almost all the MSSQL Server queries fail

**What you expected to happen**: All upgrades have been transparent since now

**How to reproduce it (as minimally and precisely as possible)**: 
SELECT
$__unixEpochTo() AS time,
count(*) as value,
'With Tokens' as metric
FROM
AD_citrixMFA
where domain in($domain) and device<>''
**Anything else we need to know?**: Screenshot attached with a simple mssql query that worked until 9.2

**Environment**:
- Grafana version: 9.2
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows Server 2019 Standard
- User OS & Browser: Windows 10 Enterprise + Microsoft Edge (Chromium)
- Grafana plugins: Piechart
- Others:
![2022-10-18 08_59_57-Edit panel - Dashboards - Dashboards - Grafana y 8 páginas más - Trabajo_ Micros](https://user-images.githubusercontent.com/94894561/196358759-77b40d56-6db0-43f7-a498-ac437b18ebef.png)

**Comment by eglyn** [comment] 2022-10-18 07:17
Same issue here.
SQL request failed with an error, but if we go into variables and run queries into variables, then the dashboard load correctly. But if we refresh the dashboard (with F5), SQL request error come back :/

**Comment by thomas-netric** [comment] 2022-10-18 07:54
Isn't this a dupe of https://github.com/grafana/grafana/issues/56784 ?

**Comment by ashharrison90** [comment] 2022-10-18 10:45
dupe of #56784 

@eglyn sounds like you have a different issue - please file a separate bug report so we can triage it to the correct squad.

thanks! 🙌

**Closed by ashharrison90** 2022-10-18 10:45 UTC
Labels: type/duplicate

**Comment by JoachimSchiewek** [comment] 2022-10-19 10:06
Datasource MSSQL 
we have the same error since the update to 9.2.
All pannels that access dashboard variables have problems.

Some but not all dashboard variables querys are executed. Regardless of the order.
When I press the "Run query" button the query runs flawless.
