### ISSUE TITLE
[Feature Request]Filter OK state notifications

### ISSUE THREAD

**Issue by dachengxi** [grafana/grafana#9949] opened 2017-11-21 09:32 UTC
Please include this information:
- What Grafana version are you using?  4.6.0
- What datasource are you using? influxdb
- What OS are you running grafana on? centos
- What did you do? Send alerting notification email to manager.
- What was the expected result? Just send Alerting,do not send OK state notification.
- What happened instead?
- If related to metric query / data viz:

Hi, I want to send an alerting email to my manager, but now an ok state notification email also send to him, that's not what i want. Is there any thing i can do to filter OK state notifications?Or just like this :
![image](https://user-images.githubusercontent.com/5352960/33064772-d13cd5b4-cee1-11e7-9d59-2c66f72132a3.png)
When state is ok,not send notifications.
Please help ,Thanks!!!

**Comment by torkelo** [comment] 2017-11-21 09:48
duplicate of https://github.com/grafana/grafana/issues/6696

**Closed by torkelo** 2017-11-21 09:48 UTC
