### ISSUE TITLE
Table: support multi data links

### ISSUE THREAD

**Issue by Betula-L** [grafana/grafana#36263] opened 2021-06-29 10:56 UTC
**Why is this component needed**:

Data link in table cell support only one data link now, whether timeseries and piechart support multi data links.

**Where is/could it be used?**:

Tables need show multi data link sometimes also.

![图片](https://user-images.githubusercontent.com/6059935/123785722-75411800-d90b-11eb-9184-57f639232341.png)
 

**Implementation**

Maybe it can support show a context menu on click as timeseries or piechart if there are multi data links.

**Comment by torkelo** [comment] 2021-07-01 12:52
duplicate of https://github.com/grafana/grafana/issues/27004

**Closed by torkelo** 2021-07-01 12:52 UTC
Labels: area/grafana/ui
