### ISSUE TITLE
Button that has a drop down list is hidden on iPhone 14 pro max

### ISSUE THREAD

**Issue by paladox** [grafana/grafana#62645] opened 2023-02-01 00:05 UTC
**What happened**:
When I go to the main dashboard, the host drop down is hidden. You have to click around to find it.

**On iPhone:**

![867A0F2A-742C-45B7-9145-32B427FB6610](https://user-images.githubusercontent.com/5727000/215912490-f053d933-816e-4c7d-99fc-9c96a82db7dc.png)
![580333E6-0B31-471A-BA83-D24A1FFB4165](https://user-images.githubusercontent.com/5727000/215912497-7aa35d65-0962-4469-a822-32cc279d9d44.png)

**On Desktop:**
<img width="1725" alt="Screenshot 2023-02-01 at 00 08 08" src="https://user-images.githubusercontent.com/5727000/215912750-800ed940-287e-483c-84e8-6c77e30335e6.png">

**What you expected to happen**:
I expect to show the drop down boxes.

**How to reproduce it (as minimally and precisely as possible)**:
Explained in the “what happened”.

**Environment**: iPhone 14 pro max
- Grafana version: 9.3.6
- Data source type & version: Prometheus 2.24.1
- OS Grafana is installed on: debian 11
- User OS & Browser: Safari
- Grafana plugins: redis
- Others:
```[tasklist]
### Tasks


```

**Comment by mellieA** [comment] 2023-02-01 21:19
@paladox are you able to share the output of get help so we can try with a sample of your dashboard? I tried this with play.grafana.com on an iPhone 13 and did not see the same behavior. I tried changing the theme to light theme but I can still see all of the variable drop-downs. Do you see any difference using dark theme?

![get help gif](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by paladox** [comment] 2023-02-05 00:37
Sorry for the late reply, here's the requested dashboard https://phabricator.miraheze.org/F2014796 (Uses prometheus-node-exporter).

**Comment by paladox** [comment] 2023-02-05 00:39
I have the same issue with dark theme.

**Comment by paladox** [comment] 2023-02-05 00:41
although... I imported https://grafana.miraheze.org/d/rYdddlPWk/testing-node?orgId=1&from=now-6h&to=now (updated version of our dashboard that we imported and customised years ago).

It's from https://github.com/rfmoz/grafana-dashboards/blob/master/prometheus/node-exporter-full.json

**Comment by paladox** [comment] 2023-02-05 00:43
Oh nvm now... it's broke on that one as well

**Comment by paladox** [comment] 2023-02-05 00:48
Ok I think I know why. When I removed two links that are added to it, it breaks, when I add them it fixes it?

Confirmed with my other dashboard which adding two links fixed the issue on mobile. Not really great but a workaround neitherless.

**Comment by shezhangzhang** [comment] 2023-06-02 10:35
android is ok, only on iphone.

**Comment by axelavargas** [comment] 2023-07-17 08:16
Hey @paladox 👋🏾, thank you for reporting this issue. I would recommend updating your Grafana instance to at least version 9.5. We [resolved](https://github.com/grafana/grafana/pull/65542) this problem in that version 😄.

**Comment by axelavargas** [comment] 2023-07-17 08:17
P.S. I will close this issue for now, but if the problem continues, please feel free to ping me and we can reopen it. 😄

**Closed by axelavargas** 2023-07-17 08:17 UTC
Labels: area/mobile-support, triage/needs-confirmation, team/grafana-dashboards

**Comment by shezhangzhang** [comment] 2023-07-18 02:35
## Additional notes
this problem is caused by iOS 16.3 or later, if you don't wish to upgrade your grafana version, copy [this code](https://github.com/grafana/grafana/pull/65542/files) into your current grafana source code and rebuild it!

**Comment by paladox** [comment] 2023-07-18 17:03
Thank you!
