### ISSUE TITLE
[Bug] Always disambiguate between tag keys and field keys in where clause drop-down menu for influxDB

### ISSUE THREAD

**Issue by omki2005** [grafana/grafana#9417] opened 2017-10-04 12:49 UTC
InfluxDB allows the set of tag and field keys to intersect. This causes problems with Grafana's query builder tool. e.g., if there is a tag and field key both named "Country" and then we click on the little "+" box next to the "WHERE" box, select "Country" from the drop down menu that appears, we get an "=" sign next to the "Country" box followed by another box with a drop down menu with the list of tag values with the key "Country".

This creates a query of the form :- 
`SELECT median("foo") from "bar" where "Country" = 'USA' AND $timeFilter GROUP BY time($__interval)`

However, this query is ambiguous to influxDB because "Country" is both a tag and a field key. I believe that influxDB defaults to interpreting it as a field key as of version 1.3 but I don't think that is part of the specification.

Grafana should automatically append a ::tag to all columns that we select for the where clause from a drop down box. This makes the behaviour intuitive since the list of items in the drop down menu is the list of tag keys and not field keys. However the generated query in certain situations refers to fields rather than tags.

I'm calling this a "Bug" but I suppose that we could also call it as a "Feature Request" if we allow grafana to specifically select tag and field keys in the where clause.

**Comment by omki2005** [comment] 2017-10-04 12:52
Requested details :- 

- What Grafana version are you using? **4.4.3**
- What datasource are you using? **influxDB**
- What OS are you running grafana on? **RHEL6**
- What did you do? **Selected tag key from where clause drop down menu**
- What was the expected result? **Query with where clause referring to tag key**
- What happened instead? **Query with where clause referring to field key**
- If related to metric query / data viz: **N/A**
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab. **N/A**

**Comment by torkelo** [comment] 2017-10-04 13:19
duplicate of this feature request: https://github.com/grafana/grafana/issues/2674 

We recommend you use value filed, and use influxdb tags for tags :)

**Comment by omki2005** [comment] 2017-10-04 13:50
It's not really a duplicate. As I understand it, #2674 is trying to get Grafana to query the list of field keys to add to the drop down menu for the WHERE clause.

This bug is about the same key appearing as both a tag and a field in the underlying InfluxDB measurement.

In that case, the tag key shows up in the drop down menu as expected but the query that gets generated is ambiguous.

The generated query is this :- 

`SELECT median("foo") from "bar" where "Country" = 'USA' AND $timeFilter GROUP BY time($__interval)`

The expected generated query is this :- 
`SELECT median("foo") from "bar" where "Country"::tag = 'USA' AND $timeFilter GROUP BY time($__interval)`

**Comment by torkelo** [comment] 2020-11-11 08:57
Closing this as it appears to affect few people and InfluxQL is deprecated by Influx

**Closed by torkelo** 2020-11-11 08:57 UTC
Labels: area/datasource, datasource/InfluxDB, type/bug
