### ISSUE TITLE
[Feature Request] Allow disabling left/right Y axes separately

### ISSUE THREAD

**Issue by bbczeuz** [grafana/grafana#3592] opened 2015-12-23 13:31 UTC
As the most current data is on the right side of a graph, I find it easier to have the y-axis on the right side.
Currently I move all metrics to Y2-Axis (Display Styles -> Series specific overrides), but I can't disable the first Y-Axis.

##### Proposal
In Graph->Edit->Axes & Grid->Show Axis, replace checkboxes by:
`[ ] X-Axis    [ ] Y1-Axis    [ ] Y2-Axis`
or
`[ ] X-Axis    [ ] left Y-Axis    [ ] right Y-Axis`

##### Alternative:
In Graph->Edit->Axes & Grid->Left Y->Scale type, add option `none` to disable the left axis
In Graph->Edit->Axes & Grid->Right Y->Scale type, add option `none` to disable the right axis

**Comment by torkelo** [comment] 2016-01-07 19:01
dupe of https://github.com/grafana/grafana/issues/2336

**Closed by torkelo** 2016-01-07 19:01 UTC
