### ISSUE TITLE
Datasource: Allow copy datasource

### ISSUE THREAD

**Issue by KEVISONG** [grafana/grafana#36411] opened 2021-07-03 09:40 UTC
**What would you like to be added**: Allow datasource to be copied.

**Why is this needed**: This is helpful when adding multiple datasources that are only different in table (MySQL) or index (Elasticsearch).

**Comment by torkelo** [comment] 2021-07-05 06:26
duplicate of https://github.com/grafana/grafana/issues/33616

**Closed by torkelo** 2021-07-05 06:26 UTC
