### ISSUE TITLE
Grafana not using the correct value from a variable to execute query

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#32644] opened 2021-04-02 14:21 UTC
**What happened**:
I was trying to create a variable under the field **@timestamp** from some Elasticsearch documents, but Grafana is not using the correct value to execute the query i expected.

**What you expected to happen**:
I expected the service to execute the correct query and return the value i was waiting for, but no value was returned. So i checked the query executed with the button **Query Inspector** and i noticed the query executed with my variable does not correspond to the exact value grafana is returning from the variable query.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a variable that look for different terms for an Elasticsearch Data Source
- Use this variable inside a query to sort the result with only the variable present inside of your documents
- Nothing is returned, but this value is present inside the Elasticsearch indice because Grafana can find it with the variable
- Check the query inspector to see it the variable used for the query is exactly the same as the variable return at the top of the dashboard

**Screenshots**

Variable creation :
![image](https://user-images.githubusercontent.com/33425208/113423211-55fb2300-93ce-11eb-996a-5ac8b951434a.png)

Query while using the variable :
![image](https://user-images.githubusercontent.com/33425208/113423378-a70b1700-93ce-11eb-8dd7-4444241ca04e.png)

Query Inspector; As you can see the value inside the query is different than the value returned. I also tried to trim the "invisible" end of the variable with a quick regex but i still got the same issue :
![image](https://user-images.githubusercontent.com/33425208/113423665-2993d680-93cf-11eb-8085-dfd9b49978e7.png)

Query while manually set the value expected :
![image](https://user-images.githubusercontent.com/33425208/113423720-3f090080-93cf-11eb-8876-bad7b45651f3.png)

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: Elasticsearch 7.12.0
- OS Grafana is installed on: CentOS7 1804
- User OS & Browser: Edge 89.0.774.68

**Comment by Elfo404** [comment] 2021-04-05 11:29
Hello @Theoooooo , thanks for reporting this.
I suspect this is an issue with how the @timestamp is stored, can you please describe your index?
how are you storing your `@timestamp` in your index? 
it seems like it's expressed in seconds, but somehow when interpolating the variable we generate a 13 char timestamp (milliseconds). 

we need to understand if we are adding these zeros out of nowhere or if the problem is somewhere else.

something else that would be very useful would be getting the `_mapping` response from the browser devtools when you save the datasource settings.

**Comment by Theoooooo** [comment] 2021-04-06 07:20
> Hello @Theoooooo , thanks for reporting this.
> I suspect this is an issue with how the @timestamp is stored, can you please describe your index?
> how are you storing your `@timestamp` in your index?
> it seems like it's expressed in seconds, but somehow when interpolating the variable we generate a 13 char timestamp (milliseconds).
> 
> we need to understand if we are adding these zeros out of nowhere or if the problem is somewhere else.
> 
> something else that would be very useful would be getting the `_mapping` response from the browser devtools when you save the datasource settings.

Hello,

Thanks for the reply, here is some informations that might be useful,

When i created the mapping of this index, i did it manually and i specified the different type of value for every field where i needed to do specific operations such as setting the date format for the **timestamp** field.

Regarding the mapping, i set it to **epoch_second** because that's how i'm creating this value when i insert it inside my JSON.
If i check my mapping through Kibana, it's returning me the correct type and format for this field :
```
"@timestamp" : {
  "type" : "date",
  "format" : "epoch_second"
}
```

If i check the response from the Elasticsearch cluster when i'm updating my DataSource from Grafana, it's also returning the correct mapping for this field :
![image](https://user-images.githubusercontent.com/33425208/113673287-1461c500-96b9-11eb-8de1-9243730622e8.png)

I didn't set this mapping to **epoch_millis** because i knew my time value will never be in milliseconds.

If you need any more informations, let me know

**Comment by Elfo404** [comment] 2021-04-09 11:42
Thanks for following up. that's indeed a bug on our side.

**Comment by Elfo404** [comment] 2021-11-12 12:42
Hello @Theoooooo, finaly found some time to look at this.

this was a bit tricky to understand, but I think that this is working as expected. here's why:
as per https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html Elasticsearch internally always stores dates as milliseconds-since-the-epoch. when displaying variables we use `key_as_string` (the formatted value according to the index field mapping) for the labels and `key` (the actual value) as their values.
hence when using `epoch_second` fields as variables their value will always be `epoch_millis`, but the label will be displayed in seconds ( in fact, you also use a format like `strict_date_optional_time||epoch_second`, in this case labels will be nicely formatted like in the following screenshot, but again, the actual value will be in milliseconds).
![Screenshot 2021-11-12 at 12 33 54](https://user-images.githubusercontent.com/1170767/141467993-743170ce-d5be-4344-a494-ecec2f847456.png)

While we could technically switch to using the `key_as_string` (the formatted valaue)  as variables' values, this would mean introducing a major breaking change.

i also just noticed that the regex you were using is missing a capture group, I'm able to make it work by using `/^(\d{10})/`.

I'm closing this issue as I think this is working as expected, but please feel free to comment if you think I'm missing something.

**Closed by Elfo404** 2021-11-12 12:42 UTC
Labels: type/bug, priority/important-soon, datasource/Elasticsearch
