### ISSUE TITLE
Grafana login URL is incorrect after an upgrade from 7.0.5 to 7.0.6

### ISSUE THREAD

**Issue by karlism** [grafana/grafana#26280] opened 2020-07-13 08:39 UTC
**What happened**:
Grafana login no longer works after an update from `7.0.5` to `7.0.6`.

**What you expected to happen**:
If unauthenticated user presses `Sign in` button, redirect to login page would happen:
`https://metrics.example.com/grafana/login?redirect=%2F%3ForgId%3D1`

**What actually happens**:
Unauthenticated user is forwarded to incorrect link (note that `/grafana` is missing in the URL):
`https://metrics.example.com/?orgId=1&forceLogin=true`

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade Grafana to `7.0.6`, press `Sign in` button as unauthenticated user.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.6
- Data source type & version: irrelevant
- OS Grafana is installed on: CentOS 7.8
- User OS & Browser: Chrome
- Grafana plugins:
- Others:
```
[server]
# Protocol (http, https, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = metrics.example.com

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = True

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://metrics.example.com/grafana/

# Log web requests
;router_logging = false

# the path relative working path
;static_root_path = public

# enable gzip
;enable_gzip = false

# https certs & key file
;cert_file =
;cert_key =

# Unix socket path
;socket =
```
We have NGINX load balancer in front of this Grafana instance with following configuration:
```
    server {
        listen 443 ssl http2;
        server_name metrics.example.com;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        ssl_certificate /etc/pki/tls/certs/metrics.example.com.crt;
        ssl_certificate_key /etc/pki/tls/private/metrics.example.com.key;

        location / {
            return 301 /grafana/;
        }
        location /grafana/ {
            proxy_pass http://grafana/;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
```

**Comment by torkelo** [comment] 2020-07-13 08:50
duplicate of https://github.com/grafana/grafana/issues/26228

**Closed by torkelo** 2020-07-13 08:50 UTC
