### ISSUE TITLE
graphs appear empty after a while with Chrome 49

### ISSUE THREAD

**Issue by FlorinAndrei** [grafana/grafana#4378] opened 2016-03-16 00:15 UTC
Grafana-2.6.0 on Ubuntu 14.04
Accessing it with Chrome 49.0.2623.87 (64-bit) on Mac OS X 10.11.3

Open a dashboard in a browser tab, let it run for a while. Meanwhile use other tabs.

After some time, go back to the tab containing Grafana. Some graphs will appear empty (except for the first graph on that page, which always seems okay).

This never happened with previous versions of Chrome.

**Comment by randywallace** [comment] 2016-03-17 22:02
I also am getting the same exact behavior on OS X with that build of Chrome on 2.6.0.  Other things (unrelated to Grafana) are behaving similarly odd, so I believe it is something that Chrome changed in the most recent build, unfortunately.  Dunno what that may be, though.  Happens consistently when I browse to another tab for a short while and then return.  Oddly enough, if I go to another tab again, then return, my graphs show up again... very odd, but more than likely Chrome's fault.

**Comment by keyan** [comment] 2016-03-18 04:24
I've noticed that opening the developer console makes the graphs show up again. Strange behavior.

**Comment by corybuecker** [comment] 2016-03-18 12:40
Same issue here, OSX 10.11.3 (15D21), Chrome 49.0.2623.87 (64-bit). The first chart, top-left, always displays correctly. After switching tabs from and back to Grafana, I end up with chart that look like the attached.

I left it running with Safari 9.0.3 (11601.4.4) for a while and didn't have the same problem.

<img width="526" alt="screen shot 2016-03-18 at 7 39 18 am" src="https://cloud.githubusercontent.com/assets/928069/13878034/a327c6c2-ecdc-11e5-967d-ec231bfcc732.png">

**Comment by torkelo** [comment] 2016-03-20 11:34
I can replicate this in Chrome 49 on mac, seems like a canvas bug in Chrome, no error is thrown, chrome just renders a blank canvas, tricky to troubleshoot further :(

**Comment by liyichao** [comment] 2016-03-26 06:19
It seems the problem is fixed in 49.0.2623.108.

**Comment by gtonello** [comment] 2016-03-28 11:27
Yeah, seems OK to me too with this version on mac.

**Comment by evanbreznyik** [comment] 2016-03-28 16:19
Seems to be the same for me on Mac OS with Chrome: was broken in .87 but seems fixed in .108

**Comment by FlorinAndrei** [comment] 2016-03-28 21:10
Appears fixed with Chrome 49.0.2623.110

**Closed** 2016-04-03 20:02 UTC
Labels: comp: panel/graph, type: bug

**Comment by shezhangzhang** [comment] 2024-05-21 07:46
This bug shows up again on 2024!!!
chrome: 124.0.6367.207
macos: 14.4.1
Firefox, Safari are good.

**Comment by shezhangzhang** [comment] 2024-05-22 03:37
@bobrik Thank you very much, the world is like a circle :-)
