### ISSUE TITLE
No "no_data" recovery notification

### ISSUE THREAD

**Issue by VVilaplana** [grafana/grafana#18622] opened 2019-08-19 11:21 UTC
**What happened**:
After upgrading to 6.2.5, I realised "No Data" alerts don't execute recovery notification. I upgraded to latest (6.3.3) and I observe the same behaviour.

Alerts are properly triggered when there's no data and notification is accordingly sent:

```
t=2019-08-19T11:02:21+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=39 newState=no_data prev state=ok
t=2019-08-19T11:02:21+0000 lvl=info msg=Rendering logger=rendering path="d-solo/SxZhUbmWz/test?orgId=1&panelId=2"
t=2019-08-19T11:02:23+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=39 notification=grafana
```

 but when there's data again, alert calls off without sending any notification).

```
t=2019-08-19T11:03:18+0000 lvl=info msg="New state change" logger=alerting.resultHandler alertId=39 newState=ok prev state=no_data
```

**What you expected to happen**:
Before 6.2.5, I received a '[No Data]' notification message when there was no data, and a '[OK]' notification message when there was data again.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an alert
2. On section "No Data & Error Handling", set "If no data or all values are null" option to "No Data".
3. Force grafana to stop receiving data for that alert to trigger the alert. Grafana logs will show the state changes and a '[No Data]' notification message should be sent.
4. Resume data feed to grafana. Grafana logs will show the state changes, but no notification message is sent.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.3
- Data source type & version: OpenTSDB 2.4
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Debian Buster, Firefox Quantum ESR 60.8
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2019-08-19 18:31
Duplicate of #17780

**Closed by marefr** 2019-08-19 18:31 UTC
