### ISSUE TITLE
Grafana-Altering: Appearing error message ""Missing receiver" and "Missing group labels" after sending test notification

### ISSUE THREAD

**Issue by YimingWei** [grafana/grafana#80267] opened 2024-01-10 08:37 UTC
### What happened?

We configured the SMTP connecttion in /etc/grafana/grafana.ini to enable sending emails by Grafana Altering, but the following error appeared:
![error-1](https://github.com/grafana/grafana/assets/40660586/026f5c00-8f50-4bc8-a045-1e9d5f2eea14)

We checked Grafana log file at /var/log/grafana/grafana.log and found this:
![error-2](https://github.com/grafana/grafana/assets/40660586/85a39eaf-e8db-48a2-97a6-bb1a6da4d2ea)

### What did you expect to happen?

A test notification email should be received by our email contact point.

### Did this work before?

No, it didn't.

### How do we reproduce it?

1.Edit the configuration file "/etc/grafana/grafana.ini" like this:

#################################### SMTP / Emailing ##########################
[smtp]
;enabled = false
enabled = true
;host = localhost:25
host = \<your host\>:\<your port\>
;user =
user = \<your email\>
\# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password = <your email's Authorization code>
;cert_file = 
;key_file = 
;skip_verify = false
;from_address = admin@grafana.localhost
from_address = \<your email\>
from_name = Grafana
\# EHLO identity in SMTP dialog (defaults to instance_name)
;ehlo_identity = dashboard.example.com
\# SMTP startTLS policy (defaults to 'OpportunisticStartTLS')
;startTLS_policy = NoStartTLS

2.Configure recipient address at Grafana->Altering->Contact points like this:
![error-3](https://github.com/grafana/grafana/assets/40660586/718cb14b-2708-4c43-bb53-773737502e11)

3.Send a test notification and the error appeared:
![error-1](https://github.com/grafana/grafana/assets/40660586/f6f362b3-72cb-40e8-ad7d-b2eed6f8f706)

### Environment (with versions)?

Grafana: v8.5.0
OS: Grafana deployed on Linux, Grafana WebUI displayed on Windows
Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment] 2024-02-07 09:49
thank you for reporting this issue @YimingWei 
however, this has been reported already
see /duplicate of #74358 
please continue the conversation in there

**Closed** 2024-02-07 09:50 UTC
Labels: type/duplicate
