### ISSUE TITLE
Unable to update/patch annotation

### ISSUE THREAD

**Issue by zaufi** [grafana/grafana#27018] opened 2020-08-15 19:25 UTC
**What happened**:
I've added a new annotation:
```
$ cat <<EOM | curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer XXXX" http://localhost:3000/api/annotations -d @-
> {
>   "time": $(date +%s)000,
>   "tags":["CI", "test"],
>   "text":"Test Annotation"
> }
> EOM
{"id":23,"message":"Annotation added"}
```
Getting the annotation result in the following output:
```
$ curl -s -H "Authorization: Bearer XXXX" 'http://localhost:3000/api/annotations?type=annotation&tags=test' | jq .'[]'
{
  "id": 23,
  "alertId": 0,
  "alertName": "",
  "dashboardId": 0,
  "panelId": 0,
  "userId": 0,
  "newState": "",
  "prevState": "",
  "created": 1597517011045,
  "updated": 1597517011045,
  "time": 1597517011000,
  "timeEnd": 1597517011000,
  "text": "Test Annotation",
  "tags": [
    "CI",
    "test"
  ],
  "login": "",
  "email": "",
  "avatarUrl": "",
  "data": {}
}
```
Now I'm trying to patch/update it:
```
$ cat <<EOM | curl -s -X PATCH -H "Content-Type: application/json" -H "Authorization: Bearer XXXX" http://localhost:3000/api/annotations/23
> {
>   "timeEnd": $(date +%s)000,
>   "text":"Test Annotation (patched)"
> }
> EOM
{"message":"Annotation patched"}
```
Dupming the annotation shows it unchanged:
```
$ curl -s -H "Authorization: Bearer XXXX" 'http://localhost:3000/api/annotations?type=annotation&tags=test' | jq .'[]'
{
  "id": 23,
  "alertId": 0,
  "alertName": "",
  "dashboardId": 0,
  "panelId": 0,
  "userId": 0,
  "newState": "",
  "prevState": "",
  "created": 1597517011045,
  "updated": 1597519081156,
  "time": 1597517011000,
  "timeEnd": 1597517011000,
  "text": "Test Annotation",
  "tags": [
    "CI",
    "test"
  ],
  "login": "",
  "email": "",
  "avatarUrl": "",
  "data": {}
}
```
**What you expected to happen**:
Updated annotation.

**How to reproduce it (as minimally and precisely as possible)**:
Please use the commands shown above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: github
- OS Grafana is installed on: Exherbo Linux
- User OS & Browser: Firefox 79
- Grafana plugins: none
- Others:

**Comment by marefr** [comment] 2020-10-07 22:34
I just tried to reproduce using your examples, but I cant. It works as expected for me. I'm using Grafana v7.2 but I don't think that should make a difference actually. I would suggest you try 7.2. I'll close this since it works as expected.

**Closed by marefr** 2020-10-07 22:34 UTC
Labels: area/annotations, needs investigation
