### ISSUE TITLE
Grafana query returns error for influxdb 0.12

### ISSUE THREAD

**Issue by FrederikP** [grafana/grafana#4610] opened 2016-04-08 07:34 UTC
grafana version: v2.6.0
Datasource: InfluxDB (0.12)
OS: Debian Jessie

I just upgraded my influxdb to 0.12 and noticed that one of my panels is not showing data anymore.

It creates a query of this structure:
SELECT mean("value") FROM "cpu_user" WHERE "host" = 'example.com' AND time > now() - 24h GROUP BY time(1m) fill(null) 
SELECT mean("value") FROM "cpu_system" WHERE "host" = 'example.com' AND time > now() - 24h GROUP BY time(1m) fill(null) 
SELECT mean("value") FROM "cpu_wait" WHERE "host" = 'example.com' AND time > now() - 24h GROUP BY time(1m) fill(null)

and the new influxdb version does not seem to like missing semicolons. This is the error it returns:
{
  "error": "error parsing query: found SELECT, expected ; at line 2, char 1",
  "message": "error parsing query: found SELECT, expected ; at line 2, char 1"
}

The query was working with influxdb 0.11

It is also the only panel with multiple queries, that I use.

Thanks for having a look.

**Comment by bergquist** [comment] 2016-04-08 07:40
Hi

This is due to an breaking api change in influxdb 0.11.1 for multiline statements.
Dupe of https://github.com/grafana/grafana/issues/4533

**Closed by bergquist** 2016-04-08 07:40 UTC
