### ISSUE TITLE
Logs: "Show context" not working if query contains `unpack`

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#81233] opened 2024-01-25 08:31 UTC
### What happened?

1. Open Explore 
2. Choose Loki as data source
3. Write query `{foo="bar"} | unpack`
4. Observe some logs being returned
5. On one of the log lines, to the far right, press **Show context**
6. Instead of showing any logs in the popup, it uses the query `{} | unpack` and all the logs returned in the popup are empty.
![image](https://github.com/grafana/grafana/assets/89977373/e3817213-7b72-499d-b4b9-a4c31f155d5d)

The problem only appears to happen when the query contain `| unpack`

### What did you expect to happen?

The popup should use the query `{foo="bar"} | unpack`

### Did this work before?

Not certain but i'm pretty sure i've used it ok in Grafana 10.2

### How do we reproduce it?

See above

### Environment (with versions)?

Grafana: 10.3.1
OS: Official Grafana docker image
Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

Loki 2.7

**Comment by nazimisik** [comment] 2024-02-07 11:38
Same behaviour also happens when I use either `json`, `regexp` and `line_format`

**Comment by nazimisik** [comment] 2024-02-07 13:35
![image](https://github.com/grafana/grafana/assets/143480653/23f0204c-71e4-42eb-9714-8d8b711f5f1c)

This comes up also from the console.

Is the error the same with yours? @hterik 

Otherwise I can open another issue

**Comment by svennergr** [comment] 2024-02-08 14:11
Hi @hterik and @nazimisik,

I can not reproduce the described issue.

https://github.com/grafana/grafana/assets/8092184/d94bbd0e-ec55-49ed-8e2d-975d8c718e56



Can you add more information how to reproduce it? And also some information about the Loki version you are using.

Thank you.

**Comment by nazimisik** [comment] 2024-02-09 11:54
Thank you for the quick interest @svennergr !

I cannot easily share the current logs, I need to make a mock. I'll work on it.

but one thing to note is either with unpack or json. On some lines there are jsonparsererror visible. Could that be breaking it?

**Comment by nazimisik** [comment] 2024-02-09 11:56
I guess so, I tried the exact expression with another filter that has no json parse errors, and show context works

**Comment by guillaume5th** [comment] 2024-03-22 11:59
Same here with Grafana 10.3.1 and Loki 2.9.2. As soon as I add a JSON parser, the log context is empty randomly (I cannot easily share the current logs too)

**Comment by hterik** [comment] 2024-04-06 16:26
The error is very intermittent, i have two log lines in the same log stream that do not differ at all in stream labels nor `unpack`'ed label content. Even the log content is almost the same.

Result of` {redacted} |= "modules completed" `
```
2024-04-05 18:41:24.214	{"foo":"manual__2024-04-05T17:10:07+02:00","_entry":"2024-04-05 16:41:24 :: 49/49 modules completed"}
2024-04-05 19:54:49.801	{"foo":"manual__2024-04-05T17:10:07+02:00","_entry":"2024-04-05 17:54:49 :: 46/46 modules completed"}
2024-04-05 20:03:07.887	{"foo":"manual__2024-04-05T17:10:07+02:00","_entry":"2024-04-05 18:03:07 :: 46/46 modules completed"}
2024-04-06 15:28:23.318	{"foo":"manual__2024-04-05T17:10:07+02:00","_entry":"2024-04-06 13:28:23 :: 40/40 modules completed"}
2024-04-06 15:48:46.872	{"foo":"manual__2024-04-05T17:10:07+02:00","_entry":"2024-04-06 13:48:46 :: 40/40 modules completed"}
2024-04-06 16:06:04.191	{"foo":"manual__2024-04-05T17:10:07+02:00","_entry":"2024-04-06 14:06:04 :: 40/40 modules completed"}
```
Using query of  `{redacted} |= "modules completed" | unpack`, on the first 5 lines, **show context** works, on the bottom 2 it doesn't.  Every time i reload grafana window it's the same set of lines that work/doesn't.

As you can see there is a huge span in time between them, but even if i zoom in the query range to only show the last line, that line still fails when pressing show context.

I checked for any broken lines within the stream using `| unpack | __error__ != ""`  but couldn't find anything.

Problem still remains after upgrade to Grafana v10.4.1 and Loki 2.9.6

**Comment by svennergr** [comment] 2024-05-10 13:06
We did a few improvements in the past months. Best experience would be a recent Grafana 11 with a Loki 3.0, as that's where Loki tells us the types of labels (`indexed` vs `nonindexed`).

I'm closing this for now since I had difficulties reproducing, but please feel free to push back or create a new issue.

**Closed by svennergr** 2024-05-10 13:06 UTC
Labels: needs investigation, datasource/Loki, area/panel/logs
