### ISSUE TITLE
Simple Json datasource bug - authentication not working correctly

### ISSUE THREAD

**Issue by RyuCaelum** [grafana/grafana#22642] opened 2020-03-09 10:22 UTC
**What happened**: After a while the datasource for simple json bugs out and the basic authentication section is not picked anymore. This makes it get a 401 error when it tries to reach the endpoint.
When looking at the datasource in grafana, when pressing save & test it does nothing and does not say the datasource is working or failed. 

**What you expected to happen**: For the datasource to work and the basic authentication passes and my datasource endpoint is hit and authorised and my dashboards work.

**How to reproduce it (as minimally and precisely as possible)**: It just happens randomly, not sure how to replicate it other than just wait until it breaks and happens.

**Anything else we need to know?**: Sometimes the access type goes to "" instead of "server" or "browser".  How I am currently fixing this bug is simply changing the access type from server, to browser, back to server then save and only then it picks up the basic authentication details until it breaks again

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on: 
- User OS & Browser: It happens on all browsers. Mac OS.
- Grafana plugins: Simple Json datasource 
- Others:

**Comment by daniellee** [comment] 2020-03-09 23:11
I did a quick test and could not replicate this locally on Ubuntu with Chrome and Firefox.

Can you explain `Sometimes the access type goes to "" instead of "server" or "browser".` Do you mean on the config page or in the request for the "Save and Test" action or something else? Do the dashboards work or is this error only on the config page?

This sounds like either a [Cross Origin error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors) in the browser or that your endpoint is having problems and returning 401's sometimes. Can you see any errors in the Dev Tools console or in the Grafana Server logs?

**Comment by RyuCaelum** [comment] 2020-03-10 14:59
"Sometimes the access type goes to "" instead of "server" or "browser"." 
By this i meant in Grafana, in the datasource. For the access type it would be blank. It would be neither of the options. Then I would need to click on the dropdown bar (where i now see 3 options, server, browser and blank).
That is one issue i sometimes get. Though the main issue is sometimes my dashboards get a 401 when I look at the logs for the api requests. When this happens, it is always because when I am on Grafana and go on the datasource. I see missing fields for the authentication. The password and username for the authentication are definitely saved as if i click on any field to edit they instantly pop back up on the UI. When this happens, I simply press save&test and it works again.

**Comment by daniellee** [comment] 2020-03-10 15:15
@RyuCaelum when you get 401's or when you get the access type issue, are there any errors in your browser console or in the Grafana server logs?

**Comment by RyuCaelum** [comment] 2020-03-13 18:20
<img width="617" alt="Screenshot 2020-03-13 at 18 13 24" src="https://user-images.githubusercontent.com/54808490/76648574-dbf3c400-6556-11ea-9063-0b6e948bf43a.png">
The UI breaks like so when this bug occurs. Even though the the username and password are correct it will say 401 unauthorised in the browser debug. The password and username are correct just to clarify, I have tested that and been using the same password and username when the UI doesn't break. For some reason most ofthe "Auth" section of the UI vanishes and then this makes the username and password not used when hitting the url.

**Comment by RyuCaelum** [comment] 2020-03-13 18:20
@daniellee

**Comment by daniellee** [comment] 2020-03-17 12:02
@RyuCaelum as I can't reproduce this locally, you'll have to help me with more details.

1. Are there any other errors in the browser console? Can you copy and paste the errors into this issue or take a screenshot of the console?
2. Are there any errors in the Grafana server logs? (Do you have access to them?)
3. Which version of Grafana are you using? (You can see that at the bottom of the page in the footer)
4. Which version of the SimpleJson plugin are you using? (You can find this in the plugins section in Grafana)

**Comment by daniellee** [comment] 2020-03-17 12:05
Also, here is how to check if it is a cross origin error: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

**Comment by RyuCaelum** [comment] 2020-03-19 15:33
I am using grafana 6.6.1
SimpleJson version 1.4.0
In the browser console I got this error:
Access to XMLHttpRequest at 'https://XXXX/metrics/' from origin 'https://grafana.XXXX.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by RyuCaelum** [comment] 2020-03-19 15:34
However, when I reset the UI like I have said before I get no console errors.
@daniellee

**Comment by torkelo** [comment] 2020-10-07 12:43
closing this as it looks CORS related

**Closed by torkelo** 2020-10-07 12:43 UTC
Labels: area/backend, area/datasource, needs more detail, type/question
