### ISSUE TITLE
Provision - error with environment variable interpolation for notification policies

### ISSUE THREAD

**Issue by fabien-github** [grafana/grafana#58550] opened 2022-11-09 22:39 UTC
**What happened**:
During provision for notifications policies, environment variable interpolation don't seems to work correcly.

**What you expected to happen**:
Follow the same pattern as others provisions endpoint and interpolate variable.

**How to reproduce it (as minimally and precisely as possible)**:
```
# cat docker-compose.yml
version: '2'
services:
  grafana_tmp:
    image: grafana/grafana-oss:9.2.4
    user: root
    volumes:
      - ./notifications_policies.yml:/etc/grafana/provisioning/alerting/notifications_policies.yml:ro
    environment:
      NOTIFIER_EMAIL_REMINDER_FREQUENCY: 4h
```

```
# cat notifications_policies.yml
apiVersion: 1

policies:
  - orgId: 1
    receiver: test
    group_by: [alertname]
    matchers:
      - alertname = test
    group_wait: 30s
    group_interval: 1m
    repeat_interval: ${NOTIFIER_EMAIL_REMINDER_FREQUENCY}
```

```
# docker-compose up
...
grafana_tmp_1  | Failed to start grafana. error: failure to parse file notifications_policies.yml: not a valid duration string: "${NOTIFIER_EMAIL_REMINDER_FREQUENCY}"
grafana_tmp_1  | failure to parse file notifications_policies.yml: not a valid duration string: "${NOTIFIER_EMAIL_REMINDER_FREQUENCY}"
root_grafana_tmp_1 exited with code 1
```

**Anything else we need to know?**:

Not sure maybe related to this PR https://github.com/grafana/grafana/pull/55666

**Environment**:
- Grafana version: 9.2.4
- Data source type & version: None
- OS Grafana is installed on: Docker
- User OS & Browser: None
- Grafana plugins: None
- Others: None

**Comment by usmangt** [comment] 2022-11-10 16:01
Hi @fabien-github,

Thanks for opening this issue.

I need to ask as where did you found about this env. variable `NOTIFIER_EMAIL_REMINDER_FREQUENCY` as I cannot find it yet.

Also, while I was trying, I notice some incompleteness in your docker-compose file e.g. no port defined, using v2 instead of v3 (just as an observation). But knowing about the above environment variable is the main question :)

**Comment by fabien-github** [comment] 2022-11-10 16:30
Hi @usmangt

thanks for your reply

It's not a grafana environment configuration variable, it's just an environment variable needed to be interpolate by the provisioning configuration, you can name it whatever you want. More here : https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables

For the docker-compose, it's to reproducing the issue, it's not functionnal at all.

FYI, v2 / v3 docker-compose co-exists, v3 is not an evolution of v2, its purpose is to implement docker-swarm with somes options removed.

**Comment by usmangt** [comment] 2022-11-10 20:47
Thanks for providing the details.

Based on your steps of reproduction, I was also able to reproduce it on my test machine. I had tried various ways but not sure why this does not work. Maybe there is a small detail missing which might be the key to defining the time unit (i.e. s, h, m).

I will move it to our team so that they can have a look and might know more about the root cause (if there is a special variable declaration missing or it is simply a bug).

**Comment by armandgrillet** [comment] 2022-11-18 10:21
We have investigated this, we are not interpolating any field for notification policies but we might be able to. @JohnnyQQQQ will try to find a fix for this.

**Closed** 2022-11-22 15:54 UTC
Labels: effort/small, prio/medium, area/alerting/notifications, area/provisioning
