### ISSUE TITLE
[Feature request] Dashboard: organization/user specific variables

### ISSUE THREAD

**Issue by danmx** [grafana/grafana#8350] opened 2017-05-11 18:32 UTC
Grafana Version: 4.2.0
Data source: AWS ElasticSearch (more on the way)

Having organization and/or user specific global variables (e.g. their names) available in templating would allow creation of more personalised dashboards.

This feature plus some query magic could solve [#1313](https://github.com/grafana/grafana/issues/1313)

**Comment by torkelo** [comment] 2017-05-11 19:49
dupe of https://github.com/grafana/grafana/issues/1959

**Comment by torkelo** [comment] 2017-05-12 10:00
kind of (very similar to #1959) so closing

**Closed by torkelo** 2017-05-12 10:00 UTC
