### ISSUE TITLE
Generic OAuth result in 'missing saved state'

### ISSUE THREAD

**Issue by code4me-xx** [grafana/grafana#20985] opened 2019-12-10 06:53 UTC
**What happened**:
Using generic OAuth (Auth0 or Keycloak) result in login.OAuthLogin(missing saved state)

![image](https://user-images.githubusercontent.com/1695378/70502651-b7381c80-1b21-11ea-944f-e7c0e400d177.png)

**What you expected to happen**:
Normal login and redirect to home dashboard

**How to reproduce it (as minimally and precisely as possible)**:
Using auth.generic_oauth with Keycloak or Auth0 just like mentioned in the Grafana documentation
https://grafana.com/docs/grafana/latest/auth/generic-oauth/

[auth.generic_oauth]
enabled = true
allow_sign_up = true
name = Auth0
client_id = <client id>
client_secret = <client secret>
scopes = openid profile email
auth_url = https://<domain>/authorize
token_url = https://<domain>/oauth/token
api_url = https://<domain>/userinfo

**Anything else we need to know?**:
I've verified the behavior on HTTPS behind an Apache web server and on a local installation with the same result. Logs shows nothing at it looks like the user is granted access. It is the same result with existing and new user, but on a local fresh install it only happens on the first login attempt.
 
**Environment**:
- Grafana version: 6.5.1
- Data source type & version: MySql 
- OS Grafana is installed on: Verified on Windows Server 2012 R2 and Linux Mint 19
- User OS & Browser: Firefox, Chrome 
- Grafana plugins: Verified without plugins  
- Others: Configuration

domain = mydomain
root_url = https://mydomain
cookie_secure = true
signout_redirect_url = https://mydomain/keycloak/auth/realms/Marine/protocol/openid-connect/logout?redirect_uri=https://mydomain/login
enabled = true
name = Keycloak
allow_sign_up = true
client_id = Grafana
client_secret = xyz
scopes = openid email
auth_url = https://mydomain/keycloak/auth/realms/Marine/protocol/openid-connect/auth
token_url = https://mydomain/keycloak/auth/realms/Marine/protocol/openid-connect/token
api_url = https://mydomain/keycloak/auth/realms/Marine/protocol/openid-connect/userinfo
email_attribute_name = email
disable_sanitize_html = true

**Comment by marefr** [comment] 2019-12-10 11:00
Duplicate of #17978

**Comment by marefr** [comment] 2019-12-10 11:09
This error means that there is no cookie set when redirecting back to Grafana from OAuth provider. Feels like a configuration error to me so will close this, but consider re-open if you can provide information that shows this is a Grafana problem/bug.

One way to understand what going on is to use chrome developer tools and network tab, check preserve log and then click on OAuth login button on Grafana login page to capture all the requests happening until redrected back to Grafana. Then inspect outgoing redirect request to OAuth provider and what cookies and cookie attributes are set and further inspect what cookies are set when redirect request back to Grafana is received.

**Closed by marefr** 2019-12-10 11:09 UTC

**Comment by code4me-xx** [comment] 2019-12-16 06:35
Thank you, it turned out you were right. I'll just add the comments below if anyone runs into the same scenario.

a) It is important that Java is updated and it is a JDK
b) A additional firewall before the web server might block or not forward host ip in headers
c) The settings below for Apache or Nginx  will work but adjust to your needs

```
Apache

ProxyPreserveHost	on
RemoteIPHeader X-Forwarded-For
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"
ProxyPass		/keycloak	http://<server>:9090/keycloak
ProxyPassReverse	/keycloak	http://<server>:9090/keycloak
ProxyPass		/		http://<server>:3000/
ProxyPassReverse	/		http://<server>:3000/
```

```
Nginx

location / {
	proxy_set_header Host                 $http_host;
	proxy_set_header X-Real-IP            $remote_addr;
	proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto    "https";
	proxy_set_header X-Forwarded-Port	  "443";
	proxy_pass http://<server>:3000/;
}
location /keycloak/ {
	proxy_set_header Host                 $http_host;
	proxy_set_header X-Real-IP            $remote_addr;
	proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto    "https";
	proxy_set_header X-Forwarded-Port	  "443";
	proxy_pass http://<server>:9090/keycloak/;
}
```

**Comment by epictralala** [comment] 2020-08-17 12:22
cookie_samesite =lax 

fixed this on my grafana
