### ISSUE TITLE
Overflow issue on small SingleStat panels

### ISSUE THREAD

**Issue by prayzzz** [grafana/grafana#17293] opened 2019-05-27 08:53 UTC
**What happened**:

With v6.2 the overflow / word-break behaviour of SingleStat panels changed. Long texts are now placed on top of each other.

![singlestat 2](https://user-images.githubusercontent.com/9248359/58408201-9d475880-806d-11e9-9f24-0a5505b2ba7a.png)

**What you expected to happen**:

Keep the word-break behaviour of `<= 6.1.x` and hide the overflow if the height is exceeded.

![singlestat](https://user-images.githubusercontent.com/9248359/58408202-9ddfef00-806d-11e9-8abc-835deaf4e1cb.png)

**How to reproduce it (as minimally and precisely as possible)**:

Create small SingleStat panels with a unit. Especially `duration` is affected by this.

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: any
- OS Grafana is installed on: Linux
- User OS & Browser: Edge Dev Channel
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment] 2019-05-27 09:07
dupe of https://github.com/grafana/grafana/issues/17237

**Closed by torkelo** 2019-05-27 09:07 UTC
