### ISSUE TITLE
Dashboards: Image Renderer Link incorrect when behind reverse proxy

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#81640] opened 2024-01-31 13:34 UTC
### What happened?

Whilst investigating another bug I discovered that if I put Grafana behind a reverse proxy without `serve_from_sub_path = true` the **Direct link rendered image**  image renderer share url appears to strip the subpath from the url...

<img width="1792" alt="Screenshot 2024-01-31 at 14 21 07" src="https://github.com/grafana/grafana/assets/73201/bbfab3e5-9acd-4fa6-979b-4b161e604489">

To the best of my knowledge it's happening in the [TextLink component here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Link/TextLink.tsx#L49). You can see in the screenshot the react component href prop contains the correct path.

### What did you expect to happen?

For the url to contain the subpath.

### Did this work before?

Not sure, I believe so.

### How do we reproduce it?

Setup grafana locally under a subpath...

```
# data/custom.ini

[server]
# The full public facing url you use in browser, used for redirects and emails
domain = grafana.loc
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
# serve_from_sub_path = true

[rendering]
server_url = http://localhost:8081/render
callback_url = http://localhost:3000/
```

This zip contains an nginx proxy config to reproduce the issue: [grafana-nginx.zip](https://github.com/grafana/grafana/files/14112210/grafana-nginx.zip)

1. start nginx.
2. set your hosts file to point grafana.loc to 127.0.0.1
3. clone [grafana-image-renderer](https://github.com/grafana/grafana-image-renderer)
4. run `yarn install && yarn build` in image-renderer
5. serve image renderer with `node build/app.js server --port=8081`
6. start the grafana server
7. navigate to dashboard and try to share a panel

### Environment (with versions)?

Grafana: `main`
OS: `Mac OS X`
Browser: `Chrome`

### Grafana platform?

Other

**Comment by cr1xu5** [comment] 2024-02-01 08:44
This bug was introduced in Grafana version 10.2.3. The "Direct link rendered image" URL includes the subpath in 10.2.2.

Our configuration:

```
GF_SERVER_ROOT_URL: https://domain.com/grafana/
GF_SERVER_SERVE_FROM_SUB_PATH: "true"
```

**Comment by JoaoSilvaGrafana** [comment] 2024-02-02 12:11
Thanks for raising this Jack! I have managed to reproduce it with just subpath configured and with any `TextLink` that is marked as `external` but links to Grafana. It seems to be exactly that line you mentioned that is stripping away the subPath. I believe we shouldn't be stripping away subpaths for external links, there doesn't seem to be any point to it. Will open a PR for it

**Comment by hafu** [comment] 2024-02-02 14:05
Links to dashboards in Alerting > Alert rules > View rule are also affected. The sub path is missing. Only the frontend seem to be affected, the URLs in the notifications are correct.

My configuration:
```
GF_SERVER_DOMAIN=host.tld
GF_SERVER_ROOT_URL=https://host.tld/grafana/
GF_SERVER_SERVE_FROM_SUB_PATH=true
```

Nginx as reverse proxy is configured [as described](https://github.com/grafana/grafana/blob/71bfea4328d10f2298a8c24f602bfb7de3dd15d7/docs/sources/tutorials/run-grafana-behind-a-proxy/index.md).

My work around for now is the following in the nginx config:
```
server {
      # …
      location /grafana/ {
        proxy_set_header Host $http_host;
        proxy_pass http://grafana;
      }

      # Proxy Grafana Live WebSocket connections.
      location /grafana/api/live/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $http_host;
        proxy_pass http://grafana;
      }

      # fix broken links
      location /render/ {
        return 301 https://$server_name/grafana$request_uri;
      }

      location /d/ {
        return 301 https://$server_name/grafana$request_uri;
      }

}
```

**Closed** 2024-02-05 10:48 UTC
Labels: type/bug, area/frontend
