### ISSUE TITLE
Alerting: Labels from elasticsearch terms are not working in templating

### ISSUE THREAD

**Issue by Vimao** [grafana/grafana#36938] opened 2021-07-20 07:27 UTC
**What happened**: Labels that are trying to utilize terms from Elasticsearch searches are not being populated

**What you expected to happen**: Labels utilizing terms from Elasticsearch searches are correctly populated

**How to reproduce it (as minimally and precisely as possible)**: Create an alerting rule that is utilizing the Group By Terms option of Elasticsearch datasource, and group by a term that is a part of a complex JSON structure, Reduce the data to prepare a multi-dimensional alert, and then try to utilize the labels in any form (Description, notification etc.)

**Anything else we need to know?**: This feature is not working when the label is a part of a complex structure (object, array). If the field is containing "." in its name, labels are not being created properly

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Elasticsearch 7.13
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu, Edge DEV and Firefox
- Grafana plugins: None other than preinstalled plugins

- Others: Part of the grafana.log indicating the issues [grafana labels.txt](https://github.com/grafana/grafana/files/6846314/grafana.labels.txt)

**Comment by ifrost** [comment] 2022-01-14 12:37
Duplicate of #40193

**Closed by ifrost** 2022-01-14 12:37 UTC
Labels: area/alerting, datasource/Elasticsearch, needs investigation
