### ISSUE TITLE
The table content is long and the table header is misplaced.

### ISSUE THREAD

**Issue by wanpingDou** [grafana/grafana#13298] opened 2018-09-17 02:37 UTC
### What Grafana version are you using?

Grafana v5.0.0

### What datasource are you using?

ClickHouse

### What OS are you running grafana on?

Linux

### What did you do?

In Grafana, if the table content is long, the table will be misplaced. In this way, the labels of many table headers are not visible. Can the contents of the form be automatically wrapped? Or, how do I set the label on the table header to be good?

**Comment by marefr** [comment] 2018-09-17 08:03
Duplicate of #3281

**Closed by marefr** 2018-09-17 08:03 UTC
