### ISSUE TITLE
Grafana 8.0.4 not able to create/save any new contact point, getting 504 time out error

### ISSUE THREAD

**Issue by LaxmiRajawat** [grafana/grafana#37354] opened 2021-07-29 14:06 UTC
Hi Grafana team,

We have recently migrated to Grafana 8.0.4 but I m not able to create any new contact point using any type like email, existing notification email also not working. getting 504 time out error while saving any new or existing contact point, please find attached error, I am selecting Grafana from alert manager drop down. Please let me know how to fix this error. Thanks for your help.

![contact point snap](https://user-images.githubusercontent.com/87098594/127506233-5666aed6-00e0-4a41-b485-cc4c7dc3b86c.JPG)

**Comment by kylebrandt** [comment] 2021-07-30 12:47
Duplicate of https://github.com/grafana/grafana/issues/36525 which is still unresolved.

**Closed by kylebrandt** 2021-07-30 12:47 UTC
