### ISSUE TITLE
Value mapping in stat panel does not resolve variable

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#26994] opened 2020-08-13 15:27 UTC
**What happened**:
I've added a stat panel and tried to map a value to a variable value, it shows the parameter name not its value
**What you expected to happen**:
That the value will be displayed

In the image, the header is replaced correctly, but the value is not.

![image](https://user-images.githubusercontent.com/2118079/90154158-75d3cd00-dd92-11ea-9b96-5b9c43c00949.png)

**How to reproduce it (as minimally and precisely as possible)**:
Add a dashboard with a variable and map a value to it
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser: fedora
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2020-08-14 08:24
duplicate of https://github.com/grafana/grafana/issues/26654

**Closed by torkelo** 2020-08-14 08:24 UTC
