### ISSUE TITLE
Grafana 7.0.x login using Microsoft Edge 1803 browser failing 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#26007] opened 2020-07-02 09:15 UTC
**What happened**:

When trying to login from MS Edge version 1803 (from 2018) browser to Grafana 7.0.x  a 'login successful' message is returned on the edge screen then redirects back to login page again.  
- There is no problem with Grafana v6.6.2 with same Edge browser. 
- There is no issue with chrome browser with the same 7.0.x environment.

**What you expected to happen**:

Successful login

**How to reproduce it (as minimally and precisely as possible)**:

Try to log in to Grafana 7.0.4 using MS edge browser 

**Anything else we need to know?**: 

The Grafana Log says the user logged in successfully. there is no any kind of error in log. 

User log says login is successful 

![image](https://user-images.githubusercontent.com/54800912/86340340-075d0480-bc55-11ea-81ac-819203235ca9.png)

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: n/a 
- OS Grafana is installed on: Centos 7 
- User OS & Browser: Windows 10 - MS Edge version below 
- Grafana plugins: n/a 
- Others: n/a 

![image](https://user-images.githubusercontent.com/54800912/86340415-25c30000-bc55-11ea-8ef9-67b1bc51cde8.png)

![image](https://user-images.githubusercontent.com/54800912/86340424-2a87b400-bc55-11ea-8a60-76fa29134bec.png)

![image](https://user-images.githubusercontent.com/54800912/86340434-2f4c6800-bc55-11ea-8691-42ea4625626f.png)

**Comment by aknuds1** [comment] 2020-07-02 09:19
This is version 7.0.4 to be specific?

**Comment by aengusrooneygrafana** [comment] 2020-07-02 09:33
Correct, 7.0.4

**Comment by aknuds1** [comment] 2020-07-02 09:36
Updated your issue description to clarify Grafana and Edge versions.

**Comment by tskarhed** [comment] 2020-07-02 12:25
Might be related to these functions https://github.com/grafana/grafana/blob/2d4bcbeff617bb921348536c652fecc410960875/public/app/core/components/Login/LoginCtrl.tsx#L97
https://github.com/grafana/grafana/blob/2d4bcbeff617bb921348536c652fecc410960875/public/app/core/components/Login/LoginCtrl.tsx#L126

I think the backend handles the redirect functionality on `/`. When not authenticated it directs to `/login`.

Just to be sure; there isn't any redirectUrl in the url?

**Comment by AgnesToulet** [comment] 2020-07-02 12:27
FYI, this is a duplicate of #25507 where there is a bit more information around this issue.

**Comment by aengusrooneygrafana** [comment] 2020-07-02 13:23
Thanks all, and yes agree, this is a duplicate - however I see there is some important information above on the possible functions responsible - Tobias, do you want to copy that across to #25507 and close off this issue?

**Closed** 2020-07-02 13:27 UTC
Labels: area/frontend, needs investigation
