### ISSUE TITLE
Drowdown variable value persists on page reload even though the dashboard is not saved

### ISSUE THREAD

**Issue by rmunoz10** [grafana/grafana#19790] opened 2019-10-13 18:31 UTC
I have a child dropdown variable whose values depend on a parent variable.  The child variable gets the correct values but the display value does not get reset to the first value in the list

You reproduce with a single drowdown variable as well. Say values are 1,2,3.  Then select 2.  Then refresh the dashboard for new parent.  I would expect the value selected on the child variable to be 1 - instead it is 2.

Note: We are using the child variable to select a min value.

This issue may be related to #2215

**Environment**:
- Grafana version: 6.5
- Data source type & version: Postgres 11
- OS Grafana is installed on: Centos 7.2
- User OS & Browser: Ubuntu, Firefox
- Grafana plugins:
- Others:

Thanks

**Comment by papagian** [comment] 2019-10-14 10:32
I'm unable to reproduce it.
Which is the query for the child variable?
Also, could you specify the correct grafana version you are using? The latest available is 6.4.2.

**Comment by rmunoz10** [comment] 2019-10-17 23:36
You can use a simple list to reproduce.  In Postgres the query is 
select a
from (
    values (1), (2),(3),(4),(5)
) s(a);

The issue is not with a child query per se. The issue is when you select a value (say 2), then refresh the dashboard, the list defaults to to 2 again.  The expectation is to default the first value (1).
As another example.  Say the list is created dynamically and now the list is {0.5, 1, 1.5, 2, 2.5}. The selected value will show 2 again when it should be 0.5. The issue arises when the previous value selected shows up again when the same list is refreshed
Hope this makes more sense.
I am using the 6.5-pre from the trunk
Thanks

**Comment by papagian** [comment] 2019-10-18 13:36
Not sure if this is actually a bug.

Steps to reproduced it:
- created a query variable:
```
select a
from (
values (1), (2),(3),(4),(5)
) s(a);

```
- Select a value (for example 2) and save the dashboard
- Reload page; the select value is as expected 2
- Change value, for example 3
- Reload page without saving the dashboard; the select value is now 3
- Navigate outside dashboard and return back; the value is the saved one 2.

**Comment by rmunoz10** [comment] 2019-10-18 14:04
The save functionality is not part of the issue.
Assume the list is a dynamic list from min-value to max-value depending on some other value x
x=1, list-var is {2,3,4,5}
x=2, list-var is {1,2,3,4,5}

Set x=1. List-var shows 2 (correct). Select 3
Set x=2. List-var shows 3 (incorrect) => Should be 1

**Comment by hugohaggmark** [comment] 2020-11-12 07:39
Closing this issue as I can't repro it on Grafana v7.3.1 (6668161a88) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2020-11-12 07:39 UTC
Labels: area/dashboard/templating, datasource/Postgres, type/bug
