### ISSUE TITLE
Variable resolution deadlock (user mistake)

### ISSUE THREAD

**Issue by msaf1980** [grafana/grafana#27847] opened 2020-09-28 06:56 UTC
Dashborad load hangs when variables has a cyclic reference.

**How to reproduce it (as minimally and precisely as possible)**:
Create datasource Graphite and import dashboard from attachment

[test.json.txt](https://github.com/grafana/grafana/files/5290399/test.json.txt)

Variables Host and Project has cross-reference.

**Environment**:
- Grafana version: all, as I know (including current master)
- Data source type & version: Graphite (may be other)
- OS Grafana is installed on: all
- User OS & Browser: all

**Comment by torkelo** [comment] 2020-09-28 14:20
duplicate of https://github.com/grafana/grafana/issues/12743

**Closed by torkelo** 2020-09-28 14:20 UTC
