### ISSUE TITLE
How to create grafana bar charts which include multiple bars in one bar

### ISSUE THREAD

**Issue by satyabhama** [grafana/grafana#25855] opened 2020-06-26 07:33 UTC
Can we club multiple bars in one bar as shown in attached screen shot.

![image](https://user-images.githubusercontent.com/11815146/85832264-5e725d80-b7ad-11ea-9647-84ac012fbaab.png)

**Comment by torkelo** [comment] 2020-06-26 14:47
duplicate of https://github.com/grafana/grafana/issues/870

**Closed by torkelo** 2020-06-26 14:47 UTC
