### ISSUE TITLE
external js script are loaded but not recognized

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#88453] opened 2024-05-29 17:47 UTC
### What happened?

Using htmlgraphics panel, from grafana10.4 to 11 several js script, even loaded locally, are yes correctly loaded but then the object itself is not recognized. The problem is that this is happening with several script, pdf-lib.min.js just to name one.

### What did you expect to happen?

The object created by the script is defined and usable as it was till last version

### Did this work before?

yes

### How do we reproduce it?

You can reproduce it by loading this script https://cdn.jsdelivr.net/npm/pdf-lib/dist/pdf-lib.min.js into the oninit section and check for the PDFLib object. It will be undefined

### Environment (with versions)?

Grafana: 11
OS: debian
Browser: chrome

### Grafana platform?

Docker

### Datasource(s)?

mysql

**Comment by thanissi** [comment] 2024-05-30 22:28
possibly the same issue as reported in https://github.com/grafana/grafana/issues/88438

**Comment by DonatoD** [comment] 2024-06-03 13:35
yes, it seems the same

**Comment by L-M-K-B** [comment] 2024-06-13 13:50
Since this is caused by the same issue that is already mentioned [here](https://github.com/grafana/grafana/issues/88438) I'll close this issue.

**Closed by L-M-K-B** 2024-06-13 13:50 UTC
Labels: area/frontend
