### ISSUE TITLE
Configurable timeout for Opentsdb datasource queries

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3730] opened 2016-01-14 07:43 UTC
Consolidating issues here:
#3596 
#3168 
#3239 

Setting timeout for Opentsdb queries will solve the above issues. If @torkelo is ready to accept a PR on it, I can work on it. :)

**Comment by torkelo** [comment] 2016-01-14 07:46
not sure the issues are related to OpenTSDB in particular, PR for solving the issues linked to would be great!

**Comment by utkarshcmu** [comment] 2016-01-14 07:47
OK. Got it.

**Comment by torkelo** [comment] 2016-01-14 07:49
but your right, all seem to be fixed with a short timeout. Not sure if it's the correct fix for all though, maybe working around some other underlying problem in the proxy feature? Not sure, strange.

**Comment by utkarshcmu** [comment] 2016-01-14 07:52
Lets keep this issue open then. Also, slow direct datasource makes Grafana unresponsive. I have a very slow graphite server which is a direct datasource and it is hell to make a complex dashboard with it as it makes Grafana unresponsive if the panel queries take too much time in getting the response from the datasource.

**Comment by utkarshcmu** [comment] 2016-01-14 07:53
Solution to #3168 should fix most of the problems.

**Comment by torkelo** [comment] 2016-01-14 07:53
that make no sense what's so ever, are you sure graphite just slow and not returning A LOT more data than maxDataPoints? (using old graphite servers will do that). 

I mean a slow metric query (taking time to respond with data) will not hang/slow down grafana

**Comment by utkarshcmu** [comment] 2016-01-14 07:57
Yes, I have dealt with a slow graphite. And about 50 queries are triggered to this slow graphite from Grafana dashboard. Until more than half of the queries come back, I am not able to Save dashboards, etc.

May be these unresponsive queries make backend related features slow, keeping the frontend features working normally.

**Comment by torkelo** [comment] 2016-01-15 07:09
will close this as it's dupe of #3168

**Closed by torkelo** 2016-01-15 07:09 UTC
