### ISSUE TITLE
[Bug] Server-side rendering broken, no useful logging output

### ISSUE THREAD

**Issue by avinson** [grafana/grafana#7197] opened 2017-01-10 01:14 UTC
there were a few bug fixes related to phantomjs server side rendering lately (such as https://github.com/grafana/grafana/pull/6813)

however, all pre-rendering seems to be broken for me (direct link and uploads) and there is not any useful log output:

```
t=2017-01-10T01:07:01+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/testing?&panelId=2"
t=2017-01-10T01:07:02+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="open /var/lib/grafana/png/5x9AO6mD3sahBql96cb2.png: no such file or directory"
```

i use a pretty vanilla config with the only exception being using an haproxy reverse-proxy:
```
GF_SERVER_ROOT_URL = "https://grafana.internal.prod-us-west-1.aws.mydomain.com"
```

how can i increase log level on png-renderer to see what's going on? i tried 4.0.2, latest, master and 4.1-beta1 docker images all with same results. thanks.

**Comment by avinson** [comment] 2017-01-10 07:26
also, setting GF_LOG_LEVEL does not seem to increase verbosity of png-renderer (possibly related to this: https://github.com/grafana/grafana/issues/6978). i'll try on master branch again tomorrow.

**Comment by avinson** [comment] 2017-01-11 00:23
with debug logging turned on, there isn't much more in the way of useful info:

```
t=2017-01-11T00:20:27+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/app-metrics?panelId=3&from=1484072425867&to=1484094025867&width=1000&height=500"
t=2017-01-11T00:20:28+0000 lvl=dbug msg="Image rendered" logger=png-renderer path=/var/lib/grafana/png/NMCGGSu1P2IlPLb2hT5M.png
t=2017-01-11T00:20:28+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/dashboard-solo/db/app-metrics status=404 remote_addr=10.1.13.220 time_ms=804ns size=19
t=2017-01-11T00:20:28+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/favicon.ico status=404 remote_addr=10.1.13.220 time_ms=23ns size=11647
t=2017-01-11T00:20:36+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
t=2017-01-11T00:20:46+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=1
^C
root@b69da387027f:/var/log/grafana# ls -la /var/lib/grafana/png/*
ls: cannot access /var/lib/grafana/png/*: No such file or directory
```

**Comment by avinson** [comment] 2017-01-12 20:02
still seeing this on 4.1.1

**Comment by avinson** [comment] 2017-01-13 20:48
this seems identical issue to https://github.com/grafana/grafana/issues/6660 except i am not changing the http_addr:

```
grafana  29448 91.0  1.7 1759920 141624 ?      Rl   20:43   0:00 /usr/share/grafana/vendor/phantomjs/phantomjs --ignore-ssl-errors=true --web-security=false /usr/share/grafana/vendor/phantomjs/render.js url=http://localhost:3000/dashboard-solo/db/avinson?from=1484318624291&to=1484340224291&panelId=3&width=1000&height=500 width=1000 height=500 png=/var/lib/grafana/png/1xEY6W1GaB2zSBSK5Wri.png domain=localhost renderKey=gXpftC2p5KIFp47f4jez1wDQN31QjNIT
```

since the parameters are not properly removed from the URL, it won't work as a cli command:

```
<0 height=500 png=/var/lib/grafana/png/1xEY6W1GaB2zSBSK5Wri.png domain=localhost renderKey=gXpftC2p5KIFp47f4jez1wDQN31QjNIT
[1] 1208
[2] 1209
[3] 1210
[4] 1211
root@29c57a3b55ea:/var/log# url=<url> png=<filename> width=<width> height=<height> renderKey=<key>
```

**Comment by avinson** [comment] 2017-01-13 21:45
actually i guess this is probably exactly the same issue as png renderer does not seem to respect GF_SERVER_DOMAIN or GF_SERVER_ROOT_URL env vars

**Comment by daniellee** [comment] 2017-03-08 13:46
The url for rendering the png looks correct. It should be localhost or http bind address. It will not use `root_url`. Hard to say what the problem is, any other info you can give us that would help troubleshoot this issue?

**Comment by avinson** [comment] 2017-03-08 19:03
@daniellee it seems identical to #6660. I cause the actual CLI call out that was being made:

```
grafana  29448 91.0  1.7 1759920 141624 ?      Rl   20:43   0:00 /usr/share/grafana/vendor/phantomjs/phantomjs --ignore-ssl-errors=true --web-security=false /usr/share/grafana/vendor/phantomjs/render.js url=http://localhost:3000/dashboard-solo/db/avinson?from=1484318624291&to=1484340224291&panelId=3&width=1000&height=500 width=1000 height=500 png=/var/lib/grafana/png/1xEY6W1GaB2zSBSK5Wri.png domain=localhost renderKey=gXpftC2p5KIFp47f4jez1wDQN31QjNIT
```

since the url param is not in quotes, the shell interprets the `&` as a background directive

**Comment by avinson** [comment] 2017-03-08 19:04
i'll try with latest master when i have a chance and see if the behavior is the same

**Comment by avinson** [comment] 2017-03-08 19:08
from #6660:

"It seems like the parsing of the arguments in render.js is reading the url parameters which leads to an error and stops PhantomJS. Replacing the url manually in the PhantomJS command with a url without parameters in it makes it working again."

I agree that these `url` params probably don't need to be there at all since `width=1000 height=500` and other stuff are already being passed as separate args. Why is there a `&width=1000&height=500` part of `url`?

**Comment by daniellee** [comment] 2017-03-11 11:47
Yes, it is probably something to do with PhantomJS. Maybe it is to do with quoting of ampersand characters in the query string. I can't recreate that on Ubuntu but I'll have a look at it.

**Comment by avinson** [comment] 2017-03-15 21:30
here's my environment info if that helps.. traffic is passing through an ELB/haproxy combo before reaching the container:

```
    config {
      image = "grafana/grafana:4.1.1"
      port_map { http = 3000 }
    }
    env {
      GF_AUTH_ANONYMOUS_ENABLED = "true"
      GF_SERVER_DOMAIN   = "elb.aws.company.co"
      GF_SERVER_ROOT_URL = "https://elb.aws.company.co"
      GF_SERVER_ROUTER_LOGGING = "true"
      GF_LOG_LEVEL = "debug"
      GF_LOG_MODE = "console file"
      GF_DATABASE_TYPE = "postgres"
      GF_DATABASE_HOST = "<REDACTED"
      GF_DATABASE_NAME = "grafana"
      GF_DATABASE_USER = "grafana"
      GF_DATABASE_PASSWORD = "<REDACTED>"
      GF_EXTERNAL_IMAGE_STORAGE_PROVIDER = "s3"
      GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET_URL = "http://mybucket.s3-us-west-1.amazonaws.com/"
      # since this key only allows write access to the bucket above, safe to check into git for now. later, move it to vault storage.
      GF_EXTERNAL_IMAGE_STORAGE_S3_ACCESS_KEY = "<REDACTED>"
      GF_EXTERNAL_IMAGE_STORAGE_S3_SECRET_KEY = "<REDACTED>"
      GF_INSTALL_PLUGINS = "grafana-clock-panel,digiapulssi-breadcrumb-panel,mtanda-histogram-panel"
      GF_SESSION_PROVIDER = "postgres"
      GF_SESSION_PROVIDER_CONFIG = "user=grafana password=<REDACTED> host=<REDACTED> dbname=grafana"
```
I will try to reproduce again and post results. Thanks for looking into this.

**Comment by torkelo** [comment] 2017-04-10 13:32
This could be an out of memory issue, we encountered something similar when running Grafana in a docker container with memory constraints below 256mb, phantomjs crashes without any error code or output. 

Closing for now. Reopen if anyone is able to replicate

**Closed by torkelo** 2017-04-10 13:32 UTC
Labels: comp: dashboard/snapshot, type: bug
