### ISSUE TITLE
Snapshot not querying panels out of window's scope

### ISSUE THREAD

**Issue by iOrcohen** [grafana/grafana#31103] opened 2021-02-10 15:34 UTC
**What happened**:
When trying to snapshot a dashboard, panels that are out of window's scope and didn't load data because of the panels data "lazy loading" will appear as empty data panels in the snapshot.

**What you expected to happen**:
All panels will have data in the snapshot.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a snapshot of a dashboard with many panels that are longer then window's scope.
2. open the snapshot and see that bottom's panels or top's panel have no data.

**Anything else we need to know?**:
![Grafanaissue](https://user-images.githubusercontent.com/26905837/107532058-2433c000-6bc6-11eb-8384-020e162836c8.gif)

**Environment**:
- Grafana version: 7.4
- Data source type & version: not relevant
- OS Grafana is installed on: Grafana playground
- User OS & Browser: - Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-02-11 11:02
duplicate of https://github.com/grafana/grafana/issues/30062

**Closed by torkelo** 2021-02-11 11:02 UTC
