### ISSUE TITLE
Loki query dashboard supports adding same label which was already chosen

### ISSUE THREAD

**Issue by SanthoshS20** [grafana/grafana#53409] opened 2022-08-08 14:38 UTC
**What happened**:
The label dropdown list shows the already chosen label in the query field. We can able to choose same label with same value multiple times which is not required.

**What you expected to happen**:
We should remove the labels from the dropdown list which was already chosen. 

**How to reproduce it (as minimally and precisely as possible)**:
**Step 1:** Go the the Loki dashboard.
**Step 2:** Switch to the builder mode.
**Step 3:** In the labels, click the + (PLUS) button to add a new label.
**Step 4:** Choose a label.
**Step 5:** Add another label by clicking the + (PLUS) button.
**Step 6:** Choose the same label which is already chosen.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/37366893/183443387-8dc58307-0c87-40ce-b981-c7242d7b4a00.png)

**Environment**:
- Grafana version: 9.0.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Windows 10 & Chrome Browser
- Grafana plugins:
- Others:

**Comment by usmangt** [comment] 2022-08-11 15:04
Hi @SanthoshS20,

Thanks for reporting this issue.

I understand your description but this sounds like an improvement or maybe a feature request as labels are user-defined (custom) and making them unique will probably need a use case.

I will suggest that you open a feature request for this case as here this is not a bug.

You can use this [link](https://github.com/grafana/grafana/discussions/new) to open your request and then one of the team member will get back to you with more information.

I will now close this case.

**Closed by usmangt** 2022-08-11 15:04 UTC

**Comment by SanthoshS20** [comment] 2022-08-11 15:15
Sure @usmangt. Thank you
