### ISSUE TITLE
When using LDAP user should not be able to update account informations

### ISSUE THREAD

**Issue by ClemPi** [grafana/grafana#6147] opened 2016-09-29 08:01 UTC
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
Grafana v3.1.1 (commit: a4d2708) 
- What datasource are you using?
N/A
- What OS are you running grafana on?
Debian GNU/Linux
- What did you do?
Connected with a LDAP user, updated the username field.
- What was the expected result?
Being rejected.
- What happened instead?
Change was applied in the local DB. 
Next login was impossible with the old user because of `error="UNIQUE constraint failed: user.email"`.
Login with the new login was also impossible because the LDAP is not aware of the login.

**Comment by torkelo** [comment] 2016-09-29 08:14
duplicate of https://github.com/grafana/grafana/issues/2493

**Closed by torkelo** 2016-09-29 08:14 UTC
