### ISSUE TITLE
[Feature request] alerting - state history information

### ISSUE THREAD

**Issue by Boolman** [grafana/grafana#7257] opened 2017-01-13 14:36 UTC
ALERTING feature
A nice-to-have would be some more information on the state history tab, eg:
* result from the query when triggered
* button to zoom to this point
* who was notified, how, and status of the notification

**Comment by bergquist** [comment] 2017-01-17 09:22
Remaning
 * link to when ever an alert was triggerd
 * see who was notified.

**Comment by wei-hai** [comment] 2017-01-17 20:00
it would be better to include the cause of alert, for example, by indicating whether the alert is triggered by condition, timeout or execution error.

**Comment by torkelo** [comment] 2017-06-26 10:00
closing in favor of https://github.com/grafana/grafana/issues/8383

**Closed by torkelo** 2017-06-26 10:00 UTC
Labels: comp: alerting, type: feature request
