### ISSUE TITLE
Grafana 6.4.1 armhf Docker Image does not start

### ISSUE THREAD

**Issue by siegfriedhoellrigl** [grafana/grafana#19709] opened 2019-10-08 15:29 UTC
Raspberry PI (arm 32 Bit System) - Was working perfectly with Version 6.3.6.

docker run -ti --rm grafana/grafana:6.4.1
 gives :
/run.sh: line 80: /usr/share/grafana/bin/grafana-server: No such file or directory

6.4.0 seems to have the same issue.

**Comment by xlson** [comment] 2019-10-08 15:40
Duplicate of #19585

**Closed** 2019-10-08 15:40 UTC
