### ISSUE TITLE
Timezone issues with v.6.6

### ISSUE THREAD

**Issue by junior466** [grafana/grafana#21890] opened 2020-02-02 21:30 UTC
**What happened**:
Timestamps of Elasticsearch now shown in UTC
**What you expected to happen**:
Timestamps show in my browser/local time.
**How to reproduce it (as minimally and precisely as possible)**:
Visualize a query from Elasticsearch
**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.6
- Data source type & version:
Influxdb 1.7.9
- OS Grafana is installed on:
Ubuntu 16.04
- User OS & Browser:
Safari, Firefox, Chrome (All Latest)
- Grafana plugins:

- Others:

After upgrading to the latest version of Grafana, my Elasticsearch queries are now showing timestamps in UTC even though that wasn't the issue before. I am using Graylog and have configured the Timezone to be in my local time but Elasticsearch remains default (UTC).

Here's my post at community board. [Link](https://community.grafana.com/t/timestamp-in-utc-after-v-6-6/25316)

Here's my post at Graylog community board. [Link](https://community.graylog.org/t/timezone-best-practice-grafana-issues/13722)

EDIT
Could be related to [#20812](https://github.com/grafana/grafana/pull/20812)?

**Comment by peterholmberg** [comment] 2020-02-03 10:19
@junior466 I see you linked to a PR that fixed an issue in Explore. Is this when visualizing in Explore or in the Table panel or both?

**Comment by junior466** [comment] 2020-02-03 14:07
Hi @peterholmberg, it's mainly on the Table Panel. To be honest, I can't even get any metrics to show up when using Explore. 

Here's a perfect screen cap of the issue. Notice the correct date on the "Message" field and to the right, the timestamp showing UTC. 

https://imgur.com/PqVkQhh

**Comment by junior466** [comment] 2020-02-10 23:15
Sorry to bump this but any recommendations of anything I should try?

**Comment by junior466** [comment] 2020-02-15 16:35
Just wanted to post an update of my findings. I was instructed by a user on another board (Influxdata) to try and revert to an older version of Grafana to prove my theory. I installed Grafana v6.4.5 and sure enough the issue goes away so It is indeed the latest version causing it.

Graylog showing correct/desired information:
![Screen Shot 2020-02-15 at 11 25 46 AM](https://user-images.githubusercontent.com/22748735/74591582-0baabd00-4fe7-11ea-847b-bbfc7bd8b22b.png)

Latest version of Grafana showing undesired date/timestamp:
![Screen Shot 2020-02-15 at 11 25 36 AM](https://user-images.githubusercontent.com/22748735/74591593-1d8c6000-4fe7-11ea-8a42-be1d46a8fab5.png)

Grafana v6.4.5 with correct/desired information:
![Screen Shot 2020-02-15 at 11 25 56 AM](https://user-images.githubusercontent.com/22748735/74591598-2d0ba900-4fe7-11ea-9973-6b9f8f500a5d.png)

**Comment by torkelo** [comment] 2020-02-15 17:03
@aocenas could it be related to you ES time parsing / formatting PR?

**Comment by aocenas** [comment] 2020-02-15 17:18
@torkelo don't think so. If it shows correct time (what ever timezone) then parsing is fine, this will probably be a presentation problem. As far as I know there is an user preference setting that controls what timezone user want's to see (utc/local) so maybe that is broken? Or that but just for table?

**Comment by aocenas** [comment] 2020-02-15 17:20
@junior466 you mention both Elastic and Influx in your comments, is that just a mistake or does this happen for both?

**Comment by junior466** [comment] 2020-02-15 17:24
A mistake as nothing is actually stored in Influx If I understand correctly. I added Elasticsearch as a datasource and started visualizing logs.

**Comment by torkelo** [comment] 2020-02-15 18:27
Do you get the correct time in dashboard table panel?

**Comment by torkelo** [comment] 2020-02-15 18:27
Just double check that your profile timezone or org timezone is set to Local

**Comment by junior466** [comment] 2020-02-15 18:35
> Do you get the correct time in dashboard table panel?

That is where I actually see the problem.  The screenshots above are from a table panel. Unless I am misunderstanding your question. 

>Just double check that your profile timezone or org timezone is set to Local

I did make sure. I wonder if the issue lies here.

![Screen Shot 2020-02-15 at 1 33 47 PM](https://user-images.githubusercontent.com/22748735/74593300-d35faa80-4ff7-11ea-84ad-4fa6222c0c04.png)

If tried changing it to UTC just to see what would happen and the timestamp jumps +5 actually making things worse.

**Comment by aocenas** [comment] 2020-02-17 16:30
@junior466 so I tried it now with both 6.4.5 and 6.6.1 and both versions seem to work the same, ie showing correct timezone based on the preferences.

Can you post a screenshot of the panel query editor? Also can you post a response data from the browser network panel?

**Comment by junior466** [comment] 2020-02-18 18:32
@aocenas Sorry for the delay. Here's a screenshot of the query:

![Screen Shot 2020-02-18 at 1 28 53 PM](https://user-images.githubusercontent.com/22748735/74766067-ab1fb800-5252-11ea-98ae-b560734ead08.png)

> Also can you post a response data from the browser network panel?

I don't quite follow what that means. I use Firefox. Use the Inspect Element Option? What exactly do you need on this page?

**Comment by aocenas** [comment] 2020-02-20 10:58
I meant something like this:
<img width="839" alt="Screenshot 2020-02-20 at 11 52 18" src="https://user-images.githubusercontent.com/1014802/74927477-f9aa8f00-53d7-11ea-95a1-021bd4147436.png">

This is a network tab in Chrome. Basically just wanted to see how the document and the timestamp is formatted in the response (one document/hit is enough) just to check if this isn't some problem in the format.

Also just to check, I assume you have a Json data table format and then transform on the time field right? Something like this:
<img width="813" alt="Screenshot 2020-02-20 at 11 54 16" src="https://user-images.githubusercontent.com/1014802/74927632-47bf9280-53d8-11ea-88f5-09ecfc071591.png">

**Comment by junior466** [comment] 2020-02-21 00:07
@aocenas Hopefully this is what you need:

> {"search_type":"query_then_fetch","ignore_unavailable":true,"index":"*","max_concurrent_shard_requests":256}
{"size":500,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1582200193818","lte":"1582243393818","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"message:(error OR failed OR fail) NOT message:(\"Server returned error NXDOMAIN\" OR \"Exception in subscribe loop\" OR \"format_graphite: error with uc_get_rate\" OR \"previous self-test completed without error\" OR \"set SCM_CREDENTIALS failed on '/dev/log': Protocol not available\")"}}]}},"sort":{"timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{}}

Here's a [paste](https://hastebin.com/etalinolih.json) for a cleaner look and some screenshots:

![Screen Shot 2020-02-20 at 7 05 56 PM](https://user-images.githubusercontent.com/22748735/74991533-2da3a580-5414-11ea-9c62-381811220d3b.png)
![Screen Shot 2020-02-20 at 6 56 16 PM](https://user-images.githubusercontent.com/22748735/74991536-2ed4d280-5414-11ea-8685-b5f2adf7c84d.png)

**Comment by junior466** [comment] 2020-03-14 22:20
@aocenas I just recreated my entire TIG stack in order to test this again and after adding my Elastisearch datasource, the issue remains. Is there a small chance that the option to change timezone in Grafana is broken on the new version?

**Comment by aocenas** [comment] 2020-03-24 14:20
@junior466 Hey sorry this is taking a bit longer, hard to say where is the problem as I am not able to reproduce so far. In the previous comment you sent a request (so the query sent to the elastic) but can you also share the response, mainly part with the timestamps that are sent from elastic (and are shown wrong in Grafana) to confirm there is not some weird formatting or something like that?

**Comment by junior466** [comment] 2020-03-24 21:36
@aocenas No problem at all. 

> but can you also share the response

I am having a tough time finding the line you need. When I right click and choose "inspect", there's a ton of information there. Any tips for finding this?

**Comment by aocenas** [comment] 2020-03-25 10:32
@junior466 basically there should be something like `hits.hits[0]._source.@timestamp`. The point is to see how the timestamp is sent from Elastic. So in any of the docs `_source` attribute there should be some time field that should contain the time for of that event. Want to check what format it is to see if that may result in the issue you see and why I do not see it locally.

**Comment by junior466** [comment] 2020-03-28 12:20
@aocenas Sorry for the delay in responding but I had a hard time finding this information.

![Screen Shot 2020-03-28 at 8 14 50 AM](https://user-images.githubusercontent.com/22748735/77822800-5cc0cd00-70cc-11ea-86be-34bd974aea32.png)

Here's the message as it displays on Grafana:

![Screen Shot 2020-03-28 at 8 15 05 AM](https://user-images.githubusercontent.com/22748735/77822810-73ffba80-70cc-11ea-8798-008dd11f1bde.png)

**Comment by aocenas** [comment] 2020-04-02 09:52
@junior466 hmm seems like the problem may be with the timestamp format. Your timestamp is lacking any timezone information so I think by default that will be interpreted in local timezone and that may produce the weird behavior you are seeing. Can you try changing the format in Elastic to be standard ISO string for example 2020-03-28T10:31:04.000Z would be proper UTC string for this.

**Comment by junior466** [comment] 2020-04-02 19:24
@aocenas I would love to try that but unfortunately I am not too familiar with Elastic and not sure where to make this change. If you could point me in the right direction would be appreciated.

**Comment by junior466** [comment] 2020-04-02 19:40
@aocenas By the way, my Graylog server is setup to send me email alerts and I noticed that my timestamps are already in the format that you suggest I chance?

`{index=graylog_4, message=t=2020-04-02T15:26:30-0400 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=17 name="Disk Busy alert" error="tsdb.HandleRequest() error time: invalid duration $interval" changing state to=alerting, timestamp=2020-04-02T19:26:30.582Z, fields={process_id=14214, gl2_accounted_message_size=383`

As you can see, my timestamp is `2020-04-02T19:26:30.582Z`. Could it be that it appeared that way when viewing it in Chrome?

**Comment by junior466** [comment] 2020-04-12 19:15
@aocenas So after troubleshooting a little longer, my newly created VM running Grafana logged a couple different messages that may shed some light on the issue. 

![Screen Shot 2020-04-12 at 3 08 34 PM](https://user-images.githubusercontent.com/22748735/79077489-255b3e80-7cd0-11ea-8542-7842adaad1e1.png)

The first message lacks the format that you mentioned in your earlier message so Grafana converts it to the unwanted format but the ones below do have it and are displayed properly. All messages coming from the same machine. 

What do you think?

**Comment by Estrax** [comment] 2020-04-28 12:38
@aocenas looks like it works properly, though treats other timestamp formats as UTC and offsets it to the client-side browser time. Should we investigate it further and possibly think of either displaying any kind of notification that the timestamp has an inappropriate format?

**Comment by aocenas** [comment] 2020-04-28 12:58
@junior466 The timestamps in the last screenshot you posted are all ok. The one with `-0400` means its timezone is minus 4h shifted from UTC. So it is easy to convert and then show in UTC which is what is happening there and that should be the correct behavior in this case. The problem may be with timestamps without any timezone info.

@Estrax So just to confirm if we get a timestamp without timezone what do we assume there? Cause we have to assume some sort of timezone and I suspect we assume local timezone of the browser but I think more sensible would be to assume it is UTC even thought that still may not be correct, it will probably be correct more times than the local one.

**Comment by Estrax** [comment] 2020-04-28 13:17
@aocenas Without timezone we assume it's UTC and in majority of the cases it's more correct than the local/browser one. I'd say it's working properly.
Closing that issue then.

**Closed by Estrax** 2020-04-28 13:17 UTC
Labels: datasource/Elasticsearch

**Comment by Fosten** [comment] 2022-01-12 17:35
This still appears to be an issue in 8.3.  I am experiencing the same results as @junior466.
Browser and server are both EST(-5) but timestamps are showing UTC.
If I set Grafana to UTC then everything is off +10 even worse.
It only seems to pertain to tables, as time series graphs show the correct EST times.
This solution corrected the issue for my filebeats collectors
https://community.grafana.com/t/elasticsearch-timestamp-in-utc-but-grafana-is-interpreting-it-as-est/26912
![grafana-graylog-timestamps-filebeats](https://user-images.githubusercontent.com/1520484/149190864-2d9859f2-eaf5-4b36-a2bd-112f30a898d5.png)
But syslogs from fluentd/gelf are still showing UTC.
![grafana-graylog-timestamps-fluentd](https://user-images.githubusercontent.com/1520484/149190974-e06848a3-1da1-4483-8f25-3b3906b436ba.png)
Any thoughts?

**Comment by junior466** [comment] 2022-01-12 22:18
@Fosten I actually ended up giving up on this issue because as I said above, it started after the update. I did open a thread over at Graylog a while ago and was told that Elasticsearch does save all messages as UTC so I know that the messages have the correct timestamp. Unfortunately I don't have the skills to troubleshoot further.

**Comment by c0herent** [comment] 2022-01-25 17:59
I am running 8.3.4 and experiencing the same issue as @junior466 and @Fosten.  The problem appears to be that Graylog stores timestamps as UTC but does not include time zone info in the timestamp.  Example timestamp below:

"timestamp":"2022-01-20 16:38:50.438"

Based on ISO 8601, when no timestamp information is provided, the time is supposed to be interpreted as local time:

https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

When using Winlogbeat with Graylog, it stores the correct timestamp on the same log entry:

"winlogbeat_@timestamp":"2022-01-20T16:38:50.438Z"

@aocenas @Estrax It appears that some parts of Grafana (like the Time Series panel) interpret not having a time zone as UTC, and other parts (like the Table panel) interpret this as local time.  According to the ISO standard, it is correct to interpret it as local time.

Based on that, it would seem that the main issue is with Graylog.  I created the below post to investigate with them:

https://community.graylog.org/t/default-timestamp-field-does-not-contain-time-zone-information/22470

Thanks!
