### ISSUE TITLE
[Feature request] Postgres Support

### ISSUE THREAD

**Issue by wazery** [grafana/grafana#9431] opened 2017-10-05 09:12 UTC
- What Grafana version are you using?
4.5.2
- What datasource are you using?
SqlDB
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Installed SqlDb plugin
- What was the expected result?
Postgres to be working
- What happened instead?
Cannot connect to the Postgres database, and I want to know if it's currently supported as a data source, or not yet. If it's not I suggest it in this feature request.

**Comment by bergquist** [comment] 2017-10-05 09:23
Closing this since its a dupe of #1542 
Support will be added once https://github.com/grafana/grafana/pull/9209 is merged

**Closed by bergquist** 2017-10-05 09:23 UTC

**Comment by wazery** [comment] 2017-10-05 09:54
@bergquist Thank you so much.
