### ISSUE TITLE
Google Cloud Monitoring: Unable to group by/filter by user metadata labels

### ISSUE THREAD

**Issue by zsrv** [grafana/grafana#81750] opened 2024-02-01 23:53 UTC
### What happened?

I want to group by and filter by Google Cloud Monitoring user metadata labels when I use the Google Cloud Monitoring datasource. I found a discussion about this in #18887 where it was said that a public Cloud Monitoring API that returned the user metadata labels could not be found (is this still the case?), but that we could enter user metadata labels manually. I found the same suggestion in the Grafana documentation [here](https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/query-editor/#metadata-labels).

The problem is that I am not able to do this in Grafana v10.2.2, neither in the Explore page nor when I am editing a dashboard panel. When I type a custom value into the Group By field in the Explore page or when I am editing a dashboard panel, it will disappear when I click or tab out of the field:

![group_by](https://github.com/grafana/grafana/assets/95176387/13eb9239-fce0-4786-928e-c8f45249e09e)

I can add a custom value to the Filter field, but no values are returned:

![filter1](https://github.com/grafana/grafana/assets/95176387/097b096c-48ca-4aa0-9c6d-b4be518a19c8)

![filter2](https://github.com/grafana/grafana/assets/95176387/ac6ee47b-8cb9-4cdf-82df-a26067555740)

A [comment](https://github.com/grafana/grafana/issues/18887#issuecomment-528526695) on #18887 says that this is because the labels must appear in the group-by clause in the Cloud Monitoring API query for us to be able to filter on them.

### What did you expect to happen?

I expected to be able to enter a custom value in the Group By field.

### Did this work before?

The first time I am trying this is on Grafana v10.2.2, but comments on #18887 and #15552 indicate that this used to work.

### How do we reproduce it?

1. Launch a Grafana v10.2.2 instance
2. Add a Google Cloud Monitoring datasource
3. Go to the Explore page in Grafana
4. Select the Google Cloud Monitoring datasource you added
5. Try to enter a custom value (that does not appear in the dropdown) into the "Group by" field

### Environment (with versions)?

Grafana: v10.2.2
OS: Windows 10
Browser: Google Chrome 118

### Grafana platform?

Kubernetes

### Datasource(s)?

Google Cloud Monitoring

**Comment by alyssabull** [comment] 2024-02-27 17:50
Thank you for reporting this issue. I have managed to reproduce this issue and will move this issue to our backlog so our team can determine how to handle this.

**Comment by aangelisc** [comment] 2024-03-21 09:18
Closing this as a duplicate of #75280. We will prioritise and investigate a fix 😊

**Closed by aangelisc** 2024-03-21 09:18 UTC
Labels: datasource/GoogleCloudMonitoring, area/query-editor
