### ISSUE TITLE
Get MySQL data, to make graph ?

### ISSUE THREAD

**Issue by SlodeSoft** [grafana/grafana#5988] opened 2016-09-08 09:15 UTC
* **I'm submitting a ...**
- [x] Question / Support request: 

Please include this information:
- What Grafana version are you using ?
2.5.0
- What OS are you running grafana on ?
Ubuntu

Hi All,

I'm searching to get data from my MySQL database to make graph. Who can help me ?

Thanks in advance ?

**Comment by torkelo** [comment] 2016-09-08 09:21
dupe of https://github.com/grafana/grafana/issues/1542

There is PR, but need some more work. 
https://github.com/grafana/grafana/pull/5364

**Closed by torkelo** 2016-09-08 09:21 UTC

**Comment by SlodeSoft** [comment] 2016-09-08 09:32
thank you :)
