### ISSUE TITLE
v7: support for non-numeric values in stat panel

### ISSUE THREAD

**Issue by w-bazan** [grafana/grafana#24877] opened 2020-05-19 15:37 UTC
**What would you like to be added**:

 

unlike singlestat, which has been deprecated, the stat plugin does not allow to display values other than numeric (e.g. strings, dates). Can you please consider supporting the non-number value in the stat panel?

 

The workaround I tried was using a query (e.g. sql SELECT) return a dummy/arbitrary numeric value and use value-to-text mapping to map it on a an object being a template variable. However using template variables is not supported in the mappings.

 

Last but not least can the panel support background coloring (obviously with a fixed color) even if string is returned by the source?

 

**Why is this needed**:

 

For better presentation of non-numeric values.

**Comment by torkelo** [comment] 2020-05-20 05:55
Duplicate of https://github.com/grafana/grafana/issues/23880

**Closed by torkelo** 2020-05-20 05:55 UTC
