### ISSUE TITLE
Poor/confusing UI when entered wrong password for datasource creation

### ISSUE THREAD

**Issue by Derek-K** [grafana/grafana#24896] opened 2020-05-19 23:57 UTC
**What happened**:
Adding a [InfluxDB] datasource using web GUI with an incorrect user/password, web browser (IE/Chrome) keeps asking for password after clicking "Save & Test".
Entering a valid grafana login UserID/password as one would expected (because it appear from localhost:3000), but it is an endless loop! Hit cancel twice and get an error. 

**What you expected to happen**:
It should not use the web browser password pop up, but instead, take user back to the 'add data source' UI and prompt for correct [InfluxDB] password.

**How to reproduce it (as minimally and precisely as possible)**:
1. Fresh installation of Grafana V7.0 for Windows.
2. Create an InfluxDB datasource, but enter an incorrect InfluxDB password
3. Click "Save & Test". Web browser pop-up will prompt for username/password as if it is for current web session (localhost:3000)
4. It will keep looping until the user hits cancel twice. And receive " Network Error: Unauthorized(401)"

**Anything else we need to know?**:
Takes a while to figure out what causes the endless loop of password prompting from web browser.

**Environment**:
- Grafana version: 7.0
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: Windows 10 Pro version 1909
- User OS & Browser: Windows 10, Chrome & IE
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment] 2020-05-20 06:46
duplicate of https://github.com/grafana/grafana/issues/15050

**Closed by torkelo** 2020-05-20 06:46 UTC
Labels: type/bug
