### ISSUE TITLE
TLS handshake error from x.x.x.x:XXXX: remote error: tls: unknown certificate' error when I am accessing Grafana using Https

### ISSUE THREAD

**Issue by saipavankumarreddy** [grafana/grafana#26798] opened 2020-08-05 10:53 UTC
**What happened**: When we are trying to access grafana using https we got TLS handshake error in /var/log/messages and also in systemctl status of grafana service

**What you expected to happen**: We shouldn't get the above error in/var/log/messages.

**How to reproduce it (as minimally and precisely as possible)**:
1.Install Grafana rpm with https
2. Login to Grafana gui and launch any dashboards
3. We are getting below error in /var/log/messages.
	"TLS handshake error from x.x.x.x:XXXX: remote error: tls: unknown certificate"

**Environment**:
Grafana version: 6.6.2 and 7.1.1
	Data source type & version: n/a
	OS Grafana is installed on: Red Hat Enterprise Linux 7.6
	User OS & Browser: chrome
	Grafana plugins: n/a
	Others: n/a

**Comment by aknuds1** [comment] 2020-08-05 11:01
Please rewrite using our standard issue template.

**Comment by saipavankumarreddy** [comment] 2020-08-10 06:48
@aknuds1  updated the ticket with standard issue template.

**Comment by aknuds1** [comment] 2020-08-10 06:52
Can you please provide more details about how you "Install Grafana rpm with https", enough so that we can reproduce what you're doing?

**Comment by saipavankumarreddy** [comment] 2020-08-10 07:29
We have used the below configuration in grafana.ini for installing Grafana rpm using https. 

[server]
# Protocol (http, https, h2, socket)
protocol = https

# https certs & key file

cert_file: /etc/grafana/ssl/server.crt
cert_key: /etc/grafana/ssl/server.key

After editing the grafana.ini I have restarted the Grafana service.

**Comment by aknuds1** [comment] 2020-08-10 07:53
AFAICT, the error means that your certificate is unrecognized by the client. If I'm correct, it's not a problem with Grafana, but with your certificate. Have you tested it to verify that it's recognized by clients? See f.ex. [this SO question](https://stackoverflow.com/questions/49064937/golang-https-certificate-error-remote-error-tls-unknown-certificate-authority).

Closing the issue for the time being, since I don't think it's a Grafana bug.

**Closed by aknuds1** 2020-08-10 07:53 UTC
Labels: area/backend, needs investigation
