### ISSUE TITLE
chaning dashboard require save changes even no changes has been made

### ISSUE THREAD

**Issue by mojitaleghani** [grafana/grafana#50649] opened 2022-06-13 04:35 UTC
**What happened**:
 Recently Updated Grafana to 8.5.5. I used to create a dashboard links so when I need to switch between dashboards I select them from the link I created. In the new version of Grafana, every time I want to switch between the dashboards, panel require me to save changes even I did not have any changes. So I would discard changes or resave and overwrite dashboard. 

**What you expected to happen**:
  changing dashboard without requiring save when no changes has been made recently. 

**How to reproduce it (as minimally and precisely as possible)**:
Update to Grafana v8.5.5 and switch between dashboards from `dashboard-links`

- Grafana version: v8.5.5
- Data source type & version: every data source I have
- OS Grafana is installed on: Centos
- User OS & Browser: chrome Version 101.0.4951.64 and firefox 101.0.1 (64-bit)

**Comment by gelicia** [comment] 2022-06-13 14:07
@mojitaleghani Can you please try hitting save after one of these prompts, then going into the dashboard version and comparing the versions between the save? I am just trying to find out what change is triggering the prompt to see if this is a duplicate of https://github.com/grafana/grafana/issues/48304 . Thank you!

**Comment by mojitaleghani** [comment] 2022-06-14 03:53
> @mojitaleghani Can you please try hitting save after one of these prompts, then going into the dashboard version and comparing the versions between the save? I am just trying to find out what change is triggering the prompt to see if this is a duplicate of #48304 . Thank you!

Hi @gelicia 
Ofcourse I did try to hit the save botton for once or even twice to check if the requirement solve but every time I close grafana tab on my browser and open it again and switching between dashboards, the save prompt pup up again.

![image](https://user-images.githubusercontent.com/43955725/173489838-dd949253-223a-4daf-9d73-ba928fd081a2.png)


I read the mentioned issue you said, I think my issue is the same. 




Thank you

**Comment by mojitaleghani** [comment] 2022-06-14 13:19
@gelicia 
I found out a mistake I made. there was a graph which I have changed the sort of the results, so when I want to switch the dashboard, I had to save. 
below picture:
![image](https://user-images.githubusercontent.com/43955725/173585488-43fcba2a-e98b-4e0e-81f1-859c6e20c35e.png)

So, I saved All changes I need and saved. changed dashboard and again back to the before dashboard. Scroll down a little and back at the top of the page. Then try to change my dashbaord. Again I was prompt to save the dashboard. 
comparing two last versions 544 & 543
![image](https://user-images.githubusercontent.com/43955725/173585804-5fdcffb4-2c3e-4dcf-bbb8-8a516f0ce2f0.png)

in my mind: :)
(Something that noticed my consider was that I have a dashboard that check some DNS and TLS with blackbox exporter. I think when the sort of the rows of the graph is changed by every refresh, the page think some changes had made and must save them.)

and some more version compares:
![image](https://user-images.githubusercontent.com/43955725/173586799-eb169cb3-71e4-4c88-baf7-979bcd59f65f.png)


Thank you

**Comment by Darth-Bobo** [comment] 2022-06-21 08:01
I'm having the same issue,  as far as I can tell a single comma is being removed when the dashboard loads and always in the same place on this dashboard.

<img width="624" alt="Screenshot 2022-06-21 at 08 59 20" src="https://user-images.githubusercontent.com/50400845/174747890-92c91000-e82f-44f6-8e86-a5771b330cf0.png">

**Comment by JoaoSilvaGrafana** [comment] 2022-06-21 08:19
Hey! Thank you both for raising this, we think this is related to this other issue https://github.com/grafana/grafana/issues/48304 , to which we have submitted a fix that will hopefully make it to 9.0.1. Once 9.0.1 is out I can let you know so you can test to see if you are still getting the same problem 🙂

**Comment by Darth-Bobo** [comment] 2022-06-22 09:41
> Hey! Thank you both for raising this, we think this is related to this other issue #48304 , to which we have submitted a fix that will hopefully make it to 9.0.1. Once 9.0.1 is out I can let you know so you can test to see if you are still getting the same problem 🙂

Just updated our test service to 9.0.1 (14e988bd22) and I'm still seeing the problem.  This is a screenshot taken from a dashboard immediately after going to it, I loaded the page and then hit the save button to be told I'd made five changes.


<img width="621" alt="Screenshot 2022-06-22 at 10 37 35" src="https://user-images.githubusercontent.com/50400845/174997584-29d4751f-3d1e-4e91-b274-34f853296820.png">

**Comment by JoaoSilvaGrafana** [comment] 2022-06-22 10:33
Hey @Darth-Bobo . Can I ask if this happened by you clicking "Save" or did you get an "Unsaved changes" popup when navigating out of the dashboard?

That specific fix only fixes the second case, so users are no longer prompted to save changes when they did not actually change anything. The "Changes" tab shows all the changes that the dashboard has so unfortunately when upgrading to new versions there might be changes, but what we tried to do is to avoid that those changes cause the popup to show.

**Comment by JoaoSilvaGrafana** [comment] 2022-06-22 16:31
That's good you're not seeing the popup, @mojitaleghani let us know when you've checked again if the issue you had is fixed.

Regarding the "Changes" tab, as the tab displays any changes to the dashboard JSON, there is not much we can do especially around major releases when there might be more changes coming through...

**Comment by mnorrsken** [comment] 2022-06-22 22:46
what happens on my panels is that updateGridPos is called causing configRev to increase when I load the page.

**Comment by mnorrsken** [comment] 2022-06-22 22:54
Only seems to happen (in 9.0.1) where I have panels that repeat by variable.

**Comment by JoaoSilvaGrafana** [comment] 2022-06-23 08:14
Ah ok I can see how that happens, you're right the `updateGridPos` is called at the start and if a repeated panel causes something else to move it will see it as the dashboard having changes. I will create an issue describing that and open a fix for it that should go in to 9.0.2 👍

**Comment by mnorrsken** [comment] 2022-07-02 09:03
Working great now for me after 9.0.2 😊

**Comment by mojitaleghani** [comment] 2022-07-04 02:55
hey @JoaoSilvaGrafana 
Sorry for my delay, Refer to other comments, the 9.0.2 version seems to work properly with the mentioned issue. I tried to update to the latest stable version but had some other problems with loading panels and plugins that forced me to revert to the version I was (v8.5.5) 

BTW, thank you.

**Closed** 2022-07-04 09:52 UTC
Labels: area/dashboard/links

**Comment by mojitaleghani** [comment] 2022-07-04 10:21
upgraded the plugins via `grafana-cli` then  grafana code version to v.9.0.2. My issue is  is solved. 
Thank you.
