### ISSUE TITLE
DataFrame: Better handling of fields with same name in transformations 

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#25592] opened 2020-06-15 07:46 UTC
**What happened**:
I wanted to make a panel where i wanted to display the count of multiples values within a single row.
I tested this method with InfluxDB datasource and it was working properly, but it seems something is wrong with ElasticSearch.
With InfluxDB, you can to multiples calculations within the request : count, max, min, ...
These requests are output in the table panel with different name, even if you ask for multiples count like count_1, count_2, etc...

You can then easily aggregate these values with a tranform "Outer Join" and organize these fields to end up with a proper table panel.

With ElasticSearch, you cannot Aggreagate values properly because the data returned by Elasticsearch doesn't separate two queries from each other : the query is just gonna return "Max : 50" for exemple.
If you want to aggregate these two request together, you end up in a result like this :
![image](https://user-images.githubusercontent.com/33425208/84630206-e45bf200-aeeb-11ea-9f27-3f2c500d40bb.png)
Despite having different values if i don't aggregate these values :

Request 1:
![image](https://user-images.githubusercontent.com/33425208/84630269-ffc6fd00-aeeb-11ea-8586-f5a148fb4c69.png)

Request 2:
![image](https://user-images.githubusercontent.com/33425208/84630293-05bcde00-aeec-11ea-9e5e-a28c09009411.png)

The two queries :
![image](https://user-images.githubusercontent.com/33425208/84630327-11a8a000-aeec-11ea-93b7-9dd043a8f51c.png)

**What you expected to happen**:
I expected to see there two count outputed with separate name line Count_1, Count_2

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two query from a Elasticsearch datasource with two count (they need to output two different result). These two request need to have a field in common
2. Aggregate on the field your two queries have in common 
3. Don't forget to remove "Group by: Date Histogram"
4. You can see that the aggregate value doesn't display the result of your queries

**Anything else we need to know?**:
If Grafana would be able to separate these two field with separate name, it would be usefull to aggregate two queries with different name to be able to create clean count for multiples field inside a table panel.
For now, we are stuck with making multiples panels because one of the nicest features from the old panel was the "Time to aggregate" panel option. It was working every time, and now we are stuck at this state with the new Table Panel

**Environment**:
Grafana version: 7.0.3
Data source type & version: ElasticSearch 7.6.1
OS Grafana is installed on: CentOS 1804
User OS & Browser: Edge 83.0.478.37

**Comment by torkelo** [comment] 2020-06-15 08:18
I think the problem is not in the transformations but in the way we display field names, not accounting duplicate field names and adding a number suffix: 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldState.ts#L52 

I think that could fix this but not sure

**Comment by torkelo** [comment] 2020-06-15 08:20
dupe of https://github.com/grafana/grafana/issues/25579

**Closed by torkelo** 2020-06-15 08:20 UTC
Labels: area/dataframe, area/transformations
