### ISSUE TITLE
Interval parsing error for intervals values expressed in days

### ISSUE THREAD

**Issue by incansvl** [grafana/grafana#11431] opened 2018-03-29 09:25 UTC
Grafana: 5.0.3
Grafana host: Windows 7 Pro, 64 bit
MySQL server: Maria DB 10.2, Debian Jessie 64 bit

**Background**
My data source is a MySQL table of network ping tests, collected hourly, covering several years worth of data. 

Table Spec:
```
+-------------+-------------------------------
| Field       | Type
+-------------+-------------------------------
| id          | int(10) unsigned
| source      | enum(<list of source hostnames>)
| target      | enum(<list of ping targets>)
| packet_size | smallint(4)
| start       | datetime
| min         | decimal(5,1)        
| mean        | decimal(5,1)
| max         | decimal(5,1)
| %_lost      | decimal(5,1)
+-------------+--------------------------------
```
Grafana Query Spec:
```
SELECT
  MAX(UNIX_TIMESTAMP(`start`)) as time_sec,
  AVG(`%_lost`) as value,
  '%_lost' as metric
FROM `ping`
WHERE $__timeFilter(`start`)
GROUP BY $__timeGroup(start, $interval)
ORDER BY $__timeGroup(start, $interval) ASC
```

**Issue**
The the default set of values for a variable of type **_interval_** is: 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d

However if I select any of the intervals expressed in days, the Grafana query fails and the display chart is blank.

Looking at the chart specification you can see that Grafana's generation of the SQL query fails for an interval expressed in days such as "7d".

It looks as if the `$__timeGroup()` function can't handle intervals in days. As the default intervals include values in days I interpret this as a bug, but if this is consdered to be `$__timeGroup()` working as designed, then please mark this as an enhancement request.

**Comment by svenklemm** [comment] 2018-03-29 17:55
grafana uses ParseDuration from the go time standard library which only supports up to hour. This is intentional from their side since a day isnt as clearly defined and could be between 23 und 25 hours. 
Since grafana does the timeGroup calculations on unix timestamps we wouldnt have to worry about daylight saving time and could set 1d to 24 hours but would have to implement our own interval parsing.

**Comment by bergquist** [comment] 2018-04-10 13:04
Such implementation could be useful in alerting as well. Should be fairly easy to implement. Should be placed in https://github.com/grafana/grafana/tree/master/pkg/util so alerting can us it as well.

**Comment by VitaliyDemchuk** [comment] 2018-06-20 12:17
I choose interval `auto`, set range `30 days` and I have a bug `error parsing interval 1d`
How can this be remedied?

**Comment by bergquist** [comment] 2018-06-21 09:09
golangs internal parser does not support time units above hours (since days might be 23 or 25 hours depending on daylight saving. So far we have not implemented custom support for days so the solution is to use hours instead. ex 720h == 30d

**Comment by VitaliyDemchuk** [comment] 2018-06-28 07:18
@bergquist thank you. I choose `auto` interval, and Grafana automatically determines `30d`. Tell me where can I change `30d` to `720h` Grafana? In config file Grafana?

**Comment by nheath** [comment] 2018-07-19 19:00
This also affects the Sql Server data source now. We're testing a relatively simple query and looking to use automatic grouping based on `$__interval`, which causes errors at larger time intervals.

```sql
select $__timeGroup(CreateDate, $__interval, 0) as time,
  count(*) as value,
  'value' as series
  from dbo.account
  where $__timeFilter(CreateDate)
  group by $__timeGroup(CreateDate, $__interval, 0)
  order by $__timeGroup(CreateDate, $__interval, 0) asc
```

**Comment by pchinery** [comment] 2018-07-27 11:30
This one is important for us as well (on Postgresql, but as explained by sven, this is a restriction of a go function).

To add some context: We are using Grafana for a bit of BI and we often like to group by week or month. So in our case, it is important that each interval can have a different size (i.e. 30 vs. 31 days), which can't be expressed with a fixed amount of hours and therefore probably requires some thoughts on the implementation (as of today, the unix timestamp is devided by a number of seconds to achieve the grouping, if I'm not mistaken)

**Comment by drusellers** [comment] 2018-08-14 13:38
I am also using grafana for a BI dashboard and need to be able to group data by days. I'm ok if its hrs in the sql, but the dashboard can't pass the right data to the function.

**Comment by StephenG89** [comment] 2018-10-04 11:32
Also having this issue. When my interval is in days (e.g. 30d) my dash fails. I understand its a tricky one since the length of a month in hrs differs. A workaround would be nice that lets a user choose to have interval only in hours, or to set a max interval of 24h

**Comment by klausbadelt** [comment] 2018-10-25 00:55
To clarify the bug and a workaround I use:

### Bug

1. `$__timeGroup(column, $__interval)` can't handle day settings like `1d`
2. But the built-in `$__interval` might calculate day settings, depending on graph zoom, resulting in error `error parsing interval 1d`, and graph not drawn

### Workaround

This workaround worked for me: Create your own variable (for example `$psql_interval`) instead of using `$__interval`. Here's how:

1.  In dashboard settings->variables create variable of type Interval
2. Replace day values with hour equivalents, like `1m,10m,30m,1h,6h,12h,24h,168h,336h,720h`
3. Add Auto Option
<img width="573" alt="variable setting" src="https://user-images.githubusercontent.com/5615403/47469179-672eb700-d7b4-11e8-9f7a-aaa97ea79610.png">

4. Use this variable in your query instead of the built-in `$__interval`, for example
```SQL
SELECT
  $__timeGroupAlias(created_at, $psql_interval),
  count(*)
FROM deliveries
WHERE
  $__timeFilter(created_at)
GROUP BY 1
ORDER BY 1
```

5. Select `auto` for your variable value in the dashboard. It then works like the built-in `$__interval`.

![image](https://user-images.githubusercontent.com/5615403/47469316-33a05c80-d7b5-11e8-9b82-4c725bf75113.png)

Wish I had the time to create a PR to either fix `$____timeGroup()` or `$__interval` calculation... sorry!

**Comment by marefr** [comment] 2018-10-26 07:18
Thanks @klausbadelt there's already a PR open for solving this, #13086

**Comment by pedro-andrade** [comment] 2018-11-05 10:47
Not sure if related, but I've noticed that when using "days" in the "Evaluate every" option of Alerts, the setting is ignored and queries start to be executed continuously. This can potentially affect the backend. If not related, I can file a new issue.

**Comment by klausbadelt** [comment] 2018-11-09 23:03
@scomma that's odd, on my instance 'auto' picks from the values I've given (which doesn't include '1d'). Will look into it.

**Comment by hluaces** [comment] 2019-02-14 22:40
I can confirm that even with a defined `interval` variable whose values do not contain any day interval (`1d`, `2d`, `3d`, etc.) the 'auto' is still picking a `7d` interval. I'm using Grafana v5.4.2 (d812109).

In my case the error is triggered by the `7d` interval when I'm selecting a time range of a year ("_Last 1 year_").

My variable contains only the following values: `10m,30m,1h,2h,5h,8h,24h,48h,72h,168h,720h`.

![image](https://user-images.githubusercontent.com/3204332/52822303-9ba2e780-30b1-11e9-95e4-82d0ba4747a7.png)

**Comment by torkelo** [comment] 2019-02-15 05:48
Yes, auto will take what fits the timerange best with your chosen number of step count

**Comment by dannybombastic** [comment] 2019-02-26 15:53
so sorry, but we have the same problem and we are all ready at 2019 hahah

**Comment by sneak-it** [comment] 2019-04-03 18:07
Klaus' solution works well, however as scomma pointed out, this breaks the 'auto' functionality. Would love to see the PR that resolves this (#13086 ) merged :)

**Comment by chenqingan** [comment] 2019-04-27 14:27
I also have this problem in the Grafana v 6.0.1(0c44a04)

**Comment by d5c0d3** [comment] 2019-05-07 18:03
So here is my work around (for a MySQL data source):

**Dashboard settings:**
1. Create variable of type Interval called $timeRange
2. Auto Option: On
3. Step Count: 20
4. Hide: Variable

![image](https://user-images.githubusercontent.com/6509326/57322122-1bfe4500-7103-11e9-969a-be13fb6345ea.png)

**Query builder:**
1. switch to Edit query
2. replace:

```
SELECT
  $__timeGroupAlias(log_timestamp,$__interval),
```
with 
```
SELECT
   CASE
      WHEN RIGHT("$timeRange", 1) = "m" THEN UNIX_TIMESTAMP(log_timestamp) DIV (CAST(LEFT("$timeRange", LENGTH("$timeRange")-1) AS UNSIGNED) * 60) * (CAST(LEFT("$timeRange", LENGTH("$timeRange")-1) AS UNSIGNED) * 60)
      WHEN RIGHT("$timeRange", 1) = "h" THEN UNIX_TIMESTAMP(log_timestamp) DIV (CAST(LEFT("$timeRange", LENGTH("$timeRange")-1) AS UNSIGNED) * 3600) * (CAST(LEFT("$timeRange", LENGTH("$timeRange")-1) AS UNSIGNED) * 3600)
      WHEN RIGHT("$timeRange", 1) = "d" THEN UNIX_TIMESTAMP(log_timestamp) DIV (CAST(LEFT("$timeRange", LENGTH("$timeRange")-1) AS UNSIGNED) * 86400) * (CAST(LEFT("$timeRange", LENGTH("$timeRange")-1) AS UNSIGNED) * 86400)
      ELSE UNIX_TIMESTAMP(log_timestamp) DIV 600 * 600
   END AS "time",
```
**Result:**
At least in my case it now works also for time ranges >= 1d. 
Selected time range: Last 24 hours -> Bars calculated for 1 hour
![image](https://user-images.githubusercontent.com/6509326/57321771-53b8bd00-7102-11e9-8d41-696ef7c14bba.png)

Selected Time Range: Last 30 days -> Bars calculated for 1 day
![image](https://user-images.githubusercontent.com/6509326/57321735-40a5ed00-7102-11e9-941e-050149c30c62.png)

Selected Time Range: Last 6 months -> Bars calculated for 7 days
![image](https://user-images.githubusercontent.com/6509326/57322072-ff620d00-7102-11e9-9b9b-aaa812358fc2.png)

**Comment by biohazardxxx** [comment] 2019-05-14 14:19
I find it strange that also if I state interval to be 36h I get error:
error parsing interval 1d. Same with 1M results in parsing error 30d. Makes it impossible to use any higher interval than 23h with MySQL data source (probably also others).
So if hours should be used, Grafana need to stop converting it at this place. While IMHO the behavior should be consistent and this function should also eat 1M, 20d, 36h.

**Closed** 2019-05-30 07:58 UTC
Labels: area/backend, area/datasource, datasource/MSSQL, datasource/MySQL, datasource/Postgres, effort/small, help wanted

**Comment by zoechi** [comment] 2020-07-09 09:59
I got this error when 1 set "Relative time" to `2y`. `1y` works fine

**Comment by shouryasimha** [comment] 2020-11-09 19:27
its 2020, I still face the same error when trying to use $__interval . Has anyone got any kind of work around this?

**Comment by hluaces** [comment] 2020-11-09 22:15
@shouryasimha I've opted to create a custom interval variable and use it instead of `$_interval`. It's more useful anyway as you have more control over the time interval that you want which might lead into finding peaks on your metrics that might be hidden otherwise.

**Comment by shouryasimha** [comment] 2020-11-16 19:40
I just updated my Grafana from 6 to grafana Version 7 and seems like this error has been solved. thanks everyone!

**Comment by StephenKing** [comment] 2024-08-20 12:40
I had the same problem. What I did was to use a custom variable (`bin_width` in my case) instead of an interval variable.

I have defined values as 

```
1s : 1, 1m : 60, 1h : 3600, 1d : 86400
```

and then used SQL as

```sql
SELECT
CAST(COUNT(event_id) as decimal) / ${bin_width} as value,
$__timeGroup(event_timestamp, '${bin_width}s')
```
