### ISSUE TITLE
Table panel JSON Data presentation broken after 6.3.6 

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#19563] opened 2019-10-02 09:33 UTC
**What happened**:
After upgrade to the latest stable 6.4 release Table panel stoped presenting ElasticSearch JSON Data. Here is how it looks like now:
![broken2](https://user-images.githubusercontent.com/12551929/66033550-cbe7ab00-e507-11e9-8b6f-d8c1ad2b5da9.png)
**What you expected to happen**:
And here is how it was presented in 6.3.6
![broken](https://user-images.githubusercontent.com/12551929/66033678-081b0b80-e508-11e9-8c34-43fddfe06dd0.png)

**Anything else we need to know?**:
The same also affects latest 6.5 nigtly builds. 

**Environment**:
- Grafana version: 6.4
- Data source type & version: ElasticSarch
- OS Grafana is installed on: CentOS

**Comment by kaiehlig** [comment] 2019-10-02 09:38
+1

**Comment by aocenas** [comment] 2019-10-02 09:41
Seems like this could be a duplicate of https://github.com/grafana/grafana/issues/19531

**Comment by torkelo** [comment] 2019-10-02 11:26
yes

**Closed by torkelo** 2019-10-02 11:26 UTC
Labels: area/panel/table, datasource/Elasticsearch, type/bug
