### ISSUE TITLE
grafana 6.0.1 can't add elasticsearch 7.0.0-beta1 datasource

### ISSUE THREAD

**Issue by DDlanWang** [grafana/grafana#15962] opened 2019-03-13 08:18 UTC
when add elasticsearch 7.0.0-beta1 datasource, get "No Date field named begin found"，but elasticsearch6 is ok

**Comment by torkelo** [comment] 2019-03-13 09:45
dupe of https://github.com/grafana/grafana/issues/15622

**Closed by torkelo** 2019-03-13 09:45 UTC
