### ISSUE TITLE
Spike: Figure out what it would take to use default values for variables with the Query Engine

### ISSUE THREAD

**Issue by timlevett** [grafana/grafana#62395] opened 2022-06-08 21:42 UTC
Product DNA Template Variables: https://docs.google.com/document/d/1QGQXa9EUod1GqqCU5dWEamGTsyEHx_EnuJMBcDznTyo/edit#heading=h.lo4c6e71q7vo

**Comment by natellium** [comment] 2023-08-17 16:35
Duplicate of https://github.com/grafana/grafana/issues/62389

**Closed by natellium** 2023-08-17 16:35 UTC
Labels: type/poc, area/public-dashboards, team/grafana-dashboards, prio/future
