### ISSUE TITLE
Collapse/Expand Repeated Rows removes panels inside

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#16258] opened 2019-03-27 15:23 UTC
**What happened**: Graphs disappear after collapse a row. I've several row repetitions based on a template variable

**What you expected to happen**: Graphs visualization is not affected by collapsing a row

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: zabbix plugin 3.10.1
- OS Grafana is installed on: RedHat
- User OS & Browser: W7 & chrome

**Comment by ru87** [comment] 2019-03-27 15:31
below the sequence.

Row on dashboard load:
![before](https://user-images.githubusercontent.com/4210908/55089209-578e0400-50ad-11e9-8b4e-7e25bff0c4d0.PNG)

Row collapsed:
![2](https://user-images.githubusercontent.com/4210908/55089210-578e0400-50ad-11e9-8cf4-ed6bb9227c15.PNG)

Row expanded:
![3](https://user-images.githubusercontent.com/4210908/55089211-58269a80-50ad-11e9-8fe3-9158b3c70e2c.PNG)

Row re-collapsed:
![4](https://user-images.githubusercontent.com/4210908/55089212-58269a80-50ad-11e9-8c89-d7292b37930d.PNG)

the first four graphs simply disappear and there is no manner of re-catch them. You have to reload the page

**Comment by marefr** [comment] 2019-03-27 16:51
@ru87 Can you give some more context to this? 
* Any errors logged (chrome developer tools/console)? 
* Please attach dashboard json before collapsing the row and dashboard json after expand?

Thanks

**Comment by ru87** [comment] 2019-03-28 11:19
@marefr files attached:

1. chrome console error log
2. dashboard json before/after collapse row in the zip

**additional info:** i experience the problem starting from the second row; the first row collapse/expand works fine. 

[10.20.96.2-1553771666978.log](https://github.com/grafana/grafana/files/3017629/10.20.96.2-1553771666978.log)

[issue.zip](https://github.com/grafana/grafana/files/3017635/issue.zip)

**Comment by marefr** [comment] 2019-03-28 11:20
@ru87 thanks. WIll have a look at them in more detail soon. Quick question, what version of the zabbix plugin are you using?

**Comment by ru87** [comment] 2019-03-28 11:26
@marefr great! we're evaluating Grafana for our company. 

 zabbix plugin v 3.10.1

**Comment by marefr** [comment] 2019-03-29 13:24
@ru87 I have not been able to reproduce this. Have used other datasource than Zabbix because I don't have Zabbix setup. Have asked the author (@alexanderzobnin) of the zabbix plugin to verify the zabbix error logged in console. If this is solely a zabbix bug I will move this issue to the zabbix repo (if I can).

**Comment by ru87** [comment] 2019-04-01 14:26
ok @marefr i'm available if you or @alexanderzobnin need more info or support to this case.

**Comment by torkelo** [comment] 2019-04-16 06:46
Closing this as we have no other reports, and I am also are unable to replicate it (using your dashboard json).

**Comment by ru87** [comment] 2019-04-16 07:29
Hi @torkelo,
have you any policy to close issue? 
I've still the problem...

**Comment by torkelo** [comment] 2019-04-16 07:56
Tried one last time and was now able to replicate it, need to add variable values to your dashboard to the row repeat repeated the first row at least once, and on the second row it happens.

**Comment by ru87** [comment] 2019-04-16 08:31
I've defined five template variables behind this dashboard. 
All are related to zabbix datasource and have regex to filter hosts and their related metrics.

![Capture](https://user-images.githubusercontent.com/4210908/56194253-d8984580-6032-11e9-8f37-ec05d0a3f5f2.PNG)

**Comment by AleRed** [comment] 2020-04-01 08:29
Same issue here when collapsing rows that are repeated by a dashboard variable. Was this resolved?

**Comment by goyalr2008** [comment] 2020-04-07 15:21
I am seeing the same issue. Is there any resolution to this?

**Comment by dprokop** [comment] 2021-03-30 08:52
I've tried reproducing this issue with the following dashboard;

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 356,
  "iteration": 1617093755097,
  "links": [],
  "panels": [
    {
      "collapsed": false,
      "datasource": null,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "panels": [],
      "repeat": "query0",
      "title": "Row title ${query0}",
      "type": "row"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fieldConfig": {
        "defaults": {},
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 8,
        "x": 0,
        "y": 1
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "maxPerRow": 3,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "7.5.0-pre",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "repeat": "query0",
      "repeatDirection": "h",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title ${query0}",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": true,
          "tags": [],
          "text": [
            "a",
            "b",
            "c"
          ],
          "value": [
            "a",
            "b",
            "c"
          ]
        },
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": "query0",
        "multi": true,
        "name": "query0",
        "options": [
          {
            "selected": true,
            "text": "a",
            "value": "a"
          },
          {
            "selected": true,
            "text": "b",
            "value": "b"
          },
          {
            "selected": true,
            "text": "c",
            "value": "c"
          }
        ],
        "query": "a,b,c",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Saving template vars",
  "uid": "pM9UrW_Mz",
  "version": 8
}
```

I've tried that again v6 and v7 - couldn't repro. Closing this for now until we get more reports of this issue happening.

@torkelo do you still have the dashboard you were able to reproduce this issue with?

**Closed by dprokop** 2021-03-30 08:52 UTC
Labels: area/dashboard/templating, needs investigation, type/bug
