### ISSUE TITLE
Unable to set alerts using Azure monitor, when using parameters to pass resource group and Resource name in the query

### ISSUE THREAD

**Issue by deepitpro** [grafana/grafana#15823] opened 2019-03-06 12:53 UTC
We have recently updated grafana to version 6.

We have Azure monitor setup for the dashboard which pulls the data from Azure monitor. however, while configuring alerts (which are supported in V6) its fails with below error.
We are passing RG name and Resource name as a parameter which defined as a variable in the query 

Thank you in advance.

<img width="895" alt="alerts" src="https://user-images.githubusercontent.com/22387865/53882647-e8d50200-403c-11e9-81cc-cbb9b2cef482.PNG">

**Comment by marefr** [comment] 2019-03-06 13:06
Duplicate of #15689

**Closed by marefr** 2019-03-06 13:06 UTC
