### ISSUE TITLE
Alert always show no_data on "Variables query schema (influxdb datasource)"

### ISSUE THREAD

**Issue by efvhi** [grafana/grafana#21281] opened 2019-12-30 06:31 UTC
**What happened**: 
`SELECT sum(total_time)/sum(total_count) FROM "service_stat" WHERE $timeFilter   and ("service_name" =~ /^$services$/)  group by service_name, time(1m)`

`firing:false
state:"no_data"
conditionEvals:"false = false"
timeMs:"1.630ms"`

**What you expected to happen**: 
`alerting or ok or pending`

**How to reproduce it (as minimally and precisely as possible)**:
`retestrule`

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.5.2
- Data source type & version: influxdb
- OS Grafana is installed on: centos
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2019-12-30 10:20
Duplicate of #6557

**Closed by marefr** 2019-12-30 10:20 UTC
