### ISSUE TITLE
Explore/Loki: persist parsed fields toggling across queries refresh

### ISSUE THREAD

**Issue by cippaciong** [grafana/grafana#27593] opened 2020-09-15 10:03 UTC
**What would you like to be added**:
In #26178 @fredr added the feature to toggle one or more parsed fields in Explore, which is *extremely useful* for Loki. The only limitation we are facing right now is that the toggling does not persist across queries refresh, this is particularly painful when using auto-refresh intervals.
It would be nice if we could make the toggling persistent across queries refresh. 

**Why is this needed**:
We often use Explore/Loki with auto refresh to watch live logs when debugging, something like `tail -f`. This is currently hard/impossible because at every refresh we lose the parsed field selection and log lines become really hard to read (we have lots of metadata in the log body).

**Comment by fredr** [comment] 2020-09-16 11:34
I would like it to be persisted in the URL state (in `ExploreUIState` maybe). That would (I think) solve this issue, and it would also be possible to share links with toggled fields. (And it would also be saved to history/starred queries I think).

**Comment by fredr** [comment] 2020-10-05 13:24
Since the ui state was removed from the url in #27753 we can't add it there.
I'll dig into this to see if there is an other way of solving the refresh problem

**Comment by ivanahuckova** [comment] 2020-10-07 11:22
So the problem why selected fields are not persisted when refreshed is because we unmount the log container when running new query/refreshing, as we don’t know what kind of results are we going to receive - what panel is going to showed. And therefore parsed field settings are lost. 

So couple of options we could do, and that I could think of:
- I think that the best option would be to save parsed fields similarly as dedup strategy in redux - therefore when refreshing, it wouldn't reset the parsed fields selection . 
- Another options would be saving it  it in url as custom param, different from `ExploreUIState` that has been removed.
- And I think less ideal option would be moving parsed fields state and functions state it to Explore component.

+cc @aocenas @davkal

**Comment by fredr** [comment] 2020-10-07 12:05
Adding it to the URL would make me happy, since it would then be preserved when pasting links to team members while debugging problems. But it would also result in quite long and "ugly" urls.

**Comment by ivanahuckova** [comment] 2020-10-07 12:43
Maybe this PR will make you happy then https://github.com/grafana/grafana/pull/27409 :)

**Comment by fredr** [comment] 2020-10-07 13:17
> Maybe this PR will make you happy then #27409. slightly_smiling_face When implemented for Explore.

It makes me very happy! :smile:

**Comment by cippaciong** [comment] 2020-12-02 22:57
Hi everyone, a quick update only to say that with the recent LogQL extensions introduced by Loki 2.0, I don't think I will need this feature anymore, at least not when using Loki as data source (don't know if the feature might be useful for other data sources).
Feel free to close the issue if you want 🙂

**Comment by fredr** [comment] 2020-12-04 09:08
I think this is still a good thing to fix, the parsed fields toggling can be quite useful when digging into logs on an ongoing issues. And I would be happy to implement it, but I would like a :+1: from the team first. 

ping @ivanahuckova @aocenas @davkal

**Comment by ivanahuckova** [comment] 2020-12-04 09:43
Definitely! I agree that this is still very useful feature, especially for:
- Non-Loki data sources (Elastic, Influx) 
- For Loki users who might not be so skilled in LogQL2
- For digging into logs without needing to rewrite query

**Comment by fredr** [comment] 2021-02-19 21:04
I was just looking into this (sorry for the long delay), but it seems to have already been fixed? 
We are currently on v7.3.7 and I can't reproduce it there (also tried on master). But I can't see what solved it, could it be that the query refresh changed somehow?

**Comment by ivanahuckova** [comment] 2021-02-22 14:11
Yes, I tested this and found out that it got fixed in 7.3.0-beta2 🎉. Closing the issue.

**Closed by ivanahuckova** 2021-02-22 14:11 UTC
Labels: datasource/Loki, help wanted, type/feature-request
