### ISSUE TITLE
FR: Using sparklines in the tables

### ISSUE THREAD

**Issue by mammuthus** [grafana/grafana#17466] opened 2019-06-06 11:12 UTC
**What would you like to be added**:
Sparklines in the table cells

**Why is this needed**:
If you remember, Tufte used first sparklines as a table cell visualization.
Using sparkline as a cell value is a great apportunity to visualize data.
It can be used as overlay with value data (like singlestat sparkline) or separately.

Rough draft:
![image](https://user-images.githubusercontent.com/1700286/59028727-f3ce4700-8864-11e9-82aa-f3c8ea3a5f0b.png)

**Comment by torkelo** [comment] 2019-06-07 09:21
duplicate of https://github.com/grafana/grafana/issues/3308

**Closed by torkelo** 2019-06-07 09:21 UTC
