### ISSUE TITLE
Dashboard parameters ignores the first item in a custom parameter

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#28787] opened 2020-11-03 14:20 UTC
**What happened**:
I'm using custom variables with repeated rows dashboards are loaded from file.

The customer variable looks like:
```
{
                "allValue": null,
                "class": "template_variable_custom",
                "current": {
                    "text": "All",
                    "value": "$__all"
                },
                "hide": 2,
                "includeAll": true,
                "label": null,
                "multi": true,
                "name": "alternator_latency_ops",
                "options": [
                    {
                        "selected": true,
                        "text": "GetItem",
                        "value": "GetItem"
                    },
                    {
                        "selected": true,
                        "text": "PutItem",
                        "value": "PutItem"
                    },
                    {
                        "selected": true,
                        "text": "UpdateItem",
                        "value": "UpdateItem"
                    },
                    {
                        "selected": true,
                        "text": "DeleteItem",
                        "value": "DeleteItem"
                    }
                ],
                "query": "GetItem,PutItem,UpdateItem,DeleteItem",
                "skipUrlSync": false,
                "type": "custom"
            }
```

As you can see the first line should be `GetItem`, but it's not there
![image](https://user-images.githubusercontent.com/2118079/97994634-28de2080-1dee-11eb-976f-c36fca15afb0.png)

If I edit the dashboard manually (like changing the order of the parameters) it would appear back

**What you expected to happen**:
This is how it should look like:
![image](https://user-images.githubusercontent.com/2118079/97995964-e1589400-1def-11eb-8666-29e465bc2103.png)

**How to reproduce it (as minimally and precisely as possible)**:
It's not minimal but a dashboard that reproduce it:
https://github.com/scylladb/scylla-monitoring/blob/branch-3.5/grafana/build/ver_master/alternator.master.json

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: N/A
- OS Grafana is installed on: Docker
- User OS & Browser: centos 7
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment] 2020-11-05 09:16
Using Grafana v7.3.1 not able to reproduce your problem, see https://play.grafana.org/d/QFRma2hMz/issue-28787-repeat-custom-variables?orgId=1.

I think you may have an error in your dashboard JSON - have you created that manually from the UI? If you save the dashboard when you've re-ordered does that work? I'm going to close this since it feels like a configuration error. But let me know if I misunderstood something.

**Closed by marefr** 2020-11-05 09:16 UTC
