### ISSUE TITLE
Data source authentication information is lost after upgrade

### ISSUE THREAD

**Issue by petersohn** [grafana/grafana#51672] opened 2022-07-01 16:24 UTC
**What happened**:

I upgraded Grafana from 8.5.6 to 9.0.2. After restarting the server, it could not connect to the InfluxDB data source because of authentication error. Resetting the password in the setting solved the problem.

I tried what happens when I restart the server again after resetting the password. In this case, everything works fine.

**What you expected to happen**:

As with all previous upgrades, I expect the server to work without any further setup.

**How to reproduce it (as minimally and precisely as possible)**:

The problem occurred after upgrading from 8.5.6 to 9.0.2.

**Anything else we need to know?**:

Grafana is installed and upgraded through Gentoo's package manager, using the official repo: https://packages.gentoo.org/packages/www-apps/grafana-bin

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: Gentoo Linux
- User OS & Browser: N/A
- Grafana plugins: InfluxDB
- Others:

**Comment by joshhunt** [comment] 2022-07-04 10:24
Hey @petersohn - has this happens to all secrets/credentials, from multiple data sources, or just this one InfluxDB config?

**Comment by petersohn** [comment] 2022-07-04 10:57
I only use this one data source, so I don't know what would have happened to other data sources.

**Comment by joshhunt** [comment] 2022-07-04 15:06
Thanks for reporting, and the additional information. I wasn't able to reproduce this myself directly using default config. Here's the steps I followed:

1. `docker volume create grafana`
2. `docker run --name grafana --rm -p 3000:3000 -v grafana:/var/lib/grafana grafana/grafana-oss:8.5.6`
3. Signed into grafana and set up Influx DB data source
4. Created a panel visualising the query `buckets()`
5. Shut down docker container and run `docker run --name grafana --rm -p 3000:3000 -v grafana:/var/lib/grafana grafana/grafana-oss:8.5.6`
6. Verify the data source is still correctly configured and data is returned from the configured panel.

Which mode and authentication method where you using for InfluxDB?

It would be helpful if we could get an exact reproduction - the above docker commands can be used to create a self-contained environment for reproducing.

**Comment by petersohn** [comment] 2022-07-07 14:23
Unfortunately no. As soon as I reset the password for InfluxDB, the issue got solved. Now I can restart the server without losing my login.

**Comment by KjarTalak** [comment] 2022-11-10 10:25
We have the same issue with our system, which we updated from ver. 8 to ver. 9. Strange is, that it works for some of our Sources but not for all of them.

**Comment by itsfeng** [comment] 2023-03-29 13:24
This broke for us too, when we migrated to 9.x.x 
Maybe the following notes can help someone, stumbling over this issue as well...

Breaking Change has been introduced in 9.0.0-beta-3 (see: https://github.com/grafana/grafana/blob/main/CHANGELOG.md#breaking-changes-8)

We fixed this by encrypting our unencrypted credentials using `grafana-cli` before upgrading to 9.x.x - [link to the docs](https://grafana.com/docs/grafana/latest/cli/#migrate-data-and-encrypt-passwords):
```
grafana-cli --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin data-migration encrypt-datasource-passwords
```

**Comment by thoernle** [comment] 2023-06-02 13:07
I have the same problem. It must be related to the implementation of "jsonSecureData". I tried to set this via the "datasources.yml" but the entry in the database seems to have priority.

If I try to run `grafana-cli admin data-migration encrypt-datasource-passwords` (which should solve that issue) I get the following error:

> INFO [06-02|12:45:36] Starting Grafana                         logger=settings version= commit= branch= compiled=1970-01-01T00:00:00Z
WARN [06-02|12:45:36] "sentry" frontend logging provider is deprecated and will be removed in the next major version. Use "grafana" provider instead. logger=settings
INFO [06-02|12:45:36] Config loaded from                       logger=settings file=/usr/share/grafana/conf/defaults.ini
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_SERVER_ROOT_URL=https://subdomain.example.com"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_SECURITY_ADMIN_USER=admin"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_USERS_ALLOW_SIGN_UP=false"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_AUTH_ANONYMOUS_ENABLED=false"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_METRICS_ENABLED=false"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_RENDERING_SERVER_URL=http://renderer:8081/render"
INFO [06-02|12:45:36] Config overridden from Environment variable logger=settings var="GF_RENDERING_CALLBACK_URL=http://grafana:3000/"
INFO [06-02|12:45:36] Target                                   logger=settings target=[all]
INFO [06-02|12:45:36] Path Home                                logger=settings path=/usr/share/grafana
INFO [06-02|12:45:36] Path Data                                logger=settings path=/var/lib/grafana
INFO [06-02|12:45:36] Path Logs                                logger=settings path=/var/log/grafana
INFO [06-02|12:45:36] Path Plugins                             logger=settings path=/var/lib/grafana/plugins
INFO [06-02|12:45:36] Path Provisioning                        logger=settings path=/etc/grafana/provisioning
INFO [06-02|12:45:36] App mode production                      logger=settings
INFO [06-02|12:45:36] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO [06-02|12:45:36] Starting DB migrations                   logger=migrator
INFO [06-02|12:45:36] migrations completed                     logger=migrator performed=0 skipped=484 duration=1.42767ms
INFO [06-02|12:45:36] Envelope encryption state                logger=secrets enabled=true current provider=secretKey.v1
INFO [06-02|12:45:36] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO [06-02|12:45:36] Starting DB migrations                   logger=migrator
INFO [06-02|12:45:36] migrations completed                     logger=migrator performed=0 skipped=484 duration=2.573375ms
panic: duplicate metrics collector registration attempted
goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x393262a?, {0xc001780690?, 0x1, 0xc0012ee5b0?})
	/opt/drone/gomodcache/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:406 +0x85
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/opt/drone/gomodcache/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:178
github.com/grafana/grafana/pkg/services/sqlstore.ProvideService(0xc0001bc880, 0x411e200?, {0x40dece0?, 0x61df6b8?}, {0x40f3c28?, 0xc00127b488?}, {0x40fd230?, 0xc0012e5d00?})
	/drone/src/pkg/services/sqlstore/sqlstore.go:83 +0x207
github.com/grafana/grafana/pkg/cmd/grafana-cli/commands.runDbCommand.func1(0xc0005f4780)
	/drone/src/pkg/cmd/grafana-cli/commands/commands.go:52 +0x29a
github.com/urfave/cli/v2.(*Command).Run(0x5f90120, 0xc0005f4540)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5c8
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc001082680, 0xc0005f4100)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xc85
github.com/urfave/cli/v2.(*Command).startApp(0x5f90000, 0xc0005f4100)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x713
github.com/urfave/cli/v2.(*Command).Run(0xc00097e320?, 0x1?)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0xaa
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0010824e0, 0xc0003c4040)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xc85
github.com/urfave/cli/v2.(*Command).startApp(0x5f910e0, 0xc0003c4040)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x713
github.com/urfave/cli/v2.(*Command).Run(0xc000cd38c0?, 0xa?)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0xaa
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0010821a0, 0xc000098940)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xc85
github.com/urfave/cli/v2.(*Command).startApp(0xc000cd3560, 0xc000098940)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x713
github.com/urfave/cli/v2.(*Command).Run(0xc0004334a0?, 0x2?)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0xaa
github.com/urfave/cli/v2.(*App).RunContext(0xc001082000, {0x4102d70?, 0xc00005a020}, {0xc0000520a0, 0x5, 0x5})
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb36
github.com/urfave/cli/v2.(*App).Run(...)
	/opt/drone/gomodcache/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/drone/src/pkg/cmd/grafana/main.go:39 +0x27d

**Comment by itsmylife** [comment] 2024-01-21 15:31
I'll close this issue since it was related to https://github.com/grafana/grafana/pull/49987 and there are workarounds shared. If you still experience problems please feel free to open a new issue.

**Closed by itsmylife** 2024-01-21 15:31 UTC
Labels: datasource/InfluxDB, needs investigation
