### ISSUE TITLE
Characters supported in tag values

### ISSUE THREAD

**Issue by qqbb18** [grafana/grafana#15261] opened 2019-02-05 15:25 UTC
### What Grafana version are you using?
    v5.4.3
### What datasource are you using?
    MetricTank
### What OS are you running grafana on?
    macOS

We would like to gain more insight into what printable ASCII characters (32-126) are supported in **tag values** on Grafana/MetricTank.
Currently, our system only directly supports a limited character set: a-zA-Z0-9-_./%, and blocks other characters (or only allows other special characters via encoding them into HEX format).  However, the tag values in the timeseries data into our system might contain substantially more characters than this list.  Therefore we plan to support additional ASCII characters in tag values, given that they will not cause issues to any existing Grafana/MetricTank functionality, such as query, computation, etc.  We have conducted some basic tests on MetricTank and Grafana by putting each character to different positions of a tag value: leading, trailing and somewhere in the middle.  After combining the test results with other limitations, we have an initial proposal for the characters supported by our system, which is listed below:

  0 - 9  allow everywhere in a tag value 
a - z  allow everywhere in a tag value 
A - Z  allow everywhere in a tag value  
  ! # % & - / : < = > @ _ . allow everywhere in a tag value  
 (space) ~  allow only in the middle of a tag value

;  Always block in a tag value because this is not supported by MetricTank
 '  Always block in a tag value because this is causes request error (unexpected character) when used on Grafana
 " $ ( ) * + , ? [ ] \ ^ ` { } |  Always block in a tag value because they might cause ambiguity when used in regex queries

  Please kindly provide suggestions/comments if you feel any of this is not accurate. Moreover, in order to better understand the restrictions on tag values, we would like to confirm with you on the officially supported list of characters. If possible, please provide brief explanations on why a character is not supported. Finally, it is probably worth adding a regression test for this so we can confidently extend the character set that we plan to support in the future. Thanks!

**Comment by torkelo** [comment] 2019-02-07 13:26
The biggest constraints come from how the tag keys & values are split to generate the tags model that is used by the tags filter UI component. 

It uses this regex pattern to extract tag keys & values:  

`const tagPattern = /([^\!=~]+)(\!?=~?)(.*)/;`

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/graphite_query.ts#L232

**Comment by DanCech** [comment] 2019-02-07 18:35
See also https://github.com/graphite-project/graphite-web/issues/2305

**Comment by shalstea** [comment] 2019-05-15 16:40
Graphite tagging key/value requirements:
https://github.com/graphite-project/graphite-web/blob/7149908675664f341c91dcacfff83c55505564fa/docs/tags.rst#carbon

**Comment by shalstea** [comment] 2019-05-20 16:27
Here is our analysis of the regex problems:

The other characters might cause the following issues:

1. **Space** : the space at the end of a tag value is ignored by Grafana, and space does not work well with regex: tagKey = val  or tagKey =~v al
2. ‘~’: this is supported by MT and Grafana, but queries like this confuses Grafana: tagKey = ~val
3. ‘*’: this is supported by MT and Grafana, but queries like this confuses Grafana: tagKey =~ *val   (400 Bad Request) also this is treated as wildcard by Grafana
4. ‘$’: supported by MT and Grafana, but this confuses Grafana (considered as variable?): tagKey =~ $val or tagKey = $val
5. Single quote ‘, not supported by Grafana (query error: “unexpected character”).  
6. ( This confuses Grafana (Request Error: 400 Bad request): tagKey =~ val(
7. )  this confuses Grafana (Request Error: 400 Bad request):  tagKey =~ )
8. + this confuses Grafana (Request Error: 400 Bad request):  tagKey =~ +val
9. , this confuses Grafana (Request Error: 400 Bad request):  tagKey = ,val or tagKey =~ ,val
10. . This works with exact match, but not with regex:  tagKey =~ val.
11. ; not supported by MT
12. ? This confuses Grafana. Exact match is fine. However regex query has problem (Request Error: 404 Bad Request):  tagKey =~ ?val
13. [  this confuses Grafana (Request Error): exact match is fine, but regex has problem: tagKey =~ val[
14. \ this confuses Grafana (Request Error: 400 Bad request):  tagKey =~ val\ (bad request), or empty response for tagKey =~ v\al
15. ^ this confuses Grafana in regex query  tagKey =~ v^al (empty response)
16. | this gives wrong result during regex query  tagKey =~ v|al (this returns extra results that don't match this pattern)
17. Double quote " These give wrong query result: tagKey =~ val” or tagKey = val”

**Comment by replay** [comment] 2019-05-21 19:07
Regarding `1)` (possibly other points too), the issue seems to be the trimming here: https://github.com/grafana/metrictank/blob/master/api/graphite.go#L662

**Comment by replay** [comment] 2019-05-22 01:55
I created a bunch of test metrics according to the points above, so I could test each of them. I tested each of them once by directly querying MT from Grafana, and once by going through a graphite instance in front of MT. I used the following version:
Grafana `6.1.6`
MT: latest master `v0.12.0-6-g7dafad7`
Graphite: latest stable `1.1.4`


2. `~` is prohibited according to: https://github.com/graphite-project/graphite-web/blob/7149908675664f341c91dcacfff83c55505564fa/docs/tags.rst#carbon
3. works when I do `tag=*val` (`=` operator) or when I enter the query like `tag=~\*val` (for regex the `*` needs to be escaped)
4. same as 3. these two queries work: `tag=$val` / `tag=~\$val`
5. can confirm that i get "bad request", will get more details about that
6. same as 3. needs escaping for regex: `tag=(val` / `tag=~\(val`. just for testing i created a series with only `(` as tag value (`tag1=(`), and I was able to query it with both the `=` and `=~` operator
7. same as 3. I created a series with tag `tag1=)))` and queried it like this: `tag1=)))` / `tag1=~\)\)\)`
8. same as 3. I created a series with tag `tag1=+++` and queried it like this `tag1=+++` / `tag1=~\+\+\+`
9. can confirm that i get "bad request", going to get more details about this
10. same as 3, `.` needs to be escaped in regex. I created a series with the tag `tag1=val.` and queried it like this: `tag1=val.` / `tag1=~val\.`
11. `;` is not allowed in tags / tag values
12. same as 3, works when escaped in regex like `tag1=~\?val` or `tag1=?val`
13. same as 3, works when escaped in regex like `tag1=~val\[` or `tag1=val[`
14. same as 3, works when escaped in regex like `tag1=~val\\` or `tag1=val\`
15. same as 3, works when escaped in regex like `tag1=~v\^al` or `tag1=v^al`
16. same as 3, works when escaped in regex like `tag1=~v\|al` or `tag1=v|al`
17. can confirm that there seems to be an issue with this query, will need to investigate more

Note that when entering the `\` in the query editor then the auto-complete can sometimes be a bit strange, I used to just enter the values like f.e. `\^val` and then hit `tab` instead of `enter` and that way it worked

**Comment by replay** [comment] 2019-05-22 15:08
Regarding `9)` (the comma) I confirmed in the debugger that the issue is also due to the query parsing, this splits by `,`: https://github.com/grafana/metrictank/blob/master/api/graphite.go#L660

**Comment by replay** [comment] 2019-05-22 22:23
The issues of points `1)`, `9)`, `17)` should be fixed with this PR: https://github.com/grafana/metrictank/pull/1323/files

**Comment by JONYsnake** [comment] 2020-02-07 15:59
Could you help me with this metric:

**Comment by JONYsnake** [comment] 2020-02-07 16:03
Could you help me with metric:
wmi_service_status{instance="10.0.0.7:9100",name="mssql$microsoft##wid",status="ok"}
mssql$microsoft##wid - is real name of windows service. But i can't use symbol "#" it is not allowed in metrics. How can I get around this?

**Comment by obetomuniz** [comment] 2022-09-19 14:32
We're closing due to the lack of activity. If anyone still has this issue, feel free to reopen and @grafana/observability-metrics will prioritize it

**Closed by obetomuniz** 2022-09-19 14:32 UTC
Labels: type/bug, datasource/Graphite, prio/medium, area/datasource
