### ISSUE TITLE
Grafana not showing date/time/graph

### ISSUE THREAD

**Issue by oparekh** [grafana/grafana#20582] opened 2019-11-22 04:11 UTC
With a clean installation of PRTG, Grafana and PRTG plugin, I'm unable to show the time and graph correctly. The graph is only showing one single day (11/11/2019) correctly.

I was expecting that the graph will continue to run and to show the exact data out of the API which is showing correctly in in the "Query Inspector".

The error can be reproduced with any clean installation of PRTG and Grafana. Furthermore, I also tried on different server or/and different operating systems. No data is showing in time graph.
On an old installation Grafana is only showing 1 day of data even data is coming in.

If I use the table view the date shows "invalid date".

- Grafana version: v6.4.4 (commit: 092e514)
- Data source type & version: 19.4.53.1912
- OS Grafana is installed on: Windows Server 2012 R2 and / or Linux Debian 9
- User OS & Browser: Windows 10 / Windows Server 2012 R2
- Grafana plugins: PRTG for Grafana v4.0.4
- Others:

**Comment by hugohaggmark** [comment] 2019-11-22 04:29
Hi @oparekh if this is a PRTG specific issue I suggest you create an issue in their [repo](https://github.com/neuralfraud/grafana-prtg).
Closing this issue for now. But we can always reopen this issue later if the issue is related to Grafana and not PRTG.

All the best

**Closed by hugohaggmark** 2019-11-22 04:29 UTC

**Comment by oparekh** [comment] 2019-11-22 04:38
Sorry. Why is this an PRTG issue when grafana clearly stops or not showing data correctly?
Please see screenshots:
![Capture_](https://user-images.githubusercontent.com/5029443/69398317-be3eec80-0d24-11ea-90b4-8e375a1999cd.PNG)

![Capture_2](https://user-images.githubusercontent.com/5029443/69398329-c8f98180-0d24-11ea-8ece-cd1f9259ba4b.PNG)

![Capture_4](https://user-images.githubusercontent.com/5029443/69398246-67391780-0d24-11ea-945b-60455d87e7ca.jpg)

**Comment by hugohaggmark** [comment] 2019-11-22 04:55
Do you see any errors in the console for Chrome devtools?

**Comment by oparekh** [comment] 2019-11-22 05:11
There is different data coming in from the APi but not being picked up by Grafana as it is looks like?
![Capture_5](https://user-images.githubusercontent.com/5029443/69399503-58089880-0d29-11ea-99e4-0799089ca807.PNG)

**Comment by hugohaggmark** [comment] 2019-11-22 05:25
This is what I meant by that this is probably an error in the PRTG datasource plugin.

**Comment by oparekh** [comment] 2019-11-22 07:50
Thank you! I used an earlier version of the plugin now and it is working!
