### ISSUE TITLE
[Bug] Where assumes string values (maybe Influx specific?)

### ISSUE THREAD

**Issue by kaithar** [grafana/grafana#8927] opened 2017-07-25 18:31 UTC
- What Grafana version are you using? 4.3.2 (already checked to see if this is mentioned in the 4.4 changelog)
- What datasource are you using? Influx
- What OS are you running grafana on? Linux

So I create a metric query like so:
![grafana - broken where](https://user-images.githubusercontent.com/76736/28587066-bfdd6864-716d-11e7-85c7-4039e7341811.png)

When I look at the actual query the editor has made, it looks like this:
`SELECT "value" FROM "autogen"."stream" WHERE "zone" = '1' AND $timeFilter`

Unfortunately, the zone tag is an integer type and thus that filter never matches.

```
> select count(id) from stream where "zone" = 1 limit 1
name: stream
time    count
----    -----
0       1317763

> select count(id) from stream where "zone" = '1' limit 1
>
```

The bigger problem is that this also applies to ad-hoc template variables which can't be corrected in edit mode.

Any ideas?

**Comment by daniellee** [comment] 2017-07-25 18:45
duplicate of #5489 and #8501

**Closed by daniellee** 2017-07-25 18:45 UTC
Labels: datasource: InfluxDB, type: duplicate

**Comment by kaithar** [comment] 2017-07-25 19:00
dang it, sorry.  I did a search for issues that looked like this and didn't turn them up

**Comment by daniellee** [comment] 2017-07-25 19:02
No worries. This is a very confusing issue I have to say. Not sure what is correct.

> Tag values are strings

https://docs.influxdata.com/influxdb/v1.2/concepts/glossary/#tag-value
