### ISSUE TITLE
postgres: change default query or postpone execution

### ISSUE THREAD

**Issue by ssube** [grafana/grafana#19024] opened 2019-09-11 19:56 UTC
**What would you like to be added**: a config/env option to modify the default query for Postgres data sources or prevent it from running automatically in the Explore and edit views. I don't see one in [the current options](https://grafana.com/docs/features/datasources/postgres/#data-source-options).

**Why is this needed**: the default query looks something like this:

```
SELECT
  $__time(time_column),
  value1
FROM
  metric_table
WHERE
  $__timeFilter(time_column)
```

We have a few TB of data in a couple of Timescale databases, mostly in the `metrics` table, and a query like that will time out due to the lack of `WHERE name =` attempting to pull _all_ our recent metrics (it used to fetch enough data to crash Grafana, before we added statement timeouts).

A way to provide a custom query, either for all postgres data sources or while setting up a single source, would be great since we could provide an illustrative default for folks to work from.

An option to postpone those initial queries until they have been edited, perhaps until the first time the user hits refresh, would also be nice. When a slow query starts running, then a user edits the query, the second (correct) query may return results, then get wiped out by the first query when it finally returns.

**Comment by joeheaton** [comment] 2019-12-20 11:15
This issue occurs when creating a new graph with Postgres, as it doesn't include $__timeFilter(time_column) by default and overloads Grafana. It also occurs when changing the table in the query builder, Grafana blanks out your WHERE's and $__timeFilter() causing the same crash..

The workaround is to keep your time range tiny while modifying graphs.

**Comment by ssube** [comment] 2020-02-28 16:48
We've inadvertently worked around this in a limited fashion, by creating a table `agg_container_cpu` that comes earlier in alphabetical order than the problematic `metrics` tables. Grafana seems to go with the first table it finds, so declaring an empty table with the right name seems like a reliable workaround until the defaults can be configured.

**Comment by aocenas** [comment] 2020-06-24 08:27
@marefr this seems like it could be solved in the datasource itself. Not sure if it makes sense to do it in other place.

**Comment by marefr** [comment] 2020-06-24 16:21
@aocenas maybe two-fold. First, seems like explore is executing the default query when switching to a postgres data source. Second, postgres graphical query editor creates a bad default query. If changing the second wouldn't explore execute it and return an error instead?

**Comment by davkal** [comment] 2020-11-11 10:58
This would need a special hook to figure out if the query is valid (e.g., checking if it's a bogus default query).

**Comment by davkal** [comment] 2020-11-11 11:01
> A way to provide a custom query, either for all postgres data sources or while setting up a single source, would be great since we could provide an illustrative default for folks to work from.

This is a great idea btw.

**Comment by gabor** [comment] 2023-10-23 12:53
hi @ssube , cannot reproduce this anymore in current grafana versions (grafana 10.1.x), now there is no default query sent. closing the issue.

(if it still happens to you on current grafana version, just respond and we can reopen the issue 👍 )

**Closed by gabor** 2023-10-23 12:53 UTC
Labels: type/feature-request, prio/medium, datasource/Postgres, area/explore
