### ISSUE TITLE
Alerting: Continuous 500 errors from ruler API on alerting list view for Prometheus datasource

### ISSUE THREAD

**Issue by fabsrc** [grafana/grafana#41483] opened 2021-11-09 14:54 UTC
**What happened**:

When visiting and staying on the unified alerting list view (/alerting/list), Grafana returns a 500 error response every 15s with the following content:

```json
{"message":"unexpected content type from upstream. expected YAML, got text/html; charset=utf-8"}
```

**What you expected to happen**:

No 500 error response is returned or it is at least not returned continuously (i.e. Grafana does not make any further request to the ruler API if the datasource does not support it).

**How to reproduce it (as minimally and precisely as possible)**:

1. Start Grafana and Prometheus with `docker-compose up` with unified alerting enabled:

```yaml
version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.31.1

  grafana:
    image: grafana/grafana:8.2.3
    ports:
      - 127.0.0.1:3000:3000
    environment:
      GF_UNIFIED_ALERTING_ENABLED: "true"
      GF_ALERTING_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
```

2. Create Prometheus datasource

```sh
curl -X POST http://localhost:3000/api/datasources \
-H 'Content-Type: application/json; charset=utf-8' \
--data-binary @- << EOF
{
  "name":"prometheus",
  "type":"prometheus",
  "url":"http://prometheus:9090",
  "access":"proxy"
}
EOF
```

3.  Go to alert list view: http://localhost:3000/alerting/list and check the dev tools network tab. A 500 error response should appear every 15s.

**Anything else we need to know?**:

I guess the 500 error is expected in the FE: https://github.com/grafana/grafana/blob/6862c7baf8a6f50d1ed571bbdb835b565bf2082c/public/app/features/alerting/unified/api/ruler.ts#L108 However, if the first response already returned a 500 error, indicating that ruler is not supported for this datasource, I think there is no need to make any additional calls to the endpoint.

**Environment**: 
- Grafana version: 8.2.3
- Data source type & version: Prometheus (v2.31.1)
- OS Grafana is installed on: K8s, Docker
- User OS & Browser: MacOS; Mozilla Firefox & Google Chrome
- Grafana plugins: -
- Others: -

**Comment by ashharrison90** [comment] 2021-11-09 15:53
this is reproducible on main as well with the `ngalert` toggle enabled

**Comment by peterholmberg** [comment] 2021-11-10 09:39
Would not categorize this a bug but rather an enhancement to our polling.

**Comment by fabsrc** [comment] 2021-11-10 15:31
> Would not categorize this a bug but rather an enhancement to our polling. We don't want to discontinue polling data sources since they can become "available" again. A 500 doesn't mean it will never respond, just that it is unavailable for the time being.

Good point, but I think in this particular case the 500 error response indicates that the datasource does not support the ruler API, so any additional polling requests are guaranteed to result in a 500 error as well. As far as I can see, there is already a helper function for this case: https://github.com/grafana/grafana/blob/ed030f9c212ed0d276804da0fd6c52fb1ec1634c/public/app/features/alerting/unified/utils/rules.ts#L51-L53

One possible solution to stop polling the ruler API after the first request failed would be to use this helper function here: https://github.com/grafana/grafana/blob/9e996eaca77a98ab70b433a05119e98f7142be90/public/app/features/alerting/unified/state/actions.ts#L148-L150

E.g.

```ts
      if (
        force ||
        (
          !rulerRules[rulesSourceName]?.loading && 
          !isRulerNotSupportedResponse(rulerRules[rulesSourceName] ?? {})
        )
      ) {
        dispatch(fetchRulerRulesAction({ rulesSourceName }));
      }
```

**Comment by IgorOhrimenko** [comment] 2022-01-21 11:40
I think the question should be asked differently, why does the error occur at all?
The API is enabled by default and works:
```
curl http://localhost:9090/api/v1/rules
{"status":"success","data":{"groups":[]}}
curl http://localhost:9090/api/v1/alerts
{"status":"success","data":{"alerts":[]}}
```
But if we look at the http logs, we see two request:
```
[21/Jan/2022:14:26:18 +0300] "GET /api/v1/rules HTTP/1.1" 200 17418 "-" "Grafana/8.3.4"
[21/Jan/2022:14:26:18 +0300] "GET /rules HTTP/1.1" 200 1200 "-" "Grafana/8.3.4"
```
one request successful "Request Completed" for the path "GET /api/v1/rules" and another error "API error" for the "GET /rules HTTP/1.1"
```
grafana_1  | t=2022-01-21T11:26:18+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=172.17.0.1 time_ms=4 size=0 referer=
grafana_1  | t=2022-01-21T11:26:18+0000 lvl=eror msg="API error" logger=context userId=1 orgId=1 uname=admin error="unexpected content type from upstream. expected YAML, got text/html; charset=utf-8" remote_addr=172.17.0.1
grafana_1  | t=2022-01-21T11:26:18+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/ruler/3/api/v1/rules status=500 remote_addr=172.17.0.1 time_ms=11 size=23 referer=http://localhost:3000/alerting/list
```
and error "unexpected content type from upstream. expected YAML, got text/html; charset=utf-8" is absolutaly right, because
```
curl http://localhost:9090/rules
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="./favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><script>const GLOBAL_CONSOLES_LINK=""</script><link rel="manifest" href="./manifest.json" crossorigin="use-credentials"/><title>Prometheus Time Series Collection and Processing Server</title><link href="./static/css/2.cede384b.chunk.css" rel="stylesheet"><link href="./static/css/main.ddf8afd6.chunk.css" rel="stylesheet"></head><body class="bootstrap"><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,l,a=r[0],p=r[1],f=r[2],c=0,s=[];c<a.length;c++)l=a[c],Object.prototype.hasOwnProperty.call(o,l)&&o[l]&&s.push(o[l][0]),o[l]=0;for(n in p)Object.prototype.hasOwnProperty.call(p,n)&&(e[n]=p[n]);for(i&&i(r);s.length;)s.shift()();return u.push.apply(u,f||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,a=1;a<t.length;a++){var p=t[a];0!==o[p]&&(n=!1)}n&&(u.splice(r--,1),e=l(l.s=t[0]))}return e}var n={},o={1:0},u=[];function l(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,l),t.l=!0,t.exports}l.m=e,l.c=n,l.d=function(e,r,t){l.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},l.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},l.t=function(e,r){if(1&r&&(e=l(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(l.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)l.d(t,n,function(r){return e[r]}.bind(null,n));return t},l.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return l.d(r,"a",r),r},l.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},l.p="./";var a=this.webpackJsonpgraph=this.webpackJsonpgraph||[],p=a.push.bind(a);a.push=r,a=a.slice();for(var f=0;f<a.length;f++)r(a[f]);var i=p;t()}([])</script><script src="./static/js/2.f35a0272.chunk.js"></script><script src="./static/js/main.e1fba23f.chunk.js"></script></body></html>
```
endpoint /rules return html, not yaml.

Why is Grafana expecting yaml in the /rules path?

**Comment by pehlert** [comment] 2022-01-28 12:36
We are observing the same issue that @IgorOhrimenko got on a Grafana + Prometheus setup.
It essentially renders unified alerting useless as we cannot get rules from Prometheus.

I checked versions + configuration against a similar setup of our where it is working and cannot find anything suspicious.
Maybe we're missing some configuration option somewhere, but this looks strange and is really hard to debug.

**Comment by fornellas** [comment] 2022-02-03 20:15
+1 affected, Grafana 8.3.4 talking to Prometheus 2.33.1 triggered this error. It was working fine with Grafana 8.3.3 and Prometheus 2.33.1, same configuration, both cases.

When Grafana's `/alerting/list` loads, I can tcpdump and see it attempting Prometheus `/rules` first, thus getting the "this is not a yaml" errror and then hitting `/api/v1/rules`:

```
IP 127.0.0.1.49682 > 127.0.0.1.9090: Flags [P.], seq 694:789, ack 13482, win 3626, options [nop,nop,TS val 145524898 ecr 145513332], length 95
E....G@.@.............#..*h...]~...*.......
......[tGET /rules HTTP/1.1
Host: localhost:9090
User-Agent: Grafana/8.3.4
Accept-Encoding: gzip


IP 127.0.0.1.9090 > 127.0.0.1.49682: Flags [P.], seq 13482:15965, ack 789, win 374, options [nop,nop,TS val 145524899 ecr 145524898], length 2483
E.	...@.@. %........#.....]~.*ha...v.......
........HTTP/1.1 200 OK
Date: Thu, 03 Feb 2022 19:58:45 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked

92b
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="./favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><script>const GLOBAL_CONSOLES_LINK="",GLOBAL_AGENT_MODE="false"</script><link rel="manifest" href="./manifest.json" crossorigin="use-credentials"/><title>Prometheus Time Series Collection and Processing Server</title><link href="./static/css/2.cede384b.chunk.css" rel="stylesheet"><link href="./static/css/main.08acd20b.chunk.css" rel="stylesheet"></head><body class="bootstrap"><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,l,a=r[0],p=r[1],f=r[2],c=0,s=[];c<a.length;c++)l=a[c],Object.prototype.hasOwnProperty.call(o,l)&&o[l]&&s.push(o[l][0]),o[l]=0;for(n in p)Object.prototype.hasOwnProperty.call(p,n)&&(e[n]=p[n]);for(i&&i(r);s.length;)s.shift()();return u.push.apply(u,f||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,a=1;a<t.length;a++){var p=t[a];0!==o[p]&&(n=!1)}n&&(u.splice(r--,1),e=l(l.s=t[0]))}return e}var n={},o={1:0},u=[];function l(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,l),t.l=!0,t.exports}l.m=e,l.c=n,l.d=function(e,r,t){l.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},l.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},l.t=function(e,r){if(1&r&&(e=l(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(l.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)l.d(t,n,function(r){return e[r]}.bind(null,n));return t},l.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return l.d(r,"a",r),r},l.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},l.p="./";var a=this.webpackJsonpgraph=this.webpackJsonpgraph||[],p=a.push.bind(a);a.push=r,a=a.slice();for(var f=0;f<a.length;f++)r(a[f]);var i=p;t()}([])</script><script src="./static/js/2.3cf95cda.chunk.js"></script><script src="./static/js/main.905ffad2.chunk.js"></script></body></html>
0


IP 127.0.0.1.49682 > 127.0.0.1.9090: Flags [.], ack 15965, win 3626, options [nop,nop,TS val 145524899 ecr 145524899], length 0
E..4.H@.@..y..........#..*ha..g1...*.(.....
........
IP 127.0.0.1.49682 > 127.0.0.1.9090: Flags [P.], seq 789:891, ack 15965, win 3626, options [nop,nop,TS val 145524906 ecr 145524899], length 102
E....I@.@.............#..*ha..g1...*.......
........GET /api/v1/rules HTTP/1.1
Host: localhost:9090
User-Agent: Grafana/8.3.4
Accept-Encoding: gzip
```

Despite the annoying UI error from the first bad request:

![image](https://user-images.githubusercontent.com/1386232/152420542-4855cacd-9d27-4dab-a0ed-a554cf228d7a.png)

everything seems to still still work.

**Comment by billabongrob** [comment] 2022-02-08 21:37
Can confirm on Grafana 8.3.4, Prometheus 2.28.1 and others.

**Comment by gillesdemey** [comment] 2022-02-09 13:52
This has been fixed in https://github.com/grafana/grafana/pull/44571 – the error will no longer be reported when the prometheus datasource does not support the rule API.

**Closed by gillesdemey** 2022-02-09 13:52 UTC
Labels: needs investigation, area/frontend, area/alerting/unified

**Comment by devopsusr-tech** [comment] 2022-02-28 11:13
Grafana v8.4.1
Prometheus v2.30.3

Grafana flooded on with following logs:
` lvl=eror msg="unexpected content type from upstream. expected YAML, got text/html; charset=utf-8" error="unexpected content type from upstream. expected YAML, got text/html; charset=utf-8"`

When want to check the alert history, does not display correct:
![image](https://user-images.githubusercontent.com/55841916/155973805-526e782c-eb1c-4345-a759-b165449a837c.png)

Any idea?

**Comment by tanandy** [comment] 2022-04-08 17:55
Grafana v8.4.5
Prometheus v2.34.0

issue is still present

**Comment by fontexD** [comment] 2022-10-31 09:50
issue still persist on latest releases
