### ISSUE TITLE
Dashboard links do not update when variable changes

### ISSUE THREAD

**Issue by gloyka** [grafana/grafana#14624] opened 2018-12-21 13:25 UTC
### What Grafana version are you using?
5.4.2
### What datasource are you using?
any
### What OS are you running grafana on?
Centos 7.6
### What did you do?
Upgrade 5.3.2 to 5.4.2
### What was the expected result?
We use template variables in dashboard links. When variables changes, dashboard links should be changed
### What happened instead?
Dashboard links do not change, until you refresh browser.

**Comment by torkelo** [comment] 2018-12-21 18:55
dupe of https://github.com/grafana/grafana/issues/14493

**Closed by torkelo** 2018-12-21 18:55 UTC
