### ISSUE TITLE
Editor Permissions granted by Teams don't work in Alerts 

### ISSUE THREAD

**Issue by molsza** [grafana/grafana#49568] opened 2022-05-25 08:47 UTC
**What happened**:

Users which are having editor roles given by team to which they are assigned cannot edit the alerts in that folder.

**What you expected to happen**:

User should have editor permissions to both dashboards and alerts from folder to which theirs team has editor permission.

**How to reproduce it (as minimally and precisely as possible)**:
Users has Viewer roles as theirs main role. 
Users are assigned to Team which have Editor role on specific folder/dashboards.
Users can edit the dashboard in that specific folder. OK
Users cannot edit alerts from folder in which theirs Team has Editor role. BUG

**Anything else we need to know?**:

Regression. Works on Grafana 8.4.7.
It is a new unified alerting, not a legacy one.

**Environment**:
- Grafana version: 8.5.3 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by penekk** [comment] 2022-05-25 15:19
Was just about to paste my prepped issue when I saw this one being opened. I also identified this issue a couple of days back.

Additional info:

When a user with permission set described above (Viewer as main role, Editor/Admin role in specific folder) tries creating an alert (they can see the button in panel settings actually) they get redirected to main Grafana page without any exception/error visible to them.

Environment:

- Grafana version: v8.5.2 (90701be19c)

**Comment by yuri-tceretian** [comment] 2022-06-23 16:17
@molsza thanks for reporting! This issue was fixed by https://github.com/grafana/grafana/pull/49270 which is in Grafana 8.5.4. I could not reproduce it in 8.5.4.
Please upgrade and if you are able to reproduce it re-open this issue.

**Closed by yuri-tceretian** 2022-06-23 16:17 UTC
Labels: type/bug, area/alerting, area/frontend
