### ISSUE TITLE
InfluxDB Aggregate functions support in templating

### ISSUE THREAD

**Issue by burdandrei** [grafana/grafana#5289] opened 2016-06-06 12:07 UTC
- [ v ] Feature request
- Grafana version 3.0.3
- datasource InfluxDB
-  OS  Docker =)

![image](https://cloud.githubusercontent.com/assets/2526486/15821344/e1c66a3c-2bf7-11e6-9e74-f3024d7a38b7.png)

I tried to make  a template to graph 5 biggest queues in our resque. Unfortunately Influx TOP() function sends back time series, and Grafana takes time values from first column.
It would be awesome to have column selector cause you cant make ```show tags keys where ``` =(

**Comment by torkelo** [comment] 2016-06-06 13:50
duplicate of https://github.com/grafana/grafana/issues/5013

**Closed by torkelo** 2016-06-06 13:50 UTC
