### ISSUE TITLE
Label filtering does not work when label is called "id"

### ISSUE THREAD

**Issue by 2easy** [grafana/grafana#16970] opened 2019-05-09 04:56 UTC
I am using dockerized version of Grafana v6.1.6.

When using **Explore** with **Prometheus** and filtering metric by label (i've inserted `rate(my_sample_metric{id="}[5m])`) - autocomplete values for **id** label show up, when I click on one of them, dialog disappears and explore is complaining about broken query. In console an error appears: `400 (Bad Request)`, and after that json response also bad request with an error: `invalid parameter 'query': parse error at char 34: unterminated quoted string` for a query `rate(my_sample_metric{id="}[5m])`.

And the second thing that does not work is clicking on values in the table below the graph, nothing happens and in dev console an error appears - **but this unfortunatelly inlcudes all labels, not only "id" one**.

`
Uncaught Error: Need label to add to query.
    at mn (language_utils.ts:9)
    at e.modifyQuery (completer.ts:4)
    at Explore.tsx:163
    at reducers.ts:511
    at Array.map (<anonymous>)
    at mapper (reducers.ts:511)
    at index.ts:1
    at explore (reducers.ts:8)
    at redux.js:445
    at g (redux.js:205)
mn @ language_utils.ts:9
e.modifyQuery @ completer.ts:4
(anonymous) @ Explore.tsx:163
(anonymous) @ reducers.ts:511
mapper @ reducers.ts:511
(anonymous) @ index.ts:1
explore @ reducers.ts:8
(anonymous) @ redux.js:445
g @ redux.js:205
(anonymous) @ index.js:11
dispatch @ redux.js:611
(anonymous) @ actions.ts:353
(anonymous) @ index.js:8
(anonymous) @ redux.js:462
n.onModifyQueries @ Explore.tsx:164
n.onClickLabel @ Explore.tsx:157
onClick @ Table.tsx:31
h.rest.onClick.L.onClick @ index.js:585
(anonymous) @ react-dom.production.min.js:14
f @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
E @ react-dom.production.min.js:17

A @ react-dom.production.min.js:18
T @ react-dom.production.min.js:18
O @ react-dom.production.min.js:21
kn @ react-dom.production.min.js:84
Rs @ react-dom.production.min.js:250
Ne @ react-dom.production.min.js:39
An @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ps @ react-dom.production.min.js:251
Cn @ react-dom.production.min.js:85

`

Tried in Firefox as well as Chrome (I can find versions if needed)

**Comment by marefr** [comment] 2019-05-09 13:25
@2easy are you sure you're not using some extension in firefox/chrome? I had an issue way back similar to this since I was using an extension in Chrome called ProKeys. Cannot reproduce on v6.2-beta1 [here](https://play.grafana.org/explore?left=%5B%22now-6h%22,%22now%22,%22demo.robustperception.io%22,%7B%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D).

Please include Firefox/Chrome versions. Screenshots/animated gifs or movies would be helpful to understand if you have some certain data in Prometheus causing this or not.

**Comment by 2easy** [comment] 2019-05-10 20:43
I've disabled all extensions, Firefox 66.0.5 .

<img width="1280" alt="Screenshot 2019-05-10 at 22 35 25" src="https://user-images.githubusercontent.com/180397/57555576-f5dfdb80-7374-11e9-8971-5afd1aab511f.png">

**Comment by davkal** [comment] 2020-03-05 15:22
I think that was 2 issues: the first was that the click caused a blur event on the field that mistakenly triggered a query, and then general issues with value completion were fixed in #21294.
Both are fixed now.

**Closed by davkal** 2020-03-05 15:22 UTC
Labels: area/explore, datasource/Prometheus, type/bug
