### ISSUE TITLE
Cloudwatch: Log group selector keeps adding groups on Enter

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#24640] opened 2020-05-13 16:08 UTC
0. Explore with Cloudwatch, Logs mode
1. Open the log group selector and select a group in the middle
2. Move cursor one up
3. Hit enter

Result: the dropdown selection was not visible but got added to the log groups.

**Comment by kaydelaney** [comment] 2020-05-18 13:57
Not sure if this is the same issue, but it seems like if you press up when the first option in a Select component is selected, the box containing the list of options doesn't get scrolled to the bottom. Seems like this is an issue with the Select component itself. CC @dprokop ?

**Comment by mchene** [comment] 2020-05-18 15:58
Can't seem to reproduce.  Which browser and build are you experiencing this on?

**Comment by aocenas** [comment] 2020-05-25 12:38
Basically the issue is if you are at the top of the list and hit arrow up, it will loop back to the end of the list without updating the list scroll position. So you do not see what is selected but something is and you can insert it into the field by hitting enter.

**Comment by aocenas** [comment] 2020-07-16 08:26
@dprokop I think this is more of an issue of the select component, should I assign this to your team?

**Closed** 2021-11-22 10:57 UTC
Labels: type/bug, priority/nice-to-have, area/grafana/ui
