### ISSUE TITLE
Color for Labels, Grafana 7.4.1, new Panel Time Series with Multiple Y-axis

### ISSUE THREAD

**Issue by Christof-W** [grafana/grafana#31231] opened 2021-02-15 23:42 UTC
**Graph line color for corresponding Label and Scale**:

**With multi Y-graphs in the panel it would made it easier to visualy connect the graphs with the scala.**

The new panel with the multiple Y-axis are a great impovement to visualize data, very well done Grafana Team!!
Could it made possible to link the color of the graph with the corresponding label and scala? 
![multiaxispanel](https://user-images.githubusercontent.com/76060280/108002070-5ffec900-6fbc-11eb-87be-a8f26ae01b75.jpg)
:
Thanks for your commitments and great work,

**Comment by leeoniya** [comment] 2021-02-15 23:54
this is a dupe of #29932 (plz add thumbs up reaction to that issue) and already on the enhancement list for the new time series panel in #30564

**Closed by leeoniya** 2021-02-15 23:54 UTC
