### ISSUE TITLE
[Feature request] Grafana do not reconnects to mysql backend if connection lost

### ISSUE THREAD

**Issue by deniszh** [grafana/grafana#5523] opened 2016-07-06 09:47 UTC
If you are using MySQL as a backend for Grafana, and e.g. using Consul DNS for managing database failovers, Grafana never reconnects to MySQL even if all connections to MySQL are lost. You need to restart it - then it works.
It will be good to have some (optional) way to make it reconnect to DB, e.g. as some connections pool manager does for Java.

**Comment by bergquist** [comment] 2018-09-05 11:37
I just tried to reproduce this.

1. Started mysql
2. started grafana
3. kill mysql
4. started mysql

and was able to access Grafana without restarting it. Anything I missed?

I'm closing this since the problem probably been fixed in our ORM library some time since this issue was created :) Poke me if you can still repro this and I will open it again.

**Closed by bergquist** 2018-09-05 11:37 UTC
Labels: P3: important, comp: backend/db, help wanted, type: feature request
