### ISSUE TITLE
Bug: "Fill below to" Rendering issue

### ISSUE THREAD

**Issue by hdost** [grafana/grafana#32234] opened 2021-03-22 19:05 UTC
**What happened**:
Render error as seen below.
![image](https://user-images.githubusercontent.com/643846/112043347-da38e500-8b48-11eb-8065-cd3e5c2e25c7.png)
Does get fixed after refreshing using the "Refresh dashboard" button in the Grafana UI.

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/643846/112043688-3a2f8b80-8b49-11eb-9b3f-9f66bee5efd2.png)

**How to reproduce it (as minimally and precisely as possible)**:
Select any oscillating dataseries and then display it with some offset positive and negative to have three series. Middle, above and below.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: Prometheus 2.20
- OS Grafana is installed on: Linux
- User OS & Browser: Fedora Firefox
- Grafana plugins: n/a
- Others: n/a

**Comment by zoltanbedi** [comment] 2021-03-23 16:42
Is this the new time series panel that you see this bug?

**Comment by torkelo** [comment] 2021-03-24 07:00
Fill below to and staircase line has some issues, think they are fixed in new time series panel 

dupe of https://github.com/grafana/grafana/issues/4612

**Closed by torkelo** 2021-03-24 07:00 UTC
Labels: needs more info
