### ISSUE TITLE
Grafana/Open TSDB - Limit on returned items for template variables

### ISSUE THREAD

**Issue by adamantio87** [grafana/grafana#11746] opened 2018-04-27 06:45 UTC
I'm using grafana 5 running on Linux and OpenTSDB 2.2 as a datasource.
I created a template variable of type Query.

Query: metrics(netusage.service.)
Regex:/net.usage.service.(.+)/
Sort: Disabled

It should return a lot of results (thousands) but when I look at the filter in the dashboard it doesn't show the whole list but just a subset. For example it doesn't show XXX. At the same time if I type XXX in the filter it will display it. It seems there is a limit on the items in the list/result returned by the query; it returns just 999 entries. Is there a way to change that (eg. modifying a conf file)? I opened another issue (#8117 - closed now) reporting the same problem but now the problem seems to be related to the grafana 1000 items limit. Is there a way to increase that value? How?

I opened a similar issue in the past #8155 for grafana 4, but the same solution doesn't work on grafana 5.

**Comment by SamuelToh** [comment] 2018-04-27 07:02
I don't think having a drop down list of a few thousand items is usable at all. 

You might want to consider refining your use-case.

**Comment by adamantio87** [comment] 2018-04-27 10:44
The problem is that when I look for a suggestion, let's say "vevia..." it doesn't return anything since the suggestion considers just the first letters (a, b,c, ...)

**Comment by daniellee** [comment] 2018-04-30 09:53
So you have a template variable that has more than 1000 items? I think you should consider adding another template variable and then chaining it your current variable to filter it to get something that is actually usable.  See [here on play.grafana.org](https://play.grafana.org/d/000000063/prometheus-templating?from=now-1h&to=now&orgId=1) for an example with Prometheus (don't have an example for OpenTSDB).

This seems like a duplicate of #8155 (version 4 or 5 is not enough reason to have two issues) so closing. 

This is also something that we will not be fixing - 1000 seems like more than enough as a limit for a dropdown.

**Closed by daniellee** 2018-04-30 09:53 UTC
Labels: comp: dashboard/templating, datasource: OpenTSDB, type: duplicate

**Comment by adamantio87** [comment] 2018-04-30 09:59
I get the point, but is there a way to modify that limit like in grafana 4?

**Comment by daniellee** [comment] 2018-04-30 10:16
@adamantio87  You tried changing [here](https://github.com/grafana/grafana/blob/v5.1.0/public/app/plugins/datasource/opentsdb/datasource.ts#L202) and it didn't work?

**Comment by annettechun** [comment] 2018-08-08 21:09
@daniellee Is there a reason why changing the datasource.ts for opentsdb doesn't have any effect? Even when I delete the entire datasource.ts file it's still able to generate the lookup/suggest queries somehow.

**Comment by Ultraseamus** [comment] 2018-10-23 21:45
I suspect that people here are running into a limit being enforced in the value select dropdown directive:

https://github.com/grafana/grafana/blob/00c0b71f3d71acbe343b99444d3bbd4e07192417/public/app/core/directives/value_select_dropdown.ts#L42

@daniellee I disagree with your statement that 1000 should be more than enough for any use case. If there are performance limitations (or there is some other issue making it more complex), that's a different matter. But with my team those template dropdowns are often used as a way to search through the available dimensions (not by scrolling, but by typing). As soon as you have a dimension with more then 1000 fields, that option is no longer available to you in Grafana.

You either have to do something complex and sloppy like trying to split the dimensions into multiple templates (one for every 1000 results) or build something custom.

**Comment by adamantio87** [comment] 2018-10-27 19:10
I completely agree. This is a serious limitation. I couldn't upgrade since
I wasn't able to modify that limit in grafana 5. I see a lot of people
facing the same issue now and a lot of time has passed...

Il Mar 23 Ott 2018, 23:46 Ultraseamus <notifications@github.com> ha scritto:
