### ISSUE TITLE
Grafana v6-beta2: worldmap panel is broken

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#15406] opened 2019-02-13 07:04 UTC
### What Grafana version are you using?
6.0.0-beta2

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu 18.04 in Docker

### What did you do?
Load a dashboard that makes use of the worldmap panel

### What was the expected result?
For the data to be displayed

### What happened instead?
Data on the map isn't displayed, and the panel is cropped somehow. If I click into the map the data is loaded and clicking back to go to the main dashboard now everything works.

This worked in Grafana 6 beta1 but is broken in beta2.

One extra curiosity, if the dashboard is set to auto-refresh the map will fully load once it refreshes and displays correctly. If you then use the browser refresh it's back to being broken until the auto refresh interval.

![screenshot from 2019-02-13 07-59-41](https://user-images.githubusercontent.com/569574/52693016-79985080-2f5d-11e9-8478-54db70141657.png)

**Comment by torkelo** [comment] 2019-02-13 13:22
been troubleshooting this, can't find anything wrong in Grafana. The height is set correctly everywhere. Some timing related issue maybe.

**Comment by daenney** [comment] 2019-02-13 13:48
But you can reproduce it?

I'm curious as what could've changed between beta1 and beta2 to trigger this. It worked as expected in beta1.

**Comment by daniellee** [comment] 2019-02-21 14:43
@daenney I could reproduce it. I have no idea which change caused this - something to do with the rendering and the migration from Angular to React. The plugin is written in Angular but more and more of Grafana is being converted to React.

I released a new version of Worldmap (0.2.0) that just does a setTimeout for 1ms when rendering the map and that seems to be enough to fix the rendering issue.

Closing the issue but let me know if this fix works for you or not and thanks for reporting it!

**Closed by daniellee** 2019-02-21 14:43 UTC
Labels: type: bug

**Comment by patrickliangli** [comment] 2019-06-19 02:28
This issue still seems to happen from time to time.

**Comment by patrickliangli** [comment] 2019-06-20 20:59
With further testing, 0.2.0 works well with Grafana 6.2.x, but not with the latest 6.3-pre.

**Comment by adriankuzniewski** [comment] 2019-08-08 09:47
Yup - seems like in version 6.3.2 still problem. 
I can see that problem on load page, when you go to edit panel and exit - all points there until new refresh of whole page.

**Comment by amotl** [comment] 2019-08-08 21:50
Hi there,

we tried hard to mitigate any timing problems we experienced with the combination of Grafana and Worldmap within [1,2].

The most recent release of the upcoming Worldmap Panel designated to be mainlined can be installed side by side through:
```
grafana-cli \
  --pluginUrl https://github.com/hiveeyes/grafana-worldmap-panel/releases/download/0.4.0/grafana-worldmap-panel-ng-0.4.0.zip \
  plugins install grafana-worldmap-panel-ng
```

Please be aware that while we believe it should work pretty well for most people, it is officially considered to be beta quality, so you should know what you are doing when running this guy in production.

Saying this, we will be happy about any feedback in order to work on any remaining issues experienced by users from the community.

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/grafana-worldmap-panel
[2] https://community.grafana.com/t/giving-the-grafana-worldmap-panel-some-love/17210

**Comment by adriankuzniewski** [comment] 2019-08-09 09:42
Hi there, 
I tried to clear cache - restart whole server, incognito, and can confirm that still not working
When i get to edit mode and then exit to normal view - it populates points.

**Comment by amotl** [comment] 2019-08-09 11:56
Dear Adrian,

thanks for letting us know. Bummer, your observations seem to match @rfrost's, see also https://github.com/grafana/worldmap-panel/issues/212#issuecomment-519710670.

We will try to catch some time to look into this.

With kind regards,
Andreas.

**Comment by adriankuzniewski** [comment] 2019-08-09 12:43
Hi Andreas
Yes i can confirm that this was working on version 6.2.x
I did update to see if some flux functionalities will be fixed or not - but seems that's not be the case - so i will reverse back to 6.2.x 

Cheers, 
Adrian.
