### ISSUE TITLE
[Bug] Table with elasticsearch, group by terms and multiple same type metrics not working

### ISSUE THREAD

**Issue by champtar** [grafana/grafana#7477] opened 2017-02-07 01:16 UTC
Hi,

Using Grafana 4.1.1 + elasticsearch datasources, I'm unable to created a simple table with 3 columns:
1 group by and 2 metric of the same type (average in this exemple)

As you can see on this screenshot, the average is not uniquely named by grafana
![grafana-bug1](https://cloud.githubusercontent.com/assets/3536755/22673120/0c02e5ae-ec8d-11e6-8f56-5727bed08698.png)
And we only see the last average metric (response_time)

Panel Json
```
{
  "id": 1,
  "title": "Panel Title",
  "span": 12,
  "type": "table",
  "targets": [
    {
      "metrics": [
        {
          "type": "avg",
          "id": "1",
          "field": "response_size",
          "settings": {},
          "meta": {}
        },
        {
          "type": "avg",
          "field": "response_time",
          "id": "3",
          "settings": {},
          "meta": {}
        }
      ],
      "dsType": "elasticsearch",
      "bucketAggs": [
        {
          "type": "terms",
          "id": "2",
          "settings": {
            "order": "asc",
            "size": "10",
            "orderBy": "_term"
          },
          "field": "hub"
        }
      ],
      "timeField": "@timestamp",
      "refId": "A",
      "hide": false
    }
  ],
  "styles": [
    {
      "type": "date",
      "pattern": "Time",
      "dateFormat": "YYYY-MM-DD HH:mm:ss"
    },
    {
      "unit": "short",
      "type": "number",
      "decimals": 2,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "colorMode": null,
      "pattern": "/.*/",
      "thresholds": []
    }
  ],
  "transform": "json",
  "pageSize": null,
  "showHeader": true,
  "columns": [],
  "scroll": true,
  "fontSize": "100%",
  "sort": {
    "col": 0,
    "desc": true
  },
  "links": []
}
```

Elasticsearch query:
```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["access-logs-2017.01.06","access-logs-2017.01.07"]}
{"size":0,"query":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1483717645059","lte":"1483783396557","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"2":{"terms":{"field":"hub","size":10,"order":{"_term":"asc"}},"aggs":{"1":{"avg":{"field":"response_size"}},"3":{"avg":{"field":"response_time"}}}}}}
```

Elasticsearch response is ok (200 and it contains both aggs)
```
{"responses":[{"took":2,"timed_out":false,"_shards":{"total":8,"successful":8,"failed":0},"hits":{"total":3086558,"max_score":0.0,"hits":[]},"aggregations":{"2":{"doc_count_error_upper_bound":0,"sum_other_doc_count":2705453,"buckets":[{"key":"ACC","doc_count":195,"1":{"value":291558.3692307692},"3":{"value":0.1189664303222507}},...]}},"status":200}]}
```

Thanks
Etienne

**Comment by torkelo** [comment] 2017-02-07 06:42
duplicate of this feature request, https://github.com/grafana/grafana/issues/4709

**Closed by torkelo** 2017-02-07 06:42 UTC
