### ISSUE TITLE
upgrading from Graph(old) to Time series deletes the alerting 

### ISSUE THREAD

**Issue by yarix** [grafana/grafana#36541] opened 2021-07-08 07:53 UTC
**What happened**:
Grafna alerts defined on "Graph(old)" are deleted once switching to new panel "Time series"
**What you expected to happen**:
alerts should stay, like that the query.
**How to reproduce it (as minimally and precisely as possible)**:
create graph(old) panel, add alerts, save
change the visualization to Time series, see that the alerts are gone.
**Anything else we need to know?**:

**Environment**:
- Grafana version:  v8.0.4
- Data source type & version: prometheus
- OS Grafana is installed on: grafana cloud
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-07-08 09:06
dupe of https://github.com/grafana/grafana/issues/36106 

fix coming in v8.0.5 (releasing today)

**Closed by torkelo** 2021-07-08 09:06 UTC
