### ISSUE TITLE
Using "data rates" y axis visualization with stackdriver source is not possible

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#15582] opened 2019-02-21 16:09 UTC
Please include this information:
### What Grafana version are you using?
Grafana 6.0 beta-1

### What datasource are you using?

Stackdriver 

### What OS are you running grafana on?
Official Docker

### What did you do?
I am trying to visualize a disk's volume throughput of a google cloud disk. Therefore I am using stackdriver to get it's metrics which works fine. However I can not choose a different unit for my Y axis than "Bytes". Instead of "Bytes" I want to get "Bytes / seconds" as this is the appropriate unit for the values I get from stackdriver.

Whenever I choose "Bytes/Second" from the dropdown, the dropdown disappears (as expected after clicking an item) but it still has "bytes" selected and the whole graphs shows Bytes instead of bytes / seconds.

### What was the expected result?

When I choose Bytes / second it would update the graph so that all the y metrics are rate metrics too.

### What happened instead?

The dropdown disappeared and still had "bytes" logged in.

### If related to metric query / data viz:

RAW query:

```
aggregation.alignmentPeriod=+60s&aggregation.crossSeriesReducer=REDUCE_NONE&aggregation.groupByFields=metric.label.instance_name&aggregation.perSeriesAligner=ALIGN_DELTA&filter=metric.type="compute.googleapis.com/instance/disk/write_bytes_count"+metric.label.instance_name=monitoring.regex.full_match("gke-kafka.*")&interval.endTime=2019-02-21T16:02:06Z&interval.startTime=2019-02-21T13:02:06Z&view=FULL
```

**Comment by torkelo** [comment] 2019-02-22 08:09
duplicate of this issue, https://github.com/grafana/grafana/issues/13733

**Closed by torkelo** 2019-02-22 08:09 UTC
