### ISSUE TITLE
ButtonCascader has a bit of a lag after selection

### ISSUE THREAD

**Issue by shavonn** [grafana/grafana#23756] opened 2020-04-21 19:56 UTC
When I make a selection from the cascader menu, it takes a few seconds before the onChange is triggered. Should look into what is causing this.

**Comment by marefr** [comment] 2020-04-24 10:01
Please add labels to issue. Are you looking into this or expecting someone else to do it? If someone else, please let me know and I try to delegate it to team. Any screenshots/animated gif showing the problem.

**Comment by shavonn** [comment] 2020-04-28 17:57
> Please add labels to issue. Are you looking into this or expecting someone else to do it? If someone else, please let me know and I try to delegate it to team. Any screenshots/animated gif showing the problem.

@marefr I discussed it with @tskarhed and he said hopefully it would make it into 7 but didn't indicate who or how.

**Comment by torkelo** [comment] 2020-04-29 04:26
Never seren this, sounds very strange. Don’t get this when I use it

**Comment by hugohaggmark** [comment] 2020-05-04 07:22
@tskarhed were you able to repro this one, otherwise I think we should close this.

**Comment by tskarhed** [comment] 2020-05-04 08:08
I'm not able to reproduce it. @shavonn do you have an example on how to reproduce or a short video?

**Comment by hugohaggmark** [comment] 2020-05-04 08:20
Closing this for now, if @shavonn can add a video or repro steps we could opened this again.

**Closed by hugohaggmark** 2020-05-04 08:20 UTC
Labels: area/frontend, area/grafana/ui, needs investigation, type/bug
