### ISSUE TITLE
Graph with one data point use 100% width

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#25601] opened 2020-06-15 14:06 UTC
**What happened**:
![image](https://user-images.githubusercontent.com/5497623/84665697-6ebe4900-af20-11ea-886e-ca3b3e1c84c4.png)

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/5497623/84665733-7aaa0b00-af20-11ea-9f63-02140e4ab973.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. create new dashboard
2. new panel -> graph
3. ensure your query return only **one result**
4. panel > display -> bars ON / lines OFF / points OFF

**Anything else we need to know?**:
If you have a group by, you can "fix" the bar by setting a "serie overrides" -> bars true

![image](https://user-images.githubusercontent.com/5497623/84667013-1425ec80-af22-11ea-897b-e183076c73f3.png)
![image](https://user-images.githubusercontent.com/5497623/84667051-2011ae80-af22-11ea-9f83-57bbc6ca68d7.png)

I'm not sure it's happens only with one data point, but this way I can reproduce 

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: stackdriver 
- OS Grafana is installed on: I use the grafana image from docker hub
- User OS & Browser: MacOS / Chrome 83

**Comment by torkelo** [comment] 2020-06-15 15:13
duplicate of https://github.com/grafana/grafana/issues/14130

**Closed by torkelo** 2020-06-15 15:13 UTC
Labels: datasource/Stackdriver, needs investigation
