### ISSUE TITLE
Publish X.Y container image

### ISSUE THREAD

**Issue by rrey** [grafana/grafana#22388] opened 2020-02-22 23:41 UTC
**What would you like to be added**:
(Hello !)
We started an effort around Grafana automation with [Ansible through a Collection](https://github.com/ansible-collections/grafana).
I am currently working on the CI setup for running tests against several versions of Grafana.

I noticed that there are no container image on dockerhub that only specify the MAJOR.MINOR version that always point to the latest patch of the version (at this moment `6.6` would be the same image as `6.6.2`).

I am wondering if it is something that you would be opened to do ?

**Why is this needed**:
On my side, it would help me have a stable CI configuration that I wouldn't have to change every time you release a bug fix.
This is a selfish request :)

**Comment by papagian** [comment] 2020-02-23 19:17
Duplicate of #16193

**Closed by papagian** 2020-02-23 19:17 UTC
Labels: area/docker, priority/nice-to-have, type/duplicate, type/feature-request
