### ISSUE TITLE
[Feature request] Alert Notifier / Notification: allow templating in message / tags

### ISSUE THREAD

**Issue by desaintmartin** [grafana/grafana#28756] opened 2020-11-02 15:56 UTC
**What would you like to be added**:

Allow templating in alert notification so that we can customize message and tags. In this case, something like:
<img width="606" alt="Screenshot 2020-11-02 at 16 53 01" src="https://user-images.githubusercontent.com/38929/97888885-f4a22b80-1d2b-11eb-9832-4be1078d7324.png">
would be translated as `This is an alert from my-great-service with value 1337`, and tag `service` would be `my-great-service`, assuming such labels exist in the metric.

**Why is this needed**:

In order to support alerting in complex environments.

**Comment by desaintmartin** [comment] 2020-11-02 16:05
This may be somehow related to:
- https://github.com/grafana/grafana/issues/5848 (in comments)
- https://github.com/grafana/grafana/issues/15079
- https://github.com/grafana/grafana/issues/25808
- https://github.com/grafana/grafana/issues/7121

**Comment by marefr** [comment] 2020-11-05 20:04
Thanks, but I'll close this as a duplicate. Please try to express your related feature request in any of the referenced issues. 

/duplicate of #5848

**Closed** 2020-11-05 20:04 UTC
