### ISSUE TITLE
Auth: signout_redirect_url Should be treated differently for auth providers.

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#21196] opened 2019-12-19 14:50 UTC
**What happened**:

When using mixed authentication ( Example : Simple authentication + OAuth Authentication ) along witht the `signout_redirect_url` specified for OAuth, user logged in with simple authentication should be redirected to grafana logout page instead of `signout_redirect_url`  . Issue https://github.com/grafana/grafana/issues/14160 have more details.

**How to reproduce it**:

* Configure OAuth Configuration along with basic form based [auth]
* Configure signout_redirect_url in `[auth]` section.
* Login with admin user / any user with simple authentication ( username & password )
* Logout and user will be redirected to url specified in `signout_redirect_url`  instead grafana login page.

**Environment**:
- Grafana version: 6 plus

**Comment by pkolyvas** [comment] 2021-07-29 00:24
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Closed by pkolyvas** 2021-07-29 00:24 UTC
Labels: area/backend, area/backend/auth, help wanted, priority/unscheduled, type/feature-request

**Comment by felixmarch** [comment] 2023-06-13 14:55
@yesoreyeram I cannot reproduce this issue in current grafana version. 

I am using grafana v9.5.2 with keycloak oauth and `signout_redirect_url = https://#{my_keycloak_url}/auth/realms/#{mykeycloak_realm}/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2F#{my_grafana_url}%2Fgrafana%2Flogin`. 

If I sign in to grafana using keycloak auth, I am able to see keycloak logout page when I try to logout from grafana.

However, when I sign in to grafana with basic authentication, I do not see keycloak logout page when I try to logout, in which this behavior should be correct and expected.

In issue #14160, I saw you were highlighting LDAP and OAuth. 

You may want to try current latest grafana version if you are still seeing same issue with ldap and oauth?
