### ISSUE TITLE
Value Mapping with Regex not working in Tables

### ISSUE THREAD

**Issue by pixelhomie** [grafana/grafana#42302] opened 2021-11-25 14:38 UTC
**What happened**:
Regarding the [Docs](https://grafana.com/docs/grafana/latest/panels/value-mappings/#table-example) i tried to highlight a table row with a green background when it contains the word "MESSAGE". Unfortunately this is not working because every row will be highlighted. I verified my Regex with [Regex101](https://regex101.com/r/3F3vqp/1)
Am i something missing or is this Feature broken?

![ksnip_20211125-151916](https://user-images.githubusercontent.com/10769674/143458766-89f2d995-f7f6-4084-a135-bc790d0c3976.png)
![ksnip_20211125-151948](https://user-images.githubusercontent.com/10769674/143458771-81198b64-b24c-4f48-8ed3-ff80f9f03e6a.png)

**What you expected to happen**:
Only Rows containing the word "MESSAGE" should be highlighted

**How to reproduce it (as minimally and precisely as possible)**:
See Screenshot / Regex101

**Anything else we need to know?**:
-

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: InfluxDB 2.1.1
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment] 2021-11-25 15:02
duplicate of https://github.com/grafana/grafana/issues/41265 

fix coming in v8.3

**Closed by torkelo** 2021-11-25 15:02 UTC
