### ISSUE TITLE
Grafana randomly logs out

### ISSUE THREAD

**Issue by petersohn** [grafana/grafana#23233] opened 2020-03-31 16:32 UTC
**What happened**:

I occasionally get logged out of Grafana. I am logged in as the admin user, and after some time, I get logged out. The actual amount of time varies.

**What you expected to happen**:

The login session should be alive until the token expires.

**How to reproduce it (as minimally and precisely as possible)**:

Log in and keep a tab with several queries open with automatic refresh turned on.

**Anything else we need to know?**:

I looked at my user page and it says that all of the sessions that I've created are active. Then I checked opened the browser's network debugger. Normally, each time an update happens, it makes a lot of queries to the server, and each query returns with 200 status code. However, ocassionally, some of the queries return 401. I checked the server logs, and these logs appear this time:

```
lvl=eror msg="Failed to look up user based on cookie" logger=context error="database is locked"
```

There are several of these log messages too:

```
lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/query status=401 remote_addr=xxx.xxx.xxx.xxx time_ms=5032 size=26 referer="https://xxxxxxxxxx"
```

After that, there is a logout log.

```
t=2020-03-31T15:42:33+0000 lvl=info msg="Successful Logout" logger=http.server User=
t=2020-03-31T15:42:33+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/logout status=302 ...
```

**Environment**:
- Grafana version: v6.6.2 (3fa63cfc34)
- Data source type & version: InfluxDB, Server access
- OS Grafana is installed on: Ubuntu Xenial
- User OS & Browser: Ubuntu Bionic, Firefox 74.0
- Grafana plugins:  Only builtin plugins
- Others: The InfluxDB database is located on the same host as the Grafana server, and it is accessed through localhost.

**Comment by jongyllen** [comment] 2020-04-02 13:02
Hi! There has been some work done around that, could you please see if upgrading to latest Grafana version helps?

**Comment by petersohn** [comment] 2020-04-09 10:06
I upgraded to Version 6.7.2 (423a25fc32). The problem still occurs.

**Comment by marefr** [comment] 2020-06-11 20:33
Duplicate of #16638

**Closed by marefr** 2020-06-11 20:33 UTC
Labels: area/backend/auth, needs investigation

**Comment by hytrek** [comment] 2021-02-21 11:57
I am using the latest Version 7.4.2 and this happens to me still. Using Chrome on Windows 10

**Comment by Surfmobile** [comment] 2021-03-18 18:29
Same here, just upgraded to 7.4.5 and still getting this problem. I usually have multiple browser tabs open to the same Grafana server. This is super annoying. Sometimes it stays okay for half a day. And then not for half an hour.

**Comment by dpsenner** [comment] 2021-04-20 06:33
We regularly observe this behavior with the latest grafana version (7.5.4). In those situations we do find the following in the logfiles:

```text
t=2021-04-19T13:56:21+0200 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2021-04-19T13:56:21+0200 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=%ipPrefix.100 time_ms=60 size=26 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=%ipPrefix.100 time_ms=60 size=26 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=%ipPrefix.100 time_ms=0 size=26 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=%ipPrefix.100 time_ms=0 size=26 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=%ipPrefix.100 time_ms=0 size=26 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d/zqvT1W9Wz/uplinks status=302 remote_addr=%ipPrefix.100 time_ms=0 size=37 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=%ipPrefix.100 time_ms=0 size=26 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
t=2021-04-19T13:56:21+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d/zqvT1W9Wz/uplinks status=302 remote_addr=%ipPrefix.100 time_ms=0 size=37 referer="http://%server/grafana/d/zqvT1W9Wz/%dashboard?orgId=1&refresh=1m"
```

This issue appears to have a different root cause. To me this is not a duplicate to #16638. Please reopen this issue.

When this happened, I had more than one dashboard opened in different browser tabs. Could this be a race condition between multiple queries attempting to refresh the token almost at the same time?

**Comment by marefr** [comment] 2021-04-20 10:07
@Surfmobile @dpsenner if you're not seeing database is locked errors you should probably have a look at #15316

**Comment by dpsenner** [comment] 2021-06-30 06:10
The situation has improved and probably was fixed with https://github.com/grafana/grafana/pull/32999.
