### ISSUE TITLE
Loki: add ability to save/load query parameters as a dashboard

### ISSUE THREAD

**Issue by previ** [grafana/grafana#18467] opened 2019-08-08 20:23 UTC
It should be possible to define a query (set of filters) on logs and save it as a dashboard.
It would be best to be able to make some query parameters immutable by the log viewer, as well as leave other parameters free to add/change.

The use case is (example):

- Define a set of log dashboards limited in scope to applications deployed in one (ore a few) namespace and accessible by a team.
- Let the team add specific query (time, component) but not alter the namespace scope.

Current solution:

- Save bookmark of "Explore" view

**Comment by hugohaggmark** [comment] 2019-08-12 05:47
Thanks for contributing @previ! I think we already have a feature request that would be close to your proposed solution here #16325. I'm closing this issue now but we can reopen it if you find that your feature request isn't covered by #16325.

**Comment by hugohaggmark** [comment] 2019-08-12 07:01
Duplicate of #16325

**Closed** 2019-08-12 07:02 UTC
Labels: type/duplicate
