### ISSUE TITLE
Alerting: cannot modify or delete alert rule if there are multiple errored alert rules in the same evaluation group

### ISSUE THREAD

**Issue by derekhuizhang** [grafana/grafana#67791] opened 2023-05-03 22:01 UTC
### 
# What went wrong?

**What happened**:

https://github.com/grafana/grafana/blob/fb5a7acc7324018a1dd745f0f1aed797bc611ee1/pkg/services/ngalert/api/api_ruler_validation.go#L154

This line appears to validate all rules in an evaluation group. This code seems to run when I try to modify or delete one rule in a evaluation group. That means **if I have errors in multiple rules in an evaluation group, I will never be able to fix any of the errors** bc trying to modify or delete any individual errored rule will cause the evaluation group rule validation to fail, preventing me from doing the modification or deletion.

**What did you expect to happen**:
I should be able to fix errored alert rules if I have multiple errors in an evaluation group. This should be able to be accomplished in any of the following ways

- delete the entire evaluation group (does not seem to be possible)
- delete individual rules without needing to validate the other rules in the group
- delete the entire folder, which would then delete the entire evaluation group (this is not possible bc it currently gives me a `folder cannot be deleted: folder contains alert rules` error when I try to delete the folder with multiple errored alerts) 

### 
# How do we reproduce it?

**Step 1**:
- Use a provisioned data source in Grafana and create some rules in an evaluation group in a folder for it.

**Step 2**:
- Change the name of the provisioned data source in the provisioning file. This should create a new provisioned data source

**Step 3**
- Delete the old data source using the deleteDatasource config in Grafana.

**Step 4**
- Go to the alerts page. The alerts should be errored out bc they are configured with an invalid data source.

**Step 5**
- Attempt to change the data source to the new one in any of the alerts, or attempt to delete the errored alerts. 

When I do this, I get the following error:
```
Error: invalid rule specification at index [0]: failed to validate condition of alert rule <OtherRuleInEvaluationGroup>: failed to build query 'A': data source not found
```

This appears to be happening bc it is validating every rule in the evaluation group. Yet because it is forcing validation of every rule in the evaluation group when I try to fix one rule, and I can't change multiple rules at once, I am never actually able to fix any errored rules at all.

### 
# What Grafana version are you using?

v9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

### Are Datasources involved?

Prometheus

**Comment by tonypowa** [comment] 2023-05-05 10:02
hi @derekhuizhang 

thank you for creating this issue

I reproduced the issue from my end. 

> I am never actually able to fix any errored rules at all.

I could update the alert rule datasource via API (you first GET the datasource UID via `api/datasources`, next you GET the rule JSON via `api/v1/provisioning/alert-rules/{ruleUid}`  . And finally, you send a PUT  request to `api/v1/provisioning/alert-rules/{alertUid}`, passing entire JSON of the rule but with the new data source IUID like so

``` json

"datasourceUid": "P7E825E495DAC7948",
            "model": {
                "datasource": {
                    "type": "prometheus",
                    "uid": "P7E825E495DAC7948"

```
You can update one rule at a time.

Here is a view of both rules after I rescued one by updating its data source via API

![image](https://user-images.githubusercontent.com/45235678/236425906-b6f9c207-2f88-4ed7-8b66-97e1a2a54803.png)

> This appears to be happening bc it is validating every rule in the evaluation group.

Yes, it seems so. This is the error I got when I tried to update the broken rule's data source via UI

`Failed to save rule: failed to update rule group: request affects resources created via provisioning API: alert rule group [{orgID: 1, namespaceUID: kEZO8vf4k, groupName: mygroup}]`

More logs:
``` 

logger=context userId=1 orgId=1 uname=admin t=2023-05-05T09:50:13.254518947Z level=error msg="failed to update rule group: request affects resources created via provisioning API: alert rule group [{orgID: 1, namespaceUID: kEZO8vf4k, groupName: mygroup}]" error="failed to update rule group: request affects resources created via provisioning API: alert rule group [{orgID: 1, namespaceUID: kEZO8vf4k, groupName: mygroup}]" remote_addr=172.25.0.1 traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-05-05T09:50:13.254584591Z level=info msg="Request Completed" method=POST path="/api/ruler/grafana/api/v1/rules/folder 2" status=400 remote_addr=172.25.0.1 time_ms=3 duration=3.752417ms size=186 referer="http://localhost:3000/alerting/KAQjztP4k/edit?returnTo=%2Falerting%2Flist" handler=/api/ruler/grafana/api/v1/rules/:Namespace
logger=datasources rule_uid=KAQjztP4k org_id=1 t=2023-05-05T09:50:15.002401257Z level=debug msg="Querying for data source via SQL store" uid=PBFA97CFB590B2093 orgId=1
logger=ngalert.scheduler rule_uid=KAQjztP4k org_id=1 version=5 attempt=0 now=2023-05-05T09:50:10Z t=2023-05-05T09:50:15.003673756Z level=error msg="Failed to build rule evaluator" error="failed to build query 'A': data source not found"


```

Forwarding issue to the Alerting team

**Comment by yuri-tceretian** [comment] 2023-05-05 22:52
It looks like a duplicate of a known bug https://github.com/grafana/grafana/issues/53357

**Closed** 2023-05-05 22:52 UTC
Labels: type/bug, area/alerting
