### ISSUE TITLE
bug/heatmap: resizing heatmap causes labels to start disappearing (label height padding?)

### ISSUE THREAD

**Issue by lrstanley** [grafana/grafana#26938] opened 2020-08-11 20:33 UTC
**What happened**:

Below is a GIF of me resizing a heatmap in what I would categorize as three different stages

1. **Normal size**, given the current font for all things on the screen
   * Half of the labels are removed, from what I suspect to be an intentional feature to make things "fit" even though there is more than enough room
2. A size that I would consider **too small**
   * More of the labels are removed, though I feel as though with the proper font weight, it's being cut a bit too early
3. A size that **I would consider unwieldy (large)**.
   * All labels fit, though...

![grafana-bug](https://user-images.githubusercontent.com/1847365/89943059-9ada0b80-dbeb-11ea-9c78-efa0dad79e3b.gif)

The way we utilize heatmaps is a bit unusual, however I think with even the proper usecase, above presents an issue. We currently utilize heatmaps to show a 0 to 1 status over the day, for each "component" of the given platform infrastructure. We have one page which provides very high level red/green, to which then the on-call person can further drill down into individual platform/component pages. For example, the below heatmap which provided high-level health info for ~72 components, now has to be at least 60% larger, meaning the person has to scroll just to be able to see the heatmap for this one platform. Then, multiply that by 15 different platforms.

![image](https://user-images.githubusercontent.com/1847365/89944563-0cb35480-dbee-11ea-8053-ca478aec5cad.png)

Also worth noting, **this did not happen on Grafana v6.7.x**. We recently Upgraded to 7.1.3 and that's when the above issues started occurring. 

**What you expected to happen**:

Labels on the heatmap to really only disappear right before the actual font starts to overlap.

**How to reproduce it (as minimally and precisely as possible)**:

This is an example query that I use:
```promql
min(min_over_time(probe_success{product="some-product"}[$__interval])) by (instance)
```

Where `$__interval` is using the `interval` variable type, with mostly default grouping configs

Here is the panel JSON (it has two queries, but it doesn't matter how many, it matters how many rows in the resulting data):

```json
{
  "cards": {
    "cardPadding": null,
    "cardRound": null
  },
  "color": {
    "cardColor": "#b4ff00",
    "colorScale": "sqrt",
    "colorScheme": "interpolateRdYlGn",
    "exponent": 0.5,
    "max": 0,
    "min": 1,
    "mode": "spectrum"
  },
  "dataFormat": "tsbuckets",
  "description": "if this is RED, it means at least one component is unhealthy (e.g. failing worker). it does not imply concourse is down.\n\nthis graph uses bosh health to determine if the cluster is healthy. this is not perfect, as bosh primarily just ensures the cluster components are running, not if they are in a good state.",
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "gridPos": {
    "h": 10,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "heatmap": {},
  "highlightCards": true,
  "id": 33,
  "interval": "$time_interval",
  "legend": {
    "show": false
  },
  "links": [],
  "reverseYBuckets": true,
  "targets": [
    {
      "expr": "min(min_over_time(bosh_job_healthy{environment=~\"cc-.*\", env=~\"$env\"}[$__interval])) by (environment)",
      "legendFormat": "bosh: {{ environment }}",
      "interval": "",
      "format": "time_series",
      "instant": false,
      "intervalFactor": 1,
      "refId": "A"
    },
    {
      "expr": "min(min_over_time(probe_success{product=\"concourse\", type=\"vip\", env=~\"$env\"}[$__interval])) by (instance)",
      "legendFormat": "vip: {{ instance }}",
      "interval": "",
      "format": "time_series",
      "hide": false,
      "intervalFactor": 1,
      "refId": "B"
    }
  ],
  "title": "concourse health (group: $time_interval)",
  "tooltip": {
    "show": true,
    "showHistogram": false
  },
  "transformations": [],
  "transparent": true,
  "type": "heatmap",
  "xAxis": {
    "show": true
  },
  "yAxis": {
    "decimals": null,
    "format": "percentunit",
    "logBase": 1,
    "max": null,
    "min": null,
    "show": true,
    "splitFactor": null
  },
  "yBucketBound": "middle",
  "hideZeroBuckets": false,
  "timeFrom": null,
  "timeShift": null,
  "xBucketNumber": null,
  "xBucketSize": null,
  "yBucketNumber": null,
  "yBucketSize": null,
  "datasource": null
}
```

**Anything else we need to know?**:

I've tried playing with bucket bounding, and many other options that could potentially affect the labels, but I can't seem to find much.

**Environment**:
- Grafana version: v7.1.3
- Data source type & version: Prometheus @ v2.20.1
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Windows 10 & Chrome 84.0.4147.125
- Grafana plugins: No plugins other than stock

**Comment by sakjur** [comment] 2020-08-12 08:09
Thank you for reporting this, I agree with you that we are overeager to hide buckets in Grafana 7 (as opposed to never hiding them in Grafana 6). Seems like it should be possible to find something between those two extremes.

**Comment by lrstanley** [comment] 2020-08-15 06:56
Looks like this is a duplicate of: https://github.com/grafana/grafana/issues/26317; also related: https://github.com/grafana/grafana/issues/11342 (and: https://github.com/grafana/grafana/pull/24351)

Submitting a PR shortly...

**Comment by sakjur** [comment] 2020-08-15 07:22
@lrstanley :+1: Awesome! I'm closing this one as a duplicate of #26317 so any discussion is kept there.

**Closed by sakjur** 2020-08-15 07:22 UTC
Labels: area/panel/heatmap, type/bug, type/ux
