### ISSUE TITLE
Password Reset throws console error Cannot read property 'google' of undefined

### ISSUE THREAD

**Issue by Awatatah** [grafana/grafana#20811] opened 2019-12-02 17:19 UTC
**What happened**:
AS a user, when I attempt to reset my password using the password reset link, after I click "Reset Password" I receive the following error in UI

> TypeError: Cannot read property 'google' of undefined

In client console, there is a JS error:

> react-dom.production.min.js:198 TypeError: Cannot read property 'google' of undefined
    at V (LoginForm.tsx:59)
    at U (ChangePassword.tsx:42)
    at $i (react-dom.production.min.js:150)
    at Do (react-dom.production.min.js:178)
    at Ga (react-dom.production.min.js:232)
    at Ya (react-dom.production.min.js:233)
    at Au (react-dom.production.min.js:249)
    at Tu (react-dom.production.min.js:248)
    at Su (react-dom.production.min.js:245)
    at Ja (react-dom.production.min.js:243)

**What you expected to happen**:
Execpt user to be able to reset password with no error

**How to reproduce it (as minimally and precisely as possible)**:
I am using the docker image:latest, `Grafana v6.5.1 (1763a0f)`

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.5.1 (1763a0f)
- OS Grafana is installed on: Docker (Heroku) 
- User OS & Browser: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- Grafana plugins: N/A
- Others: N/A
<img width="750" alt="Screen Shot 2019-12-02 at 10 18 46 AM" src="https://user-images.githubusercontent.com/17914534/69980281-25129180-14ed-11ea-9f67-65d879c02990.png">

**Comment by marefr** [comment] 2019-12-02 19:11
Duplicate of #20663

**Closed by marefr** 2019-12-02 19:11 UTC
Labels: needs investigation, type/bug

**Comment by torkelo** [comment] 2019-12-02 21:06
moved the fix for that issue to next patch (coming) patch release milestone

**Comment by Awatatah** [comment] 2019-12-02 23:14
@torkelo Why was this closed when there is no resolution on https://github.com/grafana/grafana/issues/20663 ? I am on latest version and issue is still present...

**Comment by Awatatah** [comment] 2019-12-02 23:15
Ok I will wait for next patch
