### ISSUE TITLE
Webhook Missing Data

### ISSUE THREAD

**Issue by josefkorbel** [grafana/grafana#17535] opened 2019-06-12 08:23 UTC
While switching to webhooks we've discovered that in the json payload, there is no information about the query, or the query parameter (WHERE clause, etc). How can we get these informations to webhooks? We NEED to know from where is this coming from

**What would you like to be added**:
Information about panel query, or parameters in the webhook json payload.

**Why is this needed**:
Since it is unusable for us otherwise and honestly I didnt even think about the absence of this.

**Comment by hugohaggmark** [comment] 2019-06-12 13:16
Duplicate of: #11538

**Closed** 2019-06-12 13:17 UTC
Labels: type/duplicate
