### ISSUE TITLE
Support anonymous access with cookies/localstorage is disabled

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#15884] opened 2019-03-08 19:33 UTC
**What happened**:

I'm following a link to any Grafana instance, home page, or dashboard. I see the following:

<img width="998" alt="capture" src="https://user-images.githubusercontent.com/156867/54051012-a1837880-41d8-11e9-95a7-d939b5c7ea13.png">

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.exists (./public/build/app.dfabdd44b3be44288eac.js:1:144760)
    at t.getBool (./public/build/app.dfabdd44b3be44288eac.js:1:144182)
    at new t (./public/build/app.dfabdd44b3be44288eac.js:1:160408)
    at Object.<anonymous> (./public/build/app.dfabdd44b3be44288eac.js:1:160330)
    at s (./public/build/app.dfabdd44b3be44288eac.js:1:518)
``` 

**How to reproduce it (as minimally and precisely as possible)**:

* Google Chrome (latest stable, macOS).
* Settings, Content Settings, Cookies: Untick "Allow sites.. ".

**Anything else we need to know?**:

I have multiple browser profiles. In the profile for my primary authenticated services I've allowed certain origins to store persistent data, those that I trust not to track me and want to allow storing data indefinitely.

When browsing the web in that profile, I know origin storage won't persist in my browser. If a site insists on storing data to operate, I may switch to a private mode or temporary profile.

However, most websites work just fine. It seems like Grafana should be able to operate there as well, without demanding to store data. This would allow me to browse dashboards with much less friction, from my primary browsing context.

**Environment**:
- Grafana version: Grafana v5.4.2 (d812109)
- OS Grafana is installed on: Debian 9 Stretch

**Comment by Krinkle** [comment] 2019-03-08 19:34
When using `localStorage`, one must always wrap the interaction with try/catch because the API may be disabled, full, or otherwise unauthorised. This is standardised behaviour in web browsers.

**Comment by torkelo** [comment] 2019-03-09 09:12
You won't be able to login anyway. But If you have anonymous access enabled you could still use Grafana so I think we can fix this for that use case.

**Comment by heliodor** [comment] 2020-08-16 12:53
This also occurs if you embed a dashboard in an iframe and disable 3rd party cookies. @Krinkle 's [comment](https://github.com/grafana/grafana/issues/15884#issuecomment-471049278) is on point. `localStorage` not being available needs to be handled.

**Comment by shweppsie** [comment] 2020-12-10 00:43
Is this not a bug as it seems to break the iframe functionality?
![image](https://user-images.githubusercontent.com/68794/101706281-9ff18d80-3aed-11eb-8f1a-46c3d94d0a02.png)

**Comment by pkolyvas** [comment] 2021-07-26 16:45
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by deton57** [comment] 2021-08-30 16:18
Hi is there a workaround?

**Comment by Krinkle** [comment] 2024-01-20 07:11
Still an issue as of Grafana v9.4.14 (49d3cf745f) and Google Chrome 120.

The setting has moved to: Settings, Privacy and security, Site settings, Additional, On-device site data, Don't allow.

**Comment by joshhunt** [comment] 2024-02-29 16:11
I know this was opened before, but I'm going to close-as-dupe to https://github.com/grafana/grafana/issues/40434 which contains more details about what we want  to do to fix it. This issue is already linked to from there, so we're aware of the context.

Thanks for reporting!

**Closed by joshhunt** 2024-02-29 16:11 UTC
Labels: type/bug, crossroads-call
