### ISSUE TITLE
Colored axis-values in new time series panel for better readability REQUEST

### ISSUE THREAD

**Issue by BertSchel** [grafana/grafana#33002] opened 2021-04-14 17:33 UTC
**What would you like to be added**: 
Colored axis-values, same color as belonging trendline.

**Why is this needed**: 
For easier readability. When you make use of 6 value-axes for example and all of them have values in white, it can be confusing what axis goes with what trendline. 

Attached, see example I made in photoshop.

![Colored axis](https://user-images.githubusercontent.com/40671217/114753497-ceab9900-9d57-11eb-9836-e00921ee4392.jpg)

**Comment by leeoniya** [comment] 2021-04-14 17:55
thanks for the request. this is a duplicate of https://github.com/grafana/grafana/issues/29932. please add your upvote to that issue.

we already have this on the radar in https://github.com/grafana/grafana/issues/30564, though no definitive timeline for it yet.

**Closed by leeoniya** 2021-04-14 17:55 UTC
Labels: area/panel/timeseries, type/feature-request
