### ISSUE TITLE
Update datasource field in panels when Datasource name is changed

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3240] opened 2015-11-15 04:27 UTC
Today I changed my datasource's name and all my dashboards broke. If the datasource name is changed then the name should be propagated to all the panels of all the dashboards. I understand that adding this feature needs time to be implemented.

**Comment by torkelo** [comment] 2015-11-16 05:39
dupe of https://github.com/grafana/grafana/issues/1664

**Closed by torkelo** 2015-11-16 05:39 UTC
