### ISSUE TITLE
"self-referential" dashboard variables make dashboards unusable

### ISSUE THREAD

**Issue by twz123** [grafana/grafana#22497] opened 2020-02-28 16:33 UTC
**What happened**:

I tried to create a "self-referential" dashboard variable based on a Prometheus query. This "just" worked when editing this in the Dashboard settings, and the Dashboard was rendered without any problems. After a Save and Reload, the Dashboard stopped working completely in the UI. It just showed the "Services Spinner" forever. Only workaround was to use cURL to restore a previous Dashboard version. The Web UI was completely defunct.

**What you expected to happen**:
The Dashboard just works (as it did when editing the variable, before reloading the Dashboard), or at least give a meaningful error and allow access to the Dashboard versions, so that one doesn't need to send a hand-crafted HTTP request to Grafana in order to restore functionality.

**How to reproduce it (as minimally and precisely as possible)**:

Use the Dashboard below and change the query for the variable from `query_result(count(test{test=""}))` to `query_result(count(test{test="$Test"}))` and save the changes. The Dashboard works until the web page is reloaded.

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 622,
  "iteration": 1582906525562,
  "links": [],
  "panels": [],
  "schemaVersion": 22,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "isNone": true,
          "selected": false,
          "text": "None",
          "value": ""
        },
        "datasource": "Prometheus",
        "definition": "query_result(count(test{test=\"\"}))",
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "Test",
        "options": [],
        "query": "query_result(count(test{test=\"\"}))",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "x",
  "uid": "UK9czvlWk",
  "version": 3
}
```

Diff between working and non-working version

```diff
--- x.json	2020-02-28 17:20:14.082527773 +0100
+++ x_defunct.json	2020-02-28 17:16:20.381191109 +0100
@@ -33,14 +33,14 @@
           "value": ""
         },
         "datasource": "Prometheus",
-        "definition": "query_result(count(test{test=\"\"}))",
+        "definition": "query_result(count(test{test=\"$Test\"}))",
         "hide": 0,
         "includeAll": false,
         "label": null,
         "multi": false,
         "name": "Test",
         "options": [],
-        "query": "query_result(count(test{test=\"\"}))",
+        "query": "query_result(count(test{test=\"$Test\"}))",
         "refresh": 2,
         "regex": "",
         "skipUrlSync": false,
@@ -75,4 +75,4 @@
   "title": "x",
   "uid": "UK9czvlWk",
   "version": 3
-}
+}
\ No newline at end of file
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Prometheus (how do I figure out the version?)
- OS Grafana is installed on: Docker Container / Kubernetes
- User OS & Browser: Ubuntu 18.04 / Firefox 73.0.1
- Grafana plugins: (how do I list all the plugins?)
- Others:

**Comment by torkelo** [comment] 2020-03-02 09:01
duplicate of https://github.com/grafana/grafana/issues/12743

**Closed by torkelo** 2020-03-02 09:01 UTC
