### ISSUE TITLE
ARM64 packages are missing in APT repository

### ISSUE THREAD

**Issue by pavel-odintsov** [grafana/grafana#13776] opened 2018-10-21 23:47 UTC
Hello!

I noticed that you added ARM64 version of Grafana using direct download links from install page. But your official APT repo does not have ARM64 versions of Grafana and I cannot use it to install it.

Can you add APT repository for ARM64, please?

Thank you!

**Comment by marefr** [comment] 2018-10-23 09:44
Duplicate of #12761

**Closed by marefr** 2018-10-23 09:45 UTC
