### ISSUE TITLE
can not use variable on alert name

### ISSUE THREAD

**Issue by justlooks** [grafana/grafana#16267] opened 2019-03-28 01:34 UTC
if I define alert rule like this, in alert info ,still display "alertname = system interface {{$labels.device}} outband high".

```
  - alert: system interface {{$labels.device}} inband high
    expr: 'rate(node_network_receive_bytes_total[5m]) > 2048000'
    for: 10s
    labels:
      severity: critical
    annotations:
      description: 'system interface {{$labels.device}} inband high on {{$labels.hostname}} reach {{$value}}'
      summary: system interface {{$labels.device}} inband is high
```

**Comment by marefr** [comment] 2019-03-28 04:25
Duplicate of #6557

**Closed** 2019-03-28 04:25 UTC
Labels: type/duplicate
