### ISSUE TITLE
[Bug] Grafana looks confused when fetch request is cancelled

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#8536] opened 2017-06-04 21:29 UTC
We run Grafana behind OAuth with a limited cookie validity time. When cookie expires, Grafana starts showing spinners on graphs indefinitely and doesn't indicate failure in any way.

In the console I see:

```
Panel request cancelled Object {err: Object, cancelled: true}
```

Corresponding code piece:

* https://github.com/grafana/grafana/blob/v4.3.2/public/app/features/panel/metrics_panel_ctrl.ts#L101-L105

I'd rather have a red corner with an error saying that the request is cancelled:

![image](https://cloud.githubusercontent.com/assets/89186/26765503/090984a0-4932-11e7-81a1-93c0d5775781.png)

But instead I see this:

![image](https://cloud.githubusercontent.com/assets/89186/26765494/f0f6b978-4931-11e7-828f-0f5e669c67b5.png)

**Comment by torkelo** [comment] 2017-06-05 05:46
Grafana only shows the panel error when the time series store returns an error, it is cancelled when you hit refresh and not completed yet (it will retry), I think a timeout can also cause a cancel and a retry not sure. 

Check chrome dev tools network tab for a more complete network history

**Comment by bobrik** [comment] 2017-06-05 06:03
@torkelo Grafana asks own API (datasource is proxied), gets 302 from nginx that ensures that OAuth cookie is valid. Then Chrome tries to do `OPTIONS` to accounts.google.com, but that's CORS violation so Chrome triggers 405 and that's what javascript sees. At no point there's a user-triggered cancelation of the request.

```
OPTIONS https://accounts.google.com/o/oauth2/auth?scope=email&client_id=…&redirect_uri=https%3A%2F%2Ffoo.org%2F_oauth&response_type=code 405 ()
/dashboard/db/...:1 XMLHttpRequest cannot load https://accounts.google.com/o/oauth2/auth?scope=email&client_id=…&redirect_uri=https%3A%2F%2Ffoo.org%2F_oauth&response_type=code. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://foo.org' is therefore not allowed access. The response had HTTP status code 405.
```

**Comment by torkelo** [comment] 2017-06-06 07:59
So it's a CORS issue with your oauth setup for the data source? 

Unable to replicate any issue here, can you provide more detail of the network requests and logs & setup?

**Comment by bobrik** [comment] 2017-06-10 20:46
Theres' nginx between the browser and the server:

```
browser -> nginx (auth happens here) -> grafana
```

If auth is expired, nginx does redirect to Google:

```
browser -> nginx (auth failed, 301 to google)
browser -> google
```

**Comment by torkelo** [comment] 2017-06-11 07:38
Ok, redirect on session timeout is working? Or is it that when Google OAuth cookies timeout all panels requests get CORS error that is handled as a cancelation and retried? Do you see perpetual requests? After 3 retries it should give up

**Comment by bobrik** [comment] 2017-06-11 07:49
>  Or is it that when Google OAuth cookies timeout all panels requests get CORS error that is handled as a cancelation and retried?

Almost that, but no retry (at lest not in a minute).

**Comment by torkelo** [comment] 2017-08-28 12:20
failed to replicate this, are you still seeing this?

**Comment by discordianfish** [comment] 2017-09-26 18:22
I might have a similar/same issue. Some graphs are very flakly, loading maybe 5% the time at all.  They are pretty much the same as other graphs in the dashboard, just belonging to a different row.
When I refresh the dashboard I see a bunch of canceled requests right away which looks suspicious to me:
![grafana-canceled](https://i.imgur.com/kzvAelI.png).
After that the spinner on the not-yet-loaded graphs keep spinning even though there is no request pending anymore.

But I've just realized that I manually edited the json on this one and duplicated some graphs.. Maybe I ended up with multiple graphs identified the same and canceling each others request. Will verify that and update this later. @bobrik Maybe you have a similar same issue?

**Comment by discordianfish** [comment] 2017-09-27 08:53
I can confirm this was the problem in my case.
Would be nice though to get rid of the ids in the dashboard export json to avoid such subtle issues.

**Comment by bobrik** [comment] 2017-10-16 03:59
@torkelo steps to reproduce:

1. Open http://play.grafana.org/.
2. In /etc/hosts add override: `127.0.0.1 play.grafana.org`
3. Run the following: `sudo go run 302.go`

Here's `302.go`:

```go
package main

import "net/http"

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Add("Location", "http://example.com/")
		w.WriteHeader(http.StatusFound)
	})

	http.ListenAndServe("127.0.0.1:80", nil)
}
```

Code is also here: https://github.com/bobrik/grafana-issues/tree/master/8536

4. Close idle sockets in Chrome (or equivalent in other browser): chrome://net-internals/#sockets
5. Refresh graphs in Grafana:

![image](https://user-images.githubusercontent.com/89186/31594644-1a654ec4-b1eb-11e7-9898-0baeb89ecacb.png)

![image](https://user-images.githubusercontent.com/89186/31594716-9d003632-b1eb-11e7-9bd6-6eb60267480f.png)

**Comment by torkelo** [comment] 2017-10-16 05:30
you redirecting to another domain that does not pass browser CORS test. Seems like this also causes request to cancel, and grafana will keep loading state as cancelled is usually caused by another request going out.

**Comment by bobrik** [comment] 2017-10-16 06:15
Yes, my ask here is for Grafana to detect this and act more obviously: show a warning or do a redirect itself.

**Comment by torkelo** [comment] 2017-10-16 07:26
It can't do the redirect as the browser stops that via CORS check failing (Cross origin resource sharing)

**Comment by bobrik** [comment] 2017-10-16 15:20
Is it possible to have a separate URL to double check if all requests to Grafana are being redirected?

If we see cancelled request, we can query that URL and if it is cancelled as well, we're probably being redirected to auth.

**Comment by torkelo** [comment] 2018-04-12 06:33
closing this as not sure what Grafana can do here, and no other similar reports.

**Closed by torkelo** 2018-04-12 06:33 UTC
Labels: state: needs more detail
