### ISSUE TITLE
XY Chart: tooltip bug

### ISSUE THREAD

**Issue by yulipumal** [grafana/grafana#65472] opened 2023-03-28 16:43 UTC
Dear grafana community,

when using `XY Chart`, the tooltip only shows up when hovering exactly over a plotted point. Compared to `Time Series`, the nearest point on hovered x interception is plotted. This would make sense for XY Chart as well.

Example: [XY Chart](https://i.ibb.co/TvzzB6T/XY.png) | [Time Series](https://i.ibb.co/X5v5VFV/time-Series.png)

**Comment by yulipumal** [comment] 2023-03-29 06:10
The issue happens in all XY Chart Panels on current Grafana versions, independent on OS.

**What are you trying to achieve?**
Show the tooltip on an XY Chart.

**How are you trying to achieve it?**
With mouse hover on an area outside of a data point. (see linked screenshot 1)

**What did you expect to happen?**
Showing a tooltip of the current x position, as in Time Series Panel (see screenshot 2).

**What happened?**
no tooltip is shown.

_Grafana 8.0 - 9.4.7 (latest), Running on Windows 11 with Chrome)
No errors in log._

**Comment by usmangt** [comment] 2023-03-30 11:46
Thanks

Based on your steps of reproduction, I was also able to reproduce it on my test machine. 

But I am not sure 100% if this is an expected behaviour or a bug. Therefore will ask the Engineering team if they can confirm this one.

**Comment by usmangt** [comment] 2023-03-30 11:49
Ah there seems to be an existing PR https://github.com/grafana/grafana/pull/65094

therefore please track the status there. I will now close this one!!

**Closed by usmangt** 2023-03-30 11:49 UTC
Labels: area/panel/xychart, area/tooltip, triage/needs-confirmation

**Comment by yulipumal** [comment] 2023-03-30 11:53
Thanks for the cross-reference @usmangt. #65094 describes exactly my problem.
