### ISSUE TITLE
Azure Monitor: Bug typing a template variable

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#43505] opened 2021-12-23 15:43 UTC
**What happened**:

Grafana crashes while writing the template variable. We should only execute it onBlur.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Click on dashboard settings -> variables
2. Add a new Azure Monitor query.
3. Select "Grafana Query Function"
4. Type ResourceNames() and then try to type the parameters.

![Peek 2021-12-23 16-43](https://user-images.githubusercontent.com/4025665/147262686-89a03cb4-5b98-4005-81cf-afc240e0eb5c.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4-pre
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sunker** [comment] 2021-12-27 10:08
This is a dupe of https://github.com/grafana/grafana/issues/43197

**Closed by sunker** 2021-12-27 10:08 UTC
Labels: type/bug, datasource/Azure, good first issue
