### ISSUE TITLE
Data is stripped in notification to AlertManager

### ISSUE THREAD

**Issue by jayden-xie** [grafana/grafana#25808] opened 2020-06-24 14:44 UTC
**What happened**:
Data is stripped in notification to AlertManager, only metric value is passed to AlertManager.
**What you expected to happen**:
All data should be send to AlertManager
**How to reproduce it (as minimally and precisely as possible)**:

1. Use webhook test tool, https://webhook.site/
2. Go to notification setting page
3. Try **send test** for webhook, you will get
```json
{
  "dashboardId": 1,
  "evalMatches": [
    {
      "value": 100,
      "metric": "High value",
      "tags": null
    },
    {
      "value": 200,
      "metric": "Higher Value",
      "tags": null
    }
  ],
  "message": "Someone is testing the alert notification within grafana.",
  "orgId": 0,
  "panelId": 1,
  "ruleId": 0,
  "ruleName": "Test notification",
  "ruleUrl": "http://localhost:3000/",
  "state": "alerting",
  "tags": {},
  "title": "[Alerting] Test notification"
}
```
4. Try **send test** for AlertManager, you will get
```json
[
  {
    "annotations": {
      "description": "Someone is testing the alert notification within grafana.\nError: This is only a test",
      "summary": "Test notification"
    },
    "generatorURL": "http://localhost:3000/",
    "labels": {
      "alertname": "Test notification",
      "metric": "High value"
    },
    "startsAt": "2020-06-24T13:59:04Z"
  },
  {
    "annotations": {
      "description": "Someone is testing the alert notification within grafana.\nError: This is only a test",
      "summary": "Test notification"
    },
    "generatorURL": "http://localhost:3000/",
    "labels": {
      "alertname": "Test notification",
      "metric": "Higher Value"
    },
    "startsAt": "2020-06-24T13:59:04Z"
  }
]
```
5. You can see the high value and higher value are not sent to AlertManager

**Anything else we need to know?**:
I can see in code that data is not collected.
https://github.com/grafana/grafana/blob/3a0f2dc160208fb544cc886b20c17c193105ff0b/pkg/services/alerting/notifiers/alertmanager.go#L123

**Environment**: 
- Grafana version: 7.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2020-06-24 21:50
Not sure what you're actually require. Looking at [alert manager documentation](https://prometheus.io/docs/alerting/latest/clients/) it only accepts certain payload. I'm closing this, but let me know if I've misunderstood something.

**Comment by jayden-xie** [comment] 2020-06-25 01:17
Expected payload would be:
```json
[
  {
    "annotations": {
      "description": "Someone is testing the alert notification within grafana.\nError: This is only a test",
      "summary": "Test notification"
    },
    "generatorURL": "http://localhost:3000/",
    "labels": {
      "alertname": "Test notification",
      "metric": "High value",
      **"value": "100"**
    },
    "startsAt": "2020-06-24T13:59:04Z"
  },
  {
    "annotations": {
      "description": "Someone is testing the alert notification within grafana.\nError: This is only a test",
      "summary": "Test notification"
    },
    "generatorURL": "http://localhost:3000/",
    "labels": {
      "alertname": "Test notification",
      "metric": "Higher Value",
      **"value": "200"**
    },
    "startsAt": "2020-06-24T13:59:04Z"
  }
]
```
And if there're several columns in data result, all of them should be sent.
I've tested that AlertManager is able to accept data format in this way.
@marefr

**Comment by xieziqiang** [comment] 2020-10-23 10:30
Hi, I met the same problem. How did you solve it?

**Comment by jayden-xie** [comment] 2020-10-26 01:38
@xieziqiang I had all data returned in metric with a JSON string, get all the data in this way.

**Comment by xieziqiang** [comment] 2020-10-26 03:05
@jayden-xie  I don't quite understand. How to configure alert in this case？ Can you give me an example to elaborate？thanks.

**Comment by filippog** [comment] 2024-01-22 16:01
This and #29274 seem a duplicate of each other

**Comment by JohnnyQQQQ** [comment] 2024-05-08 09:54
Values can now be templated into labels as described in the docs https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/#print-the-value-of-a-query or in the notification https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/create-notification-templates/, closing this for now.

**Closed by JohnnyQQQQ** 2024-05-08 09:54 UTC
Labels: type/feature-request, area/alerting/notifications, prio/awaiting-more-evidence
