### ISSUE TITLE
range annotations that exceed set limit, may be visualized incorrectly

### ISSUE THREAD

**Issue by voltcode** [grafana/grafana#17386] opened 2019-05-31 08:18 UTC
**What happened**:

I created 1000 annotations via api.
I pulled them onto a dashboard, with limit = 100.
I saw many annotations correctly, but one of them, seemed to start in -infinity and ending where it should've.
It seems like the limit does not respect range annotations, which may lead to sending only the timeEnd annotation to the dashboard. Such range is visualized incorrectly as starting in -infinity.

**What you expected to happen**:
limit should understand range annotations: 
either treat range annotation as 1 annotation when checking limit,
or if when visualising, when there is a range annotation with only one data point ,do not visualize it (log in console maybe?) 
there are a couple of options, but current behavior is the worst possible one, because such incorrectly painted annotation looks very bad., overlays others.

**How to reproduce it (as minimally and precisely as possible)**:
described in what happened.

**Anything else we need to know?**:

When I set the limit to 2000, everything worked correctly (albeit veeeery slow).

**Environment**:
- Grafana version:  Grafana v6.1.6 (commit: cf9cb45)

**Comment by marefr** [comment] 2019-05-31 09:38
Duplicate of #15764

**Closed by marefr** 2019-05-31 09:38 UTC
