### ISSUE TITLE
Variables: Add Toggle Button Value Picker Mode 

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#30177] opened 2021-01-11 08:34 UTC
**What would you like to be added**:

I would love to see a a toggle button beside current dropdowns. It should be created as a variable but displayed as toggle instead of dropdown.

![Toggle Example](https://images.freecreatives.com/wp-content/uploads/2015/05/214.jpg)

**Why is this needed**:

There are cases that are binary, one or off. Even though dropdowns cover the situation it doesn't look intuitive.

For example: I have N categories generated based on other filters (variables) and a single category that has no relation with those filters. Dropdowns works fine but a toggle would just look better for that single category.

**Comment by torkelo** [comment] 2021-01-11 09:46
Are you talking about a dashboard template boolean variable? What would it's values be? And it's definition?

**Comment by mertbakir** [comment] 2021-01-11 10:13
> Are you talking about a dashboard template boolean variable? What would it's values be? And it's definition?

Values can be anything. 'Day', 'Night', 0, 1, True, False. We can already set these values using the existing "Custom" Type variable. 
I was thinking to use these boolean variable in SQL CASE Statements for panel queries or queries for other variables.

**Comment by sreenivasalokesh** [comment] 2023-05-03 10:10
Would love to have this. A toggle as Variable which would produce binary results

**Comment by municharan7** [comment] 2023-08-05 11:13
is this toggle button plugin enabled. If not how we can add toggle button. Can anyone help me in this ?

**Comment by greglAAL** [comment] 2023-10-23 22:50
Would love this. My use case would be for filtering out devices. EG: "Show PROD only"
ON, would enable a query to be run and ,OFF , would run a different query....

**Comment by spryslmatej** [comment] 2024-01-10 14:04
Would greatly benefit from this as well... :)

**Comment by gelicia** [comment] 2024-02-28 17:33
Duplicate of #15490

**Closed by gelicia** 2024-02-28 17:33 UTC
Labels: type/feature-request, area/dashboard/templating, prio/awaiting-more-evidence
