### ISSUE TITLE
Internal links between one Loki datasource and another ot the same Loki datasource

### ISSUE THREAD

**Issue by JotBePunkt** [grafana/grafana#31883] opened 2021-03-11 07:30 UTC
**Why is this needed**:

Linking between Loki sources and Jaeger is a great feature to analyze issues. The issue is, that jaeger does not contain all traces, so it would be great having a link to find logs with the same traceId

**What would you like to be added**:

Similar to internal links to an Jaeger data source there should be an easy option to link between multiple (or the same) Loki instance using an derived field (or potentially multiple). 

Clicking the link, the explore view splits up and a search open with the search

```
{<log tream selector>} |= "<traceId>"
```

For the log selector I see the following options;

1. Taking over the log stream selector from the linking search. Example:
Linking from
```
{namespace=~"someNamesp.*", app="someApp"} |= "Error" | logfmt | ...
```
links to 
```
{namespace=~"someNamesp.*", app="someapp"} |="<traceId>"
```
While this might be the easiest solution, its the least helpful. the user had to manipulate the log steam selector when they would search for logs from other apps. 

2. The administrator can set a fixed log stream selector for the link. 
e.g. the administrator sets the fixed log stream selector `namespace=~"someNamespace|otherNamespace"`
then linking from 
```
{namespace=~"someNamesp.*", app="someApp"} |= "Error" | logfmt | ...
```
would lead to 
```
{namespace=~"someNamespace|otherNamespace"} |="<traceId>"
```
While this might be more helpful then the first option, it might lead to slow queries, especially when the set log stream selector is too general and too many streams needs to be searched in.

3. Taking index fields from the linked log entry:
Similar then the tag selection when linking from a Jaeger data source to the source, the administrator can set some index fields. e.g. if he selected `nameSpace`.

Linking from the search 
```
{namespace=~"someNamesp.*", app="someApp"} |= "Error" | logfmt | ...
```
and a log entry with the index `namespace="someNamespace"`

would lead to 
```
{namespace="someNamespace"} |="<traceId>"
```

**Comment by zoltanbedi** [comment] 2021-03-11 09:07
Thanks for your input @JotBePunkt. This is something that we are looking forward to do after 8.0. We also have an issue for this so I'm going to close this issue and use the other one for tracking this feature request. Duplicate of https://github.com/grafana/grafana/issues/31778

**Closed by zoltanbedi** 2021-03-11 09:07 UTC
