### ISSUE TITLE
grafana docker 6.4.x - mostly fails to connect to Graphite

### ISSUE THREAD

**Issue by JerryCurl** [grafana/grafana#20534] opened 2019-11-20 18:07 UTC
**What happened**:
Running Grafana 6.3.x in on-prem K8s. All working 100%.  Graphite is 1.15.  
when I upgrade the deployment to Grafana 6.4.x - dashboards no longer populate data from graphite at about a 50% success rate.  Nothing changed on Graphite side.  Logs from the grafana pod show dozens of : "2019/11/19 20:14:10 http: proxy error: dial tcp: lookup graphite-svc.graphite.svc.cluster.local: no such host"

I have Graphite as my only and default datasource, and it works 100% on 6.3.x docker image.

**What you expected to happen**:
reliable data returned from Graphite

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade k8s deployment to 6.4.x, open any dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.x
- Data source type & version: Graphite 1.15
- OS Grafana is installed on: docker image (6.4 is alpine)
- User OS & Browser: all
- Grafana plugins: ldap
- Others:

**Comment by marefr** [comment] 2019-11-20 18:17
Duplicate of #20153

**Closed by marefr** 2019-11-20 18:17 UTC
