### ISSUE TITLE
Dashboards: Bug in Query options when using Label filters

### ISSUE THREAD

**Issue by AresiusXP** [grafana/grafana#77915] opened 2023-11-09 10:09 UTC
### What happened?

When creating a new variable for a Dashboard, using `Query type: Label Values`, there's a bug that makes the label filters impossible to fill.

https://github.com/grafana/grafana/assets/20631840/12ae0bd5-15c2-40b8-ab32-8807b7691a70

If `Label` is left empty, `Label Filters` works normally. However, the moment you select something in `Label`, filters disappear and the  behaviour from the vid starts again.

### What did you expect to happen?

When selecting a value for the filter, I expect the filter to remain. Same when I add a new filter.

### Did this work before?

It was working before when using Grafana helm chart 6.52.1 (appVersion: 9.4.3).

### How do we reproduce it?

1. Create a new variable in a Dashboard
2. Select query type `Label values`
3. Select a Label
4. In `Label Filters` select a label, and select a new value or write it.

### Environment (with versions)?

Grafana: 10.1.5
OS: MacOS 14.1.1, Windows 11
Browser: Chrome, Firefox

### Grafana platform?

Kubernetes

**Comment by kthompsonpros** [comment] 2023-11-10 01:06
Having the same issue. When I tried switching to a query, I received an error when trying to use `label_values()`

> Error invalid parameter "query": 1:1: parse error: unknown function with name "label_values"

I had to edit the JSON Model to make it work.

**Comment by tonypowa** [comment] 2023-11-21 17:54
thank you @AresiusXP for reporting this issue and for the screen recording

I have reproduced the same behavior from my side

Forwarding issue to Dashboard squad

**Comment by tonypowa** [comment] 2023-11-22 09:41
closing this one in favor of a previously reported issue so all investigation and context stays in one place
/duplicate of #77199

**Closed** 2023-11-22 09:42 UTC
Labels: type/bug, type/duplicate, area/dashboard/templating, area/dashboard, datasource/Prometheus, team/grafana-dashboards
