### ISSUE TITLE
Time series panel: Series blurry when refreshing the dashboard

### ISSUE THREAD

**Issue by t0mj3dus0r** [grafana/grafana#44067] opened 2022-01-14 18:25 UTC
**What happened**:
The new time series is blurry when refreshing the dashboard.

**What you expected to happen**:
The visualization should not be blurry.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel
2. In its "Thresholds" section, set Show thresholds to "As filled regions and lines"
3. Refresh the dashboard (you may need to reload a few times if the panel is using Random walk)
4. The panel is blurry

**Anything else we need to know?**:
My production environment is using a Warp10 datasource, and the panel gets blurry on every reload. However, they are never blurry on the first load. They get blurry by refreshing the dashboard.

The effect instantly disappears if the user:
- Drags the window out of fullscreen mode
- Enters/Exits edit mode
- Enters/Exits view mode

I think this is related to "devicePixelRatio not updating or being cached" as mentionned in this issue #35301
One thing I note though is that on the issue, the X and Y axis are blurred, where in my screenshots they are not.

Blurred panel:
![image](https://user-images.githubusercontent.com/54417750/149565293-5bdfc046-86d9-4fba-bc57-47a713ea1fcd.png)

Same panel after dragging the window out of fullscreen:
![image](https://user-images.githubusercontent.com/54417750/149565365-bcec0e2f-674c-492a-a33d-97dee6f01550.png)

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Warp10 2.2.1, Random walk
- OS Grafana is installed on: Docker alpine & ubuntu, works on Grafana Cloud
- User OS & Browser: Ubuntu based Linux, Google Chrome
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment] 2022-01-17 05:52
Thanks for reporting this @t0mj3dus0r! Reproduced here https://play.grafana.org/d/wLEEzE17k/time-series-panel-series-blurry-when-refreshing-the-dashboard-44067?orgId=1

**Comment by leeoniya** [comment] 2022-01-25 19:59
the cause of this was the same as https://github.com/grafana/grafana/issues/44335#issuecomment-1018744969 and was fixed by https://github.com/grafana/grafana/pull/44337.

**Closed by leeoniya** 2022-01-25 19:59 UTC
Labels: type/bug, area/panel/timeseries
