### ISSUE TITLE
Feature request: "Show source" when you can't "edit" a panel

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#5902] opened 2016-08-25 09:22 UTC
@bergquist As per promcon :)

Non-editors and all [repeated graphs](https://github.com/grafana/grafana/issues/5901) should have a "show source" button instead of "edit" or nothing.

**Comment by torkelo** [comment] 2016-08-25 14:12
dupe of https://github.com/grafana/grafana/issues/5902

**Comment by torkelo** [comment] 2016-08-25 14:13
or am I missing something? seems like the same issue?

**Closed by torkelo** 2016-08-25 14:12 UTC

**Comment by RichiH** [comment] 2016-08-25 15:02
@torkelo If you're asking if #5902 is the same as #5902, then the obvious answer is yes.

I do suspect you meant a different issue, though.

**Comment by RichiH** [comment] 2016-08-25 15:07
@torkelo also, I talked to @bergquist about this here at promcon and he seemed to agree that this was a good idea.

**Comment by torkelo** [comment] 2016-08-25 15:11
I ment the issue you linked to, https://github.com/grafana/grafana/issues/5901

**Comment by RichiH** [comment] 2016-08-25 16:05
Ah, OK.

These are potentially related, but not the same. Assume you have a user with view rights. This user can not view how the graphs are created, limiting their ability to learn by example. Plus, the Prometheus backend allows you to jump into the expression browser from the edit interface. This is our preferred way to start arbitrary drilldown into the raw data. The current system prohibits people from using that.

**Comment by torkelo** [comment] 2016-08-25 16:28
You can give users the right to have viewer rights that can edit graphs, but not save dashboards, think it's called read only editor or something like that

**Comment by RichiH** [comment] 2016-08-26 14:01
Yes, there are read-only editors, but experience shows that some people will consistently shoot their own feet given the ability to edit, even without the ability to save. Add in the recurring caching issues when changing e.g. repetition rules and you have a potentially volatile mix.

This could be avoided by still showing sources without giving the ability to edit.

**Comment by torkelo** [comment] 2016-08-27 12:23
I though you wanted them to edit?
> Assume you have a user with view rights. This user can not view how the graphs are created, limiting their ability to learn by example

**Comment by RichiH** [comment] 2016-08-27 17:28
No, just to see, learn, and jump to Prometheus. I talked to @bergquist about this use case quite a bit; it's probably easiest if we wait until you met him.

**Comment by torkelo** [comment] 2016-08-27 20:13
well if you want a viewer user to view the metrics editor they will be able to change it as well, that is why we have the read-only editor. A locked down view (without ability to change) the edit view will never happen.  

Why do you want to  jump to Prometheus?

**Comment by RichiH** [comment] 2016-08-28 07:45
> A locked down view (without ability to change) the edit view will never happen

Why? I am not trying to argue the point, just understand the motivation.

> Why do you want to jump to Prometheus?

Because from there I can edit the query and do drill-down. Especially more complex queries are a pain to type out by hand when there's ready-made ones with templates prefilled.

**Comment by torkelo** [comment] 2016-08-28 14:09
> Why? I am not trying to argue the point, just understand the motivation.

Because of complexity, disabling edit features requires lots of checks everywhere. 

> Because from there I can edit the query and do drill-down. Especially more complex queries are a pain to type out by hand when there's ready-made ones with templates prefilled.

This will be solved in the new Prometheus query editor that I started a couple of months ago, will work similar to graphite/influxdb editor with tag / label auto complete and function editing, not sure when I will have time to complete it thought :(
