### ISSUE TITLE
option to align 0 between Y-axis

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2386] opened 2015-07-22 16:18 UTC
Is is possible to add an option to align 0 between Y-axis so it could be possible to have bytes/s and packets/s on the same graph :  https://snapshot.raintank.io/dashboard/snapshot/LOf5532Dx115IdX04XFuAirNM2ZHt4iV
thanks

**Comment by torkelo** [comment] 2015-07-29 06:48
not currently :(

dupe of https://github.com/grafana/grafana/issues/1271

**Closed by torkelo** 2015-07-29 06:48 UTC
