### ISSUE TITLE
[Bug] Wrong position of "Panel description"

### ISSUE THREAD

**Issue by karolisc** [grafana/grafana#7772] opened 2017-03-08 17:24 UTC
Hi,

- What Grafana version are you using?
```
http://play.grafana.org
Chrome  Version 56.0.2924.87
```
- What did you do?
```
added 7 rows (graphs) with Descriptions
```
- What was the expected result?
```
Show Descriptions next to the "i" icon
```
- What happened instead?
```
first 3 rows show correct position of the Descriptions.
The Descriptions of the rest rows are misplaced.
```
row Nr. 3
![row_nr_3](https://cloud.githubusercontent.com/assets/5957567/23715225/95ebdf82-0434-11e7-8366-40ee3e587bfb.PNG)
row Nr. 4
![row_nr_4](https://cloud.githubusercontent.com/assets/5957567/23715235/9ac2ceda-0434-11e7-9446-f8746a839e9c.PNG)
row Nr. 5
![row_nr_5](https://cloud.githubusercontent.com/assets/5957567/23715241/9e8a1708-0434-11e7-9b2d-7e6e06dfc4f8.PNG)

Karolis

**Comment by torkelo** [comment] 2017-03-09 07:33
strange, maybe a bug in the tether library we use.

**Comment by smalik03** [comment] 2017-03-10 22:32
Isn't this same as #7708 ?

**Comment by karolisc** [comment] 2017-03-11 00:36
Hi,

it is the same issue.
I can reproduce it in http://play.grafana.org/dashboard/db/big-dashboard on
chrome and opera.

**Comment by torkelo** [comment] 2017-03-11 08:42
closing as dupe of https://github.com/grafana/grafana/issues/7708

**Closed by torkelo** 2017-03-11 08:42 UTC
Labels: comp: panel/common, type: bug

**Comment by rnovikovP** [comment] 2017-03-17 09:48
fixed in https://github.com/grafana/grafana/pull/7854
