### ISSUE TITLE
The bug on new created organisation not show the allocated user dashboard ??

### ISSUE THREAD

**Issue by vishuPPatel** [grafana/grafana#11325] opened 2018-03-21 07:08 UTC
Hello grafana team here we crated one organisation and there one user[rox]& dashboard.

give the permission of the dashboard only rox user show the dashboard but there not show the dashboard of the allocated user.

In one user created that also assign  dashboard show access permission after the login on rox user there not show any dashboard. we allocated dashboard not show there.. 

bug on new created organisation..

Thanks...!!!

**Comment by bergquist** [comment] 2018-03-21 07:30
Thank you for reporting.

Dupe of https://github.com/grafana/grafana/issues/11076

**Closed by bergquist** 2018-03-21 07:30 UTC
