### ISSUE TITLE
Using fixed time on metrics

### ISSUE THREAD

**Issue by rntbrgtt** [grafana/grafana#23998] opened 2020-04-28 13:02 UTC
**What would you like to be added**: 

I would like to be able to use fixed times when creating graphs. I need to check uptime during office hours. I can already to it checking last X hours. The problem is doing this from 9AM to 5PM for example.

**Why is this needed**: 

Some stuff are only supposed to run during office hours and I need to check it's uptime.

**Comment by papagian** [comment] 2020-04-30 08:48
Duplicate of #21210

**Closed by papagian** 2020-04-30 08:48 UTC
Labels: type/duplicate
