### ISSUE TITLE
Error when jaeger exists in environment with JAEGER_AGENT_PORT

### ISSUE THREAD

**Issue by razorsk8jz** [grafana/grafana#58608] opened 2022-11-10 20:02 UTC
**What happened**:
Grafana is unable to start due to parsing error

**What you expected to happen**:
Grafana should start correctly - not sure how grafana even knows about Jaeger being installed in my environment

**How to reproduce it (as minimally and precisely as possible)**:
Install Grafana Helm Chart (I used Kube-Prometheus-Stack) alongside https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger 

**Anything else we need to know?**:
In order to fix the issue i had to supply JAEGER_AGENT_PORT - to override however grafana was attempting get get information about jaeger - 

```
logger=settings t=2022-11-10T16:51:47.208084455Z level=info msg="Starting Grafana" version=9.2.3 commit=ec9c2ed029 branch=HEAD compiled=2022-10-31T12:36:07Z
logger=settings t=2022-11-10T16:51:47.208268856Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2022-11-10T16:51:47.208282564Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
...
...
...
logger=settings t=2022-11-10T16:51:47.208433992Z level=info msg="App mode production"
logger=settings t=2022-11-10T16:51:47.208453116Z level=warn msg="[Deprecated] the configuration setting 'tracing.jaeger' is deprecated, please use 'tracing.opentelemetry.jaeger' instead"
Failed to start grafana. error: cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://100.66.193.140:5775: strconv.ParseInt: parsing "udp://100.66.193.140:5775": invalid syntax
cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://100.66.193.140:5775: strconv.ParseInt: parsing "udp://100.66.193.140:5775": invalid syntax
```
Some logs were removed 

As you see in the logs in the JAEGER_AGENT_PORT the <IP>:<PORT> was added to the variable as it was able to find the jaeger-agent service we have running in kubernetes automatically 

once i changed env var to
```JAEGER_AGENT_PORT: "5775"```
grafana started up as normal

I would also like an explanation on why grafana automatically knew about jaeger if possible - is there some integration i'm not aware of?

**Environment**:
Kubernetes 1.24 using helm charts

**Grafana version**:
9.2.3

**Comment by mrfelek** [comment] 2022-11-15 11:29
Same issue here with 9.2.4. Also 9.0.1 and 9.1.3 have same problem.

**Comment by piotrminkina** [comment] 2022-11-24 09:22
These env variable is set by k8s Service Discovery. See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ for docs. Most likely there is a jaeger-agent service in your cluster. See below.

```console
$ kubectl get svc | grep -E 'grafana|jaeger'
grafana-image-renderer                 ClusterIP   10.43.140.72    <none>        8081/TCP                                        18h
grafana                                NodePort    10.43.231.83    <none>        3000:32080/TCP                                  18h
jaeger-elasticsearch-master            ClusterIP   10.43.121.128   <none>        9200/TCP,9300/TCP                               18h
jaeger-elasticsearch-master-headless   ClusterIP   None            <none>        9200/TCP,9300/TCP                               18h
jaeger-agent                           ClusterIP   10.43.169.95    <none>        5775/UDP,6831/UDP,6832/UDP,5778/TCP,14271/TCP   18h
jaeger-collector                       ClusterIP   10.43.146.169   <none>        14250/TCP,14268/TCP,9411/TCP,14269/TCP          18h
jaeger-query                           NodePort    10.43.36.87     <none>        80:32081/TCP,16685:31579/TCP,16687:31564/TCP    18h
$ kubectl run --rm -it --annotations=sidecar.istio.io/inject=false --image=alpine console -- sh
If you don't see a command prompt, try pressing enter.
$ env | grep JAEGER_AGENT_PORT=
JAEGER_AGENT_PORT=udp://10.43.169.95:5775
```

**Comment by joey-grafana** [comment] 2022-11-28 10:55
Had a look at this with team during weekly - it looks like this is more  related to how Grafana records traces. @grafana/backend-platform

**Comment by sakjur** [comment] 2022-12-02 15:55
> I would also like an explanation on why grafana automatically knew about jaeger if possible - is there some integration i'm not aware of?

The [[tracing.jaeger] configuration section](https://grafana.com/docs/grafana/v9.3/setup-grafana/configure-grafana/#tracingjaeger) has a note about that, `JAEGER_AGENT_HOST ` and `JAEGER_AGENT_PORT` are defined for the [Jaeger client](https://www.jaegertracing.io/docs/1.16/client-features/) as a way to send the hostname and port to Jaeger. This is done by the [github.com/jaegertracing/jaeger-client-go](https://github.com/jaegertracing/jaeger-client-go/blob/f5d688f78184a0a96249d1fc374dc3478ec3adaa/config/config_env.go#L207-L215) library we're using for the legacy (and deprecated in favor of OpenTelemetry) OpenTracing Jaeger client.

This seem to clash with [Kubernetes' service discovery by environment variables](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) where the `_PORT` seem to be a URL, and the Jaeger Helm chart defines a service called `jaeger-agent` which means that Kubernetes will create a `JAEGER_AGENT_PORT` environment variable.

Another workaround, other than setting environment variables for the Grafana container, seem to be to change `jaeger.agent.name` for the Jaeger charts.

IMHO we're unlikely to invest in fixing this behavior, it is not a bug in Grafana as much as Kubernetes and Jaeger using different definitions for the same environment variable. We would likely welcome a well-tested patch that provides a permanent workaround. Otherwise this will remai until OpenTracing is removed.

**Comment by tolzhabayev** [comment] 2023-01-26 19:18
closing (see explanation above)

**Closed by tolzhabayev** 2023-01-26 19:18 UTC
Labels: help wanted, prio/low, datasource/Jaeger, triage/needs-confirmation

**Comment by amanhigh** [comment] 2023-05-28 14:52
Small Correction `jaeger.agent.name` no longer works. Use `nameOverride: "foobar"` instead in the helm [chartsl](https://artifacthub.io/packages/helm/jaegertracing/jaeger).
