### ISSUE TITLE
Explore split view URLs don't persist left-hand side state

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#16106] opened 2019-03-20 11:21 UTC
Eg when loading https://admin-ops-tools1.grafana.net/grafana/explore?left=%5B%22now-6h%22,%22now%22,%22raintank-ops%22,%7B%22datasource%22:%22raintank-ops%22,%22target%22:%22perSecond(collectd.worldping-aks.cassandra.*.GenericJMX.cassandra_ClientRequest.counter.ReadLatency_count)%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D&right=%5B%22now-6h%22,%22now%22,%22ops-tools1%22,%7B%22expr%22:%22rate(node_disk_io_time_seconds_total%7Bcluster%3D%5C%22worldping-aks%5C%22%7D%5B5m%5D)%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

I expect:

<img width="1363" alt="Screenshot 2019-03-20 at 11 19 49" src="https://user-images.githubusercontent.com/444037/54680597-2720f580-4b02-11e9-9065-1c0f23da8302.png">

I get:

<img width="1363" alt="Screenshot 2019-03-20 at 11 20 33" src="https://user-images.githubusercontent.com/444037/54680622-36a03e80-4b02-11e9-84d1-3e9c95d63090.png">

**Comment by torkelo** [comment] 2019-03-20 11:35
dupe of https://github.com/grafana/grafana/issues/15862  (it's in the top of our todo column) , so should be fixed soon.

**Closed by torkelo** 2019-03-20 11:35 UTC
Labels: area/explore, type/bug
