### ISSUE TITLE
7.0.0-beta3: Clicking Links on dashboard settings throws "dashboard not found" error

### ISSUE THREAD

**Issue by AlexHeylin** [grafana/grafana#24767] opened 2020-05-16 23:42 UTC
**What happened**:
Working on dashboard imported from https://grafana.com/grafana/dashboards/12183 (seems well written)
Save dashboard. Go into dashboard settings and click Links. Get "Dashboard not found" error. See image for details. 
![grafana-700b3-links](https://user-images.githubusercontent.com/270973/82132395-36b7cf00-97d7-11ea-9a10-31bbe390758a.png)
This also occurs on other dashboards created from scratch in 7.0.0.b3

**What you expected to happen**:
Dashboard links tab to open normally

**How to reproduce it (as minimally and precisely as possible)**:
Create dashboard and save it. Click on Dashboard settings, then click links. Error will occur

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0 beta3
- Data source type & version: InfluxDB & TestData DB
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: 
AJAX
Alert List
Azure Monitor
Bar Gauge
CloudWatch
D3 Gauge
Dashboard list
Discrete
Elasticsearch
Gauge
Getting Started
Graph
Graphite
HTML
Heatmap
Home Links
InfluxDB
Jaeger
Logs
Loki
Microsoft SQL Server
MySQL
News Panel
OpenTSDB
Organisations
Plotly
Plugin list
Polystat
PostgreSQL
Prometheus
Singlestat
Stackdriver
Stat
Status Panel
Table
Table (old)
TestData DB
Text
Welcome
Worldmap Panel
Zipkin
- Others:

**Comment by zoltanbedi** [comment] 2020-05-17 11:44
Hi @AlexHeylin,
This issue is a duplicate of #24706 also fixed in our upcoming stable release.

**Closed by zoltanbedi** 2020-05-17 11:44 UTC

**Comment by AlexHeylin** [comment] 2020-05-17 12:39
Thanks. I did look for existing issue but must have missed it somehow.
