### ISSUE TITLE
[Feature Request] Adding Color Input Box

### ISSUE THREAD

**Issue by ericturnerit** [grafana/grafana#7009] opened 2016-12-19 20:51 UTC
Using Grafana v4.0.2.

Would love to be able to input a specific RGB color for the graphs and in the single stat color options. I'm able to get it done in developer tools in Chrome but would be nice to do it in app.

![2016-12-19 14_49_20-grafana - warehouse monitor](https://cloud.githubusercontent.com/assets/13255348/21328600/67c804fa-c5fa-11e6-9326-af28ac3ae5b8.png)

![2016-12-19 14_48_58-grafana - warehouse monitor](https://cloud.githubusercontent.com/assets/13255348/21328602/6d51c0b4-c5fa-11e6-8ec5-e77f82f86a49.png)

Thanks!

**Comment by mattttt** [comment] 2016-12-19 20:57
Hi @ericturnerit, tell me about it! This is an existing issue, and I completely agree it'd be an awesome feature.

Duplicate of https://github.com/grafana/grafana/issues/2322

**Closed** 2016-12-19 21:09 UTC
