### ISSUE TITLE
[Bug] Template variable in MySQL query incorrectly wrapped in quotes

### ISSUE THREAD

**Issue by marianzange** [grafana/grafana#9194] opened 2017-09-07 14:08 UTC
- What Grafana version are you using?
Grafana v4.5.0-beta1 (commit: bc69023)
- What datasource are you using?
MySQL
- What OS are you running grafana on?
grafana/grafana Docker Image
- What did you do?
I'm trying to use a template variable (type: query) to build a table name in a MySQL query for a singlestat panel like this: `SELECT count(*) as count from $tempVar`
- What was the expected result?
I expected that the template variable gets inserted into the SQL statement as is.
- What happened instead?
The value got inserted wrapped in single quotes (which makes it impossible to use for defining a table name in a regular query). So the rendered query here is: `SELECT count(*) as count from 'theValue'`. Interestingly, if I allow an "all" option with custom value of e.g. `customAllValue` in the template, this custom value is not wrapped in single quotes when selected: `SELECT count(*) as count from customAllValue`. I would expect to be able to use template variables in any way in my SQL query and not only as string values.

**Comment by torkelo** [comment] 2017-09-07 14:14
duplicate of https://github.com/grafana/grafana/issues/9030

**Closed by torkelo** 2017-09-07 14:14 UTC
