### ISSUE TITLE
Tool tip still remains in every page 

### ISSUE THREAD

**Issue by GokulSNarayan** [grafana/grafana#24181] opened 2020-05-02 11:19 UTC
![Screenshot from 2020-05-02 16-42-00](https://user-images.githubusercontent.com/44142590/80862694-c23c4680-8c94-11ea-9a95-5fb08e89cf5f.png)
![Screenshot from 2020-05-02 16-42-55](https://user-images.githubusercontent.com/44142590/80862697-c49ea080-8c94-11ea-80ff-6a06bed82f68.png)

**What happened**: The Tool tip does not disappear. It is present in everypage

**What you expected to happen**: After hovering over a graph the tooltip shows the data. After moving the mouse out of the graph the tool tip is not getting removed.

**How to reproduce it (as minimally and precisely as possible)**: Create a graph panel and hover on it.

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.7.2 (423a25fc32)
- Data source type & version:PSQL -10
- OS Grafana is installed on: Linux 18.04
- User OS & Browser:Chrome, Linux 20.04
- Grafana plugins: Graph
- Others:

**Comment by papagian** [comment] 2020-05-03 10:44
This is possibly a duplicate of #23881 for which there is a candidate fix.

@torkelo what do you think? Can we close this issue?

**Comment by torkelo** [comment] 2020-05-03 11:41
yes

**Closed by torkelo** 2020-05-03 11:41 UTC
