### ISSUE TITLE
Docker grafana/grafana:master "Error relocating" "symbol not found" on Raspberry Pi 4 (ARM)

### ISSUE THREAD

**Issue by mhansen** [grafana/grafana#23500] opened 2020-04-10 10:15 UTC
**What happened**:
Ran `grafana/grafana:master` on a Raspberry Pi 4. It keeps restarting, never comes up to serve requests.

Here's the logs:

```
pi@pi4b ~> docker logs dc_grafana_1 -f
Error relocating /usr/share/grafana/bin/grafana-server: __dlsym_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __lstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __localtime64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __gettimeofday_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __nanosleep_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __fstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __stat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __utimes_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __dlsym_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __lstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __localtime64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __gettimeofday_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __nanosleep_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __fstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __stat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __utimes_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __dlsym_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __lstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __localtime64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __gettimeofday_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __nanosleep_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __fstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __stat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __utimes_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __dlsym_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __lstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __localtime64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __gettimeofday_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __nanosleep_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __fstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __stat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __utimes_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __dlsym_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __lstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __localtime64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __gettimeofday_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __nanosleep_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __fstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __stat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __utimes_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __dlsym_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __lstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __localtime64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __gettimeofday_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __nanosleep_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __fstat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __stat_time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __time64: symbol not found
Error relocating /usr/share/grafana/bin/grafana-server: __utimes_time64: symbol not found
```

**What you expected to happen**:
Grafana to run (it runs on my raspberry pi using `grafana/grafana:latest`)

**How to reproduce it (as minimally and precisely as possible)**:
Get a raspberry pi
$ docker run `grafana/grafana:master`

**Anything else we need to know?**:

**Environment**:
- Grafana version:
The exact version:
```
~> docker inspect grafana/grafana:master | head
[
    {
        "Id": "sha256:44ad5f5b1cb432feaecc4bf030986d199fae9ee13f075e8394cf2a44687bc220",
        "RepoTags": [
            "grafana/grafana:master"
        ],
        "RepoDigests": [
            "grafana/grafana@sha256:d563421143765d62f5034a8d49149638950961e0f0000a6299ef0dbaf6a9788c"
        ],`
```

- OS Grafana is installed on:
```
pi@pi4b ~> uname -a
Linux pi4b 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
```

- User OS & Browser:
N/A - no browser involved
- Grafana plugins:
None
- Others:

**Comment by hugohaggmark** [comment] 2020-04-14 05:05
We're investigating this further @mhansen , thank you for reporting this.

**Comment by aknuds1** [comment] 2020-04-14 06:53
Confirmed - I can reproduce the problem. Thanks for letting us know!

**Comment by aknuds1** [comment] 2020-04-14 09:55
I think the errors are because of changes in musl v1.2.0, [affecting 32-bit systems](https://musl.libc.org/releases.html). We are probably on musl v1.2.0 with our cross compiler, so getting hit by this issue.

I've tried building a musl v1.1.24 based toolchain, but haven't been able to make that work :/ It fails like this:

```
$ GOOS=linux CC=~/Projects/musl-cross-make/output/bin/arm-linux-musleabihf-gcc GOARCH=arm GOARM=7 CGO_ENABLED=1 go build -ldflags '-w -X main.version=7.0.0-ed3eb382pre -X main.commit=95e635f154 -X main.buildstamp=1586847695 -X main.buildBranch=master' -o bin/linux-armv7/grafana-server ./pkg/cmd/grafana-server
# github.com/grafana/grafana/pkg/cmd/grafana-server
/usr/lib/go/pkg/tool/linux_amd64/link: running /home/arve/Projects/musl-cross-make/output/bin/arm-linux-musleabihf-gcc failed: exit status 1
/tmp/go-link-203284969/000009.o: In function `_cgo_try_pthread_create':
/usr/lib/go/src/runtime/cgo/gcc_libinit.c:110: undefined reference to `__nanosleep_time64'
/tmp/go-link-203284969/000025.o: In function `unixCurrentTimeInt64':
/home/arve/Projects/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:39100: undefined reference to `__gettimeofday_time64'
/tmp/go-link-203284969/000025.o: In function `unixDlSym':
/home/arve/Projects/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:38984: undefined reference to `__dlsym_time64'
/tmp/go-link-203284969/000025.o: In function `dotlockLock':
/home/arve/Projects/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:34847: undefined reference to `__utimes_time64'
/tmp/go-link-203284969/000025.o: In function `osLocaltime':
/home/arve/Projects/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:21509: undefined reference to `__localtime64'
/tmp/go-link-203284969/000025.o: In function `unixRandomness':
/home/arve/Projects/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:39024: undefined reference to `__time64'
/tmp/go-link-203284969/000025.o:(.data.rel+0x34): undefined reference to `__stat_time64'
/tmp/go-link-203284969/000025.o:(.data.rel+0x40): undefined reference to `__fstat_time64'
/tmp/go-link-203284969/000025.o:(.data.rel+0x148): undefined reference to `__lstat_time64'
```j

**Comment by aknuds1** [comment] 2020-04-14 11:44
I was able to build functioning binaries with a cross-compiler toolchain based on musl v1.1.24. Hopefully the problem will be resolved after my PR gets merged.

**Closed** 2020-04-14 14:59 UTC
Labels: type/bug, type/build-packaging

**Comment by aknuds1** [comment] 2020-04-14 17:10
Please try again, the current grafana/grafana-arm32v7-linux:master image works for me.

**Comment by sorriso93** [comment] 2023-09-01 22:16
Hello exact same error on raspberry pi 4 with 10.1.1, gettin back to 10.0.3 in the meantime

**Comment by HenryGessau** [comment] 2023-09-03 00:49
> Hello exact same error on raspberry pi 4 with 10.1.1, gettin back to 10.0.3 in the meantime

Me too 😢

**Comment by ndfred** [comment] 2023-09-06 19:59
Same here with version `10.1.1`, FYI to downgrade until this is fixed just run:
> $ sudo apt install grafana=10.0.5

**Comment by NSBrianWard** [comment] 2023-09-08 07:51
> FYI to downgrade until this is fixed just run:
> 
> > $ sudo apt install grafana=10.0.5

I hit the same issue. Thanks for your post! When I wanna go back to the current release after this issue is resolved, what's the syntax for that?

**Comment by yyovkov** [comment] 2023-09-18 14:39
+1 the same RPi 4

**Comment by ndfred** [comment] 2023-09-23 08:42
> I hit the same issue. Thanks for your post! When I wanna go back to the current release after this issue is resolved, what's the syntax for that?

That is easy to do by accident: just `apt update` then `apt full-upgrade` and you will revert back to the latest Grafana version. I had to reinstall the previous version again after doing that.
