### ISSUE TITLE
[bug] Timestamps in CSV export for UTC dashboard are in local time

### ISSUE THREAD

**Issue by svet-b** [grafana/grafana#11427] opened 2018-03-28 19:25 UTC
**What Grafana version are you using?** 5.0.1 
**What datasource are you using?** InfluxDB
**What OS are you running grafana on?** Linux

**What did you do?**
In a dashboard that's set to display charts in UTC, I did a CSV export. In the export, "Time Date Format" was kept set to the default `YYYY-MM-DDTHH:mm:ssZ`

**What was the expected result?**
I expected the CSV export to contain ISO 8601 timestamps in UTC, e.g. `2018-03-26T19:14:00Z`.

This is indeed the behavior on an older Grafana 4.3 instance I was running previously, from where this dashboard was imported.

**What happened instead?**
The CSV export contained timestamps in local time, including timezone offset. E.g. `2018-03-26T15:14:00-04:00`. Attempts to work around this, such as removing the `Z` from the "Time Date Format" simply removed the timezone offset (e.g. leaving `2018-03-26T15:14:00` in local time).

This behavior persists whether exporting series as rows or columns, and no matter whether "Excel CSV Dialect" is ticked or not.

This behavior is also described in https://github.com/grafana/grafana/issues/10497, but somehow tagged as a "feature request". I believe it to be a bug, based on the following factors:
- Probably unintended change in behavior with respect to Grafana 4
- `YYYY-MM-DDTHH:mm:ssZ` denotes the ISO 8601 format for UTC time. The `Z` should not ordinarily be interpreted as "timezone offset" - though I appreciate there is some ambiguity here

**Comment by svet-b** [comment] 2018-03-28 23:06
Just looked into this further. Looks like the change was actually implemented between 4.3 and 4.4.

_Before_ (https://github.com/grafana/grafana/blob/v4.3.x/public/app/core/utils/file_export.ts#L33):
```
dataArr[0][cIndex] = new Date(dp[1]).toISOString();
```

_After_ (https://github.com/grafana/grafana/blob/v4.4.x/public/app/core/utils/file_export.ts#L36):
```
dataArr[0][cIndex] = moment(dp[1]).format(dateTimeFormat);
```
I imagine there was some discussion on this at the time, and apologies for possibly having missed that, but I wanted to make sure this is indeed the intended functionality?

Unfortunately, with moment.js, it doesn't appear to be possible to force display of timestamps as UTC simply by adjusting the format string. And indeed, the `Z` format character simply translates to a numerical timezone offset (per https://momentjs.com/docs/#/displaying/format/).

I have a couple of suggestions of how to get around this, and wouldn't mind looking at submitting a PR if these sound attractive:
1) In export UI, add an option to convert the moment object to UTC (by applying `.utc()` method) prior to formatting to string.
2) As (1), but apply UTC conversion automatically if dashboard is set to display as UTC, and leave as local time otherwise
3) In export UI, add an option to convert to ISO string (by applying `.toISOString()` method), rather than `.format()`. This works as expected for moment objects, and recreates the 4.3 behavior.

**Comment by marefr** [comment] 2018-03-29 06:27
Confirmed that it doesn't take dashboard timezone into consideration. If that's a bug or lack of feature can be discussed. Maybe unintended support initially why the change to moment js didn't take this into account.   

Will close this as duplicate of #10497 and at the same time label that issue as bug instead.

Contributions are always welcome and we appreciate if you target #10497 then instead of this issue. Some recommendations for contributing:
* Should take dashboard timezone setting into consideration for creating csv file. If you search code base you'll find that dashboard.isTimezoneUtc() probably is what you want to use and that should be available in each panel.
* your changes need to take all core panels into considerations that have export to csv functionality
* file_export.ts and file_export.jest.ts are the files responsible for creating csv file - needs to take isUtc argument or similar
* export_data_modal.ts is the modal before export - needs to take isUtc argument or similar

Thanks for the report and good luck with the contribution!

**Closed by marefr** 2018-03-29 06:27 UTC
Labels: comp: panel/graph, type: bug

**Comment by svet-b** [comment] 2018-03-29 13:04
Thanks @marefr, appreciate the comprehensive guidance! I'll try to find a bit of time to write the patch.

In that respect, I also agree that the most sensible behavior would be to convert the moment.js object to UTC (or not) prior to `.format()`, depending on whether the dashboard is in UTC or not. In this scenario a user can get the ISO timestamp (i.e. same as output from `.toISOString()`) by specifying the format `YYYY-MM-DDTHH:mm:ss[Z]`, where `[Z]` turns into the literal letter Z rather than a timezone offset.

**Comment by marefr** [comment] 2018-03-29 13:35
So regarding moment and utc we're already using the following throughout the code base for formatting:

Utc format:
`moment.utc(<epoch>).format(...)`

Local time format:
`moment(<epoch>).format(...)`
