### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by Arslanbekov** [grafana/grafana#10099] opened 2017-12-06 10:50 UTC
**- What Grafana version are you using?**
4.6.2 (Docker)

**- What datasource are you using?**
graphite / prometheus 2.0.0 / elasticsearch 5.0

**- What OS are you running grafana on?**
Ubuntu 16.04.1 LTS, but Grafana run in Docker (Version: 1.12.3 / API version: 1.24)

Periodically Grafana docker container crash, i see this errors in logs:

```fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xecb5fa]

runtime stack:
runtime.throw(0x1278ff8, 0x2a)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 123 [syscall, locked to thread]:
runtime.cgocall(0xe8f800, 0xc420c7ad68, 0xc420c7ad90)
	/usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420c7ad38 sp=0xc420c7acf8 pc=0x408254
github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3._Cfunc_sqlite3_step(0x7f100c0252a8, 0x7f1000000000)
	github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:841 +0x49 fp=0xc420c7ad68 sp=0xc420c7ad38 pc=0x914db9
github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next.func1(0x7f100c0252a8, 0x8)
	/go/src/github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3.go:917 +0x60 fp=0xc420c7ada0 sp=0xc420c7ad68 pc=0x923030
github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next(0xc4211910e0, 0xc420643260, 0xe, 0xe, 0x124e86b, 0xc420c7afa0)
	/go/src/github.com/grafana/grafana/vendor/github.com/mattn/go-sqlite3/sqlite3.go:917 +0x5d fp=0xc420c7af30 sp=0xc420c7ada0 pc=0x91ecbd
database/sql.(*Rows).nextLocked(0xc420132c00, 0xc420c7afb0)
	/usr/local/go/src/database/sql/sql.go:2457 +0x70 fp=0xc420c7af80 sp=0xc420c7af30 pc=0x84f640
database/sql.(*Rows).Next.func1()
	/usr/local/go/src/database/sql/sql.go:2442 +0x3c fp=0xc420c7afb0 sp=0xc420c7af80 pc=0x85219c
database/sql.withLock(0x1c5eaa0, 0xc420132c30, 0xc420c7aff8)
	/usr/local/go/src/database/sql/sql.go:2855 +0x65 fp=0xc420c7afd8 sp=0xc420c7afb0 pc=0x8510f5
database/sql.(*Rows).Next(0xc420132c00, 0xc4207c3910)
	/usr/local/go/src/database/sql/sql.go:2441 +0x7a fp=0xc420c7b028 sp=0xc420c7afd8 pc=0x84f59a
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Session).rows2Beans(0xc42016b900, 0xc4205271c0, 0xc420643180, 0xe, 0xe, 0xe, 0xc42072c0f0, 0xc4205271e0, 0xc420c3e660, 0x0, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/session.go:299 +0x56 fp=0xc420c7b0f0 sp=0xc420c7b028 pc=0x8cc7c6
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Session).noCacheFind(0xc42016b900, 0xc42072c0f0, 0xfe5620, 0xc4205271a0, 0x197, 0xc42037a500, 0x24f, 0xc420bc9280, 0x4, 0x4, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/session_find.go:237 +0x7b5 fp=0xc420c7b218 sp=0xc420c7b0f0 pc=0x8e2d95
github.com/grafana/grafana/vendor/github.com/go-xorm/xorm.(*Session).Find(0xc42016b900, 0xfbd5e0, 0xc4205271a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-xorm/xorm/session_find.go:149 +0x56c fp=0xc420c7b3a8 sp=0xc420c7b218 pc=0x8e195c
github.com/grafana/grafana/pkg/services/sqlstore.(*SqlAnnotationRepo).Find(0x1e38f18, 0xc421191040, 0x4, 0x1e38f18, 0x0, 0x0, 0xc420327800)
	/go/src/github.com/grafana/grafana/pkg/services/sqlstore/annotation.go:196 +0x9d7 fp=0xc420c7b5a0 sp=0xc420c7b3a8 pc=0x98d7c7
github.com/grafana/grafana/pkg/api.GetAnnotations(0xc420bc8e00, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/pkg/api/annotations.go:28 +0x292 fp=0xc420c7b678 sp=0xc420c7b5a0 pc=0xdc57f2
runtime.call32(0xc420327800, 0x12b6f08, 0xc420527160, 0x800000018)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x3b fp=0xc420c7b6a8 sp=0xc420c7b678 pc=0x460fbb
reflect.Value.call(0x101ffa0, 0x12b6f08, 0x13, 0x1243c51, 0x4, 0xc420527140, 0x1, 0x1, 0x12350c0, 0x101ffa0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906 fp=0xc420c7b980 sp=0xc420c7b6a8 pc=0x4bf826
reflect.Value.Call(0x101ffa0, 0x12b6f08, 0x13, 0xc420527140, 0x1, 0x1, 0x11f9100, 0x1, 0xf32063)
	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420c7b9e8 sp=0xc420c7b980 pc=0x4bee04
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc420526720, 0x101ffa0, 0x12b6f08, 0x1c6b5e0, 0x101ffa0, 0x1, 0x5, 0x1000000004179f8, 0xc420415140, 0x8, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 +0x2c9 fp=0xc420c7ba98 sp=0xc420c7b9e8 pc=0x7d4539
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc420526720, 0x101ffa0, 0x12b6f08, 0x3, 0xc420415140, 0xc420f5fba0, 0x479c90, 0xc4200e1b80)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 +0xca fp=0xc420c7bb30 sp=0xc420c7ba98 pc=0x7d3e3a
github.com/grafana/grafana/pkg/api.wrap.func1(0xc420bc8e00)
	/go/src/github.com/grafana/grafana/pkg/api/common.go:37 +0x4c fp=0xc420c7bb80 sp=0xc420c7bb30 pc=0xdfeecc
runtime.call32(0xc420415140, 0xc4203785e0, 0xc4201362d0, 0x800000008)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x3b fp=0xc420c7bbb0 sp=0xc420c7bb80 pc=0x460fbb
reflect.Value.call(0x1001540, 0xc4203785e0, 0x13, 0x1243c51, 0x4, 0xc420527120, 0x1, 0x1, 0x12350c0, 0x1001540, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906 fp=0xc420c7be88 sp=0xc420c7bbb0 pc=0x4bf826
reflect.Value.Call(0x1001540, 0xc4203785e0, 0x13, 0xc420527120, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420c7bef0 sp=0xc420c7be88 pc=0x4bee04
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc420526720, 0x1001540, 0xc4203785e0, 0x1c6b5e0, 0x1001540, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 +0x2c9 fp=0xc420c7bfa0 sp=0xc420c7bef0 pc=0x7d4539
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc420526720, 0x1001540, 0xc4203785e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 +0xca fp=0xc420c7c038 sp=0xc420c7bfa0 pc=0x7d3e3a
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 +0x5e fp=0xc420c7c0b0 sp=0xc420c7c038 pc=0x7f154e
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 +0x36 fp=0xc420c7c0c8 sp=0xc420c7c0b0 pc=0x7f1486
github.com/grafana/grafana/pkg/middleware.RequestTracing.func1(0x7f101ea8e180, 0xc420bc8dc0, 0xc4209c6e00, 0xc420c5a750)
	/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 +0x454 fp=0xc420c7c1f0 sp=0xc420c7c0c8 pc=0xb97814
runtime.call32(0xc42039f560, 0xc420378620, 0xc420ef4920, 0x2000000020)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x3b fp=0xc420c7c220 sp=0xc420c7c1f0 pc=0x460fbb
reflect.Value.call(0x1081180, 0xc420378620, 0x13, 0x1243c51, 0x4, 0xc421190ff0, 0x3, 0x3, 0x12350c0, 0x1081180, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906 fp=0xc420c7c4f8 sp=0xc420c7c220 pc=0x4bf826
reflect.Value.Call(0x1081180, 0xc420378620, 0x13, 0xc421190ff0, 0x3, 0x3, 0x45a85d, 0x10a1420, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420c7c560 sp=0xc420c7c4f8 pc=0x4bee04
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc420526720, 0x1081180, 0xc420378620, 0x1c6b5e0, 0x1081180, 0x3, 0x4b5523, 0x10ef640, 0xd9220, 0x1002dc0, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 +0x2c9 fp=0xc420c7c610 sp=0xc420c7c560 pc=0x7d4539
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc420526720, 0x1081180, 0xc420378620, 0xa6f870, 0x2488095c, 0xc420f60700, 0x452d08, 0x26e03727f0695c)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 +0xca fp=0xc420c7c6a8 sp=0xc420c7c610 pc=0x7d3e3a
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 +0x5e fp=0xc420c7c720 sp=0xc420c7c6a8 pc=0x7f154e
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 +0x36 fp=0xc420c7c738 sp=0xc420c7c720 pc=0x7f1486
github.com/grafana/grafana/pkg/middleware.RequestMetrics.func1(0x7f101ea8e180, 0xc420bc8dc0, 0xc4209c6e00, 0xc420c5a750)
	/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 +0xb5 fp=0xc420c7c840 sp=0xc420c7c738 pc=0xb97095
runtime.call32(0xc42039f560, 0xc420378600, 0xc420874bc0, 0x2000000020)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x3b fp=0xc420c7c870 sp=0xc420c7c840 pc=0x460fbb
reflect.Value.call(0x1081180, 0xc420378600, 0x13, 0x1243c51, 0x4, 0xc421190fa0, 0x3, 0x3, 0x12350c0, 0x1081180, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906 fp=0xc420c7cb48 sp=0xc420c7c870 pc=0x4bf826
reflect.Value.Call(0x1081180, 0xc420378600, 0x13, 0xc421190fa0, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420c7cbb0 sp=0xc420c7cb48 pc=0x4bee04
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc420526720, 0x1081180, 0xc420378600, 0x1c6b5e0, 0x1081180, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 +0x2c9 fp=0xc420c7cc60 sp=0xc420c7cbb0 pc=0x7d4539
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc420526720, 0x1081180, 0xc420378600, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 +0xca fp=0xc420c7ccf8 sp=0xc420c7cc60 pc=0x7d3e3a
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 +0x5e fp=0xc420c7cd70 sp=0xc420c7ccf8 pc=0x7f154e
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 +0x36 fp=0xc420c7cd88 sp=0xc420c7cd70 pc=0x7f1486
github.com/grafana/grafana/pkg/middleware.Sessioner.func1(0xc420bc8e00)
	/go/src/github.com/grafana/grafana/pkg/middleware/session.go:79 +0x3b fp=0xc420c7cdf0 sp=0xc420c7cd88 pc=0xb97b9b
runtime.call32(0xc420415140, 0xc420348030, 0xc4201542e8, 0x800000008)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x3b fp=0xc420c7ce20 sp=0xc420c7cdf0 pc=0x460fbb
reflect.Value.call(0x1001540, 0xc420348030, 0x13, 0x1243c51, 0x4, 0xc4205270c0, 0x1, 0x1, 0x12350c0, 0x1001540, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906 fp=0xc420c7d0f8 sp=0xc420c7ce20 pc=0x4bf826
reflect.Value.Call(0x1001540, 0xc420348030, 0x13, 0xc4205270c0, 0x1, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420c7d160 sp=0xc420c7d0f8 pc=0x4bee04
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc420526720, 0x1001540, 0xc420348030, 0x1c6b5e0, 0x1001540, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 +0x2c9 fp=0xc420c7d210 sp=0xc420c7d160 pc=0x7d4539
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc420526720, 0x1001540, 0xc420348030, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 +0xca fp=0xc420c7d2a8 sp=0xc420c7d210 pc=0x7d3e3a
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 +0x5e fp=0xc420c7d320 sp=0xc420c7d2a8 pc=0x7f154e
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 +0x36 fp=0xc420c7d338 sp=0xc420c7d320 pc=0x7f1486
github.com/grafana/grafana/pkg/middleware.Recovery.func1(0xc420c5a750)
	/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 +0x51 fp=0xc420c7d360 sp=0xc420c7d338 pc=0xb96fb1
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.ContextInvoker.Invoke(0x12b72e0, 0xc420f4ba30, 0x1, 0x1, 0xc420c5a750, 0x16, 0xc420f61418, 0x45a85d, 0x10a1420)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 +0x51 fp=0xc420c7d388 sp=0xc420c7d360 pc=0x7f1331
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).fastInvoke(0xc420526720, 0x7f101ea8e1b8, 0x12b72e0, 0x1c6b5e0, 0x10b80e0, 0x1, 0xc4202c7180, 0xc420f61500, 0x417297, 0xc420526760, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 +0x264 fp=0xc420c7d420 sp=0xc420c7d388 pc=0x7d41f4
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc420526720, 0x10b80e0, 0x12b72e0, 0x4184ac, 0xc420526760, 0xc420f61648, 0x18, 0xc420f61538)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 +0x1bb fp=0xc420c7d4b8 sp=0xc420c7d420 pc=0x7d3f2b
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 +0x5e fp=0xc420c7d530 sp=0xc420c7d4b8 pc=0x7f154e
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 +0x36 fp=0xc420c7d548 sp=0xc420c7d530 pc=0x7f1486
github.com/grafana/grafana/pkg/middleware.Logger.func1(0x7f101ea8e180, 0xc420bc8dc0, 0xc4209c6e00, 0xc420c5a750)
	/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:33 +0x152 fp=0xc420c7d670 sp=0xc420c7d548 pc=0xb94b42
runtime.call32(0xc42039f560, 0x12b72c0, 0xc420a3c760, 0x2000000020)
	/usr/local/go/src/runtime/asm_amd64.s:509 +0x3b fp=0xc420c7d6a0 sp=0xc420c7d670 pc=0x460fbb
reflect.Value.call(0x1081180, 0x12b72c0, 0x13, 0x1243c51, 0x4, 0xc421190c80, 0x3, 0x3, 0x12350c0, 0x1081180, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906 fp=0xc420c7d978 sp=0xc420c7d6a0 pc=0x4bf826
reflect.Value.Call(0x1081180, 0x12b72c0, 0x13, 0xc421190c80, 0x3, 0x3, 0xc4200b18e8, 0xc420f61af8, 0xc4200b18d8)
	/usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420c7d9e0 sp=0xc420c7d978 pc=0x4bee04
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc420526720, 0x1081180, 0x12b72c0, 0x1c6b5e0, 0x1081180, 0x3, 0x417297, 0xc42067dcc0, 0x140, 0x130, ...)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 +0x2c9 fp=0xc420c7da90 sp=0xc420c7d9e0 pc=0x7d4539
github.com/grafana/grafana/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc420526720, 0x1081180, 0x12b72c0, 0x1c61fe0, 0xc420526720, 0x4, 0xc4201a5780, 0xc42067ddb0)
	/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 +0xca fp=0xc420c7db28 sp=0xc420c7da90 pc=0x7d3e3a
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420c5a750)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 +0x5e fp=0xc420c7dba0 sp=0xc420c7db28 pc=0x7f154e
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Router).Handle.func1(0x1c60ce0, 0xc420642fc0, 0xc4209c6e00, 0xc421205980)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 +0x2a3 fp=0xc420c7dc50 sp=0xc420c7dba0 pc=0x802d83
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Router).ServeHTTP(0xc420306480, 0x1c60ce0, 0xc420642fc0, 0xc4209c6e00)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:296 +0x14c fp=0xc420c7dcb0 sp=0xc420c7dc50 pc=0x7fd2fc
github.com/grafana/grafana/vendor/gopkg.in/macaron%2ev1.(*Macaron).ServeHTTP(0xc420572480, 0x1c60ce0, 0xc420642fc0, 0xc4209c6e00)
	/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 +0x138 fp=0xc420c7dd18 sp=0xc420c7dcb0 pc=0x7f5cf8
net/http.serverHandler.ServeHTTP(0xc420556270, 0x1c60ce0, 0xc420642fc0, 0xc4209c6e00)
	/usr/local/go/src/net/http/server.go:2619 +0xb4 fp=0xc420c7dd48 sp=0xc420c7dd18 pc=0x6928b4
net/http.(*conn).serve(0xc4202b4140, 0x1c619e0, 0xc420446000)
	/usr/local/go/src/net/http/server.go:1801 +0x71d fp=0xc420c7dfc8 sp=0xc420c7dd48 pc=0x68eb6d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420c7dfd0 sp=0xc420c7dfc8 pc=0x463801
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288

....


goroutine 3369391 [IO wait]:
internal/poll.runtime_pollWait(0x7f101e9b1d78, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421208098, 0x72, 0xffffffffffffff00, 0x1c5baa0, 0x1c54b78)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc421208098, 0xc420cd2000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc421208080, 0xc420cd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc421208080, 0xc420cd2000, 0x1000, 0x1000, 0x2, 0xc4205f3780, 0x5120f8)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420154800, 0xc420cd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc420ef9a10, 0x7f101e9ea000, 0xc420154800, 0x5, 0xc420154800, 0xc421183380)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420ff4700, 0x12b9217, 0xc420ff4820, 0x43420b)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420ff4700, 0xc420c46000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x110
net/http.(*persistConn).Read(0xc4203290e0, 0xc420c46000, 0x1000, 0x1000, 0xc420c60c40, 0xc4205592b8, 0x45d900)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc4208d3a40)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4208d3a40, 0x1, 0x0, 0x0, 0x1, 0xc4205ef020, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc4203290e0)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 3370453 [select]:
context.propagateCancel.func1(0x7f101ea8e500, 0xc42121e240, 0x1c5c2e0, 0xc420394d00)
	/usr/local/go/src/context/context.go:260 +0x113
created by context.propagateCancel
	/usr/local/go/src/context/context.go:259 +0x1da

goroutine 2071981 [chan receive, 1099 minutes]:
github.com/grafana/grafana/pkg/api/avatar.(*Thunder).init.func1(0x1c45920)
	/go/src/github.com/grafana/grafana/pkg/api/avatar/avatar.go:180 +0x42
created by github.com/grafana/grafana/pkg/api/avatar.(*Thunder).init
	/go/src/github.com/grafana/grafana/pkg/api/avatar/avatar.go:178 +0x90

goroutine 3369392 [select]:
net/http.(*persistConn).writeLoop(0xc4203290e0)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 2072354 [chan receive, 1099 minutes]:
github.com/grafana/grafana/pkg/api/avatar.(*Thunder).init.func1(0x1c45920)
	/go/src/github.com/grafana/grafana/pkg/api/avatar/avatar.go:180 +0x42
created by github.com/grafana/grafana/pkg/api/avatar.(*Thunder).init
	/go/src/github.com/grafana/grafana/pkg/api/avatar/avatar.go:178 +0x90

goroutine 3310669 [select]:
net/http.(*persistConn).writeLoop(0xc420d88ea0)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 3370349 [select]:
net/http/httputil.(*ReverseProxy).ServeHTTP.func1(0xc420410310, 0xc4203da590, 0x1c619e0, 0xc420ea01c0)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:154 +0xf2
created by net/http/httputil.(*ReverseProxy).ServeHTTP
	/usr/local/go/src/net/http/httputil/reverseproxy.go:153 +0xf1c

goroutine 3370429 [select]:
net/http/httputil.(*ReverseProxy).ServeHTTP.func1(0xc42107e4d0, 0xc4201d65a0, 0x1c619e0, 0xc4210346c0)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:154 +0xf2
created by net/http/httputil.(*ReverseProxy).ServeHTTP
	/usr/local/go/src/net/http/httputil/reverseproxy.go:153 +0xf1c

goroutine 3014907 [IO wait]:
internal/poll.runtime_pollWait(0x7f101ea85eb0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420139018, 0x72, 0xffffffffffffff00, 0x1c5baa0, 0x1c54b78)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420139018, 0xc420877000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420139000, 0xc420877000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc420139000, 0xc420877000, 0x1000, 0x1000, 0xc4210e7b00, 0x6890da, 0xc42089fa18)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420f997a8, 0xc420877000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*connReader).Read(0xc42089fa10, 0xc420877000, 0x1000, 0x1000, 0xc4210e7be8, 0x59182c, 0xc420139000)
	/usr/local/go/src/net/http/server.go:753 +0x105
bufio.(*Reader).fill(0xc420307da0)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc420307da0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x7f101ea85e00)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*conn).readRequest(0xc420eb06e0, 0x1c619e0, 0xc42014e900, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:930 +0xc77
net/http.(*conn).serve(0xc420eb06e0, 0x1c619e0, 0xc42014e900)
	/usr/local/go/src/net/http/server.go:1739 +0x50e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288

goroutine 3310647 [select]:
net/http.(*persistConn).writeLoop(0xc4210ade60)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

goroutine 3370089 [IO wait]:
internal/poll.runtime_pollWait(0x7f101ea857f0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420132d18, 0x72, 0xffffffffffffff00, 0x1c5baa0, 0x1c54b78)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420132d18, 0xc4209c4000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420132d00, 0xc4209c4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc420132d00, 0xc4209c4000, 0x1000, 0x1000, 0x43420b, 0xc420d8ea40, 0x45f8a0)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420136d48, 0xc4209c4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc420710900, 0xc4209c4000, 0x1000, 0x1000, 0xc420515770, 0xc420077678, 0x45d900)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc420f5d980)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc420f5d980, 0x1, 0x0, 0x0, 0x0, 0xc420558300, 0x0)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc420710900)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e```

**Comment by torkelo** [comment] 2017-12-06 15:50
duplicate of https://github.com/grafana/grafana/issues/9706 

Yes, seems some edge cases cause sqlite3 driver to crash the process. Can you describe more about your settings & usage pattern (OS & hardware, disk etc)

**Closed by torkelo** 2017-12-06 15:50 UTC

**Comment by dimovnike** [comment] 2017-12-21 11:59
I experience this issue too in the latest docker container.
