### ISSUE TITLE
Allowed cookies not forwarded to the datasource in variables query

### ISSUE THREAD

**Issue by pmint93** [grafana/grafana#60510] opened 2022-12-19 10:02 UTC
**What happened**:

Grafana did not forward cookies to the datasource in variables query, even when `Allowed cookies` configured

![image](https://user-images.githubusercontent.com/7886909/208398323-1f18658c-8b52-4786-af12-c1e6c68176e8.png)

**What you expected to happen**:

Grafana always forward `Allowed cookies` to the datasource

**How to reproduce it (as minimally and precisely as possible)**:

_We gonna use stackoverflow `prov` cookie to test Grafana cookies forward functionality_

1. Deploy [echoserver](https://hub.docker.com/r/ealen/echo-server) to act as datasource (which help inspect the request from Grafana)
2. Fake the domain whatever.stackoverflow.com: `echo "<grafana-ip> whatever.stackoverflow.com" >> /etc/hosts`
4. Login to grafana using domain `whatever.stackoverflow.com:3000` & Configure a datasource point to `echoserver` with `Allowed cookies=[prov]`
5. Import example dashboard [315-kubernetes-cluster-monitoring-via-prometheus](https://grafana.com/grafana/dashboards/315-kubernetes-cluster-monitoring-via-prometheus/) & View it
6. Check echoserver logs to see that requests to `/api/v1/label/kubernetes_io_hostname/values?` has no `prov` cookies with it

Additional diagram:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/7886909/208397025-735c2b94-1123-4c43-ae47-5bac8cea1c58.png">

**Anything else we need to know?**:

Same issue for some other APIs:

`/api/v1/query_exemplars`
`/api/v1/rules`

Related to issue https://github.com/grafana/grafana/issues/44250#issuecomment-1352705967

**Environment**:
- Grafana version: v9.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker image grafana/grafana-oss:v9.3.1
- User OS & Browser: OSX Chrome
- Grafana plugins: None
- Others:

**Comment by tonypowa** [comment] 2022-12-19 11:00
Thanks for creating this issue, @pmint93 

As indicated in  #44250 , I am forwarding this issue to the Metric's squad since the problem still is present in Grafana v9.3.1

**Comment by ajpauwels** [comment] 2023-01-28 17:30
Running into this same issue as well. The datasource gets added successfully without issue, but going to the /explore page leads to the `/prometheus/api/v1/metadata` call not having the cookie attached to it.

**Comment by itsmylife** [comment] 2023-02-08 11:42
I can confirm that it is fixed in `main` branch.
In `v9.3.x` branch it wasn't fixed. I will try to find the relevant commit.

**Comment by itsmylife** [comment] 2023-02-08 12:52
It was fixed with this PR https://github.com/grafana/grafana/pull/58132 
I am closing this issue. Upgrading to the most recent version of `v9.4.x` will fix the problem.

**Closed by itsmylife** 2023-02-08 12:52 UTC
Labels: prio/medium, datasource/Prometheus, needs investigation
