### ISSUE TITLE
MYSQL: datasource reporting incorrect interval

### ISSUE THREAD

**Issue by dtm7** [grafana/grafana#40665] opened 2021-10-20 04:11 UTC
We have been making use of the $__interval variable in a template variable linked to a mysql datasource (with a minimum interval of 10s configured).  This is to enable auto selection of influxdb retention policies based on both the time window of the data requested and also the interval/samplerate.

Up until grafana 8.1.7 this worked well, with the $__interval correctly replaced with what appeared to be the interval of a "full width" graph panel.

From grafana 8.2.0 this has changed, with the $__interval reported being out by a factor of 10-20.

I have a minimal test dashboard with only a template variable based on a mysql query. 

**What happened**:

These are the values reported for different time windows in v8.1.7:
Last 30m: 10s
Last 1h: 10s
Last 3h: 10s
Last 6h: 15s
Last 24h: 1m

And the same in v8.2.1:
Last 30m: 20s
Last 1h: 30s
Last 3h: 2m
Last 6h: 5m
Last 24h: 15m

**What you expected to happen**:

The $__interval reported by the mysql datasource to be the same as it was in 8.1.7 (and also consistent with the interval of a full-width panel).

**How to reproduce it (as minimally and precisely as possible)**:

Here is the JSON model of the dashboard we used to verify this behaviour. The grafana instance will need a mysql datasource configured.

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 51,
  "iteration": 1634688844012,
  "links": [],
  "panels": [],
  "schemaVersion": 30,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "1m",
          "value": "1m"
        },
        "datasource": "mysql (grafana RP map)",
        "definition": "select('$__interval')",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "Interval",
        "options": [],
        "query": "select('$__interval')",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Bug Report Dashboard Copy",
  "uid": "4AZpNAOnz",
  "version": 2
}
```

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: mysql
- OS Grafana is installed on: debian linux (10)
- User OS & Browser: windows 11 / firefox
- Grafana plugins:
- Others:

**Comment by dprokop** [comment] 2021-11-08 13:15
@ying-jeanne friendly ping :)

**Comment by dtm7** [comment] 2021-11-11 06:08
I spent a bit of time getting a build environment working, it's looking to me like the pull request that caused this behavioural change is #39036. I've managed to confirm that reverting the patch from v8.2.3 gets the old (correct?) behaviour back again.

**Comment by ivanahuckova** [comment] 2021-11-12 12:55
Hello @dtm7, the interval here has changed because we have replaced hard coded resolution (number of max points we want to receive) from 1600 to the value (maxDataPoints) sent from the visualisation. It is probable, that your graphs have smaller width than 1600px and therefore the interval is larger than before. However, this is more correct behaviour than using hard coded value of 1600 points for all sizes of graph.

**Comment by ivanahuckova** [comment] 2021-11-12 13:04
I am going to close this issue now as it seems to work as intended, but feel free to reopen if I am wrong and there is an issue with interval calculation.

**Comment by dtm7** [comment] 2021-11-15 22:22
HI @ivanahuckova - the dashboard JSON I pasted in before does not contain any panels. This issue is with using $__interval in a template query, not in a visualisation. The root of the issue seems to be  that there is a significant difference between the interval when used in a visualisation and that reported by the temple variable/query.

**Comment by ivanahuckova** [comment] 2021-11-16 09:38
Okay, I was able to investigate this and find the bug.  For template query, we are not setting `query.MaxDataPoints`. In this case, when query is run without `MaxDataPoints`, we default to `100` [here](https://github.com/grafana/grafana/blob/main/pkg/api/metrics.go#L57). And this causes incorrect calculation of interval [here in sql interval calculator](https://github.com/grafana/grafana/blob/main/pkg/tsdb/sqleng/sql_engine.go#L375). Passing this back to @grafana/grafana-bi-squad.

**Comment by zoltanbedi** [comment] 2021-11-16 09:43
Thanks for investigating this @ivanahuckova 🙏

**Comment by baldm0mma** [comment] 2023-02-02 15:28
Thanks everyone, I'll take a look into this!

**Comment by gabor** [comment] 2023-10-16 07:39
hi @dtm7 sorry for the late reply. after looking into this topic more, the current situation is intentional. i'll explain:
- first let's talking about writing a mysql query in a dashboard panel
    - if you use the `$__interval` variable in the query, it will be calculated based on two things:
       - A. the currently selected time range in grafana
       - B. the available space (pixels) in the panel (in other words, how wide the panel is). this is called `maxDataPoints`
- now consider a mysql query that is created as a dashboard variable
    - such a variable is global to the whole dashboard, so when evaluating this query, we do not know how much space there is, so we are not able to calculate `maxDataPoints`, so we go with a hardcoded default value.

for dashboard queries i recommend using a hardcoded value instead of `$__interval`, or perhaps calculating the value in SQL using the currently selected time range.

**Closed by gabor** 2023-10-16 07:39 UTC
Labels: type/bug, datasource/MySQL
