### ISSUE TITLE
Silences are not deleted automatically

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana#44321] opened 2022-01-21 13:52 UTC
**What happened**:
The bottom message at the silence's page states that 
> Expired silences are automatically deleted after 5 days.

But they are not.

![image](https://user-images.githubusercontent.com/25726917/150537861-11f11442-9840-4336-9148-5f44d1f76569.png)

**What you expected to happen**:
I want to clean my very long list of silences. 

**How to reproduce it (as minimally and precisely as possible)**:
Just use silences. Maybe

**Environment**:
- Grafana version: 8.3.3, NGAlert
- Data source type & version: any 
- OS Grafana is installed on: Centos 8
- User OS & Browser: any
- Grafana plugins:
- Others:

**Comment by joeblubaugh** [comment] 2022-03-18 04:44
I believe this is a duplicate of #41156

**Closed by joeblubaugh** 2022-03-18 04:44 UTC
Labels: area/backend, area/alerting/unified
