### ISSUE TITLE
Alerting: Show alerting support indicator on data source detail page

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#51581] opened 2022-06-29 16:24 UTC
Not every data source is compatible with Grafana Alerting; we annotate this in the plugin's `plugin.json` file with `{ "alerting": true }`.

We should be able to expose this in the UI to make it easier for users to spot if their data source is going to work or not.

For some background on what is required to be compatible with Grafana Alerting, see [this comment](https://github.com/grafana/grafana/issues/46347#issuecomment-1167236218).

**Comment by VikaCep** [comment] 2022-10-19 18:55
Seems like a duplicate of https://github.com/grafana/grafana/issues/51484, right?

**Comment by VikaCep** [comment] 2022-10-20 17:00
Looks like it is, so closing it. Please reopen if I'm wrong.

**Closed by VikaCep** 2022-10-20 17:00 UTC
Labels: area/alerting, beginner friendly, area/frontend, kind/enhancement
