### ISSUE TITLE
Automatic unit conversion when value is 0

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#50868] opened 2022-06-15 11:33 UTC
**What happened**:
After upgrading from 9.0.0-beta3 to 9.0.0 (stable), all length units (km, mm) are automatically converted to fm when the value is 0.0.
![image](https://user-images.githubusercontent.com/19311511/173817083-c6df59fc-a609-4fc9-8c1b-0916c289bb8d.png)

**What you expected to happen**:
It would be much better if the unit would stay the same (for example millimeters)

**Anything else we need to know?**:
Another issue is that before Grafana 9.0.0, I was using μSv/h unit with values in the range of 0.09 - 0.2. Before Grafana 9.0.0 the unit stayed the same, however since 9.0.0 it is converted to nSv/h.
Is there any way to disable unit conversion at all?

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: InfluxDB 2.2.0
- OS Grafana is installed on: Debian
- User OS & Browser: Opera GX

**Comment by gelicia** [comment] 2022-06-15 12:15
Duplicate of https://github.com/grafana/grafana/issues/50836

**Closed by gelicia** 2022-06-15 12:15 UTC
