### ISSUE TITLE
Function ToolTip disappear quickly (ie Query->Functions->delete or move function)

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#26066] opened 2020-07-04 16:18 UTC
**What happened**:

Has been issue since grafana 4 -> 7.0.3 (but has gotten a tad better),  
To delete or move a Query's function, you have to click the function and you get a popup/tooltip with the delete or move left/right arrows.  This tooltip has always been very difficult to click upon as it often quickly disappears.

Its as if you have to be very quick with the cursor to get it to stay showing (and even then sometimes it disappears still)
(i have searched google extensively and cant find reports of this, so maybe its something on my end?)
Please see screen capture below.
Thanks

![grafana2](https://user-images.githubusercontent.com/60830628/86516614-c0ebdf00-bde7-11ea-9577-33b8afeb0240.gif)

**Environment**:
Environment:

Grafana version: 7.0.3
Data source type & version: Graphite v0.9.12
OS Grafana is installed on:
lsb_release -a
Description: Debian GNU/Linux 8.11 (jessie)
Release: 8.11
Codename: jessie

User OS & Browser:
Chrome: 81.0.4044.138 Win10
Grafana plugins:
Carpetmap (but not used)
Others:

**Comment by papagian** [comment] 2020-07-06 06:24
I'm able to reproduce it if the window is too small.

**Comment by torkelo** [comment] 2020-07-06 11:29
duplicate of https://github.com/grafana/grafana/issues/21177

**Closed by torkelo** 2020-07-06 11:29 UTC
Labels: datasource/Graphite, type/accessibility, type/bug
