### ISSUE TITLE
Cyrillic values in dashboard data link parameters are not substituted

### ISSUE THREAD

**Issue by jfk9w** [grafana/grafana#33096] opened 2021-04-18 07:59 UTC
**What happened**:
I have a Table panel which pulls data from PostgreSQL database. Most values in the column A of the table are cyrillic. I want to setup a data link to another dashboard using column A values as a parameter. But cyrillic values are not getting inserted into the data link.

**What you expected to happen**:
Data links are created with substituted cyrillic parameter values.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Table with one column and two rows, "Test" and "Тест". Try to create a data link with values from these rows.

**Anything else we need to know?**:
This is probably the case for cyrillic values in all panels, not just tables. I'm not sure though.

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: Ubuntu Server 20.04
- User OS & Browser: Mac OS Big Sur, Firefox 87.0
- Grafana plugins: none
- Others: -

**Comment by hugohaggmark** [comment] 2021-04-19 09:37
Reproduced here https://play.grafana.org/d/sdiNosuGz/cyrillic-values-in-dashboard-data-link-parameters-are-not-substituted-33096?orgId=1

**Comment by hugohaggmark** [comment] 2021-04-19 09:45
Fine until locationUtli.processUrl here
https://github.com/grafana/grafana/blob/41f6af96c4e50cb9b72692f8141f75dea92c7171/packages/grafana-data/src/field/fieldOverrides.ts#L405

Caused by https://github.com/braintree/sanitize-url that sanitizes the url when `disable_sanitize_html` is not set to `true`. `braintree/sanitize-url` have an open issue and PR here that will solve this: 
https://github.com/braintree/sanitize-url/issues/31 
https://github.com/braintree/sanitize-url/pull/32

We should await that fix and update our version of `braintree/sanitize-url` when this gets merged.

**Closed** 2021-04-30 08:13 UTC
Labels: area/field/overrides, area/panel/table, type/bug
