### ISSUE TITLE
[Feature request] Alert only at specific time

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#6962] opened 2016-12-14 21:14 UTC
Please include this information:
- What Grafana version are you using?
4.0.2
- What datasource are you using?
Elasticsearch, Graphite
- What OS are you running grafana on?
CentOS 6.6

It would be great if we could alert only at specific time. So in my example we need to alert during production hours but do not care about metric after certain time until next day. We use scripts where we specifically check for time and stop alerting if time is outside production window. Having this feature in Grafana would greatly improve our workflow.

**Comment by torkelo** [comment] 2016-12-14 21:20
duplicate of https://github.com/grafana/grafana/issues/6592

**Closed by torkelo** 2016-12-14 21:20 UTC
