### ISSUE TITLE
Dashboards: Polystat breaks when my mouse pointer moves to other Polystats 

### ISSUE THREAD

**Issue by phantazia** [grafana/grafana#73408] opened 2023-08-17 14:47 UTC
### What happened?

![CapturePolystat](https://github.com/grafana/grafana/assets/10875701/604dd989-8825-4aa2-b031-df5e9cb339c6)
’ve noticed an error, it seems to be a bug, on Polystat, I’m getting randomly an error Cannot read properties of undefined (reading 'color')
Thanks in advance for your feedback

More details about the reporting bug, it appears when the mouse pointer moves over other Polystats that have more than one element (for my case)

```
![CapturePolystat](https://github.com/grafana/grafana/assets/10875701/219b5412-ef19-4243-bd33-c634aae721a1)
```

### What did you expect to happen?

Nothing

### Did this work before?

yes, and still working on older version

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana: 10.0.3
OS: redhat 8
Browser: all

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

prometheus

**Comment by alwaysshrek** [comment] 2023-08-18 14:54
Also facing this on my grafana cloud hosted dashboard with polystat panels. Below are the versions:

Grafana cloud : v10.2.0-59422pre (25690811)
Plugin version : 2.1.2
Browser : Chrome Version 115.0.5790.170 (Official Build) (arm64)

Seems to be related to this issue in the plugin repo: https://github.com/grafana/grafana-polystat-panel/issues/288

**Comment by mellieA** [comment] 2023-08-21 22:05
@phantazia can you confirm if you're also using repeating rows with your use case?

For now, I'll close this as a duplicate of the issue that @alwaysshrek pointed to. If that's not the case please open a new issue and reference this one.

**Closed by mellieA** 2023-08-21 22:05 UTC
Labels: type/duplicate
