### ISSUE TITLE
Time correction (browser/UTC)

### ISSUE THREAD

**Issue by isj4** [grafana/grafana#2383] opened 2015-07-21 21:42 UTC
Background:
Our data is stored in UTC.
The data is from multiple timezones (EST and PST currently).
Users live in EST and PST. I live in CET. System logs are in UTC.
So the per-dashboard configuration of browser/UTC doesn't work too well for us.
What we currently do is configure the dashboards to use browser timezone. That works for the majority of users.
When I have to look at the graphs correlating something with system logs I change the dashboard setting to UTC but don't save.

I'm not sure what the best approach is, but perhaps an easier way to select the time correction, or perhaps a per-user override.

**Comment by damm** [comment] 2015-07-21 22:09
Are you using Graphite? sounds like you should switch Graphite to storing in UTC

**Comment by isj4** [comment] 2015-07-22 10:38
I'm using OpenTSDB and data is stored in UTC.

**Comment by damm** [comment] 2015-07-22 19:44
Then your data should be returned to Grafana in UTC; and using local or UTC time should be correct (at least my experience with Graphite/InfluxDB this is the case).

**Comment by isj4** [comment] 2015-07-22 20:58
Yes, the data is returned to grafana in UTC.
The problem is that the browser/UTC selection is stored per dashboard, so each time I ahve to change it without saving it. I cannot save the setting because that would make the ordinary users unhappy/confused.

**Comment by damm** [comment] 2015-07-22 23:06
Sounds like you need a userscript to override this for yourself then?

**Comment by bcmackey** [comment] 2015-07-23 16:56
I would also like to request a per-user override for the browser/UTC behavior that can currently be saved per dashboard

**Comment by torkelo** [comment] 2015-07-23 17:06
yea, I agree, this should be an option to set default on org level and user level, dupe of #1200

**Closed by torkelo** 2015-07-23 17:06 UTC
