### ISSUE TITLE
In the Loki Explore window, a label called EventName does not return label suggestions

### ISSUE THREAD

**Issue by andersosthus** [grafana/grafana#44037] opened 2022-01-14 12:14 UTC
**What happened**:
Label value suggestion does not work in Loki Explore with a label called `EventName`. When looking in my network tab, I see the request as this: `https://.../grafana/api/datasources/proxy/10/loki/api/v1/label/ventName/values?start=1642158574236000000&end=1642162174236000000`. Notice it does the request for `ventName`, not `EventName`.

I also see that the `E` in `EventName` is colored differently in the Loki query window:
![image](https://user-images.githubusercontent.com/184104/149513293-4091f61f-eda2-4eb5-91ff-59c5b8b855c5.png)

**What you expected to happen**:
To get label suggestions.

**How to reproduce it (as minimally and precisely as possible)**:
Do the following Loki query: `{EventName=""}`. Observe the network that that the request is done for a label called `ventName`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Loki
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Windows 10 - Firefox 96.0
- Grafana plugins: vonage-status-panel, grafana-piechart-panel, grafana-polystat-panel

**Comment by ifrost** [comment] 2022-01-17 08:20
This might be caused by incorrect regex for label matching [here](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/syntax.ts#L196). Prometheus shouldn't have this problem as it parses the syntax tree instead of using regex.

**Comment by andersosthus** [comment] 2022-01-17 15:07
Based on that regex, no labels that start with a capital letter will work. I do see that in all the Loki docs, labels always start with a lowercase letter, but I don't see either anything that this is recommended/required, so while it might be good practice/expected, I do believe the data source should support labels starting with a capital letter ?

I could always rewrite my labels to start with a lowercase letter, but this should probably still be addressed either with a fix, or a note in the data source doc that it's not fully functional if using labels that start with a capital letter.

**Comment by gabor** [comment] 2022-02-07 12:29
duplicate of https://github.com/grafana/grafana/issues/42573

**Closed by gabor** 2022-02-07 12:29 UTC
Labels: type/bug, datasource/Loki, area/query-editor
