### ISSUE TITLE
Fix Fastpass issues for Cloud Monitoring

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#41907] opened 2021-11-18 15:59 UTC
(just making a separate ticket for #41206 for easier tracking of this work on our board)

**Comment by vickyyyyyyy** [comment] 2022-01-11 15:32
dupe of https://github.com/grafana/grafana/issues/42710 and https://github.com/grafana/grafana/issues/42709

**Closed by vickyyyyyyy** 2022-01-11 15:32 UTC
Labels: datasource/GoogleCloudMonitoring
