### ISSUE TITLE
Postgres Query Error using Template Variables

### ISSUE THREAD

**Issue by gschwel** [grafana/grafana#13719] opened 2018-10-17 18:14 UTC
- v.  5.3.1
- Postgres
-Debian 
Using variables to define other variables is broken post upgrade to v. 5.3.1 for the Postgres datasource only.  This appears to be only happening in one dashboard.
Receiving error "Template variables could not be initialized: a is undefined.

![screen shot 2018-10-17 at 1 13 25 pm](https://user-images.githubusercontent.com/43280561/47107263-776ff080-d20e-11e8-9d82-641f2f5b05ac.png)

<img width="1318" alt="screen shot 2018-10-17 at 1 10 01 pm" src="https://user-images.githubusercontent.com/43280561/47107241-69ba6b00-d20e-11e8-9f16-c86f9ca6ba5c.png">

**Comment by marefr** [comment] 2018-10-17 22:45
Duplicate of #13692

**Comment by marefr** [comment] 2018-10-17 22:45
Fix will be included in v5.3.2

**Closed by marefr** 2018-10-17 22:45 UTC
