### ISSUE TITLE
Autocomplete does not work on incomplete input

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#20445] opened 2019-11-18 14:41 UTC
**What happened**:

I type query in explore-loki:
![ac](https://user-images.githubusercontent.com/291750/69061582-b7a93000-0a19-11ea-8be0-1cfd6dd91054.png)

Autocomplete does not happen unless I first close with `"}`

**What you expected to happen**:

Grafana autocompletes my query

**Environment**:
- Grafana version: 6.4.4
- OS Grafana is installed on: linux
- User OS & Browser: linux firefox

**Comment by hugohaggmark** [comment] 2019-11-19 06:32
Thanks @roidelapluie for reporting this but I think that this is by design. When you first enter a query you automatically get `{}` and you're suppose to write your query inside those. But I'll see what we can do.

**Comment by Estrax** [comment] 2020-04-28 19:53
Not a bug, but more of a feature request (non-critical, but nice to have). Added a relevant label.

The main question is: do we want to support that behavior? If so, what would be the best solution for that? My initial idea was to tokenize query expression and count opening tags, so then we can add an exact number of closing tags at the end of query expression (of course in the correct order, using a simple AST), when passing the context to typeahead, so typeahead treats input as syntactically correct.
The more I think of that, the more I start thinking it's kinda overkill for that problem.
@davkal @aocenas wdyt?

**Comment by aocenas** [comment] 2020-04-28 19:59
tbh I don't agree this is a feature request. The autocomplete should not stop working just because you don't have the closing bracket. I think there could be simple solution as I assume we are just checking where in the expression we are and we check whether we are inside a `{}` but it should be possible to say event starting `{` bracket means we are inside a labels expression.

**Closed** 2021-01-08 17:31 UTC
Labels: datasource/Prometheus, type/bug
