### ISSUE TITLE
No way to properly display AWS ECS running task counts

### ISSUE THREAD

**Issue by maxblaze** [grafana/grafana#15430] opened 2019-02-14 01:00 UTC
### What Grafana version are you using?
5.4.3
### What datasource are you using?
CloudWatch
### What OS are you running grafana on?
Linux
### What did you do?
Selected an ECS cluster, service, CPUUtilization, and SampleCount to get the ECS running task count, which isn't a "real" metric on CloudWatch. The only way to get it is by using the sample count: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#cw_running_task_count
### What was the expected result?
We should see a task count graph, with the Y-axis having no units
### What happened instead?

When selecting CPUUtilization, it seems like the units are fixed on percentage and can't be changed:
<img width="739" alt="screen shot 2019-02-13 at 7 47 30 pm" src="https://user-images.githubusercontent.com/7468245/52754832-e3e6da80-2fc9-11e9-8f5f-915a32e1f3a2.png">

This results in a percentage Y-axis even though it should be a count:
<img width="966" alt="screen shot 2019-02-13 at 7 47 20 pm" src="https://user-images.githubusercontent.com/7468245/52754842-e9442500-2fc9-11e9-967f-255729ae82da.png">

Note that this worked fine in 4.x

**Comment by marefr** [comment] 2019-02-14 09:30
Duplicate of #13733

**Closed by marefr** 2019-02-14 09:30 UTC

**Comment by maykonlopes41** [comment] 2019-07-31 20:19
> ### What Grafana version are you using?
> 5.4.3
> 
> ### What datasource are you using?
> CloudWatch
> 
> ### What OS are you running grafana on?
> Linux
> 
> ### What did you do?
> Selected an ECS cluster, service, CPUUtilization, and SampleCount to get the ECS running task count, which isn't a "real" metric on CloudWatch. The only way to get it is by using the sample count: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#cw_running_task_count
> 
> ### What was the expected result?
> We should see a task count graph, with the Y-axis having no units
> 
> ### What happened instead?
> When selecting CPUUtilization, it seems like the units are fixed on percentage and can't be changed:
> <img alt="screen shot 2019-02-13 at 7 47 30 pm" width="739" src="https://user-images.githubusercontent.com/7468245/52754832-e3e6da80-2fc9-11e9-8f5f-915a32e1f3a2.png">
> 
> This results in a percentage Y-axis even though it should be a count:
> <img alt="screen shot 2019-02-13 at 7 47 20 pm" width="966" src="https://user-images.githubusercontent.com/7468245/52754842-e9442500-2fc9-11e9-967f-255729ae82da.png">
> 
> Note that this worked fine in 4.x

Hi @maxblaze , how do you do the configuration to collect number of tasks in a ecs cluster with grafana? I tried some options without success. I'm in grafana version 6.2.5.
