### ISSUE TITLE
Grafana Logs Explore unnecessary re-renders 

### ISSUE THREAD

**Issue by yandingkang** [grafana/grafana#41849] opened 2021-11-18 02:50 UTC
**What happened**:
After a large amount of logs were displayed on chrome(e.g 10000 lines),when I scroll my mouse to see more logs,the UI became very slow.
Here is a Chrome Performance profile recording:
[Profile-20211118T104523.zip](https://github.com/grafana/grafana/files/7559492/Profile-20211118T104523.zip)

**What you expected to happen**:
Once the result was shown on chrome, the UI performance should be in a normal manner.
**How to reproduce it (as minimally and precisely as possible)**:
1.Open Grafana Explore
2.Select Loki datasource
3.Type a query which will display a large amount of logs e.g 10000lines
4.UI becomes slow
**Anything else we need to know?**:
I think this problem is related to re-render.In my gif,we can see the whole page was rerendered once I scroll my mouse.
**Environment**:
- Grafana version: Grafana v8.2.1 (88622d7f09)
- Data source type & version: Loki,v2.3.0
- OS Grafana is installed on: K8s
- User OS & Browser: Win10,Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- Grafana plugins:
- Others
![chrome-capture](https://user-images.githubusercontent.com/76470592/142341743-6a31efe7-db1d-4a12-bc81-d97b276a9a76.gif)
:

**Comment by ivanahuckova** [comment] 2021-11-24 14:14
Hello @yandingkang. I wasn't able to reproduce this issue. As you can see in the recording below, the log rows don't re-render on scroll. Nothing is re-rendered on scroll. I was only able to reproduce that TooltipPlugin re-renders when your mouse goes over graph, but, that is expected.

The fact that your UI is slower is due to the. fact that you are rendering 10000 logs. We recommend to render less (~1000) and either use pagination or improve filtering. 

https://user-images.githubusercontent.com/30407135/143251022-e609e17a-0091-4955-84d0-a25c0c963e3f.mov

**Comment by yandingkang** [comment] 2021-11-30 03:23
@ivanahuckova Hello, it is surprising that everything goes well in your recording. So I want to know which version of grafana did you use ? And how did you deploy your grafana? In my case , grafana was installed by helm on k8s.Thanks.

**Comment by ivanahuckova** [comment] 2021-12-01 17:13
I have checked this on main build but also on https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22nginx_access_log%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D which is on 8.2.5

**Comment by yandingkang** [comment] 2021-12-03 09:24
@ivanahuckova Sorry to disturb you.I tried the above website you mentioned and saved an recording. This time I set the line limit to 1000 rows.In my recording, when I scrolled the page, a lot of elements were repainted. And I used Chrome's tool which could display 'scrolling performance issues' things.Then you can see the text 'repaints on scroll' in the upper left corner. So I feel very confused about the differences between our results.Is it related to the browser? Hope you can find out the reason.
![repaints-on-scroll](https://user-images.githubusercontent.com/76470592/144578338-d5cc7c60-cf72-4810-b820-375413bfca8d.png)
[Explore - Loki - Grafana - Google Chrome 2021-12-02 10-37-58.zip](https://github.com/grafana/grafana/files/7648251/Explore.-.Loki.-.Grafana.-.Google.Chrome.2021-12-02.10-37-58.zip)

**Comment by ivanahuckova** [comment] 2022-01-04 11:18
I don't see repaints on scroll warning in Chrome neither. :( 
![image](https://user-images.githubusercontent.com/30407135/148051469-f18c0056-af8f-45ec-b7e3-3b073aa4d6c1.png)

**Comment by ivanahuckova** [comment] 2022-01-05 16:36
I am going to close this in favour of https://github.com/grafana/grafana/issues/43261

**Closed by ivanahuckova** 2022-01-05 16:36 UTC
Labels: type/performance, needs investigation, area/explore
