### ISSUE TITLE
db2 support

### ISSUE THREAD

**Issue by blenard81** [grafana/grafana#21884] opened 2020-01-31 22:53 UTC
We would like to see support for DB2.  We use DB2 BLU for our scientific data, and would like to see Grafana as a front end.  IBM has a Go driver on Github.  

If you don't want to do this, please give me an example of how to write a backend plugin that'll be accepted when we push it up.  Thanks!

**Comment by DavidJesus03** [comment] 2020-02-01 05:14
+1

**Comment by marefr** [comment] 2020-02-01 11:40
Duplicate of #9682

**Closed by marefr** 2020-02-01 11:40 UTC
