### ISSUE TITLE
Sharing an image of the WorldMap panel omits the background

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#15617] opened 2019-02-23 10:37 UTC
### What Grafana version are you using?

Grafana v5.4.3 (6539180)

### What datasource are you using?

MySQL

### What OS are you running grafana on?

Ubuntu Linux 16.04

### What did you do?

Tried to share a WorldMap panel as an image. (Click on panel title -> Share ->Direct link rendered image)

### What was the expected result?

I expected to get an image looking exactly as the panel.

### What happened instead?

The image lacked the world map background; it contained only the visualized data spots, as shown below. Not sure if this is a problem of Grafana or of the WorldMap plug-in specifically. I don't have this problem when obtaining images from other kinds of panels - but, then, they don't have such backgrounds.

![map](https://user-images.githubusercontent.com/580507/53285296-9dcb0d00-3767-11e9-968f-c45c2e5b1822.png)

**Comment by xlson** [comment] 2019-02-26 13:15
@daniellee Where should we track this issue?

**Comment by torkelo** [comment] 2019-04-01 13:21
duplicate of https://github.com/grafana/worldmap-panel/issues/147

**Closed by torkelo** 2019-04-01 13:21 UTC
Labels: needs investigation

**Comment by huangyuan666** [comment] 2019-06-27 10:48
Hello, author, can you put the tile map server locally?
