### ISSUE TITLE
Explore: graph is not rendered when a graphite metric query is pasted into the editor

### ISSUE THREAD

**Issue by yunkaisc** [grafana/grafana#48145] opened 2022-04-22 23:35 UTC
**What happened**:
When a graphite metric query is pasted into the editor, the corresponding graph is not rendered or probably the pasted query is not part of the request that got sent to the data source. This is different from a query that is typed into the editor. When the query is typed into the editor, the graph will automatically get rendered.
Additionally, it looks like the query is not saved locally. When the enable/disable button is clicked, the pasted query just disappears.  On the contrary typed-in queries won't disappear.

**What you expected to happen**:
Should work the same as typed queries,
1. Graph would be rendered after the metrics query is pasted
2. Query should not disappear, 

**How to reproduce it (as minimally and precisely as possible)**:
1. Open https://play.grafana.org/explore
2. Type in `apps.backend.backend_01.counters.requests.count`
3. Copy `apps.backend.backend_01.counters.requests.count`
4. Click Add query
5. Paste `apps.backend.backend_01.counters.requests.count` to Query B, the graph for query B will not render
6. Click disable, the query disappears.

**Anything else we need to know?**:
It worked in Grafana v7. It stopped working since we upgraded to Grafana v8. This issue is reproducible on play.grafana.org.

**Environment**:
- Grafana version: we are on v8. The screen shot is using play.grafana.org
- Data source type & version: graphite plugin
- OS Grafana is installed on: play.grafana.org
- User OS & Browser: Fireforx & Chrome both have same issue
- Grafana plugins: graphite datasource plugin
- Others: 

![Kapture 2022-04-22 at 16 19 01](https://user-images.githubusercontent.com/97200680/164817030-c515ee45-f163-4fa0-b2b6-d4e9ddaa1fe5.gif)

**Comment by nikobearrr** [comment] 2022-04-23 09:39
I would like to add my observations regarding this:
When using graphite datasource it sometimes happens that when I edit some series they do not get "saved". What I mean by that is it shows I have sellected `[apps][backend][*][whatever]` but it doesn't seem to use it. The workaround I have found is:
1. switch to use the raw editor
2. paste the query I want to edit
3. press ctrl+enter
4. press grafana's refresh button
5. query will execute
6. remove the new line created in step 3
7. save

To me it seems something related to how grafana verifies the queries and how it is triggering to new changes.


This may or may not be related to the issue @yunkaisc has explained

**Comment by mellieA** [comment] 2022-04-27 23:02
@yunkaisc thank you for reporting this. I tried and wasn't able to reproduce it, so I've asked for someone else to try.

**Comment by mellieA** [comment] 2022-04-28 23:35
@yunkaisc I think I reproduced a variation of this, let me know if this is what you're seeing: 

* in explore with the graphite datasource, build the query or paste the query `apps.backend.backend_01.counters.requests.count` into the raw query editor and query A graph will appear: 

![Screen Shot 2022-04-28 at 5 21 45 PM](https://user-images.githubusercontent.com/18175287/165863106-d667d81f-5d93-45fd-804f-2cc55cfe8bb6.png)


* click the **duplicate query** icon ![Screen Shot 2022-04-28 at 5 22 53 PM](https://user-images.githubusercontent.com/18175287/165863202-12f15a84-3751-477c-a649-d199228b4bcb.png) 

query B is created, click outside the editing box, no new graph appears: 

![Screen Shot 2022-04-28 at 5 24 05 PM](https://user-images.githubusercontent.com/18175287/165863308-c53b20ea-ebeb-471c-a98b-930d14fbc24c.png)

This does seem related to a refresh. If you click the **run query** button, all of the queries load. It also loads all of the queries on refresh if you choose a refresh interval from the drop-down on the **run query** button. 

* If I choose **add query** and click the pencil icon to go into raw editor mode > copy/paste the query from the line above > click outside of the editing box, the query result automatically graphs immediately


![Screen Shot 2022-04-28 at 5 34 36 PM](https://user-images.githubusercontent.com/18175287/165864196-66c5e353-8a21-44bf-b5f1-e792d88ad041.png)

**Comment by mellieA** [comment] 2022-04-28 23:39
NOTE: I also reproduced this with the TestDataDB data using the CSV metric values query and duplicating it with the duplicate icon so it's labeled for **explore** and not specific to graphite

**Comment by yunkaisc** [comment] 2022-04-29 16:59
This also happened & reproducible in dashboard.

**Comment by yunkaisc** [comment] 2022-04-29 17:03
> If I choose add query and click the pencil icon to go into raw editor mode > copy/paste the query from the line above > click outside of the editing box, the query result automatically graphs immediately

My observation is that the new query graph does not render immediately if the query is pasted.

**Comment by ifrost** [comment] 2022-05-02 12:49
I've moved it to @grafana/observability-metrics backlog as it seems to be Graphite related. Happy to help if you need it 👍  (cc @bohandley)

**Comment by bohandley** [comment] 2022-05-08 17:17
Thank you @yunkaisc for bringing this to our attention, thank you @mellieA for exploring the issue, and thank you @ifrost for tagging me. I've got some notes here after looking into this issue, bear with me :)

I can confirm the copy and paste of the query in the text editor does not load the graph, is not stored as we see when the browser is refreshed. On copying and pasting the query, this only updates the query target in the plugin state and does not update the query target in the datasource. The query target in the data source is only updated after the query is run after clicking out of the text editor with the onBlur event. In the code below, we can see the onChange event dispatches the 'update-query' event, while the onBlur event dispatches the 'run-query' action.

https://github.com/grafana/grafana/blob/809aa38103771726aa3a6208a87f8138d6d15ea6/public/app/plugins/datasource/graphite/components/GraphiteTextEditor.tsx#L12-36

The 'run-query' action refreshes the state, which updates the datasource query target, but the 'update-query' does not.

https://github.com/grafana/grafana/blob/5c2dee19d5b1bd9e3493e01c64699d7b1592267b/public/app/plugins/datasource/graphite/state/store.ts#L176-L182

So, adding a query tells the backend to add a query which is stored on refresh, but if a person copies and pastes the query without causing an onBlur event, the query target is not truly updated. When the queries are loaded from the backend in the QueryRows component, 

https://github.com/grafana/grafana/blob/5c2dee19d5b1bd9e3493e01c64699d7b1592267b/public/app/features/explore/QueryRows.tsx#L40

this returns the added query without a target, and it looks as though the query disappeared. 

https://user-images.githubusercontent.com/25674746/167307548-423cd6b7-5bab-4657-9994-f20b51a39059.mov

I'm looking into how to update the query target in the datasource when dispatching the 'update-query' action. Thank you for your patience!

**Comment by bohandley** [comment] 2022-07-27 20:57
Update: @yunkaisc, I have a PR ready for the copy and paste issue https://github.com/grafana/grafana/pull/49111. To continue working on the duplicating issue, where we would like to run the query on duplicating a query row, I have opened this issue https://github.com/grafana/grafana/issues/52910. I'll continue to work on that and see if there is a solution that doesn't involve race issues. It may require a refactor.

**Comment by bohandley** [comment] 2022-07-29 20:56
While I was looking for a fix, it appears that the storing issue has been solved in Explore. On copying and pasting a query, the query does not disappear as described in the original issue.

> **What you expected to happen**: Should work the same as typed queries,
> 
> 1. Graph would be rendered after the metrics query is pasted
> 2. Query should not disappear,
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Open https://play.grafana.org/explore
> 2. Type in `apps.backend.backend_01.counters.requests.count`
> 3. Copy `apps.backend.backend_01.counters.requests.count`
> 4. Click Add query
> 5. Paste `apps.backend.backend_01.counters.requests.count` to Query B, the graph for query B will not render
> 6. Click disable, the query disappears.


https://user-images.githubusercontent.com/25674746/181841722-04146fc6-19ad-4f23-8066-942a438c09bc.mov

**Comment by bohandley** [comment] 2022-08-01 20:08
Hello all @yunkaisc @mellieA @nikobearrr @ifrost 

Upon reflecting on the investigation and discussion in the last few months, I will be closing this issue for the following reasons and not pushing the code that I have been working on. 

1. There has been a change/fix in explore where the copied and pasted query is stored(no longer deleted when disabling the query, see evidence from video in comment above.)
2. To run the query and render the visualization after pasting or duplicating, we offer two options: clicking outside the input to fire the onBlur event or explicitly click the 'Run Query' button. This aligns with the current behavior of other datasource plugins such as Prometheus. 

Please let me know your thoughts so we can contribute them to the discussion, https://github.com/grafana/grafana/issues/51979, around standardizing running queries and thank you for bearing with me over the last few months!

**Closed** 2022-08-16 13:48 UTC
Labels: type/bug, datasource/Graphite, area/explore
