### ISSUE TITLE
Make template variable value (and multi value) encoding like glob, regex values, pipe, etc context specific. 

### ISSUE THREAD

**Issue by morganda** [grafana/grafana#2918] opened 2015-10-09 22:17 UTC
Grafana version: 2.1.3-1 (Downloaded and installed today)

On dashboard1 I will have a ROLE variable = "my-app"
When passed to the drill down dashboard via a query string I get something similar to the following URL:

http://server/dashboard/db/server-groups?from=now-1h&to=now&var-ROLE=my%5C-app

You will notice the %5C embedded in the variable. %5C is an encoded escape "\". The escaping does not get interpreted by the dashboard correctly and attempts to use the value "my\\-app".

**Comment by torkelo** [comment] 2015-10-10 16:43
yea, the escaping is there for the variable to be used in InfluxDB regex setting. So you can fix this by disabling multi select or all value. 

For a properly fixt this a big update to the templating system needs to happen (that encoding of template variable value is context specific, so if used in InfluxDB query use regex, if used in graphite query use glob, if used in url use url etc, currently the encoding of a template variable value is specified in the template var definition), this update will not happen until v2.6 or 3.0

**Comment by yacoob** [comment] 2015-10-13 23:54
Just found this behaviour when I was trying to create a disk SMART attribute drilldown console. I have SMART data stored in prometheus, in timeseries like this:

```
collectd_smart_attribute_0{instance="boxoob",job="boxoob",smart="sda",type="airflow-temperature-celsius"}	
collectd_smart_attribute_0{instance="boxoob",job="boxoob",smart="sda",type="spin-retry-count"}	
...
```

My attempt to template out `type` label failed, because grafana extracts all values of `type` label, then quotes the dashes, and then sends it back to prometheus, which gets confused:

```
parse error at char 61: unknown escape sequence U+002D '-'
```

Curiously enough, the quoting persists **even** if I disable `multi select` and `all value` for all template variables present on this dashboard. I've uploaded the json export of my dashboard [here](http://pastebin.com/Zf00R6zS), as github complained about being unable to attach a json file (even if renamed to `.txt` :|).

**Comment by pdf** [comment] 2015-12-27 22:22
Broken hyphens is a real problem since they're used so frequently.  I'm seeing the same issue as @yacoob, which seems to be a regression introduced in 2.6, because the same dashboard was rendering correctly in 2.5 (though linking was indeed broken then too).

BTW @yacoob you can use a [gist](https://gist.github.com) to link larger data to issues.

**Comment by mtanda** [comment] 2016-01-21 07:54
I'm seeing the same issue too. (I use Prometheus)

**Comment by juntagabor** [comment] 2016-02-25 19:36
Came across this issue too :(

**Comment by grobie** [comment] 2016-02-28 02:19
Same issue. I was trying to find a specification for how to deal with escaped characters if they are no escape sequence. Golang's behavior (and therefore Prometheus) is to be very strict about it.

@torkelo Any estimations when this will be fixed? As 2.6 has passed, do you think this will land in 3.0?

**Comment by torkelo** [comment] 2016-02-28 06:54
Not sure,  its an important issue that I want fixed, but requires a big refactor, will try to see how big and if it can be squeezed into 3.0

**Comment by grobie** [comment] 2016-02-28 07:16
Ok, thanks for the update!

**Comment by torkelo** [comment] 2016-03-01 18:14
templating variable formatting is now removed from the variable options, it is now controlled by the caller (so different data sources can specify what escaping and multi value formatting is needed for each interpolation call).

https://github.com/grafana/grafana/commit/2cf1193b568ba4c4ffed69a09a2540dd111b2c22

**Closed by torkelo** 2016-03-01 18:14 UTC
Labels: comp: dashboard/templating, P3: important, state: help wanted (PR), type: bug

**Comment by grobie** [comment] 2016-03-01 18:39
@torkelo Great! I fear this change broke prometheus regex though. Without using either an all or multi value, Grafana tries to escape non-escape characters now. For example a template variable with value `['foo', 'foo-bar', 'baz']` doesn't seem to work anymore when foo-bar is selected, as Grafana tries to escape the dash.

**Comment by torkelo** [comment] 2016-03-01 20:07
@grobie yea, if you do not use the regex operator in your prometheus query it could be a problem. Prometheus data source has to parse the query and see if the variable is used in a regex context or not, right now it assumes regex to support multi value scenarios

**Comment by torkelo** [comment] 2016-03-01 20:36
@grobie managed to solve the issue, https://github.com/grafana/grafana/commit/0da4168836a73a8a10bd8cf8b2e40d61b6179498 

Variables that are not multi value nor have an All value are never regex escaped.

**Comment by grobie** [comment] 2016-03-01 21:22
@torkelo Thanks, this fixes is for non all/select. This problem is not related to using the regex operator or not though. Escaping non-escape sequences is never valid with Prometheus, unrelated of which label matcher is used.

[Example queries](http://demo.robustperception.io:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22%7Btest%3D~%5C%22this%20is%20not%20%5C%5C-%20valid%5C%22%7D%22%2C%22tab%22%3A1%7D%2C%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22%7Btest%3D%5C%22this%20%5C%5C%3A%20is%20not%20valid%20either%5C%22%7D%22%2C%22tab%22%3A1%7D%5D). This seems to be the result of the [golang behavior](https://play.golang.org/p/JR0Yseis58).

How do other datasources handle that? Do you think this needs to be changed on the Prometheus side?

**Comment by grobie** [comment] 2016-03-01 21:32
Prometheus currently requires backslashes to be double escaped because of this. I'm open to suggest changing that. The behavior will still be broken for all prometheus servers before such a change.

I wonder why `:` and `-` get escaped in regular expressions though. In which context is the colon a meta character? The dash only seems to have special meaning if used in a bracket expression and even then only if used between other characters, but not if it's placed at the beginning or end.

**Comment by grobie** [comment] 2016-03-01 23:46
The right solution would be to escape backslashes so that they don't get interpreted as the beginning of an escape sequence. A workaround for the time being is to use backticks in prometheus expressions. This will break when the value itself includes backticks though and it's also way more uncommon than normal strings.

**Comment by pdf** [comment] 2016-03-01 23:53
@grobie colons are used to designate non-capturing groups `(?:dont-capture-this)`, and character classes `[[:alnum:]]`.

That said, I believe the Grafana regexp escape list may be overly broad.

Golang considers the following chars when escaping using `regexp.QuoteMeta`:
```go
var specialBytes = []byte(`\.+*?()|[]{}^$`)
```

The ES7 proposed `RegExp.escape` considers the following characters:
```javascript
String(s).replace(/[\\^$*+?.()|[\]{}]/g, '\\$&')
```

The ES7 proposal does mention `-`, as being potentially escaped in an extended proposal, but only at the start of a string.

lodash also only considers the above characters:
```javascript
var reRegExpChar = /[\\^$.*+?()[\]{}|]/g
```

So, my suggestion would be to reduce the escape coverage in Grafana unless there are known good reasons for retaining it as-is.

**Comment by grobie** [comment] 2016-03-02 00:03
Right, there is being used. I don't see how not escaping `:` can ever cause issues though, given it doesn't have any special meaning without adjacent other meta characters.

Reducing the character set is fine, but it will only postpone the issue. It'll still break with any value including a character from the escaped character set. In Prometheus escaping characters in regular expressions must be done using two backslashes to get past the escape sequence parsing.

**Comment by pdf** [comment] 2016-03-02 00:18
@grobie indeed it does seem like Prometheus will need a special-case for double-escaping, but I think the escape list is still probably too wide.  The problem with backticks is that there's no way to deal with a var containing a backtick, so you'd need a fallback to double-slash, which means you may as well just use that all the time.  And either way, you're special-casing Prometheus, so I'm not certain it gains you anything.

**Comment by grobie** [comment] 2016-03-02 00:25
Moving the escape logic into each datasource provider makes sense to me. The `templateSrv` already knows about a lucene escape funtion which also seems to be a special case. This will leave preparing a query to be sent to a datasource entirely to the datasource provider without making assumptions about the query language requirements.

**Comment by torkelo** [comment] 2016-03-02 07:43
@grobie I am not sure what the current problem is, there is no escaping at all if you have a variable with All or multi disabled. If you have multi value or all enabled you need to use the regex operator in your query and then grafana will regex escape the template variable value, I did update the regex excape to match the proposed ES7 proposed RegExp.escape function. 

I have not found any issue with escaping regex chars in my Prometheus tests.

**Comment by grobie** [comment] 2016-03-03 04:10
@torkelo I opened #4234 for this issue. I tried to describe the problem again and also provided a dashboard definition to reproduce this issue. As much as I'd love to run on master and help testing new features, with this issue we're stuck at d8f7bce which is the last revision before this rewrite. Thanks for all the work, comment on that other issue if you need more information.
