### ISSUE TITLE
Second (right-side) axis label and scale are broken since upgrading to 4.5.0-beta1

### ISSUE THREAD

**Issue by gregvolk** [grafana/grafana#9218] opened 2017-09-11 15:24 UTC
Last week I upgraded my Grafana docker image to 4.5.0-beta1 (commit: bc69023) and since then my second-axis (right-side) labels are misplaced and the axis scale values are incorrect. I've reproduced the problem with three browsers: Chrome, Opera, and Slimjet (a Firefox variant). 

This is what the problem looks like:

![20170911_1018_grafana_axis_issue](https://user-images.githubusercontent.com/13316371/30282463-02c4d256-96db-11e7-9191-5d7103d973b8.png)

This is the panel json:
```
{
"aliasColors": {},
"bars": false,
"dashLength": 10,
"dashes": false,
"datasource": null,
"fill": 1,
"id": 20,
"legend": {
"avg": false,
"current": false,
"max": false,
"min": false,
"show": true,
"total": false,
"values": false
},
"lines": true,
"linewidth": 1,
"links": [],
"nullPointMode": "null",
"percentage": false,
"pointradius": 5,
"points": false,
"renderer": "flot",
"seriesOverrides": [
{
"alias": "/retran/",
"points": true,
"yaxis": 2
}
],
"spaceLength": 10,
"span": 12,
"stack": false,
"steppedLine": false,
"targets": [
{
"hide": false,
"refId": "A",
"target": "alias(perSecond(wumpus.nstat.TcpOutSegs), 'TcpOutSegs')"
},
{
"hide": false,
"refId": "B",
"target": "alias(asPercent(perSecond(wumpus.nstat.TcpRetransSegs), #A), 'retran_pct')",
"targetFull": "alias(asPercent(perSecond(wumpus.nstat.TcpRetransSegs), alias(perSecond(wumpus.nstat.TcpOutSegs), 'TcpOutSegs')), 'retran_pct')"
}
],
"thresholds": [],
"timeFrom": null,
"timeShift": null,
"title": "TCP Output Segment Rate and Retransmit Percentage",
"tooltip": {
"shared": true,
"sort": 0,
"value_type": "individual"
},
"type": "graph",
"xaxis": {
"buckets": null,
"mode": "time",
"name": null,
"show": true,
"values": []
},
"yaxes": [
{
"format": "short",
"label": "TcpOutSegs",
"logBase": 1,
"max": null,
"min": null,
"show": true
},
{
"format": "short",
"label": "Tcp Retransmit Pct",
"logBase": 1,
"max": null,
"min": null,
"show": true
}
]
}
```

**Comment by torkelo** [comment] 2017-09-11 15:26
duplicate of https://github.com/grafana/grafana/issues/9172  

fixed in latest nightly build

**Closed by torkelo** 2017-09-11 15:26 UTC
