### ISSUE TITLE
Data source API: Unable to create or edit data source to be readOnly in order to not be editable by UI

### ISSUE THREAD

**Issue by jack-cloud-platform** [grafana/grafana#42975] opened 2021-12-10 13:23 UTC
**What happened**:

Unable to create or edit any data source using the Data source API https://grafana.com/docs/grafana/latest/http_api/data_source/ and set readOnly property to true.

**What you expected to happen**:

I expect to be able to set the readOnly property to true in the body of the PUT (when editing a data source) or POST (when creating a data source) request and the data source to change to / be created with readOnly set to true. This should then prevent the data source being able to be edited when using the Grafana UI.

Following creation of a data source via data source provisioning https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources with `editable: false`, and then doing a PUT request on the data source, the readOnly property becomes false and the data source can be edited using the Grafana UI.

**How to reproduce it (as minimally and precisely as possible)**:

Example Graphite Request:

```
POST /api/datasources HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer <api key>

{
  "name":"test_datasource",
  "type":"graphite",
  "url":"http://mydatasource.com",
  "access":"proxy",
  "basicAuth":false,
  "readOnly":true
}
```

Example Graphite Response:

```
HTTP/1.1 200
Content-Type: application/json

{
  "datasource": {
    "id": 1,
    "uid": "Ur5S242bh"
    "orgId": 1,
    "name": "test_datasource",
    "type": "graphite",
    "typeLogoUrl": "",
    "access": "proxy",
    "url": "http://mydatasource.com",
    "password": "",
    "user": "",
    "database": "",
    "basicAuth": false,
    "basicAuthUser": "",
    "basicAuthPassword": "",
    "withCredentials": false,
    "isDefault": false,
    "jsonData": {},
    "secureJsonFields": {},
    "version": 1,
    "readOnly": false
  },
  "id": 1,
  "message": "Datasource added",
  "name": "test_datasource"
}
```

**Anything else we need to know?**:

This issue was reported on Grafana community https://community.grafana.com/t/cannot-make-read-only-data-source-via-api/50942

**Environment**:
- Grafana version: v8.3.1 (b9eacd93e9)
- Data source type & version: N/A
- OS Grafana is installed on: docker Alpine image
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by Elfo404** [comment] 2021-12-13 11:46
Hello @jack-cloud-platform thanks for reporting this.

`readOnly` is only used for provisioned data sources, in fact since https://github.com/grafana/grafana/pull/19006 `readOnly` should be ignored when creating or updating datasources via the API.

Regarding
> Following creation of a data source via data source provisioning https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources with editable: false, and then doing a PUT request on the data source, the readOnly property becomes false and the data source can be edited using the Grafana UI.

this is a known issue reported in https://github.com/grafana/grafana/issues/32556.

I'm closing this as duplicate of the issue mentioned, but please feel free to follow up if you think i' missing something

**Closed by Elfo404** 2021-12-13 11:46 UTC
