### ISSUE TITLE
Bar Guage: support for automatic max. value

### ISSUE THREAD

**Issue by tramamte** [grafana/grafana#20581] opened 2019-11-22 04:01 UTC
**What would you like to be added**:
Max. value of the bar guage is automatically set to the maximum value of the query results.

**Why is this needed**:
I am using a bar guage to display TopN query with interval filter. In some cases, the guage is not usable, because the max. value of the bar guage can be set a single value.

with long interval:
A ============ 10000
B ============ 5000
C ============ 1000
D ============ 500

with short interval:
A = 11
B = 10
C = 9
D = 8

I think it is very useful that the max. value is set automatically to the maximum value (10000 or 11 above).

**Comment by hugohaggmark** [comment] 2019-11-22 04:24
Just to clarify you don't think the Calculation => Max is enough? Do you want the Bar Gauge to default to this?
![image](https://user-images.githubusercontent.com/562238/69397915-4d79df00-0ce8-11ea-8d1f-a5f29011b268.png)

**Comment by ryantxu** [comment] 2019-11-22 05:30
This is a duplicate of #19527 -- something I hope we can do soon

**Closed by ryantxu** 2019-11-22 05:30 UTC
Labels: needs more detail

**Comment by tramamte** [comment] 2019-11-22 05:37
Oops! Sorry and thanks.

**Comment by hugohaggmark** [comment] 2019-11-22 05:45
Thanks @ryantxu
