### ISSUE TITLE
The introduction panel should not be shown in a user config home dashboard

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#26914] opened 2020-08-11 08:30 UTC
**What happened**:
When setting the home dashboard from a file (https://grafana.com/docs/grafana/latest/administration/change-home-dashboard/), the default home introduction panel is pushed inside the dashboard.
It practically breaks the purpose of a home dashboard.

![image](https://user-images.githubusercontent.com/2118079/89875159-93a00700-dbc5-11ea-8e7e-f9f82547c2b8.png)

**What you expected to happen**:
just show the dashboard
**How to reproduce it (as minimally and precisely as possible)**:
just load grafana with the dashboard.home set to a json dashboard file.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: NA
- OS Grafana is installed on: Docker
- User OS & Browser: fedora/chrome
- Grafana plugins:NA
- Others:

**Comment by sakjur** [comment] 2020-08-11 08:36
Hi, thank you for submitting this report. It's easier for us to help you if you can format your bug report based on the bug report template, see https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md

**Comment by michelengelen** [comment] 2020-08-11 09:59
possible duplicate of #26447

**Comment by sakjur** [comment] 2020-08-11 10:05
@michelengelen Yup, thank you, closing this

Duplicate of #26447

**Closed by sakjur** 2020-08-11 10:05 UTC
Labels: area/dashboard, area/provisioning, type/bug
