### ISSUE TITLE
Mysql source sql:  Value type <nil> into type *string

### ISSUE THREAD

**Issue by roysbike** [grafana/grafana#8745] opened 2017-06-30 06:31 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please prefix your title with [Bug] or [Feature request]. 

Please include this information:
- Version 4.4.0-pre1 (commit: fb99ddf). What Grafana version are you using? 
- mysql  What datasource are you using? 
- centos 7.3.1611
-SELECT COUNT(`calldate`),dcontext,  SEC_TO_TIME(SUM(TIME_TO_SEC(duration))) AS duration ,   substring_index(`clid`,"<",+1) as clid  FROM  `cdr`  where (`calldate` >='2017-05-01 00:00:00' AND `calldate` <='2017-05-31 23:59:59') and duration >=14 and disposition='NO ANSWER' group by dcontext order by duration ; 
-sql: Scan error on column index 2: unsupported Scan, storing driver.Value type <nil> into type *string
- What happened instead?
- If related to metric query / data viz:
  - Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by daniellee** [comment] 2017-07-01 20:03
Can you figure out which field is causing the error (by testing one field at a time in the select)? As I don't know what your database schema looks like, it is difficult to figure out what the problem is.

**Comment by roysbike** [comment] 2017-07-12 07:55
SELECT COUNT(`calldate`), dcontext, SEC_TO_TIME(SUM(TIME_TO_SEC(duration))) AS duration,   substring_index(`clid`,"<",+1) as clid  FROM  `cdr`  where (`calldate` >='2017-05-01 00:00:00' AND `calldate` <='2017-05-31 23:59:59') and duration >=14 and disposition='NO ANSWER' group by dcontext order by duration ; 

error: sql: Scan error on column index 2: unsupported Scan, storing driver.Value type <nil> into type *string

MariaDB [asteriskcdr]> SELECT calldate,dcontext, duration , clid from cdr limit 1;
+---------------------+-----------------------+----------+-----------------------------+
| calldate            | dcontext              | duration | clid                        |
+---------------------+-----------------------+----------+-----------------------------+
| 2016-01-23 13:24:33 | zadarma-park-incoming |       22 | "TulaParking" <79157862222> |
+---------------------+-----------------------+----------+-----------------------------+
1 row in set (0.01 sec)

**Comment by daniellee** [comment] 2017-07-19 22:26
@roysbike It is currently a bit difficult to use int(11) as a the datetime field but possible if you use a subquery - see [this answer](https://community.grafana.com/t/using-sql-timefilter/1686/2?u=daniellee) on the community site for a related case. But we should definitely improve the macro support to support this.

**Comment by daniellee** [comment] 2017-08-08 13:48
Fixed by #8578 and #8918.

**Closed by daniellee** 2017-08-08 13:48 UTC
Labels: datasource: MySQL, type: question
