### ISSUE TITLE
Grafana + Flux alerts query issue

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#27635] opened 2020-09-17 09:18 UTC
I'm using Grafana cloud (7.1.5) with InfluxDB cloud 2.0 (Flux). 

I'm trying to set up a basic alert in Grafana, which should trigger based on an InfluxDB based time series chart.

**My default Flux query**
My normal Flux queries look as below, which produce the expected result in my chart:
```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "3F78A21D")
  |> filter(fn: (r) => r["_field"] == "S1_PID_0D_VehicleSpeed")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```
![image](https://user-images.githubusercontent.com/26184427/93451234-32abd300-f8d7-11ea-92fd-a9191940029f.png)

**The problem**
However, when I try to test an alert based on this I get the below error:
```
error:"tsdb.HandleRequest() response error &{invalid: error calling function "aggregateWindow" @5:6-5:42: error calling function "window" @universe.flux|125:12-125:57: parameter "every" must be nonzero A <nil> [] [] 0xc001512c00}"
```
**Attempted solution**
Based on the error, I've tried removing the Window aggregation, resulting in the below query:
```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "3F78A21D")
  |> filter(fn: (r) => r["_field"] == "S1_PID_0D_VehicleSpeed")
  |> yield(name: "mean")
```
![image](https://user-images.githubusercontent.com/26184427/93451349-5bcc6380-f8d7-11ea-8d01-14e67d9ee6b8.png)

When I test the alert rule with this query, I do not get an error. However, if I use this adjusted query, my chart only displays part of my data series (approximately 1 hour of data is not shown), as evident from the above picture. 

Am I missing something basic in setting this up, or is there a bug in the Flux alert functionality? I was not able to find specific examples of Flux queries in the context of setting up alerts. Basically I would like to be able to add alerts to charts that I also use for visualization in my dashboard.

**Comment by papagian** [comment] 2020-09-21 13:00
Duplicate of #26695

**Closed by papagian** 2020-09-21 13:00 UTC
Labels: area/alerting, datasource/InfluxDB/flux, type/bug
