### ISSUE TITLE
Allow raw Elasticsearch queries to be used instead of query builder

### ISSUE THREAD

**Issue by Inverness** [grafana/grafana#25639] opened 2020-06-16 18:10 UTC
**What would you like to be added**:

The ability to specify the raw JSON for Elasticsearch queries _instead of_ having to use the query builder.

To keep things simple, simply disable the query builder if the raw query is specified rather than requiring it to parse and understand the raw query to stay in sync.

**Why is this needed**:

Looking over other issues such as https://github.com/grafana/grafana/issues/20587 https://github.com/grafana/grafana/issues/18631 https://github.com/grafana/grafana/issues/25621 and particularly https://github.com/grafana/grafana/issues/18313 it is clear there are some cases where the query builder is simply not keeping up with some ES features. Maybe they are complex to support, or there are simply other development priorities. Rather than requiring Grafana development work first to allow these features to be used, why not allow raw queries to be written?

I understand this isn't user friendly, but it would make it possible for power users to cover edge cases while Grafana catches up.

I see that the SQL data sources already support a raw query editor, so there is precedent.

**Comment by torkelo** [comment] 2020-06-17 06:01
duplicate of https://github.com/grafana/grafana/issues/3163

**Closed by torkelo** 2020-06-17 06:01 UTC
