### ISSUE TITLE
Transformer: add field from calculation select behaves strangely

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#24271] opened 2020-05-05 04:30 UTC
Select in add field from calculation doesn't work properly, I can't choose any value above `Min`, see movie below:
![issue-with-select](https://user-images.githubusercontent.com/562238/81035178-2ed46280-8e9a-11ea-8fee-b80bd1dd06d2.gif)

**Comment by torkelo** [comment] 2020-05-05 05:05
duplicate of https://github.com/grafana/grafana/issues/24107   (a general problem with selects in new panel edit)

**Closed by torkelo** 2020-05-05 05:05 UTC
Labels: area/transformations, type/bug
