### ISSUE TITLE
TimeSeries: 0-valued stacked bars bleed colors at narrow panel widths

### ISSUE THREAD

**Issue by etam** [grafana/grafana#69610] opened 2023-06-06 08:28 UTC
### 
# What went wrong?

**What happened**:

See screenshots.

This is correct:
![big](https://github.com/grafana/grafana/assets/220752/361a6679-4602-4532-84a7-fdee2e6ea51c)

This is incorrect:
![small](https://github.com/grafana/grafana/assets/220752/9a1f56c1-04c1-480b-8520-405db0ccb0b3)

**What did you expect to happen**:

They should be the same.

### 
# How do we reproduce it?

This is a "Time series" panel with:
- style: bars
- stack series: normal
- added overrides to manually choose color for each field

### 
# What Grafana version are you using?

Grafana v9.5.2 (cfcea75916)

### 
### Is the bug inside a Dashboard Panel?

[debug-Backend request status codes-2023-06-06 10 04 34.json.txt](https://github.com/grafana/grafana/files/11662088/debug-Backend.request.status.codes-2023-06-06.10.04.34.json.txt)

### Grafana Platform?

Docker

### User's OS?

openSUSE Tumbleweed

### User's Browser?

Firefox 113.0.2

### Is this a Regression?

None

**Comment by tonypowa** [comment] 2023-06-07 11:18
hi @etam 

thank you for creating this issue

I have reproduced the behavior from my end  Grafana v10.0.0-cloud.3.b04cc88b (4f5dbbbb36) 

Firefox 113.0.2 (64-bit) with min browser width
![image](https://github.com/grafana/grafana/assets/45235678/a39b5038-38f8-4142-9a35-328edb9d2321)

Chrome 114.0.5735.110 (Official Build) (64-bit) with min browser width
![image](https://github.com/grafana/grafana/assets/45235678/78b0a26c-e529-4809-8d8a-9a352f31c7a0)

**Comment by leeoniya** [comment] 2023-06-07 16:06
this is related to stacking, and is a side-effect of how clipping regions are constructed for stacking/bands. it will need a patch in [uPlot](https://github.com/leeoniya/uPlot). i have an idea that i'll try out that should improve this for "orange=0" bars (if it pans out), but will still show this effect for non-zero orange bars.

i don't think a complete fix will be possible without rewriting the bar rendering & stacking code, which is a bigger undertaking (https://github.com/grafana/grafana/issues/51011)

**Comment by leeoniya** [comment] 2023-06-07 19:43
have a minimal repro outside of grafana:

![image](https://github.com/grafana/grafana/assets/43234/c11fa048-42fd-48f3-96bb-1fee8e5bd85e)

**Comment by leeoniya** [comment] 2023-06-08 03:25
pushed a fix in https://github.com/leeoniya/uPlot/commit/08dd61d74267156e1361b3523541508cc1a125f5

the stars that had to align to cause this behavior:

1. two un-aligned series, with non-uniform datapoint spacing
2. bar rendering style
3. stacking
4. a large enough time range (or small enough panel width) that causes the bar widths to be clamped above their "guaranteed not to collide" smaller widths.

as described in the commit, the fix will not cover all cases, but this is exact set of conditions seems to be quite rare; we've had this behavior in place for over two years, and no one had run into it.

**Comment by leeoniya** [comment] 2023-09-22 00:16
this turned out to need additional fixes because the attached dashboard uses strokes for the bars, not just fills. i would recommend to set the line width to 0 to disable strokes and only keep the bar fills.

regardless, both cases will be fixed by https://github.com/grafana/grafana/pull/75199

**Closed** 2023-09-22 16:33 UTC
Labels: type/bug, area/panel/timeseries, area/panel/trend
