### ISSUE TITLE
Useless scrollbar on iframe embeding panel 

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#12093] opened 2018-05-29 08:58 UTC
### What Grafana version are you using?
Grafana 5.1.3 official docker image

### What did you do?
Embeded panel as iframe using the `share` functionality

### What was the expected result?
To see just the panel there is no need to scroll whole panel is displayed

### What happened instead?
Grafana added scrollbar to the panel because it included also part of the background at the bottom as shown in the iframe which overflows the size of the frame. This happens to all panels not just single stat.

illustration from firefox but happens same way in chrome
(the gray is colored background of the panel the black is background color of the dashboard)
![screenshot-20180529104834-462x214](https://user-images.githubusercontent.com/6112562/40648523-f4f015ac-632e-11e8-895e-61752236230d.png)

the code of the iframe is 
```html
<iframe src="https://foo.bar/d-solo/O6BraeZmk/sre-sli?refresh=1m&orgId=1&panelId=56"
        width="450" height="200" frameborder="0"></iframe>
```

panel json is
```json
{
  "cacheTimeout": null,
  "colorBackground": true,
  "colorValue": false,
  "colors": [
    "#DC1F26",
    "#52545c",
    "#52545c"
  ],
  "datasource": "Prometheus",
  "decimals": 2,
  "format": "percentunit",
  "gauge": {
    "maxValue": 100,
    "minValue": 90,
    "show": false,
    "thresholdLabels": false,
    "thresholdMarkers": true
  },
  "gridPos": {
    "h": 3,
    "w": 8,
    "x": 0,
    "y": 2
  },
  "id": 56,
  "interval": "$time_interval",
  "links": [],
  "mappingType": 1,
  "mappingTypes": [
    {
      "name": "value to text",
      "value": 1
    },
    {
      "name": "range to text",
      "value": 2
    }
  ],
  "maxDataPoints": 100,
  "minSpan": 1,
  "nullPointMode": "connected",
  "nullText": null,
  "postfix": "",
  "postfixFontSize": "50%",
  "prefix": "",
  "prefixFontSize": "50%",
  "rangeMaps": [
    {
      "from": "null",
      "text": "N/A",
      "to": "null"
    }
  ],
  "repeat": "product",
  "repeatDirection": "h",
  "sparkline": {
    "fillColor": "rgba(207, 250, 255, 0.07)",
    "full": false,
    "lineColor": "#cffaff",
    "show": false
  },
  "tableColumn": "",
  "targets": [
    {
      "expr": " 1 - avg_over_time(sre_sli:$product[$__interval]) * increase(sre_sli:time[$__interval]) / ($seconds_count)",
      "format": "time_series",
      "instant": true,
      "interval": "$time_interval",
      "intervalFactor": 1,
      "legendFormat": "",
      "refId": "A"
    }
  ],
  "thresholds": "0.995",
  "title": "SLI",
  "transparent": false,
  "type": "singlestat",
  "valueFontSize": "80%",
  "valueMaps": [],
  "valueName": "current",
  "scopedVars": {
    "product": {
      "selected": false,
      "text": "userweb",
      "value": "userweb"
    }
  }
}
```

**Comment by budiroots** [comment] 2018-05-31 01:06
same thing +1:

**Comment by Fokey** [comment] 2018-06-27 15:02
+2 Bob

**Comment by dersimn** [comment] 2018-07-31 14:57
+1

**Comment by marefr** [comment] 2018-08-13 10:48
Duplicate of #12589

**Closed by marefr** 2018-08-13 10:48 UTC
Labels: comp: dashboard, type: bug
