### ISSUE TITLE
Randome unit of decbps after upgrade from 7.2.0 to 7.3.1

### ISSUE THREAD

**Issue by leahoswald** [grafana/grafana#28771] opened 2020-11-03 09:33 UTC
**What happened**:
I upgraded my grafana installation from 7.2.0 to 7.3.1
After that some of my graphs (most of the problematic ones are created in the last months) are showing a strange unit of decbps instead of bits/s for their Y-axis and I have no idea what this unit should mean (I would guess deca bits or a bit/s with the base 10). Also I have to change every single graph to a working unit again. This is not good.
![Screenshot2020-11-03_10-23-13](https://user-images.githubusercontent.com/1292551/97968942-a2aae580-1dbf-11eb-9454-80648603b83d.png)

**What you expected to happen**:
No unit change by an upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure. But I think it is related to this MR: https://github.com/grafana/grafana/pull/27838

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: prometheus 2.22.0
- OS Grafana is installed on: Debian 10
- User OS & Browser: Firefox 82

**Comment by ivanahuckova** [comment] 2020-11-03 09:42
Another issue related to `decbbs` mentioned on community site: https://community.grafana.com/t/panel-y-axis-units-byte-sec-si-is-saved-as-decbps-in-json/38658

**Comment by rvdheij** [comment] 2020-11-03 10:01
If this helps to determine the cause: we observed it when 7.1.5 tried to import a dashboard created on 7.2.0
Digging deeper, I see that my 7.1.3 system creates the JSON file with "Bps" where "7.2.0" does "decBps" (which is not right). This might be related to the introduction of the "(SI)" differentiation in the Data Rate units.

**Comment by rvdheij** [comment] 2020-11-03 10:12
FWIW - There is some value in scaling disk I/O with 1024 and network I/O with 1000 but that's probably not my biggest concern when typical panels are 5% - 7% off when we're reporting MB/s and GB/s. In a previous life I avoided the issue by using 1024 because network traffic often includes frame headers etc that obscure the actual application workload enough as an excuse.
My main concern was using half of the panel real estate for the units on the Y-axis showing "decBps" with a dozen digits.

**Comment by rvdheij** [comment] 2020-11-03 10:37
I probably should have reviewed https://en.wikipedia.org/wiki/Binary_prefix before commenting, but maybe we need to change this into a feature request rather than a bug report. I understand the legal issues around SSD drives, but would like a pragmatic approach for the panels.
The designer of the panel should be aware what type of scaling to use, and the user should be able to blindly trust that judgment. I would be perfectly happy with both showing GB/s even though some G may be bigger than others. I don't even expect the discrepancy to cause issues where the two meet (like iSCSI) because of the frame header overhead.

**Comment by torkelo** [comment] 2020-11-03 12:56
yes, we accidentally released 7.2 with some bad unit ids, fixed in 7.2.1, but if you used those unit ids in between those releases, you need to go into edit mode and pick the unit again

**Closed by torkelo** 2020-11-03 12:56 UTC
