### ISSUE TITLE
mssql: Incorrect syntax near the keyword 'BETWEEN'.

### ISSUE THREAD

**Issue by stepanurban** [grafana/grafana#30372] opened 2021-01-19 06:37 UTC
Hello,
I need to convert time column in mssql into correct form, thus I call a function on it. 

`SELECT
  dbo.f_FileTimeToDateTime([StartTimeStamp]) as time,
  [Type] as value
FROM
  [dbo].[alarms]
WHERE
  $__timeFilter(dbo.f_FileTimeToDateTime([StartTimeStamp]))
ORDER BY
  dbo.f_FileTimeToDateTime([StartTimeStamp]) ASC`

but then `$__timeFilter` doesn't work properly becase it it converted to

`SELECT
  dbo.f_FileTimeToDateTime([StartTimeStamp]) as time,
  [Type] as value
FROM
  [dbo].[alarms]
WHERE
  dbo.f_FileTimeToDateTime([StartTimeStamp] BETWEEN '2021-01-17T06:31:27Z' AND '2021-01-19T06:31:27Z')
ORDER BY
  dbo.f_FileTimeToDateTime([StartTimeStamp]) ASC`

which returns `mssql Incorrect syntax near the keyword 'BETWEEN'.` because of missing bracket.
Using alias time also doesn't work, it returns `mssql: Invalid column name 'time'`

Thanks

**Comment by aocenas** [comment] 2021-01-22 12:53
@papagian is this something you can take a look at? Seems like the problem is with matching correctly what is inside the parenthesis of `$__timeFilter()` construct and it just naively stops at first closing paren. At the same time docs state that it should be used for column names so maybe this can be seen as feature request.

**Comment by papagian** [comment] 2021-01-22 15:28
@stepanurban 
Thanks for reporting this. Which grafana version do you use?

**Comment by marefr** [comment] 2021-01-25 11:09
The recommended approach would be to use `$__timeFrom()` and `$__timeTo()` instead of `$__timeFilter`

**Comment by stepanurban** [comment] 2021-01-27 08:51
Hi,
I'm using Grafana v7.3.3 (2489dc4d3a).
Recommended `$__timeFrom()` and `$__timeTo()` works fine Thanks @marefr !

**Closed** 2021-01-27 10:58 UTC
Labels: datasource/MSSQL, needs investigation
