### ISSUE TITLE
[Bug] Graph panels are arranged wrong in IE and Firefox in some circumstances

### ISSUE THREAD

**Issue by datamuc** [grafana/grafana#7960] opened 2017-03-27 20:09 UTC
I'm using Grafana 4.2.0 on Debian. The datasource is an InfluxDB with [sample data from there](https://docs.influxdata.com/influxdb/v0.9/sample_data/data_download/). I'm building a Dashboard with a row with some graph panels in it. They all have a span of 4 and the fourth panel is arranged wrong in some circumstances. I've setup a [demo](http://banjo.rbfh.de:3000/dashboard/db/borken-clicked?orgId=1) but I will also attach the dashboard json.

The arrangement is wrong in Firefox and IE. But only when the third panel has only one label. If there are more labels everything works fine. Also when the second panel has only one label then it also works with the third panel having only one label.

**Comment by datamuc** [comment] 2017-03-27 20:11
[borken.json](https://github.com/grafana/grafana/files/873668/borken.txt)

**Comment by torkelo** [comment] 2017-03-28 07:48
looks to be caused by the scrollbar that is shown on one of the panels. Try increasing the height of the row.

**Comment by datamuc** [comment] 2017-03-28 08:28
increasing height doesn't help, scrollbar is gone problem persists:

[actual dashboard after increasing height](https://github.com/grafana/grafana/files/874925/borken.txt)

**Comment by datamuc** [comment] 2017-03-31 22:03
Sorry cannot run the demo any longer, here's a screenshot:

![borken](https://cloud.githubusercontent.com/assets/51400/24570914/75953dea-166e-11e7-8ba5-a55c239c1275.jpg)

**Comment by daniellee** [comment] 2017-04-04 10:17
It seems to be due to a difference in the way Firefox renders fonts with decimal places (for example font size 11.9) that adds an extra pixel or two and this messes up the calculations for the legend height.

**Comment by torkelo** [comment] 2017-12-18 14:54
should be fixed in master with new grid https://www.youtube.com/watch?v=BC_YRNpqj5k&t=35s

**Closed by torkelo** 2017-12-18 14:54 UTC
Labels: comp: panel/graph, help wanted, P3: important, type: bug
