### ISSUE TITLE
Postgresql query editor adds extra quotes for multi variables

### ISSUE THREAD

**Issue by martinscheffler** [grafana/grafana#63295] opened 2023-02-11 08:23 UTC
Seems that multi-value variables are handled differently than single-value variables in the postgres query editor (builder and code editor).

Reproduction steps:

Create a variable var_nonmulti, type custom, values a, b, c , don't check "Multi-value"
Create a variable var_multi, type custom, values a, b, c , DO check "Multi-value"
Create a postgres data source
Create a panel with postgres datasource. 
In code editor, add SQL:
select * from mytable where device_id='${var_nonmulti}' or device_id='${var_multi}'
Execute SQL.

In Postgresql log, I see:
2023-02-11 08:17:54.065 UTC [761] ERROR:  syntax error at or near "a" at character 58
2023-02-11 08:17:54.065 UTC [761] STATEMENT:  select * from devices where device_id='a' or device_id=''a''

I expect to not have double quoutes around the var_multi value.

**Environment**:
- Grafana version: docker.io/grafana/grafana:9.3.6
- Data source type & version: docker.io/timescale/timescaledb:latest-pg14
- OS Grafana is installed on: Windows 10, Rancher Desktop
- User OS & Browser: Windows 10, Microsoft Edge 109.0.1518.78
- Grafana plugins:
- Others:

**Comment by dhawal1248** [comment] 2023-03-01 15:06
+1

**Comment by learnwithjj** [comment] 2023-03-30 06:11
@martinscheffler  @dhawal1248 
I think equal to (=) is used for a single value
Try using in operator for multi value variable selection 

select * from mytable where "device_id" IN ($var_nonmulti)

**Comment by martinscheffler** [comment] 2023-03-30 06:28
@learnwithjj I haven't tried that. But that would only be a solution when using the code editor. The builder does not using IN.

**Comment by anlong465** [comment] 2023-07-16 16:09
+1

Just met the same issue today. And my scenario is a little bit complex, but it make this defect more clear.

1) For my IOT data monitoring project, we have one dynamic monitoring need. 

2) We use pgsql as datasource, and three variables (table name, column name, row filter value) are defined and then the user could select their value from the prompt down list selection.

3) and then inside the grafana dashboard, we have the below similar sql 
====================================
select a.*  from 
(SELECT to_timestamp(birth_mills/1000) as time, ${measureColumnName} as "${measureName}"
  FROM  iot.${modeTableName}
  where unit_id = ${unitId}  
  order by birth_mills) a
where $__timeFilter(time) 
=====================================
Such sql is working fine when: ${unitId} is "multi-value", and other vairables are single value.  From Grafana Query Inspector, the sql passed down to pgsql just show that: the value for ${unitId} is around with single quote, but other variables are repleaced by pure value, i.e., without single quotation.

However, if we want to make the variable of ${measureColumnName}  as multi-values and then the panel is repeated by this variable, we could not make it working, because of the extra single quotation mark for ${measureColumnName}.  Of cause, this time, single quote was not appended to ${unitId}, but it could be resolved by manual adding single quote.  But, but,   ${measureColumnName} should not have extra quote as it is appeared in the select-part, and we really have no idea how to remove such extra quote.

Anyway, I think this is need be fixed. No matter one variable is single value type or multi-value type, 
1) Number one, its value should be exactly the same as its original value, no extra char; 
2) Number two, on the perspective of grafana panel, the variable value should always have (or don't have) extra quote, no matter it is multi-value or not;  
3) Number three, to add or not add extra quot, it should be decided by grafana panel developer, not by grafana platform

**Comment by anlong465** [comment] 2023-07-20 01:48
@sjd210 
I am not sure if such additional single quote is introduced by supporting IN-clause or not. Anyway, I think, in order to make IN-clause happy and then to add additional single quote for multi-value is NOT one right choice.

Additional, multi-value variables has different scenarios,
- one is for IN-clause, which needs single quote for every value;  https://github.com/grafana/grafana/pull/71130 
- another case is when multi-value variables is used as Repeated column, and then pure value itself is expected. 

Given the above two scenarios, I still suggest that for multi-value, no single quote would be automatically appended. Even for IN-clause, since such multi-value variable is used as one single variable, then the developer could define such variable as single-value variable, and I believe there is some workaround to make IN-clause happy (for example, via its definition use string_agg or || to append single quote, or via its usage, change its sql to like "in (select some_coulmn from some_table when some_condition )" )

In a short, without single quote around for multi-value, there is many workaround to make SQL IN-cluase happy; 
but with single quote around, when such mult-value variable is used as "Panel Repeat column", and such variable is used as column name in SQL, panel developer have no way to remove such additional single quote char at all.

**Comment by sjd210** [comment] 2023-07-20 10:03
Hi @anlong465, I'm looking into what you've said now. The way we process multi-value variables is as a list of quoted strings e.g.`'a', 'b', 'c'` and from my testing this seems to be the best way to keep it.

Would you mind sending a copy of the JSON for the dashboard in which you're having this problem (via Share -> Export), or for one in which you've recreated it and I'll have a look at it to better understand?

**Comment by anlong465** [comment] 2023-07-21 07:03
[issue brief.docx](https://github.com/grafana/grafana/files/12117326/issue.brief.docx)

**Comment by anlong465** [comment] 2023-07-21 07:24
please just think about the below dashboard sql definition. certainly, depends on if  one variable is multi-value or not, the below sql would be transformed differently. At most only one case is working.  
=====================================================
select a.* from 
(SELECT to_timestamp(birth_mills/1000) as time, ${measureColumnName} 
  FROM  iot_data.${modeTableName}
  where unit_id = 'APAC-${unitId}'
  order by birth_mills) a
where $__timeFilter(a.time) 
=================================================

And the variable ${measureColumnName} needed be multi-value for panel repeat variables. And then, the sql would be 
   select time, 'a' from table where xxx,
such 'a' would be handled as constrant string value instead of column name by db server.

That would be issue, and we have no-way to bypass such issue caused by such additional single quote.

Return back your point:  "process multi-value variables is as a list of quoted strings e.g.'a', 'b', 'c'",  well, it is a list, and such list could be used in SQL IN-clause only (pl correct me if I am wrong).  Well, such demand from IN-clause could be fulfilled by many different ways:
1) walkaround-1: leveraging sql function string_agg('\'' || columm_name || '\'', ',') to automatically combine them as one single string varaiable,.
2) walkaround-2: don't need define variable, just update the dashboard SQL:  instead of puting such multi-value vairable into one SQL IN-clause, just directly put such multi-variable defition sql term inside such IN-clause.
i.e.,    
  original sql would be similar as : where id in  (${multiValueVariabelName}), 
  the new sql would be:  where id in ( select id from another_table where condition='$condtion' )

But, when such multi-value variable is appeared in SQL select-clause, such additional automatical appended single quote would make the column as one constant string value, and we have no way to fix at devloper perspective.

**Comment by mdvictor** [comment] 2023-07-25 10:16
Hello everyone! @martinscheffler, the 'Any in' filter option in the builder would create a statement of the form `column IN (${multi_var})`.  Indeed it's still an issue in the builder, because it adds extra quotes, the PR above by @sjd210 will fix this. But for the code editor it should work. Also, as @learnwithjj mentioned, I think a single value var would be preferred in your example. 

There is another option though using [variable modifiers](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/) for this concrete example. If you were to add the `raw` modifier in your statement `or device_id='${var_multi:raw}'`,  the macro processor would not add the extra quotes, leaving only the quotes you manually added, thus being correct syntactically. If you select multiple values though, the result might not return the intended data( e.g: for a multi var with values `test1`,`test2`) the above modifier would return `test1,test2` transforming your statement into `or device_id='test1,test2'`.

@anlong465 I think the same `raw` modifier can be used in your case to remove the quotes and leave the multi var list as column names instead of a constant string value.

**Comment by anlong465** [comment] 2023-07-26 01:47
@mdvictor Such **raw** modifier just resolve my issue, and thank you very much!

@sjd210,  I am still some kind of new learner to grafana, so, sorry for my rude in the previous comments.

**Closed** 2023-08-04 08:43 UTC
Labels: type/bug, area/dashboard/templating, datasource/Postgres
