### ISSUE TITLE
[Feature request] Time restriction for alert notification

### ISSUE THREAD

**Issue by rpliva** [grafana/grafana#6943] opened 2016-12-13 09:17 UTC
It would be useful if a notification could be able to define time period when should be fired. 

E.g. I have slack and pagerduty notifications connected to my alert and I need to use slack during the working hours (9am - 5pm) and pagerduty in the rest of time (5pm-9am)

Possible solution is add time restriction to the notification and when it is activated by alert check if current time is in the period. If yes than fire the notification otherwise do nothing.

We are using Grafana 4.0.2 in docker, datasource is elasticsearch

**Comment by torkelo** [comment] 2016-12-13 21:13
yes, this is something we want to implement some day. 

Closing this as it's a dupe of https://github.com/grafana/grafana/issues/6592

**Closed by torkelo** 2016-12-13 21:13 UTC
