### ISSUE TITLE
Hiding all transforms (`disabled: true`) swallows the Dataframe

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#80827] opened 2024-01-18 16:14 UTC
In Grafana 10.4, when I'm editing a panel which has transforms, when I hide (disable) **all** the transforms, suddenly the entire dataframe data disappears, and I'm left looking at `No data`

I could see this issue in Grafana 10.4, in two separate hosted-grafana instances. But I was unable to reproduce the issue on play.grafana.com, which is running Grafana 10.3. Perhaps it's an issue with 10.4, or perhaps an issue with a feature flag which is enabled across both of the 10.4 instances I was testing on. Reach out to me if you want to know which instances I tested on, so we can look into their feature flags.

<img width="1129" alt="image" src="https://github.com/grafana/grafana/assets/2903904/70e7d0ef-c407-4e7d-a63b-94cd506c8aa7">

<img width="774" alt="image" src="https://github.com/grafana/grafana/assets/2903904/b42459a4-c898-4734-aee9-a234351c6469">

I've reproduced this in this panel, which I'm sharing here via the "Get help" kebab-menu option:

| Key | Value |
|--|--|
| Panel | timeseries @ 10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907) |
| Grafana | 10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 0,
            "gradientMode": "none",
            "spanNulls": false,
            "insertNulls": false,
            "showPoints": "auto",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "axisBorderShow": false,
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "unitScale": true,
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "fields": [
                  {
                    "name": "time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {}
                  },
                  {
                    "name": "A-series",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1705572699883,
                    1705577019883,
                    1705581339883,
                    1705585659883,
                    1705589979883,
                    1705594299883
                  ],
                  [
                    1,
                    20,
                    90,
                    30,
                    5,
                    0
                  ]
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "transformations": [
        {
          "disabled": true,
          "id": "calculateField",
          "options": {}
        },
        {
          "disabled": true,
          "id": "calculateField",
          "options": {}
        }
      ],
      "type": "timeseries"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[grafana-testdata-datasource]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td>calculateField, calculateField</td>\n  </tr>\n    <tr><th>Data</th><td> 1 frames, 2 fields, 6 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.4.0-65039 (da894994d42ee2bde00f2366fe6d30ad00b0e907) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"uid\": \"J_s2d8cVz\",\n    \"type\": \"grafana-testdata-datasource\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 0,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"insertNulls\": false,\n        \"showPoints\": \"auto\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"axisBorderShow\": false,\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"unitScale\": true,\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          },\n          {\n            \"color\": \"red\",\n            \"value\": 80\n          }\n        ]\n      }\n    },\n    \"overrides\": []\n  },\n  \"gridPos\": {\n    \"h\": 6,\n    \"w\": 12,\n    \"x\": 0,\n    \"y\": 0\n  },\n  \"id\": 3,\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"targets\": [\n    {\n      \"scenarioId\": \"csv_metric_values\",\n      \"refId\": \"A\",\n      \"datasource\": {\n        \"type\": \"grafana-testdata-datasource\",\n        \"uid\": \"J_s2d8cVz\"\n      },\n      \"stringInput\": \"1,20,90,30,5,0\"\n    }\n  ],\n  \"title\": \"🐛🐛 2 Transforms, 2 hidden 🐛🐛\",\n  \"transformations\": [\n    {\n      \"disabled\": true,\n      \"id\": \"calculateField\",\n      \"options\": {}\n    },\n    {\n      \"disabled\": true,\n      \"id\": \"calculateField\",\n      \"options\": {}\n    }\n  ],\n  \"type\": \"timeseries\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above (after transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 100,
      "title": "Data (before transformations)",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": false,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: 🐛🐛 2 Transforms, 2 hidden 🐛🐛 // 2024-01-18 16:11:43",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2024-01-18T10:11:43.533Z",
    "to": "2024-01-18T16:11:43.533Z"
  }
}
```
</details>

**Comment by leeoniya** [comment] 2024-01-19 00:52
dupe of https://github.com/grafana/grafana/issues/80827
and https://github.com/grafana/support-escalations/issues/9012

**Closed by leeoniya** 2024-01-19 00:52 UTC
Labels: area/transformations, internal

**Comment by samjewell** [comment] 2024-01-19 09:47
@leeoniya Thanks for tracking that down 🙏
