### ISSUE TITLE
Typo in logs when they are level error

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26450] opened 2020-07-20 08:38 UTC
**What happened**:

Logs which have level error show as `lvl=eror`. 

**What you expected to happen**:
It looks like a typo and I expect to see `lvl=error`

**How to reproduce it (as minimally and precisely as possible)**:
Run grafana and check logs. Example log:

`t=2020-07-20T08:14:50+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0`

**Anything else we need to know?**:
Happens on both docker logs (stdout) and syslog logs

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- OS Grafana is installed on: docker

**Comment by aknuds1** [comment] 2020-07-20 08:44
Duplicate of #25052.

**Closed by aknuds1** 2020-07-20 08:44 UTC
