### ISSUE TITLE
Loki Editor: history is undefined. Fix or remove?

### ISSUE THREAD

**Issue by matyax** [grafana/grafana#56651] opened 2022-10-10 14:54 UTC
From [this comment](https://github.com/grafana/grafana/pull/55391#discussion_r988130293).

We need to figure out if the `history` is broken and should be fixed, or no longer supported or should be removed.

**Comment by ivanahuckova** [comment] 2022-10-12 08:10
I'd vote for fix

**Comment by ivanahuckova** [comment] 2022-10-18 14:15
I am closing this as it is duplicate of https://github.com/grafana/grafana/issues/56465 which I am working on.

**Closed by ivanahuckova** 2022-10-18 14:15 UTC
Labels: needs investigation
