### ISSUE TITLE
Display of 2 querry simultaneously on GeoMap

### ISSUE THREAD

**Issue by HugzWaaa** [grafana/grafana#58845] opened 2022-11-16 15:02 UTC
**Steps to reproduce**:

- Create Infinity Data Source
![image](https://user-images.githubusercontent.com/113598277/202207929-0b00543e-9e29-4de2-89df-e6b4d14f4a0b.png)

- Create a Dashboard "test"
- Add a GeoMap pannel on the Dashboard "test"
- Edit GeoMap pannel for select the Datasource " yesoreyeram-infinity-datasource"
- Do a first query 
![image](https://user-images.githubusercontent.com/113598277/202209797-ac6ec7d2-1002-42e5-be0d-582e448a3809.png)

With this query I managed to have points that are placed on the map because in the fields that I will search with the query two fields contain coordinates (1 field latitude, 1 field longitude), which allows grafana to place the points on the map
![image](https://user-images.githubusercontent.com/113598277/202211757-fc965572-24e1-4c1b-b5fc-19b89334a451.png)

So until then everything goes well, I execute a query, points are displayed on the map as I wanted, it is afterwards that I encounter a problem, when I add a second query for example

Here is my second query, it works the same way as the first, the only difference between the 2 queries is that the 2nd query has many more different values in the fields that correspond to the latitude and longitude, so it should just place me more points than the 1st query on the map
![image](https://user-images.githubusercontent.com/113598277/202214258-fb14bcb0-35f3-458e-9030-0f27f1fb08ed.png)

however when I validate the query, nothing changes on the map, I still have the same number of points as when I execute the first query, it's only when I hide the first query that the second is taken into account 
![image](https://user-images.githubusercontent.com/113598277/202215366-c7dfed6f-3985-4acb-9aa2-144c62418c1d.png)
![image](https://user-images.githubusercontent.com/113598277/202215729-d8149840-ccd0-49eb-b8fd-d0beb94e701a.png)

My question is how can I make the 2 queries active at the same time on the same panel without having to hide the first one for the second to work?

**Environment**:
- Grafana version: Grafana v9.1.5
- Data source : yesoreyeram-infinity-datasource Version 0.8.8
- User OS : Windows Server 2019
- Browser : Microsoft Edge

https://github.com/grafana/grafana/issues/58845#tasklist-block-c4829f8b-0099-4ba5-a247-0db76709c58e

**Comment by HugzWaaa** [comment] 2022-11-16 15:13
If you ever wonder why I'm trying to do this, it's because I want to add a color code to the point (say that the points that are placed on the map because of query A are in red for example, say that the points that are placed on the map because of query B are in green.... )

don't hesitate to ask me for more information about the problem if you find it missing. 

Thanks in advance for your help

**Comment by zuchka** [comment] 2022-11-16 18:07
Thanks for creating this issue, @HugzWaaa 

I'm going to close this as a duplicate of https://github.com/grafana/grafana/issues/58640

let's track that issue instead. I'll be updating it soon 👍

**Closed by zuchka** 2022-11-16 18:07 UTC
