### ISSUE TITLE
[Explore] Show all option not taking immediate effect

### ISSUE THREAD

**Issue by khrubjak** [grafana/grafana#65694] opened 2023-03-31 11:42 UTC
**What happened**:
When more than 20 time series returned by query in explore mode, clicking the `Show all` option does not take effect immediately. The legend and the displayed area do not display the new series. Change of display mode (bars/lines/etc) or selecting a specific time series fixes the issue. Seem like some find of refresh is missing there. 

![image](https://user-images.githubusercontent.com/33662896/229110788-f00f0464-4dfd-4001-a3e9-70191eae37bb.png)

**What you expected to happen**:
I would expect the `Show all` option to take effect immediately on click like in the previous versions (no such issue detected in Grafana v8.5.X).

**How to reproduce it (as minimally and precisely as possible)**:
Query something that returns 21+ different label sets (different time series). Click `Show all` option. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.0
- Data source type & version: Victoria Metrics, Influx, probably other data sources as well
- OS Grafana is installed on: Ubuntu 22.04.1 LTS
- User OS & Browser: Ubuntu 22.04.1 LTS, Google Chrome
- Grafana plugins:
- Others:

**Comment by gelicia** [comment] 2023-04-03 13:17
@khrubjak We put some changes in to 9.4 that should have fixed this issue, can you try with that version?

**Comment by gelicia** [comment] 2023-04-03 13:20
Duplicate of #59994

**Closed by gelicia** 2023-04-03 13:20 UTC
Labels: area/explore
