### ISSUE TITLE
Templating init failed - Cannot read property 'queryModel' of undefined

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#13741] opened 2018-10-18 09:50 UTC
Hi people, sorry for bothering you we have encountered this problem on 5.3.0 and 5.3.1 - it seemed to be solved by pull request https://github.com/grafana/grafana/pull/12673 - "Cannot read property 'templateSrv' of undefined #issue - 11904 #12673" - but looks like it is still present.

I had to downgrade Grafana back to 5.2.4 to make it working again because this is the one most important dashboard for our project managers.

Could you please look at it? Many thanks. I will add what ever info you want I just do not know what is really important for you.

### What Grafana version are you using?
5.3.0, 5.3.1

### What datasource are you using?
Elasticsearch 2.4.5, PostgreSQL 10 (both in one dashboard)

### What OS are you running grafana on?
Ubuntu 16.04

### What did you do?
Opened dashboard after upgrade of Grafana from 5.2.4 to 5.3.0 and later 5.3.1 and it failed with error.

### What was the expected result?
I expected dashboard to work as usual :-)

### What happened instead?
Dashboard did not show data - only error message "Templating init failed - Cannot read property 'queryModel' of undefined"

### Include raw network request & response: 

grafana_app.ts:86 warning rootScope onAppEvent called without localscope
grafana_app.ts:86 warning rootScope onAppEvent called without localscope
history_srv.ts:33 Templating init failed TypeError: Cannot read property 'queryModel' of undefined
    at datasource.ts:108
    at Qt (lodash.js:639)
    at Function.Ka [as map] (lodash.js:9553)
    at e.interpolateVariable (datasource.ts:106)
    at e.formatValue (template_srv.ts:119)
    at template_srv.ts:247
    at String.replace (<anonymous>)
    at e.replace (template_srv.ts:218)
    at e.metricFindQuery (meta_query.ts:22)
    at e.metricFindQuery (query_variable.ts:172)
 
### Temporary solution
Downgrade to 5.2.4

Many thanks.

**Comment by torkelo** [comment] 2018-10-18 10:31
already fixed in nightly build via this PR , https://github.com/grafana/grafana/pull/13708 

and will be included in upcoming path release (no ETA yet)

**Closed by torkelo** 2018-10-18 10:31 UTC

**Comment by marefr** [comment] 2018-10-18 12:17
Duplicate of #13692
