### ISSUE TITLE
Panel of Ajax plugin does not load until you scroll in view

### ISSUE THREAD

**Issue by jayden-xie** [grafana/grafana#26753] opened 2020-08-01 13:14 UTC
**What happened**: 
I was using Ajax panel to load iframes in Grafana v6.1.4, but it failed to load after upgrading to v7.0
You have to scroll to the end of the panel in view to get it load.
When you are looking at the iframe panel, change time frame does not trigger the reload.
The issue is also raised here 
- https://github.com/ryantxu/ajax-panel/issues/71

And official blog about this: https://grafana.com/blog/2019/07/08/a-closer-look-at-lazy-loading-grafana-dashboards/

**What you expected to happen**:
Load the iframes automatically, no need to lazy load for me, it's already loaded when I scroll to it.
It's annoying that have to scroll to the page end, in this way you can see the panel loading.
**Can we get lazy loading configurable? Enable it by default, but I can also disable it.**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I think it's related to PR:
https://github.com/grafana/grafana/pull/15554/files @torkelo 
https://github.com/grafana/grafana/pull/16877/files @ryantxu 

**Environment**:
- Grafana version: v7
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: ryantxu-ajax-panel
- Others:

**Comment by aknuds1** [comment] 2020-08-01 13:15
Can you try version v7.1.1 since that's the latest?

**Comment by aknuds1** [comment] 2020-08-01 13:17
@ryantxu Can you have a look at this since it's your plugin?

**Comment by torkelo** [comment] 2020-08-01 13:24
Panels load as they come into view this is by design , added in 6.2

**Comment by jayden-xie** [comment] 2020-08-01 13:25
I tried 7.1.1 just now, same issue.

**Comment by csaladenes** [comment] 2020-08-03 00:16
@torkelo This is not the issue what you closed for. I have another description here: https://github.com/ryantxu/ajax-panel/issues/71
But, fair enough, it might be a @ryantxu panel thing, rather than `grafana` core.

**Comment by torkelo** [comment] 2020-08-03 05:04
Sorry i thought it was simpel scroll into view issue

**Comment by torkelo** [comment] 2020-08-04 05:51
I think it's likely an issue in the ajax plugin as we do not have any other issue like this with other old angular plugins

**Comment by csaladenes** [comment] 2020-08-04 14:01
> I think it's likely an issue in the ajax plugin as we do not have any other issue like this with other old angular plugins

Cool - we can keep [this](https://github.com/ryantxu/ajax-panel/issues/71) issue on the AJAX panel page then. And close this one.

**Closed** 2020-08-04 14:32 UTC
