### ISSUE TITLE
Show context missing entries

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#32044] opened 2021-03-16 22:28 UTC
**What happened**:
Using `show context` feature doesn't show all neighboring entries.

**What you expected to happen**:
Display neighboring entries.

**How to reproduce it (as minimally and precisely as possible)**:
I search for `level:ERROR` shows two similar entries. One is at `@timesamp` `2021-03-16T16:22:22.140Z`, and another at `2021-03-16T16:22:22.143Z`.
![image](https://user-images.githubusercontent.com/22418250/111388686-66b25600-86b8-11eb-89f7-cbb677eccdd8.png)

Trying to investigate what http requests triggered the error, so I expected `show context` to display nginx access log entries.
Clicking `show context` on `2021-03-16T16:22:22.140Z` entry doesn't show any previous entries (bottom pop-up panel is empty).
![image](https://user-images.githubusercontent.com/22418250/111389606-ebea3a80-86b9-11eb-9ff8-680e1beebcaa.png)

But, manually searching `event.module:nginx` shows multiple entries at `@timestamp=2021-03-16T16:22:22.000Z`. These entries should be visible in `show context`.
![image](https://user-images.githubusercontent.com/22418250/111388494-0cb19080-86b8-11eb-8d3a-7bf0a7180033.png)

**Anything else we need to know?**:
_msearch request:
```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"log-*"}
{"size":10,"query":{"bool":{"filter":[{"range":{"@timestamp":{"lte":1615911742140,"format":"epoch_millis"}}}]}},"sort":[{"@timestamp":"desc"},{"_doc":"desc"}],"search_after":[1615911742140,240232]}
```
response contains the required entries, they just aren't shown:
```
{
  "took": 69,
  "responses": [
    {
      "took": 69,
      "timed_out": false,
      "_shards": {
        "total": 9,
        "successful": 9,
        "skipped": 0,
        "failed": 0
      },
      "hits": {
        "total": {
          "value": 10000,
          "relation": "gte"
        },
        "max_score": null,
        "hits": [
          { <--first entry start
            .....
              "@timestamp": "2021-03-16T16:22:22.000Z",
            ....
            }, <--first entry end
            .... <-- another 9 entries
            "sort": [
              1615911742000,
              49140
            ]
          }
        ]
      },
      "status": 200
    }
  ]
}
```

**Environment**:
- Grafana version: Grafana v7.4.1 (07649d1313)
- Data source type & version: Elasticsearch 7.10.1
- OS Grafana is installed on: docker
- User OS & Browser: Firefox 86.0 (64-bit)
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment] 2021-04-23 10:55
Hi @cdalexndr thanks for reporting this.

Unfortunately, I'm not able to reproduce this issue, it seems like everything works as expected for me.

The weird thing is in the context panel you see `Found 10 rows` but nothing shows up. this means the panel knows about those results but somehow it doesn't show them.

I'm wondering if this is a rendering issue. Do you, by any chance, get any js error at runtime? and does the same thing happen in the latest grafana?

Thank you :)

**Comment by Elfo404** [comment] 2021-05-14 09:20
Closing this as it's lacking some more information and I wasn't able to reproduce it. Please feel free to follow-up with more info and we can reopen it

**Closed by Elfo404** 2021-05-14 09:20 UTC
Labels: area/explore, datasource/Elasticsearch, needs more info
