### ISSUE TITLE
[Bug] Not possible to set auto_assign_org_id via environment variable

### ISSUE THREAD

**Issue by gzzo** [grafana/grafana#12801] opened 2018-08-02 16:07 UTC
This was added in #12401 , looks like something is missing to make it work in Docker.

Steps to reproduce:

1. `docker run -d -p3000:3000 -e GF_USERS_AUTO_ASSIGN_ORG=true -e GF_USERS_AUTO_ASSIGN_ORG_ID=2 grafana/grafana:master`

2. `curl -s http://admin:admin@localhost:3000/api/admin/settings | jq ".users.auto_assign_org_id"`

Should return 2, it currently returns 1 (the default).  

(It's irrelevant that the organization doesn't exist, it will still return 1 if you create the organization).

**Comment by gzzo** [comment] 2018-08-02 16:31
The issue wasn't particular to Docker.  The setting was ignored completely when used as an environment variable.

**Comment by marefr** [comment] 2018-08-02 16:46
Duplicate of #12800

**Comment by marefr** [comment] 2018-08-02 16:47
I think what's missing is that he auto_assign_org_id should be set in the default.ini file

**Comment by marefr** [comment] 2018-08-02 16:48
Sorry closed to fast. Didn't notice your PR.

**Comment by marefr** [comment] 2018-08-02 16:50
Fixed by #12802

**Closed by marefr** 2018-08-02 16:50 UTC
Labels: comp: backend/config, type: bug
