### ISSUE TITLE
grafana version 8.5.0 --> 8.5.3  import Upload json file not work

### ISSUE THREAD

**Issue by jicki** [grafana/grafana#49292] opened 2022-05-20 02:00 UTC
```
grafana version 8.5.0 --> 8.5.3   import Upload json file not work
```

**Comment by elboulangero** [comment] 2022-05-20 02:53
Reported 2 weeks ago here: https://github.com/grafana/grafana/issues/48783

Apparently fixed somewhere on the master branch, but not fixed in `8.5.3` indeed, I can confirm that `8.5.3` is still broken.

**Comment by auwaerter** [comment] 2022-05-20 07:11
Just wanted to give my two cents here, detected the same with `8.5.3` after an update :)

**Comment by thornung** [comment] 2022-05-20 10:36
Import via fileupload is broken since 8.5.2. Version 8.5.1 is ok.
![image](https://user-images.githubusercontent.com/25007740/169510358-ebb2774b-4c45-46a2-89ce-b4fb309fd30f.png)

**Comment by zuchka** [comment] 2022-05-20 19:44
added to the 8.5.4 milestone:

https://github.com/grafana/grafana/pull/48766

**Closed by zuchka** 2022-05-20 19:44 UTC
