### ISSUE TITLE
[Feature Request] Playlist cycle between template variables

### ISSUE THREAD

**Issue by evandro-portugal** [grafana/grafana#4799] opened 2016-04-22 20:46 UTC
Hello, 
I remember an older version that was being made by @utkarshcmu about this, but it was left behind because of all the changes that had been made to code of everything for the new version.
The thing is, the playlist is very useful, but it can (and should!) be even more useful with one thing that is missing, the ability to cycle through template variables of a dashboard.
Being able to choose to cycle between variables at the end of each cycle of the playlist or stay in a dashboard, cycling through all the variables before changing the dashboard.
A use case, that I think that everyone have, is a dashboard where we have a template variable to show different servers, so when we use this dashboard in a playlist we are able to monitor just one of these servers... so definitely it will be useful to have this variable changed to every value before changing to the next dashboard.
Off course this could be extended, letting us choose which variable value we want to see in the playlist and not all of them for example, but I don't think this would be necessary at first, a simple implementation to cycle through every value available would be excelent already.
I know we are already on beta to version 3.0, but since persistent playlist is being added now, this feature would fit nicely with this version, but even if it is not possible, it would be very nice if considered.

Cheers, keepup the very good work!

**Comment by ddes** [comment] 2016-05-02 15:17
+1, 
could be so useful !

**Comment by jrbeilke** [comment] 2016-05-26 19:15
+1 

We have a number of templated dashboards that we would like to cycle through in a playlist with different combinations of variables.

**Comment by utkarshcmu** [comment] 2016-06-16 23:03
#773 is a dupe of this.

**Comment by lmt73** [comment] 2017-02-15 21:38
+1

**Comment by daniellee** [comment] 2017-03-28 09:38
Closing due to dupe #773

**Closed by daniellee** 2017-03-28 09:38 UTC
Labels: comp: playlist, type: feature request
