### ISSUE TITLE
[Traces] Search engine

### ISSUE THREAD

**Issue by olivierboudet** [grafana/grafana#27421] opened 2020-09-07 10:07 UTC
**What would you like to be added**:

At the moment we can display trace details by its ID. It would be useful to allow displaying all traces or searching on some fields.
Basically, it would be useful to have someting similar as the search page of Jaeger UI.

**Why is this needed**:

To find slowest transactions, or transactions with some tags, etc

**Comment by zoltanbedi** [comment] 2020-09-07 11:33
Hi @olivierboudet, thanks for opening this issue but I think it is a duplicate of https://github.com/grafana/grafana/issues/24953

**Closed by zoltanbedi** 2020-09-07 11:33 UTC
Labels: datasource/Jaeger
