### ISSUE TITLE
Allow alerts with multiple conditions to be either grouped or individual alerts

### ISSUE THREAD

**Issue by calebtote** [grafana/grafana#12487] opened 2018-07-02 17:51 UTC
Currently, if you have an alert configured with multiple conditions the alert will fire once if any of the conditions fail. However, that's not always the desired result -- in order to avoid creating multiple duplicate panels for multiple alerts, we have several conditions specified for the same Alert ID, with slight variances in the condition metrics (usually an environment specifier).

Ideally, we would have an option to either have each condition part of the general alert "group" or have it fire new alerts whenever that specific condition is tripped.

An example would be the following:

We have a panel that monitors CPU% for a certain service across certain hosts. We have a single dashboard with an environment variable `$env`. Since we can't specify alerts for metrics containing variables, we explicitly define the metrics without the variable, and hide them from the panel. 

**Alert Name:**  CPU Usage
`my.metric.prod.cpu.util`
`my.metric.test.cpu.util`

**Conditions:**
`if A is above 80`
`OR`
`if B is above 90`

Currently, if either of the metrics above a tripped, we get a generic alert notification about CPU Usage, with no real indication for which environment. Further, if `test` trips for 10 minutes, and during that time `prod` also trips, we get no new alert notifications.

The obvious solution to this is to have distinct dashboards for each environment. The reality of this solution though is that it creates duplicate work, duplicate data, and is extremely prone to user-error when a change needs to be made for a panel (we then would need to make that change on n-dashboards rather than the single one)

**Comment by marefr** [comment] 2018-07-03 09:50
Thanks for the thorough description, however there's already a feature request open for per series state change tracking. It's included in our [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md#long-term-4---8-months) targeting long-term if nothing unexpected shows up.

Duplicate of #6041

**Closed by marefr** 2018-07-03 09:50 UTC
