### ISSUE TITLE
v7: table panel to support coloring cells with non-numeric values 

### ISSUE THREAD

**Issue by w-bazan** [grafana/grafana#24878] opened 2020-05-19 15:41 UTC
**What would you like to be added**:

can table panel support coloring cells with a fixed color if they represent a non-nunemric value, please?

**Why is this needed**:

better data presentation

**Comment by torkelo** [comment] 2020-05-20 05:22
Duplicate of https://github.com/grafana/grafana/issues/24557

**Comment by w-bazan** [comment] 2020-05-20 06:12
> Duplicate of #24557

Hi Torkelo, thanks for taking time to look into my issue. I read the referenced issue and cannot quite figure out how is it related. It says nothing about coloring. Am I missing something? Would you mind to double check please or explain a bit, please?

Thanks again

**Comment by torkelo** [comment] 2020-05-20 08:12
sorry posted this on wrong issue :)

**Comment by addtzg** [comment] 2020-07-07 09:12
It really would be helpful, even simple scenarios like "true" - green, "false" - red are now impossible.

**Comment by pkolyvas** [comment] 2021-08-20 16:27
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). This issue is being moved to [Discussions](https://github.com/grafana/grafana/discussions) or has been moved from our issues list, depending on where you're seeing this message. 

 We hope to use the discussion thread to continue building use cases, and additional evidence based on engagement/voting, in order to help us prioritize this feature request later on down the road. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!

**Closed** 2021-08-20 16:38 UTC
Labels: area/panel/table, gh-discussions
