### ISSUE TITLE
[Feature request] histogram normalize support

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#8149] opened 2017-04-18 03:30 UTC
Support normalize by percent value. (draw count / total count)

Quote from original comment.
https://github.com/mtanda/grafana-histogram-panel/issues/42#issuecomment-255207102

> In IE - note the blank panels where the histograms should be
> ![image](https://cloud.githubusercontent.com/assets/3433421/19575126/13dea28e-96db-11e6-994a-e89b512bb214.png)
> 
> In Chrome - this is how it's supposed to look
> ![image](https://cloud.githubusercontent.com/assets/3433421/19575130/18765968-96db-11e6-9728-a2e2ac6fd136.png)
> 
> Hi, thanks for the response. Screenshots are attached. If you have any thoughts on where the issue is, I'd be happy to test it. I haven't gotten deep enough into Grafana to recognize where the error is coming from.
> 
> On a side note I love the panel though... the only thing I wish I could do was to normalize the histograms so that they're displayed _as if_ they had the same total count. That would help visualize probability distribution differences between the two. This could probably also be accomplished by being able to put a second histogram on a different Y axis.

**Comment by torkelo** [comment] 2017-04-18 11:48
I am sorry I can't understand what you mean? Can you describe more fully?

**Comment by mtanda** [comment] 2017-04-18 12:43
Sorry for my poor english.
To compare histogram in two graph panel, we need to align same Y-axis.

If data distribution is like following,
1-10: 500
11-20: 300
21-30: 200
31-100: 0
(total data point count is 1000)

Display probability of value apearance,
1-10: 50 (= 500/1000 * 100)
11-20: 30 (= 300/1000 * 100)
21-30: 20 (= 200/1000 * 100)
31-100: 0

**Comment by mtanda** [comment] 2017-06-28 08:50
https://github.com/grafana/grafana/pull/8727 might fix this issue.

**Comment by alexanderzobnin** [comment] 2017-06-28 09:13
@mtanda yea, I've added default _percent_ option.  Also, you can align all panels with max=1 and compare results.

**Comment by mtanda** [comment] 2017-06-28 09:35
@alexanderzobnin Its' great! Thanks!!

**Comment by torkelo** [comment] 2017-08-28 12:12
closing in favor of 7 dupe of https://github.com/grafana/grafana/issues/8788

**Closed by torkelo** 2017-08-28 12:12 UTC
Labels: state: needs more detail
