### ISSUE TITLE
Public dashboards referencing other public dashboards shows unauthorised.

### ISSUE THREAD

**Issue by h3inzzz** [grafana/grafana#61392] opened 2023-01-12 14:32 UTC
We have been building dashboards internally and it seems that if you create a public dashboard as a 'landing page' that has a list of other public dashboards within a 'dashboard list' panel, the application returns unauthorised when accessing this externally or through a private browser.

The other 2 referenced dashboards are public and can be accessed externally, but when they are referenced within the dashboard list panel, the unauthorised banner appears.

![image](https://user-images.githubusercontent.com/7142634/212093567-7bdb32b3-5de2-4049-96c9-0829b8d2cfc4.png)

We would expect this to not return unauthorised, but instead to allow a user to click into the 2 other public dashboards via the dashboard list panel.

Tested on firefox / ubuntu desktop. `Grafana v9.3.2 (21c1d14e91)`

**Comment by tonypowa** [comment] 2023-01-12 21:16
Thanks for creating this issue, @h3inzzz 

assuming that the 2 dashboards are configured to be public, like so:

![image](https://user-images.githubusercontent.com/45235678/212181911-48010009-df9e-442e-9aa8-91b24b5f1f33.png)

how is that 'external' access done? 

how many users are experiencing this error? 

how do the dashboards permissions look like?

![image](https://user-images.githubusercontent.com/45235678/212182651-e0c679ba-34b2-4e9b-8f7a-d75ce497b6eb.png)

in any case, please list the steps you take to reproduce the error

thank you!

**Comment by evictorero** [comment] 2023-04-13 20:10
The dashboard list panel is not supported in public dashboards because it uses the authenticated API to get a list of dashboards, which is impossible from an unauthenticated view like the public dashboard. 
In order to have a panel that lists all public dashboards we would need a new Panel with different functionality.

**Comment by evictorero** [comment] 2023-07-27 17:20
Closing because this panel does not make sense in a public dashboard, we would need a new panel that shows only public dashboards. Similar functionality could be achieved by using a Text panel with a list of the public dashboards links.

**Closed by evictorero** 2023-07-27 17:20 UTC
Labels: area/panel/dashboard-list, area/public-dashboards, team/grafana-dashboards
