### ISSUE TITLE
Log lines are reordered when shown in Ascending order

### ISSUE THREAD

**Issue by petuhovskiy** [grafana/grafana#50307] opened 2022-06-07 12:16 UTC
**What happened**: 

@LizardWizzard told me that sometimes log messages get reordered when looking at them in Grafana. When I tried to reproduce this issue, I discovered that this happens only when you use Ascending logs order (oldest first). This bug exists both in logs panel and in Explore section.

Default logs order displays logs correctly with decreasing timestamps:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/8150127/172371199-6ef78cba-c82a-446b-b2f8-cc56c7c6b1aa.png">

Flipped logs order displays log timestamps in mixed order (look at the first 5 lines):
<img width="459" alt="image" src="https://user-images.githubusercontent.com/8150127/172371556-64ec1ec3-4408-41c4-a79b-acf89a30fd8e.png">

**What you expected to happen**:

I expected Ascending log order to work as an exact reverse of Descending log order.

**How to reproduce it (as minimally and precisely as possible)**:

That happens pretty often in our setup, I guess you just need to write about ~1000 log lines per second and try to Explore them with flipped order.

**Anything else we need to know?**:

Our promtail configuration is very basic and doesn't have a pipeline stage to parse timestamps from the text.

I looked at the frontend code briefly, and it seems that logs order is defined here: https://github.com/grafana/grafana/blob/277a83215c1e20ff8c93768f93edf92d60deee5f/packages/grafana-data/src/utils/logs.ts

**Environment**:
- Grafana version: Grafana v8.3.5 (a53fcac7b1)
- Data source type & version: Loki Helm Chart 2.8.2 (https://github.com/grafana/helm-charts/releases/tag/loki-2.8.2)
- OS Grafana is installed on: -
- User OS & Browser: macOS, Firefox
- Grafana plugins: -
- Others:

**Comment by ashharrison90** [comment] 2022-06-07 13:17
hi @petuhovskiy 👋 

i can't repro this on my local loki instance or grafana play.

are you able to create a minimal reproduction on [play](https://play.grafana.org/)? there's a loki instance already connected there

**Comment by gabor** [comment] 2022-06-09 13:01
hi @petuhovskiy thanks for reporting this. could you get us the csv-data for the page where the ordering is wrong?

1. go to explore
2. run the query, and reproduce the problem
3. please try to reproduce it with as few log lines as possible (you can limit the number of log lines using the `line limit` field in the loki query field)
4. click on `[inspector]`, then `[data]` tab, and there click `[Download CSV]`
5. remove all secret/private/confidential info from the CSV file
6. attach the CSV file here.

thanks!

**Comment by gabor** [comment] 2022-06-09 15:55
@petuhovskiy thanks for the data! i think i see now where the problem is.

you see, in your screenshots, the timestamps that are shown are not the timestamps that Loki returned for the given log-line. the timestamps in the screenshots are the beginning of the log-line.

but, loki and grafana orders the lines based on the timestamp associated with the given log-line.
Loki provides nanosecond-precision timestamps, you can see them when you open a log-line's details, look for the `tsNs` field there. it's a long number.

now, let's look at the screenshot you provided in https://github.com/grafana/grafana/issues/50307#issuecomment-1148775765

the problem is the fifth line, correct? based on the displayed timestamp, it should  be sooner than the fourth line.

but, based on the csv-provided, i reconstructed their loki-nanosecond-timestamps:

```
1654612515059731000 2022-06-07T14:35:15.059678912Z
1654612515059731000 2022-06-07T14:35:15.058596457Z
```

as you can see, Loki says they happened at the exactly same time, the same nanosecond. so they can be ordered in either way.

i think the solution is to configure the software that sends data to loki to set the timestamp to be in sync with the log-line-timestamp, but i don't know how that part works exactly. pinging @grafana/loki-squad 😄

**Comment by gabor** [comment] 2022-07-12 06:06
as this is not a bug in Grafana, i'm closing this issue. if you need help with configuring the "send data to loki" part to send good timestamps, i recommend asking in the loki forums at https://community.grafana.com/c/grafana-loki/41

**Closed by gabor** 2022-07-12 06:06 UTC
Labels: datasource/Loki, area/panel/logs
