### ISSUE TITLE
A problem of rendering graph

### ISSUE THREAD

**Issue by sunnut** [grafana/grafana#14477] opened 2018-12-13 08:02 UTC
When I render the graph, I can change the x-axis begin time & end time by the following code:
`
graph.ts

function addTimeAxis(options) {
 var ticks = panelWidth / 100;
 let intervalMilliSeconds = 300000;
 ctrl.range.from.add(intervalMilliSeconds, 'milliseconds');
 ctrl.range.to.add(intervalMilliSeconds, 'milliseconds');
 ...
}

`
The problem is that how can I change the time in the data by an easy way.

**Comment by daniellee** [comment] 2018-12-14 06:46
Not sure what you are trying to do but it looks like you are trying to write a plugin for Grafana? There are lots of community plugins: https://grafana.com/plugins Try and find one that is similar to what you want to do to get started.

Closing this as it is not a bug or feature request for Grafana. Questions can be asked on the community site: https://community.grafana.com/

**Closed by daniellee** 2018-12-14 06:46 UTC
Labels: type: question
