### ISSUE TITLE
Unable start Docker grafana/grafana:latest ARMv7

### ISSUE THREAD

**Issue by corasaniti** [grafana/grafana#73779] opened 2023-08-24 15:38 UTC
### What happened?

Unable to start Docker container with image grafana/grafana:latest (10.1.0) 
For ARMv7 architecture I get the following error
[_grafana_logs.txt](https://github.com/grafana/grafana/files/12431057/_grafana_logs.txt)

Everything works fine with the grafana/grafana:main version (10.2.0)

### What did you expect to happen?

start Docker container with ARMv7 and latest docker tag

### Did this work before?

10.0.4

### How do we reproduce it?

start docker container

### Environment (with versions)?

Grafana: 10.1.0
OS: Raspian ARMv7 
Browser:

### Grafana platform?

Docker

**Comment by BMerz** [comment] 2023-08-24 16:09
I think this is the same as #73781. We reported simultaneously.

**Comment by kminehart** [comment] 2023-08-24 21:41
Indeed, sounds like a duplicate of https://github.com/grafana/grafana/issues/73781. I'll keep it open for now until we confirm that they are the same issue.

**Comment by kminehart** [comment] 2023-08-27 15:20
I'll close this in favor of https://github.com/grafana/grafana/issues/73781 since there seems to be more activity there. Thanks for the report.

**Closed by kminehart** 2023-08-27 15:20 UTC
Labels: type/build-packaging, area/docker, triage/needs-confirmation

**Comment by corasaniti** [comment] 2023-08-28 14:18
@kminehart 

Why did you close this issue? The problem persists has not been resolved.
grafana/grafana:latest (10.1.0) tag doesn't work on Raspberry with Raspian Buster ARMv7
Everything works fine with the grafana/grafana:main version (10.2.0)

**Comment by corasaniti** [comment] 2023-08-28 14:27
@kminehart 
Ok thanks I subscribed to issue https://github.com/grafana/grafana/issues/73781 in order to receive updates
