### ISSUE TITLE
Dashboards: When i clicked Tempo`s Table panel Trace, Spans are appeared strange area.

### ISSUE THREAD

**Issue by pingping95** [grafana/grafana#72070] opened 2023-07-21 02:32 UTC
### What happened?

When i clicked a tempo trace ID, Spans are appeared at strange area.

You can see below picture.

<img width="958" alt="image" src="https://github.com/grafana/grafana/assets/67780144/38966a7e-2d7e-48fa-948e-483ae9e1cb40">

### What did you expect to happen?

The spands should be visible just below the trace.

### Did this work before?

I don't know, because I've been playing POC lately.

### How do we reproduce it?

1. Add Panel
2. Set DataSource : Tempo
3. Set Panel Type : Table
4. Finish creating table
5. When i want to see trace`s spans, The span is seen in a strange place.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: v10.0.1 (5a30620b85)
OS: MacOS
Browser: Chrome, Safari Both produced

### Grafana platform?

Kubernetes

### Datasource(s)?

Tempo 2.1.1 (Latest)

**Comment by usmangt** [comment] 2023-07-25 09:15
Hi @pingping95,

Thanks for opening this issue.

I tried to reproduce this on Grafana version 10.0.2 which is running on play.grafana.com

This is how it shows the span-ID and overall looks fine

![image](https://github.com/grafana/grafana/assets/69509548/8b818d52-927d-43f8-85db-86a9bd0a19b0)


I am not sure but since when have you noticed the change in display behavior e.g. after a recent update? (if yes, then please tell us the version).

**Comment by pingping95** [comment] 2023-07-25 13:07
@usmangt 
When i upgrade my company`s grafana version to 10.0.2, Issue was gone.

thanks for support !

**Comment by pingping95** [comment] 2023-08-10 03:06
@usmangt 

Hi. reprocudes in grafana 10.0.2 .

<img width="1327" alt="image" src="https://github.com/grafana/grafana/assets/67780144/77c571cf-7bff-4eb0-b325-be174c890bb6">

**Comment by joey-grafana** [comment] 2023-08-25 11:58
Fixed in https://github.com/grafana/grafana/pull/71953

**Closed by joey-grafana** 2023-08-25 11:58 UTC
Labels: datasource/Tempo, triage/needs-confirmation
