### ISSUE TITLE
Slack notificaitons not sending after upgrade

### ISSUE THREAD

**Issue by itmecho** [grafana/grafana#21461] opened 2020-01-13 10:37 UTC
**What happened**:
Upgraded from `6.4.2` to `6.5.2`. Email alerts continue being sent with no problem but slack alerts stop coming through. Sending the test notification in the "Notification Channel" configuration works fine.

![Notification Channel](https://i.snipboard.io/SubGX8.jpg)

![Working Test Notification](https://i.snipboard.io/9XELSO.jpg)

**What you expected to happen**:
Slack alerts should continue as normal. I couldn't see anything to do with alerting in the breaking changes since `6.4.2`

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade from `6.4.2` to `6.5.2` with an Email notification channel and a Slack notification channel as the defaults

**Anything else we need to know?**:
I don't think so

**Environment**:
- Grafana version: `6.4.2` -> `6.5.2`
- Data source type & version: Prometheus (not really relevant)
- OS Grafana is installed on: Official docker image (`grafana/grafana:6.5.2`)
- User OS & Browser: Arch Linux, Firefox Developer Edition (not really relevant)
- Grafana plugins: None
- Others: None

**Comment by itmecho** [comment] 2020-01-13 10:57
Downgrading back to `6.4.2` fixes the issue

**Comment by marefr** [comment] 2020-01-13 12:49
Duplicate of #21018

**Closed by marefr** 2020-01-13 12:50 UTC
