### ISSUE TITLE
GraphPanel - feature: Show non time series partially stacked bar chart

### ISSUE THREAD

**Issue by Crewman123** [grafana/grafana#22531] opened 2020-03-03 10:02 UTC
I have a project where I have to sum up all the productive and idle time for the selected time frame and like to show the result as stacked bars also I would like to have another bar that shows the planed machine running time in the selected time frame.

I came up with this:
![stackBars](https://user-images.githubusercontent.com/29308103/75763885-46c62380-5d3d-11ea-9737-b263751f74b4.PNG)

Then I tried using series override option to stack Idle and Running, by using the stack override option.
![seriesOverride](https://user-images.githubusercontent.com/29308103/75763950-69583c80-5d3d-11ea-8123-28e4815aeef5.PNG)

Nothing happened by the override. I would expect something like this, when using the series override:
![expected](https://user-images.githubusercontent.com/29308103/75764056-960c5400-5d3d-11ea-97f9-a0e80f412d28.PNG)

**Comment by torkelo** [comment] 2020-03-03 10:56
duplicate of https://github.com/grafana/grafana/issues/7949

**Closed by torkelo** 2020-03-03 10:56 UTC
