### ISSUE TITLE
[UI Kit] Dropdown list does not stay top when use Modal

### ISSUE THREAD

**Issue by JBrVJxsc** [grafana/grafana#35126] opened 2021-06-02 17:00 UTC
<img width="768" alt="Screen Shot 2021-06-02 at 9 57 51 AM" src="https://user-images.githubusercontent.com/3367239/120520952-43c74200-c389-11eb-9eae-6120e206059c.png">

**What happened**:

Dropdown list does not stay top when use Modal

**What you expected to happen**:

Dropdown list should stay at top

**How to reproduce it (as minimally and precisely as possible)**:

Show a dropdown list with extensive items inside and put it inside a modal.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Chrome, MacOS
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment] 2021-06-03 09:44
Hmm, honestly I feel like that this is the right behaviour but lets ask @grafana/grafana-frontend-platform team about their thoughts?

**Comment by jackw** [comment] 2021-06-03 11:00
This looks like a duplicate of #32588 which was fixed in #33939 and should be available in Grafana v8

**Closed** 2021-08-31 07:34 UTC
Labels: area/grafana/ui
