### ISSUE TITLE
Search: Search for a dashboard not only by name but also by description

### ISSUE THREAD

**Issue by JJinMaine** [grafana/grafana#21801] opened 2020-01-28 17:42 UTC
**What would you like to be added**:

When I search for a dashboard, I'd like to search through the description as well as the name.

**Why is this needed**:

Many times my description may contain more detailed information than the actual dashboard title. I want to be able to keep my dashboard name in one format and add a larger and more searchable description.

Thanks!

**Comment by marefr** [comment] 2020-01-28 18:07
Duplicate of #15257

**Closed by marefr** 2020-01-28 18:07 UTC
