### ISSUE TITLE
Failed to look up user based on cookie - invalid connection

### ISSUE THREAD

**Issue by huynhsamha** [grafana/grafana#20913] opened 2019-12-06 02:07 UTC
**What happened**:
Sometime my session is auto logout when request `/api/login/ping` is called

**What you expected to happen**:
Session should be kept.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know how to reproduce this. Grafana has worked for a long time, but now I maybe kicked out while working with grafana.

**Anything else we need to know?**:
This is log in the server that maybe help you

```
t=2019-12-06T08:46:15+0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/... status=302 remote_addr=10.xx.xx.xx time_ms=0 size=260 referer=http://my.domain.com/login
t=2019-12-06T08:46:15+0700 lvl=info msg="state check" logger=oauth queryState=eefc0aced83daf4dcdf3a3a3e20b06... cookieState=eefc0aced83daf4dcdf3a3a3...
t=2019-12-06T08:46:15+0700 lvl=info msg="Successful Login" logger=http.server User=myuser@my.domain.com
t=2019-12-06T08:46:15+0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/... status=302 remote_addr=10.xx.xx.xx time_ms=322 size=24 referer=http://my.domain.com/login
t=2019-12-06T08:46:52+0700 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="invalid connection"
t=2019-12-06T08:46:53+0700 lvl=eror msg="Failed to look up user based on cookie" logger=context error="invalid connection"
t=2019-12-06T08:46:53+0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/annotations status=401 remote_addr=10.xx.xx.xx time_ms=0 size=26 referer="http://my.domain.com/d/abcd/dashboard?orgId=1?morething..."
t=2019-12-06T08:46:53+0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=10.xx.xx.xx time_ms=0 size=26 referer="http://my.domain.com/d/abcd/dashboard?orgId=1?morething..."
t=2019-12-06T08:46:53+0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/api/tsdb/query status=401 remote_addr=10.xx.xx.xx time_ms=0 size=26 referer="http://my.domain.com/d/abcd/dashboard?orgId=1?morething..."
t=2019-12-06T08:46:54+0700 lvl=info msg="Successful Logout" logger=http.server User=
t=2019-12-06T08:46:54+0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/logout status=302 remote_addr=10.xx.xx.xx time_ms=0 size=29 referer="http://my.domain.com/d/abcd/dashboard?orgId=1?morething..."
t=2019-12-06T08:46:54+0700 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=10.xx.xx.xx time_ms=0 size=26 referer="http://my.domain.com/d/abcd/dashboard?orgId=1?morething..."
```

I think because this error **Failed to look up user based on cookie - invalid connection** make my session logout. 

**Environment**:
- Grafana version: 6.0.0
- Data source type & version: I don't think data source cause this problem
- OS Grafana is installed on: Centos
- User OS & Browser: Ubuntu, Chrome
- Grafana plugins: nothing
- Others: My database for Grafana is MySQL

**Comment by aknuds1** [comment] 2019-12-06 08:31
Given your "invalid connection" errors in the log, it looks as if Grafana is having trouble connecting to your database? Have you investigated this issue?

**Comment by aknuds1** [comment] 2019-12-06 08:37
Closing as duplicate of #15316.

**Closed by aknuds1** 2019-12-06 08:37 UTC

**Comment by aknuds1** [comment] 2019-12-06 08:42
You might want to look into the [conn_max_lifetime](https://grafana.com/docs/grafana/latest/installation/configuration/#conn-max-lifetime) configuration parameter as well, I hear.

**Comment by huynhsamha** [comment] 2019-12-06 08:44
Hi @aknuds1 

I've just see this configure, I think it caused invalid connection

Thanks

**Comment by aknuds1** [comment] 2019-12-06 08:45
Great, I hope you figure it out :) Otherwise, please consult #15316.
