### ISSUE TITLE
Query editor adds single quote to variable when used in graphite function

### ISSUE THREAD

**Issue by munokar** [grafana/grafana#11927] opened 2018-05-14 12:43 UTC
Hello,

we have some dashboards that use a variable to display the Top 5 / 10 / 15 entries of a series.
We have noticed that after modifying the query (originally created in Grafana 4) the query is not working anymore.

![grafik](https://user-images.githubusercontent.com/26091678/39997767-4dafe78c-5784-11e8-9f93-7ca811bd2846.png)

The error is an internal server errors with details:

```
Traceback (most recent call last):&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1817, in wsgi_app&#10;    response = self.full_dispatch_request()&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1477, in full_dispatch_request&#10;    rv = self.handle_user_exception(e)&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1381, in handle_user_exception&#10;    reraise(exc_type, exc_value, tb)&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1475, in full_dispatch_request&#10;    rv = self.dispatch_request()&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1461, in dispatch_request&#10;    return self.view_functions[rule.endpoint](**req.view_args)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 401, in render&#10;    series_list = evaluateTarget(context, target, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 496, in evaluateTarget&#10;    result = evaluateTokens(requestContext, tokens, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 506, in evaluateTokens&#10;    return evaluateTokens(requestContext, tokens.expression, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 514, in evaluateTokens&#10;    arg, data_store) for arg in tokens.call.args]&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 506, in evaluateTokens&#10;    return evaluateTokens(requestContext, tokens.expression, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 520, in evaluateTokens&#10;    ret = func(requestContext, *args, **kwargs)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/functions.py&#34;, line 1575, in highestMax&#10;    result_list = sorted(seriesList, key=lambda s: max(s))[-n:]&#10;TypeError: bad operand type for unary -: 'unicode'&#10;
```

If I toggle the editor I can see that single quotes are added before and after the variable ($Top):

![grafik](https://user-images.githubusercontent.com/26091678/39997915-b9f9299e-5784-11e8-9d9a-2e9974141d1d.png)

If I manually remove the single quotes. The query is performed successfully!
If I now toggle between the edit modes everything stays OK until I change the query in the dropdown editor mode.

Regards
Timo

Please include this information:
### What Grafana version are you using?
5.1.2
### What datasource are you using?
Graphite
### What OS are you running grafana on?
Red Hat Enterprise Linux Server release 7.5 (Maipo)
### What did you do?
Edit existing queries.
### What was the expected result?
Query should display results.
### What happened instead?
Query is showing Error:

```
Traceback (most recent call last):&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1817, in wsgi_app&#10;    response = self.full_dispatch_request()&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1477, in full_dispatch_request&#10;    rv = self.handle_user_exception(e)&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1381, in handle_user_exception&#10;    reraise(exc_type, exc_value, tb)&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1475, in full_dispatch_request&#10;    rv = self.dispatch_request()&#10;  File &#34;/usr/lib/python2.7/site-packages/flask/app.py&#34;, line 1461, in dispatch_request&#10;    return self.view_functions[rule.endpoint](**req.view_args)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 401, in render&#10;    series_list = evaluateTarget(context, target, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 496, in evaluateTarget&#10;    result = evaluateTokens(requestContext, tokens, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 506, in evaluateTokens&#10;    return evaluateTokens(requestContext, tokens.expression, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 514, in evaluateTokens&#10;    arg, data_store) for arg in tokens.call.args]&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 506, in evaluateTokens&#10;    return evaluateTokens(requestContext, tokens.expression, data_store)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/app.py&#34;, line 520, in evaluateTokens&#10;    ret = func(requestContext, *args, **kwargs)&#10;  File &#34;/usr/lib/python2.7/site-packages/graphite_api/functions.py&#34;, line 1575, in highestMax&#10;    result_list = sorted(seriesList, key=lambda s: max(s))[-n:]&#10;TypeError: bad operand type for unary -: 'unicode'&#10;
```

**Comment by azhiltsov** [comment] 2018-06-19 17:12
We also observe this.

**Comment by torkelo** [comment] 2018-06-20 04:49
duplicate of https://github.com/grafana/grafana/issues/2078

**Comment by azhiltsov** [comment] 2018-06-20 06:11
@torkelo I believe you closed it by mistake

**Comment by torkelo** [comment] 2018-06-20 07:14
not sure I did, as there already is an open issue for this (which I linked to)

**Comment by torkelo** [comment] 2018-06-20 07:33
Ok, its a related but new issue introduced in https://github.com/grafana/grafana/commit/3a4e05133e8799a0219f683bc4ca0d9dcb84d2b9#diff-2805d5a9f2c9a0e6e52590b65e8db820 

int func params should not be required for to parsed to numbers, before that commit that test was only applied to parms of type int_or_interval (som functions can take both a number and string for same parameter). 

So to fix this we need to restore render function to this https://github.com/grafana/grafana/blob/f8b8907cc4bafdd0f5fcd39c78af5c96e89867d5/public/app/plugins/datasource/graphite/gfunc.js#L891 

That is only apply the _.isFinite(+value) when paramType === 'int_or_interval'

**Comment by torkelo** [comment] 2018-06-20 09:50
The same change also introduced this bug, https://github.com/grafana/grafana/issues/12355 

The _includes condition there should not be there. It seems the value sometimes is true/false (js boolean not string), and it will also make having a variable there not possible. 

if (paramType === 'boolean' && _.includes(['true', 'false'], value)) {
          return value;
        }

**Comment by DanCech** [comment] 2018-06-20 14:28
In the specific case of highest/lowest you can run the master build of graphite-web which handles numeric strings until this is fixed in Grafana.

https://github.com/graphite-project/graphite-web/pull/2294

**Closed** 2018-08-14 06:52 UTC
Labels: beginner friendly, datasource: Graphite, effort1: small, help wanted, type: bug

**Comment by Surfmobile** [comment] 2019-10-18 10:55
I have the same problem, but for InfluxDB as the storage. I want to be able to do exclude entries that have a tag variable that is empty. I can do this with the manual editor:

WHERE "tag" != ''

But when I try to do this in the visual editor, it ends up as:

WHERE "tag" != ''''

So the quotes get re-quoted. This seems like a bug to me.
