### ISSUE TITLE
Random "Unauthorized" Errors resulting in Logoff using Grafana 9.2.1 in Docker

### ISSUE THREAD

**Issue by Soon5** [grafana/grafana#57485] opened 2022-10-22 13:16 UTC
Hello,

I have a Grafana installation running on my Raspberry PI, using Docker. The Image ist the "latest" which is 9.2.1 when writing this. I am using the default Grafana Authorization. Besides the admin user I created an additional user "user" which has View privileges only.

It doesn't matter whether I use the admin user or the "user" user, I randomly (sometimes after 5 mins, sometimes after some hours) I get logged of...

The configuration settings are vanilla what was provided in the docker image:
login_cookie_name =>grafana_session
login_maximum_inactive_lifetime_duration => 7d
login_maximum_lifetime_duration => 30d

Any suggestions?

Regards

**Comment by chriscareycode** [comment] 2022-10-22 15:29
I am getting much more frequent logouts after upgrading. Debian Linux, no docker.

**Comment by hudeldudel** [comment] 2022-10-22 16:28
May be a duplicate to https://github.com/grafana/grafana/issues/56994 ?

**Comment by Soon5** [comment] 2022-10-22 18:17
Sounds similiar. I will downgrade to 9.1.8 and see whether that solves the problem.

**Comment by Soon5** [comment] 2022-10-22 20:37
Ok, short update. With Grafana 9.1.8 everything is working like charm.

**Comment by mckn** [comment] 2022-10-24 13:15
Duplicate of https://github.com/grafana/grafana/issues/57485

**Closed by mckn** 2022-10-24 13:15 UTC

**Comment by Soon5** [comment] 2022-10-24 13:28
@mckn  I think the "duplicate" reference is wrong, it's a self reference....

**Comment by mckn** [comment] 2022-10-24 13:42
Ahh, super! Thanks @Soon5  <3
