### ISSUE TITLE
Variables such as << labels_values(query,label) >> doesn't work when use Loki datasource

### ISSUE THREAD

**Issue by jurycu** [grafana/grafana#29568] opened 2020-12-03 11:41 UTC
**What happened**:
when i use the query as follow to get the label value in loki,the query filter donsn't work,it get all project label's value in loki

label_values({appname="$appname", org="$org"},project)

**What you expected to happen**:
i want get the project which the appname and org that i choosed

**Comment by cyriltovena** [comment] 2020-12-04 09:19
Dupe of https://github.com/grafana/grafana/issues/25205

**Closed** 2021-01-11 12:45 UTC
Labels: area/dashboard/templating, datasource/Loki, needs investigation, priority/important-longterm
