### ISSUE TITLE
[Feature Request] Template dropdowns part of sticky nav bar

### ISSUE THREAD

**Issue by geekdave** [grafana/grafana#12790] opened 2018-08-01 17:26 UTC
I see that the sticky nav bar was implemented in 5.0 - https://github.com/grafana/grafana/issues/4670 🎉 

This request is to also have the template variable dropdowns be part of that sticky nav bar as well, so that users don't have to scroll all the way back up to change a template variable.  

Thanks!

**Comment by debmalyapan53** [comment] 2019-03-18 13:44
+1

**Comment by ximply** [comment] 2019-03-22 14:58
+1

**Comment by syamsitaufik** [comment] 2019-04-05 02:22
+1

**Comment by FRoGbis** [comment] 2019-05-02 14:27
+1

**Comment by paregupt** [comment] 2019-06-28 01:19
+1

**Comment by Roxanne-tsn** [comment] 2019-07-04 14:19
+1

**Comment by n1nj4888** [comment] 2019-09-05 00:38
I created the linked #18873 so just wondering whether there has been any update after this duplicate feature request was created?

**Comment by GedPL** [comment] 2019-09-25 13:27
+1

**Comment by RandomGHUser** [comment] 2019-11-27 19:26
+1, this is very important for any dashboard that scrolls.  I always want access to my dashboard variables without needing to scroll to the top.

As an example, the following script does this (given that the variables only take up 1 row):
```js
$("dashboard-submenu").detach().insertAfter('.navbar');
$(".scroll-canvas--dashboard").css("height", "calc(100% - 101px)");
```

**Comment by Gauravshah** [comment] 2020-09-30 02:36
it seems this is a duplicate of https://github.com/grafana/grafana/issues/11166

**Comment by aocenas** [comment] 2020-11-11 15:41
Closing this as duplicate https://github.com/grafana/grafana/issues/11166

**Closed by aocenas** 2020-11-11 15:41 UTC
Labels: area/dashboard, type/feature-request
