### ISSUE TITLE
AlertManager (Grafana Unified Alerting) is breaking the MySQL database with deadlocks

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#54096] opened 2022-08-23 14:35 UTC
Grafana is hosted on 2 nodes and load balanced via Traefik. For the database we are using MariaDB cluster of 3 servers and also load balanced via Traefik (TCP loadbalancer).

Some time ago we started having an issue with MariaDB cluster running out of space. Turns out it was generating loads of GRA_* files:
```
[root@grafana-mariadb-2 mysql]# rm -rf GRA*.log
bash: /bin/rm: Argument list too long
[root@grafana-mariadb-2 mysql]# find /var/lib/mysql -name GRA*.log -type f -delete
```

As this issue became a daily issue, we've decided to migrate MariaDB cluster to percona MySQL cluster. After the migration, we've discovered new errors:
```
logger=ngalert t=2022-08-23T14:02:50.214586072Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.234120372Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.251857821Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.348385326Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.366394661Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.401223053Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.488656693Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.534380471Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.58432477Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.624926321Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.638782503Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.65518098Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
logger=ngalert t=2022-08-23T14:02:50.73221567Z level=error msg="failed to save alert state" uid=AvUHC2a7z orgId=1 labels="__alert_rule_namespace_uid__=JS_5X4Hnk, __alert_rule_uid__=AvUHC2a7z, alerting=infra, alertname=<REDACTED>, grafana_folder=ALERTS, service=<REDACTED>" state=Normal msg="Error 1213: Deadlock found when trying to get lock; try restarting transaction"
```

We've tried experimenting with `isolation_level` configuration field in `grafana.ini` but it did not work (btw Grafana translates it to `tx_isolation` which Mysql 8 does not recognize, because [it has been deprecated since MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_tx_isolation)). Tried experimenting with [transaction_isolation](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_transaction_isolation) (using `url = ...`) but this also did not fix anything.

I believe this has to be investigated and fixed by the Grafana team.

Grafana's relevant configuration:
```
[database]
url = mysql://verynice:verysecret@10.10.10.10:3306/grafana

[unified_alerting]
enabled = true
ha_listen_address = ":1234"
ha_advertise_address = "123.123.123.123:3001"
ha_peers = "123.123.123.123:1234,123.123.123.124:1234"
evaluation_timeout = 2m
max_attempts = 10
```

Grafana's version: `9.1.0`

Percona cluster's (MySQL) version: `mysql  Ver 8.0.28-19.1 for Linux on x86_64 (Percona XtraDB Cluster (GPL), Release rel19, Revision f544540, WSREP version 26.4.3)`

**Comment by erkexzcx** [comment] 2022-08-23 14:40
Could it be that integrated alertmanager does **not** work with MySQL **cluster** because it uses some kind of exclusive locks? Those deadlock errors started to appear as soon as 2nd Grafana instance started...

**Comment by glintik** [comment] 2022-08-25 08:19
Hi @erkexzcx,

Could you please show what query caused deadlock?
You can get the latest deadlock by executing in mysql:
`SHOW ENGINE INNODB STATUS;`

or you can enable mysqld config value https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_print_all_deadlocks to print all deadlock info to error log.

**Comment by grobinson-grafana** [comment] 2022-08-29 14:26
Hi! :wave: Below is the SQL statement that we use to update the state for an alert instance:

```
INSERT INTO alert_instance (`rule_org_id`, `rule_uid`, `labels`, `labels_hash`, `current_state`, `current_reason`, `current_state_since`, `current_state_end`, `last_eval_time`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `rule_org_id`=VALUES(`rule_org_id`), `rule_uid`=VALUES(`rule_uid`), `labels`=VALUES(`labels`), `labels_hash`=VALUES(`labels_hash`), `current_state`=VALUES(`current_state`), `current_reason`=VALUES(`current_reason`), `current_state_since`=VALUES(`current_state_since`), `current_state_end`=VALUES(`current_state_end`), `last_eval_time`=VALUES(`last_eval_time`)
```

In the case where there is more than one alert, or dimensions of a single alert in an evaluation, Grafana will execute this SQL statement for each alert instance. This means that when Grafana is run in HA it is possible that the different instances of Grafana will attempt to update the alert state at the same time and result in deadlocks.

We have opened https://github.com/grafana/grafana/pull/54072 that should improve this situation as we now attempt to do most updates in a single statement, rather than a separate statement per alert instance.

**Comment by armandgrillet** [comment] 2022-09-16 09:08
#54072 has been reverted: https://github.com/grafana/grafana/pull/54885
The issue is still happening and we investigate it.

**Comment by armandgrillet** [comment] 2022-10-07 16:41
@joeblubaugh I believe this can be closed now?

**Comment by joeblubaugh** [comment] 2022-10-10 02:45
#55350 significantly reduces the # of database calls from alerting, but we have additional database performance improvements in the pipeline: #56587 #56575.

I don't think any of these guarantee that we won't see a deadlock *ever*, but they should all make it less likely. I'm OK with closing this once those are closed.

**Comment by joeblubaugh** [comment] 2022-11-16 11:55
Closing this, as the issues I mentioned above have been merged.

**Closed by joeblubaugh** 2022-11-16 11:55 UTC
Labels: type/bug, prio/high, area/alerting, area/backend/db/sql, pr/awaiting-info
