### ISSUE TITLE
Alert : error:"tsdb.HandleRequest() response error &{error parsing interval $time A 0xc4213186d0 [] []}"

### ISSUE THREAD

**Issue by rakeshratnam** [grafana/grafana#15297] opened 2019-02-07 13:13 UTC
Hi ,

Getting error while configuring alert.
Version : Grafana v5.2.4 ([[0bbac5c]
Datasource : mysql
running on: linux
Message configured :Grafana Alert (MB) : Pending orders count more than 10

error :
firing:true
state:"alerting"
conditionEvals:" = true"
timeMs:"0.246ms"
error:"tsdb.HandleRequest() response error &{error parsing interval $time A 0xc4213186d0 [] []}"

**Comment by torkelo** [comment] 2019-02-07 13:18
dupe of https://github.com/grafana/grafana/issues/15296

**Closed by torkelo** 2019-02-07 13:18 UTC

**Comment by rakeshratnam** [comment] 2019-02-07 13:20
No my message doesn't contain any Variable its pure text
