### ISSUE TITLE
[bug] Elasticsearch querie does not show.keyword terms

### ISSUE THREAD

**Issue by cosmos1978** [grafana/grafana#8862] opened 2017-07-14 10:30 UTC
Grafana 4.4.1
elasticsearch 5.4
ubuntu 16.04

 When I make a querie in grafana the fields list dropdown box shows all fields without ".keyword"
I have to add ".keyword" to each field in order to get a proper graph

**Comment by torkelo** [comment] 2017-07-14 19:47
duplicate of https://github.com/grafana/grafana/issues/3772

**Closed by torkelo** 2017-07-14 19:47 UTC
