### ISSUE TITLE
[BUG] multiple notification from multinode setup

### ISSUE THREAD

**Issue by leoleovich** [grafana/grafana#7052] opened 2016-12-22 15:52 UTC
Please include this information:
- What Grafana version are you using? 4.0.2-1481203731
- What datasource are you using? graphite
- What OS are you running grafana on? debian

We get notifications 2 times, because we are using 2 nodes of grafana in 1 cluster. They share same mysql database (master-master). No visible replication delay.
When incident happens we get 2 times the same notification.

![image](https://cloud.githubusercontent.com/assets/4749052/21431293/f481e15e-c866-11e6-9dc7-49c417f902ff.png)

**Comment by torkelo** [comment] 2016-12-23 08:07
http://docs.grafana.org/alerting/rules/#clustering

dupe of https://github.com/grafana/grafana/issues/6957

**Closed by torkelo** 2016-12-23 08:07 UTC
