### ISSUE TITLE
Dashboards: Geomap tooltip location breaks when scrolled down on dashboard

### ISSUE THREAD

**Issue by tvdhout** [grafana/grafana#94222] opened 2024-10-03 15:19 UTC
### What happened?

The tooltips for Geomap map layers (of any layer type) are drawn in the wrong location when the page is scrolled down. This effect is more profound the farther down on the page you're scrolled, to the point that the tooltip box is not shown at all. It seems the page scroll position breaks the location computation of the tooltip.

### What did you expect to happen?

The tooltips for Geomap map layers should be displayed at the cursor position, irrespective of the scrol location on the page.

### Did this work before?

I'm not sure, but I think I found a similar bug report from a few years back. I assume it was fixed after and reintroduced at some point, but I'm not sure.

### How do we reproduce it?

It can be reproduced on Grafana Play ([Geomap examples](https://play.grafana.org/d/panel-geomap/geomap-examples?from=now-6h&to=now&refresh=)). Make the page small enough (or zoom in) such that you can scroll down on the page, then look at the tooptips on the geomap datapoints.

More generally: Create any Geomap panel with data and tooltips enabled. Make sure the dashboard page can be scrolled on. See the difference in tooltip location when scrolled to the top of the page vs. farther down.

### Is the bug inside a dashboard panel?

Any Geomap panel

### Environment (with versions)?

Grafana: Cloud stable (and at least also the version on play.grafana.com: Grafana v11.3.0-76761 (137da12c99))
OS: MacOS 15.0
Browser: Safari, Firefox, Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Irrelevant

**Comment by maxlemieux** [comment] 2024-10-17 23:51
It looks like this is fixed in this PR: https://github.com/grafana/grafana/pull/94827

**Comment by moxious** [comment] 2024-10-23 19:00
@tvdhout can confirm what you're reporting here is an exact replica of something I was reporting internally. The PR above should fix, but we're waiting for the change to propagate through to all the various Grafana Cloud stacks.  Keeping this open now for not wanting to close it with the fix not yet delivered -- but for people who might be coming through late browsing, this should be done by the time you see it.

**Comment by tvdhout** [comment] 2024-10-23 19:01
Thanks for the update!

**Comment by moxious** [comment] 2024-10-25 10:44
confirmed yesterday this is fixed & closed on newly created Grafana Cloud free instances steady channel

**Closed by moxious** 2024-10-25 10:44 UTC
Labels: type/bug, type/ux, area/panel/geomap, area/tooltip, automated-triage
