### ISSUE TITLE
Compute graph color from display name

### ISSUE THREAD

**Issue by rakai93** [grafana/grafana#6324] opened 2016-10-19 10:53 UTC
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request

- What Grafana version are you using?
v3.1.1

It would be nice to have a static color for data line, e.g. generated from the line's display name. This way, you could easily find connections between multiple graphs on a single page which all show different metrics for the same entities.

Concrete example: We have a dashboard which shows different graphs like amount of queued tasks, average initial startup time and average task duration, each one grouped by the type of task. It happens quite often that some graphs show different types of tasks than other graphs, e.g. when a specific type of task is visible as queued, but not shown in the average runtime graph as no task finished in the shown time span. This causes the same type of task to be shown in different colors all over the dashboard which makes it really hard to find the same task type in different graphs to compare the data.

**Comment by torkelo** [comment] 2016-10-19 11:03
So for no one has come up with a good way t do this and get good colors with good contrast. The only solution would be to wait for all graphs to complete their queries before assigning colors, but then one query would slow the whole dashboard down

dupe of 
https://github.com/grafana/grafana/issues/221

**Closed by torkelo** 2016-10-19 11:03 UTC

**Comment by torkelo** [comment] 2016-10-19 11:04
you can assign colors manually (by clocking on the color line icon in the legend), or by specifying regex rules in "Series overrides" in display tab
