### ISSUE TITLE
Allow creating organizations using provisioning

### ISSUE THREAD

**Issue by olivierlemasle** [grafana/grafana#18990] opened 2019-09-10 17:14 UTC
**What would you like to be added**:
I'd like to be able to use provisioning (similar to datasources, notifiers and dashboards) to create and delete organizations.

**Why is this needed**:
In a GitOps-managed Grafana, datasources and dashboards can be created using provisioning. Users can be created externally in LDAP and mapped to an existing organization. However, it is currently not possible to create these organizations beforehand (except using API).

I'd be glad to contribute it if this feature is accepted.

**Comment by torkelo** [comment] 2019-09-11 07:19
dupe of https://github.com/grafana/grafana/issues/12119

**Closed by torkelo** 2019-09-11 07:19 UTC
