### ISSUE TITLE
"Fill below to" does not work if Override parameter "Display name" is set

### ISSUE THREAD

**Issue by Matze2** [grafana/grafana#43577] opened 2021-12-29 11:28 UTC
**What happened**:
The area between a 10% percentile and a 90% percentile should be filled. This works only if the "Display name" is not overridden and the standard select column representation is also taken as chart label.

**What you expected to happen**:
The area filling should work in both cases.

**How to reproduce it (as minimally and precisely as possible)**:
Screenshot 1 shows the expected behavior. Screenshot 2 overrides the "Display name" of the 10% percentile. Now the area is filled down to the X axis.

Good:
![grafik](https://user-images.githubusercontent.com/12542802/147657378-bb8d1195-0a9c-4667-8adc-6365bdef7f88.png)

Bad:
![grafik](https://user-images.githubusercontent.com/12542802/147657465-ad6a9698-7045-417c-a0de-3118ad6a5dc6.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian armv7l
- User OS & Browser: Firefox @ OpenSuse
- Grafana plugins: sunandmoon
- Others:

**Comment by ivanahuckova** [comment] 2022-01-03 10:46
I was able to reproduce this on play site:

https://user-images.githubusercontent.com/30407135/147921407-606fb345-7446-4ae8-87a6-cf3c6e24229c.mov

**Comment by isaitgirl** [comment] 2022-03-11 15:22
Same here! I thought I was making a mistake, but it really stops to work when I set an override for Display Name of the baseline series.

**Comment by codeincarnate** [comment] 2022-08-15 14:00
Going to follow up with @dprokop or @leeoniya on this one. Kind of tricky fix if memory serves me.

**Comment by mdvictor** [comment] 2022-10-27 09:30
Hello!

It seems that the issue changed a bit. I could not reproduce the exact problem, but a problem still exists. This is what I've encountered:

![Screenshot 2022-10-27 at 12 29 01](https://user-images.githubusercontent.com/36818606/198247998-80523664-65b6-4e8a-aae2-8feb77d1fc61.png)

Working on a fix for this

**Closed** 2022-10-28 06:27 UTC
Labels: type/bug, area/field/overrides, area/panel/timeseries

**Comment by mdvictor** [comment] 2022-10-28 06:43
Hey! Fix will be ready by next patch - v9.2.3
