### ISSUE TITLE
How to let the alert function to support for the third part datasource plugin

### ISSUE THREAD

**Issue by suntenday** [grafana/grafana#10314] opened 2017-12-21 06:49 UTC
I am now use the third part datasource plugin (https://github.com/aliyun/aliyun-log-grafana-datasource-plugin).
But when I use the alert function , show me the message "not support this datasource"
So how I can use alert function for third part datasource plugin or how I can make some changes in the sources of grafana to let it support.

**Comment by marefr** [comment] 2017-12-21 10:02
Grafana don't support alerting for third party datasources right now. 

Issue #6841 aims to enable support for more TSDBs for alerting.

**Comment by bergquist** [comment] 2017-12-22 10:30
To add support for you custom datasource you have to dig into the code yourself. 
I suggest looking at https://github.com/grafana/grafana/pull/8934 as an example.

Closing this since its a question and not a bug/feature.

**Closed by bergquist** 2017-12-22 10:30 UTC
Labels: type: question

**Comment by suntenday** [comment] 2017-12-26 00:52
Thanks I will check it
