### ISSUE TITLE
Cannot override Date & Time

### ISSUE THREAD

**Issue by michelegalasso** [grafana/grafana#25022] opened 2020-05-22 14:44 UTC
I am visualizing values of datetimeoffset type (t-sql) into a table in Grafana. For some reason, overriding them has no effect. I continue to see strings of the type '2020-05-20T11:20:04Z' in the table.

![override](https://user-images.githubusercontent.com/41417878/82679196-71948980-9c53-11ea-8423-cc87ad53e03e.png)

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Microsoft SQL Azure (RTM) - 12.0.2000.8
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Ubuntu 18.04.4 LTS, Mozilla Firefox 76.0.1 (64-bit)

**Comment by zoltanbedi** [comment] 2020-05-22 15:40
Hi @michelegalasso thanks for reporting this issue. I think this is a duplicate of #24655 so I'm going to close this issue.

**Closed by zoltanbedi** 2020-05-22 15:40 UTC

**Comment by michelegalasso** [comment] 2020-05-22 15:51
Thank you Zoltan!! Sorry for not noticing the duplicate.
