### ISSUE TITLE
Wrong aliases name after clicking "Refresh dashboard"

### ISSUE THREAD

**Issue by tomaszdubiel18** [grafana/grafana#60899] opened 2023-01-03 11:19 UTC
**What happened**:
On dashboard, with modified aliases names, on the start everything is ok:
![obraz](https://user-images.githubusercontent.com/85760200/210346935-d507a2ba-6b79-4ff3-95eb-667519f82ecc.png)
**How to reproduce it (as minimally and precisely as possible)**:
After clicking "Refresh dashboard" or autorefresh:
![obraz](https://user-images.githubusercontent.com/85760200/210347084-76f1bfb9-3720-45d3-9277-50866180a3ef.png)
- Grafana version: 9.3.2
- Data source type & version: PNP
- OS Grafana is installed on: Debian 10.13
- User OS & Browser: Windows 11, Firefox 108.0.1

**Comment by mellieA** [comment] 2023-01-05 01:22
@tomaszdubiel18 can you share more information: 

Which visualization type is this? 
How is the alias modified? 
Can you use the new *Get Help* feature to save a sharable version of the dashboard?  It will give you the option to randomize the data and labels. Then you can upload it to this issue so we can take a look.

<img width="338" alt="Screenshot 2023-01-04 at 6 19 56 PM" src="https://user-images.githubusercontent.com/18175287/210680227-727f5765-c915-4cb9-9890-0ae9154d7744.png">

**Comment by tomaszdubiel18** [comment] 2023-01-05 08:56
Here is the JSON of the dashboard. BTW, this new feature has a funny, basic bug. When I click on it and then "Preview", it tries to open: http://localhost:3000/dashboard/new - localhost instead of a grafana server IP.
`{
  "id": 20,
  "gridPos": {
    "h": 11,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "timeseries",
  "title": "$Serwer_Linux",
  "datasource": {
    "type": "sni-pnp-datasource",
    "uid": "1JKFMRN7z"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 2,
        "fillOpacity": 3,
        "gradientMode": "scheme",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 4,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "decimals": 2
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "% zajętego miejsca na dysku systemowym"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "red",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "% zajętego miejsca na dysku kopii"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "blue",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "% zajętego miejsca na dysku bazy"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-green",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "alias": "% zajętego miejsca na dysku bazy",
      "factor": "",
      "fill": "fill",
      "host": "/^$Serwer_Linux$/",
      "perflabel": "procent_zajetego_miejsca",
      "refId": "% zajętego miejsca na dysku bazy",
      "service": "Passive - Linux - dysk bazy",
      "type": "AVERAGE",
      "datasource": {
        "type": "sni-pnp-datasource",
        "uid": "1JKFMRN7z"
      }
    },
    {
      "alias": "% zajętego miejsca na dysku kopii",
      "factor": "",
      "fill": "fill",
      "hide": false,
      "host": "/^$Serwer_Linux$/",
      "perflabel": "procent_zajetego_miejsca",
      "refId": "% zajętego miejsca na dysku kopii",
      "service": "Passive - Linux - dysk kopii",
      "type": "AVERAGE",
      "datasource": {
        "type": "sni-pnp-datasource",
        "uid": "1JKFMRN7z"
      }
    },
    {
      "alias": "% zajętego miejsca na dysku systemowym",
      "factor": "",
      "fill": "fill",
      "hide": false,
      "host": "/^$Serwer_Linux$/",
      "perflabel": "procent_zajetego_miejsca",
      "refId": "% zajętego miejsca na dysku systemowym",
      "service": "Passive - Linux - dysk systemowy",
      "type": "AVERAGE",
      "datasource": {
        "type": "sni-pnp-datasource",
        "uid": "1JKFMRN7z"
      }
    },
    {
      "alias": "load serwera",
      "factor": "",
      "fill": "fill",
      "hide": false,
      "host": "/^$Serwer_Linux$/",
      "perflabel": "load1",
      "refId": "A",
      "service": "Passive - Linux - CPU",
      "type": "AVERAGE",
      "datasource": {
        "type": "sni-pnp-datasource",
        "uid": "1JKFMRN7z"
      }
    }
  ]
}`

**Comment by tomaszdubiel18** [comment] 2023-01-25 14:42
Can you look into this?

**Comment by tomaszdubiel18** [comment] 2023-03-01 07:13
Bump

**Comment by tomaszdubiel18** [comment] 2023-05-24 09:32
Bump

**Comment by mellieA** [comment] 2023-07-14 21:36
@tomaszdubiel18 sorry I missed your updates. Taking a look.

**Comment by mellieA** [comment] 2023-07-15 00:51
@tomaszdubiel18 I tried the panel JSON but because it is just the JSON it can't reproduce the panel. Can you try again with the **Get Help** option on the panel so we can get a copy of the panel and randomized sample data?

**Comment by tomaszdubiel18** [comment] 2023-07-15 05:32
Is it ok?
[debug-XXX-2023-07-15 07 30 42.json.txt](https://github.com/grafana/grafana/files/12060588/debug-XXX-2023-07-15.07.30.42.json.txt)

**Comment by tomaszdubiel18** [comment] 2023-07-28 12:01
It's still present in the latest Grafana version.

**Comment by tomaszdubiel18** [comment] 2023-08-24 07:07
It is finally fixed in the version v10.1.0.

**Comment by gelicia** [comment] 2024-02-28 22:18
This has been reported as fixed! Closing.

**Closed by gelicia** 2024-02-28 22:18 UTC
Labels: needs more info
