### ISSUE TITLE
Query Varibles - using ec2_instance_attribute is not respecting the selected CloudWatch datasource

### ISSUE THREAD

**Issue by kderholtvisma** [grafana/grafana#41254] opened 2021-11-03 11:43 UTC
**What happened**:
Create a variable to list EC2 instances for CloudWatch#2 datasource, but the list will always show EC2 instances for CloudWatch#1 datasource.

**What you expected to happen**:
List all names of EC2 instances in eu-west-1 for CloudWatch#2 datasource

**How to reproduce it (as minimally and precisely as possible)**:

have multiple datasources of CloudWatch - preferable for multiple AWS accounts
CloudWatch#1 and CloudWatch#2
Create a new dashboard.
Go to Settings -> Variables
Add a new one
Choose:
"Type: Query"
"Datasource: CloudWatch#2"
"Query: ec2_instance_attribute("eu-west-1", Tags.Name, { "tag:Name": ["*"] });"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: CloudWatch
- OS Grafana is installed on: grafana official docker
- User OS & Browser: MacOS - Chrome
- Grafana plugins: 
- CloudWatch Data Source - Native Plugin
Grafana ships with built in support for CloudWatch. You just have to add it as a data source and you will be ready to build dashboards for your CloudWatch metrics.

**Comment by andresmgot** [comment] 2021-11-03 12:28
I was able to reproduce this issue with the latest version

**Comment by andresmgot** [comment] 2021-11-05 11:08
We took a look again to this and I was wrong, I misinterpreted the error that I was getting and I thought I was using a different datasource. After rechecking this, we saw that the issue is not happening in 8.2. Can you verify if upgrading solves your issue @kderholtvisma?

**Comment by sunker** [comment] 2021-11-05 11:18
One thing we noted though is that the variable query is not re-triggered when changing datasource in the variable editor. I'm not saying this was the problem that you saw @kderholtvisma, but for this reason it might appear as the query still works when changing to a data source that should not return any values. 

Should changing datasource in the variable editor trigger the variable query to run once again @hugohaggmark?

**Comment by hugohaggmark** [comment] 2021-11-05 11:38
It should but there was a recent bug on main that was fixed by https://github.com/grafana/grafana/pull/41255, I hope that is what you're experiencing. Let me know otherwise.

**Comment by kderholtvisma** [comment] 2021-11-05 14:36
Hello, thanks for looking into it.
I'm not explaining it good enough, sorry for that.

So if i change datasource to say another type, "prometeheus" instead of cloudwatch. the query will naturally show an error.
If i swap back to the proper cloudwatch datasource (the 2nd). It will still go back to displaying what the 1st cloudwatch datasource has in its account

I can try to reproduce this in a local deploy within the weekend.

**Comment by iwysiu** [comment] 2022-01-05 18:46
Hi @kderholtvisma ! Were you able to reproduce your issue?

**Comment by iwysiu** [comment] 2022-01-25 19:14
Closing due to not able to reproduce this.

**Closed by iwysiu** 2022-01-25 19:14 UTC
Labels: type/bug, datasource/CloudWatch

**Comment by kderholtvisma** [comment] 2022-01-25 19:27
Im sorry for the late reply.

The story is that all of a sudden, this functionality worked on the 8.0.3 version. Probably a bug that got fixed after a restart.
We also upgraded to 8.3.4 and don't have any problems.

Thanks for your time
