### ISSUE TITLE
Input: width increases when loading is true and the spinner is shown

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#62313] opened 2023-01-27 12:35 UTC
**What happened**:
If there is an `input` without a specific `width`, it makes itself wider when `loading` is `true` and the spinner is shown.

https://user-images.githubusercontent.com/65417731/215088177-76666185-e5bc-473b-8a13-aa04b5421b2f.mov

**What you expected to happen**:
To keep its width.

**How to reproduce it (as minimally and precisely as possible)**:
Go to [Storybook > Forms > Field > Simple](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-field--simple) and set `loading` to `true

`**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tskarhed** [comment] 2023-03-06 09:24
What should the expected behavior be here? This is happening because the containing element does not have a set width. Without a set width it is hard to determine the "correct" width.

**Comment by L-M-K-B** [comment] 2023-09-19 09:14
The component is mitigating this with setting the input width to 100% but the storybook layout causes issues.
The team decided to revisit this issue when the Stack component is being published.

**Comment by joshhunt** [comment] 2023-10-27 16:35
Fixed by https://github.com/grafana/grafana/pull/75115

**Closed by joshhunt** 2023-10-27 16:35 UTC
Labels: type/bug, needs investigation, area/frontend, design-system, design-system: dev work
