### ISSUE TITLE
Variable type Custom - ability to add empty item

### ISSUE THREAD

**Issue by KrisztianKaszas** [grafana/grafana#22400] opened 2020-02-24 16:17 UTC
**What would you like to be added**:
I would like to be able to add an empty item to a Custom variable.

**Why is this needed**:
An empty item would allow creating nullable lists. E.g. with an empty item at the first position and further items after the empty one.

Nullable lists would be again useful, whenever we use custom lists as a filter for specific properties, where an empty item would be interpreted as "show all items" / no filtering at all.

**Comment by torkelo** [comment] 2020-02-24 18:11
duplicate of https://github.com/grafana/grafana/issues/5970

**Closed by torkelo** 2020-02-24 18:11 UTC
