### ISSUE TITLE
Panel title response touch event incorrectly in mobile platform

### ISSUE THREAD

**Issue by wolong12** [grafana/grafana#20055] opened 2019-10-28 09:17 UTC
**What happened**:
When I touch(click) the title of a panel (except for the first panel), the panel will be moved to the end of the page, almost immediately. 
When I was sliding the dashboard and my finger touched the panel's title, that panel would be moved to somewhere unexpectedly. This might be the same issue as the previous symptom. 
The issue happens on both Safari and Chrome.

**What you expected to happen**:
When I click the title, it should show out the title menu like what happens on the desktop.
Sliding the page or drag the panel should be identified in mobile platforms.

**How to reproduce it (as minimally and precisely as possible)**:
We could reproduce the issue on https://play.grafana.org/.
Issue 1. Just click the panel's title in Safari on iOS.
Issue 2. Slide the page, again and again.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.3
- Data source type & version: Official Docker Hub Image
- OS Grafana is installed on: 
- User OS & Browser: Safari on iOS, Chrome on Android
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-10-28 12:57
duplicate of https://github.com/grafana/grafana/issues/18497

**Closed by torkelo** 2019-10-28 12:57 UTC
