### ISSUE TITLE
Impossible to have multiple metrics with the same field and aggregation

### ISSUE THREAD

**Issue by erozen** [grafana/grafana#43533] opened 2021-12-27 04:35 UTC
**What happened**: Trying to build a table that uses the same field and aggregation twice (the second one has a script applied to perform some further mathematical changes) - however there is only one instance appearing.

**What you expected to happen**: Both columns to be visible

**How to reproduce it (as minimally and precisely as possible)**: Create a table visualisation.  Add sum(<metric1>) twice as a metric, but set the script of one to e.g. `_value / 6`

**Anything else we need to know?**: Looks like the metric is referenced just by `<aggregation> <column>` rather than any internal ID.  There is no way to supply your own reference when creating the metric, so no way to get the same value more than once.

Note also that you can't use the "Add field from calculation" transformation, as that only lets you perform a single basic operation against two fields - if you want to use more than one operation, use any operation other than add/subtract/multiply/divide, operate on a number of columns other than 2, or do operations using a constant value, that transformation won't work for you.

![image](https://user-images.githubusercontent.com/8446560/147434636-ea89dc34-1608-42d5-8d61-8945dedad81a.png)

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Elasticsearch 7.16.2
- OS Grafana is installed on: Docker / Linux
- User OS & Browser: Linux / Firefox
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment] 2022-01-14 11:11
Hi @erozen, thanks for reporting this!

I'm closing this issue as a duplicate of https://github.com/grafana/grafana/issues/16331.

**Closed by Elfo404** 2022-01-14 11:11 UTC
Labels: datasource/Elasticsearch, needs investigation
