### ISSUE TITLE
Public Dashboard not public anymore after updating to latest version

### ISSUE THREAD

**Issue by McA1992** [grafana/grafana#77648] opened 2023-11-03 17:52 UTC
### What happened?

Updated to the latest Version of Grafana 10.2.0 and my Public Dashboard now shows "No Data" if I'm not logged in in any other Tab of the Browser. As soon as I login in another tab of the browser all data appear without reload.
The Message "Unauthorized" appears from time to time when "No Data" is shown.

### What did you expect to happen?

All Data should be visible in the panels of a public dashboard without login. 

### Did this work before?

Yes worked with a previous version. 

### How do we reproduce it?

1. Create any Dashbord.
2. Make it public
3. Try to access it without being logged in in the same browser.

### Is the bug inside a dashboard panel?

No don't think so.. 

### Environment (with versions)?

Grafana: 10.2.0
OS: raspbian/debain
Browser:Chrome, Safari, Firefox (each latest version)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by McA1992** [comment] 2023-11-03 18:17
[debug-Panel Title-2023-11-03 19_15_31.json.txt](https://github.com/grafana/grafana/files/13253395/debug-Panel.Title-2023-11-03.19_15_31.json.txt)

**Comment by McA1992** [comment] 2023-11-03 18:21
[605a30b7-1c88-48a5-9eee-fd3c982889a0.tar.gz](https://github.com/grafana/grafana/files/13253422/605a30b7-1c88-48a5-9eee-fd3c982889a0.tar.gz)

**Comment by McA1992** [comment] 2023-11-03 18:46
If I run this command "sudo apt-get install grafana=9.5.13", can I rollback to grafana 9 without any issues? Or will that cause data loss?

**Comment by McA1992** [comment] 2023-11-03 19:19
Maybe related to: #77082

**Comment by McA1992** [comment] 2023-11-03 19:42
Rollback to 10.1.5 solved it for now. But data fetch is really slow now. About a minute compared to a few seconds with version 9.x.x

**Comment by bpedersen2** [comment] 2023-11-06 16:16
The problem is a POST to https://<server>/api/frontend-metrics that gets denied. Public dashboards should probably not even try to send these requests.

**Comment by McA1992** [comment] 2023-11-11 10:28
Downgrade to 10.1.5 is still not a good solution. I never knew that there's a button to cancel a query if it takes too long but now i see that all the time. Something is really slowing the data fetch down but only if a dashboard is viewed public. If I view the dashboard normal there is no time needed to fetch the data. It´s only in the public dashboard. Can anyone tell me if its possible without problems to further downgrade back to 9.5.13?

**Comment by McA1992** [comment] 2023-11-11 10:37
When fetching data the log generate a lot of these errors:
logger=context userId=1 orgId=1 uname=* t=2023-11-11T11:35:48.948720511+01:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=400 remote_addr=[::1] time_ms=28 duration=28.250273ms size=12 referer= handler=/api/live/ws

**Comment by bpedersen2** [comment] 2023-11-13 07:59
> The problem is a POST to `https://<server>/api/frontend-metrics` that gets denied. Public dashboards should probably not even try to send these requests.

This should be fixed by #77001

**Comment by tonypowa** [comment] 2023-11-15 13:28
@McA1992 
as @bpedersen2 pointed out, it should be fixed in 10.2.1 
closing 
please reopen if needed

**Comment by rda0** [comment] 2023-11-15 16:12
> @McA1992 as @bpedersen2 pointed out, it should be fixed in 10.2.1 closing please reopen if needed

I upgraded to v10.2.1 today and tested this and it does not work. Still `no data`.
The commit was not listed in the release notes: https://github.com/grafana/grafana/releases/tag/v10.2.1

**Comment by bpedersen2** [comment] 2023-11-15 17:09
The Unauthorized message due to metrics should be fixed,  the but I am not sure what the root cause for missing data is here ( My public dashboards are nicely public.)

**Comment by rda0** [comment] 2023-11-15 18:14
I get `401` on `/api/datasources/proxy/`:

![2023-11-15 19_03_44-Window](https://github.com/grafana/grafana/assets/6731714/93f80dad-c4cb-4ba5-8e94-1c396ba94096)

Could it be datasource related? This is using `InfluxDB`.

**Comment by McA1992** [comment] 2023-11-15 18:53
I'm using InfluxDB as well. Don't want to test it then. Don't know if downgrading by apt package manager is always failsafe. 

10.1.5 is working, but really slow at data fetch even if I'm logged in. 10.2.0 was fast at data fetch when logged in. But No data when not logged in. The Dashboards work all fine when not used over the public dashboard address. Then data fetch is fast as usual.

**Comment by McA1992** [comment] 2023-11-15 18:59
@tonypowa Would like to reopen the issue but there's no option to do so..

**Comment by nasi87** [comment] 2023-11-18 19:05
> Could it be datasource related? This is using `InfluxDB`.

My single one public dashboard is not working anymore too. I updated today on 10.2.1, but don't know which version I had before.
The dashboard contains data based on both InfluxDB 1.x as well as InfluxDB 2.x.
I don't know much about debugging but browser console shows some messages like:
`runRequest.catchError [...] network error: not found (404)`

**Comment by juanicabanas** [comment] 2023-11-22 13:45
Hi @McA1992  ! Thanks for reporting the issue.
Which influxdb version are you using? 
Could you provide a screenshot of all requests made in the browser?

Thanks!

**Comment by McA1992** [comment] 2023-11-23 11:29
Hi @juanicabanas, 
the influxdb version I'm using is 1.6.7rc0.

I can only provide the screenshots for version 10.1.5.
There is just the issue with the really slow data fetch (2nd Screenshot).

I'd only test it with the latest version if someone can tell me
if switching versions back and forth with this command "apt-get install grafana=x.x.x"
causes no problems. 

![Bildschirmfoto 2023-11-23 um 12 24 13](https://github.com/grafana/grafana/assets/128582916/cf4ed88a-7675-41c9-8b39-09ac8275695f)
![Bildschirmfoto 2023-11-23 um 12 23 53](https://github.com/grafana/grafana/assets/128582916/be46057c-896d-4ae5-a003-440463cbf7fd)

**Comment by corgan2222** [comment] 2023-11-23 16:53
Hello,

we have the exact same problem, after we updated from 10.0 to 10.2.
All public dashboards with influxDB 1.8 datasource are broken, with the same error. On version 10.0 the public dashboards worked fine.
The same dashboards are running fine in “non-public” mode.
After a login, the public dashboards are also working. 

![grafik](https://github.com/grafana/grafana/assets/12233951/5fe71dba-0264-4555-ae91-1ae8eeb17d13)

![grafik](https://github.com/grafana/grafana/assets/12233951/99b8695e-9ff7-46ff-ac89-4f4ad433cf3e)

![grafik](https://github.com/grafana/grafana/assets/12233951/5d2f4d63-3251-413f-b267-4ced539bb6ed)

**Comment by juanicabanas** [comment] 2023-11-27 19:08
Hi! I was able to replicate the issue.
Since 10.2.x version, public dashboards don't support InfluxQL (which is actually deprecated in Grafana code) and only support Flux (InfluxDB 2.x and 1.8+).
To make those queries work, you should change to Flux. Also, it's necessary to have the `influxdbBackendMigration` FF enabled in the config file which is enabled by default, indeed.

**Closed by juanicabanas** 2023-11-27 19:08 UTC
Labels: area/public-dashboards, triage/needs-confirmation

**Comment by corgan2222** [comment] 2023-11-28 17:02
Hello Juan,

Thank you very much for the information. However, I have several questions and concerns.

1. Is InfluxQL deprecated in general for normal Grafana dashboards, or just for public dashboards?

2. If InfluxQL is generally deprecated, I can't find any information on this. Since there is no query builder for Flux, creating dashboards is much more difficult. This seems like a big step backward.

3. Why was the support for InfluxQL in public Dashboards stopped from version 10.1 to 10.2? It worked wonderfully until version 10.1. Is there a configuration flag that we can use to reactivate it?

In general, it must be said that the public dashboards were exactly the feature we were waiting for. Unfortunately, the transition to Flux without a query builder is absolutely not user-friendly. Previously, our managers, who have little programming experience, could easily click together the queries themselves. Now, with Flux, we would need extra resources for programmers.
At the end, this would mean that we would have to go back to version 10.1 and then be stuck on that version.

**Comment by rda0** [comment] 2023-11-30 06:57
To add to the comments of @corgan2222:

We made the decision not to upgrade to InfluxDB 2.x and not to FLUX, since it is not an upgrade but a completely different language and would mean starting from scratch. FLUX is not an option for us.

- InfluxQL is officially back: https://www.influxdata.com/blog/introducing-influxdb-3-0/
- FLUX appears to be deprecated: https://community.influxdata.com/t/is-flux-being-deprecated-with-influxdb-3-0/30992/6

**Comment by melroy89** [comment] 2024-07-20 19:48
> Hello @juanicabanas
> 
> Thanks a lot, influxdbBackendMigration = true under [feature_toggles] fixed the issue for us! Great Support. vg Stefan

Thanks! This luckily still works in 2024.
