### ISSUE TITLE
Annotations: Cannot disable annotations with the same name 

### ISSUE THREAD

**Issue by ternium1** [grafana/grafana#70669] opened 2023-06-26 09:21 UTC
### 
# What went wrong?

**What happened**:

  - When having 2 annotations with the same name (in my case, 2 time regions) it is impossible to disable both in the dashboard header. Toggling the first and second one will both toggle the first one, and it is impossible to disable the second annotation this way
![image](https://github.com/grafana/grafana/assets/32877621/f9c958ff-7fbe-4657-bd9e-55f25b8a69ad)
![image](https://github.com/grafana/grafana/assets/32877621/ad55223a-3b0d-4b2c-b893-6283ee7dbd88)

**What did you expect to happen**:

  - When toggling the first one, it should toggle the first time region, and when toggling the second one it should toggle the second one

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and create a new dashboard.

**Step 2**:

- Open Dashboard settings > Annotations and create 2 annotations with the same name, in my case, those are Time regions from the Grafana Datatsource. Make sure Hidden is unclicked
![image](https://github.com/grafana/grafana/assets/32877621/a3630c32-e701-4a44-abf7-ce765617cfd4)

**Step 3**:

- Go back to the dashboard (maybe a refresh/save is needed?) and try to toggle the 2 annotations with similar names in the dashboard header. Toggling the first and second one will both toggle the first one, and it is impossible to disable the second annotation this way

### 
# What Grafana version are you using?

Grafana v10.0.1 (5a30620b85)

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Docker

### User's OS?

Windows 10 Pro 22H2

### User's Browser?

Chrome 114

### Is this a Regression?

None

### Anything else to add?

Unsure if this issue was happening before 10.x.x, as I started to use annotations for the time regions.

**Comment by mellieA** [comment] 2023-06-26 23:17
@ternium1 can you share more about the use case for having two annotations with the same name?

**Comment by ternium1** [comment] 2023-06-27 08:20
Hello, I'm monitoring my electricity consumption, and here in France we have off-peak and peak hours (HC & HP annotations). In my region, off-peak hours are from 2:00 AM to 7:00 AM and 2:00 PM to 5:00 PM (so peak hours are the opposite). I'm currently using 4 time regions:
* HC (off-peak) in blue from 1:56 AM to 6:56 AM
* HP (peak) in yellow from 6:56 AM to 1:56 PM
* HC from 1:56 PM to 4:56 PM
* HP from 4:56 PM to 1:56 AM

Since both HC & HP time regions are supposed to be the same, this is the reason I created them with similar names.

This is an example of a panel used in this dashboard:
![image](https://github.com/grafana/grafana/assets/32877621/f98590b7-43f4-4815-b97f-c9766244b894)

**Comment by mellieA** [comment] 2023-07-15 01:23
@ternium1 I'm not sure if this is expected to work - but is probably something we should check for. 

Are your annotations named HC, HP, HC, HP as shown in the UI? 

I tested this on Grafana 10 and I can see that it will let me name two annotation the same name, but it will only show one in the UI.

Moving over for our dashboard squad to take a look

**Comment by ternium1** [comment] 2023-07-15 19:52
@mellieA yes, names are similar (no spaces before or after). Issue still occurring on Grafana 10.0.2 (running in a docker container). I'm providing the configuration for each annotation. 
![image](https://github.com/grafana/grafana/assets/32877621/f4f032df-2a1a-4de3-ab9f-57657c6b67e0)
![image](https://github.com/grafana/grafana/assets/32877621/4dae0726-486d-4d86-aef2-33452b749220)
![image](https://github.com/grafana/grafana/assets/32877621/8653d276-c072-4cd1-9c9e-013fd8111492)
![image](https://github.com/grafana/grafana/assets/32877621/fcce15fa-8c17-4833-abbe-05c8b0f390e9)
![image](https://github.com/grafana/grafana/assets/32877621/70cf9907-bdf2-4f22-9bb7-325aae7480f9)

**Comment by axelavargas** [comment] 2023-07-17 08:10
Hello, @ternium1 👋🏾, thank you for reporting this issue. Unfortunately, we currently don't support annotation names that are identical.

P.S. I am closing this issue, as it's a duplicate of #66626.

**Closed by axelavargas** 2023-07-17 08:10 UTC
Labels: area/annotations, triage/needs-confirmation, team/grafana-dashboards
