### ISSUE TITLE
How to use grafana api to get metirc data points?

### ISSUE THREAD

**Issue by AnyuanLuo** [grafana/grafana#18720] opened 2019-08-26 13:08 UTC
I am using grafana to show the data collected by prometheus , then I want to get the metrics processed by grafana. Is there a kind of api, it can return a json data which is a graph's datapoints.
For example, grafana shows a figure of CPU Percentage Utilization Rate, then I use a kind of api, it return me a json file:  {  timestamp1:0.002,  timestamp2:0.001,  timestamp3:0.0025 ....}

**Comment by dprokop** [comment] 2019-08-26 14:09
Duplicate of https://github.com/grafana/grafana/issues/11989

**Closed by dprokop** 2019-08-26 14:09 UTC
Labels: type/duplicate, type/feature-request

**Comment by AnyuanLuo** [comment] 2019-08-27 01:46
Thank you for your answer!
