### ISSUE TITLE
Trace search on Tempo when traces stored as 16byte base64_encoded broken in grafana 8.0.6

### ISSUE THREAD

**Issue by hrodic** [grafana/grafana#37555] opened 2021-08-04 15:21 UTC
**What happened**:
When upgrading grafana from 7.5.8 to 8.0.6, searching TraceID sent as 16 bytes base64 encoded stopped to work.
The traces are still stored and can be accessed using tempo-query CLI.

**What you expected to happen**:
I would expect to see the same trace results on grafana.

**How to reproduce it (as minimally and precisely as possible)**:
In my case, I had performance test suite with K6 tool.
This tools allows Javascript programming to generate traces.
I generate random bytes with crypto.randomBytes(16);
Then i encode them with 
` name: "perf-test",
        trace_id: encoding.b64encode(traceId),
        span_id: encoding.b64encode(spanId),
        parent_span_id: parentSpanId !== null ? encoding.b64encode(parentSpanId) : null,
        start_time_unix_nano: startTimeNs,
        end_time_unix_nano: (startTimeNs + Math.round(Math.random() * 100000))`

I am using GRPC connectivity with
`client.invoke('opentelemetry.proto.collector.trace.v1.TraceService/Export', data);`

**Anything else we need to know?**:

When looking in grafana 8.0.6 for a trace stored as 16 byte string (No randombytes or base64 encoding). This example is using ZIPKIN format http to save the trace. It works fine.

`tempo_1                  | level=debug ts=2021-08-04T15:09:09.805584247Z caller=logging.go:66 traceID=2dd20dc31e3ab4b8 msg="GET /querier/api/traces/00000000000000000000000000000001?blockEnd=ffffffffffffffffffffffffffffffff&blockStart=00000000000000000000000000000000&mode=blocks (404) 146.617µs"
tempo_1                  | level=debug ts=2021-08-04T15:09:09.806730916Z caller=grpc_logging.go:41 method=/tempopb.Querier/FindTraceByID duration=670.099µs msg="gRPC (success)"
tempo_1                  | level=debug ts=2021-08-04T15:09:09.807382142Z caller=logging.go:66 traceID=2dd20dc31e3ab4b8 msg="GET /querier/api/traces/00000000000000000000000000000001?mode=ingesters (200) 2.027793ms"
`

When looking in grafana 8.0.6 for a trace sent as OLTP 16 randombytes base64 encoded.
The trace hex=**0e9f510afde2a10f13f2f01de8c4c401**
The trace base64_encoded=**Dp9RCv3ioQ8T8vAd6MTEAQ==**

**Note that the original TraceID is a 16 randomBytes. The CLI is able to convert from HEX to base64 encoded version of the bytes. Grafana tempo is not.** 

`tempo_1                  | level=debug ts=2021-08-04T15:13:47.814440586Z caller=grpc_logging.go:41 method=/tempopb.Querier/FindTraceByID duration=154.501µs msg="gRPC (success)"
tempo_1                  | level=debug ts=2021-08-04T15:13:47.814867201Z caller=logging.go:66 traceID=14c5fb737d145fb9 msg="GET /querier/api/traces/0e9f510afde2a10f13f2f01de8c4c401?mode=ingesters (200) 1.278309ms"
tempo_1                  | level=info ts=2021-08-04T15:13:47.818935391Z caller=tempodb.go:336 org_id=single-tenant traceID=14c5fb737d145fb9 msg="searching for trace in block" findTraceID=0e9f510afde2a10f13f2f01de8c4c401 block=ad7365e7-a9d2-4b64-89e0-8866800b21b9 found=false
tempo_1                  | level=info ts=2021-08-04T15:13:47.819465393Z caller=tempodb.go:336 org_id=single-tenant traceID=14c5fb737d145fb9 msg="searching for trace in block" findTraceID=0e9f510afde2a10f13f2f01de8c4c401 block=362f5e13-e69c-4128-ba72-f596254af0cd found=false
tempo_1                  | level=debug ts=2021-08-04T15:13:47.819626537Z caller=logging.go:66 traceID=14c5fb737d145fb9 msg="GET /querier/api/traces/0e9f510afde2a10f13f2f01de8c4c401?blockEnd=ffffffffffffffffffffffffffffffff&blockStart=00000000000000000000000000000000&mode=blocks (404) 6.237969ms"
tempo_1                  | level=info ts=2021-08-04T15:13:47.820615579Z caller=frontend.go:108 tenant=single-tenant method=GET traceID=14c5fb737d145fb9 url=/api/traces/0e9f510afde2a10f13f2f01de8c4c401 duration=8.699729ms response_size=1420 status=200
`

When searching the same trace using tempo-cli

```
Searching traceID=0e9f510afde2a10f13f2f01de8c4c401
Creating tracing-config_tempo-cli_run ... done
{"batches":[{"resource":{},"instrumentation_library_spans":[{"instrumentation_library":{},"spans":[{"trace_id":"Dp9RCv3ioQ8T8vAd6MTEAQ==","span_id":"b8utW0r2Chs=","name":"perf-test","start_time_unix_nano":1628090018413000,"end_time_unix_nano":1628090018486875,"status":{}},{"trace_id":"Dp9RCv3ioQ8T8vAd6MTEAQ==","span_id":"ayqEMhFpisc=","parent_span_id":"b8utW0r2Chs=","name":"perf-test","start_time_unix_nano":1628090018486875,"end_time_unix_nano":1628090018490692,"status":{}},{"trace_id":"Dp9RCv3ioQ8T8vAd6MTEAQ==","span_id":"CNT3lIloUJ0=","parent_span_id":"ayqEMhFpisc=","name":"perf-test","start_time_unix_nano":1628090018490692,"end_time_unix_nano":1628090018517355,"status":{}},{"trace_id":"Dp9RCv3ioQ8T8vAd6MTEAQ==","span_id":"vZP9XUytlTY=","parent_span_id":"CNT3lIloUJ0=","name":"perf-test","start_time_unix_nano":1628090018517355,"end_time_unix_nano":1628090018549640,"status":{}}
....continues...
```

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Tempo default grafana 8.0.6
- OS Grafana is installed on: Ubuntu docker 8.0.6
- User OS & Browser: Ubunut 20 (dockerized grafana)
- Grafana plugins: None
- Others: Sending traces via opentelemetry collector

**Comment by dsotirakis** [comment] 2021-08-09 09:33
Looping in @grafana/observability-squad

**Comment by connorlindsey** [comment] 2021-08-10 13:45
@hrodic Thanks for filing this. Could you provide the Grafana logs when you make the query? 

Also, could you provide a minimal way to reproduce this if possible?

**Comment by connorlindsey** [comment] 2021-08-16 20:26
@hrodic After following up with the Tempo team, they clarified that trace id's are stored as bytes decoded from hex and were not familiar with Tempo or Grafana ever handling base64 trace id's. This matches the OTel specification which states that trace ID's should be hex encoded based on this PR: https://github.com/open-telemetry/opentelemetry-specification/pull/911. 

There is potentially another underlying issue that is causing the search to fail and this conversion is a red herring. I'm going to close this as working as intended.

**Closed by connorlindsey** 2021-08-16 20:26 UTC
Labels: datasource/Tempo

**Comment by hrodic** [comment] 2021-08-18 15:50
Its kinda strange that i am able to store the trace and query it from tempo cli and tempo http using

`curl -X POST 'http://localhost:9411/api/v2/spans' --header 'Content-Type: application/json' --data-raw '[{"traceId": "31", "id": "0000000000000001", "name":"spanName", "timestamp": 1629302293, "duration": 1000, "kind": "SERVER", "tags": {"http.method": "GET"}}]'`

yet grafana 8 is not plotting it but 7 is. 

And no single error neither in chrome or grafana debug :(
