### ISSUE TITLE
Alerting support for queries using template variables in Grafana will be available "when"?

### ISSUE THREAD

**Issue by fchiorascu** [grafana/grafana#10412] opened 2018-01-03 12:07 UTC
Hi,

Sorry to open this topic.
I’ve tried to implement the alert in Grafana Dashboard but not working when you have a Dashboard with templating.
I’ve noticed that are some opened topics on GitHub regarding this subject: #6230, #6557.

–=Solution=–
The solution will be to have a Dashboard per Server in order to have alerting working?
vs
Other solution will be to have Dashboard per Services in order to have the alerting working.

Kind Regards,

**Comment by fchiorascu** [comment] 2018-01-03 12:08
Ex of templating:
![image](https://user-images.githubusercontent.com/18328353/34519991-740fa9be-f08f-11e7-8014-cab35f35d2b0.png)
![image](https://user-images.githubusercontent.com/18328353/34519996-77f639e4-f08f-11e7-8a93-bebc2d89efc3.png)

I understood that is not possible to have Alert in Grafana per each server present in the same Dashboard.
No resolution on internet regarding this, the only thing remains to have per service per server a Dashboard in order to have Alert available.

Any idea who to ask about this topic?
Below something on Internet: https://github.com/grafana/grafana/issues/6230

**Comment by fchiorascu** [comment] 2018-01-03 12:09
What are my expectations to work this Dashboard with templating and Alert in Grafana is to have the same alert per 1 single Dashboard that has 50 servers there. For the rest of the cases where the WARNING/ CRITICAL thresholds must be different from server to server I think i could create Dashboard per server in order to work the alert or per service?

**Comment by torkelo** [comment] 2018-01-03 12:36
dupe of https://github.com/grafana/grafana/issues/6557

> The solution will be to have a Dashboard per Server in order to have alerting working?
> vs
> Other solution will be to have Dashboard per Services in order to have the alerting working.

The current solution we recommend is to use wildcards in your query so that it returns many series. No ETA on when some limited form of template variable support will be implemented (or if ever)

**Closed by torkelo** 2018-01-03 12:36 UTC

**Comment by fchiorascu** [comment] 2018-01-03 13:54
Thank you for your intervention.
I understood.

**Comment by martinler** [comment] 2018-01-05 12:33
@torkelo Just "reality-check": with"wildcard" solution there is limitations, which you described in past:

> yes, it will check all series. But currently it does not keep state per series. So if one server has high CPU the alert rule will trigger (With the info on which server) and send out a notification, but a minute later another server also has high cpu it will not trigger new notifications as the alert rule is still in firing state.

So if i need to fire separate alerts for each unit, in best case with different rules (who will be notified), Grafana is not right tool for my needs and quite possible never will be, am i right?

Any idea/suggestion on existing solution? 

Thank you!

**Comment by torkelo** [comment] 2018-01-07 15:54
Keeping state per series is something we really want to do (hopefully within months).

**Comment by cybfly** [comment] 2018-05-14 08:59
hope it can be solved

**Comment by ipolishchuk** [comment] 2018-07-11 23:44
Any update on this? With multiple servers the existing Grafana alerting capabilities look insufficient enough, so we still need to keep nagios running just for alerting purposes.

**Comment by amjad** [comment] 2019-02-17 20:44
> dupe of #6557
> 
> > The solution will be to have a Dashboard per Server in order to have alerting working?
> > vs
> > Other solution will be to have Dashboard per Services in order to have the alerting working.
> 
> The current solution we recommend is to use wildcards in your query so that it returns many series. No ETA on when some limited form of template variable support will be implemented (or if ever)

Can you share an example of how this can be done? Thanks.

**Comment by podstava** [comment] 2019-02-27 05:36
Current solution for me  was  removing hostname veriable from dashboard and grouping by hostname in query.
![default](https://user-images.githubusercontent.com/20294557/53468252-1977d300-3a62-11e9-9db1-23d7502dfeb7.png)

**Comment by ybello33** [comment] 2019-04-10 16:27
Any Update on this open issue ?

**Comment by sbilello** [comment] 2019-04-18 07:09
It would be a great feature to have to save developer time to build panels

**Comment by hluaces** [comment] 2019-04-24 09:43
Apologies for asking about a closed issue, but I couldn't find information about this neither on the changelog nor on any open issue.

https://github.com/grafana/grafana/issues/10412#issuecomment-355832073:
> Keeping state per series is something we really want to do (hopefully within months).


@torkelo , could you tell us if this is still on the roadmap? any ETA for it?

Thanks to everyone for your work.

**Comment by ToWi87** [comment] 2022-01-04 14:48
if each time series has a **separate label** (which it usually has if you're using template variables), everyone here might want to look into this:
https://github.com/grafana/grafana/issues/7832#issuecomment-856725093
resp. https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/#single-and-multi-dimensional-rule

**Comment by torkelo** [comment] 2022-01-04 14:55
> Keeping state per series is something we really want to do (hopefully within months).

this is part of the new alerting system introduced in v8
