### ISSUE TITLE
Unable to query logs Grafana-Loki

### ISSUE THREAD

**Issue by singh9vj** [grafana/grafana#55227] opened 2022-09-15 10:09 UTC
**What happened**: I am facing some issue from past few days while searching logs from grafana  Loki. Even my query is correct it is throwing some syntax error (attached in screenshot) Even we have not done any changes. The grafana and Loki version V2.5 is running from few months. 

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/35693889/190377057-6c55ad15-0bda-4d6e-82dc-63450a6be0fa.png">

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: V8.5.0
- Data source type & version: Loki V2.5.0
- OS Grafana is installed on: Ubuntu arm64
- User OS & Browser: Google Chrome
- Grafana plugins:
- Others:

**Comment by cesarfreire** [comment] 2022-09-15 11:47
Same here.
There seems to be a problem when deleting and writing as well.

**Comment by learnting** [comment] 2022-09-16 02:43
you can see #54535

**Comment by athrunecho** [comment] 2022-09-16 02:49
I had the same problem on Grafana v9.0.5 (1b595e434a)

**Comment by cesarfreire** [comment] 2022-09-20 10:19
I just updated grafana to v9.1.5 and the problem is resolved.

**Comment by mellieA** [comment] 2022-09-24 00:13
Closing as a duplicate of https://github.com/grafana/grafana/issues/54535

**Closed by mellieA** 2022-09-24 00:13 UTC
Labels: type/duplicate, type/browser-compatability
