### ISSUE TITLE
Make the whole Panel Edit Page scrollable

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#40649] opened 2021-10-19 17:09 UTC
The experience when editing panels is really bad for users on laptops with not much vertical real estate.

The fact that only the part below the editing nav bar is scrollable is very very annoying when you have large queries that you can't even display entirely without scrolling ...

**Steps to reproduce**:

Laptop + panel with several large queries multiline queries

**Actual Result**:

![Pasted_Image_19_10_2021_19_03](https://user-images.githubusercontent.com/153052/137958047-4cf796c1-4734-4c73-9703-0e394e30e2d7.png)

**Expected Result**

I'd like the scroll bar to be for the whole page when editing so that I see my queries on the entire vertical space I have available on my screen.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 8.2.0
- Data source type & version: Prometheus
- User OS & Browser: MacOS / Firefox
- Others:

**Comment by hugohaggmark** [comment] 2021-10-20 12:21
Duplicate of #39487

**Closed by hugohaggmark** 2021-10-20 12:21 UTC
Labels: area/frontend, bot/duplicate
