### ISSUE TITLE
https://<grafana>/api/datasources/proxy/2/functions returned an invalid JSON

### ISSUE THREAD

**Issue by Nhyalgotphores** [grafana/grafana#46658] opened 2022-03-16 17:33 UTC
**What happened**:
After update to v8.4.3 the function proposal stopped working and all functions aren't recognized.
Console returns
`https://<grafana>/api/datasources/proxy/2/functions returned an invalid JSON - SyntaxError: JSON.parse: unexpected character at line 1 column 41308 of the JSON data [fetch.ts:111:18](webpack://grafana/public/app/core/utils/fetch.ts)`
The problem is `{"name": "limit", "type": "intOrInf", "default": Infinity}` where it should probably be `{"name": "limit", "type": "intOrInf", "default": "Infinity"}`
​

**What you expected to happen**:
N/A

**How to reproduce it (as minimally and precisely as possible)**:
Problem started showing after upgrade I am unable to say what setting causes it.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.3
- Data source type & version: Graphite
- OS Grafana is installed on: Centos 8
- User OS & Browser: Ubuntu LTS & Firefox
- Grafana plugins: Nothing that isn't Core function 
- Others:

**Comment by Dieterbe** [comment] 2022-03-16 18:56
duplicate of #45948

**Closed by Dieterbe** 2022-03-16 18:56 UTC
