### ISSUE TITLE
Uneven panel jumps row when adding new visualization 

### ISSUE THREAD

**Issue by amit-o** [grafana/grafana#15745] opened 2019-03-03 09:13 UTC
Using grafana 6.0.0.
When you have a row with uneven panels, adding a new panel causes the rightmost uneven panels to jump row.
Gif explanation:
![rowbug](https://user-images.githubusercontent.com/21155198/53693146-d5a80500-3da4-11e9-9fe0-640600eab4f4.gif)

Even panels are fine - 
![nobug](https://user-images.githubusercontent.com/21155198/53693161-3b948c80-3da5-11e9-8625-0afa9c9c2711.gif)

**Comment by torkelo** [comment] 2019-03-04 09:15
duplicate of https://github.com/grafana/grafana/issues/15224

**Closed by torkelo** 2019-03-04 09:15 UTC
