### ISSUE TITLE
InfluxDB: Tooltip and Legend shows incorrect label.

### ISSUE THREAD

**Issue by tatsutaigu** [grafana/grafana#52699] opened 2022-07-24 23:20 UTC
**What happened**:
Tooltip and Legend shows incorrect label.
I guess it shows internal Json format because It is sandwiched between `{` and `}`.
![image](https://user-images.githubusercontent.com/44219065/180669350-f14a39ac-bdf5-41d1-83b5-f9d0b77e1597.png)

**What you expected to happen**:
it does not show `{ handler=platform, ..... }` string.

**How to reproduce it (as minimally and precisely as possible)**:
1. go to playground : [https://play.grafana.org/d/000000002/influxdb-templated?orgId=1](https://play.grafana.org/d/000000002/influxdb-templated?orgId=1)
2. edit panel
3. change plugin to `Time series`
4. change data source to `influxDB v2.2 + Flux`
5. edit query as below

> from(bucket: "grafana")
> |> range(start: v.timeRangeStart, stop: v.timeRangeStop)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.4
- Data source type & version: influxDB2.2 + Flux
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome, Firefox
- Grafana plugins: Time series
- Others:

**Comment by obetomuniz** [comment] 2022-07-27 13:49
Hey, I was able to reproduce it. I'll jump on it for further investigation.

**Comment by obetomuniz** [comment] 2022-07-28 18:05
After further investigation, looks like this legend is displaying the data as expected. Even though the data between `{}` seems unnecessary in some scenarios, it is used to create a unique legend. 

If the investigation doesn't correspond well, could you please provide a more detailed definition of the expected results or additional considerations? Thanks.

**Comment by tatsutaigu** [comment] 2022-07-28 23:18
Thank you for your investigation.
would you please check tool tip on graph?
`name = http_api_request_duration_seconds` appeared in tool tip, 

I guess it is concern about below issue.
[https://github.com/grafana/grafana/issues/46719](https://github.com/grafana/grafana/issues/46719)

**Comment by obetomuniz** [comment] 2022-07-29 12:58
Hey again @tatsutaigu,

So you're saying that you expect legend and tooltip to match the same values, right? 

If so, I'll dive into another investigation to evaluate if the current scenario is the expected, even if that seems divergent. 

Thanks for bringing this to our attention. I'll keep you posted here.

**Comment by tatsutaigu** [comment] 2022-07-29 14:10
Thank you for your reply.

Yes, I expect legend and tool tip to have the same notation.
I mean tool tip is different from legend.

would you please investigate it?

**Comment by obetomuniz** [comment] 2022-07-29 14:22
Hey, thanks for the prompt reply and confirmation. 

> would you please investigate it?

Yes, I'm on it.

**Comment by tatsutaigu** [comment] 2022-07-30 00:57
Hi, Thank you for your cooperation.

I guess
 `Time series` on grafana shows multi data from influxDB + Flux,  then, tool tip strings is different from legend.

for example,
1. below data write to influxDB ( bucket=testBucket ) at the same time.
> DEVICE,id=1 temperature=25.1
> DEVICE,id=2 temperature=25.2
> DEVICE,id=3 temperature=25.3

2. set `time series` and write below query in grafana
> from(bucket: "testBucket")
>   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
>   |> filter(fn: (r) => r["_measurement"] == "DEVICE")
>   |> filter(fn: (r) => r["_field"] == "temperature")
>   |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
>   |> yield(name: "last")

**Comment by obetomuniz** [comment] 2022-08-02 19:00
Hey @tatsutaigu, there is a PR with a fix proposal. As soon as that PR gets merged or discussed, we'll give you updates on the problem fix. Thanks.

**Closed** 2022-08-03 17:47 UTC
Labels: datasource/InfluxDB
