### ISSUE TITLE
Feature Request: Add Azure AD Authentication support

### ISSUE THREAD

**Issue by olkitu** [grafana/grafana#5877] opened 2016-08-21 09:49 UTC
Grafana support Google and Github oAuth but not Azure AD? Please add this feature to grafana.

**Comment by bergquist** [comment] 2016-08-22 06:03
Once https://github.com/grafana/grafana/pull/4718 is merge it should be easy to add Azure AD an a custom provider.

**Comment by tomaszgawlik** [comment] 2016-12-06 08:39
Hi guys, did you manage to get Azure AD working with newest grafana version ? (4.0.1)
I'm trying to match all configuration values but sadly still getting errors:

grafana.ini  setting: 
```
[auth.generic_oauth]
enabled = true
allow_sign_up = true
client_id = {client id from azure}
client_secret = {client secret from azure}
scopes = https://graph.microsoft.com/mail.read  // is this needed ? 
auth_url = https://login.microsoftonline.com/{azure tenantId}/oauth2/authorize
token_url = https://login.microsoftonline.com/{azure tenantId}/oauth2/token
api_url = {azure App ID URI}
team_ids =
allowed_organizations = 
```
Additonaly in azure:
* home page {site url}/login
* my reply url: {site url}/login/generic_oauth

I'm getting: 
```
msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_resource\",\"error_description\":\"AADSTS50001: Resource identifier is not provided. ... "
t=2016-12-06T08:22:02+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr={ip} time_ms=105ns size=702
```

**Comment by bergquist** [comment] 2016-12-06 08:51
Looking back at my comment I might have been misstaken. I'm not sure Azure authentication works the same way as the custom implementation in Grafana.

**Comment by olkitu** [comment] 2016-12-06 10:00
Hmm... I do not have time figure out this but this is my config

`[auth.generic_oauth]
enabled = true
allow_sign_up = true
client_id = {client id from azure}
client_secret ={client secret from azure}
scopes = user:email,read:org
auth_url = https://login.microsoftonline.com/{azure tenantId}f/oauth2/authorize
token_url = https://login.microsoftonline.com/{azure tenantId}/oauth2/token
api_url = https://graph.windows.net/{azure tenantId}
oauth_privder_name = Azure
`

I get this error on grafana

`login.OAuthLogin(NewTransportWithCode)
`

**Comment by mazebuhu** [comment] 2017-02-10 08:29
We hit the same problem when using the `generic_oauth` for Azure. The Problem is that Azure's OAuth requires an additional `resource` parameter when requesting the token. The `golang/oauth` package doesn't implement this since it is not "standard" from what I understand. See https://github.com/golang/oauth2/issues/112

**Comment by hpbieker** [comment] 2017-07-06 07:12
Any chance to get this added? There is currely not any alternative for people using Azure AD?

**Comment by rturam** [comment] 2017-07-14 14:38
Anybody implemented same for Auth0? Any documents appreciated.

**Comment by Nin-0** [comment] 2017-08-21 11:23
We hit the same problem in our environment and I would like to share our knowledge and how we worked around. 
  
First we tried to use default OAuth approach as described in Microsoft docs. Generic-oauth-adapter didn't send a needed resource parameter, so that microsoft api returned "Invalid Resource". We found out, that the resource parameter is a string like this `00000002-0000-0000-c000-000000000000`. We hardcoded it in our configuration and got a response, but the returned json data, didn't contain a field "email" which grafana expects. Instead its name was "mail".

Here's our configuration for the case above:
 
```
[auth.generic_oauth]
enabled = true
allow_sign_up = true
client_id = <client-id>
client_secret = <client-secret>
auth_url = https://login.microsoftonline.com/<tenant-id>/oauth2/authorize?resource=00000002-0000-0000-c000-000000000000
token_url = https://login.microsoftonline.com/<tenant-id>/oauth2/token
api_url = https://graph.windows.net/<tenant-id>/me?api-version=1.6
```

After reading https://stackoverflow.com/questions/32504868/azure-ad-oauth-2-0-invalid-resource we tried to trigger an OpenID workflow with the following config:

```
[auth.generic_oauth]
enabled = true
allow_sign_up = true
client_id = <client-id> 
client_secret = <client-secret> 
scopes = openid,email,profile
auth_url = https://login.microsoftonline.com/<tenant-id>/authorize
token_url = https://login.microsoftonline.com/<tenant-id>/oauth2/token
api_url = https://login.microsoftonline.com/<tenant-id>/userinfo
```
 
We got valid user data, but again no field "email".
 
To work around this we configured "api_url" parameter to point to a small proxy script which talks to the Microsoft "userinfo" endpoint and fetches the data. After that it grabs the "upn" field and adds its content to a new one called "email". Grafana is now able to login users.
 
It would be great to have a more flexible [auth.generic_oauth] adapter with the ability to map returned json fields to that ones grafana expects.

**Comment by E14** [comment] 2017-08-25 11:19
@Nin-0 Thank you for this, it was a great help! However, MS seems to have changed things around a bit, see below:

```
auth_url = https://login.microsoftonline.com/<tenant-id>/oauth2/authorize
# token_url unchanged
api_url = https://login.microsoftonline.com/<tenant-id>/openid/userinfo
```

This also affects your script

**Comment by davidrpk** [comment] 2017-08-27 22:56
Azure AD seems to be working out of the box for me on Grafana 4.4.1 without @Nin-0 script or @mazebuhu code. This is my setup in grafana.conf:

```
[auth.generic_oauth]
enabled = true
allow_sign_up = true
client_id = <client-id> 
client_secret = <client-secret> 
scopes = openid,email,profile
auth_url = https://login.microsoftonline.com/<tenant-id>/oauth2/authorize
token_url = https://login.microsoftonline.com/<tenant-id>/oauth2/token
api_url = https://login.microsoftonline.com/<tenant-id>/openid/userinfo
```

Within your AD in the new Azure portal register your AD (ie: Grafana) and grab the required config:
* The client-id is the application id
* The client-secret is the key generated for api access
* Set a reply URL e.g. http://your.grafana.server.com:3000/login/generic_oauth

**Comment by Nin-0** [comment] 2017-08-28 06:06
@davidrpk thank you for the answer. I've got a typo in the code above, I'm using the same auth_url. Have you done any special configurations in your Azure AD users? I'm currently in contact with Microsoft support and keep you up to date if something changes.

**Comment by davidrpk** [comment] 2017-08-28 10:15
@Nin-0 No special configuration in Azure AD. The Azure AD that grafana is using was freshly deployed with users added from an external Azure AD (enterprise). If there are any tests I can run for you from my working config let me know.

**Comment by E14** [comment] 2017-08-28 10:15
Interesting, I get the feeling that there are different endpoints all over and that they have different versions... for us, with the same configuration, I still got the error that the "email" field does not exist.

However, the openid-configuration (`https://login.windows.net/<tenant-id>/.well-known/openid-configuration`) *claims* that email is supported.

Now the only thing I can think of, where MS would not be at fault is that Grafana doesn't pass the scopes properly, which I can't really believe.

**Comment by Nin-0** [comment] 2017-08-28 10:34
@davidrpk maybe you could do a manual test with your Azure AD configuration and provide the returned json fields. To run the test, I temporarily set api_url in grafana config to a private RequestBin url and grab the authorization header. After that I can send a manual request: `http https://login.microsoftonline.com/<tenant id>/openid/userinfo Authorization:'Bearer  <random stuff>' | jq`

In my case a response looks like
```
{
  "aio": "aio",
  "amr": "amr",
  "family_name": "family_name",
  "given_name": "given_name",
  "ipaddr": "<ip>",
  "name": "name",
  "oid": "<oid>",
  "onprem_sid": "<onprem_sid>",
  "sub": "<sub>",
  "tid": "<tid>",
  "unique_name": "unique_name",
  "upn": "upn",
  "ver": "1.0"
}
```

**Comment by davidrpk** [comment] 2017-08-29 01:25
@Nin-0 
This is my response from openid/userinfo:
```
{
    "aio": "<aio>",
    "amr": "[\"pwd\"]",
    "email": "<email>",
    "family_name": "<family name>",
    "given_name": "<given name>",
    "idp": "<idp address>",
    "ipaddr": "<ip>",
    "name": "<full name>",
    "oid": "<oid>",
    "sub": "<sub>",
    "tid": "<tid>",
    "unique_name": "<unique identifier>",
    "ver": "1.0"
}
```

**Comment by E14** [comment] 2017-08-29 04:10
@davidrpk I think I got a lead now... I did think I was using the "new" AD portal, but it's certainly possible that there is a newer one already, since the one I'm using is already more than 6 months old and soooo last semester. Psh. Anyway it seems my registered App is locked to the v1 API, which does not support the email scope or no scopes at all and that I can't register a v2.0 API app with the portal I was using.

But all I could find was https://apps.dev.microsoft.com , is this the new AAD portal you mentioned?

**Comment by davidrpk** [comment] 2017-08-29 04:37
I'm not sure as I can administer the Azure AD through both portals. I think I may have even deployed the AD and registered the app through the old portal. For reference these are the portals I am referring to:  
Old portal is here: https://manage.windowsazure.com
New portal is here: https://portal.azure.com

In your app registration have you given access to read the user's profile?
This will prompt the user upon first login to allow the app to their read their user profile. I'm assuming without this you won't get the email address?

Did you get anywhere with Microsoft support?

**Comment by Nin-0** [comment] 2017-08-29 07:01
@davidrpk thank you for this. Maybe I have the wrong app permissions, in https://portal.azure.com they look like 
![azure_app_permissions](https://user-images.githubusercontent.com/22942381/29808427-4f25d69c-8c98-11e7-8edc-38d2ecaf5344.png)

Do you have the same permissions?

**Comment by davidrpk** [comment] 2017-08-29 11:54
@Nin-0 I have the same permissions with my app registration.
Here is some more info I found:

> ID tokens that are issued by the v2.0 endpoint do not contain an email claim for the user, even if you acquire permission from the user to view their email.
From: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-limitations

> The email scope can be used with the openid scope and any others. It gives the app access to the user's primary email address in the form of the email claim. The email claim is included in a token only if an email address is associated with the user account, which is not always the case. If it uses the email scope, your app should be prepared to handle a case in which the email claim does not exist in the token.
From: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-scopes#openid-connect-scopes

A few things you can try:
Check your app registration permissions (from above they look correct)!. 
Check the scope is being sent correctly (try using POSTMAN to get the auth header)
Check the user has a email address associated with their account
Try with different types of accounts. Microsoft Account vs. AD account

**Comment by E14** [comment] 2017-08-29 17:07
@davidrpk Yes, those are the same documents I had found and that brought me to the conclusion. At least my API endpoint, but I expect also @Nin-0 's is behaving exactly like the v1 endpoint, while yours seems to be behaving like the v2 endpoint.

I could not verify today, but I'll do that tomorrow, with a new App registered in the UI for  "converged" Apps (https://apps.dev.microsoft.com/)

**Comment by davidrpk** [comment] 2017-08-30 02:39
@E14 Interesting, I have not seen/used the app registration portal that you linked(https://apps.dev.microsoft.com/). I had done everything through the Azure portals. When I log into the apps.dev website my grafana app comes up under "Azure AD only applications". 

Maybe the endpoint is dependent upon the datacenter the AAD is deployed to? It is probably worth checking with Microsoft support to see if the v2 endpoint is available in your region.

**Comment by cameronattard** [comment] 2017-08-30 05:33
I'm also experiencing the issue with Azure AD not returning the email claim.

**Comment by mazebuhu** [comment] 2017-08-30 05:52
We too, therefore we implemented the workaround.

Cameron Attard <notifications@github.com> schrieb am Mi., 30. Aug. 2017 um
07:34:

**Comment by geri-m** [comment] 2017-09-28 16:27
I'm trying to use AAD authentication with Grafana 4.5.2. I tried both endpoints v1 and v2, but I are into the basic problem, that some parameters are not handed over by Grafana zu the Azure-API.

The following configuration is used for V1. The Application was created int Azure Application Portal https://portal.azure.com

```
client_id     = <client_id>
client_secret = <client_secret>
scopes 		  = openid
auth_url      = https://login.windows.net/<tenant-id>/oauth2/authorize
token_url     = https://login.windows.net/<tenant-id>/oauth2/token
api_url       = https://login.windows.net/<tenant-id>/openid/userinfo
```

Grafana generates the following redirect

```
https://login.microsoftonline.com/<tenant-id>4/oauth2/authorize?
access_type=online
&client_id=<client_id>
&redirect_uri=<redirect-url>
&response_type=code
&scope=openid
&state=CQvoohIIIr6diqjW83anVSUabhriqBFDl2hc4F9T3uc%3D
```

When Grafana tries to fetch the token from the API, neither client_id nor client_secret are passed over. (only code, redirect_uri and grant_type are send - verified with a requestbin). But there is a basic authoriation Header "_Authorization: Basic ZTY5NWViZTctYmI5My00MmRlLWIxNGUtNzc2MjFmMmMyN2ZhOkZSQUFWZ0RIejNiVVZZUUxOMHNiOW0w_"

This results in the error:

`ERROR[09-28|16:43:00] login.OAuthLogin(NewTransportWithCode)   logger=context userId=0 orgId=0 uname= error="oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS90014: The request body must contain the following parameter: 'client_id'.\\r\\nTrace ID: 73039bfb-dca2-408a-9c7d-aa0999dd0700\\r\\nCorrelation ID: 0557b0b7-c673-4e95-8aa0-06d090e4ab35\\r\\nTimestamp: 2017-09-28 14:43:19Z\",\"error_codes\":[90014],\"timestamp\":\"2017-09-28 14:43:19Z\",\"trace_id\":\"73039bfb-dca2-408a-9c7d-aa0999dd0700\",\"correlation_id\":\"0557b0b7-c673-4e95-8aa0-06d090e4ab35\"}"`

I also tried to use v2. I create the application in https://apps.dev.microsoft.com/#/appList as stated in https://docs.microsoft.com/de-de/azure/active-directory/develop/active-directory-v2-protocols-oidc

```
client_id     = <client_id>
client_secret = <client_secret>
scopes 		  = openid
auth_url      = https://login.windows.net/<tenant-id>/oauth2/v2.0/authorize
token_url     = https://login.windows.net/<tenant-id>/oauth2/v2.0/token
api_url       = https://login.windows.net/<tenant-id>/openid/userinfo
```

There exactly the same happens. Grafana does not pass on the client-ID and other parameters.

The "callback" form Azure looks like

`http://<host>/login/generic_oauth?code=AQABAAIAAAABlDrqfEFlSaui6xnRjX5Em4FwJP8YzPi4SYeOBRvpcuEdN-ZyW_merCOb4hbKVWeJbIVFNlFn33K5NEMyaE7lG9RRf6-7J2O_1xu2qOGhvesCPD9uaowM9VbDCqgLNF7iDzBLuf0eKs8qIxKmRRULZHiEFZwiyqVQxQk3IYTQmIyTrLTqymqbU-ewFsMtWJlDnB3j0OK1knYFXMFjpfS9OW3YYolncMLGym5iGAgA--_UnkgFQIy7d_OQnRWOM8V0a82QM8zKb3bF_7y6Slt0JZQ7dHAqbojxiPVzl7i6T7Co_VwDlUtUcnJS06JBOPSGXRdQv2BlONlY8BINP-kKqE1g4jWmfLTOsZf0qyv7of_9qhz8O8HN351By-zrLIKBcwCLdz67jm3NCNbLy3Vqz81qDi0rBluyQ2EAYPc-eF8zTJ2q8sFfIZjGnyBUn1FJyJ-Al6QweEPwbCoMV-xQ2-0VAA7B-yOeHQSVJ1CNYjyAKUcAvI-DLVA9nf1_K6AQLhNA0Xz6d1B6QazdczMVWz-umNqq3jovwqcpY05DEiUgKk4okm4Cp0cw3kKBUxNPetxQ6mlQxF3PQjImLsHGFvRg3JY_q__F1wcI0YQ_WEAAWW06qlZNeRwf0JtkohRkRWmPrAZSQWelugzM3zTLbW7_kFBoTisy5KFLaW0cPgtBNk0TpN3OSZi_fVIypLsgAA&state=T7MxDWMwVzymibeGiSrgR2wAQqApfYDYHynPpl5ZIMY%3d&session_state=c44d6fd9-6a65-450d-885d-4062dca21aeb`

Any ideas, how to make use Grafana passed the Client-ID and fetch the token?

**Comment by E14** [comment] 2017-09-30 15:26
@geri-m I hope you know that a basic auth header is just "user:pass" in base64 encoding
(ie. change that appname and secret)

**Comment by geri-m** [comment] 2017-09-30 15:30
@E14 yes, I do. But how do I make grafana pass user (client_id) and password (client_secret) as parameters in the Body and not as basic auth header? This is where I'm struggling. Or is there a way to tell Azure AD to make use of Basic-Auth?

**Comment by E14** [comment] 2017-09-30 15:57
I don't think there was such an option. But since I'm neither part of the Grafana team nor Microsoft, I'm likely the wrong person to ask.

Did you check `https://login.windows.net/<tenant-id>/.well-known/openid-configuration` for whether the URLs are correct for your subscription?

**Comment by geri-m** [comment] 2017-09-30 16:02
Yes, the URLs are correct, but the endpoints only supports

`"token_endpoint_auth_methods_supported":["client_secret_post","private_key_jwt"]`

Look like I have to use some kind of proxy, to convert the basic auth to elements in the body similar to the one @Nin-0 is using. It's a crap, that Microsoft doesn't stick to the standard :-/

**Comment by lukeplausin** [comment] 2017-10-20 08:51
@geri-m Thanks for sharing

I'm also having the same issue with client_id in the body with Grafana 4.5.2. It would be good to get a fix for this!

**Comment by geri-m** [comment] 2017-10-20 09:04
@lukeplausin I dug deeper and figured out, that Microsoft does not stick to the OAuth Implementation standard and this is why it is not working. There are two Issue in the Interface of AAD:
1) Using Basic-Auth in stead of Username + Password in the POST Body
2) Replying with "email" instead of "upn" in the /userinfo Service. 

I don't think Micorsoft is fixing this. So you have to use a proxy (or something that modfies your requests/responses).

**Comment by lukeplausin** [comment] 2017-10-23 13:45
Hi all,

I found this kludge on Github, which seems to address issue 2 outlined by @geri-m about the email/upn header.
https://github.com/traum-ferienwohnungen/openid-proxy

I added a flask endpoint to proxy the `oauth2/token` URL, which copies the auth into the body of the POST request, this seems to address the problem with client_id/client_secret in the POST body (1). 

I submitted a pull request:
https://github.com/traum-ferienwohnungen/openid-proxy/pull/3

Both are working on Grafana 4.5.2 with AzureAD

**Comment by E14** [comment] 2017-10-25 19:12
@lukeplausin ahem, odd question maybe, but did you choose "native application" (or whatever the equivalent) when creating your App on Azure?

Because I was just researching some OAuth (different project though) and noticed that "client_id" is required by OAuth if you are using the implicit grant workflow, which is used when the Application is not trusted (like, In-Browser App or Mobile App)
Grafana is using the confidential client type, where the client_id is optional

**Comment by kr4ster** [comment] 2017-11-03 18:13
@E14 I noticed above that @davidrpk mentioned that his AAD was populated from an external AD while your's appears to be a "fresh" AD instance in Azure (same as I have).  I wonder if @davidrpk has a specific property set in LDAP that openid/userinfo pulls the email address from populated that we do not.  It doesn't really seem appropriate to use the upn or unique_name as the e-mail address because they happen to look like e-mail addresses (when in fact they are user names).

That having been said, the easier thing to do might be to expose an option for the generic_oauth provider that specifies the claim to use as the email address.

**Comment by kdubau** [comment] 2018-04-19 03:14
Any updates? This appears still broken.

**Comment by mazebuhu** [comment] 2018-04-19 05:10
No for us it is working now with the default general_oauth configuration.
See the official documentation
http://docs.grafana.org/installation/configuration/ and search for “Set up
oauth2 with Azure Active Directory”

**Comment by DanCech** [comment] 2018-05-22 23:07
This was fixed in #10560

**Closed by DanCech** 2018-05-22 23:07 UTC
Labels: P4: nice to have, help wanted, type: feature request

**Comment by lukasmrtvy** [comment] 2019-01-14 14:18
@palmamartin: what AAD permissions did you setup for Grafana? 
I am creating AAD app with:
```
az ad app create --display-name "Grafana-Azure-Oauth" --reply-urls https://grafana.example.com/login/generic_oauth --identifier-uris https://grafana.example.com/ --password verysecret 
```
and running like:
```

docker run -d \
--name grafana \
-e "GF_SERVER_ROOT_URL=https://grafana.example.com/" \
-e GF_AUTH_GENERIC_OAUTH_ENABLED=true \
-e GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=false \
-e GF_AUTH_GENERIC_OAUTH_CLIENT_ID=<appclient>     \
-e GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=verysecret \
-e "GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile" \
-e GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://login.microsoftonline.com/<tenant>/oauth2/authorize \
-e GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://login.microsoftonline.com/<tenant>/oauth2/token \
grafana/grafana:5.4.2
```
, but I am getting: 
```
t=2019-01-14T14:08:07+0000 lvl=eror msg="Login provider denied login request" logger=context userId=0 orgId=0 uname= error=access_denied errorDesc="AADSTS65005: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant. Client app ID: <appclient>.\r\nTrace ID: 0aecdb92-2866-4e91-aea0-d34ff5266600\r\nCorrelation ID: 586dc13e-2bf5-45c7-9347-fcf127362047\r\nTimestamp: 2019-01-14 14:08:07Z"
t=2019-01-14T14:08:07+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=10.130.174.65 time_ms=0 size=29 referer="https://<url>"
```

Seems that is needed to setup AAD Grants:
Like for AKS in Azure
https://gist.github.com/neilpeterson/ecf2dccae05f110f3cb244a0e2e1ac80

There is info about used appids in az commands above
https://github.com/mjisaak/azure-active-directory/blob/master/README.md#well-known-appids   


Can You confirm this? 
Thanks

**Comment by palmamartin** [comment] 2019-01-22 14:55
@lukasmrtvy I simple registered an app on  https://portal.azure.com > Azure Active Directory > App registrations
