### ISSUE TITLE
[Feature Request] Allow arbitrary timezone selections

### ISSUE THREAD

**Issue by tphipps** [grafana/grafana#5835] opened 2016-08-17 08:55 UTC
Currently, there are three Timezone options on the Dashboard Settings page:

- Default
- Local Browser Time
- UTC

I'd like to see this allow any timezone (https://www.iana.org/time-zones) to be specified rather than just these options. This would be very useful when creating dashboards that relate to data collected from a specific geographical region, so everyone viewing the dashboard can see it in the timezone of the region it relates to. This is particularly important when trying to visualize trends that happen during local business hours, local peak hours, local waking hours etc.

It's surprisingly hard to calculate the offsets in your head when looking at visualizations of data that relate to a timezone not where you are and see related trends (eg. "aah - things go awry at midnight local time each day")

**Comment by torkelo** [comment] 2016-08-17 08:59
duplicate of https://github.com/grafana/grafana/issues/558

**Closed by torkelo** 2016-08-17 08:59 UTC
