### ISSUE TITLE
Alertmanager plugin no longer works with Grafana 6.7.1

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#23023] opened 2020-03-24 11:42 UTC
**What happened**:
I updated grafana to 6.7.1 (from 6.6)
**What you expected to happen**:
Things would continue to work
**How to reproduce it (as minimally and precisely as possible)**:
I'm using containers,
Start grafana,
start alertmanager:
`docker run -d --name aalrt prom/alertmanager:v0.20.0`
open the grafana dashboard and add the alertmanager data source.

you can test and see that it's working:
![image](https://user-images.githubusercontent.com/2118079/77434968-525fb400-6dea-11ea-98e0-b4f27382520f.png)

Now open a dashboard and try to create a table that uses the alermanager datasource.
you'll get an error.

![image](https://user-images.githubusercontent.com/2118079/77421787-1a01ab00-6dd5-11ea-8cd2-b8262e9fe03f.png)
![image](https://user-images.githubusercontent.com/2118079/77421903-5503de80-6dd5-11ea-84ca-9c612f5d93f0.png)

**Anything else we need to know?**:
I use Docker containers, it stopped working when I updated Grafana.

**Comment by torkelo** [comment] 2020-03-24 13:32
looks like a problem with the plugin

**Comment by amnonh** [comment] 2020-03-24 13:41
It is the standard plugin that works solid for years.

**Comment by aknuds1** [comment] 2020-03-24 13:43
Could you provide more detail on how to reproduce it please?

**Comment by amnonh** [comment] 2020-03-24 13:58
To reproduce you need alertmanager configure as a data source.
I don't think there is something specific in my setup, could it be that something in the changes between 6.6 and 6.7.1 broke the alertmanager plugin support?

An example for a dashboard that uses alertmanager:
```
{
    "annotations": {
        "list": []
    },
    "class": "dashboard",
    "editable": true,
    "gnetId": null,
    "graphTooltip": 1,
    "hideControls": true,
    "id": null,
    "links": [],
    "originalTitle": "Scylla Cluster Metrics",
    "overwrite": true,
    "panels": [
        {
            "class": "alert_table",
            "columns": [],
            "datasource": "alertmanager",
            "fontSize": "100%",
            "gridPos": {
                "h": 6,
                "w": 8,
                "x": 0,
                "y": 0
            },
            "id": 1,
            "links": [],
            "options": {},
            "pageSize": null,
            "scroll": true,
            "showHeader": true,
            "sort": {
                "col": 0,
                "desc": true
            },
            "span": 4,
            "styles": [
                {
                    "alias": "Time",
                    "dateFormat": "YYYY-MM-DD HH:mm:ss",
                    "link": true,
                    "linkTooltip": "Jump to the see the node",
                    "linkUrl": "/d/detailed-[[dash_version]]/detailed?refresh=30s&orgId=1&var-by=instance&var-node=${__cell_4}&from=${__cell_0}",
                    "pattern": "Time",
                    "type": "date"
                },
                {
                    "class": "hidden_column",
                    "pattern": "severity",
                    "type": "hidden"
                },
                {
                    "class": "hidden_column",
                    "pattern": "alertname",
                    "type": "hidden"
                },
                {
                    "class": "hidden_column",
                    "pattern": "cluster",
                    "type": "hidden"
                },
                {
                    "class": "hidden_column",
                    "pattern": "monitor",
                    "type": "hidden"
                },
                {
                    "class": "hidden_column",
                    "pattern": "summary",
                    "type": "hidden"
                },
                {
                    "alias": "Instance",
                    "colorMode": null,
                    "colors": [
                        "rgba(245, 54, 54, 0.9)",
                        "rgba(237, 129, 40, 0.89)",
                        "rgba(50, 172, 45, 0.97)"
                    ],
                    "dateFormat": "YYYY-MM-DD HH:mm:ss",
                    "decimals": 2,
                    "link": true,
                    "linkTooltip": "Jump to the see the node",
                    "linkUrl": "/d/detailed-[[dash_version]]/detailed?refresh=30s&orgId=1&var-by=instance&var-node=${__cell}",
                    "mappingType": 1,
                    "pattern": "instance",
                    "thresholds": [],
                    "type": "string",
                    "unit": "short"
                },
                {
                    "alias": "",
                    "colorMode": null,
                    "colors": [
                        "rgba(245, 54, 54, 0.9)",
                        "rgba(237, 129, 40, 0.89)",
                        "rgba(50, 172, 45, 0.97)"
                    ],
                    "decimals": 2,
                    "pattern": "/.*/",
                    "thresholds": [],
                    "type": "number",
                    "unit": "short"
                }
            ],
            "targets": [
                {
                    "annotations": true,
                    "expr": "job!=\"scylla_manager\"",
                    "legendFormat": "{{description}}",
                    "refId": "A",
                    "target": "Query",
                    "type": "table"
                }
            ],
            "title": "Active Alerts",
            "transform": "table",
            "type": "table"
        }
    ],
    "refresh": "30s",
    "schemaVersion": 16,
    "style": "dark",
    "tags": [
        "master"
    ],
    "templating": {
        "list": []
    },
    "time": {
        "from": "now-30m",
        "to": "now"
    },
    "timepicker": {
        "now": true,
        "refresh_intervals": [
            "5s",
            "10s",
            "30s",
            "1m",
            "5m",
            "15m",
            "30m",
            "1h",
            "2h",
            "1d"
        ],
        "time_options": [
            "5m",
            "15m",
            "1h",
            "6h",
            "12h",
            "24h",
            "2d",
            "7d",
            "30d"
        ]
    },
    "timezone": "browser",
    "title": "Overview",
    "uid": "overview-master",
    "version": 1
}
```

**Comment by aknuds1** [comment] 2020-03-24 14:06
Thanks for the additional detail - please enter specific steps in the _How to reproduce it (as minimally and precisely as possible)_ section on how I (and others) can reproduce the issue.

**Comment by amnonh** [comment] 2020-03-24 14:14
I did my best to clear it out in the description.

**Comment by jongyllen** [comment] 2020-03-31 15:30
Hi, this issue seems to be with the prometheus alertmanager datasource (due to changes in Gafana 6.7)
There is already an issue for this in that repository, camptocamp/grafana-prometheus-alertmanager-datasource#72
There is also a PR to fix it, camptocamp/grafana-prometheus-alertmanager-datasource#73

So I am closing this issue in Grafana for this.

**Closed by jongyllen** 2020-03-31 15:30 UTC
Labels: area/datasource, needs investigation
