### ISSUE TITLE
Alerting when using cloudwatch is not possible using variables and there is no work-around

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#20154] opened 2019-11-04 10:31 UTC
**What would you like to be added**:
Allow template variables to be used in alerting when using the cloudwatch data source as there is no way to alert dynamically as AWS does not support regex in query

**Why is this needed**:

As its currently not possible to alert with variables in a dynamic dashboard. With 1000s of servers and instance lists changing (created and deleted due to autoscaling) its not feasible to make static dashboards

**Comment by marefr** [comment] 2019-11-04 13:09
Duplicate of #6557

**Closed** 2019-11-04 13:09 UTC
