### ISSUE TITLE
Row panel does not update variables/templating values

### ISSUE THREAD

**Issue by arnaudlemaignen** [grafana/grafana#15133] opened 2019-01-30 10:38 UTC
### What Grafana version are you using?

5.4.3
### What datasource are you using?
prometheus (but here the bug is happening on any datasource)
### What OS are you running grafana on?
Linux
### What did you do?
create a dashboard with
- a variable (custom or query)
- a row panel with the title using the variable
### What was the expected result?
when selecting a new variable in the drop down, the row panel should show the new selected value
### What happened instead?
the row shows the previous value, not updating the new value

this was tested on firefox and chrome.
THIS IS A REGRESSION it used to work previous grafana version, at least 5.2.4

below a screenshot

![row panel bug](https://user-images.githubusercontent.com/22667740/51975701-303b0200-2483-11e9-882a-60856df6c8ee.png)

and a dashboard to rename to json to test it

[Row and var bug-1548844056678.txt](https://github.com/grafana/grafana/files/2812133/Row.and.var.bug-1548844056678.txt)

**Comment by xlson** [comment] 2019-01-30 16:26
Thanks for posting such a clear repo case with the Dashboard.json!

**Comment by xlson** [comment] 2019-01-30 16:27
@marefr could this be related to the work you did in improving template variables and how they trigger changes? Or, is it something different?

**Comment by torkelo** [comment] 2019-02-01 07:19
thanks for reporting this, fixed in master now (latest nightly build shortly) and will be fixed in beta2

**Closed** 2019-02-01 07:19 UTC
Labels: comp: dashboard/templating, type: bug

**Comment by jorgeallyson** [comment] 2019-05-24 14:41
This is happening for me on Grafana 6.2. At this moment the only way to update the row is doing it manually. Maybe this is a regression?

**Comment by torkelo** [comment] 2019-05-24 14:44
If you use a variable in a row title it does not update ?

**Comment by jorgeallyson** [comment] 2019-05-24 14:53
Yes, the same as the example posted by @arnaudlemaignen . I have to go to the row settings and press the update button. Only then the row title and panels are updated.

**Comment by jorgeallyson** [comment] 2019-05-29 15:25
Since this bug was closed, should I open a new one? I have just upgraded to grafana 6.2.1 and the issue still remains. Due to this problem users with viewer roles cannot properly interact with the dashboards.

**Comment by torkelo** [comment] 2019-05-29 16:14
@jorgeallyson 
Unable to replicate. The row title updates whenever I change a template variable and have no other reports that this is not fixed.

https://play.grafana.org/d/000000153/repeat-rows?openVizPicker&orgId=1&var-app=backend&var-server=backend_01&var-interval=$__auto_interval_interval

**Comment by jorgeallyson** [comment] 2019-05-29 18:27
OK, I think my issue is actually different. Dashboards with only one variable are indeed working. The problem is with dashboards with more than one variable. Also, in my case the other variables are dependent on the value of the first. Sometimes it creates the extra rows as expected, but the titles are wrong, repeating one value multiple times. I will have to do more tests to try and find out what is really happening.

**Comment by baodongli** [comment] 2020-11-12 19:05
![image](https://user-images.githubusercontent.com/3081257/98983858-67ab5f00-24ef-11eb-8214-4e565e9a8776.png)
My question is how do I refer to the variables' values on each row? In this case, I have three variables: site, pod, cluster.
For example, if I want to link to another dashboard in each row, with the following:
<a href="/dashboard/db/cluster-detail?var-site=$site&var-pod=$pod&var-cluster=$cluster">Detail dashboard</a>

Clicking the link will lead to the detailed dashboard. However the variables's values are incorrect for site and pod. Did I write the hyperlink correctly? Or this is something not supported yet?
