### ISSUE TITLE
[Feature request]Update alert condition based on date and time

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#7228] opened 2017-01-11 21:42 UTC
Please include this information:
- What Grafana version are you using?
v4.0.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centOS

It would be better to let user add alert condition based on time range, for example, set the alert threshold to 100 from 8:00 AM to 6:00 PM and decrease it to 50 for the rest of the day, or set the threshold to 100 for weekdays and decrease it to 50 for the weekend.

**Comment by torkelo** [comment] 2017-01-12 07:46
duplicate of https://github.com/grafana/grafana/issues/6592

**Closed by torkelo** 2017-01-12 07:46 UTC
