### ISSUE TITLE
[ Feature request ] Add option to add dashboard name to alerts in slack notifications

### ISSUE THREAD

**Issue by luispabon** [grafana/grafana#12943] opened 2018-08-16 12:43 UTC
### What Grafana version are you using? 
grafana.net hosted

### What datasource are you using? 
n/a

### What OS are you running grafana on?
n/a

### What did you do?
Created alerts, get them piped into slack

### What was the expected result?
Alerts arrive just fine, but they have no information of which dashboard they belong to. Since I have a whole load of alerts for different services in different dashboards, I need to prefix each alert's name with the name of the dashboard to be able to tell them apart on the slack channel, otherwise I don't know if I'm having a "Throughput alert" from Foo service in production or Bar service in staging.

**Comment by xlson** [comment] 2018-08-17 09:13
Dupe of #5848

**Closed by xlson** 2018-08-17 09:13 UTC
