### ISSUE TITLE
Annotation description and tags defaults 

### ISSUE THREAD

**Issue by tholcman** [grafana/grafana#19482] opened 2019-09-28 15:42 UTC
I will be labeling (annotating) a lot of events for a machine learning dataset. It is pretty annoying to always write Description and add Tags for each annotation. 

I have already prepared something, what suits me best. I read defaults for non-existing annotations from the dashboard variables.

https://github.com/tholcman/grafana/pull/1/files

I have few questions

1. Is something like that possible to compose in a plugin? I guess no, without ugly DOM modifications.
2. Would something like that be appreciated as PR to public grafana?

* it is definitely not ready - I am not sure about code placement, hardcoded variable names are pretty bad, no handling of variable types (single-value vs. multi-value), ...

**Comment by pbaumard** [comment] 2019-09-30 06:18
Issue #13786 has another proposal for tag defaults.

**Comment by hugohaggmark** [comment] 2019-09-30 06:26
Hi @tholcman, we use GitHub for issues and feature requests. For questions we prefer that you ask them at the [community site](https://community.grafana.com/) or in our [Slack channel](https://grafana.slack.com/).

Duplicate of #13786

**Closed by hugohaggmark** 2019-09-30 06:26 UTC
Labels: type/duplicate
