### ISSUE TITLE
Allow Grafana's Global editing in Variables tab

### ISSUE THREAD

**Issue by CrashLaker** [grafana/grafana#17287] opened 2019-05-26 17:14 UTC
Hi all.

One feature I'd really like to see in Grafana is some shortcuts on setting up the time range.

Is it possible to overwrite the $__from and $__to variables in Grafana through another input?

Like.
![image](https://user-images.githubusercontent.com/4432491/58384983-4899d400-7fc0-11e9-8c28-7d7203b21c65.png)

So that I could do something like this..
![image](https://user-images.githubusercontent.com/4432491/58384987-6e26dd80-7fc0-11e9-8fc0-f70ac1e7aaae.png)

thank you!

**Comment by torkelo** [comment] 2019-05-27 05:33
duplicate of https://github.com/grafana/grafana/issues/8267

**Closed by torkelo** 2019-05-27 05:33 UTC
