### ISSUE TITLE
[Feature Request] Add ability to override the dashboard time with Absolute Time Range per panel.

### ISSUE THREAD

**Issue by scroodj** [grafana/grafana#22163] opened 2020-02-13 10:39 UTC
Hello.

So far we can only override the dashboard time with relative time ranges. Absolute time ranges are not available. Would be nice to have such an ability.

Thanks!

**Comment by sakjur** [comment] 2020-02-13 13:00
Hello, what would be the use case for this? Would solving #15829 provide you with what you want?

**Comment by scroodj** [comment] 2020-02-13 13:34
Hello,

my use case is: i have several panels (stat, table) within the same dashboard. For one group of panels i need Absolute Time Range: [now/d-6h TO now] for another: [now/w-6h TO now].
At the moment i split panels across different dashboards with specifying Time Range via Time Picker. But having many dashboards with it`s own Absolute Time range is not a good deal.
So, solving #15829 does not affect me.

**Comment by sakjur** [comment] 2020-02-13 15:34
:+1: Ok, that makes sense. Thank you for your feature request 🙂 The feature sounds useful, but already with time shifts we have some confusion and complexity around how this functionality work in general. Adding absolute time ranges per panel would likely require quite some thought being put into it to make sure it works as well as we'd want it to.

**Comment by scroodj** [comment] 2020-02-13 16:17
Thx. I believe you can handle over it. You guys do a grate jobs👍

**Comment by oligu** [comment] 2020-07-16 09:28
Hello,
Been sent over from #26346.
My request is closely related: we like to apply a Relative time to a panel even when there is an Absolute time on the dashboard.
Use case: We have many graph panels where we visualize measurement data. There we like to show the data of the whole measurement campaign e.g. `22.06.22 00:00:00 to now`. At the same time we like to have panels which show e.g. only the last day or the last 5 minutes in more detail.

**Comment by SpyridonSt** [comment] 2021-03-30 12:40
Hi, 
I think there are other users like myself who would greatly appreciate the ability to have an absolute time ranget per panel.
My use case is using IoT sensors to collect environmental and building performance data, where very often we need to look into historical data, make comparisons on fixed time period, while at the same time view other information for different times.
This feature would radically improve our use of Grafana and how helpful it is for us

**Comment by fifofonix** [comment] 2021-04-06 14:45
Adding another use case to bolster the case for this enhancement.

In some situations a dashboard is designed to investigate a particular time period specifically.  In our case in healthcare it is a patient encounter where we have a lot of machine data and video associated with the visit.  When a healthcare provider is examining how medical instruments were used in a particular encounter they have selected, they want to be time bound to this patient's encounter, but be able to zoom in on a graph panel's depiction of an instrument's use.  Then they want to zoom out again but still be time bound to the encounter.  In our scenario we line up camera jpg snapshots to the time period using a panel plug-in.  Yes, Grafana is really super-cool.  Provider pans out.  Pans in.  Repeats.

The problem we have is that the time period selector at top right is not easy to use, jumping in/out despite keystrokes etc.  And, you can easily get lost in what period of time within the appointment you're viewing and even spill over into other patient encounters.  Am I drilled down on the third use of this medical instrument or the second?  Were we to have a panel time-range pinned to the whole appointment, yet still allowing time periods to be selected on it, then we could have a secondary panel showing the drilled down view.  This would make for a much more intuitive user experience for this use case.  I recognize though that some panel differentiation probably needs to occur so that it is clear that a panel is fixed to an absolute time.  For me expanding on the existing top-right time offset descriptions would seem enough but I agree they are easy to miss.

**Comment by fifofonix** [comment] 2021-04-15 11:19
Note this functionality can be achieved with a community plug-in as described here: https://community.grafana.com/t/pinning-a-panel-to-a-static-timerange/45368

**Comment by torkelo** [comment] 2021-10-04 08:54
dupe of https://github.com/grafana/grafana/issues/11552

**Closed by torkelo** 2021-10-04 08:54 UTC
Labels: type/feature-request, area/panel/graph, priority/nice-to-have
