### ISSUE TITLE
Explore: Uncaught (in promise) TypeError: Cannot read property 'finally' of undefined

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#23297] opened 2020-04-02 14:33 UTC
**What happened**:
I have observed an error in the grafana console that shows when I open Explore

**What you expected to happen**:
I expect to not see any errors in the console

**How to reproduce it (as minimally and precisely as possible)**:
I have installed 6.7.2 from docker.
I have Graphite as default source. 
I opened the "Explore" tab.
Then I saw this:

![image](https://user-images.githubusercontent.com/8693064/78261133-e7139180-750f-11ea-807c-3463714a9bc0.png)

It also happens each time I click on "Split"

**Anything else we need to know?**:
It doesn't seem to affect anything as I could run queries and see results.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Graphite 1.1.7
- OS Grafana is installed on: Docker
- User OS & Browser: macOS 10.15.4 (19E266) / Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- Grafana plugins: none

**Comment by jongyllen** [comment] 2020-04-03 08:03
Hi, thanks for submitting this. I verified it and it is actually the same for when querying in the graph panel as well

**Comment by daniellee** [comment] 2020-04-20 17:14
Stack trace here:

```
Uncaught TypeError: Cannot read property 'finally' of undefined
    at promiseToDigest.ts:3
    at GraphiteQueryCtrl.buildSegments (query_ctrl.ts:64)
    at GraphiteQueryCtrl.parseTarget (query_ctrl.ts:49)
    at GraphiteQueryCtrl.toggleEditorMode (query_ctrl.ts:54)
    at QueryEditor.componentDidUpdate (QueryEditor.tsx:78)
    at QueryEditor.componentDidUpdate (react-hot-loader.development.js:642)
    at commitLifeCycles (react-dom.development.js:22117)
    at commitLayoutEffects (react-dom.development.js:25344)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
```

@hugohaggmark @mckn do either of you have time to fix this? It's something to do with the extra digest that got added.

You can reproduce it by choosing a Graphite ds in Explore and then doing a split or clicking on the edit icon (https://community.grafana.com/t/explore-v6-7-2-crashes-when-toggling-the-query-editor-mode/28898).

**Comment by torkelo** [comment] 2020-04-20 17:25
This should be fixed in master and in upcoming 6.7.3 (no eta)

**Comment by torkelo** [comment] 2020-04-20 17:26
https://github.com/grafana/grafana/pull/23512

Can you try nightly?

**Comment by daniellee** [comment] 2020-04-21 08:08
@torkelo tested on the latest master and it is sort of fixed there. But seeing other issues instead. If you click on split for a graphite data source in Explore, then this gets called: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/dashboard/datasource.ts#L17

![image](https://user-images.githubusercontent.com/434655/79841619-fa4fa980-83b7-11ea-84aa-a326b53af064.png)

**Comment by torkelo** [comment] 2020-04-21 08:30
@daniellee that looks like a bug in explore 

When debugging with any angular query editor the QueryRow in explore get rendered first with the correct data source then with the `-- Dashboard --` data source. So something strange is going on with datasourceInstance in the split.

**Comment by torkelo** [comment] 2020-04-21 08:33
closing this and opening new issue for that explore bug

**Closed by torkelo** 2020-04-21 08:33 UTC
Labels: datasource/Graphite, type/bug
