### ISSUE TITLE
Allow State Timeline Visualization an "Expand From Query" Option

### ISSUE THREAD

**Issue by lux4rd0** [grafana/grafana#36922] opened 2021-07-19 15:59 UTC
**What would you like to be added**:

When using the State Timeline plugin with data that isn't refreshed at regular intervals, there will most likely be "missing" data to the left of the last measurement. This leaves the previous state unknown. Asking to provide a Query Builder option that, with a time configuration, extends the time frame that is requested (normally with the $timeFilter variable.).

Just makes the state timeline present more effectively what happens _before_ the selected time range.

**Why is this needed**:

Current:

![current](https://user-images.githubusercontent.com/30187533/126189963-ef37828b-58bb-40a1-b8f8-4da673da0e0a.png)

Using `$timeFilter`

Proposed:

![after](https://user-images.githubusercontent.com/30187533/126189994-b7d85e13-9b20-4084-95c8-9cf87bdbc4ff.png)

Using: `(time >= ${__from}ms - 48h AND time <= ${__to}ms)`
_(48h listed here would be a new UI variable)_

edit - may be similar to https://github.com/grafana/grafana/issues/35541 - although not sure how the implementation for different use cases may affect the desired outcome.

**Comment by leeoniya** [comment] 2021-07-19 17:19
this is a duplicate of https://github.com/grafana/grafana/issues/36417

**Closed by leeoniya** 2021-07-19 17:19 UTC
