### ISSUE TITLE
Renaming a data sources breaks dashboards using the "old" name

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#35252] opened 2021-06-04 13:40 UTC
**What would you like to be added**:

When I rename a data source instances, I expect any existing panels using that data source will continue to work with the new name.

Currently, after you rename a dashboard you must manually go through and update data sources to the new name, which is a pain.

_Strictly speaking_ I believe this to be more of a bug than a feature request, but it's an enhancement nonetheless.

**Why is this needed**:

So Grafana is better 😇

**Comment by pkolyvas** [comment] 2021-06-04 19:11
Hey Josh! This is a dupe of #1664 - but one I too would like remedied. 

I'm going to close it, but that said, there's real UX value here, and I agree — it certainly straddles the "defect/feature request" line. :)

**Closed by pkolyvas** 2021-06-04 19:11 UTC
Labels: type/feature-request

**Comment by joshhunt** [comment] 2021-06-07 10:02
I promise i looked for an existing issue 😅
