### ISSUE TITLE
Using any transform option causes Panel to error

### ISSUE THREAD

**Issue by dp106** [grafana/grafana#25361] opened 2020-06-04 11:08 UTC
**What happened**:
If I try and use any of the new Transform options in V7 it causes the panel to error. I then have to close the dashboard without saving changes to avoid permanently breaking the dashboard.

**What you expected to happen**:
I was hoping the data would be transformed.  In some cases it will do the transform, for example reduce works initially. However if you exit the panel editor and go back in to it and try and edit transforms further it then errors. 

**How to reproduce it (as minimally and precisely as possible)**:
Seems to occur any time I do a transform. Go to the transform tab, select a transform, click the query tab and then back to the transform tab causes the error

**Anything else we need to know?**:

**Environment**:
- Grafana version:
v7.0.1
- Data source type & version:
SQL Server 2014 SP3

- OS Grafana is installed on:
Windows 2019

- User OS & Browser:
Windows 10, Chrome *tried with Edge browser and same result

- Grafana plugins:
Piechart, renderer, multistat
- Others:

Grafana error: "TypeError: Cannot read property 'data' of null"

**Comment by kylebrandt** [comment] 2020-06-04 12:06
Duplicate of https://github.com/grafana/grafana/issues/25122 , and fixed in 7.0.3 https://github.com/grafana/grafana/releases/tag/v7.0.3 (which was just released).

**Closed by kylebrandt** 2020-06-04 12:06 UTC

**Comment by dp106** [comment] 2020-06-04 13:07
Thanks @kylebrandt I checked previously and there wasn't a further release, didn't recheck unfortunately!
