### ISSUE TITLE
Logs histogram Y-axis values get truncated

### ISSUE THREAD

**Issue by ak2766** [grafana/grafana#57994] opened 2022-11-01 14:37 UTC
notes by @gabor : when displaying a logs-histogram in explore, if a Y-axis number starts with a "wide" digit, like `2` or `0.`, it's left-side will get slightly truncated. 

---

**Describe the bug**
The Y-axis values in Loki log browser are truncated.

**To Reproduce**
1. Launch Chrome
2. Login to Grafana
3. Explore and navigate to Loki log browser
4. Search for logs and when search returns witness that the y-axis values are truncated:
<details>
<summary>Truncated Y-axis values</summary>

![image](https://user-images.githubusercontent.com/6629646/199258770-809d44da-433f-4d7b-af09-105ef3f95758.png)

</details>

**Expected behavior**
I expected the y-axis values to be clearly visible.

The issue is present on both Firefox (105.0) and Chrome (107.0.5304.68)

**Comment by usmangt** [comment] 2022-11-07 10:55
Hi @ak2766,

Thanks for opening this issue.

I was not able to reproduce this while using the above steps.

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by ak2766** [comment] 2022-11-11 12:45
@usmangt - Thanks for looking into this.

I have older monitors (non-4K on 1920x1080 res) so I normally zoom out to see more data.  Here I've only zoomed out to 90% but you can already see the problem.

<details>
<summary>Problem replicated on Grafana playground</summary>

![Selection_01162](https://user-images.githubusercontent.com/6629646/201343010-cb7e0ab1-237c-4eb0-a738-f0d24c56035a.png)

</details>

**Comment by gabor** [comment] 2022-11-14 12:14
investigation notes: this does not happen when explore displays a graph for a metric query. we use the `<ExploreGraph` component in both cases, but in the logs-histogram case it has less horizontal space to use.

**Comment by matyax** [comment] 2023-01-18 15:20
I can no loger replicate this with the latest Grafana. I see it in Play, but it's using 9.3. What do you think @gabor ?

**Comment by gabor** [comment] 2023-01-19 08:28
@matyax wrote:
> I can no loger replicate this with the latest Grafana. I see it in Play, but it's using 9.3. What do you think @gabor ?

i think we can close it then 👍 . the author of the issue can reopen it if they can still reproduce it with newest-grafana.

**Comment by matyax** [comment] 2023-01-19 10:44
Should be fixed in the next minor release.

**Closed by matyax** 2023-01-19 10:44 UTC
Labels: type/bug, area/explore, area/logs
