### ISSUE TITLE
`eval_data` column empty in `alert` table when notification channel has send reminders on

### ISSUE THREAD

**Issue by manitua** [grafana/grafana#20358] opened 2019-11-13 12:44 UTC
**What happened**:
I am monitoring some metrics, in this particular case memory usage, and have created alert to send when metric is above some threshold.

Notification channel is set as type `webhook` with "Send reminders" set on and "Send reminder every" to value larger then evaluation period. "Send reminders" are used to be able to get notifications even if `state` is `alerting`.

This is how it looks:
![image](https://user-images.githubusercontent.com/5458346/68762739-0cfad100-0617-11ea-9e31-754e44e41cf0.png)

And in DB in `alert` table:
```sql
sqlite> SELECT state, eval_data FROM alert WHERE id = 2;
state|eval_data
ok|{}
sqlite>
```
If alert is triggered, simulated by lowering threshold:
![image](https://user-images.githubusercontent.com/5458346/68763218-32d4a580-0618-11ea-88bf-33931ebf180a.png)

DB:
```sql
sqlite> SELECT state, eval_data FROM alert WHERE id = 2;
state|eval_data
alerting|{"evalMatches":[{"value":417628160,"metric":"consent-log-747cbc5496-xpfkz","tags":{"__name__":"container_memory_usage_bytes","beta_kubernetes_io_arch":"amd64","beta_kubernetes_io_os":"linux","container_name":"consent-log","id":"/kubepods/burstable/pod56fabf2d-8921-11e9-bfbe-005056821e22/33b57ee56764ea84cb7ec0d9f4baf4ee3e7c42d7aaf1fad1635e21fe389c50c4","image":"sha256:23d9c77f55460859166bff75cadbc93093e0a08b76dc2ac84ba0b374c56d2cdc","instance":"host003t","job":"kubernetes-cadvisor","kubernetes_io_hostname":"host003t","name":"k8s_consent-log_consent-log-747cbc5496-xpfkz_hbp_56fabf2d-8921-11e9-bfbe-005056821e22_2","namespace":"team1","node_role_kubernetes_io_worker":"true","pod_name":"consent-log-747cbc5496-xpfkz","platform_context":"team1"}}]}
sqlite>
```  

So far so good, works as expected. But, as I have "Send reminders", lets assume that the other containers memory consumption went above threshold (simulated by lowering threshold):
![image](https://user-images.githubusercontent.com/5458346/68763667-446a7d00-0619-11ea-8de5-09d8de8ae1c8.png)

Now in DB `eval_data` column is empty:
```sql
sqlite> SELECT state, eval_data FROM alert WHERE id = 2;
state|eval_data
alerting|
sqlite>
```
Webhook receiver, on the other side, has received following:
1) Initial alert (and also repeated ones):
```
Timestamp: 2019-11-13 12:18:31.146922125 +0000 UTC
URL:       /k8s
===== POST =====
> RuleId:    2
> Rule Name: Total Memory Usage alert
> State:     alerting
> Title:     [Alerting] Total Memory Usage alert
> Message:   Berra ballar ur totalt
> [EvalMatches]:
> > Metric: consent-log-747cbc5496-xpfkz
    Value:  417628160.000000
    [Tags]:
      __name__:       container_memory_usage_bytes
      pod_name:       consent-log-747cbc5496-xpfkz
      container_name: consent-log
      instance:       host003t
      namespace:      team1
``` 
2) When the second metric went above threshold we received it (also repeated ones):
```
Timestamp: 2019-11-13 12:25:51.102104862 +0000 UTC
URL:       /k8s
===== POST =====
> RuleId:    2
> Rule Name: Total Memory Usage alert
> State:     alerting
> Title:     [Alerting] Total Memory Usage alert
> Message:   Berra ballar ur totalt
> [EvalMatches]:
> > Metric: consent-log-747cbc5496-xpfkz
    Value:  417636352.000000
    [Tags]:
      __name__:       container_memory_usage_bytes
      pod_name:       consent-log-747cbc5496-xpfkz
      container_name: consent-log
      instance:       host003t
      namespace:      team1
> > Metric: consent-log-747cbc5496-dbzzt
    Value:  402239488.000000
    [Tags]:
      __name__:       container_memory_usage_bytes
      pod_name:       consent-log-747cbc5496-dbzzt
      container_name: consent-log
      instance:       host001t
      namespace:      team1
```

**What you expected to happen**:
Same as above, just that `eval_data` column should contain data, `evalMatches`, for both metrics. 

**How to reproduce it (as minimally and precisely as possible)**:
Described above.

**Environment**:
- Grafana version: 6.6.0-pre (version=6.6.0-pre commit=822b0b2708 branch=master)
- Data source type & version: Prometheus 2.13.0
- OS Grafana is installed on: Ubuntu 18.04 LTS
- User OS & Browser: Ubuntu 18.04 LTS, Firefox 70

**Comment by papagian** [comment] 2019-11-15 18:42
The reason this is happening is that during the alert [update](https://github.com/grafana/grafana/blob/v6.5.0-beta1/pkg/services/sqlstore/alert.go#L208) the `eval_data` column is updated even though the `alert.Eval` is nil and according to the [docs](https://godoc.org/github.com/go-xorm/xorm#Engine.Update) only bean's non-empty fields contents are updated.
```
UPDATE
 `alert` SET `org_id` = 1,
 `dashboard_id` = 41,
 `panel_id` = 4,
 `name` = 'TestData - Always Alerting 20358',
 `message` = '', `state` = 'alerting',
 `handler` = 1,
 `frequency` = 60,
 `for` = 0, 
 `eval_data` = NULL,
 `updated` = '2019-11-15 20:32:58',
 `settings` = '{\"alertRuleTags\":{},\"conditions\":[{\"evaluator\":{\"params\":[160],\"type\":\"gt\"},\"query\":{\"datasourceId\":4,\"model\":{\"refId\":\"A\",\"scenario\":\"random_walk\",\"scenarioId\":\"csv_metric_values\",\"stringInput\":\"200,445,100,150,200,220,190\",\"target\":\"\"},\"params\":[\"A\",\"5m\",\"now\"]},\"reducer\":{\"params\":[],\"type\":\"avg\"},\"type\":\"query\"}],\"enabled\":true,\"executionErrorState\":\"alerting\",\"for\":\"0m\",\"frequency\":\"60s\",\"handler\":1,\"name\":\"TestData - Always Alerting 20358\",\"noDataState\":\"no_data\",\"notifications\":[]}'
```
A quick workaround would be to copy also the `EvalData` as it happens with the `State` field.

**Comment by marefr** [comment] 2019-11-16 01:06
@papagian this sounds like it works as intended since we want the eval data to clear when saving the dashboard/alert rules so that the alert rule is re-evaluated. This is my idea of why it's implemented this way at least.

**Comment by papagian** [comment] 2019-11-18 08:40
@marefr I was thinking also that is was intentional. So should we close it?

**Comment by manitua** [comment] 2019-11-18 09:26
When is re-evaluation occurring? As it is not happening (Only when both metrics,in my example, are below threshold, as in OK, then it is re-evaluated to `{}`)

I assumed :) that it will, as the alert has "Send reminders" set on, be re-evaluated after evaluation-period.

**Comment by marefr** [comment] 2019-11-18 09:50
@manitua 

> When is re-evaluation occurring?

After you've changed the threshold and saved the dashboard. 

If you mean that this is happening without saving dashboard it sounds like a bug.

@papagian yes we should close this since it works as intended.

**Comment by manitua** [comment] 2019-11-18 10:26
@marefr When threshold is changed and dashboard saved, the column `eval_data` is still empty. It is only populating `eval_data` column when I move threshold, in my particular case, above so that no metrics are "alerting" and save the dashboard.

**Comment by marefr** [comment] 2019-12-03 13:28
Closing this as it works as intended.

**Closed by marefr** 2019-12-03 13:28 UTC
Labels: area/alerting, area/alerting/evaluation, type/bug
