### ISSUE TITLE
Kiosk url param doesn't work when page redirected for custom home dashboard

### ISSUE THREAD

**Issue by mixmastamyk** [grafana/grafana#11833] opened 2018-05-04 17:26 UTC
Please include this information:
### What Grafana version are you using? 
5.1
### What OS are you running grafana on? 
Ubuntu 18.04
### What did you do?
Set starred dashboard as Home Dashboard then put ?kiosk at end of URL

### What was the expected result?

Kiosk mode (should hide side menu, top bar, the title, buttons, and time frame header.)

### What happened instead?  

No kiosk mode - I noticed that when I add '?kiosk' to the end of the current url it works.  However if I put the site in manually: `http://localhost/?kiosk` it doesn't.  Or make a startup script on and use as the command-line:

```bash
$ firefox "http://localhost/?kiosk"
```

It doesn't work because the url gets redirected to the home dashboard, and when that happens the kiosk parameter is not recognized.  (Though it is still there.) The page needs to be manually refreshed, and then it works. :-/

Means I can't automate sending a simple url to Firefox in a startup script.

Workaround: use full dashboard url so it doesn't redirect.

**Comment by daniellee** [comment] 2018-05-05 23:13
Just did a quick test on Firefox and Chrome and it worked for me. And by works for me, I mean that the sidebar disappears. Can you provide more details about how the kiosk mode is not working.

![image](https://user-images.githubusercontent.com/434655/39668311-9a4b10f0-50ca-11e8-8031-6600ba773d71.png)

**Comment by mixmastamyk** [comment] 2018-05-05 23:32
Hi, kiosk mode removes the top bar as well, the title, buttons, and time frame header.

You don't see it in your screen shot because your home dashboard has not been set to a real dashboard.

**Comment by daniellee** [comment] 2018-05-07 12:39
@mixmastamyk Thanks for adding the extra info needed to reproduce this issue.

**Comment by kaydelaney** [comment] 2020-11-11 14:41
Closing as this is fixed in master

**Closed by kaydelaney** 2020-11-11 14:41 UTC
Labels: area/dashboard, help wanted, type/bug
