### ISSUE TITLE
Alerting: Setting Up Multi Dimensional Alerts with Graphite Gives Error - Frame Cannot Uniquely be Identified by its Labels {}

### ISSUE THREAD

**Issue by lenilsamuel** [grafana/grafana#70033] opened 2023-06-13 21:11 UTC
### 
# What went wrong?

**What happened**:

  - Trying to create a multidimensional alert in Grafana using Graphite as the data source. I can get the alert to work fine for a single series, but not for multiple series.

Here are the results of the Graphite query. I’m aliasing them using aliasByNode to alias the metric by its unique id
![Screen Shot 2023-06-13 at 8 28 13 AM](https://github.com/grafana/grafana/assets/90015211/6098356e-b6b8-4636-adf9-939e2830e97a)

However in the ‘B’ expression when I reduce each series, they’re just labeled as series 0, series 1, series 2 and so on. I can see it grabs the right value for each series, but I would expect the series to be labeled by whatever I’m aliasing it with

If I save this alert rule and get it to fire, I get an error saying - `invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}`

**What did you expect to happen**:

  - I'd have expected each series to be properly labeled based on how I'm aliasing them, but that's not the case. This then breaks when the alert fires with the above error message
  - I found this issue previously reported [here](https://github.com/grafana/grafana/issues/45721). The suggestion was to re-open the issue if someone encounters the same problem that cannot be solved by using the Reduce expression

### 
# How do we reproduce it?

**Step 1**:

- Set up an alert rule that returns multiple series
- All the series are labeled series 0, series 1, and so on. The labels aren't properly applied even though I'm aliasing them

### 
# What Grafana version are you using?

v9.4.3

### 
### Grafana Platform?

None

### User's OS?

macOS Monterey 12.2.1

### User's Browser?

Google Chrome

**Comment by lenilsamuel** [comment] 2023-06-14 22:57
I tested this out with a different Graphite data source and I'm no longer encountering the issue. The data that is returned from the new data source has a `tags` key and so is able to properly label each series. My data source, however, does not have the `tags` key. Is this something that can be fixed?

**Comment by gillesdemey** [comment] 2023-06-20 10:05
carbonapi doesn't seem to support labels (I am unfamiliar with this one, so that's my assumption) and therefore is not compatible with Grafana Alerting. 

We recommend using the official Graphite 1.x DB and data source. 

A potential solution on our side to support data sources that don't have the concept of "tags" would be https://github.com/grafana/grafana/issues/65846

**Comment by armandgrillet** [comment] 2023-06-23 09:36
Closing due to being a duplicate of https://github.com/grafana/grafana/issues/65846

**Closed by armandgrillet** 2023-06-23 09:36 UTC
Labels: area/alerting
