### ISSUE TITLE
IOS compatibility problem

### ISSUE THREAD

**Issue by yening-zy** [grafana/grafana#18958] opened 2019-09-09 05:36 UTC
**What happened**:Pull more than three panes in dasboard, use Chrome on the iphone, click on editor or view on panel, and return to the dahboard page. such as table panel, singlestat or Heatmap will disappear and hand touch will appear again.
![1](https://user-images.githubusercontent.com/29893194/64505562-d34fd600-d306-11e9-865d-eb5be0ab6811.gif)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana 6.2.5:
- OS Grafana is installed on:
- User OS & Browser: IPhone chrome
- Grafana plugins: tabel，singlestat，heatmap
- Others:

**Comment by papagian** [comment] 2019-09-10 06:24
This is a duplicate of #18497.

**Closed by papagian** 2019-09-10 06:24 UTC
