### ISSUE TITLE
Table: max and min auto should be calculated for each column

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#29881] opened 2020-12-16 14:29 UTC
**What would you like to be added**:

Here, I've table with 2 columns, I want to visualize with gauges.
Latter one, doesn't display meaningful gauges. I'm guessing, it's because Grafana calculates the max value for whole table. 

![image](https://user-images.githubusercontent.com/43188411/102360550-32e56880-3fc3-11eb-86d9-c058168d2dbf.png)

First column is actually "seconds", so it's on a bigger scale. When I override max value, manually, for the last column, everything looks fine.

![image](https://user-images.githubusercontent.com/43188411/102361011-c9198e80-3fc3-11eb-8a36-4faf248e6d50.png)

This should be dynamic.

**Comment by hugohaggmark** [comment] 2020-12-17 05:45
Confirmed on Grafana v7.4.0-pre (7adccf1e67)

Dashboard gist is here (requires the Static Datasource Plugin by Marcus Olsson `marcusolsson-static-datasource`): [https://gist.github.com/hugohaggmark/d932ea958764c827e39493efcffdc16b](https://gist.github.com/hugohaggmark/d932ea958764c827e39493efcffdc16b)

**Comment by torkelo** [comment] 2021-06-19 05:26
duplicate of https://github.com/grafana/grafana/issues/26383

**Closed by torkelo** 2021-06-19 05:26 UTC
Labels: type/feature-request
