### ISSUE TITLE
About Variables of Templating some questions

### ISSUE THREAD

**Issue by hualidi123** [grafana/grafana#11327] opened 2018-03-21 09:45 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
4,6
### What datasource are you using?
zabbix
### What OS are you running grafana on?
centos 6.5
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
 
![image](https://user-images.githubusercontent.com/31085705/37702932-0d102194-2d2f-11e8-9725-4b271c558818.png)
like this,I want the drop down list to contain only the two items I want instead of all.can the grafana work?i can't unstand the Instructions.

**Comment by daniellee** [comment] 2018-03-21 10:31
Yes - you can use the regex field to filter values.

Here are some examples:

- https://community.grafana.com/t/is-it-possible-to-definie-variable-template-with-regex/1391
- https://community.grafana.com/t/using-regex-in-grafana-templating-how/859

The docs need to be improved and I will add some examples now to the [docs page](http://docs.grafana.org/reference/templating/#query-options) for Variables.

Closing this issue as it is a question and not a bug or feature request.

**Closed by daniellee** 2018-03-21 10:31 UTC
Labels: type: question

**Comment by hualidi123** [comment] 2018-03-22 00:58
thks
