### ISSUE TITLE
DataDog Query Panel incorrectly says "Sub by" as an aggregate function

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#26730] opened 2020-07-31 14:23 UTC
**What happened**:
Clicking the Datadog Aggregate drop down shows "sub by"

![image](https://user-images.githubusercontent.com/2272392/89043956-4e531e00-d317-11ea-8581-a1d7b4f1fbfd.png)

**What you expected to happen**:
It should say "sum by"

**How to reproduce it (as minimally and precisely as possible)**:
Click the Datadog Aggregate drop down.

**Anything else we need to know?**:
Nope.

**Environment**:
- Grafana version: Grafana v7.1.1 (3039f9c3bd)
- Data source type & version: "Datadog datasource for Grafana" version 1.5.0
- OS Grafana is installed on: Alpine docker image
- User OS & Browser: Ubuntu/Chrome
- Grafana plugins: DataDog
- Others:

**Comment by torkelo** [comment] 2020-08-04 06:00
duplicate of https://github.com/grafana/datadog-datasource/issues/110

**Closed by torkelo** 2020-08-04 06:00 UTC
