### ISSUE TITLE
Tilde (~) behaves like an escape character in query editor

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#39316] opened 2021-09-17 07:40 UTC
**What happened**:

Since Grafana 8 we can't use the `~` char normaly in the query editor

https://user-images.githubusercontent.com/153052/133743857-57c47425-0090-441d-bf37-9bfc1509439a.mov

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS Big Sur / Firedox 92
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment] 2021-09-17 12:51
closing this as duplicate of https://github.com/grafana/grafana/issues/34378

**Closed by Elfo404** 2021-09-17 12:51 UTC
