### ISSUE TITLE
[4.6.0] Can't change color in series overrides

### ISSUE THREAD

**Issue by haizaar** [grafana/grafana#9740] opened 2017-10-31 13:27 UTC
Grafana 4.6.0 from official docker image.
Prometheus 2.0 datasource

Situation:
* Create Graph panel
* Go to Display -> Series Overrides and then click "+" > Color > Change

Exepected:
Color picket should open.

Actual:
Empty popup is dislplayed like on the below screenshot:

![image](https://user-images.githubusercontent.com/58201/32225787-b7c688fc-be9a-11e7-9c8b-c0c27c92789d.png)

**Comment by torkelo** [comment] 2017-10-31 14:30
dupe of https://github.com/grafana/grafana/issues/9715 (and fixed)

**Closed by torkelo** 2017-10-31 14:30 UTC
