### ISSUE TITLE
Prometheus ad-hoc filter incorrectly modifies "by", "without" clauses

### ISSUE THREAD

**Issue by jstaffans** [grafana/grafana#16893] opened 2019-05-05 20:49 UTC
**What happened**:

Applying an ad-hoc filter, "by" and "without" clauses sometimes get mangled.

**What you expected to happen**:

Ad-hoc filter should not modify "by" and "without" clauses.

**How to reproduce it (as minimally and precisely as possible)**:

In the [Prometheus Console Tables example](https://play.grafana.org/d/000000065/prometheus-console-tables):

`up` query modified to include a by clause:

<img width="578" alt="Screenshot 2019-05-05 at 23 39 06" src="https://user-images.githubusercontent.com/1368965/57200093-c48b9800-6f8f-11e9-84a0-9ac01836106b.png">

The Prometheus query resulting from the above:

<img width="770" alt="Screenshot 2019-05-05 at 23 39 15" src="https://user-images.githubusercontent.com/1368965/57200105-f1d84600-6f8f-11e9-8efd-8e86cc7df3c5.png">

**Anything else we need to know?**:

Does not **always** happen. For example, the above query works if you change `by(instance)` to `without(job)`.

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: Prometheus 2.7.1
- User OS & Browser: Mac, Chrome 73

**Comment by mozai** [comment] 2019-07-05 15:07
Just ran into this today.  Grafana v5.4.4, Prometheus-type data source
```
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/13/api/v1/query_range?query=max%20by(rule_group%7Benvironment!%3D%22alpha%22%7D)((prometheus_rule_group_last_duration_seconds%7Benvironment!%3D%22alpha%22%7D%20%3E%2010)%20and%7Benvironment!%3D%22alpha%22%7D%20(increase(prometheus_rule_group_last_evaluation_timestamp_seconds%7Benvironment!%3D%22alpha%22%7D%5B2m%5D)%20%3E%2060))&start=1561733400&end=1562338800&step=600"
response:Object
status:"error"
errorType:"bad_data"
error:"parse error at char 18: unexpected "{" in grouping opts, expected ")""
message:"parse error at char 18: unexpected "{" in grouping opts, expected ")""
```
`max by(rule_group{environment!="alpha"})((prometheus_rule_group_last_duration_seconds{environment!="alpha"} > 10) and{environment!="alpha"} (increase(prometheus_rule_group_last_evaluation_timestamp_seconds{environment!="alpha"}[2m]) > 60))`

inserted {blah!="blah"} in two differently incorrect places.

**Comment by jstaffans** [comment] 2019-11-20 13:06
See also #19008, probably the same root cause.

**Comment by aocenas** [comment] 2020-07-22 08:37
This seems like a duplicate of https://github.com/grafana/grafana/issues/16893

**Closed by aocenas** 2020-07-22 08:37 UTC
Labels: area/dashboard/templating, datasource/Prometheus, type/bug

**Comment by mozai** [comment] 2020-07-22 15:13
Did you just close this bug #16893 because it's a duplicate of bug #16893 ?  A duplicate of itself???

**Comment by aocenas** [comment] 2020-07-23 09:20
Haha yeah wrong link, thanks for pointing that out.
