### ISSUE TITLE
[Feature request] Unit - Request per second

### ISSUE THREAD

**Issue by nutchalum** [grafana/grafana#9630] opened 2017-10-24 02:48 UTC
It'd be good to have a **req/s** in unit.
Currently I'm using **ops** (operation/sec) which is something similar to **req/s**.
But that's sound confusing when I'm reading the graph and see ops instead req/s.

Please considering about this.
I'd love to see them and hope for everybody too.

Thank you.

**Comment by torkelo** [comment] 2017-10-24 05:57
duplicate of https://github.com/grafana/grafana/issues/9401

**Comment by nutchalum** [comment] 2017-10-24 09:20
I've read #9401 and I think it's not duplicate.

I just want a unit that named **request/sec** or **req/s** in throughput group (or data rate, I don't know).
We have ops/s, read/s, write/s and I just want a request/s (or req/s), That's what I mean.

Many of us use Grafana to monitoring a load balancer which is why we need this.

Thank you.

**Comment by nutchalum** [comment] 2017-10-31 06:54
Is this still counted as closed?

@torkelo

**Comment by marefr** [comment] 2019-01-24 19:16
Fixed by #11694

**Closed by marefr** 2019-01-24 19:16 UTC
Labels: type: feature request
