### ISSUE TITLE
8.5 not running on Raspbian Buster

### ISSUE THREAD

**Issue by bloop16** [grafana/grafana#48288] opened 2022-04-26 15:28 UTC
Grafana 8.5 is not running on my Raspbian 10 Buster

```
● grafana-server.service - Grafana instance
   Loaded: loaded (/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-04-26 17:15:49 CEST; 1s ago
     Docs: http://docs.grafana.org
  Process: 12828 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.l
 Main PID: 12828 (code=exited, status=2)

Apr 26 17:15:49 Raspberry systemd[1]: grafana-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 26 17:15:49 Raspberry systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Apr 26 17:15:49 Raspberry systemd[1]: grafana-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 26 17:15:49 Raspberry systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Apr 26 17:15:49 Raspberry systemd[1]: Stopped Grafana instance.
Apr 26 17:15:49 Raspberry systemd[1]: grafana-server.service: Start request repeated too quickly.
Apr 26 17:15:49 Raspberry systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Apr 26 17:15:49 Raspberry systemd[1]: Failed to start Grafana instance.

```
And the Log File:

```
logger=context t=2022-04-26T15:41:44.98+0200 lvl=eror msg="Request Completed" method=GET path=/api/datasources/proxy/3/query status=502 remote_addr=192.168.0.156 time_ms=104 size=0 referer="http://192.168.0.110:3000/d/p5iyiQWgk/cpu?orgId=1&kiosk&refresh=500ms"
logger=context t=2022-04-26T15:41:44.99+0200 lvl=eror msg="Failed to look up user based on cookie" error="context canceled"
logger=context t=2022-04-26T15:41:45+0200 lvl=eror msg="Failed to look up user based on cookie" error="context canceled"
logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/3/query remote_addr=192.168.0.156 referer="http://192.168.0.110:3000/d/p5iyiQWgk/cpu?orgId=1&kiosk&refresh=500ms" t=2022-04-26T15:41:45+0200 lvl=eror msg="Data proxy error" error="http: proxy error: context canceled"
logger=context t=2022-04-26T15:41:45+0200 lvl=eror msg="Request Completed" method=GET path=/api/datasources/proxy/3/query status=502 remote_addr=192.168.0.156 time_ms=124 size=0 referer="http://192.168.0.110:3000/d/p5iyiQWgk/cpu?orgId=1&kiosk&refresh=500ms"
logger=server t=2022-04-26T16:05:52.24+0200 lvl=info msg="Shutdown started" reason="System signal: terminated"
logger=tracing t=2022-04-26T16:05:52.25+0200 lvl=info msg="Closing tracing"
logger=ngalert t=2022-04-26T16:05:52.25+0200 lvl=eror msg="unable to fetch orgIds" msg="context canceled"
```

After downgrading back to 8.4.7 everything works fine.

**Comment by kristofejro** [comment] 2022-04-26 16:16
See this:
https://github.com/grafana/grafana/issues/48130

**Comment by mellieA** [comment] 2022-04-26 17:16
Closing this as a duplicate of #48130

**Closed by mellieA** 2022-04-26 17:16 UTC
