### ISSUE TITLE
[Bug] Menu broken in mobile and desktop Safari on small screens

### ISSUE THREAD

**Issue by antiquechrono** [grafana/grafana#11072] opened 2018-03-03 09:41 UTC
- What Grafana version are you using?
5.0

- What OS are you running grafana on?
IOS/OSX

- What did you do?
Open the left menu on IOS or a small window in desktop safari. This is the the version with the hamburger menu.

- What was the expected result?
The menu would work like normal

- What happened instead?
The menu is permanently locked to the bottom of the screen and cannot be scrolled so that you can't ever navigate back to any dashboards.

<img width="330" alt="screen shot 2018-03-03 at 3 35 39 am" src="https://user-images.githubusercontent.com/572187/36932809-a2e89b8c-1e94-11e8-95b6-372a627880b8.png">

**Comment by torkelo** [comment] 2018-03-03 13:11
thanks for reporting this

**Comment by Ijin08** [comment] 2018-03-05 14:49
Hi,

I can't reproduce this. I don't have this issue in iOS or OSX.
What version of iOS/OSX are you using?

**Comment by antiquechrono** [comment] 2018-03-05 20:59
Sorry I should have put this in the original post.

macOS Sierra - 10.12.6
Desktop Safari Version 10.1.2 (12603.3.8)
IOS 10.3.2 - Safari 10

Also interesting but if I go to play.grafana.org it works but If I go to our private grafana I get this behavior.

**Comment by antiquechrono** [comment] 2018-03-05 21:29
Okay so I was playing around and if I turn off the following the menu starts scrolling and rendering properly on IOS and macOS. I wonder if this is a bug in Safari 10.

From the sidemenu element
display: -webkit-box;
display: flex;

**Comment by antiquechrono** [comment] 2018-03-05 22:08
I just found someone on iOS 11.2.6 and the menu works as expected there so it's very likely this is a bug in Safari 10.

**Comment by daniellee** [comment] 2018-04-12 13:17
Closing this as I think this should be fixed by #11456 but I can reopen if this is still an issue.

**Closed by daniellee** 2018-04-12 13:17 UTC
Labels: type: bug

**Comment by antiquechrono** [comment] 2018-07-12 23:06
Just letting you know this is still broken on Safari 10. I'm assuming it won't be fixed considering it's nearly 2 years old at this point.
