### ISSUE TITLE
Search: access behaviour is inconsistent

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#24089] opened 2020-04-30 10:55 UTC
Version "Grafana v7.1.0-b8976df5pre (55ac97dccc)", clicking on home no longer offers the dashboard dropdown...

![fz9iQ5gC9Y](https://user-images.githubusercontent.com/444037/80702713-67aabb00-8ad9-11ea-8d1b-3bdc1633faa3.gif)

**Comment by dprokop** [comment] 2020-04-30 11:09
@tomwilkie this is not a bug but a UX change that we have introduced. Search is no longer available via header. **It's now in the main menu of the application (magnifying glass icon)** 

Is this change something that radically breaks your workflow, or just muscle memory?

cc @sarlinska

**Comment by tomwilkie** [comment] 2020-04-30 11:13
Oh sorry, I didn't realise!

I literally couldn't find out how to get to the list of dashboards - it felt like a bug to me.

Given the dashboard list is still accessible by clicking the header on a dashboard, this also feel inconsistent to me.

**Comment by dprokop** [comment] 2020-04-30 11:20
Yeah, it's only available when you click on the folder name, then the search is scoped to the current folder by default

**Comment by torkelo** [comment] 2020-04-30 11:20
> Given the dashboard list is still accessible by clicking the header on a dashboard, this also feel inconsistent to me.

No it’s not. This is what we have changed :) a bit UX issue that a lot people complained about for years (that you had to click dashboard name to open search).

But will be a painful transition for users who are accustomed to that previous strange behavior (me included). This was a changed that was pushed for by @davkal and the rest of the UX team

**Comment by dprokop** [comment] 2020-04-30 11:21
@torkelo -> it is, when we display the folder name

**Comment by torkelo** [comment] 2020-04-30 11:24
Yes, when clicking a folder name that is still there to filter search by folder.

**Comment by davkal** [comment] 2020-04-30 11:36
I wouldn’t say we pushed for it, but rather highlighted again how the current search had discovery issues. If we wanted to tackle it, a major release like 7.0 would be a great opportunity. But the change is clearly too big to be done without testing it a bit first, especially with expert users, then we would have found this sooner. From the UX team’s point of view, I’d say that the implementation was rushed, which in crunch time is understandable. Luckily we’re still in beta and have a chance to remedy it. 
My immediate suggestion would be to keep the old behavior and add the new side bar icon, to have 2 entry points. Then we can do a bit more testing and suggest a more nuanced design.

**Comment by torkelo** [comment] 2020-05-01 14:35
> My immediate suggestion would be to keep the old behavior and add the new side bar icon, to have 2 entry points. 

Already fixed and merged :)

**Closed** 2020-05-04 10:51 UTC
Labels: type/bug, type/ux
