### ISSUE TITLE
Alerting still exists after the dashboard was deleted

### ISSUE THREAD

**Issue by pdu** [grafana/grafana#10037] opened 2017-11-30 11:40 UTC
I've configured a wrong alert rule in the dashboard, and it triggered alert, then I deleted the dashboard, but the alert was still there and state was alerting.

I've used some script to create more than 200 dashboards at the same time, after I found the false alerts, I deleted all the dashboards.

**Comment by bergquist** [comment] 2017-11-30 15:26
Can you still see the alert on `/alerting/list` ? 

What kind of database are you using for storing dashboards?

All alerts should be deleted when a dashboard is deleted. 
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/dashboard.go#L274
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/alert.go#L130

**Comment by pdu** [comment] 2017-12-01 01:34
@bergquist 
1. I can still see all the alerts in the /alerting/list, I've to pause all the alerts
2. I use SQLite as the backend storage
3. During that time, the server is very busy and I've done the following things:
3.1. I called the get dashboards API to get the dashboard list filtering by one special tag
3.2. Then I called the delete dashboard API one by one for over 200 dashboards, some of them returned failure
3.3. I repeated steps 3.1/3.2 until I've deleted all the dashboards
3.4. And the server was very CPU busy, so I restarted Grafana several times during that period

I suppose the server was very CPU busy and it affected the SQLite performance, so some of the queries got failed. But the whole process of executing the queries is not in a transaction, so the issue was caused

FYI, why the server CPU was very busy, because:
1. I've configured to include images in the alerts
2. While I configured wrong alert rules which triggered more than 200 alerts in a very short period, the phantomjs processes which were used to crop the images consumed almost all the CPUs

Before I configured massive dashboards to Grafana, I just have less than 10 dashboards in Grafana and everything works great. But sometimes I received the alerts with outdated images and the "alert rules" link in the email directed to a time range several days ago

Anyway, it's a very good experience to include images in the alerts, but I have to turn off the function to save CPU usage.

**Comment by bergquist** [comment] 2017-12-01 10:02
If you intend to run that many alerts I **strongly** recommend using mysql/postgre instead of sqlite. 

Starting a new phantomjs process for every alert notification is CPU intensive. We will look into replacing it with chromes headless browser and also make it possible to send a request to another service to render the image. But both of those require support for backend plugins. https://github.com/grafana/grafana/issues/6841

**Comment by pdu** [comment] 2017-12-01 16:26
@bergquist Thanks! We will definitely switch to use mysql instead of sqlite. Do you think it still needs the transaction even with mysql/postgre?

By the way, another issue we have found is: while the alert was deleted but there's still an ongoing pagerduty alert, I think it's better to resolve the pagerduty alert also.

**Comment by torkelo** [comment] 2018-04-12 06:41
closing this as we have no other reports of the same thing happening and no idea what happened (other than sqlite3 being overloaded)

**Closed by torkelo** 2018-04-12 06:41 UTC
Labels: state: needs more detail

**Comment by kjetilmjos** [comment] 2018-10-18 08:56
I'm experiencing the same issue with alerts not getting deleted. I deleted a dashboard with defined alerts but they continue to trigger. When running /api/alerts I can not see the deleted alarms and they are not visible in the active alarm list but they are visible in the alert history.

**Comment by SteffenWG** [comment] 2018-10-19 15:06
kjetilmjos is helping me. I have some more info. I use  DB Browser for SQLite to read the grafana.db file. In it I'm able to find the alerts that should have been deleted when deleting the dashboards containing the alerts. I try to find the dashboards that the alerts is registered with through the api. The message is : not found. So the Dashboards is confirmed deleted. Anyone with any ideas what has gon wrong? Now, is it safe to delete the records in the grafana.db file? Or will that corrupt it some how?

**Comment by madmax01** [comment] 2020-01-01 18:02
this issue is still with latest grafana.  so it's known since 2017.  any Process on this please?  as Alerts are rather sensless if Alerts preserved once re/configured etc,...

**Comment by vlizanae** [comment] 2020-11-26 18:43
Having the same issue, please reopen.

**Comment by smehta12** [comment] 2020-12-11 16:08
Same issue here too. Removed the notification channel as well as the notification from the Panel’s alert manager.

**Comment by kvz** [comment] 2021-01-14 07:51
Ran into the same. There was an alert active when the dashboard was provisioned and now it keeps alerting us, with no UI to change it.

**Comment by kathy-lee** [comment] 2022-01-05 08:10
Almost the same issue here. I use the latest unified alerting in Grafana 8.3.x, once I created two Grafana alerts for one dashboard, then deleted this dashboard and those two alerts, but now every time when I use docker compose to set up Grafana, those two alerts always get triggered with "No Data" alerting.

**Comment by torkelo** [comment] 2022-01-05 09:43
@kathy-lee Go go alert rule list and delete them? the link between alert rules and dashboards in unified alerting is more an information link so you have delete both

**Comment by kathy-lee** [comment] 2022-01-05 15:01
@torkelo Thanks for your reply! I can confirm I deleted both in dashboard and alert rule list. I went into Grafana database also and checked all tables related to alert, and did not find anything related:
```sqlite> select * from alert_configuration;
sqlite> select * from alert_notification;
1|1|notification-channel-1|slack|{"recipient":"XXX","token":"xoxb-***","uploadImage":true,"url":"https://hooks.slack.com/services/*****"}|2022-01-05 11:17:00|2022-01-05 11:17:00|1|3600000000000|1|0|notifier1|{"token":"****","url":"****"}
sqlite> select * from alert_rule;
sqlite> select * from alert_tag;
Error: no such table: alert_tag
sqlite> select * from alert_rule_tag;
sqlite> select * from alert_rule_version;
sqlite> select * from alert_instance;
sqlite> select * from cache_data;
sqlite> select * from dashboard_provisioning;
```

when I click the alert message link, I got redirected to this address: "http://localhost:3000/d/kAZxXUt7z/talent-log-dashboard-for-demo?tab=alert&viewPanel=4&orgId=1", in this address I can see the name of the deleted dashboard (talent-log-dashboard-for-demo). I don't know where this alert come from.

**Comment by mehak-sha** [comment] 2023-07-20 22:56
I am also facing the same issue with Grafana v9.3.0. The alert is still getting triggered after deleting the alert rule and when I click on the alert rule link, it shows "rule could not be found". I see no entries in grafana DB. Please help.

**Comment by JarEXE** [comment] 2023-07-22 18:04
Still experiencing the same issue with a deleted alert in Grafana v10.0.2. 

I am constantly receiving the same email regarding the initial alert every few hours, even after deleting the alert and its respective folder. 

I will attempt adding a silence rule for the alert based on its old labels and hope that helps.

**Comment by mehak-sha** [comment] 2023-07-26 14:40
I added the silence rule as well and I am still getting notifications on slack. 
Is the rule stored somewhere is local disk as well? Can somebody please re-open this issue as the unnecessary alerts keep on getting generated.

**Comment by bergquist** [comment] 2023-08-01 11:28
Grafanas new alerting feature does not depend on dashboards anymore. I suggest you migrate to that instead since the previous alerting functionally wont get any fixes.
