### ISSUE TITLE
V6 Authentication can expire session before client is updated

### ISSUE THREAD

**Issue by briangann** [grafana/grafana#16757] opened 2019-04-25 05:30 UTC
**What happened**:

Kiosk user session automatically logs out on auto-refresh

**What you expected to happen**:

Kiosk user stays logged in for max duration (30 days default)

**How to reproduce it (as minimally and precisely as possible)**:

This is an edge case that is hard to reproduce. A client logged in can have its cookie/auth rotated but not receive the new session.

**Environment**:
- Grafana version:
6.1.3

- Data source type & version:

Any datasource, problem reported with a Zabbix datasource.  Test datasource can also do this as long as the dashboard has an auto-refresh.

- OS Grafana is installed on:

linux/docker

- User OS & Browser:

linux/chrome

DETAILS:

This edge case occurs when the auth_token is rotated but the client does not receive the updated token.

Looks like it can happen at https://github.com/grafana/grafana/blob/67cbc7d4cf135c3ed2fa5a47278c6be6e7653e7f/pkg/middleware/middleware.go#L193

the function TryRotateToken can succeed, updating the database with the new token, but fail to send the new session cookie at line 200

There should be error handling to detect when WriteSessionCookie fails, and to roll back the auth token to previous so it can be refreshed again by the client.

When this happens, the client reconnects with the old token, and is logged out since it is no longer valid.

**Comment by torkelo** [comment] 2019-04-25 07:39
What error can WriteSessionCookie encounter?

**Comment by torkelo** [comment] 2019-04-25 07:40
Maybe should add some error handling / logging there, can SetCookie fail?

**Comment by marefr** [comment] 2019-04-25 09:11
`http.SetCookie` doesn't return any error so "can't fail" that way. @briangann are you meaning that the response still fails to include the written cookie?

**Comment by marefr** [comment] 2019-04-25 09:15
Guess this is a duplicate of #15316?

**Comment by marefr** [comment] 2019-04-25 09:22
Hmm I think that this code could be problematic. The idea is to not allow the proxied response to set cookies but could probably remove Grafana set-cookie here?

https://github.com/grafana/grafana/blob/25ea5fcaf2dc7dbf341d7c905b0a31dbd8277cbd/pkg/api/pluginproxy/ds_proxy.go#L105

**Comment by briangann** [comment] 2019-04-26 04:00
> `http.SetCookie` doesn't return any error so "can't fail" that way. @briangann are you meaning that the response still fails to include the written cookie?

It looks like the response never reaches the client, and the cookie that stays on the client is no longer valid.

The bug does appear similar to #15316 

Looking at the lifecycle of the auth_token made this area looks like a possible failure point.

**Closed** 2019-05-01 14:32 UTC
Labels: area/backend/auth, type/bug

**Comment by mirronelli** [comment] 2019-06-30 20:21
I still have this problem in 6.2.5. The session cookie gets set to empty value after a few minutes. Thus forcing a logout. I can provide you with browser logs as well as server logs if needed. I don't see any regularity in this. Sometimes the session lasts for more than 10 minutes, sometimes it only lasts as few as 3 minutes. I have already changed the short lived token timeout to 300 minutes but that didn't help.

**Comment by marefr** [comment] 2019-07-01 06:53
@mirronelli please refer to #16638 for further discussions.

**Comment by r3econ** [comment] 2021-11-08 13:03
I have the same problem. When will there be a fix? I'm on v8.2.2
