### ISSUE TITLE
Alerts Won't Process

### ISSUE THREAD

**Issue by RamboRogers** [grafana/grafana#24882] opened 2020-05-19 16:49 UTC
**What happened**:
Alarms don't work on imported dashboard, strange error.
**What you expected to happen**:
Alarms to work as previous release
**How to reproduce it (as minimally and precisely as possible)**:
Import Grafana 6.0 dashboard with alerts into 7.0. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.0 (aee1438ff2)
- Data source type & version: Prometheus 2.17.2
- OS Grafana is installed on: Docker Container from Grafana
- User OS & Browser: OS X Safari
- Grafana plugins: PIE Chart
- Others:

<img width="724" alt="Screen Shot 2020-05-19 at 11 57 10 AM" src="https://user-images.githubusercontent.com/7763805/82354605-06d31c00-99cf-11ea-8940-24ec17b52a6c.png">

<img width="530" alt="Screen Shot 2020-05-19 at 12 48 45 PM" src="https://user-images.githubusercontent.com/7763805/82354669-1eaaa000-99cf-11ea-8e88-f328dba5934f.png">

**Comment by marefr** [comment] 2020-05-19 21:11
Sorry you have to navigate to dashboard after import and save the dashboard for the alert rules to be saved.

**Comment by marefr** [comment] 2020-05-19 21:11
Duplicate of #11419

**Closed by marefr** 2020-05-19 21:11 UTC

**Comment by RamboRogers** [comment] 2020-05-19 23:27
That's not true, I've resaved and made new alerts and they still don't work.

**Comment by RamboRogers** [comment] 2020-05-19 23:32
**"tsdb.HandleRequest() error parse "192.168.1.11:9090": first path segment in URL cannot contain colon"**

**Comment by RamboRogers** [comment] 2020-05-19 23:32
I can't make new alerts either.

**Comment by RamboRogers** [comment] 2020-05-19 23:38
SO I FIGURED THIS OUT.  My prometheus data source didn't have an HTTP:// in front of it.  Once I added it, the alerts worked.  So this is the fix for whoever finds this post in the future, since it was wrongly closed to another problem.

**Comment by chippey5** [comment] 2020-09-23 01:52
Thanks for reporting back @RamboRogers, I had the same issue with my setup and adding http:// to my influxdb datasource url fixed the issue. This is kind of self-explanatory that it's supposed to contain a http:// prefix because the field says **URL**, but the datasource connection test still works without the prefix, only the alerts seem to break.

Perhaps users should be forced to provide the http:// prefix when adding datasources, alternatively the alerts should handle addresses when a datasource is added without the prefix.

**Comment by tobiasfiechter** [comment] 2021-08-09 08:43
> SO I FIGURED THIS OUT. My prometheus data source didn't have an HTTP:// in front of it. Once I added it, the alerts worked. So this is the fix for whoever finds this post in the future, since it was wrongly closed to another problem.

Thanks for your tip! I had the same problem and by adding http:// it was resolved
