### ISSUE TITLE
"Ad hoc filters" is always empty

### ISSUE THREAD

**Issue by ThePerro** [grafana/grafana#32118] opened 2021-03-18 15:26 UTC
HELLO
What Grafana version are you using? Grafana v7.4.3
What datasource are you using? Elasticsearch
What OS are you running grafana on? Windows
What did you do?
Create ad hoc "filters" template from Variables settings(i've add the datasource before).
What was the expected result?
The filter should apply to the graph (as advertised).
What happened instead?
<img width="278" alt="Immagine 2021-03-18 160238" src="https://user-images.githubusercontent.com/78366066/111651677-bacb5080-8806-11eb-8c72-1438fcbbd0dd.png">

How can I get Grafana to show my filters?

**Comment by Elfo404** [comment] 2021-03-24 12:02
hi @ThePerro , thanks for reporting this. Unfortunately I'm not able to reproduce it.

Can you please provide us with a bit more information? 
What are the HTTP requests & response you see from the browser dev tools when you click?

**Comment by Elfo404** [comment] 2021-04-09 11:43
Closing this as no more info were provided, feel free to comment with more info and we can reopen this :)

**Closed by Elfo404** 2021-04-09 11:43 UTC
Labels: datasource/Elasticsearch, needs more info
