### ISSUE TITLE
Regex with variable not working in graph visualization

### ISSUE THREAD

**Issue by cuxcrider** [grafana/grafana#17158] opened 2019-05-19 17:47 UTC
**What happened**:  I have a variable $CellNames1.  My query is aliased as: Temp $CellNames1
In the visualization tab I am trying to plot this on the secondary y-axis using either the alias or a regex expression.  I can use /Temp/ as expected to plot on the second y-axis, but when I use /^Temp $CellNames1$/ the expression is not captured and it plots on the primary y-axis. 

**What you expected to happen**:  I expected the regex to understand the variable name and plot on the secondary y-axis

**How to reproduce it (as minimally and precisely as possible)**:  Create a variable and attempt to plot on the secondary y-axis using a regex expression that requires the variable name.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1.6, using a MySQL database for Grafana (not the standard SQLite, but I have tried SQLite initially with the same results as above.)
- Data source type & version: Influxdb V. 1.7.6
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Windows10, Chrome
- Grafana plugins: standard install
- Others:

**Comment by torkelo** [comment] 2019-05-20 07:02
dupe of this feature request https://github.com/grafana/grafana/issues/5398

**Closed by torkelo** 2019-05-20 07:02 UTC
