### ISSUE TITLE
Grafana tries to automatically connect to Jaeger while using Helm Charts

### ISSUE THREAD

**Issue by atropos112** [grafana/grafana#64650] opened 2023-03-11 07:41 UTC
**What happened**:
I had an install of grafana on my cluster. On that same namespace I installed Jaeger, note I did not in any way instruct grafana or jaeger to connect to eachother. And yet, grafana start crash looping with 

```
logger=settings t=2023-03-11T08:06:53.084719844Z level=warn msg="[Deprecated] the configuration setting 'tracing.jaeger' is deprecated, please use 'tracing.opentelemetry.jaeger' instead"
Error: ✗ cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://10.43.92.95:5775: strconv.ParseInt: parsing "udp://10.43.92.95:5775": invalid syntax
```

**What you expected to happen**:
I expected grafana not to interfere with ANY other applications on the cluster/namespace by default unless specifically instructed to do so, the default settings shouldn't be "if there is jaeger in this namespace hook it up", thats reckless.

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana and jaeger on the same namespace.

**Anything else we need to know?**:
I am very concerned by the fact that an application like Grafana starts to spontaneously break just because I installed something else, ideally I would have some network mesh to prevent this bs happening but frankly I have always had high expectations of Grafana and it surprised me that Grafana would even attempt such dodgy connection.

**Environment**:
- Grafana version: 9.3.8
- OS Grafana is installed on: Kubernetes / Ubuntu

**Comment by atropos112** [comment] 2023-03-11 08:11
A crapy workaround here is to set 
```
JAEGER_AGENT_PORT: ""
```
in the overrides within the grafana helm chart. Nevertheless I'd argue grafana using the kubernetes environment variables in such way by default is at best unintentionally harmful.

**Comment by usmangt** [comment] 2023-03-13 18:59
Hi @atropos112,

Thanks for opening this issue.

Did you deployed Grafana on your k8 cluster via HELM or using yaml files?

**Comment by atropos112** [comment] 2023-03-14 19:33
Hi,

Helm chart but the helm chart doesn't seem to take Jaeger env in via its templates.

**Comment by usmangt** [comment] 2023-03-20 18:02
Thank you v.much for your patience.

Based on your steps of reproduction, I was also able to reproduce it on my test machine. I installed both on the default namespace and then get the same problem.

grafana POD Logs:

```
vagrant@master-node:~$ kubectl logs grafana-5658d9db45-m7vfz
logger=settings t=2023-03-20T17:52:38.317508921Z level=info msg="Starting Grafana" version=9.4.3 commit=cf0a135595 branch=HEAD compiled=2023-03-02T20:28:42Z
logger=settings t=2023-03-20T17:52:38.318001147Z level=warn msg="\"sentry\" frontend logging provider is deprecated and will be removed in the next major version. Use \"grafana\" provider instead."
logger=settings t=2023-03-20T17:52:38.318046355Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-03-20T17:52:38.318060867Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-03-20T17:52:38.318070679Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana/"
logger=settings t=2023-03-20T17:52:38.318080144Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-03-20T17:52:38.318089399Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-03-20T17:52:38.318098757Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-03-20T17:52:38.318108575Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-03-20T17:52:38.318118321Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana/"
logger=settings t=2023-03-20T17:52:38.318127647Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-03-20T17:52:38.318136773Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-03-20T17:52:38.3181461Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-03-20T17:52:38.318155523Z level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_USER=admin"
logger=settings t=2023-03-20T17:52:38.318166342Z level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_PASSWORD=*********"
logger=settings t=2023-03-20T17:52:38.318175633Z level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-03-20T17:52:38.318185176Z level=info msg="Path Data" path=/var/lib/grafana/
logger=settings t=2023-03-20T17:52:38.31819443Z level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-03-20T17:52:38.3182036Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-03-20T17:52:38.318213048Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-03-20T17:52:38.318222629Z level=info msg="App mode production"
logger=settings t=2023-03-20T17:52:38.318236791Z level=warn msg="[Deprecated] the configuration setting 'tracing.jaeger' is deprecated, please use 'tracing.opentelemetry.jaeger' instead"
Error: ✗ cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://172.17.25.171:5775: strconv.ParseInt: parsing "udp://172.17.25.171:5775": invalid syntax
```




Environment:
```
vagrant@master-node:~$ helm list
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
grafana	default  	1       	2023-03-20 17:05:20.685952485 +0000 UTC	deployed	grafana-6.52.4	9.4.3      
jaeger 	default  	1       	2023-03-20 17:01:01.826997842 +0000 UTC	deployed	jaeger-0.69.1 	1.42.0   

```

Kubernetes running on VM version:

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

I will now forward this to our Engineering team so that can decide if this is really a grafana issue or need to be reported to:
[grafana/helm-charts](https://github.com/grafana/helm-charts) repo.

**Comment by sakjur** [comment] 2023-03-27 10:25
Duplicate of #58608, I'll refer to my answer from there: https://github.com/grafana/grafana/issues/58608#issuecomment-1335457597

**Closed by sakjur** 2023-03-27 10:25 UTC
Labels: type/bug, datasource/Jaeger, area/configuration

**Comment by taruna-rohilla** [comment] 2025-02-13 11:02
The issue is still there. I am using the latest Grafana version, it is trying to connect to Jaeger by default and therefore the Grafana pod is going in Crashloopbackoff state. I had to follow the workaround to set JAEGER_AGENT_PORT: ""
Then the pod came up running.
