### ISSUE TITLE
webhook: "<" recieved as unicode in alert notification 

### ISSUE THREAD

**Issue by freesinger** [grafana/grafana#67189] opened 2023-04-25 09:17 UTC
## What happened:

I use Grafana webhook to recieve alert when conditions satisfied. But recently I found some symbol in alert body send from Grafana turned into ASCII.

Like below:
Test alert sent via webhook,
![image](https://user-images.githubusercontent.com/20896930/234231831-1084fbb9-8f03-477b-a76e-78be22451871.png)

Actual body recieved:
{"receiver":"","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"TestAlert","group":"core","instance":"Grafana"},"annotations":{"description":"test \u003c 12%","summary":"Notification test"},"...}

## What you expected to happen:
< should not turned into ASCII code \u003c
## Environment:
- Grafana version:v9.2.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment] 2023-04-26 01:02
@freesinger I'm not sure if this is on the sending or client (webhook receiver side). Moving to the alerting team to comment on that.

**Comment by grobinson-grafana** [comment] 2023-04-26 09:12
Hi! I think this is working as intended, here is the explanation from [encoding/json](https://pkg.go.dev/encoding/json#Marshal):

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. So that the JSON will be safe to embed inside HTML <script> tags, the string is encoded using HTMLEscape, which replaces "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029". This replacement can be disabled when using an Encoder, by calling SetEscapeHTML(false).

**Closed by grobinson-grafana** 2023-04-26 09:12 UTC
Labels: area/alerting/notifications, triage/needs-confirmation
