### ISSUE TITLE
Datalinks : Regression: using URL from data source no longer working

### ISSUE THREAD

**Issue by ideasman69** [grafana/grafana#46817] opened 2022-03-22 02:26 UTC
**What happened**: Since upgrading from 8.3.4 to 8.4.4, data links using fields with URLs are no longer working. Grafana seems to be appending the URL from the data field to grafana's own URL (in this case, https://grafana):

![image](https://user-images.githubusercontent.com/19260137/159392492-1b088bd0-ccd3-4960-a7c0-d6713f6f37a3.png)

**What you expected to happen**: Up until this latest release, a data link with a URL would result in a clickable URL which would open in a new tab. Loading up my 8.3.4 instance shows that it used to work:

![image](https://user-images.githubusercontent.com/19260137/159394700-7f761ab0-59a5-42d1-82d2-67c8972b89e9.png)

Interestingly, if I edit the data link to contain the exact same URL, it appears to work:

![image](https://user-images.githubusercontent.com/19260137/159395461-00317fb2-5abe-4a39-abef-4fd71efb7d22.png)

**How to reproduce it (as minimally and precisely as possible)**:

- configure a data source that has URLs
- configure data links using the URL field

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: Microsoft SQL
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Windows 10 21H2 / Latest Edge Chromium

**Comment by ideasman69** [comment] 2022-03-22 20:37
That works great, thanks for the tip!

**Comment by ideasman69** [comment] 2022-03-23 00:29
Further to this - it seems to be effecting built in variables too.

using this at the end of my data links: `&${__url_time_range}`

The link in 8.3.4 appears as:
hxxps://grafana/d/dashboard?orgId=1&refresh=1m&**from=now-6h&to=now**

The link in 8.4.4 appears as:
hxxps://grafana/d/dashboard?orgId=1&refresh=1m&**from%3Dnow-6h%26to%3Dnow**
 
Using @w4rgrum's `:raw` tip fixes this one too

**Comment by societymartingale** [comment] 2022-03-29 16:51
This also affected me. Downgrading from 8.4.4 to 8.4.3 fixed the links, so it must have been introduced in 8.4.4.

**Comment by sylock** [comment] 2022-04-06 12:13
It also affects me. Thanks @w4rgrum for the workaround :raw

**Comment by baur** [comment] 2022-04-10 10:29
Same error after 8.4.3 -> 8.4.5
all datalinks not works

**Comment by ifrost** [comment] 2022-04-12 14:26
Duplicate of https://github.com/grafana/support-escalations/issues/2125

**Comment by sylock** [comment] 2022-04-13 08:17
> Duplicate of https://github.com/grafana/support-escalations/issues/2125

The link does not work for me (404).

**Comment by kaydelaney** [comment] 2022-04-14 09:21
I think the solution we're going to go with for now is to revert the change that introduced this regression (https://github.com/grafana/grafana/pull/46100), and encourage people to use the `percentencode` and `queryparam` formatters if needed.

**Closed** 2022-04-20 09:15 UTC
Labels: type/bug, needs investigation, area/dashboard/data-links, type/regression

**Comment by rivolity** [comment] 2023-06-19 14:33
You can resolve this problem by adding HTTPS before the value, just like that.

```
htt﻿﻿﻿﻿﻿ps://${__value.raw}﻿﻿
```
<img src="https://github.com/grafana/grafana/assets/39197760/60cd6626-a769-45ca-9e55-2768c07b5dd8" width="48">
