### ISSUE TITLE
User sign in email is case sensitive and won't let user login

### ISSUE THREAD

**Issue by nalberto** [grafana/grafana#13333] opened 2018-09-19 06:41 UTC
User email is case sensitive and won't let user login if they the email has different case than in DB.
This causes a lot of frustration. I would recommend to lowercase email before inserting in DB.

### What Grafana version are you using?
5.2
### What datasource are you using?
sqlite3
### What OS are you running grafana on?
Ubuntu 18.04

**Comment by torkelo** [comment] 2018-09-19 07:49
duplicate of https://github.com/grafana/grafana/issues/12549 

It's tricky to change this without breaking many installations. But I agree email login should be case insensitive.

**Closed by torkelo** 2018-09-19 07:49 UTC

**Comment by tonglil** [comment] 2018-09-19 18:36
I'm curious how this change could break existing installations (and vs how many installs are broken currently _because_ of this).
