### ISSUE TITLE
[Bug] Tag-defined dashboard links do not open in a new tab

### ISSUE THREAD

**Issue by macgyver603** [grafana/grafana#8769] opened 2017-07-03 22:57 UTC
Grafana 4.2.0
Using Safari 10.1 and Chrome 59.0.3071

I am using a tag to populate a list of links to other dashboards from the dashboard settings menu, but the links do not open in a new tab despite checking the `Open in a new tab` radial. This only seems to be a problem when linking to other dashboards using the tag search option. When adding URL links (even if it is the URL to another dashboard within the organization), the links open in new tabs as expected.

<img width="584" alt="dashboard_link" src="https://user-images.githubusercontent.com/11929901/27809806-e1c4e2e4-6007-11e7-92b0-09487c1bd8fa.png">

The links generated by this setting will not open a new tab, but adding the dashboard URLs in explicitly with the `link` type instead will work as expected

**Comment by sqwishy** [comment] 2018-12-14 18:42
Hi, it looks like this is duplicated by/a duplicate of #10425 and was fixed by 04b9752932.

**Closed** 2018-12-14 18:58 UTC
Labels: comp: dashboard, help wanted, type: bug
