### ISSUE TITLE
Product Area: 10.4.0 - prometheus metrics browser displays traceback

### ISSUE THREAD

**Issue by systemcrash** [grafana/grafana#84047] opened 2024-03-07 03:36 UTC
### What happened?

![Screenshot 2024-03-07 at 04 35 19](https://github.com/grafana/grafana/assets/647633/bf9dbe0f-992b-445e-82d2-3a472c935923)

```
TypeError: We.type is undefined

B@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:5893:9690
WithTheme(undefined)
div
u@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:6103:3847
div
v@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:43:26178
s@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:43:24305
94254/gt<@http://localhost:3000/public/build/4254.c5f4a5512b252e3a5796.js:103:6929
vn@http://localhost:3000/public/build/4254.c5f4a5512b252e3a5796.js:103:9262
o@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:1:194
r@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:194:122062
g@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:194:122571
div
div
div
Ps@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:292:25179
Sd@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:224:19387
Dc@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:292:29657
_f@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:292:29775
p@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:409:57
div
N@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:4439:820
div
wf@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:292:30071
Sd@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:224:19387
O@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:224:17087
Fh@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:292:12797
lt@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:234:961
Ms@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:292:14558
g@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:4440:6028
div
div
div
div
div
fe@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:299:4635
u@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:194:29815
j@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:4445:56
Ln@http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:113:318
div
s@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:286:58224
div
24669/gt<@http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:113:1758
div
div
o@http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:2300
div
o@http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:4288
N@http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:9622
div
o@http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:2300
div
o@http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:4288
N@http://localhost:3000/public/build/660.838743295c2108f3492d.js:1:9622
div
div
div
L@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:357:21098
Bn@http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:130:526
at@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:412:32691
WithTheme(Connect(Bn))
yt@http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:205:472
DashboardPage
at@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:412:32691
ms@http://localhost:3000/public/build/DashboardPageProxy.9a6d60e5cac89c11c71c.js:205:6297
Suspense
r@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:194:122062
Ru@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:5705:9531
I@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:444:29242
di@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:435:4481
ni@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:435:12022
ht@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:444:17401
I@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:444:31410
div
div
main
div
Xf@http://localhost:3000/public/build/5017.830b14490d17e9cbdabb.js:5705:2385
di@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:435:4481
ni@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:435:12022
cr@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:435:11439
Hn@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:444:17692
I@http://localhost:3000/public/build/3644.93bade7d48e3d75173f7.js:444:25474
```

### What did you expect to happen?

normal Prometheus equation display

### Did this work before?

10.3.4 it's fine

### How do we reproduce it?

upgrade to 10.4.0 and use a Prometheus based panel or explorer

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: 10.4.0
OS:
Browser:

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by systemcrash** [comment] 2024-03-07 13:22
I've reviewed issue #82873 and see striking similarities. 

I've cleared my local browser cache, run Prometheus 2.50.1 (this also did not occur on Prom 2.50.0 for me), and everything is fine in 10.3.4. 

Weird.

**Comment by itsmylife** [comment] 2024-03-12 11:13
Duplicate of https://github.com/grafana/grafana/issues/82873

Could you please use Prometheus `v2.50.1` and clear the browser cache and try again? This should solve the issue.

**Closed by itsmylife** 2024-03-12 11:13 UTC
Labels: type/bug, datasource/Prometheus
