### ISSUE TITLE
[BUG]Colouring rule mismatch

### ISSUE THREAD

**Issue by LaszloGaal** [grafana/grafana#6642] opened 2016-11-19 18:28 UTC
* **I'm submitting a Bug report**

- Grafana version: 3.1.1 (+Google Chrome browser)
- Datasource: InfluxDB 1.1.0
- OS: MacOS 10.12.1
- What did you do: I've set the value colouring thresholds and enabled the Gauge in a Singlestat
- What was the expected result: Singlestat value and gauge have the same colour
- What happened instead? The colouring threshold boundaries are inclusive for the number colour but it is not in case of the Gauge colour.

![screen_shot_2016-11-19_at_18_43_16](https://cloud.githubusercontent.com/assets/23583821/20465406/b2f3d4b8-af5c-11e6-939c-eee980dd878d.png)
![screen_shot_2016-11-19_at_18_43_39](https://cloud.githubusercontent.com/assets/23583821/20465407/b670be6c-af5c-11e6-8c31-ac20e8a4ffdd.png)

**Comment by torkelo** [comment] 2016-11-21 08:29
dupe of https://github.com/grafana/grafana/issues/5515

**Closed by torkelo** 2016-11-21 08:29 UTC
