### ISSUE TITLE
Issues After Upgrading to grafana 7 - MS SQL data souce does not works on hostname\instance

### ISSUE THREAD

**Issue by siddhartha24** [grafana/grafana#25310] opened 2020-06-03 07:25 UTC
What happened : After upgrading to grafana 7, cannot add new "Microsoft SQL Server" data Source on hostname\instance.

What you expected to happen : MS SQL Data Source can be added on hostname\instance.

How to reproduce it (as minimally and precisely as possible) : Use MS SQL Data Source and try to add hostname\instance in Host. 

Anything else we need to know? : The error thrown is "validation error, invalid URL hostname\\instance". Note that there are two (\) in the error message 

Environment :
- Grafana version: 7.0.1
- Data source type & version: Microsoft SQL Server
- OS Grafana is installed on: RHEL 7.7

**Comment by c-thiel** [comment] 2020-06-03 12:27
I can confirm this happening with Grafana 7.0.2 also in the Ubuntu Docker image.
Using the API returns a Code 400 with the exact message described above.

**Comment by marefr** [comment] 2020-06-04 08:41
Duplicate of #25067

**Closed by marefr** 2020-06-04 08:41 UTC
Labels: datasource/MSSQL, needs investigation
