### ISSUE TITLE
[Feat Req] Autocomplete query term field and its values for elasticsearch

### ISSUE THREAD

**Issue by jiming** [grafana/grafana#5608] opened 2016-07-19 02:56 UTC
- **I'm submitting a ...**
- [X ] Feature request

Please include this information:
- What Grafana version are you using?  
  3.1.0
- What datasource are you using?  
  elasticsearch 2.3.3
- What OS are you running grafana on? 
  windows 7
- What did you do?  
  metrics display
- What was the expected result?  
  the query part can add a rows for term auto complete both field name and its available values (by using aggregation)
  I cannot upload image file, so please check the following url to see the the demo:

https://github.com/jiming/typo.css/blob/master/imgs/query_term_autocomplete.png

**Comment by aocenas** [comment] 2020-07-29 08:59
This seems like a duplicate of https://github.com/grafana/grafana/issues/3806

**Closed by aocenas** 2020-07-29 08:59 UTC
Labels: area/datasource, datasource/Elasticsearch, type/feature-request
