### ISSUE TITLE
Datasource as template

### ISSUE THREAD

**Issue by rvdwenden** [grafana/grafana#1384] opened 2015-01-25 10:02 UTC
We have for every DTAP (dev,test,accept,prod) environment a dedicated Graphite server and URL. The Graphite metrics trees are the same for every DTAP Graphite server.
Now we have to build/maintain 4 times a dashboard for each DTAP environment.
It should be nice to have one dashboard and to select an environment (i.e. datasource) by a template variable.

**Comment by torkelo** [comment] 2015-01-25 13:48
@rvdwenden yes, many have requested this feature. And it is in the works, just tricky to implement without introducing to much complexity, but will most likely be included in Grafana 2.0.

Dupe of https://github.com/grafana/grafana/issues/816 

The work has been going on this PR, https://github.com/grafana/grafana/pull/1055

**Closed by torkelo** 2015-01-25 13:48 UTC
