### ISSUE TITLE
Multi-value variable rendrered using __value instead of __text after selection changes

### ISSUE THREAD

**Issue by slasktrat** [grafana/grafana#26953] opened 2020-08-12 12:21 UTC
**What happened**:
I have a multi-value variable with __text and __value fields. When loading the dashboard the selected values are presented by the __text field. But if changing either the variable selection or time frame, the selected variable values are presented by the __value field. Tested using PostgreSQL and SimpleJSON data sources, same issue with both.

**What you expected to happen**:
The variable presentation in the dashboard should always reflect the __text field, also after changing selection.

**How to reproduce it (as minimally and precisely as possible)**:
Create a multi-value variable with query something like `select "name" as __text, "id" as __value from "myTable" order by "name"` 
(I use Refresh: "On Dashboard Load"), go back to the dashboard and toggle different values in the variable drop down.

**Environment**:
- Grafana version 7.1.3:
- Data source type & version: PostgreSQL (v12)
- OS Grafana is installed on: Debian 10
- User OS & Browser: Win10 + Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment] 2020-08-12 12:28
duplicate of https://github.com/grafana/grafana/issues/25959

**Closed by torkelo** 2020-08-12 12:28 UTC
