### ISSUE TITLE
    Data Source Error           Missing valid datasource id

### ISSUE THREAD

**Issue by isslower** [grafana/grafana#39115] opened 2021-09-13 05:54 UTC
![grafana_error](https://user-images.githubusercontent.com/45580748/133030438-39ff6551-ee32-4309-9d4d-755380242a05.png)

**What happened**:
First I installed it like this
`grafana-cli plugins install alexanderzobnin-zabbix-app`
After unable to link, I deleted it
`[root@prometheus plugins]# rm -rf alexanderzobnin-zabbix-app/`

Later, I downloaded and re-uploaded a version of 4.2.2 from the official website. After restarting the service, the error data source cannot be deleted
**Anything else we need to know?**:

**Environment**:
- Grafana version:  Grafana v7.2.1 (72a6c64532)
- Data source type & version: 
- OS Grafana is installed on: centos 7.8
- User OS & Browser: google 91.0.4472.124（正式版本） （64 位）
- Grafana plugins: zabbix  Version 4.2.2
- Others:

**Comment by ivanahuckova** [comment] 2021-09-17 15:05
I think this is duplicate of https://github.com/grafana/grafana/issues/37650. I am going to close it but feel free to correct me of I am wrong and we can reopen.

**Closed by ivanahuckova** 2021-09-17 15:05 UTC
