### ISSUE TITLE
Grafana 7 tables cannot show the formatted HTML (with sanitize HTML turned on), but this feature is very usable in Grafana 6.6

### ISSUE THREAD

**Issue by zenglime** [grafana/grafana#26472] opened 2020-07-21 02:17 UTC
we use the table plugin in Grafana 6.6 with below format html:
select CONCAT('<a target="_blank" href="', build_link, '">', SUBSTRING_INDEX(SUBSTRING_INDEX(build_link, 'buildId=', -1), '&', 1), '</a>') as build

with the sanitize HTML enabled, we can show a short buildId but with a full link to jump. this is very useful and when we upgrade to Grafana 7. this feature is gone...

**Comment by torkelo** [comment] 2020-07-21 07:38
duplicate of https://github.com/grafana/grafana/issues/24482

**Closed by torkelo** 2020-07-21 07:38 UTC
