### ISSUE TITLE
Alerting: Alerting queries should set interval & max data points 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#27469] opened 2020-09-09 07:30 UTC
What to set max data points and interval to is a bit tricky. 

The min interval should be fetched from data source settings if there is any (not sure if there is a standard property for that).

**Comment by torkelo** [comment] 2020-09-09 07:31
Should we create an Alerting github project?

**Comment by mckn** [comment] 2020-09-10 07:50
@torkelo do we need to add some more context here? I will move this to "Needs investigation or followup" in the mean time.

**Comment by torkelo** [comment] 2020-09-10 13:31
This is a backend issue

**Comment by kylebrandt** [comment] 2020-09-15 15:46
@torkelo I've noticed that when a query is issued from alerting, we set a header to indicate it as such. Given that this is tricky (not standard across data sources) - maybe a way forward for now is just to have data sources rely on this "FromAlert" information to set its own properties accordingly?

**Comment by torkelo** [comment] 2020-09-15 17:59
think interval & max datapoints is core thing that Grafana alerting needs to provide. It's not part of each data source's query model, it's outside of the queries so something Grafana needs to control and provide to the data source.

https://github.com/grafana/grafana/blob/master/pkg/tsdb/models.go#L25

**Comment by marefr** [comment] 2020-09-21 13:26
Currently, each data source is supposed to call [tsdb.GetIntervalFrom](https://github.com/grafana/grafana/blob/04a09dc60a5c09369f262b4aeb778a4541620bd8/pkg/tsdb/interval.go#L69) to get the minimum interval - this means currently data source decides what's the default min interval is if not configured/provided. Then [calculate](https://github.com/grafana/grafana/blob/04a09dc60a5c09369f262b4aeb778a4541620bd8/pkg/tsdb/interval.go#L56) the interval using that min interval. 

Maybe alerting should provide some default min interval, but what in that case?

Flux in interpolating the interval [here](https://github.com/grafana/grafana/blob/04a09dc60a5c09369f262b4aeb778a4541620bd8/pkg/tsdb/influxdb/flux/macros.go#L28). But I think the problem is when setting the interval [here](https://github.com/grafana/grafana/blob/04a09dc60a5c09369f262b4aeb778a4541620bd8/pkg/tsdb/influxdb/flux/query_models.go#L89-L92) where it doesn't call `tsdb.CalculateInterval` and just set 1ms as the default.

**Comment by ryantxu** [comment] 2020-10-04 00:29
In timestream, I hacked this:
https://github.com/grafana/timestream-datasource/blob/master/pkg/models/query.go#L42

I think picking a reasonable maxDataPoints is the best approach -- maybe 2048?

**Comment by marefr** [comment] 2021-03-25 17:56
@torkelo I'm eager to close this unless you can provide some more information of how you see this would be implemented. Min interval could be configured on the data source or part of the query model.

**Comment by torkelo** [comment] 2021-03-26 05:05
Yes, but some datasources use maxDataPoints and a user can set maxDataPoints in the query UI and in will impact the interval of the query

**Comment by marefr** [comment] 2021-03-26 17:13
@torkelo okay so this issue should be around making sure that a configured maxDataPoints in the UI gets stored in the alert rule in a similar way as interval:
https://github.com/grafana/grafana/blob/96ca2d6afcbfef9660d4a315c4cceb539edd425b/pkg/services/alerting/extractor.go#L174-L176

This is what allows the alert rule to provide the configured interval from the UI when evaluating the alert rule.

**Comment by marefr** [comment] 2021-04-12 12:37
Think we're missing to populate IntervalMS and MaxDataPoints fields here:
https://github.com/grafana/grafana/blob/629603dd92bdd4ae7c323577c10ed63434a38349/pkg/services/alerting/conditions/query.go#L225-L239

But interval is stored inside queryModel, hence why interval is supported in alerting today given data source implements it

**Comment by marefr** [comment] 2021-07-12 17:15
As discussed earlier today with @gabor and @kylebrandt the goal would be for data sources to be able to rely upon the provided "interval" value as the interval to be used/already calculated without having to calculate it themselves (in case not required). 
 - This is true for any query originating from the Grafana UI today
 - This should be true for anyone making a query using the Grafana HTTP API
 - For Grafana alerting queries this is not really true since a lot of data sources handles the calculation of intervals themselves.

In regards to "interval" above. For the grafana-plugin-sdk-go, we're talking about the [Interval](https://github.com/grafana/grafana-plugin-sdk-go/blob/22bb8807217417dd7f97a3770187a48808f21d00/backend/data.go#L58) field and for the legacy data model we're talking about [IntervalMS](https://github.com/grafana/grafana/blob/36cb396568ef4c450ccd05537dee5c1b4e510cea/pkg/plugins/tsdb.go#L25). 

For the old alerting system the calculated `interval` in the UI is stored in the panel JSON model as `interval` and when the dashboard is saved the alert rules is extracted in the backend where the `interval` is put into the alert rule query model on the  `interval` property:
https://github.com/grafana/grafana/blob/36cb396568ef4c450ccd05537dee5c1b4e510cea/pkg/services/alerting/extractor.go#L191-L193

The suggested solution for removing the logic for calculating intervals in each data source, related to old alerting, is to calculate the interval before executing a query, see below, since time range, query model and data source configuration is available here and it's currently what's needed for calculating intervals.
https://github.com/grafana/grafana/blob/36cb396568ef4c450ccd05537dee5c1b4e510cea/pkg/services/alerting/conditions/query.go#L167

**Comment by gabor** [comment] 2021-07-13 08:35
i think @marefr mean `panel-min-interval` in "For the old alerting system the calculated interval in the UI is stored in the panel JSON model".

this interval/min-interval thing is very confusing, so i'll try to summarize the current situation, i hope this helps:

`interval` is calculated from these values: time-range, max-data-points, panel-min-interval, datasource-min-interval.

a couple situations, from the datasource perspective (flux in this example, but it does not matter). we get a `DataQuery` (https://github.com/grafana/grafana-plugin-sdk-go/blob/master/backend/data.go#L46) structure, there are 3 fields that interest us: `Interval`, `MaxDataPoints` and `JSON`:

### Dashboard-query:
in this case, the browser calculates the `interval` from the above-mentioned values, and sends it to the server. in DataQuery in the data-source:
    - `Interval` is set to the calculated interval-value coming from the browser
    - `MaxDataPoints` is set to max-data-points
    - `JSON` contains among other things `{intervalMs, maxDataPoints}` with the correct values, the same as the values in `DataQuery` directly

in this case the data-source can simply forward the interval-value to the database, no processing needed.

### Old alerting:
the only value we get access to in the data-source is the `panel-min-interval`. it is stored in `DataQuery.JSON` under the confusing name `interval`. (NOTE: `interval` and `intervalMs` are very different things in the JSON. `interval` is `panel-min-interval` and `intervalMs` is real final calculated interval). so, in the DataQuery:
  - `Interval` is `0`
  - `MaxDataPoints` is `0`
  - `JSON` does not have `intervalMs` or `maxDataPoints`. it does have a field `interval`, which is set to `panel-min-interval`.

in this case the data-source has to calculate the real final `interval` by themselves. (NOTE: our datasources like `prometheus` or `elasticsearch` that are frontend-datasources, they do contain backend-code too, but for alerting only. this use-case (old-alert) is what their backend-code handles, assumes)

### New alerting:
currently in new alerting every value is a fixed, hardcoded value. in `DataQuery`:
  - `Interval` is `64ms`
  - `MaxDataPoints` is `5000`
  - `JSON` has:
      - `intervalMs` is `1000`
      - `maxDataPoints` is `43200`

note that the in-json values differ from the not-in-json values. they are coming probably from https://github.com/grafana/grafana/blob/main/pkg/expr/nodes.go#L129-L130 and from https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/models/alert_query.go#L12-L13

**Comment by gabor** [comment] 2021-07-13 08:39
as i wrote above, some of our data sources (prometheus, elasticseach, influxdb-influxql-mode) have backend-code to do queries, but they are only there for alerting-queries, their code assumes old-alerting. if they get converted to backend-data-sources at some point, it will be necessary to adjust the interval processing code in them to handle dashboard-queries too, so maybe this is interesting also for @ivanahuckova @Elfo404 and @dsotirakis

**Comment by marefr** [comment] 2021-07-13 09:27
Below should be a somewhat complete picture of how core data sources are handling intervals/max data points:

**Azure Monitor:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/azuremonitor/macros.go#L109-L122

**Cloud Monitoring:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/cloudmonitoring/time_series_query.go#L47-L48

**Elasticsearch:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/elasticsearch/client/client.go#L90-L94
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/elasticsearch/client/client.go#L133-L137
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/elasticsearch/time_series_query.go#L68-L72

**InfluxDB:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/influxdb/model_parser.go#L43-L46

**InfluxDB/Flux:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/influxdb/flux/macros.go#L28
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/influxdb/flux/query_models.go#L86-L93

**Graphite:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/graphite/graphite.go#L123

**Loki:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/loki/loki.go#L148-L154

**Prometheus:**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/prometheus/prometheus.go#L144-L151

**SQL (Postgres/MySQL/MSSQL):**
https://github.com/grafana/grafana/blob/702fd1cad966981c4f7c5d32302be7b12b74a408/pkg/tsdb/sqleng/sql_engine.go#L343-L347

**Comment by gabor** [comment] 2021-07-13 09:39
many data sources use `interval.GetIntervalFrom`  + `interval.Calculate` https://github.com/grafana/grafana/blob/main/pkg/tsdb/interval/interval.go#L56-L107 to handle the old-alert use case, some notes:

1. `GetIntervalFrom` it should probably be called `GetMinIntervalFrom`, because it tries to get panel-min-interval or datasource-min-interval
2. we probably have a bug in it, because we adjusted it so that it also falls back to `JSON.intervalMs`. it should not, because that only is "final" interval, not "min" interval. 
3. based on https://github.com/grafana/grafana/blob/main/pkg/tsdb/interval/interval.go#L92-L99 it seems some kind of min-interval (not sure if panel or datasource) can contain `<` or `>` symbols, which we remove.

**Comment by gabor** [comment] 2021-07-16 10:10
for reference, this is where the interval gets calculated in a dashboard-query: https://github.com/grafana/grafana/blob/main/public/app/features/query/state/PanelQueryRunner.ts#L231-L232

**Comment by gabor** [comment] 2021-08-10 10:32
i updated the comment at https://github.com/grafana/grafana/issues/27469#issuecomment-878891684 with changes that happened by https://github.com/grafana/grafana/pull/37201 .

in short, at this point, the from-dashboard-backend-query and new-alerting-query works very similarly:
in DataQuery.Interval and DataQuery.MaxDataPoints they provide values they think are correct, and in `DataQuery.JSON` the fields `intervalMs` and `maxDataPoints` have the same values.

old-alert is still different:
`DataQuery.Interval` is `0`, `DataQuery.MaxDataPoints` is `0`, `DataQuery.JSON` only contains a field named `interval`, where the panel_query_options_min_interval is stored.

**Comment by marefr** [comment] 2021-08-16 13:03
@gabor did you happen to open a PR/POC addressing this?

**Comment by gabor** [comment] 2021-08-23 09:40
@marefr i have just created a POC draft-pull-request here: https://github.com/grafana/grafana/pull/38434

**Comment by gabor** [comment] 2021-08-31 13:12
https://github.com/grafana/grafana/pull/38434 just got merged, which improves the situation for "old alerting".

the situation now is so that, in dashboard/explore-queries, in new-alert-queries and in old-alert-queries, everywhere it holds that `DataQuery.Interval` and `DataQuery.MaxDataPoints` is always set to a usable value.

so now a metric data-source can just take the `DataQuery.Interval` value and assume it is the good final value, no need to always do calculations based on panel-min-interval and datasource-min-interval.


other details:
- new-alerting and dashboard/explore-queries also set two json-attributes in the query-model-json (`intervalMs` and `maxDataPoints`). old-alerting does not do this, but i think it's not necessary to spend extra work implementing this. i recommend the datasource uses the `DataQuery.Interval` and `DataQuery.MaxDataPoints` attributes instead
- for new_alerting it's an open question how interval-values should be calculated, after all, there is not a visual place where max-data-points can be taken from. for now, if the alert is created starting from an existing dashboard-panel, and it has max-data-points set explicitly, it will be used, otherwise it defaults to 43200.

**Comment by gabor** [comment] 2021-08-31 13:12
@torkelo do you think this issue can be closed now, or maybe i overlooked something?

**Comment by marefr** [comment] 2021-09-01 16:44
@gabor think that we can close this and create a new issue for tracking updating all core backend data sources to use the query.Interval.

**Comment by marefr** [comment] 2021-09-01 16:45
Might be something more left in regards to max data points, but not sure what we could do rather than using a constant value?

**Comment by gabor** [comment] 2021-09-06 15:12
> Might be something more left in regards to max data points, but not sure what we could do rather than using a constant value?

i personally think it is "good enough" for alerting currently:
- new-alerts:
  - if you create the alert starting from a dashboard-panel, and you have max-data-points in the dashboard-panel-query-options: then it will use that value
  - otherwise: uses a constant value
- old-alerts: uses a constant value, i do not think it makes sense to work on improving this more, considering we have new-alert now.

**Comment by marefr** [comment] 2021-09-06 15:26
Sounds good to me

**Comment by gabor** [comment] 2021-09-06 15:50
@marefr i created a checklist issue at https://github.com/grafana/grafana/issues/38899 , closing this one as discussed.

**Closed by gabor** 2021-09-06 15:50 UTC
Labels: type/bug, area/alerting, area/backend, area/unified-alerting, area/alerting/legacy

**Comment by ashishkf** [comment] 2022-06-04 17:42
> i think @marefr mean `panel-min-interval` in "For the old alerting system the calculated interval in the UI is stored in the panel JSON model".
> 
> this interval/min-interval thing is very confusing, so i'll try to summarize the current situation, i hope this helps:
> 
> `interval` is calculated from these values: time-range, max-data-points, panel-min-interval, datasource-min-interval.
> 
> a couple situations, from the datasource perspective (flux in this example, but it does not matter). we get a `DataQuery` (https://github.com/grafana/grafana-plugin-sdk-go/blob/master/backend/data.go#L46) structure, there are 3 fields that interest us: `Interval`, `MaxDataPoints` and `JSON`:
> 
> ### Dashboard-query:
> in this case, the browser calculates the `interval` from the above-mentioned values, and sends it to the server. in DataQuery in the data-source: - `Interval` is set to the calculated interval-value coming from the browser - `MaxDataPoints` is set to max-data-points - `JSON` contains among other things `{intervalMs, maxDataPoints}` with the correct values, the same as the values in `DataQuery` directly
> 
> in this case the data-source can simply forward the interval-value to the database, no processing needed.
> 
> ### Old alerting:
> in this case, the alerting code calculates the `interval` from the above-mentioned values (for max-data-points it uses `1500`), and sends it to the server. in DataQuery in the data-source:
> 
> * `Interval` is set to the calculated value
> * `MaxDataPoints` is set to 1500
> * `JSON` does not have `intervalMs` or `maxDataPoints`. it does have a field `interval`, which is set to `panel-min-interval`. (i recommend ignoring this value and using the `DataQuery.Interval`)
> 
> in this case the data-source can simply forward the interval-value to the database, no processing needed.
> 
> ### New alerting:
> if the alert was created by going to a dashboard-panel's configuration, alert-tab, and choosing [Create alert rule from this panel], then `Interval` and `MaxDataPoints` is set based on dashboard-values. if the alert is created directly in the alerting-section, `Interval` will be `1s` and `MaxDataPoints` will be 43200. in summary: in `DataQuery`:
> 
> * `Interval` is `1s` or based on the dashboard it was created from
> * `MaxDataPoints` is `43200` or baed on the dashboard it was created from
> * `JSON` has:
>   
>   * `intervalMs` equals to `DataQuery.Interval`
>   * `maxDataPoints` equals to `DataQuery.MaxDataPoints`
> 
> [EDIT: updated based on changes to the code]

I am bit confused by this. The Grafana docs is using legacy alert to refer to the alerts created from dashboard panel and new alerts to the unified alerting interface/UI they introduced in 8.0. But this comments uses exactly opposite terminology.

BTW - we are still seeing prometheus alerts queries coming from the new Grafana unified alert manager with 1s step!
