### ISSUE TITLE
9.2.0: buggy behavior for time range selector on iOS

### ISSUE THREAD

**Issue by hhoffstaette** [grafana/grafana#56751] opened 2022-10-11 19:21 UTC
**What happened**:

- updated to Grafana 9.2.0
- opened a dashboard on iOS 15.x (Safari)
- selected time range picker while in regular (vertical) view
- submenu pops up (patially out of frame to the left), window locks up

At this point I have to force-close the browser window.
The behaviour is repeatable.

**What you expected to happen**:

Propely opened time range popup menu.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

It worked fine with 9.1.x.
The lockup does not happen in horizontal view.

**Environment**:
- Grafana version: 9.2.0
- Data source type & version: Prometheus latest
- OS Grafana is installed on: Linux
- User OS & Browser: iOS 15
- Grafana plugins: none
- Others: none

Thanks for Grafana! :heart:

**Comment by zuchka** [comment] 2022-10-13 02:33
Thanks for creating this issue, @hhoffstaette 

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by hhoffstaette** [comment] 2022-10-13 05:16
It does not reproduce on your sandbox, and I think I found the pattern: the problem only appears when the dashboard title is ~3 letters like e.g. "DNS". In this case the dashboard settings are immediately visible, not hidden behind the three vertical "Show more items" dots, and it locks up when I select the watch icon (time range selector) and the selector menu pops up, partially out of frame.
It does **not** lock up when the dashboard title is longer and the time range selector has to be conjured up via "Show more items"; in that case the time range selector popup menu is fully within the browser window and everything works.

**Comment by zuchka** [comment] 2022-10-13 23:49
@hhoffstaette can you please try using this three-letter dashboard on play? I see the watch icon but it doesn't lock up for me. I can select a timerange and then it collapses:

the time range selector is out of frame and that's not a great experience however:
<img width="758" alt="CleanShot 2022-10-13 at 13 49 06@2x" src="https://user-images.githubusercontent.com/37156449/195731847-959a9456-631c-4c0b-a5fa-5593bbe87450.png">

**Comment by hhoffstaette** [comment] 2022-10-14 09:01
I visited the "IOS" dashboard on the playground and _of course_ it doesn't lock up. :-/
This looks increasingly like a Safari bug on my iPhone 12 with the latest iOS 15.x, as it looks as if the lockup happens when the browser displays the offscreen area and simultaneously tries to resize/shift the window content.
Honestly not sure what else I can do except make a video using my other phone, but the result will be the same.
Anyway, if you (or anybody else) cannot reproduce this please just close this ticket. I don't use my phone on a regular basis for Grafana and only found this by accident.
Nevertheless thank you for your effort!

**Comment by zuchka** [comment] 2022-10-17 23:13
thanks @hhoffstaette I've relabeled the issue as a mobile-support problem. I'm going to close it for now but if you continue to experience issues just hop back on this thread. our mobile experience could be better 👍

**Comment by marianrh** [comment] 2022-10-28 08:21
@zuchka This is 100 % reproducible on the latest iOS 16.1 (on iPhone 13 Pro in my case) and makes Grafana almost unusable. Even though probably Safari is at fault for the lockup, the problem only occurs with Grafana >= 9.2.0, so it's a change in Grafana that triggers the bug. It would be great if you could look into that!

**Comment by lpskdl** [comment] 2022-11-16 10:04
Hello, this seems to be a duplicate of i[ssue](https://github.com/grafana/grafana/issues/32369). Could you please confirm?

**Comment by marianrh** [comment] 2022-11-18 11:04
@lpskdl Well, the two issues seem to be related. But #32369 is just about the cosmetic problem of the menu being shown outside of the visible area, while in this issue the browser tab locks up completely and cannot be used anymore.

**Comment by joshhunt** [comment] 2022-12-16 10:23
With Grafana v9.3.2-45365 (ef5286dd77), iOS 16.1.2, on iPhone 14, I'm seeing slightly different behaviour. 

I am able to open the time range picker and select a new time successfully.

However, tapping the Zoom Out button reliably freezes the browser, requiring the tab to be force quit.


https://user-images.githubusercontent.com/46142/208077550-ae490744-3a10-4395-98d3-a7937d61f35b.MP4

You can't see my frantically tapping the web page trying to get it to do something, but I am!!

**Comment by tomquist** [comment] 2022-12-26 08:18
I have the same issue but for me it only happens when I create a standalone homescreen icon from a dashboard. I attached a recording here. At the end of the video the app is completely frozen and I have to force close it:

https://user-images.githubusercontent.com/528585/209522067-5bfcbf51-3a00-4dbb-873a-d42b6c9d42f9.MOV

I didn‘t manage to reproduce the issue on any demo dashboard so far.

When I press the zoom out 🔍 button first before pressing the time range picker the buttons all disappear into the 3 dots show more menu and from there everything works as expected.

**Comment by ajaxharg** [comment] 2023-11-06 19:24
I have just upgraded from an iPhone XR iOS 17 to Max on the same os. On the xr i had no problems. On the max the safari browser completely locks up when viewing the time range option. The same happens in chrome though this is really using safari under the hood.

**Closed** 2024-02-28 10:48 UTC
Labels: type/bug, type/ux, area/mobile-support, timepicker, triage/needs-confirmation
