### ISSUE TITLE
Cannot use String type data as x-axis in Bar Gauge visualization for Azure Application Insights datasource

### ISSUE THREAD

**Issue by Leonardo610** [grafana/grafana#20698] opened 2019-11-27 11:45 UTC
**What happened**:
With the last update to Grafana 6.5.0 on the Bar Gauge visualization I got this error while using another type of data (in this case String) than timestamp as x-axis value: 
`parsing time "0" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "0" as "2006"`

**What you expected to happen**:
Until the 6.4 version the query worked fine and the data visualized were correct.

**How to reproduce it (as minimally and precisely as possible)**:
Use the Azure Monitor plugin to retrieve data from Application Insights, use it in a panel with visualization type Bar Gauge and set the x-axis with a value different than the timestamp.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: Azure Monitor 0.3.0
- OS Grafana is installed on: Linux (ubuntu 18.04)
- User OS & Browser: Windows 10 - Google Chrome
- Grafana plugins: I have some troubles extracting them at the moment.
- Others:

**Comment by marefr** [comment] 2019-11-27 12:41
Duplicate of #20608

**Closed by marefr** 2019-11-27 12:41 UTC
