### ISSUE TITLE
Varible usage in prometheus query when repeating panel

### ISSUE THREAD

**Issue by mrboso** [grafana/grafana#16056] opened 2019-03-18 16:44 UTC
![Screenshot from 2019-03-18 10-28-57](https://user-images.githubusercontent.com/25738730/54547282-b49b0300-49a5-11e9-9615-289e7c99292f.png)
![Screenshot from 2019-03-18 10-31-18](https://user-images.githubusercontent.com/25738730/54547314-c11f5b80-49a5-11e9-9d0e-19300b1c7782.png)

**What happened**:
When using variable in Prometheus query and repeat the panel with this variable, "no value" is shown in "gauge" visualization.

**What you expected to happen**:
To use correct part of variable in query.  

**How to reproduce it (as minimally and precisely as possible)**:
I have created variable "fsmount" with query `disk_used_percent{job=~"$node",path!~"^/etc.*"}` and regex `.*path="([^"]*)".*` which fills the variable with values `/home`, `/` and `/boot`. I also checked "include all options"

Then I have created a "gauge" graf with prometheus as datasource with query `disk_used_percent{job="$node",path="$fsmounts"}` and title "FS "$fsmounts" usage" and repeted with `fsmount`. After setting "All" option in drop down menu, three graphs have been generated, each with correct title, but the "no value" is shown.
The query inspector generates url with all three values from variable `
url:"api/datasources/proxy/1/api/v1/query?query=disk_used_percent%7Bjob%3D%22my-host%22%2Cpath%3D%22%2Fhome%7C%2F%7C%2Fboot%22%7D&time=1552927161"`

**Anything else we need to know?**:

**Environment**:
- Grafana version: docker 6.0.1
- Data source type & version: prometheus
- OS Grafana is installed on: docker, Centos 7.6
- User OS & Browser: centos 7.6, firefox-60.5.1-1
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-03-18 21:02
this is fixed in master and upcoming v6.1 release

dupe of 
https://github.com/grafana/grafana/issues/15880

**Closed by torkelo** 2019-03-18 21:02 UTC

**Comment by rikhul** [comment] 2019-11-06 13:45
I see this is v6.3.3 (84d0a71)

**Comment by marefr** [comment] 2019-11-06 14:43
@rikhul nice to see you here :+1: Would suggest trying out v6.4.3 and/or open a new bug report and we'll have a look. Thanks
