### ISSUE TITLE
[webpack-cli] TypeError: schema_utils_1.default is not a function

### ISSUE THREAD

**Issue by twei55** [grafana/grafana#45668] opened 2022-02-21 13:01 UTC
**What happened**:

```
git checkout v8.4.1
yarn install --immutable
yarn start
```

Fails with:
```
SASS variable files generated
Compiling message catalogs…
Done!
[webpack-cli] TypeError: schema_utils_1.default is not a function
```

**What you expected to happen**:

```
git checkout v8.4.1
yarn install --immutable
yarn start
```

```
SASS variable files generated
Compiling message catalogs…
Done!
...
webpack 5.X compiled successfully in X ms
```

**Environment**:
- Grafana version: v8.4.1
- OS Grafana is installed on: macOS 12.2.1

**Comment by DmitrySidorow** [comment] 2022-02-21 13:21
same https://github.com/grafana/grafana/issues/45600

**Comment by jackw** [comment] 2022-02-21 14:10
Closing as duplicate of #45600

**Closed by jackw** 2022-02-21 14:10 UTC
