### ISSUE TITLE
PostgreSQL alerting does not work when using variables in queries.

### ISSUE THREAD

**Issue by 4szt4l** [grafana/grafana#9880] opened 2017-11-14 10:58 UTC
- What Grafana version are you using?
4.6.1
- What datasource are you using?
Postgresql
- What OS are you running grafana on?
Ubuntu 16.04
- What did you do?
Setting up alerting for multiple panels using variables
- What was the expected result?
Working alerts
- What happened instead?
error:"tsdb.HandleRequest() response error &{pq: syntax error at or near "$" A 0xc420ac8d10 [] []}"

When I don't use variables, it's working fine.

My query looks like this:
SELECT
  $__time(tstatus.timestamp),
  cpu, mem, disk from tstatus
INNER JOIN 
tapp 
ON
tapp.app_id = tstatus.app_id
INNER JOIN 
tspace 
ON
tspace.space_id = tapp.space_id
WHERE
app_name in ($Appname) and 
space_name in ($Spacename)
order by tstatus.timestamp
limit 100000

If I don't use $Appname and $Spacename, but the exact names, alerting is working correctly. I remember a similar notification in 4.6.0pre1, but now I don't get any messages that this is not supposed to work.

**Comment by torkelo** [comment] 2017-11-14 11:18
duplicate of https://github.com/grafana/grafana/issues/6557

**Closed by torkelo** 2017-11-14 11:18 UTC

**Comment by nomar22** [comment] 2021-05-24 10:16
The point here it's because you should not use dashboard filters on an alert. This makes no sense.

**Comment by 4szt4l** [comment] 2021-05-24 10:19
> 
> 
> The point here it's because you should not use dashboard filters on an alert. This makes no sense.

You are not necessarily using variables to filter alerts, but also to generate hundreds of them...
If it didn't make much sense maybe there wouldn't be hundreds of upvotes in the OP #6557

**Comment by nomar22** [comment] 2021-05-24 10:33
ok I got it , I'm sorry I miss your point.  But the fact here is that was the reason, I was stucked on this and the response was not friendly.
