### ISSUE TITLE
 Grafana7.3.2 is not displayed in ie

### ISSUE THREAD

**Issue by donghuzi1** [grafana/grafana#30241] opened 2021-01-13 00:59 UTC
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-01-13 09:08
duplicate of https://github.com/grafana/grafana/issues/15754

**Comment by torkelo** [comment] 2021-01-13 09:09
IE is not supported

**Closed by torkelo** 2021-01-13 09:08 UTC
