### ISSUE TITLE
Share by "shorten url" strips out all but one adhoc filter

### ISSUE THREAD

**Issue by daniel-bray-sonalake** [grafana/grafana#35808] opened 2021-06-16 10:18 UTC
**What happened**:

- I created a dashboard with ad hoc filters (for elastic search)
- I added more than ad hoc 1 filter
- I shared this page using the `shorten url` option.
- The dashboard that the short url diverts to is missing all but 1 of the ad hoc filters.

**What you expected to happen**:

I expected the short url to take the user to the same page as before, with the same ad hoc filter parameters set.

**How to reproduce it (as minimally and precisely as possible)**:

1. I have a dashboard with Ad Hoc elastic search filters. 
![image](https://user-images.githubusercontent.com/18031246/122199588-1a7ed980-ce92-11eb-9e61-6a300aa3d213.png)

2. I built up a search for this 
![image](https://user-images.githubusercontent.com/18031246/122199686-36827b00-ce92-11eb-90bb-28afdc78cadf.png)

3. The URL for this page is now: 
```
https://website.com/d/sample-dashboard?orgId=1
&from=1623755251000
&to=now
&var-Filters=eircode%7C%3D%7CAA001234
&var-Filters=method%7C!%3D%7CGET
```
4. When I click on share, and use the "shorten url" option, and use the new url, I get taken to this page
```
https://website.com/d/sample-dashboard?orgId=1
&from=1623755251000
&to=1623838116076
&var-Filters=method%7C!%3D%7CGET
```
It looks like the shorten url is dropping the multiple `var-Filters` parameters, but these are from the ad-hoc filter, so it's not something I can change.

The result is that the short url is showing different results to the original shared page.

**Anything else we need to know?**:

That's about it

**Environment**:
- Grafana version: Grafana v7.5.4 (615c153b3a)
- Data source type & version: Elasticsearch (the core version shipped with Grafana)
- OS Grafana is installed on: running on docker, using `grafana/grafana:7.5.4`
- User OS & Browser: Ubuntu 21.04 in Chrome, but this is happening for all users.
- Grafana plugins:  `marcusolsson-json-datasource,marcusolsson-dynamictext-panel,marcusolsson-treemap-panel,briangann-datatable-panel,neocat-cal-heatmap-panel,grafana-polystat-panel`
- Others: N/A

**Comment by daniel-bray-sonalake** [comment] 2021-06-16 10:22
I can confirm this also happens for Prometheus, and in `Grafana v8.0.0-beta2 (9d4c719205)`

So it looks like a still current core issue, and not a plugin problem.

**Comment by marefr** [comment] 2021-06-17 09:41
Not able to reproduce using this dashboard/URL that has two adhoc filters applied: https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1&var-Filters=@hostname%7C%3D%7Cserver%2020&var-Filters=@metric%7C%3D%7Ccpu&var-NewFilter=1&from=1623920705312&to=1623922505312

I've created a short URL https://play.grafana.org/goto/CaCAtoR7k?orgId=1 that redirects to above URL with the adhoc filters left intact.

I've also tried using `!=` for the second filter, but there's no difference.

Are you sure that the link URL is correct or is that wrong as well?
![image](https://user-images.githubusercontent.com/1668778/122371871-80399700-cf60-11eb-8212-9ffddf6f825a.png)

I'll close this, but if you could provide more information/proof this is a Grafana bug we'll reopen it. Like the Elasticsearch index mapping that shows what types your fields have that you're using in adhoc filters

**Closed by marefr** 2021-06-17 09:41 UTC
Labels: area/backend, area/backend/api, needs investigation

**Comment by daniel-bray-sonalake** [comment] 2021-06-17 09:58
Thanks; let me check what's different between our two installations.

**Comment by daniel-bray-sonalake** [comment] 2021-06-17 10:48
Thanks, this is working fine. 

Looks like it was fixed between the beta version I was testing and the final 8.0.0 release.


Thanks!
