### ISSUE TITLE
Query history: deduplication

### ISSUE THREAD

**Issue by jpds** [grafana/grafana#66553] opened 2023-04-14 09:53 UTC
**What you expected to happen**:

The query history saver should support deduplication for repeated queries (possibly with an incrementing count?):

![Screenshot from 2023-04-14 10-50-14](https://user-images.githubusercontent.com/29158971/232011249-0f74f37c-62e6-4067-91eb-dc65e49831fe.png)

**Environment**:
- Grafana version: v9.4.7

**Comment by jpds** [comment] 2023-04-17 15:09
@tonypowa For completeness, this is probably already tracked by #51451.

**Comment by Elfo404** [comment] 2023-04-18 13:43
@jpds yes, i'll mark this as duplicate of https://github.com/grafana/grafana/issues/51451.

**Closed by Elfo404** 2023-04-18 13:43 UTC
Labels: type/feature-request
