### ISSUE TITLE
WHERE clause does not use tags in case of the same name for tag and field

### ISSUE THREAD

**Issue by m-peko** [grafana/grafana#23017] opened 2020-03-24 09:35 UTC
**What happened**:
`WHERE` clause in the Grafana query does not actually use InfluxDB tags. If InfluxDB for any reason has the same name for tag and field, `WHERE` clause actually uses fields instead of tags. This can be fixed by using `::tag` suffix in the raw query like: `... WHERE "foo"::tag = 'value1' ...` but this suffix cannot be imported to the Grafana through the JSON file.

Anyway, I think that Grafana should automatically add `::tag` suffix to each component of the `WHERE` clause.

Related InfluxDB issue is [here](https://github.com/influxdata/influxdb/issues/9891).

**What you expected to happen**:
I expected the tags to be evaluated, not the fields.

**How to reproduce it (as minimally and precisely as possible)**:
Use the same name for tag and field in InfluxDB.

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Google Chrome

**Comment by aknuds1** [comment] 2020-03-24 09:39
Can you please try this also with the latest Grafana version, 6.7.1?

**Comment by aknuds1** [comment] 2020-03-24 09:42
I think this must be a duplicate of #10654. Please let us know if the two issues do differ significantly.

**Closed by aknuds1** 2020-03-24 09:42 UTC
Labels: datasource/InfluxDB

**Comment by m-peko** [comment] 2020-03-24 10:12
@aknuds1 are there any changes made in API between 6.4.0 and 6.7.1? Seems like I get a 404 error when trying to import JSON dashboard through the API.

**Comment by aknuds1** [comment] 2020-03-24 10:16
@m-peko I'm not aware of it. How are you using the API?

**Comment by m-peko** [comment] 2020-03-24 10:17
@aknuds1 it worked ok but now it says it won't load application files...

**Comment by aknuds1** [comment] 2020-03-24 10:19
I can't tell if you're using the API right or not, unless you describe in detail how you make your failed API request.
