### ISSUE TITLE
Browser memory continues to grow

### ISSUE THREAD

**Issue by erduoxiangshang** [grafana/grafana#15958] opened 2019-03-13 03:49 UTC
**What happened**:Hello, build 30 graph panel s in dashboard, access the same data source, time set to 5 s refresh once, 3 or 4 hours, browser will crash. Thank you very much.
![image](https://user-images.githubusercontent.com/29893194/54252142-b2d7d680-4584-11e9-9cef-714e55862243.png)
![image](https://user-images.githubusercontent.com/29893194/54252167-c4b97980-4584-11e9-9c1d-512a906c97ff.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:Latest version
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser: google
- Grafana plugins: graph
- Others:

**Comment by torkelo** [comment] 2019-03-13 06:05
dupe of https://github.com/grafana/grafana/issues/15731 

We are investigating, currently no smoking gun :(

**Closed by torkelo** 2019-03-13 06:05 UTC

**Comment by erduoxiangshang** [comment] 2019-03-13 06:19
Thank you very much.
