### ISSUE TITLE
Grafana Alert || telegram (not showing more than 6 metrics)

### ISSUE THREAD

**Issue by faiz0210** [grafana/grafana#23878] opened 2020-04-25 01:25 UTC
If an alert has more than 6 metrics, telegram chat shows max 6 metrics. Although when I get the same alert on my email, I get all the metrics.
Are there any restrictions on the metrics count while sending alert on telegram?
If yes, is it possible to increase the same via some configuration?

I was going through this [link](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/telegram.go) and there is a parameter 
"fieldLimitCount := 4"
Could this be a reason?
![image](https://user-images.githubusercontent.com/37917624/80267885-09d53800-86c1-11ea-9360-4a5798288900.png)

Couldn't find anything related to this issue on the web.
Apologies in case this is not the right channel to raise this issue.

**Comment by papagian** [comment] 2020-05-03 14:05
Duplicate of #16662

**Closed** 2020-05-03 14:08 UTC
Labels: type/duplicate
