### ISSUE TITLE
Viewer can modify board

### ISSUE THREAD

**Issue by Tepew** [grafana/grafana#26546] opened 2020-07-23 09:55 UTC
Viewer can modify boards but don`t have any permission for it. Viewer add for url
https://url/board?editPanel=2
and change board. Then save change. Edit don`t save on the server and don`t affect other users. But user can see all metrics.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Zabbix 3.12.2
- OS Grafana is installed on: OEL7
- User OS & Browser: any
- Grafana plugins: Zabbix 3.12.2

**Comment by ivanahuckova** [comment] 2020-07-23 12:29
Yes, that is correct behaviour. Viewer role has nothing to do about data access protection but is only about preventing user from being able to modify and save / create dashboards. Also duplicate of https://github.com/grafana/grafana/issues/1826.

**Closed by ivanahuckova** 2020-07-23 12:29 UTC
