### ISSUE TITLE
Alerting UI: Grouping appears to be off

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#39674] opened 2021-09-27 15:07 UTC
It seems that with the default of "no grouping" e.g. `group_by: ""` the "alert groups" tab gets confused. 

It shows something like:

<img width="843" alt="Screenshot 2021-09-23 at 10 18 53" src="https://user-images.githubusercontent.com/231583/134935186-5e9e0e43-0206-4874-a89c-d82b619b78cc.png">

But I don't understand a) Why is there a separate group at the top and b) Why is there a `group by` empty header - should we say something like `no grouping` specified and make it all one big group?

Perhaps this is a bug?

**Comment by nathanrodman** [comment] 2021-09-27 23:06
I wasn't able to reproduce this locally, everything was grouped in a single "No grouping". But I think if there is "no grouping" for all alert groups should just show each alert in a list by most recent without a toggle

![Screen Shot 2021-09-27 at 3 37 28 PM](https://user-images.githubusercontent.com/3469390/134994745-c68725a9-2cf3-4fb5-bf55-30627d430234.png)

**Comment by gillesdemey** [comment] 2022-01-27 17:46
I've stumbled on this bug purely by coincidence; if you have more than one policy assigned to particular set of labels they will show up in different groups in the "alert groups" tab.

This warrants a bit more investigation since they the API returns them multiple times and the UI is simple rendering what we've received.

**Closed** 2022-02-28 17:50 UTC
Labels: type/bug, area/frontend, area/grafana/ui, area/alerting/unified
