### ISSUE TITLE
[Bug]: Graph & Single Value Tooltip & Stacking with individual value results in NaN

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#5339] opened 2016-06-12 00:18 UTC
All Series
![thumb_2_1024](https://cloud.githubusercontent.com/assets/406777/16060632/a0046ec2-323d-11e6-9507-315a67b59723.jpg)

Individual

![thumb_1_1024](https://cloud.githubusercontent.com/assets/406777/16060672/d91959e8-323d-11e6-8b57-6049b74211bf.jpg)

Tooltip shows NaN for Individual. I was expecting it to show 1 when i hover over a specific point.

**Comment by bergquist** [comment] 2016-06-13 05:08
Cant see any NaN values. Just lots of 1. What am I missing?

**Comment by torkelo** [comment] 2016-06-13 08:17
cant replicate this, can you look at the actual data your query returns (using chrome dev tools network tab). Maybe there is some non numeric data there?

**Comment by deepujain** [comment] 2016-06-14 21:33
Grafana Version: grafana-3.0.2-1463383025

Response: 
{"results":[{"series":[{"name":"epdetail5","tags":{"experimentId":"11473"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"11479"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"11480"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"12070"},"columns":["time","count"],"values":[[1465282800000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"12742"},"columns":["time","count"],"values":[[1465110000000,1],[1465282800000,1],[1465542000000,1]]},{"name":"epdetail5","tags":{"experimentId":"13248"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13356"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13369"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13370"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13371"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13405"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1]]},{"name":"epdetail5","tags":{"experimentId":"13463"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1]]},{"name":"epdetail5","tags":{"experimentId":"13568"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13632"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13663"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13664"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13665"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13713"},"columns":["time","count"],"values":[[1465110000000,1]]},{"name":"epdetail5","tags":{"experimentId":"13783"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13784"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13845"},"columns":["time","count"],"values":[[1465110000000,1]]},{"name":"epdetail5","tags":{"experimentId":"13848"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"13903"},"columns":["time","count"],"values":[[1465714800000,1]]},{"name":"epdetail5","tags":{"experimentId":"13936"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14037"},"columns":["time","count"],"values":[[1465110000000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14038"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14054"},"columns":["time","count"],"values":[[1465110000000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14056"},"columns":["time","count"],"values":[[1465282800000,1]]},{"name":"epdetail5","tags":{"experimentId":"14084"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14134"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1]]},{"name":"epdetail5","tags":{"experimentId":"14135"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1]]},{"name":"epdetail5","tags":{"experimentId":"14167"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14170"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14171"},"columns":["time","count"],"values":[[1465110000000,1],[1465455600000,1]]},{"name":"epdetail5","tags":{"experimentId":"14191"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1]]},{"name":"epdetail5","tags":{"experimentId":"14192"},"columns":["time","count"],"values":[[1465196400000,1],[1465369200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14193"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14214"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14215"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14222"},"columns":["time","count"],"values":[[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14223"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14224"},"columns":["time","count"],"values":[[1465110000000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14225"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14226"},"columns":["time","count"],"values":[[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465542000000,1],[1465628400000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14349"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14387"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14401"},"columns":["time","count"],"values":[[1465110000000,1]]},{"name":"epdetail5","tags":{"experimentId":"14427"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14429"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14435"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14440"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14441"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14442"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"14445"},"columns":["time","count"],"values":[[1465110000000,1]]},{"name":"epdetail5","tags":{"experimentId":"4157"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"4337"},"columns":["time","count"],"values":[[1465110000000,1]]},{"name":"epdetail5","tags":{"experimentId":"8450"},"columns":["time","count"],"values":[[1465110000000,1],[1465196400000,1],[1465282800000,1],[1465369200000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1],[1465801200000,1]]},{"name":"epdetail5","tags":{"experimentId":"8454"},"columns":["time","count"],"values":[[1465455600000,1]]},{"name":"epdetail5","tags":{"experimentId":"8456"},"columns":["time","count"],"values":[[1465369200000,1]]},{"name":"epdetail5","tags":{"experimentId":"8457"},"columns":["time","count"],"values":[[1465110000000,1]]},{"name":"epdetail5","tags":{"experimentId":"9453"},"columns":["time","count"],"values":[[1465196400000,1],[1465455600000,1],[1465542000000,1],[1465628400000,1],[1465714800000,1]]}]}]}

I do not see null values.

**Comment by deepujain** [comment] 2016-06-14 21:42
Is there a better way to visualize this kind of data? 

The values are going to be 1 or Not present at all. Like a cluster of circles for each day with radius of circle being the value ?

**Comment by torkelo** [comment] 2016-06-15 07:31
managed to replicate this, caused by the stacking and individual value tooltip option.

**Comment by deepujain** [comment] 2016-06-15 19:13
Is it a defect  that needs a fix ?

**Comment by torkelo** [comment] 2016-06-15 19:16
yepp, seems to have be an old bug with single series tooltip and stacking.

**Comment by daniellee** [comment] 2022-11-02 19:30
Closing this - don't think we are going to fix this bug for the old graph panel.

**Closed by daniellee** 2022-11-02 19:30 UTC
Labels: type/bug, area/panel/graph, version/3
