### ISSUE TITLE
Hide a column but apply rules

### ISSUE THREAD

**Issue by syedsfayaz** [grafana/grafana#18559] opened 2019-08-14 20:36 UTC
**Able to Hide a column but set rules for the column values**:

**I want to hide a status column but want to change the color of the table based on that hidden column.**:

I have details added as a comment to this old support link. 
https://community.grafana.com/t/hide-time-column/1384
![image](https://user-images.githubusercontent.com/26099918/63054259-5dd41f80-be98-11e9-94dd-01620e85924d.png)
When I add a new rule and try to hide it the rule to change color does not work. 
![image](https://user-images.githubusercontent.com/26099918/63054295-75130d00-be98-11e9-96b0-aea1d3c1eb2d.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version: mysql
- OS Grafana is installed on: Linux RH 7
- User OS & Browser: 
- Grafana plugins: table panel

**Comment by torkelo** [comment] 2019-08-15 06:16
dupe of https://github.com/grafana/grafana/issues/18040

**Closed by torkelo** 2019-08-15 06:16 UTC
