### ISSUE TITLE
Docker image grafana/grafana:master can't run in manjaro linux

### ISSUE THREAD

**Issue by YangKian** [grafana/grafana#23173] opened 2020-03-29 10:32 UTC
**What happened**:
I try to run the following:

` docker run --rm -it --name=grafana -p 3000:3000 grafana/grafana:master`

then I get an error:

 `standard_init_linux.go:211: exec user process caused "exec format error"`

but I can run the same command with the image `grafana/grafana:latest` successfully

`docker run --rm -it --name=grafana -p 3000:3000 grafana/grafana:latest` 

Is there any thing wrong with the image `grafana/grafana:master`?

**What you expected to happen**:
The image `grafana/grafana:master` should be work

**Environment**:

- User OS & Browser:
Linux 5.4.28-1-MANJARO

**Comment by aknuds1** [comment] 2020-03-29 11:12
What architecture are you on? AMD64? This is probably a duplicate of #23167, so closing for the time being. I'll work work on fixing #23167 tomorrow, once I'm back at work.

**Closed by aknuds1** 2020-03-29 11:12 UTC

**Comment by aknuds1** [comment] 2020-03-30 10:36
The issue should now be fixed, please test again and let us know if you're still experiencing issues.

**Comment by YangKian** [comment] 2020-03-30 12:07
It works for me now, thanks!

**Comment by aknuds1** [comment] 2020-03-30 12:09
Great!
