### ISSUE TITLE
Clicking 'Query History' button throws minified React error.

### ISSUE THREAD

**Issue by jmford775** [grafana/grafana#26184] opened 2020-07-08 23:35 UTC
OS: CentOS 7
Browser: Chrome
Grafana version; 6.7.0

- Used Helm to install loki-stack (loki, promtail, fluent-bit, grafana) 
- Using ceph volumes maintained by rook for persistence
- Persistence enabled on both loki and grafana

![QueryHistory_exception](https://user-images.githubusercontent.com/24438547/86980483-c4a99980-c138-11ea-9570-0a2119ae68f9.PNG)

**Comment by dprokop** [comment] 2020-07-09 10:54
@jmford775 can you please provide full stack trace from the console?

**Comment by dprokop** [comment] 2020-07-09 11:12
@jmford775 Query History was a beta feature in 6.7.0. Can you please check if it works in your scenario in Grafana 7? In the meantime, I'm gonna close the issue. Feel free to reopen if the problem is still occurring for you.

**Closed by dprokop** 2020-07-09 11:12 UTC
Labels: area/explore, needs more detail

**Comment by jmford775** [comment] 2020-07-09 23:32
I pulled the 5.3.5 chart of grafana in (app version 7.0.3) into the loki-stack umbrella chart and the issue no longer exists

**Comment by dprokop** [comment] 2020-07-10 09:41
@jmford775 great! Happy this helped :)
