### ISSUE TITLE
Grafana integration with Elasticsearch for APM metrics does not group by terms with keywords

### ISSUE THREAD

**Issue by ishaigor** [grafana/grafana#21875] opened 2020-01-31 14:48 UTC
**What happened**: I am trying to add performance metrics about transaction durations as a Grafana panel; as such, I need to group the transactions by transaction.name. This field's type is keyword out of the box per https://www.elastic.co/guide/en/apm/server/current/exported-fields-apm.html. I configured the panel to group by term on transaction.name and then group by data histogram

**What you expected to happen**: I expect the graph to be grouped by the term in transaction.name and then by the data histogram.

**How to reproduce it (as minimally and precisely as possible)**: 
- Add Elasticsearch with APM data as a Grafana source. 
- Add metric percentiles on transaction.duration.us. It will be grouped by a data histogram already. You will see the data percentiles by automatic time intervals.
- Add group by terms as a first group by clause, select transaction.name as the field. All data is gone now.  

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.3.3  (84d0a71)
- Data source type & version: Elasticsearch 7.5.0
- OS Grafana is installed on: centos 7
- User OS & Browser: Mac OS Mojave 10.14.6, Firefox 72.0.2 (64-bit)
- Grafana plugins: Elasticsearch
- Others:

**Comment by marefr** [comment] 2020-02-03 17:54
Please include query inspector request/response.

**Comment by ishaigor** [comment] 2020-02-03 18:26
@marefr  here it is `{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/53/_msearch?max_concurrent_shard_requests=5",
    "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":[\"*\"]}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1580750742494\",\"lte\":\"1580754342494\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"observer.type:\\\"apm-server\\\" AND service.environment: \\\"prod\\\" AND service.name: \\\"demand-ap\\\"\"}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"transaction.name\",\"size\":10,\"order\":{\"_key\":\"desc\"},\"min_doc_count\":1},\"aggs\":{\"2\":{\"date_histogram\":{\"interval\":\"2s\",\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":\"1580750742494\",\"max\":\"1580754342494\"},\"format\":\"epoch_millis\"},\"aggs\":{\"1\":{\"percentiles\":{\"field\":\"transaction.duration.us\",\"percents\":[\"50\",\"75\",\"95\",\"99\"]}}}}}}}}\n"
  },
  "response": {
    "took": 3962,
    "responses": [
      {
        "error": {
          "root_cause": [],
          "type": "search_phase_execution_exception",
          "reason": "",
          "phase": "fetch",
          "grouped": true,
          "failed_shards": [],
          "caused_by": {
            "type": "too_many_buckets_exception",
            "reason": "Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.",
            "max_buckets": 10000
          }
        },
        "status": 503
      }
    ],
    "$$config": {
      "method": "POST",
      "url": "api/datasources/proxy/53/_msearch?max_concurrent_shard_requests=5",
      "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":[\"*\"]}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"1580750742494\",\"lte\":\"1580754342494\",\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"observer.type:\\\"apm-server\\\" AND service.environment: \\\"prod\\\" AND service.name: \\\"demand-ap\\\"\"}}]}},\"aggs\":{\"3\":{\"terms\":{\"field\":\"transaction.name\",\"size\":10,\"order\":{\"_key\":\"desc\"},\"min_doc_count\":1},\"aggs\":{\"2\":{\"date_histogram\":{\"interval\":\"2s\",\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":\"1580750742494\",\"max\":\"1580754342494\"},\"format\":\"epoch_millis\"},\"aggs\":{\"1\":{\"percentiles\":{\"field\":\"transaction.duration.us\",\"percents\":[\"50\",\"75\",\"95\",\"99\"]}}}}}}}}\n"
    }
  }
}`

**Comment by marefr** [comment] 2020-02-04 09:01
Duplicate of #17327

**Closed by marefr** 2020-02-04 09:01 UTC
Labels: datasource/Elasticsearch, needs more detail

**Comment by aarvee11** [comment] 2023-06-16 13:26
Run the following command on your elasticsearch server. Please replace `127.0.0.1` with your elastic endpoint and also add auth if applies accordingly

`curl -XPUT http://127.0.0.1:9200/_cluster/settings -d '{"persistent":{ "search.max_buckets": 200000}}'`
