### ISSUE TITLE
Login: Grafana Login Popup Message Does Not State Account Was Blocked

### ISSUE THREAD

**Issue by ThePieMonster** [grafana/grafana#43531] opened 2021-12-26 21:35 UTC
**What happened**:
Failed login on Grafana, popup message saying username or password is incorrect.

**What you expected to happen**:
In the logs, the server shows that the account was blocked, but the login message still shows the same error message.

**How to reproduce it (as minimally and precisely as possible)**:
Fail a login 5 times.

**Anything else we need to know?**:
The popup should show that the account was blocked, just as the logs show the account was blocked.

**Environment**:
- Grafana version: 8.3.3

**Comment by zuchka** [comment] 2021-12-28 00:33
Thanks for creating this issue, @ThePieMonster 

I'm guessing this is the error message you got:

`
001-grafana-1     | t=2021-12-28T00:24:20+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=1 uname= error="too many consecutive incorrect login attempts for user - login for user temporarily blocked"
`

I did not see this message in the browser console or network tab either.

**Comment by ThePieMonster** [comment] 2021-12-28 04:00
> Thanks for creating this issue, @ThePieMonster
> 
> I'm guessing this is the error message you got:
> 
> `001-grafana-1 | t=2021-12-28T00:24:20+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=1 uname= error="too many consecutive incorrect login attempts for user - login for user temporarily blocked"`
> 
> I did not see this message in the browser console or network tab either.

Yes that is the correct message that would show in the log file on the Grafana server.

**Comment by axelavargas** [comment] 2022-01-12 09:39
I am moving this issue into the backend squad, I have tried an approach to solve it, but I am lacking some security context that is important to avoid security incidents.

**Comment by marefr** [comment] 2022-01-18 11:35
Duplicate of #30161

**Closed by marefr** 2022-01-18 11:35 UTC
Labels: type/bug, type/ux, area/frontend/login
