### ISSUE TITLE
Choosing *default* retention policy in Query builder doesn't work

### ISSUE THREAD

**Issue by waldauf** [grafana/grafana#12575] opened 2018-07-11 11:28 UTC
Please include this information:
### What Grafana version are you using?
v5.1.2

### What datasource are you using?
Influxdb-Version: 1.3.6

### What OS are you running grafana on?
Docker container - don't have access in

### What did you do?
My retention policy in InfluxDB:
```
> show retention policies
name	duration	shardGroupDuration	replicaN	default
autogen	0s		168h0m0s		1		true
default	0s		168h0m0s		1		false
```
In Grafana I choose my query and want to set policy to _default._ Both policies are shown in the dropdown inside the query builder. I choose _default_ but query doesn't work. It works just in case I switch to command line and type it directly ("default"."metrics").

### What was the expected result?
Display values from query.

### What happened instead?
Nothing - in graph I see N/A.

### If related to metric query / data viz:
My query is very simple:
`SELECT mean("value") FROM "default"."cpu/usage_rate" WHERE ("type" = 'pod' AND "pod_name" =~ /^$name/ AND "namespace_name" =~ /^$ns$/) AND $timeFilter GROUP BY time($__interval), "pod_name", "namespace_name" fill(null)`

### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
If I choose _default_ RP in Raw Network Request is:
`http://cn38x095.sos.kb.cz:3002/api/datasources/proxy/4/query?db=dbinf003&q=SELECT%20mean(%22value%22)%20FROM%20%22cpu%2Fusage_rate%22%20WHERE%20(%22type%22%20%3D%20%27pod%27%20AND%20%22pod_name%22%20%3D~%20%2F%5Eheapster-v1%5C.2%5C.0-2953545580-n4tb0%2F%20AND%20%22namespace_name%22%20%3D~%20%2F%5Ekube-system%24%2F)%20AND%20time%20%3E%3D%20now()%20-%201h%20GROUP%20BY%20time(1m)%2C%20%22pod_name%22%2C%20%22namespace_name%22%20fill(null)&epoch=ms`
Answer: `{"results":[{"statement_id":0}]}`

If I choose _autogen_ RP in Raw Network Request is:
`http://cn38x095.sos.kb.cz:3002/api/datasources/proxy/4/query?db=dbinf003&q=SELECT%20mean(%22value%22)%20FROM%20%22autogen%22.%22cpu%2Fusage_rate%22%20WHERE%20(%22type%22%20%3D%20%27pod%27%20AND%20%22pod_name%22%20%3D~%20%2F%5Eheapster-v1%5C.2%5C.0-2953545580-n4tb0%2F%20AND%20%22namespace_name%22%20%3D~%20%2F%5Ekube-system%24%2F)%20AND%20time%20%3E%3D%20now()%20-%201h%20GROUP%20BY%20time(1m)%2C%20%22pod_name%22%2C%20%22namespace_name%22%20fill(null)&epoch=ms`
Answer: `{"results":[{"statement_id":0}]}`

What I suspect to be in request (and it works):
`http://cn38x095.sos.kb.cz:3002/api/datasources/proxy/4/query?db=dbinf003&q=SELECT%20mean(%22value%22)%20FROM%20%22default%22.%22cpu%2Fusage_rate%22%20WHERE%20(%22type%22%20%3D%20%27pod%27%20AND%20%22pod_name%22%20%3D~%20%2F%5Eheapster-v1%5C.2%5C.0-2953545580-n4tb0%2F%20AND%20%22namespace_name%22%20%3D~%20%2F%5Ekube-system%24%2F)%20AND%20time%20%3E%3D%20now()%20-%201h%20GROUP%20BY%20time(1m)%2C%20%22pod_name%22%2C%20%22namespace_name%22%20fill(null)&epoch=ms`
Answer: `{"results":[{"statement_id":0,"series":[{"name":"cpu/usage_rate","tags":{"namespace_name":"kube-system","pod_name":"heapster-v1.2.0-2953545580-n4tb0"},"columns":["time","mean"],"values":[[1531304580000,null],[1531304640000,27],...}`

**Comment by alexanderzobnin** [comment] 2018-07-12 10:07
Seems, it's a duplicate of #4347.

**Closed** 2018-07-12 10:07 UTC
Labels: type: duplicate
