### ISSUE TITLE
api parameter evalMatches data is cached

### ISSUE THREAD

**Issue by sgblv** [grafana/grafana#33776] opened 2021-05-06 12:08 UTC
According documentation:

` “evalMatches” data is cached in the db when and only when the state of the alert changes (e.g. transitioning from “ok” to “alerting” state).

If data from one server triggers the alert first and, before that server is seen leaving alerting state, a second server also enters a state that would trigger the alert, the second server will not be visible in “evalMatches” data.

`
It is not desired behaviour, because third party integrations may rely on this data. As a workaround I have to use pause/unpause api call, but it break native grafana notifications (recovery messages). 

Is it possible to swich off this cache or make it tunable?

**Comment by marefr** [comment] 2021-05-10 08:18
Duplicate of #6041

**Closed by marefr** 2021-05-10 08:18 UTC
