### ISSUE TITLE
Condition "has no value" under grafana 4 not working

### ISSUE THREAD

**Issue by ankitg1989** [grafana/grafana#6654] opened 2016-11-21 16:40 UTC
* **I'm submitting a ...**
Issue

Grafana 4 beta release

getting "Validation failed Evaluator invalid evaluator type: no_value" error while using "has no value" condition in alerts.

![grafana 4](https://cloud.githubusercontent.com/assets/20354406/20491379/35d90170-b037-11e6-831a-7d0f35adf427.PNG)

**Comment by bergquist** [comment] 2016-11-22 09:38
dupe of #6631

**Closed by bergquist** 2016-11-22 09:38 UTC
