### ISSUE TITLE
Calculation of duration in state timeline is broken

### ISSUE THREAD

**Issue by hudeldudel** [grafana/grafana#45640] opened 2022-02-19 16:23 UTC
**What happened**:
Duration on mouse over in state timeline shows wrong duration.
See also: https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?orgId=1&viewPanel=63

**What you expected to happen**:
Correct values for duration in state timeline mouse overs.

**How to reproduce it (as minimally and precisely as possible)**:
Install v8.4.0 or v8.4.1, open a dashboard with state timeline, place curser over diagram, check duration field.

**Anything else we need to know?**:
It did work in versions < 8.4

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: prometheus 2.33.1
- OS Grafana is installed on: docker / raspbian 64 bit
- User OS & Browser: macOS Monterery, Chrome 98.0.4758.102
- Grafana plugins: default
- Others: -

**Comment by the02** [comment] 2022-02-21 09:30
It seems to show the $__interval or $__rate_interval instead of the correct duration of the state.

**Comment by torkelo** [comment] 2022-02-21 14:21
I can confirm this with just a simple test here: https://play.grafana.org/d/_IdYmJB7z/state-timeline-tooltip-duration?orgId=1 

@leeoniya I have tried to track down what change caused this but without any success. The issue is that findNextStateIndex always returns the next data point index, but the data is before values have been merged, so if you have data points every 10m say but with merge values enabled you get bigger blocks but the duration in the tooltip will always just say 10m 
https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/state-timeline/StateTimelineTooltip.tsx#L40

Did we change how merge values worked or any idea what change could have had this side effect?

**Comment by leeoniya** [comment] 2022-02-21 14:48
probably regressed by https://github.com/grafana/grafana/pull/44811

we used to fill all same consecutive values with `undefined` in the data, but now leave the data alone and handle consecutive same comparison in the renderer.

so this likely breaks out on first loop:

https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/state-timeline/utils.ts#L556

it should be changed to compare against the initial state value.

**Comment by codeincarnate** [comment] 2022-02-27 22:41
So in taking a look at this I think the problem actually is in `findNextStateIndex`. When "merge consecutive values" is selected it will return the initial index rather than the index of the last consecutive segment so interim segments are left out of the duration calculation. 

Thinking of making `findNextStateIndex` aware of this setting.

**Closed** 2022-02-28 20:16 UTC
Labels: type/bug, type/regression, area/panel/state-timeline
