### ISSUE TITLE
Can't create alert with variable data source

### ISSUE THREAD

**Issue by tobiasrondin-knowit** [grafana/grafana#20994] opened 2019-12-10 11:26 UTC
**What happened**:
An error message is shown when trying to set up an alert rule with a variable as data source
![image](https://user-images.githubusercontent.com/51230363/70525326-60ddd480-1b47-11ea-9981-dd3f53e74401.png)
```
Validation failed
Alert validation error: Data source used by alert rule not found, alertName=$frontend alert, datasource=$frontend
```

**What you expected to happen**:
The alert rule working

**How to reproduce it (as minimally and precisely as possible)**:
Create a data source variable
Try to set up an alert rule in a panel using the variable as data source

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Linux
- User OS & Browser: Windows, Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2019-12-10 13:54
Duplicate of #6557

**Closed by marefr** 2019-12-10 13:54 UTC
