### ISSUE TITLE
Explore datasources from datasource list

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#13736] opened 2018-10-18 08:52 UTC
When viewing the list of configured datasources, it would be great to have a button on each (that supports Explore) to jump to Explore of that datasource.

**Comment by torkelo** [comment] 2018-10-18 10:44
related issue: https://github.com/grafana/grafana/issues/13546

**Comment by ivanahuckova** [comment] 2020-11-11 12:24
/duplicate of https://github.com/grafana/grafana/issues/19348

**Closed by ivanahuckova** 2020-11-11 12:24 UTC
Labels: state/ux-mockups-needed, type/ux
