### ISSUE TITLE
Grafana 7.4.2 - ${resource.label.instance_id} variable's value is not substituted in the [OK] message

### ISSUE THREAD

**Issue by dgdevops** [grafana/grafana#31522] opened 2021-02-26 17:44 UTC
**What happened**:
The [Alerting] Grafana emails have the value of ${resource.label.instance_id} variable, however in the [OK] emails only the variable is seen without it's actual value.

**What you expected to happen**:
Expected to see the actual value of the variable in the [OK] emails as well.

**How to reproduce it (as minimally and precisely as possible)**:
1) Upgrade Grafana to v7.4.2
2) Add a GCP stackdriver datasource
3) Create a query (Redis metric) and use Group By "resource.label.instance_id" expression
4) Create an alert with a name that contains "${resource.label.instance_id}" (example: Alert - ${resource.label.instance_id})
5) Trigger it and wait for the email alert
     (example: [Alerting] Memory usage alert - projects/XY/locations/XY/instances/XY)
6) Adjust the alert threshold to make sure the alert clears and wait for the OK email and check its's subject
     (example: [OK] Memory usage alert - ${resource.label.instance_id})

**Example [Alerting] email** (with confidential information removed):
![ALERT-email](https://user-images.githubusercontent.com/61938162/109335221-0c189d80-7862-11eb-81e1-5670af18ebe3.PNG)

**Example [OK] email**:
![OK-email](https://user-images.githubusercontent.com/61938162/109334221-c0192900-7860-11eb-9e95-63b99818a78b.PNG)

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: Stackdriver
- OS Grafana is installed on: k8s
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by rgroenewoudt** [comment] 2021-03-11 07:40
I have the same issue with an InfluxDb datasource.

**Comment by marefr** [comment] 2021-03-25 20:41
Duplicate of #30606

**Closed by marefr** 2021-03-25 20:41 UTC
Labels: area/alerting, datasource/GoogleCloudMonitoring, type/bug
