### ISSUE TITLE
Limit timeframe per dashboard

### ISSUE THREAD

**Issue by oded-dd** [grafana/grafana#19258] opened 2019-09-20 10:57 UTC
**What would you like to be added**:
Grafana should support the ability to limit the timeframe per dashboard (e.g. 24hours, 2days, 7 days, 14days, etc...)

**Why is this needed**:
It should help companies achieve three goals:
* Reduce the queries done by grafana to datastores like Prometheus, elasticsearch, etc... by that reducing the organization monitoring system memory usage (and caching)
* Different dashboards have different timeframe requirements (Affects SLO)

* Avoid circuit breaker and time waiting for Grafana result to fail

**Comment by torkelo** [comment] 2019-09-20 12:27
dupe of https://github.com/grafana/grafana/issues/4288

**Closed by torkelo** 2019-09-20 12:27 UTC
