### ISSUE TITLE
8.3.3: Samsung Smart Signage is unable to open Grafana

### ISSUE THREAD

**Issue by jhfin** [grafana/grafana#43452] opened 2021-12-22 09:32 UTC
I have Samsung Smart Signage QB13R-T info display that I have been using to show Grafana for some time. After upgrading to Grafana 8.3.3 (from something like 6.x) I'm getting: "... Grafana has failed to load its application files"

I tried updating the display to the newest firmware (2320.0) with no help.

Is there something I can do to help you making this work again? I assume this is a Tizen brower and many other users also with the same problem.

**Comment by zuchka** [comment] 2021-12-22 23:22
> to Grafana 8.3.3 (from something like 6.x) 

that's a big jump

> yes. searching for "samsung" among old issues and forum topics returns a lot:
- https://community.grafana.com/search?expanded=true&q=samsung

closing this as a duplicate of https://github.com/grafana/grafana/issues/25507

please comment on that thread with your info 👍

**Comment by thisisobate** [comment] 2022-01-05 09:54
@jhfin It seems Samsung Smart Signage isn't supported in later versions of Grafana. You can take a look at the list of supported web browsers [here](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers)

**Comment by jhfin** [comment] 2022-01-05 10:00
As I wrote to #25507, this particular device is using Chromium based browser. The problem is that it is version 56 from 2017. I would be delighted if there would be a way of telling Grafana to use some sort of compability mode to support such an old browser (like Grafana 6.x did). But I guess Grafana 8.x is using some of the features not available with Chromium 56 (More details on the browser capabilities can be found here https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html).

**Comment by ashharrison90** [comment] 2022-01-06 10:27
@jhfin as you noted that's an extremely old version of a chromium browser. 😬 

we only ever claim support for the latest versions of the major browsers. in order to keep improving grafana, we need to take advantage of newer and better web APIs. it's not scalable for us to continue to maintain compatibility with browsers that are now 5 years out of date.

recommendation would probably be to either:
- switch to a setup where you have control of the browser (raspberry pi or something similar)
- continue to use an older version of grafana

appreciate that's probably not the answer you're after, but i'm sure you can understand.

**Closed by ashharrison90** 2022-01-06 10:27 UTC
Labels: needs investigation, type/browser-compatability
