### ISSUE TITLE
panel menu not editable

### ISSUE THREAD

**Issue by bigHave** [grafana/grafana#32202] opened 2021-03-22 07:24 UTC
**What happened**:
panel menu not editable
![image](https://user-images.githubusercontent.com/9249583/111953459-9b436900-8b21-11eb-9dff-a7019f3bcf24.png)

with Chrome, this panel control menu became not editable(click but not response). with safari, everything works fine.

**How to reproduce it (as minimally and precisely as possible)**:
this is a irregular issue, some people in our team works just fine with chrome, while others reproduce the situation above. we all have the same permission.

**Environment**:
- Grafana version: v6.7.4
- Data source type & version: prometheus 2.19.2
- OS Grafana is installed on: debian
- User OS & Browser: mac, chrome

**Comment by torkelo** [comment] 2021-03-22 07:36
dupe of https://github.com/grafana/grafana/issues/31374 

try updating to latest v7.4

**Closed by torkelo** 2021-03-22 07:36 UTC
