### ISSUE TITLE
Environment variables not working when provisioning Contact Points 

### ISSUE THREAD

**Issue by degisftw** [grafana/grafana#56437] opened 2022-10-06 07:24 UTC
**What happened**:
I try to provision a Contact Point for Slack and want to put the webhook URL as an ENV because I don't want to store it in plain text in my repo. But I guess Grafana just reads the variable as a string throwing this error
`Failed to send test alert.: Post "$%7BSLACKWEBHOOK%7D": unsupported protocol scheme ""
`

**What you expected to happen**:
Grafana using the URL from the ENV

**How to reproduce it (as minimally and precisely as possible)**:
In the monitoring namespace I have a secret called grafana-notifications-secrets that holds data for SLACKWEBHOOK. I have verified in the pod that SLACKWEBHOOK is there and has the correct value.
 
This is from my config file
```
envFromSecrets: 
  - name: grafana-notifications-secrets
alerting:
  contactpoints.yaml: |
    apiVersion: 1
    contactPoints:
    - orgId: 1
      name: slack-notification-channel
      receivers:
      - uid: slack1
         type: slack
         settings:
          url: $SLACKWEBHOOK
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: Contact Point
- OS Grafana is installed on: Kubernetes 1.23
- User OS & Browser:
- Grafana plugins:
- Others:

UPDATE:
There is no difference between "$SLACKWEBHOOK" and "${SLACKWEBHOOK}". Same behaviour

**Comment by zuchka** [comment] 2022-10-06 22:11
also: this looks like a duplicate of this issue: one or the other could probably get closed:

https://github.com/grafana/grafana/issues/53315

**Comment by zuchka** [comment] 2022-10-06 22:16
actually there is a better issue. There is a fix for this. It will be in 9.2.0 and 9.1.7:

https://github.com/grafana/grafana/issues/54984#issuecomment-1256021518

https://github.com/grafana/grafana/pull/55666

**Closed by zuchka** 2022-10-06 22:16 UTC
Labels: area/alerting, area/alerting/notifications
