### ISSUE TITLE
pie chart memory leak

### ISSUE THREAD

**Issue by qwertymol** [grafana/grafana#31540] opened 2021-03-01 09:16 UTC
**What happened**: 
Slow but stable increasing memory use.

**What you expected to happen**:
No memory leak.

**How to reproduce it (as minimally and precisely as possible)**:
Create dashboard and append piechart panel. On every dashboard update it will bind event "ontouchend" on document.
![изображение](https://user-images.githubusercontent.com/12717927/109475447-c852ad80-7a86-11eb-87ef-3dffbc0fb22c.png)
![изображение](https://user-images.githubusercontent.com/12717927/109475388-b3761a00-7a86-11eb-853a-5fe5e749aa5a.png)

**Anything else we need to know?**:
Seems like binded events will never unbind. After some time of code discover, I found event 'PanelEvents.panelTeardown" that must be destroy previous plot object, but it will never raised.
Sorry for bad english (not my native).

**Environment**:
- Grafana version: 7.4.1
- OS Grafana is installed on: Windows 64bit
- User OS & Browser: Windows 64bit
- Grafana plugins: grafana-piechart-panel 1.3.9

**Comment by torkelo** [comment] 2021-03-01 12:23
duplicate of https://github.com/grafana/piechart-panel/issues/259 

We are coming out with a new core pie chart plugin in 7.5

**Closed by torkelo** 2021-03-01 12:23 UTC
Labels: type/bug
