### ISSUE TITLE
Azure AD Oauth - User loses organizations after new login

### ISSUE THREAD

**Issue by joevanmaldegiam** [grafana/grafana#47451] opened 2022-04-07 13:46 UTC
**What happened**:
I have Azure AD oauth setup with role assignments and multiple organizations.  When a user signs out or signs in from a new browser all of their organizations are removed.

**What you expected to happen**: I expected organizations to remain through different sessions/

**How to reproduce it (as minimally and precisely as possible)**:
- Add user to organizations
- Confirm user can switch organizations
- Sign out
- Sign in via Oauth
- Cannot switch organizations

**Anything else we need to know?**:
I found that if I use the Generic Oauth provider in Grafana that this scenario doesnt happen which leads me to believe it's a bug.

**Environment**:
- Grafana version: 8.5.5
- Data source type & version: N/A
- OS Grafana is installed on: Server 2016
- User OS & Browser: Windows 10, Chrome, Edge. Firefox
- Grafana plugins: N/A
- Others:

Azure AD Oauth Config
[auth.azuread]
name = Unified Login
enabled = false
allow_sign_up = false
client_id = MY-Client-ID
client_secret = supersecret
scopes = openid email profile
auth_url = https://login.microsoftonline.com/My-Tenant-ID/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/My-Tenant-ID/oauth2/v2.0/token
allowed_domains = mydomain.com
allowed_groups =

Generic Oauth Config
[auth.generic_oauth]
name = Azure AD Login
enabled = true
allow_sign_up = false
client_id = CLIENT-ID
client_secret = supersecret
scopes = openid email profile
empty_scopes = false
email_attribute_name = email:primary
email_attribute_path =
login_attribute_path =
name_attribute_path =
role_attribute_path =
role_attribute_strict = false
groups_attribute_path =
id_token_attribute_name =
team_ids_attribute_path =
auth_url = https://login.microsoftonline.com/TENANT/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/TENANT/oauth2/v2.0/token
api_url =
teams_url =
allowed_domains = mydomain.com
team_ids =
allowed_organizations =
tls_skip_verify_insecure = false
tls_client_cert =
tls_client_key =
tls_client_ca =
use_pkce = false

**Comment by stefanpetter** [comment] 2022-05-04 11:21
Hi @joevanmaldegiam 

This is by design. You can disable this behaviour by adding the following line to you config file: 

```
# Skip forced assignment of OrgID 1 or 'auto_assign_org_id' for social logins
oauth_skip_org_role_update_sync = true
```

Hope this works for you as well!

**Comment by despian** [comment] 2022-05-09 15:56
> ```
> # Skip forced assignment of OrgID 1 or 'auto_assign_org_id' for social logins
> oauth_skip_org_role_update_sync = true
> ```

@stefanpetter what happens when a user logs in for the first time with this setting? Do they just get default access to the default org?

I'm looking for a way to grant OAuth users access to all orgs based on the assigned permission within the Azure AD app registration.

**Comment by Jguer** [comment] 2022-08-09 09:04
> what happens when a user logs in for the first time with this setting? Do they just get default access to the default org?

https://github.com/grafana/grafana/blob/main/pkg/api/login_oauth.go#L275 Seems they get no org membership unless they already exist in the system. (https://github.com/grafana/grafana/issues/22605 more details probably here) 

> I'm looking for a way to grant OAuth users access to all orgs based on the assigned permission within the Azure AD app registration.

This is currently not supported, there's an open discussion here https://github.com/grafana/grafana/discussions/39102

**Comment by despian** [comment] 2022-08-09 09:24
@Jguer thanks for the response.

We ended up making a little tool to sync org membership based on assigned roles in the AAD app.

**Comment by Jguer** [comment] 2022-09-05 15:02
Closing this issue for now, `oauth_skip_org_role_update_sync` should cover this use case for now

**Closed by Jguer** 2022-09-05 15:02 UTC
Labels: area/auth/oauth
