### ISSUE TITLE
Export dashboards in a folder together, rather than doing it individually.

### ISSUE THREAD

**Issue by GokulSNarayan** [grafana/grafana#26047] opened 2020-07-03 09:50 UTC
**What would you like to be added**: I would like to have a feature where you can export many dashboards as a zip and import many dashboards rather than importing them individually.

**Why is this needed**: When I am working with many dashboards in grafana it takes time to export and import each one of them separately. Thus having a feature like this would be really great.

**Comment by papagian** [comment] 2020-07-03 13:47
Duplicate of #936

**Closed by papagian** 2020-07-03 13:47 UTC
Labels: type/duplicate
