### ISSUE TITLE
Blocking from brute-force attacks is missing on Grafana login form

### ISSUE THREAD

**Issue by sysboy** [grafana/grafana#20551] opened 2019-11-21 10:07 UTC
Attacker can perform user/password brute-force attack and attacker account is never get locked after failed attempts.

**What happened**: This was picked up by our penetration testers. They marked the severity as **Low**.

**What you expected to happen**: One of the way to perform the remediation of the issue is to perform soft lock of the user after defined (e.g 3 or 5) number of consecutive failed login attempts. Captcha could be a solution too.

**How to reproduce it (as minimally and precisely as possible)**:
1) goto https://grafana/login
2) Perform multiple login attempts with invalid credentials 
3) Note that user is NOT locked

**Anything else we need to know?**:

**Environment**: Linux
- Grafana version: v6.4.2 
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2019-11-21 11:13
Duplicate of #12836

**Comment by marefr** [comment] 2019-11-21 11:14
Brute force feature currently only work if you enter wrong password for an existing user.

**Closed by marefr** 2019-11-21 11:13 UTC
