### ISSUE TITLE
minimum refresh interval blocks JSON model "save"

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#27327] opened 2020-09-02 08:49 UTC
**What happened**:
If a config is pasted into JSON model which has a refresh less than the minimum, the save is not allowed.

**What you expected to happen**:
The refresh is adjusted to the allowed minimum.

along the lines of bugs #25717 and #23099 already fixed

**How to reproduce it (as minimally and precisely as possible)**:
1. open Settings / JSON model
2. paste model having refresh less than minimum
3. attempt "Save changes"

**Environment**:
- Grafana version: 7.1.4

**Comment by hugohaggmark** [comment] 2020-09-02 09:43
Thanks for reporting this @belm0, I'm having issues trying to paste whatever change I make in the original JSON.

**Comment by belm0** [comment] 2020-09-07 01:23
To reproduce it just edit the refresh of the existing model source.

**Comment by hugohaggmark** [comment] 2021-03-10 07:27
I can't reproduce this in Grafana v7.5.0-pre (04e46e3853) so I'm going to close this issue now. We can always reopen the issue if there is new evidence pointing to it. Thank you for taking the time to write this @belm0.

**Closed by hugohaggmark** 2021-03-10 07:27 UTC
Labels: area/dashboard/import, needs investigation, type/bug
