### ISSUE TITLE
Time regions only show if the start of the time region falls within the current time range

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#28017] opened 2020-10-03 08:54 UTC
**How to reproduce it (as minimally and precisely as possible)**:

I have a graph setup with 2 time ranges:
* 21:00 to 07:00, blue
* 07:00 to 21:00, yellow

When looking at the graph this morning I noticed that the blue section was missing. It only started to show once I increase the time range of the graph so that it would include 21:00 last night.

I expected the areas to always be coloured, regardless of if the start point of a region is within the current time range or not.

![Screenshot from 2020-10-03 10-51-19](https://user-images.githubusercontent.com/569574/94987419-dc38c880-0555-11eb-93b2-7a6ad51b587c.png)
![Screenshot from 2020-10-03 10-51-36](https://user-images.githubusercontent.com/569574/94987423-df33b900-0555-11eb-8d4f-cd5fbdc86667.png)
![Screenshot from 2020-10-03 10-51-51](https://user-images.githubusercontent.com/569574/94987429-e22ea980-0555-11eb-9d52-fade14e53f06.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Prometheus, 2.11
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Linux, Firefox
- Grafana plugins: world-map

**Comment by daenney** [comment] 2020-10-03 08:59
Hmm actually, it seems the blue section starts to show up once the time range goes past last midnight. So if I do `now-8h` I don't get the blue region, but `now-9h` I do, which includes midnight UTC.

**Comment by ashharrison90** [comment] 2021-08-09 14:53
Duplicate of #15010

**Closed by ashharrison90** 2021-08-09 14:53 UTC
Labels: area/panel/graph, area/frontend
