### ISSUE TITLE
interval_year not working anymore

### ISSUE THREAD

**Issue by YetAnotherGerrit** [grafana/grafana#82334] opened 2024-02-12 21:34 UTC
### What happened?

Since the update to 10.3 the `date_formats`-setting `interval_year` is not working anymore. Intervals of "`1y`" are always displayed in `YYYY-MM-DD HH:MM`.

### What did you expect to happen?

Still displaying of the year in my charts, when using `interval_year=YYYY`.

### Did this work before?

Yes, before the update to 10.3, in the latest 10.2.x-version.

### How do we reproduce it?

1. Add a elasticsearch-datasource.
2. Create a visualization of the Time series or bar chart-type.
3. Change interval from "auto" to "1y"

### Environment (with versions)?

Grafana: 10.3
OS: any
Browser: any

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Elasticsearch 7.17.x

**Comment by ivanahuckova** [comment] 2024-05-10 13:55
Hello @YetAnotherGerrit thank you for reporting the issue! I was able to reproduce this on mentioned version, but it seems to be fixed in incoming v 11.0.0 - I could not reproduced on https://github.com/grafana/grafana/tree/v11.0.0-preview. This doesn't seem to be related to Elasticsearch data source, but rather visualisations. 

I am going to close the issue, as it resolved on main and will be fixed in next release.

**Closed by ivanahuckova** 2024-05-10 13:55 UTC
Labels: datasource/Elasticsearch, needs investigation, area/panel/timeseries
