### ISSUE TITLE
iOS Login Button unresponsive

### ISSUE THREAD

**Issue by carpii** [grafana/grafana#12133] opened 2018-06-01 23:34 UTC
Grafana v5.1.3 (commit: 087143285)
iPad iOS 11.2.5

I'm hosting Grafana locally on my LAN. 
When attempting to login using Chrome on iOS, the login button is completely unresponsive (no network activity at all, the button is just not registering the click/touch)
This has been the case since I installed Grafana 6 months ago (so would include older versions of Chrome and Grafana too)

Logging in via Safari on iOS works fine, likewise with all desktop browsers

**Comment by marefr** [comment] 2018-06-04 07:51
Just tried this on iOS 11.2.1 and Chrome and was not able to reproduce for https://play.grafana.org/login. Even if don't have any username/password entered I can click the login button.

Will close this. @carpii if you have more specific details/screenshots I'll consider re-opining this.

**Comment by flopp999** [comment] 2018-06-04 08:17
I have attached a print screen when using Chrome in iOS 11.4
Login is not orange
![img_e6014](https://user-images.githubusercontent.com/21694965/40906214-73186f78-67e0-11e8-8488-6f9e2dfaec13.JPG)

**Comment by carpii** [comment] 2018-06-04 08:45
@flopp999 good catch. I see the same effect.. removing a character from username and retyping it allows me to log in, thanks

It looks like it may be chromes login auto-complete, which the login form isn't detecting

**Comment by marefr** [comment] 2018-06-04 08:54
Thanks for that extra information

**Comment by jschill** [comment] 2019-01-16 10:38
> It looks like it may be chromes login auto-complete, which the login form isn't detecting

Correct - this is an issue with Chrome on iOS using auto-complete. There's no event fired when using the auto-complete.
Bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=895898

Will try to add a workaround.

**Comment by jschill** [comment] 2019-01-16 14:23
I have added a potential fix, but it needs to be verified.

**Closed** 2019-01-17 17:41 UTC
Labels: comp: frontend, type: bug

**Comment by volschin** [comment] 2020-01-21 06:32
This Problem Seemann to be back with grafana 6.5.3 under iOS 13.3 with chrome.

**Comment by marefr** [comment] 2020-01-21 11:09
@volschin would recommend to open a new bug report and possibly reference this issue. Thanks

**Comment by hugohaggmark** [comment] 2020-02-17 05:50
Filed again 5 days ago https://bugs.chromium.org/p/chromium/issues/detail?id=1051132
