### ISSUE TITLE
Alerting (unified + postgresql backend): SQL error when updating rule group

### ISSUE THREAD

**Issue by rechtem** [grafana/grafana#55741] opened 2022-09-26 12:11 UTC
Grafana is configured to use a PostgreSQL database ([database] in grafana.ini).

Trying to update the rule group of an existing alert produces an error:

_Failed to save rule: failed to update rule group: failed to query database for a group of alert rules: pq: entrée manquante de la clause FROM pour la table « a »_

Postgres log shows the offending query:

```
SELECT A.* FROM "alert_rule" AS "A" INNER JOIN alert_rule AS B ON A.org_id = B.org_id AND A.namespace_uid = B.namespace_uid AND A.rule_group = B.rule_group AND B.uid = "gmVYOy74z" WHERE (A.org_id = 1);
ERREUR:  entrée manquante de la clause FROM pour la table « a »
LIGNE 1 : ..."alert_rule" AS "A" INNER JOIN alert_rule AS B ON A.org_id =...
                                                               ^
```

The problem is that alias is set to "A"  at the beginning of the query, and referred to A later.

- Grafana version: 9.1.5

**Comment by grobinson-grafana** [comment] 2022-09-30 09:44
Thanks for opening this issue! This looks like a duplicate of https://github.com/grafana/grafana/issues/55901 and so I will close this issue in favour of https://github.com/grafana/grafana/issues/55901.

**Closed by grobinson-grafana** 2022-09-30 09:44 UTC
Labels: area/alerting
