### ISSUE TITLE
Would like to be able to display $__from and $__to in a readable format

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#24455] opened 2020-05-08 20:22 UTC
**What would you like to be added**:  We have queries that are displayed in a table.  In the panel title it would be very helpful to display one or both of the time range values $__from and $__to.  You can do that today but it is seconds from epoch.  It would be very nice if there was a function that you could apply to display it in "YYYY-MM-DD hh:mm::ss" format.

**Why is this needed**:  This will help the user clearly understand the time range used in the query.  In some cases we are interested in single timestamp and having that clearly displayed is very important.

**Comment by torkelo** [comment] 2020-05-10 08:40
duplicate of https://github.com/grafana/grafana/issues/19265

**Closed by torkelo** 2020-05-10 08:40 UTC
