### ISSUE TITLE
Missing check if a protocol (http://) was added to database field in datasource

### ISSUE THREAD

**Issue by morlie** [grafana/grafana#25259] opened 2020-06-01 10:14 UTC
**What happened**:
I got error message when an alert should be fired. 

[https://community.grafana.com/t/grafana-7-alerting-issue-error-tsdb-handlerequest-unsupported-protocol-scheme-influxdb/31226](url)

Sample of error message:
lvl=eror msg=“Alert Rule Result Error” logger=alerting.evalContext ruleId=3 name=“CPU Load alert” error=“tsdb.HandleRequest() error Get “influxdb:8086?db=telegraf&epoch=s&q=SELECT+mean%28%22ssCpuIdle%22%29+%2A-1+%2B100+FROM+%22snmp.SYNO%22+WHERE+%22agent_host%22+%3D+%27192.168.0.28%27+AND+time+%3E+now%28%29±+5m+GROUP+BY+time%28200ms%29%2C+%22laNames%22”: unsupported protocol scheme “influxdb”” changing state to=alerting

In the meanwhile I found that I missed the protocol in the datasource definition. I didn't add http:// in front of the server. The connection test itself was successfully and also all graphs are working.

**What you expected to happen**:
Error message (or warning) when a host is added without a protocol. This I think is the easiest way to prevent the issue. Alternatively accept host without http:// in the alerting module. 

It was my mistake, but it could happen to other users as well. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a datasource influxdb without leading http:// ..
create dashboard with alert
test alert

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.01
- Data source type & version: Influxdb
- OS Grafana is installed on: Docker (latest image)
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: N/A
- Others:

**Comment by aknuds1** [comment] 2020-06-01 11:53
Looks like a duplicate of #25242, although the error you get is different. You're sure you don't get a "nil pointer dereference" error in your logs?

**Comment by morlie** [comment] 2020-06-01 12:39
that's easy to explain ... could re-produce it. Once I enter the IP I get the null-pointer exception. When I enter the hostname my reported error is shown. Then the exception handling works better at least.

Source of issue is identical. You can merge my topic into the mentioned case. It's OK to mark as duplicate.

**Comment by aknuds1** [comment] 2020-06-01 13:16
Closing as duplicate of #25242.

**Closed by aknuds1** 2020-06-01 13:16 UTC
Labels: area/alerting, area/backend, datasource/InfluxDB, needs investigation, type/bug
