### ISSUE TITLE
[Feature request] Use SELECT output for templating variables

### ISSUE THREAD

**Issue by CarusDave** [grafana/grafana#7527] opened 2017-02-10 15:20 UTC
It would be really useful if templating variables could handle the SELECT command for various reasons where InfluxDB SHOW is lacking:

1. Benefits - shortened and time (dashboard) focused list of menu items
    How - extract a selected column that contains a uniquely sorted tag value within the restricted time range

2. Benefits - dynamic hidden variable to be used elsewhere in dashboard with other queries for singlestat math calculations
    How - extract the selected field values and store (first/last/ave/total etc) result as single value

3. Benefits - store full results from query for use as a replacement datasource for multiple panels

Here's a basic mock-up:

![image](https://cloud.githubusercontent.com/assets/20041843/22831542/a213afb6-efa2-11e6-8b11-6cafdc42e386.png)

**Comment by torkelo** [comment] 2017-02-13 10:34
duplicate of  https://github.com/grafana/grafana/issues/5013

**Closed by torkelo** 2017-02-13 10:34 UTC
