### ISSUE TITLE
[Requests] Allow variables in Alerts

### ISSUE THREAD

**Issue by Nuadvocate** [grafana/grafana#20575] opened 2019-11-21 22:34 UTC
Almost 80% of our dashboard utilized variables. Creating alerts will requires users to create more dashboard.

Is it possible if alerts can be more optimized by allowing user to create alerts based on variables combinations...

**Comment by hugohaggmark** [comment] 2019-11-22 04:05
Duplicate of #6557

**Closed by hugohaggmark** 2019-11-22 04:05 UTC
Labels: area/alerting, type/feature-request
