### ISSUE TITLE
[Bug] The macros $__time() and $__timeFilter() behave incorrectly if argument contains parenteses

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#9062] opened 2017-08-19 16:26 UTC
- What Grafana version are you using?

Latest stable version, updated regularly via `apt-get`.

- What datasource are you using?

MySQL

- What OS are you running grafana on?

Linux Mint

- What did you do?

According to the documentation, the macro `$__time(column)` expands to `UNIX_TIMESTAMP(column) as time_sec`. I used `$__time(NOW())`.

- What was the expected result?

The expected result was this to be expanded to `UNIX_TIMESTAMP(NOW()) as time_sec`.

- What happened instead?

It was expanded to `UNIX_TIMESTAMP(column as time_sec)`, which is syntactically wrong and cases errors.

I'm pretty sure the problem is caused by the parenthesis; they aren't parsed correctly by the macro expander. The above was from a real request I used. Just to verify my conjecture, I used `NOW()` also in a `$__timeFilter()` macro, although it makes no sense to use it there. The result was a similar bug.

According to the documentation, `$__timeFilter(column)` expands to `UNIX_TIMESTAMP(time_date_time) ≥ from AND UNIX_TIMESTAMP(time_date_time) ≤ 1492750877`. Well, probably somebody cut-and-pasted there too much; I suspect `1492750877` should be `to` or something like that.

Anyway, when using `$__timeFilter(NOW())`, I would expect that to be expanded to the meaningless bur syntactically correct `NOW() >= UNIX_TIMESTAMP(range_start) AND NOW() <= UNIX_TIMESTAMP(range_end)`. Instead, it is expanded to the syntactically incorrect `NOW( >= FROM_UNIXTIME(range_start) AND NOW( <= FROM_UNIXTIME(range_end))`.

**Comment by bontchev** [comment] 2017-08-19 17:31
As far as I can see, the problem is in the file `grafana/maros.go`, line 12:


```
const sExpr = `\$` + rsIdentifier + `\(([^\)]*)\)`
```

This defines a macro as a dollar sign, followed by an alphanumeric-or-underscores identifier, followed by an opening parenthesis, followed by a sequence of charcters that does not contain a closing parentesis, followed by a closing parenthesis. Presumably, the stuff between the opening and the closing parentesis is supposed to be the argument of the macro. This causes the bug, if the argument contains a closing parenthesis.

I wouldn't be surprised if this bug has security implications, too.

Generally, it is a bad idea to use regular expressions for parsing - you are likely to screw up and screw up badly. Consider writing a proper parser, instead.

**Comment by torkelo** [comment] 2017-08-19 18:35
duplicate of https://github.com/grafana/grafana/issues/8411

**Closed by torkelo** 2017-08-19 18:35 UTC

**Comment by torkelo** [comment] 2017-08-19 18:37
> Generally, it is a bad idea to use regular expressions for parsing - you are likely to screw up and screw up badly. Consider writing a proper parser, instead.

99% of all parsing is done with regex, but I agree for more complex expressions that should support nested elements like the above macros a proper lexer & parser is a better fit. the MySQl data source is labelled alpha :)

**Comment by bontchev** [comment] 2017-08-19 21:51
The problem isn't MySQL; the problem is the macro argument parsing. The macros will have this problem (won't work correctly if the argument contains a closing parenthesis) no matter the data source. It's just that such arguments are more likely to be used when the data source is MySQL.

I don't know Go myself. Is the regex matching there greedy? If it is, a quick fix would be to replace the above line with

```
const sExpr = `\$` + rsIdentifier + `\((.+)\)`
```

This will glob in the group everything between the outermost pair of parentheses, no matter what's inside.

**Comment by torkelo** [comment] 2017-08-20 07:34
I know full well what the problem is, it's as I said in the MySQL datasource code, the MySQL time macros where implemented quickly using regex.
