### ISSUE TITLE
shared crosshair very buggy since 8.0.6

### ISSUE THREAD

**Issue by hibo98** [grafana/grafana#36831] opened 2021-07-16 08:03 UTC
**What happened**:

Since the update to Version 8.0.6 the shared crosshair is very buggy. The Tooltips don't move while the mouse is moving, when the mouse stops then the tooltip moves as expected. 

Thats how it looks: https://drive.google.com/uc?id=1Jn_8GB-2z2YVAazgwYUO6Z9Dlh2zaO_r

**What you expected to happen**:

I expect it to as smooth as It was before and is in Chrome.
https://drive.google.com/uc?id=1OBXdxeUuHFl8P7JW3Ea5xiUYvbHIoSlK

**How to reproduce it (as minimally and precisely as possible)**:

Just setup shared crosshair and two panel of the new times series panels

**Anything else we need to know?**:

As far as I tested this only occurs on Firefox. I tested it on current Release 90.0, Beta 91.0b2 and Nightly 92.0a1 (2021-07-15)

If you want see your self look here: https://grafana.freifunk-dresden.de/d/geeqdF6mk/general-stats

**Environment**:
- Grafana version: v8.0.6
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 9 (upgrade planned)
- User OS & Browser: Windows 10, Firefox 91.0b2
- Grafana plugins: Grafana Image Renderer, PieChart (old)
- Others:

**Comment by zoltanbedi** [comment] 2021-07-16 09:48
This is a duplicate of https://github.com/grafana/grafana/issues/36086

**Comment by hibo98** [comment] 2021-07-16 10:47
I think is issue is a little bit different from what you mentioned. Because it first appeared in 8.0.6, but it was working as expected in 8.0.5. And the linked issue was already present in 8.0.3. The second thing that is different, is that the problem only appears for the shared tooltips, the one right under the mouse cursor is working just fine.

**Comment by hibo98** [comment] 2021-07-16 10:53
It cloud be that the problem is caused by the changes in the PR #36440

**Comment by zoltanbedi** [comment] 2021-07-16 11:00
I see, thanks for the clarification.

**Comment by ashharrison90** [comment] 2021-07-16 14:01
hi @hibo98 👋 

sorry for the performance regression! i tried a new implementation for the tooltip which was much cleaner code-wise and seemed to have similar performance across all the browsers. i'm not on windows though, so it could be something specific to the windows + firefox combination

i think the safest thing to do is revert back to the previous implementation with the additional positioning fix.
i'll raise a PR for that shortly 👍

**Closed** 2021-07-20 13:49 UTC
Labels: area/panel/timeseries, type/bug
