### ISSUE TITLE
Query Editor: Drag and drop to reorder queries no longer works well

### ISSUE THREAD

**Issue by justinsmalley** [grafana/grafana#58726] opened 2022-11-14 22:59 UTC
**What happened**:
The "Drag and Drop to Reorder" button for queries no long works consistently. Sometimes the queries swap places but usually not. Usually on the first attempt it doesn't move and some whitespace opens up below the queries. On the second attempt the whitespace usually disappears and the query moves, but without an animation. 
![Kapture 2022-11-14 at 15 55 52](https://user-images.githubusercontent.com/99200643/201785382-71d84bf3-6b6f-4009-8696-a033df2bd08b.gif)

**What you expected to happen**:
Queries dragged into different order.

**How to reproduce it (as minimally and precisely as possible)**:
Any panel with multiple queries.

**Anything else we need to know?**:
Tested on chrome (regular account and incognito) and firefox, and Grafana 9.2.3 (play.grafana.org) & 9.2.4. All had the same observed behaviour

**Environment**:
- Grafana version: Grafana 9.2.3 (play.grafana.org) & 9.2.4
- Data source type & version: All
- OS Grafana is installed on: N/A
- User OS & Browser: chrome (regular account and incognito) and firefox
- Grafana plugins: N/A
- Others:

**Comment by zuchka** [comment] 2022-11-15 04:11
Thanks for creating this issue, @justinsmalley 

can confirm that this is reproducible on play.grafana and `Grafana v9.2.4 (64017e8ca6)` 

BUT everything appears to work as expected on main `[v9.3.0-pre (28d39d35fd)]`. Don't see anything in the changelog...not sure where the issue is coming from...

**Comment by ivanortegaalba** [comment] 2022-11-16 09:09
👋 Hi, I can confirm this issue is solved in v9.3.0. This PR solves the issue https://github.com/grafana/grafana/pull/56515 and it will be included in that release.

Thanks for reporting!

**Closed by ivanortegaalba** 2022-11-16 09:09 UTC
Labels: type/bug, area/query-editor
