### ISSUE TITLE
[Bug] Grafana SMTP error: "Failed to send alert notification email" 

### ISSUE THREAD

**Issue by Metamathematics** [grafana/grafana#8548] opened 2017-06-06 15:24 UTC
Please include this information:
- What Grafana version are you using?
4.3.1
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Windows Server 2008 R2 Enterprise
- What did you do?
Attempted to set up SMTP and send test notification
- What was the expected result?
Grafana to send test email to stated address
- What happened instead?
Grafana throws errors

grafana.log:
t=2017-06-06T17:22:08+0200 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-06-06T17:22:08+0200 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[sg@loyaltypartner.com]
t=2017-06-06T17:22:08+0200 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF
t=2017-06-06T17:22:08+0200 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=3 uname=admin error=EOF
t=2017-06-06T17:22:08+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=3 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=[::1] time_ms=5 size=48

SMTP config:
#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = 127.0.0.1:25
;user =
;password =
;cert_file =
;key_file =
skip_verify = true
from_address = admin@grafana.localhost
from_name = Grafana

**Comment by torkelo** [comment] 2017-06-06 19:22
dupe of https://github.com/grafana/grafana/issues/7116

**Closed by torkelo** 2017-06-06 19:22 UTC

**Comment by xiaolongli827** [comment] 2019-02-12 12:06
are you  solve the question?

**Comment by xiaolongli827** [comment] 2019-02-12 12:07
i am facing this problem...

**Comment by HusainRegal** [comment] 2020-04-05 12:39
Follow this link if you are using gmail smtp and having problem:

https://www.techiescorner.in/archives/1341?unapproved=33550&moderation-hash=6f54c71b4a12261c6bb94367ff3cdde3#comment-33550

**Comment by techiescorner** [comment] 2020-04-13 09:17
> Follow this link if you are using gmail smtp and having problem:
> 
> https://www.techiescorner.in/archives/1341?unapproved=33550&moderation-hash=6f54c71b4a12261c6bb94367ff3cdde3#comment-33550

Please use the new URL

https://www.techiescorner.in/grafana-mail-alert-configuration/

**Comment by mahavirdarbar** [comment] 2023-12-22 05:14
When I used the Google application-specific password, I was able to work. You can find the [setup instructions](https://www.vishalvyas.com/2019/01/application-specific-password-required.html) at this link.
