### ISSUE TITLE
Dashboard custom time range in UTC doesn't show correct time window on Graph's x-axis

### ISSUE THREAD

**Issue by digrich** [grafana/grafana#25471] opened 2020-06-09 07:28 UTC
**What happened**:
Custom time range like 'From: now-21h/d+2h   To:now' in UTC time zone is not showing correct time window on the graph.  
**What you expected to happen**:
I was expecting 21h to current time on the graph as per UTC time zone

**How to reproduce it (as minimally and precisely as possible)**:
Select 'From: now-21h/d+2h   To:now' time range and UTC time zone on the dashboard. It will query the data correctly but won't display the complete data.   

**Anything else we need to know?**:
It's calculating the correct time for the query but not showing it correctly on the graph

```
range: {from: "2020-06-08T21:00:00.000Z", to: "2020-06-09T07:17:28.609Z",…}
from: "2020-06-08T21:00:00.000Z"
raw: {from: "now-21h/d+21h", to: "now"}
to: "2020-06-09T07:17:28.609Z"
rangeRaw: {from: "now-21h/d+21h", to: "now"}
from: "now-21h/d+21h"
to: "now"
```
It seems, it is interpreting the dashboard custom time range in browser timezone to calculate the graph time window.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Influx DB
- OS Grafana is installed on: Mac
- User OS & Browser: Mac & Chrome
- Grafana plugins:
- Others:

**Comment by AgnesToulet** [comment] 2020-06-09 10:02
Duplicate of #24115

**Closed by AgnesToulet** 2020-06-09 10:02 UTC
