### ISSUE TITLE
Certain Visualizations Disappear on Low-Performant Devices

### ISSUE THREAD

**Issue by onehivesystems** [grafana/grafana#79578] opened 2023-12-15 13:59 UTC
### What happened?

It seems that certain visualizations on a dashboard disappear after a little while when Grafana is displaying on a low-performant device. In my case, I have an old Raspberry Pi 3 B+ running a 1080p monitor to show this dashboard 24/7. Initially, when the dashboard loads, everything displays and refreshes properly. But after a few hours, the content of certain visualizations disappear in the panel. Currently, I have only noticed this with graph-based visualizations, such as time graph and bar chart. Other visualizations like the table or stats panel continue to function normally.

![20231214_212121](https://github.com/grafana/grafana/assets/77515137/e1f2c224-05c8-48d5-87fa-e4c7f371fece)

### What did you expect to happen?

Visualizations to function normally over time.

### Did this work before?

This works initially, when the dashboard loads up for the first time. But after a few hours, certain visualizations just disappear and no edits are made to the dashboard during this time, nor is there loss of network connectivity.

### How do we reproduce it?

1. Create a dashboard with time graphs and/or bar charts
2. Setup an older Raspberry Pi and display the dashboard in kiosk mode on Chromium browser
3. Wait a few hours, displaying it the entire time, and it should replicate the disappearing issue

### Environment (with versions)?

Grafana: 10.2.2
OS: Raspberry Pi OS 64-bit (latest version)
Browser: Chromium browser (built-in)

### Grafana platform?

None

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment] 2024-01-16 10:39
hi @onehivesystems 

Since we can't reproduce the same conditions, here are some things you that can try from your end:

1. Check for any JavaScript errors in the browser's development console when the issue occurs.
2. Confirm that the Raspberry Pi's hardware resources are not being overtaxed during the display of the dashboard.
3. Upgrade to the latest version if possible and retest, as there might have been performance improvements or bug fixes.

I'm closing this issue, but feel free to post in our [community forum](https://community.grafana.com/) instead. There are a lot of raspberry pi users that could advise you better !

**Closed by tonypowa** 2024-01-16 10:39 UTC
