### ISSUE TITLE
Library-Panels: Regression: Repeating by row does not work in 9.3+

### ISSUE THREAD

**Issue by Rumbelstilzchen** [grafana/grafana#60633] opened 2022-12-21 14:25 UTC
**What happened**:
for rows that are repeated by variable the content is not used for library panels.
(see right side of attached image)
![Repeating BUG - Grafana](https://user-images.githubusercontent.com/8233580/208926366-5cb8dcf6-913f-4ee5-9de7-bb6d38a6b333.png)
**What you expected to happen**:
The variable content should be correctly set
(see left side of attached image)
**How to reproduce it (as minimally and precisely as possible)**:
<details>
  <summary>Json of Dashboard:</summary>
  
  ```json
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 20,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "collapsed": false,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "panels": [],
          "repeat": "query0",
          "repeatDirection": "h",
          "title": "$query0",
          "type": "row"
        },
        {
          "datasource": {
            "type": "mssql",
            "uid": "Lodk2vPnz"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "displayMode": "auto",
                "inspect": false
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 3,
            "w": 12,
            "x": 0,
            "y": 1
          },
          "id": 4,
          "options": {
            "footer": {
              "fields": "",
              "reducer": [
                "sum"
              ],
              "show": false
            },
            "showHeader": true
          },
          "pluginVersion": "9.3.2",
          "targets": [
            {
              "datasource": {
                "type": "mssql",
                "uid": "Lodk2vPnz"
              },
              "editorMode": "code",
              "format": "table",
              "rawQuery": true,
              "rawSql": "select '${query0:raw}' as text ",
              "refId": "A",
              "sql": {
                "columns": [
                  {
                    "parameters": [],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              }
            }
          ],
          "title": "query0 = $query0",
          "type": "table"
        },
        {
          "gridPos": {
            "h": 3,
            "w": 12,
            "x": 12,
            "y": 1
          },
          "id": 9,
          "libraryPanel": {
            "name": "BUG_Panel",
            "uid": "wVlESCc4z"
          },
          "title": "LibraryPanel: query0 = $query0"
        }
      ],
      "schemaVersion": 37,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "hide": 0,
            "includeAll": true,
            "multi": true,
            "name": "query0",
            "options": [
              {
                "selected": true,
                "text": "All",
                "value": "$__all"
              },
              {
                "selected": false,
                "text": "Text1",
                "value": "Text1"
              },
              {
                "selected": false,
                "text": "Text2",
                "value": "Text2"
              },
              {
                "selected": false,
                "text": "Text3",
                "value": "Text3"
              }
            ],
            "query": "Text1, Text2, Text3",
            "queryValue": "",
            "skipUrlSync": false,
            "type": "custom"
          }
        ]
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Repeating BUG",
      "uid": "JzJFIjc4z",
      "version": 6,
      "weekStart": ""
    }
  ```
</details>
<details>
  <summary>Json of library panel::</summary>

  ```json
  {
    "id": 9,
    "gridPos": {
      "h": 3,
      "w": 12,
      "x": 12,
      "y": 1
    },
    "title": "LibraryPanel: query0 = $query0",
    "libraryPanel": {
      "id": 9,
      "orgId": 1,
      "folderId": 0,
      "folderUid": "",
      "uid": "wVlESCc4z",
      "name": "BUG_Panel",
      "kind": 1,
      "type": "table",
      "description": "",
      "model": {
        "id": 9,
        "gridPos": {
          "h": 3,
          "w": 12,
          "x": 12,
          "y": 1
        },
        "type": "table",
        "title": "LibraryPanel: query0 = $query0",
        "scopedVars": {
          "query0": {
            "selected": false,
            "text": "Text1",
            "value": "Text1"
          }
        },
        "datasource": {
          "type": "mssql",
          "uid": "Lodk2vPnz"
        },
        "pluginVersion": "9.3.2",
        "description": "",
        "fieldConfig": {
          "defaults": {
            "color": {
              "mode": "thresholds"
            },
            "custom": {
              "align": "auto",
              "displayMode": "auto",
              "inspect": false
            },
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": []
        },
        "options": {
          "footer": {
            "fields": "",
            "reducer": [
              "sum"
            ],
            "show": false
          },
          "showHeader": true
        },
        "targets": [
          {
            "datasource": {
              "type": "mssql",
              "uid": "Lodk2vPnz"
            },
            "editorMode": "code",
            "format": "table",
            "rawQuery": true,
            "rawSql": "select '${query0:raw}' as text ",
            "refId": "A",
            "sql": {
              "columns": [
                {
                  "parameters": [],
                  "type": "function"
                }
              ],
              "groupBy": [
                {
                  "property": {
                    "type": "string"
                  },
                  "type": "groupBy"
                }
              ],
              "limit": 50
            }
          }
        ]
      },
      "version": 3,
      "meta": {
        "folderName": "General",
        "folderUid": "",
        "connectedDashboards": 1,
        "created": "2022-12-21T13:54:58Z",
        "updated": "2022-12-21T13:57:03Z",
        "createdBy": {
          "id": 2,
          "name": "Peter",
          "avatarUrl": "/avatar/997949144f6e3b6b8bb83cd0945c18c3"
        },
        "updatedBy": {
          "id": 2,
          "name": "Peter",
          "avatarUrl": "/avatar/997949144f6e3b6b8bb83cd0945c18c3"
        }
      }
    },
    "targets": [
      {
        "datasource": {
          "type": "mssql",
          "uid": "Lodk2vPnz"
        },
        "editorMode": "code",
        "format": "table",
        "rawQuery": true,
        "rawSql": "select '${query0:raw}' as text ",
        "refId": "A",
        "sql": {
          "columns": [
            {
              "parameters": [],
              "type": "function"
            }
          ],
          "groupBy": [
            {
              "property": {
                "type": "string"
              },
              "type": "groupBy"
            }
          ],
          "limit": 50
        }
      }
    ],
    "options": {
      "showHeader": true,
      "footer": {
        "show": false,
        "reducer": [
          "sum"
        ],
        "fields": ""
      }
    },
    "fieldConfig": {
      "defaults": {
        "custom": {
          "align": "auto",
          "displayMode": "auto",
          "inspect": false
        },
        "mappings": [],
        "thresholds": {
          "mode": "absolute",
          "steps": [
            {
              "color": "green",
              "value": null
            },
            {
              "color": "red",
              "value": 80
            }
          ]
        },
        "color": {
          "mode": "thresholds"
        }
      },
      "overrides": []
    },
    "scopedVars": {
      "query0": {
        "selected": false,
        "text": "Text1",
        "value": "Text1"
      }
    },
    "type": "table",
    "datasource": {
      "type": "mssql",
      "uid": "Lodk2vPnz"
    },
    "pluginVersion": "9.3.2",
    "description": ""
  }
  ```
</details>

**Anything else we need to know?**:
Intermediate Fix:
Removing the scopedVars of the library Panel section directly via DB-SQLite-Editor fixes the problem - as long as it it not edited again

Eventually related to #59805

**Environment**:
- Grafana version: 9.3.1 & 9.3.2
- Data source type & version: ms-sql
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by Rumbelstilzchen** [comment] 2022-12-21 19:21
Grafana 9.2.8 is not affected.
After a downgrade the dashboard and the library panels work as expected.

**Comment by zuchka** [comment] 2022-12-29 21:18
Thanks for creating this issue, @Rumbelstilzchen 

guessing this PR is involved with the behavior change:

https://github.com/grafana/grafana/pull/50560

**Comment by natellium** [comment] 2023-01-12 10:34
Closing this in favour of https://github.com/grafana/grafana/issues/59805 as they seem to share the same root cause.

**Closed** 2023-01-12 11:59 UTC
Labels: needs investigation, bot/duplicate, area/frontend/library-panels, type/regression
