### ISSUE TITLE
InfluxDB 0.9 data source sends invalid time durations (months M and years y)

### ISSUE THREAD

**Issue by codyaray** [grafana/grafana#3087] opened 2015-10-29 16:02 UTC
It sends invalid time durations (such as 1y for years or 6M for months). As shown in the Inspector

    SELECT mean("loaded") FROM "sentinel_run" WHERE time > now() - 1y GROUP BY time(1d)

or

    SELECT mean("loaded") FROM "sentinel_run" WHERE time > now() - 6M GROUP BY time(1d)

Unfortunately, the "y" and "M" (in "1y" and "6M" are invalid durations for Influx 0.9.x).

If you look at the "raw query", it shows like this:

    SELECT mean("loaded") FROM "sentinel_run" WHERE $timeFilter GROUP BY time($interval)

So the $timeFilter needs to be more aware of these InfluxDB limitations. Is there a workaround for this? Or an easy fix?

**Comment by gunnaraasen** [comment] 2015-10-29 16:08
Here's the feature request for adding month and year support to InfluxDB, https://github.com/influxdb/influxdb/issues/3991.

The easiest workaround for now is to convert `1m` to `30d` and `1y` to `365d`.

**Comment by torkelo** [comment] 2015-10-29 16:28
dupe of https://github.com/grafana/grafana/issues/3067 , fixed also :)

**Closed by torkelo** 2015-10-29 16:28 UTC
