### ISSUE TITLE
Forward OAuth Identity with elasticsearch datasource still not sending headers

### ISSUE THREAD

**Issue by Scotturbina** [grafana/grafana#43311] opened 2021-12-18 19:12 UTC
When I turn on the Forward OAuth Identity and try to "Save and Test" I got an authentication error response “Authentication to data source failed”
![image](https://user-images.githubusercontent.com/22263714/146653007-2fb295a3-a640-45a4-a929-0d4e9056bf24.png)

What you expected to happen:
I expect the user credentials being forwarded successfully to elastic

How to reproduce it (as minimally and precisely as possible):
I got Open Id as auth method for grafana.
My grafana config looks like this :
![image](https://user-images.githubusercontent.com/22263714/146653016-50944474-c344-4722-b19b-434260975837.png)

```
########################## Data Proxy #############################
    [dataproxy]
    logging = true
    send_user_header = true
```
I saw that this works according to the documentation If my data source uses the same OAuth provider as Grafana itself, for example using Generic OAuth Authentication, my data source plugin can reuse the access token for the logged-in Grafana user. (https://grafana.com/docs/grafana/latest/developers/plugins/add-authentication-for-data-source-plugins/ )

Also I am using Open ID with same client id and secret for Elastic(Kibana) and Grafana
I got a Flask proxy in the middle to check what are the headers are coming, but I do not see “Authorization” header.

![image](https://user-images.githubusercontent.com/22263714/146653124-876251e6-4ab9-45ab-8461-3d3e40594572.png)

Also I am using Open ID with same client id and secret for Elastic(Kibana) and Grafana
Is there something am I doing wrong?
Is there something to do with elasticsearch plugin?
Environment:
Grafana version: 8.3.2
Data source type & version: Elasticsearch 7.9.1
OS Grafana is installed on: REHL
User OS & Browser: REHL 8.4 and google chrome
Grafana plugins:
Others:

**Comment by Scotturbina** [comment] 2022-01-10 14:21
@torkelo please let me know if I can help you in something here.

**Comment by Scotturbina** [comment] 2022-02-01 16:18
I tested version 8.3.4 seems it is forwarding an `Authorization Bearer`, but keeps failing when tries to authenticate, Grafana and Kibana are using openId, how did you make it work? 
![image](https://user-images.githubusercontent.com/22263714/152007002-ad577e75-9c14-4a79-a807-f9e79666d7e2.png)

**Comment by gabor** [comment] 2022-06-13 09:49
i can confirm that the `Authorization` header is populated when sending the request to the elasticsearch datasource, in both grafana8.5.5 and grafana9.0.0-beta3. The value of the header is not generated by the elasticsearch datasource, it's done by generic grafana data proxy code.

**Comment by gabor** [comment] 2022-06-13 09:50
issue seems to be a duplicate of https://github.com/grafana/grafana/issues/45328 , closing this one.

**Closed by gabor** 2022-06-13 09:50 UTC
Labels: type/bug, datasource/Elasticsearch, needs investigation
