### ISSUE TITLE
Datasource not working with Basic Auth settings

### ISSUE THREAD

**Issue by gw0** [grafana/grafana#28009] opened 2020-10-02 17:13 UTC
**What happened**:
As an additional precaution I use datasources that require a HTTP basic authentication. Unfortunately, it seems Grafana has a weird issue with Basic Auth credentials that makes it work only the first time or when you open a new browser window. My hypothesis is that this forwarding of HTTP basic auth prompt from the datasource to to users browser is not implemented correctly. Once set, the browser always sends these credentials to Grafana and they override whatever is being set in the datasource configuration (wrong behavior).

**What you expected to happen**:
Basic Auth credentials should work all the time and the setting in datasource should have precedence.

**How to reproduce it (as minimally and precisely as possible)**:
- Open a new browser, login to Grafana
- Add data source, select Prometheus
- Enter URL
- Enable "Basic auth", enter User and Password
- Click "Save & Test", results in: Data source is working (as expected)
- Disable "Basic auth"
- Click "Save & Test", the browser prompts you for HTTP basic auth "Authentication Required", leave empty, click "Ok"
- Results in: HTTP Error Unauthorized (as expected, but probably due to wrong reasons)
- Enable "Basic auth", reenter User and Password (use Reset)
- Click "Save & Test", results in: HTTP Error Unauthorized (WRONG!)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser: Ubuntu, Firefox

Probably related to this issues:
- https://github.com/grafana/grafana/issues/15050

**Comment by torkelo** [comment] 2020-10-07 12:44
duplicate of #15050

**Comment by aknuds1** [comment] 2020-11-03 11:35
I'm going to try and reproduce.

**Comment by aknuds1** [comment] 2020-11-06 11:49
I think I can reproduce this in Firefox. When disabling basic auth, I also get a browser prompt for username and password (at least I got the prompt, not sure if I had to disable BA first). After that happens, it looks as if Grafana frontend always sends a basic auth header to the server with the query request, which causes Grafana to try to log the user in.

With Chromium it works again once I re-enable basic auth in the data source, so looks as if the state doesn't stick somehow.

**Comment by aknuds1** [comment] 2020-11-06 11:50
I'm not sure if this is a backend or frontend bug though.

**Comment by aknuds1** [comment] 2020-11-06 11:57
It looks to me as if you're right about Grafana forwarding the basic auth prompt to the client @gw0, but I don't actually know how that works (I guess I'm too new to working on Grafana). It also looks as if the basic auth header sticks after that, so long as you use Firefox (Chromium doesn't have the problem at least).

**Comment by aknuds1** [comment] 2020-11-06 12:12
It looks as if the problem is that the Grafana server passes on the header `Www-Authenticate: Basic realm="prom"` to the client, which causes the browser to browse for credentials. Firefox apparently caches the credentials, which is causing your problem. I'll try to solve it.

**Comment by aknuds1** [comment] 2020-11-06 12:15
You can work around the issue by clearing active sessions in Firefox (hit Ctrl+Shift+Del to be prompted for things to clear, and clear "active sessions"). Then it will work if you enable basic auth and provide valid credentials.

**Comment by aknuds1** [comment] 2020-11-06 12:18
This is actually a dup of #15050, I will see if we can solve that one.

**Closed by aknuds1** 2020-11-06 12:18 UTC
Labels: area/backend/auth, needs investigation

**Comment by gw0** [comment] 2020-11-09 07:35
@aknuds1 Thanks for investigating.
