### ISSUE TITLE
Variable 'All' option does not work within repeat.

### ISSUE THREAD

**Issue by robert8103** [grafana/grafana#27154] opened 2020-08-24 08:00 UTC
**What happened**:
Since the update to Grafana 7.1.4 the Option 'All' generates a SQL with a Variable '$__all' instead of inserting one value per (repeated) panel
**What you expected to happen**:
That the 'All' option insert again one value per repeated panel
**How to reproduce it (as minimally and precisely as possible)**:
Create a variable with multiple values and set the options "Multi-value" and "Include All option"
Create a Dashboard with a repeated panel on the variable that uses this variable and set it to All.

**Environment**:
- Grafana version: 7.1.4
- Data source type & version: Postgres
- OS Grafana is installed on: Grafana Docker image

**Comment by torkelo** [comment] 2020-08-24 08:05
duplicate of https://github.com/grafana/grafana/issues/27119 

fix coming in 7.1.5 (scheduled for release tomorrow)

**Closed by torkelo** 2020-08-24 08:05 UTC
