### ISSUE TITLE
elasticseach: autocomplete for lucene query

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82826] opened 2024-02-15 22:03 UTC
### Discussed in https://github.com/grafana/grafana/discussions/64940

<div type='discussions-op-text'>

<sup>Originally posted by **gabor** March 17, 2023</sup>
we could offer autocomplete in the lucene query editor.</div>

**Comment by ivanahuckova** [comment] 2024-02-21 09:13
Closing as duplicate of https://github.com/grafana/grafana/issues/77556

**Closed by ivanahuckova** 2024-02-21 09:13 UTC
Labels: type/feature-request, datasource/Elasticsearch, migrated-discussions
