### ISSUE TITLE
Template variable from MS SQL query shows _value instead of _text when selected from multi-value dropdown

### ISSUE THREAD

**Issue by rmichaelporter** [grafana/grafana#26905] opened 2020-08-10 20:02 UTC
What happened:
Template variable selection shows value instead of text for multi-value selections

What you expected to happen:
Template variable to show text of selected entries

How to reproduce it (as minimally and precisely as possible):

1. Create a template variable using a MS SQL source
2. Make the template variable multi-value

Anything else we need to know?:

- The All option does not need to be 
- Display is correct (text shown) when single-value mode is used for the template variable

Environment:

    Grafana version: v7.1.0
    Data source type & version: MS SQL
    OS Grafana is installed on: Windows Server 2016
    User OS & Browser: Windows 10 79.0 Firefox 79.0 (64-bit)

**Comment by torkelo** [comment] 2020-08-11 06:58
looks like a duplicate of #25959

**Closed by torkelo** 2020-08-11 06:58 UTC
