### ISSUE TITLE
Inifinite loop when Scan for older logs clicked

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#15086] opened 2019-01-28 10:33 UTC

**Comment by torkelo** [comment] 2019-01-28 10:48
Are you using latest master? I fixed an issue with angular url <-> redux url state sync this weekend that might have solved this. Cannot replicate it locally.

**Comment by davkal** [comment] 2019-01-28 11:57
Looks like this happens when the query is empty.
Separate issue: how did you end up there? There should be the StartPage being shown.

**Comment by dprokop** [comment] 2019-01-28 12:06
1. Go to Explore
2. Change datasource to `TestData`
3. Change datasource to `Loki`

And no start page is displayed anymore

**Comment by hugohaggmark** [comment] 2019-01-31 11:48
Can still reproduce this

**Comment by torkelo** [comment] 2019-02-01 08:39
The root cause that I can identify is that during change data source
importQueries is called (before data source has fully changed), this generates a new empty query with new key prop, this new key prop causes an unmount/mount of QueryRow which causes a new mount of QueryEditor (wrapper for angular query editors in Explore), this component calls onQueryChange in it's mount function. So the result is we get a onQueryChange after importQueries (That did the resetting of the queries).

**Comment by torkelo** [comment] 2019-02-11 09:34
Think this is fixed with hugos big refactoring of Explore

**Closed by torkelo** 2019-02-11 09:34 UTC
Labels: comp: explore, comp: frontend, type: bug
