### ISSUE TITLE
Docs feedback: /reference/templating.md

### ISSUE THREAD

**Issue by clickstefan** [grafana/grafana#21997] opened 2020-02-07 11:11 UTC
The `$__range` is approximate (e.g. for a 1 day and a half interval it will be `1d`). When getting just a delta or increase, it can really skew the results. 
Workaround if you want precision in prometheus is to use `${__range_s}s`, but this should at least be documented.

**Comment by sakjur** [comment] 2020-02-10 12:14
Thank you for your feedback! I agree that that is confusing and that the current wording[[1]] misrepresents how the `$__range` variable is currently working. The approximate nature of `$__range` is a known issue, see #21689. There is an open PR for fixing it in #21722. However, I don't think this is a direct duplicate of that since this is a proposal to make sure the docs suggests the `${__range_s}s` work-around for Grafana before whatever version #21689 is fixed.

[1]: https://github.com/grafana/grafana/blob/master/docs/sources/reference/templating.md#the-__range-variable

**Comment by sakjur** [comment] 2020-02-11 10:14
After some additional consideration, I'm going to close this as a duplicate of #21689. Getting the fix merged for the underlying bug is on the way and hopefully happening this week (which would likely have it as part of either next minor or patch release within a month or so).

**Closed by sakjur** 2020-02-11 10:14 UTC
Labels: area/datasource, datasource/Prometheus, type/docs
