### ISSUE TITLE
nanoseconds to microseconds auto round off - ElasticSearch Queries

### ISSUE THREAD

**Issue by vmanju123** [grafana/grafana#23415] opened 2020-04-07 19:38 UTC
**What happened**:
We have a field in elastic search called nanoTS which captures time in nano seconds(Eg : 1,586,266,811,037,470,976) when we query in grafana, grafana automatically rounds this to nearest microseconds(1,586,266,811,037,478,000), we need nano second precision for the query
we verified the data in Kibana and we do see kibana brings back the value in nano seconds as is

**What you expected to happen**:
Expect grafana not to auto round off

**How to reproduce it (as minimally and precisely as possible)**:
Define a number field in elastic search call it nanoTS - type long, insert nano second value, query in grafana and check

**Anything else we need to know?**:
None

**Environment**:
- Grafana version:6.5.2
- Data source type & version:Elastic Search
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser:Windows/Chrome Browser
- Grafana plugins:
- Others:

**Comment by jongyllen** [comment] 2020-04-08 08:02
Duplicate of #23408

**Closed by jongyllen** 2020-04-08 08:02 UTC
Labels: type/duplicate
