### ISSUE TITLE
Grafana can query Prometheus for version instead of relying on user specifying it

### ISSUE THREAD

**Issue by brahmnes** [grafana/grafana#70866] opened 2023-06-28 20:48 UTC
In the prometheus data source configuration, the user needs to configure which version of Prometheus the data source is.

![image](https://github.com/grafana/grafana/assets/3384008/70c1b17e-1f1e-4326-9511-68c335995a59)

It looks like starting in Prometheus 2.14, there is a Prometheus API that can return the server side version.
[link](https://prometheus.io/docs/prometheus/latest/querying/api/#build-information)

Given this, ideally Grafana can call this API to determine the version first, and then adjust its behavior based on this information. Doing this will avoid some customer errors where they configured a version that's too high and Grafana makes unsupported calls against a particular version of server side Prometheus.

### 
# How do we reproduce it?

Just go to the data source config page for Prometheus, you will see the dropdown for selecting the prometheus api version

### 
# What Grafana version are you using?

9.4.12

### 
### Grafana Platform?

None

### Is this a Regression?

None

**Comment by gtk-grafana** [comment] 2023-07-07 20:29
The UI should auto-populate the version string when selecting a datasource type in v9.2.3+ with a few caveats.
1. There was a [bug with prometheus](https://github.com/grafana/grafana/pull/71198) versions greater than 2.41 not populating. A fix for this was merged in today and backported to all versions this feature is available (9.2.x and up), and should be available when the next release is cut.
2. Your datasource has to return a semver version property in the buildinfo api call. It currently [won't work for nightly build](https://github.com/grafana/grafana/issues/57843) versions/commit hashes.

@brahmnes Helping the user select the right version instead of leaning into an entirely automatic approach was a compromise we made because at the time of implementation, not all Prometheus compatible data sources had a buildinfo API, and also the buildinfo API responses don't readily provide us with anything to differentiate datasource types (Mimir, Thanos, Cortex, Prometheus) from each other. While this has changed since this functionality was initially released, I think Cortex has [buildinfo implemented](https://cortexmetrics.io/docs/api/#build-information) now, we still support Prometheus data sources that do not in Grafana 9 and 10, and as such it was hard to implement a solution that would cause unexpected behavior for folks with older or cortex datasources. 

That said, I still want to get rid of these dropdowns, I created an issue https://github.com/grafana/grafana/issues/71247, and put it in our backlog. 

FYI, the only location the version number logic is [currently used](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.tsx#L195-L207) is checking for labels/.../values support for the `match[]` parameter in the Prometheus API, which was released in[2.24.0].(https://github.com/prometheus/prometheus/releases/tag/v2.24.0)

**Comment by brahmnes** [comment] 2023-07-11 00:41
Thanks @gtk-grafana for the detailed explanation!
What you described makes sense and I understand the challenges around compatibility. That api you mentioned is exactly where we observed the "unsupported route" error message. From what you described it sounds like only a small percentage of people should hit it.

Thanks for tracking this in your backlog, I look forward to when this is simplified.

**Closed** 2023-07-18 14:47 UTC
Labels: datasource/Prometheus
