### ISSUE TITLE
Bar gauge panel with different color per bar

### ISSUE THREAD

**Issue by CMahesh** [grafana/grafana#19113] opened 2019-09-16 06:33 UTC
**What would you like to be added**:
When visualizing the panel using the bar gauge all the bars of the same color. There is no option for changing the color of each bar.

**Why is this needed**:
If we are showing the demo of, for example,  No of system's up, down. It is not correct to show both the values in green or red, system's up number with green and system's down number with red is the correct representation for it.

**Comment by torkelo** [comment] 2019-09-16 08:23
dupe of https://github.com/grafana/grafana/issues/18364

**Closed by torkelo** 2019-09-16 08:23 UTC
