### ISSUE TITLE
When adding a new panel, add it at the end instead of the top.

### ISSUE THREAD

**Issue by poodad** [grafana/grafana#32261] opened 2021-03-23 14:12 UTC
When adding a new panel, it goes at the top of the page which causes shifting of existing panels which then need to be moved back into proper position.

It would make more sense for new panels to be added at the end of the page so as not to disturb the placement of the existing panels.

**Comment by torkelo** [comment] 2021-03-24 06:58
duplicate of https://github.com/grafana/grafana/issues/31151

**Closed by torkelo** 2021-03-24 06:58 UTC
Labels: area/dashboard, type/feature-request
