### ISSUE TITLE
Grafana 8.0.5 - build RPM package -> Unknown command "pkg-rpm"

### ISSUE THREAD

**Issue by flynn1973** [grafana/grafana#36798] opened 2021-07-15 12:42 UTC
this always worked, but with 8.0.5 it throws an error.

````
root@lpgaixmgmtlx01:/scratch/go/dev/src/github.com/grafana/grafana>go run build.go build pkg-rpm
Version: 8.0.5, Linux Version: 8.0.5, Package Iteration: 1626352577
rm -r ./bin/linux-ppc64le/grafana-server
rm -r ./bin/linux-ppc64le/grafana-server.md5
go version
go version go1.16.6 linux/ppc64le
Targeting linux/ppc64le
go build -ldflags -w -X main.version=8.0.5 -X main.commit=cbb2aa5 -X main.buildstamp=1625740244 -X main.buildBranch=HEAD -o ./bin/linux-ppc64le/grafana-server ./pkg/cmd/grafana-server
rm -r ./bin/linux-ppc64le/grafana-cli
rm -r ./bin/linux-ppc64le/grafana-cli.md5
go version
go version go1.16.6 linux/ppc64le
Targeting linux/ppc64le
go build -ldflags -w -X main.version=8.0.5 -X main.commit=cbb2aa5 -X main.buildstamp=1625740244 -X main.buildBranch=HEAD -o ./bin/linux-ppc64le/grafana-cli ./pkg/cmd/grafana-cli
Unknown command "pkg-rpm"
exit status 1
````

so what is the newest sorcery to build an rpm package? i forced to build my as i am runnig on ppc64le.
go run build.go build creates the binaries as expected, but i need to package the whole thing (front / backedn) into an rpm.

root@lpgaixmgmtlx01:/scratch/go/dev/src/github.com/grafana/grafana>bin/linux-ppc64le/grafana-cli --version
Grafana CLI version 8.0.5

**Comment by wbrowne** [comment] 2021-07-19 08:44
Thanks for the info @flynn1973. This looks to be a duplicate of https://github.com/grafana/grafana/issues/30963. It would be best to keep everything in the same issue, so will close this this one.

**Closed by wbrowne** 2021-07-19 08:44 UTC
Labels: type/build-packaging
