### ISSUE TITLE
Cannot read property 'templateSrv' of undefined

### ISSUE THREAD

**Issue by d3xt3r01** [grafana/grafana#12182] opened 2018-06-06 12:40 UTC
### What Grafana version are you using?
Grafana v5.1.3 (commit: 087143285)
### What datasource are you using?
opentsdb
### What OS are you running grafana on?
linux gentoo
### What did you do?
Upgraded a while ago but I can't remember from what version. It didn't start with 5.1.3 but I didn't think to debug since I don't use it too often
### What was the expected result?
see my old graph
### What happened instead?
empty graph
```
TypeError: Cannot read property 'templateSrv' of undefined
    at https://d3xbucharest.go.ro/grafana/public/build/0.5c89ac3fc7a3e78b3629.js:7:129549
    at https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:68626
    at https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:78723
    at dr (https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:69166)
    at https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:78528
    at ur (https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:68594)
    at Function.as [as every] (https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:94094)
    at https://d3xbucharest.go.ro/grafana/public/build/0.5c89ac3fc7a3e78b3629.js:7:129508
    at A (https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:54009)
    at Function.fa [as findIndex] (https://d3xbucharest.go.ro/grafana/public/build/vendor.0cea50118711e7e6c839.js:1:90392)
```
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.
```
Request URL: https://d3xbucharest.go.ro/grafana/api/datasources/proxy/1/api/query
Request Method: POST
Status Code: 200 
Remote Address: 127.0.0.1:1080
Referrer Policy: no-referrer-when-downgrade
access-control-allow-headers: Authorization, Content-Type, Accept, Origin, User-Agent, DNT, Cache-Control, X-Mx-ReqToken, Keep-Alive, X-Requested-With, If-Modified-Since
access-control-allow-methods: GET, POST, PUT, DELETE
access-control-allow-origin: https://d3xbucharest.go.ro
cache-control: max-age=0
content-encoding: gzip
content-length: 42569
content-type: application/json; charset=UTF-8
date: Wed, 06 Jun 2018 12:35:37 GMT
expires: Wed, 06 Jun 2018 12:35:37 GMT
server: Apache
status: 200
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: User-Agent
x-content-type-options: nosniff
:authority: d3xbucharest.go.ro
:method: POST
:path: /grafana/api/datasources/proxy/1/api/query
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 671
content-type: application/json;charset=UTF-8
cookie: grafana_user=asandu; grafana_remember=7bbfc3e71f4182614723d63b4af38bb23aeef5c1038e475ec317204bd85b58ce56e3; grafana_sess=e923d3180ffe96ae
dnt: 1
origin: https://d3xbucharest.go.ro
referer: https://d3xbucharest.go.ro/grafana/d/000000001/frankenstein-stats?refresh=1h&orgId=1&panelId=1&fullscreen
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
x-grafana-org-id: 1
{start: 1525696536988,…}
globalAnnotations
:
true
msResolution
:
false
queries
:
[{metric: "proc.net.bytes", aggregator: "max", rate: true, rateOptions: {counter: false},…},…]
start
:
1525696536988
```

**Comment by torkelo** [comment] 2018-06-06 19:46
duplicate of https://github.com/grafana/grafana/issues/11904

**Closed by torkelo** 2018-06-06 19:46 UTC
