### ISSUE TITLE
Grafana: Variables inside Variables not working

### ISSUE THREAD

**Issue by plomatheusnunes** [grafana/grafana#74909] opened 2023-09-14 13:02 UTC
### What happened?

I have 2 variables in my dashboard:
<img width="171" alt="image" src="https://github.com/grafana/grafana/assets/101121174/8b80d3d9-0d49-49ad-a575-02daacd8a1db">

and my variable 'ambiente_db' is based on 'ambiente' variable:
<img width="209" alt="image" src="https://github.com/grafana/grafana/assets/101121174/19f688bd-1e62-4a02-b332-11a266291da0">

the problem is here in MySQL's type variable:
<img width="153" alt="image" src="https://github.com/grafana/grafana/assets/101121174/9680bddd-6a61-423c-808c-ae140eb967c1">

images that a post here it was on version 10.0.0

### What did you expect to happen?

In version 10.0.0 it's working like:
<img width="153" alt="image" src="https://github.com/grafana/grafana/assets/101121174/2dd33e8c-c112-495e-ae4d-34f953fee082">

and in version 10.1.1 Grafana doesn't found nothing based on variable, like this:
<img width="81" alt="image" src="https://github.com/grafana/grafana/assets/101121174/2a977ec8-0e53-4db5-9eb6-6423a9c800d6">

### Did this work before?

It's worked in version 10.0.0 and on previous versions.

### How do we reproduce it?

1. Set the first variable
2. Use the first variable in 'Instance name filter' in the second variable

### Is the bug inside a dashboard panel?

It's on variables.

### Environment (with versions)?

Grafana: 10.0.0 to 10.1.1
OS: RHEL 7
Browser: Google Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Zabbix and MySQL

**Comment by mellieA** [comment] 2023-09-19 19:24
I tried this in version 10.2 and it works as you expect. What kind of variable is your $ambiente var? In my test I tried constant and custom variables for the filter variable. 


https://github.com/grafana/grafana/assets/18175287/f215d334-f3c8-4384-bc3b-14b7ad646f90

**Comment by mellieA** [comment] 2023-09-19 19:25
@plomatheusnunes I've closed this with the "works-as-intended" label. If you find there is a bug and have the steps to reproduce it, please reference this issue and add the additional steps.

**Closed by mellieA** 2023-09-19 19:25 UTC
Labels: type/works-as-intended
