### ISSUE TITLE
[Feature request] ElasticSearch: Personalize "order" aggr terms in Query templating

### ISSUE THREAD

**Issue by alisson276** [grafana/grafana#8571] opened 2017-06-07 18:49 UTC
Please include this information:
Grafana version: 4.2.0
Datasource: Elasticsearch
OS: CentOS 7
Using the templating feature for query a term in elasticsearch with Query like that:
`        {"find":"terms","field":"ipv4_src_addr"}`

When using that filter, the inspect of browser show me the following "request":
       ```
 {"search_type":"query_then_fetch","ignore_unavailable":true,"index":["netflow-2017.06.07"]}
        {"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp": {"gte":"1496856178110","lte":"1496857978110","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"ipv4_src_addr","size":500,"order":{"_term":"asc"}}}}}
```

The problem is that using '"order":{"_term":"asc"}' in search request gets the IPs shuffled.

In the source code the "_term":"asc" is hardcoded, is possible show it in a customized field for don't POST these field?
 
Testing with Postman directly using that request without that field "order" the result is showed like expected for IP Addresses.

**Comment by marefr** [comment] 2018-12-18 16:19
Duplicate of #7715

**Closed by marefr** 2018-12-18 16:19 UTC
Labels: datasource: Elasticsearch, help wanted, type: feature request
