### ISSUE TITLE
Add docker tags for major/minor/patch versions

### ISSUE THREAD

**Issue by Quadrubo** [grafana/grafana#92658] opened 2024-08-29 11:21 UTC
As of the point of writing this, `11.2.0` is the latest Grafana OSS version.
As I'm manually updating my images and not using something like "latest", I have to change the image tag every new release. It would be nice if I wouldn't have to do that for patch releases (minor releases too).

Currently these tags are provided:
- `11.2.0` - Version 11.2.0
- `11.1.5` - Version 11.1.5
- `latest` - Version 11.2.0

### Desired Behavior

I would propose a tag system like this:
- `11.2.0` - Version 11.2.0
- `11.1.5` - Version 11.1.5
- `11.2`    - Version 11.2.0
- `11`       - Version 11.2.0
- `latest` - Version 11.2.0

This would allow pinning to specific version and allows the user to choose which semver types they are okay with auto updating.
I for example would have pinned to `11` and would have automatically gotten the update to `11.2.0`.
However I will not get the update to `12.x` which would be desired for me.

**Comment by marefr** [comment] 2024-09-05 08:50
Duplicate of #16193

**Closed** 2024-09-05 08:52 UTC
Labels: type/duplicate
