### ISSUE TITLE
Support Data Sources based on SRV record

### ISSUE THREAD

**Issue by sneth** [grafana/grafana#23872] opened 2020-04-24 19:28 UTC
Graphite behind DNS SRV records cannot be used as a Data Source.

Related issue #22608 was closed with a cursory response that is, as far as I can tell, not correct.

A simple and safe solution with no UI impact would be to support a protocol+srv URL format, as MongoDB does, as described here:

https://docs.mongodb.com/manual/reference/connection-string/#connections-dns-seedlist

In my case, as for the participants on #22608, I believe this is needed so that Graphite running in an Amazon EC2 cluster with bridge-mode networking on AWS ECS can be registered as a service via AWS Cloud Map and used as a Data Source in Grafana without egregious hackery.

**Comment by sneth** [comment] 2020-04-24 19:50
Related issue on the AWS side:

https://github.com/aws/containers-roadmap/issues/279

**Comment by marefr** [comment] 2020-04-27 06:58
Referenced issue doesn't have a lot of traction and this feels very AWS related so will close it. If #22608 gets more traction we'll consider reopen it.

**Comment by marefr** [comment] 2020-04-27 06:58
Duplicate of #22608

**Closed by marefr** 2020-04-27 06:58 UTC
