### ISSUE TITLE
xlink:href isn't working in Firefox

### ISSUE THREAD

**Issue by oklk** [grafana/grafana#26900] opened 2020-08-10 14:11 UTC
**What happened**:

xlink:href attribute isn't working properly in Firefox. (It works outside grafana. Tested with a react based website containing the same svg code)

When using xlink:href attributes for something like a gradient, the gradient doesn't show (shows in Chrome), making the element invisible (can select it in the inspect elements window in developer tools).

![image](https://user-images.githubusercontent.com/56425069/89788800-fd65d580-db1f-11ea-89e1-e63bb195a615.png)

**What you expected to happen**:

The xlink:href should work the same in Firefox and Chrome (as it does outside Grafana)

**How to reproduce it (as minimally and precisely as possible)**:

1. Install [marcuscalidus-svg-panel](https://github.com/MarcusCalidus/marcuscalidus-svg-panel)
2. Add a panel with the svg as the visualization
3. Paste the code below in the svg window

```
<svg
  version="1.1"
  viewBox="0 0 210 297"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
>
  <defs>
    <linearGradient
      id="linearGradient2"
      x1="0"
      x2="0"
      y1="100"
      y2="0"
      gradientUnits="userSpaceOnUse"
    >
      <stop style="stop-color: #00ffff;" offset="0" />
      <stop style="stop-color: #ff2a2a;" offset="1" />
    </linearGradient>
    <linearGradient
      id="linearGradient1"
      gradientUnits="userSpaceOnUse"
      xlink:href="#linearGradient2"
    />
  </defs>
  <g>
    <rect
      x="100"
      y="20"
      width="60"
      height="80"
      style="fill: url(#linearGradient1); paint-order: markers fill stroke;"
    />
    <rect
      x="20"
      y="20"
      width="60"
      height="80"
      style="fill: url(#linearGradient2); paint-order: markers fill stroke;"
    />
  </g>
</svg>
```

4. Save and open it in Chrome and Firefox
5. Chrome will show both rectangles and Firefox will only show the one without xlink:href

**Anything else we need to know?**:

Tested it in a plugin I'm developing by just adding it in as innerHTML

```html
HTML_NODE.shadowRoot.innerHTML = `<div style="position: absolute; top: 0; bottom: 0; left: 0; right: 0; margin: auto;">${HTML.code}</div>`;
```

Which gave the same bug

**Environment**:
- Grafana version: v7.1.1
- Data source type & version: 
- OS Grafana is installed on: Ubuntu 20.04 LTS
- User OS & Browser: Ubuntu 20.04 LTS, Chrome v83.0.4103.116 and Firefox v79.0
- Grafana plugins: marcuscalidus-svg-panel
- Others:

**Comment by sakjur** [comment] 2020-08-10 15:40
This is caused by Grafana setting the `base` tag, if you add `<base href="http://localhost">` (any URL will do) your standalone example will break in Firefox but not in Chrome or Safari. This has been marked as fixed once by Mozilla in [Firefox bug #1352979](https://bugzilla.mozilla.org/show_bug.cgi?id=1352979), but it's possible it has regressed or something. You should open a bug report with Mozilla for having this fixed.

**Closed by sakjur** 2020-08-10 15:40 UTC
