### ISSUE TITLE
Possibilty to add new Users vanished

### ISSUE THREAD

**Issue by SockenSalat** [grafana/grafana#51704] opened 2022-07-04 10:53 UTC
Grafana 9.0.1

Today, being in the admin-role, I tried to add a new user. There used to be something like `invite new user` available ... now I see a list of users, but no possibility to add new ones.

How is this supposed to work?

Thank you.

---
Update: I changed to the admin user and suddenly the missing button appeared. But the user account I was using previously also has the admin role and therfore the availability of the button is expected.
So it looks like you have a _hidden admin role_ or hardcoded the button :thinking:

**Comment by sindef** [comment] 2022-07-04 14:21
You want to go into the Server Admin menu (from the Admin user - <grafanaip>:port/admin/users ), and give them the 'Grafana Admin' permission. This will allow them to see the Server Admin. Handle with care.

**Comment by joshhunt** [comment] 2022-07-04 16:56
Thanks for reporting. Sounds like a dupe of https://github.com/grafana/grafana/issues/51634

**Closed by joshhunt** 2022-07-04 16:56 UTC
