### ISSUE TITLE
Postgres/TimescaleDB $__timeGroupAlias converts long intervals to invalid numbers

### ISSUE THREAD

**Issue by acedrew** [grafana/grafana#27253] opened 2020-08-27 20:58 UTC
![image](https://user-images.githubusercontent.com/977415/91493748-c0227700-e885-11ea-8d3c-ca27db87f8ec.png)
![image](https://user-images.githubusercontent.com/977415/91494016-2f986680-e886-11ea-9f10-9960108d1097.png)

**What happened**:
Creating an interval longer than 287h causes an invalid seconds string to be rendered in the query

**What you expected to happen**:
Any interval should work

**How to reproduce it (as minimally and precisely as possible)**:
Issue a time group query with a interval set above 288h against a postgres or timescaledb datasource

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: Postgres 7.1.3
- OS Grafana is installed on: Ubunutu 18.04
- User OS & Browser: Windows/Chrome
- Grafana plugins: Not applicable

**Comment by hugohaggmark** [comment] 2020-08-31 10:46
Thanks for reporting this @acedrew, could I bother you with screenshots from the QueryInspector? What is the generated SQL for your case reported here for instance.

**Comment by hugohaggmark** [comment] 2020-09-04 06:01
I'm going to close this issue for now because we've not received any feedback to our initial questions. If reporter supplies more proof in this issue, we'll of course reopen it.

All the best

**Comment by acedrew** [comment] 2020-09-05 02:55
I get wanting to get issues closed. But this is a bit ridiculous, there was plenty of information to recreate the issue. The question you asked was a clarifying one.
I've had a chance to get back to this now

{
  "response": {
    "results": {
      "B": {
        "error": "pq: invalid input syntax for type interval: \"2.592e+06s\"",
        "refId": "B",
        "meta": {
          "executedQueryString": "select time, metric,\n(\n    CASE\n      WHEN value >= lag(value) OVER w\n        THEN value - lag(value) OVER w\n      WHEN lag(value) OVER w IS NULL THEN NULL\n      ELSE value\n    END\n  ) AS \"value\"\nfrom (SELECT\n  time_bucket('2.592e+06s',time) AS \"time\",\n  substring(topic_name from 'ted/.*?/?(.*)/mtd') AS metric,\n  max(value) as value\nFROM test_data\nWHERE\n  \"time\" BETWEEN '2020-08-06T02:53:16.214Z' AND '2020-09-05T02:53:16.215Z' \n  and topic_name like '%/mtd'\n  group by 1,2\n  ORDER BY 1,2) a\n  window w as (partition by metric order by time)"
        },
        "series": null,
        "tables": null,
        "dataframes": null
      }
    },
    "message": "pq: invalid input syntax for type interval: \"2.592e+06s\""
  }
}

**Comment by hugohaggmark** [comment] 2020-09-07 04:38
@acedrew the problem was I couldn't recreate the issue. Can be because I have a different locale than you. But need to dig deeper. Thank you for adding more information

**Comment by marefr** [comment] 2020-09-07 09:13
@acedrew please show/include the query you're using. Thanks

**Comment by marefr** [comment] 2020-10-06 22:23
You still haven't provided the query your using in the query editor so very hard for us to investigate. Based on my own knowledge this is how I would use the `$__timeGroup` macro and it definitely works using a min interval > 288h:
![image](https://user-images.githubusercontent.com/1668778/95266077-c1ef3b00-0832-11eb-949a-6ca3e9416706.png)

Not able to reproduce and possibly thus has been fixed in later version than 7.1.3? Will close this for now, but consider reopen if you try on Grafana 7.2 and still have this problem and provide your query as it looks in the query editor.

**Comment by acedrew** [comment] 2020-10-07 14:22
![image](https://user-images.githubusercontent.com/977415/95343906-09071b80-0887-11eb-9e0a-0ab52f73ba54.png)

**Comment by acedrew** [comment] 2020-10-07 14:23
![image](https://user-images.githubusercontent.com/977415/95344020-2b009e00-0887-11eb-96ca-b14ddb9ac665.png)

**Comment by acedrew** [comment] 2020-10-07 14:23
I'll check in 7.2 as well.

**Comment by acedrew** [comment] 2020-10-07 14:28
Same problem in 7.2
![image](https://user-images.githubusercontent.com/977415/95344632-dad60b80-0887-11eb-8f49-3c9179682cd0.png)

**Comment by acedrew** [comment] 2020-10-07 14:29
I also checked using $__timeGroup instead of $__timeGroupAlias, same result. Strange that you can't recreate it.

**Comment by BobVul** [comment] 2020-11-12 03:25
I'm having the same problem, on 7.2.0:

![image](https://user-images.githubusercontent.com/1674237/98891575-9bd44f00-24f2-11eb-8908-d45cba51f869.png)

The generated SQL with a lower (working) interval e.g. `10d` is:

```sql
SELECT
  time_bucket('864000s',"time") AS "time",
  count(client_id) AS "endpoint"
FROM request_logs
WHERE
  "time" BETWEEN '2020-10-13T03:24:03.11Z' AND '2020-11-12T03:24:03.11Z'
GROUP BY 1
ORDER BY 1
```

Evidently it's a mix of the interval being specified in seconds, and the number being represented in scientific notation (float?) at a not-unreasonably-high interval.

Can this issue be reopened, or should I open a new one?

**Comment by marefr** [comment] 2020-11-13 02:02
@acedrew based on your screenshots, can you click on the generated sql button and include it here? Are you using a time range of last month?

**Comment by acedrew** [comment] 2020-11-19 19:05
@marefr see my reply on Sep 4th for generated SQL and applicable time range.

**Comment by marefr** [comment] 2021-02-08 12:47
@acedrew sorry but I can't find any comment Sep 4th from you including the time range. Only from the 5th. It's been a lot of comments back and forth here so lets try and back up a bit.

Does all of you have the timescale db configuration enabled? If so, this is probably an issue related to time_bucket. When I tested did not have timescale enabled.

**Comment by acedrew** [comment] 2021-02-08 14:04
Yes I do, that's why I mentioned timescale in the topic. That's very likely
the issue.

**Comment by BobVul** [comment] 2021-02-08 15:09
Yes, I also have the TimescaleDB option enabled on the data source.

Also, I've provided the generated SQL in [my comment here](https://github.com/grafana/grafana/issues/27253#issuecomment-725805177), which shows `time_bucket` being used.

| Min Interval / Interval | `time_bucket` (`bucket_width` param) | `intervalMs` (from Grafana generated SQL) | Working |
| ----------------------- | ------------------------------------------| ---------------------------------------------- | -------- |
| 10d | 864000s | 864000000 | ✔️ |
| 11d | 950400s | 950400000 | ✔️ |
| 12d | 1.0368e+06s | 1036800000 | ❌ |

**Comment by marefr** [comment] 2021-02-08 16:40
Cool. Sorry for not noticing this. So time bucket doesn't support certain formats. Anyone would be interested working on getting this resolved?

Think it's only this line here needing modification together with some tests: 			return fmt.Sprintf("time_bucket('%vs',%s)", interval.Seconds(), args[0]), nil

**Comment by kurokochin** [comment] 2021-02-12 15:35
Hi, I'll help with this!

**Closed** 2021-02-15 16:16 UTC
Labels: beginner friendly, datasource/Postgres, help wanted, type/bug
