### ISSUE TITLE
Loki logs do not parse ANSI escape color codes

### ISSUE THREAD

**Issue by avaly** [grafana/grafana#15263] opened 2019-01-30 01:06 UTC
I logged messages to Loki which included certain words highlighted with ANSI escape codes.

### What was the expected result?

The message should be parsed with the ANSI escape codes to highlight the text.

### What happened instead?

ANSI escape codes are not parsed/used, instead they are printed out as is.

![image](https://user-images.githubusercontent.com/356100/51908990-5b334080-2406-11e9-8c16-6cd63ba20b63.png)

PS: Opened this in https://github.com/grafana/grafana/issues/15114 but it was pointed out that this might better suited in this repo.

**Comment by DanCech** [comment] 2019-02-05 20:01
Duplicate of #15114

**Closed by DanCech** 2019-02-05 20:01 UTC
Labels: P4: nice to have, comp: explore, datasource: Loki
