### ISSUE TITLE
Login button URL is incorrect with Grafana behind reverse proxy

### ISSUE THREAD

**Issue by guiguan** [grafana/grafana#61964] opened 2023-01-24 00:20 UTC
**What happened**:

Our local Grafana is served from a reverse proxy, under `/grafana` path prefix, and we have followed the instruction at https://grafana.com/tutorials/run-grafana-behind-a-proxy/ to configure it. We are using anonymous auth mode. Everything seems fine except the login button at the bottom-left corner still shows incorrect URL:

```
https://our-public.domain/dashboards?search=open&forceLogin=true
```

instead of

```
https://our-public.domain/grafana/dashboards?search=open&forceLogin=true
```

**Environment**:
- Grafana version: v9.3.1

**Comment by zuchka** [comment] 2023-01-25 03:27
/duplicate of https://github.com/grafana/grafana/issues/59767

**Closed** 2023-01-25 03:28 UTC
Labels: type/duplicate
