### ISSUE TITLE
Feature request: include org. name in dashboard URL

### ISSUE THREAD

**Issue by rlueckl** [grafana/grafana#3130] opened 2015-11-04 10:46 UTC
We would like to use Grafana on our big screens to show us an overview of our systems. The dashboards we need are in different organisations (for example: we need 2 dashboards from Org1 and 3 Dashboards from Org2).

Unfortunately we can't open all of the dashboards in a browser because the Org is taken from the DB (or cookie?) and the current Org of the user is used.

This is also a problem for sharing links, because the user only gets a "Dashboard not found" if he is in the wrong Org.

Furthermore, this could lead to other errors, for example: there is a dashboard called "Overview" in Org1 and another dashboard also called "Overview" in Org2. User A is logged in to Org1, shares the link to hist Org1/Overview dashboard with User B. User B is in Org2 but can open the link from User A since Org2 also has a Dasboard called "Overview". But he will see something completely different!

**Comment by torkelo** [comment] 2015-11-04 11:18
dupe of 
https://github.com/grafana/grafana/issues/1613

**Closed by torkelo** 2015-11-04 11:18 UTC
