### ISSUE TITLE
Problem logging in with Firefox on iPad / mobile

### ISSUE THREAD

**Issue by bontchev** [grafana/grafana#15473] opened 2019-02-16 15:19 UTC
### What Grafana version are you using?

Grafana v5.4.3 (6539180)

### What datasource are you using?

MySQL

### What OS are you running grafana on?

Ubuntu Linux 16.04

### What did you do?

I tried to log in from Grafana's login page using Firefox on my mother's iPad.

### What was the expected result?

After entering the user name and password, I expected to be able to tap the Login button and to log in.

### What happened instead?

The button remained gray and could not be tapped.

This issue seems to be specific to Firefox on iPad. I can log in with Firefox on Windows and Linux just fine. I can log in on the iPad using the Safari browser just fine. On iOS, all browsers (Safari, Firefox, Chrome, whatever) must use one and the same browser engine (WebKit), so the issue is not caused by the different browsing engines that Safari and Firefox use on a PC. It must be something specific to Firefox on iPad but I could not determine what exactly.

**Comment by marefr** [comment] 2019-02-18 11:42
Duplicate of #12133

**Comment by marefr** [comment] 2019-02-18 11:43
Please try latest beta 6.0-beta2 - it should be fixed there.

**Comment by bontchev** [comment] 2019-02-19 17:45
Issue #12133 is about Chrome on iOS, though - while my problem is with Firefox. (My mother's iPad doesn't have Chrome, so I didn't test with that browser.)

I'd rather not install a beta and risk breaking something; I'll wait for the official release. The problem isn't urgent, I discovered it accidentally, and there are workarounds for it.

**Comment by marefr** [comment] 2019-02-20 16:51
Ah sorry for that. I've reopened issue and will ask you to give a response after you've tried 6.0 stable.

**Comment by bontchev** [comment] 2019-02-28 14:45
OK, Grafana updated to version 6.0.0 here, so I checked again. The problem is _not_ fixed. I still can't log in with Firefox on iPad. Not only this, but the workaround suggested for the similar problem in Chrome (deleting the last character of the user name and entering it again) does not help.

**Comment by marefr** [comment] 2019-03-04 12:31
Supporting Firefox on Ipad is not high priority for us. I'm going to try and reproduce whenever I got time (have an old Ipad at home). If anyone else finds this highly important please comment here if you want to work on it and submit a PR and we'll gladly assist in reviewing it.

**Comment by natellium** [comment] 2021-03-29 13:54
Closing this issue as is not a high priority and it's working in the current stable version (7.5.1)

**Closed by natellium** 2021-03-29 13:54 UTC
Labels: area/frontend, area/mobile-support, help wanted, type/bug, version/6
