### ISSUE TITLE
missing tooltip values

### ISSUE THREAD

**Issue by basking-in-the-sun2000** [grafana/grafana#36892] opened 2021-07-19 02:17 UTC
Tried to upgrade from the old graph panel to the time series. However, the tooltip isn't displaying the values continuously. 

The old graph panel would display the values from the previous value until a newer one.  I'm using _WHERE $timeFilter GROUP BY time($__interval) fill(linear)_ in the query. 

Below is an image to compare this issue. Seems one of the issues might be related to how the points are displayed. In the older graph panel, it would only display the points that matched the time interval.  The time series will display any point from any of the series

Also would be nice to be able to match the placement of the 0 line on both axis like you could before. 

Environment:

Grafana version: v8.0.6 (68fe9e3)
Data source type & version: InfluxDB (builtin)
OS Grafana is installed on: Linux raspberrypi 5.10.17-v7l+ UX - if auto-refresh is enabled, graph editing gets frustrating #1421
User OS & Browser: Mac OS 10.14.6 Safari and Firefox
Grafana plugins: Time-series

graph panel
<img width="352" alt="Screen Shot 2021-07-18 at 21 12 05" src="https://user-images.githubusercontent.com/61602111/126093242-748e6584-c48a-417c-bec6-e42b3e9a0adb.png">

time series panel
<img width="276" alt="Screen Shot 2021-07-18 at 21 12 24" src="https://user-images.githubusercontent.com/61602111/126093261-8c024b7e-8038-41ce-ac1f-6845a2c2dcf1.png">

**Comment by leeoniya** [comment] 2021-07-19 02:57
Duplicate of https://github.com/grafana/grafana/issues/31309

take a look at this PR https://github.com/grafana/grafana/pull/34552, and these demos of old vs new: https://github.com/grafana/grafana/pull/34552#issuecomment-858162775

i'm not sure we want to bring back the old behavior of showing the prior datapoint regardless of how far it is from the time shown in the tooltip header. you end up with situations like this where the green A-series shows as value 30 at 19:02, when in reality that value was at before 16:00 and the nearest value is actually the one right next to the cursor.

![image](https://user-images.githubusercontent.com/43234/126095942-601deeeb-69f6-4253-8ae8-565e0de11ada.png)

**Closed by leeoniya** 2021-07-19 02:57 UTC
