### ISSUE TITLE
[Feature Request] Rewrite url to https

### ISSUE THREAD

**Issue by matthgyver** [grafana/grafana#5066] opened 2016-05-17 11:56 UTC
Hi,
It would be nice if, when HTTPS is enabled, client url was rewritte in http**s**:// if he come in http.
Thank you

**Comment by torkelo** [comment] 2016-05-17 13:40
dupe of https://github.com/grafana/grafana/issues/2661

**Closed by torkelo** 2016-05-17 13:40 UTC
