### ISSUE TITLE
Unresponsive Prometheus datasource makes Panels with --Mixed-- datasource in which it is involved unresponsive.

### ISSUE THREAD

**Issue by itsx** [grafana/grafana#18348] opened 2019-08-02 09:48 UTC
**What happened**:
When one of the Prometheus datasources becomes unresponsive (gets down, a connection is lost, etc), Panels which uses this datasource as one of the datasources in **--Mixed-- datasource** get unresponsive. Content of the panel becomes empty (with exception of the title), just loading circle in the upper right corner of the Panel is rotating.

![image](https://user-images.githubusercontent.com/15692136/62360639-94fe1480-b519-11e9-810d-b1838061a27e.png)

![image](https://user-images.githubusercontent.com/15692136/62360839-02aa4080-b51a-11e9-9faa-79b26b9a115e.png)

**What you expected to happen**:

The panel will respond with some error pointing out which datasource is down, the content of the Panel will continue to work correctly as if the downed datasource in --Mixed-- datasource was deleted or disabled. For example in the Graph panel metrics from the healthy Prometheus datasources will continue to draw graphs. 

It would be nice if in for example Singlestat Math panel would be possible to render the number of Healthy/Unhealthy datasources from --Mixed-- datasource. It would expect that the return value from the unhealthy datasrouce (probably null), can be still used in the plugin math formula, although this is the responsibility of the plugin code, I suppose.          

![image](https://user-images.githubusercontent.com/15692136/62362047-79e0d400-b51c-11e9-8f35-0dff65b54e8e.png)

**How to reproduce it (as minimally and precisely as possible)**:

Create a new dashboard, create Graph panel.
Add a query with --Mixed-- data source: up{job="prometheus"} for Prometheus 1 datasource.
Add a query with --Mixed-- data source: up{job="prometheus"} for Prometheus 2 datasource.
Pause/kill/disconnect one of the Prometheus servers.
The panel becomes unresponsive, even that one of the datasources is still alive.

**Anything else we need to know?**:

**Environment**:
Grafana version: 6.2.5
Data source type & version: Prometheus
OS Grafana is installed on: Running as docker container (grafana/grafana) inside Ubuntu 18.04
User OS & Browser: Ubuntu 18.04, Chromium 75
Grafana plugins: default

**Comment by torkelo** [comment] 2019-08-02 12:54
duplicate of https://github.com/grafana/grafana/issues/4453

**Closed by torkelo** 2019-08-02 12:54 UTC
