### ISSUE TITLE
Dashboards: Repeating library panels duplicate unexpectedly when saved inside a closed row

### ISSUE THREAD

**Issue by hcrossman** [grafana/grafana#78563] opened 2023-11-22 22:04 UTC
### What happened?

When using a duplicated library panel inside a row if the dashboard is saved with the row collapsed the panel will create extra duplicates on expansion.
In the attached screen capture a library panel repeats horizontally for the values of `var_1` (`a`, `b`, & `c`). The dashboard is saved with the row collapsed and refreshed. The row still reads "3 panels" but on expansion it shows vertical replication also for a total of 9 panels

https://github.com/grafana/grafana/assets/151789067/4c7ec3e6-da2a-4570-8e21-ad4c5fea79d7

### What did you expect to happen?

To have only the horizontal repeats for a total of 3 panels. This works if the repeated panel is not a library panel.

### Did this work before?

No

### How do we reproduce it?

1. Create a variable and select multiple values for it
2. Create a panel that repeats horizontally for the values of that variable
3. Make the panel a library panel
4. Put the panel in a row
5. Save the dashboard with the row collapsed
6. Refresh browser (library panel changes seem to require a browser refresh to take effect)
7. Expand the row (to see extra duplicates)

### Is the bug inside a dashboard panel?

Don't have a "Get help" option, but can provide santized panel json if needed.

### Environment (with versions)?

Grafana: v10.1.4 (also tried on v9.4.14)
OS: Docker using linux/AMD64
Browser: Firefox

### Grafana platform?

Docker

**Comment by tonypowa** [comment] 2023-12-14 09:59
hi @hcrossman 
Thank you for creating this issue and for providing very clear repro steps
I have reproduced the issue, so I am forwarding it to the Dashboard team

**Comment by mampersat** [comment] 2023-12-14 14:29
+1

**Comment by mdvictor** [comment] 2024-10-30 09:57
Hello! This seems to be fixed in the new architecture, I couldn't reproduce in v11.3 anymore. I will close this for now, but please do reopen if there is anything else we can help with.

**Closed by mdvictor** 2024-10-30 09:57 UTC
Labels: type/bug, area/dashboard, area/templating/repeating, area/frontend/library-panels, team/grafana-dashboards
