### ISSUE TITLE
HealthCheck endpoint on Grafana

### ISSUE THREAD

**Issue by mwitkow** [grafana/grafana#3967] opened 2016-02-09 13:53 UTC
We're running Grafana behind a Load Balancer and we have a rolling-update mechanism for updates of our service. We'd like to have a way of telling whether the given instance of Grafana is healthy or not, for monitoring purposes. By healthy we mean whether Grafana has access to its Dashboard/User Database `[database]` and its Session Storage `[session]`. The idea is to have a `/api/health` endpoint that would return `200 OK` and a little bit of JSON information depending on what's up.

Is that something that upstream would be interested in if we were to send a PR?

**Comment by bergquist** [comment] 2016-02-09 17:31
@mwitkow yes we would :)

Im closing this issue since its a dupe of https://github.com/grafana/grafana/issues/3302 .
A PR would be very appreciated. But please make sure the check does not generate new sessions or reuse one.

**Closed by bergquist** 2016-02-09 17:31 UTC
