### ISSUE TITLE
[Bug] Pushover alerts return error 400: Bad request

### ISSUE THREAD

**Issue by jpeg2600** [grafana/grafana#8006] opened 2017-04-01 03:09 UTC
Hi there, first of all thank you all for the beautiful work. 

I came across what looks like a bug. Sending a pushover test works fine, but a real alert returns the following error in the log file: 

`t=2017-04-01T02:57:19+0000 lvl=eror msg="Failed to send pushover notification" logger=alerting.notifier.pushover error="Webhook response status 400 Bad Request" webhook=VanMorell`

**What Grafana version are you using?**
4.2.0

**What datasource are you using?**
Influxdb

**What OS are you running grafana on?**
Linux

**What did you do?**
generated a false alarm 

**What was the expected result?**
Get a notification on Pushover

**What happened instead?**
Nothing except the log entry above

Previous discussion about Pushover: [#7526](https://github.com/grafana/grafana/pull/7526)

**Comment by jcs** [comment] 2017-04-03 00:27
Pushover developer here.  If you want to [contact me](https://pushover.net/support) with the values you used for your user key and API token, I can try to find your specific API request and see what was wrong with it.

Ideally this plugin would actually log the body response in addition to the 400 status, since there is a useful error message there which says exactly why the request failed.

**Comment by jpeg2600** [comment] 2017-04-03 00:40
Hi, I sent both infos!

Thanks

**Comment by devkid** [comment] 2017-04-03 11:15
Hi.

The function used to execute the webhook should print out the response body if the error code is outside the 2xx range: https://github.com/grafana/grafana/blob/master/pkg/services/notifications/webhook.go#L100

Can you try enabling debug output for Grafana?

@jcs That being said, the caller of said function `sendWebRequestSync` (the Pushover plugin in this case) can't access the response body because it's not returned and so can't log the error message directly.

**Comment by jpeg2600** [comment] 2017-04-03 17:56
Hi there! 

I found out what the problem was. Something must be in the message notification details, it will send an error if that box is empty. 

An empty box works well with the other notification systems I tried, I would suggest that it does too with that plugin. 

Great work btw @devkid ! 

 `t=2017-04-03T17:43:22+0000 lvl=dbug msg="Sending webhook" logger=notifications.webhook url=https://api.pushover.net/1/messages.json http method=POST

t=2017-04-03T17:43:23+0000 lvl=dbug msg="Webhook failed" logger=notifications.webhook statuscode="400 Bad Request" body="{\"message\":\"cannot be blank\", \"errors\":[\"message cannot be blank\"],\"status\":0,\"request\":\"f340f4e2-9a42-48dd-80e4-47b0730221a4\"}"

t=2017-04-03T17:43:23+0000 lvl=eror msg="Failed to send pushover notification " logger=alerting.notifier.pushover error="Webhook response status 400 Bad Re                                               quest" webhook=VanMorell `

**Comment by devkid** [comment] 2017-04-03 19:55
The assumption that an empty message should not silently fail sounds reasonable. How do other notifier plugins handle empty messages? I can add it to the Pushover plugin.

**Comment by jpeg2600** [comment] 2017-04-03 20:03
You should try it using the email notification. The _message notification details_ box just add more information, but if you leave it empty it still sends out the different metrics of the graph sending the notification. 

To fix the problem for now, I just added a little message "Something needs your attention" on every alert. 

Would it be possible to add an option to attach the graph image as a link? That would be a great feature!

**Comment by devkid** [comment] 2017-04-04 13:45
@jpeg2600 Actually, empty messages work for me:

![Pushover Screenshot](https://dl.dropboxusercontent.com/s/9x4k72nhby4ib39/Screenshot_20170404-154030.png)

**Comment by jpeg2600** [comment] 2017-04-04 16:59
That's weird, because before I set some message I was getting the mentionned error with Pushover but the email it was sending at the same moment was working right. 

Is there any info I can give you to look further info the issue? 

Will you considerate adding the image URL? That would be useful for displaying the graph quickly on mobile.

**Comment by devkid** [comment] 2017-04-05 16:46
Can you reproduce the original error? The message itself should, in some way, include the alerting metric (see [here](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/pushover.go#L136)), so the message should never be empty.

I'll have a look into adding a link to the graph image.

**Comment by devkid** [comment] 2017-04-05 18:13
@jpeg2600 In case you can't reproduce the error, can you close this issue? And can you open another one for graph images?

**Comment by jpeg2600** [comment] 2017-04-05 19:36
I removed the notification details and tried to generate an alert and it worked fine. I'm closing the issue since I can't replicate it. 

Thank you @devkid and @jcs  for your time. I will open a feature request for the graph image option in a Pushover notification.

**Comment by devkid** [comment] 2017-04-09 16:44
@jpeg2600 Can you reopen this issue? I can now reproduce the error. When the alert state from "Alerting" to "OK" there are no metrics included in the error message, so all "OK" notifications will fail with the error you received.

Any suggestions for a default message?

**Comment by jpeg2600** [comment] 2017-04-09 19:24
@devkid Is a &nbsp; possible? That would be my only suggestion, but I don't know if that would be a good practice.

**Comment by jpeg2600** [comment] 2017-04-10 01:14
@devkid    Maybe you could let the user set a default message himself in the Pushover notifications options? It would be great if the "show graph" and "show dashboard with alert" texts could be editable there too!

I would use that option since the people getting the alarms mostly speak french.

**Comment by devkid** [comment] 2017-04-10 19:57
I don't really want to add more options to the configuration, I think the current texts should do well. I'm not sure if `&nbsp;` will work, Pushover seems to have a quite limited subset of HTML that is allowed inside messages. Maybe @jcs can comment on this as well?

**Comment by Artanicus** [comment] 2017-12-11 19:07
Any update here? All OK notifications are still failing with:
"Webhook response status 400 Bad Request"

**Comment by devkid** [comment] 2017-12-11 20:18
A quickfix is to just add a message to the notification.

**Closed** 2017-12-19 13:32 UTC
Labels: comp: alerting/notifications, type: bug
