### ISSUE TITLE
Stackdriver plugin always enforces Unit type from Target 

### ISSUE THREAD

**Issue by thechile** [grafana/grafana#15961] opened 2019-03-13 07:27 UTC
Hi

Using Grafana v5.4.2 and StackDriver plugin 1.0.0.

As per https://stackoverflow.com/questions/55102918/display-gcp-compute-instance-count-in-grafana-using-stackdriver/55112355?noredirect=1 

The Grafana StackDriver plugin enforces unit types bases on the selected metric which limits its usefulness. If i select Compute instance Uptime then the graph forces the unit to be in Seconds even though the desired output based on the aggregation is actually a short/none type i.e i just want to graph the raw value. Every time i try change the unit it resets back. 

Perhaps [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/stackdriver/datasource.ts#L101) .. can this be relaxed so its only the "suggested default" but doesn't prevent the unit being changed please.

**Comment by torkelo** [comment] 2019-03-13 07:30
duplicate of https://github.com/grafana/grafana/issues/13733

**Closed by torkelo** 2019-03-13 07:30 UTC
