### ISSUE TITLE
[Bug] Graph ignores Y-Min when Scale is used

### ISSUE THREAD

**Issue by Foxeronie** [grafana/grafana#8678] opened 2017-06-21 14:04 UTC
Hello everyone,

- What Grafana version are you using?
v4.3.2

- What datasource are you using?
Graphite

- What OS are you running grafana on?
Ubuntu 16.04 LTS

- What did you do?
Set scale to log (base 2) and Y-Min to 0

- What was the expected result?
A graph with a y axis starting at 0

- What happened instead?
A graph with a y axis starting at 1

Without the scale function:
![no_scale](https://user-images.githubusercontent.com/10115997/27388151-ff314bc2-569a-11e7-94fe-2aeb639c35fc.png)

With the scale function:
![scale](https://user-images.githubusercontent.com/10115997/27388155-02d8cae8-569b-11e7-9de6-c31cb97dc4e9.png)

Best regards,
Patrick

**Comment by torkelo** [comment] 2017-06-21 14:44
0 is not a valid value for a log scale. we have fixed this behavior in master  so when setting 0 it set it to 0.0001 (or something like that).

You should be able to do that manually in 4.3.2 (try setting y-min to 0.1)

**Comment by daniellee** [comment] 2017-06-21 14:44
Duplicate of #8516 and fixed in master: https://github.com/grafana/grafana/commit/1b79e179707f2f6d220e295a1474fef3b9e8b36a

**Closed by torkelo** 2017-06-21 14:44 UTC
