### ISSUE TITLE
Alerting: Supporting custom datasource

### ISSUE THREAD

**Issue by dmitrios** [grafana/grafana#6198] opened 2016-10-05 16:13 UTC
It appears that alert executors for grafana and prometheus are defined under /tsdb, but not in respective plugins. If alerting is designed to be open closed, it  would be helpful to provide best practice for implementing custom datasource to support it.

**Comment by bergquist** [comment] 2016-10-06 06:15
We wont support plugins for alerting in grafana 4.0 but we will support it at some point in the future.
In the meantime we will write up better docs about how to implement custom datasources in /tsdb

**Comment by bergquist** [comment] 2016-12-09 13:33
Depends on https://github.com/grafana/grafana/issues/6841

**Comment by bergquist** [comment] 2016-12-09 13:43
Closing this since it kinda of a dupe of https://github.com/grafana/grafana/issues/5858

**Closed by bergquist** 2016-12-09 13:43 UTC
Labels: comp: alerting, type: feature request
