### ISSUE TITLE
CloudWatch Alias for Dimension values does not work in Code mode

### ISSUE THREAD

**Issue by justinTM** [grafana/grafana#45189] opened 2022-02-10 01:52 UTC
**What happened**:
When I use `{{DbInstanceIdentifier}}` in the `Alias` field of a Grafana dashboard panel editor, the panel shows literally `{{DBInstanceIdentifier}}` instead of replacing with the value(s) of the dimension.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/9123665/153321841-9bd65172-7815-4e22-beeb-0a0af8b8998f.png">

**Comment by zoltanbedi** [comment] 2022-02-10 10:59
This only works in the Metrics search. See the documentation for possible values https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#common-metric-query-editor-fields

**Comment by zoltanbedi** [comment] 2022-02-10 12:22
Right, sorry. I could also reproduce this issue.

**Comment by zoltanbedi** [comment] 2022-02-10 12:22
Right, sorry. I could also reproduce this issue.

**Comment by jangaraj** [comment] 2022-02-10 16:44
Actually, this bug looks like CloudWatch feature, where CloudWatch doesn't return dimension tag/value, when there is only one value for them. I bet it will be interpolated correctly if you filter for all instances, e.g.`DBInstanceIdentifier="*"` (of course you need to have metrics for at least 2 instances). AWS support has recommended to use dynamic legend if I remember correctly (which is not available in the Grafana). Anyway, you have variable, so I would use that variable in the alias definition instead of fighting with CloudWatch features.

**Comment by jangaraj** [comment] 2022-02-10 18:54
OK, how your panel json looks like and how query response from the query inspector looks like? What is the value of productToken variable?

**Comment by fridgepoet** [comment] 2022-02-15 11:04
Hi @justinTM, it's not a supported alias pattern. I tried out the [documentation's](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#common-metric-query-editor-fields) possible value `{{label}}` in a query similar to yours and I have `AWS/RDS {your db instance identifier here} CPUUtilization` as the value under the gauge. Hope that'll work for you.

**Comment by fridgepoet** [comment] 2022-02-15 14:16
Sorry @justinTM thanks to @sarahzinger I've been able to properly reproduce the issue and a workaround. 
There seems to be a bug somewhere between the query `builder` and the `code` mode which we're going to investigate.

Here's the workaround to get the label `DBInstanceIdentifier` (in the response under `labels`... this doesn't seem to be documented yet). 
1. Go to Builder mode
2. Choose AWS/RDS
3. Add the dimension DBInstanceIdentifier with the value that you want ($productToken in your case). 
4. The alias {{DBInstanceIdentifier}} should now work.

**Comment by fridgepoet** [comment] 2022-08-11 08:56
With dynamic labels enabled, `${PROP('Dim.DBInstanceIdentifier')}` should be working for this case in Code mode.

**Closed by fridgepoet** 2022-08-11 08:56 UTC
Labels: datasource/CloudWatch
