### ISSUE TITLE
[Bug] Running multiple Grafanas on the same server

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#9933] opened 2017-11-20 12:47 UTC
Read before posting: 

Please include this information:
- What Grafana version are you using? Docker containers **grafana/grafana:master**
- What datasource are you using? **InfluxDB**
- What OS are you running grafana on? **Ubuntu 17.04**
- What did you do? **Running 5 Grafana instances using Docker containers**
- What was the expected result? **All Grafana instances should be absolutely separeted**
- What happened instead? **Seems like one Grafana instance on one server is disturbing another one automatic login on another server**

I know that Grafana uses a cookie to keep its sessions. 
All 5 different Grafanas has different "cookie_name" variable. 
They also have different "instance_name".
I know that due to cookie limitation port number is not included in cookie name, so all Grafanas must use different cookie names.
The more interesting:
I have 5 Grafanas on the test server.
I have 5 Grafanas on the production server, they also use different cookie names (all test instances also have "_test" suffix added). There is also an old legacy production server that runs single Grafana (non dockerized) but also uses different cookie name.
So I have 11 Grafanas on 3 different servers, all of them using other instance_name and cookie_name.

The problem:

On one instance (and only this one) anonymous login sometimes work, and sometimes it redirects to Login page. Anonymous login is enabled in all 11 Grafanas, organization names are correctly defined, default role is "Read Only Editor". 
Only in one organization (the one used on 3 servers) I see that if I "Sign In" on one server, then another one redirects to login form. Looks like some kind of shared cookie between them.
This is very strange because they use different domain, so even if the cookie name is exactly the same, cookie domains differ - so one server should not have any possibility to change other server's auth process.
I would expect problems with dockerized instances on the same server, but I don't have idea what's going on here.

Maybe I'm doing something terribly wrong?
I've seen similar issues here, but they were related to multiple Grafanas on the same server, and setting "cookie_name" was the solution.

Of course, I was trying to clear caches, cookies, history, using different browsers etc.
I've also enabled debug log level for this Grafana and examined docker logs but found nothing saying why Grafana redirected to login page.

And I know that after sign off it redirects to /login url - this is normal and I want this to be able to login as admin and add dashboards etc. But even when I manually remove "/login" from url it still redirects to "/login", clearing all browser caches, cookies sometimes help. But also signing off from another server may help, or clearing cache won't help and I need to sign in and sign off on another server.

**Comment by bergquist** [comment] 2017-11-21 07:53
What kind of database are you using? Have you configured a shared session store?

Grafana relies on the session store for syncing session data between instances. (rewriting auth to work with cookies only is on our long-term roadmap)

**Comment by lukaszgryglicki** [comment] 2017-11-21 08:10
BINGO!
I'm using Influx.
I also have Postgres there (not used by Grafana).
So I will try to change session storage to Postgres!!

Thanks thanks THANKS!

**Comment by bergquist** [comment] 2017-11-21 08:12
No Problemo!

**Comment by bergquist** [comment] 2017-11-21 08:13
Feel free to close this issue once you confirmed that its fixed :)

**Comment by lukaszgryglicki** [comment] 2017-11-21 08:14
I will, but this may take another full day.
I just have no data to check this atm, and fortunately this only happens on a new production server candidate, not a real production one - so this is not critical atm.

**Comment by lukaszgryglicki** [comment] 2017-11-21 13:03
I can confirm 99% that using Postgres as session storage fixed the issue. I'll make some 100 more refreshes, sign-ins, sign-outs using multiple tabs and will see...

https://k8s.cncftest.io
https://prometheus.cncftest.io
https://opentracing.cncftest.io
https://fluentd.cncftest.io
https://linkerd.cncftest.io
https://k8s.devstats.cncf.io
https://prometheus.devstats.cncf.io
https://opentracing.devstats.cncf.io
https://fluentd.devstats.cncf.io
https://linkerd.devstats.cncf.io
https://devstats.k8s.io

If I manage to replicate the issue again, I'll reopen.

THANKS again for an advice!

**Comment by bergquist** [comment] 2017-11-21 14:32
@lukaszgryglicki cool! in 5.0 we will introduce dashboard folders. Might make it possible to combine them into one instance?

**Comment by lukaszgryglicki** [comment] 2017-11-21 14:55
At least in 2 instances: prod (with current 5 instances) and test (with another 5 instances).
One legacy prod will come offline.

**Comment by lukaszgryglicki** [comment] 2017-11-21 15:14
Happened again, after about 1 hour idle.

Maybe I should have multiple session databases on the same server? I mean one Postgres database per single dockerized Grafana instance?

I'm now using shared Postgres database "grafana_sessions" with single table "session" - just like in documentation.

Is this OK?

**Comment by torkelo** [comment] 2017-11-21 15:33
> I'm now using shared Postgres database "grafana_sessions" with single table "session" - just like in documentation.

Yes, if all those grafana servers share grafana database & users (and cookie name)

**Comment by lukaszgryglicki** [comment] 2017-11-21 15:39
cookie name is now the same for all instances, but it was different.
Grafana database is different, each instance uses its own SQlite3 database saved in different location.

So the solution should be for all Grafanas (on a single host)
- The same sessions database (Postgres) - already done.
- The same cookie name (;cookie_name = grafana_sess) - all of them use default now - so done.
- The same Grafana database.... all of them use a different SQlite3 database, but if I use the same, then I will have the same dashboards on all, right?

What should I do to have totally independent 5 Grafanas on the same server, each of them showing different dashboards, with different data sources (each using different Influx database name but the same influx database server), with enabled anonymous access?

**Comment by lukaszgryglicki** [comment] 2017-11-21 15:56
Something like how to achieve this architecture:
- I have N InfluxDB databases running on the host (single `influxd` process)
- I Have N Postgres databases running on the host (single `postgres` process), it is used by cron job tools that compute metrics values for each Grafana (this proces computes set of metrics on every Postgres datbase and saves results on every InfluxDB databases, so Grafanas has already computed simlest possible time series to display on each instance)
- I have N Grafanas running on the host using docker containers, each of them has different dashboards list and uses different InfluxDB database (they connect to single `influxd` instance but each uses different database), each of them has its /var/lib/grafana, /etc/grafana, /usr/share/grafana mapped to host directories /var/lib/grafana.proj_name, /etc/grafana.proj_name, /usr/share/grafana.proj_name - which means each of them has own config, SQLite database, etc.
- Each docker Grafana maps `-p 127.0.0.1:300X:3000`, so I have instances on ports 3001, 3002, 3003, ..., 300N
- There is an Apache server running that maps different domains (wildcard domain *.cncftest.io) to any of those Grafanas (it is used to enable HTTPS/SSL, disable plain HTTP access, provide Let's encrypt certs). So for example apache maps: https://domain1.cncftest.io --> http://localhost:3001, then https://domain2.cncftest.io --> http://localhost:3002, ..., https://domainN.cncftest.io --> http://localhost:300N
- There is a shared Postgres database "grafana_sessions" that is available for all those Grafanas via pg_hba.conf for docker address `172.17.0.0/24` (no Postgres access from outside).
- Currently, all of those Grafanas use the same cookie name, but I can set them to use different cookie names.
- All of them have different instance_name (if that matters), and all of them has anonymous access enabled (each have different Org name, anonymous user is Read Only Editor)

I want all of them to be totally independent, I don't know why they disturb each other... they run on different domains.

Any suggestions what Am I doing wrong?

**Comment by lukaszgryglicki** [comment] 2017-11-22 08:50
I'm testing approach with separate Postgres databases for session storage for each Grafana instance, seems to work ATM.
Would be great to get some feedback - is it supposed to work? Should it work? It is not documented anywhere:

- Each Grafana now has different cookie_name, instance_name and different Postgres database for session storage. Each has a different SQListe3 database to keep its dashboards (separate folders, files).

**Comment by lukaszgryglicki** [comment] 2017-11-22 09:13
Still seems like sometimes it requires login, but also seems like browser cache is related with this... any ideas?

**Comment by bergquist** [comment] 2017-11-22 09:38
> I'm testing approach with separate Postgres databases for session storage for each Grafana instance, seems to work ATM

Per instance is not a good way. One session store per stats project would be the prefered way. 

Ex

k8s pod 1 
k8s pod 1 
k8s pod 1 


 k8s stats replication set, one for prometheus stats.

**Comment by lukaszgryglicki** [comment] 2017-11-22 09:46
```
Per instance is not a good way. One session store per stats project would be the prefered way.

Ex

k8s pod 1
k8s pod 1
k8s pod 1

k8s stats replication set, one for prometheus stats.
```
Hmm, I've tested shared Postgres database, then separate databases per docker instance.
Both were not working.
I've tried different cookie name, the same cookie name, my first approach was using default storage with different cookie names.

My guess is that the browser is a problem, it looks really like something related to cookies conflict or session config. No idea how can I help.

My next step would be to clone Grafana repo and to dive into its sources, compile, figure out how things work.... and if I manage to fix it - I'll create PR.

**Comment by lukaszgryglicki** [comment] 2017-11-22 09:47
I don't have pods at all and k8s at all.
I have N docker Grafanas, each is keeping dashboards list for the specific project.
All of them run on the same machine, behind apache proxy.
Apache proxies to a specific docker instance depending on the current domain name.

**Comment by lukaszgryglicki** [comment] 2017-11-22 11:17
@bergquist Can You point me to right places in Grafana sources that I should start working on it?
I mean some directions to where sessions, cookies related code is?
And maybe how to compile Grafana locally?
That would help me a lot tomorrow.

Not needed if You don't have time, I can dig everything myself tomorrow.

**Comment by bergquist** [comment] 2017-11-22 12:59
Sorry!!! I totally misunderstood your setup. 

If your only running one instance then storing sessions in postgre doesn't make sense. Just keep them on disk in the container (default). If you are mounting the grafana containers to local disk, make sure they dont share the same folders. Each container need their own sessions on disk. 

As you said earlier this should just work out of the box. 

I can currently reproduce this on https://prometheus.devstats.cncf.io do you see anything in the logs in that container?

**Comment by bergquist** [comment] 2017-11-22 13:31
https://github.com/cncf/devstats/blob/master/grafana/kubernetes/docker_grafana_run.sh Seems like all instances have their own data dir. So sessions should not be a problem.

**Comment by bergquist** [comment] 2017-11-22 13:52
I think we need more debug logs for this.. 

btw are you on the cncf slack? might be easier to chat there.

**Comment by lukaszgryglicki** [comment] 2017-11-22 13:57
All instance are using separate folders, separate postgres databases, different cookie names...
yet they conflict somehow.

**Comment by lukaszgryglicki** [comment] 2017-11-22 14:02
And exactly, all should just work according to docs and everything I know.

**Comment by bergquist** [comment] 2017-11-22 14:25
Any chance you can enable extremely verbose logging in apache? that might help us find the error faster than adding logs in Grafana. I will add logs tomorrow when I get back to work.

**Comment by lukaszgryglicki** [comment] 2017-11-22 14:38
Sure I'll try to enable maximum verbose Apache logs.

**Comment by lukaszgryglicki** [comment] 2017-11-22 14:58
Enabled apache2 debug log level.
Let's wait some time and then I can grep those lots or even put them somewhere accessible for all.

**Comment by lukaszgryglicki** [comment] 2017-11-22 15:42
Apache debug logs are available to download
https://cncftest.io
section: Devstats Apache debug logs
for example: https://cncftest.io/error.log

**Comment by torkelo** [comment] 2017-11-22 15:51
there are 3 cookies, the session cookie, username cookie and the remember_cookie , are all differently named?

**Comment by lukaszgryglicki** [comment] 2017-11-22 15:54
No, they are not
Only `cookie_name`
WOW: this may be another BINGO!
Will check tomorrow!

**Comment by lukaszgryglicki** [comment] 2017-11-22 15:55
I see in grafana.ini: cookie_name, cookie_username, cookie_remember_name
only cookie_name differs.

**Comment by lukaszgryglicki** [comment] 2017-11-22 15:59
But if nobody actually authorizes (none but me knows the password) the should they conflict?

**Comment by torkelo** [comment] 2017-11-22 17:03
Not sure what you mean, the remember me cookie will conflict if you login on two instances on same domain if the cookie name is the same

**Comment by lukaszgryglicki** [comment] 2017-11-22 17:26
Well, let's assume that somebody doesn't know any password.
And then uses all Grafanas - usually, all works fine (anonymous access is ok) but sometimes you are redirected to /login page and you cannot access as an anonymous user anymore - even if you manually change /login URL to some existing dashboard - you will be redirected to /login page again.
You don't know the password and you never authorized before.

**Comment by torkelo** [comment] 2017-11-22 19:20
That could not happen unless authentication was denied, maybe due to invalid remember cookie. The scenario you described sound strange, you mean anonymous access is randomly turned off? That behaviour has never been reported before :)

**Comment by bergquist** [comment] 2017-11-22 19:49
Could it be due to old cookies from earlier test run?

**Comment by lukaszgryglicki** [comment] 2017-11-22 19:53
It looks like this, I'll report if setting all 3 cookie names differently for all Grafanas would help.

**Comment by lukaszgryglicki** [comment] 2017-11-23 07:26
So setting all 3 cookies names different won't helped.
For k8s cookies are: k8s_grafana_sess, k8s_grafana_user, k8s_grafana_remeber
It is usually working but sometimes happen that after I sign that additional cookie appears "grafana_sess" (this is the default name).
In this case I have those 3 cookies plus "grafana_sess".
And in this case I cannot go anywhere - it redirects to /login.
It seems like Grafana is thinking that we're authorized (because of k8s_grafana_user and k8s_grafana_remeber cookies) but it also has k8s_grafana_sess and grafana_sess session cookies.
Probably it uses wrong one and things that my session is broken and redirects to /login.
Screenshot of cookies:
![screen shot 2017-11-23 at 08 16 54](https://user-images.githubusercontent.com/2469783/33162018-7822ab60-d027-11e7-9164-b2e64d43e29f.png)

And now screenshots of all other GRfafanas that are OK and have correct cookies, some of them using anonymous access and some of them using admin account:

![screen shot 2017-11-23 at 08 24 17](https://user-images.githubusercontent.com/2469783/33162079-e806de2e-d027-11e7-87c2-c2e56684b70c.png)
![screen shot 2017-11-23 at 08 24 21](https://user-images.githubusercontent.com/2469783/33162080-e82357de-d027-11e7-88da-ed418b13b825.png)
![screen shot 2017-11-23 at 08 23 46](https://user-images.githubusercontent.com/2469783/33162081-e83dfec2-d027-11e7-8aef-7e298f5a5c14.png)
![screen shot 2017-11-23 at 08 23 52](https://user-images.githubusercontent.com/2469783/33162082-e8576420-d027-11e7-98d2-ccc39bec80a9.png)
![screen shot 2017-11-23 at 08 23 56](https://user-images.githubusercontent.com/2469783/33162083-e871024a-d027-11e7-9d27-aa0fe0f0a7cd.png)
![screen shot 2017-11-23 at 08 24 00](https://user-images.githubusercontent.com/2469783/33162084-e88a8cce-d027-11e7-9d47-9b64c4077301.png)
![screen shot 2017-11-23 at 08 24 04](https://user-images.githubusercontent.com/2469783/33162086-e8a593c0-d027-11e7-9417-85405c9d8159.png)
![screen shot 2017-11-23 at 08 24 07](https://user-images.githubusercontent.com/2469783/33162087-e8bfb8fe-d027-11e7-8582-061f3d6b39d2.png)
![screen shot 2017-11-23 at 08 24 10](https://user-images.githubusercontent.com/2469783/33162088-e8d93680-d027-11e7-8f22-1c4b9f5dbb12.png)
![screen shot 2017-11-23 at 08 24 14](https://user-images.githubusercontent.com/2469783/33162090-e8f2967a-d027-11e7-8a97-4e85cbcbd784.png)


My guess is that Grafana is using default cookie name in some rare cases (skipping value from config file). So the problem is not that Grafanas conflict each other but maybe rather because single instance uses two cookie names for session storage, and they conflict?

**Comment by torkelo** [comment] 2017-11-23 08:25
But seeing that each site has it's own sub-domain and the cookie is on the full domain it should not be possible for a cookie from one domain to be sent to another.

**Comment by lukaszgryglicki** [comment] 2017-11-23 08:50
Yes exactly, but I see two session related cookies "k8s_grafana_sess" and "gfrafana_sess" on a single domain at the same time. First screenshot.
It means that even when I set cookie_name, clear all cookies and play with **single** Grafana it can generate two cookies for session and one of them uses default name and anothe rone uses name defined in grafana.ini.
Why?

**Comment by torkelo** [comment] 2017-11-23 09:24
That is super strange, changed my config option for session cookie name and tried to login and out and clear cookies to trigger login redirect, also enabled anonymous access. No cookie with the default name showed up yet :(

**Comment by lukaszgryglicki** [comment] 2017-11-23 09:35
Well, this is what I see, this is also strange for me.
I'm struggling with this problem 4 days.
I'm not saying that Grafana is guilty there, but I really have no idea what else can be wrong, I've triple checked everything - maybe I'm missing something.

**Comment by lukaszgryglicki** [comment] 2017-11-24 06:45
Now I've narrowed down the bug to "grafana_session" cookie.
It only happens when this cookie appears.
I'm not able to say when this cookie appears, but it just happens sometimes, and then it seems like cookie names conflicts.
Already reproduced on:
k8s.devstats.cncf.io
prometheus.devstats.cncf.io
opentracing.cncftest.io

The scenario is the same:
On a single browser tab we have two conflicting (IMHO) cookies:
k8s_grafana_sess vs. grafana_sess on k8s.devstats.cncf.io
prometheus_grafana_sess vs grafana_sess on prometheus.devstats.cncf.io
opentracing_grafana_sess_test vs grafana_sess on opentracing.cncftest.io

And if I remove cookie using browser developer tools (Safari or Chrome) - the problem is away until next time, which is quite rare.

**Comment by bergquist** [comment] 2017-11-24 07:56
Would it be possible to reproduce this without passing thru apache? Would be nice to narrow down the problem.

**Comment by lukaszgryglicki** [comment] 2017-11-24 08:08
I'll set up such env in a few minutes and will let You know here - I'll include links using raw IP and port numbers, but now I need to reenable raw IP access.

**Comment by lukaszgryglicki** [comment] 2017-11-24 08:35
Implemented in: https://github.com/cncf/devstats/commit/eaa99cd1335968cbfb3a9ccd3ad28a089ac595f3
And: https://github.com/cncf/devstats/commit/d91877af5e95223a7d8e65f5e6f1ce65daf27abd

This is K8s instance: 147.75.78.47:2999
This is Prometheus instance: 147.75.78.47:3001
This is OpenTracing instance: 147.75.78.47:3002
This is Fluentd instance: 147.75.78.47:3003
This is linkerd instance: 147.75.78.47:3004

None of them uses Apache proxy now, they're using plain HTTP and direct Grafanas on their dockerized ports.

**Comment by lukaszgryglicki** [comment] 2017-11-24 09:04
For example now 2999 seems totally broken, no idea why, not restarting it because maybe I'll find **anything** in the logs?

**Comment by lukaszgryglicki** [comment] 2017-11-24 09:32
Now 2999 instance is not responding, even locally: links 127.0.0.1:2999 waits forever, while 3001 works OK.
And logs are the same:
2999:
```
2017-11-24 09:30:12 root@devstats:~# docker logs k8s_grafana
t=2017-11-24T08:32:28+0000 lvl=info msg="Starting Grafana" logger=server version=4.7.0-pre1 commit=a534ac4 compiled=2017-11-14T11:42:45+0000
t=2017-11-24T08:32:28+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-11-24T08:32:28+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-11-24T08:32:28+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-11-24T08:32:28+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-11-24T08:32:28+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-11-24T08:32:28+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2017-11-24T08:32:28+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-11-24T08:32:28+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-11-24T08:32:28+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-11-24T08:32:28+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-11-24T08:32:28+0000 lvl=info msg="App mode production" logger=settings
t=2017-11-24T08:32:28+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-11-24T08:32:28+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-11-24T08:32:28+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-11-24T08:32:28+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-11-24T08:32:28+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-11-24T08:32:28+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-11-24T08:32:28+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-11-24T08:32:28+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-11-24T08:32:28+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-11-24T08:32:28+0000 lvl=info msg="Initializing Stream Manager"
t=2017-11-24T08:32:28+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
```

3001:
```
2017-11-24 09:30:21 root@devstats:~# docker logs prometheus_grafana
t=2017-11-24T08:32:29+0000 lvl=info msg="Starting Grafana" logger=server version=4.7.0-pre1 commit=a534ac4 compiled=2017-11-14T11:42:45+0000
t=2017-11-24T08:32:29+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-11-24T08:32:29+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-11-24T08:32:29+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-11-24T08:32:29+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-11-24T08:32:29+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-11-24T08:32:29+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2017-11-24T08:32:29+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-11-24T08:32:29+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-11-24T08:32:29+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-11-24T08:32:29+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-11-24T08:32:29+0000 lvl=info msg="App mode production" logger=settings
t=2017-11-24T08:32:29+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-11-24T08:32:29+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-11-24T08:32:29+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-11-24T08:32:29+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-11-24T08:32:29+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-11-24T08:32:29+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-11-24T08:32:29+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-11-24T08:32:29+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-11-24T08:32:29+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-11-24T08:32:29+0000 lvl=info msg="Initializing Stream Manager"
t=2017-11-24T08:32:29+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
2017-11-24 09:30:33 root@devstats:~# 
```

**Comment by lukaszgryglicki** [comment] 2017-11-24 10:45
And now after some time, it works again, I've especially didn't touched it at all.
Nothing new in the logs...

**Comment by torkelo** [comment] 2017-11-24 11:15
Very strange, a networking issue perhaps? No other reports of unresponsive grafana. But your running master build right? So maybe an issue introduced in master recently

**Comment by lukaszgryglicki** [comment] 2017-11-24 11:30
Yes, it is master build, I need to have a version with recently added features. Like sorting stacked series in the legend order.
It doesn't seem like a network issue because I wasn't able to connect to that instance locally (from within server):
`ssh root@147.75.78.47` and then links `127.0.0.1:2999`.
After some time, it just worked, without any intervention from my side (I was doing other tasks) and no info in logs.

**Comment by lukaszgryglicki** [comment] 2017-11-24 18:23
Wow, I saw other's Grafana data source to in "data source selection" onk8s.devstats.cncf.io, but when I clicked it - red box "Unauthorized" appeared and then I was redirecte to the login page.
Really strange things happen here - they're on different VirtualHosts... use different session Postgres databases, different cookie names (all 3 cookies).

**Comment by torkelo** [comment] 2017-11-24 18:49
Strange, maybe a chrome extension to blame? We are running thousands of grafana instances on sundomains of grafana.net without seeing this issue, but we don't switch between them a lot and most don't have anonymous access enabled so maybe not a the best comparison. 

What browser are you using?

**Comment by lukaszgryglicki** [comment] 2017-11-24 19:06
Chrome on Mac, Safari on Mac, FF on Mac.
On the server--> lynx, links.

**Comment by torkelo** [comment] 2017-11-25 06:58
Your being redirect to login an all browsers? The caching issue of sering another instance datasource list what browser was that in?

**Comment by lukaszgryglicki** [comment] 2017-11-25 07:47
Happened randomly on all browsers.
But now I see sometimes some instances of Grafana are not responding, but only on one server.
Configs are the same.
OS-es are the same.
Grafanas are the same.
Docker versions are the same.

But...
One host needed docker tweaks to make it run: it needed to disable apparmour and use aufs instead of overlay2.
This server has also different Linxu kernel version.
And only on THIS server docker grafanas seems frozen sometimes *.devstats.cnf.io. Maybe some deeper docker issue?

**Comment by bergquist** [comment] 2017-11-25 08:13
I also started suspect docker. 
Browsing your repo it seems like all grafana instances can be recreated from scratch from scripts. right?
If thats the case. Could you try avoid mapping `/var/lib/grafana` and `/usr/share/grafana` to the host node? I think you only need `/etc/grafana` for the config.

Depending on how many changes you have in your grafana.ini you might be able to provision grafana using environment variables instead. ex http://docs.grafana.org/administration/provisioning/#using-environment-variables

**Comment by lukaszgryglicki** [comment] 2017-11-25 08:40
I need `/usr/share/grafana` because of my local changes to js files (renaming window titles etc) and custom icons.
I need `/var/lib/grafana` because grafana.db is there - I don't want to risk losing when it is inside the container because recreating all 30+ dashboards manually takes a long time.

I can use grafana environment provision from cmd line - I've just used ini approach at the beginning. I don't think it will change anything.

**Comment by torkelo** [comment] 2017-11-25 09:04
We can try to setup a docker compose file with 4 grafana instances on different ports to see if we can replicable anything similar. But does sound a like a docker networking or docker volume related issue but not sure how it can cause all your reported problems

**Comment by lukaszgryglicki** [comment] 2017-11-25 09:18
That's the only problem - I have no idea how Docker can cause such kind of problems.

**Comment by lukaszgryglicki** [comment] 2017-11-29 07:47
At first glance (after 2 days running) seems like the problem is gone when using native Grafanas instead of Docker.
But I didn't change anything more, this was just enough.
I have no idea why Docker could cause such kind of problems? Any clue?

**Comment by bergquist** [comment] 2017-12-27 11:13
I'm closing this since it seemed to be a docker issue. 

Poke me if you want me to reopen :)

**Closed by bergquist** 2017-12-27 11:13 UTC
Labels: state: needs more detail

**Comment by sinelaw** [comment] 2018-10-24 09:43
Reproduced here, no docker - just 4 different ports on the server.
(Is the cookie based only on the host name?)
