### ISSUE TITLE
Gravatar disabled leaving no visual indicator for profile menu circle

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [grafana/grafana#11177] opened 2018-03-09 11:51 UTC
### What Grafana version are you using?
`v5`

### What datasource are you using?
`mysql`

### What OS are you running grafana on?
`arch`

### What did you do?
upgraded to 5 from 4.6.3 with gravatar images disabled

### What was the expected result?
be able to visually see where the profile / switch org menu is located on the left hand menu bar

### What happened instead?
As no profile image was available the profile circle on the menu bar was black on black leaving almost no visual indicator there is a menu circle there.

Perhaps a default user image would be viable? Something like http://www.wilwia.com/images/default-user.png but obviously not this exact image..

**Comment by marefr** [comment] 2018-03-09 15:43
Dupe of #11097

Please upgrade to v5.0.1 where this should be fixed.

**Closed by marefr** 2018-03-09 15:43 UTC
