### ISSUE TITLE
Panel: can't change legend show

### ISSUE THREAD

**Issue by yincongcyincong** [grafana/grafana#97634] opened 2024-12-09 11:23 UTC
### What happened?

everytime i change `legend` to custom. i can't change it back to `auto` or `verbose`
https://github.com/user-attachments/assets/787e53be-f515-43c0-bcfd-44807432008d

### What did you expect to happen?

when i delete all custom input content. i can choose `auto` or `verbose`

### Did this work before?

yes

### How do we reproduce it?

1. create a panel 
2. change legend to custom
3. delete all custom input content

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: 11.4.0
OS: macos
Browser: chrome

### Grafana platform?

None

**Comment by bobdanek** [comment] 2024-12-09 20:51
I'm running into the exact same problem that your attached video shows - I can't clear the text field and I can't get the dropdown back.

Since it's also happening for me in Explore, not just in dashboards, I'll share some more info:

### How do we reproduce it?

1. go to Explore and select a prometheus/mimir datasource, then run a query 
2. change legend to custom and type in something, like `{{cluster}}`
3. select all text in the custom legend field and delete - notice all text is immediately restored
4. delete the text in the custom legend field one character at a time. when the last character is deleted, the whole string gets restored.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 11.4.0-79828
OS: nixos (unstable, kde/plasma6)
Browser: firefox 133.0

### Grafana platform?

Grafana Cloud

### Datasource(s)?

Mimir

**Comment by NWRichmond** [comment] 2024-12-09 21:01
This should be fixed by https://github.com/grafana/grafana/pull/97551

**Comment by NWRichmond** [comment] 2024-12-10 14:13
Closing for now, but we can reopen if needed.

**Closed by NWRichmond** 2024-12-10 14:13 UTC
Labels: type/bug, datasource/Prometheus, area/panel/edit, type/regression, area/legend, automated-triage
