### ISSUE TITLE
Pressing "e" on a panel causes it to crash

### ISSUE THREAD

**Issue by ZuperZee** [grafana/grafana#38692] opened 2021-08-30 09:28 UTC
**What happened**:
Pressing "e" on a panel to exit edit mode on a panel then pressing "e" again on a different panel causes the page to crash.

https://user-images.githubusercontent.com/39485579/131318319-add7e94e-1c53-42e9-84a8-97cd42f911bb.mp4

**What you expected to happen**:
Open the panel in edit mode

**How to reproduce it (as minimally and precisely as possible)**:
1. Create two panels (must be different types of panels. example gauge and singlestat)
2. Press "e" on one of them to enter edit mode
3. Press "e" again to exit edit mode
4. Press "e" on the other panel

**Anything else we need to know?**:
Needs to be different types of panels and seems to happen to most panels.

**Environment**:
- Grafana version: v8.1.2
- Data source type & version:
- OS Grafana is installed on: Windows 10 on a Ubuntu v20.04 WSL docker container
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

**Comment by mckn** [comment] 2021-08-30 12:23
Thanks for opening this issue. I can reproduce this on `8.1.2` image but when testing it on main (38b398feb44edda1bc2c4cd27d0b460d60b43876) I cant reproduce it. 

I will try to figure out what change have fixed this and also make sure it will be included in the next patch release.

**Comment by mckn** [comment] 2021-08-30 12:24
Closed by the following PR: https://github.com/grafana/grafana/pull/38646 Fix will be released in `8.1.3`.

**Closed by mckn** 2021-08-30 12:24 UTC
