### ISSUE TITLE
Request : Allow to set custom time range per Dashboard

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#15186] opened 2019-02-01 08:46 UTC
It would be a great addition if we can manage the range in the Time Picker in the top right corner.
With this, you can setup restriction upon time picker and limit the ressources used when users choose very large time range and limit the range of the data gathered.
If we can setup custom Quick range picker, we also need to hide the Custom Range Picker.
If we can also setup Custom Range directly in the Quick Range it would be great.

![image](https://user-images.githubusercontent.com/33425208/52112148-f6463900-2605-11e9-8b7c-98ea7d2c6b1f.png)

Like this, if it is possible to setup Custom Range Picker directly into the Quick range and select a time range only for certain time like a Custom Range of "now-30d to now-29d" to "29 Days Ago".

**Comment by torkelo** [comment] 2019-02-01 13:19
duplicate of https://github.com/grafana/grafana/issues/9814

**Closed by torkelo** 2019-02-01 13:19 UTC
