### ISSUE TITLE
Alert conditions are partially hidden and unusable 

### ISSUE THREAD

**Issue by Christoph-AK** [grafana/grafana#59413] opened 2022-11-28 15:35 UTC
When creating a new alarm for Loki the alert condition is partially hidden and can't be used nicely. (Edge on windows 11)

<img width="830" alt="image" src="https://user-images.githubusercontent.com/72923608/204316923-534d92d8-1264-459b-aa60-6f35d0e7da3b.png">

**Environment**:
Grafana v9.4.0-90524pre (e033775264) on Docker

**Comment by mellieA** [comment] 2022-11-29 18:58
@Christoph-AK which version of Edge are you using? 

I don't see this on Grafana 9.2.5 with the latest version of Edge. It could mean there's a new issue between the current and pre-release you're using.

**Comment by Christoph-AK** [comment] 2022-11-30 08:47
Hey, thanks for looking into this! I'm on Edge Version 107.0.1418.62 (Official Build) (64-Bit) on Win 11 22H2 (2261.819).
Im using a Laptop with a 2560x1600px screen with 150% scaling - maybe thats part of the problem?

**Comment by Christoph-AK** [comment] 2022-11-30 10:03
Disabling the `position: absolute` style entry on the containing div at least makes the whole selection visible: 
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/72923608/204766738-0cb8f9d6-4676-4c4c-8de5-704c47b88e7b.png">

Still not really the desire effect I suppose. How is this supposed to behave normally?

**Comment by mellieA** [comment] 2022-11-30 15:45
I can't reproduce this one, but I can see from your screenshots that something is causing an issue. I'll move this to the correct squad to see if they have other ideas.

**Comment by mellieA** [comment] 2022-11-30 15:46
For me it looks like this: 

<img width="812" alt="Screen Shot 2022-11-30 at 8 40 54 AM" src="https://user-images.githubusercontent.com/18175287/204843492-4dfe24a4-028e-4e6b-a75d-083d6f0dcf12.png">

**Comment by Christoph-AK** [comment] 2022-11-30 15:48
Thank you!

If you click on the 'now-10m to now'-drop down, how does that display for you?

**Comment by mellieA** [comment] 2022-11-30 15:49
<img width="967" alt="Screen Shot 2022-11-30 at 8 49 28 AM" src="https://user-images.githubusercontent.com/18175287/204844375-2ca9e2a3-9a0a-4ac9-85a2-89cffb3ec18a.png">

**Comment by gillesdemey** [comment] 2023-02-06 14:36
I've tried reproducing this but was unsuccessful; version numbers I've used:

`Microsoft Edge – Version 109.0.1518.78 (Official build) (arm64)` on MacOS
`Grafana v9.4.0` – This version will be released soon

My suggestion would be to upgrade the Edge browser to the latest version.

I'm going to go ahead and close this as it's either fixed in `main` or in the latest version of the Edge browser as we don't seem to be able to reproduce this one.

**Closed by gillesdemey** 2023-02-06 14:36 UTC
Labels: area/alerting, area/frontend, triage/needs-confirmation
