### ISSUE TITLE
Time Series Y-Axis auto-scaling breaks for small values

### ISSUE THREAD

**Issue by Patschke** [grafana/grafana#92719] opened 2024-08-30 07:16 UTC
### What happened?

The auto-scaling of Y-Axis range in a time series breaks for me, if the data is smaller than some threshold (about 3.1e-10). The max is set to 100 in that case. I could not figure out, why this happens. 

Manual min/max, showing that there is some data with all points about 2e-10. 
![Image](https://github.com/user-attachments/assets/9786b214-a4ca-4065-95d6-e6b226e11dfa)

With automatic min/max, the boundaries are wrongly set to 0...100:
![Image](https://github.com/user-attachments/assets/95d0db1d-cca9-44af-868e-3f467bbf4e49)
The only place I found that sets the scale to that range (0...100) is: https://github.com/grafana/grafana/blob/ce64d7902751c79eec6c8d3f10b0864511cef6bc/packages/grafana-ui/src/components/uPlot/config/UPlotScaleBuilder.ts#L238-L242 However, I don't see a reason, why `minMax[0]! >= minMax[1]!` would be the case here, so that shouldn't be the issue. I failed to track down the cause. 

When setting a manual min smaller than 3e-10, the max is also set to 100:
![Image](https://github.com/user-attachments/assets/e6e1b038-17c4-48cd-9954-ecd84520c16e)

When increasing that min above a certain threshold, the max is instead set to a more reasonable value (the next order of magnitude, e.g. 1e-9). That doesn't help here of course, as our data in that case is below that threshold...
![Image](https://github.com/user-attachments/assets/28307312-eb92-42da-8886-bd4bd0ac62f5)

Just for comparison: If we have data above that threshold of ~3.1e-10, like shown here, the auto-scaling does work. 
![Image](https://github.com/user-attachments/assets/b527b898-8b2b-4ca3-b5b8-6e50c93773d4)

### What did you expect to happen?

Auto-Scaling should work for all orders of magnitude. 

### Did this work before?

I'm not entirely sure. I think it did. 

### How do we reproduce it?

Create a time-series with data in the magnitude of 1e-10? I did not try to build a minimal-failing-example. 

### Is the bug inside a dashboard panel?

Note: I shrinked the time region compared to the screenshots above, as the data would otherwise extend the size limit for this input box. 

| Key | Value |
|--|--|
| Panel | timeseries @ 10.1.1 |
| Grafana | Grafana v11.1.4 (13173c9874) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 10,
            "gradientMode": "none",
            "spanNulls": false,
            "insertNulls": false,
            "showPoints": "never",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "axisBorderShow": false,
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          },
          "fieldMinMax": false,
          "unit": "pressurembar"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "pressure_2d_chamber_value{job=\"labsuv\", unit=\"mbar\"}"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "dark-red",
                  "mode": "fixed"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "pressure_2d_chamber_value{job=\"labsuv\", unit=\"mbar\"}"
            },
            "properties": [
              {
                "id": "custom.axisPlacement",
                "value": "right"
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "pressure_pumpstand_pfeiffer_gauge_value{job=\"labsuv\", unit=\"mbar\"}"
            },
            "properties": [
              {
                "id": "custom.axisPlacement",
                "value": "right"
              }
            ]
          },
          {
            "__systemRef": "hideSeriesFrom",
            "matcher": {
              "id": "byNames",
              "options": {
                "mode": "exclude",
                "names": [
                  "pressure_3d_chamber_value{job=\"labsuv\", unit=\"mbar\"}"
                ],
                "prefix": "All except:",
                "readOnly": true
              }
            },
            "properties": [
              {
                "id": "custom.hideFrom",
                "value": {
                  "viz": true,
                  "legend": false,
                  "tooltip": false
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "pluginVersion": "10.1.1",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "type": "timeseries-multi",
                  "typeVersion": [
                    0,
                    1
                  ],
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: pressure_3d_chamber_value\nStep: 5s",
                  "preferredVisualisationType": "graph"
                },
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 5000
                    }
                  },
                  {
                    "name": "pressure_3d_chamber_value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "__name__": "pressure_3d_chamber_value",
                      "job": "labsuv",
                      "unit": "mbar"
                    },
                    "config": {
                      "displayNameFromDS": "pressure_3d_chamber_value{job=\"labsuv\", unit=\"mbar\"}"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1724969040000,
                    1724969045000,
                    1724969050000,
                    1724969055000,
                    1724969060000,
                    1724969065000,
                    1724969070000,
                    1724969075000,
                    1724969080000,
                    1724969085000,
                    1724969090000,
                    1724969095000,
                    1724969100000,
                    1724969105000,
                    1724969110000,
                    1724969115000,
                    1724969120000,
                    1724969125000,
                    1724969130000,
                    1724969135000,
                    1724969140000,
                    1724969145000,
                    1724969150000,
                    1724969155000,
                    1724969160000,
                    1724969165000,
                    1724969170000,
                    1724969175000,
                    1724969180000,
                    1724969185000,
                    1724969190000,
                    1724969195000,
                    1724969200000,
                    1724969205000,
                    1724969210000,
                    1724969215000,
                    1724969220000,
                    1724969225000,
                    1724969230000,
                    1724969235000,
                    1724969240000,
                    1724969245000,
                    1724969250000,
                    1724969255000,
                    1724969260000,
                    1724969265000,
                    1724969270000,
                    1724969275000,
                    1724969280000,
                    1724969285000,
                    1724969290000,
                    1724969295000,
                    1724969300000,
                    1724969305000,
                    1724969310000,
                    1724969315000,
                    1724969320000,
                    1724969325000,
                    1724969330000,
                    1724969335000,
                    1724969340000,
                    1724969345000,
                    1724969350000,
                    1724969355000,
                    1724969360000,
                    1724969365000,
                    1724969370000,
                    1724969375000,
                    1724969380000,
                    1724969385000,
                    1724969390000,
                    1724969395000,
                    1724969400000,
                    1724969405000,
                    1724969410000,
                    1724969415000,
                    1724969420000,
                    1724969425000,
                    1724969430000,
                    1724969435000,
                    1724969440000,
                    1724969445000,
                    1724969450000,
                    1724969455000,
                    1724969460000,
                    1724969465000,
                    1724969470000,
                    1724969475000,
                    1724969480000,
                    1724969485000,
                    1724969490000,
                    1724969495000,
                    1724969500000,
                    1724969505000,
                    1724969510000
                  ],
                  [
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10,
                    1.62e-10,
                    1.62e-10,
                    1.68e-10,
                    1.68e-10,
                    1.71e-10,
                    1.71e-10,
                    1.73e-10,
                    1.73e-10,
                    1.74e-10,
                    1.74e-10,
                    1.75e-10,
                    1.75e-10,
                    1.75e-10,
                    1.75e-10,
                    1.74e-10,
                    1.74e-10,
                    1.72e-10,
                    1.72e-10,
                    1.71e-10,
                    1.71e-10,
                    1.69e-10,
                    1.69e-10,
                    1.68e-10,
                    1.68e-10,
                    1.66e-10,
                    1.66e-10,
                    1.65e-10,
                    1.65e-10,
                    1.64e-10,
                    1.64e-10,
                    1.63e-10,
                    1.63e-10,
                    1.62e-10,
                    1.62e-10,
                    1.61e-10,
                    1.61e-10,
                    1.61e-10,
                    1.61e-10,
                    1.6e-10,
                    1.6e-10,
                    1.6e-10,
                    1.6e-10,
                    1.6e-10,
                    1.6e-10,
                    1.59e-10,
                    1.59e-10,
                    1.59e-10,
                    1.59e-10,
                    1.59e-10,
                    1.59e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.58e-10,
                    1.57e-10,
                    1.57e-10,
                    1.57e-10
                  ]
                ]
              }
            },
            {
              "schema": {
                "refId": "B",
                "meta": {
                  "type": "timeseries-multi",
                  "typeVersion": [
                    0,
                    1
                  ],
                  "custom": {
                    "resultType": "matrix"
                  },
                  "executedQueryString": "Expr: pressure_2d_chamber_value\nStep: 5s",
                  "preferredVisualisationType": "graph"
                },
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "typeInfo": {
                      "frame": "time.Time"
                    },
                    "config": {
                      "interval": 5000
                    }
                  },
                  {
                    "name": "pressure_2d_chamber_value",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64"
                    },
                    "labels": {
                      "__name__": "pressure_2d_chamber_value",
                      "job": "labsuv",
                      "unit": "mbar"
                    },
                    "config": {
                      "displayNameFromDS": "pressure_2d_chamber_value{job=\"labsuv\", unit=\"mbar\"}"
                    }
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1724969040000,
                    1724969045000,
                    1724969050000,
                    1724969055000,
                    1724969060000,
                    1724969065000,
                    1724969070000,
                    1724969075000,
                    1724969080000,
                    1724969085000,
                    1724969090000,
                    1724969095000,
                    1724969100000,
                    1724969105000,
                    1724969110000,
                    1724969115000,
                    1724969120000,
                    1724969125000,
                    1724969130000,
                    1724969135000,
                    1724969140000,
                    1724969145000,
                    1724969150000,
                    1724969155000,
                    1724969160000,
                    1724969165000,
                    1724969170000,
                    1724969175000,
                    1724969180000,
                    1724969185000,
                    1724969190000,
                    1724969195000,
                    1724969200000,
                    1724969205000,
                    1724969210000,
                    1724969215000,
                    1724969220000,
                    1724969225000,
                    1724969230000,
                    1724969235000,
                    1724969240000,
                    1724969245000,
                    1724969250000,
                    1724969255000,
                    1724969260000,
                    1724969265000,
                    1724969270000,
                    1724969275000,
                    1724969280000,
                    1724969285000,
                    1724969290000,
                    1724969295000,
                    1724969300000,
                    1724969305000,
                    1724969310000,
                    1724969315000,
                    1724969320000,
                    1724969325000,
                    1724969330000,
                    1724969335000,
                    1724969340000,
                    1724969345000,
                    1724969350000,
                    1724969355000,
                    1724969360000,
                    1724969365000,
                    1724969370000,
                    1724969375000,
                    1724969380000,
                    1724969385000,
                    1724969390000,
                    1724969395000,
                    1724969400000,
                    1724969405000,
                    1724969410000,
                    1724969415000,
                    1724969420000,
                    1724969425000,
                    1724969430000,
                    1724969435000,
                    1724969440000,
                    1724969445000,
                    1724969450000,
                    1724969455000,
                    1724969460000,
                    1724969465000,
                    1724969470000,
                    1724969475000,
                    1724969480000,
                    1724969485000,
                    1724969490000,
                    1724969495000,
                    1724969500000,
                    1724969505000,
                    1724969510000
                  ],
                  [
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0077,
                    0.0077,
                    0.0078,
                    0.0078,
                    0.0077,
                    0.0077,
                    0.0077,
                    0.0077,
                    0.0076,
                    0.0076,
                    0.0077,
                    0.0077,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0077,
                    0.0077,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0078,
                    0.0077,
                    0.0077,
                    0.0079,
                    0.0079,
                    0.0075,
                    0.0075,
                    0.0075,
                    0.0075,
                    0.0076,
                    0.0076,
                    0.0077,
                    0.0077,
                    0.0078,
                    0.0078,
                    0.0079,
                    0.0079,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0078,
                    0.0078,
                    0.0077,
                    0.0077,
                    0.0075,
                    0.0075,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0076,
                    0.0077,
                    0.0077,
                    0.0075,
                    0.0075,
                    0.0076,
                    0.0076,
                    0.0075,
                    0.0075,
                    0.0078,
                    0.0078,
                    0.0076,
                    0.0076,
                    0.0078,
                    0.0078,
                    0.0077,
                    0.0077,
                    0.0078,
                    0.0078,
                    0.0077,
                    0.0077,
                    0.0079,
                    0.0079,
                    0.0077
                  ]
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "type": "timeseries"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 10.1.1</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[prometheus], B[prometheus]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 2 frames, 4 fields, 190 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>Grafana v11.1.4 (13173c9874) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"uid\": \"cVCNWhdMz\",\n    \"type\": \"prometheus\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 10,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"insertNulls\": false,\n        \"showPoints\": \"never\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"axisBorderShow\": false,\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"green\",\n            \"value\": null\n          }\n        ]\n      },\n      \"fieldMinMax\": false,\n      \"unit\": \"pressurembar\"\n    },\n    \"overrides\": [\n      {\n        \"matcher\": {\n          \"id\": \"byName\",\n          \"options\": \"pressure_2d_chamber_value{job=\\\"labsuv\\\", unit=\\\"mbar\\\"}\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"color\",\n            \"value\": {\n              \"fixedColor\": \"dark-red\",\n              \"mode\": \"fixed\"\n            }\n          }\n        ]\n      },\n      {\n        \"matcher\": {\n          \"id\": \"byName\",\n          \"options\": \"pressure_2d_chamber_value{job=\\\"labsuv\\\", unit=\\\"mbar\\\"}\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"custom.axisPlacement\",\n            \"value\": \"right\"\n          }\n        ]\n      },\n      {\n        \"matcher\": {\n          \"id\": \"byName\",\n          \"options\": \"pressure_pumpstand_pfeiffer_gauge_value{job=\\\"labsuv\\\", unit=\\\"mbar\\\"}\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"custom.axisPlacement\",\n            \"value\": \"right\"\n          }\n        ]\n      },\n      {\n        \"__systemRef\": \"hideSeriesFrom\",\n        \"matcher\": {\n          \"id\": \"byNames\",\n          \"options\": {\n            \"mode\": \"exclude\",\n            \"names\": [\n              \"pressure_3d_chamber_value{job=\\\"labsuv\\\", unit=\\\"mbar\\\"}\"\n            ],\n            \"prefix\": \"All except:\",\n            \"readOnly\": true\n          }\n        },\n        \"properties\": [\n          {\n            \"id\": \"custom.hideFrom\",\n            \"value\": {\n              \"viz\": true,\n              \"legend\": false,\n              \"tooltip\": false\n            }\n          }\n        ]\n      }\n    ]\n  },\n  \"gridPos\": {\n    \"h\": 8,\n    \"w\": 12,\n    \"x\": 0,\n    \"y\": 11\n  },\n  \"id\": 30,\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"multi\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"pluginVersion\": \"10.1.1\",\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"cVCNWhdMz\"\n      },\n      \"expr\": \"pressure_3d_chamber_value\",\n      \"interval\": \"\",\n      \"legendFormat\": \"\",\n      \"refId\": \"A\",\n      \"editorMode\": \"code\",\n      \"range\": true,\n      \"instant\": false,\n      \"exemplar\": false\n    },\n    {\n      \"datasource\": {\n        \"type\": \"prometheus\",\n        \"uid\": \"cVCNWhdMz\"\n      },\n      \"expr\": \"pressure_2d_chamber_value\",\n      \"hide\": false,\n      \"interval\": \"\",\n      \"legendFormat\": \"\",\n      \"refId\": \"B\"\n    }\n  ],\n  \"title\": \"Pressure Main Chamber\",\n  \"type\": \"timeseries\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Pressure Main Chamber // 2024-08-30 09:15:54",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2024-08-29T22:04:01.614Z",
    "to": "2024-08-29T22:11:53.249Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: v11.1.4 (13173c9874)
OS: Arch-Linux 6.10.6 (client), Docker grafana/grafana (Host)
Browser: Firefox

### Grafana platform?

Docker

**Comment by leeoniya** [comment] 2024-08-31 04:00
might be duplicate of https://github.com/grafana/grafana/issues/89570, which will be fixed by a uPlot update once a new release is out.

**Comment by leeoniya** [comment] 2024-08-31 05:04
ok, after some testing it's definitely related but not a duplicate, since that issue is for log axes and this one is for linear. i just pushed the changes needed to also fix linear axes: https://github.com/leeoniya/uPlot/commit/a4edb297a9b80baf781f4d05a40fb52fae737bff:

![Image](https://github.com/user-attachments/assets/efe027cd-faec-4fe2-961a-452aca7636a6)

it will probably take a couple months for the dependency update to trickle down into a Grafana release. if you want to build Grafana from source, you can always compile by changing the three `package.json` files:

```
    "uplot": "leeoniya/uPlot#a4edb297a9b80baf781f4d05a40fb52fae737bff",
```

![Image](https://github.com/user-attachments/assets/c0fd2f68-ee68-4760-826c-fdb2424c0299)

**Closed** 2024-09-28 04:11 UTC
Labels: type/bug, area/panel/timeseries

**Comment by Patschke** [comment] 2024-09-30 08:52
Seems like it is now shipped in grafana/grafana:main. Works fine for me, thanks a lot!
