### ISSUE TITLE
Viewer permission for all users by default/config

### ISSUE THREAD

**Issue by tonglil** [grafana/grafana#13385] opened 2018-09-21 19:32 UTC
### What Grafana version are you using?
5.2.0

### What was the expected result?
Configure for all users in the installation to have viewer/read-only permission for a set of orgs in Grafana.

This is similar to https://github.com/grafana/grafana/issues/2033, however not anonymous, but all registered users.

We use OAuth to automatically create users.

We want to have separate organizations in Grafana, each mapping to a team in the company. Within each team, they have dashboards and folders of dashboards. Each team manages their own datasources with their admins and editors. This allows delegation of responsibility to teams (instead of a "central" Grafana admin).

We want anyone in the company to view any other (or some) teams' dashboards.

We want to keep admin/editors separate at the org-level so they do not have cross-team admin/edit access to other team's datasources and dashboards.

### What did you do?
Currently this is very cumbersome in an install for ~800 people.

We have to enter in emails to add "viewer" users across multiple Grafana orgs. This process is slow (n^2) and prone to problems. Some users have uppercased emails while some have lowercased emails, so we run into this bug where Grafana treats usernames are case-sensitive (https://github.com/grafana/grafana/issues/12549) whereas people adding users to their org don't know the specific casing of another user's email (because that doesn't matter in real life).

Folder-level permissions (https://github.com/grafana/grafana/issues/1611#issuecomment-287742633) in one org is not enough for us because this folders do not apply to datasources, thus admins of team A and team B in the same org can edit each other's datasources.

API keys apply to the entire org, whereas we want to allow each team to issue their own API keys to edit their org.

We considered using Grafana "teams" to add users, and then add the "team" across orgs as viewers to dashboards, however "teams" are org-level separated.

### Conclusion

If there was a way folder-level permissions applied to datasources and API keys then I think that mechanism would allow us to scale quite nicely.

**Comment by marefr** [comment] 2018-09-24 07:41
Duplicate of #2132

**Comment by marefr** [comment] 2018-09-24 07:43
I see this as a request for datasource permissions even though I recon your other described problems. Please let me know if you're actually asking for other specific features than datasource permissions. Thanks

**Closed by marefr** 2018-09-24 07:43 UTC
