### ISSUE TITLE
[Feature request] Formatted metrics in alerts

### ISSUE THREAD

**Issue by bluefish6** [grafana/grafana#14592] opened 2018-12-19 12:40 UTC
### What Grafana version are you using?
Grafana v5.3.4 (69630b9)

### What datasource are you using?
influx

### What OS are you running grafana on?

Ubuntu 16.04 server on AWS

### Current state

For graphs that have metrics with user-selected units, alerts are sent with raw metrics value.

#### Examples:
1. webhook with percentage from 0.0-1.0
![image](https://user-images.githubusercontent.com/3324881/50219929-04f7ca00-0391-11e9-9526-faec58da9a10.png)

```
{"evalMatches":[{"value":0.44398584905660377,"metric":"Something","tags":null}],
"ruleId":65,"ruleName":"Something below min","ruleUrl":"http://...","state":"alerting","title":"[Alerting] Something below min"}
```

2. slack notifications with percentage 0.0-100.0 as in image in comment https://github.com/grafana/grafana/issues/7980#issuecomment-311875770

![image](https://user-images.githubusercontent.com/3324881/50220511-ca8f2c80-0392-11e9-856c-2f3ab6557765.png)

### Proposed state

Include the `formatted_value` for each metric in webhook notifications and use the formatted value in slack notifications.
I know that this probably contains in fact 3 features:
1) implement the `formatted_value` in core Grafana
2) implement usage of this new field in webhook plugin
3) implement usage of this new field in slack plugin.

#### Examples
1.  webhook with percentage

```
{"evalMatches":[{"formatted_value":"44%", "value":0.44398584905660377,"metric":"Something","tags":null}],
"ruleId":65,"ruleName":"Something below min","ruleUrl":"http://...","state":"alerting","title":"[Alerting] Something below min"}
```

2. slack notification with percentage
![image](https://user-images.githubusercontent.com/3324881/50220642-31ace100-0393-11e9-94ec-ddbddeb370c6.png)

It will be probably require checking if metric is using left or right axis, as they can have different units.

Note: it was also mentioned as a side-request by @ccoenen in https://github.com/grafana/grafana/issues/7980#issuecomment-311893462 - but I think it deserves a separate issue that people can upvote :)

**Comment by ccoenen** [comment] 2018-12-19 12:47
thanks for picking this up!

**Comment by marefr** [comment] 2018-12-19 13:14
I would say this is a duplicate of #6511 so I'm going to close this

**Closed by marefr** 2018-12-19 13:14 UTC

**Comment by bluefish6** [comment] 2018-12-19 13:20
Thanks, you're right - however I wouldn't have guessed that it's the same issue just by looking at the title of #6511 ;)
