### ISSUE TITLE
.gitignore file ( family.cue? ) prevents Grafana from building

### ISSUE THREAD

**Issue by N0mansky** [grafana/grafana#43532] opened 2021-12-27 02:52 UTC
**What happened**:
There's  a  .gitignore entry ignore /packages/**/dist that cause grafana-server compile error while I committed changes to my local git repo.
![image](https://user-images.githubusercontent.com/16576004/147429053-53666f37-49bf-4e25-8ab2-016c1f158fb8.png)

After I executed command: yarn build, packages/grafana-schema/src/scuemata/dist/family.cue still doesn't exist.So I need to download this file from https://github.com/grafana/grafana/blob/main/packages/grafana-schema/src/scuemata/dashboard/dist/family.cue 

**What you expected to happen**:
Remove this inappropriate .gitignore entry.

**How to reproduce it (as minimally and precisely as possible)**:
1. git clone main or download v8.3.3 released source code 
2. delete untracked git file or push to your local git repository and clone again.
3. Run compile command: yarn --immutable install && yarn build && make build-go

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3 or latest version
- Data source type & version: 8.3.3 or latest version
- OS Grafana is installed on: CentOS 7.9
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by zuchka** [comment] 2021-12-27 22:24
Thanks for creating this issue, @N0mansky 

> `yarn --immutable install && yarn build && make build-go`

I think [our docs specify](https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md#backend) `make run` have you tried that instead?

If still nothing:

> delete untracked git file or push to your local git repository and clone again

Can you please add more specific information about how to reproduce this? If I had a fresh Cent 7.9 box, and I reproduced this error from scratch, what would the bash history look like?

Also:

I found this related issue, which doesn't address your specific issue, but might be useful. I found it very educational, with some useful links:

https://github.com/grafana/grafana/issues/37859

**Comment by N0mansky** [comment] 2021-12-28 01:59
> 

Thanks for your reply.I think the cause of this  problem is because the family.cue file was removed and can't regenerate,but the family.cue file is depended by  compliling grafana-server binary.

Here is my bash history

 ```
422  git clone https://github.com/grafana/grafana.git
  423  ls
  424  cd grafana/
  425  git status
  426  git rm -rf --cached .          # remove the files from the tracking index 
  427  git status
  428  git add -A                            # add all files exclude .gitignore to tracking index 
  429  git status
  430  git commit -am "Reapply .gitignore"
  431  git clean -dfX                      # Remove .ignore files from the working tree
  432  yarn --immutable install && yarn build && make build-go
```
Here is the files were removed by git clean -dfX 
![image](https://user-images.githubusercontent.com/16576004/147519096-cf75cca3-09cc-4ed2-9c29-617ec0cb9fdb.png)

**Comment by sdboyer** [comment] 2022-01-05 11:55
Ahhh, yeah, and it's gitignored because i unwisely put the `family.cue` file into a directory called `dist`, which we have the general gitignore rules around.

This file layout will end up changing sooner rather than later for other reasons, at which point we can un-make the mistake. But changing it will break CUE import paths, which i want to keep to a minimum, so given that this is only a problem if you run `git clean -dfX` which AFAIK is not a part of our expected build process (i only ever `git clean -df`, FWIW), i'm going to close this and let the problem work itself out naturally.

**Closed by sdboyer** 2022-01-05 11:55 UTC
Labels: area/backend, needs investigation, area/scuemata
