### ISSUE TITLE
Grafana 10 no longer escapes data in dashboard variables with InfluxDB

### ISSUE THREAD

**Issue by sawo1337** [grafana/grafana#81995] opened 2024-02-06 17:37 UTC
### What happened?

Variables that contain special characters used in regex, for example URLs, no longer escape the data, resulting in broken queries with InfluxDB OSS (1.8.10)

### What did you expect to happen?

Any special characters to be escaped so queries aren't broken

### Did this work before?

This works fine with 9.5.7, but not on the latest 10.3.1, most likely hasn't worked on 10.x at all

### How do we reproduce it?

1. Create variable `URL` in the dashboard and assign value of `http://site.domain.co.uk/`
3. Assuming you have the default telegraf logging data to Influx, execute the below query against influxdb oss datasource:
`show tag values from cpu with key = "host" where "host" =~ /^$URL$/`
If you don't have the cpu measurement, you can execute this query against any measurement which has tag keys and just replace "host" with any other tag key.

Resulting query in 10.3.1:
`show tag values from iis with key = \"host\" where \"ReqURL\" =~ /^http://site.domain.co.uk/$/`

Resulting query in 9.5.7:
`show tag values from iis with key = \"host\" where \"ReqURL\" =~ /^(http:\\/\\/site\\.domain\\.co\\.uk\\/)$/`

### Environment (with versions)?

Grafana: 10.3.1
OS: Any
Browser: Any

### Grafana platform?

None

### Datasource(s)?

InfluxDB OSS 1.8

**Comment by ben5311** [comment] 2024-02-07 09:20
I can confirm the error; my InfluxQL Queries are not working in Grafana **10.3.1** because the variables are not being properly escaped. 
I believe that this is a bug. According to the latest Grafana documentation, the variables should be automatically escaped when multi-value is activated (which is definitely the case in my Dashboard): https://grafana.com/docs/grafana/latest/datasources/influxdb/template-variables/#choose_a_variable_syntax.

I can confirm that the error **did not** exist in Grafana **10.1.1**. 
I can confirm that the error **does** exist in Grafana **10.3.1**.

**Comment by sawo1337** [comment] 2024-02-07 21:37
I can confirm that with the first release of Grafana 10 this was working as expected. With the current, non-escaped variables, it pretty much renders the variables useless unless you store very simple data in there without any special characters.

**Comment by ben5311** [comment] 2024-02-08 08:02
This is going to be fixed in Grafana 10.4.0:
https://github.com/grafana/grafana/pull/80971

**Comment by tubemeister** [comment] 2024-02-14 15:03
Just ran into this bug.

Specifically the difference between:
- "foo" =~ /^(foo|bar|baz)$/
- "foo" =~ /^foo|bar|baz$/

The latter also selects "foobar" as a value, the former doesn't.

This changed between 10.2.2 and 10.2.3, will this get fixed in 10.4 too? (I'm a bit lost reading that code change.)

It's fairly easy to work around in a given query, but I'd rather not go fix hundreds of dashboards. :-)

**Comment by xtvdata** [comment] 2024-02-18 11:26
Hello I can confirm this issue.
Also for me happened somewhere around 10.x, can't pinpoint the exact release, but indeed after 10.0 and before or at 10.2.4.
I'm using the official package for Debian11-arm64 (but I don't think it's relevant).

As for the other cases it seems it's an escaping issue in dashboard variables, as when "exploring" data everything works as expected.

In my case, InfluxDB is fed from an MQTT broker (integrated with a custom adapter in Go); therefore, the original topic (including the special character "/") is one of the main tags in the data model.


P.S.: while a solution could be to configure a conversion rule in the custom adapter to substitute the "/" in tags, this would imply to rebuilding the whole data model, redesign all dashboard in Grafana, and convert the whole historical database in InfluxDB...
So for the moment I've installed Chronograph and rebuilt only a handful of essential dashboards, but I'd rather keep using Grafana for data visualization and InfluxDB as data storage.

**Comment by vincejv** [comment] 2024-02-26 17:47
@sawo1337 @xtvdata @ben5311 @tubemeister @usmangt 
This was supposed to be fixed: #80971 slated for 10.4.x, apparently this got broken on 10.2.3, 10.2.2 didn't have this issue, they will not backport this to future 10.2.x releases

**Comment by jkalnik** [comment] 2024-02-27 09:38
+1
I have same issue after I updated to 10.3.3 from 10.?.? . It deestroyed great part of my dashboards :) . Good to hear it will be fixed soon.

**Comment by sawo1337** [comment] 2024-02-27 10:19
> @sawo1337 @xtvdata @ben5311 @tubemeister @usmangt This was supposed to be fixed: #80971 slated for 10.4.x, apparently this got broken on 10.2.3, 10.2.2 didn't have this issue, they will not backport this to future 10.2.x and 10.3.x releases

great to hear that 10.4.x is getting the fix, waiting for that release then.

**Comment by itsmylife** [comment] 2024-02-27 16:21
Hi all. This was indeed a bug. Thanks a lot for your patience.

This issue that OP posted will be fixed with https://github.com/grafana/grafana/pull/80971 This will be available in `v10.4.x`
And the case that @tubemeister showed will be handled with https://github.com/grafana/grafana/pull/83400 I am going to ask around in which version this particular fix will be available.

I am closing this issue but feel free to open a new one if you find other problems.

**Closed by itsmylife** 2024-02-27 16:21 UTC
Labels: type/bug, datasource/InfluxDB, area/dashboard, triage/needs-confirmation

**Comment by itsmylife** [comment] 2024-02-27 16:49
@tubemeister I see your point. That is something else for sure. Do you mind creating an issue about this? I'd like to invest some time and investigate this.

**Comment by tubemeister** [comment] 2024-02-27 16:49
Sure, I'll type that up in a new one. Thanks for all the effort anyway :)

**Comment by itsmylife** [comment] 2024-02-27 16:50
@tubemeister Thanks a lot. Please do share it here by tagging me so I will assign that to myself and try to handle asap.
