### ISSUE TITLE
Grafana 8.0.4 ngalert conversion issue, cannot save any contact points after migration

### ISSUE THREAD

**Issue by tw-bert** [grafana/grafana#36525] opened 2021-07-07 15:42 UTC
**What happened**:
(on a testing host) Set ngalert to enabled, restarted grafana.
Conversions seems OK (some omissions, like e-mail addresses not populated)
But: We cannot correct anything that went wrong. On save of **any** contact point, we get:
> Error: failed to save and apply Alertmanager configuration: alert validation error: Could not find api key property in settings

**What you expected to happen**:
A successful conversion

**How to reproduce it (as minimally and precisely as possible)**:
We could give you our grafana.db file under NDA , should be easy to reproduce.
Sidenote: the revert-migration to old-style seems fine (but hey, no ngalert)

**Anything else we need to know?**:
If we start from scratch (fresh install), ngalert works fine.
But after we swap the db for our production grafana.db, the issue is there, and we can't create any contact point.
After swapping back to the vanilla db, all is fine again.
We also tested the multi-dimensional alerts, which make us very happy.

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: InfluxDB (InfluxQL)
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows,Chrome,Chredge
- Grafana plugins: bessler-pictureit-panel,briangann-gauge-panel,grafana-clock-panel,grafana-image-renderer,grafana-piechart-panel,jdbranham-diagram-panel,natel-discrete-panel,natel-influx-admin-panel,vonage-status-panel
- Others: sqlite persistence

**Comment by kylebrandt** [comment] 2021-07-07 17:09
It looks to be like this might be opsgenie notifications, as that is where I see `apiKey` and this error. With the code is comment to this documentation section: https://grafana.com/docs/grafana/latest/installation/upgrading/#ensure-encryption-of-existing-alert-notification-channel-secrets about secrets being updated to be encrypted in 7.2

```go
// Some settings were migrated from settings to secure settings in between.
// See https://grafana.com/docs/grafana/latest/installation/upgrading/#ensure-encryption-of-existing-alert-notification-channel-secrets.
// migrateSettingsToSecureSettings takes care of that.
func migrateSettingsToSecureSettings(chanType string, settings *simplejson.Json, secureSettings securejsondata.SecureJsonData) (*simplejson.Json, map[string]string) {
	keys := []string{}
	switch chanType {
	case "slack":
		keys = []string{"url", "token"}
	case "pagerduty":
		keys = []string{"integrationKey"}
	case "webhook":
		keys = []string{"password"}
	case "prometheus-alertmanager":
		keys = []string{"basicAuthPassword"}
	case "opsgenie":
		keys = []string{"apiKey"}
```

So it looks like there might be a manual step of updating the encryption settings. So I wonder if you edit and save your contact points before the migration (in particular, looks like opsgenie, but see list in documentation link), then run the migration, does this error persist?

**Comment by tw-bert** [comment] 2021-07-07 21:35
@kylebrandt Thank you, that pointed us in the right direction.

Deleting the OpsGenie channel (without deleting the alerts) beforehand resulted in a succesful migration of 'the rest'.
The issue apparently caused all other channel types (like e-mail) to err on save.

I'll leave this open (it's still a bug), but now we know where to look, it's no showstopper anymore.

On the live server, this might not arise at all (depends where and how the secrets are stored and if a machine fingerprint is used in the validation mechanism).
So we'll try a simple migration on the live server first.
If that fails, we can try other options (like your suggestion: saving first, or 'my' way: deleting the OpsGenie channel and repopulate them by hand after the migration).

The other issue, not all e-mail channels inside contact points are populated after migrate (an 'empty' contact point is all there is), seems unrelated.
But it's no showstopper, we'll fix that after migration by hand.
I don't feel it important enough to file an issue for.

Thanks again, TW

**Comment by LaxmiRajawat** [comment] 2021-07-07 21:53
Hi Grafana team,

We have recently migrated to Grafana 8.0.4 but I m not able to create any new contact point using any type like email, existing notification email also not working. getting 504 time out error while saving any new or existing contact point, please find attached error, I am selecting Grafana from alert manager drop down. Please let me know how to fix this error. Thanks for your help.
![contact point snap](https://user-images.githubusercontent.com/87098594/124833329-06d40980-df4c-11eb-9ffd-d53d434ed1aa.JPG)

**Comment by papagian** [comment] 2021-07-08 13:37
@LaxmiRajawat can you share the failing request/response from your browser's developer tools (network tab).
Do you use any proxy?

**Comment by papagian** [comment] 2021-07-08 16:09
@tw-bert 
Can you share the response of this:
curl http://<user>:<password>@<grafana host>:3000/api/alert-notifications
and:
http://<user>:<password>@<grafana host>:3000/api/alertmanager/grafana/config/api/v1/alerts

**Comment by tw-bert** [comment] 2021-07-08 16:13
@papagian I'm not sure what you are asking. Which situation? We already have a workaround, see https://github.com/grafana/grafana/issues/36525#issuecomment-875950762

**Comment by papagian** [comment] 2021-07-09 08:24
> @papagian I'm not sure what you are asking. Which situation? We already have a workaround, see [#36525 (comment)](https://github.com/grafana/grafana/issues/36525#issuecomment-875950762)

I was asking about not all e-mail channels inside contact points are populated after migrate.
It would be useful to compare the results of the above 2 calls (the first returns the notifiers registered in the legacy alerting and the other the latest Alertmanager configuration used in the Grafana 8 alerts). Does it happen for all the email addresses or just some of them? If the latter: do they have anything particular?
If you share the results, please make sure you redact any sensitive information first.

**Comment by tw-bert** [comment] 2021-07-09 09:23
Hi @papagian , clear. We haven't migrated yet, so it's probably expected that v1/alerts gives `{"message":"Not found"}` 

We aren't aware of doing anything special or complicated.
Maybe the info below is already enough for you, the compare will have to wait to after the migration.

The alert-notifications gives (anon):

```json
[
    {
        "id": 1,
        "uid": "000000001",
        "name": "email to johndoe",
        "type": "email",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2017-04-07T14:17:54+02:00",
        "updated": "2017-04-14T14:25:03+02:00",
        "settings": {
            "addresses": "johndoe@company.com",
            "autoResolve": true,
            "httpMethod": "POST"
        },
        "secureFields": {}
    },
    {
        "id": 2,
        "uid": "000000002",
        "name": "notifier-live",
        "type": "webhook",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2017-04-11T14:01:47+02:00",
        "updated": "2017-04-11T14:02:10+02:00",
        "settings": {
            "httpMethod": "PUT",
            "url": "http://srv-somethingplus/notifier/event/create/grafana/grafana_live/part01/error/live"
        },
        "secureFields": {}
    },
    {
        "id": 3,
        "uid": "000000003",
        "name": "email to johndoe and janedoe (hourly)",
        "type": "email",
        "isDefault": false,
        "sendReminder": true,
        "disableResolveMessage": false,
        "frequency": "1h",
        "created": "2017-04-14T14:22:28+02:00",
        "updated": "2021-04-12T13:41:27+02:00",
        "settings": {
            "addresses": "johndoe.doe@company.com;janedoe.doe@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "severity": "critical",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 4,
        "uid": "000000004",
        "name": "email to helpdesk \u0026 sysadmin (hourly)",
        "type": "email",
        "isDefault": false,
        "sendReminder": true,
        "disableResolveMessage": false,
        "frequency": "1h",
        "created": "2017-05-31T14:40:25+02:00",
        "updated": "2019-12-13T10:53:22+01:00",
        "settings": {
            "addresses": "helpdesk@company.com;sysadmin@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 5,
        "uid": "000000005",
        "name": "email to somebackend-support (hourly)",
        "type": "email",
        "isDefault": false,
        "sendReminder": true,
        "disableResolveMessage": false,
        "frequency": "1h",
        "created": "2017-07-04T09:10:01+02:00",
        "updated": "2019-12-13T10:53:30+01:00",
        "settings": {
            "addresses": "somebackend-support@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 6,
        "uid": "000000006",
        "name": "email to dist_sometech_developers",
        "type": "email",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2017-07-04T13:17:43+02:00",
        "updated": "2017-07-04T13:17:43+02:00",
        "settings": {
            "addresses": "webservices@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 7,
        "uid": "000000007",
        "name": "email to johndoe and dougdoe",
        "type": "email",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2017-11-15T11:54:27+01:00",
        "updated": "2017-11-15T11:54:52+01:00",
        "settings": {
            "addresses": "dougdoe.doe@company.com;johndoe.doe@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 8,
        "uid": "000000008",
        "name": "email to johndoe janedoe dougdoe",
        "type": "email",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2017-11-28T11:36:18+01:00",
        "updated": "2021-04-12T13:36:19+02:00",
        "settings": {
            "addresses": "dougdoe.doe@company.com;johndoe@company.com;janedoe.doe@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "severity": "critical",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 9,
        "uid": "000000009",
        "name": "email to jeffdoe",
        "type": "email",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2017-12-18T09:42:55+01:00",
        "updated": "2017-12-18T09:42:55+01:00",
        "settings": {
            "addresses": "jeffdoe.doe@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 10,
        "uid": "000000010",
        "name": "email to janedoe",
        "type": "email",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2018-09-28T17:17:51+02:00",
        "updated": "2021-04-12T13:36:37+02:00",
        "settings": {
            "addresses": "janedoe.doe@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "severity": "critical",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 11,
        "uid": "000000011",
        "name": "OpsGenie (sysadmins)",
        "type": "opsgenie",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2018-10-01T08:20:29+02:00",
        "updated": "2018-10-01T08:26:19+02:00",
        "settings": {
            "apiKey": "XXXXXX-1234-abcd-defg-POIPOIPOIPOI",
            "autoClose": true,
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 14,
        "uid": "8aB7WifZk",
        "name": "email to johndoe and janedoe (daily)",
        "type": "email",
        "isDefault": false,
        "sendReminder": true,
        "disableResolveMessage": false,
        "frequency": "24h",
        "created": "2019-12-13T10:54:51+01:00",
        "updated": "2021-04-12T13:36:57+02:00",
        "settings": {
            "addresses": "johndoe.doe@company.com;janedoe.doe@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "severity": "critical",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 15,
        "uid": "KBo4ZifWz",
        "name": "email to helpdesk \u0026 sysadmin (daily)",
        "type": "email",
        "isDefault": false,
        "sendReminder": true,
        "disableResolveMessage": false,
        "frequency": "24h",
        "created": "2019-12-13T10:55:18+01:00",
        "updated": "2019-12-13T10:55:18+01:00",
        "settings": {
            "addresses": "helpdesk@company.com;sysadmin@company.com",
            "autoResolve": true,
            "httpMethod": "POST",
            "uploadImage": true
        },
        "secureFields": {}
    },
    {
        "id": 12,
        "uid": "L5ZUeEmWz",
        "name": "MSTeams ict_flag/General",
        "type": "teams",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2019-05-11T21:56:32+02:00",
        "updated": "2019-05-11T22:09:44+02:00",
        "settings": {
            "autoResolve": true,
            "httpMethod": "POST",
            "uploadImage": true,
            "url": "https://outlook.office.com/webhook/POIUPOIUPOIUPOIU/IncomingWebhook/POIUPOIUPOIUPOIU/poipoi-0987-9898-9999-poiupoiupoiu"
        },
        "secureFields": {}
    }
]
```

**Comment by papagian** [comment] 2021-07-09 10:25
> We haven't migrated yet, so it's probably expected that v1/alerts gives {"message":"Not found"}

Yes
So you are not aware yet about any empty email notifiers after the migration?
Also, you may want to hide from the above response the addresses and any other sensitive information.

**Comment by tw-bert** [comment] 2021-07-09 10:29
Hi @papagian ,

> may want to hide

No worries, everything is already anonymized

> any empty email notifiers after the migration?

yes, quite a lot. One of them:

```
"name": "email to johndoe"
```
was an empty contact point after the migration

**Comment by papagian** [comment] 2021-07-09 11:05
I'm unable to reproduce it.
Please ping me if you notice any similar empty points after the migration.

**Comment by tw-bert** [comment] 2021-07-09 11:11
@papagian Thanks for the update and for looking into this.

My earlier comment:
> I don't feel it important enough to file an issue for.

So let's keep it at that for now. You might want to restore the anonymized curl response for future reference.

Cheers, TW

**Comment by gotjosh** [comment] 2021-07-12 12:38
Hi @LaxmiRajawat! That appears to be a different issue from the one originally reported. Can you please open a separate issue for it? We're closing this one for now given I don't see a course of action from our part on this anymore.

**Comment by tw-bert** [comment] 2021-07-12 14:19
@gotjosh I think even after the diversion in this thread, the actual original issue is quite clear. I don't think it should be closed. 

A reproduction of the issue should be simple to achieve:

1. Set up an OpsGenie and an e-mail alert on server A
2. Install Grafana on server B, grab a copy of grafana.db 
3. Enable ngalert on server B

This results in 'not even e-mail-only contact points can be saved'

Have you tested?

**Comment by papagian** [comment] 2021-07-13 09:02
@tw-bert 
I still cannot reproduce the `Could not find api key property in settings` error but I hadn't noticed that you try to apply the configuration to another server. Does server A and server B have the same [secret key](https://grafana.com/docs/grafana/latest/administration/configuration/#secret_key)?
If they don't then what happens is that the secure settings (in your configuration I think the only secure setting is the `apiKey` of the `opsgenie` notifier) are encrypted using the secret key of the server A but then the server B is unable to decrypt them using its secret key.

Some additional points:
- All the contact points are stored under the same Alertmanager configuration.
- The API endpoint for saving a new Alertmanager configuration tries to call the latest stored configuration for getting the stored secure settings and update them.
Therefore, [if the stored configuration is invalid then none contact point can be saved](https://github.com/grafana/grafana/blob/e06335ffe99cf64ee7ff13ff4d1e3bf9844404d4/pkg/services/ngalert/api/api_alertmanager.go#L207-L210). In order to handle better these situations we plan to allow users to delete such invalid configuration.

Another thing that I have I spotted is in the missing `apiUrl` property (required) from the following `opsgenie` notifier:
```
    {
        "id": 11,
        "uid": "000000011",
        "name": "OpsGenie (sysadmins)",
        "type": "opsgenie",
        "isDefault": false,
        "sendReminder": false,
        "disableResolveMessage": false,
        "frequency": "",
        "created": "2018-10-01T08:20:29+02:00",
        "updated": "2018-10-01T08:26:19+02:00",
        "settings": {
            "apiKey": "XXXXXX-1234-abcd-defg-POIPOIPOIPOI",
            "autoClose": true,
            "uploadImage": true
        },
        "secureFields": {}
    },
```
I believe that this is an old obsolete entry because the UI does not allow to save such a notifier:
![Screenshot 2021-07-13 at 10 54 50 AM](https://user-images.githubusercontent.com/1632407/125418759-4c1f7457-4e1f-4ead-9094-fd7fa4a53a60.png)
As a result the Alertmanager configuration created from the migration is invalid and the frontend prevents it from being saved (together with all the other endpoints).
![Screenshot 2021-07-13 at 11 37 45 AM](https://user-images.githubusercontent.com/1632407/125419919-3f9a4577-5c52-4b85-af78-ce1fccb1aaa2.png)

**Comment by tw-bert** [comment] 2021-07-13 09:15
Hi @papagian , 

- server A and server B do not have the same secret key. Not being able to decrypt: yes, that's clear (and fine).
- 'allow users to delete such invalid configuration' : lgtm!
- ' missing apiUrl property' -> yes, it seems to be missing. I can't track down what the plugin version was at creation time, so apperently this is something that can happen.

I think it's mainly about giving proper feedback to the enduser. We didn't have a clue that it was opsgenie related. After hinted by Kyle, the issue was relatively simple circumvented.

**Comment by papagian** [comment] 2021-07-13 09:33
> I think it's mainly about giving proper feedback to the enduser. We didn't have a clue that it was opsgenie related. After hinted by Kyle, the issue was relatively simple circumvented.

As a further improvement we will return a more meaningful error to indicate the source of the problem.

**Comment by gmariani** [comment] 2021-07-13 21:52
I"m having a similar issue where I can't add/save/delete any alert contacts or alert policies. All the migrated policies used Slack using a webhook. Now it requires a token. If i edit one, add the token it won't save (I'm assuming because others don't have a token). I can't even delete them to start over.

"Error: failed to save and apply Alertmanager configuration: alert validation error: token must be specified when using the Slack chat API"

**Comment by gmariani** [comment] 2021-07-14 15:55
Had to disable the nextgen alerts because i couldn't leave the alerts disabled for an extended period. But i would verify how it migrates slack alerts because it seems to break and not let you fix it.

**Comment by codesome** [comment] 2021-07-15 13:47
> All the migrated policies used Slack using a webhook. Now it requires a token.

If you have webhook URL, it should not require a token and should not error out. Can you check if you have any slack contact point which has no webhook URL mentioned with no token?

**Comment by gotjosh** [comment] 2021-08-03 12:48
Hi all, we've made some improvements around error messages, duplicated receivers and being able to edit your whole configuration in one go. You can reference:

- https://github.com/grafana/grafana/pull/36814
- https://github.com/grafana/grafana/pull/36951
- https://github.com/grafana/grafana/pull/36812

for more information. For now, we'll consider this issue closed but feel free to open a new one if something else pops up.

**Closed by gotjosh** 2021-08-03 12:48 UTC
Labels: area/unified-alerting
