### ISSUE TITLE
Requesting nested elements in elasticsearch

### ISSUE THREAD

**Issue by n3bojs4** [grafana/grafana#4618] opened 2016-04-08 14:50 UTC
Hi,

I am trying to request some nested fields in elasticsearch, but it seems to doesn't work.
I request my index manually and it works : 

GET /postfix*/_search

`{
   "query": {
       "nested": {
          "path": "recipients",
            "query": {
              "match": {
                   "recipients.rcptto": "misteraBcd@customer.fr"
               }
          }
      }
    }
}`

My recipients.rcptto looks like this :

              "recipients": [
                  {
                     "rcptto": "misterABCD@customer.fr"
                  },
                  {
                     "rcptto": "misterDEfG@test.com"
                  }
               ],

When i add a stat panel with metric count and group by term on recipients.rcptto it return nothing.

**Comment by torkelo** [comment] 2016-04-08 18:57
dupe of https://github.com/grafana/grafana/issues/3772

**Closed by torkelo** 2016-04-08 18:57 UTC
