### ISSUE TITLE
[BUG]user with folder admin permission cannot manage folder user&permission

### ISSUE THREAD

**Issue by ermazi** [grafana/grafana#11215] opened 2018-03-13 04:14 UTC
### What Grafana version are you using?
v5.0.0

### What datasource are you using?
None

### What OS are you running grafana on?
Ubuntu16.04

### What did you do?
assign user with folder admin permission, and then login with this user, cannot manage folder user and permission, even cannot fetch data about folder. error with no permission

### What was the expected result?
expected as description in docs

**Comment by kpocius** [comment] 2018-03-21 14:48
This is a duplicate of #11173 - let's keep the discussion in one place.

**Closed** 2018-03-27 10:15 UTC
