### ISSUE TITLE
Prometheus: Show results of instant queries as text, not in table

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#32475] opened 2021-03-30 09:17 UTC
**What would you like to be added**:
We are currently showing results of instant queries in the table. This way, we split labels into separate columns. Based on [feedback from community](https://twitter.com/pstbrn/status/1375023722516647937) and discussion with @gouthamve, this can is impractical. Reasons why it is impractical:
- If you have many labels on series, the table either gets super wide (because table rows can't wrap) or you have to hide some labels. It is hard to see everything.
- It is hard to copy-paste values and labels to use them in the your next query. You could use filter-for/filter-out functionality of table, but with that, you can do just 1 label at a time. If you know you want to filter for multiple labels, it would require you to use more resources to filter them one after the other (running multiple queries). Moreover, with having label in column, you are not even able to copy-paste label-value pair.
- We are using virtualized table which means that that if you have a lot of rows, you can't search for all labels. Searching for labels is very important and the fact that not all of them are searchable is big problem. 
- Users would prefer "less-magic" and "more-control"

**Why is this needed**:
Improve experience for Prometheus users.

**Comment by davkal** [comment] 2021-04-28 08:57
This keeps people using the vanilla UI for Prometheus.

**Comment by evandandrea** [comment] 2022-08-31 14:47
One idea raised by @itsmylife is that we could have a toggle to flip between table and text view.

@obetomuniz is going to dig into the current state of how these results are presented and follow up with @ivanahuckova for further clarity.

**Comment by obetomuniz** [comment] 2022-09-08 19:07
As for:

> - If you have many labels on series, the table either gets super wide (because table rows can't wrap) or you have to hide some labels. It is hard to see everything.
> - It is hard to copy-paste values and labels to use them in the your next query. You could use filter-for/filter-out functionality of table, but with that, you can do just 1 label at a time. If you know you want to filter for multiple labels, it would require you to use more resources to filter them one after the other (running multiple queries). Moreover, with having label in column, you are not even able to copy-paste label-value pair.

The current results should have a similar user experience as in the Prometheus Dashboard (screenshot). That experience allows users to select, copy and paste queries in a way they are already familiar with.

<img width="1715" alt="Screen Shot 2022-09-08 at 15 51 05" src="https://user-images.githubusercontent.com/1680157/189202593-5375667e-1705-4585-a71b-82b1ad496661.png">

As for:

> - We are using virtualized table which means that that if you have a lot of rows, you can't search for all labels. Searching for labels is very important and the fact that not all of them are searchable is big problem.

We should investigate this to understand how big the problem is to define a plan to solve it in a way that is simple for users without impacting their experience negatively.

@grafana/observability-metrics is working to create an initial proposal for this.

**Comment by gtk-grafana** [comment] 2022-09-26 20:02
I have created an initial implementation of the project that Beto outlined above:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/109082771/192366256-8004110d-322f-49dc-b01b-cfbc9f0f67d6.png">

Since this is a virtualized list component, we must hardcode the height, or calculate the height for each box on the fly (expensive), for this MVP I have opted to display a consistent height, but enable horizontal scroll so users with narrower screens can still interact with all of the content.
Scrolled content
<img width="462" alt="image" src="https://user-images.githubusercontent.com/109082771/192367142-6eb8ee1c-df7f-4c3b-9dc8-5fd0123a56a0.png">

I believe a better long term solution to the problem above is to let users tap on rows, which will open up vertically (accordion) and allow users to view the entire query, and filter by individual attributes.

Desktop view:
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/109082771/192368088-b0ef2e31-0aac-47d5-a5bd-ffd613185e59.png">

Misc observations so far:
The new view is much better at handling large amounts of data than the table view, even on a beefy PC the table view gets memory hungry and scrolling is jumpy and content takes a while to load.  

Other design stuff I want to review with UX/design:
* I'm currently using pure red and green for text markup, what text color should we be using for each theme?
* Discuss compromises for smaller screens
* I inserted a new element in this view borrowed from the prometheus UI, keep or delete?
<img width="196" alt="image" src="https://user-images.githubusercontent.com/109082771/192369078-22112fcf-e238-4c93-92c7-4902ac7bdc6c.png">


At this point I'm going to schedule another call with UX folks to get final direction on design and present the proposed MVP functionality, and then I'll work with logs team to figure out how to get this prometheus specific UI reviewed and merged.

**Comment by gtk-grafana** [comment] 2022-09-27 19:20
After chatting with UX folks we made some minor tweaks to the styles, here it is after the updates:
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/109082771/192616414-01a7e66e-53e1-404f-acb4-c77ac67a8367.png">
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/109082771/192616454-ba6df881-ddfd-48f9-9056-05e9aa36b4de.png">

UX was fine with the new UI element displaying the number of series returned by the query so I'll keep that in for now.

**Comment by gtk-grafana** [comment] 2022-10-12 18:28
So while I've got a solution for this that works with a single prometheus query, multiple queries are complicating things since Grafana seems to combine all results into a single results section, but the native prometheus UI has a results section for each query. I tried adding a toggle to allow users to toggle between values for the various queries, but the combined query returns different results then individual queries run separately.

I think we'll have to follow the native prometheus example and create a result section for each query, but I want to review this plan with UX before starting. 

Multiple queries native prometheus UI: 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/109082771/195418375-2b0530e6-d0b7-478f-b8a1-d25cad2a5c92.png">

Work in progress UI confronted with multiple queries:
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/109082771/195418483-5ab7e72a-08e6-464d-931d-782a680d9414.png">

Tried to clean up the above, but abandoned this idea because of how bad of a job it does displaying the values:  
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/109082771/195418581-9c52d678-874a-4e7e-9335-d66fd373e122.png">

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/109082771/195420053-efad7074-a97a-4adb-adac-4f0db50c31f5.png">

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/109082771/195420089-f7929e2a-e6c8-4ea6-804a-9eeccdfbc114.png">

**Comment by gtk-grafana** [comment] 2022-10-24 13:05
Waiting on UX

**Comment by gtk-grafana** [comment] 2022-12-21 22:09
So after much thought and discussion on this, we decided to move forward after providing an additional expanded view that will only show values that are not undefined for each series, and the ability to toggle between this new "expanded" and "collapsed" views depending on the users use case, while still highlighting the ability to copy series as PromQL query strings.

While there are still issues "seeing everything" in the collapsed view (especially with many/long label names/values), the new expanded view should be able to display all of the information returned for a single metric within the users viewport (i.e. without scrolling), and the collapsed view provides an easier way to compare metrics (and their values). I don't think we can choose which UI is correct (in regard to collapsed vs expanded) programmatically, as it depends on the user and their data, so I believe letting the user decide between these is the correct decision.

Although note that the collapsed view also doesn't reserve space for values that are not applicable to the current series, so there are two variables at play between the two views, rendering each label/value pair on its own line, and including the value names inside the list item, as opposed to placed above like a table header.

https://user-images.githubusercontent.com/109082771/208957906-5cdb5082-7bac-47ee-9c67-44a79ec92fc0.png
https://user-images.githubusercontent.com/109082771/208957958-4695d88e-53ce-461f-8443-85c92b16753a.png

^^ The Github WYSIWYG isn't letting me upload images, just going to link them for now and I'll try to update soon.

**Closed** 2023-01-04 16:46 UTC
Labels: type/feature-request, prio/high, datasource/Prometheus, area/ux

**Comment by gtk-grafana** [comment] 2023-01-04 16:58
Yahoo! We've merged in the MVP implementation to main, and these changes will be released in 9.4.0. This was a much bigger lift than anticipated, but I'm really proud of what we've accomplished so far. Thank you to everyone who helped on this @obetomuniz @ivanahuckova @diegoadams @davkal @Elfo404 @gelicia @bohandley @itsmylife @evandandrea and more.

We'll be adding some tracking events in https://github.com/grafana/grafana/pull/60990 (WIP) to help gather some base usage statistics.
