### ISSUE TITLE
Panel link target cannot be changed

### ISSUE THREAD

**Issue by barakakoun** [grafana/grafana#26365] opened 2020-07-16 08:22 UTC
**What happened**:
Can't save 'Open in new tab' toggle.
When trying to select the toggle and hit 'save', the 'Open in new tab' stays unselected when opening the edit modal again.

**What you expected to happen**:
We expect TargetBlank property to be saved, so if we switch 'Open in new tab' on it will be saved.

**How to reproduce it (as minimally and precisely as possible)**:
![Kapture 2020-07-16 at 11 18 19](https://user-images.githubusercontent.com/15690241/87645633-70b13d00-c756-11ea-87d1-60c967abc314.gif)

**Environment**:
- Grafana version: 7.0.6

**Comment by ivanahuckova** [comment] 2020-07-16 09:04
duplicate of #25445 fix incoming in 7.1

**Closed by ivanahuckova** 2020-07-16 09:04 UTC
