### ISSUE TITLE
[Feature Request] Link Y-Axis min/max across panels

### ISSUE THREAD

**Issue by m-o-e** [grafana/grafana#9338] opened 2017-09-23 13:36 UTC
![vft76o636j](https://user-images.githubusercontent.com/1622080/30773559-3fd6ff24-a073-11e7-9c06-1e4589373c85.png)

Currently the only way to force multiple panels to a common scale is
by hardcoding a fixed `y-min`/`y-max` on each, which is often not desirable.

As an improvement it would be great if the `y-min`/`y-max` of
multiple panels could be linked together, e.g. by assigning the
target panels to a common _panel group_.

The smallest `y-min` would then become the `y-min` for all panels in a common _panel group_.
And the biggest `y-max` would become the `y-max` for all panels in a common _panel group_.

**Comment by torkelo** [comment] 2017-09-26 09:28
duplicate of https://github.com/grafana/grafana/issues/4156

**Closed by torkelo** 2017-09-26 09:28 UTC
