### ISSUE TITLE
Editing pane disappeared while changing boom table

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#16427] opened 2019-04-07 03:15 UTC
**What happened**:
I was editing a boom table plugin visualisation and then the entire editing area went blank.

**What you expected to happen**:
for the graph editing to not disappear

**Environment**:
- Grafana version: 6.0.2
- Data source type & version: influxdb 1.7.4
- OS Grafana is installed on: CentOS 6.6
- User OS & Browser: firefox 60.0.6.1esr
<img width="1363" alt="Screen Shot 2019-04-07 at 1 10 02 pm" src="https://user-images.githubusercontent.com/24280758/55678063-144a5580-5937-11e9-8a65-d087a8891de9.png">
![Uploading Screen Shot 2019-04-07 at 1.09.50 pm.png…]

- Grafana plugins: Boom Table 1.0
- Others:

**Comment by yellowpattern** [comment] 2019-04-07 03:16
Restarting firefox did not held. Page reload did not held.

**Comment by yellowpattern** [comment] 2019-04-07 03:22
I have been able to repeat this. Created another dashboard and after doing to the "Vizualisation" section, everything has disappeared. Cannot even do "Add Query" to make a new query appear.

**Comment by yellowpattern** [comment] 2019-04-07 03:31
It happens while changing the "Format" of the data, i.e. changing it from "None" to "Data Rate", "Bytes Per Second." The dialog box appears and then vanishes, never to return.

**Comment by yellowpattern** [comment] 2019-04-07 03:33
Once this happens, I can no longer edit *ANY* dashboard.

**Comment by torkelo** [comment] 2019-04-07 16:42
duplicate of #15524 

A quick fix is to upgrade to latest firefox.

**Closed by torkelo** 2019-04-07 16:42 UTC
