### ISSUE TITLE
Issue with the barchart value

### ISSUE THREAD

**Issue by laurielounge** [grafana/grafana#39207] opened 2021-09-15 01:08 UTC
Bar chart value (displayed to the right of the bar in this case) did not refresh

I expected the value to refresh along with the rest of the chart

Create a bar chart and attach some (say) date sensitive data to it. Save and view the chart. Then change the date range. The chart will update, but the value will not.

Pressing F5 refreshes the value successfully

**Environment**:
- Grafana version: Community Version 8.1.3 (commit: a61f38238c, branch: HEAD)
- Data source type & version: MySQL Core
- OS Grafana is installed on: Rocky 8.4
- User OS & Browser:Firefox and Chrome, latest both, on Ubuntu and Windows 10
- Grafana plugins: Only
In the screen shot below, the mouse over value of 9.23M is correct, the value $18.7M is incorrect and will remain until the dashboard is refreshed via F5
![bar_chart](https://user-images.githubusercontent.com/32884649/133353888-f587ef78-8acf-41e8-bb54-87da3c9878d6.png)
 Core
- Others:

**Comment by leeoniya** [comment] 2021-09-15 01:12
Duplicate of #38410

fixed earlier today in https://github.com/grafana/grafana/pull/39188

**Closed by leeoniya** 2021-09-15 01:12 UTC

**Comment by laurielounge** [comment] 2021-09-15 01:32
Excellent. Thank you.
