### ISSUE TITLE
Add support for large BigInt numbers 

### ISSUE THREAD

**Issue by UniversalSuperBox** [grafana/grafana#13451] opened 2018-09-27 16:28 UTC
### What Grafana version are you using?
5.2.4 and 5.3.0
### What datasource are you using?
PostgreSQL 10.5
### What OS are you running grafana on?
Ubuntu 18.04
### What did you do?
SELECTed a BIGINT column from a Postgres database
### What was the expected result?
The BIGINT is displayed with full precision
### What happened instead?
The BIGINT is cut to a lower precision. For example, instead of "105990000000000009" through "105990000000000020" I'm just getting many rows of "105990000000000020". The query inspector shows this is exactly what's being returned into Grafana.

The following image shows the confusing data this outputs. Notice that the COUNT in both cases is the same row-by-row, but the ID is incorrect.

![](https://i.imgur.com/0Q5lX84.png)

Some extremely smart users on Slack found that integers that large don't exist with the JavaScript Number datatype. However, there is a BigInt available which would store the value correctly.

![screen shot 2018-09-27 at 10 52 15 am](https://user-images.githubusercontent.com/21966173/46160331-07420080-c248-11e8-9658-3a0cb2d3dc57.png)

### Workaround

In-query the BIGINT is still a BIGINT, so it's possible to aggregate or perform math as expected. When outputting the metric for display, use `CAST(column AS TEXT)` to display the full precision number. Note that you'd lose any formatting that Grafana provides when you do this.

**Comment by torkelo** [comment] 2018-09-28 08:46
This would likely be very hard to do, especially for the graph panel as the graphing libs don't support this.

**Comment by narc-Ontakac2** [comment] 2019-08-16 04:19
A hint in the documentation would be nice. BIGINTs are rarely used as numbers. In my case it was a query variable with BIGINT __ids. Also the cause was in plain sight in the generated sql it was quite hard to find.

Using ::TEXT conversion and a csv variable should be able to work around this.

**Comment by pkolyvas** [comment] 2021-07-26 16:46
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Closed by pkolyvas** 2021-07-26 16:46 UTC
Labels: type/feature-request

**Comment by pythonwood** [comment] 2022-12-26 09:12
![image](https://user-images.githubusercontent.com/5157880/209529396-8841b30d-7bf8-4f56-ac8e-b328bb215c3c.png)

@pkolyvas 

problem still in  Grafana v8.2.0-beta.1  9eed6c5 

battle_id is jsut a string, why it be int and not correct when in table ? (in javascrip)

**Comment by narc-Ontakac2** [comment] 2023-02-20 12:48
No idea about prometheus. Does it have data types? If it is of a string datatype in the database or returned as a string from the query it should stay a string when passing through JS unless you do any math on it.

**Comment by pythonwood** [comment] 2023-02-20 12:55
**not prom issue, but a grafana issue.**  battle_id is a string type tag in prom. prom deal it right and can filter it.
however, it just become an int in  grafana table panel, but all right as string in grafana time series.

**Comment by narc-Ontakac2** [comment] 2023-02-20 13:58
You could prepend a "id_" or something like that in the query. But I am not even sure what you want to achieve.

**Comment by pythonwood** [comment] 2023-02-21 02:26
> You could prepend a "id_" or something like that in the query. But I am not even sure what you want to achieve.
what I want:
let string show in grafana table in string type, no convert and no trim and no cut.

**Comment by pythonwood** [comment] 2023-02-21 05:34
ok, fix problem:  override battle_id unit as String  thanks zhoutao@office

![image](https://user-images.githubusercontent.com/5157880/220256257-efc36d84-c773-4e90-8ef9-d2dd79e2b137.png)
