### ISSUE TITLE
Grafana Alerts shows "no data" for Elasticsearch datasource

### ISSUE THREAD

**Issue by mmujat** [grafana/grafana#60614] opened 2022-12-21 06:36 UTC
**It was recently brought to our attention that alerts on Grafana 9.3.1 no longer work for Elasticsearch datasource**:

We have for example a dashboard with one panel which basically is a timeseries and we see data flowing in, so far so good
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/15548823/208837425-7bdd7c04-b237-4ac8-b5c7-eb11442da1c4.png">

We configured an alert for this panel which worked in the past, Grafana 9.2.0.
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/15548823/208837676-333506d3-5533-44cd-8c88-09484f5c0133.png">

Could you please assist with this request because we kind of need those alerts and we rely on Grafana to work properly

**Comment by usmangt** [comment] 2022-12-21 12:49
Hi @mmujat,

Thanks for opening this issue.

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by svennergr** [comment] 2022-12-21 16:32
Hi @mmujat,

I tried replicating the issue locally but did not succeed. I encountered a few different errors, which were resolved after clicking the `Preview` button though. 

Could you please check your browser console (F12) and/or the network tab for any errors? Also try if clicking the `Preview` button would eventually resolve your issue.

If possible, a HAR file (details how to generate one here https://toolbox.googleapps.com/apps/har_analyzer/) of the requests sent when clicking `Preview` would be great.

**Comment by CompuGlobalHyperMegaNet-VP** [comment] 2022-12-28 10:26
Hi, 

thank you for your quick responses.
Since my colleague is on vacation, I'll provide the HAR for him: 
[grafana_Archive [22-12-28 11-21-33].zip](https://github.com/grafana/grafana/files/10313620/grafana_Archive.22-12-28.11-21-33.zip)

Thanks in advance.

Best regards

**Comment by CompuGlobalHyperMegaNet-VP** [comment] 2022-12-28 11:59
Hi, 

i can add one observation. We use AWS Opensearch in Version 2.3 and use the Elasticsearch Datasource in Grafana. 
In the AWS Opensearch, the "compatibility mode", that reports the version as ES 7.10, is disabled, so it reports as Opensearch 2.3.

When configuring "ElasticSearch version" in the datasource config as 7.10+, the result is the one above described. Setting it to 8.0+ (yes, experimental, tested for debugging) results in a 
`Failed to evaluate queries and expressions: [plugin.downstreamError] failed to query data: elasticsearch version is required, err=elasticsearch version=8 is not supported` when previewing alerts. 

All queries for graphs work properly with both configured versions, as do the "tests" in the datasource config.

While analysing this, we also discovered the following, which seems to be related.

With "ElasticSearch version" in the datasource config as 7.10+, there are regular 4xx requests to the Opensearch instance:
`	403 | 403	2226	239	POST [https://<hostname>:443/_msearch ](https://<hostname>/_msearch) 	Grafana/9.3.1`
I can see their numbers rise when I hit the preview button for their alerts, although the browser network tool does not report a client side 403 request, the only request - eval post - gets a 200, as in the HAR attached in the previous post.

With "ElasticSearch version" in the datasource config as 8.0+, the 403 requests to the OpenSearch stopped.

Best regards

**Comment by lucdc** [comment] 2023-01-03 15:53
Same issue here. All my alerts to ES report 'No data' in v9.3.0. Alerts to other data source still work.

Perhaps interesting to note these alerts work if I revert back to v9.2.8.

**Comment by kwenzh** [comment] 2023-01-12 02:18
same issue , grafana version: v9.0.7
![image](https://user-images.githubusercontent.com/38367518/211960325-b4008b61-8c21-4601-926b-6fca8a8e812c.png)

**Comment by svennergr** [comment] 2023-01-12 06:35
@kwenzh @lucdc Could you share some information from your datasource settings please? Especially this part:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/8092184/211994944-ea8942f4-8304-4d07-9bc5-6c93a63d6323.png">

**Comment by kwenzh** [comment] 2023-01-12 06:37
> Same issue here. All my alerts to ES report 'No data' in v9.3.0. Alerts to other data source still work.
> 
> Perhaps interesting to note these alerts work if I revert back to v9.2.8.

in 9.2.8 , grafana alert from es can work 

> @kwenzh @lucdc Could you share some information from your datasource settings please? Especially this part: <img alt="image" width="461" src="https://user-images.githubusercontent.com/8092184/211994944-ea8942f4-8304-4d07-9bc5-6c93a63d6323.png">

![image](https://user-images.githubusercontent.com/38367518/211995322-e3d90ef7-c090-400c-85c1-b52f3fdcaa7b.png)

**Comment by kwenzh** [comment] 2023-01-12 06:38
> @kwenzh @lucdc Could you share some information from your datasource settings please? Especially this part: <img alt="image" width="461" src="https://user-images.githubusercontent.com/8092184/211994944-ea8942f4-8304-4d07-9bc5-6c93a63d6323.png">

![image](https://user-images.githubusercontent.com/38367518/211995417-e0c28d0a-a209-4a0a-9bc0-21e49d7c0246.png)

**Comment by gabor** [comment] 2023-01-18 16:03
hi @mmujat , @CompuGlobalHyperMegaNet-VP , @lucdc , @kwenzh ,
we cannot reproduce it yet, so i have some more questions/ideas that might help us find the root cause:
1. are you using any authentication-settings on the datasource-configuration-page? i mean things like "custom http header", anything in the "auth" section, perhaps "allowed cookies'?
2. we found some consistency issues in the alerting-editor... if you just click on the [preview] button multiple times, does it fix the problem by any chance?
3. if you use `date_histogram` aggregation, could you try setting a fixed `interval` value? (meaning, not `auto`). does that help?
4. could you try an experiment in a dashboard?:
   - create a dashboard-panel, and add the query that is producing the `no data` error in alerting. let's say the query is named `A`. (that's the default)
   - run the query (refresh dashboard). at this point it should work fine.
   - now add an Expression using the [+Expression] button in the lower-left corner
   - set the value of the expression to `$A` (meaning, just use the value from the query named `A`) (see screenshot below)
   - run the queries (refresh dashboard). 
   - did it work correctly, or did you get the "no data" message?

thanks!
<img width="766" alt="expr" src="https://user-images.githubusercontent.com/51989/213226187-1fda0769-d1a7-45e8-965e-30f0c6bec9af.png">

**Comment by gabor** [comment] 2023-01-20 15:47
hi @CompuGlobalHyperMegaNet-VP , thanks for the info, we are looking into it..
but i'd like to discuss shortly the error you are getting for elastic8.

it should work in grafana9.3.1
could you try this please?
1. set the version to the `7.10` option, save
2. set the version to the `8.0` option, save
does it get fixed by this perhaps?

**Comment by CompuGlobalHyperMegaNet-VP** [comment] 2023-01-23 08:16
Hi @gabor ,
>does it get fixed by this perhaps?
we use this as a provisioned datasource and thus can't edit them during the lifetime of the grafana pod
`  datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        ...
        - name: ElasticSearch
          type: elasticsearch
          url: $ES_CUSTOM_DOMAIN_URL
          isDefault: false
          database: "*"
          jsonData:
            timeField: "@timestamp"
            esVersion: 7.10.0
            logMessageField: ""
            logLevelField: ""
            sigV4Auth: true
            sigV4AuthType: "default"
            sigV4Region: "$AWS_REGION"
        ...`
Setting the esVersion in the provisioning script from "7.10.0" to "8.0" results in the given error messages. However, as mentioned, testing the 8.0 datasource and normal queries work fine.

**Comment by gabor** [comment] 2023-01-23 08:35
@CompuGlobalHyperMegaNet-VP sorry, could you try to set the version to `"8.0.0"` ?
like this:
```yaml
.
.
.
jsonData:
    esVersion: "8.0.0"
```
    
```

**Comment by CompuGlobalHyperMegaNet-VP** [comment] 2023-01-23 11:24
Hi @gabor,

sorry, I should have checked the [source](https://github.com/grafana/grafana/blob/3a7623753b76cc9f3963ab81d788c6bdef3f5198/public/app/plugins/datasource/elasticsearch/configuration/ElasticDetails.tsx#L20) first. (It is, however, slightly inconvenient that using "8.0" seems to work for everything else but alarms.) 

Using "8.0.0" removed the "elasticsearch version=8 is not supported" error message. 
I repeated the tests steps 2-4 with 8.0, i now have the same results there as with version 7.10.

**Comment by gabor** [comment] 2023-01-23 11:35
@CompuGlobalHyperMegaNet-VP thanks for testing this, i'm glad at least a part of the situation is clarfied now.

i agree that it is inconvenient that the behavior is different between alarms and dashboards/explore. there's ongoing work to unify this behavior at https://github.com/grafana/grafana/issues/54011

**Comment by gabor** [comment] 2023-01-23 15:59
hi all, we found the bug, elastic-alerts with sigv4 are broken in 9.3.0 and 9.3.1.
the bugfix ( https://github.com/grafana/grafana/pull/61923 ) was merged, and will be available in the next release.

there were many comments on this issue, and while i'm quite certain we found the problem the issue-creator had, maybe this does not cover everyone's problem.

so, if your problem is not grafana9.3.x + sigv4, please:
1. try to click [run queries] multiple times, there is an inconsistency issue in the alert-mode query-editor (that inconsistency also got fixed)
2. if that does not help, please create a new github issue with:
    - description of the problem
    - which grafana-version are you using
    - which "authorization" options do you use?

thanks!

**Closed by gabor** 2023-01-23 15:59 UTC
Labels: needs more info, datasource/Elasticsearch
