### ISSUE TITLE
CloudWatch Logs - No results displayed if the last field queried is not a String

### ISSUE THREAD

**Issue by sahnib** [grafana/grafana#54725] opened 2022-09-05 16:48 UTC
**What happened**: Ran a CW logs query using Grafana. If the Logs query returns fields of type integer, Grafana does not display log results and just prints - `No Logs Found`. In the Network tab, I can see that the response for `api/ds/query` contains the log data - The front end just does not display it at all. 

**What you expected to happen**: Expected to see the logs from the query. 

**How to reproduce it (as minimally and precisely as possible)**: 

1. Configure Grafana with a CW Logs data source. 
2. Run a CW Logs query to print values of a field in JSON log which is not a String. Examples are ResponseCode, latency value etc. 

```

fields @timestamp, FieldWithIntValue
| sort @timestamp desc

```
3. No Logs would be displayed in Grafana UI. 
4. Run the same query in CW Logs Console. Displays the correct log events matching the query. 

**Anything else we need to know?**: This is quite misleading as the user might think there are no errors, whereas the log query explicitly matches log events - they are not displayed and there is no error/warning that Grafana skipped printing log events. 

**Environment**: OS Linux/Firefox 
- Grafana version: 8.4.7
- Data source type & version: CW Logs (Core plugin)
- OS Grafana is installed on: Linux
- User OS & Browser: Linux Ubuntu/Firefox
- Grafana plugins: None
- Others: None

**Comment by taleena** [comment] 2022-09-06 15:02
Affects Amazon Managed Grafana, which is on 8.4.7

**Comment by sunker** [comment] 2022-09-07 09:43
The Logs panel in Grafana requires that the returned data contains at least one timestamp field and at least one string field. If that's not the case, the panel will display an error saying "Cannot visualize data". 

I'm not able to reproduce the _No logs found_ issue when I run the query you've provided in 8.4.7, but I am seeing the _Cannot visualize data_ error which is expected. 
```
fields @timestamp, FieldWithIntValue
| sort @timestamp desc
``` 

If I'm adding a string field to the query, everything is working as expected - I can see the log results being shown in the Logs panel. 
```
fields @timestamp, @message, FieldWithIntValue
| sort @timestamp desc
``` 

Can you please add string field to your query and let me know if it works or not?

**Comment by sarahzinger** [comment] 2022-10-18 14:43
Going to close this issue since it doesn't seem like there's been much activity here over the past month but let us know if you're still experiencing the issue and we can reopen

**Closed by sarahzinger** 2022-10-18 14:43 UTC
Labels: needs investigation, datasource/CloudWatch Logs
