### ISSUE TITLE
Pick colour before sorting

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#33067] opened 2021-04-16 10:32 UTC
**What would you like to be added**:
Colours assigned to series shall be done in a deterministic fashion, before panel-specific ordering is done.

**Why is this needed**:
This would ensure that for several panels using the same series, defined in the same order, picked colour will be the same for each.

Here is a use case where one is monitoring CPU use as a share of global time, while also tracking time-based evolution:
![Grafana_colours](https://user-images.githubusercontent.com/4251220/115011658-2f011e80-9eaf-11eb-81d2-9856713c04ac.png)
Colours are misleading, making correlation difficult, while the user has no control over colour selection (other than manually overriding each series of each panel).

You can immediately see colours are picked in the same order in each panel, except that for the pie chart one, they are picked _after_ sorting is done, while this proposal suggests to do it _beforehand_.

**Comment by morsik** [comment] 2021-04-17 23:32
That would be pretty useful feature. Like "Dashboard global colors". Always what I do is I pick colors manually as you did.
We should be able at least pick colors manually but globally for whole dashboard based on names/patterns instead of single panels. That may help, a lot.

**Comment by torkelo** [comment] 2021-06-19 05:50
duplicate of https://github.com/grafana/grafana/issues/221

**Closed by torkelo** 2021-06-19 05:50 UTC
Labels: area/frontend, area/panel/piechart, type/bug
