### ISSUE TITLE
Misalignment in bar chart

### ISSUE THREAD

**Issue by pacive** [grafana/grafana#21967] opened 2020-02-06 12:04 UTC
After upgrade to 6.6.0 the alignment of the bars in the bar chart has been shifted to the left, so they are centered with regart to the time. However, the hover "tool-tip" that displays the value isn't in sync and may show different values depending on where on the bar the mouse pointer is located.

![screenshot_1](https://user-images.githubusercontent.com/30875102/73935473-e3350b80-48e0-11ea-900c-9e73fe1bbcfe.png)
Shows correct value

![screenshot_2](https://user-images.githubusercontent.com/30875102/73935549-0e1f5f80-48e1-11ea-8769-7691fbb40a40.png)
Shows value for the previous bar.

**Comment by Liczi** [comment] 2020-02-19 08:39
+1

**Comment by dprokop** [comment] 2020-04-07 20:01
Duplicate of #22611

**Closed by dprokop** 2020-04-07 20:01 UTC
Labels: area/panel/graph, type/bug
