### ISSUE TITLE
Feature Request: Ability to pin the dashboard variables bar 

### ISSUE THREAD

**Issue by JonasDeGendt** [grafana/grafana#16592] opened 2019-04-15 09:06 UTC
**What would you like to be added**:
The ability to pin the dashboard variables bar so it is always showing.

**Why is this needed**:
We have some dashboard pages that are relatively long. When changing variables we need to scroll all the way up, it'd be nice to be able to change variables regardless of where you are on the page.

A quick Gimp edit to better illustrate:
![Screenshot from 2019-04-15 10-54-58](https://user-images.githubusercontent.com/37802535/56120270-167f6600-5f6e-11e9-90fe-fdbf054ba5ca.png)

**Comment by torkelo** [comment] 2019-04-15 15:01
dupe of https://github.com/grafana/grafana/issues/11166

**Closed by torkelo** 2019-04-15 15:01 UTC
