### ISSUE TITLE
LDAP auth/z depends on MemberOf attribute being present

### ISSUE THREAD

**Issue by zeridon** [grafana/grafana#2601] opened 2015-08-26 13:08 UTC
Hello,

While playing with ldap auth in 2.1.3 we've stumbled on the situation where grafana is not able to login a ldap user if the user does not have MemberOf attribute defined.

In OpenLDAP (slapd) the memberof overlay which provides the attribute is not enabled by default.

This results basically in the user successfully authenticating but then not being able to be assigned a role due to no groups being listed. No groups being listed is due to missing attribute.

Fix is to enable checking for the mappings with direct ldap queries (but only if no MemberOf attribute is available for performance reasons).

**Comment by torkelo** [comment] 2015-08-26 13:17
OpenLDAP supports memberOf, but you are right it is not enabled by default. 
You should be able to login with this config: 

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"

**Comment by torkelo** [comment] 2015-08-26 13:19
dupe of https://github.com/grafana/grafana/issues/2538

**Closed by torkelo** 2015-08-26 13:19 UTC

**Comment by zeridon** [comment] 2015-08-26 13:52
More cleaner (at least for us) way is to omit any mappings and depend on Grafana DB for roles/orgs assignment.

**Comment by abligh** [comment] 2015-10-15 09:10
Fixed in https://github.com/grafana/grafana/pull/2928
