### ISSUE TITLE
Tighter integration of the "Boom Theme" panel plugin into Grafana

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#21286] opened 2019-12-30 10:32 UTC
**What would you like to be added**:

For the purpose of customizing the theme of Grafana beyond the standard dark and light, there is a [recently developed panel plugin](https://github.com/yesoreyeram/yesoreyeram-boomtheme-panel) that allows for custom CSS and background images.

However, the way it works is by creating a panel allowing the user to edit the theme of each dashboard at any time and that panel may be hidden, but not completely removed.

This process could be improved if the plugin is more tightly coupled either with the theme selection preferences or with the settings of the dashboard, rather than obstructing the design of the dashboard by adding a panel that needs to be concealed.

**Why is this needed**:

While Grafana provides a means to control the theme by providing a basic dark/white background and contrasting foreground combination, there is much more to beautiful metrics visualization that could be realized by integrating an already available plugin in order to expand the suite of themes.

**Comment by hugohaggmark** [comment] 2019-12-30 11:50
Duplicate of #4909

**Closed by hugohaggmark** 2019-12-30 11:50 UTC

**Comment by anirudh-ramesh** [comment] 2020-01-14 08:31
Hi, @hugohaggmark, would this or #4909 be a good fit for Grafana v6.7? I see that both issues are closed, and hence worth asking a question.

**Comment by hugohaggmark** [comment] 2020-01-14 09:12
@anirudh-ramesh I'm guessing that they are not fit for Grafana v.6.7.
