### ISSUE TITLE
5.3.0 Alerting - Email graph legend aligned left

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#13701] opened 2018-10-17 08:35 UTC
datasource influxdb
centos 7

cant see the graph on email alerts - legend is aligned left

![image](https://user-images.githubusercontent.com/12600004/47073329-4be20b80-d1f8-11e8-8fba-6a7c19f98ccf.png)

**Comment by torkelo** [comment] 2018-10-17 09:45
fixed in v5.3.1 :)

**Closed by torkelo** 2018-10-17 09:45 UTC

**Comment by marefr** [comment] 2018-10-17 10:03
Duplicate of #13616

**Comment by discoduck2x** [comment] 2018-10-17 11:09
> Duplicate of #13616

sorry i should have looked harder - thanks for ur awesome attention!
