### ISSUE TITLE
Search: Keypresses lost when typing quickly in slow browser

### ISSUE THREAD

**Issue by alshain** [grafana/grafana#75763] opened 2023-09-29 17:59 UTC
### What happened?

When using the search bar up top on a slow computer, keypresses are often lost when searching. I've not encountered this anywhere else in the Grafana UI. So I might type `dashboard`, but the search input will receive `dabrd` in extreme cases. This is extremely annoying because there's no fuzzy search.

### What did you expect to happen?

I expect no characters to be lost.

### Did this work before?

It worked without issues when we were on Grafana 8.4, but after upgrading to 10+ with the new search, the issue appeared.

### How do we reproduce it?

1. Have low powered machine
2. Type quickly into search
3. See characters being lost

### Environment (with versions)?

Grafana: 10.x (seen on 10.0 as well as two other 10.x releases)
OS: Windows 10
Browser: Chrome

### Grafana platform?

Kubernetes

**Comment by usmangt** [comment] 2023-10-12 12:23
Hi @alshain,

Thanks for opening this issue.

What exactly do you mean by a low-power machine? (are you using Grafana in a Virtual machine and how much RAM and Disk space do you have)?

Please provide the above details so that it help us to understand the problem better.

**Comment by alshain** [comment] 2023-10-19 07:26
@usmangt It's a regular business notebook with 16 gigs of RAM, 500 gigs SSD storage. But it's bogged down a little by anti virus software.

However, this is the *only* location where I notice issues with Grafana. Viewing complicated graphs works fine. A bit more laggy than on a regular machine, but no issues, not when writing queries either. It's *only* that search field where I experience lost keypresses.

**Comment by usmangt** [comment] 2023-10-19 08:24
Can you please try to reproduce this while using https://play.grafana.org/dashboards/f/e04a2013-1aef-4c39-87e4-4d6c1698820a/sandbox

Also if possible, record your session with a screencast software and send it to us.

**Comment by alshain** [comment] 2023-10-30 09:28
@usmangt Unfortunately, external URLs are opened with a different browser that goes through some security sandboxing, and lots of dynamic pages don't work at all, so that won't be representative I'm afraid.

**Comment by usmangt** [comment] 2023-10-30 09:50
Without any data it will be v.har to debug this.

Can you at least provide the Browser Developer data using exporting it into the HAR file by capturing the web session traffic?

Here, is a reference [link](https://support.google.com/admanager/answer/10358597?hl=en) as how to capture it using Chrome DevTools.

**Comment by alshain** [comment] 2023-10-30 12:15
@usmangt Of course. I managed to reproduce it using another machine on your public playground:

![Animation](https://github.com/grafana/grafana/assets/349397/1fcf3e36-d4f7-4478-948b-aebc14a6c05d)

Note how the screen recording software sees additional keypresses (jk) that the Grafana search bar does not show.

**Comment by JoaoSilvaGrafana** [comment] 2023-11-01 16:50
Hey! Thanks for raising this. I have managed to reproduce this locally by setting CPU: 6x slowdown in the "Performance" tab of chrome dev tools. Had a quick look to see if there was any quick fix to it, but couldn't find one, so moving this to our backlog so someone can have a deeper look.

**Comment by xkilian** [comment] 2023-11-01 20:22
This problem is present on all our common laptops accessing Grafana 10.2.0. There has to be a regression somewhere, as this was not present on previous version 9.x.

**Comment by ashharrison90** [comment] 2023-11-14 13:22
we _think_ this is due to a bug in `kbar`, have raised https://github.com/timc1/kbar/issues/341 to discuss next steps 👍

**Closed** 2023-11-20 11:36 UTC
Labels: type/bug, area/search
