### ISSUE TITLE
valueString webhook body is empty

### ISSUE THREAD

**Issue by aft2d** [grafana/grafana#45459] opened 2022-02-16 11:33 UTC
**What happened**:
We set up an ngalert webhook and processing the webhook calls.
`fired` event: `valueString` is always empty
`resolved` event: `valueString` is sometimes empty, sometimes filled. Circumstances unclear.

**What you expected to happen**:
valueString should not be empty in `firing` event

**How to reproduce it (as minimally and precisely as possible)**:

![screencapture](https://user-images.githubusercontent.com/6129115/154251758-c76aa288-89e6-4351-8734-901a9b235b0f.png)

```js
{
  receiver: 'Telegram default',
  status: 'firing',
  alerts: [
    {
      status: 'firing',
      labels: {
        alertname: '************** fails alert',
        rule_uid: 'YTSsr3-7k'
      },
      annotations: {},
      startsAt: '2022-02-16T10:45:32.088827563Z',
      endsAt: '0001-01-01T00:00:00Z',
      generatorURL: 'https://grafana.local/alerting/YTSsr3-7k/edit',
      fingerprint: 'b566c0d7267af169',
      silenceURL: 'https://grafana.local/alerting/silence/new?alertmanager=grafana&matchers=alertname%3DUnblocked+minion+fails+alert%2Crule_uid%3DYTSsr3-7k',
      dashboardURL: 'https://grafana.local/d/SoBr6vTmk',
      panelURL: 'https://grafana.local/d/SoBr6vTmk?viewPanel=7',
      valueString: ''
    }
  ],
  groupLabels: {
    __alert_rule_uid__: 'YTSsr3-7k',
    alertname: '************** fails alert',
    rule_uid: 'YTSsr3-7k'
  },
  commonLabels: { alertname: '************** fails alert', rule_uid: 'YTSsr3-7k' },
  commonAnnotations: {},
  externalURL: 'https://grafana.local/',
  version: '1',
  groupKey: '{}:{__alert_rule_uid__="YTSsr3-7k", alertname="************** fails alert", rule_uid="YTSsr3-7k"}',
  truncatedAlerts: 0,
  orgId: 1,
  title: '[FIRING:1] ************** fails alert YTSsr3-7k YTSsr3-7k ',
  state: 'alerting',
  message: '**Firing**\n' +
    '\n' +
    'Value: [no value]\n' +
    'Labels:\n' +
    ' - alertname = ************** fails alert\n' +
    ' - rule_uid = YTSsr3-7k\n' +
    'Annotations:\n' +
    'Source: https://grafana.local/alerting/YTSsr3-7k/edit\n' +
    'Silence: https://grafana.local/alerting/silence/new?alertmanager=grafana&matchers=alertname%3DUnblocked+minion+fails+alert%2Crule_uid%3DYTSsr3-7k\n' +
    'Dashboard: https://grafana.local/d/SoBr6vTmk\n' +
    'Panel: https://grafana.local/d/SoBr6vTmk?viewPanel=7\n'
}
```
```js
{
  receiver: 'Telegram default',
  status: 'resolved',
  alerts: [
    {
      status: 'resolved',
      labels: {
        alertname: '************** fails alert',
        rule_uid: 'YTSsr3-7k'
      },
      annotations: {},
      startsAt: '2022-02-16T10:45:32.088827563Z',
      endsAt: '2022-02-16T10:48:02.088827563Z',
      generatorURL: 'https://grafana.local/alerting/YTSsr3-7k/edit',
      fingerprint: 'b566c0d7267af169',
      silenceURL: 'https://grafana.local/alerting/silence/new?alertmanager=grafana&matchers=alertname%3DUnblocked+minion+fails+alert%2Crule_uid%3DYTSsr3-7k',
      dashboardURL: 'https://grafana.local/d/SoBr6vTmk',
      panelURL: 'https://grafana.local/d/SoBr6vTmk?viewPanel=7',
      valueString: ''
    }
  ],
  groupLabels: {
    __alert_rule_uid__: 'YTSsr3-7k',
    alertname: '************** fails alert',
    rule_uid: 'YTSsr3-7k'
  },
  commonLabels: { alertname: '************** fails alert', rule_uid: 'YTSsr3-7k' },
  commonAnnotations: {},
  externalURL: 'https://grafana.local/',
  version: '1',
  groupKey: '{}:{__alert_rule_uid__="YTSsr3-7k", alertname="************** fails alert", rule_uid="YTSsr3-7k"}',
  truncatedAlerts: 0,
  orgId: 1,
  title: '[RESOLVED] ************** fails alert YTSsr3-7k YTSsr3-7k ',
  state: 'ok',
  message: '**Resolved**\n' +
    '\n' +
    'Value: [no value]\n' +
    'Labels:\n' +
    ' - alertname = ************** fails alert\n' +
    ' - rule_uid = YTSsr3-7k\n' +
    'Annotations:\n' +
    'Source: https://grafana.local/alerting/YTSsr3-7k/edit\n' +
    'Silence: https://grafana.local/alerting/silence/new?alertmanager=grafana&matchers=alertname%3DUnblocked+minion+fails+alert%2Crule_uid%3DYTSsr3-7k\n' +
    'Dashboard: https://grafana.local/d/SoBr6vTmk\n' +
    'Panel: https://grafana.local/d/SoBr6vTmk?viewPanel=7\n'
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Manjaro, Chrome
- Grafana plugins: -
- Others: -

**Comment by zuchka** [comment] 2022-02-24 00:05
Thanks for creating this issue, @aft2d 

Have you tried using a multi-dimensional rule?

From the [docs](https://github.com/grafana/grafana/pull/31352):

>For a query that returns multiple series, Grafana does not track the alert state of each series. As a result, Grafana sends only a single alert even when alert conditions are met for multiple series.

**Comment by aft2d** [comment] 2022-03-02 13:24
A multi dimensional rule works.
Your reference to the docs is exactly what we want. We have that alert that raises when any of the series matches and the alert stays open as long as any series matches. 
But, tbh, I don't really get how this is related to the fact that valueString is empty.

**Comment by murilosrj1990** [comment] 2022-03-13 03:39
I'm facing similar problem, but the "resolved" alert that is arriving empty the "annotation" "__value_string__" inside the body of the webhook.

`{
    "receiver": "apialertslack",
    "status": "resolved",
    "alerts": [
        {
            "status": "resolved",
            "labels": {
                "__alert_rule_namespace_uid__": "chKKKiP7k",
                "__alert_rule_uid__": "_2dRVWEnk",
                "alertname": "MEMORY USED STARGAZE"
            },
            "annotations": {
                "__dashboardUid__": "s38UsmEnz",
                "__panelId__": "78"
            },
            "startsAt": "2022-03-13T02:47:01.186Z",
            "endsAt": "2022-03-13T02:57:01.186Z",
            "generatorURL": "https://telemetry.posbaker.com/grafana/alerting/_2dRVWEnk/edit",
            "fingerprint": "1463e12b33356c44"
        }
    ],
    "groupLabels": {
        "alertname": "MEMORY USED STARGAZE"
    },
    "commonLabels": {
        "__alert_rule_namespace_uid__": "chKKKiP7k",
        "__alert_rule_uid__": "_2dRVWEnk",
        "alertname": "MEMORY USED STARGAZE"
    },
    "commonAnnotations": {
        "__dashboardUid__": "s38UsmEnz",
        "__panelId__": "78"
    },
    "externalURL": "http://telemetry:9093",
    "version": "4",
    "groupKey": "{}/{}:{alertname=\"MEMORY USED STARGAZE\"}",
    "truncatedAlerts": 0
}`

**Comment by ahrtolia** [comment] 2022-04-26 05:48
I also encountered the same problem, is this problem solved?
`{
    "receiver": "echo hook ",
    "status": "firing",
    "alerts": [
        {
            "status": "firing",
            "labels": {
                "alertname": "rocketMQ QPS 过高",
                "channel": "FI"
            },
            "annotations": {
                "owner": "zhaoxiaodong,liangshucheng"
            },
            "startsAt": "2022-04-26T11:57:03.93550693+08:00",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "http://localhost:3000/alerting/JXf5UfQnz/edit",
            "fingerprint": "5e04008d880dab73",
            "silenceURL": "http://localhost:3000/alerting/silence/new?alertmanager=grafana\u0026matchers=alertname%3DrocketMQ+QPS+%E8%BF%87%E9%AB%98%2Cchannel%3DFI",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": ""
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "echo  QPS过高",
                "channel": "FI"
            },
            "annotations": {
                "alert_level": "1",
                "group_id": "FI",
                "owner": "zhaoxiaodong"
            },
            "startsAt": "2022-04-26T10:33:03.93550693+08:00",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "http://localhost:3000/alerting/U8m2Bmwnk/edit",
            "fingerprint": "399e7a735408f482",
            "silenceURL": "http://localhost:3000/alerting/silence/new?alertmanager=grafana\u0026matchers=alertname%3Decho++QPS%E8%BF%87%E9%AB%98%2Cchannel%3DFI",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='plat-limos-ops-v2 GET /publish_history_by_host' labels={app=plat-limos-ops-v2, method=GET, uri=/publish_history_by_host} value=6.666666666666666 ], [ metric='plat-limos-ops-v2 GET /publish_host/running/hosts' labels={app=plat-limos-ops-v2, method=GET, uri=/publish_host/running/hosts} value=6.666666666666666 ], [ metric='plat-nemesis-web GET /metrics' labels={app=plat-nemesis-web, method=GET, uri=/metrics} value=13.333333333333332 ]"
        }
    ],
    "groupLabels": {},
    "commonLabels": {
        "channel": "FI"
    },
    "commonAnnotations": {},
    "externalURL": "http://localhost:3000/",
    "version": "1",
    "groupKey": "{}/{channel=\"FI\"}:{}",
    "truncatedAlerts": 0,
    "orgId": 1,
    "title": "[FIRING:2]  (FI)",
    "state": "alerting",
    "message": "**Firing**\n\nValue: [no value]\nLabels:\n - alertname = rocketMQ QPS 过高\n - channel = FI\nAnnotations:\n - owner = zhaoxiaodong,liangshucheng\nSource: http://localhost:3000/alerting/JXf5UfQnz/edit\nSilence: http://localhost:3000/alerting/silence/new?alertmanager=grafana\u0026matchers=alertname%3DrocketMQ+QPS+%E8%BF%87%E9%AB%98%2Cchannel%3DFI\n\nValue: [ metric='plat-limos-ops-v2 GET /publish_history_by_host' labels={app=plat-limos-ops-v2, method=GET, uri=/publish_history_by_host} value=6.666666666666666 ], [ metric='plat-limos-ops-v2 GET /publish_host/running/hosts' labels={app=plat-limos-ops-v2, method=GET, uri=/publish_host/running/hosts} value=6.666666666666666 ], [ metric='plat-nemesis-web GET /metrics' labels={app=plat-nemesis-web, method=GET, uri=/metrics} value=13.333333333333332 ]\nLabels:\n - alertname = echo  QPS过高\n - channel = FI\nAnnotations:\n - alert_level = 1\n - group_id = FI\n - owner = zhaoxiaodong\nSource: http://localhost:3000/alerting/U8m2Bmwnk/edit\nSilence: http://localhost:3000/alerting/silence/new?alertmanager=grafana\u0026matchers=alertname%3Decho++QPS%E8%BF%87%E9%AB%98%2Cchannel%3DFI\n"
}`
This is the request I got, and you can see that the above alarm has no valueString

**Comment by chanehua** [comment] 2022-05-16 06:52
I also encountered the same problem.
grafana version:  v8.1.5
datasource: prometheus
{
          "receiver": "auto_scal_nodes",
          "matchers": [
            "alert_type=\"auto_update\""
          ],
          "group_wait": "15s",
          "group_interval": "30s",
          "repeat_interval": "5m"
        }
      ]
    },

**Comment by alexweav** [comment] 2022-06-24 16:14
I think this happens if there is a NoData/Execution error, and the alert is mapped to "OK on error/nodata." The lack of value is usually the tell here for execution errors, when the errors are suppressed.

**Comment by vsile** [comment] 2022-06-30 08:32
I have the same problem with Grafana 9.0.1

I get empty valueString in `resolved` event if in the group of alerts more then one item.

If I have only one alert in the alert group I get non-empty valueString, but it includes non-expected value.
So if firinig the value is "0", and if resolved the value is "0" also. But I expect "1"

**Comment by KoyomiKun** [comment] 2022-07-04 06:11
+1 , grafana version v8.3.4 
empty valuestring occurs randomly without error annotation even if error/nodata state is set to 'error'

**Comment by LQCong** [comment] 2022-07-05 01:43
> I have the same problem with Grafana 9.0.1
> 
> I get an empty valueString on `resolved` event if there are more then one item in the group of alerts.
> 
> If I have only one alert in the alert group I get non-empty valueString, but it includes unexpected value. For example, on `firinig` the value is "0", and on `resolved` the value is "0" also. But I expect "1" on `resolved`.

The problem that valuestring is empty still exists in version 9.02. I upgraded version 9.02 yesterday. In the recovery alarm received today, the valuestring field is empty

**Comment by vsile** [comment] 2022-07-05 08:34
This may help to solve the issue:

In [pkg/services/ngalert/notifier/channels/template_data.go](https://github.com/grafana/grafana/blob/f78b7f1f179e6fb8f2e378e425cd8d0b64762b1b/pkg/services/ngalert/notifier/channels/template_data.go#L93) we set ValueString as alert.Annotations[\`\_\_value_string\_\_\`]:
```
if alert.Annotations != nil {
	extended.ValueString = alert.Annotations[`__value_string__`]
}
```
In [pkg/services/ngalert/schedule/compat.go](https://github.com/grafana/grafana/blob/f78b7f1f179e6fb8f2e378e425cd8d0b64762b1b/pkg/services/ngalert/schedule/compat.go#L39) we set nA as alertState.LastEvaluationString.
```
if alertState.LastEvaluationString != "" {
	nA["__value_string__"] = alertState.LastEvaluationString
}
```
But in [pkg/services/ngalert/manager.go](https://github.com/grafana/grafana/blob/f78b7f1f179e6fb8f2e378e425cd8d0b64762b1b/pkg/services/ngalert/state/manager.go#L124) we erase the field `LastEvaluationString`.
```
stateForEntry := &State{
	AlertRuleUID:         entry.RuleUID,
	OrgID:                entry.RuleOrgID,
	CacheId:              cacheId,
	Labels:               lbs,
	State:                translateInstanceState(entry.CurrentState),
	StateReason:          entry.CurrentReason,
	LastEvaluationString: "",
	StartsAt:             entry.CurrentStateSince,
	EndsAt:               entry.CurrentStateEnd,
	LastEvaluationTime:   entry.LastEvalTime,
	Annotations:          ruleForEntry.Annotations,
}
```
Why the field `LastEvaluationString` is erasing here?

**Comment by santihernandezc** [comment] 2022-10-18 17:44
Hi @aft2d, what's your config for No Data/Error scenarios? That tab is collapsed in your screenshots. I'd really appreciate specific steps to reproduce the issue.
It's expected that `valueString` is empty when an alert fires due to no data/error.

**Comment by santihernandezc** [comment] 2022-11-01 16:18
It has been two weeks since my last message. I'm closing this issue, but feel free to reopen it if needed.

**Comment by vsile** [comment] 2022-11-01 18:15
The issue is still actual with Grafana 9.2.1.
Unlikely "No data and error handling" configuration is a point of the issue. Anyway here is my configuration.
![изображение](https://user-images.githubusercontent.com/9244347/199303962-e93bfd8a-1a21-44f3-b827-92417da09ed3.png)

@santihernandezc 
To reproduce the error try to create 20-25 alert rules and to simulate firing and solving of all of them.

**Comment by vsile** [comment] 2023-02-14 07:15
The issue is still actual with Grafana 9.3.0.
@santihernandezc, could you reopen the issue, please?

**Closed** 2023-03-06 17:32 UTC
Labels: type/bug, prio/high, area/alerting/notifications
