### ISSUE TITLE
Changing scale on the x-axis (Timeseries, Grafana 8.2.3)

### ISSUE THREAD

**Issue by roe1974** [grafana/grafana#41548] opened 2021-11-10 13:53 UTC
Hello
I updated my Grafana Docker yesterday to version 8.2.3. I have the following phenomenon with my dashboards: the x-axis (timeseries) changes approx. in 15 seconds interval from hour display (16:00, 18:00, 20:00 ....) to a day display (9/11 16:00, 9/11 20:00, ...). Can I set that only the hour display remains constant like earlier with Grafaba 7.x ? Attached two screenshots:
<img width="291" alt="1" src="https://user-images.githubusercontent.com/30420568/141125552-9241639f-5262-4f89-b508-71e3a3d0d284.PNG">
<img width="289" alt="2" src="https://user-images.githubusercontent.com/30420568/141125558-766d68bc-51f4-4a3e-879d-c577e47a8a7a.PNG">

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Docker
- User OS & Browser: iOS, Windows 10
- Grafana plugins:
- Others:

**Comment by roe1974** [comment] 2021-11-10 15:12
hi @ashharrison90 

The problem is like you describe here:

- screenshot A and screenshot B are both from Grafana 8.2.3, and every 15 seconds or so it alternates between the display in screenshot A and screenshot B? -> YES .. but only the x-axis changes like you see in the two screenshots.

so .... this sounds like a bug ;-)

**Comment by ashharrison90** [comment] 2021-11-10 15:16
@roe1974 thanks for the clarification, that does sound annoying and like a bug 😄

**Comment by roe1974** [comment] 2021-11-10 15:27
@ashharrison90 
PS: this happens especially when embeding the dashbards using links like this:

http://xxx.xxx.xxx.xxx:3000/d-solo/uAqhn9BWz/home-overviews?orgId=1&refresh=5s&from=now-24h&to=now&panelId=7&width=696&height=420&frameborder=0

**Comment by ashharrison90** [comment] 2021-11-10 16:19
few more questions @roe1974 if you don't mind:
- does this occur at any other browser zoom levels? 
- does this occur at different panel sizes?
- does this occur with different time ranges? looks like you're on now-24h currently, if you set that to `now-23h` or something does that work around the issue?

thanks again!

**Comment by roe1974** [comment] 2021-11-10 16:26
hi @ashharrison90 

does this occur at any other browser zoom levels? -> YES
does this occur at different panel sizes? -> YES
does this occur with different time ranges? looks like you're on now-24h currently, if you set that to now-23h or something does that work around the issue? -> YES !!!! ... when i change to now-8h, i see only values from the actual day, there is no flipping values on x-axis. I guess now that happens only when the displayed area is more than the current day

**Comment by ashharrison90** [comment] 2021-11-10 17:00
@roe1974 thanks for the info. 🙌 
yes, it should only show the date when the time range spans more than 24 hours.
our resident timeseries expert (and `uPlot` creator) @leeoniya suspected something similar, that before the data refreshes it must just tick over into >24h. we're struggling to reproduce locally though which is why i was asking about zoom levels/panel sizes 😅

**Comment by roe1974** [comment] 2021-11-10 17:03
do you need more informations ? ;-)

**Comment by ashharrison90** [comment] 2021-11-10 17:13
@roe1974 dashboard json might be useful if you don't mind sharing that? 

you can find that via `share dashboard` -> `export` -> `export for sharing externally` then click `view json`

i'll leave the rest to the guys that work on the timeseries panel. thanks for all your help! 😄

**Comment by roe1974** [comment] 2021-11-10 17:48
et voila :-)
[dash.txt](https://github.com/grafana/grafana/files/7514874/dash.txt)

**Comment by dprokop** [comment] 2021-11-12 15:07
May be a duplicate of https://github.com/grafana/grafana/issues/39869

**Closed** 2021-11-15 14:16 UTC
Labels: type/bug, area/panel/timeseries

**Comment by roe1974** [comment] 2021-11-29 07:51
In which Grafana version will the fix flow in ?
