### ISSUE TITLE
[Feat] Validate templated queries so you cannot create circular references

### ISSUE THREAD

**Issue by dupondje** [grafana/grafana#12743] opened 2018-07-27 14:06 UTC
Please include this information:
### What Grafana version are you using?
5.2.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Debian 9
### What did you do?
I edited a variable:
```
label_values(memcached_uptime{iv_name=~"$iv_name"}, server)
```

Into
```
label_values(memcached_uptime{iv_name=~"$iv_name", server=~"$server"}, server)
```
### What was the expected result?
The variable query is indeed incorrect. But I would expect a warning, or just that it doesn't work

### What happened instead?
When its saved, the complete graph page is empty. You are even unable to edit the graph again to fix the mistake...

**Comment by zoltanbedi** [comment] 2021-03-29 13:14
This is still an "issue" in 7.5.1 that you can create circular references without any hint or warning. I'm also going to remove Prometheus label as this is a @grafana/grafana-frontend-platform issue.

**Comment by hugohaggmark** [comment] 2021-03-30 09:00
Duplicate of #8583

**Closed by hugohaggmark** 2021-03-30 09:00 UTC
Labels: area/dashboard/templating, area/ux, priority/nice-to-have, type/bug
