### ISSUE TITLE
Search: Cannot type Korean character in search input

### ISSUE THREAD

**Issue by donghoon-lee-mrt** [grafana/grafana#76595] opened 2023-10-16 04:51 UTC
### What happened?

When I try to type Korean characters in Dashboard search input on the top of screen, all characters are separated.
<img width="1499" alt="image" src="https://github.com/grafana/grafana/assets/109510557/c2c0816f-328c-42d5-83a1-4036a1d7ac92">

### What did you expect to happen?

For example, I expect to input "대시보드" in the search box, but search box only shows "ㄷㅐㅅㅣㅂㅗㄷㅡ".

### Did this work before?

Yes, we have used 9.2 and 9.4, it worked.

### How do we reproduce it?

1. Install Korean keyboard input in your OS.
2. Go to https://play.grafana.org/ and click search box
3. Change input mode to Korean (2-set Korean) Try to type "대시보드" (in US keyboard, you can type `eotlqhem`)

### Environment (with versions)?

Grafana: v10.2.0-60853 (0c081633) (Official Sandbox play.grafana.org)
OS: MacOS 13.4 (22F66)
Browser: Chrome 117.0.5938.149

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Prometheus

**Comment by usmangt** [comment] 2023-10-24 08:42
Hi @donghoon-lee-mrt,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by joshhunt** [comment] 2023-10-25 09:47
Dupe of https://github.com/grafana/grafana/issues/72864.

It appears that was closed incorrectly, so I've reopened it so we can take a look at it again.

**Closed by joshhunt** 2023-10-25 09:47 UTC
Labels: area/search
