### ISSUE TITLE
Cannot seem to use the Variable 'Include All Option' with wildcard value % and the like statement in MySQL

### ISSUE THREAD

**Issue by jrobertsz366** [grafana/grafana#27343] opened 2020-09-02 19:53 UTC
When I use the 'Include All Option' for a variable with the value % and then try to use it in a query with a statement 'column like '$variable' I get an error and no results

**Comment by therealcodlord** [comment] 2020-09-02 20:31
You have given no useful information in your report. I would suggest you edit your original report with some or all of the information requested in the issue template such as:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment] 2020-09-03 08:37
@therealcodlord thank you 🌟  and @jrobertsz366 please supply information as describe by @therealcodlord 

All the best

**Comment by torkelo** [comment] 2020-10-12 14:46
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.

**Closed by torkelo** 2020-10-12 14:46 UTC
Labels: needs more info
