### ISSUE TITLE
Docs need upating to reflect Debian best-practice

### ISSUE THREAD

**Issue by udf2457** [grafana/grafana#37586] opened 2021-08-05 11:50 UTC
Re: https://grafana.com/docs/grafana/latest/installation/debian/#install-from-apt-repository

The instructions presented for key handling are not inline with Debian best-practices.

As per https://wiki.debian.org/DebianRepository/UseThirdParty: 

> The key MUST be downloaded over a secure mechanism like HTTPS to a location only writable by root, which SHOULD be /usr/share/keyrings. The key MUST NOT be placed in /etc/apt/trusted.gpg.d or loaded by apt-key add. A sources.list entry SHOULD have the signed-by option set. The signed-by entry MUST point to a file, and not a fingerprint.

**Comment by zuchka** [comment] 2022-02-04 01:15
duplicate of https://github.com/grafana/grafana/issues/35467

working on a draft pr to replace apt-key in the docs

**Closed by zuchka** 2022-02-04 01:15 UTC
Labels: type/docs, help wanted, area/backend
