### ISSUE TITLE
Table panel - allow text wrapping in cells

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#32164] opened 2021-03-19 13:53 UTC
**What would you like to be added**:
In Grafana 6, it was possible to customize text wrapping

**Why is this needed**:
Return lost functionality

**Comment by torkelo** [comment] 2021-03-20 12:35
duplicate of https://github.com/grafana/grafana/issues/25623

**Closed by torkelo** 2021-03-20 12:35 UTC
