### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by einhirn** [grafana/grafana#7371] opened 2017-01-26 14:19 UTC
- What Grafana version are you using?
 Grafana v4.1.1 (commit: v4.1.1)

- What datasource are you using?
InfluxDB v1.1

- What OS are you running grafana on?
Ubuntu 14.04.5 LTS x86_64
- What did you do?
Added a graph, multiple queries with one series each. Defined an alert on "query(A,1m,now)". 

- What was the expected result?
It should have worked, at least showing the graph. Group by time Interval was ">120s", so I should have used "query(A,5m,now)" or something, granted. But even so, at most, the alert shouldn't have worked.

- What happened instead?
The query produces an error and no datapoints at all. Problem is that suddenly instead of a computed "group by time interval", the "$interval" is replaced with the literal "group by time interval" setting. The json shows that ">120s" is entered as an "Override relative time" - which of course doesn't work.

- An image or text representation of your metric query
![image](https://cloud.githubusercontent.com/assets/189249/22334178/0d2f8e84-e3da-11e6-9c28-5b097fb5dfa5.png)

- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)
````
SELECT difference(mean("eqliscsiVolumeStatsWriteLatency")) / difference(mean("eqliscsiVolumeStatsWriteOpCount")) AS "Avg. Write Latency" FROM "eqlVolumeStats" WHERE "eqliscsiVolumeName" = 'vdi1' AND time > 1485193416472ms and time < 1485265267378ms GROUP BY time(>120s) fill(null);SELECT difference(mean("eqliscsiVolumeStatsReadLatency")) / difference(mean("eqliscsiVolumeStatsReadOpCount")) AS "Avg. Read Latency" FROM "eqlVolumeStats" WHERE "eqliscsiVolumeName" = 'vdi1' AND time > 1485193416472ms and time < 1485265267378ms GROUP BY time(>120s) fill(null);SELECT mean("eqliscsiVolumeStatsWriteAvgLatency") / 1000 AS "Avg. Write Latency (~3hr)" FROM "eqlVolumeStats" WHERE "eqliscsiVolumeName" = 'vdi1' AND time > 1485193416472ms and time < 1485265267378ms GROUP BY time(2m) fill(null);SELECT mean("eqliscsiVolumeStatsReadAvgLatency") / 1000 AS "Avg. Read Latency (~3hr)" FROM "eqlVolumeStats" WHERE "eqliscsiVolumeName" = 'vdi1' AND time > 1485193416472ms and time < 1485265267378ms GROUP BY time(2m) fill(null)
````
Panel JSON:
[panel.json.txt](https://github.com/grafana/grafana/files/732464/panel.json.txt)

- An image of the test execution data fully expanded.
By now I've deleted the alert again, because it didn't work together with templating and "repeat row on <template variable>". But the error described above remains.

I'm able to remove the bad "interval"-entries from the panel json, but up until now the query was somehow always broken again after changing to another dashboard and back to this one...

**Comment by torkelo** [comment] 2017-01-26 14:25
this is fixed in master, try a nightly build of the next release 4.2
grafana.org/builds/

dupe of https://github.com/grafana/grafana/issues/6765

**Closed by torkelo** 2017-01-26 14:25 UTC

**Comment by einhirn** [comment] 2017-01-26 14:34
Thanks - I didn't spot the other issue because I only searched for open issues - oh well...
