### ISSUE TITLE
Image Rendering Timeout too low (2secs) ?

### ISSUE THREAD

**Issue by garceri** [grafana/grafana#16663] opened 2019-04-18 01:53 UTC
**What happened**:
Setting up Telegram alerts. The panel i'm alerting from can take some time to render after failing to receive the image on the alert message found errors on grafana log stating that image rendering failed, Log timestamps seem to imply that the timeout was set to 2 seconds

**What you expected to happen**:
Rendering timeout should be configurable
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
These are the relevant log entries:
`t=2019-04-17T22:46:01-0300 lvl=info msg=Rendering logger=rendering path="d-solo/ZQHR1QgZz/alerting?orgId=1&panelId=2"
t=2019-04-17T22:46:03-0300 lvl=info msg="Rendering timed out" logger=rendering
t=2019-04-17T22:46:03-0300 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-04-17T22:46:03-0300 lvl=eror msg="Could not close Telegram inline image." logger=alerting.notifier.telegram err="invalid argument"
t=2019-04-17T22:46:03-0300 lvl=eror msg="Could not generate Telegram message with inline image." logger=alerting.notifier.telegram err="open : no such file or directory"
`

**Environment**:
- Grafana version: 6.2.0 Nighty 4/17/19
- Data source type & version: Prometheus 2.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows / Chrome x86_64
- Grafana plugins:None
- Others:

**Comment by torkelo** [comment] 2019-04-18 06:19
where did you get 2s from? it's 30 seconds I think.

**Comment by torkelo** [comment] 2019-04-18 06:20
This looks like a problem in the telegram upload

**Comment by garceri** [comment] 2019-04-18 18:50
Look at the logs i attached, the first message signals rendering start at 22:46:01, the timeout message happens at 22:46:03 ( 2 seconds) i had the same error while trying to use a slack notification channel, the graph tales more than 2 seco ds to render for sure as i've already tried to use the image direct link from the panel and it took about 10 secs to get the image.

**Comment by marefr** [comment] 2019-04-24 16:22
@garceri please try and change timeout to higher values and report back if that makes any difference https://grafana.com/docs/installation/configuration/#evaluation-timeout-seconds

**Comment by garceri** [comment] 2019-04-24 21:00
@marefr just tried it, no change, same Timeout error after 2 seconds.

**Comment by marefr** [comment] 2019-04-25 07:56
@garceri thanks. Can you please try and enable rendering debug and report the debug messages from Grafana server log here when your above error happens.

```
[log]
filters = rendering:debug
```

**Comment by garceri** [comment] 2019-04-26 00:56
Here you go @marefr :


**This is the rendering log from the alert**
`t=2019-04-25T21:41:31-0300 lvl=info msg=Rendering logger=rendering path="d-solo/ZQHR1QgZz/alerting?orgId=1&panelId=3"
t=2019-04-25T21:41:31-0300 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/ZQHR1QgZz/alerting?orgId=1&panelId=3&render=1 width=1000 height=500 png=/var/lib/grafana/png/OhmtqljbXuROBbPp6olh.png domain=localhost timeout=2.7e-08 renderKey=hMfhpTLTukrM0EQQHIQUy9j2wa7XsvzG]" timezone=
t=2019-04-25T21:41:33-0300 lvl=dbug msg="Phantomjs output" logger=rendering out=
t=2019-04-25T21:41:33-0300 lvl=dbug msg="Phantomjs error" logger=rendering error="signal: killed"
t=2019-04-25T21:41:33-0300 lvl=info msg="Rendering timed out" logger=rendering
t=2019-04-25T21:41:33-0300 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Timeout error. You can set timeout in seconds with &timeout url parameter"
`
Note the funny looking scientific notation timeout value on the "executing phantomjs" line, looks like that's maybe causing the 2sec timeout to fire.

**This is the rendering log from an attempt to use the Panel Share Direct Link**
`t=2019-04-25T21:18:56-0300 lvl=info msg=Rendering logger=rendering path="d-solo/ZQHR1QgZz/alerting?tab=alert&orgId=1&refresh=5m&panelId=3&from=1556216329065&to=1556237929065&width=1000&height=500&tz=America%2FBuenos_Aires"
t=2019-04-25T21:18:56-0300 lvl=dbug msg="executing Phantomjs" logger=rendering binPath=/usr/share/grafana/tools/phantomjs/phantomjs cmdArgs="[--ignore-ssl-errors=true --web-security=false --debug=true /usr/share/grafana/tools/phantomjs/render.js url=http://localhost:3000/d-solo/ZQHR1QgZz/alerting?tab=alert&orgId=1&refresh=5m&panelId=3&from=1556216329065&to=1556237929065&width=1000&height=500&tz=America%2FBuenos_Aires&render=1 width=1000 height=500 png=/var/lib/grafana/png/AYRQkpM2zhir9lGYj5aw.png domain=localhost timeout=60 renderKey=EPxT7Mk9ZXCNu7BsTSCFWMP5NZ8NtoJ7]" timezone=America/Buenos_Aires
t=2019-04-25T21:19:17-0300 lvl=dbug msg="Phantomjs output" logger=rendering out="Loading a web page: http://localhost:3000/d-solo/ZQHR1QgZz/alerting?tab=alert&orgId=1&refresh=5m&panelId=3&from=1556216329065&to=1556237929065&width=1000&height=500&tz=America%2FBuenos_Aires&render=1 status: success 60000\n"
t=2019-04-25T21:19:17-0300 lvl=dbug msg="Image rendered" logger=rendering path=/var/lib/grafana/png/AYRQkpM2zhir9lGYj5aw.png
`

Here the same value is set to a sane 60 secs value...

**Comment by marefr** [comment] 2019-04-26 08:54
@garceri thank you! Confirmed bug. Will be fixed until 6.2 stable.

**Comment by marefr** [comment] 2019-04-26 09:02
It's a regression of #16240

**Comment by bergquist** [comment] 2019-04-26 09:10
https://github.com/grafana/grafana/blob/master/pkg/setting/setting.go#L894 is also wrong since the default value here https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L497 is `30` and not `30s`

**Closed** 2019-04-30 10:05 UTC
Labels: area/alerting/notifications, area/image-rendering, type/bug
