### ISSUE TITLE
ElasticSearch datasource - JS error when using the filter for value option

### ISSUE THREAD

**Issue by camsellem** [grafana/grafana#36770] opened 2021-07-15 00:52 UTC
**What happened**:

A javascript error is thrown when trying to filter the results using the "Filter for value"/"Filter out for value" option.

**What you expected to happen**:

Expecting behaviour is to have the value added/appended to the query

**How to reproduce it (as minimally and precisely as possible)**:

- Go to the explore view
- Open an ElasticSearch Datasource
- Select "Raw data" in the query builder
- Click "Filter for value"/"Filter out for value" option in the result table.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.5
- Data source type & version: ElasticSearch
- OS Grafana is installed on: K8S (Grafana internal demo env)
- User OS & Browser: MacOS / Brave
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/3879044/125710981-6faeacba-b649-497e-8066-e55b7eeef955.png)

**Comment by zoltanbedi** [comment] 2021-07-15 10:07
I think this is a duplicate of https://github.com/grafana/grafana/issues/28076

**Closed by zoltanbedi** 2021-07-15 10:07 UTC
