### ISSUE TITLE
Grafana 7, table view not function as before - raw data, display/transform as json data

### ISSUE THREAD

**Issue by doronha** [grafana/grafana#25759] opened 2020-06-23 06:08 UTC
**What happened**:
Use table panel, connect to Elasticsearch data source, in query select "raw document", select "json data" in table transform or in panel option 

**What you expected to happen**:
have a table with the json data fields where user can change the column style as was before 7.

**How to reproduce it (as minimally and precisely as possible)**:
describe above

**Anything else we need to know?**:
While importing table panel from 6 to 7, the table is presented as previously but while editing it doesn't have the "table" as selected visualization  and can't enjoy the new functionality of 7/table

**Environment**:
- Grafana version:
Grafana v7.0.3 (00ee734baf)
- Data source type & version:
elasticsearch native plugin
- OS Grafana is installed on:
Linux
- User OS & Browser:
windows & Chrome
- Grafana plugins:
OOB
- Others:

**Comment by marefr** [comment] 2020-06-23 09:47
Duplicate of #24163

**Closed by marefr** 2020-06-23 09:47 UTC
