### ISSUE TITLE
When editing Data links in Table (new version) the option "open in new tab" is set to off

### ISSUE THREAD

**Issue by cnoork** [grafana/grafana#26102] opened 2020-07-06 20:15 UTC
**What happened**:
When I go back to the Edit link in the Table report it does not read the current state and thereby it is always set to off for "open in new tab".

**What you expected to happen**:
I expect that the last status is displayed and when saving it is not changed.

**How to reproduce it (as minimally and precisely as possible)**:
For every edit it is set to off.

**Environment**:
- Grafana version: v7.0.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: docker image: grafana/grafana
- User OS & Browser: Windows 10 & Chrome Version 83.0.4103.116

**Comment by torkelo** [comment] 2020-07-07 08:20
duplicate of https://github.com/grafana/grafana/issues/25445  fix incoming in 7.1

**Closed by torkelo** 2020-07-07 08:20 UTC
