### ISSUE TITLE
Relative data links starting with / are prefixed by root_url

### ISSUE THREAD

**Issue by barry-luijten** [grafana/grafana#33118] opened 2021-04-19 10:59 UTC
**What happened**:
We serve Grafana from a subpath on a url that also contains other subpaths. Grafana is for instance hosted on <url>/grafana/ and another app on <url>/otherapp/.

When adding a data link to a panel with url  /otherapp/, the resulting link is rendered as **/grafana**/otherapp/.

**What you expected to happen**:
I expected that a relative url starting with / should always point to the root of the url, not the grafana root url, so in this case, I would expect the link to render as <url>/otherapp/. 
When creating a link to another Grafana dashboard, I specify "/grafana/d/<dashboard_id>", which still works as expected.

**How to reproduce it (as minimally and precisely as possible)**:
docker environment variables set:
GF_SERVER_ROOT_URL=<url>/grafana/
GF_SERVER_SERVE_FROM_SUB_PATH=true
Create a panel with a data link and a url /otherapp/.
Hover over the link and look in the lower-left corner of the browser, so the target is shown. It will show the prefixed url.

**Anything else we need to know?**:
We are running Grafana behind an Apache reverse proxy. Grafana is running on http://localhost:3000, the reverse proxy listens on https://<url>/grafana and forwards requests to http://localhost:3000

When creating the same link in a HTML text panel manually, the link works as expected.

**Environment**:
- Grafana version: 7.5.4 docker version
- Data source type & version: Elasticsearch
- OS Grafana is installed on: RHEL 7
- User OS & Browser: MS Edge latest build
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment] 2021-04-19 12:01
Duplicate of #24594

**Closed by hugohaggmark** 2021-04-19 12:01 UTC
Labels: bot/duplicate
