### ISSUE TITLE
Unable to get admin access while authenticating via github

### ISSUE THREAD

**Issue by asharabu** [grafana/grafana#18980] opened 2019-09-10 07:41 UTC
Hi,

I have enabled GitHub authentication on grafana container and limited by team_ids and we are able to login to the grafana using github also able to see dashboard but we are unable to get admin access via github login to create new dashboard etc. Can someone please assist?

**Comment by torkelo** [comment] 2019-09-10 11:36
duplicate of https://github.com/grafana/grafana/issues/8875

**Closed by torkelo** 2019-09-10 11:36 UTC
