### ISSUE TITLE
Constant variables should be allowed in alerts

### ISSUE THREAD

**Issue by Sytten** [grafana/grafana#18418] opened 2019-08-06 16:29 UTC
**What would you like to be added**:
This is in part related to #6557. The issue raised is that variables should be allowed in alerts, though it is not agreed on how best to do that if you have multiple values. But In the case of a constant you only have one possible value so it should be fairly easy to implement and should not be a big debate.

**Why is this needed**:
This is needed because you have datasources like cloudwatch who do not support wildcards. So it is very hard to share dashboards between multiple environments without a constant for this environment (for example we use kinesis streams which are referenced like `streams-<ENV>-main-mystream`).

**Comment by marefr** [comment] 2019-08-06 17:00
Duplicate of #6557

**Comment by marefr** [comment] 2019-08-06 17:01
Have to close this as duplicate since we're trying to keep the number of opened issues as low as possible and have one issue tracking one feature request.

**Closed by marefr** 2019-08-06 17:01 UTC

**Comment by Sytten** [comment] 2019-08-06 17:04
Since there has been no progress on that other issue for a long time, this is a bit weird to close it. Like I said this is related, but not a duplicates because it could probably be implemented much more quickly...

**Comment by marefr** [comment] 2019-08-06 18:00
> Since there has been no progress on that other issue for a iong time

That doesn't count for that new issues should be opened. We're aware of the feature request, but not sure that alert rules and template variables is something to build upon for the future, rather we may want to to separate alert rules from dashboards/panels as a first step. This is all related to Grafana next gen alerting which still is in early discussion phase.

**Comment by mvndaai** [comment] 2019-12-11 21:54
I still don't understand why this isn't allowed. I can understand the rest of  #6557 being complicated. 

@marefr since
> This is all related to Grafana next gen alerting which still is in early discussion phase.

why not make a change that shouldn't be to complicated and would have high impact on customers? 

Has next gen alerting been figured out? When is that expected?
