### ISSUE TITLE
Grafana should do the timezone convertion before perform $__unixEpochGroup

### ISSUE THREAD

**Issue by oz4899** [grafana/grafana#28489] opened 2020-10-23 05:11 UTC
**What happened**:
When we have data point which store together with timestamp in Postgres SQL and we try to make a summary report based on daily granularity.  Grafana perform the normalize process (specified in unixEpochGroup) before convert the presentation layer to be in defined timezone of grafana setting , see below example: 

let say we have below datapoint and our grafana preference is set to GMT+7 (will present by JSON format for the sake of simplicity)
{
  (below time is  Tuesday, October 20, 2020 17:10:10 in GMT or Wednesday, October 21, 2020 0:10:10 GMT+07:00)
  time_in_sec_epoch:  1603213810,
  value: 555
}

when we do some query to make time group as 1 day granularity (1440 minutes)

select $__unixEpochGroup(time_in_sec_epoch,'1440m', 0) as time , count(value)
from test_table
group by time

Currently Grafana will show result as 
time = 2020-10-20 - 07:00 
value = 1 

**What you expected to happen**:
Grafana should convert the timezone first so that the unixEpochGroup function work properly so the result should be 

time = 2020-10-21 - 00:00
value =1 

**How to reproduce it (as minimally and precisely as possible)**:

see first section

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.1.5
- Data source type & version: postgres SQL
- OS Grafana is installed on: Cloud, on premise AWS EC-2
- User OS & Browser: windows 10 , chrome
- Grafana plugins:
- Others:

**Comment by wbrowne** [comment] 2020-10-26 16:45
Thanks for creating this issue @oz4899. I believe this is a /duplicate of #18120, therefore I will close as we will track any changes from the original issue.

**Closed by wbrowne** 2020-10-26 16:45 UTC
Labels: datasource/Postgres, type/bug
