### ISSUE TITLE
No information shown in alert resolve message

### ISSUE THREAD

**Issue by prabhinmp** [grafana/grafana#33810] opened 2021-05-07 08:43 UTC
Hi,
I’m using grafana for our monitoring system to send alerts based on the data fetched by the Prometheus from the Kubernetes cluster.

I’m using ${label} in the alert name and the message fields. But I found that the alert resolve message doest not resolve the label variables. Please find the attached screenshot below.

Even the details section is blank in the alert resolve message. is there a way to add details in the resolve messages?
Kindly please suggest on this.
<img width="1274" alt="Screenshot 2021-04-30 at 10 42 42 AM" src="https://user-images.githubusercontent.com/34641909/117423390-4f684a00-af3e-11eb-92f9-dd709a637b27.png">

**Comment by marefr** [comment] 2021-05-18 16:42
Duplicate of #30606

**Closed by marefr** 2021-05-18 16:42 UTC
Labels: area/alerting, area/alerting/notifications, needs investigation
