### ISSUE TITLE
Cannot edit row title in Grafana 6.0.0-beta1

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#15369] opened 2019-02-11 16:09 UTC
### What Grafana version are you using?
6.0.0-beta1

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
Ubuntu 18.04 in Docker

### What did you do?
Define a dashboard with a row. Click the cog to edit the row.

### What was the expected result?
A modal shows up letting me edit the title

### What happened instead?
The modal overlay kinda works, something is clearly overlayed on the screen because everything is muted/grey-washed. But nothing else shows up.

I see this in the developer console:

```
/grafana/public/app/features/dashboard/partials/row_options.html?v=1549901142771:1 Failed to load resource: the server responded with a status of 404 ()
vendor.383d9ff15706c7fc3a05.js:134 Error: [$compile:tpload] Failed to load template: public/app/features/dashboard/partials/row_options.html (HTTP status: 404 )
http://errors.angularjs.org/1.6.6/$compile/tpload?p0=public%2Fapp%2Ffeatures%2Fdashboard%2Fpartials%2Frow_options.html&p1=404&p2=
    at vendor.383d9ff15706c7fc3a05.js:134
    at vendor.383d9ff15706c7fc3a05.js:134
    at vendor.383d9ff15706c7fc3a05.js:134
    at vendor.383d9ff15706c7fc3a05.js:134
    at l.$digest (vendor.383d9ff15706c7fc3a05.js:134)
    at l.$apply (vendor.383d9ff15706c7fc3a05.js:134)
    at vendor.383d9ff15706c7fc3a05.js:134
    at h (vendor.383d9ff15706c7fc3a05.js:134)
    at vendor.383d9ff15706c7fc3a05.js:134
(anonymous) @ vendor.383d9ff15706c7fc3a05.js:134
vendor.383d9ff15706c7fc3a05.js:134 Error: [$compile:tpload] Failed to load template: public/app/features/dashboard/partials/row_options.html (HTTP status: 404 )
http://errors.angularjs.org/1.6.6/$compile/tpload?p0=public%2Fapp%2Ffeatures%2Fdashboard%2Fpartials%2Frow_options.html&p1=404&p2=
    at vendor.383d9ff15706c7fc3a05.js:134
    at vendor.383d9ff15706c7fc3a05.js:134
    at vendor.383d9ff15706c7fc3a05.js:134
    at vendor.383d9ff15706c7fc3a05.js:134
    at l.$digest (vendor.383d9ff15706c7fc3a05.js:134)
    at l.$apply (vendor.383d9ff15706c7fc3a05.js:134)
    at vendor.383d9ff15706c7fc3a05.js:134
    at h (vendor.383d9ff15706c7fc3a05.js:134)
    at vendor.383d9ff15706c7fc3a05.js:134
(anonymous) @ vendor.383d9ff15706c7fc3a05.js:134
```

**Comment by torkelo** [comment] 2019-02-11 16:17
dupe of https://github.com/grafana/grafana/issues/15157 

fix incoming in beta2 releasing soon (today)

**Closed** 2019-02-11 16:30 UTC
