### ISSUE TITLE
Auto hide no data tiles

### ISSUE THREAD

**Issue by Ustat-Singh** [grafana/grafana#23793] opened 2020-04-22 16:12 UTC
**What would you like to be added**:
When creating large shared dashboards, sometimes its useful to create tiles for things that may not exist in every scenario. Example, it maybe useful to display a sql metric, if the workload has sql. However when the workload does not have sql, it would be beneficial to hide that tile.

**Why is this needed**:
In order to enable us to create better standard dashboards that apply to a wide variety of scenarios.

**Comment by jbrownleed01** [comment] 2020-04-22 16:21
Same need for me as well. It would be nice to have an option by tile to hide when zero rows are returned by the query. That way the dashboard author can determine when it will or won't happen.

**Comment by torkelo** [comment] 2020-04-22 16:54
duplicate of https://github.com/grafana/grafana/issues/4470

**Closed by torkelo** 2020-04-22 16:54 UTC
