### ISSUE TITLE
Grafana 9 permissions changes

### ISSUE THREAD

**Issue by Lusitaniae** [grafana/grafana#51798] opened 2022-07-06 09:57 UTC
**What happened**:
I can't access Teams as Grafana Admin

**What you expected to happen**:
I can access teams as Grafana Admin

**How to reproduce it (as minimally and precisely as possible)**:
1. Login as "Grafana Admin"
2. Access "Teams" `/org/teams `
3. Get redirected away

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment] 2022-07-06 11:16
Hmmm, I'm not able to reproduce this

![image](https://user-images.githubusercontent.com/46142/177536347-09884318-fb25-48c5-9137-5c749b03d56d.png)

I also tried creating an admin on 8.5.6 and then upgrading to 9.0.2 and it still had permissions to create teams.

What exactly Role does this "Grafana Admin" user have?

**Comment by IevaVasiljeva** [comment] 2022-07-08 10:27
Hi @Lusitaniae! Which version of Grafana were you using previously?

Team page is intended to only be accessible by Organization Admins (or Organization Editors if `editors_can_admin` setting is enabled), and it's been this way for a while. Grafana Server Admin role does not grant any extra access to teams. Here's an overview of what access different roles grant: https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/#organization-roles

So it seems like it works as intended now. But I'm curious to learn more about what your workflow and permission setup were before Grafana 9.0, perhaps there's something that I'm overlooking here :)

**Comment by Lusitaniae** [comment] 2022-07-08 12:16
Using grafana 8.5.x before

We're doing multi tenant in 2 ways:

Folder per customer:
- Add all dashboards inside
- Add Team "Customer A" with role viewer to the folder

Dashboard per customer:
- Single dashboard, add team with role viewer to the folder

Admins simply have Admin role in a single organization which **was** enough for **any** day to day tasks (inviting users, managing teams, dashboards, etc)

It's likely we need to improve things on our side too, feel free to close

**Comment by vtorosyan** [comment] 2022-07-19 08:12
Thanks for the issue, as suggested, I'll close the issue now.

**Closed by vtorosyan** 2022-07-19 08:12 UTC
Labels: needs more info, area/auth/rbac
