### ISSUE TITLE
Buggy scroll and focus changes when using multiple queries in a panel

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#28675] opened 2020-10-29 18:12 UTC
**What happened**:
Switching between queries in a panel with the mouse causes unexpected jumps and focus changes occasionally. Sometimes this also causes deletion of parts of the query, but I am unable to reproduce this.

**What you expected to happen**:
Selecting a query should move your cursor to that query.

**How to reproduce it (as minimally and precisely as possible)**:
I've experienced this in a variety of scenarios with no clear pattern, but with some playing around I've found these steps to work reliably:

1. Create new panel
2. Add some query, e.g. `up`
3. Duplicate the query until the scrollbar appears
4. Edit query A and use autocomplete to add a label selector, e.g. `up{instance="test"}`
5. Scroll downwards until the text field for query A is no longer visible
6. Click the last query
7. With Firefox, the cursor has now jumped to the start of query A, which is now in view. With Chrome, the click is simply ignored.

**Anything else we need to know?**:
CC @torkelo, who requested a bug report for this

**Environment**:
- Grafana version: 7.3.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian and Ubuntu
- User OS & Browser: Fedora/Debian, Firefox/Chrome
- Grafana plugins: N/A
- Others:

**Comment by hugohaggmark** [comment] 2020-10-30 05:44
Hi @NotAFile, hard issues to reproduce tend to take more time to investigate/solve, so please have patience with this issue. Thank you.

**Comment by torkelo** [comment] 2020-10-30 07:10
Think @marcusolsson opened an issue reporting the problem of clicking and cursor position

**Comment by jsedy7** [comment] 2020-10-30 07:10
Well, I have a problem with deleting parts in a query editor and I tried reproduce my problem. 

![grafana_issue2](https://user-images.githubusercontent.com/8748774/97670753-3199c400-1a87-11eb-8c4a-905e70dbfa51.gif)

**Comment by NotAFile** [comment] 2020-10-30 09:00
> Hi @NotAFile, hard issues to reproduce tend to take more time to investigate/solve, so please have patience with this issue. Thank you.

Sorry for being confusing, but unlike the other issue, this buggy cursor movement reproduces 100% reliably for me. The deletion one is the one that's hard to reproduce.

**Comment by davkal** [comment] 2020-11-04 09:31
This seems to be a problem with the editor component, mixed with the query run on blur behavior. We'll take a look.

**Comment by davkal** [comment] 2020-11-04 09:35
Related to #26760

**Comment by davkal** [comment] 2020-11-04 09:36
@grafana/grafana-frontend-platform we'll take this.

**Comment by NotAFile** [comment] 2020-11-04 14:04
@davkal oh, didn't see that issue. I'd go further and call them duplicates. The only difference to me seems to be that my steps are a bit more complete, as they include deliberately triggering the drop down.

**Comment by ivanahuckova** [comment] 2020-11-10 09:39
@NotAFile fixes are coming in 7.3.2 https://github.com/grafana/grafana/pull/28622. We are also dedicating more time to investigate all of the issues with query editors and improve overall experience there. I am going to close this specific issue in favour of #26760, so if you have any more issues/information/steps on how to reproduce this, please add it there. We would be grateful! 🙏 

/duplicate of #26760

**Closed** 2020-11-10 10:40 UTC
Labels: area/panel/data, datasource/Prometheus, type/duplicate
