### ISSUE TITLE
feature request: toggle full time range in Grafana explore histogram for loki queries on or off

### ISSUE THREAD

**Issue by rsteneteg** [grafana/grafana#32731] opened 2021-04-06 20:06 UTC
**What would you like to be added**:
When running Loki queries in Grafana Explore the histogram the time range for the graph is adjusted to the start/end time of the 1000 lines that the query is limited to return, regardless if the query was run for longer time range using the time range selector. This makes the graph look less empty, but it also makes it much harder to zoom in on a time that is with the selected time range but beyond the 1000 lines returned. 

It would be nice if there was some button near the graph that could toggle this behavior on or off, so that you could choose to view the entire time range when needing to zoom in.

**Why is this needed**:
This would make it much easier to zoom in on a specific time range using the cursor in the graph instead of needing to manually enter the start/end time in the time range selector

**Comment by zoltanbedi** [comment] 2021-04-07 06:58
Duplicate of #19949

**Closed by zoltanbedi** 2021-04-07 06:58 UTC
