### ISSUE TITLE
6.6.1 and ElasticSearch unable to pull logs

### ISSUE THREAD

**Issue by xFilosofx** [grafana/grafana#21996] opened 2020-02-07 09:23 UTC
**What happened**:Updated to Grafana 6.6.1 today and after a while, the ESi Datasource stopped allowing us to query logs.When i open Explore tab and ES Source, choose Metric, time and click to Run query work only Graph panel. Table stay empty and Run button stop working, not change result if change time. If go to Logs tab and click Run query thats start loading but not finish and lods list stay clear. If i go back to metric Table block show my logs, but Run Button not work again.

**What you expected to happen**: The "Run Query" button should pull in logs from ES.

**How to reproduce it (as minimally and precisely as possible)**: Try to pool log from ES Datasource
**Anything else we need to know?**:

**Environment**: 
- Grafana version:6.6.1
- Data source type & version: ES 6
- OS Grafana is installed on: CentOS Linux release 7.7.1908
- User OS & Browser: Elementary OS, Vivaldi
- Grafana plugins:
- Others:

**Comment by aocenas** [comment] 2020-02-10 16:00
@xFilosofx can you check if this isn't the same issue as here: https://github.com/grafana/grafana/issues/21987 That the disable button is toggled?

**Comment by xFilosofx** [comment] 2020-02-14 17:07
Okay, i check it and get info.

**Comment by xFilosofx** [comment] 2020-02-17 03:39
No, this button is enabled. Loading not finish and logs not display. Only metrics.

**Comment by aocenas** [comment] 2020-02-17 15:51
@xFilosofx can you post the request and response data from the browser network tab?

**Comment by ivanahuckova** [comment] 2020-04-23 15:26
Hi @xFilosofx! I was not able to reproduce this bug. I am going to close the issue for now, but if you experience the problem again and/or if you would have more information for us on how to reproduce the issue, we can definitely open the issue again.  Also, it would be very helpful if you would be able to send us the request and response data from the browser network tab.

**Closed by ivanahuckova** 2020-04-23 15:26 UTC
Labels: area/explore, datasource/Elasticsearch, needs more detail
