### ISSUE TITLE
Maximum call stack size exceeded using getLocationSrv().update()

### ISSUE THREAD

**Issue by polovmak** [grafana/grafana#27328] opened 2020-09-02 09:20 UTC
**What happened**:
When I'm calling getLocationSrv().update() function to update dashboard variables, **Unhandled Promise Rejection: RangeError: Maximum call stack size exceeded.** appears and also query update is cycling
**What you expected to happen**:
When calling this function, it shouldn't go into cycle.

**Environment**:
React plugin for grafana
Grafana version: 7.1.4

**Comment by hugohaggmark** [comment] 2020-09-02 09:33
Duplicate of #26558

**Closed by hugohaggmark** 2020-09-02 09:33 UTC
