### ISSUE TITLE
Alerting: Regex silence rule didn't work (OR: Regex silence rule UI is confusing)

### ISSUE THREAD

**Issue by mkopinsky** [grafana/grafana#37362] opened 2021-07-29 15:12 UTC
**What happened**:
I had two alerts firing last night, called "mysql connections" and "mysql connection errors", and I figured that rather than silencing them individually, I would use a regex to silence both in one stone. I'm not sure whether I did something wrong, or whether the regex silencing didn't work.

Silence definition (copied from `/api/alertmanager/grafana/api/v2/silences`)

```json
[
  {
    "id": "9c61d613-b9fc-45e4-9249-66d45827d273",
    "status": {
      "state": "active"
    },
    "updatedAt": "2021-07-29T14:51:27.290Z",
    "comment": "silencing again to test grafana regex silencing",
    "createdBy": "admin",
    "endsAt": "2021-07-29T16:51:04.322Z",
    "matchers": [
      {
        "isEqual": false,
        "isRegex": true,
        "name": "alertname",
        "value": "mysql.*"
      }
    ],
    "startsAt": "2021-07-29T14:51:27.290Z"
  }
]
```
![image](https://user-images.githubusercontent.com/591435/127515952-c76de922-3fb1-4742-8fea-ef54306ffafc.png)

Alert definition (copied from `/api/alertmanager/grafana/api/v2/alerts?silenced&active&inhibited`)

```json
[
  {
    "annotations": {
      "__dashboardUid__": "oOB1HMinz",
      "__value_string__": "[ metric='{instance=\"mysqld_exporter:9104\", job=\"mysqld\"}' labels={instance=mysqld_exporter:9104, job=mysqld} value=0.9205298013245033 ], [ metric='{instance=\"mysqld_exporter:9104\", job=\"mysqld\"}' labels={instance=mysqld_exporter:9104, job=mysqld} value=12 ]",
      "summary": "MySQL connection usage is at >80% of the limit"
    },
    "endsAt": "2021-07-29T14:53:01.732Z",
    "fingerprint": "920a82ee6dde0d8e",
    "receivers": [
      {
        "name": "TST slack"
      }
    ],
    "startsAt": "2021-07-29T11:53:01.732Z",
    "status": {
      "inhibitedBy": [],
      "silencedBy": [],
      "state": "active"
    },
    "updatedAt": "2021-07-29T14:51:08.409Z",
    "generatorURL": "https://labs.waytohealth.org/grafana-tst/alerting/NieSSIm7z/edit",
    "labels": {
      "__alert_rule_uid__": "NieSSIm7z",
      "alertname": "mysql connections"
    }
  }
]
```

**What you expected to happen**:

I'd expect an alert with regex of `mysql.*` to silence alerts starting with `mysql`.

As I'm typing this, I'm realizing that I probably misread the UI. Does the right hand "Equals" checkbox change the meaning of the rule from "regex matches" to "regex doesn't match"? If so, that is super confusing.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.6 (68fe9e3431)
- Data source type & version: Prometheus (latest)
- OS Grafana is installed on: Alpine (standard docker image)
- User OS & Browser: Chrome 91.0.4472.114 (Official Build) (x86_64), macOS Big Sur
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment] 2021-07-30 12:51
> As I'm typing this, I'm realizing that I probably misread the UI. Does the right hand "Equals" checkbox change the meaning of the rule from "regex matches" to "regex doesn't match"?

It does impact the regex as match or not match.

> If so, that is super confusing.

Agreed, I and others got confused as well. We have an issue open to change it to 4 option select dropdown instead of being the combination of two things: https://github.com/grafana/grafana/issues/35745 , so closing this as a duplicate of that issue.

**Closed** 2021-07-30 12:52 UTC
Labels: area/alerting, needs investigation
