### ISSUE TITLE
8.0.x causing crash on Chromium/Chrome

### ISSUE THREAD

**Issue by sbrooke** [grafana/grafana#36241] opened 2021-06-28 21:54 UTC
Since the update to 8.0.3 I’ve been having crashes (Aw, Snap) on a couple of RPi’s running Chromium in a kiosk mode. I also had one crash on an old iMac that’s only displaying Chrome. The dashboard has not changed, aside from the visual updates that came with 8.x. I’ve searched the interwebs and come across a few others that are having the same problem, mostly with RPis. Please let me know what detail you need from me.

**Comment by leeoniya** [comment] 2021-06-28 22:48
Duplicate of https://github.com/grafana/grafana/issues/35987

**Closed by leeoniya** 2021-06-28 22:48 UTC
