### ISSUE TITLE
improvements - use format=completer in query to graphite datasource

### ISSUE THREAD

**Issue by unix196** [grafana/grafana#12070] opened 2018-05-25 13:08 UTC
##### Grafana v4.6.3, datasourcer - Graphite. Debian GNU/Linux 8.6 (jessie)
A wrote my question on [filter enhancement](https://github.com/grafana/grafana/issues/439), but no one response(.
Duplicate question:
For example, I have graphite database (go-carbon) as datasource for grafana and graphite API (carbonapi), do some query to API:
```
1) curl -s  "http://localhost:7081/metrics/find?query=stats.*.mysql" | json_pp      

[
   {
      "id" : "stats.*.mysql",
      "allowChildren" : 1,
      "leaf" : 0,
      "expandable" : 1,
      "context" : {},
      "text" : "mysql"
   }
]
```
Add flag format=completer [(graphite API)](https://graphite-api.readthedocs.io/en/latest/api.html#the-metrics-api) 
```
2) 
curl -s  "http://localhost:7081/metrics/find?format=completer&query=stats.*.mysql" | json_pp
...
      {
         "is_leaf" : "0",
         "path" : "stats.server1.mysql",
         "name" : "mysql"
      },
      {
         "is_leaf" : "0",
         "path" : "stats.server2.mysql",
         "name" : "mysql"
      },
      {
         "name" : "mysql",
         "path" : "stats.server3.mysql",
         "is_leaf" : "0"
      }
   ]
}

```
If I create variable in grafana with query: `stats.*.mysql` it return value `mysql` (i.e. use first variant of curl query). Is it possible receive value path?
Why it is may necessary: we have about hundread servers and they not all have mysql (apache, logstash and so on) service and I may dont know/remember on which server there is right service.

### What  the expected result?
I create variable $servers with this new query and receive all servers that have specified service. Then, for example, I may use this variable $server for create new variables.

**Comment by xlson** [comment] 2018-05-28 11:59
There's, unfortunately, no way to do this right now.

Duplicate of  #2343

**Closed by xlson** 2018-05-28 11:59 UTC
