### ISSUE TITLE
Template variables for Elasticsearch add option to disable time range filter

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#13880] opened 2018-10-29 13:26 UTC
Please include this information:
# What Grafana version are you using? 
- `Version 5.3.0-pre1 (commit: 0f6e5e2)`
# What datasource are you using?
- `Elasticsearch 6.4`
# What OS are you running Grafana on?
- `Ubuntu 18.04 LTS`
# What did you do? 
- `trying to create template variable using custom Lucene query, but it seems like current data range selected in the UI is added to the query, so I cannot find data which is needed for this variable. Why adding the date range to the query in such a way that we cannot remove it?`
# What was the expected result?
- `filter query that runs on Elasticsearch should be exactly the same as I put it into the "Lucene query" text field`
# What happened instead?
- `I see that Grafana added time range from the UI`

Is there any way to tell Grafana not to do this?

**Comment by torkelo** [comment] 2018-10-29 14:00
yes, this works the same for all TSDB data sources. With no date range Frafana does not know which Elasticsearch index to target (if you have date named indices). 

With supporting ES for 3 years this is the first time this has been raised, which is why an option to disable it has not been added.

**Comment by lukaszgryglicki** [comment] 2018-10-29 15:06
OK, so rather no chance to skip this when for example Lucene query is filled in?

**Comment by torkelo** [comment] 2018-10-29 15:17
That would break millions of dashboards so would have to be an option so would have to be an option, and it would only work for non time/date named indices

**Comment by lukaszgryglicki** [comment] 2018-10-29 15:23
yes, sure, thanks for the info.

**Comment by aocenas** [comment] 2020-08-26 08:29
Hey @lukaszgryglicki I am closing this as it seems like this works as intended for most people and there wasn't any more requests for doing something like this.

**Closed by aocenas** 2020-08-26 08:29 UTC
Labels: area/datasource, datasource/Elasticsearch, type/feature-request, type/works-as-intended
