### ISSUE TITLE
Alerting: Elasticsearch support

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5893] opened 2016-08-24 10:22 UTC
Port frontend data source code to backend & Go. Includes building ES query from internal query model, and parsing ES response into time series. 

Grafana internal query model example: 

```
Elastic query json model: 
{
  "bucketAggs": [
    {
      "field": "@timestamp",
      "id": "2",
      "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "trimEdges": 0
      },
      "type": "date_histogram"
    }
  ],
  "dsType": "elasticsearch",
  "metrics": [
    {
      "field": "@value",
      "id": "1",
      "meta": {},
      "settings": {},
      "type": "avg"
    }
  ],
  "refId": "A",
  "target": "",
  "timeField": "@timestamp"
}
```

**Comment by bergquist** [comment] 2016-10-04 13:14
ref https://github.com/grafana/grafana/issues/5858

**Comment by luigiberrettini** [comment] 2016-10-05 07:36
Since #5948 is merged is this issue closed?

**Comment by bergquist** [comment] 2016-10-05 07:51
@luigiberrettini its not merged to master just to the alerting-elasticsearch branch. It far from completed yet.

**Comment by DEvil0000** [comment] 2016-10-06 15:49
not more far then graphite support ;)
missing graphite query features in alerting:
* template variables
* functions referencing other queries (e.g. asPercent)

**Comment by ictcorebiz** [comment] 2016-10-12 11:55
Hi, will complete elasticsearch support come after the 4.0.0 deliverable (planned for November), because I see this issue marked with the 4.1.0 milestone?
If so: when is 4.1.0 planned for delivery?

**Comment by torkelo** [comment] 2016-10-12 12:02
4.1 does not have a release date yet, but would get January / early feb. 

Elasticsearch alerting might not make it into Grafana v4, we tried (the work is started), but requires a lot more work to complete and some more high prio issues has pushed it out of v4

**Comment by ictcorebiz** [comment] 2016-10-12 13:37
In that case, would it be possible to enable/disable the alert-menu items and panel-tabs based on an Organization preference (or even better: on individual user level definitions within the organization)?

**Comment by warroyo** [comment] 2016-12-07 16:34
Has there been any progress on this? Is the `elasticsearch-alerting` branch still active? I am wondering if there is something that I could start testing and giving feedback on.

**Comment by xamox** [comment] 2017-01-13 04:17
Looking forward to this getting into 4.2 so we can fully move to grafana + elasticsearch (metricbeats).

**Comment by andytsnowden** [comment] 2017-01-13 05:42
Having this functionality would be a huge win for my company

**Comment by torkelo** [comment] 2017-01-13 06:29
@andytsnowden enough to buy a support plan? https://grafana.net/support/plans :stuck_out_tongue_winking_eye: 

We hope get a chance to continue work on this soon.

**Comment by gbrian** [comment] 2017-01-25 08:36
Maybe silly (please don't answer "yes, you are") but what about kind of **feature-crowdfunding** ? sure many will support

**Comment by wirecutter313** [comment] 2017-01-30 19:56
This was the whole reason I downloaded this tool, in hopes of having alerting for elastic.

**Comment by DEvil0000** [comment] 2017-01-30 21:57
There is a branch which was at least working for most queries. But it is a bit outdated - you would need to align some things.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: wirecutter313 <notifications@github.com> 
Datum: 30.01.2017  20:56  (GMT+01:00) 
An: grafana/grafana <grafana@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Manual <manual@noreply.github.com> 
Betreff: Re: [grafana/grafana] Alerting: Elasticsearch support (#5893) 

This was the whole reason I downloaded this tool, in hopes of having alerting for elastic.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/grafana/grafana","title":"grafana/grafana","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/grafana/grafana"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wirecutter313 in #5893: This was the whole reason I downloaded this tool, in hopes of having alerting for elastic. "}],"action":{"name":"View Issue","url":"https://github.com/grafana/grafana/issues/5893#issuecomment-276172036"}}}

**Comment by yannispanousis** [comment] 2017-02-02 14:54
Is there a strong chance this is going to make the 4.2.0 mark?

**Comment by torkelo** [comment] 2017-02-02 15:24
its not looking like that. No one is working on it that we know and we have a lot on our plate right now.

**Comment by yannispanousis** [comment] 2017-02-02 15:30
That's pretty unfortunate! Considering using Graphite as a backend, until we can support ES. But trying to understand what limitations that in terms of the queries (and thus alerts) and such, as opposed to ES

**Comment by Alexander-Payne** [comment] 2017-02-22 14:47
Is anyone aware of any way of getting some kind of alerting into Grafana whilst having ES as a data source? Or for anyone who also uses Kibana to visualise data before Grafana are you aware of any solutions to have alerting on this side of things?

**Comment by torkelo** [comment] 2017-02-22 15:20
we are working on it in this branch, https://github.com/grafana/grafana/tree/alerting-elasticsearch

**Comment by DEvil0000** [comment] 2017-02-22 21:45
Check out the experimental branch. You might need to align some things to get it working again.

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Alexander Payne <notifications@github.com> 
Datum: 22.02.2017  15:48  (GMT+01:00) 
An: grafana/grafana <grafana@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Manual <manual@noreply.github.com> 
Betreff: Re: [grafana/grafana] Alerting: Elasticsearch support (#5893) 

Is anyone aware of any way of getting some kind of alerting into Grafana whilst having ES as a data source? Or for anyone who also uses Kibana to visualise data before Grafana are you aware of any solutions to have alerting on this side of things?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/grafana/grafana","title":"grafana/grafana","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/grafana/grafana"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Alexander-Payne in #5893: Is anyone aware of any way of getting some kind of alerting into Grafana whilst having ES as a data source? Or for anyone who also uses Kibana to visualise data before Grafana are you aware of any solutions to have alerting on this side of things?"}],"action":{"name":"View Issue","url":"https://github.com/grafana/grafana/issues/5893#issuecomment-281689640"}}}

**Comment by mwjackson** [comment] 2017-02-28 12:59
What's a rough estimate of how far you are along with this? 50%? 90%?

**Comment by j-datadome** [comment] 2017-03-01 17:31
Hello
We are very interested about this feature. 
Is there a release date?

Thanks

**Comment by pachico** [comment] 2017-03-10 13:07
Thumbs up for this feature and good work!

**Comment by ma-sir** [comment] 2017-03-14 11:28
Thumbs up for this feature and good work!

**Comment by playqdrew** [comment] 2017-03-15 18:26
Thank you guys for the work on this one. Will be huge when it's ready!

**Comment by anhlqn** [comment] 2017-03-15 20:18
Was super happy to upgrade Grafana to 4.1.2 just to realize that ES data source is not supported :(. I guess I have to stick with Powershell script for alerting for now.

**Comment by danisabad** [comment] 2017-03-15 20:29
Guys, it will be nice to have Elastic alerting in Grafana - that is the fact. But obviously it will not happen faster if every one will leave exactly the same comment here ;)
And obviously alert rules will be quite unsophisticated, at least at first, as they are now for metrics. Most likely simple threshholds. 
If you NEED alerting for ElasticSearch - use ElastAlert. It's there for long time, support all Elastic versions and quite complex rules.

**Comment by anhlqn** [comment] 2017-03-15 21:31
Unfortunately, ElastAlert does not support aggregation, `The only aggregation supported currently is a terms aggregation, by setting use_terms_query.` But I'm glad that Alert finally comes to Grafana.

**Comment by bharathrajbk** [comment] 2017-03-17 02:02
Hi, can I know when this would be completed please? I am eagerly looking forward to alerting from elasticsearch in grafana

**Comment by pdf** [comment] 2017-03-17 03:11
People, **please stop spamming this issue with pointless comments**.  It will be done when it's done.  If you want to contribute, by all means submit a PR with an implementation.

If you wish to show your support for the issue, use the reaction button on the first post.  If you wish to receive an update when the issue is completed, the subscribe button is on the right.

Making a useless comment spams _every_ subscriber on the issue, and won't cause it to be resolved any faster, so please stop (apologies for my contribution the noise here everyone!).

**Comment by kerlos** [comment] 2017-04-20 20:33
I got "tsdb.HandleRequest() error type assertion to string failed" on alerting-elasticsearch branch 
(Same problem as #7909)
Grafana v4.2.0-pre1
Datasource : Elasticsearch version 2.x

json from query
```
{
    "search_type": "count",
    "ignore_unavailable": true,
    "index": "moa-log-alias"
}
{
    "size": 0,
    "query": {
        "bool": {
            "filter": [
                {
                    "range": {
                        "@timestamp": {
                            "gte": "1492718034259",
                            "lte": "1492719834259",
                            "format": "epoch_millis"
                        }
                    }
                },
                {
                    "query_string": {
                        "analyze_wildcard": true,
                        "query": "type:\"oauth2_request_log\""
                    }
                }
            ]
        }
    },
    "aggs": {
        "3": {
            "terms": {
                "field": "method",
                "size": 500,
                "order": {
                    "_term": "desc"
                },
                "min_doc_count": 0
            },
            "aggs": {
                "2": {
                    "date_histogram": {
                        "interval": "1m",
                        "field": "@timestamp",
                        "min_doc_count": 0,
                        "extended_bounds": {
                            "min": "1492718034259",
                            "max": "1492719834259"
                        },
                        "format": "epoch_millis"
                    },
                    "aggs": {}
                }
            }
        }
    }
}
```

**Comment by Madhu1512** [comment] 2017-05-04 03:21
we are also started testing elasticsearch alerting using alerting-elasticsearch branch and we see same issue what @kerlos  is seeing.

Grafana v4.2.0
Datasource : Elasticsearch 5.x 

from logs:

EROR[05-03|23:12:01] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=1 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting
EROR[05-03|23:13:01] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=1 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting
EROR[05-03|23:14:01] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=1 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting
EROR[05-03|23:15:00] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=0 name=Test error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting
EROR[05-03|23:15:01] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=1 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting
EROR[05-03|23:16:01] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=1 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting
EROR[05-03|23:17:01] Alert Rule Result Error                  logger=alerting.evalHandler ruleId=1 name="Panel Title alert" error="tsdb.HandleRequest() error type assertion to string failed" changing state to=alerting


<img width="1244" alt="screen shot 2017-05-03 at 11 15 06 pm" src="https://cloud.githubusercontent.com/assets/9481189/25689509/b78c0024-3056-11e7-8f81-92850ee17e47.png">

**Comment by eueuy** [comment] 2017-05-10 10:56
@torkelo @kerlos @Madhu1512 
so....  whats going on?  :)

**Comment by Nodens2k** [comment] 2017-05-30 10:15
Hi there,

Just two questions:

* I see that the last commit in the alerting-elasticsearch branch is from Feb 2017. Is it already mature enough to fit into 4.4.0? 
* Does this alerting module require X-Pack on the elasticsearch server? If that's the case, I would like to propose another candidate for the list of supported alert datasources: [elastalert](http://elastalert.readthedocs.io/en/latest/elastalert.html).

**Comment by torkelo** [comment] 2017-05-30 11:09
- It's not mature I think (have not tested it much). 
- X-Pack is not required.

**Comment by arjun9916** [comment] 2017-06-25 07:11
Are we getting any closer for this?

**Comment by ebirukov** [comment] 2017-06-26 13:00
We are waiting for this figure for several months. When released?

**Comment by michaeleino** [comment] 2017-07-09 11:55
How could I patch this to grafana_4.3.2 ??  it is really important & useful

**Comment by ldktta** [comment] 2017-07-14 18:05
Please do not discard this feature.

**Comment by arjun9916** [comment] 2017-07-18 14:49
We are desperately waiting for this feature..

**Comment by lvheyang** [comment] 2017-07-26 13:43
https://github.com/grafana/grafana/pull/8934 this is my edition about this issue. hope to be helpful

**Comment by GedPL** [comment] 2017-09-08 08:49
Could it be merged to one of nearest releases ?

**Comment by caneraydinbey** [comment] 2017-10-11 11:04
Elastic is still not supported? @torkelo

**Comment by ahirri** [comment] 2017-10-12 14:23
Should we expect to have this released soon?

**Comment by caneraydinbey** [comment] 2017-10-12 16:44
Why no answer @playqdrew

**Comment by nukede** [comment] 2017-10-13 18:07
Please include the feature to the nearest release. It would be really cool!

**Comment by dustinvanbuskirk** [comment] 2017-10-17 23:39
@lvheyang I've pulled your changes locally and it appears the Alerting is not respecting the Size set in the Metric Query.  I've set the Size to no limit but the alerting only evaluates 10 objects and the 10 evaluated seem to be random as I've set order to Bottom on my query showing the lowest values on top of my legend but none of those bottom values are evaluated.  Maybe, this is a limitation or I'm doing something incorrectly?  What do you think?

**Comment by leehambley** [comment] 2017-10-19 15:36
@dustinvanbuskirk I'd be glad to help you figuring this out. Maybe if the work was _largely_ done we can just finish

**Comment by GedPL** [comment] 2017-11-15 09:00
Hi guys,
Any updates on this ? Waiting for this functionality for over year ....

**Comment by torkelo** [comment] 2017-11-15 10:23
Really sorry that this always ends up being pushed, a bit overwhelmed by other issues & making progress on Grafana v5 (new grid, user groups & dashboard folders). Can't promise when we can get this in, hopefully in v5.1 (early Q1 2018)

**Comment by GedPL** [comment] 2017-11-15 14:44
Hoping to have it soon. Fingers crossed !

**Comment by nbarrientos** [comment] 2017-12-01 10:10
We'd benefit from this too :)

**Comment by tibbing** [comment] 2017-12-01 22:35
+1 Also missing this feature

**Comment by Shiinii** [comment] 2018-01-08 15:14
Hey @torkelo,
I'm just curious if you made any progress in elasticsearch alerting ? :)

KR

**Comment by vijaychd** [comment] 2018-02-01 20:37
+1

**Comment by yossiv** [comment] 2018-02-11 17:08
Q1 almost end.. 
so waiting for this Elastic alerting to be ready

**Comment by MichaelLogutov** [comment] 2018-02-11 17:35
I'm curious - do ELK "watcher" feature that can do elastic alerting which is also one of the main feature in **payed** X-Pack have something to do with stalling the progress on this feature?

**Comment by hemebond** [comment] 2018-02-11 23:24
@yossiv @MichaelLogutov @vijaychd @Shiinii  https://www.bountysource.com/

**Comment by guohailong2006** [comment] 2018-02-24 02:25
i still wait for the "alert  feature for es".  it is import for me .but i can't see some more advance  about this issue

**Comment by dannyz29** [comment] 2018-02-28 14:53
+ 1 would be very useful

**Comment by calston** [comment] 2018-03-01 12:20
I'd still trade all these newfangled dashboard rearrangements for this

**Comment by kallasramon** [comment] 2018-03-06 10:26
I would also love to see ES alerting on Grafana.

**Comment by vijaychd** [comment] 2018-03-08 22:52
Any timeline when it will be ready ?

**Comment by HeWhoWas** [comment] 2018-03-12 22:36
I wouldn't be waiting for this functionality, given that the ticket has been open for 18 months and there appears to be no developers working on it for over a year. If you need alerting, I'd suggest you look at migrating to a backend that supports it.

**Comment by elboletaire** [comment] 2018-03-13 09:57
So... making likes to issues is totally useless? This is the third issue sorted by votes... it's disappointing to see it ignored.

![imatge](https://user-images.githubusercontent.com/153305/37334853-58db1d82-26ad-11e8-8359-d0e4839ef831.png)

**Comment by calston** [comment] 2018-03-13 09:59
> I'd suggest you look at migrating to a backend that supports it.

@HeWhoWas I would but they're all terrible.

**Comment by tibbing** [comment] 2018-03-13 10:06
We created our own alerting solution in a durable azure function instead, continuously polling the logs.

**Comment by rhefner1** [comment] 2018-03-13 10:32
^ right, for basic use cases this definitely isn't rocket science. Just go to Kibana and run your query, then copy the raw Elasticsearch query that it generates. Then run some code like this (incomplete, but you get the idea):

```bash
# Get results from ES
result=$(
    curl -sS -X POST \
    "http://${ES_HOST}:9200/logstash-*/_search" \
    -H "cache-control: no-cache" \
    -H "content-type: application/json" \
    -d @/app/es_query.json
)
count=$(echo ${result} | jq -r '.hits.total')
echo "[DEBUG] Found ${count} hits"

# Send alert if necessary
if [ "${count}" -ge "${COUNT_THRESHOLD}" ]; then
    echo "[INFO] Found ${count} hits on search, which is over the threshold"

    alert_text="{\"text\": \"[${APP_NAME}] Found ${count} *${ALERT_TEXT}* events in the last ${REPORTING_PERIOD}. See ${INSPECT_LINK} .\"}"
    echo ${alert_text} | curl "${SLACK_HOOK_URL}" -d @-
fi
```

**Comment by calston** [comment] 2018-03-13 10:35
Yeah or just use x-pack monitoring, or pass them through Riemann and alert that way. 

Alerting isn't the issue, having the neat Grafana functionality of visualisation and tweaking it is the desire. 

All your solutions above are basically "forget grafana" - well this is the grafana project, and this issue is here to improve it. So lets focus on solutions that do that.

**Comment by leehambley** [comment] 2018-03-13 10:43
This PR is huge, and partly because it includes an entire 3rd party ElasticSearch library, and support for ES 2.x and 5.x series.

If someone would take the time to simplify this PR drastically it could be reduced from ~5k lines of code to possibly 800-1000 tops, which would make it much more feasible to include.

As far as I've gathered this branch basically works, but there's a missing aggregate function that prevents certain kinds of queries working.

Does someone volunteer to get the branch simplified and prepare it, and champion it towards being merged?

**Comment by calston** [comment] 2018-03-13 10:45
Not sure why it would need a 3rd party library to send JSON to an HTTP/S service. 

ES 2.x should just be discarded, no one should be running it anymore (I know lots of people are. Stop it!)

**Comment by MKGrizzly71** [comment] 2018-03-14 13:08
Is there a possible work around to ES alerts in Grafana?

Thanks.

**Comment by sybrandy** [comment] 2018-03-14 13:14
What I did to workaround this was to stand up a stand-alone InfluxDB instance and have anything that I wanted to alert on go there instead of ES.  It's not too bad as InfluxDB isn't much of a resource hog and since you don't need all of your data in there, you can keep data usage low by not keeping a lot of historical data and only ingest the required data that you need into it.

**Comment by elvarb** [comment] 2018-03-15 22:45
That's a solid workaround

I have experimented with this in the past, I took all logs from a small windows environment that were already going to elasticsearch and sent them to telegraf, then to influxdb. This worked amazingly well because fields in the event log became fields in influxdb, so in grafana I could query for event ids, hostnames and usernames for example.

The best part about this is that the disk space this all took was tiny, I mean really tiny. Trying to remember from memory but it was something like 500mb a day in elasticsearch, this became less than 300mb in influxdb... For data covering over 6 months.

This was just an experiment, never thought about solving the alerting problem with this. 

I encourage everyone to try this out.

**Comment by harshvladha** [comment] 2018-03-21 07:47
Can I contribute by developing Alerting for ElasticSearch >=5.0 ? I will need some guidance from the community, as in how to proceed, if this change won't get merged in this repository, I can have the code in another repo which can be used while building grafana from source-code.

I see that ElasticSearch API is now stable across major version (ES.5, ES.6)

Any suggestions? I will be starting to work on it from this weekend.

**Comment by nikskiz** [comment] 2018-03-24 11:54
Spent all this time trying to move away from logz.io (expensive) to Grafana for the company I work for...to only find out I can not setup alerting.

I need to have an ETA? I am working on a project which requires this feature.

**Comment by mizalewski** [comment] 2018-03-24 13:38
@nikskiz Grafana is open source project, and everyone can contribute to it. Also you can contribute!

Many people work on open source projects for free in their free time, and I think it is not ok to be rude and criticize their work.

**Comment by javasoze** [comment] 2018-03-24 14:44
There is a smaller PR in progress: https://github.com/WPH95/grafana/pull/2 by @WPH95

**Comment by 4ndv** [comment] 2018-03-24 15:14
@nikskiz right now you can use influxdb

**Comment by kvalev** [comment] 2018-03-24 18:10
@nikskiz or you can simply use elastalert

**Comment by lucasrodcosta** [comment] 2018-03-25 00:39
Hi everyone!

We all know that alerting for Elasticsearch is an amazing, very-welcome and long-waited feature.  
But I think we should keep this thread as clean and organized as possible.

So, questions and comments like these...

> Any timeline?
> It would be very usefull!
> Can't wait for it!
> Has there been any progress on this?

doesn't help in evolution of the feature, generates a lot of useless emails to people who subscribed to the thread and makes the discussion too much confusing to new participants.

Even questions about workaround and other alerting solutions (like ElastAlert) shouldn't been posted here anymore, as it has already discussed a lot in previous comments.

So, please, **stop trivializing this space**! Let's use them to spread useful comments and to share the progress you've made on this feature.

**Comment by WPH95** [comment] 2018-03-26 12:15
I just finished a PR #11380 to make grafana support Alerting [Elasticsearch]

Compared to some early implementations e.g.  #8943 , #10343

- base on grafana-5.0.0
- source code less than 1000 lines
- Code logic is consistent with the front

this week i will continue to improve this PR, more comprehensive test, clearer abstract model.
I'm looking forward to someone who can try to use this PR and improve it :)

**Comment by harshvladha** [comment] 2018-03-27 15:38
@WPH95 - I will be trying your PR this week for sure, will create issue in your repo, if that's ok with you, and look into contributing there.

**Comment by Guchman** [comment] 2018-04-26 10:45
Merge that already please. Thats a hot feature.

**Comment by yossiv** [comment] 2018-04-27 06:41
anything we can help in order to promote this ?

**Comment by jockjiang** [comment] 2018-05-03 17:40
+1, What is the estimation to merge it?  5.2.x?

**Comment by yossiv** [comment] 2018-05-12 08:03
Hi i know we pushing you too much on this , but this issue was open almost 2 years ago (Aug2016) .
elasticsearch + Grafana commutiy is wide and big like others i guess.
i really appreciate the great job this community doing for us, but seems like this issue stayed behind :(
is there anything we can do in order to promote this?

**Comment by demetriusnunes** [comment] 2018-05-15 22:31
Why is it taking so long to merge the PR?

**Comment by futurpc** [comment] 2018-05-18 16:34
+1

**Comment by petrochen** [comment] 2018-05-19 07:17
+1

**Comment by guohailong2006** [comment] 2018-05-22 03:29
+1

**Comment by Trainxy** [comment] 2018-05-29 05:53
+1

**Closed** 2018-06-01 13:17 UTC
Labels: comp: alerting, datasource: Elasticsearch

**Comment by ldktta** [comment] 2018-06-04 01:10
:tada: :tada: :tada: :sparkling_heart:

**Comment by mvlach** [comment] 2018-06-04 08:43
🎉

**Comment by xamox** [comment] 2018-06-04 13:48
Wow, it happened. I honestly thought this was going to go the way of duke nukem.  :+1:

**Comment by dev-e** [comment] 2018-06-28 10:40
Thanks a lot for your efforts!
