### ISSUE TITLE
Cannot use $timeFilter in "On Time Range Change" variables

### ISSUE THREAD

**Issue by LionelCons** [grafana/grafana#12475] opened 2018-07-02 06:20 UTC
When using a variable that depends on time ranges ("Refresh" set to "On Time Range Change"), the `$timeFilter` variable should be available.

Currently, when using it, we get:
```
Template variables could not be initialized: error parsing query: missing parameter: timeFilter
```

**Comment by torkelo** [comment] 2018-07-02 07:11
duplicate of https://github.com/grafana/grafana/issues/7918  (related to same root issue)

**Closed by torkelo** 2018-07-02 07:11 UTC
