### ISSUE TITLE
External snapshots don't delete on the external snapshot grafana instance

### ISSUE THREAD

**Issue by Sadzeih** [grafana/grafana#44009] opened 2022-01-13 15:52 UTC
**What happened**:
When you use an external snapshot instance, and delete a snapshot (from the normal grafana instance), the snapshot (on the external instance) is not deleted.

**What you expected to happen**:
The snapshot should be delete on both the local instance and the external instance.

**How to reproduce it (as minimally and precisely as possible)**:
Have 2 grafana instances, set up external snapshots, create dashboard, snapshot dashboard, view on external, delete from local, view on external again (is still there)

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.3.3
- Data source type & version: Grafana test datasource (with random timeseries)
- OS Grafana is installed on: Docker container / k8s
- User OS & Browser: Firefox/Chrome
- Grafana plugins: None
- Others:

**Comment by axelavargas** [comment] 2022-02-16 13:06
Hey @Sadzeih, thank you for taking the time and reporting this issue, we finally had the time to investigate it 😄.

Unfortunately, we were not able to reproduce it,

- We created the 2 instances (local and external using docker) -> we used the latest grafana version in both of them
- Created a dashboard
- Publish on the external instance the snapshot of the created dashboard
- Then proceeded to delete the snapshot (local) via Dashboards -> snapshots 
- After that, we verify that the external snapshot was deleted

🤔 I am thinking that maybe is something related to cache, sometimes it can take an hour before it's cleared from any CDN caches.

So to continue the investigation, can you verify that is not a cache problem?

**Comment by Sadzeih** [comment] 2022-02-25 10:19
Hi @axelavargas,

I tested a bit more, and it turns out that the issue comes from the fact that one of our Grafana is behind a OAuth 2 proxy. So the request from Grafana to the external instance fails.

Without the authentication limitations it seems to work great!

**Comment by axelavargas** [comment] 2022-02-28 16:36
Thank you for the great investigation @Sadzeih 🙌🏾 , 

> I tested a bit more, and it turns out that the issue comes from the fact that one of our Grafana is behind a OAuth 2 proxy. So the request from Grafana to the external instance fails.

🤔 It seems that this behavior is expected when we are using the interface. I checked in the [API](https://grafana.com/docs/grafana/latest/http_api/snapshot/#delete-snapshot-by-deletekey) and found that there is an alternative to delete an external snapshot without authentication using a secret `deleteKey`, but this is only possible using the API.

For now, I'll close this issue, I'm glad you found a solution 😄.
Thanks!

**Closed by axelavargas** 2022-02-28 16:36 UTC
Labels: needs more info, area/dashboard/snapshot
