### ISSUE TITLE
8.1.0 - Old Alerting annotations are not working

### ISSUE THREAD

**Issue by Vimao** [grafana/grafana#37640] opened 2021-08-06 12:58 UTC
**What happened**:

After upgrading to 8.1.0 all alerting annotations are being rendered as a single color (no no data/alerting/ok separation) and without the text details with explanation

![image](https://user-images.githubusercontent.com/47415312/128513687-a8ea106a-3114-4dcc-84dd-3620940c846b.png)

![image](https://user-images.githubusercontent.com/47415312/128513784-cf6a1eb7-c68a-443d-85ed-f01422df50d1.png)

![image](https://user-images.githubusercontent.com/47415312/128513823-e61e7689-bca9-4621-9a72-8993ac91b4e9.png)

**What you expected to happen**:

I expected old alerting annotations to render as they did in the previous version

**How to reproduce it (as minimally and precisely as possible)**: Trigger any alert after upgrade to 8.1.0

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: Elasticsearch and InfluxDB
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu, Firefox
- Grafana plugins: None
- Others:

**Comment by salavessa** [comment] 2021-08-06 16:04
I'm also experiencing this behavior which if it's intentional it's not great as it removes a lot of visibility on the previous RAG model both in the dashboard and in the alerts (e.g. email).
It's probably also worth mentioning that the annotations generated by an alert are being rendered for every single panel in the dashboard, and not only for the one which triggered the alert.

**Comment by gorkem2020** [comment] 2021-08-09 05:58
yeah I'm also experiencing this. I had to go back to 8.0.6 because of this.

**Comment by kylebrandt** [comment] 2021-08-09 13:53
Closing as a duplicate of https://github.com/grafana/grafana/issues/37304 , This has a PR open to fix this associated with that issue so hopefully should be fixed in a one of the 8.1.x releases.

**Closed by kylebrandt** 2021-08-09 13:53 UTC
Labels: area/unified-alerting
