### ISSUE TITLE
[Feature request] Alerting: Conditions to compare metrics

### ISSUE THREAD

**Issue by elvarb** [grafana/grafana#6637] opened 2016-11-18 15:53 UTC
In the alert part in Grafana you can define multiple conditions for the alert.

You can only say if this metric is above a static value and another metric is above a static value.

The possiblity to say if a metric is above another metric or below.

**Comment by bergquist** [comment] 2016-11-18 15:56
Grafana does not support this yet. 

We will add support for this in the future.

**Comment by elvarb** [comment] 2016-11-18 22:34
Thanks, another idea 

Instead of just having one metric compared to another metric, instead add the option to do math functions on them also. 

Trying to think of a solid use case for that option and not finding a solid one yet. Just feel that math functions would be really flexible.

**Comment by blak3r2** [comment] 2016-12-08 10:56
A common use case I would have is... 

QRYA = now
QRYB = timeshifted -7d

IF QRYA is below QRYB * 0.80%, then alert.

In otherwords, just some additional cushion.  I realize this could be handled with a diffSeries or some other graphite function but if a user needs to make a bunch of these it'd be faster and more user friendly to adjust threshold percents on the alerting screen rather than making a new metric for doing the math.

**Comment by proggfreak** [comment] 2017-03-24 14:35
+1
please realize that and don't delay that from one planned Version to the next one anymore  ;-)

**Comment by Danny-UKDM** [comment] 2017-06-05 13:34
+1
I have come across the need for this currently. 

We have a dataSeries which I have added a Moving Average to. I have then applied the standard deviation of the dataSeries both above and below the moving average to create an "area of standard deviation". 

What I'd like to be able to do here is use the upper and lower deviations of my moving average to alert if any raw data points fall outside of that area of standard deviation.

The idea here was to create a dynamic alerting threshold, as using a static value does not suit the hourly trending dataSeries I'm working with. This way, gradually inclining or declining data points are considered normal, and large spikes or drops in data are still caught (due to raw data points falling outside of the area of deviation to the moving average)

Alas, everything is set up and ready to go, but I can only alert based on a static number :( 

Alerting based on a query or a function (or both) would be absolutely perfect!

**Comment by d-shi** [comment] 2017-08-23 17:26
+1

**Comment by dripukailas** [comment] 2017-11-27 04:15
+1

**Comment by maxramqvist** [comment] 2017-12-13 15:01
+1

**Comment by Krinkle** [comment] 2018-01-02 18:26
This appears to be a duplicate of https://github.com/grafana/grafana/issues/6593.

**Comment by torkelo** [comment] 2018-01-04 08:38
closing as dupe of #6593

**Closed by torkelo** 2018-01-04 08:38 UTC
Labels: comp: alerting, comp: alerting/evaluation, type: feature request
