### ISSUE TITLE
Grafana 7.5: Cannot reference variable as panel's datasource if variable points to the global default datasource

### ISSUE THREAD

**Issue by chrnola** [grafana/grafana#32173] opened 2021-03-19 18:41 UTC
**What happened**: Edits to a panel's data source do not stick if attempting to use a data source variable who's current value matches the global default data source.

**What you expected to happen**: I expected to be able to reference a data source variable in a panel and have the value stick even if the currently selected value of the data source variable matches the global default data source.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a Prometheus data source to Grafana, make it the global default data source ("Data Source A").
2. Add another Prometheus data source to Grafana, do not make it the global default data source ("Data Source B").
3. Create a new dashboard.
4. Add a new `Datasource` type variable (name=`datasource`) to said dashboard and set the "Data source options -> Type" to `Prometheus`. Update/save the new variable. Observe that the variable is not referenced anywhere, as expected.
5. Set the variable's value on the dashboard to "Data Source A" (the global default).
6. Add a new panel to the dashboard. Observe that the new panel's data source is already populated with the global default as expected: `Data Source A (Default)`.
7. Change the new panel's data source to `${datasource} (Default)`.
8. Back out of the Edit Panel view.
9. Edit the new panel again, observe that the data source has reverted back to `Data Source A`. This is unexpected. It should still be `${datasource}`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.5.0-13916pre (f135d75a22)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: macOS 10.15.7, Firefox 86
- Grafana plugins: Loki, Prometheus, Splunk, SQL Server, InfluxDB
- Others: N/A

**Comment by zoltanbedi** [comment] 2021-03-23 17:42
I couldn't reproduce this problem. Whenever I choose`${datasource} (Default)` it always jumped to the default data source. Is this not the expected behaviour? @hugohaggmark

**Comment by hugohaggmark** [comment] 2021-03-24 05:45
I can reproduce this, as long as you have anything expect `Data Source A` or `default` chosen in the data source variable picker it works as expected. But as soon as you have `Data Source A` or `default` selected in the picker then the data source for the panel reverts to the default. So this is probably a bug.

**Comment by hugohaggmark** [comment] 2021-03-24 06:25
Duplicate of #31815

**Closed by hugohaggmark** 2021-03-24 06:25 UTC
Labels: area/dashboard/templating, area/panel/data, type/bug

**Comment by hugohaggmark** [comment] 2021-03-24 06:26
This issue seems to be a duplicate of #31815 but let me know if I'm wrong here. I think the description and repro steps in this issue is better though :)

**Comment by chrnola** [comment] 2021-03-24 12:44
Yup, it looks like a duplicate. Thanks everyone!
