### ISSUE TITLE
Table panel: can I control order of the columns?

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#14785] opened 2019-01-09 10:51 UTC
/cc @bergquist

**Comment by torkelo** [comment] 2019-01-09 12:20
For most datasources that can return table data (InfluxDB, SQL etc) you control in the order your query returns columns. For other data sources that do not have this capability in the query language we do not have a way to do this currently. 

dupe of https://github.com/grafana/grafana/issues/5082

**Closed by torkelo** 2019-01-09 12:20 UTC
