### ISSUE TITLE
UI Bug, Alert Creation: "Evaluate every:" with non number input blocks the whole page

### ISSUE THREAD

**Issue by micheee** [grafana/grafana#55357] opened 2022-09-19 07:34 UTC
**What happened**:

When I enter anything in the field that does start with a number, the UI immediately displays an error and I can do nothing but reload the page or navigate away otherwise.

![CleanShot 2022-09-19 at 09 32 33](https://user-images.githubusercontent.com/422242/190969679-ca7f5402-34e4-40e3-bc36-ababfcbbfa4b.gif)

**What you expected to happen**:

The UI might only mark the field as invalid instead of blocking the whole page.

**How to reproduce it (as minimally and precisely as possible)**:

Tab or click into the <kbd>Evaluate every </kbd>-input widget and delete the `1` that's there by default, or enter anything that does not start with a number.

**Environment**:
- Grafana version: 9.1.5
- Data source type & version: Prometheus 
- OS Grafana is installed on: Ubuntu, Running in a docker container
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by adrianguyareach** [comment] 2022-09-23 09:20
Also noticed this. looks like its trying to validate the value when the state changes. Maybe validation should be added when the whole alert gets saved.

**Comment by mellieA** [comment] 2022-09-24 01:24
I can only reproduce this on self-managed grafana, it doesn't happen in my cloud instance which makes me think that it could be related to a configuration setting.

My on-prem instance is using the default grafana configuration

**Comment by grobinson-grafana** [comment] 2022-09-30 09:16
Hi! This bug is fixed in 9.2.0-beta1 and will be available in 9.2.0.

**Closed** 2022-10-07 13:01 UTC
Labels: type/bug, area/alerting, area/alerting/evaluation, area/frontend
