### ISSUE TITLE
Variable substitution in DataLinks does not URL encode unsafe characters

### ISSUE THREAD

**Issue by yanscalyr** [grafana/grafana#22183] opened 2020-02-13 19:47 UTC
**What happened**:
When following a DataLink that contains a variable, the variable will be substituted in without being encoded, which can result in [unsafe characters](https://tools.ietf.org/html/rfc1738#page-3) being present in the URL.
Some safe characters will also be backslash escaped automatically which adds additional unsafe characters, and is probably unnecessary in a URL.

Unsafe characters can result in the server rejecting the request.

**What you expected to happen**:
Variable values would be encoded and not backslash escaped in the URL.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a variable with a value containing a backslash `\`
2. Create a datalink that references the above variable (for full effect point it to a server using a recent version of Apache Tomcat, as this is how I ran into this issue)
3. Use the DataLink 

**Anything else we need to know?**:
Depending on where your DataLink is pointing to, some servers encode unsafe values when received, or do not reject the request.

**Environment**:
- Grafana version: v6.5.2
- Data source type & version:
- OS Grafana is installed on: MacOS Catalina Version 10.15.3
- User OS & Browser: MacOS Catalina Version 10.15.3, Chrome
- Grafana plugins:
- Others:

**Comment by sakjur** [comment] 2020-02-14 10:39
This is similar to #22125, so I'm closing this as a duplicate of that. Would be great if you could add a comment there to put emphasis that it's not about more characters than `#` 🙂

**Closed by sakjur** 2020-02-14 10:39 UTC
