### ISSUE TITLE
[Bug] Hipchat alert notification is missing important information.

### ISSUE THREAD

**Issue by Samuel1989** [grafana/grafana#8426] opened 2017-05-19 15:18 UTC
Please include this information:
- What Grafana version are you using?
V4.2.0

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Ubuntu 14.04

- What did you do?
Fire an alert to Hipchat based upon a graph exceeding a particular threshold. 

- What was the expected result?
To see information the the particular metric being alerted on.

- What happened instead?
Only the alerts name and state are included in the alert.

Hi, I am using the Hipchat alert notifier to alert on particular metrics. From the code I can see that the Grafana code is building up a "message" and a "card", the card only includes the alert name and its state, where the message contains more important information such as what metric is being alerted and it's value.

Building up the card using the alert title and state (but no info on the metric value):
```
card := map[string]interface{}{
		"style":       "link",
		"url":         ruleUrl,
		"id":          "1",
		"title":       evalContext.GetNotificationTitle(),
		"description": evalContext.GetNotificationTitle() + " in state " + evalContext.GetStateModel().Text,
		"icon": map[string]interface{}{
			"url": "https://grafana.com/assets/img/fav32.png",
		},
		"date": evalContext.EndTime.Unix(),
	}
```

Building up the message body, finding particular metrics that are alerting and their values:
```
message := evalContext.GetNotificationTitle() + " in state " + evalContext.GetStateModel().Text + "<br><a href=" + ruleUrl + ">Check Dasboard</a>"
	fields := make([]map[string]interface{}, 0)
	message += "<br>"
	for index, evt := range evalContext.EvalMatches {
		message += evt.Metric + " :: " + strconv.FormatFloat(evt.Value.Float64, 'f', -1, 64) + "<br>"
		fields = append(fields, map[string]interface{}{
			"title": evt.Metric,
			"value": evt.Value,
			"short": true,
		})
		if index > maxFieldCount {
			break
		}
	}
```

Both are then wrapped up in some JSON and sent off to Hipchat:
```
body := map[string]interface{}{
		"message":        message,
		"notify":         "true",
		"message_format": "html",
		"color":          color,
		"card":           card,
	}

	hipUrl := fmt.Sprintf("%s/v2/room/%s/notification?auth_token=%s", this.Url, this.RoomId, this.ApiKey)
	data, _ := json.Marshal(&body)
	cmd := &models.SendWebhookSync{Url: hipUrl, Body: string(data)}
```
 
The issue is according to Hipchats documentation only a card or a message are supported, not both. A Card is optional but if included will replace the message body.

https://developer.atlassian.com/hipchat/guide/sending-messages 

> When a card object is rendered in a supported client it is rendered instead of the message body.

I hope I have provided enough information, please let me know if you need some more or some screenshots.

Sam

**Comment by torkelo** [comment] 2017-05-19 18:16
duplicate of https://github.com/grafana/grafana/issues/8030

**Closed by torkelo** 2017-05-19 18:16 UTC
