### ISSUE TITLE
Feature request to have OR operation between Adhoc filters

### ISSUE THREAD

**Issue by rahuls1071** [grafana/grafana#10876] opened 2018-02-12 11:44 UTC
Feature request to have OR operation between Adhoc filters.
Currently when we select different adhoc filters, they are queried using AND operation. It would be really helpful to have option to choose between AND & OR operation for different adhoc filters.

–Rahul

**Comment by bergquist** [comment] 2018-02-15 15:09
Dupe of https://github.com/grafana/grafana/issues/10918

**Closed by bergquist** 2018-02-15 15:09 UTC
Labels: comp: dashboard/templating, type: feature request
