### ISSUE TITLE
Bug running grafana-server.exe on windows

### ISSUE THREAD

**Issue by jdieguezbean** [grafana/grafana#35084] opened 2021-06-02 08:04 UTC
**What happened**:
`t=2021-06-02T10:59:26+0300 lvl=info msg="Starting Grafana" logger=server version=8.1.0-pre commit=5660bb585f branch=main compiled=2021-05-27T13:47:55+0300
t=2021-06-02T10:59:26+0300 lvl=info msg="Config loaded from" logger=settings file=d:/WORKSPACE/CRON_DATA/grafana/conf/defaults.ini
t=2021-06-02T10:59:26+0300 lvl=info msg="Config loaded from" logger=settings file=./conf/defaults.ini
t=2021-06-02T10:59:26+0300 lvl=info msg="Path Home" logger=settings path=d:/WORKSPACE/CRON_DATA/grafana
t=2021-06-02T10:59:26+0300 lvl=info msg="Path Data" logger=settings path=d:\\WORKSPACE\\CRON_DATA\\grafana\\data
t=2021-06-02T10:59:26+0300 lvl=info msg="Path Logs" logger=settings path=d:\\WORKSPACE\\CRON_DATA\\grafana\\data\\log
t=2021-06-02T10:59:26+0300 lvl=info msg="Path Plugins" logger=settings path=d:\\WORKSPACE\\CRON_DATA\\grafana\\data\\plugins
t=2021-06-02T10:59:26+0300 lvl=info msg="Path Provisioning" logger=settings path=d:\\WORKSPACE\\CRON_DATA\\provisioning
t=2021-06-02T10:59:26+0300 lvl=info msg="App mode development" logger=settings
t=2021-06-02T10:59:26+0300 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-06-02T10:59:26+0300 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=d:\\WORKSPACE\\CRON_DATA\\grafana\\data\\grafana.db mode=-rw-rw-rw- expected=-rw-r-----
t=2021-06-02T10:59:26+0300 lvl=info msg="Starting DB migrations" logger=migrator
t=2021-06-02T10:59:26+0300 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=327 duration=1.0585ms
t=2021-06-02T10:59:26+0300 lvl=info msg="Starting plugin search" logger=plugins
t=2021-06-02T10:59:26+0300 lvl=warn msg="Plugin missing module.js" logger=plugins name="Direct Input" warning="Missing module.js, If you loaded this plugin from git, make sure to compile it." path=d:\\WORKSPACE\\CRON_DATA\\grafana\\plugins-bundled\\internal\\input-datasource\\src\\module.js
t=2021-06-02T10:59:26+0300 lvl=info msg="Registering plugin" logger=plugins id=input
t=2021-06-02T10:59:26+0300 lvl=warn msg="Plugin missing module.js" logger=plugins name="Plugin Admin" warning="Missing module.js, If you loaded this plugin from git, make sure to compile it." path=d:\\WORKSPACE\\CRON_DATA\\grafana\\plugins-bundled\\internal\\plugin-admin-app\\src\\module.js
t=2021-06-02T10:59:26+0300 lvl=info msg="Registering plugin" logger=plugins id=grafana-plugin-admin-app
t=2021-06-02T10:59:26+0300 lvl=info msg="Telemetry Gateway initialization" logger=live.push_http
t=2021-06-02T10:59:26+0300 lvl=eror msg="can't read datasource provisioning files from directory" logger=provisioning.datasources path=d:\\WORKSPACE\\CRON_DATA\\provisioning\\datasources error="open d:\\WORKSPACE\\CRON_DATA\\provisioning\\datasources: The system cannot find the path specified."
t=2021-06-02T10:59:26+0300 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=d:\\WORKSPACE\\CRON_DATA\\provisioning\\plugins error="open d:\\WORKSPACE\\CRON_DATA\\provisioning\\plugins: The system cannot find the path specified."
t=2021-06-02T10:59:26+0300 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=d:\\WORKSPACE\\CRON_DATA\\provisioning\\notifiers error="open d:\\WORKSPACE\\CRON_DATA\\provisioning\\notifiers: The system cannot find the path specified."
service init failed: failed to load dashboard cue schema from path {{%!q(*[]embed.file=&[{cue/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/data/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/scuemata/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/ui/  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} {cue/data/gen.cue package grafanaschema

import "github.com/grafana/grafana/cue/scuemata"

Family: scuemata.#Family & {
        lineages: [
                [
                        { // 0.0
                // Unique numeric identifier for the dashboard.
                // TODO must isolate or remove identifiers local to a Grafana instance...?
                id?: number
                // Unique dashboard identifier that can be generated by anyone. string (8-40)
                uid?: string
                // Title of dashboard.
                title?: string
                // Description of dashboard.
                description?: string

                gnetId?: string
                // Tags associated with dashboard.
                tags?: [...string]
                // Theme of dashboard.
                style: *"light" | "dark"
                // Timezone of dashboard,
                timezone?: *"browser" | "utc"
                // Whether a dashboard is editable or not.
                editable: bool | *true
                // 0 for no shared crosshair or tooltip (default).
                // 1 for shared crosshair.
                // 2 for shared crosshair AND shared tooltip.
                graphTooltip: >=0 & <=2 | *0
                // Time range for dashboard, e.g. last 6 hours, last 7 days, etc
                time?: {
                    from: string | *"now-6h"
                    to:   string | *"now"
                }
                // Timepicker metadata.
                timepicker?: {
                    // Whether timepicker is collapsed or not.
                    collapse: bool | *false
                    // Whether timepicker is enabled or not.
                    enable: bool | *true
                    // Whether timepicker is visible or not.
                    hidden: bool | *false
                    // Selectable intervals for auto-refresh.
                    refresh_intervals: [...string] | *["5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d"]
                }
                // Templating.
                templating?: list: [...{...}]
                // Annotations.
                annotations?: list: [...{
                    builtIn: number | *0
                    // Datasource to use for annotation.
                    datasource: string
                    // Whether annotation is enabled.
                    enable?: bool | *true
                    // Whether to hide annotation.
                    hide?: bool | *false
                    // Annotation icon color.
                    iconColor?: string
                    // Name of annotation.
                    name?: string
                    type: string | *"dashboard"
                    // Query for annotation data.
                    rawQuery?: string
                    showIn:   number | *0
                }]
                // Auto-refresh interval.
                refresh?: string
                // Version of the JSON schema, incremented each time a Grafana update brings
                // changes to said schema.
                schemaVersion: number | *25
                // Version of the dashboard, incremented each time the dashboard is updated.
                version?: number
                panels?: [...#Panel]

                // Dashboard panels. Panels are canonically defined inline
                // because they share a version timeline with the dashboard
                // schema; they do not vary independently. We create a separate,
                // synthetic Family to represent them in Go, for ease of generating
                // e.g. JSON Schema.
                #Panel: {
                    ...
                    // The panel plugin type id.
                    type: !=""

                    // Internal - the exact major and minor versions of the panel plugin
                    // schema. Hidden and therefore not a part of the data model, but
                    // expected to be filled with panel plugin schema versions so that it's
                    // possible to figure out which schema version matched on a successful
                    // unification.
                    // _pv: { maj: int, min: int }
                    // The major and minor versions of the panel plugin for this schema.
                    // TODO 2-tuple list instead of struct?
                    panelSchema?: { maj: number, min: number }

                    // Panel title.
                    title?: string
                    // Description.
                    description?: string
                    // Whether to display the panel without a background.
                    transparent: bool | *false
                    // Name of default datasource.
                    datasource?: string
                    // Grid position.
                    gridPos?: {
                        // Panel
                        h: number & >0 | *9
                        // Panel
                        w: number & >0 & <=24 | *12
                        // Panel x
                        x: number & >=0 & <24 | *0
                        // Panel y
                        y: number & >=0 | *0
                        // true if fixed
                        static?: bool
                    }
                    // Panel links.
                    // links?: [..._panelLink]
                    // Name of template variable to repeat for.
                    repeat?: string
                    // Direction to repeat in if 'repeat' is set.
                    // "h" for horizontal, "v" for vertical.
                    repeatDirection: *"h" | "v"
                    // Schema for panel targets is specified by datasource
                    // plugins. We use a placeholder definition, which the Go
                    // schema loader either left open/as-is with the Base
                    // variant of the Dashboard and Panel families, or filled
                    // with types derived from plugins in the Instance variant.
                    // When working directly from CUE, importers can extend this
                    // type directly to achieve the same effect.
                    targets?: [...{...}]

                    // The values depend on panel type
                    options: {...}
                    fieldConfig: {
                        defaults: {
                            ...
                            // The display value for this field.  This supports template variables blank is auto
                            displayName?: string

                            // This can be used by data sources that return and explicit naming structure for values and labels
                            // When this property is configured, this value is used rather than the default naming strategy.
                            displayNameFromDS?: string

                            // Human readable field metadata
                            description?: string

                            // An explict path to the field in the datasource.  When the frame meta includes a path,
                            // This will default to `${frame.meta.path}/${field.name}
                            //
                            // When defined, this value can be used as an identifier within the datasource scope, and
                            // may be used to update the results
                            path?: string

                            // True if data source can write a value to the path.  Auth/authz are supported separately
                            writeable?: bool

                            // True if data source field supports ad-hoc filters
                            filterable?: bool

                            // Numeric Options
                            unit?: string

                            // Significant digits (for display)
                            decimals?: number

                            min?: number
                            max?: number

                            //   // Convert input values into a display string
                            //   mappings?: ValueMapping[];

                            //   // Map numeric values to states
                            //   thresholds?: ThresholdsConfig;

                            //   // Map values to a display color
                            //   color?: FieldColor;

                            //   // Used when reducing field values
                            //   nullValueMode?: NullValueMode;

                            //   // The behavior when clicking on a result
                            links?: [...]

                            // Alternative to empty string
                            noValue?: string

                            // Can always exist. Valid fields within this are
                            // defined by the panel plugin - that's the
                            // PanelFieldConfig that comes from the plugin.
                            custom?: {...}
                        }
                        overrides: [...{
                            matcher: {
                                id: string | *""
                                options?: _
                            }
                            properties: [...{
                                id: string | *""
                                value?: _
                            }]
                        }]
                    }
                }
            }
                ]
        ]
}

#Latest: {
    #Dashboard: Family.latest
    #Panel: Family.latest._Panel
}
 [57 207 245 111 230 118 182 130 211 5 219 149 100 55 21 161]} {cue/scuemata/panel-plugin.cue package scuemata

// Definition of the shape of a panel plugin's schema declarations in its
// schema.cue file.
//
// Note that these keys do not appear directly in any real JSON artifact;
// rather, they are composed into panel structures as they are defined within
// the larger Dashboard schema.
#PanelSchema: {
    // Defines plugin specific options for a panel
    PanelOptions: {...}

    // Define the custom properties that exist within standard field config
    PanelFieldConfig?: {...}

    // Panels may define their own types
    ...
}

// A lineage of panel schema
#PanelLineage: [#PanelSchema, ...#PanelSchema]

// Panel plugin-specific Family
#PanelFamily: {
    lineages: [#PanelLineage, ...#PanelLineage]
    migrations: [...#Migration]
}
 [86 73 13 44 148 38 21 78 11 5 134 84 112 242 142 26]} {cue/scuemata/scuemata.cue package scuemata

// A family is a collection of schemas that specify a single kind of object,
// allowing evolution of the canonical schema for that kind of object over time.
//
// The schemas are organized into a list of Lineages, which are themselves ordered
// lists of schemas where each schema with its predecessor in the lineage.
//
// If it is desired to define a schema with a breaking schema relative to its
// predecessors, a new Lineage must be created, as well as a Migration that defines
// a mapping to the new schema from the latest schema in prior Lineage.
//
// The version number of a schema is not controlled by the schema itself, but by
// its position in the list of lineages - e.g., 0.0 corresponds to the first
// schema in the first lineage.
#Family: {
        lineages: [#Lineage, ...#Lineage]
        migrations: [...#Migration]
        let lseq = lineages[len(lineages)-1]
        latest: #LastSchema & {_p: lseq}
}

// A Lineage is a non-empty list containing an ordered series of schemas that
// all describe a single kind of object, where each schema is backwards
// compatible with its predecessor.
#Lineage: [{...}, ...{...}]

#LastSchema: {
        _p: #Lineage
        _p[len(_p)-1]
}

// A Migration defines a relation between two schemas, "_from" and "_to". The
// relation expresses any complex mappings that must be performed to
// transform an input artifact valid with respect to the _from schema, into
// an artifact valid with respect to the _to schema. This is accomplished
// in two stages:
//   1. A Migration is initially defined by passing in schemas for _from and _to,
//      and mappings that translate _from to _to are defined in _rel.
//   2. A concrete object may then be unified with _to, resulting in its values
//      being mapped onto "result" by way of _rel.
//
// This is the absolute simplest possible definition of a Migration. It's
// incumbent on the implementor to manually ensure the correctness and
// completeness of the mapping. The primary value in defining such a generic
// structure is to allow comparably generic logic for migrating concrete
// artifacts through schema changes.
//
// If _to isn't backwards compatible (accretion-only) with _from, then _rel must
// explicitly enumerate every field in _from and map it to a field in _to, even
// if they're identical. This is laborious for anything outside trivially tiny
// schema. We'll want to eventually add helpers for whitelisting or blacklisting
// of paths in _from, so that migrations of larger schema can focus narrowly on
// the points of actual change.
#Migration: {
        from: {...}
        to: {...}
        rel: {...}
        result: to & rel
}
 [169 97 218 4 6 208 63 43 205 120 78 84 191 7 233 101]} {cue/ui/gen.cue package grafanaschema

TableCellDisplayMode: {
  Auto: "auto",
  ColorText: "color-text",
  ColorBackground: "color-background",
  GradientGauge: "gradient-gauge",
  LcdGauge: "lcd-gauge",
  JSONView: "json-view",
  BasicGauge: "basic",
  Image: "image",
} @cuetsy(targetType="enum")

TableFieldOptions: {
  width?: number
  align: FieldTextAlignment | *"auto"
  displayMode: TableCellDisplayMode | *"auto"
  hidden?: bool  // ?? default is missing or false ??
} @cuetsy(targetType="interface")

TableSortByFieldState: {
  displayName: string
  desc?: bool
} @cuetsy(targetType="interface")

TooltipDisplayMode:          "single" | "multi" | "none"          @cuetsy(targetType="enum")
FieldTextAlignment:   "auto" | "left" | "right" | "center" @cuetsy(targetType="type")
AxisPlacement:        "auto" | "top" | "right" | "bottom" | "left" | "hidden" @cuetsy(targetType="enum")
PointVisibility:      "auto" | "never" | "always"                             @cuetsy(targetType="enum")
DrawStyle:            "line" | "bars" | "points"                              @cuetsy(targetType="enum")
LineInterpolation:    "linear" | "smooth" | "stepBefore" | "stepAfter"        @cuetsy(targetType="enum")
ScaleDistribution:    "linear" | "log"                                        @cuetsy(targetType="enum")
GraphGradientMode:    "none" | "opacity" | "hue" | "scheme"                   @cuetsy(targetType="enum")
LineStyle: {
        fill?: "solid" | "dash" | "dot" | "square"
        dash?: [number]
} @cuetsy(targetType="interface")
LineConfig: {
        lineColor?:         string
        lineWidth?:         number
        lineInterpolation?: LineInterpolation
        lineStyle?:         LineStyle
        spanNulls?:         bool
} @cuetsy(targetType="interface")
FillConfig: {
        fillColor?:   string
        fillOpacity?: number
        fillBelowTo?: string
} @cuetsy(targetType="interface")
PointsConfig: {
        showPoints?:  PointVisibility
        pointSize?:   number
        pointColor?:  string
        pointSymbol?: string
} @cuetsy(targetType="interface")
ScaleDistributionConfig: {
        type: ScaleDistribution
        log?: number
} @cuetsy(targetType="interface")
AxisConfig: {
        axisPlacement?:     AxisPlacement
        axisLabel?:         string
        axisWidth?:         number
        axisSoftMin?:       number
        axisSoftMax?:       number
        scaleDistribution?: ScaleDistributionConfig
} @cuetsy(targetType="interface")
HideSeriesConfig: {
        tooltip: bool
        legend:  bool
        graph:   bool
} @cuetsy(targetType="interface")
LegendPlacement:   "bottom" | "right"          @cuetsy(targetType="type")
LegendDisplayMode: "list" | "table" | "hidden" @cuetsy(targetType="enum")
TableFieldOptions: {
        width?:      number
        align:       FieldTextAlignment | *"auto"
        displayMode: TableCellDisplayMode | *"auto"
        hidden?:     bool
} @cuetsy(targetType="interface")
GraphFieldConfig: LineConfig & FillConfig & PointsConfig & AxisConfig & {
        drawStyle?:    DrawStyle
        gradientMode?: GraphGradientMode
        hideFrom?:     HideSeriesConfig
} @cuetsy(targetType="interface")
VizLegendOptions: {
        displayMode: LegendDisplayMode
        placement:   LegendPlacement
        calcs: [string]
} @cuetsy(targetType="interface")
VizTooltipOptions: {
        mode: TooltipDisplayMode
} @cuetsy(targetType="interface")
 [86 75 157 152 122 207 49 23 165 202 142 228 90 151 147 249]}])} %!q(*fs.subFS=&{{0x3360720} public/app/plugins}) <nil>}: must provide absolute path prefix when generating cue overlay, got "/"
`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Fork repo
- Follow instruction to compile for windows
- Run command `./bin/windows-amd64/grafana-server.exe --config=./conf/defaults.ini --homepath=d:/WORKSPACE/grafana
`

**Environment**:
- Grafana version:
![image](https://user-images.githubusercontent.com/26327410/120446172-f8fdf800-c391-11eb-84e1-9fecc7d31bda.png)
- OS Grafana is installed on:
 Windows 10

**Comment by torkelo** [comment] 2021-06-02 10:13
duplicate of #34863

**Closed by torkelo** 2021-06-02 10:13 UTC
