### ISSUE TITLE
Feature Request - Key-Value variable type

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#2948] opened 2015-10-14 12:54 UTC
Hi,

What do you think about implementing additional template variable type in key-value(s) format? For example I have some interface traffic metrics only with interface names but I would like to group them based on functionality selected from the dropdown menu like below:
Group 1 >  eth0,eth1,eth2
Group 2 > eth3, bond0 

I think that it might be realy usefull feature even for the other use-cases.

**Comment by torkelo** [comment] 2015-10-16 14:53
would something like this solve your case? https://github.com/grafana/grafana/issues/2080

Can you describe how you build the groups? Buy metric inspection queries? Manual entry?

The issue title is not very accurate (i think), because the current templating system i key value,  the text you see when you pick a variable value is not the same as the underlying value (for example for All)

**Comment by pavleec** [comment] 2015-10-19 08:04
No, but I succesfully use it for many different cases.
The problem is that I would like to manually describe groups apart from the metrics inspection which don't contain required piece of information, e.g. I would like to group interface names based on their function but I'm unable to get their discriptions and include them in metric names to be able to use it as value groups/tags.

Group A > eth0,eth1
host1.interface.eth0.in
host2.interface.eth1.in
Group B > eth5
host3.interface.eth5.in

**Comment by pavleec** [comment] 2015-10-29 23:14
Do you need some more explanation or clarification of the above?

**Comment by mtanda** [comment] 2015-11-06 18:54
looks very similar https://github.com/grafana/grafana/issues/1988

**Comment by pavleec** [comment] 2015-11-07 21:31
You're right - that's exactly what I'm looking for :)

**Comment by mtanda** [comment] 2015-11-08 06:16
Is this PR solved for your case?
https://github.com/grafana/grafana/pull/1471

**Comment by pavleec** [comment] 2015-11-08 14:02
Yes, that's exactly what I need.
8 lis 2015 07:16 "Mitsuhiro Tanda" <notifications@github.com> napisał(a):

**Comment by mtanda** [comment] 2015-11-09 09:20
@torkelo The PR https://github.com/grafana/grafana/pull/1471 is ready to merge.
Do you have a plan to merge the PR?

**Comment by torkelo** [comment] 2015-11-09 09:25
no sure, its not high prio right now

**Comment by mtanda** [comment] 2015-11-09 10:05
ahh, okay. thanks for reply.

**Comment by torkelo** [comment] 2016-06-02 09:46
closing as dupe of https://github.com/grafana/grafana/issues/1988

**Closed by torkelo** 2016-06-02 09:46 UTC
Labels: state: needs more detail
