### ISSUE TITLE
Alerting showing mustache braces in email

### ISSUE THREAD

**Issue by ericuldall** [grafana/grafana#6300] opened 2016-10-17 23:46 UTC
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? Version 4.0.0-pre1 (commit: 97008f9)
- What datasource are you using? Prometheus
- What OS are you running grafana on? Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08)
- What did you do? Created a sweet alerting test
- What was the expected result? Alerts would pop
- What happened instead? Alerts popped, but the information in the alerting email was not fully parsed

More info...

So the alerts are awesome, except the labels are not getting parsed in the alert email.

Sample:

![screen shot 2016-10-17 at 4 38 29 pm](https://cloud.githubusercontent.com/assets/3223296/19459618/101a6b14-9489-11e6-956c-50641ce3d5a5.png)

{{ io_kubernetes_container_name }} should be getting parsed into something meaningful..I think. Any idea if there's something I have not configured correctly?

**Comment by bergquist** [comment] 2016-10-18 08:34
Are the legends correct in the graph panel? 
Using {{ X }} is a way to format the serie names based on label. Ex {{ job }} or {{ cpu }} is `io_kubernetes_container_name` really a label? Seems like a very long name for a label :)

**Comment by ericuldall** [comment] 2016-10-18 22:37
Yes, this is actually a correct label name that I can  use to customize labels in the legend.

**Comment by ericuldall** [comment] 2016-10-18 22:39
Why was this closed? I don't see any resolution here.

**Comment by bergquist** [comment] 2016-10-19 07:02
The was caused by a bug in the backend implementation of prometheus that didnt allow whitespace between `{{` and the label name. Thats been fixed in master. 

You can fix this in your current installation by removing the white space between the brackets and the labelname.

**Closed** 2016-10-19 07:01 UTC
Labels: comp: alerting, comp: alerting/notifications

**Comment by discoduck2x** [comment] 2016-10-19 07:09
@bergquist im using influx and get this:
![image](https://cloud.githubusercontent.com/assets/12600004/19508780/61f998d0-95db-11e6-8de1-d45052cc634b.png)

any way to get it to show the tag as its displayed in graph "VLAN20 IN" ?
![image](https://cloud.githubusercontent.com/assets/12600004/19508813/99586b1c-95db-11e6-8473-133618e2fd02.png)

**Comment by ericuldall** [comment] 2016-10-19 07:40
I just deployed a nightly build a few minutes ago. Should that have the fix?

**Comment by ericuldall** [comment] 2016-10-19 07:46
Just tested an alert and it is resolved in the new nightly build. TY!
