### ISSUE TITLE
Table footer shifts calculation when hiding other columns

### ISSUE THREAD

**Issue by Emieligeter** [grafana/grafana#65799] opened 2023-04-03 10:44 UTC
**What happened**:
The table footer calculation is not aligned with the correct column when a column is hidden

**What you expected to happen**:
That the calculations are done for the selected columns

**How to reproduce it (as minimally and precisely as possible)**:
You can reproduce it easily with two random walks and joining by field:

![image](https://user-images.githubusercontent.com/34571684/229486750-efa5ca58-98ca-4853-98f5-fc393f660237.png)

Here you see all the columns and the summation is done only for B-series. Now if I hide the time column:
![image](https://user-images.githubusercontent.com/34571684/229486822-b5208532-a861-4326-87b0-6fef144c66f1.png)

You can see that the calculation is now done for A-series (while the selected column for the calculation remained unchaged)

**Environment**:
- Grafana version: 9.4.3
- Datasource: tested with postgresql and randomwalk

**Comment by usmangt** [comment] 2023-04-03 11:13
Hi @Emieligeter,

Thanks for opening this issue.

Based on your steps of reproduction, I was not able to reproduce it on my test machine. I tried the same as you explained on play.grafana.com but for some strange reason, I cannot get the Table footer working. (I am probably missing a step here).

Can you please try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it?

Thanks

**Comment by Emieligeter** [comment] 2023-04-03 11:22
Hi @usmangt,
Thanks for your quick response. You can see the same behavior here: https://play.grafana.org/d/000000012/grafana-play-home?orgId=1
If you toggle hide column override youll see it happen. 

Ps. I just noticed that also the 'Total' footer title has dissapeared

**Comment by Emieligeter** [comment] 2023-04-03 11:35
Hi @usmangt,
Thanks for your quick response. I reproduced the issue in the play environment but I cant seem to share it properly. 
Ive copied the panel JSON source code so I hope you can reproduce it using this
```{
  "type": "table",
  "title": "Table sum bug",
  "datasource": {
    "uid": "grafana",
    "type": "datasource"
  },
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 8
  },
  "id": 13,
  "targets": [
    {
      "datasource": {
        "type": "datasource",
        "uid": "grafana"
      },
      "refId": "A"
    },
    {
      "datasource": {
        "uid": "grafana",
        "type": "datasource"
      },
      "refId": "B",
      "hide": false
    }
  ],
  "options": {
    "showHeader": true,
    "footer": {
      "show": true,
      "reducer": [
        "sum"
      ],
      "countRows": false,
      "fields": [
        "B-series"
      ]
    }
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "cellOptions": {
          "type": "auto"
        },
        "inspect": false
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "time"
        },
        "properties": [
          {
            "id": "custom.hidden",
            "value": true
          }
        ]
      }
    ]
  },
  "transformations": [
    {
      "id": "joinByField",
      "options": {}
    }
  ],
  "pluginVersion": "9.4.7"
}```

**Comment by polibb** [comment] 2023-04-13 13:23
Hi @Emieligeter 🙂. We reproduced this issue in Grafana 9.4.7 and earlier versions (as well as yours, 9.4.3) indeed. 
However, this issue is now fixed! So if you have an instance of Grafana Cloud on version 9.5.0 or wait for 9.5.0 OSS to be released, and upgrade to it - you will no longer have this bug 😊

**Closed by polibb** 2023-04-13 13:23 UTC
Labels: needs more info, area/panel/table
