### ISSUE TITLE
Other organizations dashboards in dashboard home

### ISSUE THREAD

**Issue by rjes** [grafana/grafana#5861] opened 2016-08-18 12:43 UTC
Hello!
I'm submitting a Feature request and running grafana version 3.1.1 (commit a4d2708).
I have two organizations "main" and "infra" with two corresponding users (admin vs infra).
The "admin" user is ofc admin and the infra have only access to the organization "infra".
I would like to have the dashboards from the organization "infra" on the "main" dashboard home so it's simple to look at different dashboards without jumping between organizations.

A feature request to the feature request: If I add an additional user that belongs to another organization it would be nice to be able to show the dashboards from all organizations that the user have access to.

**Comment by bergquist** [comment] 2016-08-18 12:48
Duplicate of https://github.com/grafana/grafana/issues/1613 (its been requested for a long time but never prioritized)

**Closed by bergquist** 2016-08-18 12:48 UTC
