### ISSUE TITLE
Table: Add support for multiple links per cell 

### ISSUE THREAD

**Issue by RobertoBiundo** [grafana/grafana#27004] opened 2020-08-14 08:58 UTC
**What happened**:
Adding two data links using overrides on a table panel works, multiple data links can be added, but only the first added data link is shown when clicking on the cell.

**What you expected to happen**:
That the popup while hovering over the cell showed multiple available links like it does with Panel level data links

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a table panel.
2. Create any simple query
3. Go to the overrides tab and create an override to one of the columns.
4. Add to data links to the columns using the override
5. Apply changes.
6. Hover over a cell with the new links.
7. Only one like appears. The other link can never be used

**Anything else we need to know?**:
This happens for both the datalinks from the override tab and the data links on the Fields tab

**Environment**:
- Grafana version: grafana docker : latest ( 7.1.1 )
- Data source type & version: ElasticSearch 7.0+
- OS Grafana is installed on: Dockerized ( host: ubuntu 20.04 )
- User OS & Browser: Ubuntu 20.04 - Firefox 79.0
- Grafana plugins:
- Others:

![Screenshot from 2020-08-14 10-52-59](https://user-images.githubusercontent.com/1950094/90232433-f93a0080-de1c-11ea-8fff-abcc8353390e.png)
![Screenshot from 2020-08-14 10-53-50](https://user-images.githubusercontent.com/1950094/90232434-f9d29700-de1c-11ea-835c-5945a90d8e50.png)

**Comment by torkelo** [comment] 2020-08-14 11:03
the table cell only support one link at this point

**Comment by RobertoBiundo** [comment] 2020-08-14 11:13
The why even allow creating multiple ones. It seem like a UX bug. Can I
then turn this into a request. I think is quite a useful tool to.have. And
most of the job is already done.

**Comment by maemigh** [comment] 2020-08-19 10:45
Multiple links per cell would be extremely useful to me as well.

**Comment by AnnasOop** [comment] 2020-09-01 20:34
This would also be useful for me.

**Comment by maemigh** [comment] 2020-10-28 15:18
As a workaround, I wonder if there is a way to use data from an external link to produce data in a modal? ie click the link and have data from it popup in a modal?

**Comment by Ultraseamus** [comment] 2021-01-27 00:07
Having this marked as "awaiting more evidence" seems like an odd choice.

In recent versions of Grafana, the old "+/-" buttons were removed from table cells. Which is something we used heavily. It was a nice, free way for tables to be interactable, and to allow people to quickly filter data on a dashboard based on what they were seeing in a table.

I was thinking that it was taken away in part because it could be replaced by multiple data links (harder for a user to implement, but still doable), but I am seeing now that multiple data links are not possible.

Combined with the table changes, this feels like a real regression.

At the vey least, it is a UX bug that multiple links can be added. But I think there is also something lost in that there is no longer any way to let people interact with a table and filter to/out a specific value (for the dash. The new table filter form React is nice, but it's only local). It has to be one or the other.

**Comment by MicahZoltu** [comment] 2021-03-28 13:13
To add some specificity to the use case here, I have a table with many different columns and I would like each column to link somewhere else.  As a trivial example, imagine a table with an `amazon_product_id` column and a `walmart_product_id` column.  I would like to be able to click on the `amazon_product_id` cell in the table and be taken to `amazon.com/amazon_product_id` and click on the `walmart_product_id` column and be taken to the `walmart.com/walmart_product_id` page.

As an alternative, just having the pop-up like Single Stat does when you have multiple data links would be a boon!  Then at least I could have an Amazon and a Walmart link for the table row that would go to different locations.

**Comment by bobemoe** [comment] 2022-03-24 08:56
Same here, added multiple data links to a Table like I do TimeSeries and expected to see the same style popup.

What does the `prio/awaiting-more-evidence` tag on here mean? The above discussion seems to describe the issue clearly. Happy to provide further evidence, what is required?

**Comment by Flambix9** [comment] 2022-04-26 11:21
Same here, i would be glad to help also.

**Comment by zerlok** [comment] 2022-05-04 17:25
Multiple links in single cell would be useful for me too.

**Comment by maspies** [comment] 2022-05-17 11:39
+1

**Comment by elliottll** [comment] 2022-05-20 01:42
+1

**Comment by tanking007** [comment] 2022-08-21 16:11
It is a fundamental feature for providing multiple hyperlinks, grafana should include this.

**Comment by puneetgoyal08** [comment] 2022-10-06 08:44
+1

**Comment by outtersg** [comment] 2022-10-27 15:23
… Or port "Sanitize HTML" from #24482 to get tuned formatting?

Note that the tip telling to switch to table-old still works on Grafana 9.

**Comment by bobemoe** [comment] 2023-02-03 19:10
This has just started working for me! When I commented on this issue back here https://github.com/grafana/grafana/issues/27004#issuecomment-1077386658 I left those not working data links in place! I just updated to latest 1.4pre and suddenly those links are now working!

**Comment by supilee** [comment] 2023-02-09 23:29
@RobertoBiundo , can you please confirm that it works for you as well?

<img width="354" alt="Screenshot 2023-02-09 at 3 26 21 PM" src="https://user-images.githubusercontent.com/110845248/217962097-95056ab3-ebed-400f-9c20-f85914dd01ef.png">

**Closed** 2023-02-10 16:01 UTC
Labels: type/feature-request, area/panel/table, prio/awaiting-more-evidence

**Comment by bobemoe** [comment] 2023-02-11 09:52
Any idea which commit/PR implemented this?

**Comment by Itsariandl** [comment] 2025-02-15 08:32
Its also useful for me 
Please add this
