### ISSUE TITLE
Grafana Custom Variable Dulicate Values

### ISSUE THREAD

**Issue by micgruber** [grafana/grafana#57104] opened 2022-10-17 15:36 UTC
**What happened**:

I created the following custom variable:

LastKeyFigureService : keyfigurechangedtopic, KeyFigureService : keyfiguretopic, DailyMachineDataService : keyfigurechangedtopic 

![image](https://user-images.githubusercontent.com/19686895/196220621-27da9d37-18fb-4278-aa4f-7bea4edd7296.png)

When I try to select the keys via the dropdown menu keys with the same value will be selected together.

![image](https://user-images.githubusercontent.com/19686895/196220415-2740cfd6-9a36-4ce4-b792-7fe16e7f4bd9.png)

**What you expected to happen**:

Keys should be selected individualy even if they have the same value.

**Environment**:
- Grafana version: 9.0.8.1

**Comment by ashharrison90** [comment] 2022-10-18 13:47
sounds like a duplicate of https://github.com/grafana/grafana/issues/52830

i don't think there's any easy fix for this btw: when parsing variable values from the url we only have the value so would have no idea which label it corresponds to

**Closed by ashharrison90** 2022-10-18 13:47 UTC
