### ISSUE TITLE
Amazon Athena: Variable 'query' field does not show up (in some projects)

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#81151] opened 2024-01-24 13:41 UTC
### What happened?

We have used Amazon Athena as data source for a long period, which works well.

However, in one account we recently experienced that the 'Variable/Query' method does not work in Project1 - yet it works in Project2. Both run the Grafana Cloud `Grafana v10.4.0-65283 (3b401d0d4d)`. 

Below you can see screenshots of creating a new dashboard within Grafana, adding a Variable of the query type and selecting Amazon Athena as the data source:

**Project1 (not working)**
![image](https://github.com/grafana/grafana/assets/26184427/b6bf3001-0236-4a2b-b7cc-423fea0f8d55)

**Project2 (working)**
![athena-query-works](https://github.com/grafana/grafana/assets/26184427/dc42f526-06d6-48da-94bb-f61b18733a4e)

In Project2, we are therefore unable to e.g. import dashboard templates that leverage the variables. When trying to do this we get the below error messages:
![error](https://github.com/grafana/grafana/assets/26184427/565f8819-46db-4ba9-9d72-5949652e21fd)

Currently this renders us unable to use the Amazon Athena data source in our Project2, which is problematic.

A few notes:
1) Both Projects shown above use the same backend and are set up identically
2) Both Projects are within the same Grafana account
3) We have tried uninstalling/reinstalling the Amazon Athena plugin (no change in result)
4) We have tried deleting and re-adding the Amazon Athena data source (no change in result)
5) In both projects we are able to create a new dashboard panel and query the Amazon Athena data source without any issues - i.e. the problem is specific to the Variable creation

### What did you expect to happen?

Both projects should work and support Variables with Amazon Athena queries

### Did this work before?

Yes, this worked before. It stopped working at some point when we tried to create a new Amazon Athena based dashboard in Project2 and has since then not worked. 

### How do we reproduce it?

Unsure how it can be reproduced as we are unable to replicate it across other accounts, but we may be able to provide access to the account.

### Is the bug inside a dashboard panel?

The bug is in the Variables "query" view for Amazon Athena

### Environment (with versions)?

Grafana: Cloud
OS: Windows 10
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Amazon Athena

**Comment by MatinF** [comment] 2024-02-08 13:06
Any updates on this? We are now seeing this also on another end user account and we're unable to resolve it, beyond creating a new separate account entirely?

**Comment by barkanhvl** [comment] 2024-02-09 05:12
Experiences:
1. I set up Athena to the account/S3 bucket that i have been using with Influx for a long time, and new set up distrupted Influx Lambda function.
2. For this set up, i got same error as explained above for Athena. This means neither Influx nor Athena is working after i set up Athena to the Grafana account that i've been using with Influx. 
3. I created a new Grafana account, still connected to same S3 bucket and it worked.  But with some issues. At this time, my Influx Lambda function still not working. 
3.1 Stack output includes most of DBC file messages but not all of them. I don't know what depends on this but some ID's don't exist as output, so as Grafana visualization.
3.2 In Grafana Athena, i lost visualization for some time later. For ex: i was able to see X data in the graph, but now it is empty  and not coming back. I'm not sure if this is a triggering issue.

**Comment by MatinF** [comment] 2024-02-09 06:22
> Experiences:
> 
> 1. I set up Athena to the account/S3 bucket that i have been using with Influx for a long time, and new set up distrupted Influx Lambda function.
> 2. For this set up, i got same error as explained above for Athena. This means neither Influx nor Athena is working after i set up Athena to the Grafana account that i've been using with Influx.
> 3. I created a new Grafana account, still connected to same S3 bucket and it worked.  But with some issues. At this time, my Influx Lambda function still not working.
>    3.1 Stack output includes most of DBC file messages but not all of them. I don't know what depends on this but some ID's don't exist as output, so as Grafana visualization.
>    3.2 In Grafana Athena, i lost visualization for some time later. For ex: i was able to see X data in the graph, but now it is empty  and not coming back. I'm not sure if this is a triggering issue.

Note that the Lambda function aspect is isolated from Grafana - for questions on that aspect, I suggest reaching out to us directly at CSS. The Grafana aspect relates to the issue with the Athena data source Variable aspect only

**Comment by idastambuk** [comment] 2024-02-19 12:03
Hi @MatinF sorry for the delay in us getting to this! That's quite strange, I can't reproduce this in my cloud instance, so I have some questions to help us debug: 
1. Which version of Athena do you have on both the working and non-working instances?
2. When you open the variable query editor in the instance that doesn't show the query editor, can you see any errors in the dev tools console?

**Comment by barkanhvl** [comment] 2024-02-20 04:27
Hello.

1. Both are same. 2.13.4
2. Can you share a screenshot of where you want to see please.

**Comment by MatinF** [comment] 2024-02-20 07:11
@barkanhvl I think they are referring to this type of view, you can open it via F12:

![image](https://github.com/grafana/grafana/assets/26184427/8d0218f1-e94d-4792-87bd-c3eb14a13185)

**Comment by idastambuk** [comment] 2024-02-20 14:15
Hi again @MatinF and @dragpopo, thanks a lot for the screenshots! I wonder if the two instances have different feature toggle configuration that makes them behave differently. Are we allowed to temporarily access the two instances in order to debug? Thanks!

**Comment by MatinF** [comment] 2024-02-20 14:40
@dragpopo perhaps you can arrange this with the Grafana team. Where can he send login details in that case @idastambuk ?

**Comment by idastambuk** [comment] 2024-02-20 15:41
Hi @MatinF I see your instances from the screenshots, we can access them with our Grafana support accounts - nothing you need to do manually. Will keep you updated!

**Comment by sarahzinger** [comment] 2024-02-20 18:14
Hey folks! Sorry for the confusion but could you actually open up a support ticket with Grafana if you'd like us to help debug your instance: https://grafana.com/profile/org/tickets/new 

We can't actually access your account without going through that route first for security reasons. Sorry for the mixup!

Also in the meantime, if you could take a screenshot for each of the affected instances with the version of grafana you're running that could help us try to reproduce it on our end without necessarily having to access the instance. For example on the upper right hand quarter of the page if you click on the ? you should see something like this when you click on it:

<img width="326" alt="Screenshot 2024-02-20 at 1 02 47 PM" src="https://github.com/grafana/grafana/assets/6620164/06851484-419c-4fff-8013-f4b03498313e">

Each will have a git commit that lets us determine the exact version of grafana your instance is running on so we can better debug on our end. Thanks!

**Comment by sarahzinger** [comment] 2024-02-20 18:22
Wondering if this is related: https://github.com/grafana/grafana/issues/83068

**Comment by MatinF** [comment] 2024-02-20 18:43
Thanks Sarah - I unfortunately can't replicate it in my account, but perhaps Dragos can do this when he is able

**Comment by sarahzinger** [comment] 2024-02-20 18:49
Hmm I think I may have reproduced the problem by enabling this feature toggle `pluginsFrontendSandbox` which I believe is an additional security layer that folks have been working on for a while. I haven't quite figured out yet why that causes the issue. But until we get to a fix you're welcome to reach out to support and ask that pluginsFrontendSandbox is turned off temporarily to see if that fixes the issue?

**Comment by dragpopo** [comment] 2024-02-20 19:03
Hello, something seemed to have happened in the past hour that actually reproduced the issue on our new dashboard. We just lost all the data on Grafana even though it is still being uploaded on the S3 server.
![image](https://github.com/grafana/grafana/assets/86256063/72be6268-439a-433f-b149-7ee1b39f52e1)
We need that dashboard to work to see our data, while trying to reproduce the issue, did you use the new account that we are currently using ?

**Comment by MatinF** [comment] 2024-02-20 19:15
@dragpopo I don't think they can access your dashboard as per their previous reply. Rather, I think this is a general bug in Grafana that may arise - the dashboard data is not lost, but until the template issue is fixed it'll show that error. You can try their suggestion:

```
Hmm I think I may have reproduced the problem by enabling this feature toggle pluginsFrontendSandbox which I believe is an additional security layer that folks have been working on for a while. I haven't quite figured out yet why that causes the issue. But until we get to a fix you're welcome to reach out to support and ask that pluginsFrontendSandbox is turned off temporarily to see if that fixes the issue?
```

**Comment by dragpopo** [comment] 2024-02-21 12:17
Hello, I think the issue yesterday might have come from Grafana, it is working fine now:
![image](https://github.com/grafana/grafana/assets/86256063/a0f42018-7561-42b6-9f68-d9fc86a52536)
But I'll keep in mind the pluginsFrontendSandbox if it happens again.

**Comment by sarahzinger** [comment] 2024-02-21 21:26
Its unrelated to the managed alerting error, it was fixed when the `pluginsFrontendSandbox` feature flag was rolled back for all accounts. We believe the root cause was fixed in: https://github.com/grafana/grafana/pull/83152 and shouldn't happen as we roll out the feature again. Thanks for reporting!

**Closed by sarahzinger** 2024-02-21 21:26 UTC
Labels: effort/small, area/dashboard, area/query-editor, triage/needs-confirmation, team/grafana-aws-datasources

**Comment by dragpopo** [comment] 2024-02-23 13:11
Hello, thanks for the help Sarah, it is much appreciated!
