### ISSUE TITLE
Expose an API for plugins for setting variable values

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#24798] opened 2020-05-18 15:38 UTC
Expose an API to set variable values from plugins.
Existing API only allows plugins to get variables values.

Personally, I have a very needed scenario in which I'm required to set a variable value from my plugin.
I noticed a few questions about it here and there on the web, so I'm not the only one.
Didn't find a straight enough solution for Grafana 7.0

**Comment by wbrowne** [comment] 2021-07-05 14:30
Closing this in favour of duplicate #29647

**Closed by wbrowne** 2021-07-05 14:30 UTC
Labels: area/plugins, type/feature-request

**Comment by Ultraseamus** [comment] 2021-07-21 20:18
@wbrowne I don't think I'd agree that this request is a duplicate of https://github.com/grafana/grafana/issues/29647.

 
gilkgit's feature request is specifically to be able to set variable values form a plugin. Whereas the other request was for the ability to create new variables from scratch.

@torkelo Responded to that other request asking for more evidence that that feature would be valuable (it sounds pretty niche, and giving plugins that level of control seems complex and risky). Also, that feature request is almost a year old without any activity.

However, I would argue that this request to allow plugins to set existing variables is much more reasonable, and I'll bet it could find uses in many plugins.

I can provide usage examples, if that would help (I can place them in the other feature request if that's where these types of requests are being kept). But, it just boils down to what this feature request stated already. An interactive plugin is much more powerful than a static one. Word Clouds, Maps, Sankeys, Bubble Charts, search bars... all of those the user would want to be able to click on an element and have the page update using that as a filter.
