### ISSUE TITLE
Dashboards: Chinese characters cannot be filtered when they are re-filtered within the template value

### ISSUE THREAD

**Issue by 291723286** [grafana/grafana#90123] opened 2024-07-05 09:40 UTC
### What happened?

 I can no  use chinese character filtering in template values when upgrade v10.0.1 to v11.1.0. 
This issue will also occur with the new grafana v11.1.0 instances as well

issus
![1](https://github.com/grafana/grafana/assets/35591735/b92dd615-d0fc-44cd-806b-9e7ba35f2db0)

filter by 中国，but is no values 
![2](https://github.com/grafana/grafana/assets/35591735/5afc6716-32ab-4605-a16f-a383295ad315)

### What did you expect to happen?

filter sucess

### Did this work before?

v10.0.1 is ok

### How do we reproduce it?

Template Variables  container chinese character

### Environment (with versions)?

Grafana:  v11.1.0
OS: docker
Browser: google

### Grafana platform?

Docker

**Comment by kapmix** [comment] 2024-07-31 08:36
Any solution? 
Expect sharing.

**Comment by ashharrison90** [comment] 2024-08-16 14:07
dupe of https://github.com/grafana/grafana/issues/90123

**Closed by ashharrison90** 2024-08-16 14:07 UTC
Labels: area/frontend, area/internationalization

**Comment by kapmix** [comment] 2024-08-31 05:12
Grafana: v11.2.0

This issue still exists.
