### ISSUE TITLE
One data point per day: bars representation spreads over two days (BigQuery datasource)

### ISSUE THREAD

**Issue by HugoPuntos** [grafana/grafana#26655] opened 2020-07-28 14:51 UTC
**What happened**:

I've noticed that when creating a chart containing one data point per hour, the bar representation spreads over two days:

<img width="1302" alt="screenshot-b" src="https://user-images.githubusercontent.com/5734735/88673499-fa62f200-d0e8-11ea-8056-0fe8e6d2590f.png">

<img width="1256" alt="screenshot-a" src="https://user-images.githubusercontent.com/5734735/88673507-fc2cb580-d0e8-11ea-8085-cb6003a33a1a.png">

**What you expected to happen**:

I expect to have the bar not spreading over two days.

**How to reproduce it (as minimally and precisely as possible)**:

  1. Create a chart using a BigQuery data source
  1. Use the following query to reproduce the issue
```
select TIMESTAMP("2020-07-26 00:00:00 UTC") as time, 100
union all
select TIMESTAMP("2020-07-27 00:00:00 UTC") as time, 231
union all
select CAST(CURRENT_DATE() as timestamp) as time, 300
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: BigQuery
- User OS & Browser: MacOS/Chrome
- Grafana plugins: oitintl-bigquery-datasource

**Comment by torkelo** [comment] 2020-07-28 18:30
can you open panel inspect and show the raw data points in the table?

**Comment by HugoPuntos** [comment] 2020-08-06 08:39
Hello,

Here are the data:

![Screenshot 2020-08-06 at 10 32 44](https://user-images.githubusercontent.com/5734735/89510168-87383a80-d7d0-11ea-98ac-e5885fac7444.png)

I tried with the following request to have the timestamp at "00:00:00":

```
select TIMESTAMP("2020-08-03 00:00:00 UTC+2") as time, 100
union all
select TIMESTAMP("2020-08-04 00:00:00 UTC+2") as time, 231
union all
select TIMESTAMP("2020-08-05 00:00:00 UTC+2") as time, 156
```

but the result is the same.

Thanks for your help,

**Comment by torkelo** [comment] 2020-08-09 06:50
duplicate of https://github.com/grafana/grafana/issues/22611

**Closed by torkelo** 2020-08-09 06:50 UTC
Labels: needs more detail
