### ISSUE TITLE
Value groups/tags seems to be broken

### ISSUE THREAD

**Issue by directionless** [grafana/grafana#6906] opened 2016-12-09 22:36 UTC
I'm playing with the value groups/tags, and it seems to be broken.

The dashboard in http://play.grafana.org/dashboard/db/templating-value-groups looks okay, but as soon as I toggle any of the template variables, I stop seeing tags. 

And if I try to add a variable with tags from graphite, following the examples, it doesn't seem to work. 

query: apps.*.*
tags value: apps.*
tag value query: apps.$tag.*

**Comment by Farfaday** [comment] 2016-12-10 21:52
It seems that the tag ceased working since release of version 4.0.
It works on latest 3.* version. 

Our setup on version 3.x and InfluxDB as a datasource:
query: SHOW TAG VALUES WITH KEY=host
tag value: SHOW TAG VALUES WITH KEY=host where host =~ /$tag/

On version 4.0.2, I can click on "enable" in the "Templating" menu, but it disappears after clicking the green "update" button.

**Comment by tfylling** [comment] 2016-12-12 09:27
Duplicate of #6752

**Comment by bergquist** [comment] 2016-12-12 09:34
Closing since its a dupe.

**Comment by bergquist** [comment] 2016-12-12 09:34
Thanks @tfylling :)

**Closed** 2016-12-12 09:33 UTC
Labels: comp: dashboard/templating, type: bug
