### ISSUE TITLE
Unable to locally build the plugin generated by the grafana-toolkit

### ISSUE THREAD

**Issue by GuruCharan94** [grafana/grafana#24626] opened 2020-05-13 12:15 UTC
**What happened**:
I am trying to build a new Grafana plugin on Windows 10 . When I try to build the generated code using `yarn build`, the build fails with error `The "path" argument must be of type string. Received undefined` 

**What you expected to happen**: The build to succeed.

**How to reproduce it (as minimally and precisely as possible)**: Create a new plugin by following [the docs](https://grafana.com/tutorials/build-a-data-source-plugin/#3)

**Anything else we need to know?**: 
`pwd` is empty here and causes the issue.  https://github.com/grafana/grafana/blob/87c2e58dfd3dc6fa4e6c95e324b5a33f9572a6fa/packages/grafana-toolkit/bin/grafana-toolkit.js#L11

This fixes the problem locally.
` const pwd = process.env.CIRCLE_WORKING_DIRECTORY || process.env.PWD || "" ; `

**Environment**:
- Grafana version: NA
- Data source type & version: NA
- OS Grafana is installed on: NA
- User OS & Browser: NA
- Grafana plugins: NA
- Others: `@grafana/toolkit@next":  version "7.0.0-beta.1"`

**Comment by zoltanbedi** [comment] 2020-05-13 18:57
Hi @GuruCharan94,
Thanks for reporting this problem, I can confirm it is bug. Would you mind creating pr with a fix?
I think a better approach would be to use `process.cwd()` instead of `process.env.PWD`

**Comment by zoltanbedi** [comment] 2020-05-13 19:11
I've found out that this issue is a duplicate of #24582 so I'm going to close this. PR with the fix is still welcome though!

**Closed by zoltanbedi** 2020-05-13 19:11 UTC
Labels: area/grafana/toolkit, type/bug
