### ISSUE TITLE
The table header is not scrolling(horizontal) with the content 

### ISSUE THREAD

**Issue by NilaanL** [grafana/grafana#18839] opened 2019-09-02 17:14 UTC
The table header is not scrolling(horizontal) with the content :

The header should move together with the content  :

The header is define as a different division in design , Bounding table header  together with the table body could be a solution :

**Anything else we need to know?**:

- 6.2.5
- mysql :
- windows:
- os-windows 10, linux ;browser -chrome :
- pie chart , worldmap
- Others:

**Comment by torkelo** [comment] 2019-09-03 06:31
dupe of https://github.com/grafana/grafana/issues/17784

**Closed by torkelo** 2019-09-03 06:31 UTC
