### ISSUE TITLE
Snapshots created with absolute time range doesn't render the data

### ISSUE THREAD

**Issue by dominikbenner** [grafana/grafana#33969] opened 2021-05-12 06:59 UTC
Hi!

I have a public grafana server, where i only publish snapshots to. They can be accessed anonymously.
Simple Dashboards work to publish.
Complex Dashboards are broken on public server. For example: TimeSeries Panels dont have data inside; Tables only have one column and Transformations dont apply.
Ive set timeout to 40 seconds on snapshot creation but the issue persists.
There are no errors in logfiles in general.

Dashboard with Timeseries panels:
![image](https://user-images.githubusercontent.com/17137915/117932041-383fa880-b300-11eb-9930-8c16fde327b9.png)

Snapshot from this Dashboard:
![image](https://user-images.githubusercontent.com/17137915/117932095-45f52e00-b300-11eb-915b-a150bdf09639.png)

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: Postgresql
- OS Grafana is installed on: Internal Server Windows Server 2016 ; Snapshotserver Centos7
- User OS & Browser: Windows 10; Chrome
- Grafana plugins: Zabbix Datasource (not used in this snapshots)
- Others:

**Comment by marefr** [comment] 2021-05-12 17:07
What's the Grafana version of the snapshot server? If you use your browsers developer tools and check the console can you see any errors/warnings being logged?

**Comment by s4ndst0rm** [comment] 2021-05-18 18:48
@marefr The Snapshot Server is on 7.5.6.  Updated main server to 7.5.6 too. The issue persists.
I am using graph panel / timeseries panel / table.

On other dashboards these panel types are working. On some dashboards not.

Screenshot from developer console from snapshot server:
![image](https://user-images.githubusercontent.com/17137915/118706890-2f783680-b81a-11eb-8e85-47e1be68d072.png)


Screenshot from main server after creating snapshot:
![image](https://user-images.githubusercontent.com/17137915/118707082-664e4c80-b81a-11eb-82c1-a4db08ada1fa.png)

**Comment by marefr** [comment] 2021-05-19 08:01
Haven't been able to reproduce. Seems like the data is there because you get series labels. If you create a local snapshot does that always work? Would have to ask you to include your dashboard json from main server and for a snapshot on snapshot server replace the snapshot url `http://<host>/dashboard/snapshot/<snapshot id>?orgId=1` with `http://<host>/api/snapshots/<snapshot id>` to get the full snapshot JSON and include it here. Should there be sensitive data, please replace that dummy data.

**Comment by dominikbenner** [comment] 2021-05-20 11:05
Nice hint. 
Local snaptshot does not work too.
Here is the Snapshot JSON. Maybe my custom all value, which is a SQL statement, is the problem?
[1hHH7H67l6FQjXdwQaEU5wWZKIo89Op7.zip](https://github.com/grafana/grafana/files/6515369/1hHH7H67l6FQjXdwQaEU5wWZKIo89Op7.zip)

**Comment by dominikbenner** [comment] 2021-05-28 09:28
@marefr Any update on this?

**Comment by marefr** [comment] 2021-06-28 12:12
Sorry for slow response. Thanks for the data. I got the same results as you. When loading the snapshot all panels seems to use last 6 hours, for example 

![image](https://user-images.githubusercontent.com/1668778/123632690-83623c00-d818-11eb-8429-1d9a50872cdf.png)

However, opening the time range control and clicking _Apply time range_ the snapshot seems to show all the data. So please try this as a workaround for now
![image](https://user-images.githubusercontent.com/1668778/123632789-a1c83780-d818-11eb-9982-04cb71ed5814.png)

Inspecting the JSON of the loaded snapshot shows that the time-property has a raw-property and I'm not sure that should be there, see below
![image](https://user-images.githubusercontent.com/1668778/123633135-1d29e900-d819-11eb-9435-1e0ce741d8dc.png)

I tried removing the raw-property and using the same raw from/to-values as time from/to-values and creating the snapshot again without any success. Seems like a bug with loading snapshots with absolute time. I did test on latest main (81a79aef23641181585c907225000472403b683e)

Able to reproduce on play. I did create [this snapshot](https://play.grafana.org/dashboard/snapshot/S274PpXPbVNwrE7oTjOWqYIOVi8srL7M?orgId=1) from this [absolute time dashboard](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&from=1624744800000&to=1624831199000) (before changing the time it was the home dashboard default last 1 hour). I will ask @grafana/grafana-frontend-platform to look into the details of this.

**Comment by dominikbenner** [comment] 2021-06-29 14:54
@marefr Thank you! Some of the problems are solved changing the timepicker some not.

Tables DO work randomly: 
![image](https://user-images.githubusercontent.com/17137915/123819904-6f8f0680-d8fa-11eb-8bcc-66eda862d1be.png)

Original (without sensitive data. table is filled with data):
![image](https://user-images.githubusercontent.com/17137915/123820212-b41aa200-d8fa-11eb-9406-3d47707c7742.png)



This Stat panels never work:

![image](https://user-images.githubusercontent.com/17137915/123819962-7cabf580-d8fa-11eb-8fa4-4aabc8d467a2.png)

Original:
![image](https://user-images.githubusercontent.com/17137915/123820128-9f3e0e80-d8fa-11eb-9987-8ea80b9216bf.png)

Other panels DO work. very strange.

**Comment by masto** [comment] 2021-06-30 15:17
I think this is the same problem I have been encountering, which is more generically described in the [earlier comment](https://github.com/grafana/grafana/issues/33969?_pjax=%23js-repo-pjax-container#issuecomment-869632192) as defaulting to 6 hours. Whenever I load a snapshot, it ignores the time range (even if it's set in the URL). Clicking the Grafana reload button resets the view to show the correct time, though, so all the data is there.

Here's a simple example: https://grafana.masto.house/dashboard/snapshot/s61DQiRnOCPgXY3Y9H7jFVjYQwInDP0G

**Comment by dominikbenner** [comment] 2021-07-01 10:51
@masto I changed the timerange. But my tables and statspanel remain incorrent and full of glitches as described in my last comment.
So there must be another problem.

**Comment by masto** [comment] 2021-07-01 11:13
Ah. I’ll open a separate issue then for the time range thing.

**Comment by torkelo** [comment] 2021-07-01 12:34
Can confirm this, the time range in the snapshot does not look correct

**Comment by torkelo** [comment] 2021-07-01 12:49
Fixed in https://github.com/grafana/grafana/pull/36350

**Closed** 2021-07-02 11:05 UTC
Labels: area/dashboard/snapshot, type/bug

**Comment by dominikbenner** [comment] 2021-07-02 15:24
@torkelo did you noticed my comment that there is another issue not related to the timepicker? Especially in stats Panel and table.

**Comment by torkelo** [comment] 2021-07-05 13:23
@dominikbenner I am unable to replicate any issues with table or stat panel snapshots. 

https://play.grafana.org/dashboard/snapshot/Nl5yrmH1oC4DvQRebgcNabYpNdV35Qeu?orgId=1

https://play.grafana.org/dashboard/snapshot/yJ0iH164ztiUGmv9Pqk3POekh39BoEMc?orgId=1

**Comment by dominikbenner** [comment] 2021-07-05 15:13
@torkelo Unfortunately i cannot give you full access to my snapshots because there is confidential data in it. 
The glitches i posted above in the screenshot are reproducable. I Took multiple snapshots and everytime the same issues

Any other chance to inspect this issue ?

**Comment by torkelo** [comment] 2021-07-05 16:24
@dominikbenner can you share the dashboard json or stat panel settings?

**Comment by torkelo** [comment] 2021-07-05 16:24
any transformations used?

**Comment by dominikbenner** [comment] 2021-07-07 06:04
Hi. 
Attached the panel JSONS from source and snapshot target.

There are no transformations configured.
[paneljson.zip](https://github.com/grafana/grafana/files/6774741/paneljson.zip)
