### ISSUE TITLE
sign in url is wrong (404) when installed under a path

### ISSUE THREAD

**Issue by avelo** [grafana/grafana#26327] opened 2020-07-14 12:46 UTC
**What happened**:
Pressing Sign In on sidebar menu gives an 404 error, due to path missing in that url. ex: if grafana is installed in foo.bar/grafana/, forceLogin url uses only foo.bar/ and not foo.bar/grafana/ as base url

**What you expected to happen**:
That installing path were included and so, not having a 404

**How to reproduce it (as minimally and precisely as possible)**:
Make an install in a path ang go to sign in

**Anything else we need to know?**:

**Environment**:
- Grafana version:
7.0.6
- Data source type & version:

- OS Grafana is installed on:
Debian 10
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by acdha** [comment] 2020-07-15 22:42
I confirmed the same bug — we have server.root_url but some change between 7.0.5 and 7.0.6 causes the sign in URL to be generated without it, although most of the other application links work.

**Comment by ivanahuckova** [comment] 2020-07-16 15:07
duplicate of #26228, fix is part of [7.1 release](https://github.com/grafana/grafana/pull/26239).

**Closed** 2020-07-16 15:07 UTC
