### ISSUE TITLE
Public dashboards can't config in docker-compose, `GF_FEATURE_TOGGLES_PUBLICDASHBOARDS=true` is not working

### ISSUE THREAD

**Issue by we684123** [grafana/grafana#57237] opened 2022-10-19 03:51 UTC
**What happened**:
i follow [Override configuration with environment variables](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables) to make a `docker-Compose.yml`, 

docker-Compose.yml：
```docker-compose
version: '3.9'

services:
  grafana:
    image: grafana/grafana:9.2.0-ubuntu
    container_name: grafana_alpha
    networks:
      - backend
    ports:
      - "3001:3000"
    volumes:
      - ./Docker_link:/var/Docker_link
      - ./Docker_link/grafana/data:/var/lib/grafana
      - ./Docker_link/grafana/provisioning:/etc/grafana/provisioning
      - ./secrets/grafana/admin_password:/run/secrets/admin_password
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_FEATURE_TOGGLES_PUBLICDASHBOARDS=true

networks:
  backend:
    driver: bridge
```

in docker-compose, `GF_FEATURE_TOGGLES_PUBLICDASHBOARDS=true` is not working

----

**What you expected to happen**:

when i exec in container, and `cat /etc/grafana/grafana.ini` ,  
the
```
[feature_toggles]
publicDashboards = true
```
is not exist , so when i open 127:0.0.1:3001, and make a dashboard,  just got this ↓
![2022-10-19 11_14_09-粗糙的新版 - Dashboards - Dashboards - Grafana — Mozilla Firefox](https://user-images.githubusercontent.com/22027801/196591617-206c74b7-ff05-47fe-bb81-bd1ee7306331.png)

----

**How to reproduce it (as minimally and precisely as possible)**:
```bash
docker compose up
```

**Environment**:
- win11 (22621.675)
- Docker Desktop 4.12.0 (85629)

**Comment by we684123** [comment] 2022-10-19 03:54
Another way to enable Public dashboards in Docker
```
volumes:
      - ./configs:/var/Docker_link/configs
environment:
      - GF_PATHS_CONFIG=/var/Docker_link/configs/grafana.ini
```

**Comment by usmangt** [comment] 2022-10-20 09:54
Hi @we684123,

Thanks for opening this issue. I will try to reproduce it as per your steps and will get back to you.

**Comment by usmangt** [comment] 2022-10-20 11:03
Ok, I was also not able to enable the public dashboard by using the 

`GF_FEATURE_TOGGLES_PUBLICDASHBOARDS=true`

So will forward to our engineers to have a look and tell whether there is a configuration issue or a bug.

**Comment by usmangt** [comment] 2022-11-09 10:31
Added the Dashboard project as well because not sure via excel sheet which says that it comes under Dashboard. (incase wrong then kindly let me know)

**Comment by axelavargas** [comment] 2022-11-09 14:32
Hello @we684123 👋🏾 , thanks for reporting this issue, I think we need to update our documentation on how to enable feature flags in docker, can you try adding this:

`GF_FEATURE_TOGGLES_ENABLE=publicDashboards`

Thank you 🙏🏾

**Comment by axelavargas** [comment] 2022-11-09 17:24
btw, I'm closing this issue because this line should work, but if it doesn't, feel free to let me know and we can reopen it 😄

**Closed by axelavargas** 2022-11-09 17:24 UTC
Labels: type/bug, area/docker, public-dashboards
