### ISSUE TITLE
[Bug] time filter is exclusive instead of inclusive

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#8995] opened 2017-08-06 21:05 UTC
Please include this information:
- What Grafana version are you using?
4.3.2

- What datasource are you using?
InfluxDB

- What OS are you running grafana on?
Linux

- What did you do?
Used the time picker

- What was the expected result?
See results starting at the selected start time, and results ending at the selected end time.

- What happened instead?
See results starting after the selected time, and results ending before the selected end time.
This results in a gap at the start and end of the graph.

- Additional information
The query that is generated uses `WHERE time > X and time < Y` instead of `WHERE time >= X and time <= Y`.

**Comment by torkelo** [comment] 2017-08-07 08:03
duplicate of https://github.com/grafana/grafana/issues/8319

**Closed by torkelo** 2017-08-07 08:03 UTC
