### ISSUE TITLE
No notifications on alerts send if notification channel for webhook is not set to default

### ISSUE THREAD

**Issue by krauselukas** [grafana/grafana#26725] opened 2020-07-31 12:26 UTC
**What happened**:

After removing the default flag (send on all alerts) from our webhook notification channel in the grafana settings, we didn't received any notification on alerts. We double checked that the notification channel is now set manually in the corresponding alerts. This was the case. After setting the channel back to default, grafana again started to send notification as expected.

**What you expected to happen**:

Grafana sends notifications through a webhook, even the channel is not set as a default for alerts.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure a notification channel with a webhook in Grafana, and enable the default (send on all alerts) flag.
2. Setup an alert in one of your panels.
3. Wait for the alert to be triggered and a notification send to the corresponding endpoint.
4. Disable the default option, and make sure the channel is set manually in the recently created alert.
5. Re-trigger the alert, and confirm that no notification is received at the configured webhook endpoint.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.1 (3039f9c3bd)
- Data source type & version: InfluxDB
- OS Grafana is installed on: SUSE Linux Enterprise Server 15 SP2

**Comment by badcrc** [comment] 2020-09-17 14:40
I can confirm this happening in Grafana v7.1.3 (5723d951af)

**Comment by dsotirakis** [comment] 2021-03-02 16:18
Tested with both Slack/Discord norifications on 7.4.3 and 7.1.1, and I can't see any error if you set the channel manually? 
I get the alerting on both platforms. Is there a case you didn't specify a channel at all?

**Comment by marefr** [comment] 2021-03-29 19:24
Since we cannot reproduce this we'll close this. If you don't agree please provide more information such as dashboard/panel json together with Grafana server log and we'll consider reopen this. Thanks

**Closed by marefr** 2021-03-29 19:24 UTC
Labels: area/alerting/notifications, area/backend, needs investigation
