### ISSUE TITLE
Assign notification channels to teams / users 

### ISSUE THREAD

**Issue by schoofsc** [grafana/grafana#22885] opened 2020-03-19 07:50 UTC
**What would you like to be added**:
It should be possible to assign the notification channels to teams or users, so that the users can only see their own notification channels with the role editor. 
In the context of this feature, the dashboards would also only have to display the notification channels in the configuration of the alerts that are in your own team.

**Why is this needed**:
This feature is needed to prevent misuse of Grafana's editor rights and to avoid errors caused by incorrect editing of the wrong notification channel. 
It also facilitates the clarity of the notification channels

**Comment by aknuds1** [comment] 2020-03-19 08:42
Looks as a possible duplicate of #12332. What do you think @schoofsc - is there overlap between what you want and that feature request?

**Comment by aknuds1** [comment] 2020-03-19 08:44
Closing as a duplicate of #12332, please upvote that issue :)

**Closed** 2020-03-19 09:27 UTC
Labels: type/duplicate
