### ISSUE TITLE
Is there a way to track missing features/issues for Timeseries

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#49031] opened 2022-05-16 19:50 UTC
For over a year I'm trying to migrate to Timeseries panel.

However, I've found a lot of bugs and missing features, created a lot off issues to track those. Some of those issues, especially features, were converted to discussions.

I think discussions suck, it's impossible to filter it. E.g. I tried to find a way to filter out FR discussions that are resolved. But did not a way how. E.g. https://github.com/grafana/grafana/discussions/38202 this is resolved already.

Does anyone have a way to track active feature requests? https://github.com/grafana/grafana/discussions?discussions_q=label%3Aarea%2Fpanel%2Ftimeseries is the most far.

**Comment by zuchka** [comment] 2022-05-18 18:34
sorry @simPod 

I agree that the tracking could be better. Have you seen this epic issue?

https://github.com/grafana/grafana/issues/30564

**Comment by simPod** [comment] 2022-05-18 19:28
Yup, that's actually what I had in mind. I was tracking the issue and it was a great overview. But it was closed as solved and is no longer active.

> This one has been with us for a long time and majority of the items here are already tracked as independent issues/discussions. Closing this epic.

But Timeseries panel is still kind of far from being viable replacement of Graph. It has few features where it's superior already but for me and many many users (ref: check discussions, community forum, issues) is still impossible to upgrade. 

E.g. Time Regions were introduced recently as a Graph feature. So users started using it. Then Timeseries panel came and the feature is not there.

It's hard to track what's planned by Grafana to be implemented, what Grafana is aware of to be missing.

**Comment by leeoniya** [comment] 2022-05-18 19:51
hey @simPod 

can you please put together a new list here of what is still missing and we'll continue from that. Graph has so many features that have been moved to other panels, or deprecated, that it's quite difficult to track what is still truly missing. you're right, the discussions thing is pretty useless, and my personal opinion is that it was a mistake because of terrible filtering and search functionality.

What i'm aware of currently:

**Missing:**

- Time Regions
- Null as zero (we're working through this currently) https://github.com/grafana/grafana/discussions/43093
- Log axes for bases 4,16,32,128, etc.

**Needs improvement:**

- legend and tooltip
  - hide null & 0 series: https://github.com/grafana/grafana/discussions/38299
  - sorting/filtering: https://github.com/grafana/grafana/discussions/41104, https://github.com/grafana/grafana/discussions/38861, https://github.com/grafana/grafana/discussions/38305
- Y axis ticks
  - need to adjust auto-decimals better, to prevent looking like they repeat when exceeding 3 decimals. somewhat intertwined with https://github.com/grafana/grafana/issues/35838
  - y auto-scaling needs to select top and bottom ticks better so they're always at the graph edges. needed for small-height panels. https://github.com/grafana/grafana/issues/39359

what else?

**Comment by simPod** [comment] 2022-05-19 11:17
@leeoniya thanks for input! I propose to create new epic issue so your team can do some triaging there? Followup of https://github.com/grafana/grafana/issues/30564, that one was great.

There are issues with Viz:

- https://github.com/grafana/grafana/issues/46290
- https://github.com/grafana/grafana/issues/46273

Z-index used to work better https://github.com/grafana/grafana/issues/47064

Setting legend width https://github.com/grafana/grafana/pull/49126

Weird behaviour of axes scale for 0-0.1 percent unit https://github.com/grafana/grafana/issues/46271#issuecomment-1127575633

Tooltip values ordering https://github.com/grafana/grafana/discussions/38305

Let's then collect the rest from issues and discussions and manage it in the epic to-be-created mentioned above.

**Comment by towolf** [comment] 2022-05-20 20:11
@zuchka could you please tell me why you closed my issue when it's not to duplicate? I'm referring to the issue mentioned above regarding toggling of legends.

**Comment by zuchka** [comment] 2022-05-20 22:01
@towolf I believe that adding this kind of parity between Graph (old) and TimeSeries ([in your case](https://github.com/grafana/grafana/issues/49005), the ability to toggle legends) is a feature request not a bug. I reopened the issue and labelled as such.

But as you can see this is part of a much larger discussion in the community, so I invited you to jump in on this thread 👍

**Comment by dprokop** [comment] 2022-05-26 08:42
@simPod thanks for raiing this issue. I've created the epic for better visibility going forward: https://github.com/grafana/grafana/issues/49670

Gonna close this issue now.

**Closed by dprokop** 2022-05-26 08:42 UTC
Labels: area/panel/timeseries

**Comment by simPod** [comment] 2022-05-26 08:44
Amazing, me very happy!
