### ISSUE TITLE
Dashboard links not updated on time-range or variable value change

### ISSUE THREAD

**Issue by jkreileder** [grafana/grafana#12660] opened 2018-07-19 16:36 UTC
Using 5.2.1:

When you have a dashboard link with 'Include time range' and 'Include variable values' checked, the link doesn't get updated when changing the time range or a variable, i.e. it still contains the time range and variable values it had initially.

**Comment by daniellee** [comment] 2018-07-20 09:55
Is this different from #12506 ? Guess it is another edge case for this issue.

**Comment by marefr** [comment] 2018-07-23 07:37
Duplicate of #12506  

Fix will be included in the next Grafana release (5.2.2) or you can use a nightly build

**Closed by marefr** 2018-07-23 07:37 UTC
Labels: needs investigation
