### ISSUE TITLE
Grafana is raising an error on IE11 (ProdData plugin failedError: Loading chunk 44 failed.)

### ISSUE THREAD

**Issue by lioncedric** [grafana/grafana#21557] opened 2020-01-17 09:55 UTC
**What happened**:
When you open a dashboard with charts in it a red  popup appear saying 
ProdData plugin failedError: Loading chunk 44 failed.
Then the chart in not rendered

**What you expected to happen**:
The charts to be rendered

**How to reproduce it (as minimally and precisely as possible)**:
just open a dashboard with charts

**Anything else we need to know?**:
I downgraded to grafana 6.4.5 and this verstion works fine with iE11

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: Prometheus
- OS Grafana is installed on: RH6
- User OS & Browser: W10 - IE11
- Grafana plugins: None
- Others:

**Comment by marefr** [comment] 2020-01-17 18:04
Duplicate of #15754

**Comment by marefr** [comment] 2020-01-17 18:04
Please refer to [requirements](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers)

**Closed by marefr** 2020-01-17 18:04 UTC
