### ISSUE TITLE
Unable to export dashboard with "all" selected for datasource variable

### ISSUE THREAD

**Issue by LDaneliukas** [grafana/grafana#16540] opened 2019-04-12 06:56 UTC
**What happened**: Received an error when attempting to export a dashboard with the option "Export for sharing externally" enabled when using a variable for the datasource with "all" selected.
```json
{
  "error": {
    "message": "Datasource named $__all was not found"
  }
}
```

**What you expected to happen**: Expected to received the dashboard json.

**How to reproduce it (as minimally and precisely as possible)**: 
- Create a dashboard with a variable for the datasource and "Include All option" enabled.
- Select the "All" option in the variable for the dashboard.
- Attempt to export it by selecting "Export for sharing externally" and clicking "View Json"
![image](https://user-images.githubusercontent.com/10710427/56017626-8be9fd00-5d08-11e9-929b-921ed2e57fe1.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.1.3 (9504db8)
- Data source type & version: Prometheus 2.6.0
- OS Grafana is installed on: Docker container
- User OS & Browser: Chrome on Fedora 29
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment] 2019-04-12 07:16
problem should be somewhere in this file: 
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/DashExportModal/DashboardExporter.ts#L69

**Comment by psschand** [comment] 2019-05-05 15:05
I'm not able to reproduce this error in the latest build from the master branch.
@LDaneliukas can you confirm?

**Comment by LDaneliukas** [comment] 2019-05-06 06:14
@psschand, yes I am able to reproduce it with `Grafana v6.1.6 (cf9cb45)`.

Note, that you have to have the "all" option selected for the datasource variable and the checkbox for "Export for sharing externally" has to be ticked, if it's not - the issue doesn't reproduce.

**Comment by hugohaggmark** [comment] 2020-11-11 10:18
Closing this issue as I can't repro it on Grafana v7.3.1 (6668161a88) and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2020-11-11 10:18 UTC
Labels: area/dashboard/templating, beginner friendly, help wanted, type/bug, version/6
