### ISSUE TITLE
"Failed to look up user based on cookie" logger=context error="user token not found"

### ISSUE THREAD

**Issue by Knaky41** [grafana/grafana#42366] opened 2021-11-26 12:30 UTC
**What happened**:

We're unable to navigate between the pages of Grafana, there is an issue to authenticate the user with the browser cookie.

We're using the latest grafana version on docker v8.2.5 (b57a137acd), with LDAP authentification + mysql cluster database. We checked on the browser that a cookie is well added to the session but if we change on another grafana webpage, we're logged out and the error message above.

**What you expected to happen**:

Be able to nagivate between pages while maintening authentication.

**How to reproduce it (as minimally and precisely as possible)**:

Install the latest version of Grafana with Mysql cluster as back-end data source.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.2.5 (b57a137acd)
- Data source type & version: 
- OS Grafana is installed on: Docker over Ubuntu 18
- User OS & Browser: Firefox & Chrome on Windows 10
- Grafana plugins: None
- Others: None

**Comment by Knaky41** [comment] 2021-11-26 14:22
Hi, we stopped 2 nodes of our 3 MySQL cluster and it seems to be working fine now. We'll try to check if it's related to replication or GTID...

**Comment by marefr** [comment] 2021-11-26 16:51
Duplicate of #13497

**Closed by marefr** 2021-11-26 16:51 UTC
