### ISSUE TITLE
adhoc filter variables vanished on first save after a 8.2 -> 8.3 migration.

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#43495] opened 2021-12-23 09:33 UTC
**What happened**:

We have several dashboards with a single data source (Elasticsearch) and an ad-hoc filter variable. On first save after 8.3 adoption, adhoc filter is removed by schema migration. 

Adhoc filter variable is simply gone and must be explicitly re-created.

**What you expected to happen**:

Adhoc filter should have been migrated.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with an adhoc filter using 8.2. 
2. Upgrade to 8.3
3. Open the dashboard and save it.
4. Observe adhoc filter is gone. Comparing versions confirm that filter was removed. 

**Anything else we need to know?**:

This might be related to https://github.com/grafana/grafana/issues/43472. My guess is that migration doesn't know how to link an adhoc filter to a data source and simply remove it.

![image](https://user-images.githubusercontent.com/1764725/147214024-00a9c8b2-bb34-4192-99d3-bc42d77cb9e2.png)

![image](https://user-images.githubusercontent.com/1764725/147213551-4e337c9d-4ebc-4b8f-be67-3e81d65f0a4f.png)

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Elasticsearch

**Comment by feuerrot** [comment] 2021-12-28 12:32
We've got a similar issue, which occured after the update from 8.2.7 to 8.3.3: Saving a specific dashboards removes every adhoc/textbox variable.

![gh0](https://user-images.githubusercontent.com/150068/147566477-40494a28-5d87-4ba4-af17-e94222e6d1e5.png)
![gh1](https://user-images.githubusercontent.com/150068/147566478-82a9eb7e-cbb4-4ce4-9542-bfadc232b895.png)

Environment:
* Grafana version: 8.3.3
* Data source type & version: Clickhouse 2.3.1

**Comment by marefr** [comment] 2022-01-17 13:32
Duplicate of #43184

**Closed by marefr** 2022-01-17 13:32 UTC
Labels: area/dashboard/templating, needs investigation, area/dashboard/schemas

**Comment by hugohaggmark** [comment] 2022-01-17 13:42
I think this is fixed by https://github.com/grafana/grafana/pull/43263. Before this fix the migration silently fails and it looks like the adhoc variable is missing from the dashboard json. The fix will be released Grafana 8.3.4.
