### ISSUE TITLE
Azure Monitor Plugin not show Configurations fields

### ISSUE THREAD

**Issue by faCalegari** [grafana/grafana#12708] opened 2018-07-24 17:25 UTC
Please include this information:
### What Grafana version are you using?
v5.2.1 (commit: 2040f61)
### What datasource are you using?
Azure Monitor 0.1.1
### What OS are you running grafana on?
Ubuntu 14.04.5
### What happened instead?
the Azure Monitor config page don't show the configurations fieds
### Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on 

warning rootScope onAppEvent called without localscope
 Failed to load resource: the server responded with a status of 401 (Unauthorized)
 Plugin component error Error: Fetch error: 401 Unauthorized
  Instantiating
  Loading https
  Instantiating

**Comment by marefr** [comment] 2018-07-24 19:43
Duplicate of #12551. Will be released (soon) in upcoming 5.2.2 release

**Closed by marefr** 2018-07-24 19:43 UTC
