### ISSUE TITLE
tencentcloud-monitor-app plugin's datasource not available in Grafana < 7.3

### ISSUE THREAD

**Issue by jamesxwang** [grafana/grafana#33116] opened 2021-04-19 09:21 UTC
**What happened**: Datasource not installed for `tencentcloud-monitor-app` plugin in Grafana version 7.0 & 7.1 & 7.2.

**What you expected to happen**: Support the `tencentcloud-monitor-app` plugin in Grafana version >= 7.0.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use the compose file below:
```yaml
---
version: '3'

services:
  grafana-730:
    image: grafana/grafana:7.3.0
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=tencentcloud-monitor-app
  grafana-715:
    image: grafana/grafana:7.1.5
    ports:
      - '3001:3000'
    environment:
      - GF_INSTALL_PLUGINS=tencentcloud-monitor-app
```
2. docker-compose up
3. Enable the plugin 
![image](https://user-images.githubusercontent.com/36892657/115212255-e22d7a00-a132-11eb-9975-2f441aae9542.png)
4. Search datasource `tencent`
![image](https://user-images.githubusercontent.com/36892657/115212315-f3768680-a132-11eb-9763-720b1f54e2ae.png)

In http://localhost:3000/, Datasource is available while in http://localhost:3001/ is not.

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: 7.1.x
- Data source type & version: plugin built-in datasource
- OS Grafana is installed on: MacOS (irrelevant)
- User OS & Browser: MacOS & Chrome (irrelevant)
- Grafana plugins: tencentcloud-monitor-app
- Others: N/A

**Comment by hugohaggmark** [comment] 2021-04-19 11:52
Reproducable with the following error for Grafana 7.1.5, seems like the datasource part fails.
```
grafana    | t=2021-04-19T11:49:00+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana    | t=2021-04-19T11:49:00+0000 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
grafana    | t=2021-04-19T11:49:00+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"tencentcloud-monitor-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/tencentcloud-monitor-app/datasource
grafana    | t=2021-04-19T11:49:00+0000 lvl=info msg="Registering plugin" logger=plugins name="Tencent Cloud Monitor"
grafana    | t=2021-04-19T11:49:00+0000 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[plugin \"tencentcloud-monitor-datasource\" is unsigned]"
```

Not sure if we'll backport a fix for this, but I'm passing this on to @grafana/backend-platform

**Comment by aknuds1** [comment] 2021-04-19 12:21
Looks as if the issue is that the plugin is unsigned. Can you solve this by configuring plugins.allow_loading_unsigned_plugins as `tencentcloud-monitor-datasource`?

**Comment by jamesxwang** [comment] 2021-04-19 15:11
> Looks as if the issue is that the plugin is unsigned. Can you solve this by configuring plugins.allow_loading_unsigned_plugins as `tencentcloud-monitor-datasource`?

Hi Arve, I can confirm that the datasource is unsigned in Grafana < 7.3 and can load with `plugins.allow_loading_unsigned_plugins`

**Comment by aknuds1** [comment] 2021-04-19 15:58
Closing the issue then, as it's not a Grafana bug.

**Closed by aknuds1** 2021-04-19 15:58 UTC
Labels: area/plugins, area/plugins/app, needs more info

**Comment by jamesxwang** [comment] 2021-04-20 01:42
@marcusolsson Would resign the MANIFEST.txt solve this issue? as it is not a Grafana bug.

**Comment by aknuds1** [comment] 2021-04-20 06:35
BTW do you mean that tencentcloud-monitor-app is only detected as unsigned in Grafana versions from 7.0.x up to and including 7.2.x? After realizing that might be what you mean, I checked v7.3.x and v7.2.x and it does look that way. However, we don't provide unpaid support for those versions so you would have to upgrade to v7.3.x or higher to fix the issue.

**Comment by marcusolsson** [comment] 2021-04-20 13:11
It seems that for versions prior to 7.3 the app plugins need to provide a signature for each bundled plugin in addition to the signature for the app plugin. From 7.3, bundled plugins uses the same signature as the app plugin.

My first thought would be to add a signature to the bundled plugins, but I'm not sure whether that would break the plugin in recent versions of Grafana. @wbrowne might know.
