### ISSUE TITLE
TimeSeries: timestamp display issues

### ISSUE THREAD

**Issue by Knocks83** [grafana/grafana#37873] opened 2021-08-13 11:15 UTC
**What happened**:
When moving the mouse between points, if you go to a point before the last one you highlighted, it shows a wrong timestamp (probably toe one of the point after)

**What you expected to happen**:
Show the right timestamp

**How to reproduce it (as minimally and precisely as possible)**:
With at least 3 points, hover on the first one, go to the second one and then go back to the first one.

**Anything else we need to know?**:
As you'll see in the video there's also another bug: when you hover a point, move the cursor outside the work zone of the tooltip and then hover the same point, it won't show that point. If you want, I can open another issue for that.

I'm attaching a video.
https://user-images.githubusercontent.com/22529815/129348391-1f398cdb-4b46-4e16-9f70-c17e3bf9d830.mp4

As always, that's the panel JSON:
```
{
  "id": 2,
  "gridPos": {
    "h": 19,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "timeseries",
  "title": "Environment",
  "datasource": "Localhost",
  "pluginVersion": "8.0.0-beta1",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 10,
        "gradientMode": "none",
        "spanNulls": 600000,
        "showPoints": "never",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "Temperature",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false,
          "graph": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "axisWidth": 60,
        "lineStyle": {
          "fill": "solid"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "mappings": [],
      "decimals": 1,
      "max": 40,
      "min": 10,
      "unit": "celsius"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Temperature"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "red",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Humidity"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "max",
            "value": 100
          },
          {
            "id": "custom.axisLabel",
            "value": "Humidity"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-blue",
              "mode": "fixed"
            }
          },
          {
            "id": "custom.axisPlacement",
            "value": "right"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "External Temperature"
        },
        "properties": [
          {
            "id": "unit",
            "value": "celsius"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-red",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "External Humidity"
        },
        "properties": [
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "custom.axisPlacement",
            "value": "right"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "light-blue",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "multi"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": [
        "lastNotNull",
        "max",
        "min"
      ]
    }
  },
  "targets": [
    {
      "alias": "Temperature",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "none"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "environment",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"temperature\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
      "rawQuery": false,
      "refId": "Temperature",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "temperature"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "Humidity",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "none"
          ],
          "type": "fill"
        }
      ],
      "measurement": "environment",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"value\") FROM \"Humidity\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
      "rawQuery": false,
      "refId": "Humidity",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "humidity"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "External Temperature",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "none"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "ext_environment",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"temperature\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
      "rawQuery": false,
      "refId": "External Temperature",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "temperature"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "External Humidity",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "none"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "ext_environment",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "SELECT mean(\"value\") FROM \"Humidity\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
      "rawQuery": false,
      "refId": "External Humidity",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "humidity"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "transparent": true
}
```

I'm also attaching the data. It's different from what I showed in the video but the bug still happens.
[Environment-data-as-seriestocolumns-2021-08-13 13 11 16.csv](https://github.com/grafana/grafana/files/6982007/Environment-data-as-seriestocolumns-2021-08-13.13.11.16.csv)

**Environment**:
- Grafana version: 8.1.0-beta3
- Data source type & version: InfluxDB 1.8.6
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Frefox on Windows 10

**Comment by leeoniya** [comment] 2021-08-13 13:46
Duplicate of https://github.com/grafana/grafana/issues/37798.

please try 8.1.1.

**Closed by leeoniya** 2021-08-13 13:46 UTC
