### ISSUE TITLE
Grafana 2.0.2 - 401 Unauthorized

### ISSUE THREAD

**Issue by anthonyhaussman** [grafana/grafana#1861] opened 2015-04-23 09:10 UTC
Similar to the issue #1667, when i try to save a dashboard after some time grafana returns Unauthorized:
```
2015/04/23 08:59:27 [I] Completed /api/dashboards/db/ 401 Unauthorized in 340.803228ms
2015/04/23 08:59:29 [I] Completed /api/dashboards/db/ 401 Unauthorized in 1.751473952s
```
The issue appears from firefox or chrome.

On firefox with devtools :
```
POST 
http://graphite-cdn.stcon.wan/grafana/api/dashboards/db/ [HTTP/1.1 401 Unauthorized 5ms]

Object { data: Object, status: 401, headers: eb/<(), config: Object, statusText: "Unauthorized" }
e/<() app.6e379bdb.js:10
bb/this.$get</<() app.6e379bdb.js:10
i() app.6e379bdb.js:10
j/<() app.6e379bdb.js:10
Rb/this.$get</l.prototype.$eval() app.6e379bdb.js:12
Rb/this.$get</l.prototype.$digest() app.6e379bdb.js:12
Rb/this.$get</l.prototype.$apply() app.6e379bdb.js:12
h() app.6e379bdb.js:10
q() app.6e379bdb.js:10
kb/</u.onload()

Object { message: "Access denied", severity: "warning" } app.6e379bdb.js:10:24424
e/<() app.6e379bdb.js:10
bb/this.$get</<() app.6e379bdb.js:10
f/j<() app.6e379bdb.js:12
g() app.6e379bdb.js:9
Ta/m.defer/c<()
```

I use grafana with a graphite backend and with a proxypass via apache.
If I restart the browser, it starts working again.

**Comment by torkelo** [comment] 2015-04-23 09:29
what version of grafana are you using? Similar issue was fixed in beta3

**Comment by anthonyhaussman** [comment] 2015-04-23 09:33
The last stable release => Grafana v 2.0.2.

**Comment by imkarthikk** [comment] 2015-04-25 05:53
Even I'm facing this same issue. The issue has been existing since Grafana v 2.0.1

**Comment by imkarthikk** [comment] 2015-04-27 14:48
@torkelo Do you think you can help us with this issue? Do you need the logs?

**Comment by torkelo** [comment] 2015-04-27 15:05
What session store are you using?

**Comment by imkarthikk** [comment] 2015-04-27 15:06
Graphite as the the data store.

**Comment by torkelo** [comment] 2015-04-27 15:07
No I mean Grafana session store?  (can be file based by default, or mysql, postgres or redis)

**Comment by imkarthikk** [comment] 2015-04-27 15:07
Oops. Sorry. Grafana session store with all the default options.

**Comment by torkelo** [comment] 2015-04-27 15:11
ok, I would suggest moving to mysql, redis or postgres, if you have any of those services that you can use or setup easily. I think this issue is related to a sync bug in the file session store (working on a fix, but might take a few weeks)

**Comment by imkarthikk** [comment] 2015-04-27 15:20
Cool then. I'll move to Redis or mySQL then. Thank you for the suggestion @torkelo . Do we have that migration in the documentation?

**Comment by torkelo** [comment] 2015-04-27 15:21
@imkarthikk http://docs.grafana.org/installation/configuration/#session

**Comment by imkarthikk** [comment] 2015-04-27 15:22
Awesome. Thanks. :)

**Comment by imkarthikk** [comment] 2015-05-01 16:38
@torkelo : Sorry to bother you once more. Just wanted to check with you if this configuration is correct: 

```
[session]
# Either "memory", "file", "redis", "mysql", default is "memory"
provider = mysql

# Provider config options
# memory: not have any config yet
# file: session dir path, is relative to grafana data_path
# redis: config like redis server addr, poolSize, password, e.g. `127.0.0.1:6379,100,grafana`
# mysql: go-sql-driver/mysql dsn config string, e.g. `user:password@tcp(127.0.0.1)/database_name`
provider_config = grafana:Grafana123@tcp(127.0.0.1)/grafana
```

Right after changing these parameters in `/etc/grafana/grafana.ini`, Grafana does not start. Here's the log that I have:

```
2015/05/01 16:30:10 [I] Starting Grafana
2015/05/01 16:30:10 [I] Version: 2.0.2, Commit: v2.0.2, Build date: 2015-04-22 15:51:50 +0000 UTC
2015/05/01 16:30:10 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/05/01 16:30:10 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/05/01 16:30:10 [I] Migrator: Starting DB migration
```

**Comment by torkelo** [comment] 2015-05-01 16:43
@imkarthikk that is very strange, cant see what is wrong, I know many use mysql as session store. 

Btw, you need to create the table (and database, since you are still using sqlite3 for the main database)
http://docs.grafana.org/installation/configuration/#session

**Comment by imkarthikk** [comment] 2015-05-01 16:57
The tables were created. Can it be because I upgraded from 2.0.0beta to stable?

**Comment by torkelo** [comment] 2015-05-01 17:00
Do you have any github or google oauth? Try commenting out things in the config file. The only case I have seen where i hangs like that was due to a config issue, but that config issue hang should have been fixed.

**Comment by imkarthikk** [comment] 2015-05-01 17:04
I have Github auth enabled. Let me check after disabling it. Right now, I don't have much data in production, I wouldn't mind doing a clean install of Grafana. But I wanted to solve this, since it might help someone.

**Comment by svetomir** [comment] 2015-05-12 18:44
@imkarthikk

try adding mysql port:
provider_config = `grafana:Grafana123@tcp(127.0.0.1:3306)/grafana`

**Comment by imkarthikk** [comment] 2015-05-13 10:54
I finally got this to work today. Had to delete the DB and start Grafana again. But obviously, I think its because of the migrations from the beta to the stable release. It works just fine now. With `mysql`

**Comment by vchekan** [comment] 2015-05-20 19:00
2.0.2, from official rpm.
I am logged in as "admin", and I can navigate around without problems, except when I am trying to add a metric in the designer (influxdb-0.8). I am getting native browser prompt for password. It is caused by response header:
    
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 2592000
Content-Encoding: gzip
Content-Length: 49
Content-Type: text/plain
Date: Wed, 20 May 2015 18:54:02 GMT
WWW-Authenticate: Basic realm="influxdb"
X-Influxdb-Version: InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept


Ping *is successful* both before and after failed request.
I have created DB from grafana UI, set login/password and left access type as proxy.

**Comment by torkelo** [comment] 2015-05-20 19:02
looks like InfluxDB is configured to use basic auth? Have you enabled this in the data source edit page? (and specified user/pass)

**Comment by vchekan** [comment] 2015-05-20 19:49
Ah, solved this one. 
If credentials in DB configuration are set incorrect, than configuration dialog will not check it. 
Also, when grafana access DB with misconfigured credentials, it will pass 401 error to unsuspected user's browser and user would have little clue whee it is coming from.

So I would say: 
1. check access in DB config dialog
2. Do not pass 401 error to the user but rather some "misconfigured DB" message

If this sounds reasonable, I will create another bug report for it.

**Closed** 2015-10-10 15:48 UTC
