### ISSUE TITLE
In table view column overrides are unapplied to the right of the column that has "Hide in Table" override triggered

### ISSUE THREAD

**Issue by Owersun** [grafana/grafana#43361] opened 2021-12-20 14:04 UTC
**What happened**:

In table view overriding property "Hide in table" for a column and triggering it removes part of overrides from columns to the right of it

**What you expected to happen**:

"Hide in table" should just remove the column from the table and not affect adjust columns

**How to reproduce it (as minimally and precisely as possible)**:

Make a table, add overrides for columns, display color, threshold, colouring by threshold, value type, data link are good examples.
Add "Hide in table" override to the column in the center of the table, trigger it.
See that the overrides applied to columns to the right of the hidden column are unapplied and overrides to the left are still in place.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Prometheus 2.43
- OS Grafana is installed on: Docker container
- User OS & Browser: MacOS 12.1, Safari
- Grafana plugins: -
- Others: -

<img width="1920" alt="Bildschirmfoto 2021-12-20 um 15 00 12" src="https://user-images.githubusercontent.com/4807375/146779194-80c65833-aa58-4cdd-8b23-8daa8db7f917.png">
<img width="1920" alt="Bildschirmfoto 2021-12-20 um 15 00 31" src="https://user-images.githubusercontent.com/4807375/146779205-e048ecc0-a9f4-4691-884f-63fcdb977735.png">

**Comment by torkelo** [comment] 2021-12-20 14:19
duplicate of https://github.com/grafana/grafana/issues/43191

**Closed by torkelo** 2021-12-20 14:19 UTC
