### ISSUE TITLE
Defaulting stack-driver data source to GCE does not work (jwt is always the default)

### ISSUE THREAD

**Issue by webzakimbo** [grafana/grafana#43077] opened 2021-12-14 09:56 UTC
**What happened**:

I created a data source for grafana as follows:

```
    datasources:
    - name: Google Cloud monitoring
      type: stackdriver
      editable: true
      orgId: 1
      readOnly: false
      version: 1
      access: proxy
      jsonData:
        authenticationType: gce
```

When I access my Grafana instance, the system has picked up the datasource configuration and a Google Cloud Monitoring source is visible in the data source section, however it is defaulted to 'jwt' rather than 'gce'.

An Admin has to then manually change the datasource from jwt to gce so that the stackdriver/google cloud monitoring dashboards work.

The data source otherwise works - when I manually select 'gce' a test works (and my stackdriver graphs pull data).

As the default of gce is not correctly set this means that I cannot fully deploy my grafana instances automatically - manual intervention is required.

**What you expected to happen**:

When I access the datasource configuration as an admin and select "Google Cloud Monitoring", my data source should have defaulted to 'gce' and my dashboards should work without manual intervention as an admin.

**How to reproduce it (as minimally and precisely as possible)**:

Use the minimal data source configuration from the documentation as follows:

```
datasources:
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: gce
```

Then access Grafana (as an admin) -> datasources -> select google cloud monitoring.  It will have defaulted to 'jwt' rather than 'gce'.

**Anything else we need to know?**:

**Environment**:
- Grafana version:

Grafana v8.3.0 (914fcedb72) also just tried today's latest build Grafana v8.3.2 (afb9e8e5f3)

- Data source type & version:

google cloud monitoring

- OS Grafana is installed on:

Ubuntu

- User OS & Browser:

Mac OS & Chrome (also firefox, safari etc etc)

- Grafana plugins:

https://grafana.com/docs/grafana/latest/datasources/google-cloud-monitoring/

**Comment by Elfo404** [comment] 2021-12-14 11:16
Hello @webzakimbo thanks for reporting this.

I just tried to reproduce this but unfortunately I couldn't.

it works as expected for me with 

```
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: gce
```

![Screenshot 2021-12-14 at 11 06 02](https://user-images.githubusercontent.com/1170767/145987697-b7854141-8e57-46bf-93bd-d8f1b5c4182b.png)

can you think of anything else in your setup that might affect this? are you sure there are no typos in your actual configuration? are you restarting grafana after applying the changes? (just trying to rule out some options)

**Comment by webzakimbo** [comment] 2021-12-15 11:23
Hi @Elfo404 

Thanks for the quick response.

I'm not restarting grafana no - this is part of a kubernetes deployment, where the configuration gets mapped in prior to the service starting.

My full configuration looks as follows - 

```
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  org_id: 1
  url: http://prometheus-server
  is_default: true
  version: 1
  editable: false
- name: Google Cloud monitoring
  type: stackdriver
  editable: true
  orgId: 1
  readOnly: false
  version: 1
  access: proxy
  jsonData:
    authenticationType: gce
```
I know that my datasources configuration is being applied because:

* on the /datasources page I see the prometheus datasource defined above (and this works)
* on the /datasources page I see the stackdriver datasource, and removing this from the configuration above removes it from hostname/datasource - so is is being added from the configuration

It's just that this:

``
  jsonData:
    authenticationType: gce
```

Is ignored.

**Comment by webzakimbo** [comment] 2021-12-15 11:34
Just to add as well - when I manually change the authentication method to GCE in the UI, I can successfully test & save the configuration, and my dashboards work.

**Comment by sunker** [comment] 2021-12-16 08:13
Thanks for creating this issue @webzakimbo. 

I'm not able to reproduce this either. Can you check the grafana server log and see if there's any errors on startup? Do you know if this used to work in previous versions of grafana?

**Comment by webzakimbo** [comment] 2021-12-16 16:10
Nothing via the logs either I'm afraid.

Now this is interesting. I call the following API method to view the datasources:  curl -f user:pass@hostname/api/datasources.

I get the following back:

```
[{:id=>1,
  :uid=>"XXX",
  :orgId=>1,
  :name=>"Google Cloud monitoring",
  :type=>"stackdriver",
  :typeName=>"Google Cloud Monitoring",
  :typeLogoUrl=>
   "public/app/plugins/datasource/cloud-monitoring/img/cloud_monitoring_logo.svg",
  :access=>"proxy",
  :url=>"",
  :password=>"",
  :user=>"",
  :database=>"",
  :basicAuth=>false,
  :isDefault=>false,
  :jsonData=>{},
 ]
```
Note the empty jsonData above. I then *manually* via the API perform a curl PUT request to update the datasource, I get the following:

```
[{:id=>1,
  :uid=>"XXX",
  :orgId=>1,
  :name=>"Google Cloud monitoring",
  :type=>"stackdriver",
  :typeName=>"Google Cloud Monitoring",
  :typeLogoUrl=>
   "public/app/plugins/datasource/cloud-monitoring/img/cloud_monitoring_logo.svg",
  :access=>"proxy",
  :url=>"",
  :password=>"",
  :user=>"",
  :database=>"",
  :basicAuth=>false,
  :isDefault=>false,
  :jsonData=>{:authenticationType=>"gce"},
  :readOnly=>false},
```

**Comment by webzakimbo** [comment] 2021-12-16 16:24
I can also see that when I perform an update against a data source, it doesn't update the original datasource.yaml provisioning file - so I imagine that this file is used as a source only and then the data copied to the local db store?

I'm guessing that in my instance, jsonData is not being propagated when the config is processed.

**Comment by sunker** [comment] 2021-12-17 13:07
That is very strange. @grafana/backend-platform does this ring a bell to you? Have you had reports of problems provisioning data sources recently?

**Comment by marefr** [comment] 2021-12-17 13:51
Make sure to include this at the top of the yaml file as shown in the [docs](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file):'

```yaml
apiVersion: 1
```

**Comment by webzakimbo** [comment] 2021-12-20 09:24
OK - yes that fixed it.  Thanks :)

Would it be an idea to error trap in some way against the absence of that field and log an appropriate message?  It's odd that its absence would result in the part-installation of the stack-driver data source (and the full installation of the prometheus one) - most difficult to debug, as this thread attests.   

Thank you anyway for the assist.

**Comment by papagian** [comment] 2021-12-21 13:55
> OK - yes that fixed it. Thanks :)

🎉 

> Would it be an idea to error trap in some way against the absence of that field and log an appropriate message? It's odd that its absence would result in the part-installation of the stackdriver data source (and the full installation of the prometheus one) - most difficult to debug, as this thread attests.
> 

That is reasonable but we still support both versions (v0 with snake case properties v1 with camel case properties) and we would need to check this for each absent field whose case differs between v0 and v1.
I will close the issue for now and let's reconsider it if your request gets a lot of upvotes.

**Closed by papagian** 2021-12-21 13:55 UTC
Labels: needs investigation, datasource/GoogleCloudMonitoring
