### ISSUE TITLE
Debian packages not found during installation of Grafana agent

### ISSUE THREAD

**Issue by palok** [grafana/grafana#62559] opened 2023-01-31 10:45 UTC
Docker image build fails with the following error message:

`Failed to fetch https://apt.grafana.com/pool/main/g/grafana-agent/grafana-agent-0.30.2-1.arm64.deb  404  Not Found [IP: 151.101.2.217 443]`

Followed instructions on https://grafana.com/docs/agent/latest/set-up/install-agent-linux/

Relevant part of `Dockerfile`
```
# Install the Grafana Agent
RUN apt-get update && apt-get install -y gnupg
RUN mkdir -p /etc/apt/keyrings/
RUN wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list
RUN apt-get update \
    && apt-get install -y grafana-agent
```

**Comment by TrixterTheTux** [comment] 2023-01-31 10:58
This seems to also apply to grafana installations as well (issues with the apt repo itself?):
```
E: Failed to fetch https://apt.grafana.com/pool/main/g/grafana/grafana_9.3.6_amd64.deb  404  Not Found [IP: 151.101.130.217 443]
```

**Comment by alby6969** [comment] 2023-01-31 12:31
Same problem here on ubuntu server:

E: Failed to fetch https://apt.grafana.com/pool/main/g/grafana/grafana_9.3.6_amd64.deb  404  Not Found [IP: 151.101.194.217 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by ankurga** [comment] 2023-01-31 13:00
Same error happening for me as well.

**Comment by alecks3474** [comment] 2023-01-31 13:17
Same error on Debian 11 server

**Comment by dezzzmond** [comment] 2023-01-31 13:56
Same for me

**Comment by mellieA** [comment] 2023-01-31 16:35
Duplicate of https://github.com/grafana/grafana/issues/62544 

Hi all! Closing this as a duplicate, please join the conversation there

**Closed by mellieA** 2023-01-31 16:35 UTC
Labels: type/duplicate
