### ISSUE TITLE
[Feature request] Templating - Show/Hide repeating row based on metric value

### ISSUE THREAD

**Issue by Maahaax** [grafana/grafana#7682] opened 2017-02-28 08:11 UTC
Hello all!
I'm currently working on a dashboard which repeats rows based on the device name. Now it would be really great, if Grafana would be able to show/hide the complete row, if a specific value (based on a sub-metric of the template-var) is over 0. It is pretty similiar to #7529, but for rows and based on the value of a metric.

Thank you and thanks a million for the great tool that Grafana is!

**Comment by torkelo** [comment] 2017-02-28 09:09
duplicate of https://github.com/grafana/grafana/issues/5171

**Closed by torkelo** 2017-02-28 09:09 UTC
