### ISSUE TITLE
Showing 'Unsupported route' across Prometheus experience when Prometheus Rules api is not available

### ISSUE THREAD

**Issue by weng5e** [grafana/grafana#53021] opened 2022-07-31 05:19 UTC
**What happened**:
![image](https://user-images.githubusercontent.com/22308724/182011312-2f0d295e-2662-4c3e-85c9-f256349496b0.png)

After upgrading to Grafana 9.0.1, we are starting to see more warning banners in the Explore UI for Prometheus data source. The Prometheus data source we are using does not support '[Prometheus rules](https://prometheus.io/docs/prometheus/latest/querying/api/#rules)' and '[Prometheus querying metric metadata](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-metric-metadata)' api. Those warning banner seems very confusing and annoying. Although the explore UI can still work, however, the warning keep popping up. Is it possible to do not go through those APIs in the explore UI or do not pop up such warnings? Besides the explore UI, normal Prometheus dashboards may also trigger this confusing banner.

There seems like another issue that I have already configure the Prometheus data source to not use the 'Manage alerts via Alerting UI'. The explore UI is not respecting this toggle and keep calling the prometheus rules api. It seems like the [code (datasource.tsx) does not use the toggle value](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.tsx#L135) at all.

![image](https://user-images.githubusercontent.com/22308724/182011316-1f0fc771-46ec-4175-8ddd-9a5629f5507e.png)

![image](https://user-images.githubusercontent.com/22308724/182011308-6bb3f897-8966-413a-a2d3-7ab9027fefba.png)

![image](https://user-images.githubusercontent.com/22308724/182011293-8b5aeeb7-8760-4d04-9b66-ced76ba2cc59.png)

**What you expected to happen**:
The warning banner should not show. The Prometheus rules api and querying metric metadata api should not be called when not necessary.

**How to reproduce it (as minimally and precisely as possible)**:
Block the two Prometheus apis (probably add a proxy which will return 404) then add it in Grafana data source.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 9.0.1 to 9.0.4
- Data source type & version: Prometheus
- OS Grafana is installed on: docker image
- User OS & Browser:
- Grafana plugins: Prometheus
- Others:

**Comment by weng5e** [comment] 2022-07-31 05:22
Hi @taleena @timlevett, could you please help triaging this issue?

**Comment by zuchka** [comment] 2022-08-04 00:30
closing this as it is a duplicate of a support escalation. Both from Microsoft and same info/images:

https://github.com/grafana/grafana/issues/53021

**Closed by zuchka** 2022-08-04 00:30 UTC
Labels: datasource/Prometheus
