### ISSUE TITLE
Feature request: Stacking of series with missing values

### ISSUE THREAD

**Issue by Kuermel** [grafana/grafana#2912] opened 2015-10-09 12:35 UTC
Version: grafana_2.5.0-pre1_amd64.deb 8.10.2015 17:44:15

When you switch on stacking and a metric is on the edge NULL, all other values are not displayed.

![grafana2 5 elasticsearch stacking off](https://cloud.githubusercontent.com/assets/6574969/10393649/fd0d327c-6e91-11e5-9dbb-694c4dc51caa.jpg)

![grafana2 5 elasticsearch stacking on](https://cloud.githubusercontent.com/assets/6574969/10393648/fd0b96ba-6e91-11e5-82ca-f16484d4e39c.jpg)

**Comment by torkelo** [comment] 2015-10-10 18:41
this is not a bug, stacking requires all series have a null value, it wont stack null values. 

This limitation could be an issue for elasticsearch as its query language does not support inserting nulls/zeros for missing data points.

**Comment by torkelo** [comment] 2015-10-10 18:42
if you have null values you can change display option. Null point mode: to connected

**Comment by Jhors2** [comment] 2015-10-29 23:19
Is this a limitation that can possibly be lifted somehow?  I understand that creating missing key values could be a bit messy but ES and Druid don't have the ability to null fill values like other datasources can.

**Comment by torkelo** [comment] 2015-10-30 07:06
would love a fix, https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.stack.js#L57

**Comment by mwitkow** [comment] 2015-11-26 18:21
We've hit a similar issue with Prometheus. If there is a gap in data, stacking doesn't work properly.

**Comment by Elufimov** [comment] 2015-12-03 10:56
Same here. If we use filters for separating data and one of filter return null stacking is no longer working.

**Comment by alastrange** [comment] 2015-12-03 15:52
This will probably prevent us from leveraging Grafana, as our datasets can be sparse from interval to interval.  Kibana handles this as I would expect.  One of the datasets is missing data in the middle of the graph, which causes an unnatural slope on the grafana render, and all other data is omitted.

What about an option to indicate that missing datapoints on an interval should be considered 0?

![connected2](https://cloud.githubusercontent.com/assets/6774078/11565280/3fcc7b10-99ab-11e5-84d7-cdf645eb4af6.jpg)

**Comment by torkelo** [comment] 2015-12-03 18:01
@alastrange this is fixed in master where group by time has a min_doc_count: 0 which will introduce zeros for missing data.

**Comment by torkelo** [comment] 2015-12-03 18:01
or nulls (for values)

**Comment by ZhukovAlexey** [comment] 2016-06-03 15:31
>> if you have null values you can change display option. Null point mode: to connected
It doesnt' work anyway

![null_stacked](https://cloud.githubusercontent.com/assets/1679467/15783985/23178d18-29b9-11e6-86b7-7f59b8740c6f.png)

If the second metric is disabled than graph works 

![null_stacked_2](https://cloud.githubusercontent.com/assets/1679467/15784016/5196d770-29b9-11e6-8521-f55a17834936.png)

**Comment by benrubson** [comment] 2016-09-29 14:07
Hello,

Here is another example where _ps.sleep_, _ps.wait_ and _ps.run_ have a value every 30 seconds.
_ps.zomb_, which is always 0, only has a value every 5 minutes.
Metrics are from OpenTSDB, with `none` (or `zimsum`) aggregator.
15:44 and 15:49 stacks are the expected behaviour.
All other stacks are not correctly rendered, _ps.run_ (orange) should be at the top of _ps.wait_ (yellow), whatever the _ps.zomb_ value is.

![stack](https://cloud.githubusercontent.com/assets/6764151/18957176/65013916-865e-11e6-90d7-e901d0044290.png)

@torkelo, do you think this could be part of the next Grafana release ?

Many thanks 👍 

Ben

**Comment by benrubson** [comment] 2016-10-03 20:52
Would the fix consist in modifying the beginning of function [stackData](https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.stack.js#L57) (as may suppose @torkelo a few post above), so that instead of returning if value is missing, it will continue as if the value were 0 ?

**Comment by torkelo** [comment] 2016-10-04 04:26
Something like that, but nit sure it is that easy

**Comment by torkelo** [comment] 2016-10-04 05:47
tried to fix this, but is tricky. Some changes it requires in flot have undesired site effects, like all null values being handled as null. 

Will require more substantial changes to flot lib. 

problem 1) 
Flot when cleaning up data and detects null values will null out the timestamp (x-axis) value as well if the axis is marked as required. This change be changed here and mark the y-axis as not required:
https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js#L1128

But this causes all null values to be handled as 0, which makes missing data very hard to spot (and big breaking change). 

The other way to solve it is here, but complicated to do without strange side efffects and especially when the null values do not have a timestamp any more due to problem 1 
https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.stack.js#L102
By not

**Comment by benrubson** [comment] 2016-10-04 08:45
Thank you very much Torkel for your help trying to solve this 👍 

According to what you say, best place to find a fix seems to be jquery.flot.stack.js, to avoid big breaking change.

What about the following idea ?
_If the point with the same timestamp from the previous serie (the serie below) has a null value, assign it a 0 value._
We would then be sure all values for a specific timestamp are stackable.
We could have a null value at the very last point, but this should not be a problem.
However I'm not sure we can proceed this way.

**Comment by benrubson** [comment] 2016-10-05 10:21
Hello,

Solved with PR #6194 !

Ben

**Comment by benrubson** [comment] 2016-10-05 12:11
This bug correction also offers a new possibility : we can now deliberately avoid pushing 0 values, leading to less data pushed to the backend, which can in some circumstances be a good thing.

**Comment by benrubson** [comment] 2016-10-15 11:20
Solved by #6287 👍

**Comment by benrubson** [comment] 2016-10-15 11:23
This bug correction also offers a new possibility : we can now deliberately avoid pushing 0 values, leading to less data pushed to the backend, which can in some circumstances be a good thing.

There is however a drawback doing this with OpenTSDB, see https://github.com/OpenTSDB/opentsdb/issues/881.

**Closed** 2016-11-09 10:37 UTC
Labels: comp: panel/graph, P4: nice to have, state: help wanted (PR)
