### ISSUE TITLE
Binary Grafana releases for ARM64 / Linux

### ISSUE THREAD

**Issue by pavel-odintsov** [grafana/grafana#11682] opened 2018-04-20 17:28 UTC
Hello!

ARM64 is rising server platform and we're using it a lot. Any chance to get binary builds for Grafana on ARM64? 

Thank you!

**Comment by bergquist** [comment] 2018-04-23 06:10
Dupe of https://github.com/grafana/grafana/issues/11557

**Closed by bergquist** 2018-04-23 06:10 UTC
