### ISSUE TITLE
password policy enhancement (common password shall be rejected)

### ISSUE THREAD

**Issue by lm123** [grafana/grafana#15340] opened 2019-02-11 01:29 UTC
### What Grafana version are you using?
5.2.4

### What datasource are you using?
Sqlite3

### What OS are you running grafana on?
CentOS 7.x

Our customer asks to enhance on the password policy in Grafana, they desire the following features:
      blacklist common words/passwords

Do you have plan to do such enhancement? If Yes, when?
Can we contribute this enhancement?

**Comment by marefr** [comment] 2019-02-11 08:10
Duplicate of #12257

**Comment by marefr** [comment] 2019-02-11 08:12
Thanks. We try to keep the number of feature requests as low as possible and even though this request is more detailed than referred issue it's still suggest solving the same problem. I would recommend you to post your additional requests/details in referenced issue.

**Closed by marefr** 2019-02-11 08:12 UTC
