### ISSUE TITLE
Ability to export a dashboard (not just individual graphs)

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2935] opened 2015-10-12 23:16 UTC
It would be cool if there was a way to export an entire dashboard (i.e. all the graphs together) as a PNG.

Currently, you are only able to export individual graphs one by one.

**Comment by torkelo** [comment] 2015-10-12 23:20
dupe of https://github.com/grafana/grafana/issues/2085 :)

**Closed by torkelo** 2015-10-12 23:20 UTC

**Comment by victorhooi** [comment] 2015-10-12 23:25
Aha, whoops - that'll teach me for not making my search terms more specific...lol.

Sorry - I used "dashboard export" and skimmed the list quickly. Thanks!
