### ISSUE TITLE
Wrong axis precision with unit "Percent (0.0-1.0)"

### ISSUE THREAD

**Issue by dguendisch** [grafana/grafana#31519] opened 2021-02-26 16:44 UTC
**What happened**:

The axis precision for unit `Percent (0.0-1.0)` seems wrong when using manual decimals/precision.
The precision seems to correctly apply to the metric (which is between 0.0 and 1.0) but in the rendering of the y axis, the percentage has again the amount of decimals displayed although this percentage unit (0.0-1.0) actually multiplies the metric already by `100`, hence it should "loose" two precision decimals. The rendering however suggests wrongly that you have a higher precision.
See in these two examples how e.g. the decimals in the y-axis never make any sense (they give a wrong impression of the actual precision):

![image](https://user-images.githubusercontent.com/30311254/109328406-b63ff780-7859-11eb-94ec-6a635ca1212e.png)

and another example for precision/decimals of `2`:

![image](https://user-images.githubusercontent.com/30311254/109328696-08811880-785a-11eb-863d-a29a0ac42836.png)

**What you expected to happen**:
The axis precision for unit Percent (0.0-1.0) should reflect the manually selected precision/decimals and take into account that it already multiplies the metric by 100, so the precision in the axis needs to be lowered by 2 decimals.

**How to reproduce it (as minimally and precisely as possible)**:
See screenshots.

**Anything else we need to know?**:
I described the issue already in https://github.com/grafana/grafana/issues/31397 but mistakenly referred to the legend precision instead of the axis precision. Just wanted to ensure that this issue is known.

**Environment**:
- Grafana version: 7.4.1

**Comment by torkelo** [comment] 2021-02-27 16:20
Your screenshots show no bugs, it shows exactly the number of decimals you specified  

duplicate of https://github.com/grafana/grafana/issues/31397

**Closed by torkelo** 2021-02-27 16:20 UTC
