### ISSUE TITLE
[BUG] phantomjs render - Y axis labels not rotated to vertical in serverside rendered PNG

### ISSUE THREAD

**Issue by Kaacz** [grafana/grafana#6981] opened 2016-12-15 19:54 UTC
- Grafana version are you using? - 4.0.2
- What datasource are you using? - InfluxDB 1.1.1
- What OS are you running grafana on? - Linux/Debian last stable
- What did you do? - Graph -> Share -> Link -> Direct link rendered image
- What was the expected result?- Vertical Y axis Labels 
- What happened instead? - Horizontal Y axis Labels over graph
![yaxislabelgraph](https://cloud.githubusercontent.com/assets/7330896/21239751/8f06316c-c308-11e6-9848-6df7ee8578e8.png)
![yaxislabelphantomjs](https://cloud.githubusercontent.com/assets/7330896/21239750/8eff3196-c308-11e6-9caf-7ad2f9634a58.png)
PS: PNG render is best idea, will be good to have this fixed. Thanks.

**Comment by torkelo** [comment] 2016-12-16 06:27
duplicate of https://github.com/grafana/grafana/issues/6924

**Closed by torkelo** 2016-12-16 06:27 UTC

**Comment by torkelo** [comment] 2017-01-02 11:10
just a heads up this is now fixed in master (and in upcoming 4.1 stable)
