### ISSUE TITLE
Wrong representation of stacked series if one of them has no data

### ISSUE THREAD

**Issue by DEvil0000** [grafana/grafana#6220] opened 2016-10-10 10:17 UTC
* **I'm submitting a ...**
- [x] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.1
master
- What datasource are you using?
graphite
- What OS are you running grafana on?
ubuntu 14.04
- What did you do?
Rendering 10 series with "something.*.xx.value" in a graph. Some of them have gaps or no values at all.
If display is set to "null" and "not stacked" all series are rendered.
If display is set to "null" and "stacked" only some series are rendered
If display is set to "null as zero" and "stacked" all series are rendered again.
- What was the expected result?
I would expect all series should get rendered in any combination of the display config.
- What happened instead?
(Some) series with gaps are not rendered if display is set to "null" and "stacked"
To be more precise:
Legend is showing one series with no data for this timeframe. Every series after this is not rendered.

**IMPORTANT** If it relates to metric data viz:
- An image or text representation of your metric query

[null_and_stacked](https://picload.org/image/rdorirla/bildschirmfotovom2016-10-1012-.png)

[null_as_zero_and_stacked](https://picload.org/image/rdorirll/bildschirmfotovom2016-10-1012-.png)

**Comment by torkelo** [comment] 2016-10-10 11:35
null + 1 = null, that is the current way the stacking logic works (I know it sucks), there about 100 duplicate issues of other running into the same issue, please search before opening a new ticket :) 

dupe of https://github.com/grafana/grafana/issues/2912 
There is a potential fix on the way https://github.com/grafana/grafana/pull/6194

**Comment by torkelo** [comment] 2016-10-10 11:36
you can easily solve this in graphite by changing "null value" mode in display tab to "null as zero"

**Closed by torkelo** 2016-10-10 11:35 UTC

**Comment by DEvil0000** [comment] 2016-10-10 12:47
Was doing a search before but somehow I was not able to find those. The bug seams very similar and related but I am not sure if it is the same.

I do not want to display null as zero. It would give the impression of values being recorded but actually there are no recorded values so showing a gap is more correct (like in display "null" mode). But display "null" is not working as expected for stacking.

I understand that "null + 1" is a issue but showing all data series before the series with null values only but no series (with data) after the one with null (in stacked) seams very odd.
I have those ~13 series where 12 have data and one has mostly (or only) null values. But I do only see a few of the series in stacked (because of their order/every servies after the nulled one is not there).

How about change sorting in stacked mode. Ignore series with only nulled data and stack the series with most datapoints to the bottom?

**Comment by torkelo** [comment] 2016-10-10 13:16
Your welcomed to try to save it, the stacking logic is very complex as it has to deal with interpolation for points that are not aligned, and handling null values correctly for all cases is impossible, as depending how it's done some scenarios work great some other not so much. M

**Comment by benrubson** [comment] 2016-10-10 15:14
@DEvil0000 #6194 will solve your problem 👍 
Series will be correctly stacked without displaying null as zero (i.e. without adding new / not recorded points to the graph).
