### ISSUE TITLE
Different Time Periods In Dashboard Redux

### ISSUE THREAD

**Issue by haverdude** [grafana/grafana#26979] opened 2020-08-13 05:54 UTC
I too have a time period issue that is similar to what other people have previously posted in [Different Time Periods In Dashboard #171](https://github.com/grafana/grafana/issues/171), which is now closed (otherwise I'd post there)

I have two graphs of the same data. I want the top graph to be very flexible (relative / absolute time ranges, zoom, etc.), and the graph under it to always display the last 12h completely independent of what the dashboard time picker is set to or whether I have zoomed in on the graph above it.

Is this even remotely on the radar?

I really need to be able to search for past data in one graph, while the bottom graph _always_ shows what's happened recently, and I want to see these two views _simultaneously_.  Right now, if I zoom in on the upper graph, the bottom graph snaps to what the top graph is showing until I pick a relative time period in the dashboard time picker, which is _not_ the desired behavior.

**Comment by torkelo** [comment] 2020-08-13 06:13
duplicate of https://github.com/grafana/grafana/issues/22163

**Closed by torkelo** 2020-08-13 06:13 UTC
