### ISSUE TITLE
Slack notifications to use mrkdwn in messages

### ISSUE THREAD

**Issue by yeo-yeo** [grafana/grafana#35417] opened 2021-06-09 11:25 UTC
**What would you like to be added**:
Add `"mrkdwn_in": ["text"]` to the `attachment` property of the Slack notification payload
(https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifiers/slack.go#L287)

**Why is this needed**:
So Slack's mrkdwn syntax can be used to format the notification message (contained in the `text` property), e.g. you could display hyperlinks in a more user-friendly way, with syntax like: `<www.alongboringhyperlink.com/reallylongandconfusingtoread|Click here>`

https://api.slack.com/reference/messaging/attachments
https://api.slack.com/reference/surfaces/formatting

**Comment by pkolyvas** [comment] 2021-06-09 12:49
Hey @yeo-yeo, thanks for the feedback! This is duplicate of #23252 so I'm going to close it. 

If you'd be willing to thumbs-up or follow that issue it would be helpful for us. 

Note: also related to #5848

**Closed by pkolyvas** 2021-06-09 12:49 UTC

**Comment by llamafilm** [comment] 2024-02-16 00:41
I would also like to use markdown in Slack alerts.  Can this feature request be re-opened?
