### ISSUE TITLE
Dashboards: Ad-hoc filters do not apply to queries in `-- Mixed --` data source panels

### ISSUE THREAD

**Issue by cannonpalms** [grafana/grafana#86223] opened 2024-04-15 19:46 UTC
### What happened?

Ad-hoc filters are not applied to queries in a dashboard panel of `-- Mixed --` data source, even when the data source matches.

### What did you expect to happen?

I would expect any ad-hoc filter to apply on a query-by-query basis rather than a panel-by-panel basis.

### Did this work before?

I doubt this has ever worked, but I have not bisected.

### How do we reproduce it?

1. Define two data sources
2. Create a dashboard with two ad-hoc filters: one for each data source
3. Create a panel with `-- Mixed --` data source and two queries: one for each data source

The filters do not apply.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by axelavargas** [comment] 2024-05-29 10:40
This is a duplicate of https://github.com/grafana/grafana/issues/84673.

**Closed by axelavargas** 2024-05-29 10:40 UTC
Labels: area/dashboard
