### ISSUE TITLE
Improve Stat Panel Font Size

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#26430] opened 2020-07-17 22:11 UTC
**What would you like to be added**:

Hi, I couldn't post a good example here (had to cover the hostnames, lol) but it's enough to explain the issue.

![image](https://user-images.githubusercontent.com/43188411/87834482-39947600-c893-11ea-9da1-128e10afbf05.png)

1. Create a stat panel and use a long (more than 20 chars) tag as a name.
2. Make it multiple stat panels. (group by host for example)

Currently, all stat panels use same font size, I believe it sets the font size based on the longest name to make it fit. Bad thing is all names becomes smaller and hard to read. I think it would be better if each panel has independent dynamic font size.

**Also**, it would be better to use all the space when we select ```Text Mode (name)```. We may use ```wordwrap``` and display the text in more than one row with bigger font-size.

**Why is this needed**:

This will create better dashboards by covering more situations. A little bigger (dynamic) fonts size make it easy read to while current ones can become very tiny.

Edit: Also, there are cases where we need the name is more important than the value. Bigger name with smaller value option might be helpful and more flexible. So, "an option for users to configure font-size manually in the panel editor" would be a useful feature.

**Comment by torkelo** [comment] 2020-07-20 08:31
Yes, currently all stat panes align their size, as each having different size would make it quite distracting, 

dupe of #23305

**Closed by torkelo** 2020-07-20 08:31 UTC
