### ISSUE TITLE
Alert Migration failure

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#37366] opened 2021-07-29 16:37 UTC
**What happened**:

When upgrading to Grafana 8.0.6 and having many dashboard alerts migrate to the new alerting system, the ability to delete the alerts seems to have gone away.

For valid reasons on our end, the alerts that were migrated used data sources whose data no longer existed, so all of the alerts were constantly firing.

We then tried to delete the alerts through the new UX, which seemed to work, but the alerts continued to fire even after being deleted. Since then I have also deleted their dashboard counterparts, which also did not work. Clearing out the contact point list is the only way I could stop it from spamming my team. But even that seems to undo itself after a server restart.

I'm really not sure what is going on, but it seems like artifacts of those deleted alerts are sticking around, and they can't be accessed. Also, I believe server restarts are bringing the contact points back.

**What you expected to happen**:

If a migration to the new alerting system is triggered, it should be 100% controlled by the new UI. An alert migrating needs to clean up after itself, it should not be able to re-migrate again later. And deleting it form the new UI should make sure it never comes back, even after a server restart.

**Environment**:
- Grafana version: 8.0.6

**Comment by yuri-tceretian** [comment] 2021-12-09 22:45
I think that the reason why it keeps sending alerts after the rule is deleted is related to https://github.com/grafana/grafana/issues/39154. In other words, when user deletes an alert rule which is firing, Grafana removes the rule, cleans up the state but does not expire the firing alert in Alertmanager. Eventually, the Alertmanager expires the alert but it can take some time because the expiration interval is calculated as _three_ evaluation intervals, eg if the interval is 1 hour, the alert will be expired in 3 hours.

I think we can close it as a duplicate of https://github.com/grafana/grafana/issues/39154 which is being worked on.

**Comment by peterholmberg** [comment] 2022-01-27 09:08
closing as per @yuri-tceretian suggestion

**Closed by peterholmberg** 2022-01-27 09:08 UTC
Labels: needs investigation, prio/awaiting-more-evidence, area/alerting/unified
