### ISSUE TITLE
Grafana doesn't scroll when using Firefox's full-page screenshot tool

### ISSUE THREAD

**Issue by genebean** [grafana/grafana#19824] opened 2019-10-15 13:50 UTC
**What happened**:

While taking screenshots of dashboards using the builtin screenshot tool in Firefox I found that the "save full page" function was not able to scroll the Grafana web interface like it does on other pages which leads to not being able to get a single screenshot of an entire dashboard.

**What you expected to happen**:

I expect that the Grafana web interface will be scrollable by Firefox's tool

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Firefox and navigate to a Grafana dashboard that does not fully fit on the viewable portion of the screen
2. Click on the three dots at the end of the address bar and select "Take a Screenshot" as shown here:
   ![Screen Shot 2019-10-15 at 9 42 43 AM](https://user-images.githubusercontent.com/966789/66837123-7d3b0780-ef30-11e9-83d7-29ddae2c5b16.png)
3. Click "Save full page" as shown here:
   ![Screen Shot 2019-10-15 at 9 43 02 AM](https://user-images.githubusercontent.com/966789/66837137-80ce8e80-ef30-11e9-8e33-d593ec8463ca.png)

**Anything else we need to know?**:

This bug really hampers documenting processes and sharing examples.

**Environment**:
- Grafana version: 6.4.0
- Data source type & version: any
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: macOS and Firefox 69.0.1

**Comment by papagian** [comment] 2019-10-16 12:40
There is duplicate of this [issue](https://github.com/grafana/grafana/issues/13437).

**Closed by papagian** 2019-10-16 12:40 UTC
Labels: type/duplicate
