### ISSUE TITLE
Templating - Dynamic Datasources do not allow for multi-value configuration, no repeated panel support

### ISSUE THREAD

**Issue by alexmnyc** [grafana/grafana#9511] opened 2017-10-12 16:06 UTC
With current limited support for templating datasources, I am unable to create a template variable of datasource type with multi-value and All option to be used for templating repeated panels. That is a big problem. Thanks.

**Comment by torkelo** [comment] 2017-10-13 08:44
duplicate of https://github.com/grafana/grafana/issues/7492

**Closed by torkelo** 2017-10-13 08:44 UTC
