### ISSUE TITLE
Table Panel column content wrap - max column width

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#6516] opened 2016-11-09 12:19 UTC
* **I'm submitting a ...**
- [x] Feature request

- What Grafana version are you using? **v3.1.1**
- What datasource are you using? **Elasticsearch 2**
- What OS are you running grafana on? **Centos 7**
- What did you do? **Created a table panel to display mysql queries from an elasticsearch source**
- What was the expected result? **Expected to be able to be able to set the max column width so there is no need for horizontal scroll **
- What happened instead? **See below**
![grafanatablewrap](https://cloud.githubusercontent.com/assets/12910496/20138054/10efe0e2-a676-11e6-9e38-9f8fef8ce341.PNG)

Apologies, had to blank out most of the queries but you should get the idea.
It would be nice if we could set the wQuery column to be a certain width so instead of, for example, in the above image - there being 1 line, it would wrap around to 2 lines with a smaller width column. 

I had  a search here: https://github.com/grafana/grafana/search?utf8=%E2%9C%93&q=table+panel+column+width&type=Issues
But not sure if others are asking for exactly this and the PR is still open inwhich I noticed the column width option.

**Comment by torkelo** [comment] 2016-11-09 13:09
duplicate of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2016-11-09 13:09 UTC
