### ISSUE TITLE
User with global viewer permission but Edit permission on the dashboard not able to revert to older version using Dashboard history

### ISSUE THREAD

**Issue by gauravk48** [grafana/grafana#14397] opened 2018-12-07 17:55 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:

**Comment by gauravk48** [comment] 2018-12-07 18:00
What Grafana version are you using? v5.2.1
What datasource are you using? Not applicable
What OS are you running grafana on? Linux
What did you do? We have a user with Viewer role but he is part of the team which has edit permissions on a folder. So based on that he is able to create a dashboard inside that folder. But when he is trying to revert the dashboard to an older version using version history he is not able to do it, and it says access denied.

Example: User X is part of team T
Team T has edit access to folder named T
X being part of team T created a dashboard under folder T and made some commits. Now he is trying to revert back to an older version of dashboard, lets say revision 1 after he is on revision 4.
He gets access denied.

What was the expected result? Dashboard should revert to the older version
What happened instead? Nothing 
If related to metric query / data viz: No
Include raw network request & response: get by opening Chrome Dev Tools (F12, Ctrl+Shift+I on windows, Cmd+Opt+I on Mac), go the network tab.

**Comment by torkelo** [comment] 2018-12-07 19:42
thanks for reporting this, looks like restore action gets confused and thinks your moving the dashboard to another folder when restoring.

**Comment by marefr** [comment] 2018-12-10 08:39
Duplicate of #12926

**Closed by marefr** 2018-12-10 08:39 UTC
Labels: comp: permissions, type: bug

**Comment by gauravk48** [comment] 2018-12-10 16:42
Thanks for taking a look at my issue. Hope this gets resolved sooner.
