### ISSUE TITLE
Plugin with ID \"stackdriver\" already exists error log during Grafana upgrade from 6.6.2 to 7.1.3 version

### ISSUE THREAD

**Issue by VeenaThimmegowda** [grafana/grafana#27209] opened 2020-08-26 06:07 UTC
**What happened**: Upgraded Grafana rpm from 6.6.2 to 7.1.3 version. After upgrade in the grafana logs **"Plugin with ID \"stackdriver\" already exists]"** error was seen.

**What you expected to happen**: After upgrade there shouldn't be any error logs. 

**How to reproduce it (as minimally and precisely as possible)**:
1. In any standalone VM install grafana 6.6.2 rpm 
2. upgrade grafana to 7.1.3 rpm
3. once upgrade is done , check the grafana logs ( /var/log/grafana/grafana.log ).

**t=2020-08-26T05:24:55+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="Failed to register plugin: Plugin with ID \"stackdriver\" already exists" pluginPath=/usr/share/grafana/public/app/plugins/datasource/stackdriver
t=2020-08-26T05:24:55+0000 lvl=warn msg="Some plugins failed to load" logger=plugins errors="[Failed to register plugin:\n    github.com/grafana/grafana/pkg/util/errutil.Wrap\n        /home/jenkins/workspace/CTO/CSF/FaultAndPerformanceManagement/CSF-CPRO-GRAFANA/Grafana-test/LX/build/src/github.com/grafana/grafana/pkg/util/errutil/errors.go:18\n  - Plugin with ID \"stackdriver\" already exists]"**

**Anything else we need to know?**: 

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: stackdriver / cloud-monitring
- OS Grafana is installed on: CentOS Linux 7
- User OS & Browser: n/a
- Grafana plugins: stackdriver / cloud-monitring
- Others: n/a

Since stackdriver datasource plugin is renamed to google cloud-monitoring is there any migration steps should be followed during Grafana upgrade.

[grafana.log](https://github.com/grafana/grafana/files/5127903/grafana.log)

**Comment by saipavankumarreddy** [comment] 2020-08-28 09:39
We are also upgrade Grafana from 6.6.2 to 7.1.3 facing the similare issue. In Grafana logs it is showing like this "Plugin with ID "stackdriver" already exists]" error was seen.

**Comment by marefr** [comment] 2020-08-31 09:15
Do you have both a directory named `cloud-monitoring` and `stackdriver` in `/usr/share/grafana/public/app/plugins/datasource/`? If so, the current workaround is to delete the stackdriver directory.

**Comment by VeenaThimmegowda** [comment] 2020-09-02 06:11
Yeah , we do have both **cloud-monitoring** and **stackdriver** directories in _/usr/share/grafana/public/app/plugins/datasource/_ path.
Before upgrade i've manually deleted stackdriver directory, so no error was found after upgrade.

**Comment by marefr** [comment] 2020-09-07 16:56
@VeenaThimmegowda thanks. What command did you run when upgrading?

I was under the impression that upgrading RPM would remove all existing files and add the new ones (except changed configuration files of course). Maybe we have to add some logic to the RPM scripts to delete the stackdriver directory if it's there?

**Comment by VeenaThimmegowda** [comment] 2020-09-10 11:24
Hi @marefr
I'm using below cmd to upgrade 
**rpm -Uvh grafana-7.1.3-1599723981.x86_64.rpm**

**Comment by sunker** [comment] 2021-02-03 08:51
@marefr @papagian do you know if this is fixed? If not, can we do anything to solve this?

**Comment by papagian** [comment] 2021-02-03 09:30
The problem is for some reason the rpm didn't upgrade cleanly and ended it up with both the old and the renamed directory. I'm not at all familiar with building rpm packages and I didn't find time to go deeper but even though back then [we didn't use](https://app.circleci.com/pipelines/github/grafana/grafana/13482/workflows/4043a249-cd4b-4492-991c-bff78f1d7462/jobs/524667) the build pipeline that we use today, the command for creating the rpm is almost the same (only the architecture used to be `amd64` and now is `armhfp`). So I assume that this can be an issue even today.

**Comment by sunker** [comment] 2021-02-03 12:01
Okay, thanks for info. This seems like a CI problem so I'll remove this from cloud datasources board. Thanks!

**Comment by jessabe** [comment] 2021-08-16 13:16
For all those curious about this, the workaround isn't the best but it works-- and as there's not a lot of traction on this bug, we'll be closing this for now. Please reach out though if you need more help. Thanks!

**Closed by jessabe** 2021-08-16 13:16 UTC
Labels: type/bug, area/plugins, type/build-packaging, area/backend, datasource/GoogleCloudMonitoring
