### ISSUE TITLE
 Graph is not visible in a certain time zone.

### ISSUE THREAD

**Issue by Mon-terr** [grafana/grafana#12684] opened 2018-07-23 00:24 UTC
Read before posting:

Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue.
Checkout FAQ: https://community.grafana.com/c/howto/faq
Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50
Please include this information:

What Grafana version are you using?
Grafana 5.2.0

What datasource are you using?
Elasticsearch

What OS are you running grafana on?
Ubuntu 16.04

What did you do?
Time Graph

What was the expected result?
Graph is always output well

What happened instead?
Hi, torkelo.

The data from 1:00 am to 9:00 am is not displayed on the graph every day. And by 9 o'clock, all the data from 1:00 to 9:00 will be visible. It is no data message.

I've tried with comments you gave me before, but it does not work well.
(your comments 'here is the feature request for time of day restrictions: #6592')

I add pictures this time.
![9 -](https://user-images.githubusercontent.com/33366914/43051785-86dc4e2c-8e59-11e8-810e-8ac8624f6071.PNG)
![9 -](https://user-images.githubusercontent.com/33366914/43051786-870ca450-8e59-11e8-907e-9eaf2b2f1ae0.PNG)

Thanks!

**Comment by marefr** [comment] 2018-07-23 12:35
Duplicate of #6222

**Closed by marefr** 2018-07-23 12:35 UTC
