### ISSUE TITLE
[Feature request] Add color to table column value when the type is string

### ISSUE THREAD

**Issue by wei-hai** [grafana/grafana#8693] opened 2017-06-22 22:11 UTC
Please include this information:
- What Grafana version are you using?
4.3.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
centOS 7

When you select values into table, you can set color to column value when the type is number, can we support adding color when the value is String? For example, when I add deployment result into influxdb, the value could be `success` or `failure`, when the value is `failure` I would like to highlight the cell in red. I suggest using regex to match and set color to string value.

project_name|build_number|build_result
|--------------|-------------|-----------|
abc|1|success
abc|2|failure `in red color`

**Comment by torkelo** [comment] 2017-06-25 07:36
duplicate of https://github.com/grafana/grafana/issues/3601

**Closed by torkelo** 2017-06-25 07:36 UTC
