### ISSUE TITLE
Time series tooltip colors breaks after refresh

### ISSUE THREAD

**Issue by tomasbedrich** [grafana/grafana#39506] opened 2021-09-22 09:29 UTC
![screenshot 2021-09-22 at 11 05 46](https://user-images.githubusercontent.com/4974343/134318777-d5259721-b840-42af-a12e-80bba69c66ed.jpg)

**What happened**:
Tooltip colors doesn't match plot+legend colors after refreshing data for a panel.

**What you expected to happen**:
All colors (tooltip, legend, plot) to match all the time.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new dashboard.
2. Add a panel of "Time series" type.
3. Add two series.
4. Switch tooltip to "All" mode (optional step – it also breaks for "Single" mode, but it's better visible in "All" mode).
5. Refresh dashboard without refreshing the browser page (either press "Refresh dashboard" button, or change time range).
6. Tooltip colors shuffles.

**Anything else we need to know?**:
none

**Environment**:
- Grafana version: Grafana v8.0.5 (cbb2aa5001)
- Data source type & version: Prometheus (builtin)
- OS Grafana is installed on: ubuntu-focal-20.04-amd64*
- User OS & Browser: Chrome 93 on macOS (Catalina)
- Grafana plugins: none
- Others: none

**Comment by leeoniya** [comment] 2021-09-22 11:26
Duplicate of https://github.com/grafana/grafana/issues/36385

this is fixed in recent versions.

**Closed by leeoniya** 2021-09-22 11:26 UTC
