### ISSUE TITLE
show context not available when using regex `or`

### ISSUE THREAD

**Issue by lazedo** [grafana/grafana#56427] opened 2022-10-05 21:49 UTC
**What happened**:
`Show Context` not available
**What you expected to happen**:
`Show Context`  to be available
**How to reproduce it (as minimally and precisely as possible)**:
use the regex operator `or` ( | ) to select more than one value
**Anything else we need to know?**:
adding anything with double quote at the beginning does work
creating multiple queries with each regex expression is ok but if we have multiple values to search that could be a bad ux experience
**Environment**:
grafan - Grafana version: 9.0.6 -> 9.1.7
- Data source type & version: loki
- OS Grafana is installed on: kubernetes
- User OS & Browser: windows/chrome

![image](https://user-images.githubusercontent.com/770988/194166945-fcce74bd-9bec-4e8f-be5b-b43ccec54f59.png)

![image](https://user-images.githubusercontent.com/770988/194167327-c36bdd9f-e41e-4507-9f54-9d64e81f7536.png)

**Comment by ivanahuckova** [comment] 2022-10-21 12:16
@lazedo I was able to reproduce this issue on v9.1.7, but it has been fixed on v 9.2.0. So as soon as you update your Grafana to v9.2+, the issue is going to be resolved. 🎉

**Closed by ivanahuckova** 2022-10-21 12:16 UTC
Labels: needs investigation, datasource/Loki
