### ISSUE TITLE
Thresholds Query

### ISSUE THREAD

**Issue by entrop92** [grafana/grafana#3594] opened 2015-12-23 14:45 UTC
Hi!

Some monitoring apps (icinga2) can push warn/crit/min/max to the DB.
It would be great, if it would be possible to handle these values in Thresholds. Right now it's possible to enter a constant for it, but why not a query? Sometimes these values can change dynamically and it's not handy to handle them with ordinary metrics (or it's required to be able to set a per-line style option like "Line Fill" and so on).

Best regards, Petr

**Comment by torkelo** [comment] 2016-01-07 18:55
dupe of https://github.com/grafana/grafana/issues/159

**Closed by torkelo** 2016-01-07 18:55 UTC
