### ISSUE TITLE
version check in settings page is wrong/ wrong plugin version in use?

### ISSUE THREAD

**Issue by JanHBade** [grafana/grafana#32841] opened 2021-04-09 12:42 UTC
Hello,

I am runnig a grafana (v7.5.3) docker container an a rasperry pi 4, everything works fine.

When I restart the container the downloads the needed plugins:

```
installing grafana-piechart-panel @ 1.6.1
from: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.6.1/download
into: /var/lib/grafana/plugins

✔ Installed grafana-piechart-panel successfully 
```

but when i look in the settings page

![grafik](https://user-images.githubusercontent.com/3524802/114180839-0de57e80-9941-11eb-9b38-cb91ed4aff41.png)

so I think the website not checked that there is a new plugin or is ist using the old one?

Docker Compose
```
grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - influxdb
    volumes:
      - ./../grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    networks:
      - gateway
    environment:
     - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
     - GF_INSTALL_PLUGINS=grafana-clock-panel,fetzerch-sunandmoon-datasource,natel-discrete-panel,grafana-piechart-panel
     - GF_RENDERING_SERVER_URL=http://grafana-renderer:8081/render
     - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
 ```

**Comment by dprokop** [comment] 2021-04-14 08:47
@JanHBade I've just tried to reproduce this problem with the docker compose file you provided. It works OK :
![image](https://user-images.githubusercontent.com/2376619/114681805-c7ac6880-9d0e-11eb-90c3-467eafface50.png)


Are you still encountering the issue, and have you for sure restarted the grafana server?

**Comment by JanHBade** [comment] 2021-04-14 10:55
yes the problem is still there, restarted the container nothing changed

maybe is that a issue that i work with the anonymous login? (i have a another auth in front)

**Comment by zuchka** [comment] 2021-04-14 14:32
@dprokop and @JanHBade fwiw I also tested the docker compose file on my pi but could not reproduce the issue. 1.6.1 installed/loaded normally.

**Comment by dprokop** [comment] 2021-04-16 13:40
@JanHBade tried with anonymous login and still the same- I get 1.6.1 installed.

**Comment by JanHBade** [comment] 2021-04-20 13:08
strange things...

I stop the container, deleted the plugins folder from the docker volume by hand, so now the plugin is the newest version, but the website still display the old values

**Comment by wbrowne** [comment] 2021-07-05 14:17
Will close this for now, but feel free to re-open if they problem persists

**Closed by wbrowne** 2021-07-05 14:17 UTC
Labels: area/plugins, needs more info, type/bug
