### ISSUE TITLE
Time series: Display name override is not propagated.

### ISSUE THREAD

**Issue by pepisp** [grafana/grafana#35823] opened 2021-06-16 13:54 UTC
**What happened**:
If you use display name override in Time series panel you'll get some strange behavior. 
Firstly you can't change series color from legend. Color picker is ok but in override you will see that the series name can't be found, so the color is not changed.
Secondly you can't pick one series from legend. Clicking on series in a legend hide/show all series but not showing the one you chose.
There maybe more consequences of this issue. It seems like the new name of series is not propagated to other "components".
![F73N60zEH0](https://user-images.githubusercontent.com/4233983/122231266-9db42580-ceba-11eb-9418-25deede552b4.gif) 
**What you expected to happen**:
Working color picking and series show/hide from legend just like it is working without series name override

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new panel from Grafana source with more than one series.
2. Override one of the series name
3. Try to change the series color from legend, you will see error in override which is then created. 
4. Click on the series name to see that it hides/shows all but you can't see the series alone.

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: Influx 2.0, Grafana source (probably all other )
- OS Grafana is installed on: Docker (Alpine image)
- User OS & Browser: Win10, Brave Version 1.25.72 (Chrome)
- Grafana plugins: Core + polystat

**Comment by torkelo** [comment] 2021-06-16 14:15
duplicate of https://github.com/grafana/grafana/issues/31364 

I would suggest using transform "Organize fields"  (use join transform first if you have multiple time series) this transform supports renames that happen before any field display setting overrides

**Closed by torkelo** 2021-06-16 14:15 UTC
