### ISSUE TITLE
Panel dropdown not visible when located at the rightmost end of the screen

### ISSUE THREAD

**Issue by walterdolce** [grafana/grafana#18923] opened 2019-09-05 13:33 UTC
**What happened**:
Positioned a panel at the rightmost end of the screen, hovered over with the mouse to click on "Copy":
<img width="309" alt="Screenshot 2019-09-05 at 14 27 14" src="https://user-images.githubusercontent.com/6195629/64346172-8fe52700-cfe9-11e9-96a1-c8c5ef965478.png">

**What you expected to happen**:
That I could see the dropdown panel, like so (perhaps appearing to the left-hand side of the first-level dropdown?):
<img width="461" alt="Screenshot 2019-09-05 at 14 27 24" src="https://user-images.githubusercontent.com/6195629/64346291-c15df280-cfe9-11e9-9671-9de87f5d1733.png">

**How to reproduce it (as minimally and precisely as possible)**:
Create a Singlestat panel and place it at the rightmost side of the screen. Then repeat the steps above.

**Anything else we need to know?**:
Nope. Don't think so.

**Environment**:
- Grafana version: `v6.2.4 (commit: ee01897)`
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: macOS & Google Chrome, latest version as of this time of writing
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment] 2019-09-05 14:38
Think there is already an issue for this

**Comment by torkelo** [comment] 2019-09-05 19:59
dupe of https://github.com/grafana/grafana/issues/15692

**Closed by torkelo** 2019-09-05 19:59 UTC
