### ISSUE TITLE
[Bug] ebs_volume_ids only accepts a single instanceId

### ISSUE THREAD

**Issue by davis190** [grafana/grafana#8014] opened 2017-04-03 13:07 UTC
**Use case:** We are monitoring a group of servers from Amazon Web Services. We are using templating to pull in the correct group of servers (1 or more). We also want to monitor Disk I/O on that group of servers so we attempt to create another template using the _ebs_volume_ids_ function and pass in the variable with the list of servers we would like to monitor. 

**Result**: We get an error that we are using incorrect instnaceIds. The _ebs_volume_ids_ function will work if there is a single server returned from the first template query and the "Include All option" is not selected. If we select more that one instanceId or the all option the _ebs_volume_ids_ query will break.

- What Grafana version are you using? - **v4.1.2**
- What datasource are you using? - **AWS Cloudwatch**
- What OS are you running grafana on? - **CentOS 7**

 Please let me know if you need any additional details or screenshots and I can capture and provide those.

**Comment by torkelo** [comment] 2017-04-03 13:31
Cloudwatch api does not support multiple dimensions of the same id in a single query (that I know).

Duplicate of https://github.com/grafana/grafana/issues/7658

**Closed by torkelo** 2017-04-03 13:31 UTC

**Comment by davis190** [comment] 2017-04-03 18:22
@torkelo - Looks like the API does support passing in multiple instanceIds. Pull request above should fix the issue.

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html

**Comment by torkelo** [comment] 2017-04-03 19:21
that's great, does not look like a great fit though as it does not support multiple instance  filters in one expression which is what the templating engine provides.

**Comment by davis190** [comment] 2017-04-03 20:29
@torkelo - What do you mean by multiple instance filters? The ebs_volume_ids function doesn't have any instance filters in it. 

The use case above would use other templates to create a list of InstanceIds and then pass that template as a variable into the ebs_volume_ids function to get all of the volumes for that list of instances.

**My tests looked like the below:**
Template called _Servers_
`ec2_instance_attribute(us-west-2, InstanceId, { "tag:Name": [ "ECS-Cluster*" ] })`

Template called _Volumes_ that gets all the volumes attaches to the instances from _Servers_.
`ebs_volume_ids(us-west-2, $Servers)`

**Comment by torkelo** [comment] 2017-04-04 06:15
what I mean is that the cloudwatch api does not support matching multiple properties using glob, regex or wildcard, which are the methods that the templating engine was designed for and which all other data sources support one variant off.
