### ISSUE TITLE
Forward slash in a string not visualized correctly in a link using ${__data.fields.name} 

### ISSUE THREAD

**Issue by ambarit** [grafana/grafana#47894] opened 2022-04-19 15:38 UTC
**What happened**:
In a dashboard panel, in Table, I have an Override with a Data link on the first column, which leads to another dashboard.  
The link of the URL is like the following:

https://grafana.com/d/${__data.fields.Link_value}

Link_value is another column. Consists of two values: eXx_qJmMk/classic-gen and jFHx8KRGk/next-gen.
When the link is clicked it opens the below URL:

https://grafana.com/d/eXx_qJmMk%2Fclassic-gen

As seen, the forward slash is substituted with %2F. 
This is observed after an upgrade from Grafana 8.4.1 to Grafana 8.4.6.

**What you expected to happen**:
I expect to see the exact same string in the link, as it is in the column Link_value. I.e.  eXx_qJmMk/classic-gen or jFHx8KRGk/next-gen.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a table panel with two columns. 
2. Add a Value mapping Override to the second column and give it a value eXx_qJmMk/classic-gen.
3. Add a Data Link Override to the first column with URL https://grafana.com/d/${__data.fields.Column2}
4. Clicking on the link will lead to https://grafana.com/d/eXx_qJmMk%2Fclassic-gen. It should lead to https://grafana.com/d/eXx_qJmMk/classic-gen

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Prometheus.
- User OS & Browser: Linux. Chrome and Firefox.

**Comment by joshhunt** [comment] 2022-04-20 13:05
Thanks for reporting!

Duplicate of #46817, already fixed by #47763 😌

**Closed by joshhunt** 2022-04-20 13:05 UTC
