### ISSUE TITLE
Math expression referencing hidden queries results in 500 error

### ISSUE THREAD

**Issue by qistoph** [grafana/grafana#51152] opened 2022-06-21 09:19 UTC
**What happened**:
A math expression like `$B + $C - $A` results in an error if `$A`, `$B` or `$C` is hidden.
![image](https://user-images.githubusercontent.com/678500/174763278-7cacc68c-4e61-4310-bac9-c8c837853086.png)

Showing `$A`, `$B` and `$C` makes everything work as expected
![image](https://user-images.githubusercontent.com/678500/174763120-75e3434c-be82-4bfa-910f-7f52991d413d.png)

**What you expected to happen**:
The math expression should show, without errors, even though any referenced queries are hidden.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a Panel
- Add an (InfluxDB) data query
- Add a math expression referencing that query (just `$A`)
- Hide the data query (`$A`)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.0 (b5c56f6371)
- Data source type & version: InfluxDB 1.8.4
- OS Grafana is installed on: [grafana/grafana](https://hub.docker.com/r/grafana/grafana) docker image
- User OS & Browser: Windows 10, Chrome 102
- Grafana plugins: None
- Others:

**Comment by N0tronic** [comment] 2022-06-21 15:35
Here too. Same version. Datasource Elasticsearch.

**Comment by N0tronic** [comment] 2022-06-23 18:26
No idea, what the problem is? It's a key feature in many of my dashboard. Now it doesn't work anymore 😔

Should I downgrade to the old version, or is there a solution on the way?

**Comment by heha1012** [comment] 2022-07-07 12:06
Facing this problem since updating to v9 too. Is there any solution in planning?

**Comment by mishamo** [comment] 2022-09-28 08:29
We had the same issue in 9.0.0, then updated to version 9.1.6 and this now works.

**Comment by UberPinguin** [comment] 2023-03-22 15:55
We're seeing this issue in 9.4.1.

**Comment by edoocosta** [comment] 2023-04-25 03:43
Facing the same problem in v9.4.2 using Bigquery plugin as datasource.

**Comment by UberPinguin** [comment] 2023-04-25 14:10
> Facing the same problem in v9.4.2 using Bigquery plugin as datasource.

FWIW, in our case it turned out to be a plugin not marking the hidden variables as transient when performing the query. It wasn't a bug in Grafana proper.

**Comment by gtk-grafana** [comment] 2023-07-06 16:39
I can't reproduce this on influx in v9 or v10. Works fine on [play](https://play.grafana.org/) as well.

**Comment by gtk-grafana** [comment] 2023-07-06 16:42
I'm closing this out as this issue is for influxDB, which appears to have been fixed. If you are still having this issue please create an [issue](https://github.com/grafana/grafana/issues/new/choose) and include what data source you are using

**Closed by gtk-grafana** 2023-07-06 16:42 UTC
Labels: effort/small, datasource/InfluxDB, prio/high, area/expressions, triage/needs-confirmation

**Comment by ttftw** [comment] 2023-08-15 01:40
I'm having this problem with Influx data source and using any expression query regardless of if it's hidden. Was there any other solution?
