### ISSUE TITLE
Dashboard edit issue in IE 11

### ISSUE THREAD

**Issue by biro11** [grafana/grafana#20364] opened 2019-11-13 16:24 UTC
**What happened**:
No possible to edit any dashboard component in IE 11. This error received:
![image](https://user-images.githubusercontent.com/5763101/68782016-f2d1ea80-0638-11ea-992a-6f57957a833d.png)

**What you expected to happen**:
Continue to edit dashboard component

**How to reproduce it (as minimally and precisely as possible)**:
Try to edit any dashboard component in IE 11

**Anything else we need to know?**:
Everything OK in Chrome

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: Probably any (I tested only on Elasticsearch and Prometheus)
- OS Grafana is installed on: Debian 9
- User OS & Browser: Windows 10, Internet Explorer 11
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-11-13 17:32
IE11 is not supported in v6.+ https://github.com/grafana/grafana/issues/15754

**Comment by marefr** [comment] 2019-11-13 19:02
Duplicate of #15754

**Closed by marefr** 2019-11-13 19:02 UTC
