### ISSUE TITLE
[PostgreSQL] [query-editor] column selection popup not showing all available columns

### ISSUE THREAD

**Issue by ChriZ982** [grafana/grafana#42124] opened 2021-11-23 11:00 UTC
**What happened**: I am trying to view Postgres data in a table visualization. When I add a column in Grafana, only some of the actual Postgres columns are shown in the recommendation popup (probably due to this line of code: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/postgres/meta_query.ts#L130).

![example](https://user-images.githubusercontent.com/28103843/143014999-cc61c1b2-ea15-44b5-86d5-101641bba2a4.gif)

**What you expected to happen**: I expect that all columns are shown in the popup because I want to add text columns to my table as well. Also, other numeric types are excluded with that check. I know that it is still possible to add them by knowing the column name, but this is not feasible for an end user who does not know all available columns for every table and does not have direct database access to look them up.

**How to reproduce it (as minimally and precisely as possible)**: Create a Postgres/Timescale table with "text" columns. Then, create a Grafana panel with table visualization and try to add a column. The text columns are not displayed in the popup.

**Anything else we need to know?**: The datatypes that are shown in the recommendation popup should be configurable in the datasource settings or it should be possible to disable the check entirely.

**Environment**:
- Grafana version: v7.5.10 (e72061a129)
- Data source type & version: PostgreSQL (TimescaleDB)
- OS Grafana is installed on: Docker 20.10.7
- User OS & Browser: Windows 10 - Edge
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment] 2022-01-06 15:39
Duplicate of https://github.com/grafana/grafana/discussions/37009

**Comment by ChriZ982** [comment] 2022-01-14 14:07
This is not really a duplicate of https://github.com/grafana/grafana/discussions/37009 and the merged PR https://github.com/grafana/grafana/pull/43445 does not fix this issue. I would expect to find all columns shown in the popup. Otherwise, it is just confusing the end user when columns are not shown for the table visualization where it would make perfect sense.

In general, the idea behind [this line of code](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/postgres/meta_query.ts#L130) is not clear to me. The behaviour you described in [this comment](https://github.com/grafana/grafana/pull/43445#issuecomment-1006736375) is similar to what happens when using an InfluxDB datasource and selecting a string field (see screenshot). There it is absolutely possible to select string measurements and I would love to see this for the Postgres datasource as well.

![image](https://user-images.githubusercontent.com/28103843/149527019-5b4a2894-fada-4ca3-b6d5-ed8392ab1216.png)

**Comment by zoltanbedi** [comment] 2022-01-14 14:35
@ChriZ982 sorry, you are right.

**Comment by codeincarnate** [comment] 2022-08-23 20:24
We're on the verge of releasing a new Postgres query editor in #52831 that contains a number of improvements on the Angular based editor here. We're currently focused on that so going to close this issue in favor of that. That being said if there's an ongoing need or if this wouldn't be solved by the new query editor please feel free to re-open 😄

**Closed by codeincarnate** 2022-08-23 20:24 UTC
Labels: type/feature-request, datasource/Postgres, area/query-editor
