### ISSUE TITLE
A proposal to enhance Grafana alerting

### ISSUE THREAD

**Issue by oktal** [grafana/grafana#18288] opened 2019-07-29 15:49 UTC
# Motivation

The company I’m working at is using Grafana to monitor its internal system and empowers the Grafana alerting engine to get notified when something wrong happens.
We are heavily using alerting through Grafana, and would like to use it more but we’re currently hitting some limitations from the alerting engine that we would like to get rid of.

## Per-serie alerting

We use telegraf to monitor our machines, especially data like memory and CPU usage. Now, we’d like to setup an alert when say disk usage exceeds 80%. We can do that with a single panel displaying one graph per host (through a group by), and then put an alert on the whole panel. However, if the alert gets triggered once, it won’t get triggered anymore if an other host also exceeds the configured threshold while it is in the alerting state. This means that hosts that are problematic can go undetected, which is not ideal.
I remember that this was identified as an item in the previous roadmap, but I can not find it back since the roadmap has been migrated to Github’s project list.

## Time of day restriction

Our systems are not running 24/7 and are down during the week-end. Thus, alerts should not get triggered outside particular time-range.
Currently, we are publishing InfluxDB measurements that encode the current time, date, and weekday and are adding them to alerting panels that need time-range restriction. This works as expected but is very error prone. Also, with this kind of hack, “No Data” won’t get triggered anymore since the time and date query always returns data points.

## More fine-grained alert thresholds

Currently, Grafana alerting engine only allows for a fixed threshold, and recently added a special “for” to keep the alert in “pending” state during a certain period of time before triggering it. However, it happens that sometimes our metrics report a value above the configured alert threshold, but it is expected as it might be during a particular system startup. Ideally, we would like to ignore such specific conditions by configuring the alert such that it only triggers after exceeding the threshold a certain number of times during a certain time window (for example, trigger an alert when metric A is above a threshold N times during the last M seconds).

# Detailed design

## Track alerting state per-serie

Instead of tracking the state of the alert at the panel level, track the state at the serie level, thus allowing for the alert being triggered multiple times for the same panel. Everything on the alert definition stays the same.

## A new “Time restrictions” subsection in Alerting section

Under the “Alerting” tab, a new “Time restrictions” is added to define custom named time restrictions, the same way Notification channels work

![image1](https://user-images.githubusercontent.com/859699/62062109-acdb4d00-b228-11e9-9aa1-8e49c658d5cf.png)

A time restriction has a name (e.g “Business hours”) and a list of included “ranges”. A range has the following properties
* A time of day restriction (e.g between 9AM to 6PM)
* A day of week restriction (e.g monday to friday)

Also, at the time restriction level, can be defined
* A list of excluded days (e.g holidays)

On the alert definition panel, add the ability to apply a time restriction previously defined. To avoid potential conflicts and keep things simple at the beginning, only one time restriction can be applied per alert

## Extend alerting rule

In the Rule section, replace “For” by a combobox with a new “TIMES” option that can be used to specify that a query must violate the configured threshold N TIMES during a certain period of time. Like “For”, the alert first goes from “OK” to “Pending” before going into “Alerting”.

![image2](https://user-images.githubusercontent.com/859699/62062140-b82e7880-b228-11e9-87bf-34275ad14b01.png)

# Open questions

In this issue https://github.com/grafana/grafana/issues/17520 the following comment is made

> We are currently in an early phase of designing the next generation of Grafana alerting. So we won't implement this in the current version of Grafana alerting. I'm not sure how we will solve the issue like this but we will make sure to solve the underlying problem. I'm leaving this open as a reminder for us.

What is the Roadmap on this ? What is the expected due date ? Should we expect a lot of code breaking if we implement a first version of our design ?

**Comment by jdmaloney** [comment] 2019-07-30 16:57
Tracking alert state per-series is also in issue #6041, I agree it'd be great to have I've been following that issue for a while now along with some other alerting based issues (alerts on single stat panels, etc.)

**Comment by Ultraseamus** [comment] 2019-07-31 15:51
Something else that would come indirectly from the time restrictions is the ability to pick a particular time of day for the alert, making it more like a notification. As in: Every morning at 8:00am I want to see a status report of my services.

I'll add on the the request to say that there should also be a better story around alerting on graphs with template variables. As it is today, when we want to build alerts we have to branch off of our existing monitoring dashboards, because they all use templates. Either we make whole separate alert dashboards, or we have a collapsed row at the bottom of the monitoring dash.

I think there is a good way to improve this without going so far as to actually have the alert run queries for every possible template value (which could get out of hand very quickly); and that is by having the alert config detect that template variables are in use, and prompt the user to select (or multi-select) values for those templates to be replaced with (essentially defining a scopedVars). This way, the same graphs that run in normal, templated dashboards can be alerted on.

**Comment by oktal** [comment] 2019-08-01 12:35
> Something else that would come indirectly from the time restrictions is the ability to pick a particular time of day for the alert, making it more like a notification. As in: Every morning at 8:00am I want to see a status report of my services.

That's also something we would need. Ability to schedule the evaluation of an alert at a particular time of the day.

**Comment by uepoch** [comment] 2019-08-01 14:16
I would argue against limiting the alerts to be evaluated at a certain time

It's more of the pager responsibility than the evaluation system to act / escalate differently based on time, if the value should be monitored, the state should be tracked at all times

**Comment by marefr** [comment] 2019-08-05 15:47
Duplicate of #6592 
Duplicate of #17520 
Duplicate of #6041

**Comment by marefr** [comment] 2019-08-05 15:55
Most of these requests already have open feature requests so will close this. If you rewrite the issue to target a feature request that's not already open we'll reopen this. 

> What is the Roadmap on this ? What is the expected due date ? Should we expect a lot of code breaking if we implement a first version of our design ?

There are currently no detailed roadmap for this and we have no expected due date, it's still in a very early stage. One first step that we probably want to do is allowing to detach alert rules from dashboard/panel to enable alert rules for any type of query/visualization. We cannot guarantee that your code will break, but as with all changes in Grafana we try to implement them in a backward compatible way.

**Closed by marefr** 2019-08-05 15:55 UTC
Labels: area/alerting, needs investigation, type/feature-request
