### ISSUE TITLE
[Feature request] Alerting/Notification - Webhook - more customisation

### ISSUE THREAD

**Issue by gihuma15dheufn** [grafana/grafana#7070] opened 2016-12-26 20:04 UTC
Hello,

I was setting up an alert using a webhook to inform/alert into a Hipchat room, this is working, but for the alert, "back to normal" and "no data" I get the same message into Hipchat, so you can image the complains of my users ;)

It would be great to have the possibility to configure 3 different messages & colors (min red, green & grey) to customize it.
And the possibility to include the log value into the alert message, like you get if you click on "test rule"
e.g.
logs

    0 { message: Condition[0]: Query Result, data: [object Object], $$hashKey: object:950 }
    1 { message: Condition[0]: Eval: true, Metric: cpu.mean, Value: 0.670, 
 
but a bit nicer ... Metric blabla (0.670) > Threshold (0.550).
Or/and the possibilty to specify graph name, hostname or whatever comming from the graph by using a variable in the alert text:

eg:
 Host $host hit the $graph threshold ($threshold) please have a look/fix fit 

- Grafana version 4.0.2
- datasource influxdb

Thanks in advance,

![hipchat](https://cloud.githubusercontent.com/assets/15520545/21485971/36cfa62a-cbac-11e6-9fe1-83f10bc8e491.PNG)
![grafana](https://cloud.githubusercontent.com/assets/15520545/21485973/36d2015e-cbac-11e6-85c7-5efd118daabe.PNG)
![notification](https://cloud.githubusercontent.com/assets/15520545/21485972/36d0327a-cbac-11e6-8366-bca27e0665b4.PNG)

**Comment by torkelo** [comment] 2016-12-27 09:16
Duplicate of https://github.com/grafana/grafana/issues/6956

**Closed by torkelo** 2016-12-27 09:16 UTC
