### ISSUE TITLE
Dashboard: panel context menu doesn't hide

### ISSUE THREAD

**Issue by Develer** [grafana/grafana#71217] opened 2023-07-07 15:03 UTC
### 
# What went wrong?

The panel context menu doesn't hide when I choose something from the menu using a keyboard hotkey instead of a mouse click. After open some page (e.g. Edit) menu still displaying and jump into top left page corner. If 

Please see the video demonstration:
![ezgif-5-9462be89fa](https://github.com/grafana/grafana/assets/1418924/a907ca7b-e206-4f0c-80a4-8492ab3fd421)

### 
# How do we reproduce it?

1. Click on the context menu of the panel;
2. Instead of using the mouse, click "e" on the keyboard to open the Edit page;
3. If you didn't click your mouse anywhere - the menu still gonna be here;
4. After hovering over the menu it will jump to the top left page corner;
5. After clicking somewhere outside of the menu - the menu gonna hide;

### 
# What Grafana version are you using?

v10.1.0-pre

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

**Comment by evictorero** [comment] 2023-07-13 15:20
Hi @Develer! Thanks for letting us know I could easily reproduce it, we will prioritize it.

**Comment by natellium** [comment] 2024-03-25 09:11
👋 I was trying to reproduce this in the upcoming v11.0.0 and it seems to be working as expected. I'll be closing this issue but do reopen it if the problem persists.

**Closed by natellium** 2024-03-25 09:11 UTC
Labels: type/bug, area/dashboard, team/grafana-dashboards, prio/future
