### ISSUE TITLE
InfluxDB Datasource: Measurement with name "%" is not useable in grafana flux query

### ISSUE THREAD

**Issue by merzchristoph** [grafana/grafana#84935] opened 2024-03-21 16:49 UTC
### What happened?

Hello,
my datasource store the measurement into my influx database with the unit type as name. 
![measurement](https://github.com/grafana/grafana/assets/147244664/98450a9d-508b-4e84-83ab-3aeb53166ae9)
In grafana, I use follow query into my visualisations: 
![nodata](https://github.com/grafana/grafana/assets/147244664/563e6ff2-b165-4ccf-a5ee-86c8d647662b)
With % as measurement name I got no results (funny: on my first try, I got a result value but after an hour the result is: No Data)
If I use the measurement name "W" in my query, it works. 
![works](https://github.com/grafana/grafana/assets/147244664/8df750d1-3dee-42cd-aac6-8698f244fe83)
I don't find a method to escape the symbol name. 

### What did you expect to happen?

Eighter it should be possible to escape the symbols or accept all character as names

### Did this work before?

In the past I use Influxdb SQL for my queries. This works, but not with flux query language.

### How do we reproduce it?

1. Create measurements with % as name 
2. create flux querys in visualisations

### Environment (with versions)?

Grafana: 10.4.0
OS: Ubuntu 20.04.6 LTS
Browser: Google Chrome Version 122.0.6261.131 (Offizieller Build) (64-Bit)

### Grafana platform?

Docker

### Datasource(s)?

InfluxDB Plugin 5.0.0 (latest compatible version)

**Comment by merzchristoph** [comment] 2024-03-23 09:05
Sorry, but I got a little impatient, so I replaced the influxdb v2 with an influxdb v1 and everything works with that. So I can no longer recreate the situation well. Maybe my opened bug ticket will help other users.

**Comment by NWRichmond** [comment] 2024-05-08 14:50
Thank you for that update, @merzchristoph!

Grafana's InfluxDB data source doesn't differentiate between InfluxDB versions, so it's interesting (and puzzling) that switching to InfluxDB v1 sorted things out.

Closing this for now since it sounds like this is resolved, but can reopen as needed (especially if there are other reproductions with InfluxDB v2).

**Closed by NWRichmond** 2024-05-08 14:50 UTC
Labels: datasource/InfluxDB
