### ISSUE TITLE
Support for windows authentication over mssql

### ISSUE THREAD

**Issue by wsjnohyeah** [grafana/grafana#17560] opened 2019-06-12 22:32 UTC
**What happened**:
I tried to use windows connection for mssql. There is no option for this so I left both username and password blank. Sometimes it says connection set successful, but sometimes not. Later I tried to set up a query and the query either fails or always return empty stuffs.

**What you expected to happen**:
I should be able to execute query and get expected result using windows authentication for mssql.

**How to reproduce it (as minimally and precisely as possible)**:
Set up a mssql with windows authentication. Choose mssql as datasource in Grafana, leave username and password blank. Queries cannot return expected results.

**Environment**: Windows 10
- Grafana version:6.2.2
- Data source type & version: mssql 2014
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins: none

**Comment by hugohaggmark** [comment] 2019-06-13 13:21
Hi @wsjnohyeah and thanks for taking the time to report this. 
We already have an open feature request #11876 that looks like it would solve your issue.

Duplicate of #11876

**Closed** 2019-06-13 13:22 UTC
Labels: type/duplicate
