### ISSUE TITLE
[Feature request] possibility to operate some simple calcul on different series

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#7109] opened 2017-01-02 13:22 UTC
Hello

I don't know if it is possible, but it would be AWESOME to be able to defines some calculation functions in the "metrics" tabs of a panel.

Example:

- Defining some time series (ex: 2 graphite, 1 influx, 1 elasticsearch so A,B,C,D)
- Creating a new timeseries of a new type (ex: "grafana computation")
- Defining something like "(#A + #B) / (#C - #D)

the formula would be applied as a resulting new time series.

The interest could be to have the possibility to operate simple operations on different kind of timeseries.

Regards
Jeremy

**Comment by bergquist** [comment] 2017-01-02 13:26
Sure would be awesome! :)

Dupe of https://github.com/grafana/grafana/issues/3677

**Closed by bergquist** 2017-01-02 13:26 UTC
