### ISSUE TITLE
8.2.4 and 8.3.1 grafana/plugins - bad gatewey

### ISSUE THREAD

**Issue by pep3l** [grafana/grafana#42906] opened 2021-12-09 07:41 UTC
**What happened**:
"bad gatewey", when im going to grafana\plugins or click "plugins"

**What you expected to happen**:
plugins list

**How to reproduce it (as minimally and precisely as possible)**:
open a plugins tab

**Anything else we need to know?**:
I upgraded 6 instance grafana 8.2.4 => 8.3.1 updated by replacing files.
5 instance is OK
but 1 instance is bad gateway.
The configuration is the same everywhere.

**Environment**:
- Grafana version: 8.2.4&8.3.1
- Data source type & version: none
- OS Grafana is installed on: WIndows Server 2019 Standard
- User OS & Browser: WIndows 10\ Chrome
- Grafana plugins: none
- Others:

**Comment by ashharrison90** [comment] 2021-12-09 10:35
hi @pep3l 👋 

thanks for raising this! 🙌 
can't reproduce this locally, and haven't heard of any other reports of this. it's also super weird it's only happening for 1 of the 6 instances. is there any more information you can provide to help us recreate the problem?
- when you say the configuration is the same, are the same plugins installed on each instance?
- is there any error in the console or network tab?

**Comment by pep3l** [comment] 2021-12-09 11:36
I remove any plugins for test - not passed.

console:
t=2021-12-09T14:32:07+0300 lvl=info msg="Request Completed" logger=context userId=6 orgId=1 uname=*name* method=GET path=/api/live/ws status=0 remote_addr=IP time_ms=0 size=0 referer=
t=2021-12-09T14:32:08+0300 lvl=eror msg="Request Completed" logger=context userId=6 orgId=1 uname=*name* 
 method=GET path=/api/gnet/plugins status=502 remote_addr=IP time_ms=1 size=0 referer=http://grafanaDNSname/plugins
t=2021-12-09T14:32:08+0300 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"

**Comment by mckn** [comment] 2021-12-14 11:14
@pep3l do you have any more logs that you can share?

**Comment by mckn** [comment] 2021-12-14 11:20
@pep3l can you also provide a screen shot of the chrome console?

**Comment by mckn** [comment] 2021-12-14 11:22
@pep3l do your instance have access to https://grafana.com/api/plugins?

**Comment by pep3l** [comment] 2021-12-15 07:44
> @pep3l do your instance have access to https://grafana.com/api/plugins?

Yes, access. I see long json code.

**Comment by mckn** [comment] 2021-12-15 08:42
@pep3l please provide the other information I requested so we can help you debug this. Thanks!

**Comment by pep3l** [comment] 2021-12-15 14:10
> @pep3l please provide the other information I requested so we can help you debug this. Thanks!

There was not very interesting information about the problem. Perhaps the problem was in the backlog of old files. I updated Grafana starting from version 6 in small pieces by replacing the files. As a result, the public folder has grown a lot. I removed it completely and replaced it from the 8.3.3 distribution and the problem disappeared.

**Comment by mckn** [comment] 2021-12-16 20:26
> > @pep3l please provide the other information I requested so we can help you debug this. Thanks!
> 
> There was not very interesting information about the problem. Perhaps the problem was in the backlog of old files. I updated Grafana starting from version 6 in small pieces by replacing the files. As a result, the public folder has grown a lot. I removed it completely and replaced it from the 8.3.3 distribution and the problem disappeared.

Closing the issue since it seems to be resolved

**Closed by mckn** 2021-12-16 20:26 UTC
Labels: needs more info, area/plugins-catalog
