### ISSUE TITLE
Add support for multiple variable selection in data links

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#30850] opened 2021-02-03 03:09 UTC
**What would you like to be added***:
We should be able to pass multiple variables in a data link. We need to something like an `asUrl` format option, where `${foo:asUrl}` would resolve to `var-foo=A&var-foo=B` 

**Why is this needed**:
At the moment the options are to pass either 1 variable value, or all variables (using `$__all_variables}` ). If you select multiple variable in for $test  here what happens:
data link configured => http://localhost:3000/d/i2QdgeBGz/test-data-link-child-dashoard?var-test=${test} 
URL created => http://localhost:3000/d/i2QdgeBGz/test-data-link-child-dashoard?var-test={value1,value2}
URL that would work =>  http://localhost:3000/d/i2QdgeBGz/test-data-link-child-dashoard?var-test=value1$var-test=value2

`$__all_variables}`  only works if there is one variable, or if the intent is to pass all the variables. It doesn't work if the goal is to pass some variables from data.fields, and some from the selected variables from the drop down.

**Comment by torkelo** [comment] 2021-02-03 08:08
duplicate of https://github.com/grafana/grafana/issues/21459

**Closed by torkelo** 2021-02-03 08:08 UTC
Labels: area/dashboard/data-links, priority/support-subscription, type/feature-request
