### ISSUE TITLE
Implement a way to easily duplicate and/or embed a graph from one dashboard to another

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#415] opened 2014-05-14 20:35 UTC
Apologies if I've missed something but as far as I can tell there is no _simple_ way to duplicate or embed an existing graph from one dashboard to another. This is something that could really enhance collaboration and "graphs reuse" amongst the users.
Embedded would be preferable but extending the "duplicate" function would already be a big plus (the target row could be a new one).

**Comment by simple10** [comment] 2015-01-15 02:07
+1

**Comment by torkelo** [comment] 2015-01-15 09:09
Just as temporary solution (not a very good one), you can view a panels json (from the panel menu), copy the json, and view another panels json on another dashboard, paste the json and hit update.

**Comment by MichaelScofield** [comment] 2015-09-01 08:28
+1!

**Comment by jshook** [comment] 2015-10-20 15:10
+1
I'd like to see this generalized to rows too.

**Comment by ty** [comment] 2016-06-01 17:09
+1

**Comment by Fabex** [comment] 2016-09-06 13:37
:+1:

**Comment by bluecmd** [comment] 2017-02-16 07:58
+1

**Comment by jelgh** [comment] 2017-02-16 07:59
+1

**Comment by torkelo** [comment] 2017-12-18 14:51
closing this as it's 90% dupe of https://github.com/grafana/grafana/issues/1004

**Closed by torkelo** 2017-12-18 14:51 UTC
Labels: type: feature
