### ISSUE TITLE
Multiple Tag Variables Not Expanding in Slack Messages

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#42172] opened 2021-11-23 21:02 UTC
**What happened**:
Alert fired by Grafana into a slack channel is no longer expanding all tag variable as it did before

**What you expected to happen**:
All tag variables in alert message are expanded so we can see what they are for meaningful alerts

**How to reproduce it (as minimally and precisely as possible)**:
Configure an alert on a panel in Grafana where the query has (for example) a "GROUP BY host,path", in the query and in the "Alias by" field put something similar to $tag_host - $tag_path and configure the alert using that query

**Anything else we need to know?**:
This was working in v7.5.11 and we think also in earlier versions of 8.2, but is not working in 8.2.5.  I've attached screenshots of an example of what we're seeing in the Slack alerts both a before (v7.5.11 and now with 8.2.5).

<img width="529" alt="Working_Variable_Expansion_7_5_11" src="https://user-images.githubusercontent.com/16138910/143122227-fccebb94-e521-48d9-af99-0eda0af359b4.png">
<img width="424" alt="Broken_Variable_Expansion_8_2_5" src="https://user-images.githubusercontent.com/16138910/143122324-1d25220e-eda2-471f-8922-f59893f63511.png">

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: RHEL 8.4
- User OS & Browser: MacOS Safari & Windows Chrome tested
- Grafana plugins: N/A
- Others: N/A

**Comment by billglick** [comment] 2022-01-13 16:26
This is still giving us issues with Grafana v8.3.3

**Comment by jdmaloney** [comment] 2022-02-18 17:44
@armandgrillet Thanks for taking a look at this; I've tested with v8.4.1 this morning and the behavior looks to have returned to normal with alerts containing all their proper information.  

I tested by temporarily lowering the thresholds of a couple of our alerts to force them to fire and they worked fine.  I not test every single alert definition we have with multiple tags (as there are many) but the few I tested looked good; so I think you are safe to close this issue.  If for some reason we see it crop up again we can reopen at that point.  

Thanks again!

**Comment by joelsdc** [comment] 2022-03-04 19:49
Hi! We're also facing this...

I'm going to test on 8.4.X, in 8.3.6 we have the same behavior:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/16212586/156831647-b53c376f-3dc4-48fc-bb15-6d327353fba7.png">

So far I've only noticed the issue with `$tag_host`, other tags seems to be shown ok.

**Comment by billglick** [comment] 2022-03-04 20:58
We continue to see this same issue with Grafana v8.4.3.

**Comment by santihernandezc** [comment] 2022-03-22 22:15
@jdmaloney I managed to reproduce the issue. There's a bug in the regex responsible for matching aliases, it's matching things that it shouldn't. I made a [PR](https://github.com/grafana/grafana/pull/46862) to fix this.

This is the result of "Test Alert" before the PR:

<img width="777" alt="Screen Shot 2022-03-22 at 16 02 22" src="https://user-images.githubusercontent.com/41638679/159585212-cf33a341-595e-4a66-b317-7ca5b19156b6.png">


After the fix:

<img width="776" alt="Screen Shot 2022-03-22 at 16 02 56" src="https://user-images.githubusercontent.com/41638679/159585155-286f6179-9fed-442c-9729-20c8f6bdfe64.png">

**Comment by santihernandezc** [comment] 2022-03-24 03:20
The PR fixing this bug was just merged into `main`, so I'm closing this issue.

**Closed by santihernandezc** 2022-03-24 03:20 UTC
Labels: type/bug, prio/medium, effort/large, area/alerting/notifications, area/alerting/legacy
