### ISSUE TITLE
Query Editor gui issues / query breaking

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#41557] opened 2021-11-10 16:16 UTC
**What happened**:
Since v8 (or maybe v8.1) , the query editor has been giving very unexpected output / changes.  IE will re-order or duplicate a query when selecting from the drop down menus and other un-expected behaviors.  I have tried my best to rule out browser-side causes (or other causes on my end), however I frequently see this occur both on Chrome and Firefox, as well as on entirely different physical PCs (ie to try to rule out browser / cache / cookie issues).

(in the past week i have purchased a brand new / fresh win11 based laptop, and im seeing the same issues occur on that laptop , as i do on my win10 based desktop pc)

**What you expected to happen**:
Query editor to preform as expected (and as it did pre grafana version 8-8.1)

**How to reproduce it (as minimally and precisely as possible)**:
Using a graphite data source, edit an existing panel (ie not create a new one) with several queries-  then change dropdown options and re-order queries (see screen video).

**Anything else we need to know?**:
Please see video at bottom showing the issue occur.  I can repeat this across any of my varied dashboards.

(in video i also show a prior, *unrelated* issue in regards to not being able to access the bottom elements of drop down lists, but that is not the focus of this bug report-  i have that filed seperately, under: https://github.com/grafana/grafana/issues/41011

thank you- LOVE GRAFANA!

**Environment**:
- Grafana version: v8.2.2
- Data source type & version: Graphite (v0.9.14)
- OS Grafana is installed on: Debian 8
- User OS & Browser: Win10 on Chrome
- Grafana plugins: N/A
- Others: 

![doneGrafanaCAP](https://user-images.githubusercontent.com/60830628/141150158-53d3e6f2-b668-4410-8f07-6a91afe218bc.gif)

**Comment by ashharrison90** [comment] 2021-11-10 17:04
hey @bob454522 👋 

that looks super frustrating. unfortunately i'm struggling to reproduce the problem locally.
is there any smaller reproducible example you've found? 🤔

**Comment by bob454522** [comment] 2021-11-12 19:28
thanks for your reply @ashharrison90  - 
i was able to reproduce it with a simpler example.  as well as a 2nd video in which i change the data source to a 2nd graphite system i have (which is same as the first, except it keeps all data at a 1min retention period - so is higher resolution).   It does look like graphite is throwing the error, but im not clear what has changed in how grafana is calling graphite (as of recent v8 versions) to cause this.

nb; even though im choosing the same series in both videos ("tedACfast") that is irrelevant, as i can choose *any* series and this same thing will occur.

nb; I have always had memcache in place as well.  (i did a test with memcache service stopped, and the same thing occurred)

Please let me know if there is other info i can provide to help debug this.

Im still running the same graphite version (v0.9.12) as i always have (ie same as back when using grafana v5/v6/v7- ie for past two or so years - so no recent changes there).  I generally stay upto-date on grafana version (ie have gone from v4 to v6 to v7 , and now v8)   

Really the only change on this local, dedicated VM (debian 8) is update grafana from time to time (no other updates).  I have always had carbon-relay-ng in place so that does provide some basic syntax filtering for the data incoming to graphite/whisper.

(i have also been running carbon-relay-ng for years, without any updates or changes to its config).

thank you for your help,  please see video below.  (note in these videos i am using Firefox, as opposed to my opening post video where i was using chrome).  
In the 2nd / bottom video you can see im using my other graphite instance / datasource ("1min-res-Graphite-69.42"  which runs on a different debian8 VM), with the same issue occurring.

![doneGrafanaCAP2](https://user-images.githubusercontent.com/60830628/141522733-a521204c-bb62-4d15-bdac-4c3da15b4e6b.gif)

2nd video w a different graphite datasource (but has SAME data relayed to it, just on a different , higher RES, retention period) + shows graphite query / return error at the end:
![doneGrafanaCAP3](https://user-images.githubusercontent.com/60830628/141523844-b09925f7-0d77-4057-b945-19734bb2eb8e.gif)

thanks - LOVE GRAFANA!

**Comment by mckn** [comment] 2021-11-19 11:22
@bob454522 it sounds like this is related to the issue where the order of the series is changed on refresh. Do you think you can verify that this is resolved in the 8.3-beta1 version?

https://github.com/grafana/grafana/pull/41868

**Comment by mckn** [comment] 2021-11-19 15:50
@marefr highlighted to med that it probably isn't the issue that I linked. So we need to investigate this a bit more.

**Comment by marefr** [comment] 2021-11-19 15:53
I can reproduce it here: https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=2
1. Duplicate A. Now you have A, B
2. Drag B to the top
3. Click on fakesite in B and select backend
4. You now have two queries with the RefID B

**Comment by marefr** [comment] 2021-11-19 16:07
Cannot reproduce with the test data source so seems to me like a graphite issue so maybe should let @grafana/observability-squad take it over?

**Comment by aocenas** [comment] 2021-11-23 13:14
@marefr @ifrost  I think I seen this with other data sources too. Maybe there is some special way the dropdown needs to be wrapped so it does not overflow.

**Comment by ifrost** [comment] 2021-11-23 13:22
@aocenas - yes. There are two problems mentioned here:
* Duplicate + drag & drop breaks Graphite editor (Graphite specific)
* Segment with asynchronously loaded options always shows the dropdown below the input. Synchronously loaded options do not have this problem (e.g. list of functions in Graphite). This happens in any data sources that use async options (e.g. Influx)

**Comment by mckn** [comment] 2021-11-25 08:44
@ifrost great work on this! Can this issue be closed?

**Comment by ifrost** [comment] 2021-11-25 09:47
@mckn 

> There are two problems mentioned here:

> Duplicate + drag & drop breaks Graphite editor (Graphite specific) 

This is fixed by #42136

> Segment with asynchronously loaded options always shows the dropdown below the input. Synchronously loaded options do not have this problem (e.g. list of functions in Graphite). This happens in any data sources that use async options (e.g. Influx)

This still needs to be addressed. Shall I create a separate issue for it?

**Comment by mckn** [comment] 2021-11-25 13:49
Ah, thanks - sorry for the confusion. I think you can do it within this issue.

**Closed** 2021-12-13 13:59 UTC
Labels: type/bug, datasource/Graphite, prio/high
