### ISSUE TITLE
Feature request: Support POSTing to Prometheus series endpoint

### ISSUE THREAD

**Issue by eahydra** [grafana/grafana#16519] opened 2019-04-11 12:47 UTC
**What would you like to be added**:
The newest Prometheus v2.9.0 rc0 supports POSTing to /series endpoint

**Why is this needed**:

we need compatible with Prometheus.

**Comment by aocenas** [comment] 2020-07-22 08:32
Closing this as a duplicate of https://github.com/grafana/grafana/issues/17342 because it has more information now.

**Closed by aocenas** 2020-07-22 08:32 UTC
Labels: datasource/Prometheus, type/feature-request
