### ISSUE TITLE
Confusing timezone with custom time selector in explore

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#20411] opened 2019-11-15 13:18 UTC
Set the timezone via preferences to UTC, select a custom time range in explore, what you pick seems to be translated vs what shows up after you close the time picker window.

This came up when trying to use explore during a postmortem review.

**Comment by torkelo** [comment] 2019-11-15 14:22
duplicate of https://github.com/grafana/grafana/issues/19978

**Closed by torkelo** 2019-11-15 14:22 UTC
Labels: area/explore
