### ISSUE TITLE
Alert Notifications - execute program/script

### ISSUE THREAD

**Issue by itsecworks** [grafana/grafana#12637] opened 2018-07-17 20:50 UTC
We need the possibility to execute some program or script in case of an alert.
If grafana can send email, webhook an many thing in case of an alert, why just cant start simple script for what the user just gives the path. and of course some variables are required that can be taken over to the script as a parameter, for example some tags.

I have some cases where it would be really important to start a script. Thats why I cant move completely to grafana, because of this one simple step...

**Comment by torkelo** [comment] 2018-07-19 06:33
duplicate of https://github.com/grafana/grafana/issues/6721

**Closed by torkelo** 2018-07-19 06:33 UTC
