### ISSUE TITLE
How to get Prometheus value in ngalert

### ISSUE THREAD

**Issue by tetsuya28** [grafana/grafana#37497] opened 2021-08-03 15:39 UTC
**What happened**:
I set this alert query, and got following query result.
<img width="1456" alt="スクリーンショット 170" src="https://user-images.githubusercontent.com/11973270/128043888-d794b599-3ed5-4132-b275-ae6f3ec74fa1.png">

<img width="1453" alt="スクリーンショット 168" src="https://user-images.githubusercontent.com/11973270/128043535-c961d760-c466-4db3-8107-db85971ecc03.png">

In this alert, I wanted to get the prometheus value in Description annotations for notify the value.
<img width="1038" alt="スクリーンショット 169" src="https://user-images.githubusercontent.com/11973270/128043775-a1875032-9c90-406d-834d-b4b76d9a8b98.png">

But, with `{{ $value }}`, shows following string
```
[ var='B' labels={instance=192.168.10.112:9100} value=57.00000000069849 ], [ var='C' labels={instance=192.168.10.112:9100} value=1 ]
```
Is there a way to get prometheus value? In this case, the prometheus value is `65.00000000014552` in `var=B`'s `value`.

**What you expected to happen**:
Just get `65.00000000014552` with `${{ value }}`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0-beta3 (f778fdbbe8)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by itsmjeu** [comment] 2021-08-04 07:27
This is duplicated with #37393

**Comment by ashharrison90** [comment] 2021-08-09 09:35
thanks for raising this! 🙌 

agreed, sounds like a duplicate of https://github.com/grafana/grafana/issues/37393
please stick a 👍 on https://github.com/grafana/grafana/issues/37393 and we'll track fixing it through that issue

if you think this is a mistake and it's a different problem, let me know and we can reopen. thanks! 😄

**Closed by ashharrison90** 2021-08-09 09:35 UTC
