### ISSUE TITLE
[Bug] SSL certs are not verified

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#9366] opened 2017-09-28 05:18 UTC
Grafana 4.5.1:

* https://github.com/grafana/grafana/blob/c114c4611/pkg/models/datasource_cache.go#L50

This is the default transport for all datasources:

```
	transport := &http.Transport{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
		Proxy: http.ProxyFromEnvironment,
		Dial: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
		}).Dial,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
	}
```

If I add prometheus datasource pointing to https endpoint:

![image](https://user-images.githubusercontent.com/89186/30950432-b4f988ba-a3d1-11e7-831a-63d9200cd9b7.png)

Then SSL certificate is not going to be validated. This seems wrong.

**Comment by mattbostock** [comment] 2017-09-28 09:08
Duplicate of #8812.

**Closed** 2017-09-28 15:06 UTC
