### ISSUE TITLE
CloudWatch Logs: e.data[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by lijok** [grafana/grafana#32658] opened 2021-04-03 00:19 UTC
**What happened**:
`e.data[Symbol.iterator] is not a function`
<img width="289" alt="image" src="https://user-images.githubusercontent.com/28689084/113462783-8b2d6280-941a-11eb-94c0-4109e6fe4997.png">

**What you expected to happen**:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/28689084/113462771-823c9100-941a-11eb-8cf5-56657ee5b3eb.png">

**How to reproduce it (as minimally and precisely as possible)**:
`filter message = "Processed document" | parse lambda_event.source_key "*/*" as client, _ | stats count(*) by bin(24h), client`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: cloudwatch logs
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment] 2021-08-10 09:27
@lijok can't really reproduce it although it may be because I have different data. Can you post what the query produces when showed in table panel? Also is this issue in graph panel or also in the new time series panel? Can you also check new grafana versions if it is still present?

**Comment by lijok** [comment] 2021-08-10 12:45
@aocenas thanks for having a look into this
upgraded to latest (v8.1.1) and it seems to be working now
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/28689084/128868863-23b7da26-569a-4980-a93d-2ef16a206615.png">
thanks

**Comment by hugohaggmark** [comment] 2021-08-23 07:03
Closing this issue because reporter reports it's fixed and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2021-08-23 07:03 UTC
Labels: type/bug, priority/important-soon, needs more info, area/frontend, datasource/CloudWatch Logs
