### ISSUE TITLE
Grafana 8.0 - Table Panel Transformations - Merge and Outer Join - breaking and not working

### ISSUE THREAD

**Issue by mavasaf** [grafana/grafana#34606] opened 2021-05-24 16:26 UTC
**What happened**:
Created Table Panels with Transformations using earlier versions of Grafana 7+, Transforms all work without any issues,. 
On Upgrading from 7.5.7 to 8.0 Beta 2, noticing issues with Table Panels. It does not show any data - 'No Data'

**What you expected to happen**:
Created Table Panels with Transformations using earlier versions of Grafana 7+, Transforms all work without any issues,. 
On Upgrading from 7.5.7 to 8.0 Beta 2, expecting the same behavior without any issues. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Grafana 7.5.7 
2. Create two queries to elasticsearch data from Grafana Table Panel. 
3. Using 'Terms' to group the data from elasticsearch. ( Please note - no date histogram fields)
4. Apply Panel Transformation to join the two queries data into a single view by using 'Merge' or 'Outer Join' transform. 
5.  Data should be seen in one view with the data combined and shown by the  field used in the 'Terms' grouping. 
6. Upgrade the dashboard to 8.0 Beta 2, 
7. After upgrade, we notice that the panel loads showing 'No Data' (screenshot below)
 
![image](https://user-images.githubusercontent.com/68710456/119376970-69f62f00-bc71-11eb-901d-133011498b5d.png)

Expecting an image like below with data 
![image](https://user-images.githubusercontent.com/68710456/119376999-737f9700-bc71-11eb-9dcc-9298634ec119.png)
 

**Anything else we need to know?**:

On investigating into transformations, 
queries return data without any issues. 
same query , same environment, same data set, works with Grafana 7.5.7
Note : In case of Outer Join, after again editing the transforms it seems to work. 
However in case of Merge transform, even after editing, doesn't seemt to work. 
Any immediate help and a fix for this before 8.0 goes live, is greatly appreciated, thank you !

**Environment**: PROD, TEST, LOCAL - ALL ENVIRONMENTS
- Grafana version: Grafana 8.0 Beta 2 
- Data source type & version: Elasticsearch 6.5+
- OS Grafana is installed on: Windows, Linux. 
- User OS & Browser: Windows, Chrome,. 
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-05-24 16:41
Can you paste data from the two queries failing to be joined?

**Comment by torkelo** [comment] 2021-05-24 16:42
Also show your transformation settings? For the join transform have you specified a field name?

**Comment by torkelo** [comment] 2021-05-24 16:43
Oh and thanks for testing the beta and opening an issue!

**Comment by mavasaf** [comment] 2021-05-24 16:57
sure, sharing the screenshot below of transform window 
Grafana 7.5+ screenshot 

![image](https://user-images.githubusercontent.com/68710456/119382030-5dc0a080-bc76-11eb-864c-d007c2909d51.png)

Grafana 8.0 + screenshot
![image](https://user-images.githubusercontent.com/68710456/119382131-792bab80-bc76-11eb-865a-4c9c2cbc8b66.png)

**Comment by mavasaf** [comment] 2021-05-24 16:58
> Can you paste data from the two queries failing to be joined?

Apologies, those are Org specific sensitive data and I cannot share here, thanks !

**Comment by mavasaf** [comment] 2021-05-24 17:00
probably, I missed a pointer to mention in the original issue. For the Terms Grouping, we are using template variable. with multiple option select behavior, with repeat panel based on the selection in template variable. Variable Name - $groupby as you see in the above screenshot.

**Comment by mavasaf** [comment] 2021-06-09 16:29
Any update on this ? so 8.0 released without this fix ?

**Comment by mavasaf** [comment] 2021-06-09 16:41
Should we stop our upgrade and point to 7.5.7 until this issue fixed ? 
working around it with upgrade to 8.0 is a tedious one, we have 40+ dashboards to check and implement work around. 
Any suggestions please ?

**Comment by ryantxu** [comment] 2021-06-10 00:32
weird -- from the screenshots, it looks like the data is missing long before a join.  but very hard to tell without data.   If you don't have values shown here:

![image](https://user-images.githubusercontent.com/705951/121446576-a8197100-c948-11eb-9de4-d3b48ecab963.png)

it is not even getting to the join

**Comment by ryantxu** [comment] 2021-06-10 00:33
if you remove the transformation do you have data?  what does it look like?

**Comment by torkelo** [comment] 2021-06-10 04:55
@ryantxu think he used a variable in the join field select , looks like the old transform supported this

**Comment by mavasaf** [comment] 2021-06-10 15:23
right, there is data prior to transform and transformation works until 7.5.7. In 8.0 it is not working,
Since 8.0 is already released. We are now making 7.5.7 as the desired version until this issue is fixed. 
Unfortunately, we have been looking forward to use 8.0 and we are blocked due to this.

**Comment by hugohaggmark** [comment] 2021-06-14 07:09
I've investigated this and this PR https://github.com/grafana/grafana/pull/32762 introduced this bug. Moving it to @grafana/observability-squad 

Dashboard to repro this using dev block `elastic7`
{
  "__inputs": [
    {
      "name": "DS_GDEV-ELASTICSEARCH-V7-METRICS",
      "label": "gdev-elasticsearch-v7-metrics",
      "description": "",
      "type": "datasource",
      "pluginId": "elasticsearch",
      "pluginName": "Elasticsearch"
    }
  ],
  "__requires": [
    {
      "type": "datasource",
      "id": "elasticsearch",
      "name": "Elasticsearch",
      "version": "1.0.0"
    },
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.5.7"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1623650960985,
  "links": [],
  "panels": [
    {
      "collapsed": false,
      "datasource": null,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "panels": [],
      "repeat": "groupBy",
      "title": "Row title $groupBy",
      "type": "row"
    },
    {
      "datasource": "${DS_GDEV-ELASTICSEARCH-V7-METRICS}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": null,
            "filterable": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 1
      },
      "id": 4,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "7.5.7",
      "targets": [
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "$groupBy",
              "id": "2",
              "settings": {
                "min_doc_count": "0",
                "order": "desc",
                "orderBy": "_term",
                "size": "10"
              },
              "type": "terms"
            }
          ],
          "metrics": [
            {
              "id": "1",
              "type": "count"
            }
          ],
          "query": "",
          "refId": "A",
          "timeField": "@timestamp"
        },
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "$groupBy",
              "id": "2",
              "settings": {
                "min_doc_count": "0",
                "order": "desc",
                "orderBy": "_term",
                "size": "10"
              },
              "type": "terms"
            }
          ],
          "hide": false,
          "metrics": [
            {
              "field": "@value",
              "id": "1",
              "type": "sum"
            }
          ],
          "query": "",
          "refId": "B",
          "timeField": "@timestamp"
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "seriesToColumns",
          "options": {
            "byField": "$groupBy"
          }
        }
      ],
      "type": "table"
    }
  ],
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_GDEV-ELASTICSEARCH-V7-METRICS}",
        "definition": "{\"find\": \"fields\", \"type\": \"keyword\"}",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "groupBy",
        "options": [],
        "query": "{\"find\": \"fields\", \"type\": \"keyword\"}",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Grafana 8.0 - Table Panel Transformations - Merge and Outer Join - breaking and not working #34606",
  "uid": "O0YidIR7z",
  "version": 5
}

**Comment by torkelo** [comment] 2021-06-14 07:27
It looks like you named a field $groupBy? in v8 Grafana will try to interpolate that (but did not in v7.5)

**Comment by torkelo** [comment] 2021-06-14 07:27
This looks like a very edge case scenario

**Comment by aocenas** [comment] 2021-06-14 08:20
@Elfo404 can you take a look and see how common this could be?

**Comment by Elfo404** [comment] 2021-06-14 10:28
Yeah, looks like an edge case but I can see the value there.
I created a PR that **should** fix this (still needs testing), as @hugohaggmark pointed out this was unintentionally introduced by the new variable interpolation logic in the ES plugin.

**Closed** 2021-06-17 10:50 UTC
Labels: area/frontend, area/transformations, datasource/Elasticsearch, priority/important-soon, type/bug

**Comment by mavasaf** [comment] 2021-07-30 21:21
I still can reproduce the error with 8.1 Beta 2. 

Can you please confirm if this issue is fixed ?

**Comment by Elfo404** [comment] 2021-07-30 23:58
@mavasaf it's fixed in 8.0.4 (https://github.com/grafana/grafana/pull/35624) but we introduced it again in 8.1 (https://github.com/grafana/grafana/pull/36035) as an intentional breaking change. 

We reverted the change for 8.0.x because it was - as pointed out - an undocumented breaking change

**Comment by mavasaf** [comment] 2021-08-06 22:21
Thank you @Elfo404 for the update. When can we expect this issue to be fixed?
We have currebyl

**Comment by Elfo404** [comment] 2021-08-06 22:53
Sorry for the confusion @mavasaf , what I meant is that the behavior you described is intended. A "fix" is available in the latest 8.0.x release, but in 8.1 and forward this should be considered the intended behavior, so it won't change.

**Comment by mavasaf** [comment] 2021-08-06 23:44
Does that mean this bug will stay on? And not fixed?

**Comment by mavasaf** [comment] 2021-08-06 23:46
Reason I ask is, we use the template variable based Grouping and transformation based on template variable and this is heavily used in so many dashboards. If this bug is not fixed, we will not be able to migrate to latest Grafana.

**Comment by mavasaf** [comment] 2021-08-10 21:46
@Elfo404  - Can you please help me with an update please ?

**Comment by Elfo404** [comment] 2021-08-17 09:57
@mavasaf we do not consider this as a bug but it works as expected. Grafana 8.0.x (starting from 8.0.4) will support your use case, but not 8.1 and forward. what you were doing was possible because of another "bug" that prevented variables to be assigned the correct value when parsing queries results. we fixed that in 8.1, but this means your use case is not supported anymore.

there's an open future request to allow your specific use case in https://github.com/grafana/grafana/issues/25469

**Comment by mavasaf** [comment] 2021-08-17 18:48
Thank you @Elfo404  for the response. I wasn't aware of this. the functionality that we were using is a result of another bug :-) In fact, we have heavily relied on that template variable in the transformation. 
Now that we have upgraded to 8.0.4, so we can use that transformation and repeat panels as desired. 

For the future request #25469, is there any ETA ?

**Comment by Elfo404** [comment] 2021-08-17 18:50
Not really, but PRs are always welcome :)

Otherwise you can upvote the issue to signal your interest
