### ISSUE TITLE
Option to hide version information on the login page

### ISSUE THREAD

**Issue by oliob** [grafana/grafana#16810] opened 2019-04-29 15:31 UTC
**What would you like to be added**:
Possibility to configure NOT to show detailed grafana version including commit tag on the login page.
At least I haven't found that option yet. 
**Why is this needed**:
I don't want to disclose this information to everyone...

**Comment by marefr** [comment] 2019-04-29 16:12
Duplicate of #12925

**Closed by marefr** 2019-04-29 16:12 UTC
