### ISSUE TITLE
Grafana shows "Unable to load datasource meta data" errors

### ISSUE THREAD

**Issue by maoyuanh** [grafana/grafana#19736] opened 2019-10-10 09:59 UTC
We are using grafana 6.2.2. 
When first login to grafana we can see dashboard normally.
![gracap](https://user-images.githubusercontent.com/39478165/66558907-ffb97500-eb86-11e9-9d2c-284425823a11.PNG)
but after wait a few minutes if i did not do any thing on gui, it cannot display data from prometheus at all: "Unable to load datasource meta data" error is shown. See screenshots.
![dashboard_not_able_to_load_datasource](https://user-images.githubusercontent.com/39478165/66559091-5aeb6780-eb87-11e9-92d8-0dcb858f9321.png)
 In Grafana log hundreds of following kind entries are shown:
t=2019-10-07T08:14:19+0000 lvl=eror msg="Unable to load datasource meta data" logger=context userId=1 orgId=1 uname=admin error="Data source not found"
t=2019-10-07T08:14:19+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/53/api/v1/query_range status=500 remote_addr=10.145.225.24 time_ms=36 size=49 referer="https://grafana.vneoe2e.eecloud.dynamic.nsn-net.net/d/container_resources/container-resources?orgId=1&refresh=30s"

And if i input F5 to refresh, then it can recover.

**Comment by papagian** [comment] 2019-10-14 08:20
This can be a duplicate of #8177
Are you using multiple organizations and have grafana open with same user but different organizations?

**Comment by torkelo** [comment] 2019-10-19 08:44
closing due to lack of updates / details

**Closed by torkelo** 2019-10-19 08:44 UTC
Labels: needs more detail

**Comment by dacort** [comment] 2022-09-16 20:14
In case somebody else stumbles across this, I also had this issue when I had the same dashboard open in multiple browsers (but same user). I think one of the old dashboards just had a stale ID or something (and clearly wasn't working), and had just gotten hidden in my mess of tabs. 🤭 Closing it made the errors go away.
