### ISSUE TITLE
Still cannot log in on Firefox mobile (iOS)

### ISSUE THREAD

**Issue by systemcrash** [grafana/grafana#24046] opened 2020-04-29 11:41 UTC
Sorry if this is a dupe - searched but nothing matched, it seems.

**What happened**: login screen presented, login button mangled slightly below user/pass fields. No customisations. This is vanilla Grafana in docker image. 

[View here](https://www.dropbox.com/s/fk08bj5y8pzsul1/Video%202020-04-29%2C%2013%2003%2022.mov?dl=0) - sounds in the video are me mashing the return key. 

**What you expected to happen**: not the above - to be able to log in

**How to reproduce it (as minimally and precisely as possible)**: go to a grafana instance to log in using Firefox mobile browser (iOS)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.3 (same with 6.7.2, 6.4.3, 6.4.2 etc etc)
- Data source type & version:
- OS Grafana is installed on: docker img
- User OS & Browser: iOS Firefox latest
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment] 2020-04-29 14:18
duplicate of https://github.com/grafana/grafana/issues/15473

**Closed by torkelo** 2020-04-29 14:18 UTC
