### ISSUE TITLE
[Feature request] select shared crosshair style

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#6947] opened 2016-12-13 20:45 UTC
Please include this information:
- What Grafana version are you using?
4.1.0-beta

While shared tooltips in 4.1.x are nice, they are hammering performance pretty high if you have alot of graphs. 
And shared crosshair will be missing.

Is it possible to implement selection for shared mode, like
1) Off, crosshair only on selected graph
2) Shared crosshair (pre-4.1.0 style)
3) Shared tooltip (4.1.0 style)

**Comment by torkelo** [comment] 2016-12-13 21:10
I agree, will change this soon. 

dupe of https://github.com/grafana/grafana/issues/6894

**Closed by torkelo** 2016-12-13 21:10 UTC
