### ISSUE TITLE
Repeat row don't update automaticaly with variable change

### ISSUE THREAD

**Issue by aruizpardo** [grafana/grafana#16300] opened 2019-03-29 13:16 UTC
I have diferents groups of hosts in Zabbix, and exists a variable of hosts that depends of this value. I have installed the zabbix datasource plugin. In my dashboard, there is a row (and panels) that's it repeat for everyhots marked in the host's list.

**What happened**:
The first row don't change the name automaticatly when you change the host's group (Obviously change the host list too). You have to close and open the row to update the name. The panels inside update correctly.

**What you expected to happen**:
Automaticaly update the title's row.

**How to reproduce it (as minimally and precisely as possible)**:
First, create a dashboard with a group variable, before, create a row that repeat for every host inside this group. For last, change the group variable value.

**Environment**:
- Grafana version: 5.4.2
- Data source type & version: Zabbix datasource
- OS Grafana is installed on: Centos OS 7
- User OS & Browser: Linux mint 19.1, Chrome and firefox fail
- Grafana plugins: "Zabbix plugin for Grafana" by Alexander Zobnin

**Other**
This only fail in the first row, the rest of rows update correctly

**Comment by marefr** [comment] 2019-03-29 13:53
Duplicate of #15133

**Comment by marefr** [comment] 2019-03-29 13:54
Please upgrade to at least Grafana v6.0 or latest stable version.

**Closed by marefr** 2019-03-29 13:54 UTC
