### ISSUE TITLE
Adding an _exp_ overrides Stats Plugin Labels 

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#48868] opened 2022-05-09 19:15 UTC
**What happened**:
Stats plugin overrides sql query alias

**What you expected to happen**:
The plugin to display data with alias of column instead of Value

**How to reproduce it (as minimally and precisely as possible)**:
--Mixed Data source
A. 1 with a count numeric value
B. 1 with another count also with a numeric value
C. 1 expression that calculates the values from A and B

**Anything else we need to know?**:
Interestingly the tag/label of the __expr_ shows on the Stats as is 
**Environment**:
- Grafana version: 8.4.5
- Data source type & version: mssql and one expression
- OS Grafana is installed on: Windows 2022
- User OS & Browser: WIndows/Chrome
- Grafana plugins: Stats
- Others:
![image](https://user-images.githubusercontent.com/900951/167481283-c2207d1b-584a-4789-b3a0-1da8a34f6ed2.png)

**Comment by yosiasz** [comment] 2022-05-09 19:21
sample data
```
create table chronogram(heure datetime,
varname varchar(50),
duree int)

2022-03-21 13:00:14.000,op2250_3_tcy,	29
2022-03-21 13:00:45.000,	op2250_3_tcy,	24
2022-03-21 13:01:20.000,	op2250_3_tcy,	24
2022-03-21 13:01:53.000,	op2250_3_tcy,	29
2022-03-21 13:02:21.000,	op2250_3_tcy,	24
2022-03-21 13:00:14.000,	op2250_1_tcy,	29
2022-03-21 13:00:45.000,	op2250_1_tcy,	24
2022-03-21 13:01:20.000,	op2250_1_tcy,	24
2022-03-21 13:01:53.000,	op2250_1_tcy,	29
2022-03-21 13:02:21.000,	op2250_1_tcy,	24
2022-03-21 13:02:52.000,	op2250_1_tcy,	24
```

two queries
```
SELECT count(1) as 'Total'
  FROM [researchteam].[dbo].[chronogram]

SELECT count(1) as 'Failures'
  FROM [researchteam].[dbo].[chronogram]
  where varname != 'op2250_3_tcy'

--Expression
($A* 100) /$B
```

**Comment by yosiasz** [comment] 2022-05-09 19:46
Update: Issue happens only when you add an expression. Without an expression the column alias does display in the viz

😨

**Comment by mellieA** [comment] 2022-05-16 18:22
This looks similar to https://github.com/grafana/grafana/issues/46325 that had a backport merged for 8.4.x. 

@yosiasz have you tested with any other newer version of grafana? I see that you are using 8.4.5 - I wasn't able to reproduce the issue on 8.5.2.

**Comment by yosiasz** [comment] 2022-05-16 18:44
Let me upgrade and see what happens. Thanks

**Comment by yosiasz** [comment] 2022-05-16 19:14
Upgraded to 8.5
2 and now it is worse 😆
Now all of them say Value instead of inheriting the alias name

**Comment by mellieA** [comment] 2022-05-17 23:41
@yosiasz oh no! Thank you for trying the upgrade, I'm sorry it made things worse!

I couldn't reproduce this with the elasticsearch or testdataDB datasources, but I do see it with the MySQL datasource on 8.5.0.

**Comment by yosiasz** [comment] 2022-05-18 00:18
No worries as it is a test environment

**Closed** 2022-11-16 15:39 UTC
Labels: type/bug, area/expressions
