### ISSUE TITLE
External links do no refresh template variable expansion

### ISSUE THREAD

**Issue by tcolgate** [grafana/grafana#12795] opened 2018-08-02 09:38 UTC
### What Grafana version are you using?
v5.2.0

### What datasource are you using?
simplejson

### What OS are you running grafana on?
linux (official docker images)

### What did you do?
Create an external link on a dashboard that uses template variables.

### What was the expected result?
The external link should update as template variables update (including from/to)

### What happened instead?
Template variables in the external link are expanded on the initial load, and if I change selection and do a full page reload. They are not changed simply by changing a template variable (the link contains its original value).  The from/to variables included if we include time range in the external link are also not updated when the time range changes.

**Comment by marefr** [comment] 2018-08-02 09:51
Duplicate of #12506

**Closed by marefr** 2018-08-02 09:51 UTC

**Comment by tcolgate** [comment] 2018-08-02 10:09
@marefr thanks, very sorry, I should have tried 5.2.2 first.
