### ISSUE TITLE
A single Bar will not return to zero at the end of the data

### ISSUE THREAD

**Issue by LittleWhite-Carry** [grafana/grafana#26713] opened 2020-07-31 02:18 UTC
**What happened**:
A single Bar will not return to zero at the end of the data.

**What you expected to happen**:
A single Bar display is cleared when the data is over。

**How to reproduce it (as minimally and precisely as possible)**:
Just do it.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: 7.1.1
- Data source type & version:  postgresql 10.1
- OS Grafana is installed on: ubantu
- User OS & Browser: windows, chrome
- Grafana plugins: no
- Others:

**Comment by aknuds1** [comment] 2020-07-31 05:22
Please fill in the "How to reproduce it (as minimally and precisely as possible):" of your issue description, so it's clear how to reproduce your problem.

**Comment by torkelo** [comment] 2020-08-09 06:45
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.

**Closed by torkelo** 2020-08-09 06:45 UTC
Labels: area/frontend, needs more detail

**Comment by LittleWhite-Carry** [comment] 2020-08-11 09:25
First, randomly select a time range. Then use a bar chart to display the data. When the system stops updating data to the database and the timestamp of the last data record exceeds the current time range, the bar chart does not return to zero.
