### ISSUE TITLE
[Bug] can't access cloudwatch using grafana

### ISSUE THREAD

**Issue by andyjp94** [grafana/grafana#9076] opened 2017-08-22 11:52 UTC
```
grafana-server -v
Version 4.4.3 (commit: 54c79c5)
```
datasource: cloudwatch
OS: ubuntu 16.04
What did I do?
Shown in pictures
![default](https://user-images.githubusercontent.com/10004367/29563929-9fbd8b38-8737-11e7-9a5e-85a98b1dc5ca.png)
and also 

![adf](https://user-images.githubusercontent.com/10004367/29563962-c0be99da-8737-11e7-8131-196472736056.png)

What was the expected result?
Should have pulled the cloudwatch information correctly.

What happened instead?
The two images as you can see from the GUI produced different results depending upon the "Name" field which I didn't expect. If the name is default then it seems to hang in testing, if the name is anything else then if falls over completely with a http error as can be seen. The log file shows the same error either way though. The error is shown below. This is really surprising because if I run ```aws cloudwatch  list-metrics --profile cloudwatch``` on the command line then it connects fine. So this would appear to be a problem with grafana and not my configuration of aws
```
t=2017-08-22T11:43:24+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="AccessDenied: User: arn:aws:sts::COMPANY_ID:assumed-role/aws-elasticbeanstalk-ec2-role/i-0be92a0ee5fc028ba is not authorized to perform: cloudwatch:ListMetrics\n\tstatus code: 403, request id: 1ae1876b-872f-11e7-aae2-efea6a0425eb"  
t=2017-08-22T11:43:24+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1 status=500 remote_addr=188.65.97.29 time_ms=26 size=36 referer=https://grafana.simomics.com/datasources/edit/1?gettingstarted
```

**Comment by torkelo** [comment] 2017-08-22 12:46
Can you try to remove the data source and create a new one? think we fixed a bug related to ARN auth that might be fixed by doing that (we fixed the root cause in master but might still be in v4.4.3)

**Comment by andyjp94** [comment] 2017-08-22 13:10
That did seem to work, do you have a release schedule or any idea when this fix might make it into a package?

**Comment by torkelo** [comment] 2017-08-22 13:22
will be in 4.5 (so 2-3 weeks)

**Closed by torkelo** 2017-08-22 13:22 UTC
