### ISSUE TITLE
Grafana 6.4.3 always show add annotation from iphone safari

### ISSUE THREAD

**Issue by lcgogo** [grafana/grafana#20770] opened 2019-11-29 10:40 UTC
**What would you like to be added**:
I upgrade grafana to v6.4.3 (3a2bfb7). However, when i use it from my iphone, the touched place always show an add annotation when I want to see the value of my lines.

**Why is this needed**:

**Comment by marefr** [comment] 2019-12-02 14:48
Duplicate of #19681

**Closed by marefr** 2019-12-02 14:48 UTC
