### ISSUE TITLE
Changing one variable doesn't refresh or update other variable

### ISSUE THREAD

**Issue by amivit** [grafana/grafana#13775] opened 2018-10-21 19:48 UTC
Grafana v5.3.1. ElasticSearch 6.5+. I have one dropdown for choosing the machine type, and another dropdown to choose the specific machine ID. The available machines should only be the one's of the chosen machine type. 

I have this working but only when I change the time range. I want the machine list to be updated immediately upon choosing a different machine type.

What's very weird is it works perfectly on my friends demo he shows me, but he's running Grafana v5.2.2, and his machine ID is a string, as opposed to my data where the ID is number. 

![image](https://user-images.githubusercontent.com/1857719/47271575-e33dba80-d57a-11e8-802b-32e48caff049.png)

So on my friends, he uses machineId.keyword. I cannot since it is a number. Is that where the issue resides? Or did something else break between v5.2.2 & v5.3.1.

Perhaps there's a setting or something I'm missing.

**Comment by torkelo** [comment] 2018-10-22 06:32
That is. Strange, can you open chrome dev tools network tab as you change the first variable you should see a request to elasticsearch can you paste the request body and response here?

**Comment by amivit** [comment] 2018-10-22 12:26
There are two _msearch requests sent:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"*moulding*","max_concurrent_shard_requests":256}
{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1540143444287","lte":"1540145669412","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"machineId:155654"}}]}},"aggs":{"4":{"terms":{"field":"machineId","size":10,"order":{"_term":"desc"},"min_doc_count":1},"aggs":{"2":{"date_histogram":{"interval":"2s","field":"timestamp","min_doc_count":0,"extended_bounds":{"min":"1540143444287","max":"1540145669412"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"parameters.CycleTime"}},"3":{"moving_avg":{"buckets_path":"1","minimize":false,"model":"simple","window":5}}}}}}}}
```
and

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"*moulding*","max_concurrent_shard_requests":256}
{"size":0,"query":{"bool":{"filter":[{"range":{"timestamp":{"gte":"1540143444287","lte":"1540145669412","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"machineId:155654"}}]}},"aggs":{"2":{"date_histogram":{"interval":"2s","field":"timestamp","min_doc_count":0,"extended_bounds":{"min":"1540143444287","max":"1540145669412"},"format":"epoch_millis"},"aggs":{"1":{"avg":{"field":"parameters.BackPressure"}}}}}}
```

**Comment by amivit** [comment] 2018-10-22 12:30
Actually I think the two _msearch queries are for the two panel's/graphs below. On my friends demo when I choose a machine type, I see_msearch?search_type=query_then_fetch

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"mdata","max_concurrent_shard_requests":256}
{"size":0,"query":{"bool":{"filter":[{"range":{"TIMESTAMPMSSQL":{"gte":"1540189741107","lte":"1540211341107","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"*"}}]}},"aggs":{"1":{"terms":{"field":"DataType.keyword","size":500,"order":{"_term":"asc"}}}}}
```

**Comment by torkelo** [comment] 2018-10-22 14:19
I see the issue , you are using the new preferred syntax ‘${varname}’  and we have an open issue (on mobile now so can’t find it) for this bug. The code that checks if a string constrains a dependant variable is not updated to also check the new syntax. As temp workaround switch to $varname syntax

**Comment by marefr** [comment] 2018-10-22 14:21
Duplicate of #13600

**Comment by marefr** [comment] 2018-10-22 14:22
Please continue discussion in #13600 if needed

**Closed by marefr** 2018-10-22 14:22 UTC
Labels: state: needs more detail

**Comment by amivit** [comment] 2018-10-23 15:34
$varname as opposed to ${varname} syntax fixed my issue. Thanks and good luck solving the bug!
