### ISSUE TITLE
[Feature request] Add message in the webhook request

### ISSUE THREAD

**Issue by GOOD21** [grafana/grafana#6725] opened 2016-11-28 08:41 UTC
4.0.0-beta2.

I think it's useful that the http server can get custom message.

Thank you.

![image](https://cloud.githubusercontent.com/assets/3470273/20661382/75a83b34-b589-11e6-8f0b-f0a65e2aa7ad.png)

**Comment by bergquist** [comment] 2016-12-05 08:37
Dupe of https://github.com/grafana/grafana/issues/6807 will be available in 4.0.2

**Closed by bergquist** 2016-12-05 08:37 UTC
Labels: comp: alerting, comp: alerting/notifications, type: feature request
