### ISSUE TITLE
Grafana Datasource Docs for Loki are Not Comprehensive

### ISSUE THREAD

**Issue by bennbollay** [grafana/grafana#41603] opened 2021-11-11 13:48 UTC
Documentation for Loki's Datasource YAML has a few examples, but no comprehensive list of the options and their formats.  For example, while [configuring datasources](https://grafana.com/docs/grafana/latest/datasources/loki/#configure-the-data-source-with-provisioning) has several examples, there's no mention of the `URL Label` parameter that's hinted at [here](https://grafana.com/docs/grafana/latest/datasources/loki/#derived-fields).

Please add a set of exhaustively generated "full" specifications for each yaml section.

**Comment by ifrost** [comment] 2021-11-16 11:20
Thanks @bennbollay!

All possible generic options are defined by `DataSourceSettings` object: https://github.com/grafana/grafana/blob/d3e19b1b3b58670fe49f82e73ecde4303f7e530a/packages/grafana-data/src/types/datasource.ts#L533

Loki-specific json data is defined in: https://github.com/grafana/grafana/blob/d3e19b1b3b58670fe49f82e73ecde4303f7e530a/public/app/plugins/datasource/loki/types.ts#L41. 

The example in docs shows how URL is used but I agree it's not clear how to provision settings in yaml. I think this is a problem not only in Loki and we should update documentation in all core data sources.

**Comment by matyax** [comment] 2022-10-07 11:04
@grafana/observability-logs this issue is not really a _bug_, isn't it? I'm trying to understand the labelling.

**Comment by gabor** [comment] 2022-10-07 11:17
it's about incomplete documentation.. so, in a way it's a "bug in the documentation", but perhaps that's not the best way to look at it?

hmm.. the basic problem is that the example yaml file at https://grafana.com/docs/grafana/latest/datasources/loki/#configure-the-data-source-with-provisioning

does not have options for every possible configuration option.

but that's quite broad, because there's a lot of generic options, things like "skip tls verify", and maybe it would be best to document those at a separate, generic place.

for this github issue i would focus on: make sure all loki-specific datasource-settings are represented in that YAML file.

what do you think?

**Comment by matyax** [comment] 2022-10-07 11:20
> it's about incomplete documentation.. so, in a way it's a "bug in the documentation", but perhaps that's not the best way to look at it?

Not a bug. Just better docs needed.

**Comment by ivanahuckova** [comment] 2022-10-07 12:10
>but that's quite broad, because there's a lot of generic options, things like "skip tls verify", and maybe it would be best to document those at a separate, generic place.

There is already a documentation for this https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources

**Comment by matyax** [comment] 2022-10-11 08:55
Closing this one. Please reopen if there's anything else to do.

**Closed by matyax** 2022-10-11 08:55 UTC
Labels: type/bug, type/docs, prio/medium, datasource/Loki
