### ISSUE TITLE
Panel Editor: Options Resolutions drop down disappears on 1/1 selection

### ISSUE THREAD

**Issue by supilee** [grafana/grafana#53791] opened 2022-08-16 15:49 UTC
**What happened**:
When trying to edit any panel of the MacOSX integration in order to change the resolution, the resolution drop down list disappeared when selecting 1/1. It works fine for 1/2, 1/3,1/4, 1/5 and 1/10 (see attached screen recording).
This happens with any panel on the dashboard.

**What you expected to happen**:
I expected the resolution to be changed to 1/1 but still be able to change it to change it back or to any other resultion available in the drop down list.

**How to reproduce it (as minimally and precisely as possible)**:
1. Select the editing function of any given panel (tested with MacOSX Integration on my end)
2. Scroll down to the options

3. from the resolution drop down select 1/1
--> the resolution drop down disappears

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 9.0.7 (eed942a50)
- Data source type & version: Prometheus
- OS Grafana is installed on: macOS Monterey 12.5
- User OS & Browser: Chrome Version 104.0.5112.79 (Official Build) (arm64)
- Grafana plugins:
- Others: macOSX Integration

https://user-images.githubusercontent.com/110845248/184922739-95e1c0bc-eb94-4996-8196-f81cae5ca51c.mov

**Comment by dginhoux** [comment] 2022-08-16 20:53
Hi, 

Have the same similar issue.

**Comment by torkelo** [comment] 2022-08-17 08:53
duplicate of https://github.com/grafana/grafana/issues/48081

**Closed by torkelo** 2022-08-17 08:53 UTC
Labels: datasource/Prometheus, area/editor, area/panel/edit
