### ISSUE TITLE
fix method of changing interval parameter value for queries more than 12 hours duration

### ISSUE THREAD

**Issue by sksingh20** [grafana/grafana#34775] opened 2021-05-26 20:43 UTC
**What happened**: lost downtime data point when queried for longer duration on system status

**What you expected to happen**: Downtime should have shown clearly even for queries for longer duration

**How to reproduce it (as minimally and precisely as possible)**: Increase time duration for queries more than 12 hours.. interval also increases by itself

**Anything else we need to know?**:
If power outage for 30 sec happened two days back. Obviously someone will try to change duration of graph to last 7 days.. and surprisingly this will show no power outage in last 7 days, whereas there was power outage two days back for 30 secs

**Environment**:
- Grafana version: Grafana v7.5.7 
- Data source type & version: Prometheus
- OS Grafana is installed on: ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

<img width="587" alt="metric disappear on refresh" src="https://user-images.githubusercontent.com/35199465/119728420-1530ff00-be91-11eb-9622-604b851e471c.png">

for six hour duration query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622040435&end=1622062035&step=**15**"

For 12Hour duration Grafa query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622018980&end=1622062180&step=**20**"

for 7 days duration Grafana query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1621457100&end=1622061900&step=**300**"

Change in step parameter value dynamically missing major incidents

**Comment by Elfo404** [comment] 2021-05-27 09:08
Hi @sksingh20 , thanks for reporting this.
Closing as duplicate of https://github.com/grafana/grafana/issues/9705

**Comment by sksingh20** [comment] 2021-05-27 13:22
@Elfo404 I did not see solution statement in #9705.
which remarks I need to see as solution statement? If this is limitation of grafana and grafana is not the tool for historical data granularity view?

Please reopen this defect.

**Comment by Elfo404** [comment] 2021-05-27 13:28
there's no solution yet also there, but the issue you are describing here is the same as the linked one, that's why I closed this.

as said in that issue, we are aware of the issue in dashboard panels, but there's no solution for it yet.

**Comment by sksingh20** [comment] 2021-05-27 13:32
@Elfo404 Thank you for confirmation.

This brings a very serious issue in reporting.
This mean Grafana is not right tool for historical data view as this represent data wrongly and will completely mislead analysis and reporting?

Changing step value on fly is changing full data view resulting to wrong reporting... Please confirm so that same will be communicated to CXO forums.

**Comment by aocenas** [comment] 2021-05-27 14:12
Seems to me more like an UX issue with how the legend summary should probably work. The automatic step alignment make sense from visualization perspective because the `No power` band just cannot be shown anyway but if we wan't to also show that aggregated data there in the legend, that has other requirements. Right now it just summarizes the "visible" data points which as you say probably isn't what user expects.

https://github.com/grafana/grafana/issues/9705 would help to manually override the step I assume but still user may not know it is required and can still create wrong results in the summary legend anyway.

@torkelo can you maybe chime in here whether we are solving this in some other visualizations or whether this is something users have to expect.

**Comment by torkelo** [comment] 2021-05-28 05:00
This is not a Grafana issue, it's a Prometheus issue. Your query is not looking correct for what your trying to do, must have a range vector, otherwise Prometheus will just sample data every step point.

**Closed by torkelo** 2021-05-28 05:00 UTC
Labels: datasource/Prometheus, type/duplicate

**Comment by sksingh20** [comment] 2021-05-28 05:39
@torkelo Can you please confirm why grafana including step value by its own if this is issue of prometheus.. This is very bad way of handling bugs.

Please reopen issue.

Query is build by Grafana dynamically and you are claiming that query is wrong.. what this mean?
Do you mean grafana is creating wrong queries. 



for six hour duration query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622040435&end=1622062035&step=15"

For 12Hour duration Grafa query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622018980&end=1622062180&step=20"

for 7 days duration Grafana query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1621457100&end=1622061900&step=300"

**Comment by sksingh20** [comment] 2021-05-28 05:46
![image](https://user-images.githubusercontent.com/35199465/119936007-14d65800-bfa6-11eb-8bd1-c98897e3e1ff.png)

**Comment by sksingh20** [comment] 2021-05-28 05:47
@torkelo Can you please confirm 
(1) ground of saying grafana query is wrong?
(2) this issue is not of grafana?

**Comment by sksingh20** [comment] 2021-05-28 05:52
Please reopen this issue.

**Comment by torkelo** [comment] 2021-05-28 07:42
@sksingh20 I think you need to read up on Prometheus query mechanics

This is a good resource 
https://www.robustperception.io/step-and-query_range 

https://prometheus.io/docs/prometheus/latest/querying/basics/ 

Prometheus time range query samples data at different points, this works great for ever-increasing counters, but for other types of metrics this requires some specific crafting of the query to get the desired data.

**Comment by sksingh20** [comment] 2021-05-28 07:50
@torkelo I think t\you are completely missing issue.

**Initially you have said that query is wrong where query is generated by Grafana.**

Now you are saying "some specific crafting of the query to get the desired data"
(1) How Grafana is modifying query my itself which actually removing data points.  
(2) How Grafana is knowing what data is desired. Its doing mistake by changing step value by its own. This is bug in Grafana.

(1) what is criteria grafana is creating query

**Comment by torkelo** [comment] 2021-05-28 08:39
Grafana does not write the query, you do.  Grafana sets the step, which is needed to not overload the browser and return every possible data point. step & range queries in prometheus are quite different from other data sources as Prometheus range queries always samples data at specific steps. To read the data in between you need to include a range vector in your query and a reduce (math function) for which data point within that time range to use (min max etc) . 

Instead of hardcoding a range vector you can use $__interval or $__rate_interval variables to read all the data within the step. 

Read https://grafana.com/docs/grafana/latest/datasources/prometheus 

> (2) How Grafana is knowing what data is desired. Its doing mistake by changing step value by its own. This is bug in Grafana.

No this is just very fundamental prometheus query mechanics (but not super easy for new users, I struggled with this myself)

**Comment by sksingh20** [comment] 2021-05-28 09:06
@torkelo I must say that your approach is purely developer context leaving business use case behind. 
Now this is really a question whether  Grafana is developed to solve business use case or some private project of developers?

(1) What you mean to say that "which is needed to not overload the browser", when this fails to fulfill business use case?
This only mean that Grafana failed to handle data in its base design and completely lost view by endup showing nice graphics leaving result as false. 

(2) You say that "Grafana sets the step"... And grafana lost view that what is impact of step on result.

Are we really talking about solution for enterprise?

(3) Again you are saying "prometheus are quite different from other data sources", whereas step value is induced by Grafana. Why you deviating from problem. If you keep step value 15 secs, whether Prometheus will not return data? Prometheus will return data. Challange is Grafana is not able to handle data and so grafana reducing data points by its own view loosing result of data completely.

(4) How will know range vector when you are trying to find out out those range itself? This only means Grafana is not a dashboard for CXO.

I have to bring this major issue to CXO forum, as this is now very clear that Grafana dashboard will mislead entire analysis.

**Comment by torkelo** [comment] 2021-05-28 10:19
@sksingh20 I feel your pain, this is a documentation and Prometheus query mechanics issue. Prometheus is not easy to learn and use for beginners and both Grafana and Prometheus docs can improve. 

> Challange is Grafana is not able to handle data and so grafana reducing data points by its own view loosing result of data completely. 

Grafana is not reducing data points, just increasing step, like EVERY prometheus query UI has to do in order not to hit prometheus data return limit (11k). It's just you have to learn how to write queries so they work independently of step. This is why I say your query is wrong for the type of data you are querying / and looking for, it only works for short time ranges. 

You need to wrap your query in for example `max_over_time(<your_query>[$__interval])`      the prometheus range vector [5m] etc is the thing that will make sure it reads data points between steps, and you can use `[$__interval]`  to get a range vector equal to the step to read all data points between steps.  

Prometheus query logic can be very hard to learn.

**Comment by sksingh20** [comment] 2021-05-30 14:55
@torkelo I am not sure from where you have received 11K. Could you please heolp with that.

As per Prometheus it is fairly large 5e7.
https://github.com/prometheus/prometheus/pull/4532/files/14b044963748b0d9d95f89409fb928ded0da51c8

**Comment by sksingh20** [comment] 2021-05-31 15:51
Please reopen this issue.
