### ISSUE TITLE
Feature request - Template Variables to work per Row in dashboard

### ISSUE THREAD

**Issue by biker73** [grafana/grafana#6781] opened 2016-12-01 15:44 UTC
Please include this information:
- Version 4.0
- influxdb
- Windows 7 and Redhat 7

It would be great to have template variables that can be per row in a dashboard. If I want to graph statistics from two different platforms for example it would be nice to have one ROW where a user can select 'Window' and  cpu statistics, and then another row with Linux and cpu statistics.  Because field keys have different names with different operating systems its nice to be able to compare stats across servers with different operating systems. Currently this can only be done by hard selecting certain information within a query rather than selecting values from drop downs generated from templating. It would be could to have this across rows, effectively dashboards within a dashboard, to allow nicer usability from templated graphs.

**Comment by torkelo** [comment] 2016-12-01 17:08
duplicate of https://github.com/grafana/grafana/issues/5329

**Closed by torkelo** 2016-12-01 17:08 UTC
