### ISSUE TITLE
Add configurable option to require admin permissions to add or modify notification channel.

### ISSUE THREAD

**Issue by azhiltsov** [grafana/grafana#15969] opened 2019-03-13 10:19 UTC
**What would you like to be added**:
Add configurable option to require admin permissions to add or modify notification channels.
**Why is this needed**:
In order to restrict users from creating their own (possible insecure or unreliable, non controlled) communication channels

**Comment by torkelo** [comment] 2019-03-13 11:39
duplicate of https://github.com/grafana/grafana/issues/12332

**Closed by torkelo** 2019-03-13 11:39 UTC
