### ISSUE TITLE
Explore: Disable/enable query button state is not differentiated enough.

### ISSUE THREAD

**Issue by strangeminds** [grafana/grafana#21987] opened 2020-02-06 21:46 UTC
**What happened**: Updated to Grafana 6.6.1 today and after a while, the Loki Datasource stopped allowing us to query logs.  The "Run Query" button seemed to have stopped working.   Chrome Developer console showed us the error:

parse error : **syntax error: unexpected $end**

```
Request URL: https://xxxxxxxx.xx/api/datasources/proxy/1/loki/api/v1/query_range
Request Method: GET
Status Code: 400
Remote Address: XXX.XXX.XXX.XXX:443
Referrer Policy: no-referrer-when-downgrade
:path: /api/datasources/proxy/1/loki/api/v1/query_range
```

Downgrading to Grafana 6.6.0 and restarting Chrome fixed the issue.

**What you expected to happen**:   The "Run Query" button should pull in logs from Loki.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This issue happened to me and confirmed by another person.
Running Loki in AWS with dynamodb & S3.

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Loki 1.3.0
- OS Grafana is installed on: Kubernetes 1.14.10
- User OS & Browser: Mac OS 10.14 - Chrome 80.0.3987.87 - Safari 13.0.4 (14608.4.9.1.4)
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment] 2020-02-07 08:32
Thanks for reporting this, we'll look into it!

**Comment by aocenas** [comment] 2020-02-07 08:53
@strangeminds So far I was not able to reproduce this. Can you post also the full request with the query params from the networks tab to see the query that was send?

**Comment by strangeminds** [comment] 2020-02-07 14:32
@aocenas I was able to reproduce the issue this morning.  I upgraded again to **Grafana 6.6.1-ubuntu** and Loki pulled logs fine.  I ran the same search over and over again for about 30 minutes, maybe clicking "Run Query" a few dozen times `{app="alb-ingress-controller"}`.  The query was for the last 1 hour and kept pulling in the last 2000 log lines.  Then for an unknown reason, Grafana stopped pulling in logs and now will only show two logs lines.
`Limit: 2000 (2 returned)` - exiting Chrome or changing the query time range does not help.  Clearing Chrome cache now yields no results for that same query.  I tried to reproduce the same issue running another query `{app="grafana"}` but so far that is still pulling in new results.

Here is the full request, thank you!

```
Request URL: https://xxxxxxxxxx.com/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=2000&regexp=&query=%7Bapp%3D%22alb-ingress-controller%22%7D&start=1581079442000000000&end=1581083043000000000&step=1
Request Method: GET
Status Code: 200 
Remote Address: xxx.xxx.xxx.xxx:443
Referrer Policy: no-referrer-when-downgrade
content-length: 946
content-type: text/plain; charset=utf-8
date: Fri, 07 Feb 2020 13:44:02 GMT
status: 200
x-frame-options: deny
:authority: xxxxxxxxxx.com
:method: GET
:path: /api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=2000&regexp=&query=%7Bapp%3D%22alb-ingress-controller%22%7D&start=1581079442000000000&end=1581083043000000000&step=1
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: messagesUtk=d9698b4495b28934ed39d12a3f5b98d4; _ga=GA1.2.550994314.1508178812; _fbp=fb.1.1549300131618.1840702137; hubspotutk=d9698b4495b28934ed39d12a3f5b98d4; sandbox.user.id=BAhpCw%3D%3D--c252341794c83048707b863faa8016ba5a406092; staging.user.id=BAhpCw%3D%3D--65b565d4cb4001731eea56c151edb6fbf03780b3; __hs_opt_out=no; ajs_group_id=null; production.user.id=BAhpAh4C--4d6b62e988206ab3898393e1cc8f8131f433ff25; __hstc=119598103.d9698b4495b28934ed39d12a3f5b98d4.1572638845313.1580156327662.1580234880661.14; _gid=GA1.2.821270854.1580743079; LokiSessionCookie-0=WTnm5L61GySYUC7vsREx7Qom/muSqY7iEbc+4/OFtvnyr/vs9qOBB8kTV7Wtt12ZoqLIJT4wpJNoHSNsG/wVyqlcv7QTETd2hpB36qS4L2pBriaVz0a301soGL6mH0xZ17qz3SLG+Tqih/va7XgQmOhfqE5LPVbtX3+r+H1fVgj6HEq9E0c2jiDNNR6YVMKrJSqgzf+Nsi6a+cD6v0DRqGwSxxzzlrX4C6xsQuBfXRTLESqi88DtG4rAkjo0W+KJwe0MBTwGS1DHJ6Al7Nm6edOCG7s9S2z/kVJbtBaKVnyLgG4IIhwtKLKbfGg6J+ahF6omIUhdCntDKzhAYKoYejAVs23JcLKTLUqTWnfSscnTzDBbQ2HQYi/5d3B1I4X0vIduadXeVdMZpRir2ZM9eQoNYyXeqdYrYnV8JhCAFFl+dlcNVdezGXH4g1e5Se0mdwBZK01u6NLfhSJsjaME2fi2Q7+8HiAR6mVWhgPukNHcJXzg3bo96bvv504C26j6DKt790OorHsqym0XNhcSYIrPmlbCNaZ5gXv3Wgwy4jPf65lD6eOzl2svzYUGrGlzU0a5anJY42QAVfis9DRKBeKuXKHBNv+dXfQelEdD2rxsjs3NicJGzN6P2GviXkiWafM4GVKcc2DU43abQI0Q9T4SHcfmyHClH+PrD3uJQbTRVwFNRQh5rytB25ShUdDRf/ivzOSAFnt4ceMr05+3bwxZznEpLOlgsg8cCHNsN4O+YB+xoisUTJZcbsptI77RvQLGpDZzUP1gnv1PY+RkSeb5G6R5anZ8PvgKtCNCqNSjpdkBwrVH/yx4B0MnJhrS+3dTIewlAHrNsWnezmwVmJCa1Rd3tKiXwe5wUFPJ/XAH3ny7MGEAgYv4R6m+JAuGawFc77mFxO3VkFaLQ/vAYAs8PLRE4ReL/OE2Fc6MCxhpmjnonqd9F6WxTjU9FkzXAM3NiTLKL3hSNhO8r9JREp+Jw/8XSD5tvMkCJ6DOh0vLp4YKzFnDKGf5q9XbSkkGf60ZNd/toZiQm4Hp8MVuM6EroAhbPyShg5T884LLcWCtS4jHJpwGxTTmw6ZXhwYF146eBWva3hM4tDGGNAwrqB+5ODUYj7BbNsIdt2R8pxRCyvHw9KQ3C7ilRryboayUke/yNHC+wXmkpvQ/R2lyaA2U1hae4dVhKyIJqBqv2ZZFZDT/bf6qbSBCm+N4UJPCTuRKrkfIUPkPBnj0iZ8U1GXYno/VlFMljXDl4/9xwoVYSddGzp2+EJ6rkOXu5eyMU9/grVy6/ro8e5co9KmU2z1oPTo1rVpHFwL3e0uvzeXoRA9RIpvk9tO/6oxc1XV0nQ4h/8l2q81s+v5mNsr1wv+mceq1xbBFQSXz/BlhzC/6mPc5rFmN6B57zDa3iHOlY3KNK2hAADgn0WW5mMDLHoDHzDn2v1tyhq0n14tAhKhzube3UUBumSakr9ZHyDAc/093a7XTIYpFhLUyh3ceIXbkV4uup31uc7Erj127GfOYJCUcj7FWuZWyXKhoDAZrjk1/VWsA1Ace2L0TUwn4L3vtFXrIqx7Gc+5o4gMsOEvtkYec7jSndelIwVMxPYXr00+T5gV2LToxNRr5RRKQShbNwmRSMmAgaz5uEGQAfIXNtfW5EQ8q/jo3WCRYNFSPa+Dq4d1xNYmw3w8JbZXUHmxEAtEjt2F+kIeQ6auxIP8aYdpp2Gloe8h4qV5bJ7G+HkvlvP4c7c1ISuFyPlKdoGhwBU8y5B2rm4EL5UqLZdeZzX7I6uamjZbwYU2Mookd40k27ZrvJViGdpj4P8zSnRMN8HHPTkelEQ2gdSpis3z40iiygXNf4ZH2kkMbX3xo6TQm0h8enPoXID0xZ0V35bj0Tz2rg+XzdG3epC6cx/L99DljvOF2JFxNZmcg7ezPsh2nu1n5bSj8puglbRnUqWl856LY8BUm28/SL7mAQQnm0ikcOOKhFDqKwJgRf4zdySkwAdR3IHjUBf0InY8f3uk0do1pjAaqMavjCUsqYdT3nm4oE55NBgtOdniaaoh1LrTzsffW6DE8Wa4FQNDvS/e2qf1gH0/gu3TOO9jiUPznDe8dvqJAgLsN6mxb6jk9VICwI5ATK8KBRhWWN7CimOl060gxzZCPXpMqu02JpC7C9CUBuSxXJErmmD49Q6kHa3jj/ppvTCEJWKPyttupvVK5wYcVASOwE0LLNNnkL/65N8G79NDj7LKRPqigp5VeJurxbFZ9vh4DhCi6DQyE/0TS/7+pbS7Kn+4jm+DlYTf3yM9aYDfyLvXIFXANf7AONEyVHO7B747Pe7je6J325f0Y9/hPz64pjUxUJiGcNkSogNrhd8eAlOKr11NssZ3hscVNMmaDu9bOmHuMz7ee0sh02BP8AcIF/W7+7YMnsz13ij43JwRqSTdWcUKI/Kr345hB12nghG6CrU7X6/QqxYjmELoJkd4c0NPAQ57eFgUZH1QzpnbJuALDsW1gKk02EUqzSN3Ud0yeJkVJWoG6PFpA7lkQmuBgw1MebgxZf6DzWILrZ27Rhu280HGlPLbSQiC+JAWTjh/5EtNzoxCgg7AI3pRijYjCkx2NYY65vZ9u7JLJpCQrfmFPGVYbEt1JkTgZ/SKCxP3zhKfjUeBqVodYjUN+vvrs9fUM9tV97uBWY/YnRL272XtvHdcSFgvkdvYdlTPj327OI3zk990c0y8Cby2DdXC6AZV9hBw4FWjWkpUMjGqyDqHJQLate5rm2JzUho9divVCj4Uz5KUQWUCampvIgF8g+gw9sAGMYQdgq5kN8JViGAYQvhStNBtcsjeZldPxHipJOQfWIRBuFtjxuSyie1fL2a+fDsYwvGVHiqz+DO86bigwYufBCLfyL6ZSoXYeaFb6CDusRr3y/L3RZMBoaRephyK4Puadl75FhzMe2Ahj/wE4HGWMHpe3eL6ujTibTobXy3vGS8vhyxXkj2H2UVh640V9CriNuPslI6TpiYreOiOod4mdZmBT7y/XyyeZdVO74HSKHB0ae3TqmP/4JfymHywlvvoOl/Qzc4tA0PpjK6GMqixVlk0uv3oHbZkvwFtRAB3sbFeTaA74lXrQeRyCLs20YvBkHTUWt75BghtlcMIoCEnlD/nNwSPfCS49mNmkOpLmwcmjPKo2/BPYcWtJqqUCci0q2qxKOhXwpsZBv6JcDNE1nC7aYP75Sd4fWKQP6jSGAhW5tALFB4FNOS6x3QkhvzAWgpZBOdkHQUau30Uoh12RSb7rP50y8qp2zbuvbg+4R+QiM+4MVXAqE0P3TAkS6IDo3yaN5BZvY89PPo/uTBLt3IpK05/Yg58hPeeJ02sgPbfZhHTrAvol7xQf070DK8BuCq6KzmRBzZgYeZn2v90HjfBPqilUeQZnOc1fqOcwqOq4ZRz2DGEM7BT92vfrky/qbQ72IeUc9CKM6WLMUtyW3slTzClgIB2lKrCIZMWLl8Y7LyUv0fVh2ks7g+VfthaKtp0IyW3i0rnclSTEps6c0kOqs8eZnm/BbBdL2ZRX+G876e/KNPNPL2vYCr9bk1RIh1+akIiX8o8q15kPUxHiJSttqFO0i5XdelKwqgKX5jO+wNqtPymfoe3EhYzfcI9aJwvRM3l1ARMnHPX7L/NL/y9WRWMOCTV89zQHkykN3LLImBdjaZAx3+oSmzLVntJZZDN3Ew8yCwfSz7IkB77Wr4WxrCwguIRuoObfzT0OsZtdEjvvBwogP4at2OTWd7cyAfNVRdPG6HOWdJLGxKvw8KEyK7UmBEnqcYkQu0mk3XaA04UfdsZAQr5D+8XkoGihN2EM8JUVr/cxgrnPGw==
pragma: no-cache
referer: https://xxxxxxxxxx.com/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bapp%3D%5C%22alb-ingress-controller%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
x-grafana-org-id: 1
direction: BACKWARD
limit: 2000
regexp: 
query: {app="alb-ingress-controller"}
start: 1581079442000000000
end: 1581083043000000000
step: 1
```

**Comment by strangeminds** [comment] 2020-02-07 14:40
Sorry, I forgot to say, the first error I reported in this bug report `parse error : syntax error: unexpected $end` seems to not be related to this issue.  I get the same error in **Grafana 6.6.0-ubuntu**, yet that version has no issues with Loki logs.

Thank you.

**Comment by strangeminds** [comment] 2020-02-07 15:55
@aocenas I thought I was able to reproduce this issue this morning, but I was wrong.  The `parse error : syntax error: unexpected $end` error seems to be unrelated to what we experienced last night.  Downgrading to Grafana 6.6.0-ubuntu seems to give us the same error, yet Loki works fine.

I'll keep testing and see if we experience the same issue again with Grafana 6.6.1-ubuntu.

Thank you.

**Comment by strangeminds** [comment] 2020-02-07 17:54
@aocenas I think we found the issue.  For some reason the "Enable/disable query" eyeball icon was clicked.  I'm not sure if this was caused by Grafana 6.6.1 or just user error.  The engineer that reported the issue was sending me direct links and I saw the same as they did.  Today he had the same issue and he figured out the icon was disabled.

<img width="125" alt="Screen Shot 2020-02-07 at 12 52 21 PM" src="https://user-images.githubusercontent.com/796234/74052975-e693ca00-49a8-11ea-861f-07258f4a5b96.png">

**Comment by aocenas** [comment] 2020-02-10 16:02
@jessover9000 @sarlinska this seems like a good datapoint for the UX of the disable button.

**Comment by hhromic** [comment] 2020-04-30 09:06
Hello, I'm experiencing the same error here in a different setup with latest Grafana and Loki:

```
Request URL: https://server/api/datasources/proxy/6/loki/api/v1/query_range
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 16.200.32.151:8300
Referrer Policy: no-referrer-when-downgrade

parse error : syntax error: unexpected $end
```

I'm using Grafana `6.7.3` and Loki `latest` using Docker on my own private servers.
Loki latest for me is `grafana/loki:latest@sha256:0c80891f063390e0a2ce8122506d650cebb882c5e8fa0daa551de514bfed4aca@sha256:22de65ef5d368442ac9b41c9d57b5b9f2e9acd907b451cad3c4863d15219b0af`.

The eye-ball icon does not seem to matter because this also happens as soon as I open the Explorer section and selecting Loki as a datasource, no queries necessary to trigger. For example the following Grafana URL gives me the error in the console immediately:

    https://server/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22loki%22,%7B%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by phoerious** [comment] 2020-05-06 16:02
I can always reproduce it when I leave the explore tab open for a while (several minutes) and then hit F5 or "Run Query". When I close it and come back after a while, it's often working again.

**Comment by sarlinska** [comment] 2020-05-07 12:44
@Estrax this doesn't seem like an issue where @jessover9000 or I need to pitch in, right?

**Comment by Estrax** [comment] 2020-05-07 12:47
@sarlinska UI/UX-wise it was solved quite some time ago, the latter is solved as well in 7.0.

**Comment by Estrax** [comment] 2020-05-07 21:47
Confirmed to be working properly in 7.0. Closing this issue.

**Closed by Estrax** 2020-05-07 21:47 UTC
Labels: area/explore, area/ux, type/bug

**Comment by phoerious** [comment] 2020-05-08 10:32
I upgrade to 7.0.0-beta3 and still had problems with the data result being empty. I didn't see a 404 status response anymore, but I got no labels and no data at all. After reducing the Loki  deployment size to one, everything started working smoothly.
