### ISSUE TITLE
ad-hoc filter is missing 'remove', POST /api/v1/labels fail with code 500, missing body with start and end time

### ISSUE THREAD

**Issue by valdemarpavesi** [grafana/grafana#56479] opened 2022-10-06 14:53 UTC
Ad-hoc filter is missing 'remove' and not able to remove the filter

'remove' option shall appear on combox

Grafana is sending POST  [/grafana/api/datasources/218/resources/api/v1/labels]
to get all labels, it will fail with code 500

The POST is missing a body with start and end time

https://prometheus.io/docs/prometheus/latest/querying/api/

start=<rfc3339 | unix_timestamp>: Start timestamp. Optional.
end=<rfc3339 | unix_timestamp>: End timestamp. Optional.
match[]=<series_selector>: Repeated series selector argument that selects the series from which to read the label names. Optional.

There is another way to list all labels from Prometheus by a variable: 
label_names()

It is working fine because it has a POST body with start and end time

it takes 7 seconds to get all labels.

POST ok, with payload
![image](https://user-images.githubusercontent.com/10376101/194345456-9a849cb1-53ab-47dc-b13f-70b2cca9390a.png)

POST fail, missing payload:
![image](https://user-images.githubusercontent.com/10376101/194346912-0fc0d168-9913-4d85-814e-0d7c90e70b70.png)

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: Prometheus latest
- OS Grafana is installed on:
- User OS & Browser: K8S
- Grafana plugins:
- Others:

**Comment by valdemarpavesi** [comment] 2022-10-06 16:44
same problem, ad-hoc by table or by variable-adhoc

![image](https://user-images.githubusercontent.com/10376101/194370860-ca13b6dc-0e28-4054-b61f-b144d2953193.png)

![image](https://user-images.githubusercontent.com/10376101/194370932-6e3678a4-f904-4db9-94fa-63a5f9277ab5.png)

![image](https://user-images.githubusercontent.com/10376101/194371039-df2aced8-1938-4265-b266-e0b4566eb4bc.png)

![image](https://user-images.githubusercontent.com/10376101/194371106-1ad360b6-e5e5-4b98-9a3c-a71aab6ae580.png)

**Comment by itsmylife** [comment] 2022-10-27 18:32
Hi, @valdemarpavesi Thanks for reaching out. I cannot reproduce the issue. Could you please provide a `.har` file or a reproducible environment?
Also, it would be very useful if you can explain the steps that you ended up having this inconsistency. In my case, I add ad-hoc filter and test a couple of times and couldn't see any problems.

**Comment by valdemarpavesi** [comment] 2022-11-04 17:37
Hello @itsmylife 

It will occur with a big Prometheus database.
The problem with the ad-hoc filter is the missing body for a POST request.

There is timeout 500 due not able to transverse the database.

It is missing the body with
start=<rfc3339 | unix_timestamp>: Start timestamp. Optional.
end=<rfc3339 | unix_timestamp>: End timestamp. Optional.

regards!
Valdemar

**Comment by itsmylife** [comment] 2022-11-09 22:37
Linking a possible related issue https://github.com/grafana/grafana/issues/56943

**Comment by itsmylife** [comment] 2022-11-09 22:38
@valdemarpavesi Thanks for the response. I will try to reproduce or at least find a way to create timeout state.

**Comment by itsmylife** [comment] 2022-11-10 13:41
@valdemarpavesi I can get the response without POST body. I cannot really reproduce or pinpoint anything. 
Could you please provide a `.har` file and a dashboard json? Those might help me to detect the issue.
Thanks

**Comment by valdemarpavesi** [comment] 2022-11-16 17:21
@itsmylife the key to solving this problem is label_names()
it will send a POST with start-end 
but, ad-hoc will query to get all labels, not sending the time limit.
how complicated yes, to just add the start-end time to force not transverse the entire Prometheus database?

**Comment by valdemarpavesi** [comment] 2022-11-16 17:36
please see the time to get all labels

![image](https://user-images.githubusercontent.com/10376101/202250350-4da92a75-3b9f-4cf7-a3fa-afe979633786.png)
![image](https://user-images.githubusercontent.com/10376101/202250903-8d3ee371-63b4-4522-8896-e365fcb5fad0.png)


:path: /grafana/api/datasources/proxy/78/api/v1/labels
payload 
start=1668597857&end=1668619457

+++++++

**problem with ad-hoc:**
![image](https://user-images.githubusercontent.com/10376101/202252123-ddbc26a5-0ac5-4bbd-b30a-947cecb5ee9c.png)

32seconds fail
![image](https://user-images.githubusercontent.com/10376101/202252619-e58c5c6e-4eb8-4d70-b804-18fa41a1d189.png)
:path: /grafana/api/datasources/proxy/87/api/v1/labels

missing body
![image](https://user-images.githubusercontent.com/10376101/202252812-92f5778b-670b-4130-a5fe-931b368d4cd0.png)

+++

the problem is just the inconsistency, one way has a body and another has no body, so there is no reason to have the body missing, just the body missing is a problem.

after fix, the body, ad-hoc will be fixed automatically.

**Comment by itsmylife** [comment] 2022-12-01 12:19
@valdemarpavesi I created a PR to address this. Will you be able to upgrade your Grafana instance to `v9.3.2` once it will be released?

**Closed** 2022-12-02 18:11 UTC
Labels: type/bug, datasource/Prometheus, needs investigation

**Comment by valdemarpavesi** [comment] 2022-12-14 14:46
@itsmylife, yes, thanks for your work.
