### ISSUE TITLE
Share entire dashboard as iframe

### ISSUE THREAD

**Issue by p4block** [grafana/grafana#31631] opened 2021-03-03 10:39 UTC
**What would you like to be added**:
An option in share menu to embed iframe the entire dashboard page, just like you can do it with individual charts. Kiosk mode could be leveraged to do this. 

**Why is this needed**:
Currently, we use Grafana to display charts from various CSV datasources (great new feature) at a different site. This implies **a lot** of iframes, and the structure of the dashboard is lost and has to be re-done in HTML at our site. It also takes ages to load with a lot of network usage even on gigabit. 

There is a kiosk mode and embedding that is possible, but there are plenty of keys that allow the user to escape the kiosk mode and access the grafana UI (specially esc,  f). This is a dealbreaker because users will "break" the site, however, this single iframe kiosk is easily 5x faster _or more_ to load. 

I know the security implications of embedding charts and I accept those as I am using Grafana only to visualize publicly available data, there is no concern of users poking URLs and accessing different dashboards with different datasources. 

I feel like our usecase isn't even contemplated by Grafana, but it is amazing software that solves our file parsing+plotting problems and it would really help us if this was possible.

**Comment by torkelo** [comment] 2021-03-03 19:34
duplicate of https://github.com/grafana/grafana/issues/13706

**Closed by torkelo** 2021-03-03 19:34 UTC
