### ISSUE TITLE
Graph Panel shows invalid data for crosshair position (MySQL Data Source)

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#15639] opened 2019-02-25 14:44 UTC
I am using Grafana 6.0.0beta3

I noticed when there is no data available for the period  the cross-hair shows wrong data 

![image](https://user-images.githubusercontent.com/3651746/53344890-b6f7c900-38e1-11e9-841d-93a96fca0f9d.png)

As you can see the crosshair is positioned at around 7:30  and there is no data available for this time,
however it shows the data for 9:34 which happens to be the latest (current) time. 

Expected Result:  It would expect the crosshair to show the time which matches it position on the graph and also matching data (no data in this case)

**Comment by xlson** [comment] 2019-02-26 13:02
Not sure about this one. Technically it would be correct to not show any data, at the same time, showing whatever data exists nearest in time is useful.

@davkal @Ijin08 @torkelo What do you think?

**Comment by PeterZaitsev** [comment] 2019-02-26 13:14
This is artificial example of course.  But in general "gaps" - the lack of data can be very meaningful event 
and hovering over small gaps it might be pretty misleading when the other data point is shown.

Also I think we already have full NULL option, which allows to treat nulls differently if so desired ?

**Comment by Ijin08** [comment] 2019-03-04 08:19
I think I Have to agree with @PeterZaitsev . Can lead to confusion to show value where there is no data. Not sure if there is a good way to show that there is no data and also show nearest data.

**Comment by torkelo** [comment] 2019-03-04 10:51
@PeterZaitsev What is the data your query returns in this case? and what is your graph null value option?

**Comment by torkelo** [comment] 2019-12-02 09:36
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment] 2020-11-10 14:53
duplicate of https://github.com/grafana/grafana/issues/6946

**Closed by torkelo** 2020-11-10 14:53 UTC
Labels: area/panel/graph, type/discussion, type/ux
