### ISSUE TITLE
Mobile view: panels not loading after opening an initially closed row

### ISSUE THREAD

**Issue by dnnshssmnn** [grafana/grafana#38549] opened 2021-08-25 12:54 UTC
**What happened**:
This happened after upgrading to 8.1.x. After opening a dashboard on the mobile version, the panels in the rows that are saved in open state will load and are correctly displayed. However, when opening a row of the dashboard that is saved in closed state, those panels will not load. Only the background is visible as if they were invisible. 

**What you expected to happen**:
The panels will be loaded and displayed after opening a row.

**How to reproduce it (as minimally and precisely as possible)**:
Save dashboard with a row in open state and a row in closed state. Load the dashboard in the mobile version. After it is loaded, open the closed row.

**Anything else we need to know?**:
Downgrading to 8.0.x fixes the issue.

**Environment**:
- Grafana version: 8.1.2
- OS Grafana is installed on: Ubuntu 18.04.5 
- User OS & Browser: Windows 10, Firefox 91.0.1 and Chrome 92.0.4515.159

**Comment by mckn** [comment] 2021-09-02 08:12
Closing this one since I'm not able to reproduce it.

**Closed by mckn** 2021-09-02 08:12 UTC
Labels: area/dashboard, needs more info
