### ISSUE TITLE
Prometheus: Strange editing behaviour when dashboard is refreshing / query is executed 

### ISSUE THREAD

**Issue by AeroNotix** [grafana/grafana#28955] opened 2020-11-09 23:47 UTC
**What happened**:

Editing queries while auto-refresh is enabled, or if the dashboard refreshes for any other reason causes the query input box to behave strangely.

* Executes the previous query
* Removes text that is being edited

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.3.0 (though I saw similar issues in previous versions)
- Data source type & version: prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Linux/Chrone
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2020-11-10 07:09
Not able to replicate the issue where text is being removed but I do find the editor moving about because the metrics button at the left switches to loading state every query execution.

![image](https://user-images.githubusercontent.com/10999/98641455-17d06a80-232c-11eb-9fdb-5b938ea4fbd1.png)

**Comment by torkelo** [comment] 2020-11-10 07:13
We need to cache these metrics metadata requests, we should not executee them on every query refresh & for every query editor 
![Screenshot from 2020-11-10 08-12-01](https://user-images.githubusercontent.com/10999/98641676-74338a00-232c-11eb-9d02-0b1e7ff751bd.png)

**Comment by torkelo** [comment] 2020-11-10 07:17
This logic refreshes metrics for all queries every refresh: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/components/PromQueryField.tsx#L189

range will change every refresh if you have a time range that is like last 5min,

**Comment by aocenas** [comment] 2020-11-10 09:17
May be fixed by this https://github.com/grafana/grafana/pull/28622 as it prevents the loading state on metrics refresh.

@torkelo 
> We need to cache these metrics metadata requests

I think this was sort of conscious decision. The reason is that if you start scraping some data you probably want to see it as soon as possible and so we do the request because the time range changed. Caching would create delay or you would have to refresh the whole page (annoying when creating a new panel/dashboard). We could at least cache it per datasource so if you have multiple queries it does not do request for each.

**Comment by AeroNotix** [comment] 2020-11-10 11:02
One way I found to consistently reproduce the issue is to:

* Edit the query to a valid query, watch the dashboard load
* Edit the query to an invalid query, allow dashboard to show the red triangle
* Highlight text in the query editor
* Soon the dashboard will issue a "phantom" refresh
* Highlighted text is removed.

**Comment by mgabeler-lee-6rs** [comment] 2020-11-10 14:24
I've been able to reproduce this simply by highlighting the existing, valid, query text

**Comment by ivanahuckova** [comment] 2020-11-12 16:46
Grafana 7.3.2 was [released](https://community.grafana.com/t/release-notes-v7-3-x/37993) yesterday and it includes the fixes #28622 for the issues that are related to those mentioned here -> e.g. copy paste behaving as cut and paste and jumping metrics button. With 7.3.2 I wasn't able to replicate the issues mentioned in this thread, but could you please check if the issues you are describing were fixed and/or if there are any issues still present, so we can close the issue. 🙂🙏

**Comment by adamdougal** [comment] 2020-11-17 13:41
I was able to recreate this in **7.3.1** by highlighting the query as @mgabeler-lee-6rs pointed out. After updating to **7.3.2** the issue is resolved.

**Comment by zoltanbedi** [comment] 2020-11-17 15:10
Thanks for confirming this @adamdougal. I'm going to close the issue now.

**Closed by zoltanbedi** 2020-11-17 15:10 UTC
Labels: area/ux, datasource/Prometheus, type/bug
