### ISSUE TITLE
"Kibana visual builder"-like that allows calculation for ElasticSearch queries

### ISSUE THREAD

**Issue by erouvin** [grafana/grafana#10806] opened 2018-02-06 23:19 UTC
Hi

I am looking for something similar to what Kibana offers with Visual Builder and Calculation feature.
Something like `"script": "params.tShirtSales / params.totalSales * 100"` as described in [Bucket Script Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-script-aggregation.html#search-aggregations-pipeline-bucket-script-aggregation)

This was related within issue [#3163](https://github.com/grafana/grafana/issues/3163) but it would be better to have it embedded within the panel options ( e.g. Singlestat ) rather than changing the JSON itself. This is really useful for Key Performance Indicators which involve several parameters.

Grafana v4.6.3 (commit: 7a06a47) against ElasticSearch

Thank you.

**Comment by torkelo** [comment] 2018-02-07 09:35
duplicate of https://github.com/grafana/grafana/issues/5968

**Closed by torkelo** 2018-02-07 09:35 UTC
