### ISSUE TITLE
Unable to build image from Dockerfile v5.3.2

### ISSUE THREAD

**Issue by hassanfarid** [grafana/grafana#14003] opened 2018-11-08 16:55 UTC
I am using following script to build image from docker file. 
My environment is:
```bash
$> docker --version
Docker version 17.06.0-ce, build 02c1d87

$> cat /etc/system-release
CentOS Linux release 7.3.1611 (Core)

```

```bash
mkdir -p cb_deployment
cd cb_deployment

## Deploy Grafana
git clone https://github.com/grafana/grafana.git
cd grafana
git checkout v5.3.2
docker build -t cb_frontend:poc-release .

```

I get following error:

![image](https://user-images.githubusercontent.com/782236/48213833-ab8d8b80-e34c-11e8-9107-b98d31575b52.png)

**Comment by xlson** [comment] 2018-11-12 12:47
@hassanfarid I just did the same build with a fresh copy of v5.3.2 on my local machine and I do get the slate error, but the build keeps going. Most likely the issue is related to your version of docker. I'm running `Docker version 18.06.1-ce, build e68fc7a215`.

**Comment by hassanfarid** [comment] 2018-11-14 23:50
I have the latest version now, still getting same error on a different module each time.
```
$> docker --version
Docker version 18.06.1-ce, build e68fc7a
```

**Comment by xlson** [comment] 2018-11-16 13:11
@hassanfarid It could perhaps be related to selinux. You could take a look at system logs and docker logs to see if anything jumps out at you.

**Comment by hassanfarid** [comment] 2018-11-28 13:31
@xlson  - is there anyway I can identify and resolve this?

**Comment by xlson** [comment] 2019-01-09 14:13
Closing this as we haven't received any more details

**Closed by xlson** 2019-01-09 14:13 UTC
Labels: comp: docker, state: needs more detail, type: build & packaging
