### ISSUE TITLE
Error building Grafana RPM on CentOS 8

### ISSUE THREAD

**Issue by dirtyren** [grafana/grafana#26587] opened 2020-07-24 13:53 UTC
**What happened**:

  Grafana build on CentOS 6 and 7, but not on 8

**How to reproduce it (as minimally and precisely as possible)**:

  Download v7.1.0 and try to build RPM

** Error **

*** ERROR: ambiguous python shebang in /usr/share/grafana/scripts/build/ci-msi-build/msigenerator/generator/build.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.

**Environment**:
- Grafana version: v7.10
- OS Grafana is installed on: CentOS 8

**Comment by aknuds1** [comment] 2020-07-24 13:57
Can you please explain how you try to build the RPM in the "How to reproduce it (as minimally and precisely as possible)" section?

**Comment by dirtyren** [comment] 2020-07-24 15:04
hey @aknuds1 , the problem is here in CentOS8 , RPM complains that can not set python on this script

scripts/build/ci-msi-build/msigenerator/generator/build.py

  I think its because CentOS8 comes with both python2 and python3 and doing a sed to change  it on the script, solved the build
  This sed is done in the spec file

sed -i -e '1 s/^\#!\/usr\/bin\/env python/\#!\/usr\/libexec\/platform-python/' scripts/build/ci-msi-build/msigenerator/generator/build.py

Hope I could help, anything else please let me know.

[]s.

**Comment by dirtyren** [comment] 2020-07-24 15:06
We came with the above solution from here

https://github.com/aws/efs-utils/pull/55/

**Comment by aknuds1** [comment] 2020-07-24 15:10
I understand the basic error, but please do as I asked previously so I can understand how this happens.

**Comment by aknuds1** [comment] 2020-07-24 15:11
I need to see if this is a valid problem or not.

**Comment by dirtyren** [comment] 2020-07-24 16:35
we have a customized spec file that build Grafana using this script
After the build, rpmbuild throws that error above about the python env.
With sed changing the string on the script. rpmbuild goes ahead and creates the pkg.

Let no know, tks.

`#!/bin/bash

cd go/
export GOPATH=$PWD
export GOBIN=/usr/local/go/bin/

# Download latest grafana
echo "Download latest grafana."
go get github.com/grafana/grafana

# Enter grafana directory
echo "Enter grafana directory."
cd src/github.com/grafana/grafana/

# Get stable version 6.4.3
echo "Get stable version 6.4.3."
git checkout v7.1.0

sed -i -e '1 s/^\#!\/usr\/bin\/env python/\#!\/usr\/libexec\/platform-python/' scripts/build/ci-msi-build/msigenerator/generator/build.py

# Backend: Go setup
echo "Backend: Go Setup"
go run build.go setup

# Backend: Go build
echo "Backend: Go Build"
go run build.go build

# Frontend: Yarn Get Dependencies
echo "Frontend: Yarn Get Dependencies."
yarn install

# Frontend: Yarn Build
echo "Frontend: Yarn Build."
yarn build --force
`

**Comment by aknuds1** [comment] 2020-07-25 10:11
Can you please specify how you try to build the RPM? That's the information needed to tell what's going wrong here, and your above script only builds Grafana, it doesn't get into packaging. To be honest, I think you're doing something wrong during packaging since RPMs shouldn't contain scripts/build/ci-msi-build/msigenerator/generator/build.py. That script is for generating Windows installers.

To see how to package Grafana with RPM, I would instead extract an official Grafana RPM and see what's contained.

**Comment by dirtyren** [comment] 2020-07-27 19:45
Tks @aknuds1 , it was a problem in our SPEC file. Do you know wher I could find the official Grafana SPEC file or rme SRC RPM? Tks

**Comment by aknuds1** [comment] 2020-07-28 04:35
Sorry, we don't have any RPM spec file or source RPM. Closing, since it's not a Grafana issue.

**Closed by aknuds1** 2020-07-28 04:35 UTC
Labels: needs more detail, type/build-packaging
