### ISSUE TITLE
Invalid URL link to Grafana OSS v9.2.2 (78a3e64e4f) release notes

### ISSUE THREAD

**Issue by usmangt** [grafana/grafana#57816] opened 2022-10-28 10:27 UTC
**What happened**:

After installing Grafana OSS v9.2.2 (78a3e64e4f) on local machine and clicking it during the login page in the footer does not open the correct link to the release notes as the link is set to https://grafana.com/docs/grafana/latest/release-notes/release-notes-9-2-2/

which says 404 not found

**What you expected to happen**:

Link to correct release notes

**How to reproduce it (as minimally and precisely as possible)**:

during a local install after upgrading from Grafana OSS v.9.0.x to v9.2.2 

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: v9.2.2 
- OS Grafana is installed on: CentOS ver 7
- User OS & Browser: Chrome

**Comment by usmangt** [comment] 2022-10-28 10:37
Ah just saw on the [page](https://grafana.com/docs/grafana/latest/release-notes/) 


that;

**Note**: As of Grafana v9.2 we no longer publish release notes, which are redundant with other release lists that we publish:

The suggestion would be to make the link redirected to the above page so as to avoid confusion.

**Comment by mckn** [comment] 2022-10-28 16:00
Duplicate of https://github.com/grafana/grafana/issues/57782

**Closed by mckn** 2022-10-28 16:00 UTC
