### ISSUE TITLE
OR operator in ad-hoc filter

### ISSUE THREAD

**Issue by farzanehataei** [grafana/grafana#31220] opened 2021-02-15 15:10 UTC
Feature request to have OR operation between Adhoc filters.
Currently when we select different adhoc filters, they are queried using AND operation. It would be really helpful to have option to choose between AND & OR operation for different adhoc filters.

Datasource: elasticsearch

**Comment by hugohaggmark** [comment] 2021-02-16 05:19
Duplicate of #10918

**Closed by hugohaggmark** 2021-02-16 05:19 UTC
Labels: area/dashboard/templating, priority/awaiting-more-evidence, type/feature-request
