### ISSUE TITLE
Generic OAuth (Dex) - Empty user info JSON response provided

### ISSUE THREAD

**Issue by cmanzi** [grafana/grafana#20383] opened 2019-11-14 14:15 UTC
**What happened**:
When using Dex as a generic OAuth provider (connected to Okta via SAML), I am able to log in, but the role_attribute_path configuration does not work because Grafana cannot get the userinfo for the token. When I log in, my user is assigned the 'Viewer' role.

Below is my config file:
```
[analytics]
check_for_updates = true
[grafana_net]
url = https://grafana.net
[log]
mode = console
[log.console]
level = debug
format = json
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
domain = grafana.example.com
root_url = https://%(domain)s
[auth.generic_oauth]
name = Dex
enabled = true
scopes = openid profile email groups
client_id = grafana
client_secret = secret
auth_url = https://dex.example.com/auth
token_url = https://dex.example.com/token
api_url = https://dex.example.com/userinfo
role_attribute_path = contains(groups[*], `SRE`) && 'Admin' || contains(groups[*], `devops`) && 'Admin' || 'Editor'
```

Here are the relevant logs:
```
{"logger":"oauth","lvl":"dbug","msg":"OAuthLogin Got token","t":"2019-11-14T13:50:16.27554324Z","token":{"access_token":"eyJh...","token_type":"Bearer","expiry":"2019-11-15T13:50:15.27551416Z"}}
{"data":{"name":"someone@example.com","display_name":"","login":"","username":"","email":"someone@example.com","upn":"","attributes":null},"json":"{\"iss\":\"https://dex.example.com/\",\"sub\":\"...\",\"aud\":\"grafana\",\"exp\":1573825816,\"iat\":1573739416,\"at_hash\":\"...\",\"email\":\"someone@example.com\",\"email_verified\":true,\"groups\":[...\"SRE\",\"Users\"...],\"name\":\"someone@example.com\"}","logger":"oauth.generic_oauth","lvl":"dbug","msg":"Received id_token","t":"2019-11-14T13:50:16.275798144Z"}
{"logger":"oauth.generic_oauth","lvl":"eror","msg":"Empty user info JSON response provided","t":"2019-11-14T13:50:16.27583317Z"}
{"logger":"oauth","lvl":"dbug","msg":"OAuthLogin got user info","t":"2019-11-14T13:50:16.275852427Z","userInfo":{"Id":"","Name":"someone@example.com","Email":"someone@example.com","Login":"someone@example.com","Company":"","Role":"","Groups":null}}
{"logger":"login.ext_user","lvl":"dbug","msg":"Updating user_auth info","t":"2019-11-14T13:50:16.283312326Z","user_id":2}
{"auth_module":"oauth_generic_oauth","logger":"sqlstore","lvl":"dbug","msg":"Updated user_auth","rows":3,"t":"2019-11-14T13:50:16.316541656Z","user_id":2}
{"authToken":"...","clientIP":"192.168.0.0","logger":"auth","lvl":"dbug","msg":"user auth token created","t":"2019-11-14T13:50:16.325494367Z","tokenId":3,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36","userId":2}
{"User":"someone@example.com","logger":"http.server","lvl":"info","msg":"Successful Login","t":"2019-11-14T13:50:16.325558711Z"}
```

I verified that the userinfo endpoint responds with the expected claims, and is accessible from within the Grafana pod. I use this Dex setup for OAuth with other applications without running into the same issue.

**What you expected to happen**:
Grafana would retrieve the token's claims from the /userinfo endpoint and use the `groups` attribute to map a Grafana role to the user. 

**How to reproduce it (as minimally and precisely as possible)**:
- Set up Dex as an OAuth provider with a client for Grafana
- Use generic OAuth configs for grafana
- Log in

**Anything else we need to know?**:
- Using Istio

**Environment**:
- Grafana version: 6.6.0-pre (073e9ef)
- Data source type & version: n/a
- OS Grafana is installed on: Ubuntu (Kubernetes)
- User OS & Browser: Mac OSX Catalina/Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by cmanzi** [comment] 2019-11-14 14:32
Ah ok, so I think I see what's going on here. So what's happening is that it retrieves a valid idToken, which means that `s.extractToken == true`:
https://github.com/grafana/grafana/blob/7a3d1c0e4ba1b4803f7b8273f3f7dd8e8f78b19f/pkg/login/social/generic_oauth.go#L215-L230
Because of that, `rawUserInfoResponse` is empty because the /userinfo endpoint is never called. So in this block of code:
https://github.com/grafana/grafana/blob/7a3d1c0e4ba1b4803f7b8273f3f7dd8e8f78b19f/pkg/login/social/generic_oauth.go#L234-L242
`extractEmail` and `extractRole` will never return anything. Did I miss something here? Or is this expected behavior?

**Comment by marefr** [comment] 2019-11-14 20:34
Duplicate of #20243

**Comment by marefr** [comment] 2019-11-14 20:35
There's already a PR opened to fix referenced issue so not sure your PR is needed. But please have a look at #20300 and provide feedback, if any. Thanks

**Closed by marefr** 2019-11-14 20:35 UTC
