### ISSUE TITLE
Want to be able to have multiple items in one column

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#3954] opened 2016-02-05 17:59 UTC
Its better explained with a image of what I am trying to do: 
![image](https://cloud.githubusercontent.com/assets/12910496/12854513/061bb642-cc32-11e5-9ac2-b746400f87c1.png)

I set the height of both items to be 25px, and the row height is 250px. But I cant move it to underneath the other little stat, disk usage one.

**Comment by torkelo** [comment] 2016-02-08 09:00
this would be great, tricky though. 

Closing as this is a dupe of https://github.com/grafana/grafana/issues/170

**Closed by torkelo** 2016-02-08 09:00 UTC
