### ISSUE TITLE
allow_embedding does not change X-Frame-Options

### ISSUE THREAD

**Issue by dxnnv** [grafana/grafana#52364] opened 2022-07-17 03:08 UTC
**What happened**:
Unable to display Grafana panel as iFrame

Browser console responds with 
`Refused to display 'https://<user>.grafana.net/login' in a frame because it set 'X-Frame-Options' to 'deny'`

allow_embedding and cookie_secure are set to true, cookie_samesite is set to none (verified in https://<host-ip>:3000/admin/settings
**What you expected to happen**:
To display Grafana panel as iFrame
**How to reproduce it (as minimally and precisely as possible)**:
Log into Grafana
Obtain the iFrame by clicking "share">"embed" on a panel
Add the iFrame to a website
Open said website
iFrame does not load
Check browser console for the error 
**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.3
- Data source type & version:
- OS Grafana is installed on: Debian, via Docker
- User OS & Browser: OSX, Safari and Chrome
- Grafana plugins: None
- Others: None

**Comment by aso824** [comment] 2022-07-17 22:49
Werd, I'm also running Grafana v9.0.3 and can confirm that changing `allow_embedding` to true fixed that error from console.

**Comment by dxnnv** [comment] 2022-07-17 23:37
@aso824 are you using Grafana Cloud?

**Comment by aso824** [comment] 2022-07-18 08:29
@dxnnv no, self hosted, without Docker

**Comment by ashharrison90** [comment] 2022-07-26 13:50
hi @dxnnv 👋 

i also can't reproduce this - it works locally for me
is there any more information you can provide about your setup/config? have you set `allow_embedding` at the top level or under the security section? it needs to look like this in your config:

```
[security]
allow_embedding = false
```

thanks!

**Comment by dxnnv** [comment] 2022-07-27 23:32
> hi @dxnnv 👋 
> 
> 
> 
> i also can't reproduce this - it works locally for me
> 
> is there any more information you can provide about your setup/config? have you set `allow_embedding` at the top level or under the security section? it needs to look like this in your config:
> 
> 
> 
> ```
> 
> [security]
> 
> allow_embedding = false
> 
> ```
> 
> 
> 
> thanks!

Yes, allow_embedding is set to true. I have tried using Grafana using both Grafana Cloud and just the agent on localhost, both have run into this error.

**Comment by mcy567** [comment] 2022-08-02 04:30
I had the same problem...
![image](https://user-images.githubusercontent.com/22673808/182291870-e268a4d4-baff-41f6-8446-4b5096577cfd.png)
![image](https://user-images.githubusercontent.com/22673808/182291894-28caf302-3e49-4638-a250-21cc37843caf.png)
![image](https://user-images.githubusercontent.com/22673808/182291561-b836b089-1cff-4e05-89da-f74a17c513d5.png)
![image](https://user-images.githubusercontent.com/22673808/182291626-35b8b7d6-7ed4-48ef-bc4c-291ffd79d445.png)
![image](https://user-images.githubusercontent.com/22673808/182291671-3e67c144-b14d-4caa-b2da-af4f16fb270a.png)

**Comment by chenkaiyin1201** [comment] 2022-10-18 03:34
It also does not take effect in the self-hosted version

grafana version: 7.5.9

**Comment by chenkaiyin1201** [comment] 2022-10-18 03:52
> It also does not take effect in the self-hosted version
> 
> grafana version: 7.5.9

The parameter allow_embedding is modified, but the configuration of /admin/settings does not take effect.

Because it is started through docker image, even if I re-create the same does not take effect.

**Comment by jamescwaters** [comment] 2022-11-14 19:22
I'm running into the same issue. I have /etc/grafana/grafana.ini allow_embedding = true but in admin/settings I see allow_embedding = false. Restarting the service doesn't help.

**Comment by zuchka** [comment] 2022-11-22 01:45
sounds like this is now resolved. @dxnnv closing this pending any new information. Please note that we are not supporting v7 anymore 👍

**Closed by zuchka** 2022-11-22 01:45 UTC
Labels: needs more info
