### ISSUE TITLE
Grafana oauth2 RBAC enhancement

### ISSUE THREAD

**Issue by lm123** [grafana/grafana#15345] opened 2019-02-11 08:55 UTC
### What Grafana version are you using?
5.2.4

### What datasource are you using?
Sqlite3

### What OS are you running grafana on?
CentOS 7.x

When Grafana integrates with Keycloak for authentication, the user permission defined in Keycloak side is not used by Grafana. Can Grafana be enhanced to use RBAC provided by Keycloak?

Current behavior of Grafana when integrating with Keycloak:
1. User/Password is verified on the side of Keycloak.
2. If the user is not existed on the side of Grafana, one new user with guest permission will be created.

The desired behavior will be liking as below:
1. User/Password is verified on the side of Keycloak.
2. If the user is not existed on the side of Grafana, one new user with permission defined in Keycloak shall be created, not using guest permission.

**Comment by torkelo** [comment] 2019-02-11 13:02
duplicate of https://github.com/grafana/grafana/issues/9766

**Closed by torkelo** 2019-02-11 13:02 UTC
