### ISSUE TITLE
External plugins requiring auth do not work in 5.2.0+

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#12551] opened 2018-07-09 20:18 UTC
### What Grafana version are you using?

5.2.1

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

Irrelevant

### What did you do?

Open a dashboard with `jdbranham-diagram-panel` plugin.

### What was the expected result?

Things work as they did before.

### What happened instead?

Panel fails to load, because request is redirected to auth. The reason is missing cookies for `/public/vendor/plugin-css/css.js`. If I open `css.js` in a separate tab to cache it, next dashboard load works.

I suspect it broke in 8bcd55d2213375dd00930c09f13ae020bd94d787 after #12096. cc @davkal

It's very similar to https://github.com/systemjs/systemjs/issues/1731.

**Comment by davkal** [comment] 2018-07-10 09:08
Hi @bobrik, could you please help me reproducing this?

What I found so far:

- I'm testing this on 30c882c which has 8bcd55d included
- the installation i'm using is hosted by grafana.com, which has Google auth
- I added the plugin panel to a dashboard with no issues
- In a production deployment `/public/vendor/plugin-css/css.js` is part of a the bundle, so should not be loaded separately. Could you attach a screenshot of dev tools showing that the file is loaded independently?
- the css files required by `css.js` from the plugin are requested with cookies (`grafana_sess`, `grafana_user`, `grafana_remember`)

Where does your setup differ?

**Comment by bobrik** [comment] 2018-07-10 15:30
We are using Grafana 5.2.1 docker image with plugin installed, running behind reverse proxy that does Google auth, similar to [nginx-google-oauth](https://github.com/cloudflare/nginx-google-oauth). When I click to add Diagram panel:

![image](https://user-images.githubusercontent.com/89186/42520417-0f0f8564-841b-11e8-893f-07c261ba7fbd.png)

The cookies we need are not `grafana_` cookies, they are cookies set by out reverse proxy that does the auth and passes `X-Webauth-User` to Grafana if cookies are valid.

**Comment by torkelo** [comment] 2018-07-10 17:02
@davkal somehow the plugin css is not bundled and since it does not start with plugin it does not get the authorization config flag after you added the plugin prefix requirement. Maybe it’s the fact that this is systemjs plugin that makes the bundling not works. Was there a reason you added the plugin prefix , or was that in a PR that you merged?

**Comment by torkelo** [comment] 2018-07-11 09:13
So basically I think it's the adding of the `plugin*` prefix here that is the root of the problem as it makes the authorization: true flag not apply to css loader when it is being fetched. https://github.com/grafana/grafana/commit/8bcd55d2213375dd00930c09f13ae020bd94d787#diff-7d38adb6eb3fcc661871ef8d0968ffcfR50

**Comment by davkal** [comment] 2018-07-11 09:23
There was no reason other than trying to limit the scope to plugins. But if that css.js import is still being done per file, then we should remove it. I'll make a PR.

**Comment by davkal** [comment] 2018-07-11 10:10
Noticed the problem now too, `css.js` was excluded from the plugin loader mechanism. PR opened.

**Closed** 2018-07-11 10:29 UTC

**Comment by bobrik** [comment] 2018-07-11 22:40
Is there any ETA on 5.2.2 to have this in a public release?

**Comment by torkelo** [comment] 2018-07-12 05:02
No eta yet, maybe in 2 weeks?
