### ISSUE TITLE
[Feat] Support for InfluxDB 0.11.1 Multiple query syntax

### ISSUE THREAD

**Issue by sstarcher** [grafana/grafana#4533] opened 2016-04-02 18:50 UTC
* What grafana version are you using? 3.0 beta 1
* What datasource are you using? InfluxDB
* What OS are you running grafana on? Docker image

When using multiple InfluxDB queries I get
```"InfluxDB Error Response: error parsing query: found SELECT, expected ; at line 2, char 1"```

**Comment by torkelo** [comment] 2016-04-02 20:18
Ok, maybe influxdb has as more breaking changes in their API in 0.11 :(

**Comment by anazia** [comment] 2016-04-05 16:05
👍 

Same with v0.12 which is the latest:

`"error": "error parsing query: found SELECT, expected ; at line 2, char 1",`

I guess you just need a ';' between the queries, or am I missing something simple?

BTW, this is just when adding a new query on the same graph. Inspector:

q=
`SELECT count("#") FROM "access-log" WHERE "status" = '100' AND time > now() - 5m GROUP BY time(10s) fill(null) SELECT count("#") FROM "access-log" WHERE "status" = '200' AND time > now() - 5m GROUP BY time(10s) fill(null)`

**Comment by torkelo** [comment] 2016-04-05 17:35
The only issue is that this breaks influxdb 0.9 and 0.10 , but can maybe use the version prop and do it it differently for 0.11 , have not been able to test with InfluxDB 0.11 yet as there were updated docker containers yet for it

**Comment by r0bj** [comment] 2016-04-05 18:38
https://github.com/influxdata/influxdb/issues/6220

**Comment by ljagiello** [comment] 2016-04-05 20:34
Looks like it's connected with that change: #6004

**Comment by blacklensman** [comment] 2016-04-05 21:41
Yes. As far as I can tell also, adding ';' doesn't help. You can view the individual datasets but not all at once.  I guess if all your measurements are in the same DB at least you can do something like 'select value from /(m1|m2|m3)/ and aggregate over them.

**Comment by ljagiello** [comment] 2016-04-05 22:15
@blacklensman It's working as long as `;` is correctly urlencoded in url - `%3B`.

**Comment by ljagiello** [comment] 2016-04-06 03:00
The fix is pretty trivial:
```
diff --git a/public/app/plugins/datasource/influxdb/datasource.ts b/public/app/plugins/datasource/influxdb/datasource.ts
index daa6ada..f1dacbe 100644
--- a/public/app/plugins/datasource/influxdb/datasource.ts
+++ b/public/app/plugins/datasource/influxdb/datasource.ts
@@ -55,7 +55,7 @@ export default class InfluxDatasource {
       query = query.replace(/\$interval/g, (target.interval || options.interval));
       return query;

-    }).join("\n");
+    }).join(";\n");

     // replace grafana variables
     allQueries = allQueries.replace(/\$timeFilter/g, timeFilter);
```

But the real problem is a bug in angular.js (https://github.com/angular/angular.js/issues/9224) it's not encoding correctly semi-colon. If semi-colon is encoded properly everything is working fine.

**Comment by TheOneValen** [comment] 2016-04-06 07:04
When I try @ljagiello s fix, the querys don't throw any errors, but only the first query is displayed, not the rest of my queries.

**Comment by ljagiello** [comment] 2016-04-06 07:13
@TheOneValen it's because semicolon is not encoded properly. If you use curl and manually change `[…]fill(null);%0ASELECT[…]` -> `[…]fill(null)%3B%0ASELECT[…]` you will get all series in result.

**Comment by TheOneValen** [comment] 2016-04-06 07:35
you are right! the function encodeUriQuery in angular.js replaces %3B with a literal ;

deleting this line makes everything fine for now

thanks!

**Comment by bogdanveres** [comment] 2016-04-06 08:10
@TheOneValen is this fix available in latest Grafana build ?

**Comment by TheOneValen** [comment] 2016-04-06 10:04
Hi! I just modified the angular.js file locally.

**Comment by torkelo** [comment] 2016-04-06 11:26
Anyone know if InfluxDB is going to fix their breaking change?

**Comment by sstarcher** [comment] 2016-04-06 11:31
@torkelo doubtful the change was on purpose

**Comment by sstarcher** [comment] 2016-04-06 11:32
I'll quote 
```
I can remove the special newline behavior if we want to force the semi-colon, but it will break things that were previously possible.
```

https://github.com/influxdata/influxdb/pull/6004#issuecomment-199971438

**Comment by bogdanveres** [comment] 2016-04-06 13:22
Still reproducible on my side even with the changes.

Affected files by change:

C:\grafana_3\public\app\plugins\datasource\influxdb\datasource.ts
C:\grafana_3\public\vendor\angular\angular.js

**Comment by willowpet** [comment] 2016-04-06 13:54
same issue for me with the fix @ljagiello

**Comment by torkelo** [comment] 2016-04-06 14:24
@bogdanveres you cant apply the changes to a locally optimized build, for builds grafana combines all js files and minifies them ,

**Comment by bogdanveres** [comment] 2016-04-06 15:50
@torkelo is there a nightly build which contains the fix for windows version of Grafana?

**Comment by ReeseSys** [comment] 2016-04-06 16:07
It is not in the nightly build yet.  The pull request https://github.com/grafana/grafana/pull/4580 has not yet been merged.

**Comment by torkelo** [comment] 2016-04-06 17:03
I can't merge that fix as it is modifying a library file, also need to verify if a fix like that will still work for older versions of InfluxDB. Woud also like to know if there are any plans to fix this on InfluxDB side or if this is a permanent breaking change on their part.

**Comment by steverweber** [comment] 2016-04-06 21:05
https://github.com/influxdata/influxdb/issues/6220
was closed saying ... wont fix

**Comment by sstarcher** [comment] 2016-04-07 16:11
@steverweber That's not fully true.  It was closed saying "won't fix"
```Closing this since this comment lends me to believe that this is an issue on Grafana's side:```

They are right because they intentionally broke backward compatibility with an edge case.  So the fix needs to happen on the grafana side as influxdb does not plan to support newlines as a seperator.

**Comment by samson-jerome** [comment] 2016-04-08 17:23
Tried to hack the fix from @ljagiello by also inserting the changes in **angular.min.js** and **datasource.js** compiled files...
Still does not work.

**Comment by t-orb** [comment] 2016-04-08 18:23
@samson-jerome for me the compiled and minimized javascript is all in a single file:

     /usr/share/grafana/public/app/app.ca0ab6f9.js

    sed --in-place=backup 's/join("\\n");return k=k.replace/join(";\\n");return k=k.replace/;s/.replace(\/%3B\/gi,";").replace/.replace/' app.ca0ab6f9.js

Makes the two required changes. It could very well be your file is different though. This is from the Ubuntu package.

**Comment by samson-jerome** [comment] 2016-04-08 19:10
Awesome, I did the changes in public/app on files named differently and grafana will properly display multiple queries now. Thanks a bunch !

**Comment by LaurentDumont** [comment] 2016-04-09 05:19
What would be the current way to fix this when using Grafana from APT? I've tried changing the files locally l but it doesn't seem to work. I see that there is a PR open : https://github.com/grafana/grafana/pull/4580

**Closed** 2016-04-09 15:00 UTC
Labels: datasource: InfluxDB, state: help wanted (PR)

**Comment by torkelo** [comment] 2016-04-09 15:05
Finaly had time to do a proper fix for this, in commit ed62822  . Sorry that this took a couple of days to fix, had hoped someone would find the angular hook paramSerializer that allows the caller to customize url encoding without modifying the angular code itself :) 

new beta3 build should appear here shortly. 
http://grafana.org/download/builds.html

Will try to publish a official beta3 build on monday to testing APT/YUM repos

**Comment by pauldix** [comment] 2016-04-09 16:10
Just chiming in on this thread. Sorry for the InfluxDB API change. Being able to use newline was an undocumented "feature" and something we wanted to clean up in the run up to the 1.0 release to lock the API down and make it consistent.

**Comment by TotallyInformation** [comment] 2016-04-10 17:30
I'd also like to comment that the inline patch works just fine with the current v2.6 stable release too! Nice workaround, thanks.

**Comment by bogdanveres** [comment] 2016-04-12 13:46
@torkelo is there a nightly build for windows that contains the fix for multiple query syntax?

**Comment by torkelo** [comment] 2016-04-12 14:05
just published a new beta3 official build, http://grafana.org/download/   (with windows build )

**Comment by sstarcher** [comment] 2016-04-12 14:17
@torkelo could we get a docker build?  The last one that is tagged is beta1 from 12 days ago.  I'll test it out if you cut me one ;)

**Comment by mnietz** [comment] 2016-04-12 14:59
Installed beta3 using InfluxDB 0.12, works like a charm. Thanks !

**Comment by torkelo** [comment] 2016-04-12 15:30
@sstarcher will publish docker image shortly,

**Comment by MrSpock** [comment] 2016-04-13 13:10
Hi,
Bug still exists. Grafana downloaded 10 minutes ago and added simple interface traffic graph.
<img width="1257" alt="zrzut ekranu 2016-04-13 15 09 46" src="https://cloud.githubusercontent.com/assets/681680/14494196/d649c872-0189-11e6-9ab7-8a701e7099a8.png">

**Comment by torkelo** [comment] 2016-04-13 13:36
@MrSpock strange, everyone so far has reported success, what build are you on (check footer on loading page)

**Comment by MrSpock** [comment] 2016-04-13 18:51
I made upgrade:
grafana_3.0.0-beta21459801392_amd64.deb -> grafana_3.0.0-beta31460467884_amd64.deb

**Comment by MrSpock** [comment] 2016-04-13 18:53
Ok - it's working.
`systemctl restart grafana` didn't helped.
`systemctl stop grafana; systemctl start grafana` did the trick

**Comment by torkelo** [comment] 2016-04-13 20:23
strange, should be systemctl start grafana-server with the official packages

**Comment by sstarcher** [comment] 2016-04-13 20:24
beta3 docker container works great

**Comment by Dual-Boot** [comment] 2016-04-14 18:43
Hi, is there a way that this fix will be backport into grafana 2.6 ?
regards

**Comment by torkelo** [comment] 2016-04-14 18:44
@Dual-Boot no backport. But Grafana 3.0 stable is soon released.

**Comment by Dual-Boot** [comment] 2016-04-14 18:57
Oki doki.
Maybe I will upgrade to the beta version.

**Comment by maverick2202** [comment] 2016-10-12 15:28
Is Grafana 3.1 compatible with latest influxdb 1.0 ? Assuming that 3.1 is compatible with 0.12 influxdb as per this ticket.
