### ISSUE TITLE
text box don't work well

### ISSUE THREAD

**Issue by EM1994** [grafana/grafana#52379] opened 2022-07-18 07:46 UTC
**What happened**:
I want to implement a complex lucene query through text box，like  : DestCityName:Torino AND Carrier:JetBeats
![image](https://user-images.githubusercontent.com/32710096/179464023-eae4e5e1-c804-4316-ac38-303be6262de2.png)
![image](https://user-images.githubusercontent.com/32710096/179464139-971e77e6-f357-410e-8672-e0513f2c0f80.png)
but it seem don't work 
1) input DestCityName:Torino AND Carrier:JetBeats in text box named test
![image](https://user-images.githubusercontent.com/32710096/179464457-01c3d7e5-afff-4d85-aa77-0873211446f1.png)
2)  Query inspector show like flow, why sapce and :  were be escaped ? I dont't understand  :)  
![image](https://user-images.githubusercontent.com/32710096/179464602-bf7f93a6-a0e5-4226-8cbd-a47ef5493748.png)

Because of these escapes, es doesn't recognize this query
"{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"kibana_sample_data_flights\"}
{\"size\":500,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"timestamp\":{\"gte\":1658112469152,\"lte\":1658134069152,\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"DestCityName\\\\:Torino\\\\ AND\\\\ Carrier\\\\:JetBeats\"}}]}},\"sort\":[{\"timestamp\":{\"order\":\"desc\",\"unmapped_type\":\"boolean\"}},{\"_doc\":{\"order\":\"desc\"}}],\"script_fields\":{}}
**What you expected to happen**:
I think spcace and :  should not be escaped ,
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.3  https://play.grafana.org/d/MziCItNnk/textbox-bug-on-pressing-enter?orgId=1&var-textbox=&from=1658112469152&to=1658134069152&var-test=DestCityName:Torino%20AND%20Carrier:JetBeats
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
- elasticsearch8.2.0

**Comment by zoltanbedi** [comment] 2022-07-19 14:53
This is a duplicate of https://github.com/grafana/grafana/issues/32662 Please try the solution commented there or this document https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/

**Closed by zoltanbedi** 2022-07-19 14:53 UTC
