### ISSUE TITLE
Docs: getting 404 while accessing packages api 

### ISSUE THREAD

**Issue by adigov** [grafana/grafana#57026] opened 2022-10-14 20:31 UTC
**What happened**: Googled "grafana docs runtime"

**What you expected to happen**: previously, until less than 2 weeks ago, https://grafana.com/docs/grafana/latest/packages_api/data/ used to show information. Now it is giving 404

**How to reproduce it (as minimally and precisely as possible)**: simple google search and click first result

**Comment by Eve832** [comment] 2022-10-18 13:29
This content has been removed in this PR https://github.com/grafana/grafana/pull/54473 for releases after 9.1.x. To view the content from previous releases, see https://grafana.com/docs/grafana/v9.1/packages_api/data/ 
If you're interested in creating a plugin, you can also start here: https://grafana.com/docs/grafana/latest/developers/plugins/

**Comment by gguillotte-grafana** [comment] 2022-10-18 19:09
Context on the reproduction steps:

The first search result returns 
https://grafana.com/docs/latest/packages_api/runtime, which 404s since Grafana v9.2.

I believe the equivalent code implementation is at https://github.com/grafana/grafana/blob/v9.2.x/packages/grafana-runtime/src/config.ts. If the temporary intent is to redirect from the deprecated API docs to the APIs' source, that should be the target.

**Comment by chri2547** [comment] 2023-07-20 17:39
Per Jack: I no longer see that page come up in search results for that term. I think it is probably safe to close the issue with some explanation to that effect.

**Closed by chri2547** 2023-07-20 17:39 UTC
Labels: type/docs, migrate/status-product-backlog
