### ISSUE TITLE
Static panels are not showing in repeating rows when a mix of static & repeating panels are present

### ISSUE THREAD

**Issue by gdacunda** [grafana/grafana#11815] opened 2018-05-03 15:23 UTC
Please include this information:
### What Grafana version are you using?
4.6.2 (works well) and 5.x (does not work as expected)
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
Grafana is running in official Docker container
### What did you do?
I have a dashboard in Grafana v4.6.2 which has repeating rows and a mix of fixed and repeating panels in the row.
### What was the expected result?
In v.4.6.2 the repeating rows shows both static and repeating panels. In v.5.x only the first row shows static and repeating panels, the other rows only shows the repeating ones.
### If related to metric query / data viz:
No

**Comment by marefr** [comment] 2018-05-03 15:29
Not sure I understand what you mean. Do you repeat a row by variable which includes some static panels and some panels where you've enabled repeat by variable?

If possible, please include your dashboard json or a dashboard json which highlights your problem so that we can reproduce it.

**Comment by gdacunda** [comment] 2018-05-03 15:35
I repeat a row by variable and that row contains some static panels and some other which are repeated by variable.
When I select more than one variable to repeat the rows, the behavior is the following
- In v.4.6.2 the repeated rows shows all panels (static and repeated ones)
- In 5.x only the first repeated row show all panels, the other only shows the repeated panels.

**Comment by gdacunda** [comment] 2018-05-03 15:58
[Server Status-1525362703969.txt](https://github.com/grafana/grafana/files/1971664/Server.Status-1525362703969.txt)
Included dashboard exported from 5.x

**Comment by marefr** [comment] 2018-05-04 12:37
Duplicate of #5329

**Closed by marefr** 2018-05-04 12:37 UTC
Labels: state: needs more detail
