### ISSUE TITLE
Image not getting attached in Sentry / Mail notifications. Timeout Error in logs for Alert Panel Image.

### ISSUE THREAD

**Issue by Nikita279** [grafana/grafana#22595] opened 2020-03-05 10:52 UTC
**What happened**:
Image is not getting attached in Sentry / E-mail alert notifications even when "Include Image" option is enabled from Notification Channel panel.
```
Full logs -
t=2020-03-05T10:16:01+0000 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=2 newState=ok prev state=alerting
t=2020-03-05T10:16:01+0000 lvl=info msg=Rendering logger=rendering renderer=phantomJS path="d-solo/jwPKIsniz/kafka-exporter-overview?orgId=1&panelId=12"
t=2020-03-05T10:16:46+0000 lvl=info **msg="Rendering timed out" logger=rendering renderer=phantomJS
t=2020-03-05T10:16:46+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=2 error="Timeout error. You can set timeout in seconds with &timeout url parameter"**
t=2020-03-05T10:16:46+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=2 notification=Slack
t=2020-03-05T10:25:28+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 time_ms=0 size=0_ 
```

**What you expected to happen**:
Expecting graph/table screenshot in E-mail and Sentry alert notification. Although test mail sends test image correctly.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup E-mail/Slack alerts on Grafana.
- Enable "Include Image" option.
- Check mail/slack notification - No image attached. Only text is sent.

**Anything else we need to know?**:
I tried increasing the timeout but doesn't seem to have any effect -
```
#Default setting for alert calculation timeout. Default value is 30
evaluation_timeout_seconds = 90
#Default setting for alert notification timeout. Default value is 30
notification_timeout_seconds = 90
```

**Environment**:
- Grafana version:  v6.6.1 (21bf8b71bc)
- Data source type & version: Prometheus 2.15.2
- OS Grafana is installed on: Linux
- User OS & Browser: Mac OS
- Grafana plugins: N/A
- Others:

![Grafana - Alerting Alert Rules](https://user-images.githubusercontent.com/40610477/75974810-6b68f980-5efd-11ea-90dd-a23ea5c87755.png)

![Grafana - Mail Alert](https://user-images.githubusercontent.com/40610477/75974631-2349d700-5efd-11ea-8513-a95527d3c2ab.png)

<img width="1438" alt="Screenshot 2020-03-05 at 4 17 48 PM" src="https://user-images.githubusercontent.com/40610477/75974563-06ad9f00-5efd-11ea-8bc5-fae064fa6426.png">

<img width="841" alt="Screenshot 2020-03-05 at 4 15 48 PM" src="https://user-images.githubusercontent.com/40610477/75974696-407ea580-5efd-11ea-8d51-5ccd76b024b9.png">

**Comment by aknuds1** [comment] 2020-03-05 10:57
Please try the image rendering plugin since PhantomJS is deprecated.

**Comment by Nikita279** [comment] 2020-03-05 10:58
> Please try the image rendering plugin since PhantomJS is deprecated.

Which plugin do you recommend?

**Comment by aknuds1** [comment] 2020-03-05 11:00
The [official one](https://grafana.com/docs/grafana/latest/administration/image_rendering/#install-grafana-image-renderer-plugin).

Closing as duplicate of #21912.

**Closed by aknuds1** 2020-03-05 11:00 UTC

**Comment by Nikita279** [comment] 2020-03-05 13:02
Cool. Thank you!
