### ISSUE TITLE
Can't import or save new dashboards if their graphs have alerts configured.

### ISSUE THREAD

**Issue by nohablo** [grafana/grafana#11227] opened 2018-03-13 16:21 UTC
### What Grafana version are you using?

5.0.1 (docker)

### What datasource are you using?

Prometheus

### What OS are you running grafana on?

CentOS 7

### What did you do?

Attempted to import dashboard json with alerts configured via the API. Similarly, when using the web frontend, new dashboards cannot be saved if alerts have been configured on any of their graphs (however, saving a dashboard prior to adding alerts and then adding them works as expected)

### What was the expected result?

Dashboards would import/save

### What happened instead?

"Invalid alert data, cannot save dashboard"

**Comment by jeremyjpj0916** [comment] 2018-03-14 04:37
Was going to post the same exact thing, glad to see someone has an issue already opened. To elaborate and give concrete example here was a JSON dashboard with an ALERT configured. I copy pasted the json into a file, deleted the dashboard fully expecting the import to work. Instead I get an error, try with this JSON, using latest 5.0.1 stable via YUM pull down. 

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 6,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus-Kong-Shared-Dev-Core",
      "fill": 1,
      "gridPos": {
        "h": 5,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 3,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "sum(netdata_kong_F5Monitor_request_count_events_persec_average{alias='kong'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "Requests Per Second",
          "refId": "A"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "F5Monitor API Requests Per Second",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    },
    {
      "alert": {
        "conditions": [
          {
            "evaluator": {
              "params": [
                0
              ],
              "type": "gt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "E",
                "2m",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "count"
            },
            "type": "query"
          }
        ],
        "executionErrorState": "alerting",
        "frequency": "60s",
        "handler": 1,
        "message": "API Returning Error Codes in the 500 HTTP Status Range.",
        "name": "F5Monitor HTTP Status Codes Per Second alert",
        "noDataState": "ok",
        "notifications": []
      },
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus-Kong-Shared-Dev-Core",
      "fill": 1,
      "gridPos": {
        "h": 5,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 4,
      "legend": {
        "avg": false,
        "current": false,
        "hideEmpty": false,
        "hideZero": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "$$hashKey": "object:1436",
          "expr": "sum({__name__=~\"netdata_kong_F5Monitor_request_status_1.*._events_persec_average\"})",
          "format": "time_series",
          "hide": true,
          "intervalFactor": 2,
          "legendFormat": "100's Response Count",
          "refId": "B"
        },
        {
          "$$hashKey": "object:1437",
          "expr": "sum({__name__=~\"netdata_kong_F5Monitor_request_status_2.*._events_persec_average\"})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "200's Response Count",
          "refId": "A"
        },
        {
          "$$hashKey": "object:1438",
          "expr": "sum({__name__=~\"netdata_kong_F5Monitor_request_status_3.*._events_persec_average\"})",
          "format": "time_series",
          "hide": true,
          "intervalFactor": 2,
          "legendFormat": "300's Response Count",
          "refId": "C"
        },
        {
          "$$hashKey": "object:1439",
          "expr": "sum({__name__=~\"netdata_kong_F5Monitor_request_status_4.*._events_persec_average\"})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "400's Response Count",
          "refId": "D"
        },
        {
          "$$hashKey": "object:1440",
          "expr": "sum({__name__=~\"netdata_kong_F5Monitor_request_status_5.*._events_persec_average\"})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "500's Response Count",
          "refId": "E"
        }
      ],
      "thresholds": [
        {
          "colorMode": "critical",
          "fill": true,
          "line": true,
          "op": "gt",
          "value": 0
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "F5Monitor HTTP Status Codes Per Second",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    },
    {
      "aliasColors": {
        "max": "#bf1b00",
        "median": "#e0752d"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus-Kong-Shared-Dev-Core",
      "fill": 1,
      "gridPos": {
        "h": 7,
        "w": 24,
        "x": 0,
        "y": 5
      },
      "id": 5,
      "legend": {
        "avg": false,
        "current": false,
        "hideZero": true,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "sum(netdata_kong_F5Monitor_latency_milliseconds_average{alias='kong', dimension='95.0%'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "95th Percentile",
          "refId": "A"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_latency_milliseconds_average{alias='kong', dimension='max'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "Max",
          "refId": "B"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_latency_milliseconds_average{alias='kong', dimension='min'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "Min",
          "refId": "C"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_latency_milliseconds_average{alias='kong', dimension='average'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Average",
          "refId": "D"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "F5Monitor Total Latency (ms)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    },
    {
      "aliasColors": {
        "max": "#bf1b00",
        "median": "#e0752d"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus-Kong-Shared-Dev-Core",
      "fill": 1,
      "gridPos": {
        "h": 7,
        "w": 12,
        "x": 0,
        "y": 12
      },
      "id": 7,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "sum(netdata_kong_F5Monitor_upstream_latency_milliseconds_average{alias='kong', dimension='95.0%'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "95th Percentile",
          "refId": "A"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_upstream_latency_milliseconds_average{alias='kong', dimension='max'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Max",
          "refId": "B"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_upstream_latency_milliseconds_average{alias='kong', dimension='min'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Min",
          "refId": "C"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_upstream_latency_milliseconds_average{alias='kong', dimension='average'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Average",
          "refId": "D"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "F5Monitor Backend Latency (ms)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    },
    {
      "aliasColors": {
        "max": "#bf1b00",
        "median": "#e0752d"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus-Kong-Shared-Dev-Core",
      "fill": 1,
      "gridPos": {
        "h": 7,
        "w": 12,
        "x": 12,
        "y": 12
      },
      "id": 6,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "sum(netdata_kong_F5Monitor_kong_latency_milliseconds_average{alias='kong', dimension='95.0%'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "95th Percentile",
          "refId": "A"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_kong_latency_milliseconds_average{alias='kong', dimension='max'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Max",
          "refId": "B"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_kong_latency_milliseconds_average{alias='kong', dimension='min'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Min",
          "refId": "C"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_kong_latency_milliseconds_average{alias='kong', dimension='average'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Average",
          "refId": "D"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "F5Monitor Proxy Latency (ms)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    },
    {
      "aliasColors": {
        "max": "#bf1b00",
        "median": "#e0752d"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus-Kong-Shared-Dev-Core",
      "fill": 1,
      "gridPos": {
        "h": 7,
        "w": 12,
        "x": 0,
        "y": 19
      },
      "id": 8,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "sum(netdata_kong_F5Monitor_request_size_milliseconds_average{alias='kong', dimension='95.0%'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "95th Percentile",
          "refId": "A"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_request_size_milliseconds_average{alias='kong', dimension='max'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Max",
          "refId": "B"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_request_size_milliseconds_average{alias='kong', dimension='min'})\r\n",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Min",
          "refId": "C"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_request_size_milliseconds_average{alias='kong', dimension='average'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Average",
          "refId": "D"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "F5Monitor Request Size Per Second (Bytes)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    },
    {
      "aliasColors": {
        "max": "#bf1b00",
        "median": "#e0752d"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus-Kong-Shared-Dev-Core",
      "fill": 1,
      "gridPos": {
        "h": 7,
        "w": 12,
        "x": 12,
        "y": 19
      },
      "id": 9,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "sum(netdata_kong_F5Monitor_response_size_milliseconds_average{alias='kong', dimension='95.0%'})",
          "format": "time_series",
          "hide": false,
          "intervalFactor": 2,
          "legendFormat": "95th Percentile",
          "refId": "A"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_response_size_milliseconds_average{alias='kong', dimension='max'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Max",
          "refId": "B"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_response_size_milliseconds_average{alias='kong', dimension='min'})\r\n",
          "format": "time_series",
          "interval": "",
          "intervalFactor": 2,
          "legendFormat": "Min",
          "refId": "C"
        },
        {
          "expr": "sum(netdata_kong_F5Monitor_response_size_milliseconds_average{alias='kong', dimension='average'})",
          "format": "time_series",
          "intervalFactor": 2,
          "legendFormat": "Average",
          "refId": "D"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "F5Monitor Response Size Per Second (Bytes)",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    }
  ],
  "refresh": false,
  "schemaVersion": 16,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-5m",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "API - F5Monitor",
  "uid": "000000006",
  "version": 12
}
```

**Comment by ghandim** [comment] 2018-03-14 08:06
Same here with our dashboards where alerts are configured.

**Comment by jordijansen** [comment] 2018-03-14 09:51
Getting the same problems. Did some debugging using debug logging and looking at the source-code of Grafana. Issue seems to be in the alert.go model. There is a method there that checks if the alert is validToSafe:
`func (alert *Alert) ValidToSave() bool {
	return alert.DashboardId != 0 && alert.OrgId != 0 && alert.PanelId != 0
}
`

Seems to me that alert.DashboardId is no longer used (since I had to remove that from my dashboard JSON aswell). I'm not sure about the OrgId, can't find that in the new Json either. The panelId does seem to be filled so that doesn't seem to be the issue.

**Comment by marefr** [comment] 2018-03-14 10:27
Confirmed bug. Same applies if you create a new dashboard and define an alert and then save.

**Comment by jordijansen** [comment] 2018-03-14 10:50
@marefr I can confirm this also happens when using provisioned dashboards since that was the case for me.

**Comment by marefr** [comment] 2018-03-14 13:34
I've submitted a PR to fix the problem with import of dashboard having alert rule(s). Basically we revert the logic of import to how it worked before v5.0, i.e. import of dashboard with alert rule(s) will be accepted, but no alert rules will be created. This will be included in our upcoming patch release v5.0.2.

Regarding creating alert rules on import, when saving a new dashboard and when using provisioning we've created a separate issue #11247.

**Closed** 2018-03-14 13:38 UTC
Labels: comp: alerting/evaluation, comp: dashboard, type: bug

**Comment by atzoum** [comment] 2018-03-20 08:33
I am afraid I am still getting the same error when trying to provision a dashboard which contains an alert in version 5.0.3:
`EROR[03-20|08:30:43] failed to save dashboard                 logger=provisioning.dashboard type=file name=ecs error="Invalid alert data. Cannot save dashboard"`

Here is an example dashboards that fails with provisioning

```
{
  "__inputs": [
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "5.0.3"
    },
    {
      "type": "panel",
      "id": "graph",
      "name": "Graph",
      "version": "5.0.0"
    },
    {
      "type": "datasource",
      "id": "influxdb",
      "name": "InfluxDB",
      "version": "5.0.0"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "alert": {
        "conditions": [
          {
            "evaluator": {
              "params": [
                10
              ],
              "type": "gt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "A",
                "5m",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "avg"
            },
            "type": "query"
          }
        ],
        "executionErrorState": "alerting",
        "frequency": "60s",
        "handler": 1,
        "name": "alert",
        "noDataState": "no_data",
        "notifications": []
      },
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "ecs_app",
      "fill": 1,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "groupBy": [
            {
              "params": [
                "$__interval"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "mean"
              }
            ]
          ],
          "tags": []
        }
      ],
      "thresholds": [
        {
          "colorMode": "critical",
          "fill": true,
          "line": true,
          "op": "gt",
          "value": 10
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ]
    }
  ],
  "schemaVersion": 16,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "New dashboard Copy",
  "uid": "dUtbgMkmk",
  "version": 2
}
```

**Comment by marefr** [comment] 2018-03-20 10:20
@atzoum please see my earlier comment:
> Regarding creating alert rules on import, when saving a new dashboard and when using provisioning we've created a separate issue #11247.
