### ISSUE TITLE
It'd be awesome to have the Variable selector remain visible at all times when scrolling long dashboards like Node Exporter Full.

### ISSUE THREAD

**Issue by ak2766** [grafana/grafana#56147] opened 2022-10-02 05:01 UTC
**Steps to reproduce**:
Navigate to any dashboard that has variables defined such as this one:

![Selection_00994](https://user-images.githubusercontent.com/6629646/193438350-a69cf485-1f77-4063-b03d-d35256fc350a.png)

**Actual Result**:
When you scroll down the list of elements in the dashboard, the variable selector scrolls out of view:

![Selection_00995](https://user-images.githubusercontent.com/6629646/193438639-9449bb42-c384-4884-a215-d7f229067e6a.png)

**Expected Result**
I expected the variable selector to remain visible at all times.  Otherwise, one has to scroll back to the top to select a new source for the data, then scroll back down.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: v9.1.6 (92461d8d1e)
- Data source type & version: kube-prometheus-stack v40.1.2
- User OS & Browser:
```
OS: Ubuntu 20.04.5 TLS
Browsers:
  Chrome - 106.0.5249.61 (Official Build) (64-bit)
  Firefox - 105.0 (64-bit)

**Comment by torkelo** [comment] 2022-10-03 07:49
duplicate of https://github.com/grafana/grafana/issues/11166

**Closed by torkelo** 2022-10-03 07:49 UTC

**Comment by ak2766** [comment] 2022-10-04 00:47
Apologies.  My searching did not reveal that particular issue.  I'll watch that one instead...
