### ISSUE TITLE
Slack alerting: Text line escaping is a bit too eager

### ISSUE THREAD

**Issue by theneva** [grafana/grafana#25729] opened 2020-06-20 10:30 UTC
Hi! :wave:

I have a panel called `LB 4xx & 5xx req/s` with an alerting rule that sends notifications to Slack.

I've recently upgraded from Grafana 6.7.4 to 7.0.3, and noticed that the Slack alerts now include a text line (presumably to be included in push notification text):

![image](https://user-images.githubusercontent.com/1404650/85199571-d98ccd00-b2f0-11ea-9f76-ad1647bdb574.png)

Compare with the same alert sent from 6.7.4:

![image](https://user-images.githubusercontent.com/1404650/85199587-f75a3200-b2f0-11ea-9aa3-86d98f8c86b4.png)

The new text line doesn't seem to escape text quite correctly, so the `&` which is correctly rendered in the attachment becomes `&amp;` in the text line.

This seems like a bug to me. I would expect the text line to also show `&`, or at least be identical to the text in the attachment :smile:

**Comment by sakjur** [comment] 2020-06-22 06:49
Thank you for your report!

I don't know the exact details of why we're having this problem, but the short version of it is that we need to upgrade our Slack integration to fix this duplicate line. There's no reason for us to write the same text twice. The difference in escaping comes from that problem, so I'll mark this as a duplicate of that bug 🙂

Duplicate of #24495

**Closed by sakjur** 2020-06-22 06:49 UTC
