### ISSUE TITLE
[Feature Request] Share variable definitions and keep selection state when switching dashboards

### ISSUE THREAD

**Issue by jstrachan** [grafana/grafana#5323] opened 2016-06-09 15:00 UTC
it would be nice to be able to share template values between dashboards.

e.g. on dashboard A you could pick template value X=Y. Then if dashboard B also had a template value X, it would be awesome to default X=Y when navigating to that dashboard. Then you could flip between A and B and keep the context (X=Y) to avoid each navigation having to re-select the context.

As background, we're making lots of dashboards with grafana and [prometheus](https://prometheus.io/) on top of [kubernetes](https://kubernetes.io/) which is working really well. There's often common template names like (`namespace`, `project`, `version` etc) to filter the dashboards. When someone's looking at one namespace/project/version at, say, CPU its kinda nice to be able to navigate to a different dashboard; while keeping the context (the template values).

Right now if you share a link to a dashboard it passes the template parameter values as URI parameters. e.g.
http://grafana2.vagrant.f8/dashboard/db/kuberentes-cpu?var-namespace=cheese&var-project=foo&var-version=1.1.2

Though when navigating to another dashboard via the dashboard drop down, all these parameter queries are discarded. It'd be nice if we could keep these query parameters on the link; maybe enable/disable it globally or on a per dashboard basis?

Then if we're on dashboard A and we want to navigate to B, it could pass the template parameters as query parameters on the URL so they get pre-populated by the dashboard B

**Comment by beat** [comment] 2018-11-22 09:47
Seems that it is a long-time request, see #1959 https://github.com/grafana/grafana/issues/1959 from May 2015, which asked for sharing variables across dashboards too.

This FR is not a duplicate of #1959 as it adds the valid concern to keep the time-frame.

It is a big scalability concern for the otherwise awesome Grafana, so thumbs up to this FR and #1959.

**Comment by beat** [comment] 2018-11-22 09:55
As just commented on https://github.com/grafana/grafana/issues/11382#issuecomment-440974155 , an elegant way to implement that would be to have sub-dashboards inside dashboards, i.e. dashboards able to display inside a dashboard, and instead of having their own time-ranges and variables, optionally be able to re-use the top-page settings (intervals) and variables from the parent dashboard ?

**Comment by hugohaggmark** [comment] 2020-10-07 11:40
I think this feature request has been solved for a while. The latest changes including a bug fix will be released with Grafana 7.2 (see #27926). 
I'm going to close this for now but we can reopen it.

**Closed by hugohaggmark** 2020-10-07 11:40 UTC
Labels: area/dashboard/templating, type/feature-request
