### ISSUE TITLE
Grafana-Athena: Same query request is repeated 4-8x vs. expected, causing slow loading

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#81236] opened 2024-01-25 08:57 UTC
### What happened?

We use the Amazon Athena datasource for our dashboards. This works well, but the initial loading of a dashboard is very slow compared to e.g. InfluxDB datasources. For comparison, try loading the two dashboard playgrounds below:

**InfluxDB playground**
Loading time: **~4 seconds**

**Athena playground**
https://grafana.csselectronics.stellarhosted.com/d/obd2-gps-car/obd2-gps-car?orgId=1
Loading time: **~9 seconds**

Of course, Athena would be expected to be slower vs. InfluxDB in general, but the problem seems mainly related to the initial loading of the dashboard, which seems to be much slower than what we'd expect.

When looking at the network traffic on the two playgrounds, one thing that we observed was that the Athena data source seems to result in multiple requests with the same query being sent - for example, the indicated query requests below all relate to ``SHOW TABLES`` - but we only have one Variable that requests this, meaning it should only be sent once.

If you look through the network traffic, you will see that the same issue persists across other panels - i.e. a lot of delay appears to be added due to the same request being sent multiple times for each query. Despite this, when looking at the Athena side only one request is handled by Athena for each panel (as expected) - so it appears to have no actual effect on the backend. But based on the network traffic, it seems to cause a lot of delays.

My guess is that the data source is setup to attempt to repeat a request if it does not receive a response within X ms - and since Athena is perhaps slower than many other data sources in providing the answer, that threshold may be set too aggressively today. 

![image](https://github.com/grafana/grafana/assets/26184427/f5c9df7e-c05b-48e8-86d6-1b835fb62ce4)

**Athena 1-panel playground**
https://grafana.csselectronics.stellarhosted.com/d/a690c7a7-68b1-4ff6-ab0e-ddd558c5516d/test-dashboard-athena?orgId=1

To make this more explicit, we also tried creating a playground with just 1 panel that has 1 query. You can test it out above. Here, Grafana sends the same query request 4 times as per the below image:
![image](https://github.com/grafana/grafana/assets/26184427/99fd1e8d-51a3-41da-9e01-baae92223198)

### What did you expect to happen?

We would expect Grafana to not send multiple requests for the same query, which we expect is causing a slow loading speed vs. what could be the case

### Did this work before?

Not sure 

### How do we reproduce it?

1. Try opening the two playgrounds and comparing the network traffic

### Environment (with versions)?

Grafana: Cloud
OS: Windows 10
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Amazon Athena

**Comment by sarahzinger** [comment] 2024-02-21 14:05
Hi @MatinF thanks for reporting!

This is a tricky one. On the one hand I think a lot of this is actually expected behavior. On the other hand I wouldn't be surprised if there was some kind of performance issue here that we don't quite see yet. 

So it is true that the Athena will make multiple network calls for the same query. However this is done purposely. If you look at the "Response" section of your network tab you'll see that we're getting back a status each time of the query. Often the first call is to start the query, the second call has a status of running or started, and the third (or Nth) call will have a status of "finished" and have the response values sent. 

We have a few datasources that work in this way but it's not a common pattern for us. We do this because some Athena queries are genuinely expected to take very long periods of time due to the nature of the data's format, and if we simply held open a Network connection for that long we'd be in trouble. 

On the otherhand, I agree this does seem _too_ slow sometimes, although I don't see a root cause for it just yet, or a reliable way to reproduce it. When I go to your shared dashboard for example it loaded with multiple requests but it also took less than a second to load for me each time. If you see something to indicate the performance issue besides multiple network requests (which is expected) let us know!

In the meantime we do have a few recommended ways to speed some requests:
Grafana Cloud offers Query Caching:
![Screenshot 2024-02-21 at 8 38 30 AM](https://github.com/grafana/grafana/assets/6620164/0bf5b4bc-d879-4373-8093-a71795b1312e)

And AWS allows us to pass a boolean for [Query Result Reuse](https://docs.aws.amazon.com/athena/latest/ug/reusing-query-results.html) which you can toggle in the query editor which should look something like this:
![Screenshot 2024-02-21 at 8 38 05 AM](https://github.com/grafana/grafana/assets/6620164/7b5031b8-d0e8-45b1-a05a-895eba389405)
or in our new UI (coming soon) will look like this:
![Screenshot 2024-02-21 at 8 36 59 AM](https://github.com/grafana/grafana/assets/6620164/0265109e-681a-43c3-9233-b9e1fef44e7b)

Both of those options should at least solve the problem of reloading queries after you've made the the first time. Let us know if that helps things a bit.

**Comment by MatinF** [comment] 2024-02-21 14:20
Thanks for the tips!

1) The problem with using Grafana Cloud here is that it does not enable us to create a public playground, hence why we're self-hosting Grafana and thus not able to use the built in query caching frontend (which I agree might otherwise solve this)

2) The query result reuse does not work for e.g. ``SHOW TABLES`` which we use in the Template Variables, hence the issue

3) I'm not sure why it loads in 1 second on your end, maybe there is a regional latency effect in play here as well. But my main observation was that there seemed to be some suboptimal behavior in the network request logic that might cause it to be too slow. In particular, the issue is observable in my first link which takes 7-9 seconds on my end to load the first time when I do a hard refresh (F5), though not if I use the Grafana refresh button. This distinction is important as I think the delay is down to some initialization behavior, not the general performance once the dashboard has been loaded the first time.

**Comment by sarahzinger** [comment] 2024-02-21 16:14
Hmm yeah here's a recording of me visiting the two links you've shared they seem to load pretty quick for me? 
https://github.com/grafana/grafana/assets/6620164/2bb4ac43-4433-46e1-9535-1c2af175cafc

If we can't reproduce it I'm not sure what we can fix. It sounds to me like the issue is more on AWS's end that our own? Might be worth filing a ticket with them?

**Comment by MatinF** [comment] 2024-02-21 18:06
It does seem to load a bit faster on your side with the multipanel dashboard (1st link), but still takes significantly longer than e.g. a comparable InfluxDB dashboard. Below is the equivalent dashboard in terms of panels, but designed with the InfluxDB datasource:

InfluxDB: https://grafana.csselectronics.stellarhosted.com/d/6qvL9OvMz/css-playground-obd2?orgId=1
Athena: https://grafana.csselectronics.stellarhosted.com/d/obd2-gps-car/obd2-gps-car?orgId=1

If you can test the above two, I expect you'll see a much quicker loading time on the InfluxDB vs. Athena. Maybe this is expected, but it just seems weird why the loading of the panels should differ so significantly, when the Athena content loads super snappy when hitting the Grafana refresh button. This intuitively seems like some sub optimal loading performance from my point of view, but maybe that's not the case.

**Comment by sarahzinger** [comment] 2024-02-26 14:04
@MatinF Yeah I do notice that in Athena I see this screen much longer

![Image](https://github.com/grafana/grafana/assets/6620164/f342567b-f44a-4f30-9865-6fffb858bf66)

Is that what you're experiencing? I wonder also if this could be a difference between how plugins load somehow? I know Influx is bundled with grafana and athena is bundled separately? 

I also notice that influx db seems to lazy load their panels. So if your browser is very narrow and only has 2 queries visible on a dashboard with say 30 panels, it will only load 2 panels.

But with Athena it looks like we do something similar, except... more of them? When I shrink the size of my window so that 2 panels are visible, 6 queries return back finished (I confirmed they all seem like separate queries). But then again I notice that the Athena dashboard has more template variables than the influx dashboard. In fact it has 4 :) I find it interesting that the influx db template variables don't fire off `/query` perhaps they are made with hard coded values or regexes ?

So in that sense it would make sense to me that this is not really an apple to apples comparison, where one dashboard is actually loading 4 more queries with template variables than another, and that could explain the difference in time? I think if you can spot a specific way we could improve performance here do let us know! At the moment I'm not sure I see one (but that doesn't mean it doesn't exist!)

**Comment by MatinF** [comment] 2024-02-26 14:18
correct, the unexpected behavior is that the loading view takes up far longer time vs. the comparable InfluxDB dashboard - to an extent that I do not think makes sense when comparing what is loaded. It may not be fully like-for-like, but I just wanted to point out that this doesn't seem as expected. I don't have a solution

**Comment by sarahzinger** [comment] 2024-03-12 19:31
Hey @MatinF Been thinking through this and until we have ideas on how to make this actionable, we're going to close this as "won't fix" for now. We appreciate you bringing it to our attention though, and will continue to try to brainstorm performance improvements. If you do happen to see ways we can improve this code definitely let us know! Sorry we don't have a more satisfying answer to this one at this time.

**Closed by sarahzinger** 2024-03-12 19:31 UTC
Labels: triage/needs-confirmation
