### ISSUE TITLE
time range

### ISSUE THREAD

**Issue by caotic112** [grafana/grafana#3492] opened 2015-12-11 09:32 UTC
On influxdb 0.9 the now() - xM doesn't work.The accepted parameters are:
u microseconds
s seconds
m minutes
h hours
d days
w weeks

**Comment by torkelo** [comment] 2015-12-11 09:59
What version are using? Think this is fixed in master and 2.6

**Closed by torkelo** 2015-12-11 09:59 UTC

**Comment by caotic112** [comment] 2015-12-11 10:06
2.5.0 , i'll try the 2.6, still a question, with big range time my influxdb crash with nothing in the log, what could be the problem?

**Comment by torkelo** [comment] 2015-12-11 11:59
The problem is that your using InfluxDB, it crashes all the time
