### ISSUE TITLE
postgres (TimescaleDB): "Null value: null" does not work

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#25060] opened 2020-05-25 02:37 UTC
**What happened**:
When using postgres with timescaledb enabled, when there are gaps in the data, these gaps are hidden by automatically connecting the graph line from the point prior to the gap to the point after the gap.

**What you expected to happen**:
Gaps should not bridged unless grafana has been configured to do so. That is why it has the option after all:

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/1826947/82773013-ea8c1080-9e0e-11ea-88c2-fb53163d1a24.png)
Note the gap in the data between 16:06 and 16:09, and how the graph hides it by connecting the points. Also note that I have it set so that null values should be null.

**Anything else we need to know?**:
Grafana is using the wrong function for grouping by time. It should be using `time_bucket_gapfill()`, not `time_bucket()`. The former will returns null values for the gaps.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: PostgreSQL 12 with TimescaleDB
- OS Grafana is installed on: CentOS/8
- User OS & Browser: Linux Chrome
- Grafana plugins: None
- Others:

**Comment by marefr** [comment] 2020-05-26 06:30
Duplicate of #15145

**Closed by marefr** 2020-05-26 06:30 UTC
Labels: area/datasource/frontend, area/frontend, datasource/Postgres
