### ISSUE TITLE
Annotations: OK state being annotated after a NoData event even when NoData is set to OK

### ISSUE THREAD

**Issue by michael-sawczuk** [grafana/grafana#69185] opened 2023-05-26 15:25 UTC
### 
# What went wrong?

**What happened**:
An alert rule has been assigned to a panel and data is only available when a certain condition is met, this means NoData occurs often. The alert-rule has been configured to see NoData as an OK state however once data arrives an OK annotation is added to the panel.

**What did you expect to happen**:
If NoData is set to OK state then no annotations should be added to the panel when the rule changes from NoData to OK.
 

### 
# How do we reproduce it?

**Step 1**:
- Have a metric that only has data points when a specific event occurs

**Step 2**:
- Create an alert rule to check if the data point is greater than 1 and set treat NoData as OK

**Step 3**:
Watch the panel start to get filled with annotations as the rule moves from NoData to OK to NoData to OK.

![image](https://github.com/grafana/grafana/assets/16261916/6c4e1c30-fa6f-46e4-8a7c-2f77fe83c78d)

This did not occur with Grafana legacy alerting

### 
# What Grafana version are you using?

v9.4.9, v9.5.2

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### Is this a Regression?

None

### Are Datasources involved?

Influx 1.8

**Comment by tonypowa** [comment] 2023-05-31 11:20
hi @michael-sawczuk 

this should be a expected behavior since it is a state transition.

You are welcome to start a  [GitHub discussion](https://github.com/grafana/grafana/discussions), or convert this issue into one, to see if other users in the community would agree with having less annotations of this kind, as in legacy alerting.

**Comment by michael-sawczuk** [comment] 2023-05-31 12:04
Hi @tonypowa, from a user perspective NoData is being treated as OK so there is no state change occurring, so when there is NoData, state = OK, when data arrives, state = OK, but Grafana isn't adhering to the setting. The annotations that Grafana is currently applying have no value.

Checking the alert history you can see the change into "Normal (NoData)" but never going into "OK" after data arrives.
![Untitled](https://github.com/grafana/grafana/assets/16261916/f9e99151-6c93-4284-b226-d818465f5f2f)

**Comment by tonypowa** [comment] 2023-06-06 13:05
@michael-sawczuk 
Forwarding the issue to the alerting team for further review

**Comment by grobinson-grafana** [comment] 2023-06-06 13:07
Hi! The output state is the same (**OK**), but a state transition did occur to get there (**NoData** -> **OK**). Grafana considers this as a different state event from (**OK** -> **OK**).

**Comment by michael-sawczuk** [comment] 2023-06-06 13:32
Hi @grobinson-grafana, what value does the treat NoData as OK serve when it comes to annotations?

**Comment by ahutson-bbc** [comment] 2023-06-06 13:34
> Hi! The output state is the same (**OK**), but a state transition did occur to get there (**NoData** -> **OK**). Grafana considers this as a different state event from (**OK** -> **OK**).

(**NoData** -> **OK**) isn't the one that's causing annotations, it's (**OK** -> **NoData**) that's doing that. If annotations are supposed to happen for transitions between those states, then it's half broken anyway. But I can't see any value in these anntations either.

**Comment by iridos** [comment] 2023-10-25 09:32
I see that as well on license data. There is no value in these annotations, but they make it hard/impossible to see the actual graph. 

The whole point  of treating "no data" as "ok" is that this is an expected state that is just as good as a certain value range. 

I have my collector not send any values when there is 0 use, because a lot of the curves are 0 all the time and I don't want this to clutter graphs (or even be stored in the tsdb)… others become 0 nightly and now I cannot view data on a long time-range anymore because all you can see are annotations.

**Comment by KaplanSarah** [comment] 2024-04-04 15:39
This issue has been fixed as of Grafana 10.3.
https://github.com/grafana/grafana/pull/77164

**Closed by KaplanSarah** 2024-04-04 15:39 UTC
Labels: area/alerting, triage/needs-confirmation
