### ISSUE TITLE
Passing Multi-Value Variables Between Dashboards

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#30760] opened 2021-01-30 08:40 UTC
**What happened**:

I created a variable named multiselect, with values 1, 2, 3, 4, 5. Grafana uses a syntax like this in the url:

```
&var-multiselect=1&var-multiselect=2&var-multiselect=3&var-multiselect=4&var-multiselect=5
```

And when passing the variable between dashboards using data link. By default, it passes the variable like this, and it doesn't work.

```
&var-multiselect={1,2,3,4,5}
```

![resizablegrafanaquerypanel](https://user-images.githubusercontent.com/43188411/106351855-ded2e100-62ef-11eb-9cac-e3d3342f12a6.gif)

**What you expected to happen**:

I expect it to pass the variable according to the url syntax. 

**How to reproduce it (as minimally and precisely as possible)**:

- Create 2 dashboards with same variable.
- Make the variables multi-value
- Use a data link to the variable from one dashboard the another.
- It should work fine when one value is selected but not multiple values are selected.

**Anything else we need to know?**:

I'm not use if this is a bug but if it's not I couldn't find the solution.

**Environment**:
- Grafana version: 7.3.7

**Comment by torkelo** [comment] 2021-02-01 20:11
duplicate of https://github.com/grafana/grafana/issues/21459

**Closed by torkelo** 2021-02-01 20:11 UTC

**Comment by singhgaurav007** [comment] 2023-03-02 12:59
Hi All,
Can anyone please suggest how to pass multi-value selection variable from one dashboard to other dashboard(drill down) using data link. i tried, but unable to understand how to add repeated variables in datalink URL.
For example
&var-multiselect=1&var-multiselect=2&var-multiselect=3&var-multiselect=4&var-multiselect=5.

Practically in grafana, how to add repeated variables like **var-multiselect**  in datalink. please suggest me.
![image](https://user-images.githubusercontent.com/15037988/222434864-abfab967-083a-45cd-81ac-291f98e13e43.png)
