### ISSUE TITLE
Annotations broken since 6.something for us

### ISSUE THREAD

**Issue by beorn-** [grafana/grafana#17176] opened 2019-05-20 14:21 UTC
**What happened**:
After upgrade dashboards with annotations enabled are showing the following messages:

Firefox
    ```Annotation query failed.
    e is undefined```

Chrome
    ```Annotation query failed.
   undefined is not iterable cannot read property Symbol(Symbol.iterator)```

In grafana logs i can see
    ```t=2019-05-20T14:07:20+0000 lvl=eror msg="failed to look up user based on cookie" logger=context error="user token not found" (edited) ```

**What you expected to happen**:
Nothing special really show the annotations

**How to reproduce it (as minimally and precisely as possible)**:
Just load the annotation

**Anything else we need to know?**:
i can provide whatever debugging information you'd need

**Environment**:
- Grafana version: at least 6.1.3, 6.1.6 and 6.2.0 (since 6.x)
- Data source type & version: not relevant
- OS Grafana is installed on: debian stretch with official grafana packages
- User OS & Browser: Linux Firefox-esr and Google Chrome
- Grafana plugins: not relevant

**Comment by marefr** [comment] 2019-05-20 15:05
Tried to reproduce on v6.1.6 using the following annotations settings and adding an annotation to a dashboard and then reloading:

![image](https://user-images.githubusercontent.com/1668778/58031697-367fe780-7b21-11e9-9d93-612f0560aa57.png)

It works as expected for me. Please include more information:
- Annotations settings in dashboard?
- Any errors in chrome developer tools console tab?
- Network response with annotations?

**Comment by beorn-** [comment] 2019-05-22 10:33
> It works as expected for me. Please include more information:
> 
>     * Annotations settings in dashboard?
The same as you 

>     * Any errors in chrome developer tools console tab?
The errors shown earlier
 
>     * Network response with annotations?
401 : {"message":"Unauthorized"}

Hence the log message from the annotations api in the issue

**Comment by beorn-** [comment] 2019-05-22 10:36
[console.log](https://github.com/grafana/grafana/files/3206972/console.log)

**Comment by marefr** [comment] 2019-05-22 12:02
Duplicate of #15316

**Comment by beorn-** [comment] 2019-05-22 12:18
Are you sure it's a duplicate ? There's no "when i un lock my computer after a long time" here.

**Comment by marefr** [comment] 2019-05-22 12:43
Related to #16319 since auth proxy is used

**Comment by marefr** [comment] 2019-05-22 12:49
First, since you're using auth proxy, please provide your related grafana configurations for auth proxy.

Second, can you provide a [HAR file](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366) when you're loading a dashboard where annotations request fails? If there's sensitive information you can send it to me personally on Slack for example.

**Comment by beorn-** [comment] 2019-05-22 13:04
HAR file sent on slack.

```
[auth.proxy]
enabled = true
header_name = X-Forwarded-Email
header_property = username
auto_sign_up = true
;ldap_sync_ttl = 60
;whitelist = 192.168.1.1, 192.168.2.1
```

**Comment by beorn-** [comment] 2019-05-22 13:04
the proxy is https://github.com/bitly/oauth2_proxy

**Comment by beorn-** [comment] 2019-05-22 13:06
Still happening with 6.2.0

**Comment by marefr** [comment] 2019-05-22 13:31
The only possible reason I can think of is that your proxy doesn't attach the auth proxy header name `X-Forwarded-Email` since you get a "failed to look up user based on cookie" which shouldn't be in use when there are an auth proxy header provided. Maybe you can have a look at request logs from your proxy?

**Comment by beorn-** [comment] 2019-05-22 13:38
i'll do a mitm and check for this.

**Comment by beorn-** [comment] 2019-05-22 15:17
You were right. When calling the `annotations` API the `X-Forwarded-Email` is missing but when calling the `dataproxy/proxy` API the `X-Forwarded-Email` is there. I've sent you data over slack about this.

**Comment by marefr** [comment] 2019-09-20 08:19
@beorn- so this is working now? Closing this. Let me know if you still have problem and I'll reopen.

**Closed by marefr** 2019-09-20 08:19 UTC
Labels: area/backend/auth, needs investigation
