### ISSUE TITLE
Lot of decimals on Y axis since 6.4

### ISSUE THREAD

**Issue by Hipska** [grafana/grafana#19651] opened 2019-10-07 07:45 UTC
**What happened**: Left Y axis has 6 decimals

**What you expected to happen**: Left Y axis to have 0, 1 or 2 decimals

**How to reproduce it (as minimally and precisely as possible)**:
It is a graph with interface traffic (unit: bits/sec) and Y axis decimals is left to be "auto". The tooltip values shows correctly with mixed 0 or 1 decimals.

It works fine if you put 0 or 1 as decimals setting, but auto always gives 6 decimals since this Grafana version.

**Environment**:
- Grafana version: 5.4
- Data source type & version: Graphite
- OS Grafana is installed on: Red Hat 7
- User OS & Browser: MacOS Safari

**Comment by torkelo** [comment] 2019-10-07 08:13
duplicate of https://github.com/grafana/grafana/issues/19541 

fixed in master and upcoming 6.4.2 patch

**Closed by torkelo** 2019-10-07 08:13 UTC

**Comment by Hipska** [comment] 2019-10-07 08:28
Thanks
