### ISSUE TITLE
Latest Grafana Version 7.4.1 Variables query using Elasticsearch data source not working

### ISSUE THREAD

**Issue by ashishkaransingh** [grafana/grafana#31165] opened 2021-02-12 11:45 UTC
**What happened**: Grafana 7.4.1 Variable query using Elasticsearch data source not working

**What you expected to happen**: Variable query using Elasticsearch data source should fetch data

**How to reproduce it (as minimally and precisely as possible)**: 
1) Add elasticsearch as datasource
2) Add a variable 
    Type: Query
{"find": "terms", "field": "fields.yourfield.keyword"}
 Preview of values: None

**Anything else we need to know?**: It works in 7.3.4

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: Elasticsearch 7.10.1
- OS Grafana is installed on:
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:
https://community.grafana.com/t/urgent-grafana-7-4-1-elasticsearch-datasource-not-working/43043

**Comment by torkelo** [comment] 2021-02-12 17:14
You need to provide more information here, unable to replicate https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated?orgId=1&var-source=backend&var-host=All 

@peterholmberg could you replicate?

**Comment by cruscio** [comment] 2021-02-12 20:00
We rolled back our dev server to 7.3.4 and stood up a clone on 7.4.1 - identical configs via docker environment variables, just copied over the grafana.db file.

We can share more config/logs from both working and not working systems, and from elasticsearch. Is there's something specific that'd helpful @torkelo

**Comment by D3luxee** [comment] 2021-02-17 08:26
Hi,
i can confirm that its broken but i see that you could not reproduce it and your queries look similar to ours.
Maybe the difference is in some details of the datasource or used elasticsearch version.
I've upgraded from 7.4.0 to 7.4.1 and it broke in 7.4.1, all plugins are up to date.


For me its the following:
Grafana 7.4.1 with Postgres as database.

**Datasource:**
Opendistro 1.10.1 / Elasticsearch 7.9.1
HTTPS + Basic Auth
Indexname: index-* | Pattern: No Pattern
Time field name: timestamp
Version: 7.0+
Max concurrent Shard Requests: 5
Min time Interval: 2m

**I was able to fix this temporary by:**
Edit -> Variables -> Select Variable -> Change Refresh from "On Dashboard Load" to "On Time Range..." then enable Value Group Tags and disable it again

This loaded all variables and you could see it in the Preview of values. But it throws following errors:
```Validation
Unexpected end of JSON input
```
```
Templating [myVariableName]
Error updating options: Unexpected end of JSON input

```
After going back to the dashboard everything worked.
Until you reload the dashboard entirely (F5) then its broken again.
After the reload all config changes are back to the previous settings (On Dashboard Load).


Maybe there is something broken in the database migration paths?
Do you upgrade play.grafana.org or just redeploy with the latest versions? Might be the reason why its working there but thats just wild guessing.

**Comment by barry-luijten** [comment] 2021-02-24 11:33
I have noticed the same problem with Grafana 7.4.2.
I found out that when the variable refresh is set to "On Dashboard Load", the query is performed against the data source with a time frame of the last 6 hours, irrespective of the selected time range on the dashboard. When the refresh is set to "On Time Range Change", the query does respect the selected time range.  In my case, I had variables based on a query against a dataset that contains monthly data, i.e. my timestamps are set to the first of each month. With the "On Dashboard Load" refresh setting, the query does not return any data, because there is none for the time range now-6h - now. 
This behavior was different in previous versions, so I must conclude this is either a breaking change or a bug ;)

**Comment by Elfo404** [comment] 2021-02-26 09:57
@barry-luijten what you described led me to https://github.com/grafana/grafana/pull/29770 where we removed the dependency on `timeSrv`, so we are defaulting to `now - now-6h` because on first load `options` is undefined in https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L729

@hugohaggmark you might have more context here, is there a way to get the actual time range there without depending on `timeSrv` ? or maybe `getTimeSrv` should be part of `@grafana/runtime` ?

**Comment by hugohaggmark** [comment] 2021-02-26 11:38
> getTimeSrv

Shouldn't this line be enough @Elfo404, not sure I understand the complete context:
https://github.com/grafana/grafana/blob/eddc163e78b433cd678561f89a85a1f3e349c8ad/public/app/features/variables/query/VariableQueryRunner.ts#L177

**Comment by Elfo404** [comment] 2021-02-26 12:02
Had a quick chat with @hugohaggmark (thanks!) and it's actually working as expected. what we were doing before was injecting the time in a non-standard way.

when selecting 'On Dashboard Load' as a refresh option, we assume the query doesn't depend on the time. In elasticsearch we default to `now-now-6h`, that's just a way to have a time range to infer an index name from.

@D3luxee what you are describing feels like a different bug, the "fix" for this one is just setting the refresh to "On Time Range Change", could you please open new issue for that?

so, @barry-luijten this is indeed a "breaking change" is it's changing the previous behavior, but we were just doing the wrong thing before the change 😄 

Closing this as it seems a non-issue. we can reopen if there's something I missed :)

**Closed by Elfo404** 2021-02-26 12:02 UTC
Labels: area/dashboard/templating, datasource/Elasticsearch, priority/important-soon, type/bug
