### ISSUE TITLE
Influxdb: Support InfluxDB 1.2+ Partial data responses 

### ISSUE THREAD

**Issue by khenderick** [grafana/grafana#7380] opened 2017-01-26 21:01 UTC
I have a dashboard that returns a large amount of data, a lot more than the default 10,000 rows after which InfluxDB will start chunking the returned data. I recently updated from InfluxDB 1.0.2 to 1.2.0 and suddenly, not all data is shown.

I noticed a change in InfluxDB 1.2 that might be related; a "partial" tag is added indicating more data is available. See https://github.com/influxdata/influxdb/pull/7368

Grafana 4.1.1
Datasource: InfluxDB 1.2
OS: Archlinux

**Comment by torkelo** [comment] 2017-01-27 06:04
Is this a breaking change in InfluxDB? So they are not returning the data for the full time span anymore?

**Comment by torkelo** [comment] 2017-01-27 06:05
Wonder if there is a way to disable partial response chunking

**Comment by khenderick** [comment] 2017-01-27 06:17
I looked with Chrome Dev tools to the query that was executed. When replaying that query in a browser window, I could see the partial result, with this extra `"partial": true` key added. Based on the docs (https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/ section "chunking") it is possible to add a `chunked=true` parameter to the HTTP request that will cause InfluxDB to provide the full reply in streaming batches.

The odd thing is that this setting was also available in 1.0 (so with the same limit of datapoints returned, possibility for streaming with this chunked=true parameter), but the "partial" indicator wasn't there.

**Comment by einhirn** [comment] 2017-01-27 08:05
From what I understand in the referenced influxDB issue post, the partial flag was added to influxDB's chunked response to make it easier for clients to identify a chunked response...

@torkelo not quite - only thing you can do is to change Chunk size: https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/ -> "Chunking". But I don't know if the "max_rows" config setting in influxDB overrides this query parameter.

**Comment by torkelo** [comment] 2017-01-27 10:37
So how does it work? Do you get a url with the second chunk or does the http response contain multiple json bodies? Is this compatible with the json decoders in browser?

**Comment by einhirn** [comment] 2017-01-27 13:12
I've just tried this against our InfluxDB v1.2:
[chunked query.txt](https://github.com/grafana/grafana/files/735295/chunked.query.txt)
It seems you just get multiple json bodies.

**Comment by Andy2003** [comment] 2017-01-28 10:28
relates to https://github.com/grafana/grafana/issues/863

**Comment by Andy2003** [comment] 2017-01-28 10:39
@torkelo 

modern browsers support chunked response processing (see here: http://stackoverflow.com/a/12280916 )

**Comment by salarali** [comment] 2017-01-31 17:36
Is there a quick fix resolution for this?
Or we have to wait?

**Comment by torkelo** [comment] 2017-01-31 18:12
Is there a way to disable chucking?

**Comment by salarali** [comment] 2017-01-31 18:20
Maybe set `max_row_limit` to zero?
https://github.com/influxdata/influxdb/issues/7879

**Comment by orester** [comment] 2017-02-01 08:52
max-row-limit works but never tried setting it to zero.

**Comment by FrederikP** [comment] 2017-02-01 13:36
Setting it to zero worked for me, because I also had this issue after upgrading to influxdb 1.2 . You just have to be careful as there is no other safety measure regarding RAM usage, depending on the amount of data you query and your hardware.

**Comment by ayebayley** [comment] 2017-02-10 16:06
Any progress on this? I'm seeing the same issues after my upgrade to Influx 1.2. I'm a little hesitant to change the max-row-limit due to already existing RAM constraints on the server.

**Comment by willemdh** [comment] 2017-02-12 15:56
Could this issue be the reason why we sometimes get limited results in Grafana lately? When zooming out or using larger intervals more results seem to be loaded. But on low intervals (1 - 10s) I seem to missing results when using queries with templates.

**Comment by Andy2003** [comment] 2017-02-13 12:03
@willemdh yes I guess so

**Comment by phemmer** [comment] 2017-02-14 04:20
One thing that has helped us significantly with this issue is to change the default `fill(null)` to `fill(none)`.
For us, in some of our graphs, grafana was sending back thousands of "null" points. Using `fill(none)` causes influxdb to not send these.
This is especially problematic when using the auto-interval feature, and grafana selects an interval smaller than the frequency of your data.


P.S. It would be really nice to be able to change the defaults for things like this.

**Comment by bergquist** [comment] 2017-02-14 09:10
This would also require partial support for influxdb in the backend.

**Comment by torkelo** [comment] 2017-02-17 12:31
this looks like an InfluxDB bug, as it seems to ignore chunked=false parameter. With that set to false it still returns a partial response (but only 1 partial response), if I set it to true it will return more results, but this looks like a bug in InfluxDB, firstly it returns a partial response (when it did not before 1.1x) and it does so even with chunked=false. If I set chunked=true it does return the reminaing chunks but that requires a custom json deserialiser for InfluxDB as the response is no longer valid json. Should be possible to do but think this needs to be fixed in InfluxDB

**Comment by jl98800** [comment] 2017-02-17 13:04
Thanks!

We worked around this by setting max-row-limit to the largest query results. Everyone is happy now. 

Thanks,

John

**Comment by phemmer** [comment] 2017-02-17 13:20
> If I set chunked=true it does return the reminaing chunks but ... the response is no longer valid json

That's arguable. The resulting format is in a widely used format called [JSON streaming](https://en.wikipedia.org/wiki/JSON_Streaming)

In general, using a JSON streaming format is a good thing. The reasons I've always used it are the same reasons InfluxDB is using it now: Having one giant JSON object requires holding the entire thing in memory before you can try to parse it. JSON streaming allows you to digest it in chunks. It also means you can start processing it before all data has been received. Though this point doesn't matter much here.

Now I'm not saying there isn't a bug in InfluxDB, as there very well may be. I might also have expected `chunked=false` to prevent the result from being limited. However to play devil's advocate, I can understand why it might have been done this way as a client could use this to OOM InfluxDB by requesting a massive result set.

**Comment by khenderick** [comment] 2017-02-17 13:34
I guess they understand the `chunked=false` parameter as "please give me the full result set". And because it hits the `max-row-limit` configuration value, it reports that the non-chunked result is however only partial. If you add `chunked=true` to the query parameters, will stream the response in chunks, as requested. I'd expect that you can't request a `chunk_size` to be more than the configured `max-row-limit`.

Grafana could for example by default use a `chunk_size` of 1000 entries to load the graphs progressive, showing results as they come in.

So I don't think that they will see it as a bug on their end.

**Comment by jl98800** [comment] 2017-02-17 15:37
Funny thing is previous to influxdb 1.2 max rows was set to 0 because of a bug.  We upgraded to 1.2 and ran into the issue when max rows was set to 1000. We've increased it to 12000 and all is well. 

Thanks,

John

**Comment by torkelo** [comment] 2017-02-17 15:37
If they see `max-row-limit` as overriding the chunked parameter I guess that can be seen as not a bug but a backend feature that results in a major breaking API change. Sadly nothing in the InfluxDB  ChangeLog is mentioning this breaking change which is causing so many issues for InfluxDB users :( 

>That's arguable. The resulting format is in a widely used format called JSON streaming

Not it's not. Its a very different response format that required vastly different result processing. I was not saying it's a bad practice or uncommon format, just not something that is easily interchanged with a normal json response :) 

So setting `max-row-limit` is a workaround, but so many users are going to troubleshoot and have a bad time before finding this issue and that workaround, so we need a quick solution in Grafana. The tricky thing is that there is no quick way to do this as angular $http service does not support multiple json bodies in responses so we have to handle responses in a non standard way (compared to other json data sources). And it needs to be implemented in the backend as well for alerting queries that target large time spans or many series. I wish there was a simple solution for this in Grafana but I cannot find it. Would be simpler for InfluxDB to change back the default value for max-row-limit but I guess they did that change for a reason.

**Comment by corentingi** [comment] 2017-03-01 13:16
Would it be possible to show a panel warning when the influxdb response contains a `partial=true`?

**Comment by elvarb** [comment] 2017-03-10 11:15
I'm having similar problems but with smaller datasets instead of larger.

    SELECT count("Available_Bytes") FROM "win_mem" WHERE $timeFilter GROUP BY time(1m), "host", "domain" fill(null)


With this query for the last 1h results in no hits.
![image](https://cloud.githubusercontent.com/assets/1716457/23793368/c66498b2-0582-11e7-8fda-43979f5e6744.png)

If I change the timeframe to the last 3h I actually get the last 2h while the last 1h is blank.
![image](https://cloud.githubusercontent.com/assets/1716457/23793350/afbf41ac-0582-11e7-8982-d1f723688a15.png)

**Comment by jwilder** [comment] 2017-03-14 18:30
We're switching the default `max-row-limit` to `0` for InfluxDB 1.2.2 since it inadvertently changed behavior.  See https://github.com/influxdata/influxdb/pull/8133

**Comment by dandv** [comment] 2018-08-19 08:41
I see `partial: true` in responses, even though the entire response has been received. SELECT COUNT(*) WHERE... shows `41369`. The same number of elements have arrived to the client, yet `partial: true` was set as well in the response. Shouldn't it be `partial: false`?

Influx 1.4.2.

**Comment by gabor** [comment] 2021-06-01 09:54
it seems the original problem was resolved with https://github.com/grafana/grafana/issues/7380#issuecomment-286517025 , so closing this issue.

note: we have a separate issue open for adding a warning in partial-response-cases ( https://github.com/grafana/grafana/issues/18725 ), and also a separate issue for handling chunked responses ( https://github.com/grafana/grafana/issues/863 )

@dandv if your problem mentioned in https://github.com/grafana/grafana/issues/7380#issuecomment-414112992 still exists, please open a separate issue and we can look at it there. thanks.

**Closed by gabor** 2021-06-01 09:54 UTC
Labels: area/datasource, datasource/InfluxDB, effort/large, help wanted, priority/important-longterm, type/feature-request
