### ISSUE TITLE
Grafana 9.0.0: Unexpected error while loading a Prometheus datasource in Explore view

### ISSUE THREAD

**Issue by dbluxo** [grafana/grafana#50870] opened 2022-06-15 11:49 UTC
**What happened**: Updated from Grafana 8.5.1 to 9.0.0 (without changing any of the Grafana config)

When we open the Explore view for the datasource listed below, we see an "Unexpected error".

Grafana 9.0.0:

<img width="1626" alt="Bildschirmfoto 2022-06-15 um 13 18 32" src="https://user-images.githubusercontent.com/20679842/173817701-285ab312-1400-499d-9311-87c5a7dbf18b.png">
<img width="1124" alt="Bildschirmfoto 2022-06-15 um 13 17 18" src="https://user-images.githubusercontent.com/20679842/173817709-15332505-51f8-4814-9993-6950d1378c2d.png">

Grafana 8.5.1:

<img width="1622" alt="Bildschirmfoto 2022-06-15 um 13 25 43" src="https://user-images.githubusercontent.com/20679842/173817798-d8299ae7-37c6-4e3f-92b5-07e184603a38.png">
<img width="1107" alt="Bildschirmfoto 2022-06-15 um 13 31 21" src="https://user-images.githubusercontent.com/20679842/173817793-980cd707-5073-418f-9e5b-9ff70654bc43.png">

What I see as differences:

1. With Grafana 9.0 there is an unexpected error when opening the Explore view. 
2. The message "Labels and metrics lookup was disabled in data source settings." is not shown anymore.
3. Furthermore, I see that the `rules` and `query_examplars` requests end in a 401.
4. And 403s are logged continuously:

logger=live t=2022-06-15T11:35:06.776238617Z level=warn msg="Request Origin is not authorized" origin=https://grafana-observability-lab.<redacted-domain> host=grafana:80 appUrl=http://localhost:3000/ allowedOrigins=
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2022-06-15T11:35:06.776303276Z level=info msg="Request Completed" method=GET path=/api/live/ws status=403 remote_addr=x.x.x.x time_ms=1 duration=1.502536ms size=10 referer= traceID=00000000000000000000000000000000

Datasource configuration:

```yaml
apiVersion: 1
datasources:
- orgId: 1
  version: 1
  name: Billing-observability-lab
  type: prometheus
  access: proxy
  url: https://amp-user-proxy.observability-lab.svc.cluster.local:8443
  jsonData:
    customQueryParameters: namespace=observability-lab
    disableMetricsLookup: true
    httpHeaderName1: Authorization
    httpMethod: GET
    manageAlerts: false
    tlsSkipVerify: false
  secureJsonData:
    httpHeaderValue1: $BILLING_OBSERVABILITY_LAB_HTTPHEADERVALUE_1
```

**What you expected to happen**: Opening the Explore view without errors. 

**Anything else we need to know?**: However, dashboards based on this datasource appear at first glance to be able to retrieve metrics and work.

**Environment**: 
- Grafana version: 9.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker, Kubernetes
- User OS & Browser: Firefox, Safari, Chrome

**Comment by dbluxo** [comment] 2022-06-15 13:26
I was able to fix the 403 messages with the `allowed_origins` [setting](https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/#allowed_origins).

The other problems remain:

1. With Grafana 9.0 there is an unexpected error when opening the Explore view. 
2. The message "Labels and metrics lookup was disabled in data source settings." is not shown anymore.
3. Furthermore, I see that the `rules` and `query_examplars` requests end in a 401.
4. ~~And 403s are logged continuously:~~

**Comment by dbluxo** [comment] 2022-06-21 19:39
Same with Grafana 9.0.1

**Comment by dbluxo** [comment] 2022-07-04 10:39
Same with Grafana 9.0.2

**Comment by dbluxo** [comment] 2022-07-06 11:27
Just saw that in Chrome browser it doesn't show an "Unexpected error" like in Firefox/Safari browser, but an "Unauthorized", so I strongly suspect it's related to the `rules` and `query_examplars` requests, the only question is how to avoid it. 

<img width="1655" alt="Bildschirmfoto 2022-07-06 um 13 18 43" src="https://user-images.githubusercontent.com/20679842/177539926-5eae036e-6abc-45df-b980-75b5dc2249d3.png">

**Comment by gbeyer3** [comment] 2022-07-08 13:06
Getting the same issue in v9.0.2 (0641b5d0cd)   I am unable to edit any of my existing queries, or create new ones!

**Comment by gtk-grafana** [comment] 2022-08-22 18:58
@gbeyer3 Can you open up another issue if you are still having trouble? If you are unable to edit your queries that is likely something another issue.

**Comment by gtk-grafana** [comment] 2022-08-22 19:37
I can't reproduce this error on 9.0.2 or 9.0.1, it looks as though the UI is showing an error message that shouldn't be exposed to the front-end, but I would assume that you can safely ignore this issue as long as there is no functional impact and things are working properly. 
Also there were some changes to error handling in more recent versions, so upgrading Grafana to the most recent might solve this error as well.
@dbluxo What version of prometheus are you running?

**Comment by gtk-grafana** [comment] 2022-08-24 14:27
Potential Duplicate of https://github.com/grafana/grafana/issues/53451, closing since this is no longer an issue on 9.0.5 and up.

**Closed by gtk-grafana** 2022-08-24 14:27 UTC
Labels: type/bug, datasource/Prometheus, needs investigation
