### ISSUE TITLE
Updating Varables using getLocationSrv.update doesn't trigger update of query

### ISSUE THREAD

**Issue by Jim-Rouse** [grafana/grafana#25667] opened 2020-06-17 13:43 UTC
Using the following typescript code to update a dashboard variable.  The URL updates but there is no update triggered on the dashboard to update the underlying datasource.

getLocationSrv().update({partial:true, query: {'var-enterpriseservice_id':serviceId.toString()}, replace:true});

**What happened**:
Url updated but the page doesn't update the queries or attempt to communicate with the backend.

**What you expected to happen**:
Updating the variable should trigger a request to update the queries that are dependent on respective variable.

**How to reproduce it (as minimally and precisely as possible)**:
Create dashboard with variable, Create plugin that updates the variable using typescript using the template: getLocationSrv().update({partial:true, query: {'var-enterpriseservice_id':serviceId.toString()}, replace:true});

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Microsoft SQL Server
- OS Grafana is installed on: (Docker)
- User OS & Browser: (Chrome)
- Grafana plugins: Custom
- Others:

**Comment by torkelo** [comment] 2020-06-17 17:13
Fix coming in v7.1 

duplicate of #25115

**Closed by torkelo** 2020-06-17 17:13 UTC
