### ISSUE TITLE
[Bug] Problems with rendering table panel for raw_document data

### ISSUE THREAD

**Issue by danmx** [grafana/grafana#8401] opened 2017-05-17 13:25 UTC
Please include this information:
>- What Grafana version are you using?

4.2, 4.3
>- What datasource are you using?

ElasticSearch 5.1
>- What OS are you running grafana on?

running raw binary on MacOS and also tested running in docker container
>- What did you do?

Created a table panel and fed it raw_document json data
>- What was the expected result?

Table with properly alined column names with corresponding data 
>- What happened instead?

  - When data string was shorter than column name then column names overlapped.
  - When string data was too long and wasn't divided into rows (e.g. a very long hash or a random string) column names of last columns were displayed outside of table panel.
  - When data were too long and panel had to be scrolled horizontally column names stayed in the same place which made table very unclear and hard to read.

Screenshot:
![screen shot 2017-05-17 at 15 19 45](https://cloud.githubusercontent.com/assets/11769367/26155689/5cefc006-3b14-11e7-9e58-4163226f29eb.png)

**Comment by torkelo** [comment] 2017-05-19 08:40
duplicate of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2017-05-19 08:40 UTC
