### ISSUE TITLE
Allow execution of multiple MySQL commands at once

### ISSUE THREAD

**Issue by y0gzah** [grafana/grafana#10060] opened 2017-12-03 13:57 UTC
Hi, first of all thank you for the lovely system.

I have an issue in which I'm trying to set varibales in MySQL before executing my query.
For example:
SET @end_date = '2017-11-30';
SET @start_date = '2016-01-01';
SELECT * FROM `Recruitments`;

(Recruitments is a view in which I work with global variables, don't ask why I work this way, this is my only option at the moment.)

This query however should work just fine in a mysql_query command.
However, Grafana always throws a syntax error.

Is it possible to disable the syntax checker?
Would you consider allowing multiple commands in a MySQL query?

**Comment by daniellee** [comment] 2017-12-04 12:44
Duplicate of #8755

This is not on our current roadmap unfortunately.

Can you wrap this query in another view or use temp tables to be able to use a vanilla select statement?

**Closed by daniellee** 2017-12-04 12:44 UTC
Labels: datasource: MySQL, type: duplicate

**Comment by y0gzah** [comment] 2017-12-06 08:23
I need to be able to set Grafana's start date and end date in the variables, therefore my only way is to be able to execute multiple MySQL statements in one query.
What if I contribute the appropriate changes to the project, would that be accepted?

**Comment by daniellee** [comment] 2017-12-06 12:55
@y0gzah to merge a PR for this, then we would need more than just the code. 

- Are there any security considerations around allowing this? 
- What would be the [recommended database user permissions](http://docs.grafana.org/features/datasources/mysql/#database-user-permissions-important)?
- Does this break any of the mysql compatible data sources? (MariaDB, AWS RDS/redshift etc.)
- Is it backwards compatible and do the macros work as expected?

But if we have good answers to these questions then yes, we would merge it.
