### ISSUE TITLE
[Feature Request] Adds text/color mapping when show is set to name

### ISSUE THREAD

**Issue by arcenik** [grafana/grafana#21063] opened 2019-12-12 13:23 UTC
**What would you like to be added**:

The goal is to show the systemd service status with a SingleStat panel and have a color according to the state.

The SingleStat panel has those parameters:
* Query: node_systemd_unit_state{instance="test",name="crond.service"} > 0
* Legend: {{ state }}
* Show: Name

The returned value is alway 1 but the state label can change.

```
node_systemd_unit_state{instance="test",job="amosmon_nodes",name="crond.service",state="active",type="simple"}	1
```

**Why is this needed**:

Adds a text to color mapping or text to value mapping and use the threshold to do the coloring

**Comment by marefr** [comment] 2019-12-13 19:17
Duplicate of #11418

**Closed by marefr** 2019-12-13 19:17 UTC
