### ISSUE TITLE
notification via email using SMTP uses TLS irrespective of config

### ISSUE THREAD

**Issue by raviscal** [grafana/grafana#7780] opened 2017-03-09 00:31 UTC
{BUG}: Grafana is uisng TLS for smtp server connection irrespective of changing the config file.

Please include this information:

What Grafana version are you using?
4.1.1
What datasource are you using?
influxdb
What OS are you running grafana on?
ubuntu

What did you do?
trying to set notification via email

What was the expected result?
notification succeeds

What happened instead?
"remote error: tls: handshake failure"

INFO[03-08|15:49:40] Sending alert notification to logger=alerting.notifier.email addresses=[rbommu@qualcomm.com]
EROR[03-08|15:49:40] Failed to send alert notification email logger=alerting.notifier.email error="remote error: tls: handshake failure"
EROR[03-08|15:49:40] Failed to send alert notifications logger=context userId=1 orgId=1 uname=admin error="remote error: tls: handshake failure"
EROR[03-08|15:49:40] Request Completed logger=context userId=1 orgId=1 uname=admin method=POST path=/api/alert-notifications/test status=500 remote_addr=10.64.101.18 time_ms=67ns size=48

I changed the property 'skip_verify' to true and false but no luck. Is there anyway not to use SSL/TLS connection?

[smtp]
enabled = true
host = smtphost.:25
user =
password =
cert_file =
key_file =
skip_verify = false
from_address =

**Comment by torkelo** [comment] 2017-03-09 05:55
Hi, thanks for reporting this, 

We already are aware of this, so closing due to duplicate of https://github.com/grafana/grafana/issues/7189

**Closed by torkelo** 2017-03-09 05:55 UTC

**Comment by torkelo** [comment] 2017-04-11 13:31
what smtp server are you using? Does it support TLS? When I spin up a smtp server without TLS on port 25 I get no errors, so it seem to work fine. But your SMTP server seems to want to renegotiate the connection to TLS.
