### ISSUE TITLE
Grafana 5 fails to create user specified in auth proxy header

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#10276] opened 2017-12-19 10:41 UTC
```
t=2017-12-19T11:37:46+0100 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
```

With proxy auth settings and autosubscribe, I get the following error:

**Comment by roidelapluie** [comment] 2017-12-19 10:43
I don get it all the time, it just happens once in a while

**Comment by roidelapluie** [comment] 2017-12-26 12:15
This is due to SQLite dB being locked.

**Comment by roidelapluie** [comment] 2017-12-26 12:16
Not sure why it is locked. Maybe we try to access it from 2 go routines.

**Comment by friesoft** [comment] 2018-01-03 15:11
Experiencing the same issue on 5.0.0-11065pre1, the username provided in the Header is not created

**Comment by BugRoger** [comment] 2018-02-07 12:08
Seeing this too. I think, the `auth.proxy` is completely stateless. On each request, it updates the `user_seen_at` date of a user. Additionally, it seems to retry to auto-signup the user again. I suppose, this usually bails out with a benign "user already exists"-error and continues.

Occasionally, when reloading a dashboard multiple requests seem to hit at exactly the same time and cause a database lock. Some kind of retry logic kicks. It eventually updates the `user_seen_at`. 

Once the request gets to the auto-sign it looks like the db lock falsely causes another sign-up for an already existing user. That fails with the uniqueness constraint.

See this log. It's a single dashboard (with multiple panels) being requested.

```
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=D038720 user_id=2
t=2018-02-07T10:28:29+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:29+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:29+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:29+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:29+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:29+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:29+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
t=2018-02-07T10:28:30+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=500 remote_addr=198.18.0.78 time_ms=89 size=1154 referer="https://grafana.kubernikus.eu-nl-1.cloud.sap/dashboard/db/kubernikus?refresh=1m&orgId=1&kiosk=true"
t=2018-02-07T10:28:30+0000 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
t=2018-02-07T10:28:30+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=500 remote_addr=198.18.0.78 time_ms=90 size=1154 referer="https://grafana.kubernikus.eu-nl-1.cloud.sap/dashboard/db/kubernikus?refresh=1m&orgId=1&kiosk=true"
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
t=2018-02-07T10:28:30+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=500 remote_addr=198.18.0.78 time_ms=122 size=1154 referer="https://grafana.kubernikus.eu-nl-1.cloud.sap/dashboard/db/kubernikus?refresh=1m&orgId=1&kiosk=true"
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=0
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=2
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=2
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=2
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=1
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=2
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=2
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=3
t=2018-02-07T10:28:30+0000 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
t=2018-02-07T10:28:30+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=500 remote_addr=198.18.0.78 time_ms=226 size=1154 referer="https://grafana.kubernikus.eu-nl-1.cloud.sap/dashboard/db/kubernikus?refresh=1m&orgId=1&kiosk=true"
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=3
t=2018-02-07T10:28:30+0000 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
t=2018-02-07T10:28:30+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=500 remote_addr=198.18.0.78 time_ms=268 size=1154 referer="https://grafana.kubernikus.eu-nl-1.cloud.sap/dashboard/db/kubernikus?refresh=1m&orgId=1&kiosk=true"
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=3
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=2
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=4
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=3
t=2018-02-07T10:28:30+0000 lvl=info msg="Database table locked, sleeping then retrying" logger=sqlstore retry=3
t=2018-02-07T10:28:30+0000 lvl=eror msg="Failed to create user specified in auth proxy header" logger=context error="UNIQUE constraint failed: user.email"
```

**Comment by sni** [comment] 2018-02-07 12:36
Btw, we are seeing this with 4.6.3 as well, assuming the code has not much changed from 4 to 5 at this point.

**Comment by BugRoger** [comment] 2018-02-07 15:00
I think, the only way this error could happen if this line returns `ErrUserNotFound` even though the user exists. In my case the user definitely exists already.
https://github.com/grafana/grafana/blob/9dac602e98dfda546ae52f8059caca99a2578e84/pkg/middleware/auth_proxy.go#L34

That leads me to:
https://github.com/grafana/grafana/blob/c395237710eaa7629e9f7d321082da9100f1f463/pkg/services/sqlstore/user.go#L375

So, sometimes this query fails without error but doesn't return a user. Oddly enough, as you can see from the log it even manages to update the `last_seen` timestamp for that user before. 

I don't understand how the session handling works here and what could go wrong. I'd guess it somehow swallows the lock and returns nil. Maybe someone else has an idea.

**Comment by daradib** [comment] 2018-02-26 07:14
@BugRoger I set `auto_sign_up = false` and I still get the 401 responses on dashboard updates, but the error changed:

    lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"

even though the user exists, as you mentioned. No more "Database table locked" errors though.

I'm also using the embedded SQLite. Is this reproducible with MySQL?

**Comment by degremont** [comment] 2018-05-17 12:37
I've got a similar setup and I'm seeing the same kind of failing request `Failed to create user specified in auth proxy header` (by the way, it could be nice if error messages have more details like culprit username here)

Grafana is sitting being a auth proxy. All users already exist for a while. This happens when a dashboard with multiple panel reloads. I see this with Grafana 5.0.4 and 5.1.2

**Comment by daradib** [comment] 2018-05-22 22:19
@degremont I switched the [Grafana database](http://docs.grafana.org/installation/configuration/#database) from the default embedded SQLite to MySQL/MariaDB and can't reproduce this issue anymore.

**Comment by degremont** [comment] 2018-05-23 14:18
Thanks @daradib but using a MySQL server for storing a 5 MB database is overkill to me. I think SQLite perfectly fit Grafana need for small deployments.

I was rather thinking about disabling `last_seen` update (even if I like this feature). If `auth_proxy` become read-only, I think this should work around the problem.

At the end, the real fix is that `auth_proxy` should handle concurrency properly.

**Comment by torkelo** [comment] 2019-07-03 05:01
closing this, we have improved/changed some of the related code here, and no new reports in over a year

**Closed by torkelo** 2019-07-03 05:01 UTC
Labels: area/backend/auth, type/bug
