### ISSUE TITLE
Cloudwatch: flow-logs demo query produces error

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#24637] opened 2020-05-13 15:41 UTC
Cloudwatch datasource in Explore:

Click on VPC Flow Logs
Average, min, and max byte transfers by source and destination IP addresses
`stats avg(bytes), min(bytes), max(bytes) by srcAddr, dstAddr`
produces error:

```
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

**Comment by aocenas** [comment] 2020-05-14 11:51
This is actually duplicate of https://github.com/grafana/grafana/issues/24639

**Closed by aocenas** 2020-05-14 11:51 UTC
Labels: datasource/CloudWatch, type/bug
