### ISSUE TITLE
No data on a stat panel when displaying 'Time' instead of value itself (Public dashboard)

### ISSUE THREAD

**Issue by spookyrecharge** [grafana/grafana#62479] opened 2023-01-30 14:26 UTC
**What happened**:
I'm trying to make a public dashboard where my neighbors can see if there is electricity in the building and when there is no electricity. Everything is ok except one moment: I would like to display the timestamp of the last value I've got from my sensor. I got it displaying on original grafana dashboard when I'm logged in, but it doesn't work on a public dashboard as anonymous user.

![image](https://user-images.githubusercontent.com/5503131/215503664-508ef4a9-c124-4af5-a120-9d33de929a71.png)
FYI: There is no problem when displaying the value itself by using this query, but when I'm selecting 'Time' in 'Fields' - I've got 'no data' displaying on the panel

![image](https://user-images.githubusercontent.com/5503131/215503456-86650fcb-227b-4c6f-9cdd-7a7e943e8ade.png)
how it's looking when I'm logged in (non public dashboard view)

![image](https://user-images.githubusercontent.com/5503131/215503539-ab360d05-9339-4db1-86d9-84be1f0b0931.png)
and this is what I got when seeing it as public dashboard

**Environment**:
- Grafana version: 9.3.6
- Data source type & version: InfluxDB 1.8.10
- OS Grafana is installed on: 
- User OS & Browser: 
- Grafana plugins: 
- Others:

**Comment by mellieA** [comment] 2023-01-30 19:54
@spookyrecharge are you able to use the panel > get help button to share a copy of this panel that we can review? 

Have you noticed if you use developer tools in the browser and inspect the request/response in the network tab while logged in and viewing publicly if there is a difference in the return values or error messages?

**Comment by evictorero** [comment] 2023-05-23 18:00
I was able to reproduce this error with this JSON [JSON](https://github.com/grafana/grafana/files/11547064/repro-issue-62479.json.txt)
The issue occurs because the influxDB data source is querying the backend using a proxy. There is an [ongoing effort](https://github.com/grafana/grafana/issues/65045) targeting this Q about migrating to query without the proxy using the backend endpoint which is what public dashboards need to be fully compatible. 
This could be turned on and tested using a feature flag `influxdbBackendMigration` which is in [alpha stage](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/#alpha-feature-toggles).
Using this flag, I couldn't see any difference between the original dashboard and the public version.

**Comment by evictorero** [comment] 2023-05-23 20:25
Closing this issue since the `influxDB` querying using a proxy won't be supported by Public Dashboards. We expect to have this particular case working once the influxDB backend query is delivered. In the meantime, this could be tested with the feature flag.

**Closed by evictorero** 2023-05-23 20:25 UTC
Labels: area/dashboard, public-dashboards
