### ISSUE TITLE
Cache .betterer.cache

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#47866] opened 2022-04-19 08:55 UTC
For https://github.com/grafana/grafana/pull/45901

We want to introduce a tool to help us make gradual refactors to our codebase. The tool writes a cache file to disk which speeds up subsequent runs. 

I think we actually run eslint _twice_ during the pipeline (the second time in [`ci-frontend-stats`](https://github.com/grafana/grafana/blob/main/scripts/ci-frontend-metrics.sh#L15) so moving this check to betterer should actually make the pipeline run quicker.

**Comment by tleopold** [comment] 2022-11-02 15:53
Duplicate of [Feature: Add drone caching#40746](https://github.com/grafana/grafana/issues/40746)

**Closed by tleopold** 2022-11-02 15:53 UTC
Labels: type/chore
