### ISSUE TITLE
FR: Alerting Contact Point Matrix

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#82764] opened 2024-02-15 19:44 UTC
### Discussed in https://github.com/grafana/grafana/discussions/65352

<div type='discussions-op-text'>

<sup>Originally posted by **Chaostheorie** March 27, 2023</sup>
Hi, thank you for your work on Grafana. The alerting module is an awesome however I'd like to request/ add a new contact point for interfacing with [Matrix](https://matrix.org/) servers.

One of the reasons for wanting this in addition to the existing services is the ability to self-host the Matrix Server and as such, among other elements, isolate notifications from third-parties. There are other advantages too, like the various security elements of the Matrix protocol or the ability to create more contact points on a self-hosted server compared to some hosted/ SaaS alternatives.

This would, regarding implementation, look similar to the Telegram Contact Point. Though a client library, like [mautrix](https://github.com/mautrix/go), will most likely be required.

If this feature aligns with the plans for Grafana Alerting, then I would try to contribute it myself.</div>

**Comment by armandgrillet** [comment] 2024-03-27 10:16
Dupe of https://github.com/grafana/grafana/issues/82764

**Closed by armandgrillet** 2024-03-27 10:16 UTC
Labels: type/feature-request, area/alerting, migrated-discussions

**Comment by stefan736** [comment] 2024-04-24 13:45
Hey @armandgrillet, looks like you mentioned the issue being a duplicate of its own.
What is the other issue you really meant?

I'm also looking into how the matrix integration could work via setting up as webhook.

**Comment by mkarg** [comment] 2024-06-22 22:12
@armandgrillet Please reopen this issue, as it is not a duplicate. Thanks.

**Comment by Chaostheorie** [comment] 2024-07-09 13:08
This is likely not a duplicate of itself but rather of #19777.
