### ISSUE TITLE
[Feature Request] Hide Alarm Thresholds

### ISSUE THREAD

**Issue by Chris-Hicks** [grafana/grafana#10410] opened 2018-01-03 10:08 UTC
- What Grafana version are you using?
Grafana v5.0.0-pre1 (commit: e480a38)
- What OS are you running grafana on?
Debian

 ## Request
To be able to disable the threshold lines for configured alarms.  The reasoning is mainly cosmetic but there are times when they are confusing.  Particularly when the alarm to for a metric on the right hand Y-axis as the threshold line is drawn against the left hand Y-axis.

Ideally it would be nice to configure alarms to hide/show thresholds and also re-enable manual thresholds whilst alarms are configured.

**Comment by torkelo** [comment] 2018-01-03 10:36
dupe of https://github.com/grafana/grafana/issues/7258

**Closed by torkelo** 2018-01-03 10:36 UTC
