### ISSUE TITLE
Add multiple URLs support for Elasticsearch data source

### ISSUE THREAD

**Issue by KEVISONG** [grafana/grafana#35762] opened 2021-06-15 14:31 UTC
**What would you like to be added**: Add multiple URLs support for Elasticsearch data source.

**Why is this needed**: Currently the Elasticsearch data source only supports one URL like below.

![image](https://user-images.githubusercontent.com/39701004/122070427-8b89a700-ce28-11eb-805a-656b2f4b4d29.png)

Elasticsearch usually run as cluster in production environments, which have multiple URLs (one per node)

It would be great if Elasticsearch data source supports entering multiple URLs. It provides redundancy to avoid loss of dashboard data points in the event of single point of failure.

**Comment by marefr** [comment] 2021-06-15 15:54
Duplicate of #8170

**Closed by marefr** 2021-06-15 15:54 UTC
