### ISSUE TITLE
Seperate Template Variables for Rows

### ISSUE THREAD

**Issue by n3k232** [grafana/grafana#11669] opened 2018-04-20 09:45 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.0.4
### What datasource are you using?
InfluxDB
### What OS are you running grafana on?
SLES 12
### What did you do?
I tried to Build a Dynamical Dashboard, where i want to all Services from Multiple Hosts.
i repeat every Row by hostname and in this row i repeat a Panels by Measurement.
### What was the expected result?
i hope to get all services from a Host in a row
### What happened instead?
i get all measurements from all Hosts in a Row
### If related to metric query / data viz:
Variable
$hostname | SELECT Domain1.global_id as fqdn FROM Domain1 WHERE productive = 1
$service | show measurements where HOSTNAME =~ /$hostname$/

Panel Query
SELECT /value|max/ FROM /$service$/ WHERE  "HOSTNAME" =~ /^$hostname$/ AND $timeFilter GROUP BY HOSTNAME

When i select multiple Hosts Windows,Unix etc... i get many empty panels in row with measuremnts which are not releated to the selected Hosts.

So i Suggest it would be great to get aanother template variable for Rows so i can work with multple Hosts and Services.

**Comment by bergquist** [comment] 2018-04-20 13:57
Thank you for taking the time to provide feedback to us. 

Right now we don't think this idea aligns with the current scope/goal of the Project. I'm closing this issue since we want open issues to reflect the current state of the project. It doesn't mean we never considered it. A closed issue can still get attention from other users and be reopened.

**Closed by bergquist** 2018-04-20 13:57 UTC

**Comment by marefr** [comment] 2018-05-04 12:37
Duplicate of #5329
