### ISSUE TITLE
Grafana Line Graph with Bars - Width is not adjustable, single bar is having 2 time series on hover 

### ISSUE THREAD

**Issue by rnachire** [grafana/grafana#25524] opened 2020-06-11 05:29 UTC
Grafana Line Graph with Bars - Width is not adjustable, single bar is having 2 time series on hover 

we are using 7.0.0 grafana with prometheus

we have a requirement to get the count of Instances run in every 1hour by aggregating from Prometheus..

So, I made a step interval as a variable which is matching with query range time window and query is count(count_over_time(workflow_activity_instance_duration[$throughput_duration]) ) 

![image](https://user-images.githubusercontent.com/23050574/84348225-0eeb3980-abd2-11ea-9d4b-c27e56ed8a43.png)

Here, each bar width is too large so, each bar is having 2 time series on hover w.r.t time.. but we need single point with bar for every 1hour(which is variable)

So, how do we adjust the width of bar and also how represent the value on top of it.. as unless we hover we can't see the exact value.

Please refer the attached snapshot above

**Comment by torkelo** [comment] 2020-06-11 06:53
not sure I understand, can you show the raw results of your query? The results look correct, the bar width cannot be exactly 1h as that would mean no space between bars. 

> each bar is having 2 time series on hover w.r.t time.

I think this is caused by the all series tooltip mode, change it to single and it should only show one data point when hovering over the bar 

![Screenshot from 2020-06-11 08-52-03](https://user-images.githubusercontent.com/10999/84354301-ec9cf000-abc0-11ea-9a86-b98bc5992fcc.png)

Duplicate of https://github.com/grafana/grafana/issues/22611

**Closed by torkelo** 2020-06-11 06:53 UTC

**Comment by rnachire** [comment] 2020-06-11 08:27
Why can't we have single line bar instead of too much width which is
confusing
