### ISSUE TITLE
ApplicationInsights analytics integration fails in Grafana 11

### ISSUE THREAD

**Issue by sasa-gojic** [grafana/grafana#88438] opened 2024-05-29 15:29 UTC
### What happened?

When upgrading to Grafana 11 and ApplicationInsightsConnectionString is set, every page throws an error to the console
![image](https://github.com/grafana/grafana/assets/64943245/8d87fc44-f670-49fb-a6a6-b5aeb6162d02)

![image](https://github.com/grafana/grafana/assets/64943245/82dda2dc-7bfe-4dba-8b76-fa60fa13e626)

### What did you expect to happen?

Version 10 worked without issue

### Did this work before?

Version 10 worked without issue

### How do we reproduce it?

1. Set Application Insights Connection String, we use env GF_ANALYTICS_APPLICATION_INSIGHTS_CONNECTION_STRING
2. Upgrade to use Grafana 11 

### Environment (with versions)?

Grafana: v11.0.0
OS:
Browser:

### Grafana platform?

Docker

**Comment by thanissi** [comment] 2024-05-30 22:26
We have the same issue. Can we get this fix asap?

**Comment by thanissi** [comment] 2024-06-02 22:39
Hi @iwysiu sorry to reach out to you directly on this but can you help prioritise this? We believe it is a bug and we are unable to use Azure AppInsights feature.

**Comment by DonatoD** [comment] 2024-06-03 13:37
I have the same problem with htmlgraphics plugin https://github.com/gapitio/gapit-htmlgraphics-panel/issues/190. With grafana 11 external scripts stop working

**Comment by sasa-gojic** [comment] 2024-06-04 04:00
@iwysiu 
I'm not sure this issue is related to the azure data source, It is affecting the usage analytics feature,
https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/#application_insights_connection_string

**Comment by DonatoD** [comment] 2024-06-04 07:49
I'm not using azure, but the described problem seems the same

**Comment by sasa-gojic** [comment] 2024-06-04 08:52
@DonatoD I also believe our issues are the same. I suspect the issue is with any library that is dependant on the global window context.

**Comment by DonatoD** [comment] 2024-06-04 09:15
I'm not able to fix it and I hope in a quick feedback since I cannot update grafana at the moment but I have to :-(

**Comment by adamyeats** [comment] 2024-06-12 08:38
Assigning to @grafana/grafana-frontend-platform as this seems to be an issue with the `loadScript` function used in `public/app/core/services/echo/backends/analytics/ApplicationInsightsBackend.ts`, rather than anything to do with the Azure Monitor datasource. @grafana/grafana-frontend-platform team: please feel free to pass back to us if that turns out to not be the case! 👍

**Comment by jackw** [comment] 2024-06-12 09:25
Having spent a little time looking at this I have a feeling the issue is that script is UMD and is now falling into SystemJS define function which treats it as a module rather than a global script. I can see the following options available to us to solve this:

1. Load the current script with `System.import` and execute it.
2. Move to the [v3 version of the azure script](https://js.monitor.azure.com/scripts/b/ai.3.gbl.min.js) which creates global namespaces and isn't UMD.
3. Move the script into the bundle with npm package [`@microsoft/applicationinsights-web`](https://www.npmjs.com/package/@microsoft/applicationinsights-web) and dynamically load it based on config.

**Comment by sasa-gojic** [comment] 2024-06-13 00:41
Hi @jackw and @joshhunt 

I also had a similar follow up question for loading external libraries for custom plugins. Especially older libraries that are dependant on the global namespace.

Is option 1 the recommended approach or should those continue to work as expected?

**Comment by jackw** [comment] 2024-06-13 15:46
> @jackw What would have stopped this from working recently though? Is this related to a SystemJS upgrade we did?

Yes, SystemJS places a `define` function on the window now. This in turn means that any UMD library that previously would have loaded using a global factory method is now finding the `define` function and assuming the code is being loaded by a module loader like RequireJS. I imagine this would have broken in older versions of Grafana if a user had loaded monaco which used to use RequireJS first then navigated to a dashboard that would have loaded an external script. 

>Just trying to figure how to resolve this for scripts others are loading (for whatever reason #88453 )

Ah I some how missed that issue and commented on [another related issue here](https://github.com/gapitio/gapit-htmlgraphics-panel/issues/190#issuecomment-2162898506).

**Closed** 2024-06-17 15:19 UTC
Labels: area/frontend
