### ISSUE TITLE
Playlist randomly stops

### ISSUE THREAD

**Issue by geekiehiway** [grafana/grafana#20429] opened 2019-11-16 14:08 UTC
I created a playlist with 8 graphs. After starting the playlist, it stops after about four graphs and it notifies me of unsaved changed and asks if I want to save or discard.

**Environment**:
- Grafana version: v6.2.5
- User OS & Browser: 3.19.0-32-generic #37~14.04.1-Ubuntu SMP i686 athlon Firefox

**Comment by torkelo** [comment] 2019-11-17 09:22
Temp workaround: 

Fix it by saving the dashboard, it probably has schema upgrades (or panel models changes) that are causing the unsaved changes warning

**Comment by geekiehiway** [comment] 2019-11-17 11:45
Saving it did not help, but it does cycle through completely and stops by the end the second cycle.

**Comment by grtfou** [comment] 2021-07-26 00:56
I have same problem. 

Environment:
  * Grafana version: v7.5.3
  * Browser: Chrome 91.0.4472  and  Firefox 90.0

**Comment by jeremybanzhaf** [comment] 2024-02-26 09:10
seems fixed as of (at latest) 9.5.2

**Comment by gelicia** [comment] 2024-02-28 17:16
This seems to be fixed. Closing issue. Feel free to make a new issue or reopen this one if it is reproducible in a later version of Grafana.

**Closed by gelicia** 2024-02-28 17:16 UTC
Labels: type/bug, help wanted, area/playlist
