### ISSUE TITLE
Add support for variables in axes Y-Min & Y-Max

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#6477] opened 2016-11-05 23:10 UTC
* **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 3.1.1
- What datasource are you using? Graphite
- What OS are you running grafana on? Red Hat Enterprise Linux Server release 6.8
- What did you do?  Entered "$variable" in axis Y-Max ($variable was a "custom" type)
- What was the expected result?  The graph should scale to the number of $variable 
- What happened instead? $variable was ignored

![image](https://cloud.githubusercontent.com/assets/12067107/20034162/45ebef72-a38b-11e6-95c9-a66ccbd661ed.png)

![image](https://cloud.githubusercontent.com/assets/12067107/20034166/714c5472-a38b-11e6-97fb-3178244627f5.png)

**Comment by torkelo** [comment] 2016-11-07 10:12
dupe of https://github.com/grafana/grafana/issues/3935

**Closed by torkelo** 2016-11-07 10:12 UTC

**Comment by sgokulakannan** [comment] 2017-05-01 18:25
Is this done ?

**Comment by daniellee** [comment] 2017-05-02 11:39
@sgokulakannan no. Check the duplicate issue #3935 for the latest.
