### ISSUE TITLE
Explore UI: Variable to Configure Default Time Range

### ISSUE THREAD

**Issue by tonyswu** [grafana/grafana#77764] opened 2023-11-07 00:15 UTC
**Why is this needed**:

In the Explore UI the default time range used to be 1 hour (version 9.*). Since upgrading to version 10.2 the default time range became 6 hours, and there doesn't seem to be a way to change it.

<img width="1698" alt="Screenshot 2023-11-06 at 1 14 53 PM" src="https://github.com/grafana/grafana/assets/5482178/fcd1653e-ee71-4ade-a026-72d4816b43d8">

**What would you like to be added**:

A variable that can be used to configure the default time range in the Explore UI.

**Comment by chrisdewar** [comment] 2023-11-21 23:27
Not sure if this has been raised already but this is a feature that is sorely needed...

**Comment by waddles** [comment] 2023-11-21 23:39
Exploring 6 hours of Loki data by accident often leads to OOMKills of the Loki pods. This really needs to be configurable.

**Comment by flashmann** [comment] 2023-11-29 09:00
really surprised to see that this is not yet configurable, can you please make default Explore time range configurable, would be very appreciated

**Comment by krishnaindani** [comment] 2023-12-01 23:37
We have the use case where we would like to configure it to lower time as well since some of the prometheus datasource are so big leading it to memory issues.

**Comment by owanio1992** [comment] 2023-12-27 07:33
very need this feature 
time range default 6hr is too large

**Comment by yosiasz** [comment] 2024-01-01 18:01
This does not seem like a feature  change request but a regression bug?

**Comment by aryalireza** [comment] 2024-01-06 14:53
It would be very nice if we could change the default interval of the explore to some valid values.
I think this feature is really necessary

**Comment by gelicia** [comment] 2024-01-29 20:21
The original bug, where the default was set to 6h instead of 1h, was fixed in #81135

I have moved this feature request to the right team so it can be prioritized.

**Comment by welyss** [comment] 2024-03-25 05:04
hope to be customized, everyone maybe different

**Comment by bobnecat** [comment] 2024-04-24 00:30
Guys! It's now April 2024 and this is still an open topic!? 
How is this not an option to set default time range? Everyone has different needs; for some 1 hour would work for others 30 days default is needed, considering grafana can show both and more.
It seems like a pretty straightforward implementation (just like update interval options) yet persistently ignored and instead the time defaults are "fixed"? How is this even a fix when it only fits one's preference but not the others?

**Comment by aljoshare** [comment] 2024-06-14 11:56
🙏

**Closed** 2024-07-17 16:47 UTC
Labels: type/feature-request, area/explore

**Comment by pnishimoto** [comment] 2025-02-26 09:38
Any news about including an option to set default time range? Maybe a general option and also a possibility of changing it for each dashboard? It would be so helpful...
