### ISSUE TITLE
Dashboard init failed (upgrade from 7 to 8)

### ISSUE THREAD

**Issue by davidgiga1993** [grafana/grafana#35404] opened 2021-06-09 08:41 UTC
**What happened**:
When loading my main dashboard grafana failes with `Dashboard init failed` and the following stacktrace
```
TypeError: e.changePlugin is not a function
    at DashboardMigrator.ts:896
    at v.<anonymous> (DashboardMigrator.ts:580)
    at v.updateSchema (DashboardMigrator.ts:633)
    at D.updateSchema (DashboardModel.ts:993)
    at new D (DashboardModel.ts:156)
    at initDashboard.ts:134
```

**What you expected to happen**:
It should just work

**How to reproduce it (as minimally and precisely as possible)**:
Not sure yet, it only happes for this single dashboard. I can't export the json and dump it here since the edit button is not showing up in this case.

**Anything else we need to know?**:
Is there a way to still export the json of the dashboard?

**Environment**:
- Grafana version: 8 (latest docker image)
- Data source type & version: Prometheus
- OS Grafana is installed on: RedHat (openshift 3.11)
- User OS & Browser: Windows 10 + Chrome (latest)
- Grafana plugins: core + Diagram

**Comment by zoltanbedi** [comment] 2021-06-09 08:52
duplicate of #34788

**Closed by zoltanbedi** 2021-06-09 08:52 UTC
