### ISSUE TITLE
Error Display with Graph panel bars display mode

### ISSUE THREAD

**Issue by poxiao-fly** [grafana/grafana#27084] opened 2020-08-20 06:12 UTC
**What happened**:
When there is just one data point, if i use Graph panel and bars display mode to show the data  it will be a huge rectangular across all time series.
Error histogram plot:
![image](https://user-images.githubusercontent.com/12975248/90722785-0f98fe00-e2ee-11ea-89de-96b6af8ea346.png)
Data:
![image](https://user-images.githubusercontent.com/12975248/90723293-107e5f80-e2ef-11ea-841f-b6e450ede87d.png)

**What you expected to happen**:
Just show a normal histogram plot with one data point.

**How to reproduce it (as minimally and precisely as possible)**:
1. DataSource: Azure Monitor;
2. Service: Application Insights
3. Ensure the all time span has just one data record.
4. Use Graph panel -> Bars Display Mode and X-Axis mode is time.
**Anything else we need to know?**:
I think it's not just the issuse in Azure Monitor data source.
**Environment**:
- Grafana version: v7.1.1
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Azure Linux VM
- User OS & Browser: Windows10 2004 & Chrome 84.0.4147.125
- Grafana plugins:  Graph
- Others:

**Comment by torkelo** [comment] 2020-08-20 07:41
duplicate of https://github.com/grafana/grafana/issues/14130

**Closed by torkelo** 2020-08-20 07:41 UTC
