### ISSUE TITLE
please enhance (single)stat panel contents sizing/alignment options

### ISSUE THREAD

**Issue by devZer0** [grafana/grafana#25630] opened 2020-06-16 12:17 UTC
Hello, 
could you please enhance that panel for more flexibilty in arranging the contents inside?

i try to add some singlestat panels to my dashboard and having a hard time to make it look pretty.

to be honest - it really sucks. 

there is too much room wasted inside and resizing the panel behaves "un-intuitive",  i.e. the spacing between labels/data should be configurable and behave to user expectation.

for example, if i reduce horizontal size of the Testpanel2 (copy of Testpanel), i would expect the free space between label and data reduces, but it is also reducing text in size way too early , which makes it look pretty ugly and wasting precious space on screen when your screen is limited and you have a lot of single(stat) panels. 
i would expect the free space to shrink BEFORE the text being shrinked.

<img width="355" alt="grafik" src="https://user-images.githubusercontent.com/3506105/84772878-d84f5d80-afdb-11ea-96f0-39fb8d9fd442.png">

**Comment by sakjur** [comment] 2020-06-16 12:46
As you noticed, this is a duplicate of an already existing issue (or rather, I'd consider this to be a duplicate of either of two other issues). We'll use those for tracking this request.

Duplicate of #23305 
Duplicate of #22209

**Closed by sakjur** 2020-06-16 12:46 UTC
