### ISSUE TITLE
Enhancement: multi-day graph time-range

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#9454] opened 2017-10-06 18:37 UTC
On a multi-day graph, > 24 hours covered, I would like to be able to select a time-range that should be applied to each of the days.  So for example I would like to be able to compare the 9-10am hour across 5 days.

As a proposal on the time-range selector on the top of the dashboard, if more than 24 hours is displayed it would be nice to have an option to show just a selected window of time for each day.

**Comment by shalstea** [comment] 2017-10-06 18:44
![capture](https://user-images.githubusercontent.com/10222648/31293317-cc90e764-aaa4-11e7-9a60-f3c670fb6508.PNG)

The above is a screen snapshot of a graph that covers 10-12am across 4 days.

**Comment by torkelo** [comment] 2017-10-07 20:11
duplicate of https://github.com/grafana/grafana/issues/5930

**Closed by torkelo** 2017-10-07 20:11 UTC
