### ISSUE TITLE
[Bug] Get 1ms as minimum time interval

### ISSUE THREAD

**Issue by bloomz** [grafana/grafana#8018] opened 2017-04-03 14:40 UTC
Please include this information:
- What Grafana version are you using : grafana-4.2.0
- What datasource are you using : InfluxDB
- What OS are you running grafana on : RHEL 7
- What did you do : zoom on a time window of 200 ms
- What was the expected result: an expected time interval of 1 ms.
- What happened instead: the minimum time interval is of 10 ms

The minimum possible time interval is 1ms. Nevertheless the minimum displayed time interval is 10 ms. 
From my unexperimented analysis, it seems to come from interval rounding in interval.go, Maybe adding in roundInterval function the cases where interval are < 1.5 ms (and <2ms ,< 5 ms) could help.
(furthermore setting interval through templating variable did not provide the "new" $__interval_ms needed)

**Comment by torkelo** [comment] 2017-04-03 14:46
thanks for reporting this. 

Closing as it's a duplicate of this feature request:
https://github.com/grafana/grafana/issues/7533

**Closed by torkelo** 2017-04-03 14:46 UTC
