### ISSUE TITLE
Create playlist within a panel

### ISSUE THREAD

**Issue by arsibaba** [grafana/grafana#4043] opened 2016-02-16 07:09 UTC
I've been playing with the Grafana playlist feature but what would be even more useful is if I had the ability to swap between multiple graphs on the same dashboard. My use case is the following:

I have aggregated KPIs that I observe in my top panel (2 graphs).
These KPIs can be drilled down by multiple values, each one being important to me. However, this would cause me to create 8 additional graphs. If I had the ability to show my aggregates in my top panel and use the panel right below to swap through multiple graphs in a playlist (or any other way), I would be able to display a lot more information to our users.

Just leaving this here in case anyone else is interested or if it can get some traction.

**Comment by bergquist** [comment] 2016-12-21 22:43
Closing. Dupe of https://github.com/grafana/grafana/issues/4043

**Closed by bergquist** 2016-12-21 22:43 UTC
Labels: type: feature request
