### ISSUE TITLE
label_values function for prometheus can use "/api/v1/label/label/values" instead of "/api/v1/series" API ?

### ISSUE THREAD

**Issue by chenlujjj** [grafana/grafana#43005] opened 2021-12-11 15:00 UTC
### Discussed in https://github.com/grafana/grafana/discussions/43001

<div type='discussions-op-text'>

<sup>Originally posted by **chenlujjj** December 11, 2021</sup>
In some of our use cases, `label_values(metric, label)` function returns response very slowly (more than 10 seconds). We find out that it calls prometheus `/api/v1/series API` and the response body size is about 150MB. 

I'm wondering if grafana can use `/api/v1/label/label/values` instead since it is faster and response body is much smaller? Prometheus has provided `match[]=<series_selector>` parameter for this API since version 2.24.  </div>

**Comment by aocenas** [comment] 2021-12-13 19:18
Duplicate of https://github.com/grafana/grafana/issues/33487

**Closed by aocenas** 2021-12-13 19:18 UTC
Labels: type/feature-request, datasource/Prometheus
