### ISSUE TITLE
Dashboards: cannot move scrollbar in logs panel using Chrome

### ISSUE THREAD

**Issue by Estrax** [grafana/grafana#24569] opened 2020-05-12 08:33 UTC
**What happened**:

When running logs query in dashboards I can't move the scrollbar in the logs panel in Chromium-powered browsers. Works properly in Firefox.

**What you expected to happen**:

Logs panel working properly with an ability to move scrollbars.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open Grafana
2. Create new dashboard
3. Add new panel
4. Set the panel visualization to Logs
5. Use a logs datasource (Loki, Elasticsearch logs)
6. Write a query to display data with long log messages (for Loki under linux, usually `{job="varlogs"}` should do the job)
7. Try to move the scrollbar.

**Comment by ivanahuckova** [comment] 2020-05-15 14:46
@Estrax I wasn't able to reproduce this issue on MacOS + Chrome. Scrolling in Logs Panel worked for me.
![Kapture 2020-05-15 at 16 45 03](https://user-images.githubusercontent.com/30407135/82063217-80b38e80-96cb-11ea-931d-22f3b49dc0e6.gif)

**Comment by Estrax** [comment] 2020-05-15 14:50
@ivanahuckova Thanks for checking!

Not sure if that's also the case on Windows - so far we have at least 2 cases confirming that bug on Linux. (me & @bergquist, who originally reported that on slack)

**Comment by torkelo** [comment] 2020-05-18 15:39
This was due to the LogRows has the wrong style! Fixed by removing the overflow: scroll here https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Logs/getLogRowStyles.ts#L64 

Then it works great in dashboard panel. But scroll won't work in Explore probably. I suggest moving the CustomScrollbar from the LogsPanel and into the LogRows component so that it's used in both scenarios (Explore & Panel)

**Comment by ivanahuckova** [comment] 2020-05-18 15:49
@torkelo that scroll styling is there due to the wrap lines functionality. If we remove it, un-wrapped version doesn't work. However, this is causing also another problem (in context). So we probably need to fix/rework horizontal scroll in a way, that it doesn't affect scroll and context.

**Closed** 2020-05-20 09:20 UTC
Labels: area/dashboard, area/frontend, area/panel/logs, type/bug
