### ISSUE TITLE
Allow default values while provisioning dashbaords

### ISSUE THREAD

**Issue by gerardo8a** [grafana/grafana#22551] opened 2020-03-03 20:17 UTC
With previous grafana I use to use a watcher that injected the dashboards and update them. For this to work I used the template like this:

```
{
  "overwrite": true,
  "inputs": [
    {
      "value": "prometheus",
      "type": "datasource",
      "pluginId": "prometheus",
      "name": "DS_PROMETHEUS"
    }
  ],
  "dashboard": {
    "__inputs": [
      {
        "name": "DS_PROMETHEUS",
        "label": "prometheus",
        "description": "",
        "type": "datasource",
        "pluginId": "prometheus",
        "pluginName": "Prometheus"
      }
    ],
```

Now that grafana takes care of reloading the dashboards this does not work, I have only to include whatever is inside the "dashboard" section, but because the default values is not included the dashboard will not because the datasource is not defined/set. 

I've been reading and most people just replace the     `"datasource": "${DS_PROMETHEUS}"` section with the default. But is there a wat that I can feed my current templated dashboard to grafana and set the defaults for grafana to just load the dashboard? 

This is the grafana error when I try to access the dashboard that was placed in the grafana dashboard directory

```
"Templating init failed
Datasource named ${DS_PROMETHEUS} was not found"
```

**Comment by torkelo** [comment] 2020-03-04 12:34
duplicate of https://github.com/grafana/grafana/issues/10786

**Closed by torkelo** 2020-03-04 12:34 UTC
