### ISSUE TITLE
StateTimeline: support paging, sort and column filter

### ISSUE THREAD

**Issue by Betula-L** [grafana/grafana#36209] opened 2021-06-28 10:42 UTC
**Why is this component needed**:

If too many time series, we totally can not use state timeline now. As shown below, we can not get an avaiable picture because all timeline is mixed in a tiny panel.

![图片](https://user-images.githubusercontent.com/6059935/123623428-00ed7280-d840-11eb-9961-88ded702772a.png)

**Where is/could it be used?**:
We use it when time series large than 20.

**Implementation**
Maybe we can introduce paging, sorting and column filter as table.

**Comment by leeoniya** [comment] 2021-06-28 12:38
Duplicate of https://github.com/grafana/grafana/issues/35843

**Closed by leeoniya** 2021-06-28 12:38 UTC
Labels: area/grafana/ui
