### ISSUE TITLE
Opentsdb incorrect alias when using duplicate metric queries with different tags

### ISSUE THREAD

**Issue by mdehus** [grafana/grafana#5377] opened 2016-06-16 16:20 UTC
* **I'm submitting a ...**
- [X] Bug report
- [ ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
3.0.4

- What datasource are you using?
OpenTSDB

- What OS are you running grafana on?
CentOS7

- What did you do?
Create multiple metric queries using the same metric name, but with different tags and assigned aliases to each query.

- What was the expected result?
Each query would have the appropriate alias assigned to it.

- What happened instead?
All queries with the same metric names have the same aliases.

![screen shot 2016-06-16 at 10 07 25](https://cloud.githubusercontent.com/assets/1952447/16124274/8a19cd22-33ab-11e6-9d32-d409e34a68d0.png)

**Comment by torkelo** [comment] 2016-06-16 16:31
Please search before :) OpenTSDB alias has a bunch of closed issues :) 

They all relate to a problem in OpenTSDB that makes it impossible for Grafana to know which series came from which query. 


Dupe of 
https://github.com/grafana/grafana/issues/2687
https://github.com/grafana/grafana/issues/3108
https://github.com/grafana/grafana/issues/1915
https://github.com/grafana/grafana/issues/1876


Fixed in OpenTSDB 2.3 and Grafana 3.1 (master)

**Closed by torkelo** 2016-06-16 16:31 UTC
