### ISSUE TITLE
[Feature request] Please hide datasource's password in edit section.

### ISSUE THREAD

**Issue by Demengjkee** [grafana/grafana#8580] opened 2017-06-09 13:32 UTC
Hi, 

When editing data source configured via username/password password is written in plain text form in `<input type="password">` so if you change type to `text` via browser's developer tools, you can easily acquire password as it can be seen on screenshots below:
![image](https://user-images.githubusercontent.com/10945476/26977156-86c19ee0-4d2f-11e7-8ffc-5bca4598e819.png)
![image](https://user-images.githubusercontent.com/10945476/26977177-9606a4c2-4d2f-11e7-919f-6841753d762c.png)

I suggest encoding password or using some hash before printing it. 

Details:
- What Grafana version are you using? - Grafana 4.3.2
- What datasource are you using? - Affects all datasources, InfluxDB config is shown on screenshots
- What OS are you running grafana on? - Docker hosted on CentOS 7.3
- What did you do? - changed input's type via browser developer tools
- What was the expected result? - I should be unable to see password
- What happened instead? - I see password

**Comment by torkelo** [comment] 2017-06-09 13:40
duplicate of https://github.com/grafana/grafana/issues/2557

**Closed by torkelo** 2017-06-09 13:40 UTC
