### ISSUE TITLE
[BUG] Table - ERROR: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by baur** [grafana/grafana#21954] opened 2020-02-06 03:35 UTC
**What happened**:

![image](https://user-images.githubusercontent.com/2898361/73903498-7eb78380-48c3-11ea-9d00-dac91bdb915a.png)

**What you expected to happen**:
no error

**How to reproduce it (as minimally and precisely as possible)**:
Just set Thresholds to Table panel and Color Mode = Cell || Value || Row 

![image](https://user-images.githubusercontent.com/2898361/73903718-01404300-48c4-11ea-81c6-4d84e7f32cc9.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: **6.6.0**
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Windows 2016
- User OS & Browser: Windows10, Chrome
- Grafana plugins: Table
- Others:

**Comment by baur** [comment] 2020-02-06 03:38
Looks like as #16094

**Comment by peterholmberg** [comment] 2020-02-06 08:03
duplicate of https://github.com/grafana/grafana/issues/16094

**Closed by peterholmberg** 2020-02-06 08:03 UTC
Labels: type/bug
