### ISSUE TITLE
Custom time ranges aren't saved

### ISSUE THREAD

**Issue by smurfix** [grafana/grafana#54940] opened 2022-09-09 07:00 UTC
**What happened**:

Entering a custom absolute time range in the Time Series panel doesn't save that range.

**What you expected to happen**:

The "It looks like you haven't used this time picker before." messag goes away and is replaced with my custom range(s).

**How to reproduce it**:

- clear local storage, reload page
- open time series viewer.
- open time drop-down
- observe the above text
- enter a time range, e.g. "now-12h" to "now+2h", and click "Apply time range"
- observe the graph changing as expected
- open time drop-down again
- **still** observe the above text

**Anything else we need to know?**:

**Environment**:
- Grafana version: OSS 9.1.3
- Data source type & version: any
- OS Grafana is installed on: Linux, Debian 11
- User OS & Browser: Firefox, current
- Grafana plugins: ./.
- Others:

![Screenshot from 2022-09-09 08-55-44](https://user-images.githubusercontent.com/236571/189290761-f773e23e-5ec8-4bdf-aada-b4c132cbd4a0.png)

**Comment by ivanahuckova** [comment] 2022-09-09 14:49
I was able to reproduce this as well. To reproduce, clear you local storage and follow the steps above.

**Comment by supilee** [comment] 2022-09-15 03:18
reproducible in 9.1.5

**Comment by smurfix** [comment] 2022-09-15 08:43
> To reproduce, clear you local storage

I added this to the "how-to-reproduce" steps.

**Comment by supilee** [comment] 2022-09-16 13:35
@smurfix i know. happens also without clearing the storage.

**Comment by supilee** [comment] 2022-09-16 14:25
@smurfix can you please try the following:
Instead of enter a time range, e.g. "now-12h" to "now+2h", double click the date and then click "Apply time range".
It's a workaround only but i would like to know how this behaves for you with 9.1.5, OS and browser
at least.

![Image](https://user-images.githubusercontent.com/110845248/190662122-8fbaeda2-63cf-4c95-ba98-aa455865062f.png)

This i my environment:
Grafana version: OSS 9.1.5
Data source type & version: any
OS Grafana is installed on: MacOSX Monterey 12.6
User OS & Browser: Chrome

**Comment by smurfix** [comment] 2022-09-16 15:15
Yes, with that trick I managed to save some range in February.

To be helpful, what I'd really like to see instead of (and/or in addition to) this issue is getting https://github.com/grafana/grafana/issues/2417 implemented. Can't be that difficult. (Famous last words, I know. 😀)

**Comment by supilee** [comment] 2022-09-22 14:26
thanks @smurfix .We will look into it ..

**Comment by joshhunt** [comment] 2022-12-05 12:22
I don't believe there is a bug here. 

Time range picker will only save absolute time ranges - this was an [explicit design decision](https://github.com/grafana/grafana/pull/20931/files#diff-af9e998cda26a9c654543f8cc59c9879d398d18e4e442eb90d8321cecd0abf17R29).

**Comment by ivanahuckova** [comment] 2022-12-05 13:50
Not anymore. I am pretty sure/think that I've tried it in the past with absolute time ranges as well and it wasn't working. But I am not able to reproduce this anymore. I even tested with version 9.1.3 and it works as expected. So I think you can close the issue.

**Closed** 2022-12-05 15:36 UTC
Labels: timepicker
