### ISSUE TITLE
FR: Show refresh button even if time picker was hided

### ISSUE THREAD

**Issue by baur** [grafana/grafana#26190] opened 2020-07-09 06:26 UTC
**What would you like to be added**:

Please, stay refresh button even if time picker was hided or hide it with another way

![image](https://user-images.githubusercontent.com/2898361/87004294-07be4800-c1df-11ea-97a3-00986692c1d0.png)

**Why is this needed**:

Refresh dashboard not related with time picker at all

**Comment by torkelo** [comment] 2020-07-10 05:10
duplicate of https://github.com/grafana/grafana/issues/11782

**Closed by torkelo** 2020-07-10 05:10 UTC
