### ISSUE TITLE
Alerting: Any change to a rule always increments version and resets state for all other rules in the same group

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#64256] opened 2023-03-06 18:20 UTC
**What happened**:

Updating a single rule definition should increment that rule's version. There are a few cases where it should increment the version of all rules in the group too, i.e. when the group's evaluation interval is changed.

However, right now, it seems **any** change to a rule causes versions to be needlessly bumped for the entire group. The result is, any time you change a rule, all the other rules in the group get rescheduled and their states get reset. Any firing rules are reset to normal and have to go through another pending cycle.

Furthermore, Prometheus also - it maintains state for other rules in the same group correctly, as long as the change doesn't affect a property at the group level.

**What you expected to happen**:

I expected only the version for the touched rule to be incremented for changes that do not affect the group at large. As a result, I expected other rules to not have their states reset (and extra notifications sent) when making a seemingly orthogonal change.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a rule group containing multiple always-firing rules.
2. Make a localized change to just one of the rules. Update the value of an annotation or something.
3. Go back to the alert rule panel.
4. Note that **all rules** in the group have their states reset to normal, not just the one that got updated.
5. Open the network tab and observe the `/rules?subtype=cortex` request containing the rule definitions. Note that the version incremented by one for the other rules in the group, not just the one you changed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by alexweav** [comment] 2023-03-06 19:56
I've narrowed things down a bit. The bug is in this function:
https://github.com/grafana/grafana/blob/10476043ea1b31402e150d0436ea8df884d9b9a3/pkg/services/ngalert/store/deltas.go#L131

When we originally perform the diff, the results are correct. Then, after updating calculated fields (specifically the rule group index) is when the erroneus updates to other rules happen. This is a bug, as the rule group index did not change. The rules were not re-ordered.

**Comment by alexweav** [comment] 2023-03-06 20:12
Found a fix, creating a test...

**Comment by alexweav** [comment] 2023-03-06 21:03
Other option is to fix it at state management level: https://github.com/grafana/grafana/blob/4f3d64e8b7174bfb98da6c1d5004d203c3aea8ae/pkg/services/ngalert/schedule/schedule.go#L472

I.e. when a version gets updated, if the rule still matches then keep the state.

**Comment by yuri-tceretian** [comment] 2023-03-06 21:09
That is done intentionally to make sure about the consistency of the group and prevent concurrent updates of rules in the same group. Related to https://github.com/grafana/grafana/issues/48353

The consequences of this behavior were expected. I agree that we can better reset the state and resolve notifications. However, this should be done in state management instead of API: state management logic should be able to detect whether two versions of a rule are the same (or produce the same state).

**Comment by empollard** [comment] 2023-03-14 19:55
Hi Team!
Any news on this? Customer is asking for an update because they're blocked in migrating their alerts until this is fixed.

Thanks!

**Comment by yuri-tceretian** [comment] 2023-03-15 16:42
I think I would go with "other option" Alex suggested in the comment above. The problem is that there is nothing to compare with, i.e. there is no previous rule in the state but only the rule version in the rule evaluation routine. 

The idea is that rule states contain a unique fingerprint (a hash) created when the rule state is calculated. In the general case, this can be a hash of the structure excluding the version field but including the _folder name_ because it is part of the labels, and therefore part of the unique state fingerprint (cacheID). That hash can be stored in the rule evaluation routine but I would prefer it be in the state manager. 
However, I think the best way forward is if that fingerprint can include __only__ fields that are used to calculate state's labels, which are: rule UID, Title, folder UID, folder Name (depending on the settings), data query, and labels. Other fields such as annotations, interval, and `for` interval, group, and group_index do not affect the calculation of the state. At least for now. 

Ideally, it can replace the version field which is used for optimistic concurrency in the database. The side effect of that replacement is that we will let users avoid needless resetting of state when they change rule fields that do not affect the state (changing interval or for).

**Comment by empollard** [comment] 2023-03-16 13:51
Hey Yuri,
Thanks for that info and for creating the PR. I've let the customer know we've determined how to move forward. Any thoughts on what version we might see this in?

**Comment by yuri-tceretian** [comment] 2023-04-05 14:36
Yes, yesterday we met and decided to implement proposal https://github.com/grafana/grafana/issues/64843. Unfortunately, this will not land in 9.5.0. Most likely the next patch release.

**Comment by yuri-tceretian** [comment] 2023-04-28 15:17
Fixed in https://github.com/grafana/grafana/pull/66531 backported to 9.5.x, and will be released in 9.5.2

**Closed** 2023-04-28 15:22 UTC
Labels: type/bug, area/alerting, area/backend
