### ISSUE TITLE
PublicDashboards: Library Panels will not load in Public Dashboards in v9.2.7+

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#59771] opened 2022-12-04 20:16 UTC
**What happened**:
After updating from grafana 9.2.6  to v 9.3.1,  any of our public monitors that show dashboards containing "Library Panels" throw an error of "Panel plugin not found: Unable to load library panel: aY7hJID4k"  (last part , the panel ID, ofcouse changes)

this does NOT occur if you are a logged in user, ie logged into grafana and pull up the dashboard.

**its as if there are some new, special permissions related to only Library Panels**  (if this is the case, please let me know where i can modify these permissions, as i looked but could not find this setting in webGUI nor in grafana.ini , nor in the v9.3.1 changelog)

**How to reproduce it (as minimally and precisely as possible)**:
Add a library panel to a dashboard,  choose Share,  then load the Dashboard via that share URL (and be sure to use incognito browser mode so that you are NOT logged in to grafana).

**Anything else we need to know?**:
downgrading back to v 9.2.6 (from 9.3.1) resolved this issue.

**Environment**:
- Grafana version: v9.3.1 (prior was  v9.2.6)
- Data source type & version: Graphite (I dont think this matters though)
- OS Grafana is installed on: Debian
- User OS & Browser:  Chrome , FF (both on Win11)
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/60830628/205513393-1c327d12-df31-480c-8639-e01bb6db4949.png)

**Comment by zuchka** [comment] 2022-12-06 22:31
Thanks for creating this issue, @bob454522 

I see this in the changelog for 9.2.7:

- **LibraryPanels:** Load library panels in the frontend rather than the backend. [#50560](https://github.com/grafana/grafana/pull/50560), [@ryantxu](https://github.com/ryantxu)

perhaps it is related

**Comment by krzd7** [comment] 2022-12-09 23:09
Also having this issue after updating to v9.3.1. Basically, it happens to viewers, they can no longer load panels. As admin I cannot reproduce that.

**Comment by krzd7** [comment] 2022-12-23 22:34
Anyone found a way to fix this without reverting back to v9.2.6?

@torkelo , any idea if #50560 is causing this or how to fix the panels for viewers?

**Comment by bob454522** [comment] 2022-12-24 22:05
> Anyone found a way to fix this without reverting back to v9.2.6?
> 
> @torkelo , any idea if #50560 is causing this or how to fix the panels for viewers?

Im in the same sistuation (and have made a forum post on this as well),  **sorry i cant help, but the only new info i can add, is i wonder if this PR is related to our issue ?
(shows as merged into 9.3.2):
https://github.com/grafana/grafana/pull/59608**

I have not tried 9.3.2 yet, as i dont want to have to revert back from 9.3.x again (i will update my grafana when i see confirmation that this public dashboard panel issue is resolved).

The issue that is concerning to me-  I would think this is a pretty widespread/serious bug, as i assume ALOT of grafana users, use/display public dashboard and thus have broken dashboards as of 9.3.x.
 However, i dont see this issue getting alot of attention from grafana devs.  (which makes me wonder if its something unique to our own grafana use-cases and its in-fact not a widespread issue).

**Comment by krzd7** [comment] 2022-12-26 21:38
More info on this bug:

Create a dashboard and add a Team with "View" only permission. Add a user to that team and login. You'll see the message "Panel plugin not found: Unable to load library panel: XYZ" for each panel.

- If you edit the dashboard and set the team to "Edit", it won't work;
- If you change the user role from "Viewer" to "Editor", it works and you'll be able to load the panels.

Web console report returns a bunch of JSON objects like this:
```
{
  "status": 404,
  "statusText": "Not Found",
  "data": {
    "message": "library element could not be found",
    "traceID": "4a2609677ad8ce5e48563444a83e9033"
  },
  "config": {
    "method": "GET",
    "url": "api/library-elements/xdyCej6Mz",
    "showSuccessAlert": false,
    "showErrorAlert": false,
    "retry": 0,
    "headers": {
      "X-Grafana-Org-Id": 1
    },
    "hideFromInspector": true
  }
}
```

**Comment by timlevett** [comment] 2023-01-04 20:22
This is a duplicate of https://github.com/grafana/grafana/issues/54802

**Closed by timlevett** 2023-01-04 20:22 UTC
Labels: area/frontend/library-panels, type/regression, public-dashboards

**Comment by bob454522** [comment] 2023-01-25 19:33
to update / close out this thread:

**I can confirm that adjusting the permissions does resolve this issue.**  (its not a bug, but rather a change in how Folder Permissions -> Library panels  operate) ** -   see my post here for more info:  https://github.com/grafana/grafana/issues/54802#issuecomment-1404127899
