### ISSUE TITLE
Dashboard: Explore's editor in Prometheus panels crashes browser

### ISSUE THREAD

**Issue by LDaneliukas** [grafana/grafana#18855] opened 2019-09-03 11:20 UTC
**What happened**:
Creating a new panel or editing an existing one which uses the Prometheus datasource will now show the "Explore" editor in the query box after https://github.com/grafana/grafana/commit/4ddeb94f5272ca0eaed355877fb4705aae1db2ec

It seems that this new editor loads all of the series vailable in order to provide suggestions and in an environment with a large number of series, this causes browsers to load up to 5GB of RAM (or even more), resulting in a crashed tab and rendering the Prometheus datasource unusable.

A similar issue was already raised for the Explore UI itself https://github.com/grafana/grafana/issues/14718, however, using Explore UI is or rather was optional, which is no longer the case.

**What you expected to happen**:
Being able to edit / create a panel with the Prometheus datasource.

**How to reproduce it (as minimally and precisely as possible)**:
Edit a panel which is using Prometheus as the datasource whilst having a significant amount of series in the datasource (7.000.000 in our case).

In the described case, opening the API endpoint `/api/v1/label/__name__/values` in your browser (which is now called in the panel edit view) loads ~13GB of memory before crashing.

**Anything else we need to know?**:
This could potentially be enabled by a setting, rather than by default.

**Environment**:
- Grafana version: v6.3.5
- Data source type & version: Prometheus (Thanos)
- OS Grafana is installed on: Docker on Linux
- User OS & Browser: Fedora / Windows, Firefox / Firefox Developer Edition / Chrome

**Comment by torkelo** [comment] 2019-09-03 16:25
dupe of https://github.com/grafana/grafana/issues/18842

**Comment by torkelo** [comment] 2019-09-03 16:25
Sorry for this will fix in an upcoming patch!

**Closed by torkelo** 2019-09-03 16:25 UTC
