### ISSUE TITLE
Tooltip selects wrong point when in mode "all series"

### ISSUE THREAD

**Issue by BobClaerhout** [grafana/grafana#22922] opened 2020-03-20 11:01 UTC
**What happened**:
The tooltip displays wrong data when "hover tooltip mode" is set to "all series". (mind the selcted point in the graph and the wrong timestamp in the tooltip)
![image](https://user-images.githubusercontent.com/3315222/77156439-a8a5bd80-6a9f-11ea-9f42-b9b85943d6b4.png)

**What you expected to happen**:
When I change the "hover tooltip mode" to "single", it selects the correct value. (mind the selected point in the graph)
![image](https://user-images.githubusercontent.com/3315222/77156451-b0656200-6a9f-11ea-9143-c8fa079c62f0.png)

**How to reproduce it (as minimally and precisely as possible)**:
Change the "hover tooltip mode" from "all series" to "single" and vice versa.

**Anything else we need to know?**:
Copy of the query inspector:
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1584699039820",
      "to": "1584699104285",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 1878,
          "datasourceId": 1,
          "rawSql": "SELECT\n  date_trunc('second',time) \"time\",\n  \"customerValue\",\n  \"customName\"\nFROM\n  table\nWHERE\n  time BETWEEN '2020-03-20T10:10:39.82Z' AND '2020-03-20T10:11:44.285Z'\n",
          "format": "time_series"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 0,
          "sql": "SELECT\n  date_trunc('second',time) \"time\",\n  \"customerValue\",\n  \"customName\"\nFROM\n  table\nWHERE\n  time BETWEEN '2020-03-20T10:10:39.82Z' AND '2020-03-20T10:11:44.285Z'\n"
        },
        "series": [
          {
            "name": "70b3d57bb1000053",
            "points": [
              [
                0,
                1584699084000
              ],
              [
                100,
                1584699084000
              ],
              [
                100,
                1584699055000
              ],
              [
                0,
                1584699055000
              ]
            ]
          }
        ],
        "tables": null,
        "dataframes": null
      }
    }
  }
}
```

**Environment**:
- Grafana version: grafana/grafana:6.6.2 (3fa63cfc34) (docker)
- Data source type & version: timescale/timescaledb:1.5.1-pg11-bitnami (docker)
- OS Grafana is installed on: docker
- User OS & Browser: Linux Firefox, Linux Chrome, Windows Chrome, Windows IE(yes we did :)), Windows Edge(and did this as well) and Windows Firefox

**Comment by dprokop** [comment] 2020-03-20 11:02
Possibly related to #22611

**Comment by BobClaerhout** [comment] 2020-03-20 11:50
We don't know whether this is relative to each other but we also noticed something weird when point are being connected:
![image](https://user-images.githubusercontent.com/3315222/77161132-3934cb80-6aa9-11ea-8190-1e5378866e65.png)
However, when we zoom in on this timespan, we notice that the points are connected correct:
![image](https://user-images.githubusercontent.com/3315222/77161197-5d90a800-6aa9-11ea-8459-5c970797cff2.png)
The crossing lines in the first screenshot are not correct.

**Comment by dprokop** [comment] 2020-04-09 19:06
Duplicate of #22611

**Closed by dprokop** 2020-04-09 19:06 UTC
Labels: area/frontend, needs investigation
