### ISSUE TITLE
Grafana not updating direction parameter with loki

### ISSUE THREAD

**Issue by ahmedTouati** [grafana/grafana#46397] opened 2022-03-10 08:18 UTC
When I go to the logs panel and try to download logs, the order I get is descendant (direction=BACKWARD), even when I click on 'Flip results order' direction doesn't switch to FORWARD. 

**What happened**: Click on 'Flip results order'

**What you expected to happen**: direction will switch to 'FORWARD'

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.3
- Data source type & version: loki

**Comment by Elfo404** [comment] 2022-03-10 09:58
Duplicate of #20394

**Closed** 2022-03-10 09:58 UTC
