### ISSUE TITLE
Grafana 8: time series panel stacking issues

### ISSUE THREAD

**Issue by wiz78** [grafana/grafana#36832] opened 2021-07-16 08:05 UTC
I have a "Graph (old)" panel pulling data from postgres to create this:

<img width="990" alt="Schermata 2021-07-16 alle 09 41 55" src="https://user-images.githubusercontent.com/9781798/125911544-f948a63d-1d50-4e53-8a0c-aad884e537c1.png">

If I simply convert the panel to "Time series", I would expect it to remain pretty much the same. However, stacked values are rendered with very thin lines:

<img width="990" alt="Schermata 2021-07-16 alle 09 42 28" src="https://user-images.githubusercontent.com/9781798/125911588-9d4aa665-a952-4ea9-9e2b-c0fc8a6d5293.png">

why does only the bottom value use the _normal_ width? I would expect all bars to have the same size. 

Line width is set to 1. Setting it to 0 seems to help, but every other value has weird behaviour:
- 1, 2: only the bottom bar changes
- 3: like 1-2, but an additional thin line appears parallel to the main bar, when there's no data point. eg, suppose the output of the query is:

timestamp1 metric1 1
timestamp1 metric2 1
timestamp2 metric1 4

I get a thin line next to the timestamp2 bar:
<img width="15" alt="Schermata 2021-07-16 alle 10 01 27" src="https://user-images.githubusercontent.com/9781798/125913627-3075391d-f1f7-47ce-9eab-6407f6304a93.png">
(see the orange line that runs up to the top?)

When there are few values and bars grow larger, this artifact disappears. You still get that width inconsistency:
<img width="327" alt="Schermata 2021-07-16 alle 10 04 10" src="https://user-images.githubusercontent.com/9781798/125913957-be9cfd56-bbc7-4fe9-87ed-0f2bb234e290.png">

**Comment by wiz78** [comment] 2021-07-19 15:30
Server:
Grafana 8.0.6
Windows 2016

Client:
Firefox 90
macOS 11.4

With Brave 1.26.77 it's even worse (axis labels):

<img width="1019" alt="Schermata 2021-07-19 alle 17 28 11" src="https://user-images.githubusercontent.com/9781798/126185752-a6b38524-eb11-43b5-b19d-6dc29abdbbe8.png">

Edge 91.0.864.70 is just like Firefox:

<img width="928" alt="Schermata 2021-07-19 alle 17 29 39" src="https://user-images.githubusercontent.com/9781798/126186001-b99ce45c-76e5-4bd8-b6ab-39de0e655c66.png">

**Comment by wiz78** [comment] 2021-07-19 15:33
oh, and I'm using an iMac with Retina screen (it might be due to hi-dpi?)

**Comment by leeoniya** [comment] 2021-07-19 21:37
i can reproduce this on `main` with both devicePixelRatio of 1 and > 1 (when zoomed).

this is definitely related to a non-zero line width and not due to hi-dpi. my educated guess is that uPlot is not properly accounting for stroke width when building clipping paths for bands.

**Comment by leeoniya** [comment] 2021-07-19 22:04
fixed in uPlot by https://github.com/leeoniya/uPlot/commit/3b65b330f51113c85747e4008aec80a5874efe23

**Closed** 2021-07-21 22:27 UTC
Labels: area/panel/timeseries, type/bug
