### ISSUE TITLE
Grafana 8.0.2 Annotation Bug 

### ISSUE THREAD

**Issue by keiths2021** [grafana/grafana#35896] opened 2021-06-17 16:55 UTC
**What happened**:
Just installed 8.0.2 - when try to create annotation in 8.0.2 using built-in Grafana dataset random walk get error as follows with red warning triangle  "AnnotataionQueryRunner failed Query error: 400 Bad Request"
  
**What you expected to happen**:
Annotation to be added successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Create new panel in 8.0.2 with Grafana test data and try to add annotation. 

**Anything else we need to know?**:
Same annotation test works fine on 7.5.8 with Random Walk test data set  

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: Grafana test dataset Random Walk (and also SQL) 
- OS Grafana is installed on: Ubuntu 20.04 LTS 
- User OS & Browser: Firefox
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment] 2021-06-17 18:42
Can you describe what your doing more? 

* Are you creating an annotation query? 
* Are you trying to CTRL+click graph to create an annotation event?

**Comment by keiths2021** [comment] 2021-06-18 10:58
Having installed and done nothing else I simply try to create (using  CTRL+click graph) an annotation event on a newly created panel using Random Walk dataset - but that fails on 8.0.2 with error as given before.

I just now, to be sure, created a new ubuntu 21.04 VM on Hyperv and now installed 8.0.3 (which was new in today).

When installed this I see immediately Random Walk dataset panel unlike in 8.0.2. When I do CTRL+click on graph to add annotation event it now just zooms-in as-if did not recognised I was hold the CTRL button.

The exact same action working fine on another 21.04 VM but with 3.5.8 installed.

**Comment by keiths2021** [comment] 2021-06-18 11:01
PS The keyboard mapping for CTRL button is fine a other commands like CTRL+s work to save

**Comment by keiths2021** [comment] 2021-06-18 12:15
Update   I see that the default Random Walk Graph in v8 has changed from v7 to in that previously is was of type Graph and now it is of type Timeseries….and Timeseries appears not to support annotation which explains the new 8.0.3 behaviour

**Comment by isaacag** [comment] 2021-07-14 08:44
Being Reproduced on 8.0.5

Dashboard with 2 Annotation queries from postgres data source, one contains ranges, one simple events. When both are activated and dashboard is loaded message appears "AnnotataionQueryRunner failed Query error: 400 Bad Request" and query with simple events is not loaded, query with ranges is loaded without issue.

Recovery: Toggle annotation visibility fo force reload and annotations are returned as expected.

Error started appearing after migration from Grafana 7.5, deleting and recreating annotation query has no effect.

**Comment by ivanahuckova** [comment] 2021-07-20 15:41
@isaacag I am going to close this issue as it is duplicate of https://github.com/grafana/grafana/issues/35896.

**Closed by ivanahuckova** 2021-07-20 15:41 UTC
Labels: area/annotations, needs more info
