### ISSUE TITLE
[Bug] Admin page doesn't update the title

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#6891] opened 2016-12-09 10:32 UTC
Admin page doesn't update the title. Whenever user navigates from old page, still the old title remains.

Please include this information:
- What Grafana version are you using? - 3.1.0
- What datasource are you using? - N/A
- What OS are you running grafana on? - Windows & Chrome
- What did you do? - Navigate to Admin page after visiting some dashboards
- What was the expected result? - Admin page title should be "Grafana - Admin Page" or something similar
- What happened instead? - Old title didn't change.

**Comment by torkelo** [comment] 2016-12-12 14:20
duplicate of https://github.com/grafana/grafana/issues/3211

**Closed by torkelo** 2016-12-12 14:20 UTC
