### ISSUE TITLE
upgrade from version 10.0.4 to version 10.1.1, influxql adhoc filters gives me "failed to load options"

### ISSUE THREAD

**Issue by HolgerHees** [grafana/grafana#74258] opened 2023-09-01 08:46 UTC
### What happened?

After my upgrade from version 10.0.4 to version 10.1.1 (10.1.0 too), Adhoc filters for my influxdb (influxql) datasource does not work anymore. I get the message "failed to load options"

![grafik](https://github.com/grafana/grafana/assets/5681988/4b4930ac-a87c-47b3-8f02-44be1be84f0f)

in javascript console I see '[FilterByValue] Could not find index for field name: blocking_state"

with the old version, everything was working fine.

If I manually provide a filtervalue as a get parameter, the adhoc filter is using this value, but I'm not able to change or remove.

![grafik](https://github.com/grafana/grafana/assets/5681988/04c17056-545e-4b47-a14b-64b90a02a756)

If I revert back to version 10.0.4, it works again.

![grafik](https://github.com/grafana/grafana/assets/5681988/a898d3f6-4c31-43be-9919-8e3d13855c5f)

### What did you expect to happen?

that it works again like before

### Did this work before?

yes, in version 10.0.4

### How do we reproduce it?

just open a influxql adhoc filter in version 10.1.1

### Environment (with versions)?

Grafana: 10.1.1
OS: Opensuse 15.4
Browser: Firefox Version 116

### Grafana platform?

Docker

### Datasource(s)?

InfluxDB

**Comment by itsmylife** [comment] 2023-09-15 14:05
@HolgerHees Thanks for the bug report. I can reproduce this issue and I have a fix. I will create a PR soon.

**Comment by itsmylife** [comment] 2023-09-18 12:25
I will hold my PR and not merge for the sake of this PR https://github.com/grafana/grafana/pull/74962. It is resolving the issue in a way better way. When it will be merged, it will resolve this issue. I will provide some unit tests additionally.

**Closed** 2023-09-18 12:44 UTC
Labels: type/bug, datasource/InfluxDB, triage/needs-confirmation

**Comment by HolgerHees** [comment] 2023-10-25 06:43
with Version 10.1.5 it was fixed. 

Today I updated to version 10.2.0 and the error happens again.

**Comment by itsmylife** [comment] 2023-10-25 06:46
@HolgerHees let me check this first. Sorry for the inconvenience.

**Comment by itsmylife** [comment] 2023-10-25 06:54
@HolgerHees I can reproduce this on `main` 🤦‍♂️
If you like you can create an issue an assign it to me. I fil sort this out asap.

**Comment by itsmylife** [comment] 2023-10-25 07:00
It is broken again here because of me https://github.com/grafana/grafana/pull/75653
In the `datasource.ts` file there is a method called `metricFindQuery`. In it, I use the `scopedVars` from `options` but `options` is optional. This was handled properly before and I somehow removed that optional check. 🤦‍♂️

**Comment by HolgerHees** [comment] 2023-10-25 07:04
thanks for investigating.

this is now the new ticket.

https://github.com/grafana/grafana/issues/77105

and I can't assign anyone to this ticket.
