### ISSUE TITLE
Linking to a panel inside a collapsed row does not work

### ISSUE THREAD

**Issue by roganartu** [grafana/grafana#11438] opened 2018-03-29 20:12 UTC
### Version
v5.0.1-pre1 (commit: b1494637d)

### Steps
1. Create a dashboard with a default-collapsed row
1. Expand the row, but do not save the dashboard
1. View a panel inside that row in fullscreen
1. Copy the URL into a new browser tab or window

### Expected
Panel is shown fullscreen

### Actual
Dashboard renders as if visiting normally, but loads no data and simply shows blank panels (if there are any outside of the collapsed row). No error is presented.

Once you expand the collapsed panel, you are immediately shown the originally linked panel in fullscreen, with data seemingly already loaded and rendered.

**Comment by torkelo** [comment] 2018-04-02 11:53
dupe of https://github.com/grafana/grafana/issues/11086 (fixed in v5.0.4)

**Closed by torkelo** 2018-04-02 11:53 UTC
