### ISSUE TITLE
[Feature Request] Implementing Tabs on Dashboards

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3506] opened 2015-12-12 12:09 UTC
Greetings,

I'm actually doing several custom dashboards for our company. The fact is that people always want a dashboard with maximum information as possible, wich becomes a  huge DB with more than 20 graph panels. Thinking about that, implementing Tabs on Grafana would be awesome.

It would reduce the number of queries (wich means less charge on datasources), faster loading time and a heavy customization. From the point of view of the user, it would allow to see a huge DB without scrolling, only changing between tabs mantaining the same templating values and time range.

They way to implement that would be creating a new top-level on the DB hierarchy, above rows. The JSON would be:
` "tabs": [
   {
     "rows": [
     {
       ...
       "panels": [
         {
          ...
          }
         ]
      }
     ]
   }
 ]`

As an example:
<h4>First Tab selected:
![tab1](https://cloud.githubusercontent.com/assets/13196237/11761783/616f1c9c-a0d0-11e5-8bba-23a324bca54a.jpg)

<h4>Second Tab selected:
![tab2](https://cloud.githubusercontent.com/assets/13196237/11761785/706dfc5e-a0d0-11e5-8b2b-3d408b02a4d3.jpg)

As an extended improvement, it would be implemented with "Repeat mode" feature, so as row and panel work, Tabs would be repeated depeding on templating params.

Thanks!

**Comment by toni-moreno** [comment] 2015-12-12 12:17
+1

**Comment by torkelo** [comment] 2015-12-14 09:21
This is duplicate of https://github.com/grafana/grafana/issues/322 , but nice mockup! please add the image to the above issue!

**Closed by torkelo** 2015-12-14 09:21 UTC
