### ISSUE TITLE
label_values(metric, label) prints surplus results for a long period of time (old metric values)

### ISSUE THREAD

**Issue by Blasterdick** [grafana/grafana#8219] opened 2017-04-26 09:57 UTC
Grafana 4.2.0
Prometheus 1.6.1

Custom recording rule:

````
kube_alive_pods = kube_pod_status_phase{pod=~"frontend-.*",phase="Running"} == 1
````
Querying it from Prom interface results list of currently running pods in kubernetes cluster.

While querying this from templating variable like:

```
label_values(kube_alive_pods, pod)
```
prints surplus values, if time range contains already deleted pods. 

How can I print only currently running pods regardless of the time range, that I've selected?

**Comment by torkelo** [comment] 2017-04-26 12:50
dupe of https://community.grafana.com/t/label-values-metric-label-prints-surplus-results-for-a-long-period-of-time-old-metric-values/689/2

**Closed by torkelo** 2017-04-26 12:50 UTC
