### ISSUE TITLE
Automatic min/max gauge does not use Decimals or Unit

### ISSUE THREAD

**Issue by pandadoudou** [grafana/grafana#21973] opened 2020-02-06 13:29 UTC
Hello,

I installed the 6.6 version (5c11bbdfb4) and added a gauge without setting the min and max value.
As per the new feature, it will generate the min/max values from the dataset.

Issue : the decimals are not applied, nor the Units.

![Capture](https://user-images.githubusercontent.com/28102855/73941163-05348b00-48ed-11ea-94f4-8c66dcc2dc82.PNG)
![Capture2](https://user-images.githubusercontent.com/28102855/73941164-05348b00-48ed-11ea-84f8-e4f98760d064.PNG)

![Capture3](https://user-images.githubusercontent.com/28102855/73941162-049bf480-48ed-11ea-9eb8-fca0ff57d13e.PNG)

Thanks

**Comment by peterholmberg** [comment] 2020-02-06 15:45
Hello @pandadoudou ! I'd need more information to trouble shoot this properly. Please use the bug report issue template

**Comment by pandadoudou** [comment] 2020-02-06 15:53
Hello @peterholmberg,
Sorry, I'm new here, where do I find this template ?

**Comment by pandadoudou** [comment] 2020-02-06 15:53
> 
> 
> Hello @pandadoudou ! I'd need more information to trouble shoot this properly. Please use the bug report issue template

Hello @peterholmberg , where do I find this template?

**Comment by peterholmberg** [comment] 2020-02-07 12:01
@pandadoudou when you create an issue you have the option to choose an issue template

**Comment by pandadoudou** [comment] 2020-02-09 10:23
**What happened**: Automatic gauge min/max not using the number formatting.

**What you expected to happen**: Units should be applied the same as the value

**How to reproduce it (as minimally and precisely as possible)**:

Case 1 :
0. Having a datasource having a value of 62'300'000'000 and a value below it and a value above it (in the same time-range)
1. Create a new gauge
2. Clear the "Minimum" and "Maximum" value
3. Set the "Unit" as "Bytes/sec"

Result : The displayed value is 623Mbs (OK) but the minimum and maximum auto-generated values does not follow the display rules.

Case 2 :
0. Having a datasource having a value of 0.1234 and 0.4567 and 0.6789
1. Create a new gauge
2. Clear the "Minimum" and "Maximum" value
3. Set the "Unit" as "Short"
4. Set the "Decimals" as 2

Result : The displayed value is 0.46 (OK) but the minimum and maximum auto-generated values does not follow the display rules.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Microsoft SQL Server
- OS Grafana is installed on: Ubuntu Server
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None
- Others:

**Comment by pandadoudou** [comment] 2020-02-17 08:56
@peterholmberg Do you need any futher details ?

**Comment by torkelo** [comment] 2020-02-17 12:06
Duplicate of https://github.com/grafana/grafana/issues/5348

**Closed by torkelo** 2020-02-17 12:06 UTC
Labels: needs more detail
