### ISSUE TITLE
Alerting: double notification with HA setup

### ISSUE THREAD

**Issue by pavriet-boxtal** [grafana/grafana#71203] opened 2023-07-07 12:48 UTC
### 
# What went wrong?

**What happened**:

  - Running grafana v9.5.1, with 2 nodes (HA setup), On AWS ECS (so 2 containers on 2 EC2 hosts)
  - many alerts, all running smoothly. Instance is not prod yet, we are moving from v8.
  - One of our team reports receiving a double notification on one of his alert. It does not happen with other alerts. (I did follow [this](https://grafana.com/docs/grafana/next/alerting/set-up/configure-high-availability))
 
Rule labels:
![image](https://github.com/grafana/grafana/assets/136579429/c5c009f7-ed91-4144-a458-6f97913efa8e)
Rule UID: `cb4f7904-f587-4191-870b-00739ce8c9e5`
Notification matchers:
![image](https://github.com/grafana/grafana/assets/136579429/13b6cf65-0776-48dd-914f-a2419c19d5a1)

Looking for rule uid in the logs I found the following:
2 "Sending notification" on 2 container instances, at the time the 2 notifications are received. 
![image](https://github.com/grafana/grafana/assets/136579429/6b0bacf7-64fb-4a8c-97ff-7bbbe21509fd)

**What did you expect to happen**:

  - Only receive a single notification

### 
# How do we reproduce it?

- Create alert with given labels
- Create notification policies (and contact points) given
- Wait (or force) alert to trigger

### 
# What Grafana version are you using?

v9.5.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

AWS Linux 2023

### User's Browser?

Any

### Is this a Regression?

None

**Comment by stevesg** [comment] 2023-07-10 10:59
This could be due to the Alertmanagers in the two Grafana instances not communicating. If they are not sharing notifications, then there will be duplicates

Would you mind checking the `alertmanager_cluster_members` metric? If the communication between the instances is working as expected, the metric in both instances should have a value of `2`.

**Comment by pavriet-boxtal** [comment] 2023-07-10 13:34
They are both at 2

![Screenshot from 2023-07-10 15-31-07](https://github.com/grafana/grafana/assets/136579429/40caed9a-037b-4ef8-aeb6-6c0180feff45)

**Comment by armandgrillet** [comment] 2023-07-28 15:35
@pavriet-boxtal Did the comment from Steve worked for you?

**Comment by armandgrillet** [comment] 2023-08-30 09:37
Closing due to lack of reply, please reopen if the issue is still happening.

**Closed by armandgrillet** 2023-08-30 09:37 UTC
Labels: area/alerting, triage/needs-confirmation
