### ISSUE TITLE
OAuth - Unable to override insecure email lookup in 9.3.16

### ISSUE THREAD

**Issue by dboden-nitro** [grafana/grafana#70567] opened 2023-06-23 08:24 UTC
### 
# What went wrong?

**What happened**:

Upgraded our docker based deployment of Grafana 9.3.14 to 9.3.16 and noticed that I could no longer authenticate.
We are using the generic OAuth configuration in combination with Azure AD.
I read about the breaking change and added the GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP=true environment variable which did not solve the issue.
Further investigation showed that the setting was not overridden and still set to false when looking at the config settings in the Grafana UI.

**What did you expect to happen**:

Upgrade to 9.3.16 and adding the environment variable should have allowed me to authenticate.

### 
# How do we reproduce it?

**Step 1**:

- Upgrade grafana docker image from version 9.3.14 to 9.3.16

**Step 2**:

- Add environment variable GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP=true

**Step 3**:

- Log on to Grafana using Azure AD credentials

### 
# What Grafana version are you using?

v9.3.16

### 
### Grafana Platform?

Kubernetes

### Is this a Regression?

Yes

### Anything else to add?

Looks like https://github.com/grafana/grafana/commit/26b48dbf19a709ac4a1523ce1c5e8e42323aa62a was not backported to the 9.x branch

**Comment by usmangt** [comment] 2023-06-26 09:33
Hi @dboden-nitro,

Thanks for opening this issue.

Could you please provide us with the backend logs by adding the environment variable `GF_LOG_LEVEL=debug` in your docker-compose file and then reproduce this case?

**Comment by Jguer** [comment] 2023-06-30 09:50
Hi @dboden-nitro , I'm closing this issue has it's been answered in https://github.com/grafana/grafana/issues/70203#issuecomment-1609850174.

This due to https://github.com/grafana/grafana/commit/ee1533007e5a8693ab49c8ce70084fc7ca1008c1 not being included in 9.3.16. 

You'll need to include the following in your .ini config unfortunately

```ini
[auth]
oauth_allow_insecure_email_lookup=true
```

**Closed by Jguer** 2023-06-30 09:50 UTC
Labels: needs more info, area/auth/oauth, area/docker

**Comment by tobijdc** [comment] 2023-06-30 10:22
Hi @Jguer 

We use exclusively ENV variables to configure our Grafana instances.
Does this mean this will not be fixed?
Would mean for us to either:

- stay on old version (not being able to update to future security patches)
- implement Adaption of config file for the his one second
- fast track the move to v10

Is there a reason why this is setting is not configurable via ENV (as I don't know of another setting that acts like this)?

Thanks

**Comment by Jguer** [comment] 2023-06-30 12:40
> Is there a reason why this is setting is not configurable via ENV (as I don't know of another setting that acts like this)?

This is due to https://github.com/grafana/grafana/commit/ee1533007e5a8693ab49c8ce70084fc7ca1008c1 not being included in 9.3.16 neither in any of the 9.x as those releases were made with minimal changes to fix the CVE.

I don't know when next releases of 9.x will be and if they'll include the fix (the most likely to include it would be the next release of 9.5)

**Comment by elasticdotventures** [comment] 2023-10-08 23:28
For anybody else reading this -- 
the environment variable `GF_AUTH_GENERIC_OAUTH_INSECURE_EMAIL_LOOKUP ` does not appear to work on version 10.x either.

**Comment by Jguer** [comment] 2023-10-09 10:10
@elasticdotventures `GF_AUTH_GENERIC_OAUTH_INSECURE_EMAIL_LOOKUP` does not exist, only
`GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP` which applies to all oauth providers
