### ISSUE TITLE
Alerting: Search by Label errors when viewing Alert Rule

### ISSUE THREAD

**Issue by cmcculler** [grafana/grafana#80233] opened 2024-01-09 16:56 UTC
### What happened?

When trying to use the Search by Label feature when viewing an Alert Rule, a javascript error is thrown and the filter does not apply. 

```
Uncaught TypeError: Cannot read properties of null (reading 'value')
    at MatcherFilter.tsx:27:31
```

The error points to an event handler in [MatcherFilter.tsx](https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/alert-groups/MatcherFilter.tsx#L24-L25) that is attempting to get the value for `e.currentTarget`. However `e.currentTarget` is null. `e.Target` is not null and contains the expected value. See the attached gif for a reproduction with a debug breakpoint
![grafana-search-by-label-bug](https://github.com/grafana/grafana/assets/88672305/a000c930-6914-44e6-ab9a-dc03c20744ec)

### What did you expect to happen?

The match filter to work and display only matches

### Did this work before?

Unsure.

### How do we reproduce it?

1. Create an alert rule that has one or more matching labels
2. View the rule
3. Attempt to filter the matches

### Environment (with versions)?

Grafana: v10.2.0 (895fbafb7a)
OS: MacOS Sonoma 14.2.1
Browser: Chrome 120.0.6099.199

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment] 2024-02-07 08:59
hi @cmcculler Thank you for reporting this bug

This is a [known issue](https://github.com/grafana/grafana/issues/79987) and it's already assigned to the codeowners project

I will mark this ticket as duplicate, but I will mention your report in the other ticket for visibility . Thank you!

/duplicate of #79987

**Closed** 2024-02-07 09:00 UTC
Labels: type/duplicate
