### ISSUE TITLE
[Feature Request] Allow template variables to have a filter after matching

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#4939] opened 2016-05-06 21:09 UTC
In some cases, metrics have variant structure depending on the name at some level.
It would be nice to have template variables that can hide the odd structure for a particular use, to ensure that expanded metric names are proper.

To allow for this, an optional "exclude values" filter would be nice. Regex doesn't seem to be as suitable for this in the query expression directly.

For example, if you have metrics:

~~~
a.b.c.AllC
a.b.c.d
a.b.c.e
~~~

It would be nice to query for names a.b.c.*, but not include AllC.

**Comment by torkelo** [comment] 2016-05-09 06:31
duplicate of https://github.com/grafana/grafana/issues/4000

**Closed by torkelo** 2016-05-09 06:31 UTC
Labels: comp: dashboard/templating
