### ISSUE TITLE
Staircase is drawn into future, not into past

### ISSUE THREAD

**Issue by tarko** [grafana/grafana#19090] opened 2019-09-13 10:11 UTC
**What happened**:

Prometheus query (with min step 2h) returns maximum value of in/out (whichever is largest) for last $__interval

Intention is to display this maximum as staircase next to the actual in and out graphs

Currently, staircase (yellow) is drawn into future. Value returned at 06:00 (values also shown as orange dots) covers period from 04:00 - 06:00. But staircase is drawn from 06:00 - 08:00 so one could say max value is shifted $__interval into future.

![staircase](https://user-images.githubusercontent.com/1047849/64854590-a6f9c980-d626-11e9-9299-84293922ef71.png)

There doesn't seem to be any reasonable way to fix this in query as you cannot have negative offset that would allow you to run queries into future. There is currently also no time shift support for single query.

**What you expected to happen**:

Value returned at 06:00 would be used to draw staircase from 04:00 to 06:00

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: Prometheus

**Comment by torkelo** [comment] 2019-09-13 14:44
duplicate of https://github.com/grafana/grafana/issues/7941

**Closed by torkelo** 2019-09-13 14:44 UTC
