### ISSUE TITLE
[Bug] Alias are not showing properly when using templates in dashboard

### ISSUE THREAD

**Issue by kaustubhmallik** [grafana/grafana#8575] opened 2017-06-08 15:00 UTC
Grafana version: **4.3.2**
Datasource: **OpenTSDB**
OS: **Debian Wheezy (Debian 7)**

Created a dashboard with template, using a variable of custom type to be used in metric name which is to be queried from OpenTSDB server. Created multiple queries, and used different Alias for each of them. 

Expected result was that each metric will have different alias as provided but, all the alias are coming to be same, and that of alias of first metric. I checked the same issue exist in version 4.3.1 also. Can you please check this. Alias is working fine in normal dashboards (when not using templates). Below are the screenshots:

![screenshot-1](https://user-images.githubusercontent.com/4466799/26935246-11452a70-4c89-11e7-80fd-e19b2abda460.png)

![screenshot-2](https://user-images.githubusercontent.com/4466799/26935253-174cf952-4c89-11e7-9fbb-fede0af9385a.png)

**Comment by torkelo** [comment] 2017-06-08 15:28
Please search before :) `OpenTSDB alias` would have yielded a bunch of closed issues :) 

They all relate to a problem in OpenTSDB that makes it impossible for Grafana to know which series came from which query. 

Dupe of 
https://github.com/grafana/grafana/issues/2687
https://github.com/grafana/grafana/issues/3108
https://github.com/grafana/grafana/issues/1915
https://github.com/grafana/grafana/issues/1876

Fixed in OpenTSDB 2.3 and Grafana 3.1 (master)

**Closed by torkelo** 2017-06-08 15:28 UTC
