### ISSUE TITLE
[Bug] PNG rendering fails with JavaScript error

### ISSUE THREAD

**Issue by wienczny** [grafana/grafana#9196] opened 2017-09-07 15:53 UTC
Grafana Version 4.5.0-beta1 (provided debian package)
Datasource is influxdb
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch

Im trying to render a dashboard to a png by prepending /render to the url. This gets stuck in a timeout.
When looking at the debug output from phantomjs I geht this:

> ...
2017-09-07T17:02:54 [DEBUG] WebPage - evaluateJavaScript result QVariant(bool, false)
2017-09-07T17:02:54 [DEBUG] WebPage - evaluateJavaScript "(function() { return (function () {\n        if (!window.angular) { return false; }\n        var body = window.angular.element(document.body);\n        if (!body.injector) { return false; }\n        if (!body.injector()) { return false; }\n\n        var rootScope = body.injector().get('$rootScope');\n        if (!rootScope) {return false;}\n        var panels = angular.element('div.panel:visible').length;\n        return rootScope.panelsRendered >= panels;\n      })(); })()"
2017-09-07T17:02:54 [DEBUG] WebPage - evaluateJavaScript result QVariant(bool, false)
2017-09-07T17:02:54 [DEBUG] WebPage - evaluateJavaScript "(function() { return (function () {\n          return document.getElementsByClassName(\"main-view\")[0].getBoundingClientRect();\n        })(); })()"
ERROR: TypeError: undefined is not an object (evaluating 'document.getElementsByClassName("main-view")[0].getBoundingClientRect')
TRACE:
 -> undefined: 2
 -> : 3
  phantomjs://code/render.js:48 in onError
2017-09-07T17:02:54 [DEBUG] WebPage - evaluateJavaScript result QVariant(Invalid)
TypeError: null is not an object (evaluating 'bb.top')

New dashboards are working. Older dashboards are not. A clone of a broken dashboard does not work either, even after deleting all panels.
All dashboards work in a regular browser.

**Comment by torkelo** [comment] 2017-09-08 08:34
does it work for single panels?

**Comment by wienczny** [comment] 2017-09-08 09:44
Single panels are working

**Comment by torkelo** [comment] 2017-09-15 14:19
not sure what can be the cause of this, have yet to find a dashboard that does not work. Maybe it's just slow panel queries ?

**Comment by philipspigelmire** [comment] 2017-10-18 20:40
If the timeout is reached, the render.js code calls 
`document.getElementsByClassName("main-view")[0].getBoundingClientRect();`
Since the page didn't load for some reason you get that error. I think render.js should not call this if panelsRendered is false.

**Comment by eloo** [comment] 2020-02-04 13:04
I'm currently also having this issue.. Is the timeout for the renderer configurable?

**Comment by torkelo** [comment] 2020-11-10 16:30
Closing this due to no other reports and old bug that is probably fixed

**Closed by torkelo** 2020-11-10 16:30 UTC
Labels: area/dashboard/snapshot, type/bug
