### ISSUE TITLE
Unable to view or edit panel expressions

### ISSUE THREAD

**Issue by Nibblefritz** [grafana/grafana#63227] opened 2023-02-09 21:55 UTC
**What happened**: Unable to view or edit expressions in the grafana UI after update to 8.5.16

**What you expected to happen**: When clicking on an existing expression or adding a new one, should be able to edit the expression in the UI and not just panel JSON

**How to reproduce it (as minimally and precisely as possible)**:  Open up a panel, click +expression. Whether clicking the arrow to expand or not all that shows is (expression).

**Anything else we need to know?**: The only way currently to view the expression that exists is by opening the panel JSON

**Environment**:
- Grafana version: 8.5.16
- Data source type & version: Prometheus 2.43.0
- OS Grafana is installed on: Linux Ubuntu 20.04
- User OS & Browser: Mac OS, Windows, Firefox, Chrome
- Grafana plugins: Alertmanager

![Screen Shot 2023-02-09 at 2 52 46 PM](https://user-images.githubusercontent.com/23125198/217948223-a43ad9fa-785c-4fc3-a35e-d32c92e9b5ff.png)

**Comment by quickguard** [comment] 2023-02-10 06:30
same issue

**Comment by julianullrich99** [comment] 2023-02-10 12:38
same here

**Comment by LouisHaftmann** [comment] 2023-02-10 12:41
same here

**Comment by zuchka** [comment] 2023-02-13 20:37
looks like the same issue that this PR addressed. If it is, then it needs to get backported to 8.x

https://github.com/grafana/grafana/pull/62510

**Comment by zuchka** [comment] 2023-02-13 20:41
as a workaround, or a future migration, panel transformations are client-side, not server-side like expressions. but they are heavily developed and very powerful

https://grafana.com/docs/grafana/v8.4/panels/reference-transformation-functions/#merge

**Comment by itsmylife** [comment] 2023-02-20 15:42
I cannot reproduce the issue on `v8.5.16`. 
I tried several things but it is working. 
- Creating a new expression
- Editing an existing expression

The problem solved with this PR https://github.com/grafana/grafana/pull/62510 wasn't backported to `v8.x`.

**Comment by bck01215** [comment] 2023-02-21 20:45
Same issue on v9.3.6

**Comment by itsmylife** [comment] 2023-02-22 11:58
@bck01215 It will be fixed in `v9.3.7`.

**Comment by itsmylife** [comment] 2023-02-22 11:58
@Nibblefritz what was the version you were updating it from?

**Comment by andrea-tomassi** [comment] 2023-03-01 16:33
Same here. It seems that it is only a UI issue. If you use a panel you developed previously, with an older version, then the expression keeps working, you just cannot see/edit its details from the Grafana GUI.

So another workaround could be: programming the panel into another (older) Grafana and then import the panel into the new Grafana.

**Comment by zuchka** [comment] 2023-03-28 00:31
thanks for the update @pchang388 . going to close this issue for now 👍

**Closed by zuchka** 2023-03-28 00:31 UTC
Labels: type/bug, area/expressions
