### ISSUE TITLE
Multi-value variable search will deselect any previously selected value

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#25020] opened 2020-05-22 13:40 UTC
**What happened**:

Multi-value variable search will deselect any previously selected value.

**What you expected to happen**:

Values to remain selected.

**How to reproduce it (as minimally and precisely as possible)**:

Select few values:
![image](https://user-images.githubusercontent.com/5955795/82673397-7acd2880-9c4a-11ea-8ea9-3f33c0ffdb56.png)

Start searching for value and other selected values will be automatically deselected (don't need to press Enter):
![image](https://user-images.githubusercontent.com/5955795/82673515-ab14c700-9c4a-11ea-8d7e-bbe309be34cd.png)

**Anything else we need to know?**:

This seem to be a bug introduced in Grafana 7.0.0

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: N/A
- OS Grafana is installed on: Debian 10
- User OS & Browser: Google Chrome (latest), Arch Linux.
- Grafana plugins: N/A
- Others: N/A

**Comment by dswarbrick** [comment] 2020-05-22 14:38
This sounds like a duplicate of #24990.

**Comment by zoltanbedi** [comment] 2020-05-22 15:21
Thanks for reporting this issue, as @dswarbrick said it is a duplicate of #24990 so I'm going to close this.

**Closed by zoltanbedi** 2020-05-22 15:21 UTC
