### ISSUE TITLE
Embedding Grafana: allow_embedding is broken 

### ISSUE THREAD

**Issue by dean9** [grafana/grafana#23876] opened 2020-04-24 22:06 UTC
**What happened**:
* Grafana's provided html to embed a dashboard includes a URL which returns a response that includes the header "X-Frame-Options: deny" regardless of the configured "allow_embedding" value.  This causes the iframe to not be displayed.

**What you expected to happen**:
* This header should be omitted if "allow_embedding = true" is in the grafana.ini config file.

**How to reproduce it (as minimally and precisely as possible)**:
* in grafana.ini add "allow_embedding = true"
* restart grafana (system dependent)
* open grafana, navigate to the share tab of the relevant dashboard
* under the "Embed" tab, there is html provided for embedding the dashboard as an iframe.  Copy and request the provided URL.
* view the response headers
* you will find this includes "X-Frame-Options: deny"

**Anything else we need to know?**:
Initial feature implementation as a result of this issue  https://github.com/grafana/grafana/issues/14189

**Environment**:
- Grafana version: Version 6.7.3
- Data source type & version: n/a
- OS Grafana is installed on: Mac OS
- User OS & Browser: Mac OS, tested on Safari and Firefox
- Grafana plugins: n/a
- Others: n/a

**Comment by papagian** [comment] 2020-05-02 10:13
I'm unable to reproduce it and reading the source the grafana [takes into account](https://github.com/grafana/grafana/blob/v6.7.3/pkg/middleware/middleware.go#L292) the `allow_embedding` configuration for setting this header.

Can you verify in the Settings page (http://localhost:3000/admin/settings) that allow_embedding is set?

**Comment by wizzfizz94** [comment] 2020-06-04 09:36
I am also experiencing this problem this problem. I'm running the official Grafana docker image behind nginx and trying to share iframes on another site that is also behind the nginx server. My run script looks like this:
```
#!/bin/bash

docker run \
--sig-proxy=false \
--name=grafana_dev \
--network=cams-net \
-p 3001:3000 \
--restart unless-stopped \
-e "GF_SERVER_DOMAIN=mysite.com" \
-e "GF_SERVER_ROOT_URL=http://mysite.com/dev/graphs/" \
-e "GF_DATABASE_URL=mysql://grafana_user:grafana_password@XXX.XX.XX.XX:XXXX/grafana_dev" \
-e "GF_INSTALL_PLUGINS=grafana-worldmap-panel,fetzerch-sunandmoon-datasource,https://github.com/panodata/grafana-worldmap-panel/releases/download/0.4.0/grafana-worldmap-panel-ng-0.4.0.zip;grafana-worldmap-paneli-ng" \
-e "GF_SECURITY_ALLOW_EMBEDDING=true" \
grafana/grafana:6.4.4
``` 
Note I've stripped a lot of the config but i can confirm it works fine beside the allow embedding option. When i share an iframe at `mysite.com/dev/app` i get:
```
Refused to display 'https://mysite.com/dev/graphs/d-solo/XXXXXX/dashname?orgId=1&refresh=5m&panelId=2' in a frame because it set 'X-Frame-Options' to 'deny'.
```

**Comment by papagian** [comment] 2020-06-04 10:17
@wizzfizz94 
can you try hiding `X-Frame-Options` header in your nginx configuration as suggested [here](https://stackoverflow.com/questions/47405597/x-frame-options-in-nginx-to-allow-all-domains#answer-47406213)?

does this help?

**Comment by wizzfizz94** [comment] 2020-06-06 15:17
@papagian my bad i had an existing line in my nginx config `add_header X-Frame-Options DENY`. Removing that the embedding works fine.

**Comment by marefr** [comment] 2020-06-15 10:40
Closing this since feels like a configuration error.

**Closed by marefr** 2020-06-15 10:40 UTC
Labels: needs investigation
