### ISSUE TITLE
Time series panel - Hover Tooltip

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#38051] opened 2021-08-19 06:03 UTC
**What happened**: 
- Hover tooltip shows wrong value in tooltip
- Color in tooltip differs from color in legend
- Hover tooltip is shown only near by a metrics point

**What you expected to happen**:
- Hover tooltip should show the right value in the right color
- Hover tooltip should always be the same for the hole range of the value

**How to reproduce it (as minimally and precisely as possible)**:
Create a time series panel that shows multiple metrics
Tooltip mode single
Legend mode table

**Anything else we need to know?**: no

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Prometheus 2.28.1
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Windows 10, Chrome  92.0.4515.159 (Offizieller Build) (64-Bit)
- Grafana plugins:
grafana-clock-panel/        
grafana-image-renderer/     
grafana-piechart-panel/     
grafana-polystat-panel/     
grafana-singlestat-panel/   
jdbranham-diagram-panel/    
natel-plotly-panel/         
novalabs-annotations-panel/ 
ryantxu-ajax-panel/         
savantly-heatmap-panel/     
vonage-status-panel/        

- Others: no

![Tooltip](https://user-images.githubusercontent.com/56024424/130016207-8a58c241-0441-4110-9113-f548130bfff4.gif)

**Comment by AFriemann** [comment] 2021-08-19 07:30
I *believe* these are fixed in 8.1.1 @mhollstein (didn't verify the value difference but the colors and location issues are gone)

**Comment by oscarkilhed** [comment] 2021-08-19 07:56
Duplicate of #36385

**Closed by oscarkilhed** 2021-08-19 07:56 UTC

**Comment by zuchka** [comment] 2021-08-19 21:20
@mhollstein can you try upgrading to v8.1.1 and see if your issues persist? Thanks! 👍

**Comment by leeoniya** [comment] 2021-08-19 21:22
now v8.1.2 ;)

**Comment by mhollstein** [comment] 2021-08-20 06:01
Color seems to be okay in 8.1.2.
Hover color depends on, which datapoint is closer to the mouse pointer.

But I wonder why the third data point is on top.

![Top](https://user-images.githubusercontent.com/56024424/130187201-fc3eb23b-311d-46e3-a763-b66a94cf8a93.gif)

As datapoints:

![Top 2](https://user-images.githubusercontent.com/56024424/130187243-40b45055-3a9e-4b1e-8081-c46b021c64a9.gif)
