### ISSUE TITLE
[ngalert] Alerting notifications not being sent

### ISSUE THREAD

**Issue by dadamssg** [grafana/grafana#39009] opened 2021-09-08 20:33 UTC
**What happened**:
I cannot seem to get v8 alert notifications working. I've created an alert rule based on a prometheus query:

![image](https://user-images.githubusercontent.com/881986/132579791-103082e9-fc1e-4d7d-8cb3-7324e278ccbf.png)

Added a label to use in my Notification Policy: 

![image](https://user-images.githubusercontent.com/881986/132579892-15023bd7-e565-4fc4-a3a8-6c04f5441c4b.png)

Notification policy that is supposed to send a slack notification and email:
![image](https://user-images.githubusercontent.com/881986/132580060-5d990b17-b521-4fb1-b7f7-c886c2c9cd25.png)

The alert goes into the Alerting state but no notifications are sent.
![image](https://user-images.githubusercontent.com/881986/132580173-da5454fa-fbbd-4f6e-84df-07b212f50a97.png)

According to the logs, it appears the alert is being perpetually resolved yet it always stays in the Alerting state according to the ui. 

> t=2021-09-08T15:28:09-0500 lvl=info msg="level=debug component=dispatcher msg=\"Received alert\" alert=\"RAM Used[ea86b3f][resolved]\"" logger=alertmanager
t=2021-09-08T15:28:09-0500 lvl=info msg="level=debug component=dispatcher aggrGroup=\"{}/{alert=\\\"yes\\\"}:{}\" msg=flushing alerts=\"[RAM Used[ea86b3f][resolved]]\"" logger=alertmanager

Here are some of the logs after i turned debug logging on:
![image](https://user-images.githubusercontent.com/881986/132582719-3c1f377a-51f7-4f53-98d0-2c276a3976b2.png)

Here is my admin json blob:

```json
{
  "template_files": {
    "Alerts": "{{ define \"Alerts\" }}\n  {{ range .Alerts }} [{{ .Status }}] {{ range .Labels }} {{ .Name }}={{ .Value }}{{ end }} {{ end }}\n{{ end }}"
  },
  "alertmanager_config": {
    "route": {
      "receiver": "Slack + Email",
      "routes": [
        {
          "receiver": "Slack + Email",
          "matchers": [
            "alert=\"yes\""
          ]
        }
      ],
      "repeat_interval": "5m"
    },
    "templates": [
      "Alerts"
    ],
    "receivers": [
      {
        "name": "autogen-contact-point-default",
        "grafana_managed_receiver_configs": [
          {
            "uid": "spzGkVI7z",
            "name": "Email Notification",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "support@company.com",
              "autoResolve": true,
              "httpMethod": "POST",
              "severity": "critical",
              "uploadImage": false
            },
            "secureFields": {}
          }
        ]
      },
      {
        "name": "Slack + Email",
        "grafana_managed_receiver_configs": [
          {
            "uid": "c2zMzVS7zz",
            "name": "Slack + Email",
            "type": "slack",
            "disableResolveMessage": false,
            "settings": {
              "autoResolve": true,
              "httpMethod": "POST",
              "severity": "critical",
              "text": "{{ range .Alerts }} [{{ .Status }}] {{ range .Labels }} {{ .Name }}={{ .Value }}{{ end }} {{ end }}\n",
              "title": "hi!",
              "uploadImage": false
            },
            "secureFields": {
              "url": true
            }
          },
          {
            "uid": "c2kMkVS7km",
            "name": "Slack + Email",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "support@company.com",
              "autoResolve": true,
              "httpMethod": "POST",
              "severity": "critical",
              "singleEmail": false,
              "uploadImage": false
            },
            "secureFields": {}
          }
        ]
      }
    ]
  }
}
```

I was also informed that i _should_ be able to test contact points but i'm missing that. These contact points were created when i upgraded from v7 to v8.

![image](https://user-images.githubusercontent.com/881986/132584153-a95bd6dd-cf78-427d-86ee-18cb7ce1abcd.png)

I've also tried creating a new slack contact point from scratch and updating the notification policy to use that to no avail.

**What you expected to happen**:
I expect to get an email and slack notification and _not_ to see those "resolved" logs.

**How to reproduce it (as minimally and precisely as possible)**:
I'm using prometheus and the node exporter. I've screenshot everything besides my contact points. I don't _think_ those are necessary to capture here but i can if need be.

**Environment**:
- Grafana version: 8.1.3
- Data source type & version: prometheus
- OS Grafana is installed on: centos 7
- User OS & Browser: mac + brave
- Grafana plugins: ngalert
- Others:

**Comment by davidmparrott** [comment] 2021-09-08 20:57
Thread in public slack about this: https://grafana.slack.com/archives/C0Y4TLW74/p1631132230143500

I haven't dug into this issue but @dadamssg mentioned that this channel was created during migration from v7

**Comment by fbuecklers** [comment] 2021-09-09 10:08
Hi,

we are experience the same issue with 8.1.3. No alerts are sent at all, and the Notification Panel is empty. 
With 8.1.2 everything works as expected.

**Comment by a-mazed** [comment] 2021-09-10 07:15
I can confirm this problem in 8.1.3. After downgrading to 8.1.2 alert start working and sending notifications

**Comment by dadamssg** [comment] 2021-09-10 14:21
@davidmparrott i think i've tracked this down to the usage of templating. Here's what i did:

- removed the label from from alert so it would use the default notification policy which in my case is a slack notification
- changed my alert from `1m for 5m` to `10s for 30s` for testing purposes
- saved my alert rule threshold to where it would resolve and saved(which turned the alert state to "Ok")
- saved my alert rule threshold to where it would fire and saved
- the alert was then eventually in a firing state

I did not get any notification at this point. I _was_ attempting to use a template i had defined in my slack contact point:

Template saved with the name "Alerts"
```
{{ define "Alerts" }}
  {{ range .Alerts }} [{{ .Status }}] {{ range .Labels }} {{ .Name }}={{ .Value }}{{ end }} {{ end }}
{{ end }}
```

In the **Text Body** of my slack contact point:

```
{{ template "Alerts" . }}
```

As soon as i updated the **Text Body** of my slack contact point to plain text, "Test?", and saved the notification immediately went through to slack successfully. 

At this point, i'm thinking i have a bug in my template so i created and saved the example templates from [here](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/#template-examples) and updated my slack contact point to use `{{ template "message" . }}` in the **Text Body** and then ran through the same steps to clear the error and then get it in a firing state again. The notification was never sent. I do not see any templating errors being logged in the `grafana.log`. It seems to just silently fail.

So the only "solution" i have found is to clear the **Text Body** and rely on grafana's default error template which is less than ideal since i lose out on critical pieces of information in the notification.

Side note: i find the template naming confusing. First, you have to `define` your template in the template itself _and_ give it a template name. I'm assuming that the **Template name** field in the grafana ui is purely to allow the user to identify the template. It would be less confusing to me if you did _not_ have to use the ``{{ define "Template" }}` syntax inside the **Content** and grafana would do that for you based on the **Template name**. Like this:

![image](https://user-images.githubusercontent.com/881986/132868403-ce46f4ea-b8f4-4015-9523-9934ccfc0d47.png)

**Comment by dadamssg** [comment] 2021-09-10 15:19
I think i've determined that there were errors in my templates _and_ then templates [documented here](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/#template-examples).

I was able to set my contact point's **Text Body** to this and it worked:

```
{{ range .Alerts }}
  [{{ .Status }}]
  {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
  {{ end }}
{{ end }}
```

So i think the real issue here is that if you have an error in your template it will just silently fail.

**Comment by dadamssg** [comment] 2021-09-10 19:12
However, if i try to use `{{ $values.B.Value }}` in a custom label, Summary, or Description it will silently fail. No notifications get sent.

**Comment by chaoyi996** [comment] 2021-09-13 23:44
I also encountered the same problem

**Comment by N3v3R3nD** [comment] 2021-09-14 07:58
Also, experience the same issue.

**Comment by gerobinson** [comment] 2021-09-15 14:08
Hi @dadamssg, thanks for raising this issue! It looks like there are a number of differe  nt issues here.

> The alert goes into the Alerting state but no notifications are sent.

Is it possible that the alert is fluctuating between Normal and Alerting faster before either `group_wait` or `group_interval` have elapsed in Alertmanager? I understand the default value for these is 30 seconds and 5 minutes and which one is used will depend on whether the alert is the first or a subsequent alert in this group of alerts.

 > I was also informed that i should be able to test contact points but i'm missing that. These contact points were created when i upgraded from v7 to v8.

The UI for contact point testing is not in 8.1.3 I'm afraid. I'm afraid we don't have an ETA for when this will be released (@domasx2).

>  I was attempting to use a template i had defined in my slack contact point:
> ```
> {{ define "Alerts" }}
>  {{ range .Alerts }} [{{ .Status }}] {{ range .Labels }} {{ .Name }}={{ .Value }}{{ end }} {{ end }}
> {{ end }}
> ```

I am unable to reproduce the issue using the same template. Is it possible that since the `repeat_interval` is `5m` it was not resending the notification until 5 minutes has elapsed? I decreased the `repeat_interval` to `30s` as otherwise Alertmanager will wait 5 minutes before sending another notification.

> However, if i try to use {{ $values.B.Value }} in a custom label, Summary, or Description it will silently fail. No notifications get sent.

In the case where a custom annotation cannot be expanded we catch the error and use the literal template text as the custom annotation or label. You might see an error in the logs such as:

    logger=ngalert name=description value="The value is {{ $values.B }}" err="error executing template __alert_Panel Title: template: __alert_Panel Title:1:99: executing \"__alert_Panel Title\" at <$values.B>: map has no entry for key \"B\""

However the notification will contain the following:

    "annotations":{"description":"The value is {{ $values.B }}"},

**Comment by gerobinson** [comment] 2021-09-15 14:12
Hi @dadamssg, thanks for raising this issue! It looks like there are a number of different issues here.

> The alert goes into the Alerting state but no notifications are sent.

Is it possible that the alert is fluctuating between Normal and Alerting faster before either `group_wait` or `group_interval` have elapsed in Alertmanager? I understand the default value for these is 30 seconds and 5 minutes and which one is used will depend on whether the alert is the first or a subsequent alert in this group of alerts.

 > I was also informed that i should be able to test contact points but i'm missing that. These contact points were created when i upgraded from v7 to v8.

The UI for contact point testing is not in 8.1.3 I'm afraid. I'm afraid we don't have an ETA for when this will be released (@domasx2).

>  I was attempting to use a template i had defined in my slack contact point:
> ```
> {{ define "Alerts" }}
>  {{ range .Alerts }} [{{ .Status }}] {{ range .Labels }} {{ .Name }}={{ .Value }}{{ end }} {{ end }}
> {{ end }}
> ```

I am unable to reproduce the issue using the same template. Is it possible that since the `repeat_interval` is `5m` it was not resending the notification until 5 minutes has elapsed? I decreased the `repeat_interval` to `30s` as otherwise Alertmanager will wait 5 minutes before sending another notification.

> However, if i try to use {{ $values.B.Value }} in a custom label, Summary, or Description it will silently fail. No notifications get sent.

In the case where a custom annotation cannot be expanded we catch the error and use the literal template text as the custom annotation or label. You might see an error in the logs such as:

    logger=ngalert name=description value="The value is {{ $values.B }}" err="error executing template __alert_Panel Title: template: __alert_Panel Title:1:99: executing \"__alert_Panel Title\" at <$values.B>: map has no entry for key \"B\""

However the notification will contain the following:

    "annotations":{"description":"The value is {{ $values.B }}"},

**Comment by dadamssg** [comment] 2021-09-15 14:37
@gerobinson 

> Is it possible that the alert is fluctuating between Normal and Alerting faster before either group_wait or group_interval have elapsed in Alertmanager? I understand the default value for these is 30 seconds and 5 minutes and which one is used will depend on whether the alert is the first or a subsequent alert in this group of alerts.

I don't believe so. I'm testing on an alert that tracks filesystem used. I set the `C` expression to alert on any instances above 50%, of which half of my servers exceed. Basically forcing an alert. There shouldn't be any fluctuation on this.

>  I decreased the repeat_interval to 30s as otherwise Alertmanager will wait 5 minutes before sending another notification.

After your comment, i updated it to this to test again: 
![image](https://user-images.githubusercontent.com/881986/133453035-4a1365e0-1172-4d67-baeb-6a6ffa7552c3.png)
![image](https://user-images.githubusercontent.com/881986/133453123-2d5c953c-c802-4402-8cc4-b5fc6f330aae.png)
 
And attempting to use `$values.B` in a label:
![image](https://user-images.githubusercontent.com/881986/133453296-4f648298-2156-493e-80df-973b7f046794.png)

This causes the instances that _should_ be alerting to be stuck in a Pending state
![image](https://user-images.githubusercontent.com/881986/133453666-3c3f628e-a4ce-45d7-8ea9-55db6f6f8497.png)
 
I do not see any reference to "{{ $values.B }}" in the logs.

I'm happy to try any settings that you think need to be tweaked.

**Comment by dadamssg** [comment] 2021-09-15 15:05
if i delete the label that contains the `{{ $values.B }}` and change nothing else, the alert gets reset and eventually goes into firing and i get the notification.

**Comment by gerobinson** [comment] 2021-09-15 15:46
@dadamssg using values in labels will create a new alert instance each time the value changes. It's not that the alerts are getting stuck in `pending`, it's that new alerts are being created and the old alerts are not getting updated, and so never transition from `pending` to `normal` or `firing`. You perhaps want to use it in an annotation instead?

**Comment by gerobinson** [comment] 2021-09-15 15:47
@dadamssg using values in labels will create a new alert instance each time the value changes. It's not that the alerts are getting stuck in `pending`, it's that new alerts are being created and the old alerts are not getting updated, and so never transition from `pending` to `normal` or `firing`.

**Comment by dadamssg** [comment] 2021-09-15 16:04
@gerobinson ooooh interesting. So is there not a way to get the value of a query into the notification if the values change during the duration of the **Evaluate** rule? Logically that makes sense now that i know that the alerts are being perpetually recreated _because_ of the reference to the value but that's kind of disappointing. 

If i want to alert on my filesystem space being above > 50%. It would be nice to see _how_ worried i need to be in the notification with an actual value being present.

**Comment by gerobinson** [comment] 2021-09-15 16:16
I think it's possible to put the value into an annotation and set a lower `repeat_interval` in the Alertmanager configuration in Grafana but that would affect all alerts, not just this one. However, the default `repeat_interval` of `5m` I think should be sufficient to get frequent notifications with up to date annotations (i.e. available disk space)?

**Comment by gerobinson** [comment] 2021-09-15 16:17
I think it's possible to put the value into an annotation and set a lower `repeat_interval` in the Alertmanager configuration in Grafana but that would affect all alerts, not just this one. However, the default `repeat_interval` of `5m` I think should be sufficient to get frequent notifications with up to date annotations (i.e. available disk space)?

**Comment by dadamssg** [comment] 2021-09-15 16:23
i guess i need to read up on annotations. From what i understand they're kind of like events(?). I'm not really sure how to set them up from prometheus data 🤔

**Comment by gerobinson** [comment] 2021-09-15 16:35
It's the same as custom labels, and custom annotations can also be templated with `{{ $values.B }}`. You can find it just above `Custom Labels` when configuring an alert rule.

**Comment by kylebrandt** [comment] 2021-09-15 16:37
> i guess i need to read up on annotations. From what i understand they're kind of like events(?). I'm not really sure how to set them up from prometheus data

Annotations configured on the alert rule add information to the alert. Those are not used for any sort of routing or anything like that, they added informational that can be displayed in the UI and Notifications. They are key/value like labels, but not used for grouping or routing.

**Comment by dadamssg** [comment] 2021-09-15 16:41
Oh perfect! I didn't realize _those_ were annotations. I definitely did not see the "and annotations" text. Just used it successfully to get the value in a notification!

**Comment by vfylyk** [comment] 2021-09-16 02:57
I am experiencing the same issue in version 8.1.3. I have removed the use of templates everywhere and played with the evaluation intervals, and still I get no notifications being fired. The logs show all alerts as being "resolved", as per the issue description. Going back to version 8.1.2 at any time fixes the issue.

**Comment by N3v3R3nD** [comment] 2021-09-16 11:18
The same issue with 8.1.4 had to revert to 8.1.2 to get it working.

**Comment by gerobinson** [comment] 2021-09-16 14:04
I think we should start a new issue for alert notifications not working in 8.1.3 and 8.1.4 when upgrading from 8.1.2 as I understand that is a different issue from what @dadamssg reported which was to do with using `$values` in custom labels.

**Closed by gerobinson** 2021-09-16 14:04 UTC
Labels: area/alerting, area/unified-alerting

**Comment by gerobinson** [comment] 2021-09-16 14:12
Let's move the discussion on missing alert notifications in 8.1.3 and 8.1.4 to #39295.
