### ISSUE TITLE
Log panel colorisation

### ISSUE THREAD

**Issue by ollie-campbell** [grafana/grafana#82368] opened 2024-02-13 11:57 UTC
**Why is this needed**:

The log panel only highlights a specific logging level using a small bar on the left hand side of the panel.

**What would you like to be added**:

There should be an option to highlight the entire line.

**Comment by usmangt** [comment] 2024-02-26 10:08
Hi @ollie-campbell,

Thanks for opening this issue.

I found this documentation that says that log level colors is also dependent on the labeling:

https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/logs/#log-level

**Comment by ollie-campbell** [comment] 2024-02-26 10:47
> Hi @ollie-campbell,
> 
> Thanks for opening this issue.
> 
> I found this documentation that says that log level colors is also dependent on the labeling:
> 
> https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/logs/#log-level

The logging colouring is working fine. The suggestion is to extend the colouring across the log text and not just have a small bar on the left hand side.

**Comment by usmangt** [comment] 2024-02-26 11:34
Hi @ollie-campbell 

This will be a feature request. It is now marked !!

**Comment by matyax** [comment] 2024-03-12 15:07
Thanks for opening this issue. Closing as duplicate of https://github.com/grafana/grafana/issues/82660

**Closed by matyax** 2024-03-12 15:07 UTC
Labels: type/feature-request, area/panel/logs, area/logs
