### ISSUE TITLE
Variable: Autocomplete does not support Korean

### ISSUE THREAD

**Issue by jooyg62** [grafana/grafana#91166] opened 2024-07-30 04:11 UTC
### What happened?

Details: Korean autocomplete works correctly in Grafana version 8, but it is not supported in versions 10 and 11.

![image (17)](https://github.com/user-attachments/assets/e3eb5518-b983-4854-a706-0030be73201e)
![image (16)](https://github.com/user-attachments/assets/1cb901bc-191b-4e3f-a2ae-d8b9d0e8a50c)

### What did you expect to happen?

Desired Outcome: Enable autocomplete support for Korean.

### Did this work before?

Details: Korean autocomplete works correctly in Grafana version 8, but it is not supported in versions 10 and 11.

### How do we reproduce it?

1. Enable autocomplete support for Korean.

### Is the bug inside a dashboard panel?

No, Dashboard Variable.

### Environment (with versions)?

Grafana: 10.3.3 & 11.X
OS: Windows 10
Browser: Google Chrome

### Grafana platform?

A downloaded binary

**Comment by ashharrison90** [comment] 2024-09-02 13:13
same root cause as https://github.com/grafana/grafana/issues/90459

closing as duplicate of this - looks like the dashboard team are aware and working on a fix 👍

**Closed by ashharrison90** 2024-09-02 13:13 UTC
Labels: area/internationalization
