### ISSUE TITLE
[Feature request] Highlight and focus on a horizontal slice of data

### ISSUE THREAD

**Issue by tgquan67** [grafana/grafana#11929] opened 2018-05-14 14:33 UTC
Version: 5
OS: Debian 9
Data source: InfluxDB
RIght now we can highlight a "vertical" slice of data (a.k.a. a timeframe) and have Grafana to focus on that. Can we apply that to the Y-axis to focus on a horizontal slice? There will be some data being left out of view but that will be helpful when the data have one huge spike and the rest are so small that are barely visible. I know that we can adjust the scale for Y-axis in a graph settings, but it's not really dynamic and intuitive.
P/s: a way to reset the view to default (for both horizontal and vertical slices) is also welcome.

**Comment by daniellee** [comment] 2018-05-18 07:58
Duplicate of #11910

**Comment by tgquan67** [comment] 2018-05-18 08:11
No I don't think it a duplicate of #11910 or any that comes before it. It's not about drawing a horizontal indicator, but about zooming into part of the data.

**Comment by daniellee** [comment] 2018-05-23 21:59
Sorry you're right. Reopening.

**Comment by marefr** [comment] 2018-10-10 16:44
Duplicate of #9457

**Closed** 2018-10-10 16:44 UTC
Labels: comp: panel/graph, type: feature request
