### ISSUE TITLE
OAuth Role mapping in 6.5 - Advanced example

### ISSUE THREAD

**Issue by synepolskyi** [grafana/grafana#20735] opened 2019-11-28 10:24 UTC
**What happened**:
The issue is related to new roles mapping functionality for Generic OAuth in Grafana version 6.5.
The advanced role mapping example from docs (https://grafana.com/docs/auth/generic-oauth/#role-mapping) does not seem to be correct.
```
Payload:
{
    ...
    "info": {
        ...
        "groups": [
            "engineer",
            "admin",
        ],
        ...
    },
    ...
}
Config:
role_attribute_path = contains(info.groups[*], 'admin') && 'Admin' || contains(info.groups[*], 'editor') && 'Editor' || 'Viewer'
```
If I'm not mistaken, the system will find `info.groups['admin']`, translate JMESPath expression to `'Admin'` and then will try to find role in nonexistent attribute `'Admin'`.

**What you expected to happen**:
Role 'Admin' is assigned on behalf of the 'admin' presence in 'info.groups'.

**How to reproduce it (as minimally and precisely as possible)**:
The following payload:
```
{
  ...
  "groups": [
    "grafana_editor",
    "grafana_admin"
  ]
}
```
and the JMESPath specified below:
```
role_attribute_path = contains(groups[*], 'grafana_admin') && 'Admin' || contains(groups[*], 'grafana_editor') && 'Editor' || 'Viewer'
```
have created user with role `'Viewer'`.

**Comment by sxd** [comment] 2019-11-29 18:30
I can confirm this bug

Looks more like an error in handling the raw data in 
[this line](https://github.com/grafana/grafana/blob/fad098c9d1f0a727c5342a25a94e8bb722a624f3/pkg/login/social/generic_oauth.go#L92) because it will always get an "Empty user info JSON response provided" 

Can you confirm @synepolskyi that you get the same error all the time?

Best Regards!

**Comment by orsanawwad** [comment] 2019-12-01 11:52
Currently on 6.4.2, having the same issue after integrating Oauth into grafana.

Payload example:

```
{
...
   "groups":[
      "/Grafana/Admin"
   ],
...
}
```
Expression in grafana.ini:

```
role_attribute_path: contains(groups[*], '/Grafana/Admin') && 'Admin' || contains(groups[*], '/Grafana/Editor') && 'Editor' || contains(groups[*], '/Grafana/Viewer') && 'Viewer'
```

Evaluating on jmespath.org results in the following:

```
"Admin"
```

So I assume that the expression is not the issue, but when logging in the role of the user gets set to Viewer, and I would have to login using the admin password to set it back to the correct role for that user.

@sxd I tried to look for what you suggested to @synepolskyi in my grafana instance logs but couldn't find such message, there are no errors at all.

When I login all I'm getting is this.

```
t=... lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=... time_ms=0 size=29 referer=
t=... lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=... time_ms=0 size=320 referer=...
t=... lvl=info msg="state check" logger=oauth queryState=... cookieState=...
t=... lvl=info msg="Successful Login" logger=http.server User=testuser@testuser.com
t=... lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=... time_ms=384 size=24 referer="..."
```

The payload for all of userinfo access_token id_token do include this groups array object.

So I assume it's something else other than the error mentioned above, its like grafana is not evaluating the expression at all since I don't see anything related to role assignments.

**Comment by sxd** [comment] 2019-12-01 12:14
@orsanawwad sadly you hvae to use 6.5.0 at least, because in 6.4.2 this feature it's not available :/ that's why you will not see the message I suggested to @synepolskyi 

@orsanawwad Can you try upgrading to 6.5.1? this latest version fix a few bugs

**Comment by orsanawwad** [comment] 2019-12-01 13:28
@sxd Right... didn't notice the note about version support in Grafana docs.

Either way, I upgraded to 6.5.1, I deleted all registered users from Grafana, assigned an admin role to it `["/Grafana/Admin"]`, logged in with it, still being assigned as Viewer.

However, I can confirm that I'm getting the exact same error as you mentioned:

```
t=... lvl=eror msg="Empty user info JSON response provided" logger=oauth.generic_oauth
```
The rest of the log is exactly the same as I wrote previously.

**Comment by sxd** [comment] 2019-12-02 11:10
@hypery2k maybe you can give us a hand here to understand what are we doing wrong ?

**Comment by synepolskyi** [comment] 2019-12-02 12:36
> I can confirm this bug
> 
> Looks more like an error in handling the raw data in
> [this line](https://github.com/grafana/grafana/blob/fad098c9d1f0a727c5342a25a94e8bb722a624f3/pkg/login/social/generic_oauth.go#L92) because it will always get an "Empty user info JSON response provided"
> 
> Can you confirm @synepolskyi that you get the same error all the time?
> 
> Best Regards!

You are right!
Also, I want to pay attention to the fact that the variable was named 'role_attribute_**path**' but jmespath expression returns **role**.

**Comment by marefr** [comment] 2019-12-02 12:40
@synepolskyi @sxd what OAuth provider are you using, an open id one like azure? 

I think that this may be related to #20300

**Comment by sxd** [comment] 2019-12-02 12:46
@marefr in my case I'm using Keycloak, if you think that maybe that PR will fix it I can try a version with that PR applied and then try to reproduce the issue, it's that ok with you? maybe @synepolskyi can do the same and try

**Comment by synepolskyi** [comment] 2019-12-02 12:57
@marefr I'm using OpenId client “webapplication” in Okta

**Comment by orsanawwad** [comment] 2019-12-02 13:10
@marefr I'm using Keycloak.

I tried running a local instance of Grafana from #20300 as you mentioned and seems like this fixes it, the roles gets assigned correctly now, plus it updates if I change the groups in Keycloak.

**Comment by sxd** [comment] 2019-12-02 13:18
@orsanawwad thanks!! =) 

@marefr well looks like there's a lot of people with the same issue and it's replicated :D looks like you put the milestone to 6.6 it is possible to move that to the next minor version?

**Comment by mgar** [comment] 2019-12-03 17:55
I'm getting the same `Empty user info JSON response provided` error with the following configuration:

```
[auth.generic_oauth]
api_url = https://example.okta.com/oauth2/v1/userinfo
auth_url = https://example.okta.com/oauth2/v1/authorize
token_url = https://example.okta.com/oauth2/v1/token
client_id = grafana
client_secret = secret
enabled = true
name = Okta
role_attribute_path = contains(groups[*], 'ADMIN') && 'Admin' || contains(groups[*], 'EDITOR') && 'Editor' || 'Viewer'
scopes = openid profile email groups
```

@synepolskyi since we both use and Okta implementation, do you mind sharing your configuration?

**Comment by synepolskyi** [comment] 2019-12-03 18:13
@mgar It's almost the same, really

**Comment by orsanawwad** [comment] 2019-12-03 18:21
I've built a Docker image for #20300 to temporarily fix it until it gets merged into a release.

You can find it here, https://hub.docker.com/layers/orsanawwad/grafana/20300/images/sha256-ebe68514c54cda80766fe8b23f24b887b1328780cd70108a09f6ddcd12b3fedc

I've used the same instruction in the developer's guide page.

Note: I do not recommend deploying WIP code for security reasons of course, so use the image at your own risk.

**Comment by marefr** [comment] 2019-12-03 21:10
Closing this in favor of #20243 since that was opened first and the PR we've discussed will close that issue. Let's continue discussions in that issue.

**Comment by marefr** [comment] 2019-12-03 21:10
Duplicate of #20243

**Closed by marefr** 2019-12-03 21:10 UTC
