### ISSUE TITLE
TypeError: n.state is null

### ISSUE THREAD

**Issue by yuvarajhere** [grafana/grafana#25201] opened 2020-05-28 21:14 UTC
**What happened**: Getting "An unexpected error happened TypeError: n.state is null" when using Transform function.

Screen capture:
<img width="315" alt="Screen Shot 2020-05-28 at 3 26 14 PM" src="https://user-images.githubusercontent.com/29648850/83194280-c54d1a00-a10e-11ea-8854-22c03ccd9350.png">

**What you expected to happen**: Normal output

**How to reproduce it (as minimally and precisely as possible)**:
- Add a new panel and update them with a prometheus query
- Change the visulization to Singlestat or Table
- Select reduce under transformation function
- Go back to Query tab and then try to select Transform tab. The error will be displayed. 
<img width="306" alt="Screen Shot 2020-05-28 at 6 11 49 PM" src="https://user-images.githubusercontent.com/29648850/83194295-cda55500-a10e-11ea-9096-bec3847c9b7d.png">

**Anything else we need to know?**: Tested this with v7.0.0 and getting the error only on the new version v7.0.0. Also, I tried this in two environments and getting the same error. 

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Prometheus
- OS Grafana is installed on: MacOS
- User OS & Browser: Firefox
- Grafana plugins: NA
- Others: NA

**Comment by zoltanbedi** [comment] 2020-05-28 21:20
> Fixed by #25152 , will come in patch 7.0.3 next week,
> But I would suggest download nightly to get fix right away: https://grafana.com/grafana/download/7.1.0-cdcd1ef9pre
> 
> Sorry for this, we added integration test for transforms so this does not happen again

Duplicate of #25122

**Closed by zoltanbedi** 2020-05-28 21:20 UTC
