### ISSUE TITLE
Plotly: Public Dashboard with TypeError: Cannot read properties of undefined (reading 'fields') 

### ISSUE THREAD

**Issue by ranayayas** [grafana/grafana#61896] opened 2023-01-21 15:24 UTC
**What happened**:
Hi, I am building a public dashboard with plotly panel and elasticsearch datasource.
When  I build the dashboard, make query to elasticsearch with metric of `rawdata`, the graph succesfully shown as below.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1107085/213873169-7089dc01-a5e2-4ede-9740-70a965d23060.png">

Here is the sample script using in the panel
<img width="517" alt="image" src="https://user-images.githubusercontent.com/1107085/213873817-ee59dfe5-2b8c-4764-8a48-a2e3d64a8d52.png">

However, when I export and make the dashboard public and access it,  there is a message of 
`TypeError: Cannot read properties of undefined (reading 'fields')  `in the panel. It seems that the data is not send to the public dashbord

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1107085/213873216-52c7e4d6-c192-4a4c-8b47-362d4efb7801.png">

Here is one of the script that can be executed in the dashboard but raise error when accessed from the public dashboard. 

`let pos  = data.series[0].fields[9].values.buffer[0]`

There is no `fields[9] `value, as  seen in developer console, when accessing the public version of dashboard.

Additional information: when query metric is `count`, the panel can be seen in public dashboard.
**Environment**:
- Grafana version: 9.2.1
- Data source type & version: Elasticsearch 8
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS and Chrome
- Grafana plugins: Plotly Panel
- Others: 

Any help is appreciated.

Regards
Widy

**Comment by zuchka** [comment] 2023-01-27 20:24
whicxh plotly panel are you using? there are at least three.

In any case, all three are third-party plugins not maintained by Grafana. If the error is specific to using that plugin, then you will need to make an issue in that plugin's repo. ❤️

**Comment by ranayayas** [comment] 2023-01-29 12:16
I am using Plotly panel by ae3e.

Actually the panel function normally as I can make a graph out of it. Even I can make publicdashboard if using metric of`count`.  But fail to make public dashboard if metric either `raw data` or `log`.
So it might be due to the way public dashboard and the panel communicate ...

**Comment by zuchka** [comment] 2023-02-01 00:38
it would be interesting to see if we could break a public dashboard just using ES raw data or log + the vanilla table panel, or time series panel. Then we could rule out plotly and this would fall under our area. B/c if it's just the plotly panel throwing the error, unfortunately there's little we can do...

**Comment by ranayayas** [comment] 2023-02-05 05:34
Dear @zuchka 

Using just ES raw data + vanila table panel got this
<img width="949" alt="image" src="https://user-images.githubusercontent.com/1107085/216803464-646ea158-e8b9-4f61-9460-da174a1a167c.png">

when I access the public dashboard version of the panel, got `no data` message
<img width="549" alt="image" src="https://user-images.githubusercontent.com/1107085/216803519-eb55fac1-f2a3-4651-9424-e78cab28cffe.png">

**Comment by gabor** [comment] 2023-02-20 07:18
@grafana/dashboards-squad this seems to be an issue with public-dashboards (considering it works with "normal" dashboards), but if there's anything the logs-squad can help with, just ping us 👍 .

**Comment by juanicabanas** [comment] 2023-04-04 18:44
See bug report https://github.com/grafana/grafana/discussions/49253#discussioncomment-4747692

**Comment by evictorero** [comment] 2023-05-23 21:11
Hi @ranayayas,  I'm trying to understand what the problem is and how to reproduce it. It seems to be a problem with Public dashboards and data source Elasticsearch right? In that case, maybe we can remove the Plotly panel from the title?
I made a public dashboard with the [gdev Elastic search provisioned dashboards](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#add-data-sources) and all panels worked as expected.
Can you help me to reproduce the error by sharing the dashboard JSON or explaining step by step how to create the panel that is failing?

**Comment by polibb** [comment] 2023-06-13 14:27
Hi @ranayayas, I'm closing this for now since we cannot reproduce the issue in question. 
If you're still experiencing this problem, please reopen this issue with more information as @evictorero suggested.

**Closed by polibb** 2023-06-13 14:27 UTC
Labels: needs more info, datasource/Elasticsearch, public-dashboards, triage/needs-confirmation, needs refinement
