### ISSUE TITLE
X-Grafana-User not sent since 9.0.0

### ISSUE THREAD

**Issue by mpitt** [grafana/grafana#54159] opened 2022-08-24 15:31 UTC
**What happened**:

After upgrading to 9.0.0, the `X-Grafana-User` header is not sent to datasources (Promehteus, Loki) despite having set [`send_user_header = true`](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#send_user_header)

**What you expected to happen**:

`X-Grafana-User` should be sent to datasources in the same way it was sent in 8.x.

**How to reproduce it (as minimally and precisely as possible)**:

On Grafana 9, set

```
[dataproxy]
send_user_header = true
```

in the configuration file, then check the headers sent to the datasource (e.g. use requestbin or capture traffic from Grafana to the datasource).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0 - 9.1.0
- Data source type & version: Prometheus, Loki
- OS Grafana is installed on: Ubuntu, Raspbian
- User OS & Browser: macOS/Chrome
- Grafana plugins:
- Others:

**Comment by gelicia** [comment] 2022-08-24 16:14
To triage: I'm not sure if this is an issue with the backend or individual datasources. The header gets added at `applyUserHeader` ([src](https://github.com/grafana/grafana/blob/062d255124160420f48c2af9a09a8cf89681369e/pkg/api/pluginproxy/utils.go#L91)) and I'm guessing the data sources apply it [here](https://github.com/grafana/grafana/blob/main/pkg/api/pluginproxy/ds_proxy.go#L224). I don't know enough about the internals to triage this further. Can you point this to the right team if this is not the right one?

**Comment by ve4eslav** [comment] 2022-08-30 11:01
The request is executed correctly and headers are transferred only when the datasource is created/tested.
But when a request is made on the dashboard or even to the "Explore", then all the headers are deleted.

when creating a datasource
```
GET /api/v1/status/buildinfo HTTP/1.1
Host: xxx.namespace.svc:8080
User-Agent: Grafana/9.1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,ru;q=0.9,en-US;q=0.8,en;q=0.7
Forwarded: for=n.n.n.n;host=DNS;proto=https
Sec-Ch-Ua: "Opera";v="89", "Chromium";v="103", "_Not:A-Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Forwarded-For: n.n.n.n, n.n.n.n, n.n.n.n
X-Grafana-Nocache: true
X-Grafana-Org-Id: 1
X-Grafana-User: test_user
```
when a request is made in the "Explore" section
```
GET /api/v1/label/__name__/values?start=1661852725&end=1661856325 HTTP/1.1
Host: xxx.namespace.svc:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.54
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Forwarded: for=n.n.n.n;host=DNS;proto=https
Sec-Ch-Ua: " Not A;Brand";v="99", "Chromium";v="104", "Opera";v="90"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Forwarded-For: n.n.n.n, n.n.n.n
X-Grafana-Org-Id: 1

POST /api/v1/query_range HTTP/1.1
Host: xxx.namespace.svc:8080
User-Agent: Grafana/9.1.1
Content-Length: 48
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip
```

My workaround for now is this, but it's not a production solution:
> in dev I build my grafana with the following changes in the file
`grafana/pkg/services/query/query.go
`
```
func (s *Service) handleQueryData(ctx context.Context, user *models.SignedInUser, parsedReq *parsedRequest) (*backend.QueryDataResponse, error) 
...
       if s.cfg.SendUserHeader && !user.IsAnonymous {
               req.Headers["X-Grafana-User"] = user.Login
       }

	for k, v := range customHeaders(ds.JsonData, instanceSettings.DecryptedSecureJSONData) {
		req.Headers[k] = v
	}
...
```
It works as described in the official documentation.
send_user_header
If enabled and user is not anonymous, data proxy will add X-Grafana-User header with username into the request. Default is false.

Because of this problem, it's impossible to implement multi-tenancy or other feature where it's required to understand which user is making the request.

**Comment by thethir13en** [comment] 2022-09-07 08:54
Hello, 
on my project we're expecting same problem with team.

This functionality seems broken :(

**Comment by mildwonkey** [comment] 2022-09-07 16:36
I'm looking into this! I'm going to capture my triage notes so I can follow up with my team to determine the correct solution - as others have noted, it's not immediately clear where the fix should be. 

--------
triage notes for myself!

The custom header is specific to the datasource proxy API and only applied to those requests: https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#data-source-proxy-calls

The query service doesn't go through the datasource proxy; [this commit](https://github.com/grafana/grafana/commit/87afd9cadc490205b44a773a9ce4acf9874779c3) could be where the issue started, though the bug might actually live elsewhere (the middleware).

**Comment by ve4eslav** [comment] 2022-09-07 16:46
I'm only talking about the "X-Grafana-User" header. In the code snippet above, the custom_header is only displayed to show where I pasted my code. The code that inserts the service header of the Grafana itself. 
```
if s.cfg.SendUserHeader && !user.IsAnonymous {
               req.Headers["X-Grafana-User"] = user.Login
       }
```

A custom header is completely different, and we are not interested in this case.

**Comment by mildwonkey** [comment] 2022-09-29 13:52
@grafana/observability-experience-squad We're seeing this behavior specifically in the datasource Explore panel. Do you have more context on that method? It isn't going through the datasource proxy. (and sorry if I tagged the wrong squad!)

**Comment by gabor-grafana** [comment] 2022-10-04 07:07
hi @mildwonkey , Prometheus & Loki do not use the datasource-proxy in 9.1.x, they have their own backend code, doing the usual "get the http client provider in ProvideService" etc.

to me it seems the generic backend code should add this header, not every datasource separately. what do you think?

**Comment by mildwonkey** [comment] 2022-10-05 14:38
Thanks @gabor-grafana, that helps. So this is a regression in the prometheus & loki integrations, and I agree that the most likely solution is along the lines of a middleware to handle that header. 
I'll flag this as both a bug (regression in the datasources not using the proxy) and a feature request for a new middleware.

**Comment by marefr** [comment] 2022-10-12 21:01
I would say this is a duplicate of https://github.com/grafana/grafana/issues/47734 and we probably should close this. It's something @grafana/plugins-platform-backend have planned to fix - see issue for details.

**Comment by mildwonkey** [comment] 2022-10-13 12:36
closing in favor of #47734

**Closed by mildwonkey** 2022-10-13 12:36 UTC
Labels: area/backend/plugins, area/datasource/backend
