### ISSUE TITLE
Alerts "Recent state changes" panel not refreshing when updating time range

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#41925] opened 2021-11-18 20:42 UTC
**What happened**:
Alerts list visualization configured to display "Recent state changes" is not refreshing when updating time range, it only picks up the new range when performing page reload via browser.

**What you expected to happen**:
Not having to manually reload the page via browser to view the recent alerts' state changes when selecting a new time range.

**How to reproduce it (as minimally and precisely as possible)**:
Assuming default time range `from=now-1h&to=now`, and having one recent alert state changed 12 hours old it will not be shown when time range gets updated to e.g. `Last 24 hours` - reloading the page after selecting the new time range will correctly display all alert changes from `Last 24 hours`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: CloudWatch
- OS Grafana is installed on: linux (docker)
- User OS & Browser: Win10 & Chrome96
- Grafana plugins: n/a
- Others: official grafana docker image

**Comment by mckn** [comment] 2021-11-19 12:35
Thanks for reporting this. Looks like we are missing the time range in the list of dependencies here:

https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/alertlist/AlertList.tsx#L67

**Comment by peterholmberg** [comment] 2021-11-25 15:00
possible duplicate of https://github.com/grafana/grafana/issues/36165

**Closed** 2021-11-29 09:22 UTC
Labels: type/bug, area/alerting, area/panel/alertlist, area/alerting/unified
