### ISSUE TITLE
Flux (InfluxDB) Panel Queries: Incorrect comment syntax coloring and shortcut gives incorrect comment syntax

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#72046] opened 2023-07-20 17:02 UTC
### What happened?

If I have a Flux query like
```
from(bucket: "my_bucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "my_measurement")
```
and I enter `ctrl+/` on a line, the line gets prepended with `-- ` and the syntax coloring is changed to reflect a comment. But `-- ` is not correct Flux comment syntax.

If I manually put `// `, the correct comment syntax, at the beginning of a line, the syntax coloring does _not_ change like it should.

### What did you expect to happen?

I expect the line I want to be commented out to be prepended with `// `.
If a line starts with `//`, the line syntax color should reflect that the line is commented out.

### Did this work before?

I did not try in previous versions.

### How do we reproduce it?

1. Setup an InfliuxDB data source configured to use Flux, not InfluxQL, as the query language.
2. Create a panel using that data source and enter a Flux query.
3. With your cursor on a line of the query, hit `ctrl+/` and see that `-- ` is added where `// ` should instead be added.

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | timeseries @ 10.0.2 |
| Grafana | 10.0.2 (b2bbe10fbc) // Enterprise |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": "linear",
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 0,
            "gradientMode": "none",
            "spanNulls": false,
            "showPoints": "auto",
            "pointSize": 5,
            "stacking": {
              "mode": "none",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "#0066ff40",
                "value": null
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        }
      },
      "pluginVersion": "10.0.2",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "typeVersion": [
                    0,
                    0
                  ],
                  "executedQueryString": "from(bucket: \"my_bucket\")\r\n  |> range(start: 2023-07-20T11:02:04.877Z, stop: 2023-07-20T17:02:04.877Z)\r\n  |> filter(fn: (r) => r._measurement == \"my_measurement\")"
                },
                "fields": []
              },
              "data": {
                "values": []
              }
            }
          ]
        }
      ],
      "transformations": [],
      "type": "timeseries",
      "description": "",
      "title": "Reproduced with embedded data"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 10.0.2</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[influxdb]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td></td>\n  </tr>\n    <tr><th>Data</th><td>Error 1 frames, 0 fields, 0 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>10.0.2 (b2bbe10fbc) // Enterprise</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"uid\": \"abdf7929-2831-4020-8ed0-8c4169de87b2\",\n    \"type\": \"influxdb\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": \"linear\",\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 0,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"showPoints\": \"auto\",\n        \"pointSize\": 5,\n        \"stacking\": {\n          \"mode\": \"none\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"off\"\n        }\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"#0066ff40\",\n            \"value\": null\n          }\n        ]\n      },\n      \"unit\": \"none\"\n    },\n    \"overrides\": []\n  },\n  \"gridPos\": {\n    \"h\": 4,\n    \"w\": 6,\n    \"x\": 0,\n    \"y\": 7\n  },\n  \"id\": 33,\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    }\n  },\n  \"pluginVersion\": \"10.0.2\",\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"influxdb\",\n        \"uid\": \"abdf7929-2831-4020-8ed0-8c4169de87b2\"\n      },\n      \"hide\": false,\n      \"query\": \"from(bucket: \\\"my_bucket\\\")\\r\\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\\r\\n  |> filter(fn: (r) => r._measurement == \\\"my_measurement\\\")\",\n      \"refId\": \"A\"\n    }\n  ],\n  \"transformations\": [],\n  \"type\": \"timeseries\",\n  \"description\": \"\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: undefined // 2023-07-20 17:02:09",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2023-07-20T11:02:09.171Z",
    "to": "2023-07-20T17:02:09.171Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 10.0.2
OS: Windows 11
Browser: Microsoft Edge Version 114.0.1823.82 (Official build) (64-bit)

### Grafana platform?

None

### Datasource(s)?

InfluxDB

**Comment by gpinkos** [comment] 2023-07-26 10:56
I believe [this is the area of documentation](https://grafana.com/docs/grafana/latest/datasources/influxdb/query-editor/#flux-query-editor) that should address this issue.

I concur that the rendering of Flux comments (which is preceeding the line with two slashes, i.e. // ) has never worked correctly in Grafana.   One has to manually type them.  In addition, it does not gray out the text like it does when using the query editor in InfluxDB.

Example of a commented line in InfluxDB (commented line was inserted using ctrl+/ )
![image](https://github.com/grafana/grafana/assets/97072938/b2c6f422-1db2-4552-8f1f-63e07bd4c5c8)

Example of using ctrl+/ to comment out the line of code in Grafana, which incorrectly inserts -- instead of //
![image](https://github.com/grafana/grafana/assets/97072938/231a8a0d-7500-491a-a4be-672f2adb7023)

Correctly commented out line of code in Grafana (created by manually typing the slashes):
![image](https://github.com/grafana/grafana/assets/97072938/6c41af3c-7962-4b60-ac76-967ce93d9d77)

**Comment by itsmylife** [comment] 2023-08-01 15:08
Duplicate of https://github.com/grafana/grafana/issues/59407

**Closed by itsmylife** 2023-08-01 15:08 UTC
Labels: datasource/InfluxDB, prio/low, effort/large
