### ISSUE TITLE
BarGauge: Filling problem when using Total calculation

### ISSUE THREAD

**Issue by eledobleefe** [grafana/grafana#60797] opened 2022-12-28 15:09 UTC
**What happened**:
The Bar Gauge is completely full for all bars when using the Total calculation:
![image](https://user-images.githubusercontent.com/49911675/208935546-123c7e94-0380-4cb8-8b2c-87a24057649e.png)
It works as expected when using Last, Min or Max:
![image](https://user-images.githubusercontent.com/49911675/208935430-d1386189-1b6d-489f-a440-14f73b4ff29f.png)

**What you expected to happen**:
The bars should be filled according to the percentage of their value.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a dashboard with the TestDataDB data source
2) Create a Bar Gauge panel
3) Set the calculation to `Total`.

Here is a dashboard JSON that can be used to reproduce the issue.
[Bar Gauge Total-1671634659088.zip](https://github.com/grafana/support-escalations/files/10278756/Bar.Gauge.Total-1671634659088.zip) 

**Anything else we need to know?**:
Seems it also happens in `Gauge`.

**Environment**:
- Grafana version: reproduced in 8.5.5, 9.1.0, 9.2.0, 9.3.2 and 9.4.0
- Data source type & version: TestDataDB
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by JoaoSilvaGrafana** [comment] 2023-02-28 14:53
We investigated this today and we believe this happens by design. Selecting a calculation does not change the underlying data of the panel, which is used to determine the min/max values, it only affects what is displayed.
If we want to update the data, therefore using that to calculate min/max, we can do it in one of two ways:
- Add a "Reduce" transformation with "Total" calculation
- Add a query expression that sums the value of each of the series

Since there are 2 ways of accomplishing what is asked in this issue, we will be closing it.

**Closed by JoaoSilvaGrafana** 2023-02-28 14:53 UTC
Labels: area/frontend, area/panel/bargauge, mob-friendly

**Comment by Falmarri** [comment] 2023-10-03 22:43
This is very unsatisfying. If this is by design, the design of this gauge is flawed. Why would it even default to "Last" anyway? That is very unintuitive, and I'll bet most people using this panel would be surprised by that, like I was.
