### ISSUE TITLE
Alert sources result in Permission denied when clicking

### ISSUE THREAD

**Issue by hdost** [grafana/grafana#26931] opened 2020-08-11 15:21 UTC
**What happened**:
When clicking on the sources to an alert it takes me to the dashboard, but does not direct me to the panel and instead displays a permission denied.

**What you expected to happen**:
When clicking on the link it should show a zoomed in version of the panel which triggered the alert.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a dashboard
2. Create an alert pointing to a target (in our case alertmanager -> opsgenie)
3. Trigger alert
4. Click on Sources link.
5. See permission denied message

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: Grafana 7.1.3
- Data source type & version: Graphite 1.x
- OS Grafana is installed on: Centos 7
- User OS & Browser: All
- Grafana plugins: Irrelevant
- Others:

**Comment by sakjur** [comment] 2020-08-11 17:05
Thank you for your bug report.

Based on the attached PR (:pray: thank you!), it seems like this might just be reproducible if the logged in user doesn't have edit perms to the dashboard if I understand this correctly. Since the link goes to the edit view, that makes sense.

Possible workaround would be to enable `viewers_can_edit` which allows viewers access to those views but not to save any dashboards.

**Comment by hdost** [comment] 2020-08-11 17:15
So this is an issue if you have dashboards as un-editable also.

**Comment by aenima-x** [comment] 2020-08-14 12:46
I was gonna open an issue about that the link is going to de edit view, that changed.
It already have a button to de edit view, the default action of the link should be to "view" not edit.

**Comment by torkelo** [comment] 2020-09-25 06:52
This was fixed in 7.2 via this PR, https://github.com/grafana/grafana/pull/27378 

That changes the link in the notifications to go to panel view mode instead of edit mode

**Closed** 2020-09-28 08:59 UTC
Labels: area/alerting/notifications, area/permissions, type/bug
