### ISSUE TITLE
Visualization: Stats Panel: Display label value

### ISSUE THREAD

**Issue by trallnag** [grafana/grafana#25480] opened 2020-06-09 11:41 UTC
**What would you like to be added**:

Add `name` support to Stats panel similar to the option available with the now depreciated Single Stats panel. This is helpful when visualizing textual information, for example the build version of my Prometheus.

**Why is this needed**:

This right here is not possible in Grafana 7:

https://play.grafana.org/d/77d47mNik/prometheus-singlestat-label-value?orgId=1

This has also been mentioned in a few other places:

https://github.com/grafana/grafana/issues/5094#issuecomment-638743730
https://community.grafana.com/t/extract-labels-values-from-prometheus-metrics/2087/10

**Comment by torkelo** [comment] 2020-06-10 07:24
duplicate of https://github.com/grafana/grafana/issues/24076

**Closed by torkelo** 2020-06-10 07:24 UTC
