### ISSUE TITLE
[Feature Request] Alertmanager notifier support

### ISSUE THREAD

**Issue by iksaif** [grafana/grafana#7534] opened 2017-02-12 15:50 UTC
cc: @Thib17 

It would be great to make Grafana able to send alert to a prometheus alertmanager. This would allow the alertmanager to do grouping / de-duplication / inhibition before going further (like OpsGenie or similar).

This would also make https://github.com/grafana/grafana/issues/6957 less annoying.

Links:
* Prometheus Alertmanager Clients: https://prometheus.io/docs/alerting/clients/
* Grafana notifications: http://docs.grafana.org/alerting/notifications/
* Grafana notifiers: https://github.com/grafana/grafana/tree/master/pkg/services/alerting/notifiers

**Comment by bergquist** [comment] 2017-02-12 20:23
Dupe of https://github.com/grafana/grafana/issues/7481 :)

**Closed by bergquist** 2017-02-12 20:23 UTC
