### ISSUE TITLE
Support requesting only active tags from influxdb in a time range

### ISSUE THREAD

**Issue by mkutsevol** [grafana/grafana#7918] opened 2017-03-23 13:21 UTC
Partially it touches #5327 #1322

**The problem**: 
I use kubernetes and heapster+influxdb+grafana to monitor usage

As a part of normal workflow k8s pods are born and die and after some time I have lots of inactive pod_name tags in the database. They will never be reused and it alone renders grafana templating unusable. It just returns 10k tags for one pod type. 

**The solution**: 
Add support for $timeRange and column selection in templating queries

**PR is coming in an instant**

**Comment by kareem613** [comment] 2018-05-02 21:10
This looks like it was already done for postgres and mysql. 
https://github.com/grafana/grafana/pull/10071
https://github.com/grafana/grafana/pull/10069

This would be very useful for influxdb as well. I haven't tried any development on this project, but @torkelo , if you can point me in the right direction I can try.

Does adding the filter go in datasource.ts  metricFindQuery or in the queryBuilder? Am I on the right track?

**Comment by akilan27** [comment] 2018-06-27 15:49
Without the ability to add $timeRange to query the refresh 'On Time Range Change' option in the template variable settings is basically pointless. Please bring this in.

**Comment by voiprodrigo** [comment] 2018-08-29 18:33
This feature would be much appreciated.

**Comment by MichaelCosby** [comment] 2018-09-16 05:38
It looks like #12598 (coming in grafana 5.3) solves this, possibly

**Comment by akilan27** [comment] 2018-09-16 15:10
> It looks like #12598 (coming in grafana 5.3) solves this, possibly

It does seem so. Excellent work. I will test it and comment here.

**Comment by stefanbie** [comment] 2019-03-14 10:10
Hi!
I have tried this in v5.4.2:
SHOW TAG VALUES WITH KEY = "domain" WHERE $timeFilter
..but I get the error message:
"Template variables could not be initialized: error parsing query: missing parameter: timeFilter"
Have I misunderstood it?

**Comment by stefanbie** [comment] 2019-03-21 10:23
Also tried with "SELECT "xxx" FROM "yyy" WHERE $timeFilter" in grafana 6.0.2 and got the same error:

"Template variables could not be initialized: error parsing query: missing parameter: timeFilter"

...so I guess $timeFilter is still not supported in template variables?

**Comment by bdeam** [comment] 2019-05-28 23:38
> Also tried with "SELECT "xxx" FROM "yyy" WHERE $timeFilter" in grafana 6.0.2 and got the same error:
> 
> "Template variables could not be initialized: error parsing query: missing parameter: timeFilter"
> 
> ...so I guess $timeFilter is still not supported in template variables?

You'll need to set your Query Refresh to "On Time Range Change". Should do the trick :)

**Comment by bewing** [comment] 2019-07-01 15:02
Will this actually work?  My testing shows that the WHERE clause is ignored when doing "SHOW TAG VALUES", and the documentation appears to back that:

https://docs.influxdata.com/influxdb/v1.7/query_language/schema_exploration/#show-tag-values

> The FROM, WHERE, LIMIT, and OFFSET clauses are optional. The WHERE clause supports tag comparisons; **field comparisons are not valid** for the SHOW TAG KEYS query.

**Comment by bewing** [comment] 2019-07-01 15:14
The workaround appears to involve subqueries, and retrieves every point in the timeFilter -- grafana handles the de-dupe

`SELECT "tag" FROM (SELECT "field", "tag" FROM "table" WHERE $timeFilter)`

**Comment by davidnewhall** [comment] 2019-08-16 19:37
It's not clear to me how this is a Grafana issue; this is an InfluxDB issue. InfluxDB does not support filtering by field values when `SHOW`ing tags, that includes the `time` field. The `SELECT` operation, of course, does support filtering by fields, but it's reeeeaaaallly slow if you have a lot of data snd set your time range to a long duration.

I think the fix is going to be convincing InfluxDB devs to create another index on tags+time so these can be filtered quickly. I don't believe Grafana devs can't fix this problem. 

I can confirm the workaround mentioned above does work. Until you select a year of data on a large database. Good luck!

**Comment by hugohaggmark** [comment] 2020-11-11 13:50
Hi everyone :) 

I'm very late to the game here, but as I read through all this and follow all the links in the issue, it seems like this is both an issue with the Influx Query language and partially already fixed in later versions of Grafana. 

So I'm going to close this issue now because we're trying to limit open GitHub issues in order to better track planned work and features. If you feel like this is wrong for some reason, please let me know, thank you.

Thank You to you for taking the time to create this issue!

**Closed by hugohaggmark** 2020-11-11 13:50 UTC
Labels: type/feature-request
