### ISSUE TITLE
Graph panel with query "Mixed" shows the resulting values in the legend in a random order.

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#21660] opened 2020-01-22 08:58 UTC
**What happened**:
Graph panel with query - Mixed - shows the resulting values in the legend in a random order.

**What you expected to happen**:
The sorting result should always be the same, even with multiple data sources in one panel.

**How to reproduce it (as minimally and precisely as possible)**:
Use a graph panel with two datasources in "Mixed" mode. 
Each datasource should show two values.

**Anything else we need to know?**:
Reload in browser and have a look at the sorting order.

**Environment**:
- Grafana version: 6.5.3
- Data source type & version: NetXMS v1.2.1
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: ---
- Others:

Graph panel with query - Mixed - shows the resulting values in the legend in a random order.
It depends on which datasource answers first.

The incoming results of all data source queries should first be collected, then
sorted and then be output. The sorting result should always be the same, even
with multiple data sources in one panel.

My datasoures are: NetXMS server1 and NetXMS server2

My queries are:

A NetXMS server1
Target server 11
DCI: CPU:usage
Legend: server11

B NetXMS server2
Target server 12
DCI: CPU:usage
Legend: server12

C NetXMS server1
Target server 13
DCI: CPU:usage
Legend: server13

D NetXMS server2
Target server 14
DCI: CPU:usage
Legend: server14

Legend after first page load:
server 12 server 14 server 11 server 13

page reload:
server 11 server 13 server 12 server 14

page reload:
server 12 server 14 server 11 server 13

**Comment by torkelo** [comment] 2020-01-22 09:07
duplicate of https://github.com/grafana/grafana/issues/20555

**Closed by torkelo** 2020-01-22 09:07 UTC
