### ISSUE TITLE
Password reset via CLI not working

### ISSUE THREAD

**Issue by seallard** [grafana/grafana#17594] opened 2019-06-15 08:43 UTC
**What happened**:
Admin password did not change using the [CLI command](https://grafana.com/docs/administration/cli/):
sudo grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" newpass
Returns "Admin password changed successfully ✔", despite password not being changed. 

**What you expected to happen**:
Admin password changed to newpass.

**How to reproduce it (as minimally and precisely as possible)**:
sudo grafana-cli admin reset-admin-password --homepath "/usr/share/grafana" newpass

**Anything else we need to know?**:
The password can be changed by editing grafana.ini as described [here](https://github.com/grafana/grafana/issues/1815#issuecomment-412397098). 

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: None
- OS Grafana is installed on: Ubuntu 18.04.2
- User OS & Browser: Ubuntu, Firefox
- Grafana plugins: None
- Others: None

**Comment by bergquist** [comment] 2019-06-15 09:48
Dupe of https://github.com/grafana/grafana/issues/12638

**Closed by bergquist** 2019-06-15 09:48 UTC
