### ISSUE TITLE
share: link Copy button doesn't work

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#45382] opened 2022-02-15 08:28 UTC
**What happened**:
regression: Copy button in Share / Link doesn't work.  Even though it pops up "Content copied to clipboard" nothing is copied.

**What you expected to happen**:
copy the link

**How to reproduce it (as minimally and precisely as possible)**:
1. put some random text into your clipboard
2. open grafana Share or Share Panel dialog
3. under Link, hit Copy button
4. paste clipboard --> original text from (1) is pasted

**Anything else we need to know?**:
I could not reproduce it at play.grafana.org (v8.4.0-beta1).  However, no bug fix was mentioned in the 8.4.0 changelog.  If it was fixed, it should be noted, and backported to v8.3.

**Environment**:
- Grafana version: v8.3.6
- User OS & Browser: macOS 10.15.7 / Chrome 97.0.4692.99

**Comment by zoltanbedi** [comment] 2022-02-15 10:22
Duplicate of #44110

**Closed by zoltanbedi** 2022-02-15 10:22 UTC
