### ISSUE TITLE
Password works only in UI not in Provisioning

### ISSUE THREAD

**Issue by Grey2k** [grafana/grafana#17833] opened 2019-06-28 23:08 UTC
**What happened**:

Im using same config

```yml
# # config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: mysql_grafana

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: mysql_grafana
    # <string, required> datasource type. Required
    type: mysql
    # <string, required> access mode. direct or proxy. Required
    access: direct
    # <string> url
    url: mysql
    # <bool> mark as default datasource. Max one per org
    isDefault: false
    # <bool> allow users to edit datasources from the UI.
    editable: true
    database: "grafana"
    user: "grafana"
    secureJsonData:
      password: "p!@8sword"
```

After start - data source available but password is incorrect, after i copy and paste it in UI - its start work.  What i doing wrong - i checked 5 times - its the same password

**What you expected to happen**:

Data source will be correct

**How to reproduce it (as minimally and precisely as possible)**:

Use this config on 6.2.5 version Grafana.

Also a see that encrypted password in DB changes after i enter it through UI.
May be issue related with secure_key?

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: mysql percona 8.0.13-4.1.el7
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-07-01 07:53
Unable to replicate :( 

Works when I test here, can you test with a different password?

**Comment by marefr** [comment] 2019-07-09 15:39
Think this is a duplicate of #17986 but not sure

**Comment by marefr** [comment] 2019-08-07 13:40
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Closed by marefr** 2019-08-07 13:40 UTC
Labels: area/provisioning, datasource/MySQL, needs more detail

**Comment by carlosrbcunha** [comment] 2023-05-17 16:24
I have the same problem. 
I create, via provisioning the datasource, put the basicAuthPassword in the secureJsonData section and the connection does  not work. 
I reset the password in the UI and all works. 
Is there any type of encoding that we need to use when storing the credentials in the configuration file ??

**Comment by marefr** [comment] 2023-05-17 16:46
@carlosrbcunha see https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file. There's a basicAuth boolean flag you need to set to true.

**Comment by marefr** [comment] 2023-05-22 14:25
@carlosrbcunha feel free to provide your provisioning file (removing any sensitive information) here. In general, would suggest inspecting the network request when creating/updating your datasource via the UI using something like Chrome Developer Tools and the network tab and inspect the payload.
