### ISSUE TITLE
Grafana 7 Slack alerts issue

### ISSUE THREAD

**Issue by YakobovLior** [grafana/grafana#25327] opened 2020-06-03 15:01 UTC
Hello,
we have upgraded our Dev environment to Grafana 7.0.1 and looks like there is an issue with the alerting to Slack, the text shown twice - one as plain text, and once again in the Grafana text with the color of the alert status.

First image: alert from Grafana 6.6.0
![image](https://user-images.githubusercontent.com/33580144/83653051-fd97a100-a5c3-11ea-9801-84573d9152bb.png)

Second image: alert from Grafana 7.0.1, marked the repeated text in red
![image](https://user-images.githubusercontent.com/33580144/83653213-27e95e80-a5c4-11ea-97be-1c55efe259a6.png)

Is there a configuration that needs to be changed in order to prevent this?

Thanks,
Lior

**Comment by kylebrandt** [comment] 2020-06-04 12:12
Duplicate of https://github.com/grafana/grafana/issues/24495

**Closed by kylebrandt** 2020-06-04 12:12 UTC
