### ISSUE TITLE
About Chinese i18n

### ISSUE THREAD

**Issue by HaoLi-Rainbow** [grafana/grafana#36771] opened 2021-07-15 01:22 UTC
**What would you like to be added**:
About Chinese i18n
**Why is this needed**:
grafana is a very good software, but the big software when it becomes famous will provide rich i18n, I think grafana should do the same, so it can also increase the visibility of grafana. Why not?

**Comment by zoltanbedi** [comment] 2021-07-15 07:27
Duplicate of https://github.com/grafana/grafana/issues/448

**Closed by zoltanbedi** 2021-07-15 07:27 UTC
