### ISSUE TITLE
Feature : Ability to create variable on "Team" Level or "user" level to override variables on dashboards

### ISSUE THREAD

**Issue by konvergence** [grafana/grafana#11586] opened 2018-04-13 14:37 UTC
Please include this information:
### If related to metric query / data viz: ; no

With grafana 5.0 there is a good feature : folders, teams and access rights
But to be able to present a dashboard, without the same variables values, I need to duplicate dashboard for each team.

If we could define variables on “team” or “user” level, it could overwrite the variables on dashboard.
So I could manage only one dashboard, but restrict the vision according to the variables overwrited from team or user

see : https://community.grafana.com/t/ability-to-create-variable-on-team-level-or-user-level-to-override-variables-on-dashboards/6798

**Comment by bergquist** [comment] 2018-04-16 06:00
Dupe of https://github.com/grafana/grafana/issues/1959

**Closed by bergquist** 2018-04-16 06:00 UTC
