### ISSUE TITLE
Graph with Y-axis as time & X-axis as Value

### ISSUE THREAD

**Issue by mohanraj1939** [grafana/grafana#11808] opened 2018-05-03 07:27 UTC
Hi @torkelo   or all,

Please include this information:
### What Grafana version are you using?
Grafana V 5.0.4(commit: 7dc36ae)
### What datasource are you using?
Simple JSON
### What OS are you running grafana on?
Ubuntu 16.04
### What did you do?

I have to graph with values (Time,value1) and (value1, value2) where value1 is common in both the metrics so i decided to plot Value 1 in X-axis and Time in Left Y-axis and Value 2 In Right Y-axis

### What was the expected result?

To show time series in Y-axis & Values in X-axis.

### What happened instead? 

Time series in X-axis & Values in Y-axis.

**Comment by mohanraj1939** [comment] 2018-05-04 09:36
![grafana](https://user-images.githubusercontent.com/33648564/39621475-8c34a9fa-4fac-11e8-8e47-cc36166dc87b.png)

Left Y-axis- Time Series
Right Y-axis- Value 2
X-axis- Value 1

**Comment by marefr** [comment] 2018-05-04 11:11
Duplicate of #7158

You can maybe experiment with X-Axes mode=series, but you won't be able to create such a graph in Grafana currently.

**Closed by marefr** 2018-05-04 11:11 UTC
Labels: state: needs more detail
