### ISSUE TITLE
Grafana instance IP being added while navigating to external URL through Data link

### ISSUE THREAD

**Issue by ekragan** [grafana/grafana#47847] opened 2022-04-18 13:00 UTC
I have added an external Jenkins link to one of the cells in Grafana panel using Feature DATA LINK which was working properly before.
We have recently upgraded to 8.4.6 from 8.2
The syntax used is : ${__data.fields["Job Url"]}

When we click on the field , the Url address changes to x.x.x.x/https://testsomethingabc.com
where as previously it was navigating easily to correct address which is https://testsomethingabc.com
Here  x.x.x.x is the IP address of Grafana instance

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Influx DB
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac, windows, Chrome
- Grafana plugins: None
- Others:

**Comment by joshhunt** [comment] 2022-04-21 10:09
Thanks for reporting!

Duplicate of https://github.com/grafana/grafana/issues/46817, already fixed by https://github.com/grafana/grafana/pull/47763 😌

**Closed by joshhunt** 2022-04-21 10:09 UTC
