### ISSUE TITLE
Time series panel - time axis does not autoscaling

### ISSUE THREAD

**Issue by Zhankin** [grafana/grafana#31920] opened 2021-03-11 18:42 UTC
Grafana 7.4.3
Panel - Time series 
Data Source - Postgres
OS Grafana is installed on: Docker image based on grafana/grafana:7.4.3.
User OS & Browser: Ubuntu 20.4, Chrome Version 89.0.4389.72 (Official Build) (64-bit)

Some times X axis showing in incorrect format

![image](https://user-images.githubusercontent.com/23161328/110837302-3f7c1300-82cb-11eb-8ab3-24443d5a20c6.png)

But if I change the time period to more days it works fine
![image](https://user-images.githubusercontent.com/23161328/110837323-473bb780-82cb-11eb-9b03-4eaf9a647af1.png)

![image](https://user-images.githubusercontent.com/23161328/110837456-70f4de80-82cb-11eb-93c3-d455c6690132.png)

**Comment by leeoniya** [comment] 2021-03-11 18:56
this was fixed recently in https://github.com/grafana/grafana/pull/31332, try 7.5.0-beta1

**Comment by leeoniya** [comment] 2021-03-11 18:57
Duplicate of https://github.com/grafana/grafana/issues/30906

**Closed** 2021-03-11 18:56 UTC
