### ISSUE TITLE
Variable not working within transform rename

### ISSUE THREAD

**Issue by shaunroselt** [grafana/grafana#61239] opened 2023-01-10 16:20 UTC
**What happened**:
I am trying to do a transform rename on a field and replace it with a name from my dashboard variables, but it's not working. It's using my variable as plain text instead of using it as a variable

**What you expected to happen**:
I would expect for it to use the value from the variable that I'm specifying

**How to reproduce it (as minimally and precisely as possible)**:
Create a variable with a value in it. Then try to do a field rename transform and set it to that variable

**Anything else we need to know?**:

Here's a screenshot of what I'm doing:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/5418178/211604802-f49793d6-2f07-4faf-b6f9-724f5e9a7e8e.png">

You can see at the top that it is using the variable name as text instead of actually getting the value of the variable. Am I missing something or is this a bug?

**Environment**:
- Grafana version: 9.3.1
- OS Grafana is installed on: Windows Server 2022
- User OS & Browser: Windows 11 & Microsoft Edge

**Comment by shaunroselt** [comment] 2023-01-10 16:53
<img width="934" alt="image" src="https://user-images.githubusercontent.com/5418178/211613235-bbdada55-4d5e-4e37-a0e4-101a96fbf637.png">

Transform Rename by Regex is also not working with variables. I want to check for "Speed" and then replace it with the value from my ${lang_speed} variable.

**Comment by usmangt** [comment] 2023-01-11 09:44
Hi @shaunroselt,

Thanks for opening this issue.

Could you please tell us what is the Datasource you are using when performing the Transform operation on the query?

**Comment by shaunroselt** [comment] 2023-01-11 13:05
> Hi @shaunroselt,
> 
> Thanks for opening this issue.
> 
> Could you please tell us what is the Datasource you are using when performing the Transform operation on the query?

Sure thing. My data comes from a PostgreSQL database. Here's one of the variables:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/5418178/211812888-367b8620-b3c8-4746-84f2-418aeeae4710.png">


All of my variables work everywhere where I need them to work except within the transform renaming and that's kind of the most important place where I need them to work 😅

Thanks!

**Comment by JakesFouche** [comment] 2023-01-13 07:29
Tested this on my side. I can confirm that I have the same issue as well. Seems like it's a bug. I would expect for the variable to be used.

**Comment by usmangt** [comment] 2023-01-17 15:50
Ok got some updates regarding this issue.

So, variables are not supported with the Transformation at the moment. There was a similar issue opened in the past [#25469](https://github.com/grafana/grafana/issues/25469)

Also, the same question was [asked](https://community.grafana.com/t/how-to-use-a-variable-in-a-transformation-regex/35864) in our community forums.

I will close this issue.

**Closed by usmangt** 2023-01-17 15:50 UTC
Labels: area/dashboard/templating, datasource/Postgres, needs investigation, area/transformations

**Comment by shaunroselt** [comment] 2023-01-17 16:54
> Ok got some updates regarding this issue.
> 
> So, variables are not supported with the Transformation at the moment. There was a similar issue opened in the past [#25469](https://github.com/grafana/grafana/issues/25469)
> 
> Also, the same question was [asked](https://community.grafana.com/t/how-to-use-a-variable-in-a-transformation-regex/35864) in our community forums.
> 
> I will close this issue.

Thanks for the update.

Do you know if there are any plans to implement this or support it in the future?

**Comment by natellium** [comment] 2023-01-18 09:34
> Do you know if there are any plans to implement this or support it in the future?
@grafana/observability-metrics you might be able to answer this?

**Comment by gtk-grafana** [comment] 2023-01-18 14:33
It looks like this would require migrating all transformations to core, so I would take a guess this isn't coming out any time soon unless metrics de-prioritizes work on other focus areas (i.e. prometheus, graphite, influx)

**Comment by shaunroselt** [comment] 2023-01-24 22:29
Looks like it's possibly planned for v10:

https://github.com/grafana/grafana/issues/46428
https://github.com/grafana/grafana/issues/55605

**Comment by shaunroselt** [comment] 2023-06-05 07:28
> Looks like it's possibly planned for v10:
> 
> #46428 #55605

Looks like this has been pushed to v11+. It's not planned for v10 anymore 😢

**Comment by nukleuz80** [comment] 2025-04-17 07:26
Any news? with 11.6 it doesn´t work

**Comment by isaacchacko** [comment] 2025-05-19 15:42
+1
