### ISSUE TITLE
Tags with '.' in key resolve in series alias but not in alert test rule results

### ISSUE THREAD

**Issue by michaelmuske** [grafana/grafana#17858] opened 2019-07-01 18:53 UTC
**What happened**:
I wrote a query against an InfluxDB with the following value in ALIAS BY:
`[[tag_tags.thing1]] [[tag_thing2]]@[[tag_tags.thing3]] ([[tag_tags.thing4]])`

I noticed that the other alias pattern of $tag_tags.thing1 did not resolve for the tags with a '.' character in the tag key, which is why I'm using this alternate alias pattern.

The series labels on the resulting panel work as expected with the tags I specified in the ALIAS BY section resolving to their actual values. However, when I created an Alert and ran the Test Rule it returned many Objects in the logs array, all of which contained a message with unresolved tags for 3 of my 4 tags, i.e.: `message:"Condition[0]: Eval: false, Metric: [[tag_tags.thing1]] consumer@[[tag_tags.thing3]] ([[tag_tags.thing4]]), Value: 14.000"`

**What you expected to happen**:
I would expect the message for Objects returned by the Test Rule to resolve the tags to their actual values. As it works now, the Test Rule is worthless because I can't tell which series are triggering the alert since the tags contain identifying information.

**How to reproduce it (as minimally and precisely as possible)**:
1. Write a metric to InfluxDB with a tag that contains a '.' in the name.
2. Define a query and specify the tag in the ALIAS BY section.
3. Define an alert and run the Test Rule, verify that the tag is not resolved in the Objects that are reported from the Test Rule.

**Anything else we need to know?**:
I did specify each of the 4 tags in the GROUP BY section of the query.

**Environment**:
- Grafana version:
v6.0.2
- Data source type & version:
InfluxDB
- OS Grafana is installed on:
Unknown
- User OS & Browser:
MacOS Mojave 10.14.3
Chrome 75.0.3770.100
- Grafana plugins:
- Others:

**Comment by michaelmuske** [comment] 2019-07-01 20:11
InfluxDB version: 1.4.3-1
Grafana OS: Red Hat Enterprise Linux 7 (64-bit)

**Comment by marefr** [comment] 2019-07-02 07:43
Duplicate of #9148

**Comment by marefr** [comment] 2019-07-02 07:43
Upgrade to Grafana v6.1.0 at least to get the fix.

**Closed by marefr** 2019-07-02 07:43 UTC
