### ISSUE TITLE
Slack Notifications: Missing orgId param in title url

### ISSUE THREAD

**Issue by krokwen-tftc** [grafana/grafana#92277] opened 2024-08-22 10:10 UTC
### What happened?

Grafana (at least for slack) wraps produced message title into alert rule url, but misses orgId param.
That breaks link behavior when you follow the link but you switched to another organization

### What did you expect to happen?

Slack message title link to include orgId param, so user will be able to get to the right alert rule page regardless of current selected organization

### Did this work before?

Don't know

### How do we reproduce it?

1. Setup 2 organizations
2. Setup slack alert contact point on the first organization
3. Setup alert rule and trigger it on the first organization to receive notification
4. Switch to the second organization in browser
5. Try to follow the link from slack message title

### Environment (with versions)?

Grafana: 10.4.2

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by santihernandezc** [comment] 2024-10-09 10:01
Hi @krokwen-tftc, thanks for creating this bug report. We're closing it as it's a duplicate of https://github.com/grafana/grafana/issues/69248.
There's a PR already in place to fix this bug. We'll review it and continue working on the original issue if needed.

**Closed by santihernandezc** 2024-10-09 10:01 UTC
Labels: type/bug, area/alerting, automated-triage
