### ISSUE TITLE
Panels disappears when setting row collapsed = false in JSON Module

### ISSUE THREAD

**Issue by stefanbie** [grafana/grafana#50855] opened 2022-06-15 09:25 UTC
**What happened**:
Panels disappears when setting a row panel to "collapsed": false, in the json Module

**What you expected to happen**:
Panels are viable when setting a row panel to "collapsed": false, in the JSON Module

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a new row
2. Add a panel to the row
3. Collapse the row
4. Save dashboard
5. In JSON Model find _"collapsed": true_ and change to "_collapsed": false_
6. Save Changes
7. Go back to the dashboard view. Panel is gone

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.5.5
- OS Grafana is installed on: Ubuntu
- User OS & Browser:Ununtu/ Chrome

**Comment by daniellee** [comment] 2022-06-15 10:34
Can confirm that this bug is in latest main. After changing collapsed to false and saving in JSON model section you can still see the panel in the json. But if you leave and go back then the panels are removed.

When comparing dashboard versions then the removed panel is not visible in the diff:

![image](https://user-images.githubusercontent.com/434655/173805917-8cc2b078-cf82-4804-978d-4cd94d230db0.png)

But looking at the raw json in the database then the panel is still there:

[row-collapse-false.json.txt](https://github.com/grafana/grafana/files/8908475/row-collapse-false.json.txt)

Something going wrong when loading the json from the database?

**Comment by Stephan202** [comment] 2022-07-02 16:49
We're also experiencing this issue with Grafana 8.3.2, so it seems the regression happened before then.

**Comment by Stephan202** [comment] 2022-07-02 16:56
Ah, this appears to be a duplicate of/related to #34565.

**Comment by ivanortegaalba** [comment] 2022-07-13 15:12
I'm able to reproduce it too. Thanks for the detailed instructions.
I can see the panel is properly saved in the database when modifying the JSON manually, the status of `collapsed` is `true`, and the panel is still there. But during runtime, the dashboard row receives an empty array of panels, so it seems it is a runtime error.
<img width="1638" alt="Captura de Pantalla 2022-07-13 a las 17 08 14" src="https://user-images.githubusercontent.com/5699976/178768498-ac30979d-a174-4f85-b914-348fb8e0c26d.png">

**Comment by ivanortegaalba** [comment] 2022-07-13 16:27
I think I found the root cause: 
* The dashboard row panel has a property panels with the panels in it. Located at `panels[0].panels`
* When the row is collapsed, the panels inside a row panel are at the `panels[0].panels` level
* When the row is expanded, the panels inside the row are moved to `panels`
* If we modify the JSON template by hand, only changing the collapsed attribute, the panel is not moved between `panels[0].panels` and `panels`, this is why we have a inconsistent behavior.
* When there are more than one row, the layout is recalculated for the elements below the row

<img width="816" alt="Captura de Pantalla 2022-07-13 a las 18 20 04" src="https://user-images.githubusercontent.com/5699976/178783269-8a0b05fe-97f6-4e68-8697-c32edceb2ab4.png">
<img width="652" alt="Captura de Pantalla 2022-07-13 a las 18 20 11" src="https://user-images.githubusercontent.com/5699976/178783283-0faa6ca7-cb07-486a-87ad-0e7fc8a3aec3.png">

There is not a easy way to fix this, since in reality, the dashboard is literally removing the widgets within a collapsed panel, and stored to be recovered later. The ideal scenario is that the JSON keeps the array of panels without modification, but mark them as hidden.

My suggestion is to not modify the JSON manually to collapse items. And in case you really have to do it, you should move the widgets within that row inside the dashboard row `panels` property.

* When the panel is collapsed using the UI, the `panels` property is set to empty string, and it extracts 
When a panel is collapsed through UI, the dashboard row panel is

**Comment by ivanortegaalba** [comment] 2022-07-14 09:08
Since this behavior is not contemplated as part of Grafana's core features, it is derived from a custom edition in a JSON and it is intrinsic to the way Grafana manages the rows and panels, I'm closing this issue.

Please, feel free to reach out if you need help with anything else. Thanks for raising this issue and helping to improve Grafana 🙏

**Closed by ivanortegaalba** 2022-07-14 09:08 UTC
Labels: type/bug, area/dashboard
