### ISSUE TITLE
[Feature request] Block top bar menu

### ISSUE THREAD

**Issue by gwuillou** [grafana/grafana#8671] opened 2017-06-21 06:10 UTC
- What Grafana version are you using?
4.2
- What datasource are you using?
influxdb
- What OS are you running grafana on?
Debian
- What was the expected result?
I thing it's should be great to have the possibility to fix the top bar menu when we scroll down to see other panels.

Thank you for your work!

**Comment by torkelo** [comment] 2017-06-21 12:19
duplicate of https://github.com/grafana/grafana/issues/4670

**Closed by torkelo** 2017-06-21 12:19 UTC
