### ISSUE TITLE
Message field name dissapearing when selecting other parsed fields

### ISSUE THREAD

**Issue by tomas-mota** [grafana/grafana#33374] opened 2021-04-26 10:34 UTC
**What happened**:
Overriding message field makes the message field dissapear from list of parsed fields

**What you expected to happen**:
Expected to be able to add parsed fields _alongside_ the message field, when it has been set up when configuring the data source

**How to reproduce it (as minimally and precisely as possible)**:
- Set "message field name" when setting elasticsearch datasource
- Go to explore view, and select that datasource with metric as "Logs". Each log line will show the log message
- Click on one of the log lines and add click on the little eye for one of the fields.
- The message will be replaced (as expected), but it is gone from the list of parsed fields, meaning you can't have both the message and other fields being shown at the same time

**Anything else we need to know?**:
View before adding another field:
The message seen at the top comes from the "message" field, which was configured when setting up the data source
![image](https://user-images.githubusercontent.com/25929015/116068842-fa4d4e00-a68a-11eb-870e-444b6b93fd48.png)

View after selecting another field:
"message" field is gone from parsed fields, meaning I can not see it at the top alongside any other field
![image](https://user-images.githubusercontent.com/25929015/116069048-426c7080-a68b-11eb-83da-bacf653f8270.png)

**Environment**:
- Grafana version: v7.3.6 (ea06633c34)
- Data source type & version: Elasticsearch, don't know version

**Comment by tomas-mota** [comment] 2021-04-26 10:36
Should be labeled as datasource/Elasticsearch

**Comment by Elfo404** [comment] 2021-05-06 09:17
Closing this as duplicate of https://github.com/grafana/grafana/issues/30817

**Closed by Elfo404** 2021-05-06 09:17 UTC
Labels: datasource/Elasticsearch, needs investigation
