### ISSUE TITLE
Data links are not updated after sorting/filtering

### ISSUE THREAD

**Issue by Traver72** [grafana/grafana#32740] opened 2021-04-07 07:25 UTC
**What happened**:
Data links do not work as expected. They point to the wrong page after sorting/filtering data.
GIF: After sorting, you can see that the link in the bottom left corner does not change correctly
![Peek 2021-04-07 09-27](https://user-images.githubusercontent.com/67479615/113827439-99191580-9783-11eb-9ed3-e8229633541a.gif)

**What you expected to happen**:
Links should correspond to the data

**How to reproduce it (as minimally and precisely as possible)**:
1. create a new table Panel (format as table) and select * something (Or use grafana sample data "random walk").
2. in the right panel go to "Field" -> Data Links -> Add Link -> enter "$" and select any ${__data.fields.column_name} or ${__value.text}
3. optional: activate filter
4. apply changes
5. filter or sort the table -> links do not correspond to the data

**Anything else we need to know?**:
/

**Environment**:
- Grafana version: Grafana v7.5.2
- Data source type & version: MySQL / -- Grafana --
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment] 2021-04-07 07:37
Duplicate of #32542

**Closed by zoltanbedi** 2021-04-07 07:37 UTC
