### ISSUE TITLE
Repeating panel by variable from row

### ISSUE THREAD

**Issue by drix1994** [grafana/grafana#19181] opened 2019-09-17 14:43 UTC
Hello
I have the issue which I can’t resolve…
In dashboard definition I used a “row panel” with repeat option and set variable to use $row and it works properly. I have the same number of rows as variable $row contains values. (ex. $row={A,B,C}):
RowA
RowB
RowC

Next I put into a row Singlestat Panel with repeat option also, but repeat option is set to use $sp={1,2,3}.

Finally I have situation that I have diferent row but with the same definiton of Singlestat Panel.
If I select "all" option in $row and $sp each row have:
RowA:
RowA_sp1, RowA_sp2, RowA_sp3
RowB_sp1, RowB_sp2, RowB_sp3
RowC_sp1, RowC_sp2, RowC_sp3

RowB:
RowA_sp1, RowA_sp2, RowA_sp3
RowB_sp1, RowB_sp2, RowB_sp3
RowC_sp1, RowC_sp2, RowC_sp3

RowC:
RowA_sp1, RowA_sp2, RowA_sp3
RowB_sp1, RowB_sp2, RowB_sp3
RowC_sp1, RowC_sp2, RowC_sp3

Situation that I would like to have should look like:
RowA:
RowA_sp1, RowA_sp2, RowA_sp3

RowB:
RowB_sp1, RowB_sp2, RowB_sp3

RowC:
RowC_sp1, RowC_sp2, RowC_sp3

In my opinion it is imposible, because the Signlestat Panel should have option to inherit variable $row as filter from “row panel” and then Singlestat Panel should repeat by variable $sp in fact repeat by $row also.

Is there any solution to solve my problem?

best regards

**Comment by torkelo** [comment] 2019-09-17 16:14
repeating by row and by panel using different repeats for each and expecting grafana to issue new queries for each row to fetch locally scoped sub-values for the panel repeat variable will likely not happen. 

We hope to introduce a new form of scripted dashboard in the future to solve more complex dynamic dashboard building scenarios

**Comment by torkelo** [comment] 2019-09-17 16:15
dupe of https://github.com/grafana/grafana/issues/11263 (and probably a few others),

**Closed by torkelo** 2019-09-17 16:14 UTC
