### ISSUE TITLE
Plot graph when one of the series is unavailable

### ISSUE THREAD

**Issue by feliksik** [grafana/grafana#2064] opened 2015-05-28 12:03 UTC
When a graph plots 6 series and (the first?) one is not available in InfluxDB, none of the series is plotted. 
It would be nice if it would plot the available series, and display the error for the unavailable one(s).

**Comment by torkelo** [comment] 2015-05-28 12:15
duplicate of https://github.com/grafana/grafana/issues/1101

**Closed by torkelo** 2015-05-28 12:15 UTC
