### ISSUE TITLE
bar chart tool tip mode does not display correctly ，including single | all

### ISSUE THREAD

**Issue by CodeDontRun** [grafana/grafana#57579] opened 2022-10-25 02:23 UTC
**What happened**: Tooltip doesn't properly show (single | all) values.

**What you expected to happen**:  Correctly display tooltips for single or all values on hover

**How to reproduce it (as minimally and precisely as possible)**: use bar chart and transform Grouping to matrix ，Stacking is normal 
 set tool tip mode is single 

**Anything else we need to know?**: I have a json model I hope to reproduce the problem

**Environment**:
- Grafana version: 9.1.7
- Data source type & version: mysql 
- OS Grafana is installed on: CentOS
- User OS & Browser: CentOS7
- Grafana plugins: Bar Chart 
- Others:

![image](https://user-images.githubusercontent.com/116553310/197666106-482213d0-f183-46c4-a838-1ea1e5d79886.png)
![image](https://user-images.githubusercontent.com/116553310/197666406-fb70248b-a74f-4373-8ab3-641272fca3fe.png)
![image](https://user-images.githubusercontent.com/116553310/197666632-533c83a9-9357-4590-b113-7c1d3b8388b1.png)
![image](https://user-images.githubusercontent.com/116553310/197666667-87d864b5-e88b-4b76-aeda-c7553ec126e3.png)

this json model

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 1502,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "mysql",
        "uid": "QTzGEw97z"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 80,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 14,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "orientation": "auto",
        "showValue": "auto",
        "stacking": "normal",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 0
      },
      "pluginVersion": "9.2.1-cab7049",
      "targets": [
        {
          "datasource": {
            "type": "mysql",
            "uid": "QTzGEw97z"
          },
          "editorMode": "code",
          "format": "table",
          "group": [],
          "metricColumn": "none",
          "rawQuery": true,
          "rawSql": "SELECT\nCountryCode,Language,Percentage\nFROM countrylanguage WHERE  Language = 'English' LIMIT 20",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "column"
              }
            ]
          ],
          "sql": {
            "columns": [
              {
                "parameters": [],
                "type": "function"
              }
            ],
            "groupBy": [
              {
                "property": {
                  "type": "string"
                },
                "type": "groupBy"
              }
            ],
            "limit": 50
          },
          "table": "countrylanguage",
          "timeColumn": "time",
          "where": []
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "groupingToMatrix",
          "options": {
            "columnField": "CountryCode",
            "rowField": "Language",
            "valueField": "Percentage"
          }
        }
      ],
      "type": "barchart"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [
    "mysql",
    "community",
    "ds-example"
  ],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "MySQL 8: Cities of the World Sample Data Set",
  "uid": "8JOvPQr7k",
  "version": 5,
  "weekStart": ""
}

**Comment by leeoniya** [comment] 2022-10-25 05:07
mostly a dupe of https://github.com/grafana/grafana/issues/57110

i plan to look into a fix this week.

**Closed by leeoniya** 2022-10-25 05:07 UTC
