### ISSUE TITLE
Timestamp not being displayed correctly in the Explore Tad

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#20062] opened 2019-10-28 16:20 UTC
**What happened**:
I first configured a datasource for Elasticsearch and then go under Explore --> Logs to see all my logs stored.
The messages are sorted correctly, from the newest to the oldest, but the timestamp display in the left colomn is incorrect, despite the timestamp value being correctly formated.

**What you expected to happen**:
I expect to see the timestamp being displayed correctly in the Logs Tab

**How to reproduce it (as minimally and precisely as possible)**:
Configure a datasource under ElasticSearch version 7.x
Configure the data time field under @timestamp
Save my datasource
Go under Explore --> Logs and select my datasource
All the logs are being sorted correctly but the timestamp displayed is incorrect

**Anything else we need to know?**:

Configuration of my datasource :
![image](https://user-images.githubusercontent.com/33425208/67696456-32e16e00-f9a7-11e9-9bf4-8e184b2971ed.png)

Result in the Explore --> Logs tab :
![image](https://user-images.githubusercontent.com/33425208/67696341-fa419480-f9a6-11e9-8613-a880c6df39fb.png)

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: Elasticsearch 7.4.1-1
- OS Grafana is installed on: CentOS 7 1804
- User OS & Browser: Microsoft Edge Version 80.0.315.0 (Official build) canary (64-bit)

**Comment by torkelo** [comment] 2019-10-28 19:26
strange.

**Comment by torkelo** [comment] 2019-10-28 19:27
@davkal can someone on the observability squad investigate this?

**Comment by davkal** [comment] 2019-10-29 10:43
Duplicate of #19909

**Closed by davkal** 2019-10-29 10:43 UTC
Labels: area/explore, datasource/Elasticsearch, needs investigation
