### ISSUE TITLE
Displaying colored cells depending on string value

### ISSUE THREAD

**Issue by Melic-Dufrene** [grafana/grafana#27546] opened 2020-09-11 13:27 UTC
**What would you like to be added**:
i would like to set treshold on string values either by matching some regular expressions or converting string to values.
The issue has already be opened in previous version of grafana but I am working with grafana 7.0.5 and I could not find anything regarding this issue.

**Why is this needed**:
I would like to see this feature to display some status in grafana.

**Comment by marefr** [comment] 2020-09-11 15:54
Duplicate of #11418

**Closed by marefr** 2020-09-11 15:54 UTC
