### ISSUE TITLE
Cannot set "for 0" for existing alert

### ISSUE THREAD

**Issue by piotrp** [grafana/grafana#52491] opened 2022-07-19 22:19 UTC
When modifying a Unified Alerting alert the value for "for" cannot be changed to "0" - Grafana reverts to previously stored value.

Tested on Docker (`docker run --rm -it --name=grafana -p 3000:3000 grafana/grafana:8.5.9`):

1. Create TestData DB datasource
2. Create new valid alert rule, it will have "Evaluate every [1m] for [5m]"
3. Edit this rule, set "for [0]" and click "Save" - screen will reload and the value will revert to "for [5m]"

![obraz](https://user-images.githubusercontent.com/1409807/179858038-df08b59b-e854-4aa7-a566-4e7433818152.png)

Tested on Grafana 8.5.9 and 9.0.3.

**Comment by zoltanbedi** [comment] 2022-07-21 11:52
This is by design see the error.
![Screenshot 2022-07-21 at 13 51 48](https://user-images.githubusercontent.com/13729989/180207324-748e19d4-e16e-4b13-b4f6-691d249e0bc3.png)

**Comment by piotrp** [comment] 2022-07-21 12:03
I cannot see an error that isn't there in current stable version (tested in 9.0.3).

The error you are writing about is shown for non-zero values:
![obraz](https://user-images.githubusercontent.com/1409807/180208053-88c450a5-9e00-4576-9cce-2e7cd336856a.png)

But not for "0":
![obraz](https://user-images.githubusercontent.com/1409807/180208835-cead74f2-a8ed-45c6-a7cc-5fac9f01bdf2.png)

And then, what about alerts migrated from classic alerting - do they work at all? Are they silently broken? They do have "0", and I can easily create alerts with "0", which you claim to be invalid.

Does this mean that the official advice from four months ago at https://community.grafana.com/t/grafana-8-alerting-evaluation-immediate-firing-once-every-24h/62179:
> To get an alert to fire immediately if the condition is true, you want to set the for time to 0. Otherwise, the condition needs to remain true for one minute before the alert will fire.

is invalid?

**Comment by armandgrillet** [comment] 2022-07-22 09:41
The Alerting team has investigated this.

> And then, what about alerts migrated from classic alerting - do they work at all? Are they silently broken? They do have "0", and I can easily create alerts with "0", which you claim to be invalid.

When migrating/provisioning, the `for` value is correctly set to 0 and the alert will be triggered as soon as the first evaluation returns true (as expected).

However, there are two bugs:

1. The frontend does not accept 0 nor 0m as a value for the `for`duration.
2. Even without that check: when updating a rule, the compare function does not notice that the `for` is 0 and will thus not do an update.

The first bug is a frontend one, the second one is backend. This is a big issue, thanks for reporting it.

Tried this in Grafana 9.0.5 (Grafana Cloud) and you can set `for` to `0`, . Migrated alerts thus work. Closing this but please reopen if it doesn't work

**Comment by yuri-tceretian** [comment] 2022-07-22 13:45
Hey @piotrp, thanks for reporting the bug! It was introduced in 8.5 and it is still there in 9.0. 
Recently we have fixed it in the backend https://github.com/grafana/grafana/pull/50992. The fix was merged to the master branch and will be released in 9.1.

**Closed** 2022-07-29 09:45 UTC
Labels: type/bug, prio/high, area/alerting

**Comment by konrad147** [comment] 2022-07-29 09:54
FE PR https://github.com/grafana/grafana/pull/52942
