### ISSUE TITLE
Exlpore Metrics Tab Panel Bug

### ISSUE THREAD

**Issue by denissduan** [grafana/grafana#20097] opened 2019-10-30 10:27 UTC
**What happened**:
i was using Grafana version 6.4.3
and embed it into my platform。
no metrics tab link or switch to log tab link embed it awalys display default to metrics tab panel
**What you expected to happen**:
when i using log tab link to embed it can default dispaly to log tab panel 
**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/8587100/67850323-2a259f00-fb43-11e9-9dd4-e4de3e2a498b.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-10-31 11:10
duplicate of https://github.com/grafana/grafana/issues/19357

**Closed by torkelo** 2019-10-31 11:10 UTC
