### ISSUE TITLE
graphite data source can not use from/util in query

### ISSUE THREAD

**Issue by xbsura** [grafana/grafana#21258] opened 2019-12-25 08:43 UTC
**What happened**:
If I create two query in one panel, and try to make one show data of yesterday, I add &from=now-24h to query two, but it does not work

**What you expected to happen**:
different query can has its own from and util and any other & param

**How to reproduce it (as minimally and precisely as possible)**:
just add from to query

**Anything else we need to know?**:
I found that grafana try to fetch all data in one query, and &param is used to all query, maybe this is the reason

If this is by design, How can I display data of today and yesterday in one panel

thanks

**Environment**:
- Grafana version: 6.5
- Data source type & version: graphite
- OS Grafana is installed on: Linux
- User OS & Browser: CHrome
- Grafana plugins: no
- Others: no

**Comment by torkelo** [comment] 2019-12-26 06:03
you can use Graphite's timeshift function to shift a query to a different time range.  
you cannot add &from an to params to a query, they are not part of the query language, but are query parameters that Grafana control (either via dashboard time range or panel time range). 

dupe of https://github.com/grafana/grafana/issues/7762

**Closed by torkelo** 2019-12-26 06:03 UTC

**Comment by xbsura** [comment] 2019-12-26 06:59
thanks! I will keep watching #7762
