### ISSUE TITLE
[Feature request] Is grafana support elasticsearch alert?

### ISSUE THREAD

**Issue by YunSangJun** [grafana/grafana#7287] opened 2017-01-18 10:24 UTC
Is grafana alerting engine support elasticsearch data soures?

http://docs.grafana.org/alerting/rules/
https://github.com/grafana/grafana/issues/5893

**Comment by bergquist** [comment] 2017-01-18 10:48
Not yet.

Dupe of #5893

**Closed by bergquist** 2017-01-18 10:48 UTC

**Comment by rwagner-inf** [comment] 2018-03-01 13:45
Hi guys!

Is there any estimate for grafana to work with alerts for elasticsearch?
