### ISSUE TITLE
Sort order of legends [bump]

### ISSUE THREAD

**Issue by shannonmoeller** [grafana/grafana#23201] opened 2020-03-30 12:41 UTC
This is a bump for issue #2640 which should be reopened.

**Comment by torkelo** [comment] 2020-03-31 08:19
The order of series is best sorted in your metric query, we will add sort transformations as part of the new data transformation feature 

duplicate of https://github.com/grafana/grafana/issues/18186

**Closed by torkelo** 2020-03-31 08:19 UTC
