### ISSUE TITLE
GraphNG: Using colour picker for a series doesn't work correctly when override on displayName is set

### ISSUE THREAD

**Issue by sd2k** [grafana/grafana#32355] opened 2021-03-26 11:12 UTC
**What happened**:

In the 'time series' panel, when trying to use the colour picker to change the colour of a series with a 'displayName' override property already set, the new colour override property is applied incorrectly - it ends up being a separate override without a field to apply to, rather than being applied to the selected series.

**What you expected to happen**:
The colour override property should be applied to the existing override, rather than to a new override.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a timeseries panel with one or more series
2. Add an override using 'Fields with name' and the Display name override property (name it anything)
3. Use the legend to try to change the colour of the series

**Anything else we need to know?**:

GIF attached: 
![Kapture 2021-03-26 at 11 10 59](https://user-images.githubusercontent.com/5464991/112623250-080d7a80-8e24-11eb-9a95-bcb93eefdbd0.gif)

**Environment**:
- Grafana version: 7.4.4 + 7.5.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS + Firefox
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment] 2021-03-26 11:22
Think we have an issue for this already

**Comment by sd2k** [comment] 2021-03-26 11:24
Could be related to https://github.com/grafana/grafana/issues/31364? Couldn't find any exact dupes though.

**Comment by torkelo** [comment] 2021-03-26 11:25
dupe of https://github.com/grafana/grafana/issues/31364

**Closed by torkelo** 2021-03-26 11:25 UTC
Labels: area/panel/timeseries, type/bug
