### ISSUE TITLE
window slider buttons are gone

### ISSUE THREAD

**Issue by wiebeytec** [grafana/grafana#14165] opened 2018-11-22 17:18 UTC
[This pull request](https://github.com/grafana/grafana/pull/13025) seems to have made the window silder buttons disappear:

![screenshot_20181122_181355](https://user-images.githubusercontent.com/6682400/48916395-73c13080-ee82-11e8-8012-30d634a2f14d.png)

I expected < and > to be there. They now only show up if I zoom out first:

![screenshot_20181122_181706](https://user-images.githubusercontent.com/6682400/48916502-dc101200-ee82-11e8-958b-3028a54f3507.png)

But then it's no longer a window of 30 days.

Grafana version: 5.3.4

**Comment by torkelo** [comment] 2018-11-23 06:51
duplicate of https://github.com/grafana/grafana/issues/13687

**Closed by torkelo** 2018-11-23 06:51 UTC
