### ISSUE TITLE
Support mysql mgr cluster as back-end storage database

### ISSUE THREAD

**Issue by JokerDevops** [grafana/grafana#63104] opened 2023-02-08 15:09 UTC
**What happened**:
I use mysql mgr cluster as the back-end database of grafana.

The following error occurred when starting grafana：
```
Feb 08 22:48:43 xxx grafana-server[533457]: logger=migrator t=2023-02-08T22:48:43.813742944+08:00 level=info msg="Executing migration" id="copy alert_rule_tag v1 to v2"
Feb 08 22:48:43 xxx grafana-server[533457]: logger=migrator t=2023-02-08T22:48:43.81436509+08:00 level=error msg="Executing migration failed" id="copy alert_rule_tag v1 to v2" error="Error 3098: The table does not comply with the requirements by an external plugin."
Feb 08 22:48:43 xxx grafana-server[533457]: logger=migrator t=2023-02-08T22:48:43.814426969+08:00 level=error msg="Exec failed" error="Error 3098: The table does not comply with the requirements by an external plugin." sql="INSERT INTO `alert_rule_tag` (`alert_id`\n, `tag_id`) SELECT `alert_id`\n, `tag_id` FROM `alert_rule_tag_v1`"
Feb 08 22:48:43 xxx grafana-server[533457]: Failed to start grafana. error: migration failed (id = copy alert_rule_tag v1 to v2): Error 3098: The table does not comply with the requirements by an external plugin.
```
**What you expected to happen**:

Start the service normally

**How to reproduce it (as minimally and precisely as possible)**:

Use the mysql mgr cluster as the grafana back-end database to start the grafana service.

**Anything else we need to know?**:

Please alert when migrating the database table `structure_ rule_ tag_ V1` table and ` annotation_ tag_ Set the upper primary key of the v2 ` table

**Environment**:
- Grafana version: grafana-enterprise-9.3.1.linux-amd64
- Data source type & version: mysql 5.7 mgr cluster
- OS Grafana is installed on:  centos7
- User OS & Browser: centos7
- Grafana plugins:
- Others:

**Comment by usmangt** [comment] 2023-02-09 09:35
Hi @JokerDevops,

Thanks for opening this issue.

I see that you are using Grafana Enterprise. I will ask the their team to have a look into it.

**Comment by usmangt** [comment] 2023-02-09 10:05
Looking at the first 2 lines of the logs, indicates that the server is trying to migrate legacy alerting rules into the newer unified alerting `v2` platform.

There seems to be already an existing issue (https://github.com/grafana/grafana/issues/45639) reported on this, which describes what is the reason and how to resolve it. 

I hope this helps.

**Comment by usmangt** [comment] 2023-02-21 08:44
closing as a duplicate of an existing known issue (https://github.com/grafana/grafana/issues/45639)

**Closed by usmangt** 2023-02-21 08:44 UTC
Labels: area/alerting, area/backend/db/mysql, area/alerting-legacy

**Comment by JokerDevops** [comment] 2023-02-21 10:22
@usmangt  thanks
