### ISSUE TITLE
Grafana Table Panel Dimensioning

### ISSUE THREAD

**Issue by mamenezes** [grafana/grafana#9388] opened 2017-09-29 15:22 UTC
Weird Table Panel Auto Dimensioning
Why is it not able to resize the columns and rows in the Table Panel?
Is this that dificult to implement?
Like... Just make it to be able to put the cursor in the column borders and drag to one side or another to adjust it, so we don't have weird tables like this: 

![image](https://user-images.githubusercontent.com/32394929/31022902-9e10b250-a510-11e7-9be1-be165f2151c7.png)

**Comment by torkelo** [comment] 2017-10-01 07:17
The table panel does not handle wide columns very well.

dupe of 
https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2017-10-01 07:17 UTC
