### ISSUE TITLE
Fill below to: Support queries with any number of series returned

### ISSUE THREAD

**Issue by MzazM** [grafana/grafana#24735] opened 2020-05-15 13:45 UTC
This is a great feature. I use it show intervals of confidence, to give the user a feeling of noise or indicate the std in the series. At the moment it is not usable in a general way, if the number of series to display is not known a-priori

**What would you like to be added**:
I would like the series specific override "Fill Below To" to support template variables. 
For these queries, the number of series returned might be unknown. Therefore it is not possible to define the series override rules a priori. It was mentioned in #940. 
If my series are named "max_$variable" and "min_$variable", currently you can't express that in the interface because when $variable changes it'll break the binding.

**Comment by torkelo** [comment] 2020-06-15 13:51
Can you use a regex in the rule?

**Comment by torkelo** [comment] 2020-06-15 13:53
duplicate of https://github.com/grafana/grafana/issues/5398

**Closed by torkelo** 2020-06-15 13:53 UTC
Labels: area/dashboard/templating, type/feature-request
