### ISSUE TITLE
[Feature request] Set JSON body to be send on Webhook notification

### ISSUE THREAD

**Issue by vanduijnjordi** [grafana/grafana#7433] opened 2017-02-02 13:45 UTC
Please include this information:
- What Grafana version are you using? **4.1.0**
- What datasource are you using? **Graphite**
- What OS are you running grafana on? **Windows**
- What did you do? **Trying to send a JSON body as the notification message**
- What was the expected result? **An "OK" response from the API I was sending it to**
- What happened instead? **Webhook response status 400 Bad Request**

More information:
The API I am sending the data to via the webhook expects an "application/json" header and a JSON package with specific fields. I am trying to send this package throught the notification message field, but it seems it is being wrapped in something bigger. Am I missing something, or is this simply impossible with the current build?

**Comment by torkelo** [comment] 2017-02-02 13:49
dupe of https://github.com/grafana/grafana/issues/6956

**Closed by torkelo** 2017-02-02 13:49 UTC

**Comment by vanduijnjordi** [comment] 2017-02-02 14:03
I'm sorry, completely overlooked that one. Is there any indication on if/when this will be added to grafana?

Thanks for the quick response!
