### ISSUE TITLE
Grafana not showing time series trend on types stored as "nested" in schema

### ISSUE THREAD

**Issue by IamShubhamGupto** [grafana/grafana#46394] opened 2022-03-10 07:27 UTC
**What happened**:
Data stored in elasticsearch (is populated with data) is not being plotted on grafana time series graphs.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/32878682/157607311-231cd51a-747c-417d-a908-38a0d4948afb.png">

**What you expected to happen**:
Show how data varies over time
**How to reproduce it (as minimally and precisely as possible)**:
From the query image:
- customer_id, cluster_type and cluster_name are variables and adding or removing them from the query makes no difference. They do not affect this graph.
- schema format of data stored in elasticsearch:
```
{
  "index-pattern-name": {
    "mappings": {
      "properties": {
        "apps": {
          "properties": {
            "app_installs": {
              "type": "nested",
              "properties": {
                "app-name": {
                  "type": "long"
                },
                "app-name-2": {
                  "type": "long"
                },
                .... so on for any number of apps installed by that customer
           }
         },
        "date": {
          "type": "date"
        },
        .... 
     }
   }
 }
}

```
- data format fed into elastic search
```
{
  "date": <date>,
  "apps":{
    "app_installs": [
      {
        "app-name-1": <number>
      },
      {
        "app-name-2": <number>
      },
      ....
    ]
  }
}
```
**Anything else we need to know?**:
The goal is to show how the individual app installations vary over time, query the top 5/10 most downloaded apps and so on. However, currently Grafana is unable to process nested data stored as an array. 

The reason I went with nested is we do not know from the beginning how many apps are installed by the customer (variable length) and the number of apps can always be increased or decreased based on the customers needs.

**Environment**:
- Grafana version: v8.3.0 (https://github.com/grafana/grafana/commit/914fcedb72c5e1bd6752f8f311b14df9cc7f7281)
- Data source type & version: ElasticSearch V7+
- OS Grafana is installed on: Ubuntu 20
- User OS & Browser: Windows 10 & Microsoft Edge
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment] 2022-03-10 12:11
Duplicate of #4693

**Closed by Elfo404** 2022-03-10 12:11 UTC

**Comment by IamShubhamGupto** [comment] 2022-03-10 13:34
@Elfo404 
Thanks for pointing out to the original PR, however, there seems to be no working solution. 

1. Does it mean it is not feasible to implement this?
2. Are there any work arounds?

The answers to the above questions will help me decide how to proceed.

**Comment by Elfo404** [comment] 2022-03-10 13:38
we'd have to implement support for nested bucket aggregation type in the Elasticsearch datasource, it's already in the squad backlog but i can't give you an ETA, and i'm not aware of any workaround i'm afraid
