### ISSUE TITLE
Grafana is not responding when variable or formula is input in X-Min, X-Max, Y-Min, Y-Max box

### ISSUE THREAD

**Issue by bily-gates** [grafana/grafana#12291] opened 2018-06-15 03:58 UTC
I am currently using Grafana 5.1.3, Graph panel and Microsoft SQL Server datasource.

The thing is, I want to dynamically scale Y-Axis using variable. But whenever I put the variable in the Y-Max box, refresh panel, Grafana is hang and I cannot do anything else. The only way to get it online is close the tab and reopen it.

If someone know how do the dynamic Y-axis in other ways, please help me with your solution.
In the meantime, please take a look in the bug (I think) as described above.

Thanks for any supports.

**Comment by torkelo** [comment] 2018-06-15 06:04
I think there is already a feature request for this

**Comment by torkelo** [comment] 2018-06-15 11:16
duplicate of https://github.com/grafana/grafana/issues/3935

**Closed by torkelo** 2018-06-15 11:16 UTC
