### ISSUE TITLE
Elasticsearch: Grafana randomly provisioning datasources with incomplete information (missing Index name)

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#68737] opened 2023-05-18 21:29 UTC
### 
# What went wrong?

**What happened**:
Grafana is randomly provisioning Elasticsearch datasources from git that are missing an Index name, which makes these not functional.  We've seen this quite a bit lately, restarting the pod usually fixes it however I just hit this in production where I had to restart grafana 7 or 8 times until it provisioned it correctly.

When this happens we end up with a datasource that looks like so:
![Screen Shot 2023-05-18 at 3 04 04 PM](https://github.com/grafana/grafana/assets/5891946/d59ebf9e-5a38-4963-89a9-b5a41802fb66)

here are the logs I captured from grafana starting up when this happens:
[grafana_datasource_issue.txt](https://github.com/grafana/grafana/files/11511712/grafana_datasource_issue.txt)

When this happens it happens to all of our elasticsearch datasources.  None of them will have an Index name, it will be blank for all of them

**What did you expect to happen**:
Grafana to consistently load the file from git in the same manner each time it starts up

  - 

### 
# How do we reproduce it?

**Step 1**:

restart grafana pod and see if it loaded datasources correctly or not

**Step 2**:

if it didn't, restart grafana and hope for the best

### 
# What Grafana version are you using?

FROM grafana/grafana:9.4.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### User's OS?

FROM grafana/grafana:9.4.7

### User's Browser?

safari

### Is this a Regression?

None

### Are Datasources involved?

yes, elasticsearch

**Comment by danfinn** [comment] 2023-05-18 21:31
As far as I know we never saw this on 8.x and have only started seeing it since moving to 9.x

**Comment by rmawhinnie** [comment] 2023-05-19 13:04
this is impacting our team as well, and as it is not something that can easily be remedied it is causing us some grief :(

**Comment by JSlater743** [comment] 2023-05-19 20:07
Yes I've also seen this problem .. very annoying

**Comment by danfinn** [comment] 2023-05-22 20:54
I can get some logs however we have since upgraded to 9.5.2 and so far have not hit it on that version.  Will the logs from 9.5.2 still be helpful?

**Comment by ivanahuckova** [comment] 2023-05-24 13:15
I looked into issues and it seem like a duplicate of https://github.com/grafana/grafana/issues/65105 and https://github.com/grafana/grafana/issues/65603. The issue was fixed  in https://github.com/grafana/grafana/pull/62790 which was released in v9.4.8, v9.5.0. So I suggest to upgrade your Grafana to (at least) these versions. I am closing this issue, but if anyone experience issue at v 9.5+, I can reopen.

**Closed** 2023-05-29 10:44 UTC
Labels: needs more info, datasource/Elasticsearch, area/provisioning
