### ISSUE TITLE
metric name selection query sends current system time rather than dashboard range [elasticsearch as datasource] 

### ISSUE THREAD

**Issue by arcolife** [grafana/grafana#3455] opened 2015-12-08 12:10 UTC
While using elasticsearch as datasource, and trying to select metric name for 'average' type, Grafana gave me query issue error. 

On debugging I found out, that it tried to query time-series index pattern [xyz.abc-]YYYYMMDD based on the current system time, rather than the time range that I had selected for that dashboard. 

```js
Object { data: Object, status: 404, headers: wb/<(), config: Object, statusText: "Not Found" }
```

I got this error in browser console. I opened the link it tried to do a GET on, which was for current day, rather than the time range I had set for the dashboard. It worked when I manually typed in the metric name though. Just that I don't get a dropdown list automatically.

**Comment by torkelo** [comment] 2015-12-08 16:04
duplicate of https://github.com/grafana/grafana/issues/3125

**Closed by torkelo** 2015-12-08 16:04 UTC
