### ISSUE TITLE
[Bug] 5.4 Cannot hide legend

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana#14164] opened 2018-11-22 16:39 UTC
### What Grafana version are you using?
5.4 running in docker

### What datasource are you using?
Prometheus

I'm testing the `5.4.0-beta1` release and it looks like it's not possible to disable legend display.
The `show` checkbox does not seem to be working.

![image](https://user-images.githubusercontent.com/6112562/48915007-6d7c8580-ee7d-11e8-8dbd-529e6218f5e9.png)

**Comment by marefr** [comment] 2018-11-22 16:44
Duplicate of #14144

**Comment by marefr** [comment] 2018-11-22 16:45
Fix will be included in v5.4.0 stable or is available in the latest docker:master.

**Closed by marefr** 2018-11-22 16:45 UTC
Labels: type: duplicate

**Comment by FUSAKLA** [comment] 2018-11-22 16:49
Sorry I must have overlooked it.
