### ISSUE TITLE
Numerical sorting for JSON-data in table

### ISSUE THREAD

**Issue by blekfet** [grafana/grafana#6262] opened 2016-10-13 06:41 UTC
- [x] Bug report
- What Grafana version are you using?
  3.1.1
- What datasource are you using?
  Elasticsearch
- What OS are you running grafana on?
  Windows
- What did you do?
  Sorted a table column with numbers.
- What was the expected result?
  A numerical sorted list.
- What happened instead?
  A string sorted list. Se attatched image.

![image](https://cloud.githubusercontent.com/assets/11923767/19338970/cce418d8-9120-11e6-945e-8fde56246298.png)

**Comment by torkelo** [comment] 2016-10-13 07:56
is the data numbers? set number column style in the table options (and unit/format type)

**Comment by blekfet** [comment] 2016-10-13 13:31
@torkelo Yes, the data is numbers. The column style is also set to number.

**Comment by waqark3389** [comment] 2016-11-08 11:20
+1

**Comment by waqark3389** [comment] 2016-11-08 11:48
@blekfet @torkelo I have an update to this: 
I noticed the data for this field in elasticsearch was of type "string". As logstash inserts into elasticsearch I converted the field into an "integer" and now the ordering is correct; 

However, I have no idea what is going on with threshold colouring. The example and config is below. For reference the numbers below 5 are coloured orange...

![grafanamysqlthresholdsconfig](https://cloud.githubusercontent.com/assets/12910496/20097920/dca48ca2-a5a8-11e6-91e9-1d4c62f785c3.PNG)
![grafanamysqlthresholds](https://cloud.githubusercontent.com/assets/12910496/20097921/de796ed0-a5a8-11e6-9009-a71d25b883b8.PNG)

**Comment by torkelo** [comment] 2016-11-08 12:49
you should only have two numbers in the threshold field. a lower and upper limit. 

so for example:
`5,10`

values < 5 would be green, > 5 & < 10 would be orange, >10 would be red

**Comment by waqark3389** [comment] 2016-11-08 13:11
@torkelo I did that, but it only colours integers, floats dont get coloured. Maybe something to do with conversion to integer in eleasticsearch. I will fix that and report back.

**Comment by torkelo** [comment] 2016-11-08 13:22
make sure Elasticsearch is returning proper numbers in the json and not strings

**Comment by waqark3389** [comment] 2016-11-08 14:07
@torkelo All working perfectly now. Silly mistake really, I had duplicate data in elasticsearch and fields in wrong places with wrong types. (been testing for a while and forgot to clear it once) 

Thanks a tonne for your help. This is not a bug in grafana so I think can be closed. 

You're a legend, keep up the good work. If you were running for presidency somewhere, you have my vote :p

**Comment by blekfet** [comment] 2016-11-10 13:57
I did just find that my numerical fields in elastic are quoted. Because I inserted them that way. My types in the index is numerical but they are returned in the same way they were inserted. That is, with quotes.

**Comment by waqark3389** [comment] 2016-11-10 14:31
@blekfet Therein lies the problem IMV. Numbers obviously cannot have quotes around them. https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html - states 
"This means that if you index a number in quotes ("123"), it will be mapped as type string, not type long. However, if the field is already mapped as type long, then Elasticsearch will try to convert the string into a long, and throw an exception if it can’t."

**Comment by blekfet** [comment] 2016-11-10 14:46
@waqark3389 Yes, I found that. Now I'm trying to find a way for elastic to return the numerical value and not the inserted value. Not sure if it is possible however.

I'm not in control of the insertions in the index and would like to find a way to format the numbers correctly even if they are inserted with quotes.

**Comment by waqark3389** [comment] 2016-11-10 14:58
@blekfet Thats a tough one, I dont think its possible. But may be worth bringing it up on the elastic forums to find out what your options are.

**Comment by blekfet** [comment] 2016-11-10 15:12
@waqark3389 Just posted that question [here](https://discuss.elastic.co/t/return-numerical-values-without-quotes/65687)

**Comment by blekfet** [comment] 2016-11-11 10:05
I resolved my issue by changing the sorting algorithm in `public\app\core\table_model.ts` with a "natural sorting" algorithm.

I guess that is not optimal for all use cases.

**Comment by waqark3389** [comment] 2016-11-11 10:09
@blekfet Nice to see you fixed it. But this is a very temp solution :p. 
@torkelo Maybe a setting in table panel options?

**Comment by codeincarnate** [comment] 2023-03-03 11:08
Things have changed dramatically since this issue was opened and I think this has likely been addressed in the move over to data frames and the use of `react-table`. If this still happens to be an issue please feel free to re-open!

**Closed by codeincarnate** 2023-03-03 11:08 UTC
Labels: type/feature-request, help wanted, prio/medium, area/panel/table
