### ISSUE TITLE
Problem in ec2_instance_attribute when templating with cloudwatch datasource

### ISSUE THREAD

**Issue by gkope** [grafana/grafana#9839] opened 2017-11-09 16:19 UTC
- What Grafana version are you using?

v4.6.1

- What datasource are you using?

Cloudwatch

- What OS are you running grafana on?

Kubernetes V1.6.4 on CoreOS
Running image from grafana/grafana

- What did you do?

Hey guys,

We are using Grafana here in my company in version v4.6.1 and since we updated to version v4.6.x, our dashboards using `templating` with `ec2_instance_attribute` doing ec2 tag filtering is not working anymore.

On our latest version `v4.5.2`, the dashboard was working properly.

Information

You can see on the screenshot, our templating screen with the query that was working on version v4.5.2, and as you can see on the right side of the screen, there is an error:

![image](https://user-images.githubusercontent.com/3788237/32613572-74beacf6-c552-11e7-9126-8326c896ba1e.png)

If we try to do a query without tag filtering, only a blank `{}`, you can see that the same results are returning:

![image](https://user-images.githubusercontent.com/3788237/32613852-0fcebb96-c553-11e7-8893-131b4264c3a4.png)

I also tested the queries above:
```
ec2_instance_attribute($region, Tag["Release"], [{"Key":"App","Value":"elasticsearch"},{"Key":"Product","Value":"search"},{"Key":"Env","Value":"prod"}])

ec2_instance_attribute($region, Tags.Release, [{"Key":"App","Value":"elasticsearch"},{"Key":"Product","Value":"search"},{"Key":"Env","Value":"prod"}])

ec2_instance_attribute($region, Tags.Release,  {"tag:App": [ "elasticsearch" ] , "tag:Product": [ "search" ], "tag:Env": [ "prod" ] })
```

Is there a new way of doing ec2 tag filtering in new versions?

Also, sorry if this is already an open issue about this, I was not able to find it.

Any more needed information, I'm available for questions.

Thanks,

- What was the expected result?

The expected result was to return only instances tagged with values passed in Filters block.

```console
$ aws ec2 describe-instances --filters Name=tag-key,Values=App Name=tag-value,Values=elasticsearch Name=tag-key,Values=Product Name=tag-value,Values=search Name=tag-key,Values=Env Name=tag-value,Values=prod | jq -r '.Reservations[].Instances[].Tags' | grep Release -A1
    "Key": "Release",
    "Value": "pdp"
--
    "Key": "Release",
    "Value": "pdp"
--
    "Key": "Release",
    "Value": "pdp"
--
    "Key": "Release",
    "Value": "pdp"
```
- What happened instead?

Not filtering by tags, the filters simply don't work.

**Comment by torkelo** [comment] 2017-11-09 16:45
duplicate of https://github.com/grafana/grafana/issues/9667

**Closed by torkelo** 2017-11-09 16:45 UTC
