### ISSUE TITLE
Influx: Regressions w Custom Variable + InfluxQL: using float values errors (Grafana v9.4.1)

### ISSUE THREAD

**Issue by emoruzzi** [grafana/grafana#63973] opened 2023-03-01 19:08 UTC
**What happened**:
Using custom variables no longer work with float values as of Grafana v9.4.1 using InfluxQL.

v9.4.1
<img width="641" alt="v9 4 1" src="https://user-images.githubusercontent.com/9886846/222238950-ec1e3182-c41d-4d87-891e-2a4f51c30cfc.png">
v.9.3.8
<img width="556" alt="v9 3 8" src="https://user-images.githubusercontent.com/9886846/222238972-c153d70d-48cb-430c-9efa-7a4df043bfab.png">

**What you expected to happen**:
The query would use the custom variable.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup a `custom variable` in grafana using any float value.
- Use `custom variable` in a influxql query.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.4.1
- Data source type & version: InfluxDB Using InfluxQL (Running InfluxDB 2.5.1)
- https://hub.docker.com/r/grafana/grafana
- Grafana plugins: None

<details>
  <summary>Dashboard JSON</summary>

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 24,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "influxdb",
        "uid": "ATWEbFv4k"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green"
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 9,
        "x": 2,
        "y": 0
      },
      "id": 2,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "textMode": "auto"
      },
      "pluginVersion": "9.4.1",
      "targets": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "ATWEbFv4k"
          },
          "query": "SELECT count(watts) * $test_var FROM \"ups_status\" WHERE $timeFilter \n",
          "rawQuery": true,
          "refId": "A",
          "resultFormat": "time_series"
        }
      ],
      "title": "Test Var: $test_var",
      "type": "stat"
    }
  ],
  "refresh": "",
  "revision": 1,
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "1.3",
          "value": "1.3"
        },
        "hide": 0,
        "includeAll": false,
        "label": "test_var",
        "multi": false,
        "name": "test_var",
        "options": [
          {
            "selected": true,
            "text": "1.3",
            "value": "1.3"
          }
        ],
        "query": "1.3",
        "queryValue": "1.3",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-15m",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Test Custom Var",
  "uid": "d9vse1x4z",
  "version": 3,
  "weekStart": ""
}
```
</details>

<details>
  <summary>v9.3.8 Query Inspector</summary>

```
{
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/2/query",
    "params": {
      "db": "ups",
      "q": "SELECT count(watts) * 1.3 FROM \"ups_status\" WHERE time >= now() - 15m and time <= now() \n",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms",
    "hideFromInspector": false
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "ups_status",
            "columns": [
              "time",
              "count"
            ],
            "values": [
              [
                1677695769535,
                55.9
              ]
            ]
          }
        ]
      }
    ],
    "executedQueryString": "SELECT count(watts) * 1.3 FROM \"ups_status\" WHERE time >= now() - 15m and time <= now() \n"
  }
}
```
</details>

<details>
  <summary>v9.4.1 Query Inspector</summary>

```
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "datasource": {
            "type": "influxdb",
            "uid": "ATWEbFv4k"
          },
          "query": "SELECT count(watts) * 1\\.3 FROM \"ups_status\" WHERE $timeFilter \n",
          "rawQuery": true,
          "refId": "A",
          "resultFormat": "time_series",
          "alias": "",
          "adhocFilters": [],
          "limit": "",
          "measurement": "",
          "policy": "",
          "slimit": "",
          "tz": "",
          "datasourceId": 2,
          "intervalMs": 500,
          "maxDataPoints": 1388
        }
      ],
      "range": {
        "from": "2023-03-01T18:33:38.633Z",
        "to": "2023-03-01T18:48:38.633Z",
        "raw": {
          "from": "now-15m",
          "to": "now"
        }
      },
      "from": "1677695618633",
      "to": "1677696518633"
    },
    "hideFromInspector": false
  },
  "response": {
    "message": "An error occurred within the plugin",
    "messageId": "plugin.downstreamError",
    "statusCode": 500,
    "traceID": ""
  }
}
```
</details>

**Comment by emoruzzi** [comment] 2023-03-01 19:10
Inspecting the 9.4.1 query, it looks like something is trying to double escape it - which is likely the failure point
`SELECT count(watts) * 1\\.3 FROM \"ups_status\"`

**Comment by zuchka** [comment] 2023-03-01 21:22
thanks @emoruzzi 

could you please copy and paste all relevant data using the `panel --> more --> get help` workflow in the panel's dropdown menu? This will help up mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:

https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

![CleanShot 2023-01-31 at 14 40 21](https://user-images.githubusercontent.com/37156449/215916832-8d29d39c-57a1-40a7-a6e0-bfe584ea8bd4.gif)

**Comment by af7567** [comment] 2023-03-11 16:12
I just looked at one of my dashboards which were broken because of this problem (after upgrading from 9.3.x to 9.4.3) and it was suddenly working again somehow. It turns out this was just because of some data cached by the browser and after forcing a reload the variables were broken as expected.
Just adding that in case it helps at all with tracking the problem down.

**Comment by nickmoeck** [comment] 2023-03-14 03:30
This seems to be affecting more than just floats as variables in Influx queries. On 9.3.4, I'm seeing the same type of double escaping on the following variable value:

`"provider" =~ /^(Amazon EC2|Google Cloud)$/`

The slashes get double escaped to this in the query inspector:

`\"provider\" =~ \\/\\^\\(Amazon EC2\\|Google Cloud\\)\\$\\/`

On 9.3.1, it ends up as follows in the query inspector:

`\"provider\" =~ /^(Amazon EC2|Google Cloud)$/`

**Comment by Phaze-III** [comment] 2023-03-18 12:01
I have the same issue after upgrading from 9.3.8 to 9.4.3 with InfluxQL but using query type variables returning a single value with a float. It appears that in 9.4.3 single value variables are regex-escaped where 9.3.x uses the raw format (no escaping). According to the documentation at https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#multi-value-variables (Troubleshoot multi-value variables) this should not happen:

>Troubleshoot multi-value variables
>Automatic escaping and formatting can cause problems and it can be tricky to grasp the logic behind it. Especially for InfluxDB and Prometheus where the use of regex syntax requires that the variable is used in regex operator context.

>If you do not want Grafana to do this automatic regex escaping and formatting, then you must do one of the following:

> * Turn off the Multi-value or Include All option options.
> * Use the [raw variable format](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#raw).

In my case the settings for Multi-value and Include All are turned off but in 9.4.3 the result is regex escaped. It looks like a similar thing happens in 9.4.3 with custom variables containing regex special characters.

**Comment by soloam** [comment] 2023-03-18 12:03
This still happens even clearing browser cached information, or even in incognito mode!

**Comment by af7567** [comment] 2023-03-30 10:24
This seems to be fixed now in grafana 9.4.7. I upgraded from 9.4.3 to 9.4.7 so it could have been fixed in some version between them.

**Comment by Worty** [comment] 2023-03-30 12:34
Just upgraded to 9.4.7 everything is working fine now 👍

**Comment by vincent-olivert-riera** [comment] 2023-03-31 01:37
> Just upgraded to 9.4.7 everything is working fine now +1

Be very careful with 9.4.7. It has a bug in the bar charts where the colors of the bars don't match with the ones in the legend: https://github.com/grafana/grafana/issues/65299
You could be looking at one of those charts and getting wrong information (which is worse than no information).

**Comment by itsmylife** [comment] 2023-04-14 18:10
The [PR](https://github.com/grafana/grafana/pull/65875) is merged. The next version will have the fix.

**Closed by itsmylife** 2023-04-14 18:10 UTC
Labels: datasource/InfluxDB, area/dashboard/templating, type/regression, effort/medium
