### ISSUE TITLE
Azure logs are not sorted correctly(Log Analytics)

### ISSUE THREAD

**Issue by zbbkeepgoing** [grafana/grafana#20547] opened 2019-11-21 09:32 UTC
**What happened**:

When only  show 'TimeGenerated' column
Sorted correctly, result is asc where query by asc
![image](https://user-images.githubusercontent.com/42572980/69324881-37d2ce00-0c84-11ea-8c69-8988ea6bfc9a.png)

But When show more than 'TimeGenerated' column
Sorted reversal, result is desc where query by asc
![image](https://user-images.githubusercontent.com/42572980/69325058-81bbb400-0c84-11ea-9f94-bdc26469584a.png)

**What you expected to happen**:

Sorted correctly

**How to reproduce it (as minimally and precisely as possible)**:

Use azure log analytics by azure monitor datasource

**Anything else we need to know?**:

I build the image from master branch

**Environment**:
- Grafana version: master branch
- Data source type & version: host path  
- OS Grafana is installed on: ubuntu:18.04
- User OS & Browser: chrome
- Grafana plugins: azure monitor
- Others:

**Comment by hugohaggmark** [comment] 2020-06-11 12:45
Thank you for reporting this @zbbkeepgoing and very sorry for the late feedback. I can confirm this was a bug but on it's not a bug on latest master anymore 79fea5df2aeb72aafe91b118be031901d8772260. I will close this issue for now but we can always reopen it if new evidence is found.

**Closed by hugohaggmark** 2020-06-11 12:45 UTC
Labels: needs investigation
