### ISSUE TITLE
InfluxDB SQL Query: Grafana doesn't show expected error messages, instead show success with no data

### ISSUE THREAD

**Issue by appletreeisyellow** [grafana/grafana#89574] opened 2024-06-21 18:38 UTC
### What happened?

A query failed and returned an error message in InfluxDB but Grafana showed that the query was successful and returned no data.  

### What did you expect to happen?

Grafana should return the error message

### Did this work before?

No

### How do we reproduce it?

You can skip the first two steps if you know how to write data into InfluxDB and how to add InfluxDB as datasource in Grafana

## 1. Write sample data into InfluxDB

1. If you don't have an InfluxDB, you can sign up a free account here: https://cloud2.influxdata.com/signup
2. After log into your InfluxDB account, you can create a bucket and write data into it
    1. Click "Add Data", then click "UPLOAD LINE PROTOCOL"
       ![Screenshot 2024-06-21 at 1 13 04 PM](https://github.com/grafana/grafana/assets/14298407/0e2e12b5-5ee1-4c2b-a72d-53b0a36f15ef)
    2. You will see a page look like this, then click "ENTER MANUALLY"
       ![Screenshot 2024-06-21 at 1 17 16 PM](https://github.com/grafana/grafana/assets/14298407/6d6ed6e7-255d-482a-864a-965b82511910)
    4. Copy sample data from [here](https://github.com/influxdata/influxdb2-sample-data/blob/master/air-sensor-data/air-sensor-data.lp) and paste into the text area
    ![Screenshot 2024-06-21 at 1 16 53 PM](https://github.com/grafana/grafana/assets/14298407/dc10394a-0d70-4a2a-8fc0-bf8813d9e170)
    5. After click "WRITE DATA", you will see the data is uploaded successfully
    ![Screenshot 2024-06-21 at 1 19 54 PM](https://github.com/grafana/grafana/assets/14298407/36e2126c-57e0-4798-baec-dfedca855afb)

## 2. Add InfluxDB as datasource in Grafana

Follow the instructions from here: https://docs.influxdata.com/influxdb/cloud-serverless/process-data/visualize/grafana/#influxdb-data-source

When adding a new InfluxDB datasource, make sure to set the "Query language" as "SQL" to reproduce

## 3. Explore Data

Run a basic query in Grafana to see if you can query data successfully. With the sample data from step 1, you can get data using this query:
```sql
SELECT "sensor_id" FROM "airSensors" WHERE "time" >= $__timeFrom AND "time" <= $__timeTo
```
The result looks like this:

![Screenshot 2024-06-21 at 1 24 42 PM](https://github.com/grafana/grafana/assets/14298407/afac2cc1-ddb9-424c-acfe-5f9467d7c2f9)

## 4. Reproduce the bug

Then run this query:
```sql
SELECT array_to_string(array_agg("sensor_id"),',')
FROM (SELECT "sensor_id" FROM "airSensors" WHERE "time" >= $__timeFrom AND "time" <= $__timeTo)
```

I'm expecting an error message, something like 'rpc error: code = Internal desc = Join Error (panic)', but I don't see any. Instead, Grafana shows the query was successful with no data:

![Screenshot 2024-06-21 at 1 35 17 PM](https://github.com/grafana/grafana/assets/14298407/d68122a4-4876-421e-b842-39a2e761560e)

You can also use your own data to reproduce by having `array_to_string(array_agg("column_name"),',')` in the SELECT statement

### Environment (with versions)?

Grafana: Grafana v10.4.1 (d94d597d84)
OS: MacOS 13.5 (22G74)
Browser: Chrome

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

InfluxDB

**Comment by appletreeisyellow** [comment] 2024-06-24 21:06
This might be helpful: https://github.com/apache/arrow/issues/42145

**Comment by aangelisc** [comment] 2024-09-25 11:29
Hi @appletreeisyellow,

I'll be closing this issue as we're unable to reproduce. If you can provide a more detailed reproduction please re-open the issue and share with us!

**Closed by aangelisc** 2024-09-25 11:29 UTC
Labels: datasource/InfluxDB, prio/low, triage/needs-confirmation
