### ISSUE TITLE
Grafana "ok" alert- missing tags

### ISSUE THREAD

**Issue by iiidddaaannn102** [grafana/grafana#13258] opened 2018-09-12 20:16 UTC
### What Grafana version are you using?
5.3.0 beta1

### What datasource are you using?
Influxdb

### What OS are you running grafana on?
Windows

### What did you do?
Create an alert that triggered with "groupby" on many hosts.

### What was the expected result?
That when the "ok" alert is triggered it will be with specific tags(host, url, device...)
Because the "alerting" alert  automatic goes on specific host and when the ok send i dont know to which host or tag it means, i know just on which rulename..this is not enough information.

It will be nice to have all alerting information(without message, and information that relevant to critical alert) on the ok alerts.

Hope you understand me..

Idan

**Comment by marefr** [comment] 2018-09-13 07:04
Duplicate of #11560

**Closed by marefr** 2018-09-13 07:04 UTC
