### ISSUE TITLE
Bug: Cannot select text from legend and table panel (only works in panel edit/view mode)

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#2083] opened 2015-06-01 07:25 UTC
We have a lot of dashboards with wildcards and in the resulting metrics list it is oftentimes desired to do a copy a metric name for a subsequent paste in some other dashboard for a more drill-down view.

Currently on a panel from a main dashboard page you cannot select to copy whereas on a 'view' full page of a panel you can (even though you have to do your copy before you let up on your mouse).  

Request is to allow selecting for copy on both the main view and a 'view' full page view.

**Comment by torkelo** [comment] 2016-01-20 14:56
this is caused by dragable property on panels. Not sure what the best solution is, but a solution would be great

**Comment by jeffsmith82** [comment] 2016-03-04 10:24
+1

**Comment by waqark3389** [comment] 2016-03-04 10:26
+1

**Comment by shamasis** [comment] 2016-03-24 09:31
+1 ... seems like a bug and not a feature-request. :-)

**Comment by eostermueller** [comment] 2016-04-23 19:08
So @torkelo, I've seen two different dragable things:  dragable graph names for relocating graphs on a panel, and then drag to alter timeframe.  Would it be possible to put the legend in some kind of a subpanel so we could then set dragable=false ?

**Comment by selbyk** [comment] 2016-05-19 00:32
+1

**Comment by c2415565** [comment] 2016-05-31 11:51
+1

**Comment by phateuk** [comment] 2016-06-06 14:24
+1 Would love to be able to select and copy from legends especially

**Comment by futamint** [comment] 2016-06-15 16:33
+1

**Comment by valhallasw** [comment] 2016-08-12 09:11
At least for the table panel, it seems the issue is not with the `-webkit-user-drag: element;` propety, but with the `-webkit-user-select: none;` property. 

* If I change that property to `-webkit-user-select: text;`, all text becomes selectable.
* The panel is still draggable, but not when you click the title (because that selects the title)
* Setting `-webkit-user-select: none` on the title div does not seem to solve this

**Comment by tbarbugli** [comment] 2016-09-30 12:52
+1 this is indeed really annoying for us :)

**Comment by waqark3389** [comment] 2016-11-08 10:10
@torkelo Any progress on this? :) 
Very annoying not being able to select and copy.

**Comment by sfingram** [comment] 2016-12-20 00:28
You can disable dragging, and thus enable text selection, in a panel by making the panel fullscreen.
See [public/app/features/dashboard/row/row.html](https://github.com/grafana/grafana/blob/2d19af601a2e2566357a48844869cc1d57418a08/public/app/features/dashboard/row/row.html) : 58
```html
<div ng-repeat="panel in ctrl.row.panels track by panel.id" class="panel" ui-draggable="!ctrl.dashboard.meta.fullscreen" drag="panel.id" ui-on-drop="ctrl.onDrop($data, panel)" drag-handle-class="drag-handle" panel-width>
```
You can get to/from fullscreen mode by clicking the panel and pressing the 'v' key.  So click, press 'v', select and copy, then press v again.  A little annoying, but less annoying than not copying at all.

**Comment by frankie7** [comment] 2017-01-10 10:34
+1 ... it would be great to copy some text from the text/html panel

**Comment by discoduck2x** [comment] 2017-01-13 12:33
+1 any update?

**Comment by purduemike** [comment] 2017-02-01 22:07
+1

**Comment by Celibat1** [comment] 2017-02-16 13:36
+1

**Comment by wokr** [comment] 2017-02-16 13:43
+1

**Comment by Pigueiras** [comment] 2017-02-20 11:13
This one is annoying, IMO at least when the dashboard is not editable + hide controls the `drag` property should be disabled no? (And then, this shouldn't happen anymore).

**Comment by datamuc** [comment] 2017-02-21 08:32
On my Firefox on Linux I can press ALT and select text on the dragable panels.

**Comment by ftoresan** [comment] 2017-03-14 15:33
+1

**Comment by bogdanstoica35** [comment] 2017-03-21 13:22
Any updates on this?!

**Comment by StephenPCG** [comment] 2017-04-10 08:54
+1

**Comment by K4LiN** [comment] 2017-04-12 18:35
Maybe adding "user-select: all;" to elements that you want to be able to select could be a good way to do this?

**Comment by datamuc** [comment] 2017-04-17 13:54
-1

Close it and bug the browser vendors instead. (Firefox allows you to select the text while pressing ALT)

**Comment by valhallasw** [comment] 2017-04-17 16:56
> -1
>
> Close it and bug the browser vendors instead. (Firefox allows you to select the text while pressing ALT)

The browsers correctly implement `webkit-user-select: none` to mean 'do not allow the user to select the text'. As far as I can see, this is an issue with Grafana's CSS, not with how browsers render the CSS. (Firefox' alt-select is [allowed but not required](https://drafts.csswg.org/css-ui-4/#valdef-user-select-none) by the relevant CSS spec).

**Comment by andy-corcoran** [comment] 2017-06-15 14:24
+1

**Comment by iziang** [comment] 2017-06-18 10:13
+1

**Comment by peter-gerhard** [comment] 2017-07-13 15:22
+1

**Comment by andrewmchen** [comment] 2017-08-01 01:29
+1

**Comment by albertvaka** [comment] 2017-08-08 13:36
Seems really easy to fix, and still pending since 2015 D:

**Comment by dpereira** [comment] 2017-08-19 00:07
+1

**Comment by crummy** [comment] 2017-08-22 14:55
Here's a workaround, works in Chrome and probably elsewhere:

Right click the Grafana dashboard (anywhere), click Inspect. Click the Console tab, and enter:
`$('.panel').each(function(i, obj) { obj.setAttribute("draggable", "false"); });`

Now you can copy and paste text. Note that this will break dragging, and will be gone after a refresh.

**Comment by keel** [comment] 2017-08-30 06:24
Also, you can do this in Inspect's console:
`$('.table-panel-wrapper').attr ('style','user-select:text');`

**Comment by denglitong** [comment] 2017-09-08 08:51
+1 Very annoying not being able to select and copy.

**Comment by birengoodco** [comment] 2017-10-16 14:07
+1

**Comment by sjdy521** [comment] 2017-10-16 14:37
+1 with the latest version

**Comment by CyberLine** [comment] 2017-11-16 10:08
+1

**Comment by silveraignacio** [comment] 2017-11-27 17:12
+1

**Comment by Padrio** [comment] 2017-11-28 08:00
+1

**Comment by jiacai2050** [comment] 2017-12-19 07:12
Thanks @crummy , I create a bookmarklet based on your solution (URL encoded).
For anyone else, Add a bookmark with location below:

```
javascript:(function()%20%7B%0A%24('.panel').each(function(i%2C%20obj)%20%7B%20obj.setAttribute(%22draggable%22%2C%20%22false%22)%3B%20%7D)%3B%0A%7D)()
```

With this, just one click then you can copy as usual

**Comment by ilFuma** [comment] 2017-12-20 07:41
+1

**Comment by torkelo** [comment] 2017-12-20 13:17
this is fixed by using the new grid engine https://www.youtube.com/watch?v=BC_YRNpqj5k

**Closed by torkelo** 2017-12-20 13:17 UTC
Labels: comp: dashboard, help wanted, P3: important, type: bug, type: feature request
