### ISSUE TITLE
Inspect data with Table panel does not print all datas

### ISSUE THREAD

**Issue by Tristou27** [grafana/grafana#27392] opened 2020-09-04 14:09 UTC
**What happened**:
When I try to view raw data, via the Inspect > Data panel option, they are very few datas printed in comparison with the real raw results. 
I'm trying to export a table into a CSV file, but in the CSV I get only 15-20 lines instead of 2500.
In the "query" tab, I see that the query returned 2500 rows, but they are not printed out in "Data" tab and not present in the CSV file. In the "Panel JSON" tab, all my datas are present. 

**What you expected to happen**:

I'm expecting that all the datas returned by my query are present in the "Data" tab and in the exported CSV file.

**How to reproduce it (as minimally and precisely as possible)**:

Use a Table panel constructed via a query with multiple field selected. Try to export datas into CSV format, the file should be abnormally sized and contain only a few datas among all returned datas.

**Anything else we need to know?**:

**Environment**:
 Grafana version: 7.1.5
- Data source type & version: InfluxDB v1.7
- OS Grafana is installed on: Ubuntu 19.10
- User OS & Browser: Windows + Firefox
- Grafana plugins: None
- Others: None

**Comment by torkelo** [comment] 2020-09-04 14:21
duplicate of https://github.com/grafana/grafana/issues/26460 

If you can paste the raw query results and the panel json to that issue that could help as we have been unable to replicate it

**Closed by torkelo** 2020-09-04 14:21 UTC

**Comment by Tristou27** [comment] 2020-09-08 07:53
Hello,

Sorry for the delay.
Please find attached the output you've requested. I've also added a screenshot of what "Inspect > Data" is returning as well as the CSV file. You will see that over 350 results in the query, only 2 lines appears in the CSV file..

Thank you for your support.

[raw_query_results.json.txt](https://github.com/grafana/grafana/files/5186872/raw_query_results.json.txt)
[panel_json.json.txt](https://github.com/grafana/grafana/files/5186873/panel_json.json.txt)
[panel_data.json.txt](https://github.com/grafana/grafana/files/5186874/panel_data.json.txt)
![inspect_data](https://user-images.githubusercontent.com/32581367/92448531-05657380-f1b9-11ea-85f2-cbe01f8c81b5.GIF)

[Memory Per Process-data-as-seriestocolumns-2020-09-08 09_47_06.csv.txt](https://github.com/grafana/grafana/files/5186881/Memory.Per.Process-data-as-seriestocolumns-2020-09-08.09_47_06.csv.txt)
