### ISSUE TITLE
Grafana 7.5 Time Series panel tooltip X-axis alignment with different length data frames in query response

### ISSUE THREAD

**Issue by kristjansb** [grafana/grafana#32172] opened 2021-03-19 18:41 UTC
**What happened**: Time series panel tooltip values are out of sync with x-axis position. See screen recording.

![time_series_panel_x-axis_tooltip_alignment](https://user-images.githubusercontent.com/7348565/111827657-874cfc80-88c0-11eb-9dce-477a5d48faa9.gif)

**What you expected to happen**: Tooltip displays values matching the cursor position.

**How to reproduce it (as minimally and precisely as possible)**: Create time series panel with TestData DB data source. Configure two queries A & B. Set query A to the Random Walk scenario and query B to CSV Metric Values scenario and inspect tooltip.

**Anything else we need to know?**: Occurs on 7.5.0-beta1 and beta2. Fine on 7.4.x.

**Environment**:
- Grafana version: grafana-enterprise-7.5.0-beta1 & beta2
- Data source type & version: TestData DB & Time Series panel
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome on Win10
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-03-22 07:38
Can you try beta2 ? think this https://github.com/grafana/grafana/pull/32098 PR might solve this

**Comment by zoltanbedi** [comment] 2021-03-22 12:53
I couldn't reproduce this in https://play.grafana.org/d/ZN-GryEMz/time-series-bug?orgId=1 so I'm going to close this issue. If you think this is still an issue we can reopen it.

**Comment by kristjansb** [comment] 2021-03-22 12:59
I tried both 7.5.0-beta1 and 7.5.0-beta2 with same results. Does not occur on 7.4.x, which I suspect is what is running on play.grafana.org? For reference, I'm installing from the enterprise RPM if that makes a difference.

**Comment by zoltanbedi** [comment] 2021-03-22 13:03
Can you show your dashboard.json so I can try to reproduce that?

**Comment by kristjansb** [comment] 2021-03-22 13:14
It actually seems to be related to the test data DB's non random walk scenarios. It looks like two queries A & B with the random walk scenario have correct timestamps. If the B query uses a different scenario the timestamps get condensed on the left.

`{
  "__inputs": [
    {
      "name": "DS_TESTDATA_DB",
      "label": "TestData DB",
      "description": "",
      "type": "datasource",
      "pluginId": "testdata",
      "pluginName": "TestData DB"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.5.0-beta2"
    },
    {
      "type": "panel",
      "id": "graph",
      "name": "Graph",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "testdata",
      "name": "TestData DB",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "timeseries",
      "name": "Time series",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "${DS_TESTDATA_DB}",
      "fieldConfig": {
        "defaults": {
          "unit": "short"
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 6,
      "interval": "1m",
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "7.5.0-beta2",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "alias": "",
          "csvWave": {
            "timeStep": 60,
            "valuesCSV": "0,0,2,2,1,1"
          },
          "lines": 10,
          "points": [],
          "pulseWave": {
            "offCount": 3,
            "offValue": 1,
            "onCount": 3,
            "onValue": 2,
            "timeStep": 60
          },
          "queryType": "randomWalk",
          "refId": "A",
          "scenarioId": "random_walk",
          "seriesCount": 2,
          "spread": 1,
          "stream": {
            "bands": 1,
            "noise": 2.2,
            "speed": 250,
            "spread": 3.5,
            "type": "signal"
          },
          "stringInput": ""
        },
        {
          "alias": "",
          "csvWave": {
            "timeStep": 60,
            "valuesCSV": "0,0,2,2,1,1"
          },
          "hide": false,
          "lines": 10,
          "points": [],
          "pulseWave": {
            "offCount": 3,
            "offValue": 1,
            "onCount": 3,
            "onValue": 2,
            "timeStep": 60
          },
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stream": {
            "bands": 1,
            "noise": 2.2,
            "speed": 250,
            "spread": 3.5,
            "type": "signal"
          },
          "stringInput": "1,20,90,30,5,0"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Graph",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "datasource": "${DS_TESTDATA_DB}",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 10,
            "gradientMode": {
              "label": "None",
              "value": "none"
            },
            "hideFrom": {
              "graph": false,
              "legend": false,
              "tooltip": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 6,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": true
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "short"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 5,
      "interval": "1m",
      "options": {
        "graph": {},
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltipOptions": {
          "mode": "multi"
        }
      },
      "pluginVersion": "7.4.0-beta1",
      "targets": [
        {
          "alias": "",
          "csvWave": {
            "timeStep": 60,
            "valuesCSV": "0,0,2,2,1,1"
          },
          "lines": 10,
          "points": [],
          "pulseWave": {
            "offCount": 3,
            "offValue": 1,
            "onCount": 3,
            "onValue": 2,
            "timeStep": 60
          },
          "queryType": "randomWalk",
          "refId": "A",
          "scenarioId": "random_walk",
          "seriesCount": 2,
          "spread": 1,
          "stream": {
            "bands": 1,
            "noise": 2.2,
            "speed": 250,
            "spread": 3.5,
            "type": "signal"
          },
          "stringInput": ""
        },
        {
          "alias": "",
          "csvWave": {
            "timeStep": 60,
            "valuesCSV": "0,0,2,2,1,1"
          },
          "hide": false,
          "lines": 10,
          "points": [],
          "pulseWave": {
            "offCount": 3,
            "offValue": 1,
            "onCount": 3,
            "onValue": 2,
            "timeStep": 60
          },
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stream": {
            "bands": 1,
            "noise": 2.2,
            "speed": 250,
            "spread": 3.5,
            "type": "signal"
          },
          "stringInput": "1,20,90,30,5,0"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Time Series",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Time Series Panel eval",
  "uid": "Q3crpOLGk",
  "version": 3
}`

**Comment by kristjansb** [comment] 2021-03-22 13:16
I checked the version on play moments after posting the previous comment. I was able to reproduce it on the dashboard you shared by setting the scenario in query B to `CSV Metric Values`.

**Comment by zoltanbedi** [comment] 2021-03-22 13:32
@dprokop probably something you should check.

**Closed** 2021-03-26 08:56 UTC
Labels: area/panel/timeseries, priority/important-soon, type/bug
