### ISSUE TITLE
Template variables are not supported in alert queries

### ISSUE THREAD

**Issue by ESLCH** [grafana/grafana#36110] opened 2021-06-24 08:56 UTC
**Template variables are not supported in alert queries**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:8.0
- Data source type & version:prometheus
- OS Grafana is installed on:Linux CentOs 64bits
- User OS & Browser:chrome 
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-06-24 13:30
duplicate of https://github.com/grafana/grafana/issues/6557  (closed, not implemented)

**Closed by torkelo** 2021-06-24 13:30 UTC
