### ISSUE TITLE
Tooltips show mismatched label colors

### ISSUE THREAD

**Issue by thefeli73** [grafana/grafana#36886] opened 2021-07-18 09:59 UTC
**What happened**:
Tooltip (show all labels) colors are shifted by one color.
![image](https://user-images.githubusercontent.com/39433012/126062701-e259eccb-6684-43c8-9a4b-3a95ef80b6f0.png)

**What you expected to happen**:
Tooltip colors should be the same as in the table:
![image](https://user-images.githubusercontent.com/39433012/126062728-4d3af3e1-6afa-4074-a853-9c8ea0ca57fc.png)
 

**How to reproduce it (as minimally and precisely as possible)**:
Create timeseries with multiple labels. It will look fine initially and on page reload, but when the dashboard is refreshed (either by timeout or by pressing 'refresh dashboard' button) all tooltips are no longer accurate, and only the labels in the table below show the matching colors 

**Anything else we need to know?**:
Panel json used in example:
`{
  "id": 49,
  "gridPos": {
    "h": 13,
    "w": 13,
    "x": 11,
    "y": 1
  },
  "type": "timeseries",
  "title": "Network activity",
  "transformations": [
    {
      "id": "renameByRegex",
      "options": {
        "regex": "(:9100)",
        "renamePattern": ""
      }
    }
  ],
  "maxDataPoints": 2000,
  "interval": "15s",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 60,
        "gradientMode": "opacity",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 3,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [],
      "unit": "Bps"
    },
    "overrides": []
  },
  "options": {
    "tooltip": {
      "mode": "multi"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "exemplar": true,
      "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"enp2s0|enp0s25|eth0\", instance=~\"$node\"}[5m])) by (instance)",
      "hide": false,
      "interval": "",
      "intervalFactor": 1,
      "legendFormat": "upload: {{instance}} ",
      "refId": "A"
    },
    {
      "exemplar": true,
      "expr": "- sum(rate(node_network_receive_bytes_total{device=~\"enp2s0|enp0s25|eth0\", instance=~\"$node\"}[5m])) by (instance)",
      "hide": false,
      "interval": "",
      "intervalFactor": 1,
      "legendFormat": "download: {{instance}} ",
      "refId": "B"
    }
  ],
  "datasource": null
}`

**Environment**:
- Grafana version: Grafana v8.0.6 (68fe9e3431)
- Data source type & version: Prometheus v2.28.1 revision: b0944590a1c9a6b35dc5a696869f75f422b107a1
- OS Grafana is installed on: Docker (image grafana/grafana)
- User OS & Browser: Windows, Chrome 91
- Grafana plugins: Default
- Others:

**Comment by benrubson** [comment] 2021-07-18 19:09
Duplicate of #36385

**Closed** 2021-07-19 06:37 UTC
