### ISSUE TITLE
Grafana 5.4 on docker for armv7 not working

### ISSUE THREAD

**Issue by rtmaster** [grafana/grafana#14304] opened 2018-12-04 14:37 UTC
Please include this information:
### What happened instead? Docker logs shows: exec user process caused "exec format error"

 
**If I run the following**

docker run --rm mplatform/mquery grafana/grafana

**I get:**

Image: grafana/grafana
 * Manifest List: No
 * Supports: amd64/linux

Does this mean that the docker image does not have a manifest for armv7?
Any other option to run Grafana 5.4 on a docker for arm?

**Comment by marefr** [comment] 2018-12-04 14:59
Duplicate of #13186

**Closed by marefr** 2018-12-04 14:59 UTC
