### ISSUE TITLE
[Feature request] Turn off "OK" notifications

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#8463] opened 2017-05-24 15:37 UTC
Please add the ability to turn off "OK" notifications. Sometimes too much notifications distracting in slack.

[Feature request]. 

- What Grafana version are you using? 4.2.0
- What datasource are you using? Graphite
- What OS are you running grafana on? Ubunty
- What did you do? Slack alerts and notifications
- What was the expected result? 
**Please add the ability to turn off "OK" notifications. Sometimes too much notifications distracting in slack.** 
- What happened instead? N/A
- If related to metric query / data viz: N/A

**Comment by torkelo** [comment] 2017-05-25 18:38
duplicate of https://github.com/grafana/grafana/issues/6696

**Closed by torkelo** 2017-05-25 18:38 UTC

**Comment by TomasJavurek** [comment] 2018-04-19 13:50
Same problem.
