### ISSUE TITLE
Using wildcard in adhoc filter based on Elasticsearch DataSource

### ISSUE THREAD

**Issue by mrjoubari** [grafana/grafana#13836] opened 2018-10-25 14:56 UTC
### What did you do?
 I tried to filter a dashboard using a wildcard in the ad hoc variable

![Example](https://discourse-cdn-sjc2.com/standard14/uploads/grafana/original/2X/0/0571dcdb6dd8ed785aba5a7e8c221f807b396304.png)

### What was the expected result?
All rows with txt field containing a value that start with "LAT"

### What happened instead?
Empty result

Is it supported ? if not, is it planned ?

Thanks a lot!!

Post on the community: [community.grafana.com](https://community.grafana.com/t/how-to-use-wildcard-in-adhoc-filter-based-on-elasticsearch-datasource/11335)``

**Comment by torkelo** [comment] 2018-10-25 18:00
duplicate of https://github.com/grafana/grafana/issues/12447

**Closed by torkelo** 2018-10-25 18:00 UTC
