### ISSUE TITLE
Awful time series graph with only one row

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#45641] opened 2022-02-19 18:29 UTC
**What happened**:
When you have just one row as a query result, as bar type it is shown in a horrible way when using time series graph.
It is used relative time to show all the year long as X axis (Relative time = 0s, Time shift = 2y/y)
![image](https://user-images.githubusercontent.com/51508670/154813377-0c57b70a-c100-48f4-a5da-aa7302cee95f.png)
![image](https://user-images.githubusercontent.com/51508670/154813353-7df168f0-de3e-432d-94ed-67bd5896167d.png)

**What you expected to happen**:
The bar just takes its time range, in this case just december as for example when you have more rows from the query
![image](https://user-images.githubusercontent.com/51508670/154813422-7ae94b6f-827e-443c-a3ad-3546e5afab76.png)

**How to reproduce it (as minimally and precisely as possible)**:
just make the query getting back only one row

**Anything else we need to know?**:
As well (as you can see from the pictures) it should be possible to set the time X axis interval, especially when you use a relative time range

**Environment**:
- Grafana version: 8.2.5 (but I tested it even with 8.4.1)
- Data source type & version: phpMyAdmin 5.1.1
- OS Grafana is installed on: debian 11 (tested even on windows10)
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2022-02-22 06:33
duplicate of https://github.com/grafana/grafana/issues/14130

**Closed** 2022-02-24 00:25 UTC
