### ISSUE TITLE
mobile view cut legend

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#14489] opened 2018-12-13 18:07 UTC
### What Grafana version are you using?
5.4.1
### What datasource are you using?
Influx
### What OS are you running grafana on?
Debian
### What did you do?
After I updated to 5.4.0 I noticed that my legends were cut off.
Today I updated to 5.4.2 and it is still cut off legends.
![img_0322](https://user-images.githubusercontent.com/21694965/49958167-478d5280-ff0a-11e8-911d-90a1c80bd5cc.jpg)

**Comment by daniellee** [comment] 2018-12-14 14:12
What phone and browser is this? I am not seeing this after testing play.grafana.org with an iPhone and in the browser dev tools in Chrome.

**Comment by daniellee** [comment] 2018-12-14 15:39
@flopp999 thanks, can't reproduce it via the Chrome dev tools with any of the emulated iPhone profiles but on the [alerting](https://play.grafana.org/d/000000074/alerting?orgId=1) dashboard on the play site, I can see the same bug on my iPhone 7.

**Comment by daniellee** [comment] 2018-12-14 15:41
It looks slightly better if you choose the `As Table` option for the legend but we will do a proper fix for this in the next version of Grafana.

**Closed** 2019-01-07 07:20 UTC
Labels: type: bug, type: ux
