### ISSUE TITLE
Query: Forward slashes in variables are not escaped

### ISSUE THREAD

**Issue by iBug** [grafana/grafana#80161] opened 2024-01-08 16:11 UTC
### What happened?

InfluxQL broke for a variable containing a forward slash. In my case, it's `$mountpoint` = `/`.

![image](https://github.com/grafana/grafana/assets/7273074/18fcee12-7458-4557-b914-f0eed209b585)

I had to change the condition to `path::tag = '${mountpoint:raw}'` for this query to work.

Setting `[log] level = debug` allows me to inspect this (log manually formatted for readability):

```text
Processing metrics query
logger=query_data
query="&{
  [...]
  query:
    SELECT mean(\"total\") AS \"total\",
          mean(\"used\") AS \"used\" FROM \"disk\"
    WHERE (
      \"host\"::tag =~ /^rosemary\\.ibugone\\.net$/
      AND \"path\"::tag =~ /^/$/
    ) AND $timeFilter
    GROUP BY time($__interval),
             \"host\"::tag,
             \"path\"::tag
    fill(linear)
  [...]
}"
```

### What did you expect to happen?

The variable `$mountpoint` should expand to `\/`, with the forward slash escaped, as is already done to dots (like the `$server` variable).

### Did this work before?

Never used an older version of Grafana

### How do we reproduce it?

1. Using InfluxDB backend, insert `disk,host=rosemary.ibugone.net,path=/ total=12345i,used=123i`
2. In dashboard variables, set `path` to `SHOW TAG VALUES FROM "disk" WITH KEY = "path" WHERE host = 'redacted.ibugone.com'
3. Select `path` = `/` and build the InfluxQL query in a panel.

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | timeseries @ 10.1.1 |
| Grafana | 10.2.3 (1e84fede543acc892d2a2515187e545eb047f237) // Open Source |

JSON too long, uploaded as file instead: [debug-Disk usage for _-2024-01-09 00_11_09.json.txt](https://github.com/grafana/grafana/files/13863485/debug-Disk.usage.for._-2024-01-09.00_11_09.json.txt)

### Environment (with versions)?

Grafana: Grafana v10.2.3 (1e84fede54)
OS: Windows 10
Browser: Microsoft Edge \| 120.0.2210.121 (Official build) (64-bit)

### Grafana platform?

None

### Datasource(s)?

InfluxDB v1.8 (using InfluxQL)

**Comment by devopstt** [comment] 2024-01-09 13:45
I think the issue is already known and a duplicate of https://github.com/grafana/grafana/issues/80003

@iBug: You can try to set the following option in your grafana.ini as workaround:
> influxdbBackendMigration = false

**Comment by gtk-grafana** [comment] 2024-01-09 19:18
Yup, this looks like a duplicate of https://github.com/grafana/grafana/issues/80003, and we're currently working on a fix. Thank you!

**Closed by gtk-grafana** 2024-01-09 19:18 UTC
