### ISSUE TITLE
Mobile view, panel menu bug

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#17768] opened 2019-06-25 19:26 UTC
**What happened**:
Panel moves to bottom when I try to open panel menu
**What you expected to happen**:
Panel menu drop down, to select eg. View,Edit etc
**How to reproduce it (as minimally and precisely as possible)**:
Open Grafana, try to open the menu. The panel will move to the bottom.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: Influx
- OS Grafana is installed on: Debian
- User OS & Browser: iOS Chrome
- Grafana plugins:
- Others:

**Comment by flopp999** [comment] 2019-06-25 19:31
It works on some panels but not all.
Sometimes it can be a Bar Gauge or Table, but it is also graph.
First panel seems to work all the time.

**Comment by torkelo** [comment] 2019-06-26 07:34
loosk like a bug with angular panels.

**Comment by vonox7** [comment] 2019-07-05 15:25
Reproducible in iOS Chrome and iOS Safari.
Reproducible only on Dashboards with panels that are on desktop ordered side by side, so multiple panels in one row and also multiple rows.

**Comment by torkelo** [comment] 2019-10-31 10:21
Think we can disable grid drag and drop in mobile view, should solve this and https://github.com/grafana/grafana/issues/20120

**Comment by vonox7** [comment] 2019-10-31 11:09
Thats a great idea, i guess nobody wants to drag panels on mobile :D

**Comment by flopp999** [comment] 2019-10-31 12:28
Great idea

**Comment by su-ex** [comment] 2019-12-06 09:26
Same issue here. Scrolling on a touch device is quite impossible without dragging around the panels. That's indeed a very nasty bug.
Disabling drag and drop would solve this, but a lock button to prevent accidental editing would be great though (and maybe a possibility defaulting to a locked state, because you're probably viewing a dashboard more often than editing it).

**Comment by torkelo** [comment] 2019-12-06 10:06
fixed by https://github.com/grafana/grafana/pull/20629

**Closed by torkelo** 2019-12-06 10:06 UTC
Labels: area/mobile-support, type/bug

**Comment by su-ex** [comment] 2019-12-06 13:28
Hmm, I'm not sure checking device width is a good idea to determine a "mobile device". I'd consider tablets and notebooks with touchscreens as mobile devices too and there the issue would remain?!?
At least with my notebook which has a touchscreen I have the same issue.
Seperating by touch and non touch interaction would be the far better solution imho.

**Comment by torkelo** [comment] 2019-12-06 14:26
yea, sorry, agree. Thought problem only affected mobiles
