### ISSUE TITLE
[NgAlerting] No alerts if graphite returns multiple serries and some of them are nulls

### ISSUE THREAD

**Issue by molsza** [grafana/grafana#40848] opened 2021-10-25 08:22 UTC
**What happened**:

If alerting is configured in a way that it returns multiple series, but only some of them have data, then alert is not generated, even though its condition is met for existing series. Grafana sees this as a no data situation. This is a different behaviour comparing to old alerting system. 

Compare those 2 screenshots:
![single](https://user-images.githubusercontent.com/41799777/138660025-08345b2f-f735-4ac9-864a-e2122ba8f715.jpg)

![multiple](https://user-images.githubusercontent.com/41799777/138660036-c1645a1b-c33d-4719-9202-d250015b56ff.jpg)
**What you expected to happen**:

Grafana should apply the condition to all series independently and report only the series which has met the condition. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create graphite datasource.
2. Create create an alert for this datasource
3. Write a query which returns multiple series 
4. Modify the query to return one empty series.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: Graphite (build-in)

**Comment by zuchka** [comment] 2022-02-02 02:46
Hi @molsza

A few troubleshooting questions:

1. There are a lot of notes in the changelog referencing alerting between 8.2.2 and 8.3.4. Of particular interest was this note regarding NoData & legacy alerts: https://github.com/grafana/grafana/blob/main/CHANGELOG.md#fix-no-data-behaviour-in-legacy-alerting
2. Does this behavior happen if you use a multi-dimensional condition instead of a classic condition?
3. Can you reproduce this behavior on 8.3.4?

**Comment by molsza** [comment] 2022-02-03 08:52
Hi @zuchka 
1. A few things has been fixed, but not this one.
2. If I change the type of condition, then it seems that passing this point - condition is showing the right data, then in alert message I get `["invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}"]()` <- since when is it required? At least I have a different metric name. Something is fishy here.
3.  Yes, problem still exists.

**Comment by yuri-tceretian** [comment] 2022-04-01 15:51
This seems to be a problem with data-source. We need to investigate it more deeply and decide on what side (expression or datasource) it should be fixed

**Comment by yuri-tceretian** [comment] 2022-05-20 17:15
@molsza did you try to use Reduce with option to map NaN to some constant and then apply Classic condition to it?

**Comment by molsza** [comment] 2022-05-20 18:42
if reduce then I will loose the names set by `groupByNodes` and I will get a full series name.

**Comment by yuri-tceretian** [comment] 2022-05-20 19:25
> if reduce then I will loose the names set by groupByNodes and I will get a full series name.

I mean use Reduce expression in Grafana 

![image](https://user-images.githubusercontent.com/25988953/169597992-7889a2f6-40c3-40f9-a621-a5beaa890bb6.png)

**Comment by grobinson-grafana** [comment] 2022-06-24 09:38
We are going to close this issue but please feel free to re-open it if the suggestion from @yuri-tceretian didn't work.

**Closed by grobinson-grafana** 2022-06-24 09:38 UTC
Labels: area/alerting, prio/medium, area/alerting/evaluation, needs investigation, area/datasource/backend, area/expressions
