### ISSUE TITLE
[Feature] Display percentage in hover tip next to actual value 

### ISSUE THREAD

**Issue by deric** [grafana/grafana#7713] opened 2017-03-02 23:35 UTC
When using stacking & percent display options, would it be possible to display in hover tip actual percent value? Probably optionally in format like:
```
...
1.2870 OK (85.8%)
```
![grafana-pct](https://cloud.githubusercontent.com/assets/138573/23531813/a0943ed8-ffa8-11e6-9008-cffd24cbe696.png)

**Comment by bergquist** [comment] 2017-03-03 08:47
Dupe of https://github.com/grafana/grafana/issues/6865

**Closed by bergquist** 2017-03-03 08:47 UTC
