### ISSUE TITLE
Cannot send alerts to slack

### ISSUE THREAD

**Issue by yasharne** [grafana/grafana#35969] opened 2021-06-20 19:35 UTC
**What happened**:
After upgrading to version `8.0.1`  we couldn't get slack notifications, here is the error log (upgrading to `8.0.2` and `8.0.3` didn't find the issue):

```
lvl=eror msg="Alert Panic" logger=alerting.engine error="interface conversion: interface {} is nil, not bool" stack="[engine.go:177 panic.go:965 iface.go:261 slack.go:390 slack.go:325 notifier.go:138 notifier.go:178 notifier.go:183 notifier.go:125 result_handler.go:102 engine.go:220]"
```
So I checked the code, and the exception is rising from the bellow section in `slack.go`:
```go
		var rslt map[string]interface{}
		// Slack responds to some requests with a JSON document, that might contain an error
		if err := json.Unmarshal(body, &rslt); err == nil {
			if !rslt["ok"].(bool) {
				errMsg := rslt["error"].(string)
				sn.log.Warn("Sending Slack API request failed", "url", sn.url.String(), "statusCode", resp.Status,
					"err", errMsg)
				return fmt.Errorf("failed to make Slack API request: %s", errMsg)
			}
		}
```
The `!rslt["ok"].(bool)` is causing exception as `rslt` has no `ok` field: 
```
map[queued:true success:true]
```
I will add a PR regarding this issue

**Comment by codesome** [comment] 2021-06-21 07:14
I have commented on the corresponding [PR](https://github.com/grafana/grafana/pull/35970) regarding this issue

**Comment by codesome** [comment] 2021-07-07 12:26
Closing this since this is not a bug in Grafana. See https://github.com/grafana/grafana/pull/35970#issuecomment-875518051

**Closed by codesome** 2021-07-07 12:26 UTC
Labels: area/alerting/notifications, area/unified-alerting
