### ISSUE TITLE
Upgrade failed to 8.2.x since #39476

### ISSUE THREAD

**Issue by gillg** [grafana/grafana#40601] opened 2021-10-19 08:13 UTC
**What happened**:
When I try to upgrade from Grafana 8.1.7 (I tested from lower versions too) to 8.2.x Grafana is crashing at startup during SQL migration phase. It's caused by #39476 introduced in 8.2.0.
I suspect it's because AlertingNG is already enabled on my side since version 8.0.x ?
I also see in the upgrade procedure, the script is reading some previous logs... How it can work in a docker context with ephemeral logs ?

Env : 
`GF_FEATURE_TOGGLES_ENABLE=ngalert`

Result at startup of 8.2.x :
```
t=2021-10-19T07:54:04+0000 lvl=info msg="Starting DB migrations" logger=migrator
t=2021-10-19T07:54:04+0000 lvl=info msg="Executing migration" logger=migrator id="update dashboard_uid and panel_id from existing annotations"
t=2021-10-19T07:54:04+0000 lvl=eror msg="Executing migration failed" logger=migrator id="update dashboard_uid and panel_id from existing annotations" error="failed to set dashboard_uid and panel_id for alert rule: Error 1406: Data too long for column 'dashboard_uid' at row 1"
t=2021-10-19T07:54:04+0000 lvl=eror msg="Exec failed" logger=migrator error="failed to set dashboard_uid and panel_id for alert rule: Error 1406: Data too long for column 'dashboard_uid' at row 1" sql="set dashboard_uid and panel_id migration"
Failed to start grafana. error: migration failed (id = update dashboard_uid and panel_id from existing annotations): failed to set dashboard_uid and panel_id for alert rule: Error 1406: Data too long for column 'dashboard_uid' at row 1
migration failed (id = update dashboard_uid and panel_id from existing annotations): failed to set dashboard_uid and panel_id for alert rule: Error 1406: Data too long for column 'dashboard_uid' at row 1
```

**What you expected to happen**:
The upgrade should work nevermind the source version and if ngalert is already installed.

**How to reproduce it (as minimally and precisely as possible)**:
I don't really know... Enable ngalert in Grafana 8.0.6 (as exemple) and try to upgrade to 8.2.1 with a docker container.

**Anything else we need to know?**:
Does somone can at least provide an SQL query to be able to apply the upgrade ?

**Environment**:
- Grafana version: 8.1.7 to 8.2.x
- OS Grafana is installed on: Docker image on centos host

**Comment by davidmparrott** [comment] 2021-11-22 19:31
I've been looking into the potential for improving this error message and I'm not certain there's a good path to do so. The error message you see logged comes from SQL, ultimately. The migrator hasn't got much special case handling or error checking/parsing and I don't like the idea of introducing some for this. The other alternative would be to make changes to the migrations or migrator packages (possibly both) that could accommodate more flexible error handling, which would be a larger undertaking. I'm going to close this since we've found the root cause and I don't think improving this error message is really feasible.

**Closed by davidmparrott** 2021-11-22 19:31 UTC
Labels: type/bug, needs investigation, area/alerting/unified
