### ISSUE TITLE
Playlist delete error

### ISSUE THREAD

**Issue by andrejflorjancic** [grafana/grafana#11851] opened 2018-05-07 09:56 UTC
Grafana version:
Grafana v5.0.4 (commit: 7dc36ae)

When I click on playlist "delete", got this message:
* Unable to delete playlist
* Playlist is empty

I put two dashboards on playlist. Than I deploy new configuration of grafana in which those two dashboards were missing. After that playlist can not be deleted any more.

**Comment by daniellee** [comment] 2018-05-07 12:25
This has already been fixed in 5.1. Duplicate of #11133

**Closed by daniellee** 2018-05-07 12:25 UTC
Labels: type: duplicate
