### ISSUE TITLE
[Feature request] Alert maintenance (downtime) feature

### ISSUE THREAD

**Issue by kapustor** [grafana/grafana#7329] opened 2017-01-23 08:38 UTC
Hi.
It would be great to have a downtime feature - pausing alert for N hours.
Now there is a pause button on every alert on Alerts page. It would be great to have a 'Plan downtime' button there, that will pop-up a window with downtime start time (current time by default) and downtime duration (ex 10h, 10m, etc), for example. The alert will be paused for this time.
The same feature is Nagios, Zabbix, etc.

Thank you, guys, for great software!

**Comment by torkelo** [comment] 2017-01-23 08:39
duplicate of https://github.com/grafana/grafana/issues/5856

**Closed by torkelo** 2017-01-23 08:39 UTC
