### ISSUE TITLE
Table panel: with no title set it's not possible to click the column name and filter icon.

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#49070] opened 2022-05-17 11:08 UTC
**What happened**:
Can't click sort/filter in table header

**How to reproduce it (as minimally and precisely as possible)**:
Create a table panel.
Set title to empty string.
Enable column filtering.

The hidden panel header overlays the controls for sorting and filtering when you mouse over the table.

**Environment**:
- Grafana version: 9.0.0-pre
- User OS & Browser: Linux, Chrome

**Comment by oscarkilhed** [comment] 2022-05-17 11:20
I see two potential fixes for this:


1. Make the sort and filter controls overlay the panel header.
![image](https://user-images.githubusercontent.com/468940/168799119-a63af53b-0fd1-4a01-af55-09a1eab50eae.png)
Downside: Long column names in the header makes it hard to edit and drag-drop the panel.

2. Keep the header even when there is no title. 
![image](https://user-images.githubusercontent.com/468940/168798079-6c71e438-9665-4a5a-b38b-380b9bcd94bf.png)
Downside: Not as pretty.

**Comment by dprokop** [comment] 2022-05-17 13:40
@torkelo I remember you've been exploring some alternative approaches to panel title when hidden, do you have any thoughts on this?

**Comment by torkelo** [comment] 2022-05-18 05:58
yes, https://github.com/grafana/grafana/issues/31080   would solve this, but waiting on UX help since nov 21, no ETA

**Comment by supilee** [comment] 2022-09-15 22:30
do we have a fix for this? just reproduced in 9.1.5

**Comment by mdvictor** [comment] 2023-03-09 12:36
A fix is already in beta under a feature flag, and a default release is in store for v9.5, as discussed [here](https://github.com/grafana/grafana/issues/56526).

**Closed by mdvictor** 2023-03-09 12:36 UTC
Labels: area/panel/table, prio/support-subscription, prio/customer-support
