### ISSUE TITLE
Cannot position Variable Template like panels

### ISSUE THREAD

**Issue by mitunmbj** [grafana/grafana#22596] opened 2020-03-05 12:37 UTC
Hello, While working through grafana I can position and resize the panels whereas I could not position the variable template and always remains in the upright corner and making difficult to sail across page for altering and viewing changes. can you please provide any suggestions on it.

**Comment by torkelo** [comment] 2020-03-05 13:52
duplicate of https://github.com/grafana/grafana/issues/16452

**Closed by torkelo** 2020-03-05 13:52 UTC
