### ISSUE TITLE
Bulk dashboard export and import

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30128] opened 2021-01-08 05:08 UTC
**What would you like to be added**:

Bulk dashboard export and import

**Why is this needed**:

When we have several dashboards that we want to share with people with separate Grafana installs, it can be a big pain to go through and export them all individually. Especially as we make updates and have to do this every time. Another use case is updating several dashboards and exporting them for version control.  There is certainly demand for this:

- https://gist.github.com/crisidev/bd52bdcc7f029be2f295
- https://medium.com/@raghavendrasamant/bulk-export-of-dashboards-in-grafana-84b8135a772f
- https://www.neteye-blog.com/2018/12/how-to-back-up-all-of-your-grafana-dashboards/
- https://stackoverflow.com/questions/42036663/how-to-completely-copy-grafana-dashboards-from-one-server-to-other-server

**Comment by torkelo** [comment] 2021-01-08 07:57
duplicate of https://github.com/grafana/grafana/issues/5552

**Closed by torkelo** 2021-01-08 07:57 UTC
