### ISSUE TITLE
Grafana 6.5.0-beta1, Explorer view, Log context UI glitches

### ISSUE THREAD

**Issue by pstibrany** [grafana/grafana#20624] opened 2019-11-25 10:12 UTC
There are several issues with context view:

- [x] It cannot be closed with simple press of Escape button. One has to find by-default-invisible (!!!) link to Hide context.

- [ ] Top and bottom part scroll separately. Entire context should be displayed in a single window, initially scrolled to line for which the context was displayed. It be be highlighted, but should not stay fixed on the screen while scrolling top/bottom separately.

- [x] Short messages break UI... some minimum sizes should be defined here it seems.

<img width="1477" alt="Screenshot 2019-11-25 at 10 58 16" src="https://user-images.githubusercontent.com/895919/69530608-9ba21300-0f72-11ea-9cdf-4eb7af023965.png">

- [x] I know that my log file has 90 messages in total, but I cannot load them all here. [perhaps "Load 10 more" doesn't cross time boundaries?]. 

<img width="1477" alt="Screenshot 2019-11-25 at 11 11 30" src="https://user-images.githubusercontent.com/895919/69531540-58e13a80-0f74-11ea-8375-846156f173bf.png">

- [ ] Why are timestamps hidden? Timestamps can be important. Setting from outer window should probably be respected when viewing context as well.

**Comment by torkelo** [comment] 2019-11-27 23:35
What browser and version are you using? Can you test chrome?

**Comment by pstibrany** [comment] 2019-11-28 07:36
Previous screenshots were using Safari 13.0.3 on macOS Catalina 10.15.1.

It looks pretty much the same with Chrome Version 78.0.3904.108 (Official Build) (64-bit) on the same macOS, against Grafana v6.5.0:

<img width="1477" alt="Screenshot 2019-11-28 at 08 34 35" src="https://user-images.githubusercontent.com/895919/69786093-01cca700-11ba-11ea-87f5-bea595d4a424.png">

**Comment by Estrax** [comment] 2020-05-04 02:49
@pstibrany re:
1. Log row context can be closed just by clicking outside of the log context component. Escape key is already addressed in #24205 - gonna add other fixes to this PR as well.
2. Good point, but isn't the user going to lose an info which log line they investigated when they request a lot of additional log lines and start scrolling? Unless we somehow lock the _background_ content from scrolling. 
3. Cannot reproduce it under linux; cc @ivanahuckova could you check if that's still the case under macOS?
4. Already addressed in #24135 
5. Can add timestamps there, but would love to hear from @jessover9000 if there should be any UI changes to make sure it looks well.

**Comment by ivanahuckova** [comment] 2020-05-04 11:14
>short messages break UI... some minimum sizes should be defined here it seems.

@Estrax seems like it was already fixed - couldn't reproduce either:
![image](https://user-images.githubusercontent.com/30407135/80960440-26801700-8e09-11ea-90e0-c806c3023436.png)

**Comment by ivanahuckova** [comment] 2020-05-04 11:19
However, found couple more UI glitches:
1. When Wrap-lines is not active, there are UI issue on context:
![image](https://user-images.githubusercontent.com/30407135/80960536-5af3d300-8e09-11ea-80fa-84ef3910e995.png)
![image](https://user-images.githubusercontent.com/30407135/80960655-92fb1600-8e09-11ea-97dd-4e3835fe2730.png)

This is also related to what was mentioned here (I haven't tested with no wrap-lines option) and it is not exclusive to Firefox - https://github.com/grafana/grafana/issues/22968#issuecomment-623358111

**Comment by Estrax** [comment] 2020-05-07 07:58
> * [x]  It cannot be closed with simple press of Escape button. One has to find by-default-invisible (!!!) link to Hide context.
> * [x]  Short messages break UI... some minimum sizes should be defined here it seems.

Fixed in #24205

> * [x]  I know that my log file has 90 messages in total, but I cannot load them all here. [perhaps "Load 10 more" doesn't cross time boundaries?].

Fixed in #24203

**Comment by Estrax** [comment] 2020-05-07 08:00
> * [x]  It cannot be closed with simple press of Escape button. One has to find by-default-invisible (!!!) link to Hide context.
> * [x]  Short messages break UI... some minimum sizes should be defined here it seems.

Fixed in #24205

> * [x]  I know that my log file has 90 messages in total, but I cannot load them all here. [perhaps "Load 10 more" doesn't cross time boundaries?].

Fixed in #24135

**Comment by Estrax** [comment] 2020-05-15 09:33
Closing this issue as part of those things are already fixed and the rest is mentioned in other issues: #23716 and #24727.

**Closed by Estrax** 2020-05-15 09:33 UTC
Labels: area/explore, area/panel/logs, area/ux, type/bug
