### ISSUE TITLE
Dashboards: Exporting for external use

### ISSUE THREAD

**Issue by a-pattani** [grafana/grafana#82260] opened 2024-02-09 14:12 UTC
### What happened?

While exporting boards for external use it generated data source UID variable e.g. "$DS_PROMETHEUS". It is only useful when you have only one other environment. In my case I have three different environments and using helm charts to provision boards. In other two environment it throws error "$DS_PROMETHEUS not found" because though the data source is same e.g. prometheus UID is different.

### What did you expect to happen?

It should some how auto detect the DS UID and should set it in background.

### Did this work before?

No

### How do we reproduce it?

1. In my case I have three different environments and using helm charts to provision boards. In other two environment it throws error "$DS_PROMETHEUS not found"
2.
3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.2
OS: Windows
Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus and Loki

**Comment by tonypowa** [comment] 2024-03-05 11:53
Hello @a-pattani 

Thank you for submitting the issue, tonypowa! To help us better understand and address your concern about the data source UID variable during export, could you please provide the following additional information:

Error logs or screenshots where '$DS_PROMETHEUS not found' is being shown

To reproduce the issue more effectively, it would also be valuable if you could provide a minimal example of a dashboard definition (in JSON) that is failing to import correctly due to the UID issue.

**Comment by a-pattani** [comment] 2024-03-05 13:32
Hi, This has been resolved.
i have created datasource template variable with this name and it solved the issue.

**Comment by tonypowa** [comment] 2024-03-05 13:38
thank you for sharing your solution @a-pattani  !
closing ...

**Closed by tonypowa** 2024-03-05 13:38 UTC
Labels: needs more info
