### ISSUE TITLE
Redirect loop with Grafana v5.4.1

### ISSUE THREAD

**Issue by kompa3** [grafana/grafana#14616] opened 2018-12-20 14:26 UTC
### What Grafana version are you using?
v5.4.1 (308c818)

### What OS are you running grafana on?

debian:jessie (inside docker container monitoringartist/grafana-xxl)

We use Grafana behind proxy so the following parameter is defined for grafana-xxl container: `GF_SERVER_ROOT_URL: https://ourdomain.com/grafana`

### What did you do?

Navigated to https://ourdomain.com/grafana/?orgId=13 in order to change the current organization.

### What was the expected result?

Grafana returns http 200.

### What happened instead?

After updating from v5.3 to v5.4.1, Grafana started returning http 302 randomly to the current url (ie. the same as the original request was made to) - sometimes so much that Chrome decides to give up because of a redirect loop.

Otherwise navigation between dashboards works well but organization switches randomly (and most often) do not work.

### A working case example with redirects but not ending in a redirect loop

Screenshots have been taken from Chrome developer mode.

![image](https://user-images.githubusercontent.com/9412499/50290499-88d6b280-0474-11e9-9c65-f17377904069.png)

First query in detail:
![image](https://user-images.githubusercontent.com/9412499/50289952-eff36780-0472-11e9-8764-b1464f200b26.png)

Last query in detail:
![image](https://user-images.githubusercontent.com/9412499/50289992-04376480-0473-11e9-9c50-a0d8a8925b7c.png)

All the queries are identical. I copied the queries from Chrome developer tools with Copy -> Copy as cURL (bash) and compared them -> no differences found.

### A redirect loop that happens quite often

![image](https://user-images.githubusercontent.com/9412499/50290153-7445ea80-0473-11e9-8297-d7e2d183e9e9.png)

All the queries are identical and result in http 302 to the exact url that was present in the original query.

**Comment by kompa3** [comment] 2018-12-20 14:40
Downgraded to v5.3.3 (commit: a8aa166) and organization switch started to work again. So there must have been some breaking change in v5.4.

**Comment by torkelo** [comment] 2018-12-20 14:44
Dupe of https://github.com/grafana/grafana/issues/14543, 

fixed in master & nightly builds, we will release a 5.4.3 patch release soon

**Closed by torkelo** 2018-12-20 14:44 UTC
