### ISSUE TITLE
Exceeded datasources query limit

### ISSUE THREAD

**Issue by oiooj** [grafana/grafana#14564] opened 2018-12-18 13:29 UTC
Please include this information:
### What Grafana version are you using? 
Grafana v5.4.2 (d812109)

### What datasource are you using?
influxDB
### What OS are you running grafana on?
Linux  #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
import datasources using `API` and `provisioning/datasources` 

### What was the expected result?

all success

### What happened instead?

some datasources import failed

![image](https://user-images.githubusercontent.com/2253095/50156806-ac7de980-030a-11e9-89ac-330c00db7aa4.png)

But this datasource already imported into grafana.db

```
select * from data_source where org_id = "4" and name = "collect.yz.switch.loda"

```

![image](https://user-images.githubusercontent.com/2253095/50156909-fa92ed00-030a-11e9-8312-049f4a5f9288.png)

and I try to add this datasource manually, of course it failed. The debug log:

```
t=2018-12-18T21:05:54+0800 lvl=eror msg="Failed to update datasource" logger=context userId=1 orgId=4 uname=admin error="UNIQUE constraint failed: data_source.org_id, data_source.name"

```

**Comment by oiooj** [comment] 2018-12-18 13:35
![image](https://user-images.githubusercontent.com/2253095/50157573-bf91b900-030c-11e9-906f-d8de51bb47a0.png)

And not displayed in datasources page.

**Comment by marefr** [comment] 2018-12-18 14:20
I'm not quite follow the steps you took and what data you had before. Would need some more detailed information and step-by-step descriptions to be able to verify/reproduce this. You're sure you're not on "wrong" organization in UI/API?

For example what do you mean by "import datasources using API and provisioning/datasources" - are you using both API and provisioning? Which API endpoint and how did that request look like. Did you have the datasource already created/provisioned etc etc etc.

**Comment by marefr** [comment] 2018-12-18 17:03
Duplicate of #13883

**Comment by marefr** [comment] 2018-12-18 17:04
Closing this. Please change your PR to target #13883 instead

**Closed by marefr** 2018-12-18 17:04 UTC
Labels: state: needs more detail
