### ISSUE TITLE
[Feature Request] - Add option to trigger alert after # of consecutive violation count

### ISSUE THREAD

**Issue by dudusakharovich** [grafana/grafana#10429] opened 2018-01-04 15:27 UTC
Hey,

I think it would be a great feature to add if while creating/configuring an alert you could choose to trigger the alert after # of consecutive violations.

For example:

If you create alert for CPU usage violation you could define it to change its state if the CPU usage is above 85 for 3 consecutive samples (While each sample interval is based on the alert check interval) during a period of you choosing (From 30m to now).

Regards,

**Comment by torkelo** [comment] 2018-01-08 11:33
dupe of https://github.com/grafana/grafana/issues/9323

**Closed by torkelo** 2018-01-08 11:33 UTC
