### ISSUE TITLE
A-Z reference query limitation

### ISSUE THREAD

**Issue by biro11** [grafana/grafana#20868] opened 2019-12-04 13:28 UTC
**What happened**:
In Grafana GUI is limitation for number of defined queries.
![image](https://user-images.githubusercontent.com/5763101/70146156-f1c53380-16a1-11ea-901d-d329e9bb405d.png)

**What you expected to happen**:
Queries should be referenced after "Z" also. For example as .. Y, Z, AB, AC, ... 
So it isn't possible to reference queries after "Z" in metaqueries plugin. Workaround is manually rewrite json model definition of dashboard and add refId field. But this is not user friendly.

**How to reproduce it (as minimally and precisely as possible)**:
Create new graph panel and add or duplicate query until reach "Z" .. next one will create without letter, and it can't be referenced in metaqueries.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.2
- Data source type & version: Elasticsearch 6.8.0
- OS Grafana is installed on: Debian
- User OS & Browser: Chrome
- Grafana plugins: metaqueries
- Others:

**Comment by papagian** [comment] 2019-12-04 13:51
duplicate of #4978

**Closed by papagian** 2019-12-04 13:51 UTC
Labels: type/duplicate
