### ISSUE TITLE
Cloudwatch - Define an alert using id query

### ISSUE THREAD

**Issue by maauso** [grafana/grafana#16825] opened 2019-04-30 12:20 UTC
**What happened**:
On If you are using id on you queries and then you want to use that query on Alert, you will receive ```message:"Condition: Eval: false, Query Returned No Series (reduced to null/no value)"``` 

if you remove the id, the query Alert works fine. 

**What you expected to happen**:
Receive the value on Alert query

**How to reproduce it (as minimally and precisely as possible)**:
Create a new cloudwatch query, like 
![image](https://user-images.githubusercontent.com/9114848/56960713-0791d980-6b52-11e9-9586-92986ee895ec.png)

We want to use query C to create an Alert, then 
![image](https://user-images.githubusercontent.com/9114848/56960991-ccdc7100-6b52-11e9-8b61-a9694716b85e.png)

If you remove the id filed the alert works 

**Anything else we need to know?**:

Also, we tried to modify the query with something like `query(error,5m,now)` where error is the id that we defined on the query. 

**Environment**:
- Grafana version: 6.1.6
- Data source type & version: CloudWatch
- OS Grafana is installed on: Docker
- User OS & Browser: 
- Grafana plugins: CloudWatch
- Others:

**Comment by marefr** [comment] 2019-04-30 12:44
Duplicate of #13749

**Closed by marefr** 2019-04-30 12:44 UTC
