### ISSUE TITLE
Raspberry pi: apt update mirror sync

### ISSUE THREAD

**Issue by Douglasdc3** [grafana/grafana#35600] opened 2021-06-13 19:23 UTC
**What happened**: When running `apt update` following output is given
```
Get:3 https://packages.grafana.com/oss/deb stable InRelease [12.1 kB]
Get:4 https://packages.grafana.com/oss/deb stable/main armhf Packages [26.2 kB]
Err:4 https://packages.grafana.com/oss/deb stable/main armhf Packages
  File has unexpected size (26024 != 26162). Mirror sync in progress? [IP: 199.232.194.217 443]
  Hashes of expected file:
   - Filesize:26162 [weak]
   - SHA512:f250eb04a626b82bc57f2380fb318d9c82cfe0eb933d9dddf6714a1ebcd79010757d3d10766ee3721ce864e915c19d4a651cedf5d5a6406fbe8774f07271feae
   - SHA256:6dc627e28e7ec78d79f1bb8cc99a5e3503cb1c0e2e353e872da6da408f16b1c1
   - SHA1:bf7ec09c3f7b9867d8b03754d248bb563c541ebd [weak]
   - MD5Sum:87615fc40342460ec2635dc3fb3795bf [weak]
  Release file created at: Thu, 10 Jun 2021 12:24:13 +0000
Fetched 12.1 kB in 1s (8753 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.grafana.com/oss/deb/dists/stable/main/binary-armhf/Packages.bz2  File has unexpected size (26024 != 26162). Mirror sync in progress? [IP: 199.232.194.217 443]
   Hashes of expected file:
    - Filesize:26162 [weak]
    - SHA512:f250eb04a626b82bc57f2380fb318d9c82cfe0eb933d9dddf6714a1ebcd79010757d3d10766ee3721ce864e915c19d4a651cedf5d5a6406fbe8774f07271feae
    - SHA256:6dc627e28e7ec78d79f1bb8cc99a5e3503cb1c0e2e353e872da6da408f16b1c1
    - SHA1:bf7ec09c3f7b9867d8b03754d248bb563c541ebd [weak]
    - MD5Sum:87615fc40342460ec2635dc3fb3795bf [weak]
   Release file created at: Thu, 10 Jun 2021 12:24:13 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**What you expected to happen**:  apt should update normally

**How to reproduce it (as minimally and precisely as possible)**: Following the grafana installation guide https://grafana.com/tutorials/install-grafana-on-raspberry-pi/

```
Install Grafana
Now that you’ve got the Raspberry Pi up and running, the next step is to install Grafana.

Add the APT key used to authenticate packages:

wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
Add the Grafana APT repository:

echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
Install Grafana:

sudo apt-get update
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: stable (oss)
- Data source type & version:
- OS Grafana is installed on: raspberry pi (raspbian) buster
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2021-06-14 07:36
Duplicate of #35273

**Comment by marefr** [comment] 2021-06-14 07:37
Please report in referenced issue if you still have problem with v8.0.1.

**Closed by marefr** 2021-06-14 07:37 UTC
