### ISSUE TITLE
Datalinks underline style is lost in Table

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#34653] opened 2021-05-25 13:10 UTC
![image](https://user-images.githubusercontent.com/327717/119502817-9fcb0e80-bd6a-11eb-8ad6-5b1747960dc6.png)

The `a` element has the style 

![image](https://user-images.githubusercontent.com/327717/119503084-e1f45000-bd6a-11eb-8cc0-70d3559424d1.png)

but it is not further propagated to the children div.

I guess it's a browser bug because it is shown as inherited `underline`

![image](https://user-images.githubusercontent.com/327717/119503432-431c2380-bd6b-11eb-8a39-262803c1cfaf.png)

**Environment**:
- Grafana version: https://play.grafana.org/d/tNlWezqGk/datalinks_autorefresh?orgId=1

**Comment by hugohaggmark** [comment] 2021-05-26 11:21
Duplicate of #33244

**Closed by hugohaggmark** 2021-05-26 11:21 UTC
Labels: area/dashboard/data-links, area/frontend, area/panel/table, area/ux
