### ISSUE TITLE
[Feature request]: Work around hitting max pending requests via data source proxy (due to slow data source queries), locks up dashboard search

### ISSUE THREAD

**Issue by benthorner** [grafana/grafana#5361] opened 2016-06-14 17:57 UTC
Grafana version: 3.0.4
Datasource: Graphite
OS: CentOS 7

What did you do?
We have several dashboards we use a lot. First we visit one dashboard, then another, depending on what we're looking for. To change dashboards, we click on the current one in the top-left corner.

What did you expect to happen?
We expect to see a list of dashboards.

What happened instead?
Unfortunately, the list isn't available until the current dashboard has finished loading, which can take a very long time (some of the graphs may be very data-heavy).

It would be great if you could parallelise or prioritise loading the dashboard list.

**Comment by torkelo** [comment] 2016-06-15 12:16
what version of Graphite are you using? Could you show a network trace and a javascript cpu profile for when the dashboard search is unresponsive? Want to know where the issue is, if it's due to long requests or due to locked up UI due to maybe old Graphite version returning millions of data rows

**Comment by benthorner** [comment] 2016-06-15 17:01
We're actually using Graphite API. It looks like the issue is due to long requests - this also affects switching organisations (you can't see the other organisations until the whole dashboard loads).

Interestingly, this issue goes away if you disable browser caching for the webpage. I've attached a JS profile if that helps - I'll look at getting a network trace if that'll still be useful.

[CPU-20160615T175511.txt](https://github.com/grafana/grafana/files/316699/CPU-20160615T175511.txt)

**Comment by torkelo** [comment] 2016-06-17 11:57
So this problem is caused by hitting max concurrent requests to single server.

**Comment by torkelo** [comment] 2016-06-17 11:57
This is a browser limit

**Comment by benthorner** [comment] 2016-06-17 22:29
Thanks for identifying the problem @torkelo 👍

**Comment by torkelo** [comment] 2016-06-18 05:36
I don't have any good solution though,  beside abort all requests button

**Comment by benthorner** [comment] 2016-06-21 12:05
Perhaps it could be an automatic action when you click on the dashboard selector (and other controls with this problem)? The logic being that if you're looking at a list of dashboards, then you probably don't care whether the current one finishes loading. Does sound like a bit of a hack, though.

**Comment by benthorner** [comment] 2016-06-21 12:21
I don't really understand why the problem goes away when caching is disabled. Perhaps the list gets pre-fetched when the page is first loaded, or something - maybe that's a clue as to another possible fix?

**Comment by torkelo** [comment] 2016-06-21 13:13
Caching has nothing to do with this, maybe with it disabled it is easier to replicate due to more requests

**Comment by benthorner** [comment] 2016-06-21 14:54
The issue actually goes away if you disable caching. I would expect it to get worse (due to more requests!), but it actually gets better. Perhaps it changes the order in which the requests are made...

**Comment by ahurtaud** [comment] 2019-04-25 15:26
Hello,

We are facing the same issue. 
As explained already, there are limitations on browser side to limit the number of parallel connections to the same server (in our case multiple panel to the datasource).
On firefox the default value is in about:config: 
`network.http.max-persistent-connections-per-server: 6`
Changing it to a higher value allow the parallelism to more than 6 queries at a time leading to a faster dashboard rendering if you are using a LB in your datasource...

I dont really like to modify browser settings at a company scope. I dont think it is possible, to change the grafana server to override such setting neither...

So the only solution would be to rethink how queries are sent to datasources. What do you think?

**Comment by torkelo** [comment] 2020-11-12 14:15
Fixed in Grafana 7.2

**Closed by torkelo** 2020-11-12 14:15 UTC
Labels: type/feature-request
