### ISSUE TITLE
SQL error while migrating 7.2.0 -> 8.3.0-beta: "copy alert_rule_tag v1 to v2"

### ISSUE THREAD

**Issue by Scotturbina** [grafana/grafana#42177] opened 2021-11-24 00:40 UTC
**What happened**:

I am migrating from grafana 7.2.0 to grafana 8.3.0 beta, during the database migration (we are using mysql)  I get these errors 
```
{"error":"Error 3098: The table does not comply with the requirements by an external plugin.","id":"copy alert_rule_tag v1 to v2","logger":"migrator","lvl":"eror","msg":"Executing migration failed","t":"2021-11-23T23:30:05.229137089Z"}
```
```
{"error":"Error 3098: The table does not comply with the requirements by an external plugin.","logger":"migrator","lvl":"eror","msg":"Exec failed","sql":"INSERT INTO `alert_rule_tag` (`alert_id`\n, `tag_id`) SELECT `alert_id`\n, `tag_id` FROM `alert_rule_tag_v1`","t":"2021-11-23T23:30:05.229246621Z"}
```
Curious thing is that if we change the image of our statefulset yml to 7.3 it gets migrated correctly, but if we try higher versions we get above error.

**What you expected to happen**:

I expect the migration flow get succeed and start using grafana.

**How to reproduce it (as minimally and precisely as possible)**:

Install grafana 7.2.1  with mysql as db, then try to install grafana 8.3.0 beta 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.0
- Data source type & version:
- OS Grafana is installed on: RHEL server 
- User OS & Browser: RHEL and google chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2021-11-24 10:02
Duplicate of #12971

**Comment by marefr** [comment] 2021-11-24 10:05
#22255 changed so that all tables includes primary keys. You might need to turn off the constraint not allowing primary keys to pass the migration introduced in #22255. Please check suggestions  https://github.com/grafana/grafana/issues/12971#issuecomment-773785434  for more information.

**Closed by marefr** 2021-11-24 10:05 UTC
Labels: type/duplicate, area/alerting, area/backend/db/migration
