### ISSUE TITLE
[Feat] Should be able to see full legend name when legend has a fixed witdh

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#12683] opened 2018-07-22 23:36 UTC
### What OS are you running grafana on? CentOS

It isn't always possible to control what text will show up in a legend and often using the "legend to the right" is preferable to "legend at the bottom" except that the legend is given preference in how horizontal display space is allocated. This means that the legend can take up to 90% of the space and 10% of the space is the graph unless a minimum size for the graph is set. Ideally I would like to specify the size as a % rather than a number of pixels but that's for another day.

When the minimum size for the graph is set, it is possible that the legend names will be cropped and thus the full name unreadable. Either better collapsing of the name (e.g. use part of the start and part of the end) or adding a horizontal scroller to see all of the name would be good.

As example of why start/end..
if my metric names are "hostnameA.long.domain.name longmetricnameA" and "hostnameB.long.domain.name longmetricnameB" then having "hostnameA...nameA" and "hostnameB...nameB" in the legend would be sufficient.

Some might see this as a bug (unreadable legend names) but it is behaving the way it has been written to.

**Comment by aocenas** [comment] 2019-06-20 14:38
Duplicate of https://github.com/grafana/grafana/issues/8291

**Comment by aocenas** [comment] 2019-06-20 14:39
The legend now is scrollable on both x/y axis and also it is possible to set fixed width of the legend.

**Closed by aocenas** 2019-06-20 14:39 UTC
Labels: area/dashboard, area/panel/graph, type/feature-request
