### ISSUE TITLE
[Feature Request] Notification Channel with multiple destinations

### ISSUE THREAD

**Issue by fredsmithjr** [grafana/grafana#9176] opened 2017-09-06 00:02 UTC
Please include this information:

What Grafana version are you using? Master
What datasource are you using? Graphite
What OS are you running grafana on? Ubuntu 16.04
In alerting list allow selecting a notification channel as a filter so you can add an extra notification channel to each.
Example: The team has a critical alert chat room BUT we also need to alert the 24/7 monitoring team. This requires 2 notification channels on the same set of alerts. It would be easier to pair the destinations under the same channel

**Comment by melor** [comment] 2017-09-06 05:51
Duplicate of https://github.com/grafana/grafana/issues/7832

**Closed** 2017-09-06 06:11 UTC
