### ISSUE TITLE
"Include All options" for Data source

### ISSUE THREAD

**Issue by filipre** [grafana/grafana#15536] opened 2019-02-19 14:18 UTC
Hi!

Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. ✅
- Checkout FAQ: https://community.grafana.com/c/howto/faq ✅
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50 ✅

Please include this information:
### What Grafana version are you using?
Grafana v5.2.3 (cf4c090)

### What datasource are you using?
Prometheus

### What OS are you running grafana on?
I don't know

### What did you do?
I tried to add a variable for all my data sources. This worked, however...

### What was the expected result?
I expected to have an option to also select "all" data sources I have instead of *only* one like you have for custom variables. I want to have a row in my dashboard for each data source. 
<img width="214" alt="screenshot 2019-02-19 at 15 06 01" src="https://user-images.githubusercontent.com/8502198/53021211-fb561580-3458-11e9-9c10-6517da94fdbc.png">

### What happened instead?
Instead, I can select one data source only and therefore, my defined row does not repeat. I can't find the option to select multiple data sources
<img width="558" alt="screenshot 2019-02-19 at 15 06 10" src="https://user-images.githubusercontent.com/8502198/53021250-13c63000-3459-11e9-997d-d87492052d9b.png">

I am wondering why you have the options for custom variables but not for data sources? Or am I missing something obvious?

Greetings!
René

**Comment by torkelo** [comment] 2019-02-19 14:30
duplicate of feature request, https://github.com/grafana/grafana/issues/7492

**Closed by torkelo** 2019-02-19 14:30 UTC
