### ISSUE TITLE
Null values break stacked graphs

### ISSUE THREAD

**Issue by richvdh** [grafana/grafana#33742] opened 2021-05-05 11:21 UTC
**What happened**:

Null values in a dataset break the stacking order in line/bar graphs, so that series get plotted over each other.

See the gif below:

![Peek 2021-05-05 12-11](https://user-images.githubusercontent.com/1389908/117132685-15ab0e00-ad9b-11eb-9ccd-8ff1d476da29.gif)

Initially, two dataseries are shown, correctly stacked. I then enable a third dataseries (which is null up to 30/April/08:00, and 0% thereafter). This changes the way one of the other dataseries is shown, so that it is not correctly stacked in that timeframe.

**What you expected to happen**:

A dataseries with null values should be ignored from the point of view of a stack.

**How to reproduce it (as minimally and precisely as possible)**:

 * Plot multiple dataseries in a stacked graph, where one or more dataseries have null values
 * Enable/disable the dataseries with null values. Observe that dataseries above it in the stacking order move position.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: Prometheus v2.25.0
- OS Grafana is installed on: Debian buster, via docker
- User OS & Browser: Ubuntu Focal. Firefox 85.0.1
- Grafana plugins: 
- Others:

**Comment by callahad** [comment] 2021-05-05 12:09
What happens if you set "null value: null as zero"?

![Screen Shot 2021-05-05 at 13 08 39](https://user-images.githubusercontent.com/24193/117138582-1e9fdd80-ada3-11eb-9a6e-e40778c78c3d.png)

**Comment by richvdh** [comment] 2021-05-05 12:40
yes, that seems to fix it.

**Comment by marefr** [comment] 2021-05-10 08:02
I'll close this since a solution to the problem have been posted

**Closed by marefr** 2021-05-10 08:02 UTC

**Comment by davidsuba** [comment] 2021-05-10 11:03
This is not solved! 

Using "null value: null as zero" corrects the graphs, but not everytime you want to consider null values as zero. In case that is mentioned in documentation in Note [here](https://grafana.com/docs/grafana/next/panels/visualizations/graph-panel/#stacking-and-null-value) I want to see gap in the graph, not zero values. It's misleading to see zeros, when in fact, no data were available.

Graphs should stack correctly even when "null value: null" is selected.

**Comment by marefr** [comment] 2021-05-10 11:25
@grafana/grafana-frontend-platform is this something the new graph panel would resolve perhaps?

**Comment by marefr** [comment] 2021-05-10 11:28
Duplicate of #15690
