### ISSUE TITLE
Navigation: Organization Switch Causes Error Notifications in topnav UI

### ISSUE THREAD

**Issue by chriswasser** [grafana/grafana#76723] opened 2023-10-17 19:32 UTC
### What happened?

After migrating our Grafana instance to 9.5.X (and with that to the by default enabled topnav navigation), the two following issues occurred when switching between organizations:

1. In Safari: Every organization switch through the UI causes an error notification showing "Load failed":
<img width="1512" alt="Safari-UI" src="https://github.com/grafana/grafana/assets/23461860/b33b1c9c-18f8-451c-b9ae-3c5e113ad0af">

However, all data is still shown correctly and a reload does not trigger the same kind of error notification. When disabling the topnav navigation through the associated feature toggle, organization switching is possible without errors (as before in Grafana version 9.4.X). This seems related to issue #72501 which initially reports on issues in Firefox but the discussion also mentions issues in Safari. For me, the error in the console reads:
<img width="1177" alt="Safari-Console" src="https://github.com/grafana/grafana/assets/23461860/e298306b-bcd1-4022-be86-3a6ba1bed84a">

Comparing the network tab of the topnav enabled case
<img width="1192" alt="Safari-Organization-Switch-topnav-enabled" src="https://github.com/grafana/grafana/assets/23461860/b76d3187-afdf-4cdd-9d9e-b3c3c929891d">
with the topnav disabled case
<img width="1192" alt="Safari-Organization-Switch-topnav-disabled" src="https://github.com/grafana/grafana/assets/23461860/3e053880-2fd3-4d35-8a3e-445ad75aacc6">
showed an additional redirect (as shown in the bar on the bottom) in combination with various 304 return codes in the prior erroneous case. Maybe these indicators can aid debugging.

2. In Chrome: **Some** organization switches through the UI causes an error notification showing "DashboardQueryRunner failed Failed to fetch":
<img width="1512" alt="Chrome-UI" src="https://github.com/grafana/grafana/assets/23461860/cf5adf72-7f61-4c3a-b5f5-4e0712afb18c">

This observation seems related to issue #76633 which describes the same error notification after migration to Grafana version 10.X which only supports topnav navigation. For me, no error is reported on the console:
<img width="1512" alt="Chrome-Console" src="https://github.com/grafana/grafana/assets/23461860/39369008-b477-499b-9636-a67c9def330c">

Inspecting the network tab, shows a failing API request to the wrong dashboardUID of the dashboard of the previously selected organization. However, the correct API call is automatically rerun with the correct dashboardUID of the dashboard  of the currently selected organization:
<img width="1512" alt="Chrome-Organization-Switch-topnav-enabled" src="https://github.com/grafana/grafana/assets/23461860/01a7a158-0d59-46e2-be37-9aab387d9417">

As this error does not occur every time when switching between organizations, this seems related to a race condition in the DashboardQueryRunner mentioned in the pull request #36254. Also in this case: When disabling the topnav navigation through the associated feature toggle, organization switching is possible without errors (as before in Grafana version 9.4.X).

### What did you expect to happen?

The same organization switching behavior in the old and in the topnav navigation without error notifications.

### Did this work before?

Works up until version 9.4.X without modifications in `/etc/grafana/grafana.ini`. For 9.5.X, the feature toggle `topnav = false` can be set to revert to the old navigation where everything works smoothly. By default, 9.5.X and 10.X have the topnav navigation enabled - the 10.X series does not even allow disabling it. In these cases, the errors occur.

### How do we reproduce it?

For Safari: Occurs on every organization switch through the UI
For Chrome: Only occurs on some organization switches through the UI

Again I am going to reference the related issues #72501 and #76633 as well as pull request #36254.

### Is the bug inside a dashboard panel?

This issue is not related to a specific dashboard panel.

### Environment (with versions)?

Grafana: OSS 9.5.X and 10.X from manually installed RPM package
OS: CentOS 7
Browser: Safari, Chrome
Deployed behind Apache reverse proxy
Authentication via AuthProxy
All organizations have a default Home Dashboard

### Grafana platform?

Other

**Comment by usmangt** [comment] 2023-10-30 09:58
Hi @chriswasser,

Thanks for opening this issue.

I will forward this to our Engineers so that they can have a look and might be able to tell more details about it.

**Comment by ashharrison90** [comment] 2023-11-06 11:02
hi @chriswasser 👋

I was able to reproduce this in grafana v10.0.0, but cannot reproduce in grafana v10.2.0. are you able to confirm the problem is fixed in v10.2.0?

**Closed** 2023-11-06 22:14 UTC
Labels: area/dashboard, area/navigation, triage/needs-confirmation
