### ISSUE TITLE
Variable Query will disappear when new selecting new datasource

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#20942] opened 2019-12-06 22:07 UTC
**What happened**:
Query in Query Variable  disappeared  after selecting new datasource

**What you expected to happen**:
All fields will remain as they were before I selected the new datasource.

**How to reproduce it (as minimally and precisely as possible)**:
I created datasource variable and used it in Query variable as datasource, additionally I filled query filed with the query. Then I renamed the datasource variable name (had a typo in a real case). When I opened the Query Variable and datasource was undefined which is expected. Then I selected the new renamed datasource variable.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Influxdb 1.7
- OS Grafana is installed on: RH 7.5
- User OS & Browser: Win10Pro , chrome 78.0.3904.108
- Grafana plugins: pie chart 
- Others:

**Comment by papagian** [comment] 2019-12-07 17:35
I don't fully understand what you tried to do. Could you please include some screenshots? thank you

**Comment by torkelo** [comment] 2019-12-09 13:34
>  Then I selected the new renamed datasource variable.

What happened then? Did the query show?

**Comment by gjemp** [comment] 2019-12-09 14:17
What happened:
Query in Query Variable disappeared after selecting new datasource

**Comment by torkelo** [comment] 2019-12-09 14:38
unable to replicate this, the query input / options does not disappear after changing a data source variable name, then going back to the variable that uses it, the datasource dropdown is empty, but once I select the renamed data source variable everything is fine. 
Variables
Can you record a video of what your seeing?

**Comment by Eraac** [comment] 2019-12-11 13:28
Yes already experiment this, step for reproduce

1. create datasource (name my-datasource)
2. create dashboard and graph using this new datasource
3. rename the datasource (to my-super-datasource)
4. go into the dashboard, graph doesn't work anymore (because "my-datasource" doesn't exist)
5. edit the graph (you can see the query with the "wrong" datasource selected)
6. set the good datasource
7. boom, query disappear


BTW, why Grafana reference datasource by their name instead of an internal ID? I suppose is for the json export, but can be update automatically ?

**Comment by papagian** [comment] 2019-12-16 11:17
@Eraac 
there is an open [issue](https://github.com/grafana/grafana/issues/1664) for updating dashboards when renaming a datasource.
Also, setting the query after changing datasource can be tricky given the query editor can vary from datasource to datasource.
Finally I think that this will be no more an issue after renaming datasource issue will have been addressed.

**Comment by torkelo** [comment] 2019-12-16 12:34
Fixed by https://github.com/grafana/grafana/pull/21079

**Closed by torkelo** 2019-12-16 12:34 UTC
Labels: needs more detail
