### ISSUE TITLE
Error processing alert, elasticsearch 7.0.0

### ISSUE THREAD

**Issue by holiiveira** [grafana/grafana#16602] opened 2019-04-15 17:55 UTC
**What happened**:
After upgrading Elasticsearch from 6.7.0 to 7.0.0, the alerts configured in Grafana are in error.

**What you expected to happen**:
That the processing of the alert occurred without error.

**How to reproduce it (as minimally and precisely as possible)**:
Using elasticsearch 7.0.0 as the data source and setting up an alert, look at the Grafana log to see the error.

**Anything else we need to know?**:
The problem with Elasticsearch 6.7.0 does not occur.

Log error:

`error:"tsdb.HandleRequest() error json: cannot unmarshal object into Go struct field SearchResponseHits.Total of type int64"`

I have this environment ready for testing if necessary.

**Environment**:
- Grafana version: Grafana v6.1.3 (commit: 9504db8)
- Data source type & version: Elasticsearch 7.0.0
- OS Grafana is installed on: HPE SimpliVity Hyperconvergence
- User OS & Browser: Ubuntu Server 18 LTS & Google Chrome 73.0.3683.103
- Grafana plugins: None

**Comment by holiiveira** [comment] 2019-04-15 18:46
The problem is that the return of the Search API has changed.

In versions prior to 7.0.0:
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/_the_search_api.html

The `Total` attribute was:
```
...
hits" : {
    "total" : 1000,
...
```

Now it is:
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-search-API.html

```
...
"hits" : {
    "total" : {
        "value": 1000,
        "relation": "eq"
    },
...
```

I believe that the file you take care of would be the [models.go (L45)](https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/client/models.go#L45)

That's what I was able to track.

**Comment by marefr** [comment] 2019-04-15 18:46
Duplicate of #15622

**Comment by marefr** [comment] 2019-04-15 18:47
There's an open PR #16597 which you can try and provide feedback in.

**Closed by marefr** 2019-04-15 18:47 UTC

**Comment by holiiveira** [comment] 2019-04-15 19:04
The problem is that the return of the Search API has changed.

In versions prior to 7.0.0:
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/_the_search_api.html

The `Total` attribute was:
```
...
hits" : {
    "total" : 1000,
...
```

Now it is:
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-search-API.html

```
...
"hits" : {
    "total" : {
        "value": 1000,
        "relation": "eq"
    },
...
```

I believe that the file you take care of would be the [models.go (L45)](https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/client/models.go#L45)

That's what I was able to track.

**Comment by marefr** [comment] 2019-04-16 08:16
@holiiveira please provide this feedback in PR #16597. Thanks
