### ISSUE TITLE
Org identifier in URL

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#3571] opened 2015-12-19 16:11 UTC
It would be nice if there could be an org identifier in the URL for the dashboards or it would look through all ors when trying to serve a dashboard.  The reason we're running in to this now is if you have a dashboard that's not in the default org and even though we allow unauthenticated viewing, if you view this dashboard you get an error saying dashboard not found.

**Comment by torkelo** [comment] 2015-12-20 13:29
duplicate of https://github.com/grafana/grafana/issues/1613

**Closed by torkelo** 2015-12-20 13:29 UTC
