### ISSUE TITLE
Unable to create a rule based on Azure Monitor Data Source - plugin unavaible

### ISSUE THREAD

**Issue by gregoryb** [grafana/grafana#44077] opened 2022-01-14 22:33 UTC
**What happened**:

Unable to create an alert rule based on Azure Monitor.
Graph with Azure Monitor is working great. eval call from Alert rules seems is failing.

`Failed to evaluate queries and expressions: failed to execute conditions: plugin unavailable`

**What you expected to happen**:

Creation succeed :)

**How to reproduce it (as minimally and precisely as possible)**:

Try to create an alert using Azure Monitor Data Source.

**Anything else we need to know?**:

<img width="972" alt="alert_view_error" src="https://user-images.githubusercontent.com/609183/149593695-0e0b79c4-b45d-4ae2-8a17-bf33780d24fe.png">
<img width="611" alt="alert_create_notif" src="https://user-images.githubusercontent.com/609183/149593696-fc6ca79f-b542-4b28-9ce6-e792df23dcbd.png">

**Environment**:
- Grafana version: 8.3.3 & 8.4
- Data source type & version: Azure Monitor 0.3.1 & 0.3.1
- OS Grafana is installed on: OSX & Ubuntu 18.04
- User OS & Browser: Chrome
- Grafana plugins: Azure Monitor, Azure Data Source
- Others:

**Comment by hugohaggmark** [comment] 2022-01-17 06:06
Thanks for reporting this @gregoryb, we'll investigate this further. Not sure if this is @grafana/alerting-squad or @grafana/cloud-datasources so I've assigned both.

**Comment by andresmgot** [comment] 2022-01-17 08:37
Seems related to https://github.com/grafana/grafana/issues/43401. @gregoryb can you uninstall the external Azure Monitor datasource? That should fallback to the core plugin (which version is 0.3.0).

**Comment by gregoryb** [comment] 2022-01-17 09:15
@andresmgot With 0.3.0 on 8.4, i got this error

<img width="1461" alt="grafana_switch" src="https://user-images.githubusercontent.com/609183/149741180-cdee905b-0fa2-4028-8059-11f03e7f81a7.png">

That's why i tried to update to 0.3.1

**Comment by andresmgot** [comment] 2022-01-17 12:17
Thanks @gregoryb, that is the issue we should investigate then. Unfortunately I am not able to reproduce it with Grafana 8.4:

![Screenshot from 2022-01-17 13-02-49](https://user-images.githubusercontent.com/4025665/149766288-fc0c03d5-9f42-452a-9044-da552846336e.png)

If the same query works in a normal dashboard, the issue seems to be related to the alerting system. Can you send detailed instructions on how to reproduce it? The full trace of the error may help too.

Since this does not seem an issue with the Azure monitor data source I am removing it from the Cloud Data Sources board but feel free to add it again if you suspect there is an issue with it.

**Comment by gregoryb** [comment] 2022-01-17 12:48
Here is the full trace.
The issue occurs only on the timeseries tab only. Table and Stats displays values. AND as you said, it occurs only on Rule view.
[grafana_stack.txt](https://github.com/grafana/grafana/files/7881875/grafana_stack.txt)
.
I don't know how to be more precise to reproduce the issue. 
It's a fresh install 8.4.0-pre (unknown dev). Installed from brew. I just connected my Microsoft Account and tried to create a rule.

**Comment by santihernandezc** [comment] 2022-01-17 15:11
Hi @gregoryb, @andresmgot, there's a [related issue](https://github.com/grafana/grafana/issues/42755) that was opened a while ago about this exact error. I made the following PR to solve this: https://github.com/grafana/grafana/pull/42989

**Comment by peterholmberg** [comment] 2022-01-27 08:54
@santihernandezc @andresmgot can we close this if it's fixed by Santiagos PR?

**Comment by andresmgot** [comment] 2022-01-27 09:38
yes, the original issue has been fixed (correct me @santihernandezc otherwise)

**Closed by andresmgot** 2022-01-27 09:38 UTC
Labels: area/alerting, needs investigation, datasource/Azure, area/alerting/unified
