### ISSUE TITLE
BarChart: Value mappings are not always applied

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#51966] opened 2022-07-08 12:12 UTC
Bar chart only applies value mappings on first refresh/query result, when I hit the refresh button again the value mappings are not used. 

First render/query 
![Screenshot from 2022-07-08 14-12-03](https://user-images.githubusercontent.com/10999/177989766-b7ff54c9-2fdf-47ee-8fd8-9971f50830a2.png)

Afrer hitting refresh button
![Screenshot from 2022-07-08 14-12-14](https://user-images.githubusercontent.com/10999/177989793-a1cd3828-89f8-468f-acdc-b1f3b61a6c63.png)

Example dashboard below

<details>
   <summary>JSON Block</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 370,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "fillOpacity": 47,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineWidth": 1,
            "scaleDistribution": {
              "type": "linear"
            }
          },
          "mappings": [
            {
              "options": {
                "AAA": {
                  "index": 0,
                  "text": "MAP-A"
                },
                "BBB": {
                  "index": 1,
                  "text": "MAP-B"
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 11,
        "w": 13,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "options": {
        "barRadius": 0,
        "barWidth": 0.97,
        "groupWidth": 0.7,
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "orientation": "auto",
        "showValue": "auto",
        "stacking": "none",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "xTickLabelRotation": 0,
        "xTickLabelSpacing": 200
      },
      "targets": [
        {
          "csvContent": "Owner, value \nAAA,10\nBBB,20",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "barchart"
    }
  ],
  "refresh": "",
  "schemaVersion": 36,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Value mapping",
  "uid": "qtaE8AaGz",
  "version": 7,
  "weekStart": ""
}
```
</details>

**Comment by codeincarnate** [comment] 2022-07-11 14:06
I suspect that the data preparation pipeline is either being marked is being complete and not being rerun or something similar. We've had some similar things popup with state timeline.

**Comment by leeoniya** [comment] 2022-07-11 23:02
this is a duplicate of https://github.com/grafana/grafana/issues/47697, was fixed by https://github.com/grafana/grafana/pull/51945

**Closed by leeoniya** 2022-07-11 23:02 UTC
Labels: type/bug, area/panel/barchart
