### ISSUE TITLE
MSSQL: issue with host names containing \

### ISSUE THREAD

**Issue by xslugx** [grafana/grafana#19483] opened 2019-09-28 18:49 UTC
**What happened**: 
Unable to get instances from Sql Server Browser on host hostname: read udp -ip range: i/o timeout

**What you expected to happen**:connection ok

**How to reproduce it (as minimally and precisely as possible)**:try different host name with success, then change back to original host name

**Anything else we need to know?**:host name contains \ , for example if host name is Ryan\stuff,else the error comes back with just Ryan and not the second part of the host name

**Environment**:
- Grafana version: 6.2.5
- Data source type & version: mssql
- OS Grafana is installed on: windows 10
- User OS & Browser: windows 10, google chrome
- Grafana plugins: default
- Others:

**Comment by hugohaggmark** [comment] 2019-09-30 06:48
Hi @xslugx, which SQL version are you using?

**Comment by xslugx** [comment] 2019-10-01 13:11
MSSQL version: 13.0.5026.0 SP2 , sorry for the delay on this.

**Comment by xslugx** [comment] 2019-10-01 13:45
I would like to state that I can connect to the same server I am trying to connect with Grafana using Heidi SQL and Microsoft SQL Server Management Studio

**Comment by marefr** [comment] 2019-10-01 20:17
Possibly duplicate of #17665

**Comment by xslugx** [comment] 2019-10-01 20:29
After looking at #17665 it appears to be a bit different, as this pertains to the actual connection string and not a username and password error. we used named servers for MSSQL instead of IP's, while the name contains a \ symbol it removes whatever is after \, So it may just be something with the go language that stops it from recognizing that in the string. I will do some further investigation into why that may be caused in the string.

**Comment by marefr** [comment] 2019-10-01 21:12
Can you try and replace `\` with `\\`?

**Comment by xslugx** [comment] 2019-10-01 21:31
> Can you try and replace `\` with `\\`?
That did not work as, so now I went with servername'\\ 'servername and the error stats 
"Unable to get instances from sql Server Browser on host servername': dial udp lookup servername': no such host" so again removing everything after \

**Comment by marefr** [comment] 2019-10-01 22:05
Looking at the code from the mssql go-library we're using:
Error is returned fromr `getInstances`:
https://github.com/grafana/grafana/blob/ac11352e3e9daec0c173b6db8bfa42690cc7fb1b/vendor/github.com/denisenkom/go-mssqldb/tds.go#L1187-L1190

Looking at `getInstances` it tries to connect to the first part of your host (what's before `\`) over udp port 1434 and that seems to fail:
https://github.com/grafana/grafana/blob/ac11352e3e9daec0c173b6db8bfa42690cc7fb1b/vendor/github.com/denisenkom/go-mssqldb/tds.go#L57

Are you using mssql express maybe?

**Comment by xslugx** [comment] 2019-10-01 22:42
I do not believe it is mssql express due to the properties of the server. This is in a Corporate setting for a major company. I was testing Grafana for a use case for my department, and I was met with this particular issue immediately. I will look more tomorrow at the server settings but I am certain it is not express.

**Comment by xslugx** [comment] 2019-10-02 13:11
I am at work and was able to check the SQL version, we are using Microsoft SQL Server Enterprise

**Comment by reuvygroovy** [comment] 2020-05-31 05:34
I am presently on 6.7.2 and this works fine with a named instance that contains a slash. I opened a new bug #25067 where this problems appears in 7.0

**Closed** 2021-11-25 08:30 UTC
Labels: datasource/MSSQL

**Comment by hameedshk** [comment] 2022-08-30 17:47
this problem exists in v9.0.5 and it took almost a month to figure out. I replicated by creating two instance of sql server , one named istance and another default. Connection string with default works but for named instance it fails as it contains '\' character. Adding another \ character doesnt work. Really stuck on this for very long , I dont have any clue on how to proceed.

**Comment by reuvygroovy** [comment] 2022-08-31 04:49
This works for us: SQLServer\Instance:Port

**Comment by hameedshk** [comment] 2022-08-31 05:56
Thanks for your valuable comment , now I get another error "login error:ms sql login failed for domain\hostname ". Looks like when I select windows authentication mode, hostname is appended as login instead of username. Browser and login is with the same user.

**Comment by hameedshk** [comment] 2022-08-31 07:25
Finally I tried to run garafana.exe via explorer rather than as service and it works.

**Comment by xslugx** [comment] 2023-01-17 15:58
> Finally I tried to run garafana.exe via explorer rather than as service and it works.

Is it possible you could test a connection using / instead of \? 
I was looking back at one of the original responses then I was looking through the code for that library and it seems the format for the link is a / not a \. I no longer have it installed or I would do it myself.

**Comment by xslugx** [comment] 2023-01-17 16:05
> > Finally I tried to run garafana.exe via explorer rather than as service and it works.
> 
> Is it possible you could test a connection using / instead of ? I was looking back at one of the original responses then I was looking through the code for that library and it seems the format for the link is a / not a . I no longer have it installed or I would do it myself.

I will be able to test this out this week when I am at home.
