### ISSUE TITLE
Shorten  URL doesn't take orgId into account

### ISSUE THREAD

**Issue by rlueckl** [grafana/grafana#33813] opened 2021-05-07 13:42 UTC
**What happened**: Using _Shorten URL_ doesn't include the `orgId`. If somebody tries to open the link whilst in a different org., they get a 404.

**What you expected to happen**: The shortened URL also contains the `orgId`, so that people opening the link are automatically switched to the correct org.

**How to reproduce it (as minimally and precisely as possible)**:
 * Create 2 organisations in your Grafana (for example: "Main Org." with orgId=1 and "Test Org." with orgId=2)
 * Create a dashboard in Main Org. (URL in address bar contains `&orgId=1`)
 * Click _Share_ button and use _Shorten URL_, click _Copy_ to copy the shortened URL to your clipboard
 * Switch to Test Org. (URL in address bar now has `&orgId=2`)
 * Try to open the shortened URL
 * Result: 404 "Page not found"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.3

**Comment by farodin91** [comment] 2021-05-14 16:15
I would like to work on it. 

I checked the code. It looks like to org is already saved and is already used to query the database(only the current user orgId). My idea would be to include the orgId in the goto link. Otherwise, it would be also possible to add index to just query using the uid. 

The short url would be second type. 
What is the preferred solution?

**Comment by marefr** [comment] 2021-05-18 10:06
@farodin91 maybe just include the orgId in redirect if the orgId stored for short url doesn't match the current orgId of the request?

**Comment by farodin91** [comment] 2021-05-19 05:59
If I'm correct their is no difference between ReqContext.OrgId and SignedInUser.OrgId, or?  SignedInUser.OrgId will be automatically updated if user switches the org, correct?.

**Comment by marefr** [comment] 2021-05-19 07:39
> If I'm correct their is no difference between ReqContext.OrgId and SignedInUser.OrgId

Correct. After consideration seems like the problem is that shorturl is filtered by active orgId https://github.com/grafana/grafana/blob/6e2a9f2f3234078ae49fce815b05efa01cf737a0/pkg/services/shorturls/short_url_service.go#L30.

One solution might be to remove filter by orgId above. But the following redirect should then always have `orgId` included in URL: 
https://github.com/grafana/grafana/blob/6e2a9f2f3234078ae49fce815b05efa01cf737a0/pkg/api/short_url.go#L67

**Comment by marefr** [comment] 2021-05-26 10:15
I'm a bit unsure what the proper solution to this should be given that a short url has a unique index for org id and short url uid indicating that two different orgs should in theory be able to have the same short url uid. I see two possible solutions:

1. Remove filtering short url by current user active org id
2. Making sure that the generated short url includes the current org id, i.e. `http://<host>/goto/<uid>?orgId=<org id>` instead of how it currently works `http://<host>/goto/<uid>` 

I think I would prefer solution number 2 after consideration. 

@ivanahuckova pinging you here since you was involved getting the short url feature merged. What's your thoughts on this/your preferred solution?

**Comment by ivanahuckova** [comment] 2021-05-26 10:53
I like proposed solution 2 more as well. The short url will be a little bit longer, but it is still pretty short compared to regular url.

**Comment by marefr** [comment] 2021-05-26 14:05
Thanks. Great so solution 2 it is. 

I believe the only thing that needs to change is to include the orgId query string parameter here https://github.com/grafana/grafana/blob/9016d20c4c63e77faddf3e72cf2c9d1f989c496b/pkg/api/short_url.go#L32

That would ensure that orgId query string parameter is included when generating a new short url from the UI.

**Closed** 2021-06-01 12:19 UTC
Labels: area/dashboard, area/explore, priority/important-soon, type/bug
