### ISSUE TITLE
Colors in timeseries panel use wrong palette

### ISSUE THREAD

**Issue by xrstf** [grafana/grafana#39614] opened 2021-09-24 12:09 UTC
**What happened**:
I have a timeseries panel with 3 graphs using the right axis. They should just continue to work as normal, nothing fancy.

**What you expected to happen**:
The color for a certain series should stay constant. But when I refresh, the colors are wrong until I click on one of the series. In the video below, note how AvE and Stede are changing colors all the time.

https://user-images.githubusercontent.com/127499/134671490-88940cfb-412b-40de-82a6-6546563ff6a0.mp4

![2021-09-24 14_09_37-](https://user-images.githubusercontent.com/127499/134671898-8fc53ab2-1296-4baf-8962-f80b213a345e.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create a timeseries panel and set a series override with "axis placement: right; standard unit: none".

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.4 (Docker)
- Data source type & version: Postgres 11
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows 10, Firefox 91
- Grafana plugins: none
- Others: I used Grafana 7 for many years, maybe I am misusing v8 and don't know what I'm doing :)

**Comment by zoltanbedi** [comment] 2021-09-27 10:59
Hi @xrstf,
Can you please try to be more specific with the repro steps because I was not able to in https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&editPanel=540

**Comment by zoltanbedi** [comment] 2021-10-21 08:36
I'm still not able to reproduce this in Grafana v8.3.0-pre (1df969b5a0). I'll close this issue now but I'll reopen if you provide me steps to reproduce or a panel.json where it happens.

**Comment by zoltanbedi** [comment] 2021-10-21 12:07
Thank you @alaendle, I'll take a look.

**Comment by hit0ri** [comment] 2021-11-09 12:58
I don't know if it's a related issue, but for me, colours and series placement are changing almost every refresh.
I'm on grafana v8.2.3

https://user-images.githubusercontent.com/4470499/140928163-3efa7dce-0275-4194-8d96-ee9f49161804.mov

**Comment by torkelo** [comment] 2021-11-15 18:44
Looks like the order of the time series are returned in random order, maybe a cloudwatch issue

**Comment by mckn** [comment] 2021-11-18 15:39
I think this is related to the following https://github.com/grafana/grafana-plugin-sdk-go/issues/366 and it is closed by the following https://github.com/grafana/grafana-plugin-sdk-go/pull/425.

So I guess we need to upgrade the `Cloudwatch Datasource` to use the new SDK.

**Comment by marefr** [comment] 2021-11-18 15:54
#41868 will make Grafana use the SDK changes. I'm not sure that will resolve all of the different problems discussed in this issue though why I suggest keeping this issue for a while and let users provide feedback if their problems are resolved.

**Comment by alaendle** [comment] 2021-11-19 07:23
Sorry - at least my problem is reproducible with Grafana v8.3.0-42202pre (a6e60c62f4).

**Comment by mckn** [comment] 2021-11-19 09:21
> Sorry - at least my problem is reproducible with Grafana v8.3.0-42202pre ([a6e60c6](https://github.com/grafana/grafana/commit/a6e60c62f458e7b5af3328c8863a5c29fe6d47d5)).

@alaendle what datasource are you using?

**Comment by alaendle** [comment] 2021-11-19 10:19
@mckn In my case I have a influxDB and I'm using the Flux QL (for more details take a look at my dashboard https://github.com/grafana/grafana/issues/39614#issuecomment-948544685 and my debugging experience https://github.com/grafana/grafana/issues/39614#issuecomment-951094479)

**Comment by marefr** [comment] 2021-11-19 14:01
@alaendle I cannot reproduce. Guess you have something special with your data, but not sure. Would suggest you do panel menu -> inspect -> query -> refresh and copy to clipboard and paste it here so that we can get a better understand.

![Selection_1103](https://user-images.githubusercontent.com/1668778/142634727-22c5f5f0-3d4a-4891-8432-f0ab459a547e.png)

https://user-images.githubusercontent.com/1668778/142634485-eba0a621-7027-4cb0-ae29-5026b271b8f2.mp4

**Comment by alaendle** [comment] 2021-11-19 17:27
@marefr Many thanks for your effort to track down this issue! I also believe that this problem might be data-sensitive. And don't hesitate to ask for more information if needed.

Here is the requested data of a panel that reproduces the problem.

![grafik](https://user-images.githubusercontent.com/969523/142663698-f09c2cce-775a-489a-9744-4625a408e1d7.png)

**Query inspector result:**
[inspector.json.txt](https://github.com/grafana/grafana/files/7571899/inspector.json.txt)

**Comment by marefr** [comment] 2021-11-24 11:00
I was able to sort of reproduce I think:
https://user-images.githubusercontent.com/1668778/143224353-3efc6cd3-a8f2-49b0-b9c8-9387d3c1a6cc.mp4

Using https://github.com/yesoreyeram/grafana-infinity-datasource/releases/tag/v0.8.0-dev.7 data source and the following dashboard: https://gist.github.com/marefr/81176cdc564baa55f4035ed9c7919671

Sometimes when I load the dashboard it has series and legends with correct colors:
![image](https://user-images.githubusercontent.com/1668778/143225463-85c50f14-1e48-4afd-b915-1a14ea7187e6.png)

And doing a refresh is what can be seen in video above.

Sometime when loading the dashboard (refresh browser tab) the colors are of:
![image](https://user-images.githubusercontent.com/1668778/143226133-e6b10a36-51c5-40b2-bdff-b071001a5cb7.png)

**Comment by andresmgot** [comment] 2021-11-24 11:07
_removed the CloudWatch label, let us know if you still think this is a CloudWatch issue_

**Comment by TimShilov** [comment] 2022-03-23 09:36
I also experience a similar (or the same) issue. It happens very frequently but randomly and I cannot reliably reproduce it.
It takes one click on one of the legend items and it gets fine.
I'm using Grafana 8.4.4 and Prometheus as a data source. Nothing extra ordinary.

It gives me a little heart attack every single time as it swaps colors of **success** and **error** cases which make it seem like a disaster! 😅

https://user-images.githubusercontent.com/20239045/159668323-f0af2732-6e64-4828-851e-28c47f23fe18.mov

**Comment by tomtastic** [comment] 2022-09-09 10:15
Still a problem in Grafana `9.1.3` 
![image](https://user-images.githubusercontent.com/302127/189327407-0b5130a8-e962-40d6-8d1e-3316e8058a87.png)
Selecting any of the series in the legend at the bottom of the graph fixes the colour.
If `Refresh Dashboard` is clicked, the colours return to being incorrect.

**Comment by Cougar** [comment] 2022-11-15 23:22
Still the same problem in 9.2.4. I have InfluxDB (Flux) DS. Graph after dashboard (graph) refresh or time range chang:

![2022-11-16_002024_486931593](https://user-images.githubusercontent.com/60040/202045464-c65eda0e-fdfc-4ee9-9d7d-70eb52feddbb.png)

Graph after web page reload, after "graph reload" or when selecting or deselecting any specific line:

![2022-11-16_002206_406645083](https://user-images.githubusercontent.com/60040/202045477-91dd4d9c-0310-4db8-9336-f194c5a688ab.png)

**Comment by nmarrs** [comment] 2023-03-03 17:58
Hi, we believe that [this PR](https://github.com/grafana/grafana/pull/63823) has fixed this issue. We will close this, please let us know if the issue has not been resolved and we will re-open this issue. Thanks! :)

**Closed by nmarrs** 2023-03-03 17:58 UTC
Labels: type/bug, area/panel/timeseries
