### ISSUE TITLE
Capturing fieldname and value for click for drilldown option

### ISSUE THREAD

**Issue by jayannah** [grafana/grafana#6400] opened 2016-10-27 14:48 UTC
I'm submitting a Bug/Feature request..
- [ ] Bug report
- [ ] Feature request

In the present scenario the multi level drilldown from top level to the deep drive is one of the key requirement to identify the rootcause. 

Grafana should provide way to capture the field name and value of mouse click from table or graph for using them in the further deep drive.

Please include this information:
- What Grafana version are you using?
3.0.4
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Linux
- What did you do?
Trying to implement multilevel drilldown table/graph from the mouse clicks
- What was the expected result?
The fieldnames & values of mouse click  are not captured
- What happened instead?
Nothing.

**Comment by torkelo** [comment] 2016-10-27 20:08
dupe of https://github.com/grafana/grafana/issues/1232

**Closed by torkelo** 2016-10-27 20:08 UTC
