### ISSUE TITLE
When user fails role_attribute_path, user is still granted "Viewer" role

### ISSUE THREAD

**Issue by Andrewpk** [grafana/grafana#26626] opened 2020-07-27 15:39 UTC
**What happened**:
* Created a `role_attribute_path` jmespath that maps specific oauth `/userInfo` to `Admin` and `Viewer` roles.
* If a user with oauth authentication fails this authorization check, the user is by default given the `Viewer` role anyway.

**What you expected to happen**:
* I expect that if a user succeeds in authentication, but fails the `role_attribute_path` authorization check, that the user is given an unauthorized role.

**How to reproduce it (as minimally and precisely as possible)**:

Simple Repro Config
1) Configure oauth login with an oauth system of your choice
2) Create a `role_attribute_path` rule that provides someone with a specific email address the `Admin` role and fails for any other email address.
3) Login with a different user/email than what was configured in step 2 which successfully authenticates with the configured oauth system from step 1.
4) Verify that you have `Viewer` access even though you failed all `role_attribute_path` checks.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: n/a
- OS Grafana is installed on: published docker image
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by torkelo** [comment] 2020-07-28 18:36
@alexanderzobnin do you know what is correct behavior here? I cannot find what happens if role is missing

**Comment by klausenbusk** [comment] 2020-09-24 19:08
> @alexanderzobnin do you know what is correct behavior here? I cannot find what happens if role is missing

Looking at the code, nothing happens: https://github.com/grafana/grafana/blob/adc1b965f322634abd8924d02db6bcb9253dad23/pkg/login/social/generic_oauth.go#L153-L156

We could probably add something like:
```go
if role == "unauthorized" {
	return nil, errors.New("user is unauthorized")
}
```
What do you think?

**Comment by klausenbusk** [comment] 2020-10-03 19:12
PR opened: https://github.com/grafana/grafana/pull/28021

**Comment by marefr** [comment] 2020-10-12 22:55
Duplicate of #23218

**Closed** 2020-10-12 22:55 UTC
Labels: needs investigation
