### ISSUE TITLE
Loki live tail: no message to the user when over the max concurrent tail requests limit

### ISSUE THREAD

**Issue by mattmendick** [grafana/grafana#32177] opened 2021-03-19 19:29 UTC
**What happened**:
When using Loki with the "live tail" feature, and there are already 5 concurrent tail requests (websocket connections to Loki), any subsequent connection requests will fail. However, this error is not propagated to the user, and is only visible by using the developer tools and turning on some additional options.

**What you expected to happen**:
The Grafana UI should display somehow that there was a failure in starting live tail because of the concurrent requests limit.

**How to reproduce it (as minimally and precisely as possible)**:
Open Explore for a Loki data source and perform a live tail on any query. Do this 4 more times to get to the maximum of 5. On the 5th try, begin live tail, but you will not see any data flowing.

**Anything else we need to know?**:
If you are using Firefox (Chrome doesn't expose this), open the network console, begin live tailing on the 6th attempt, and then enable the "All Control" feature of the Response tab for the websocket connection.
![image](https://user-images.githubusercontent.com/5992202/111832868-b2871a00-88c7-11eb-81b1-5ab0f7a53603.png)
This will let you see the error
![image](https://user-images.githubusercontent.com/5992202/111832883-ba46be80-88c7-11eb-953f-c950fa020b97.png)

**Environment**:
- Grafana version: Hosted Grafana, Grafana v7.4.5 (010f20c1c8)
- Data source type & version: Loki in Hosted Grafana
- OS Grafana is installed on: HG
- User OS & Browser: Mac Firefox 81.0
- Grafana plugins: N/A
- Others: N/A

**Comment by aocenas** [comment] 2021-10-04 08:54
I am not able re reproduce this right now. Is this some limit that was removed @slim-bean? I don't see any setting for this in the docs and `max_concurrent` queries do not seem to limit the live tails.

**Comment by gabor** [comment] 2022-02-10 10:04
pinging @grafana/loki-squad ... see https://github.com/grafana/grafana/issues/32177#issuecomment-933280875. , thanks!

**Comment by slim-bean** [comment] 2022-02-10 11:52
This limit still exists, `max_concurrent_tail_requests` is the name in the `limits:` section of the config and has a default value of 10. I don't see it in the docs either :( 

Some of our internal environments have this value set way higher than default, I will ping you with an environment that has it at 10 still.

**Comment by gabor** [comment] 2022-02-10 12:03
@mattmendick based on testing it seems we currently display an error message explaining the situation. i assume this got fixed since the original report. i will close the issue for now, but if you see still problems here, we can reopen it. thanks!

**Closed by gabor** 2022-02-10 12:03 UTC
Labels: type/bug, prio/medium, datasource/Loki
