### ISSUE TITLE
$timeFilter variable is shown in unknown variables yet is resolving

### ISSUE THREAD

**Issue by nathanpegram** [grafana/grafana#31530] opened 2021-02-27 18:56 UTC
**What happened**: 
The new variable reference maps are awesome, but are flagging $timerFilter as an unknown variable. I also get the $tag_VAR and $col - used in alias by fields - flagged as unknown. 

**What you expected to happen**:
I wouldn't expect to see these in the unknown list as they are resolving and working.

**How to reproduce it (as minimally and precisely as possible)**:
Adding a new panel with an influx query doesn't seem to cause this, but all dashboards with existing influx query driven panels prior to upgrade all have the $timeFilter variable flagged as unknown.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Currently running 7.4.2. Upgrade path was 6.7.3->7.3.7->7.4.2.
- Data source type & version: influxdb, not sure how to check data source version
- OS Grafana is installed on: ubuntu bionic
- User OS & Browser: mac os 10.15.17 & firefox 85
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2021-03-01 08:57
duplicate of https://github.com/grafana/grafana/issues/31212

**Closed by torkelo** 2021-03-01 08:57 UTC
