### ISSUE TITLE
generic oauth - failed to retrieve access token from oauth provider

### ISSUE THREAD

**Issue by onlylove168** [grafana/grafana#20407] opened 2019-11-15 09:39 UTC
I managed to log on to Grafana by generic oauth with my own single sign on server.

![image](https://user-images.githubusercontent.com/13606483/68932670-0e222e80-07ce-11ea-80d2-10f259e08f60.png)

It works fine but I got unexpected errors on the page when i refresh it after 1 hour.

I checked the log and found these error msg “Failed to retrieve access token from oauth provider”.

I can tell this was due to token expiry becasuse the error has gone after i logout and login again.

Grafana version: 6.4.3
OS: windows server 2012 R2

**Comment by marefr** [comment] 2019-11-15 15:37
Duplicate of #12131

**Comment by marefr** [comment] 2019-11-15 15:38
Grafana don't keep track when tokens are on the way to expire to automatically renew them. Closing this as duplicate because referenced issue is the solution to your problem.

**Closed by marefr** 2019-11-15 15:38 UTC
