### ISSUE TITLE
Loki Query Builder failed to convert the Line filter Loki Query Code

### ISSUE THREAD

**Issue by SanthoshS20** [grafana/grafana#53030] opened 2022-08-01 10:39 UTC
**What happened**:
Issue present in Loki Query Builder. Loki query code with the line filter ("Line does not match regex") is failed to convert in Builder mode. It is failed to convert and error was shown (**Operation "__line_matches_regex"_not not found**)

**What you expected to happen**:
Loki query builder should show the expected line filter ("Line does not match regex") in the UI when we convert the Loki query code to Loki query builder.

**How to reproduce it (as minimally and precisely as possible)**:
**Step 1:** Go the the Loki dashboard.
**Step 2:** Switch to the Loki query code.
**Step 3:** Create a query with the line filter ("Line does not match regex") and run the query.
**Step 4:** Switch to the builder mode.

Here you will see the error - **Operation "__line_matches_regex"_not not found**

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/37366893/182130553-77dcd0a9-1b2d-4792-af02-282b50415c49.png)

**Environment**:
- Grafana version: 9.0.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

**Comment by MustDie95** [comment] 2022-08-01 11:23
I confirm, encountered the same behavior with  

`{job="systemd-journal", nodename=~"$nodename", unit=~"$unit"} |~ "(?i)$searchable_pattern" !~ "(?i)$excluded_pattern"`

**Comment by usmangt** [comment] 2022-08-01 11:53
Hi @SanthoshS20, thanks for reporting this case.

Based on your steps of reproduction, I was also able to reproduce it on my test machine.

I am using :

Grafana-OSS ver 9.0.2 (running on Docker version 20.10.17, build 100c701)

**Comment by ivanahuckova** [comment] 2022-08-01 13:41
Thank you for reporting the issue. This is happening because of misspelled name for `__line_matches_regex_not`. This bug is already fixed on the main branch and fix will be part of the next minor release.

**Closed by ivanahuckova** 2022-08-01 13:41 UTC
Labels: type/bug, datasource/Loki
