### ISSUE TITLE
Grafana flux query fail error

### ISSUE THREAD

**Issue by ollie-campbell** [grafana/grafana#70604] opened 2023-06-23 13:31 UTC
### 
# What went wrong?

Dashboard refreshes cause errors in the grafana-server log, but dashboards appear OK.

**What happened**:

  - Errors showing in grafana-server log file after dashboard refreshes.

**What did you expect to happen**:

  - No errors.

### 
# How do we reproduce it?

**Step 1**:

- Open Grafana and refresh a dashboard.

**Step 2**:

- None.

**Step 3**:

- Server error messages saying:
`Jun 23 14:28:46 HOSTNAME grafana[41728]: logger=tsdb.influx_flux t=2023-06-23T14:28:46.584983091+01:00 level=warn msg="Flux query failed" err="Post \"https://HOSTNAME.HERE:8086/api/v2/query?org=ORG_HERE\": context canceled" query="from(bucket: \"BUCKET_NAME\")\r\n  |> range(start: -3s, stop: 2023-06-23T13:28:46.7Z)\r\n  |> filter(fn: (r) => r[\"Metric\"] == \"Alarm_info\")\r\n  |> last()"
`

### 
# What Grafana version are you using?

v10.0.1

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

A package manager (APT, YUM, BREW, etc.)

### User's OS?

Ubuntu 22.04.2 LTS

### User's Browser?

Brave v1.52.126

### Is this a Regression?

No

### Are Datasources involved?

InfluxDB v2.7.1 

### Anything else to add?

It only happens when an entire dashboard is refreshed using the browser. The dashboards have an auto-refresh of 1s, which doesn't seem to cause the issue.

**Comment by usmangt** [comment] 2023-06-26 09:39
Hi @ollie-campbell,

Thanks for opening this issue.

Looking at the message, it appears that this is a warning message which then relates to the query that is causing some problem and indicating it as an error.

I would recommend asking about this in our community forums under the [InfluxDB category](https://community.grafana.com/c/support/influxdb/11) as we do have very good community support (especially for the InfluxDB Data source).

I will close this issue but if you still do not get any help there, then let me know so I can reopen it.

**Comment by ollie-campbell** [comment] 2023-06-27 08:48
I have received no help at the other end. Please re-open this.

**Comment by gtk-grafana** [comment] 2023-07-06 18:30
`context canceled` indicates that the client (the browser) terminated the inflight request, which is expected when refreshing the browser, it's letting the server know that it doesn't need those requests anymore because the user is navigating away to another page.

**Comment by gtk-grafana** [comment] 2023-07-06 18:33
Closing as this is not a bug or feature request. I would suggest changing your [log level](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#level) if you don't want to see warnings in the output.

**Closed by gtk-grafana** 2023-07-06 18:33 UTC
Labels: datasource/InfluxDB, area/dashboard, triage/needs-confirmation
