### ISSUE TITLE
Prometheus DS: Relative time filters (Yesterday, Last week) adds extra data point to the request

### ISSUE THREAD

**Issue by v-zhuravlev** [grafana/grafana#42948] opened 2021-12-09 17:19 UTC
**What happened**:

Using time filter `Yesterday`(that expands to `08-11-21 00:00:00 - 08-11-21 23:59:59` in hint) (or other relative filters) would query Prometheus for extra data point. This would give significant error to calculations (total first of all).

Using corresponding to yesterday absolute time filter `08-11-21 00:00:00 - 08-11-21 23:59:59` would query the data as expected and would give `1` data point for `24h` aggregation, `24` data points for `1h` aggregation and 1440 data points for 1m aggregation.

<img width="2984" alt="Screenshot 2021-12-09 at 20 04 02" src="https://user-images.githubusercontent.com/14870891/145443849-a883dfc0-c5d1-434a-8839-01a37dd4308c.png">

<img width="2248" alt="Screenshot 2021-12-09 at 20 07 09" src="https://user-images.githubusercontent.com/14870891/145443772-78d6ff4b-ec26-43ea-9e87-82e14e60163a.png">

**What you expected to happen**:
Relative filters should not return extra data point from Prometheus DS as it messes the results when aggregated by large intervals. 

Let's say you want to calculate total number of bytes received during yesterday and show it on graph panel. 
Since you have two data points, you basically have totals for two days instead. (7883804675007  instead of 4029532001682 in my example)
<img width="2992" alt="Screenshot 2021-12-09 at 20 20 54" src="https://user-images.githubusercontent.com/14870891/145445082-e1e948d5-11f5-4794-9ae8-49e04c463590.png">

If you aggregate by 1h - you would have data for 25 hours instead.

**How to reproduce it (as minimally and precisely as possible)**:

Use any metric from prometheus datasource (prefer counters)

add simple graph and two prometheus queries:

increase(node_network_receive_bytes_total[24h], min step 24h)
increase(node_network_receive_bytes_total[1h]), min step 1h

Add total and count calculations to graph legend.

<img width="1483" alt="Screenshot 2021-12-09 at 20 12 58" src="https://user-images.githubusercontent.com/14870891/145443697-4f1ffd26-a31d-438f-8dc1-4698e109112f.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.2.6 and v8.1.7
- Data source type & version: Prometheus 2.31.1

**Comment by ivanahuckova** [comment] 2022-01-14 12:45
Hello @v-zhuravlev, could you please try v8.3+ because we have moved query + response processing to a backend. I have tried to reproduce this on v8.3.3, but both `Yesterday` and `absolute range of yesterday` gave me the same from-to timestamps. So it seems that migration to backend helped fix this.

**Comment by v-zhuravlev** [comment] 2022-01-17 10:55
Thanks @ivanahuckova , I can confirm this problem is no longer reproducible in 8.3.3!

**Comment by ivanahuckova** [comment] 2022-01-17 15:47
Awesome! Thank you for confirmation. Closing the issue. 🎉

**Closed by ivanahuckova** 2022-01-17 15:47 UTC
Labels: needs more info, datasource/Prometheus
