### ISSUE TITLE
Unable to get property 'indexOf' of undefined or null reference

### ISSUE THREAD

**Issue by ahmenezes** [grafana/grafana#13359] opened 2018-09-20 08:59 UTC
### What Grafana version are you using?
Grafana v5.2.3 (cf4c090

### What datasource are you using?
ElasticSearch

### What OS are you running grafana on?
Ubuntu
result of uname -a 
uname -a
Linux 4.15.0-1023-azure #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
In a Table Panel, when magnifier is used to filter values exception is created instead of filter. Table moves to empty as uploaded image

### What was the expected result?
table filter (in or out) values

### What happened instead?

TypeError: Unable to get property 'indexOf' of undefined or null reference
   at t.prototype.getAdhocFilters (http://hostname/public/build/0.6aa12092d3333cb24394.js:1:62721)
   at t.prototype.query (http://hostname/public/build/0.6aa12092d3333cb24394.js:7:107362)
   at e.prototype.issueQueries (http://hostname/public/build/0.6aa12092d3333cb24394.js:7:18156)
   at e.prototype.issueQueries (http://hostname/public/build/0.6aa12092d3333cb24394.js:7:303988)
   at u (http://hostname
[console-1537433886441.log](https://github.com/grafana/grafana/files/2400532/console-1537433886441.log)
[console-1537433886441.log](https://github.com/grafana/grafana/files/2400534/console-1537433886441.log)

:3000/public/build/vendor.6aa12092d3333cb24394.js:87:68718)
   at Anonymous function (http://hostname/public/build/vendor.6aa12092d3333cb24394.js:87:69127)
   at h.prototype.$digest (http://hostname/public/build/vendor.6aa12092d3333cb24394.js:87:74810)
   at Anonymous function (http://hostname/public/build/vendor.6aa12092d3333cb24394.js:87:76438)
   at i (http://hostname/public/build/vendor.6aa12092d3333cb24394.js:87:21868)
   at Anonymous function (http://hostname/public/build/vendor.6aa12092d3333cb24394.js:87:23320)

![image](https://user-images.githubusercontent.com/37075495/45807172-c6337480-bcba-11e8-966a-0667279c0035.png)

**Comment by ahmenezes** [comment] 2018-09-20 09:03
including console log with additional info
[console-1537433886441.log](https://github.com/grafana/grafana/files/2400544/console-1537433886441.log)

**Comment by ahmenezes** [comment] 2018-09-20 10:13
Console Log
[console-1537433886441.log](https://github.com/grafana/grafana/files/2400784/console-1537433886441.log)

**Comment by marefr** [comment] 2018-09-20 13:02
Would need some more information. What field/value where you using the magnifier on? And how does the mapping in ES look for that field? How have you enabled adhoc-filters in Settings -> Variables - like this? 

![image](https://user-images.githubusercontent.com/1668778/45820065-3acfd880-bce6-11e8-9f28-def1bd9fe1d7.png)

**Comment by ahmenezes** [comment] 2018-09-20 14:47
Hi, I'm uploading JSON with panel definition
ES field is string.
I had no variables, so adhoc-filters were not used.
I created as you indicated, but result is not the expected.the result looks like this:
![image](https://user-images.githubusercontent.com/37075495/45826289-2393e980-bcec-11e8-9c9d-84610edb96b3.png)
[console-1537433886441.log](https://github.com/grafana/grafana/files/2401777/console-1537433886441.log)

**Comment by ahmenezes** [comment] 2018-09-20 14:49
table before filtering looks like this
![image](https://user-images.githubusercontent.com/37075495/45826610-b6348880-bcec-11e8-8eb3-1ac6d9b30bf8.png)

**Comment by marefr** [comment] 2018-09-20 14:59
Weird that you get another "Filters" component which make it two. DId you save and reload the dashboard after you've added the ad-hoc filters? Would it be possible for you to include your dashboard json model?

**Comment by ahmenezes** [comment] 2018-09-20 15:38
I agree, It's very strange. but this happens with every dashboards with tables.
Yes I saved after adding ad-hoc filters. 
I'm uploading dashboard json
[AMTeste-1537457593094.zip](https://github.com/grafana/grafana/files/2402013/AMTeste-1537457593094.zip)

**Comment by torkelo** [comment] 2018-09-20 16:20
Are you using mixed datasource ? Is the datasource in the panel the exact same as you defined in the ad hoc filter ?

**Comment by marefr** [comment] 2018-09-20 16:27
@ahmenezes uploaded dashboard is in exported format (Share -> Export). Would rather need Settings -> Json Model -> Copy content to file and upload. Thanks

**Comment by ahmenezes** [comment] 2018-09-20 16:46
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 69,
  "iteration": 1537457467582,
  "links": [],
  "panels": [
    {
      "columns": [
        {
          "text": "WASPerformance.BlockedThreadInfo.blockedCount",
          "value": "WASPerformance.BlockedThreadInfo.blockedCount"
        },
        {
          "text": "WASPerformance.BlockedThreadInfo.threadName",
          "value": "WASPerformance.BlockedThreadInfo.threadName"
        },
        {
          "text": "WASPerformance.BlockedThreadInfo.waitedCount",
          "value": "WASPerformance.BlockedThreadInfo.waitedCount"
        },
        {
          "text": "WASPerformance.BlockedThreadInfo.stackTrace",
          "value": "WASPerformance.BlockedThreadInfo.stackTrace"
        }
      ],
      "datasource": null,
      "fontSize": "100%",
      "gridPos": {
        "h": 19,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "links": [],
      "pageSize": null,
      "scroll": true,
      "showHeader": true,
      "sort": {
        "col": 0,
        "desc": true
      },
      "styles": [
        {
          "alias": "Blocked",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "WASPerformance.BlockedThreadInfo.blockedCount",
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "Thread Name",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "WASPerformance.BlockedThreadInfo.threadName",
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "Count",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "WASPerformance.BlockedThreadInfo.waitedCount",
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "Stack",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "WASPerformance.BlockedThreadInfo.stackTrace",
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "decimals": 2,
          "pattern": "/.*/",
          "thresholds": [],
          "type": "number",
          "unit": "short"
        }
      ],
      "targets": [
        {
          "bucketAggs": [],
          "metrics": [
            {
              "field": "select field",
              "id": "1",
              "meta": {},
              "settings": {
                "size": 500
              },
              "type": "raw_document"
            }
          ],
          "query": "metricset.name:\"BlockedThreadInfo\"  AND host_name:adpemdbpm0",
          "refId": "A",
          "timeField": "timestamp_occurred"
        }
      ],
      "title": "Panel Title",
      "transform": "json",
      "type": "table"
    }
  ],
  "schemaVersion": 16,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "datasource": "Kamino",
        "filters": [],
        "hide": 0,
        "label": null,
        "name": "Filters",
        "type": "adhoc"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "",
  "title": "AMTeste",
  "uid": "1qPWk9Tiz",
  "version": 14
}

**Comment by ahmenezes** [comment] 2018-09-20 16:46
>           Are you using mixed datasource ? Is the datasource in the panel the exact same as you defined in the ad hoc filter ?

yes, same datasource

**Comment by marefr** [comment] 2018-09-20 18:17
Datasource property in your panel is null - any idea how that happen? Was that due to adding an ad-hoc filter?

**Comment by ahmenezes** [comment] 2018-09-21 08:39
@marefr ,datasource is null because is set to default.
I changed from default to a specific datasource. 
After this change, filters work as expected!
in conclusion, "Default"  setting changes the behavior of the ad-hoc filters.
If datasource = default, we get the error above.
if datasource != default, ad-hoc works fine.
I bellieve this behavior was introduced in Grafana v5.2.3

![image](https://user-images.githubusercontent.com/37075495/45869980-c2b6f080-bd81-11e8-8470-531b37abdfb8.png)

**Comment by marefr** [comment] 2018-09-21 09:50
Thank you for the details. Now I was able to reproduce on v5.2.3. However not able to reproduce on v5.3-pre1 (master) so fix for this will be included in v5.3 stable.

**Closed by marefr** 2018-09-21 09:50 UTC
Labels: state: needs more detail
