### ISSUE TITLE
Loki: Cannot display logs when using "repeating" on a panel

### ISSUE THREAD

**Issue by erandu** [grafana/grafana#21643] opened 2020-01-21 13:21 UTC
**What happened**:

I am using Loki to display logs of my Kubernetes Pods. I have a variable than contains the list of my Kubernetes pods, and a panel that uses this variable with the "repeating" option for this variable. So my dashboard contains one panel per pod.

When I select only one pod, the logs are well displayed into the panel. But when I choose two or more pods, I can't see any logs on panels that are repeated.

With one value (1 pod) selected :
![oe_pod](https://user-images.githubusercontent.com/10061868/72809865-cb148980-3c5c-11ea-95e1-2755b6f9b0d3.png)

 
With two values (2pods) selected : 
![oe_2pods](https://user-images.githubusercontent.com/10061868/72809706-753fe180-3c5c-11ea-955d-ee49be5ed48d.png)

**What you expected to happen**:

To see logs within panels repeated when I select more than one option to my variable.

**How to reproduce it (as minimally and precisely as possible)**:

Using Loki, Promtail, Grafana and Kubernetes : 

Create a variable using a query that generate a list of pods within Kubernetes cluster.
Add options "multi-value" and "Include all option" to this variable.
Create a panel for Logs using Loki as a datasource.
Add this query : {instance="$pod"} (where pod is the name/label of the variable created)
And on general configuration of the panel, repeating menu, select pod for repeat, and choose horizontal or vertical.
Then select some pods in the variable menu, and the panels are empty.
Select only one pod in the variable menu, and if your pod have logs, then you can see them.

**Anything else we need to know?**:

We use Promtail to collect logs of Kubernetes Pods and put them into Loki.

**Environment**:
- Grafana version: grafana:6.6.0-beta1
- Data source type & version: Loki v1.2.0
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10 / Chrome  79.0.3945.117
- Grafana plugins: 
- Others:

**Comment by aknuds1** [comment] 2020-01-22 10:21
Thanks for reporting this, but it looks as if it's a duplicate of #21419. Please let us know if it turns out not to be the case! :)

**Closed by aknuds1** 2020-01-22 10:21 UTC
Labels: area/panel/logs, datasource/Loki, type/bug
