### ISSUE TITLE
Submenu is not visible due to viewport limit while editing panel

### ISSUE THREAD

**Issue by neel5481** [grafana/grafana#25701] opened 2020-06-18 16:21 UTC
Grafana build from master branch.

When user edit the panel and hover the "More" to click on "Duplicate" action. Submenu is not visible due to view area. Submenu should open left side when there is no space to render on right side.

Check below screenshot where, we hove on "More" but "Duplicate" and "Copy" action is not visible which is under submenu. We should render the Submenu left side when there is no space for view.

![grafana](https://user-images.githubusercontent.com/4135603/85046203-b60d3980-b1ad-11ea-8af9-064c5e45f392.jpg)

Let us know in case you require more information.

**Comment by torkelo** [comment] 2020-06-19 07:43
duplicate of https://github.com/grafana/grafana/issues/23095

**Closed by torkelo** 2020-06-19 07:43 UTC
