### ISSUE TITLE
Dashboards: Mixed Datasource: Error When Selecting Prometheus DS

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#69936] opened 2023-06-12 15:28 UTC
### 
# What went wrong?

![image](https://github.com/grafana/grafana/assets/1692624/676a0a3a-39de-44c3-9ef7-3c43b25ddb66)

### 
# How do we reproduce it?

Create Dashobard, picked mixed, and test datasource query, add another query, try to select prom datasource.

### 
# What Grafana version are you using?

555ebb891b

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

None

### Is this a Regression?

None

### Anything else to add?

Seems to work fine in explore.

**Comment by gtk-grafana** [comment] 2023-06-12 17:39
@kylebrandt Potential duplicate of https://github.com/grafana/grafana/issues/69935? 
Does the fix here help? https://github.com/grafana/grafana/pull/69938

**Closed by gtk-grafana** 2023-06-12 17:39 UTC
Labels: datasource/Prometheus, area/frontend
