### ISSUE TITLE
Unit fields overrides not working as Intended

### ISSUE THREAD

**Issue by Angga-XII** [grafana/grafana#30220] opened 2021-01-12 11:51 UTC
**What happened**:
when overriding a field unit using fields with name option, unit on all fields changes. 

**What you expected to happen**:
override only occurs on the selected field.

**How to reproduce it (as minimally and precisely as possible)**:
1. add 2 or more fields.
2. use the field tab to set a unit for all fields. (in my case 0-100%)
3. go to override tab and pick "fields with name" options, and then pick a fields and unit ("Temperature" to "celcius" unit).

**Anything else we need to know?**:
weirdly enough the override only happens when picking 1 out of 3 fields (in my case "Temperature" field). 
![1610449033746](https://user-images.githubusercontent.com/16426926/104307603-00ffed00-5502-11eb-8fee-787ea330a363.jpg)
![1610449081267](https://user-images.githubusercontent.com/16426926/104307599-ffcec000-5501-11eb-850f-92855071afb0.jpg)
![1610449127572](https://user-images.githubusercontent.com/16426926/104307594-fd6c6600-5501-11eb-91a8-c106c67ac023.jpg)

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: influxdb v1.8.3
- OS Grafana is installed on: Raspberry Pi OS with desktop 5.4 (02-december-2020)

**Comment by torkelo** [comment] 2021-01-12 12:28
In the old graph you can only have a different unit if it's on a different axis. 

This will work with the new graph panel coming in v7.4 (that will only use field & override settings for all options) 


dupe of https://github.com/grafana/grafana/issues/30008

**Closed by torkelo** 2021-01-12 12:28 UTC
