### ISSUE TITLE
Add a custom unit directly in the unit section?

### ISSUE THREAD

**Issue by jeanduporte** [grafana/grafana#19853] opened 2019-10-16 09:54 UTC
Hello,

I use Grafana to display some chemicals data (conductivity, flow, etc.) and I thought it would be nice to have some more units, for example, the conductivity is in µS/cm or the flow in m³/h.

Instead of asking each time to add a unit, it would be nice to write directly to the unit section (see the picture in the attachment). I know that possible to write a prefix for some panels (Graph for example) but in my case, I'm using the panel Gauge and it is impossible to write a postfix.

![Capture d’écran 2019-10-16 à 11 50 56](https://user-images.githubusercontent.com/28293036/66908372-3c63f100-f00b-11e9-88a8-dc73e87780d8.png)

**Comment by torkelo** [comment] 2019-10-16 11:10
duplicate of https://github.com/grafana/grafana/issues/2968

**Closed by torkelo** 2019-10-16 11:10 UTC
