### ISSUE TITLE
Link to dashboard with qualified organisation

### ISSUE THREAD

**Issue by jobrs** [grafana/grafana#4462] opened 2016-03-23 16:22 UTC
We are using Grafana together with the OpenStack Keystone authentication plugin. In OpenStack environment we have a larger number of projects and even domains which are mapped to Grafanas organisations.

Since the "Share Dashboard" functionality includes only the dashboard name but not the organisation into the link URL, the link will only work if its recipient belongs to a single organisation. 

If the generated links would include a unique qualifier for both dashboard and organisation and Grafana would use this information, then users with adequate permission could jump to a shared dashboard with a single click.

**Comment by bergquist** [comment] 2016-03-23 21:23
Hi

Thanks for taking the time to make grafana better.
This seems like a duplicate of https://github.com/grafana/grafana/issues/1613 so I'm going to close it. 
Lets continue the discussion in that issue.

/Carl

**Closed by bergquist** 2016-03-23 21:23 UTC

**Comment by jobrs** [comment] 2016-03-24 08:59
Hi, indeed I missed this one while searching for an existing issue. 

Thanks
Joachim
