### ISSUE TITLE
[Bug] Hiding a query in graph results in "No Data Points"

### ISSUE THREAD

**Issue by msm93v2** [grafana/grafana#8439] opened 2017-05-22 13:24 UTC
Using Grafana 4.3.0-beta1 with a Promtheus data source, toggling a query as hidden on a graph with multiple queries, "No Data Points" is shown on the graph despite the other queries having data to display. attached are screen shots showing the effect of toggling one of the queries as hidden. This is a new issue after coming from 4.2 (stable).
![datapoints](https://cloud.githubusercontent.com/assets/25506816/26310845/5035c95e-3ed0-11e7-83e3-194c736c0adf.png)
![nodatapoints](https://cloud.githubusercontent.com/assets/25506816/26310851/54150eb8-3ed0-11e7-8590-1b6f0c091c5e.png)
Let me know what other information may be valuable in addressing this issue.

**Comment by torkelo** [comment] 2017-05-22 13:38
duplicate of https://github.com/grafana/grafana/issues/8413

**Closed by torkelo** 2017-05-22 13:38 UTC
