### ISSUE TITLE
[Table] Render Column With Clickable Link

### ISSUE THREAD

**Issue by Kenith** [grafana/grafana#8684] opened 2017-06-22 08:54 UTC
Hello All,

These days, we are trying to render the column with clickable link.
We take time to search the result in Grafana repository, but failed.

We have 2 columns "Report" and "Log". In these 2 columns, we have already poured the data source, for example "`<a href="http://127.0.0.1:8085/browse/FOR-DEMO-1/artifact/JOB1/Report/" target="_blank">Report</a>`",  in them as following, and we tried to set the column "Report" as "Sanitize HTML". The <a> is link still not turned into "Report", and still not clickable.

Is anything solution for this?
Or would you please add a "Link" type into table?

<img width="1410" alt="screen shot 2017-06-22 at 4 41 22 pm" src="https://user-images.githubusercontent.com/14316290/27425397-de2c988e-576a-11e7-91f3-c64bb20f087d.png">

Thank you,
Ken

**Comment by torkelo** [comment] 2017-06-22 15:39
duplicate of https://github.com/grafana/grafana/issues/3754

**Closed by torkelo** 2017-06-22 15:39 UTC
