### ISSUE TITLE
Alert is not sent if render hangs

### ISSUE THREAD

**Issue by StupidScience** [grafana/grafana#21018] opened 2019-12-11 07:59 UTC
**What happened**:
I have some problem with image rendering. I tried PhantomJS and external renderer and still have similar result. 
But what is really bad that when render is broken Grafana do not send any alert notification. 

So I disable images in alert notifications.

**What you expected to happen**:
Grafana send alert notification even if it can't render image.

**How to reproduce it (as minimally and precisely as possible)**:
* Break your image rendering
* Trigger alert
* Got nothing in your notification channels

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.1
- Data source type & version: Any
- OS Grafana is installed on: Docker

**Comment by aknuds1** [comment] 2019-12-11 10:53
Can you please enable debug logging and paste your logs?

**Comment by StupidScience** [comment] 2019-12-11 11:01
If I use external renderer then I got in Grafana logs:
```
t=2019-12-11T10:53:53+0000 lvl=eror msg="Remote rendering request failed" logger=rendering error="500 Internal Server Error"
```
And something like this in Renderer logs:
```
::ffff:10.0.0.86 - - [11/Dec/2019:10:28:04 +0000] "GET /render?domain=grafana&encoding=&height=500&renderKey=OXiIC7ERTtIwa8IKLgoO3IGhKavPSAGQ&timeout=60&timezone=Europe%2FMoscow&url=http%3A%2F%2Fgrafana%2Fd-solo%2FxaYxwRRik%2Fkubernetes-pods%3Ftab%3Dvisualization%26orgId%3D1%26var-Namespace%3Dmonitoring%26var-Container%3Dgrafana%26panelId%3D2%26from%3D1576055019557%26to%3D1576058619557%26width%3D1000%26height%3D500%26tz%3DEurope%252FMoscow%26render%3D1&width=1000 HTTP/1.1" 500 96 "-" "Go-http-client/1.1"
render request received for http://grafana/d-solo/xaYxwRRik/kubernetes-pods?tab=visualization&orgId=1&var-Namespace=monitoring&var-Container=grafana&panelId=2&from=1576055019557&to=1576058619557&width=1000&height=500&tz=Europe%2FMoscow&render=1
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/usr/src/app/node_modules/puppeteer/lib/NavigatorWatcher.js:74:21)
  stack:
   'TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded\n    at Promise.then (/usr/src/app/node_modules/puppeteer/lib/NavigatorWatcher.js:74:21)',
  message: 'Navigation Timeout Exceeded: 30000ms exceeded',
  name: 'TimeoutError',
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function],
  isDeveloperError: true }
```

So it is timeouted.

Do you need alerting-related logs?
Can you please specify how to enable debug log for alerting?

**Comment by marefr** [comment] 2019-12-11 11:53
@StupidScience Have a feeling that this may be related to dashboard refresh, do you have dashboard refresh enabled in all of your dashboard you're trying to render? If no, please try disable refresh and save the dashboard and try to render again. Maybe releated to https://github.com/grafana/grafana-image-renderer/pull/24 included in v1.0.6. 

If that doesn't work, we'll need some more information from you:
- What version of remote rendering service? How do you run it, in Docker?
- Please include a dashboard json model (as simple as possible) where a panel render times out
- Include your configuration related to the sections [[server]](https://grafana.com/docs/grafana/latest/installation/configuration/#server) and [[rendering](https://grafana.com/docs/grafana/latest/installation/configuration/#rendering)` (remove sensitive information, if any)
- Changing log level to debug will include alerting and rendering debug messages ,see [[log]](https://grafana.com/docs/grafana/latest/installation/configuration/#level). Then include relevant log messages here (remove sensitive information, if any). If you want more granular control of what debug messages being logged have a look  [here](https://grafana.com/docs/grafana/latest/alerting/rules/#troubleshooting) and [here](https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshooting).

Thanks

**Comment by StupidScience** [comment] 2019-12-11 12:53
@marefr I'm pretty sure it's not image-renderer bug coz it also occur with PhantomJS and I don't use dashboard refreshing.

Now answers:
* Rendering service run in docker. Its version is `1.0.7`. It is running in docker in k8s. But again, I believe it is not renderer issue
* I've created new dashboard from scratch, here its json:
```{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 172,
  "links": [],
  "panels": [
    {
      "alert": {
        "alertRuleTags": {},
        "conditions": [
          {
            "evaluator": {
              "params": [
                0
              ],
              "type": "gt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "A",
                "5m",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "avg"
            },
            "type": "query"
          }
        ],
        "executionErrorState": "keep_state",
        "for": "",
        "frequency": "1m",
        "handler": 1,
        "name": "Panel Title alert",
        "noDataState": "ok",
        "notifications": [
          {
            "uid": "000000011"
          }
        ]
      },
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Prometheus",
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "dataLinks": []
      },
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "up{app=\"advertising-service\"}",
          "refId": "A"
        }
      ],
      "thresholds": [
        {
          "colorMode": "critical",
          "fill": true,
          "line": true,
          "op": "gt",
          "value": 0
        }
      ],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 21,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "New dashboard Copy",
  "uid": "rUvMIj-Wz",
  "version": 2
}
```
*  Server section:
```
server:
        protocol: http
        root_url: https://grafana.example.com
```
* Rendering section:
```
    env:
      GF_RENDERING_CALLBACK_URL: http://grafana/
      GF_RENDERING_SERVER_URL: http://grafana-image-renderer/render
```
* I have a lot of logs, not sure which of them are relevant. Hope it will be enough:

```
kl grafana-fd68d44c4-x27dp -f | grep 'alerting' | grep -e 'notifier\|Panel Title alert'
t=2019-12-11T12:30:13+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:30:33+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=241.272 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:31:12+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:31:42+0000 lvl=dbug msg="Job Execution attempt triggered retry" logger=alerting.engine timeMs=0.190 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:31:55+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-15.761 alertId=150 name="Panel Title alert" firing=true attemptID=2
t=2019-12-11T12:32:11+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:32:41+0000 lvl=dbug msg="Job Execution attempt triggered retry" logger=alerting.engine timeMs=0.205 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:33:11+0000 lvl=dbug msg="Job Execution attempt triggered retry" logger=alerting.engine timeMs=0.242 alertId=150 name="Panel Title alert" firing=true attemptID=2
t=2019-12-11T12:33:41+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=150 name="Panel Title alert" error="tsdb.HandleRequest() error Get http://thanos-query-http:10902/api/v1/query_range?end=2019-12-11T12%3A33%3A11.338127174Z&query=up%7Bapp%3D%22advertising-service%22%7D&start=2019-12-11T12%3A28%3A11.338127174Z&step=15.000: context deadline exceeded" changing state to=keep_state
t=2019-12-11T12:33:41+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=0.234 alertId=150 name="Panel Title alert" firing=true attemptID=3
t=2019-12-11T12:34:09+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:34:29+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=349.645 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:34:57+0000 lvl=dbug msg="Sending notification" logger=alerting.notifier type=webhook uid=Nh0PQlaZz isDefault=false
t=2019-12-11T12:34:57+0000 lvl=info msg="Sending webhook" logger=alerting.notifier.webhook
t=2019-12-11T12:35:08+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:35:27+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=491.890 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:36:07+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:36:24+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-122.534 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:37:06+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:37:06+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=66.655 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:38:05+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:38:05+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=116.868 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:39:04+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:39:04+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=110.228 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:40:03+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:40:03+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=129.091 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:41:02+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:41:07+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=-106.633 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:42:01+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:42:01+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=161.243 alertId=150 name="Panel Title alert" firing=true attemptID=1
t=2019-12-11T12:43:59+0000 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=150
t=2019-12-11T12:44:29+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Failed to send request to remote rendering service. Get http://grafana-image-renderer/render?domain=grafana&encoding=&height=500&renderKey=Z3ozG4sIp2G6W20HPKN7TPWIRbU87zNA&timeout=30&timezone=&url=http%3A%2F%2Fgrafana%2Fd-solo%2FrUvMIj-Wz%2Fnew-dashboard-copy%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000: context deadline exceeded"
t=2019-12-11T12:44:29+0000 lvl=dbug msg="Sending notification" logger=alerting.notifier type=slack uid=000000011 isDefault=false
t=2019-12-11T12:44:29+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=150 notification=#grafana-infrastructure
t=2019-12-11T12:44:29+0000 lvl=eror msg="Failed to send slack notification" logger=alerting.notifier.slack error="context deadline exceeded" webhook=#grafana-infrastructure
t=2019-12-11T12:44:29+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000011 error="context deadline exceeded"
t=2019-12-11T12:44:29+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=000000011 error="context deadline exceeded"
t=2019-12-11T12:44:29+0000 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=208.229 alertId=150 name="Panel Title alert" firing=false attemptID=1
```

That what i got when request `Share -> Link -> Direct link rendered image`
```
kl grafana-fd68d44c4-x27dp -f | grep 'logger=render'
t=2019-12-11T12:29:24+0000 lvl=info msg="Backend rendering via external http server" logger=rendering
t=2019-12-11T12:30:29+0000 lvl=eror msg="Remote rendering request failed" logger=rendering error="500 Internal Server Error"
t=2019-12-11T12:44:29+0000 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering error="Get http://grafana-image-renderer/render?domain=grafana&encoding=&height=500&renderKey=Z3ozG4sIp2G6W20HPKN7TPWIRbU87zNA&timeout=30&timezone=&url=http%3A%2F%2Fgrafana%2Fd-solo%2FrUvMIj-Wz%2Fnew-dashboard-copy%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000: context deadline exceeded"
```

Also, if it is important Grafana is run in Kubernetes, and was installed with Helm. It worked till yesterday. And at some moment just broke.

**Comment by marefr** [comment] 2019-12-11 20:11
@StupidScience thanks. Weird it worked yesterday - What is different compared to yesterday? Any versions of something changed?

- Could you try the v1.0.5 of the image renderer service?
- Could be related to dns problem in k8s if you're using Grafana Alpine based docker image. Would suggest trying the ubuntu based docker image.
- Could be related to not enough memory resources like CPU and memory available for the renderer container.

**Comment by StupidScience** [comment] 2019-12-11 21:35
Yep, that's pretty strange. I believe that biggest thing that was changed yesterday was adding new notification channel and setting it to some alerts. I already tried to delete it and it didn't help.
Also yesterday I used default PhantomJS renderer so I switched to external renderer today just for trying figure out what is going on.
At the moment looks like rendering works, but rendering take a lot of time (TTFB around 15 second). I will retest it tomorrow when Grafana have a bit more load.

* I've tried 1.0.5 and nothing drastically changed
* I already tried ubuntu-based image, also without any success.
* I checked it. There is enough CPU/memory.

Once again I believe that issue is not relates to image renderer itself.
Also for me biggest problem that alerts are not sent when rendering broken.

**Comment by 3nin6** [comment] 2019-12-12 16:43
+1 that the worst part of the issue is that a render failure causes alerts not to be sent. 

Assuming an alert is generated successfully, any individual missing/delayed piece of data that is part of the body of the alert should not be allowed to cause the sending of the alert to fail. Way better to receive an empty alert in any of our notification channels and then fish out what it was than nothing at all.

Saw same symptoms in 6.5.1 / 6.5.2 being deployed from helm stable charts 4.1.0 and 4.1.3. Issue was not fully consistent in my case: 
- alert notifications went through inconsistently from graphs sourced from elasticsearch
- alert notifications from prometheus sourced graphs were consistently failing

 I've rolled back image tags from 6.5.x to 6.4.x for now.

**Comment by itmecho** [comment] 2020-01-13 14:29
I upgraded from `6.4.2` to `6.5.2` and saw this behavior. Nothing else changed and reverting back to `6.4.2` fixes the problem. I am using the default phantomJS renderer in the `grafana/grafana` docker image.

Email notifications still get sent but don't include the image of the graph. Slack notifications never come through.

**Comment by aknuds1** [comment] 2020-01-16 16:02
@StupidScience For which notification channels are your alerts not being sent? Slack? Email?

**Comment by StupidScience** [comment] 2020-01-16 16:51
@aknuds1 I use Slack and webhook channels and problem occurs for both of them.

**Comment by marefr** [comment] 2020-01-17 10:59
Thanks all. Fix will be included in 6.6.0-beta1 planned to be released on Monday.

**Closed** 2020-01-17 11:07 UTC
Labels: area/alerting, area/image-rendering, type/bug

**Comment by mcs** [comment] 2020-02-18 14:58
> Thanks all. Fix will be included in 6.6.0-beta1 planned to be released on Monday.

Well, I just upgraded vom 6.5.1 to 6.6.1 because of the fix. But I still only get "OK" mails, but nothing when alert state changes to "Alerting".

```
t=2020-02-18T14:40:30+0000 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=15 newState=pending prev state=ok

t=2020-02-18T14:42:45+0000 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=15 newState=alerting prev state=pending
t=2020-02-18T14:42:45+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[all@the.people]" singleEmail=false

t=2020-02-18T14:48:45+0000 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=15 newState=ok prev state=alerting
t=2020-02-18T14:48:45+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[all@the.people]" singleEmail=false
```
I did not delete any lines, this is the whole logging part. The "newState=alerting" mail is not send, the "newState=ok" mail is sent. This happens even though I disabled image rendering in the email alerting configuration.

I'm using docker image `grafana/grafana:6.6.1`

**Comment by marefr** [comment] 2020-02-18 21:18
@mcs Seems to be sent to me since there are no errors logged. Maybe a network problem?

**Comment by marefr** [comment] 2020-02-18 22:35
@kylebrandt that worked. Will merge this now, but we can probably improve this later since right now the resources are just test handlers. Would be nice to find a use case for populate something in query editor.

**Comment by mcs** [comment] 2020-02-19 08:50
@marefr I have no idea what changed over night, but today the alerting works fine with 6.6.1. Yesterday, three sequential alerting tests went wrong.

Sorry for bothering you...

**Comment by ajitchahal** [comment] 2020-06-05 14:32
with 6.6.1 the upload of image still does not work. 
```
t=2020-06-05T14:28:41+0000 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=1 newState=ok prev state=alerting

t=2020-06-05T14:28:41+0000 lvl=info msg=Rendering logger=rendering renderer=phantomJS path="d-solo/lwogG7iMk/test-1?orgId=1&panelId=2"

t=2020-06-05T14:28:56+0000 lvl=info msg="Rendering timed out" logger=rendering renderer=phantomJS

t=2020-06-05T14:28:56+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=1 error="Timeout error. You can set timeout in seconds with &timeout url parameter"

t=2020-06-05T14:28:56+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification=notification-channel-1
```
What works, is even if the upload of image fails, the alert is sent to target system.
