### ISSUE TITLE
[New Data Source]: PRTG

### ISSUE THREAD

**Issue by roaralmli** [grafana/grafana#93644] opened 2024-09-24 07:54 UTC
### Background

Network monitoring

### Use case

Grafana can visualize prtg data in an excellent way.

### Contribution

- [ ] Are you looking to create the plugin?
- [ ] Are you affiliated with the project/product the data source integrates with?
- [ ] Does the plugin integrate with a commercial product?

**Comment by sympatheticmoose** [comment] 2024-11-05 11:22
closing as duplicate of [#90786](https://github.com/grafana/grafana/issues/90786) please upvote the original issue

**Closed by sympatheticmoose** 2024-11-05 11:22 UTC
Labels: area/datasource, type/new-plugin-request
