### ISSUE TITLE
stack not working in series mode

### ISSUE THREAD

**Issue by YuvrajSingh79** [grafana/grafana#11200] opened 2018-03-12 06:50 UTC
What Grafana version are you using? - 5.0
### What happened instead? functionality not working

Please refer the screenshot below :-
![image](https://user-images.githubusercontent.com/16950851/37269270-a79fda16-25ef-11e8-8747-3fcb31fb8a93.png)

I just want the output of my queries to be stacked in series mode, instead it is coming side by side.

can anyone guide me regarding the same.

**Comment by marefr** [comment] 2018-03-12 12:01
Closing this as duplicate of #7949

**Closed by marefr** 2018-03-12 12:01 UTC

**Comment by YuvrajSingh79** [comment] 2018-03-12 13:51
@marefr thanks for reference, but can you suggest any alternative to achieve the above requirement as it is matter of priority to me

**Comment by marefr** [comment] 2018-03-12 14:23
Use X-Axis mode time instead. Otherwise, please continue with comments/questions in #7949. Thanks
