### ISSUE TITLE
[notification] telegram via proxy

### ISSUE THREAD

**Issue by mator** [grafana/grafana#20550] opened 2019-11-21 10:03 UTC
**What would you like to be added**:

Please add support for telegram proxy , for example via [mtproto / mtproxy](https://github.com/alexbers/mtprotoproxy)

**Why is this needed**:

getting 'connection reset' on my alert/notification (probably because ISP is blocking telegram):

    t=2019-11-21T09:06:25+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=9 orgId=1 uname=user1 error="Post https://api.telegram.org/bot${id is masked}/sendMessage: read tcp src:port->149.154.167.220:443: read: connection reset by peer"

Thanks

**Comment by marefr** [comment] 2019-11-21 10:43
Duplicate of #11962

**Closed by marefr** 2019-11-21 10:43 UTC
