### ISSUE TITLE
Alert email shows incorrect metric name when OR is used in alert graph

### ISSUE THREAD

**Issue by l0ckt1ght** [grafana/grafana#22076] opened 2020-02-10 16:53 UTC
**What happened**: 

Graph has multiple (2) queries and multiple (2) conditions exist with an OR on a graph
for the alert, the first condition references query A, then an OR condition references query B

When query b condition for alerting is met, email is sent out
Email that is sent out shows Query A tag with Query B value

**What you expected to happen**:

When query b condition for alerting is met, email is sent out
Email that is sent out should shows Query B tag with Query B value

**How to reproduce it (as minimally and precisely as possible)**:

using telegraf and ping metric, create a graph with two queries:
1) SELECT mean("maximum_response_ms") FROM "ping" WHERE ("url" = X.X.X.X) AND $timeFilter GROUP BY time($__interval), "url" fill(none)
2)SELECT mean("percent_packet_loss") FROM "ping" WHERE ("url" = X.X.X.X) AND $timeFilter GROUP BY time($__interval), "url" fill(none)

![image](https://user-images.githubusercontent.com/48327576/74170454-ee4aad00-4bfa-11ea-9897-ad386d285f2e.png)

Set alerting as follows:
![image](https://user-images.githubusercontent.com/48327576/74170504-01f61380-4bfb-11ea-8a5f-2f1df6fbef73.png)

Trigger packet loss (on linux, I used `iptables -I INPUT -s x.x.x.x -j DROP`)

Email sent out looks like this (note "Response" is the tag for query A):
![image](https://user-images.githubusercontent.com/48327576/74170705-5a2d1580-4bfb-11ea-979f-ebbf1b8bbbf1.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.6.1
- Data source type & version: influxdb 1.7.10-1
- OS Grafana is installed on: Ubuntu 18
- User OS & Browser: Windows/Linux Chrome
- Grafana plugins: 
- Others:

**Comment by sakjur** [comment] 2020-02-11 16:01
Tried this (with Prometheus), but it sent me an email correctly saying that the `B` value was triggering the alert.

**Comment by marefr** [comment] 2020-06-15 09:05
Closing this since we couldn't reproduce it.

**Closed by marefr** 2020-06-15 09:05 UTC
Labels: needs investigation
