### ISSUE TITLE
Alerting: email notification styles are broken for multiple alerts

### ISSUE THREAD

**Issue by nathanrodman** [grafana/grafana#44501] opened 2022-01-26 23:28 UTC
**What happened**:

Email styles for multiple alerts are broken and are really ugly. They are very unreadable. Both examples are for Gmail

![image](https://user-images.githubusercontent.com/3469390/151221122-5b0b48ff-c90a-4337-8194-6530043d231f.png)

![image](https://user-images.githubusercontent.com/3469390/151263550-856310bb-788c-4890-b01f-9386a6f413cc.png)

**What you expected to happen**:

Each alert should be readable.

**How to reproduce it (as minimally and precisely as possible)**:

Create an email contact point and add it to a notification policy and assign it to an existing firing rule with multiple instances. You should get an email with multiple alerts in it and should see the formatting issue.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment] 2022-01-27 06:58
duplicate of https://github.com/grafana/grafana/issues/44478

**Closed by peterholmberg** 2022-01-27 06:58 UTC
Labels: area/frontend, area/alerting/unified
