### ISSUE TITLE
Not possible to use variables in query calculations

### ISSUE THREAD

**Issue by soloam** [grafana/grafana#64527] opened 2023-03-09 14:49 UTC
**What happened**:

Since I updated to the new 9.4.3 some queries to influx stoped working, the problem is that grafana is giving a error when using a variable in the calculation. For example

This does not run, and $price_kwh has a value in the dashboard
```sql
SELECT sum("kwh") * $price_kwh as price FROM "storage"."power_h" WHERE ("device_type" =~ /^$device$/) AND ("invoice_year" =~ /^$invoice_year$/) AND ("invoice_month" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)
```

This works
```sql
SELECT sum("kwh") * 0.14 as price FROM "storage"."power_h" WHERE ("device_type" =~ /^$device$/) AND ("invoice_year" =~ /^$invoice_year$/) AND ("invoice_month" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)
```

This was working before the update

**What you expected to happen**:

Grafana to map my vars and do the calculations

**How to reproduce it (as minimally and precisely as possible)**:

Use this sql or somting similar:

```sql
SELECT sum("kwh") * $price_kwh as price FROM "storage"."power_h" WHERE ("device_type" =~ /^$device$/) AND ("invoice_year" =~ /^$invoice_year$/) AND ("invoice_month" =~ /^$invoice_month$/) AND $timeFilter AND tarif='peak' GROUP BY time(1d) fill(null)
```

**Anything else we need to know?**:

Don't know if relevant, but I'm doing a query to a influxdb database

**Environment**:
- Grafana version: 9.4.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: InfluxDB 1.8.10
- User OS & Browser: Debian 11

**Comment by Worty** [comment] 2023-03-10 11:13
Same as #63973

**Comment by tonypowa** [comment] 2023-03-13 10:33
@soloam 

thank you for creating this issue
 
could this be a browser cache related issue? ref: https://github.com/grafana/grafana/issues/63973#issuecomment-1464944307

anyway, it does seem like a duplicate so I am closing this one in favor of  https://github.com/grafana/grafana/issues/63973
You are welcome to add any new comments/findings in that issue, which is already assigned to an engineering team 👍

**Comment by tonypowa** [comment] 2023-03-13 10:35
/duplicate of https://github.com/grafana/grafana/issues/63973

**Closed** 2023-03-13 10:35 UTC
Labels: type/duplicate
