### ISSUE TITLE
Table Panel Header Bug Issue in Table Plugin

### ISSUE THREAD

**Issue by Jaeguki** [grafana/grafana#19760] opened 2019-10-11 07:09 UTC
**What happened**:
It happened in the grappa table panel.

Occurs when the table panel header is longer than the maximum representable length on the web screen.

Move the scroll left or right.

The table records shown move well along the scroll.

But the table header is fixed.

The table header shown does not move as you scroll.

**What you expected to happen**:
The table header shown when the scroll moves should move.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.2.4
- Data source type & version:
- OS Grafana is installed on: centos7.0
- User OS & Browser: Window10 & Chrome
- Grafana plugins: Table
- Others:

**Comment by torkelo** [comment] 2019-10-11 07:37
duplicate of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2019-10-11 07:37 UTC
