### ISSUE TITLE
Bars overlap

### ISSUE THREAD

**Issue by dimrozakis** [grafana/grafana#12417] opened 2018-06-26 19:51 UTC
### What Grafana version are you using?

v5.2.0-beta2 (latest docker image)

### What datasource are you using?

Prometheus
### What OS are you running grafana on?

Debian Linux, Docker

### What did you do?

Upgrade grafana to latest image and see one of my bar charts.

It's in stack mode with null as zero setting.

### What was the expected result?

Expected result, working properly with v5.1.4

![grafana1](https://user-images.githubusercontent.com/5428237/41935674-2ace9f02-7993-11e8-8612-4f80bef89611.png)

### What happened instead?

![grafana2](https://user-images.githubusercontent.com/5428237/41935681-332f0d6c-7993-11e8-9c79-1debe1d2133c.png)

I downgraded and rerupgraded multiple times, clearing the browser's cache in between. I managed to replicate the issue every time. It will display properly witth `5.1.4` docker image but not with `latest` image.

As a side note, I think it'd be safer to have the `latest` image point to the last stable (not alpha/beta) release.

**Comment by marefr** [comment] 2018-06-27 07:31
Please include your panel json and also tell what configuration of `Scrape interval` you have of your datasource for us to further investigate this.

Thanks for pointing out issue with `latest` image. That's a bug - created an issue https://github.com/grafana/grafana-docker/issues/173

**Comment by dimrozakis** [comment] 2018-06-27 10:19
Panel.json
```json
{
  "aliasColors": {},
  "bars": true,
  "dashLength": 10,
  "dashes": false,
  "datasource": "$ds",
  "decimals": null,
  "fill": 0,
  "gridPos": {
    "h": 7,
    "w": 8,
    "x": 8,
    "y": 14
  },
  "id": 50,
  "legend": {
    "alignAsTable": true,
    "avg": false,
    "current": false,
    "hideEmpty": true,
    "hideZero": true,
    "max": false,
    "min": false,
    "rightSide": true,
    "show": true,
    "sort": "total",
    "sortDesc": true,
    "total": true,
    "values": true
  },
  "lines": false,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "null as zero",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": true,
  "steppedLine": false,
  "targets": [
    {
      "expr": "myapp_request_logs{instance=\"$instance\"} - myapp_request_logs{instance=\"$instance\"} offset $__interval > 0",
      "format": "time_series",
      "interval": "",
      "intervalFactor": 10,
      "legendFormat": "{{view}} {{method}} {{code}}",
      "refId": "A"
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeShift": null,
  "title": "Request Logs",
  "tooltip": {
    "shared": true,
    "sort": 2,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "decimals": 0,
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": "0",
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}
```

The scrape interval configured in the datasource is 20 seconds.

**Comment by marefr** [comment] 2018-06-28 11:56
Have been trying to reproduce this but it works as expected for me. Would it be possible for you to use the query inspector and investigate what the response from prometheus are when the bars overlap. Thanks

**Comment by grobie** [comment] 2018-06-29 13:33
I can report a similar issue after upgrading to Grafana v5.2.1. We sometimes use bar charts to render error rates where some timeseries will disappear (e.g. due to a filter to show only time series with an error rate > 0 like `sum by(dependency) (rate(errors_total[1m])) > 0`).

It's worth to note that the render issue appears only at certain timings, the render results range from "everything looks normal like in 5.1" to "almost every bar is misplaced". See the following screenshots taken with 10 seconds apart from each other.

![screenshot from 2018-06-29 15-28-50](https://user-images.githubusercontent.com/3432/42094797-2f90d3fa-7bb1-11e8-8643-76aa67a7c653.png)
![screenshot from 2018-06-29 15-29-35](https://user-images.githubusercontent.com/3432/42094852-4dfabf68-7bb1-11e8-9c1a-c1b5d95ca2bf.png)
![screenshot from 2018-06-29 15-29-44](https://user-images.githubusercontent.com/3432/42094851-4dd9ace2-7bb1-11e8-8371-004e085686f9.png)

I suspect this issue to be the result of the new Prometheus step alignment handling introduced in #10434 @davkal

**Comment by dswarbrick** [comment] 2018-06-29 14:44
@grobie I think what you're experiencing is #12379

**Comment by grobie** [comment] 2018-06-29 14:47
Oh, right, I didn't read all issues open for the bar issue. I'd assume they're all related to the alignment changes.

**Comment by marefr** [comment] 2018-06-29 14:51
Closing this in favor of #12379

**Closed by marefr** 2018-06-29 14:51 UTC
Labels: datasource: Prometheus, state: needs more detail

**Comment by davkal** [comment] 2018-07-02 15:13
The above PR should fix this.

This was an interesting issue, since the bar width seemed to have changed mid-graph. This happens when `null` values are being filled in in an unaligned fashion. When doing the alignment logic, it wasnt on my radar that bar widths are being informed by the minimal step of the series.

**Comment by davkal** [comment] 2018-07-02 15:15
@dimrozakis would be great if you could confirm this as well. I was not able to reproduce this shifted bars issue, but I think it was a side effect of the above issue.
