### ISSUE TITLE
Table: Not able to display more than one column

### ISSUE THREAD

**Issue by valcryst** [grafana/grafana#26649] opened 2020-07-28 11:00 UTC
**What happened**:
Created a new Dashboard with a Table, to show multiple values
![image](https://user-images.githubusercontent.com/12711020/88656914-57eb4480-d0d1-11ea-8380-e2fde22d635d.png)

**What you expected to happen**:
I expected to see multiple columns with all the values or atleast an option to switch like before
![image](https://user-images.githubusercontent.com/12711020/88657055-94b73b80-d0d1-11ea-9077-6ef50952c4e7.png)
(this is an table created with Grafana 6.x)

**Reproduce**:
Create a new table with multiple fields to query.
Instead of multiple columns you will see only a dropdown (red circle)
![image](https://user-images.githubusercontent.com/12711020/88659245-0a70d680-d0d5-11ea-9340-d4eaefbd6cd8.png)

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: InfluxDB 1.8.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 Pro 2004 / Chrome 84.0.4147.105
- Grafana plugins: -
- Others: -

**Comment by valcryst** [comment] 2020-07-28 11:09
Edit: The last table in "expected" is actualy a plugin, but this is the original Grafana Table from 6.x with expected result.

![image](https://user-images.githubusercontent.com/12711020/88658342-8ff38700-d0d3-11ea-8049-ea829e6d3c10.png)

**Comment by aknuds1** [comment] 2020-07-28 11:15
Please include in the issue description also how to reproduce the problem you're seeing.

**Comment by valcryst** [comment] 2020-07-28 11:22
@aknuds1 Hi, is this ok, or is there anything more i could provide?

**Comment by aknuds1** [comment] 2020-07-28 15:01
Ah OK, I see what you mean now. I'm not aware of this change, but it looks as if only one query is shown at a time, and you must use the dropdown to choose the query to display. I don't think it's a bug, but I'll just double check with the front-end team.

**Comment by valcryst** [comment] 2020-07-28 15:33
@aknuds1 Thanks, yes thats what i mean.
If thats the new expected behaviour, how could we display a table like before and use data transform?
Or do we have to use external plugins for this now, because in our case this table plugin is now pretty much useless.

**Comment by torkelo** [comment] 2020-07-28 16:36
This is expected if your query format is set to time series.

You then have to use a merge or join transform to combine all time series into one table.

This is improved in flux queries I think as all fields are then automatically returned in one DataFrame (I think)

**Comment by mahadi** [comment] 2020-07-31 07:45
Unfortunately, if i am using flux queries, the "format as" table part is missing... Where has it gone?

**Comment by torkelo** [comment] 2020-07-31 18:30
If your return time series , just use a merge transform to combine them into one table

**Comment by mahadi** [comment] 2020-08-01 06:14
What i actually mean is the effect that if i use a table panel, only two columns are displayed (time and value). 
I am using a flux query with map `  |> map(fn: (r) => ({
      r with
      month: date.month(t: r._time)
  }))`.
But the month column is simply dropped and not displayed in grafana when i use the table panel.
In Chronograf i can see that the column is present in the query result.

Currently there is no option to switch to "Format as: Table" like in InfluxQL. Perhaps thats the reason?

**Comment by peterholmberg** [comment] 2020-08-20 09:40
@torkelo do you have an answer to the above?

**Comment by hugohaggmark** [comment] 2020-08-25 04:45
> What i actually mean is the effect that if i use a table panel, only two columns are displayed (time and value).
> I am using a flux query with map ` |> map(fn: (r) => ({ r with month: date.month(t: r._time) }))`.
> But the month column is simply dropped and not displayed in grafana when i use the table panel.
> In Chronograf i can see that the column is present in the query result.
> 
> Currently there is no option to switch to "Format as: Table" like in InfluxQL. Perhaps thats the reason?

@mahadi have you tried to add the merge transform or join? Let me know if you need help with that.

I will close this issue for now but we can always reopen it if new evidence point to an actual issue in Grafana.

All the best

**Closed by hugohaggmark** 2020-08-25 04:45 UTC
Labels: area/grafana/ui, area/panel/table
