### ISSUE TITLE
InfluxDB 0.10 series autocomplete in query editor limited

### ISSUE THREAD

**Issue by flyersa** [grafana/grafana#4278] opened 2016-03-07 18:00 UTC
Hi,

it seems that influxdb limited the "SHOW MEASURMENTS" command to only return a few thousand series. With this, autocomplete in the influxdb query editor is not working (also not in 3.0).

You can get around it by using WHERE to look for tags, but in some cases you cant do that because you have no such tags given how the data is inserted.

An easy solution would be that instead of "SHOW MEASURMENTS" that is fired when clicking in the "select measurment" field after from that the query with the regex is fired:

SHOW MEASUREMENTS WITH MEASUREMENT =~ /icinga.*/

as example, if i start typing "icinga" in the measurment field, it should try to get measurements matching to that.

**Comment by bergquist** [comment] 2016-03-08 14:28
@flyersa Thank you for reporting this. 
Linking this issue to the issue you created in the Influxdb repo https://github.com/influxdata/influxdb/issues/5927

**Comment by bergquist** [comment] 2016-03-08 14:39
I cannot reproduce this issue.
Running docker tutum/influxdb:0.10 and grafana master. 

"SHOW MEASUREMENTS" runs without problems in the influxdb admin tool.

**Comment by flyersa** [comment] 2016-03-09 09:39
Yes it runs without problems. but it does not return all measurements if you have alot of them. Anyway using SHOW MEASUREMENTS WITH MEASUREMENT =~ with the value of the input field will also greatly speed up autocompletion in the query editor instead of returning ALL measurements from the api.

As example we have ten thousands of measurements in an 0.10 cluster and the query in grafana and also in the influxdb cli only returns the first 10k or so. I also opened this as issue on influxdb.

As example in our usecase the icinga measurements are after the first 10.000, so if i start typing icinga in the query editor it is never shown becuase its not in the measurement list returned by influxdb, only if utilizing with the regex query.

**Comment by danielsand** [comment] 2016-03-09 09:42
@bergquist just as cross reference this is the open issue in GH influxdb https://github.com/influxdata/influxdb/issues/5635

SHOW MEASUREMENTS got capped in Influxdb 0.10

**Comment by flyersa** [comment] 2016-03-29 14:53
any progress here?

**Comment by torkelo** [comment] 2016-04-03 20:04
looks to be fixed in InfluxDB, https://github.com/influxdata/influxdb/issues/5635

**Comment by flyersa** [comment] 2016-04-04 16:49
Even if thats fixed on influxdb, that will cause another grafana issue if its really fixed. Why not just go with the regex autocomplete instead of pre-loading ALL measurements of which some users have a few hundred thousands. This will cause the complete browser to hang up as we had it in the past BEFORE influxdb added this cap.

**Comment by torkelo** [comment] 2016-04-04 16:54
@flyersa yea, I agree the autocomplete should make queries to InfluxDB as you type now that InfluxDB supports it

**Comment by flyersa** [comment] 2016-04-05 09:48
so can we reopen it? ;)

**Comment by sklevenz** [comment] 2016-04-19 11:42
I am supporting this, too. We have more than 10K series in Influx10. The query  SHOW MEASUREMENTS is limited to 9999 and auto completion in the query editor is very poor. After typing the first "/" there is no further result shown. 

The query editor of Influx8 doesn't show this effect with the same amount of data.

**Comment by torkelo** [comment] 2016-04-19 13:54
You can specify a where tag filter before you select the measurement.

10k measurements? No way to reduce by using tags?

**Comment by sklevenz** [comment] 2016-04-19 15:32
10k is a an issue, but there is a growing number of data sources in our use case. At least and apart of this issue we don't have yet a problem with scale :-/

But thanks for the tag hint. I will try that out.

**Comment by flyersa** [comment] 2016-05-17 15:08
3.0.2 and its stil doing SHOW MEASUREMENTS ... damn it

**Comment by torkelo** [comment] 2016-05-17 17:52
@flyersa yea, me neither, no PR yet :(

**Comment by flyersa** [comment] 2016-08-15 23:15
stil no update? :(  can at least maybe point me to the direction in the code, then i patch it myself?

**Closed** 2016-09-15 14:11 UTC
Labels: datasource: InfluxDB, P3: important, state: help wanted (PR)
