### ISSUE TITLE
Please add alert button for singlestat visualization

### ISSUE THREAD

**Issue by Nurlan199206** [grafana/grafana#18297] opened 2019-07-30 12:04 UTC
**What would you like to be added**:
You can make alert button for singlestat visualization too? i'm using grafana 6.1.6

**Why is this needed**:
ICMP checks: UP or DOWN remote PC or hardware.

![alert](https://user-images.githubusercontent.com/22808731/62127634-5c312600-b2f4-11e9-92cd-72022469b864.PNG)

**Comment by Nurlan199206** [comment] 2019-07-30 12:09
my checks looking like this:

![alert1](https://user-images.githubusercontent.com/22808731/62127983-3a846e80-b2f5-11e9-983c-195082f243b4.PNG)

**Comment by torkelo** [comment] 2019-07-30 12:48
dupe of https://github.com/grafana/grafana/issues/6983

**Closed by torkelo** 2019-07-30 12:48 UTC
