### ISSUE TITLE
Alert rules with CloudWatch metrics seems to evaluate both builder and code conditions

### ISSUE THREAD

**Issue by Fresa** [grafana/grafana#86426] opened 2024-04-17 11:38 UTC
### What happened?

We started to get No Data alerts yesterday on our alert rules using AWS CloudWatch Metrics. Something seems to be up with how these alert rules are evaluated, or that's my best guess after troubleshooting. 

When querying an alert condition like:
`SEARCH('MetricName="ApproximateNumberOfMessagesVisible" AND ("AWS/SQS") AND QueueName=my-queue-prefix NOT QueueName=dlq', 'Sum') ` using the Code editor the result is now no data. If I go to the explorer and query the exact same query, I get data. The datasource is the same, and so is the query period.
Going back to the alert condition and entering Builder editor, choosing any queue name as a dimension I get data. If I now go back to the Code editor (the query is still the same) and run the query, I now get data.

Saving this alert rule and waiting for the next evaluation period, the alert triggers with a no data alert. Going back into the alert again and running the query I do get data.

If I now go into builder mode, enter any queue name as a dimension (or remove all dimensions) go back to code editor mode and save the rule, wait for the next evaluation period, it now transitions into an error stating:
`invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}`
If I enter another metric in builder mode, enter code mode and hit save, and wait for the next evaluation it then transitions into an error state like:
`No error message provided`

Have builder and code mode started to interfere with each other during evaluation maybe?

### What did you expect to happen?

The code edited alert condition to evaluate

### Did this work before?

Yes

### How do we reproduce it?

1. Create an alert rule using AWS CloudWatch source provider and have some queues in active state in AWS (so it produces metrics). Use the search expression `SEARCH('MetricName="ApproximateNumberOfMessagesVisible" AND ("AWS/SQS") AND QueueName=my-queue-prefix NOT QueueName=dlq', 'Sum')` where `my-queue-prefix` partially match some queue names. Hit run queries.
2. Go to builder mode enter the equivalent query. In Dimensions add QueueName and *. Run the query, it should return data.
3. Go back to Code mode and hit run queries -> no data.
4. Go back to builder mode, remove the Dimension, and then go back to Code mode and run queries -> data!
5. Save the rule and wait for it evaluate -> it triggers an error state as described above.

### Environment (with versions)?

Grafana v11.1.0-69372 (51da96d94e)
OS: Windows 11
Browser: Chrome Version 123.0.6312.122 (Official Build) (64-bit)

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

AWS CloudWatch

**Comment by idastambuk** [comment] 2024-05-21 08:24
Hi @Fresa thanks for reporting this in such detail! 
We already have a ticket that describes a similar issue here:https://github.com/grafana/grafana/issues/87568. We've prioritized it so you can follow the progress there as well. 

I have a few questions to make sure your issue has the same cause as the bug I linked:
Does starting with a fresh query fix you alerts, or do they still break on the next evaluation attempt? 
It looks like there might also be an issue with the "Match exact" toggle - does turning it off in builder mode before switching to code prevent the errors from happening?

**Comment by Fresa** [comment] 2024-05-21 10:34
@idastambuk Thanks for your reply! I tried setting up an exact copy of the alert rule manually via code mode, and it also enters an error state with the same error message as the original one. Since I now set it up via code mode exclusively and never enter the builder, I'm not configuring/touching the match exact toggle.

**Comment by idastambuk** [comment] 2024-05-22 15:27
Hi @Fresa, I can't seem to reproduce the bug, this is what I tried (just focussing on code mode, since that alone also produced the bug):
1. Added a new alert rule
2. Selected Cloudwatch -> Metric Search -> code mode 
3. Added this query `SEARCH('MetricName="CPUUtilization" AND ("AWS/EC2") AND AutoScalingGroupName=partial-match NOT partial-match-not ', 'Average')`
4. Ran the query - got data
5. Saved the rule
6. Let the rule pass a few evaluations

I'm not getting any errors and health reports ok. Is this what you're doing as well? 
Is this your only Cloudwatch query in the alert rule?
Which error message exactly are you getting?

Thanks a lot for the help in debugging this!

**Comment by Fresa** [comment] 2024-05-22 15:47
We're using the query I mentioned in the first post: `SEARCH('MetricName="ApproximateNumberOfMessagesVisible" AND ("AWS/SQS") AND QueueName=my-queue-prefix NOT QueueName=dlq', 'Sum')`

Seems similar to what you have tried, interesting.

The error we get is `invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}`

**Comment by kevinwcyu** [comment] 2024-05-31 18:41
Investigation notes:

It looks like there are two separate issues here

1. Repro steps 1-4 should be addressed by https://github.com/grafana/grafana/issues/87568.
2. Repro step 5, I was able to reproduce this without doing steps 1-4. It initially has an error with the message `invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}`. Subsequent errors I got were `No error message provided`, but these happened after a couple of hours.

The query I used was:

```
SEARCH('MetricName="ResourceCount" AND ("AWS/Usage") AND Resource=TargetsPer NOT QueueName=TargetsPerNetworkLoadBalancer', 'Average')
```

I left the rest of the alert settings at their defaults.

**Comment by iwysiu** [comment] 2024-06-07 16:03
Hi @Fresa ! Do you remember what labels you were getting on your working alert queries/what version the queries were last working on? I was investigating this and I think the issue is that queries made with the code editor are not labeled. If the labels were just `Series:<timeseries name>` then it's a pretty quick fix, otherwise it will be a little more involved.

**Comment by Fresa** [comment] 2024-06-07 16:48
@iwysiu `Label` for the alert is set to `${PROP('Dim.QueueName')}` (seems to be the same as default). I'm not sure what you refer to with 

> what labels you were getting

Looking at the query response with the Query inspector in the explorer, the json path `$[0:].schema.fields[?("name"=="Value")].labels` always seems to be an empty object, if that's what you are referring to?

The Reduce expression shows something like
```
Series 1    0
Series 2    0
...
Series 20   0
```
I don't know what it returned when it was working unfortunately.

**Comment by Fresa** [comment] 2024-06-07 17:00
Looking at the response from a similar query defined with the builder and selecting a `QueueName` as `Dimensions`, it seems the `labels` property is returned containing that dimension

**Comment by iwysiu** [comment] 2024-06-07 17:23
@Fresa thanks for answering! In that case, I'll put up a pr with the quick fix for now to get the code queries working, and then if we need other improvements we can look at them then.

**Closed** 2024-06-07 21:37 UTC
Labels: datasource/CloudWatch
