### ISSUE TITLE
Loki query editor does not work with dead keys / international keyboard layout

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#43177] opened 2021-12-15 20:29 UTC
**What happened**:

Loki query editor is unusable with US international keyboard layout (and likely any layout with dead keys). As soon as you try to type a double quote, i.e. " followed by SPACE, things get messed up.

https://user-images.githubusercontent.com/1764725/146258200-def64322-9db9-4853-8439-3da636b9121c.mp4

https://user-images.githubusercontent.com/1764725/146258545-28409405-bc86-4a96-b279-006d4e323b6d.mp4

This happens both in the label selector part and in the filtering part. I thought that the label selector part would have been fixed by https://github.com/grafana/grafana/pull/33545 but it doesn't seem to be (:wave: @zoltanbedi @ivanahuckova)

**What you expected to happen**:

Being able to use US international keyboard layout.

**How to reproduce it (as minimally and precisely as possible)**:

 - Use US international keyboard layout
 - Enter `{stream="stderr"}`in the query editor
 - Observe that what is displayed is not what you typed and there is no way to edit the query anymore
 
**Anything else we need to know?**:

This issue has been going on for months, if not years. Having to switch between keyboard layout is annoying, even more during troubleshooting and incident management.

Several issues have been filled in the past but Loki editor never really get fixed. References:

 * https://github.com/grafana/grafana/issues/34378
 * https://github.com/grafana/grafana/issues/32500
 * https://github.com/grafana/grafana/issues/29080
 * And more.

Same issue was fixed for Prometheus query editor in 8.3.0. 

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: Loki
- User OS & Browser: Firefox 94.0

**Comment by Elfo404** [comment] 2021-12-16 11:29
hi @cykl! thanks for reporting this (it's always nice to get such well detailed issues, so double thanks! )

Probably duplicate of https://github.com/grafana/grafana/issues/42910 which should be as well about dead keys.

I'm going to close https://github.com/grafana/grafana/issues/42910 as this one has much more details.

As you mentioned, we recently solved these kinds of issues for Prometheus by switching to Monaco editor, we should probably consider doing the same for Loki.

**Comment by aocenas** [comment] 2022-01-13 15:42
So I think the best thing to do here is to also move Loki to the Monaco editor (similar we did for prometheus) instead of fixing this directly in Slate. We don't have it on roadmap but should add it soon.

**Comment by cykl** [comment] 2022-01-14 09:25
> So I think the best thing to do here is to also move Loki to the Monaco editor (similar we did for prometheus) instead of fixing this directly in Slate. We don't have it on roadmap but should add it soon.

That sounds fine :+1: 

If you start working on Monaco editor rewrite, then please be aware the new Prometheus editor still has some issues with dead keys. The first example that springs to mind is `{key=~"value"}`, the ~ then " sequence almost always ends  up with garbage character that must be fixed. Would be great if that could be fixed too.

**Comment by aocenas** [comment] 2022-01-14 14:25
@cykl can you file an issue for that? Or is there already existing issue?

**Comment by gabor** [comment] 2022-02-10 10:01
as this will be fixed with the loki monaco migration ( https://github.com/grafana/grafana/issues/44985 ), i'm closing the issue for now.

**Closed by gabor** 2022-02-10 10:01 UTC
Labels: type/bug, prio/medium, datasource/Loki, area/frontend/code-editor
