### ISSUE TITLE
Always loading while edit table panel

### ISSUE THREAD

**Issue by chengyanQtl** [grafana/grafana#19332] opened 2019-09-24 01:39 UTC
**What happened**: The loading circle at the upper right corner of the table panel never stop running even the data has been loaded while edit table panel. It will raise an exception message(*Canceled: Query Changed while running*) if refresh the browser at this time.

**What you expected to happen**: The circle should stop running after the data has been loaded.

**How to reproduce it (as minimally and precisely as possible)**: It could reproduce in any kind of OS or Browser for grafana 6.3.2. It could be found at the following URL. https://play.grafana.org/d/000000031/table-panel-showcase?orgId=1&fullscreen&edit&panelId=6

**Anything else we need to know?**: Nothing

**Environment**:
- Grafana version: 6.3.2
- Data source type & version: Elasticsearch 6.5
- OS Grafana is installed on: Centos 6
- User OS & Browser: Ubuntu 18 & Firefox 69.0
- Grafana plugins: Meta Query, Pie Chart
- Others: None

**Comment by marcusolsson** [comment] 2019-09-24 11:39
Duplicate of #18411

**Closed** 2019-09-24 11:41 UTC
Labels: type/duplicate
