### ISSUE TITLE
Threshold calculation on hidden columns

### ISSUE THREAD

**Issue by diamondo25** [grafana/grafana#18040] opened 2019-07-10 15:16 UTC
**What would you like to be added**:
I'd like to see a feature for changing the row color based on a hidden column.

**Why is this needed**:
Tables can be full of numbers, but if your source of data has for example an enum or text field, you cannot put any threshold on it ('error' < 0 will not work). In order to work around this limitation, I'd like to provide an additional column in the output, then hide this column, and then put a threshold on it.

Lets say i've got the following query:
```
-- status is an ENUM('GOOD', 'BAD')
SELECT group, status, COUNT(*) FROM collection GROUP BY 1, 2
```

The output will be, for example:
```
group | status | COUNT(*)
1     | GOOD   | 12
1     | BAD    | 3
2     | GOOD   | 33
```

Now, the status itself doesn't really matter, I just want to highlight the row for when the BAD field pops up. There is currently no way to do that, other than to map either `status` to an int in a separate column and then show the status there and do a threshold, eg:
```
group | status | COUNT(*) | is_bad 
1     | GOOD   | 12       | 0
1     | BAD    | 3        | 1
2     | GOOD   | 33       | 0
```

This is not really ideal, as we are cluttering the UI...

My suggestion is to keep the threshold UI shown even though you selected the 'Hidden' type.

**Comment by syedsfayaz** [comment] 2019-08-05 17:50
I have similar requirement. I want to change the color of a row based on a hidden column status. It will be a duplicating if we show the status and change the color of the table. 

Attached issue for details. 
https://community.grafana.com/t/hide-table-column-but-keep-the-rules/19918

**Comment by fabiocosta0305** [comment] 2019-08-22 15:02
This is a feature I want too, also

**Comment by mazamsezer** [comment] 2020-09-17 12:02
Count me in too.

**Comment by pari205** [comment] 2021-02-02 06:56
Count me in too. This is required.

**Comment by baldm0mma** [comment] 2023-04-14 14:33
This seems to be a dupe of #8017; going to close this ticket.

**Closed by baldm0mma** 2023-04-14 14:33 UTC
Labels: type/feature-request, area/panel/table
