### ISSUE TITLE
Cloudwatch: reconsider the way sessions are cached

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#28142] opened 2020-10-09 13:41 UTC
**What happened**:
Following discussions #25548 session caching as we handle it now has [some implications](https://github.com/grafana/grafana/pull/25548#issuecomment-706067454).
Currently we cache a session upon successful credentials retrieval but it's not guaranteed
that these credentials are valid.
We have to cache them after the API has been successfully queried.

Another [suggested approach](https://github.com/grafana/grafana/pull/25556) is to use the datasource versioning.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vickyyyyyyy** [comment] 2021-07-09 13:50
Duplicate of https://github.com/grafana/grafana/issues/30977

**Comment by sunker** [comment] 2021-11-19 14:45
I think this was mainly a problem before we had the session store in grafana-aws-sdk. Then, we were using non-sufficient cache key which wouldn't allow the user to create new sessions because the previous one was always returned. 

This problem can still occur, but we haven't had any issues reported related to this in the last year. Since there's no easy way of solving this, it's not something we'll work with anytime soon. For that reason, I'll close this issue now. Feel free to re-open it if you want to.

**Closed by sunker** 2021-11-19 14:45 UTC
Labels: type/bug, datasource/CloudWatch, area/backend, needs investigation
