### ISSUE TITLE
Custom Decimal Value seems to be broken Grafana 6.1 Singlestat

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#16422] opened 2019-04-06 00:10 UTC
I have for my singlestat   specified decimal=1 yet I still see 3 digits 

![image](https://user-images.githubusercontent.com/3651746/55662087-8eb39200-57de-11e9-8e90-6edaca7a62cf.png)

![image](https://user-images.githubusercontent.com/3651746/55662093-9ecb7180-57de-11e9-9e4b-16a23ea62095.png)

The issue looks to be type specific. If I chose to display just raw value It respects decimal value

![image](https://user-images.githubusercontent.com/3651746/55662113-cde1e300-57de-11e9-97ec-4af2ab5745a8.png)

**Comment by RedJohn14** [comment] 2019-04-06 12:52
Hello,

I have the same issue, see also my issue:

https://github.com/grafana/grafana/issues/16423

Thanks for report!

Regards

**Comment by torkelo** [comment] 2019-04-07 12:40
dupe of https://github.com/grafana/grafana/issues/16373, 
PR with fix was opened 2 days ago, https://github.com/grafana/grafana/pull/16413 

will be fixed in 6.1.2

**Closed by torkelo** 2019-04-07 12:40 UTC
