### ISSUE TITLE
Timestamp fields in variables returned as epoch 

### ISSUE THREAD

**Issue by n4ch04** [grafana/grafana#52195] opened 2022-07-14 06:11 UTC
**What happened**:
Using grafana 9.0.2 connected to a Postgres datasource if you declare a variable that includes data of type timestamp, the values returned are in epoch format, when the original ones are in iso8601 format. It happens only on the variables queries, since from the explorer and in panels the values returned are the original ones.

<img width="155" alt="image" src="https://user-images.githubusercontent.com/59198746/178911609-23ea6925-3209-4020-a43e-da61af8c05dc.png">

<img width="1067" alt="Screenshot 2022-07-14 at 07 55 45" src="https://user-images.githubusercontent.com/59198746/178912712-38d6e8ad-c10a-4529-be79-37d2b425d692.png">

<img width="1195" alt="Screenshot 2022-07-14 at 07 53 09" src="https://user-images.githubusercontent.com/59198746/178912765-6a9484a8-f157-4dd9-ae9c-074ec1caf7cc.png">

**What you expected to happen**:

In variables definition the values returned should be in the same format as the original in database, as happens in panels and explorer

**How to reproduce it (as minimally and precisely as possible)**:

- Create grafana and postgres containers with grafana postgres datasource configured.
- Create a table in postgres database with a column storing timestamp data
- Query that table from grafana in a variable definition, from the explorer feature and from a panel

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version:  Postgresql latest
- OS Grafana is installed on: macOS Monterey 12.2.1 arm64
- User OS & Browser: macOS Monterey 12.2.1 - Google Chrome Version 103.0.5060.114 (Official Build) (arm64)
- Grafana plugins: None
- Others:

**Comment by mellieA** [comment] 2022-07-21 13:22
This looks related to https://github.com/grafana/grafana/issues/36404, I'll let the squad confirm if this is a duplicate 

There's a suggested short-term workaround there to:

> The suggested short-term workaround would be for you to convert your time column into a string using something like SELECT to_char(<time column>, 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"');

**Comment by zoltanbedi** [comment] 2022-07-21 13:28
I think we can close this one and we will track the other issue that @mellieA linked above. Thank you.

**Closed by zoltanbedi** 2022-07-21 13:28 UTC
Labels: type/bug, area/dashboard/templating, datasource/Postgres

**Comment by n4ch04** [comment] 2022-07-22 06:31
I've tried to cast the epoch values to timestamp with `to_timestamp` and it is retrieving incorrect values
I do not understand the need to include this  cast https://github.com/grafana/grafana/blob/main/pkg/tsdb/sqleng/sql_engine.go#L300 when grafana is handling well the timestamp everywhere 
You are saying that to use grafana with timestamp fields into variables you need to cast it as string (which is really inefficient ) or change the database model??? Really??

**Comment by mellieA** [comment] 2022-07-22 14:03
@n4ch04 we closed this issue because it is a duplicate of https://github.com/grafana/grafana/issues/36404. Please feel free to continue the conversation there. The proposed workaround is meant to be a short-term solution until the issue is fixed.
