### ISSUE TITLE
Prometheus: "TypeError is null" when editing dashboards with Firefox

### ISSUE THREAD

**Issue by duncanawoods** [grafana/grafana#28914] opened 2020-11-08 14:02 UTC
**What happened**:

When using Firefox to edit a prometheus query on any multi-query panel, if you select text e.g. copy/paste or to overwrite, when you change focus to another query, it causes the editor to crash with `An unexpected error happened, TypeError: e is null`. This does not happen with chrome

![out](https://user-images.githubusercontent.com/2480457/98466982-c65c9a00-21ca-11eb-9f04-f258a6f30499.gif)

**How to reproduce it (as minimally and precisely as possible)**:

1. create a new dashboard
2. edit the default panel
3. connect datasource to prometheus
4. add a query and paste in a metric name
5. add another query and paste the metric name again
6. click back on the first query text
7. <query editor crashes, dashboard is now broken and must be reloaded>

**Anything else we need to know?**:

- Sometimes the query text disappears so maybe related to #28571
- If there is a error/warning message then it only flashes up for a spit second and the ui does some janky relayout

**Environment**:
- Grafana version:  v7.3.1
- Data source type & version: prometheus 2.20.1
- OS Grafana is installed on: Ubuntu 18.04 server
- User OS & Browser: Ubuntu 18.04, Firefox 82.0.2

**Comment by papagian** [comment] 2020-11-09 19:28
I'm unable to reproduce it in master (commit: a7ea8de47e) and in 7.3.1 using Firefox in Mac OS X

**Comment by zoltanbedi** [comment] 2020-11-09 20:26
This is still https://github.com/grafana/grafana/issues/28571 and a fix is going to be released in 7.3.2

**Closed by zoltanbedi** 2020-11-09 20:26 UTC
Labels: datasource/Prometheus, needs investigation
