### ISSUE TITLE
Variable is displayed inconsistently in the title and content of a Text panel

### ISSUE THREAD

**Issue by lingyufei** [grafana/grafana#80523] opened 2024-01-15 06:10 UTC
### What happened?

The label of a variable would be displayed in the title, but the value of a variable would be displayed in the text.

I created a variable named 'a' with the options: "a : 1,b : 2"
<img width="310" alt="image" src="https://github.com/grafana/grafana/assets/49775184/ede9d372-297a-4e47-8b4a-d4cfbffe1640">

When I use it in the Text panel. The label 'a' is displayed in the title, but the value '1' is displayed in the context.
<img width="1205" alt="image" src="https://github.com/grafana/grafana/assets/49775184/c3ddc812-341f-4c7f-900e-920ef2f98852">
 

### What did you expect to happen?

**The display value should always be the same (label or value). Or we can support the feature that can display the label or value of a variable based on the configuration like ${a.label}, ${a.value}.**

### Did this work before?

no

### How do we reproduce it?

1. Add a variable with the options: "a : 1,b : 2"
2. Reference it in the title and content of a text panel

### Environment (with versions)?

Grafana: 10.2.2
OS: MacOS
Browser: Chrome

### Grafana platform?

Docker

**Comment by tonypowa** [comment] 2024-02-09 13:05
thank you for reporting this bug @lingyufei  !

the issue will be sent to the team for review

I am adding a screenshot with the variable details for clearer repro steps

![image](https://github.com/grafana/grafana/assets/45235678/cc53ad85-aac7-42d8-8a40-ee39f2053db2)

**Comment by ivanortegaalba** [comment] 2024-03-25 19:19
Hi @lingyufei, thank you for the feedback, very much appreciated it :) 

This is an intended behavior.
When you're using a variable in the title or description of the panel, very likely you want to mention the variable you're using and why.
Instead, when you're using the variable in the visualization itself you want the values: to compose a query or to display the list of something.

There are options to force the variable to display as text or value:
- `${var:text}` always display the label
- `${var:raw}` always display the variable value

You can see more about how to format a variable [here](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/)

This feature request has been open for a long time with few received upvotes and it also has a workaround, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!

**Closed by ivanortegaalba** 2024-03-25 19:19 UTC
Labels: type/bug, area/dashboard/templating, area/dashboard, needs refinement, team/grafana-dashboards
