### ISSUE TITLE
Bar Gauge data link bug

### ISSUE THREAD

**Issue by gretamosa** [grafana/grafana#19967] opened 2019-10-23 09:40 UTC
**What happened**: In Bar Gauge panel, lost focus in title input text (data links)

**What you expected to happen**: Edit title input text every time you want

**How to reproduce it (as minimally and precisely as possible)**: I've reproduce in play.grafana.org in Bar Gauge dashboard. Add datalink > focus on title (no edit) > focus on url > you never go back to title input.

**Anything else we need to know?**: I think not but you can ask me :)

**Environment**:
- Grafana version: 6.4.3 (3a2bfb7)
- Data source type & version: Grafana Test Data
- OS Grafana is installed on: You know better than me :)

**Comment by torkelo** [comment] 2019-10-23 09:46
duplicate of https://github.com/grafana/grafana/issues/19868 

We have a PR open and will be included in next patch

**Closed by torkelo** 2019-10-23 09:46 UTC
