### ISSUE TITLE
AdHoc Filters - Elasticsearch cross cluster datasources failing to remove filters

### ISSUE THREAD

**Issue by joedugdale** [grafana/grafana#90634] opened 2024-07-18 21:30 UTC
### What happened?

When datasources are defined using cross cluster search syntax (eg *:dev-index,dev-index) we can no longer remove or adjust adhoc filters by selecting the field.

Elasticsearch doesn't provide the _mapping method under cross cluster search, and this seems to be the cause of the error, however this was previously working for us before we updated to Elasticsearch v8.

Adding a filter is ok. Browser dev tools shows it's failing on the _mapping method on both grafana 8 and 11.
![image](https://github.com/user-attachments/assets/92d9416d-132a-401b-9a4e-6ef5c9b66fa3)

Can Grafana make adhoc filters cross cluster search compatible?

The same error is shown on datasource save
![image](https://github.com/user-attachments/assets/4026dfc2-df25-4f41-823c-eb66d3b2f45b)

**Grafana 8.3.4**

Cross-cluster calls are not supported in this context but remote indices were requested: [*:index1]"

**Grafana 11**
{
    "message": "An error occurred within the plugin",
    "messageId": "plugin.downstreamError",
    "statusCode": 500,
    "traceID": ""
}

### What did you expect to happen?

options for remove filter, other values shown and no errors

### Did this work before?

when all backends were Elasticsearch v7, yes this did work

### How do we reproduce it?

1. create a datasource using cross cluster serach syntax for index name eg *:test-all,test-all
2. add an ad hoc filter to a dashboard with this datasource selected
3. try to remove the filter

### Environment (with versions)?

Grafana: 8.3.4 and 11.1
OS: Windows 10
Browser: Chrome Version 126.0.6478.128

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Elasticsearch 8x

**Comment by iwysiu** [comment] 2024-08-19 19:28
Hi @joedugdale ! This looks like a duplicate of https://github.com/grafana/grafana/issues/72353 (which is about supporting cross cluster search) so I'm going to close this issue, but the team is actually going to discuss ElasticSearch feature requests this week to see what want to prioritize, and I'll make sure to bring this one up.

**Closed by iwysiu** 2024-08-19 19:28 UTC
Labels: datasource/Elasticsearch
