### ISSUE TITLE
Datasource Provisioning on updateInterval

### ISSUE THREAD

**Issue by lswith** [grafana/grafana#13145] opened 2018-09-05 04:08 UTC
### What Grafana version are you using?
Grafana v.5.3.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
Linux

### Feature

Datasources are only provisioned on startup. This makes them vastly different to provisioning dashboards as they have an `updateInterval`. 

It would be very helpful to be able to provision a datasource after startup.

**Comment by torkelo** [comment] 2018-09-05 07:54
duplicate of https://github.com/grafana/grafana/issues/12878

**Closed by torkelo** 2018-09-05 07:54 UTC
