### ISSUE TITLE
Grafana DRILLDOWN / Search

### ISSUE THREAD

**Issue by drix1994** [grafana/grafana#10850] opened 2018-02-09 09:01 UTC
Please include this information:
- What Grafana version are you using?
Grafana v5.0.0-beta1 (commit: 3e2da1f)
- What datasource are you using?
MySQL
- What OS are you running grafana on?
RedHat 7.2
- What did you do?
I did dashboard with some graphs and i want to use drilldown.
- What was the expected result?
It's possible to drilldown to next dashboard after click on value on the chart? Its mean: for example I want to click on value on OY, OX (datetime) and go to next dashboard with the datetime after click? 
I dont want to push params the same as upper chart. I want to see narrowed down chart.

Question 2. Could you make search which will check words also inside dashboard which have some rows with names?

Thanks and grettings

**Comment by torkelo** [comment] 2018-02-09 09:56
duplicate of https://github.com/grafana/grafana/issues/1232

**Closed by torkelo** 2018-02-09 09:56 UTC
