### ISSUE TITLE
Variables: Constant variables should not become part of URL query parameters

### ISSUE THREAD

**Issue by letmaik** [grafana/grafana#82682] opened 2024-02-15 17:29 UTC
### What happened?

When creating one custom variable that is exposed to the UI to switch between values, and another hidden constant variable, then the constant variable also becomes part of the URL when switching between values of the custom variable. This means that it is not guaranteed that the dashboard is always using the current value of the hidden constant variable when links are shared that include URL query parameters.

### What did you expect to happen?

All hidden variables should never become part of URLs.

### Did this work before?

No.

### How do we reproduce it?

1. Create a variable of type "Custom" with two values 1 and 2.
2. Create a variable of type "Constant" with value "foo"
3. Save the dashboard
4. Switch the value for the custom variable
5. Observe that the URL now contains the hidden variable as well

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.2.1
OS: Linux
Browser: Edge

### Grafana platform?

Other

**Comment by tonypowa** [comment] 2024-03-14 10:32
hi @letmaik 

thank you for creating this issue

i tested and reproduced the behaviour (the constant variable is passed to the URL when changing the custom variable (in my case named 'numbers')

![image](https://github.com/grafana/grafana/assets/45235678/747e21be-8f5e-4e19-828f-a65a47e9e149)

adding issue to squads' board for review

**Comment by aaronzink** [comment] 2024-03-14 17:27
This is a problem when creating dashboards for large teams. 

When users bookmark a URL with the variable values they need for their individual use case the ULR also contains var-constant=foo. Then when I deploy an improved dashboard with where I have updated Constant to have value bar users complain when they open the dashboard it seems broken because it is still showing foo. 

This means the name of the hidden constant variable needs to be updated every time the constant value is changed in case a user has bookmarked a value for the old name

**Comment by letmaik** [comment] 2024-04-12 15:51
@natellium Will this be fixed in the non-scenes variant? This is one of the biggest pain points we have right now.

**Comment by letmaik** [comment] 2024-04-25 16:26
@torkelo This is pretty important for us. Could you guide me to the right place in the code so that I can attempt to implement it myself assuming it's not being prioritized?

**Comment by torkelo** [comment] 2024-05-15 13:41
this looks fixed in the new scenes variables implementation (G11 & feature toggle dashboardScene=true)

**Closed by torkelo** 2024-05-15 13:41 UTC
Labels: type/bug, area/dashboard/templating, team/grafana-dashboards

**Comment by letmaik** [comment] 2024-05-15 17:27
> this looks fixed in the new scenes variables implementation (G11 & feature toggle dashboardScene=true)

I'm using Managed Grafana in Azure which is still on 10 and also doesn't expose feature toggles, probably for reliability reasons. 

`dashboardScene` is listed under "Experimental feature toggles" in https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/. I'm assuming it will take quite a while until it transitions to Public Preview and eventually GA. No chance this can be backported to the non-scenes variant?

**Comment by nckswt** [comment] 2024-07-18 22:18
> since constant variables always had URL sync removing it might actually cause issues, so backporting this behavior change does not feel right

@torkelo your prediction of future issues was accurate :sweat_smile:: https://github.com/grafana/grafana/issues/90635
