### ISSUE TITLE
build query in 'explore' tab not working 

### ISSUE THREAD

**Issue by yoramshai** [grafana/grafana#17244] opened 2019-05-23 05:32 UTC
when clicking on one of the cells in the table in the "explore" tab, the query does not update accordingly   

I expected that the query will be updated with the value I just click on.
can be reproduced by run some query in "explore" and hit one of the values in the table

Grafana version:  6.2.0
data source: any
 os: ubuntu

**Comment by torkelo** [comment] 2019-05-23 09:05
Looks like our fix for this was not cherry picked for the release as it was opened just minutes after our cherry pick automation was run. 

https://github.com/grafana/grafana/pull/17083

We wil fix this in v6.2.1

**Comment by torkelo** [comment] 2019-05-23 09:06
dupe of https://github.com/grafana/grafana/issues/17071

**Closed by torkelo** 2019-05-23 09:06 UTC
