### ISSUE TITLE
Support for transformations on repeated panels

### ISSUE THREAD

**Issue by amrmahdi** [grafana/grafana#32081] opened 2021-03-17 18:14 UTC
**What would you like to be added**:
I have a row with 2 stat panels A, and B. B is using panel A as source with additional transformation (simple multiplication).
That works great with a fixed row. Now I want the row to be repeated based on the number of days in the query. Once I convert to a repeated row, panel A in rows work as expected, while panel B is the same for all since the reference is fixed and does not change when the repeat is set.

**Why is this needed**:
This is needed to avoid re-running queries that we have results for already, this is especially expensive for repeated panels, where the query will need to be executed per transformation per repetition. 

 An example dashboard that illustrates the issues is attached. 
[repeated-transformations.json.txt](https://github.com/grafana/grafana/files/6158656/repeated-transformations.json.txt)

Screenshot:
![image](https://user-images.githubusercontent.com/1451116/111517056-e28cbc80-8711-11eb-89e9-c19f8c578634.png)

I believe this is not supported today, if it is, please point me to docs on how to do it. 

Version: Grafana v7.4.3 (010f20c1c8)

**Comment by torkelo** [comment] 2021-03-18 07:42
duplicate of https://github.com/grafana/grafana/issues/29471

**Closed by torkelo** 2021-03-18 07:42 UTC
