### ISSUE TITLE
Prometheus: Stacked data sometimes render at wrong X axis point

### ISSUE THREAD

**Issue by atombender** [grafana/grafana#3513] opened 2015-12-14 19:46 UTC
Here's a screenshot:

![screen shot 2015-12-14 at 14 45 29](https://cloud.githubusercontent.com/assets/50314/11791892/6052f82c-a271-11e5-99d8-b1e63f22960f.png)

Notice how the crosshairs are at different locations within the same graph. It seems to be drawing data at wrong locations. If I disabling stacking, it works fine:

![screen shot 2015-12-14 at 14 44 21](https://cloud.githubusercontent.com/assets/50314/11791893/6061cf5a-a271-11e5-9063-b2abcbaaddc9.png)

JSON:

```
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "decimals": 2,
          "editable": true,
          "error": false,
          "fill": 10,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)",
            "thresholdLine": false
          },
          "id": 2,
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": true,
            "max": false,
            "min": false,
            "show": false,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 0,
          "links": [],
          "nullPointMode": "null",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": true,
          "steppedLine": true,
          "targets": [
            {
              "calculatedInterval": "1m",
              "datasourceErrors": {},
              "errors": {},
              "expr": "sort_desc(node_load1{environment=\"$environment\"})",
              "interval": "30s",
              "intervalFactor": 2,
              "legendFormat": "{{instance}}",
              "metric": "",
              "prometheusLink": "https://prometheus/graph#%5B%7B%22expr%22%3A%22sort_desc(node_load1%7Benvironment%3D%5C%22%24environment%5C%22%7D)%22%2C%22range_input%22%3A%2221600s%22%2C%22end_input%22%3A%222015-12-13%2022%3A53%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Load Average",
          "tooltip": {
            "shared": true,
            "value_type": "individual"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "short",
            "short"
          ]
        }
```

[Here](https://gist.github.com/atombender/cbce87dd6d96f0322dc9) is the data from the Prometheus query (host names have been censored).

Grafana 2.5.0, Prometheus 0.15.1.

**Comment by mtanda** [comment] 2015-12-15 10:37
@atombender Thanks for reporting! I'll check it later.

**Comment by mtanda** [comment] 2015-12-17 04:55
I success to replicate the issue by the data you provided.
I suspect this PR could broke something, https://github.com/grafana/grafana/pull/3284.
So I revert it in local env, but the issue isn't solved.

The related code might be this part, but I don't know well about it, so I don't have any idea what is wrong...
https://github.com/grafana/grafana/blob/3693473f4082f0c627898d673ce52df5a193ffd6/public/app/plugins/panels/graph/graph.tooltip.js#L76-L85

**Comment by mtanda** [comment] 2015-12-17 04:56
@torkelo Do you have any idea about this?

**Comment by atombender** [comment] 2015-12-17 05:02
Just to clarify (in case it's not obvious), it's not just the hover that's wrong. The hover position seems correct, relative to where the data is placed on the X axis. The problem is that the data is drawn at the wrong X positions.

**Comment by torkelo** [comment] 2015-12-17 07:59
if you stack series, all series must have data points for each time point, and the value cannot be null.

**Comment by atombender** [comment] 2015-12-17 14:13
Looks like Prometheus' API doesn't backfill data. It excludes data points where there is no Y value. However, it does provide all the necessary X values.

**Comment by mtanda** [comment] 2015-12-18 05:21
This comment maybe related https://github.com/grafana/grafana/issues/2912#issuecomment-159972504.
Prometheus datasource plugin can fill missing data point, but I'm not sure the approach is good.

**Comment by mtanda** [comment] 2015-12-18 05:30
@grobie I want to hear your opinion about this.
Is there possibility that Prometheus support backfill?

**Comment by grobie** [comment] 2015-12-19 14:27
@atombender @mtanda Can you clarify what you mean with backfilling in this context? I understand the situation that there are no samples available at some points of time. What do you expect the Prometheus API to do in such cases?

**Comment by atombender** [comment] 2015-12-19 14:41
@grobie By backfill I mean that it only provides samples for points in time where it has data. It doesn't return any null samples; the range of time labels is not contiguous. As far as I'm concerned, that's entirely correct. The problem here is that Grafana seems to mismanage the time values when it's stacking.

**Comment by torkelo** [comment] 2015-12-19 16:04
Yes :( but in Grafana's defense all other time series has been able to report null in time buckets where there is no value.

**Comment by atombender** [comment] 2015-12-20 00:25
@toerklo: Just in case it's not clear, this is a regression. My graphs were quite happy before; now they are not. I was using [grafana-plugins](https://github.com/grafana/grafana-plugins) with 2.0.2 before I upgraded to 2.5.

The fact that it happens only for some graphs is also worth considering. I also see a similar X-value problem affecting single-metric panels, might be the same issue:

![screen shot 2015-12-19 at 19 18 58](https://cloud.githubusercontent.com/assets/50314/11915802/8570716c-a685-11e5-8646-9b07edeb2548.png)

This particular panel is doing a `sum(rate(something{}[5m]) + rate(somethingelse{}[5m]))`. It has no null data. Of course, it could be something else.

I'm on Prometheus 0.15.1, in case it's relevant.

**Comment by torkelo** [comment] 2015-12-20 08:28
Try setting null point mode to zero.

**Comment by atombender** [comment] 2015-12-20 21:18
@torkelo: Doesn't change anything.

By the way, never mind what I wrote about single-metric panels. I accidentally set the time range to "today".

**Comment by mtanda** [comment] 2016-01-19 11:11
https://github.com/grafana/grafana/issues/3661 is merged.
If fill null fix the issue, please try latest build.

**Closed** 2016-06-02 09:51 UTC
Labels: state: needs more detail
