### ISSUE TITLE
Create a new panel and option to import it inside a dashboard.

### ISSUE THREAD

**Issue by prashant1rana** [grafana/grafana#21883] opened 2020-01-31 21:12 UTC
**What would you like to be added**:
Create a new panel and option to import it inside a dashboard.

**Why is this needed**:
This is a very important feature, which can be used in different scenario.

For instance
You have 3 different panels and you want to create 4 dashboards with different combinations as
Dashboard #1 : Panel #1 + Panel #2
Dashboard #2 : Panel #2 + Panel #3
Dashboard #3 : Panel #3 + Panel #1
Dashboard #4 : Panel #1 + Panel #2 + Panel #3

Now you wanna play Grafana playlist on a Kiosk/TV. So you can't use link.

**Current way:**
Create 4 new dashboard and create new panels for each dashboard.

**Issue:**
If you wanna change something for Panel #2.. You will have to update Dashboard #1, #2 and #4. That is not user friendly at all, beacause you are gonna end up with more than 20 dashboard if you are gonna monitor a medium size system.

**What would be awesome:**
Option to create and name panels.
Creating dashboard with new panels or you can import above created panels using names.
On run time, dashboard will get the updated content from panels.
If you wanna change panel #2, then you don't need to change in any dashboard at all.

**Now all will be HAPPY...**

**Comment by peterholmberg** [comment] 2020-02-03 15:41
duplicate of https://github.com/grafana/grafana/issues/1803

**Closed by peterholmberg** 2020-02-03 15:41 UTC
