### ISSUE TITLE
Dynamic max value calculated per Column instead of whole Table

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#35324] opened 2021-06-07 11:26 UTC
**What happened**:
If you use a _Override_ for a column to set the _Cell display mode_ to **Gradient gauge**, the maximum is calculated based on **all** values of **all** columns.
![out](https://user-images.githubusercontent.com/1107939/121008657-832fcd00-c793-11eb-8875-00ed205f352f.gif)

**What you expected to happen**:
The maximum should be **only** calculated per column, not between different columns.

**How to reproduce it**:
- Create a new panel: Visualization -> Table
- Set: Format as: Table
- Query:
``` sql
SELECT
 c1 as time,
 c2 as small,
 c3 as large
FROM (VALUES
  (1,10,1000), (2,20,2000), (3,30,3000)
) t1 (c1, c2, c3)
```
- Create override: Overrides -> Cell display mode -> Gradient gauge

**Environment**:
- Grafana version: v7.5.7 (91de51771c)

**Comment by torkelo** [comment] 2021-06-07 12:01
duplicate of https://github.com/grafana/grafana/issues/26383

**Closed by torkelo** 2021-06-07 12:01 UTC
