### ISSUE TITLE
InfluxDB fill() function does not work in alert requests

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#24979] opened 2020-05-21 11:06 UTC
**What happened**:
If you use the `fill()` function in the request for an alert, the alert shows a lack of data, although the graph is displayed correctly.

**What you expected to happen**:
There will be no data difference between the alert and the graph

**How to reproduce it (as minimally and precisely as possible)**:
Create a query that can return no values sometimes
Use the `fill()` function to fill empty spaces
Set alert

**Anything else we need to know?**:
Alert configuration:
![image](https://user-images.githubusercontent.com/50422107/82552859-9a415400-9b6b-11ea-8732-e49fc7a1bb44.png)
Query:
![image](https://user-images.githubusercontent.com/50422107/82552929-c2c94e00-9b6b-11ea-9068-a4719427f377.png)

This is a rather serious situation, since Grafana does not allow you to configure an alert so that it works only if one of the series stops returning data. Nor can we use `fill()` so that the lack of data is perceived as some value.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: InfluxDB 1.7.3
- OS Grafana is installed on: container

**Comment by Estrax** [comment] 2020-06-03 09:57
@M0rdecay the fill function works flawlessly - you just have your alert set in a wrong way. With that alert definition you are looking for a max value that the query returns, that's equal to 1, according to your query expression - it's also displayed properly on a graph and within the graph legend. To get it working the way I see you wanted, so to alert when something falls below a given threshold, you have to use a a condition when `last()` value changes instead.

![Screenshot from 2020-06-03 11-54-43](https://user-images.githubusercontent.com/6322797/83623011-1044b280-a591-11ea-94db-c73583b06251.png)

So the correct setting is going to be like:

![Screenshot from 2020-06-03 11-56-40](https://user-images.githubusercontent.com/6322797/83623221-57cb3e80-a591-11ea-9128-2ac939726d2f.png)


Closing this issue now. Happy to help if there are more questions.

**Comment by M0rdecay** [comment] 2020-06-03 10:10
Unfortunately, this did not work:
![image](https://user-images.githubusercontent.com/50422107/83624557-72a2b080-a59b-11ea-82d1-65fe4cb07954.png)

**Comment by M0rdecay** [comment] 2020-06-03 10:29
@Estrax it is worth clarifying that I can only reproduce the situation in this form:
1. Install the telegraf to the host, start the collection of metrics
2. Turn off the telegraf

Then the alert returns No Data, although zero is displayed on the chart.

At the same time, if for some reason the telegraf cannot call pgrep on the host to collect information about the processes, the information is also missing, but the alert works as if the presence of information in neighboring tables somehow affects this (which sounds illogical and unrealistic).

**Comment by Estrax** [comment] 2020-06-03 11:46
@M0rdecay with the same settings (just a different metric) I get alerts being rendered properly:
![Screenshot from 2020-06-03 13-09-04](https://user-images.githubusercontent.com/6322797/83632511-b26b9700-a59f-11ea-8213-ec14c154639c.png)

so looks like we miss out something. How do you have the section of "No data & error handling" configured (you can find them in the alerts tab)? Which version of Telegraf do you use? Are you able to query the data from the telegraf influxdb after stopping the telegraf agent?

**Comment by M0rdecay** [comment] 2020-06-03 12:02
The version of telegraf is 1.13.4 - 1.14.3 depending on the host. The agent version does not affect the situation.
Data from InfluxDB is available after stopping the agent.
Full alert settings are as follows:
![image](https://user-images.githubusercontent.com/50422107/83633896-51958c00-a5aa-11ea-8dff-179661dbc142.png)
Alert test:
```json
{
  "firing": false,
  "state": "no_data",
  "conditionEvals": "false = false",
  "timeMs": "2.827ms",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1591185085409,
        "queries": [
          {
            "refId": "A",
            "model": {
              "alias": "$tag_host : $tag_appl",
              "groupBy": [
                {
                  "params": [
                    "$__interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "interval": "1m",
              "orderByTime": "ASC",
              "policy": "default",
              "query": "SELECT round(mean(\"running\") / mean(\"running\")) FROM \"base_rp\".\"procstat_lookup\" WHERE \"host\" = 'host' AND \"appl\" = 'telegraf' AND $timeFilter GROUP BY \"stand_name\", \"host\", \"appl\", time($__interval) fill(0) offset 1",
              "rawQuery": true,
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "mean"
                  }
                ]
              ],
              "tags": []
            },
            "datasource": {
              "id": 2,
              "name": "emon"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1591185205409
      }
    },
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "series": []
      }
    },
    {
      "message": "Condition: Eval: false, Query Returned No Series (reduced to null/no value)",
      "data": null
    }
  ]
}
```
For simplicity, I limit the request to one test host. This is how the alert looks for all the site’s hosts:
![image](https://user-images.githubusercontent.com/50422107/83634189-c963b680-a5aa-11ea-8cc0-2569771aa927.png)

Interestingly, the alert temporarily switched to `Pending`, but returned to the `OK` state. It works like this after setting `when` -> `last()`, before (`mean()`) there wasn’t even going to `Pending`.

**Comment by Estrax** [comment] 2020-06-03 12:10
@M0rdecay Did you try setting up "if no data or all values are null" to `Alerting` and check if that solves your problem?

**Comment by M0rdecay** [comment] 2020-06-03 12:12
@Estrax yes of course. I will report the result in a few minutes

**Comment by M0rdecay** [comment] 2020-06-03 12:28
Unfortunately, this did not help:
![image](https://user-images.githubusercontent.com/50422107/83635726-632c6300-a5ad-11ea-9cda-ea044f48f4a4.png)

What is expected, in my opinion - according to the documentation, this setting affects only all returned series.
As the time window shrinks, the series associated with the test host simply disappears from the graphs - this is a InfluxDB issue [#6967](https://github.com/influxdata/influxdb/issues/6967) 

And now it seems to me that this is the reason...
When the alert is working, of course, the period specified in OF is evaluated, and when we go beyond it, the data simply disappears - they are not returned by InfluxDB.

Thanks for your time, you really helped! Let's close the issue, it’s all about the data source.

**Closed** 2020-06-03 12:28 UTC
Labels: datasource/InfluxDB

**Comment by Estrax** [comment] 2020-06-03 12:43
Unfortunately, we weren't able to solve the issue this time, but at least we confirmed where the problem comes from. Thank you for providing a lot of context, @M0rdecay! It clearly made it all much easier to debug. Feel free to reach out if you have any questions.
