### ISSUE TITLE
Graph-panel with staircase interpolation draws incorrect starting point

### ISSUE THREAD

**Issue by StephanThonig** [grafana/grafana#26658] opened 2020-07-28 15:37 UTC
Hello there,

Recently i´ve been working a lot with the basic graph panel to visualize my data.
For the purpose of representing sampled sensor metrics (correctly) i chose the staircase interpolation type,
This is when i realised that the starting point of the staircase always begins at 0.
In contrast to that the normal line interpolation starts drawing the line from the first valid value.
The difference can be seen right here **(behaviour for NULL configured as "NULL")**:

Staircase:

![InterpolationStaircase](https://user-images.githubusercontent.com/68914026/88686538-7c5a1780-d0f7-11ea-908d-3f475cae032c.png)

Line (default):

![InterpolationLine](https://user-images.githubusercontent.com/68914026/88686582-85e37f80-d0f7-11ea-95ab-e3455589a45d.png)

I would expect the staircase to behave the same for the first valid value after a NULL, meaning the line should not start a 0.
This also has a bad effect on the scaling of the entire panel, as can be seen in the two images as well.
Since the value 0 is the starting point for the staircase the minimum y-value is 0, even tho there is no such value in the data.

It would be highly appreciated to see this fixed in future version of Grafana.

**Anyways a big thanks for all the great work done so far!**

**Comment by torkelo** [comment] 2020-07-28 18:27
duplicate of https://github.com/grafana/grafana/issues/17838

**Closed by torkelo** 2020-07-28 18:27 UTC
Labels: area/frontend, area/panel/graph, needs investigation
