### ISSUE TITLE
Raw document selectable

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#3697] opened 2016-01-11 13:32 UTC
Feature request: 
When using raw document metric, the panel output lines are not selectable. Useful if showing log files and need to copy something

**Comment by torkelo** [comment] 2016-01-11 13:40
?

**Comment by torkelo** [comment] 2016-01-11 13:40
You mean select text with mouse?

**Comment by torkelo** [comment] 2016-01-11 13:41
As a temp work around enter edit mode, the bug is caused by dragosgcrisan@gmail.com droplease.  Think I fixed it in master

**Comment by torkelo** [comment] 2016-01-11 13:42
Dam auto correct, caused by drag and drop

**Comment by waqark3389** [comment] 2016-01-11 13:43
@torkelo Yes, sorry wasnt clear enough. so I can copy and paste. this will be added in 2.7?

**Comment by torkelo** [comment] 2016-01-11 14:19
I think I fixed it ,will double check before closing issue

**Comment by torkelo** [comment] 2016-01-12 09:22
this appears to not have been fixed :(

dupe of 
https://github.com/grafana/grafana/issues/2083

**Closed by torkelo** 2016-01-12 09:22 UTC
