### ISSUE TITLE
choose time range have a bug

### ISSUE THREAD

**Issue by mengxuexue** [grafana/grafana#26715] opened 2020-07-31 03:40 UTC
**What happened**:
when i clearn ’from’ value，then focue to ‘to’ input,will alert error
![image](https://user-images.githubusercontent.com/23066891/88996693-7eeb8580-d320-11ea-8d01-ca8eac2e5906.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v7.1.0
- Data source type & version: any
- OS Grafana is installed on:
- User OS & Browser: choogle chrome
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment] 2020-07-31 05:19
Can you please fill in the "How to reproduce it (as minimally and precisely as possible):" section in the issue description, so we can see how to reproduce?

**Comment by torkelo** [comment] 2020-07-31 06:02
duplicate of #26553

**Closed by torkelo** 2020-07-31 06:02 UTC
Labels: area/frontend, needs more detail
