### ISSUE TITLE
apt fails to upgrade grafana to 9.3.6

### ISSUE THREAD

**Issue by nerblock** [grafana/grafana#62595] opened 2023-01-31 14:29 UTC
**What happened**:

Ran `apt update && apt upgrade`, it found 9.3.6 and tried to download it but failed with this error:

```
Err:1 https://apt.grafana.com stable/main armhf grafana armhf 9.3.6
  404  Not Found [IP: 2a04:4e42:41::729 443]
E: Failed to fetch https://apt.grafana.com/pool/main/g/grafana/grafana_9.3.6_armhf.deb  404  Not Found [IP: 2a04:4e42:41::729 443]
```

**What you expected to happen**:

A successful upgrade.

**How to reproduce it (as minimally and precisely as possible)**:

Run `apt update && apt upgrade`.

**Anything else we need to know?**:

That's all for now.

**Environment**:
- Grafana version: 9.3.6
- OS Grafana is installed on: Armbian

**Comment by wiggels** [comment] 2023-01-31 14:36
Same issue here attempting to install grafana with apt on Debian 11.

**Comment by nerblock** [comment] 2023-01-31 14:47
As a sidenote I'm using the latest rotated gpg keys mentioned here: https://apt.grafana.com

Also for those who has this problem. Just disable the grafana repo temporarily so your other updates won't get interrupted white they sort this out with:

```
sudo mv /etc/apt/sources.list.d/grafana.list /etc/apt/sources.list.d/grafana.list.bak
```

**Comment by paladox** [comment] 2023-01-31 15:38
I'm also having the same issue.

**Comment by mellieA** [comment] 2023-01-31 16:19
Duplicate of https://github.com/grafana/grafana/issues/62544

**Comment by mnul** [comment] 2023-01-31 16:19
New installs according to the latest documentation don't work as well.
You can follow up to `sudo apt install grafana`
It fails with 
`Err:1 https://apt.grafana.com stable/main amd64 grafana amd64 9.3.6
  404  Not Found [IP: 151.101.130.217 443]
E: Failed to fetch https://apt.grafana.com/pool/main/g/grafana/grafana_9.3.6_amd64.deb  404  Not Found [IP: 151.101.130.217 443]`

**Closed** 2023-01-31 16:22 UTC
Labels: type/duplicate
