### ISSUE TITLE
[Feature Request] - Aliases for "Custom" templated variable

### ISSUE THREAD

**Issue by PauloAugusto-Asos** [grafana/grafana#8270] opened 2017-05-02 10:07 UTC
# Request aliases for "Custom" templated variables

I recently had to construct an optional filter for some InfluxDB Panels. The filter had to be optional. I ended up creating a "Custom" template variable with the following options:

- NO
- (.+\.storage)|(.+\.control)|(.+\.timeoutsdispatcher)|(.+\.timeouts)|(os:.+)|(tcp:.+)

To be used in a query like:
`SELECT qwerty, azerty, FROM table WHERE a = 123 AND instance !~ /$customFilter/`

So the user is presented with the option "NO", which is user friendly but ends up having to «work» correctly in the InfluxQL query;

And the second option in the DLL is just .. inscrutably looking for the user but I can't give it an alias.

# Proposal
Some way of allowing the options in the Custom template variables to have an alias, instead of showing the value itself as the option name too.

**Comment by torkelo** [comment] 2017-05-02 11:35
duplicate of https://github.com/grafana/grafana/issues/1032

**Closed by torkelo** 2017-05-02 11:35 UTC
