### ISSUE TITLE
Alerting/Graphite - "tsdb.HandleRequest() error Request failed status: 500 Internal Server Error"

### ISSUE THREAD

**Issue by luketopa** [grafana/grafana#10475] opened 2018-01-09 14:50 UTC
- What Grafana version are you using?

Grafana_4.6.3

- What datasource are you using?

Graphite

- What OS are you running grafana on?

CentOS 7

- What did you do?

Setup Alerting

- What was the expected result?

Alert Fired on select query metric

- What happened instead?

error:"tsdb.HandleRequest() error Request failed status: 500 Internal Server Error"

- If related to metric query / data viz:

Query

 A

stream.prod.us1customer_order_oms_gm_opm.count
 B

stream.prod.us2crc_customer_order_oms_gm_opm.count
 C

stream.prod.us3crc_customer_order_oms_gm_opm.count
 D

stream.prod.us4crc_customer_order_oms_gm_opm.count
 E

stream.prod.no_stress_test_order_cnt.order_cnt
 F

alias(movingAverage(sumSeries(#A, #B, #C, #D, #E), 10), 'Current')
 G

timeShift(sumSeries(#A, #B, #C, #D, #E), '7d')
 H

timeShift(sumSeries(#A, #B, #C, #D, #E), '14d')
 I

timeShift(sumSeries(#A, #B, #C, #D, #E), '21d')
 J

timeShift(sumSeries(#A, #B, #C, #D, #E), '28d')
 K

timeShift(sumSeries(#A, #B, #C, #D, #E), '35d')
 L

group(#G, #H, #I, #J, #K)
 M

alias(movingAverage(percentileOfSeries(#L,50, 'false'),10), 'Prediction')
 N

offset(asPercent(#F, #M), -100)
 O

![image](https://user-images.githubusercontent.com/22776264/34726551-33c9c5aa-f509-11e7-880a-f4e52ea08eb2.png)

I want to Alert against 'N'

![image](https://user-images.githubusercontent.com/22776264/34726593-5f39caaa-f509-11e7-92d0-7cb613f23b8e.png)

**Comment by torkelo** [comment] 2018-01-10 08:55
dupe of https://github.com/grafana/grafana/issues/9995

**Closed by torkelo** 2018-01-10 08:55 UTC
