### ISSUE TITLE
Could I send an alert every minute if the conditions are met every minute?

### ISSUE THREAD

**Issue by ck003** [grafana/grafana#20493] opened 2019-11-20 03:50 UTC
> **What happened**:
 > When the persistent condition is met, the alert cannot be sent every minute. Only when the alert state changes, the alert is sent only when the alert condition is met again.
 > **What you expected to happen**:
 > I expect that as long as the alert condition is met, the alert is sent every minute.
 > **How to reproduce it (as minimally and precisely as possible)**:
 > **Environment:**
 > Grafana version:  v5.4.3
 > Data source type & version: Elasticsearch 5.x
 > OS Grafana is installed on: Docker
 > User OS & Browser: Win10 Chrome
 > Grafana plugins:
 > Others: 
![image](https://user-images.githubusercontent.com/19967081/69207601-55703c80-0b8b-11ea-8cfe-4d1f52dbe524.png)

**Comment by marefr** [comment] 2019-11-20 13:45
Duplicate of #6041

**Comment by marefr** [comment] 2019-11-20 13:46
Have a look at [notifcation reminders](https://grafana.com/docs/alerting/notifications/#send-reminders) for a workaround.

**Closed by marefr** 2019-11-20 13:46 UTC
