### ISSUE TITLE
calendar sometimes closes itself when using new timepicker

### ISSUE THREAD

**Issue by tsn77130** [grafana/grafana#21981] opened 2020-02-06 15:40 UTC
**What happened**:

When we select dates in Absolute time range new calendar, it sometimes closes itself and does not validate selected start & end dates.

**What you expected to happen**:

After selection, see selected period in blue as expected, and be able to change it if needed before validate.

**How to reproduce it (as minimally and precisely as possible)**:

Just select a first date on calendar, blue circle appears around date, and then select a second date. Randomly, calendar closes itself and we have to start again.

**Anything else we need to know?**: - 

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: postgres
- OS Grafana is installed on: debian 9.11
- User OS & Browser: chrome 79.0.3945.88 on debian
- Grafana plugins: -
- Others: -

**Comment by sakjur** [comment] 2020-02-10 12:56
I looked into this a little and can confirm the same behavior in both Chrome 79.0.3945.130 and Safari 13.0.4 on MacOS (both master and 6.6.1). I also noticed that pressing say "from" and then a date and "apply timerange" doesn't seem to work, unsure if that's intended behavior, but it had me perplexed for a little while when trying to recreate this bug.

**Comment by heyrod** [comment] 2020-02-10 15:02
The same issue. Our users complain about "unfriendly" behavior of the Time Picker when trying to select dates in different months.
Often double-clicking the "from" date helps fix the start of the period.

**Comment by mckn** [comment] 2020-02-17 15:31
Thanks for reporting this, will be fixed in next release 🙌

**Closed** 2020-02-18 11:30 UTC
Labels: area/frontend, needs investigation, priority/important-soon, type/bug
