### ISSUE TITLE
Garbled characters when typing Metrics.

### ISSUE THREAD

**Issue by Joey777210** [grafana/grafana#58496] opened 2022-11-09 02:09 UTC
![grafanabug](https://user-images.githubusercontent.com/53630996/200719904-8cc3eb1b-3801-4c05-888b-b7d711b1d67e.gif)

**What happened**: Garbled characters when typing Metrics. Seems a Character set problem. Not sure it whether a grafana bug or my environment issue.
Just Metrics textbox, every thing good with other functions.
I can't write/edit, but when I wrote promQL in vscode and paste in Metrics textbox, it works fine.

**What you expected to happen**: No Garbled characters.

**How to reproduce it (as minimally and precisely as possible)**: Garbled characters when typing Metrics. But everything all right with other functions.

**Anything else we need to know?**: 

**Environment**:
  OS: windows 10
  Browser:Chrome 107.0.5304.88

- Grafana version:   v7.3.6 (ea06633c34)
- Data source type & version: Prometheus with promQL 
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome 107.0.5304.88
- Grafana plugins: no plugins 
- Others:

**Comment by usmangt** [comment] 2022-11-09 07:22
Hi @Joey777210,

Thanks for opening this issue.

Based on your steps of reproduction, I was not able to reproduce it on my test machine. (see attached screenshot)

![image](https://user-images.githubusercontent.com/69509548/200764354-72c9aeeb-fdd9-4d77-8ef6-3519eebb36e0.png)

One of the main reasons is that I am using the latest stable version of Grafana 9 and as you wrote that using ver. 7

Still giving a chance of doubt, try to reproduce this same issue on https://play.grafana.org/ and then share the dashboard link so that we can view it.

**Additional**
Please note that we are no longer maintaining/fixing the ver 7 issue as we only support 2 major versions for bugfixes (currently ver 8 and 9).

Therefore suggestion would be to update to the latest stable version.

**Comment by herrbpl** [comment] 2022-11-28 11:08
I have similar issues with Grafana 8.1.0
I type in explorer bar:
![image](https://user-images.githubusercontent.com/2135514/204262941-cd0b25e0-25b3-4156-86d3-0a944696de56.png)
But when I copy this text to VS code edit window, i see this:
![image](https://user-images.githubusercontent.com/2135514/204263108-e641cd5b-682b-4b24-8416-57c357e5cce5.png)
Its totally broken, not possible to edit any query in query window

**Comment by herrbpl** [comment] 2022-11-28 11:11
I guess there is some "helper" for providing Intellisense which garbles anything

**Comment by herrbpl** [comment] 2022-11-28 11:13
There is also issue with typing that when you edit query and go to edit something inside the text, cursor always jumps to end of input.

**Comment by herrbpl** [comment] 2022-11-28 11:14
Dev tools console shows such error, not sure, if related anyhow:

`language_utils.ts:75 Uncaught (in promise) Error: Not inside selector, previous selector already closed: ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿dotnet_exceptions_total﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿{﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿service﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿=﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿"prod-bo01-cellxpert-integration-service"﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿, ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿type﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿=﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿"System.OutOfMemoryException"﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿}﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿[﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿1m﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿]﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿
    at h (language_utils.ts:75:11)
    at g.getAggregationCompletionItems (language_provider.ts:310:22)
    at g.provideCompletionItems (language_provider.ts:182:19)
    at PromQueryField.tsx:259:43
    at ne (suggestions.tsx:278:42)
    at h (lodash.js:10401:23)
    at y (lodash.js:10450:18)
    at g (lodash.js:10438:18)`

**Comment by itsmylife** [comment] 2022-11-30 20:57
@Joey777210 @herrbpl 
This was a known issue and was resolved in `v7.5.17` and `v8.5.13` and `v9.1.4`. So I suggest upgrading the versions. 
Related PR https://github.com/grafana/grafana/pull/54566

Could you please upgrade the Grafana version and try again?

**Comment by itsmylife** [comment] 2023-01-03 20:46
I am closing this one assuming it is resolved. Feel free to open another issue if you still experiencing problems.

**Closed by itsmylife** 2023-01-03 20:46 UTC
Labels: datasource/Prometheus, area/frontend, oss-user-essentials
