### ISSUE TITLE
Grafana Bar-Chart Panel does not refresh shown values

### ISSUE THREAD

**Issue by AlexWirthAAU** [grafana/grafana#39166] opened 2021-09-14 07:53 UTC
I am using Grafana (Grafana v8.1.2 (103f8fa094)) for viewing data that i read directly from a MySQL DB. I have two panels using the new beta bar-chart. The problem i have is the following:

When i choose a new intervall in the right top corner (e.g. from 7 days to 30 days) the new correct values are loaded and the length of the bars is refreshed. However, the values next to the bars dont refresh automatically. Only when clicking on the right bottom corner legend the values next to the bars are updated:

Here is the data with intervall 7 days

![image](https://user-images.githubusercontent.com/56222411/133217530-1f374764-15a7-41a9-987c-c4d9e5a9d016.png)

After choosing 30 days the data is loaded correctly and the bars are shown correctly, but the values next to the bars are still the old ones, unless i click the yellow legend “Bestellungen”. Then the shown values are refreshed and the line turns from color yellow to color green.

![image](https://user-images.githubusercontent.com/56222411/133217562-91e876cd-483d-4506-92b6-dafc83826be5.png)

You can actually see it from the axis, that the right values are there but not shown correctly next to the bars.

Additional Info: I am using Opera Browser

Kind regards
Alex

**Comment by leeoniya** [comment] 2021-09-14 11:45
duplicate of https://github.com/grafana/grafana/issues/38410

**Closed by leeoniya** 2021-09-14 11:45 UTC
