### ISSUE TITLE
Explore Mode:  Show the values displayed on the graph with mouseover

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#16567] opened 2019-04-13 19:29 UTC
**What would you like to be added**:

I noticed Explore graph panel misses mouse over function which is present in "normal" graph panels - moving mouse close to the graph would show the values

![image](https://user-images.githubusercontent.com/3651746/56084409-ae5f4180-5e00-11e9-997e-4558669dec3c.png)

**Why is this needed**:

It is very helpful to see the exact values on the graph without having to find it in the table below

**Comment by torkelo** [comment] 2019-04-15 10:14
dupe of https://github.com/grafana/grafana/issues/12000

**Closed by torkelo** 2019-04-15 10:14 UTC
