### ISSUE TITLE
Light theme hover on graph is broken in grafana 6.1.0

### ISSUE THREAD

**Issue by radut** [grafana/grafana#16421] opened 2019-04-05 19:39 UTC
**What happened**:
Light Theme hover bold is broken 

**What you expected to happen**:

See highlighted line

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana, set light theme, hover a graph with lines

**Anything else we need to know?**:

On black theme everything is ok

**Environment**:
- Grafana version: 6.1.0
- Data source type & version: Prometheus 2
- OS Grafana is installed on: linux
- User OS & Browser: Chrome
- Grafana plugins: 
- Others: 
<img width="392" alt="Screenshot 2019-04-05 at 22 34 52" src="https://user-images.githubusercontent.com/4960306/55652227-9598cf80-57f3-11e9-9456-ab82ff89507e.png">
<img width="334" alt="Screenshot 2019-04-05 at 22 38 15" src="https://user-images.githubusercontent.com/4960306/55652236-99c4ed00-57f3-11e9-9c79-c259412229f8.png">

**Comment by lukasertl** [comment] 2019-04-05 21:34
Duplicate of #16359 ?

**Comment by multiple1** [comment] 2019-04-07 09:28
Having the same issue with Grafana v6.1.1 (eff01d2).

Possible something wrong with stylesheet:
Disabling of color attribute of .graph-tooltip-list-item--highlight seems to fix it:

![A](https://user-images.githubusercontent.com/37273764/55681345-bd885000-5925-11e9-96b0-02d6cc5dfeca.png)
![B](https://user-images.githubusercontent.com/37273764/55681346-c0834080-5925-11e9-91f1-fb3549b41b6d.png)

When i disable the attribute in dark mode the text gets slightly darker (not so easy to see in screenshot).
=> color for light mode needs to be changed independently

![image](https://user-images.githubusercontent.com/37273764/55681431-ec52f600-5926-11e9-91ab-cb8c436ed054.png)

![image](https://user-images.githubusercontent.com/37273764/55681427-dd6c4380-5926-11e9-8c66-34ea279279ac.png)


PS:
graph-tooltip-list-item--highlight: possible typo graph-tooltip-list-item--highlight vs graph-tooltip-list-item-highlight

**Comment by torkelo** [comment] 2019-04-07 13:05
dupe of https://github.com/grafana/grafana/issues/16359 

but thanks for the info 

> graph-tooltip-list-item--highlight: possible typo graph-tooltip-list-item--highlight vs graph-tooltip-list-item-highlight

No it's not a type, it followes BEM naming rules

**Closed** 2019-04-07 16:44 UTC
