### ISSUE TITLE
[BUG] SMTP error: tls: server selected unsupported protocol version 300

### ISSUE THREAD

**Issue by eagleamon** [grafana/grafana#8385] opened 2017-05-16 09:09 UTC
Hi, I have not found something related to this issue for grafana so I am opening this.

- What Grafana version are you using? 
4.2.0
- What datasource are you using?
graphite
- What OS are you running grafana on?
ubuntu 14.04
- What did you do?
configured alerting with email to be sent, no authorisation nor tls required
- What was the expected result?
a mail sent
- What happened instead?
an error: tls: server selected unsupported protocol version 300

I have tested the smtp server with direct telnet command without authorisation nor certificates and it works.

My smtp config (cleaned):
 
[smtp]
enabled = true
host = myrelay:25
;user =
;password =
;cert_file =
;key_file =
skip_verify = true
from_address = monitoring@mydomain
from_name = Me

**Comment by torkelo** [comment] 2017-05-16 09:28
Looks like your smtp server tries to upgrade to TLS but that fails for some reason. 

duplicate of https://github.com/grafana/grafana/issues/7189

**Closed by torkelo** 2017-05-16 09:28 UTC

**Comment by eagleamon** [comment] 2017-05-16 10:18
Is it a duplicate ?

Here is the EHLO output of the smtp server:
250-TLS
250-STARTTLS
250-DSN
250-SIZE 37580800
250-8BITMIME
250 PIPELINING

Is there anyway to trace the smtp exchange between grafana and the server  ? I tried debug and trace in the log level but I do not get anything more than the error.

**Comment by eagleamon** [comment] 2017-05-23 08:17
No ? :s

**Comment by torkelo** [comment] 2017-05-23 08:36
not sure
