### ISSUE TITLE
Custom Plugin: Error with threejs on v10.2.0

### ISSUE THREAD

**Issue by GuYounes** [grafana/grafana#84368] opened 2024-03-13 12:46 UTC
### What happened?

I have an error on plugin load when using a specific loader of threejs: 
![image](https://github.com/grafana/grafana/assets/32415454/674eec36-61b7-4313-9ac6-33239dff8634).

I encountered this issue since upgrading to Grafana 10.2.0. I think that it comes from the systemjs module loader.
Maybe I can have an easier way to reproduce the issue. Let me know if needed.

### What did you expect to happen?

The plugin to load correctly

### Did this work before?

It was working prior Grafana v10.2.0

### How do we reproduce it?

1. Create new plugin
2. Install threejs 0.158.0
3. Add those lines to the plugin panel component: 

```
import React, { PropsWithChildren, ReactElement, useRef } from 'react';
import { VRMLLoader } from 'three/examples/jsm/loaders/VRMLLoader.js';

export const TestPanel= () => {
  const loader = new VRMLLoader();

  return <div></div>;
}

```

### Is the bug inside a dashboard panel?

A custom panel I made.

### Environment (with versions)?

Grafana: 10.2.0
OS: Windows 11
Browser: Chrome 121.0.6167.185

### Grafana platform?

None

**Comment by jackw** [comment] 2024-04-22 10:49
@GuYounes many thanks for raising this issue. Unfortunately ThreeJS is a rather large library with many bundled dependencies which can trip up plugin loading. Having reproduced the issue it appears to be caused by the bundled lib `chevrotain` which includes a lib that relies on window.define. Unfortunately this doesn't work with the SystemJS define function that we rely on for loading plugins.

The only workaround I can suggest would be to:

1. copy the VRMLLoader.js from Three into the plugin source code
2. install `chevrotain` as an npm dependency of the plugin
3. update the import in the copied VRMLLoader.js to `import chevrotain from 'chevrotain';`.

Like this the plugin will bundle all the libs rather than use the pre-bundled version from Three that is causing the error. If I do this locally, I get a working ThreeJS plugin:

<img width="1792" alt="Screenshot 2024-04-22 at 12 41 09" src="https://github.com/grafana/grafana/assets/73201/0a9cd4e5-be77-4fb7-9f9e-1e26f7a9e7bf">

**Comment by GuYounes** [comment] 2024-04-23 06:27
@jackw thank you for investigating this. The issue is even more complexe because I'm using a library using ThreeJS. I simplified the exemple so it would be easier to debug for you.
Anyway thanks for your time and for the workaround :)

**Comment by jackw** [comment] 2024-04-24 12:07
That certainly makes it more tricky! The only workaround I can think of there would be to use either `yarn patch` or the npm [patch-package](https://www.npmjs.com/package/patch-package) module to "doctor" the `three/examples/jsm/loaders/VRMLLoader.js` file so it imports `import chevrotain from 'chevrotain';` and install `chevrotain` as a dependency of the plugin so webpack will bundle it without the umd build.

**Comment by GuYounes** [comment] 2024-04-24 15:56
Thank you for the hint  :) !  I'll see if I can achieve something with that

**Comment by mckn** [comment] 2024-04-29 07:35
I'm closing this issue as resolved with @jackw great responses. Please let me know if I should re-open this issue.

**Closed by mckn** 2024-04-29 07:35 UTC
Labels: area/plugins, triage/needs-confirmation
