### ISSUE TITLE
 Create link to dashboard

### ISSUE THREAD

**Issue by renanGoncalez** [grafana/grafana#10699] opened 2018-01-31 15:48 UTC
Hello guys!
I am trying to create an authenticated link for a dashbord, I have a backend in java and a front end in JSF, I want to put on the screen a user that when clicked will redirect the user direct to his dashboar.
Is this possible?

**Comment by torkelo** [comment] 2018-01-31 16:43
closing as dupe of this feature request, https://github.com/grafana/grafana/issues/3752

**Closed by torkelo** 2018-01-31 16:43 UTC

**Comment by renanGoncalez** [comment] 2018-01-31 17:10
Hello guys!
I'm trying to create an authenticated link for a dashbord, I have a backend in java and a front end in JSF, I want to put a user on the screen that, when clicked, will redirect the user directly to his dashboar, I'm not understanding the concept well, someone Do you have an example of how I can do this?
