### ISSUE TITLE
Make time picker consistent with time correction setting

### ISSUE THREAD

**Issue by swissdave** [grafana/grafana#2547] opened 2015-08-18 14:48 UTC
Hi there.. just updated to the latest version - very nice, thanks!

I've had a request from a couple of users - when you set the time correction to UTC mode, the charts show the correct times in UTC.  As far as I can see, the time picker remains in local browser time though - this makes things a little confusing.

Could we possibly switch the time picker to either local/UTC based on the dashboard setting and show this in the title bar somewhere?

**Comment by torkelo** [comment] 2015-08-18 16:43
duplicate of https://github.com/grafana/grafana/issues/1050

**Closed by torkelo** 2015-08-18 16:43 UTC

**Comment by swissdave** [comment] 2015-08-18 17:39
Sorry, searched but this didn't turn up.
