### ISSUE TITLE
When the variables refers each other in the dashboard,  there will be just a empty page

### ISSUE THREAD

**Issue by xf0rk** [grafana/grafana#11307] opened 2018-03-20 09:51 UTC
Read before posting: 

- Questions should be posted to https://community.grafana.com. Please search there and here on GitHub for similar issues before creating a new issue. 
- Checkout FAQ: https://community.grafana.com/c/howto/faq
- Checkout How to troubleshoot metric query issues: https://community.grafana.com/t/how-to-troubleshoot-metric-query-issues/50

Please include this information:
### What Grafana version are you using?
5.0.1
### What datasource are you using?
Elasticsearch
### What OS are you running grafana on?
Centos 7.4
### What did you do?
Refer two different variables each other in one dashboard，like 
v1: {"find":"terms", "field":"log.va1.keyword", "query":"log.va2.keyword: $v2"}
v2: {"find":"terms", "field":"log.va2.keyword", "query":"log.va1.keyword: $v1"}
### What was the expected result?
Try to work like the lab feature "value groups/tags".
### What happened instead?
It works without step into other dashboards. 

![2018-03-20_173853](https://user-images.githubusercontent.com/10670906/37646903-e030468c-2c65-11e8-98ee-ba8102e7841e.png)

![image](https://user-images.githubusercontent.com/10670906/37646970-0e525c58-2c66-11e8-93c3-f7f0400bfa65.png)

Once you leave the dashboard, the dashboard will show nothing just a empty page in chrome. 

![2018-03-20_174609](https://user-images.githubusercontent.com/10670906/37647182-9989f02e-2c66-11e8-8e62-bfd35d0a2eca.png)

It's easy to make it shown again.

**Comment by bergquist** [comment] 2018-04-10 19:03
dupe of https://github.com/grafana/grafana/issues/8583

**Closed by bergquist** 2018-04-10 19:03 UTC
