### ISSUE TITLE
[Feature request] Support multiple metrics in JSON data table for Elasticsearch

### ISSUE THREAD

**Issue by 907th** [grafana/grafana#6899] opened 2016-12-09 16:47 UTC
Grafana 4.0.1 | Elasticsearch 1.7 | macOS Sierra

*What did you do?*
I create JSON data table from a single query containing multiple `Sum(field1)` `Sum(field2)` ... metrics.

*What was the expected result?*
There must be two separate columns available for two different metrics.

*What happened instead?*
Only one attribute/column `Sum` available for show.

![Screenshot 1](http://www.picshare.ru/uploads/161209/bCk9K9oH0i.png)
![Screenshot 2](http://www.picshare.ru/uploads/161209/93MSJp1nvf.png)

**Comment by 907th** [comment] 2016-12-09 21:18
I'm absolutely newbie in this project sources. But the issue seems related to [this func](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/elastic_response.js#L183). I may try to fix this myself

**Comment by torkelo** [comment] 2016-12-12 14:19
dupe of https://github.com/grafana/grafana/issues/4709

**Closed by torkelo** 2016-12-12 14:19 UTC
