### ISSUE TITLE
Cannot add an alias for a query when Aliasing is next to the bottom of the browser window

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#44319] opened 2022-01-21 13:33 UTC
**What happened**: When trying to add an alias for a query (B), the menu panel that opens up descends below the bottom of the window in the browser but I cannot scroll down into it to select then entry under "Aliasing". A screenshot is attached showing the bottom section of the browser window where the "Aliasing" entry in the menu finishes just above the bottom of the browser window with the "^" next to aliasing indicating that there should be a sub menu. That sub menu cannot be seen.

**What you expected to happen**: To be able to access the menu under "Aliasing"

**How to reproduce it (as minimally and precisely as possible)**: Go to the dashboard and try to add an alias to the query.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: influxdb
- OS Grafana is installed on: CentOS
- User OS & Browser: MacOS, Chrome Version 93.0.4577.63 (Official Build) (x86_64)
![Screen Shot 2022-01-22 at 12 25 26 am](https://user-images.githubusercontent.com/24280758/150535334-c492cc5a-4cca-4ba5-8c26-7e90f3d2e4fd.png)

**Comment by yellowpattern** [comment] 2022-01-21 13:35
The problem is actually worse than this - if the menu descends below the bottom of the browser window, it isn't possible to scroll the browser window down to see the rest of the menu.

This should either trigger the browser window to resize to be bigger and allow scrolling down or for the menu to expand above where it originates from.

**Comment by yesoreyeram** [comment] 2022-02-01 12:35
@yellowpattern - I am able to reproduce this issue.

@ashharrison90 - Setting the `menuShouldPortal`[ here](https://github.com/grafana/grafana/blob/v8.3.4/public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Seg.tsx#L110) to `false` seems to fix the issue. But I am afraid to make this change as that is going to be removed in future versions. Do you know what will be the actual fix here instead setting the `menuShouldPortal` to false?

cc @gabor

**Comment by ashharrison90** [comment] 2022-02-01 14:43
@yesoreyeram yeah i'd avoid that as well. it doesn't really fix the issue anyway, it just works around it by growing the content. 

it looks like the select menu doesn't correctly calculate the position when you default `isOpen` to true. i'm guessing because the options are populated asynchronously? i think it positions the menu based on the initial content (which is basically nothing). so on first render, the content is empty. then the options get populated and the menu grows. if you change [this line](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Seg.tsx#L114) to something like `isOpen={!loadState.loading}`, it positions correctly.

that might be a good enough fix, or you might want the select menu to be open all the time. if that's the case, you'll probably need to trigger a rerender of the select component somehow.

**Comment by gabor** [comment] 2022-02-01 15:16
@yesoreyeram i think @ifrost was looking into this `isOpen` problem a couple months ago, i don't remember what the end of it was, i'll ask him.

**Comment by ifrost** [comment] 2022-02-02 09:25
It was fixed in 8.3.4 by https://github.com/grafana/grafana/pull/42446. The bug back then was reported for Graphite so I haven't tested Influx, but if Influx uses the same component it should be working fine.

**Comment by gabor** [comment] 2022-02-02 09:36
unfortunetely, i tried and in both 8.3.3 and 8.3.4 it is the same problem.. maybe the influx version uses the component with different props?

the component doing the work is at https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/influxdb/components/VisualInfluxQLEditor/Seg.tsx

it uses `import { InlineLabel, Select, AsyncSelect, Input } from '@grafana/ui';` so in theory should be covered by @ifrost 's change

**Comment by jorioux** [comment] 2022-03-15 13:25
The issue is still present on 8.3.4.

As a workaround, you can zoom out (`CTRL` + `-`) in chrome until you see the whole dropdown menu.

**Comment by yellowpattern** [comment] 2022-06-11 11:49
Any chance this will get looked at before 9.0?

**Closed** 2022-12-14 09:51 UTC
Labels: datasource/InfluxDB, needs investigation
