### ISSUE TITLE
FR: Services as grafana plugins

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3886] opened 2016-01-29 04:08 UTC

**Comment by torkelo** [comment] 2016-01-29 13:25
can you describe what you mean and what the problem is that your trying to solve?

**Comment by utkarshcmu** [comment] 2016-01-29 22:43
I would like to have Grafana has services as plugins which can be used in panel plugins or datasource plugins without changing Grafana core structure. Following are some use cases which I can come up in my mind right now:

1. If Atlas datasource wants to write to Slack, then Atlas datasource plugin can use Slack service plugin to post messages on Slack.

2. If Gauge panel wants to send some data to a Kafka Queue or an SQS queue, then gauge panel plugin can use Kafka / SQS service plugin to post data to Kafka / SQS.

**Comment by woodsaj** [comment] 2016-01-30 20:39
This is already possible with the new "App" plugin support in Master.

We will be providing documentation and example plugins to demonstrate the feature in the near future.

**Comment by utkarshcmu** [comment] 2016-01-30 20:41
@woodsaj That is awesome news. Looking forward to Apps documentation. :)

**Comment by bergquist** [comment] 2016-02-12 09:17
Closing this since apps will for full the requirements.

**Closed by bergquist** 2016-02-12 09:17 UTC
