### ISSUE TITLE
Stat plugin - magic colorizing

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#34810] opened 2021-05-27 10:44 UTC
**What happened**:
When I put some code and take Stat Panel then colorizing me text automatically and is not possible to change color font to other color. I don't have overrides.
**How to reproduce it (as minimally and precisely as possible)**:
Add stat plugin and code: `SELECT convert(varchar,dateadd(hour,1,$__timeTo()),120) 'Zakres od:'`

Look it, when I click a code and exit from code, the font change color automatically :) magic :)
**_How do I change the font color to make it constants?_**

![Animation](https://user-images.githubusercontent.com/73607094/119813124-30c7f400-bee9-11eb-892a-55659029f27e.gif)

**Environment**:
- Grafana version: 8.0.0-beta2
- Data source type & version: MS SQL
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome
- Grafana plugins: Stat plugin
- Others: n/a

**Comment by Elfo404** [comment] 2021-05-28 14:14
Thanks for reporting this, i can reproduce it a well. 

looping in @grafana/grafana-frontend-platform

**Comment by torkelo** [comment] 2021-05-28 14:33
duplicate of https://github.com/grafana/grafana/issues/34519

**Closed by torkelo** 2021-05-28 14:33 UTC
Labels: area/frontend, area/panel/stat

**Comment by Elfo404** [comment] 2021-05-28 14:37
@torkelo i looked for a duplicate for solid 5 minutes but somehow I missed that issue. sorry for the spam 🙏
