### ISSUE TITLE
when exceeding 10k time series, not getting rendered from drop down by Stackdriver plugin

### ISSUE THREAD

**Issue by joyw-2018** [grafana/grafana#53837] opened 2022-08-17 14:16 UTC
**What happened**:
When using Cloud Monitoring Grafana Plugin, 
once the project has more than 10,000 metrics, the plugin would not render the metrics in the drop down

**What you expected to happen**:
the plug in renders the metrics when over 10,000 metrics and the page would paginate properly for selecting.

**How to reproduce it (as minimally and precisely as possible)**:
When using a project that returns more than 10,000 timeseries when call ListMetricsDescriptor API

**Anything else we need to know?**:

The issues seem to be listMetricsDescriptor has a cap of 10k so if you implement pagination on the plugin it would fix it.
https://github.com/grafana/grafana/blob/689639cdb060f87f1689505c85d199dbc61d6ef1/public/app/plugins/datasource/cloud-monitoring/datasource.ts#L178

**Environment**:
- Grafana version: 8+
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: Cloud Ops (Stackdriver)
- Others:

**Comment by andresmgot** [comment] 2022-08-18 08:07
Another note: it seems we could hit similar limits with other resources there like SLOs and SLO services. We should move the resource fetching to the backend and handle the pagination there.

**Comment by aangelisc** [comment] 2022-08-18 09:59
Hey @joyw-2018, which version of Grafana are you using exactly? It looks like this may be a duplicate of #53563. Pagination was introduced [here](https://github.com/grafana/grafana/pull/42546) and should appropriately handle the case where more than 10k metrics are in a project. 

If you let me know what version you're using we can identify if it has that fix 😊

**Comment by andresmgot** [comment] 2022-08-18 10:24
> Another note: it seems we could hit similar limits with other resources there like SLOs and SLO services. We should move the resource fetching to the backend and handle the pagination there.

so that was already done :) :+1:

**Closed** 2022-08-18 16:15 UTC
Labels: type/bug, datasource/GoogleCloudMonitoring
