### ISSUE TITLE
User Configurable Units

### ISSUE THREAD

**Issue by EdHurtig** [grafana/grafana#2968] opened 2015-10-17 04:51 UTC
~It is possible that I missed something however I can't seem to find a way to get Distance Units (meters, centimeters, ect).  Please let me know if this is possible! Otherwise:~

Could there be some way of configuring custom units? I doubt it is a good idea to keep hardcoding all the units as there will always be far more units out there that people will want to use.  

Is seems like it would also help DRY up [code like this](https://github.com/grafana/grafana/blob/5b1727bcba39dc70da471acdbbaaf93755698a05/src/app/components/kbn.js#L382-L389)

A Unit Configuration would be a:
- Name of the Unit: `Feet`
- Category/Group: `Distances`
- Symbol: `ft`

Dealing with the `formatFuncCreator` might be a bit difficult and change up that basic definition slightly

Custom units could be part of the Dashboard config, Org Config, or just a global Grafana configuration

Specifically looking for units of Distance, Acceleration, and Force.

**Comment by torkelo** [comment] 2015-10-17 16:53
some custom units are simple, the problem is that some require scaling (like ms -> seconds -> minutes). But for simple unit prefix a custom option could be added. 

And there is some improvement to the units code in this PR
https://github.com/grafana/grafana/pull/2955

**Comment by EdHurtig** [comment] 2015-10-17 17:39
Yup that scaling part was what I was alluding to with the `formatFuncCreator`.  Will check out that PR

**Comment by phillipp** [comment] 2016-03-06 16:53
So I would like to address another thing with the units, because I would like to "localize" the units.

"Bps", "bps" and "pps" might be what the human brain of a non-german (or non-european, I don't know) is used to, but my german brain is not and believe it or not it makes the graph a lot harder to read for me. I would like it to be "/s" instead of "ps".

I tried to do this by injecting custom JS in the browser but the units are defined in a anonymous function and I can't see how they can be changed. What would be the easiest way to do this?

**Comment by EdHurtig** [comment] 2016-03-06 23:21
:+1: to localized units

**Comment by royemmerich** [comment] 2017-02-07 16:38
I'm busy working on a water desalination project where we're using the following units not available in Grafana:

* µS/cm (conductivity - microsiemens per centimeter)
* bar (as in pressure)
* l/h (flow - litres per hour)

I strongly support being able to add custom units.

**Comment by RichiH** [comment] 2017-02-07 18:38
Funny; I will need all those soon.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by mookins** [comment] 2017-02-14 21:29
I require those same units too!

**Comment by nagimov** [comment] 2017-02-26 21:46
+1 for more pressure units (bar, torr, pa) and units customization

**Comment by mikeshultz** [comment] 2017-02-28 02:45
If we're just throwing out units here, time ticks (tenths of a second) too?  But yeah, a good way to do user-defined unit conversions would be awesome.  We don't always have control of the data being fed into grafana, so we kind of have to deal with what we're given.

**Comment by joriws** [comment] 2017-03-21 12:45
Is there any progress on this? On my mind I would like to see 1000-based and 1024 (or 2^10) based units as well. Key thing would be easy to implement units with base.

**Comment by EdHurtig** [comment] 2017-03-22 08:40
I have been adding suffixes to my single-stat panels for the time being and adjusting the font such that it looks somewhat similar to the units display.

**Comment by nagimov** [comment] 2017-03-22 16:15
Same here, I add suffixes with units, grafana's scaling takes care of adding `K`, `M`, etc. prefixes to your suffixes. E.g. here's the panel with `Hz` suffix and automatically added `K` prefix (so it reads `3200 Hz`):
![2017-03-22 09_12_26-grafana - isac cryoplants](https://cloud.githubusercontent.com/assets/3197765/24208016/bc1aac78-0edf-11e7-811a-e46c88aff8bf.png)

**Comment by MarkTurbo** [comment] 2017-06-06 20:22
Configurable unit prefixes and suffixes are great, but there is also the need to apply custom formatting to the actual numeric values as well, like using the 'printf' format code "%'d" to turn 1234567 into 1,234,567.

**Comment by wrossmann** [comment] 2017-06-21 20:34
+1 for this. It's not possible for Grafana to account for all the bizarre things that someone might choose to calculate.

Eg: `scale(derivative(seconds_behind_master), -1)` gives the the recovery rate of my MySQL slave in `s/s`, a unit which I doubt is useful enough to be built in to a future version.

**Comment by brunorey** [comment] 2017-06-26 19:33
I'm measuring framerate in FPS (frames per second) and this would be useful for me as well.

Also, there's a similar issue open, maybe it should be marked as dupe: https://github.com/grafana/grafana/issues/4113

**Comment by lgerster** [comment] 2017-08-29 07:56
I more often than not don´t find the units I need provided by grafana, Hertz per second, Gauss, liters per hour, kg per day, Megahertz, Terahertz

**Comment by steveh80** [comment] 2018-02-17 14:27
I'd need g/m³ for absolute humidity.

Another useful thing would be to transform values to a specified value (e.g. pump 0/1 is on on/off, window 0/1 is open/closed).

**Comment by victorclaessen** [comment] 2018-02-21 09:27
I would like to request the unit Bq (for "radioactivity") and Sv/h (Sievert/h, for "radiation level" or "dose equivalent rate"). It would be great if we could just add any custom unit as text.

**Comment by EdHurtig** [comment] 2018-02-21 22:32
More details on the suffix/postfix workaround: For unsupported units, I put my unit designators in the `Postfix` field and using unicode characters as needed for superscripts/subscripts etc. While this does not auto-range the unit (ex. when pressure is `1500` the text renders as `1.5 kpsi`) however, solves the immediate problem of tagging my single stat's with units.

<img width="453" alt="screen shot 2018-02-21 at 5 18 44 pm" src="https://user-images.githubusercontent.com/1410448/36508975-284691dc-172c-11e8-933c-2668364b9299.png">

@steveh80 regarding the conversion of 0/1 to Open/Closed or On/Off, I do that with value mappings and use the value (0 or 1) to set the background color. 

<img width="923" alt="screen shot 2018-02-21 at 5 24 43 pm" src="https://user-images.githubusercontent.com/1410448/36508958-217819ac-172c-11e8-8e94-7a2de39827eb.png">

Regarding g/m³, you should be able to paste that directly into the postfix field.

Sorry if this is pointing out the obvious... just wanted to make sure this thread had a well worded workaround.

**Comment by steveh80** [comment] 2018-02-22 05:04
@EdHurtig I understand your workarounds are for the singlestat panel. Are there similar workarounds for the graph panel, because I have the problems there.

**Comment by EdHurtig** [comment] 2018-02-22 06:46
The only workaround I have found for graphs is adding a label to the Y axis like so.
<img width="344" alt="screen shot 2018-02-22 at 1 45 33 am" src="https://user-images.githubusercontent.com/1410448/36523954-1e732922-1772-11e8-92a3-b4132a1eb68f.png">

**Comment by flopp999** [comment] 2018-03-10 15:09
We are measuring gases and we use a lot of different units for this, can you add below unit:
ppm
ppb
ng/m3
ng/Nm3
μg/m3
μg/Nm3
mg/m3
mg/Nm3
g/m3
g/Nm3

**Comment by flopp999** [comment] 2018-03-12 19:40
@marefr Thank, I have never done it but I will try, all help is welcomed :)
I have now created an issue #11211

**Comment by tecmatia-dp** [comment] 2018-05-11 14:44
+1 for customizable units.

I have modified the kbn.ts file with the units that we use most in our projects, and rebuild custom Grafana, but each installation almost always requires a new one... It would be a great improvement.

**Comment by gabrielbriones** [comment] 2018-11-27 02:32
+1 customizable units

I use grafana to report tensorflow benchmarks which units are images/sec

**Comment by Stardidi** [comment] 2018-12-06 13:03
+1 
In our case I would like to display our data (in seconds) as work days or  work weeks, where 8 * 60 * 60 seconds = 1 work day.

This might also be a good area for plugins to come in.

**Comment by wuast94** [comment] 2018-12-20 00:17
+1 
In my Case mhz (Core Clock from GPU/CPU)

**Comment by egomezgon** [comment] 2018-12-20 16:02
+1 customizable units

It depens on the data source if the wind speed unit is m/s or km/h

**Comment by jeanduporte** [comment] 2019-10-16 12:05
+1
In my case, I need some units that don't exist because I use chemical parameters. I need µS/cm for the conductivity and m³/h for my flow.

This might also be good to create our own unit without asking them each time.

**Comment by torkelo** [comment] 2019-12-04 11:26
This is now implemented and will come in 6.6
https://github.com/grafana/grafana/pull/20763

**Closed by torkelo** 2019-12-04 11:26 UTC
Labels: area/panel/common, type/feature-request

**Comment by polmonso** [comment] 2020-03-20 15:06
It'd be nice to be able to still get the mili- kilo- Mega- in some cases. In my case, for Wh/m^2

**Comment by SaSc0803** [comment] 2020-04-21 07:37
I have the issues with times/durations in a table.
I want to format values like 4.5 to 5h or 0.25 to 15m but not 168 to 1week or 24 to 1day.
Is there a way to set postfixes in a table?

**Comment by OZ1SEJ** [comment] 2020-05-14 12:38
> This is now implemented and will come in 6.6
> #20763

I'm running 6.7.3, and I don't have Length -> cm

**Comment by Soumyank** [comment] 2020-08-13 18:14
I need micron / micrometer

**Comment by rufreakde** [comment] 2023-07-06 14:21
So is there no default for kubernetes [CPU metric units](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu)?

1 CPU / 1000m
0.1CPU / 100m

I saw "mebibytes" for the Memory but where is the CPU pendant?

I mean grafana is used so often with k8s that should be default right?
