### ISSUE TITLE
Link shortener option in share pop-up replaces IP address with "localhost"

### ISSUE THREAD

**Issue by jacobHclarkson** [grafana/grafana#29233] opened 2020-11-19 14:22 UTC
**What happened**:
When I toggle the "Shorten URL" option, the IP address in the sharing link is replaced with "localhost"
![image](https://user-images.githubusercontent.com/6830620/99678034-0e10da80-2a83-11eb-9fc2-bd25363448ad.png)

**What you expected to happen**:
Shortened URL maintains IP address.

**How to reproduce it (as minimally and precisely as possible)**:

- Toggle "shorten URL" when the original link has the IP address instead of a domain name.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.3 (2489dc4d3a)
- Data source type & version: prometheus
- OS Grafana is installed on: ubuntu 20.04
- User OS & Browser: Manjaro Linux, Chromium
- Grafana plugins: None
- Others: Grafana and Prometheus data source both running on same EC2 instance

**Comment by dprokop** [comment] 2020-11-20 09:18
@jacobHclarkson thanks for reporting this. Is your app configured with https://grafana.com/docs/grafana/latest/administration/configuration/#root_url set to the correct ip?

The problem is in line https://github.com/grafana/grafana/blob/60d40fa99b4bfb01941c2e63336640fae7551e2f/pkg/api/short_url.go#L31 where the setting.AppUrl is used for the shortlink generation

**Comment by hija** [comment] 2020-11-20 17:07
I am having the same problem.  I set up my grafana instance behind nginx as reverse proxy according to https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1. I set domain and so I think that url_url should be correct.

**Comment by wbrowne** [comment] 2020-11-24 10:56
@hija @jacobHclarkson could you clarify what your `setting.AppUrl` is set to? This is what is used to define the host

**Comment by hija** [comment] 2020-11-24 20:44
Good news - I am just stupid.

I've set the "domain" value in the grafana.ini but forgot to comment out (or comment in... I mean like converting the line from a comment to an acutal settings value) the line. Now I did it, restarted grafana and it works.

**Comment by wbrowne** [comment] 2020-11-25 09:08
Great to hear your problem is resolved @hija! In that case, I will close this issue.

**Closed by wbrowne** 2020-11-25 09:08 UTC
Labels: needs more info
