### ISSUE TITLE
Plain text version of email notifications

### ISSUE THREAD

**Issue by djairho** [grafana/grafana#32345] opened 2021-03-26 08:44 UTC
**What would you like to be added**:
Currently, it seems like the email notifications that are sent by the alerting system only contain a HTML version. However, it would be better to also include a plain-text version of the email.

```
Content-Type: multipart/alternative;boundary=SOMEBOUNDARY

This is a MIME encoded message.

--SOMEBOUNDARY
Content-type: text/plain;charset=utf-8

This is a text email, the text/plain version.

--SOMEBOUNDARY
Content-type: text/html;charset=utf-8

This is a text email, the <b>html</b> version.

--SOMEBOUNDARY--
```

**Why is this needed**:
Not all email clients support viewing HTML emails.
Also, some transactional email providers require both a HTML and plain-text version (e.g. MailerSend).

**Comment by zoltanbedi** [comment] 2021-03-26 08:54
Duplicate of #11436

**Closed by zoltanbedi** 2021-03-26 08:54 UTC
