### ISSUE TITLE
Generic_OAuth should reject user if role_attribute_path is set and returns nil

### ISSUE THREAD

**Issue by dabelenda** [grafana/grafana#23202] opened 2020-03-30 14:04 UTC
**What would you like to be added**:
When setting `role_attribute_path` auth.in generic_oauth, the user should be rejected when JMES returns nul. This is what seems the most reasonable when the oauth userinfo does not return a role for the user.

**Why is this needed**:
For the same reason as https://github.com/grafana/grafana/issues/22741 having a default role when the OAuth provider does not provide one is a problem for some providers that do not allow application authentication control, and only provide applications with roles.
An example of that is Keycloak. When a keycloak client (application that needs to be authenticated via oauth) is configured in a realm, all users in the realm can authenticate, and RBAC support is expected from the client (application). The only workaround for that is to create an application-specific realm, but it's not Single Sign On anymore...

**Comment by dabelenda** [comment] 2020-03-30 14:06
The default role comes from [users] auto_assign_org_role
which also cannot be unset.

**Comment by burakksglu** [comment] 2020-03-31 06:33
Is this related? grafana/grafana/issues/23218

**Comment by dabelenda** [comment] 2020-03-31 06:37
@burakksglu I can see why you say it could be related, but in my case I still want View, Edit and Admin roles, what I am missing is a "no rights" role in grafana.

**Comment by marefr** [comment] 2020-03-31 07:45
Duplicate of #23218

**Closed by marefr** 2020-03-31 07:45 UTC

**Comment by marefr** [comment] 2020-03-31 07:46
Suggest you add a comment to referenced issue of your requirement,

**Comment by dabelenda** [comment] 2020-03-31 07:59
@marefr using #23218 to fix my use-case mean completely changing the roles management in grafana to add a new role without any rights. The two use-cases are not really related since I want to ban users without role from generic_oauth, and #23218 is disallow users with a role.
I specifically pointed #22741 because it is the same use-case with another authentication provider.

**Comment by burakksglu** [comment] 2020-03-31 08:10
Actually the first part what you're saying is what #23218 does. We also wanted to restrict users with only the right roles. Therefore we used Grafana's default roles 'Admin','Editor','Viewer'. If user doesn't have neither of those we can restrict login if  the parameter is set like this in config : 'Role_allowed=True'

I know it's not %100 your use case but disallowing or restricting unwanted roles is what we tried to do in that PR.

Best Regards :)

**Comment by marefr** [comment] 2020-03-31 08:12
Both this and referenced issue is about restricting access based on some criteria why this issue is a duplicate. Will try to rewrite referenced issue to make it more applicable if needed.

**Comment by levkar** [comment] 2020-04-01 09:05
@dabelenda please vote for https://github.com/grafana/grafana/issues/23218

**Comment by tnacsak** [comment] 2022-11-09 15:44
The solution is not working properly in 9.1.1. If role_attribute_path results nil (or a defualt strig of empty string. None, whatever, means a non existing role, and role_attribute_strict = true set, Login drops to error page, and log shows problem on nil.
https://community.grafana.com/t/oauth-reject-users-if-they-dont-own-specific-roles/25168/9?u=tnacsak
