### ISSUE TITLE
Transformations: Ability to move transformations up and down rearrange 

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#24481] opened 2020-05-10 05:45 UTC
Transformation order should be rearrangeable.

The transformation order on tables matters when fields are filtered. If a field is marked as filtered before a calculated field is created (using a filtered field), then the calculation will not work. This makes adding calculated fields an annoyance as the field filter must come afterwards and recreated manually when new calculated fields are added.

**Comment by dprokop** [comment] 2020-07-02 11:49
Duplicate of https://github.com/grafana/grafana/issues/25482

**Closed by dprokop** 2020-07-02 11:49 UTC
Labels: area/transformations, type/duplicate, type/feature-request
