### ISSUE TITLE
Loading into frame

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#29280] opened 2020-11-20 21:20 UTC
**What would you like to be added**:
Option to add grafana dashboard to for example frame in HTML, without logging in.
**Why is this needed**:
It would be better for integrating into websites.

**Comment by aocenas** [comment] 2020-11-23 12:01
There is already a way to embed panels. https://grafana.com/docs/grafana/latest/dashboards/share-panel/#embed-panel. If you want embed full dashboards can you be more specific of how that should look like or what is your usecase?

**Comment by radimkohout** [comment] 2020-11-23 14:41
Yeah, but you need to create a snapshot and then load it into the frame. I need to load it for displaying in my system without the user's need to log in.

**Comment by aocenas** [comment] 2020-11-24 08:57
There are already 2 issues for helping with embedding dashboard as an Iframe https://github.com/grafana/grafana/issues/26105 and https://github.com/grafana/grafana/issues/13706. Please check if some of the workarounds there would help you.

Regarding the "displaying in my system without the user's need to log in" part you can allow users to see dashboards without them being logged in https://grafana.com/docs/grafana/latest/auth/grafana/#anonymous-authentication.

**Comment by radimkohout** [comment] 2020-11-25 17:29
How can I do it without logging in? I can't figure.

**Comment by aocenas** [comment] 2020-11-26 16:20
@radimkohout I mean if you setup the anonymous authentication then users don't need to authenticate to access dashboards. This means if you embed the dashboard in an iframe, users seeing the iframe will see the dashboard and not the login page.

**Comment by radimkohout** [comment] 2020-11-26 18:08
@aocenas Isn't there a possibility to change the dashboard variable in anonymous mode?

**Comment by aocenas** [comment] 2020-11-27 11:28
It should be possible. Or are you saying you would like for anonymous users not to be able to change variables? You can always create a dashboard without the variables and just hardcode the values.

**Comment by radimkohout** [comment] 2020-11-27 12:04
That's not really the best option, since I would need 400 dashboards for all users.

**Comment by marefr** [comment] 2021-01-13 11:22
Seems like this is not a bug and workarounds have been provided. I'm closing this for now. In case you think this is wrong, please provide detailed information of reproducing your setup and implied bug. 

In addition, make sure you enable Grafana to be embedded, https://grafana.com/docs/grafana/latest/administration/configuration/#allow_embedding.

**Closed by marefr** 2021-01-13 11:22 UTC
Labels: area/dashboard, needs more info, type/feature-request
