### ISSUE TITLE
BarChart: missing tooltip values when stacking option is set to normal

### ISSUE THREAD

**Issue by vishynit** [grafana/grafana#41977] opened 2021-11-19 14:14 UTC
**What happened**:
When stacking option is set to normal in Bar graph, the tool tip does not show any values. 

![Recording_App_Monitor_Stacking_Issue](https://user-images.githubusercontent.com/52401068/142636316-c80d4a96-6f07-485c-b363-566a05c07f4a.gif)

Stacked bar chart should also show the values in tooltip. 

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: Infinity 0.7.8
- OS Grafana is installed on: Ubuntu
- User OS & Browser: OS - Mac , Browser - Chrome
- Grafana plugins: Bar Graph
- Others:

**Comment by torkelo** [comment] 2021-11-20 08:43
Can replicate this on 8.2 and main
![Screenshot from 2021-11-20 09-41-05](https://user-images.githubusercontent.com/10999/142720222-e06337a9-042e-4a9d-9a00-cd5b0ba484fb.png)

Just enable stacking on this panel: 
https://play.grafana.org/d/ktMs4D6Mk/5-bar-charts-and-pie-charts?orgId=1&editPanel=15

**Comment by zoltanbedi** [comment] 2021-11-22 08:24
I'm going to close this as duplicate of #40865

**Closed by zoltanbedi** 2021-11-22 08:24 UTC
Labels: type/bug, area/panel/barchart
