### ISSUE TITLE
Cannot assign folder to new alert rule (not always, at least)

### ISSUE THREAD

**Issue by nagylzs** [grafana/grafana#58313] opened 2022-11-07 10:41 UTC
This is on Grafana 9.1.8, please see the attached video.

- When I type in "General" folder name, then it is not found in the list, but it says "Hit enter to create"
- I hit enter, and it says that folder already exists
- However, it is never shown in the list, even if I refresh the whole page
- Interestingly, if I choose a different name, yes "not so general" and hit enter, then the folder is created

What is happening here?

**Comment by nagylzs** [comment] 2022-11-07 10:43
I was not sure how to add a screen recording, because I had it in mp4 format. Here is a link: https://imgur.com/a/Pwi23IN

**Comment by usmangt** [comment] 2022-11-08 13:24
Hi @nagylzs,

Thanks for opening this issue.

Based on your steps of reproduction, I was also able to reproduce it on my test machine. However, the behaviour seems valid because there is already a folder defined inside my dashboard (i think by default) named General (see attached screenshot).

So, just like you, if I also use the "+ Add a new folder to create" and type General, gives the same error message.

![image](https://user-images.githubusercontent.com/69509548/200575696-4740ddc9-9edb-4626-b605-a3b6cb26e858.png)

I think we can close this issue unless I am missing something (if yes, then let me know).

Thanks

**Comment by nagylzs** [comment] 2022-11-08 13:50
If there is already a folder named "General" then why can't I search for it and select it?

You might say, that dashboard folders and alert folders are separated - but in that case, why can't I have a "General" folder for alerts? In other words: if the "General" folder can store both bashboards and alerts, then I should be able to find it using its name. In the current implementation, it is not possible to find it or select it, and also not possible to create it.  I believe this is an error (or at least hard to explain to a user.)

**Comment by usmangt** [comment] 2022-11-14 13:20
Thanks,

I understand what you mean. This seems like in between a bug or feature request, therefore I will let the developers decide as what category suits best of this case.

**Comment by jonatan-ivanov** [comment] 2024-01-08 11:00
I bumped into this too, if I don't specify a folder for my dashboards, they go into `General` but I can't specify the `General` folder for alerts and I need to specify one (`folder` cannot be empty for alerts) so I end up with an empty folder for my dashboards.

**Comment by joshhunt** [comment] 2024-12-03 18:47
This was addressed in Grafana 10.2 by removing the 'General' folder https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-2/#find-your-dashboard-faster-with-the-new-dashboards-browse-screen 

> To make using folders easier and more consistent, there’s no longer a special General folder. Dashboards without a folder, or dashboards previously in the General folder, are now shown at the root level.

The reason Alerts could not be placed in the General folder was because the General folder did not technically exist - it was a fiction of the frontend to house dashboards that are not in a folder. Alerts _must_ be placed in a folder, and the fake General folder didn't count.

Because this was annoying and confusing, when we revamped the Browse Dashboards UI in Grafana 10.2, we show Dashboards without a folder as just floating at the root, where people expect them.

**Closed by joshhunt** 2024-12-03 18:47 UTC
Labels: type/bug, area/alerting, area/dashboard/folders, needs investigation, prio/unscheduled
