### ISSUE TITLE
Alerting: Add default email template to templates

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#73446] opened 2023-08-17 22:16 UTC
### Discussed in https://github.com/grafana/grafana/discussions/46329

<div type='discussions-op-text'>

<sup>Originally posted by **bobemoe** March  8, 2022</sup>
# Use case

I'm wanting to customise the alert email message. Just want to make some small tweaks,

# Backgroud
By default the contact points and message templates are empty. Granted there are links to templating and variable docs.

I create a template but have to search how to link the template to a contact point. Seems I need to edit the message and put a link to the template in there. Still not quite figured that out yet. 

As for the email template, I'll have to start crafting from scratch referencing docs for variable names. (this will help https://github.com/grafana/grafana/issues/35726)

# Feature Request
If would be great if the default email template was already available in the templates list for editing or duplication. This would give me a much better starting point for customisation.</div>

**Comment by armandgrillet** [comment] 2023-08-18 16:33
Duplicate of https://github.com/grafana/grafana/issues/57439

**Closed by armandgrillet** 2023-08-18 16:33 UTC
Labels: area/alerting, area/alerting/notifications
