### ISSUE TITLE
Explore and Learn : Prometheus Metrics Overview

### ISSUE THREAD

**Issue by sc00bylu** [grafana/grafana#72638] opened 2023-07-31 17:55 UTC
### What happened?

In the explore and Learn module, the URL that goes to Prometheus Metrics Overview has "Dashboard Not Found

### What did you expect to happen?

I'd expect the link to be accurate to go directly to the Prometheus Metrics Overview page

### Did this work before?

Yes

### How do we reproduce it?

1.  Go to Explore and Learn https://<user>.grafana.net/a/cloud-home-app/onboarding-flow/explore
2. Click on Prometheus Metrics Overview
3. Observe error page

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

I use Grafana Cloud

**Comment by sc00bylu** [comment] 2023-07-31 17:56
Same issue with Population and avg life expectancy, and the Citi Bike in NYC dashboards...

**Comment by tonypowa** [comment] 2023-08-02 08:41
thank you for reporting this issue @sc00bylu 

I am routing this to the appropriate team

{"message":"Dashboard not found","traceID":"059474753bd94bd29e3cd34eb6a6784e"}

**Comment by tonypowa** [comment] 2023-08-03 07:50
@sc00bylu 

the problem has been [acknowledged ](https://github.com/grafana/hg-cloud-home-admin/issues/473)and there is a fix in place 🎉 

I am closing this issue since the problem is related to Grafana cloud, and not to Grafana open source

Thank you

**Closed by tonypowa** 2023-08-03 07:50 UTC
