### ISSUE TITLE
Save Dashboard popup when interacting with Library panels

### ISSUE THREAD

**Issue by danialre** [grafana/grafana#51932] opened 2022-07-07 19:28 UTC
**What happened**: The "Save Dashboard" dialog appears when leaving a dashboard without making changes. This is reliably reproduced after interacting with a Library panel. When selecting/deselecting a series in a Time series panel, the dialog appears even when there is no change in filtered series.

**What you expected to happen**: The dialog to only pop up when making changes

**How to reproduce it (as minimally and precisely as possible)**:
1. Open a dashboard with a library panel
2. Interact with the library panel - for example, select/deselect certain series in a Time Series panel.
3. Exit the dashboard.
4. The "Save Dashboard" dialog pops up, and the Changes tab only shows a change in iteration.
![Screen Shot 2022-07-07 at 1 26 14 PM](https://user-images.githubusercontent.com/22201598/177856208-602ba67d-7c35-4032-9856-639890972a7d.png)

**Anything else we need to know?**: Started with 8.5, is likely related to #48304, #50649

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: grafana/grafana Docker image
- User OS & Browser: MacOS/Firefox & MacOS/Chrome
- Grafana plugins:
- Others:

**Comment by eric-kinsa** [comment] 2022-07-13 15:31
I'm experiencing this as well. I recently setup the [prometheus/grafana ](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)stack, which includes a kubernetes mixin of grafana dashboards. When I just view the dashboard; don't even click on anything, I get prompted to save when I exit. I couldn't even save it if I wanted to since I get this:

> This dashboard cannot be saved from the Grafana UI because it has been provisioned from another source. Copy the JSON or save it to a file below, then you can update your dashboard in the provisioning source.

**Comment by zuchka** [comment] 2022-07-15 19:54
@JoaoSilvaGrafana passing this along. not sure if you'd like to keep this one open, close and reopen another, or something else 👍

**Comment by polibb** [comment] 2022-07-22 14:11
@danialre This is no longer an issue - I cannot reproduce it in any way :). It seems to have been fixed with [this PR](https://github.com/grafana/grafana/pull/51272).

@eric-kinsa What you are describing sounds like a different issue than the one described here. Would you please open a new issue with more information about the problem you're encountering, so we can look at it separately?

**Closed by polibb** 2022-07-22 14:11 UTC
Labels: area/dashboard, oss-user-essentials
