### ISSUE TITLE
Invalid dimensions for plot

### ISSUE THREAD

**Issue by stuartbrierley1** [grafana/grafana#13118] opened 2018-09-03 10:54 UTC
I’ve installed Grafana 5.2.2 and I’m using the graph panel but in some circumstances I get an ‘Invalid dimensions for plot, width = 875, height = 0’ when using Internet Explorer 11. I do not see the error in Chrome. I am also using the ‘Grafana internals’ dashboard which I have downloaded and one of the chart panels is giving me this error. In some cases, viewing the chart in full page will work correctly and other times it will not. Any idea what is wrong?

### What Grafana version are you using?
5.2.2
### What datasource are you using?
Custom datasource and Prometheus
### What OS are you running grafana on
Redhat
### What did you do?
Open a dashboard
### What was the expected result?
Display graph
### What happened instead?
Error:  ‘Invalid dimensions for plot, width = 875, height = 0’

**Comment by marefr** [comment] 2018-09-03 14:51
Are you referring to https://grafana.com/dashboards/3590? Looks like a quite old dashboard. Please save your dashboard to be sure that the dashboard saved has the latest schema version - then reload page do you have same problems? If so, can you please include screenshots/animated gifs when it's working as expected and when not working as expected?

**Comment by stuartbrierley1** [comment] 2018-09-05 08:37
@marefr Our corporate security prevents us from uploading files like screenshots. Is there and email address I can send them to?

**Comment by marefr** [comment] 2018-09-05 11:06
@stuartbrierley1 first letter of my first name followed by my lastname at grafana.com

**Comment by marefr** [comment] 2018-09-06 16:13
@stuartbrierley1 I can reproduce it using this dashboard on play.grafana.org, https://play.grafana.org/d/9R5_J_2mk/graph-panel-with-lots-of-series?orgId=1. The three panels have the same amount of series. When using IE11 the panel at top left is resulting in "Invalid dimensions for plot" for me, but not the others.

However, we only support IE11 in a best effort manner. This is not something that we'll focus on fixing if not a lot of users reports the same problem or upvotes this issue. We accept pull requests if your interested in giving it a go with a fix.

Possible workarounds:
* Don't use IE11
* Change the legend to be placed on the right side plus set fixed width (needed for IE11) - like panel in top right
* Make the panel bigger (in height) until graph is displayed - like panel in bottom left

Will close this, but will consider reopening if you submit a pull request with a fix and/or we got more reports or a lot of upvotes from other users.

**Closed by marefr** 2018-09-06 16:13 UTC
Labels: state: needs more detail

**Comment by crazychatting** [comment] 2018-09-10 13:44
Unfortunately in our organisation we have hundreds of users that still use IE 11 so having Grafana work correctly in IE 11 is a must for us. I can understand that the UI won't be as polished due to the poor CSS support however. IE11 market share might not be big, but in enterprises it's still most used browser. At least all the basic functionality should work in IE11 (e.g. getting the correct height in JS from DOM-elements or not requiring fixed widths)... we have no chance to switch to a modern browser as IE11 is set as default browser by our IT Administration due to group policies and permissions/restrictions etc. and thatswhy it is the only allowed webkit for .NET-Applications for our kiosk-monitoring-workstations.

So all in all the Workaround solution "Don't use IE11" is not acceptable, solution 2 would also not fit on the dashboard.
It would be really nice if you could fix this for IE, that the legend will be displayed under/after the graph, so that the graph has prio 1 for the view :)
![dashboard](https://user-images.githubusercontent.com/36714171/45300794-d733f700-b4fe-11e8-8046-4b25d065f980.jpg)

**Comment by marefr** [comment] 2018-09-10 14:13
As I wrote earlier, we'll consider reopening if someone submit a pull request with a fix and/or we got more reports or a lot of upvotes from other users.

**Comment by stuartbrierley1** [comment] 2018-09-10 14:59
@crazychatting When I raised this, we were in the position that IE was the only permitted browser in the company, but fortunately that has now changed and Chrome is freely available as an alternative, where previously it was only permitted for developers.

**Comment by marefr** [comment] 2018-09-10 15:36
@stuartbrierley1 glad to hear about this update :+1:
