### ISSUE TITLE
Cannot link to dashboard using multi-value template variable

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#25638] opened 2020-06-16 17:22 UTC
**What happened**:
When using a template variable in a link (both panel link & data link), if that variable is multi-value, grafana is unable to parse the resultant URL. 

**What you expected to happen**:
Provide functional link.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a dashboard.
2. Add a multi-value variable called `foo`
3. Select multiple values in the variable selection box.
4. Create a link to a dashboard (e.g. the current one) which uses the variable.
5. Watch the multi-value variable be interpreted as a single string value (e.g. `{one,two,three}` instead of the 3 values `one`, `two`, `three`).

**Anything else we need to know?**:
Grafana normally handles multi-value variables by repeating the variable in the query string. However when constructing a link, there does not appear to be a way to accomplish this. Putting `var-myvar=${myvar}` is [the documented method for adding template variables to a link](https://grafana.com/docs/grafana/latest/variables/url-variables/#template-variables), so I would expect the documented method to work.

**Environment**:
- Grafana version: v7.0.1
- Data source type & version: N/A
- OS Grafana is installed on: CentOS/8
- User OS & Browser: Linux Chrome
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment] 2020-06-17 05:58
duplicate of https://github.com/grafana/grafana/issues/21459

**Closed by torkelo** 2020-06-17 05:58 UTC

**Comment by kamyagarg** [comment] 2021-04-05 16:40
Hey, im using v7.4.0 
I was facing the same issue. If you want to select multi values in template then data link ${var_name} would send the values like {a,b} but what i wanted was to send values in the link as a,b. 
Hence I used ${var_name:csv} and it worked.
