### ISSUE TITLE
Hide variables in the url for the users

### ISSUE THREAD

**Issue by alexrc20** [grafana/grafana#27589] opened 2020-09-15 08:55 UTC
I would like to know if is it posible to hide variables I have in the dashboard to select filters in the url.

User should use this filter and manipulate the variable, but I would like to hide the variable that the user is choosing in the url.

![Captura de pantalla 2020-09-15 a las 10 53 40](https://user-images.githubusercontent.com/51723835/93188814-bd5ac980-f741-11ea-954d-5e3c5018c60c.png)

**Comment by torkelo** [comment] 2020-09-15 09:00
duplicate of https://github.com/grafana/grafana/issues/21134

**Closed by torkelo** 2020-09-15 09:00 UTC
