### ISSUE TITLE
Ability to disable forgot your password

### ISSUE THREAD

**Issue by josephmc5** [grafana/grafana#3670] opened 2016-01-07 15:09 UTC
Add the ability to optionally remove the "Forgot your password?" link on the login page. For LDAP integrations forgot your password doesn't make sense. Users are trying to use it.

**Comment by romanponomarev** [comment] 2016-01-07 15:19
+1

**Comment by torkelo** [comment] 2016-01-07 16:10
dupe of https://github.com/grafana/grafana/issues/2495

**Closed by torkelo** 2016-01-07 16:10 UTC
