### ISSUE TITLE
LogQL Json Parser sorting logs in random order with same TS

### ISSUE THREAD

**Issue by suikast42** [grafana/grafana#60997] opened 2023-01-04 18:15 UTC
I have serval logs with the same ts but ingestest one by one over NATS to loki over golang gRPC api.

The Query returns the logs in the right order 

JournalD output on ingress is in order

![image](https://user-images.githubusercontent.com/5046525/210621601-40ecb4e3-1182-4608-ad07-4914f27eb2c6.png)

The LogQl returns the right order 
![image](https://user-images.githubusercontent.com/5046525/210621459-f49e606d-b2ed-4ff4-862d-2a6bc5f000be.png)

If I pipe the json parser to  LogQl then the logs are in wrong order 

![image](https://user-images.githubusercontent.com/5046525/210621909-2144bebe-2a93-4d08-89e3-cd28f65757e2.png)

**Comment by svennergr** [comment] 2023-01-11 09:39
Hi @suikast42,

this seems like a duplicate of https://github.com/grafana/grafana/issues/56071.

Especially you might want to look at this comment: https://github.com/grafana/grafana/issues/56071#issuecomment-1265419313

**Closed by svennergr** 2023-01-11 09:39 UTC
Labels: needs investigation, datasource/Loki, component/logql
