### ISSUE TITLE
Panels With More than 26 Queries Will have Queries w/ No Ref ID

### ISSUE THREAD

**Issue by im-auld** [grafana/grafana#11129] opened 2018-03-06 23:04 UTC
Read before posting: 

Please include this information:
- What Grafana version are you using?
4.6.3

- What datasource are you using?
N/A

- What OS are you running grafana on?
Linux

- What did you do?
Add 26 queries to a panel then add one more

- What was the expected result?
That the 27th query's `ref_id` would be labeled "AA" (or something similar).
 
- What happened instead?
It got no `ref_id` nor did any subsequent queries

Probably not a big deal since you shouldn't really be adding 27 separate queries to a single panel but it should either be a hard limit, you can't add the 27th query, or it should properly label the query. You can save the board with the unlabelled queries however referencing them in an alert would be impossible. Produces the following JSON:

```
"targets": [
  {
    "expr": "$expr",
    "format": "time_series",
    "hide": true,
     "intervalFactor": 2,
     "legendFormat": "{{listener_name}} accept",
     "refId": "A"
   },
  {
    "expr": "$expr",
    "format": "time_series",
    "hide": true,
     "intervalFactor": 2,
     "legendFormat": "{{listener_name}} accept",
     "refId": "B"
   },
  {
    "expr": "$expr",
    "format": "time_series",
    "hide": true,
     "intervalFactor": 2,
     "legendFormat": "{{listener_name}} accept",
     "refId": "C"
   },
            ...
  {
    "expr": "",
    "format": "time_series",
    "intervalFactor": 2,
    "legendFormat": "{{listener_name}} accept",
    "refId": "Z"
  },
  {
    "expr": "$aggregator($kube_node)",
    "format": "time_series",
    "intervalFactor": 2
  }
],
```

**Comment by bergquist** [comment] 2018-03-07 10:56
Duplicate of #4978

**Closed by bergquist** 2018-03-07 10:56 UTC
