### ISSUE TITLE
[BUG] No panel editor options on Firefox ESR

### ISSUE THREAD

**Issue by KnpA** [grafana/grafana#19630] opened 2019-10-04 15:11 UTC
**What happened**: When a user open another dashboard, the panel editor options are not showing in Firefox 60.9.0esr :
![image](https://user-images.githubusercontent.com/6367927/66218054-b4a3eb80-e6c8-11e9-96cc-1c2a81a9bf8a.png)

**What you expected to happen**: Having access to the panel editor 😃 

**How to reproduce it (as minimally and precisely as possible)**:
1°) Create a new dashboard
2°) Create a new panel
3°) Save the new dashboard
4°) Go to another dashboard
5°) Go back to the previously saved dashboard
6°) Edit the previously created panel

**Anything else we need to know?**:
I don't notice this issue on Edge, it looks like something related to Firefox ESR.
Maybe linked to : https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

I found a workaround : I have to open and close the dashboard list menu to see the editor options appear.

**Environment**:
- Grafana version: 6.0 to 6.4.1
- Data source type & version: -
- OS Grafana is installed on: -
- User OS & Browser: Windows 10 - Firefox 60.9.0esr
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment] 2019-10-04 15:58
dupe of https://github.com/grafana/grafana/issues/15524 

think latest firefox ESR is 68, it works fine in that verison

**Closed by torkelo** 2019-10-04 15:58 UTC
