### ISSUE TITLE
Problem with legend on the right side

### ISSUE THREAD

**Issue by mojchal** [grafana/grafana#3560] opened 2015-12-18 13:52 UTC
I have legend with many items, when I set it to be displayed on the right side, it makes really long list. It would be great to have it displayed as scrollable list with the height same or similar to actual graph area.
Also, when displayed on the right side, when I select multiple items using Ctrl+LeftMouse, all legend text is shown inverted and it is impossible to see which items are actualy selected.
v2.6.0

**Comment by torkelo** [comment] 2015-12-19 09:58
dupe of https://github.com/grafana/grafana/issues/1277

**Closed by torkelo** 2015-12-19 09:58 UTC
