### ISSUE TITLE
Time series panel lack option Hide series: With only zeroes

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#46734] opened 2022-03-18 13:00 UTC
**What happened**:

Old Graph panel had option to hide series if all returned values were zero or null.
https://grafana.com/docs/grafana/latest/visualizations/graph-panel/#hide-series

Hiding all zero values is useful to remove "noise" from the graph when rate/response used. 

Noise is time series not in use in requested time range due low usage or due fact timeseries does not exists anymore.
Prometheus list all timeseries combination found from TSDB and return value 0.

Useful when graph contain > 10 timeseries or when large percentage of timeseries are 0.

**What you expected to happen**:
Possibility to hide graph when no all values zero

Removing non zero rate is not resulting same outcome .

sum(rate(http_server_requests_seconds_count{}[2m])) by (dnsname, method, uri, exception, status) > 0

Because resut contains gaps for time series not having continuous changes and is not rendered similar way.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.7/8.4.3
- Data source type & version: Prometheus
- OS Grafana is installed on: WIndows
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by zuchka** [comment] 2022-03-22 19:54
duplicate of [this feature request](https://github.com/grafana/grafana/discussions/38299). To show your support, you can upvote the request.

**Closed by zuchka** 2022-03-22 19:54 UTC
