### ISSUE TITLE
Dashboard variable InfluxDB Flux query output different from "Explore"

### ISSUE THREAD

**Issue by Beetix** [grafana/grafana#37994] opened 2021-08-18 07:58 UTC
**What happened**:
Tested an InfluxDB Flux query in "Explore":
```
from(bucket: "mybucket")
    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "measurement")
    |> keep(columns: ["mytag"])
    |> distinct(column: "mytag")
```
The table shows a column "_value" with 3 values.
Created a dashboard variable with the same InfluxDB Flux query. The output contains only the first value of the list obtained in "Explore".

**What you expected to happen**:
Getting the same values as in "Explore"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.1 (90c87a52f7)
- Data source type & version: InfluxDB v2.0.6
- OS Grafana is installed on: Using Docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment] 2021-08-20 21:35
Hi @Beetix 

Thanks so much for opening this. Your problem sounds similar to [this old issue regarding the early days of using flux queries to define template variables](https://github.com/grafana/grafana/issues/26357).

Could you please provide any steps for reliably reproducing this issue? Thanks so much for your help on this! 👍

**Comment by Beetix** [comment] 2021-08-24 08:42
To reproduce this behaviour:

- Insert multiples measures with different values of a tag in an InfluxDB measurement
- Execute in "Explore", replacing "mybucket", "measurement" and "mytag" with values used in the previous step
```
from(bucket: "mybucket")
    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "measurement")
    |> keep(columns: ["mytag"])
    |> distinct(column: "mytag")
```
You should see all the tag's values in the given time range

- Create a dashboard variable with the same query
Only one tag value shows up even though the same time range is selected

**Comment by gabor** [comment] 2021-08-30 08:42
@artstar-es thanks for the sample data! unfortunately, i cannot reproduce the problem. if i make influxdb return the csv-data you sent us, it works just fine as a query-variable, i see 2 options in the preview-of-values: "UPS RACK" and "UPSTower".

some ideas:
1. please double-check, if you used exactly the same query in the dashboard-variable-editor as the one you used to generate the CSV
2. which settings did you change in the variable-edit form? are you using maybe the "Hide" option? or the "Regex" option? "Multi-value"? "Include all options"?

**Comment by artstar-es** [comment] 2021-08-30 10:13
OK, you've just enabled me to make a discovery, though not a favourable one. :)

Definitely using the exact same query. None of the other settings are being used.

However, if I create a new dashboard and create a new variable, the query works.

If I try creating a new variable in the existing dashboard with this query, it does not work!

Seems to me that the only way out of this will be to recreate the dashboard from scratch rather than modifying a copy of a dashboard that was originally built for a v1 DB.

**Comment by gabor** [comment] 2021-08-31 11:36
that's very strange... maybe you could try to export the problematic dashboard and then import it again, maybe the new copy will work ok? ( https://grafana.com/docs/grafana/latest/dashboards/export-import/ )

**Comment by artstar-es** [comment] 2021-09-02 10:09
Hi Gabor,

Unfortunately, no luck with that either. There must be something in that original v1 JSON that simply modifying what I need is in conflict with it.

**Comment by gabor** [comment] 2021-09-06 08:50
very strange! could you try this?:

- export the JSON and then import it as a new dashboard
- remove everything from that dashboard, except the not-working variable-query
- export the JSON from the new minimal dashboard, and upload it here? (please check the JSON and make sure no private/secret info remains in it)

**Comment by artstar-es** [comment] 2021-09-10 04:29
I have absolutely no explanation for it but apart from a couple of apt upgrades (one being cpio and the other being kernel) on this Ubuntu Focal VM, I can't see anything else that was done differently to what I was attempting before.

The good news is that it is now working with that query for the very same dashboard, so no need to export, re-import, etc.

Again, I'm buggered if I know what's made it work and I can't see how a kernel update could've had any effect on it. InfluxDB is still on 2.0.8 and Grafana is still on 8.1.2.

Anyway, for me, this is now case closed. Even the other variable query (I have two in this dashboard) is working well, using the former query's variable as part of the filter function.

Sorry for wasting your time like this mate.

**Comment by gabor** [comment] 2021-09-10 10:04
@artstar-es no worries, it was not wasted time 👍 , and it happens again in the future, feel free to reopen this issue and we can try finding the cause. for now i'll close this one.

**Closed by gabor** 2021-09-10 10:04 UTC
Labels: datasource/InfluxDB, area/dashboard/templating, needs more info
