### ISSUE TITLE
Allow to sign in as GrafanaAdmin using AzureAD

### ISSUE THREAD

**Issue by secustor** [grafana/grafana#27314] opened 2020-09-01 15:12 UTC
**What would you like to be added**:
Allow to set `Grafana Admin` as it is already possible to set Viewer, Editor and Admin for the organizations.    
This roles should be synchronized using the AzureAD functionality as described in this [guide](https://grafana.com/docs/grafana/latest/auth/azuread/)

**Why is this needed**:
We are operating our Grafana at the moment stateless, stateless as we have everything in K8 objects defined and don't allow dashboard creation on the production instance.     
The single thing we can not define externally at the moment are the Grafana Admins.

**Comment by marefr** [comment] 2020-10-06 22:27
Duplicate of #23473

**Comment by marefr** [comment] 2020-10-06 22:28
Maybe not exactly like referenced issue, but solving that would include a solution for Grafana Admin similar to what we have for LDAP grouo mapping.

**Closed by marefr** 2020-10-06 22:28 UTC
Labels: needs investigation
