### ISSUE TITLE
A11y - follow up: make slider for time range accessible (query history tab)

### ISSUE THREAD

**Issue by L-M-K-B** [grafana/grafana#53776] opened 2022-08-16 13:05 UTC
Follow up from issue [#46477](https://github.com/grafana/grafana/issues/46477)
Solves issue [#46480](https://github.com/grafana/grafana/issues/46480)

The [slider](https://github.com/grafana/grafana/blob/480056d98e78dc5040fcd6f1f40211518399efdd/packages/grafana-ui/src/components/Slider/RangeSlider.tsx) is a component in grafana-ui which is created by using an external library ([rc-slider](https://www.npmjs.com/package/rc-slider)). In storybook it is fully accessible. 
In [RichHistoryQueriesTab.tsx](https://github.com/grafana/grafana/blob/480056d98e78dc5040fcd6f1f40211518399efdd/public/app/features/explore/RichHistory/RichHistoryQueriesTab.tsx) `updateFilters()` is called `onAfterChange` which blocks the a11y of the slider in this case (nothing happens when space or return key are being pressed, pressing arrow right or arrow down causes re-rendering of query list). Why?

There is a newer version available for rc-slider. Does it make sense to update?

**Comment by juliopiubello** [comment] 2022-08-23 12:34
Hi @L-M-K-B , hope you are doing well 

the goal here would be just updating the rc-slider or any other action further?

**Comment by L-M-K-B** [comment] 2022-09-06 07:46
Updating won't help as it brings some other issues with it. I have to look into the function which is called onAfterChange as it's causing the weird behaviour.

**Comment by ifrost** [comment] 2022-10-26 08:05
Closing as a duplicate of #46480

**Closed by ifrost** 2022-10-26 08:05 UTC
Labels: type/bug, prio/medium, area/explore, area/frontend, type/accessibility
