### ISSUE TITLE
Scrolling still broken on mobile

### ISSUE THREAD

**Issue by scanlime** [grafana/grafana#26684] opened 2020-07-30 01:14 UTC
**What happened**:

Scrolling has been broken for me on mobile for a while now; i saw that some recent changes attempted to fix this, but I'm still having trouble both on Chrome and Firefox for Android.

**What you expected to happen**:

When I touch and drag, the page should scroll vertically. Instead, there is usually no response to a drag aside from the tooltip appearing at the touch location, and sometimes a panel changes places. It seems like there is a brief time window after loading when scrolling may work properly.

**How to reproduce it (as minimally and precisely as possible)**:

Load any dashboard on my phone... Android Pixel3a, Chrome or Firefox, tried several types of dashboards, all have this issue.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian
- User OS & Browser: Chrome on Android, Firefox on Android
- Grafana plugins: clock, discrete, image render
- Others:

**Comment by torkelo** [comment] 2020-07-30 05:50
Unable to replicate on iOS and chrome or Safari , will try to get someone to test on android

**Comment by zoltanbedi** [comment] 2020-07-30 08:57
I was also unable to replicate in chrome for Android.

**Comment by zoltanbedi** [comment] 2020-07-30 08:59
@scanlime is scrolling works for you in https://play.grafana.org/ ?

**Comment by scanlime** [comment] 2020-07-30 12:55
> @scanlime is scrolling works for you in https://play.grafana.org/ ?

I'm seeing the same problem there, both on Chrome and Firefox for Android.

**Comment by scanlime** [comment] 2020-07-31 13:00
This seems to be related to the "Display Size" system-wide preference. I usually run with it set to "small" where the scrolling is broken. I tried "larger" and scrolling works, but i really won't change my screen resolution permanently.

**Comment by zoltanbedi** [comment] 2020-07-31 15:56
Thanks for your input @scanlime. I'm going to close this issue as duplicate of #25360 I think it is pretty much the same.

**Closed by zoltanbedi** 2020-07-31 15:56 UTC
Labels: needs more detail
