### ISSUE TITLE
[Question] Get max value of certain field

### ISSUE THREAD

**Issue by jacopobalocco** [grafana/grafana#14044] opened 2018-11-13 09:59 UTC
Hello, I would like to create a variable in my dashboard with the last value of a certain timestamp field. In Elasticsearch the query for this would be: 

{"size":1,
 "sort":[{"EventTimestamp":{"order":"desc"}}],
 "query":{"term":{"OperationsEventType":"EndCampaign"}}}

Is there a way to do this using Template Variables? I would use this value to filter time range within my dashboard. I would expect something like this to work:

![image](https://user-images.githubusercontent.com/17435350/48405220-2af6d280-e732-11e8-8724-66a34c7b5345.png)

But I get an error from grafana:
Template variables could not be initialized: Cannot read property 'then' of undefined

![image](https://user-images.githubusercontent.com/17435350/48405372-73ae8b80-e732-11e8-92f0-fc138f8f2fe8.png)

I am using grafana 5.3.2, on an Elasticsearch datasource, running grafana on Linux Ubuntu 18.04 LTS. 

Many thanks for your help!

**Comment by jacopobalocco** [comment] 2018-11-13 10:02
It would also be ok for me to achieve this using a value aggregation like "max". Notice that it is also important to have the filter for "OperationsEventType". Thank you!

**Comment by marefr** [comment] 2018-11-13 10:10
Sorting in template variable query is currently not supported, see [documentation](http://docs.grafana.org/features/datasources/elasticsearch/#query-variable).

**Comment by marefr** [comment] 2018-11-13 10:10
Duplicate of #4748

**Closed by marefr** 2018-11-13 10:10 UTC
