### ISSUE TITLE
[Bug] Unable to remove Grafana Admin permissions

### ISSUE THREAD

**Issue by williamlord** [grafana/grafana#8759] opened 2017-07-02 11:43 UTC
Regression of https://github.com/grafana/grafana/issues/2143.

Grafana v4.3.2 (commit: ed4d170)

**Comment by torkelo** [comment] 2017-08-08 14:24
fixed/dupe of https://github.com/grafana/grafana/issues/8977

**Closed by torkelo** 2017-08-08 14:24 UTC
Labels: comp: admin/user, type: bug
