### ISSUE TITLE
The table plug-in cannot be distributed

### ISSUE THREAD

**Issue by hjun881** [grafana/grafana#26772] opened 2020-08-04 02:08 UTC
**What would you like to be added**:

Table plug-in to achieve pagination, search function

**Why is this needed**:

Table (old) has the function, but the table after grafana 7.0 has no paging function. The table often needs pagination for a long time

**Comment by torkelo** [comment] 2020-08-04 05:44
distributed? 

closing as dupe of https://github.com/grafana/grafana/issues/26022

**Closed by torkelo** 2020-08-04 05:44 UTC
