### ISSUE TITLE
Table headings do not word wrap

### ISSUE THREAD

**Issue by m2b** [grafana/grafana#7840] opened 2017-03-15 14:11 UTC
Using grafana 4.1.1.  Elastic search 5.2.   
<img width="718" alt="screen shot 2017-03-15 at 7 08 38 am" src="https://cloud.githubusercontent.com/assets/773233/23952400/9fe7de86-094e-11e7-904b-7bb16345f5dc.png">

**Comment by torkelo** [comment] 2017-03-15 14:42
duplicate of https://github.com/grafana/grafana/issues/4157

**Closed by torkelo** 2017-03-15 14:42 UTC
