### ISSUE TITLE
Sending Wrong data while alerting

### ISSUE THREAD

**Issue by suresh447** [grafana/grafana#16246] opened 2019-03-27 09:35 UTC
**What happened**: Grafana is sending wrong data while alerting.i configured alert for error logs of one application means it is sending remaining application error logs as well 
For Example i configured error logs for one of my application please find the below screen shot
![image](https://user-images.githubusercontent.com/33586664/55063786-c08e6100-5046-11e9-8681-bfa5fb64d538.png)
 
But while alerting it is sending notification like below

![image](https://user-images.githubusercontent.com/33586664/55064262-a7d27b00-5047-11e9-8766-21e5a9fcd238.png)
 In the above image kube-system **kubernetes-dashboard-dfbbfd8-cw6fg** is not belonging to that configured application.
 
Similarly for VM Logs if i configured alerts for error logs for one VM it is sending notifications for other VM error logs. see below
 configuration  
![image](https://user-images.githubusercontent.com/33586664/55064801-9b9aed80-5048-11e9-981a-f53246e2f2a7.png)

it is sending the notification like this 
![image](https://user-images.githubusercontent.com/33586664/55064891-cab15f00-5048-11e9-8e8b-a4a63d37e26a.png)

**What you expected to happen**:
I need grafana has to send right alert for error logs for that particular application and also it has to send right error log alert to right VM. It should not send all remaining VM's alert
**Anything else we need to know?**:

**Environment**: 
- Grafana version: 5.4.2
- Data source type & version: Elasticsearch,Prometheus
- OS Grafana is installed on:Ubuntu 16
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: worldping
- Others:

**Comment by marefr** [comment] 2019-03-27 17:06
@suresh447 You're using ad-hoc filters to filter your data which is not supported in alerting scenario.

**Comment by marefr** [comment] 2019-03-27 17:07
Sort of duplicate of #6230

**Closed by marefr** 2019-03-27 17:06 UTC
