### ISSUE TITLE
Contact Point: View notification health

### ISSUE THREAD

**Issue by hieunguyen847** [grafana/grafana#69885] opened 2023-06-12 02:25 UTC
### 
# What went wrong?

**What happened**:

  - Contact Point does not show the health column after Grafana upgrade from 8.5.x to 9.2.7.

**What did you expect to happen**:

  - It should show the column as Grafana v9 release.

### 
# How do we reproduce it?

- Upgrading Grafana 8.5 --> 9.2.7

### 
# What Grafana version are you using?

v9.2.7

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Kubernetes

### Is this a Regression?

None

**Comment by tonypowa** [comment] 2023-06-12 15:29
hi @hieunguyen847 
thank you for creating this issue

are you provisioning those contact points?
if so, please try to reload the configuration files via the following API endpoint;

`/api/admin/provisioning/alerting/reload` 

https://grafana.com/docs/grafana/latest/developers/http_api/admin/#reload-provisioning-configurations

**Comment by hieunguyen847** [comment] 2023-06-16 07:49
> hi @hieunguyen847 thank you for creating this issue
> 
> are you provisioning those contact points? if so, please try to reload the configuration files via the following API endpoint;
> 
> `/api/admin/provisioning/alerting/reload`
> 
> https://grafana.com/docs/grafana/latest/developers/http_api/admin/#reload-provisioning-configurations

Hi @tonypowa ,
Those contact point had created through UI.

**Comment by armandgrillet** [comment] 2023-06-16 08:37
Hi @hieunguyen847 , a few questions:
- Which Alertmanager are you using? Grafana? A Prometheus one?
- Can you share a screenshot of the before/after or just the after?

We can see the health of the contact points of Grafana managed contact points:

![Image](https://github.com/grafana/grafana/assets/2117580/2c645b53-7d1c-45c8-985f-f75dcb69945d)

There should be no regression though thus please give us more details so that we can investigate.

**Comment by hieunguyen847** [comment] 2023-06-19 02:59
> Which Alertmanager are you using? Grafana? A Prometheus one?

All alerts we use on Grafana side.

> Can you share a screenshot of the before/after or just the after?

I confirmed that at Grafana managed Contact Point I see only 3 columns named: **Contact point name**, **Type**, and **Actions** which always as it before, no health column is shown.
FYI: I upgraded Grafana from 7.5.x to 8.5.x to use Grafana Alerting, after using for a while I decided to upgrade to v9.2.7 for a major alerting, another functionality, and expected that is for a contact point improvement.

Another issue there are some unused contact point that I'm unable to delete them after upgaded. The issue says:
`Contact point cannot be deleted because it is used in more policies. Please update or delete these policies first.`

**Comment by armandgrillet** [comment] 2023-06-23 17:01
Thank you for your feedback, one last question: are you using Grafana in High Availability mode? For the second issue, are you editing the right org? Have you checked your root policy as well?

**Comment by hieunguyen847** [comment] 2023-06-30 15:14
>  are you using Grafana in High Availability mode?
No.
> are you editing the right org?
Yes. We are using only org main by default.
> Have you checked your root policy as well?
Yes.

**Comment by armandgrillet** [comment] 2023-07-28 08:48
This is an interesting issue. There is some logic making the health column visible or not thus this could happen: https://github.com/grafana/grafana/blob/7406c4ff5141f410a4935cb4dbf86c587516ee59/public/app/features/alerting/unified/components/receivers/ReceiversTable.tsx#L445

This is hard to debug without knowing what is in the database. This could be due to the Alertmanager configuration containing a contact point that is not well configured making the endpoint returning the health of the contact points fails. That error should be seen from the logs, can you check?

There is a new view for contact points coming in Grafana 10.2 that could fix the issue: https://github.com/grafana/grafana/pull/72444

**Comment by armandgrillet** [comment] 2024-02-07 10:16
This should work in Grafana 10.X when using Grafana managed alerts, closing as we see it works in these newer versions.

**Closed by armandgrillet** 2024-02-07 10:16 UTC
Labels: area/alerting, needs investigation
