### ISSUE TITLE
Legend Data Bytes (IEC/Metric) does not honour decimals

### ISSUE THREAD

**Issue by logopk** [grafana/grafana#25006] opened 2020-05-22 07:59 UTC
**What happened**:
Legend for Filesystem Sizes has 6 decimals and occupies a lot of space
**What you expected to happen**:
Legend for Filesystem Sizes used to have only 2 Decimals (as specified)

**How to reproduce it (as minimally and precisely as possible)**:
Panel with byte-sizes, add legend with min,max,avg
 
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser: MacOS, Safari
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2020-05-22 08:43
duplicate of https://github.com/grafana/grafana/issues/24823

**Closed by torkelo** 2020-05-22 08:43 UTC
