### ISSUE TITLE
Thresholds not applying to columns with mixed data types

### ISSUE THREAD

**Issue by stevencole2305** [grafana/grafana#64308] opened 2023-03-07 12:22 UTC
**Upgraded from 8.0.6 to 9.4.3**:

**Previously Each cell within each threshold changed to the relevant colour for the columns 1/7 - 1/6.
E.g. <=79 - Red, 80-84 - Orange, >85 - Green**:

**Create Columns with mixed data types and apply number thresholds**:

**This worked in 8.* but not in 9.* **:

**Environment**:
- Grafana version:9.4.3
- Data source type & version:SQL Server
- OS Grafana is installed on: WIndows 2016
- User OS & Browser: Chrome / Edge
- Grafana plugins: Table
- Others:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/12542746/223420048-00bc7300-6c29-46d6-834a-9258f69c222f.png">
<img width="159" alt="image" src="https://user-images.githubusercontent.com/12542746/223420206-d639a3cc-f3f1-4630-ad32-da113d50ecbe.png">
<img width="158" alt="image" src="https://user-images.githubusercontent.com/12542746/223420286-1d02b5e1-88e5-47a0-bea7-0d8d3baabecf.png">
<img width="158" alt="image" src="https://user-images.githubusercontent.com/12542746/223420337-e8dc6975-f141-4bb4-9a96-6d3b689afaec.png">

**Comment by tonypowa** [comment] 2023-03-10 09:46
:wave: Thanks for creating this issue, @stevencole2305 


could you please copy and paste all relevant data using the panel --> more --> get help workflow in the panel's dropdown menu? This will help up mock up your data and reproduce your issue. It is important to our teams that issues get verified as reproducible before we formally mark them as bugs. Thank you!

here are more details and steps for copying your data over to this issue:
https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/

**Comment by stevencole2305** [comment] 2023-03-10 09:53
| Key | Value |
|--|--|
| Panel | table @ 9.4.3 |
| Grafana | 9.4.3 (cf0a135595) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "description": "",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": "center",
            "cellOptions": {
              "type": "color-background",
              "mode": "gradient"
            },
            "inspect": false,
            "filterable": false,
            "width": 85
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "text",
                "value": null
              },
              {
                "color": "red",
                "value": 0
              },
              {
                "color": "#EAB839",
                "value": 80
              },
              {
                "color": "green",
                "value": 85
              }
            ]
          },
          "color": {
            "mode": "thresholds"
          },
          "noValue": "-"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "KPI"
            },
            "properties": [
              {
                "id": "custom.width",
                "value": 470
              },
              {
                "id": "color",
                "value": {
                  "mode": "fixed"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "Target"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.width",
                "value": 71
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "YTD Average"
            },
            "properties": [
              {
                "id": "custom.width",
                "value": 102
              },
              {
                "id": "thresholds",
                "value": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "text",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 0.0001
                    },
                    {
                      "color": "#EAB839",
                      "value": 80
                    },
                    {
                      "color": "green",
                      "value": 85
                    }
                  ]
                }
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "showHeader": true,
        "footer": {
          "show": false,
          "reducer": [
            "sum"
          ],
          "countRows": false,
          "fields": ""
        },
        "sortBy": []
      },
      "pluginVersion": "9.4.3",
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "executedQueryString": "SELECT\n  --DATEDIFF(second, '1970-01-01', id) AS time,\n  [KPI]\n      ,[Target]\n      ,[1/7]\n      ,[1/8]\n      ,[1/9]\n      ,[1/10]\n      ,[1/11]\n      ,[1/12]\n      ,[1/1]\n      ,[1/2]\n      ,[1/3]\n      ,[1/4]\n      ,[1/5]\n      ,[1/6]\n      ,CASE\n         WHEN COALESCE([1/7]\n      ,[1/8]\n      ,[1/9]\n      ,[1/10]\n      ,[1/11]\n      ,[1/12]\n      ,[1/1]\n      ,[1/2]\n      ,[1/3]\n      ,[1/4]\n      ,[1/5]\n      ,[1/6]) IS NOT NULL THEN \n         ( COALESCE(case when IsNumeric([1/7]) = 1\n       then [1/7]\n       else 0 end, 0) + \n\t\t COALESCE(case when IsNumeric([1/8]) = 1\n       then [1/8]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/9]) = 1\n       then [1/9]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/10]) = 1\n       then [1/10]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/11]) = 1\n       then [1/11]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/12]) = 1\n       then [1/12]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/1]) = 1\n       then [1/1]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/2]) = 1\n       then [1/2]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/3]) = 1\n       then [1/3]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/4]) = 1\n       then [1/4]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/5]) = 1\n       then [1/5]\n       else 0 end, 0) +\n\t\t COALESCE(case when IsNumeric([1/6]) = 1\n       then [1/6]\n       else 0 end, 0)) / \n            (CASE WHEN [1/7] IS NULL THEN 0 ELSE 1 END + \n             CASE WHEN [1/8] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/9] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/10] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/11] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/12] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/1] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/2] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/3] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/4] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/5] IS NULL THEN 0 ELSE 1 END +\n\t\t\t CASE WHEN [1/6] IS NULL THEN 0 ELSE 1 END)\n             \n       END AS 'YTD Average'\n  FROM [IT].[dbo].[KPI HEADER_v2]\n  order by ID"
                },
                "fields": [
                  {
                    "name": "KPI",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "Tvhvsb",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/7",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/8",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/9",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/10",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/11",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/12",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/1",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/2",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/3",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/4",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/5",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "1/6",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "YTD Ahzqnsw",
                    "type": "number",
                    "typeInfo": {
                      "frame": "int64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "Helpdesk - Critical Operational tickets not responded to within 24hrs",
                    "Operational Failure / Count",
                    "Helpdesk - Critical User tickets not responded to within 1 working day",
                    "Critical User Response Failure / Count",
                    "Helpdesk - Critical User tickets not resolved within 2 working days",
                    "Critical User Resolve Failure / Count",
                    "Helpdesk - Major tickets not responded to within 1 working day",
                    "Major Response Failure / Count",
                    "Helpdesk - Major tickets not resolved within 3 working days",
                    "Major Resolve Failure / Count",
                    "Helpdesk - Moderate tickets not responded to within 3 working days",
                    "Moderate Response Failure / Count",
                    "Helpdesk - Moderate tickets not resolved within 10 working days",
                    "Moderate Resolve Failure / Count",
                    "Helpdesk - Minor tickets not responded to within 5 working days",
                    "Minor Response Failure / Count",
                    "Helpdesk - Minor tickets not resolved within 20 working days",
                    "Minor Resolve Failure / Count",
                    "Helpdesk - Question tickets not responded to within 10 working days",
                    "Question Response Failure / Count",
                    "Helpdesk - Question tickets not resolved within 40 working days",
                    "Question Resolve Failure / Count",
                    "Helpdesk - New User tickets not responded to within 3 working days",
                    "New User Response Failure / Count",
                    "Helpdesk - New User/Equipment tickets not resolved within 40 working days",
                    "New User Resolve Failure / Count",
                    "Tickets Logged With No Priority"
                  ],
                  [
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    85,
                    null,
                    0
                  ],
                  [
                    "67",
                    "1/3",
                    "58",
                    "3/7",
                    "72",
                    "2/7",
                    "79",
                    "6/29",
                    "86",
                    "4/29",
                    "75",
                    "3/12",
                    "100",
                    "0/12",
                    "74",
                    "4/15",
                    "100",
                    "0/15",
                    "94",
                    "1/17",
                    "100",
                    "0/17",
                    "54",
                    "7/15",
                    "94",
                    "1/15",
                    "36 "
                  ],
                  [
                    "100",
                    "0/0",
                    "100",
                    "0/2",
                    "100",
                    "0/2",
                    "72",
                    "6/21",
                    "81",
                    "4/21",
                    "75",
                    "1/4",
                    "100",
                    "0/4",
                    "87",
                    "2/15",
                    "94",
                    "1/15",
                    "93",
                    "1/14",
                    "100",
                    "0/14",
                    "20",
                    "4/5",
                    "80",
                    "1/5",
                    "51 "
                  ],
                  [
                    "100",
                    "0/0",
                    "100",
                    "0/1",
                    "100",
                    "0/1",
                    "31",
                    "9/13",
                    "85",
                    "2/13",
                    "75",
                    "1/4",
                    "100",
                    "0/4",
                    "60",
                    "4/10",
                    "90",
                    "1/10",
                    "67",
                    "3/9",
                    "89",
                    "1/9",
                    "100",
                    "0/3",
                    "100",
                    "0/3",
                    "26 "
                  ],
                  [
                    "100",
                    "2/2",
                    "84",
                    "1/6",
                    "84",
                    "1/6",
                    "45",
                    "10/18",
                    "67",
                    "6/18",
                    "60",
                    "4/10",
                    "60",
                    "4/10",
                    "70",
                    "3/10",
                    "70",
                    "3/10",
                    "50",
                    "5/10",
                    "60",
                    "4/10",
                    "38",
                    "5/8",
                    "50",
                    "4/8",
                    "40 "
                  ],
                  [
                    "67",
                    "1/3",
                    "75",
                    "1/4",
                    "75",
                    "1/4",
                    "77",
                    "4/17",
                    "83",
                    "3/17",
                    "82",
                    "2/11",
                    "82",
                    "2/11",
                    "67",
                    "3/9",
                    "89",
                    "1/9",
                    "85",
                    "3/26",
                    "96",
                    "1/26",
                    "67",
                    "3/9",
                    "100",
                    "0/9",
                    "29"
                  ],
                  [
                    "100",
                    "0/1",
                    "100",
                    "0/2",
                    "100",
                    "0/2",
                    "73",
                    "4/15",
                    "87",
                    "2/15",
                    "100",
                    "0/4",
                    "100",
                    "0/4",
                    "80",
                    "1/5",
                    "80",
                    "1/5",
                    "100",
                    "0/11",
                    "100",
                    "0/11",
                    "33",
                    "2/3",
                    "100",
                    "0/3",
                    "14"
                  ],
                  [
                    "100",
                    "0/0",
                    "64",
                    "4/11",
                    "90",
                    "1/11",
                    "80",
                    "6/30",
                    "87",
                    "4/30",
                    "60",
                    "4/10",
                    "90",
                    "1/10",
                    "100",
                    "0/11",
                    "100",
                    "0/11",
                    "100",
                    "0/22",
                    "100",
                    "0/22",
                    "72",
                    "2/7",
                    "86",
                    "1/7",
                    "43"
                  ],
                  [
                    "100",
                    "0/0",
                    "75",
                    "1/4",
                    "100",
                    "0/4",
                    "95",
                    "1/20",
                    "100",
                    "0/20",
                    "77",
                    "3/13",
                    "93",
                    "1/13",
                    "88",
                    "1/8",
                    "100",
                    "0/8",
                    "100",
                    "0/11",
                    "100",
                    "0/11",
                    "100",
                    "0/3",
                    "100",
                    "0/3",
                    "59"
                  ],
                  [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  [
                    91,
                    0,
                    82,
                    0,
                    90,
                    0,
                    69,
                    0,
                    84,
                    0,
                    75,
                    0,
                    90,
                    0,
                    78,
                    0,
                    90,
                    0,
                    86,
                    0,
                    93,
                    0,
                    60,
                    0,
                    88,
                    0,
                    37
                  ]
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "type": "table"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >table @ 9.4.3</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[mssql]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 15 fields, 27 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.4.3 (cf0a135595) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"type\": \"mssql\",\n    \"uid\": \"_zz8Tsm7k\"\n  },\n  \"description\": \"\",\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"align\": \"center\",\n        \"cellOptions\": {\n          \"type\": \"color-background\",\n          \"mode\": \"gradient\"\n        },\n        \"inspect\": false,\n        \"filterable\": false,\n        \"width\": 85\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"text\",\n            \"value\": null\n          },\n          {\n            \"color\": \"red\",\n            \"value\": 0\n          },\n          {\n            \"color\": \"#EAB839\",\n            \"value\": 80\n          },\n          {\n            \"color\": \"green\",\n            \"value\": 85\n          }\n        ]\n      },\n      \"color\": {\n        \"mode\": \"thresholds\"\n      },\n      \"noValue\": \"-\"\n    },\n    \"overrides\": [\n      {\n        \"matcher\": {\n          \"id\": \"byName\",\n          \"options\": \"KPI\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"custom.width\",\n            \"value\": 470\n          },\n          {\n            \"id\": \"color\",\n            \"value\": {\n              \"mode\": \"fixed\"\n            }\n          }\n        ]\n      },\n      {\n        \"matcher\": {\n          \"id\": \"byName\",\n          \"options\": \"Target\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"color\",\n            \"value\": {\n              \"mode\": \"fixed\"\n            }\n          },\n          {\n            \"id\": \"custom.width\",\n            \"value\": 71\n          }\n        ]\n      },\n      {\n        \"matcher\": {\n          \"id\": \"byName\",\n          \"options\": \"YTD Average\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"custom.width\",\n            \"value\": 102\n          },\n          {\n            \"id\": \"thresholds\",\n            \"value\": {\n              \"mode\": \"absolute\",\n              \"steps\": [\n                {\n                  \"color\": \"text\",\n                  \"value\": null\n                },\n                {\n                  \"color\": \"red\",\n                  \"value\": 0.0001\n                },\n                {\n                  \"color\": \"#EAB839\",\n                  \"value\": 80\n                },\n                {\n                  \"color\": \"green\",\n                  \"value\": 85\n                }\n              ]\n            }\n          }\n        ]\n      }\n    ]\n  },\n  \"gridPos\": {\n    \"h\": 29,\n    \"w\": 24,\n    \"x\": 0,\n    \"y\": 4\n  },\n  \"id\": 2,\n  \"options\": {\n    \"showHeader\": true,\n    \"footer\": {\n      \"show\": false,\n      \"reducer\": [\n        \"sum\"\n      ],\n      \"countRows\": false,\n      \"fields\": \"\"\n    },\n    \"sortBy\": []\n  },\n  \"pluginVersion\": \"9.4.3\",\n  \"targets\": [\n    {\n      \"alias\": \"\",\n      \"datasource\": {\n        \"type\": \"mssql\",\n        \"uid\": \"_zz8Tsm7k\"\n      },\n      \"editorMode\": \"code\",\n      \"format\": \"table\",\n      \"rawQuery\": true,\n      \"rawSql\": \"SELECT\\n  --$__timeEpoch(id),\\n  [KPI]\\n      ,[Target]\\n      ,[1/7]\\n      ,[1/8]\\n      ,[1/9]\\n      ,[1/10]\\n      ,[1/11]\\n      ,[1/12]\\n      ,[1/1]\\n      ,[1/2]\\n      ,[1/3]\\n      ,[1/4]\\n      ,[1/5]\\n      ,[1/6]\\n      ,CASE\\n         WHEN COALESCE([1/7]\\n      ,[1/8]\\n      ,[1/9]\\n      ,[1/10]\\n      ,[1/11]\\n      ,[1/12]\\n      ,[1/1]\\n      ,[1/2]\\n      ,[1/3]\\n      ,[1/4]\\n      ,[1/5]\\n      ,[1/6]) IS NOT NULL THEN \\n         ( COALESCE(case when IsNumeric([1/7]) = 1\\n       then [1/7]\\n       else 0 end, 0) + \\n\\t\\t COALESCE(case when IsNumeric([1/8]) = 1\\n       then [1/8]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/9]) = 1\\n       then [1/9]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/10]) = 1\\n       then [1/10]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/11]) = 1\\n       then [1/11]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/12]) = 1\\n       then [1/12]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/1]) = 1\\n       then [1/1]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/2]) = 1\\n       then [1/2]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/3]) = 1\\n       then [1/3]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/4]) = 1\\n       then [1/4]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/5]) = 1\\n       then [1/5]\\n       else 0 end, 0) +\\n\\t\\t COALESCE(case when IsNumeric([1/6]) = 1\\n       then [1/6]\\n       else 0 end, 0)) / \\n            (CASE WHEN [1/7] IS NULL THEN 0 ELSE 1 END + \\n             CASE WHEN [1/8] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/9] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/10] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/11] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/12] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/1] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/2] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/3] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/4] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/5] IS NULL THEN 0 ELSE 1 END +\\n\\t\\t\\t CASE WHEN [1/6] IS NULL THEN 0 ELSE 1 END)\\n             \\n       END AS 'YTD Average'\\n  FROM [IT].[dbo].[KPI HEADER_v2]\\n  order by ID\",\n      \"refId\": \"A\",\n      \"sql\": {\n        \"columns\": [\n          {\n            \"parameters\": [],\n            \"type\": \"function\"\n          }\n        ],\n        \"groupBy\": [\n          {\n            \"property\": {\n              \"type\": \"string\"\n            },\n            \"type\": \"groupBy\"\n          }\n        ],\n        \"limit\": 50\n      }\n    }\n  ],\n  \"title\": \"SLA Achievement July - June\",\n  \"type\": \"table\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: SLA Achievement July - June // 2023-03-10 09:50:35",
  "tags": [
    "debug",
    "debug-table"
  ],
  "time": {
    "from": "2023-03-10T03:50:35.146Z",
    "to": "2023-03-10T09:50:35.146Z"
  }
}
```
</details>


[debug-SLA Achievement July - June-2023-03-10 09_52_37.json.txt](https://github.com/grafana/grafana/files/10940771/debug-SLA.Achievement.July.-.June-2023-03-10.09_52_37.json.txt)

**Comment by tonypowa** [comment] 2023-03-10 10:17
thank you @stevencole2305 👍 

forwarding issue to the BI squad for review

**Comment by mdvictor** [comment] 2023-03-31 12:29
Hello! Thank you for opening this issue! We will investigate this asap and come back with a resolution as soon as we have one!

**Comment by stevencole2305** [comment] 2023-05-26 11:20
Hello, Is there any update on this, I have updated to the latest version (v9.5.2) and the issue persists

**Comment by torkelo** [comment] 2023-05-26 12:17
Thresholds only apply to numeric values, if you want to color string values you need to use "value mapping"

**Comment by torkelo** [comment] 2023-05-26 12:19
If I test the debug / help dasboard every row for the last column has a color (include 0)
![image](https://github.com/grafana/grafana/assets/10999/349ae7bd-4522-4fb0-bcf3-7ffbd75e98c7)

**Comment by stevencole2305** [comment] 2023-05-31 13:30
Hi torkelo,

The end column is working as expected, the issue is with the columns such as 1/2

The row values under this heading would be as follows:
100 would be green
0/0 would be grey
75 would be red
1/4 would be grey and so on,

This has only changed since updating from v8 to v9 so I wouldn't understand how functionality that was available and working would now be removed

**Comment by mdvictor** [comment] 2023-06-27 09:50
Hey @stevencole2305, after looking a bit through this, I believe the functionality was not removed but tweaked a bit. Since there are string values present (e.g: `1/4`), the entire column will be treated as string and excluded from proper threshold coloring. 

To get the same results as in the previous version, try setting the `Standard option > Unit` to `Number`, which will then manage to apply threshold colors as per the numeric values, while leaving the other values to the base threshold color, as per your example above.

**Comment by codeincarnate** [comment] 2024-01-11 02:51
Per the above comment it appears that this wasn't so much as bug as a change in behavior, and a seemingly sensible change at that! Going to close this but feel free to re-open if there are more details that would impact this.

**Closed by codeincarnate** 2024-01-11 02:51 UTC
Labels: area/panel/table
