### ISSUE TITLE
Undo doesn't work in explore with Prometheus

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#24730] opened 2020-05-15 10:51 UTC
I accidentally typed the wrong thing, and ctrl-z (or cmd-z on a mac) didn't undo it.

Version Grafana v7.1.0-91219227pre (bd42407620)

**Comment by Mario-Hofstaetter** [comment] 2020-05-15 18:44
Possible duplicate to #24137

**Comment by zoltanbedi** [comment] 2020-05-15 19:23
Hi Tom, thanks for reporting, it is indeed a duplicate of #24137 as Mario said so I'm closing this now.

**Closed by zoltanbedi** 2020-05-15 19:23 UTC
Labels: area/explore, type/bug
