### ISSUE TITLE
Allow variables as Graph Threshold input

### ISSUE THREAD

**Issue by RishoT17** [grafana/grafana#34056] opened 2021-05-13 13:12 UTC
**What would you like to be added**:
I'd like to be able to control the graph threshold with a URL variable.

**Why is this needed**:
We use URL variables to dynamically populate data in queries that get displayed in Graph visualisation. One dashboard is used to display different data series - for example FPS, or loading time. The data series to be displayed is chosen based on a URL variable.

Different data series can have different thresholds. However, there is currently no way to set the graph threshold based on a variable. The only allowed input type is number.

![image](https://user-images.githubusercontent.com/84135434/118130440-43283500-b3f5-11eb-958c-b610592c4039.png)

**Comment by torkelo** [comment] 2021-05-13 13:51
duplicate of https://github.com/grafana/grafana/issues/159

**Closed by torkelo** 2021-05-13 13:51 UTC
