### ISSUE TITLE
Legend on chart - lines

### ISSUE THREAD

**Issue by drix1994** [grafana/grafana#11901] opened 2018-05-10 09:41 UTC
Please include this information:
### What Grafana version are you using?
5.1.2
### What datasource are you using?
MySQL
### What OS are you running grafana on?
Redhat 7
### What did you do?
nothing speciall, I made dashboard with two charts, legend as table, on right side and with dynamic width.
### What was the expected result?
In Firefox after refresh, zoom or something. Only labels from the legend overlaps the graph. Piece after piece. Screenshot:
![image](https://user-images.githubusercontent.com/30824428/39863423-e5033e04-5446-11e8-8576-6f2b9d9c2c40.png)
After setting the width, the problem disappears, but i want to set width dynamically.

**Comment by retzkek** [comment] 2018-05-10 15:29
Yep we're seeing the same behavior in Firefox, the legend "expands" every time the mouse enters or leaves the panel. Chrome is not affected.

**Comment by drix1994** [comment] 2018-05-11 12:05
The same problem is with sliders. In Chrome they are nice but in firefox they are terrible.

**Comment by daniellee** [comment] 2018-05-14 08:55
Duplicate of #11830

**Closed by daniellee** 2018-05-14 08:55 UTC
Labels: type: duplicate
