### ISSUE TITLE
v7 Stat & Gauge panel not respecting "Display Name" for graphite queries

### ISSUE THREAD

**Issue by cartw** [grafana/grafana#25212] opened 2020-05-29 11:20 UTC
**What happened**:
A dashboard imported/migrated from v6 contains stat panels where I would set the Panel Title (under general) to nothing and set the "Title" in the visualiation settings to a string.  
In v7 this setting is now called "Display Name" but any string I enter is ignored and the full metric target string is used as the title, which generally makes it unreadable when not in edit view. If the display name field is set to none then nothing is shown, but otherwise it only ever shows the metric target.  
e.g. here I typed "uptime" in the display name field, but the panel is using maxSeries(logstash.stats.nodes.ops_logstash_1.jvm.uptime)
![image](https://user-images.githubusercontent.com/41674477/83253244-93869280-a1a4-11ea-8654-ac46c599cb46.png)
This seems to only be broken for graphite datasource.

**What you expected to happen**:
I expected the display name to be used as the panel text rather than the metric target string. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a Stat panel with a graphite datasource. Add a metric query. Under the panel options enter text in the "Display Name" field. The panel then updates with the metric target string rather than the diaplay name entered. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: graphite 9.x
- OS Grafana is installed on: Ubuntu 16.04 
- User OS & Browser: MacOS 10.15.4
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment] 2020-05-29 14:20
thanks for reporting this! use an override rule as temporary work around

**Comment by torkelo** [comment] 2020-05-29 15:56
@ryantxu this is a bit of a tricky one, since prometheus & Graphite now set field.config.displayName from the data source, this overrides default Display name set in the Field tab making it in-effective for these data sources

**Comment by mertbakir** [comment] 2020-07-17 16:06
@torkelo I didn't want to open a new issue since these are similar but it happened to me after 7.1.0. Everything was fine with the previous version 7.0.6.

Here it should display the $http_name variable yet it's blank. I've tried with ${__field.name} and with arbitrary text, still no luck. 

![image](https://user-images.githubusercontent.com/43188411/87806938-49469700-c860-11ea-8188-41360b4c3b60.png)

**Comment by ryantxu** [comment] 2020-07-17 16:10
@mertbakir -- can you try the new 7.1 setting for the text mode?
![image](https://user-images.githubusercontent.com/705951/87807637-571efc80-c80d-11ea-9834-9d793bfa6b87.png)

when there is only one metric, the "Auto" behavior does not show the name

**Comment by mertbakir** [comment] 2020-07-17 16:15
@ryantxu Oh, thanks. 👍

**Comment by ryantxu** [comment] 2020-07-21 16:05
FYI, as a workaround, you can also set the display name as an override.  The issue here is that the "fields" section is really "field defaults" and believes what the datasource returns for field config.  To get the graphite naming structure to look OK, we stuck the name in the same slot and that overrides whatever you ender

**Comment by cartw** [comment] 2020-07-22 11:40
For graphite queries you can also just explicity set an `alias()`. However these workarounds are only good for a single panel. The reason I opened the issue is because if I migrate my many (many) existing dashboards to grafana 7 I need to edit an awful lot of panels to make them look right again. So a proper fix sometime would avoid that pain.

**Comment by yesoreyeram** [comment] 2020-07-30 21:35
I can confirm that the display name field not respected when migrating from 6.x to 7.1.1 ( Datasource Azure )

Before 
![image](https://user-images.githubusercontent.com/153843/88976946-e1a73780-d2b4-11ea-9bd8-b6d4b10dd483.png)

After
![image](https://user-images.githubusercontent.com/153843/88976977-ebc93600-d2b4-11ea-9f1a-5937db1a2985.png)

**Comment by mertbakir** [comment] 2020-07-30 21:39
> I can confirm that the display name field not respected when migrating from 6.x to 7.1.1 ( Datasource Azure )
> 
> Before 
> ![image](https://user-images.githubusercontent.com/153843/88976946-e1a73780-d2b4-11ea-9bd8-b6d4b10dd483.png)
> 
> After
> ![image](https://user-images.githubusercontent.com/153843/88976977-ebc93600-d2b4-11ea-9f1a-5937db1a2985.png)
> 
> 

Try to use "Value and Name" display option, it shows only the value as a default when there is only 1 series to display. See a few comments back.

**Comment by yesoreyeram** [comment] 2020-07-30 21:48
Yea I understand that i can do that. But it was not handled automatically while migration. As a end user, I don't want spend time analyzing the issue nor converting hundreds of panels manually. This regression should have been handled through migration scripts in some way.

**Comment by torkelo** [comment] 2020-07-31 05:16
We are working on a fix for this

**Closed** 2020-08-28 16:22 UTC
Labels: area/frontend, area/panel/stat, datasource/Graphite, needs investigation, priority/support-subscription, type/bug
