### ISSUE TITLE
Alert: the function percent_diff() is always positive

### ISSUE THREAD

**Issue by AsherXian903** [grafana/grafana#21252] opened 2019-12-24 09:20 UTC
**What happened**:
Alert: the function percent_diff() result is always positive

**What you expected to happen**: 
expect percent_diff() function to support negative result

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.5.2
- Data source type & version:Prometheus
- OS Grafana is installed on:CentOS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by AsherXian903** [comment] 2019-12-24 09:22
It's really inconvenient to use, hope will solve this issue soon, thanks, Merry Christmas!

**Comment by vikkyomkar** [comment] 2019-12-26 19:00
looks like the formula percent_diff() function using is different from the defined formula
https://github.com/grafana/grafana/blob/master/pkg/services/alerting/conditions/reducer.go#L158
Defined formula:
Percentage Difference = | First Value − Second Value|/(First Value + Second Value)/2 | × 100%

**Comment by hugohaggmark** [comment] 2019-12-27 04:47
Duplicate of #16270

**Closed by hugohaggmark** 2019-12-27 04:47 UTC
