### ISSUE TITLE
Check: adding new query when mixed data sources are disabled (it added test data source)

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#60199] opened 2022-12-12 20:58 UTC
When adding a new query to explore, first check the root datasource of the page. If it's not mixed, the datasource of that query should be that datasource.

If it is mixed, it should be the datasource of the last query.

**Comment by meanmina** [comment] 2023-01-09 13:07
As part of resolving this issue we should also add tests around addQueryRow() logic and also generateEmptyQuery() as the lack of has introduced some risk.

**Comment by ifrost** [comment] 2023-01-16 14:05
@L-M-K-B please create a new issue just for adding tests and close this one because it's not a bug anymore (we couldn't reproduce it).

**Closed** 2023-01-17 11:49 UTC
Labels: type/bug, prio/medium, area/explore
