### ISSUE TITLE
[feature request] make $__range available for elastic search data source

### ISSUE THREAD

**Issue by kccheung** [grafana/grafana#14925] opened 2019-01-17 10:20 UTC
I am creating a date histogram chart where the group by EVENT TIME clause interval needs to be set as the current time range, i.e. the $__range variable provided for prometheus data source. Now I need to set it to a very large duration, e.g. 7d, but this may cause "data points outside time range group by interval" appeared on screen.

![screen shot 2019-01-17 at 18 19 23](https://user-images.githubusercontent.com/1140487/51311768-9a67a600-1a84-11e9-84ae-cd205319163f.png)

**Comment by marefr** [comment] 2019-01-17 11:40
Duplicate of #13238

**Closed by marefr** 2019-01-17 11:40 UTC
