### ISSUE TITLE
Table Panel : Ability to filter rows by column value.

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#3956] opened 2016-02-07 17:15 UTC
Feature Request.

Built Grafana from source for Mac. (http://docs.grafana.org/project/building_from_source/)
Data source: Influx DB
Panel : Table

I am able to see see a table panel with few rows and columns. As the size of table increases fetching rows for a given column value becomes tedious and requires navigating through pages.

Would be nice if there is a text box below each column at bottom of table (above pagination links) that allows to filter rows based on the value entered in the text box.

**Comment by torkelo** [comment] 2016-02-07 17:39
you can use template variables and add those to your influxdb query to dynamically filter values in a table panel. 

dupe of https://github.com/grafana/grafana/issues/3919

**Closed by torkelo** 2016-02-07 17:39 UTC

**Comment by holgerbrandl** [comment] 2019-10-02 07:57
I understand the variables, but column filters are imho an independent drill-down mechanism. E.g. the user may want to quickly narrow down a particual table without changing the compelte dashboard configuration. See https://rstudio.github.io/DT/ (section 2.8) for a nice implementation.
