### ISSUE TITLE
Increase timeout and retries number for alerting

### ISSUE THREAD

**Issue by SnirX** [grafana/grafana#15211] opened 2019-02-03 14:53 UTC
Hi,
We are using Grafana v5.3.2 on Centos 7.3 machines.
We want to increase alerting timeout and retries number (datasources are Elasticsearch and InfluxDB) due to Slack connectivity issues,
Can we increase that with the configuration?
Didn't find option in docs.

Thank you!

**Comment by daniellee** [comment] 2019-02-04 13:32
This sounds like an alert notifier problem rather than the alert engine. There are a couple of configuration settings for the alert notifier here: http://docs.grafana.org/installation/configuration/#alerting

But what sort of errors are you getting in the Grafana server logs?

Unfortunately, adding more configuration options seems to be marked as [todo](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/engine.go#L107) in the alerting engine but don't think that would help you anyway if the problem is Slack connectivity.

@bergquist any suggestions?

**Comment by bergquist** [comment] 2019-02-05 08:56
In 5.4 we introduced a new setting name `FOR` which introduces alert deboucing which can be used to retry requests more then 3 times before switching state on the alert.

in 6.0 we fixed a bug where both alert queries and alert notifications used the same timeout. 

So once 6.0 stable (end of February) is out you have two improvements that should reduce the need to make these configurable. I'm closing this for now but once you tried 6.0 and this is still a problem, please ping us and we will reopen it.

**Closed by bergquist** 2019-02-05 08:56 UTC
Labels: state: needs more detail
