### ISSUE TITLE
Service Graph filtering by service name does not apper to work correctly

### ISSUE THREAD

**Issue by Starefossen** [grafana/grafana#83967] opened 2024-03-06 08:28 UTC
**Describe the bug**

Using the `service` filter in the Service Graph does not work (there are several reported instances of this on the Grafana Slack).

<img width="1041" alt="Screenshot 2024-03-06 at 09 22 22" src="https://github.com/grafana/tempo/assets/968267/f0552a1f-f40b-4ed1-ac12-eef34fc79d14">

Filtering by either `client` or `server` does work, but not `service`.

<img width="1038" alt="Screenshot 2024-03-06 at 09 25 30" src="https://github.com/grafana/tempo/assets/968267/0b4520d4-afc5-4aa5-8f88-39cab8ca133c">

How is `service` filter supposed to work?

**To Reproduce**
1. Start Tempo
2. Enable Service Graph
3. Add a service filter
 
**Expected behavior**

I expected to get the service graph for the selected service (services).

**Environment:**
 - Infrastructure: Kubernetes / GKE
 - Deployment tool: Helm

**Additional Context**

Tempo Version: v2.3.1 (Helm Chart 1.8.4)
Grafana Version: v10.3.3 (Helm Chart 7.3.3)

Similar issues reported on Slack:
* https://grafana.slack.com/archives/C01D981PEE5/p1702460470166809
* https://grafana.slack.com/archives/C01D981PEE5/p1709134894140339?thread_ts=1709121857.539459&cid=C01D981PEE5
* https://grafana.slack.com/archives/C01D981PEE5/p1709121857539459

**Comment by Starefossen** [comment] 2024-03-06 18:43
Thanks @joe-elliott 🙏🏻 Also regular expression matching `=~` does not appear to be working for any of the filters.

**Comment by aocenas** [comment] 2024-03-11 13:34
This is duplicate of this existing issue: https://github.com/grafana/grafana/issues/80822

**Closed by aocenas** 2024-03-11 13:34 UTC
Labels: area/explore, area/tracing, datasource/Tempo

**Comment by gespi1** [comment] 2024-07-16 14:41
If you want to filter by the name of a service for spanmetrics and service graphs you can  add `service.name` as additional dimensions on the tempo config 

```
metrics_generator:
      processor:
        service_graphs:
          dimensions:
            - service.name
        span_metrics:
          dimensions:
            - service.name
```

The reason the service filter does not work can found in this users [comment](https://github.com/grafana/grafana/issues/80822#issuecomment-1921307778)
