### ISSUE TITLE
Grafana Alert: diff() and percent_diff() still returning absolute value

### ISSUE THREAD

**Issue by djsharp** [grafana/grafana#16562] opened 2019-04-12 21:49 UTC
**What happened**:

Grafana Alert functions diff() and percent_diff() only return absolute values. Negative values (<0) are never returned.

**What you expected to happen**:

When the first value in a data series is > the last value in the series, diff() and percent_diff() should return negative values. For example, if first value = 200 and last value =150, diff() should be -50 and percent_diff should be -25. Currently, 50 and 25 are returned, respectively.

See attached screen shots. Note that regardless of whether the first value Array[0] is > or < the last value Array[9] in the series, the "Value" is always > 0. The math seems to be correct though, in that Value is always the abs_value(first value - last value). Or maybe it is abs_value(last value - first value); I can't tell. The fact that the math is correct indicates issue #9386 is fixed.

**How to reproduce it (as minimally and precisely as possible)**:

Chose a data series where the first value is > the last value.

**Anything else we need to know?**:

The diff() and percent_diff() functions have had several defects filed against them recently: #11563 and #10129. #10129 is very similar to this defect and was supposedly fixed in v5.3. Maybe the fix got lost sometime between 5.3 and 6.1 (where I'm at now)? #9386 also involved these two functions; #9386 seems to be resolved.

**Environment**:
- Grafana version: v6.1.3
- Data source type & version: Graphite (although I don't think this is involved)
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: MacOS 10.14.4/Chrome
- Grafana plugins: n/a
- Others: n/a
![Screen Shot 2019-04-12 at 3 17 28 PM](https://user-images.githubusercontent.com/22942207/56068032-8dccb400-5d3a-11e9-92b7-f414b132500f.png)
![Screen Shot 2019-04-12 at 3 17 08 PM](https://user-images.githubusercontent.com/22942207/56068042-93c29500-5d3a-11e9-9c22-9593746c1f56.png)
![Screen Shot 2019-04-12 at 3 21 37 PM](https://user-images.githubusercontent.com/22942207/56068045-97561c00-5d3a-11e9-99d3-fb47ca84584c.png)

**Comment by torkelo** [comment] 2019-04-14 09:16
dupe of https://github.com/grafana/grafana/issues/10129  and https://github.com/grafana/grafana/issues/16270

**Closed by torkelo** 2019-04-14 09:16 UTC
