### ISSUE TITLE
Internal Server Error when updating datasource via api

### ISSUE THREAD

**Issue by Kirchen99** [grafana/grafana#14338] opened 2018-12-05 12:54 UTC
### What Grafana version are you using?
 v5.3.2
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
kubernetes
### What did you do?
Created a datasource using api:
`curl -X POST -H 'Content-Type: application/json;charset=UTF-8'-s --user user:password 'https://grafana/api/datasources' -d '{"access":"proxy","isDefault":true,"name":"Prometheus","type":"prometheus","url":"http://prometheus:9090"}' | jq`

Received:
```
{
  "datasource": {
    "id": 38,
    "orgId": 1,
    "name": "Prometheus",
    "type": "prometheus",
    "typeLogoUrl": "",
    "access": "proxy",
    "url": "http://prometheus:9090",
    "password": "",
    "user": "",
    "database": "",
    "basicAuth": false,
    "basicAuthUser": "",
    "basicAuthPassword": "",
    "withCredentials": false,
    "isDefault": true,
    "secureJsonFields": {},
    "version": 1,
    "readOnly": false
  },
  "id": 38,
  "message": "Datasource added",
  "name": "Prometheus"
}
```

Then update the Datasource using api:
`curl -X PUT -H 'Content-Type: application/json;charset=UTF-8'-s --user user:password 'https://grafana/api/datasources/38' -d '{"access":"proxy","basicAuth":false,"id":38,"isDefault":true,"name":"Prometheus","type":"prometheus","url":"http://prometheus:9090"}' | jq`

Received:
```
{
  "datasource": {
    "id": 38,
    "orgId": 1,
    "name": "Prometheus",
    "type": "prometheus",
    "typeLogoUrl": "",
    "access": "proxy",
    "url": "http://prometheus:9090",
    "password": "",
    "user": "",
    "database": "",
    "basicAuth": false,
    "basicAuthUser": "",
    "basicAuthPassword": "",
    "withCredentials": false,
    "isDefault": true,
    "secureJsonFields": {},
    "version": 1,
    "readOnly": false
  },
  "id": 38,
  "message": "Datasource updated",
  "name": "Prometheus"
}
```
### What was the expected result?
Nothing happens
### What happened instead?
The datasource can not be used. All Dashboards using the datasource are saying: 
```
Templating init failed
Internal Server Error - Check the Grafana server logs for the detailed error message.
```

And in logs:
```
t=2018-12-05T12:40:50+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname=user method=GET path=/api/datasources/proxy/38/api/v1/query_range status=500 remote_addr=172.18.18.85 time_ms=3 size=122 referer="https://grafana/d/F7Vl_bLik/k8s-deployments?refresh=5s&amp;orgId=1"
t=2018-12-05T12:40:50+0000 lvl=eror msg="Request error" logger=context userId=3 orgId=1 uname=user error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:513 (0x434ed8)\n/usr/local/go/src/runtime/panic.go:82 (0x43402d)\n/usr/local/go/src/runtime/signal_unix.go:390 (0x44adc1)\n/go/src/github.com/grafana/grafana/pkg/components/simplejson/simplejson.go:198 (0xec6a08)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a54)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a54)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a54)\n/usr/local/go/src/net/http/httputil/reverseproxy.go:197 (0xa4d24d)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:99 (0xec64fc)\n/go/src/github.com/grafana/grafana/pkg/api/dataproxy.go:56 (0xf558f1)\n/go/src/github.com/grafana/grafana/pkg/api/api.go:255 (0xf87743)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xb2860c)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xb27f27)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:15 (0xb28911)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb27e40)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x82f200)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x812f20)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x812c8b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xb2583d)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x83faa4)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x83a2ae)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x833821)\n/usr/local/go/src/net/http/server.go:2741 (0x6b1c8a)\n/usr/local/go/src/net/http/server.go:1847 (0x6ae045)\n/usr/local/go/src/runtime/asm_amd64.s:1333 (0x465220)\n"

```

In Datasource -> Prometheus the URL text box is empty and the following message is shown under the URL text box.:
<img width="487" alt="snipping" src="https://user-images.githubusercontent.com/9981745/49515083-2be4d500-f896-11e8-8e39-270678aa29bb.PNG">

After I clicked the Button "Save & Test", the following logs are shown:

```
t=2018-12-05T12:31:04+0000 lvl=eror msg="Request error" logger=context userId=3 orgId=1 uname=user error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:513 (0x434ed8)\n/usr/local/go/src/runtime/panic.go:82 (0x43402d)\n/usr/local/go/src/runtime/signal_unix.go:390 (0x44adc1)\n/go/src/github.com/grafana/grafana/pkg/components/simplejson/simplejson.go:198 (0xec6a08)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a54)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a54)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:163 (0xec8a54)\n/usr/local/go/src/net/http/httputil/reverseproxy.go:197 (0xa4d24d)\n/go/src/github.com/grafana/grafana/pkg/api/pluginproxy/ds_proxy.go:99 (0xec64fc)\n/go/src/github.com/grafana/grafana/pkg/api/dataproxy.go:56 (0xf558f1)\n/go/src/github.com/grafana/grafana/pkg/api/api.go:255 (0xf87743)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_tracing.go:25 (0xb2860c)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/request_metrics.go:17 (0xb27f27)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/session.go:15 (0xb28911)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/recovery.go:146 (0xb27e40)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:79 (0x82f200)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:157 (0x812f20)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:135 (0x812c8b)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:112 (0x82f27e)\n/go/src/github.com/grafana/grafana/pkg/middleware/logger.go:34 (0xb2583d)\n/usr/local/go/src/runtime/asm_amd64.s:522 (0x46350a)\n/usr/local/go/src/reflect/value.go:447 (0x4c0978)\n/usr/local/go/src/reflect/value.go:308 (0x4c0413)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:177 (0x813233)\n/go/src/github.com/grafana/grafana/vendor/github.com/go-macaron/inject/inject.go:137 (0x812b99)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/context.go:121 (0x82f360)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:187 (0x83faa4)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/router.go:303 (0x83a2ae)\n/go/src/github.com/grafana/grafana/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x833821)\n/usr/local/go/src/net/http/server.go:2741 (0x6b1c8a)\n/usr/local/go/src/net/http/server.go:1847 (0x6ae045)\n/usr/local/go/src/runtime/asm_amd64.s:1333 (0x465220)\n"
t=2018-12-05T12:31:04+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname=user method=GET path=/api/datasources/proxy/38/api/v1/query status=500 remote_addr=172.18.18.85 time_ms=1 size=122 referer=https://grafana/datasources/edit/38

```

I can still get the correct datasource Json using api:
`curl -X GET -s --user user:password 'https://grafana/api/datasources/38' | jq`

Received:
```
{
  "id": 38,
  "orgId": 1,
  "name": "Prometheus",
  "type": "prometheus",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://prometheus:9090",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": true,
  "secureJsonFields": {},
  "version": 2,
  "readOnly": false
}
```

**Comment by Kirchen99** [comment] 2018-12-05 12:55
<img width="487" alt="snipping" src="https://user-images.githubusercontent.com/9981745/49514797-6ac65b00-f895-11e8-987f-7b9250a30f2c.PNG">

**Comment by marefr** [comment] 2018-12-05 16:30
Duplicate of #13046

**Closed** 2018-12-05 16:31 UTC
