### ISSUE TITLE
Multi-Series Alert Invalid Format

### ISSUE THREAD

**Issue by nicholas-a-guerra** [grafana/grafana#73852] opened 2023-08-25 15:36 UTC
### What happened?

There is currently a bug where it seems to not possible to have a multi-series alert for PostgreSQL based queries. The exact error can be seen below.

<img width="1411" alt="image" src="https://github.com/grafana/grafana/assets/114434291/989fbef1-f601-4565-be1a-20cbca5e6d8e">

The query itself is successful and shows multiple series of data and the reduce and threshold expressions seem to populate correctly as seen below.

<img width="1388" alt="image" src="https://github.com/grafana/grafana/assets/114434291/9d6562f0-5299-4317-b7a6-45fa5469b91f">

<img width="1335" alt="image" src="https://github.com/grafana/grafana/assets/114434291/e86e4cdb-ea14-4539-a626-9197f1bbe668">

I have reviewed other issues that have indicated that a metric label was the root cause of the same error but in this situation there is no metric column. If the Classic Condition is used instead then the alert does not have this same error, which seems to indicate some specific bug with the reduce and threshold expressions. 

### What did you expect to happen?

It would be expected that this expression combination functions similarly to the Classic Condition.

### Did this work before?

NA

### How do we reproduce it?

1. Generate a multiseries PostgreSQL query alert
2. Use any reduce expression
3. Use any threshold expression

### Environment (with versions)?

Grafana: 10.1.0
OS: Ubuntu 22.04.3 LTS
Browser: NA

### Grafana platform?

Docker

### Datasource(s)?

QuestDB 7.3.1 (queried with PostgreSQL)

**Comment by gelicia** [comment] 2023-08-25 15:53
I took a look at this when the poster first asked in the community slack - a multi series query on the test datasource works fine, but postgres doesn't seem to create labels based on the aliased values. I posted a screenshot of the difference here https://grafana.slack.com/archives/C0Y4TLW74/p1692323775395719 .

**Comment by gabor** [comment] 2023-08-30 12:39
the problem is not really specific to postgres, it seems dataframes with multiple values, where there are no labels involved, do not work well with server-side-expressions, i created a separate issue to track this at https://github.com/grafana/grafana/issues/74108 .

@nicholas-a-guerra unfortunately there's nothing that can be done from the user's side to fix the problem, maybe a workaround would be to track both values separately, in two separate alerts?

**Comment by nicholas-a-guerra** [comment] 2023-08-31 06:52
@gabor Understood, I will separate out all alerts for now. With this breaking what seems to be a normal operation, is there any indication as to when an item like this gets picked from backlog? (just generally curious) Thanks!

**Comment by gabor** [comment] 2024-02-28 13:51
as this is now tracked in https://github.com/grafana/grafana/issues/74108, i'm closing this issue. i recommend following  https://github.com/grafana/grafana/issues/74108 to receive updates.

**Closed by gabor** 2024-02-28 13:51 UTC
Labels: area/alerting, datasource/Postgres, triage/needs-confirmation
