### ISSUE TITLE
Azure Monitor: All subscriptions in the query

### ISSUE THREAD

**Issue by websolut** [grafana/grafana#70083] opened 2023-06-14 15:28 UTC
### 
# What went wrong?

**What happened**:
When one creates a new graph query a random subscription is added to the field 'Subscriptions'. When this subscription is deleted the interface implies all the subscriptions are selected and the query results reflect this. We can save the dashboard and it works correctly - querying data from all the subscriptions.

As soon as you click 'edit' this panel next time - that random subscription is added again automatically. So we have to delete it and save.

**What did you expect to happen**:

When running a graph query we should be able to avoid selecting individual subscriptions as new one maybe added etc. thus an option for all the subscriptions should be available.

### 
# How do we reproduce it?

When one creates a new graph query a random subscription is added to the field 'Subscriptions'. When this subscription is deleted the interface implies all the subscriptions are selected and the query results reflect this. We can save the dashboard and it works correctly - querying data from all the subscriptions.

As soon as you click 'edit' this panel next time - that random subscription is added again automatically. So we have to delete it and save.

### 
# What Grafana version are you using?

9.4.12 Azure managed grafana

### 
### Is the bug inside a Dashboard Panel?

Copy the panel's ["get-help" data](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/) here

### Grafana Platform?

Other

### User's Browser?

Chrome

### Is this a Regression?

None

**Comment by zuchka** [comment] 2023-06-20 22:38
> 9.4.12 Azure managed grafana

not sure if this is the repo for AMG issue....

**Comment by websolut** [comment] 2023-06-21 09:08
@zuchka The issue is about this part of grafana interface - 
![image](https://github.com/grafana/grafana/assets/13100077/a3c5e8af-e287-484d-84eb-6f221971b972)

**Comment by aangelisc** [comment] 2023-07-04 12:14
Hi @websolut,

This issue was actually fixed via #66890 and has been available since v9.5.1. The behaviour has been updated to specify that the subscription field is required and cannot be left empty. In addition, we are tracking the request to select all subscriptions in #71034. I'm going to close this issue as a duplicate of the issue that was previously resolved.

**Closed by aangelisc** 2023-07-04 12:14 UTC
Labels: datasource/Azure, triage/needs-confirmation
