### ISSUE TITLE
[Bug] Row controls show on long dashboards with menu pinned

### ISSUE THREAD

**Issue by magnuspwhite** [grafana/grafana#7236] opened 2017-01-12 11:57 UTC
- What Grafana version are you using?
v4.1.1
- What datasource are you using?
N/A
- What OS are you running grafana on?
Debian Jessie
- What did you do?
View a dashboard with 6+ rows
- What was the expected result?
The controls to be hidden.
- What happened instead?
Row controls show in the menu area when the menu is pinned and on approximately the 6th row where each row is 200px.

![row controls](https://cloud.githubusercontent.com/assets/925749/21888829/eb4efaa6-d8bd-11e6-983f-1a1743fca8c4.png)

**Comment by torkelo** [comment] 2017-01-12 11:59
duplicate of https://github.com/grafana/grafana/issues/6972

**Closed by torkelo** 2017-01-12 11:59 UTC
