### ISSUE TITLE
Grafana 5.1.0 Docker Container crashes during datasource provisioning

### ISSUE THREAD

**Issue by sharenz** [grafana/grafana#11814] opened 2018-05-03 14:04 UTC
Please include this information:
### What Grafana version are you using?
msg="Starting Grafana" logger=server version=5.1.0 commit=844bdc53a compiled=2018-04-26T17:09:23+0200
### What datasource are you using?
Prometheus
### What OS are you running grafana on?
https://hub.docker.com/r/grafana/grafana/ latest on Debian 9
### What did you do?
Starting Grafana Container with provisioned datasource Prometheus. Note that the system is under quite heavy load and also other containers are starting simultaneously. There are no problems with the other containers.

This problem does not occur everytime.

prometheus.yaml:
```
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  version: 1
  editable: false
```

### What was the expected result?
Grafana starts

### What happened instead?
Grafana crashes some times with the following error message:

```
grafana_1               | t=2018-05-03T14:16:55+0200 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name=Prometheus
grafana_1               | fatal error: concurrent map read and map write
grafana_1               | 
grafana_1               | goroutine 848 [running]:
grafana_1               | runtime.throw(0x13fc946, 0x21)
grafana_1               | 	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0xc4201bab48 sp=0xc4201bab28 pc=0x432511
grafana_1               | runtime.mapaccess1_faststr(0x11ded40, 0xc4201701b0, 0x10b25ba, 0x20, 0x417769)
grafana_1               | 	/usr/local/go/src/runtime/hashmap_fast.go:181 +0x421 fp=0xc4201babb8 sp=0xc4201bab48 pc=0x411e81
grafana_1               | github.com/grafana/grafana/pkg/bus.(*InProcBus).Dispatch(0xc420170180, 0x10dff40, 0xc4204b6000, 0xc4201bac01, 0xc4204b6000)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/bus/bus.go:65 +0xbd fp=0xc4201bac78 sp=0xc4201babb8 pc=0x7bbf4d
grafana_1               | github.com/grafana/grafana/pkg/bus.Dispatch(0x10dff40, 0xc4204b6000, 0xc4201bad10, 0x4a8614)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/bus/bus.go:154 +0x49 fp=0xc4201bacb0 sp=0xc4201bac78 pc=0x7bccd9
grafana_1               | github.com/grafana/grafana/pkg/services/dashboards.(*dashboardServiceImpl).GetProvisionedDashboardData(0xc42021a740, 0xc4206a6280, 0x7, 0x40800c, 0xc4201bad68, 0xc4201bad70, 0x4a7f01, 0xc420218a80)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/dashboards/dashboard_service.go:52 +0x6f fp=0xc4201bace8 sp=0xc4201bacb0 pc=0x8cfb7f
grafana_1               | github.com/grafana/grafana/pkg/services/provisioning/dashboards.getProvisionedDashboardByPath(0x1515ec0, 0xc42021a740, 0xc4206a6280, 0x7, 0x150b580, 0xc42021bc10, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/provisioning/dashboards/file_reader.go:188 +0x52 fp=0xc4201bad60 sp=0xc4201bace8 pc=0xdc86a2
grafana_1               | github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*fileReader).startWalkingDisk(0xc42018c7c0, 0xc4205be768, 0x40b800)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/provisioning/dashboards/file_reader.go:97 +0x137 fp=0xc4201baec8 sp=0xc4201bad60 pc=0xdc72e7
grafana_1               | github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*fileReader).ReadAndListen(0xc42018c7c0, 0x1518200, 0xc4201cb880, 0x0, 0xc4202d1320)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/provisioning/dashboards/file_reader.go:59 +0x40 fp=0xc4201bafb8 sp=0xc4201baec8 pc=0xdc6f50
grafana_1               | runtime.goexit()
grafana_1               | 	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4201bafc0 sp=0xc4201bafb8 pc=0x461f51
grafana_1               | created by github.com/grafana/grafana/pkg/services/provisioning/dashboards.(*DashboardProvisioner).Provision
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/provisioning/dashboards/dashboard.go:42 +0x9a
grafana_1               | 
grafana_1               | goroutine 1 [chan receive]:
grafana_1               | main.main()
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:96 +0x2ce
grafana_1               | 
grafana_1               | goroutine 5 [syscall]:
grafana_1               | os/signal.signal_recv(0x0)
grafana_1               | 	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
grafana_1               | os/signal.loop()
grafana_1               | 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
grafana_1               | created by os/signal.init.0
grafana_1               | 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
grafana_1               | 
grafana_1               | goroutine 34 [select]:
grafana_1               | main.listenToSystemSignals(0xc4201cb9c0, 0xc420040240)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:110 +0x21a
grafana_1               | created by main.main
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:84 +0x28b
grafana_1               | 
grafana_1               | goroutine 35 [runnable]:
grafana_1               | github.com/grafana/grafana/pkg/bus.AddCtxHandler(0x13d2230, 0x7, 0x11b41a0, 0x144fb38)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/bus/bus.go:140 +0x58
grafana_1               | github.com/grafana/grafana/pkg/services/notifications.Init(0xc4201cb8c0, 0xc4202d1ce0)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/notifications/notifications.go:34 +0x131
grafana_1               | main.(*GrafanaServerImpl).Start(0xc4201cb9c0, 0x0, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:92 +0x3ca
grafana_1               | main.main.func2(0xc4201cb9c0)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:88 +0x2f
grafana_1               | created by main.main
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/main.go:86 +0x2ad
grafana_1               | 
grafana_1               | goroutine 50 [select, locked to thread]:
grafana_1               | runtime.gopark(0x1451f38, 0x0, 0x13d018b, 0x6, 0x18, 0x1)
grafana_1               | 	/usr/local/go/src/runtime/proc.go:291 +0x11a
grafana_1               | runtime.selectgo(0xc42049df50, 0xc4200e8060)
grafana_1               | 	/usr/local/go/src/runtime/select.go:392 +0xe50
grafana_1               | runtime.ensureSigM.func1()
grafana_1               | 	/usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
grafana_1               | runtime.goexit()
grafana_1               | 	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1
grafana_1               | 
grafana_1               | goroutine 51 [select]:
grafana_1               | database/sql.(*DB).connectionOpener(0xc4200b08c0, 0x1518200, 0xc4202e6e80)
grafana_1               | 	/usr/local/go/src/database/sql/sql.go:935 +0x119
grafana_1               | created by database/sql.OpenDB
grafana_1               | 	/usr/local/go/src/database/sql/sql.go:634 +0x178
grafana_1               | 
grafana_1               | goroutine 52 [select]:
grafana_1               | database/sql.(*DB).connectionResetter(0xc4200b08c0, 0x1518200, 0xc4202e6e80)
grafana_1               | 	/usr/local/go/src/database/sql/sql.go:948 +0x12a
grafana_1               | created by database/sql.OpenDB
grafana_1               | 	/usr/local/go/src/database/sql/sql.go:635 +0x1ae
grafana_1               | 
grafana_1               | goroutine 55 [select]:
grafana_1               | database/sql.(*DB).connectionCleaner(0xc4200b08c0, 0xd18c2e28000)
grafana_1               | 	/usr/local/go/src/database/sql/sql.go:856 +0x38a
grafana_1               | created by database/sql.(*DB).startCleanerLocked
grafana_1               | 	/usr/local/go/src/database/sql/sql.go:843 +0xba
grafana_1               | 
grafana_1               | goroutine 849 [select]:
grafana_1               | github.com/grafana/grafana/pkg/services/alerting.(*Ticker).run(0xc42018c840)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/alerting/ticker.go:54 +0x283
grafana_1               | created by github.com/grafana/grafana/pkg/services/alerting.NewTicker
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/alerting/ticker.go:36 +0x121
grafana_1               | 
grafana_1               | goroutine 994 [chan receive]:
grafana_1               | github.com/grafana/grafana/pkg/services/alerting.(*DefaultRuleReader).initReader(0xc42018c880)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/alerting/reader.go:39 +0x4e
grafana_1               | created by github.com/grafana/grafana/pkg/services/alerting.NewRuleReader
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/alerting/reader.go:30 +0xb6
grafana_1               | 
grafana_1               | goroutine 995 [runnable]:
grafana_1               | github.com/grafana/grafana/vendor/github.com/inconshreveable/log15.(*swapHandler).Log(0xc42021a880, 0xc4204ae000, 0x1aa4ff8, 0x1aa5038)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/handler_go14.go:13 +0xc6
grafana_1               | github.com/grafana/grafana/vendor/github.com/inconshreveable/log15.(*logger).write(0xc4202d1b40, 0x13e7ecd, 0x15, 0x3, 0x0, 0x0, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/logger.go:106 +0x24b
grafana_1               | github.com/grafana/grafana/vendor/github.com/inconshreveable/log15.(*logger).Info(0xc4202d1b40, 0x13e7ecd, 0x15, 0x0, 0x0, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/logger.go:139 +0x66
grafana_1               | github.com/grafana/grafana/pkg/services/alerting.(*Engine).Run(0xc420076ba0, 0x1518200, 0xc4201cb880, 0x0, 0xc4205bf790)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/alerting/engine.go:43 +0x5e
grafana_1               | main.(*GrafanaServerImpl).Start.func2(0x8, 0x14520a8)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:85 +0x3f
grafana_1               | github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc4201cb8c0, 0xc4202d1c60)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
grafana_1               | created by github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
grafana_1               | 
grafana_1               | goroutine 996 [runnable]:
grafana_1               | github.com/grafana/grafana/vendor/github.com/go-stack/stack.Caller(0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/github.com/go-stack/stack/stack.go:45 +0xf6
grafana_1               | github.com/grafana/grafana/vendor/github.com/inconshreveable/log15.(*logger).write(0xc4202d1cc0, 0x13f266f, 0x1b, 0x3, 0x0, 0x0, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/logger.go:111 +0xc9
grafana_1               | github.com/grafana/grafana/vendor/github.com/inconshreveable/log15.(*logger).Info(0xc4202d1cc0, 0x13f266f, 0x1b, 0x0, 0x0, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/logger.go:139 +0x66
grafana_1               | github.com/grafana/grafana/pkg/services/cleanup.(*CleanUpService).Run(0xc42021a940, 0x1518200, 0xc4201cb880, 0xc4205bb798, 0xc4205bb790)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/cleanup/cleanup.go:29 +0x5d
grafana_1               | main.(*GrafanaServerImpl).Start.func3(0xc400000008, 0x14520a8)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:90 +0x3f
grafana_1               | github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc4201cb8c0, 0xc4202d1ce0)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
grafana_1               | created by github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
grafana_1               | 
grafana_1               | goroutine 990 [select]:
grafana_1               | github.com/grafana/grafana/pkg/metrics.instrumentationLoop(0xc42028d920, 0x0)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/metrics/metrics.go:334 +0x188
grafana_1               | created by github.com/grafana/grafana/pkg/metrics.initMetricVars
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/metrics/metrics.go:319 +0xabb
grafana_1               | 
grafana_1               | goroutine 838 [sleep]:
grafana_1               | time.Sleep(0x12a05f200)
grafana_1               | 	/usr/local/go/src/runtime/time.go:102 +0x166
grafana_1               | github.com/grafana/grafana/pkg/plugins.updateAppDashboards()
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/plugins/dashboards_updater.go:15 +0x34
grafana_1               | created by github.com/grafana/grafana/pkg/plugins.initPlugins
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/plugins/plugins.go:117 +0x92c
grafana_1               | 
grafana_1               | goroutine 997 [runnable]:
grafana_1               | github.com/grafana/grafana/pkg/services/notifications.processMailQueue()
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:29
grafana_1               | created by github.com/grafana/grafana/pkg/services/notifications.initMailQueue
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/notifications/mailer.go:26 +0x64
grafana_1               | 
grafana_1               | goroutine 839 [chan receive]:
grafana_1               | github.com/grafana/grafana/pkg/plugins.(*PluginManager).Run(0xc42006a430, 0x1518200, 0xc4201cb880, 0xc4203d2798, 0xc4203d2790)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/plugins/plugins.go:55 +0x60
grafana_1               | main.(*GrafanaServerImpl).Start.func1(0xc400000008, 0x14520a8)
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:70 +0x3f
grafana_1               | github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc4201cb8c0, 0xc420261a40)
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
grafana_1               | created by github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup.(*Group).Go
grafana_1               | 	/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
grafana_1               | 
grafana_1               | goroutine 998 [runnable]:
grafana_1               | github.com/grafana/grafana/pkg/services/notifications.processWebhookQueue()
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/notifications/webhook.go:51
grafana_1               | created by github.com/grafana/grafana/pkg/services/notifications.initWebhookQueue
grafana_1               | 	/go/src/github.com/grafana/grafana/pkg/services/notifications/webhook.go:48 +0xb4
```

**Comment by marefr** [comment] 2018-05-03 14:14
You're aware of the [breaking changes for Grafana docker container](http://docs.grafana.org/guides/whats-new-in-v5-1/#improved-docker-image-breaking-change) introduced in v5.1?

Could you please provide more information:
* how do you run the docker container, solely docker run or docker-compose or kubernetes etc. Include any details that can be of importance.
* how are you mapping in the volume for the *prometheus.yaml* file?

**Comment by marefr** [comment] 2018-05-03 15:12
Thanks. Since you're using a customized entrypoint I'll close this issue. Will reopen this if you can reproduce it without the customized entrypoint and/or you include your docker-compose files, custom entrypoint and provisioning files.

**Closed by marefr** 2018-05-03 15:12 UTC
Labels: state: needs more detail
