### ISSUE TITLE
Build fails with Go 1.13. `go get -u golang.org/x/xerrors` solves the issue

### ISSUE THREAD

**Issue by dmilith** [grafana/grafana#19311] opened 2019-09-23 11:34 UTC
Please do: `go get -u golang.org/x/xerrors` and commit potential locks. This solves build failure with new (1.13+) Golang compiler.

**Comment by marefr** [comment] 2019-09-24 07:04
Duplicate of #18878

**Closed** 2019-09-24 07:04 UTC
