### ISSUE TITLE
Loki Auto-Refresh

### ISSUE THREAD

**Issue by stevenpall** [grafana/grafana#15865] opened 2019-03-07 20:41 UTC
**What would you like to be added**:

"Auto-refresh" of Loki logs

**Why is this needed**:

This would be useful for "tailing" logs. Currently, the query has to be rerun manually which is workable but not as convenient.

**Comment by torkelo** [comment] 2019-03-08 12:05
duplicate of https://github.com/grafana/grafana/issues/15192

**Closed by torkelo** 2019-03-08 12:05 UTC
Labels: datasource: Loki, type: feature request
