### ISSUE TITLE
Direct image rendering doesn't work when using UNIX socket protocol

### ISSUE THREAD

**Issue by stefangluszek** [grafana/grafana#20725] opened 2019-11-28 07:46 UTC
**What happened**:
When grafana is configured to use UNIX socket protocols instead of HTTP the direct image rendering doesn't work.

**What you expected to happen**:
Direct image rendering works.

**How to reproduce it (as minimally and precisely as possible)**:
Reproduce steps:
- configure grafana to use UNIX socket instead of HTTP protocol
```[server]
# Protocol (http, https, h2, socket)
protocol = socket
socket = /run/grafana/socket
```
- use socat to listen on TCP socket and relay your request to the UNIX socket
```
socat  TCP4-LISTEN:3000,fork UNIX-CONNECT:/run/grafana/socket
```
- request a direct image for any graph
- if you change the protocol to HTTP the images are rendered

grafana debug log:
```
t=2019-11-28T07:38:29+0000 lvl=info msg=Rendering logger=rendering path="d-solo/GZNijPbZk/new-dashboard-copy?orgId=1&from=1574905107588&to=1574926707588&panelId=2&width=1000&height=500&tz=Europe%2FStockholm"
t=2019-11-28T07:39:31+0000 lvl=info msg="Rendering timed out" logger=rendering
t=2019-11-28T07:39:31+0000 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2019-11-28T07:39:31+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/GZNijPbZk/new-dashboard-copy status=500 remote_addr=@ time_ms=62010 size=1782 referer="http://localhost:3000/d/GZNijPbZk/new-dashboard-copy?orgId=1"
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.0
- Data source type & version:
- OS Grafana is installed on: Ubuntu 18.04.3
- User OS & Browser: Linux, Chrome
- Grafana plugins: none
- Others:

**Comment by aknuds1** [comment] 2019-11-28 08:48
I've tested direct image rendering locally in both socket and http mode, both time out for me. Will investigate as to what's going on.

**Comment by stefangluszek** [comment] 2019-11-28 09:13
For me switching to HTTP solved the issue, both in my test and production setup.

**Comment by aknuds1** [comment] 2019-12-02 11:52
I haven't been able to reproduce personally, but I hear from my colleagues image rendering in Unix socket mode isn't yet supported. Marking this as a feature request.

**Comment by RedShift1** [comment] 2020-03-26 14:16
As this bug is marked "awaiting-more-evidence", here is some more evidence:
```
Mar 26 15:12:56 websrv1 grafana-server: t=2020-03-26T15:12:56+0100 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/l0eRS29Wz/REDACTED-alerts?orgId=1&refresh=5s&from=1585210218006&to=1585231818006&panelId=2&width=1000&height=500&tz=Europe%2FBrussels"
Mar 26 15:12:56 websrv1 grafana-server: t=2020-03-26T15:12:56+0100 lvl=eror msg="Browser request failed" logger=plugins.backend pluginId=grafana-image-renderer url="socket://localhost:3000/d-solo/l0eRS29Wz/REDACTED-alerts?orgId=1&refresh=5s&from=1585210218006&to=1585231818006&panelId=2&width=1000&height=500&tz=Europe%2FBrussels&render=1" method=GET
Mar 26 15:12:56 websrv1 grafana-server: t=2020-03-26T15:12:56+0100 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="socket://localhost:3000/d-solo/l0eRS29Wz/REDACTED-alerts?orgId=1&refresh=5s&from=1585210218006&to=1585231818006&panelId=2&width=1000&height=500&tz=Europe%2FBrussels&render=1" error="Error: net::ERR_ABORTED at socket://localhost:3000/d-solo/l0eRS29Wz/REDACTED-alerts?orgId=1&refresh=5s&from=1585210218006&to=1585231818006&panelId=2&width=1000&height=500&tz=Europe%2FBrussels&render=1"
Mar 26 15:12:56 websrv1 grafana-server: t=2020-03-26T15:12:56+0100 lvl=eror msg="Rendering failed." logger=context userId=2 orgId=1 uname=REDACTED@REDACTED.com error="Rendering failed: Error: net::ERR_ABORTED at socket://localhost:3000/d-solo/l0eRS29Wz/REDACTED-alerts?orgId=1&refresh=5s&from=1585210218006&to=1585231818006&panelId=2&width=1000&height=500&tz=Europe%2FBrussels&render=1"
Mar 26 15:12:56 websrv1 grafana-server: t=2020-03-26T15:12:56+0100 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=REDACTED@REDACTED.com method=GET path=/render/d-solo/l0eRS29Wz/REDACTED-alerts status=500 remote_addr=10.1.0.93 time_ms=421 size=1722 referer="https://grafana.REDACTED.com/d/l0eRS29Wz/REDACTED-alerts?orgId=1&refresh=5s"
```

**Comment by aknuds1** [comment] 2020-04-15 09:49
I tried latest Grafana master revision and the image renderer plugin now, and it fails in the same way as for @RedShift1. I will see if I can figure out why.

**Comment by aknuds1** [comment] 2020-04-15 14:02
I've done some research, and from what I can tell [Puppeteer](https://pptr.dev/), which we use to perform the actual rendering, doesn't support Unix sockets. Since we don't foresee fixing this, we've decided to close this ticket.

However, you should be able to work around this issue by using Grafana's `rendering.callback_url` configuration parameter, if you have an HTTP ingress to the Grafana server also.

**Closed** 2020-04-15 14:02 UTC
Labels: area/image-rendering, needs investigation, type/feature-request

**Comment by whitequark** [comment] 2020-12-06 23:59
> However, you should be able to work around this issue by using Grafana's `rendering.callback_url` configuration parameter, if you have an HTTP ingress to the Grafana server also.

This workaround doesn't seem possible unless I run the renderer as a remote service according to https://github.com/grafana/grafana-image-renderer/issues/151#issuecomment-638982458. Can you explain how to use it?
