### ISSUE TITLE
Add the option to click on a legend entry and have it update a variable, thus filtering all charts in the dashboard that use that variable.

### ISSUE THREAD

**Issue by jeremygurr** [grafana/grafana#16126] opened 2019-03-20 23:40 UTC
**What would you like to be added**:
The ability to update dashboard filters by changing variables caused by the selection of a legend entry in any of the charts that belong to the dashboard. For example, if I had a dashboard showing web requests broken down by response time bucket, web domain, and error rate, I could click on the error code in the error rate chart (say 404) and it would update the "ErrorCode" variable with the value "404", which would filter all three charts to only include requests that returned a 404. Then this variable could be hidden from the user, and would only be updated when the user clicked on a legend entry that was linked to the variable. Then if they click on a legend entry that was already the current filter, it would remove the filter and go back to showing all data for that variable. 

In the options for a chart, possibly in the "Legend" tab, would be an option that says: update variable with value, and would have a drop down with the list of defined variables for this dashboard. 

**Why is this needed**:

Being able to filter a dashboard by clicking on a legend entry of a chart you are looking at is far more efficient than going up to the top and going through a possibly long list of variables, dropping down the one you want, and trying to find the exact value you want to filter on. It also makes the dashboard less cluttered and is arguably more intuitive.

**Comment by torkelo** [comment] 2019-03-21 08:16
duplicate of https://github.com/grafana/grafana/issues/1232 

This is something that we will begin working on shortly

**Closed by torkelo** 2019-03-21 08:16 UTC
