### ISSUE TITLE
Hover tooltip struggle to open on right screen edge when not enough space to render

### ISSUE THREAD

**Issue by Juraj243** [grafana/grafana#30775] opened 2021-02-01 08:22 UTC
**What happened**:
On graph. Tooltip struggle to open when pointer is on the right edge of the screen (tooltip should render on the left side of the pointer) and there is not enough space to render it.
However, when displaying tooltip on the right side of the pointer, there is no issue even when not enough space.

**What you expected to happen**:
Tooltip should render and stick to the top as it does when on the right side of he pointer.

**How to reproduce it (as minimally and precisely as possible)**:
1. create graph with bars and a lot of labels
2. move pointer to the right side of the screen so that there is not enough space above/below/right to the mouse to display tooltip.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/9944907/106432247-bcb39d00-646e-11eb-9dd8-1998b447969e.png)
You need to scroll the screen or move pointer exactly somewhere so it has enough space to render.

**Environment**:
- Grafana version: v7.3.4 (14c494085e)
- Data source type & version: InfluxDB
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome 88.0.4324.104
- Grafana plugins: piechart
- Others:

**Comment by torkelo** [comment] 2021-02-01 20:08
duplicate of https://github.com/grafana/grafana/issues/30130

**Closed by torkelo** 2021-02-01 20:08 UTC
