### ISSUE TITLE
Datasource UID

### ISSUE THREAD

**Issue by alter** [grafana/grafana#17163] opened 2019-05-20 08:05 UTC
Hello,
**What would you like to be added**:
I think it would be a nice idea to add UID for datasources, like you already did it for dashboards.

**Why is this needed**:
B/c sometimes people may need to switch datasource name, but it's impossible if you have a lot of dashboards which use it.

**Comment by marefr** [comment] 2019-05-20 11:31
Duplicate of #1664

**Comment by marefr** [comment] 2019-05-20 11:33
This can be a solution to referenced issue, but please continue discussions in that issue.

**Closed by marefr** 2019-05-20 11:33 UTC
