### ISSUE TITLE
Graphite: Support using full path for variable values in templating queries

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#20171] opened 2019-11-05 10:10 UTC
**What would you like to be added**:
When creating a template variable, i would like to use the full path of matching metrics, rather than just the last node.

An alternate feature would be to allow specifying the node position to use for values, but this can be achieved using the existing regex support, provided the full path is returned.

**Why is this needed**:
The primary motivation for this is to allow template queries to target more specific values.  A common example is to get the list of datacenters that have a specific application running.

A common series name format is `collectd.<datacenter>.my-application.*`
when building a dashboard, you would typically want template variables for datacenter. Right now, a datacenter variable would use `collected.*` for its query, which would contain the list of all datacenters, not just those that have 'my-application' running. 

To support this feature, Grafana would need to use the 'completer' format for find queries instead of the default 'json'.

/metrics/find?query=collected.*.cassandra
```
[{"allowChildren":1,"expandable":1,"leaf":0,"id":"collectd.us-west1.cassandra","text":"cassandra","context":{}}]
```
/metrics/find?query=collected.*.cassandra&format=completer
```
{ 
   "metrics":[ 
      { 
         "path":"collectd.us-central1.cassandra",
         "name":"cassandra",
         "is_leaf":"0"
      },
      { 
         "path":"collectd.us-east1.cassandra",
         "name":"cassandra",
         "is_leaf":"0"
      }
   ]
}
```

**Comment by torkelo** [comment] 2019-11-05 12:49
looks similar https://github.com/grafana/grafana/issues/2343

**Comment by davkal** [comment] 2020-11-11 10:48
Duplicate of #2343

**Closed by davkal** 2020-11-11 10:48 UTC
Labels: datasource/Graphite, priority/important-longterm, type/feature-request
