### ISSUE TITLE
GLIBC version requirement changed after Grafana version 9.1.6

### ISSUE THREAD

**Issue by xiaodong-xie** [grafana/grafana#57157] opened 2022-10-18 09:51 UTC
**What happened**:

We were running Grafana on AWS EC2 instance using Amazon Linux 2, the GLIBC version is 2.26 (https://aws.amazon.com/amazon-linux-2/faqs/) 

```
Q. What are the core components of Amazon Linux 2?

The core components of Amazon Linux 2 are:

A Linux kernel tuned for performance on Amazon EC2.
A set of core packages including systemd, GCC 7.3, Glibc 2.26, Binutils 2.29.1 that receive Long Term Support (LTS) from AWS.
An extras channel for rapidly evolving technologies that are likely to be updated frequently and outside the Long Term Support (LTS) model.
```

Grafana was running fine until we upgraded Grafana passing version 9.1.6

We got this error in `/var/log/messages`: 

```
grafana-server: /usr/sbin/grafana-server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /usr/sbin/grafana-server)
```

**What you expected to happen**:

Grafana should be running fine on Amazon Linux 2.

**How to reproduce it (as minimally and precisely as possible)**:

Install any version of Grafana beyond 9.1.6

**Anything else we need to know?**:

We are using `t4g` instance family, which is Arm based, but most probably this is irrelevant. 

**Environment**:
- Grafana version: 9.1.6
- Data source type & version:
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser:
- Grafana plugins:
- Others:

Thanks a lot for your help. If this is intended (using a higher version of Glibc since version 9.1.6), please close this bug report.

**Comment by tleopold** [comment] 2022-11-30 15:54
Hi

This looks like you should be running the Arm version of Grafana instead of the x86 version.  https://grafana.com/grafana/download/9.1.6?platform=arm

We will close this issue now but please re-open if the above advice does not help.

Thanks

**Comment by xiaodong-xie** [comment] 2022-11-30 17:01
Hello, @tleopold, 

Thanks for checking this issue. 🙏  

The original Grafana installation was using `yum`, following the steps provided here https://grafana.com/docs/grafana/latest/setup-grafana/installation/rpm/.

In order to verify we are using the Arm version of Grafana, I went for the direct download approach to install Grafana as you suggested. 

I first tried https://grafana.com/grafana/download/9.1.6?platform=arm, using 
```
wget https://dl.grafana.com/enterprise/release/grafana-enterprise-9.1.6.linux-arm64.tar.gz
tar -zxvf grafana-enterprise-9.1.6.linux-arm64.tar.gz
```

Then started Grafana using `grafana-9.1.6/bin/grafana-server`, Grafana-9.1.6 started successfully. 

Then I tried https://grafana.com/grafana/download/9.3.0?platform=arm, using 
```
wget https://dl.grafana.com/enterprise/release/grafana-enterprise-9.3.0.linux-arm64.tar.gz
tar -zxvf grafana-enterprise-9.3.0.linux-arm64.tar.gz
```

Then started Grafana using `grafana-9.3.0/bin/grafana-server`, Grafana-9.3.0 could not start. 

It failed to start with the following message:
```
bin/grafana-server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by bin/grafana-server)
```

**Comment by dsymonds** [comment] 2022-12-01 00:10
Yes, I can confirm I got the same issue. It's the ARM build/packaging, not using the x86 version by mistake.

@tleopold, could you please re-open this issue? I don't think we're able to re-open it ourselves.

**Comment by dsymonds** [comment] 2022-12-16 07:46
This remains an issue with `grafana-enterprise-9.3.2.linux-armv7.tar.gz`.

```shell
$ wget https://dl.grafana.com/enterprise/release/grafana-enterprise-9.3.2.linux-armv7.tar.gz
...
$ tar zxf grafana-enterprise-9.3.2.linux-armv7.tar.gz
$ grafana-9.3.2/bin/grafana-server
grafana-9.3.2/bin/grafana-server: /lib/libc.so.6: version `GLIBC_2.28' not found (required by grafana-9.3.2/bin/grafana-server)
```

(The same machine happily runs other linux-armv7 packages, such as Prometheus.)

@tleopold, could you please re-open this?

**Comment by mourya92** [comment] 2023-05-24 22:53
Can we please re-open this issue ? I am getting exact same issue. Is it possible to get a ARM64 binary (for >9.1.6 version) that can run on Amazon Linux 2 ?

**Comment by kminehart** [comment] 2023-10-11 11:54
@mourya92 should be good now yeah?

**Comment by dsymonds** [comment] 2023-10-12 21:15
Looks like linux-armv7 binaries are no longer being built for releases.  :-(

**Comment by gelicia** [comment] 2024-02-28 22:31
Looks to be fixed by https://github.com/grafana/grafana/issues/69030 - closing

**Closed by gelicia** 2024-02-28 22:31 UTC
Labels: type/build-packaging
