### ISSUE TITLE
Provide the ARM packages in debian and rpm repositories

### ISSUE THREAD

**Issue by rawctl** [grafana/grafana#12761] opened 2018-07-30 12:54 UTC
Hello,

I wanted to ask if it would be possible to provide the new ARM packages on packagecloud [1]. This would make it easier to upgrade to new releases.

The packages are currently provided only through direct download of `.rpm` and `.deb` packages on [2].

[1] https://packagecloud.io/grafana/stable
[2] https://grafana.com/grafana/download?platform=arm

**Comment by xlson** [comment] 2018-07-31 16:03
@rawctl We are considering adding the packages to packagecloud in the future. It depends mostly on the demand for this feature, so far you are the first to ask for it.

**Comment by mcaulifn** [comment] 2018-07-31 22:31
I had asked in #5156. Would help with updates and deterministic installs.

**Comment by wcndave** [comment] 2018-08-20 09:42
I would like to see this too.  I have spent hours trying to install on pi, and I am still not there...

**Comment by matiasfrndz** [comment] 2018-08-20 16:00
+1 from me, as described in https://community.grafana.com/t/arm-packages-in-packagecloud-debian-repository/9773

**Comment by ajsicek** [comment] 2018-08-29 12:34
+1 for this, would be great to be able to update grafana automatically with all the other packages.
running it in debian LXC container on turris omnia. I thought there is quite a few people running grafana on arm as it makes a lot of sense for home usage. thank you very much for all the great work :)

**Comment by huczas** [comment] 2018-10-02 21:31
+1

**Comment by alex-voigt** [comment] 2018-10-18 17:58
+1

**Comment by EliasGabrielsson** [comment] 2018-11-16 13:35
On behalf of the [OpenHAB](https://www.openhab.org/) community we would appreciate this support. 

+1

**Comment by mark9064** [comment] 2018-12-19 17:56
Grafana works great on arm, would really like to see it added as arm servers become more popular and powerful. Without this automatic updating is a real mess, which is a big problem considering things like security updates that shouldn't be missed.

+1

**Comment by xlson** [comment] 2018-12-21 13:37
I have been working on standing up a new repository for Grafana recently. This contains the arm packages as well as the amd64 releases. I don't have access to a Raspberry PI at work and would really appreciate if  someone could help me test the arm packages.

# Usage

## Debian
Trust our GPG key:
`curl https://packages.grafana.com/gpg.key | sudo apt-key add -`

Create `/etc/apt/sources.list.d/grafana.list`
```
deb https://packages.grafana.com/oss/deb squeeze main
```

Install Grafana
```
apt update
apt install grafana
```

## Centos
Create `/etc/yum.repos.d/grafana.repo`
```
[grafana]
name=grafana
baseurl=https://packages.grafana.com/oss/rpm
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packages.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

Install Grafana
```
yum install grafana
```

**Comment by pavel-odintsov** [comment] 2018-12-21 20:19
Hello!

That's great news!

I tested it on https://www.pine64.org/?page_id=61454 with Armbian distro (Ubuntu 18.04 Bionic based). 

It works perfect:
<img width="1440" alt="grafana" src="https://user-images.githubusercontent.com/2744166/50361989-a7fd3f00-055d-11e9-9688-9378253832de.png">

**Comment by huczas** [comment] 2018-12-21 22:58
HW: Raspberry Pi 3B, Debian Stretch(ARMv7), I've added to sources file grafana.list(GPG keys are trusted): 

`deb https://packages.grafana.com/oss/deb stretch main`

But when trying to update I'm getting:

```
Ign:9 https://packages.grafana.com/oss/deb stretch InRelease
Err:10 https://packages.grafana.com/oss/deb stretch Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://packages.grafana.com/oss/deb stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by mark9064** [comment] 2018-12-22 11:01
@huczas try using squeeze instead of stretch? I know it's the wrong one for your distro but that's how the other repo works too (all ubuntu/debian versions should use the stretch build on the packagecloud for example)

**Comment by xlson** [comment] 2018-12-22 22:18
@huczas you need to specify squeeze instead of stretch for it to work. Thanks for testing!

**Comment by huczas** [comment] 2018-12-23 00:11
Ok, I can confirm that’s working fine on latest raspbian RPi3B with “squeeze” in repo. 
Thanks a lot for great work.

**Comment by rawctl** [comment] 2019-01-01 15:38
@xlson Do you consider this to be fixed or are you going to do any other changes here? Otherwise I could close this issue.

**Comment by ajsicek** [comment] 2019-01-02 08:57
Great job :) thanks a lot
works for me on debian LXC container on turris omnia with "squeeze" repo.
Debian stretch
ARMv7

**Comment by xlson** [comment] 2019-01-02 13:18
@rawctl I'm going to update our documentation before closing the issue. Thanks for asking.

**Comment by xlson** [comment] 2019-01-03 16:11
Distribution has been changed from `squeeze` to `stable` to avoid confusion. If you are using the repository you will have to update your repo config.

**Comment by xlson** [comment] 2019-01-07 08:59
The documentation has been updated with the new instructions so I'm closing this issue. Thanks everyone who helped in testing!

**Closed by xlson** 2019-01-07 08:59 UTC
Labels: type: build & packaging, type: feature request

**Comment by pavel-odintsov** [comment] 2019-01-28 20:40
@xlson thank you so much! :) It works great!

**Comment by SeppPenner** [comment] 2019-07-02 17:43
I have trusted the GPG key using `curl https://packages.grafana.com/gpg.key | sudo apt-key add -` as described and added `deb https://packages.grafana.com/oss/deb squeeze main` to the grafana.list file under `etc/apt/sources.list.d/`.

When I do a `apt update`, I get the following error message:
```batch
Fehl:4 https://packages.grafana.com/oss/deb squeeze Release
  404  Not Found
Paketlisten werden gelesen... Fertig
E: The repository 'https://packages.grafana.com/oss/deb squeeze Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Can anyone help me out here, please?

**Comment by matiasfrndz** [comment] 2019-07-02 18:55
@SeppPenner I think the difference is in the URL for the repo. The output from `apt` looks like you had configured
```deb https://packages.grafana.com/oss/deb squeeze Release```
where as in https://grafana.com/docs/installation/debian/ it says:
```deb https://packages.grafana.com/oss/deb stable main```
