### ISSUE TITLE
Alert not sent by email

### ISSUE THREAD

**Issue by thomazrhel** [grafana/grafana#7150] opened 2017-01-05 21:03 UTC
Hello,

I'm using Grafana 4.0.1 + RHEL6 and I'm not able to send notifications by email, follow below my SMTP configuration and the log error.

Please, someone help me solve this problem?

#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = my_smtp_server:25
;user =
;password =
;cert_file =
;key_file =
skip_verify = true
from_address = kkkkkkkk@x.com
 
[emails]
welcome_email_on_sign_up = false
 
 
t=2017-01-05T14:54:51-0500 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
t=2017-01-05T14:54:51-0500 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[myemail@mydomain.com.br]
t=2017-01-05T14:54:51-0500 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error=EOF

Many thanks

**Comment by torkelo** [comment] 2017-01-06 05:35
duplicate of https://github.com/grafana/grafana/issues/7116

**Closed by torkelo** 2017-01-06 05:35 UTC

**Comment by imvishalvyas** [comment] 2019-01-31 12:07
https://www.vishalvyas.com/2019/01/application-specific-password-required.html
