### ISSUE TITLE
[Feature Request] LDAP Group Mapping for Global Admin

### ISSUE THREAD

**Issue by felixkretschmer** [grafana/grafana#9116] opened 2017-08-29 09:53 UTC
I'd love to assign global Admins via LDAP or AD group.

Is it possible to add the feature for ldap configuration.
Something like:

[[servers.group_mappings]]
group_dn = "CN=GrafanaAdmins,OU=Groups,DC=example,DC=com"
org_role = "GlobalAdmin"

**Comment by torkelo** [comment] 2017-08-29 12:06
duplicate of https://github.com/grafana/grafana/issues/2469

**Closed by torkelo** 2017-08-29 12:06 UTC
