### ISSUE TITLE
Prometheus: Adding expressions to a query with exemplars causes internal server error

### ISSUE THREAD

**Issue by yves-chan** [grafana/grafana#66157] opened 2023-04-06 21:56 UTC
**What happened**:
When adding expressions to prometheus queries that have exemplars enabled, with a simple expression such as `$A+10`, we get 500 error
![Animation](https://user-images.githubusercontent.com/7664931/230500998-8ae592ee-1c6f-494f-8f0c-81648fd4a225.gif)

**What you expected to happen**:
Expression works for both exemplars enabled and disabled

**How to reproduce it (as minimally and precisely as possible)**:
1. Download and run the tns demo app https://github.com/grafana/tns
2. On the grafana dashboard provided, edit one of the dashboards with the exemplars and keep only query A
3. Try to add a math expression referencing query A

**Anything else we need to know?**:
It could possibly be related to this? https://github.com/grafana/grafana/issues/46429, where in this case, the exemplar dataframes might not be number and time series vals?

**Environment**:
- Grafana version: 9.3.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment] 2023-04-07 20:49
@yves-chan I'm not able to reproduce this on 9.4.7, it may be fixed with these fixes: 

https://github.com/grafana/grafana/pull/65950 - not yet merged
https://github.com/grafana/grafana/pull/62510 -  merged in 9.3.7

Please open a new issue and reference this one if you're still seeing the problem with 9.3.7+ or the latest version of 9.4.x

**Closed by mellieA** 2023-04-07 20:49 UTC
