### ISSUE TITLE
[Timeseries] Axis does not reflect max datapoint Y

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#79524] opened 2023-12-14 15:59 UTC
### What happened?

I have two series but my Y axis' max range reflects only one of those series. That said, max is around 400Gbps while the max Y should be 800 Gbps

<img width="1224" alt="image" src="https://github.com/grafana/grafana/assets/327717/b946a613-67d4-47cd-9578-1682098fad5a">

 If I select only single series via legend toggle, the axis is displayed correctly.

<img width="1302" alt="image" src="https://github.com/grafana/grafana/assets/327717/db1dca3a-c4b9-45d4-8048-e35e5b75f6eb">

 

### What did you expect to happen?

Y axis to have max around 800Gbps

### Did this work before?

Not sure

### How do we reproduce it?

1. See attached panel

### Is the bug inside a dashboard panel?

| Key | Value |
|--|--|
| Panel | timeseries @ 10.3.0-pre (bac4bba1a81) |
| Grafana | 10.3.0-pre (bac4bba1a81) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "drawStyle": "line",
            "lineInterpolation": null,
            "barAlignment": 0,
            "lineWidth": 1,
            "fillOpacity": 80,
            "gradientMode": "none",
            "spanNulls": false,
            "insertNulls": false,
            "showPoints": "never",
            "pointSize": 1,
            "stacking": {
              "mode": "normal",
              "group": "A"
            },
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "axisBorderShow": false,
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "thresholdsStyle": {
              "mode": "line"
            },
            "axisWidth": 90
          },
          "color": {
            "mode": "palette-classic"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "transparent",
                "value": null
              }
            ]
          },
          "decimals": 2,
          "fieldMinMax": false
        },
        "overrides": [
          {
            "matcher": {
              "id": "byRegexp",
              "options": "/ out$/"
            },
            "properties": [
              {
                "id": "custom.stacking",
                "value": {
                  "group": "A",
                  "mode": "normal"
                }
              }
            ]
          },
          {
            "matcher": {
              "id": "byRegexp",
              "options": "/(ole) .+$/"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "#508642",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.lineWidth",
                "value": 0
              },
              {
                "id": "unit",
                "value": "bps"
              }
            ]
          },
          {
            "matcher": {
              "id": "byRegexp",
              "options": "/speed .+$/"
            },
            "properties": [
              {
                "id": "color",
                "value": {
                  "fixedColor": "#ef843c",
                  "mode": "fixed"
                }
              },
              {
                "id": "custom.fillOpacity",
                "value": 0
              },
              {
                "id": "custom.lineInterpolation",
                "value": "stepAfter"
              },
              {
                "id": "custom.lineWidth",
                "value": 1
              },
              {
                "id": "custom.stacking",
                "value": {
                  "group": false,
                  "mode": "none"
                }
              },
              {
                "id": "unit",
                "value": "bps"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "links": [],
      "minSpan": null,
      "options": {
        "tooltip": {
          "mode": "multi",
          "sort": "desc"
        },
        "legend": {
          "showLegend": true,
          "displayMode": "table",
          "placement": "right",
          "calcs": [
            "max",
            "last",
            "pctl95"
          ],
          "width": 420
        }
      },
      "repeat": null,
      "repeatDirection": null,
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "name": "ole out",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1700866500000,
                    1700866560000,
                    1700866620000,
                    1700866680000,
                    1700866740000,
                    1700866800000,
                    1700866860000,
                    1700866920000,
                    1700866980000,
                    1700867040000,
                    1700867100000,
                    1700867160000,
                    1700867220000,
                    1700867280000,
                    1700867340000,
                    1700867400000,
                    1700867460000,
                    1700867520000,
                    1700867580000,
                    1700867640000,
                    1700867700000,
                    1700867760000,
                    1700867820000,
                    1700867880000,
                    1700867940000,
                    1700868000000,
                    1700868060000,
                    1700868120000,
                    1700868180000,
                    1700868240000,
                    1700868300000,
                    1700868360000,
                    1700868420000,
                    1700868480000,
                    1700868540000,
                    1700868600000,
                    1700868660000,
                    1700868720000,
                    1700868780000,
                    1700868840000,
                    1700868900000,
                    1700868960000,
                    1700869020000,
                    1700869080000,
                    1700869140000,
                    1700869200000,
                    1700869260000,
                    1700869320000,
                    1700869380000,
                    1700869440000,
                    1700869500000,
                    1700869560000,
                    1700869620000,
                    1700869680000,
                    1700869740000,
                    1700869800000,
                    1700869860000,
                    1700869920000,
                    1700869980000,
                    1700870040000,
                    1700870100000,
                    1700870160000,
                    1700870220000,
                    1700870280000,
                    1700870340000,
                    1700870400000,
                    1700870460000,
                    1700870520000,
                    1700870580000,
                    1700870640000,
                    1700870700000,
                    1700870760000,
                    1700870820000,
                    1700870880000,
                    1700870940000,
                    1700871000000,
                    1700871060000,
                    1700871120000,
                    1700871180000,
                    1700871240000,
                    1700871300000,
                    1700871360000,
                    1700871420000,
                    1700871480000,
                    1700871540000,
                    1700871600000,
                    1700871660000,
                    1700871720000,
                    1700871780000,
                    1700871840000,
                    1700871900000,
                    1700871960000,
                    1700872020000,
                    1700872080000,
                    1700872140000,
                    1700872200000,
                    1700872260000,
                    1700872320000,
                    1700872380000,
                    1700872440000,
                    1700872500000,
                    1700872560000,
                    1700872620000,
                    1700872680000,
                    1700872740000,
                    1700872800000,
                    1700872860000,
                    1700872920000,
                    1700872980000,
                    1700873040000,
                    1700873100000,
                    1700873160000,
                    1700873220000,
                    1700873280000,
                    1700873340000,
                    1700873400000,
                    1700873460000,
                    1700873520000
                  ],
                  [
                    176864487464,
                    185142964945,
                    184424688369,
                    182772167534,
                    181334188091,
                    176487750895,
                    182535526915,
                    176419361271,
                    180159495267,
                    177844282618,
                    179669512923,
                    173024903300,
                    178325211407,
                    179028552474,
                    176077825150,
                    170145171875,
                    172630128785,
                    164488177744,
                    175183200611,
                    168879553636,
                    167833567383,
                    163069852468,
                    164399140159,
                    159654664395,
                    163295374182,
                    163629930715,
                    162637142233,
                    157633330405,
                    160355800540,
                    157050248877,
                    156608414997,
                    157564757654,
                    157840052336,
                    156043063827,
                    155131137796,
                    150453910065,
                    148828453615,
                    152120381119,
                    152188470866,
                    152231488522,
                    151409814815,
                    147090829590,
                    145378043660,
                    148328256133,
                    149157067532,
                    147677018900,
                    145599264224,
                    139471897086,
                    133928917330,
                    140427270855,
                    139720996995,
                    138028053409,
                    137821514711,
                    136360374883,
                    127902886779,
                    136238284165,
                    135757874966,
                    133868574301,
                    133536994904,
                    132652233075,
                    127952442863,
                    126392521246,
                    129581672648,
                    129213895898,
                    128594351385,
                    128888871651,
                    125851282132,
                    125404706705,
                    128922261904,
                    130487896649,
                    128618561162,
                    125444201538,
                    127436628898,
                    127166187835,
                    123181633763,
                    126559664312,
                    120288839837,
                    121294860219,
                    121593793220,
                    121328499025,
                    118747547847,
                    112178044380,
                    117915826085,
                    116903194609,
                    118564412883,
                    115684226675,
                    119382682625,
                    115950369595,
                    108834218808,
                    113255832991,
                    114834522471,
                    114324180916,
                    114985374010,
                    112397169665,
                    105370771493,
                    110545730303,
                    111191400711,
                    111081238753,
                    109746513485,
                    109376871661,
                    107971659929,
                    103086746161,
                    108281887536,
                    105912431381,
                    105978950751,
                    106012444469,
                    104548440375,
                    100522060215,
                    101119761953,
                    103179188793,
                    101998247173,
                    100075455361,
                    100938367788,
                    98494340511,
                    98151073726,
                    100298475758,
                    99048661520,
                    99048661520
                  ]
                ]
              }
            },
            {
              "schema": {
                "name": "speed out",
                "fields": [
                  {
                    "name": "Time",
                    "type": "time",
                    "config": {}
                  },
                  {
                    "name": "Value",
                    "type": "number",
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    1700866501000,
                    1700869605000,
                    1700873502000
                  ],
                  [
                    800000000000,
                    400000000000,
                    400000000000
                  ]
                ]
              }
            },
            {
              "schema": {
                "meta": {
                  "dataTopic": "annotations"
                },
                "fields": [
                  {
                    "name": "type",
                    "config": {},
                    "type": "string"
                  },
                  {
                    "name": "color",
                    "config": {},
                    "type": "string"
                  },
                  {
                    "name": "time",
                    "config": {},
                    "type": "time"
                  },
                  {
                    "name": "timeEnd",
                    "config": {},
                    "type": "number"
                  },
                  {
                    "name": "text",
                    "config": {},
                    "type": "string"
                  },
                  {
                    "name": "source",
                    "config": {},
                    "type": "other"
                  },
                  {
                    "name": "isRegion",
                    "config": {},
                    "type": "boolean"
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "Weekends"
                  ],
                  [
                    "rgba(255, 255, 255, 0.04)"
                  ],
                  [
                    1700863200000
                  ],
                  [
                    1701036000000
                  ],
                  [
                    "Weekends"
                  ],
                  [
                    {
                      "datasource": {
                        "type": "datasource",
                        "uid": "grafana"
                      },
                      "enable": true,
                      "hide": false,
                      "iconColor": "rgba(255, 255, 255, 0.04)",
                      "mappings": [],
                      "name": "Weekends",
                      "tags": [],
                      "target": {
                        "queryType": "timeRegions",
                        "refId": "Anno",
                        "timeRegion": {
                          "from": "22:00",
                          "fromDayOfWeek": 5,
                          "timezone": "utc",
                          "to": "22:00",
                          "toDayOfWeek": 7
                        }
                      }
                    }
                  ],
                  [
                    true
                  ]
                ]
              }
            }
          ]
        }
      ],
      "title": "Reproduced with embedded data",
      "transformations": [],
      "transparent": true,
      "type": "timeseries"
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >timeseries @ 10.3.0-pre (bac4bba1a81)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[undefined]</td>\n    </tr>\n    <tr>\n      <th>Transform</th>\n      <td></td>\n  </tr>\n    <tr><th>Data</th><td> 2 frames, 4 fields, 121 rows </td></tr>\n    <tr>\n  <th>Annotations</th>\n  <td><span>1</span></td>\n</tr>\n    <tr>\n      <th>Grafana</th>\n      <td>10.3.0-pre (bac4bba1a81) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"datasource\": {\n    \"uid\": \"-- Mixed --\",\n    \"type\": \"datasource\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"drawStyle\": \"line\",\n        \"lineInterpolation\": null,\n        \"barAlignment\": 0,\n        \"lineWidth\": 1,\n        \"fillOpacity\": 80,\n        \"gradientMode\": \"none\",\n        \"spanNulls\": false,\n        \"insertNulls\": false,\n        \"showPoints\": \"never\",\n        \"pointSize\": 1,\n        \"stacking\": {\n          \"mode\": \"normal\",\n          \"group\": \"A\"\n        },\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"axisBorderShow\": false,\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"thresholdsStyle\": {\n          \"mode\": \"line\"\n        },\n        \"axisWidth\": 90\n      },\n      \"color\": {\n        \"mode\": \"palette-classic\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"absolute\",\n        \"steps\": [\n          {\n            \"color\": \"transparent\",\n            \"value\": null\n          }\n        ]\n      },\n      \"decimals\": 2,\n      \"fieldMinMax\": false\n    },\n    \"overrides\": [\n      {\n        \"matcher\": {\n          \"id\": \"byRegexp\",\n          \"options\": \"/ out$/\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"custom.stacking\",\n            \"value\": {\n              \"group\": \"A\",\n              \"mode\": \"normal\"\n            }\n          }\n        ]\n      },\n      {\n        \"matcher\": {\n          \"id\": \"byRegexp\",\n          \"options\": \"/(ole) .+$/\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"color\",\n            \"value\": {\n              \"fixedColor\": \"#508642\",\n              \"mode\": \"fixed\"\n            }\n          },\n          {\n            \"id\": \"custom.lineWidth\",\n            \"value\": 0\n          },\n          {\n            \"id\": \"unit\",\n            \"value\": \"bps\"\n          }\n        ]\n      },\n      {\n        \"matcher\": {\n          \"id\": \"byRegexp\",\n          \"options\": \"/speed .+$/\"\n        },\n        \"properties\": [\n          {\n            \"id\": \"color\",\n            \"value\": {\n              \"fixedColor\": \"#ef843c\",\n              \"mode\": \"fixed\"\n            }\n          },\n          {\n            \"id\": \"custom.fillOpacity\",\n            \"value\": 0\n          },\n          {\n            \"id\": \"custom.lineInterpolation\",\n            \"value\": \"stepAfter\"\n          },\n          {\n            \"id\": \"custom.lineWidth\",\n            \"value\": 1\n          },\n          {\n            \"id\": \"custom.stacking\",\n            \"value\": {\n              \"group\": false,\n              \"mode\": \"none\"\n            }\n          },\n          {\n            \"id\": \"unit\",\n            \"value\": \"bps\"\n          }\n        ]\n      }\n    ]\n  },\n  \"gridPos\": {\n    \"h\": 8,\n    \"w\": 24,\n    \"x\": 0,\n    \"y\": 0\n  },\n  \"id\": 1,\n  \"links\": [],\n  \"minSpan\": null,\n  \"options\": {\n    \"tooltip\": {\n      \"mode\": \"multi\",\n      \"sort\": \"desc\"\n    },\n    \"legend\": {\n      \"showLegend\": true,\n      \"displayMode\": \"table\",\n      \"placement\": \"right\",\n      \"calcs\": [\n        \"max\",\n        \"last\",\n        \"pctl95\"\n      ],\n      \"width\": 420\n    }\n  },\n  \"repeat\": null,\n  \"repeatDirection\": null,\n  \"targets\": [\n    {\n      \"datasource\": \"JSON\",\n      \"alias\": \"\",\n      \"payload\": \"{\\\"timeseries_group_by\\\":\\\"none\\\",\\\"force_second_y_axis\\\":true,\\\"panel_type\\\":\\\"timeseries\\\"}\",\n      \"refId\": \"A\",\n      \"target\": \"a\",\n      \"editorMode\": \"code\"\n    }\n  ],\n  \"title\": \"Hi\",\n  \"transformations\": [],\n  \"transparent\": true,\n  \"type\": \"timeseries\"\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    },
    {
      "id": 7,
      "gridPos": {
        "h": 6,
        "w": 24,
        "x": 0,
        "y": 20
      },
      "type": "table",
      "title": "Annotations",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "topic": "annotations",
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: Hi // 2023-12-14 16:50:21",
  "tags": [
    "debug",
    "debug-timeseries"
  ],
  "time": {
    "from": "2023-11-24T22:55:56.550Z",
    "to": "2023-11-25T00:51:42.968Z"
  }
}
```
</details>

### Environment (with versions)?

Grafana: 9e52414a912b0bfa853d16eb538aa7ac4cdd63d1
OS: macos
Browser: chrome

### Grafana platform?

Other

**Comment by leeoniya** [comment] 2023-12-14 18:25
duplicate of https://github.com/grafana/grafana/issues/60956#issuecomment-1490883094

**Closed by leeoniya** 2023-12-14 18:25 UTC
Labels: area/panel/timeseries

**Comment by simPod** [comment] 2023-12-15 12:08
Ok, I've adapted my backend. Thanks.
