### ISSUE TITLE
Missing min value in Heatmap legend / no auto min

### ISSUE THREAD

**Issue by cgfoed** [grafana/grafana#24849] opened 2020-05-19 09:23 UTC
It seems to me, that the displayed min value is fixed to 0, somehow?
In my example the boundries should have been min 80 and max 150

![image](https://user-images.githubusercontent.com/53257619/82309182-1ba9b280-99c3-11ea-9c6f-b3d0393d2482.png)

**Comment by cgfoed** [comment] 2020-05-19 13:34
Maybe I should add, that I'm using Time Series Buckets here with each bucket containing only one value or null
If I leave the color scale config on auto, it seems to detect the upper max value fine but the lower value for the color scale remains at 0

**Comment by peterholmberg** [comment] 2020-06-04 11:45
Hello, 
thanks for reporting this. Could you provide a minimum steps to reproduce this. Thanks.

**Comment by cgfoed** [comment] 2020-06-09 06:46
I hope this helps:
![minmax github bug grafana](https://user-images.githubusercontent.com/53257619/84115089-bc711800-aa2d-11ea-965b-cb45a670db39.PNG)

**Comment by peterholmberg** [comment] 2020-10-15 09:29
@cgfoed Sorry for the extremely late reply. I could not reproduce this on the latest master, care to check if this is still an issue?

**Comment by cgfoed** [comment] 2020-10-22 10:05
Hi peterholmberg, Thx for catching up!
I'm using Grafana v7.1.5 (9893b8c53d)

Please find attached some more information that hopefully provide some insight.
[Histogram - Grafana - Problem Example.zip](https://github.com/grafana/grafana/files/5421896/Histogram.-.Grafana.-.Problem.Example.zip)

PW is your username!

**Comment by hugohaggmark** [comment] 2020-10-30 10:11
Confirmed on Grafana v7.4.0-pre (76fb7ee494)

**Comment by hugohaggmark** [comment] 2020-10-30 10:15
This line looks wrong for the auto value:
https://github.com/grafana/grafana/blob/e8bfb2185184c7b36b05d21176515a8e139ee945/public/app/plugins/panel/heatmap/rendering.ts#L545

This line also looks wrong for the legend:
https://github.com/grafana/grafana/blob/e8bfb2185184c7b36b05d21176515a8e139ee945/public/app/plugins/panel/heatmap/color_legend.ts#L74

**Comment by lukewing** [comment] 2020-11-04 19:36
@hugohaggmark @torkelo I am looking at contributing for a class project. May I take on this item?

**Comment by torkelo** [comment] 2020-11-04 20:34
Yes that be much appreciated

**Comment by lukewing** [comment] 2020-11-05 17:50
@cgfoed Do you have any more information as to how I can reproduce this locally?

**Comment by hugohaggmark** [comment] 2020-11-06 05:22
@lukewing using the data supplied by @cgfoed should be enough to repro.

I used [Google Spread Sheets plugin](https://grafana.com/grafana/plugins/grafana-googlesheets-datasource/installation) and this [dashboard.json](https://gist.github.com/hugohaggmark/eab43edb4647bf9cdbfcc43394b03b07).

**Comment by cgfoed** [comment] 2021-01-06 14:06
@lukewing could you find a solution already?

**Comment by kurokochin** [comment] 2021-02-23 16:48
Hi @hugohaggmark I'll help to work on this :)

**Comment by peterholmberg** [comment] 2021-03-03 09:33
Closed by #31430

**Closed by peterholmberg** 2021-03-03 09:33 UTC
Labels: area/panel/heatmap, beginner friendly, effort/small, help wanted, type/bug
