### ISSUE TITLE
Cannot save changes to Home dashboard

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#3846] opened 2016-01-25 18:39 UTC
I'm trying to increase the number of displayed dashboards in the dashboards panel on the Home dashboard and while that works there seems to be no way to make this change persistent. There is no save icon like for the other dashboards and using "save as..." trying to overwrite "Home" creates a new dashboard with that name instead and doesn't change the actual home dashboard.
Is there something special that needs to be done to modify the home dashboard?

**Comment by torkelo** [comment] 2016-01-25 19:20
dupe of https://github.com/grafana/grafana/issues/1678

**Closed by torkelo** 2016-01-25 19:20 UTC
