### ISSUE TITLE
Dashboards: Loki data source Variables not returning results within dashboard time range, stuck at 6h.

### ISSUE THREAD

**Issue by hermesribeiro** [grafana/grafana#80508] opened 2024-01-13 17:43 UTC
### What happened?

When using Loki data source to create "label values" dashboard variables, the query always uses a time range of 6h regardless if the dashboard time range is lower or higher than six hours.

### What did you expect to happen?

Label values to be populated according the user selected time range in the dashboard.

### Did this work before?

Not sure. Mimir data source is working correctly.

### How do we reproduce it?

1. Create a dashboard variable with `Data source: Loki`, `Query type: Label values`, `Label: pod`.
2. Inspect visually that all labels returned are within 6h time range.
3. Open browser network inspector and find the `start` parameter for `*/series` or `*/values` requests and see that it equals `end-6h`.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.2.3 (1e84fede54)
OS: Ubuntu 23.10
Browser: Chrome 120.0.6099.216 (Official Build) (64-bit)

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by MiggL** [comment] 2024-02-02 15:35
@itsmylife This is the same issue that you solved for prometheus variables in #78950, no?

**Comment by ivanahuckova** [comment] 2024-02-16 13:16
@MiggL, I am not able to reproduce this. Could you please check, if you have **Refresh** set to **On time range change**? 

<img width="537" alt="image" src="https://github.com/grafana/grafana/assets/30407135/ffeb8173-4aaa-46b4-ad96-1a2747ce01d1">

**Comment by MiggL** [comment] 2024-02-27 09:13
@ivanahuckova Yes, I have **Refresh** set to **On time range change**. However, this issue seems to be solved in the latest version(s). It works correctly for me in Grafana 10.3.3, but I can still reproduce the issue in Grafana 10.2.3. Strange, as I cannot find anything in the changelog referring to this.

**Comment by ivanahuckova** [comment] 2024-02-27 10:08
I think that https://github.com/grafana/grafana/pull/79326 fixed the issue. Thanks again for reporting and confirming that it works on v10.3+. 🙏  Closing the issue. 🙂

**Closed by ivanahuckova** 2024-02-27 10:08 UTC
Labels: needs more info, datasource/Loki
