### ISSUE TITLE
Tooltip Sort Broken Time Series Chart v8.4.7+ on Windows

### ISSUE THREAD

**Issue by timlharrison** [grafana/grafana#49756] opened 2022-05-27 16:37 UTC
**What happened**:
The hover-over tooltip with all data shown is not sorting properly descending or ascending.

**What you expected to happen**:
Sort to sort numbers correctly

**How to reproduce it (as minimally and precisely as possible)**:
Create a time series panel with multiple series, change tooltip to "All" and "Descending"

**Anything else we need to know?**:
I'm not sure exactly when this issue first appeared - it may not only be in 8.4.7. Also it isn't happening on every chart all the time -- it seems to be somewhat random.

**Update**: I upgraded to 8.5.3 and the issue persists.

**Environment**:
- Grafana version: 8.4.7 (and 8.5.3)
- Data source type & version: Prometheus 2.35
- OS Grafana is installed on: Windows 2016
- User OS & Browser: Windows 10 + Chrome
- Grafana plugins: n/a
- Others:

![image](https://user-images.githubusercontent.com/33101253/170741311-7890a6c5-1186-4d3a-8c5b-e23d3173c9ed.png)
![image](https://user-images.githubusercontent.com/33101253/170741817-7b2cc9b5-3b34-4dcf-a0fd-8f584a6b579b.png)

**Comment by mellieA** [comment] 2022-06-01 02:49
I was able to reproduce this with Prometheus but not on another time-series graph that uses the graphite datasource.

**Comment by srclosson** [comment] 2022-06-02 14:13
Is this only on windows? Only prometheus? Needs investigation...

**Comment by mellieA** [comment] 2022-06-02 15:21
@srclosson I realized I was looking at the legend not the tooltip. I can't reproduce this on my mac after all.

**Comment by timlharrison** [comment] 2022-06-02 15:46
I just ran Grafana 7.5.16-ubuntu Docker container pointed at my Prometheus server and the issue wasn't there. I spun up a Grafana 8.5.3-ubuntu Docker container and the issue is there. 

So the issue exists with the Linux Grafana 8.5.x Docker image + (my) Windows-based Prometheus.

**Comment by timlharrison** [comment] 2022-06-02 16:00
I just reproduced this with the official Grafana 8.5.3-ubuntu Docker image pointed at the official Prometheus latest Docker image on my local machine. Just spin up both, create a time series using this query "go_gc_duration_seconds{instance="localhost:9090"}" and change the tooltip to All/Descending and move the mouse over the time series. Sometimes its sorted correctly and sometimes it isn't. This isn't just a Windows issue. Notice in the image below, tooltip is All/Descending and the bottom two in the tooltip are out of order as it has 0.0000237 **above** 0.0000820

![image](https://user-images.githubusercontent.com/33101253/171673401-321495bf-9634-4d42-af90-3bcda88322dc.png)

**Comment by codeincarnate** [comment] 2022-06-27 14:11
This should be fixed by https://github.com/grafana/grafana/pull/49084 but please re-open if that's not the case.

**Closed by codeincarnate** 2022-06-27 14:11 UTC
Labels: type/bug, datasource/Prometheus, needs investigation, area/panel/timeseries
