### ISSUE TITLE
Shared tooltip bug

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#32831] opened 2021-04-09 08:32 UTC
**What happened**: 
Shared tooltip stopped working between graph panel and custom panel plugins (in my case grafana-discrete-panel)

**What you expected to happen**:
In the previous version 7.3.7, the shared tooltip worked fine

**Environment**:
- Grafana version: 7.5.3
- Data source type & version: Postgres 12 + timescaleDB
- OS Grafana is installed on: ubuntu 20.04
- User OS & Browser: chrome 89 + windows 10
- Grafana plugins: grafana-discrete-panel

**Comment by ivanahuckova** [comment] 2021-04-09 13:37
Yeah, I can reproduce this. Not sure if this should be fixed in Grafana or Discrete panel. Passing to platform team for investigation. 
![image](https://user-images.githubusercontent.com/30407135/114188322-4ee19100-9949-11eb-9ab4-324abd1ff3ee.png)
![image](https://user-images.githubusercontent.com/30407135/114188343-54d77200-9949-11eb-8796-bc39f7cb12fa.png)

**Comment by dprokop** [comment] 2021-04-14 08:32
@DmitrySidorow what version of te discrete-panale are you using?

**Comment by DmitrySidorow** [comment] 2021-04-14 08:33
> @DmitrySidorow what version of te discrete-panale are you using?

latest 0.1.0

**Comment by fatbasstard** [comment] 2021-04-26 07:11
Any update on this issue?

**Comment by DmitrySidorow** [comment] 2021-05-18 13:33
it was broken in 7.4.0-beta1

**Comment by torkelo** [comment] 2021-06-21 07:48
Closing this, not a bug in Grafana. We changed the event from being emitted on the appEvents emitter to the dashboard events, probably done in 7.3 or there about

**Closed by torkelo** 2021-06-21 07:48 UTC
Labels: area/dashboard, needs investigation, priority/important-soon, type/bug
