### ISSUE TITLE
Documentation for Standalone MacOS/Darwin Binaries doesn't match download assets

### ISSUE THREAD

**Issue by geuis** [grafana/grafana#13772] opened 2018-10-21 05:05 UTC
At the end of this page, https://grafana.com/grafana/download?platform=mac, the standalone archive that is referenced is `https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.1.darwin-amd64.tar.gz`.

On the installation instructions at `http://docs.grafana.org/installation/mac/` the instructions are:

```
Installing from binary tar file
Download the latest .tar.gz file and extract it. This will extract into a folder named after the version you downloaded. This folder contains all files required to run Grafana. There are no init scripts or install scripts in this package.

To configure Grafana add a configuration file named custom.ini to the conf folder and override any of the settings defined in conf/defaults.ini.

Start Grafana by executing ./bin/grafana-server web. The grafana-server binary needs the working directory to be the root install directory (where the binary and the public folder is located).
```

However, the assets that are untarred from the above mentioned link does not include a `./bin` directory and the included README.md does not have any relevant directions.

**Comment by torkelo** [comment] 2018-10-22 07:44
duplicate of https://github.com/grafana/grafana/issues/13763

**Closed by torkelo** 2018-10-22 07:44 UTC

**Comment by xlson** [comment] 2018-10-22 10:10
@geuis We just found out last week that there is a problem with our Mac builds of Grafana that have resulted in bad archives. We are looking into a fix, in the meantime I would suggest you use [Homebrew](http://docs.grafana.org/installation/mac/) to install Grafana (if that is an option). Alternatively, you can [build Grafana from source](http://docs.grafana.org/project/building_from_source/) yourself.
