### ISSUE TITLE
Snapshot does not match the dashboard

### ISSUE THREAD

**Issue by marianoju** [grafana/grafana#47050] opened 2022-03-30 10:34 UTC
**What happened**: 
I have created a Snapshot (by selecting Share > Snapshot, see [documentation](https://grafana.com/docs/grafana/latest/sharing/share-dashboard/)) and published to snapshot.raintank.io (which redirects to snapshots-origin.grafana.net). When I open the URL, the dashboard displayed does not match my original dashboard. See my [stackoverflow post](https://stackoverflow.com/questions/71675049/) for screenshots. 

**What you expected to happen**:
I expected the snapshot to be a somewhat static representation of the original dashboard, mirroring numeric values and graphs. 

**How to reproduce it (as minimally and precisely as possible)**: 
Create a snapshot of a dashboard, publish to snapshot.raintank.io and compare snapshot and original dashboard's selection used to create snapshot. 

**Anything else we need to know?**:
Snapshot encompasses two months of second-by-second data points. Is there possibly a limitation on the data volume to be hosted by snapshot.raintank.io? 

**Environment**:
- Grafana version: 8.0.0-beta1 (84203aaff8) 
- Data source type & version: PostgreSQL 13.3 
- OS Grafana is installed on: unknown (Cloud Server) 
- User OS & Browser: tested with Mozilla Firefox, Chrome and Chromium (latest versions) on MS Windows 10 and Ubuntu 20.04 
- Grafana plugins: unknown 
- Others:

**Comment by mellieA** [comment] 2022-07-29 00:42
@marianoju Are you still seeing this issue with a newer version of grafana? You can test it out on our demo server at 

https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=10s&from=now-5m&to=now

I tried it on play and couldn't reproduce what you saw in version 8.0 beta. The snapshot should match the dashboard you see frozen in the background when it is created. I'll close this for now, but please reopen it if you're still seeing this issue and we can dig deeper.

**Closed by mellieA** 2022-07-29 00:42 UTC
Labels: area/dashboard/snapshot, needs investigation, oss-user-essentials

**Comment by marianoju** [comment] 2022-08-14 12:22
@mellieA I do not have access to the Grafana instance anymore. I can neither confirm nor dispute a solution to the issue.
