### ISSUE TITLE
InfluxDB: Influx schema Queries not working with Grafana time variable "v.timeRangeStart"

### ISSUE THREAD

**Issue by R-Studio** [grafana/grafana#30414] opened 2021-01-20 09:07 UTC
**What happened**:
I want to use some InfluxDB Flux schema functions in Grafana, but this is not working with Grafana time variable "v.timeRangeStart".
For example with the function [schema.tagValues()](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/tagvalues/)

If I use this schema function in a Grafana table panel and using "v.timeRangeStart" the following error occurs:
![image](https://user-images.githubusercontent.com/7498854/105151344-20040d80-5b06-11eb-9145-45b3fa404606.png)

**What you expected to happen**:
I expect that this is working with the Grafana default variables.
If I replace the "v.timeRangeStart" for example with "-30d" then this is working:
![image](https://user-images.githubusercontent.com/7498854/105151606-71140180-5b06-11eb-9b5a-357d6e64295f.png)

If I use "v.timeRangeStart" in the InfluxDB Explorer, this is working as expected.

**Anything else we need to know?**:
_There are a lot of other Grafana issues with InfluxDB v2.x and Flux and I hope this issues with Flux will be fixed soon. Right now I use a lot of workarounds to are able to work with Grafana and InfluxDB 2.x Flux. That is a real shame._

**Environment**:
- Grafana version: 7.3.5
- Data source type: InfluxDB Flux
- OS Grafana is installed on: a VM
- User OS & Browser: Chrome
- Grafana plugins: Built-In InfluxDB Flux datasource

**Comment by philomory** [comment] 2021-01-29 00:45
Sadly, I don't think this is a Grafana issue, I think it _is_ an InfluxDB issue.

The "start" argument for `schema.tagValues` (as in most similar functions) is documented as taking both a time, or a (negative) duration. However, it only _actually_ accepts a negative duration. If you pass it a time, it'll fail.

In InfluxDB, whether `v.timeRangeStart` is a Time or a Duration depends on whether you selected a pre-set duration from the drop-down menu (e.g. "Past 1h"), or entered a custom time range. If you enter a custom time range, v.timeRangeStart is a time rather than a duration, and in that case it doesn't work for `schema.tagValues` in InfluxDB either. More basically, if you manually enter a time literal, it doesn't work in InfluxDB, even though the documentation says it should.

The only difference between InfluxDB's UI and Grafana's, here, is that Grafana consistently uses a Time value for v.timeRangeStart, rather than switching between Time and Duration values depending on what you've selected in the UI.

This is probably better fixed in InfluxDB than in Grafana.

**Comment by R-Studio** [comment] 2021-01-29 10:31
I thought this is a Grafana bug, because with the same "variable" in Influx it is working. But now it is clear, thanks for your feedback.
Should I close the issue or we wait until the flux issue is fixed?

**Comment by gabor** [comment] 2021-03-26 10:57
hi, i think we will close this issue, because the problem is in influxDB and they are working on improving the situation. if there will be problems still after the "influxdb fix", we can reopen the issue.

**Closed by gabor** 2021-03-26 10:57 UTC
Labels: datasource/InfluxDB/flux, needs investigation, type/bug

**Comment by R-Studio** [comment] 2021-03-30 13:11
@gabor Do you have the related issue on InfluxDB?
