### ISSUE TITLE
[Bug] multiple old axis

### ISSUE THREAD

**Issue by miton18** [grafana/grafana#9126] opened 2017-08-30 09:44 UTC
- What Grafana version are you using? **Master ? commit 54129b13401964c065f132aa101753315c270e64**
- What datasource are you using? **Warp10/OpenTSDB**
- What OS are you running grafana on? **Tux**
- What did you do? **change timerange** 
- What was the expected result? **a clean chart**
- What happened instead? **All previous axis stay on the graph**

Sometimes, On Firefox#55 the old graph panels doesn't clean their old X and Y axis, no problem on Chromium

![grafana-problem](https://user-images.githubusercontent.com/5887985/29866375-82668516-8d78-11e7-88e9-4ad5623d6abb.png)

**Comment by daniellee** [comment] 2017-08-31 09:37
Any way to reproduce this? I'm not seeing this on my machine with Firefox. 

- Do you see the same bug if you open Grafana in a private window?
- How often is "sometimes"?

**Comment by miton18** [comment] 2017-09-08 09:29
Try to grep some data on FireFox and change the time range of the query

**Comment by miton18** [comment] 2017-10-22 13:19
Hi some updates ?
last news : it seems "flot-x-axis" is not cleaned at every time range update

![grafana](https://user-images.githubusercontent.com/5887985/31862318-3770a026-b73c-11e7-98fa-e04865bbe0ea.PNG)

**Comment by daniellee** [comment] 2017-10-27 16:44
Testing on Firefox 56 and I cannot recreate this. I have tried with graphs with no datapoints and changing the time range and zooming in and out. 

What settings do you have on your axes tab? Wondering if it could be something to do with logscale?

**Comment by hikatanguy** [comment] 2018-04-25 10:28
Also happens with datapoints: 
![image](https://user-images.githubusercontent.com/25170344/39240466-1e6df806-4884-11e8-8da9-55a317f141af.png)

**Comment by torkelo** [comment] 2019-09-18 12:49
closing this due to lack of reports / way to replicate

**Closed by torkelo** 2019-09-18 12:49 UTC
Labels: area/panel/graph
