### ISSUE TITLE
Feature Request: provide OFFSET support (for influxdb)

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#13960] opened 2018-11-04 14:01 UTC
In this thread:
https://github.com/influxdata/influxdb/issues/6451#issuecomment-255583038

many users complain about influxdb's inability to deal well with the first piece of data returned when using some transformation functions.

To implement the workaround in grafana currently requires changing the edit mode for the query to add "OFFSET 1".

Yes it would be good to just see this part of InfluxQL supported but that's not what I really care about - just dropping the first outrageous metric value returned by influxdb is.

Whether it is a check-box ("add OFFSET(1) [X]") that can be selected per query or even is only presented when the derivative functions are used, I don't care. I would also be happy if grafana had an option to "Drop First Result" or "Drop first result when first result outside of 2 sigma from the 2nd" (i.e. likely that influxdb bug is flashing us) regardless of the query syntax used.

**Comment by marefr** [comment] 2018-11-05 16:53
Duplicate of #6401

**Closed by marefr** 2018-11-05 16:53 UTC
