### ISSUE TITLE
Error broken pipe on dashboard

### ISSUE THREAD

**Issue by checkk22** [grafana/grafana#29957] opened 2020-12-22 13:55 UTC
since the upgrade of grafana from 6.4.3 to 7.3.5 we have encountered “broken pipe” problems. The dashboards all put in error after a few hours of use, as seen below.

`"write tcp 127.0.0.1:59132->127.0.0.1:5432:write: broken pipe"`
Grafana is linked to a postgresql 10 database on the same server.

A restart of the grafana services makes it possible to solve it, for x time but this solution is not viable.
we have tried to modify Max lifetime in db settings, but without success
Do you have an idea ?

thanks in advance

**Environment**:
- Grafana version:7.3.5
- Data source type & version: postgresql 10
- OS Grafana is installed on: ubuntu
- User OS & Browser: windows & chrome
- Grafana plugins: worldmap
- Others:

**Comment by dprokop** [comment] 2020-12-23 09:52
@checkk22 you can take a look at https://github.com/grafana/grafana/issues/15707 which has a discussion about a similar issue, but with MySQL.

**Comment by checkk22** [comment] 2020-12-29 10:19
@dprokop indeed, I have already looked at this post. However there is no reconnection string `?reconnect=true` in postgresql, normally it keeps the connections open.

I have forced the max lifetime duration to 1800 on a short duration to force the recreation of the connection, but the problem is still roaming

**Comment by wbrowne** [comment] 2021-01-04 14:47
>Grafana is linked to a postgresql 10 database on the same server.

@checkk22 Can you provide more detail here? Are you able to reproduce with a minimal setup e.g. Grafana 7.3.5 and PostgresQL 10 running in Docker, or provide some more info to help us replicate the issues you're seeing?

How long does it take for the problem to occur? And does that depend on the `conn_max_lifetime` config?

**Comment by checkk22** [comment] 2021-01-04 17:14
Grafana and postgresql are installed in an ubuntu 18.04 machine, we don't use docker but in the coming weeks we will be setting up a test environment under docker, to try to work around this problem. 
I would therefore have at this time more information on this.

in terms of the environment, it's pretty basic, apart from using timescaldb on postgresql, on grafana we only have one plugins in addition to the core: worldmap

![grafana-error_LI](https://user-images.githubusercontent.com/76479659/103558832-8ad20980-4eb5-11eb-8421-966b0de43b9e.jpg)

in grafana.log when trying to access:
![log-error](https://user-images.githubusercontent.com/76479659/103559984-52cbc600-4eb7-11eb-81ae-bfb609e09f42.png)

I did not feel any relation with the max lifetime value, we restart the grafana server every 30 minutes to avoid the problem, sometimes it happens that it is triggered even before this duration. This one is currently at 1800, but I will reset it to default

**Comment by uebenes** [comment] 2021-02-11 11:12
I have the same problem with Postgres 12 and Ubunto 20.04

**Comment by zuehlke-dea** [comment] 2021-02-16 09:52
We see the same issue since the weekend. 

We are connecting to a AWS Redshift Cluster (based on PSQL). There was a patch on the weekend which does not really say something in this direction (https://forums.aws.amazon.com/ann.jspa?annID=8530) but we have not face this issue before.

**Comment by marefr** [comment] 2021-02-16 17:43
Please try Grafana v7.4.x:
- Found this issue in the repository of the postgres library we're using: https://github.com/lib/pq/issues/870
- That issue linked to this merged PR: https://github.com/lib/pq/pull/1013
- That change was included in lib/pq v1.9.0
- Grafana upgraded lib/pq dependency to v1.9.0 via https://github.com/grafana/grafana/pull/30181 which is included in Grafana v7.4.0-beta1

Let us know if that makes any difference. Thanks

**Comment by zuehlke-dea** [comment] 2021-02-17 07:32
Thx for the support! 

We adjusted the datasource connection to 
![image](https://user-images.githubusercontent.com/5172182/108170534-904c8180-70fa-11eb-8b59-b3b3eea7af9a.png)
Since then we have not faced the issue anymore. 

But I removed this in our Test environment and we will update to the newest version (I have only not seen any changes in the release notes, my bad ;) )

We keep you updated

**Comment by zuehlke-dea** [comment] 2021-02-25 15:59
We tested now the new release 7.4.2 in dev environment for a week. It seems to fix the problem.
Before we removed the connection config again (which also seemed to solve the issue) and saw the problem occure again multiple times. After upgrading to 7.4.2 we have not seen the issue again. 

Let's see how it works in the future. 
Thx again  for the support here!

**Comment by wbrowne** [comment] 2021-02-25 16:16
Great to hear @zuehlke-dea! So to confirm, on v7.4.2 the problem does not occur either with or without the connection configuration?

**Comment by zuehlke-dea** [comment] 2021-02-25 16:20
We have tested 7.4.2 only without the configuration, where the problem occurred before with 7.3.5

With the configuration it seems also not happen in 7.3.5 But only with the lifetime of 1800.. We had a different time before (I only do not remember which one, I think it was lower) where the problem occurred also .

**Comment by wbrowne** [comment] 2021-02-25 17:15
Interesting findings - thanks for the information @zuehlke-dea!

In that case, I think we can close this issue now. If this re-occurs we can always re-open and continue the discussion.

Thanks for contributing to Grafana ❤️

**Closed by wbrowne** 2021-02-25 17:15 UTC
Labels: area/backend/db/postgres, datasource/Postgres, needs investigation

**Comment by denisle1981** [comment] 2024-08-06 09:12
Hi there,

We are facing the same issue. We use Grafana version 8.4.2, it's deployed in Openshift 4.12. The datasource is Prometheus.

Thanks in advance.
