### ISSUE TITLE
http: panic serving 10.0.2.3:35038: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by prologic** [grafana/grafana#47602] opened 2022-04-12 00:45 UTC
I'm seeing Grafana panic on what looks like an empty set of rows from the [Prometheus AlertManager Plugin](https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/)

```
mon_alertmanager.1.rnecgjj0lbld@dm2    | ts=2022-04-12T00:40:01.852Z caller=api.go:228 level=error component=api version=v2 path=/api/v2/alerts method=GET msg="Failed to parse matchers" err="bad matcher format: alertname"
mon_alertmanager.1.rnecgjj0lbld@dm2    | 2022/04/12 00:40:02 http: panic serving 10.0.2.3:35038: runtime error: index out of range [0] with length 0
mon_alertmanager.1.rnecgjj0lbld@dm2    | goroutine 31294 [running]:
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*conn).serve.func1()
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:1802 +0xb9
mon_alertmanager.1.rnecgjj0lbld@dm2    | panic({0xf619c0, 0xc000c66438})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/runtime/panic.go:1047 +0x266
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/pkg/labels.ParseMatcher({0xc000bcf090, 0xa})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/pkg/labels/parse.go:130 +0x692
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2.parseFilter({0xc0008e6f80, 0x1, 0xc0004a9538})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/api.go:666 +0xa7
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2.(*API).getAlertsHandler(0xc000266c60, {0xc00066e900, 0xc000bcf09a, {0xc0008e6f80, 0x1, 0x1}, 0xc000bcf09b, 0x0, 0xc000bcf09c, 0xc000bcf07c})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/api.go:226 +0x1ad
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2/restapi/operations/alert.GetAlertsHandlerFunc.Handle(0x1341218, {0xc00066e900, 0xc000bcf09a, {0xc0008e6f80, 0x1, 0x1}, 0xc000bcf09b, 0x0, 0xc000bcf09c, 0xc000bcf07c})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/restapi/operations/alert/get_alerts.go:33 +0x59
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2/restapi/operations/alert.(*GetAlerts).ServeHTTP(0xc000a1c408, {0x1337760, 0xc0007ec540}, 0xc00066e900)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/restapi/operations/alert/get_alerts.go:68 +0x25e
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x1337760, 0xc0007ec540}, 0xc00066e900)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/operation.go:28 +0x59
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x40d1f4, {0x1337760, 0xc0007ec540}, 0xc0002fd9e0)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.NewRouter.func1({0x1337760, 0xc0007ec540}, 0xc000972c00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/router.go:78 +0x25e
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x0, {0x1337760, 0xc0007ec540}, 0xe)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.Spec.func1({0x1337760, 0xc0007ec540}, 0xc0007a5aa8)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/spec.go:46 +0x18c
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0xc00073e480, {0x1337760, 0xc0007ec540}, 0xc000972c00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/rs/cors.(*Cors).Handler.func1({0x1337760, 0xc0007ec540}, 0xc000972c00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0xc0007fc300, {0x1337760, 0xc0007ec540}, 0x7fe68db55de8)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api.(*API).limitHandler.func1({0x1337760, 0xc0007ec540}, 0xc000972c00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/api.go:222 +0x1eb
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x0, {0x1337760, 0xc0007ec540}, 0x0)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*ServeMux).ServeHTTP(0xc000716313, {0x1337760, 0xc0007ec540}, 0xc000972c00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2425 +0x149
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.serverHandler.ServeHTTP({0xc000c500c0}, {0x1337760, 0xc0007ec540}, 0xc000972c00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2879 +0x43b
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*conn).serve(0xc00063c1e0, {0x1341218, 0xc0006c5fb0})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:1930 +0xb08
mon_alertmanager.1.rnecgjj0lbld@dm2    | created by net/http.(*Server).Serve
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:3034 +0x4e8
mon_alertmanager.1.rnecgjj0lbld@dm2    | 2022/04/12 00:40:02 http: panic serving 10.0.2.3:35156: runtime error: index out of range [0] with length 0
mon_alertmanager.1.rnecgjj0lbld@dm2    | goroutine 31304 [running]:
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*conn).serve.func1()
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:1802 +0xb9
mon_alertmanager.1.rnecgjj0lbld@dm2    | panic({0xf619c0, 0xc000b1e3c0})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/runtime/panic.go:1047 +0x266
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/pkg/labels.ParseMatcher({0xc0007dc630, 0xa})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/pkg/labels/parse.go:130 +0x692
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2.parseFilter({0xc000308ee0, 0x1, 0xc0007c5538})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/api.go:666 +0xa7
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2.(*API).getAlertsHandler(0xc000266c60, {0xc00020e500, 0xc0007dc63a, {0xc000308ee0, 0x1, 0x1}, 0xc0007dc63b, 0x0, 0xc0007dc63c, 0xc0007dc61c})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/api.go:226 +0x1ad
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2/restapi/operations/alert.GetAlertsHandlerFunc.Handle(0x1341218, {0xc00020e500, 0xc0007dc63a, {0xc000308ee0, 0x1, 0x1}, 0xc0007dc63b, 0x0, 0xc0007dc63c, 0xc0007dc61c})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/restapi/operations/alert/get_alerts.go:33 +0x59
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2/restapi/operations/alert.(*GetAlerts).ServeHTTP(0xc000a1c408, {0x1337760, 0xc000874540}, 0xc00020e500)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/restapi/operations/alert/get_alerts.go:68 +0x25e
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x1337760, 0xc000874540}, 0xc00020e500)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/operation.go:28 +0x59
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x40d1f4, {0x1337760, 0xc000874540}, 0xc0009b6f30)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.NewRouter.func1({0x1337760, 0xc000874540}, 0xc000489000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/router.go:78 +0x25e
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x0, {0x1337760, 0xc000874540}, 0xe)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.Spec.func1({0x1337760, 0xc000874540}, 0xc0009504a8)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/spec.go:46 +0x18c
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0xc00073e480, {0x1337760, 0xc000874540}, 0xc000489000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/rs/cors.(*Cors).Handler.func1({0x1337760, 0xc000874540}, 0xc000489000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0xc0007fc300, {0x1337760, 0xc000874540}, 0x7fe68db55b30)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api.(*API).limitHandler.func1({0x1337760, 0xc000874540}, 0xc000489000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/api.go:222 +0x1eb
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x0, {0x1337760, 0xc000874540}, 0x0)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*ServeMux).ServeHTTP(0xc0001022b3, {0x1337760, 0xc000874540}, 0xc000489000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2425 +0x149
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.serverHandler.ServeHTTP({0xc0009e4ba0}, {0x1337760, 0xc000874540}, 0xc000489000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2879 +0x43b
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*conn).serve(0xc00063c5a0, {0x1341218, 0xc0006c5fb0})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:1930 +0xb08
mon_alertmanager.1.rnecgjj0lbld@dm2    | created by net/http.(*Server).Serve
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:3034 +0x4e8
mon_alertmanager.1.rnecgjj0lbld@dm2    | 2022/04/12 00:40:02 http: panic serving 10.0.2.3:35172: runtime error: index out of range [0] with length 0
mon_alertmanager.1.rnecgjj0lbld@dm2    | goroutine 31311 [running]:
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*conn).serve.func1()
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:1802 +0xb9
mon_alertmanager.1.rnecgjj0lbld@dm2    | panic({0xf619c0, 0xc0000369f0})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/runtime/panic.go:1047 +0x266
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/pkg/labels.ParseMatcher({0xc0009071b0, 0xa})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/pkg/labels/parse.go:130 +0x692
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2.parseFilter({0xc0007c2420, 0x1, 0xc0007c9538})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/api.go:666 +0xa7
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2.(*API).getAlertsHandler(0xc000266c60, {0xc000973000, 0xc0009071ba, {0xc0007c2420, 0x1, 0x1}, 0xc0009071bb, 0x0, 0xc0009071bc, 0xc00090719c})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/api.go:226 +0x1ad
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2/restapi/operations/alert.GetAlertsHandlerFunc.Handle(0x1341218, {0xc000973000, 0xc0009071ba, {0xc0007c2420, 0x1, 0x1}, 0xc0009071bb, 0x0, 0xc0009071bc, 0xc00090719c})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/restapi/operations/alert/get_alerts.go:33 +0x59
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api/v2/restapi/operations/alert.(*GetAlerts).ServeHTTP(0xc000a1c408, {0x1337760, 0xc00019a7e0}, 0xc000973000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/v2/restapi/operations/alert/get_alerts.go:68 +0x25e
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x1337760, 0xc00019a7e0}, 0xc000973000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/operation.go:28 +0x59
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x40d1f4, {0x1337760, 0xc00019a7e0}, 0xc000b80000)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.NewRouter.func1({0x1337760, 0xc00019a7e0}, 0xc000972d00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/router.go:78 +0x25e
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x0, {0x1337760, 0xc00019a7e0}, 0xe)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/go-openapi/runtime/middleware.Spec.func1({0x1337760, 0xc00019a7e0}, 0xc000976a28)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/go-openapi/runtime@v0.23.1/middleware/spec.go:46 +0x18c
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0xc00073e480, {0x1337760, 0xc00019a7e0}, 0xc000972d00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/rs/cors.(*Cors).Handler.func1({0x1337760, 0xc00019a7e0}, 0xc000972d00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0xc0007fc300, {0x1337760, 0xc00019a7e0}, 0x7fe68db55b30)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | github.com/prometheus/alertmanager/api.(*API).limitHandler.func1({0x1337760, 0xc00019a7e0}, 0xc000972d00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/app/api/api.go:222 +0x1eb
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.HandlerFunc.ServeHTTP(0x0, {0x1337760, 0xc00019a7e0}, 0x0)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2047 +0x2f
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*ServeMux).ServeHTTP(0xc0002b05b3, {0x1337760, 0xc00019a7e0}, 0xc000972d00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2425 +0x149
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.serverHandler.ServeHTTP({0xc0009e5fb0}, {0x1337760, 0xc00019a7e0}, 0xc000972d00)
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:2879 +0x43b
mon_alertmanager.1.rnecgjj0lbld@dm2    | net/http.(*conn).serve(0xc00063d2c0, {0x1341218, 0xc0006c5fb0})
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:1930 +0xb08
mon_alertmanager.1.rnecgjj0lbld@dm2    | created by net/http.(*Server).Serve
mon_alertmanager.1.rnecgjj0lbld@dm2    | 	/usr/local/go/src/net/http/server.go:3034 +0x4e8
```

Running latest version of all components involved.

**Comment by prologic** [comment] 2022-04-12 00:48
Also the [Published Dashboard](https://grafana.com/grafana/dashboards/8010) for this plugin seems a bit off, I've had to make modification to it for it to make any sense at all, or even remotely work (ignoring the `alertname` differences in my setup).

**Comment by zuchka** [comment] 2022-04-12 20:08
Thanks for creating this issue, @prologic 

the datasource in question is not maintained by Grafana, but is a third-party resource:

https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource

Have you tried making an issue in that repo?  Will close this for now, but if you believe that the issue is outside the plugin and with OSS grafana's codebase, let us know how to reproduce and we'll reopen. Thank you! 👍

**Closed by zuchka** 2022-04-12 20:08 UTC

**Comment by prologic** [comment] 2022-04-12 21:42
@zuchka Actually I believe this is an issue with Prometheus's AlertManager. So I filed the issue there. Thanks!

See https://github.com/prometheus/alertmanager/issues/2888
