### ISSUE TITLE
Singlestat Options Thresholds on String

### ISSUE THREAD

**Issue by SongYg** [grafana/grafana#12420] opened 2018-06-27 04:35 UTC
Hello, I'm new to grafana v5.1 and I am trying to figure out how to get the singlestat panel to display different colors with different string values. For example,  it shows green color when string is "success" and it shows red color when string is "fail".
When I did it, in "Options" I made Unit as none. But the threshold field accepts int or float ranges. How to set it to string?
<img width="963" alt="monitor_single_stat" src="https://user-images.githubusercontent.com/13520404/41953131-7df6c86c-7a06-11e8-861c-a17529b843e0.png">

**Comment by marefr** [comment] 2018-06-27 07:33
Duplicate of #11418

**Closed by marefr** 2018-06-27 07:33 UTC
