### ISSUE TITLE
Prometheus Ad-Hoc Filter does not support some expressions 

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#16568] opened 2019-04-13 19:46 UTC
**What happened**:

Ad-hoc filters do not work with some expressions

**What you expected to happen**:

For them  to work properly

**How to reproduce it (as minimally and precisely as possible)**:

Use Prometheus expression "up or up"    it will show data with no adhoc filters applied but will show error when ad-hoc filter attempted to be applied

![image](https://user-images.githubusercontent.com/3651746/56084585-fed79e80-5e02-11e9-9b61-0e8db656bded.png)

![image](https://user-images.githubusercontent.com/3651746/56084594-16168c00-5e03-11e9-8358-90af35c8ea5c.png)

**Anything else we need to know?**:

Additionally "opening graph in prometheus" link does not seem to pass expression with ad-hoc filters applied which complicates troubleshooting 

**Environment**:
- Grafana version:

6.1.3

- Data source type & version:

Prometheus 2.7.1

- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment] 2019-04-14 09:14
think dupe of https://github.com/grafana/grafana/issues/16486

**Closed by torkelo** 2019-04-14 09:14 UTC
