### ISSUE TITLE
Alert Templating doesn't apply on OK

### ISSUE THREAD

**Issue by ShaneMalachow** [grafana/grafana#30606] opened 2021-01-25 17:09 UTC
**What happened**:
Webhook alerts firing OK do not template. On an alert fire, ${instance} resolves to the appropriate instance, but whenever returning to OK it just returns `${instance}` as a string, not the variable value itself. 

**What you expected to happen**:
Whenever an alert returns to OK that the alert templating engine still replaces values for the alert returning to OK.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an alert on a graph with a message containing a templated variable `Instance: ${instance}`
2. Trigger an alert (these alerts will template appropriately)
3. Resolve the alert to OK (this alert will return `${instance}` as a string)

**Anything else we need to know?**:
Not certain if this bug is solely due to webhooks or if there's a potential this has not been implemented in the beta.

**Environment**:
- Grafana version: v7.4.0-beta1
- Data source type & version: prometheus v2.24.1
- OS Grafana is installed on: Oracle Linux 7.7 (Docker Engine 19.03.1-ol, containerd v1.2.3, runc v1.0.0-rc5+dev)
- User OS & Browser: MacOS Catalina 10.15.7, Chrome v87.0.4280.141
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment] 2021-01-26 07:25
@wbrowne I remember @papagian also discovering this in the PR review, is there anything we can do here or a limitation of the alerting engine?

**Comment by wbrowne** [comment] 2021-01-28 09:28
This is something I was aware of as a limitation. @papagian just pointed out that we still have that previous alert state in the DB, so there may be something we can do with that. I'll investigate and see what might work

**Comment by marefr** [comment] 2021-03-25 11:06
There's probably many issues related to this, for example #7414

**Comment by dgdevops** [comment] 2021-06-22 10:25
Facing the same issue in 8.0.3 as well, are there any plans to fix this?

**Comment by louij2** [comment] 2021-09-09 13:22
same issue here

**Comment by abiydv** [comment] 2021-09-18 09:14
Is there a way to get the state info in the alert message via templating? Unfortunately could not find it in the documentation.

That could help us implement some workaround while this is fixed.

**Comment by jomacarpe** [comment] 2021-09-20 15:59
Is this bug solved? in which Grafana version?

**Comment by erachenko23** [comment] 2021-09-21 06:24
Actual bug on Grafana v7.5.10 (e72061a129), Prometheus datasource.
Panel legend: {{instance}} 

Alert example:

[Alerting] Probe Success alert
Check interface http://192.168.1.1:9093/checkAddress error
Metric name
http://192.168.1.1:9093/checkAddress
Value 0.000

Resolved:

[OK] Probe Success alert
Check interface ${instance} error

**Comment by wbrowne** [comment] 2021-10-04 12:17
As per the docs:

>Labels that exist from the evaluation of the alert query can be used in the alert rule name and in the alert notification message fields. The alert label data is injected into the notification fields when the alert is in the **alerting** state

The current limitation is that we only know the value of these labels when the alert is firing. More work will be required for this to function across different alert states.

**Comment by sdpoueme** [comment] 2022-02-08 22:35
Hello @armandgrillet do we have an ETA / timeline for resolution ?

**Comment by 52fhy** [comment] 2022-03-14 09:32
The same problem, looking forward to resolving.

**Comment by armandgrillet** [comment] 2022-03-16 20:53
Still planned, ETA is end of April.

**Comment by santihernandezc** [comment] 2022-04-04 22:03
I managed to reproduce the issue and I'm working on a fix.
One thing responsible for this bug is that we're overwriting the alert each time the user updates the dashboard, so previous evaluation data is deleted. I'm currently trying to figure out a way of leaving the `eval_data` untouched so we can use it for parsing alert titles and messages.

**Comment by santihernandezc** [comment] 2022-04-13 20:07
Templates are now parsed when going from Alerting -> OK.
The expected behavior is:
- FIRING: the data used to parse the templates correspond to the series that are violating the alert condition at the moment we make the evaluation and send the notification.
- OK: all series are used since there are none that are violating the condition.

Example: I set up an alert in which two series were causing the alert to fire, then just one, and then all series were OK.
The alert rule name is `Prueba legacy alert: ${instance}`. Note that the notifier is configured to send reminders.

![image](https://user-images.githubusercontent.com/41638679/163261303-1e4fdd79-2cf6-4fb1-8751-89b5c1da4a7c.png)

The docs for legacy alerting have been updated to make this behavior clear.
This fix is going to be part of v8.5.

**Closed by santihernandezc** 2022-04-13 20:07 UTC
Labels: type/bug, prio/high, area/alerting, area/alerting/legacy
