### ISSUE TITLE
Cloudwatch metrics with IDs do not respect "hide" button in query builder

### ISSUE THREAD

**Issue by alexmv** [grafana/grafana#52360] opened 2022-07-15 21:47 UTC
**What happened**:  Adding a Cloudwatch query with an ID makes it appear even when that data is marked as hidden.  This is particularly frustrating as the ID is necessary to build derived metrics in Cloudwatch -- for instance, pull in a metric, give it an id, hide it, and then show `metric_id/60` as a separate line.

https://user-images.githubusercontent.com/28347/179315012-c295a440-07d6-48f1-87b3-690cd57e411a.mov

**What you expected to happen**: The query should stay hidden.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Cloudwatch graph.  Add an ID.  Click the "hide" icon.  The data will stay visible.

**Anything else we need to know?**:

This is a regression since my upgrade from 8.5.3 to 9.0.3.

**Environment**:
- Grafana version: 9.0.3
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: MacOS, Chrome 103.0.5060.53

**Comment by pvincentgf** [comment] 2022-07-19 09:28
I can confirm @alexmv report. CloudWatch queries are no longer taking the "Hidden" option into account since Grafana 9.0.3 (on Grafana Cloud in my case).

**Comment by iwysiu** [comment] 2022-07-25 20:41
Hi, thanks for reporting this bug! It should be fixed in https://github.com/grafana/grafana/pull/52759

**Closed** 2022-07-27 12:46 UTC
Labels: type/bug, datasource/CloudWatch
