### ISSUE TITLE
[Bug] Open a dashboard url cannot switch org automatically

### ISSUE THREAD

**Issue by lcrenix** [grafana/grafana#5111] opened 2016-05-20 08:32 UTC
I have a shared URL that points a dashboard which belongs to org A, and my latest working org is B. Now, I open the URL want to see the dashboard, but grafana cannot switch to the org A automatically, instead, it says "Dashboard not found".

I sure have permissions for both org A and org B.

It annoyed me when sharing dashboards to other people, I always need to explain to them that "you need to switch to the correct org first" and some times, they even don't know which one is the "correct" org.

Hope this can be fixed soon, thx.

**Comment by utkarshcmu** [comment] 2016-05-20 08:37
I guess this can be solved by https://github.com/grafana/grafana/issues/1613

**Comment by bergquist** [comment] 2016-05-20 09:24
Thank you for reporting this!

But I'm closing it since its kind of a dupe of #1613

**Closed by bergquist** 2016-05-20 09:24 UTC
