### ISSUE TITLE
elasticsearch datasource - time shift per metric

### ISSUE THREAD

**Issue by nvtkaszpir** [grafana/grafana#5385] opened 2016-06-18 16:32 UTC
* **I'm submitting a ...**
- [ ] Bug report
- [x] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using?
2.6.0 from .deb repo

- What datasource are you using?
elasticsearch 1.7

- What OS are you running grafana on?
ubuntu 14.04

- What did you do?
Elastic with simple logstash index.
Created panel with a metric with a query: @timestamp:[now-7d/d TO now]
Next, wanted to add new metric with the query: @timestamp:[now-14d/d TO now-7d/d] and added timeshift 7 days.

- What was the expected result?
The only solution is to create another panel with a query and time shift
I really miss the feature that more graphs with metrics could be layered together to visualize better trends

Also shared crosshair is not working in such situation, because it should be rendered with timeshift on other panels

- What happenend instead?
For certain visualizations I was forced to get back to kibana ;)

**Comment by bergquist** [comment] 2016-06-20 06:20
Closing this since its a dupe of https://github.com/grafana/grafana/issues/5385

**Closed by bergquist** 2016-06-20 06:20 UTC

**Comment by nvtkaszpir** [comment] 2016-06-20 06:27
Please fix your link, you referenced this issue:)

**Comment by bergquist** [comment] 2016-06-20 09:12
@nvtkaszpir thanks for spotting! now updated :)
