### ISSUE TITLE
Case (in)sensitivity sqlite -> MySQL

### ISSUE THREAD

**Issue by scaarup** [grafana/grafana#19934] opened 2019-10-21 11:35 UTC
**What happened**:
Trying to migrate from sqlite to MySQL is hard because sqlite is case sensitive and my MySQL is not. In my sqlite's tag table, I have this following:

```
sqlite> select * from tag;
1|dt|
2|DT|
3|D2|
4|d2|
```
The DDL for the same table in my case insensitive MySQL:
```
CREATE TABLE `tag` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UQE_tag_key_value` (`key`,`value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
Which makes it impossible to migrate, since "DT" and "dt" is violating the unique index on key,value.

**What you expected to happen**:
The UI permits me to create tags which only differs in case. I am not sure this is a good idea and it certainly makes migrating to MySQL harder.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4
- Data source type & version:
- OS Grafana is installed on: RHEL 7.7
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2019-10-21 11:43
Duplicate of #12549

**Comment by marefr** [comment] 2019-10-21 11:43
Not exactly the same, but very similar.

**Closed by marefr** 2019-10-21 11:43 UTC

**Comment by scaarup** [comment] 2019-10-21 11:44
If you were to handle this in the UI when users are creating tags, you shouldn't close this.

**Comment by marefr** [comment] 2019-10-22 08:16
It's still the underlying problem as in the other issue of how to migrate Grafana instances that have data that looks like you posted, i.e.
```
1|dt|
2|DT|
3|D2|
4|d2|
```
