### ISSUE TITLE
Postgresql creation/migration hang

### ISSUE THREAD

**Issue by alsonkemp** [grafana/grafana#1714] opened 2015-04-03 21:29 UTC
See #1643, too?  FYI, I'm using the grafana/grafana Docker container.

I'm stuck at Starting DB migration, too.  I can use psql to get from inside the running container and to my RDS instance, so the box has access.  And I can run grafana from my dev machine using the RDS instance.  

    # /opt/grafana/current/grafana --config /grafana.ini web
    2015/04/03 20:46:54 [1;32m[I] Starting Grafana[0m
    2015/04/03 20:46:54 [1;32m[I] Version: 2.0.0-beta1, Commit: fb0629a, Build date: 2015-03-30 13:45:02 +0000 UTC[0m
    2015/04/03 20:46:54 [1;32m[I] Config: Loaded from /grafana.ini[0m
    2015/04/03 20:46:54 [1;32m[I] Database: postgres, ConnectionString: user=user password=... host=....us-west-1.rds.amazonaws.com port=5432 dbname=dbname sslmode=disable[0m
    2015/04/03 20:46:54 [1;32m[I] Migrator: Starting DB migration[0m

Any thoughts on what might be causing the hang?  Perhaps it's hanging in mg.x.IsTableExist in migrator.go?

**Comment by alsonkemp** [comment] 2015-04-03 22:04
Hmm... I just switched to sqlite3 and I'm stuck after creating the admin user:

    2015/04/03 22:03:24 [I] Migrator: exec migration id: create index UQE_dashboard_snapshot_delete_key - v5
    2015/04/03 22:03:24 [I] Migrator: exec migration id: create index IDX_dashboard_snapshot_user_id - v5
    2015/04/03 22:03:24 [I] Created default admin user: admin

If I run a second instance of Grafana, it appears to hang at Starting DB migration...

**Comment by torkelo** [comment] 2015-04-04 07:24
@alsonkemp I asked @mag009 to explain how he solved it, I think I remember him saying it was a config issue on IRC, but not what exactly. What ever config issue it should not hang, but just double check what your config changes are.

**Comment by alsonkemp** [comment] 2015-04-06 15:43
@torkelo I just stripped down my .ini file and re-deployed, but I'm still stuck at:

    2015/04/06 15:41:56 [1;32m[I] Migrator: exec migration id: create dashboard_snapshot table v5 #2[0m
    2015/04/06 15:41:56 [1;32m[I] Migrator: exec migration id: create index UQE_dashboard_snapshot_key - v5[0m
    2015/04/06 15:41:56 [1;32m[I] Migrator: exec migration id: create index UQE_dashboard_snapshot_delete_key - v5[0m
    2015/04/06 15:41:56 [1;32m[I] Migrator: exec migration id: create index IDX_dashboard_snapshot_user_id - v5[0m
2015/04/06 15:41:56 [1;32m[I] Created default admin user: admin[0m

**Comment by torkelo** [comment] 2015-04-06 17:09
I found the cause for this today, fixed in master. A bug the Go ini file config package grafana uses can cause a deadlock on the config object. The bug for me only happened when I removed or had en empty setting in auth.github or auth.google  section, but could happen  when there is an empty config key in any ini section with a dot (log.file, etc).

I have pushed a new beta2 build with the fix, can download here http://grafana.org/download/builds  or you can try to track down the blank config key that is causin the hang

**Closed by torkelo** 2015-04-06 17:09 UTC
