### ISSUE TITLE
The filterByValue in transformations have An unexpected error happened with "TypeError: Cannot read property 'type' of undefined"

### ISSUE THREAD

**Issue by hwygithub** [grafana/grafana#34613] opened 2021-05-25 03:23 UTC
**What happened**:
when I use transformations filterByValue set the value and saved, I try to open transformations find web crashed with stack ：

![image](https://user-images.githubusercontent.com/14356413/119434984-e9f0c780-bd4b-11eb-99e2-e33947dca0b3.png)

**What you expected to happen**:
open ok

**How to reproduce it (as minimally and precisely as possible)**:
I can recovery by edit the plane json and delete the filterByValue 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta2 (2021-05-20)
- Data source type & version: 
- OS Grafana is installed on: linux
- User OS & Browser: macOS , edge browser
- Grafana plugins: transforms
- Others:

**Comment by Elfo404** [comment] 2021-05-25 09:18
Hello @hwygithub thanks for reporting this and thanks for testing out the beta!

I can reproduce this quite easily, definitely a bug on our side. looping in @grafana/grafana-frontend-platform

**Comment by torkelo** [comment] 2021-05-26 07:33
dupe of https://github.com/grafana/grafana/issues/34626

**Closed by torkelo** 2021-05-26 07:33 UTC
Labels: area/frontend, area/transformations, type/bug
