### ISSUE TITLE
Transformations: Threshold from "Config from query results" overrides base value

### ISSUE THREAD

**Issue by colega** [grafana/grafana#91870] opened 2024-08-14 07:40 UTC
### What happened?

Context: I have a value that is "bad" when it's lower than given treshold, and "good" when it's higher. I.e., my threshold colors go red->green. My threshold is dynamic, so I decided to use "Config from query results".

I defined a threshold through the "Config from query results" transformation, setting green color from given threshold.

In the panel settings, I set red as the base color.

However, the **base color is "green"** regardless of any settings I can find, so my threshold doesn't work.

(I also faced this bug trying to set base color as "blue" to be more accessible for colorblind people).

I also tried adding another query, with constant 0 value, and add another tranformation setting that as "red" threshold, but it didn't work.

### What did you expect to happen?

I expected the base color to be the one from the panel settings, or maybe configurable, or maybe built from multiple config transformations.

### Did this work before?

I have no idea.

### How do we reproduce it?

1. Create a singlestat panel
1. Set color theme to threshold
1. Set threshold base color as red
1. Define a prometheus query `vector(10)` as "query"
1. Define a prometheus query `vector(100)` as "treshold"
1. Add a "Config from query results" transformation, based on "treshold" result to be considered as "treshold" with green color.

Observe that "query" result is green (unless you can't distinguish red/green), instead of the expected red.

### Environment (with versions)?

Grafana: Grafana v11.2.0-74515 (b4126d3bce)
OS: Mac OS
Browser: Arc

### Grafana platform?

I use Grafana Cloud

**Comment by mrmeloman** [comment] 2024-11-05 07:08
Can confirm it's not specific to Grafana Cloud, having this issue on the standalone Ubuntu app

**Comment by gelicia** [comment] 2024-11-19 19:43
Duplicate of https://github.com/grafana/grafana/issues/90201

**Closed by gelicia** 2024-11-19 19:43 UTC
Labels: type/bug, area/transformations
