### ISSUE TITLE
[Bug] Render graphic from snapshot lost all colors from legend

### ISSUE THREAD

**Issue by Arkote** [grafana/grafana#7381] opened 2017-01-27 08:06 UTC
Please prefix your title with [Bug] or [Feature request]
For question please check [Support Options](http://grafana.org/support/). **Do not** open a github issue

Please include this information:
- What Grafana version are you using?
tested in 3+ and 4+ versions, reproduce in http://play.grafana.org/
- What datasource are you using?
influxDB\demo datasource
- What OS are you running grafana on?
tested on windows\unix
- What did you do?
1) I got snapshot from this dashboard: http://play.grafana.org/dashboard/db/1-promcon-dashboard?panelId=1&fullscreen
2) This snapshot: http://play.grafana.org/dashboard/snapshot/aj5u5YeaQBX6M9pGflivdrek96BsbMb2
3) Try to render image from this graph, and you get the image without legend colors: http://play.grafana.org/render/dashboard-solo/snapshot/aj5u5YeaQBX6M9pGflivdrek96BsbMb2?from=1484905496563&to=1484907296563&panelId=1&width=1000&height=500
- What was the expected result?
- What happened instead?
lost legend colors.

**IMPORTANT** 
If it relates to *metric data viz*:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

If it relates to *alerting*
- An image of the test execution data fully expanded.

same my closed issue https://github.com/grafana/grafana/issues/6616 is ignored.

**Comment by torkelo** [comment] 2017-01-27 09:30
The issue is that the rendering complete's so quickly (due to no metric queries having to be issued), and the fonts have yet to finish loading when the image is captured.

**Comment by rburchell** [comment] 2017-04-26 13:58
I have what I assume is a similar problem. Slightly different in that I see legend colors, but no text:

![image](https://cloud.githubusercontent.com/assets/125863/25438270/313871a0-2a99-11e7-9975-35ed8b1fddba.png)

**Comment by torkelo** [comment] 2017-04-26 14:01
try installing font packages on your server http://docs.grafana.org/installation/rpm/#server-side-image-rendering

**Comment by Arkote** [comment] 2017-05-31 06:39
@torkelo Hi, is there progress on this bug with the loss of colors? On play.grafana.org he is still reapiting.

**Comment by torkelo** [comment] 2018-05-29 06:38
this seems to be fixed in v5.

**Closed by torkelo** 2018-05-29 06:38 UTC
Labels: P3: important, help wanted, type: bug

**Comment by Jendem** [comment] 2020-05-14 11:07
This bug is back in Grafana v6.7.3 (a04ef6cefc). Grafana is installed on Windows Server 2016 Standard (64 bit). Strangely, the colors in the legend are gone in some panels, ad ok in other.

**Comment by amitmalhotra-cell** [comment] 2020-05-17 07:16
@torkelo : Is there any update on this issue ? If legends missing colors , then in grafana email alerts , image is of no help .

**Comment by Jendem** [comment] 2020-05-17 10:58
I found a workaround: if I write anything in the description field of the panel, the colors are rendered ok in the legend of the png.
