### ISSUE TITLE
Explorer renders logs with extra 'frame' in Firefox

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#22968] opened 2020-03-23 14:12 UTC
**What happened**:
Using Firefox (mac os, firfox 74) to view Loki logs in Explorer the logs are rendered inside what looks like an extra nested frame of some sort. The issue is compounded if you actually click on a log event to view details and even more so if you view the context during a search - most of the modal is off the viewport. This does not occur in chrome. The effect is that I can only see a dozen or so log lines and the full page scrolling doesn't work properly.

https://files.slack.com/files-pri/T05675Y01-F010GPW1HA4/image.png

**What you expected to happen**:
Should be able to the full rendered line limit from loki in Explorer, with full page scrolling.

**How to reproduce it (as minimally and precisely as possible)**:
easiest to see the issue by visiting a Loki data source in explore and doing any sort of query, the visible log lines will render inside an extra frame.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.0 and 6.7.1
- Data source type & version: Loki 1.3.0
- OS Grafana is installed on: Ubunutu 18.04
- User OS & Browser: Mac OSX Catalina, Firefox 74.0
- Grafana plugins: n/a
- Others:

**Comment by Estrax** [comment] 2020-05-03 21:04
@ivanahuckova can you check this one whenever you have some time? I don't have an access to macOS right now.

**Comment by ivanahuckova** [comment] 2020-05-04 09:21
@Estrax I have tested this with Grafana 6.7.1 and 6.6.0 on Mac OSX Catalina and with Firefox 74.0 and I couldn't reproduce the issue.

 Grafana 6.7.1 - without extra frame: 
![image](https://user-images.githubusercontent.com/30407135/80950376-0004b080-8df6-11ea-871b-eaa6756eba68.png)
 
Grafana 6.6.0 - without extra frame: 
![image](https://user-images.githubusercontent.com/30407135/80952075-5fb08b00-8df9-11ea-8139-8af1fa090a90.png)

**Comment by ivanahuckova** [comment] 2020-05-04 09:26
I have also tested with smaller number of results (in posted image, it is 13 logs), but works as expected as well. 
![image](https://user-images.githubusercontent.com/30407135/80952542-1c0a5100-8dfa-11ea-9098-e2d9db50d45c.png)

**Comment by Estrax** [comment] 2020-05-04 09:30
@ivanahuckova Thanks for checking it out. So it works exactly the same as under Linux.

Closing this issue then.

**Closed by Estrax** 2020-05-04 09:30 UTC
Labels: area/explore

**Comment by Estrax** [comment] 2020-05-07 00:23
Noticed that I forgot to check `wrap lines` option and it was actually causing this issue. Gonna be fixed in #24205. Thanks @zswanson for reporting!

**Comment by zswanson** [comment] 2020-06-12 18:08
@Estrax This is occurring again but now only if you turn *off* the 'wrap lines' option in Explore, using 7.0.3. I've opened #25571 for this new behavior
