### ISSUE TITLE
 TableV7 needing: two features of V6 and table cell gauge stacking

### ISSUE THREAD

**Issue by jayemce** [grafana/grafana#25969] opened 2020-07-01 09:34 UTC
We are using your excellent tool for "compliance reporting", hence mainly true/false reports of configuration standards on IT infrastructure.
We have dashboards showing the compliance status (in %, in numbers, etc.) per data center, locations, infrastructure groups, applications, etc. We can dive from global to a single item (device, app, etc.) and single check.

When we want to understand, why a check of a particular item is red, we can extract it from the evidence table. That evidence table contains, things like time of check, DC, item name or IP address, checked configuration standard, etc ... and the most important for our operations team, the evidence. The evidence is a short but multi line summary of the detected configuration drift; it may contain additional instructions, etc.

* Feature 1/2: "preserveFormat": true
   * How evidence looks on tableV7:
     One very long string on one line that does not fit in the cell. It makes it impossible to read, copy/paste, etc.
     -> Does not exist: "preserveFormat": true

   * How evidence looks on tableV6:
     Format is preserved, the cell width adapts to the content. Beautiful!
     -> This is achieved with setting:  "preserveFormat": true

* Feature 2/2: "panel pages"
   In V6, table panels contain numbered pages (per "pageSize") at the bottom of the panel making it very comfortable
   to read and scroll.
   In V7, table panels don't contain pages, instead you scroll to infinity and additionally you can't see the remaining records
   once scrolled to the bottom. To see additional records the table must be resized ... very awkward when tables are long ...

* Feature 3/3: stacking cell gauges with different colors (thresholds)
   I really like the feature of cell gauges. I immediately adopted this feature and I'm representing compliant compliance results
  in % with a gauge. Additionally I also use the gauge on the cell to the right to represent the non-compliant results in %.
  Being able though, to stack both values and to represent them with two different colors in one cell, would make this
  feature simply "complete"

Feature number 3 is a beautiful goody but the features 1 and 2 hold us back from replacing all V6 tables with V7 tables.

I would be very happy to showcase our compliance reporting solution to you if that would help to fully understand our request and if it can help to accelerate for a solution.

Best regards,
Jesús

**Comment by torkelo** [comment] 2020-07-01 10:25
1) duplicate of https://github.com/grafana/grafana/issues/25623 
2) can you open a seperate feature request for pagination? Not sure I understand why it's better, you can scroll down and see all records without resize 
3) I do not understand the stacking feature request. A cell can only visualize one value, not sure what you want to stack

**Closed by torkelo** 2020-07-01 10:25 UTC

**Comment by jayemce** [comment] 2020-07-02 10:40
![tableV7stackingrequest](https://user-images.githubusercontent.com/11334355/86348559-1eedba80-bc60-11ea-9996-936b0c9d576d.png)

With regards to stacking, pls see attachment.
The two gauge columns with the % values could be stacked and shown in one single column.

With regards to pagination:
The attachment contains one TID per row. When the TID are unfolded, which is another table, then we have 1446 records per TID per consolidate time groups, hence the table gets really long. With V7 you need to scroll and scroll and when arriving at the bottom you need to resize the panel to allow further scrolling. Instead with pagination, the panel can be as big as one window size and then pressing the paging numbers is much more comfortable then scrolling.
-> Feedback from my operations team using it every day.

thank you for answering that fast!

**Comment by noob2master** [comment] 2021-04-20 12:00
> 1. duplicate of #25623
> 2. can you open a seperate feature request for pagination? Not sure I understand why it's better, you can scroll down and see all records without resize
> 3. I do not understand the stacking feature request. A cell can only visualize one value, not sure what you want to stack

Please tell me how to open a seperate feature request for pagination,thx

**Comment by noob2master** [comment] 2021-04-20 12:03
> 1. duplicate of #25623
> 2. can you open a seperate feature request for pagination? Not sure I understand why it's better, you can scroll down and see all records without resize
> 3. I do not understand the stacking feature request. A cell can only visualize one value, not sure what you want to stack

@torkelo Please tell me how to open a seperate feature request for pagination,thx

**Comment by torkelo** [comment] 2021-04-20 14:04
we already have that
