### ISSUE TITLE
Migration from 5.2.2 is failing

### ISSUE THREAD

**Issue by RestfulBlue** [grafana/grafana#17329] opened 2019-05-28 14:34 UTC
Hey there, we are trying to migrate one of our grafana installation from old version ( 5.2.2)
But when we start grafana 6.1.3 migration is failing with following log errors : 
```
Starting Grafana on port 3000
t=2019-05-28T16:27:57+0300 lvl=info msg="Starting Grafana" logger=server version=6.1.4 commit=fef1733b0 branch=HEAD compiled=2019-04-16T12:04:07+0300
t=2019-05-28T16:27:57+0300 lvl=info msg="Config loaded from" logger=settings file=/opt/cloudera/parcels/GRAFANA-6.1.4-2.4.1/conf/defaults.ini
t=2019-05-28T16:27:57+0300 lvl=info msg="Path Home" logger=settings path=/opt/cloudera/parcels/GRAFANA-6.1.4-2.4.1
t=2019-05-28T16:27:57+0300 lvl=info msg="Path Data" logger=settings path=/opt/cloudera/parcels/GRAFANA-6.1.4-2.4.1/data
t=2019-05-28T16:27:57+0300 lvl=info msg="Path Logs" logger=settings path=/opt/cloudera/parcels/GRAFANA-6.1.4-2.4.1/data/log
t=2019-05-28T16:27:57+0300 lvl=info msg="Path Plugins" logger=settings path=/opt/cloudera/parcels/GRAFANA-6.1.4-2.4.1/data/plugins
t=2019-05-28T16:27:57+0300 lvl=info msg="Path Provisioning" logger=settings path=/opt/cloudera/parcels/GRAFANA-6.1.4-2.4.1/conf/provisioning
t=2019-05-28T16:27:57+0300 lvl=info msg="App mode production" logger=settings
t=2019-05-28T16:27:57+0300 lvl=info msg="Ldap enabled, reading config file" logger=ldap file=/opt/cloudera/parcels/GRAFANA-6.1.4-2.4.1/conf/ldap.toml
t=2019-05-28T16:27:57+0300 lvl=info msg="Initializing HTTPServer" logger=server
t=2019-05-28T16:27:57+0300 lvl=info msg="Initializing SqlStore" logger=server
t=2019-05-28T16:27:57+0300 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=postgres
t=2019-05-28T16:27:57+0300 lvl=info msg="Starting DB migration" logger=migrator
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="create user table"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="add unique index user.login"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="add unique index user.email"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_login - v1"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_email - v1"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="Rename table user to user_v1 - v1"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="create user table v2"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_login - v2"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_email - v2"
t=2019-05-28T16:27:57+0300 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
t=2019-05-28T16:27:57+0300 lvl=eror msg="Executing migration failed" logger=migrator id="copy data_source v1 to v2" error="pq: column \"account_id\" does not exist"
t=2019-05-28T16:27:57+0300 lvl=eror msg="Exec failed" logger=migrator error="pq: column \"account_id\" does not exist" sql="INSERT INTO \"user\" (\"id\"\n, \"version\"\n, \"email\"\n, \"salt\"\n, \"company\"\n, \"created\"\n, \"updated\"\n, \"login\"\n, \"name\"\n, \"password\"\n, \"rands\"\n, \"org_id\"\n, \"is_admin\") SELECT \"id\"\n, \"version\"\n, \"email\"\n, \"salt\"\n, \"company\"\n, \"created\"\n, \"updated\"\n, \"login\"\n, \"name\"\n, \"password\"\n, \"rands\"\n, \"account_id\"\n, \"is_admin\" FROM \"user_v1\""
t=2019-05-28T16:27:57+0300 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: pq: column \"account_id\" does not exist"
```

And it looks like there is not account_id column in table user. 
I was looking at sql in migration_log table, and it also does not create required column in create table statements :(

**Comment by marefr** [comment] 2019-05-28 14:36
Duplicate of #16720

**Comment by torkelo** [comment] 2019-05-28 14:36
duplicate of https://github.com/grafana/grafana/issues/16720

**Closed by torkelo** 2019-05-28 14:36 UTC
Labels: type/duplicate
