### ISSUE TITLE
[Feature Request] Implement retention period for internal annotations

### ISSUE THREAD

**Issue by fhemberger** [grafana/grafana#10618] opened 2018-01-25 15:13 UTC
Please include this information:
- What Grafana version are you using?
**4.6.3**

- What datasource are you using?
**Grafana**

Please add a method to limit the retention time for annotations stored in Grafana's native annotation storage. So far, this seems to be implemented only as a [manual step](https://community.grafana.com/t/annotation-retention-period/2614) for alerts, but not for regular annotations and not in an automated manner.

**Comment by bergquist** [comment] 2018-01-25 21:43
To fix this issue we need to solve two problems.
1) Cleaning up alert annotations. Which can be solved the same way as we solved [dashboard versions](https://github.com/grafana/grafana/issues/9671). 
2) Cleaning up other annotations from the annotation table. Which can be solved be deleting all annotations `Where type = ''` and older than X days. 

Both should be triggered from https://github.com/grafana/grafana/blob/master/pkg/services/cleanup/cleanup.go#L48

**Comment by bergquist** [comment] 2018-01-25 21:46
:man_facepalming: dupe of https://github.com/grafana/grafana/issues/8224

**Closed by bergquist** 2018-01-25 21:46 UTC
Labels: comp: alerting, comp: annotations, help wanted
