### ISSUE TITLE
Unable to scroll properly in mobile device 

### ISSUE THREAD

**Issue by mvkarthikeyan** [grafana/grafana#21015] opened 2019-12-11 07:03 UTC
**Steps to reproduce**: open any dashboard  which is editable in mobile device and try to scroll 

**Actual Result**: the panels are getting rearranged 

**Expected Result** : scroll through the dashboard 

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: 6.5.0
- Data source type & version: NA
- User OS & Browser: OnePlus 3 (Chrome)
- Others: can we lock the dashboard in mobile devices ?

**Comment by marefr** [comment] 2019-12-11 23:05
Duplicate of #17768

**Comment by marefr** [comment] 2019-12-11 23:05
Fix will be included in v6.6.

**Closed by marefr** 2019-12-11 23:05 UTC
