### ISSUE TITLE
opentsdb dashboards bug

### ISSUE THREAD

**Issue by JingxuanC** [grafana/grafana#89083] opened 2024-06-12 02:39 UTC
### What happened?

After I upgraded grafana from 10.3.0 to 11.0.0, some opentsdb dashbords had some issues. The query should be opentsdb, but it is prometheus instead.

### What did you expect to happen?

![image](https://github.com/grafana/grafana/assets/56199250/8b3261d2-05b9-4c72-96a5-043883a9e841)

### Did this work before?

grafana worked properly until the upgrade to 11.0

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

A downloaded binary

### Datasource(s)?

opentsdb

**Comment by alyssabull** [comment] 2024-08-22 17:47
Hi @JingxuanC - can you provide me with some more details? What was the query in v10.3.0 and what is the query now in v11.0.0?

**Comment by alyssabull** [comment] 2024-08-22 19:48
@grafana/dashboards-squad - looping you in here to see if you know why this issue might be occuring.

**Comment by oscarkilhed** [comment] 2024-08-23 06:34
Without some more info we will not be able to find out what's going on here. If you click the menu at the top left corner of the panel and click `more` > `get help` you can copy a debug dashboard that we can use to hopefully reproduce the error on our end.

**Comment by aangelisc** [comment] 2024-09-06 15:35
Hi @JingxuanC, I'm going to close this but if the issue is still occurring please follow the steps suggested by @oscarkilhed and reopen the issue 😊

**Closed by aangelisc** 2024-09-06 15:35 UTC
Labels: datasource/OpenTSDB, needs more info, prio/low, effort/none, triage/needs-confirmation, team/grafana-dashboards
