### ISSUE TITLE
Users with Editor role are able to save over Provisioned dashboard.

### ISSUE THREAD

**Issue by ckyongrtl** [grafana/grafana#44829] opened 2022-02-03 12:20 UTC
How to reproduce:

- Have a provisioned dashboard available (updates from UI turned off).
- Log in as a user with the Editor role.
- Open the dashboard and add a panel.
- Attempt to save through the 'Save' button. The dialog telling you that you cannot save over a provisioned dashboard appears.
- Copy the JSON in the dialog.
- Go to the dashboard's `Settings > JSON Model` and paste the copied JSON in there.
- Save changes (**not** Save Dashboard or Save As)
- Go back to the dashboard.

**What happened**:
- The changes are somehow persisted to Grafana's DB, and the changes remain on the dashboard, even after refreshing.
- A new version is created in the `Settings > Version` section. Notably: we cannot revert to this version, as the dashboard is provisioned.

**What you expected to happen**:
- Change is not persisted to the database.
- No new version is created.

**How to reproduce it (as minimally and precisely as possible)**:
See above, but in short: edit the dashboard through the JSON Model, and press Save Changes.

**Anything else we need to know?**:
Our Grafana instance is running on a Kubernetes cluster. Only when we restart the container, then the dashboards are restored back to their provisioned state. It is interesting to see that the dashboard is not automatically updated through the configmap that originally provisioned the dashboard (as that one didn't actually change).

**Environment**:
- Grafana version: v8.0.5 (cbb2aa5001)

In order to prevent problems, we've temporarily set our users to only be granted the Viewer role, but this prevents our users from creating new temporary dashboards for testing purposes. We'd like the provisioned dashboards to always remain unchanged unless we modify our config files.

**Comment by marefr** [comment] 2022-02-03 18:01
Duplicate of #26620

**Comment by marefr** [comment] 2022-02-03 18:01
Fix included in upcoming 8.4 release

**Closed by marefr** 2022-02-03 18:01 UTC
