### ISSUE TITLE
MSTeams Test Alert works but Actual alert not

### ISSUE THREAD

**Issue by vient28** [grafana/grafana#23222] opened 2020-03-31 10:26 UTC
**What happened**:
Alerts are not sent to MSTeams Channel with error context deadline exceeded
**What you expected to happen**:
Alerts are sent to MSTeams Channel
**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:
MSTeams Test Alerts are working but the actual alerts are not
**Environment**:
- Grafana version: v6.5.3
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment] 2020-03-31 15:48
Please upgrade, was a lot of fixes related to alerting and image rendering in v6.6.0. See [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#660-beta1-2020-01-20)

**Comment by marefr** [comment] 2020-03-31 15:49
Duplicate of #21018

**Closed by marefr** 2020-03-31 15:48 UTC
